var _combat_projectile_8java =
[
    [ "com.runehive.game.world.entity.combat.projectile.CombatProjectile", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1projectile_1_1_combat_projectile.html", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1projectile_1_1_combat_projectile" ],
    [ "com.runehive.game.world.entity.combat.projectile.CombatProjectile.ProjectileBuilder", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1projectile_1_1_combat_projectile_1_1_projectile_builder.html", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1projectile_1_1_combat_projectile_1_1_projectile_builder" ]
];