var _phoenix_necklace_listener_8java =
[
    [ "com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1attack_1_1listener_1_1item_1_1_phoenix_necklace_listener.html", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1attack_1_1listener_1_1item_1_1_phoenix_necklace_listener" ]
];