var _private_message_list_status_8java =
[
    [ "com.runehive.game.world.entity.mob.player.relations.PrivateMessageListStatus", "enumcom_1_1runehive_1_1game_1_1world_1_1entity_1_1mob_1_1player_1_1relations_1_1_private_message_list_status.html", "enumcom_1_1runehive_1_1game_1_1world_1_1entity_1_1mob_1_1player_1_1relations_1_1_private_message_list_status" ]
];