var _scythe_of_vitur_strategy_8java =
[
    [ "com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1strategy_1_1player_1_1custom_1_1_scythe_of_vitur_strategy.html", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1strategy_1_1player_1_1custom_1_1_scythe_of_vitur_strategy" ]
];