var _seers_climb_interaction_8java =
[
    [ "com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction", "interfacecom_1_1runehive_1_1content_1_1skill_1_1impl_1_1agility_1_1obstacle_1_1impl_1_1_seers_climb_interaction.html", "interfacecom_1_1runehive_1_1content_1_1skill_1_1impl_1_1agility_1_1obstacle_1_1impl_1_1_seers_climb_interaction" ]
];