var _seers_jump_gap_interaction2_8java =
[
    [ "com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction2", "interfacecom_1_1runehive_1_1content_1_1skill_1_1impl_1_1agility_1_1obstacle_1_1impl_1_1_seers_jump_gap_interaction2.html", "interfacecom_1_1runehive_1_1content_1_1skill_1_1impl_1_1agility_1_1obstacle_1_1impl_1_1_seers_jump_gap_interaction2" ]
];