var _trident_of_the_swamp_strategy_8java =
[
    [ "com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1strategy_1_1player_1_1custom_1_1_trident_of_the_swamp_strategy.html", "classcom_1_1runehive_1_1game_1_1world_1_1entity_1_1combat_1_1strategy_1_1player_1_1custom_1_1_trident_of_the_swamp_strategy" ]
];