RuneHive-Game: com.runehive.fs.util.ByteBufferUtil Class Reference
com.runehive.fs.util.ByteBufferUtil Class Reference
A static-utility class containing extension or helper methods for ByteBuffers.
Static Public Member Functions
static String decodeStringCp1252 (ByteBuffer buffer, int var1, int var2)
static byte[] get (ByteBuffer buffer, int length)
Reads length bytes from the specified ByteBuffer.
static String getJString (ByteBuffer buffer)
Gets a newline-terminated String from the specified ByteBuffer.
static int getMedium (ByteBuffer buffer)
Gets a 24-bit medium integer from the specified ByteBuffer, this method does not mark the ByteBuffers current position.
static int getSmart (final ByteBuffer buffer)
Reads a 'smart' (either a byte or short depending on the value) from the specified buffer.
static String getString (ByteBuffer buffer)
Gets a null-terminated String from the specified ByteBuffer.
static String getString (ByteBuffer buffer, char terminator)
Gets a String from the specified ByteBuffer, the ByteBuffer will continue to get until the specified terminator is reached.
static void putSmart (ByteBuffer buffer, int value)
Puts a 'smart' (either a byte or short.
static String readStringCp1252NullTerminated (ByteBuffer buffer)
Static Public Attributes
static final char[] cp1252AsciiExtension = new char[]{'€', '\u0000', '‚', 'ƒ', '„', '…', '†', '‡', 'ˆ', '‰', 'Š', '‹', 'Œ', '\u0000', 'Ž', '\u0000', '\u0000', '‘', '’', '“', '”', '•', '–', '—', '˜', '™', 'š', '›', 'œ', '\u0000', 'ž', 'Ÿ'}
static final char DEFAULT_STRING_TERMINATOR = '\0'
The default String terminator, equal to 0 and otherwise known as the 'null' String terminator.
static final char J_STRING_TERMINATOR = '\n'
The terminator used within the client, equal to 10 and otherwise know as the Jagex String terminator.
Private Member Functions
ByteBufferUtil ()
Sole private constructor to discourage instantiation of this class.
Detailed Description
A static-utility class containing extension or helper methods for ByteBuffers.
Author
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Definition at line 12 of file ByteBufferUtil.java.
Constructor & Destructor Documentation
ByteBufferUtil()
com.runehive.fs.util.ByteBufferUtil.ByteBufferUtil () private
Sole private constructor to discourage instantiation of this class.
Definition at line 169 of file ByteBufferUtil.java.
{
    }
Member Function Documentation
decodeStringCp1252()
String com.runehive.fs.util.ByteBufferUtil.decodeStringCp1252 (ByteBuffer buffer, int var1, int var2) static
Definition at line 69 of file ByteBufferUtil.java.
{
        char[] var3 = new char[var2];
        int var4 = 0;
        for(int var5 = 0; var5 < var2; ++var5) {
            int var6 = buffer.get(var5 + var1) & 255;
            if (var6 != 0) {
                if (var6 >= 128 && var6 < 160) {
                    char var7 = cp1252AsciiExtension[var6 - 128];
                    if (var7 == 0) {
                        var7 = '?';
                    }
                    var6 = var7;
                }
                var3[var4++] = (char)var6;
            }
        }
        return new String(var3, 0, var4);
    }
References cp1252AsciiExtension.
Referenced by readStringCp1252NullTerminated().
get()
byte[] com.runehive.fs.util.ByteBufferUtil.get (ByteBuffer buffer, int length) static
Reads length bytes from the specified ByteBuffer.
Parameters
buffer The ByteBuffer to read from.
length The amount of bytes to read.
Returns
The read bytes.
Definition at line 102 of file ByteBufferUtil.java.
{
        byte[] data = new byte[length];
        buffer.get(data);
        return data;
    }
getJString()
String com.runehive.fs.util.ByteBufferUtil.getJString (ByteBuffer buffer) static
Gets a newline-terminated String from the specified ByteBuffer.
Parameters
buffer The ByteBuffer to read from.
Returns
The newline-terminated String.
Definition at line 53 of file ByteBufferUtil.java.
{
        return getString(buffer, J_STRING_TERMINATOR);
    }
References getString(), and J_STRING_TERMINATOR.
getMedium()
int com.runehive.fs.util.ByteBufferUtil.getMedium (ByteBuffer buffer) static
Gets a 24-bit medium integer from the specified ByteBuffer, this method does not mark the ByteBuffers current position.
Parameters
buffer The ByteBuffer to read from.
Returns
The read 24-bit medium integer.
Definition at line 33 of file ByteBufferUtil.java.
{
        return (buffer.getShort() & 0xFFFF) << 8 | buffer.get() & 0xFF;
    }
Referenced by com.runehive.fs.cache.archive.Archive.decode(), com.runehive.fs.cache.decoder.ObjectDefinitionDecoder.decode(), com.runehive.fs.cache.Index.decode(), and com.runehive.fs.cache.Sector.decode().
getSmart()
int com.runehive.fs.util.ByteBufferUtil.getSmart (final ByteBuffer buffer) static
Reads a 'smart' (either a byte or short depending on the value) from the specified buffer.
Parameters
buffer The buffer.
Returns
The 'smart'.
Definition at line 138 of file ByteBufferUtil.java.
{
        final int position = buffer.position();
        if (position >= buffer.limit()) {
            return 0;
        }
        final int peek = buffer.get(position) & 0xFF;
        if (peek < 128) {
            return buffer.get() & 0xFF;
        }
        return (buffer.getShort() & 0xFFFF) - 32768;
    }
Referenced by com.runehive.fs.cache.decoder.RegionDecoder.parseGameObject().
getString() [1/2]
String com.runehive.fs.util.ByteBufferUtil.getString (ByteBuffer buffer) static
Gets a null-terminated String from the specified ByteBuffer.
Parameters
buffer The ByteBuffer to read from.
Returns
The null-terminated String.
Definition at line 43 of file ByteBufferUtil.java.
{
        return getString(buffer, DEFAULT_STRING_TERMINATOR);
    }
References DEFAULT_STRING_TERMINATOR, and getString().
Referenced by getJString(), and getString().
getString() [2/2]
String com.runehive.fs.util.ByteBufferUtil.getString (ByteBuffer buffer, char terminator) static
Gets a String from the specified ByteBuffer, the ByteBuffer will continue to get until the specified terminator is reached.
We use a ByteArrayOutputStream as it is self expanding. We don't want to waste precious time determining a fixed length for the String.
Parameters
buffer The ByteBuffer to read from.
terminator The terminator which denotes when to stop reading.
Returns
The read String.
Definition at line 119 of file ByteBufferUtil.java.
{
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        for (; ; ) {
            int read = buffer.get() & 0xFF;
            if (read == terminator) {
                break;
            }
            os.write(read);
        }
        return new String(os.toByteArray());
    }
putSmart()
void com.runehive.fs.util.ByteBufferUtil.putSmart (ByteBuffer buffer, int value) static
Puts a 'smart' (either a byte or short.
Parameters
buffer The buffer.
value The value to write.
Definition at line 156 of file ByteBufferUtil.java.
{
        if (value < 128) {
            buffer.put((byte) value);
        } else {
            value += 32768;
            buffer.put((byte) (value >> 8));
            buffer.put((byte) value);
        }
    }
readStringCp1252NullTerminated()
String com.runehive.fs.util.ByteBufferUtil.readStringCp1252NullTerminated (ByteBuffer buffer) static
Definition at line 57 of file ByteBufferUtil.java.
{
        int var1 = buffer.position();
        while (true) {
            buffer.position(buffer.position() + 1);
            byte b = buffer.get(buffer.position() - 1);
            if (b == 0) break;
        }
        int var2 =buffer.position() - var1 - 1;
        return var2 == 0 ? "" : decodeStringCp1252(buffer, var1, var2);
    }
References decodeStringCp1252().
Referenced by com.runehive.fs.cache.decoder.ObjectDefinitionDecoder.decode().
Member Data Documentation
cp1252AsciiExtension
final char [] com.runehive.fs.util.ByteBufferUtil.cp1252AsciiExtension = new char[]{'€', '\u0000', '‚', 'ƒ', '„', '…', '†', '‡', 'ˆ', '‰', 'Š', '‹', 'Œ', '\u0000', 'Ž', '\u0000', '\u0000', '‘', '’', '“', '”', '•', '–', '—', '˜', '™', 'š', '›', 'œ', '\u0000', 'ž', 'Ÿ'} static
Definition at line 92 of file ByteBufferUtil.java.
{'€', '\u0000', '‚', 'ƒ', '„', '…', '†', '‡', 'ˆ', '‰', 'Š', '‹', 'Œ', '\u0000', 'Ž', '\u0000', '\u0000', '‘', '’', '“', '”', '•', '–', '—', '˜', '™', 'š', '›', 'œ', '\u0000', 'ž', 'Ÿ'};
Referenced by decodeStringCp1252().
DEFAULT_STRING_TERMINATOR
final char com.runehive.fs.util.ByteBufferUtil.DEFAULT_STRING_TERMINATOR = '\0' static
The default String terminator, equal to 0 and otherwise known as the 'null' String terminator.
Definition at line 24 of file ByteBufferUtil.java.
Referenced by getString().
J_STRING_TERMINATOR
final char com.runehive.fs.util.ByteBufferUtil.J_STRING_TERMINATOR = '\n' static
The terminator used within the client, equal to 10 and otherwise know as the Jagex String terminator.
Definition at line 18 of file ByteBufferUtil.java.
Referenced by getJString().
The documentation for this class was generated from the following file:
java/com/runehive/fs/util/ByteBufferUtil.java