RuneHive-Game: com.runehive.content.ProfileViewer Class Reference
com.runehive.content.ProfileViewer Class Reference
Handles viewing other player's profiles.
Static Public Member Functions
static void open (Player player, Player other)
Opens the profile interface.
static String[] string (Player player)
Gets the main strings to display.
Detailed Description
Handles viewing other player's profiles.
Author
Daniel
Definition at line 20 of file ProfileViewer.java.
Member Function Documentation
open()
void com.runehive.content.ProfileViewer.open (Player player, Player other) static
Opens the profile interface.
Definition at line 42 of file ProfileViewer.java.
{
        if (!other.getPosition().isWithinDistance(player.getPosition(), 26)) {
            player.message("You must get closer to that player if you want to view their profile!");
            return;
        }
        if (player.getCombat().inCombat()) {
            player.send(new SendMessage("You can't view profiles whilst in combat!"));
            return;
        }
        for (int index = 0, string = 51832; index < Skill.SKILL_COUNT; index++, string += 2) {
            Skill skill = other.skills.get(index);
            String color = Integer.toHexString(other.prestige.getPrestigeColor(index));
            player.send(new SendString(skill.getMaxLevel() + "<col=" + color + "></col>/<col=" + color + ">" + skill.getMaxLevel(), string));
        }
        int string = 51902;
        for (String context : string(other)) {
            player.send(new SendString(context, string));
            string += 2;
        }
        if (PlayerRight.isModerator(player) && !player.equals(other)) {
            player.send(new SendString("Manage Player: " + other.getName(), 51811));
            player.send(new SendTooltip("Manage Player: " + other.getName(), 51811));
            player.managing = Optional.of(other);
        } else {
            player.send(new SendString("", 51811));
            player.send(new SendTooltip("", 51811));
        }
        player.send(new SendPlayerIndex(other.getIndex()));
        player.send(new SendString("", 51810));
        player.send(new SendString("</col>Name: <col=FFB83F>" + other.getName(), 51807));
        player.send(new SendString("</col>Rank: <col=FFB83F>" + PlayerRight.getCrown(other) + " " + other.right.getName(), 51808));
        player.send(new SendString("</col>Level: <col=FFB83F>" + other.skills.getCombatLevel(), 51809));
        player.send(new SendMessage("You are now viewing " + other.getName() + "'s profile."));
        player.interfaceManager.open(51800);
    }
References com.runehive.game.world.entity.mob.player.Player.equals(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getCombatLevel(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.entity.Entity.getIndex(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.PlayerRight.getName(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.content.prestige.Prestige.getPrestigeColor(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.PlayerRight.isModerator(), com.runehive.game.world.position.Position.isWithinDistance(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.game.world.entity.mob.player.Player.prestige, com.runehive.game.world.entity.mob.player.Player.right, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.skill.Skill.SKILL_COUNT, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by com.runehive.game.plugin.PluginContext.onClick().
string()
String[] com.runehive.content.ProfileViewer.string (Player player) static
Gets the main strings to display.
Definition at line 23 of file ProfileViewer.java.
{
        return new String[]{
                "Created: ", player.created,
                "Total play time:", Utility.getTime(player.playTime),
                "Networth:", "" + Utility.formatPrice(player.playerAssistant.networth()),
                "Clan:", player.clanChannel == null ? "None" : player.clanChannel.getName(),
                "Total level:", "" + Utility.formatDigits(player.skills.getTotalLevel()),
                "Kills/Deaths/KDR", "" + player.kill + "/" + player.death + "/" + player.playerAssistant.kdr() + "",
                "Current KC:", "" + player.killstreak.streak,
                "Vote Points:", "" + Utility.formatDigits(player.votePoints),
                "Total Votes:", "" + Utility.formatDigits(player.totalVotes),
                "Skilling Points:", "" + Utility.formatDigits(player.skillingPoints),
                "Mage's Arena Points:", "" + Utility.formatDigits(player.mageArenaPoints),
                "Pest Control Points:", "" + Utility.formatDigits(player.pestPoints),
                "Achievements Completed:", "" + AchievementHandler.getTotalCompleted(player) + "",
        };
    }
References com.runehive.game.world.entity.mob.player.Player.clanChannel, com.runehive.game.world.entity.mob.player.Player.created, com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatPrice(), com.runehive.content.clanchannel.channel.ClanChannel.getName(), com.runehive.util.Utility.getTime(), com.runehive.content.achievement.AchievementHandler.getTotalCompleted(), com.runehive.game.world.entity.skill.SkillManager.getTotalLevel(), com.runehive.game.world.entity.mob.player.PlayerAssistant.kdr(), com.runehive.game.world.entity.mob.player.Player.killstreak, com.runehive.game.world.entity.mob.player.Player.mageArenaPoints, com.runehive.game.world.entity.mob.player.PlayerAssistant.networth(), com.runehive.game.world.entity.mob.player.Player.pestPoints, com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.game.world.entity.mob.player.Player.playTime, com.runehive.game.world.entity.mob.player.Player.skillingPoints, com.runehive.game.world.entity.mob.Mob.skills, com.runehive.content.combat.Killstreak.streak, com.runehive.game.world.entity.mob.player.Player.totalVotes, and com.runehive.game.world.entity.mob.player.Player.votePoints.
The documentation for this class was generated from the following file:
java/com/runehive/content/ProfileViewer.java