RuneHive-Game: com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob > Class Template Reference
com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob > Class Template Reference abstract
Public Member Functions
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatType getCombatType ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Detailed Description
Definition at line 21 of file CombatStrategy.java.
Member Function Documentation
attack()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit to apply
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 44 of file CombatStrategy.java.
{
    }
References hit().
block()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit being applied
combatType the combat type for this hit
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 56 of file CombatStrategy.java.
{
    }
References hit().
canAttack()
abstract boolean com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.canAttack (T attacker, Mob defender) abstract
Checks if the attacker can attack the defender.
Parameters
attacker the attacking mob
defender the defending mob
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
canOtherAttack()
boolean com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
Parameters
attacker the attacking mob
defender the defending mob
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 35 of file CombatStrategy.java.
{
        return true;
    }
finishIncoming()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
Parameters
attacker the attacking mob
defender the defending mob
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 80 of file CombatStrategy.java.
{
    }
finishOutgoing()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
Parameters
attacker the attacking mob
defender the defending mob
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 76 of file CombatStrategy.java.
{
    }
getAttackAnimation()
abstract Animation com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getAttackAnimation (T attacker, Mob defender) abstract
getAttackDelay()
abstract int com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getAttackDelay (T attacker, Mob defender, FightType fightType) abstract
getAttackDistance()
abstract int com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getAttackDistance (T attacker, FightType fightType) abstract
Referenced by com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >.withinDistance(), com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.withinDistance(), and com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.withinDistance().
getCombatProjectile()
CombatProjectile com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getCombatProjectile ()
Reimplemented in com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy, and com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.
Definition at line 223 of file CombatStrategy.java.
{
        return null;
    }
getCombatType()
abstract CombatType com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getCombatType () abstract
Reimplemented in com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy, com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy, com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy, com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy, com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy, com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy, com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy, com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy, com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy, com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy, com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy, com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy, com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy, and com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.accuracy().
getEndGraphic() [1/3]
Graphic com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic) static
Definition at line 195 of file CombatStrategy.java.
{
        final int duration = getProjectileDuration(combatProjectile);
        return getEndGraphic(combatProjectile.getEnd(), splash, splashGraphic, duration);
    }
References com.runehive.game.world.entity.combat.projectile.CombatProjectile.getEnd(), getEndGraphic(), and getProjectileDuration().
Referenced by getEndGraphic(), getEndGraphic(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.sendProjectile(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.start(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start().
getEndGraphic() [2/3]
Graphic com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration) static
Definition at line 201 of file CombatStrategy.java.
{
        return getEndGraphic(combatProjectile.getEnd(), splash, splashGraphic, duration);
    }
References com.runehive.game.world.entity.combat.projectile.CombatProjectile.getEnd(), and getEndGraphic().
getEndGraphic() [3/3]
Graphic com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration) static
Definition at line 207 of file CombatStrategy.java.
{
        final Graphic base = splash ? splashGraphic : end.orElse(null);
        return base == null ? null : new Graphic(base.getId(), duration, base.getHeight());
    }
References com.runehive.game.Graphic.getHeight(), and com.runehive.game.Graphic.getId().
getHits()
abstract CombatHit[] com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getHits (T attacker, Mob defender) abstract
getProjectileDuration()
int com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getProjectileDuration (final CombatProjectile combatProjectile) static
Definition at line 186 of file CombatStrategy.java.
{
        final Optional<Projectile> optProjectile = combatProjectile.getProjectile();
        if (optProjectile.isPresent()) {
            final Projectile projectile = optProjectile.get();
            return projectile.getClientTicks();
        }
        return 0;
    }
References com.runehive.game.world.entity.combat.projectile.CombatProjectile.getProjectile().
Referenced by getEndGraphic().
hit()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit to apply
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 48 of file CombatStrategy.java.
{
    }
References hit().
Referenced by com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >.addCombatExperience(), com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.addCombatExperience(), com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.addCombatExperience(), attack(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.attack(), block(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Ranged.getHits(), hit(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.hitEvent(), hitsplat(), missed(), nextMeleeHit(), onDamage(), onDeath(), onKill(), preDeath(), preKill(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), and com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.start().
hitsplat()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 52 of file CombatStrategy.java.
{
    }
References hit().
isAlwaysAccurate()
boolean com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.isAlwaysAccurate ()
Definition at line 227 of file CombatStrategy.java.
{
        return false;
    }
missed()
boolean com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.missed (final Hit... hits) static
Definition at line 214 of file CombatStrategy.java.
{
        for (final Hit hit : hits) {
            if (hit.isAccurate()) {
                return false;
            }
        }
        return true;
    }
References hit().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.start(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start().
nextMagicHit() [1/5]
final CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit (T attacker, Mob defender) protected
Definition at line 97 of file CombatStrategy.java.
{
        int max = getMaxHit(attacker, defender, CombatType.MAGIC);
        return nextMagicHit(attacker, defender, max);
    }
References com.runehive.game.world.entity.combat.CombatType.MAGIC, and nextMagicHit().
Referenced by com.runehive.content.activity.infernomobs.JalAk.Mage.getHits(), com.runehive.content.activity.infernomobs.JalTokJad.MagicAttack.getHits(), com.runehive.content.activity.infernomobs.JaxXil.Ranged.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Ahrim.FireBlast.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.DarkBeast.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.ArmadylSpritualMage.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.BandosSpritualMage.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SaradominPriest.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SpritualMage.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Gowler.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Kraken.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Tentacle.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Shockwave.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.RangedAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothPrime.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.Spinolyp.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.kril.Balfrug.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.TeleGrab.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.TeleGrab.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.IceSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.TeleGrab.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Ranged.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword.getHits(), nextMagicHit(), nextMagicHit(), nextMagicHit(), nextMagicHit(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack.start().
nextMagicHit() [2/5]
CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit (T attacker, Mob defender, CombatProjectile projectile) protected
Definition at line 153 of file CombatStrategy.java.
{
        int max = projectile.getMaxHit();
        return nextMagicHit(attacker, defender, max, projectile);
    }
References nextMagicHit().
nextMagicHit() [3/5]
final CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit (T attacker, Mob defender, int max) protected
Definition at line 122 of file CombatStrategy.java.
{
        int hitDelay = getHitDelay(attacker, defender, CombatType.MAGIC);
        int hitsplatDelay = getHitsplatDelay(CombatType.MAGIC);
        return nextMagicHit(attacker, defender, max, hitDelay, hitsplatDelay);
    }
References com.runehive.game.world.entity.combat.CombatType.MAGIC, and nextMagicHit().
nextMagicHit() [4/5]
CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile) protected
Definition at line 138 of file CombatStrategy.java.
{
        int hitDelay = getHitDelay(attacker, defender, CombatType.MAGIC);
        int hitsplatDelay = getHitsplatDelay(CombatType.MAGIC);
        hitDelay = projectile.getHitDelay().orElse(hitDelay);
        hitsplatDelay = projectile.getHitsplatDelay().orElse(hitsplatDelay);
        return nextMagicHit(attacker, defender, max, hitDelay, hitsplatDelay);
    }
References com.runehive.game.world.entity.combat.CombatType.MAGIC, and nextMagicHit().
nextMagicHit() [5/5]
final CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay) protected
Definition at line 177 of file CombatStrategy.java.
{
        return new CombatHit(FormulaFactory.nextMagicHit(attacker, defender, max), hitDelay, hitsplatDelay);
    }
References com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMagicHit().
nextMeleeHit() [1/5]
CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit (T attacker, Mob defender) protected
Definition at line 87 of file CombatStrategy.java.
{
        int max = getMaxHit(attacker, defender, CombatType.MELEE);
        return nextMeleeHit(attacker, defender, max, false);
    }
References com.runehive.game.world.entity.combat.CombatType.MELEE, and nextMeleeHit().
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.fourthOption(), com.runehive.content.activity.infernomobs.JalAk.CrushMelee.getHits(), com.runehive.content.activity.infernomobs.Jalimkot.Burrow.getHits(), com.runehive.content.activity.infernomobs.Jalimkot.Melee.getHits(), com.runehive.content.activity.infernomobs.JalTokJad.MeleeAttack.getHits(), com.runehive.content.activity.infernomobs.JaxXil.Melee.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.CrushMelee.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.StabMelee.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.CrushMelee.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.StabMelee.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.CrushMelee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.CrushMelee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.SlashMelee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.CrushMelee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.StabMelee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.kril.Tstanon.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MeleeAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Earthquake.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalDagger.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalTentacleWhip.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalWhip.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.hit(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.hitEvent(), nextMeleeHit(), nextMeleeHit(), nextMeleeHit(), nextMeleeHit(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.secondOption(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Melee.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.thirdOption().
nextMeleeHit() [2/5]
CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit (T attacker, Mob defender, int max) protected
Definition at line 104 of file CombatStrategy.java.
{
        int hitDelay = getHitDelay(attacker, defender, CombatType.MELEE);
        int hitsplatDelay = getHitsplatDelay(CombatType.MELEE);
        return nextMeleeHit(attacker, defender, max, hitDelay, hitsplatDelay, false);
    }
References com.runehive.game.world.entity.combat.CombatType.MELEE, and nextMeleeHit().
nextMeleeHit() [3/5]
CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed) protected
Definition at line 110 of file CombatStrategy.java.
{
        int hitDelay = getHitDelay(attacker, defender, CombatType.MELEE);
        int hitsplatDelay = getHitsplatDelay(CombatType.MELEE);
        return nextMeleeHit(attacker, defender, max, hitDelay, hitsplatDelay, multipleHitsAllowed);
    }
References com.runehive.game.world.entity.combat.CombatType.MELEE, and nextMeleeHit().
nextMeleeHit() [4/5]
CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay) protected
Definition at line 160 of file CombatStrategy.java.
{
        return nextMeleeHit(attacker, defender, max, hitDelay, hitsplatDelay, false);
    }
References nextMeleeHit().
nextMeleeHit() [5/5]
CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed) protected
Definition at line 164 of file CombatStrategy.java.
{
        Hit hit = FormulaFactory.nextMeleeHit(attacker, defender, max, multipleHitsAllowed);
        if(hit.getMultipleHits() != null) // && maxHits > 1
            return new CombatHit(hit.getMultipleHits(), hitDelay, hitsplatDelay);
        return new CombatHit(hit, hitDelay, hitsplatDelay);
    }
References hit(), and com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit().
nextRangedHit() [1/5]
final CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit (T attacker, Mob defender) protected
Definition at line 92 of file CombatStrategy.java.
{
        int max = getMaxHit(attacker, defender, CombatType.RANGED);
        return nextRangedHit(attacker, defender, max);
    }
References nextRangedHit(), and com.runehive.game.world.entity.combat.CombatType.RANGED.
Referenced by com.runehive.content.activity.infernomobs.AkMej.Mage.getHits(), com.runehive.content.activity.infernomobs.AkXil.Ranged.getHits(), com.runehive.content.activity.infernomobs.JalAk.Ranged.getHits(), com.runehive.content.activity.infernomobs.JalTokJad.RangedAttack.getHits(), com.runehive.content.activity.infernomobs.MejRah.Ranged.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Ranged.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothSupreme.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.Spinolyp.Ranged.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Ranged.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.Ranged.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.kril.Zakln.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Melee.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.RangedAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.RangedAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.RangedAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.magic.EldritchNightmareStaff.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.magic.VolatileNightmareStaff.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.ArmadylCrossbow.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.Ballista.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.CrawsBow.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DragonThrownaxe.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.MagicShortbow.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.hitsplat(), nextRangedHit(), nextRangedHit(), nextRangedHit(), and nextRangedHit().
nextRangedHit() [2/5]
final CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit (T attacker, Mob defender, CombatProjectile projectile) protected
Definition at line 148 of file CombatStrategy.java.
{
        int max = getMaxHit(attacker, defender, CombatType.RANGED);
        return nextRangedHit(attacker, defender, max, projectile);
    }
References nextRangedHit(), and com.runehive.game.world.entity.combat.CombatType.RANGED.
nextRangedHit() [3/5]
final CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit (T attacker, Mob defender, int max) protected
Definition at line 116 of file CombatStrategy.java.
{
        int hitDelay = getHitDelay(attacker, defender, CombatType.RANGED);
        int hitsplatDelay = getHitsplatDelay(CombatType.RANGED);
        return nextRangedHit(attacker, defender, max, hitDelay, hitsplatDelay);
    }
References nextRangedHit(), and com.runehive.game.world.entity.combat.CombatType.RANGED.
nextRangedHit() [4/5]
final CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile) protected
Definition at line 130 of file CombatStrategy.java.
{
        int hitDelay = getHitDelay(attacker, defender, CombatType.RANGED);
        int hitsplatDelay = getHitsplatDelay(CombatType.RANGED);
        hitDelay = projectile.getHitDelay().orElse(hitDelay);
        hitsplatDelay = projectile.getHitsplatDelay().orElse(hitsplatDelay);
        return nextRangedHit(attacker, defender, max, hitDelay, hitsplatDelay);
    }
References nextRangedHit(), and com.runehive.game.world.entity.combat.CombatType.RANGED.
nextRangedHit() [5/5]
CombatHit com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay) protected
Definition at line 173 of file CombatStrategy.java.
{
        return new CombatHit(FormulaFactory.nextRangedHit(attacker, defender, max), hitDelay, hitsplatDelay);
    }
References com.runehive.game.world.entity.combat.attack.FormulaFactory.nextRangedHit().
onDamage()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.onDamage (T defender, Hit hit)
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 182 of file CombatStrategy.java.
{
    }
References hit().
onDeath()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 64 of file CombatStrategy.java.
{
    }
References hit().
onKill()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 72 of file CombatStrategy.java.
{
    }
References hit().
preDeath()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 60 of file CombatStrategy.java.
{
    }
References hit().
preKill()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Reimplemented in com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 68 of file CombatStrategy.java.
{
    }
References hit().
start()
void com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Parameters
attacker the attacking mob
defender the defending mob
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Definition at line 40 of file CombatStrategy.java.
{
    }
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/CombatStrategy.java