RuneHive-Game: com.runehive.content.dialogue.OptionDialogue Class Reference
com.runehive.content.dialogue.OptionDialogue Class Reference
The Chainable implementation that represents a dialogue in which options are given to the player.
Public Member Functions
void accept (DialogueFactory factory)
List< Runnable > getActions ()
Gets the list of actions for this dialogue.
String[] getLines ()
Gets the text for this dialogue.
OptionDialogue (String option1, Runnable action1, String option2, Runnable action2)
Creates a new OptionDialogue.
OptionDialogue (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3)
Creates a new OptionDialogue.
OptionDialogue (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3, String option4, Runnable action4)
Creates a new OptionDialogue.
OptionDialogue (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3, String option4, Runnable action4, String option5, Runnable action5)
Creates a new OptionDialogue.
Private Attributes
final List< Runnable > actions = new ArrayList<>()
The list of actions for this dialogue.
final String[] lines
The text for this dialogue.
Detailed Description
The Chainable implementation that represents a dialogue in which options are given to the player.
Author
Michael | Chex
Definition at line 11 of file OptionDialogue.java.
Constructor & Destructor Documentation
OptionDialogue() [1/4]
com.runehive.content.dialogue.OptionDialogue.OptionDialogue (String option1, Runnable action1, String option2, Runnable action2)
Creates a new OptionDialogue.
Parameters
option1 The text for the first option.
action1 The action for the first action.
option2 The text for the second option.
action2 The action for the second action.
Definition at line 27 of file OptionDialogue.java.
{
        lines = new String[]{option1, option2};
        actions.add(action1);
        actions.add(action2);
    }
References actions, and lines.
OptionDialogue() [2/4]
com.runehive.content.dialogue.OptionDialogue.OptionDialogue (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3)
Creates a new OptionDialogue.
Parameters
option1 The text for the first option.
action1 The action for the first action.
option2 The text for the second option.
action2 The action for the second action.
option3 The text for the third option.
action3 The action for the third action.
Definition at line 43 of file OptionDialogue.java.
{
        lines = new String[]{option1, option2, option3};
        actions.add(action1);
        actions.add(action2);
        actions.add(action3);
    }
References actions, and lines.
OptionDialogue() [3/4]
com.runehive.content.dialogue.OptionDialogue.OptionDialogue (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3, String option4, Runnable action4)
Creates a new OptionDialogue.
Parameters
option1 The text for the first option.
action1 The action for the first action.
option2 The text for the second option.
action2 The action for the second action.
option3 The text for the third option.
action3 The action for the third action.
option4 The text for the four option.
action4 The action for the four action.
Definition at line 62 of file OptionDialogue.java.
{
        lines = new String[]{option1, option2, option3, option4};
        actions.add(action1);
        actions.add(action2);
        actions.add(action3);
        actions.add(action4);
    }
References actions, and lines.
OptionDialogue() [4/4]
com.runehive.content.dialogue.OptionDialogue.OptionDialogue (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3, String option4, Runnable action4, String option5, Runnable action5)
Creates a new OptionDialogue.
Parameters
option1 The text for the first option.
action1 The action for the first action.
option2 The text for the second option.
action2 The action for the second action.
option3 The text for the third option.
action3 The action for the third action.
option4 The text for the four option.
action4 The action for the four action.
option5 The text for the fifth option.
action5 The action for the fifth action.
Definition at line 84 of file OptionDialogue.java.
{
        lines = new String[]{option1, option2, option3, option4, option5};
        actions.add(action1);
        actions.add(action2);
        actions.add(action3);
        actions.add(action4);
        actions.add(action5);
    }
References actions, and lines.
Member Function Documentation
accept()
void com.runehive.content.dialogue.OptionDialogue.accept (DialogueFactory factory)
Definition at line 94 of file OptionDialogue.java.
{
        factory.sendOption(this);
    }
References com.runehive.content.dialogue.DialogueFactory.sendOption().
getActions()
List< Runnable > com.runehive.content.dialogue.OptionDialogue.getActions ()
Gets the list of actions for this dialogue.
Returns
The list of actions.
Definition at line 112 of file OptionDialogue.java.
{
        return actions;
    }
References actions.
Referenced by com.runehive.content.dialogue.DialogueFactory.executeOption().
getLines()
String[] com.runehive.content.dialogue.OptionDialogue.getLines ()
Gets the text for this dialogue.
Returns
The text.
Definition at line 103 of file OptionDialogue.java.
{
        return lines;
    }
References lines.
Member Data Documentation
actions
final List<Runnable> com.runehive.content.dialogue.OptionDialogue.actions = new ArrayList<>() private
The list of actions for this dialogue.
Definition at line 17 of file OptionDialogue.java.
Referenced by getActions(), OptionDialogue(), OptionDialogue(), OptionDialogue(), and OptionDialogue().
lines
final String [] com.runehive.content.dialogue.OptionDialogue.lines private
The text for this dialogue.
Definition at line 14 of file OptionDialogue.java.
Referenced by getLines(), OptionDialogue(), OptionDialogue(), OptionDialogue(), and OptionDialogue().
The documentation for this class was generated from the following file:
java/com/runehive/content/dialogue/OptionDialogue.java