RuneHive-Game: com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect Class Reference
com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect Class Reference
The class which is responsible for the effect when you drink an anti-fire potion.
Public Member Functions
boolean apply (Mob mob)
Applies this effect to mob.
CombatAntifireEffect (AntifireDetails.AntifireType type)
Constructs a new CombatAntifireEffect.
boolean onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
void process (Mob mob)
Provides processing for this effect on mob.
boolean removeOn (Mob mob)
Removes this effect from mob if needed.
Public Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
CombatEffect (int delay)
Creates a new CombatEffect.
final boolean start (Mob mob)
Starts this combat effect by scheduling a task utilizing the abstract methods in this class.
Private Attributes
final AntifireDetails.AntifireType type
The type of antifire this player has drunk.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
static Collection< CombatEffect > values ()
Returns an unmodifiable view of the combat effect listeners.
Static Public Attributes inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
static final Map< CombatEffectType, CombatEffect > EFFECTS = new HashMap<>()
The map of all of the combat effect types mapped to their respective listeners.
Protected Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
final int getDelay ()
Gets the delay for this individual combat effect.
Detailed Description
The class which is responsible for the effect when you drink an anti-fire potion.
Author
Stand Up
Definition at line 13 of file CombatAntifireEffect.java.
Constructor & Destructor Documentation
CombatAntifireEffect()
com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.CombatAntifireEffect (AntifireDetails.AntifireType type)
Constructs a new CombatAntifireEffect.
Parameters
type type.
Definition at line 24 of file CombatAntifireEffect.java.
{
        super(1);
        this.type = type;
    }
References type.
Member Function Documentation
apply()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.apply (Mob mob)
Applies this effect to mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 30 of file CombatAntifireEffect.java.
{
        if(!mob.isPlayer()) {
            return false;
        }
        Player player = mob.getPlayer();
        if(player.getAntifireDetails().isPresent()) {
            player.setAntifireDetail(new AntifireDetails(type));
            return false;
        }
        player.setAntifireDetail(new AntifireDetails(type));
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.getAntifireDetails(), com.runehive.game.world.entity.mob.player.Player.setAntifireDetail(), and type.
onLogin()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 74 of file CombatAntifireEffect.java.
{
        return mob.isPlayer() && mob.getPlayer().getAntifireDetails().isPresent();
    }
process()
void com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.process (Mob mob)
Provides processing for this effect on mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 58 of file CombatAntifireEffect.java.
{
        if(mob.isPlayer() && mob.getPlayer().getAntifireDetails().isPresent()) {
            Player player = mob.getPlayer();
            AntifireDetails detail = player.getAntifireDetails().get();
            int count = detail.getAntifireDelay().decrementAndGet();
            if(count == 30) {
                player.send(new SendMessage("@red@Your resistance to dragon fire is about to wear off!"));
            }
            if(count < 1) {
                player.setAntifireDetail(null);
                player.send(new SendMessage("Your resistance to dragon fire has worn off!"));
            }
        }
    }
References com.runehive.util.MutableNumber.decrementAndGet(), com.runehive.game.world.entity.combat.effect.AntifireDetails.getAntifireDelay(), com.runehive.game.world.entity.mob.player.Player.getAntifireDetails(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.player.Player.setAntifireDetail().
removeOn()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.removeOn (Mob mob)
Removes this effect from mob if needed.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 47 of file CombatAntifireEffect.java.
{
        if(mob.isPlayer()) {
            Player player = mob.getPlayer();
            return !player.getAntifireDetails().isPresent();
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.getAntifireDetails().
Member Data Documentation
type
final AntifireDetails.AntifireType com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.type private
The type of antifire this player has drunk.
Definition at line 18 of file CombatAntifireEffect.java.
Referenced by apply(), and CombatAntifireEffect().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/effect/impl/CombatAntifireEffect.java