RuneHive-Game: com.runehive.content.dialogue.impl.RoyalKingDialogue Class Reference
com.runehive.content.dialogue.impl.RoyalKingDialogue Class Reference
The royal king dialogue.
Public Member Functions
RoyalKingDialogue (int index)
void sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Private Member Functions
void claim (DialogueFactory factory)
void myStats (DialogueFactory factory)
void store (DialogueFactory factory)
Private Attributes
int index
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.dialogue.Dialogue
static final boolean isDialogueButton (int button)
Checks if the button triggered is an optional dialogue button.
Static Public Attributes inherited from com.runehive.content.dialogue.Dialogue
static final ImmutableList< Integer > DIALOGUE_BUTTONS = ImmutableList.of(2461, 2471, 2482, 2462, 2472, 2483, 2473, 2484, 2485, 2494, 2495, 2496, 2497, 2498)
The action buttons responsible for dialogues.
Detailed Description
The royal king dialogue.
Author
Daniel
Definition at line 16 of file RoyalKingDialogue.java.
Constructor & Destructor Documentation
RoyalKingDialogue()
com.runehive.content.dialogue.impl.RoyalKingDialogue.RoyalKingDialogue (int index)
Definition at line 20 of file RoyalKingDialogue.java.
{
        this.index = index;
    }
References index.
Member Function Documentation
claim()
void com.runehive.content.dialogue.impl.RoyalKingDialogue.claim (DialogueFactory factory) private
Definition at line 47 of file RoyalKingDialogue.java.
{
        Player player = factory.getPlayer();
        player.send(new SendMessage("Claiming is temporarily disabled until EverythingRS is replaced."));
        /*new Thread(() -> {
            try {
                Donation[] donations = Donation.donations(
                        "V48tgd7OxwrvPMmZZbjkVt6qTYB2MrZ5sw6PD4DBJnM83zepnUlIT8DiFoND3BYEQjqxPamH", player.getName());
                if (donations.length == 0) {
                    player.send(new SendMessage("You currently don't have any items waiting. You must donate first!"));
                    return;
                }
                if (donations[0].message != null) {
                    player.send(new SendMessage(donations[0].message));
                    return;
                }
                for (Donation donate : donations) {
                    player.inventory.add(new Item(donate.product_id, donate.product_amount));
                }
                player.send(new SendMessage("Thank you for donating!"));
            } catch (Exception e) {
                player.send(new SendMessage("Api Services are currently offline. Please check back shortly"));
                e.printStackTrace();
            }
        }).start();*/
    }
References com.runehive.content.dialogue.DialogueFactory.getPlayer(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by sendDialogues().
myStats()
void com.runehive.content.dialogue.impl.RoyalKingDialogue.myStats (DialogueFactory factory) private
Definition at line 42 of file RoyalKingDialogue.java.
{
        factory.sendStatement("Money spent: $" + factory.getPlayer().donation.getSpent(), "Current credits: " + factory.getPlayer().donation.getCredits());
    }
References com.runehive.game.world.entity.mob.player.Player.donation, com.runehive.content.donators.Donation.getCredits(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.donators.Donation.getSpent(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
Referenced by sendDialogues().
sendDialogues()
void com.runehive.content.dialogue.impl.RoyalKingDialogue.sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Parameters
factory The factory for this dialogue.
Reimplemented from com.runehive.content.dialogue.Dialogue.
Definition at line 25 of file RoyalKingDialogue.java.
{
        if (index == 1) {
            claim(factory);
            factory.execute();
            return;
        }
        if (index == 2) {
            store(factory);
            factory.execute();
            return;
        }
        Player player = factory.getPlayer();
        factory.sendNpcChat(5523, Expression.HAPPY, "Hello adventurer, how may I help you?");
        factory.sendOption("Claim Purchase", () -> claim(factory), "Donator Information", () -> player.send(new SendURL("https://runehive.com")), "My donation statistics", () -> myStats(factory), "Open Store", () -> store(factory), "Nevermind", factory::clear);
        factory.execute();
    }
References claim(), com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.dialogue.Expression.HAPPY, index, myStats(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and store().
store()
void com.runehive.content.dialogue.impl.RoyalKingDialogue.store (DialogueFactory factory) private
Definition at line 74 of file RoyalKingDialogue.java.
{
        factory.sendOption("Open Donator Store", () -> Store.STORES.get("Donator Store").open(factory.getPlayer()), "Ironman Donator Store", () -> Store.STORES.get("Ironman Donator Store").open(factory.getPlayer()),"Nevermind", factory::clear);
    }
References com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.store.Store.STORES.
Referenced by sendDialogues().
Member Data Documentation
index
int com.runehive.content.dialogue.impl.RoyalKingDialogue.index private
Definition at line 18 of file RoyalKingDialogue.java.
Referenced by RoyalKingDialogue(), and sendDialogues().
The documentation for this class was generated from the following file:
java/com/runehive/content/dialogue/impl/RoyalKingDialogue.java