RuneHive-Game: com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy Class Reference
com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy Class Reference
The high alchemy spell.
Public Member Functions
void execute (Player player, Item item)
Executes the magic spell.
int getLevel ()
Gets the level required to cast spell.
String getName ()
Gets the name of the spell.
Item[] getRunes ()
Gets the runes required to cast the spell.
Detailed Description
The high alchemy spell.
Author
Daniel
Definition at line 25 of file HighAlchemy.java.
Member Function Documentation
execute()
void com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute (Player player, Item item)
Executes the magic spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 43 of file HighAlchemy.java.
{
        if (player.spellbook != Spellbook.MODERN)
            return;
        if (!player.spellCasting.castingDelay.elapsed(500)) {
            return;
        }
        if (Arrays.stream(Magic.UNALCHEABLES).anyMatch($it -> item.getId() == $it.getId())) {
            player.send(new SendMessage("You can not alch this item!"));
            return;
        }
        int value = item.getHighAlch();
        player.animate(new Animation(713));
        player.graphic(new Graphic(113, true));
        player.inventory.remove(item.getId(), 1);
        player.inventory.removeAll(getRunes());
        player.inventory.add(Config.CURRENCY, value == 0 ? 1 : value);
        player.inventory.refresh();
        player.send(new SendForceTab(6));
        player.skills.addExperience(Skill.MAGIC, 65 * (Config.MAGIC_MODIFICATION + 5));
        AchievementHandler.activate(player, AchievementKey.HIGH_ALCHEMY, 1);
        player.spellCasting.castingDelay.reset();
        player.action.clearNonWalkableActions();
        RandomEventHandler.trigger(player);
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.content.skill.impl.magic.spell.SpellCasting.castingDelay, com.runehive.game.action.ActionManager.clearNonWalkableActions(), com.runehive.Config.CURRENCY, com.runehive.util.Stopwatch.elapsed(), com.runehive.game.world.items.Item.getHighAlch(), com.runehive.game.world.items.Item.getId(), getRunes(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.content.achievement.AchievementKey.HIGH_ALCHEMY, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.skill.Skill.MAGIC, com.runehive.Config.MAGIC_MODIFICATION, com.runehive.content.skill.impl.magic.Spellbook.MODERN, com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.containers.ItemContainer.removeAll(), com.runehive.util.Stopwatch.reset(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.mob.player.Player.spellbook, com.runehive.game.world.entity.mob.player.Player.spellCasting, com.runehive.content.activity.randomevent.RandomEventHandler.trigger(), and com.runehive.content.skill.impl.magic.Magic.UNALCHEABLES.
getLevel()
int com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.getLevel ()
Gets the level required to cast spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 33 of file HighAlchemy.java.
{
        return 55;
    }
getName()
String com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.getName ()
Gets the name of the spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 28 of file HighAlchemy.java.
{
        return "High alchemy";
    }
getRunes()
Item[] com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.getRunes ()
Gets the runes required to cast the spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 38 of file HighAlchemy.java.
{
        return new Item[] { new Item(554, 5), new Item(561, 1) };
    }
Referenced by execute().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/magic/spell/impl/HighAlchemy.java