RuneHive-Game: com.runehive.util.generic.GenericAttributes Class Reference
com.runehive.util.generic.GenericAttributes Class Reference
Holds generic attributes.
Package Functions
public< K, E > E get (K key)
Gets a generic attribute.
public< K, E > E get (K key, Class<? extends E > type)
Gets a generic attribute casted to a specific class type.
public< K > Object getObject (K key)
Gets a generic attribute.
public< K > boolean has (K key)
Checks if a key is in the list of generic attribute.
public< K > boolean is (K key)
Gets the state of a key.
public< K, E > void modify (K key, E value)
Modifies a generic attribute.
public< K, V > void put (K key, V value)
public< K > void remove (K key)
Removes a generic attribute.
public< K, E > void set (K key, E attribute)
Sets a generic attribute.
Private Attributes
final Map< Object, Object > genericAttributes = new HashMap<>()
The map of generic attributes for an entity.
Detailed Description
Holds generic attributes.
Author
Michael | Chex
Definition at line 11 of file GenericAttributes.java.
Member Function Documentation
get() [1/2]
public< K, E > E com.runehive.util.generic.GenericAttributes.get (K key) package
Gets a generic attribute.
Parameters
<K> The key type.
<E> The return value class type.
key The key.
Returns
The value associated with the key, or null.
Definition at line 85 of file GenericAttributes.java.
{
        try {
            return (E) genericAttributes.get(key);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
References genericAttributes, and get().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.canAttack(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.canExecute(), com.runehive.content.skill.impl.construction.BuildableInterface.click(), com.runehive.content.teleport.TeleportHandler.click(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.content.skill.impl.fletching.Fletching.clickButton(), com.runehive.content.store.Store.closeShop(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.store.Store.exchange(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.teleport.TeleportHandler.favorite(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), get(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.hitsplat(), com.runehive.content.skill.impl.agility.obstacle.impl.RopeSwingInteraction.onExecution(), com.runehive.content.DropDisplay.open(), com.runehive.content.teleport.TeleportHandler.open(), com.runehive.content.tittle.TitleManager.redeem(), com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), com.runehive.content.tittle.TitleManager.refresh(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), com.runehive.net.packet.in.ItemContainerActionPacketListener.sixthAction(), and com.runehive.content.teleport.TeleportHandler.teleport().
get() [2/2]
public< K, E > E com.runehive.util.generic.GenericAttributes.get (K key, Class<? extends E > type) package
Gets a generic attribute casted to a specific class type.
Parameters
<K> The key type.
<E> The return value class type.
key The key.
type The class for the return type.
Returns
The value associated with the key, or null.
Definition at line 126 of file GenericAttributes.java.
{
        Object attribute = genericAttributes.get(key);
        try {
            return type.cast(attribute);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
References genericAttributes.
getObject()
public< K > Object com.runehive.util.generic.GenericAttributes.getObject (K key) package
Gets a generic attribute.
Parameters
<K> The key type.
key The key.
Returns
The value associated with the key, or null.
Definition at line 104 of file GenericAttributes.java.
{
        try {
            return genericAttributes.get(key);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
References genericAttributes, and getObject().
Referenced by com.runehive.content.skill.impl.crafting.Crafting.clickButton(), and getObject().
has()
public< K > boolean com.runehive.util.generic.GenericAttributes.has (K key) package
Checks if a key is in the list of generic attribute.
Parameters
<K> The key type.
key The key.
Returns
True if the generic attributes contains a value with this key.
Definition at line 69 of file GenericAttributes.java.
{
        return genericAttributes.containsKey(key);
    }
References genericAttributes.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.canAttack(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.content.store.Store.closeShop(), com.runehive.content.store.Store.exchange(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.getAttackDelay(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), is(), and com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage().
is()
public< K > boolean com.runehive.util.generic.GenericAttributes.is (K key) package
Gets the state of a key.
Parameters
<K> The key type.
key The key to check.
Returns
True if the value of the key is equal to Boolean.TRUE.
Definition at line 146 of file GenericAttributes.java.
{
        return has(key) && Boolean.TRUE == get(key, Boolean.class);
    }
References has().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.canAttack(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start().
modify()
public< K, E > void com.runehive.util.generic.GenericAttributes.modify (K key, E value) package
Modifies a generic attribute.
Parameters
<K> The key type.
<E> The return value class type.
key The key.
value The value to set.
Definition at line 43 of file GenericAttributes.java.
{
        genericAttributes.replace(key, value);
    }
References genericAttributes.
put()
public< K, V > void com.runehive.util.generic.GenericAttributes.put (K key, V value) package
Definition at line 16 of file GenericAttributes.java.
{
        genericAttributes.put(key, value);
    }
References genericAttributes.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.canAttack(), and com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.hitsplat().
remove()
public< K > void com.runehive.util.generic.GenericAttributes.remove (K key) package
Removes a generic attribute.
Parameters
<K> The key type.
key The key.
Definition at line 55 of file GenericAttributes.java.
{
        genericAttributes.remove(key);
    }
References genericAttributes.
Referenced by com.runehive.content.store.impl.DefaultStore.close(), com.runehive.content.store.impl.PersonalStore.close(), com.runehive.content.store.impl.RecipeForDisasterStore.close(), com.runehive.content.store.impl.SkillcapeStore.close(), com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.finishOutgoing(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start().
set()
public< K, E > void com.runehive.util.generic.GenericAttributes.set (K key, E attribute) package
Sets a generic attribute.
Parameters
<K> The key type.
<E> The return value class type.
key The key.
attribute The value associated with this key.
Definition at line 32 of file GenericAttributes.java.
{
        genericAttributes.put(key, attribute);
    }
References genericAttributes.
Referenced by com.runehive.content.Obelisks.activate(), com.runehive.content.teleport.TeleportHandler.click(), com.runehive.content.tittle.TitleManager.click(), com.runehive.content.itemaction.impl.SerpentineHelm.dismantle(), com.runehive.content.skill.impl.construction.BuildableInterface.display(), com.runehive.content.teleport.TeleportHandler.display(), com.runehive.content.simulator.DropSimulator.drawList(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fifthAction(), com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.init(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.lavaTask(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember(), com.runehive.content.Obelisks.open(), com.runehive.content.skill.impl.construction.BuildableInterface.open(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.content.teleport.TeleportHandler.open(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask(), com.runehive.content.StarterKit.refresh(), com.runehive.content.itemaction.impl.MagmaHelm.restore(), com.runehive.content.itemaction.impl.TanzaniteHelm.restore(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.content.DropDisplay.search(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.content.skill.impl.crafting.Crafting.useItem(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
Member Data Documentation
genericAttributes
final Map<Object, Object> com.runehive.util.generic.GenericAttributes.genericAttributes = new HashMap<>() private
The map of generic attributes for an entity.
Definition at line 14 of file GenericAttributes.java.
Referenced by get(), get(), getObject(), has(), modify(), put(), remove(), and set().
The documentation for this class was generated from the following file:
java/com/runehive/util/generic/GenericAttributes.java