RuneHive-Game: com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener Class Reference
com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener Class Reference
An ItemContainerAdapter implementation that listens for changes to the inventory.
Public Member Functions
String getCapacityExceededMsg ()
int getWidgetId ()
void itemUpdated (ItemContainer container, Optional< Item > oldItem, Optional< Item > newItem, int index, boolean refresh, boolean login)
Fired when an Item is added, removed, or replaced.
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainerAdapter
void bulkItemsUpdated (ItemContainer container)
Fired when an Items are added, removed, or replaced in bulk.
void capacityExceeded (ItemContainer container)
Fired when the capacity of container is exceeded.
ItemContainerAdapter (Player player)
Creates a new ItemContainerAdapter.
Package Functions
InventoryListener (Player player)
Creates a new InventoryListener.
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.world.items.containers.ItemContainerAdapter
void sendItemsToWidget (ItemContainer container)
Queues a message that displays items from an ItemContainer on a widget.
Detailed Description
An ItemContainerAdapter implementation that listens for changes to the inventory.
Definition at line 156 of file Inventory.java.
Constructor & Destructor Documentation
InventoryListener()
com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.InventoryListener (Player player) package
Creates a new InventoryListener.
Definition at line 159 of file Inventory.java.
{
            super(player);
        }
References com.runehive.game.world.items.containers.ItemContainerAdapter.player.
Member Function Documentation
getCapacityExceededMsg()
String com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.getCapacityExceededMsg ()
Returns
The message sent when the ItemContainer exceeds its capacity.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 175 of file Inventory.java.
{
            return "You do not have enough space in your inventory.";
        }
getWidgetId()
int com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.getWidgetId ()
Returns
The widget to display items on.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 170 of file Inventory.java.
{
            return INVENTORY_DISPLAY_ID;
        }
References com.runehive.game.world.items.containers.inventory.Inventory.INVENTORY_DISPLAY_ID.
Referenced by itemUpdated().
itemUpdated()
void com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.itemUpdated (ItemContainer container, Optional< Item > oldItem, Optional< Item > newItem, int index, boolean refresh, boolean login)
Fired when an Item is added, removed, or replaced.
Parameters
container The ItemContainer firing the randomevent.
oldItem The old item being removed from this container.
newItem The new item being added to this container.
index The index the update is occurring on.
refresh The condition if we have to refresh this container.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 164 of file Inventory.java.
{
            if (refresh)
                player.send(new SendItemOnInterfaceSlot(getWidgetId(), newItem.orElse(null), index));
        }
References getWidgetId(), com.runehive.game.world.items.containers.ItemContainer.ItemContainer(), com.runehive.game.world.items.containers.ItemContainerAdapter.player, and com.runehive.game.world.items.containers.inventory.Inventory.refresh().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/inventory/Inventory.java