RuneHive-Game: com.runehive.game.plugin.PluginContext Class Reference
com.runehive.game.plugin.PluginContext Class Reference
The base class that all plugins should extend.
Public Member Functions
boolean accept (Player player, Event event)
The method that allows an event listener to accept an event.
void onInit ()
Public Member Functions inherited from com.runehive.game.event.listener.EventListener
default void accept (Event event)
Static Public Attributes
static final Logger logger = LogManager.getLogger(PluginContext.class)
Protected Member Functions
boolean allButOneItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean fifthClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean firstClickItem (Player player, ItemClickEvent event)
boolean firstClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean firstClickNpc (Player player, NpcClickEvent event)
boolean firstClickObject (Player player, ObjectClickEvent event)
boolean fourthClickItem (Player player, ItemClickEvent event)
boolean fourthClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean fourthClickNpc (Player player, NpcClickEvent event)
boolean handleCommand (Player player, CommandParser parser)
boolean itemOnItem (Player player, ItemOnItemEvent event)
boolean itemOnNpc (Player player, ItemOnNpcEvent event)
boolean itemOnObject (Player player, ItemOnObjectEvent event)
boolean itemOnPlayer (Player player, ItemOnPlayerEvent event)
boolean modifiableXItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean onClick (final Player player, final int button)
boolean onDropItem (Player player, DropItemEvent event)
boolean onMovement (Player player, MovementEvent event)
boolean onPickupItem (Player player, PickupItemEvent event)
boolean secondClickItem (Player player, ItemClickEvent event)
boolean secondClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean secondClickNpc (Player player, NpcClickEvent event)
boolean secondClickObject (Player player, ObjectClickEvent event)
boolean sixthClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean thirdClickItem (Player player, ItemClickEvent event)
boolean thirdClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean thirdClickNpc (Player player, NpcClickEvent event)
boolean thirdClickObject (Player player, ObjectClickEvent event)
Private Member Functions
boolean handleButtonClickEvent (Player player, ButtonClickEvent event)
boolean handleCommandEvent (Player player, CommandEvent event)
boolean handleDropItemEvent (Player player, DropItemEvent event)
boolean handleItemClickEvent (Player player, ItemClickEvent event)
boolean handleItemContainerContextMenuEvent (Player player, ItemContainerContextMenuEvent event)
boolean handleItemOnItemEvent (Player player, ItemOnItemEvent event)
boolean handleItemOnNpcEvent (Player player, ItemOnNpcEvent event)
boolean handleItemOnObjectEvent (Player player, ItemOnObjectEvent event)
boolean handleItemOnPlayerEvent (Player player, ItemOnPlayerEvent event)
boolean handleNpcClickEvent (Player player, NpcClickEvent event)
boolean handleObjectClickEvent (Player player, ObjectClickEvent event)
boolean handlePickupItemEvent (Player player, PickupItemEvent event)
Detailed Description
The base class that all plugins should extend.
This class allows plugins to have many different behaviors and listen to all types of events.
Author
nshusa
Definition at line 35 of file PluginContext.java.
Member Function Documentation
accept()
boolean com.runehive.game.plugin.PluginContext.accept (Player player, Event event)
The method that allows an event listener to accept an event.
Parameters
player The player that is sending the event.
event The event that is being sent.
Returns
true If the event was handled. Otherwise return false.
Implements com.runehive.game.event.listener.PlayerEventListener.
Definition at line 44 of file PluginContext.java.
{
        try {
            if (event instanceof ButtonClickEvent) {
                return handleButtonClickEvent(player, (ButtonClickEvent) event);
            } else if (event instanceof ItemClickEvent) {
                return handleItemClickEvent(player, (ItemClickEvent) event);
            } else if (event instanceof NpcClickEvent) {
                return handleNpcClickEvent(player, (NpcClickEvent) event);
            } else if (event instanceof ObjectClickEvent) {
                return handleObjectClickEvent(player, (ObjectClickEvent) event);
            } else if (event instanceof ItemOnItemEvent) {
                return handleItemOnItemEvent(player, (ItemOnItemEvent) event);
            } else if (event instanceof ItemOnNpcEvent) {
                return handleItemOnNpcEvent(player, (ItemOnNpcEvent) event);
            } else if (event instanceof ItemOnObjectEvent) {
                return handleItemOnObjectEvent(player, (ItemOnObjectEvent) event);
            } else if (event instanceof ItemOnPlayerEvent) {
                return handleItemOnPlayerEvent(player, (ItemOnPlayerEvent) event);
            } else if (event instanceof CommandEvent) {
                return handleCommandEvent(player, (CommandEvent) event);
            } else if (event instanceof ItemContainerContextMenuEvent) {
                return handleItemContainerContextMenuEvent(player, (ItemContainerContextMenuEvent) event);
            } else if (event instanceof DropItemEvent) {
                return handleDropItemEvent(player, (DropItemEvent) event);
            } else if (event instanceof PickupItemEvent) {
                return handlePickupItemEvent(player, (PickupItemEvent) event);
            } else if (event instanceof MovementEvent) {
                return onMovement(player, (MovementEvent) event);
            }
        } catch (Exception ex) {
            logger.error(String.format("player=%s error while handling event: %s", player.getName(), this.getClass().getSimpleName()), ex);
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.getName(), handleButtonClickEvent(), handleCommandEvent(), handleDropItemEvent(), handleItemClickEvent(), handleItemContainerContextMenuEvent(), handleItemOnItemEvent(), handleItemOnNpcEvent(), handleItemOnObjectEvent(), handleItemOnPlayerEvent(), handleNpcClickEvent(), handleObjectClickEvent(), handlePickupItemEvent(), logger, and onMovement().
allButOneItemContainer()
boolean com.runehive.game.plugin.PluginContext.allButOneItemContainer (Player player, ItemContainerContextMenuEvent event) protected
Definition at line 231 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemContainerContextMenuEvent().
fifthClickItemContainer()
boolean com.runehive.game.plugin.PluginContext.fifthClickItemContainer (Player player, ItemContainerContextMenuEvent event) protected
Definition at line 223 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemContainerContextMenuEvent().
firstClickItem()
boolean com.runehive.game.plugin.PluginContext.firstClickItem (Player player, ItemClickEvent event) protected
Definition at line 482 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemClickEvent().
firstClickItemContainer()
boolean com.runehive.game.plugin.PluginContext.firstClickItemContainer (Player player, ItemContainerContextMenuEvent event) protected
Definition at line 207 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemContainerContextMenuEvent().
firstClickNpc()
boolean com.runehive.game.plugin.PluginContext.firstClickNpc (Player player, NpcClickEvent event) protected
Definition at line 421 of file PluginContext.java.
{
        return false;
    }
Referenced by handleNpcClickEvent().
firstClickObject()
boolean com.runehive.game.plugin.PluginContext.firstClickObject (Player player, ObjectClickEvent event) protected
Definition at line 347 of file PluginContext.java.
{
        logger.log(Level.INFO, String.format("[%s, type=%d]:first click object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId()));
        if (player.debug) {
            player.send(new SendMessage(String.format("[%s, type=%d]: object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId())));
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, logger, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by handleObjectClickEvent().
fourthClickItem()
boolean com.runehive.game.plugin.PluginContext.fourthClickItem (Player player, ItemClickEvent event) protected
Definition at line 494 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemClickEvent().
fourthClickItemContainer()
boolean com.runehive.game.plugin.PluginContext.fourthClickItemContainer (Player player, ItemContainerContextMenuEvent event) protected
Definition at line 219 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemContainerContextMenuEvent().
fourthClickNpc()
boolean com.runehive.game.plugin.PluginContext.fourthClickNpc (Player player, NpcClickEvent event) protected
Definition at line 433 of file PluginContext.java.
{
        return false;
    }
Referenced by handleNpcClickEvent().
handleButtonClickEvent()
boolean com.runehive.game.plugin.PluginContext.handleButtonClickEvent (Player player, ButtonClickEvent event) private
Definition at line 498 of file PluginContext.java.
{
        if (onClick(player, event.getButton())) {
            if (player.debug) {
                player.send(new SendMessage(String.format("[%s]: button=%d", this.getClass().getSimpleName(), event.getButton())));
            }
            return true;
        }
         return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, onClick(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by accept().
handleCommand()
boolean com.runehive.game.plugin.PluginContext.handleCommand (Player player, CommandParser parser) protected
Reimplemented in com.runehive.game.plugin.extension.CommandExtension.
Definition at line 249 of file PluginContext.java.
{
        return false;
    }
Referenced by handleCommandEvent().
handleCommandEvent()
boolean com.runehive.game.plugin.PluginContext.handleCommandEvent (Player player, CommandEvent event) private
Definition at line 239 of file PluginContext.java.
{
        if (handleCommand(player, event.getParser())) {
            if (Config.LOG_PLAYER) {
                World.getDataBus().publish(new CommandLogEvent(player, event.getParser()));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.World.getDataBus(), handleCommand(), com.runehive.Config.LOG_PLAYER, and com.runehive.game.event.bus.DataBus.publish().
Referenced by accept().
handleDropItemEvent()
boolean com.runehive.game.plugin.PluginContext.handleDropItemEvent (Player player, DropItemEvent event) private
Definition at line 100 of file PluginContext.java.
{
        if (onDropItem(player, event)) {
            logger.log(Level.INFO, String.format("player=%s dropped item=%d amount=%d slot=%d position=%s", player.getName(), event.getItem().getId(), event.getItem().getAmount(), event.getSlot(), event.getPosition()));
            if (PlayerRight.isDeveloper(player)) {
                player.send(new SendMessage(String.format("[%s]: item=%d amount=%d slot=%d position=%s", this.getClass().getSimpleName(), event.getItem().getId(), event.getItem().getAmount(), event.getSlot(), event.getPosition())));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), logger, onDropItem(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by accept().
handleItemClickEvent()
boolean com.runehive.game.plugin.PluginContext.handleItemClickEvent (Player player, ItemClickEvent event) private
Definition at line 437 of file PluginContext.java.
{
        switch(event.getType()) {
            case 1:
                if (firstClickItem(player, event)) {
                    logger.log(Level.INFO, String.format("[%s, type=%d]:first click item=%d", this.getClass().getSimpleName(), event.getType(), event.getItem().getId()));
                    if (player.debug) {
                        player.send(new SendMessage(String.format("[%s, type=%d]: item=%d", this.getClass().getSimpleName(), event.getType(), event.getItem().getId())));
                    }
                    return true;
                }
                break;
            case 2:
                if (secondClickItem(player, event)) {
                    logger.log(Level.INFO, String.format("[%s, type=%d]:second click item=%d", this.getClass().getSimpleName(), event.getType(), event.getItem().getId()));
                    if (player.debug) {
                        player.send(new SendMessage(String.format("[%s, type=%d]: item=%d", this.getClass().getSimpleName(), event.getType(), event.getItem().getId())));
                    }
                    return true;
                }
                break;
            case 3:
                if (thirdClickItem(player, event)) {
                    logger.log(Level.INFO, String.format("[%s, type=%d]:third click item=%d", this.getClass().getSimpleName(), event.getType(), event.getItem().getId()));
                    if (player.debug) {
                        player.send(new SendMessage(String.format("[%s, type=%d]: item=%d", this.getClass().getSimpleName(), event.getType(), event.getItem().getId())));
                    }
                    return true;
                }
                break;
            case 4:
                if (fourthClickItem(player, event)) {
                    logger.log(Level.INFO, String.format("[%s, type=%d]:fourth click item=%d", this.getClass().getSimpleName(), event.getType(), event.getItem().getId()));
                    if (player.debug) {
                        player.send(new SendMessage(String.format("[%s, type=%d]: item=%d", this.getClass().getSimpleName(), event.getType(), event.getItem().getId())));
                    }
                    return true;
                }
                break;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, firstClickItem(), fourthClickItem(), logger, secondClickItem(), com.runehive.game.world.entity.mob.player.Player.send(), and thirdClickItem().
Referenced by accept().
handleItemContainerContextMenuEvent()
boolean com.runehive.game.plugin.PluginContext.handleItemContainerContextMenuEvent (Player player, ItemContainerContextMenuEvent event) private
Definition at line 115 of file PluginContext.java.
{
            switch(event.getType()) {
                case 1:
                    if (firstClickItemContainer(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]: first item interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot()));
                        if (PlayerRight.isDeveloper(player)) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot())));
                        }
                        return true;
                    }
                    break;
                case 2:
                    if (secondClickItemContainer(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]: second item interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot()));
                        if (PlayerRight.isDeveloper(player)) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot())));
                        }
                        return true;
                    }
                    break;
                case 3:
                    if (thirdClickItemContainer(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]: third item interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot()));
                        if (PlayerRight.isDeveloper(player)) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot())));
                        }
                        return true;
                    }
                    break;
                case 4:
                    if (fourthClickItemContainer(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]: fourth item interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot()));
                        if (PlayerRight.isDeveloper(player)) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot())));
                        }
                        return true;
                    }
                    break;
                case 5:
                    if (fifthClickItemContainer(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]: fifth item interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot()));
                        if (PlayerRight.isDeveloper(player) ) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot())));
                        }
                        return true;
                    }
                    break;
                case 6:
                    if (sixthClickItemContainer(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]: sixth item interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot()));
                        if (PlayerRight.isDeveloper(player) ) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot())));
                        }
                        return true;
                    }
                    break;
                case 7:
                    if (allButOneItemContainer(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]: seventh item interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot()));
                        if (PlayerRight.isDeveloper(player)) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot())));
                        }
                        return true;
                    }
                        break;
                case 8:
                    if (modifiableXItemContainer(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]: eight item interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot()));
                        if (PlayerRight.isDeveloper(player) ) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: interfaceId=%d (removeId=%d, removeSlot=%d)", this.getClass().getSimpleName(), event.getType(), event.getInterfaceId(), event.getRemoveId(), event.getRemoveSlot())));
                        }
                        return true;
                    }
                    break;
            }
            return false;
    }
References allButOneItemContainer(), fifthClickItemContainer(), firstClickItemContainer(), fourthClickItemContainer(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), logger, modifiableXItemContainer(), secondClickItemContainer(), com.runehive.game.world.entity.mob.player.Player.send(), sixthClickItemContainer(), and thirdClickItemContainer().
Referenced by accept().
handleItemOnItemEvent()
boolean com.runehive.game.plugin.PluginContext.handleItemOnItemEvent (Player player, ItemOnItemEvent event) private
Definition at line 297 of file PluginContext.java.
{
        if (itemOnItem(player, event)) {
            logger.log(Level.INFO, String.format("[%s]: used=%d usedSlot=%d with=%d withSlot=%d", this.getClass().getSimpleName(), event.getUsed().getId(), event.getUsedSlot(), event.getWith().getId(), event.getWithSlot()));
            if (player.debug) {
                player.send(new SendMessage(String.format("[%s]: used=%d usedSlot=%d with=%d withSlot=%d", this.getClass().getSimpleName(), event.getUsed().getId(), event.getUsedSlot(), event.getWith().getId(), event.getWithSlot())));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, itemOnItem(), logger, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by accept().
handleItemOnNpcEvent()
boolean com.runehive.game.plugin.PluginContext.handleItemOnNpcEvent (Player player, ItemOnNpcEvent event) private
Definition at line 282 of file PluginContext.java.
{
        if (itemOnNpc(player, event)) {
            logger.log(Level.INFO, String.format("[%s]: item=%d slot=%d npc=%d", this.getClass().getSimpleName(), event.getUsed().getId(), event.getSlot(), event.getNpc().id));
            if (player.debug) {
                player.send(new SendMessage(String.format("[%s]: item=%d slot=%d npc=%d", this.getClass().getSimpleName(), event.getUsed().getId(), event.getSlot(), event.getNpc().id)));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, itemOnNpc(), logger, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by accept().
handleItemOnObjectEvent()
boolean com.runehive.game.plugin.PluginContext.handleItemOnObjectEvent (Player player, ItemOnObjectEvent event) private
Definition at line 267 of file PluginContext.java.
{
        if (itemOnObject(player, event)) {
            logger.log(Level.INFO, String.format("[%s]: item=%d slot=%d object=%d", this.getClass().getSimpleName(), event.getUsed().getId(), event.getSlot(), event.getObject().getId()));
            if (player.debug) {
                player.send(new SendMessage(String.format("[%s]: item=%d slot=%d object=%d", this.getClass().getSimpleName(), event.getUsed().getId(), event.getSlot(), event.getObject().getId())));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, itemOnObject(), logger, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by accept().
handleItemOnPlayerEvent()
boolean com.runehive.game.plugin.PluginContext.handleItemOnPlayerEvent (Player player, ItemOnPlayerEvent event) private
Definition at line 253 of file PluginContext.java.
{
        if (itemOnPlayer(player, event)) {
            if (player.debug) {
                player.send(new SendMessage(String.format("[%s]: item=%d slot=%d player=%s", this.getClass().getSimpleName(), event.getUsed().getId(), event.getSlot(), event.getOther().getName())));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, itemOnPlayer(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by accept().
handleNpcClickEvent()
boolean com.runehive.game.plugin.PluginContext.handleNpcClickEvent (Player player, NpcClickEvent event) private
Definition at line 373 of file PluginContext.java.
{
        switch(event.getType()) {
            case 1:
                if (firstClickNpc(player, event)) {
                    logger.log(Level.INFO, String.format("[%s, type=%d]:first click npc=%d", this.getClass().getSimpleName(), event.getType(), event.getNpc().id));
                    if (player.debug) {
                        player.send(new SendMessage(String.format("[%s, type=%d]: npc=%d", this.getClass().getSimpleName(), event.getType(), event.getNpc().id)));
                    }
                    return true;
                }
                break;
            case 2:
                if (secondClickNpc(player, event)) {
                    logger.log(Level.INFO, String.format("[%s, type=%d]:second click npc=%d", this.getClass().getSimpleName(), event.getType(), event.getNpc().id));
                    if (player.debug) {
                        player.send(new SendMessage(String.format("[%s, type=%d]: npc=%d", this.getClass().getSimpleName(), event.getType(), event.getNpc().id)));
                    }
                    return true;
                }
                break;
            case 3:
                if (thirdClickNpc(player, event)) {
                    logger.log(Level.INFO, String.format("[%s, type=%d]:third click npc=%d", this.getClass().getSimpleName(), event.getType(), event.getNpc().id));
                    if (player.debug) {
                        player.send(new SendMessage(String.format("[%s, type=%d]: npc=%d", this.getClass().getSimpleName(), event.getType(), event.getNpc().id)));
                    }
                    return true;
                }
                break;
            case 4:
                if (fourthClickNpc(player, event)) {
                    logger.log(Level.INFO, String.format("[%s, type=%d]:fourth click npc=%d", this.getClass().getSimpleName(), event.getType(), event.getNpc().id));
                    if (player.debug) {
                        player.send(new SendMessage(String.format("[%s, type=%d]: npc=%d", this.getClass().getSimpleName(), event.getType(), event.getNpc().id)));
                    }
                    return true;
                }
                break;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, firstClickNpc(), fourthClickNpc(), logger, secondClickNpc(), com.runehive.game.world.entity.mob.player.Player.send(), and thirdClickNpc().
Referenced by accept().
handleObjectClickEvent()
boolean com.runehive.game.plugin.PluginContext.handleObjectClickEvent (Player player, ObjectClickEvent event) private
Definition at line 312 of file PluginContext.java.
{
        switch(event.getType()) {
                case 1:
                    if (firstClickObject(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]:first click object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId()));
                        if (player.debug) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId())));
                        }
                        return true;
                    }
                    break;
                case 2:
                    if (secondClickObject(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]:second click object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId()));
                        if (player.debug) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId())));
                        }
                        return true;
                    }
                    break;
                case 3:
                    if (thirdClickObject(player, event)) {
                        logger.log(Level.INFO, String.format("[%s, type=%d]:third click object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId()));
                        if (player.debug) {
                            player.send(new SendMessage(String.format("[%s, type=%d]: object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId())));
                        }
                        return true;
                    }
                    break;
            }
            return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, firstClickObject(), logger, secondClickObject(), com.runehive.game.world.entity.mob.player.Player.send(), and thirdClickObject().
Referenced by accept().
handlePickupItemEvent()
boolean com.runehive.game.plugin.PluginContext.handlePickupItemEvent (Player player, PickupItemEvent event) private
Definition at line 84 of file PluginContext.java.
{
        if (onPickupItem(player, event)) {
            logger.log(Level.INFO, String.format("player=%s picked up item=%d amount=%d position=%s", player.getName(), event.getItem().getId(), event.getItem().getAmount(), event.getPosition()));
            if (PlayerRight.isDeveloper(player)) {
                player.send(new SendMessage(String.format("[%s]: item=%d position=%s", this.getClass().getSimpleName(), event.getItem().getId(), event.getPosition().toString())));
            }
            World.getDataBus().publish(new PickupItemLogEvent(player, event.getGroundItem()));
            return true;
        }
        return false;
    }
References com.runehive.game.world.World.getDataBus(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), logger, onPickupItem(), com.runehive.game.event.bus.DataBus.publish(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by accept().
itemOnItem()
boolean com.runehive.game.plugin.PluginContext.itemOnItem (Player player, ItemOnItemEvent event) protected
Definition at line 308 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemOnItemEvent().
itemOnNpc()
boolean com.runehive.game.plugin.PluginContext.itemOnNpc (Player player, ItemOnNpcEvent event) protected
Definition at line 293 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemOnNpcEvent().
itemOnObject()
boolean com.runehive.game.plugin.PluginContext.itemOnObject (Player player, ItemOnObjectEvent event) protected
Definition at line 278 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemOnObjectEvent().
itemOnPlayer()
boolean com.runehive.game.plugin.PluginContext.itemOnPlayer (Player player, ItemOnPlayerEvent event) protected
Definition at line 263 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemOnPlayerEvent().
modifiableXItemContainer()
boolean com.runehive.game.plugin.PluginContext.modifiableXItemContainer (Player player, ItemContainerContextMenuEvent event) protected
Definition at line 235 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemContainerContextMenuEvent().
onClick()
boolean com.runehive.game.plugin.PluginContext.onClick (final Player player, final int button) protected
Definition at line 508 of file PluginContext.java.
{
        switch (button) {
            case 29404:
                player.send(new SendURL("https://runehive.com"));
                return true;
            case 29408:
            InterfaceWriter.write(new AchievementWriter(player));
            player.interfaceManager.setSidebar(Config.QUEST_TAB, 35_000);
            return true;
                  case 29411:
                InterfaceWriter.write(new InformationWriter(player));
                return true;
            case -30528:
                InterfaceWriter.write(new InformationWriter(player));
                player.interfaceManager.setSidebar(Config.QUEST_TAB, 29_400);
            return true;
            case -30525:
                player.dialogueFactory.sendOption("Activity Logger", () -> {
                    player.dialogueFactory.onAction(player.activityLogger::open);
                }, "Drop Simulator", () -> {
                    player.dialogueFactory.onAction(() -> DropSimulator.open(player));
               /* }, "Activity Logger", () -> {
                    player.dialogueFactory.onAction(player.activityLogger::open);*/
                }, "Title Manager", () -> {
                    player.dialogueFactory.onAction(() -> TitleManager.open(player));
                }, "Slayer Interface", () -> {
                    player.dialogueFactory.onAction(() -> player.slayer.open(SlayerTab.MAIN));
                }).execute();
                return true;
            case -30085:
                ProfileViewer.open(player, player);
                return true;
            case -30084:
                player.activityLogger.open();
                return true;
            case -30083:
                TitleManager.open(player);
                return true;
            case -30082:
                DropDisplay.open(player);
                return true;
            case -30081:
                DropSimulator.open(player);
                return true;
            case -30080:
                player.gameRecord.display(ActivityType.getFirst());
                return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.activityLogger, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.activity.record.PlayerRecord.display(), com.runehive.game.world.entity.mob.player.Player.gameRecord, com.runehive.content.activity.ActivityType.getFirst(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.content.skill.impl.slayer.SlayerTab.MAIN, com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.content.ActivityLogger.open(), com.runehive.content.DropDisplay.open(), com.runehive.content.ProfileViewer.open(), com.runehive.content.simulator.DropSimulator.open(), com.runehive.content.skill.impl.slayer.Slayer.open(), com.runehive.content.tittle.TitleManager.open(), com.runehive.Config.QUEST_TAB, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendOption(), com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar(), com.runehive.game.world.entity.mob.player.Player.slayer, and com.runehive.content.writer.InterfaceWriter.write().
Referenced by handleButtonClickEvent().
onDropItem()
boolean com.runehive.game.plugin.PluginContext.onDropItem (Player player, DropItemEvent event) protected
Definition at line 111 of file PluginContext.java.
{
        return false;
    }
Referenced by handleDropItemEvent().
onInit()
void com.runehive.game.plugin.PluginContext.onInit ()
Reimplemented in com.runehive.game.plugin.extension.CommandExtension.
Definition at line 39 of file PluginContext.java.
{
    }
Referenced by com.runehive.game.plugin.PluginManager.load().
onMovement()
boolean com.runehive.game.plugin.PluginContext.onMovement (Player player, MovementEvent event) protected
Definition at line 80 of file PluginContext.java.
{
        return false;
    }
Referenced by accept().
onPickupItem()
boolean com.runehive.game.plugin.PluginContext.onPickupItem (Player player, PickupItemEvent event) protected
Definition at line 96 of file PluginContext.java.
{
        return false;
    }
Referenced by handlePickupItemEvent().
secondClickItem()
boolean com.runehive.game.plugin.PluginContext.secondClickItem (Player player, ItemClickEvent event) protected
Definition at line 486 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemClickEvent().
secondClickItemContainer()
boolean com.runehive.game.plugin.PluginContext.secondClickItemContainer (Player player, ItemContainerContextMenuEvent event) protected
Definition at line 211 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemContainerContextMenuEvent().
secondClickNpc()
boolean com.runehive.game.plugin.PluginContext.secondClickNpc (Player player, NpcClickEvent event) protected
Definition at line 425 of file PluginContext.java.
{
        return false;
    }
Referenced by handleNpcClickEvent().
secondClickObject()
boolean com.runehive.game.plugin.PluginContext.secondClickObject (Player player, ObjectClickEvent event) protected
Definition at line 355 of file PluginContext.java.
{
        logger.log(Level.INFO, String.format("[%s, type=%d]:second click object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId()));
        if (player.debug) {
            player.send(new SendMessage(String.format("[%s, type=%d]: object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId())));
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, logger, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by handleObjectClickEvent().
sixthClickItemContainer()
boolean com.runehive.game.plugin.PluginContext.sixthClickItemContainer (Player player, ItemContainerContextMenuEvent event) protected
Definition at line 227 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemContainerContextMenuEvent().
thirdClickItem()
boolean com.runehive.game.plugin.PluginContext.thirdClickItem (Player player, ItemClickEvent event) protected
Definition at line 490 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemClickEvent().
thirdClickItemContainer()
boolean com.runehive.game.plugin.PluginContext.thirdClickItemContainer (Player player, ItemContainerContextMenuEvent event) protected
Definition at line 215 of file PluginContext.java.
{
        return false;
    }
Referenced by handleItemContainerContextMenuEvent().
thirdClickNpc()
boolean com.runehive.game.plugin.PluginContext.thirdClickNpc (Player player, NpcClickEvent event) protected
Definition at line 429 of file PluginContext.java.
{
        return false;
    }
Referenced by handleNpcClickEvent().
thirdClickObject()
boolean com.runehive.game.plugin.PluginContext.thirdClickObject (Player player, ObjectClickEvent event) protected
Definition at line 364 of file PluginContext.java.
{
        logger.log(Level.INFO, String.format("[%s, type=%d]:third click object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId()));
        if (player.debug) {
            player.send(new SendMessage(String.format("[%s, type=%d]: object=%d", this.getClass().getSimpleName(), event.getType(), event.getObject().getId())));
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.debug, logger, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by handleObjectClickEvent().
Member Data Documentation
logger
final Logger com.runehive.game.plugin.PluginContext.logger = LogManager.getLogger(PluginContext.class) static
Definition at line 37 of file PluginContext.java.
Referenced by accept(), firstClickObject(), handleDropItemEvent(), handleItemClickEvent(), handleItemContainerContextMenuEvent(), handleItemOnItemEvent(), handleItemOnNpcEvent(), handleItemOnObjectEvent(), handleNpcClickEvent(), handleObjectClickEvent(), handlePickupItemEvent(), secondClickObject(), and thirdClickObject().
The documentation for this class was generated from the following file:
java/com/runehive/game/plugin/PluginContext.java