RuneHive-Game: com.runehive.content.tradingpost.TradingPost Class Reference
com.runehive.content.tradingpost.TradingPost Class Reference
Classes
class TradingPostActiveListingSearch
enum TradingPostActiveListingSearchType
class TradingPostActiveListingSort
enum TradingPostSortType
Public Member Functions
void addSearchResultsAndUpdateInterface (TradingPostActiveListingSearch search)
void addToCoffer (String owner, int amount)
void addToItemHistory (ItemHistory itemHistory)
void buyingDialogueOptions (int amount)
void cleanUp ()
boolean delist (TradingPostListing listing)
CompletableFuture< Coffer > getCoffer (final String owner)
void getOrMakeNewCofferIfNotExists (final String owner, final Consumer< Coffer > useCoffer)
List< ItemHistory > getPlayersItemHistory ()
boolean handleButtonClick (int btnId)
void openOverviewInterface ()
void saveCoffer (final Coffer coffer)
void saveListings (final String owner, final List< TradingPostListing > listings)
void selectItemToList (Item item)
void sendItemHistoryData (List< ItemHistory > itemHistories)
void sortQuantity ()
void testData ()
TradingPost (Player player)
void updateCofferAmountWidget ()
void updatePriceStrings ()
void updateQuantityString ()
Static Public Member Functions
static void createFileAndDirIfNotExists (File file)
static void loadAllListings ()
static void loadItemHistory ()
static void loadRecentItemHistory ()
static void saveAllItemHistory ()
static void saveRecentHistory ()
Static Public Attributes
static final int BUYING_PAGE_INTERFACE_ID = 80174
Private Member Functions
void alertSeller (String sellerName, String item, int amount)
void clearSellingOverlay ()
void confirmToAddListing ()
void displayMostRecentListings ()
void editPriceInputPrompt ()
void editQuantityInputPrompt ()
Item[] getItemArrayFromActiveListings (List< TradingPostListing > list)
Item[] getItemArrayFromItemHistory (List< ItemHistory > list)
List< TradingPostListing > getListingsByName (String name)
List< TradingPostListing > getPageListings (List< TradingPostListing > listings)
List< TradingPostListing > getSearchResults (TradingPostActiveListingSearchType type, String search)
int getSlotSizeByDonatorRank ()
boolean handleBuyingButton (int btnId)
boolean handleDismissListingButton (int btnId)
boolean handleSellingOverlayButtons (int btnId)
void nextPage ()
void openSellingOverlay ()
void previousPage ()
void purchase (int amount)
void refresh ()
void searchExistingItemInput ()
void searchExistingListing (TradingPostActiveListingSearch search)
void searchItemHistoryInput ()
void searchPlayerInput ()
void sendOverviewWidgetVisibility (int i, boolean isHidden)
void sort ()
void sortPrice ()
void toggleBuyingPageWidgetVisibility (int i, boolean isHidden)
void toggleSellingOverlayVisibilityAndOpen (boolean isHidden)
void updateBuyingPageWidgets (List< TradingPostListing > listings)
void updateExistingListingsList ()
void updateExistingListingsWidgets ()
void withdrawFromCoffer ()
Private Attributes
final AhoCorasickDoubleArrayTrie< String > acdat = new AhoCorasickDoubleArrayTrie<>()
List< TradingPostListing > displayedPageListings = new ArrayList<>()
The displayed listings on the buying page.
TradingPostListing listingToAdd
The listing that the player will add to their existing listings.
TradingPostListing listingToBuy
The listing that the player selects in the buying page.
List< TradingPostListing > myListings = new ArrayList<>()
List containing the players existing listings/offers.
int page
The page # of the buying interface.
final Player player
final List< ItemHistory > playersItemHistory = new ArrayList<>()
contains last 50 players buying history
List< TradingPostListing > searchedListings = new ArrayList<>()
The current searched listings.
TradingPostActiveListingSearch tradingPostSearch
The current item or player search.
TradingPostActiveListingSort tradingPostSort
The current sort of the buyable listings.
Static Private Attributes
static final Map< String, Coffer > allCoffers = Collections.synchronizedMap(new HashMap<>())
Hashmap containing the coffers <PlayerName, Coffer>
static final List< TradingPostListing > allListings = new ArrayList<>()
A list containing all the trading post listings.
static final int CURRENCY_ID = 995
static final int HISTORY_PAGE_INTERFACE_ID = 80616
static final Map< String, List< ItemHistory > > itemHistories = new HashMap<>()
Contains a list of the last 50 sold of each item.
static final Logger logger = LoggerFactory.getLogger(TradingPost.class)
static final int MAX_LISTING_SIZE = 20
static final int MAX_LISTINGS_SHOWN = 50
static final int OVERVIEW_INTERFACE_ID = 80000
static final List< ItemHistory > recentlySoldItems = new ArrayList<>()
contains the last 50 sold items on the trading post
static final int TAX_RATE = 10
Detailed Description
Definition at line 33 of file TradingPost.java.
Constructor & Destructor Documentation
TradingPost()
com.runehive.content.tradingpost.TradingPost.TradingPost (Player player)
Definition at line 114 of file TradingPost.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
addSearchResultsAndUpdateInterface()
void com.runehive.content.tradingpost.TradingPost.addSearchResultsAndUpdateInterface (TradingPostActiveListingSearch search)
Definition at line 426 of file TradingPost.java.
{
        searchedListings.clear();
        searchedListings.addAll(getSearchResults(search.searchType,search.text));
        updateBuyingPageWidgets(getPageListings(searchedListings));
    }
References getPageListings(), getSearchResults(), searchedListings, com.runehive.content.tradingpost.TradingPost.TradingPostActiveListingSearch.searchType, com.runehive.content.tradingpost.TradingPost.TradingPostActiveListingSearch.text, and updateBuyingPageWidgets().
Referenced by displayMostRecentListings(), purchase(), refresh(), and searchExistingListing().
addToCoffer()
void com.runehive.content.tradingpost.TradingPost.addToCoffer (String owner, int amount)
Definition at line 784 of file TradingPost.java.
{
        getOrMakeNewCofferIfNotExists(owner, coffer -> {
            coffer.addAmount((int) (amount - (TAX_RATE/100.0*amount)));
            saveCoffer(coffer);
        });
    }
References getOrMakeNewCofferIfNotExists(), saveCoffer(), and TAX_RATE.
Referenced by purchase().
addToItemHistory()
void com.runehive.content.tradingpost.TradingPost.addToItemHistory (ItemHistory itemHistory)
Definition at line 762 of file TradingPost.java.
{
        List<ItemHistory> itemHistoryList = itemHistories.computeIfAbsent(ItemDefinition.get(itemHistory.getItemId()).getName(), x -> new ArrayList<>());
        if(itemHistoryList.size() == 50) {
            itemHistoryList.remove(49);
        }
        itemHistoryList.add(itemHistory);
        if(recentlySoldItems.size() == 50) {
            recentlySoldItems.remove(49);
        }
        recentlySoldItems.add(itemHistory);
        if(playersItemHistory.size() == 50) {
            playersItemHistory.remove(49);
        }
        playersItemHistory.add(itemHistory);
    }
References com.runehive.game.world.items.ItemDefinition.get(), com.runehive.content.tradingpost.ItemHistory.getItemId(), com.runehive.game.world.items.ItemDefinition.getName(), itemHistories, playersItemHistory, and recentlySoldItems.
Referenced by purchase().
alertSeller()
void com.runehive.content.tradingpost.TradingPost.alertSeller (String sellerName, String item, int amount) private
Definition at line 693 of file TradingPost.java.
{
        Optional<Player> playerOptional = World.search(sellerName);
        if(playerOptional.isPresent()) {
            Player player = playerOptional.get();
            player.send(new SendMessage("@red@Trading post: " + amount + " of your " + item + "s have been sold"));
            player.tradingPost.updateExistingListingsList();
            if(player.interfaceManager.hasAnyOpen(OVERVIEW_INTERFACE_ID)) {
                player.tradingPost.openOverviewInterface();
            }
        }
    }
References OVERVIEW_INTERFACE_ID, player, and com.runehive.game.world.World.search().
Referenced by purchase().
buyingDialogueOptions()
void com.runehive.content.tradingpost.TradingPost.buyingDialogueOptions (int amount)
Definition at line 677 of file TradingPost.java.
{
        if((long)amount + listingToBuy.getPrice() > Integer.MAX_VALUE) {
            player.send(new SendMessage("Cannot buy this quantity for this price."));
            return;
        }
        if(amount > listingToBuy.getAmountLeft()) {
            amount = listingToBuy.getAmountLeft();
        }
        int finalAmount = amount;
        player.dialogueFactory.sendStatement("Purchase " + amount + " of " + ItemDefinition.get(listingToBuy.getItemId()).getName(),
                        "for <col=A52929>" + Utility.formatDigits(listingToBuy.getPrice()*amount) + " " + ItemDefinition.get(CURRENCY_ID).getName() + "?")
                .sendOption("Yes", () -> purchase(finalAmount), "Nevermind", () -> player.dialogueFactory.clear()).execute();
    }
References CURRENCY_ID, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), listingToBuy, player, and purchase().
Referenced by handleBuyingButton().
cleanUp()
void com.runehive.content.tradingpost.TradingPost.cleanUp ()
Definition at line 847 of file TradingPost.java.
{
        displayedPageListings.clear();
        searchedListings.clear();
        tradingPostSearch = null;
        tradingPostSort = null;
        listingToAdd = null;
        listingToBuy = null;
        page = 0;
    }
References displayedPageListings, listingToAdd, listingToBuy, page, searchedListings, tradingPostSearch, and tradingPostSort.
Referenced by openOverviewInterface(), and searchExistingListing().
clearSellingOverlay()
void com.runehive.content.tradingpost.TradingPost.clearSellingOverlay () private
Definition at line 555 of file TradingPost.java.
{
        player.send(new SendItemOnInterface(80153, new Item(-1,0)));
        player.send(new SendString("",80160));
        player.send(new SendString("",80161));
        player.send(new SendString("",80162));
        player.send(new SendString("",80163));
        player.send(new SendString("",80173));
    }
References player.
Referenced by openSellingOverlay().
confirmToAddListing()
void com.runehive.content.tradingpost.TradingPost.confirmToAddListing () private
Definition at line 572 of file TradingPost.java.
{
        if(listingToAdd.getPrice() == 0) {
            player.send(new SendMessage("Unable to add listing with a price of zero."));
            return;
        }
        if(myListings.size() > getSlotSizeByDonatorRank()) {
            player.send(new SendMessage("Unable to add listing with max number listings listed."));
            return;
        }
        if(player.inventory.remove(listingToAdd.getItemId(), listingToAdd.getInitialQuantity())) {
            allListings.add(listingToAdd);
            updateExistingListingsList();
            openSellingOverlay();
            updateExistingListingsWidgets();
            saveListings(player.getName(),getListingsByName(player.getName()));
        } else {
            player.send(new SendMessage("Unable to list this item. Please try again."));
        }
    }
References allListings, getListingsByName(), getSlotSizeByDonatorRank(), listingToAdd, myListings, openSellingOverlay(), player, saveListings(), updateExistingListingsList(), and updateExistingListingsWidgets().
Referenced by handleSellingOverlayButtons().
createFileAndDirIfNotExists()
void com.runehive.content.tradingpost.TradingPost.createFileAndDirIfNotExists (File file) static
Definition at line 1061 of file TradingPost.java.
{
        if (!file.getParentFile().exists() || !file.exists()) {
            try {
                file.getParentFile().mkdirs();
                file.createNewFile();
            } catch (SecurityException e) {
                System.out.println("Unable to create directory");
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }
Referenced by loadItemHistory(), and loadRecentItemHistory().
delist()
boolean com.runehive.content.tradingpost.TradingPost.delist (TradingPostListing listing)
Definition at line 831 of file TradingPost.java.
{
        if(myListings.isEmpty()) {
            return false;
        }
        if(!myListings.contains(listing)) {
            return false;
        }
        if(!allListings.contains(listing)) {
            return false;
        }
        return allListings.remove(listing) && myListings.remove(listing);
    }
References allListings, and myListings.
Referenced by handleDismissListingButton().
displayMostRecentListings()
void com.runehive.content.tradingpost.TradingPost.displayMostRecentListings () private
Definition at line 404 of file TradingPost.java.
{
        if(!player.interfaceManager.isInterfaceOpen(BUYING_PAGE_INTERFACE_ID)) {
            player.interfaceManager.open(BUYING_PAGE_INTERFACE_ID);
        }
        player.send(new SendString("Search: Most recent",80176));
        tradingPostSearch = new TradingPostActiveListingSearch(TradingPostActiveListingSearchType.MOST_RECENT, "");
        addSearchResultsAndUpdateInterface(tradingPostSearch);
    }
References addSearchResultsAndUpdateInterface(), BUYING_PAGE_INTERFACE_ID, com.runehive.content.tradingpost.TradingPost.TradingPostActiveListingSearchType.MOST_RECENT, player, and tradingPostSearch.
Referenced by handleButtonClick(), purchase(), refresh(), and searchExistingListing().
editPriceInputPrompt()
void com.runehive.content.tradingpost.TradingPost.editPriceInputPrompt () private
Definition at line 568 of file TradingPost.java.
{
        player.send(new SendInputAmount("How much would you like sell this for?", 10, input -> listingToAdd.setPrice(player, Integer.parseInt(input))));
    }
References listingToAdd, and player.
Referenced by handleSellingOverlayButtons().
editQuantityInputPrompt()
void com.runehive.content.tradingpost.TradingPost.editQuantityInputPrompt () private
Definition at line 564 of file TradingPost.java.
{
        player.send(new SendInputAmount("How many would you like to sell?", 10, input -> listingToAdd.setQuantity(player,Integer.parseInt(input))));
    }
References listingToAdd, and player.
Referenced by handleSellingOverlayButtons().
getCoffer()
CompletableFuture< Coffer > com.runehive.content.tradingpost.TradingPost.getCoffer (final String owner)
Definition at line 896 of file TradingPost.java.
{
        final Coffer cachedCoffer = allCoffers.get(owner);
        if (cachedCoffer != null) {
            return CompletableFuture.completedFuture(cachedCoffer);
        }
        // retrieve coffer if coffer hasn't been retrieved since server start
        return CompletableFuture.supplyAsync(() -> {
            final Path path = Path.of("./data/profile/save/tradingpost/coffers/", owner, ".json");
            if (!Files.exists(path)) {
                return null;
            }
            final Gson gson = GsonUtils.JSON_ALLOW_NULL.get();
            try (final BufferedReader reader = Files.newBufferedReader(path)) {
                final Coffer coffer = gson.fromJson(reader, Coffer.class);
                if (coffer != null) {
                    allCoffers.put(coffer.getOwner(), coffer);
                    return coffer;
                }
            } catch (final IOException e) {
                logger.error("Failed reading coffer for \"" + owner + "\"", e);
            }
            return null;
        });
    }
References allCoffers, com.runehive.content.tradingpost.Coffer.getOwner(), com.runehive.util.GsonUtils.JSON_ALLOW_NULL, and logger.
Referenced by getOrMakeNewCofferIfNotExists().
getItemArrayFromActiveListings()
Item[] com.runehive.content.tradingpost.TradingPost.getItemArrayFromActiveListings (List< TradingPostListing > list) private
Definition at line 604 of file TradingPost.java.
{
        return list
                .stream()
                .map(tradingPostListing -> new Item(ItemDefinition.get(tradingPostListing.getItemId()).isNoted()
                        ?  ItemDefinition.get(tradingPostListing.getItemId()).getUnnotedId()
                        : tradingPostListing.getItemId(), tradingPostListing.getAmountLeft()))
                .toArray(Item[]::new);
    }
References com.runehive.game.world.items.ItemDefinition.get(), and com.runehive.game.world.items.ItemDefinition.isNoted().
Referenced by updateBuyingPageWidgets(), and updateExistingListingsWidgets().
getItemArrayFromItemHistory()
Item[] com.runehive.content.tradingpost.TradingPost.getItemArrayFromItemHistory (List< ItemHistory > list) private
Definition at line 613 of file TradingPost.java.
{
        return list
                .stream()
                .map(ih -> new Item(ItemDefinition.get(ih.getItemId()).isNoted()
                        ?  ItemDefinition.get(ih.getItemId()).getUnnotedId()
                        : ih.getItemId(), ih.getQuantity()))
                .toArray(Item[]::new);
    }
References com.runehive.game.world.items.ItemDefinition.get(), and com.runehive.game.world.items.ItemDefinition.isNoted().
Referenced by sendItemHistoryData().
getListingsByName()
List< TradingPostListing > com.runehive.content.tradingpost.TradingPost.getListingsByName (String name) private
Definition at line 597 of file TradingPost.java.
{
        return allListings
                .stream()
                .filter(tradingPostListing -> tradingPostListing.getSeller().equals(name))
                .collect(Collectors.toList());
    }
References allListings.
Referenced by confirmToAddListing(), handleDismissListingButton(), purchase(), and updateExistingListingsList().
getOrMakeNewCofferIfNotExists()
void com.runehive.content.tradingpost.TradingPost.getOrMakeNewCofferIfNotExists (final String owner, final Consumer< Coffer > useCoffer)
Definition at line 791 of file TradingPost.java.
{
        getCoffer(owner).thenAccept(coffer -> {
            if (coffer == null) {
                coffer = allCoffers.compute(owner, (k, v) -> new Coffer(owner));
                saveCoffer(coffer);
            }
            useCoffer.accept(coffer);
        });
    }
References allCoffers, getCoffer(), and saveCoffer().
Referenced by addToCoffer(), updateCofferAmountWidget(), and withdrawFromCoffer().
getPageListings()
List< TradingPostListing > com.runehive.content.tradingpost.TradingPost.getPageListings (List< TradingPostListing > listings) private
Definition at line 450 of file TradingPost.java.
{
        return listings.subList(
                        Math.min(listings.size(), page * MAX_LISTINGS_SHOWN),
                        Math.min(listings.size(), (page * MAX_LISTINGS_SHOWN + MAX_LISTINGS_SHOWN))).
                stream()
                .filter(tradingPostListing -> !tradingPostListing.getSeller().equalsIgnoreCase(player.getName()))
                .limit(MAX_LISTINGS_SHOWN)
                .collect(Collectors.toList());
    }
References MAX_LISTINGS_SHOWN, page, and player.
Referenced by addSearchResultsAndUpdateInterface(), nextPage(), previousPage(), and sort().
getPlayersItemHistory()
List< ItemHistory > com.runehive.content.tradingpost.TradingPost.getPlayersItemHistory ()
Definition at line 1074 of file TradingPost.java.
{
        return playersItemHistory;
    }
References playersItemHistory.
getSearchResults()
List< TradingPostListing > com.runehive.content.tradingpost.TradingPost.getSearchResults (TradingPostActiveListingSearchType type, String search) private
Definition at line 432 of file TradingPost.java.
{
        if(type == TradingPostActiveListingSearchType.MOST_RECENT) {
            return Lists.reverse(allListings);
        }
        List<TradingPostListing> temp = new ArrayList<>();
        TreeMap<String, String> map = new TreeMap<>();
        map.put(search,search);
        tradingPostSearch.acdat.build(map);
        for(TradingPostListing listing : allListings) {
            tradingPostSearch.acdat.parseText(type == TradingPostActiveListingSearchType.ITEM ? ItemDefinition.get(listing.getItemId()).getName().toLowerCase() : listing.getSeller().toLowerCase(), (begin, end, value) -> {
                if(!temp.contains(listing)) {
                    temp.add(listing);
                }
            });
        }
        return temp;
    }
References allListings, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.content.tradingpost.TradingPost.TradingPostActiveListingSearchType.ITEM, com.runehive.content.tradingpost.TradingPost.TradingPostActiveListingSearchType.MOST_RECENT, and tradingPostSearch.
Referenced by addSearchResultsAndUpdateInterface().
getSlotSizeByDonatorRank()
int com.runehive.content.tradingpost.TradingPost.getSlotSizeByDonatorRank () private
Definition at line 499 of file TradingPost.java.
{
        switch (player.right) {
            case KING_DONATOR -> {
                return MAX_LISTING_SIZE;
            }
            case ELITE_DONATOR -> {
                return 18;
            }
            case EXTREME_DONATOR -> {
                return 15;
            }
            case SUPER_DONATOR -> {
                return 12;
            }
            case DONATOR -> {
                return 10;
            }
            default -> {
                return 5;
            }
        }
    }
References MAX_LISTING_SIZE, and player.
Referenced by confirmToAddListing().
handleButtonClick()
boolean com.runehive.content.tradingpost.TradingPost.handleButtonClick (int btnId)
Definition at line 133 of file TradingPost.java.
{
        if(!player.interfaceManager.hasAnyOpen(OVERVIEW_INTERFACE_ID, BUYING_PAGE_INTERFACE_ID,HISTORY_PAGE_INTERFACE_ID)) {
            return false;
        }
        switch (btnId) {
            case 14650:
            case 15418:
                openOverviewInterface();
                return true;
            case 15091:
            case 14597:
                searchItemHistoryInput();
                return true;
            case 14600:
                searchPlayerInput();
                return true;
            case 14603:
                displayMostRecentListings();
                return true;
            case 14662:
                player.dialogueFactory.sendOption("Search item", this::searchExistingItemInput, "Search player", this::searchPlayerInput, "Nevermind", () -> player.dialogueFactory.clear()).execute();
                return true;
            case 14474:
                searchExistingItemInput();
                return true;
            case 14477:
                openSellingOverlay();
                return true;
            case 14484:
                sendItemHistoryData(playersItemHistory);
                return true;
            case 14487:
                sendItemHistoryData(recentlySoldItems);
                return true;
            case 14614:
                toggleSellingOverlayVisibilityAndOpen(true);
                return true;
            case 14659:
                nextPage();
                return true;
            case 14653:
                previousPage();
                return true;
            case 14656:
                refresh();
                return true;
            case 14466:
                withdrawFromCoffer();
                return true;
            case 14649:
                sortPrice();
                return true;
            case 14648:
                sortQuantity();
                return true;
            default: {
                /*
                 * Returns true or false based on button ids
                 */
                if(handleBuyingButton(btnId) || handleDismissListingButton(btnId) || handleSellingOverlayButtons(btnId)) {
                    return true;
                }
            }
        }
        return false;
    }
References BUYING_PAGE_INTERFACE_ID, displayMostRecentListings(), handleBuyingButton(), handleDismissListingButton(), handleSellingOverlayButtons(), HISTORY_PAGE_INTERFACE_ID, nextPage(), openOverviewInterface(), openSellingOverlay(), OVERVIEW_INTERFACE_ID, player, playersItemHistory, previousPage(), recentlySoldItems, refresh(), searchExistingItemInput(), searchItemHistoryInput(), searchPlayerInput(), sendItemHistoryData(), sortPrice(), sortQuantity(), toggleSellingOverlayVisibilityAndOpen(), and withdrawFromCoffer().
handleBuyingButton()
boolean com.runehive.content.tradingpost.TradingPost.handleBuyingButton (int btnId) private
Definition at line 647 of file TradingPost.java.
{
        if(btnId >= 14878 && btnId <= 14927) {
            int index = btnId - 14878;
            if(displayedPageListings.size() < index) {
                return true;
            }
            TradingPostListing temp = displayedPageListings.get(index);
            if(temp == null) {
                return true;
            }
            if(!allListings.contains(temp)) {
                return true;
            }
            listingToBuy = temp;
            if(listingToBuy.getAmountLeft() > 1) {
                player.send(new SendInputAmount("How many of " + ItemDefinition.get(listingToBuy.getItemId()).getName() + "?", 10, input -> buyingDialogueOptions(Integer.parseInt(input))));
            } else {
                buyingDialogueOptions(1);
            }
        }
        return false;
    }
References allListings, buyingDialogueOptions(), displayedPageListings, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), listingToBuy, and player.
Referenced by handleButtonClick().
handleDismissListingButton()
boolean com.runehive.content.tradingpost.TradingPost.handleDismissListingButton (int btnId) private
Definition at line 803 of file TradingPost.java.
{
        if(btnId >= 14516 && btnId <= 14535) {
            int index = btnId - 14516;
            if(myListings.isEmpty()) {
                return true;
            }
            if(myListings.size() < index) {
                return true;
            }
            TradingPostListing listing = myListings.get(index);
            if(!delist(listing)) {
                player.send(new SendMessage("Unable to delist this item. Please try again."));
            } else {
                saveListings(player.getName(),getListingsByName(player.getName()));
                player.inventory.addOrBank(new Item(listing.getItemId(),listing.getAmountLeft()));
                openOverviewInterface();
            }
            return true;
        }
        return false;
    }
References delist(), com.runehive.content.tradingpost.TradingPostListing.getAmountLeft(), com.runehive.content.tradingpost.TradingPostListing.getItemId(), getListingsByName(), myListings, openOverviewInterface(), player, and saveListings().
Referenced by handleButtonClick().
handleSellingOverlayButtons()
boolean com.runehive.content.tradingpost.TradingPost.handleSellingOverlayButtons (int btnId) private
Definition at line 380 of file TradingPost.java.
{
        if(listingToAdd == null) return false;
        switch (btnId) {
            case 14618:
                listingToAdd.addQuantity(player,1);
                return true;
            case 14621:
                listingToAdd.removeQuantity(player,1);
                return true;
            case 14636:
                editQuantityInputPrompt();
                return true;
            case 14628:
                editPriceInputPrompt();
                return true;
            case 14631:
                confirmToAddListing();
                return true;
        }
        return false;
    }
References confirmToAddListing(), editPriceInputPrompt(), editQuantityInputPrompt(), listingToAdd, and player.
Referenced by handleButtonClick().
loadAllListings()
void com.runehive.content.tradingpost.TradingPost.loadAllListings () static
Definition at line 948 of file TradingPost.java.
{
        try {
            File folder = new File("./data/profile/save/tradingpost/listings/");
            File[] files = folder.listFiles();
            if (files == null) return;
            for(File f : files) {
                File toRead = null;
                if(f.isDirectory()) {
                    toRead = Objects.requireNonNull(f.getAbsoluteFile().listFiles())[0];
                }
                try {
                    assert toRead != null;
                    final Gson gson = GsonUtils.JSON_ALLOW_NULL.get();
                    try (final BufferedReader reader = Files.newBufferedReader(Path.of(toRead.getPath()))) {
                        final List<TradingPostListing> listings = List.of(gson.fromJson(reader, TradingPostListing[].class));
                        allListings.addAll(listings);
                    } catch (final IOException e) {
                        logger.error("Failed reading listings", e);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
References allListings, com.runehive.util.GsonUtils.JSON_ALLOW_NULL, and logger.
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
loadItemHistory()
void com.runehive.content.tradingpost.TradingPost.loadItemHistory () static
Definition at line 1020 of file TradingPost.java.
{
        Path path = Paths.get("./data/profile/save/tradingpost/itemhistory.json");
        File file = path.toFile();
        createFileAndDirIfNotExists(file);
        if(file.length() == 0) return;
        try (FileReader fileReader = new FileReader(file)) {
            JsonParser fileParser = new JsonParser();
            Gson builder = new GsonBuilder()
                    .create();
            JsonObject reader = (JsonObject) fileParser.parse(fileReader);
            HashMap<String,  List<ItemHistory>> itemHistory = builder.fromJson(reader.get("itemhistory"),
                    new TypeToken<HashMap<String, List<ItemHistory>>>() {
                    }.getType());
            itemHistories.putAll(itemHistory);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
References createFileAndDirIfNotExists(), and itemHistories.
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
loadRecentItemHistory()
void com.runehive.content.tradingpost.TradingPost.loadRecentItemHistory () static
Definition at line 1042 of file TradingPost.java.
{
        Path path = Paths.get("./data/profile/save/tradingpost/itemhistoryrecent.json");
        File file = path.toFile();
        createFileAndDirIfNotExists(file);
        if(file.length() == 0) return;
        try (FileReader fileReader = new FileReader(file)) {
            JsonParser fileParser = new JsonParser();
            Gson builder = new GsonBuilder()
                    .create();
            JsonObject reader = (JsonObject) fileParser.parse(fileReader);
            ItemHistory[] temp = builder.fromJson(reader.get("recentitemhistory").getAsJsonArray(), ItemHistory[].class);
            recentlySoldItems.addAll(Arrays.asList(temp));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
References createFileAndDirIfNotExists(), and recentlySoldItems.
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
nextPage()
void com.runehive.content.tradingpost.TradingPost.nextPage () private
Definition at line 362 of file TradingPost.java.
{
        page++;
        List<TradingPostListing> temp;
        temp = getPageListings(searchedListings);
        if(temp.isEmpty()) {
            page--;
            player.send(new SendMessage("No more results on the next page"));
        } else {
            updateBuyingPageWidgets(temp);
        }
    }
References getPageListings(), page, player, searchedListings, and updateBuyingPageWidgets().
Referenced by handleButtonClick().
openOverviewInterface()
void com.runehive.content.tradingpost.TradingPost.openOverviewInterface ()
Definition at line 118 of file TradingPost.java.
{
        cleanUp();
        updateExistingListingsList();
        updateExistingListingsWidgets();
        updateCofferAmountWidget();
        toggleSellingOverlayVisibilityAndOpen(true);
        player.interfaceManager.open(OVERVIEW_INTERFACE_ID);
    }
References cleanUp(), OVERVIEW_INTERFACE_ID, player, toggleSellingOverlayVisibilityAndOpen(), updateCofferAmountWidget(), updateExistingListingsList(), and updateExistingListingsWidgets().
Referenced by handleButtonClick(), and handleDismissListingButton().
openSellingOverlay()
void com.runehive.content.tradingpost.TradingPost.openSellingOverlay () private
Definition at line 523 of file TradingPost.java.
{
        clearSellingOverlay();
        toggleSellingOverlayVisibilityAndOpen(false);
        listingToAdd = null;
        player.send(new SendInventoryInterface(OVERVIEW_INTERFACE_ID, 65300));
        player.send(new SendItemOnInterface(65301, player.inventory.toArray()));
    }
References clearSellingOverlay(), listingToAdd, OVERVIEW_INTERFACE_ID, player, and toggleSellingOverlayVisibilityAndOpen().
Referenced by confirmToAddListing(), and handleButtonClick().
previousPage()
void com.runehive.content.tradingpost.TradingPost.previousPage () private
Definition at line 374 of file TradingPost.java.
{
        if(page == 0) return;
        page--;
        updateBuyingPageWidgets(getPageListings(searchedListings));
    }
References getPageListings(), page, searchedListings, and updateBuyingPageWidgets().
Referenced by handleButtonClick().
purchase()
void com.runehive.content.tradingpost.TradingPost.purchase (int amount) private
Definition at line 709 of file TradingPost.java.
{
        if(listingToBuy == null) {
            return;
        }
        int getPlayerCurrencyAmount = player.inventory.computeAmountForId(CURRENCY_ID);
        int totalPrice = listingToBuy.getPrice()*amount;
        if(totalPrice > getPlayerCurrencyAmount) {
            player.send(new SendMessage("Insufficient " + ItemDefinition.get(CURRENCY_ID).getName() + " to complete your transaction."));
            return;
        }
        if(amount > listingToBuy.getAmountLeft()) {
            amount = listingToBuy.getAmountLeft();
            player.send(new SendMessage("Your purchase amount has been lowered to " + amount));
        }
        if(!allListings.contains(listingToBuy)) {
            player.send(new SendMessage("This item does not exist in the trading post anymore."));
            return;
        }
        if(player.inventory.add(listingToBuy.getItemId(), amount)) {
            player.inventory.remove(CURRENCY_ID,totalPrice);
            listingToBuy.addToAmountSold(amount);
            if(listingToBuy.getAmountLeft() == 0) {
                allListings.remove(listingToBuy);
                displayedPageListings.remove(listingToBuy);
                searchedListings.remove(listingToBuy);
            }
            if(tradingPostSearch != null) {
                addSearchResultsAndUpdateInterface(tradingPostSearch);
            } else {
                displayMostRecentListings();
            }
            addToCoffer(listingToBuy.getSeller(),listingToBuy.getPrice()*amount);
            alertSeller(listingToBuy.getSeller(),ItemDefinition.get(listingToBuy.getItemId()).getName(), amount);
            String seller = listingToBuy.getSeller();
            saveListings(seller,getListingsByName(seller));
            addToItemHistory(new ItemHistory(amount, listingToBuy.getItemId(), listingToBuy.getPrice()*amount, listingToBuy.getSeller(), player.getName()));
        } else {
            player.send(new SendMessage("You do not have enough inventory spaces to complete this transaction"));
        }
    }
References addSearchResultsAndUpdateInterface(), addToCoffer(), addToItemHistory(), alertSeller(), allListings, CURRENCY_ID, displayedPageListings, displayMostRecentListings(), com.runehive.game.world.items.ItemDefinition.get(), getListingsByName(), com.runehive.game.world.items.ItemDefinition.getName(), listingToBuy, player, saveListings(), searchedListings, and tradingPostSearch.
Referenced by buyingDialogueOptions().
refresh()
void com.runehive.content.tradingpost.TradingPost.refresh () private
Definition at line 354 of file TradingPost.java.
{
        if(tradingPostSearch != null) {
            addSearchResultsAndUpdateInterface(tradingPostSearch);
        } else {
            displayMostRecentListings();
        }
    }
References addSearchResultsAndUpdateInterface(), displayMostRecentListings(), and tradingPostSearch.
Referenced by handleButtonClick().
saveAllItemHistory()
void com.runehive.content.tradingpost.TradingPost.saveAllItemHistory () static
Definition at line 976 of file TradingPost.java.
{
        Path path = Paths.get("./data/profile/save/tradingpost/itemhistory.json");
        File file = path.toFile();
        file.getParentFile().setWritable(true);
        if(!file.getParentFile().exists()) {
            try {
                file.getParentFile().mkdirs();
            } catch (SecurityException e) {
                System.out.println("Error while creating item history directory");
            }
        }
        try(FileWriter writer = new FileWriter(file)) {
            Gson builder = new GsonBuilder().setPrettyPrinting().create();
            JsonObject object = new JsonObject();
            object.add("itemhistory",builder.toJsonTree(itemHistories));
            writer.write(builder.toJson(object));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
References itemHistories.
Referenced by com.runehive.game.world.World.save().
saveCoffer()
void com.runehive.content.tradingpost.TradingPost.saveCoffer (final Coffer coffer)
Definition at line 872 of file TradingPost.java.
{
        Thread.startVirtualThread(() -> {
            try {
                final String json = GsonUtils.JSON_PRETTY_ALLOW_NULL.get().toJson(coffer);
                final Path path = Path.of("./data/profile/save/tradingpost/coffers/", coffer.getOwner(), ".json");
                Path parent = path.getParent();
                if (parent == null) {
                    throw new UnsupportedOperationException("Path must have a parent " + path);
                }
                if (!Files.exists(parent)) {
                    parent = Files.createDirectories(parent);
                }
                final Path tempFile = Files.createTempFile(parent, path.getFileName().toString(), ".tmp");
                Files.writeString(tempFile, json, StandardCharsets.UTF_8);
                Files.move(tempFile, path, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
            } catch (final Exception ex) {
                logger.error(String.format("Error while saving player=%s", player.getName()), ex);
            }
        });
    }
References com.runehive.content.tradingpost.Coffer.getOwner(), com.runehive.util.GsonUtils.JSON_PRETTY_ALLOW_NULL, logger, and player.
Referenced by addToCoffer(), getOrMakeNewCofferIfNotExists(), and withdrawFromCoffer().
saveListings()
void com.runehive.content.tradingpost.TradingPost.saveListings (final String owner, final List< TradingPostListing > listings)
Definition at line 923 of file TradingPost.java.
{
        Thread.startVirtualThread(() -> {
           try {
               final String json = GsonUtils.JSON_PRETTY_ALLOW_NULL.get().toJson(listings);
               final Path path = Path.of("./data/profile/save/tradingpost/listings/", owner, ".json");
               Path parent = path.getParent();
               if (parent == null) {
                   throw new UnsupportedOperationException("Path must have a parent " + path);
               }
               if (!Files.exists(parent)) {
                   parent = Files.createDirectories(parent);
               }
               final Path tempFile = Files.createTempFile(parent, path.getFileName().toString(), ".tmp");
               Files.writeString(tempFile, json, StandardCharsets.UTF_8);
               Files.move(tempFile, path, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
           } catch (final Exception ex) {
               logger.error(String.format("Error while saving player=%s", player.getName()), ex);
           }
        });
    }
References com.runehive.util.GsonUtils.JSON_PRETTY_ALLOW_NULL, logger, and player.
Referenced by confirmToAddListing(), handleDismissListingButton(), and purchase().
saveRecentHistory()
void com.runehive.content.tradingpost.TradingPost.saveRecentHistory () static
Definition at line 998 of file TradingPost.java.
{
        Path path = Paths.get("./data/profile/save/tradingpost/itemhistoryrecent.json");
        File file = path.toFile();
        file.getParentFile().setWritable(true);
        if(!file.getParentFile().exists()) {
            try {
                file.getParentFile().mkdirs();
            } catch (SecurityException e) {
                System.out.println("Error while creating recent item history directory");
            }
        }
        try(FileWriter writer = new FileWriter(file)) {
            Gson builder = new GsonBuilder().setPrettyPrinting().create();
            JsonObject object = new JsonObject();
            object.add("recentitemhistory",builder.toJsonTree(recentlySoldItems));
            writer.write(builder.toJson(object));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
References recentlySoldItems.
Referenced by com.runehive.game.world.World.save().
searchExistingItemInput()
void com.runehive.content.tradingpost.TradingPost.searchExistingItemInput () private
Definition at line 256 of file TradingPost.java.
{
        World.schedule(new Task(1) { // task added so input prompt shows after dialogue
            @Override
            protected void execute() {
                player.send(new SendInputMessage("Enter item name to search for:", 16, input -> {
                    searchExistingListing(new TradingPostActiveListingSearch(TradingPostActiveListingSearchType.ITEM, String.valueOf(input)));
                    player.interfaceManager.open(BUYING_PAGE_INTERFACE_ID);
                }));
                this.cancel();
            }
        });
    }
References BUYING_PAGE_INTERFACE_ID, com.runehive.content.tradingpost.TradingPost.TradingPostActiveListingSearchType.ITEM, player, com.runehive.game.world.World.schedule(), and searchExistingListing().
Referenced by handleButtonClick().
searchExistingListing()
void com.runehive.content.tradingpost.TradingPost.searchExistingListing (TradingPostActiveListingSearch search) private
Definition at line 414 of file TradingPost.java.
{
        if(search.text.length() == 0) {
            cleanUp();
            displayMostRecentListings();
            return;
        }
        tradingPostSearch = search;
        this.page = 0;
        addSearchResultsAndUpdateInterface(search);
        player.send(new SendString("Search: " + tradingPostSearch.text,80176));
    }
References addSearchResultsAndUpdateInterface(), cleanUp(), displayMostRecentListings(), player, com.runehive.content.tradingpost.TradingPost.TradingPostActiveListingSearch.text, and tradingPostSearch.
Referenced by searchExistingItemInput(), and searchPlayerInput().
searchItemHistoryInput()
void com.runehive.content.tradingpost.TradingPost.searchItemHistoryInput () private
Definition at line 202 of file TradingPost.java.
{
        player.send(new SendInputMessage("Enter item name to search history for:", 16, input -> {
            if(Objects.equals(input, "")) {
                sendItemHistoryData(recentlySoldItems);
                return;
            }
            List<ItemHistory> historyItems = new ArrayList<>();
            TreeMap<String, String> map = new TreeMap<>();
            map.put(input,input);
            acdat.build(map);
            for(Map.Entry<String, List<ItemHistory>> lf : itemHistories.entrySet()) {
                acdat.parseText(lf.getKey().toLowerCase(), (b,e,v) -> {
                    List<ItemHistory> temp = lf.getValue();
                    for(ItemHistory h : temp) {
                        if(!historyItems.contains(h)) {
                            historyItems.add(h);
                        }
                        if(historyItems.size() == 50) {
                            break;
                        }
                    }
                });
            }
            sendItemHistoryData(historyItems);
        }));
    }
References acdat, itemHistories, player, recentlySoldItems, and sendItemHistoryData().
Referenced by handleButtonClick().
searchPlayerInput()
void com.runehive.content.tradingpost.TradingPost.searchPlayerInput () private
Definition at line 269 of file TradingPost.java.
{
        World.schedule(new Task(1) { // task added so input prompt shows after dialogue
            @Override
            protected void execute() {
                player.send(new SendInputMessage("Enter player name to search for:", 16, input -> {
                    searchExistingListing(new TradingPostActiveListingSearch(TradingPostActiveListingSearchType.PLAYER, String.valueOf(input)));
                    player.interfaceManager.open(BUYING_PAGE_INTERFACE_ID);
                }));
                this.cancel();
            }
        });
    }
References BUYING_PAGE_INTERFACE_ID, com.runehive.content.tradingpost.TradingPost.TradingPostActiveListingSearchType.PLAYER, player, com.runehive.game.world.World.schedule(), and searchExistingListing().
Referenced by handleButtonClick().
selectItemToList()
void com.runehive.content.tradingpost.TradingPost.selectItemToList (Item item)
Definition at line 531 of file TradingPost.java.
{
        if(!item.isTradeable() || item.getId() == 995) {
            player.send(new SendMessage("You cannot list this item."));
            return;
        }
        listingToAdd = new TradingPostListing(item.getId(), player.getName());
        player.send(new SendItemOnInterface(80153,item));
        player.send(new SendString(item.getDefinition().getName(),80160));
        updatePriceStrings();
        updateQuantityString();
    }
References com.runehive.game.world.items.Item.getDefinition(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.items.Item.isTradeable(), listingToAdd, player, updatePriceStrings(), and updateQuantityString().
sendItemHistoryData()
void com.runehive.content.tradingpost.TradingPost.sendItemHistoryData (List< ItemHistory > itemHistories)
Definition at line 236 of file TradingPost.java.
{
            for(int i = 0; i < MAX_LISTINGS_SHOWN; i++) {
                if(itemHistories.size() > i) {
                    ItemHistory ih = itemHistories.get(i);
                    player.send(new SendString(ItemDefinition.get(ih.getItemId()).getName(),80753+i));
                    player.send(new SendString(Utility.formatDigits(ih.getPrice()),80803+i));
                    player.send(new SendString(ih.getSeller(),80853+i));
                    player.send(new SendString(ih.getBuyer(),80903+i));
                } else {
                    player.send(new SendString("",80753+i));
                    player.send(new SendString("",80803+i));
                    player.send(new SendString("",80853+i));
                    player.send(new SendString("",80903+i));
                }
            }
        player.send(new SendItemOnInterface(80953, getItemArrayFromItemHistory(itemHistories)));
        player.interfaceManager.open(HISTORY_PAGE_INTERFACE_ID);
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.content.tradingpost.ItemHistory.getBuyer(), getItemArrayFromItemHistory(), com.runehive.content.tradingpost.ItemHistory.getItemId(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.content.tradingpost.ItemHistory.getPrice(), com.runehive.content.tradingpost.ItemHistory.getSeller(), HISTORY_PAGE_INTERFACE_ID, itemHistories, MAX_LISTINGS_SHOWN, and player.
Referenced by handleButtonClick(), and searchItemHistoryInput().
sendOverviewWidgetVisibility()
void com.runehive.content.tradingpost.TradingPost.sendOverviewWidgetVisibility (int i, boolean isHidden) private
Definition at line 639 of file TradingPost.java.
{
        player.send(new SendInterfaceVisibility(80032+i,isHidden));
        player.send(new SendInterfaceVisibility(80052+i,isHidden));
        player.send(new SendInterfaceVisibility(80072+i,isHidden));
        player.send(new SendInterfaceVisibility(80112+i,isHidden));
    }
References player.
Referenced by updateExistingListingsWidgets().
sort()
void com.runehive.content.tradingpost.TradingPost.sort () private
Definition at line 282 of file TradingPost.java.
{
        if(displayedPageListings == null) return;
        if(tradingPostSort == null) return;
        page = 0;
        searchedListings = searchedListings
                .stream()
                .sorted(Comparator.comparingInt(
                                (tradingPostSort.postSortType == TradingPostSortType.HIGHEST_PRICE ||  tradingPostSort.postSortType == TradingPostSortType.LOWEST_PRICE)
                                ? TradingPostListing::getPrice
                                : TradingPostListing::getAmountLeft))
                .collect(Collectors.toList());
        if(tradingPostSort.postSortType == TradingPostSortType.HIGHEST_QUANTITY || tradingPostSort.postSortType == TradingPostSortType.HIGHEST_PRICE) {
            Collections.reverse(searchedListings);
        }
        updateBuyingPageWidgets(getPageListings(searchedListings));
    }
References displayedPageListings, com.runehive.content.tradingpost.TradingPostListing.getAmountLeft(), getPageListings(), com.runehive.content.tradingpost.TradingPostListing.getPrice(), com.runehive.content.tradingpost.TradingPost.TradingPostSortType.HIGHEST_PRICE, com.runehive.content.tradingpost.TradingPost.TradingPostSortType.HIGHEST_QUANTITY, com.runehive.content.tradingpost.TradingPost.TradingPostSortType.LOWEST_PRICE, page, searchedListings, tradingPostSort, and updateBuyingPageWidgets().
Referenced by sortPrice(), and sortQuantity().
sortPrice()
void com.runehive.content.tradingpost.TradingPost.sortPrice () private
Definition at line 304 of file TradingPost.java.
{
        tradingPostSort = tradingPostSort != null ? tradingPostSort.setPostSortType(
                tradingPostSort.postSortType == TradingPostSortType.HIGHEST_PRICE
                        ? TradingPostSortType.LOWEST_PRICE
                        : TradingPostSortType.HIGHEST_PRICE
        ) : new TradingPostActiveListingSort(TradingPostSortType.LOWEST_PRICE);
        sort();
    }
References com.runehive.content.tradingpost.TradingPost.TradingPostSortType.HIGHEST_PRICE, com.runehive.content.tradingpost.TradingPost.TradingPostSortType.LOWEST_PRICE, sort(), and tradingPostSort.
Referenced by handleButtonClick().
sortQuantity()
void com.runehive.content.tradingpost.TradingPost.sortQuantity ()
Definition at line 314 of file TradingPost.java.
{
        tradingPostSort = tradingPostSort != null ? tradingPostSort.setPostSortType(
                tradingPostSort.postSortType == TradingPostSortType.HIGHEST_QUANTITY
                        ? TradingPostSortType.LOWEST_QUANTITY
                        : TradingPostSortType.HIGHEST_QUANTITY
        ) : new TradingPostActiveListingSort(TradingPostSortType.HIGHEST_QUANTITY);
        sort();
    }
References com.runehive.content.tradingpost.TradingPost.TradingPostSortType.HIGHEST_QUANTITY, com.runehive.content.tradingpost.TradingPost.TradingPostSortType.LOWEST_QUANTITY, sort(), and tradingPostSort.
Referenced by handleButtonClick().
testData()
void com.runehive.content.tradingpost.TradingPost.testData ()
Definition at line 857 of file TradingPost.java.
{
        int addCounter = 0;
        for(int i = 0; i < 1000; i++) {
            ItemDefinition def = ItemDefinition.DEFINITIONS[new Random().nextInt(ItemDefinition.DEFINITIONS.length)];
            if(def != null) {
                TradingPostListing listing = new TradingPostListing(def.getId(), "John"+i);
                listing.setInitialQuantity(i+1);
                listing.setPrice(i+1);
                allListings.add(listing);
                addCounter++;
                System.out.println("Adding listing: " + addCounter);
            }
        }
    }
References allListings, com.runehive.game.world.items.ItemDefinition.DEFINITIONS, com.runehive.content.tradingpost.TradingPostListing.setInitialQuantity(), and com.runehive.content.tradingpost.TradingPostListing.setPrice().
toggleBuyingPageWidgetVisibility()
void com.runehive.content.tradingpost.TradingPost.toggleBuyingPageWidgetVisibility (int i, boolean isHidden) private
Definition at line 481 of file TradingPost.java.
{
        player.send(new SendInterfaceVisibility(80214+i, isHidden));
        player.send(new SendInterfaceVisibility(80264+i, isHidden));
        player.send(new SendInterfaceVisibility(80314+i, isHidden));
        player.send(new SendInterfaceVisibility(80364+i, isHidden));
        player.send(new SendInterfaceVisibility(80414+i, isHidden));
        player.send(new SendInterfaceVisibility(80464+i, isHidden));
        player.send(new SendInterfaceVisibility(80564+i, isHidden));
    }
References player.
Referenced by updateBuyingPageWidgets().
toggleSellingOverlayVisibilityAndOpen()
void com.runehive.content.tradingpost.TradingPost.toggleSellingOverlayVisibilityAndOpen (boolean isHidden) private
Definition at line 491 of file TradingPost.java.
{
        if(isHidden) {
            player.interfaceManager.close();
        }
        player.interfaceManager.open(OVERVIEW_INTERFACE_ID);
        player.send(new SendInterfaceVisibility(80146, isHidden));
    }
References OVERVIEW_INTERFACE_ID, and player.
Referenced by handleButtonClick(), openOverviewInterface(), and openSellingOverlay().
updateBuyingPageWidgets()
void com.runehive.content.tradingpost.TradingPost.updateBuyingPageWidgets (List< TradingPostListing > listings) private
Definition at line 460 of file TradingPost.java.
{
         displayedPageListings = listings;
         for(int i = 0; i < MAX_LISTINGS_SHOWN; i++) {
             if(displayedPageListings.size() > i) {
                TradingPostListing listing = displayedPageListings.get(i);
                 player.send(new SendString(ItemDefinition.get(listing.getItemId()).getName(),80214+i));
                 player.send(new SendString(Utility.formatDigits(listing.getAmountLeft()*listing.getPrice()),80264+i));
                 player.send(new SendString("= " + Utility.formatDigits(listing.getPrice()) + " (ea)",80314+i));
                 player.send(new SendString(listing.getSeller(),80364+i));
                 toggleBuyingPageWidgetVisibility(i,false);
             } else {
                 toggleBuyingPageWidgetVisibility(i, true);
             }
         }
        player.send(new SendString("Page: " + (page+1),80615));
        player.send(new SendItemOnInterface(80614, getItemArrayFromActiveListings(displayedPageListings)));
        player.send(new SendScrollbar(80211, Math.max(238, displayedPageListings.size()*34)));
    }
References displayedPageListings, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.content.tradingpost.TradingPostListing.getAmountLeft(), getItemArrayFromActiveListings(), com.runehive.content.tradingpost.TradingPostListing.getItemId(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.content.tradingpost.TradingPostListing.getPrice(), com.runehive.content.tradingpost.TradingPostListing.getSeller(), MAX_LISTINGS_SHOWN, page, player, and toggleBuyingPageWidgetVisibility().
Referenced by addSearchResultsAndUpdateInterface(), nextPage(), previousPage(), and sort().
updateCofferAmountWidget()
void com.runehive.content.tradingpost.TradingPost.updateCofferAmountWidget ()
Definition at line 127 of file TradingPost.java.
{
        getOrMakeNewCofferIfNotExists(player.getName(), coffer -> {
            player.send(new SendString(Utility.formatDigits(coffer.getAmount()), 80005));
        });
    }
References getOrMakeNewCofferIfNotExists(), and player.
Referenced by openOverviewInterface(), and withdrawFromCoffer().
updateExistingListingsList()
void com.runehive.content.tradingpost.TradingPost.updateExistingListingsList () private
Definition at line 593 of file TradingPost.java.
{
        myListings = getListingsByName(player.getName());
    }
References getListingsByName(), myListings, and player.
Referenced by confirmToAddListing(), and openOverviewInterface().
updateExistingListingsWidgets()
void com.runehive.content.tradingpost.TradingPost.updateExistingListingsWidgets () private
Definition at line 622 of file TradingPost.java.
{
        player.send(new SendItemOnInterface(80132, getItemArrayFromActiveListings(myListings)));
        for(int i = 0; i < MAX_LISTING_SIZE; i++) {
            if(myListings.size() > i) {
                TradingPostListing tradingPostListing = myListings.get(i);
                sendOverviewWidgetVisibility(i,false);
                player.send(new SendString(tradingPostListing.getAmountSold() + "/" + tradingPostListing.getInitialQuantity(), 80112+i));
                player.send(new SendProgressBar(80032+i,  ((tradingPostListing.getAmountSold() * 100) / tradingPostListing.getInitialQuantity())));
            } else {
                sendOverviewWidgetVisibility(i,true);
            }
        }
        player.send(new SendScrollbar(80029, Math.max(38*myListings.size(), 157)));
    }
References com.runehive.content.tradingpost.TradingPostListing.getAmountSold(), com.runehive.content.tradingpost.TradingPostListing.getInitialQuantity(), getItemArrayFromActiveListings(), MAX_LISTING_SIZE, myListings, player, and sendOverviewWidgetVisibility().
Referenced by confirmToAddListing(), and openOverviewInterface().
updatePriceStrings()
void com.runehive.content.tradingpost.TradingPost.updatePriceStrings ()
Definition at line 543 of file TradingPost.java.
{
        if(listingToAdd == null) return;
        player.send(new SendString("Price: @gre@" + Utility.formatDigits(listingToAdd.getPrice()), 80161));
        player.send(new SendString("Total: @gre@" + Utility.formatDigits(listingToAdd.getPrice()*listingToAdd.getInitialQuantity()), 80163));
    }
References com.runehive.util.Utility.formatDigits(), listingToAdd, and player.
Referenced by com.runehive.content.tradingpost.TradingPostListing.checkAndUpdate(), com.runehive.content.tradingpost.TradingPostListing.removeQuantity(), selectItemToList(), and com.runehive.content.tradingpost.TradingPostListing.setPrice().
updateQuantityString()
void com.runehive.content.tradingpost.TradingPost.updateQuantityString ()
Definition at line 549 of file TradingPost.java.
{
        if(listingToAdd == null) return;
        player.send(new SendString("Quantity: @gre@" + listingToAdd.getInitialQuantity(), 80162));
        player.send(new SendString(listingToAdd.getInitialQuantity(), 80173));
    }
References listingToAdd, and player.
Referenced by com.runehive.content.tradingpost.TradingPostListing.checkAndUpdate(), com.runehive.content.tradingpost.TradingPostListing.removeQuantity(), and selectItemToList().
withdrawFromCoffer()
void com.runehive.content.tradingpost.TradingPost.withdrawFromCoffer () private
Definition at line 325 of file TradingPost.java.
{
        getOrMakeNewCofferIfNotExists(player.getName(), coffer -> {
            if (coffer.getAmount() == 0) {
                return;
            }
            player.send(new SendInputAmount("How much gold would you like to withdraw?", 10, input -> {
                int amount = Integer.parseInt(input);
                if (amount > coffer.getAmount()) {
                    amount = (int) coffer.getAmount();
                }
                if (amount > coffer.getAmount()) {
                    return;
                }
                if (player.inventory.add(CURRENCY_ID, amount)) {
                    coffer.subtractAmount(amount);
                    updateCofferAmountWidget();
                    saveCoffer(coffer);
                } else {
                    player.send(new SendMessage("You do not have enough inventory spaces to withdraw this gold"));
                }
            }));
        });
    }
References CURRENCY_ID, getOrMakeNewCofferIfNotExists(), player, saveCoffer(), and updateCofferAmountWidget().
Referenced by handleButtonClick().
Member Data Documentation
acdat
final AhoCorasickDoubleArrayTrie<String> com.runehive.content.tradingpost.TradingPost.acdat = new AhoCorasickDoubleArrayTrie<>() private
Definition at line 45 of file TradingPost.java.
Referenced by searchItemHistoryInput().
allCoffers
final Map<String, Coffer> com.runehive.content.tradingpost.TradingPost.allCoffers = Collections.synchronizedMap(new HashMap<>()) static private
Hashmap containing the coffers <PlayerName, Coffer>
Definition at line 55 of file TradingPost.java.
Referenced by getCoffer(), and getOrMakeNewCofferIfNotExists().
allListings
final List<TradingPostListing> com.runehive.content.tradingpost.TradingPost.allListings = new ArrayList<>() static private
A list containing all the trading post listings.
Definition at line 50 of file TradingPost.java.
Referenced by confirmToAddListing(), delist(), getListingsByName(), getSearchResults(), handleBuyingButton(), loadAllListings(), purchase(), and testData().
BUYING_PAGE_INTERFACE_ID
final int com.runehive.content.tradingpost.TradingPost.BUYING_PAGE_INTERFACE_ID = 80174 static
Definition at line 38 of file TradingPost.java.
Referenced by com.runehive.game.world.entity.mob.player.InterfaceManager.close(), displayMostRecentListings(), handleButtonClick(), searchExistingItemInput(), and searchPlayerInput().
CURRENCY_ID
final int com.runehive.content.tradingpost.TradingPost.CURRENCY_ID = 995 static private
Definition at line 42 of file TradingPost.java.
Referenced by buyingDialogueOptions(), purchase(), and withdrawFromCoffer().
displayedPageListings
List<TradingPostListing> com.runehive.content.tradingpost.TradingPost.displayedPageListings = new ArrayList<>() private
The displayed listings on the buying page.
Definition at line 90 of file TradingPost.java.
Referenced by cleanUp(), handleBuyingButton(), purchase(), sort(), and updateBuyingPageWidgets().
HISTORY_PAGE_INTERFACE_ID
final int com.runehive.content.tradingpost.TradingPost.HISTORY_PAGE_INTERFACE_ID = 80616 static private
Definition at line 39 of file TradingPost.java.
Referenced by handleButtonClick(), and sendItemHistoryData().
itemHistories
final Map<String, List<ItemHistory> > com.runehive.content.tradingpost.TradingPost.itemHistories = new HashMap<>() static private
Contains a list of the last 50 sold of each item.
Definition at line 95 of file TradingPost.java.
Referenced by addToItemHistory(), loadItemHistory(), saveAllItemHistory(), searchItemHistoryInput(), and sendItemHistoryData().
listingToAdd
TradingPostListing com.runehive.content.tradingpost.TradingPost.listingToAdd private
The listing that the player will add to their existing listings.
Definition at line 65 of file TradingPost.java.
Referenced by cleanUp(), confirmToAddListing(), editPriceInputPrompt(), editQuantityInputPrompt(), handleSellingOverlayButtons(), openSellingOverlay(), selectItemToList(), updatePriceStrings(), and updateQuantityString().
listingToBuy
TradingPostListing com.runehive.content.tradingpost.TradingPost.listingToBuy private
The listing that the player selects in the buying page.
Definition at line 70 of file TradingPost.java.
Referenced by buyingDialogueOptions(), cleanUp(), handleBuyingButton(), and purchase().
logger
final Logger com.runehive.content.tradingpost.TradingPost.logger = LoggerFactory.getLogger(TradingPost.class) static private
Definition at line 35 of file TradingPost.java.
Referenced by getCoffer(), loadAllListings(), saveCoffer(), and saveListings().
MAX_LISTING_SIZE
final int com.runehive.content.tradingpost.TradingPost.MAX_LISTING_SIZE = 20 static private
Definition at line 41 of file TradingPost.java.
Referenced by getSlotSizeByDonatorRank(), and updateExistingListingsWidgets().
MAX_LISTINGS_SHOWN
final int com.runehive.content.tradingpost.TradingPost.MAX_LISTINGS_SHOWN = 50 static private
Definition at line 40 of file TradingPost.java.
Referenced by getPageListings(), sendItemHistoryData(), and updateBuyingPageWidgets().
myListings
List<TradingPostListing> com.runehive.content.tradingpost.TradingPost.myListings = new ArrayList<>() private
List containing the players existing listings/offers.
Definition at line 60 of file TradingPost.java.
Referenced by confirmToAddListing(), delist(), handleDismissListingButton(), updateExistingListingsList(), and updateExistingListingsWidgets().
OVERVIEW_INTERFACE_ID
final int com.runehive.content.tradingpost.TradingPost.OVERVIEW_INTERFACE_ID = 80000 static private
Definition at line 37 of file TradingPost.java.
Referenced by alertSeller(), handleButtonClick(), openOverviewInterface(), openSellingOverlay(), and toggleSellingOverlayVisibilityAndOpen().
page
int com.runehive.content.tradingpost.TradingPost.page private
The page # of the buying interface.
Definition at line 110 of file TradingPost.java.
Referenced by cleanUp(), getPageListings(), nextPage(), previousPage(), sort(), and updateBuyingPageWidgets().
player
final Player com.runehive.content.tradingpost.TradingPost.player private
Definition at line 112 of file TradingPost.java.
Referenced by alertSeller(), buyingDialogueOptions(), clearSellingOverlay(), confirmToAddListing(), displayMostRecentListings(), editPriceInputPrompt(), editQuantityInputPrompt(), getPageListings(), getSlotSizeByDonatorRank(), handleButtonClick(), handleBuyingButton(), handleDismissListingButton(), handleSellingOverlayButtons(), nextPage(), openOverviewInterface(), openSellingOverlay(), purchase(), saveCoffer(), saveListings(), searchExistingItemInput(), searchExistingListing(), searchItemHistoryInput(), searchPlayerInput(), selectItemToList(), sendItemHistoryData(), sendOverviewWidgetVisibility(), toggleBuyingPageWidgetVisibility(), toggleSellingOverlayVisibilityAndOpen(), TradingPost(), updateBuyingPageWidgets(), updateCofferAmountWidget(), updateExistingListingsList(), updateExistingListingsWidgets(), updatePriceStrings(), updateQuantityString(), and withdrawFromCoffer().
playersItemHistory
final List<ItemHistory> com.runehive.content.tradingpost.TradingPost.playersItemHistory = new ArrayList<>() private
contains last 50 players buying history
Definition at line 105 of file TradingPost.java.
Referenced by addToItemHistory(), getPlayersItemHistory(), and handleButtonClick().
recentlySoldItems
final List<ItemHistory> com.runehive.content.tradingpost.TradingPost.recentlySoldItems = new ArrayList<>() static private
contains the last 50 sold items on the trading post
Definition at line 100 of file TradingPost.java.
Referenced by addToItemHistory(), handleButtonClick(), loadRecentItemHistory(), saveRecentHistory(), and searchItemHistoryInput().
searchedListings
List<TradingPostListing> com.runehive.content.tradingpost.TradingPost.searchedListings = new ArrayList<>() private
The current searched listings.
Definition at line 85 of file TradingPost.java.
Referenced by addSearchResultsAndUpdateInterface(), cleanUp(), nextPage(), previousPage(), purchase(), and sort().
TAX_RATE
final int com.runehive.content.tradingpost.TradingPost.TAX_RATE = 10 static private
Definition at line 43 of file TradingPost.java.
Referenced by addToCoffer().
tradingPostSearch
TradingPostActiveListingSearch com.runehive.content.tradingpost.TradingPost.tradingPostSearch private
The current item or player search.
Definition at line 75 of file TradingPost.java.
Referenced by cleanUp(), displayMostRecentListings(), getSearchResults(), purchase(), refresh(), and searchExistingListing().
tradingPostSort
TradingPostActiveListingSort com.runehive.content.tradingpost.TradingPost.tradingPostSort private
The current sort of the buyable listings.
Definition at line 80 of file TradingPost.java.
Referenced by cleanUp(), sort(), sortPrice(), and sortQuantity().
The documentation for this class was generated from the following file:
java/com/runehive/content/tradingpost/TradingPost.java