RuneHive-Game: com.runehive.content.bot.botclass.impl.PureRangeMelee Class Reference
com.runehive.content.bot.botclass.impl.PureRangeMelee Class Reference
Public Member Functions
void block (Mob attacker, Player defender, Hit hit, CombatType combatType)
boolean canOtherAttack (Mob attacker, Player defender)
void eat (Player target, PlayerBot bot)
void endFight (PlayerBot bot)
Item[] equipment ()
void handleCombat (Player target, PlayerBot bot)
void hit (Player attacker, Mob defender, Hit hit)
void initCombat (Player target, PlayerBot bot)
Item[] inventory ()
void pot (Player target, PlayerBot bot)
int[] skills ()
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
boolean canAttack (T attacker, Mob defender)
boolean canOtherAttack (Mob attacker, T defender)
void finishIncoming (Mob attacker, T defender)
void finishOutgoing (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
void hitsplat (T attacker, Mob defender, Hit hit)
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
void onKill (T attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, T defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
void start (T attacker, Mob defender, Hit[] hits)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Private Member Functions
boolean checkSkill (PlayerBot bot, int id, int minimum)
void meleePrayers (PlayerBot bot)
void rangedPrayers (PlayerBot bot)
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
static final CombatListener< Mob > CANT_ATTACK
Detailed Description
Definition at line 23 of file PureRangeMelee.java.
Member Function Documentation
block()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.block (Mob attacker, Player defender, Hit hit, CombatType combatType)
Definition at line 196 of file PureRangeMelee.java.
{
        ((PlayerBot) defender).consumableDelay = RandomUtils.inclusive(1, 3);
    }
References hit(), and com.runehive.util.RandomUtils.inclusive().
canOtherAttack()
boolean com.runehive.content.bot.botclass.impl.PureRangeMelee.canOtherAttack (Mob attacker, Player defender)
Definition at line 187 of file PureRangeMelee.java.
{
        if (defender.getCombat().isAttacking() && !defender.getCombat().isAttacking(attacker)) {
            attacker.getPlayer().message("You cannot attack a bot while they are attacking another player.");
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.mob.Mob.getPlayer(), and com.runehive.game.world.entity.mob.player.Player.message().
checkSkill()
boolean com.runehive.content.bot.botclass.impl.PureRangeMelee.checkSkill (PlayerBot bot, int id, int minimum) private
Definition at line 220 of file PureRangeMelee.java.
{
        return bot.skills.getLevel(id) <= minimum;
    }
Referenced by pot().
eat()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.eat (Player target, PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 162 of file PureRangeMelee.java.
{
        int max = target.playerAssistant.getMaxHit(bot, target.getStrategy().getCombatType());
        if (bot.getCurrentHealth() > bot.getMaximumHealth() * 0.45 && max < bot.getCurrentHealth())
            return;
        if (target.getCurrentHealth() <= Math.floor(target.getMaximumHealth() * 0.35) && max < bot.getCurrentHealth())
            return;
        int index = bot.inventory.computeIndexForId(391);
        if (index >= 0) {
            EatFoodPlugin.eat(bot, bot.inventory.get(index), index, FoodData.MANTA);
            bot.foodRemaining--;
        }
        if (bot.getCurrentHealth() >= bot.getMaximumHealth() * 0.35)
            return;
        index = bot.inventory.computeIndexForId(3144);
        if (index >= 0) {
            EatFoodPlugin.eat(bot, bot.inventory.get(index), index, FoodData.COOKED_KARAMBWAN);
            bot.foodRemaining--;
        }
    }
References com.runehive.content.consume.FoodData.COOKED_KARAMBWAN, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.player.PlayerAssistant.getMaxHit(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.mob.player.Player.getStrategy(), com.runehive.content.consume.FoodData.MANTA, and com.runehive.game.world.entity.mob.player.Player.playerAssistant.
endFight()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.endFight (PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 80 of file PureRangeMelee.java.
{
        bot.prayer.deactivate(Prayer.PROTECT_ITEM, Prayer.SMITE, Prayer.EAGLE_EYE, Prayer.ULTIMATE_STRENGTH, Prayer.STEEL_SKIN, Prayer.INCREDIBLE_REFLEXES);
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.EAGLE_EYE, com.runehive.game.world.entity.mob.prayer.Prayer.INCREDIBLE_REFLEXES, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_ITEM, com.runehive.game.world.entity.mob.prayer.Prayer.SMITE, com.runehive.game.world.entity.mob.prayer.Prayer.STEEL_SKIN, and com.runehive.game.world.entity.mob.prayer.Prayer.ULTIMATE_STRENGTH.
equipment()
Item[] com.runehive.content.bot.botclass.impl.PureRangeMelee.equipment ()
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 39 of file PureRangeMelee.java.
{
        return new Item[] { new Item(2900), new Item(10498), new Item(1129), new Item(11978), new Item(892, 125), new Item(3105), new Item(2497), new Item(861), new Item(2491) };
    }
handleCombat()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.handleCombat (Player target, PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 58 of file PureRangeMelee.java.
{
        if (!bot.prayer.isActive(Prayer.SMITE) && target.prayer.isActive(Prayer.SMITE)) {
            bot.prayer.toggle(Prayer.SMITE);
            bot.speak("Let's smite then...");
        } else if (bot.prayer.isActive(Prayer.SMITE) && !target.prayer.isActive(Prayer.SMITE)) {
            bot.prayer.toggle(Prayer.SMITE);
        }
        if (bot.isSpecialActivated() && target.prayer.isActive(Prayer.PROTECT_FROM_MELEE)) {
            bot.speak("That's not fair...");
            bot.getCombatSpecial().disable(bot, false);
            bot.endFight();
        }
        if (!bot.prayer.isActive(Prayer.PROTECT_FROM_MELEE) && target.prayer.isActive(Prayer.PROTECT_FROM_MELEE)) {
            bot.prayer.toggle(Prayer.PROTECT_FROM_MELEE);
        } else if (bot.prayer.isActive(Prayer.PROTECT_FROM_MELEE) && !target.prayer.isActive(Prayer.PROTECT_FROM_MELEE)) {
            bot.prayer.toggle(Prayer.PROTECT_FROM_MELEE);
        }
    }
References com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MELEE, and com.runehive.game.world.entity.mob.prayer.Prayer.SMITE.
hit()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.hit (Player attacker, Mob defender, Hit hit)
Definition at line 85 of file PureRangeMelee.java.
{
        int max = getModifiedMaxHit(attacker, defender, CombatType.MELEE);
        boolean hasSpec = attacker.getSpecialPercentage().intValue() >= 50;
        boolean lowHp = defender.getCurrentHealth() <= defender.getMaximumHealth() * RandomUtils.inclusive(0.50, 0.65);
        boolean combo = defender.getCurrentHealth() <= defender.getMaximumHealth() * RandomUtils.inclusive(0.50, 0.70)
                && hit.getDamage() >= max * RandomUtils.inclusive(0.65, 0.75);
        if (!combo && !lowHp)
            return;
        PlayerBot bot = ((PlayerBot) attacker);
        bot.schedule(4, () -> {
            if (bot.equipment.getWeapon().matchesId(861)) {
                int index = bot.inventory.computeIndexForId(11802);
                bot.equipment.equip(index);
                bot.getCombat().setFightType(FightType.GODSWORD_SLASH);
                meleePrayers(bot);
            }
            if (hasSpec && (lowHp || RandomUtils.success(0.75)))
                bot.getCombatSpecial().enable(bot);
            bot.schedule(4, () -> {
                if (!bot.isSpecialActivated() && bot.equipment.getWeapon().matchesId(11802)) {
                    int idx = bot.inventory.computeIndexForId(861);
                    bot.equipment.equip(idx);
                    bot.getCombat().setFightType(FightType.SHORTBOW_RAPID);
                    rangedPrayers(bot);
                }
            });
        });
    }
References com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.mob.player.Player.getSpecialPercentage(), com.runehive.game.world.entity.combat.attack.FightType.GODSWORD_SLASH, hit(), com.runehive.util.RandomUtils.inclusive(), com.runehive.util.MutableNumber.intValue(), com.runehive.game.world.entity.combat.CombatType.MELEE, meleePrayers(), rangedPrayers(), com.runehive.game.world.entity.combat.attack.FightType.SHORTBOW_RAPID, and com.runehive.util.RandomUtils.success().
Referenced by block(), and hit().
initCombat()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.initCombat (Player target, PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 49 of file PureRangeMelee.java.
{
        pot(target, bot);
        bot.prayer.toggle(Prayer.PROTECT_ITEM, Prayer.EAGLE_EYE);
        bot.getCombat().addListener(this);
        bot.spellCasting.cast(new Vengeance(), null);
        bot.getCombat().setFightType(FightType.SHORTBOW_RAPID);
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.EAGLE_EYE, pot(), com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_ITEM, and com.runehive.game.world.entity.combat.attack.FightType.SHORTBOW_RAPID.
inventory()
Item[] com.runehive.content.bot.botclass.impl.PureRangeMelee.inventory ()
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 26 of file PureRangeMelee.java.
{
        return new Item[] {
            new Item(2444), new Item(12695), new Item(3144), new Item(3144),
            new Item(3024), new Item(3024), new Item(3144), new Item(3144),
            new Item(3024), new Item(3024), new Item(391), new Item(391),
            new Item(391), new Item(391), new Item(391), new Item(391),
            new Item(391), new Item(391), new Item(391), new Item(391),
            new Item(391), new Item(11802), new Item(391), new Item(391),
            new Item(391), new Item(391), new Item(391), new Item(391)
        };
    }
meleePrayers()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.meleePrayers (PlayerBot bot) private
Definition at line 207 of file PureRangeMelee.java.
{
        bot.prayer.deactivate(Prayer.EAGLE_EYE);
        if (bot.prayer.isActive(Prayer.ULTIMATE_STRENGTH))
            bot.prayer.toggle(Prayer.ULTIMATE_STRENGTH);
        if (bot.prayer.isActive(Prayer.STEEL_SKIN))
            bot.prayer.toggle(Prayer.STEEL_SKIN);
        if (bot.prayer.isActive(Prayer.INCREDIBLE_REFLEXES))
            bot.prayer.toggle(Prayer.INCREDIBLE_REFLEXES);
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.EAGLE_EYE, com.runehive.game.world.entity.mob.prayer.Prayer.INCREDIBLE_REFLEXES, com.runehive.game.world.entity.mob.prayer.Prayer.STEEL_SKIN, and com.runehive.game.world.entity.mob.prayer.Prayer.ULTIMATE_STRENGTH.
Referenced by hit().
pot()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.pot (Player target, PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 120 of file PureRangeMelee.java.
{
        int max = target.playerAssistant.getMaxHit(bot, target.getStrategy().getCombatType());
        if (target.getCurrentHealth() <= Math.floor(target.getMaximumHealth() * 0.35) && max < bot.getCurrentHealth())
            return;
        if (!bot.potionDelay.elapsed(1250)) {
            return;
        }
        PotionData potion;
        ItemClickEvent event;
        if (checkSkill(bot, Skill.PRAYER, 25)) {
            int index = bot.inventory.computeIndexForId(3024);
            if (index >= 0) {
                event = new ItemClickEvent(0, bot.inventory.get(index), index);
                potion = PotionData.SUPER_RESTORE_POTIONS;
                bot.pot(target, event, potion);
            }
        } else {
            if (checkSkill(bot, Skill.ATTACK, 71)
                    || checkSkill(bot, Skill.STRENGTH, 115)
                    || checkSkill(bot, Skill.DEFENCE, 3)) {
                int index = bot.inventory.computeIndexForId(12695);
                if (index >= 0) {
                    event = new ItemClickEvent(0, bot.inventory.get(index), index);
                    potion = PotionData.SUPER_COMBAT_POTION;
                    bot.pot(target, event, potion);
                }
            }
            if (checkSkill(bot, Skill.RANGED, 108)) {
                int index = bot.inventory.computeIndexForId(2444);
                if (index >= 0) {
                    event = new ItemClickEvent(0, bot.inventory.get(index), index);
                    potion = PotionData.RANGE_POTIONS;
                    bot.pot(target, event, potion);
                }
            }
        }
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, checkSkill(), com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.player.PlayerAssistant.getMaxHit(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.mob.player.Player.getStrategy(), com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.content.consume.PotionData.RANGE_POTIONS, com.runehive.game.world.entity.skill.Skill.RANGED, com.runehive.game.world.entity.skill.Skill.STRENGTH, com.runehive.content.consume.PotionData.SUPER_COMBAT_POTION, and com.runehive.content.consume.PotionData.SUPER_RESTORE_POTIONS.
Referenced by initCombat().
rangedPrayers()
void com.runehive.content.bot.botclass.impl.PureRangeMelee.rangedPrayers (PlayerBot bot) private
Definition at line 200 of file PureRangeMelee.java.
{
        bot.prayer.deactivate(Prayer.ULTIMATE_STRENGTH, Prayer.STEEL_SKIN, Prayer.INCREDIBLE_REFLEXES);
        if (bot.prayer.isActive(Prayer.EAGLE_EYE))
            bot.prayer.toggle(Prayer.EAGLE_EYE);
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.EAGLE_EYE, com.runehive.game.world.entity.mob.prayer.Prayer.INCREDIBLE_REFLEXES, com.runehive.game.world.entity.mob.prayer.Prayer.STEEL_SKIN, and com.runehive.game.world.entity.mob.prayer.Prayer.ULTIMATE_STRENGTH.
Referenced by hit().
skills()
int[] com.runehive.content.bot.botclass.impl.PureRangeMelee.skills ()
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 44 of file PureRangeMelee.java.
{
        return new int[] { 75, 1, 99, 80, 99, 52, 1 };
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/bot/botclass/impl/PureRangeMelee.java