RuneHive-Game: com.runehive.game.service.ForumService Class Reference
com.runehive.game.service.ForumService Class Reference
Static Public Member Functions
static Connection getConnection () throws SQLException
static HikariDataSource getConnectionPool ()
static void start () throws Exception
Static Private Attributes
static HikariDataSource connectionPool
static final Logger logger = LogManager.getLogger(ForumService.class)
Detailed Description
Definition at line 12 of file ForumService.java.
Member Function Documentation
getConnection()
Connection com.runehive.game.service.ForumService.getConnection () throws SQLException static
Definition at line 37 of file ForumService.java.
{
        return connectionPool.getConnection();
    }
References connectionPool.
getConnectionPool()
HikariDataSource com.runehive.game.service.ForumService.getConnectionPool () static
Definition at line 33 of file ForumService.java.
{
        return connectionPool;
    }
References connectionPool.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser().
start()
void com.runehive.game.service.ForumService.start () throws Exception static
Definition at line 18 of file ForumService.java.
{
        HikariConfig config = new HikariConfig();
        config.setDriverClassName("com.mysql.jdbc.Driver");
        config.setJdbcUrl(Config.FORUM_DB_URL);
        config.setUsername(Config.FORUM_DB_USER);
        config.setPassword(Config.FORUM_DB_PASS);
        config.setMaximumPoolSize(10);
        config.setConnectionTimeout(5_000);
        config.setIdleTimeout(0);
        config.setMaxLifetime(0);
        config.addDataSourceProperty("cachePrepStmts", "true");
        connectionPool = new HikariDataSource(config);
        logger.info("Successfully connected to forum database.");
    }
References connectionPool, com.runehive.Config.FORUM_DB_PASS, com.runehive.Config.FORUM_DB_URL, com.runehive.Config.FORUM_DB_USER, and logger.
Referenced by com.runehive.RuneHive.start().
Member Data Documentation
connectionPool
HikariDataSource com.runehive.game.service.ForumService.connectionPool static private
Definition at line 16 of file ForumService.java.
Referenced by getConnection(), getConnectionPool(), and start().
logger
final Logger com.runehive.game.service.ForumService.logger = LogManager.getLogger(ForumService.class) static private
Definition at line 14 of file ForumService.java.
Referenced by start().
The documentation for this class was generated from the following file:
java/com/runehive/game/service/ForumService.java