RuneHive-Game: com.runehive.content.bot.botclass.impl.ZerkerMelee Class Reference
com.runehive.content.bot.botclass.impl.ZerkerMelee Class Reference
Public Member Functions
void block (Mob attacker, Player defender, Hit hit, CombatType combatType)
boolean canOtherAttack (Mob attacker, Player defender)
void eat (Player target, PlayerBot bot)
void endFight (PlayerBot bot)
Item[] equipment ()
void handleCombat (Player target, PlayerBot bot)
void hit (Player attacker, Mob defender, Hit hit)
void initCombat (Player target, PlayerBot bot)
Item[] inventory ()
void pot (Player target, PlayerBot bot)
int[] skills ()
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
boolean canAttack (T attacker, Mob defender)
boolean canOtherAttack (Mob attacker, T defender)
void finishIncoming (Mob attacker, T defender)
void finishOutgoing (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
void hitsplat (T attacker, Mob defender, Hit hit)
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
void onKill (T attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, T defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
void start (T attacker, Mob defender, Hit[] hits)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Private Member Functions
boolean checkSkill (PlayerBot bot, int id, int minimum)
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
static final CombatListener< Mob > CANT_ATTACK
Detailed Description
Definition at line 25 of file ZerkerMelee.java.
Member Function Documentation
block()
void com.runehive.content.bot.botclass.impl.ZerkerMelee.block (Mob attacker, Player defender, Hit hit, CombatType combatType)
Definition at line 211 of file ZerkerMelee.java.
{
        ((PlayerBot) defender).consumableDelay = RandomUtils.inclusive(1, 3);
    }
References hit(), and com.runehive.util.RandomUtils.inclusive().
canOtherAttack()
boolean com.runehive.content.bot.botclass.impl.ZerkerMelee.canOtherAttack (Mob attacker, Player defender)
Definition at line 202 of file ZerkerMelee.java.
{
        if (defender.getCombat().isAttacking() && !defender.getCombat().isAttacking(attacker)) {
            attacker.getPlayer().message("You cannot attack a bot while they are attacking another player.");
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.mob.Mob.getPlayer(), and com.runehive.game.world.entity.mob.player.Player.message().
checkSkill()
boolean com.runehive.content.bot.botclass.impl.ZerkerMelee.checkSkill (PlayerBot bot, int id, int minimum) private
Definition at line 215 of file ZerkerMelee.java.
{
        return bot.skills.getLevel(id) < minimum;
    }
Referenced by pot().
eat()
void com.runehive.content.bot.botclass.impl.ZerkerMelee.eat (Player target, PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 177 of file ZerkerMelee.java.
{
        int max = target.playerAssistant.getMaxHit(bot, target.getStrategy().getCombatType());
        if (bot.getCurrentHealth() > bot.getMaximumHealth() * 0.45 && max < bot.getCurrentHealth())
            return;
        if (target.getCurrentHealth() <= Math.floor(target.getMaximumHealth() * 0.35) && max < bot.getCurrentHealth())
            return;
        int index = bot.inventory.computeIndexForId(391);
        if (index >= 0) {
            EatFoodPlugin.eat(bot, bot.inventory.get(index), index, FoodData.MANTA);
            bot.foodRemaining--;
        }
        if (bot.getCurrentHealth() >= bot.getMaximumHealth() * 0.35)
            return;
        index = bot.inventory.computeIndexForId(3144);
        if (index >= 0) {
            EatFoodPlugin.eat(bot, bot.inventory.get(index), index, FoodData.COOKED_KARAMBWAN);
            bot.foodRemaining--;
        }
    }
References com.runehive.content.consume.FoodData.COOKED_KARAMBWAN, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.player.PlayerAssistant.getMaxHit(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.mob.player.Player.getStrategy(), com.runehive.content.consume.FoodData.MANTA, and com.runehive.game.world.entity.mob.player.Player.playerAssistant.
endFight()
void com.runehive.content.bot.botclass.impl.ZerkerMelee.endFight (PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 97 of file ZerkerMelee.java.
{
        bot.prayer.deactivate(Prayer.PROTECT_ITEM, Prayer.SMITE, Prayer.PIETY);
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.PIETY, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_ITEM, and com.runehive.game.world.entity.mob.prayer.Prayer.SMITE.
equipment()
Item[] com.runehive.content.bot.botclass.impl.ZerkerMelee.equipment ()
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 41 of file ZerkerMelee.java.
{
        return new Item[] {
                new Item(6570),
                new Item(11128),
                new Item(10551),
                new Item(3751),
                new Item(1079),
                new Item(8850),
                new Item(4131),
                new Item(2550),
                new Item(7462),
                new Item(4587)
        };
    }
handleCombat()
void com.runehive.content.bot.botclass.impl.ZerkerMelee.handleCombat (Player target, PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 71 of file ZerkerMelee.java.
{
        if (!bot.prayer.isActive(Prayer.SMITE) && target.prayer.isActive(Prayer.SMITE)) {
            bot.prayer.toggle(Prayer.SMITE);
            bot.speak("Let's smite then...");
        } else if (bot.prayer.isActive(Prayer.SMITE) && !target.prayer.isActive(Prayer.SMITE)) {
            bot.prayer.toggle(Prayer.SMITE);
        }
        if (bot.isSpecialActivated() && target.prayer.isActive(Prayer.PROTECT_FROM_MELEE)) {
            bot.speak("That's not fair...");
            bot.getCombatSpecial().disable(bot, false);
            bot.endFight();
        }
        if (!bot.prayer.isActive(Prayer.PROTECT_FROM_MELEE) && target.prayer.isActive(Prayer.PROTECT_FROM_MELEE)) {
            bot.prayer.toggle(Prayer.PROTECT_FROM_MELEE);
        } else if (bot.prayer.isActive(Prayer.PROTECT_FROM_MELEE) && !target.prayer.isActive(Prayer.PROTECT_FROM_MELEE)) {
            bot.prayer.toggle(Prayer.PROTECT_FROM_MELEE);
        }
        if (bot.spellCasting.vengeanceDelay.elapsedTime(TimeUnit.SECONDS) >= 30) {
            bot.spellCasting.cast(new Vengeance(), null);
        }
    }
References com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MELEE, and com.runehive.game.world.entity.mob.prayer.Prayer.SMITE.
hit()
void com.runehive.content.bot.botclass.impl.ZerkerMelee.hit (Player attacker, Mob defender, Hit hit)
Definition at line 102 of file ZerkerMelee.java.
{
        int max = getModifiedMaxHit(attacker, defender, CombatType.MELEE);
        max = attacker.getCombat().modifyDamage(defender, max);
        boolean hasRoom = attacker.inventory.getFreeSlots() > 0;
        boolean hasSpec = attacker.getSpecialPercentage().intValue() >= 25;
        boolean lowHp = defender.getCurrentHealth() <= defender.getMaximumHealth() * RandomUtils.inclusive(0.50, 0.65);
        boolean combo = defender.getCurrentHealth() <= defender.getMaximumHealth() * RandomUtils.inclusive(0.50, 0.70)
                && hit.getDamage() >= max * RandomUtils.inclusive(0.65, 0.75);
        if (!combo && !lowHp)
            return;
        PlayerBot bot = ((PlayerBot) attacker);
        bot.schedule(4, () -> {
            if (bot.equipment.getWeapon().matchesId(4587)) {
                boolean useMaul = hasRoom && (!hasSpec || RandomUtils.success(0.50));
                if (useMaul) {
                    int index = bot.inventory.computeIndexForId(21103);
                    bot.equipment.equip(index);
                    bot.getCombat().setFightType(FightType.ELDER_MAUL_PUMMEL);
                } else {
                    int index = bot.inventory.computeIndexForId(5698);
                    bot.equipment.equip(index);
                    bot.getCombat().setFightType(FightType.DRAGON_DAGGER_LUNGE);
                }
            }
            if (bot.equipment.getWeapon().matchesId(5698) && hasSpec && (lowHp || RandomUtils.success(0.75)))
                bot.getCombatSpecial().enable(bot);
            bot.schedule(4, () -> {
                if (!bot.isSpecialActivated() && bot.equipment.getWeapon().matchesId(5698)) {
                    int idx = bot.inventory.computeIndexForId(4587);
                    bot.equipment.equip(idx);
                    idx = bot.inventory.computeIndexForId(8850);
                    bot.equipment.equip(idx);
                    bot.getCombat().setFightType(FightType.SCIMITAR_SLASH);
                }
            });
        });
    }
References com.runehive.game.world.entity.combat.attack.FightType.DRAGON_DAGGER_LUNGE, com.runehive.game.world.entity.combat.attack.FightType.ELDER_MAUL_PUMMEL, com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.mob.player.Player.getSpecialPercentage(), hit(), com.runehive.util.RandomUtils.inclusive(), com.runehive.util.MutableNumber.intValue(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.combat.CombatType.MELEE, com.runehive.game.world.entity.combat.attack.FightType.SCIMITAR_SLASH, and com.runehive.util.RandomUtils.success().
Referenced by block(), and hit().
initCombat()
void com.runehive.content.bot.botclass.impl.ZerkerMelee.initCombat (Player target, PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 62 of file ZerkerMelee.java.
{
        pot(target, bot);
        bot.prayer.toggle(Prayer.PROTECT_ITEM, Prayer.PIETY);
        bot.getCombat().addListener(this);
        bot.spellCasting.cast(new Vengeance(), null);
        bot.getCombat().setFightType(FightType.SCIMITAR_SLASH);
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.PIETY, pot(), com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_ITEM, and com.runehive.game.world.entity.combat.attack.FightType.SCIMITAR_SLASH.
inventory()
Item[] com.runehive.content.bot.botclass.impl.ZerkerMelee.inventory ()
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 28 of file ZerkerMelee.java.
{
        return new Item[] {
            new Item(5698), new Item(21003), new Item(12695), new Item(3024),
            new Item(3024), new Item(3024), new Item(3024), new Item(3144),
            new Item(3144), new Item(3144), new Item(3144), new Item(3144),
            new Item(3144), new Item(560, 150), new Item(9075, 150), new Item(557, 300),
            new Item(391), new Item(391), new Item(391), new Item(391),
            new Item(391), new Item(391), new Item(391), new Item(391),
            new Item(391), new Item(391), new Item(391), new Item(391)
        };
    }
pot()
void com.runehive.content.bot.botclass.impl.ZerkerMelee.pot (Player target, PlayerBot bot)
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 146 of file ZerkerMelee.java.
{
        if (target.getCurrentHealth() <= Math.floor(target.getMaximumHealth() * 0.35))
            return;
        if (!bot.potionDelay.elapsed(1250)) {
            return;
        }
        PotionData potion;
        ItemClickEvent event;
        if (checkSkill(bot, Skill.PRAYER, 40)) {
            int index = bot.inventory.computeIndexForId(3024);
            if (index >= 0) {
                event = new ItemClickEvent(0, bot.inventory.get(index), index);
                potion = PotionData.SUPER_RESTORE_POTIONS;
                bot.pot(target, event, potion);
            }
        } else if (checkSkill(bot, Skill.ATTACK, 115)
                || checkSkill(bot, Skill.STRENGTH, 115)
                || checkSkill(bot, Skill.DEFENCE, 115)) {
            int index = bot.inventory.computeIndexForId(12695);
            if (index >= 0) {
                event = new ItemClickEvent(0, bot.inventory.get(index), index);
                potion = PotionData.SUPER_COMBAT_POTION;
                bot.pot(target, event, potion);
            }
        }
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, checkSkill(), com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.skill.Skill.STRENGTH, com.runehive.content.consume.PotionData.SUPER_COMBAT_POTION, and com.runehive.content.consume.PotionData.SUPER_RESTORE_POTIONS.
Referenced by initCombat().
skills()
int[] com.runehive.content.bot.botclass.impl.ZerkerMelee.skills ()
Implements com.runehive.content.bot.botclass.BotClass.
Definition at line 57 of file ZerkerMelee.java.
{
        return new int[] { 75, 45, 99, 99, 1, 52, 1 };
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/bot/botclass/impl/ZerkerMelee.java