RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility Class Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility Class Reference
Created by TJ#5762 Jusiticar Utility Class, handles the spawning & generate.
Classes
enum SpawnData2
Static Public Member Functions
static void defeated (Npc justicar, Player player)
static Npc generateSpawn ()
Static Public Attributes
static boolean activated = false
static int[] ALWAYSLOOT = { 1, 1, 1, 1, 1, 2, 3, 4, 5 }
Identification of all loot, it selects the loot.
static int[] COMMONLOOT = { 6199, 989, 3140, 4087, 11732, 989, 12878, 6585, 4675 }
static boolean justicarbutton
static int[] RARELOOT
static SpawnData2 spawn
static int[] SUPERRARELOOT
Detailed Description
Created by TJ#5762 Jusiticar Utility Class, handles the spawning & generate.
Definition at line 14 of file JusticarUtility.java.
Member Function Documentation
defeated()
void com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.defeated (Npc justicar, Player player) static
Definition at line 44 of file JusticarUtility.java.
{
        boolean hasClan = player.clanChannel != null;
        if (hasClan) {
            World.sendMessage("<col=8714E6> Skotizo has been defeated by " + player.getName() + " !");
        } else {
            World.sendMessage("<col=8714E6> Skotizo has been defeated by " + player.getName()
                    + ", a solo individual with balls of steel!");
        }
        justicar.unregister();
        activated = false;
    }
References activated, com.runehive.game.world.World.sendMessage(), and com.runehive.game.world.entity.mob.npc.Npc.unregister().
generateSpawn()
Npc com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn () static
Definition at line 22 of file JusticarUtility.java.
{
        activated = true;
        spawn = SpawnData2.generate();
        Npc jusiticar = new Npc(7858, spawn.position, 10, Direction.NORTH);
        World.sendMessage("<col=8714E6> Justicar has just spawned! He is located at " + spawn.location + "!");
        World.sendBroadcast(1, "The Justicar boss has spawned!" + spawn.location + "!", true);
        jusiticar.register();
        jusiticar.definition.setRespawnTime(-1);
        jusiticar.definition.setAggressive(true);
        jusiticar.speak("Darkness is here to penetrate your souls!");
        return jusiticar;
    }
References activated, com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.generate(), com.runehive.game.world.entity.mob.Direction.NORTH, com.runehive.game.world.entity.mob.npc.Npc.register(), com.runehive.game.world.World.sendBroadcast(), com.runehive.game.world.World.sendMessage(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setAggressive(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setRespawnTime(), spawn, and com.runehive.game.world.entity.mob.Mob.speak().
Member Data Documentation
activated
boolean com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.activated = false static
Definition at line 18 of file JusticarUtility.java.
Referenced by defeated(), and generateSpawn().
ALWAYSLOOT
int [] com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.ALWAYSLOOT = { 1, 1, 1, 1, 1, 2, 3, 4, 5 } static
Identification of all loot, it selects the loot.
Definition at line 37 of file JusticarUtility.java.
{ 1, 1, 1, 1, 1, 2, 3, 4, 5 };
COMMONLOOT
int [] com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.COMMONLOOT = { 6199, 989, 3140, 4087, 11732, 989, 12878, 6585, 4675 } static
Definition at line 38 of file JusticarUtility.java.
{ 6199, 989, 3140, 4087, 11732, 989, 12878, 6585, 4675 };
justicarbutton
boolean com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.justicarbutton static
Definition at line 20 of file JusticarUtility.java.
RARELOOT
int [] com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.RARELOOT static
Initial value:
= { 11834, 11832, 11828, 11830, 11836, 11773, 13239, 13237, 13235, 11772, 11771, 11770,
            20143, 20002 }
Definition at line 39 of file JusticarUtility.java.
                                   { 11834, 11832, 11828, 11830, 11836, 11773, 13239, 13237, 13235, 11772, 11771, 11770,
            20143, 20002 };
spawn
SpawnData2 com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.spawn static
Definition at line 16 of file JusticarUtility.java.
Referenced by generateSpawn().
SUPERRARELOOT
int [] com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SUPERRARELOOT static
Initial value:
= { 11862, 12817, 12825, 12821, 20997, 13652, 11802, 13576, 11785, 19481, 11791,
            12904, }
Definition at line 41 of file JusticarUtility.java.
                                        { 11862, 12817, 12825, 12821, 20997, 13652, 11802, 13576, 11785, 19481, 11791,
            12904, };
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/magearena/JusticarUtility.java