RuneHive-Game: com.runehive.game.action.impl.TeleportAction Class Reference
com.runehive.game.action.impl.TeleportAction Class Reference
Teleports an entity to another part of the world.
Public Member Functions
String getName ()
WalkablePolicy getWalkablePolicy ()
boolean prioritized ()
TeleportAction (Mob entity, Position position, TeleportationData type, Runnable onDestination)
Constructs a new TeleportAction object.
Public Member Functions inherited from com.runehive.game.action.ConsecutiveAction< T extends Mob >
ConsecutiveAction (T mob)
Generates a new ConsecutiveAction object.
void execute ()
Public Member Functions inherited from com.runehive.game.action.Action< T >
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
abstract String getName ()
Gets the name of this action.
abstract WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
boolean prioritized ()
Determines if this action is prioritized.
Protected Member Functions
void onCancel (boolean logout)
void onSchedule ()
Protected Member Functions inherited from com.runehive.game.action.ConsecutiveAction< T extends Mob >
void add (Consumer< Action< T > > action)
Adds an action to the actions list.
void addFirst (Consumer< Action< T > > action)
Adds an action to the actions list.
Private Member Functions
void end (Action< Mob > action)
void init ()
void move (Action< Mob > action)
void reset (Action< Mob > action)
void start (Action< Mob > action)
void startTablet (Action< Mob > action)
boolean valid (Action< Mob > action)
Private Attributes
final Runnable onDestination
The destination randomevent.
final Position position
The teleport position.
final TeleportationData type
The teleportType.
Detailed Description
Teleports an entity to another part of the world.
Author
Daniel
Michael | Chex
Definition at line 22 of file TeleportAction.java.
Constructor & Destructor Documentation
TeleportAction()
com.runehive.game.action.impl.TeleportAction.TeleportAction (Mob entity, Position position, TeleportationData type, Runnable onDestination)
Constructs a new TeleportAction object.
Definition at line 34 of file TeleportAction.java.
{
        super(entity);
        this.position = position;
        this.type = type;
        this.onDestination = onDestination;
    }
References onDestination, position, and type.
Member Function Documentation
end()
void com.runehive.game.action.impl.TeleportAction.end (Action< Mob > action) private
Definition at line 114 of file TeleportAction.java.
{
        type.getEndGraphic().ifPresent(action.getMob()::graphic);
        type.getEndAnimation().ifPresent(action.getMob()::animate);
        if (type.getEndAnimation().isPresent() || type.getEndGraphic().isPresent()) {
            action.setDelay(type.getDelay());
        }
        onDestination.run();
        action.getMob().onStep();
        //This is for overrides - updates appearance after teleport to account for duel arena
        action.getMob().updateFlags.add(UpdateFlag.APPEARANCE);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, onDestination, and type.
getName()
String com.runehive.game.action.impl.TeleportAction.getName ()
Definition at line 151 of file TeleportAction.java.
{
        return "teleport_action";
    }
getWalkablePolicy()
WalkablePolicy com.runehive.game.action.impl.TeleportAction.getWalkablePolicy ()
Definition at line 161 of file TeleportAction.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
init()
void com.runehive.game.action.impl.TeleportAction.init () private
Definition at line 56 of file TeleportAction.java.
{
        add(this::start);
        add(this::move);
        if (type != TeleportationData.TABLET)
            add(this::end);
        add(this::reset);
    }
References com.runehive.game.action.ConsecutiveAction< T extends Mob >.add(), com.runehive.content.skill.impl.magic.teleport.TeleportationData.TABLET, and type.
Referenced by onSchedule().
move()
void com.runehive.game.action.impl.TeleportAction.move (Action< Mob > action) private
Definition at line 98 of file TeleportAction.java.
{
        if (valid(action)) {
            action.setDelay(1);
            action.getMob().move(position);
            action.getMob().inTeleport = true;
            action.getMob().teleporting = true;
            if (action.getMob().isPlayer()) {
                action.getMob().getPlayer().send(new SendString("[CLOSE_MENU]", 0));
            }
        } else {
            reset(action);
            onDestination.run();
        }
    }
References onDestination, position, reset(), and valid().
onCancel()
void com.runehive.game.action.impl.TeleportAction.onCancel (boolean logout) protected
Definition at line 135 of file TeleportAction.java.
{
        getMob().animate(Animation.RESET, true);
        getMob().graphic(Graphic.RESET, true);
        getMob().inTeleport = false;
        getMob().teleporting = false;
        if (type == TeleportationData.TABLET) {
            getMob().getPlayer().pvpInstance = false;
            getMob().instance = Mob.DEFAULT_INSTANCE;
            if (getMob().getPlayer().pet != null) {
                getMob().getPlayer().pet.instance = getMob().instance;
            }
        }
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, com.runehive.game.action.Action< T >.getMob(), com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, com.runehive.content.skill.impl.magic.teleport.TeleportationData.TABLET, and type.
onSchedule()
void com.runehive.game.action.impl.TeleportAction.onSchedule () protected
Definition at line 42 of file TeleportAction.java.
{
        if (getMob().isPlayer() && getMob().getPlayer().isTeleblocked()) {
            cancel();
            getMob().getPlayer().message("You are currently under the affects of a teleblock spell and can not teleport!");
            return;
        }
        if (!valid(this)) {
            cancel();
        } else {
            init();
        }
    }
References com.runehive.game.action.Action< T >.getMob(), init(), and valid().
prioritized()
boolean com.runehive.game.action.impl.TeleportAction.prioritized ()
Definition at line 156 of file TeleportAction.java.
{
        return false;
    }
reset()
void com.runehive.game.action.impl.TeleportAction.reset (Action< Mob > action) private
Definition at line 129 of file TeleportAction.java.
{
        action.getMob().inTeleport = false;
        cancel();
    }
Referenced by move().
start()
void com.runehive.game.action.impl.TeleportAction.start (Action< Mob > action) private
Definition at line 75 of file TeleportAction.java.
{
        if (type != TeleportationData.HOME)
            action.getMob().inTeleport = true;
        action.setDelay(type.getDelay());
        action.getMob().movement.reset();
        type.getStartAnimation().ifPresent(action.getMob()::animate);
        type.getStartGraphic().ifPresent(action.getMob()::graphic);
        if (type.lockMovement()) {
            action.getMob().locking.lock();
        }
        if (type == TeleportationData.TABLET) {
            addFirst(this::startTablet);
        }
    }
References com.runehive.game.action.ConsecutiveAction< T extends Mob >.addFirst(), com.runehive.content.skill.impl.magic.teleport.TeleportationData.HOME, com.runehive.content.skill.impl.magic.teleport.TeleportationData.TABLET, and type.
startTablet()
void com.runehive.game.action.impl.TeleportAction.startTablet (Action< Mob > action) private
Definition at line 93 of file TeleportAction.java.
{
        action.setDelay(type.getDelay());
        type.getEndAnimation().ifPresent(action.getMob()::animate);
    }
References type.
valid()
boolean com.runehive.game.action.impl.TeleportAction.valid (Action< Mob > action) private
Definition at line 64 of file TeleportAction.java.
{
        if (type == TeleportationData.HOME && action.getMob().getCombat().inCombat()) {
            if (action.getMob().isPlayer()) {
                action.getMob().getPlayer().send(new SendMessage("You can't teleport home while in combat!"));
            }
            cancel();
            return false;
        }
        return true;
    }
References com.runehive.content.skill.impl.magic.teleport.TeleportationData.HOME, and type.
Referenced by move(), and onSchedule().
Member Data Documentation
onDestination
final Runnable com.runehive.game.action.impl.TeleportAction.onDestination private
The destination randomevent.
Definition at line 31 of file TeleportAction.java.
Referenced by end(), move(), and TeleportAction().
position
final Position com.runehive.game.action.impl.TeleportAction.position private
The teleport position.
Definition at line 25 of file TeleportAction.java.
Referenced by move(), and TeleportAction().
type
final TeleportationData com.runehive.game.action.impl.TeleportAction.type private
The teleportType.
Definition at line 28 of file TeleportAction.java.
Referenced by end(), init(), onCancel(), start(), startTablet(), TeleportAction(), and valid().
The documentation for this class was generated from the following file:
java/com/runehive/game/action/impl/TeleportAction.java