RuneHive-Game: dev.advo.fs.net.ondemand.OnDemandResponseEncoder Class Reference
dev.advo.fs.net.ondemand.OnDemandResponseEncoder Class Reference
Static Public Member Functions
static int create (int index, int file)
Protected Member Functions
Object encode (ChannelHandlerContext ctx, Channel c, Object msg) throws Exception
Detailed Description
Definition at line 12 of file OnDemandResponseEncoder.java.
Member Function Documentation
create()
int dev.advo.fs.net.ondemand.OnDemandResponseEncoder.create (int index, int file) static
Definition at line 33 of file OnDemandResponseEncoder.java.
{
            if ((index & 0xFFFFFFE0) != 0)
              throw new IllegalArgumentException("invalid index " + index + ":" + file);
            if ((file & 0xFFF80000) != 0)
              throw new IllegalArgumentException("invalid file " + index + ":" + file);
            return index & 0x1F | (file & 0x7FFFF) << 5;
          }
Referenced by encode().
encode()
Object dev.advo.fs.net.ondemand.OnDemandResponseEncoder.encode (ChannelHandlerContext ctx, Channel c, Object msg) throws Exception protected
Definition at line 15 of file OnDemandResponseEncoder.java.
{
        if (msg instanceof OnDemandResponse) {
            OnDemandResponse resp = (OnDemandResponse) msg;
            FileDescriptor fileDescriptor = resp.getFileDescriptor();
            int fileSize = resp.getFileSize();
            ChannelBuffer chunkData = resp.getChunkData();
            ChannelBuffer buf = ChannelBuffers.buffer(7 + chunkData.readableBytes());
            buf.writeMedium(create(fileDescriptor.getType(), fileDescriptor.getFile()));
            buf.writeInt(fileSize);
            buf.writeBytes(chunkData);
            return buf;
        }
        return msg;
    }
References create(), dev.advo.fs.net.ondemand.OnDemandResponse.getChunkData(), dev.advo.fs.fs.FileDescriptor.getFile(), dev.advo.fs.net.ondemand.OnDemandResponse.getFileDescriptor(), dev.advo.fs.net.ondemand.OnDemandResponse.getFileSize(), and dev.advo.fs.fs.FileDescriptor.getType().
The documentation for this class was generated from the following file:
java/dev/advo/fs/net/ondemand/OnDemandResponseEncoder.java