RuneHive-Game: com.runehive.content.prestige.Prestige Class Reference
com.runehive.content.prestige.Prestige Class Reference
Handles the prestige class.
Public Member Functions
boolean activatePerk (Item item)
Activates the perk.
int getColor (int tier)
Gets the prestige color based on the tier.
int getPrestigeColor (int skill)
Gets the current prestige color of the player.
int getPrestigePoint ()
boolean hasPerk (PrestigePerk perk)
void open ()
Opens the prestige panel.
void perkInformation ()
Displays all the perk information.
Prestige (Player player)
Constructs a new Prestige.
void prestige (PrestigeData data)
Handles prestiging the skill.
void setPrestigePoint (int prestigePoint)
Public Attributes
Set< PrestigePerk > activePerks = new HashSet<>()
The set of all the active perks for the player.
int[] prestige = new int[Skill.SKILL_COUNT]
The prestiges.
int totalPrestige
The total amount of prestiges.
Private Member Functions
String getColorInterface (int tier)
Gets the prestige color based on the tier for the itemcontainer.
Private Attributes
final Player player
The player instance.
int prestigePoint
The prestige points.
Static Private Attributes
static final String COLOR = "<col=354CE6>"
Detailed Description
Handles the prestige class.
Author
Daniel.
Definition at line 24 of file Prestige.java.
Constructor & Destructor Documentation
Prestige()
com.runehive.content.prestige.Prestige.Prestige (Player player)
Constructs a new Prestige.
Definition at line 44 of file Prestige.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
activatePerk()
boolean com.runehive.content.prestige.Prestige.activatePerk (Item item)
Activates the perk.
Definition at line 94 of file Prestige.java.
{
        PrestigePerk perk = PrestigePerk.forItem(item.getId());
        if (perk == null) {
            return false;
        }
        if (activePerks == null) {
            activePerks = new HashSet<>();
        }
        if (activePerks.contains(perk)) {
            player.send(new SendMessage("The Perk: " + perk.name + " perk is already active on your account!", MessageColor.DARK_BLUE));
            return true;
        }
        player.inventory.remove(item);
        activePerks.add(perk);
        player.send(new SendMessage("You have successfully activated the " + perk.name + " perk.", MessageColor.DARK_BLUE));
        return true;
    }
References activePerks, com.runehive.util.MessageColor.DARK_BLUE, com.runehive.content.prestige.PrestigePerk.forItem(), com.runehive.game.world.items.Item.getId(), com.runehive.content.prestige.PrestigePerk.name, and player.
getColor()
int com.runehive.content.prestige.Prestige.getColor (int tier)
Gets the prestige color based on the tier.
Definition at line 122 of file Prestige.java.
{
        switch (tier) {
            case 1:
                return 0xf49242;
            case 2:
                return 0x42f468;
            case 3:
                return 0x42d1f4;
            case 4:
                return 0xa76ffc;
            case 5:
                return 0xf44949;
            default:
                return 0xFFFF00;
        }
    }
Referenced by getColorInterface(), and getPrestigeColor().
getColorInterface()
String com.runehive.content.prestige.Prestige.getColorInterface (int tier) private
Gets the prestige color based on the tier for the itemcontainer.
Definition at line 140 of file Prestige.java.
{
        return Integer.toHexString(getColor(tier));
    }
References getColor().
Referenced by open().
getPrestigeColor()
int com.runehive.content.prestige.Prestige.getPrestigeColor (int skill)
Gets the current prestige color of the player.
Definition at line 117 of file Prestige.java.
{
        return getColor(prestige[skill]);
    }
References getColor(), and prestige.
Referenced by com.runehive.net.packet.out.SendSkill.encode(), and com.runehive.content.ProfileViewer.open().
getPrestigePoint()
int com.runehive.content.prestige.Prestige.getPrestigePoint ()
Definition at line 144 of file Prestige.java.
{
        return prestigePoint;
    }
References prestigePoint.
Referenced by com.runehive.content.store.currency.impl.PrestigePointCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.store.currency.impl.PrestigePointCurrency.recieveCurrency(), and com.runehive.content.store.currency.impl.PrestigePointCurrency.takeCurrency().
hasPerk()
boolean com.runehive.content.prestige.Prestige.hasPerk (PrestigePerk perk)
Definition at line 112 of file Prestige.java.
{
        return activePerks.contains(perk);
    }
References activePerks.
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.woodcutting.BirdsNest.drop(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), perkInformation(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
open()
void com.runehive.content.prestige.Prestige.open ()
Opens the prestige panel.
Definition at line 49 of file Prestige.java.
                       {
        player.send(new SendString(player.getName(), 52007));
        player.send(new SendString("Total Prestiges: <col=76E34B>" + totalPrestige + "</col>", 52008));
        player.send(new SendString("Prestige Points: <col=76E34B>" + prestigePoint + "</col>", 52009));
        Arrays.stream(PrestigeData.values).forEach(p -> player.send(new SendString(p.name + " " + "(<col=" + getColorInterface(prestige[p.skill]) + ">" + prestige[p.skill] + "</col>)", p.string)));
        player.interfaceManager.open(52000);
    }
References getColorInterface(), player, prestige, prestigePoint, totalPrestige, and com.runehive.content.prestige.PrestigeData.values.
Referenced by prestige().
perkInformation()
void com.runehive.content.prestige.Prestige.perkInformation ()
Displays all the perk information.
Definition at line 74 of file Prestige.java.
{
        final int totalPerks = PrestigePerk.values.length;
        for (int i = 0, string = 37114; i < totalPerks; i++) {
            PrestigePerk perk = PrestigePerk.forId(i);
            player.send(new SendString("<col=" + (hasPerk(perk) ? "347043" : "3c50b2") + ">" + perk.name, string++));
            player.send(new SendString(perk.description, string++));
            player.send(new SendString("", string++));
        }
        player.send(new SendString("<col=000000>This is a list of all the available perks.", 37111));
        player.send(new SendString("<col=000000>Perks with green names indicate that it is active.", 37112));
        player.send(new SendString("", 37113));
        player.send(new SendString("", 37107));
        player.send(new SendString("Prestige Perks Information", 37103));
        player.send(new SendScrollbar(37110, totalPerks * 65));
        player.send(new SendItemOnInterface(37199));
        player.interfaceManager.open(37100);
    }
References com.runehive.content.prestige.PrestigePerk.description, com.runehive.content.prestige.PrestigePerk.forId(), hasPerk(), com.runehive.content.prestige.PrestigePerk.name, player, and com.runehive.content.prestige.PrestigePerk.values.
prestige()
void com.runehive.content.prestige.Prestige.prestige (PrestigeData data)
Handles prestiging the skill.
Definition at line 58 of file Prestige.java.
{
        prestige[data.skill]++;
        totalPrestige += 1;
        prestigePoint += 1;
        player.skills.setExperience(data.skill, Skill.getExperienceForLevel(data.skill == 3 ? 10 : 1));
        player.skills.setMaxLevel(data.skill, data.skill == 3 ? 10 : 1);
        player.skills.setLevel(data.skill, data.skill == 3 ? 10 : 1);
        player.skills.refresh(data.skill);
        player.skills.setCombatLevel();
        player.bankVault.add(COINS, 1_000_000);
        player.send(new SendMessage("You have successfully prestiged your <col=255>" + Skill.getName(data.skill) + "</col> skill!"));
        World.sendMessage(  "<icon=21> Prestige: <col=354CE6>" + player.getName() + "</col> has prestiged " + Skill.getName(data.skill) + " and has a total of "  + player.prestige.totalPrestige +  " prestiges!");
        open();
    }
References com.runehive.game.world.entity.skill.Skill.getExperienceForLevel(), com.runehive.game.world.entity.skill.Skill.getName(), open(), player, prestige, prestigePoint, com.runehive.game.world.World.sendMessage(), com.runehive.content.prestige.PrestigeData.skill, and totalPrestige.
setPrestigePoint()
void com.runehive.content.prestige.Prestige.setPrestigePoint (int prestigePoint)
Definition at line 148 of file Prestige.java.
{
        this.prestigePoint = prestigePoint;
    }
References prestigePoint.
Referenced by com.runehive.content.store.currency.impl.PrestigePointCurrency.recieveCurrency(), and com.runehive.content.store.currency.impl.PrestigePointCurrency.takeCurrency().
Member Data Documentation
activePerks
Set<PrestigePerk> com.runehive.content.prestige.Prestige.activePerks = new HashSet<>()
The set of all the active perks for the player.
Definition at line 41 of file Prestige.java.
Referenced by activatePerk(), and hasPerk().
COLOR
final String com.runehive.content.prestige.Prestige.COLOR = "<col=354CE6>" static private
Definition at line 28 of file Prestige.java.
player
final Player com.runehive.content.prestige.Prestige.player private
The player instance.
Definition at line 27 of file Prestige.java.
Referenced by activatePerk(), open(), perkInformation(), Prestige(), and prestige().
prestige
int [] com.runehive.content.prestige.Prestige.prestige = new int[Skill.SKILL_COUNT]
The prestiges.
Definition at line 38 of file Prestige.java.
Referenced by getPrestigeColor(), open(), prestige(), and com.runehive.game.service.HighscoreService.saveHighscores().
prestigePoint
int com.runehive.content.prestige.Prestige.prestigePoint private
The prestige points.
Definition at line 35 of file Prestige.java.
Referenced by getPrestigePoint(), open(), prestige(), and setPrestigePoint().
totalPrestige
int com.runehive.content.prestige.Prestige.totalPrestige
The total amount of prestiges.
Definition at line 32 of file Prestige.java.
Referenced by open(), prestige(), com.runehive.game.service.HighscoreService.saveHighscores(), and com.runehive.game.world.entity.skill.SkillManager.updateSkill().
The documentation for this class was generated from the following file:
java/com/runehive/content/prestige/Prestige.java