RuneHive-Game: com.runehive.game.world.entity.combat.FormulaUtils Class Reference
com.runehive.game.world.entity.combat.FormulaUtils Class Reference
Static Public Member Functions
static boolean hasAmuletOfAvarice (Player player)
static boolean hasCrawsBow (Player player)
static boolean hasObbyWeapon (Player player)
static boolean hasThammaronSceptre (Player player)
static boolean hasViggorasChainMace (Player player)
static boolean obbyArmour (Player player)
static boolean voidBase (Player player)
static boolean voidMagic (Player player)
static boolean voidMelee (Player player)
static boolean voidRanger (Player player)
static boolean wearingBlackMask (Player player)
static boolean wearingBlackMaskImbued (Player player)
static boolean wearingEliteVoid (Player p)
Static Private Attributes
static final int[] BLACK_MASK = new int[]{BLACK_MASK_1_, BLACK_MASK_2, BLACK_MASK_3_, BLACK_MASK_4_, BLACK_MASK_5_, BLACK_MASK_6_, BLACK_MASK_7_, BLACK_MASK_8_, BLACK_MASK_9_, BLACK_MASK_10_}
static final int[] BLACK_MASK_IMBUED = new int[]{BLACK_MASK_1__I_, BLACK_MASK_2__I_, BLACK_MASK_3__I_, BLACK_MASK_4__I_, BLACK_MASK_5__I_, BLACK_MASK_6__I_, BLACK_MASK_7__I_, BLACK_MASK_8__I_, BLACK_MASK_9__I_, BLACK_MASK_10__I_}
Detailed Description
Definition at line 11 of file FormulaUtils.java.
Member Function Documentation
hasAmuletOfAvarice()
boolean com.runehive.game.world.entity.combat.FormulaUtils.hasAmuletOfAvarice (Player player) static
Definition at line 30 of file FormulaUtils.java.
{
        ItemContainer eq = player.equipment;
        return (eq.contains(22557) && Area.inWilderness(player));
    }
References com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, and com.runehive.game.world.position.Area.inWilderness().
hasCrawsBow()
boolean com.runehive.game.world.entity.combat.FormulaUtils.hasCrawsBow (Player player) static
Definition at line 26 of file FormulaUtils.java.
{
        return ((player.equipment.contains(22550)) && Area.inWilderness(player)) && player.crawsBowCharges > 0;
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, and com.runehive.game.world.position.Area.inWilderness().
Referenced by com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getOtherBonus().
hasObbyWeapon()
boolean com.runehive.game.world.entity.combat.FormulaUtils.hasObbyWeapon (Player player) static
Definition at line 35 of file FormulaUtils.java.
{
        var eq = player.equipment;
        return eq.contains(6525) || eq.contains(6528) || eq.contains(6523);
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), and com.runehive.game.world.entity.mob.player.Player.equipment.
hasThammaronSceptre()
boolean com.runehive.game.world.entity.combat.FormulaUtils.hasThammaronSceptre (Player player) static
Definition at line 21 of file FormulaUtils.java.
{
        ItemContainer eq = player.equipment;
        return (eq.contains(22555) && (Area.inWilderness(player))) && player.thammoranSceptreCharges > 0;
    }
References com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, and com.runehive.game.world.position.Area.inWilderness().
hasViggorasChainMace()
boolean com.runehive.game.world.entity.combat.FormulaUtils.hasViggorasChainMace (Player player) static
Definition at line 17 of file FormulaUtils.java.
{
        return ((player.equipment.contains(22545) && Area.inWilderness(player))) && player.viggorasChainmaceCharges > 0;
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, and com.runehive.game.world.position.Area.inWilderness().
obbyArmour()
boolean com.runehive.game.world.entity.combat.FormulaUtils.obbyArmour (Player player) static
Definition at line 12 of file FormulaUtils.java.
{
        ItemContainer eq = player.equipment;
        return ((eq.contains(21298) && eq.contains(21301) && eq.contains(21304)));
    }
References com.runehive.game.world.items.containers.ItemContainer.contains(), and com.runehive.game.world.entity.mob.player.Player.equipment.
voidBase()
boolean com.runehive.game.world.entity.combat.FormulaUtils.voidBase (Player player) static
Definition at line 40 of file FormulaUtils.java.
{
        return ((player.equipment.contains(8839)) && player.equipment.contains(8840)) || (player.equipment.contains(13072)) && (player.equipment.contains(13073)) && player.equipment.contains(8842);
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), and com.runehive.game.world.entity.mob.player.Player.equipment.
Referenced by voidMagic(), voidMelee(), and voidRanger().
voidMagic()
boolean com.runehive.game.world.entity.combat.FormulaUtils.voidMagic (Player player) static
Definition at line 53 of file FormulaUtils.java.
{
        return player.equipment.contains(11663) && voidBase(player);
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, and voidBase().
Referenced by com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEquipmentBonus(), and com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.successful().
voidMelee()
boolean com.runehive.game.world.entity.combat.FormulaUtils.voidMelee (Player player) static
Definition at line 49 of file FormulaUtils.java.
{
        return player.equipment.contains(11665) && voidBase(player);
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, and voidBase().
Referenced by com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getEffectiveLevel().
voidRanger()
boolean com.runehive.game.world.entity.combat.FormulaUtils.voidRanger (Player player) static
Definition at line 45 of file FormulaUtils.java.
{
        return player.equipment.contains(11664) && voidBase(player);
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, and voidBase().
Referenced by com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getEffectiveLevel(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getEffectiveRanged(), and com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getOtherBonus().
wearingBlackMask()
boolean com.runehive.game.world.entity.combat.FormulaUtils.wearingBlackMask (Player player) static
Definition at line 64 of file FormulaUtils.java.
{
        return Arrays.stream(BLACK_MASK).anyMatch(mask -> player.equipment.contains(mask));
    }
References BLACK_MASK, com.runehive.game.world.items.containers.equipment.Equipment.contains(), and com.runehive.game.world.entity.mob.player.Player.equipment.
wearingBlackMaskImbued()
boolean com.runehive.game.world.entity.combat.FormulaUtils.wearingBlackMaskImbued (Player player) static
Definition at line 68 of file FormulaUtils.java.
{
        return Arrays.stream(BLACK_MASK_IMBUED).anyMatch(mask -> player.equipment.contains(mask));
    }
References BLACK_MASK_IMBUED, com.runehive.game.world.items.containers.equipment.Equipment.contains(), and com.runehive.game.world.entity.mob.player.Player.equipment.
wearingEliteVoid()
boolean com.runehive.game.world.entity.combat.FormulaUtils.wearingEliteVoid (Player p) static
Definition at line 57 of file FormulaUtils.java.
{
        return (p.equipment.contains(11665) || p.equipment.contains(11664) || p.equipment.contains(11663)) && p.equipment.contains(13072) && p.equipment.contains(13073) && p.equipment.contains(8842);
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), and com.runehive.game.world.entity.mob.player.Player.equipment.
Referenced by com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getOtherBonus().
Member Data Documentation
BLACK_MASK
final int [] com.runehive.game.world.entity.combat.FormulaUtils.BLACK_MASK = new int[]{BLACK_MASK_1_, BLACK_MASK_2, BLACK_MASK_3_, BLACK_MASK_4_, BLACK_MASK_5_, BLACK_MASK_6_, BLACK_MASK_7_, BLACK_MASK_8_, BLACK_MASK_9_, BLACK_MASK_10_} static private
Definition at line 61 of file FormulaUtils.java.
{BLACK_MASK_1_, BLACK_MASK_2, BLACK_MASK_3_, BLACK_MASK_4_, BLACK_MASK_5_, BLACK_MASK_6_, BLACK_MASK_7_, BLACK_MASK_8_, BLACK_MASK_9_, BLACK_MASK_10_};
Referenced by wearingBlackMask().
BLACK_MASK_IMBUED
final int [] com.runehive.game.world.entity.combat.FormulaUtils.BLACK_MASK_IMBUED = new int[]{BLACK_MASK_1__I_, BLACK_MASK_2__I_, BLACK_MASK_3__I_, BLACK_MASK_4__I_, BLACK_MASK_5__I_, BLACK_MASK_6__I_, BLACK_MASK_7__I_, BLACK_MASK_8__I_, BLACK_MASK_9__I_, BLACK_MASK_10__I_} static private
Definition at line 62 of file FormulaUtils.java.
{BLACK_MASK_1__I_, BLACK_MASK_2__I_, BLACK_MASK_3__I_, BLACK_MASK_4__I_, BLACK_MASK_5__I_, BLACK_MASK_6__I_, BLACK_MASK_7__I_, BLACK_MASK_8__I_, BLACK_MASK_9__I_, BLACK_MASK_10__I_};
Referenced by wearingBlackMaskImbued().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/FormulaUtils.java