RuneHive-Game: com.runehive.content.triviabot.TriviaBot Class Reference
com.runehive.content.triviabot.TriviaBot Class Reference
Manages the trivia bot system.
Static Public Member Functions
static void answer (Player player, String answer)
Handles player answering the question.
static void assign ()
Assigns a new question.
static void declare ()
Declares the TriviaBot data.
Static Public Attributes
static int answeredTotal = 0
Static Private Member Functions
static void answered (Player player, String answer)
Handles player answering the question successfully.
Static Private Attributes
static final String COLOR = "<col=354CE6>"
Color of the TriviaBot messages.
static TriviaBotData CURRENT = null
The current question/answer set.
static final Set< TriviaBotData > DATA = new HashSet<>()
Holds all the bot data.
Detailed Description
Manages the trivia bot system.
Author
Daniel
Definition at line 25 of file TriviaBot.java.
Member Function Documentation
answer()
void com.runehive.content.triviabot.TriviaBot.answer (Player player, String answer) static
Handles player answering the question.
Definition at line 62 of file TriviaBot.java.
{
        if (!player.settings.triviaBot) {
            return;
        }
        if (CURRENT == null) {
            player.send(new SendMessage(COLOR + "<icon=21> TriviaBot: </col>There is no question currently assigned!"));
            return;
        }
        if (Arrays.stream(Config.BAD_STRINGS).anyMatch(answer::contains)) {
            player.send(new SendMessage(COLOR + "<icon=21> TriviaBot: </col>You think you're funny, don't you? Guess what? You ain't."));
            return;
        }
        if (Arrays.stream(CURRENT.getAnswers()).anyMatch(a -> a.equalsIgnoreCase(answer))) {
            answered(player, answer);
            return;
        }
        if (Utility.random(3) == 0) {
            player.speak("Golly gee! I just entered a wrong trivia answer!");
        }
        player.send(new SendMessage(COLOR + "<icon=21> TriviaBot: </col>Sorry, the answer you have entered is incorrect! Try again!"));
    }
References answer(), answered(), com.runehive.Config.BAD_STRINGS, COLOR, CURRENT, com.runehive.util.Utility.random(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.Player.settings, com.runehive.game.world.entity.mob.Mob.speak(), and com.runehive.game.world.entity.mob.player.Settings.triviaBot.
Referenced by answer(), and answered().
answered()
void com.runehive.content.triviabot.TriviaBot.answered (Player player, String answer) static private
Handles player answering the question successfully.
Definition at line 87 of file TriviaBot.java.
{
        String color = player.right.getColor();
        int reward = Utility.random(50, 150);
        if (PlayerRight.isIronman(player)) {
            player.bankVault.add(COINS, reward);
            AchievementHandler.activate(player, AchievementKey.TRIVIABOT, 1);
            player.answeredTrivias += 1;
            player.send(new SendMessage(Utility.formatDigits(reward) + " coins were added into your bank vault."));
        } else {
            player.bankVault.add(BLOOD_MONEY, reward);
            player.answeredTrivias += 1;
            AchievementHandler.activate(player, AchievementKey.TRIVIABOT, 1);
            player.send(new SendMessage(Utility.formatDigits(reward) + " blood money were added into your bank vault."));
        }
        // DISABLED
        // World.sendMessage(COLOR + "<icon=21> TriviaBot: <col=" + color + ">" + player.getName() + "</col> has answered the question correctly!");
        CURRENT = null;
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.items.containers.bank.BankVault.add(), answer(), com.runehive.game.world.entity.mob.player.Player.bankVault, CURRENT, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.PlayerRight.getColor(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.util.Utility.random(), com.runehive.game.world.entity.mob.player.Player.right, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.content.achievement.AchievementKey.TRIVIABOT.
Referenced by answer().
assign()
void com.runehive.content.triviabot.TriviaBot.assign () static
Assigns a new question.
Definition at line 53 of file TriviaBot.java.
{
        // DISABLED
        // CURRENT = Utility.randomElement(DATA);
        // World.sendMessage(COLOR + "<icon=21> TriviaBot: </col>" + CURRENT.getQuestion(), player -> player.settings.triviaBot);
    }
Referenced by com.runehive.game.task.impl.MessageEvent.execute().
declare()
void com.runehive.content.triviabot.TriviaBot.declare () static
Declares the TriviaBot data.
Definition at line 46 of file TriviaBot.java.
{
        Collections.addAll(DATA, TriviaBotData.values());
    }
References DATA.
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
Member Data Documentation
answeredTotal
int com.runehive.content.triviabot.TriviaBot.answeredTotal = 0 static
Definition at line 42 of file TriviaBot.java.
COLOR
final String com.runehive.content.triviabot.TriviaBot.COLOR = "<col=354CE6>" static private
Color of the TriviaBot messages.
Definition at line 40 of file TriviaBot.java.
Referenced by answer().
CURRENT
TriviaBotData com.runehive.content.triviabot.TriviaBot.CURRENT = null static private
The current question/answer set.
Definition at line 35 of file TriviaBot.java.
Referenced by answer(), and answered().
DATA
final Set<TriviaBotData> com.runehive.content.triviabot.TriviaBot.DATA = new HashSet<>() static private
Holds all the bot data.
Definition at line 30 of file TriviaBot.java.
Referenced by declare().
The documentation for this class was generated from the following file:
java/com/runehive/content/triviabot/TriviaBot.java