RuneHive-Game: com.runehive.content.activity.record.PlayerRecord Class Reference
com.runehive.content.activity.record.PlayerRecord Class Reference
Public Member Functions
void add (GameRecord tracker)
void display (ActivityType activity)
void display (boolean global, ActivityType activity)
long end (ActivityType activity)
long end (ActivityType activity, boolean track)
PlayerRecord (Player player)
void start ()
Public Attributes
boolean global
long time
Package Functions
void clean (int size)
void showActivities (ActivityType viewing)
Private Attributes
Map< ActivityType, TreeSet< GameRecord > > personalRecord = new HashMap<>()
final Player player
Detailed Description
Definition at line 11 of file PlayerRecord.java.
Constructor & Destructor Documentation
PlayerRecord()
com.runehive.content.activity.record.PlayerRecord.PlayerRecord (Player player)
Definition at line 18 of file PlayerRecord.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
add()
void com.runehive.content.activity.record.PlayerRecord.add (GameRecord tracker)
Definition at line 48 of file PlayerRecord.java.
{
        ActivityType activity = tracker.activityType;
        TreeSet<GameRecord> personal = personalRecord.computeIfAbsent(activity, act -> new TreeSet<>(Comparator.comparingLong(record -> record.time)));
        if (personal.size() < 10) {
            personal.add(tracker);
        } else if (tracker.time < personal.first().time) {
            personal.pollLast();
            personal.add(tracker);
        }
    }
References com.runehive.content.activity.record.GameRecord.activityType, personalRecord, and com.runehive.content.activity.record.GameRecord.time.
Referenced by end().
clean()
void com.runehive.content.activity.record.PlayerRecord.clean (int size) package
Definition at line 59 of file PlayerRecord.java.
{
        int string = 32401;
        for (int count = 0; count < (size < 25 ? 25 : size); count++) {
            player.send(new SendString("", ++string));
            player.send(new SendString("", ++string));
            player.send(new SendString("", ++string));
            player.send(new SendString("", ++string));
            string++;
        }
        player.send(new SendScrollbar(32400, (size < 10 ? 10 : size) * 28));
    }
References player.
Referenced by display().
display() [1/2]
void com.runehive.content.activity.record.PlayerRecord.display (ActivityType activity)
Definition at line 93 of file PlayerRecord.java.
{
        display(global, activity);
    }
References display(), and global.
Referenced by display(), and com.runehive.game.plugin.PluginContext.onClick().
display() [2/2]
void com.runehive.content.activity.record.PlayerRecord.display (boolean global, ActivityType activity)
Definition at line 97 of file PlayerRecord.java.
{
        this.global = global;
        player.send(new SendConfig(325, global ? 1 : 0));
      /*  if (global) {
            GlobalRecords.display(player, activity);
            return;
        }*/
        clean(0);
        showActivities(activity);
        TreeSet<GameRecord> records = personalRecord.getOrDefault(activity, new TreeSet<>());
        int idx = 0;
        for (GameRecord personal : records) {
            player.send(new SendString((idx / 5 + 1) + ")", (idx + 1) + 32401));
            player.send(new SendString(Utility.formatName(personal.name), (idx + 2) + 32401));
            player.send(new SendString(personal.time == 0 ? "None!" : Utility.getTime(personal.time), (idx + 3) + 32401));
            player.send(new SendString(personal.date, (idx + 4) + 32401));
            idx += 5;
        }
        player.send(new SendScrollbar(32400, (records.size() < 9 ? 9 : records.size()) * 28));
        player.interfaceManager.open(32300);
    }
References clean(), com.runehive.util.Utility.formatName(), com.runehive.util.Utility.getTime(), global, personalRecord, player, and showActivities().
end() [1/2]
long com.runehive.content.activity.record.PlayerRecord.end (ActivityType activity)
Definition at line 26 of file PlayerRecord.java.
{
        return end(activity, true);
    }
References end().
Referenced by end().
end() [2/2]
long com.runehive.content.activity.record.PlayerRecord.end (ActivityType activity, boolean track)
Definition at line 30 of file PlayerRecord.java.
{
        long record = System.currentTimeMillis() - time;
        /* Don't add if time is longer than 30 minutes */
        if (record > 1_800_000) {
            return 0;
        }
        if (track && !PlayerRight.isAdministrator(player)) {
            GameRecord tracker = new GameRecord(player, record, activity);
           // GlobalRecords.add(player, tracker);
            add(tracker);
        }
        time = -1;
        return record;
    }
References add(), com.runehive.game.world.entity.mob.player.PlayerRight.isAdministrator(), player, and time.
showActivities()
void com.runehive.content.activity.record.PlayerRecord.showActivities (ActivityType viewing) package
Definition at line 71 of file PlayerRecord.java.
{
        int count = 0;
        String[] marquee = new String[5];
        List<ActivityType> activities = ActivityType.getRecordable();
        for (ActivityType activity : activities) {
            String name = Utility.formatEnum(activity.name());
            player.send(new SendString((viewing == activity ? "<col=ffffff>" : "</col>") + name, 32352 + count));
            player.send(new SendTooltip("Display " + name + " records", 32352 + count));
            count +=2;
        }
        for (int index = 0; index < marquee.length; index++) {
            ActivityType type = Utility.randomElement(activities);
          //  GameRecord top = GlobalRecords.getTopRecord(type);
            activities.remove(type);
         //   String details = top == null ? "None" : top.name + "(" + Utility.getTime(top.time) + ")";
         //   marquee[index] = Utility.formatEnum(type.name()) + ": " + details;
        }
        int size = ActivityType.values().length < 12 ? 12 : ActivityType.values().length;
        player.send(new SendScrollbar(32350 , size * 23));
        player.send(new SendMarquee(32306, marquee));
    }
References com.runehive.util.Utility.formatEnum(), com.runehive.content.activity.ActivityType.getRecordable(), player, and com.runehive.util.Utility.randomElement().
Referenced by display().
start()
void com.runehive.content.activity.record.PlayerRecord.start ()
Definition at line 22 of file PlayerRecord.java.
{
        time = System.currentTimeMillis();
    }
References time.
Member Data Documentation
global
boolean com.runehive.content.activity.record.PlayerRecord.global
Definition at line 15 of file PlayerRecord.java.
Referenced by display(), and display().
personalRecord
Map<ActivityType, TreeSet<GameRecord> > com.runehive.content.activity.record.PlayerRecord.personalRecord = new HashMap<>() private
Definition at line 16 of file PlayerRecord.java.
Referenced by add(), and display().
player
final Player com.runehive.content.activity.record.PlayerRecord.player private
Definition at line 13 of file PlayerRecord.java.
Referenced by clean(), display(), end(), PlayerRecord(), and showActivities().
time
long com.runehive.content.activity.record.PlayerRecord.time
Definition at line 14 of file PlayerRecord.java.
Referenced by end(), and start().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/record/PlayerRecord.java