RuneHive-Game: com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector Class Reference
com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector Class Reference
Drives a simple "over-the-shoulder" dialogue camera:
Classes
enum Mode
Static Public Member Functions
static void boostSwap (Player p, int ticks)
Small helper to prime faster turn for a few ticks after a mode swap.
static void requestReset (Player p)
Ask for a smooth reset on the next tick.
static void tick (Player p)
Recompute and send camera on each tick while active.
Private Member Functions
DialogueCameraDirector ()
Static Private Member Functions
static void shoulderShot (Player p, Position from, Position to, int moveConst, int moveVar, int turnConst, int turnVar)
Place camera behind 'from' and turn toward 'to'.
Static Private Attributes
static final double BACK = 1.7
static final boolean DEBUG = true
static final int MOVE_CONST_BASE = 18
static final int MOVE_CONST_SWAP = 16
static final int MOVE_VAR_BASE = 0
static final int MOVE_VAR_SWAP = 0
static final int MOVE_Z = 220
static final double RIGHT = RIGHT_BASE + RIGHT_NUDGE
static final double RIGHT_BASE = 0.35
static final double RIGHT_NUDGE = 0.25
static final int TURN_CONST_BASE = 20
static final int TURN_CONST_SWAP = 14
static final int TURN_TILT_Z = 210
static final int TURN_VAR_BASE = 0
static final int TURN_VAR_SWAP = 0
Detailed Description
Drives a simple "over-the-shoulder" dialogue camera:
BEHIND_PLAYER: camera behind player, looks at NPC
BEHIND_NPC: camera behind NPC, looks at player Smoothness is controlled by camera packet speeds (const/var).
Definition at line 16 of file DialogueCameraDirector.java.
Constructor & Destructor Documentation
DialogueCameraDirector()
com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.DialogueCameraDirector () private
Definition at line 38 of file DialogueCameraDirector.java.
{}
Member Function Documentation
boostSwap()
void com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.boostSwap (Player p, int ticks) static
Small helper to prime faster turn for a few ticks after a mode swap.
Definition at line 179 of file DialogueCameraDirector.java.
{
        p.dialogueCamSwapBoostTicks = Math.max(p.dialogueCamSwapBoostTicks, Math.max(1, ticks));
    }
References com.runehive.game.world.entity.mob.player.Player.dialogueCamSwapBoostTicks.
requestReset()
void com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.requestReset (Player p) static
Ask for a smooth reset on the next tick.
Definition at line 172 of file DialogueCameraDirector.java.
{
        if (p.dialogueCamMode != Mode.OFF) {
            p.dialogueCamMode = Mode.RESET_PENDING;
        }
    }
References com.runehive.game.world.entity.mob.player.Player.dialogueCamMode, com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.OFF, and com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.RESET_PENDING.
Referenced by tick().
shoulderShot()
void com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.shoulderShot (Player p, Position from, Position to, int moveConst, int moveVar, int turnConst, int turnVar) static private
Place camera behind 'from' and turn toward 'to'.
Definition at line 110 of file DialogueCameraDirector.java.
{
        System.out.println("== Dialogue Camera Shot ==");
        System.out.println("Player world pos : " + from);
        System.out.println("Target world pos : " + to);
        System.out.println("Player position  : " + p.getPosition());
        System.out.println("from.getLocalX(p.pos) : " + from.getLocalX(p.getPosition()));
        System.out.println("from.getLocalY(p.pos) : " + from.getLocalY(p.getPosition()));
        System.out.println("to.getLocalX(p.pos)   : " + to.getLocalX(p.getPosition()));
        System.out.println("to.getLocalY(p.pos)   : " + to.getLocalY(p.getPosition()));
        final double dx = to.getX() - from.getX();
        final double dy = to.getY() - from.getY();
        final double len = Math.max(1e-6, Math.hypot(dx, dy));
        // Forward vector from 'from' → 'to'
        final double fx = dx / len;
        final double fy = dy / len;
        // Right-hand vector (perpendicular on the plane)
        final double rx =  fy, ry = -fx;
        // Behind-right shoulder camera position
        final double camX = from.getX() - fx * BACK + rx * RIGHT;
        final double camY = from.getY() - fy * BACK + ry * RIGHT;
        final Position cam  = new Position((int)Math.round(camX), (int)Math.round(camY), from.getHeight());
        final Position look = to; // look straight at the target speaker/listener
        // Guard: skip if we haven't set the scene base yet (first tick before MapRegion)
        if (p.getSceneBaseChunkX() == 0 && p.getSceneBaseChunkY() == 0) {
            return;
        }
        final int localCamX  = p.toSceneLocalX(cam);
        final int localCamY  = p.toSceneLocalY(cam);
        final int localLookX = p.toSceneLocalX(look);
        final int localLookY = p.toSceneLocalY(look);
        // Safety bounds
        if ((localCamX|localCamY|localLookX|localLookY) < 0 ||
            localCamX > 104 || localCamY > 104 || localLookX > 104 || localLookY > 104) {
            System.err.printf("[Camera BUG] Out-of-bounds: LocalCam=(%d,%d) LocalLook=(%d,%d)%n",
                localCamX, localCamY, localLookX, localLookY);
            return;
        }
        if (DEBUG) {
            System.out.printf("GlobalCam=(%d,%d) GlobalLook=(%d,%d) | SceneBaseTiles=(%d,%d) | LocalCam=(%d,%d) LocalLook=(%d,%d)%n",
                cam.getX(), cam.getY(),
                look.getX(), look.getY(),
                p.getSceneBaseChunkX() * 8, p.getSceneBaseChunkY() * 8,
                localCamX, localCamY,
                localLookX, localLookY
            );
        }
        p.send(new SendCameraMove(localCamX, localCamY, MOVE_Z, moveConst, moveVar));
        p.send(new SendCameraTurn(localLookX, localLookY, TURN_TILT_Z, turnConst, turnVar));
    }
References BACK, DEBUG, com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getLocalX(), com.runehive.game.world.position.Position.getLocalY(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.player.Player.getSceneBaseChunkX(), com.runehive.game.world.entity.mob.player.Player.getSceneBaseChunkY(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), MOVE_Z, RIGHT, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.Player.toSceneLocalX(), com.runehive.game.world.entity.mob.player.Player.toSceneLocalY(), and TURN_TILT_Z.
Referenced by tick().
tick()
void com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick (Player p) static
Recompute and send camera on each tick while active.
Definition at line 41 of file DialogueCameraDirector.java.
{
        if (p.dialogueCamMode == Mode.OFF) return;
        if (p.regionChange) return; // skip 1-2 ticks while scene base shifts
        // Handle delay before camera activation
        if (p.dialogueCamDelayTicks > 0) {
            p.dialogueCamDelayTicks--;
            if (p.dialogueCamDelayTicks == 0) {
                p.dialogueCamMode = Mode.BEHIND_PLAYER; // now safe to activate
                if (DEBUG) {
                    System.out.println("[DialogueCam] Delay complete, activating BEHIND_PLAYER mode");
                }
            }
            if (DEBUG) {
                System.out.println("[DialogueCam] Delaying activation: " + p.dialogueCamDelayTicks + " ticks remaining");
            }
            return;
        }
        if (p.dialogueCamMode == Mode.OFF) return;
        final Npc npc = p.dialogueCamNpc;
        if (npc == null || npc.isDead() || p.isDead()) {
            // If target is gone, reset smoothly
            requestReset(p);
            return;
        }
        final Position playerPos = p.getPosition();
        final Position npcPos    = npc.getPosition();
        // Choose speeds; during swap-boost we turn a bit faster
        final boolean swapBoost = p.dialogueCamSwapBoostTicks > 0;
        final int moveConst = swapBoost ? MOVE_CONST_SWAP : MOVE_CONST_BASE;
        final int moveVar   = swapBoost ? MOVE_VAR_SWAP   : MOVE_VAR_BASE;
        final int turnConst = swapBoost ? TURN_CONST_SWAP : TURN_CONST_BASE;
        final int turnVar   = swapBoost ? TURN_VAR_SWAP   : TURN_VAR_BASE;
        if (DEBUG) {
            System.out.println("[DialogueCam] Mode=" + p.dialogueCamMode +
                " | Delay=" + p.dialogueCamDelayTicks +
                " | PlayerPos=" + p.getPosition() +
                " | NpcPos=" + (p.dialogueCamNpc != null ? p.dialogueCamNpc.getPosition() : "null"));
        }
        switch (p.dialogueCamMode) {
            case BEHIND_PLAYER -> {
                shoulderShot(p, playerPos, npcPos, moveConst, moveVar, turnConst, turnVar); // behind player, look at NPC
            }
            case BEHIND_NPC -> {
                shoulderShot(p, npcPos, playerPos, moveConst, moveVar, turnConst, turnVar); // behind NPC, look at player
            }
            case RESET_PENDING -> {
                // Send one gentle easing frame, then clear cinematics
                shoulderShot(p, playerPos, playerPos, MOVE_CONST_BASE, MOVE_VAR_BASE, TURN_CONST_BASE, TURN_VAR_BASE); // short ease toward default
                p.send(new SendCameraReset());         // opcode 107
                p.dialogueCamMode = Mode.OFF;
                p.dialogueCamNpc  = null;
                p.dialogueCamSwapBoostTicks = 0;
            }
            default -> { /* no-op */ }
        }
        if (p.dialogueCamSwapBoostTicks > 0) {
            p.dialogueCamSwapBoostTicks--;
        }
    }
References com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_PLAYER, DEBUG, com.runehive.game.world.entity.mob.player.Player.dialogueCamDelayTicks, com.runehive.game.world.entity.mob.player.Player.dialogueCamMode, com.runehive.game.world.entity.mob.player.Player.dialogueCamNpc, com.runehive.game.world.entity.mob.player.Player.dialogueCamSwapBoostTicks, com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.Mob.isDead(), MOVE_CONST_BASE, MOVE_CONST_SWAP, MOVE_VAR_BASE, MOVE_VAR_SWAP, com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.OFF, com.runehive.game.world.entity.mob.Mob.regionChange, requestReset(), com.runehive.game.world.entity.mob.player.Player.send(), shoulderShot(), TURN_CONST_BASE, TURN_CONST_SWAP, TURN_VAR_BASE, and TURN_VAR_SWAP.
Member Data Documentation
BACK
final double com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.BACK = 1.7 static private
Definition at line 24 of file DialogueCameraDirector.java.
Referenced by shoulderShot().
DEBUG
final boolean com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.DEBUG = true static private
Definition at line 21 of file DialogueCameraDirector.java.
Referenced by shoulderShot(), and tick().
MOVE_CONST_BASE
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.MOVE_CONST_BASE = 18 static private
Definition at line 32 of file DialogueCameraDirector.java.
Referenced by tick().
MOVE_CONST_SWAP
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.MOVE_CONST_SWAP = 16 static private
Definition at line 35 of file DialogueCameraDirector.java.
Referenced by tick().
MOVE_VAR_BASE
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.MOVE_VAR_BASE = 0 static private
Definition at line 32 of file DialogueCameraDirector.java.
Referenced by tick().
MOVE_VAR_SWAP
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.MOVE_VAR_SWAP = 0 static private
Definition at line 35 of file DialogueCameraDirector.java.
Referenced by tick().
MOVE_Z
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.MOVE_Z = 220 static private
Definition at line 28 of file DialogueCameraDirector.java.
Referenced by shoulderShot().
RIGHT
final double com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.RIGHT = RIGHT_BASE + RIGHT_NUDGE static private
Definition at line 27 of file DialogueCameraDirector.java.
Referenced by shoulderShot().
RIGHT_BASE
final double com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.RIGHT_BASE = 0.35 static private
Definition at line 25 of file DialogueCameraDirector.java.
RIGHT_NUDGE
final double com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.RIGHT_NUDGE = 0.25 static private
Definition at line 26 of file DialogueCameraDirector.java.
TURN_CONST_BASE
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.TURN_CONST_BASE = 20 static private
Definition at line 33 of file DialogueCameraDirector.java.
Referenced by tick().
TURN_CONST_SWAP
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.TURN_CONST_SWAP = 14 static private
Definition at line 36 of file DialogueCameraDirector.java.
Referenced by tick().
TURN_TILT_Z
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.TURN_TILT_Z = 210 static private
Definition at line 29 of file DialogueCameraDirector.java.
Referenced by shoulderShot().
TURN_VAR_BASE
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.TURN_VAR_BASE = 0 static private
Definition at line 33 of file DialogueCameraDirector.java.
Referenced by tick().
TURN_VAR_SWAP
final int com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.TURN_VAR_SWAP = 0 static private
Definition at line 36 of file DialogueCameraDirector.java.
Referenced by tick().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/camera/DialogueCameraDirector.java