RuneHive-Game: com.runehive.game.world.entity.combat.CombatDamage Class Reference
com.runehive.game.world.entity.combat.CombatDamage Class Reference
A fs of players who have inflicted damage on another player in a combat session.
Classes
class DamageCounter
A counter that will track the amount of damage dealt and whether that damaged has timed out or not.
Public Member Functions
void add (Mob character, Hit hit)
Registers damage in the backing collection for character.
Optional< Mob > calculateProperKiller ()
Determines which entity in the backing collection has inflicted the most damage.
void clear ()
Clears all data from the backing collection.
Optional< Npc > getNpcKiller ()
Determines which player in the backing collection has inflicted the most damage.
Optional< Player > getPlayerKiller ()
Determines which player in the backing collection has inflicted the most damage.
Public Attributes
Hit lastHit
Private Attributes
final Map< Mob, DamageCounter > attackers = new HashMap<>()
The damages of players who have inflicted damage.
Detailed Description
A fs of players who have inflicted damage on another player in a combat session.
Author
lare96 http://github.com/lare96
Definition at line 21 of file CombatDamage.java.
Member Function Documentation
add()
void com.runehive.game.world.entity.combat.CombatDamage.add (Mob character, Hit hit)
Registers damage in the backing collection for character.
This method has no effect if the character isn't a PLAYER or if amount is below 0.
Parameters
character the character to register damage for.
hit the hit to register.
Definition at line 38 of file CombatDamage.java.
{
        if (hit.getDamage() > 0) {
            DamageCounter counter = attackers.putIfAbsent(character, new DamageCounter(hit.getDamage()));
            if (counter != null)
                counter.incrementAmount(hit.getDamage());
            lastHit = hit;
        }
    }
References attackers, com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.incrementAmount(), and lastHit.
calculateProperKiller()
Optional< Mob > com.runehive.game.world.entity.combat.CombatDamage.calculateProperKiller ()
Determines which entity in the backing collection has inflicted the most damage.
Returns
the player who has inflicted the most damage, or an empty optional if there are no entries.
Definition at line 102 of file CombatDamage.java.
{
        int amount = 0;
        Mob killer = null;
        for (Map.Entry<Mob, DamageCounter> entry : attackers.entrySet()) {
            DamageCounter counter = entry.getValue();
            Mob mob = entry.getKey();
            if (mob.isDead() || !mob.isValid() || counter.isTimeout())
                continue;
            if (attackers.size() > 1 && mob.isPlayer() && PlayerRight.isIronman(mob.getPlayer()))
                continue;
            if (counter.getAmount() > amount) {
                amount = counter.getAmount();
                killer = mob;
            }
        }
        return Optional.ofNullable(killer);
    }
References attackers, com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.getAmount(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), and com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.isTimeout().
clear()
void com.runehive.game.world.entity.combat.CombatDamage.clear ()
Clears all data from the backing collection.
Definition at line 126 of file CombatDamage.java.
{
        attackers.clear();
    }
References attackers.
getNpcKiller()
Optional< Npc > com.runehive.game.world.entity.combat.CombatDamage.getNpcKiller ()
Determines which player in the backing collection has inflicted the most damage.
Returns
the player who has inflicted the most damage, or an empty optional if there are no entries.
Definition at line 54 of file CombatDamage.java.
{
        int amount = 0;
        Npc killer = null;
        for (Map.Entry<Mob, DamageCounter> entry : attackers.entrySet()) {
            DamageCounter counter = entry.getValue();
            Mob entity = entry.getKey();
            if (!entity.isNpc() || entity.isDead() || !entity.isValid() || counter.isTimeout())
                continue;
            if (counter.getAmount() > amount) {
                amount = counter.getAmount();
                killer = entity.getNpc();
            }
        }
        return Optional.ofNullable(killer);
    }
References attackers, com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.getAmount(), and com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.isTimeout().
getPlayerKiller()
Optional< Player > com.runehive.game.world.entity.combat.CombatDamage.getPlayerKiller ()
Determines which player in the backing collection has inflicted the most damage.
Returns
the player who has inflicted the most damage, or an empty optional if there are no entries.
Definition at line 78 of file CombatDamage.java.
{
        int amount = 0;
        Player killer = null;
        for (Map.Entry<Mob, DamageCounter> entry : attackers.entrySet()) {
            DamageCounter counter = entry.getValue();
            Mob entity = entry.getKey();
            if (!entity.isPlayer() || entity.isDead() || entity.isValid() || counter.isTimeout())
                continue;
            if (counter.getAmount() > amount) {
                amount = counter.getAmount();
                killer = entity.getPlayer();
            }
        }
        return Optional.ofNullable(killer);
    }
References attackers, com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.getAmount(), and com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.isTimeout().
Member Data Documentation
attackers
final Map<Mob, DamageCounter> com.runehive.game.world.entity.combat.CombatDamage.attackers = new HashMap<>() private
The damages of players who have inflicted damage.
Definition at line 26 of file CombatDamage.java.
Referenced by add(), calculateProperKiller(), clear(), getNpcKiller(), and getPlayerKiller().
lastHit
Hit com.runehive.game.world.entity.combat.CombatDamage.lastHit
Definition at line 28 of file CombatDamage.java.
Referenced by add().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/CombatDamage.java