RuneHive-Game: com.runehive.content.collectionlog.CollectionLog Class Reference
com.runehive.content.collectionlog.CollectionLog Class Reference
Public Member Functions
CollectionLog ()
ArrayList< CollectionLogItem > getLog ()
Static Public Member Functions
static void checkItemDrop (Player player, int npcId, int itemId, int amount)
static boolean clickButton (Player player, int button)
static int getCounter (CollectionLog cl, CollectionLogData data)
static int getLogItemAmount (Player player, CollectionLogData data, int item)
static void increaseCounter (Player player, CollectionLogData data)
static void loadPage (Player player, CollectionLogPage page)
static void logItem (Player player, CollectionLogData data, int item, int amount)
static void onNpcKill (Player player, int npcId)
static void open (Player player)
static void selectLog (Player player, CollectionLogData selected, int slot)
static void selectLogButton (Player player, int slot)
static void sendButtons (Player player, CollectionLogPage page)
Static Public Attributes
static final int INTERFACE_ID = 44500
static final int ITEM_CONTAINER = 44521
static final int KC_ID = 44518
static final int NAME_ID = 44516
static final int OBTAINED_ID = 44517
Private Attributes
ArrayList< CollectionLogItem > log
Detailed Description
Definition at line 13 of file CollectionLog.java.
Constructor & Destructor Documentation
CollectionLog()
com.runehive.content.collectionlog.CollectionLog.CollectionLog ()
Definition at line 23 of file CollectionLog.java.
{
        log = new ArrayList<>();
    }
References log.
Referenced by getCounter().
Member Function Documentation
checkItemDrop()
void com.runehive.content.collectionlog.CollectionLog.checkItemDrop (Player player, int npcId, int itemId, int amount) static
Definition at line 164 of file CollectionLog.java.
{
        if (npcId < 1) {
            return;
        }
        for (CollectionLogData data : CollectionLogData.values()) {
            for(int npc : data.getNpcIds()) {
                if (npc == npcId) {
                    logItem(player, data, itemId, amount);
                    return;
                }
            }
        }
    }
References logItem().
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), and com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop().
clickButton()
boolean com.runehive.content.collectionlog.CollectionLog.clickButton (Player player, int button) static
Definition at line 128 of file CollectionLog.java.
{
        CollectionLogPage page = CollectionLogPage.forButton(button);
        if (page != null) {
            loadPage(player, page);
            return true;
        }
        if (button >= -21013 && button < -20915) {
            selectLogButton(player, (button - -21013) / 2);
            return true;
        }
        return false;
    }
References com.runehive.content.collectionlog.CollectionLogPage.forButton(), loadPage(), and selectLogButton().
getCounter()
int com.runehive.content.collectionlog.CollectionLog.getCounter (CollectionLog cl, CollectionLogData data) static
Definition at line 142 of file CollectionLog.java.
{
        for (CollectionLogItem i : cl.getLog()) {
            if (i.getData() == data) {
                return i.getCounter();
            }
        }
        return 0;
    }
References CollectionLog(), and getLog().
Referenced by selectLog().
getLog()
ArrayList< CollectionLogItem > com.runehive.content.collectionlog.CollectionLog.getLog ()
Definition at line 27 of file CollectionLog.java.
{
        return this.log;
    }
Referenced by getCounter(), getLogItemAmount(), increaseCounter(), logItem(), and sendButtons().
getLogItemAmount()
int com.runehive.content.collectionlog.CollectionLog.getLogItemAmount (Player player, CollectionLogData data, int item) static
Definition at line 151 of file CollectionLog.java.
{
        for (CollectionLogItem cli : player.getCollectionLog().getLog()) {
            if (cli.getData() == data) {
                for (int i = 0; i < cli.getItems().size(); ++i) {
                    if (cli.getItems().get(i).getId() == item) {
                        return cli.getItems().get(i).getAmount();
                    }
                }
            }
        }
        return 0;
    }
References com.runehive.game.world.entity.mob.player.Player.getCollectionLog(), and getLog().
Referenced by selectLog().
increaseCounter()
void com.runehive.content.collectionlog.CollectionLog.increaseCounter (Player player, CollectionLogData data) static
Definition at line 218 of file CollectionLog.java.
{
        for (CollectionLogItem cli : player.getCollectionLog().getLog()) {
            if (cli.getData() == data) {
                cli.setCounter(cli.getCounter() + 1);
                return;
            }
        }
        CollectionLogItem addLog = new CollectionLogItem(data);
        addLog.setCounter(1);
        player.getCollectionLog().getLog().add(addLog);
    }
References com.runehive.game.world.entity.mob.player.Player.getCollectionLog(), getLog(), and com.runehive.content.collectionlog.CollectionLogItem.setCounter().
Referenced by com.runehive.content.wintertodt.Wintertodt.award(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), and onNpcKill().
loadPage()
void com.runehive.content.collectionlog.CollectionLog.loadPage (Player player, CollectionLogPage page) static
Definition at line 45 of file CollectionLog.java.
{
        player.collectionLogPageOpen = page;
        player.send(new SendConfig(906, page.ordinal()));
        player.send(new SendConfig(907, 0));
        sendButtons(player, page);
        ArrayList<CollectionLogData> list = CollectionLogData.getPageList(player.collectionLogPageOpen);
        CollectionLogData selected = list.get(0);
        selectLog(player, selected, 0);
    }
References com.runehive.game.world.entity.mob.player.Player.collectionLogPageOpen, com.runehive.content.collectionlog.CollectionLogData.getPageList(), selectLog(), com.runehive.game.world.entity.mob.player.Player.send(), and sendButtons().
Referenced by clickButton(), and open().
logItem()
void com.runehive.content.collectionlog.CollectionLog.logItem (Player player, CollectionLogData data, int item, int amount) static
Definition at line 178 of file CollectionLog.java.
{
        boolean valid = false;
        for (int i : data.getItems()) {
            if (i == item) {
                valid = true;
                break;
            }
        }
        if (!valid) {
            return;
        }
        for (CollectionLogItem cli : player.getCollectionLog().getLog()) {
            if (cli.getData() == data) {
                cli.addItem(item, amount);
                player.send(new SendMessage("@red@An item was added to your collection log: " + amount + "x " + ItemDefinition.get(item).getName() + "!"));
                CollectionLogSaving.save(player);
                return;
            }
        }
        player.send(new SendMessage("@red@An item was added to your collection log: " + amount + "x " + ItemDefinition.get(item).getName() + "!"));
        CollectionLogItem addLog = new CollectionLogItem(data);
        addLog.addItem(item, amount);
        player.getCollectionLog().getLog().add(addLog);
        CollectionLogSaving.save(player);
    }
References com.runehive.content.collectionlog.CollectionLogItem.addItem(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.entity.mob.player.Player.getCollectionLog(), com.runehive.content.collectionlog.CollectionLogData.getItems(), getLog(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.content.collectionlog.CollectionLogSaving.save(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by checkItemDrop(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.pet.Pets.onObtain(), and com.runehive.content.activity.impl.warriorguild.WarriorGuild.pickupItem().
onNpcKill()
void com.runehive.content.collectionlog.CollectionLog.onNpcKill (Player player, int npcId) static
Definition at line 204 of file CollectionLog.java.
{
        if (npcId < 1) {
            return;
        }
        for (CollectionLogData data : CollectionLogData.values()) {
            for(int npc : data.getNpcIds()) {
                if (npc == npcId) {
                    increaseCounter(player, data);
                    return;
                }
            }
        }
    }
References increaseCounter().
Referenced by com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath().
open()
void com.runehive.content.collectionlog.CollectionLog.open (Player player) static
Definition at line 31 of file CollectionLog.java.
{
        player.interfaceManager.open(INTERFACE_ID);
        if (player.collectionLogPageOpen != null)
            loadPage(player, player.collectionLogPageOpen);
        else
            loadPage(player, CollectionLogPage.BOSSES);
        if (player.collectionLogView != null)
            selectLog(player, player.collectionLogView, -1);
        else
            selectLog(player, CollectionLogData.BARROWS, 0);
    }
References com.runehive.content.collectionlog.CollectionLogData.BARROWS, com.runehive.content.collectionlog.CollectionLogPage.BOSSES, com.runehive.game.world.entity.mob.player.Player.collectionLogPageOpen, com.runehive.game.world.entity.mob.player.Player.collectionLogView, INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, loadPage(), com.runehive.game.world.entity.mob.player.InterfaceManager.open(), and selectLog().
selectLog()
void com.runehive.content.collectionlog.CollectionLog.selectLog (Player player, CollectionLogData selected, int slot) static
Definition at line 77 of file CollectionLog.java.
{
        if(slot != -1)
            player.send(new SendConfig(907, slot));
        player.send(new SendString(selected.getName(), NAME_ID));
        ArrayList<Item> items = new ArrayList<>();
        int[] itemIds = selected.getItems();
        int total = itemIds == null ? 0 : itemIds.length;
        if (itemIds != null) {
            for (int i : itemIds) {
                items.add(new Item(i, getLogItemAmount(player, selected, i)));
            }
        }
        int obtained = 0;
        for (Item gi : items) {
            if (gi.getAmount() > 0) {
                obtained++;
            }
        }
        String colorCode = obtained >= total ? "65280" : obtained > 0 ? "FFFF00" : "FF0000";
        player.send(new SendString("Obtained: <col="+colorCode+">" + obtained + "/" + total + "</col>", OBTAINED_ID));
        String outcome = "";
        int counter = getCounter(player.getCollectionLog(), selected);
        if (selected.getType().equals(CollectionCategory.BOSSES))
            outcome = selected.getName() + " kills: <col=FFFFFF>" + counter + "</col>";
        else if (selected.getCounterText() != null)
            outcome = selected.getCounterText() + ": <col=FFFFFF>" + counter + "</col>";
        player.send(new SendString(outcome, KC_ID));
        player.send(new SendItemOnInterface(ITEM_CONTAINER, items.toArray(new Item[0])));
        player.collectionLogView = selected;
    }
References com.runehive.content.collectionlog.CollectionCategory.BOSSES, com.runehive.game.world.entity.mob.player.Player.getCollectionLog(), getCounter(), com.runehive.content.collectionlog.CollectionLogData.getCounterText(), com.runehive.content.collectionlog.CollectionLogData.getItems(), getLogItemAmount(), com.runehive.content.collectionlog.CollectionLogData.getName(), com.runehive.content.collectionlog.CollectionLogData.getType(), ITEM_CONTAINER, KC_ID, NAME_ID, OBTAINED_ID, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by loadPage(), open(), and selectLogButton().
selectLogButton()
void com.runehive.content.collectionlog.CollectionLog.selectLogButton (Player player, int slot) static
Definition at line 119 of file CollectionLog.java.
{
        ArrayList<CollectionLogData> list = CollectionLogData.getPageList(player.collectionLogPageOpen);
        if (slot > list.size() - 1) {
            return;
        }
        CollectionLogData selected = list.get(slot);
        selectLog(player, selected, slot);
    }
References com.runehive.game.world.entity.mob.player.Player.collectionLogPageOpen, com.runehive.content.collectionlog.CollectionLogData.getPageList(), and selectLog().
Referenced by clickButton().
sendButtons()
void com.runehive.content.collectionlog.CollectionLog.sendButtons (Player player, CollectionLogPage page) static
Definition at line 56 of file CollectionLog.java.
{
        ArrayList<CollectionLogData> list = CollectionLogData.getPageList(page);
        int index = 44524;
        for (int i = 0; i < list.size(); ++i, index += 2) {
            int color = 0;
            CollectionLogData selected = list.get(i);
            for (CollectionLogItem cli : player.getCollectionLog().getLog()) {
                if (cli.getData() == selected) {
                    if (cli.hasClaimed()) {
                        color = 1;
                    }
                }
            }
            player.send(new SendString(color > 0 ? "@gre@" + list.get(i).getName() : list.get(i).getName(), index));
        }
        for(int i = list.size(); i < 17; i++, index += 2)
            player.send(new SendString("", index));
    }
References com.runehive.game.world.entity.mob.player.Player.getCollectionLog(), getLog(), com.runehive.content.collectionlog.CollectionLogData.getPageList(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by loadPage().
Member Data Documentation
INTERFACE_ID
final int com.runehive.content.collectionlog.CollectionLog.INTERFACE_ID = 44500 static
Definition at line 15 of file CollectionLog.java.
Referenced by open().
ITEM_CONTAINER
final int com.runehive.content.collectionlog.CollectionLog.ITEM_CONTAINER = 44521 static
Definition at line 19 of file CollectionLog.java.
Referenced by selectLog().
KC_ID
final int com.runehive.content.collectionlog.CollectionLog.KC_ID = 44518 static
Definition at line 18 of file CollectionLog.java.
Referenced by selectLog().
log
ArrayList<CollectionLogItem> com.runehive.content.collectionlog.CollectionLog.log private
Definition at line 21 of file CollectionLog.java.
Referenced by CollectionLog().
NAME_ID
final int com.runehive.content.collectionlog.CollectionLog.NAME_ID = 44516 static
Definition at line 16 of file CollectionLog.java.
Referenced by selectLog().
OBTAINED_ID
final int com.runehive.content.collectionlog.CollectionLog.OBTAINED_ID = 44517 static
Definition at line 17 of file CollectionLog.java.
Referenced by selectLog().
The documentation for this class was generated from the following file:
java/com/runehive/content/collectionlog/CollectionLog.java