RuneHive-Game: com.runehive.content.skill.impl.slayer.SlayerOfferings Class Reference
com.runehive.content.skill.impl.slayer.SlayerOfferings Class Reference
Handles selling offering slayer rewards.
Classes
enum OfferingData
Static Public Member Functions
static void offer (Player player)
Static Private Member Functions
static void confirm (Player player)
Detailed Description
Handles selling offering slayer rewards.
Author
Daniel
Definition at line 14 of file SlayerOfferings.java.
Member Function Documentation
confirm()
void com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm (Player player) static private
Definition at line 40 of file SlayerOfferings.java.
{
        int points = 0;
        double experience = 0;
        for (Item item : player.inventory) {
            if (item == null)
                continue;
            OfferingData offering = OfferingData.forItem(item.getId());
            if (offering == null)
                continue;
            points += offering.getPoints();
            experience += offering.getExperience();
            player.inventory.remove(item);
        }
        player.message("Your offerings were accepted!");
        player.slayer.setPoints(player.slayer.getPoints() + points);
        player.skills.addExperience(Skill.SLAYER, experience);
        player.dialogueFactory.clear();
    }
References com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.content.dialogue.DialogueFactory.clear(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.forItem(), com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.getExperience(), com.runehive.game.world.items.Item.getId(), com.runehive.content.skill.impl.slayer.Slayer.getPoints(), com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.getPoints(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.content.skill.impl.slayer.Slayer.setPoints(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.skill.Skill.SLAYER, and com.runehive.game.world.entity.mob.player.Player.slayer.
Referenced by offer().
offer()
void com.runehive.content.skill.impl.slayer.SlayerOfferings.offer (Player player) static
Definition at line 16 of file SlayerOfferings.java.
{
        int points = 0;
        double experience = 0;
        for (Item item : player.inventory) {
            if (item == null)
                continue;
            OfferingData offering = OfferingData.forItem(item.getId());
            if (offering == null)
                continue;
            points += offering.getPoints();
            experience += offering.getExperience();
        }
        if (points == 0 && experience == 0) {
            player.dialogueFactory.sendNpcChat(6797, "You have no offerings for me!").execute();
            return;
        }
        player.dialogueFactory.sendNpcChat(6797, "I will give you " + points + " slayer points &", Utility.formatDigits(experience) + " experience for your offerings.", "Do you accept?");
        player.dialogueFactory.sendOption("Yes", () -> confirm(player),"No", () -> player.dialogueFactory.clear());
        player.dialogueFactory.execute();
    }
References com.runehive.content.dialogue.DialogueFactory.clear(), confirm(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.forItem(), com.runehive.util.Utility.formatDigits(), com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.getExperience(), com.runehive.game.world.items.Item.getId(), com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.getPoints(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), and com.runehive.content.dialogue.DialogueFactory.sendOption().
Referenced by com.runehive.content.dialogue.impl.NieveDialogue.sell().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/slayer/SlayerOfferings.java