RuneHive-Game: com.runehive.content.activity.impl.fightcaves.FightCaves Class Reference
com.runehive.content.activity.impl.fightcaves.FightCaves Class Reference
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
ActivityDeathType deathType ()
void finish ()
Finishes the activity.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
void update ()
The update method.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
Static Public Member Functions
static FightCaves create (Player player)
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Public Attributes
final Set< Npc > npcs = new HashSet<>()
A set of npcs in this activity.
Protected Member Functions
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Package Functions
void handleDeath (Mob dead)
Handles what happens to a mob when they die in the activity.
Private Member Functions
FightCaves (Player player, int instance)
Constructs a new FightCaves object for a player and an instance.
Private Attributes
boolean completed
The activity completed flag.
final FightCavesListener listener = new FightCavesListener(this)
The combat listener to add for all mobs.
final Player player
The player in the cave.
int tokkuls
The amount of tokkuls the player has acquired.
TzhaarData.WaveData wave = TzhaarData.WaveData.WAVE_1
The current wave of this activity.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Author
Daniel
Definition at line 30 of file FightCaves.java.
Constructor & Destructor Documentation
FightCaves()
com.runehive.content.activity.impl.fightcaves.FightCaves.FightCaves (Player player, int instance) private
Constructs a new FightCaves object for a player and an instance.
Definition at line 51 of file FightCaves.java.
{
        super(10, instance);
        this.player = player;
    }
References com.runehive.content.activity.Activity.instance, and player.
Referenced by create().
Member Function Documentation
canTeleport()
boolean com.runehive.content.activity.impl.fightcaves.FightCaves.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 182 of file FightCaves.java.
{
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.fightcaves.FightCaves.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 163 of file FightCaves.java.
{
        ActivityPanel.clear(player);
        if (!npcs.isEmpty())
            npcs.forEach(this::remove);
    }
References com.runehive.content.activity.panel.ActivityPanel.clear(), npcs, and player.
Referenced by finish(), and onRegionChange().
create()
FightCaves com.runehive.content.activity.impl.fightcaves.FightCaves.create (Player player) static
Definition at line 56 of file FightCaves.java.
{
        FightCaves minigame = new FightCaves(player, player.playerAssistant.instance());
        player.move(new Position(2398, 5083, player.getHeight()));
        ActivityPanel.update(player, -1, "Fight Caves", "Activity Completion:", "Good Luck, " + player.getName() + "!");
        player.dialogueFactory.sendNpcChat(2180, "Welcome to the Fight Caves, #name.", "There are a total of 15 waves, Tz-Tok Jad being the last.", "Use your activity panel (bottom left tab) for wave information.", "Good luck!").execute();
        minigame.add(player);
        minigame.resetCooldown();
        player.gameRecord.start();
        return minigame;
    }
References com.runehive.content.activity.Activity.add(), FightCaves(), player, com.runehive.content.activity.Activity.resetCooldown(), and com.runehive.content.activity.panel.ActivityPanel.update().
deathType()
ActivityDeathType com.runehive.content.activity.impl.fightcaves.FightCaves.deathType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 201 of file FightCaves.java.
{
        return ActivityDeathType.SAFE;
    }
References com.runehive.content.activity.ActivityDeathType.SAFE.
finish()
void com.runehive.content.activity.impl.fightcaves.FightCaves.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 140 of file FightCaves.java.
{
        cleanup();
        remove(player);
        if (completed) {
            long time = player.gameRecord.end(ActivityType.FIGHT_CAVES);
            player.dialogueFactory.sendNpcChat(2180, "You have defeated Tztok-Jad, I am most impressed!", "Please accept this gift, young thug.").execute();
            tokkuls += 3500;
            player.inventory.addOrDrop(new Item(6570));
            Pets.onReward(player, PetData.JAD);
            player.send(new SendMessage("You have completed the Fight Caves activity. Final time: @red@" + Utility.getTime(time) + "</col>."));
            player.activityLogger.add(ActivityLog.FIGHT_CAVES);
            return;
        }
        if (tokkuls <= 0)
            tokkuls = 1;
        player.inventory.addOrDrop(new Item(6529, tokkuls));
        player.dialogueFactory.sendNpcChat(2180, "Better luck next time!", "Take these tokkuls as a reward.").execute();
    }
References cleanup(), completed, com.runehive.content.activity.ActivityType.FIGHT_CAVES, com.runehive.content.ActivityLog.FIGHT_CAVES, com.runehive.util.Utility.getTime(), com.runehive.content.pet.PetData.JAD, com.runehive.content.pet.Pets.onReward(), player, and tokkuls.
Referenced by handleDeath(), onDeath(), onLogout(), and start().
getListener()
Optional<? extends ActivityListener<? extends Activity > > com.runehive.content.activity.impl.fightcaves.FightCaves.getListener ()
Gets an Optional of the ActivityListener for this activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 211 of file FightCaves.java.
{
        return Optional.of(listener);
    }
References listener.
getType()
ActivityType com.runehive.content.activity.impl.fightcaves.FightCaves.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 206 of file FightCaves.java.
{
        return ActivityType.FIGHT_CAVES;
    }
References com.runehive.content.activity.ActivityType.FIGHT_CAVES.
handleDeath()
void com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath (Mob dead) package
Handles what happens to a mob when they die in the activity.
Definition at line 68 of file FightCaves.java.
{
        if (dead.isPlayer() && dead.equals(player)) {
            finish();
            return;
        }
        if (dead.isNpc() && npcs.contains(dead)) {
            if (dead.id == 2191) {
                remove(dead);
                npcs.remove(dead);
                for (int index = 0; index < 2; index++) {
                    Position position = new Position(dead.getX() + (index == 0 ? -1 : + 1), dead.getY(), dead.getHeight());
                    Npc TzKet = new Npc(2192, position);
                    add(TzKet);
                    npcs.add(TzKet);
                    TzKet.getCombat().attack(player);
                }
                return;
            }
            npcs.remove(dead);
            remove(dead);
            tokkuls += Utility.random(100, 500);
            if (npcs.isEmpty()) {
                wave = TzhaarData.WaveData.getNext(wave.ordinal());
                if (wave == null) {
                    completed = true;
                    player.send(new SendMessage("You have finished the activity!"));
                } else {
                    player.send(new SendMessage("The next wave will commence soon."));
                }
                resetCooldown();
                return;
            }
        }
    }
References com.runehive.content.activity.Activity.add(), completed, com.runehive.game.world.entity.Entity.equals(), finish(), com.runehive.game.world.entity.mob.npc.Npc.getCombat(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.getNext(), com.runehive.game.world.entity.Entity.getX(), com.runehive.game.world.entity.Entity.getY(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), npcs, player, com.runehive.util.Utility.random(), com.runehive.content.activity.Activity.resetCooldown(), tokkuls, and wave.
onDeath()
void com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 128 of file FightCaves.java.
{
        if (mob.isNpc()) {
            World.schedule(new NpcDeath(mob.getNpc()));
        } else if (mob.isPlayer()) {
            mob.move(new Position(2438, 5169, 0));
            mob.animate(Animation.RESET, true);
            mob.graphic(Graphic.RESET, true);
            finish();
        }
    }
References com.runehive.game.world.entity.mob.Mob.animate(), finish(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, and com.runehive.game.world.World.schedule().
onLogout()
void com.runehive.content.activity.impl.fightcaves.FightCaves.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 195 of file FightCaves.java.
{
        finish();
        remove(player);
    }
References finish(), and player.
onRegionChange()
void com.runehive.content.activity.impl.fightcaves.FightCaves.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 187 of file FightCaves.java.
{
        if (!Area.inFightCaves(player)) {
            cleanup();
            remove(player);
        }
    }
References cleanup(), com.runehive.game.world.position.Area.inFightCaves(), and player.
start()
void com.runehive.content.activity.impl.fightcaves.FightCaves.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 105 of file FightCaves.java.
{
        if (wave == null) {
            finish();
            return;
        }
        if (player.locking.locked()) {
            return;
        }
        Position spawn = new Position(2398, 5083, player.getHeight());
        Position[] boundaries = Utility.getInnerBoundaries(spawn, 8, 8);
        for (int id : wave.getMonster()) {
            Npc npc = new Npc(id, RandomUtils.random(boundaries));
            npc.owner = player;
            add(npc);
            npcs.add(npc);
            npc.getCombat().attack(player);
        }
        pause();
    }
References com.runehive.content.activity.Activity.add(), finish(), com.runehive.game.world.entity.mob.npc.Npc.getCombat(), com.runehive.util.Utility.getInnerBoundaries(), npcs, com.runehive.content.activity.Activity.pause(), player, com.runehive.util.RandomUtils.random(), and wave.
update()
void com.runehive.content.activity.impl.fightcaves.FightCaves.update ()
The update method.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 170 of file FightCaves.java.
{
        if (wave == null) {
            ActivityPanel.update(player, 100, "Fight Caves", new Item(6570), "Congratulations, you have", "completed the Fight Caves", "activity!");
            return;
        }
        int progress = (int)Utility.getPercentageAmount(wave.ordinal() + 1, TzhaarData.WaveData.values().length);
        if (progress >= 100 && !completed)
            progress = 99;
        ActivityPanel.update(player, progress, "Fight Caves", new Item(6570), "</col>Wave: <col=FF5500>" + (wave.ordinal()  + 1) + "/" + (TzhaarData.WaveData.values().length), "</col>Monsters Left: <col=FF5500>" + npcs.size(), "</col>Tokkuls Gained: <col=FF5500>" + Utility.formatDigits(tokkuls));
    }
References completed, com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.getPercentageAmount(), npcs, player, tokkuls, com.runehive.content.activity.panel.ActivityPanel.update(), and wave.
Member Data Documentation
completed
boolean com.runehive.content.activity.impl.fightcaves.FightCaves.completed private
The activity completed flag.
Definition at line 36 of file FightCaves.java.
Referenced by finish(), handleDeath(), and update().
listener
final FightCavesListener com.runehive.content.activity.impl.fightcaves.FightCaves.listener = new FightCavesListener(this) private
The combat listener to add for all mobs.
Definition at line 48 of file FightCaves.java.
Referenced by getListener().
npcs
final Set<Npc> com.runehive.content.activity.impl.fightcaves.FightCaves.npcs = new HashSet<>()
A set of npcs in this activity.
Definition at line 42 of file FightCaves.java.
Referenced by cleanup(), handleDeath(), start(), and update().
player
final Player com.runehive.content.activity.impl.fightcaves.FightCaves.player private
The player in the cave.
Definition at line 33 of file FightCaves.java.
Referenced by canTeleport(), cleanup(), create(), FightCaves(), finish(), handleDeath(), onLogout(), onRegionChange(), start(), and update().
tokkuls
int com.runehive.content.activity.impl.fightcaves.FightCaves.tokkuls private
The amount of tokkuls the player has acquired.
Definition at line 39 of file FightCaves.java.
Referenced by finish(), handleDeath(), and update().
wave
TzhaarData.WaveData com.runehive.content.activity.impl.fightcaves.FightCaves.wave = TzhaarData.WaveData.WAVE_1 private
The current wave of this activity.
Definition at line 45 of file FightCaves.java.
Referenced by handleDeath(), start(), and update().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/fightcaves/FightCaves.java