RuneHive-Game: dev.advo.fs.dispatch.RequestDispatcher Class Reference
dev.advo.fs.dispatch.RequestDispatcher Class Reference
A class which dispatches requests to worker threads.
Static Public Member Functions
static void dispatch (Channel channel, OnDemandRequest request)
Dispatches an 'on-demand' request.
Static Package Functions
static ChannelRequest< OnDemandRequest > nextOnDemandRequest () throws InterruptedException
Gets the next 'on-demand' request from the queue, blocking if none are available.
Private Member Functions
RequestDispatcher ()
Default private constructor to prevent instantiation.
Static Private Attributes
static final int MAXIMUM_QUEUE_SIZE = 1024
The maximum size of a queue before requests are rejected.
static final BlockingQueue< ChannelRequest< OnDemandRequest > > onDemandQueue = new PriorityBlockingQueue<ChannelRequest<OnDemandRequest>>()
A queue for pending 'on-demand' requests.
Detailed Description
A class which dispatches requests to worker threads.
Author
Graham
Definition at line 14 of file RequestDispatcher.java.
Constructor & Destructor Documentation
RequestDispatcher()
dev.advo.fs.dispatch.RequestDispatcher.RequestDispatcher () private
Default private constructor to prevent instantiation.
Definition at line 51 of file RequestDispatcher.java.
{
    }
Member Function Documentation
dispatch()
void dev.advo.fs.dispatch.RequestDispatcher.dispatch (Channel channel, OnDemandRequest request) static
Dispatches an 'on-demand' request.
Parameters
channel The channel.
request The request.
Definition at line 41 of file RequestDispatcher.java.
{
//      if (onDemandQueue.size() >= MAXIMUM_QUEUE_SIZE) {
//          channel.close();
//      }
        onDemandQueue.add(new ChannelRequest<OnDemandRequest>(channel, request));
    }
References onDemandQueue.
Referenced by dev.advo.fs.net.FileServerHandler.messageReceived().
nextOnDemandRequest()
ChannelRequest< OnDemandRequest > dev.advo.fs.dispatch.RequestDispatcher.nextOnDemandRequest () throws InterruptedException static package
Gets the next 'on-demand' request from the queue, blocking if none are available.
Returns
The 'on-demand' request.
Exceptions
InterruptedException if the thread is interrupted.
Definition at line 32 of file RequestDispatcher.java.
{
        return onDemandQueue.take();
    }
References onDemandQueue.
Referenced by dev.advo.fs.dispatch.OnDemandRequestWorker.nextRequest().
Member Data Documentation
MAXIMUM_QUEUE_SIZE
final int dev.advo.fs.dispatch.RequestDispatcher.MAXIMUM_QUEUE_SIZE = 1024 static private
The maximum size of a queue before requests are rejected.
Definition at line 19 of file RequestDispatcher.java.
onDemandQueue
final BlockingQueue<ChannelRequest<OnDemandRequest> > dev.advo.fs.dispatch.RequestDispatcher.onDemandQueue = new PriorityBlockingQueue<ChannelRequest<OnDemandRequest>>() static private
A queue for pending 'on-demand' requests.
Definition at line 24 of file RequestDispatcher.java.
Referenced by dispatch(), and nextOnDemandRequest().
The documentation for this class was generated from the following file:
java/dev/advo/fs/dispatch/RequestDispatcher.java