RuneHive-Game: com.runehive.fs.cache.decoder.AnimationDefinitionDecoder Class Reference
com.runehive.fs.cache.decoder.AnimationDefinitionDecoder Class Reference
A class which parses animation definitions.
Public Member Functions
AnimationDefinitionDecoder (final FileSystem fs)
void run ()
Static Public Attributes
static final Int2ObjectMap< AnimationDefinition > definitions = new Int2ObjectOpenHashMap<>()
Private Attributes
final FileSystem fs
The IndexedFileSystem.
Static Private Attributes
static final Logger LOGGER = LogManager.getLogger(AnimationDefinitionDecoder.class)
The logger to log process output.
Detailed Description
A class which parses animation definitions.
Definition at line 15 of file AnimationDefinitionDecoder.java.
Constructor & Destructor Documentation
AnimationDefinitionDecoder()
com.runehive.fs.cache.decoder.AnimationDefinitionDecoder.AnimationDefinitionDecoder (final FileSystem fs)
Definition at line 25 of file AnimationDefinitionDecoder.java.
{
        this.fs = fs;
    }
References fs.
Member Function Documentation
run()
void com.runehive.fs.cache.decoder.AnimationDefinitionDecoder.run ()
Definition at line 30 of file AnimationDefinitionDecoder.java.
                      {
        LOGGER.info("Loading animation definitions.");
        final Archive archive = fs.getArchive(FileSystem.CONFIG_ARCHIVE);
        final ByteBuf buffer = Unpooled.wrappedBuffer(archive.getData("seq.dat"));
        try {
            final int highestFileId = buffer.readUnsignedShort();
            for (int i = 0; i <= highestFileId; i++) {
                final int id = buffer.readUnsignedShort();
                if (id == 65535) break;
                final int length = buffer.readUnsignedShort();
                final ByteBuf animBuffer = buffer.readBytes(length);
                try {
                    final AnimationDefinition definition = new AnimationDefinition(id);
                    definition.decode(animBuffer);
                    definitions.put(id, definition);
                } finally {
                    animBuffer.release();
                }
                if (id >= highestFileId) break;
            }
        } finally {
            buffer.release();
        }
        LOGGER.info("Loaded " + definitions.size() + " animation definitions.");
    }
References com.runehive.fs.cache.FileSystem.CONFIG_ARCHIVE, com.runehive.fs.cache.decoder.AnimationDefinition.decode(), definitions, fs, and LOGGER.
Referenced by com.runehive.RuneHive.processSequentialStartupTasks().
Member Data Documentation
definitions
final Int2ObjectMap<AnimationDefinition> com.runehive.fs.cache.decoder.AnimationDefinitionDecoder.definitions = new Int2ObjectOpenHashMap<>() static
Definition at line 20 of file AnimationDefinitionDecoder.java.
Referenced by com.runehive.game.world.entity.mob.Mob.animate(), and run().
fs
final FileSystem com.runehive.fs.cache.decoder.AnimationDefinitionDecoder.fs private
The IndexedFileSystem.
Definition at line 23 of file AnimationDefinitionDecoder.java.
Referenced by AnimationDefinitionDecoder(), and run().
LOGGER
final Logger com.runehive.fs.cache.decoder.AnimationDefinitionDecoder.LOGGER = LogManager.getLogger(AnimationDefinitionDecoder.class) static private
The logger to log process output.
Definition at line 18 of file AnimationDefinitionDecoder.java.
Referenced by run().
The documentation for this class was generated from the following file:
java/com/runehive/fs/cache/decoder/AnimationDefinitionDecoder.java