RuneHive-Game: com.runehive.content.itemaction.impl.ThammaronsSceptre Class Reference
com.runehive.content.itemaction.impl.ThammaronsSceptre Class Reference
Public Member Functions
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
String message (Item item)
The message of the action.
String toString ()
Static Public Attributes
static final short ETHER_ID = 21820
static final short THAMMARONS_SCEPTRE_CHARGED_ID = 22555
static final short THAMMARONS_SCEPTRE_UNCHARGED_ID = 22552
Private Member Functions
void charge (Player player, int amount)
void check (Player player)
Detailed Description
Definition at line 10 of file ThammaronsSceptre.java.
Member Function Documentation
charge()
void com.runehive.content.itemaction.impl.ThammaronsSceptre.charge (Player player, int amount) private
Definition at line 95 of file ThammaronsSceptre.java.
{
        if (amount > player.inventory.computeAmountForId(ETHER_ID)) {
            amount = player.inventory.computeAmountForId(ETHER_ID);
        }
        if (amount > 0) {
            player.inventory.remove(ETHER_ID, amount);
            player.inventory.refresh();
            player.thammoranSceptreCharges += amount;
            player.message("You added " + amount + " charges to your "+name()+"");
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), ETHER_ID, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), and com.runehive.game.world.items.containers.ItemContainer.remove().
Referenced by itemOnItem().
check()
void com.runehive.content.itemaction.impl.ThammaronsSceptre.check (Player player) private
Definition at line 91 of file ThammaronsSceptre.java.
{
        player.message("You have " + Utility.formatDigits(player.thammoranSceptreCharges) + " charges in your "+name()+".");
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.Player.message(), name(), and com.runehive.game.world.entity.mob.player.Player.thammoranSceptreCharges.
Referenced by equipment(), and inventory().
drop()
boolean com.runehive.content.itemaction.impl.ThammaronsSceptre.drop (Player player, Item item)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 76 of file ThammaronsSceptre.java.
{
        if (item.getId() != THAMMARONS_SCEPTRE_CHARGED_ID) {
            return false;
        }
        player.inventory.remove(THAMMARONS_SCEPTRE_CHARGED_ID);
        player.inventory.add(THAMMARONS_SCEPTRE_UNCHARGED_ID, 1);
        player.inventory.add(ETHER_ID, 1000 + player.thammoranSceptreCharges);
        player.thammoranSceptreCharges = 0;
        player.message("You uncharge your "+name()+".");
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), ETHER_ID, com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.ItemContainer.remove(), THAMMARONS_SCEPTRE_CHARGED_ID, THAMMARONS_SCEPTRE_UNCHARGED_ID, and com.runehive.game.world.entity.mob.player.Player.thammoranSceptreCharges.
equipment()
boolean com.runehive.content.itemaction.impl.ThammaronsSceptre.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 64 of file ThammaronsSceptre.java.
{
        if (item.getId() != THAMMARONS_SCEPTRE_CHARGED_ID) {
            return false;
        }
        if (opcode == 1) {
            check(player);
            return true;
        }
        return true;
    }
References check(), com.runehive.game.world.items.Item.getId(), and THAMMARONS_SCEPTRE_CHARGED_ID.
inventory()
boolean com.runehive.content.itemaction.impl.ThammaronsSceptre.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 50 of file ThammaronsSceptre.java.
{
        if (item.getId() != THAMMARONS_SCEPTRE_CHARGED_ID) {
            return false;
        }
        if (opcode == 2) {
            check(player);
            return true;
        }
        return false;
    }
References check(), com.runehive.game.world.items.Item.getId(), and THAMMARONS_SCEPTRE_CHARGED_ID.
itemOnItem()
boolean com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 22 of file ThammaronsSceptre.java.
{
        System.out.println("?????");
        if ((first.getId() != THAMMARONS_SCEPTRE_UNCHARGED_ID && second.getId() != THAMMARONS_SCEPTRE_UNCHARGED_ID) && (first.getId() != THAMMARONS_SCEPTRE_CHARGED_ID && second.getId() != THAMMARONS_SCEPTRE_CHARGED_ID)) {
            System.out.println("dfgdfgdfg");
            return false;
        }
        if(first.getId() == ETHER_ID || second.getId() == ETHER_ID) {
            if (first.getId() == THAMMARONS_SCEPTRE_UNCHARGED_ID || second.getId() == THAMMARONS_SCEPTRE_UNCHARGED_ID) {
                if(!player.inventory.contains(ETHER_ID, 1000)) {
                    player.message("You need at least 1000 "+ ItemDefinition.get(ETHER_ID).getName() +" to charge the "+name()+".");
                    return true;
                }
                player.inventory.remove(ETHER_ID, 1000);
                player.inventory.remove(THAMMARONS_SCEPTRE_UNCHARGED_ID);
                player.inventory.add(THAMMARONS_SCEPTRE_CHARGED_ID, 1);
                player.inventory.refresh();
            } else {
                System.out.println("Recharge craws bow");
                player.send(new SendInputAmount("How many charges would you like add? (0-"+player.inventory.computeAmountForId(ETHER_ID)+")", 10, input -> charge(player, Integer.parseInt(input))));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), charge(), com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), ETHER_ID, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), THAMMARONS_SCEPTRE_CHARGED_ID, and THAMMARONS_SCEPTRE_UNCHARGED_ID.
name()
String com.runehive.content.itemaction.impl.ThammaronsSceptre.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 17 of file ThammaronsSceptre.java.
{
        return "Thammaron's sceptre";
    }
Referenced by charge(), check(), drop(), and itemOnItem().
Member Data Documentation
ETHER_ID
final short com.runehive.content.itemaction.impl.ThammaronsSceptre.ETHER_ID = 21820 static
Definition at line 14 of file ThammaronsSceptre.java.
Referenced by charge(), drop(), and itemOnItem().
THAMMARONS_SCEPTRE_CHARGED_ID
final short com.runehive.content.itemaction.impl.ThammaronsSceptre.THAMMARONS_SCEPTRE_CHARGED_ID = 22555 static
Definition at line 13 of file ThammaronsSceptre.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.itemaction.ItemActionRepository.declare(), drop(), equipment(), inventory(), itemOnItem(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start().
THAMMARONS_SCEPTRE_UNCHARGED_ID
final short com.runehive.content.itemaction.impl.ThammaronsSceptre.THAMMARONS_SCEPTRE_UNCHARGED_ID = 22552 static
Definition at line 12 of file ThammaronsSceptre.java.
Referenced by com.runehive.content.itemaction.ItemActionRepository.declare(), drop(), and itemOnItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/ThammaronsSceptre.java