RuneHive-Game: com.runehive.game.event.impl.log.LogEvent Class Reference
com.runehive.game.event.impl.log.LogEvent Class Reference abstract
Public Member Functions
void log ()
abstract void onLog () throws Exception
Protected Attributes
final LocalDateTime dateTime = LocalDateTime.now()
Static Private Attributes
static final Logger logger = LogManager.getLogger(LogEvent.class)
Detailed Description
Definition at line 10 of file LogEvent.java.
Member Function Documentation
log()
void com.runehive.game.event.impl.log.LogEvent.log ()
Definition at line 15 of file LogEvent.java.
                      {
        if (!Config.FORUM_INTEGRATION || !Config.LOG_PLAYER) {
            return;
        }
        Thread.startVirtualThread(() -> {
            try {
                onLog();
            } catch (Exception ex) {
                logger.error(String.format("Error logging %s", this.getClass().getSimpleName()), ex);
            }
        });
    }
References com.runehive.Config.FORUM_INTEGRATION, com.runehive.Config.LOG_PLAYER, logger, and onLog().
Referenced by com.runehive.game.event.listener.WorldEventListener.accept().
onLog()
abstract void com.runehive.game.event.impl.log.LogEvent.onLog () throws Exception abstract
Reimplemented in com.runehive.game.event.impl.log.ChatLogEvent, com.runehive.game.event.impl.log.CommandLogEvent, com.runehive.game.event.impl.log.DropItemLogEvent, com.runehive.game.event.impl.log.PickupItemLogEvent, com.runehive.game.event.impl.log.PrivateMessageChatLogEvent, and com.runehive.game.event.impl.log.TradeLogEvent.
Referenced by log().
Member Data Documentation
dateTime
final LocalDateTime com.runehive.game.event.impl.log.LogEvent.dateTime = LocalDateTime.now() protected
Definition at line 13 of file LogEvent.java.
Referenced by com.runehive.game.event.impl.log.ChatLogEvent.onLog(), com.runehive.game.event.impl.log.CommandLogEvent.onLog(), com.runehive.game.event.impl.log.DropItemLogEvent.onLog(), com.runehive.game.event.impl.log.PickupItemLogEvent.onLog(), com.runehive.game.event.impl.log.PrivateMessageChatLogEvent.onLog(), and com.runehive.game.event.impl.log.TradeLogEvent.onLog().
logger
final Logger com.runehive.game.event.impl.log.LogEvent.logger = LogManager.getLogger(LogEvent.class) static private
Definition at line 12 of file LogEvent.java.
Referenced by log().
The documentation for this class was generated from the following file:
java/com/runehive/game/event/impl/log/LogEvent.java