RuneHive-Game: com.runehive.net.packet.GamePacket Class Reference
com.runehive.net.packet.GamePacket Class Reference
Represents a single game packet.
Public Member Functions
GamePacket (final int opcode, final PacketType header, final ByteBuf payload)
Creates a GamePacket.
PacketType getHeader ()
Gets the type.
int getOpcode ()
Gets the opcode.
ByteBuf getPayload ()
Gets the payload.
String getRS2String ()
Reads a RuneScape string.
int getSize ()
Gets the size of this payload.
int readByte ()
Reads a STANDARD signed byte from the payload.
int readByte (boolean signed)
Reads a STANDARD byte from the payload.
int readByte (boolean signed, ByteModification mod)
Reads a single byte from the payload.
int readByte (ByteModification mod)
Reads a signed byte from the payload.
byte[] readBytes (int amount)
Reads the amount of bytes into the array, starting at the current position.
byte[] readBytes (int amount, ByteModification mod)
Reads a series of bytes from a buffer.
byte[] readBytesReverse (int amount)
Reads a series of bytes in reverse.
byte[] readBytesReverse (int amount, ByteModification mod)
Reads a series of bytes in reverse.
int readInt ()
Reads a STANDARD signed integer value from the payload in BIG order.
int readInt (boolean signed)
Reads a STANDARD integer value from the payload in BIG order.
int readInt (boolean signed, ByteModification mod)
Reads an integer value from the payload in BIG order.
int readInt (boolean signed, ByteOrder order)
Reads a STANDARD integer value from the payload.
int readInt (boolean signed, ByteOrder order, ByteModification mod)
Reads an integer value from the payload.
int readInt (ByteModification mod)
Reads a signed integer value from the payload in ByteOrder BIG order.
long readLong ()
Reads a STANDARD signed long value from the payload in BIG order.
long readLong (boolean signed)
Reads a STANDARD long value from the payload in BIG order.
long readLong (boolean signed, ByteModification mod)
Reads a long value from the payload in BIG order.
long readLong (boolean signed, ByteOrder order)
Reads a STANDARD long value from the payload.
long readLong (boolean signed, ByteOrder order, ByteModification mod)
Reads a long value from the payload.
long readLong (ByteModification mod)
Reads a signed long value from the payload in BIG order.
int readShort ()
Reads a STANDARD signed short value from the payload in BIG order.
int readShort (boolean signed)
Reads a STANDARD short value from the payload in BIG order.
int readShort (boolean signed, ByteModification mod)
Reads a short value from the payload in BIG order.
int readShort (boolean signed, ByteOrder order)
Reads a STANDARD short value from the payload.
int readShort (boolean signed, ByteOrder order, ByteModification mod)
Reads a short value from the payload.
int readShort (ByteModification mod)
Reads a signed short value from the payload BIG order.
int readShort (ByteOrder order)
Reads a STANDARD signed short value from the payload.
int readShort (ByteOrder order, ByteModification mod)
Reads a signed short value from the payload.
String toString ()
Private Attributes
final PacketType header
The header for this packet.
final int opcode
The opcode for this packet.
final ByteBuf payload
The buffer that contains the data for this packet.
final int size
The size of this packet.
Detailed Description
Represents a single game packet.
Author
nshusa
Definition at line 13 of file GamePacket.java.
Constructor & Destructor Documentation
GamePacket()
com.runehive.net.packet.GamePacket.GamePacket (final int opcode, final PacketType header, final ByteBuf payload)
Creates a GamePacket.
Parameters
opcode The opcode.
header The header.
payload The payload.
Definition at line 45 of file GamePacket.java.
{
        super(payload);
        this.opcode = opcode;
        this.header = header;
        this.payload = payload;
        this.size = payload.readableBytes();
    }
References header, opcode, and payload.
Member Function Documentation
getHeader()
PacketType com.runehive.net.packet.GamePacket.getHeader ()
Gets the type.
Returns
The type.
Definition at line 77 of file GamePacket.java.
{
        return header;
    }
References header.
getOpcode()
int com.runehive.net.packet.GamePacket.getOpcode ()
Gets the opcode.
Returns
The opcode.
Definition at line 68 of file GamePacket.java.
{
        return opcode;
    }
References opcode.
getPayload()
ByteBuf com.runehive.net.packet.GamePacket.getPayload ()
Gets the payload.
Returns
The payload.
Definition at line 86 of file GamePacket.java.
{
        return payload;
    }
References payload.
getRS2String()
String com.runehive.net.packet.GamePacket.getRS2String ()
Reads a RuneScape string.
Returns
The string.
Definition at line 600 of file GamePacket.java.
{
        final StringBuilder bldr = new StringBuilder();
        byte b;
        while (payload.isReadable() && (b = payload.readByte()) != 10) {
            bldr.append((char) b);
        }
        return bldr.toString();
    }
References payload.
getSize()
int com.runehive.net.packet.GamePacket.getSize ()
Gets the size of this payload.
Returns
The amount of readable bytes.
Definition at line 59 of file GamePacket.java.
{
        return size;
    }
References size.
readByte() [1/4]
int com.runehive.net.packet.GamePacket.readByte ()
Reads a STANDARD signed byte from the payload.
Returns
The byte.
Definition at line 95 of file GamePacket.java.
{
        return payload.readByte();
    }
References payload.
Referenced by readByte(), readByte(), readBytes(), readInt(), readLong(), and readShort().
readByte() [2/4]
int com.runehive.net.packet.GamePacket.readByte (boolean signed)
Reads a STANDARD byte from the payload.
Parameters
signed The flag that denotes this value is signed.
Returns
The byte.
Definition at line 107 of file GamePacket.java.
{
        return readByte(signed, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteModification.NONE, and readByte().
readByte() [3/4]
int com.runehive.net.packet.GamePacket.readByte (boolean signed , ByteModification mod)
Reads a single byte from the payload.
Parameters
signed The flag that denotes this value is signed.
mod The modification performed on this value.
Returns
The byte.
Definition at line 134 of file GamePacket.java.
{
        int value = payload.readByte();
        switch (mod) {
        case ADD:
            value = value - 128;
            break;
        case SUB:
            value = 128 - value;
            break;
        case NEG:
            value = -value;
            break;
        case NONE:
            break;
        }
        return signed ? value : value & 0xFF;
    }
References payload.
readByte() [4/4]
int com.runehive.net.packet.GamePacket.readByte (ByteModification mod)
Reads a signed byte from the payload.
Parameters
mod The modification performed on this value.
Returns
The signed byte.
Definition at line 119 of file GamePacket.java.
{
        return readByte(true, mod);
    }
References readByte().
readBytes() [1/2]
byte[] com.runehive.net.packet.GamePacket.readBytes (int amount)
Reads the amount of bytes into the array, starting at the current position.
Parameters
amount the amount to read.
Returns
a buffer filled with the data.
Definition at line 518 of file GamePacket.java.
{
        return readBytes(amount, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteModification.NONE, and readBytes().
Referenced by readBytes().
readBytes() [2/2]
byte[] com.runehive.net.packet.GamePacket.readBytes (int amount, ByteModification mod)
Reads a series of bytes from a buffer.
Parameters
amount The amount of bytes to read.
mod The modifications performed on the bytes values.
Returns
The bytes that where read.
Definition at line 533 of file GamePacket.java.
{
        byte[] data = new byte[amount];
        for (int i = 0; i < amount; i++) {
            data[i] = (byte) readByte(mod);
        }
        return data;
    }
References readByte().
readBytesReverse() [1/2]
byte[] com.runehive.net.packet.GamePacket.readBytesReverse (int amount)
Reads a series of bytes in reverse.
Parameters
amount The amount of bytes to read.
Returns
The bytes in reverse.
Definition at line 549 of file GamePacket.java.
{
        return readBytesReverse(amount, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteModification.NONE, and readBytesReverse().
Referenced by readBytesReverse().
readBytesReverse() [2/2]
byte[] com.runehive.net.packet.GamePacket.readBytesReverse (int amount, ByteModification mod)
Reads a series of bytes in reverse.
Parameters
amount The amount of bytes to read.
mod The modification performed on these bytes.
Returns
The bytes in reverse.
Definition at line 564 of file GamePacket.java.
{
        byte[] data = new byte[amount];
        int dataPosition = 0;
        for (int index = payload.readerIndex() + amount - 1; index >= payload.readerIndex(); index--) {
            int value = payload.getByte(index);
            switch (mod) {
            case ADD:
                value -= 128;
                break;
            case NEG:
                value = -value;
                break;
            case SUB:
                value = 128 - value;
                break;
            case NONE:
                break;
            }
            data[dataPosition++] = (byte) value;
        }
        return data;
    }
References payload.
readInt() [1/6]
int com.runehive.net.packet.GamePacket.readInt ()
Reads a STANDARD signed integer value from the payload in BIG order.
Returns
The integer value.
Definition at line 290 of file GamePacket.java.
{
        return readInt(true, ByteOrder.BE, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteOrder.BE, com.runehive.net.codec.ByteModification.NONE, and readInt().
Referenced by readInt(), readInt(), readInt(), readInt(), and readInt().
readInt() [2/6]
int com.runehive.net.packet.GamePacket.readInt (boolean signed)
Reads a STANDARD integer value from the payload in BIG order.
Parameters
signed The flag that denotes this value is signed.
Returns
The integer value.
Definition at line 303 of file GamePacket.java.
{
        return readInt(signed, ByteOrder.BE, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteOrder.BE, com.runehive.net.codec.ByteModification.NONE, and readInt().
readInt() [3/6]
int com.runehive.net.packet.GamePacket.readInt (boolean signed , ByteModification mod)
Reads an integer value from the payload in BIG order.
Parameters
signed The flag that denotes this value is signed.
mod The modifications performed on this value.
Returns
The integer value.
Definition at line 331 of file GamePacket.java.
{
        return readInt(signed, ByteOrder.BE, mod);
    }
References com.runehive.net.codec.ByteOrder.BE, and readInt().
readInt() [4/6]
int com.runehive.net.packet.GamePacket.readInt (boolean signed , ByteOrder order)
Reads a STANDARD integer value from the payload.
Parameters
signed The flag that denotes this value is signed.
order The order in which the value is written.
Returns
The integer value.
Definition at line 346 of file GamePacket.java.
{
        return readInt(signed, order, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteModification.NONE, and readInt().
readInt() [5/6]
int com.runehive.net.packet.GamePacket.readInt (boolean signed , ByteOrder order, ByteModification mod)
Reads an integer value from the payload.
Parameters
signed The flag that denotes this value is signed.
order The order in which the value is written.
mod The modifications performed on this value.
Returns
The integer value.
Definition at line 364 of file GamePacket.java.
{
        long value = 0;
        switch (order) {
        case BE:
            value |= readByte(false) << 24;
            value |= readByte(false) << 16;
            value |= readByte(false) << 8;
            value |= readByte(false, mod);
            break;
        case ME:
            value |= readByte(false) << 8;
            value |= readByte(false, mod);
            value |= readByte(false) << 24;
            value |= readByte(false) << 16;
            break;
        case IME:
            value |= readByte(false) << 16;
            value |= readByte(false) << 24;
            value |= readByte(false, mod);
            value |= readByte(false) << 8;
            break;
        case LE:
            value |= readByte(false, mod);
            value |= readByte(false) << 8;
            value |= readByte(false) << 16;
            value |= readByte(false) << 24;
            break;
        }
        return (int) (signed ? value : value & 0xFFFFFFFFL);
    }
References readByte().
readInt() [6/6]
int com.runehive.net.packet.GamePacket.readInt (ByteModification mod)
Reads a signed integer value from the payload in ByteOrder BIG order.
Parameters
mod The modifications performed on this value.
Returns
The integer value.
Definition at line 316 of file GamePacket.java.
{
        return readInt(true, ByteOrder.BE, mod);
    }
References com.runehive.net.codec.ByteOrder.BE, and readInt().
readLong() [1/6]
long com.runehive.net.packet.GamePacket.readLong ()
Reads a STANDARD signed long value from the payload in BIG order.
Returns
The long value.
Definition at line 404 of file GamePacket.java.
{
        return readLong(true, ByteOrder.BE, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteOrder.BE, com.runehive.net.codec.ByteModification.NONE, and readLong().
Referenced by readLong(), readLong(), readLong(), readLong(), and readLong().
readLong() [2/6]
long com.runehive.net.packet.GamePacket.readLong (boolean signed)
Reads a STANDARD long value from the payload in BIG order.
Parameters
signed The flag that denotes this value is signed.
Returns
The long value.
Definition at line 417 of file GamePacket.java.
{
        return readLong(signed, ByteOrder.BE, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteOrder.BE, com.runehive.net.codec.ByteModification.NONE, and readLong().
readLong() [3/6]
long com.runehive.net.packet.GamePacket.readLong (boolean signed , ByteModification mod)
Reads a long value from the payload in BIG order.
Parameters
signed The flag that denotes this value is signed.
mod The modifications performed on this value.
Returns
The long value.
Definition at line 444 of file GamePacket.java.
{
        return readLong(signed, ByteOrder.BE, mod);
    }
References com.runehive.net.codec.ByteOrder.BE, and readLong().
readLong() [4/6]
long com.runehive.net.packet.GamePacket.readLong (boolean signed , ByteOrder order)
Reads a STANDARD long value from the payload.
Parameters
signed The flag that denotes this value is signed.
order The order in which the value is written.
Returns
The long value.
Definition at line 459 of file GamePacket.java.
{
        return readLong(signed, order, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteModification.NONE, and readLong().
readLong() [5/6]
long com.runehive.net.packet.GamePacket.readLong (boolean signed , ByteOrder order, ByteModification mod)
Reads a long value from the payload.
Parameters
signed The flag that denotes this value is signed.
order The order in which the value is written.
mod The modifications performed on this value.
Returns
The long value.
Definition at line 477 of file GamePacket.java.
{
        long value = 0;
        switch (order) {
        case BE:
            value |= (long) readByte(false) << 56L;
            value |= (long) readByte(false) << 48L;
            value |= (long) readByte(false) << 40L;
            value |= (long) readByte(false) << 32L;
            value |= (long) readByte(false) << 24L;
            value |= (long) readByte(false) << 16L;
            value |= (long) readByte(false) << 8L;
            value |= readByte(false, mod);
            break;
        case ME:
        case IME:
            throw new UnsupportedOperationException("Middle and " + "inverse-middle value types not supported!");
        case LE:
            value |= readByte(false, mod);
            value |= (long) readByte(false) << 8L;
            value |= (long) readByte(false) << 16L;
            value |= (long) readByte(false) << 24L;
            value |= (long) readByte(false) << 32L;
            value |= (long) readByte(false) << 40L;
            value |= (long) readByte(false) << 48L;
            value |= (long) readByte(false) << 56L;
            break;
        }
        return signed ? value : value & 0xFFFFFFFFL;
    }
References readByte().
readLong() [6/6]
long com.runehive.net.packet.GamePacket.readLong (ByteModification mod)
Reads a signed long value from the payload in BIG order.
Parameters
mod The modifications performed on this value.
Returns
The long value.
Definition at line 429 of file GamePacket.java.
{
        return readLong(true, ByteOrder.BE, mod);
    }
References com.runehive.net.codec.ByteOrder.BE, and readLong().
readShort() [1/8]
int com.runehive.net.packet.GamePacket.readShort ()
Reads a STANDARD signed short value from the payload in BIG order.
Returns
The standard signed short value.
Definition at line 162 of file GamePacket.java.
{
        return payload.readShort();
    }
References payload.
Referenced by readShort(), readShort(), readShort(), readShort(), readShort(), and readShort().
readShort() [2/8]
int com.runehive.net.packet.GamePacket.readShort (boolean signed)
Reads a STANDARD short value from the payload in BIG order.
Parameters
signed The flag that denotes this value is signed.
Returns
The standard short value.
Definition at line 175 of file GamePacket.java.
{
        return readShort(signed, ByteOrder.BE, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteOrder.BE, com.runehive.net.codec.ByteModification.NONE, and readShort().
readShort() [3/8]
int com.runehive.net.packet.GamePacket.readShort (boolean signed , ByteModification mod)
Reads a short value from the payload in BIG order.
Parameters
signed The flag that denotes this value is signed.
mod The modifications performed on this value.
Returns
The short value.
Definition at line 244 of file GamePacket.java.
{
        return readShort(signed, ByteOrder.BE, mod);
    }
References com.runehive.net.codec.ByteOrder.BE, and readShort().
readShort() [4/8]
int com.runehive.net.packet.GamePacket.readShort (boolean signed , ByteOrder order)
Reads a STANDARD short value from the payload.
Parameters
signed The flag that denotes this value is signed.
order The order in which this value is written.
Returns
The standard short value.
Definition at line 202 of file GamePacket.java.
{
        return readShort(signed, order, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteModification.NONE, and readShort().
readShort() [5/8]
int com.runehive.net.packet.GamePacket.readShort (boolean signed , ByteOrder order, ByteModification mod)
Reads a short value from the payload.
Parameters
signed The flag that denotes this value is signed.
order The order in which the value is written.
mod The modifications performed on this value.
Returns
The short value.
Definition at line 262 of file GamePacket.java.
{
        int value = 0;
        switch (order) {
        case BE:
            value |= readByte(false) << 8;
            value |= readByte(false, mod);
            break;
        case IME:
            throw new UnsupportedOperationException("Inverse-middle-endian short is impossible!");
        case ME:
            throw new UnsupportedOperationException("Middle-endian short " + "is impossible!");
        case LE:
            value |= readByte(false, mod);
            value |= readByte(false) << 8;
            break;
        }
        return signed ? value : value & 0xFFFF;
    }
References readByte().
readShort() [6/8]
int com.runehive.net.packet.GamePacket.readShort (ByteModification mod)
Reads a signed short value from the payload BIG order.
Parameters
mod The modifications performed on this value.
Returns
The short value.
Definition at line 229 of file GamePacket.java.
{
        return readShort(true, ByteOrder.BE, mod);
    }
References com.runehive.net.codec.ByteOrder.BE, and readShort().
readShort() [7/8]
int com.runehive.net.packet.GamePacket.readShort (ByteOrder order)
Reads a STANDARD signed short value from the payload.
Parameters
order The order in which this value is written.
Returns
The signed standard short value.
Definition at line 187 of file GamePacket.java.
{
        return readShort(true, order, ByteModification.NONE);
    }
References com.runehive.net.codec.ByteModification.NONE, and readShort().
readShort() [8/8]
int com.runehive.net.packet.GamePacket.readShort (ByteOrder order, ByteModification mod)
Reads a signed short value from the payload.
Parameters
order The order in which this value is written.
mod The modifications performed on this value.
Returns
The short value.
Definition at line 217 of file GamePacket.java.
{
        return readShort(true, order, mod);
    }
References readShort().
toString()
String com.runehive.net.packet.GamePacket.toString ()
Definition at line 610 of file GamePacket.java.
{
        return String.format("[opcode=%d], [type=%s], [size= %d]", opcode, header.name(), size);
    }
References header, opcode, and size.
Member Data Documentation
header
final PacketType com.runehive.net.packet.GamePacket.header private
The header for this packet.
Definition at line 23 of file GamePacket.java.
Referenced by GamePacket(), getHeader(), and toString().
opcode
final int com.runehive.net.packet.GamePacket.opcode private
The opcode for this packet.
Definition at line 18 of file GamePacket.java.
Referenced by GamePacket(), getOpcode(), and toString().
payload
final ByteBuf com.runehive.net.packet.GamePacket.payload private
The buffer that contains the data for this packet.
Definition at line 28 of file GamePacket.java.
Referenced by GamePacket(), getPayload(), getRS2String(), readByte(), readByte(), readBytesReverse(), and readShort().
size
final int com.runehive.net.packet.GamePacket.size private
The size of this packet.
Definition at line 33 of file GamePacket.java.
Referenced by getSize(), and toString().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/GamePacket.java