RuneHive-Game: com.runehive.content.itemaction.impl.MimeBox Class Reference
com.runehive.content.itemaction.impl.MimeBox Class Reference
Public Member Functions
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean itemOnItem (Player player, Item first, Item second)
String message (Item item)
The message of the action.
String toString ()
Static Private Attributes
static final EmoteUnlockable[] EMOTES = {EmoteUnlockable.GLASS_BOX, EmoteUnlockable.GLASS_WALL, EmoteUnlockable.LEAN, EmoteUnlockable.CLIMB_ROPE}
static final Item[] MIME_COSTUME = { new Item(3057), new Item(3058), new Item(3059), new Item(3060), new Item(3061) }
Detailed Description
Definition at line 11 of file MimeBox.java.
Member Function Documentation
inventory()
boolean com.runehive.content.itemaction.impl.MimeBox.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 23 of file MimeBox.java.
{
        if (opcode != 1)
            return false;
        player.inventory.remove(item);
        int random = Utility.random(1, 5);
        switch (random) {
            case 1:
            case 2:
                if (!EmoteHandler.containsAll(player, EMOTES)) {
                    EmoteUnlockable emote = EmoteHandler.selectRandom(player, EMOTES);
                    player.emoteUnlockable.add(emote);
                    EmoteHandler.refresh(player);
                    player.send(new SendMessage("You have unlocked the " + Utility.formatName(emote.name().toLowerCase().replace("_", "")) + " emote!"));
                    return true;
                }
                int random2 = Utility.random(1, 2);
                if (random2 == 1) {
                    Item clothing = Utility.randomElement(MIME_COSTUME);
                    player.inventory.add(clothing);
                    player.send(new SendMessage("You have received the " + clothing.getName() + " item!"));
                } else {
                    player.inventory.add(new Item(995, 75000));
                }
                break;
            case 3:
            case 4:
                player.inventory.add(Utility.randomElement(MIME_COSTUME));
                break;
            case 5:
                player.inventory.add(new Item(995, 75000));
                break;
        }
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.content.emote.EmoteHandler.containsAll(), EMOTES, com.runehive.game.world.entity.mob.player.Player.emoteUnlockable, com.runehive.util.Utility.formatName(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, MIME_COSTUME, com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), com.runehive.content.emote.EmoteHandler.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.content.emote.EmoteHandler.selectRandom(), and com.runehive.game.world.entity.mob.player.Player.send().
name()
String com.runehive.content.itemaction.impl.MimeBox.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 18 of file MimeBox.java.
{
        return "Mime box";
    }
Member Data Documentation
EMOTES
final EmoteUnlockable [] com.runehive.content.itemaction.impl.MimeBox.EMOTES = {EmoteUnlockable.GLASS_BOX, EmoteUnlockable.GLASS_WALL, EmoteUnlockable.LEAN, EmoteUnlockable.CLIMB_ROPE} static private
Definition at line 13 of file MimeBox.java.
{EmoteUnlockable.GLASS_BOX, EmoteUnlockable.GLASS_WALL, EmoteUnlockable.LEAN, EmoteUnlockable.CLIMB_ROPE};
Referenced by inventory().
MIME_COSTUME
final Item [] com.runehive.content.itemaction.impl.MimeBox.MIME_COSTUME = { new Item(3057), new Item(3058), new Item(3059), new Item(3060), new Item(3061) } static private
Definition at line 15 of file MimeBox.java.
{ new Item(3057), new Item(3058), new Item(3059), new Item(3060), new Item(3061) };
Referenced by inventory().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/MimeBox.java