RuneHive-Game: com.runehive.net.packet.in.DropItemPacketListener Class Reference
com.runehive.net.packet.in.DropItemPacketListener Class Reference
The GamePacket responsible for dropping items.
Public Member Functions
void handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Detailed Description
The GamePacket responsible for dropping items.
Author
Daniel | Obey
Definition at line 28 of file DropItemPacketListener.java.
Member Function Documentation
handlePacket()
void com.runehive.net.packet.in.DropItemPacketListener.handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Parameters
player The player receiving this packet.
packet The packet that has been received.
Implements com.runehive.net.packet.PacketListener.
Definition at line 31 of file DropItemPacketListener.java.
{
        if (player.isDead() || player.locking.locked(PacketType.DROP_ITEM) || player.getGambling().getStage().equals(GambleStage.PLACING_BET) || player.getGambling().getStage().equals(GambleStage.IN_PROGRESS)) {
            return;
        }
        final int itemId = packet.readShort(false, ByteModification.ADD);
        packet.readByte(false);
        packet.readByte(false);
        final int slot = packet.readShort(false, ByteModification.ADD);
        final Item item = player.inventory.get(slot);
        if (ItemDefinition.get(itemId) == null)
            return;
        player.getCombat().reset();
        if (!player.interfaceManager.isClear())
            player.interfaceManager.close(false);
        if (player.idle)
            player.idle = false;
        if (item == null)
            return;
        if (item.getId() != itemId)
            return;
        if (PluginManager.getDataBus().publish(player, new DropItemEvent(item, slot, player.getPosition().copy())))
            return;
        if (ItemActionRepository.drop(player, item)) {
            if (PlayerRight.isDeveloper(player)) {
                player.send(new SendMessage(String.format("[%s]: item=%d amount=%d slot=%d", ItemActionRepository.class.getSimpleName(), item.getId(), item.getAmount(), slot)));
            }
            return;
        }
        boolean inWilderness = Area.inWilderness(player);
        if (inWilderness && item.getValue(PriceType.VALUE) >= 500_000) {
            player.dialogueFactory.sendStatement("This is a valuable item, are you sure you want to", "drop it? In a PvP area, this item will be seen", "by everyone when dropped.");
            player.dialogueFactory.sendOption("Yes, drop it.", () -> {
                player.inventory.remove(item, slot, true);
                GroundItem.createGlobal(player, item);
            }, "Nevermind", () -> player.dialogueFactory.clear());
            player.dialogueFactory.execute();
            return;
        } else if (inWilderness) {
            player.inventory.remove(item, slot, true);
            GroundItem.createGlobal(player, item);
            return;
        }
        player.inventory.remove(item, slot, true);
        GroundItem.create(player, item);
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.dialogue.DialogueFactory.clear(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.position.Position.copy(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.items.ground.GroundItem.createGlobal(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.itemaction.ItemActionRepository.drop(), com.runehive.game.world.entity.mob.data.PacketType.DROP_ITEM, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.game.world.entity.mob.player.Player.getGambling(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.content.gambling.GambleManager.getStage(), com.runehive.game.world.items.Item.getValue(), com.runehive.game.world.entity.mob.player.Player.idle, com.runehive.content.gambling.GambleStage.IN_PROGRESS, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.mob.player.InterfaceManager.isClear(), com.runehive.game.world.entity.mob.Mob.isDead(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), com.runehive.game.world.entity.mob.Locking.locked(), com.runehive.game.world.entity.mob.Mob.locking, com.runehive.content.gambling.GambleStage.PLACING_BET, com.runehive.game.event.bus.PlayerDataBus.publish(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendOption(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE.
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/in/DropItemPacketListener.java