RuneHive-Game: com.runehive.net.codec.login.LoginDecoder Class Reference
com.runehive.net.codec.login.LoginDecoder Class Reference
The class that handles a connection through the login protocol.
Classes
enum State
Protected Member Functions
void decode (ChannelHandlerContext ctx, ByteBuf in, List< Object > out) throws Exception
Private Member Functions
void decodeConnectionType (ChannelHandlerContext ctx, ByteBuf in) throws Exception
void decodeHandshake (ChannelHandlerContext ctx, ByteBuf in)
void decodePayload (ChannelHandlerContext ctx, ByteBuf in, List< Object > out)
void sendResponseCode (ChannelHandlerContext ctx, LoginResponse response)
Private Attributes
State state = State.HANDSHAKE
Static Private Attributes
static final Logger logger = LogManager.getLogger(LoginDecoder.class)
static final int LOGIN_BLOCK_HEADER_SIZE = 38
static final int LOGIN_HANDSHAKE = 14
static final int MAGIC_NUMBER = 255
static final int NEW_CONNECTION_OPCODE = 16
static final ThreadLocal< Random > RANDOM = ThreadLocal.withInitial(SecureRandom::new)
static final int RECONNECTION_OPCODE = 18
Detailed Description
The class that handles a connection through the login protocol.
Author
nshusa
Definition at line 26 of file LoginDecoder.java.
Member Function Documentation
decode()
void com.runehive.net.codec.login.LoginDecoder.decode (ChannelHandlerContext ctx, ByteBuf in, List< Object > out) throws Exception protected
Definition at line 41 of file LoginDecoder.java.
{
        switch (state) {
            case HANDSHAKE:
                decodeHandshake(ctx, in);
                state = State.CONNECTION_TYPE;
                break;
            case CONNECTION_TYPE:
                decodeConnectionType(ctx, in);
                state = State.PAYLOAD;
                break;
            case PAYLOAD:
                decodePayload(ctx, in, out);
                break;
        }
    }
References com.runehive.net.codec.login.LoginDecoder.State.CONNECTION_TYPE, decodeConnectionType(), decodeHandshake(), decodePayload(), com.runehive.net.codec.login.LoginDecoder.State.PAYLOAD, and state.
decodeConnectionType()
void com.runehive.net.codec.login.LoginDecoder.decodeConnectionType (ChannelHandlerContext ctx, ByteBuf in) throws Exception private
Definition at line 86 of file LoginDecoder.java.
{
        if (in.isReadable()) {
            final int connectionType = in.readUnsignedByte();
            if (connectionType != NEW_CONNECTION_OPCODE && connectionType != RECONNECTION_OPCODE) {
                sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
            }
        } else {
            sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
        }
    }
References com.runehive.net.codec.login.LoginResponse.LOGIN_SERVER_REJECTED_SESSION, NEW_CONNECTION_OPCODE, RECONNECTION_OPCODE, and sendResponseCode().
Referenced by decode().
decodeHandshake()
void com.runehive.net.codec.login.LoginDecoder.decodeHandshake (ChannelHandlerContext ctx, ByteBuf in) private
Definition at line 61 of file LoginDecoder.java.
{
        final Channel channel = ctx.channel();
        channel.attr(Config.SESSION_KEY).set(new LoginSession(channel));
        if (in.readableBytes() >= 2) {
            final int handshake = in.readUnsignedByte();
            if (handshake != LOGIN_HANDSHAKE) {
                sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
                return;
            }
            @SuppressWarnings("unused") final int nameHash = in.readUnsignedByte();
            final long serverSeed = RANDOM.get().nextLong();
            ByteBuf buf = ctx.alloc().buffer(17);
            buf.writeLong(0);
            buf.writeByte(0);
            buf.writeLong(serverSeed);
            ctx.writeAndFlush(buf, ctx.voidPromise());
        } else {
            sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
        }
    }
References LOGIN_HANDSHAKE, com.runehive.net.codec.login.LoginResponse.LOGIN_SERVER_REJECTED_SESSION, RANDOM, sendResponseCode(), and com.runehive.Config.SESSION_KEY.
Referenced by decode().
decodePayload()
void com.runehive.net.codec.login.LoginDecoder.decodePayload (ChannelHandlerContext ctx, ByteBuf in, List< Object > out) private
Definition at line 98 of file LoginDecoder.java.
{
        final String host = ((InetSocketAddress) ctx.channel().remoteAddress()).getAddress().getHostAddress();
        final int loginBlockSize = in.readUnsignedByte();
        if (in.isReadable(loginBlockSize)) {
            final int magicId = in.readUnsignedByte();
            if (magicId != MAGIC_NUMBER) {
                logger.warn(String.format("[%s] wrong magic id: %d", host, magicId));
                sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
                return;
            }
            final int clientVersion = in.readUnsignedByte();
            if (Config.CLIENT_VERSION != clientVersion) {
                logger.warn("[{}] outdated client(client version): {} should be: {}", host, clientVersion, Config.CLIENT_VERSION);
                sendResponseCode(ctx, LoginResponse.GAME_UPDATED);
                return;
            }
            final int memoryVersion = in.readUnsignedByte();
            if (memoryVersion != 0 && memoryVersion != 1) {
                logger.warn(String.format("[%s] wrong memory version: %d", host, memoryVersion));
                sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
                return;
            }
            final int[] crcs = new int[9];
            for (int index = 0; index < crcs.length; index++) {
                crcs[index] = in.readInt();
            }
            final int expectedSize = in.readUnsignedByte(); // rsa header
            if (expectedSize != loginBlockSize - LOGIN_BLOCK_HEADER_SIZE) {
                logger.warn(String.format("[%s] wrong rsa block size: %d expecting: %d", host, (loginBlockSize - LOGIN_BLOCK_HEADER_SIZE), expectedSize));
                sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
                return;
            }
            final byte[] rsaBytes = new byte[loginBlockSize - LOGIN_BLOCK_HEADER_SIZE];
            in.readBytes(rsaBytes);
            final byte[] rsaBufBytes = new BigInteger(rsaBytes).modPow(Config.RSA_EXPONENT, Config.RSA_MODULUS).toByteArray();
            final int rsaBufferSize = rsaBufBytes.length;
            final ByteBuf rsaBuffer = in.alloc().buffer(rsaBufferSize, rsaBufferSize);
            try {
                rsaBuffer.writeBytes(rsaBufBytes);
                final int rsa = rsaBuffer.readUnsignedByte();
                if (rsa != 10) {
                    logger.warn(String.format("[%s] failed decrypt rsa %d", host, rsa));
                    sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
                    return;
                }
                final long clientHalf = rsaBuffer.readLong();
                final long serverHalf = rsaBuffer.readLong();
                int[] isaacSeed = {
                        (int) (clientHalf >> 32),
                        (int) clientHalf,
                        (int) (serverHalf >> 32),
                        (int) serverHalf
                };
                final IsaacCipher decryptor = new IsaacCipher(isaacSeed);
                for (int index = 0; index < isaacSeed.length; index++) {
                    isaacSeed[index] += 50;
                }
                final IsaacCipher encryptor = new IsaacCipher(isaacSeed);
                @SuppressWarnings("unused") final int uid = rsaBuffer.readInt();
                final String UUID = ByteBufUtil.readString(rsaBuffer);
                final String macAddress = ByteBufUtil.readString(rsaBuffer);
                final String username = ByteBufUtil.readString(rsaBuffer);
                final String password = ByteBufUtil.readString(rsaBuffer);
                out.add(new LoginDetailsPacket(UUID, macAddress, username, password, encryptor, decryptor));
            } finally {
                rsaBuffer.release();
            }
        } else {
            sendResponseCode(ctx, LoginResponse.LOGIN_SERVER_REJECTED_SESSION);
        }
    }
References com.runehive.Config.CLIENT_VERSION, com.runehive.net.codec.login.LoginResponse.GAME_UPDATED, logger, LOGIN_BLOCK_HEADER_SIZE, com.runehive.net.codec.login.LoginResponse.LOGIN_SERVER_REJECTED_SESSION, MAGIC_NUMBER, com.runehive.Config.RSA_EXPONENT, com.runehive.Config.RSA_MODULUS, and sendResponseCode().
Referenced by decode().
sendResponseCode()
void com.runehive.net.codec.login.LoginDecoder.sendResponseCode (ChannelHandlerContext ctx, LoginResponse response) private
Definition at line 190 of file LoginDecoder.java.
{
        if (response == LoginResponse.LOGIN_SERVER_REJECTED_SESSION) {
            final String host = ((InetSocketAddress) ctx.channel().remoteAddress()).getHostString();
            logger.warn(String.format("[%s] session was rejected", host));
        }
        ByteBuf buffer = ctx.alloc().buffer(Byte.BYTES);
        buffer.writeByte(response.getOpcode());
        ctx.writeAndFlush(buffer)
                .addListener(ChannelFutureListener.CLOSE);
        state = State.IGNORE;
    }
References com.runehive.net.codec.login.LoginResponse.getOpcode(), com.runehive.net.codec.login.LoginDecoder.State.IGNORE, logger, com.runehive.net.codec.login.LoginResponse.LOGIN_SERVER_REJECTED_SESSION, and state.
Referenced by decodeConnectionType(), decodeHandshake(), and decodePayload().
Member Data Documentation
logger
final Logger com.runehive.net.codec.login.LoginDecoder.logger = LogManager.getLogger(LoginDecoder.class) static private
Definition at line 28 of file LoginDecoder.java.
Referenced by decodePayload(), and sendResponseCode().
LOGIN_BLOCK_HEADER_SIZE
final int com.runehive.net.codec.login.LoginDecoder.LOGIN_BLOCK_HEADER_SIZE = 38 static private
Definition at line 34 of file LoginDecoder.java.
Referenced by decodePayload().
LOGIN_HANDSHAKE
final int com.runehive.net.codec.login.LoginDecoder.LOGIN_HANDSHAKE = 14 static private
Definition at line 30 of file LoginDecoder.java.
Referenced by decodeHandshake().
MAGIC_NUMBER
final int com.runehive.net.codec.login.LoginDecoder.MAGIC_NUMBER = 255 static private
Definition at line 33 of file LoginDecoder.java.
Referenced by decodePayload().
NEW_CONNECTION_OPCODE
final int com.runehive.net.codec.login.LoginDecoder.NEW_CONNECTION_OPCODE = 16 static private
Definition at line 31 of file LoginDecoder.java.
Referenced by decodeConnectionType().
RANDOM
final ThreadLocal<Random> com.runehive.net.codec.login.LoginDecoder.RANDOM = ThreadLocal.withInitial(SecureRandom::new) static private
Definition at line 36 of file LoginDecoder.java.
Referenced by decodeHandshake().
RECONNECTION_OPCODE
final int com.runehive.net.codec.login.LoginDecoder.RECONNECTION_OPCODE = 18 static private
Definition at line 32 of file LoginDecoder.java.
Referenced by decodeConnectionType().
state
State com.runehive.net.codec.login.LoginDecoder.state = State.HANDSHAKE private
Definition at line 38 of file LoginDecoder.java.
Referenced by decode(), and sendResponseCode().
The documentation for this class was generated from the following file:
java/com/runehive/net/codec/login/LoginDecoder.java