RuneHive-Game: com.runehive.content.skill.impl.construction.House Class Reference
com.runehive.content.skill.impl.construction.House Class Reference
Public Member Functions
void construct ()
void enter ()
void enter (String name)
int getHeight ()
BuildableMap getMap ()
List< ConstructionObject > getObjects ()
House (Player player)
boolean isInside ()
void leave ()
void location (BuildableMap newMap)
void purchase ()
void setMap (BuildableMap map)
void setObject (List< ConstructionObject > object)
boolean toolkit (GameObject object)
Private Attributes
int height
boolean inside
BuildableMap map
List< ConstructionObject > OBJECT = new ArrayList<ConstructionObject>()
Player player
Detailed Description
Definition at line 24 of file House.java.
Constructor & Destructor Documentation
House()
com.runehive.content.skill.impl.construction.House.House (Player player)
Definition at line 36 of file House.java.
{
        this.player = player;
        this.height = /* player.getPlayerAssistant().instance() */0;
    }
References player.
Referenced by enter().
Member Function Documentation
construct()
void com.runehive.content.skill.impl.construction.House.construct ()
Definition at line 207 of file House.java.
{
        BuildableObject object = player.attributes.get("CONSTRUCTION_BUILDOBJECT_KEY", BuildableObject.class);
        if (player.skills.getLevel(Skill.CONSTRUCTION) < object.getLevel()) {
            player.send(new SendMessage("You need a construction level of " + object.getLevel() + " to build this."));
            return;
        }
        // if (!player.inventory.contains(object.getItems())) {
        // player.send(new SendMessage("You do not have the required item to
        // build this."));
        // return;
        // }
        player.interfaceManager.close();
        player.animate(new Animation(898));
        player.inventory.removeAll(object.getItems());
        CustomGameObject gameObject = new CustomGameObject(object.getObject(), player.getPosition().copy());
        World.schedule(5, () -> {
            gameObject.register();
            player.skills.addExperience(Skill.CONSTRUCTION, object.getExperience());
            OBJECT.add(new ConstructionObject(gameObject.getId(), 0, gameObject.getPosition()));
            player.send(new SendMessage("You have successfully constructed " + Utility.getAOrAn(gameObject.getName()) + " " + gameObject.getName() + "."));
        });
    }
References com.runehive.game.world.entity.skill.Skill.CONSTRUCTION, com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.object.GameObject.getId(), com.runehive.game.world.object.CustomGameObject.getName(), com.runehive.game.world.entity.Entity.getPosition(), OBJECT, player, com.runehive.game.world.object.CustomGameObject.register(), and com.runehive.game.world.World.schedule().
enter() [1/2]
void com.runehive.content.skill.impl.construction.House.enter ()
Definition at line 84 of file House.java.
{
        if (map == null) {
            player.dialogueFactory.sendStatement("You need to purchase a house first.", "Speak to the agent to purchase one.").execute();
            return;
        }
        player.send(new SendString("Please wait as your house data is loaded...", 12285));
        player.send(new SendMinimapState(MinimapState.HIDDEN));
        player.interfaceManager.open(12283);
        player.move(new Position(map.getPosition().getX(), map.getPosition().getY(), height));
        map.execute(player);
        for (ConstructionObject aOBJECT : OBJECT) {
            new CustomGameObject(aOBJECT.getObject(), aOBJECT.getPosition()).register();
        }
        World.schedule(2500, () -> {
            player.send(new SendMinimapState(MinimapState.NORMAL));
            player.interfaceManager.close();
            player.send(new SendMessage("Welcome to your house! To start building please click on the world map to enter the", MessageColor.DARK_GREEN));
            player.send(new SendMessage("Construction Builder itemcontainer. To leave your house please click on the portal.", MessageColor.DARK_GREEN));
            player.send(new SendString("[CONSTRUCTION_MAP]", 0));
        });
        inside = true;
    }
References com.runehive.util.MessageColor.DARK_GREEN, height, com.runehive.net.packet.out.SendMinimapState.MinimapState.HIDDEN, inside, map, com.runehive.net.packet.out.SendMinimapState.MinimapState.NORMAL, OBJECT, player, com.runehive.game.world.object.CustomGameObject.register(), and com.runehive.game.world.World.schedule().
enter() [2/2]
void com.runehive.content.skill.impl.construction.House.enter (String name)
Definition at line 111 of file House.java.
{
        if (!ProfileRepository.exist(name)) {
            player.dialogueFactory.sendStatement("According to our data base, this player does not exist.").execute();
            return;
        }
        if (!World.search(name).isPresent()) {
            player.dialogueFactory.sendStatement(Utility.formatName(name) + " is not currently online.").execute();
            return;
        }
        Player other = World.search(name).get();
        House otherHouse = other.house;
        if (otherHouse.getMap() == null) {
            player.dialogueFactory.sendStatement(Utility.formatName(name) + " does not have a house for you to visit.").execute();
            return;
        }
        if (!otherHouse.isInside()) {
            player.dialogueFactory.sendStatement(Utility.formatName(name) + " must be in their house for you to visit.").execute();
        }
        player.send(new SendString("Please wait as your friend's house data is loaded...", 12285));
        player.send(new SendMinimapState(MinimapState.HIDDEN));
        player.interfaceManager.open(12283);
        player.move(new Position(other.house.getMap().getPosition().getX(), otherHouse.getMap().getPosition().getY(), otherHouse.getHeight()));
        otherHouse.getMap().execute(player);
        for (int index = 0; index < otherHouse.getObjects().size(); index++) {
            new CustomGameObject(otherHouse.getObjects().get(index).getObject(), otherHouse.getObjects().get(index).getPosition()).register();
        }
        World.schedule(2500, () -> {
            player.send(new SendMinimapState(MinimapState.NORMAL));
            player.interfaceManager.close();
            player.send(new SendMessage("Welcome to your friend's house.", MessageColor.DARK_GREEN));
        });
        inside = true;
    }
References com.runehive.util.MessageColor.DARK_GREEN, com.runehive.util.generic.GenericVoid< T >.execute(), com.runehive.game.world.entity.mob.player.profile.ProfileRepository.exist(), com.runehive.util.Utility.formatName(), getHeight(), getMap(), getObjects(), com.runehive.content.skill.impl.construction.BuildableMap.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.net.packet.out.SendMinimapState.MinimapState.HIDDEN, House(), com.runehive.game.world.entity.mob.player.Player.house, inside, isInside(), com.runehive.net.packet.out.SendMinimapState.MinimapState.NORMAL, player, com.runehive.game.world.object.CustomGameObject.register(), com.runehive.game.world.World.schedule(), and com.runehive.game.world.World.search().
getHeight()
int com.runehive.content.skill.impl.construction.House.getHeight ()
Definition at line 254 of file House.java.
{
        return height;
    }
References height.
Referenced by enter().
getMap()
BuildableMap com.runehive.content.skill.impl.construction.House.getMap ()
Definition at line 234 of file House.java.
{
        return map;
    }
References map.
Referenced by enter().
getObjects()
List< ConstructionObject > com.runehive.content.skill.impl.construction.House.getObjects ()
Definition at line 242 of file House.java.
{
        return OBJECT;
    }
References OBJECT.
Referenced by enter().
isInside()
boolean com.runehive.content.skill.impl.construction.House.isInside ()
Definition at line 250 of file House.java.
{
        return inside;
    }
References inside.
Referenced by enter().
leave()
void com.runehive.content.skill.impl.construction.House.leave ()
Definition at line 153 of file House.java.
{
        if (inside) {
            inside = false;
            player.move(new Position(3079, 3484, 0));
            player.send(new SendString("[NORMAL_MAP]", 0));
        }
    }
References inside, and player.
location()
void com.runehive.content.skill.impl.construction.House.location (BuildableMap newMap)
Definition at line 57 of file House.java.
{
        if (map == null) {
            player.dialogueFactory.sendStatement("Please purchase a house first.").execute();
            return;
        }
        if (map == newMap) {
            player.dialogueFactory.sendStatement("Your house is already set to this location.").execute();
            return;
        }
        if (player.skills.getLevel(Skill.CONSTRUCTION) < newMap.getLevel()) {
            player.dialogueFactory.sendStatement("You need a construction level of " + newMap.getLevel() + " to build this.").execute();
            return;
        }
        if (!player.inventory.contains(new Item(995, newMap.getCost()))) {
            player.dialogueFactory.sendStatement("You need " + newMap.getCost() + " royale tokens to purchase this map.").execute();
            return;
        }
        map = newMap;
        OBJECT.clear();
        player.inventory.remove(new Item(995, newMap.getCost()));
        player.dialogueFactory.sendStatement("You have successfully purchased the " + newMap.getName() + " map.").execute();
    }
References com.runehive.game.world.entity.skill.Skill.CONSTRUCTION, com.runehive.content.skill.impl.construction.BuildableMap.getCost(), com.runehive.content.skill.impl.construction.BuildableMap.getLevel(), com.runehive.content.skill.impl.construction.BuildableMap.getName(), map, OBJECT, and player.
Referenced by com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues().
purchase()
void com.runehive.content.skill.impl.construction.House.purchase ()
Definition at line 41 of file House.java.
{
        if (map != null) {
            player.dialogueFactory.sendStatement("You already have a house purchased!").execute();
            return;
        }
        if (!player.inventory.contains(new Item(995, 1000000))) {
            player.dialogueFactory.sendStatement("You need 1,000,000 royale tokens to purchase a house.").execute();
            return;
        }
        map = BuildableMap.SMALL_CAVE;
        player.inventory.remove(new Item(995, 1000000));
        player.dialogueFactory.sendStatement("You have successfully purchased a house for 1,000,000 royale tokens.", "Your house has been set to the default location.").execute();
    }
References map, player, and com.runehive.content.skill.impl.construction.BuildableMap.SMALL_CAVE.
Referenced by com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues().
setMap()
void com.runehive.content.skill.impl.construction.House.setMap (BuildableMap map)
Definition at line 238 of file House.java.
{
        this.map = map;
    }
References map.
setObject()
void com.runehive.content.skill.impl.construction.House.setObject (List< ConstructionObject > object)
Definition at line 246 of file House.java.
{
        OBJECT = object;
    }
References OBJECT.
toolkit()
boolean com.runehive.content.skill.impl.construction.House.toolkit (GameObject object)
Definition at line 161 of file House.java.
{
        if (!inside) {
            return false;
        }
        ConstructionObject constructionObject = null;
        for (int index = 0; index < OBJECT.size(); index++) {
            if (OBJECT.get(index).getObject() == object.getId() && OBJECT.get(index).getPosition().equals(object.getPosition())) {
                constructionObject = new ConstructionObject(object.getId(), OBJECT.get(index).getRotation(), object.getPosition());
                break;
            }
        }
        if (constructionObject == null) {
            return false;
        }
        player.dialogueFactory.sendOption("Remove object", () -> {
            // OBJECT.withdraw(constructionObject);
            object.unregister();
        }, "Change rotation", () -> {
            player.dialogueFactory.onAction(() -> {
                player.dialogueFactory.sendStatement("Please select the rotation direction").sendOption("North", () -> {
                    object.unregister();
                    new CustomGameObject(object.getId(), object.getPosition(), ObjectDirection.NORTH, ObjectType.GENERAL_PROP).register();
                }, "East", () -> {
                    object.unregister();
                    new CustomGameObject(object.getId(), object.getPosition(), ObjectDirection.EAST, ObjectType.GENERAL_PROP).register();
                }, "West", () -> {
                    object.unregister();
                    new CustomGameObject(object.getId(), object.getPosition(), ObjectDirection.WEST, ObjectType.GENERAL_PROP).register();
                }, "South", () -> {
                    object.unregister();
                    new CustomGameObject(object.getId(), object.getPosition(), ObjectDirection.SOUTH, ObjectType.GENERAL_PROP).register();
                }, "Nevermind", () -> {
                    player.interfaceManager.close();
                }).execute();
            });
        }, "Nevermind", () -> {
            player.interfaceManager.close();
        }).execute();
        return true;
    }
References com.runehive.game.world.object.ObjectDirection.EAST, com.runehive.game.world.object.ObjectType.GENERAL_PROP, inside, com.runehive.game.world.object.ObjectDirection.NORTH, OBJECT, player, com.runehive.game.world.object.CustomGameObject.register(), com.runehive.game.world.object.ObjectDirection.SOUTH, and com.runehive.game.world.object.ObjectDirection.WEST.
Member Data Documentation
height
int com.runehive.content.skill.impl.construction.House.height private
Definition at line 34 of file House.java.
Referenced by enter(), and getHeight().
inside
boolean com.runehive.content.skill.impl.construction.House.inside private
Definition at line 32 of file House.java.
Referenced by enter(), enter(), isInside(), leave(), and toolkit().
map
BuildableMap com.runehive.content.skill.impl.construction.House.map private
Definition at line 28 of file House.java.
Referenced by enter(), getMap(), location(), purchase(), and setMap().
OBJECT
List<ConstructionObject> com.runehive.content.skill.impl.construction.House.OBJECT = new ArrayList<ConstructionObject>() private
Definition at line 30 of file House.java.
Referenced by construct(), enter(), getObjects(), location(), setObject(), and toolkit().
player
Player com.runehive.content.skill.impl.construction.House.player private
Definition at line 26 of file House.java.
Referenced by construct(), enter(), enter(), House(), leave(), location(), purchase(), and toolkit().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/construction/House.java