RuneHive-Game: com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc Class Reference
com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc Class Reference
@Author Origin 2/22/2023
Static Public Member Functions
static double getAttackRoll (Mob attacker, CombatType style, SlayerTask task)
static double getDefenceRoll (Mob defender, CombatType style)
static double getEffectiveLevelAttacker (Mob attacker, CombatType style)
static double getEffectiveLevelDefender (Mob defender)
static int getEquipmentBonus (Mob attacker, CombatType style, SlayerTask task)
static int getMagicDefenceLevelNpc (Mob defender, CombatType style)
static int getMagicLevel (Mob attacker)
static int getMagicLevelNpc (Mob defender)
static double getPrayerBonus (Mob attacker, CombatType style)
static boolean successful (Mob attacker, Mob defender, CombatType style)
Static Public Attributes
static final SecureRandom srand = new SecureRandom()
Detailed Description
@Author Origin 2/22/2023
Definition at line 19 of file MagicAccuracyNpc.java.
Member Function Documentation
getAttackRoll()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getAttackRoll (Mob attacker, CombatType style, SlayerTask task) static
Definition at line 134 of file MagicAccuracyNpc.java.
{
        return Math.round(getEffectiveLevelAttacker(attacker, style) * (getEquipmentBonus(attacker, style, task)) + 64D);
    }
References getEffectiveLevelAttacker(), and getEquipmentBonus().
getDefenceRoll()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getDefenceRoll (Mob defender, CombatType style) static
Definition at line 122 of file MagicAccuracyNpc.java.
{
        return Math.floor((getEffectiveLevelDefender(defender) + 9) * (getMagicDefenceLevelNpc(defender, style) + 64));
    }
References getEffectiveLevelDefender(), and getMagicDefenceLevelNpc().
getEffectiveLevelAttacker()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEffectiveLevelAttacker (Mob attacker, CombatType style) static
Definition at line 130 of file MagicAccuracyNpc.java.
{
        return getMagicLevel(attacker) * (getPrayerBonus(attacker, style) + 9D);
    }
References getMagicLevel(), and getPrayerBonus().
Referenced by getAttackRoll().
getEffectiveLevelDefender()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEffectiveLevelDefender (Mob defender) static
Definition at line 118 of file MagicAccuracyNpc.java.
{
        return getMagicLevelNpc(defender);
    }
References getMagicLevelNpc().
Referenced by getDefenceRoll().
getEquipmentBonus()
int com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEquipmentBonus (Mob attacker, CombatType style, SlayerTask task) static
Definition at line 52 of file MagicAccuracyNpc.java.
{
        int bonus = 1;
        if (attacker.isPlayer()) {
            if (style == CombatType.MAGIC) {
                bonus = attacker.getPlayer().getBonus(3);
            }
        }
        if (attacker.isPlayer()) {
            if (style.equals(CombatType.MAGIC)) {
                if (FormulaUtils.voidMagic((Player) attacker)) {
                    bonus *= 1.45D; //45%
                }
                if (((Player) attacker).equipment.contains(27275)) {
                    bonus *= 3;
                }
                if (((Player) attacker).equipment.contains(Items.SALVE_AMULET)) {
                    bonus *= 1.10D;
                }
                if (attacker.isNpc()) {
                    if (((Player) attacker).equipment.contains(Items.SLAYER_HELMET)) {
                        bonus *= 1.05D;
                    }
                    if (((Player) attacker).equipment.contains(Items.BLACK_SLAYER_HELMET) || ((Player) attacker).equipment.contains(Items.GREEN_SLAYER_HELMET)
                            || ((Player) attacker).equipment.contains(Items.PURPLE_SLAYER_HELMET) || ((Player) attacker).equipment.contains(Items.RED_SLAYER_HELMET) || ((Player) attacker).equipment.contains(21888)) {
                        bonus *= 1.10D;
                    }
                    if (((Player) attacker).equipment.contains(19720)) {
                        bonus *= 1.05D;
                    }
                    if (((Player) attacker).equipment.contains(22555)) {
                        bonus *= 1.50D;
                    }
                }
            }
            if (task != null && task.valid(task.getName())) {
                if (((Player) attacker).equipment.contains(Items.SLAYER_HELMET)) {
                    bonus *= 1.15D;
                }
                if (((Player) attacker).equipment.contains(11865)) {
                    bonus *= 1.18D;
                }
                if (((Player) attacker).equipment.contains(Items.BLACK_SLAYER_HELMET) || ((Player) attacker).equipment.contains(Items.GREEN_SLAYER_HELMET) || ((Player) attacker).equipment.contains(Items.PURPLE_SLAYER_HELMET)
                        || ((Player) attacker).equipment.contains(Items.RED_SLAYER_HELMET) || ((Player) attacker).equipment.contains(21888)) {
                    bonus *= 1.20D;
                }
            }
        }
        //some of these are custom
        return bonus;
    }
References com.runehive.util.Items.BLACK_SLAYER_HELMET, com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.util.Items.GREEN_SLAYER_HELMET, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.combat.CombatType.MAGIC, com.runehive.util.Items.PURPLE_SLAYER_HELMET, com.runehive.util.Items.RED_SLAYER_HELMET, com.runehive.util.Items.SALVE_AMULET, com.runehive.util.Items.SLAYER_HELMET, and com.runehive.game.world.entity.combat.FormulaUtils.voidMagic().
Referenced by getAttackRoll().
getMagicDefenceLevelNpc()
int com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicDefenceLevelNpc (Mob defender, CombatType style) static
Definition at line 108 of file MagicAccuracyNpc.java.
{
        int bonus = 0;
        if (defender instanceof Npc npc) {
            if (style == CombatType.MAGIC) {
                bonus = npc.getBonus(8);
            }
        }
        return bonus + 64;
    }
References com.runehive.game.world.entity.combat.CombatType.MAGIC.
Referenced by getDefenceRoll().
getMagicLevel()
int com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicLevel (Mob attacker) static
Definition at line 126 of file MagicAccuracyNpc.java.
{
        return attacker.skills.getLevel(Skill.MAGIC);
    }
References com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.MAGIC, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by getEffectiveLevelAttacker().
getMagicLevelNpc()
int com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicLevelNpc (Mob defender) static
Definition at line 104 of file MagicAccuracyNpc.java.
{
        return defender.getNpc().definition.getSkills()[6];
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.mob.Mob.getNpc(), and com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getSkills().
Referenced by getEffectiveLevelDefender().
getPrayerBonus()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getPrayerBonus (Mob attacker, CombatType style) static
Definition at line 37 of file MagicAccuracyNpc.java.
{
        double prayerBonus = 1D;
        if (style == CombatType.MAGIC) {
            if (attacker.prayer.isActive(Prayer.MYSTIC_WILL))
                prayerBonus *= 1.05D; // 5% magic level boost
            else if (attacker.prayer.isActive(Prayer.MYSTIC_LORE))
                prayerBonus *= 1.10D; // 10% magic level boost
            else if (attacker.prayer.isActive(Prayer.MYSTIC_MIGHT))
                prayerBonus *= 1.15D; // 15% magic level boost
            else if (attacker.prayer.isActive(Prayer.AUGURY))
                prayerBonus *= 1.25D; // 25% magic level boost
        }
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.AUGURY, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.combat.CombatType.MAGIC, com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_LORE, com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_MIGHT, com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_WILL, and com.runehive.game.world.entity.mob.Mob.prayer.
Referenced by getEffectiveLevelAttacker().
successful()
boolean com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.successful (Mob attacker, Mob defender, CombatType style) static
Definition at line 23 of file MagicAccuracyNpc.java.
{
        double attackRoll = MagicAccuracy.getAttackRoll(attacker);//getAttackRoll(attacker, style, null); // XXX: task needs to be grabbed in the inverse direction (player attacking NPC)
        double defenceRoll = MagicAccuracy.getDefenceRoll(defender);//getDefenceRoll(defender, style);
        double chance;
        if (attackRoll > defenceRoll)
            chance = 1D - (defenceRoll + 2D) / (2D * (attackRoll + 1D));
        else
            chance = attackRoll / (2D * (defenceRoll + 1D));
        double roll = srand.nextDouble();
        return chance > roll;
    }
References com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getAttackRoll(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getDefenceRoll(), and srand.
Referenced by com.runehive.game.world.entity.combat.attack.FormulaFactory.isAccurate().
Member Data Documentation
srand
final SecureRandom com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.srand = new SecureRandom() static
Definition at line 21 of file MagicAccuracyNpc.java.
Referenced by successful().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/accuracy/MagicAccuracyNpc.java