RuneHive-Game: com.runehive.game.world.region.Region Class Reference
com.runehive.game.world.region.Region Class Reference
Represents a single region.
Public Member Functions
void addGroundItem (GroundItem item)
Adds a ground item to this region.
void addNpc (Npc npc)
Adds an npc to this region.
void addObject (GameObject object)
Adds an object to this region.
void addPlayer (Player player)
Adds a player to this region.
boolean contains (int x, int y)
boolean contains (Position position)
boolean containsNpc (int height, Npc npc)
boolean containsObject (int height, GameObject object)
boolean containsObject (Position position)
boolean containsPlayer (int height, Player player)
GameObject getCustomObject (int id, Position position)
int getFlags (int height, int x, int y)
Gets a single tile in this region from the specified height, x and y coordinates.
GameObject getGameObject (int id, Position position)
GroundItem getGroundItem (int id, Position position)
Set< GroundItem > getGroundItems (Position position)
int getId ()
Collection< Npc > getNpcs (int height)
List< GameObject > getObjects (Position position)
Collection< Player > getPlayers (int height)
Optional< Region[]> getSurroundingRegions ()
int getX ()
int getY ()
Region (int x, int y)
Creates a region.
void removeGroundItem (GroundItem item)
Adds a ground item to this region.
void removeNpc (Npc npc)
Removes an npc from this region.
void removeObject (GameObject object)
Removes an object from this region.
void removePlayer (Player player)
Removes a player from this region.
void sendGameObjects (Player player)
Sends game objects in this region to the player.
void sendGroundItems (Player player)
Sends ground items in this region to the player.
void setFlags (int height, int x, int y, int flags)
Gets a single tile in this region from the specified height, x and y coordinates.
void setSurroundingRegions (Optional< Region[]> surroundingRegions)
void skip (GameObject gameObject)
String toString ()
void unsetFlags (int height, int x, int y, int flags)
Gets a single tile in this region from the specified height, x and y coordinates.
Static Public Member Functions
static boolean reachable (Interactable source, Interactable target)
static boolean reachable (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength)
Static Public Attributes
static final Map< Position, GameObject > ACTIVE_OBJECT = new HashMap<>()
static final int SIZE = CHUNK_SIZE * 8
static final Set< Position > SKIPPED_OBJECTS = new HashSet<>()
static final int VIEW_DISTANCE = SIZE / 4 - 1
Private Member Functions
RegionBlock getBlock (int height)
Private Attributes
final RegionBlock[] blocks = new RegionBlock[HEIGHT_LEVELS]
The region blocks that execute different heights.
int id
The region id.
Optional< Region[]> surroundingRegions = Optional.empty()
The surrounded regions.
int x
The region coordinates.
int y
Static Private Attributes
static final int CHUNK_SIZE = 8
Detailed Description
Represents a single region.
Author
Graham Edgecombe
Definition at line 21 of file Region.java.
Constructor & Destructor Documentation
Region()
com.runehive.game.world.region.Region.Region (int x, int y)
Creates a region.
Definition at line 41 of file Region.java.
{
        this.x = x;
        this.y = y;
        this.id = ((x >> 6) << 8) + (y >> 6);
    }
References x, and y.
Referenced by setSurroundingRegions().
Member Function Documentation
addGroundItem()
void com.runehive.game.world.region.Region.addGroundItem (GroundItem item)
Adds a ground item to this region.
Definition at line 150 of file Region.java.
{
        getBlock(item.getHeight()).addGroundItem(item);
    }
References com.runehive.game.world.region.RegionBlock.addGroundItem(), getBlock(), and com.runehive.game.world.entity.Entity.getHeight().
addNpc()
void com.runehive.game.world.region.Region.addNpc (Npc npc)
Adds an npc to this region.
Definition at line 130 of file Region.java.
{
        getBlock(npc.getHeight()).addNpc(npc);
    }
References com.runehive.game.world.region.RegionBlock.addNpc(), getBlock(), and com.runehive.game.world.entity.Entity.getHeight().
addObject()
void com.runehive.game.world.region.Region.addObject (GameObject object)
Adds an object to this region.
Definition at line 140 of file Region.java.
{
        getBlock(object.getHeight()).addObject(object);
    }
References com.runehive.game.world.region.RegionBlock.addObject(), and getBlock().
addPlayer()
void com.runehive.game.world.region.Region.addPlayer (Player player)
Adds a player to this region.
Definition at line 120 of file Region.java.
{
        getBlock(player.getHeight()).addPlayer(player);
    }
References com.runehive.game.world.region.RegionBlock.addPlayer(), getBlock(), and com.runehive.game.world.entity.Entity.getHeight().
contains() [1/2]
boolean com.runehive.game.world.region.Region.contains (int x, int y)
Returns
true if the region contains the position
Definition at line 211 of file Region.java.
{
        return getX() == ((x >> 3) - 6) >> 3 && getY() == ((y >> 3) - 6) >> 3;
    }
References getX(), getY(), x, and y.
contains() [2/2]
boolean com.runehive.game.world.region.Region.contains (Position position)
Returns
true if the region contains the position
Definition at line 206 of file Region.java.
{
        return getX() == position.getRegionX() && getY() == position.getRegionY();
    }
References getX(), and getY().
containsNpc()
boolean com.runehive.game.world.region.Region.containsNpc (int height, Npc npc)
Definition at line 159 of file Region.java.
{
        return getBlock(height).containsNpc(npc);
    }
References com.runehive.game.world.region.RegionBlock.containsNpc(), and getBlock().
containsObject() [1/2]
boolean com.runehive.game.world.region.Region.containsObject (int height, GameObject object)
Returns
true if object is in region
Definition at line 168 of file Region.java.
{
        return getBlock(height).containsObject(object);
    }
References com.runehive.game.world.region.RegionBlock.containsObject(), and getBlock().
Referenced by com.runehive.game.world.object.StaticGameObject.active(), com.runehive.game.world.object.CustomGameObject.addToRegion(), com.runehive.content.skill.impl.firemaking.FiremakingAction.canInit(), com.runehive.content.combat.cannon.Cannon.register(), com.runehive.game.world.object.StaticGameObject.register(), com.runehive.game.world.object.CustomGameObject.removeFromRegion(), and com.runehive.game.world.object.StaticGameObject.unregister().
containsObject() [2/2]
boolean com.runehive.game.world.region.Region.containsObject (Position position)
Returns
true if object occupies position
Definition at line 173 of file Region.java.
{
        return getBlock(position.getHeight()).containsObject(position);
    }
References com.runehive.game.world.region.RegionBlock.containsObject(), and getBlock().
containsPlayer()
boolean com.runehive.game.world.region.Region.containsPlayer (int height, Player player)
Definition at line 163 of file Region.java.
{
        return getBlock(height).containsPlayer(player);
    }
References com.runehive.game.world.region.RegionBlock.containsPlayer(), and getBlock().
getBlock()
RegionBlock com.runehive.game.world.region.Region.getBlock (int height) private
Definition at line 215 of file Region.java.
{
        if (height > HEIGHT_LEVELS || height < 0) {
            throw new IllegalArgumentException("Height is out of bounds. Received (" + height + "), expected range [0, " + HEIGHT_LEVELS + "].");
        }
        if (blocks[height] == null) {
            blocks[height] = new RegionBlock();
        }
        return blocks[height];
    }
References blocks.
Referenced by addGroundItem(), addNpc(), addObject(), addPlayer(), containsNpc(), containsObject(), containsObject(), containsPlayer(), getCustomObject(), getFlags(), getGameObject(), getGroundItem(), getGroundItems(), getNpcs(), getObjects(), getPlayers(), removeGroundItem(), removeNpc(), removeObject(), removePlayer(), sendGameObjects(), sendGroundItems(), setFlags(), skip(), and unsetFlags().
getCustomObject()
GameObject com.runehive.game.world.region.Region.getCustomObject (int id, Position position)
Definition at line 187 of file Region.java.
{
        return getBlock(position.getHeight()).getCustomObject(id, position);
    }
References getBlock(), and com.runehive.game.world.region.RegionBlock.getCustomObject().
getFlags()
int com.runehive.game.world.region.Region.getFlags (int height, int x, int y)
Gets a single tile in this region from the specified height, x and y coordinates.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
The tile in this region for the specified attributes.
Definition at line 66 of file Region.java.
{
        return getBlock(height).getFlags(x, y);
    }
References getBlock(), com.runehive.game.world.region.RegionBlock.getFlags(), x, and y.
getGameObject()
GameObject com.runehive.game.world.region.Region.getGameObject (int id, Position position)
Returns
true if object with given id occupies position
Definition at line 183 of file Region.java.
{
        return getBlock(position.getHeight()).getGameObject(id, position);
    }
References getBlock(), and com.runehive.game.world.region.RegionBlock.getGameObject().
Referenced by com.runehive.content.Obelisks.activate().
getGroundItem()
GroundItem com.runehive.game.world.region.Region.getGroundItem (int id, Position position)
Returns
the ground item with the given id at the given position
Definition at line 115 of file Region.java.
{
        return getBlock(position.getHeight()).getGroundItem(id, position);
    }
References getBlock(), and com.runehive.game.world.region.RegionBlock.getGroundItem().
getGroundItems()
Set< GroundItem > com.runehive.game.world.region.Region.getGroundItems (Position position)
Returns
a set of ground items on the position
Definition at line 178 of file Region.java.
{
        return getBlock(position.getHeight()).getGroundItems(position);
    }
References getBlock(), and com.runehive.game.world.region.RegionBlock.getGroundItems().
getId()
int com.runehive.game.world.region.Region.getId ()
Definition at line 282 of file Region.java.
                       {
        return id;
    }
References id.
getNpcs()
Collection< Npc > com.runehive.game.world.region.Region.getNpcs (int height)
Returns
the npcs in this region
Definition at line 110 of file Region.java.
{
        return getBlock(height).getNpcs();
    }
References getBlock(), and com.runehive.game.world.region.RegionBlock.getNpcs().
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression().
getObjects()
List< GameObject > com.runehive.game.world.region.Region.getObjects (Position position)
Definition at line 191 of file Region.java.
{
        return getBlock(position.getHeight()).getGameObjects(position);
    }
References getBlock(), and com.runehive.game.world.region.RegionBlock.getGameObjects().
getPlayers()
Collection< Player > com.runehive.game.world.region.Region.getPlayers (int height)
Returns
the players in this region
Definition at line 105 of file Region.java.
{
        return getBlock(height).getPlayers();
    }
References getBlock(), and com.runehive.game.world.region.RegionBlock.getPlayers().
Referenced by com.runehive.content.combat.cannon.Cannon.addToRegion(), com.runehive.content.combat.cannon.Cannon.removeFromRegion(), and com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack.start().
getSurroundingRegions()
Optional< Region[]> com.runehive.game.world.region.Region.getSurroundingRegions ()
Definition at line 96 of file Region.java.
{
        return surroundingRegions;
    }
References surroundingRegions.
Referenced by com.runehive.game.world.region.RegionManager.forNearbyPlayer(), and com.runehive.game.world.region.RegionManager.getSurroundingRegions().
getX()
int com.runehive.game.world.region.Region.getX ()
Returns
region x-coordinate
Definition at line 48 of file Region.java.
                      {
        return x;
    }
References x.
Referenced by contains(), and contains().
getY()
int com.runehive.game.world.region.Region.getY ()
Returns
region y-coordinate
Definition at line 53 of file Region.java.
                      {
        return y;
    }
References y.
Referenced by contains(), and contains().
reachable() [1/2]
boolean com.runehive.game.world.region.Region.reachable (Interactable source, Interactable target) static
Definition at line 227 of file Region.java.
{
        return reachable(source.getPosition(), source.width(), source.length(), target.getPosition(), target.width(), target.length());
    }
References com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), reachable(), and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), com.runehive.game.world.pathfinding.path.impl.DijkstraPathFinder.find(), and reachable().
reachable() [2/2]
boolean com.runehive.game.world.region.Region.reachable (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength) static
Definition at line 231 of file Region.java.
{
        if (Utility.inside(source, sourceWidth, sourceLength, target, targetWidth, targetLength)) {
            return targetWidth == 0 || targetLength == 0;
        }
        int x, y;
        int sourceTopX = source.getX() + sourceWidth - 1;
        int sourceTopY = source.getY() + sourceLength - 1;
        int targetTopX = target.getX() + targetWidth - 1;
        int targetTopY = target.getY() + targetLength - 1;
        if (sourceTopY == target.getY() - 1 && source.getX() >= target.getX() && source.getX() <= targetTopX) {
            for (x = 0, y = sourceLength - 1; x < sourceWidth; x++)
                if (TraversalMap.blockedNorth(source.transform(x, y)))
                    return false;
            return true;
        }
        if (sourceTopX == target.getX() - 1 && source.getY() >= target.getY() && source.getY() <= targetTopY) {
            for (x = 0, y = 0; y < sourceLength; y++)
                if (TraversalMap.blockedEast(source.transform(x, y)))
                    return false;
            return true;
        }
        if (source.getY() == targetTopY + 1 && source.getX() >= target.getX() && source.getX() <= targetTopX) {
            for (x = 0, y = 0; x < sourceWidth; x++)
                if (TraversalMap.blockedSouth(source.transform(x, y)))
                    return false;
            return true;
        }
        if (source.getX() == targetTopX + 1 && source.getY() >= target.getY() && source.getY() <= targetTopY) {
            for (x = sourceWidth - 1, y = 0; y < sourceLength; y++)
                if (TraversalMap.blockedWest(source.transform(x, y)))
                    return false;
            return true;
        }
        return false;
    }
References com.runehive.game.world.pathfinding.TraversalMap.blockedEast(), com.runehive.game.world.pathfinding.TraversalMap.blockedNorth(), com.runehive.game.world.pathfinding.TraversalMap.blockedSouth(), com.runehive.game.world.pathfinding.TraversalMap.blockedWest(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.util.Utility.inside(), com.runehive.game.world.position.Position.transform(), x, and y.
removeGroundItem()
void com.runehive.game.world.region.Region.removeGroundItem (GroundItem item)
Adds a ground item to this region.
Definition at line 155 of file Region.java.
{
        getBlock(item.getHeight()).removeGroundItem(item);
    }
References getBlock(), com.runehive.game.world.entity.Entity.getHeight(), and com.runehive.game.world.region.RegionBlock.removeGroundItem().
removeNpc()
void com.runehive.game.world.region.Region.removeNpc (Npc npc)
Removes an npc from this region.
Definition at line 135 of file Region.java.
{
        getBlock(npc.getHeight()).removeNpc(npc);
    }
References getBlock(), com.runehive.game.world.entity.Entity.getHeight(), and com.runehive.game.world.region.RegionBlock.removeNpc().
removeObject()
void com.runehive.game.world.region.Region.removeObject (GameObject object)
Removes an object from this region.
Definition at line 145 of file Region.java.
{
        getBlock(object.getHeight()).removeObject(object);
    }
References getBlock(), and com.runehive.game.world.region.RegionBlock.removeObject().
removePlayer()
void com.runehive.game.world.region.Region.removePlayer (Player player)
Removes a player from this region.
Definition at line 125 of file Region.java.
{
        getBlock(player.getHeight()).removePlayer(player);
    }
References getBlock(), com.runehive.game.world.entity.Entity.getHeight(), and com.runehive.game.world.region.RegionBlock.removePlayer().
sendGameObjects()
void com.runehive.game.world.region.Region.sendGameObjects (Player player)
Sends game objects in this region to the player.
Definition at line 201 of file Region.java.
{
        getBlock(player.getHeight()).sendGameObjects(player);
    }
References getBlock(), com.runehive.game.world.entity.Entity.getHeight(), and com.runehive.game.world.region.RegionBlock.sendGameObjects().
sendGroundItems()
void com.runehive.game.world.region.Region.sendGroundItems (Player player)
Sends ground items in this region to the player.
Definition at line 196 of file Region.java.
{
        getBlock(player.getHeight()).sendGroundItems(player);
    }
References getBlock(), com.runehive.game.world.entity.Entity.getHeight(), and com.runehive.game.world.region.RegionBlock.sendGroundItems().
setFlags()
void com.runehive.game.world.region.Region.setFlags (int height, int x, int y, int flags)
Gets a single tile in this region from the specified height, x and y coordinates.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
The tile in this region for the specified attributes.
Definition at line 79 of file Region.java.
{
        getBlock(height).setFlags(x, y, flags);
    }
References getBlock(), com.runehive.game.world.region.RegionBlock.setFlags(), x, and y.
setSurroundingRegions()
void com.runehive.game.world.region.Region.setSurroundingRegions (Optional< Region[]> surroundingRegions)
Definition at line 100 of file Region.java.
{
        this.surroundingRegions = surroundingRegions;
    }
References Region(), and surroundingRegions.
Referenced by com.runehive.game.world.region.RegionManager.getSurroundingRegions().
skip()
void com.runehive.game.world.region.Region.skip (GameObject gameObject)
Definition at line 273 of file Region.java.
{
        getBlock(gameObject.getHeight()).skip(gameObject);
    }
References getBlock(), com.runehive.game.world.Interactable.getHeight(), and com.runehive.game.world.region.RegionBlock.skip().
toString()
String com.runehive.game.world.region.Region.toString ()
Definition at line 278 of file Region.java.
{
        return "Region[" + x + "_" + y + "]";
    }
References x, and y.
unsetFlags()
void com.runehive.game.world.region.Region.unsetFlags (int height, int x, int y, int flags)
Gets a single tile in this region from the specified height, x and y coordinates.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
The tile in this region for the specified attributes.
Definition at line 92 of file Region.java.
{
        getBlock(height).unsetFlags(x, y, flags);
    }
References getBlock(), com.runehive.game.world.region.RegionBlock.unsetFlags(), x, and y.
Member Data Documentation
ACTIVE_OBJECT
final Map<Position, GameObject> com.runehive.game.world.region.Region.ACTIVE_OBJECT = new HashMap<>() static
Definition at line 25 of file Region.java.
Referenced by com.runehive.game.world.object.CustomGameObject.register(), and com.runehive.game.world.object.CustomGameObject.unregister().
blocks
final RegionBlock [] com.runehive.game.world.region.Region.blocks = new RegionBlock[HEIGHT_LEVELS] private
The region blocks that execute different heights.
Definition at line 35 of file Region.java.
Referenced by getBlock().
CHUNK_SIZE
final int com.runehive.game.world.region.Region.CHUNK_SIZE = 8 static private
Definition at line 22 of file Region.java.
id
int com.runehive.game.world.region.Region.id private
The region id.
Definition at line 29 of file Region.java.
Referenced by getId().
SIZE
final int com.runehive.game.world.region.Region.SIZE = CHUNK_SIZE * 8 static
Definition at line 23 of file Region.java.
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find(), com.runehive.game.world.pathfinding.path.impl.DijkstraPathFinder.find(), and com.runehive.content.skill.impl.farming.zones.FarmingZone.isViewable().
SKIPPED_OBJECTS
final Set<Position> com.runehive.game.world.region.Region.SKIPPED_OBJECTS = new HashSet<>() static
Definition at line 26 of file Region.java.
Referenced by com.runehive.util.parser.impl.ObjectRemovalParser.parse(), and com.runehive.fs.cache.decoder.RegionDecoder.parseGameObject().
surroundingRegions
Optional<Region[]> com.runehive.game.world.region.Region.surroundingRegions = Optional.empty() private
The surrounded regions.
Definition at line 38 of file Region.java.
Referenced by getSurroundingRegions(), and setSurroundingRegions().
VIEW_DISTANCE
final int com.runehive.game.world.region.Region.VIEW_DISTANCE = SIZE / 4 - 1 static
Definition at line 24 of file Region.java.
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.checkDistances(), com.runehive.game.world.entity.combat.CombatTarget.compare(), com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.findRoute(), com.runehive.game.world.region.RegionManager.getLocalNpcs(), com.runehive.game.world.region.RegionManager.getLocalPlayers(), com.runehive.content.combat.cannon.CannonManager.getNpc(), com.runehive.game.world.object.StaticGameObject.register(), com.runehive.game.world.entity.mob.player.requests.RequestManager.request(), com.runehive.game.world.World.sendGraphic(), com.runehive.game.world.World.sendGraphic(), com.runehive.game.world.World.sendObjectAnimation(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.World.sendProjectile(), and com.runehive.game.world.object.StaticGameObject.unregister().
x
int com.runehive.game.world.region.Region.x private
The region coordinates.
Definition at line 32 of file Region.java.
Referenced by contains(), getFlags(), getX(), reachable(), Region(), setFlags(), toString(), and unsetFlags().
y
int com.runehive.game.world.region.Region.y private
Definition at line 32 of file Region.java.
Referenced by contains(), getFlags(), getY(), reachable(), Region(), setFlags(), toString(), and unsetFlags().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/region/Region.java