RuneHive-Game: com.runehive.content.dialogue.impl.NieveDialogue Class Reference
com.runehive.content.dialogue.impl.NieveDialogue Class Reference
Public Member Functions
void sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Private Member Functions
void sell (DialogueFactory factory)
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.dialogue.Dialogue
static final boolean isDialogueButton (int button)
Checks if the button triggered is an optional dialogue button.
Static Public Attributes inherited from com.runehive.content.dialogue.Dialogue
static final ImmutableList< Integer > DIALOGUE_BUTTONS = ImmutableList.of(2461, 2471, 2482, 2462, 2472, 2483, 2473, 2484, 2485, 2494, 2495, 2496, 2497, 2498)
The action buttons responsible for dialogues.
Detailed Description
Definition at line 10 of file NieveDialogue.java.
Member Function Documentation
sell()
void com.runehive.content.dialogue.impl.NieveDialogue.sell (DialogueFactory factory) private
Definition at line 21 of file NieveDialogue.java.
{
        factory.sendOption("What do I get for my offerings?", () -> {
            factory.sendNpcChat(6797, "You will get slayer experience and points!");
        }, "What items can be offered?", () -> {
            factory.sendStatement("Ensouled heads", "Ancient shards & Dark Totem pieces");
        }, "Offer all items", () -> {
            factory.onAction(() -> SlayerOfferings.offer(factory.getPlayer()));
        }, "Nevermind", factory::clear);
    }
References com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
Referenced by sendDialogues().
sendDialogues()
void com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Parameters
factory The factory for this dialogue.
Reimplemented from com.runehive.content.dialogue.Dialogue.
Definition at line 14 of file NieveDialogue.java.
{
        Player player = factory.getPlayer();
        factory.sendNpcChat(6797, Expression.HAPPY, "Hello adventurer, how may I help you?").sendOption("Offer slayer items", () -> sell(factory), "Open slayer manager", () -> factory.onAction(() -> player.slayer.open(SlayerTab.MAIN)), "Nevermind", () -> factory.onAction(player.interfaceManager::close));
        factory.execute();
    }
References com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.dialogue.Expression.HAPPY, com.runehive.content.skill.impl.slayer.SlayerTab.MAIN, com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.content.skill.impl.slayer.Slayer.open(), sell(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.game.world.entity.mob.player.Player.slayer.
The documentation for this class was generated from the following file:
java/com/runehive/content/dialogue/impl/NieveDialogue.java