RuneHive-Game: com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility Class Reference
com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility Class Reference
This class handles util methods for the Warrior's activity.
Static Public Member Functions
static int contains (Player player, int itemId)
Checks if the player has a complete armour set to activate the animator.
static int getDefender (Player player)
Gets the defender index to drop for the player.
Static Public Attributes
static final int[] CYCLOPS = {2463, 2464, 2465, 2466, 2467, 2468}
The warrior guild cyclops npcs.
Static Package Functions
static int getDefenderIndex (Player player)
Gets the defender tier index.
Static Package Attributes
static final int[] ANIMATED = {2450, 2451, 2452, 2453, 2454, 2455, 2456}
The warrior guild animated npcs.
static final int[][] ARMOUR = {{1155, 1117, 1075}, {1153, 1115, 1067}, {1157, 1119, 1069}, {1165, 1125, 1077}, {1159, 1121, 1071}, {1161, 1123, 1073}, {1163, 1127, 1079}}
The warrior guild animator armour data .
Static Private Attributes
static final int[] DEFENDER = new int[]{8844, 8845, 8846, 8847, 8848, 8849, 8850, 12954}
The warrior guild defenders.
Detailed Description
This class handles util methods for the Warrior's activity.
Author
Daniel
Definition at line 11 of file WarriorGuildUtility.java.
Member Function Documentation
contains()
int com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.contains (Player player, int itemId) static
Checks if the player has a complete armour set to activate the animator.
Definition at line 48 of file WarriorGuildUtility.java.
{
        int itemIndex = -1;
        for (int index = 0; index < ARMOUR.length; index++) {
            for (int j = 0; j < ARMOUR[index].length; j++) {
                if (itemId == ARMOUR[index][j]) {
                    itemIndex = index;
                    for (int k = 0; k < ARMOUR[index].length; k++) {
                        if (!player.inventory.contains(ARMOUR[index][k])) {
                            player.send(new SendMessage("You need a complete armour set to do this!"));
                            return -1;
                        }
                    }
                    break;
                }
            }
        }
        return itemIndex;
    }
References ARMOUR, com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.inventory, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuild.useItem().
getDefender()
int com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefender (Player player) static
Gets the defender index to drop for the player.
Definition at line 36 of file WarriorGuildUtility.java.
{
        int foundIndex = -1;
        for (int i = 0; i < DEFENDER.length; i++) {
            if (player.inventory.contains(DEFENDER[i]) || player.equipment.contains(DEFENDER[i]))
                foundIndex = i;
        }
        if (foundIndex != 7)
            foundIndex++;
        return DEFENDER[foundIndex];
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), DEFENDER, com.runehive.game.world.entity.mob.player.Player.equipment, and com.runehive.game.world.entity.mob.player.Player.inventory.
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuild.pickupItem(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), and com.runehive.content.activity.impl.warriorguild.WarriorGuild.update().
getDefenderIndex()
int com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefenderIndex (Player player) static package
Gets the defender tier index.
Definition at line 26 of file WarriorGuildUtility.java.
{
        int foundIndex = 0;
        for (int index = 0; index < DEFENDER.length; index++) {
            if (player.inventory.contains(DEFENDER[index]) || player.equipment.contains(DEFENDER[index]))
                foundIndex = index;
        }
        return foundIndex;
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), DEFENDER, com.runehive.game.world.entity.mob.player.Player.equipment, and com.runehive.game.world.entity.mob.player.Player.inventory.
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuild.update().
Member Data Documentation
ANIMATED
final int [] com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.ANIMATED = {2450, 2451, 2452, 2453, 2454, 2455, 2456} static package
The warrior guild animated npcs.
Definition at line 20 of file WarriorGuildUtility.java.
{2450, 2451, 2452, 2453, 2454, 2455, 2456};
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuild.summon().
ARMOUR
final int [][] com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.ARMOUR = {{1155, 1117, 1075}, {1153, 1115, 1067}, {1157, 1119, 1069}, {1165, 1125, 1077}, {1159, 1121, 1071}, {1161, 1123, 1073}, {1163, 1127, 1079}} static package
The warrior guild animator armour data .
Definition at line 14 of file WarriorGuildUtility.java.
{{1155, 1117, 1075}, {1153, 1115, 1067}, {1157, 1119, 1069}, {1165, 1125, 1077}, {1159, 1121, 1071}, {1161, 1123, 1073}, {1163, 1127, 1079}};
Referenced by contains(), and com.runehive.content.activity.impl.warriorguild.WarriorGuild.summon().
CYCLOPS
final int [] com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.CYCLOPS = {2463, 2464, 2465, 2466, 2467, 2468} static
The warrior guild cyclops npcs.
Definition at line 23 of file WarriorGuildUtility.java.
{2463, 2464, 2465, 2466, 2467, 2468};
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuildActivityListener.canAttack(), and com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath().
DEFENDER
final int [] com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.DEFENDER = new int[]{8844, 8845, 8846, 8847, 8848, 8849, 8850, 12954} static private
The warrior guild defenders.
Definition at line 17 of file WarriorGuildUtility.java.
{8844, 8845, 8846, 8847, 8848, 8849, 8850, 12954};
Referenced by getDefender(), and getDefenderIndex().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/warriorguild/WarriorGuildUtility.java