RuneHive-Game: com.runehive.game.world.items.containers.impl.LostUntradeables Class Reference
com.runehive.game.world.items.containers.impl.LostUntradeables Class Reference
Handles the donator deposit box.
Public Member Functions
boolean claim (int slot, int id)
void close ()
boolean deposit (Item item)
LostUntradeables (Player player)
void onRefresh ()
Any functionality that should occur when refreshed.
void open ()
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainer
boolean add (int id, int amount)
Attempts to deposit item into this container.
boolean add (Item item)
Attempts to deposit item into this container.
boolean add (Item item, boolean refresh, boolean stack)
boolean add (Item item, int preferredIndex, boolean refresh)
boolean add (Item item, int preferredIndex, boolean refresh, boolean stack)
Attempts to deposit item into this container, preferably at preferredIndex.
boolean add (Item item, int slot)
Attempts to deposit item into this container.
boolean addAll (Collection<? extends Item > items)
Attempts to deposit items in bulk into this container.
boolean addAll (Item... items)
Attempts to deposit items in bulk into this container.
boolean addAll (ItemContainer items)
Attempts to deposit items in bulk into this container.
final boolean addListener (ItemContainerListener listener)
Adds an ItemContainerListener to this container.
boolean allowZero ()
final int capacity ()
void clear ()
Removes all of the items from this container.
final void clear (boolean refresh)
Removes all of the items from this container.
final int computeAmountForId (int id)
Computes the total quantity of the Items in this container with id.
final int computeFreeIndex ()
Computes the next free (null) index in this container.
final Optional< Integer > computeIdForIndex (int index)
Computes the identifier of the Item on index.
final int computeIndexCount (Item... forItems)
Computes the amount of indexes required to hold items in this container.
final int computeIndexForId (int id)
Computes the first index found that id is in.
long containerValue (PriceType type)
Gets the total worth of the container using the item's values.
boolean contains (int id)
Determines if this container contains id.
final boolean contains (int id, int amount)
final boolean contains (Item item)
final boolean containsAll (Collection< Item > items)
final boolean containsAll (int... identifiers)
Determines if this container contains all identifiers.
final boolean containsAll (Item... items)
final boolean containsAny (Collection< Item > items)
final boolean containsAny (int... identifiers)
Determines if this container contains any identifiers.
final boolean containsAny (Item... items)
final ItemContainer copy ()
Creates a copy of the underlying item container.
final void fireBulkItemsUpdatedEvent ()
Fires the ItemContainerListener.bulkItemsUpdated(ItemContainer) event.
final void fireCapacityExceededEvent ()
Fires the ItemContainerListener.capacityExceeded(ItemContainer) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh)
Fires the ItemContainerListener.itemUpdated(ItemContainer, int) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh, boolean login)
final void forEach (Consumer<? super Item > action)
Iterates through all of the Items within this container and performs action on them, skipping empty indexes (null values) as they are encountered.
final Item get (int index)
Gets the Item located on index.
int getFreeSlots ()
final int getId (int index)
Gets the item id located on index.
Item[] getItems ()
int getSlotById (int id)
Gets a slot by id.
double getWeight ()
Gets the weight of the container.
final boolean hasCapacityAfter (Item[] add, Item... remove)
Creates a copy of the underlying container and removes the items specified from it and after tries to deposit the specified items to it.
final boolean hasCapacityFor (Item... item)
Determines if this container has the capacity for item.
final void ifPresent (int index, Consumer< Item > action)
Consumes an action if the index is a valid item index in this container.
final boolean indexFree (int index)
Returns true if index is not occupied (null).
final boolean indexOccupied (int index)
Returns true if index is occupied (non-null).
final void insert (int oldIndex, int newIndex, boolean refresh)
final boolean isEmpty ()
final boolean isFull ()
ItemContainer (int capacity, StackPolicy policy)
Creates a new ItemContainer.
ItemContainer (int capacity, StackPolicy policy, Item[] items)
Creates a new ItemContainer.
final Iterator< Item > iterator ()
final StackPolicy policy ()
void refresh (Player player, int widget)
Sends the items on the itemcontainer.
final int remaining ()
boolean remove (int id)
boolean remove (int id, int amount)
boolean remove (Item item)
Attempts to withdraw item from this container.
boolean remove (Item item, int preferredIndex)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean remove (Item item, int preferredIndex, boolean refresh)
boolean remove (Item item, int preferredIndex, boolean refresh, boolean removeAll)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean removeAll (Collection<? extends Item > items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (Item... items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (ItemContainer items)
Attempts to withdraw items in bulk from this container.
final boolean removeListener (ItemContainerListener listener)
Removes an ItemContainerListener from this container.
final boolean replace (int oldId, int newId, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (int oldId, int newId, int index, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (Item first, Item second, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replaceAll (int oldId, int newId)
Replaces all occurrences of Items having the identifier
oldId with newId.
final Optional< Item > retrieve (int index)
Retrieves the item located on index.
Optional< Item > search (int id)
Searches and returns the first item found with id.
Optional< Item > search (Item item)
Searches and returns the first item found with id and
amount.
void set (int index, Item item, boolean refresh)
Sets the index to item.
final void set (Item[] toSet)
void setFiringEvents (boolean firingEvents)
Sets the value for firingEvents.
final void setItems (Item[] items)
final void setItems (Item[] items, boolean copy)
Sets the container of items to items.
void shift ()
Percolates the null indices to the end of the stack.
final int size ()
final Spliterator< Item > spliterator ()
final Stream< Item > stream ()
final void swap (boolean insert, int oldIndex, int newIndex, boolean refresh)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex, boolean refresh)
final Item[] toArray ()
Returns a shallow copy of the backing array.
final Item[] toNonNullArray ()
final void transfer (int firstIndex, int secondIndex, ItemContainer other, boolean refresh)
Private Member Functions
void refresh ()
Private Attributes
final Player player
Static Private Attributes
static final int DONATOR_DEPOSIT_BOX_DISPLAY_ID = 57307
Detailed Description
Handles the donator deposit box.
Author
DanielDonatorDeposit
Definition at line 17 of file LostUntradeables.java.
Constructor & Destructor Documentation
LostUntradeables()
com.runehive.game.world.items.containers.impl.LostUntradeables.LostUntradeables (Player player)
Definition at line 22 of file LostUntradeables.java.
{
        super(30, StackPolicy.ALWAYS);
        this.player = player;
    }
References com.runehive.game.world.items.containers.ItemContainer.StackPolicy.ALWAYS, and player.
Member Function Documentation
claim()
boolean com.runehive.game.world.items.containers.impl.LostUntradeables.claim (int slot, int id)
Definition at line 46 of file LostUntradeables.java.
{
        if (!player.interfaceManager.isInterfaceOpen(57300)) {
            return false;
        }
        Item item = get(slot);
        if (item == null || item.getId() != id) {
            return false;
        }
        if (player.inventory.getFreeSlots() == 0) {
            player.message("You do not have enough free inventory space!");
            return false;
        }
        if (!player.inventory.contains(13307, 350)) {
            player.message("You need 350 blood money to re-claim this item!");
            return false;
        }
        if (remove(item.getId(), 1)) {
            player.inventory.add(id, 1);
            player.inventory.remove(13307, 350);
            shift();
            refresh();
        }
        return true;
    }
References com.runehive.game.world.items.Item.getId(), player, refresh(), and com.runehive.game.world.items.containers.ItemContainer.shift().
close()
void com.runehive.game.world.items.containers.impl.LostUntradeables.close ()
Definition at line 32 of file LostUntradeables.java.
{
        clear(false);
        refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.clear(), and refresh().
deposit()
boolean com.runehive.game.world.items.containers.impl.LostUntradeables.deposit (Item item)
Definition at line 37 of file LostUntradeables.java.
{
        int id = item.getId();
        setFiringEvents(false);
        add(id, item.getAmount());
        setFiringEvents(true);
        refresh();
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), refresh(), and com.runehive.game.world.items.containers.ItemContainer.setFiringEvents().
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems().
onRefresh()
void com.runehive.game.world.items.containers.impl.LostUntradeables.onRefresh ()
Any functionality that should occur when refreshed.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 81 of file LostUntradeables.java.
{
        player.inventory.refresh();
        player.send(new SendString(this.size() + "/" + this.capacity(), 57306));
        player.send(new SendItemOnInterface(DONATOR_DEPOSIT_BOX_DISPLAY_ID, getItems()));
    }
References com.runehive.game.world.items.containers.ItemContainer.capacity, DONATOR_DEPOSIT_BOX_DISPLAY_ID, com.runehive.game.world.items.containers.ItemContainer.getItems(), player, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.items.containers.ItemContainer.size().
open()
void com.runehive.game.world.items.containers.impl.LostUntradeables.open ()
Definition at line 27 of file LostUntradeables.java.
                       {
        refresh();
        player.interfaceManager.open(57300);
    }
References player, and refresh().
refresh()
void com.runehive.game.world.items.containers.impl.LostUntradeables.refresh () private
Definition at line 76 of file LostUntradeables.java.
{
        refresh(player, DONATOR_DEPOSIT_BOX_DISPLAY_ID);
    }
References DONATOR_DEPOSIT_BOX_DISPLAY_ID, player, and refresh().
Referenced by claim(), close(), deposit(), open(), and refresh().
Member Data Documentation
DONATOR_DEPOSIT_BOX_DISPLAY_ID
final int com.runehive.game.world.items.containers.impl.LostUntradeables.DONATOR_DEPOSIT_BOX_DISPLAY_ID = 57307 static private
Definition at line 18 of file LostUntradeables.java.
Referenced by onRefresh(), and refresh().
player
final Player com.runehive.game.world.items.containers.impl.LostUntradeables.player private
Definition at line 20 of file LostUntradeables.java.
Referenced by claim(), LostUntradeables(), onRefresh(), open(), and refresh().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/impl/LostUntradeables.java