RuneHive-Game: com.runehive.content.famehall.FameHandler Class Reference
com.runehive.content.famehall.FameHandler Class Reference
This class handles the fame system.
Static Public Member Functions
static void activate (Player player, FameEntry fameEntry)
Checks if player should be entered in the hall of fame.
static Map< FameEntry, Fame > getEntries (FameType type)
Filters the hall of fame entries for a certain fame type.
static void load ()
Loads the hall of fames and puts them into the map.
static void open (Player player, FameType type)
Opens the hall of fame itemcontainer.
static void remove (FameEntry fameEntry)
Removes a fame entry from the hall of fame.
static void save ()
Saves the hall of fames into a json file.
static void search (Player player, String context)
Searches through all the fame entries for a specific player.
Static Public Attributes
static Map< FameEntry, Fame > HALL_OF_FAME = new HashMap<>()
Holds the hall of fame entries.
Static Private Member Functions
static Fame getEntry (FameEntry entry)
Gets the fame by the fame entry.
Detailed Description
This class handles the fame system.
Author
Daniel
Definition at line 29 of file FameHandler.java.
Member Function Documentation
activate()
void com.runehive.content.famehall.FameHandler.activate (Player player, FameEntry fameEntry) static
Checks if player should be entered in the hall of fame.
Parameters
player The player instance.
fameEntry The fame entry.
Definition at line 42 of file FameHandler.java.
{
        if (!HALL_OF_FAME.containsKey(fameEntry)) {
            HALL_OF_FAME.put(fameEntry, new Fame(fameEntry.getType(), PlayerRight.getCrown(player) + " " + player.getName(), Utility.getDate()));
            player.send(new SendMessage("Congratulations, you have left your mark on the hall of fame!"));
            World.sendBroadcast(1, player.getName() + " is now on the hall of fame for " + fameEntry.getEntry(), false);
            save();
        }
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.util.Utility.getDate(), com.runehive.content.famehall.FameEntry.getEntry(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.famehall.FameEntry.getType(), HALL_OF_FAME, save(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.World.sendBroadcast().
getEntries()
Map< FameEntry, Fame > com.runehive.content.famehall.FameHandler.getEntries (FameType type) static
Filters the hall of fame entries for a certain fame type.
Parameters
type The fame type to filer.
Returns
Map of all the entries.
Definition at line 69 of file FameHandler.java.
{
        Map<FameEntry, Fame> hall = new HashMap<>();
        for (Entry<FameEntry, Fame> entries : HALL_OF_FAME.entrySet()) {
            if (entries.getKey().getType() == type)
                hall.put(entries.getKey(), entries.getValue());
        }
        return hall;
    }
References HALL_OF_FAME.
Referenced by getEntry().
getEntry()
Fame com.runehive.content.famehall.FameHandler.getEntry (FameEntry entry) static private
Gets the fame by the fame entry.
Parameters
entry The entry to get.
Returns
The fame.
Definition at line 85 of file FameHandler.java.
{
        Fame result = null;
        for (Entry<FameEntry, Fame> fame : getEntries(entry.getType()).entrySet()) {
            if (fame.getKey().name().equalsIgnoreCase(entry.name())) {
                result = fame.getValue();
                break;
            }
        }
        return result;
    }
References getEntries(), and com.runehive.content.famehall.FameEntry.getType().
Referenced by open().
load()
void com.runehive.content.famehall.FameHandler.load () static
Loads the hall of fames and puts them into the map.
Definition at line 157 of file FameHandler.java.
{
        Type type = new TypeToken<Map<FameEntry, Fame>>() {
        }.getType();
        Path path = Paths.get("data", "/content/fame/hall_of_fame_list.json");
        try (FileReader reader = new FileReader(path.toFile())) {
            JsonParser parser = new JsonParser();
            HALL_OF_FAME = new GsonBuilder().create().fromJson(parser.parse(reader), type);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
References HALL_OF_FAME.
open()
void com.runehive.content.famehall.FameHandler.open (Player player, FameType type) static
Opens the hall of fame itemcontainer.
Parameters
player The player instance.
type The fame type tab.
Definition at line 104 of file FameHandler.java.
{
        int string = 58533;
        List<FameEntry> entry_list = FameEntry.getEntries(type);
        Item[] items = new Item[entry_list.size()];
        for (int index = 0; index < entry_list.size(); index++) {
            FameEntry display = entry_list.get(index);
            Fame fame = getEntry(display);
            items[index] = new Item(display.getDisplay());
            player.send(new SendString(display == null ? "" : display.getEntry(), string));
            string++;
            player.send(new SendString(fame == null ? "---" : fame.getName(), string));
            string++;
            player.send(new SendString(fame == null ? "---" : fame.getAccomplished(), string));
            string++;
            string++;
        }
        player.send(new SendConfig(1150, type.ordinal()));
        player.send(new SendString(HALL_OF_FAME.size() + "/" + FameEntry.values().length + " Remaining", 58523));
        player.send(new SendString("<col=" + (type.ordinal() == 0 ? "ffffff" : "ff9933") + ">Player Killing", 58515));
        player.send(new SendString("<col=" + (type.ordinal() == 1 ? "ffffff" : "ff9933") + ">Monster Killing", 58516));
        player.send(new SendString("<col=" + (type.ordinal() == 2 ? "ffffff" : "ff9933") + ">Skilling", 58517));
        player.send(new SendString("<col=" + (type.ordinal() == 3 ? "ffffff" : "ff9933") + ">Miscellaneous", 58518));
        player.send(new SendItemOnInterface(58531, items));
        player.send(new SendScrollbar(58530, (entry_list.size() * 34)));
        player.interfaceManager.open(58500);
    }
References com.runehive.content.famehall.Fame.getAccomplished(), com.runehive.content.famehall.FameEntry.getDisplay(), com.runehive.content.famehall.FameEntry.getEntries(), com.runehive.content.famehall.FameEntry.getEntry(), getEntry(), com.runehive.content.famehall.Fame.getName(), HALL_OF_FAME, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), and com.runehive.game.world.entity.mob.player.Player.send().
remove()
void com.runehive.content.famehall.FameHandler.remove (FameEntry fameEntry) static
Removes a fame entry from the hall of fame.
Parameters
fameEntry The fame entry to withdraw.
Definition at line 57 of file FameHandler.java.
{
        if (HALL_OF_FAME.containsKey(fameEntry))
            HALL_OF_FAME.remove(fameEntry);
    }
References HALL_OF_FAME.
save()
void com.runehive.content.famehall.FameHandler.save () static
Saves the hall of fames into a json file.
Definition at line 173 of file FameHandler.java.
{
        Gson gson = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();
        try (FileWriter fw = new FileWriter("./data/content/fame/hall_of_fame_list.json")) {
            fw.write(gson.toJson(HALL_OF_FAME));
        } catch (final Exception e) {
            e.printStackTrace();
        }
    }
References HALL_OF_FAME.
Referenced by activate().
search()
void com.runehive.content.famehall.FameHandler.search (Player player, String context) static
Searches through all the fame entries for a specific player.
Parameters
player The player instance.
context The context being searched.
Definition at line 142 of file FameHandler.java.
{
        int index = 0;
        for (Entry<FameEntry, Fame> entries : HALL_OF_FAME.entrySet()) {
            if (entries.getValue().getName().equalsIgnoreCase(context)) {
                index++;
            }
        }
        String message = index == 0 ? Utility.formatName(context) + " was not found in the hall of fame." : index + " entries were found in the hall of fame for " + Utility.formatName(context) + ".";
        player.send(new SendMessage(message));
    }
References com.runehive.util.Utility.formatName(), HALL_OF_FAME, and com.runehive.game.world.entity.mob.player.Player.send().
Member Data Documentation
HALL_OF_FAME
Map<FameEntry, Fame> com.runehive.content.famehall.FameHandler.HALL_OF_FAME = new HashMap<>() static
Holds the hall of fame entries.
Definition at line 32 of file FameHandler.java.
Referenced by activate(), getEntries(), load(), open(), remove(), save(), and search().
The documentation for this class was generated from the following file:
java/com/runehive/content/famehall/FameHandler.java