RuneHive-Game: com.runehive.content.activity.impl.pestcontrol.PestControlLobby Class Reference
com.runehive.content.activity.impl.pestcontrol.PestControlLobby Class Reference
A PestControlLobby manages all the PestControlGame that are active.
Static Public Member Functions
static void joinBoat (Player player)
Joins a Player into a PestControlGame lobby.
static void sequence ()
Sequences all the active PestControlGame.
Protected Member Functions
LobbyNode createLobby ()
void exceededGameCapacity (Player player)
void exceededPlayerCapacity (Player player)
void onEnter (Player player)
void onLeave (Player player)
Protected Member Functions inherited from com.runehive.content.activity.lobby.LobbyManager
LobbyManager (int gameCapacity, int playerCapacity, int minimumRequired, int lobbyCooldown, int gameCooldown)
Private Member Functions
PestControlLobby ()
Constructs a new PestControlLobby.
Static Private Attributes
static final int GAME_CAPACITY = 1
The active game limit.
static final int GAME_COOLDOWN = 1000
The game cooldown timer in ticks (10 minutes).
static final Position INSIDE_BOAT_POSITION = new Position(2661, 2639)
The position inside the pest control boat.
static final int LOBBY_COOLDOWN = 50
The lobby cooldown timer in ticks (30 seconds).
static final int MINIMUM_PLAYERS = 3
The minimum amount of players required to start.
static final PestControlLobby PEST_CONTROL = new PestControlLobby()
The pest control instance, used for managing all activities.
static final int PLAYER_CAPACITY = 25
The player capacity.
Additional Inherited Members
Public Member Functions inherited from com.runehive.content.activity.lobby.LobbyManager
boolean canStart (LobbyNode node)
final void enter (Player player)
int getGameCapacity ()
int getGameCooldown ()
int getLobbyCooldown ()
int getMinimumRequired ()
int getPlayerCapacity ()
final void leave (Player player)
final void sequenceActive ()
Detailed Description
A PestControlLobby manages all the PestControlGame that are active.
Author
Michael | Chex
Definition at line 14 of file PestControlLobby.java.
Constructor & Destructor Documentation
PestControlLobby()
com.runehive.content.activity.impl.pestcontrol.PestControlLobby.PestControlLobby () private
Constructs a new PestControlLobby.
Definition at line 38 of file PestControlLobby.java.
{
        super(GAME_CAPACITY, PLAYER_CAPACITY, MINIMUM_PLAYERS, LOBBY_COOLDOWN, GAME_COOLDOWN);
    }
References GAME_CAPACITY, GAME_COOLDOWN, LOBBY_COOLDOWN, MINIMUM_PLAYERS, and PLAYER_CAPACITY.
Member Function Documentation
createLobby()
LobbyNode com.runehive.content.activity.impl.pestcontrol.PestControlLobby.createLobby () protected
Reimplemented from com.runehive.content.activity.lobby.LobbyManager.
Definition at line 78 of file PestControlLobby.java.
{
        return new PestControlGame(PEST_CONTROL);
    }
References PEST_CONTROL.
exceededGameCapacity()
void com.runehive.content.activity.impl.pestcontrol.PestControlLobby.exceededGameCapacity (Player player) protected
Reimplemented from com.runehive.content.activity.lobby.LobbyManager.
Definition at line 73 of file PestControlLobby.java.
{
        player.message("A game is already active. Please wait for the next boat to depart.");
    }
References com.runehive.game.world.entity.mob.player.Player.message().
exceededPlayerCapacity()
void com.runehive.content.activity.impl.pestcontrol.PestControlLobby.exceededPlayerCapacity (Player player) protected
Reimplemented from com.runehive.content.activity.lobby.LobbyManager.
Definition at line 68 of file PestControlLobby.java.
{
        player.message("This boat doesn't need any more players.");
    }
References com.runehive.game.world.entity.mob.player.Player.message().
joinBoat()
void com.runehive.content.activity.impl.pestcontrol.PestControlLobby.joinBoat (Player player) static
Joins a Player into a PestControlGame lobby.
Parameters
player the player who is joining
Definition at line 47 of file PestControlLobby.java.
{
        PEST_CONTROL.enter(player);
    }
References PEST_CONTROL.
onEnter()
void com.runehive.content.activity.impl.pestcontrol.PestControlLobby.onEnter (Player player) protected
Reimplemented from com.runehive.content.activity.lobby.LobbyManager.
Definition at line 57 of file PestControlLobby.java.
{
        player.move(INSIDE_BOAT_POSITION);
        player.message(true, "You have entered the pest control boat.");
    }
References INSIDE_BOAT_POSITION, com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.entity.mob.Mob.move().
onLeave()
void com.runehive.content.activity.impl.pestcontrol.PestControlLobby.onLeave (Player player) protected
Reimplemented from com.runehive.content.activity.lobby.LobbyManager.
Definition at line 63 of file PestControlLobby.java.
{
        player.message(true, "You have left the pest control waiting boat.");
    }
References com.runehive.game.world.entity.mob.player.Player.message().
sequence()
void com.runehive.content.activity.impl.pestcontrol.PestControlLobby.sequence () static
Sequences all the active PestControlGame.
Definition at line 52 of file PestControlLobby.java.
{
        PEST_CONTROL.sequenceActive();
    }
References PEST_CONTROL.
Referenced by com.runehive.game.world.World.process().
Member Data Documentation
GAME_CAPACITY
final int com.runehive.content.activity.impl.pestcontrol.PestControlLobby.GAME_CAPACITY = 1 static private
The active game limit.
Definition at line 20 of file PestControlLobby.java.
Referenced by PestControlLobby().
GAME_COOLDOWN
final int com.runehive.content.activity.impl.pestcontrol.PestControlLobby.GAME_COOLDOWN = 1000 static private
The game cooldown timer in ticks (10 minutes).
Definition at line 29 of file PestControlLobby.java.
Referenced by PestControlLobby().
INSIDE_BOAT_POSITION
final Position com.runehive.content.activity.impl.pestcontrol.PestControlLobby.INSIDE_BOAT_POSITION = new Position(2661, 2639) static private
The position inside the pest control boat.
Definition at line 35 of file PestControlLobby.java.
Referenced by onEnter().
LOBBY_COOLDOWN
final int com.runehive.content.activity.impl.pestcontrol.PestControlLobby.LOBBY_COOLDOWN = 50 static private
The lobby cooldown timer in ticks (30 seconds).
Definition at line 26 of file PestControlLobby.java.
Referenced by PestControlLobby().
MINIMUM_PLAYERS
final int com.runehive.content.activity.impl.pestcontrol.PestControlLobby.MINIMUM_PLAYERS = 3 static private
The minimum amount of players required to start.
Definition at line 32 of file PestControlLobby.java.
Referenced by PestControlLobby().
PEST_CONTROL
final PestControlLobby com.runehive.content.activity.impl.pestcontrol.PestControlLobby.PEST_CONTROL = new PestControlLobby() static private
The pest control instance, used for managing all activities.
Definition at line 17 of file PestControlLobby.java.
Referenced by createLobby(), joinBoat(), and sequence().
PLAYER_CAPACITY
final int com.runehive.content.activity.impl.pestcontrol.PestControlLobby.PLAYER_CAPACITY = 25 static private
The player capacity.
Definition at line 23 of file PestControlLobby.java.
Referenced by PestControlLobby().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/pestcontrol/PestControlLobby.java