RuneHive-Game: com.runehive.util.Words Class Reference
com.runehive.util.Words Class Reference
This class specially written to convert the given number into words.
Public Member Functions
String belowBillion (long x)
String belowCrore (long x)
long getNumber ()
String getNumberInWords ()
long leftChars (int n)
long leftChars (long num, int n)
int length (long num)
long rightChars (int n)
long rightChars (long num, int n)
void setNumber (long num)
Static Public Member Functions
static Words getInstance (long num)
static String leftChars (String str, int n)
static String rightChars (String str, int n)
Package Attributes
long num
Private Member Functions
String belowHundred (long x)
String belowLakh (long x)
String belowTen (long x)
String belowThousand (long x)
String belowTwenty (long x)
Words ()
Words (long num)
Detailed Description
This class specially written to convert the given number into words.
It will support upto 1 crore.
Author
SANTHOSH REDDY MANDADI
Version
release: 2_0_48
Since
April 03 2008
Definition at line 11 of file Words.java.
Constructor & Destructor Documentation
Words() [1/2]
com.runehive.util.Words.Words () private
Definition at line 14 of file Words.java.
                    {
        num = 0;
    }
References num.
Referenced by getInstance().
Words() [2/2]
com.runehive.util.Words.Words (long num) private
Definition at line 18 of file Words.java.
{
        this.num = num;
    }
References num.
Member Function Documentation
belowBillion()
String com.runehive.util.Words.belowBillion (long x)
Definition at line 188 of file Words.java.
{
        if (x < 10)
            return belowTen(x);
        else if (x < 20)
            return belowTwenty(x);
        else if (x < 100)
            return belowHundred(x);
        else if (x < 1000)
            return belowThousand(x);
        else if (x < 100000)
            return belowLakh(x);
        else if (x < 100000000)
            return belowCrore(x);
        if (length(x) == 8)
            return belowTen(leftChars(x, 1)) + "Bilion " + belowCrore(rightChars(x, 7));
        else
            return belowHundred(leftChars(x, 2)) + "Bilion " + belowCrore(rightChars(x, 7));
    }
References belowCrore(), belowHundred(), belowLakh(), belowTen(), belowThousand(), belowTwenty(), leftChars(), length(), and rightChars().
Referenced by getNumberInWords().
belowCrore()
String com.runehive.util.Words.belowCrore (long x)
Definition at line 171 of file Words.java.
{
        if (x < 10)
            return belowTen(x);
        else if (x < 20)
            return belowTwenty(x);
        else if (x < 100)
            return belowHundred(x);
        else if (x < 1000)
            return belowThousand(x);
        else if (x < 100000)
            return belowLakh(x);
        if (length(x) == 6)
            return belowTen(leftChars(x, 1)) + "Lakh " + belowLakh(rightChars(x, 5));
        else
            return belowHundred(leftChars(x, 2)) + "Lakh " + belowLakh(rightChars(x, 5));
    }
References belowHundred(), belowLakh(), belowTen(), belowThousand(), belowTwenty(), leftChars(), length(), and rightChars().
Referenced by belowBillion(), and getNumberInWords().
belowHundred()
String com.runehive.util.Words.belowHundred (long x) private
Definition at line 120 of file Words.java.
{
        if (x < 10)
            return belowTen(x);
        else if (x < 20)
            return belowTwenty(x);
        switch ((int) leftChars(x, 1)) {
        case 2:
            return "Twenty " + belowTen(rightChars(x, 1));
        case 3:
            return "Thirty " + belowTen(rightChars(x, 1));
        case 4:
            return "Fourty " + belowTen(rightChars(x, 1));
        case 5:
            return "Fifty " + belowTen(rightChars(x, 1));
        case 6:
            return "Sixty " + belowTen(rightChars(x, 1));
        case 7:
            return "Seventy " + belowTen(rightChars(x, 1));
        case 8:
            return "Eighty " + belowTen(rightChars(x, 1));
        case 9:
            return "Ninety " + belowTen(rightChars(x, 1));
        }
        return "";
    }
References belowTen(), belowTwenty(), leftChars(), and rightChars().
Referenced by belowBillion(), belowCrore(), belowLakh(), belowThousand(), and getNumberInWords().
belowLakh()
String com.runehive.util.Words.belowLakh (long x) private
Definition at line 156 of file Words.java.
{
        if (x < 10)
            return belowTen(x);
        else if (x < 20)
            return belowTwenty(x);
        else if (x < 100)
            return belowHundred(x);
        else if (x < 1000)
            return belowThousand(x);
        if (length(x) == 4)
            return belowTen(leftChars(x, 1)) + "Thousand " + belowThousand(rightChars(x, 3));
        else
            return belowHundred(leftChars(x, 2)) + "Thousand " + belowThousand(rightChars(x, 3));
    }
References belowHundred(), belowTen(), belowThousand(), belowTwenty(), leftChars(), length(), and rightChars().
Referenced by belowBillion(), belowCrore(), and getNumberInWords().
belowTen()
String com.runehive.util.Words.belowTen (long x) private
Definition at line 68 of file Words.java.
{
        switch ((int) x) {
        case 1:
            return "One ";
        case 2:
            return "Two ";
        case 3:
            return "Three ";
        case 4:
            return "Four ";
        case 5:
            return "Five ";
        case 6:
            return "Six ";
        case 7:
            return "Seven ";
        case 8:
            return "Eight ";
        case 9:
            return "Nine ";
        }
        return "";
    }
Referenced by belowBillion(), belowCrore(), belowHundred(), belowLakh(), belowThousand(), belowTwenty(), and getNumberInWords().
belowThousand()
String com.runehive.util.Words.belowThousand (long x) private
Definition at line 146 of file Words.java.
{
        if (x < 10)
            return belowTen(x);
        else if (x < 20)
            return belowTwenty(x);
        else if (x < 100)
            return belowHundred(x);
        return belowTen(leftChars(x, 1)) + "Hundred " + belowHundred(rightChars(x, 2));
    }
References belowHundred(), belowTen(), belowTwenty(), leftChars(), and rightChars().
Referenced by belowBillion(), belowCrore(), belowLakh(), and getNumberInWords().
belowTwenty()
String com.runehive.util.Words.belowTwenty (long x) private
Definition at line 92 of file Words.java.
{
        if (x < 10)
            return belowTen(x);
        switch ((int) x) {
        case 10:
            return "Ten ";
        case 11:
            return "Eleven ";
        case 12:
            return "Twelve ";
        case 13:
            return "Thirteen ";
        case 14:
            return "Fourteen ";
        case 15:
            return "Fifteen ";
        case 16:
            return "Sixteen ";
        case 17:
            return "Seventeen ";
        case 18:
            return "Eighteen ";
        case 19:
            return "Nineteen ";
        }
        return "";
    }
References belowTen().
Referenced by belowBillion(), belowCrore(), belowHundred(), belowLakh(), belowThousand(), and getNumberInWords().
getInstance()
Words com.runehive.util.Words.getInstance (long num) static
Definition at line 30 of file Words.java.
{
        return new Words(num);
    }
References num, and Words().
Referenced by com.runehive.util.Utility.convertWord().
getNumber()
long com.runehive.util.Words.getNumber ()
Definition at line 26 of file Words.java.
{
        return num;
    }
References num.
getNumberInWords()
String com.runehive.util.Words.getNumberInWords ()
Definition at line 208 of file Words.java.
{
        if (num < 10)
            return belowTen(num);
        else if (num < 20)
            return belowTwenty(num);
        else if (num < 100)
            return belowHundred(num);
        else if (num < 1000)
            return belowThousand(num);
        else if (num < 100000)
            return belowLakh(num);
        else if (num < 10000000)
            return belowCrore(num);
        else if (num < 1000000000)
            return belowBillion(num);
        return "";
    }
References belowBillion(), belowCrore(), belowHundred(), belowLakh(), belowTen(), belowThousand(), belowTwenty(), and num.
Referenced by com.runehive.util.Utility.convertWord().
leftChars() [1/3]
long com.runehive.util.Words.leftChars (int n)
Definition at line 48 of file Words.java.
{
        return Long.parseLong(leftChars(Long.toString(num), n));
    }
References leftChars(), and num.
leftChars() [2/3]
long com.runehive.util.Words.leftChars (long num, int n)
Definition at line 56 of file Words.java.
{
        return Long.parseLong(leftChars(Long.toString(num), n));
    }
References leftChars(), and num.
leftChars() [3/3]
String com.runehive.util.Words.leftChars (String str, int n) static
Definition at line 34 of file Words.java.
{
        if (str.length() <= n)
            return str;
        else
            return str.substring(0, n);
    }
Referenced by belowBillion(), belowCrore(), belowHundred(), belowLakh(), belowThousand(), leftChars(), and leftChars().
length()
int com.runehive.util.Words.length (long num)
Definition at line 64 of file Words.java.
{
        return Long.toString(num).length();
    }
References num.
Referenced by belowBillion(), belowCrore(), and belowLakh().
rightChars() [1/3]
long com.runehive.util.Words.rightChars (int n)
Definition at line 52 of file Words.java.
{
        return Long.parseLong(rightChars(Long.toString(num), n));
    }
References num, and rightChars().
rightChars() [2/3]
long com.runehive.util.Words.rightChars (long num, int n)
Definition at line 60 of file Words.java.
{
        return Long.parseLong(rightChars(Long.toString(num), n));
    }
References num, and rightChars().
rightChars() [3/3]
String com.runehive.util.Words.rightChars (String str, int n) static
Definition at line 41 of file Words.java.
{
        if (str.length() <= n)
            return str;
        else
            return str.substring(str.length() - n);
    }
Referenced by belowBillion(), belowCrore(), belowHundred(), belowLakh(), belowThousand(), rightChars(), and rightChars().
setNumber()
void com.runehive.util.Words.setNumber (long num)
Definition at line 22 of file Words.java.
{
        this.num = num;
    }
References num.
Member Data Documentation
num
long com.runehive.util.Words.num package
Definition at line 12 of file Words.java.
Referenced by getInstance(), getNumber(), getNumberInWords(), leftChars(), leftChars(), length(), rightChars(), rightChars(), setNumber(), Words(), and Words().
The documentation for this class was generated from the following file:
java/com/runehive/util/Words.java