RuneHive-Game: com.runehive.game.Projectile Class Reference
com.runehive.game.Projectile Class Reference
Public Member Functions
Projectile copy ()
int getClientTicks ()
int getCurve ()
int getDelay ()
int getDistance ()
int getDuration ()
int getEndHeight ()
int getId ()
int getOffsetX ()
int getOffsetY ()
int getStartHeight ()
Projectile (int id)
Projectile (int id, int delay, int duration, int startHeight, int endHeight)
Projectile (int id, int delay, int duration, int startHeight, int endHeight, int curve)
Projectile (int id, int delay, int duration, int startHeight, int endHeight, int curve, int distance)
Projectile (int id, int delay, int duration, int startHeight, int endHeight, int curve, int distance, int offsetX, int offsetY)
void send (Mob source, Mob target)
void send (Mob source, Position target)
void setCurve (int curve)
void setDelay (int delay)
void setDistance (int distance)
void setDuration (int duration)
void setEndHeight (int endHeight)
void setId (int id)
void setOffsetX (int offsetX)
void setOffsetY (int offsetY)
void setStartHeight (int startHeight)
Static Public Attributes
static final int[] MAGIC_DELAYS = { 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5 }
Magic combat projectile delays.
static final int[] RANGED_DELAYS = { 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4 }
Ranged combat projectile delays.
Private Attributes
int curve
int delay
int distance
int duration
int endHeight
int id
int offsetX
int offsetY
int startHeight
Detailed Description
Definition at line 7 of file Projectile.java.
Constructor & Destructor Documentation
Projectile() [1/5]
com.runehive.game.Projectile.Projectile (int id, int delay, int duration, int startHeight, int endHeight, int curve, int distance, int offsetX, int offsetY)
Definition at line 25 of file Projectile.java.
{
        setId(id);
        setDelay(delay);
        setDuration(duration);
        setStartHeight(startHeight);
        setEndHeight(endHeight);
        setCurve(curve);
        setDistance(distance);
        setOffsetX(offsetX);
        setOffsetY(offsetY);
    }
References curve, delay, distance, duration, endHeight, offsetX, offsetY, setCurve(), setDelay(), setDistance(), setDuration(), setEndHeight(), setId(), setOffsetX(), setOffsetY(), setStartHeight(), and startHeight.
Projectile() [2/5]
com.runehive.game.Projectile.Projectile (int id, int delay, int duration, int startHeight, int endHeight, int curve, int distance)
Definition at line 37 of file Projectile.java.
{
        this(id, delay, duration, startHeight, endHeight, curve, distance, 0, 0);
    }
References curve, delay, distance, duration, endHeight, id, and startHeight.
Projectile() [3/5]
com.runehive.game.Projectile.Projectile (int id, int delay, int duration, int startHeight, int endHeight, int curve)
Definition at line 41 of file Projectile.java.
{
        this(id, delay, duration, startHeight, endHeight, curve, 64);
    }
References curve, delay, duration, endHeight, id, and startHeight.
Projectile() [4/5]
com.runehive.game.Projectile.Projectile (int id, int delay, int duration, int startHeight, int endHeight)
Definition at line 45 of file Projectile.java.
{
        this(id, delay, duration, startHeight, endHeight, 16);
    }
References delay, duration, endHeight, id, and startHeight.
Projectile() [5/5]
com.runehive.game.Projectile.Projectile (int id)
Definition at line 49 of file Projectile.java.
{
        this(id, 51, 68, 43, 31);
    }
References id.
Member Function Documentation
copy()
Projectile com.runehive.game.Projectile.copy ()
Definition at line 133 of file Projectile.java.
{
        return new Projectile(id, delay, duration, startHeight, endHeight, curve, distance, offsetX, offsetY);
    }
References curve, delay, distance, duration, endHeight, offsetX, offsetY, and startHeight.
getClientTicks()
int com.runehive.game.Projectile.getClientTicks ()
Definition at line 137 of file Projectile.java.
{
        return /*getDelay() + */getDuration();
    }
References getDuration().
getCurve()
int com.runehive.game.Projectile.getCurve ()
Definition at line 101 of file Projectile.java.
{
        return curve;
    }
References curve.
getDelay()
int com.runehive.game.Projectile.getDelay ()
Definition at line 69 of file Projectile.java.
{
        return delay;
    }
References delay.
getDistance()
int com.runehive.game.Projectile.getDistance ()
Definition at line 109 of file Projectile.java.
{
        return distance;
    }
References distance.
getDuration()
int com.runehive.game.Projectile.getDuration ()
Definition at line 77 of file Projectile.java.
{
        return duration;
    }
References duration.
Referenced by getClientTicks(), and com.runehive.game.world.entity.combat.ranged.RangedAmmunition.sendProjectile().
getEndHeight()
int com.runehive.game.Projectile.getEndHeight ()
Definition at line 93 of file Projectile.java.
{
        return endHeight;
    }
References endHeight.
getId()
int com.runehive.game.Projectile.getId ()
Definition at line 61 of file Projectile.java.
                       {
        return id;
    }
References id.
getOffsetX()
int com.runehive.game.Projectile.getOffsetX ()
Definition at line 117 of file Projectile.java.
{
        return offsetX;
    }
References offsetX.
getOffsetY()
int com.runehive.game.Projectile.getOffsetY ()
Definition at line 125 of file Projectile.java.
{
        return offsetY;
    }
References offsetY.
getStartHeight()
int com.runehive.game.Projectile.getStartHeight ()
Definition at line 85 of file Projectile.java.
{
        return startHeight;
    }
References startHeight.
send() [1/2]
void com.runehive.game.Projectile.send (Mob source, Mob target)
Definition at line 53 of file Projectile.java.
{
        World.sendProjectile(source, target, this);
    }
References com.runehive.game.world.World.sendProjectile().
Referenced by com.runehive.game.world.entity.combat.ranged.RangedAmmunition.sendProjectile().
send() [2/2]
void com.runehive.game.Projectile.send (Mob source, Position target)
Definition at line 57 of file Projectile.java.
{
        World.sendProjectile(source, target, this);
    }
References com.runehive.game.world.World.sendProjectile().
setCurve()
void com.runehive.game.Projectile.setCurve (int curve)
Definition at line 105 of file Projectile.java.
{
        this.curve = curve;
    }
References curve.
Referenced by Projectile(), and com.runehive.game.world.entity.combat.ranged.RangedAmmunition.sendProjectile().
setDelay()
void com.runehive.game.Projectile.setDelay (int delay)
Definition at line 73 of file Projectile.java.
{
        this.delay = delay;
    }
References delay.
Referenced by Projectile().
setDistance()
void com.runehive.game.Projectile.setDistance (int distance)
Definition at line 113 of file Projectile.java.
{
        this.distance = distance;
    }
References distance.
Referenced by Projectile().
setDuration()
void com.runehive.game.Projectile.setDuration (int duration)
Definition at line 81 of file Projectile.java.
{
        this.duration = duration;
    }
References duration.
Referenced by Projectile(), and com.runehive.game.world.entity.combat.ranged.RangedAmmunition.sendProjectile().
setEndHeight()
void com.runehive.game.Projectile.setEndHeight (int endHeight)
Definition at line 97 of file Projectile.java.
{
        this.endHeight = endHeight;
    }
References endHeight.
Referenced by com.runehive.content.combat.cannon.CannonManager.getCannonFire(), and Projectile().
setId()
void com.runehive.game.Projectile.setId (int id)
Definition at line 65 of file Projectile.java.
{
        this.id = id;
    }
References id.
Referenced by Projectile().
setOffsetX()
void com.runehive.game.Projectile.setOffsetX (int offsetX)
Definition at line 121 of file Projectile.java.
{
        this.offsetX = offsetX;
    }
References offsetX.
Referenced by Projectile().
setOffsetY()
void com.runehive.game.Projectile.setOffsetY (int offsetY)
Definition at line 129 of file Projectile.java.
{
        this.offsetY = offsetY;
    }
References offsetY.
Referenced by Projectile().
setStartHeight()
void com.runehive.game.Projectile.setStartHeight (int startHeight)
Definition at line 89 of file Projectile.java.
{
        this.startHeight = startHeight;
    }
References startHeight.
Referenced by com.runehive.content.combat.cannon.CannonManager.getCannonFire(), and Projectile().
Member Data Documentation
curve
int com.runehive.game.Projectile.curve private
Definition at line 20 of file Projectile.java.
Referenced by copy(), getCurve(), Projectile(), Projectile(), Projectile(), and setCurve().
delay
int com.runehive.game.Projectile.delay private
Definition at line 16 of file Projectile.java.
Referenced by copy(), getDelay(), Projectile(), Projectile(), Projectile(), Projectile(), and setDelay().
distance
int com.runehive.game.Projectile.distance private
Definition at line 21 of file Projectile.java.
Referenced by copy(), getDistance(), Projectile(), Projectile(), and setDistance().
duration
int com.runehive.game.Projectile.duration private
Definition at line 17 of file Projectile.java.
Referenced by copy(), getDuration(), Projectile(), Projectile(), Projectile(), Projectile(), and setDuration().
endHeight
int com.runehive.game.Projectile.endHeight private
Definition at line 19 of file Projectile.java.
Referenced by copy(), getEndHeight(), Projectile(), Projectile(), Projectile(), Projectile(), and setEndHeight().
id
int com.runehive.game.Projectile.id private
Definition at line 15 of file Projectile.java.
Referenced by getId(), Projectile(), Projectile(), Projectile(), Projectile(), and setId().
MAGIC_DELAYS
final int [] com.runehive.game.Projectile.MAGIC_DELAYS = { 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5 } static
Magic combat projectile delays.
Definition at line 10 of file Projectile.java.
{ 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5 };
offsetX
int com.runehive.game.Projectile.offsetX private
Definition at line 22 of file Projectile.java.
Referenced by copy(), getOffsetX(), Projectile(), and setOffsetX().
offsetY
int com.runehive.game.Projectile.offsetY private
Definition at line 23 of file Projectile.java.
Referenced by copy(), getOffsetY(), Projectile(), and setOffsetY().
RANGED_DELAYS
final int [] com.runehive.game.Projectile.RANGED_DELAYS = { 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4 } static
Ranged combat projectile delays.
Definition at line 13 of file Projectile.java.
{ 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4 };
startHeight
int com.runehive.game.Projectile.startHeight private
Definition at line 18 of file Projectile.java.
Referenced by copy(), getStartHeight(), Projectile(), Projectile(), Projectile(), Projectile(), and setStartHeight().
The documentation for this class was generated from the following file:
java/com/runehive/game/Projectile.java