RuneHive-Game: com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy Class Reference
com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy Class Reference
@Author Origin 2/22/2023
Static Public Member Functions
static double getAttackRoll (Mob attacker)
static double getDefenceRoll (Mob defender)
static double getEffectiveLevel (Mob attacker)
static boolean successful (Mob attacker, Mob defender)
Static Public Attributes
static final SecureRandom srand = new SecureRandom()
Static Private Member Functions
static int getAttackBonus (Mob attacker)
static int getDefenceBonus (Mob defender)
static double getPrayerAttackBonus (Mob attacker)
static double getPrayerDefenseBonus (Mob defender)
Detailed Description
@Author Origin 2/22/2023
Definition at line 15 of file MeleeAccuracy.java.
Member Function Documentation
getAttackBonus()
int com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getAttackBonus (Mob attacker) static private
Definition at line 107 of file MeleeAccuracy.java.
{
        return attacker.getBonus(attacker.getCombat().getFightType().getBonus());
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), and com.runehive.game.world.entity.mob.Mob.getCombat().
Referenced by getAttackRoll().
getAttackRoll()
double com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getAttackRoll (Mob attacker) static
Definition at line 53 of file MeleeAccuracy.java.
{
        double effectiveLevel = getEffectiveLevel(attacker);
        double attackBonus = getAttackBonus(attacker);
        double roll = effectiveLevel * (attackBonus + 64);
        if (attacker instanceof Player player) {
            // TODO equipment bonuses
        }
        return Math.floor(roll);
    }
References getAttackBonus(), and getEffectiveLevel().
Referenced by successful().
getDefenceBonus()
int com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getDefenceBonus (Mob defender) static private
Definition at line 103 of file MeleeAccuracy.java.
{
        return defender.getBonus(defender.getCombat().getFightType().getCorrespondingBonus());
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), and com.runehive.game.world.entity.mob.Mob.getCombat().
Referenced by getDefenceRoll().
getDefenceRoll()
double com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getDefenceRoll (Mob defender) static
Definition at line 35 of file MeleeAccuracy.java.
{
        double defenceLevel = defender.skills.getLevel(Skill.DEFENCE);
        double defenceBonus = getDefenceBonus(defender);
        if (defender instanceof Player) {
            defenceLevel *= getPrayerDefenseBonus(defender);
            switch (defender.getCombat().getFightType().getStyle()) {
                case DEFENSIVE -> defenceLevel += 3;
                case CONTROLLED -> defenceLevel += 1;
            }
        } else {
            defenceLevel += 9;
        }
        return defenceLevel * (defenceBonus + 64);
    }
References com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.Mob.getCombat(), getDefenceBonus(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), getPrayerDefenseBonus(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by successful().
getEffectiveLevel()
double com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getEffectiveLevel (Mob attacker) static
Definition at line 66 of file MeleeAccuracy.java.
{
        double effectiveLevel = attacker.skills.getLevel(Skill.ATTACK);
        if (attacker instanceof Player) {
            effectiveLevel *= getPrayerAttackBonus(attacker);
            effectiveLevel = Math.floor(effectiveLevel);
            switch (attacker.getCombat().getFightType().getStyle()) {
                case ACCURATE -> effectiveLevel += 3;
                case CONTROLLED -> effectiveLevel += 1;
            }
        }
        effectiveLevel += 8;
        if (attacker instanceof Player player) {
            if (FormulaUtils.voidMelee(player)) {
                effectiveLevel *= 1.10;
            }
        }
        return Math.floor(effectiveLevel);
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), getPrayerAttackBonus(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.combat.FormulaUtils.voidMelee().
Referenced by getAttackRoll().
getPrayerAttackBonus()
double com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerAttackBonus (Mob attacker) static private
Definition at line 111 of file MeleeAccuracy.java.
{
        double prayerBonus = 1;
        if (attacker.prayer.isActive(Prayer.THICK_SKIN))
            prayerBonus += 1.05D; // 5% def level boost
        else if (attacker.prayer.isActive(Prayer.ROCK_SKIN))
            prayerBonus += 1.10D; // 10% def level boost
        else if (attacker.prayer.isActive(Prayer.STEEL_SKIN))
            prayerBonus += 1.15D; // 15% def level boost
        else if (attacker.prayer.isActive(Prayer.CHIVALRY))
            prayerBonus += 1.20D; // 20% def level boost
        else if (attacker.prayer.isActive(Prayer.PIETY))
            prayerBonus += 1.25D; // 25% def level boost
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.CHIVALRY, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.prayer.Prayer.PIETY, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.ROCK_SKIN, com.runehive.game.world.entity.mob.prayer.Prayer.STEEL_SKIN, and com.runehive.game.world.entity.mob.prayer.Prayer.THICK_SKIN.
Referenced by getEffectiveLevel().
getPrayerDefenseBonus()
double com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerDefenseBonus (Mob defender) static private
Definition at line 88 of file MeleeAccuracy.java.
{
        double prayerBonus = 1;
        if (defender.prayer.isActive(Prayer.THICK_SKIN))
            prayerBonus += 1.05D; // 5% def level boost
        else if (defender.prayer.isActive(Prayer.ROCK_SKIN))
            prayerBonus += 1.10D; // 10% def level boost
        else if (defender.prayer.isActive(Prayer.STEEL_SKIN))
            prayerBonus += 1.15D; // 15% def level boost
        else if (defender.prayer.isActive(Prayer.CHIVALRY))
            prayerBonus += 1.20D; // 20% def level boost
        else if (defender.prayer.isActive(Prayer.PIETY))
            prayerBonus += 1.25D; // 25% def level boost
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.CHIVALRY, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.prayer.Prayer.PIETY, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.ROCK_SKIN, com.runehive.game.world.entity.mob.prayer.Prayer.STEEL_SKIN, and com.runehive.game.world.entity.mob.prayer.Prayer.THICK_SKIN.
Referenced by getDefenceRoll().
successful()
boolean com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.successful (Mob attacker, Mob defender) static
Definition at line 19 of file MeleeAccuracy.java.
{
        double attackRoll = getAttackRoll(attacker);
        double defenceRoll = getDefenceRoll(defender);
        double chance;
        if (attackRoll > defenceRoll)
            chance = 1D - (defenceRoll + 2D) / (2D * (attackRoll + 1D));
        else
            chance = attackRoll / (2D * (defenceRoll + 1D));
        double roll = srand.nextDouble();
        return chance > roll;
    }
References getAttackRoll(), getDefenceRoll(), and srand.
Referenced by com.runehive.game.world.entity.combat.attack.FormulaFactory.isAccurate().
Member Data Documentation
srand
final SecureRandom com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.srand = new SecureRandom() static
Definition at line 17 of file MeleeAccuracy.java.
Referenced by successful().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/accuracy/MeleeAccuracy.java