RuneHive-Game: com.runehive.fs.cache.decoder.Buffer Class Reference
com.runehive.fs.cache.decoder.Buffer Class Reference
Public Member Functions
Buffer (byte[] array)
void encodeRSA (BigInteger exponent, BigInteger modulus)
void finishBitAccess ()
int getUIncrementalSmart ()
void initBitAccess ()
void method403 (int j)
int method421 ()
int method422 ()
void method425 (int j)
byte method429 ()
byte method430 ()
int method438 ()
int method439 ()
int method440 ()
void method441 (int i, byte[] abyte0, int j)
byte peek ()
int read24Int ()
int readBigSmart2 ()
int readBits (int amount)
byte[] readBytes ()
byte[] readBytes (final int length)
void readBytes (int amount, int offset, byte[] destination)
float readFloat ()
int readInt ()
int readLEShort ()
int readLEUShort ()
int readLEUShortA ()
int readMedium ()
int readNegUByte ()
String readNewString ()
void readReverseData (int i, int j, byte[] abyte0)
int readShort ()
int readShort2 ()
int readShortOSRS ()
int readShortSmart ()
byte readSignedByte ()
int readSignedShort ()
int readSignedSmart ()
int readSignedWord ()
int readSmart ()
String readString ()
String readStringCp1252NullTerminated ()
String readStringNew ()
int readUByteA ()
int readUByteS ()
int readUnsignedByte ()
int readUnsignedInt ()
int readUnsignedIntSmartShortCompat ()
long readUnsignedLong ()
int readUnsignedShort ()
int readUnsignedShortSmart ()
int readUnsignedShortSmartMinusOne ()
int readUnsignedTriByte ()
int readUShort ()
int readUShortA ()
int readUSmart2 ()
void setOffset (int offset)
void setPosition (int offset)
void writeByte (int i)
void writeBytes (byte[] abyte0, int i, int j)
void writeBytes (int i)
void writeDWord (int i)
void writeDWordBigEndian (int i)
void writeLEShort (int i)
void writeLEShortA (int j)
void writeNegatedByte (int i)
void writeOpcode (int i)
void writeQWord (long l)
void writeShort (int i)
void writeShortA (int j)
void writeString (String s)
Static Public Member Functions
static String decodeStringCp1252 (byte[] var0, int var1, int var2)
static Buffer fromByteBuffer (final ByteBuffer byteBuffer)
Public Attributes
byte[] array
int bitPosition
IsaacCipher encryption
int position
Static Public Attributes
static final char[] cp1252AsciiExtension = new char[]{'€', '\u0000', '‚', 'ƒ', '„', '…', '†', '‡', 'ˆ', '‰', 'Š', '‹', 'Œ', '\u0000', 'Ž', '\u0000', '\u0000', '‘', '’', '“', '”', '•', '–', '—', '˜', '™', 'š', '›', 'œ', '\u0000', 'ž', 'Ÿ'}
Package Functions
final int v (int i)
Private Member Functions
Buffer ()
Static Private Attributes
static int anInt1412
static final int[] BIT_MASK = {0, 1, 3, 7, 15, 31, 63, 127, 255, 511, 1023, 2047, 4095, 8191, 16383, 32767, 65535, 0x1ffff, 0x3ffff, 0x7ffff, 0xfffff, 0x1fffff, 0x3fffff, 0x7fffff, 0xffffff, 0x1ffffff, 0x3ffffff, 0x7ffffff, 0xfffffff, 0x1fffffff, 0x3fffffff, 0x7fffffff, -1}
Detailed Description
Definition at line 8 of file Buffer.java.
Constructor & Destructor Documentation
Buffer() [1/2]
com.runehive.fs.cache.decoder.Buffer.Buffer () private
Definition at line 104 of file Buffer.java.
                     {
    }
Referenced by fromByteBuffer().
Buffer() [2/2]
com.runehive.fs.cache.decoder.Buffer.Buffer (byte[] array)
Definition at line 107 of file Buffer.java.
{
        this.array = array;
        position = 0;
    }
References array, and position.
Member Function Documentation
decodeStringCp1252()
String com.runehive.fs.cache.decoder.Buffer.decodeStringCp1252 (byte[] var0, int var1, int var2) static
Definition at line 312 of file Buffer.java.
{
        char[] var3 = new char[var2];
        int var4 = 0;
        for(int var5 = 0; var5 < var2; ++var5) {
            int var6 = var0[var5 + var1] & 255;
            if (var6 != 0) {
                if (var6 >= 128 && var6 < 160) {
                    char var7 = cp1252AsciiExtension[var6 - 128];
                    if (var7 == 0) {
                        var7 = '?';
                    }
                    var6 = var7;
                }
                var3[var4++] = (char)var6;
            }
        }
        return new String(var3, 0, var4);
    }
References cp1252AsciiExtension.
Referenced by readStringCp1252NullTerminated().
encodeRSA()
void com.runehive.fs.cache.decoder.Buffer.encodeRSA (BigInteger exponent, BigInteger modulus)
Definition at line 395 of file Buffer.java.
{
        int i = position;
        position = 0;
        byte[] abyte0 = new byte[i];
        readBytes(i, 0, abyte0);
        byte[] rsa = new BigInteger(abyte0).modPow(exponent, modulus).toByteArray();
        position = 0;
        writeByte(rsa.length);
        writeBytes(rsa, rsa.length, 0);
    }
References position, readBytes(), writeByte(), and writeBytes().
finishBitAccess()
void com.runehive.fs.cache.decoder.Buffer.finishBitAccess ()
Definition at line 375 of file Buffer.java.
{
        position = (bitPosition + 7) / 8;
    }
References bitPosition, and position.
fromByteBuffer()
Buffer com.runehive.fs.cache.decoder.Buffer.fromByteBuffer (final ByteBuffer byteBuffer) static
Definition at line 112 of file Buffer.java.
{
        final byte[] array = new byte[byteBuffer.capacity()];
        byteBuffer.get(array);
        return new Buffer(array);
    }
References array, and Buffer().
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.unpackConfig().
getUIncrementalSmart()
int com.runehive.fs.cache.decoder.Buffer.getUIncrementalSmart ()
Definition at line 270 of file Buffer.java.
{
        int value = 0, remainder;
        for (remainder = method422(); remainder == 32767; remainder = method422()) {
            value += 32767;
        }
        value += remainder;
        return value;
    }
References method422().
initBitAccess()
void com.runehive.fs.cache.decoder.Buffer.initBitAccess ()
Definition at line 350 of file Buffer.java.
{
        bitPosition = position * 8;
    }
References bitPosition, and position.
method403()
void com.runehive.fs.cache.decoder.Buffer.method403 (int j)
Definition at line 181 of file Buffer.java.
{
        array[position++] = (byte) j;
        array[position++] = (byte) (j >> 8);
        array[position++] = (byte) (j >> 16);
        array[position++] = (byte) (j >> 24);
    }
References array, and position.
method421()
int com.runehive.fs.cache.decoder.Buffer.method421 ()
Definition at line 379 of file Buffer.java.
{
        int i = array[position] & 0xff;
        if (i < 128)
            return readUnsignedByte() - 64;
        else
            return readUnsignedShort() - 49152;
    }
References array, position, readUnsignedByte(), and readUnsignedShort().
method422()
int com.runehive.fs.cache.decoder.Buffer.method422 ()
Definition at line 387 of file Buffer.java.
{
        int i = array[position] & 0xff;
        if (i < 128)
            return readUnsignedByte();
        else
            return readUnsignedShort() - 32768;
    }
References array, position, readUnsignedByte(), and readUnsignedShort().
Referenced by getUIncrementalSmart(), and readUSmart2().
method425()
void com.runehive.fs.cache.decoder.Buffer.method425 (int j)
Definition at line 412 of file Buffer.java.
{
        array[position++] = (byte) (128 - j);
    }
References array, and position.
method429()
byte com.runehive.fs.cache.decoder.Buffer.method429 ()
Definition at line 428 of file Buffer.java.
{
        return (byte) (-array[position++]);
    }
References array, and position.
method430()
byte com.runehive.fs.cache.decoder.Buffer.method430 ()
Definition at line 432 of file Buffer.java.
{
        return (byte) (128 - array[position++]);
    }
References array, and position.
method438()
int com.runehive.fs.cache.decoder.Buffer.method438 ()
Definition at line 474 of file Buffer.java.
{
        position += 2;
        int j = ((array[position - 1] & 0xff) << 8) + (array[position - 2] - 128 & 0xff);
        if (j > 32767)
            j -= 0x10000;
        return j;
    }
References array, and position.
method439()
int com.runehive.fs.cache.decoder.Buffer.method439 ()
Definition at line 482 of file Buffer.java.
{
        position += 4;
        return ((array[position - 2] & 0xff) << 24) + ((array[position - 1] & 0xff) << 16) + ((array[position - 4] & 0xff) << 8) + (array[position - 3] & 0xff);
    }
References array, and position.
method440()
int com.runehive.fs.cache.decoder.Buffer.method440 ()
Definition at line 487 of file Buffer.java.
{
        position += 4;
        return ((array[position - 3] & 0xff) << 24) + ((array[position - 4] & 0xff) << 16) + ((array[position - 1] & 0xff) << 8) + (array[position - 2] & 0xff);
    }
References array, and position.
method441()
void com.runehive.fs.cache.decoder.Buffer.method441 (int i, byte[] abyte0, int j)
Definition at line 492 of file Buffer.java.
{
        for (int k = (i + j) - 1; k >= i; k--)
            array[position++] = (byte) (abyte0[k] + 128);
    }
References array, and position.
peek()
byte com.runehive.fs.cache.decoder.Buffer.peek ()
Definition at line 231 of file Buffer.java.
    {
        return array[position];
    }
References array, and position.
Referenced by readBigSmart2(), readShortSmart(), readSignedSmart(), readUnsignedShortSmart(), and readUnsignedShortSmartMinusOne().
read24Int()
int com.runehive.fs.cache.decoder.Buffer.read24Int ()
Definition at line 53 of file Buffer.java.
{
        position += 3;
        return ((array[position - 3] & 0xff) << 16) + ((array[position - 2] & 0xff) << 8) + (array[position - 1] & 0xff);
    }
References array, and position.
readBigSmart2()
int com.runehive.fs.cache.decoder.Buffer.readBigSmart2 ()
Definition at line 242 of file Buffer.java.
    {
        if (peek() < 0)
        {
            return readInt() & Integer.MAX_VALUE; // and off sign bit
        }
        int value = readUnsignedShort();
        return value == 32767 ? -1 : value;
    }
References peek(), readInt(), and readUnsignedShort().
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode().
readBits()
int com.runehive.fs.cache.decoder.Buffer.readBits (int amount)
Definition at line 354 of file Buffer.java.
{
        int bytePos = bitPosition >> 3;
        int bitOffset = 8 - (bitPosition & 7);
        int value = 0;
        bitPosition += amount;
        for (; amount > bitOffset; bitOffset = 8) {
            value += (array[bytePos++] & BIT_MASK[bitOffset]) << amount - bitOffset;
            amount -= bitOffset;
        }
        if (amount == bitOffset) {
            value += array[bytePos] & BIT_MASK[bitOffset];
        } else {
            value += array[bytePos] >> bitOffset - amount & BIT_MASK[amount];
        }
        return value;
    }
References array, BIT_MASK, and bitPosition.
readBytes() [1/3]
byte[] com.runehive.fs.cache.decoder.Buffer.readBytes ()
Definition at line 337 of file Buffer.java.
{
        int start = position;
        while (array[position++] != 10);
        byte[] bytes = new byte[position - start - 1];
        System.arraycopy(array, start, bytes, start - start, position - 1 - start);
        return bytes;
    }
References array, and position.
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode(), and encodeRSA().
readBytes() [2/3]
byte[] com.runehive.fs.cache.decoder.Buffer.readBytes (final int length)
Definition at line 508 of file Buffer.java.
{
        final byte[] bytes = new byte[length];
        System.arraycopy(array, position, bytes, 0, length);
        position += length;
        return bytes;
    }
References array, and position.
readBytes() [3/3]
void com.runehive.fs.cache.decoder.Buffer.readBytes (int amount, int offset, byte[] destination)
Definition at line 345 of file Buffer.java.
{
        for (int l = offset; l < offset + amount; l++)
            destination[l] = array[position++];
    }
References array, and position.
readFloat()
float com.runehive.fs.cache.decoder.Buffer.readFloat ()
Definition at line 504 of file Buffer.java.
{
        return Float.intBitsToFloat(readInt());
    }
References readInt().
readInt()
int com.runehive.fs.cache.decoder.Buffer.readInt ()
Definition at line 70 of file Buffer.java.
{
        position += 4;
        return ((array[position - 4] & 0xff) << 24)
                + ((array[position - 3] & 0xff) << 16)
                + ((array[position - 2] & 0xff) << 8)
                + (array[position - 1] & 0xff);
    }
References array, and position.
Referenced by readBigSmart2(), and readFloat().
readLEShort()
int com.runehive.fs.cache.decoder.Buffer.readLEShort ()
Definition at line 466 of file Buffer.java.
{
        position += 2;
        int j = ((array[position - 1] & 0xff) << 8) + (array[position - 2] & 0xff);
        if (j > 32767)
            j -= 0x10000;
        return j;
    }
References array, and position.
readLEUShort()
int com.runehive.fs.cache.decoder.Buffer.readLEUShort ()
Definition at line 451 of file Buffer.java.
{
        position += 2;
        return ((array[position - 1] & 0xff) << 8) + (array[position - 2] & 0xff);
    }
References array, and position.
readLEUShortA()
int com.runehive.fs.cache.decoder.Buffer.readLEUShortA ()
Definition at line 461 of file Buffer.java.
{
        position += 2;
        return ((array[position - 1] & 0xff) << 8) + (array[position - 2] - 128 & 0xff);
    }
References array, and position.
readMedium()
int com.runehive.fs.cache.decoder.Buffer.readMedium ()
Definition at line 58 of file Buffer.java.
{
        this.position += 3;
        return ((this.array[this.position - 3] & 255) << 16) + (this.array[this.position - 1] & 255) + ((this.array[this.position - 2] & 255) << 8);
    }
References array, and position.
readNegUByte()
int com.runehive.fs.cache.decoder.Buffer.readNegUByte ()
Definition at line 420 of file Buffer.java.
{
        return -array[position++] & 0xff;
    }
References array, and position.
readNewString()
String com.runehive.fs.cache.decoder.Buffer.readNewString ()
Definition at line 147 of file Buffer.java.
{
        int i = position;
        while (array[position++] != 0)
            ;
        return new String(array, i, position - i - 1);
    }
References array, and position.
readReverseData()
void com.runehive.fs.cache.decoder.Buffer.readReverseData (int i, int j, byte[] abyte0)
Definition at line 498 of file Buffer.java.
{
        for (int k = (j + i) - 1; k >= j; k--)
            abyte0[k] = array[position++];
    }
References array, and position.
readShort()
int com.runehive.fs.cache.decoder.Buffer.readShort ()
Definition at line 78 of file Buffer.java.
{
        position += 2;
        int value = ((array[position - 2] & 0xff) << 8)
                + (array[position - 1] & 0xff);
        if (value > 32767) {
            value -= 0x10000;
        }
        return value;
    }
References array, and position.
readShort2()
int com.runehive.fs.cache.decoder.Buffer.readShort2 ()
Definition at line 29 of file Buffer.java.
{
        position += 2;
        int i = ((array[position - 2] & 0xff) << 8) + (array[position - 1] & 0xff);
        if (i > 60000)
            i = -65535 + i;
        return i;
    }
References array, and position.
readShortOSRS()
int com.runehive.fs.cache.decoder.Buffer.readShortOSRS ()
Definition at line 89 of file Buffer.java.
{
        this.position += 2;
        int var1 = (this.array[this.position - 1] & 255) + ((this.array[this.position - 2] & 255) << 8);
        if (var1 > 32767) {
            var1 -= 65536;
        }
        return var1;
    }
References array, and position.
readShortSmart()
int com.runehive.fs.cache.decoder.Buffer.readShortSmart ()
Definition at line 47 of file Buffer.java.
    {
        int peek = array[position] & 0xFF;
        return peek < 128 ? this.readUnsignedByte() - 64 : this.readUnsignedShort() - 0xc000;
    }
References array, peek(), position, readUnsignedByte(), and readUnsignedShort().
readSignedByte()
byte com.runehive.fs.cache.decoder.Buffer.readSignedByte ()
Definition at line 252 of file Buffer.java.
{
        return array[position++];
    }
References array, and position.
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode().
readSignedShort()
int com.runehive.fs.cache.decoder.Buffer.readSignedShort ()
Definition at line 38 of file Buffer.java.
{
        this.position += 2;
        int value = ((this.array[this.position - 2] & 0xff) << 8) + (this.array[this.position - 1] & 0xff);
        if (value > 32767)
            value -= 0x10000; //theres no errors its just gradle being slow as fck
        return value;
    }
References array, and position.
readSignedSmart()
int com.runehive.fs.cache.decoder.Buffer.readSignedSmart ()
Definition at line 223 of file Buffer.java.
{
        int value = peek() & 0xff;
        if (value < 128)
            return this.readUnsignedByte() - 64;
        else
            return this.readUnsignedShort() - 49152;
    }
References peek(), readUnsignedByte(), and readUnsignedShort().
readSignedWord()
int com.runehive.fs.cache.decoder.Buffer.readSignedWord ()
Definition at line 261 of file Buffer.java.
{
        position += 2;
        int i = ((array[position - 2] & 0xff) << 8) + (array[position - 1] & 0xff);
        if (i > 32767) {
            i -= 0x10000;
        }
        return i;
    }
References array, and position.
readSmart()
int com.runehive.fs.cache.decoder.Buffer.readSmart ()
Definition at line 15 of file Buffer.java.
{
        int value = array[position] & 0xff;
        if (value < 128)
            return readUnsignedByte() - 64;
        else
            return readUShort() - 49152;
    }
References array, position, readUnsignedByte(), and readUShort().
readString()
String com.runehive.fs.cache.decoder.Buffer.readString ()
Definition at line 295 of file Buffer.java.
{
        int start = position;
        while (array[position++] != 10);
        return new String(array, start, position - start - 1);
    }
References array, and position.
readStringCp1252NullTerminated()
String com.runehive.fs.cache.decoder.Buffer.readStringCp1252NullTerminated ()
Definition at line 301 of file Buffer.java.
{
        int var1 = this.position;
        while(this.array[++this.position - 1] != 0) {
            ;
        }
        int var2 = this.position - var1 - 1;
        return var2 == 0 ? "" : decodeStringCp1252(this.array, var1, var2);
    }
References array, decodeStringCp1252(), and position.
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode().
readStringNew()
String com.runehive.fs.cache.decoder.Buffer.readStringNew ()
Definition at line 22 of file Buffer.java.
{
        int i = position;
        while (array[position++] != 0)
            ;
        return new String(array, i, position - i - 1);
    }
References array, and position.
readUByteA()
int com.runehive.fs.cache.decoder.Buffer.readUByteA ()
Definition at line 416 of file Buffer.java.
{
        return array[position++] - 128 & 0xff;
    }
References array, and position.
readUByteS()
int com.runehive.fs.cache.decoder.Buffer.readUByteS ()
Definition at line 424 of file Buffer.java.
{
        return 128 - array[position++] & 0xff;
    }
References array, and position.
readUnsignedByte()
int com.runehive.fs.cache.decoder.Buffer.readUnsignedByte ()
Definition at line 219 of file Buffer.java.
{
        return array[position++] & 0xff;
    }
References array, and position.
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode(), method421(), method422(), readShortSmart(), readSignedSmart(), readSmart(), readUnsignedShortSmart(), and readUnsignedShortSmartMinusOne().
readUnsignedInt()
int com.runehive.fs.cache.decoder.Buffer.readUnsignedInt ()
Definition at line 284 of file Buffer.java.
{
        position += 4;
        return ((array[position - 4] & 0xff) << 24) + ((array[position - 3] & 0xff) << 16) + ((array[position - 2] & 0xff) << 8) + (array[position - 1] & 0xff);
    }
References array, and position.
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode(), and readUnsignedLong().
readUnsignedIntSmartShortCompat()
int com.runehive.fs.cache.decoder.Buffer.readUnsignedIntSmartShortCompat ()
Definition at line 124 of file Buffer.java.
    {
        int var1 = 0;
        int var2;
        for (var2 = this.readUnsignedShortSmart(); var2 == 32767; var2 = this.readUnsignedShortSmart())
        {
            var1 += 32767;
        }
        var1 += var2;
        return var1;
    }
References readUnsignedShortSmart().
readUnsignedLong()
long com.runehive.fs.cache.decoder.Buffer.readUnsignedLong ()
Definition at line 289 of file Buffer.java.
{
        long big = (long) readUnsignedInt() & 0xFFFF_FFFFL;
        long little = (long) readUnsignedInt() & 0xFFFF_FFFFL;
        return (big << 32) + little;
    }
References readUnsignedInt().
readUnsignedShort()
int com.runehive.fs.cache.decoder.Buffer.readUnsignedShort ()
Definition at line 256 of file Buffer.java.
{
        position += 2;
        return ((array[position - 2] & 0xff) << 8) + (array[position - 1] & 0xff);
    }
References array, and position.
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode(), method421(), method422(), readBigSmart2(), readShortSmart(), readSignedSmart(), readUnsignedShortSmart(), readUnsignedShortSmartMinusOne(), and com.runehive.fs.cache.decoder.CacheNpcDefinition.unpackConfig().
readUnsignedShortSmart()
int com.runehive.fs.cache.decoder.Buffer.readUnsignedShortSmart ()
Definition at line 118 of file Buffer.java.
    {
        int peek = this.peek() & 0xFF;
        return peek < 128 ? this.readUnsignedByte() : this.readUnsignedShort() - 0x8000;
    }
References peek(), readUnsignedByte(), and readUnsignedShort().
Referenced by readUnsignedIntSmartShortCompat().
readUnsignedShortSmartMinusOne()
int com.runehive.fs.cache.decoder.Buffer.readUnsignedShortSmartMinusOne ()
Definition at line 236 of file Buffer.java.
    {
        int peek = this.peek() & 0xFF;
        return peek < 128 ? this.readUnsignedByte() - 1 : this.readUnsignedShort() - 0x8001;
    }
References peek(), readUnsignedByte(), and readUnsignedShort().
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode().
readUnsignedTriByte()
int com.runehive.fs.cache.decoder.Buffer.readUnsignedTriByte ()
Definition at line 279 of file Buffer.java.
{
        position += 3;
        return ((array[position - 3] & 0xff) << 16) + ((array[position - 2] & 0xff) << 8) + (array[position - 1] & 0xff);
    }
References array, and position.
Referenced by com.runehive.fs.cache.decoder.CacheNpcDefinition.decode().
readUShort()
int com.runehive.fs.cache.decoder.Buffer.readUShort ()
Definition at line 64 of file Buffer.java.
{
        position += 2;
        return ((array[position - 2] & 0xff) << 8)
                + (array[position - 1] & 0xff);
    }
References array, and position.
Referenced by readSmart().
readUShortA()
int com.runehive.fs.cache.decoder.Buffer.readUShortA ()
Definition at line 456 of file Buffer.java.
{
        position += 2;
        return ((array[position - 2] & 0xff) << 8) + (array[position - 1] - 128 & 0xff);
    }
References array, and position.
readUSmart2()
int com.runehive.fs.cache.decoder.Buffer.readUSmart2 ()
Definition at line 138 of file Buffer.java.
{
        int baseVal = 0;
        int lastVal = 0;
        while ((lastVal = method422()) == 32767) {
            baseVal += 32767;
        }
        return baseVal + lastVal;
    }
References method422().
setOffset()
void com.runehive.fs.cache.decoder.Buffer.setOffset (int offset)
Definition at line 11 of file Buffer.java.
{
        this.position = offset;
    }
setPosition()
void com.runehive.fs.cache.decoder.Buffer.setPosition (int offset)
Definition at line 522 of file Buffer.java.
{
        this.position = offset;
    }
v()
final int com.runehive.fs.cache.decoder.Buffer.v (int i) package
Definition at line 99 of file Buffer.java.
                       {
        position += 3;
        return (0xff & array[position - 3] << 16) + (0xff & array[position - 2] << 8) + (0xff & array[position - 1]);
    }
References array, and position.
writeByte()
void com.runehive.fs.cache.decoder.Buffer.writeByte (int i)
Definition at line 159 of file Buffer.java.
{
        array[position++] = (byte) i;
    }
References array, and position.
Referenced by encodeRSA().
writeBytes() [1/2]
void com.runehive.fs.cache.decoder.Buffer.writeBytes (byte[] abyte0, int i, int j)
Definition at line 210 of file Buffer.java.
{
        for (int k = j; k < j + i; k++)
            array[position++] = abyte0[k];
    }
References array, and position.
Referenced by encodeRSA().
writeBytes() [2/2]
void com.runehive.fs.cache.decoder.Buffer.writeBytes (int i)
Definition at line 215 of file Buffer.java.
{
        array[position - i - 1] = (byte) i;
    }
References array, and position.
writeDWord()
void com.runehive.fs.cache.decoder.Buffer.writeDWord (int i)
Definition at line 174 of file Buffer.java.
{
        array[position++] = (byte) (i >> 24);
        array[position++] = (byte) (i >> 16);
        array[position++] = (byte) (i >> 8);
        array[position++] = (byte) i;
    }
References array, and position.
writeDWordBigEndian()
void com.runehive.fs.cache.decoder.Buffer.writeDWordBigEndian (int i)
Definition at line 168 of file Buffer.java.
{
        array[position++] = (byte) (i >> 16);
        array[position++] = (byte) (i >> 8);
        array[position++] = (byte) i;
    }
References array, and position.
writeLEShort()
void com.runehive.fs.cache.decoder.Buffer.writeLEShort (int i)
Definition at line 436 of file Buffer.java.
{
        array[position++] = (byte) i;
        array[position++] = (byte) (i >> 8);
    }
References array, and position.
writeLEShortA()
void com.runehive.fs.cache.decoder.Buffer.writeLEShortA (int j)
Definition at line 446 of file Buffer.java.
{
        array[position++] = (byte) (j + 128);
        array[position++] = (byte) (j >> 8);
    }
References array, and position.
writeNegatedByte()
void com.runehive.fs.cache.decoder.Buffer.writeNegatedByte (int i)
Definition at line 408 of file Buffer.java.
{
        array[position++] = (byte) (-i);
    }
References array, and position.
writeOpcode()
void com.runehive.fs.cache.decoder.Buffer.writeOpcode (int i)
Definition at line 154 of file Buffer.java.
{
        // System.out.println("Frame: " + i);
        array[position++] = (byte) (i + encryption.getKey());
    }
References array, encryption, and position.
writeQWord()
void com.runehive.fs.cache.decoder.Buffer.writeQWord (long l)
Definition at line 188 of file Buffer.java.
{
        try {
            array[position++] = (byte) (int) (l >> 56);
            array[position++] = (byte) (int) (l >> 48);
            array[position++] = (byte) (int) (l >> 40);
            array[position++] = (byte) (int) (l >> 32);
            array[position++] = (byte) (int) (l >> 24);
            array[position++] = (byte) (int) (l >> 16);
            array[position++] = (byte) (int) (l >> 8);
            array[position++] = (byte) (int) l;
        } catch (RuntimeException runtimeexception) {
            throw new RuntimeException();
        }
    }
References array, and position.
writeShort()
void com.runehive.fs.cache.decoder.Buffer.writeShort (int i)
Definition at line 163 of file Buffer.java.
{
        array[position++] = (byte) (i >> 8);
        array[position++] = (byte) i;
    }
References array, and position.
writeShortA()
void com.runehive.fs.cache.decoder.Buffer.writeShortA (int j)
Definition at line 441 of file Buffer.java.
{
        array[position++] = (byte) (j >> 8);
        array[position++] = (byte) (j + 128);
    }
References array, and position.
writeString()
void com.runehive.fs.cache.decoder.Buffer.writeString (String s)
Definition at line 203 of file Buffer.java.
{
        // s.getBytes(0, s.length(), buffer, currentOffset); //deprecated
        System.arraycopy(s.getBytes(), 0, array, position, s.length());
        position += s.length();
        array[position++] = 10;
    }
References array, and position.
Member Data Documentation
anInt1412
int com.runehive.fs.cache.decoder.Buffer.anInt1412 static private
Definition at line 520 of file Buffer.java.
array
byte [] com.runehive.fs.cache.decoder.Buffer.array
Definition at line 515 of file Buffer.java.
Referenced by Buffer(), fromByteBuffer(), method403(), method421(), method422(), method425(), method429(), method430(), method438(), method439(), method440(), method441(), peek(), read24Int(), readBits(), readBytes(), readBytes(), readBytes(), readInt(), readLEShort(), readLEUShort(), readLEUShortA(), readMedium(), readNegUByte(), readNewString(), readReverseData(), readShort(), readShort2(), readShortOSRS(), readShortSmart(), readSignedByte(), readSignedShort(), readSignedWord(), readSmart(), readString(), readStringCp1252NullTerminated(), readStringNew(), readUByteA(), readUByteS(), readUnsignedByte(), readUnsignedInt(), readUnsignedShort(), readUnsignedTriByte(), readUShort(), readUShortA(), v(), writeByte(), writeBytes(), writeBytes(), writeDWord(), writeDWordBigEndian(), writeLEShort(), writeLEShortA(), writeNegatedByte(), writeOpcode(), writeQWord(), writeShort(), writeShortA(), and writeString().
BIT_MASK
final int [] com.runehive.fs.cache.decoder.Buffer.BIT_MASK = {0, 1, 3, 7, 15, 31, 63, 127, 255, 511, 1023, 2047, 4095, 8191, 16383, 32767, 65535, 0x1ffff, 0x3ffff, 0x7ffff, 0xfffff, 0x1fffff, 0x3fffff, 0x7fffff, 0xffffff, 0x1ffffff, 0x3ffffff, 0x7ffffff, 0xfffffff, 0x1fffffff, 0x3fffffff, 0x7fffffff, -1} static private
Definition at line 518 of file Buffer.java.
{0, 1, 3, 7, 15, 31, 63, 127, 255, 511, 1023, 2047, 4095, 8191, 16383, 32767, 65535, 0x1ffff, 0x3ffff, 0x7ffff, 0xfffff, 0x1fffff, 0x3fffff, 0x7fffff, 0xffffff, 0x1ffffff, 0x3ffffff, 0x7ffffff, 0xfffffff, 0x1fffffff, 0x3fffffff, 0x7fffffff, -1};
Referenced by readBits().
bitPosition
int com.runehive.fs.cache.decoder.Buffer.bitPosition
Definition at line 517 of file Buffer.java.
Referenced by finishBitAccess(), initBitAccess(), and readBits().
cp1252AsciiExtension
final char [] com.runehive.fs.cache.decoder.Buffer.cp1252AsciiExtension = new char[]{'€', '\u0000', '‚', 'ƒ', '„', '…', '†', '‡', 'ˆ', '‰', 'Š', '‹', 'Œ', '\u0000', 'Ž', '\u0000', '\u0000', '‘', '’', '“', '”', '•', '–', '—', '˜', '™', 'š', '›', 'œ', '\u0000', 'ž', 'Ÿ'} static
Definition at line 335 of file Buffer.java.
{'€', '\u0000', '‚', 'ƒ', '„', '…', '†', '‡', 'ˆ', '‰', 'Š', '‹', 'Œ', '\u0000', 'Ž', '\u0000', '\u0000', '‘', '’', '“', '”', '•', '–', '—', '˜', '™', 'š', '›', 'œ', '\u0000', 'ž', 'Ÿ'};
Referenced by decodeStringCp1252().
encryption
IsaacCipher com.runehive.fs.cache.decoder.Buffer.encryption
Definition at line 519 of file Buffer.java.
Referenced by writeOpcode().
position
int com.runehive.fs.cache.decoder.Buffer.position
Definition at line 516 of file Buffer.java.
Referenced by Buffer(), encodeRSA(), finishBitAccess(), initBitAccess(), method403(), method421(), method422(), method425(), method429(), method430(), method438(), method439(), method440(), method441(), peek(), read24Int(), readBytes(), readBytes(), readBytes(), readInt(), readLEShort(), readLEUShort(), readLEUShortA(), readMedium(), readNegUByte(), readNewString(), readReverseData(), readShort(), readShort2(), readShortOSRS(), readShortSmart(), readSignedByte(), readSignedShort(), readSignedWord(), readSmart(), readString(), readStringCp1252NullTerminated(), readStringNew(), readUByteA(), readUByteS(), readUnsignedByte(), readUnsignedInt(), readUnsignedShort(), readUnsignedTriByte(), readUShort(), readUShortA(), v(), writeByte(), writeBytes(), writeBytes(), writeDWord(), writeDWordBigEndian(), writeLEShort(), writeLEShortA(), writeNegatedByte(), writeOpcode(), writeQWord(), writeShort(), writeShortA(), and writeString().
The documentation for this class was generated from the following file:
java/com/runehive/fs/cache/decoder/Buffer.java