RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy Class Reference
com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy Class Reference
Public Member Functions
boolean canAttack (Player attacker, Mob defender)
Animation getAttackAnimation (Player attacker, Mob defender)
int getAttackDelay (Player attacker, Mob defender, FightType fightType)
int getAttackDistance (Player attacker, FightType fightType)
CombatType getCombatType ()
CombatHit[] getHits (Player attacker, Mob defender)
CombatSpell getSpell ()
void hit (Player attacker, Mob defender, Hit hit)
void hitsplat (Player attacker, Mob defender, Hit hit)
PlayerMagicStrategy (CombatSpell spell)
Constructs a new SpellStrategy from a CombatSpell.
void start (Player attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Private Attributes
final CombatSpell spell
The magic spell definition.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Static Public Attributes inherited from com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >
static final Graphic SPLASH = new Graphic(85, 0, Graphic.HIGH_HEIGHT)
The spell splash graphic.
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >
static void addCombatExperience (Player player, double base, Hit... hits)
Detailed Description
Definition at line 32 of file PlayerMagicStrategy.java.
Constructor & Destructor Documentation
PlayerMagicStrategy()
com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.PlayerMagicStrategy (CombatSpell spell)
Constructs a new SpellStrategy from a CombatSpell.
Definition at line 38 of file PlayerMagicStrategy.java.
{
        this.spell = spell;
    }
References spell.
Member Function Documentation
canAttack()
boolean com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack (Player attacker, Mob defender)
Definition at line 43 of file PlayerMagicStrategy.java.
{
        if (defender.isPlayer() && defender.getPlayer().isBot && !PlayerRight.isOwner(defender.getPlayer())) {
            attacker.message("You can't attack bots with magic.");
            return false;
        }
        if (spell == CombatSpell.TELE_BLOCK) {
            if (defender.isPlayer()) {
                if (defender.getPlayer().isTeleblocked()) {
                    attacker.message("This player is already affected by this spell!");
                    return false;
                }
            } else if (defender.isNpc()) {
                attacker.message("You can't teleblock a npc!");
                return false;
            }
        }
        if (spell == CombatSpell.CRUMBLE_UNDEAD) {
            if (defender.isPlayer()) {
                attacker.message("You can not use the crumble undead spell on a player!");
                return false;
            }
            if (defender.isNpc()) {
                String name = defender.getName().toLowerCase();
                if (!(name.contains("zombified") || name.contains("undead") || name.contains("zombie") || name.contains("skeleton") || name.contains("ghost") || name.contains("shade"))) {
                    attacker.message("This spell only affects skeletons, zombies, ghosts and shades");
                    return false;
                }
            }
        }
        if (/*PlayerRight.isDeveloper(attacker) ||*/ spell.canCast(attacker, defender)) {
            return true;
        }
        attacker.send(new SendMessage("You need some runes to cast this spell."));
        attacker.getCombat().reset();
        return false;
    }
References com.runehive.game.world.entity.combat.magic.CombatSpell.CRUMBLE_UNDEAD, com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.Entity.getName(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.player.Player.isBot, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.player.PlayerRight.isOwner(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.player.Player.isTeleblocked(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.player.Player.send(), spell, and com.runehive.game.world.entity.combat.magic.CombatSpell.TELE_BLOCK.
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackAnimation (Player attacker, Mob defender)
Definition at line 188 of file PlayerMagicStrategy.java.
{
        if (spell.getAnimation().isPresent()) {
            return spell.getAnimation().get();
        }
        FightType fightType = attacker.getCombat().getFightType();
        int animation = fightType.getAnimation();
        if (attacker.equipment.hasShield()) {
            Item weapon = attacker.equipment.getShield();
            animation = weapon.getAttackAnimation(fightType).orElse(animation);
        }
        if (attacker.equipment.hasWeapon()) {
            Item weapon = attacker.equipment.getWeapon();
            animation = weapon.getAttackAnimation(fightType).orElse(animation);
        }
        return new Animation(animation, UpdatePriority.HIGH);
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.combat.attack.FightType.getAnimation(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.items.containers.equipment.Equipment.getShield(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.hasShield(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), com.runehive.game.UpdatePriority.HIGH, and spell.
Referenced by start().
getAttackDelay()
int com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackDelay (Player attacker, Mob defender, FightType fightType)
Definition at line 178 of file PlayerMagicStrategy.java.
{
        return 5;
    }
getAttackDistance()
int com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackDistance (Player attacker, FightType fightType)
Definition at line 183 of file PlayerMagicStrategy.java.
{
        return 10;
    }
getCombatType()
CombatType com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getCombatType ()
Reimplemented from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
Definition at line 210 of file PlayerMagicStrategy.java.
{
        return CombatType.MAGIC;
    }
References com.runehive.game.world.entity.combat.CombatType.MAGIC.
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getHits (Player attacker, Mob defender)
Definition at line 167 of file PlayerMagicStrategy.java.
{
        CombatHit combatHit = nextMagicHit(attacker, defender, spell.getCombatProjectile());
        if (spell == CombatSpell.CRUMBLE_UNDEAD && defender.getName().equalsIgnoreCase("zombified spawn")) {
            combatHit.setDamage(defender.getCurrentHealth());
        }
        return new CombatHit[]{combatHit};
    }
References com.runehive.game.world.entity.combat.magic.CombatSpell.CRUMBLE_UNDEAD, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.Entity.getName(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit(), com.runehive.game.world.entity.combat.hit.Hit.setDamage(), and spell.
getSpell()
CombatSpell com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getSpell ()
Definition at line 214 of file PlayerMagicStrategy.java.
{
        return spell;
    }
References spell.
hit()
void com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.hit (Player attacker, Mob defender, Hit hit)
Definition at line 150 of file PlayerMagicStrategy.java.
{
        if (!attacker.isSingleCast() && !attacker.isAutocast()) {
            attacker.resetFace();
        }
        if (hit.isAccurate()) {
            if (attacker.equipment.retrieve(WEAPON_SLOT).filter(item -> item.getId() == 12904).isPresent() && RandomUtils.success(0.25)) {
                defender.venom();
            }
        }
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, hit(), com.runehive.game.world.entity.mob.player.Player.isAutocast(), com.runehive.game.world.entity.mob.player.Player.isSingleCast(), com.runehive.game.world.entity.mob.Mob.resetFace(), com.runehive.game.world.items.containers.ItemContainer.retrieve(), com.runehive.util.RandomUtils.success(), and com.runehive.game.world.entity.mob.Mob.venom().
Referenced by hit(), hitsplat(), and start().
hitsplat()
void com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.hitsplat (Player attacker, Mob defender, Hit hit)
Definition at line 163 of file PlayerMagicStrategy.java.
{
    }
References hit().
start()
void com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start (Player attacker, Mob defender, Hit[] hits)
Definition at line 87 of file PlayerMagicStrategy.java.
{
        if (attacker.getCombat().getDefender() == defender) {
            attacker.animate(getAttackAnimation(attacker, defender), true);
            spell.getStart().ifPresent(attacker::graphic);
            int projectileDuration = spell.sendProjectile(attacker, defender);
            if (projectileDuration == 0) {
                final int distance = attacker.getPosition().getChebyshevDistance(defender.getPosition());
                final int duration = distance * 10;
                projectileDuration = 51 + duration;
            }
            // so this is special just for ice barrage/burst, the projectile does this.
            final Graphic endGraphic = getEndGraphic(spell.getEnd(), missed(hits), SPLASH, projectileDuration);
            if (endGraphic != null) {
                defender.graphic(endGraphic);
            }
            if (spell.getEffect().isPresent()) {
                List<Hit> extra = new LinkedList<>();
                for (Hit hit : hits) {
                    Predicate<CombatImpact> filter = effect -> effect.canAffect(attacker, defender, hit);
                    Consumer<CombatImpact> execute = effect -> effect.impact(attacker, defender, hit, extra);
                    spell.getEffect().filter(filter).ifPresent(execute);
                }
                if (!defender.isPlayer() || !PlayerRight.isIronman(attacker)) {
                    if (extra.isEmpty()) {
                        Collections.addAll(extra, hits);
                        addCombatExperience(attacker, spell.getBaseExperience(), extra.toArray(new Hit[0]));
                    } else {
                        addCombatExperience(attacker, spell.getBaseExperience(), hits);
                    }
                } else {
                    attacker.skills.addExperience(Skill.MAGIC, spell.getBaseExperience());
                }
            } else if (!defender.isPlayer() || !PlayerRight.isIronman(attacker)) {
                addCombatExperience(attacker, spell.getBaseExperience(), hits);
            } else {
                attacker.skills.addExperience(Skill.MAGIC, spell.getBaseExperience());
            }
            if ((!attacker.equipment.containsAny(11791, 12904) || !RandomUtils.success(0.125))) {
                MagicRune.remove(attacker, spell.getRunes());
            }
            if (attacker.isSingleCast()) {
                attacker.setSingleCast(null);
                attacker.getCombat().reset();
                attacker.interact(defender);
            }
            Item weapon = attacker.equipment.get(Equipment.WEAPON_SLOT);
            if(weapon != null) {
                switch(weapon.getId()) {
                    case ThammaronsSceptre.THAMMARONS_SCEPTRE_CHARGED_ID -> {
                        attacker.thammoranSceptreCharges--;
                    }
                }
            }
        }
    }
References com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >.addCombatExperience(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.items.containers.ItemContainer.containsAny(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), getAttackAnimation(), com.runehive.game.world.position.Position.getChebyshevDistance(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.Mob.graphic, hit(), com.runehive.game.world.entity.mob.Mob.interact(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.player.Player.isSingleCast(), com.runehive.game.world.entity.skill.Skill.MAGIC, com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.missed(), com.runehive.game.world.entity.combat.magic.MagicRune.remove(), com.runehive.game.world.entity.mob.player.Player.setSingleCast(), com.runehive.game.world.entity.mob.Mob.skills, spell, com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >.SPLASH, com.runehive.util.RandomUtils.success(), com.runehive.content.itemaction.impl.ThammaronsSceptre.THAMMARONS_SCEPTRE_CHARGED_ID, com.runehive.game.world.entity.mob.player.Player.thammoranSceptreCharges, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Member Data Documentation
spell
final CombatSpell com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.spell private
The magic spell definition.
Definition at line 35 of file PlayerMagicStrategy.java.
Referenced by canAttack(), getAttackAnimation(), getHits(), getSpell(), PlayerMagicStrategy(), and start().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/PlayerMagicStrategy.java