RuneHive-Game: com.runehive.game.action.ActionManager Class Reference
com.runehive.game.action.ActionManager Class Reference
The class which manages Actions executed by mobs.
Public Member Functions
void cancel ()
Cancels the current Action for the underlying Mob.
void cancel (String name)
Purges actions in the queue with a WalkablePolicy of NON_WALKABLE.
void clearNonWalkableActions ()
Purges actions in the queue with a WalkablePolicy of NON_WALKABLE.
Action<?> getCurrentAction ()
Gets the current action.
void reset ()
Resets all the actions for the underlying Mob.
void sequence ()
Sequences the pending actions, and as soon as the current action has stopped, it executes the head of the queue.
String toString ()
Package Functions
public< A extends Action<?> > void execute (A action)
public< A extends Action<?> > void execute (A action, boolean override)
Adds an Action to the queue.
public< A extends Action<?> > void queue (A action)
Queues the specified action.
Private Member Functions
void cancelQueuedActions ()
Cancels all the queued actions by stopping them and removing all elements from the queue.
Private Attributes
Action<?> currentAction = null
The current action.
final Queue< Action<?> > queuedActions = new ArrayDeque<>()
A queue of Action object.
Detailed Description
The class which manages Actions executed by mobs.
Author
Stand Up
Definition at line 16 of file ActionManager.java.
Member Function Documentation
cancel() [1/2]
void com.runehive.game.action.ActionManager.cancel ()
Cancels the current Action for the underlying Mob.
Definition at line 74 of file ActionManager.java.
{
        if (currentAction != null && currentAction.isRunning() && currentAction.prioritized()) {
            currentAction.cancel();
            currentAction = null;
        }
    }
References currentAction.
Referenced by reset().
cancel() [2/2]
void com.runehive.game.action.ActionManager.cancel (String name)
Purges actions in the queue with a WalkablePolicy of NON_WALKABLE.
Definition at line 109 of file ActionManager.java.
{
        if (currentAction != null && Objects.equals(currentAction.getName(), name)) {
            currentAction.cancel();
            currentAction = null;
        }
        for (Action<?> actionEvent : queuedActions) {
            if (Objects.equals(actionEvent.getName(), name)) {
                actionEvent.cancel();
                queuedActions.remove(actionEvent);
            }
        }
    }
References currentAction, and queuedActions.
cancelQueuedActions()
void com.runehive.game.action.ActionManager.cancelQueuedActions () private
Cancels all the queued actions by stopping them and removing all elements from the queue.
Definition at line 68 of file ActionManager.java.
{
        queuedActions.forEach(Action::cancel);
        queuedActions.clear();
    }
References com.runehive.game.task.Task.cancel(), and queuedActions.
Referenced by reset().
clearNonWalkableActions()
void com.runehive.game.action.ActionManager.clearNonWalkableActions ()
Purges actions in the queue with a WalkablePolicy of NON_WALKABLE.
Definition at line 88 of file ActionManager.java.
{
        final Action<?> currentAction = this.currentAction;
        if (currentAction != null) {
            if (!currentAction.cancellableInProgress()) {
                return;
            }
            if (currentAction.getWalkablePolicy() == WalkablePolicy.NON_WALKABLE) {
                currentAction.cancel();
                this.currentAction = null;
            }
        }
        for (Action<?> actionEvent : queuedActions) {
            if (actionEvent.getWalkablePolicy() != WalkablePolicy.WALKABLE) {
                actionEvent.cancel();
                queuedActions.remove(actionEvent);
            }
        }
    }
References currentAction, com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, queuedActions, and com.runehive.game.action.policy.WalkablePolicy.WALKABLE.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), and com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute().
execute() [1/2]
public< A extends Action<?> > void com.runehive.game.action.ActionManager.execute (A action) package
Definition at line 38 of file ActionManager.java.
{
        execute(action, true);
    }
References execute().
Referenced by com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride(), com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride(), com.runehive.content.wintertodt.Wintertodt.chopRoot(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.hunter.Hunter.clickObject(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.emote.Emote.execute(), execute(), com.runehive.content.wintertodt.Wintertodt.feedBrazier(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), com.runehive.content.wintertodt.Wintertodt.fletch(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.wintertodt.Wintertodt.mixHerb(), sequence(), com.runehive.content.wintertodt.Wintertodt.shootFlame(), com.runehive.content.skill.impl.smithing.Smelting.smelt(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fishing.Fishing.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.skill.impl.mining.Mining.start(), com.runehive.content.wintertodt.Wintertodt.takeHerb(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), com.runehive.content.skill.impl.firemaking.Firemaking.useItem(), com.runehive.content.skill.impl.herblore.Herblore.useItem(), and com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem().
execute() [2/2]
public< A extends Action<?> > void com.runehive.game.action.ActionManager.execute (A action, boolean override) package
Adds an Action to the queue.
Definition at line 43 of file ActionManager.java.
{
        //if current action is priorized stop.
        if (currentAction != null && currentAction.isRunning() && currentAction.prioritized()) {
            return;
        }
        //if there is already an action active and we don't want to override
        //we ignore.
        //if u don't want to override but you also dont want to ignore
        //queue the action.
        if (currentAction != null && currentAction.isRunning() && !override) {
            return;
        }
        //if there is an action active, make sure we stop it before running
        //another action.
        if (currentAction != null && currentAction.isRunning()) {
            currentAction.cancel();
        }
        //finally submit the action.
        World.schedule(currentAction = action);
    }
References currentAction, and com.runehive.game.world.World.schedule().
getCurrentAction()
Action<?> com.runehive.game.action.ActionManager.getCurrentAction ()
Gets the current action.
Definition at line 124 of file ActionManager.java.
{
        return currentAction;
    }
References currentAction.
queue()
public< A extends Action<?> > void com.runehive.game.action.ActionManager.queue (A action) package
Queues the specified action.
Definition at line 34 of file ActionManager.java.
{
        queuedActions.add(action);
    }
References queuedActions.
reset()
void com.runehive.game.action.ActionManager.reset ()
Resets all the actions for the underlying Mob.
Definition at line 82 of file ActionManager.java.
{
        cancel();
        cancelQueuedActions();
    }
References cancel(), and cancelQueuedActions().
sequence()
void com.runehive.game.action.ActionManager.sequence ()
Sequences the pending actions, and as soon as the current action has stopped, it executes the head of the queue.
Definition at line 25 of file ActionManager.java.
{
        if (queuedActions.isEmpty() || (currentAction != null && currentAction.isRunning())) {
            return;
        }
        execute(this.currentAction = queuedActions.poll(), true);
    }
References currentAction, execute(), and queuedActions.
toString()
String com.runehive.game.action.ActionManager.toString ()
Definition at line 129 of file ActionManager.java.
{
        return String.format("ActionManager[size=%s, action=%s]", queuedActions.size(), currentAction);
    }
References currentAction, and queuedActions.
Member Data Documentation
currentAction
Action<?> com.runehive.game.action.ActionManager.currentAction = null private
The current action.
Definition at line 22 of file ActionManager.java.
Referenced by cancel(), cancel(), clearNonWalkableActions(), execute(), getCurrentAction(), sequence(), and toString().
queuedActions
final Queue<Action<?> > com.runehive.game.action.ActionManager.queuedActions = new ArrayDeque<>() private
A queue of Action object.
Definition at line 19 of file ActionManager.java.
Referenced by cancel(), cancelQueuedActions(), clearNonWalkableActions(), queue(), sequence(), and toString().
The documentation for this class was generated from the following file:
java/com/runehive/game/action/ActionManager.java