RuneHive-Game: com.runehive.game.world.entity.mob.Mob Class Reference
com.runehive.game.world.entity.mob.Mob Class Reference abstract
Handles the mob class.
Public Member Functions
void animate (Animation animation)
Plays an animation.
void animate (Animation animation, final boolean override)
Plays an animation.
void animate (int animation)
void animate (int animation, boolean override)
void appendBonus (int index, int amount)
void attack (Mob target)
void clearTeleportTarget ()
Resets the teleport target.
void damage (Hit... hits)
Hit decrementHealth (Hit hit)
void face (Direction direction)
Sets the client update flag to face a certain direction.
void face (GameObject object)
Sets the client update flag to face a certain direction.
void face (Mob mob)
void face (Position position)
Sets the client update flag to face a certain direction.
void follow (Mob target)
void forceMove (int animation, int x, int y)
void forceMove (int delay, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
void forceMove (int delay, int delay2, int animation, int animationDelay, int startSpeed, int endSpeed, Position offset, Direction direction)
Creates a force movement action for an entity.
void forceMove (int delay, int delay2, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
Optional< Animation > getAnimation ()
int getBonus (int index)
int[] getBonuses ()
abstract Combat<? extends Mob > getCombat ()
The combat of the mob.
int getCurrentHealth ()
ForceMovement getForceMovement ()
Optional< Graphic > getGraphic ()
int getId ()
int getListIndex ()
int getMaximumHealth ()
final Npc getNpc ()
final Player getPlayer ()
final MutableNumber getPoisonDamage ()
PoisonType getPoisonType ()
int getPriorityIndex ()
abstract< T extends Mob > CombatStrategy<? super T > getStrategy ()
The combat strategy of the mob.
int getTransformId ()
MutableNumber getVenomDamage ()
void graphic (Graphic graphic)
Plays a graphic.
void graphic (Graphic graphic, boolean override)
Plays a graphic.
void graphic (int graphic)
boolean hasPriorityIndex (Mob other)
void heal (int amount)
boolean inActivity ()
boolean inActivity (ActivityType type)
void interact (Mob mob)
Sets the mob interacting with another mob.
abstract boolean isAutoRetaliate ()
State of the mob's auto retaliate.
boolean isDead ()
boolean isFixingInside ()
final boolean isNpc ()
Check if an entity is an npc.
final boolean isNpc (BooleanInterface< Npc > condition)
Check if an entity is an npc.
final boolean isPlayer ()
Check if an entity is a player.
final boolean isPlayer (Function< Player, Boolean > condition)
Check if an entity is a player.
final boolean isPoisoned ()
boolean isUpdateRequired ()
Checks if mob requires an update.
final boolean isVenomed ()
Mob (Position position)
Constructs a new Mob.
Mob (Position position, boolean visible)
void move (Position position)
Moves the mob to a set position.
void poison (PoisonType type)
Applies poison with an intensity of type to the entity.
final void reset ()
Resets the mob after an update.
void resetAnimation ()
void resetFace ()
Resets the mob's face location.
void resetGraphic ()
final void resetWaypoint ()
Resets the waypoint.
void runTo (Position destination)
abstract void sequence ()
The method which is invoked every tick.
void setActivity (Activity activity)
void setBonus (int equipSlot, int bonus)
void setBonuses (int[] bonuses)
void setDead (boolean dead)
void setFixingInside (boolean fixingInside)
void setForceMovement (ForceMovement forceMovement)
void setListIndex (int listIndex)
void speak (String forceChat)
Sets the mob's forced chat.
void takeStep ()
void transform (int transformId)
void transform (int transformId, boolean reload)
Transforms the mob.
void unpoison ()
void unvenom ()
void venom ()
Applies venom to the entity.
void walk (Position destination, boolean ignoreClip)
void walk (Position position)
void walkExactlyTo (Position position)
void walkExactlyTo (Position position, Runnable onDestination)
void walkTo (Interactable target, boolean clearAction, Runnable onDestination)
void walkTo (Interactable target, Runnable onDestination)
void walkTo (Position position)
void walkTo (Position position, Runnable onDestination)
void writeDamage (Hit hit)
void writeFakeDamage (Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.Entity
abstract void addToRegion (Region region)
Adds this entity to the specified region.
Entity (Position position)
Entity (Position position, boolean visible)
abstract boolean equals (Object obj)
Position getCenterPosition ()
int getHeight ()
int getIndex ()
abstract String getName ()
Gets the name of this entity.
Position getPosition ()
Region getRegion ()
abstract EntityType getType ()
Gets the EntityType.
int getX ()
int getY ()
abstract int hashCode ()
boolean is (EntityType type)
final boolean isCustomObject ()
Check if an entity is an object.
final boolean isRegistered ()
final boolean isStaticObject ()
Check if an entity is an object.
boolean isValid ()
Validates this npc based on its current region and registered state.
boolean isVisible ()
int length ()
void onStep ()
abstract void register ()
Registers an entity to the World.
abstract void removeFromRegion (Region region)
Removes this entity from the specified region.
void setIndex (int index)
void setLength (int length)
void setPosition (Position position)
void setVisible (boolean visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
void setZ (int z)
String toString ()
abstract void unregister ()
Unregisters an entity from the World.
int width ()
Static Public Member Functions
static boolean pathfinderProjectiles (Mob source)
Static Public Member Functions inherited from com.runehive.game.world.Interactable
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Public Attributes
ActionManager action = new ActionManager()
Activity activity
final GenericAttributes attributes = new GenericAttributes()
boolean blockFace
boolean blockInteract
Stopwatch damageImmunity = Stopwatch.start()
Position facePosition
Hit firstHit
List< Mob > followers = new LinkedList<>()
String forceChat
ForceMovement forceMovement
boolean forceWalking
final Stopwatch freezeImmunity = Stopwatch.start()
int id = -1
boolean inTeleport
Mob interactingWith
Position lastPosition
final Locking locking = new Locking(this)
MobAnimation mobAnimation = new MobAnimation(updateFlags)
final Movement movement = new Movement(this)
transient long nextAnimation
boolean pathfinderProjectiles = false
boolean positionChange
PrayerBook prayer = new PrayerBook()
boolean regionChange
Hit secondHit
final SkillManager skills = new SkillManager(this)
final SkillManager skills_copy = new SkillManager(this)
boolean teleporting
boolean teleportRegion
Position teleportTarget
final EnumSet< UpdateFlag > updateFlags = EnumSet.noneOf(UpdateFlag.class)
Public Attributes inherited from com.runehive.game.world.entity.Entity
int instance = DEFAULT_INSTANCE
Protected Member Functions
abstract void appendDeath ()
Handles the mob death.
void setWaypoint (Waypoint waypoint)
Protected Member Functions inherited from com.runehive.game.world.entity.Entity
Entity destroy ()
Destroys this entity.
void setRegistered (boolean registered)
Protected Attributes
Waypoint cachedWaypoint
Private Attributes
Optional< Animation > animation = Optional.empty()
int[] bonuses = EMPTY_BONUSES
boolean dead
boolean fixingInside
Optional< Graphic > graphic = Optional.empty()
int listIndex
final MutableNumber poisonDamage = new MutableNumber()
PoisonType poisonType
int transformId
final MutableNumber venomDamage = new MutableNumber()
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.Entity
static final int DEFAULT_INSTANCE = 0
Detailed Description
Handles the mob class.
Author
Daniel
Chex
Definition at line 66 of file Mob.java.
Constructor & Destructor Documentation
Mob() [1/2]
com.runehive.game.world.entity.mob.Mob.Mob (Position position)
Constructs a new Mob.
Definition at line 114 of file Mob.java.
{
        super(position);
        this.lastPosition = position.copy();
    }
References com.runehive.game.world.entity.Entity.position.
Referenced by attack(), face(), follow(), hasPriorityIndex(), interact(), com.runehive.game.world.entity.mob.npc.Npc.Npc(), pathfinderProjectiles(), and transform().
Mob() [2/2]
com.runehive.game.world.entity.mob.Mob.Mob (Position position, boolean visible)
Definition at line 119 of file Mob.java.
{
        super(position, visible);
        this.lastPosition = position.copy();
    }
References com.runehive.game.world.entity.Entity.position, and com.runehive.game.world.entity.Entity.visible.
Member Function Documentation
animate() [1/4]
void com.runehive.game.world.entity.mob.Mob.animate (Animation animation)
Plays an animation.
Definition at line 145 of file Mob.java.
{
        animate(animation, false);
    }
References animate(), and animation.
animate() [2/4]
void com.runehive.game.world.entity.mob.Mob.animate (Animation animation, final boolean override)
Plays an animation.
Definition at line 163 of file Mob.java.
{
        final long now = System.currentTimeMillis();
        if (!override && (nextAnimation > now || updateFlags.contains(UpdateFlag.ANIMATION))) {
            return;
        }
        final Optional<Animation> result = Optional.ofNullable(animation);
        animation = result.orElse(Animation.RESET);
        final AnimationDefinition definition =
                animation == Animation.RESET
                        ? null
                        : AnimationDefinitionDecoder.definitions.get(animation.getId());
        if (definition != null) {
            nextAnimation = now + definition.durationTime + 600;
        }
        this.animation = result;
        this.updateFlags.add(UpdateFlag.ANIMATION);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.ANIMATION, animation, com.runehive.fs.cache.decoder.AnimationDefinitionDecoder.definitions, nextAnimation, com.runehive.game.Animation.RESET, and updateFlags.
animate() [3/4]
void com.runehive.game.world.entity.mob.Mob.animate (int animation)
Definition at line 134 of file Mob.java.
{
        animate(animation, false);
    }
References animate(), and animation.
Referenced by animate(), animate(), animate(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.block(), com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.activity.impl.kraken.KrakenActivity.cleanup(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.skill.impl.hunter.trap.TrapManager.dismantle(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.game.action.impl.FlaxPickingAction.execute(), com.runehive.content.wintertodt.Wintertodt.feedBrazier(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.wintertodt.Wintertodt.fletch(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleLogout(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.hit(), com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.wintertodt.Wintertodt.mixHerb(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onCancel(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsActivity.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneWallClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SwingAcrossCableInteraction.onExecution(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.combat.cannon.CannonManager.pickup(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonAttack(), com.runehive.content.bot.PlayerBot.pot(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.lms.LMSGame.reset(), com.runehive.content.lms.LMSGame.rollChest(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendAnimation(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.sendAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff(), com.runehive.game.world.entity.combat.strategy.player.special.range.ArmadylCrossbow.sendStuff(), com.runehive.game.world.entity.combat.strategy.player.special.range.CrawsBow.sendStuff(), com.runehive.game.world.entity.combat.strategy.player.special.range.DragonThrownaxe.sendStuff(), com.runehive.game.world.entity.combat.strategy.player.special.range.MagicShortbow.sendStuff(), com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.sendStuff(), com.runehive.content.ai.LazyAIManager.showGptInstructionsWithGreeting(), com.runehive.content.activity.inferno.InfernoBoss.spawnbosswave(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.activity.infernomobs.Jalimkot.Burrow.start(), com.runehive.content.activity.infernomobs.JalTokJad.RangedAttack.start(), com.runehive.content.skill.impl.mining.Mining.start(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.MagicAttack.start(), com.runehive.game.world.entity.combat.attack.listener.npc.DarkBeast.MagicAttack.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Gowler.MagicAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.TeleGrab.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.TeleGrab.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.start(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.start(), com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.start(), com.runehive.content.wintertodt.Wintertodt.takeHerb(), com.runehive.content.activity.impl.kraken.KrakenActivity.transform(), and com.runehive.content.skill.impl.herblore.Herblore.useItem().
animate() [4/4]
void com.runehive.game.world.entity.mob.Mob.animate (int animation, boolean override)
Definition at line 138 of file Mob.java.
{
        animate(new Animation(animation), override);
    }
References animate(), and animation.
appendBonus()
void com.runehive.game.world.entity.mob.Mob.appendBonus (int index, int amount)
Definition at line 688 of file Mob.java.
{
        if (bonuses == EMPTY_BONUSES)
            bonuses = new int[EMPTY_BONUSES.length];
        bonuses[index] += amount;
    }
References bonuses, and com.runehive.game.world.entity.Entity.index.
appendDeath()
abstract void com.runehive.game.world.entity.mob.Mob.appendDeath () abstract protected
Handles the mob death.
Reimplemented in com.runehive.game.world.entity.mob.npc.Npc, and com.runehive.game.world.entity.mob.player.Player.
Referenced by decrementHealth().
attack()
void com.runehive.game.world.entity.mob.Mob.attack (Mob target)
Definition at line 424 of file Mob.java.
{
        Waypoint waypoint = new CombatWaypoint(this, target);
        if (cachedWaypoint == null || (!cachedWaypoint.isRunning() || !waypoint.equals(cachedWaypoint))) {
            resetWaypoint();
            movement.reset();
            action.clearNonWalkableActions();
            World.schedule(cachedWaypoint = waypoint);
        }
    }
References action, cachedWaypoint, com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.equals(), Mob(), movement, resetWaypoint(), and com.runehive.game.world.World.schedule().
Referenced by com.runehive.content.activity.inferno.InfernoBoss.spawnbosswave(), com.runehive.content.activity.inferno.Inferno.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack.start().
clearTeleportTarget()
void com.runehive.game.world.entity.mob.Mob.clearTeleportTarget ()
Resets the teleport target.
Definition at line 536 of file Mob.java.
{
        this.teleportTarget = null;
    }
damage()
void com.runehive.game.world.entity.mob.Mob.damage (Hit... hits)
Definition at line 443 of file Mob.java.
{
        for (Hit hit : hits)
            getCombat().queueDamage(hit);
    }
References getCombat().
Referenced by com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.block(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), decrementHealth(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.content.lms.LMSGame.handleFogDamage(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.handleRecoil(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.hitEvent(), com.runehive.content.consume.PotionData.modifySkill(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.TeleGrab.start(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start().
decrementHealth()
Hit com.runehive.game.world.entity.mob.Mob.decrementHealth (Hit hit)
Definition at line 478 of file Mob.java.
{
        if (getCurrentHealth() - hit.getDamage() < 0)
            hit.modifyDamage(damage -> getCurrentHealth());
        skills.modifyLevel(level -> level - hit.getDamage(), Skill.HITPOINTS, 0, getCurrentHealth());
        skills.refresh(Skill.HITPOINTS);
        if (getCurrentHealth() < 1)
            appendDeath();
        return hit;
    }
References appendDeath(), damage(), getCurrentHealth(), com.runehive.game.world.entity.combat.hit.Hit.getDamage(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.game.world.entity.combat.hit.Hit.modifyDamage(), and skills.
Referenced by writeDamage().
face() [1/4]
void com.runehive.game.world.entity.mob.Mob.face (Direction direction)
Sets the client update flag to face a certain direction.
Definition at line 317 of file Mob.java.
{
        if (blockFace)
            return;
        Position position = getPosition().transform(direction.getFaceLocation());
        if (!position.equals(facePosition)) {
            this.facePosition = position;
            this.updateFlags.add(UpdateFlag.FACE_COORDINATE);
        }
    }
References blockFace, com.runehive.game.world.entity.mob.UpdateFlag.FACE_COORDINATE, facePosition, com.runehive.game.world.entity.mob.Direction.getFaceLocation(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.position, and com.runehive.game.world.position.Position.transform().
face() [2/4]
void com.runehive.game.world.entity.mob.Mob.face (GameObject object)
Sets the client update flag to face a certain direction.
Definition at line 289 of file Mob.java.
{
        if (blockFace)
            return;
        if (object == null || object.getPosition().equals(facePosition))
            return;
        this.facePosition = object.getPosition();
        this.updateFlags.add(UpdateFlag.FACE_COORDINATE);
    }
References blockFace, com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.mob.UpdateFlag.FACE_COORDINATE, facePosition, and com.runehive.game.world.entity.Entity.getPosition().
Referenced by face(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.content.ai.AIDialogueHandler.handleAICommand(), com.runehive.content.ai.LazyAIManager.handleGandalfAIClick(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onExecution(), com.runehive.content.pet.Pets.onLogin(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.content.lms.LMSGame.reset(), com.runehive.content.activity.inferno.InfernoBoss.spawnbosswave(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.content.activity.inferno.Inferno.start(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2.start(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneWallClimbInteraction.start(), com.runehive.content.skill.impl.mining.Mining.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.start().
face() [3/4]
void com.runehive.game.world.entity.mob.Mob.face (Mob mob)
Definition at line 298 of file Mob.java.
{
        face(mob.getPosition());
    }
References face(), and Mob().
face() [4/4]
void com.runehive.game.world.entity.mob.Mob.face (Position position)
Sets the client update flag to face a certain direction.
Definition at line 305 of file Mob.java.
{
        if (blockFace)
            return;
        if (!position.equals(facePosition)) {
            this.facePosition = position;
            this.updateFlags.add(UpdateFlag.FACE_COORDINATE);
        }
    }
References blockFace, com.runehive.game.world.entity.mob.UpdateFlag.FACE_COORDINATE, facePosition, and com.runehive.game.world.entity.Entity.position.
follow()
void com.runehive.game.world.entity.mob.Mob.follow (Mob target)
Definition at line 414 of file Mob.java.
{
        Waypoint waypoint = new FollowWaypoint(this, target);
        if (cachedWaypoint == null || (!cachedWaypoint.isRunning() || !waypoint.equals(cachedWaypoint))) {
            resetWaypoint();
            movement.reset();
            action.clearNonWalkableActions();
            World.schedule(cachedWaypoint = waypoint);
        }
    }
References action, cachedWaypoint, com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.equals(), Mob(), movement, resetWaypoint(), and com.runehive.game.world.World.schedule().
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.findRoute(), com.runehive.content.pet.Pets.onLogin(), and com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start().
forceMove() [1/4]
void com.runehive.game.world.entity.mob.Mob.forceMove (int animation, int x, int y)
Definition at line 255 of file Mob.java.
{
        forceMove(0, 0, animation, 0, 0, 0, new Position(x, y), Direction.NORTH);
    }
References animation, forceMove(), and com.runehive.game.world.entity.mob.Direction.NORTH.
Referenced by com.runehive.game.action.impl.RevShortcutAction.execute(), forceMove(), forceMove(), forceMove(), com.runehive.content.skill.impl.agility.obstacle.impl.ClimbOverInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.RopeSwingInteraction.onExecution(), and com.runehive.content.skill.impl.agility.obstacle.impl.SteppingStonesInteraction.onExecution().
forceMove() [2/4]
void com.runehive.game.world.entity.mob.Mob.forceMove (int delay, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
Definition at line 259 of file Mob.java.
{
        forceMove(delay, 0, animation, startSpeed, endSpeed, offset, direction);
    }
References animation, and forceMove().
forceMove() [3/4]
void com.runehive.game.world.entity.mob.Mob.forceMove (int delay, int delay2, int animation, int animationDelay, int startSpeed, int endSpeed, Position offset, Direction direction)
Creates a force movement action for an entity.
Definition at line 270 of file Mob.java.
{
        ForceMovement movement = new ForceMovement(getPosition().copy(), offset, startSpeed, endSpeed, direction);
        World.schedule(new ForceMovementTask(this, delay, delay2, movement, new Animation(animation, animationDelay)));
    }
References animation, com.runehive.game.world.entity.Entity.getPosition(), movement, and com.runehive.game.world.World.schedule().
forceMove() [4/4]
void com.runehive.game.world.entity.mob.Mob.forceMove (int delay, int delay2, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
Definition at line 263 of file Mob.java.
{
        forceMove(delay, delay2, animation, 0, startSpeed, endSpeed, offset, direction);
    }
References animation, and forceMove().
getAnimation()
Optional< Animation > com.runehive.game.world.entity.mob.Mob.getAnimation ()
Definition at line 708 of file Mob.java.
{
        return animation;
    }
References animation.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendAnimationMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendAnimationMask().
getBonus()
int com.runehive.game.world.entity.mob.Mob.getBonus (int index)
Reimplemented in com.runehive.game.world.entity.mob.npc.Npc.
Definition at line 680 of file Mob.java.
{
        return bonuses[index];
    }
References bonuses, and com.runehive.game.world.entity.Entity.index.
Referenced by com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getAttackBonus(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getAttackBonus(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getBaseDamage(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getDefenceBonus(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getDefenceBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getDefenceBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEquipmentBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getGearAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getRangeBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStrengthBonus(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressiveBonus(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAggressiveBonus(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDefensiveBonus(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensiveBonus(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensiveBonus(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyOffensiveBonus(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyOffensiveBonus(), and com.runehive.game.world.entity.combat.formula.RangedFormula.modifyOffensiveBonus().
getBonuses()
int[] com.runehive.game.world.entity.mob.Mob.getBonuses ()
Reimplemented in com.runehive.game.world.entity.mob.npc.Npc.
Definition at line 676 of file Mob.java.
{
        return bonuses;
    }
References bonuses.
getCombat()
abstract Combat<? extends Mob > com.runehive.game.world.entity.mob.Mob.getCombat () abstract
The combat of the mob.
Reimplemented in com.runehive.game.world.entity.mob.npc.Npc, and com.runehive.game.world.entity.mob.player.Player.
Referenced by com.runehive.content.activity.Activity.add(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.block(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.canAttack(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), damage(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.execute(), com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.finishOutgoing(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.finishOutgoing(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getAttackBonus(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getDefenceBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getDefenceRoll(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getDefenceRoll(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getDefenceRoll(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getEffectiveLevel(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getEffectiveLevel(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getEffectiveRanged(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getOtherBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStyleBonus(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getStyleBonus(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.handleRecoil(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), com.runehive.game.world.entity.combat.magic.MagicImpact.hitEvent(), com.runehive.game.world.entity.combat.ranged.RangedEffects.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.hitEvent(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplat(), com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.init(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAggressive(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressive(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAggressive(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAggressiveBonus(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressiveBonus(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAggressiveBonus(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDefensive(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensive(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensive(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDefensiveBonus(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensiveBonus(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensiveBonus(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyOffensiveBonus(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyOffensiveBonus(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyOffensiveBonus(), move(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.preKill(), com.runehive.game.world.entity.combat.attack.FormulaFactory.rollDefensive(), com.runehive.game.world.entity.combat.attack.FormulaFactory.rollOffensive(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start(), com.runehive.game.world.entity.combat.CombatUtil.validate(), com.runehive.game.world.entity.combat.CombatUtil.validateMobs(), walkTo(), walkTo(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.withinDistance(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.withinDistance(), and writeDamage().
getCurrentHealth()
int com.runehive.game.world.entity.mob.Mob.getCurrentHealth ()
Definition at line 652 of file Mob.java.
{
        if (isNpc()) {
            Npc npc = (Npc) this;
            switch (npc.id) {
                case Wintertodt.PYROMANCER, Wintertodt.INCAPACITATED_PYROMANCER -> {
                    return npc.pyroHealth;
                }
            }
        }
        return skills.getLevel(Skill.HITPOINTS);
    }
References com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.content.wintertodt.Wintertodt.INCAPACITATED_PYROMANCER, isNpc(), com.runehive.content.wintertodt.Wintertodt.PYROMANCER, and skills.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask(), com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.game.world.entity.combat.attack.listener.npc.Alkahrid.block(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.canAttack(), decrementHealth(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.eat(), com.runehive.content.bot.botclass.impl.PureMelee.eat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.eat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.eat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.eat(), com.runehive.content.bot.PlayerBot.endFight(), com.runehive.content.itemaction.impl.DragonfireShield.equipment(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.finishIncoming(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getHits(), heal(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), com.runehive.content.bot.botclass.impl.PureMelee.hit(), com.runehive.content.bot.botclass.impl.PureRangeMelee.hit(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.hit(), com.runehive.content.bot.botclass.impl.ZerkerMelee.hit(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplat(), com.runehive.content.bot.PlayerBot.loopCombat(), com.runehive.game.world.entity.combat.attack.listener.item.DharokListener.modifyDamage(), com.runehive.content.consume.PotionData.modifySkill(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextHit(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.pot(), com.runehive.content.bot.botclass.impl.PureMelee.pot(), com.runehive.content.bot.botclass.impl.PureRangeMelee.pot(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.pot(), com.runehive.content.bot.botclass.impl.ZerkerMelee.pot(), com.runehive.net.packet.out.SendEntityFeed.SendEntityFeed(), com.runehive.content.activity.inferno.InfernoBoss.spawnbosswave(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.update(), and writeDamage().
getForceMovement()
ForceMovement com.runehive.game.world.entity.mob.Mob.getForceMovement ()
Definition at line 597 of file Mob.java.
{
        return forceMovement;
    }
References forceMovement.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendForceMovementMask().
getGraphic()
Optional< Graphic > com.runehive.game.world.entity.mob.Mob.getGraphic ()
Definition at line 712 of file Mob.java.
{
        return graphic;
    }
References graphic.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendGfxMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendGraphicMask().
getId()
int com.runehive.game.world.entity.mob.Mob.getId ()
Definition at line 767 of file Mob.java.
                       {
        return id;
    }
References id.
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack.getAttackAnimation(), and com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack.getHits().
getListIndex()
int com.runehive.game.world.entity.mob.Mob.getListIndex ()
Definition at line 700 of file Mob.java.
{
        return listIndex;
    }
References listIndex.
Referenced by getPriorityIndex(), and com.runehive.game.world.entity.mob.npc.Npc.getPriorityIndex().
getMaximumHealth()
int com.runehive.game.world.entity.mob.Mob.getMaximumHealth ()
Definition at line 664 of file Mob.java.
{
        if (isNpc()) {
            Npc npc = (Npc) this;
            switch (npc.id) {
                case Wintertodt.PYROMANCER, Wintertodt.INCAPACITATED_PYROMANCER -> {
                    return 24;
                }
            }
        }
        return skills.getMaxLevel(Skill.HITPOINTS);
    }
References com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.content.wintertodt.Wintertodt.INCAPACITATED_PYROMANCER, isNpc(), com.runehive.content.wintertodt.Wintertodt.PYROMANCER, and skills.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.activate(), com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask(), com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.game.world.entity.combat.attack.listener.npc.Alkahrid.block(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.eat(), com.runehive.content.bot.botclass.impl.PureMelee.eat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.eat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.eat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.eat(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.finishIncoming(), heal(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), com.runehive.content.bot.botclass.impl.PureMelee.hit(), com.runehive.content.bot.botclass.impl.PureRangeMelee.hit(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.hit(), com.runehive.content.bot.botclass.impl.ZerkerMelee.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.attack.listener.item.DharokListener.modifyDamage(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.pot(), com.runehive.content.bot.botclass.impl.PureMelee.pot(), com.runehive.content.bot.botclass.impl.PureRangeMelee.pot(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.pot(), com.runehive.content.bot.botclass.impl.ZerkerMelee.pot(), com.runehive.net.packet.out.SendEntityFeed.SendEntityFeed(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update().
getNpc()
final Npc com.runehive.game.world.entity.mob.Mob.getNpc ()
Definition at line 568 of file Mob.java.
{
        return (Npc) this;
    }
Referenced by com.runehive.content.activity.impl.kraken.KrakenActivity.add(), com.runehive.game.world.entity.mob.Viewport.add(), com.runehive.game.world.entity.mob.Viewport.canAdd(), com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.canAttack(), com.runehive.content.activity.impl.zulrah.ZulrahListener.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.content.skill.impl.fishing.Fishing.clickNpc(), com.runehive.content.skill.impl.hunter.Hunter.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.game.action.impl.NpcFaceAction.execute(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getDefenceNpc(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicLevelNpc(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getRangeDefenceLevelNpc(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.hit(), isNpc(), com.runehive.game.world.position.Position.isWithinDiagonalDistance(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextHit(), com.runehive.content.activity.Activity.onDeath(), com.runehive.content.activity.impl.barrows.Barrows.onDeath(), com.runehive.content.activity.impl.CerberusActivity.onDeath(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.kraken.KrakenActivity.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.content.activity.impl.VorkathActivity.onDeath(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.onDeath(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsListener.onKill(), com.runehive.game.world.World.sendKillFeed(), and transform().
getPlayer()
final Player com.runehive.game.world.entity.mob.Mob.getPlayer ()
Definition at line 648 of file Mob.java.
{
        return (Player) this;
    }
Referenced by com.runehive.game.world.entity.mob.Viewport.add(), com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer.attack(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block(), com.runehive.game.world.entity.combat.attack.listener.npc.Alkahrid.block(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.mob.Viewport.canAdd(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.canAttack(), com.runehive.content.activity.infernomobs.Jalimkot.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.PureMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.PureRangeMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.ZerkerMelee.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.canOtherAttack(), com.runehive.content.skill.impl.HarvestingSkillAction.canRun(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.game.action.impl.FlaxPickingAction.execute(), com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.execute(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEquipmentBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getGearAttackBonus(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.content.activity.infernomobs.MejRah.Ranged.hit(), com.runehive.game.world.entity.combat.attack.listener.item.AhrimListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.StarterAgsListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.StarterWhipListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ToragListener.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.SergeantStrongstack.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.TzKihListener.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Shockwave.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), isPlayer(), com.runehive.game.world.entity.combat.magic.MagicImpact.kbdShock(), com.runehive.game.world.entity.combat.magic.MagicImpact.lowerSkill(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), move(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.game.action.impl.ScatterAshAction.onExecute(), com.runehive.game.world.entity.combat.attack.listener.item.DharokListener.onKill(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate(), com.runehive.game.world.entity.mob.player.Player.sendInitialPackets(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.submitStrategy(), and com.runehive.game.world.entity.mob.player.Player.unregister().
getPoisonDamage()
final MutableNumber com.runehive.game.world.entity.mob.Mob.getPoisonDamage ()
Definition at line 628 of file Mob.java.
{
        return poisonDamage;
    }
References poisonDamage.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect().
getPoisonType()
PoisonType com.runehive.game.world.entity.mob.Mob.getPoisonType ()
Definition at line 636 of file Mob.java.
{
        return poisonType;
    }
References poisonType.
getPriorityIndex()
int com.runehive.game.world.entity.mob.Mob.getPriorityIndex ()
Reimplemented in com.runehive.game.world.entity.mob.npc.Npc.
Definition at line 759 of file Mob.java.
{
        return getListIndex();
    }
References getListIndex().
Referenced by hasPriorityIndex().
getStrategy()
abstract< T extends Mob > CombatStrategy<? super T > com.runehive.game.world.entity.mob.Mob.getStrategy () abstract
The combat strategy of the mob.
Reimplemented in com.runehive.game.world.entity.mob.npc.Npc, and com.runehive.game.world.entity.mob.player.Player.
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.block(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.block(), com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.canOtherAttack(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.finishIncoming(), com.runehive.game.world.entity.combat.CombatUtil.getHitDelay(), com.runehive.game.world.entity.combat.attack.FormulaFactory.getMaxHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.getModifiedMaxHit(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus(), com.runehive.game.world.entity.combat.attack.listener.item.OccultNecklaceListener.modifyDamage(), com.runehive.game.world.entity.combat.attack.listener.other.prayer.RigourListener.modifyDamage(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextHit(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.preDeath(), and com.runehive.content.activity.impl.kraken.KrakenActivityListener.withinDistance().
getTransformId()
int com.runehive.game.world.entity.mob.Mob.getTransformId ()
Definition at line 771 of file Mob.java.
{
        return transformId;
    }
References transformId.
getVenomDamage()
MutableNumber com.runehive.game.world.entity.mob.Mob.getVenomDamage ()
Definition at line 632 of file Mob.java.
{
        return venomDamage;
    }
References venomDamage.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect().
graphic() [1/3]
void com.runehive.game.world.entity.mob.Mob.graphic (Graphic graphic)
Plays a graphic.
Definition at line 156 of file Mob.java.
{
        graphic(graphic, false);
    }
References graphic.
graphic() [2/3]
void com.runehive.game.world.entity.mob.Mob.graphic (Graphic graphic, boolean override)
Plays a graphic.
Definition at line 186 of file Mob.java.
{
        Optional<Graphic> result = Optional.ofNullable(graphic);
        graphic = result.orElse(Graphic.RESET);
        if (!this.graphic.isPresent() || override || this.graphic.get().compareTo(graphic) > 0) {
            this.graphic = result;
            this.updateFlags.add(UpdateFlag.GRAPHICS);
        }
    }
References com.runehive.game.Graphic.compareTo(), graphic, com.runehive.game.world.entity.mob.UpdateFlag.GRAPHICS, and com.runehive.game.Graphic.RESET.
graphic() [3/3]
void com.runehive.game.world.entity.mob.Mob.graphic (int graphic)
Definition at line 149 of file Mob.java.
{
        graphic(new Graphic(graphic));
    }
References graphic.
hasPriorityIndex()
boolean com.runehive.game.world.entity.mob.Mob.hasPriorityIndex (Mob other)
Definition at line 763 of file Mob.java.
{
        return getPriorityIndex() < other.getPriorityIndex();
    }
References getPriorityIndex(), and Mob().
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.execute().
heal()
void com.runehive.game.world.entity.mob.Mob.heal (int amount)
Definition at line 489 of file Mob.java.
{
        int health = getCurrentHealth();
        if (health >= getMaximumHealth())
            return;
        skills.modifyLevel(hp -> health + amount, Skill.HITPOINTS, 0, getMaximumHealth());
        skills.refresh(Skill.HITPOINTS);
    }
References getCurrentHealth(), getMaximumHealth(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, and skills.
Referenced by com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener.block(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.content.activity.infernomobs.JalTokJad.Guardian.Guardian(), com.runehive.game.world.entity.combat.magic.MagicImpact.heal(), com.runehive.game.world.entity.combat.attack.listener.item.GuthansListner.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.preDeath(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), and com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.start().
inActivity() [1/2]
boolean com.runehive.game.world.entity.mob.Mob.inActivity ()
Definition at line 518 of file Mob.java.
{
        return activity != null;
    }
References activity.
Referenced by com.runehive.game.world.entity.mob.npc.Npc.appendDeath(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.content.event.EventDispatcher.execute(), inActivity(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.content.combat.Skulling.skull(), and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
inActivity() [2/2]
boolean com.runehive.game.world.entity.mob.Mob.inActivity (ActivityType type)
Definition at line 522 of file Mob.java.
{
        return inActivity() && activity.getType() == type;
    }
References activity, and inActivity().
interact()
void com.runehive.game.world.entity.mob.Mob.interact (Mob mob)
Sets the mob interacting with another mob.
Definition at line 278 of file Mob.java.
{
        if (blockInteract) {
            return;
        }
        this.interactingWith = mob;
        this.updateFlags.add(UpdateFlag.INTERACT);
    }
References blockInteract, com.runehive.game.world.entity.mob.UpdateFlag.INTERACT, and Mob().
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.findRoute(), com.runehive.content.pet.Pets.onLogin(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.start(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start().
isAutoRetaliate()
abstract boolean com.runehive.game.world.entity.mob.Mob.isAutoRetaliate () abstract
State of the mob's auto retaliate.
Reimplemented in com.runehive.game.world.entity.mob.npc.Npc, and com.runehive.game.world.entity.mob.player.Player.
isDead()
boolean com.runehive.game.world.entity.mob.Mob.isDead ()
Definition at line 640 of file Mob.java.
{
        return dead;
    }
References dead.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.content.bot.PlayerBot.endFight(), com.runehive.content.itemaction.impl.DragonfireShield.equipment(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handlePacket(), com.runehive.net.packet.in.UseItemPacketListener.handlePacket(), com.runehive.content.bot.PlayerBot.loopCombat(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.preDeath(), com.runehive.game.world.entity.mob.npc.Npc.sequence(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick(), and writeDamage().
isFixingInside()
boolean com.runehive.game.world.entity.mob.Mob.isFixingInside ()
Definition at line 751 of file Mob.java.
{
        return fixingInside;
    }
References fixingInside.
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.execute().
isNpc() [1/2]
final boolean com.runehive.game.world.entity.mob.Mob.isNpc ()
Check if an entity is an npc.
Definition at line 550 of file Mob.java.
{
        return getType() == EntityType.NPC;
    }
References com.runehive.game.world.entity.Entity.getType(), and com.runehive.game.world.entity.EntityType.NPC.
Referenced by com.runehive.content.activity.Activity.add(), com.runehive.content.activity.impl.kraken.KrakenActivity.add(), com.runehive.game.world.entity.mob.Viewport.add(), com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.mob.Viewport.canAdd(), com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.canAttack(), com.runehive.content.activity.impl.zulrah.ZulrahListener.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.getAttackDelay(), getCurrentHealth(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getEffectiveRanged(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEquipmentBonus(), getMaximumHealth(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getOtherBonus(), com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.hit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.isAccurate(), com.runehive.game.world.position.Position.isWithinDiagonalDistance(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDamage(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextHit(), com.runehive.content.activity.Activity.onDeath(), com.runehive.content.activity.impl.barrows.Barrows.onDeath(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.kraken.KrakenActivity.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.content.activity.impl.VorkathActivity.onDeath(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.onDeath(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsListener.onKill(), com.runehive.game.world.entity.combat.magic.MagicImpact.poison(), com.runehive.game.world.World.sendKillFeed(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBarrage(), com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBurst(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.start(), and transform().
isNpc() [2/2]
final boolean com.runehive.game.world.entity.mob.Mob.isNpc (BooleanInterface< Npc > condition)
Check if an entity is an npc.
Definition at line 557 of file Mob.java.
{
        return getType() == EntityType.NPC && condition.activated(getNpc());
    }
References com.runehive.util.generic.BooleanInterface< T >.activated(), getNpc(), com.runehive.game.world.entity.Entity.getType(), and com.runehive.game.world.entity.EntityType.NPC.
isPlayer() [1/2]
final boolean com.runehive.game.world.entity.mob.Mob.isPlayer ()
Check if an entity is a player.
Definition at line 564 of file Mob.java.
{
        return getType() == EntityType.PLAYER;
    }
References com.runehive.game.world.entity.Entity.getType(), and com.runehive.game.world.entity.EntityType.PLAYER.
Referenced by com.runehive.game.world.entity.mob.Viewport.add(), com.runehive.net.packet.out.SendNpcUpdate.appendFaceEntityMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceEntityMask(), com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer.attack(), com.runehive.game.world.entity.combat.attack.listener.npc.Alkahrid.block(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.game.world.entity.mob.Viewport.canAdd(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.canAttack(), com.runehive.content.activity.impl.pestcontrol.PestControlListener.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.canOtherAttack(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.execute(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getEffectiveRanged(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEquipmentBonus(), com.runehive.net.packet.out.SendEntityFeed.getOpponent(), com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.hit(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.content.activity.infernomobs.MejRah.Ranged.hit(), com.runehive.game.world.entity.combat.attack.listener.item.AhrimListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ToragListener.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.SergeantStrongstack.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.TzKihListener.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Shockwave.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.hit(), com.runehive.content.activity.impl.pestcontrol.PestControlListener.hitsplat(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.PinkDragonfireAttack.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonMace.hitsplat(), com.runehive.game.world.entity.combat.magic.MagicImpact.kbdShock(), com.runehive.game.world.entity.combat.magic.MagicImpact.lowerSkill(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDamage(), move(), com.runehive.content.activity.impl.barrows.Barrows.onDeath(), com.runehive.content.activity.impl.CerberusActivity.onDeath(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsActivity.onDeath(), com.runehive.content.activity.impl.kraken.KrakenActivity.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.game.world.entity.combat.attack.listener.item.DharokListener.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.onKill(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill(), com.runehive.game.ProjectileTest.ProjectileTest(), com.runehive.game.world.entity.mob.Viewport.shouldRemove(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.start(), com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.start(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.submitStrategy(), com.runehive.game.world.entity.combat.magic.MagicImpact.teleblock(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.twistedBowBonus(), and com.runehive.content.activity.impl.kraken.KrakenActivityListener.withinDistance().
isPlayer() [2/2]
final boolean com.runehive.game.world.entity.mob.Mob.isPlayer (Function< Player, Boolean > condition)
Check if an entity is a player.
Definition at line 575 of file Mob.java.
{
        return getType() == EntityType.PLAYER && condition.apply(getPlayer());
    }
References getPlayer(), com.runehive.game.world.entity.Entity.getType(), and com.runehive.game.world.entity.EntityType.PLAYER.
isPoisoned()
final boolean com.runehive.game.world.entity.mob.Mob.isPoisoned ()
Definition at line 620 of file Mob.java.
{
        return poisonDamage.get() > 0;
    }
References poisonDamage.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect(), and com.runehive.game.world.entity.combat.magic.MagicImpact.poison().
isUpdateRequired()
boolean com.runehive.game.world.entity.mob.Mob.isUpdateRequired ()
Checks if mob requires an update.
Definition at line 543 of file Mob.java.
{
        return !updateFlags.isEmpty();
    }
References updateFlags.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.addNewNpc(), com.runehive.net.packet.out.SendNpcUpdate.encode(), com.runehive.net.packet.out.SendPlayerUpdate.encode(), com.runehive.net.packet.out.SendNpcUpdate.updateMovement(), com.runehive.net.packet.out.SendPlayerUpdate.updateMovement(), com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
isVenomed()
final boolean com.runehive.game.world.entity.mob.Mob.isVenomed ()
Definition at line 624 of file Mob.java.
{
        return venomDamage.get() > 0;
    }
References venomDamage.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect().
move()
void com.runehive.game.world.entity.mob.Mob.move (Position position)
Moves the mob to a set position.
Definition at line 340 of file Mob.java.
{
        if (regionChange)
            return;
        if (isPlayer() && !getPlayer().interfaceManager.isClear())
            getPlayer().interfaceManager.close(false);
        setPosition(position);
        if (Utility.isRegionChange(position, lastPosition)) {
            regionChange = true;
        } else {
            positionChange = true;
        }
        teleportRegion = true;
        getCombat().reset();
        resetFace();
        locking.lock(599, TimeUnit.MILLISECONDS, LockType.MASTER);
        onStep();
    }
References com.runehive.game.world.entity.mob.player.InterfaceManager.close(), getCombat(), getPlayer(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, isPlayer(), com.runehive.util.Utility.isRegionChange(), lastPosition, locking, com.runehive.game.world.entity.mob.data.LockType.MASTER, com.runehive.game.world.entity.Entity.onStep(), com.runehive.game.world.entity.Entity.position, positionChange, regionChange, resetFace(), com.runehive.game.world.entity.Entity.setPosition(), and teleportRegion.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.content.skill.impl.runecrafting.Runecraft.click(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.game.action.impl.RevShortcutAction.execute(), com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.findRoute(), com.runehive.content.gambling.impl.FlowerPoker.gamble(), com.runehive.content.ai.AIDialogueHandler.handleAICommand(), com.runehive.content.ai.LazyAIManager.handleGandalfAIClick(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.activity.Activity.onDeath(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsActivity.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlLobby.onEnter(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneWallClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction2.onExecution(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.content.bot.PlayerBot.postDeath(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack.start(), and com.runehive.content.activity.impl.barrows.BarrowsUtility.teleportPlayer().
pathfinderProjectiles()
boolean com.runehive.game.world.entity.mob.Mob.pathfinderProjectiles (Mob source) static
Definition at line 196 of file Mob.java.
{
        final String name = source.getName().toLowerCase();
        return "imp".equals(name) || name.contains("impling");
    }
References com.runehive.game.world.entity.Entity.getName(), and Mob().
poison()
void com.runehive.game.world.entity.mob.Mob.poison (PoisonType type)
Applies poison with an intensity of type to the entity.
Definition at line 500 of file Mob.java.
{
        poisonType = type;
        CombatUtil.effect(this, CombatEffectType.POISON);
    }
References com.runehive.game.world.entity.combat.CombatUtil.effect(), com.runehive.game.world.entity.combat.effect.CombatEffectType.POISON, and poisonType.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect(), and com.runehive.game.world.entity.combat.magic.MagicImpact.poison().
reset()
final void com.runehive.game.world.entity.mob.Mob.reset ()
Resets the mob after an update.
Definition at line 241 of file Mob.java.
{
        resetAnimation();
        resetGraphic();
    }
References resetAnimation(), and resetGraphic().
resetAnimation()
void com.runehive.game.world.entity.mob.Mob.resetAnimation ()
Definition at line 716 of file Mob.java.
{
        this.animation = Optional.empty();
    }
Referenced by reset().
resetFace()
void com.runehive.game.world.entity.mob.Mob.resetFace ()
Resets the mob's face location.
Definition at line 330 of file Mob.java.
{
        if (blockFace || interactingWith == null)
            return;
        interactingWith = null;
        this.updateFlags.add(UpdateFlag.INTERACT);
    }
References blockFace, com.runehive.game.world.entity.mob.UpdateFlag.INTERACT, and interactingWith.
Referenced by com.runehive.content.pet.Pets.abandon(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.hit(), move(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.start().
resetGraphic()
void com.runehive.game.world.entity.mob.Mob.resetGraphic ()
Definition at line 720 of file Mob.java.
{
        this.graphic = Optional.empty();
    }
Referenced by reset().
resetWaypoint()
final void com.runehive.game.world.entity.mob.Mob.resetWaypoint ()
Resets the waypoint.
Definition at line 249 of file Mob.java.
{
        if (cachedWaypoint != null && cachedWaypoint.isRunning()) {
            cachedWaypoint.cancel();
        }
    }
References cachedWaypoint.
Referenced by com.runehive.content.pet.Pets.abandon(), attack(), follow(), com.runehive.game.world.entity.mob.player.Player.pickup(), setWaypoint(), and walkTo().
runTo()
void com.runehive.game.world.entity.mob.Mob.runTo (Position destination)
Definition at line 370 of file Mob.java.
{
        movement.dijkstraPath(destination);
    }
References movement.
sequence()
abstract void com.runehive.game.world.entity.mob.Mob.sequence () abstract
The method which is invoked every tick.
Reimplemented in com.runehive.content.activity.infernomobs.JalTokJad.Guardian, com.runehive.content.bot.PlayerBot, com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian, com.runehive.game.world.entity.mob.npc.Npc, and com.runehive.game.world.entity.mob.player.Player.
setActivity()
void com.runehive.game.world.entity.mob.Mob.setActivity (Activity activity)
Definition at line 526 of file Mob.java.
{
        if (this.activity != null) {
            this.activity.cleanup();
        }
        this.activity = activity;
    }
References activity, and com.runehive.content.activity.Activity.cleanup().
Referenced by com.runehive.content.activity.Activity.add().
setBonus()
void com.runehive.game.world.entity.mob.Mob.setBonus (int equipSlot, int bonus)
Definition at line 694 of file Mob.java.
{
        if (bonuses == EMPTY_BONUSES)
            bonuses = new int[EMPTY_BONUSES.length];
        bonuses[equipSlot] = bonus;
    }
References bonuses.
setBonuses()
void com.runehive.game.world.entity.mob.Mob.setBonuses (int[] bonuses)
Definition at line 684 of file Mob.java.
{
        this.bonuses = bonuses;
    }
References bonuses.
Referenced by transform().
setDead()
void com.runehive.game.world.entity.mob.Mob.setDead (boolean dead)
Definition at line 644 of file Mob.java.
{
        this.dead = dead;
    }
References dead.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.preDeath().
setFixingInside()
void com.runehive.game.world.entity.mob.Mob.setFixingInside (boolean fixingInside)
Definition at line 755 of file Mob.java.
{
        this.fixingInside = fixingInside;
    }
References fixingInside.
Referenced by com.runehive.util.Utility.fixInsidePosition().
setForceMovement()
void com.runehive.game.world.entity.mob.Mob.setForceMovement (ForceMovement forceMovement)
Definition at line 512 of file Mob.java.
{
        this.forceMovement = forceMovement;
        if (forceMovement != null)
            this.updateFlags.add(UpdateFlag.FORCE_MOVEMENT);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.FORCE_MOVEMENT, and forceMovement.
setListIndex()
void com.runehive.game.world.entity.mob.Mob.setListIndex (int listIndex)
Definition at line 704 of file Mob.java.
{
        this.listIndex = listIndex;
    }
References listIndex.
setWaypoint()
void com.runehive.game.world.entity.mob.Mob.setWaypoint (Waypoint waypoint) protected
Definition at line 434 of file Mob.java.
{
        if (cachedWaypoint == null || (!cachedWaypoint.isRunning() || !waypoint.equals(cachedWaypoint))) {
            resetWaypoint();
            movement.reset();
            action.clearNonWalkableActions();
            World.schedule(cachedWaypoint = waypoint);
        }
    }
References action, cachedWaypoint, com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.equals(), movement, resetWaypoint(), and com.runehive.game.world.World.schedule().
Referenced by com.runehive.content.activity.infernomobs.JalTokJad.Guardian.Guardian(), and com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.Guardian().
speak()
void com.runehive.game.world.entity.mob.Mob.speak (String forceChat)
Sets the mob's forced chat.
Definition at line 127 of file Mob.java.
{
        if (forceChat == null || forceChat.isEmpty() || forceChat.length() > ChatMessage.CHARACTER_LIMIT)
            return;
        this.forceChat = forceChat;
        this.updateFlags.add(UpdateFlag.FORCED_CHAT);
    }
References com.runehive.game.world.entity.mob.player.relations.ChatMessage.CHARACTER_LIMIT, forceChat, and com.runehive.game.world.entity.mob.UpdateFlag.FORCED_CHAT.
Referenced by com.runehive.content.triviabot.TriviaBot.answer(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.block(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.gambling.GambleManager.finish(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.finishIncoming(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.finishOutgoing(), com.runehive.content.gambling.impl.FiftyFive.gamble(), com.runehive.content.gambling.impl.FlowerPoker.gamble(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn(), com.runehive.content.gambling.GambleManager.give(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.MagicAttack.hit(), com.runehive.content.bot.PlayerBot.loopCombat(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.preDeath(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.preDeath(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill(), com.runehive.content.gambling.GambleManager.send(), com.runehive.content.ai.LazyAIManager.showGptInstructionsWithGreeting(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.start(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.start(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.TeleGrab.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.TeleGrab.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), and com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse().
takeStep()
void com.runehive.game.world.entity.mob.Mob.takeStep ()
Definition at line 579 of file Mob.java.
{
        Position walkTo = getPosition();
        if (TraversalMap.isTraversable(getPosition(), Direction.WEST, width())) {
            walkTo = walkTo.west();
        } else if (TraversalMap.isTraversable(getPosition(), Direction.EAST, width())) {
            walkTo = walkTo.east();
        } else if (TraversalMap.isTraversable(getPosition(), Direction.SOUTH, width())) {
            walkTo = walkTo.north();
        } else if (TraversalMap.isTraversable(getPosition(), Direction.NORTH, width())) {
            walkTo = walkTo.south();
        }
        if (!getPosition().equals(walkTo)) {
            movement.walkTo(walkTo);
        }
    }
References com.runehive.game.world.entity.mob.Direction.EAST, com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.pathfinding.TraversalMap.isTraversable(), movement, com.runehive.game.world.entity.mob.Direction.NORTH, com.runehive.game.world.entity.mob.Direction.SOUTH, walkTo(), com.runehive.game.world.entity.mob.Direction.WEST, and com.runehive.game.world.entity.Entity.width.
Referenced by com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), and com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct().
transform() [1/2]
void com.runehive.game.world.entity.mob.Mob.transform (int transformId)
Definition at line 201 of file Mob.java.
{
        transform(transformId, false);
    }
References transform(), and transformId.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.block(), com.runehive.content.wintertodt.Wintertodt.healPyromancer(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.preDeath(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.content.activity.impl.kraken.KrakenActivity.transform(), and transform().
transform() [2/2]
void com.runehive.game.world.entity.mob.Mob.transform (int transformId, boolean reload)
Transforms the mob.
Definition at line 208 of file Mob.java.
{
        this.transformId = transformId;
        this.id = transformId;
        this.updateFlags.add(UpdateFlag.TRANSFORM);
        this.updateFlags.add(UpdateFlag.APPEARANCE);
        if (isNpc()) {
            NpcDefinition definition = NpcDefinition.get(id);
            final Npc npc = getNpc();
            npc.definition = definition;
            npc.pathfinderProjectiles = Mob.pathfinderProjectiles(npc);
            setWidth(definition.getSize());
            setLength(definition.getSize());
            setBonuses(definition.getBonuses());
            mobAnimation.setNpcAnimations(definition);
            if (reload) {
                Combat<Npc> combat = getNpc().getCombat();
                CombatListener<Npc> listener = CombatListenerManager.NPC_LISTENERS.get(getNpc().id);
                if (listener != null) {
                    combat.addListener(listener);
                }
                getNpc().npcAssistant.reloadSkills();
                getNpc().setStrategy(NpcUtility.STRATEGIES.getOrDefault(getNpc().id, () -> NpcAssistant.loadStrategy(getNpc()).orElse(NpcMeleeStrategy.get())).get());
            }
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.get(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getBonuses(), com.runehive.game.world.entity.mob.npc.Npc.getCombat(), getNpc(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getSize(), isNpc(), com.runehive.game.world.entity.mob.npc.NpcAssistant.loadStrategy(), Mob(), mobAnimation, com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.NPC_LISTENERS, com.runehive.game.world.entity.mob.npc.Npc.npcAssistant, com.runehive.game.world.entity.mob.npc.NpcAssistant.reloadSkills(), setBonuses(), com.runehive.game.world.entity.Entity.setLength(), com.runehive.game.world.entity.mob.npc.Npc.setStrategy(), com.runehive.game.world.entity.Entity.setWidth(), com.runehive.game.world.entity.mob.npc.NpcUtility.STRATEGIES, com.runehive.game.world.entity.mob.UpdateFlag.TRANSFORM, and transformId.
unpoison()
void com.runehive.game.world.entity.mob.Mob.unpoison ()
Definition at line 601 of file Mob.java.
{
        poisonDamage.set(0);
        poisonType = null;
        if (this instanceof Player) {
            Player player = (Player) this;
            player.send(new SendPoison(SendPoison.PoisonType.NO_POISON));
        }
    }
References com.runehive.net.packet.out.SendPoison.PoisonType.NO_POISON, poisonDamage, and poisonType.
Referenced by com.runehive.content.activity.Activity.add(), com.runehive.content.bot.PlayerBot.endFight(), and com.runehive.content.activity.Activity.onDeath().
unvenom()
void com.runehive.game.world.entity.mob.Mob.unvenom ()
Definition at line 611 of file Mob.java.
{
        venomDamage.set(0);
        if (this instanceof Player) {
            Player player = (Player) this;
            player.send(new SendPoison(SendPoison.PoisonType.NO_POISON));
        }
    }
References com.runehive.net.packet.out.SendPoison.PoisonType.NO_POISON, and venomDamage.
Referenced by com.runehive.content.activity.Activity.add(), com.runehive.content.bot.PlayerBot.endFight(), and com.runehive.content.activity.Activity.onDeath().
venom()
void com.runehive.game.world.entity.mob.Mob.venom ()
Applies venom to the entity.
Definition at line 508 of file Mob.java.
{
        CombatUtil.effect(this, CombatEffectType.VENOM);
    }
References com.runehive.game.world.entity.combat.CombatUtil.effect(), and com.runehive.game.world.entity.combat.effect.CombatEffectType.VENOM.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomDragonfireAttack.hit(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), and com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz().
walk() [1/2]
void com.runehive.game.world.entity.mob.Mob.walk (Position destination, boolean ignoreClip)
Definition at line 362 of file Mob.java.
{
        if (ignoreClip) {
            movement.walk(destination);
        } else {
            movement.simplePath(destination);
        }
    }
References movement.
walk() [2/2]
void com.runehive.game.world.entity.mob.Mob.walk (Position position)
Definition at line 358 of file Mob.java.
{
        walk(position, false);
    }
References com.runehive.game.world.entity.Entity.position, and walk().
Referenced by walk().
walkExactlyTo() [1/2]
void com.runehive.game.world.entity.mob.Mob.walkExactlyTo (Position position)
Definition at line 384 of file Mob.java.
{
        walkExactlyTo(position, () -> {
        });
    }
References com.runehive.game.world.entity.Entity.position, and walkExactlyTo().
Referenced by com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.content.activity.inferno.InfernoBoss.spawnbosswave(), and walkExactlyTo().
walkExactlyTo() [2/2]
void com.runehive.game.world.entity.mob.Mob.walkExactlyTo (Position position, Runnable onDestination)
Definition at line 389 of file Mob.java.
{
        Interactable interactable = Interactable.create(position, 0, 0);
        walkTo(interactable, onDestination);
    }
References com.runehive.game.world.Interactable.create(), com.runehive.game.world.entity.Entity.position, and walkTo().
walkTo() [1/4]
void com.runehive.game.world.entity.mob.Mob.walkTo (Interactable target, boolean clearAction, Runnable onDestination)
Definition at line 398 of file Mob.java.
{
        Waypoint waypoint = new WalkToWaypoint(this, target, onDestination);
        if (cachedWaypoint == null || (!cachedWaypoint.isRunning() || !waypoint.equals(cachedWaypoint))) {
            resetWaypoint();
            getCombat().reset();
            movement.reset();
            if (clearAction) {
                action.clearNonWalkableActions();
            }
            World.schedule(cachedWaypoint = waypoint);
        }
    }
References action, cachedWaypoint, com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.equals(), getCombat(), movement, resetWaypoint(), and com.runehive.game.world.World.schedule().
walkTo() [2/4]
void com.runehive.game.world.entity.mob.Mob.walkTo (Interactable target, Runnable onDestination)
Definition at line 394 of file Mob.java.
{
        walkTo(target, true, onDestination);
    }
References walkTo().
walkTo() [3/4]
void com.runehive.game.world.entity.mob.Mob.walkTo (Position position)
Definition at line 374 of file Mob.java.
{
        getCombat().reset();
        walkTo(position, () -> { /* Do nothing on arrival */ });
    }
References getCombat(), com.runehive.game.world.entity.Entity.position, and walkTo().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.content.skill.impl.mining.Mining.start(), takeStep(), walkExactlyTo(), walkTo(), walkTo(), and walkTo().
walkTo() [4/4]
void com.runehive.game.world.entity.mob.Mob.walkTo (Position position, Runnable onDestination)
Definition at line 379 of file Mob.java.
{
        Interactable interactable = Interactable.create(position);
        walkTo(interactable, onDestination);
    }
References com.runehive.game.world.Interactable.create(), com.runehive.game.world.entity.Entity.position, and walkTo().
writeDamage()
void com.runehive.game.world.entity.mob.Mob.writeDamage (Hit hit)
Definition at line 458 of file Mob.java.
{
        if (isDead() || getCurrentHealth() < 1) {
            return;
        }
        if (!damageImmunity.finished()) {
            return;
        }
        getCombat().onDamage(hit);
        if (!updateFlags.contains(UpdateFlag.FIRST_HIT)) {
            firstHit = decrementHealth(hit);
            updateFlags.add(UpdateFlag.FIRST_HIT);
        } else {
            secondHit = decrementHealth(hit);
            updateFlags.add(UpdateFlag.SECOND_HIT);
        }
    }
References damageImmunity, decrementHealth(), com.runehive.game.world.entity.mob.UpdateFlag.FIRST_HIT, firstHit, getCombat(), getCurrentHealth(), isDead(), com.runehive.game.world.entity.mob.UpdateFlag.SECOND_HIT, secondHit, and updateFlags.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.AcidTask(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.lavaTask(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special().
writeFakeDamage()
void com.runehive.game.world.entity.mob.Mob.writeFakeDamage (Hit hit)
Definition at line 448 of file Mob.java.
{
        if (!updateFlags.contains(UpdateFlag.FIRST_HIT)) {
            firstHit = hit;
            updateFlags.add(UpdateFlag.FIRST_HIT);
        } else {
            secondHit = hit;
            updateFlags.add(UpdateFlag.SECOND_HIT);
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.FIRST_HIT, firstHit, com.runehive.game.world.entity.mob.UpdateFlag.SECOND_HIT, secondHit, and updateFlags.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers().
Member Data Documentation
action
ActionManager com.runehive.game.world.entity.mob.Mob.action = new ActionManager()
Definition at line 100 of file Mob.java.
Referenced by com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride(), com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride(), attack(), com.runehive.content.wintertodt.Wintertodt.chopRoot(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.hunter.Hunter.clickObject(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.emote.Emote.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.wintertodt.Wintertodt.feedBrazier(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), com.runehive.content.wintertodt.Wintertodt.fletch(), follow(), com.runehive.game.world.entity.mob.player.Player.forClan(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.wintertodt.Wintertodt.mixHerb(), com.runehive.game.world.entity.mob.player.Player.pickup(), com.runehive.game.world.entity.mob.npc.Npc.sequence(), com.runehive.game.world.entity.mob.player.Player.sequence(), setWaypoint(), com.runehive.content.wintertodt.Wintertodt.shootFlame(), com.runehive.content.skill.impl.smithing.Smelting.smelt(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fishing.Fishing.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.skill.impl.mining.Mining.start(), com.runehive.content.wintertodt.Wintertodt.takeHerb(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), com.runehive.content.skill.impl.firemaking.Firemaking.useItem(), com.runehive.content.skill.impl.herblore.Herblore.useItem(), com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem(), and walkTo().
activity
Activity com.runehive.game.world.entity.mob.Mob.activity
Definition at line 88 of file Mob.java.
Referenced by com.runehive.game.world.entity.mob.npc.Npc.appendDeath(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.content.activity.Activity.evaluate(), com.runehive.content.activity.Activity.forActivity(), inActivity(), inActivity(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.content.activity.Activity.search(), and setActivity().
animation
Optional<Animation> com.runehive.game.world.entity.mob.Mob.animation = Optional.empty() private
Definition at line 89 of file Mob.java.
Referenced by animate(), animate(), animate(), animate(), forceMove(), forceMove(), forceMove(), forceMove(), and getAnimation().
attributes
final GenericAttributes com.runehive.game.world.entity.mob.Mob.attributes = new GenericAttributes()
Definition at line 95 of file Mob.java.
Referenced by com.runehive.content.Obelisks.activate(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.canAttack(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.canExecute(), com.runehive.content.skill.impl.construction.BuildableInterface.click(), com.runehive.content.teleport.TeleportHandler.click(), com.runehive.content.tittle.TitleManager.click(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.content.skill.impl.fletching.Fletching.clickButton(), com.runehive.content.store.impl.DefaultStore.close(), com.runehive.content.store.impl.PersonalStore.close(), com.runehive.content.store.impl.RecipeForDisasterStore.close(), com.runehive.content.store.impl.SkillcapeStore.close(), com.runehive.content.store.Store.closeShop(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.itemaction.impl.SerpentineHelm.dismantle(), com.runehive.content.skill.impl.construction.BuildableInterface.display(), com.runehive.content.teleport.TeleportHandler.display(), com.runehive.content.simulator.DropSimulator.drawList(), com.runehive.content.store.Store.exchange(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.teleport.TeleportHandler.favorite(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fifthAction(), com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.finishOutgoing(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.getAttackDelay(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.hitsplat(), com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.init(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.lavaTask(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.content.skill.impl.agility.obstacle.impl.RopeSwingInteraction.onExecution(), com.runehive.content.DropDisplay.open(), com.runehive.content.Obelisks.open(), com.runehive.content.skill.impl.construction.BuildableInterface.open(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.content.teleport.TeleportHandler.open(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask(), com.runehive.content.tittle.TitleManager.redeem(), com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), com.runehive.content.StarterKit.refresh(), com.runehive.content.tittle.TitleManager.refresh(), com.runehive.content.itemaction.impl.MagmaHelm.restore(), com.runehive.content.itemaction.impl.TanzaniteHelm.restore(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.content.DropDisplay.search(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), com.runehive.net.packet.in.ItemContainerActionPacketListener.sixthAction(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start(), com.runehive.content.teleport.TeleportHandler.teleport(), com.runehive.content.skill.impl.crafting.Crafting.useItem(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
blockFace
boolean com.runehive.game.world.entity.mob.Mob.blockFace
Definition at line 79 of file Mob.java.
Referenced by face(), face(), face(), and resetFace().
blockInteract
boolean com.runehive.game.world.entity.mob.Mob.blockInteract
Definition at line 80 of file Mob.java.
Referenced by interact().
bonuses
int [] com.runehive.game.world.entity.mob.Mob.bonuses = EMPTY_BONUSES private
Definition at line 103 of file Mob.java.
Referenced by appendBonus(), getBonus(), getBonuses(), setBonus(), and setBonuses().
cachedWaypoint
Waypoint com.runehive.game.world.entity.mob.Mob.cachedWaypoint protected
Definition at line 101 of file Mob.java.
Referenced by attack(), follow(), com.runehive.game.world.entity.mob.player.Player.pickup(), resetWaypoint(), setWaypoint(), and walkTo().
damageImmunity
Stopwatch com.runehive.game.world.entity.mob.Mob.damageImmunity = Stopwatch.start()
Definition at line 109 of file Mob.java.
Referenced by com.runehive.content.bot.PlayerBot.endFight(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.preKill(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), and writeDamage().
dead
boolean com.runehive.game.world.entity.mob.Mob.dead private
Definition at line 72 of file Mob.java.
Referenced by isDead(), and setDead().
facePosition
Position com.runehive.game.world.entity.mob.Mob.facePosition
Definition at line 87 of file Mob.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFaceCoordinateMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceCoordinteMask(), face(), face(), and face().
firstHit
Hit com.runehive.game.world.entity.mob.Mob.firstHit
Definition at line 83 of file Mob.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), writeDamage(), and writeFakeDamage().
fixingInside
boolean com.runehive.game.world.entity.mob.Mob.fixingInside private
Definition at line 749 of file Mob.java.
Referenced by isFixingInside(), and setFixingInside().
followers
List<Mob> com.runehive.game.world.entity.mob.Mob.followers = new LinkedList<>()
Definition at line 92 of file Mob.java.
Referenced by com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath().
forceChat
String com.runehive.game.world.entity.mob.Mob.forceChat
Definition at line 81 of file Mob.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendForceChatMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendForceChatMask(), and speak().
forceMovement
ForceMovement com.runehive.game.world.entity.mob.Mob.forceMovement
Definition at line 93 of file Mob.java.
Referenced by getForceMovement(), and setForceMovement().
forceWalking
boolean com.runehive.game.world.entity.mob.Mob.forceWalking
Definition at line 75 of file Mob.java.
freezeImmunity
final Stopwatch com.runehive.game.world.entity.mob.Mob.freezeImmunity = Stopwatch.start()
Definition at line 107 of file Mob.java.
Referenced by com.runehive.game.world.entity.combat.magic.MagicImpact.freeze().
graphic
Optional<Graphic> com.runehive.game.world.entity.mob.Mob.graphic = Optional.empty() private
Definition at line 91 of file Mob.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalDagger.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalTentacleWhip.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalWhip.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.attack(), com.runehive.game.world.entity.combat.attack.listener.item.ElysianListener.block(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.block(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.itemaction.impl.DragonfireShield.empty(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword.finishOutgoing(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), getGraphic(), graphic(), graphic(), graphic(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.game.world.entity.combat.attack.listener.item.AhrimListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.GuthansListner.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ToragListener.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Shockwave.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MagicAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.hit(), com.runehive.game.world.entity.combat.strategy.player.special.magic.EldritchNightmareStaff.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.magic.VolatileNightmareStaff.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalBludgen.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.range.Ballista.hitsplat(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsActivity.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.sendProjectile(), com.runehive.game.world.entity.combat.strategy.player.special.range.MagicShortbow.sendStuff(), com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.TeleGrab.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonLongsword.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonMace.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.OsmumFang.start().
id
int com.runehive.game.world.entity.mob.Mob.id = -1
Definition at line 70 of file Mob.java.
Referenced by com.runehive.content.activity.impl.kraken.KrakenActivity.add(), com.runehive.net.packet.out.SendNpcUpdate.addNewNpc(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.out.SendNpcUpdate.appendTransformationMask(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.attack(), com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.block(), com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.canAttack(), com.runehive.content.activity.impl.warriorguild.WarriorGuildActivityListener.canAttack(), com.runehive.content.activity.impl.zulrah.ZulrahListener.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.canAttack(), com.runehive.content.skill.impl.hunter.trap.TrapManager.catchNPC(), com.runehive.content.skill.impl.fishing.Fishing.clickNpc(), com.runehive.content.skill.impl.hunter.Hunter.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.pet.Pets.dialogue(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.finishIncoming(), com.runehive.content.activity.impl.barrows.BrotherData.getBarrowsBrother(), getId(), com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.content.ai.LazyAIManager.handleGandalfAIClick(), com.runehive.content.wintertodt.Wintertodt.healPyromancer(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.hit(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit(), com.runehive.content.ai.LazyAIManager.initializeOpenAIAndProcess(), com.runehive.content.activity.impl.barrows.BrotherData.isBarrowsBrother(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.combat.attack.listener.item.DragonHunterCrossbowListener.modifyRangedLevel(), com.runehive.game.world.entity.mob.npc.Npc.Npc(), com.runehive.game.world.entity.mob.npc.Npc.Npc(), com.runehive.game.world.entity.mob.npc.Npc.Npc(), com.runehive.game.world.entity.mob.npc.Npc.Npc(), com.runehive.game.action.impl.NpcFaceAction.NpcFaceAction(), com.runehive.content.activity.impl.kraken.KrakenActivity.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.pet.Pets.onDeath(), com.runehive.content.pet.Pets.onObtain(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), com.runehive.content.skill.impl.hunter.trap.TrapExecution.setTrapProcess(), com.runehive.content.ai.LazyAIManager.showGptInstructions(), com.runehive.content.ai.LazyAIManager.showGptInstructionsWithGreeting(), com.runehive.content.ai.LazyAIManager.showOpenAIConnectionOffer(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.content.ai.LazyAIManager.startInactivityTimer(), and com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.withinDistance().
inTeleport
boolean com.runehive.game.world.entity.mob.Mob.inTeleport
Definition at line 77 of file Mob.java.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplat(), and com.runehive.game.world.entity.combat.Combat< T extends Mob >.start().
interactingWith
Mob com.runehive.game.world.entity.mob.Mob.interactingWith
Definition at line 82 of file Mob.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFaceEntityMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceEntityMask(), and resetFace().
lastPosition
Position com.runehive.game.world.entity.mob.Mob.lastPosition
Definition at line 85 of file Mob.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendForceMovementMask(), com.runehive.net.packet.out.SendCoordinate.encode(), move(), and com.runehive.net.packet.out.SendPlayerUpdate.updateMovement().
listIndex
int com.runehive.game.world.entity.mob.Mob.listIndex private
Definition at line 69 of file Mob.java.
Referenced by getListIndex(), and setListIndex().
locking
final Locking com.runehive.game.world.entity.mob.Mob.locking = new Locking(this)
Definition at line 106 of file Mob.java.
Referenced by com.runehive.content.activity.impl.kraken.KrakenActivity.add(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.attack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.canAttack(), com.runehive.game.plugin.extension.CommandExtension.canExecute(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.content.emote.Emote.execute(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.game.world.entity.combat.magic.MagicImpact.freeze(), com.runehive.content.ai.AIDialogueHandler.handleAICommand(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.net.packet.in.ChatMessagePacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handlePacket(), com.runehive.net.packet.in.KeyPacketListener.handlePacket(), com.runehive.net.packet.in.PickupItemPacketListener.handlePacket(), com.runehive.net.packet.in.UseItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), move(), com.runehive.content.StarterKit.open(), com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.game.world.entity.mob.npc.Npc.sequence(), com.runehive.content.emote.Emote.skillcape(), com.runehive.content.activity.inferno.Inferno.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
mobAnimation
MobAnimation com.runehive.game.world.entity.mob.Mob.mobAnimation = new MobAnimation(updateFlags)
Definition at line 99 of file Mob.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.game.world.entity.mob.player.Player.login(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onExecution(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction.start(), com.runehive.content.skill.impl.agility.obstacle.impl.WalkInteraction.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), and transform().
movement
final Movement com.runehive.game.world.entity.mob.Mob.movement = new Movement(this)
Definition at line 98 of file Mob.java.
Referenced by com.runehive.content.pet.Pets.abandon(), com.runehive.net.packet.out.SendNpcUpdate.appendFaceCoordinateMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceCoordinteMask(), attack(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.execute(), com.runehive.util.Utility.fixInsidePosition(), follow(), forceMove(), com.runehive.game.world.entity.combat.magic.MagicImpact.freeze(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.WalkInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onExecution(), com.runehive.game.world.entity.mob.player.Player.pickup(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.content.bot.PlayerBot.postDeath(), com.runehive.content.StarterKit.refresh(), runTo(), setWaypoint(), com.runehive.content.wintertodt.Wintertodt.shootFlame(), takeStep(), com.runehive.net.packet.out.SendNpcUpdate.updateMovement(), com.runehive.net.packet.out.SendPlayerUpdate.updateMovement(), walk(), and walkTo().
nextAnimation
transient long com.runehive.game.world.entity.mob.Mob.nextAnimation
Definition at line 90 of file Mob.java.
Referenced by animate().
pathfinderProjectiles
boolean com.runehive.game.world.entity.mob.Mob.pathfinderProjectiles = false
Definition at line 68 of file Mob.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), and com.runehive.game.world.entity.mob.npc.NpcAssistant.login().
poisonDamage
final MutableNumber com.runehive.game.world.entity.mob.Mob.poisonDamage = new MutableNumber() private
Definition at line 104 of file Mob.java.
Referenced by getPoisonDamage(), isPoisoned(), and unpoison().
poisonType
PoisonType com.runehive.game.world.entity.mob.Mob.poisonType private
Definition at line 108 of file Mob.java.
Referenced by getPoisonType(), poison(), and unpoison().
positionChange
boolean com.runehive.game.world.entity.mob.Mob.positionChange
Definition at line 74 of file Mob.java.
Referenced by com.runehive.game.world.entity.mob.player.Player.login(), move(), and com.runehive.content.bot.PlayerBot.PlayerBot().
prayer
PrayerBook com.runehive.game.world.entity.mob.Mob.prayer = new PrayerBook()
Definition at line 102 of file Mob.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect.apply(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.attack(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getPrayerBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getPrayerBonus(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonusDefender(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerDefenseBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerDefenseBonus(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.handleCombat(), com.runehive.content.bot.botclass.impl.PureMelee.handleCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.handleCombat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.handleCombat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.handleCombat(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MeleeAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MagicAttack.hitsplat(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.hitsplat(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.PinkDragonfireAttack.hitsplat(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDamage(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.withinDistance().
regionChange
boolean com.runehive.game.world.entity.mob.Mob.regionChange
Definition at line 73 of file Mob.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.encode(), com.runehive.game.world.entity.mob.player.Player.login(), move(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick(), and com.runehive.net.packet.out.SendPlayerUpdate.updateMovement().
secondHit
Hit com.runehive.game.world.entity.mob.Mob.secondHit
Definition at line 84 of file Mob.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask(), writeDamage(), and writeFakeDamage().
skills
final SkillManager com.runehive.game.world.entity.mob.Mob.skills = new SkillManager(this)
Definition at line 96 of file Mob.java.
Referenced by com.runehive.content.consume.FoodData.anglerfishHeal(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.skill.impl.slayer.SlayerTask.asList(), com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword.attack(), com.runehive.content.skill.impl.mining.Mining.attempt(), com.runehive.content.wintertodt.Wintertodt.award(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.slayer.SlayerTask.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), com.runehive.util.parser.old.defs.EquipmentRequirement.canEquip(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.canExecute(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.canExecute(), com.runehive.content.skill.impl.fishing.Fishing.canFish(), com.runehive.content.skill.impl.thieving.WallSafe.chance(), com.runehive.util.Utility.checkRequirements(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.fishing.Fishing.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.game.world.entity.combat.CombatTarget.compare(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.shootingstar.ShootingStarData.decreaseDust(), decrementHealth(), com.runehive.content.emote.Skillcape.equip(), com.runehive.content.event.EventDispatcher.execute(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.game.action.impl.RevShortcutAction.execute(), com.runehive.content.skill.impl.thieving.PickpocketAction.failureRate(), com.runehive.content.skill.impl.thieving.Thieving.failureRate(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.wintertodt.Wintertodt.getAreaAttackDamage(), com.runehive.content.wintertodt.Wintertodt.getBrazierAttackDamage(), com.runehive.content.wintertodt.Wintertodt.getColdDamage(), getCurrentHealth(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getDefenceRoll(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getDefenceRoll(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getDefenceRoll(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getEffectiveLevel(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.getHits(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicLevel(), getMaximumHealth(), com.runehive.content.skill.impl.hunter.trap.TrapManager.getMaximumTraps(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getRangedlevel(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getRangeLevel(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getRangeLevel(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStrengthLevel(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.game.world.entity.combat.magic.MagicImpact.heal(), heal(), com.runehive.content.activity.infernomobs.MejRah.Ranged.hit(), com.runehive.game.world.entity.combat.attack.listener.item.AhrimListener.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.TzKihListener.hit(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.ScorpiaOffspring.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.hit(), com.runehive.content.skill.SkillRepository.isSuccess(), com.runehive.content.skill.SkillRepository.isSuccess(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.game.world.entity.combat.magic.MagicImpact.kbdShock(), com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), com.runehive.game.world.entity.mob.player.Player.login(), com.runehive.content.bot.PlayerBot.loopCombat(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.game.world.entity.combat.magic.MagicImpact.lowerSkill(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.game.world.entity.combat.attack.listener.item.TwistedBowListener.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAggressive(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressive(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAggressive(), com.runehive.game.world.entity.combat.attack.listener.item.TwistedBowListener.modifyDamage(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalBludgen.modifyDamage(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDefensive(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensive(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensive(), com.runehive.content.consume.PotionData.modifySkill(), com.runehive.content.skill.impl.runecrafting.Runecraft.multiplier(), com.runehive.content.consume.PotionData.onAgilityEffect(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.game.action.impl.ScatterAshAction.onExecute(), com.runehive.content.consume.PotionData.onFishingEffect(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.consume.PotionData.onPrayerEffect(), com.runehive.content.consume.PotionData.onRestoreEffect(), com.runehive.content.ProfileViewer.open(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.content.bot.PlayerBot.postDeath(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), com.runehive.content.shootingstar.ShootingStar.prospect(), com.runehive.content.store.impl.SkillcapeStore.purchase(), com.runehive.content.skill.impl.thieving.WallSafe.rate(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.lms.LMSGame.resetLevels(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.game.service.HighscoreService.saveHighscores(), com.runehive.game.world.entity.mob.player.Player.sendInitialPackets(), com.runehive.game.world.entity.mob.npc.Npc.sequence(), com.runehive.content.lms.LMSGame.setLevels(), com.runehive.content.skill.impl.smithing.Smelting.smelt(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fishing.Fishing.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.skill.impl.mining.Mining.start(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), com.runehive.content.ProfileViewer.string(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.skill.impl.cooking.Cooking.success(), com.runehive.content.skill.impl.fishing.Fishing.success(), com.runehive.content.skill.impl.mining.Mining.success(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.twistedBowBonus(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), and com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.wasSuccesful().
skills_copy
final SkillManager com.runehive.game.world.entity.mob.Mob.skills_copy = new SkillManager(this)
Definition at line 97 of file Mob.java.
Referenced by com.runehive.content.lms.lobby.LMSLobby.joinLobby(), and com.runehive.content.lms.LMSGame.resetLevels().
teleporting
boolean com.runehive.game.world.entity.mob.Mob.teleporting
Definition at line 76 of file Mob.java.
Referenced by com.runehive.game.world.entity.mob.Viewport.shouldRemove().
teleportRegion
boolean com.runehive.game.world.entity.mob.Mob.teleportRegion
Definition at line 78 of file Mob.java.
Referenced by move(), com.runehive.game.world.entity.mob.Viewport.shouldRemove(), and com.runehive.net.packet.out.SendPlayerUpdate.updateMovement().
teleportTarget
Position com.runehive.game.world.entity.mob.Mob.teleportTarget
Definition at line 86 of file Mob.java.
transformId
int com.runehive.game.world.entity.mob.Mob.transformId private
Definition at line 71 of file Mob.java.
Referenced by getTransformId(), transform(), and transform().
updateFlags
final EnumSet<UpdateFlag> com.runehive.game.world.entity.mob.Mob.updateFlags = EnumSet.noneOf(UpdateFlag.class)
Definition at line 94 of file Mob.java.
Referenced by com.runehive.game.world.entity.mob.Viewport.add(), animate(), com.runehive.game.world.entity.mob.player.Player.chat(), com.runehive.content.clanchannel.channel.ClanChannel.establish(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.net.packet.in.ColorPacketListener.handlePacket(), isUpdateRequired(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction.onExecution(), com.runehive.content.tittle.TitleManager.redeem(), com.runehive.content.StarterKit.refresh(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.content.tittle.TitleManager.reset(), com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer(), writeDamage(), and writeFakeDamage().
venomDamage
final MutableNumber com.runehive.game.world.entity.mob.Mob.venomDamage = new MutableNumber() private
Definition at line 105 of file Mob.java.
Referenced by getVenomDamage(), isVenomed(), and unvenom().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/Mob.java