RuneHive-Game: com.runehive.content.preset.PresetManager Class Reference
com.runehive.content.preset.PresetManager Class Reference
Handles managing the preset system.
Public Member Functions
void activate ()
Activates the preset.
void delete ()
Handles deleting the preset.
void name (String name)
Handles naming the preset.
void open ()
Opens the preset to the last viewed slot.
void open (int slot)
Opens the preset to a specific slot.
void openSettings ()
Handles opening the settings menu for the preset.
PresetManager (Player player)
Constructs a new PresetManager.
void refresh ()
Refreshes all the components on the interface.
void upload ()
Handles uploading the preset content.
Public Attributes
boolean autoDeposit
The automatically deposit items on activate flag.
boolean deathOpen
The preset opening on death flag.
Preset[] preset = new Preset[SIZE]
The presets.
Static Public Attributes
static final int SIZE = 10
The total preset size.
Private Member Functions
void equipment (Preset preset)
int getSlot ()
Gets the current slot of the preset.
int getTaken ()
Gets the taken preset amount.
boolean hasItemRequirements (Player player, int[] requirements)
void inventory (Preset preset)
boolean valid (boolean open)
Checks if the preset is valid.
Private Attributes
boolean permitted
If the player is allowed all presets.
final Player player
The player instance.
Detailed Description
Handles managing the preset system.
Author
Daniel
Definition at line 27 of file PresetManager.java.
Constructor & Destructor Documentation
PresetManager()
com.runehive.content.preset.PresetManager.PresetManager (Player player)
Constructs a new PresetManager.
Definition at line 48 of file PresetManager.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
activate()
void com.runehive.content.preset.PresetManager.activate ()
Activates the preset.
Definition at line 158 of file PresetManager.java.
{
        if (!valid(false))
            return;
        int slot = getSlot();
        if (preset[slot] == null) {
            player.send(new SendMessage("You have nothing assigned to this preset!"));
            return;
        }
        if (autoDeposit) {
            player.bank.depositeInventory(false);
            player.bank.depositeEquipment(false);
        }
        if (!player.inventory.isEmpty() || !player.equipment.isEmpty()) {
            player.send(new SendMessage("Please deposit all items from your inventory and equipment."));
            return;
        }
        player.updateFlags.add(UpdateFlag.APPEARANCE);
        equipment(preset[slot]);
        inventory(preset[slot]);
        Autocast.reset(player);
        player.prayer.reset();
        player.equipment.login();
        player.inventory.refresh();
        player.quickPrayers.only(preset[slot].getPrayer().getEnabled().toArray(new Prayer[0]));
        player.spellbook = preset[slot].getSpellbook();
        player.interfaceManager.setSidebar(Config.MAGIC_TAB,  player.spellbook.getInterfaceId());
        player.send(new SendMessage("<col=ff0000>" + preset[slot].getName() + "</col> has been activated."));
        if (player.pvpInstance) {
            player.playerAssistant.setValueIcon();
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, autoDeposit, equipment(), getSlot(), inventory(), com.runehive.Config.MAGIC_TAB, player, preset, com.runehive.game.world.entity.combat.magic.Autocast.reset(), and valid().
delete()
void com.runehive.content.preset.PresetManager.delete ()
Handles deleting the preset.
Definition at line 278 of file PresetManager.java.
{
        if (!valid(false))
            return;
        int slot = getSlot();
        if (preset[slot] == null)
            return;
        player.dialogueFactory.sendOption("Delete " + preset[slot].getName() + " (<col=f44259>CANT BE UNDONE</col>)", () -> {
            preset[slot] = null;
            refresh();
            player.send(new SendMessage("You have successfully cleared preset #" + (slot + 1) + "."));
            player.dialogueFactory.clear();
        }, "Nevermind", () -> player.dialogueFactory.clear()).execute();
    }
References getSlot(), player, preset, refresh(), and valid().
equipment()
void com.runehive.content.preset.PresetManager.equipment (Preset preset) private
Definition at line 198 of file PresetManager.java.
{
        List<String> requirements = new ArrayList<>();
        for (Item item : preset.getEquipment()) {
            if (item == null)
                continue;
            if (!hasItemRequirements(player, item.getRequirements())) {
                requirements.add(item.getName());
                continue;
            }
            int tabSlot = player.bank.computeIndexForId(item.getId());
            if (tabSlot <= -1)
                continue;
            int tab = player.bank.tabForSlot(tabSlot);
            if (tab <= -1)
                continue;
            int amount = player.bank.get(tabSlot).getAmount();
            if (amount <= 0)
                continue;
            if (item.getAmount() > amount) {
                item = item.copy();
                item.setAmount(amount);
            }
            if (player.bank.remove(item.unnoted(), tabSlot, false)) {
                if (!player.bank.indexOccupied(tabSlot)) {
                    player.bank.changeTabAmount(tab, -1);
                    player.bank.shift();
                }
                player.equipment.manualWear(item.copy());
            }
        }
        if (!requirements.isEmpty()) {
            player.send(new SendMessage("<col=ff0000>Some items could not be equipped due to not having the skill requirements."));
        }
    }
References hasItemRequirements(), player, and preset.
Referenced by activate().
getSlot()
int com.runehive.content.preset.PresetManager.getSlot () private
Gets the current slot of the preset.
Definition at line 334 of file PresetManager.java.
{
        return player.attributes.get("PRELOADING_SLOT_KEY", Integer.class);
    }
References player.
Referenced by activate(), delete(), name(), open(), refresh(), and upload().
getTaken()
int com.runehive.content.preset.PresetManager.getTaken () private
Gets the taken preset amount.
Definition at line 323 of file PresetManager.java.
{
        int taken = SIZE;
        for (int i = 0; i < SIZE; i++) {
            if (preset[i] != null || i >= PlayerRight.getPresetAmount(player)) {
                taken--;
            }
        }
        return taken;
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.getPresetAmount(), player, preset, and SIZE.
Referenced by refresh().
hasItemRequirements()
boolean com.runehive.content.preset.PresetManager.hasItemRequirements (Player player, int[] requirements) private
Definition at line 338 of file PresetManager.java.
{
        for (int i = 0; i < requirements.length; i++) {
            int level = player.skills.getMaxLevel(i);
            int required = requirements[i];
            if (level < required) {
                return false;
            }
        }
        return true;
    }
References player.
Referenced by equipment().
inventory()
void com.runehive.content.preset.PresetManager.inventory (Preset preset) private
Definition at line 241 of file PresetManager.java.
{
        Item[] inventory = preset.getInventory();
        for (int index = 0; index < inventory.length; index++) {
            Item item = inventory[index];
            if (item == null)
                continue;
            int tabSlot = player.bank.computeIndexForId(item.getId());
            if (tabSlot <= -1)
                continue;
            int tab = player.bank.tabForSlot(tabSlot);
            if (tab <= -1)
                continue;
            int amount = player.bank.get(tabSlot).getAmount();
            if (amount <= 0)
                continue;
            if (item.getAmount() > amount) {
                item = item.copy();
                item.setAmount(amount);
            }
            if (player.bank.remove(item.unnoted(), tabSlot, false)) {
                if (!player.bank.indexOccupied(tabSlot)) {
                    player.bank.changeTabAmount(tab, -1);
                    player.bank.shift();
                }
                player.inventory.set(index, item.copy(), false);
            }
        }
    }
References com.runehive.game.world.items.Item.copy(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), inventory(), player, preset, com.runehive.game.world.items.Item.setAmount(), and com.runehive.game.world.items.Item.unnoted().
Referenced by activate(), and inventory().
name()
void com.runehive.content.preset.PresetManager.name (String name)
Handles naming the preset.
Definition at line 110 of file PresetManager.java.
{
        int slot = getSlot();
        if (!permitted && slot >= 5) {
            player.dialogueFactory.sendStatement("You need to be a donator for more preset slots!").execute();
            return;
        }
        if (preset[slot] == null) {
            preset[slot] = new Preset(name);
        } else {
            preset[slot].setName(name);
        }
        refresh();
        player.send(new SendMessage("You have successfully titles preset #" + (slot + 1) + " to " + name + "."));
    }
References getSlot(), name(), permitted, player, preset, and refresh().
Referenced by name(), and refresh().
open() [1/2]
void com.runehive.content.preset.PresetManager.open ()
Opens the preset to the last viewed slot.
Definition at line 53 of file PresetManager.java.
                       {
        open(getSlot());
    }
References getSlot(), and open().
Referenced by open(), and valid().
open() [2/2]
void com.runehive.content.preset.PresetManager.open (int slot)
Opens the preset to a specific slot.
Definition at line 58 of file PresetManager.java.
{
        if (valid(true)) {
            permitted = slot <= PlayerRight.getPresetAmount(player);
            if (!permitted) {
                player.dialogueFactory.sendStatement("You need to be a donator for more preset slots!").execute();
                return;
            }
            player.attributes.set("PRELOADING_SLOT_KEY", slot);
            refresh();
            player.interfaceManager.open(57_000);
        }
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.getPresetAmount(), permitted, player, refresh(), and valid().
openSettings()
void com.runehive.content.preset.PresetManager.openSettings ()
Handles opening the settings menu for the preset.
Definition at line 293 of file PresetManager.java.
{
        DialogueFactory factory = player.dialogueFactory;
        factory.sendOption("View current settings", () -> {
            factory.onAction(() -> {
                factory.sendInformationBox("<col=3E74B8>Preset Settings", "</col>Open on death: " + (deathOpen ? "<col=0E8716>Enabled" : "<col=F01818>Disabled"), "</col>Automatic deposit: " + (autoDeposit ? "<col=0E8716>Enabled" : "<col=F01818>Disabled")).execute();
            });
        }, "Toggle open on death", () -> factory.onAction(() -> {
            deathOpen = !deathOpen;
            factory.sendStatement("The preset interface will now " + (deathOpen ? "" : "<col=F01818>not</col> ") + "open on death", "automatically.").execute();
        }), "Toggle automatic deposit", () -> {
            factory.onAction(() -> {
                autoDeposit = !autoDeposit;
                factory.sendStatement("Your items will now " + (autoDeposit ? "" : "<col=F01818>not</col> ") + "automatically deposit on activation.").execute();
            });
        }, "Nevermind", () -> factory.onAction(factory::clear)).execute();
    }
References autoDeposit, deathOpen, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.dialogue.DialogueFactory.onAction(), player, com.runehive.content.dialogue.DialogueFactory.sendInformationBox(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
refresh()
void com.runehive.content.preset.PresetManager.refresh ()
Refreshes all the components on the interface.
Definition at line 74 of file PresetManager.java.
{
        int slot = getSlot();
        int slotId = 57049;
        for (int i = 0; i < SIZE; i++) {
            boolean locked = i >= PlayerRight.getPresetAmount(player);
            String defaultName = locked ? "<col=F23030>Locked" : (preset[i] == null ? "---" : preset[i].getName());
            String name = (i == slot ? "<col=ffffff>" : "<col=39BF5B>") + defaultName;
            player.send(new SendString(name, slotId));
            slotId += 4;
        }
        int attack = preset[slot] == null ? 1 : player.skills.get(Skill.ATTACK).getMaxLevel();
        int strength = preset[slot] == null ? 1 : player.skills.get(Skill.STRENGTH).getMaxLevel();
        int defence = preset[slot] == null ? 1 : player.skills.get(Skill.DEFENCE).getMaxLevel();
        int hitpoints = preset[slot] == null ? 10 : player.skills.get(Skill.HITPOINTS).getMaxLevel();
        int prayer = preset[slot] == null ? 1 : player.skills.get(Skill.PRAYER).getMaxLevel();
        int ranged = preset[slot] == null ? 1 : player.skills.get(Skill.RANGED).getMaxLevel();
        int magic = preset[slot] == null ? 1 : player.skills.get(Skill.MAGIC).getMaxLevel();
        player.send(new SendString(attack, 57014));
        player.send(new SendString(strength, 57015));
        player.send(new SendString(defence, 57016));
        player.send(new SendString(hitpoints, 57017));
        player.send(new SendString(prayer, 57018));
        player.send(new SendString(ranged, 57019));
        player.send(new SendString(magic, 57020));
        player.send(new SendString("Cmb Lvl: " + player.skills.getCombatLevel(), 57041));
        boolean prayers = preset[slot] == null || preset[slot].getPrayer() == null;
        player.send(new SendString("<col=99E823>" + (prayers ? "Not " : "") + "Set!", 57013));
        player.send(new SendString("<col=BD23E8>" + (preset[slot] == null ? "Not Set!" : preset[slot].getSpellbook().getName()), 57011));
        player.send(new SendString("Available " + getTaken() + "/" + PlayerRight.getPresetAmount(player), 57024));
        player.send(new SendItemOnInterface(57023, preset[slot] == null ? new Item[0] : preset[slot].getInventory()));
        player.send(new SendItemOnInterface(57022, preset[slot] == null ? new Item[0] : preset[slot].getEquipment()));
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.player.PlayerRight.getPresetAmount(), getSlot(), getTaken(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.game.world.entity.skill.Skill.MAGIC, name(), player, com.runehive.game.world.entity.skill.Skill.PRAYER, preset, com.runehive.game.world.entity.skill.Skill.RANGED, SIZE, and com.runehive.game.world.entity.skill.Skill.STRENGTH.
Referenced by delete(), name(), open(), and upload().
upload()
void com.runehive.content.preset.PresetManager.upload ()
Handles uploading the preset content.
Definition at line 128 of file PresetManager.java.
{
        if (!valid(false))
            return;
        int slot = getSlot();
        if (!permitted && slot >= 5) {
            player.dialogueFactory.sendStatement("You need to be a donator for more preset slots!").execute();
            return;
        }
        if (preset[slot] == null) {
            player.dialogueFactory.sendStatement("Please name your preset before uploading your gear!").execute();
            return;
        }
        player.dialogueFactory.sendOption("Upload preset", () -> {
            PrayerBook prayerBook = new PrayerBook();
            if (player.quickPrayers != null) {
                prayerBook.only(player.quickPrayers.getEnabled().toArray(new Prayer[0]));
            }
            preset[slot] = new Preset(preset[slot].getName(), player.inventory.toArray(), player.equipment.getEquipment(), prayerBook, player.spellbook);
            player.send(new SendMessage("You have successfully uploaded your preset."));
            refresh();
            AchievementHandler.activate(player, AchievementKey.PRELOAD_SETUP, 1);
            player.dialogueFactory.clear();
        }, "Nevermind", () -> player.dialogueFactory.clear()).execute();
    }
References com.runehive.content.achievement.AchievementHandler.activate(), getSlot(), com.runehive.game.world.entity.mob.prayer.PrayerBook.only(), permitted, player, com.runehive.content.achievement.AchievementKey.PRELOAD_SETUP, preset, refresh(), and valid().
valid()
boolean com.runehive.content.preset.PresetManager.valid (boolean open) private
Checks if the preset is valid.
Definition at line 311 of file PresetManager.java.
{
        if (!open && !player.interfaceManager.isInterfaceOpen(57_000))
            return false;
        if (player.getCombat().inCombat()) {
            player.send(new SendMessage("You can not do this while in combat!"));
            return false;
        }
        return !player.positionChange;
    }
References open(), and player.
Referenced by activate(), delete(), open(), and upload().
Member Data Documentation
autoDeposit
boolean com.runehive.content.preset.PresetManager.autoDeposit
The automatically deposit items on activate flag.
Definition at line 42 of file PresetManager.java.
Referenced by activate(), and openSettings().
deathOpen
boolean com.runehive.content.preset.PresetManager.deathOpen
The preset opening on death flag.
Definition at line 39 of file PresetManager.java.
Referenced by openSettings().
permitted
boolean com.runehive.content.preset.PresetManager.permitted private
If the player is allowed all presets.
Definition at line 45 of file PresetManager.java.
Referenced by name(), open(), and upload().
player
final Player com.runehive.content.preset.PresetManager.player private
The player instance.
Definition at line 33 of file PresetManager.java.
Referenced by activate(), delete(), equipment(), getSlot(), getTaken(), hasItemRequirements(), inventory(), name(), open(), openSettings(), PresetManager(), refresh(), upload(), and valid().
preset
Preset [] com.runehive.content.preset.PresetManager.preset = new Preset[SIZE]
The presets.
Definition at line 36 of file PresetManager.java.
Referenced by activate(), delete(), equipment(), getTaken(), inventory(), name(), refresh(), and upload().
SIZE
final int com.runehive.content.preset.PresetManager.SIZE = 10 static
The total preset size.
Definition at line 30 of file PresetManager.java.
Referenced by getTaken(), and refresh().
The documentation for this class was generated from the following file:
java/com/runehive/content/preset/PresetManager.java