RuneHive-Game: com.runehive.game.world.entity.combat.formula.MagicFormula Class Reference
com.runehive.game.world.entity.combat.formula.MagicFormula Class Reference
Public Member Functions
int modifyAccuracy (Mob attacker, Mob defender, int roll)
int modifyAggressive (Mob attacker, Mob defender, int roll)
int modifyAggressiveBonus (Mob attacker, Mob defender, int bonus)
int modifyDamage (Mob attacker, Mob defender, int damage)
int modifyDefensive (Mob attacker, Mob defender, int roll)
int modifyDefensiveBonus (Mob attacker, Mob defender, int bonus)
int modifyOffensiveBonus (Mob attacker, Mob defender, int bonus)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Detailed Description
Definition at line 10 of file MagicFormula.java.
Member Function Documentation
modifyAccuracy()
int com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAccuracy (Mob attacker, Mob defender, int roll)
Definition at line 13 of file MagicFormula.java.
{
        int level = attacker.skills.getLevel(Skill.MAGIC);
        return 8 + attacker.getCombat().modifyMagicLevel(defender, level);
    }
References com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.MAGIC, and com.runehive.game.world.entity.mob.Mob.skills.
modifyAggressive()
int com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAggressive (Mob attacker, Mob defender, int roll)
Definition at line 19 of file MagicFormula.java.
{
        int level = attacker.skills.getLevel(Skill.MAGIC);
        return 8 + attacker.getCombat().modifyMagicLevel(defender, level);
    }
References com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.MAGIC, and com.runehive.game.world.entity.mob.Mob.skills.
modifyAggressiveBonus()
int com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAggressiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 75 of file MagicFormula.java.
{
        return attacker.getCombat().modifyAggresiveBonus(defender, bonus);
    }
References com.runehive.game.world.entity.mob.Mob.getCombat().
modifyDamage()
int com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage (Mob attacker, Mob defender, int damage)
Definition at line 47 of file MagicFormula.java.
{
        int bonus = attacker.getBonus(Equipment.MAGIC_STRENGTH);
        if (attacker.isPlayer()) {
            if (attacker.getPlayer().isSingleCast()) {
                damage = attacker.getPlayer().singleCast.getCombatProjectile().getMaxHit();
            } else if (attacker.getPlayer().isAutocast()) {
                damage = attacker.getPlayer().autocast.getCombatProjectile().getMaxHit();
            }
        }
        damage += damage * bonus / 100;
        damage = attacker.getCombat().modifyDamage(defender, damage);
        if (defender.prayer.isActive(Prayer.PROTECT_FROM_MAGIC)) {
            damage *= !attacker.isPlayer() || defender.isNpc() ? 0.0 : 0.6;
        }
        return damage;
    }
References com.runehive.game.world.entity.mob.player.Player.autocast, com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.combat.magic.CombatSpell.getCombatProjectile(), com.runehive.game.world.entity.combat.projectile.CombatProjectile.getMaxHit(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.player.Player.isAutocast(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.player.Player.isSingleCast(), com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_STRENGTH, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MAGIC, and com.runehive.game.world.entity.mob.player.Player.singleCast.
modifyDefensive()
int com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDefensive (Mob attacker, Mob defender, int roll)
Definition at line 25 of file MagicFormula.java.
{
        //FightType fightType = defender.getCombat().getFightType();
        int magic = defender.skills.getLevel(Skill.MAGIC);
        magic = defender.getCombat().modifyMagicLevel(defender, magic);
        int defence = defender.skills.getLevel(Skill.DEFENCE);
        defence = defender.getCombat().modifyDefenceLevel(attacker, defence);
        double eD;
        if (attacker instanceof Player) {
            eD = magic * 0.7 + defence * 0.3;
        } else {
            eD = magic + 9;
        }
        /*int effectiveLevel = 8 + fightType.getStyle().getDefensiveIncrease();
        effectiveLevel += 0.70 * magic + 0.30 * defence;*/
        return (int) eD;
    }
References com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.MAGIC, and com.runehive.game.world.entity.mob.Mob.skills.
modifyDefensiveBonus()
int com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDefensiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 80 of file MagicFormula.java.
{
        bonus = defender.getBonus(Equipment.MAGIC_DEFENSE);
        return defender.getCombat().modifyDefensiveBonus(attacker, bonus);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getCombat(), and com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_DEFENSE.
modifyOffensiveBonus()
int com.runehive.game.world.entity.combat.formula.MagicFormula.modifyOffensiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 69 of file MagicFormula.java.
{
        bonus = attacker.getBonus(Equipment.MAGIC_OFFENSE);
        return attacker.getCombat().modifyOffensiveBonus(defender, bonus);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getCombat(), and com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_OFFENSE.
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/formula/MagicFormula.java