RuneHive-Game: com.runehive.util.parser.GsonParser Class Reference
com.runehive.util.parser.GsonParser Class Reference abstract
This class provides an easy to use google gson parser specifically designed for parsing JSON files.
Public Member Functions
final void deserialize ()
The method that deserializes the file information.
GsonParser (String path)
Creates a new GsonParser.
GsonParser (String path, boolean log)
Creates a new GsonParser.
void initialize (int size)
Public Member Functions inherited from com.runehive.util.parser.GenericParser
GenericParser (String path, String extension, boolean log)
Creates a new GenericParser.
final int getIndex ()
Gets the current index of the line being parsed.
void onRead ()
The method called after all the data has been parsed.
void run ()
String toString ()
Protected Member Functions
void onEnd ()
This method handles what happens after the parser has ended.
abstract void parse (JsonObject data)
The method allows a user to modify the data as its being parsed.
Protected Attributes
transient Gson builder
The Gson object.
Protected Attributes inherited from com.runehive.util.parser.GenericParser
int index
The index of the current line being parsed.
final Path path
The path of the file to parse.
Static Private Attributes
static final Logger logger = LogManager.getLogger(GsonParser.class)
Detailed Description
This class provides an easy to use google gson parser specifically designed for parsing JSON files.
Author
Seven
Daniel
Definition at line 16 of file GsonParser.java.
Constructor & Destructor Documentation
GsonParser() [1/2]
com.runehive.util.parser.GsonParser.GsonParser (String path)
Creates a new GsonParser.
Parameters
path The specified path of the json file to parse.
Definition at line 28 of file GsonParser.java.
{
        this(path, true);
    }
References com.runehive.util.parser.GenericParser.path.
GsonParser() [2/2]
com.runehive.util.parser.GsonParser.GsonParser (String path, boolean log)
Creates a new GsonParser.
Parameters
path The specified path of the json file to parse.
log The flag that denotes to log messages.
Definition at line 38 of file GsonParser.java.
{
        super(path, ".json", log);
        this.builder = new GsonBuilder().create();
    }
References com.runehive.util.parser.GenericParser.log, and com.runehive.util.parser.GenericParser.path.
Member Function Documentation
deserialize()
final void com.runehive.util.parser.GsonParser.deserialize ()
The method that deserializes the file information.
Reimplemented from com.runehive.util.parser.GenericParser.
Definition at line 60 of file GsonParser.java.
{
        try (final JsonReader reader = new JsonReader(new FileReader(path.toFile()))) {
            final JsonParser parser = new JsonParser();
            final JsonElement element = parser.parse(reader);
            if (element.isJsonNull()) {
                logger.warn(String.format("json document=%s is null", path));
                return;
            }
            if (element.isJsonArray()) {
                final JsonArray array = element.getAsJsonArray();
                initialize(array.size());
                for (index = 0; index < array.size(); index++) {
                    final JsonElement element2 = array.get(index);
                    if (element2 == null) continue;
                    if (element2 instanceof JsonNull) continue;
                    final JsonObject data = (JsonObject) element2;
                    parse(data);
                }
            } else if (element.isJsonObject()) {
                parse(element.getAsJsonObject());
            }
            onEnd();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
References com.runehive.util.parser.GenericParser.index, initialize(), logger, onEnd(), parse(), and com.runehive.util.parser.GenericParser.path.
Referenced by com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.main().
initialize()
void com.runehive.util.parser.GsonParser.initialize (int size)
Reimplemented in com.runehive.util.parser.old.EquipmentDefinitionParser.
Definition at line 43 of file GsonParser.java.
{
    }
Referenced by deserialize().
onEnd()
void com.runehive.util.parser.GsonParser.onEnd () protected
This method handles what happens after the parser has ended.
Reimplemented in com.runehive.util.parser.old.EquipmentDefinitionParser.
Definition at line 56 of file GsonParser.java.
{
    }
Referenced by deserialize().
parse()
abstract void com.runehive.util.parser.GsonParser.parse (JsonObject data) abstract protected
The method allows a user to modify the data as its being parsed.
Parameters
data The JsonObject that contains all serialized information.
Reimplemented in com.runehive.util.parser.impl.CombatProjectileParser, com.runehive.util.parser.impl.GlobalObjectParser, com.runehive.util.parser.impl.NpcDropParser, com.runehive.util.parser.impl.NpcForceChatParser, com.runehive.util.parser.impl.NpcSpawnParser, com.runehive.util.parser.impl.ObjectRemovalParser, com.runehive.util.parser.impl.PacketSizeParser, com.runehive.util.parser.impl.StoreParser, com.runehive.util.parser.old.EquipmentDefinitionParser, com.runehive.util.parser.old.EquipmentParser, com.runehive.util.parser.old.ItemDefinitionParser, and com.runehive.util.parser.old.WeaponDefinitionParser.
Referenced by deserialize().
Member Data Documentation
builder
transient Gson com.runehive.util.parser.GsonParser.builder protected
The Gson object.
Definition at line 21 of file GsonParser.java.
Referenced by com.runehive.util.parser.impl.CombatProjectileParser.parse(), com.runehive.util.parser.impl.GlobalObjectParser.parse(), com.runehive.util.parser.impl.NpcDropParser.parse(), com.runehive.util.parser.impl.NpcForceChatParser.parse(), com.runehive.util.parser.impl.NpcSpawnParser.parse(), com.runehive.util.parser.impl.ObjectRemovalParser.parse(), com.runehive.util.parser.impl.StoreParser.parse(), com.runehive.util.parser.old.EquipmentParser.parse(), and com.runehive.util.parser.old.WeaponDefinitionParser.parse().
logger
final Logger com.runehive.util.parser.GsonParser.logger = LogManager.getLogger(GsonParser.class) static private
Definition at line 18 of file GsonParser.java.
Referenced by deserialize().
The documentation for this class was generated from the following file:
java/com/runehive/util/parser/GsonParser.java