RuneHive-Game: com.runehive.fs.cache.decoder.MapDefinitionDecoder Class Reference
com.runehive.fs.cache.decoder.MapDefinitionDecoder Class Reference
A class which parses RegionDefinitions.
Public Member Functions
MapDefinitionDecoder (FileSystem fs)
Creates the MapDefinitionDecoder.
void run ()
Private Attributes
final FileSystem fs
The IndexedFileSystem.
Static Private Attributes
static final Logger LOGGER = LogManager.getLogger(MapDefinitionDecoder.class)
The logger that will print important information.
Detailed Description
A class which parses RegionDefinitions.
Author
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Definition at line 17 of file MapDefinitionDecoder.java.
Constructor & Destructor Documentation
MapDefinitionDecoder()
com.runehive.fs.cache.decoder.MapDefinitionDecoder.MapDefinitionDecoder (FileSystem fs)
Creates the MapDefinitionDecoder.
Parameters
fs The FileSystem.
Definition at line 30 of file MapDefinitionDecoder.java.
{
        this.fs = fs;
    }
References fs.
Member Function Documentation
run()
void com.runehive.fs.cache.decoder.MapDefinitionDecoder.run ()
Definition at line 35 of file MapDefinitionDecoder.java.
                      {
        LOGGER.info("Loading region definitions.");
        Archive archive = fs.getArchive(FileSystem.MANIFEST_ARCHIVE);
        ByteBuffer buffer = archive.getData("map_index");
        int count = (buffer.getShort() & 0xFFFF);
        for (int i = 0; i < count; i++) {
            int hash = buffer.getShort() & 0xFFFF;
            int terrainFile = buffer.getShort() & 0xFFFF;
            int objectFile = buffer.getShort() & 0xFFFF;
            RegionDefinition.set(new RegionDefinition(hash, terrainFile, objectFile));
        }
        LOGGER.info("Loaded " + count + " region definitions.");
    }
References fs, LOGGER, com.runehive.fs.cache.FileSystem.MANIFEST_ARCHIVE, and com.runehive.game.world.region.RegionDefinition.set().
Referenced by com.runehive.RuneHive.processSequentialStartupTasks().
Member Data Documentation
fs
final FileSystem com.runehive.fs.cache.decoder.MapDefinitionDecoder.fs private
The IndexedFileSystem.
Definition at line 23 of file MapDefinitionDecoder.java.
Referenced by MapDefinitionDecoder(), and run().
LOGGER
final Logger com.runehive.fs.cache.decoder.MapDefinitionDecoder.LOGGER = LogManager.getLogger(MapDefinitionDecoder.class) static private
The logger that will print important information.
Definition at line 20 of file MapDefinitionDecoder.java.
Referenced by run().
The documentation for this class was generated from the following file:
java/com/runehive/fs/cache/decoder/MapDefinitionDecoder.java