RuneHive-Game: com.runehive.content.skill.impl.thieving.PickpocketAction Class Reference
com.runehive.content.skill.impl.thieving.PickpocketAction Class Reference
Handles the pickpocketing action.
Public Member Functions
void execute ()
A function representing the unit of work that will be carried out.
String getName ()
Gets the name of this action.
WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
PickpocketAction (Player player, Npc npc, PickpocketData pickpocket)
Constructs a new PickpocketData.
boolean prioritized ()
Determines if this action is prioritized.
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Private Member Functions
int failureRate (Player player)
The failure rate for pickpocketing.
Private Attributes
final Npc npc
The npc being pickpocketed.
final PickpocketData pickpocket
The pickpocket data.
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
Handles the pickpocketing action.
Author
Daniel
Definition at line 21 of file PickpocketAction.java.
Constructor & Destructor Documentation
PickpocketAction()
com.runehive.content.skill.impl.thieving.PickpocketAction.PickpocketAction (Player player, Npc npc, PickpocketData pickpocket)
Constructs a new PickpocketData.
Definition at line 29 of file PickpocketAction.java.
{
        super(player, 3);
        this.npc = npc;
        this.pickpocket = pickpocket;
    }
References npc, and pickpocket.
Member Function Documentation
execute()
void com.runehive.content.skill.impl.thieving.PickpocketAction.execute ()
A function representing the unit of work that will be carried out.
Reimplemented from com.runehive.game.task.Task.
Definition at line 43 of file PickpocketAction.java.
{
        boolean failed = Utility.random(100) < failureRate(getMob());
        if (failed) {
            npc.interact(getMob());
            npc.face(npc.faceDirection);
            npc.animate(new Animation(422));
            npc.speak("What do you think you're doing?");
            getMob().action.clearNonWalkableActions();
            getMob().damage(new Hit(Utility.random(pickpocket.getDamage())));
            getMob().locking.lock(pickpocket.getStun(), LockType.STUN);
            getMob().send(new SendMessage("You failed to pickpocketing the " + npc.getName() + "."));
            cancel();
            return;
        }
        double experience = Area.inSuperDonatorZone(getMob()) || Area.inRegularDonatorZone(getMob()) ? pickpocket.getExperience() * 2 : pickpocket.getExperience();
        getMob().skills.addExperience(Skill.THIEVING, experience * Config.THIEVING_MODIFICATION);
        getMob().send(new SendMessage("You have successfully pickpocket the " + npc.getName() + "."));
        getMob().inventory.add(Utility.randomElement(pickpocket.getLoot()));
        getMob().locking.unlock();
        cancel();
    }
References com.runehive.game.task.Task.cancel(), failureRate(), com.runehive.game.action.Action< T extends Mob >.getMob(), com.runehive.game.world.position.Area.inRegularDonatorZone(), com.runehive.game.world.position.Area.inSuperDonatorZone(), npc, pickpocket, com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), com.runehive.game.world.entity.mob.data.LockType.STUN, com.runehive.game.world.entity.skill.Skill.THIEVING, and com.runehive.Config.THIEVING_MODIFICATION.
failureRate()
int com.runehive.content.skill.impl.thieving.PickpocketAction.failureRate (Player player) private
The failure rate for pickpocketing.
Definition at line 36 of file PickpocketAction.java.
{
        double f1 = pickpocket.getLevel() / 10;
        double f2 = 100 / ((player.skills.getMaxLevel(Skill.THIEVING) + 1) - pickpocket.getLevel());
        return (int) Math.floor((f2 + f1) / 2);
    }
References com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), pickpocket, com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.skill.Skill.THIEVING.
Referenced by execute().
getName()
String com.runehive.content.skill.impl.thieving.PickpocketAction.getName ()
Gets the name of this action.
Returns
The name of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 68 of file PickpocketAction.java.
{
        return "Thieving pickpocket";
    }
getWalkablePolicy()
WalkablePolicy com.runehive.content.skill.impl.thieving.PickpocketAction.getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 78 of file PickpocketAction.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
prioritized()
boolean com.runehive.content.skill.impl.thieving.PickpocketAction.prioritized ()
Determines if this action is prioritized.
When making an action prioritized, the next action will be ignored if not queued.
Returns
true if this action is prioritized, false otherwise.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 73 of file PickpocketAction.java.
{
        return false;
    }
Member Data Documentation
npc
final Npc com.runehive.content.skill.impl.thieving.PickpocketAction.npc private
The npc being pickpocketed.
Definition at line 26 of file PickpocketAction.java.
Referenced by execute(), and PickpocketAction().
pickpocket
final PickpocketData com.runehive.content.skill.impl.thieving.PickpocketAction.pickpocket private
The pickpocket data.
Definition at line 23 of file PickpocketAction.java.
Referenced by execute(), failureRate(), and PickpocketAction().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/thieving/PickpocketAction.java