RuneHive-Game: com.runehive.content.puzzle.PuzzleDisplay Class Reference
com.runehive.content.puzzle.PuzzleDisplay Class Reference
Handles displaying the puzzle.
Public Member Functions
boolean click (int button)
Handles clicking on the puzzle interface.
void open (PuzzleType puzzleType)
Opens the puzzle interface.
PuzzleDisplay (Player player)
Constructs a new PuzzleDisplay.
Package Attributes
int successCount
The success count.
Private Member Functions
boolean checkAnswer (int button)
Checks the puzzle answer.
void randomize ()
Randomize the puzzle.
Private Attributes
int[] options
The options array.
final Player player
The player instance.
PuzzleData puzzle
The puzzle data.
PuzzleType type
The puzzle type.
Detailed Description
Handles displaying the puzzle.
Author
Daniel
Definition at line 12 of file PuzzleDisplay.java.
Constructor & Destructor Documentation
PuzzleDisplay()
com.runehive.content.puzzle.PuzzleDisplay.PuzzleDisplay (Player player)
Constructs a new PuzzleDisplay.
Definition at line 29 of file PuzzleDisplay.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
checkAnswer()
boolean com.runehive.content.puzzle.PuzzleDisplay.checkAnswer (int button) private
Checks the puzzle answer.
Definition at line 55 of file PuzzleDisplay.java.
{
        int index = button - 4550;
        int model = options[index];
        return model == puzzle.getAnswer();
    }
References options, and puzzle.
Referenced by click().
click()
boolean com.runehive.content.puzzle.PuzzleDisplay.click (int button)
Handles clicking on the puzzle interface.
Definition at line 62 of file PuzzleDisplay.java.
{
        switch (button) {
            case 4550:
            case 4551:
            case 4552:
                if (checkAnswer(button)) {
                    successCount++;
                    type.onSuccess(player);
                    return true;
                }
                successCount = 0;
                type.onFailure(player);
                return true;
        }
        return false;
    }
References checkAnswer(), player, successCount, and type.
open()
void com.runehive.content.puzzle.PuzzleDisplay.open (PuzzleType puzzleType)
Opens the puzzle interface.
Definition at line 40 of file PuzzleDisplay.java.
{
        randomize();
        for (int index = 0; index < 3; index++) {
            int sequenceModel = puzzle.getSequenceModel(index);
            int optionModel = options[index];
            player.send(new SendInterfaceWidget(4545 + index, sequenceModel));
            player.send(new SendInterfaceWidget(4550 + index, optionModel));
        }
        type = puzzleType;
        player.interfaceManager.open(4543);
    }
References options, player, puzzle, randomize(), and type.
Referenced by com.runehive.content.bloodmoney.BloodMoneyChest.open().
randomize()
void com.runehive.content.puzzle.PuzzleDisplay.randomize () private
Randomize the puzzle.
Definition at line 34 of file PuzzleDisplay.java.
{
        this.puzzle = PuzzleData.PUZZLES[(int) (Math.random() * PuzzleData.PUZZLES.length)];
        this.options = Utility.shuffleArray(puzzle.getOptions());
    }
References puzzle, com.runehive.content.puzzle.PuzzleData.PUZZLES, and com.runehive.util.Utility.shuffleArray().
Referenced by open().
Member Data Documentation
options
int [] com.runehive.content.puzzle.PuzzleDisplay.options private
The options array.
Definition at line 20 of file PuzzleDisplay.java.
Referenced by checkAnswer(), and open().
player
final Player com.runehive.content.puzzle.PuzzleDisplay.player private
The player instance.
Definition at line 14 of file PuzzleDisplay.java.
Referenced by click(), open(), and PuzzleDisplay().
puzzle
PuzzleData com.runehive.content.puzzle.PuzzleDisplay.puzzle private
The puzzle data.
Definition at line 17 of file PuzzleDisplay.java.
Referenced by checkAnswer(), open(), and randomize().
successCount
int com.runehive.content.puzzle.PuzzleDisplay.successCount package
The success count.
Definition at line 26 of file PuzzleDisplay.java.
Referenced by click().
type
PuzzleType com.runehive.content.puzzle.PuzzleDisplay.type private
The puzzle type.
Definition at line 23 of file PuzzleDisplay.java.
Referenced by click(), and open().
The documentation for this class was generated from the following file:
java/com/runehive/content/puzzle/PuzzleDisplay.java