RuneHive-Game: com.runehive.content.itemaction.impl.ToxicBlowpipe Class Reference
com.runehive.content.itemaction.impl.ToxicBlowpipe Class Reference
Public Member Functions
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
ToxicBlowpipe ()
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
String message (Item item)
The message of the action.
String toString ()
Static Public Member Functions
static void check (Player player)
Static Private Member Functions
static void charge (Player player, Item scales)
static void load (Player player, Item ammo)
static void uncharge (Player player)
static void unload (Player player, Item item)
Static Private Attributes
static final short CHARGED_BLOWPIPE = 12_926
static final DecimalFormat FORMATTER = new DecimalFormat("#.#")
static final short FULL = 16_383
static final short UNCHARGED_BLOWPIPE = 12_924
static final short ZULRAH_SCALES = 12_934
Detailed Description
Definition at line 13 of file ToxicBlowpipe.java.
Constructor & Destructor Documentation
ToxicBlowpipe()
com.runehive.content.itemaction.impl.ToxicBlowpipe.ToxicBlowpipe ()
Definition at line 20 of file ToxicBlowpipe.java.
{
        FORMATTER.setRoundingMode(RoundingMode.FLOOR);
    }
References FORMATTER.
Member Function Documentation
charge()
void com.runehive.content.itemaction.impl.ToxicBlowpipe.charge (Player player, Item scales) static private
Definition at line 119 of file ToxicBlowpipe.java.
{
        if (player.blowpipeScales >= FULL) {
            player.send(new SendMessage("Your blowpipe is already fully charged."));
            return;
        }
        if (Integer.MAX_VALUE - scales.getAmount() < FULL) {
            scales = scales.copy();
            scales.setAmount((int) (FULL - player.blowpipeScales));
        }
        if (player.blowpipeScales + scales.getAmount() > FULL) {
            scales = scales.copy();
            scales.setAmount((int) (FULL - player.blowpipeScales));
        }
        player.blowpipeScales += scales.getAmount();
        player.inventory.remove(scales);
        player.inventory.replace(UNCHARGED_BLOWPIPE, CHARGED_BLOWPIPE, true);
        player.send(new SendMessage(String.format("You load %s scales into your blowpipe.", Utility.formatDigits(scales.getAmount()))));
    }
References com.runehive.game.world.entity.mob.player.Player.blowpipeScales, CHARGED_BLOWPIPE, com.runehive.game.world.items.Item.copy(), com.runehive.util.Utility.formatDigits(), FULL, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.items.Item.setAmount(), and UNCHARGED_BLOWPIPE.
Referenced by itemOnItem().
check()
void com.runehive.content.itemaction.impl.ToxicBlowpipe.check (Player player) static
Definition at line 82 of file ToxicBlowpipe.java.
{
        String ammo = "None";
        if (player.blowpipeDarts != null && player.blowpipeDarts.getAmount() > 0)
            ammo = player.blowpipeDarts.getName() + " x " + player.blowpipeDarts.getAmount();
        String scales = FORMATTER.format(player.blowpipeScales * 100 / FULL) + "%";
        player.send(new SendMessage("Darts: <col=007F00>" + ammo + "</col>. Charges: <col=007F00>" + scales));
    }
References com.runehive.game.world.entity.mob.player.Player.blowpipeDarts, com.runehive.game.world.entity.mob.player.Player.blowpipeScales, FORMATTER, FULL, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getName(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by equipment(), and inventory().
drop()
boolean com.runehive.content.itemaction.impl.ToxicBlowpipe.drop (Player player, Item item)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 77 of file ToxicBlowpipe.java.
{
        uncharge(player);
        return true;
    }
References uncharge().
equipment()
boolean com.runehive.content.itemaction.impl.ToxicBlowpipe.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 69 of file ToxicBlowpipe.java.
{
        if (opcode == 1) {
            check(player);
        }
        return true;
    }
References check().
inventory()
boolean com.runehive.content.itemaction.impl.ToxicBlowpipe.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 59 of file ToxicBlowpipe.java.
{
        if (opcode == 2) {
            check(player);
        } else if (opcode == 3) {
            unload(player, item);
        }
        return true;
    }
References check(), and unload().
itemOnItem()
boolean com.runehive.content.itemaction.impl.ToxicBlowpipe.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 30 of file ToxicBlowpipe.java.
{
        Item item = first;
        if ((first.getId() == UNCHARGED_BLOWPIPE && second.getId() != ZULRAH_SCALES)
                || (second.getId() == UNCHARGED_BLOWPIPE && first.getId() != ZULRAH_SCALES)) {
            player.send(new SendMessage("You can't load an uncharged blowpipe!"));
            return true;
        }
        if (first.getId() == UNCHARGED_BLOWPIPE || first.getId() == CHARGED_BLOWPIPE) {
            item = second;
        }
        if (item.getId() == ZULRAH_SCALES) {
            charge(player, item);
            return true;
        }
        RangedAmmunition ammo = RangedAmmunition.find(null, item);
        if (ammo == null || !ammo.isDart()) {
            player.send(new SendMessage("You can't load your blowpipe with this!"));
            return true;
        }
        load(player, item);
        return true;
    }
References charge(), CHARGED_BLOWPIPE, com.runehive.game.world.entity.combat.ranged.RangedAmmunition.find(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.combat.ranged.RangedAmmunition.isDart(), load(), com.runehive.game.world.entity.mob.player.Player.send(), UNCHARGED_BLOWPIPE, and ZULRAH_SCALES.
load()
void com.runehive.content.itemaction.impl.ToxicBlowpipe.load (Player player, Item ammo) static private
Definition at line 164 of file ToxicBlowpipe.java.
{
        if (player.blowpipeDarts != null && player.blowpipeDarts.getAmount() >= FULL) {
            player.send(new SendMessage("Your blowpipe is already fully loaded."));
            return;
        }
        if (ammo.getAmount() > FULL) {
            ammo = new Item(ammo.getId(), FULL);
        }
        if (player.blowpipeDarts == null) {
            player.blowpipeDarts = ammo;
            player.inventory.remove(ammo);
            player.send(new SendMessage(String.format("You load your blowpipe with %s %ss.", Utility.formatDigits(ammo.getAmount()), ammo.getName())));
            return;
        }
        if (player.blowpipeDarts.getId() != ammo.getId()) {
            player.send(new SendMessage("You need to unload your blowpipe before adding a different type of dart!"));
            return;
        }
        int remove;
        if (player.blowpipeDarts.getAmount() + ammo.getAmount() > FULL) {
            remove = FULL - player.blowpipeDarts.getAmount();
        } else {
            remove = ammo.getAmount();
        }
        player.blowpipeDarts.incrementAmountBy(remove);
        player.inventory.remove(ammo.getId(), remove);
        player.send(new SendMessage(String.format("You load your blowpipe with %s %s.", Utility.formatDigits(ammo.getAmount()), ammo.getName())));
    }
References com.runehive.game.world.entity.mob.player.Player.blowpipeDarts, com.runehive.util.Utility.formatDigits(), FULL, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.Item.incrementAmountBy(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.ItemContainer.remove(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by itemOnItem().
name()
String com.runehive.content.itemaction.impl.ToxicBlowpipe.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 25 of file ToxicBlowpipe.java.
{
        return "Toxic Blowpipe";
    }
uncharge()
void com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge (Player player) static private
Definition at line 141 of file ToxicBlowpipe.java.
{
        if (player.blowpipeScales <= 0) {
            player.send(new SendMessage("Your blowpipe doesn't have any charges."));
            return;
        }
        if (player.blowpipeDarts != null && player.blowpipeDarts.getAmount() > 0) {
            player.send(new SendMessage("You need to unload your blowpipe first."));
            return;
        }
        Item scales = new Item(ZULRAH_SCALES, (int) player.blowpipeScales);
        if (!player.inventory.hasCapacityFor(scales)) {
            player.send(new SendMessage("You need more inventory space to do this."));
            return;
        }
        player.blowpipeScales = 0;
        player.inventory.add(scales);
        player.inventory.replace(CHARGED_BLOWPIPE, UNCHARGED_BLOWPIPE, true);
        player.send(new SendMessage(String.format("You uncharged your blowpipe and received %s of Zulra's scales.", Utility.formatDigits(scales.getAmount()))));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.Player.blowpipeDarts, com.runehive.game.world.entity.mob.player.Player.blowpipeScales, CHARGED_BLOWPIPE, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.entity.mob.player.Player.send(), UNCHARGED_BLOWPIPE, and ZULRAH_SCALES.
Referenced by drop().
unload()
void com.runehive.content.itemaction.impl.ToxicBlowpipe.unload (Player player, Item item) static private
Definition at line 90 of file ToxicBlowpipe.java.
{
        if (item.getId() == 12924) {
            int current = player.inventory.computeAmountForId(ZULRAH_SCALES);
            if (Integer.MAX_VALUE - current < 20_000) {
                player.send(new SendMessage("You need to deposit some of your scales first."));
                return;
            }
            player.inventory.remove(item);
            player.inventory.add(new Item(ZULRAH_SCALES, 20_000));
            player.send(new SendMessage("You dismantle your blowpipe and receive 20,000 of Zulra's scales."));
        } else {
            if (player.inventory.getFreeSlots() < 1) {
                player.send(new SendMessage("You need at least one free slot to unload your blowpipe."));
                return;
            }
            Item darts = player.blowpipeDarts;
            if (darts == null) {
                player.send(new SendMessage("You have no darts to unload."));
                return;
            }
            player.inventory.add(darts);
            player.blowpipeDarts = null;
            player.send(new SendMessage("You unload the darts out of your blowpipe."));
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.Player.blowpipeDarts, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), and ZULRAH_SCALES.
Referenced by inventory().
Member Data Documentation
CHARGED_BLOWPIPE
final short com.runehive.content.itemaction.impl.ToxicBlowpipe.CHARGED_BLOWPIPE = 12_926 static private
Definition at line 17 of file ToxicBlowpipe.java.
Referenced by charge(), itemOnItem(), and uncharge().
FORMATTER
final DecimalFormat com.runehive.content.itemaction.impl.ToxicBlowpipe.FORMATTER = new DecimalFormat("#.#") static private
Definition at line 18 of file ToxicBlowpipe.java.
Referenced by check(), and ToxicBlowpipe().
FULL
final short com.runehive.content.itemaction.impl.ToxicBlowpipe.FULL = 16_383 static private
Definition at line 14 of file ToxicBlowpipe.java.
Referenced by charge(), check(), and load().
UNCHARGED_BLOWPIPE
final short com.runehive.content.itemaction.impl.ToxicBlowpipe.UNCHARGED_BLOWPIPE = 12_924 static private
Definition at line 16 of file ToxicBlowpipe.java.
Referenced by charge(), itemOnItem(), and uncharge().
ZULRAH_SCALES
final short com.runehive.content.itemaction.impl.ToxicBlowpipe.ZULRAH_SCALES = 12_934 static private
Definition at line 15 of file ToxicBlowpipe.java.
Referenced by itemOnItem(), uncharge(), and unload().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/ToxicBlowpipe.java