RuneHive-Game: com.runehive.content.donators.Donation Class Reference
com.runehive.content.donators.Donation Class Reference
This class handles everything related to donators.
Public Member Functions
Donation (Player player)
int getCredits ()
int getSpent ()
void redeem (DonatorBond bond)
void setCredits (int credits)
void setSpent (int spent)
void updateRank (boolean login)
Private Attributes
int credits
final Player player
int spent
Static Private Attributes
static final Logger logger = LogManager.getLogger(Donation.class)
Detailed Description
This class handles everything related to donators.
Author
Daniel
Definition at line 19 of file Donation.java.
Constructor & Destructor Documentation
Donation()
com.runehive.content.donators.Donation.Donation (Player player)
Definition at line 27 of file Donation.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
getCredits()
int com.runehive.content.donators.Donation.getCredits ()
Definition at line 71 of file Donation.java.
{
        return credits;
    }
References credits.
Referenced by com.runehive.content.store.currency.impl.DonatorPointCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.dialogue.impl.RoyalKingDialogue.myStats(), com.runehive.content.store.currency.impl.DonatorPointCurrency.recieveCurrency(), redeem(), and com.runehive.content.store.currency.impl.DonatorPointCurrency.takeCurrency().
getSpent()
int com.runehive.content.donators.Donation.getSpent ()
Definition at line 75 of file Donation.java.
{
        return spent;
    }
References spent.
Referenced by com.runehive.content.dialogue.impl.RoyalKingDialogue.myStats(), and redeem().
redeem()
void com.runehive.content.donators.Donation.redeem (DonatorBond bond)
Definition at line 31 of file Donation.java.
{
        setSpent(getSpent() + bond.moneySpent);
        setCredits(getCredits() + bond.credits);
        player.message("<col=FF0000>You have claimed your donator bond. You now have " + Utility.formatDigits(getCredits()) + " donator credits!");
        World.sendMessage("<col=CF2192>osroyale: <col=" + player.right.getColor() + ">" + player.getName() + " </col>has opened <col=CF2192>" + Utility.formatEnum(bond.name()) + "");
        updateRank(false);
    }
References com.runehive.content.donators.DonatorBond.credits, com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatEnum(), getCredits(), getSpent(), com.runehive.content.donators.DonatorBond.moneySpent, player, com.runehive.game.world.World.sendMessage(), setCredits(), setSpent(), and updateRank().
setCredits()
void com.runehive.content.donators.Donation.setCredits (int credits)
Definition at line 79 of file Donation.java.
{
        this.credits = credits;
    }
References credits.
Referenced by com.runehive.content.store.currency.impl.DonatorPointCurrency.recieveCurrency(), redeem(), and com.runehive.content.store.currency.impl.DonatorPointCurrency.takeCurrency().
setSpent()
void com.runehive.content.donators.Donation.setSpent (int spent)
Definition at line 83 of file Donation.java.
{
        this.spent = spent;
    }
References spent.
Referenced by redeem().
updateRank()
void com.runehive.content.donators.Donation.updateRank (boolean login)
Definition at line 39 of file Donation.java.
{
        PlayerRight rank = PlayerRight.forSpent(spent);
        if (rank == null) {
            return;
        }
        if (player.right.equals(rank)) {
            return;
        }
        if (login) {
            if (!PlayerRight.isIronman(player) && !PlayerRight.isHelper(player)) {
                player.right = rank;
                player.updateFlags.add(UpdateFlag.APPEARANCE);
            }
            return;
        }
        if (PlayerRight.isIronman(player)) {
            player.message("Since you are an iron man, your rank icon will not change.");
        } else if (!PlayerRight.isModerator(player)) {
            player.right = rank;
            player.updateFlags.add(UpdateFlag.APPEARANCE);
        }
        String name = rank.getName();
        player.send(new SendAnnouncement("Rank Level Up!", "You are now " + Utility.getAOrAn(name) + " " + PlayerRight.getCrown(player) + " " + name + "!", 0x1C889E));
        player.dialogueFactory.sendStatement("You are now " + Utility.getAOrAn(name) + " " + PlayerRight.getCrown(player) + " " + name + "!").execute();
        InterfaceWriter.write(new InformationWriter(player));
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.game.world.entity.mob.player.PlayerRight.forSpent(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.entity.mob.player.PlayerRight.getName(), com.runehive.game.world.entity.mob.player.PlayerRight.isHelper(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.game.world.entity.mob.player.PlayerRight.isModerator(), player, spent, and com.runehive.content.writer.InterfaceWriter.write().
Referenced by redeem().
Member Data Documentation
credits
int com.runehive.content.donators.Donation.credits private
Definition at line 24 of file Donation.java.
Referenced by getCredits(), and setCredits().
logger
final Logger com.runehive.content.donators.Donation.logger = LogManager.getLogger(Donation.class) static private
Definition at line 21 of file Donation.java.
player
final Player com.runehive.content.donators.Donation.player private
Definition at line 23 of file Donation.java.
Referenced by Donation(), redeem(), and updateRank().
spent
int com.runehive.content.donators.Donation.spent private
Definition at line 25 of file Donation.java.
Referenced by getSpent(), setSpent(), and updateRank().
The documentation for this class was generated from the following file:
java/com/runehive/content/donators/Donation.java