RuneHive-Game: com.runehive.game.world.entity.skill.SkillManager Class Reference
com.runehive.game.world.entity.skill.SkillManager Class Reference
Manages all skills related to an mob.
Public Member Functions
void addExperience (int id, double experience)
Adds experience to a given skill.
void addExperience (int id, double experience, boolean levelUp)
Adds experience to a given skill.
void addExperience (int id, double experience, boolean levelUp, boolean counter)
Adds experience to a given skill.
Skill get (int id)
Gets the skill for an id.
int getCombatLevel ()
Gets the mob's combat level.
int getExpCounter ()
Gets the experience counter value.
int getLevel (int id)
Gets the level of a skill.
int getMaxLevel (int id)
Gets the highest possible level of a skill.
Skill[] getSkills ()
Gets the skills of the mob.
int getTotalLevel ()
Gets the total level of the mob.
long getTotalXp ()
boolean isMaxed ()
Checks if the mob is maxed in all skills.
void login ()
Handles a player logging in.
void master ()
Handles mastering all skills.
void modifyLevel (Function< Integer, Integer > modification, int id)
Sets the level of a skill.
void modifyLevel (Function< Integer, Integer > modification, int id, int lowerBound, int upperBound)
Sets the level of a skill.
boolean onEvent (InteractionEvent interactionEvent)
The interactionEvent listener.
void refresh ()
Refreshes all the skills for the mob.
void refresh (int id)
Refreshes a skill to a player's client if this class's mob is a player.
void regress (int skill)
Handles regressing the skills.
void resetSkilling ()
void restore (int id)
Restores a specific skill.
void restoreAll ()
Restores all the skills.
void sendSkills ()
Sends all skills to this player's client.
void setCombatLevel ()
Sets the mob's combat level.
void setExperience (int id, double experience)
Sets the experience for a skill.
void setLevel (int id, int level)
Sets the level of a skill.
void setMaxLevel (int id, int level)
Sets the max level of a skill.
void setNpcMaxLevel (int id, int level)
Sets the experience for a npc skill.
void setSkills (Skill[] skills)
Sets the skills of the mob.
SkillManager (Mob mob)
Constructs a new SkillManager object.
String toString ()
Static Public Member Functions
static double calculateCombat (int attack, int defence, int strength, int hp, int prayer, int ranged, int magic)
Calculates the combat level of an mob.
Public Attributes
double experienceCounter
The experience counter.
Private Member Functions
double calculateCombat ()
Calculates the combat level of an mob.
void showLevelUpInterface (Player player, Skill skill)
void updateCombat ()
Handles updating the combat level.
void updateSkill (Player player, int maxLevel, int newMax, Skill skill, boolean levelUp, boolean combat)
Handles updating a skill.
Private Attributes
double combatLevel
The mob's combat level.
final Mob mob
The mob to manage for.
Skill[] skills
An array of skills that belong to an mob.
Detailed Description
Manages all skills related to an mob.
Author
Michael | Chex
Definition at line 45 of file SkillManager.java.
Constructor & Destructor Documentation
SkillManager()
com.runehive.game.world.entity.skill.SkillManager.SkillManager (Mob mob)
Constructs a new SkillManager object.
Definition at line 60 of file SkillManager.java.
{
        this.mob = mob;
        this.skills = new Skill[mob.isPlayer() ? Skill.SKILL_COUNT : 7];
        for (int index = 0; index < skills.length; index++) {
            boolean hitpoints = mob.isPlayer() && index == 3;
            skills[index] = hitpoints ? new Skill(index, 10, 1154) : new Skill(index, 1, 0);
        }
        if (mob.isPlayer()) {
            skills[Skill.HUNTER] = new Hunter(1, 0);
            skills[Skill.COOKING] = new Cooking(1, 0);
            skills[Skill.HERBLORE] = new Herblore(1, 0);
            skills[Skill.CRAFTING] = new Crafting(1, 0);
            skills[Skill.THIEVING] = new Thieving(1, 0);
            skills[Skill.FLETCHING] = new Fletching(1, 0);
            skills[Skill.PRAYER] = new BoneSacrifice(1, 0);
            skills[Skill.FIREMAKING] = new Firemaking(1, 0);
            skills[Skill.RUNECRAFTING] = new Runecraft(1, 0);
            skills[Skill.MINING] = new Mining(1, 0);
            skills[Skill.WOODCUTTING] = new Woodcutting(1, 0);
            skills[Skill.SMITHING] = new Smithing(1, 0);
            skills[Skill.FISHING] = new Fishing(1, 0);
        }
    }
References com.runehive.game.world.entity.skill.Skill.COOKING, com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.game.world.entity.skill.Skill.FIREMAKING, com.runehive.game.world.entity.skill.Skill.FISHING, com.runehive.game.world.entity.skill.Skill.FLETCHING, com.runehive.game.world.entity.skill.Skill.HERBLORE, com.runehive.game.world.entity.skill.Skill.HUNTER, com.runehive.game.world.entity.skill.Skill.MINING, mob, com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.skill.Skill.RUNECRAFTING, com.runehive.game.world.entity.skill.Skill.SKILL_COUNT, skills, com.runehive.game.world.entity.skill.Skill.SMITHING, com.runehive.game.world.entity.skill.Skill.THIEVING, and com.runehive.game.world.entity.skill.Skill.WOODCUTTING.
Member Function Documentation
addExperience() [1/3]
void com.runehive.game.world.entity.skill.SkillManager.addExperience (int id, double experience)
Adds experience to a given skill.
The skill level will increase if the experience causes the skill to level up.
Definition at line 266 of file SkillManager.java.
{
        addExperience(id, experience, true);
    }
References addExperience().
Referenced by addExperience(), addExperience(), com.runehive.content.wintertodt.Wintertodt.award(), com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.shootingstar.ShootingStarData.decreaseDust(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.game.action.impl.RevShortcutAction.execute(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.game.action.impl.ScatterAshAction.onExecute(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.shootingstar.ShootingStar.prospect(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), and com.runehive.content.skill.impl.crafting.impl.Stringing.string().
addExperience() [2/3]
void com.runehive.game.world.entity.skill.SkillManager.addExperience (int id, double experience, boolean levelUp)
Adds experience to a given skill.
The skill level will increase if the experience causes the skill to level up.
Definition at line 271 of file SkillManager.java.
{
        addExperience(id, experience, levelUp, true);
    }
References addExperience().
addExperience() [3/3]
void com.runehive.game.world.entity.skill.SkillManager.addExperience (int id, double experience, boolean levelUp, boolean counter)
Adds experience to a given skill.
The skill level will increase if the experience causes the skill to level up.
Definition at line 276 of file SkillManager.java.
{
        if (!mob.isPlayer() || mob.getPlayer().settings.lockExperience)
            return;
        Player player = (Player) mob;
        Skill skill = get(id);
        double old = skill.getExperience();
        double modified_experience = experience;
        if(LMSGame.inGameArea(player)) {
            player.send(new SendExpCounter(skill.getSkill(), (int) modified_experience, counter));
            return;
        }
        double bonusXp = 0;
        switch(id) {
            case Skill.FARMING:
                bonusXp = Math.ceil((experience * Farming.getBonus(player)) / 100);
                break;
            case Skill.FISHING:
                bonusXp = Math.ceil((experience * Fishing.getBonus(player)) / 100);
                break;
            case Skill.MINING:
                bonusXp = Math.ceil((experience * Mining.getBonus(player)) / 100);
                break;
            case Skill.PRAYER:
                bonusXp = Math.ceil((experience * Prayer.getBonus(player)) / 100);
                break;
            case Skill.FIREMAKING:
                bonusXp = Math.ceil((experience * Firemaking.getBonus(player)) / 100);
                break;
            case Skill.WOODCUTTING:
                bonusXp = Math.ceil((experience * Woodcutting.getBonus(player)) / 100);
                break;
        }
        modified_experience += bonusXp;
        if (Config.DOUBLE_EXPERIENCE || WellOfGoodwill.isActive()) {
            modified_experience *= 2;
        }
        int maxLevel = Skill.getLevelForExperience(old);
        SkillData skillData = SkillData.values()[id];
        boolean combatSkill = skillData.isCombatSkill();
        if (counter) {
            experienceCounter += modified_experience;
        }
        player.send(new SendExpCounter(skill.getSkill(), (int) modified_experience, counter));
        int newMax = Skill.getLevelForExperience(skill.addExperience(modified_experience));
        updateSkill(player, maxLevel, newMax, skill, levelUp, combatSkill);
        if (skill.getExperience() >= 200_000_000) {
            AchievementHandler.activate(player, AchievementKey.EXPERIENCE_MASTERY, 1);
        }
        player.send(new SendSkill(skill));
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.Config.DOUBLE_EXPERIENCE, com.runehive.content.achievement.AchievementKey.EXPERIENCE_MASTERY, experienceCounter, com.runehive.game.world.entity.skill.Skill.FARMING, com.runehive.game.world.entity.skill.Skill.FIREMAKING, com.runehive.game.world.entity.skill.Skill.FISHING, com.runehive.content.skill.impl.farming.Farming.getBonus(), com.runehive.content.skill.impl.firemaking.Firemaking.getBonus(), com.runehive.content.skill.impl.fishing.Fishing.getBonus(), com.runehive.content.skill.impl.mining.Mining.getBonus(), com.runehive.content.skill.impl.woodcutting.Woodcutting.getBonus(), com.runehive.game.world.entity.mob.prayer.Prayer.getBonus(), com.runehive.game.world.entity.skill.Skill.getLevelForExperience(), com.runehive.content.lms.LMSGame.inGameArea(), com.runehive.content.WellOfGoodwill.isActive(), com.runehive.game.world.entity.skill.SkillData.isCombatSkill(), com.runehive.game.world.entity.skill.Skill.MINING, mob, com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.mob.player.Player.send(), updateSkill(), and com.runehive.game.world.entity.skill.Skill.WOODCUTTING.
calculateCombat() [1/2]
double com.runehive.game.world.entity.skill.SkillManager.calculateCombat () private
Calculates the combat level of an mob.
Definition at line 429 of file SkillManager.java.
{
        return calculateCombat(getMaxLevel(Skill.ATTACK), getMaxLevel(Skill.DEFENCE), getMaxLevel(Skill.STRENGTH), getMaxLevel(Skill.HITPOINTS), getMaxLevel(Skill.PRAYER), getMaxLevel(Skill.RANGED), getMaxLevel(Skill.MAGIC));
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, calculateCombat(), com.runehive.game.world.entity.skill.Skill.DEFENCE, getMaxLevel(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.game.world.entity.skill.Skill.MAGIC, com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.skill.Skill.RANGED, and com.runehive.game.world.entity.skill.Skill.STRENGTH.
Referenced by calculateCombat(), and setCombatLevel().
calculateCombat() [2/2]
double com.runehive.game.world.entity.skill.SkillManager.calculateCombat (int attack, int defence, int strength, int hp, int prayer, int ranged, int magic) static
Calculates the combat level of an mob.
Definition at line 85 of file SkillManager.java.
{
        int combat = (defence + hp + prayer / 2) * 250;
        int melee = (attack + strength) * 325;
        int range = (ranged / 2 + ranged) * 325;
        int mage = (magic / 2 + magic) * 325;
        combat += Math.max(Math.max(melee, range), mage);
        return combat / 1000.0;
    }
get()
Skill com.runehive.game.world.entity.skill.SkillManager.get (int id)
Gets the skill for an id.
Definition at line 95 of file SkillManager.java.
{
        if (id < 0 || id >= skills.length) {
            throw new IllegalArgumentException("The skill id is out of bounds! id=" + id);
        }
        return skills[id];
    }
References skills.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword.attack(), com.runehive.content.skill.impl.mining.Mining.attempt(), com.runehive.content.wintertodt.Wintertodt.award(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.content.skill.impl.fishing.Fishing.canFish(), com.runehive.content.skill.impl.fishing.Fishing.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.content.wintertodt.Wintertodt.getAreaAttackDamage(), com.runehive.content.wintertodt.Wintertodt.getBrazierAttackDamage(), com.runehive.content.wintertodt.Wintertodt.getColdDamage(), com.runehive.game.world.entity.combat.magic.MagicImpact.heal(), com.runehive.content.activity.infernomobs.MejRah.Ranged.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.TzKihListener.hit(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.ScorpiaOffspring.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.hit(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.game.world.entity.combat.magic.MagicImpact.kbdShock(), com.runehive.game.world.entity.combat.magic.MagicImpact.lowerSkill(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.consume.PotionData.modifySkill(), com.runehive.content.consume.PotionData.onAgilityEffect(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.content.consume.PotionData.onFishingEffect(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.consume.PotionData.onPrayerEffect(), com.runehive.content.consume.PotionData.onRestoreEffect(), com.runehive.content.ProfileViewer.open(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.lms.LMSGame.resetLevels(), com.runehive.game.service.HighscoreService.saveHighscores(), com.runehive.content.lms.LMSGame.setLevels(), com.runehive.content.skill.impl.smithing.Smelting.smelt(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.content.skill.impl.fishing.Fishing.start(), com.runehive.content.skill.impl.mining.Mining.start(), com.runehive.content.skill.impl.fishing.Fishing.success(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), and com.runehive.content.skill.impl.cooking.Cooking.useItem().
getCombatLevel()
int com.runehive.game.world.entity.skill.SkillManager.getCombatLevel ()
Gets the mob's combat level.
Definition at line 439 of file SkillManager.java.
{
        return (int) combatLevel;
    }
References combatLevel.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.combat.CombatTarget.compare(), com.runehive.content.ProfileViewer.open(), and updateCombat().
getExpCounter()
int com.runehive.game.world.entity.skill.SkillManager.getExpCounter ()
Gets the experience counter value.
Definition at line 434 of file SkillManager.java.
{
        return (int) Math.floor(experienceCounter);
    }
References experienceCounter.
getLevel()
int com.runehive.game.world.entity.skill.SkillManager.getLevel (int id)
Gets the level of a skill.
Definition at line 103 of file SkillManager.java.
{
        return get(id).getLevel();
    }
References getLevel().
Referenced by com.runehive.content.skill.impl.slayer.SlayerTask.asList(), com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.content.skill.impl.slayer.SlayerTask.canAttack(), com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.canExecute(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.canExecute(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getDefenceRoll(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getDefenceRoll(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getDefenceRoll(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getEffectiveLevel(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.getHits(), getLevel(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicLevel(), com.runehive.content.skill.impl.hunter.trap.TrapManager.getMaximumTraps(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getRangedlevel(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getRangeLevel(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getRangeLevel(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStrengthLevel(), com.runehive.game.world.entity.combat.attack.listener.item.AhrimListener.hit(), com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyAggressive(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressive(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAggressive(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalBludgen.modifyDamage(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDefensive(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensive(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensive(), com.runehive.content.skill.impl.runecrafting.Runecraft.multiplier(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.skill.impl.cooking.Cooking.success(), and com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.wasSuccesful().
getMaxLevel()
int com.runehive.game.world.entity.skill.SkillManager.getMaxLevel (int id)
Gets the highest possible level of a skill.
Definition at line 108 of file SkillManager.java.
{
        return get(id).getMaxLevel();
    }
References getMaxLevel().
Referenced by com.runehive.content.consume.FoodData.anglerfishHeal(), calculateCombat(), com.runehive.util.parser.old.defs.EquipmentRequirement.canEquip(), com.runehive.content.skill.impl.thieving.WallSafe.chance(), com.runehive.util.Utility.checkRequirements(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.emote.Skillcape.equip(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.content.skill.impl.thieving.PickpocketAction.failureRate(), com.runehive.content.skill.impl.thieving.Thieving.failureRate(), getMaxLevel(), isMaxed(), com.runehive.content.skill.SkillRepository.isSuccess(), com.runehive.content.skill.SkillRepository.isSuccess(), com.runehive.game.world.entity.combat.attack.listener.item.TwistedBowListener.modifyAccuracy(), com.runehive.game.world.entity.combat.attack.listener.item.TwistedBowListener.modifyDamage(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalBludgen.modifyDamage(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), com.runehive.content.store.impl.SkillcapeStore.purchase(), com.runehive.content.skill.impl.thieving.WallSafe.rate(), com.runehive.content.skill.impl.mining.Mining.success(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), and com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.twistedBowBonus().
getSkills()
Skill[] com.runehive.game.world.entity.skill.SkillManager.getSkills ()
Gets the skills of the mob.
Definition at line 449 of file SkillManager.java.
{
        return skills;
    }
References skills.
Referenced by com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), and com.runehive.content.lms.LMSGame.resetLevels().
getTotalLevel()
int com.runehive.game.world.entity.skill.SkillManager.getTotalLevel ()
Gets the total level of the mob.
Definition at line 173 of file SkillManager.java.
{
        int total = 0;
        for (Skill skill : skills) {
            total += skill.getMaxLevel();
        }
        return total;
    }
References skills.
Referenced by com.runehive.game.service.HighscoreService.saveHighscores(), com.runehive.content.ProfileViewer.string(), and updateSkill().
getTotalXp()
long com.runehive.game.world.entity.skill.SkillManager.getTotalXp ()
Definition at line 181 of file SkillManager.java.
{
        long totalXp = 0;
        for (Skill skill : skills) {
            totalXp += skill.getExperience();
        }
        return totalXp;
    }
References skills.
Referenced by com.runehive.game.service.HighscoreService.saveHighscores().
isMaxed()
boolean com.runehive.game.world.entity.skill.SkillManager.isMaxed ()
Checks if the mob is maxed in all skills.
Definition at line 234 of file SkillManager.java.
{
        int maxCount = Skill.SKILL_COUNT;
        int count = 0;
        for (int index = 0; index < maxCount; index++) {
            if (getMaxLevel(index) >= 99) {
                count++;
            } else {
                if (index == Skill.HUNTER)
                    count++;
                if (index == Skill.FARMING)
                    count++;
                if (index == Skill.CONSTRUCTION)
                    count++;
            }
        }
        return count == maxCount;
    }
References com.runehive.game.world.entity.skill.Skill.CONSTRUCTION, com.runehive.game.world.entity.skill.Skill.FARMING, getMaxLevel(), com.runehive.game.world.entity.skill.Skill.HUNTER, and com.runehive.game.world.entity.skill.Skill.SKILL_COUNT.
Referenced by com.runehive.net.packet.in.WieldItemPacketListener.handlePacket().
login()
void com.runehive.game.world.entity.skill.SkillManager.login ()
Handles a player logging in.
Definition at line 209 of file SkillManager.java.
{
        Smelting.clearInterfaces(mob.getPlayer());
        refresh();
        setCombatLevel();
    }
References com.runehive.content.skill.impl.smithing.Smelting.clearInterfaces(), mob, refresh(), and setCombatLevel().
master()
void com.runehive.game.world.entity.skill.SkillManager.master ()
Handles mastering all skills.
Only players should access this.
Definition at line 216 of file SkillManager.java.
{
        for (int index = 0; index < Skill.SKILL_COUNT; index++) {
            setMaxLevel(index, 99);
        }
        setCombatLevel();
        mob.updateFlags.add(UpdateFlag.APPEARANCE);
        mob.getPlayer().send(new SendMessage("You have successfully mastered all skills."));
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, mob, setCombatLevel(), setMaxLevel(), and com.runehive.game.world.entity.skill.Skill.SKILL_COUNT.
modifyLevel() [1/2]
void com.runehive.game.world.entity.skill.SkillManager.modifyLevel (Function< Integer, Integer > modification, int id)
Sets the level of a skill.
Definition at line 167 of file SkillManager.java.
{
        Skill skill = get(id);
        skill.modifyLevel(modification);
    }
modifyLevel() [2/2]
void com.runehive.game.world.entity.skill.SkillManager.modifyLevel (Function< Integer, Integer > modification, int id, int lowerBound, int upperBound)
Sets the level of a skill.
Definition at line 149 of file SkillManager.java.
{
        Skill skill = get(id);
        skill.modifyLevel(modification, lowerBound, upperBound);
    }
onEvent()
boolean com.runehive.game.world.entity.skill.SkillManager.onEvent (InteractionEvent interactionEvent)
The interactionEvent listener.
Definition at line 253 of file SkillManager.java.
{
        if (mob.is(EntityType.PLAYER)) {
            Player player = (Player) mob;
            boolean success = false;
            for (final Skill skill : skills) {
                success |= skill.onEvent(player, interactionEvent);
            }
            return success;
        }
        return false;
    }
References mob, com.runehive.game.world.entity.EntityType.PLAYER, and skills.
Referenced by com.runehive.content.event.EventDispatcher.execute().
refresh() [1/2]
void com.runehive.game.world.entity.skill.SkillManager.refresh ()
Refreshes all the skills for the mob.
Definition at line 190 of file SkillManager.java.
{
        for (final Skill skill : skills) {
            refresh(skill.getSkill());
        }
    }
References refresh(), and skills.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer.attack(), com.runehive.content.activity.infernomobs.MejRah.Ranged.hit(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.ScorpiaOffspring.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.hit(), com.runehive.game.world.entity.combat.magic.MagicImpact.kbdShock(), login(), com.runehive.game.world.entity.combat.magic.MagicImpact.lowerSkill(), com.runehive.content.consume.PotionData.modifySkill(), com.runehive.content.consume.PotionData.onAgilityEffect(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.content.consume.PotionData.onFishingEffect(), com.runehive.content.consume.PotionData.onPrayerEffect(), com.runehive.content.consume.PotionData.onRestoreEffect(), refresh(), regress(), com.runehive.content.lms.LMSGame.resetLevels(), restore(), setExperience(), setLevel(), com.runehive.content.lms.LMSGame.setLevels(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special().
refresh() [2/2]
void com.runehive.game.world.entity.skill.SkillManager.refresh (int id)
Refreshes a skill to a player's client if this class's mob is a player.
Definition at line 226 of file SkillManager.java.
{
        if (mob.isPlayer()) {
            Skill skill = get(id);
            mob.getPlayer().send(new SendSkill(skill));
        }
    }
References mob.
regress()
void com.runehive.game.world.entity.skill.SkillManager.regress (int skill)
Handles regressing the skills.
Definition at line 155 of file SkillManager.java.
{
        Skill s = get(skill);
        if (s.getLevel() > s.getMaxLevel()) {
            s.modifyLevel(level -> level - 1, 0, s.getLevel());
            refresh(skill);
        } else if (s.getLevel() < s.getMaxLevel()) {
            s.modifyLevel(level -> level + 1, 0, s.getMaxLevel());
            refresh(skill);
        }
    }
References com.runehive.game.world.entity.skill.Skill.getLevel(), com.runehive.game.world.entity.skill.Skill.getMaxLevel(), com.runehive.game.world.entity.skill.Skill.modifyLevel(), and refresh().
resetSkilling()
void com.runehive.game.world.entity.skill.SkillManager.resetSkilling ()
Definition at line 415 of file SkillManager.java.
{
        boolean doingSkill = false;
        for (Skill skill : skills) {
            if (skill.isDoingSkill()) {
                doingSkill = true;
                skill.setDoingSkill(false);
            }
        }
        if (doingSkill) {
            mob.resetAnimation();
        }
    }
References mob, and skills.
restore()
void com.runehive.game.world.entity.skill.SkillManager.restore (int id)
Restores a specific skill.
Definition at line 197 of file SkillManager.java.
{
        Skill skill = get(id);
        skill.setLevel(skill.getMaxLevel());
        refresh(id);
    }
References refresh().
restoreAll()
void com.runehive.game.world.entity.skill.SkillManager.restoreAll ()
Restores all the skills.
Definition at line 204 of file SkillManager.java.
{
        IntStream.range(0, skills.length).forEach(this::restore);
    }
References skills.
sendSkills()
void com.runehive.game.world.entity.skill.SkillManager.sendSkills ()
Sends all skills to this player's client.
If the mob created with this object is not a player, no code will be executed.
Definition at line 406 of file SkillManager.java.
{
        if (mob.is(EntityType.PLAYER)) {
            Player player = (Player) mob;
            for (Skill skill : skills) {
                player.send(new SendSkill(skill));
            }
        }
    }
References mob, com.runehive.game.world.entity.EntityType.PLAYER, com.runehive.game.world.entity.mob.player.Player.send(), and skills.
setCombatLevel()
void com.runehive.game.world.entity.skill.SkillManager.setCombatLevel ()
Sets the mob's combat level.
Definition at line 444 of file SkillManager.java.
{
        this.combatLevel = calculateCombat();
    }
References calculateCombat().
Referenced by login(), master(), and updateCombat().
setExperience()
void com.runehive.game.world.entity.skill.SkillManager.setExperience (int id, double experience)
Sets the experience for a skill.
Definition at line 132 of file SkillManager.java.
{
        Skill skill = get(id);
        int level = Skill.getLevelForExperience(experience);
        skill.setLevel(level);
        skill.setMaxLevel(level);
        skill.setExperience(experience);
        refresh(id);
    }
References com.runehive.game.world.entity.skill.Skill.getLevelForExperience(), and refresh().
Referenced by setMaxLevel().
setLevel()
void com.runehive.game.world.entity.skill.SkillManager.setLevel (int id, int level)
Sets the level of a skill.
Definition at line 113 of file SkillManager.java.
{
        get(id).setLevel(level);
        refresh(id);
    }
References refresh(), and setLevel().
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword.attack(), com.runehive.game.world.entity.combat.attack.listener.item.AhrimListener.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.TzKihListener.hit(), and setLevel().
setMaxLevel()
void com.runehive.game.world.entity.skill.SkillManager.setMaxLevel (int id, int level)
Sets the max level of a skill.
Definition at line 119 of file SkillManager.java.
{
        setExperience(id, Skill.getExperienceForLevel(level));
        if (mob.isPlayer() && id <= Skill.MAGIC && !mob.getPlayer().quickPrayers.getEnabled().isEmpty()) {
            List<Prayer> deactivate = new LinkedList<>();
            for (Prayer prayer : mob.getPlayer().quickPrayers.getEnabled())
                if (!prayer.canToggle(mob.getPlayer()))
                    deactivate.add(prayer);
            if (!deactivate.isEmpty())
                mob.getPlayer().quickPrayers.deactivate(deactivate.toArray(new Prayer[deactivate.size()]));
        }
    }
References com.runehive.game.world.entity.skill.Skill.getExperienceForLevel(), com.runehive.game.world.entity.skill.Skill.MAGIC, mob, and setExperience().
Referenced by master().
setNpcMaxLevel()
void com.runehive.game.world.entity.skill.SkillManager.setNpcMaxLevel (int id, int level)
Sets the experience for a npc skill.
Definition at line 142 of file SkillManager.java.
{
        Skill skill = get(id);
        skill.setLevel(level);
        skill.setMaxLevel(level);
    }
setSkills()
void com.runehive.game.world.entity.skill.SkillManager.setSkills (Skill[] skills)
Sets the skills of the mob.
Definition at line 454 of file SkillManager.java.
{
        this.skills = skills;
        if (mob.isPlayer()) {
            this.skills[Skill.HUNTER] = new Hunter(skills[Skill.HUNTER].getLevel(), skills[Skill.HUNTER].getExperience());
            this.skills[Skill.PRAYER] = new BoneSacrifice(skills[Skill.PRAYER].getLevel(), skills[Skill.PRAYER].getExperience());
            this.skills[Skill.COOKING] = new Cooking(skills[Skill.COOKING].getLevel(), skills[Skill.COOKING].getExperience());
            this.skills[Skill.CRAFTING] = new Crafting(skills[Skill.CRAFTING].getLevel(), skills[Skill.CRAFTING].getExperience());
            this.skills[Skill.THIEVING] = new Thieving(skills[Skill.THIEVING].getLevel(), skills[Skill.THIEVING].getExperience());
            this.skills[Skill.HERBLORE] = new Herblore(skills[Skill.HERBLORE].getLevel(), skills[Skill.HERBLORE].getExperience());
            this.skills[Skill.FLETCHING] = new Fletching(skills[Skill.FLETCHING].getLevel(), skills[Skill.FLETCHING].getExperience());
            this.skills[Skill.FIREMAKING] = new Firemaking(skills[Skill.FIREMAKING].getLevel(), skills[Skill.FIREMAKING].getExperience());
            this.skills[Skill.RUNECRAFTING] = new Runecraft(skills[Skill.RUNECRAFTING].getLevel(), skills[Skill.RUNECRAFTING].getExperience());
            this.skills[Skill.MINING] = new Mining(skills[Skill.MINING].getLevel(), skills[Skill.MINING].getExperience());
            this.skills[Skill.SMITHING] = new Smithing(skills[Skill.SMITHING].getLevel(), skills[Skill.SMITHING].getExperience());
            this.skills[Skill.WOODCUTTING] = new Woodcutting(skills[Skill.WOODCUTTING].getLevel(), skills[Skill.WOODCUTTING].getExperience());
            this.skills[Skill.FISHING] = new Fishing(skills[Skill.FISHING].getLevel(), skills[Skill.FISHING].getExperience());
        }
    }
References com.runehive.game.world.entity.skill.Skill.COOKING, com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.game.world.entity.skill.Skill.FIREMAKING, com.runehive.game.world.entity.skill.Skill.FISHING, com.runehive.game.world.entity.skill.Skill.FLETCHING, com.runehive.game.world.entity.skill.Skill.HERBLORE, com.runehive.game.world.entity.skill.Skill.HUNTER, com.runehive.game.world.entity.skill.Skill.MINING, mob, com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.skill.Skill.RUNECRAFTING, skills, com.runehive.game.world.entity.skill.Skill.SMITHING, com.runehive.game.world.entity.skill.Skill.THIEVING, and com.runehive.game.world.entity.skill.Skill.WOODCUTTING.
showLevelUpInterface()
void com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface (Player player, Skill skill) private
Definition at line 373 of file SkillManager.java.
{
        SkillData skillData = SkillData.values()[skill.getSkill()];
        String line1 = "Congratulations! You've just advanced " + Utility.getAOrAn(skillData.toString()) + " " + skillData + " level!";
        String line2 = "You have reached level " + skill.getMaxLevel() + "!";
        player.send(new SendString(line1, skillData.getFirstLine()));
        player.send(new SendString(line2, skillData.getSecondLine()));
        player.send(new SendChatBoxInterface(skillData.getChatbox()));
        if(skillData == SkillData.HUNTER) {
            player.send(new SendMoveComponent(0, 5, 311));
            player.send(new SendInterfaceConfig(311, 200, 9951));
        }
        if(skillData == SkillData.FARMING) {
            player.send(new SendMoveComponent(0, 30, 311));
            player.send(new SendInterfaceConfig(311, 200, 5340));
        }
        String name = Skill.getName(skill.getSkill());
        player.send(new SendMessage("Congratulations, you just advanced " + Utility.getAOrAn(name) + " " + name + " level."));
        player.graphic(new Graphic(199, UpdatePriority.VERY_HIGH));
        player.dialogueFactory.setActive(true);
    }
References com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.game.world.entity.skill.SkillData.FARMING, com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.entity.skill.SkillData.getChatbox(), com.runehive.game.world.entity.skill.SkillData.getFirstLine(), com.runehive.game.world.entity.skill.Skill.getName(), com.runehive.game.world.entity.skill.SkillData.getSecondLine(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.skill.SkillData.HUNTER, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.setActive(), com.runehive.game.world.entity.skill.SkillData.toString(), and com.runehive.game.UpdatePriority.VERY_HIGH.
Referenced by updateSkill().
toString()
String com.runehive.game.world.entity.skill.SkillManager.toString ()
Definition at line 474 of file SkillManager.java.
{
        return super.toString();
    }
updateCombat()
void com.runehive.game.world.entity.skill.SkillManager.updateCombat () private
Handles updating the combat level.
Definition at line 395 of file SkillManager.java.
{
        int oldLevel = (int) getCombatLevel();
        setCombatLevel();
        int newLevel = (int) getCombatLevel();
        if (newLevel != oldLevel) {
            mob.updateFlags.add(UpdateFlag.APPEARANCE);
            mob.getPlayer().send(new SendMessage("You've reached a combat level of " + newLevel + "."));
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, getCombatLevel(), mob, and setCombatLevel().
Referenced by updateSkill().
updateSkill()
void com.runehive.game.world.entity.skill.SkillManager.updateSkill (Player player, int maxLevel, int newMax, Skill skill, boolean levelUp, boolean combat) private
Handles updating a skill.
Definition at line 339 of file SkillManager.java.
{
        if (maxLevel < 99 && newMax != maxLevel) {
            skill.setMaxLevel(newMax);
            if (skill.getLevel() <= newMax) {
                skill.modifyLevel(level -> (newMax - maxLevel) + level);
            }
            if (levelUp) {
                if (newMax > 99) {
                }
                showLevelUpInterface(player, skill);
                if (newMax == 99 && !combat) {
                    World.sendMessage(
                            "<col=7B44B3>osroyale: <col=" + player.right.getColor() + ">" + player.getName() + " </col>has just reached level 99 in <col=7B44B3>" + Skill.getName(skill.getSkill()) + "</col> with a prestige of " +player.prestige.totalPrestige + "!");
                    // DiscordPlugin.sendSimpleMessage(player.getName() + " has just reached level 99 in " + Skill.getName(skill.getSkill()) + "!");
                }
            } else {
                player.send(new SendMessage("Congratulations, you have reached " + Utility.getAOrAn(Skill.getName(skill.getSkill())) + " " + Skill.getName(skill.getSkill()) + " level of " + skill.getMaxLevel() + "."));
            }
            if (SkillData.values()[skill.getSkill()].isCombatSkill()) {
                updateCombat();
            }
            if (skill.getMaxLevel() == 99) {
                AchievementHandler.activate(player, AchievementKey.SKILL_MASTERY, 1);
            }
            AchievementHandler.set(player, AchievementKey.TOTAL_LEVEL, getTotalLevel());
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.entity.mob.player.PlayerRight.getColor(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.skill.Skill.getName(), getTotalLevel(), com.runehive.game.world.entity.skill.SkillData.isCombatSkill(), com.runehive.game.world.entity.mob.player.Player.prestige, com.runehive.game.world.entity.mob.player.Player.right, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.World.sendMessage(), com.runehive.content.achievement.AchievementHandler.set(), showLevelUpInterface(), com.runehive.content.achievement.AchievementKey.SKILL_MASTERY, com.runehive.content.achievement.AchievementKey.TOTAL_LEVEL, com.runehive.content.prestige.Prestige.totalPrestige, and updateCombat().
Referenced by addExperience().
Member Data Documentation
combatLevel
double com.runehive.game.world.entity.skill.SkillManager.combatLevel private
The mob's combat level.
Definition at line 57 of file SkillManager.java.
Referenced by getCombatLevel().
experienceCounter
double com.runehive.game.world.entity.skill.SkillManager.experienceCounter
The experience counter.
Definition at line 51 of file SkillManager.java.
Referenced by addExperience(), getExpCounter(), and com.runehive.content.lms.lobby.LMSLobby.joinLobby().
mob
final Mob com.runehive.game.world.entity.skill.SkillManager.mob private
The mob to manage for.
Definition at line 48 of file SkillManager.java.
Referenced by addExperience(), login(), master(), onEvent(), refresh(), resetSkilling(), sendSkills(), setMaxLevel(), setSkills(), SkillManager(), and updateCombat().
skills
Skill [] com.runehive.game.world.entity.skill.SkillManager.skills private
An array of skills that belong to an mob.
Definition at line 54 of file SkillManager.java.
Referenced by get(), getSkills(), getTotalLevel(), getTotalXp(), onEvent(), refresh(), resetSkilling(), restoreAll(), sendSkills(), setSkills(), and SkillManager().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/skill/SkillManager.java