RuneHive-Game: com.runehive.game.plugin.extension.CommandExtension Class Reference
com.runehive.game.plugin.extension.CommandExtension Class Reference abstract
Public Member Functions
abstract boolean canAccess (Player player)
void onInit ()
Public Member Functions inherited from com.runehive.game.plugin.PluginContext
boolean accept (Player player, Event event)
The method that allows an event listener to accept an event.
Public Member Functions inherited from com.runehive.game.event.listener.EventListener
default void accept (Event event)
Public Attributes
final Multimap< String, Command > multimap = ArrayListMultimap.create()
Static Public Attributes
static final Logger logger = LogManager.getLogger(CommandExtension.class)
Static Public Attributes inherited from com.runehive.game.plugin.PluginContext
static final Logger logger = LogManager.getLogger(PluginContext.class)
Protected Member Functions
boolean handleCommand (Player player, CommandParser parser)
abstract void register ()
Protected Member Functions inherited from com.runehive.game.plugin.PluginContext
boolean allButOneItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean fifthClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean firstClickItem (Player player, ItemClickEvent event)
boolean firstClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean firstClickNpc (Player player, NpcClickEvent event)
boolean firstClickObject (Player player, ObjectClickEvent event)
boolean fourthClickItem (Player player, ItemClickEvent event)
boolean fourthClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean fourthClickNpc (Player player, NpcClickEvent event)
boolean itemOnItem (Player player, ItemOnItemEvent event)
boolean itemOnNpc (Player player, ItemOnNpcEvent event)
boolean itemOnObject (Player player, ItemOnObjectEvent event)
boolean itemOnPlayer (Player player, ItemOnPlayerEvent event)
boolean modifiableXItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean onClick (final Player player, final int button)
boolean onDropItem (Player player, DropItemEvent event)
boolean onMovement (Player player, MovementEvent event)
boolean onPickupItem (Player player, PickupItemEvent event)
boolean secondClickItem (Player player, ItemClickEvent event)
boolean secondClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean secondClickNpc (Player player, NpcClickEvent event)
boolean secondClickObject (Player player, ObjectClickEvent event)
boolean sixthClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean thirdClickItem (Player player, ItemClickEvent event)
boolean thirdClickItemContainer (Player player, ItemContainerContextMenuEvent event)
boolean thirdClickNpc (Player player, NpcClickEvent event)
boolean thirdClickObject (Player player, ObjectClickEvent event)
Protected Attributes
final Set< Command > commands = new HashSet<>()
Static Protected Attributes
static final Set< CommandExtension > extensions = new HashSet<>()
Static Private Member Functions
static boolean canExecute (Player player, CommandParser parser)
Detailed Description
Definition at line 17 of file CommandExtension.java.
Member Function Documentation
canAccess()
abstract boolean com.runehive.game.plugin.extension.CommandExtension.canAccess (Player player) abstract
canExecute()
boolean com.runehive.game.plugin.extension.CommandExtension.canExecute (Player player, CommandParser parser) static private
Definition at line 53 of file CommandExtension.java.
{
        return !player.locking.locked(PacketType.COMMANDS) || parser.getCommand().startsWith("key");
    }
References com.runehive.game.world.entity.mob.data.PacketType.COMMANDS, com.runehive.game.world.entity.mob.player.command.CommandParser.getCommand(), com.runehive.game.world.entity.mob.Locking.locked(), and com.runehive.game.world.entity.mob.Mob.locking.
Referenced by handleCommand().
handleCommand()
boolean com.runehive.game.plugin.extension.CommandExtension.handleCommand (Player player, CommandParser parser) protected
Reimplemented from com.runehive.game.plugin.PluginContext.
Definition at line 58 of file CommandExtension.java.
{
        if (!canExecute(player, parser)) {
            return true;
        }
        for (CommandExtension extension : extensions) {
            if (!extension.canAccess(player)) {
                continue;
            }
            final Collection<Command> collection = extension.multimap.get(parser.getCommand().toLowerCase());
            if (collection == null) {
                continue;
            }
            if (collection.isEmpty()) {
                continue;
            }
            final Command command = collection.toArray(new Command[0])[0];
            // execute error
            try {
                command.execute(player, parser);
            } catch (Exception ex) {
                // but dont care about the exception
            }
            return true;
        }
        return false;
    }
References canExecute(), com.runehive.game.world.entity.mob.player.command.Command.execute(), extensions, and com.runehive.game.world.entity.mob.player.command.CommandParser.getCommand().
onInit()
void com.runehive.game.plugin.extension.CommandExtension.onInit ()
Reimplemented from com.runehive.game.plugin.PluginContext.
Definition at line 26 of file CommandExtension.java.
{
        extensions.add(this);
        register();
        multimap.clear();
        for (Command command : commands) {
            if (command.getNames().length == 0) {
                logger.warn(String.format("plugin=%s command missing name.", this.getClass().getSimpleName()));
                continue;
            }
            for (String name : command.getNames()) {
                final String key = name.toLowerCase();
                if (multimap.containsKey(key)) {
                    logger.warn(String.format("plugin=%s duplicate command=%s", this.getClass().getSimpleName(), key));
                    continue;
                }
                multimap.put(key, command);
            }
        }
        commands.clear();
    }
References commands, extensions, logger, multimap, and register().
register()
abstract void com.runehive.game.plugin.extension.CommandExtension.register () abstract protected
Referenced by onInit().
Member Data Documentation
commands
final Set<Command> com.runehive.game.plugin.extension.CommandExtension.commands = new HashSet<>() protected
Definition at line 22 of file CommandExtension.java.
Referenced by onInit().
extensions
final Set<CommandExtension> com.runehive.game.plugin.extension.CommandExtension.extensions = new HashSet<>() static protected
Definition at line 20 of file CommandExtension.java.
Referenced by handleCommand(), and onInit().
logger
final Logger com.runehive.game.plugin.extension.CommandExtension.logger = LogManager.getLogger(CommandExtension.class) static
Definition at line 19 of file CommandExtension.java.
Referenced by onInit().
multimap
final Multimap<String, Command> com.runehive.game.plugin.extension.CommandExtension.multimap = ArrayListMultimap.create()
Definition at line 23 of file CommandExtension.java.
Referenced by onInit().
The documentation for this class was generated from the following file:
java/com/runehive/game/plugin/extension/CommandExtension.java