RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility Class Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility Class Reference
Created by Daniel on 2017-12-20.
Classes
enum SpawnData
Static Public Member Functions
static void defeated (Npc npc, Player player)
static String getInformation ()
Static Package Functions
static Npc generateSpawn ()
Static Package Attributes
static Npc skotizo = null
Static Private Attributes
static SpawnData data
Detailed Description
Created by Daniel on 2017-12-20.
Definition at line 14 of file SkotizoUtility.java.
Member Function Documentation
defeated()
void com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.defeated (Npc npc, Player player) static
Definition at line 35 of file SkotizoUtility.java.
{
        if (skotizo != null && skotizo.isRegistered()) {
            skotizo.unregister();
        }
        skotizo = null;
    }
References skotizo.
Referenced by com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath().
generateSpawn()
Npc com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.generateSpawn () static package
Definition at line 19 of file SkotizoUtility.java.
{
        data = SpawnData.generate();
        skotizo = new Npc(7286, data.position, 10, Mob.DEFAULT_INSTANCE, Direction.NORTH);
        skotizo.register();
        skotizo.definition.setRespawnTime(-1);
        skotizo.definition.setAggressive(true);
        skotizo.speak("Darkness is here to penetrate your souls!");
        World.sendMessage("<icon=6><col=8714E6> Skotizo has just spawned! He is located at " + data.location + "!");
        // DiscordPlugin.sendSimpleMessage("Skotizo has entered the wilderness! He is located at " + data.location + "!");
        return skotizo;
    }
References data, com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.generate(), com.runehive.game.world.entity.mob.Direction.NORTH, com.runehive.game.world.World.sendMessage(), and skotizo.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoEvent.execute().
getInformation()
String com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.getInformation () static
Definition at line 31 of file SkotizoUtility.java.
{
        return (skotizo == null || skotizo.isDead()) ? "Not Active" : data.location;
    }
References data, and skotizo.
Member Data Documentation
data
SpawnData com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.data static private
Definition at line 17 of file SkotizoUtility.java.
Referenced by generateSpawn(), and getInformation().
skotizo
Npc com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.skotizo = null static package
Definition at line 16 of file SkotizoUtility.java.
Referenced by defeated(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoEvent.execute(), generateSpawn(), and getInformation().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/skotizo/SkotizoUtility.java