RuneHive-Game: com.runehive.content.achievement.AchievementWriter Class Reference
com.runehive.content.achievement.AchievementWriter Class Reference
Handles the achievement tab.
Public Member Functions
AchievementWriter (Player player)
Public Member Functions inherited from com.runehive.content.writer.InterfaceWriter
InterfaceWriter (Player player)
void scroll ()
Protected Member Functions
int[][] color ()
int[][] font ()
int startingIndex ()
String[] text ()
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.writer.InterfaceWriter
static void write (InterfaceWriter writer)
Protected Attributes inherited from com.runehive.content.writer.InterfaceWriter
Player player
Detailed Description
Handles the achievement tab.
Author
Daniel
Definition at line 16 of file AchievementWriter.java.
Constructor & Destructor Documentation
AchievementWriter()
com.runehive.content.achievement.AchievementWriter.AchievementWriter (Player player)
Definition at line 18 of file AchievementWriter.java.
{
        super(player);
        int total = AchievementList.values().length;
        int progress = (int) (AchievementHandler.getTotalCompleted(player) * 100 / (double) AchievementList.getTotal());
        int pvp = (int) (AchievementHandler.getDifficultyCompletion(player, PVP) * 100 / (double) AchievementHandler.getDifficultyAmount(PVP));
        int pvm = (int) (AchievementHandler.getDifficultyCompletion(player, PVM) * 100 / (double) AchievementHandler.getDifficultyAmount(PVM));
        int skilling = (int) (AchievementHandler.getDifficultyCompletion(player, SKILLING) * 100 / (double) AchievementHandler.getDifficultyAmount(SKILLING));
        int minigame = (int) (AchievementHandler.getDifficultyCompletion(player, MINIGAME) * 100 / (double) AchievementHandler.getDifficultyAmount(MINIGAME));
        int miscellaneous = (int) (AchievementHandler.getDifficultyCompletion(player, MISCELLANEOUS) * 100 / (double) AchievementHandler.getDifficultyAmount(MISCELLANEOUS));
        player.send(new SendString("Player Killing (" + pvp + "%)", 35051));
        player.send(new SendColor(35051, AchievementHandler.getColor(player, PVP)));
        player.send(new SendString("Monster Killing (" + pvm + "%)", 35052));
        player.send(new SendColor(35052, AchievementHandler.getColor(player, PVM)));
        player.send(new SendString("Skilling (" + skilling + "%)", 35053));
        player.send(new SendColor(35053, AchievementHandler.getColor(player, AchievementType.SKILLING)));
        player.send(new SendString("Minigames (" + minigame + "%)", 35054));
        player.send(new SendColor(35054, AchievementHandler.getColor(player, AchievementType.MINIGAME)));
        player.send(new SendString("Miscellaneous (" + miscellaneous + "%)", 35055));
        player.send(new SendColor(35055, AchievementHandler.getColor(player, AchievementType.MISCELLANEOUS)));
        player.send(new SendScrollbar(35050, 200));
        player.send(new SendString("Completed: " + AchievementHandler.getTotalCompleted(player) + "/" + total + " (" + progress + "%)", 35004));
    }
References com.runehive.content.achievement.AchievementHandler.getColor(), com.runehive.content.achievement.AchievementHandler.getDifficultyAmount(), com.runehive.content.achievement.AchievementHandler.getDifficultyCompletion(), com.runehive.content.achievement.AchievementList.getTotal(), com.runehive.content.achievement.AchievementHandler.getTotalCompleted(), com.runehive.content.achievement.AchievementType.MINIGAME, com.runehive.content.achievement.AchievementType.MISCELLANEOUS, com.runehive.content.writer.InterfaceWriter.player, and com.runehive.content.achievement.AchievementType.SKILLING.
Member Function Documentation
color()
int[][] com.runehive.content.achievement.AchievementWriter.color () protected
Reimplemented from com.runehive.content.writer.InterfaceWriter.
Definition at line 55 of file AchievementWriter.java.
{
        return null;
    }
font()
int[][] com.runehive.content.achievement.AchievementWriter.font () protected
Reimplemented from com.runehive.content.writer.InterfaceWriter.
Definition at line 60 of file AchievementWriter.java.
{
        return null;
    }
startingIndex()
int com.runehive.content.achievement.AchievementWriter.startingIndex () protected
Reimplemented from com.runehive.content.writer.InterfaceWriter.
Definition at line 45 of file AchievementWriter.java.
{
        return 35051;
    }
text()
String[] com.runehive.content.achievement.AchievementWriter.text () protected
Reimplemented from com.runehive.content.writer.InterfaceWriter.
Definition at line 50 of file AchievementWriter.java.
{
        return null;
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/achievement/AchievementWriter.java