RuneHive-Game: com.runehive.content.skill.impl.farming.patches.FarmingPatch Class Reference
com.runehive.content.skill.impl.farming.patches.FarmingPatch Class Reference abstract
Public Member Functions
boolean clickObject (int opcode)
void fromJson (JsonObject object)
int getConfig ()
boolean isComposted ()
boolean isDead ()
boolean isDiseased ()
boolean isEmpty ()
boolean isGrowing ()
boolean isNormal ()
boolean isWatered ()
boolean itemOnObject (Item item, int index)
boolean needsWeeding ()
abstract Plant plantForSeed (int seedId)
void setDead ()
void setDiseased ()
void setEmpty ()
void setNormal ()
void setWatered ()
void tick ()
JsonObject toJson ()
boolean within (Position position)
Protected Member Functions
void onGrowth ()
void resetPatch ()
Protected Attributes
CompostType compost
boolean fullyGrown
int growth
Plant plant
final Player player
FarmingStage stage = FarmingStage.FULL_WEEDS
FarmingState state = FarmingState.NORMAL
final Stopwatch timer = Stopwatch.start()
final FarmingZone zone
Package Functions
FarmingPatch (Player player, FarmingZone zone, Interactable[] boundaries)
Private Member Functions
void clearPatch ()
Action< Player > createClearingAction (Player player, int animation, int delay)
void inspect ()
boolean plantSeed (int seedId, int slot)
boolean putCompost (int itemId, int slot)
void simulate (long elapsed)
Private Attributes
final Interactable[] boundaries
Static Private Attributes
static final double CLEARING_EXPERIENCE = 4
Detailed Description
Definition at line 25 of file FarmingPatch.java.
Constructor & Destructor Documentation
FarmingPatch()
com.runehive.content.skill.impl.farming.patches.FarmingPatch.FarmingPatch (Player player, FarmingZone zone, Interactable[] boundaries) package
Definition at line 43 of file FarmingPatch.java.
{
        this.player = player;
        this.zone = zone;
        this.boundaries = boundaries;
        resetPatch();
    }
References boundaries, player, resetPatch(), and zone.
Member Function Documentation
clearPatch()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.clearPatch () private
Definition at line 134 of file FarmingPatch.java.
{
        int animation, delay;
        if (isEmpty()) {
            player.dialogueFactory.sendStatement("This patch is already empty.").execute();
            return;
        }
        if (isGrowing()) {
            if (!player.inventory.contains(FarmingConstants.SPADE)) {
                player.dialogueFactory.sendStatement("You need a spade to clear this patch.").execute();
                return;
            }
            delay = 3;
            animation = FarmingConstants.SPADE_ANIM;
        } else {
            if (!player.inventory.contains(FarmingConstants.RAKE)) {
                player.dialogueFactory.sendStatement("You need a rake to clear this patch.").execute();
                return;
            }
            delay = 5;
            animation = FarmingConstants.RAKING_ANIM;
        }
        player.action.execute(createClearingAction(player, animation, delay));
    }
References createClearingAction(), isEmpty(), isGrowing(), player, com.runehive.content.skill.impl.farming.FarmingConstants.RAKE, com.runehive.content.skill.impl.farming.FarmingConstants.RAKING_ANIM, com.runehive.content.skill.impl.farming.FarmingConstants.SPADE, and com.runehive.content.skill.impl.farming.FarmingConstants.SPADE_ANIM.
Referenced by clickObject(), and itemOnObject().
clickObject()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.clickObject (int opcode)
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch, and com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 114 of file FarmingPatch.java.
{
        if (opcode == 1 && (needsWeeding() || isDead())) {
            clearPatch();
            return true;
        }
        if (opcode == 2) {
            inspect();
            return true;
        }
        return false;
    }
References clearPatch(), inspect(), isDead(), and needsWeeding().
createClearingAction()
Action< Player > com.runehive.content.skill.impl.farming.patches.FarmingPatch.createClearingAction (Player player, int animation, int delay) private
Definition at line 372 of file FarmingPatch.java.
{
        return new Action<Player>(player, delay) {
            @Override
            protected void onSchedule() {
                player.animate(animation);
            }
            @Override
            public void execute() {
                if (needsWeeding()) {
                    stage = stage.getNextStage();
                    player.inventory.add(6055, 1);
                } else {
                    setEmpty();
                }
                timer.reset();
                player.animate(animation);
                player.skills.addExperience(Skill.FARMING, CLEARING_EXPERIENCE * Config.FARMING_MODIFICATION);
                zone.sendPatchConfigs(player);
                if (isEmpty()) {
                    player.message("You clear the patch.");
                    resetPatch();
                    setEmpty();
                    cancel();
                }
            }
            @Override
            public void onCancel(boolean logut) {
                player.resetAnimation();
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
            @Override
            public String getName() {
                return "Farming Clear";
            }
        };
    }
References CLEARING_EXPERIENCE, com.runehive.game.world.entity.skill.Skill.FARMING, com.runehive.Config.FARMING_MODIFICATION, isEmpty(), needsWeeding(), com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, player, resetPatch(), setEmpty(), stage, timer, and zone.
Referenced by clearPatch().
fromJson()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.fromJson (JsonObject object)
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch, and com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 432 of file FarmingPatch.java.
{
        stage = FarmingStage.valueOf(object.get("stage").getAsString());
        state = FarmingState.valueOf(object.get("state").getAsString());
        compost = CompostType.valueOf(object.get("compost").getAsString());
        fullyGrown = object.get("fully-grown").getAsBoolean();
        growth = object.get("growth").getAsInt();
        if (object.has("plant")) {
            plant = plantForSeed(object.get("plant").getAsInt());
        }
        long cached = object.get("timer").getAsLong();
        simulate(TimeUnit.SECONDS.convert(System.nanoTime() - cached, TimeUnit.NANOSECONDS) / 12);
        timer.setCachedTime(cached);
    }
References compost, fullyGrown, growth, plant, plantForSeed(), simulate(), stage, state, and timer.
getConfig()
int com.runehive.content.skill.impl.farming.patches.FarmingPatch.getConfig ()
Definition at line 292 of file FarmingPatch.java.
{
        if (isEmpty() || needsWeeding()) {
            return stage.ordinal();
        }
        return (state.ordinal() << 6) | (plant.getStartingState() + growth);
    }
References growth, isEmpty(), needsWeeding(), plant, stage, and state.
inspect()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.inspect () private
Definition at line 236 of file FarmingPatch.java.
{
        if (isDiseased()) {
            player.dialogueFactory.sendStatement("This plant is diseased. Use a plant cure on it to cure it, ", "or clear the patch with a spade.").execute();
            return;
        } else if (isDead()) {
            player.dialogueFactory.sendStatement("This plant is dead. You did not cure it while it was diseased.", "Clear the patch with a spade.").execute();
            return;
        }
        String patch = getClass().getSimpleName().replace("Patch", "").toLowerCase();
        patch = Utility.getAOrAn(patch) + " " + patch;
        if (needsWeeding()) {
            player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has not been treated.", "The patches needs weeding.").execute();
        } else if (isWatered() && isEmpty()) {
            if (compost == CompostType.COMPOST) {
                player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has been treated with water", "and compost. The patches is empty and weeded.").execute();
            } else if (compost == CompostType.SUPERCOMPOST) {
                player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has been treated with water", "and supercompost. The patches is empty and weeded.").execute();
            } else if (compost == CompostType.ULTRACOMPOST) {
                player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has been treated with water", "and ultracompost. The patches is empty and weeded.").execute();
            } else {
                player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has been treated with water.", "The patches is empty and weeded.").execute();
            }
        } else if (isComposted() && isEmpty()) {
            if (compost == CompostType.COMPOST) {
                player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has been treated with compost.", "The patches is empty and weeded.").execute();
            } else if (compost == CompostType.SUPERCOMPOST) {
                player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has been treated with supercompost.", "The patches is empty and weeded.").execute();
            } else if (compost == CompostType.ULTRACOMPOST) {
                player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has been treated with ultracompost.", "The patches is empty and weeded.").execute();
            }
        } else if (isEmpty()) {
            player.dialogueFactory.sendStatement("This is " + patch + " patch. The soil has not been treated.", "The patches is empty and weeded.").execute();
        } else {
            player.locking.lock(5);
            player.message("You bend down and start to inspect the patch...");
            player.animate(1331);
            World.schedule(new Task(5) {
                @Override
                public void execute() {
                    int index = growth % plant.getInspectMessages().length;
                    if (growth > index) index = growth - index - 1;
                    player.dialogueFactory.sendStatement(plant.getInspectMessages()[index]).execute();
                    cancel();
                }
                @Override
                public void onCancel(boolean logout) {
                    player.animate(1332);
                }
            });
        }
    }
References com.runehive.content.skill.impl.farming.CompostType.COMPOST, compost, com.runehive.util.Utility.getAOrAn(), growth, isComposted(), isDead(), isDiseased(), isEmpty(), isWatered(), needsWeeding(), plant, player, com.runehive.game.world.World.schedule(), com.runehive.content.skill.impl.farming.CompostType.SUPERCOMPOST, and com.runehive.content.skill.impl.farming.CompostType.ULTRACOMPOST.
Referenced by clickObject().
isComposted()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.isComposted ()
Definition at line 356 of file FarmingPatch.java.
{
        return compost != CompostType.NONE;
    }
References compost, and com.runehive.content.skill.impl.farming.CompostType.NONE.
Referenced by inspect(), and putCompost().
isDead()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.isDead ()
Definition at line 344 of file FarmingPatch.java.
{
        return state.equals(FarmingState.DEAD);
    }
References com.runehive.content.skill.impl.farming.FarmingState.DEAD, and state.
Referenced by clickObject(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.clickObject(), inspect(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.onGrowth(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.protectsDisease(), simulate(), and tick().
isDiseased()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.isDiseased ()
Definition at line 340 of file FarmingPatch.java.
{
        return state.equals(FarmingState.DISEASED);
    }
References com.runehive.content.skill.impl.farming.FarmingState.DISEASED, and state.
Referenced by com.runehive.content.skill.impl.farming.patches.DiseasablePatch.clickObject(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.curePlant(), and inspect().
isEmpty()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.isEmpty ()
Definition at line 348 of file FarmingPatch.java.
{
        return stage.equals(FarmingStage.EMPTY) && plant == null;
    }
References com.runehive.content.skill.impl.farming.FarmingStage.EMPTY, plant, and stage.
Referenced by clearPatch(), createClearingAction(), getConfig(), inspect(), isGrowing(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.plantScareCrow(), and plantSeed().
isGrowing()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.isGrowing ()
Definition at line 352 of file FarmingPatch.java.
{
        return !isEmpty() && !needsWeeding();
    }
References isEmpty(), and needsWeeding().
Referenced by clearPatch(), and com.runehive.content.skill.impl.farming.patches.WaterablePatch.waterPatch().
isNormal()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.isNormal ()
Definition at line 332 of file FarmingPatch.java.
{
        return state.equals(FarmingState.NORMAL);
    }
References com.runehive.content.skill.impl.farming.FarmingState.NORMAL, and state.
isWatered()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.isWatered ()
Definition at line 336 of file FarmingPatch.java.
{
        return state.equals(FarmingState.WATERED);
    }
References state, and com.runehive.content.skill.impl.farming.FarmingState.WATERED.
Referenced by inspect(), com.runehive.content.skill.impl.farming.patches.WaterablePatch.onGrowth(), and com.runehive.content.skill.impl.farming.patches.WaterablePatch.waterPatch().
itemOnObject()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.itemOnObject (Item item, int index)
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch, com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch, and com.runehive.content.skill.impl.farming.patches.WaterablePatch.
Definition at line 126 of file FarmingPatch.java.
{
        if (item.matchesId(FarmingConstants.RAKE) || item.matchesId(FarmingConstants.SPADE)) {
            clearPatch();
            return true;
        }
        return putCompost(item.getId(), index) || plantSeed(item.getId(), index);
    }
References clearPatch(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.matchesId(), plantSeed(), putCompost(), com.runehive.content.skill.impl.farming.FarmingConstants.RAKE, and com.runehive.content.skill.impl.farming.FarmingConstants.SPADE.
needsWeeding()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.needsWeeding ()
Definition at line 360 of file FarmingPatch.java.
{
        return stage.equals(FarmingStage.FULL_WEEDS) || stage.equals(FarmingStage.ONE_THIRD_WEEDS) || stage.equals(FarmingStage.TWO_THIRDS_WEEDS);
    }
References com.runehive.content.skill.impl.farming.FarmingStage.FULL_WEEDS, com.runehive.content.skill.impl.farming.FarmingStage.ONE_THIRD_WEEDS, stage, and com.runehive.content.skill.impl.farming.FarmingStage.TWO_THIRDS_WEEDS.
Referenced by clickObject(), createClearingAction(), getConfig(), inspect(), isGrowing(), and putCompost().
onGrowth()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.onGrowth () protected
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch, and com.runehive.content.skill.impl.farming.patches.WaterablePatch.
Definition at line 112 of file FarmingPatch.java.
{}
Referenced by simulate(), and tick().
plantForSeed()
abstract Plant com.runehive.content.skill.impl.farming.patches.FarmingPatch.plantForSeed (int seedId) abstract
Reimplemented in com.runehive.content.skill.impl.farming.patches.impl.AllotmentPatch, com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch, and com.runehive.content.skill.impl.farming.patches.impl.HerbPatch.
Referenced by fromJson(), and plantSeed().
plantSeed()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.plantSeed (int seedId, int slot) private
Definition at line 163 of file FarmingPatch.java.
{
        if (player.locking.locked()) {
            return false;
        }
        Plant toPlant = plantForSeed(seedId);
        if (toPlant == null) {
            return false;
        }
        if (!isEmpty()) {
            player.message("You can't plant a seed here.");
            return false;
        }
        if (toPlant.getLevelRequired() > player.skills.getLevel(Skill.FARMING)) {
            player.dialogueFactory.sendStatement("You need a farming level of " + toPlant.getLevelRequired() + " to plant this seed.").execute();
            return true;
        }
        if (!player.inventory.contains(FarmingConstants.SEED_DIBBER)) {
            player.dialogueFactory.sendStatement("You need a seed dibber to plant seeds here.").execute();
            return true;
        }
        if (!player.inventory.contains(toPlant.getSeedId(), toPlant.getSeedAmount())) {
            player.dialogueFactory.sendStatement("You need at least " + toPlant.getSeedAmount() + " seeds to plant here.").execute();
            return true;
        }
        plant = toPlant;
        setNormal();
        timer.reset();
        player.locking.lock(3 * 3 / 5);
        player.animate(FarmingConstants.SEED_DIBBING);
        player.inventory.remove(new Item(seedId, toPlant.getSeedAmount()), slot, true);
        World.schedule(3, () -> {
            player.resetAnimation();
            player.skills.addExperience(Skill.FARMING, plant.getPlantingXp() * Config.FARMING_MODIFICATION);
            zone.sendPatchConfigs(player);
        });
        return true;
    }
References com.runehive.game.world.entity.skill.Skill.FARMING, com.runehive.Config.FARMING_MODIFICATION, com.runehive.content.skill.impl.farming.plants.Plant.getLevelRequired(), com.runehive.content.skill.impl.farming.plants.Plant.getSeedAmount(), com.runehive.content.skill.impl.farming.plants.Plant.getSeedId(), isEmpty(), plant, plantForSeed(), player, com.runehive.game.world.World.schedule(), com.runehive.content.skill.impl.farming.FarmingConstants.SEED_DIBBER, com.runehive.content.skill.impl.farming.FarmingConstants.SEED_DIBBING, setNormal(), timer, and zone.
Referenced by itemOnObject().
putCompost()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.putCompost (int itemId, int slot) private
Definition at line 210 of file FarmingPatch.java.
{
        if (player.locking.locked()) {
            return false;
        }
        CompostType type = CompostType.forItem(itemId);
        if (type == CompostType.NONE) {
            return false;
        }
        if (needsWeeding() || isComposted()) {
            player.message("This patch doesn't need compost.");
            return true;
        }
        player.locking.lock(7 * 3 / 5);
        player.animate(FarmingConstants.PUTTING_COMPOST);
        player.inventory.replace(itemId, FarmingConstants.BUCKET, slot, true);
        player.message("You pour some " + type.name().toLowerCase() + " on the patch.");
        player.skills.addExperience(Skill.FARMING, type.getExp() * Config.FARMING_MODIFICATION);
        compost = type;
        return true;
    }
References com.runehive.content.skill.impl.farming.FarmingConstants.BUCKET, compost, com.runehive.game.world.entity.skill.Skill.FARMING, com.runehive.Config.FARMING_MODIFICATION, com.runehive.content.skill.impl.farming.CompostType.forItem(), com.runehive.content.skill.impl.farming.CompostType.getExp(), isComposted(), needsWeeding(), com.runehive.content.skill.impl.farming.CompostType.NONE, player, and com.runehive.content.skill.impl.farming.FarmingConstants.PUTTING_COMPOST.
Referenced by itemOnObject().
resetPatch()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.resetPatch () protected
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch, and com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 299 of file FarmingPatch.java.
{
        plant = null;
        state = FarmingState.NORMAL;
        stage = FarmingStage.FULL_WEEDS;
        compost = CompostType.NONE;
        growth = 0;
        fullyGrown = false;
        timer.reset();
    }
References compost, com.runehive.content.skill.impl.farming.FarmingStage.FULL_WEEDS, fullyGrown, growth, com.runehive.content.skill.impl.farming.CompostType.NONE, com.runehive.content.skill.impl.farming.FarmingState.NORMAL, plant, stage, state, and timer.
Referenced by createClearingAction(), and FarmingPatch().
setDead()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.setDead ()
Definition at line 323 of file FarmingPatch.java.
{
        state = FarmingState.DEAD;
    }
References com.runehive.content.skill.impl.farming.FarmingState.DEAD, and state.
Referenced by com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.protectsDisease().
setDiseased()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.setDiseased ()
Definition at line 319 of file FarmingPatch.java.
{
        state = FarmingState.DISEASED;
    }
References com.runehive.content.skill.impl.farming.FarmingState.DISEASED, and state.
setEmpty()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.setEmpty ()
Definition at line 327 of file FarmingPatch.java.
{
        plant = null;
        stage = FarmingStage.EMPTY;
    }
References com.runehive.content.skill.impl.farming.FarmingStage.EMPTY, plant, and stage.
Referenced by createClearingAction().
setNormal()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.setNormal ()
Definition at line 311 of file FarmingPatch.java.
{
        state = FarmingState.NORMAL;
    }
References com.runehive.content.skill.impl.farming.FarmingState.NORMAL, and state.
Referenced by com.runehive.content.skill.impl.farming.patches.DiseasablePatch.curePlant(), com.runehive.content.skill.impl.farming.patches.WaterablePatch.onGrowth(), and plantSeed().
setWatered()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.setWatered ()
Definition at line 315 of file FarmingPatch.java.
{
        state = FarmingState.WATERED;
    }
References state, and com.runehive.content.skill.impl.farming.FarmingState.WATERED.
Referenced by com.runehive.content.skill.impl.farming.patches.WaterablePatch.waterPatch().
simulate()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.simulate (long elapsed) private
Definition at line 84 of file FarmingPatch.java.
{
        /* nothing is growing on this patch */
        if (plant == null || isDead()) {
            return;
        }
        int growthStates = plant.getEndingState() - plant.getStartingState();
        int growthTime = plant.getGrowthTime();
        if (elapsed > growthTime) {
            elapsed = growthTime;
        }
        int completed = (int) (growthStates * elapsed / growthTime);
        for (int i = growth; i <= completed; i++) {
            fullyGrown = i == growthStates;
            onGrowth();
            if (isDead()) {
                return;
            }
            growth = i;
        }
    }
References fullyGrown, growth, isDead(), onGrowth(), and plant.
Referenced by fromJson().
tick()
void com.runehive.content.skill.impl.farming.patches.FarmingPatch.tick ()
Definition at line 50 of file FarmingPatch.java.
                       {
        /* if the patch is empty, grow back the weeds */
        if (!stage.equals(FarmingStage.FULL_WEEDS) && plant == null && timer.elapsed(5, TimeUnit.MINUTES)) {
            stage = stage.getPreviousStage();
            zone.sendPatchConfigs(player);
            timer.reset();
        }
        /* nothing is growing on this patch */
        if (plant == null) {
            return;
        }
        int elapsed = (int) timer.elapsedTime(TimeUnit.SECONDS) / 12;
        int growthStates = plant.getEndingState() - plant.getStartingState();
        int growthTime = plant.getGrowthTime();
        if (elapsed > growthTime) {
            elapsed = growthTime;
        }
        int completed = growthStates * elapsed / growthTime;
        if (growth != completed) {
            fullyGrown = completed == growthStates;
            onGrowth();
            if (!isDead()) {
                growth = completed;
            }
            zone.sendPatchConfigs(player);
        }
    }
References com.runehive.content.skill.impl.farming.FarmingStage.FULL_WEEDS, fullyGrown, growth, isDead(), onGrowth(), plant, player, stage, timer, and zone.
toJson()
JsonObject com.runehive.content.skill.impl.farming.patches.FarmingPatch.toJson ()
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch, and com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 418 of file FarmingPatch.java.
{
        JsonObject object = new JsonObject();
        object.addProperty("stage", stage.name());
        object.addProperty("state", state.name());
        object.addProperty("compost", compost.name());
        object.addProperty("timer", timer.getCachedTime());
        object.addProperty("fully-grown", fullyGrown);
        object.addProperty("growth", growth);
        if (plant != null) {
            object.addProperty("plant", plant.getSeedId());
        }
        return object;
    }
References compost, fullyGrown, growth, plant, stage, state, and timer.
within()
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.within (Position position)
Definition at line 364 of file FarmingPatch.java.
{
        for (Interactable boundary : boundaries) {
            if (Utility.inside(boundary, position))
                return true;
        }
        return false;
    }
References boundaries, and com.runehive.util.Utility.inside().
Member Data Documentation
boundaries
final Interactable [] com.runehive.content.skill.impl.farming.patches.FarmingPatch.boundaries private
Definition at line 40 of file FarmingPatch.java.
Referenced by com.runehive.content.skill.impl.farming.patches.impl.AllotmentPatch.AllotmentPatch(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.DiseasablePatch(), FarmingPatch(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.FlowerPatch(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.HarvestablePatch(), com.runehive.content.skill.impl.farming.patches.impl.HerbPatch.HerbPatch(), com.runehive.content.skill.impl.farming.patches.WaterablePatch.WaterablePatch(), and within().
CLEARING_EXPERIENCE
final double com.runehive.content.skill.impl.farming.patches.FarmingPatch.CLEARING_EXPERIENCE = 4 static private
Definition at line 26 of file FarmingPatch.java.
Referenced by createClearingAction().
compost
CompostType com.runehive.content.skill.impl.farming.patches.FarmingPatch.compost protected
Definition at line 36 of file FarmingPatch.java.
Referenced by fromJson(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.harvest(), inspect(), isComposted(), putCompost(), resetPatch(), and toJson().
fullyGrown
boolean com.runehive.content.skill.impl.farming.patches.FarmingPatch.fullyGrown protected
Definition at line 35 of file FarmingPatch.java.
Referenced by com.runehive.content.skill.impl.farming.patches.HarvestablePatch.clickObject(), fromJson(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.protectsDisease(), resetPatch(), simulate(), tick(), toJson(), and com.runehive.content.skill.impl.farming.patches.WaterablePatch.waterPatch().
growth
int com.runehive.content.skill.impl.farming.patches.FarmingPatch.growth protected
Definition at line 33 of file FarmingPatch.java.
Referenced by fromJson(), getConfig(), inspect(), resetPatch(), simulate(), tick(), and toJson().
plant
Plant com.runehive.content.skill.impl.farming.patches.FarmingPatch.plant protected
Definition at line 28 of file FarmingPatch.java.
Referenced by com.runehive.content.skill.impl.farming.patches.HarvestablePatch.createHarvestAction(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.curePlant(), fromJson(), getConfig(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.harvest(), inspect(), isEmpty(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.plantScareCrow(), plantSeed(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.protectsDisease(), resetPatch(), setEmpty(), simulate(), tick(), and toJson().
player
final Player com.runehive.content.skill.impl.farming.patches.FarmingPatch.player protected
Definition at line 38 of file FarmingPatch.java.
Referenced by com.runehive.content.skill.impl.farming.patches.impl.AllotmentPatch.AllotmentPatch(), clearPatch(), createClearingAction(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.createHarvestAction(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.curePlant(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.DiseasablePatch(), FarmingPatch(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.FlowerPatch(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.harvest(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.HarvestablePatch(), com.runehive.content.skill.impl.farming.patches.impl.HerbPatch.HerbPatch(), inspect(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.plantScareCrow(), plantSeed(), putCompost(), tick(), com.runehive.content.skill.impl.farming.patches.WaterablePatch.WaterablePatch(), and com.runehive.content.skill.impl.farming.patches.WaterablePatch.waterPatch().
stage
FarmingStage com.runehive.content.skill.impl.farming.patches.FarmingPatch.stage = FarmingStage.FULL_WEEDS protected
Definition at line 30 of file FarmingPatch.java.
Referenced by createClearingAction(), fromJson(), getConfig(), isEmpty(), needsWeeding(), resetPatch(), setEmpty(), tick(), and toJson().
state
FarmingState com.runehive.content.skill.impl.farming.patches.FarmingPatch.state = FarmingState.NORMAL protected
Definition at line 31 of file FarmingPatch.java.
Referenced by fromJson(), getConfig(), isDead(), isDiseased(), isNormal(), isWatered(), resetPatch(), setDead(), setDiseased(), setNormal(), setWatered(), and toJson().
timer
final Stopwatch com.runehive.content.skill.impl.farming.patches.FarmingPatch.timer = Stopwatch.start() protected
Definition at line 41 of file FarmingPatch.java.
Referenced by createClearingAction(), fromJson(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.plantScareCrow(), plantSeed(), resetPatch(), tick(), and toJson().
zone
final FarmingZone com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone protected
Definition at line 39 of file FarmingPatch.java.
Referenced by com.runehive.content.skill.impl.farming.patches.impl.AllotmentPatch.AllotmentPatch(), createClearingAction(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.createHarvestAction(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.curePlant(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.DiseasablePatch(), FarmingPatch(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.FlowerPatch(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.HarvestablePatch(), com.runehive.content.skill.impl.farming.patches.impl.HerbPatch.HerbPatch(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.plantScareCrow(), plantSeed(), tick(), com.runehive.content.skill.impl.farming.patches.WaterablePatch.WaterablePatch(), and com.runehive.content.skill.impl.farming.patches.WaterablePatch.waterPatch().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/farming/patches/FarmingPatch.java