RuneHive-Game: com.runehive.content.itemaction.ItemAction Class Reference
com.runehive.content.itemaction.ItemAction Class Reference abstract
Handles executing an item action.
Public Member Functions
int delay ()
The item click delay of the action.
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String message (Item item)
The message of the action.
abstract String name ()
The name of the action.
String toString ()
Detailed Description
Handles executing an item action.
Author
Daniel
Definition at line 11 of file ItemAction.java.
Member Function Documentation
delay()
int com.runehive.content.itemaction.ItemAction.delay ()
The item click delay of the action.
Reimplemented in com.runehive.content.itemaction.impl.DrillDemonBox.
Definition at line 22 of file ItemAction.java.
                       {
        return -1;
    }
drop()
boolean com.runehive.content.itemaction.ItemAction.drop (Player player, Item item)
Reimplemented in com.runehive.content.itemaction.impl.CelestialRing, com.runehive.content.itemaction.impl.CrawsBow, com.runehive.content.itemaction.impl.MagmaHelm, com.runehive.content.itemaction.impl.SerpentineHelm, com.runehive.content.itemaction.impl.TanzaniteHelm, com.runehive.content.itemaction.impl.ThammaronsSceptre, com.runehive.content.itemaction.impl.ToxicBlowpipe, and com.runehive.content.itemaction.impl.ViggorasChainmace.
Definition at line 39 of file ItemAction.java.
{
        return false;
    }
Referenced by com.runehive.content.itemaction.ItemActionRepository.drop().
equipment()
boolean com.runehive.content.itemaction.ItemAction.equipment (Player player, Item item, int opcode)
Reimplemented in com.runehive.content.itemaction.impl.CelestialRing, com.runehive.content.itemaction.impl.CrawsBow, com.runehive.content.itemaction.impl.DragonfireShield, com.runehive.content.itemaction.impl.MagmaHelm, com.runehive.content.itemaction.impl.SerpentineHelm, com.runehive.content.itemaction.impl.TanzaniteHelm, com.runehive.content.itemaction.impl.ThammaronsSceptre, com.runehive.content.itemaction.impl.ToxicBlowpipe, com.runehive.content.itemaction.impl.TridentOfTheSeas, com.runehive.content.itemaction.impl.TridentOfTheSwamp, and com.runehive.content.itemaction.impl.ViggorasChainmace.
Definition at line 31 of file ItemAction.java.
{
        return false;
    }
Referenced by com.runehive.content.itemaction.ItemActionRepository.equipment().
inventory()
boolean com.runehive.content.itemaction.ItemAction.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented in com.runehive.content.itemaction.impl.CelestialRing, com.runehive.content.itemaction.impl.ClanResourceBox, com.runehive.content.itemaction.impl.ClanShowcaseBox, com.runehive.content.itemaction.impl.CrawsBow, com.runehive.content.itemaction.impl.DragonfireShield, com.runehive.content.itemaction.impl.DrillDemonBox, com.runehive.content.itemaction.impl.MagmaHelm, com.runehive.content.itemaction.impl.MimeBox, com.runehive.content.itemaction.impl.SerpentineHelm, com.runehive.content.itemaction.impl.TanzaniteHelm, com.runehive.content.itemaction.impl.ThammaronsSceptre, com.runehive.content.itemaction.impl.ToxicBlowpipe, com.runehive.content.itemaction.impl.TridentOfTheSeas, com.runehive.content.itemaction.impl.TridentOfTheSwamp, and com.runehive.content.itemaction.impl.ViggorasChainmace.
Definition at line 27 of file ItemAction.java.
{
        return false;
    }
Referenced by com.runehive.content.itemaction.ItemActionRepository.inventory().
itemOnItem()
boolean com.runehive.content.itemaction.ItemAction.itemOnItem (Player player, Item first, Item second)
Reimplemented in com.runehive.content.itemaction.impl.CelestialRing, com.runehive.content.itemaction.impl.CrawsBow, com.runehive.content.itemaction.impl.MagmaHelm, com.runehive.content.itemaction.impl.SerpentineHelm, com.runehive.content.itemaction.impl.TanzaniteHelm, com.runehive.content.itemaction.impl.ThammaronsSceptre, com.runehive.content.itemaction.impl.ToxicBlowpipe, com.runehive.content.itemaction.impl.TridentOfTheSeas, com.runehive.content.itemaction.impl.TridentOfTheSwamp, and com.runehive.content.itemaction.impl.ViggorasChainmace.
Definition at line 35 of file ItemAction.java.
{
        return false;
    }
Referenced by com.runehive.content.itemaction.ItemActionRepository.itemOnItem().
message()
String com.runehive.content.itemaction.ItemAction.message (Item item)
The message of the action.
Reimplemented in com.runehive.content.itemaction.impl.DrillDemonBox.
Definition at line 17 of file ItemAction.java.
{
        return "";
    }
name()
abstract String com.runehive.content.itemaction.ItemAction.name () abstract
The name of the action.
Reimplemented in com.runehive.content.itemaction.impl.CelestialRing, com.runehive.content.itemaction.impl.ClanResourceBox, com.runehive.content.itemaction.impl.ClanShowcaseBox, com.runehive.content.itemaction.impl.CrawsBow, com.runehive.content.itemaction.impl.DragonfireShield, com.runehive.content.itemaction.impl.DrillDemonBox, com.runehive.content.itemaction.impl.MagmaHelm, com.runehive.content.itemaction.impl.MimeBox, com.runehive.content.itemaction.impl.SerpentineHelm, com.runehive.content.itemaction.impl.TanzaniteHelm, com.runehive.content.itemaction.impl.ThammaronsSceptre, com.runehive.content.itemaction.impl.ToxicBlowpipe, com.runehive.content.itemaction.impl.TridentOfTheSeas, com.runehive.content.itemaction.impl.TridentOfTheSwamp, and com.runehive.content.itemaction.impl.ViggorasChainmace.
Referenced by toString().
toString()
String com.runehive.content.itemaction.ItemAction.toString ()
Definition at line 44 of file ItemAction.java.
{
        return String.format("Action=%s", name());
    }
References name().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/ItemAction.java