RuneHive-Game: com.runehive.game.world.entity.mob.player.requests.RequestManager Class Reference
com.runehive.game.world.entity.mob.player.requests.RequestManager Class Reference
The request manager manages.
Public Member Functions
void close ()
Called when an itemcontainer is closed.
boolean request (Player other, RequestType type)
Sends another player a request.
RequestManager (Player player)
Creates the request manager.
Private Member Functions
boolean mutualRequest (RequestManager otherManager)
Checks if a request is mutual between two players.
void reset ()
Resets the variables for a request.
boolean validate (Player entity)
Performs a check to validate a player for a request.
Private Attributes
Player acquaintance
The current 'acquaintance'.
Player player
The player.
RequestType requestType
The current request type.
RequestState state = RequestState.NORMAL
The current state.
Detailed Description
The request manager manages.
Author
Graham Edgecombe
Definition at line 13 of file RequestManager.java.
Constructor & Destructor Documentation
RequestManager()
com.runehive.game.world.entity.mob.player.requests.RequestManager.RequestManager (Player player)
Creates the request manager.
Parameters
player The player whose requests the manager is managing.
Definition at line 33 of file RequestManager.java.
{
        this.player = player;
    }
References player.
Referenced by mutualRequest(), and request().
Member Function Documentation
close()
void com.runehive.game.world.entity.mob.player.requests.RequestManager.close ()
Called when an itemcontainer is closed.
Definition at line 108 of file RequestManager.java.
{
        reset();
    }
References reset().
mutualRequest()
boolean com.runehive.game.world.entity.mob.player.requests.RequestManager.mutualRequest (RequestManager otherManager) private
Checks if a request is mutual between two players.
Parameters
otherManager The other player's {@codeplain RequestManager}.
Returns
True if the request was mutual
Definition at line 93 of file RequestManager.java.
{
        boolean otherRequested = otherManager.state == RequestState.REQUESTED;
        boolean sameRequestType = requestType == otherManager.requestType;
        boolean mutualAcquantances = player.equals(otherManager.acquaintance);
        return otherRequested && sameRequestType && mutualAcquantances;
    }
References acquaintance, player, com.runehive.game.world.entity.mob.player.requests.RequestState.REQUESTED, RequestManager(), and requestType.
Referenced by request().
request()
boolean com.runehive.game.world.entity.mob.player.requests.RequestManager.request (Player other, RequestType type)
Sends another player a request.
Parameters
other The other player to request.
type The request type.
Returns
True if the request was mutual
Definition at line 46 of file RequestManager.java.
{
        if (!validate(player) || !validate(other)) {
            return false;
        }
        if (!Utility.withinDistance(other, player, Region.VIEW_DISTANCE)) {
            player.send(new SendMessage("Unable to find " + Utility.formatName(other.getName()) + "."));
            return false;
        }
        RequestManager otherManager = other.requestManager;
        if (state == RequestState.PARTICIPATING || otherManager.state == RequestState.PARTICIPATING) {
            return false;
        }
        requestType = type;
        acquaintance = other;
        state = RequestState.REQUESTED;
        if (mutualRequest(otherManager)) {
            state = RequestState.PARTICIPATING;
            otherManager.state = RequestState.PARTICIPATING;
            return true;
        }
        return false;
    }
References acquaintance, com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.player.Player.getName(), mutualRequest(), com.runehive.game.world.entity.mob.player.requests.RequestState.PARTICIPATING, player, com.runehive.game.world.entity.mob.player.requests.RequestState.REQUESTED, RequestManager(), com.runehive.game.world.entity.mob.player.Player.requestManager, requestType, state, validate(), com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinDistance().
reset()
void com.runehive.game.world.entity.mob.player.requests.RequestManager.reset () private
Resets the variables for a request.
Definition at line 101 of file RequestManager.java.
{
        requestType = null;
        acquaintance = null;
        state = RequestState.NORMAL;
    }
References acquaintance, com.runehive.game.world.entity.mob.player.requests.RequestState.NORMAL, requestType, and state.
Referenced by close().
validate()
boolean com.runehive.game.world.entity.mob.player.requests.RequestManager.validate (Player entity) private
Performs a check to validate a player for a request.
Parameters
entity The player to validate.
Returns
True if the player is valid
Definition at line 82 of file RequestManager.java.
{
        return entity != null && !entity.positionChange;
    }
Referenced by request().
Member Data Documentation
acquaintance
Player com.runehive.game.world.entity.mob.player.requests.RequestManager.acquaintance private
The current 'acquaintance'.
Definition at line 25 of file RequestManager.java.
Referenced by mutualRequest(), request(), and reset().
player
Player com.runehive.game.world.entity.mob.player.requests.RequestManager.player private
The player.
Definition at line 16 of file RequestManager.java.
Referenced by mutualRequest(), request(), and RequestManager().
requestType
RequestType com.runehive.game.world.entity.mob.player.requests.RequestManager.requestType private
The current request type.
Definition at line 22 of file RequestManager.java.
Referenced by mutualRequest(), request(), and reset().
state
RequestState com.runehive.game.world.entity.mob.player.requests.RequestManager.state = RequestState.NORMAL private
The current state.
Definition at line 19 of file RequestManager.java.
Referenced by request(), and reset().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/requests/RequestManager.java