RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Spinning Class Reference
com.runehive.content.skill.impl.crafting.impl.Spinning Class Reference
Handles spinning items on the spinning wheel.
Classes
enum Spinnable
The spinnable data.
Static Public Member Functions
static void click (Player player, Spinnable spinnable)
Opens the spinnable dialogue.
static void open (Player player)
Handles opening the spinning dialogue.
Static Private Member Functions
static Action< Player > spin (Player player, Spinnable spinnable, int amount)
The spinnable action.
Detailed Description
Handles spinning items on the spinning wheel.
Author
Daniel
Definition at line 21 of file Spinning.java.
Member Function Documentation
click()
void com.runehive.content.skill.impl.crafting.impl.Spinning.click (Player player, Spinnable spinnable) static
Opens the spinnable dialogue.
Parameters
player The player instance.
spinnable The spinnable data.
Definition at line 99 of file Spinning.java.
{
        player.dialogueFactory.clear();
        if (player.skills.getMaxLevel(Skill.CRAFTING) < spinnable.requiredLevel) {
            player.dialogueFactory.sendStatement("You need a crafting level of " + spinnable.requiredLevel + " to spin this!").execute();
            return;
        }
        if (!player.inventory.contains(spinnable.item)) {
            player.dialogueFactory.sendStatement("You do not have the required items to do this!").execute();
            return;
        }
        ChatBoxItemDialogue.sendInterface(player, 1746, spinnable.item, 170);
        player.chatBoxItemDialogue = new ChatBoxItemDialogue(player) {
            @Override
            public void firstOption(Player player) {
                player.action.execute(spin(player, spinnable, 1), true);
            }
            @Override
            public void secondOption(Player player) {
                player.action.execute(spin(player, spinnable, 5), true);
            }
            @Override
            public void thirdOption(Player player) {
                player.send(new SendInputAmount("Enter amount", 2, input -> player.action.execute(spin(player, spinnable, Integer.parseInt(input)), true)));
            }
            @Override
            public void fourthOption(Player player) {
                player.action.execute(spin(player, spinnable, 28), true);
            }
        };
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.content.dialogue.DialogueFactory.clear(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.crafting.impl.Spinning.Spinnable.item, com.runehive.content.skill.impl.crafting.impl.Spinning.Spinnable.requiredLevel, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.ChatBoxItemDialogue.sendInterface(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.game.world.entity.mob.Mob.skills, and spin().
Referenced by open().
open()
void com.runehive.content.skill.impl.crafting.impl.Spinning.open (Player player) static
Handles opening the spinning dialogue.
Parameters
player The player instance.
Definition at line 74 of file Spinning.java.
{
        DialogueFactory factory = player.dialogueFactory;
        factory.sendOption("Ball of wool (wool)", () -> {
            factory.onAction(() -> {
                click(player, Spinnable.WOOL);
            });
        }, "Bow string (flax)", () -> {
            factory.onAction(() -> {
                click(player, Spinnable.BOWSTRING);
            });
        }, "Rope (yak hair)", () -> {
            factory.onAction(() -> {
                click(player, Spinnable.ROPE);
            });
        }, "Nevermind", () -> {
            player.interfaceManager.close();
        }).execute();
    }
References com.runehive.content.skill.impl.crafting.impl.Spinning.Spinnable.BOWSTRING, click(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.content.skill.impl.crafting.impl.Spinning.Spinnable.ROPE, com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.skill.impl.crafting.impl.Spinning.Spinnable.WOOL.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.clickObject().
spin()
Action< Player > com.runehive.content.skill.impl.crafting.impl.Spinning.spin (Player player, Spinnable spinnable, int amount) static private
The spinnable action.
Parameters
player The player instance.
spinnable The spinnable data.
amount The amount beeing spun.
Returns
The spinnable action.
Definition at line 144 of file Spinning.java.
{
        return new Action<Player>(player, 2, true) {
            int ticks = 0;
            @Override
            public void execute() {
                if (!player.inventory.contains(spinnable.item)) {
                    cancel();
                    player.send(new SendMessage("<col=369>You have run out of materials."));
                    return;
                }
                player.animate(new Animation(896));
                player.inventory.remove(spinnable.item);
                player.inventory.add(spinnable.outcome);
                player.skills.addExperience(Skill.CRAFTING, spinnable.experience * Config.CRAFTING_MODIFICATION);
                player.send(new SendMessage("You spin the " + spinnable.item.getName() + " into " + Utility.getAOrAn(spinnable.outcome.getName()) + " " + spinnable.outcome.getName() + "."));
                if (++ticks == amount) {
                    cancel();
                    return;
                }
            }
            @Override
            public String getName() {
                return "Spinning";
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
        };
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.Config.CRAFTING_MODIFICATION, com.runehive.content.skill.impl.crafting.impl.Spinning.Spinnable.experience, com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.crafting.impl.Spinning.Spinnable.item, com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, com.runehive.content.skill.impl.crafting.impl.Spinning.Spinnable.outcome, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by click().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Spinning.java