RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener Class Reference
com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener Class Reference
no more bugs
Public Member Functions
void block (Mob attacker, Player defender, Hit hit, CombatType combatType)
void finishIncoming (Mob attacker, Player defender)
void preKill (Mob attacker, Mob defender, Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
boolean canAttack (T attacker, Mob defender)
boolean canOtherAttack (Mob attacker, T defender)
void finishIncoming (Mob attacker, T defender)
void finishOutgoing (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
void hitsplat (T attacker, Mob defender, Hit hit)
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
void onKill (T attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, T defender, Hit hit)
void start (T attacker, Mob defender, Hit[] hits)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Static Public Member Functions
static VengeanceListener get ()
Private Member Functions
VengeanceListener ()
Static Private Attributes
static final VengeanceListener INSTANCE = new VengeanceListener()
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
static final CombatListener< Mob > CANT_ATTACK
Detailed Description
no more bugs
Definition at line 11 of file VengeanceListener.java.
Constructor & Destructor Documentation
VengeanceListener()
com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.VengeanceListener () private
Definition at line 15 of file VengeanceListener.java.
{
    }
Referenced by get().
Member Function Documentation
block()
void com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.block (Mob attacker, Player defender, Hit hit, CombatType combatType)
Definition at line 19 of file VengeanceListener.java.
{
        if (hit.getDamage() < 2) {
            return;
        }
        Hit recoil = new Hit((int) (hit.getDamage() * 0.75), HitIcon.DEFLECT);
        attacker.damage(recoil);
        attacker.getCombat().getDamageCache().add(defender, recoil);
        defender.speak("Taste vengeance!");
        defender.venged = false;
    }
References com.runehive.game.world.entity.mob.Mob.damage(), com.runehive.game.world.entity.combat.hit.HitIcon.DEFLECT, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.hit(), and com.runehive.game.world.entity.mob.Mob.speak().
finishIncoming()
void com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.finishIncoming (Mob attacker, Player defender)
Definition at line 50 of file VengeanceListener.java.
{
        if (!defender.venged) {
            defender.getCombat().removeListener(this);
        }
    }
References com.runehive.game.world.entity.mob.player.Player.getCombat(), and com.runehive.game.world.entity.mob.player.Player.venged.
get()
VengeanceListener com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.get () static
Definition at line 56 of file VengeanceListener.java.
{
        return INSTANCE;
    }
References INSTANCE, and VengeanceListener().
Referenced by com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.restore().
preKill()
void com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill (Mob attacker, Mob defender, Hit hit)
Reimplemented from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.
Definition at line 32 of file VengeanceListener.java.
{
        if (!defender.isPlayer()) {
            return;
        }
        if (hit.getDamage() < 2) {
            return;
        }
        Hit recoil = new Hit((int) (hit.getDamage() * 0.75), HitIcon.DEFLECT);
        attacker.damage(recoil);
        attacker.getCombat().getDamageCache().add(defender, recoil);
        defender.speak("Taste vengeance!");
        defender.getPlayer().venged = false;
    }
References com.runehive.game.world.entity.mob.Mob.damage(), com.runehive.game.world.entity.combat.hit.HitIcon.DEFLECT, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.hit(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.Mob.speak(), and com.runehive.game.world.entity.mob.player.Player.venged.
Member Data Documentation
INSTANCE
final VengeanceListener com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.INSTANCE = new VengeanceListener() static private
Definition at line 13 of file VengeanceListener.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/other/VengeanceListener.java