RuneHive-Game: com.runehive.content.combat.Skulling Class Reference
com.runehive.content.combat.Skulling Class Reference
Handles the skulling class.
Public Member Functions
void checkForSkulling (Player opponent)
Checks if player requires a skull upon attacking another player.
SkullHeadIconType getHeadIconType ()
Gets the skull icon.
SkullRemoveTask getSkullRemoveTask ()
boolean isSkulled ()
void skull ()
void skull (Player attacking, SkullHeadIconType icon)
Skulls the player and deposit's the attacked player into the list.
void skull (SkullHeadIconType icon)
Skulling (Player player)
Constructs a new Skulling class.
void unskull ()
Unskulls the player.
Private Attributes
final List< String > attacked = new LinkedList<>()
All the other player's this entity has attacked.
SkullHeadIconType icon = SkullHeadIconType.NO_SKULL
Their skull icon identification.
Player player
The player of this class.
SkullRemoveTask skullRemoveTask
Detailed Description
Handles the skulling class.
Author
Daniel
Definition at line 18 of file Skulling.java.
Constructor & Destructor Documentation
Skulling()
com.runehive.content.combat.Skulling.Skulling (Player player)
Constructs a new Skulling class.
Parameters
player The player instance.
Definition at line 36 of file Skulling.java.
{
        this.player = player;
        this.skullRemoveTask = new SkullRemoveTask(player);
    }
References player.
Member Function Documentation
checkForSkulling()
void com.runehive.content.combat.Skulling.checkForSkulling (Player opponent)
Checks if player requires a skull upon attacking another player.
Parameters
opponent The opponent.
Definition at line 46 of file Skulling.java.
{
    /*    if (Area.inEventArena(opponent)) {
            return;
        }*/
        if (!attacked.contains(opponent.getName()) && !opponent.skulling.attacked.contains(player.getName())) {
            skull(opponent, SkullHeadIconType.WHITE_SKULL);
        }
    }
References attacked, com.runehive.game.world.entity.mob.player.Player.getName(), player, skull(), com.runehive.game.world.entity.mob.player.Player.skulling, and com.runehive.content.combat.SkullHeadIconType.WHITE_SKULL.
getHeadIconType()
SkullHeadIconType com.runehive.content.combat.Skulling.getHeadIconType ()
Gets the skull icon.
Returns
The skull icon.
Definition at line 115 of file Skulling.java.
{
        return icon;
    }
References icon.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask().
getSkullRemoveTask()
SkullRemoveTask com.runehive.content.combat.Skulling.getSkullRemoveTask ()
Definition at line 106 of file Skulling.java.
{
         return skullRemoveTask;
    }
References skullRemoveTask.
isSkulled()
boolean com.runehive.content.combat.Skulling.isSkulled ()
Definition at line 88 of file Skulling.java.
{
        return skullRemoveTask.isRunning();
    }
References skullRemoveTask.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.apply(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.onLogin(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.removeOn(), and unskull().
skull() [1/3]
void com.runehive.content.combat.Skulling.skull ()
Definition at line 55 of file Skulling.java.
{
        skull(player, SkullHeadIconType.WHITE_SKULL);
    }
References player, skull(), and com.runehive.content.combat.SkullHeadIconType.WHITE_SKULL.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.apply(), checkForSkulling(), skull(), and skull().
skull() [2/3]
void com.runehive.content.combat.Skulling.skull (Player attacking, SkullHeadIconType icon)
Skulls the player and deposit's the attacked player into the list.
Parameters
attacking
Definition at line 68 of file Skulling.java.
{
        if (attacking.inActivity()) {
            return;
        }
        if(LMSGame.inGameArea(attacking)) return;
        if (attacking != player) {
            attacked.add(attacking.getName());
        }
        this.icon = icon;
        player.updateFlags.add(UpdateFlag.APPEARANCE);
        if (!skullRemoveTask.isRunning()) {
            skullRemoveTask.setSkullTime(skullRemoveTask.getSkullTime() <= 0 ? Config.SKULL_TIME : skullRemoveTask.getSkullTime());
            World.schedule(skullRemoveTask);
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, attacked, com.runehive.game.world.entity.mob.player.Player.getName(), icon, com.runehive.game.world.entity.mob.Mob.inActivity(), com.runehive.content.lms.LMSGame.inGameArea(), player, com.runehive.game.world.World.schedule(), com.runehive.Config.SKULL_TIME, and skullRemoveTask.
skull() [3/3]
void com.runehive.content.combat.Skulling.skull (SkullHeadIconType icon)
Definition at line 59 of file Skulling.java.
{
        skull(player, icon);
    }
References icon, player, and skull().
unskull()
void com.runehive.content.combat.Skulling.unskull ()
Unskulls the player.
Definition at line 95 of file Skulling.java.
{
        if (!isSkulled()) {
            return;
        }
        skullRemoveTask.setSkullTime(0);
        attacked.clear();
        icon = SkullHeadIconType.NO_SKULL;
        player.updateFlags.add(UpdateFlag.APPEARANCE);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, attacked, icon, isSkulled(), com.runehive.content.combat.SkullHeadIconType.NO_SKULL, player, and skullRemoveTask.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.removeOn().
Member Data Documentation
attacked
final List<String> com.runehive.content.combat.Skulling.attacked = new LinkedList<>() private
All the other player's this entity has attacked.
Definition at line 21 of file Skulling.java.
Referenced by checkForSkulling(), skull(), and unskull().
icon
SkullHeadIconType com.runehive.content.combat.Skulling.icon = SkullHeadIconType.NO_SKULL private
Their skull icon identification.
Definition at line 27 of file Skulling.java.
Referenced by getHeadIconType(), skull(), skull(), and unskull().
player
Player com.runehive.content.combat.Skulling.player private
The player of this class.
Definition at line 24 of file Skulling.java.
Referenced by checkForSkulling(), skull(), skull(), skull(), Skulling(), and unskull().
skullRemoveTask
SkullRemoveTask com.runehive.content.combat.Skulling.skullRemoveTask private
Definition at line 29 of file Skulling.java.
Referenced by getSkullRemoveTask(), isSkulled(), skull(), and unskull().
The documentation for this class was generated from the following file:
java/com/runehive/content/combat/Skulling.java