RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.VeracModifier Class Reference
com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.VeracModifier Class Reference
Public Member Functions
int modifyDefenceLevel (Mob attacker, Mob defender, int level)
int modifyDefensiveBonus (Mob attacker, Mob defender, int bonus)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static VeracModifier get ()
Static Private Attributes
static final VeracModifier INSTANCE = new VeracModifier()
Detailed Description
Definition at line 28 of file VeracListener.java.
Member Function Documentation
get()
VeracModifier com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.VeracModifier.get () static
Definition at line 41 of file VeracListener.java.
{
            return INSTANCE;
        }
References INSTANCE.
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.finishOutgoing(), and com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.init().
modifyDefenceLevel()
int com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.VeracModifier.modifyDefenceLevel (Mob attacker, Mob defender, int level)
Definition at line 32 of file VeracListener.java.
{
            return 0;
        }
modifyDefensiveBonus()
int com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.VeracModifier.modifyDefensiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 37 of file VeracListener.java.
{
            return 0;
        }
Member Data Documentation
INSTANCE
final VeracModifier com.runehive.game.world.entity.combat.attack.listener.item.VeracListener.VeracModifier.INSTANCE = new VeracModifier() static private
Definition at line 29 of file VeracListener.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/item/VeracListener.java