RuneHive-Game: com.runehive.game.world.entity.mob.player.Player Class Reference
com.runehive.game.world.entity.mob.player.Player Class Reference
This class represents a character controlled by a player.
Public Member Functions
void addToRegion (Region region)
Adds this entity to the specified region.
void appendDeath ()
Handles the mob death.
void chat (ChatMessage chatMessage)
boolean equals (Object obj)
void forClan (Consumer< ClanChannel > action)
Optional< AntifireDetails > getAntifireDetails ()
Appearance getAppearance ()
Optional< ChatMessage > getChatMessage ()
CollectionLog getCollectionLog ()
Combat< Player > getCombat ()
The combat of the mob.
CombatSpecial getCombatSpecial ()
Events getEvents ()
GambleManager getGambling ()
long getLastModification ()
int getMemberId ()
String getName ()
Gets the name of this entity.
String getPassword ()
final MutableNumber getPoisonImmunity ()
int getSceneBaseChunkX ()
int getSceneBaseChunkY ()
Optional< GameSession > getSession ()
MutableNumber getSpecialPercentage ()
CombatStrategy< Player > getStrategy ()
The combat strategy of the mob.
EntityType getType ()
Gets the EntityType.
String getUsername ()
final MutableNumber getVenomImmunity ()
WeaponInterface getWeapon ()
int hashCode ()
boolean isAutocast ()
boolean isAutoRetaliate ()
State of the mob's auto retaliate.
boolean isGambleLocked ()
boolean isSingleCast ()
boolean isSpecialActivated ()
boolean isTeleblocked ()
boolean isValid ()
Validates this npc based on its current region and registered state.
void loadRegion ()
final void logout ()
final void logout (boolean force)
void message (boolean filtered, String... messages)
void message (String message)
void message (String... messages)
void onStep ()
void pickup (Item item, Position position)
Player (String username)
Player (String username, Position position)
void register ()
Registers an entity to the World.
void removeFromRegion (Region region)
Removes this entity from the specified region.
void send (OutgoingPacket encoder)
void sequence ()
The method which is invoked every tick.
void setAntifireDetail (AntifireDetails antifireDetails)
void setAutocast (CombatSpell autocast)
void setCollectionLog (CollectionLog collectionLog)
void setCombatSpecial (CombatSpecial special)
void setGambleLock (boolean gambleLocked)
void setLastModification (long lastModification)
void setMemberId (int memberId)
void setPassword (String password)
void setSceneBaseChunks (int chunkX, int chunkY)
void setSession (GameSession session)
void setSingleCast (CombatSpell singleCast)
void setSpecialActivated (boolean activated)
void setUsername (String username)
void setWeapon (WeaponInterface weapon)
void teleblock (int time)
int toSceneLocalX (int worldX)
int toSceneLocalX (Position pos)
int toSceneLocalY (int worldY)
int toSceneLocalY (Position pos)
String toString ()
void unregister ()
Unregisters an entity from the World.
Public Member Functions inherited from com.runehive.game.world.entity.mob.Mob
void animate (Animation animation)
Plays an animation.
void animate (Animation animation, final boolean override)
Plays an animation.
void animate (int animation)
void animate (int animation, boolean override)
void appendBonus (int index, int amount)
void attack (Mob target)
void clearTeleportTarget ()
Resets the teleport target.
void damage (Hit... hits)
Hit decrementHealth (Hit hit)
void face (Direction direction)
Sets the client update flag to face a certain direction.
void face (GameObject object)
Sets the client update flag to face a certain direction.
void face (Mob mob)
void face (Position position)
Sets the client update flag to face a certain direction.
void follow (Mob target)
void forceMove (int animation, int x, int y)
void forceMove (int delay, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
void forceMove (int delay, int delay2, int animation, int animationDelay, int startSpeed, int endSpeed, Position offset, Direction direction)
Creates a force movement action for an entity.
void forceMove (int delay, int delay2, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
Optional< Animation > getAnimation ()
int getBonus (int index)
int[] getBonuses ()
int getCurrentHealth ()
ForceMovement getForceMovement ()
Optional< Graphic > getGraphic ()
int getId ()
int getListIndex ()
int getMaximumHealth ()
final Npc getNpc ()
final Player getPlayer ()
final MutableNumber getPoisonDamage ()
PoisonType getPoisonType ()
int getPriorityIndex ()
int getTransformId ()
MutableNumber getVenomDamage ()
void graphic (Graphic graphic)
Plays a graphic.
void graphic (Graphic graphic, boolean override)
Plays a graphic.
void graphic (int graphic)
boolean hasPriorityIndex (Mob other)
void heal (int amount)
boolean inActivity ()
boolean inActivity (ActivityType type)
void interact (Mob mob)
Sets the mob interacting with another mob.
boolean isDead ()
boolean isFixingInside ()
final boolean isNpc ()
Check if an entity is an npc.
final boolean isNpc (BooleanInterface< Npc > condition)
Check if an entity is an npc.
final boolean isPlayer ()
Check if an entity is a player.
final boolean isPlayer (Function< Player, Boolean > condition)
Check if an entity is a player.
final boolean isPoisoned ()
boolean isUpdateRequired ()
Checks if mob requires an update.
final boolean isVenomed ()
Mob (Position position)
Constructs a new Mob.
Mob (Position position, boolean visible)
void move (Position position)
Moves the mob to a set position.
void poison (PoisonType type)
Applies poison with an intensity of type to the entity.
final void reset ()
Resets the mob after an update.
void resetAnimation ()
void resetFace ()
Resets the mob's face location.
void resetGraphic ()
final void resetWaypoint ()
Resets the waypoint.
void runTo (Position destination)
void setActivity (Activity activity)
void setBonus (int equipSlot, int bonus)
void setBonuses (int[] bonuses)
void setDead (boolean dead)
void setFixingInside (boolean fixingInside)
void setForceMovement (ForceMovement forceMovement)
void setListIndex (int listIndex)
void speak (String forceChat)
Sets the mob's forced chat.
void takeStep ()
void transform (int transformId)
void transform (int transformId, boolean reload)
Transforms the mob.
void unpoison ()
void unvenom ()
void venom ()
Applies venom to the entity.
void walk (Position destination, boolean ignoreClip)
void walk (Position position)
void walkExactlyTo (Position position)
void walkExactlyTo (Position position, Runnable onDestination)
void walkTo (Interactable target, boolean clearAction, Runnable onDestination)
void walkTo (Interactable target, Runnable onDestination)
void walkTo (Position position)
void walkTo (Position position, Runnable onDestination)
void writeDamage (Hit hit)
void writeFakeDamage (Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.Entity
Entity (Position position)
Entity (Position position, boolean visible)
Position getCenterPosition ()
int getHeight ()
int getIndex ()
Position getPosition ()
Region getRegion ()
int getX ()
int getY ()
boolean is (EntityType type)
final boolean isCustomObject ()
Check if an entity is an object.
final boolean isRegistered ()
final boolean isStaticObject ()
Check if an entity is an object.
boolean isVisible ()
int length ()
void setIndex (int index)
void setLength (int length)
void setPosition (Position position)
void setVisible (boolean visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
void setZ (int z)
int width ()
Public Attributes
int[] achievedSkills = new int[7]
final ActivityLogger activityLogger = new ActivityLogger(this)
Stopwatch aggressionTimer = Stopwatch.start()
int agsCharges = 750
int answeredTrivias
Appearance appearance = Config.DEFAULT_APPEARANCE
CombatSpell autocast
final Bank bank = new Bank(this)
final BankPin bankPin = new BankPin(this)
final BankVault bankVault = new BankVault(this)
boolean[] barrowKills = new boolean[BrotherData.values().length]
int barrowsKillCount
List< PlayerBirdHouseData > birdHouseData = new ArrayList<>()
Item blowpipeDarts
float blowpipeScales
Stopwatch buttonDelay = Stopwatch.start()
int celestialRingCharges
ChatBoxItemDialogue chatBoxItemDialogue
String clan = ""
ClanChannel clanChannel
String clanTag = ""
String clanTagColor = ""
final ClanViewer clanViewer = new ClanViewer(this)
CoalBag coalBag = new CoalBag()
CollectionLogPage collectionLogPageOpen = null
CollectionLogData collectionLogView = null
boolean completedMageArena
final Set< PlayerOption > contextMenus = new HashSet<>()
int cooldown = 7 * 60 * 1000
int crawsBowCharges
String created = Utility.getDate()
DailyEffect dailySlayerTaskSkip = new DailySlayerTaskSkip()
DailyEffect dailySlayerTaskTeleport = new DailySlayerTaskTeleport()
DailyEffect dailySpellBookSwap = new DailySpellBookSwap()
Stopwatch databaseRequest = Stopwatch.start()
int death
boolean debug
Optional< Dialogue > dialogue = Optional.empty()
transient int dialogueCamDelayTicks = 0
Delay ticks before camera activates (prevents coordinate misalignment at dialogue start).
transient com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.OFF
Dialogue camera system.
transient com.runehive.game.world.entity.mob.npc.Npc dialogueCamNpc = null
transient int dialogueCamSwapBoostTicks = 0
While >0, camera turns use slightly faster "swap" speeds for a smoother PNPC flip.
DialogueFactory dialogueFactory = new DialogueFactory(this)
Stopwatch diceDelay = Stopwatch.start()
final Donation donation = new Donation(this)
final DonatorDeposit donatorDeposit = new DonatorDeposit(this)
int dragonfireCharges
long dragonfireUsed
List< EmoteUnlockable > emoteUnlockable = new LinkedList<>()
int energyRate
Optional< Consumer< String > > enterInputListener = Optional.empty()
final Equipment equipment = new Equipment(this)
final Equipment equipment_copy = new Equipment(this)
final ExchangeSessionManager exchangeSession = new ExchangeSessionManager(this)
double experienceRate = Config.COMBAT_MODIFICATION
final Farming farming = new Farming(this)
Stopwatch fastFoodDelay = Stopwatch.start()
List< Teleport > favoriteTeleport = new ArrayList<>()
HashMap< WeaponInterface, FightType > fightStyles = new HashMap<>()
Stopwatch foodDelay = Stopwatch.start()
final PlayerRecord gameRecord = new PlayerRecord(this)
GemBag gemBag = new GemBag()
int giantPouch
int glovesTier
Stopwatch godwarsDelay = Stopwatch.start()
boolean hasPvPTimer
int headIcon
BrotherData hiddenBrother
final Set< String > hostList = new HashSet<>()
final House house = new House(this)
boolean idle
final InterfaceManager interfaceManager = new InterfaceManager(this)
final Inventory inventory = new Inventory(this)
final Inventory inventory_copy = new Inventory(this)
boolean isBot
Stopwatch itemDelay = Stopwatch.start()
int kill
final Killstreak killstreak = new Killstreak(this)
int largePouch
String lastClan = ""
int lastFogSent
LMS Variables.
String lastHost
Deque< String > lastKilled = new ArrayDeque<>(3)
long lastLMSRopeCross
Teleport lastTeleport = null
long lastUsed = 0
int lmsDeaths
transient long lmsImmunity
int lmsKills
int lmsPoints
int lmsTotalDeaths
int lmsTotalKills
int lmsWins
HashMap< ActivityLog, Integer > loggedActivities
final LootingBag lootingBag = new LootingBag(this)
LinkedList< Item > lostItems = new LinkedList<>()
Set< PetData > lostPets = new HashSet<>()
final LostUntradeables lostUntradeables = new LostUntradeables(this)
int mageArenaPoints
int magmaHelmCharges
Optional< Player > managing
int mediumPouch
int menuOpened
final MysteryBoxManager mysteryBox = new MysteryBoxManager(this)
boolean needsStarter
boolean newPlayer
Optional< OptionDialogue > optionDialogue = Optional.empty()
int optionOpened = -1
final Overrides overrides = new Overrides(this)
int pestPoints
Npc pet
Set< PetData > petInsurance = new HashSet<>()
HashMap< AchievementKey, Integer > playerAchievements
final PlayerAssistant playerAssistant = new PlayerAssistant(this)
PlayerTitle playerTitle = PlayerTitle.empty()
int playTime
Stopwatch potionDelay = Stopwatch.start()
final PresetManager presetManager = new PresetManager(this)
final Prestige prestige = new Prestige(this)
final PriceChecker priceChecker = new PriceChecker(this)
final PlayerPunishment punishment = new PlayerPunishment(this)
final PuzzleDisplay puzzle = new PuzzleDisplay(this)
boolean pvpInstance
Stopwatch pvpTimer = Stopwatch.start()
PrayerBook quickPrayers = new PrayerBook()
RangedAmmunition rangedAmmo
RangedWeaponDefinition rangedDefinition
final PlayerRelation relations = new PlayerRelation(this)
final RequestManager requestManager = new RequestManager(this)
boolean resting
Stopwatch restoreDelay = Stopwatch.start()
Stopwatch revstele = Stopwatch.start()
PlayerRight right = PlayerRight.PLAYER
int ringOfRecoil = 40
int royalty
int royaltyLevel = 1
final RunecraftPouch runecraftPouch = new RunecraftPouch(this)
int runEnergy
final RunePouch runePouch = new RunePouch(this)
final RunePouch runePouch_copy = new RunePouch(this)
final AtomicBoolean saved = new AtomicBoolean(false)
int sequence
int serpentineHelmCharges
final Settings settings = new Settings(this)
int shop
CombatSpell singleCast
int skillingPoints
Skulling skulling = new Skulling(this)
Slayer slayer = new Slayer(this)
int smallPouch
Spellbook spellbook = Spellbook.MODERN
Spellbook spellbook_copy = Spellbook.MODERN
SpellCasting spellCasting = new SpellCasting(this)
Stopwatch staffOfDeadSpecial = Stopwatch.start().reset(200)
int tanzaniteHelmCharges
final AtomicInteger teleblockTimer = new AtomicInteger(0)
int thammoranSceptreCharges
int totalVotes
final TradingPost tradingPost = new TradingPost(this)
int trapsLaid
int tridentSeasCharges
int tridentSwampCharges
List< Integer > unlockedLMSItems = new ArrayList<>()
HashSet< Prayer > unlockedPrayers = new HashSet<>()
long usernameLong
String uuid
int valueIcon = -1
boolean venged
final Map< Integer, PersonalStore > viewing_shops = new HashMap<>()
final Viewport viewport = new Viewport(this)
int viggorasChainmaceCharges
int votePoints
boolean warriorGuidTask
Map< String, Position > waypoints = new HashMap<>()
int whipCharges = 2500
int wilderness
int wintertodtPoints
Stopwatch yellDelay = Stopwatch.start()
Public Attributes inherited from com.runehive.game.world.entity.mob.Mob
ActionManager action = new ActionManager()
Activity activity
final GenericAttributes attributes = new GenericAttributes()
boolean blockFace
boolean blockInteract
Stopwatch damageImmunity = Stopwatch.start()
Position facePosition
Hit firstHit
List< Mob > followers = new LinkedList<>()
String forceChat
ForceMovement forceMovement
boolean forceWalking
final Stopwatch freezeImmunity = Stopwatch.start()
int id = -1
boolean inTeleport
Mob interactingWith
Position lastPosition
final Locking locking = new Locking(this)
MobAnimation mobAnimation = new MobAnimation(updateFlags)
final Movement movement = new Movement(this)
transient long nextAnimation
boolean pathfinderProjectiles = false
boolean positionChange
PrayerBook prayer = new PrayerBook()
boolean regionChange
Hit secondHit
final SkillManager skills = new SkillManager(this)
final SkillManager skills_copy = new SkillManager(this)
boolean teleporting
boolean teleportRegion
Position teleportTarget
final EnumSet< UpdateFlag > updateFlags = EnumSet.noneOf(UpdateFlag.class)
Public Attributes inherited from com.runehive.game.world.entity.Entity
int instance = DEFAULT_INSTANCE
Package Functions
CombatSpell getAutocastSpell ()
CombatSpell getSingleCastSpell ()
Private Member Functions
boolean canLogout ()
void login ()
void sendInitialPackets ()
Private Attributes
AntifireDetails antifireDetails
Optional< ChatMessage > chatMessage = Optional.empty()
CollectionLog collectionLog = new CollectionLog()
final Combat< Player > combat = new Combat<>(this)
CombatSpecial combatSpecial
final Events events = new Events()
boolean gambleLocked
final GambleManager gamblingManager = new GambleManager()
long lastModification
int memberId = -1
String password = ""
final MutableNumber poisonImmunity = new MutableNumber()
transient int sceneBaseChunkX
Client's current scene base, in 8x8 chunks (set when SendMapRegion is sent).
transient int sceneBaseChunkY
Optional< GameSession > session = Optional.empty()
boolean specialActivated
final MutableNumber specialPercentage = new MutableNumber()
String username = ""
final MutableNumber venomImmunity = new MutableNumber()
WeaponInterface weapon = WeaponInterface.UNARMED
Static Private Attributes
static final Logger logger = LogManager.getLogger(Player.class)
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.mob.Mob
static boolean pathfinderProjectiles (Mob source)
Static Public Member Functions inherited from com.runehive.game.world.Interactable
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Static Public Attributes inherited from com.runehive.game.world.entity.Entity
static final int DEFAULT_INSTANCE = 0
Protected Member Functions inherited from com.runehive.game.world.entity.mob.Mob
void setWaypoint (Waypoint waypoint)
Protected Member Functions inherited from com.runehive.game.world.entity.Entity
Entity destroy ()
Destroys this entity.
void setRegistered (boolean registered)
Protected Attributes inherited from com.runehive.game.world.entity.mob.Mob
Waypoint cachedWaypoint
Detailed Description
This class represents a character controlled by a player.
Author
Daniel
Michael | Chex
Definition at line 125 of file Player.java.
Constructor & Destructor Documentation
Player() [1/2]
com.runehive.game.world.entity.mob.player.Player.Player (String username)
Definition at line 394 of file Player.java.
{
        super(Config.DEFAULT_POSITION, false);
        this.username = username;
        this.usernameLong = Utility.nameToLong(username);
    }
References com.runehive.Config.DEFAULT_POSITION, com.runehive.util.Utility.nameToLong(), and username.
Referenced by equals(), com.runehive.content.bot.PlayerBot.retaliate(), com.runehive.content.bot.PlayerBot.unregister(), and unregister().
Player() [2/2]
com.runehive.game.world.entity.mob.player.Player.Player (String username, Position position)
Definition at line 400 of file Player.java.
{
        super(Config.DEFAULT_POSITION);
        this.setPosition(position);
        this.setUsername(username);
        this.isBot = true;
    }
References com.runehive.Config.DEFAULT_POSITION, com.runehive.game.world.entity.Entity.position, com.runehive.game.world.entity.Entity.setPosition(), setUsername(), and username.
Member Function Documentation
addToRegion()
void com.runehive.game.world.entity.mob.player.Player.addToRegion (Region region)
Adds this entity to the specified region.
Parameters
region The region.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 619 of file Player.java.
{
        region.addPlayer(this);
        aggressionTimer.reset();
    }
References aggressionTimer.
appendDeath()
void com.runehive.game.world.entity.mob.player.Player.appendDeath ()
Handles the mob death.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 769 of file Player.java.
{
        World.schedule(new PlayerDeath(this));
    }
References com.runehive.game.world.World.schedule().
canLogout()
boolean com.runehive.game.world.entity.mob.player.Player.canLogout () private
Definition at line 486 of file Player.java.
{
        if (getCombat().inCombat()) {
            send(new SendMessage("You can not logout whilst in combat!"));
            return false;
        }
        if (!getCombat().hasPassed(CombatConstants.COMBAT_LOGOUT_COOLDOWN)) {
            final long seconds = TimeUnit.SECONDS.convert(
                    CombatConstants.COMBAT_LOGOUT_COOLDOWN - combat.elapsedTime(),
                    TimeUnit.MILLISECONDS);
            send(new SendMessage("You must wait " + seconds + " second" + (seconds > 1 ? "s" : "")
                    + " before you can logout as you were recently in combat."));
            return false;
        }
        if (!interfaceManager.isMainClear()) {
            send(new SendMessage("Please close what you are doing before logging out!"));
            return false;
        }
        return !Activity.evaluate(this, it -> !it.canLogout(this));
    }
References combat, com.runehive.game.world.entity.combat.CombatConstants.COMBAT_LOGOUT_COOLDOWN, com.runehive.content.activity.Activity.evaluate(), getCombat(), interfaceManager, and send().
Referenced by logout().
chat()
void com.runehive.game.world.entity.mob.player.Player.chat (ChatMessage chatMessage)
Definition at line 407 of file Player.java.
{
        if (!chatMessage.isValid()) {
            return;
        }
        this.chatMessage = Optional.of(chatMessage);
        this.updateFlags.add(UpdateFlag.CHAT);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.CHAT, chatMessage, and com.runehive.game.world.entity.mob.Mob.updateFlags.
equals()
boolean com.runehive.game.world.entity.mob.player.Player.equals (Object obj)
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 789 of file Player.java.
{
        if (obj == this) {
            return true;
        }
        if (obj == null || !(obj instanceof Player)) {
            return false;
        }
        Player other = (Player) obj;
        return Objects.equals(getIndex(), other.getIndex()) && Objects.equals(username, other.username) && Objects.equals(password, other.password) && Objects.equals(isBot, other.isBot);
    }
References com.runehive.game.world.entity.Entity.getIndex(), isBot, password, Player(), and username.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.hitEvent(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyMagicLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyRangedLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyStrengthLevel(), com.runehive.content.ProfileViewer.open(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove(), and com.runehive.content.activity.impl.duelarena.DuelRule.set().
forClan()
void com.runehive.game.world.entity.mob.player.Player.forClan (Consumer< ClanChannel > action)
Definition at line 568 of file Player.java.
{
        if (clanChannel != null)
            action.accept(clanChannel);
    }
References com.runehive.game.world.entity.mob.Mob.action, and clanChannel.
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), and com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards().
getAntifireDetails()
Optional< AntifireDetails > com.runehive.game.world.entity.mob.player.Player.getAntifireDetails ()
Definition at line 897 of file Player.java.
{
        return Optional.ofNullable(antifireDetails);
    }
References antifireDetails.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.apply(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.process(), and com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.removeOn().
getAppearance()
Appearance com.runehive.game.world.entity.mob.player.Player.getAppearance ()
Definition at line 949 of file Player.java.
{
        return appearance;
    }
References appearance.
getAutocastSpell()
CombatSpell com.runehive.game.world.entity.mob.player.Player.getAutocastSpell () package
Definition at line 856 of file Player.java.
{
        return autocast;
    }
References autocast.
Referenced by login().
getChatMessage()
Optional< ChatMessage > com.runehive.game.world.entity.mob.player.Player.getChatMessage ()
Definition at line 913 of file Player.java.
{
        return chatMessage;
    }
References chatMessage.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask().
getCollectionLog()
CollectionLog com.runehive.game.world.entity.mob.player.Player.getCollectionLog ()
Definition at line 204 of file Player.java.
{
        return this.collectionLog;
    }
Referenced by com.runehive.content.collectionlog.CollectionLog.getLogItemAmount(), com.runehive.content.collectionlog.CollectionLog.increaseCounter(), com.runehive.content.collectionlog.CollectionLog.logItem(), com.runehive.content.collectionlog.CollectionLogSaving.save(), com.runehive.content.collectionlog.CollectionLog.selectLog(), and com.runehive.content.collectionlog.CollectionLog.sendButtons().
getCombat()
Combat< Player > com.runehive.game.world.entity.mob.player.Player.getCombat ()
The combat of the mob.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 759 of file Player.java.
{
        return combat;
    }
References combat.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.accuracy(), com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.addListener(), com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block(), com.runehive.content.lms.LMSGame.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), canLogout(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.PureMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.PureRangeMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.ZerkerMelee.canOtherAttack(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.combat.magic.Autocast.clickButton(), com.runehive.content.bot.PlayerBot.endFight(), com.runehive.content.itemaction.impl.DragonfireShield.equipment(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.finishIncoming(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackDelay(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.bot.botclass.impl.ZerkerMelee.hit(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.hitEvent(), com.runehive.content.bot.PlayerBot.loopCombat(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.content.lms.LMSGame.onDeath(), com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction.onExecution(), onStep(), com.runehive.content.ProfileViewer.open(), com.runehive.content.RoyaltyProgram.open(), pickup(), com.runehive.content.bot.PlayerBot.postDeath(), com.runehive.content.bot.PlayerBot.pot(), com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.removeListener(), com.runehive.content.bot.PlayerBot.retaliate(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
getCombatSpecial()
CombatSpecial com.runehive.game.world.entity.mob.player.Player.getCombatSpecial ()
Definition at line 885 of file Player.java.
{
        return combatSpecial;
    }
References combatSpecial.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start(), and com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.start().
getEvents()
Events com.runehive.game.world.entity.mob.player.Player.getEvents ()
Definition at line 953 of file Player.java.
{
        return events;
    }
References events.
Referenced by com.runehive.net.packet.in.UseItemPacketListener.handleItemOnNpc(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnObject(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnPlayer(), com.runehive.net.packet.in.AppearanceChangePacketListener.handlePacket(), com.runehive.net.packet.in.ChatMessagePacketListener.handlePacket(), com.runehive.net.packet.in.CommandPacketListener.handlePacket(), com.runehive.net.packet.in.DialoguePacketListener.handlePacket(), com.runehive.net.packet.in.DropdownMenuPacketListener.handlePacket(), com.runehive.net.packet.in.DropViewerListener.handlePacket(), com.runehive.net.packet.in.ExaminePacketListener.handlePacket(), com.runehive.net.packet.in.InputFieldPacketListener.handlePacket(), com.runehive.net.packet.in.InputStringPacketListener.handlePacket(), com.runehive.net.packet.in.KeyPacketListener.handlePacket(), com.runehive.net.packet.in.MoveItemPacketListener.handlePacket(), com.runehive.net.packet.in.PickupItemPacketListener.handlePacket(), com.runehive.net.packet.in.PlayerRelationPacketListener.handlePacket(), com.runehive.net.packet.in.PrivacyOptionPacketListener.handlePacket(), com.runehive.net.packet.in.RegionChangePacketListener.handlePacket(), and com.runehive.net.packet.in.WalkingPacketListener.handlePacket().
getGambling()
GambleManager com.runehive.game.world.entity.mob.player.Player.getGambling ()
Definition at line 136 of file Player.java.
{
        return gamblingManager;
    }
References gamblingManager.
Referenced by com.runehive.content.gambling.GambleManager.accept(), com.runehive.content.gambling.GambleManager.acceptRequest(), com.runehive.content.gambling.GambleManager.canGamble(), com.runehive.content.gambling.GambleManager.decline(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.gambling.GambleManager.finish(), com.runehive.content.gambling.impl.FiftyFive.gamble(), com.runehive.content.gambling.impl.FlowerPoker.gamble(), com.runehive.content.gambling.impl.FlowerPoker.getRank(), com.runehive.content.gambling.GambleManager.give(), com.runehive.content.gambling.GambleManager.handleModeSelection(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.gambling.GambleManager.open(), com.runehive.content.gambling.impl.FlowerPoker.plant(), com.runehive.content.gambling.GambleManager.removeFlowers(), com.runehive.content.gambling.GambleManager.reset(), com.runehive.content.gambling.GambleManager.sendRequest(), com.runehive.content.gambling.GambleManager.start(), unregister(), and com.runehive.content.gambling.GambleManager.withdraw().
getLastModification()
long com.runehive.game.world.entity.mob.player.Player.getLastModification ()
Definition at line 146 of file Player.java.
{
        return lastModification;
    }
References lastModification.
Referenced by com.runehive.content.gambling.GambleManager.accept().
getMemberId()
int com.runehive.game.world.entity.mob.player.Player.getMemberId ()
Definition at line 925 of file Player.java.
{
        return memberId;
    }
References memberId.
Referenced by com.runehive.game.service.HighscoreService.saveHighscores(), and toString().
getName()
String com.runehive.game.world.entity.mob.player.Player.getName ()
Gets the name of this entity.
Returns
The entity's name.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 774 of file Player.java.
{
        return Utility.formatName(username);
    }
References com.runehive.util.Utility.formatName(), and username.
Referenced by com.runehive.game.plugin.PluginContext.accept(), com.runehive.content.famehall.FameHandler.activate(), com.runehive.content.store.impl.PersonalStore.add(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.allMatch(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.anyMatch(), com.runehive.content.RoyaltyProgram.append(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.lms.LMSGame.canAttack(), com.runehive.content.store.impl.PersonalStore.changeName(), com.runehive.content.clanchannel.ClanMember.chat(), com.runehive.content.combat.Skulling.checkForSkulling(), com.runehive.game.service.DonationService.claimDonation(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), com.runehive.content.skill.impl.fletching.Fletching.clickButton(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.clanchannel.channel.ClanChannelHandler.connect(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.clanchannel.channel.ClanChannel.create(), com.runehive.content.clanchannel.channel.ClanChannelHandler.disconnect(), com.runehive.content.combat.cannon.CannonManager.drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.combat.cannon.CannonManager.empty(), com.runehive.content.combat.Killstreak.end(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.activity.record.GameRecord.GameRecord(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getOther(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.game.plugin.PluginContext.handleDropItemEvent(), com.runehive.game.plugin.PluginContext.handlePickupItemEvent(), com.runehive.content.store.impl.PersonalStore.isOwner(), com.runehive.content.combat.cannon.CannonManager.load(), com.runehive.content.combat.cannon.CannonManager.logout(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manage(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember(), com.runehive.content.store.impl.PersonalStore.myShop(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.content.ProfileViewer.open(), com.runehive.content.store.impl.PersonalStore.openMenu(), com.runehive.content.combat.cannon.CannonManager.pickup(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), com.runehive.content.tittle.TitleManager.refresh(), register(), com.runehive.game.world.entity.mob.player.requests.RequestManager.request(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.game.service.HighscoreService.saveHighscores(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues(), sendInitialPackets(), com.runehive.content.gambling.GambleManager.sendRequest(), com.runehive.content.combat.Skulling.skull(), com.runehive.content.combat.cannon.CannonManager.test(), unregister(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateMainComponents(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateMainComponents(), com.runehive.content.clanchannel.channel.ClanChannelHandler.updateMemberList(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents(), com.runehive.game.world.entity.skill.SkillManager.updateSkill(), and com.runehive.content.Yell.yell().
getPassword()
String com.runehive.game.world.entity.mob.player.Player.getPassword ()
Definition at line 945 of file Player.java.
{
        return password;
    }
References password.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser(), com.runehive.net.session.LoginSession.evaluate(), and com.runehive.net.session.LoginSession.handleUserLoginDetails().
getPoisonImmunity()
final MutableNumber com.runehive.game.world.entity.mob.player.Player.getPoisonImmunity ()
Definition at line 905 of file Player.java.
{
        return poisonImmunity;
    }
References poisonImmunity.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.apply(), com.runehive.game.task.impl.SuperAntipoisonTask.execute(), com.runehive.content.consume.PotionData.onAntiPoisonEffect(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask().
getSceneBaseChunkX()
int com.runehive.game.world.entity.mob.player.Player.getSceneBaseChunkX ()
Definition at line 958 of file Player.java.
{
        return sceneBaseChunkX;
    }
References sceneBaseChunkX.
Referenced by com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.shoulderShot().
getSceneBaseChunkY()
int com.runehive.game.world.entity.mob.player.Player.getSceneBaseChunkY ()
Definition at line 962 of file Player.java.
{
        return sceneBaseChunkY;
    }
References sceneBaseChunkY.
Referenced by com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.shoulderShot().
getSession()
Optional< GameSession > com.runehive.game.world.entity.mob.player.Player.getSession ()
Definition at line 929 of file Player.java.
{
        return session;
    }
References session.
Referenced by com.runehive.net.packet.OutgoingPacket.execute(), and com.runehive.game.world.World.queueLogin().
getSingleCastSpell()
CombatSpell com.runehive.game.world.entity.mob.player.Player.getSingleCastSpell () package
Definition at line 844 of file Player.java.
{
        return singleCast;
    }
References singleCast.
getSpecialPercentage()
MutableNumber com.runehive.game.world.entity.mob.player.Player.getSpecialPercentage ()
Definition at line 864 of file Player.java.
{
        return specialPercentage;
    }
References specialPercentage.
Referenced by com.runehive.net.packet.out.SendSpecialAmount.encode(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), com.runehive.content.bot.botclass.impl.PureMelee.hit(), com.runehive.content.bot.botclass.impl.PureRangeMelee.hit(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.hit(), and com.runehive.content.bot.botclass.impl.ZerkerMelee.hit().
getStrategy()
CombatStrategy< Player > com.runehive.game.world.entity.mob.player.Player.getStrategy ()
The combat strategy of the mob.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 764 of file Player.java.
{
        return playerAssistant.getStrategy();
    }
References playerAssistant.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.accuracy(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.eat(), com.runehive.content.bot.botclass.impl.PureMelee.eat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.eat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.eat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.eat(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.VoidKnightMeleeListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.elite.EliteKnightMagicListener.modifyDamage(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.elite.EliteKnightRangedListener.modifyDamage(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.elite.EliteKnightRangedListener.modifyRangedLevel(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.VoidKnightMeleeListener.modifyStrengthLevel(), com.runehive.content.bot.botclass.impl.PureMelee.pot(), com.runehive.content.bot.botclass.impl.PureRangeMelee.pot(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update().
getType()
EntityType com.runehive.game.world.entity.mob.player.Player.getType ()
Gets the EntityType.
Returns
The EntityType.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 779 of file Player.java.
{
        return EntityType.PLAYER;
    }
References com.runehive.game.world.entity.EntityType.PLAYER.
getUsername()
String com.runehive.game.world.entity.mob.player.Player.getUsername ()
Definition at line 917 of file Player.java.
{
        return username;
    }
References username.
Referenced by com.runehive.content.gambling.GambleManager.accept(), com.runehive.util.tools.LogReader.alreadyClaimedReferral(), com.runehive.net.session.LoginSession.authenticatedForumUser(), com.runehive.content.lms.LMSGame.canAttack(), com.runehive.content.clanchannel.channel.ClanChannelHandler.connect(), com.runehive.net.session.LoginSession.evaluate(), com.runehive.content.ai.AIDialogueHandler.handleAICommand(), com.runehive.content.ai.LazyAIManager.handleGandalfAIClick(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleLogout(), com.runehive.net.packet.in.InputStringPacketListener.handlePacket(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleRegionChange(), com.runehive.content.collectionlog.CollectionLogSaving.load(), com.runehive.content.gambling.GambleManager.open(), com.runehive.util.tools.LogPrinter.printReferralLog(), com.runehive.util.tools.LogPrinter.printToplist(), com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), com.runehive.content.collectionlog.CollectionLogSaving.save(), com.runehive.content.ai.LazyAIManager.showOpenAIConnectionOffer(), com.runehive.content.ai.LazyAIManager.startInactivityTimer(), com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse(), com.runehive.content.teleport.TeleportHandler.teleport(), toString(), unregister(), and com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents().
getVenomImmunity()
final MutableNumber com.runehive.game.world.entity.mob.player.Player.getVenomImmunity ()
Definition at line 909 of file Player.java.
{
        return venomImmunity;
    }
References venomImmunity.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.apply(), and com.runehive.game.task.impl.AntiVenomTask.execute().
getWeapon()
WeaponInterface com.runehive.game.world.entity.mob.player.Player.getWeapon ()
Definition at line 889 of file Player.java.
{
        return weapon;
    }
References weapon.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute().
hashCode()
int com.runehive.game.world.entity.mob.player.Player.hashCode ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 803 of file Player.java.
{
        return Objects.hash(getIndex(), username);
    }
References com.runehive.game.world.entity.Entity.getIndex(), and username.
isAutocast()
boolean com.runehive.game.world.entity.mob.player.Player.isAutocast ()
Definition at line 852 of file Player.java.
{
        return autocast != null;
    }
References autocast.
Referenced by com.runehive.game.world.entity.combat.magic.Autocast.clickButton(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.hit(), login(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), and com.runehive.game.world.entity.combat.magic.Autocast.reset().
isAutoRetaliate()
boolean com.runehive.game.world.entity.mob.player.Player.isAutoRetaliate ()
State of the mob's auto retaliate.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 824 of file Player.java.
{
        return settings.autoRetaliate;
    }
References settings.
isGambleLocked()
boolean com.runehive.game.world.entity.mob.player.Player.isGambleLocked ()
Definition at line 156 of file Player.java.
{
        return gambleLocked;
    }
References gambleLocked.
Referenced by com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
isSingleCast()
boolean com.runehive.game.world.entity.mob.player.Player.isSingleCast ()
Definition at line 840 of file Player.java.
{
        return singleCast != null;
    }
References singleCast.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.hit(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start().
isSpecialActivated()
boolean com.runehive.game.world.entity.mob.player.Player.isSpecialActivated ()
Definition at line 828 of file Player.java.
{
        return specialActivated;
    }
References specialActivated.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.start(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start().
isTeleblocked()
boolean com.runehive.game.world.entity.mob.player.Player.isTeleblocked ()
Definition at line 881 of file Player.java.
{
        return teleblockTimer.get() > 0;
    }
References teleblockTimer.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect.apply(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect.onLogin(), com.runehive.content.teleport.TeleportHandler.special(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
isValid()
boolean com.runehive.game.world.entity.mob.player.Player.isValid ()
Validates this npc based on its current region and registered state.
Returns
True if this npc is a valid log in the game world.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 784 of file Player.java.
{
        return (isBot || session != null) && super.isValid();
    }
References isBot, and session.
Referenced by com.runehive.content.combat.cannon.Cannon.addToRegion(), and com.runehive.content.combat.cannon.Cannon.removeFromRegion().
loadRegion()
void com.runehive.game.world.entity.mob.player.Player.loadRegion ()
Definition at line 525 of file Player.java.
{
        for(PlayerBirdHouseData playerBirdHouseData : birdHouseData) {
            if(Utility.goodDistance(playerBirdHouseData.birdhousePosition.getX(), playerBirdHouseData.birdhousePosition.getY(), getPosition().getX(), getPosition().getY(), 60)) {
                int objectId = playerBirdHouseData.birdhouseData.objectData[playerBirdHouseData.seedAmount >= 10 ? 1 : 0];
                send(new SendAddObject(new CustomGameObject(objectId, playerBirdHouseData.birdhousePosition, ObjectDirection.valueOf(playerBirdHouseData.rotation).get(), ObjectType.valueOf(playerBirdHouseData.type).get())));
            }
        }
        Activity.forActivity(this, minigame -> minigame.onRegionChange(this));
        Region[] surrounding = World.getRegions().getSurroundingRegions(getPosition());
        for (Region region : surrounding) {
            region.sendGroundItems(this);
            region.sendGameObjects(this);
            //Npc Face
            for (Npc npc : region.getNpcs(getHeight())) {
                if (!npc.getCombat().inCombat())
                    npc.face(npc.faceDirection);
            }
        }
        farming.regionChange(this);
        TrapManager.handleRegionChange(this);
        if (debug && PlayerRight.isDeveloper(this)) {
            send(new SendMessage("[REGION] Loaded new region.", MessageColor.DEVELOPER));
        }
    }
References birdHouseData, debug, com.runehive.util.MessageColor.DEVELOPER, farming, com.runehive.content.activity.Activity.forActivity(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.region.RegionManager.getSurroundingRegions(), com.runehive.game.world.entity.Entity.getX(), com.runehive.game.world.entity.Entity.getY(), com.runehive.util.Utility.goodDistance(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleRegionChange(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), send(), com.runehive.game.world.object.ObjectDirection.valueOf(), and com.runehive.game.world.object.ObjectType.valueOf().
login()
void com.runehive.game.world.entity.mob.player.Player.login () private
Definition at line 424 of file Player.java.
{
        positionChange = true;
        regionChange = true;
        onStep();
        skills.login();
        mobAnimation.reset();
        inventory.refresh();
        CombatSpell autocast = getAutocastSpell();
        equipment.login();
        settings.login();
        relations.onLogin();
        sendInitialPackets();
        playerAssistant.login();
        send(new SendSpecialEnabled(0));
        send(new SendConfig(301, 0));
        setAutocast(autocast);
        if (isAutocast() && equipment.hasWeapon()) {
            send(new SendConfig(43, 3));
            send(new SendConfig(108, 1));
        } else {
            setAutocast(null);
            send(new SendConfig(108, 0));
            send(new SendString("Spell", 18584));
        }
    }
References autocast, equipment, getAutocastSpell(), inventory, isAutocast(), com.runehive.game.world.entity.mob.Mob.mobAnimation, onStep(), playerAssistant, com.runehive.game.world.entity.mob.Mob.positionChange, com.runehive.game.world.entity.mob.Mob.regionChange, relations, send(), sendInitialPackets(), setAutocast(), settings, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by register().
logout() [1/2]
final void com.runehive.game.world.entity.mob.player.Player.logout ()
Definition at line 511 of file Player.java.
{
        logout(false);
    }
References logout().
Referenced by logout().
logout() [2/2]
final void com.runehive.game.world.entity.mob.player.Player.logout (boolean force)
Definition at line 515 of file Player.java.
{
        if (!canLogout() && !force) {
            return;
        }
        send(new SendLogout());
        setVisible(false);
        World.queueLogout(this);
    }
References canLogout(), com.runehive.game.world.World.queueLogout(), send(), and com.runehive.game.world.entity.Entity.setVisible().
message() [1/3]
void com.runehive.game.world.entity.mob.player.Player.message (boolean filtered, String... messages)
Definition at line 812 of file Player.java.
{
        for (String message : messages) {
            send(new SendMessage(message, filtered));
        }
    }
References message(), and send().
message() [2/3]
void com.runehive.game.world.entity.mob.player.Player.message (String message)
Definition at line 572 of file Player.java.
{
        send(new SendMessage(message));
    }
References message(), and send().
Referenced by com.runehive.content.gambling.GambleManager.accept(), com.runehive.content.wintertodt.Wintertodt.addPoints(), com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer.attack(), com.runehive.content.skill.impl.mining.Mining.attempt(), com.runehive.content.wintertodt.Wintertodt.award(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), com.runehive.content.lms.LMSGame.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), com.runehive.content.skill.impl.fishing.Fishing.canFish(), com.runehive.content.skill.impl.hunter.trap.TrapManager.canLay(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.canLogout(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.PureMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.PureRangeMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.canOtherAttack(), com.runehive.content.bot.botclass.impl.ZerkerMelee.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.canOtherAttack(), com.runehive.content.itemaction.impl.CelestialRing.charge(), com.runehive.content.itemaction.impl.CrawsBow.charge(), com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.ThammaronsSceptre.charge(), com.runehive.content.itemaction.impl.ViggorasChainmace.charge(), com.runehive.content.bags.impl.CoalBag.check(), com.runehive.content.bags.ItemBag.check(), com.runehive.content.itemaction.impl.CelestialRing.check(), com.runehive.content.itemaction.impl.CrawsBow.check(), com.runehive.content.itemaction.impl.MagmaHelm.check(), com.runehive.content.itemaction.impl.SerpentineHelm.check(), com.runehive.content.itemaction.impl.TanzaniteHelm.check(), com.runehive.content.itemaction.impl.ThammaronsSceptre.check(), com.runehive.content.itemaction.impl.TridentOfTheSeas.check(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.check(), com.runehive.content.itemaction.impl.ViggorasChainmace.check(), com.runehive.content.wintertodt.Wintertodt.chopRoot(), com.runehive.content.skill.impl.agility.Agility.clickButton(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.clanchannel.channel.ClanChannelHandler.connect(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.content.gambling.GambleManager.decline(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.skill.impl.hunter.trap.TrapManager.dismantle(), com.runehive.content.itemaction.impl.CelestialRing.drop(), com.runehive.content.itemaction.impl.CrawsBow.drop(), com.runehive.content.itemaction.impl.ThammaronsSceptre.drop(), com.runehive.content.itemaction.impl.ViggorasChainmace.drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.bags.ItemBag.empty(), com.runehive.content.itemaction.impl.DragonfireShield.empty(), com.runehive.content.combat.Killstreak.end(), com.runehive.content.itemaction.impl.DragonfireShield.equipment(), com.runehive.content.activity.impl.pestcontrol.PestControlLobby.exceededGameCapacity(), com.runehive.content.activity.impl.pestcontrol.PestControlLobby.exceededPlayerCapacity(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.wintertodt.Wintertodt.feedBrazier(), com.runehive.content.bags.ItemBag.fill(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), com.runehive.content.wintertodt.Wintertodt.fletch(), com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), com.runehive.content.Waypoints.getWaypoints(), com.runehive.content.lms.LMSGame.giveChestItems(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.content.ai.AIDialogueHandler.handleAICommand(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleRegionChange(), com.runehive.content.skill.impl.fishing.Fishing.hasFishingItems(), com.runehive.content.wintertodt.Wintertodt.healPyromancer(), com.runehive.content.activity.infernomobs.MejRah.Ranged.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.hit(), com.runehive.content.itemaction.impl.DragonfireShield.inspect(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.SerpentineHelm.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), message(), message(), message(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.wintertodt.Wintertodt.mixHerb(), com.runehive.content.lms.LMSGame.onDeath(), com.runehive.content.pet.Pets.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlLobby.onEnter(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.content.activity.impl.pestcontrol.PestControlLobby.onLeave(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.content.ProfileViewer.open(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask(), com.runehive.content.store.impl.SkillcapeStore.purchase(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), sendInitialPackets(), com.runehive.content.store.Store.sendPurchaseValue(), com.runehive.content.gambling.GambleManager.sendRequest(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), com.runehive.content.clanchannel.channel.ClanChannel.setName(), com.runehive.content.clanchannel.channel.ClanChannel.setSlogan(), com.runehive.content.clanchannel.channel.ClanChannel.setTag(), com.runehive.content.Waypoints.setWaypoint(), com.runehive.content.ai.LazyAIManager.showOpenAIConnectionOffer(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.content.skill.impl.mining.Mining.start(), com.runehive.content.store.currency.impl.ClanPointCurrency.takeCurrency(), com.runehive.content.wintertodt.Wintertodt.takeHerb(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), com.runehive.content.teleport.TeleportHandler.teleport(), com.runehive.content.itemaction.impl.MagmaHelm.uncharge(), com.runehive.content.itemaction.impl.SerpentineHelm.uncharge(), com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge(), com.runehive.content.itemaction.impl.TridentOfTheSeas.uncharge(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.uncharge(), com.runehive.content.skill.impl.crafting.Crafting.useItem(), com.runehive.content.skill.impl.fletching.Fletching.useItem(), and com.runehive.content.Yell.yell().
message() [3/3]
void com.runehive.game.world.entity.mob.player.Player.message (String... messages)
Definition at line 818 of file Player.java.
{
        for (String message : messages) {
            send(new SendMessage(message));
        }
    }
References message(), and send().
onStep()
void com.runehive.game.world.entity.mob.player.Player.onStep ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 651 of file Player.java.
{
        PluginManager.getDataBus().publish(this, new MovementEvent(getPlayer().getPosition().copy()));
        send(new SendMultiIcon(Area.inMulti(this) ? 1 : -1));
        if (Activity.evaluate(this, activity -> activity.onStep(this))) {
            return;
        }
        // Reset the options
        send(new SendPlayerOption(PlayerOption.GAMBLE_REQUEST, false, true));
        send(new SendPlayerOption(PlayerOption.ATTACK, false, true));
        send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
        send(new SendPlayerOption(PlayerOption.FOLLOW, false));
        send(new SendPlayerOption(PlayerOption.TRADE_REQUEST, false));
        send(new SendPlayerOption(PlayerOption.VIEW_PROFILE, false));
        if(Boundary.isIn(this, GambleManager.GAMBLING_ZONE)) {
            //send(new SendPlayerOption(PlayerOption.TRADE_REQUEST, false, true));
            send(new SendPlayerOption(PlayerOption.GAMBLE_REQUEST, false));
        }
        else if(LMSGame.inGameArea(this)){
            send(new SendPlayerOption(PlayerOption.ATTACK, true));
            if (interfaceManager.getWalkable() != 44660)
                interfaceManager.openWalkable(44660);
        }
        else if(Area.inLMSLobby(this) || Area.inLMSBuilding(this)) {
            if (interfaceManager.getWalkable() != 44650)
                interfaceManager.openWalkable(44650);
        }
        // pvp instance
        else if (pvpInstance) {
            if (hasPvPTimer) {
                send(new SendPlayerOption(PlayerOption.ATTACK, true));
                send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
            } else if (Area.inPvP(this)) {
                send(new SendString("<col=E68A00>" + playerAssistant.getCombatRange(), 23327));
                send(new SendPlayerOption(PlayerOption.ATTACK, true));
                send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
                if (interfaceManager.getWalkable() != 23400) {
                    interfaceManager.openWalkable(23400);
                }
                return;
            } else {
                if (!hasPvPTimer && getCombat().inCombat()) {
                    World.schedule(new PvPTimerTask(this));
                } else {
                    send(new SendString("<col=36CF4D>Safe", 23327));
                    send(new SendPlayerOption(PlayerOption.ATTACK, false, true));
                    send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
                }
            }
            if (interfaceManager.getWalkable() != 23410) {
                interfaceManager.openWalkable(23410);
            }
            // wilderness
        } else if (Area.inWilderness(this)) {
            int modY = getPosition().getY() > 6400 ? getPosition().getY() - 6400 : getPosition().getY();
            wilderness = (((modY - 3521) / 8) + 1);
            send(new SendString("Level " + wilderness, 23327));
            send(new SendPlayerOption(PlayerOption.ATTACK, true));
            send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
            if (interfaceManager.getWalkable() != 23400)
                interfaceManager.openWalkable(23400);
            // duel arena lobby
        } else if (Area.inDuelArenaLobby(this)) {
            send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false));
            send(new SendPlayerOption(PlayerOption.ATTACK, false, true));
            if (interfaceManager.getWalkable() != 201)
                interfaceManager.openWalkable(201);
            // duel arena
        } else if (Area.inDuelArena(this) || Area.inDuelObsticleArena(this)) {
            send(new SendPlayerOption(PlayerOption.ATTACK, true));
            send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
            if (interfaceManager.getWalkable() != 201)
                interfaceManager.openWalkable(201);
            // event arena
      /*  } else if (Area.inEventArena(this)) {
            send(new SendPlayerOption(PlayerOption.ATTACK, true));
            send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
            send(new SendString("Fun PK", 23327));
            if (interfaceManager.getWalkable() != 23400)
                interfaceManager.openWalkable(23400);*/
            //
        } else if (Area.inSuperDonatorZone(this) && (Area.inRegularDonatorZone(this) && !PlayerRight.isDonator(this))) {
            move(Config.DEFAULT_POSITION);
            send(new SendMessage("You're not supposed to be here!"));
            // clear
        } else if (!inActivity()) {
            send(new SendPlayerOption(PlayerOption.GAMBLE_REQUEST, false, true));
            send(new SendPlayerOption(PlayerOption.ATTACK, false, true));
            send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
            send(new SendPlayerOption(PlayerOption.FOLLOW, false));
            send(new SendPlayerOption(PlayerOption.TRADE_REQUEST, false));
            send(new SendPlayerOption(PlayerOption.VIEW_PROFILE, false));
//
//            if (!interfaceManager.isClear())
                interfaceManager.close();
            if (wilderness > 0)
                wilderness = 0;
        }
    }
References com.runehive.game.world.entity.mob.Mob.activity, com.runehive.game.world.entity.mob.player.PlayerOption.ATTACK, com.runehive.Config.DEFAULT_POSITION, com.runehive.game.world.entity.mob.player.PlayerOption.DUEL_REQUEST, com.runehive.content.activity.Activity.evaluate(), com.runehive.game.world.entity.mob.player.PlayerOption.FOLLOW, com.runehive.game.world.entity.mob.player.PlayerOption.GAMBLE_REQUEST, com.runehive.content.gambling.GambleManager.GAMBLING_ZONE, getCombat(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Position.getY(), hasPvPTimer, com.runehive.game.world.entity.mob.Mob.inActivity(), com.runehive.game.world.position.Area.inDuelArena(), com.runehive.game.world.position.Area.inDuelArenaLobby(), com.runehive.game.world.position.Area.inDuelObsticleArena(), com.runehive.content.lms.LMSGame.inGameArea(), com.runehive.game.world.position.Area.inLMSBuilding(), com.runehive.game.world.position.Area.inLMSLobby(), com.runehive.game.world.position.Area.inMulti(), com.runehive.game.world.position.Area.inPvP(), com.runehive.game.world.position.Area.inRegularDonatorZone(), com.runehive.game.world.position.Area.inSuperDonatorZone(), interfaceManager, com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.mob.player.PlayerRight.isDonator(), com.runehive.game.world.position.Boundary.isIn(), com.runehive.game.world.entity.mob.Mob.move(), playerAssistant, com.runehive.game.event.bus.PlayerDataBus.publish(), pvpInstance, com.runehive.game.world.World.schedule(), send(), com.runehive.game.world.entity.mob.player.PlayerOption.TRADE_REQUEST, com.runehive.game.world.entity.mob.player.PlayerOption.VIEW_PROFILE, and wilderness.
Referenced by login().
pickup()
void com.runehive.game.world.entity.mob.player.Player.pickup (Item item, Position position)
Definition at line 557 of file Player.java.
{
        Waypoint waypoint = new PickupWaypoint(this, item, position);
        if (cachedWaypoint == null || (!cachedWaypoint.isRunning() || !waypoint.equals(cachedWaypoint))) {
            resetWaypoint();
            action.clearNonWalkableActions();
            movement.reset();
            getCombat().reset();
            World.schedule(cachedWaypoint = waypoint);
        }
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.cachedWaypoint, com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.equals(), getCombat(), com.runehive.game.world.entity.mob.Mob.movement, com.runehive.game.world.entity.Entity.position, com.runehive.game.world.entity.mob.Mob.resetWaypoint(), and com.runehive.game.world.World.schedule().
register()
void com.runehive.game.world.entity.mob.player.Player.register ()
Registers an entity to the World.
Reimplemented from com.runehive.game.world.entity.Entity.
Reimplemented in com.runehive.content.bot.PlayerBot.
Definition at line 577 of file Player.java.
{
        if (!isRegistered() && !World.getPlayers().contains(this)) {
            setRegistered(World.getPlayers().add(this));
            setPosition(getPosition());
            login();
            logger.info("[REGISTERED]: " + Utility.formatName(getName()) + " [" + lastHost + "]");
            EventDispatcher.execute(this, new LogInEvent());
        }
    }
References com.runehive.content.event.EventDispatcher.execute(), com.runehive.util.Utility.formatName(), getName(), com.runehive.game.world.World.getPlayers(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.isRegistered(), lastHost, logger, login(), com.runehive.game.world.entity.Entity.setPosition(), and com.runehive.game.world.entity.Entity.setRegistered().
Referenced by com.runehive.game.world.World.dequeLogins().
removeFromRegion()
void com.runehive.game.world.entity.mob.player.Player.removeFromRegion (Region region)
Removes this entity from the specified region.
Parameters
region The region.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 625 of file Player.java.
{
        region.removePlayer(this);
    }
send()
void com.runehive.game.world.entity.mob.player.Player.send (OutgoingPacket encoder)
Definition at line 420 of file Player.java.
{
        encoder.execute(this);
    }
References com.runehive.net.packet.OutgoingPacket.execute().
Referenced by com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.content.famehall.FameHandler.activate(), com.runehive.content.Obelisks.activate(), com.runehive.content.store.impl.PersonalStore.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.content.triviabot.TriviaBot.answer(), com.runehive.content.triviabot.TriviaBot.answered(), com.runehive.content.RoyaltyProgram.append(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.apply(), com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect.apply(), com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.apply(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.attack(), com.runehive.content.clanchannel.channel.ClanChannelHandler.attemptConnection(), com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.canAttack(), com.runehive.content.lms.LMSGame.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.canAttack(), com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), com.runehive.util.parser.old.defs.EquipmentRequirement.canEquip(), canLogout(), com.runehive.content.skill.impl.HarvestingSkillAction.canRun(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.canTeleport(), com.runehive.content.store.impl.PersonalStore.changeName(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), com.runehive.content.clanchannel.ClanMember.chat(), com.runehive.content.itemaction.impl.ToxicBlowpipe.check(), com.runehive.util.Utility.checkRequirements(), com.runehive.content.dialogue.impl.RoyalKingDialogue.claim(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel(), com.runehive.content.clanchannel.channel.ClanChannelHandler.clean(), com.runehive.content.skill.guides.SkillGuides.cleanInterface(), com.runehive.content.activity.panel.ActivityPanel.clear(), com.runehive.content.skill.impl.smithing.Smelting.clearInterfaces(), com.runehive.content.skill.impl.crafting.impl.Glass.click(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.crafting.impl.Tanning.click(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.content.skill.impl.fletching.Fletching.clickButton(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.mining.Mining.clickObject(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.smithing.Smithing.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.achievement.AchievementHandler.completeAll(), com.runehive.content.clanchannel.channel.ClanChannelHandler.connect(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.contains(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.clanchannel.channel.ClanChannel.create(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.pet.Pets.dialogue(), com.runehive.content.itemaction.impl.SerpentineHelm.dismantle(), com.runehive.content.DropDisplay.display(), com.runehive.content.skill.impl.construction.BuildableInterface.display(), com.runehive.content.teleport.TeleportHandler.display(), com.runehive.content.simulator.DropSimulator.drawList(), com.runehive.content.combat.cannon.CannonManager.drop(), com.runehive.content.skill.impl.woodcutting.BirdsNest.drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.store.impl.PersonalStore.edit(), com.runehive.content.combat.cannon.CannonManager.empty(), com.runehive.net.packet.out.SendAddObject.encode(), com.runehive.net.packet.out.SendGraphic.encode(), com.runehive.net.packet.out.SendGroundItem.encode(), com.runehive.net.packet.out.SendObjectAnimation.encode(), com.runehive.net.packet.out.SendPlayerUpdate.encode(), com.runehive.net.packet.out.SendProjectile.encode(), com.runehive.net.packet.out.SendProjectileTestPacket.encode(), com.runehive.net.packet.out.SendRemoveGroundItem.encode(), com.runehive.net.packet.out.SendRemoveObject.encode(), com.runehive.net.packet.out.SendSkill.encode(), com.runehive.content.emote.Skillcape.equip(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.execute(), com.runehive.content.teleport.TeleportHandler.favorite(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fifthAction(), com.runehive.game.plugin.PluginContext.firstClickObject(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.game.plugin.PluginContext.handleButtonClickEvent(), com.runehive.game.plugin.PluginContext.handleDropItemEvent(), com.runehive.content.lms.LMSGame.handleFogDamage(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.plugin.PluginContext.handleItemClickEvent(), com.runehive.game.plugin.PluginContext.handleItemContainerContextMenuEvent(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnGround(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnItem(), com.runehive.game.plugin.PluginContext.handleItemOnItemEvent(), com.runehive.game.plugin.PluginContext.handleItemOnNpcEvent(), com.runehive.game.plugin.PluginContext.handleItemOnObjectEvent(), com.runehive.game.plugin.PluginContext.handleItemOnPlayerEvent(), com.runehive.content.gambling.GambleManager.handleModeSelection(), com.runehive.game.plugin.PluginContext.handleNpcClickEvent(), com.runehive.game.plugin.PluginContext.handleObjectClickEvent(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.net.packet.in.ChatMessagePacketListener.handlePacket(), com.runehive.net.packet.in.ColorPacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.RegionChangePacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.game.plugin.PluginContext.handlePickupItemEvent(), com.runehive.game.world.entity.combat.attack.listener.item.AhrimListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ToragListener.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Shockwave.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.content.itemaction.impl.CelestialRing.inventory(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), com.runehive.content.skill.impl.smithing.Smithing.itemContainerAction(), com.runehive.content.store.impl.DefaultStore.itemContainerAction(), com.runehive.content.store.impl.PersonalStore.itemContainerAction(), com.runehive.content.itemaction.impl.CelestialRing.itemOnItem(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.ToxicBlowpipe.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.game.world.World.kickPlayer(), com.runehive.content.combat.cannon.CannonManager.load(), com.runehive.content.itemaction.impl.ToxicBlowpipe.load(), com.runehive.content.collectionlog.CollectionLog.loadPage(), loadRegion(), login(), com.runehive.content.collectionlog.CollectionLog.logItem(), logout(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manage(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember(), message(), message(), message(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.message(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.content.consume.PotionData.onAntiPoisonEffect(), com.runehive.game.plugin.PluginContext.onClick(), com.runehive.content.pet.Pets.onDeath(), com.runehive.content.consume.PotionData.onEnergyEffect(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.game.action.impl.ScatterAshAction.onExecute(), com.runehive.content.skill.impl.agility.obstacle.impl.RopeSwingInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onExecution(), com.runehive.content.pet.Pets.onObtain(), com.runehive.game.world.items.containers.bank.DonatorDeposit.onRefresh(), com.runehive.game.world.items.containers.impl.LostUntradeables.onRefresh(), com.runehive.content.pet.Pets.onSpawn(), onStep(), com.runehive.content.famehall.FameHandler.open(), com.runehive.content.gambling.GambleManager.open(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.Obelisks.open(), com.runehive.content.ProfileViewer.open(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.simulator.DropSimulator.open(), com.runehive.content.skill.impl.crafting.impl.Jewellery.open(), com.runehive.content.skill.impl.crafting.impl.Tanning.open(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.content.teleport.TeleportHandler.open(), com.runehive.content.WellOfGoodwill.open(), com.runehive.content.pet.Pets.openInsurance(), com.runehive.content.skill.guides.SkillGuides.openInterface(), com.runehive.content.skill.impl.smithing.Smelting.openInterface(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.pet.Pets.openLostPets(), com.runehive.content.store.impl.PersonalStore.openMenu(), com.runehive.content.store.impl.PersonalStore.openPanel(), com.runehive.content.clanchannel.content.ClanShowcase.openShowcase(), com.runehive.content.combat.cannon.CannonManager.pickup(), com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.process(), com.runehive.content.store.Store.purchase(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.tittle.TitleManager.redeem(), com.runehive.content.emote.EmoteHandler.refresh(), com.runehive.content.skill.impl.construction.BuildableInterface.refresh(), com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), com.runehive.content.StarterKit.refresh(), com.runehive.content.store.impl.DefaultStore.refresh(), com.runehive.content.store.impl.RecipeForDisasterStore.refresh(), com.runehive.content.store.impl.SkillcapeStore.refresh(), com.runehive.content.tittle.TitleManager.refresh(), com.runehive.game.world.items.containers.ItemContainer.refresh(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.removeOn(), com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.removeOn(), com.runehive.content.gambling.GambleManager.reset(), com.runehive.content.lms.LMSGame.reset(), com.runehive.content.tittle.TitleManager.reset(), com.runehive.game.world.entity.combat.magic.Autocast.reset(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.reset(), com.runehive.content.itemaction.impl.MagmaHelm.restore(), com.runehive.content.itemaction.impl.TanzaniteHelm.restore(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.content.DropDisplay.search(), com.runehive.content.famehall.FameHandler.search(), com.runehive.content.skill.impl.woodcutting.BirdsNest.search(), com.runehive.game.plugin.PluginContext.secondClickObject(), com.runehive.content.clanchannel.content.ClanShowcase.select(), com.runehive.content.collectionlog.CollectionLog.selectLog(), com.runehive.content.store.Store.sell(), com.runehive.content.wintertodt.Wintertodt.send(), com.runehive.content.collectionlog.CollectionLog.sendButtons(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), com.runehive.content.dialogue.impl.RoyalKingDialogue.sendDialogues(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), com.runehive.game.world.region.RegionBlock.sendGameObjects(), com.runehive.game.world.region.RegionBlock.sendGroundItems(), sendInitialPackets(), com.runehive.content.skill.impl.farming.zones.FarmingZone.sendPatchConfigs(), com.runehive.content.gambling.GambleManager.sendRequest(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.content.store.Store.sendSellValue(), com.runehive.game.world.entity.skill.SkillManager.sendSkills(), sequence(), com.runehive.content.activity.impl.duelarena.DuelRule.set(), com.runehive.game.world.entity.combat.magic.Autocast.setAutocast(), com.runehive.content.skill.impl.slayer.SlayerTab.setFrame(), com.runehive.content.tradingpost.TradingPostListing.setPrice(), com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.shoulderShot(), com.runehive.content.clanchannel.channel.ClanManagement.showBanned(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.showDuelRulesOnSecondScreen(), com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface(), com.runehive.content.activity.impl.duelarena.DuelRule.showRules(), com.runehive.content.emote.Emote.skillcape(), com.runehive.content.skill.impl.smithing.Smelting.smelt(), com.runehive.content.activity.inferno.InfernoBoss.spawnbosswave(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.gambling.GambleManager.start(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.store.currency.impl.DonatorPointCurrency.takeCurrency(), com.runehive.content.store.currency.impl.LMSPointCurrency.takeCurrency(), com.runehive.content.store.currency.impl.MageArenaCurrency.takeCurrency(), com.runehive.content.store.currency.impl.PestPointCurrency.takeCurrency(), com.runehive.content.store.currency.impl.PrestigePointCurrency.takeCurrency(), com.runehive.content.store.currency.impl.SkillingPointCurrency.takeCurrency(), com.runehive.content.store.currency.impl.SlayerPointCurrency.takeCurrency(), com.runehive.content.store.currency.impl.VotePointCurrency.takeCurrency(), com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), teleblock(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), com.runehive.content.teleport.TeleportHandler.teleport(), com.runehive.content.activity.impl.barrows.BarrowsUtility.teleportPlayer(), com.runehive.content.clanchannel.channel.ClanChannelHandler.testPassword(), com.runehive.game.plugin.PluginContext.thirdClickObject(), com.runehive.content.store.impl.DefaultStore.StoreRestockTask.tick(), com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick(), com.runehive.content.clanchannel.channel.ClanChannel.unban(), com.runehive.content.itemaction.impl.MagmaHelm.uncharge(), com.runehive.content.itemaction.impl.SerpentineHelm.uncharge(), com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.unload(), com.runehive.content.emote.EmoteHandler.unlock(), com.runehive.content.emote.EmoteHandler.unlockAll(), unregister(), com.runehive.content.activity.panel.ActivityPanel.update(), com.runehive.content.clanchannel.channel.ClanChannelHandler.updateMemberList(), com.runehive.game.world.entity.skill.SkillManager.updateSkill(), com.runehive.content.emote.EmoteHandler.updateSkillcape(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), com.runehive.content.skill.impl.crafting.Crafting.useItem(), com.runehive.content.skill.impl.fletching.Fletching.useItem(), com.runehive.content.skill.impl.herblore.Herblore.useItem(), com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem(), com.runehive.content.activity.impl.duelarena.DuelRule.validateEquipmentRules(), com.runehive.content.gambling.GambleManager.withdraw(), and com.runehive.content.Yell.yell().
sendInitialPackets()
void com.runehive.game.world.entity.mob.player.Player.sendInitialPackets () private
Definition at line 462 of file Player.java.
{
        int players = World.getPlayerCount();
        send(new SendRunEnergy());
        send(new SendPlayerDetails());
        send(new SendCameraReset());
        send(new SendExpCounter(skills.getExpCounter()));
        World.sendMessage("<img=15> " +getPlayer().getName()+ " has logged in.");
        message(true, String.format("Welcome to %s. ", Config.SERVER_NAME));
        message(true, "We are currently in early access.");
        if (Config.DOUBLE_EXPERIENCE) {
            message("Double experience is currently active!");
        }
        if (players > GameSaver.MAX_PLAYERS) {
            GameSaver.MAX_PLAYERS = players;
        }
        if (needsStarter) {
            newPlayer = true;
        }
        playerAssistant.welcomeScreen();
    }
References com.runehive.Config.DOUBLE_EXPERIENCE, getName(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.World.getPlayerCount(), com.runehive.util.GameSaver.MAX_PLAYERS, message(), needsStarter, newPlayer, playerAssistant, send(), com.runehive.game.world.World.sendMessage(), com.runehive.Config.SERVER_NAME, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by login().
sequence()
void com.runehive.game.world.entity.mob.player.Player.sequence ()
The method which is invoked every tick.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Reimplemented in com.runehive.content.bot.PlayerBot.
Definition at line 630 of file Player.java.
{
        if (!idle) {
            playTime++;
        }
        action.sequence();
        playerAssistant.sequence();
        sequence++;
        // Dialogue camera tick
        com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick(this);
        if(Area.inLMSLobby(this) || Area.inLMSBuilding(this)) {
            send(new SendString("Next Game: ", 44654));
            send(new SendString("" + ((LMSLobbyEvent.lobbyTicks * 600) / 1000), 44655));
            send(new SendString("" + LMSLobby.currentGameType.getClass().getSimpleName(), 44657));
            send(new SendString("<col="+(LMSLobby.lobbyMembers.size() >= LMSLobby.requiredPlayers ? "65280" : "ff0000")+">" + LMSLobby.lobbyMembers.size() + "/" + LMSLobby.maxPlayers + "</col>", 44659));
        }
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.content.lms.lobby.LMSLobby.currentGameType, idle, com.runehive.game.world.position.Area.inLMSBuilding(), com.runehive.game.world.position.Area.inLMSLobby(), com.runehive.content.lms.lobby.LMSLobby.lobbyMembers, com.runehive.content.lms.lobby.LMSLobbyEvent.lobbyTicks, com.runehive.content.lms.lobby.LMSLobby.maxPlayers, playerAssistant, playTime, com.runehive.content.lms.lobby.LMSLobby.requiredPlayers, send(), and sequence.
setAntifireDetail()
void com.runehive.game.world.entity.mob.player.Player.setAntifireDetail (AntifireDetails antifireDetails)
Definition at line 901 of file Player.java.
{
        this.antifireDetails = antifireDetails;
    }
References antifireDetails.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.apply(), and com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.process().
setAutocast()
void com.runehive.game.world.entity.mob.player.Player.setAutocast (CombatSpell autocast)
Definition at line 860 of file Player.java.
{
        this.autocast = autocast;
    }
References autocast.
Referenced by login(), com.runehive.game.world.entity.combat.magic.Autocast.reset(), and com.runehive.game.world.entity.combat.magic.Autocast.setAutocast().
setCollectionLog()
void com.runehive.game.world.entity.mob.player.Player.setCollectionLog (CollectionLog collectionLog)
Definition at line 198 of file Player.java.
{
        this.collectionLog = collectionLog;
    }
References collectionLog.
setCombatSpecial()
void com.runehive.game.world.entity.mob.player.Player.setCombatSpecial (CombatSpecial special)
Definition at line 836 of file Player.java.
{
        this.combatSpecial = special;
    }
setGambleLock()
void com.runehive.game.world.entity.mob.player.Player.setGambleLock (boolean gambleLocked)
Definition at line 152 of file Player.java.
{
        this.gambleLocked = gambleLocked;
    }
References gambleLocked.
Referenced by com.runehive.content.gambling.GambleManager.reset(), and com.runehive.content.gambling.GambleManager.start().
setLastModification()
void com.runehive.game.world.entity.mob.player.Player.setLastModification (long lastModification)
Definition at line 142 of file Player.java.
{
        this.lastModification = lastModification;
    }
References lastModification.
Referenced by com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.gambling.GambleManager.handleModeSelection(), and com.runehive.content.gambling.GambleManager.withdraw().
setMemberId()
void com.runehive.game.world.entity.mob.player.Player.setMemberId (int memberId)
Definition at line 921 of file Player.java.
{
        this.memberId = memberId;
    }
References memberId.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser().
setPassword()
void com.runehive.game.world.entity.mob.player.Player.setPassword (String password)
Definition at line 941 of file Player.java.
{
        this.password = password;
    }
References password.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser(), and com.runehive.net.session.LoginSession.handleUserLoginDetails().
setSceneBaseChunks()
void com.runehive.game.world.entity.mob.player.Player.setSceneBaseChunks (int chunkX, int chunkY)
Definition at line 966 of file Player.java.
{
        this.sceneBaseChunkX = chunkX;
        this.sceneBaseChunkY = chunkY;
    }
Referenced by com.runehive.net.packet.out.SendMapRegion.encode().
setSession()
void com.runehive.game.world.entity.mob.player.Player.setSession (GameSession session)
Definition at line 933 of file Player.java.
{
        this.session = Optional.of(session);
        final String host = session.getHost();
        this.lastHost = host;
        this.hostList.add(host);
    }
References session.
Referenced by com.runehive.net.session.LoginSession.handleUserLoginDetails().
setSingleCast()
void com.runehive.game.world.entity.mob.player.Player.setSingleCast (CombatSpell singleCast)
Definition at line 848 of file Player.java.
{
        this.singleCast = singleCast;
    }
References singleCast.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start().
setSpecialActivated()
void com.runehive.game.world.entity.mob.player.Player.setSpecialActivated (boolean activated)
Definition at line 832 of file Player.java.
{
        this.specialActivated = activated;
    }
Referenced by com.runehive.content.bot.PlayerBot.postDeath().
setUsername()
void com.runehive.game.world.entity.mob.player.Player.setUsername (String username)
Definition at line 415 of file Player.java.
{
        this.username = username;
        this.usernameLong = Utility.nameToLong(username);
    }
References com.runehive.util.Utility.nameToLong(), and username.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser(), and Player().
setWeapon()
void com.runehive.game.world.entity.mob.player.Player.setWeapon (WeaponInterface weapon)
Definition at line 893 of file Player.java.
{
        this.weapon = weapon;
    }
References weapon.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute().
teleblock()
void com.runehive.game.world.entity.mob.player.Player.teleblock (int time)
Definition at line 870 of file Player.java.
{
        if (time <= 0 || (teleblockTimer.get() > 0)) {
            return;
        }
        teleblockTimer.set(time);
        send(new SendMessage("A teleblock spell has been casted on you!"));
        send(new SendWidget(SendWidget.WidgetType.TELEBLOCK, (int) ((double) teleblockTimer.get() / 1000D * 600D)));
        World.schedule(new TeleblockTask(this));
    }
References com.runehive.game.world.World.schedule(), send(), com.runehive.net.packet.out.SendWidget.WidgetType.TELEBLOCK, and teleblockTimer.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect.apply().
toSceneLocalX() [1/2]
int com.runehive.game.world.entity.mob.player.Player.toSceneLocalX (int worldX)
Definition at line 972 of file Player.java.
{
        return worldX - (sceneBaseChunkX * 8);
    }
References sceneBaseChunkX.
Referenced by com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.shoulderShot(), and toSceneLocalX().
toSceneLocalX() [2/2]
int com.runehive.game.world.entity.mob.player.Player.toSceneLocalX (Position pos)
Definition at line 980 of file Player.java.
{
        return toSceneLocalX(pos.getX());
    }
References com.runehive.game.world.position.Position.getX(), and toSceneLocalX().
toSceneLocalY() [1/2]
int com.runehive.game.world.entity.mob.player.Player.toSceneLocalY (int worldY)
Definition at line 976 of file Player.java.
{
        return worldY - (sceneBaseChunkY * 8);
    }
References sceneBaseChunkY.
Referenced by com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.shoulderShot(), and toSceneLocalY().
toSceneLocalY() [2/2]
int com.runehive.game.world.entity.mob.player.Player.toSceneLocalY (Position pos)
Definition at line 984 of file Player.java.
{
        return toSceneLocalY(pos.getY());
    }
References com.runehive.game.world.position.Position.getY(), and toSceneLocalY().
toString()
String com.runehive.game.world.entity.mob.player.Player.toString ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 808 of file Player.java.
{
        return String.format("Player[index=%d member_id=%d username=%s pos=%s bot=%b]", getIndex(), getMemberId(), getUsername(), getPosition(), isBot);
    }
References com.runehive.game.world.entity.Entity.getIndex(), getMemberId(), com.runehive.game.world.entity.Entity.getPosition(), getUsername(), and isBot.
unregister()
void com.runehive.game.world.entity.mob.player.Player.unregister ()
Unregisters an entity from the World.
Reimplemented from com.runehive.game.world.entity.Entity.
Reimplemented in com.runehive.content.bot.PlayerBot.
Definition at line 590 of file Player.java.
{
        if (!isRegistered()) {
            return;
        }
        if (!World.getPlayers().contains(this)) {
            return;
        }
        if (LMSGame.isActivePlayer(this))
            LMSGame.onDeath(this, true);
        World.sendMessage("<img=15> " +getPlayer().getName()+ " has logged out.");
        send(new SendLogout());
        Activity.forActivity(this, minigame -> minigame.onLogout(this));
        relations.updateLists(false);
        TrapManager.handleLogout(this);
        ClanChannelHandler.disconnect(this, true);
        interfaceManager.close();
        new Highscores(this).execute();
        //HighscoreService.saveHighscores(this);
        World.cancelTask(this, true);
        Pets.onLogout(this);
        CollectionLogSaving.save(this);
        World.getPlayers().remove((Player) destroy());
        getGambling().decline(this);
        com.runehive.content.ai.LazyAIManager.clearPlayerConsent(getUsername());
        logger.info(String.format("[UNREGISTERED]: %s [%s]", getName(), lastHost));
    }
References com.runehive.game.world.World.cancelTask(), com.runehive.content.gambling.GambleManager.decline(), com.runehive.game.world.entity.Entity.destroy(), com.runehive.content.clanchannel.channel.ClanChannelHandler.disconnect(), com.runehive.game.service.Highscores.execute(), com.runehive.content.activity.Activity.forActivity(), getGambling(), getName(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.World.getPlayers(), getUsername(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleLogout(), interfaceManager, com.runehive.content.lms.LMSGame.isActivePlayer(), com.runehive.game.world.entity.Entity.isRegistered(), lastHost, logger, com.runehive.content.lms.LMSGame.onDeath(), com.runehive.content.pet.Pets.onLogout(), Player(), relations, com.runehive.content.collectionlog.CollectionLogSaving.save(), send(), and com.runehive.game.world.World.sendMessage().
Member Data Documentation
achievedSkills
int [] com.runehive.game.world.entity.mob.player.Player.achievedSkills = new int[7]
Definition at line 258 of file Player.java.
activityLogger
final ActivityLogger com.runehive.game.world.entity.mob.player.Player.activityLogger = new ActivityLogger(this)
Definition at line 347 of file Player.java.
Referenced by com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.game.plugin.PluginContext.onClick(), and com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath().
aggressionTimer
Stopwatch com.runehive.game.world.entity.mob.player.Player.aggressionTimer = Stopwatch.start()
Definition at line 310 of file Player.java.
Referenced by addToRegion(), and com.runehive.game.world.entity.combat.CombatTarget.checkAggression().
agsCharges
int com.runehive.game.world.entity.mob.player.Player.agsCharges = 750
Definition at line 263 of file Player.java.
answeredTrivias
int com.runehive.game.world.entity.mob.player.Player.answeredTrivias
Definition at line 183 of file Player.java.
antifireDetails
AntifireDetails com.runehive.game.world.entity.mob.player.Player.antifireDetails private
Definition at line 229 of file Player.java.
Referenced by getAntifireDetails(), and setAntifireDetail().
appearance
Appearance com.runehive.game.world.entity.mob.player.Player.appearance = Config.DEFAULT_APPEARANCE
Definition at line 215 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), getAppearance(), and com.runehive.content.bot.PlayerBot.PlayerBot().
autocast
CombatSpell com.runehive.game.world.entity.mob.player.Player.autocast
Definition at line 213 of file Player.java.
Referenced by getAutocastSpell(), isAutocast(), login(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), and setAutocast().
bank
final Bank com.runehive.game.world.entity.mob.player.Player.bank = new Bank(this)
Definition at line 327 of file Player.java.
Referenced by com.runehive.content.gambling.GambleManager.decline(), com.runehive.content.gambling.GambleManager.give(), and com.runehive.content.pet.Pets.onObtain().
bankPin
final BankPin com.runehive.game.world.entity.mob.player.Player.bankPin = new BankPin(this)
Definition at line 329 of file Player.java.
bankVault
final BankVault com.runehive.game.world.entity.mob.player.Player.bankVault = new BankVault(this)
Definition at line 328 of file Player.java.
Referenced by com.runehive.content.achievement.AchievementHandler.activate(), and com.runehive.content.triviabot.TriviaBot.answered().
barrowKills
boolean [] com.runehive.game.world.entity.mob.player.Player.barrowKills = new boolean[BrotherData.values().length]
Definition at line 240 of file Player.java.
Referenced by com.runehive.content.activity.impl.barrows.BarrowsUtility.getHiddenBrother().
barrowsKillCount
int com.runehive.game.world.entity.mob.player.Player.barrowsKillCount
Definition at line 246 of file Player.java.
birdHouseData
List<PlayerBirdHouseData> com.runehive.game.world.entity.mob.player.Player.birdHouseData = new ArrayList<>()
Definition at line 129 of file Player.java.
Referenced by loadRegion(), and com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot().
blowpipeDarts
Item com.runehive.game.world.entity.mob.player.Player.blowpipeDarts
Definition at line 374 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.content.itemaction.impl.ToxicBlowpipe.check(), com.runehive.content.itemaction.impl.ToxicBlowpipe.load(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge(), and com.runehive.content.itemaction.impl.ToxicBlowpipe.unload().
blowpipeScales
float com.runehive.game.world.entity.mob.player.Player.blowpipeScales
Definition at line 373 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.check(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), and com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge().
buttonDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.buttonDelay = Stopwatch.start()
Definition at line 300 of file Player.java.
celestialRingCharges
int com.runehive.game.world.entity.mob.player.Player.celestialRingCharges
Definition at line 383 of file Player.java.
Referenced by com.runehive.content.itemaction.impl.CelestialRing.check(), and com.runehive.content.itemaction.impl.CelestialRing.drop().
chatBoxItemDialogue
ChatBoxItemDialogue com.runehive.game.world.entity.mob.player.Player.chatBoxItemDialogue
Definition at line 220 of file Player.java.
chatMessage
Optional<ChatMessage> com.runehive.game.world.entity.mob.player.Player.chatMessage = Optional.empty() private
Definition at line 221 of file Player.java.
Referenced by chat(), and getChatMessage().
clan
String com.runehive.game.world.entity.mob.player.Player.clan = ""
Definition at line 294 of file Player.java.
clanChannel
ClanChannel com.runehive.game.world.entity.mob.player.Player.clanChannel
Definition at line 293 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), com.runehive.content.store.currency.impl.ClanPointCurrency.currencyAmount(), com.runehive.content.clanchannel.channel.ClanChannelHandler.disconnect(), forClan(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manage(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember(), com.runehive.content.clanchannel.channel.ClanChannelHandler.onLogin(), com.runehive.content.store.currency.impl.ClanPointCurrency.recieveCurrency(), com.runehive.content.clanchannel.channel.ClanChannelHandler.sendConnectionWarning(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), com.runehive.content.clanchannel.channel.ClanChannel.splitLoot(), com.runehive.content.ProfileViewer.string(), and com.runehive.content.store.currency.impl.ClanPointCurrency.takeCurrency().
clanTag
String com.runehive.game.world.entity.mob.player.Player.clanTag = ""
Definition at line 295 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.content.bot.PlayerBot.PlayerBot().
clanTagColor
String com.runehive.game.world.entity.mob.player.Player.clanTagColor = ""
Definition at line 296 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.content.bot.PlayerBot.PlayerBot().
clanViewer
final ClanViewer com.runehive.game.world.entity.mob.player.Player.clanViewer = new ClanViewer(this)
Definition at line 315 of file Player.java.
Referenced by com.runehive.content.dialogue.impl.ClanmasterDialogue.sendDialogues(), com.runehive.content.clanchannel.channel.ClanChannel.setName(), com.runehive.content.clanchannel.channel.ClanChannel.setSlogan(), and com.runehive.content.clanchannel.channel.ClanChannel.setTag().
coalBag
CoalBag com.runehive.game.world.entity.mob.player.Player.coalBag = new CoalBag()
Definition at line 191 of file Player.java.
collectionLog
CollectionLog com.runehive.game.world.entity.mob.player.Player.collectionLog = new CollectionLog() private
Definition at line 196 of file Player.java.
Referenced by setCollectionLog().
collectionLogPageOpen
CollectionLogPage com.runehive.game.world.entity.mob.player.Player.collectionLogPageOpen = null
Definition at line 193 of file Player.java.
Referenced by com.runehive.content.collectionlog.CollectionLog.loadPage(), com.runehive.content.collectionlog.CollectionLog.open(), and com.runehive.content.collectionlog.CollectionLog.selectLogButton().
collectionLogView
CollectionLogData com.runehive.game.world.entity.mob.player.Player.collectionLogView = null
Definition at line 194 of file Player.java.
Referenced by com.runehive.content.collectionlog.CollectionLog.open().
combat
final Combat<Player> com.runehive.game.world.entity.mob.player.Player.combat = new Combat<>(this) private
Definition at line 346 of file Player.java.
Referenced by canLogout(), and getCombat().
combatSpecial
CombatSpecial com.runehive.game.world.entity.mob.player.Player.combatSpecial private
Definition at line 231 of file Player.java.
Referenced by getCombatSpecial().
completedMageArena
boolean com.runehive.game.world.entity.mob.player.Player.completedMageArena
Definition at line 233 of file Player.java.
contextMenus
final Set<PlayerOption> com.runehive.game.world.entity.mob.player.Player.contextMenus = new HashSet<>()
Definition at line 509 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerOption.encode().
cooldown
int com.runehive.game.world.entity.mob.player.Player.cooldown = 7 * 60 * 1000
Definition at line 306 of file Player.java.
crawsBowCharges
int com.runehive.game.world.entity.mob.player.Player.crawsBowCharges
Definition at line 377 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.content.itemaction.impl.CrawsBow.check(), and com.runehive.content.itemaction.impl.CrawsBow.drop().
created
String com.runehive.game.world.entity.mob.player.Player.created = Utility.getDate()
Definition at line 291 of file Player.java.
Referenced by com.runehive.content.ProfileViewer.string().
dailySlayerTaskSkip
DailyEffect com.runehive.game.world.entity.mob.player.Player.dailySlayerTaskSkip = new DailySlayerTaskSkip()
Definition at line 223 of file Player.java.
dailySlayerTaskTeleport
DailyEffect com.runehive.game.world.entity.mob.player.Player.dailySlayerTaskTeleport = new DailySlayerTaskTeleport()
Definition at line 222 of file Player.java.
dailySpellBookSwap
DailyEffect com.runehive.game.world.entity.mob.player.Player.dailySpellBookSwap = new DailySpellBookSwap()
Definition at line 224 of file Player.java.
databaseRequest
Stopwatch com.runehive.game.world.entity.mob.player.Player.databaseRequest = Stopwatch.start()
Definition at line 311 of file Player.java.
Referenced by com.runehive.game.service.DonationService.claimDonation(), and com.runehive.game.service.VoteService.claimReward().
death
int com.runehive.game.world.entity.mob.player.Player.death
Definition at line 250 of file Player.java.
debug
boolean com.runehive.game.world.entity.mob.player.Player.debug
Definition at line 211 of file Player.java.
Referenced by com.runehive.game.plugin.PluginContext.firstClickObject(), com.runehive.game.plugin.PluginContext.handleButtonClickEvent(), com.runehive.game.plugin.PluginContext.handleItemClickEvent(), com.runehive.game.plugin.PluginContext.handleItemOnItemEvent(), com.runehive.game.plugin.PluginContext.handleItemOnNpcEvent(), com.runehive.game.plugin.PluginContext.handleItemOnObjectEvent(), com.runehive.game.plugin.PluginContext.handleItemOnPlayerEvent(), com.runehive.game.plugin.PluginContext.handleNpcClickEvent(), com.runehive.game.plugin.PluginContext.handleObjectClickEvent(), com.runehive.net.packet.in.RegionChangePacketListener.handlePacket(), loadRegion(), com.runehive.game.plugin.PluginContext.secondClickObject(), and com.runehive.game.plugin.PluginContext.thirdClickObject().
dialogue
Optional<Dialogue> com.runehive.game.world.entity.mob.player.Player.dialogue = Optional.empty()
Definition at line 237 of file Player.java.
dialogueCamDelayTicks
transient int com.runehive.game.world.entity.mob.player.Player.dialogueCamDelayTicks = 0
Delay ticks before camera activates (prevents coordinate misalignment at dialogue start).
Definition at line 174 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick().
dialogueCamMode
transient com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode com.runehive.game.world.entity.mob.player.Player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.OFF
Dialogue camera system.
Definition at line 168 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.requestReset(), com.runehive.content.ai.LazyAIManager.showGptInstructions(), com.runehive.content.ai.LazyAIManager.showGptInstructionsWithGreeting(), com.runehive.content.ai.LazyAIManager.showOpenAIConnectionOffer(), and com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick().
dialogueCamNpc
transient com.runehive.game.world.entity.mob.npc.Npc com.runehive.game.world.entity.mob.player.Player.dialogueCamNpc = null
Definition at line 170 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick().
dialogueCamSwapBoostTicks
transient int com.runehive.game.world.entity.mob.player.Player.dialogueCamSwapBoostTicks = 0
While >0, camera turns use slightly faster "swap" speeds for a smoother PNPC flip.
Definition at line 172 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.boostSwap(), and com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.tick().
dialogueFactory
DialogueFactory com.runehive.game.world.entity.mob.player.Player.dialogueFactory = new DialogueFactory(this)
Definition at line 341 of file Player.java.
Referenced by com.runehive.content.pet.Pets.buyInsurance(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.canExecute(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.canExecute(), com.runehive.content.dailyeffect.DailyEffect.canUse(), com.runehive.game.service.DonationService.claimDonation(), com.runehive.content.pet.Pets.claimLostPets(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.staff.PlayerManagement.confirm(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.CrystalChest.createKey(), com.runehive.content.pet.Pets.dialogue(), com.runehive.content.store.impl.PersonalStore.edit(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.game.plugin.PluginContext.onClick(), com.runehive.content.bloodmoney.BloodMoneyChest.open(), com.runehive.content.Obelisks.open(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.skill.impl.crafting.impl.Spinning.open(), com.runehive.content.shootingstar.ShootingStar.prospect(), com.runehive.content.Waypoints.removeWaypoint(), com.runehive.content.DropDisplay.search(), com.runehive.content.clanchannel.channel.ClanChannelHandler.sendConnectionWarning(), com.runehive.content.dialogue.impl.ClanRankDialogue.setRank(), com.runehive.content.Waypoints.setWaypoint(), com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse(), com.runehive.content.clanchannel.channel.ClanChannelHandler.testPassword(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), and com.runehive.content.skill.impl.herblore.Herblore.useItem().
diceDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.diceDelay = Stopwatch.start()
Definition at line 309 of file Player.java.
donation
final Donation com.runehive.game.world.entity.mob.player.Player.donation = new Donation(this)
Definition at line 242 of file Player.java.
Referenced by com.runehive.content.store.currency.impl.DonatorPointCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.dialogue.impl.RoyalKingDialogue.myStats(), com.runehive.content.store.currency.impl.DonatorPointCurrency.recieveCurrency(), and com.runehive.content.store.currency.impl.DonatorPointCurrency.takeCurrency().
donatorDeposit
final DonatorDeposit com.runehive.game.world.entity.mob.player.Player.donatorDeposit = new DonatorDeposit(this)
Definition at line 340 of file Player.java.
dragonfireCharges
int com.runehive.game.world.entity.mob.player.Player.dragonfireCharges
Definition at line 391 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.canAttack(), com.runehive.content.itemaction.impl.DragonfireShield.empty(), com.runehive.content.itemaction.impl.DragonfireShield.equipment(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), and com.runehive.content.itemaction.impl.DragonfireShield.inspect().
dragonfireUsed
long com.runehive.game.world.entity.mob.player.Player.dragonfireUsed
Definition at line 392 of file Player.java.
Referenced by com.runehive.content.itemaction.impl.DragonfireShield.equipment().
emoteUnlockable
List<EmoteUnlockable> com.runehive.game.world.entity.mob.player.Player.emoteUnlockable = new LinkedList<>()
Definition at line 352 of file Player.java.
Referenced by com.runehive.content.emote.EmoteHandler.contains(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.content.emote.EmoteHandler.unlock(), and com.runehive.content.emote.EmoteHandler.unlockAll().
energyRate
int com.runehive.game.world.entity.mob.player.Player.energyRate
Definition at line 266 of file Player.java.
enterInputListener
Optional<Consumer<String> > com.runehive.game.world.entity.mob.player.Player.enterInputListener = Optional.empty()
Definition at line 239 of file Player.java.
Referenced by com.runehive.net.packet.in.InputStringPacketListener.handlePacket(), and com.runehive.net.packet.in.ItemContainerActionPacketListener.sixthAction().
equipment
final Equipment com.runehive.game.world.entity.mob.player.Player.equipment = new Equipment(this)
Definition at line 335 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.addListener(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack(), com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.combat.magic.Autocast.clickButton(), com.runehive.game.world.entity.mob.player.PlayerAssistant.copy(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation(), com.runehive.content.skill.impl.mining.PickaxeData.getBestPickaxe(), com.runehive.content.skill.impl.farming.Farming.getBonus(), com.runehive.content.skill.impl.firemaking.Firemaking.getBonus(), com.runehive.content.skill.impl.fishing.Fishing.getBonus(), com.runehive.content.skill.impl.mining.Mining.getBonus(), com.runehive.content.skill.impl.woodcutting.Woodcutting.getBonus(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefender(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefenderIndex(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getGearAttackBonus(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.getHits(), com.runehive.content.wintertodt.Wintertodt.getWarmItemsWorn(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.game.world.entity.combat.FormulaUtils.hasAmuletOfAvarice(), com.runehive.game.world.entity.combat.FormulaUtils.hasCrawsBow(), com.runehive.game.world.entity.combat.FormulaUtils.hasObbyWeapon(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.game.world.entity.combat.FormulaUtils.hasThammaronSceptre(), com.runehive.game.world.entity.combat.FormulaUtils.hasViggorasChainMace(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.hit(), com.runehive.content.itemaction.impl.CelestialRing.inventory(), com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), login(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.modifyDamage(), com.runehive.game.world.entity.combat.FormulaUtils.obbyArmour(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.bot.PlayerBot.postDeath(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.StarterKit.refresh(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.removeListener(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.sendStuff(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), com.runehive.content.emote.Emote.skillcape(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start(), com.runehive.content.skill.impl.cooking.Cooking.success(), com.runehive.content.skill.impl.fishing.Fishing.success(), com.runehive.content.skill.impl.mining.Mining.success(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.twistedBowBonus(), com.runehive.content.emote.EmoteHandler.updateSkillcape(), com.runehive.game.world.entity.combat.FormulaUtils.voidBase(), com.runehive.game.world.entity.combat.FormulaUtils.voidMagic(), com.runehive.game.world.entity.combat.FormulaUtils.voidMelee(), com.runehive.game.world.entity.combat.FormulaUtils.voidRanger(), com.runehive.game.world.entity.combat.FormulaUtils.wearingBlackMask(), com.runehive.game.world.entity.combat.FormulaUtils.wearingBlackMaskImbued(), and com.runehive.game.world.entity.combat.FormulaUtils.wearingEliteVoid().
equipment_copy
final Equipment com.runehive.game.world.entity.mob.player.Player.equipment_copy = new Equipment(this)
Definition at line 336 of file Player.java.
Referenced by com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), and com.runehive.content.lms.LMSGame.reset().
events
final Events com.runehive.game.world.entity.mob.player.Player.events = new Events() private
Definition at line 127 of file Player.java.
Referenced by getEvents().
exchangeSession
final ExchangeSessionManager com.runehive.game.world.entity.mob.player.Player.exchangeSession = new ExchangeSessionManager(this)
Definition at line 318 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onButtonClick().
experienceRate
double com.runehive.game.world.entity.mob.player.Player.experienceRate = Config.COMBAT_MODIFICATION
Definition at line 276 of file Player.java.
farming
final Farming com.runehive.game.world.entity.mob.player.Player.farming = new Farming(this)
Definition at line 317 of file Player.java.
Referenced by com.runehive.content.skill.impl.farming.Farming.firstClickObject(), com.runehive.content.skill.impl.farming.Farming.itemOnObject(), loadRegion(), com.runehive.content.skill.impl.farming.Farming.secondClickObject(), and com.runehive.content.skill.impl.farming.Farming.tick().
fastFoodDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.fastFoodDelay = Stopwatch.start()
Definition at line 303 of file Player.java.
favoriteTeleport
List<Teleport> com.runehive.game.world.entity.mob.player.Player.favoriteTeleport = new ArrayList<>()
Definition at line 353 of file Player.java.
Referenced by com.runehive.content.teleport.TeleportHandler.display(), com.runehive.content.teleport.TeleportHandler.favorite(), and com.runehive.content.teleport.TeleportHandler.open().
fightStyles
HashMap<WeaponInterface, FightType> com.runehive.game.world.entity.mob.player.Player.fightStyles = new HashMap<>()
Definition at line 202 of file Player.java.
foodDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.foodDelay = Stopwatch.start()
Definition at line 302 of file Player.java.
gambleLocked
boolean com.runehive.game.world.entity.mob.player.Player.gambleLocked private
Definition at line 150 of file Player.java.
Referenced by isGambleLocked(), and setGambleLock().
gamblingManager
final GambleManager com.runehive.game.world.entity.mob.player.Player.gamblingManager = new GambleManager() private
Definition at line 133 of file Player.java.
Referenced by getGambling().
gameRecord
final PlayerRecord com.runehive.game.world.entity.mob.player.Player.gameRecord = new PlayerRecord(this)
Definition at line 316 of file Player.java.
Referenced by com.runehive.game.plugin.PluginContext.onClick().
gemBag
GemBag com.runehive.game.world.entity.mob.player.Player.gemBag = new GemBag()
Definition at line 189 of file Player.java.
giantPouch
int com.runehive.game.world.entity.mob.player.Player.giantPouch
Definition at line 274 of file Player.java.
glovesTier
int com.runehive.game.world.entity.mob.player.Player.glovesTier
Definition at line 267 of file Player.java.
Referenced by com.runehive.content.store.impl.RecipeForDisasterStore.open().
godwarsDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.godwarsDelay = Stopwatch.start()
Definition at line 299 of file Player.java.
hasPvPTimer
boolean com.runehive.game.world.entity.mob.player.Player.hasPvPTimer
Definition at line 235 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack(), and onStep().
headIcon
int com.runehive.game.world.entity.mob.player.Player.headIcon
Definition at line 252 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.content.bot.PlayerBot.PlayerBot().
hiddenBrother
BrotherData com.runehive.game.world.entity.mob.player.Player.hiddenBrother
Definition at line 245 of file Player.java.
hostList
final Set<String> com.runehive.game.world.entity.mob.player.Player.hostList = new HashSet<>()
Definition at line 354 of file Player.java.
Referenced by com.runehive.net.session.LoginSession.handleUserLoginDetails().
house
final House com.runehive.game.world.entity.mob.player.Player.house = new House(this)
Definition at line 342 of file Player.java.
Referenced by com.runehive.content.skill.impl.construction.House.enter(), and com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues().
idle
boolean com.runehive.game.world.entity.mob.player.Player.idle
Definition at line 278 of file Player.java.
Referenced by com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), and sequence().
interfaceManager
final InterfaceManager com.runehive.game.world.entity.mob.player.Player.interfaceManager = new InterfaceManager(this)
Definition at line 321 of file Player.java.
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack(), canLogout(), com.runehive.content.store.impl.PersonalStore.changeName(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel(), com.runehive.content.activity.panel.ActivityPanel.clear(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.agility.Agility.clickButton(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.game.world.entity.combat.magic.Autocast.clickButton(), com.runehive.content.store.Store.closeShop(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.store.currency.impl.ClanPointCurrency.currencyAmount(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface(), com.runehive.net.packet.out.SendChatBoxInterface.encode(), com.runehive.net.packet.out.SendFadeScreen.encode(), com.runehive.content.store.Store.exchange(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.net.packet.in.CloseInterfacePacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manage(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.plugin.PluginContext.onClick(), onStep(), com.runehive.content.collectionlog.CollectionLog.open(), com.runehive.content.DropDisplay.open(), com.runehive.content.famehall.FameHandler.open(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.Obelisks.open(), com.runehive.content.ProfileViewer.open(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.simulator.DropSimulator.open(), com.runehive.content.skill.impl.construction.BuildableInterface.open(), com.runehive.content.skill.impl.crafting.impl.Glass.open(), com.runehive.content.skill.impl.crafting.impl.Jewellery.open(), com.runehive.content.skill.impl.crafting.impl.Spinning.open(), com.runehive.content.skill.impl.crafting.impl.Tanning.open(), com.runehive.content.StarterKit.open(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.content.teleport.TeleportHandler.open(), com.runehive.content.tittle.TitleManager.open(), com.runehive.content.WellOfGoodwill.open(), com.runehive.content.pet.Pets.openInsurance(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.pet.Pets.openLostPets(), com.runehive.content.store.impl.PersonalStore.openMenu(), com.runehive.content.store.impl.PersonalStore.openPanel(), com.runehive.content.clanchannel.content.ClanShowcase.openShowcase(), com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), com.runehive.content.store.currency.impl.ClanPointCurrency.recieveCurrency(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate(), com.runehive.content.clanchannel.content.ClanShowcase.select(), com.runehive.content.wintertodt.Wintertodt.send(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.game.world.entity.combat.magic.Autocast.setAutocast(), com.runehive.content.dialogue.impl.ClanRankDialogue.setRank(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.clanchannel.channel.ClanManagement.showBanned(), com.runehive.content.ai.LazyAIManager.showGptInstructions(), com.runehive.content.ai.LazyAIManager.showGptInstructionsWithGreeting(), com.runehive.content.skill.impl.smithing.Smelting.smelt(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse(), com.runehive.content.store.currency.impl.ClanPointCurrency.takeCurrency(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), unregister(), com.runehive.content.activity.panel.ActivityPanel.update(), and com.runehive.content.skill.impl.crafting.Crafting.useItem().
inventory
final Inventory com.runehive.game.world.entity.mob.player.Player.inventory = new Inventory(this)
Definition at line 325 of file Player.java.
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.content.RoyaltyProgram.append(), com.runehive.content.wintertodt.Wintertodt.award(), com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.game.action.impl.BuryBoneAction.BuryBoneAction(), com.runehive.content.pet.Pets.buyInsurance(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.store.currency.impl.ItemCurrency.canRecieveCurrency(), com.runehive.content.skill.impl.HarvestingSkillAction.canRun(), com.runehive.content.activity.impl.duelarena.DuelRule.canSet(), com.runehive.content.itemaction.impl.CelestialRing.charge(), com.runehive.content.itemaction.impl.CrawsBow.charge(), com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.ThammaronsSceptre.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), com.runehive.content.itemaction.impl.ViggorasChainmace.charge(), com.runehive.content.tradingpost.TradingPostListing.checkAndUpdate(), com.runehive.content.wintertodt.Wintertodt.chopRoot(), com.runehive.game.service.DonationService.claimDonation(), com.runehive.content.pet.Pets.claimLostPets(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.agility.Agility.clickButton(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.smithing.Smithing.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.contains(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.game.world.entity.mob.player.PlayerAssistant.copy(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.CrystalChest.createKey(), com.runehive.content.store.currency.impl.ItemCurrency.currencyAmount(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.content.gambling.GambleManager.decline(), com.runehive.content.shootingstar.ShootingStarData.decreaseDust(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.skill.impl.hunter.trap.TrapManager.dismantle(), com.runehive.content.itemaction.impl.CelestialRing.drop(), com.runehive.content.itemaction.impl.CrawsBow.drop(), com.runehive.content.itemaction.impl.ThammaronsSceptre.drop(), com.runehive.content.itemaction.impl.ViggorasChainmace.drop(), com.runehive.content.bags.ItemBag.empty(), com.runehive.content.combat.cannon.CannonManager.empty(), com.runehive.content.itemaction.impl.DragonfireShield.empty(), com.runehive.content.combat.Killstreak.end(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.game.action.impl.FlaxPickingAction.execute(), com.runehive.content.bags.ItemBag.fill(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.wintertodt.Wintertodt.fletch(), com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), com.runehive.content.skill.impl.mining.PickaxeData.getBestPickaxe(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefender(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefenderIndex(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.content.skill.impl.runecrafting.Runecraft.getEssence(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.gambling.GambleManager.give(), com.runehive.content.lms.LMSGame.giveChestItems(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnItem(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleLogout(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handleSecondOption(), com.runehive.net.packet.in.ItemOptionPacketListener.handleThirdOption(), com.runehive.content.skill.impl.fishing.Fishing.hasFishingItems(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.content.wintertodt.Wintertodt.healPyromancer(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), com.runehive.content.bot.botclass.impl.PureMelee.hit(), com.runehive.content.bot.botclass.impl.ZerkerMelee.hit(), com.runehive.content.itemaction.impl.CelestialRing.inventory(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.content.store.impl.PersonalStore.itemContainerAction(), com.runehive.content.itemaction.impl.CelestialRing.itemOnItem(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.SerpentineHelm.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), com.runehive.content.combat.cannon.CannonManager.load(), com.runehive.content.itemaction.impl.ToxicBlowpipe.load(), login(), com.runehive.content.combat.cannon.CannonManager.logout(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.wintertodt.Wintertodt.mixHerb(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.content.pet.Pets.onDeath(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.game.action.impl.ScatterAshAction.onExecute(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.pet.Pets.onObtain(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.content.gambling.GambleManager.open(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.skill.impl.crafting.impl.Tanning.open(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.combat.cannon.CannonManager.pickup(), com.runehive.content.bot.PlayerBot.pot(), com.runehive.content.store.impl.SkillcapeStore.purchase(), com.runehive.content.store.Store.purchase(), com.runehive.content.skill.impl.thieving.WallSafe.rate(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.store.currency.impl.ItemCurrency.recieveCurrency(), com.runehive.content.store.impl.DefaultStore.refresh(), com.runehive.content.store.impl.RecipeForDisasterStore.refresh(), com.runehive.content.store.impl.SkillcapeStore.refresh(), com.runehive.content.wintertodt.Wintertodt.removeGameItems(), com.runehive.content.lms.LMSGame.reset(), com.runehive.content.lms.LMSGame.resupplyKiller(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.content.lms.LMSGame.rollChest(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.game.action.impl.ScatterAshAction.ScatterAshAction(), com.runehive.content.skill.impl.woodcutting.BirdsNest.search(), com.runehive.content.store.Store.sell(), com.runehive.content.store.Store.sendSellValue(), com.runehive.content.activity.impl.duelarena.DuelRule.set(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.skill.impl.fishing.Fishing.success(), com.runehive.content.store.currency.impl.ItemCurrency.takeCurrency(), com.runehive.content.wintertodt.Wintertodt.takeHerb(), com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), com.runehive.content.itemaction.impl.MagmaHelm.uncharge(), com.runehive.content.itemaction.impl.SerpentineHelm.uncharge(), com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge(), com.runehive.content.itemaction.impl.TridentOfTheSeas.uncharge(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.uncharge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.unload(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), com.runehive.content.skill.impl.herblore.Herblore.useItem(), com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem(), and com.runehive.content.gambling.GambleManager.withdraw().
inventory_copy
final Inventory com.runehive.game.world.entity.mob.player.Player.inventory_copy = new Inventory(this)
Definition at line 326 of file Player.java.
Referenced by com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), and com.runehive.content.lms.LMSGame.reset().
isBot
boolean com.runehive.game.world.entity.mob.player.Player.isBot
Definition at line 285 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), equals(), com.runehive.net.packet.OutgoingPacket.execute(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), isValid(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.game.world.World.queueLogin(), and toString().
itemDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.itemDelay = Stopwatch.start()
Definition at line 301 of file Player.java.
kill
int com.runehive.game.world.entity.mob.player.Player.kill
Definition at line 249 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.death().
killstreak
final Killstreak com.runehive.game.world.entity.mob.player.Player.killstreak = new Killstreak(this)
Definition at line 332 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), and com.runehive.content.ProfileViewer.string().
largePouch
int com.runehive.game.world.entity.mob.player.Player.largePouch
Definition at line 273 of file Player.java.
lastClan
String com.runehive.game.world.entity.mob.player.Player.lastClan = ""
Definition at line 292 of file Player.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.connect(), com.runehive.content.clanchannel.channel.ClanChannel.establish(), and com.runehive.content.clanchannel.channel.ClanChannelHandler.sendConnectionWarning().
lastFogSent
int com.runehive.game.world.entity.mob.player.Player.lastFogSent
LMS Variables.
Definition at line 163 of file Player.java.
Referenced by com.runehive.content.lms.LMSGame.handleFogDamage().
lastHost
String com.runehive.game.world.entity.mob.player.Player.lastHost
Definition at line 290 of file Player.java.
Referenced by com.runehive.util.tools.LogReader.alreadyClaimedReferral(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.net.session.LoginSession.handleUserLoginDetails(), com.runehive.util.tools.LogPrinter.printReferralLog(), register(), com.runehive.util.Utility.setStarter(), and unregister().
lastKilled
Deque<String> com.runehive.game.world.entity.mob.player.Player.lastKilled = new ArrayDeque<>(3)
Definition at line 351 of file Player.java.
lastLMSRopeCross
long com.runehive.game.world.entity.mob.player.Player.lastLMSRopeCross
Definition at line 165 of file Player.java.
lastModification
long com.runehive.game.world.entity.mob.player.Player.lastModification private
Definition at line 140 of file Player.java.
Referenced by getLastModification(), and setLastModification().
lastTeleport
Teleport com.runehive.game.world.entity.mob.player.Player.lastTeleport = null
Definition at line 135 of file Player.java.
lastUsed
long com.runehive.game.world.entity.mob.player.Player.lastUsed = 0
Definition at line 307 of file Player.java.
lmsDeaths
int com.runehive.game.world.entity.mob.player.Player.lmsDeaths
Definition at line 181 of file Player.java.
lmsImmunity
transient long com.runehive.game.world.entity.mob.player.Player.lmsImmunity
Definition at line 164 of file Player.java.
Referenced by com.runehive.content.lms.LMSGame.canAttack().
lmsKills
int com.runehive.game.world.entity.mob.player.Player.lmsKills
Definition at line 180 of file Player.java.
Referenced by com.runehive.content.lms.LMSGame.onKill().
lmsPoints
int com.runehive.game.world.entity.mob.player.Player.lmsPoints
Definition at line 184 of file Player.java.
Referenced by com.runehive.content.store.currency.impl.LMSPointCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.lms.LMSGame.onDeath(), and com.runehive.content.store.currency.impl.LMSPointCurrency.takeCurrency().
lmsTotalDeaths
int com.runehive.game.world.entity.mob.player.Player.lmsTotalDeaths
Definition at line 186 of file Player.java.
Referenced by com.runehive.content.lms.LMSGame.onDeath().
lmsTotalKills
int com.runehive.game.world.entity.mob.player.Player.lmsTotalKills
Definition at line 185 of file Player.java.
Referenced by com.runehive.content.lms.LMSGame.onKill().
lmsWins
int com.runehive.game.world.entity.mob.player.Player.lmsWins
Definition at line 187 of file Player.java.
Referenced by com.runehive.content.lms.LMSGame.onDeath().
loggedActivities
HashMap<ActivityLog, Integer> com.runehive.game.world.entity.mob.player.Player.loggedActivities
Initial value:
= new HashMap<ActivityLog, Integer>(ActivityLog.values().length) {
        {
            for (final ActivityLog achievement : ActivityLog.values())
                put(achievement, 0);
        }
    }
Definition at line 359 of file Player.java.
{
        {
            for (final ActivityLog achievement : ActivityLog.values())
                put(achievement, 0);
        }
    };
logger
final Logger com.runehive.game.world.entity.mob.player.Player.logger = LogManager.getLogger(Player.class) static private
Definition at line 208 of file Player.java.
Referenced by register(), and unregister().
lootingBag
final LootingBag com.runehive.game.world.entity.mob.player.Player.lootingBag = new LootingBag(this)
Definition at line 333 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems().
lostItems
LinkedList<Item> com.runehive.game.world.entity.mob.player.Player.lostItems = new LinkedList<>()
Definition at line 244 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems().
lostPets
Set<PetData> com.runehive.game.world.entity.mob.player.Player.lostPets = new HashSet<>()
Definition at line 313 of file Player.java.
Referenced by com.runehive.content.pet.Pets.claimLostPets(), com.runehive.content.pet.Pets.onDeath(), and com.runehive.content.pet.Pets.openLostPets().
lostUntradeables
final LostUntradeables com.runehive.game.world.entity.mob.player.Player.lostUntradeables = new LostUntradeables(this)
Definition at line 243 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems().
mageArenaPoints
int com.runehive.game.world.entity.mob.player.Player.mageArenaPoints
Definition at line 260 of file Player.java.
Referenced by com.runehive.content.store.currency.impl.MageArenaCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.ProfileViewer.string(), and com.runehive.content.store.currency.impl.MageArenaCurrency.takeCurrency().
magmaHelmCharges
int com.runehive.game.world.entity.mob.player.Player.magmaHelmCharges
Definition at line 387 of file Player.java.
Referenced by com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.MagmaHelm.check(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), and com.runehive.content.itemaction.impl.MagmaHelm.uncharge().
managing
Optional<Player> com.runehive.game.world.entity.mob.player.Player.managing
Definition at line 232 of file Player.java.
mediumPouch
int com.runehive.game.world.entity.mob.player.Player.mediumPouch
Definition at line 272 of file Player.java.
memberId
int com.runehive.game.world.entity.mob.player.Player.memberId = -1 private
Definition at line 209 of file Player.java.
Referenced by getMemberId(), and setMemberId().
menuOpened
int com.runehive.game.world.entity.mob.player.Player.menuOpened
Definition at line 131 of file Player.java.
Referenced by com.runehive.content.skill.guides.SkillGuides.openInterface().
mysteryBox
final MysteryBoxManager com.runehive.game.world.entity.mob.player.Player.mysteryBox = new MysteryBoxManager(this)
Definition at line 323 of file Player.java.
Referenced by com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption().
needsStarter
boolean com.runehive.game.world.entity.mob.player.Player.needsStarter
Definition at line 281 of file Player.java.
Referenced by sendInitialPackets().
newPlayer
boolean com.runehive.game.world.entity.mob.player.Player.newPlayer
Definition at line 280 of file Player.java.
Referenced by com.runehive.content.bot.PlayerBot.PlayerBot(), and sendInitialPackets().
optionDialogue
Optional<OptionDialogue> com.runehive.game.world.entity.mob.player.Player.optionDialogue = Optional.empty()
Definition at line 238 of file Player.java.
optionOpened
int com.runehive.game.world.entity.mob.player.Player.optionOpened = -1
Definition at line 131 of file Player.java.
Referenced by com.runehive.content.skill.guides.SkillGuides.openInterface().
overrides
final Overrides com.runehive.game.world.entity.mob.player.Player.overrides = new Overrides(this)
Definition at line 356 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation().
password
String com.runehive.game.world.entity.mob.player.Player.password = "" private
Definition at line 288 of file Player.java.
Referenced by equals(), getPassword(), and setPassword().
pestPoints
int com.runehive.game.world.entity.mob.player.Player.pestPoints
Definition at line 255 of file Player.java.
Referenced by com.runehive.content.store.currency.impl.PestPointCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.ProfileViewer.string(), and com.runehive.content.store.currency.impl.PestPointCurrency.takeCurrency().
pet
Npc com.runehive.game.world.entity.mob.player.Player.pet
Definition at line 212 of file Player.java.
Referenced by com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.pet.Pets.onDeath(), com.runehive.content.pet.Pets.onLogin(), com.runehive.content.pet.Pets.onLogout(), com.runehive.content.pet.Pets.onObtain(), com.runehive.content.pet.Pets.onSpawn(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
petInsurance
Set<PetData> com.runehive.game.world.entity.mob.player.Player.petInsurance = new HashSet<>()
Definition at line 312 of file Player.java.
Referenced by com.runehive.content.pet.Pets.buyInsurance(), and com.runehive.content.pet.Pets.hasInsurance().
playerAchievements
HashMap<AchievementKey, Integer> com.runehive.game.world.entity.mob.player.Player.playerAchievements
Initial value:
= new HashMap<AchievementKey, Integer>(AchievementKey.values().length) {
        {
            for (final AchievementKey achievement : AchievementKey.values())
                put(achievement, 0);
        }
    }
Definition at line 366 of file Player.java.
{
        {
            for (final AchievementKey achievement : AchievementKey.values())
                put(achievement, 0);
        }
    };
Referenced by com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.content.achievement.AchievementHandler.completeAll(), com.runehive.content.achievement.AchievementHandler.completed(), com.runehive.content.achievement.AchievementHandler.getDifficultyCompletion(), and com.runehive.content.achievement.AchievementHandler.getTotalCompleted().
playerAssistant
final PlayerAssistant com.runehive.game.world.entity.mob.player.Player.playerAssistant = new PlayerAssistant(this)
Definition at line 320 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.eat(), com.runehive.content.bot.botclass.impl.PureMelee.eat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.eat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.eat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.eat(), com.runehive.net.packet.out.SendString.encode(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), getStrategy(), login(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), onStep(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.content.bot.PlayerBot.postDeath(), com.runehive.content.bot.botclass.impl.PureMelee.pot(), com.runehive.content.bot.botclass.impl.PureRangeMelee.pot(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), sendInitialPackets(), sequence(), com.runehive.content.ProfileViewer.string(), com.runehive.content.activity.randomevent.RandomEventHandler.trigger(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update().
playerTitle
PlayerTitle com.runehive.game.world.entity.mob.player.Player.playerTitle = PlayerTitle.empty()
Definition at line 217 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.ColorPacketListener.handlePacket(), and com.runehive.content.bot.PlayerBot.PlayerBot().
playTime
int com.runehive.game.world.entity.mob.player.Player.playTime
Definition at line 248 of file Player.java.
Referenced by com.runehive.content.gambling.GambleManager.sendRequest(), sequence(), and com.runehive.content.ProfileViewer.string().
poisonImmunity
final MutableNumber com.runehive.game.world.entity.mob.player.Player.poisonImmunity = new MutableNumber() private
Definition at line 348 of file Player.java.
Referenced by getPoisonImmunity().
potionDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.potionDelay = Stopwatch.start()
Definition at line 304 of file Player.java.
Referenced by com.runehive.content.bot.PlayerBot.pot().
presetManager
final PresetManager com.runehive.game.world.entity.mob.player.Player.presetManager = new PresetManager(this)
Definition at line 337 of file Player.java.
prestige
final Prestige com.runehive.game.world.entity.mob.player.Player.prestige = new Prestige(this)
Definition at line 338 of file Player.java.
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.store.currency.impl.PrestigePointCurrency.currencyAmount(), com.runehive.content.skill.impl.woodcutting.BirdsNest.drop(), com.runehive.net.packet.out.SendSkill.encode(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.content.ProfileViewer.open(), com.runehive.content.store.currency.impl.PrestigePointCurrency.recieveCurrency(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.game.service.HighscoreService.saveHighscores(), com.runehive.content.store.currency.impl.PrestigePointCurrency.takeCurrency(), and com.runehive.game.world.entity.skill.SkillManager.updateSkill().
priceChecker
final PriceChecker com.runehive.game.world.entity.mob.player.Player.priceChecker = new PriceChecker(this)
Definition at line 339 of file Player.java.
punishment
final PlayerPunishment com.runehive.game.world.entity.mob.player.Player.punishment = new PlayerPunishment(this)
Definition at line 334 of file Player.java.
Referenced by com.runehive.net.packet.in.ChatMessagePacketListener.handlePacket(), and com.runehive.content.Yell.yell().
puzzle
final PuzzleDisplay com.runehive.game.world.entity.mob.player.Player.puzzle = new PuzzleDisplay(this)
Definition at line 314 of file Player.java.
Referenced by com.runehive.content.bloodmoney.BloodMoneyChest.open().
pvpInstance
boolean com.runehive.game.world.entity.mob.player.Player.pvpInstance
Definition at line 234 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), onStep(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
pvpTimer
Stopwatch com.runehive.game.world.entity.mob.player.Player.pvpTimer = Stopwatch.start()
Definition at line 236 of file Player.java.
quickPrayers
PrayerBook com.runehive.game.world.entity.mob.player.Player.quickPrayers = new PrayerBook()
Definition at line 225 of file Player.java.
rangedAmmo
RangedAmmunition com.runehive.game.world.entity.mob.player.Player.rangedAmmo
Definition at line 228 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start().
rangedDefinition
RangedWeaponDefinition com.runehive.game.world.entity.mob.player.Player.rangedDefinition
Definition at line 227 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start().
relations
final PlayerRelation com.runehive.game.world.entity.mob.player.Player.relations = new PlayerRelation(this)
Definition at line 241 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPrivateMessage.encode(), login(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.message(), and unregister().
requestManager
final RequestManager com.runehive.game.world.entity.mob.player.Player.requestManager = new RequestManager(this)
Definition at line 322 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.requests.RequestManager.request().
resting
boolean com.runehive.game.world.entity.mob.player.Player.resting
Definition at line 279 of file Player.java.
restoreDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.restoreDelay = Stopwatch.start()
Definition at line 308 of file Player.java.
revstele
Stopwatch com.runehive.game.world.entity.mob.player.Player.revstele = Stopwatch.start()
Definition at line 305 of file Player.java.
right
PlayerRight com.runehive.game.world.entity.mob.player.Player.right = PlayerRight.PLAYER
Definition at line 216 of file Player.java.
Referenced by com.runehive.content.triviabot.TriviaBot.answered(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.activity.record.GameRecord.GameRecord(), com.runehive.content.Waypoints.getAllowedPoints(), com.runehive.net.packet.in.ColorPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.net.session.LoginSession.handleUserLoginDetails(), com.runehive.content.store.impl.PersonalStore.myShop(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.content.ProfileViewer.open(), com.runehive.game.service.HighscoreService.saveHighscores(), com.runehive.game.world.entity.skill.SkillManager.updateSkill(), and com.runehive.content.Yell.yell().
ringOfRecoil
int com.runehive.game.world.entity.mob.player.Player.ringOfRecoil = 40
Definition at line 261 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block().
royalty
int com.runehive.game.world.entity.mob.player.Player.royalty
Definition at line 269 of file Player.java.
Referenced by com.runehive.content.RoyaltyProgram.append(), and com.runehive.content.RoyaltyProgram.open().
royaltyLevel
int com.runehive.game.world.entity.mob.player.Player.royaltyLevel = 1
Definition at line 268 of file Player.java.
Referenced by com.runehive.content.RoyaltyProgram.append(), and com.runehive.content.RoyaltyProgram.open().
runecraftPouch
final RunecraftPouch com.runehive.game.world.entity.mob.player.Player.runecraftPouch = new RunecraftPouch(this)
Definition at line 275 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), and com.runehive.content.skill.impl.runecrafting.Runecraft.clickItem().
runEnergy
int com.runehive.game.world.entity.mob.player.Player.runEnergy
Definition at line 265 of file Player.java.
Referenced by com.runehive.net.packet.out.SendRunEnergy.encode(), com.runehive.game.world.entity.combat.attack.listener.item.ToragListener.hit(), and com.runehive.content.consume.PotionData.onEnergyEffect().
runePouch
final RunePouch com.runehive.game.world.entity.mob.player.Player.runePouch = new RunePouch(this)
Definition at line 330 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), and com.runehive.content.lms.LMSGame.reset().
runePouch_copy
final RunePouch com.runehive.game.world.entity.mob.player.Player.runePouch_copy = new RunePouch(this)
Definition at line 331 of file Player.java.
Referenced by com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), and com.runehive.content.lms.LMSGame.reset().
saved
final AtomicBoolean com.runehive.game.world.entity.mob.player.Player.saved = new AtomicBoolean(false)
Definition at line 297 of file Player.java.
sceneBaseChunkX
transient int com.runehive.game.world.entity.mob.player.Player.sceneBaseChunkX private
Client's current scene base, in 8x8 chunks (set when SendMapRegion is sent).
Definition at line 177 of file Player.java.
Referenced by getSceneBaseChunkX(), and toSceneLocalX().
sceneBaseChunkY
transient int com.runehive.game.world.entity.mob.player.Player.sceneBaseChunkY private
Definition at line 178 of file Player.java.
Referenced by getSceneBaseChunkY(), and toSceneLocalY().
sequence
int com.runehive.game.world.entity.mob.player.Player.sequence
Reimplemented in com.runehive.content.bot.PlayerBot.
Definition at line 247 of file Player.java.
Referenced by sequence().
serpentineHelmCharges
int com.runehive.game.world.entity.mob.player.Player.serpentineHelmCharges
Definition at line 385 of file Player.java.
Referenced by com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.check(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), and com.runehive.content.itemaction.impl.SerpentineHelm.uncharge().
session
Optional<GameSession> com.runehive.game.world.entity.mob.player.Player.session = Optional.empty() private
Definition at line 390 of file Player.java.
Referenced by getSession(), isValid(), and setSession().
settings
final Settings com.runehive.game.world.entity.mob.player.Player.settings = new Settings(this)
Definition at line 324 of file Player.java.
Referenced by com.runehive.content.triviabot.TriviaBot.answer(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.execute(), isAutoRetaliate(), login(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember(), com.runehive.content.clanchannel.channel.ClanChannelHandler.updateMemberList(), and com.runehive.content.Yell.yell().
shop
int com.runehive.game.world.entity.mob.player.Player.shop
Definition at line 251 of file Player.java.
singleCast
CombatSpell com.runehive.game.world.entity.mob.player.Player.singleCast
Definition at line 214 of file Player.java.
Referenced by getSingleCastSpell(), isSingleCast(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), and setSingleCast().
skillingPoints
int com.runehive.game.world.entity.mob.player.Player.skillingPoints
Definition at line 254 of file Player.java.
Referenced by com.runehive.content.store.currency.impl.SkillingPointCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.ProfileViewer.string(), and com.runehive.content.store.currency.impl.SkillingPointCurrency.takeCurrency().
skulling
Skulling com.runehive.game.world.entity.mob.player.Player.skulling = new Skulling(this)
Definition at line 344 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.apply(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.combat.Skulling.checkForSkulling(), com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.onLogin(), com.runehive.content.ItemsKeptOnDeath.open(), and com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.removeOn().
slayer
Slayer com.runehive.game.world.entity.mob.player.Player.slayer = new Slayer(this)
Definition at line 343 of file Player.java.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTask.asList(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.store.currency.impl.SlayerPointCurrency.currencyAmount(), com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.SlayerHelmListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyMagicLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyRangedLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyStrengthLevel(), com.runehive.game.world.entity.combat.attack.listener.item.SlayerHelmListener.modifyStrengthLevel(), com.runehive.game.plugin.PluginContext.onClick(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), com.runehive.content.store.currency.impl.SlayerPointCurrency.recieveCurrency(), com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues(), and com.runehive.content.store.currency.impl.SlayerPointCurrency.takeCurrency().
smallPouch
int com.runehive.game.world.entity.mob.player.Player.smallPouch
Definition at line 271 of file Player.java.
specialActivated
boolean com.runehive.game.world.entity.mob.player.Player.specialActivated private
Definition at line 283 of file Player.java.
Referenced by isSpecialActivated().
specialPercentage
final MutableNumber com.runehive.game.world.entity.mob.player.Player.specialPercentage = new MutableNumber() private
Definition at line 350 of file Player.java.
Referenced by getSpecialPercentage().
spellbook
Spellbook com.runehive.game.world.entity.mob.player.Player.spellbook = Spellbook.MODERN
Definition at line 218 of file Player.java.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.content.lms.LMSGame.reset(), and com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface().
spellbook_copy
Spellbook com.runehive.game.world.entity.mob.player.Player.spellbook_copy = Spellbook.MODERN
Definition at line 219 of file Player.java.
Referenced by com.runehive.content.lms.LMSGame.reset().
spellCasting
SpellCasting com.runehive.game.world.entity.mob.player.Player.spellCasting = new SpellCasting(this)
Definition at line 345 of file Player.java.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), and com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute().
staffOfDeadSpecial
Stopwatch com.runehive.game.world.entity.mob.player.Player.staffOfDeadSpecial = Stopwatch.start().reset(200)
Definition at line 389 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage().
tanzaniteHelmCharges
int com.runehive.game.world.entity.mob.player.Player.tanzaniteHelmCharges
Definition at line 386 of file Player.java.
Referenced by com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.check(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), and com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge().
teleblockTimer
final AtomicInteger com.runehive.game.world.entity.mob.player.Player.teleblockTimer = new AtomicInteger(0)
Definition at line 868 of file Player.java.
Referenced by isTeleblocked(), com.runehive.content.bot.PlayerBot.postDeath(), and teleblock().
thammoranSceptreCharges
int com.runehive.game.world.entity.mob.player.Player.thammoranSceptreCharges
Definition at line 379 of file Player.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.itemaction.impl.ThammaronsSceptre.check(), com.runehive.content.itemaction.impl.ThammaronsSceptre.drop(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start().
totalVotes
int com.runehive.game.world.entity.mob.player.Player.totalVotes
Definition at line 257 of file Player.java.
Referenced by com.runehive.game.service.VoteService.claimReward(), and com.runehive.content.ProfileViewer.string().
tradingPost
final TradingPost com.runehive.game.world.entity.mob.player.Player.tradingPost = new TradingPost(this)
Definition at line 355 of file Player.java.
Referenced by com.runehive.content.tradingpost.TradingPostListing.checkAndUpdate(), com.runehive.content.tradingpost.TradingPostListing.removeQuantity(), and com.runehive.content.tradingpost.TradingPostListing.setPrice().
trapsLaid
int com.runehive.game.world.entity.mob.player.Player.trapsLaid
Definition at line 286 of file Player.java.
Referenced by com.runehive.content.skill.impl.hunter.trap.TrapManager.canLay(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleLogout(), and com.runehive.content.skill.impl.hunter.trap.TrapManager.handleRegionChange().
tridentSeasCharges
int com.runehive.game.world.entity.mob.player.Player.tridentSeasCharges
Definition at line 380 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.content.itemaction.impl.TridentOfTheSeas.check(), com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem(), and com.runehive.content.itemaction.impl.TridentOfTheSeas.uncharge().
tridentSwampCharges
int com.runehive.game.world.entity.mob.player.Player.tridentSwampCharges
Definition at line 381 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.check(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.itemOnItem(), and com.runehive.content.itemaction.impl.TridentOfTheSwamp.uncharge().
unlockedLMSItems
List<Integer> com.runehive.game.world.entity.mob.player.Player.unlockedLMSItems = new ArrayList<>()
Definition at line 179 of file Player.java.
Referenced by com.runehive.content.lms.LMSGame.onDeath(), and com.runehive.content.lms.LMSGame.rollChest().
unlockedPrayers
HashSet<Prayer> com.runehive.game.world.entity.mob.player.Player.unlockedPrayers = new HashSet<>()
Definition at line 226 of file Player.java.
username
String com.runehive.game.world.entity.mob.player.Player.username = "" private
Definition at line 287 of file Player.java.
Referenced by equals(), getName(), getUsername(), hashCode(), Player(), Player(), and setUsername().
usernameLong
long com.runehive.game.world.entity.mob.player.Player.usernameLong
Definition at line 277 of file Player.java.
Referenced by com.runehive.game.world.items.ground.GroundItem.addToRegion(), com.runehive.game.world.items.ground.GroundItem.canSee(), com.runehive.game.world.items.ground.GroundItem.equals(), and com.runehive.game.world.items.ground.GroundItem.pickup().
uuid
String com.runehive.game.world.entity.mob.player.Player.uuid
Definition at line 289 of file Player.java.
valueIcon
int com.runehive.game.world.entity.mob.player.Player.valueIcon = -1
Definition at line 253 of file Player.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask().
venged
boolean com.runehive.game.world.entity.mob.player.Player.venged
Definition at line 282 of file Player.java.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.finishIncoming(), and com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill().
venomImmunity
final MutableNumber com.runehive.game.world.entity.mob.player.Player.venomImmunity = new MutableNumber() private
Definition at line 349 of file Player.java.
Referenced by getVenomImmunity().
viewing_shops
final Map<Integer, PersonalStore> com.runehive.game.world.entity.mob.player.Player.viewing_shops = new HashMap<>()
Definition at line 319 of file Player.java.
Referenced by com.runehive.content.store.impl.PersonalStore.close(), and com.runehive.content.store.impl.PersonalStore.openPanel().
viewport
final Viewport com.runehive.game.world.entity.mob.player.Player.viewport = new Viewport(this)
Definition at line 210 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.Alkahrid.block(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.net.packet.out.SendNpcUpdate.encode(), com.runehive.net.packet.out.SendPlayerUpdate.encode(), and com.runehive.game.world.entity.combat.attack.listener.npc.SergeantStrongstack.hit().
viggorasChainmaceCharges
int com.runehive.game.world.entity.mob.player.Player.viggorasChainmaceCharges
Definition at line 378 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.attack(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), com.runehive.content.itemaction.impl.ViggorasChainmace.check(), and com.runehive.content.itemaction.impl.ViggorasChainmace.drop().
votePoints
int com.runehive.game.world.entity.mob.player.Player.votePoints
Definition at line 256 of file Player.java.
Referenced by com.runehive.content.store.currency.impl.VotePointCurrency.currencyAmount(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.ProfileViewer.string(), and com.runehive.content.store.currency.impl.VotePointCurrency.takeCurrency().
warriorGuidTask
boolean com.runehive.game.world.entity.mob.player.Player.warriorGuidTask
Definition at line 284 of file Player.java.
waypoints
Map<String, Position> com.runehive.game.world.entity.mob.player.Player.waypoints = new HashMap<>()
Definition at line 134 of file Player.java.
Referenced by com.runehive.content.Waypoints.getWaypoints(), com.runehive.content.Waypoints.removeWaypoint(), and com.runehive.content.Waypoints.setWaypoint().
weapon
WeaponInterface com.runehive.game.world.entity.mob.player.Player.weapon = WeaponInterface.UNARMED private
Definition at line 230 of file Player.java.
Referenced by getWeapon(), and setWeapon().
whipCharges
int com.runehive.game.world.entity.mob.player.Player.whipCharges = 2500
Definition at line 262 of file Player.java.
wilderness
int com.runehive.game.world.entity.mob.player.Player.wilderness
Definition at line 264 of file Player.java.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), onStep(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), and com.runehive.content.teleport.TeleportHandler.teleport().
wintertodtPoints
int com.runehive.game.world.entity.mob.player.Player.wintertodtPoints
Definition at line 130 of file Player.java.
Referenced by com.runehive.content.wintertodt.Wintertodt.addPoints(), com.runehive.content.wintertodt.Wintertodt.award(), and com.runehive.content.wintertodt.Wintertodt.send().
yellDelay
Stopwatch com.runehive.game.world.entity.mob.player.Player.yellDelay = Stopwatch.start()
Definition at line 298 of file Player.java.
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/Player.java