RuneHive-Game: dev.advo.fs.dispatch.OnDemandRequestWorker Class Reference
dev.advo.fs.dispatch.OnDemandRequestWorker Class Reference
A worker which services 'on-demand' requests.
Public Member Functions
OnDemandRequestWorker (IndexedFileSystem fs)
Creates the 'on-demand' request worker.
final void run ()
final void stop ()
Stops this worker.
Protected Member Functions
ChannelRequest< OnDemandRequest > nextRequest () throws InterruptedException
void service (IndexedFileSystem fs, Channel channel, OnDemandRequest request) throws IOException
Private Attributes
final Object lock = new Object()
An object used for locking checks to see if the worker is running.
final IndexedFileSystem provider
The resource provider.
boolean running = true
A flag indicating if the worker should be running.
Detailed Description
A worker which services 'on-demand' requests.
Author
Graham
Definition at line 19 of file OnDemandRequestWorker.java.
Constructor & Destructor Documentation
OnDemandRequestWorker()
dev.advo.fs.dispatch.OnDemandRequestWorker.OnDemandRequestWorker (IndexedFileSystem fs)
Creates the 'on-demand' request worker.
Parameters
fs The file system.
Definition at line 38 of file OnDemandRequestWorker.java.
{
        this.provider = fs;
    }
Member Function Documentation
nextRequest()
ChannelRequest< OnDemandRequest > dev.advo.fs.dispatch.OnDemandRequestWorker.nextRequest () throws InterruptedException protected
Definition at line 42 of file OnDemandRequestWorker.java.
{
        return RequestDispatcher.nextOnDemandRequest();
    }
References dev.advo.fs.dispatch.RequestDispatcher.nextOnDemandRequest().
Referenced by run().
run()
final void dev.advo.fs.dispatch.OnDemandRequestWorker.run ()
Definition at line 78 of file OnDemandRequestWorker.java.
{
        while (true) {
            synchronized (lock) {
                if (!running) {
                    break;
                }
            }
            ChannelRequest<OnDemandRequest> request;
            try {
                request = nextRequest();
            } catch (InterruptedException e) {
                continue;
            }
            Channel channel = request.getChannel();
            try {
                service(provider, channel, request.getRequest());
            } catch (IOException e) {
            //  System.err.println("Error serving file: " + request.getRequest().getFileDescriptor().toString());
            //  e.printStackTrace();
            //  channel.close();
            }
        }
    }
References dev.advo.fs.dispatch.ChannelRequest< T >.getChannel(), dev.advo.fs.dispatch.ChannelRequest< T >.getRequest(), lock, nextRequest(), provider, running, and service().
service()
void dev.advo.fs.dispatch.OnDemandRequestWorker.service (IndexedFileSystem fs, Channel channel, OnDemandRequest request) throws IOException protected
Definition at line 52 of file OnDemandRequestWorker.java.
{
        FileDescriptor desc = request.getFileDescriptor();
        System.err.println("Serving file: " + desc.toString());
        ByteBuffer buf = fs.getFile(desc);
        int bufLen = buf.remaining();
        int length = bufLen;
        byte[] tmp = new byte[bufLen];
        buf.get(tmp, 0, tmp.length);
        ChannelBuffer chunkData = ChannelBuffers.wrappedBuffer(tmp, 0, bufLen);
        OnDemandResponse response = new OnDemandResponse(desc, length, chunkData);
        channel.write(response);
    }
References dev.advo.fs.fs.FileDescriptor.toString().
Referenced by run().
stop()
final void dev.advo.fs.dispatch.OnDemandRequestWorker.stop ()
Stops this worker.
The worker's thread may need to be interrupted.
Definition at line 71 of file OnDemandRequestWorker.java.
{
        synchronized (lock) {
            running = false;
        }
    }
References lock, and running.
Member Data Documentation
lock
final Object dev.advo.fs.dispatch.OnDemandRequestWorker.lock = new Object() private
An object used for locking checks to see if the worker is running.
Definition at line 28 of file OnDemandRequestWorker.java.
Referenced by run(), and stop().
provider
final IndexedFileSystem dev.advo.fs.dispatch.OnDemandRequestWorker.provider private
The resource provider.
Definition at line 24 of file OnDemandRequestWorker.java.
Referenced by run().
running
boolean dev.advo.fs.dispatch.OnDemandRequestWorker.running = true private
A flag indicating if the worker should be running.
Definition at line 32 of file OnDemandRequestWorker.java.
Referenced by run(), and stop().
The documentation for this class was generated from the following file:
java/dev/advo/fs/dispatch/OnDemandRequestWorker.java