RuneHive-Game: com.runehive.content.bags.impl.CoalBag Class Reference
com.runehive.content.bags.impl.CoalBag Class Reference
Public Member Functions
void check (Player player)
CoalBag ()
String getIndication ()
String getItem ()
String getName ()
Predicate< Item > isAllowed ()
Public Member Functions inherited from com.runehive.content.bags.ItemBag
void empty (Player player)
void fill (Player player)
ItemBag (ItemContainer container)
Static Public Attributes
static final int SIZE = 27
Additional Inherited Members
Public Attributes inherited from com.runehive.content.bags.ItemBag
final ItemContainer container
Detailed Description
Definition at line 12 of file CoalBag.java.
Constructor & Destructor Documentation
CoalBag()
com.runehive.content.bags.impl.CoalBag.CoalBag ()
Definition at line 16 of file CoalBag.java.
                     {
        super(new ItemContainer(SIZE, ItemContainer.StackPolicy.NEVER));
    }
References com.runehive.game.world.items.containers.ItemContainer.StackPolicy.NEVER, and SIZE.
Member Function Documentation
check()
void com.runehive.content.bags.impl.CoalBag.check (Player player)
Reimplemented from com.runehive.content.bags.ItemBag.
Definition at line 41 of file CoalBag.java.
{
        if(container.getFreeSlots() == SIZE) {
            player.message("The "+getName()+" is empty.");
            return;
        }
        player.message("The "+getName()+" contains "+container.computeAmountForId(453)+" pieces of coal.");
    }
References com.runehive.content.bags.ItemBag.container, getName(), com.runehive.game.world.entity.mob.player.Player.message(), and SIZE.
getIndication()
String com.runehive.content.bags.impl.CoalBag.getIndication ()
Reimplemented from com.runehive.content.bags.ItemBag.
Definition at line 36 of file CoalBag.java.
{
        return "is";
    }
getItem()
String com.runehive.content.bags.impl.CoalBag.getItem ()
Reimplemented from com.runehive.content.bags.ItemBag.
Definition at line 21 of file CoalBag.java.
{
        return "coal";
    }
getName()
String com.runehive.content.bags.impl.CoalBag.getName ()
Reimplemented from com.runehive.content.bags.ItemBag.
Definition at line 26 of file CoalBag.java.
{
        return "coal bag";
    }
Referenced by check().
isAllowed()
Predicate< Item > com.runehive.content.bags.impl.CoalBag.isAllowed ()
Reimplemented from com.runehive.content.bags.ItemBag.
Definition at line 31 of file CoalBag.java.
{
        return coal -> Objects.nonNull(coal) && (ItemDefinition.get(coal.getId()).getName().startsWith("Coal") && !ItemDefinition.get(coal.getId()).getName().contains("bag")) && !ItemDefinition.get(coal.getId()).isStackable();
    }
References com.runehive.game.world.items.ItemDefinition.get(), and com.runehive.game.world.items.ItemDefinition.getName().
Member Data Documentation
SIZE
final int com.runehive.content.bags.impl.CoalBag.SIZE = 27 static
Definition at line 14 of file CoalBag.java.
Referenced by check(), and CoalBag().
The documentation for this class was generated from the following file:
java/com/runehive/content/bags/impl/CoalBag.java