RuneHive-Game: com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob > Class Template Reference
com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob > Class Template Reference
Holds variables to generate combat data of an actor.
Public Member Functions
CombatData (T attacker, Mob defender, CombatHit hit, CombatStrategy<? super T > strategy, boolean lastHit)
Constructs a new CombatHitData object.
T getAttacker ()
Mob getDefender ()
CombatHit getHit ()
int getHitDelay ()
int getHitsplatDelay ()
CombatStrategy<? super T > getStrategy ()
boolean isLastHit ()
Private Attributes
final T attacker
The attacker.
final Mob defender
The defender.
final CombatHit hit
The combat hit.
final boolean lastHit
Whether or not this hit is the last one.
final CombatStrategy<? super T > strategy
The combat strategy.
Detailed Description
Holds variables to generate combat data of an actor.
Author
Michael | Chex
Definition at line 11 of file CombatData.java.
Constructor & Destructor Documentation
CombatData()
com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.CombatData (T attacker, Mob defender, CombatHit hit, CombatStrategy<? super T > strategy, boolean lastHit)
Constructs a new CombatHitData object.
Definition at line 29 of file CombatData.java.
{
        this.attacker = attacker;
        this.defender = defender;
        this.hit = hit;
        this.strategy = strategy;
        this.lastHit = lastHit;
    }
References attacker, defender, hit, lastHit, and strategy.
Member Function Documentation
getAttacker()
T com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getAttacker ()
Returns
the attacker
Definition at line 38 of file CombatData.java.
{
        return attacker;
    }
References attacker.
getDefender()
Mob com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getDefender ()
Returns
the defender
Definition at line 43 of file CombatData.java.
{
        return defender;
    }
References defender.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplatTask(), and com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitTask().
getHit()
CombatHit com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getHit ()
Returns
the hit
Definition at line 48 of file CombatData.java.
{
        return hit;
    }
References hit.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplatTask(), and com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitTask().
getHitDelay()
int com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getHitDelay ()
Returns
the hit delay.
Definition at line 53 of file CombatData.java.
{
        return hit.getHitDelay();
    }
References hit.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitTask().
getHitsplatDelay()
int com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getHitsplatDelay ()
Returns
the hitsplat delay.
Definition at line 58 of file CombatData.java.
{
        return hit.getHitsplatDelay();
    }
References hit.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplatTask().
getStrategy()
CombatStrategy<? super T > com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getStrategy ()
Returns
the combat strategy
Definition at line 63 of file CombatData.java.
{
        return strategy;
    }
References strategy.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplatTask().
isLastHit()
boolean com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.isLastHit ()
Returns
true if this hit data is the last hit
Definition at line 68 of file CombatData.java.
{
        return lastHit;
    }
References lastHit.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplatTask().
Member Data Documentation
attacker
final T com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.attacker private
The attacker.
Definition at line 14 of file CombatData.java.
Referenced by CombatData(), and getAttacker().
defender
final Mob com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.defender private
The defender.
Definition at line 17 of file CombatData.java.
Referenced by CombatData(), and getDefender().
hit
final CombatHit com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.hit private
The combat hit.
Definition at line 20 of file CombatData.java.
Referenced by CombatData(), getHit(), getHitDelay(), and getHitsplatDelay().
lastHit
final boolean com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.lastHit private
Whether or not this hit is the last one.
Definition at line 26 of file CombatData.java.
Referenced by CombatData(), and isLastHit().
strategy
final CombatStrategy<? super T> com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.strategy private
The combat strategy.
Definition at line 23 of file CombatData.java.
Referenced by CombatData(), and getStrategy().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/hit/CombatData.java