RuneHive-Game: com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropTable Class Reference
com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropTable Class Reference
Protected Member Functions
void parseDocument (Document document)
Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTable
WikiTable (String link)
Package Functions
NpcDropTable (String link, Collection< NpcDefinition > definitions)
Private Member Functions
void log (String message)
Static Private Member Functions
static JsonArray buildDropItemTables (Collection< DropItem > drops)
Private Attributes
final Collection< NpcDefinition > definitions
Additional Inherited Members
Public Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTable
String getLink ()
JsonArray getTable ()
Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTable
final JsonArray table = new JsonArray()
Detailed Description
Definition at line 84 of file NpcDropsParser.java.
Constructor & Destructor Documentation
NpcDropTable()
com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropTable.NpcDropTable (String link, Collection< NpcDefinition > definitions) package
Definition at line 87 of file NpcDropsParser.java.
{
            super(link);
            this.definitions = definitions;
        }
References definitions, and com.runehive.util.tools.wiki.parser.WikiTable.link.
Member Function Documentation
buildDropItemTables()
JsonArray com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropTable.buildDropItemTables (Collection< DropItem > drops) static private
Definition at line 194 of file NpcDropsParser.java.
{
            JsonArray items = new JsonArray();
            for (DropItem item : drops) {
                JsonObject dropItem = new JsonObject();
                dropItem.addProperty("id", item.id);
                dropItem.addProperty("minimum", item.min);
                dropItem.addProperty("maximum", item.max);
                dropItem.addProperty("type", item.rarity.name());
                items.add(dropItem);
            }
            return items;
        }
Referenced by parseDocument().
log()
void com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropTable.log (String message) private
Definition at line 210 of file NpcDropsParser.java.
{
            String name = ((NpcDefinition) definitions.toArray()[0]).getName();
            System.out.println("[name=" + name + "]  --  " + message);
        }
References definitions.
Referenced by parseDocument().
parseDocument()
void com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropTable.parseDocument (Document document) protected
Reimplemented from com.runehive.util.tools.wiki.parser.WikiTable.
Definition at line 93 of file NpcDropsParser.java.
{
            Elements dropTable = document.select(".wikitable.sortable.dropstable");
            Elements td = dropTable.select("td");
            Iterator<Element> iterator = td.iterator();
            List<DropItem> drops = new LinkedList<>();
            boolean rareDropTable = false;
            while (iterator.hasNext()) {
                iterator.next();
                String name = iterator.next().text();
                String amount = iterator.next().text().replaceAll(",", "");
                String rarity = iterator.next().text().toLowerCase();
                iterator.next();
                if (!itemByName.containsKey(name)) {
                    log("missing item: " + name);
                    if (name.contains("Rare drop table")) {
                        rareDropTable = true;
                    }
                    continue;
                }
                if (amount.contains("Unknown")) {
                    log("unknown drop amount: " + name);
                    continue;
                }
                try {
                    int id, min, max;
                    int notedIndex = amount.indexOf("(noted)");
                    if (notedIndex > -1) {
                        amount = amount.substring(0, notedIndex - 1).trim();
                        id = itemByName.get(name).getNotedId();
                    } else {
                        id = itemByName.get(name).getId();
                    }
                    DropRarity rate;
                    if (rarity.startsWith("very rare")) {
                        rate = DropRarity.VERY_RARE;
                    } else if (rarity.startsWith("rare")) {
                        rate = DropRarity.RARE;
                    } else if (rarity.startsWith("uncommon")) {
                        rate = DropRarity.UNCOMMON;
                    } else if (rarity.startsWith("common")) {
                        rate = DropRarity.COMMON;
                    } else if (rarity.startsWith("always")) {
                        rate = DropRarity.ALWAYS;
                    } else {
                        log("unknown drop rarity: " + rarity);
                        continue;
                    }
                    if (amount.contains(";")) {
                        String[] amounts = amount.split("; ");
                        for (String s : amounts) {
                            int hyphen = s.indexOf("–");
                            if (hyphen > -1) {
                                min = Integer.valueOf(s.substring(0, hyphen));
                                max = Integer.valueOf(s.substring(hyphen + 1));
                            } else {
                                min = max = Integer.valueOf(s);
                            }
                            drops.add(new DropItem(id, min, max, rate));
                        }
                    } else {
                        int hyphen = amount.indexOf("–");
                        if (hyphen > -1) {
                            min = Integer.valueOf(amount.substring(0, hyphen));
                            max = Integer.valueOf(amount.substring(hyphen + 1));
                        } else {
                            min = max = Integer.valueOf(amount);
                        }
                        drops.add(new DropItem(id, min, max, rate));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            if (drops.isEmpty()) {
                return;
            }
            JsonObject object = new JsonObject();
            JsonArray array = new JsonArray();
            for (NpcDefinition definition : definitions) {
                array.add(definition.getId());
            }
            drops.sort(Comparator.comparing(drop -> drop.rarity));
            object.add("ids", array);
            object.addProperty("rare_table", rareDropTable);
            object.add("drops", buildDropItemTables(drops));
            table.add(object);
        }
References com.runehive.util.tools.wiki.impl.NpcDropsParser.DropRarity.ALWAYS, buildDropItemTables(), com.runehive.util.tools.wiki.impl.NpcDropsParser.DropRarity.COMMON, definitions, com.runehive.util.tools.wiki.impl.NpcDropsParser.itemByName, log(), com.runehive.util.tools.wiki.impl.NpcDropsParser.DropRarity.RARE, com.runehive.util.tools.wiki.parser.WikiTable.table, com.runehive.util.tools.wiki.impl.NpcDropsParser.DropRarity.UNCOMMON, and com.runehive.util.tools.wiki.impl.NpcDropsParser.DropRarity.VERY_RARE.
Member Data Documentation
definitions
final Collection<NpcDefinition> com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropTable.definitions private
Definition at line 85 of file NpcDropsParser.java.
Referenced by log(), NpcDropTable(), and parseDocument().
The documentation for this class was generated from the following file:
java/com/runehive/util/tools/wiki/impl/NpcDropsParser.java