RuneHive-Game: com.runehive.content.clanchannel.channel.ClanChannel Class Reference
com.runehive.content.clanchannel.channel.ClanChannel Class Reference
Handles the clan chat channel.
Public Member Functions
void activateAchievement (ClanAchievement achievement)
void activateTask (ClanTaskKey key, String name)
void activateTask (ClanTaskKey key, String name, int amount)
int activeSize ()
void addExperience (double experience)
void ban (String name)
boolean canManage (ClanMember member)
void chat (String name, String message)
int compareTo (ClanChannel other)
boolean equals (Object obj)
void forEach (Consumer< ClanMember > member)
Handles looping through each clan member.
String getColor ()
ClanDetails getDetails ()
ClanChannelHandler getHandler ()
ClanManagement getManagement ()
Optional< ClanMember > getMember (String name)
Set< ClanMember > getMembers ()
String getName ()
String getOwner ()
String getPassword ()
ClanShowcase getShowcase ()
Item[] getShowcaseItems ()
String getSlogan ()
String getTag ()
int hashCode ()
boolean isLocked ()
boolean lootshareEnabled ()
void message (Object... messages)
Handles messaging all the members in the clan channel.
void receiveTask (Difficulty difficulty)
void setColor (String color)
void setName (Player player, String name)
void setRank (ClanMember member, ClanRank rank)
void setSlogan (Player player, String slogan)
void setTag (Player player, String tag)
int size ()
void splitLoot (Player player, Mob dead, Item item)
JsonObject toJson ()
void unban (Player player, int index)
Static Public Member Functions
static ClanChannel create (Player player)
static void load (String owner)
Package Functions
void add (Player player, ClanMember member)
boolean canEnter (ClanMember member)
void connect (Player player)
Handles a player connecting to the clan channel.
void disconnect (String name, boolean logout)
Handles disconnecting a player from the clan channel.
void establish (Player player, ClanMember member)
List< ClanMember > getActiveMembers ()
boolean hasPassword ()
boolean isBanned (String name)
boolean isPassword (String input)
Package Attributes
final List< String > bannedMembers = new ArrayList<>()
A list of banned members.
Private Member Functions
boolean addMember (ClanMember member)
ClanChannel ()
void forPlayers (Consumer< Player > player)
Handles looping through each clan member.
Private Attributes
int active
The total active logged in members.
ClanDetails details = new ClanDetails(this)
The clan channel details.
ClanChannelHandler handler = new ClanChannelHandler(this)
The clan channel handler.
ClanManagement management = new ClanManagement(this)
The clan channel management tab panel.
final Set< ClanMember > members = new HashSet<>()
The clan channel member set.
ClanShowcase showcase = new ClanShowcase(this)
The clan channel showcase items.
Static Private Attributes
static final Gson GSON = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create()
Detailed Description
Handles the clan chat channel.
Author
Daniel
Michael
Definition at line 34 of file ClanChannel.java.
Constructor & Destructor Documentation
ClanChannel()
com.runehive.content.clanchannel.channel.ClanChannel.ClanChannel () private
Definition at line 59 of file ClanChannel.java.
{
    }
Referenced by activateTask(), compareTo(), create(), equals(), load(), and setRank().
Member Function Documentation
activateAchievement()
void com.runehive.content.clanchannel.channel.ClanChannel.activateAchievement (ClanAchievement achievement)
Definition at line 295 of file ClanChannel.java.
{
        final int current = details.achievements.computeIfAbsent(achievement, a -> 0);
        for (ClanAchievement list : ClanAchievement.values()) {
            if (list == achievement) {
                details.achievements.put(achievement, current + 1);
                if (details.completedAchievement(list)) {
                    message("Achievement completed! " + list.details, "We have earned " + list.getPoints() + " CP and " + Utility.formatDigits(list.getExperience()) + " Clan EXP.");
                }
            }
        }
    }
References details, com.runehive.util.Utility.formatDigits(), and message().
Referenced by activateTask(), and add().
activateTask() [1/2]
void com.runehive.content.clanchannel.channel.ClanChannel.activateTask (ClanTaskKey key, String name)
Definition at line 252 of file ClanChannel.java.
{
        activateTask(key, name, 1);
    }
References activateTask().
Referenced by activateTask().
activateTask() [2/2]
void com.runehive.content.clanchannel.channel.ClanChannel.activateTask (ClanTaskKey key, String name, int amount)
Definition at line 256 of file ClanChannel.java.
{
        if (details.clanTask == null)
            return;
        ClanTask task = details.clanTask;
        if (task.key != key)
            return;
        double experience = task.getProgressExperience();
        int progress = details.taskAmount - amount;
        if (progress <= 0) {
            int reward = details.clanTask.getReward();
            details.points += reward;
            message("Task complete! Reward: <col=255>" + reward + "</col> CP. We now have: <col=255>" + Utility.formatDigits(details.points) + "</col> CP.");
            details.clanTask = null;
            progress = 0;
            activateAchievement(ClanAchievement.TASKS_I);
            activateAchievement(ClanAchievement.TASKS_II);
            activateAchievement(ClanAchievement.TASKS_III);
        }
        details.taskAmount = progress;
        addExperience(experience);
        getMember(name).ifPresent(member -> {
            member.expGained += experience;
            if (task.type == ClanType.PVP) {
                member.playerKills++;
            } else if (task.type == ClanType.PVM) {
                member.npcKills++;
            }
            member.player.ifPresent(player -> {
                if (!player.lastClan.isEmpty() && !player.lastClan.equalsIgnoreCase(player.getName())) {
                    ClanChannel channel = ClanRepository.getChannel(player.lastClan);
                    if (channel != null)
                        channel.disconnect(name, false);
                }
            });
        });
    }
References activateAchievement(), addExperience(), ClanChannel(), details, com.runehive.util.Utility.formatDigits(), com.runehive.content.clanchannel.ClanRepository.getChannel(), getMember(), com.runehive.content.clanchannel.content.ClanTask.getProgressExperience(), com.runehive.content.clanchannel.content.ClanTask.key, message(), com.runehive.content.clanchannel.ClanType.PVM, com.runehive.content.clanchannel.ClanType.PVP, com.runehive.content.clanchannel.content.ClanAchievement.TASKS_I, com.runehive.content.clanchannel.content.ClanAchievement.TASKS_II, com.runehive.content.clanchannel.content.ClanAchievement.TASKS_III, and com.runehive.content.clanchannel.content.ClanTask.type.
activeSize()
int com.runehive.content.clanchannel.channel.ClanChannel.activeSize ()
Definition at line 453 of file ClanChannel.java.
{
        return active;
    }
References active.
Referenced by com.runehive.game.task.impl.ClanUpdateEvent.tick().
add()
void com.runehive.content.clanchannel.channel.ClanChannel.add (Player player, ClanMember member) package
Definition at line 99 of file ClanChannel.java.
{
        if (member.name.equalsIgnoreCase(details.owner)) {
            member.rank = ClanRank.LEADER;
        }
        if (!handler.attemptConnection(player, member)) {
            return;
        }
        if (handler.testPassword(player, member)) {
            return;
        }
        int count = getMembers().size();
        establish(player, member);
        if (getMembers().size() > count) {
            activateAchievement(ClanAchievement.CLAN_MEMBERS_I);
            activateAchievement(ClanAchievement.CLAN_MEMBERS_II);
            activateAchievement(ClanAchievement.CLAN_MEMBERS_III);
        }
    }
References activateAchievement(), com.runehive.content.clanchannel.content.ClanAchievement.CLAN_MEMBERS_I, com.runehive.content.clanchannel.content.ClanAchievement.CLAN_MEMBERS_II, com.runehive.content.clanchannel.content.ClanAchievement.CLAN_MEMBERS_III, details, establish(), getMembers(), handler, com.runehive.content.clanchannel.ClanRank.LEADER, com.runehive.content.clanchannel.ClanMember.name, and size().
Referenced by connect().
addExperience()
void com.runehive.content.clanchannel.channel.ClanChannel.addExperience (double experience)
Definition at line 227 of file ClanChannel.java.
{
        if (experience + details.experience > Double.MAX_VALUE)
            return;
        details.experience += experience;
        ClanLevel level = ClanLevel.getLevel(details.experience);
        if (details.level != level) {
            details.level = level;
            details.points += level.getPoints();
            forPlayers(player -> {
                player.clanTagColor = level.getColor();
                player.updateFlags.add(UpdateFlag.APPEARANCE);
            });
            message("We have leveled up to <col=255>" + Utility.formatEnum(level.name()) + "</col>! Total Experience: <col=255>" + Utility.formatDigits(details.experience), "We have earned <col=255>" + level.getPoints() + "</col> CP, which puts us at <col=255>" + Utility.formatDigits(details.points) + "</col> CP.");
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, details, com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatEnum(), forPlayers(), com.runehive.content.clanchannel.content.ClanLevel.getColor(), com.runehive.content.clanchannel.content.ClanLevel.getLevel(), com.runehive.content.clanchannel.content.ClanLevel.getPoints(), and message().
Referenced by activateTask().
addMember()
boolean com.runehive.content.clanchannel.channel.ClanChannel.addMember (ClanMember member) private
Definition at line 143 of file ClanChannel.java.
{
        return members.add(member);
    }
References members.
Referenced by establish().
ban()
void com.runehive.content.clanchannel.channel.ClanChannel.ban (String name)
Definition at line 177 of file ClanChannel.java.
{
        bannedMembers.add(name);
        Iterator<ClanMember> iterator = members.iterator();
        while (iterator.hasNext()) {
            ClanMember member = iterator.next();
            if (member.name.equals(name)) {
                if (member.rank.greaterThanEqual(ClanRank.LEADER)) {
                    return;
                }
                member.player.ifPresent(player -> {
                    ClanChannelHandler.clean(player);
                    player.clanTag = "";
                    player.lastClan = details.owner;
                    player.clanChannel = null;
                    player.updateFlags.add(UpdateFlag.APPEARANCE);
                    player.send(new SendMessage("You have been banned from the clan chat channel."));
                    member.player = Optional.empty();
                    if (--active == 0) {
                        ClanRepository.setInactive(this);
                    }
                });
                iterator.remove();
                return;
            }
        }
    }
References active, com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, bannedMembers, com.runehive.content.clanchannel.channel.ClanChannelHandler.clean(), details, com.runehive.content.clanchannel.ClanRank.greaterThanEqual(), com.runehive.content.clanchannel.ClanRank.LEADER, members, com.runehive.content.clanchannel.ClanMember.name, com.runehive.content.clanchannel.ClanMember.player, com.runehive.content.clanchannel.ClanMember.rank, and com.runehive.content.clanchannel.ClanRepository.setInactive().
canEnter()
boolean com.runehive.content.clanchannel.channel.ClanChannel.canEnter (ClanMember member) package
Definition at line 478 of file ClanChannel.java.
{
        return management.canEnter(member);
    }
References management.
canManage()
boolean com.runehive.content.clanchannel.channel.ClanChannel.canManage (ClanMember member)
Definition at line 461 of file ClanChannel.java.
{
        return member != null && management.canManage(member);
    }
References management.
Referenced by com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), and com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues().
chat()
void com.runehive.content.clanchannel.channel.ClanChannel.chat (String name, String message)
Definition at line 402 of file ClanChannel.java.
{
        getMember(name).ifPresent(member -> {
            if (management.canTalk(member)) {
                if (Arrays.stream(Yell.INVALID).anyMatch(message::contains)) {
                    member.message("Your message contains invalid characters.");
                    return;
                }
                forEach(other -> other.chat(member, message));
            } else {
                member.message("Your rank is too low to talk in this channel.");
            }
        });
    }
References forEach(), getMember(), com.runehive.content.Yell.INVALID, management, and message().
compareTo()
int com.runehive.content.clanchannel.channel.ClanChannel.compareTo (ClanChannel other)
Definition at line 658 of file ClanChannel.java.
{
        int compare = Double.compare(other.details.experience, details.experience);
        if (compare == 0)
            return management.name.compareTo(other.management.name);
        return compare;
    }
References ClanChannel(), details, com.runehive.content.clanchannel.channel.ClanDetails.experience, management, and com.runehive.content.clanchannel.channel.ClanManagement.name.
connect()
void com.runehive.content.clanchannel.channel.ClanChannel.connect (Player player) package
Handles a player connecting to the clan channel.
Definition at line 84 of file ClanChannel.java.
{
        ClanMember member = new ClanMember(player);
        if (!player.lastClan.isEmpty()) {
            if (player.lastClan.equals(details.owner)) {
                player.lastClan = "";
            } else if (!members.contains(member)) {
                handler.sendConnectionWarning(player, member);
                return;
            }
        }
        add(player, member);
    }
References add(), details, handler, com.runehive.game.world.entity.mob.player.Player.lastClan, and members.
create()
ClanChannel com.runehive.content.clanchannel.channel.ClanChannel.create (Player player) static
Definition at line 62 of file ClanChannel.java.
{
        if (ClanRepository.getChannel(player.getName()) != null) {
            player.send(new SendMessage("There is already a clan channel under your name!"));
            return null;
        }
        int[] showcase = new int[]{1155, 1117, 1075};
        ClanChannel channel = new ClanChannel();
        channel.management.name = player.getName();
        channel.details.owner = player.getName();
        channel.management.slogan = "Generic slogan here";
        channel.details.established = Utility.getSimpleDate();
        channel.details.type = ClanType.SOCIAL;
        channel.details.level = ClanLevel.BRONZE;
        channel.showcase.showcase = showcase;
        Arrays.stream(showcase).forEach(i -> channel.showcase.showcaseItems.add(i));
        channel.connect(player);
        ClanRepository.addChannel(channel);
        ClanRepository.ALLTIME.add(channel);
        return channel;
    }
References com.runehive.content.clanchannel.ClanRepository.addChannel(), com.runehive.content.clanchannel.ClanRepository.ALLTIME, com.runehive.content.clanchannel.content.ClanLevel.BRONZE, ClanChannel(), com.runehive.content.clanchannel.ClanRepository.getChannel(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.util.Utility.getSimpleDate(), com.runehive.game.world.entity.mob.player.Player.send(), showcase, and com.runehive.content.clanchannel.ClanType.SOCIAL.
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.connect().
disconnect()
void com.runehive.content.clanchannel.channel.ClanChannel.disconnect (String name, boolean logout) package
Handles disconnecting a player from the clan channel.
Definition at line 148 of file ClanChannel.java.
{
        Iterator<ClanMember> iterator = members.iterator();
        while (iterator.hasNext()) {
            ClanMember member = iterator.next();
            if (member.name.equals(name)) {
                if (member.rank == ClanRank.SYSTEM || (member.rank == ClanRank.MEMBER && !member.hasContributed())) {
                    iterator.remove();
                }
                member.player.ifPresent(player -> {
                    if (!logout) {
                        ClanChannelHandler.clean(player);
                        player.clanTag = "";
                        player.clanChannel = null;
                        player.updateFlags.add(UpdateFlag.APPEARANCE);
                        player.send(new SendMessage("You have disconnected from the clan chat channel."));
                    }
                    if (member.rank != ClanRank.SYSTEM) {
                        player.lastClan = details.owner;
                    }
                    member.player = Optional.empty();
                    if (--active == 0) {
                        ClanRepository.setInactive(this);
                    }
                });
                return;
            }
        }
    }
References active, com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.clanchannel.channel.ClanChannelHandler.clean(), details, com.runehive.content.clanchannel.ClanMember.hasContributed(), com.runehive.content.clanchannel.ClanRank.MEMBER, members, com.runehive.content.clanchannel.ClanMember.name, com.runehive.content.clanchannel.ClanMember.player, com.runehive.content.clanchannel.ClanMember.rank, com.runehive.content.clanchannel.ClanRepository.setInactive(), and com.runehive.content.clanchannel.ClanRank.SYSTEM.
equals()
boolean com.runehive.content.clanchannel.channel.ClanChannel.equals (Object obj)
Definition at line 671 of file ClanChannel.java.
{
        if (obj == this) return true;
        if (obj instanceof ClanChannel) {
            ClanChannel other = (ClanChannel) obj;
            return Objects.equals(details, other.details)
                    && Objects.equals(management, other.management);
        }
        return super.equals(obj);
    }
References ClanChannel(), details, and management.
establish()
void com.runehive.content.clanchannel.channel.ClanChannel.establish (Player player, ClanMember member) package
Definition at line 123 of file ClanChannel.java.
{
        player.clanChannel = this;
        player.clanTag = getTag();
        player.clanTagColor = details.level.getColor();
        player.updateFlags.add(UpdateFlag.APPEARANCE);
        if (player.lastClan.equals(details.owner)) {
            player.lastClan = "";
        }
        active++;
        member = getMember(member.name).orElse(member);
        member.player = Optional.of(player);
        if (addMember(member)) {
            member.joined = Utility.getSimpleDate();
        }
        handler.connected(member);
        ClanRepository.setActive(this);
    }
References active, addMember(), com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, details, getMember(), com.runehive.util.Utility.getSimpleDate(), getTag(), handler, com.runehive.game.world.entity.mob.player.Player.lastClan, com.runehive.content.clanchannel.ClanMember.name, com.runehive.content.clanchannel.ClanRepository.setActive(), and com.runehive.game.world.entity.mob.Mob.updateFlags.
Referenced by add().
forEach()
void com.runehive.content.clanchannel.channel.ClanChannel.forEach (Consumer< ClanMember > member)
Handles looping through each clan member.
Definition at line 393 of file ClanChannel.java.
{
        members.forEach(member);
    }
References members.
Referenced by chat(), getActiveMembers(), message(), and com.runehive.game.task.impl.ClanUpdateEvent.tick().
forPlayers()
void com.runehive.content.clanchannel.channel.ClanChannel.forPlayers (Consumer< Player > player) private
Handles looping through each clan member.
Definition at line 386 of file ClanChannel.java.
{
        for (ClanMember member : members) {
            member.player.ifPresent(player);
        }
    }
References members.
Referenced by addExperience().
getActiveMembers()
List< ClanMember > com.runehive.content.clanchannel.channel.ClanChannel.getActiveMembers () package
Definition at line 379 of file ClanChannel.java.
{
        List<ClanMember> list = new LinkedList<>();
        forEach(member -> member.player.ifPresent(player -> list.add(member)));
        return list;
    }
References forEach().
getColor()
String com.runehive.content.clanchannel.channel.ClanChannel.getColor ()
Definition at line 518 of file ClanChannel.java.
{
        return management.color;
    }
References management.
getDetails()
ClanDetails com.runehive.content.clanchannel.channel.ClanChannel.getDetails ()
Definition at line 490 of file ClanChannel.java.
{
        return details;
    }
References details.
Referenced by com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask(), com.runehive.content.store.currency.impl.ClanPointCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), com.runehive.content.store.currency.impl.ClanPointCurrency.recieveCurrency(), and com.runehive.content.store.currency.impl.ClanPointCurrency.takeCurrency().
getHandler()
ClanChannelHandler com.runehive.content.clanchannel.channel.ClanChannel.getHandler ()
Definition at line 502 of file ClanChannel.java.
{
        return handler;
    }
References handler.
Referenced by com.runehive.game.task.impl.ClanUpdateEvent.tick().
getManagement()
ClanManagement com.runehive.content.clanchannel.channel.ClanChannel.getManagement ()
Definition at line 494 of file ClanChannel.java.
{
        return management;
    }
References management.
getMember()
Optional< ClanMember > com.runehive.content.clanchannel.channel.ClanChannel.getMember (String name)
Definition at line 371 of file ClanChannel.java.
{
        for (ClanMember member : members) {
            if (member.name.equalsIgnoreCase(name))
                return Optional.of(member);
        }
        return Optional.empty();
    }
References members.
Referenced by activateTask(), chat(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), establish(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), and splitLoot().
getMembers()
Set< ClanMember > com.runehive.content.clanchannel.channel.ClanChannel.getMembers ()
Definition at line 498 of file ClanChannel.java.
{
        return members;
    }
References members.
Referenced by add().
getName()
String com.runehive.content.clanchannel.channel.ClanChannel.getName ()
Definition at line 441 of file ClanChannel.java.
{
        return management.name;
    }
References management.
Referenced by com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), setName(), and com.runehive.content.ProfileViewer.string().
getOwner()
String com.runehive.content.clanchannel.channel.ClanChannel.getOwner ()
Definition at line 445 of file ClanChannel.java.
{
        return details.owner;
    }
References details.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.clanchannel.channel.ClanChannelHandler.onLogin(), and com.runehive.game.task.impl.ClanUpdateEvent.tick().
getPassword()
String com.runehive.content.clanchannel.channel.ClanChannel.getPassword ()
Definition at line 510 of file ClanChannel.java.
{
        return management.password;
    }
References management.
getShowcase()
ClanShowcase com.runehive.content.clanchannel.channel.ClanChannel.getShowcase ()
Definition at line 522 of file ClanChannel.java.
{
        return showcase;
    }
References showcase.
Referenced by com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory().
getShowcaseItems()
Item[] com.runehive.content.clanchannel.channel.ClanChannel.getShowcaseItems ()
Definition at line 526 of file ClanChannel.java.
{
        Item[] items = new Item[showcase.showcase.length];
        int count = 0;
        for (int iem : showcase.showcase) {
            items[count] = new Item(iem, 1);
            if (items[count].isStackable()) {
                items[count].setAmount(250);
            }
            count++;
        }
        return items;
    }
References com.runehive.game.world.items.Item.setAmount(), and showcase.
Referenced by com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory().
getSlogan()
String com.runehive.content.clanchannel.channel.ClanChannel.getSlogan ()
Definition at line 506 of file ClanChannel.java.
{
        return management.slogan;
    }
References management.
getTag()
String com.runehive.content.clanchannel.channel.ClanChannel.getTag ()
Definition at line 514 of file ClanChannel.java.
{
        return management.tag;
    }
References management.
Referenced by establish(), and setTag().
hashCode()
int com.runehive.content.clanchannel.channel.ClanChannel.hashCode ()
Definition at line 666 of file ClanChannel.java.
{
        return details.owner.hashCode();
    }
References details.
hasPassword()
boolean com.runehive.content.clanchannel.channel.ClanChannel.hasPassword () package
Definition at line 482 of file ClanChannel.java.
{
        return management.password != null && !management.password.isEmpty();
    }
References management.
isBanned()
boolean com.runehive.content.clanchannel.channel.ClanChannel.isBanned (String name) package
Definition at line 465 of file ClanChannel.java.
{
        for (String banned : bannedMembers) {
            if (banned.equalsIgnoreCase(name)) {
                return true;
            }
        }
        return false;
    }
References bannedMembers.
isLocked()
boolean com.runehive.content.clanchannel.channel.ClanChannel.isLocked ()
Definition at line 474 of file ClanChannel.java.
{
        return management.locked;
    }
References management.
isPassword()
boolean com.runehive.content.clanchannel.channel.ClanChannel.isPassword (String input) package
Definition at line 486 of file ClanChannel.java.
{
        return input.equals(management.password);
    }
References management.
load()
void com.runehive.content.clanchannel.channel.ClanChannel.load (String owner) static
Definition at line 585 of file ClanChannel.java.
{
        new GsonParser("/content/clan/" + owner, false) {
            @Override
            protected void parse(JsonObject object) {
                ClanChannel channel = new ClanChannel();
                channel.details.owner = object.get("owner").getAsString();
                channel.management.name = object.get("name").getAsString();
                if (object.has("password")) {
                    channel.management.password = object.get("password").getAsString();
                }
                channel.details.established = object.get("established").getAsString();
                if (object.has("forum")) {
                    channel.management.forum = object.get("forum").getAsString();
                }
                if (object.has("slogan")) {
                    channel.management.slogan = object.get("slogan").getAsString();
                }
                if (object.has("clan-tag")) {
                    channel.management.tag = object.get("clan-tag").getAsString();
                }
                channel.details.type = ClanType.valueOf(object.get("clan-type").getAsString());
                if (object.has("clan-color")) {
                    channel.management.color = object.get("clan-color").getAsString();
                }
                channel.details.points = object.get("clan-points").getAsInt();
                channel.details.experience = object.get("clan-experience").getAsLong();
                channel.details.level = ClanLevel.valueOf(object.get("clan-level").getAsString());
                if (object.has("clan-task")) {
                    channel.details.clanTask = ClanTask.valueOf(object.get("clan-task").getAsString());
                }
                channel.details.taskAmount = object.get("task-amount").getAsInt();
                channel.management.locked = object.get("locked").getAsBoolean();
                channel.management.lootshare = object.get("lootshare").getAsBoolean();
                channel.management.loadRanks(object);
                channel.showcase.showcase = GSON.fromJson(object.get("showcase"), int[].class);
                JsonArray array = object.get("showcase-items").getAsJsonArray();
                for (JsonElement element : array) {
                    channel.showcase.showcaseItems.add(element.getAsInt());
                }
                array = object.get("banned-members").getAsJsonArray();
                for (JsonElement element : array) {
                    channel.bannedMembers.add(element.getAsString());
                }
                JsonArray members = object.get("members").getAsJsonArray();
                for (JsonElement element : members) {
                    JsonObject memberObj = (JsonObject) element;
                    String name = memberObj.get("name").getAsString();
                    ClanMember member = new ClanMember(name);
                    member.joined = memberObj.get("joined").getAsString();
                    member.rank = ClanRank.valueOf(memberObj.get("rank").getAsString());
                    member.expGained = memberObj.get("exp-gained").getAsDouble();
                    member.npcKills = memberObj.get("npc-kills").getAsInt();
                    member.playerKills = memberObj.get("player-kills").getAsInt();
                    member.totalLevel = memberObj.get("total-level").getAsInt();
                    channel.addMember(member);
                }
                if (!channel.getTag().isEmpty())
                    ClanRepository.ACTIVE_TAGS.add(channel.getTag());
                if (!channel.getName().isEmpty())
                    ClanRepository.ACTIVE_NAMES.add(channel.getName());
                ClanRepository.ALLTIME.add(channel);
                ClanRepository.addChannel(channel);
            }
        }.run();
    }
References com.runehive.content.clanchannel.ClanRepository.ACTIVE_NAMES, com.runehive.content.clanchannel.ClanRepository.ACTIVE_TAGS, com.runehive.content.clanchannel.ClanRepository.addChannel(), com.runehive.content.clanchannel.ClanRepository.ALLTIME, ClanChannel(), GSON, and members.
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.connect(), and com.runehive.content.clanchannel.ClanRepository.loadChannels().
lootshareEnabled()
boolean com.runehive.content.clanchannel.channel.ClanChannel.lootshareEnabled ()
Definition at line 457 of file ClanChannel.java.
{
        return management.lootshare;
    }
References management.
Referenced by splitLoot().
message()
void com.runehive.content.clanchannel.channel.ClanChannel.message (Object... messages)
Handles messaging all the members in the clan channel.
Definition at line 398 of file ClanChannel.java.
{
        forEach(member -> member.message(messages));
    }
References forEach().
Referenced by activateAchievement(), activateTask(), addExperience(), chat(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), receiveTask(), setName(), and setTag().
receiveTask()
void com.runehive.content.clanchannel.channel.ClanChannel.receiveTask (Difficulty difficulty)
Definition at line 243 of file ClanChannel.java.
{
        if (details.clanTask == null) {
            ClanTask task = ClanTask.getAssignment(details.type, difficulty);
            details.taskAmount = task.getAmount();
            details.clanTask = task;
            message("Task time! <col=255>" + task.getName(this) + "</col>.");
        }
    }
References details, com.runehive.content.clanchannel.content.ClanTask.getAmount(), com.runehive.content.clanchannel.content.ClanTask.getAssignment(), com.runehive.content.clanchannel.content.ClanTask.getName(), and message().
Referenced by com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask().
setColor()
void com.runehive.content.clanchannel.channel.ClanChannel.setColor (String color)
Definition at line 539 of file ClanChannel.java.
{
        management.color = color;
    }
setName()
void com.runehive.content.clanchannel.channel.ClanChannel.setName (Player player, String name)
Definition at line 318 of file ClanChannel.java.
{
        if (getName().equalsIgnoreCase(name)) {
            player.message("Your clan channel name is already set to " + getName() + "!");
            return;
        }
        if (Arrays.stream(Config.BAD_STRINGS).anyMatch(name::contains)) {
            player.message("The name you have entered was prohibited! Try something else.");
            return;
        }
        if (ClanRepository.nameExist(name)) {
            player.message("There is already a clan that exists with that name!");
            return;
        }
        name = Utility.formatName(name);
        if (!management.name.isEmpty())
            ClanRepository.ACTIVE_NAMES.remove(management.name.toLowerCase().trim());
        ClanRepository.ACTIVE_NAMES.add(name.toLowerCase().trim());
        management.name = name;
        message("The clan name has been changed to: <col=255>" + name + "</col>.");
        player.clanViewer.update(this);
    }
References com.runehive.content.clanchannel.ClanRepository.ACTIVE_NAMES, com.runehive.Config.BAD_STRINGS, com.runehive.game.world.entity.mob.player.Player.clanViewer, com.runehive.util.Utility.formatName(), getName(), management, message(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.clanchannel.ClanRepository.nameExist(), and com.runehive.content.clanchannel.content.ClanViewer.update().
setRank()
void com.runehive.content.clanchannel.channel.ClanChannel.setRank (ClanMember member, ClanRank rank)
Definition at line 307 of file ClanChannel.java.
{
        member.player.ifPresent(player -> {
            if (!player.lastClan.isEmpty() && !player.lastClan.equalsIgnoreCase(player.getName())) {
                ClanChannel channel = ClanRepository.getChannel(player.lastClan);
                if (channel != null)
                    channel.disconnect(member.name, false);
            }
        });
        member.rank = rank;
    }
References ClanChannel(), com.runehive.content.clanchannel.ClanRepository.getChannel(), com.runehive.content.clanchannel.ClanMember.name, and com.runehive.content.clanchannel.ClanMember.player.
Referenced by com.runehive.content.dialogue.impl.ClanRankDialogue.setRank().
setSlogan()
void com.runehive.content.clanchannel.channel.ClanChannel.setSlogan (Player player, String slogan)
Definition at line 362 of file ClanChannel.java.
{
        if (Arrays.stream(Config.BAD_STRINGS).anyMatch(slogan::contains)) {
            player.message("The slogan you have entered was prohibited! Try something else.");
            return;
        }
        management.slogan = Utility.formatName(slogan);
        player.clanViewer.update(this);
    }
References com.runehive.Config.BAD_STRINGS, com.runehive.game.world.entity.mob.player.Player.clanViewer, com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.content.clanchannel.content.ClanViewer.update().
setTag()
void com.runehive.content.clanchannel.channel.ClanChannel.setTag (Player player, String tag)
Definition at line 340 of file ClanChannel.java.
{
        if (tag.length() > 4)
            return;
        if (getTag().equalsIgnoreCase(tag)) {
            player.message("Your clan channel tag is already set to " + getTag() + "!");
            return;
        }
        if (Arrays.stream(Config.BAD_STRINGS).anyMatch(tag::contains)) {
            player.message("The tag you have entered was prohibited! Try something else.");
            return;
        }
        if (ClanRepository.tagExist(tag)) {
            player.message("There is already a clan that exists with that tag!");
            return;
        }
        if (!management.tag.isEmpty())
            ClanRepository.ACTIVE_TAGS.remove(management.tag);
        ClanRepository.ACTIVE_TAGS.add(management.tag = tag);
        message("The clan tag has been changed to: <col=255>" + getTag() + "</col>.");
        player.clanViewer.update(this);
    }
References com.runehive.content.clanchannel.ClanRepository.ACTIVE_TAGS, com.runehive.Config.BAD_STRINGS, com.runehive.game.world.entity.mob.player.Player.clanViewer, getTag(), management, message(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.clanchannel.ClanRepository.tagExist(), and com.runehive.content.clanchannel.content.ClanViewer.update().
size()
int com.runehive.content.clanchannel.channel.ClanChannel.size ()
Definition at line 449 of file ClanChannel.java.
                      {
        return members.size();
    }
References members.
Referenced by add(), and unban().
splitLoot()
void com.runehive.content.clanchannel.channel.ClanChannel.splitLoot (Player player, Mob dead, Item item)
Definition at line 417 of file ClanChannel.java.
{
        if (!lootshareEnabled()) {
            return;
        }
        Set<Player> players = new HashSet<>();
        long value = item.getValue(PriceType.HIGH_ALCH_VALUE) * item.getAmount();
        long tax = value / 4;
        players.add(player);
        RegionManager.forNearbyPlayer(dead, 32, nearby -> {
            if (Objects.equals(nearby.clanChannel, player.clanChannel)) {
                players.add(nearby);
            }
        });
        long split = (value - tax) / players.size();
        players.forEach(other -> {
            getMember(other.getName()).ifPresent(member ->
                    member.message(Utility.formatDigits(split) + " coins have been deposited into your bank vault."));
//            other.bankVault.deposit((int) split);
        });
    }
References com.runehive.game.world.entity.mob.player.Player.clanChannel, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.region.RegionManager.forNearbyPlayer(), com.runehive.game.world.items.Item.getAmount(), getMember(), com.runehive.game.world.items.Item.getValue(), com.runehive.game.world.items.containers.pricechecker.PriceType.HIGH_ALCH_VALUE, and lootshareEnabled().
toJson()
JsonObject com.runehive.content.clanchannel.channel.ClanChannel.toJson ()
Definition at line 543 of file ClanChannel.java.
{
        JsonObject object = new JsonObject();
        object.addProperty("owner", details.owner);
        object.addProperty("established", details.established);
        object.addProperty("name", management.name);
        object.addProperty("password", management.password);
        object.addProperty("forum", management.forum);
        object.addProperty("slogan", management.slogan);
        object.addProperty("clan-tag", management.tag);
        object.addProperty("clan-type", String.valueOf(details.type));
        object.addProperty("clan-color", management.color);
        object.addProperty("clan-points", details.points);
        object.addProperty("clan-experience", details.experience);
        object.addProperty("clan-level", String.valueOf(details.level));
        if (details.clanTask != null) {
            object.addProperty("clan-task", String.valueOf(details.clanTask));
        }
        object.addProperty("task-amount", details.taskAmount);
        object.addProperty("locked", management.locked);
        object.addProperty("lootshare", management.lootshare);
        management.saveRanks(object);
        object.add("showcase", GSON.toJsonTree(showcase.showcase));
        object.add("showcase-items", GSON.toJsonTree(showcase.showcaseItems));
        object.add("banned-members", GSON.toJsonTree(bannedMembers));
        JsonArray memberArray = new JsonArray();
        for (ClanMember member : members) {
            JsonObject memberObj = new JsonObject();
            memberObj.addProperty("name", member.name);
            memberObj.addProperty("joined", member.joined);
            memberObj.addProperty("rank", String.valueOf(member.rank));
            memberObj.addProperty("exp-gained", member.expGained);
            memberObj.addProperty("npc-kills", member.npcKills);
            memberObj.addProperty("player-kills", member.playerKills);
            memberObj.addProperty("total-level", member.totalLevel);
            memberArray.add(memberObj);
        }
        object.add("members", memberArray);
        return object;
    }
References bannedMembers, details, GSON, management, members, and showcase.
Referenced by com.runehive.game.task.impl.ClanUpdateEvent.tick().
unban()
void com.runehive.content.clanchannel.channel.ClanChannel.unban (Player player, int index)
Definition at line 208 of file ClanChannel.java.
{
        if (index < 0 || index >= bannedMembers.size())
            return;
        String name = bannedMembers.get(index);
        if (bannedMembers.remove(index) != null) {
            int string = 51311;
            int size = bannedMembers.size() < 10 ? 10 : bannedMembers.size();
            for (int idx = 0; idx < size; idx++) {
                boolean valid = idx < bannedMembers.size();
                Optional<String> banned = valid ? Optional.of(bannedMembers.get(idx)) : Optional.empty();
                player.send(new SendString(banned.orElse(""), string));
                player.send(new SendTooltip(valid ? "Unban " + bannedMembers.get(idx) : "", string));
                string++;
            }
            player.send(new SendScrollbar(51310, size * 23));
            player.send(new SendMessage("You have unbanned " + name + " from the clan chat channel."));
        }
    }
References bannedMembers, com.runehive.game.world.entity.mob.player.Player.send(), and size().
Member Data Documentation
active
int com.runehive.content.clanchannel.channel.ClanChannel.active private
The total active logged in members.
Definition at line 57 of file ClanChannel.java.
Referenced by activeSize(), ban(), disconnect(), and establish().
bannedMembers
final List<String> com.runehive.content.clanchannel.channel.ClanChannel.bannedMembers = new ArrayList<>() package
A list of banned members.
Definition at line 54 of file ClanChannel.java.
Referenced by ban(), isBanned(), toJson(), and unban().
details
ClanDetails com.runehive.content.clanchannel.channel.ClanChannel.details = new ClanDetails(this) private
The clan channel details.
Definition at line 39 of file ClanChannel.java.
Referenced by activateAchievement(), activateTask(), add(), addExperience(), ban(), compareTo(), connect(), disconnect(), equals(), establish(), getDetails(), getOwner(), hashCode(), receiveTask(), and toJson().
GSON
final Gson com.runehive.content.clanchannel.channel.ClanChannel.GSON = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create() static private
Definition at line 36 of file ClanChannel.java.
Referenced by load(), and toJson().
handler
ClanChannelHandler com.runehive.content.clanchannel.channel.ClanChannel.handler = new ClanChannelHandler(this) private
The clan channel handler.
Definition at line 48 of file ClanChannel.java.
Referenced by add(), connect(), establish(), and getHandler().
management
ClanManagement com.runehive.content.clanchannel.channel.ClanChannel.management = new ClanManagement(this) private
The clan channel management tab panel.
Definition at line 42 of file ClanChannel.java.
Referenced by canEnter(), canManage(), chat(), compareTo(), equals(), getColor(), getManagement(), getName(), getPassword(), getSlogan(), getTag(), hasPassword(), isLocked(), isPassword(), lootshareEnabled(), setName(), setTag(), and toJson().
members
final Set<ClanMember> com.runehive.content.clanchannel.channel.ClanChannel.members = new HashSet<>() private
The clan channel member set.
Definition at line 51 of file ClanChannel.java.
Referenced by addMember(), ban(), connect(), disconnect(), forEach(), forPlayers(), getMember(), getMembers(), load(), size(), and toJson().
showcase
ClanShowcase com.runehive.content.clanchannel.channel.ClanChannel.showcase = new ClanShowcase(this) private
The clan channel showcase items.
Definition at line 45 of file ClanChannel.java.
Referenced by create(), getShowcase(), getShowcaseItems(), and toJson().
The documentation for this class was generated from the following file:
java/com/runehive/content/clanchannel/channel/ClanChannel.java