RuneHive-Game: com.runehive.game.service.VoteService Class Reference
com.runehive.game.service.VoteService Class Reference
Static Public Member Functions
static void claimReward (Player player)
Static Private Attributes
static final String CONNECTION_STRING = "jdbc:mysql://173.82.152.23:3306/osroyjs_vote"
static final Logger logger = LogManager.getLogger(VoteService.class)
static final String PASS = "3AXbU=W7IfzX"
static final Item REWARD = new Item(7478, 1)
static final String USER = "osroyjs_exo1"
Detailed Description
Definition at line 14 of file VoteService.java.
Member Function Documentation
claimReward()
void com.runehive.game.service.VoteService.claimReward (Player player) static
Definition at line 22 of file VoteService.java.
{
        if (!player.databaseRequest.elapsed(1, TimeUnit.MINUTES)) {
            player.dialogueFactory.sendStatement("You can only check our database once every 1 minute!").execute();
            return;
        }
        if (!player.inventory.hasCapacityFor(REWARD)) {
            player.dialogueFactory.sendStatement("Please clear up some inventory spaces before doing this!").execute();
            return;
        }
        boolean found = false;
        player.dialogueFactory.sendStatement("Checking request...").execute();
        player.databaseRequest.reset();
        try (Connection connection = DriverManager.getConnection(CONNECTION_STRING, USER, PASS);
             PreparedStatement sta = connection.prepareStatement("SELECT * FROM fx_votes WHERE username = ? AND claimed=0 AND callback_date IS NOT NULL", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
            sta.setString(1, player.getName().replace(" ", "_"));
            try (ResultSet rs = sta.executeQuery()) {
                while (rs.next()) {
                    String timestamp = rs.getTimestamp("callback_date").toString();
                    String ipAddress = rs.getString("ip_address");
                    int siteId = rs.getInt("site_id");
                    found = true;
                    player.inventory.add(REWARD);
                    player.totalVotes += 1;
                    logger.info(String.format("[Vote] Vote claimed by %s. (sid: %d, ip: %s, time: %s)", player.getName(), siteId, ipAddress, timestamp));
                    rs.updateInt("claimed", 1); // do not delete otherwise they can reclaim!
                    rs.updateRow();
                }
            }
            if (!found) {
                player.dialogueFactory.sendStatement("There is no vote reward for you to claim!").execute();
            } else {
                AchievementHandler.activate(player, AchievementKey.VOTE);
                player.dialogueFactory.sendStatement("Thank-you for your support, " + player.getName() + "!").execute();
                World.sendMessage("<col=CF2192>osroyale: <col=" + player.right.getColor() + ">" + player.getName() + " </col>has just voted! They have voted a total of <col=CF2192>" +  player.totalVotes + " </col>times.");
            }
        } catch (SQLException ex) {
            logger.error(String.format("Error claiming vote for player=%s", player.getName()), ex);
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.items.containers.ItemContainer.add(), CONNECTION_STRING, com.runehive.game.world.entity.mob.player.Player.databaseRequest, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.util.Stopwatch.elapsed(), com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.entity.mob.player.PlayerRight.getColor(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, logger, PASS, com.runehive.util.Stopwatch.reset(), REWARD, com.runehive.game.world.entity.mob.player.Player.right, com.runehive.game.world.World.sendMessage(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.game.world.entity.mob.player.Player.totalVotes, USER, and com.runehive.content.achievement.AchievementKey.VOTE.
Member Data Documentation
CONNECTION_STRING
final String com.runehive.game.service.VoteService.CONNECTION_STRING = "jdbc:mysql://173.82.152.23:3306/osroyjs_vote" static private
Definition at line 17 of file VoteService.java.
Referenced by claimReward().
logger
final Logger com.runehive.game.service.VoteService.logger = LogManager.getLogger(VoteService.class) static private
Definition at line 16 of file VoteService.java.
Referenced by claimReward().
PASS
final String com.runehive.game.service.VoteService.PASS = "3AXbU=W7IfzX" static private
Definition at line 19 of file VoteService.java.
Referenced by claimReward().
REWARD
final Item com.runehive.game.service.VoteService.REWARD = new Item(7478, 1) static private
Definition at line 20 of file VoteService.java.
Referenced by claimReward().
USER
final String com.runehive.game.service.VoteService.USER = "osroyjs_exo1" static private
Definition at line 18 of file VoteService.java.
Referenced by claimReward().
The documentation for this class was generated from the following file:
java/com/runehive/game/service/VoteService.java