RuneHive-Game: com.runehive.content.skill.impl.thieving.WallSafe Class Reference
com.runehive.content.skill.impl.thieving.WallSafe Class Reference
Handles the wall safe thieving.
Static Public Member Functions
static int chance (Player player)
The wallsafe fail chance.
Static Package Functions
static void thieve (Player player)
Handles thieving from the wall safe.
Static Private Member Functions
static Action< Player > crack (Player player)
The wallsafe crack action.
static int rate (Player player)
Gets the thieving rate.
Static Private Attributes
static final Item REWARD []
Holds all the rewards.
Detailed Description
Handles the wall safe thieving.
Author
Daniel
Definition at line 19 of file WallSafe.java.
Member Function Documentation
chance()
int com.runehive.content.skill.impl.thieving.WallSafe.chance (Player player) static
The wallsafe fail chance.
Definition at line 52 of file WallSafe.java.
{
        return (Utility.random((int) Math.floor(player.skills.getMaxLevel(Skill.THIEVING / 10) + 1)));
    }
References com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.util.Utility.random(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.skill.Skill.THIEVING.
Referenced by crack().
crack()
Action< Player > com.runehive.content.skill.impl.thieving.WallSafe.crack (Player player) static private
The wallsafe crack action.
Definition at line 57 of file WallSafe.java.
{
        return new Action<Player>(player, 3, true) {
            int rate = rate(player);
            int tick = 0;
            @Override
            public void execute() {
                if (tick++ != rate) {
                    player.animate(new Animation(881));
                    return;
                }
                if (chance(player) == 0) {
                    player.animate(new Animation(404));
                    player.send(new SendMessage("You slip and trigger a trap!"));
                    player.damage(new Hit(Utility.random(1, 5)));
                    cancel();
                    return;
                }
                player.send(new SendMessage("You get some loot."));
                player.inventory.add(Utility.randomElement(REWARD));
                player.skills.addExperience(Skill.THIEVING, 100 * Config.THIEVING_MODIFICATION);
                cancel();
            }
            @Override
            protected void onSchedule() {
                player.skills.get(Skill.THIEVING).setDoingSkill(true);
                player.send(new SendMessage("You attempt to crack the safe... "));
            }
            @Override
            protected void onCancel(boolean logout) {
                player.skills.get(Skill.THIEVING).setDoingSkill(false);
            }
            @Override
            public String getName() {
                return "Wallsafe crack";
            }
            @Override
            public boolean prioritized() {
                return false;
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
        };
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), chance(), com.runehive.game.world.entity.mob.Mob.damage(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), rate(), REWARD, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.skill.Skill.setDoingSkill(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.skill.Skill.THIEVING, and com.runehive.Config.THIEVING_MODIFICATION.
Referenced by thieve().
rate()
int com.runehive.content.skill.impl.thieving.WallSafe.rate (Player player) static private
Gets the thieving rate.
Definition at line 44 of file WallSafe.java.
{
        boolean stethoscope = player.inventory.contains(new Item(5560));
        int calculation = stethoscope ? Utility.random(5) : (Utility.random(11) + 20);
        int calculated = (10 - (int) Math.floor(player.skills.getMaxLevel(Skill.THIEVING) / 10) + calculation) / 2;
        return calculated <= 0 ? 1 : (calculated > 10 ? 10 : calculated);
    }
References com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.util.Utility.random(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.skill.Skill.THIEVING.
Referenced by crack().
thieve()
void com.runehive.content.skill.impl.thieving.WallSafe.thieve (Player player) static package
Handles thieving from the wall safe.
Definition at line 28 of file WallSafe.java.
{
        if (player.skills.getMaxLevel(Skill.THIEVING) < 50) {
            player.dialogueFactory.sendStatement("You need a thieving level of 50 to do this!").execute();
            return;
        }
        if (player.inventory.remaining() == 0) {
            player.dialogueFactory.sendStatement("You do not have inventory spaces to do this!").execute();
            return;
        }
        if (player.skills.get(Skill.THIEVING).isDoingSkill()) {
            return;
        }
        player.action.execute(crack(player), true);
    }
References com.runehive.game.world.entity.mob.Mob.action, crack(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.skill.Skill.isDoingSkill(), com.runehive.game.world.items.containers.ItemContainer.remaining(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.skill.Skill.THIEVING.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickObject().
Member Data Documentation
REWARD
final Item com.runehive.content.skill.impl.thieving.WallSafe.REWARD[] static private
Initial value:
= {
            new Item(1617), new Item(1619), new Item(1621), new Item(1623),
            new Item(1623), new Item(995, 20), new Item(995, 40)
    }
Holds all the rewards.
Definition at line 22 of file WallSafe.java.
{
            new Item(1617), new Item(1619), new Item(1621), new Item(1623),
            new Item(1623), new Item(995, 20), new Item(995, 40)
    };
Referenced by crack().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/thieving/WallSafe.java