RuneHive-Game: com.runehive.content.skill.impl.runecrafting.RunecraftPouch Class Reference
com.runehive.content.skill.impl.runecrafting.RunecraftPouch Class Reference
The runecraft pouch.
Public Member Functions
boolean death (Item item)
Handles player dying with a rune pouch.
void deposit (RunecraftPouchData pouch)
Deposits essence into the player's runecraft pouch.
RunecraftPouch (Player player)
Constructs a new RunecraftPouch.
void withdraw (RunecraftPouchData pouch)
Withdraws essence from the player's rune essence pouch.
Private Attributes
final Player player
The player instance.
Detailed Description
The runecraft pouch.
Author
Daniel
Definition at line 12 of file RunecraftPouch.java.
Constructor & Destructor Documentation
RunecraftPouch()
com.runehive.content.skill.impl.runecrafting.RunecraftPouch.RunecraftPouch (Player player)
Constructs a new RunecraftPouch.
Definition at line 17 of file RunecraftPouch.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
death()
boolean com.runehive.content.skill.impl.runecrafting.RunecraftPouch.death (Item item)
Handles player dying with a rune pouch.
Definition at line 57 of file RunecraftPouch.java.
{
        RunecraftPouchData pouch = RunecraftPouchData.forItem(item.getId());
        if (pouch == null)
            return false;
        pouch.empty(player);
        return true;
    }
References com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.empty(), com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.forItem(), com.runehive.game.world.items.Item.getId(), and player.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems().
deposit()
void com.runehive.content.skill.impl.runecrafting.RunecraftPouch.deposit (RunecraftPouchData pouch)
Deposits essence into the player's runecraft pouch.
Definition at line 22 of file RunecraftPouch.java.
{
        if (player.skills.getMaxLevel(Skill.RUNECRAFTING) < pouch.level) {
            player.message("You need a runecrafting level of " + pouch.level + " to use this pouch!");
            return;
        }
        int inventory = player.inventory.computeAmountForId(7936);
        if (inventory == 0) {
            player.message("You have no rune essences in your inventory to fill this pouch!");
            return;
        }
        int essence = pouch.deposit(player, pouch.capacity);
        System.out.println(essence);
        if (essence != 0) {
            player.inventory.remove(7936, essence);
            player.message("You have filled your pouch with " + essence + " rune essences!");
        }
    }
References com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.capacity, com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.deposit(), com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.level, player, and com.runehive.game.world.entity.skill.Skill.RUNECRAFTING.
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.clickItem().
withdraw()
void com.runehive.content.skill.impl.runecrafting.RunecraftPouch.withdraw (RunecraftPouchData pouch)
Withdraws essence from the player's rune essence pouch.
Definition at line 47 of file RunecraftPouch.java.
{
        int essence = pouch.withdraw(player);
        if (essence != 0) {
            player.inventory.add(7936, essence);
            player.message("You have emptied your pouch.");
        }
    }
References player, and com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.withdraw().
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.clickItem().
Member Data Documentation
player
final Player com.runehive.content.skill.impl.runecrafting.RunecraftPouch.player private
The player instance.
Definition at line 14 of file RunecraftPouch.java.
Referenced by death(), deposit(), RunecraftPouch(), and withdraw().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/runecrafting/RunecraftPouch.java