RuneHive-Game: com.runehive.content.wintertodt.Brazier Class Reference
com.runehive.content.wintertodt.Brazier Class Reference
Public Member Functions
Brazier (GameObject object, Npc pyromancer, int flameOffsetX, int flameOffsetY, Direction direction)
int getBrazierState ()
int getFlameOffsetX ()
int getFlameOffsetY ()
GameObject getObject ()
Npc getPyromancer ()
boolean hasSnowStorm ()
boolean isPyromancerAlive ()
void setObject (int objectId)
void setSnowStorm (boolean snowStorm)
Public Attributes
Direction direction
Private Attributes
int flameOffsetX
int flameOffsetY
GameObject object
Npc pyromancer
boolean snowStorm
Detailed Description
Definition at line 8 of file Brazier.java.
Constructor & Destructor Documentation
Brazier()
com.runehive.content.wintertodt.Brazier.Brazier (GameObject object, Npc pyromancer, int flameOffsetX, int flameOffsetY, Direction direction)
Definition at line 16 of file Brazier.java.
{
        this.object = object;
        this.pyromancer = pyromancer;
        this.flameOffsetX = flameOffsetX;
        this.flameOffsetY = flameOffsetY;
        this.direction = direction;
    }
References direction, flameOffsetX, flameOffsetY, object, and pyromancer.
Member Function Documentation
getBrazierState()
int com.runehive.content.wintertodt.Brazier.getBrazierState ()
Definition at line 52 of file Brazier.java.
{
        return object.getId() == Wintertodt.EMPTY_BRAZIER_ID ? 0 :
                (object.getId() == Wintertodt.BURNING_BRAZIER_ID ? 1 : 3);
    }
References com.runehive.content.wintertodt.Wintertodt.BURNING_BRAZIER_ID, and com.runehive.content.wintertodt.Wintertodt.EMPTY_BRAZIER_ID.
getFlameOffsetX()
int com.runehive.content.wintertodt.Brazier.getFlameOffsetX ()
Definition at line 36 of file Brazier.java.
{
        return flameOffsetX;
    }
References flameOffsetX.
Referenced by com.runehive.content.wintertodt.Wintertodt.shootFlame().
getFlameOffsetY()
int com.runehive.content.wintertodt.Brazier.getFlameOffsetY ()
Definition at line 40 of file Brazier.java.
{
        return flameOffsetY;
    }
References flameOffsetY.
Referenced by com.runehive.content.wintertodt.Wintertodt.shootFlame().
getObject()
GameObject com.runehive.content.wintertodt.Brazier.getObject ()
Definition at line 24 of file Brazier.java.
{
        return object;
    }
References object.
Referenced by com.runehive.content.wintertodt.Wintertodt.breakBrazier(), and com.runehive.content.wintertodt.Wintertodt.shootFlame().
getPyromancer()
Npc com.runehive.content.wintertodt.Brazier.getPyromancer ()
Definition at line 28 of file Brazier.java.
{
        return pyromancer;
    }
References pyromancer.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), and com.runehive.content.wintertodt.Wintertodt.healPyromancer().
hasSnowStorm()
boolean com.runehive.content.wintertodt.Brazier.hasSnowStorm ()
Definition at line 44 of file Brazier.java.
{
        return snowStorm;
    }
References snowStorm.
isPyromancerAlive()
boolean com.runehive.content.wintertodt.Brazier.isPyromancerAlive ()
Definition at line 32 of file Brazier.java.
{
        return pyromancer.id == Wintertodt.PYROMANCER;
    }
References com.runehive.content.wintertodt.Wintertodt.PYROMANCER.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), and com.runehive.content.wintertodt.Wintertodt.lightBrazier().
setObject()
void com.runehive.content.wintertodt.Brazier.setObject (int objectId)
Definition at line 57 of file Brazier.java.
{
        this.object = new CustomGameObject(objectId, this.object.getPosition(), this.object.getDirection(), this.object.getObjectType());
    }
Referenced by com.runehive.content.wintertodt.Wintertodt.breakBrazier().
setSnowStorm()
void com.runehive.content.wintertodt.Brazier.setSnowStorm (boolean snowStorm)
Definition at line 48 of file Brazier.java.
{
        this.snowStorm = snowStorm;
    }
References snowStorm.
Referenced by com.runehive.content.wintertodt.Wintertodt.breakBrazier().
Member Data Documentation
direction
Direction com.runehive.content.wintertodt.Brazier.direction
Definition at line 14 of file Brazier.java.
Referenced by Brazier(), and com.runehive.content.wintertodt.Wintertodt.shootFlame().
flameOffsetX
int com.runehive.content.wintertodt.Brazier.flameOffsetX private
Definition at line 13 of file Brazier.java.
Referenced by Brazier(), and getFlameOffsetX().
flameOffsetY
int com.runehive.content.wintertodt.Brazier.flameOffsetY private
Definition at line 13 of file Brazier.java.
Referenced by Brazier(), and getFlameOffsetY().
object
GameObject com.runehive.content.wintertodt.Brazier.object private
Definition at line 10 of file Brazier.java.
Referenced by Brazier(), and getObject().
pyromancer
Npc com.runehive.content.wintertodt.Brazier.pyromancer private
Definition at line 11 of file Brazier.java.
Referenced by Brazier(), and getPyromancer().
snowStorm
boolean com.runehive.content.wintertodt.Brazier.snowStorm private
Definition at line 12 of file Brazier.java.
Referenced by hasSnowStorm(), and setSnowStorm().
The documentation for this class was generated from the following file:
java/com/runehive/content/wintertodt/Brazier.java