RuneHive-Game: com.runehive.game.world.position.Area Class Reference
com.runehive.game.world.position.Area Class Reference abstract
Handles checking if mobs are in a certain area.
Public Member Functions
abstract Position getRandomLocation ()
abstract boolean inArea (Position position)
Static Public Member Functions
static boolean inAllArea (Interactable entity, Area... area)
static boolean inAnyArea (Interactable entity, Area... area)
static boolean inArdougneCourse (Interactable entity)
static boolean inBandos (Mob mob)
static boolean inBarbarianCourse (Interactable entity)
static boolean inBarrows (Entity entity)
static boolean inBarrowsChamber (Interactable entity)
static boolean inCatacombs (Interactable entity)
static boolean inCerberus (Interactable entity)
static boolean inCyclops (Interactable entity)
static boolean inDuelArena (Interactable entity)
static boolean inDuelArenaLobby (Entity entity)
static boolean inDuelObsticleArena (Interactable entity)
static boolean inEdgeville (Interactable entity)
static boolean inFeroxEnclave (Interactable entity)
static boolean inFightCaves (Interactable entity)
static boolean inGnomeCourse (Interactable entity)
static boolean inGodwars (Interactable entity)
static boolean inGodwarsChambers (Mob mob)
static boolean inInferno (Entity entity)
static boolean inKingBlackDragon (Interactable entity)
static boolean inkolodionArena (Entity entity)
static boolean inKraken (Interactable entity)
static boolean inLMSBuilding (Interactable entity)
static boolean inLMSGame (Interactable entity)
static boolean inLMSLobby (Interactable entity)
static boolean inMulti (Entity entity)
static boolean inPestControl (Interactable entity)
static boolean inPvP (Interactable entity)
static boolean inRegularDonatorZone (Interactable entity)
static boolean inRestrictedArea (Mob mob)
static boolean inRFD (Interactable entity)
static boolean inSeersCourse (Interactable entity)
static boolean inSuperDonatorZone (Interactable entity)
static boolean inVorkath (Interactable entity)
static boolean inWarriorGuild (Interactable entity)
static boolean inWilderness (Interactable entity)
static boolean inWilderness (Position position)
static boolean inWildernessCourse (Interactable entity)
static boolean inWildernessResource (Interactable entity)
static boolean inZulrah (Interactable entity)
Static Public Attributes
static final Area[] INFERNO = { new SquareArea("Arena Zone", 2243, 5314, 2300, 5372) }
static final Boundary NEX = new Boundary(2900, 5183, 2943, 5227)
static final Area[] WILDERNESS_RESOURCE = { new SquareArea("Wilderness Resource", 3174, 3924, 3196, 3944) }
The collection of areas that resemble the wilderness resource area.
Static Private Member Functions
static boolean inArea (Interactable interactable, Position bottomLeft, Position topRight)
static boolean inArmadyl (Mob mob)
static boolean inSaradomin (Mob mob)
static boolean inZamorak (Mob mob)
Static Private Attributes
static final Area ARMADYL_ROOM = new SquareArea("Armadyl room", 2824, 5296, 2842, 5308, 2)
static final Area BANDOS_ROOM = new SquareArea("General Graardor room", 2864, 5351, 2876, 5369, 2)
The General Graardor room.
static final Area[] BARROWS
static final Area[] CATACOMBS = { new SquareArea("Catacombs", 1591, 9982, 1736, 10111) }
static final Area[] DUEL_ARENA_LOBBY
The collection of areas that resemble the duel arena.
static final SquareArea[] DUEL_ARENAS
static final SquareArea[] DUEL_OBSTICLE_ARENAS
static final Area DZ = new SquareArea("Donator Zone", 2462, 10422, 2493, 10463)
static final Area[] EVENT_ARENA = { new SquareArea("Event Arena", 3082, 3506, 3089, 3513) }
static final Area[] FEROX_ENCLAVE
static final Area[] KBD = { new SquareArea("King Black Dragon lair", 2256, 4680, 2287, 4711) }
The collection of areas that resemble the king black dragon area.
static final Area[] KRAKEN = { new SquareArea("Kraken Cave", 2268, 10022, 2292, 10046) }
The collection of areas that resemble the kraken area.
static final Area[] LMS_BUILDING = { new SquareArea("LMS Lobby", 3140, 3632, 3144, 3638) }
static final Area[] LMS_GAME = {new SquareArea("LMS Game", 3392, 5760, 3519, 5893) }
static final Area[] LMS_LOBBY = { new SquareArea("LMS Lobby", 3138, 3639, 3145, 3645) }
static final Area[] MULTI_COMBAT_ZONES
The collection of areas that resemble multi-combat zones.
static final Area[] PEST_CONTROL_GAME = { new SquareArea("Pest Control Game", 2622, 2558, 2693, 2627) }
static final Area RFD_MINIGAME = new SquareArea("RFD Minigame", 1889, 5345, 1910, 5366, 2)
The General Graardor room.
static final Area[] SAFEZONE
static final Area SARADOMIN_ROOM = new SquareArea("Saradomin room", 2889, 5258, 2907, 5275, 0)
static final Area SDZ = new SquareArea("Super Donator Zone", 2398, 10404, 2444, 10440)
static final Area[] WILDERNESS
The collection of areas that resemble the wilderness area.
static final Area ZAMORAK_ROOM = new SquareArea("Zamorak room", 2918, 5318, 2936, 5331, 2)
static final Area[] ZULRAH = { new SquareArea("Zulrah", 2235, 3050, 2288, 3083) }
The collection of areas that resemble the zulrah area.
Detailed Description
Handles checking if mobs are in a certain area.
Author
Daniel
Definition at line 13 of file Area.java.
Member Function Documentation
getRandomLocation()
abstract Position com.runehive.game.world.position.Area.getRandomLocation () abstract
Reimplemented in com.runehive.game.world.position.impl.CircleArea, and com.runehive.game.world.position.impl.SquareArea.
inAllArea()
boolean com.runehive.game.world.position.Area.inAllArea (Interactable entity, Area... area) static
Definition at line 401 of file Area.java.
{
        for (Area zone : area) {
            if (!zone.inArea(entity.getPosition())) {
                return false;
            }
        }
        return true;
    }
inAnyArea()
boolean com.runehive.game.world.position.Area.inAnyArea (Interactable entity, Area... area) static
Definition at line 410 of file Area.java.
{
        for (Area zone : area) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
inArdougneCourse()
boolean com.runehive.game.world.position.Area.inArdougneCourse (Interactable entity) static
Definition at line 167 of file Area.java.
{
        return inArea(entity, new Position(2642, 3285, entity.getHeight()), new Position(2681, 3331, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
inArea() [1/2]
boolean com.runehive.game.world.position.Area.inArea (Interactable interactable, Position bottomLeft, Position topRight) static private
Definition at line 394 of file Area.java.
{
        return (interactable.getPosition().getX() >= bottomLeft.getX())
                && (interactable.getPosition().getX() <= topRight.getX())
                && (interactable.getPosition().getY() >= bottomLeft.getY())
                && (interactable.getPosition().getY() <= topRight.getY());
    }
References com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.position.Position.getX(), and com.runehive.game.world.position.Position.getY().
Referenced by inArdougneCourse(), inBarbarianCourse(), inBarrowsChamber(), inCerberus(), inCyclops(), inEdgeville(), inFightCaves(), inGnomeCourse(), inGodwars(), inkolodionArena(), inSeersCourse(), inVorkath(), inWarriorGuild(), inWildernessCourse(), and inWildernessResource().
inArea() [2/2]
abstract boolean com.runehive.game.world.position.Area.inArea (Position position) abstract
Reimplemented in com.runehive.game.world.position.impl.CircleArea, and com.runehive.game.world.position.impl.SquareArea.
inArmadyl()
boolean com.runehive.game.world.position.Area.inArmadyl (Mob mob) static private
Definition at line 374 of file Area.java.
{
        return ARMADYL_ROOM.inArea(mob.getPosition());
    }
References ARMADYL_ROOM, and com.runehive.game.world.entity.Entity.getPosition().
Referenced by inGodwarsChambers().
inBandos()
boolean com.runehive.game.world.position.Area.inBandos (Mob mob) static
Definition at line 366 of file Area.java.
{
        return BANDOS_ROOM.inArea(mob.getPosition());
    }
References BANDOS_ROOM, and com.runehive.game.world.entity.Entity.getPosition().
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.hitsplat(), and inGodwarsChambers().
inBarbarianCourse()
boolean com.runehive.game.world.position.Area.inBarbarianCourse (Interactable entity) static
Definition at line 159 of file Area.java.
{
        return inArea(entity, new Position(2529, 3542, entity.getHeight()), new Position(2553, 3559, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), and inRestrictedArea().
inBarrows()
boolean com.runehive.game.world.position.Area.inBarrows (Entity entity) static
Definition at line 254 of file Area.java.
{
        for (Area zone : BARROWS) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References BARROWS.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.onRegionChange(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity().
inBarrowsChamber()
boolean com.runehive.game.world.position.Area.inBarrowsChamber (Interactable entity) static
Definition at line 179 of file Area.java.
{
        return inArea(entity, new Position(3547, 9690, entity.getHeight()), new Position(3556, 9699, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.game.task.impl.CeillingCollapseTask.tick().
inCatacombs()
boolean com.runehive.game.world.position.Area.inCatacombs (Interactable entity) static
Definition at line 204 of file Area.java.
{
        for(Area zone : CATACOMBS) {
            if(zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References CATACOMBS.
Referenced by com.runehive.content.combat.cannon.CannonManager.drop().
inCerberus()
boolean com.runehive.game.world.position.Area.inCerberus (Interactable entity) static
Definition at line 125 of file Area.java.
{
        return inArea(entity, new Position(1217, 1223, 0), new Position(1262, 1264, 0));
    }
References inArea().
Referenced by inRestrictedArea(), com.runehive.content.activity.impl.CerberusActivity.onRegionChange(), com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start().
inCyclops()
boolean com.runehive.game.world.position.Area.inCyclops (Interactable entity) static
Definition at line 140 of file Area.java.
{
        return inArea(entity, new Position(2847, 3532, 2), new Position(2876, 3542, 2)) ||
                inArea(entity, new Position(2838, 3543, 2), new Position(2877, 3577, 2));
    }
References inArea().
Referenced by com.runehive.game.task.impl.WarriorGuildCyclopEvent.execute(), and inRestrictedArea().
inDuelArena()
boolean com.runehive.game.world.position.Area.inDuelArena (Interactable entity) static
Definition at line 311 of file Area.java.
{
        for (Area zone : DUEL_ARENAS) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References DUEL_ARENAS.
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.content.overrides.Overrides.hasOverride(), inRestrictedArea(), com.runehive.game.world.entity.mob.player.Player.onStep(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setContextMenu().
inDuelArenaLobby()
boolean com.runehive.game.world.position.Area.inDuelArenaLobby (Entity entity) static
Definition at line 293 of file Area.java.
{
        for (Area zone : DUEL_ARENA_LOBBY) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References DUEL_ARENA_LOBBY.
Referenced by inRestrictedArea(), com.runehive.game.world.entity.mob.player.Player.onStep(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setContextMenu().
inDuelObsticleArena()
boolean com.runehive.game.world.position.Area.inDuelObsticleArena (Interactable entity) static
Definition at line 302 of file Area.java.
{
        for (Area zone : DUEL_OBSTICLE_ARENAS) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References DUEL_OBSTICLE_ARENAS.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack(), inRestrictedArea(), com.runehive.game.world.entity.mob.player.Player.onStep(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setContextMenu().
inEdgeville()
boolean com.runehive.game.world.position.Area.inEdgeville (Interactable entity) static
Definition at line 121 of file Area.java.
{
        return inArea(entity, new Position(3075, 3457, 0), new Position(3116, 3518, 0));
    }
References inArea().
Referenced by com.runehive.content.skill.impl.firemaking.FiremakingAction.canInit().
inFeroxEnclave()
boolean com.runehive.game.world.position.Area.inFeroxEnclave (Interactable entity) static
Definition at line 196 of file Area.java.
{
        for(Area zone : FEROX_ENCLAVE) {
            if(zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References FEROX_ENCLAVE.
Referenced by inWilderness().
inFightCaves()
boolean com.runehive.game.world.position.Area.inFightCaves (Interactable entity) static
Definition at line 129 of file Area.java.
{
        return inArea(entity, new Position(2368, 5057, 0), new Position(2428, 5120, 0));
    }
References inArea().
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.combat.CombatTarget.compare(), inRestrictedArea(), and com.runehive.content.activity.impl.fightcaves.FightCaves.onRegionChange().
inGnomeCourse()
boolean com.runehive.game.world.position.Area.inGnomeCourse (Interactable entity) static
Definition at line 155 of file Area.java.
{
        return inArea(entity, new Position(2464, 3412, entity.getHeight()), new Position(2490, 3444, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), and inRestrictedArea().
inGodwars()
boolean com.runehive.game.world.position.Area.inGodwars (Interactable entity) static
Definition at line 133 of file Area.java.
{
        return inArea(entity, new Position(2810, 5250, entity.getHeight()), new Position(2950, 5370, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.combat.CombatTarget.compare(), inMulti(), inRestrictedArea(), com.runehive.content.activity.impl.godwars.GodwarsActivity.onRegionChange(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity().
inGodwarsChambers()
boolean com.runehive.game.world.position.Area.inGodwarsChambers (Mob mob) static
Definition at line 382 of file Area.java.
{
        return inBandos(mob) || inSaradomin(mob) || inArmadyl(mob) || inZamorak(mob);
    }
References inArmadyl(), inBandos(), inSaradomin(), and inZamorak().
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), and inRestrictedArea().
inInferno()
boolean com.runehive.game.world.position.Area.inInferno (Entity entity) static
Definition at line 245 of file Area.java.
{
        for (Area zone1 : INFERNO) {
            if (zone1.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References INFERNO.
Referenced by inRestrictedArea(), and com.runehive.content.activity.inferno.Inferno.onRegionChange().
inKingBlackDragon()
boolean com.runehive.game.world.position.Area.inKingBlackDragon (Interactable entity) static
Definition at line 187 of file Area.java.
{
        for (Area zone : KBD) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References KBD.
Referenced by inMulti(), inRestrictedArea(), and inWilderness().
inkolodionArena()
boolean com.runehive.game.world.position.Area.inkolodionArena (Entity entity) static
Definition at line 145 of file Area.java.
{
        return entity.instance != Mob.DEFAULT_INSTANCE && inArea(entity, new Position(3092, 3921, entity.getHeight()), new Position(3117, 3947, entity.getHeight()));
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, and inArea().
Referenced by inMulti(), inRestrictedArea(), and com.runehive.content.activity.impl.magearena.MageArena.onRegionChange().
inKraken()
boolean com.runehive.game.world.position.Area.inKraken (Interactable entity) static
Definition at line 237 of file Area.java.
{
        for (Area zone : KRAKEN) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References KRAKEN.
Referenced by com.runehive.content.activity.impl.kraken.KrakenActivity.finish(), inMulti(), inRestrictedArea(), com.runehive.content.activity.impl.kraken.KrakenActivity.onRegionChange(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity().
inLMSBuilding()
boolean com.runehive.game.world.position.Area.inLMSBuilding (Interactable entity) static
Definition at line 223 of file Area.java.
{
        for(Area zone : LMS_BUILDING) {
            if(zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References LMS_BUILDING.
Referenced by inRestrictedArea(), inWilderness(), com.runehive.game.world.entity.mob.player.Player.onStep(), and com.runehive.game.world.entity.mob.player.Player.sequence().
inLMSGame()
boolean com.runehive.game.world.position.Area.inLMSGame (Interactable entity) static
Definition at line 337 of file Area.java.
{
        for (Area zone : LMS_GAME) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References LMS_GAME.
Referenced by inRestrictedArea().
inLMSLobby()
boolean com.runehive.game.world.position.Area.inLMSLobby (Interactable entity) static
Definition at line 214 of file Area.java.
{
        for(Area zone : LMS_LOBBY) {
            if(zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References LMS_LOBBY.
Referenced by inRestrictedArea(), inWilderness(), com.runehive.game.world.entity.mob.player.Player.onStep(), and com.runehive.game.world.entity.mob.player.Player.sequence().
inMulti()
boolean com.runehive.game.world.position.Area.inMulti (Entity entity) static
Definition at line 263 of file Area.java.
{
        for (Area zone : MULTI_COMBAT_ZONES) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return /*inEventArena(entity) ||*/ inVorkath(entity) || inkolodionArena(entity) || inKraken(entity) || inKingBlackDragon(entity) || inGodwars(entity) || inZulrah(entity);
    }
References inGodwars(), inKingBlackDragon(), inkolodionArena(), inKraken(), inVorkath(), inZulrah(), and MULTI_COMBAT_ZONES.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.areaAction(), com.runehive.content.lms.LMSGame.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.mob.player.Player.onStep(), and com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath().
inPestControl()
boolean com.runehive.game.world.position.Area.inPestControl (Interactable entity) static
Definition at line 329 of file Area.java.
{
        for (Area zone : PEST_CONTROL_GAME) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References PEST_CONTROL_GAME.
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.finish(), inRestrictedArea(), and com.runehive.content.activity.impl.pestcontrol.PestControlGame.onRegionChange().
inPvP()
boolean com.runehive.game.world.position.Area.inPvP (Interactable entity) static
Definition at line 355 of file Area.java.
{
        boolean pvp = false;
        for (Area zone : SAFEZONE) {
            if (zone.inArea(entity.getPosition())) {
                pvp = true;
                break;
            }
        }
        return !pvp;
    }
References SAFEZONE.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.task.impl.PvPTimerTask.execute(), and com.runehive.game.world.entity.mob.player.Player.onStep().
inRegularDonatorZone()
boolean com.runehive.game.world.position.Area.inRegularDonatorZone (Interactable entity) static
Definition at line 151 of file Area.java.
{
        return DZ.inArea(entity.getPosition());
    }
References DZ.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.thieving.PickpocketAction.execute(), com.runehive.content.skill.impl.mining.MiningAction.mine(), and com.runehive.game.world.entity.mob.player.Player.onStep().
inRestrictedArea()
boolean com.runehive.game.world.position.Area.inRestrictedArea (Mob mob) static
Definition at line 385 of file Area.java.
{
        return inGodwarsChambers(mob) || inCerberus(mob) || inBarbarianCourse(mob)
                || inCyclops(mob) || inDuelArena(mob) || inDuelArenaLobby(mob) || inFightCaves(mob) || inDuelObsticleArena(mob)
                || inGnomeCourse(mob) || inGodwars(mob) || inGodwarsChambers(mob) || inInferno(mob) || inKingBlackDragon(mob)
                || inkolodionArena(mob) || inKraken(mob) || inLMSBuilding(mob) || inPestControl(mob)  || inRFD(mob)
                || inVorkath(mob) || inVorkath(mob) || inWilderness(mob) || inZulrah(mob) || inLMSGame(mob) || inLMSLobby(mob);
         }
References inBarbarianCourse(), inCerberus(), inCyclops(), inDuelArena(), inDuelArenaLobby(), inDuelObsticleArena(), inFightCaves(), inGnomeCourse(), inGodwars(), inGodwarsChambers(), inInferno(), inKingBlackDragon(), inkolodionArena(), inKraken(), inLMSBuilding(), inLMSGame(), inLMSLobby(), inPestControl(), inRFD(), inVorkath(), inWilderness(), and inZulrah().
Referenced by com.runehive.content.Waypoints.setWaypoint().
inRFD()
boolean com.runehive.game.world.position.Area.inRFD (Interactable entity) static
Definition at line 233 of file Area.java.
{
        return RFD_MINIGAME.inArea(entity.getPosition());
    }
References RFD_MINIGAME.
Referenced by inRestrictedArea(), and com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onRegionChange().
inSaradomin()
boolean com.runehive.game.world.position.Area.inSaradomin (Mob mob) static private
Definition at line 370 of file Area.java.
{
        return SARADOMIN_ROOM.inArea(mob.getPosition());
    }
References com.runehive.game.world.entity.Entity.getPosition(), and SARADOMIN_ROOM.
Referenced by inGodwarsChambers().
inSeersCourse()
boolean com.runehive.game.world.position.Area.inSeersCourse (Interactable entity) static
Definition at line 163 of file Area.java.
{
        return inArea(entity, new Position(2695, 3455, entity.getHeight()), new Position(2740, 3500, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
inSuperDonatorZone()
boolean com.runehive.game.world.position.Area.inSuperDonatorZone (Interactable entity) static
Definition at line 148 of file Area.java.
{
        return SDZ.inArea(entity.getPosition());
    }
References SDZ.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.thieving.PickpocketAction.execute(), com.runehive.content.skill.impl.mining.MiningAction.mine(), and com.runehive.game.world.entity.mob.player.Player.onStep().
inVorkath()
boolean com.runehive.game.world.position.Area.inVorkath (Interactable entity) static
Definition at line 183 of file Area.java.
{
        return inArea(entity, new Position(2257, 4053, entity.getHeight()), new Position(2288, 4079, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.AcidTask(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.content.activity.impl.VorkathActivity.finish(), inMulti(), inRestrictedArea(), com.runehive.content.activity.impl.VorkathActivity.onRegionChange(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity().
inWarriorGuild()
boolean com.runehive.game.world.position.Area.inWarriorGuild (Interactable entity) static
Definition at line 136 of file Area.java.
{
        return inArea(entity, new Position(2838, 3535, 0), new Position(2875, 3555, 0));
    }
References inArea().
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuild.onRegionChange(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity().
inWilderness() [1/2]
boolean com.runehive.game.world.position.Area.inWilderness (Interactable entity) static
Definition at line 281 of file Area.java.
{
        if (entity == null) return false;
        if (inKingBlackDragon(entity)) return false;
        if (inFeroxEnclave(entity) || inLMSLobby(entity) || inLMSBuilding(entity)) return false;
        for (Area wild : WILDERNESS) {
            if (wild.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References inFeroxEnclave(), inKingBlackDragon(), inLMSBuilding(), inLMSLobby(), and WILDERNESS.
inWilderness() [2/2]
boolean com.runehive.game.world.position.Area.inWilderness (Position position) static
Definition at line 272 of file Area.java.
{
        for (Area wild : WILDERNESS) {
            if (wild.inArea(position)) {
                return true;
            }
        }
        return false;
    }
References WILDERNESS.
Referenced by com.runehive.content.overrides.Overrides.addOverride(), com.runehive.game.world.items.containers.impl.LootingBag.allowed(), com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.apply(), com.runehive.game.world.entity.combat.CombatUtil.areaAction(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.content.skill.impl.firemaking.FiremakingAction.canInit(), com.runehive.content.mysterybox.MysteryBoxManager.click(), com.runehive.game.world.entity.combat.CombatTarget.compare(), com.runehive.content.skill.impl.magic.RunePouch.death(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getEffectiveRanged(), com.runehive.game.world.World.getWildernessCount(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.game.world.entity.combat.FormulaUtils.hasAmuletOfAvarice(), com.runehive.game.world.entity.combat.FormulaUtils.hasCrawsBow(), com.runehive.content.overrides.Overrides.hasOverride(), com.runehive.game.world.entity.combat.FormulaUtils.hasThammaronSceptre(), com.runehive.game.world.entity.combat.FormulaUtils.hasViggorasChainMace(), inRestrictedArea(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.overrides.Overrides.openInterface(), com.runehive.game.world.World.sendKillFeed(), com.runehive.game.world.entity.mob.npc.Npc.sequence(), com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity(), and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
inWildernessCourse()
boolean com.runehive.game.world.position.Area.inWildernessCourse (Interactable entity) static
Definition at line 171 of file Area.java.
{
        return inArea(entity, new Position(2989, 3933, entity.getHeight()), new Position(3006, 3964, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
inWildernessResource()
boolean com.runehive.game.world.position.Area.inWildernessResource (Interactable entity) static
Definition at line 175 of file Area.java.
{
        return inArea(entity, new Position(3714, 3924, entity.getHeight()), new Position(3196, 3944, entity.getHeight()));
    }
References inArea().
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), and com.runehive.game.world.World.getWildernessResourcePlayers().
inZamorak()
boolean com.runehive.game.world.position.Area.inZamorak (Mob mob) static private
Definition at line 378 of file Area.java.
{
        return ZAMORAK_ROOM.inArea(mob.getPosition());
    }
References com.runehive.game.world.entity.Entity.getPosition(), and ZAMORAK_ROOM.
Referenced by inGodwarsChambers().
inZulrah()
boolean com.runehive.game.world.position.Area.inZulrah (Interactable entity) static
Definition at line 320 of file Area.java.
{
        for (Area zone : ZULRAH) {
            if (zone.inArea(entity.getPosition())) {
                return true;
            }
        }
        return false;
    }
References ZULRAH.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.death(), inMulti(), inRestrictedArea(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.onRegionChange(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
Member Data Documentation
ARMADYL_ROOM
final Area com.runehive.game.world.position.Area.ARMADYL_ROOM = new SquareArea("Armadyl room", 2824, 5296, 2842, 5308, 2) static private
Definition at line 25 of file Area.java.
Referenced by inArmadyl().
BANDOS_ROOM
final Area com.runehive.game.world.position.Area.BANDOS_ROOM = new SquareArea("General Graardor room", 2864, 5351, 2876, 5369, 2) static private
The General Graardor room.
Definition at line 22 of file Area.java.
Referenced by inBandos().
BARROWS
final Area [] com.runehive.game.world.position.Area.BARROWS static private
Initial value:
= {
            new SquareArea("Barrows", 3533, 3261, 3585, 3328),
            new SquareArea("Barrows Underground", 3523, 9672, 3591, 9725, 3) }
Definition at line 67 of file Area.java.
{
            new SquareArea("Barrows", 3533, 3261, 3585, 3328),
            new SquareArea("Barrows Underground", 3523, 9672, 3591, 9725, 3) };
Referenced by inBarrows().
CATACOMBS
final Area [] com.runehive.game.world.position.Area.CATACOMBS = { new SquareArea("Catacombs", 1591, 9982, 1736, 10111) } static private
Definition at line 71 of file Area.java.
{ new SquareArea("Catacombs", 1591, 9982, 1736, 10111) };
Referenced by inCatacombs().
DUEL_ARENA_LOBBY
final Area [] com.runehive.game.world.position.Area.DUEL_ARENA_LOBBY static private
Initial value:
= {
            new SquareArea("Lobby", 3353, 3263, 3388, 3287),
            new SquareArea("Lobby Altar", 3374, 3280, 3379, 3286),
            new SquareArea("Lobby east bank", 3380, 3267, 3388, 3273) }
The collection of areas that resemble the duel arena.
Definition at line 74 of file Area.java.
{
            new SquareArea("Lobby", 3353, 3263, 3388, 3287),
            new SquareArea("Lobby Altar", 3374, 3280, 3379, 3286),
            new SquareArea("Lobby east bank", 3380, 3267, 3388, 3273) };
Referenced by inDuelArenaLobby().
DUEL_ARENAS
final SquareArea [] com.runehive.game.world.position.Area.DUEL_ARENAS static private
Initial value:
= {
            new SquareArea("Arena", 3327, 3203, 3389, 3290)
    }
Definition at line 106 of file Area.java.
{
            new SquareArea("Arena", 3327, 3203, 3389, 3290)
    };
Referenced by inDuelArena().
DUEL_OBSTICLE_ARENAS
final SquareArea [] com.runehive.game.world.position.Area.DUEL_OBSTICLE_ARENAS static private
Initial value:
= {
            new SquareArea("South East Obstacle Arena", 3362, 3205, 3390, 3221),
            new SquareArea("West Obstacle Arena", 3331, 3224, 3359, 3240),
            new SquareArea("North East Obstacle Arena", 3362, 3243, 3390, 3259) }
Definition at line 110 of file Area.java.
{
            new SquareArea("South East Obstacle Arena", 3362, 3205, 3390, 3221),
            new SquareArea("West Obstacle Arena", 3331, 3224, 3359, 3240),
            new SquareArea("North East Obstacle Arena", 3362, 3243, 3390, 3259) };
Referenced by inDuelObsticleArena().
DZ
final Area com.runehive.game.world.position.Area.DZ = new SquareArea("Donator Zone", 2462, 10422, 2493, 10463) static private
Definition at line 19 of file Area.java.
Referenced by inRegularDonatorZone().
EVENT_ARENA
final Area [] com.runehive.game.world.position.Area.EVENT_ARENA = { new SquareArea("Event Arena", 3082, 3506, 3089, 3513) } static private
Definition at line 65 of file Area.java.
{ new SquareArea("Event Arena", 3082, 3506, 3089, 3513) };
FEROX_ENCLAVE
final Area [] com.runehive.game.world.position.Area.FEROX_ENCLAVE static private
Initial value:
= {
            new SquareArea(3125, 3618, 3143, 3639),
            new SquareArea(3123, 3622, 3124, 3632),
            new SquareArea(3144, 3627, 3153, 3640),
            new SquareArea(3138, 3640, 3145, 3645),
            new SquareArea(3148, 3641, 3155, 3646),
            new SquareArea(3130, 3617, 3139, 3617),
            new SquareArea(3153, 3636, 3155, 3640),
            new SquareArea(3153, 3627, 3155, 3633),
            new SquareArea(3143, 3618, 3146, 3626),
            new SquareArea(3146, 3622, 3151, 3626)
    }
Definition at line 47 of file Area.java.
{
            new SquareArea(3125, 3618, 3143, 3639),
            new SquareArea(3123, 3622, 3124, 3632),
            new SquareArea(3144, 3627, 3153, 3640),
            new SquareArea(3138, 3640, 3145, 3645),
            new SquareArea(3148, 3641, 3155, 3646),
            new SquareArea(3130, 3617, 3139, 3617),
            new SquareArea(3153, 3636, 3155, 3640),
            new SquareArea(3153, 3627, 3155, 3633),
            new SquareArea(3143, 3618, 3146, 3626),
            new SquareArea(3146, 3622, 3151, 3626)
    };
Referenced by inFeroxEnclave().
INFERNO
final Area [] com.runehive.game.world.position.Area.INFERNO = { new SquareArea("Arena Zone", 2243, 5314, 2300, 5372) } static
Definition at line 28 of file Area.java.
{ new SquareArea("Arena Zone", 2243, 5314, 2300, 5372) };
Referenced by inInferno().
KBD
final Area [] com.runehive.game.world.position.Area.KBD = { new SquareArea("King Black Dragon lair", 2256, 4680, 2287, 4711) } static private
The collection of areas that resemble the king black dragon area.
Definition at line 41 of file Area.java.
{ new SquareArea("King Black Dragon lair", 2256, 4680, 2287, 4711) };
Referenced by inKingBlackDragon().
KRAKEN
final Area [] com.runehive.game.world.position.Area.KRAKEN = { new SquareArea("Kraken Cave", 2268, 10022, 2292, 10046) } static private
The collection of areas that resemble the kraken area.
Definition at line 61 of file Area.java.
{ new SquareArea("Kraken Cave", 2268, 10022, 2292, 10046) };
Referenced by inKraken().
LMS_BUILDING
final Area [] com.runehive.game.world.position.Area.LMS_BUILDING = { new SquareArea("LMS Lobby", 3140, 3632, 3144, 3638) } static private
Definition at line 45 of file Area.java.
{ new SquareArea("LMS Lobby", 3140, 3632, 3144, 3638) };
Referenced by inLMSBuilding().
LMS_GAME
final Area [] com.runehive.game.world.position.Area.LMS_GAME = {new SquareArea("LMS Game", 3392, 5760, 3519, 5893) } static private
Definition at line 62 of file Area.java.
{new SquareArea("LMS Game", 3392, 5760, 3519, 5893) };
Referenced by inLMSGame().
LMS_LOBBY
final Area [] com.runehive.game.world.position.Area.LMS_LOBBY = { new SquareArea("LMS Lobby", 3138, 3639, 3145, 3645) } static private
Definition at line 43 of file Area.java.
{ new SquareArea("LMS Lobby", 3138, 3639, 3145, 3645) };
Referenced by inLMSLobby().
MULTI_COMBAT_ZONES
final Area [] com.runehive.game.world.position.Area.MULTI_COMBAT_ZONES static private
Initial value:
= {
            new SquareArea("Lizard shamans", 1408, 3692, 1457, 3729),
            new SquareArea("Al-kahrid Warrior", 3281, 3158, 3304, 3178),
            new SquareArea("Smoke devils", 2378, 9421, 2429, 9465),
            new SquareArea("Rock Crab", 2660, 3711, 2743, 3739),
            new SquareArea("Skotizo", 2255, 5646, 2290, 5680),
            new SquareArea("Wilderness Resource", 3174, 3924, 3196, 3944),
            new SquareArea("Start of Varrock Wilderness", 3134, 3525, 3327, 3607),
            new SquareArea("North of GE, near gravestones", 3190, 3648, 3327, 3839),
            new SquareArea("Near Chaos Elemental", 3200, 3840, 3390, 3967),
            new SquareArea("Near wilderness agility course", 2992, 3912, 3007, 3967),
            new SquareArea("West wilderness altar", 2946, 3816, 2959, 3831),
            new SquareArea("Deep wilderness 1", 3008, 3856, 3199, 3903),
            new SquareArea("Near wilderness castle", 3008, 3600, 3071, 3711),
            new SquareArea("North of varrock lumbermill", 3072, 3608, 3327, 3647),
            new SquareArea("Pest control", 2624, 2550, 2690, 2619),
            new SquareArea("Fight caves", 2371, 5062, 2422, 5117),
            new SquareArea("Fight arena", 2896, 3595, 2927, 3630),
            new SquareArea("Inferno", 2243, 5314, 2300, 5372),
            new SquareArea("Scorpia lair", 3218, 10329, 3248, 10353),
            new SquareArea("Corporeal Beast lair", 2964, 4360, 3001, 4399),
            new SquareArea("Revenant Cave", 3168, 10047, 3290, 10143),
            new SquareArea("Catacombs of Kourend 1", 1588, 9982, 1747, 10068),
            new SquareArea("Catacombs of Kourend 2", 1641, 9982, 1734, 10110),
            new SquareArea("Dagannoth lair", 2890, 4425, 2942, 4466) }
The collection of areas that resemble multi-combat zones.
Definition at line 80 of file Area.java.
{
            new SquareArea("Lizard shamans", 1408, 3692, 1457, 3729),
            new SquareArea("Al-kahrid Warrior", 3281, 3158, 3304, 3178),
            new SquareArea("Smoke devils", 2378, 9421, 2429, 9465),
            new SquareArea("Rock Crab", 2660, 3711, 2743, 3739),
            new SquareArea("Skotizo", 2255, 5646, 2290, 5680),
            new SquareArea("Wilderness Resource", 3174, 3924, 3196, 3944),
            new SquareArea("Start of Varrock Wilderness", 3134, 3525, 3327, 3607),
            new SquareArea("North of GE, near gravestones", 3190, 3648, 3327, 3839),
            new SquareArea("Near Chaos Elemental", 3200, 3840, 3390, 3967),
            new SquareArea("Near wilderness agility course", 2992, 3912, 3007, 3967),
            new SquareArea("West wilderness altar", 2946, 3816, 2959, 3831),
            new SquareArea("Deep wilderness 1", 3008, 3856, 3199, 3903),
            new SquareArea("Near wilderness castle", 3008, 3600, 3071, 3711),
            new SquareArea("North of varrock lumbermill", 3072, 3608, 3327, 3647),
            new SquareArea("Pest control", 2624, 2550, 2690, 2619),
            new SquareArea("Fight caves", 2371, 5062, 2422, 5117),
            new SquareArea("Fight arena", 2896, 3595, 2927, 3630),
            new SquareArea("Inferno", 2243, 5314, 2300, 5372),
            new SquareArea("Scorpia lair", 3218, 10329, 3248, 10353),
            new SquareArea("Corporeal Beast lair", 2964, 4360, 3001, 4399),
            new SquareArea("Revenant Cave", 3168, 10047, 3290, 10143),
            new SquareArea("Catacombs of Kourend 1", 1588, 9982, 1747, 10068),//2 to leave out brutals
            new SquareArea("Catacombs of Kourend 2", 1641, 9982, 1734, 10110),
            new SquareArea("Dagannoth lair", 2890, 4425, 2942, 4466) };
Referenced by inMulti().
NEX
final Boundary com.runehive.game.world.position.Area.NEX = new Boundary(2900, 5183, 2943, 5227) static
Definition at line 26 of file Area.java.
PEST_CONTROL_GAME
final Area [] com.runehive.game.world.position.Area.PEST_CONTROL_GAME = { new SquareArea("Pest Control Game", 2622, 2558, 2693, 2627) } static private
Definition at line 63 of file Area.java.
{ new SquareArea("Pest Control Game", 2622, 2558, 2693, 2627) };
Referenced by inPestControl().
RFD_MINIGAME
final Area com.runehive.game.world.position.Area.RFD_MINIGAME = new SquareArea("RFD Minigame", 1889, 5345, 1910, 5366, 2) static private
The General Graardor room.
Definition at line 32 of file Area.java.
Referenced by inRFD().
SAFEZONE
final Area [] com.runehive.game.world.position.Area.SAFEZONE static private
Initial value:
= {
            new SquareArea("Edgeville Bank", 3091, 3488, 3098, 3499),
            new SquareArea("Edgeville Bank", 3091, 3507, 3100, 3513) }
Definition at line 15 of file Area.java.
{
            new SquareArea("Edgeville Bank", 3091, 3488, 3098, 3499),
            new SquareArea("Edgeville Bank", 3091, 3507, 3100, 3513) };
Referenced by inPvP().
SARADOMIN_ROOM
final Area com.runehive.game.world.position.Area.SARADOMIN_ROOM = new SquareArea("Saradomin room", 2889, 5258, 2907, 5275, 0) static private
Definition at line 23 of file Area.java.
Referenced by inSaradomin().
SDZ
final Area com.runehive.game.world.position.Area.SDZ = new SquareArea("Super Donator Zone", 2398, 10404, 2444, 10440) static private
Definition at line 20 of file Area.java.
Referenced by inSuperDonatorZone().
WILDERNESS
final Area [] com.runehive.game.world.position.Area.WILDERNESS static private
Initial value:
= {
            new SquareArea("Wilderness 1", 2941, 3525, 3392, 3966),
            new SquareArea("Wilderness 2", 2941, 9920, 3392, 10366),
            new SquareArea("Wilderness 3", 2250, 4672, 2296, 4721) }
The collection of areas that resemble the wilderness area.
Definition at line 116 of file Area.java.
{
            new SquareArea("Wilderness 1", 2941, 3525, 3392, 3966),
            new SquareArea("Wilderness 2", 2941, 9920, 3392, 10366),
            new SquareArea("Wilderness 3", 2250, 4672, 2296, 4721) };
Referenced by inWilderness(), and inWilderness().
WILDERNESS_RESOURCE
final Area [] com.runehive.game.world.position.Area.WILDERNESS_RESOURCE = { new SquareArea("Wilderness Resource", 3174, 3924, 3196, 3944) } static
The collection of areas that resemble the wilderness resource area.
Definition at line 35 of file Area.java.
{ new SquareArea("Wilderness Resource", 3174, 3924, 3196, 3944) };
ZAMORAK_ROOM
final Area com.runehive.game.world.position.Area.ZAMORAK_ROOM = new SquareArea("Zamorak room", 2918, 5318, 2936, 5331, 2) static private
Definition at line 24 of file Area.java.
Referenced by inZamorak().
ZULRAH
final Area [] com.runehive.game.world.position.Area.ZULRAH = { new SquareArea("Zulrah", 2235, 3050, 2288, 3083) } static private
The collection of areas that resemble the zulrah area.
Definition at line 38 of file Area.java.
{ new SquareArea("Zulrah", 2235, 3050, 2288, 3083) };
Referenced by inZulrah().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/position/Area.java