RuneHive-Game: com.runehive.content.skill.impl.crafting.CraftableItem Class Reference
com.runehive.content.skill.impl.crafting.CraftableItem Class Reference
The craftable item.
Public Member Functions
CraftableItem (Item product, Item requiredItem, int level, double experience)
Constructs a new CraftableItem.
double getExperience ()
Gets the experience rewarded.
int getLevel ()
Gets the level required.
Item getProduct ()
Gets the product item.
Item getRequiredItem ()
Gets the required items.
Private Attributes
final double experience
The craftable experience rewarded.
final int level
The craftable level required.
final Item product
The craftable product.
final Item requiredItem
The craftable required item.
Detailed Description
The craftable item.
Author
Daniel
Definition at line 10 of file CraftableItem.java.
Constructor & Destructor Documentation
CraftableItem()
com.runehive.content.skill.impl.crafting.CraftableItem.CraftableItem (Item product, Item requiredItem, int level, double experience)
Constructs a new CraftableItem.
Parameters
product The product item.
requiredItem The required item.
level The level required.
experience The experience rewarded.
Definition at line 40 of file CraftableItem.java.
{
        this.product = product;
        this.requiredItem = requiredItem;
        this.level = level;
        this.experience = experience;
    }
References experience, level, product, and requiredItem.
Member Function Documentation
getExperience()
double com.runehive.content.skill.impl.crafting.CraftableItem.getExperience ()
Gets the experience rewarded.
Returns
The experience rewarded.
Definition at line 79 of file CraftableItem.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.craft().
getLevel()
int com.runehive.content.skill.impl.crafting.CraftableItem.getLevel ()
Gets the level required.
Returns
The level required.
Definition at line 70 of file CraftableItem.java.
{
        return level;
    }
References level.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.start().
getProduct()
Item com.runehive.content.skill.impl.crafting.CraftableItem.getProduct ()
Gets the product item.
Returns
The product item.
Definition at line 52 of file CraftableItem.java.
{
        return product;
    }
References product.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.crafting.Crafting.start(), and com.runehive.content.skill.impl.crafting.Crafting.useItem().
getRequiredItem()
Item com.runehive.content.skill.impl.crafting.CraftableItem.getRequiredItem ()
Gets the required items.
Returns
The required items.
Definition at line 61 of file CraftableItem.java.
{
        return requiredItem;
    }
References requiredItem.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.start().
Member Data Documentation
experience
final double com.runehive.content.skill.impl.crafting.CraftableItem.experience private
The craftable experience rewarded.
Definition at line 30 of file CraftableItem.java.
Referenced by CraftableItem(), and getExperience().
level
final int com.runehive.content.skill.impl.crafting.CraftableItem.level private
The craftable level required.
Definition at line 25 of file CraftableItem.java.
Referenced by CraftableItem(), and getLevel().
product
final Item com.runehive.content.skill.impl.crafting.CraftableItem.product private
The craftable product.
Definition at line 15 of file CraftableItem.java.
Referenced by CraftableItem(), and getProduct().
requiredItem
final Item com.runehive.content.skill.impl.crafting.CraftableItem.requiredItem private
The craftable required item.
Definition at line 20 of file CraftableItem.java.
Referenced by CraftableItem(), and getRequiredItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/crafting/CraftableItem.java