RuneHive-Game: com.runehive.content.itemaction.impl.ClanShowcaseBox Class Reference
com.runehive.content.itemaction.impl.ClanShowcaseBox Class Reference
Public Member Functions
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean itemOnItem (Player player, Item first, Item second)
String message (Item item)
The message of the action.
String toString ()
Detailed Description
Definition at line 15 of file ClanShowcaseBox.java.
Member Function Documentation
inventory()
boolean com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 23 of file ClanShowcaseBox.java.
{
        if (opcode != 1) {
            return false;
        }
        ClanChannel channel = player.clanChannel;
        if (channel == null) {
            player.send(new SendMessage("You need to be in a clan to do this!"));
            return true;
        }
        if (channel.getShowcase().showcaseItems.size() >= 28) {
            player.send(new SendMessage("You have reached the maximum capacity of showcase items you can hold. Please delete an item to proceed."));
            return true;
        }
        ClanLevel level = channel.getDetails().level;
        List<Item> items = new ArrayList<>();
        for (int reward : ClanUtility.getRewardItems(level)) {
            Item rewardItem = new Item(reward, 1);
            for (Item showcase : channel.getShowcaseItems()) {
                if (rewardItem.getId() != showcase.getId())
                    items.add(rewardItem);
            }
        }
        if (items.isEmpty()) {
            return true;
        }
        Item showcaseReward = Utility.randomElement(items);
        player.inventory.remove(item);
        channel.getShowcase().showcaseItems.add(showcaseReward.getId());
        channel.message("We just received " + showcaseReward.getName() + " from the showcase box!");
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.clanChannel, com.runehive.content.clanchannel.channel.ClanChannel.getDetails(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.content.clanchannel.ClanUtility.getRewardItems(), com.runehive.content.clanchannel.channel.ClanChannel.getShowcase(), com.runehive.content.clanchannel.channel.ClanChannel.getShowcaseItems(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.clanchannel.channel.ClanDetails.level, com.runehive.content.clanchannel.channel.ClanChannel.message(), com.runehive.util.Utility.randomElement(), com.runehive.game.world.items.containers.ItemContainer.remove(), and com.runehive.game.world.entity.mob.player.Player.send().
name()
String com.runehive.content.itemaction.impl.ClanShowcaseBox.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 18 of file ClanShowcaseBox.java.
{
        return "Clan Showcase Box";
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/ClanShowcaseBox.java