RuneHive-Game: com.runehive.content.lms.loadouts.LMSLoadoutManager Class Reference
com.runehive.content.lms.loadouts.LMSLoadoutManager Class Reference
Static Public Member Functions
static List< LMSLoadout > getLmsLoadouts ()
static void load ()
Static Private Attributes
static List< LMSLoadout > lmsLoadouts = new ArrayList<LMSLoadout>()
static final Logger logger = LogManager.getLogger(LMSLoadoutManager.class)
Detailed Description
Definition at line 14 of file LMSLoadoutManager.java.
Member Function Documentation
getLmsLoadouts()
List< LMSLoadout > com.runehive.content.lms.loadouts.LMSLoadoutManager.getLmsLoadouts () static
Definition at line 19 of file LMSLoadoutManager.java.
{
        return lmsLoadouts;
    }
References lmsLoadouts.
Referenced by load(), and com.runehive.content.lms.LMSGame.moveToGame().
load()
void com.runehive.content.lms.loadouts.LMSLoadoutManager.load () static
Definition at line 23 of file LMSLoadoutManager.java.
{
        try (final ScanResult scanResult = new ClassGraph().enableClassInfo().enableMethodInfo().scan()) {
            for (final ClassInfo classInfo : scanResult.getSubclasses(LMSLoadout.class)) {
                try {
                    if (!classInfo.isAbstract()) {
                        final MethodInfoList constructorInfos = classInfo.getDeclaredConstructorInfo();
                        final MethodInfo constructorInfo = constructorInfos.get(0);
                        final Constructor<?> constructor = constructorInfo.loadClassAndGetConstructor();
                        final Object instance = constructor.newInstance();
                        final LMSLoadout loadout = (LMSLoadout) instance;
                        loadout.setup();
                        lmsLoadouts.add(loadout);
                    }
                } catch (Exception ex) {
                    logger.error(String.format("Error loading lms loadout=%s", classInfo.getSimpleName()), ex);
                }
            }
        }
        logger.info(String.format("Loaded: %d lms loadouts.", lmsLoadouts.size()));
        LMSLobby.currentGameType = LMSLoadoutManager.getLmsLoadouts().get(Utility.random(LMSLoadoutManager.getLmsLoadouts().size()));
    }
References com.runehive.content.lms.lobby.LMSLobby.currentGameType, getLmsLoadouts(), lmsLoadouts, logger, com.runehive.util.Utility.random(), and com.runehive.content.lms.loadouts.LMSLoadout.setup().
Referenced by com.runehive.RuneHive.start().
Member Data Documentation
lmsLoadouts
List<LMSLoadout> com.runehive.content.lms.loadouts.LMSLoadoutManager.lmsLoadouts = new ArrayList<LMSLoadout>() static private
Definition at line 17 of file LMSLoadoutManager.java.
Referenced by getLmsLoadouts(), and load().
logger
final Logger com.runehive.content.lms.loadouts.LMSLoadoutManager.logger = LogManager.getLogger(LMSLoadoutManager.class) static private
Definition at line 15 of file LMSLoadoutManager.java.
Referenced by load().
The documentation for this class was generated from the following file:
java/com/runehive/content/lms/loadouts/LMSLoadoutManager.java