RuneHive-Game: com.runehive.content.clanchannel.channel.ClanChannelHandler Class Reference
com.runehive.content.clanchannel.channel.ClanChannelHandler Class Reference
The handler for the clan channel.
Public Member Functions
void updateMemberList (ClanMember member)
Handles updating the clan channel member list.
Static Public Member Functions
static void clean (Player player)
Handles cleaning the clan tab itemcontainer.
static void connect (Player player, String owner)
Handles player joining a clan channel.
static boolean disconnect (Player player, boolean logout)
Handles player joining a clan channel.
static void manage (Player player)
static void manageMember (Player player, int button)
static void onLogin (Player player)
Handles logging into the server.
Package Functions
boolean attemptConnection (Player player, ClanMember member)
Attempts a connection to the clan channel.
ClanChannelHandler (ClanChannel channel)
Constructs a new ClanChannelHandler.
void connected (ClanMember member)
Handles connecting to the clan channel.
void sendConnectionWarning (Player player, ClanMember member)
The sends the connection warning for hopping clans.
boolean testPassword (Player player, ClanMember member)
Handles entering a clan channel password.
Private Attributes
final ClanChannel channel
The clan channel instance.
Detailed Description
The handler for the clan channel.
Author
Michael
Daniel
Definition at line 24 of file ClanChannelHandler.java.
Constructor & Destructor Documentation
ClanChannelHandler()
com.runehive.content.clanchannel.channel.ClanChannelHandler.ClanChannelHandler (ClanChannel channel) package
Constructs a new ClanChannelHandler.
Definition at line 34 of file ClanChannelHandler.java.
{
        this.channel = channel;
    }
References channel.
Member Function Documentation
attemptConnection()
boolean com.runehive.content.clanchannel.channel.ClanChannelHandler.attemptConnection (Player player, ClanMember member) package
Attempts a connection to the clan channel.
Definition at line 149 of file ClanChannelHandler.java.
{
        if (member.rank.equals(ClanRank.MEMBER)) {
            if (ProfileRepository.isFriend(player, channel.getOwner()))
                member.rank = ClanRank.FRIEND;
            if (PlayerRight.isDeveloper(player))
                member.rank = ClanRank.SYSTEM;
        }
        if (!channel.canEnter(member)) {
            player.send(new SendMessage("Connection was refused: No required permission!"));
            return false;
        }
        if (channel.isLocked() && !channel.canManage(member)) {
            player.send(new SendMessage("Connection was refused: Clan is currently locked!"));
            return false;
        }
        return true;
    }
References channel, com.runehive.content.clanchannel.ClanRank.FRIEND, com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), com.runehive.game.world.entity.mob.player.profile.ProfileRepository.isFriend(), com.runehive.content.clanchannel.ClanRank.MEMBER, com.runehive.content.clanchannel.ClanMember.rank, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.content.clanchannel.ClanRank.SYSTEM.
clean()
void com.runehive.content.clanchannel.channel.ClanChannelHandler.clean (Player player) static
Handles cleaning the clan tab itemcontainer.
Definition at line 288 of file ClanChannelHandler.java.
{
        player.send(new SendString("Talking in: <col=F7DC6F>None", 33502));
        for (int i = 0; i < 99; i += 4) {
            player.send(new SendString("", 33531 + (i + 1)));
            player.send(new SendString("", 33531 + (i + 2)));
            player.send(new SendString("", 33531 + (i + 3)));
        }
        player.send(new SendScrollbar(33530, 11 * 22));
    }
References com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.ban(), com.runehive.content.clanchannel.channel.ClanChannel.disconnect(), and onLogin().
connect()
void com.runehive.content.clanchannel.channel.ClanChannelHandler.connect (Player player, String owner) static
Handles player joining a clan channel.
Definition at line 53 of file ClanChannelHandler.java.
{
        player.send(new SendMessage("Attempting to connect to clan..."));
        ClanChannel channel = ClanRepository.getChannel(owner);
        if (channel == null) {
            boolean loaded = true;
            Path path = Paths.get("./data/content/clan/");
            File[] files = path.toFile().listFiles();
            if (files == null) {
                System.out.println("No clan files were found!");
                player.message("Clan does not exist!");
                if (owner.equalsIgnoreCase(player.getName())) {
                    ClanChannel.create(player);
                }
                return;
            }
            for (File file : files) {
                if (file.getName().toLowerCase().contains(player.getUsername().toLowerCase().trim()) && file.length() > 0) {
                    loaded = false;
                    break;
                }
            }
            if (owner.equalsIgnoreCase(player.getName())) {
                if (!loaded) {
                    player.send(new SendMessage("Your clan didn't load into the server properly!"));
                    player.send(new SendMessage("If you see this message, your clan was not reset."));
                    player.message("Try to join your clan again. If you still see this message, contact a staff member.");
                    ClanChannel.load(player.getUsername().toLowerCase().trim());
                    return;
                }
                ClanChannel.create(player);
            } else {
                if (!loaded) {
                    player.send(new SendMessage("This clan didn't load into the server properly!"));
                    player.message("Try to join your clan again. If you still see this message, contact a staff member.");
                    ClanChannel.load(player.getUsername().toLowerCase().trim());
                    return;
                }
                player.send(new SendMessage("Connection was refused: No channel exists!"));
            }
            return;
        }
        if (!channel.getOwner().equals("osroyale") && channel.activeSize() >= 80) {
            player.send(new SendMessage("Connection was refused: Channel currently full!"));
            return;
        }
        if (channel.isBanned(player.getName())) {
            player.send(new SendMessage("Connection was refused: Currently banned from channel!"));
            return;
        }
        if (channel.getDetails().type == ClanType.IRON_MAN && !PlayerRight.isIronman(player)) {
            player.message("Only Iron-man accounts can join this clan!");
            return;
        }
        channel.connect(player);
    }
References channel, com.runehive.content.clanchannel.channel.ClanChannel.create(), com.runehive.content.clanchannel.ClanRepository.getChannel(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.content.clanchannel.ClanType.IRON_MAN, com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.content.clanchannel.channel.ClanChannel.load(), com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by onLogin().
connected()
void com.runehive.content.clanchannel.channel.ClanChannelHandler.connected (ClanMember member) package
Handles connecting to the clan channel.
Definition at line 195 of file ClanChannelHandler.java.
{
        updateMemberList(member);
        member.player.ifPresent(player -> {
            player.send(new SendMessage("Now talking in clan chat <col=FFFF64><shad=0>" + Utility.formatName(channel.getName()) + "</shad></col>."));
            player.send(new SendMessage("To talk, start each line of chat with the / symbol."));
        });
    }
References channel, com.runehive.util.Utility.formatName(), com.runehive.content.clanchannel.ClanMember.player, and updateMemberList().
disconnect()
boolean com.runehive.content.clanchannel.channel.ClanChannelHandler.disconnect (Player player, boolean logout) static
Handles player joining a clan channel.
Definition at line 116 of file ClanChannelHandler.java.
{
        if (player == null || player.clanChannel == null)
            return false;
        ClanChannel channel = player.clanChannel;
        channel.disconnect(player.getName(), logout);
        return true;
    }
References channel, com.runehive.game.world.entity.mob.player.Player.clanChannel, and com.runehive.game.world.entity.mob.player.Player.getName().
Referenced by com.runehive.game.world.entity.mob.player.Player.unregister().
manage()
void com.runehive.content.clanchannel.channel.ClanChannelHandler.manage (Player player) static
Definition at line 124 of file ClanChannelHandler.java.
{
        ClanChannel channel = player.clanChannel;
        Optional<ClanMember> member = channel.getMember(player.getName());
        member.ifPresent(m -> {
            if (!channel.canManage(m)) {
                player.send(new SendMessage("You do not have sufficient privileges to manage this clan!"));
                return;
            }
            player.send(new SendString(channel.getName(), 42102));
            player.send(new SendString(channel.getTag(), 42104));
            player.send(new SendString(channel.getSlogan(), 42106));
            player.send(new SendString(channel.getPassword(), 42108));
            player.send(new SendString(channel.getDetails().type.getIcon() + "" + channel.getDetails().type.getName(), 42110));
            player.send(new SendString(channel.getManagement().getRank(ENTER_RANK_INDEX) + " " + channel.getManagement().getEnter(), 42112));
            player.send(new SendString(channel.getManagement().getRank(TALK_RANK_INDEX) + " " + channel.getManagement().getTalk(), 42114));
            player.send(new SendString(channel.getManagement().getRank(MANAGE_RANK_INDEX) + " " + channel.getManagement().getManage(), 42116));
            player.send(new SendConfig(326, channel.getManagement().locked ? 1 : 0));
            player.send(new SendItemOnInterface(42126, channel.getShowcaseItems()));
            player.interfaceManager.setSidebar(Config.CLAN_TAB, 42000);
        });
    }
References channel, com.runehive.Config.CLAN_TAB, com.runehive.game.world.entity.mob.player.Player.clanChannel, com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar().
Referenced by com.runehive.content.clanchannel.content.ClanShowcase.set(), and com.runehive.content.clanchannel.content.ClanViewer.update().
manageMember()
void com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember (Player player, int button) static
Definition at line 219 of file ClanChannelHandler.java.
{
        ClanChannel channel = player.clanChannel;
        if (channel == null)
            return;
        channel.getMember(player.getName()).ifPresent(member -> {
            if (!channel.canManage(member))
                return;
            List<ClanMember> sorted = new ArrayList<>(channel.getActiveMembers());
            sorted.sort(player.settings.clanMemberComporator);
            int ordinal = ClanUtility.getRankOrdinal(button);
            if (ordinal >= sorted.size())
                return;
            ClanMember other = sorted.get(ordinal);
            if (other != null && !other.name.equalsIgnoreCase(player.getName()) && other.rank.lessThan(ClanRank.LEADER)) {
                player.attributes.set("CLAN_RANK_MEMBER", other);
                player.send(new SendString(other.name, 43606));
                player.interfaceManager.open(43600);
            }
        });
    }
References com.runehive.game.world.entity.mob.Mob.attributes, channel, com.runehive.game.world.entity.mob.player.Player.clanChannel, com.runehive.game.world.entity.mob.player.Settings.clanMemberComporator, com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.clanchannel.ClanUtility.getRankOrdinal(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.content.clanchannel.ClanRank.LEADER, com.runehive.content.clanchannel.ClanRank.lessThan(), com.runehive.content.clanchannel.ClanMember.name, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.content.clanchannel.ClanMember.rank, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), and com.runehive.game.world.entity.mob.player.Player.settings.
onLogin()
void com.runehive.content.clanchannel.channel.ClanChannelHandler.onLogin (Player player) static
Handles logging into the server.
Definition at line 41 of file ClanChannelHandler.java.
{
        clean(player);
        if (player.clanChannel != null) {
            String owner = player.clanChannel.getOwner();
            player.clanChannel = null;
            connect(player, owner);
        }
    }
References com.runehive.game.world.entity.mob.player.Player.clanChannel, clean(), connect(), and com.runehive.content.clanchannel.channel.ClanChannel.getOwner().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.login().
sendConnectionWarning()
void com.runehive.content.clanchannel.channel.ClanChannelHandler.sendConnectionWarning (Player player, ClanMember member) package
The sends the connection warning for hopping clans.
Definition at line 206 of file ClanChannelHandler.java.
{
        player.dialogueFactory.sendStatement(
                "-<col=FF0000>WARNING</col>-",
                "Contributing to this clan or gaining a rank will remove",
                "all of your progress from your current clan <col=FF4444>" + player.lastClan + "</col>.",
                "Are you sure you want to join?")
                .sendOption(
                        "Yes, I accept.",
                        () -> channel.add(player, member),
                        "No, I don't want to risk it.",
                        () -> player.clanChannel = null).execute();
    }
References channel, com.runehive.game.world.entity.mob.player.Player.clanChannel, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.entity.mob.player.Player.lastClan, com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
testPassword()
boolean com.runehive.content.clanchannel.channel.ClanChannelHandler.testPassword (Player player, ClanMember member) package
Handles entering a clan channel password.
Definition at line 173 of file ClanChannelHandler.java.
{
        if (!channel.hasPassword() || channel.canManage(member)) {
            return false;
        }
        player.dialogueFactory.sendStatement("This clan requires a password in order to join.").onAction(() -> {
            player.send(new SendInputMessage("Enter the password:", 6, input -> {
                if (!channel.isPassword(input)) {
                    player.send(new SendMessage("You have entered an invalid clan password."));
                    player.dialogueFactory.clear();
                    return;
                }
                player.dialogueFactory.sendStatement("Password was accepted!").execute();
                channel.establish(player, member);
            }));
        }).execute();
        return true;
    }
References channel, com.runehive.content.dialogue.DialogueFactory.clear(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
updateMemberList()
void com.runehive.content.clanchannel.channel.ClanChannelHandler.updateMemberList (ClanMember member)
Handles updating the clan channel member list.
Definition at line 246 of file ClanChannelHandler.java.
{
        Player player = member.player.orElse(null);
        if (player == null)
            return;
        int size = channel.size() < 10 ? 10 : channel.size();
        player.send(new SendString("Talking in: <col=F7DC6F>" + Utility.formatName(channel.getName()), 33502));
        player.send(new SendConfig(393, channel.lootshareEnabled() ? 1 : 0));
        player.send(new SendScrollbar(33530, size * 22));
        List<ClanMember> members = new LinkedList<>();
        members.addAll(channel.getMembers());
        members.sort(player.settings.clanMemberComporator);
        Iterator<ClanMember> iterator = members.iterator();
        boolean tooltip = channel.canManage(member);
        int string = 33532;
        for (int index = 0; index < size * 3; index++) {
            ClanMember nextMember = null;
            if (iterator.hasNext()) {
                nextMember = iterator.next();
            }
            if (nextMember == null || (!nextMember.player.isPresent() && index / 3 >= members.size())) {
                player.send(new SendString("", string++));
                player.send(new SendString("", string));
                player.send(new SendTooltip("", string++));
                player.send(new SendString("", string++));
                string++;
            } else if (nextMember.player.isPresent()) {
                player.send(new SendString(nextMember.rank.getString(), string++));
                player.send(new SendString(nextMember.name, string));
                player.send(new SendTooltip(tooltip ? (nextMember.name.equals(player.getName()) ? "" : "Manage " + nextMember.name) : "", string++));
                player.send(new SendString("", string++));
                string++;
            }
        }
    }
References channel, com.runehive.game.world.entity.mob.player.Settings.clanMemberComporator, com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.clanchannel.ClanRank.getString(), com.runehive.content.clanchannel.ClanMember.name, com.runehive.content.clanchannel.ClanMember.player, com.runehive.content.clanchannel.ClanMember.rank, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.player.Player.settings.
Referenced by connected(), and com.runehive.game.task.impl.ClanUpdateEvent.tick().
Member Data Documentation
channel
final ClanChannel com.runehive.content.clanchannel.channel.ClanChannelHandler.channel private
The clan channel instance.
Definition at line 29 of file ClanChannelHandler.java.
Referenced by attemptConnection(), ClanChannelHandler(), connect(), connected(), disconnect(), manage(), manageMember(), sendConnectionWarning(), testPassword(), and updateMemberList().
The documentation for this class was generated from the following file:
java/com/runehive/content/clanchannel/channel/ClanChannelHandler.java