RuneHive-Game: com.runehive.game.world.entity.combat.attack.FormulaFactory Class Reference
com.runehive.game.world.entity.combat.attack.FormulaFactory Class Reference
Supplies factory methods useful for combat.
Static Public Member Functions
static int getMaxHit (Mob attacker, Mob defender, CombatType type)
static int getModifiedMaxHit (Mob attacker, Mob defender, CombatType type)
static Hit nextMagicHit (Mob attacker, Mob defender, int max)
static Hit nextMeleeHit (Mob attacker, Mob defender)
static Hit nextMeleeHit (Mob attacker, Mob defender, int max)
static Hit nextMeleeHit (Mob attacker, Mob defender, int max, boolean multipleHitsAllowed)
static Hit nextRangedHit (Mob attacker, Mob defender, int max)
static int rollDefensive (Mob attacker, Mob defender, FormulaModifier< Mob > formula)
static int rollOffensive (Mob attacker, Mob defender, FormulaModifier< Mob > formula)
Static Private Member Functions
static boolean isAccurate (Mob attacker, Mob defender, CombatType type, CombatStrategy<? super Mob > strategy)
static int maxHit (int level, int bonus)
static Hit nextHit (Mob attacker, Mob defender, int max, Hitsplat hitsplat, HitIcon icon, boolean multipleHitsAllowed, CombatType type)
Detailed Description
Supplies factory methods useful for combat.
Author
Michael | Chex
Definition at line 20 of file FormulaFactory.java.
Member Function Documentation
getMaxHit()
int com.runehive.game.world.entity.combat.attack.FormulaFactory.getMaxHit (Mob attacker, Mob defender, CombatType type) static
Definition at line 130 of file FormulaFactory.java.
{
        FormulaModifier<Mob> formula = type.getFormula();
        int level = formula.modifyAggressive(attacker, defender, 0);
        int bonus = formula.modifyAggressiveBonus(attacker, defender, 0);
        switch (attacker.getStrategy().getCombatType()) {
            case MELEE -> MeleeMaxHit.maxHit(attacker);
        }
        return maxHit(level, bonus);
    }
References com.runehive.game.world.entity.combat.CombatType.getFormula(), com.runehive.game.world.entity.mob.Mob.getStrategy(), maxHit(), and com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.maxHit().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.getHits(), and nextMeleeHit().
getModifiedMaxHit()
int com.runehive.game.world.entity.combat.attack.FormulaFactory.getModifiedMaxHit (Mob attacker, Mob defender, CombatType type) static
Definition at line 140 of file FormulaFactory.java.
{
        FormulaModifier<Mob> formula = type.getFormula();
        int level = formula.modifyAggressive(attacker, defender, 0);
        int bonus = formula.modifyAggressiveBonus(attacker, defender, 0);
        switch (attacker.getStrategy().getCombatType()) {
            case MELEE -> MeleeMaxHit.maxHit(attacker);
        }
        if (attacker.getStrategy().getCombatType().equals(CombatType.RANGED)) {
            return (int) Math.floor(RangeMaxHit.maxHit(attacker));
        }
        return formula.modifyDamage(attacker, defender, maxHit(level, bonus));
    }
References com.runehive.game.world.entity.combat.CombatType.getFormula(), com.runehive.game.world.entity.mob.Mob.getStrategy(), maxHit(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.maxHit(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.maxHit(), and com.runehive.game.world.entity.combat.CombatType.RANGED.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.getMaxHit(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.thirdOption().
isAccurate()
boolean com.runehive.game.world.entity.combat.attack.FormulaFactory.isAccurate (Mob attacker, Mob defender, CombatType type, CombatStrategy<? super Mob > strategy) static private
Definition at line 94 of file FormulaFactory.java.
{
        if (strategy != null && strategy.isAlwaysAccurate()) {
            return true;
        }
        double attackRoll = rollOffensive(attacker, defender, type.getFormula());
        double defenceRoll = rollDefensive(attacker, defender, type.getFormula());
        boolean isNpc = attacker.isNpc();
        switch (type) {
            case RANGED -> {
                return isNpc ? RangeAccuracyNpc.successful(attacker, defender, type) : RangeAccuracy.successful(attacker, defender);
            }
            case MAGIC -> {
                return isNpc ? MagicAccuracyNpc.successful(attacker, defender, type) : MagicAccuracy.successful(attacker, defender);
            }
            case MELEE -> {
                return MeleeAccuracy.successful(attacker, defender);
            }
            default -> {
                return RandomUtils.success(attackRoll / (attackRoll + defenceRoll));
            }
        }
    }
References com.runehive.game.world.entity.combat.CombatType.getFormula(), com.runehive.game.world.entity.mob.Mob.isNpc(), rollDefensive(), rollOffensive(), com.runehive.util.RandomUtils.success(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.successful(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.successful(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.successful(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.successful(), and com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.successful().
Referenced by nextHit().
maxHit()
int com.runehive.game.world.entity.combat.attack.FormulaFactory.maxHit (int level, int bonus) static private
Definition at line 153 of file FormulaFactory.java.
{
        return (320 + level * (bonus + 64)) / 640;
    }
Referenced by getMaxHit(), and getModifiedMaxHit().
nextHit()
Hit com.runehive.game.world.entity.combat.attack.FormulaFactory.nextHit (Mob attacker, Mob defender, int max, Hitsplat hitsplat, HitIcon icon, boolean multipleHitsAllowed, CombatType type) static private
Definition at line 43 of file FormulaFactory.java.
{
        final CombatStrategy<? super Mob> strategy = attacker.getStrategy();
        final int totalHits = defender.isNpc() && defender.getNpc().definition.getSize() > 1 ? 3 : 1;
        if (strategy.toString().contains("ScytheOfVitur") && totalHits > 1) {
            final Hit[] hits = new Hit[totalHits];
            for (int index = 0; index < hits.length; index++) {
                final Hit hit = hits[index] = new Hit(max < 0 ? -1 : 0, hitsplat, icon,
                        isAccurate(attacker, defender, type, strategy));
                if (max > 0) {
                    max = type.getFormula().modifyDamage(attacker, defender, max);
                    int verdict = RandomUtils.inclusive(0, max);
                    switch (index) {
                        case 1:
                            verdict /= 2;
                            break;
                        case 2:
                            verdict /= 3;
                            break;
                    }
                    if (verdict > defender.getCurrentHealth()) {
                        verdict = defender.getCurrentHealth();
                    }
                    hit.setDamage(verdict);
                }
            }
            return new Hit(hits);
        }
        final Hit hit = new Hit(max < 0 ? -1 : 0, hitsplat, icon,
                isAccurate(attacker, defender, type, strategy));
        if (max > 0) {
            max = type.getFormula().modifyDamage(attacker, defender, max);
            int verdict = RandomUtils.inclusive(0, max);
            if (verdict > defender.getCurrentHealth()) {
                verdict = defender.getCurrentHealth();
            }
            hit.setDamage(verdict);
        }
        return hit;
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.combat.CombatType.getFormula(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getSize(), com.runehive.game.world.entity.mob.Mob.getStrategy(), com.runehive.util.RandomUtils.inclusive(), isAccurate(), com.runehive.game.world.entity.mob.Mob.isNpc(), and com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.modifyDamage().
Referenced by nextMagicHit(), nextMeleeHit(), nextMeleeHit(), nextMeleeHit(), and nextRangedHit().
nextMagicHit()
Hit com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMagicHit (Mob attacker, Mob defender, int max) static
Definition at line 39 of file FormulaFactory.java.
{
        return nextHit(attacker, defender, max, Hitsplat.NORMAL, HitIcon.MAGIC, false, CombatType.MAGIC);
    }
References com.runehive.game.world.entity.combat.CombatType.MAGIC, com.runehive.game.world.entity.combat.hit.HitIcon.MAGIC, nextHit(), and com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL.
Referenced by com.runehive.game.world.entity.combat.magic.MagicImpact.hitEvent(), and com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit().
nextMeleeHit() [1/3]
Hit com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit (Mob attacker, Mob defender) static
Definition at line 22 of file FormulaFactory.java.
{
        int max = getMaxHit(attacker, defender, CombatType.MELEE);
        return nextHit(attacker, defender, max, Hitsplat.NORMAL, HitIcon.MELEE, false, CombatType.MELEE);
    }
References getMaxHit(), com.runehive.game.world.entity.combat.CombatType.MELEE, com.runehive.game.world.entity.combat.hit.HitIcon.MELEE, nextHit(), and com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL.
Referenced by com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit().
nextMeleeHit() [2/3]
Hit com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit (Mob attacker, Mob defender, int max) static
Definition at line 27 of file FormulaFactory.java.
{
        return nextHit(attacker, defender, max, Hitsplat.NORMAL, HitIcon.MELEE, false, CombatType.MELEE);
    }
References com.runehive.game.world.entity.combat.CombatType.MELEE, com.runehive.game.world.entity.combat.hit.HitIcon.MELEE, nextHit(), and com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL.
nextMeleeHit() [3/3]
Hit com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit (Mob attacker, Mob defender, int max, boolean multipleHitsAllowed) static
Definition at line 31 of file FormulaFactory.java.
{
        return nextHit(attacker, defender, max, Hitsplat.NORMAL, HitIcon.MELEE, multipleHitsAllowed, CombatType.MELEE);
    }
References com.runehive.game.world.entity.combat.CombatType.MELEE, com.runehive.game.world.entity.combat.hit.HitIcon.MELEE, nextHit(), and com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL.
nextRangedHit()
Hit com.runehive.game.world.entity.combat.attack.FormulaFactory.nextRangedHit (Mob attacker, Mob defender, int max) static
Definition at line 35 of file FormulaFactory.java.
{
        return nextHit(attacker, defender, max, Hitsplat.NORMAL, HitIcon.RANGED, false, CombatType.RANGED);
    }
References nextHit(), com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL, com.runehive.game.world.entity.combat.CombatType.RANGED, and com.runehive.game.world.entity.combat.hit.HitIcon.RANGED.
Referenced by com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit().
rollDefensive()
int com.runehive.game.world.entity.combat.attack.FormulaFactory.rollDefensive (Mob attacker, Mob defender, FormulaModifier< Mob > formula) static
Definition at line 124 of file FormulaFactory.java.
{
        int roll = formula.modifyDefensive(attacker, defender, 0);
        int bonus = formula.modifyDefensiveBonus(attacker, defender, 0);
        return attacker.getCombat().modifyDefensive(defender, roll * (bonus + 64));
    }
References com.runehive.game.world.entity.mob.Mob.getCombat().
Referenced by isAccurate().
rollOffensive()
int com.runehive.game.world.entity.combat.attack.FormulaFactory.rollOffensive (Mob attacker, Mob defender, FormulaModifier< Mob > formula) static
Definition at line 118 of file FormulaFactory.java.
{
        int roll = formula.modifyAccuracy(attacker, defender, 0);
        int bonus = formula.modifyOffensiveBonus(attacker, defender, 0);
        return attacker.getCombat().modifyAccuracy(defender, roll * (bonus + 64));
    }
References com.runehive.game.world.entity.mob.Mob.getCombat().
Referenced by isAccurate().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/FormulaFactory.java