RuneHive-Game: com.runehive.content.ai.OpenAIService Class Reference
com.runehive.content.ai.OpenAIService Class Reference
Classes
class ChatMessage
Public Member Functions
void clearConversationHistory (String username)
int getActiveSessionCount ()
int getMinWordCount ()
void initialize ()
boolean isInitialized ()
CompletableFuture< String > processPlayerMessage (String username, String message, int npcId)
void shutdown ()
Static Public Member Functions
static OpenAIService getInstance ()
Private Member Functions
String hashUsername (String username)
void loadApiKey () throws IOException
OpenAIService ()
Private Attributes
String apiKey
final ConcurrentHashMap< String, List< ChatMessage > > conversationHistory
final ExecutorService executorService
final AtomicBoolean initialized = new AtomicBoolean(false)
OpenAIClient openAIClient
Static Private Attributes
static final String API_KEY_ENV = "OPENAI_API_KEY"
static final String API_KEY_FILE = "openai-java-key.txt"
static final OpenAIService INSTANCE = new OpenAIService()
static final Logger logger = LoggerFactory.getLogger(OpenAIService.class)
static final int MAX_CONVERSATION_HISTORY = 10
static final int MAX_TOKENS = 500
static final double TEMPERATURE = 0.8
Detailed Description
Definition at line 25 of file OpenAIService.java.
Constructor & Destructor Documentation
OpenAIService()
com.runehive.content.ai.OpenAIService.OpenAIService () private
Definition at line 42 of file OpenAIService.java.
{
        this.executorService = Executors.newFixedThreadPool(4);
        this.conversationHistory = new ConcurrentHashMap<>();
    }
Referenced by getInstance().
Member Function Documentation
clearConversationHistory()
void com.runehive.content.ai.OpenAIService.clearConversationHistory (String username)
Definition at line 175 of file OpenAIService.java.
{
        if (conversationHistory.remove(username) != null) {
            logger.debug("Cleared conversation history for user: {}", hashUsername(username));
        }
    }
References conversationHistory, hashUsername(), and logger.
getActiveSessionCount()
int com.runehive.content.ai.OpenAIService.getActiveSessionCount ()
Definition at line 195 of file OpenAIService.java.
{
        return conversationHistory.size();
    }
References conversationHistory.
getInstance()
OpenAIService com.runehive.content.ai.OpenAIService.getInstance () static
Definition at line 47 of file OpenAIService.java.
{
        return INSTANCE;
    }
References INSTANCE, and OpenAIService().
Referenced by com.runehive.content.ai.LazyAIManager.initializeOpenAIServices().
getMinWordCount()
int com.runehive.content.ai.OpenAIService.getMinWordCount ()
Definition at line 191 of file OpenAIService.java.
{
        return 0;
    }
hashUsername()
String com.runehive.content.ai.OpenAIService.hashUsername (String username) private
Definition at line 181 of file OpenAIService.java.
{
        if (username == null) return "null";
        int hash = username.hashCode();
        return "user_" + Integer.toHexString(hash);
    }
Referenced by clearConversationHistory(), and processPlayerMessage().
initialize()
void com.runehive.content.ai.OpenAIService.initialize ()
Definition at line 51 of file OpenAIService.java.
{
        if (initialized.compareAndSet(false, true)) {
            logger.info("Initializing Official OpenAI Service with GPT-4o-mini model");
            try {
                loadApiKey();
                openAIClient = OpenAIOkHttpClient.builder()
                    .apiKey(apiKey)
                    .timeout(Duration.ofSeconds(30))
                    .maxRetries(3)
                    .build();
                logger.info("Official OpenAI Service initialized and ready for GPT-4o-mini requests");
            } catch (Exception e) {
                logger.error("Failed to initialize Official OpenAI Service", e);
                initialized.set(false);
                throw new RuntimeException("OpenAI Service initialization failed", e);
            }
        }
    }
References apiKey, initialized, loadApiKey(), logger, and openAIClient.
isInitialized()
boolean com.runehive.content.ai.OpenAIService.isInitialized ()
Definition at line 187 of file OpenAIService.java.
{
        return initialized.get();
    }
References initialized.
loadApiKey()
void com.runehive.content.ai.OpenAIService.loadApiKey () throws IOException private
Definition at line 73 of file OpenAIService.java.
{
        apiKey = System.getenv(API_KEY_ENV);
        if (apiKey != null && !apiKey.trim().isEmpty()) {
            apiKey = apiKey.trim();
            if (apiKey.matches("^sk-[a-zA-Z0-9\\-_]{20,}$")) {
                logger.info("OpenAI API key loaded from environment variable");
                return;
            } else {
                logger.warn("Invalid API key format in environment variable - must match pattern: sk-[alphanumeric]{20+}");
                apiKey = null;
            }
        }
        try {
            Path keyFile = Paths.get(API_KEY_FILE);
            if (Files.exists(keyFile)) {
                byte[] bytes = Files.readAllBytes(keyFile);
                apiKey = new String(bytes, "UTF-8").trim();
                if (apiKey.isEmpty() || !apiKey.matches("^sk-[a-zA-Z0-9\\-_]{20,}$")) {
                    throw new IllegalArgumentException("Invalid API key format in file - must match pattern: sk-[alphanumeric]{20+}");
                }
                logger.warn("OpenAI API key loaded from file - consider using environment variable {} for better security", API_KEY_ENV);
                return;
            }
        } catch (IOException e) {
            logger.error("Could not read API key file: {}", API_KEY_FILE);
        }
        throw new IOException("OpenAI API key not found. Set environment variable " + API_KEY_ENV +
                            " or create file " + API_KEY_FILE + " with a valid API key starting with 'sk-'");
    }
References API_KEY_ENV, API_KEY_FILE, apiKey, and logger.
Referenced by initialize().
processPlayerMessage()
CompletableFuture< String > com.runehive.content.ai.OpenAIService.processPlayerMessage (String username, String message, int npcId)
Definition at line 106 of file OpenAIService.java.
{
        return CompletableFuture.supplyAsync(() -> {
            try {
                if (!initialized.get()) {
                    logger.warn("OpenAI Service not initialized");
                    return "The mystical networks are not yet connected. Please try again.";
                }
                List<ChatMessage> history = conversationHistory.computeIfAbsent(username,
                    k -> new ArrayList<>());
                history.add(new ChatMessage("user", message));
                if (history.size() > MAX_CONVERSATION_HISTORY) {
                    history = new ArrayList<>(history.subList(
                        history.size() - MAX_CONVERSATION_HISTORY, history.size()));
                    conversationHistory.put(username, history);
                }
                ChatCompletionCreateParams.Builder paramsBuilder = ChatCompletionCreateParams.builder()
                    .model(ChatModel.GPT_4O_MINI)
                    .maxCompletionTokens(MAX_TOKENS)
                    .temperature(TEMPERATURE)
                    .addDeveloperMessage(
                        "You are a helpful AI assistant. Provide accurate, concise, and direct answers to questions. " +
                        "Keep responses under 150 tokens while ensuring they fully answer the question."
                    );
                for (ChatMessage msg : history) {
                    if ("user".equals(msg.getRole())) {
                        paramsBuilder.addUserMessage(msg.getContent());
                    } else if ("assistant".equals(msg.getRole())) {
                        paramsBuilder.addAssistantMessage(msg.getContent());
                    }
                }
                ChatCompletionCreateParams params = paramsBuilder.build();
                logger.debug("Making OpenAI API request for user: {}", hashUsername(username));
                ChatCompletion completion = openAIClient.chat().completions().create(params);
                if (completion.choices().isEmpty()) {
                    logger.warn("No choices returned from OpenAI API");
                    return "The mystical spirits did not respond. Please try again.";
                }
                String response = completion.choices().get(0).message().content().orElse("");
                if (response.isEmpty()) {
                    logger.warn("Empty response from OpenAI API");
                    return "The AI spirits whispered too quietly. Please try again.";
                }
                history.add(new ChatMessage("assistant", response));
                completion.usage().ifPresent(usage -> {
                    logger.info("OpenAI API usage for {}: prompt_tokens={}, completion_tokens={}, total_tokens={}",
                        hashUsername(username), usage.promptTokens(), usage.completionTokens(), usage.totalTokens());
                });
                logger.debug("Successfully processed OpenAI request for user: {}", hashUsername(username));
                return response;
            } catch (Exception e) {
                logger.error("Error processing OpenAI request for user: " + username, e);
                return "The mystical connection encountered turbulence. Please try again later.";
            }
        }, executorService);
    }
References conversationHistory, executorService, hashUsername(), initialized, logger, MAX_CONVERSATION_HISTORY, MAX_TOKENS, openAIClient, and TEMPERATURE.
Referenced by com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage().
shutdown()
void com.runehive.content.ai.OpenAIService.shutdown ()
Definition at line 199 of file OpenAIService.java.
{
        logger.info("Shutting down Official OpenAI Service...");
        conversationHistory.clear();
        if (executorService != null && !executorService.isShutdown()) {
            executorService.shutdown();
        }
        openAIClient = null;
        initialized.set(false);
        logger.info("Official OpenAI Service shutdown complete");
    }
References conversationHistory, executorService, initialized, logger, and openAIClient.
Member Data Documentation
API_KEY_ENV
final String com.runehive.content.ai.OpenAIService.API_KEY_ENV = "OPENAI_API_KEY" static private
Definition at line 28 of file OpenAIService.java.
Referenced by loadApiKey().
API_KEY_FILE
final String com.runehive.content.ai.OpenAIService.API_KEY_FILE = "openai-java-key.txt" static private
Definition at line 29 of file OpenAIService.java.
Referenced by loadApiKey().
apiKey
String com.runehive.content.ai.OpenAIService.apiKey private
Definition at line 40 of file OpenAIService.java.
Referenced by initialize(), and loadApiKey().
conversationHistory
final ConcurrentHashMap<String, List<ChatMessage> > com.runehive.content.ai.OpenAIService.conversationHistory private
Definition at line 37 of file OpenAIService.java.
Referenced by clearConversationHistory(), getActiveSessionCount(), processPlayerMessage(), and shutdown().
executorService
final ExecutorService com.runehive.content.ai.OpenAIService.executorService private
Definition at line 36 of file OpenAIService.java.
Referenced by processPlayerMessage(), and shutdown().
initialized
final AtomicBoolean com.runehive.content.ai.OpenAIService.initialized = new AtomicBoolean(false) private
Definition at line 38 of file OpenAIService.java.
Referenced by initialize(), isInitialized(), processPlayerMessage(), and shutdown().
INSTANCE
final OpenAIService com.runehive.content.ai.OpenAIService.INSTANCE = new OpenAIService() static private
Definition at line 34 of file OpenAIService.java.
Referenced by getInstance().
logger
final Logger com.runehive.content.ai.OpenAIService.logger = LoggerFactory.getLogger(OpenAIService.class) static private
Definition at line 27 of file OpenAIService.java.
Referenced by clearConversationHistory(), initialize(), loadApiKey(), processPlayerMessage(), and shutdown().
MAX_CONVERSATION_HISTORY
final int com.runehive.content.ai.OpenAIService.MAX_CONVERSATION_HISTORY = 10 static private
Definition at line 32 of file OpenAIService.java.
Referenced by processPlayerMessage().
MAX_TOKENS
final int com.runehive.content.ai.OpenAIService.MAX_TOKENS = 500 static private
Definition at line 30 of file OpenAIService.java.
Referenced by processPlayerMessage().
openAIClient
OpenAIClient com.runehive.content.ai.OpenAIService.openAIClient private
Definition at line 39 of file OpenAIService.java.
Referenced by initialize(), processPlayerMessage(), and shutdown().
TEMPERATURE
final double com.runehive.content.ai.OpenAIService.TEMPERATURE = 0.8 static private
Definition at line 31 of file OpenAIService.java.
Referenced by processPlayerMessage().
The documentation for this class was generated from the following file:
java/com/runehive/content/ai/OpenAIService.java