RuneHive-Game: com.runehive.net.packet.in.ItemContainerActionPacketListener Class Reference
com.runehive.net.packet.in.ItemContainerActionPacketListener Class Reference
The GamePacket's responsible for the options for Items inside a container itemcontainer.
Public Member Functions
void handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Private Member Functions
void allButOne (Player player, GamePacket packet)
Handles the randomevent when a player clicks on the sixth option of an item container itemcontainer.
void fifthAction (Player player, GamePacket packet)
Handles the action when a player clicks on the fifth option of an item container itemcontainer.
void firstAction (Player player, GamePacket packet)
Handles the randomevent when a player clicks on the first option of an item container itemcontainer.
void fourthAction (Player player, GamePacket packet)
Handles the randomevent when a player clicks on the fourth option of an item container itemcontainer.
void modifiableXAction (Player player, GamePacket packet)
Handles the randomevent when a player clicks on the sixth option of an item container itemcontainer.
void secondAction (Player player, GamePacket packet)
Handles the randomevent when a player clicks on the second option of an item container itemcontainer.
void sixthAction (Player player, GamePacket packet)
Handles the randomevent when a player clicks on the sixth option of an item container itemcontainer.
void thirdAction (Player player, GamePacket packet)
Handles the randomevent when a player clicks on the third option of an item container itemcontainer.
Static Private Attributes
static final int ALL_BUT_ONE_ACTION_OPCODE = 140
static final int FIFTH_ITEM_ACTION_OPCODE = 135
static final int FIRST_ITEM_ACTION_OPCODE = 145
static final int FOURTH_ITEM_ACTION_OPCODE = 129
static final int MODIFIABLE_X_ACTION_OPCODE = 141
static final int SECOND_ITEM_ACTION_OPCODE = 117
static final int SIXTH_ITEM_ACTION_OPCODE = 208
static final int THIRD_ITEM_ACTION_OPCODE = 43
Detailed Description
The GamePacket's responsible for the options for Items inside a container itemcontainer.
Author
Daniel | Obey
Definition at line 23 of file ItemContainerActionPacketListener.java.
Member Function Documentation
allButOne()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.allButOne (Player player, GamePacket packet) private
Handles the randomevent when a player clicks on the sixth option of an item container itemcontainer.
Parameters
player The player clicking the option.
packet The packet for this option.
Definition at line 208 of file ItemContainerActionPacketListener.java.
{
        final int removeSlot = packet.readShort(ByteModification.ADD);
        final int interfaceId = packet.readShort();
        final int removeId = packet.readShort(ByteModification.ADD);
        PluginManager.getDataBus().publish(player, new ItemContainerContextMenuEvent(7, interfaceId, removeSlot, removeId));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.plugin.PluginManager.getDataBus(), and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
fifthAction()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.fifthAction (Player player, GamePacket packet) private
Handles the action when a player clicks on the fifth option of an item container itemcontainer.
Parameters
player The player clicking the option.
packet The packet for this option.
Definition at line 154 of file ItemContainerActionPacketListener.java.
{
        final int removeSlot = packet.readShort(ByteOrder.LE);
        final int interfaceId = packet.readShort(ByteModification.ADD);
        final int removeId = packet.readShort(ByteOrder.LE);
        player.attributes.set("XREMOVE_SLOT", removeSlot);
        player.attributes.set("XREMOVE_INTERFACE", interfaceId);
        player.attributes.set("XREMOVE_REMOVE", removeId);
        if(interfaceId == 7423) {
            player.send(new SendInputAmount("Enter amount", 10, input -> DepositBoxPlugin.deposit(player, removeSlot, Integer.parseInt(input))));
            return;
        }
        if (EventDispatcher.execute(player, new ItemContainerInteractionEvent(5, interfaceId, removeSlot, removeId))) {
            return;
        }
        PluginManager.getDataBus().publish(player, new ItemContainerContextMenuEvent(5, interfaceId, removeSlot, removeId));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.net.codec.ByteOrder.LE, com.runehive.game.event.bus.PlayerDataBus.publish(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.util.generic.GenericAttributes.set().
Referenced by handlePacket().
firstAction()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.firstAction (Player player, GamePacket packet) private
Handles the randomevent when a player clicks on the first option of an item container itemcontainer.
Parameters
player The player clicking the option.
packet The packet for this action.
Definition at line 79 of file ItemContainerActionPacketListener.java.
{
        final int interfaceId = packet.readShort(ByteModification.ADD);
        final int removeSlot = packet.readShort(ByteModification.ADD);
        final int removeId = packet.readShort(ByteModification.ADD);
        if (EventDispatcher.execute(player, new ItemContainerInteractionEvent(1, interfaceId, removeSlot, removeId))) {
            return;
        }
        PluginManager.getDataBus().publish(player, new ItemContainerContextMenuEvent(1, interfaceId, removeSlot, removeId));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.plugin.PluginManager.getDataBus(), and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
fourthAction()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.fourthAction (Player player, GamePacket packet) private
Handles the randomevent when a player clicks on the fourth option of an item container itemcontainer.
Parameters
player The player clicking the option.
Definition at line 135 of file ItemContainerActionPacketListener.java.
{
        final int interfaceId = packet.readShort(ByteOrder.LE);
        final int removeId = packet.readShort(ByteModification.ADD);
        final int removeSlot = packet.readShort(ByteModification.ADD);
        if (EventDispatcher.execute(player, new ItemContainerInteractionEvent(4, interfaceId, removeSlot, removeId))) {
            return;
        }
        PluginManager.getDataBus().publish(player, new ItemContainerContextMenuEvent(4, interfaceId, removeSlot, removeId));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.net.codec.ByteOrder.LE, and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
handlePacket()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Parameters
player The player receiving this packet.
packet The packet that has been received.
Implements com.runehive.net.packet.PacketListener.
Definition at line 35 of file ItemContainerActionPacketListener.java.
{
        switch (packet.getOpcode()) {
            case FIRST_ITEM_ACTION_OPCODE:
                firstAction(player, packet);
                break;
            case SECOND_ITEM_ACTION_OPCODE:
                secondAction(player, packet);
                break;
            case THIRD_ITEM_ACTION_OPCODE:
                thirdAction(player, packet);
                break;
            case FOURTH_ITEM_ACTION_OPCODE:
                fourthAction(player, packet);
                break;
            case FIFTH_ITEM_ACTION_OPCODE:
                fifthAction(player, packet);
                break;
            case SIXTH_ITEM_ACTION_OPCODE:
                sixthAction(player, packet);
                break;
            case ALL_BUT_ONE_ACTION_OPCODE:
                allButOne(player, packet);
                break;
            case MODIFIABLE_X_ACTION_OPCODE:
                modifiableXAction(player, packet);
                break;
        }
    }
References ALL_BUT_ONE_ACTION_OPCODE, allButOne(), FIFTH_ITEM_ACTION_OPCODE, fifthAction(), FIRST_ITEM_ACTION_OPCODE, firstAction(), FOURTH_ITEM_ACTION_OPCODE, fourthAction(), MODIFIABLE_X_ACTION_OPCODE, modifiableXAction(), SECOND_ITEM_ACTION_OPCODE, secondAction(), SIXTH_ITEM_ACTION_OPCODE, sixthAction(), THIRD_ITEM_ACTION_OPCODE, and thirdAction().
modifiableXAction()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.modifiableXAction (Player player, GamePacket packet) private
Handles the randomevent when a player clicks on the sixth option of an item container itemcontainer.
Parameters
player The player clicking the option.
packet The packet for this option.
Definition at line 223 of file ItemContainerActionPacketListener.java.
{
        final int removeSlot = packet.readShort(ByteModification.ADD);
        final int interfaceId = packet.readShort();
        final int removeId = packet.readShort(ByteModification.ADD);
        final int amount = packet.readInt();
        PluginManager.getDataBus().publish(player, new ItemContainerContextMenuEvent(8, interfaceId, removeSlot, removeId, amount));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.plugin.PluginManager.getDataBus(), and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
secondAction()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.secondAction (Player player, GamePacket packet) private
Handles the randomevent when a player clicks on the second option of an item container itemcontainer.
Parameters
player The player clicking the option.
packet The packet for this option.
Definition at line 98 of file ItemContainerActionPacketListener.java.
{
        final int interfaceId = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        final int removeId = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        final int removeSlot = packet.readShort(ByteOrder.LE);
        if (EventDispatcher.execute(player, new ItemContainerInteractionEvent(2, interfaceId, removeSlot, removeId))) {
            return;
        }
        PluginManager.getDataBus().publish(player, new ItemContainerContextMenuEvent(2, interfaceId, removeSlot, removeId));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.net.codec.ByteOrder.LE, and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
sixthAction()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.sixthAction (Player player, GamePacket packet) private
Handles the randomevent when a player clicks on the sixth option of an item container itemcontainer.
Parameters
player The player clicking the option.
packet The packet for this option.
Definition at line 182 of file ItemContainerActionPacketListener.java.
{
        final int amount = packet.readInt();
        if (player.enterInputListener.isPresent()) {
            player.enterInputListener.get().accept(Integer.toString(amount));
            return;
        }
        final int interfaceId = player.attributes.get("XREMOVE_INTERFACE", Integer.class);
        final int removeSlot = player.attributes.get("XREMOVE_SLOT", Integer.class);
        final int removeId = player.attributes.get("XREMOVE_REMOVE", Integer.class);
        if (EventDispatcher.execute(player, new ItemContainerInteractionEvent(6, interfaceId, removeSlot, removeId))) {
            return;
        }
        PluginManager.getDataBus().publish(player, new ItemContainerContextMenuEvent(6, interfaceId, removeSlot, removeId));
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.entity.mob.player.Player.enterInputListener, com.runehive.content.event.EventDispatcher.execute(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.plugin.PluginManager.getDataBus(), and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
thirdAction()
void com.runehive.net.packet.in.ItemContainerActionPacketListener.thirdAction (Player player, GamePacket packet) private
Handles the randomevent when a player clicks on the third option of an item container itemcontainer.
Parameters
player The player clicking the option.
packet The packet for this option.
Definition at line 117 of file ItemContainerActionPacketListener.java.
{
        final int interfaceId = packet.readShort(ByteOrder.LE);
        final int removeId = packet.readShort(ByteModification.ADD);
        final int removeSlot = packet.readShort(ByteModification.ADD);
        if (EventDispatcher.execute(player, new ItemContainerInteractionEvent(3, interfaceId, removeSlot, removeId))) {
            return;
        }
        PluginManager.getDataBus().publish(player, new ItemContainerContextMenuEvent(3, interfaceId, removeSlot, removeId));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.net.codec.ByteOrder.LE, and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
Member Data Documentation
ALL_BUT_ONE_ACTION_OPCODE
final int com.runehive.net.packet.in.ItemContainerActionPacketListener.ALL_BUT_ONE_ACTION_OPCODE = 140 static private
Definition at line 31 of file ItemContainerActionPacketListener.java.
Referenced by handlePacket().
FIFTH_ITEM_ACTION_OPCODE
final int com.runehive.net.packet.in.ItemContainerActionPacketListener.FIFTH_ITEM_ACTION_OPCODE = 135 static private
Definition at line 29 of file ItemContainerActionPacketListener.java.
Referenced by handlePacket().
FIRST_ITEM_ACTION_OPCODE
final int com.runehive.net.packet.in.ItemContainerActionPacketListener.FIRST_ITEM_ACTION_OPCODE = 145 static private
Definition at line 25 of file ItemContainerActionPacketListener.java.
Referenced by handlePacket().
FOURTH_ITEM_ACTION_OPCODE
final int com.runehive.net.packet.in.ItemContainerActionPacketListener.FOURTH_ITEM_ACTION_OPCODE = 129 static private
Definition at line 28 of file ItemContainerActionPacketListener.java.
Referenced by handlePacket().
MODIFIABLE_X_ACTION_OPCODE
final int com.runehive.net.packet.in.ItemContainerActionPacketListener.MODIFIABLE_X_ACTION_OPCODE = 141 static private
Definition at line 32 of file ItemContainerActionPacketListener.java.
Referenced by handlePacket().
SECOND_ITEM_ACTION_OPCODE
final int com.runehive.net.packet.in.ItemContainerActionPacketListener.SECOND_ITEM_ACTION_OPCODE = 117 static private
Definition at line 26 of file ItemContainerActionPacketListener.java.
Referenced by handlePacket().
SIXTH_ITEM_ACTION_OPCODE
final int com.runehive.net.packet.in.ItemContainerActionPacketListener.SIXTH_ITEM_ACTION_OPCODE = 208 static private
Definition at line 30 of file ItemContainerActionPacketListener.java.
Referenced by handlePacket().
THIRD_ITEM_ACTION_OPCODE
final int com.runehive.net.packet.in.ItemContainerActionPacketListener.THIRD_ITEM_ACTION_OPCODE = 43 static private
Definition at line 27 of file ItemContainerActionPacketListener.java.
Referenced by handlePacket().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/in/ItemContainerActionPacketListener.java