RuneHive-Game: com.runehive.game.engine.GameEngine Class Reference
com.runehive.game.engine.GameEngine Class Reference
Public Member Functions
GameEngine ()
Static Public Member Functions
static int clientTicksToMillis (final int clientTicks)
static int clientTicksToServerTicks (final int clientTicks)
static int millisToTicks (final int millis)
Static Public Attributes
static final int TICK_MILLIS = 600
Protected Member Functions
void runOneIteration ()
Scheduler scheduler ()
String serviceName ()
Private Attributes
final ClientSynchronizer synchronizer
Static Private Attributes
static final Logger logger = LogManager.getLogger(GameEngine.class)
Detailed Description
Definition at line 22 of file GameEngine.java.
Constructor & Destructor Documentation
GameEngine()
com.runehive.game.engine.GameEngine.GameEngine ()
Definition at line 47 of file GameEngine.java.
{
        synchronizer = (Config.PARALLEL_GAME_ENGINE ? new ParallelClientSynchronizer() : new SequentialClientSynchronizer());
    }
References com.runehive.Config.PARALLEL_GAME_ENGINE, and synchronizer.
Member Function Documentation
clientTicksToMillis()
int com.runehive.game.engine.GameEngine.clientTicksToMillis (final int clientTicks) static
Definition at line 30 of file GameEngine.java.
{
        return clientTicks * 20;
    }
Referenced by clientTicksToServerTicks().
clientTicksToServerTicks()
int com.runehive.game.engine.GameEngine.clientTicksToServerTicks (final int clientTicks) static
Definition at line 34 of file GameEngine.java.
{
        return millisToTicks(clientTicksToMillis(clientTicks));
    }
References clientTicksToMillis(), and millisToTicks().
Referenced by com.runehive.game.world.entity.combat.projectile.CombatProjectile.getServerTicks(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), and com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.sendProjectile().
millisToTicks()
int com.runehive.game.engine.GameEngine.millisToTicks (final int millis) static
Definition at line 26 of file GameEngine.java.
{
        return millis / TICK_MILLIS;
    }
References TICK_MILLIS.
Referenced by clientTicksToServerTicks().
runOneIteration()
void com.runehive.game.engine.GameEngine.runOneIteration () protected
Definition at line 52 of file GameEngine.java.
{
        try {
            final Stopwatch stopwatch = Stopwatch.start();
            final Stopwatch stopwatch2 = Stopwatch.start();
            World world = World.get();
            MobList<Player> players = World.getPlayers();
            MobList<Npc> npcs = World.getNpcs();
            world.dequeLogins();
            long elapsed = stopwatch.elapsedTime(TimeUnit.MILLISECONDS);
            if (elapsed > 10 && Config.SERVER_DEBUG) {
                System.out.printf("world.dequeLogins(): %d ms%n", elapsed);
            }
            stopwatch.reset();
            world.dequeLogouts();
            elapsed = stopwatch.elapsedTime(TimeUnit.MILLISECONDS);
            if (elapsed > 10 && Config.SERVER_DEBUG) {
                System.out.printf("world.dequeLogouts(): %d ms%n", elapsed);
            }
            stopwatch.reset();
            npcs.forEach(npc -> new NpcPreUpdateTask(npc).run());
            elapsed = stopwatch.elapsedTime(TimeUnit.MILLISECONDS);
            if (elapsed > 10 && Config.SERVER_DEBUG) {
                System.out.printf("NpcPreUpateTask: %d ms%n", elapsed);
            }
            stopwatch.reset();
            players.forEach(player -> new PlayerPreUpdateTask(player).run());
            elapsed = stopwatch.elapsedTime(TimeUnit.MILLISECONDS);
            if (elapsed > 10 && Config.SERVER_DEBUG) {
                System.out.printf("PlayerPreUpdateTask: %d ms%n", elapsed);
            }
            stopwatch.reset();
            world.process();
            elapsed = stopwatch.elapsedTime(TimeUnit.MILLISECONDS);
            if (elapsed > 10 && Config.SERVER_DEBUG) {
                System.out.printf("world.process(): %d ms%n", elapsed);
            }
            stopwatch.reset();
            npcs.forEach(Npc::sequence);
            elapsed = stopwatch.elapsedTime(TimeUnit.MILLISECONDS);
            if (elapsed > 10 && Config.SERVER_DEBUG) {
                System.out.printf("npc.sequence(): %d ms%n", elapsed);
            }
            stopwatch.reset();
            players.forEach(player -> {
                try {
                    player.sequence();
                } catch (Exception ex) {
                    logger.error(String.format("error player.sequence(): %s", player), ex);
                }
            });
            elapsed = stopwatch.elapsedTime(TimeUnit.MILLISECONDS);
            if (elapsed > 10 && Config.SERVER_DEBUG) {
                System.out.printf("player.sequence(): %d ms%n", elapsed);
            }
            stopwatch.reset();
            try {
                synchronizer.synchronize(players, npcs);
            } catch (Exception ex) {
                logger.fatal("Error in the main game sequencer.", ex);
            }
            elapsed = stopwatch.elapsedTime(TimeUnit.MILLISECONDS);
            if (elapsed > 10 && Config.SERVER_DEBUG) {
                System.out.printf("synchronizer.synchronize(): %d ms%n", elapsed);
            }
            players.forEach(player -> {
                    InterfaceWriter.write(new InformationWriter(player));
            });
            stopwatch.reset();
            if (stopwatch2.elapsedTime(TimeUnit.MILLISECONDS) > 60 && Config.SERVER_DEBUG) {
                System.out.printf("CYCLE END: %d ms%n", stopwatch2.elapsedTime(TimeUnit.MILLISECONDS));
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
References com.runehive.util.Stopwatch.elapsedTime(), com.runehive.game.world.entity.MobList< E extends Mob >.forEach(), com.runehive.game.world.World.get(), com.runehive.game.world.World.getNpcs(), com.runehive.game.world.World.getPlayers(), logger, com.runehive.util.Stopwatch.reset(), com.runehive.game.world.entity.mob.npc.Npc.sequence, com.runehive.Config.SERVER_DEBUG, com.runehive.util.Stopwatch.start(), synchronizer, and com.runehive.content.writer.InterfaceWriter.write().
scheduler()
Scheduler com.runehive.game.engine.GameEngine.scheduler () protected
Definition at line 140 of file GameEngine.java.
{
        return Scheduler.newFixedRateSchedule(0, TICK_MILLIS, TimeUnit.MILLISECONDS);
    }
References TICK_MILLIS.
serviceName()
String com.runehive.game.engine.GameEngine.serviceName () protected
Definition at line 43 of file GameEngine.java.
{
        return "GameThread";
    }
Member Data Documentation
logger
final Logger com.runehive.game.engine.GameEngine.logger = LogManager.getLogger(GameEngine.class) static private
Definition at line 38 of file GameEngine.java.
Referenced by runOneIteration().
synchronizer
final ClientSynchronizer com.runehive.game.engine.GameEngine.synchronizer private
Definition at line 40 of file GameEngine.java.
Referenced by GameEngine(), and runOneIteration().
TICK_MILLIS
final int com.runehive.game.engine.GameEngine.TICK_MILLIS = 600 static
Definition at line 24 of file GameEngine.java.
Referenced by millisToTicks(), and scheduler().
The documentation for this class was generated from the following file:
java/com/runehive/game/engine/GameEngine.java