RuneHive-Game: com.runehive.util.parser.old.EquipmentDefinitionParser Class Reference
com.runehive.util.parser.old.EquipmentDefinitionParser Class Reference
Parses through the equipment definitions file and creates equipment definition object.
Public Member Functions
EquipmentDefinitionParser ()
void initialize (int size)
Public Member Functions inherited from com.runehive.util.parser.GsonParser
final void deserialize ()
The method that deserializes the file information.
GsonParser (String path)
Creates a new GsonParser.
GsonParser (String path, boolean log)
Creates a new GsonParser.
Public Member Functions inherited from com.runehive.util.parser.GenericParser
GenericParser (String path, String extension, boolean log)
Creates a new GenericParser.
final int getIndex ()
Gets the current index of the line being parsed.
void onRead ()
The method called after all the data has been parsed.
void run ()
String toString ()
Static Public Member Functions
static void main (String[] args)
Protected Member Functions
void onEnd ()
This method handles what happens after the parser has ended.
void parse (JsonObject data)
The method allows a user to modify the data as its being parsed.
Static Private Member Functions
static int getReq (String first, String second, EquipmentType type)
Additional Inherited Members
Protected Attributes inherited from com.runehive.util.parser.GsonParser
transient Gson builder
The Gson object.
Protected Attributes inherited from com.runehive.util.parser.GenericParser
int index
The index of the current line being parsed.
final Path path
The path of the file to parse.
Detailed Description
Parses through the equipment definitions file and creates equipment definition object.
Author
Daniel | Obey
Definition at line 14 of file EquipmentDefinitionParser.java.
Constructor & Destructor Documentation
EquipmentDefinitionParser()
com.runehive.util.parser.old.EquipmentDefinitionParser.EquipmentDefinitionParser ()
Definition at line 16 of file EquipmentDefinitionParser.java.
{
        super("def/equipment/equipment_definitions");
    }
Referenced by main().
Member Function Documentation
getReq()
int com.runehive.util.parser.old.EquipmentDefinitionParser.getReq (String first, String second, EquipmentType type) static private
Definition at line 60 of file EquipmentDefinitionParser.java.
{
        switch (first) {
            case "bronze":
                if (type == EquipmentType.WEAPON || type == EquipmentType.ARROWS) {
                    return -1;
                }
                return 1;
            case "iron":
                if (type == EquipmentType.WEAPON || type == EquipmentType.ARROWS) {
                    return -1;
                }
                return 1;
            case "steel":
                if (type == EquipmentType.WEAPON || type == EquipmentType.ARROWS) {
                    return -1;
                }
                return 10;
            case "mithril":
                if (type == EquipmentType.WEAPON || type == EquipmentType.ARROWS) {
                    return -1;
                }
                return 20;
            case "adamant":
                if (type == EquipmentType.WEAPON || type == EquipmentType.ARROWS) {
                    return -1;
                }
                return 30;
            case "rune":
                if (type == EquipmentType.WEAPON || type == EquipmentType.ARROWS) {
                    return -1;
                }
                return 40;
            case "dragon":
            case "toktz-ket-xil":
                if (type == EquipmentType.WEAPON || type == EquipmentType.ARROWS) {
                    return -1;
                }
                return 60;
            case "bandos":
                if (second.equals("mitre") || second.equals("robe")) {
                    return -1;
                }
                if (second.startsWith("plate") || second.startsWith("full") || second.startsWith("kite")) {
                    return 40;
                }
                if (type == EquipmentType.WEAPON) {
                    return -1;
                }
                return 65;
            case "armadyl":
                if (second.equals("mitre") || second.equals("robe")) {
                    return -1;
                }
                if (second.startsWith("plate") || second.startsWith("full") || second.startsWith("kite")) {
                    return 40;
                }
                if (type == EquipmentType.WEAPON) {
                    return -1;
                }
                return 70;
            case "dharok's":
            case "guthan's":
            case "torag's":
            case "verac's":
            case "karil's":
            case "ahrim's":
            case "barrows":
                if (type == EquipmentType.WEAPON) {
                    return -1;
                }
                return 70;
            case "dragonfire":
                return 75;
            case "neitiznot":
                return 55;
            case "saradomin":
            case "guthix":
            case "zamorak":
                if (second.equals("mitre") || second.equals("robe")) {
                    return -1;
                }
                if (type == EquipmentType.WEAPON) {
                    return -1;
                }
                return 40;
            case "berserker":
            case "archer":
            case "farseer":
            case "warrior":
                if (type == EquipmentType.RING) {
                    return -1;
                }
                return 45;
            case "green":
            case "red":
            case "blue":
            case "black":
                if (type != EquipmentType.BODY) {
                    return -1;
                }
                return 40;
            case "hardleather":
                if (type != EquipmentType.BODY) {
                    return -1;
                }
                return 10;
            case "void":
                return 42;
            case "snakeskin":
                return 30;
            case "3rd":
                return 45;
            case "penance":
            case "runner":
            case "fighter":
                if (type == EquipmentType.GLOVES) {
                    return -1;
                }
                return 40;
        }
        return -1;
    }
References com.runehive.game.world.items.containers.equipment.EquipmentType.ARROWS, com.runehive.game.world.items.containers.equipment.EquipmentType.BODY, com.runehive.game.world.items.containers.equipment.EquipmentType.GLOVES, com.runehive.game.world.items.containers.equipment.EquipmentType.RING, and com.runehive.game.world.items.containers.equipment.EquipmentType.WEAPON.
initialize()
void com.runehive.util.parser.old.EquipmentDefinitionParser.initialize (int size)
Reimplemented from com.runehive.util.parser.GsonParser.
Definition at line 27 of file EquipmentDefinitionParser.java.
{
        ItemDefinition.createParser().run();
    }
References com.runehive.game.world.items.ItemDefinition.createParser(), and com.runehive.util.parser.GenericParser.run().
main()
void com.runehive.util.parser.old.EquipmentDefinitionParser.main (String[] args) static
Definition at line 20 of file EquipmentDefinitionParser.java.
{
       new EquipmentDefinitionParser().run();
      //  ItemDefinition.merge("wiki/client_item_dump", "wiki/wiki_item_dump", "wiki/new_item_dump");
        ItemDefinition.dump(ItemDefinition.create("wiki/new_item_dump"), "wiki/item_definitions");
    }
References com.runehive.game.world.items.ItemDefinition.create(), com.runehive.game.world.items.ItemDefinition.dump(), and EquipmentDefinitionParser().
onEnd()
void com.runehive.util.parser.old.EquipmentDefinitionParser.onEnd () protected
This method handles what happens after the parser has ended.
Reimplemented from com.runehive.util.parser.GsonParser.
Definition at line 56 of file EquipmentDefinitionParser.java.
{
        ItemDefinition.dump("def/item/newer_item_definitions");
    }
References com.runehive.game.world.items.ItemDefinition.dump().
parse()
void com.runehive.util.parser.old.EquipmentDefinitionParser.parse (JsonObject data) protected
The method allows a user to modify the data as its being parsed.
Parameters
data The JsonObject that contains all serialized information.
Reimplemented from com.runehive.util.parser.GsonParser.
Definition at line 32 of file EquipmentDefinitionParser.java.
{
        int id = data.get("id").getAsInt();
        ItemDefinition definition = ItemDefinition.get(id);
        if (definition.getEquipmentType() == EquipmentType.NOT_WIELDABLE) {
            String name = definition.getName().toLowerCase();
            if (name.startsWith("hood") || name.endsWith("hood")) {
                definition.setEquipmentType(EquipmentType.FACE);
            } else if (name.contains("full helm")) {
                definition.setEquipmentType(EquipmentType.HELM);
            } else if (name.contains("med helm")) {
                definition.setEquipmentType(EquipmentType.FACE);
            } else if (name.contains("helm")) {
                if (name.startsWith("dharok")) {
                    definition.setEquipmentType(EquipmentType.FACE);
                } else {
                    definition.setEquipmentType(EquipmentType.HELM);
                }
            }
        }
    }
References com.runehive.game.world.items.containers.equipment.EquipmentType.FACE, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.items.containers.equipment.EquipmentType.HELM, and com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE.
The documentation for this class was generated from the following file:
java/com/runehive/util/parser/old/EquipmentDefinitionParser.java