RuneHive-Game: com.runehive.util.Stopwatch Class Reference
com.runehive.util.Stopwatch Class Reference
Public Member Functions
boolean elapsed (long time)
boolean elapsed (long time, TimeUnit unit)
long elapsedTime ()
long elapsedTime (TimeUnit unit)
boolean finished ()
long getCachedTime ()
Stopwatch reset ()
Stopwatch reset (int delay, TimeUnit unit)
Stopwatch reset (long millis)
void setCachedTime (long cachedTime)
Stopwatch ()
String toString ()
Static Public Member Functions
static Stopwatch start ()
Private Attributes
long cachedTime
Detailed Description
Definition at line 5 of file Stopwatch.java.
Constructor & Destructor Documentation
Stopwatch()
com.runehive.util.Stopwatch.Stopwatch ()
Definition at line 9 of file Stopwatch.java.
                       {
        cachedTime = System.nanoTime();
    }
References cachedTime.
Referenced by reset(), reset(), reset(), and start().
Member Function Documentation
elapsed() [1/2]
boolean com.runehive.util.Stopwatch.elapsed (long time)
Definition at line 53 of file Stopwatch.java.
{
        return elapsed(time, TimeUnit.MILLISECONDS);
    }
References elapsed().
elapsed() [2/2]
boolean com.runehive.util.Stopwatch.elapsed (long time, TimeUnit unit)
Definition at line 49 of file Stopwatch.java.
{
        return elapsedTime(unit) >= time;
    }
References elapsedTime().
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.service.DonationService.claimDonation(), com.runehive.game.service.VoteService.claimReward(), elapsed(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.net.session.LoginSession.handleUserLoginDetails(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hasPassed(), and com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage().
elapsedTime() [1/2]
long com.runehive.util.Stopwatch.elapsedTime ()
Definition at line 45 of file Stopwatch.java.
{
        return elapsedTime(TimeUnit.MILLISECONDS);
    }
References elapsedTime().
Referenced by elapsed(), elapsedTime(), and toString().
elapsedTime() [2/2]
long com.runehive.util.Stopwatch.elapsedTime (TimeUnit unit)
Definition at line 37 of file Stopwatch.java.
{
        return unit.convert(System.nanoTime() - cachedTime, TimeUnit.NANOSECONDS);
    }
References cachedTime.
Referenced by com.runehive.content.bloodmoney.BloodChestEvent.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.util.Utility.getUptime(), com.runehive.game.engine.GameEngine.runOneIteration(), and com.runehive.game.service.NetworkService.start().
finished()
boolean com.runehive.util.Stopwatch.finished ()
Definition at line 41 of file Stopwatch.java.
{
        return cachedTime - System.nanoTime() <= 0;
    }
References cachedTime.
Referenced by com.runehive.game.world.entity.combat.magic.MagicImpact.freeze(), and com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate().
getCachedTime()
long com.runehive.util.Stopwatch.getCachedTime ()
Definition at line 57 of file Stopwatch.java.
{
        return cachedTime;
    }
References cachedTime.
reset() [1/3]
Stopwatch com.runehive.util.Stopwatch.reset ()
Definition at line 22 of file Stopwatch.java.
{
        cachedTime = System.nanoTime();
        return this;
    }
References cachedTime, and Stopwatch().
Referenced by com.runehive.game.service.DonationService.claimDonation(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.bloodmoney.BloodChestEvent.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.game.world.entity.combat.magic.MagicImpact.freeze(), com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.incrementAmount(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.preKill(), com.runehive.game.engine.GameEngine.runOneIteration(), com.runehive.game.service.NetworkService.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents().
reset() [2/3]
Stopwatch com.runehive.util.Stopwatch.reset (int delay, TimeUnit unit)
Definition at line 27 of file Stopwatch.java.
{
        cachedTime = System.nanoTime() + TimeUnit.NANOSECONDS.convert(delay, unit);
        return this;
    }
References cachedTime, and Stopwatch().
reset() [3/3]
Stopwatch com.runehive.util.Stopwatch.reset (long millis)
Definition at line 32 of file Stopwatch.java.
{
        cachedTime = System.nanoTime() + TimeUnit.NANOSECONDS.convert(millis, TimeUnit.MILLISECONDS);
        return this;
    }
References cachedTime, and Stopwatch().
setCachedTime()
void com.runehive.util.Stopwatch.setCachedTime (long cachedTime)
Definition at line 61 of file Stopwatch.java.
{
        this.cachedTime = cachedTime;
    }
References cachedTime.
start()
Stopwatch com.runehive.util.Stopwatch.start () static
Definition at line 13 of file Stopwatch.java.
{
        return new Stopwatch();
    }
References Stopwatch().
Referenced by com.runehive.game.engine.GameEngine.runOneIteration().
toString()
String com.runehive.util.Stopwatch.toString ()
Definition at line 18 of file Stopwatch.java.
{
        return String.format("STOPWATCH[elapsed=%d]", elapsedTime());
    }
References elapsedTime().
Member Data Documentation
cachedTime
long com.runehive.util.Stopwatch.cachedTime private
Definition at line 7 of file Stopwatch.java.
Referenced by elapsedTime(), finished(), getCachedTime(), reset(), reset(), reset(), setCachedTime(), and Stopwatch().
The documentation for this class was generated from the following file:
java/com/runehive/util/Stopwatch.java