RuneHive-Game: com.runehive.util.MutableNumber Class Reference
com.runehive.util.MutableNumber Class Reference
The container class that contains functions to simplify the modification of a number.
Public Member Functions
int compareTo (MutableNumber o)
int decrementAndGet ()
Decrements the value within this counter by 1 and then returns it.
int decrementAndGet (int amount)
Decrements the value within this counter by amount and then returns it.
int decrementAndGet (int amount, int minimum)
Decrements the value within this counter by amount to a minimum of minimum and then returns it.
double doubleValue ()
boolean equals (Object obj)
float floatValue ()
int get ()
Gets the value present within this counter.
int getAndDecrement ()
Returns the value within this counter and then decrements it by an amount of 1.
int getAndDecrement (int amount)
Returns the value within this counter and then decrements it by amount.
int getAndDecrement (int amount, int minimum)
Returns the value within this counter and then decrements it by amount to a minimum of minimum.
int getAndIncrement ()
Returns the value within this counter and then increments it by an amount of 1.
int getAndIncrement (int amount)
Returns the value within this counter and then increments it by amount.
int getAndIncrement (int amount, int maximum)
Returns the value within this counter and then increments it by amount to a maximum of maximum.
int hashCode ()
MutableNumber increment ()
Increments the value within this counter by 1 and then returns it.
int incrementAndGet ()
Increments the value within this counter by 1 and then returns it.
int incrementAndGet (int amount)
Increments the value within this counter by amount and then returns it.
int incrementAndGet (int amount, int maximum)
Increments the value within this counter by amount to a maximum of maximum and then returns it.
int intValue ()
long longValue ()
MutableNumber ()
Creates a new MutableNumber with a value of 0.
MutableNumber (int value)
Creates a new MutableNumber with value.
void set (int value)
Sets the value within this container to rarity.
String toString ()
Private Attributes
int value
The value present within this counter.
Static Private Attributes
static final long serialVersionUID = -7475363158492415879L
The constant serial version UID for serialization.
Detailed Description
The container class that contains functions to simplify the modification of a number.
This class is similar in functionality to AtomicInteger but does not support atomic operations, and therefore should not be used across multiple threads.
Author
lare96 http://github.com/lare96
Definition at line 16 of file MutableNumber.java.
Constructor & Destructor Documentation
MutableNumber() [1/2]
com.runehive.util.MutableNumber.MutableNumber (int value)
Creates a new MutableNumber with value.
Parameters
value the value present within this counter.
Definition at line 34 of file MutableNumber.java.
{
        this.value = value;
    }
References value.
Referenced by compareTo(), equals(), and increment().
MutableNumber() [2/2]
com.runehive.util.MutableNumber.MutableNumber ()
Creates a new MutableNumber with a value of 0.
Definition at line 41 of file MutableNumber.java.
{
        this(0);
    }
Member Function Documentation
compareTo()
int com.runehive.util.MutableNumber.compareTo (MutableNumber o)
Definition at line 68 of file MutableNumber.java.
{
        return Integer.compare(value, o.value);
    }
References MutableNumber(), and value.
decrementAndGet() [1/3]
int com.runehive.util.MutableNumber.decrementAndGet ()
Decrements the value within this counter by 1 and then returns it.
Returns
the value after it is decremented.
Definition at line 262 of file MutableNumber.java.
{
        return decrementAndGet(1);
    }
References decrementAndGet().
Referenced by decrementAndGet(), and decrementAndGet().
decrementAndGet() [2/3]
int com.runehive.util.MutableNumber.decrementAndGet (int amount)
Decrements the value within this counter by amount and then returns it.
Parameters
amount the amount to decrement it by.
Returns
the value after it is decremented.
Definition at line 252 of file MutableNumber.java.
{
        return decrementAndGet(amount, Integer.MIN_VALUE);
    }
References decrementAndGet().
decrementAndGet() [3/3]
int com.runehive.util.MutableNumber.decrementAndGet (int amount, int minimum)
Decrements the value within this counter by amount to a minimum of minimum and then returns it.
Parameters
amount the amount to decrement it by.
minimum the minimum amount it will be decremented to.
Returns
the value after it is decremented.
Definition at line 237 of file MutableNumber.java.
{
        value -= amount;
        if (value < minimum)
            value = minimum;
        return value;
    }
References value.
Referenced by com.runehive.game.task.impl.AntiVenomTask.execute(), com.runehive.game.task.impl.SuperAntipoisonTask.execute(), and com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect.process().
doubleValue()
double com.runehive.util.MutableNumber.doubleValue ()
Definition at line 93 of file MutableNumber.java.
{
        return (double) value;
    }
References value.
equals()
boolean com.runehive.util.MutableNumber.equals (Object obj)
Definition at line 56 of file MutableNumber.java.
{
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof MutableNumber))
            return false;
        MutableNumber other = (MutableNumber) obj;
        return value == other.value;
    }
References MutableNumber(), and value.
floatValue()
float com.runehive.util.MutableNumber.floatValue ()
Definition at line 88 of file MutableNumber.java.
{
        return (float) value;
    }
References value.
get()
int com.runehive.util.MutableNumber.get ()
Gets the value present within this counter.
This function equates to the inherited MutableNumber#intValue() function.
Returns
the value present.
Definition at line 272 of file MutableNumber.java.
                     {
        return value;
    }
References value.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.apply(), com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.apply(), com.runehive.net.packet.out.SendSpecialAmount.encode(), com.runehive.content.consume.PotionData.onAntiPoisonEffect(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask().
getAndDecrement() [1/3]
int com.runehive.util.MutableNumber.getAndDecrement ()
Returns the value within this counter and then decrements it by an amount of 1.
Returns
the value before it is decremented.
Definition at line 223 of file MutableNumber.java.
{
        return getAndDecrement(1);
    }
References getAndDecrement().
Referenced by getAndDecrement(), and getAndDecrement().
getAndDecrement() [2/3]
int com.runehive.util.MutableNumber.getAndDecrement (int amount)
Returns the value within this counter and then decrements it by amount.
Parameters
amount the amount to decrement it by.
Returns
the value before it is decremented.
Definition at line 213 of file MutableNumber.java.
{
        return getAndDecrement(amount, Integer.MIN_VALUE);
    }
References getAndDecrement().
getAndDecrement() [3/3]
int com.runehive.util.MutableNumber.getAndDecrement (int amount, int minimum)
Returns the value within this counter and then decrements it by amount to a minimum of minimum.
Parameters
amount the amount to decrement it by.
minimum the minimum amount it will be decremented to.
Returns
the value before it is decremented.
Definition at line 197 of file MutableNumber.java.
{
        int val = value;
        value -= amount;
        if (value < minimum)
            value = minimum;
        return val;
    }
References value.
getAndIncrement() [1/3]
int com.runehive.util.MutableNumber.getAndIncrement ()
Returns the value within this counter and then increments it by an amount of 1.
Returns
the value before it is incremented.
Definition at line 133 of file MutableNumber.java.
{
        return getAndIncrement(1);
    }
References getAndIncrement().
Referenced by getAndIncrement(), and getAndIncrement().
getAndIncrement() [2/3]
int com.runehive.util.MutableNumber.getAndIncrement (int amount)
Returns the value within this counter and then increments it by amount.
Parameters
amount the amount to append it by.
Returns
the value before it is incremented.
Definition at line 123 of file MutableNumber.java.
{
        return getAndIncrement(amount, Integer.MAX_VALUE);
    }
References getAndIncrement().
getAndIncrement() [3/3]
int com.runehive.util.MutableNumber.getAndIncrement (int amount, int maximum)
Returns the value within this counter and then increments it by amount to a maximum of maximum.
Parameters
amount the amount to append it by.
maximum the maximum amount it will be incremented to.
Returns
the value before it is incremented.
Definition at line 107 of file MutableNumber.java.
{
        int val = value;
        value += amount;
        if (value > maximum)
            value = maximum;
        return val;
    }
References value.
hashCode()
int com.runehive.util.MutableNumber.hashCode ()
Definition at line 51 of file MutableNumber.java.
{
        return Integer.hashCode(value);
    }
References value.
increment()
MutableNumber com.runehive.util.MutableNumber.increment ()
Increments the value within this counter by 1 and then returns it.
Returns
the value after it is incremented.
Definition at line 182 of file MutableNumber.java.
{
        incrementAndGet(1);
        return this;
    }
References incrementAndGet(), and MutableNumber().
incrementAndGet() [1/3]
int com.runehive.util.MutableNumber.incrementAndGet ()
Increments the value within this counter by 1 and then returns it.
Returns
the value after it is incremented.
Definition at line 172 of file MutableNumber.java.
{
        return incrementAndGet(1);
    }
References incrementAndGet().
Referenced by increment(), incrementAndGet(), and incrementAndGet().
incrementAndGet() [2/3]
int com.runehive.util.MutableNumber.incrementAndGet (int amount)
Increments the value within this counter by amount and then returns it.
Parameters
amount the amount to append it by.
Returns
the value after it is incremented.
Definition at line 162 of file MutableNumber.java.
{
        return incrementAndGet(amount, Integer.MAX_VALUE);
    }
References incrementAndGet().
incrementAndGet() [3/3]
int com.runehive.util.MutableNumber.incrementAndGet (int amount, int maximum)
Increments the value within this counter by amount to a maximum of maximum and then returns it.
Parameters
amount the amount to append it by.
maximum the maximum amount it will be incremented to.
Returns
the value after it is incremented.
Definition at line 147 of file MutableNumber.java.
{
        value += amount;
        if (value > maximum)
            value = maximum;
        return value;
    }
References value.
Referenced by com.runehive.content.bot.BotUtility.logLoot(), and com.runehive.content.consume.PotionData.onAntiPoisonEffect().
intValue()
int com.runehive.util.MutableNumber.intValue ()
This function equates to the MutableNumber#get() function.
Definition at line 78 of file MutableNumber.java.
{
        return value;
    }
References value.
Referenced by com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), com.runehive.content.bot.botclass.impl.PureMelee.hit(), com.runehive.content.bot.botclass.impl.PureRangeMelee.hit(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.hit(), and com.runehive.content.bot.botclass.impl.ZerkerMelee.hit().
longValue()
long com.runehive.util.MutableNumber.longValue ()
Definition at line 83 of file MutableNumber.java.
{
        return (long) value;
    }
References value.
set()
void com.runehive.util.MutableNumber.set (int value)
Sets the value within this container to rarity.
Parameters
value the new value to set.
Definition at line 282 of file MutableNumber.java.
{
        this.value = value;
    }
References value.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect().
toString()
String com.runehive.util.MutableNumber.toString ()
Definition at line 46 of file MutableNumber.java.
{
        return Integer.toString(value);
    }
References value.
Member Data Documentation
serialVersionUID
final long com.runehive.util.MutableNumber.serialVersionUID = -7475363158492415879L static private
The constant serial version UID for serialization.
Definition at line 21 of file MutableNumber.java.
value
int com.runehive.util.MutableNumber.value private
The value present within this counter.
Definition at line 26 of file MutableNumber.java.
Referenced by compareTo(), decrementAndGet(), doubleValue(), equals(), floatValue(), get(), getAndDecrement(), getAndIncrement(), hashCode(), incrementAndGet(), intValue(), longValue(), MutableNumber(), set(), and toString().
The documentation for this class was generated from the following file:
java/com/runehive/util/MutableNumber.java