RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager Class Reference
com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager Class Reference
Classes
class CombatListenerSet
Static Public Member Functions
static void addListener (Player player, int id)
static void load ()
static void removeListener (Player player, int id)
Static Public Attributes
static final Map< Integer, CombatListener< Npc > > NPC_LISTENERS = new HashMap<>()
static final Map< Integer, CombatStrategy< Npc > > NPC_STRATEGIES = new HashMap<>()
Static Private Member Functions
static void loadItems (final String pkg)
static void loadNpcs (final String pkg)
Static Private Attributes
static final Map< Integer, Set< CombatListenerSet > > ITEM_LISTENERS = new HashMap<>()
static final Logger logger = LogManager.getLogger(CombatListenerManager.class)
Detailed Description
Author
StanTheWoman
Definition at line 17 of file CombatListenerManager.java.
Member Function Documentation
addListener()
void com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.addListener (Player player, int id) static
Definition at line 96 of file CombatListenerManager.java.
{
        Set<CombatListenerSet> sets = ITEM_LISTENERS.get(id);
        if (sets == null) {
            return;
        }
        for (CombatListenerSet set : sets) {
            if (set.requireAll && !player.equipment.containsAll(set.set)) {
                continue;
            }
            if (!set.requireAll && !player.equipment.containsAny(set.set)) {
                continue;
            }
            player.getCombat().addListener(set.listener);
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.world.items.containers.ItemContainer.containsAny(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.getCombat(), and ITEM_LISTENERS.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated().
load()
void com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.load () static
Definition at line 25 of file CombatListenerManager.java.
{
        loadItems("com.runehive.game.world.entity.combat.attack.listener.item");
        loadNpcs("com.runehive.game.world.entity.combat.attack.listener.npc");
    }
References loadItems(), and loadNpcs().
Referenced by com.runehive.RuneHive.processSequentialStartupTasks().
loadItems()
void com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.loadItems (final String pkg) static private
Definition at line 30 of file CombatListenerManager.java.
{
        try (final ScanResult scanResult =
                     new ClassGraph()
                             .enableClassInfo()
                             .enableMethodInfo()
                             .enableAnnotationInfo()
                             .acceptPackages(pkg)
                             .scan()) {
            for (final ClassInfo classInfo : scanResult.getClassesWithAnnotation(ItemCombatListenerSignature.class)) {
                try {
                    final MethodInfoList constructorInfos = classInfo.getDeclaredConstructorInfo();
                    final MethodInfo constructorInfo = constructorInfos.get(0);
                    final Constructor<?> constructor = constructorInfo.loadClassAndGetConstructor();
                    final Object instance = constructor.newInstance();
                    @SuppressWarnings("unchecked") final CombatListener<Player> listener = (CombatListener<Player>) instance;
                    final AnnotationInfo annotationInfo = classInfo.getAnnotationInfo(ItemCombatListenerSignature.class);
                    final Annotation annotation = annotationInfo.loadClassAndInstantiate();
                    final ItemCombatListenerSignature meta = (ItemCombatListenerSignature) annotation;
                    for (int item : meta.items()) {
                        Set<CombatListenerSet> set = ITEM_LISTENERS.getOrDefault(item, new HashSet<>());
                        set.add(new CombatListenerSet(meta.items(), meta.requireAll(), listener));
                        ITEM_LISTENERS.put(item, set);
                    }
                } catch (Exception ex) {
                    logger.error(String.format("Error loading item set combat listener=%s", classInfo.getSimpleName()), ex);
                }
            }
        }
        logger.info(String.format("Loaded: %d item set combat listeners.", ITEM_LISTENERS.size()));
    }
References ITEM_LISTENERS, com.runehive.game.world.entity.combat.attack.listener.ItemCombatListenerSignature.items(), logger, and com.runehive.game.world.entity.combat.attack.listener.ItemCombatListenerSignature.requireAll().
Referenced by load().
loadNpcs()
void com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.loadNpcs (final String pkg) static private
Definition at line 64 of file CombatListenerManager.java.
{
        try (final ScanResult scanResult =
                     new ClassGraph()
                             .enableClassInfo()
                             .enableMethodInfo()
                             .enableAnnotationInfo()
                             .acceptPackages(pkg)
                             .scan()) {
            for (final ClassInfo classInfo : scanResult.getClassesWithAnnotation(NpcCombatListenerSignature.class)) {
                try {
                    final MethodInfoList constructorInfos = classInfo.getDeclaredConstructorInfo();
                    final MethodInfo constructorInfo = constructorInfos.get(0);
                    final Constructor<?> constructor = constructorInfo.loadClassAndGetConstructor();
                    final Object instance = constructor.newInstance();
                    @SuppressWarnings("unchecked") final CombatListener<Npc> listener = (CombatListener<Npc>) instance;
                    final AnnotationInfo annotationInfo = classInfo.getAnnotationInfo(NpcCombatListenerSignature.class);
                    final Annotation annotation = annotationInfo.loadClassAndInstantiate();
                    final NpcCombatListenerSignature meta = (NpcCombatListenerSignature) annotation;
                    for (int npc : meta.npcs()) {
                        NPC_LISTENERS.put(npc, listener);
                    }
                } catch (Exception ex) {
                    logger.error(String.format("Error loading npc combat listener=%s", classInfo.getSimpleName()), ex);
                }
            }
        }
        logger.info(String.format("Loaded: %d npc combat listeners.", NPC_LISTENERS.size()));
    }
References logger, NPC_LISTENERS, and com.runehive.game.world.entity.combat.attack.listener.NpcCombatListenerSignature.npcs().
Referenced by load().
removeListener()
void com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.removeListener (Player player, int id) static
Definition at line 116 of file CombatListenerManager.java.
{
        Set<CombatListenerSet> sets = ITEM_LISTENERS.get(id);
        if (sets == null) {
            return;
        }
        for (CombatListenerSet set : sets) {
            if (set.requireAll && player.equipment.containsAll(set.set)) {
                continue;
            }
            if (!set.requireAll && player.equipment.containsAny(set.set)) {
                continue;
            }
            player.getCombat().removeListener(set.listener);
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.world.items.containers.ItemContainer.containsAny(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.getCombat(), and ITEM_LISTENERS.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated().
Member Data Documentation
ITEM_LISTENERS
final Map<Integer, Set<CombatListenerSet> > com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.ITEM_LISTENERS = new HashMap<>() static private
Definition at line 21 of file CombatListenerManager.java.
Referenced by addListener(), loadItems(), and removeListener().
logger
final Logger com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.logger = LogManager.getLogger(CombatListenerManager.class) static private
Definition at line 19 of file CombatListenerManager.java.
Referenced by loadItems(), and loadNpcs().
NPC_LISTENERS
final Map<Integer, CombatListener<Npc> > com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.NPC_LISTENERS = new HashMap<>() static
Definition at line 22 of file CombatListenerManager.java.
Referenced by loadNpcs(), com.runehive.game.world.entity.mob.npc.NpcAssistant.login(), and com.runehive.game.world.entity.mob.Mob.transform().
NPC_STRATEGIES
final Map<Integer, CombatStrategy<Npc> > com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.NPC_STRATEGIES = new HashMap<>() static
Definition at line 23 of file CombatListenerManager.java.
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/CombatListenerManager.java