RuneHive-Game: com.runehive.fs.cache.decoder.ObjectDefinitionDecoder Class Reference
com.runehive.fs.cache.decoder.ObjectDefinitionDecoder Class Reference
A class which parses object definitions.
Public Member Functions
ObjectDefinitionDecoder (FileSystem fs)
Creates the ObjectDefinitionDecoder.
void run ()
Static Private Member Functions
static void decode (int id, ByteBuffer buffer)
Parses a single game object definition by reading object info from a buffer.
Private Attributes
final FileSystem fs
The IndexedFileSystem.
Static Private Attributes
static final Logger LOGGER = LogManager.getLogger(ObjectDefinitionDecoder.class)
The logger to log process output.
Detailed Description
A class which parses object definitions.
Author
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Definition at line 18 of file ObjectDefinitionDecoder.java.
Constructor & Destructor Documentation
ObjectDefinitionDecoder()
com.runehive.fs.cache.decoder.ObjectDefinitionDecoder.ObjectDefinitionDecoder (FileSystem fs)
Creates the ObjectDefinitionDecoder.
Parameters
fs The FileSystem.
Definition at line 31 of file ObjectDefinitionDecoder.java.
{
        this.fs = fs;
    }
References fs.
Member Function Documentation
decode()
void com.runehive.fs.cache.decoder.ObjectDefinitionDecoder.decode (int id, ByteBuffer buffer) static private
Parses a single game object definition by reading object info from a buffer.
Parameters
id The id of the object.
buffer The buffer.
Definition at line 68 of file ObjectDefinitionDecoder.java.
{
        String name = "null";
        String desc = "null";
        int width = 1;
        int length = 1;
        boolean solid = true;
        boolean impenetrable = true;
        boolean hasActions = false;
        boolean interactive = false;
        boolean wall = false;
        boolean decoration = false;
        boolean removeClipping = false;
        boolean models = false;
        boolean is10 = true;
        int walkingFlag = 0;
        int lastOpcode = -1;
        while (true) {
            int opcode = buffer.get() & 0xff;
            if (opcode == 0) {
                break;
            }
            if (opcode == 1) {
                int len = buffer.get();
                if (len > 0 && !models) {
                    for (int idx = 0; idx < len; idx++) {
                        buffer.position(buffer.position() + Short.BYTES);
                        if (buffer.get() != 10 && idx == 0) {
                            is10 = false;
                        }
                    }
                } else {
                    buffer.position(buffer.position() + len * (Byte.BYTES + Short.BYTES));
                }
            } else if (opcode == 2) {
                name = ByteBufferUtil.readStringCp1252NullTerminated(buffer);
            } else if (opcode == 3) {
            } else if (opcode == 5) {
                int len = buffer.get();
                if (len > 0) {
                    models = true;
                    buffer.position(buffer.position() + len * Short.BYTES);
                }
            } else if (opcode == 14) {
                width = buffer.get();
            } else if (opcode == 15) {
                length = buffer.get();
            } else if (opcode == 17) {
                solid = false;
                impenetrable = false;
            } else if (opcode == 18) {
                impenetrable = false;
            } else if (opcode == 19) {
                hasActions = (buffer.get() == 1);
            } else if (opcode == 21) {
            } else if (opcode == 22) {
            } else if (opcode == 23) {
            } else if (opcode == 24) {
                buffer.getShort();
            } else if (opcode == 27) {
                // interact type = 1
            } else if (opcode == 28) {
                buffer.get();
            } else if (opcode == 29) {
                buffer.get();
            } else if (opcode == 39) {
                buffer.get();
            } else if (opcode >= 30 && opcode < 35) {
                ByteBufferUtil.readStringCp1252NullTerminated(buffer);
                interactive = true;
            } else if (opcode == 40) {
                int len = buffer.get();
                for (int i = 0; i < len; i++) {
                    buffer.getShort();
                    buffer.getShort();
                }
            } else if (opcode == 41) {
                int len = buffer.get();
                for (int i = 0; i < len; i++) {
                    buffer.getShort();
                    buffer.getShort();
                }
            } else if (opcode == 61) {
                buffer.getShort();
            } else if (opcode == 62) {
                wall = true;
            } else if (opcode == 64) {
            } else if (opcode == 65) {
                buffer.getShort();
            } else if (opcode == 66) {
                buffer.getShort();
            } else if (opcode == 67) {
                buffer.getShort();
            } else if (opcode == 68) {
                buffer.getShort();
            } else if (opcode == 69) {
                walkingFlag = buffer.get();
            } else if (opcode == 70) {
                buffer.getShort();
            } else if (opcode == 71) {
                buffer.getShort();
            } else if (opcode == 72) {
                buffer.getShort();
            } else if (opcode == 73) {
                decoration = true;
            } else if (opcode == 74) {
                removeClipping = true;
            } else if (opcode == 75) {
                buffer.get();
            } else if (opcode == 77) {
                buffer.getShort();
                buffer.getShort();
                int len = buffer.get() & 0xFF;
                for (int i = 0; i <= len; ++i) {
                    buffer.getShort();
                }
            } else if (opcode == 78) {
                buffer.getShort();
                buffer.get();
            } else if (opcode == 79) {
                buffer.getShort();
                buffer.getShort();
                buffer.get();
                int len = buffer.get() & 0xFF;
                for (int i = 0; i < len; ++i) {
                    buffer.getShort();
                }
            } else if (opcode == 81) {
                buffer.get();
            } else if (opcode == 82) {
                buffer.getShort();
            } else if (opcode == 89) {
            } else if (opcode == 92) {
                buffer.getShort();
                buffer.getShort();
                buffer.getShort();
                int len = buffer.get() & 0xFF;
                for (int i = 0; i <= len; ++i) {
                    buffer.getShort();
                }
            } else if (opcode == 249) {
                int len = buffer.get();
                for (int i = 0; i < len; i++) {
                    boolean isString = buffer.get() == 1;
                    ByteBufferUtil.getMedium(buffer);
                    if (isString) {
                        ByteBufferUtil.readStringCp1252NullTerminated(buffer);
                    } else {
                        buffer.getInt();
                    }
                }
            } else {
                // Unknown opcode - break to prevent infinite loop (for cache compatibility with different revisions)
                LOGGER.warn("Unknown object opcode: {} (last: {}) for object id: {}. Skipping remaining opcodes for this object.",
                            opcode, lastOpcode, id);
                break;
            }
            lastOpcode = opcode;
        }
        if (!name.equals("null")) {
            hasActions = models && is10;
            if (interactive) {
                hasActions = true;
            }
        }
        if (removeClipping) {
            solid = false;
            impenetrable = false;
        }
        int distance = 1;
        switch(id) {
            case 31561:
                distance = 2;
                break;
            case 26254:
                name = "Donator Box";
                break;
        }
        GameObjectDefinition.addDefinition(new GameObjectDefinition(id, name, desc, width, length, distance, solid, impenetrable, hasActions, wall, decoration, walkingFlag));
    }
References com.runehive.game.world.object.GameObjectDefinition.addDefinition(), com.runehive.fs.util.ByteBufferUtil.getMedium(), LOGGER, and com.runehive.fs.util.ByteBufferUtil.readStringCp1252NullTerminated().
Referenced by run().
run()
void com.runehive.fs.cache.decoder.ObjectDefinitionDecoder.run ()
Definition at line 36 of file ObjectDefinitionDecoder.java.
                      {
        LOGGER.info("Loading object definitions.");
        Archive archive = fs.getArchive(FileSystem.CONFIG_ARCHIVE);
        ByteBuffer dat = archive.getData("loc.dat");
        ByteBuffer idx = archive.getData("loc.idx");
        int count = idx.getShort() & 0xFFFF;
        // Allow dynamic object count to support different cache versions (Elvarg: 44934, osroyale: 47501)
        if (count != GameObjectDefinition.MAX_DEFINITIONS) {
            LOGGER.warn("GameObjectDefinition count mismatch: cache has " + count + ", expected " +
                        GameObjectDefinition.MAX_DEFINITIONS + ". Using cache count.");
        }
        int pos = 0;
        int loaded = 0;
        for (int index = 0; index < count; index++) {
            dat.position(pos);
            decode(index, dat);
            pos += idx.getShort() & 0xFFFF;
            loaded++;
        }
        LOGGER.info("Loaded " + loaded + " object definitions.");
    }
References com.runehive.fs.cache.FileSystem.CONFIG_ARCHIVE, decode(), fs, LOGGER, and com.runehive.game.world.object.GameObjectDefinition.MAX_DEFINITIONS.
Referenced by com.runehive.RuneHive.processSequentialStartupTasks().
Member Data Documentation
fs
final FileSystem com.runehive.fs.cache.decoder.ObjectDefinitionDecoder.fs private
The IndexedFileSystem.
Definition at line 24 of file ObjectDefinitionDecoder.java.
Referenced by ObjectDefinitionDecoder(), and run().
LOGGER
final Logger com.runehive.fs.cache.decoder.ObjectDefinitionDecoder.LOGGER = LogManager.getLogger(ObjectDefinitionDecoder.class) static private
The logger to log process output.
Definition at line 21 of file ObjectDefinitionDecoder.java.
Referenced by decode(), and run().
The documentation for this class was generated from the following file:
java/com/runehive/fs/cache/decoder/ObjectDefinitionDecoder.java