RuneHive-Game: com.runehive.game.task.TaskDeadlockWatcher Class Reference
com.runehive.game.task.TaskDeadlockWatcher Class Reference
Public Member Functions
void requestExit ()
void run ()
TaskDeadlockWatcher (TaskManager taskManager)
Private Attributes
final HashMap< String, Task > _alreadyAlertedTaskMap = new HashMap<>()
A map of tasks that have already alerted us to a deadlock, we don't want to spam the logs.
boolean exitRequested
final TaskManager taskManager
Static Private Attributes
static final long DEADLOCK_WATCHER_SLEEP_MS = 1000
static final Logger logger = LogManager.getLogger(TaskDeadlockWatcher.class)
static final long TASK_TOO_LONG_MS = 1000
Detailed Description
Definition at line 10 of file TaskDeadlockWatcher.java.
Constructor & Destructor Documentation
TaskDeadlockWatcher()
com.runehive.game.task.TaskDeadlockWatcher.TaskDeadlockWatcher (TaskManager taskManager)
Definition at line 22 of file TaskDeadlockWatcher.java.
{
        this.taskManager = taskManager;
    }
References taskManager.
Member Function Documentation
requestExit()
void com.runehive.game.task.TaskDeadlockWatcher.requestExit ()
Definition at line 26 of file TaskDeadlockWatcher.java.
{
        logger.info("TaskDeadlockWatcher exit requested");
        exitRequested = true;
    }
References exitRequested, and logger.
run()
void com.runehive.game.task.TaskDeadlockWatcher.run ()
Definition at line 33 of file TaskDeadlockWatcher.java.
                      {
        while (!exitRequested) {
            try {
                var tasks = taskManager.getTasks().stream().collect(Collectors.toList()).stream()
                        .filter(t -> t != null && t.getRunStartTime().isPresent())
                        .sorted(Comparator.comparingLong((Task t) -> t.getTaskCreationTime()).reversed())
                        .collect(Collectors.toList());
                for (int i = 0; i < tasks.size(); i++) {
                    var task = tasks.get(i);
                    if (task == null || _alreadyAlertedTaskMap.containsKey(task.getTaskId())) {
                        continue;
                    }
                    if (task.getElapsedTimeFromRunStartTime() > TASK_TOO_LONG_MS) {
                        var elapsedTime = task.getElapsedTimeFromRunStartTime();
                        logger.error("Task {} deadlock detected, task has been running for {}ms, task: {}, stacktrace: {}", task.getTaskId(), elapsedTime, task, task.getCreationStackTraceStr());
                        _alreadyAlertedTaskMap.put(task.getTaskId(), task);
                    }
                }
                Thread.sleep(DEADLOCK_WATCHER_SLEEP_MS);
            } catch (Exception ex) {
                logger.error("Error in TaskDeadlockWatcher", ex);
            }
        }
    }
References _alreadyAlertedTaskMap, DEADLOCK_WATCHER_SLEEP_MS, exitRequested, com.runehive.game.task.Task.getTaskCreationTime(), logger, TASK_TOO_LONG_MS, and taskManager.
Member Data Documentation
_alreadyAlertedTaskMap
final HashMap<String, Task> com.runehive.game.task.TaskDeadlockWatcher._alreadyAlertedTaskMap = new HashMap<>() private
A map of tasks that have already alerted us to a deadlock, we don't want to spam the logs.
Definition at line 20 of file TaskDeadlockWatcher.java.
Referenced by run().
DEADLOCK_WATCHER_SLEEP_MS
final long com.runehive.game.task.TaskDeadlockWatcher.DEADLOCK_WATCHER_SLEEP_MS = 1000 static private
Definition at line 13 of file TaskDeadlockWatcher.java.
Referenced by run().
exitRequested
boolean com.runehive.game.task.TaskDeadlockWatcher.exitRequested private
Definition at line 11 of file TaskDeadlockWatcher.java.
Referenced by requestExit(), and run().
logger
final Logger com.runehive.game.task.TaskDeadlockWatcher.logger = LogManager.getLogger(TaskDeadlockWatcher.class) static private
Definition at line 15 of file TaskDeadlockWatcher.java.
Referenced by requestExit(), and run().
TASK_TOO_LONG_MS
final long com.runehive.game.task.TaskDeadlockWatcher.TASK_TOO_LONG_MS = 1000 static private
Definition at line 14 of file TaskDeadlockWatcher.java.
Referenced by run().
taskManager
final TaskManager com.runehive.game.task.TaskDeadlockWatcher.taskManager private
Definition at line 12 of file TaskDeadlockWatcher.java.
Referenced by run(), and TaskDeadlockWatcher().
The documentation for this class was generated from the following file:
java/com/runehive/game/task/TaskDeadlockWatcher.java