RuneHive-Game: com.runehive.content.activity.randomevent.RandomEventHandler Class Reference
com.runehive.content.activity.randomevent.RandomEventHandler Class Reference
Static Public Member Functions
static void trigger (Player player)
Detailed Description
Definition at line 12 of file RandomEventHandler.java.
Member Function Documentation
trigger()
void com.runehive.content.activity.randomevent.RandomEventHandler.trigger (Player player) static
Definition at line 14 of file RandomEventHandler.java.
{
        if (Area.inWilderness(player))
            return;
        if (player.playerAssistant.busy())
            return;
        if (player.inActivity())
            return;
        if (!player.isVisible())
            return;
        int base = 200;
        if (Utility.random(base) != 0)
            return;
        int events = RandomUtils.inclusive(1, 3);
        switch (events) {
            case 1: GenieEvent.create(player); break;
            case 2: MimeEvent.create(player);  break;
            case 3: DrillDemonEvent.create(player); break;
        }
    }
References com.runehive.game.world.entity.mob.player.PlayerAssistant.busy(), com.runehive.content.activity.randomevent.impl.DrillDemonEvent.create(), com.runehive.content.activity.randomevent.impl.GenieEvent.create(), com.runehive.content.activity.randomevent.impl.MimeEvent.create(), com.runehive.game.world.entity.mob.Mob.inActivity(), com.runehive.util.RandomUtils.inclusive(), com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.Entity.isVisible(), com.runehive.game.world.entity.mob.player.Player.playerAssistant, and com.runehive.util.Utility.random().
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.skill.impl.hunter.net.Netting.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), and com.runehive.content.skill.impl.smithing.Smelting.smelt().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/randomevent/RandomEventHandler.java