RuneHive-Game: dev.advo.fs.fs.Index Class Reference
dev.advo.fs.fs.Index Class Reference
An Index points to a file in the main_file_cache.dat file.
Public Member Functions
int getBlock ()
Gets the first block of the file.
int getSize ()
Gets the size of the file.
Index (int size, int block)
Creates the index.
Static Public Member Functions
static Index decode (byte[] buffer)
Decodes a buffer into an index.
Private Attributes
final int block
The first block of the file.
final int size
The size of the file.
Detailed Description
An Index points to a file in the main_file_cache.dat file.
Author
Graham
Definition at line 7 of file Index.java.
Constructor & Destructor Documentation
Index()
dev.advo.fs.fs.Index.Index (int size, int block)
Creates the index.
Parameters
size The size of the file.
block The first block of the file.
Definition at line 41 of file Index.java.
{
        this.size = size;
        this.block = block;
    }
References block, and size.
Referenced by decode().
Member Function Documentation
decode()
Index dev.advo.fs.fs.Index.decode (byte[] buffer) static
Decodes a buffer into an index.
Parameters
buffer The buffer.
Returns
The decoded Index.
Exceptions
IllegalArgumentException if the buffer length is invalid.
Definition at line 15 of file Index.java.
{
        if (buffer.length != FileSystemConstants.INDEX_SIZE) {
            throw new IllegalArgumentException("Incorrect buffer length.");
        }
        int size = ((buffer[0] & 0xFF) << 16) | ((buffer[1] & 0xFF) << 8) | (buffer[2] & 0xFF);
        int block = ((buffer[3] & 0xFF) << 16) | ((buffer[4] & 0xFF) << 8) | (buffer[5] & 0xFF);
        return new Index(size, block);
    }
References block, Index(), dev.advo.fs.fs.FileSystemConstants.INDEX_SIZE, and size.
Referenced by dev.advo.fs.fs.IndexedFileSystem.getIndex().
getBlock()
int dev.advo.fs.fs.Index.getBlock ()
Gets the first block of the file.
Returns
The first block of the file.
Definition at line 58 of file Index.java.
{
        return block;
    }
References block.
getSize()
int dev.advo.fs.fs.Index.getSize ()
Gets the size of the file.
Returns
The size of the file.
Definition at line 50 of file Index.java.
{
        return size;
    }
References size.
Member Data Documentation
block
final int dev.advo.fs.fs.Index.block private
The first block of the file.
Definition at line 34 of file Index.java.
Referenced by decode(), getBlock(), and Index().
size
final int dev.advo.fs.fs.Index.size private
The size of the file.
Definition at line 29 of file Index.java.
Referenced by decode(), getSize(), and Index().
The documentation for this class was generated from the following file:
java/dev/advo/fs/fs/Index.java