RuneHive-Game: com.runehive.content.skill.impl.fishing.FishingAction Class Reference
com.runehive.content.skill.impl.fishing.FishingAction Class Reference
Created by Daniel on 2017-12-18.
Public Member Functions
void execute ()
A function representing the unit of work that will be carried out.
String getName ()
Gets the name of this action.
WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
boolean prioritized ()
Determines if this action is prioritized.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Protected Member Functions
boolean canSchedule ()
A function executed on registration.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
Package Functions
FishingAction (Player player, FishingTool tool, Fishable[] fishing)
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Private Member Functions
boolean fish (Player player, Fishable[] fishing)
Private Attributes
final Fishable[] fishing
final FishingTool tool
Detailed Description
Created by Daniel on 2017-12-18.
Definition at line 22 of file FishingAction.java.
Constructor & Destructor Documentation
FishingAction()
com.runehive.content.skill.impl.fishing.FishingAction.FishingAction (Player player, FishingTool tool, Fishable[] fishing) package
Definition at line 26 of file FishingAction.java.
{
        super(player, 6, false);
        this.tool = tool;
        this.fishing = fishing;
    }
References fishing, and tool.
Member Function Documentation
canSchedule()
boolean com.runehive.content.skill.impl.fishing.FishingAction.canSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 100 of file FishingAction.java.
{
        return !getMob().skills.get(Skill.FISHING).isDoingSkill();
    }
References com.runehive.game.world.entity.skill.Skill.FISHING, and com.runehive.game.action.Action< T extends Mob >.getMob().
execute()
void com.runehive.content.skill.impl.fishing.FishingAction.execute ()
A function representing the unit of work that will be carried out.
Reimplemented from com.runehive.game.task.Task.
Definition at line 110 of file FishingAction.java.
{
        if (!getMob().skills.get(Skill.FISHING).isDoingSkill()) {
            cancel();
            return;
        }
        getMob().animate(tool.getAnimationId());
        if (!fish(getMob(), fishing)) {
            cancel();
        }
    }
References com.runehive.game.task.Task.cancel(), fish(), com.runehive.game.world.entity.skill.Skill.FISHING, fishing, com.runehive.game.action.Action< T extends Mob >.getMob(), and tool.
fish()
boolean com.runehive.content.skill.impl.fishing.FishingAction.fish (Player player, Fishable[] fishing) private
Definition at line 32 of file FishingAction.java.
{
        if (fishing == null)
            return false;
        Fishable[] fish = new Fishable[5];
        byte c = 0;
        for (Fishable aFishing : fishing) {
            if (Fishing.canFish(player, aFishing, false)) {
                fish[c] = aFishing;
                c = (byte) (c + 1);
            }
        }
        if (c == 0) {
            return false;
        }
        Fishable f = fish[Utility.random(c)];
        if (player.inventory.getFreeSlots() == 0) {
            player.dialogueFactory.sendStatement("You can't carry anymore fish.").execute();
            player.animate(Animation.RESET, true);
            return false;
        }
        if (Fishing.success(player, f)) {
            if (f.getBaitRequired() != -1) {
                player.inventory.remove(new Item(f.getBaitRequired(), 1));
                if (!player.inventory.contains(f.getBaitRequired(), 1)) {
                    player.dialogueFactory.sendStatement("You have run out of bait.").execute();
                    player.animate(Animation.RESET, true);
                    return false;
                }
            }
            boolean infernalHarpoon = player.equipment.contains(21031) && Utility.random(3) == 0 && (f.equals(Fishable.SWORD_FISH) || f.equals(Fishable.SWORD_FISH2) || f.equals(Fishable.SWORD_FISH) || f.equals(Fishable.TUNA) || f.equals(Fishable.TUNA2) || f.equals(Fishable.SHARK));
            int id = f.getRawFishId();
            String name = ItemDefinition.get(id).getName();
            if(!infernalHarpoon)
                player.inventory.add(new Item(id, 1));
            else {
                double xp = f.equals(Fishable.SWORD_FISH) || f.equals(Fishable.SWORD_FISH2) ? 70 : f.equals(Fishable.TUNA) || f.equals(Fishable.TUNA2) ? 50 : 105;
                player.skills.addExperience(Skill.COOKING, xp * Config.COOKING_MODIFICATION);
            }
            player.skills.addExperience(Skill.FISHING, f.getExperience() * Config.FISHING_MODIFICATION);
            player.message(true, "You manage to catch a " + name + ".");
            RandomEventHandler.trigger(player);
            player.playerAssistant.activateSkilling(1);
            Pets.onReward(player, PetData.HERON.getItem(), 7500);
            if (player.prestige.hasPerk(PrestigePerk.MASTERBAIRTER) && RandomUtils.success(.15)) {
                player.inventory.addOrDrop(new Item(id, 1));
            }
            if (id == 383) {
                player.forClan(channel -> channel.activateTask(ClanTaskKey.SHARK, player.getName()));
            } else if (id == 11934) {
                player.forClan(channel -> channel.activateTask(ClanTaskKey.DARK_CRAB, player.getName()));
            }
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.content.skill.impl.fishing.Fishing.canFish(), com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.skill.Skill.COOKING, com.runehive.Config.COOKING_MODIFICATION, com.runehive.content.clanchannel.content.ClanTaskKey.DARK_CRAB, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.content.dialogue.DialogueFactory.execute(), fish(), com.runehive.game.world.entity.skill.Skill.FISHING, fishing, com.runehive.Config.FISHING_MODIFICATION, com.runehive.game.world.entity.mob.player.Player.forClan(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.content.skill.impl.fishing.Fishable.getBaitRequired(), com.runehive.content.skill.impl.fishing.Fishable.getExperience(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.content.skill.impl.fishing.Fishable.getRawFishId(), com.runehive.content.prestige.Prestige.hasPerk(), com.runehive.content.pet.PetData.HERON, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.prestige.PrestigePerk.MASTERBAIRTER, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.pet.Pets.onReward(), com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.game.world.entity.mob.player.Player.prestige, com.runehive.util.Utility.random(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.Animation.RESET, com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.content.clanchannel.content.ClanTaskKey.SHARK, com.runehive.content.skill.impl.fishing.Fishable.SHARK, com.runehive.game.world.entity.mob.Mob.skills, com.runehive.content.skill.impl.fishing.Fishing.success(), com.runehive.util.RandomUtils.success(), com.runehive.content.skill.impl.fishing.Fishable.SWORD_FISH, com.runehive.content.skill.impl.fishing.Fishable.SWORD_FISH2, com.runehive.content.activity.randomevent.RandomEventHandler.trigger(), com.runehive.content.skill.impl.fishing.Fishable.TUNA, and com.runehive.content.skill.impl.fishing.Fishable.TUNA2.
Referenced by execute(), and fish().
getName()
String com.runehive.content.skill.impl.fishing.FishingAction.getName ()
Gets the name of this action.
Returns
The name of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 135 of file FishingAction.java.
{
        return "fishing-action";
    }
getWalkablePolicy()
WalkablePolicy com.runehive.content.skill.impl.fishing.FishingAction.getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 130 of file FishingAction.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
onCancel()
void com.runehive.content.skill.impl.fishing.FishingAction.onCancel (boolean logout) protected
A function executed on cancellation.
Reimplemented from com.runehive.game.task.Task.
Definition at line 124 of file FishingAction.java.
{
        getMob().resetFace();
        getMob().skills.get(Skill.FISHING).setDoingSkill(false);
    }
References com.runehive.game.world.entity.skill.Skill.FISHING, and com.runehive.game.action.Action< T extends Mob >.getMob().
onSchedule()
void com.runehive.content.skill.impl.fishing.FishingAction.onSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 105 of file FishingAction.java.
{
        getMob().animate(tool.getAnimationId());
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), and tool.
Member Data Documentation
fishing
final Fishable [] com.runehive.content.skill.impl.fishing.FishingAction.fishing private
Definition at line 24 of file FishingAction.java.
Referenced by execute(), fish(), and FishingAction().
tool
final FishingTool com.runehive.content.skill.impl.fishing.FishingAction.tool private
Definition at line 23 of file FishingAction.java.
Referenced by execute(), FishingAction(), and onSchedule().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/fishing/FishingAction.java