RuneHive-Game: com.runehive.game.world.object.CustomGameObject Class Reference
com.runehive.game.world.object.CustomGameObject Class Reference
Represents a static game object loaded from the map fs.
Public Member Functions
boolean active ()
Determines if this object is active on the world.
void addToRegion (Region objectRegion)
Adds this entity to the specified region.
CustomGameObject (int id, int instance, Position position)
CustomGameObject (int id, int instance, Position position, ObjectDirection direction, ObjectType type)
CustomGameObject (int id, Position position)
CustomGameObject (int id, Position position, ObjectDirection direction, ObjectType type)
int distance ()
boolean equals (Object obj)
GameObjectDefinition getDefinition ()
Gets the object definition.
ObjectDirection getDirection ()
Gets the rotation.
GenericAttributes getGenericAttributes ()
Gets the generic attributes.
int getInstancedHeight ()
String getName ()
Gets the name of this entity.
ObjectType getObjectType ()
Gets the object type.
EntityType getType ()
Gets the EntityType.
int hashCode ()
int length ()
void register ()
Registers an entity to the World.
void removeFromRegion (Region objectRegion)
Removes this entity from the specified region.
void rotate (ObjectDirection direction)
String toString ()
void transform (int id)
void unregister ()
Unregisters an entity from the World.
int width ()
Public Member Functions inherited from com.runehive.game.world.entity.Entity
Entity (Position position)
Entity (Position position, boolean visible)
Position getCenterPosition ()
int getHeight ()
int getIndex ()
Position getPosition ()
Region getRegion ()
int getX ()
int getY ()
boolean is (EntityType type)
final boolean isCustomObject ()
Check if an entity is an object.
final boolean isRegistered ()
final boolean isStaticObject ()
Check if an entity is an object.
boolean isValid ()
Validates this npc based on its current region and registered state.
boolean isVisible ()
void onStep ()
void setIndex (int index)
void setLength (int length)
void setPosition (Position position)
void setVisible (boolean visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
void setZ (int z)
Public Member Functions inherited from com.runehive.game.world.object.GameObject
default int getId ()
Gets the object id.
Position getPosition ()
Gets the regional location.
Private Attributes
GameObjectDefinition definition
The object definition.
ObjectDirection direction
The object direction.
GenericAttributes genericAttributes
The generic attributes.
ObjectType type
The object type.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.Interactable
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Public Attributes inherited from com.runehive.game.world.entity.Entity
int instance = DEFAULT_INSTANCE
Static Public Attributes inherited from com.runehive.game.world.entity.Entity
static final int DEFAULT_INSTANCE = 0
Protected Member Functions inherited from com.runehive.game.world.entity.Entity
Entity destroy ()
Destroys this entity.
void setRegistered (boolean registered)
Detailed Description
Represents a static game object loaded from the map fs.
Author
Michael | Chex
Definition at line 25 of file CustomGameObject.java.
Constructor & Destructor Documentation
CustomGameObject() [1/4]
com.runehive.game.world.object.CustomGameObject.CustomGameObject (int id, int instance, Position position, ObjectDirection direction, ObjectType type)
Definition at line 39 of file CustomGameObject.java.
{
        super(position);
        this.definition = GameObjectDefinition.forId(id);
        this.instance = instance;
        this.direction = direction;
        this.type = type;
    }
References direction, com.runehive.game.world.object.GameObjectDefinition.forId(), com.runehive.game.world.entity.Entity.instance, com.runehive.game.world.entity.Entity.position, and type.
Referenced by equals().
CustomGameObject() [2/4]
com.runehive.game.world.object.CustomGameObject.CustomGameObject (int id, Position position, ObjectDirection direction, ObjectType type)
Definition at line 47 of file CustomGameObject.java.
{
        this(id, Mob.DEFAULT_INSTANCE, position, direction, type);
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, direction, com.runehive.game.world.entity.Entity.position, and type.
CustomGameObject() [3/4]
com.runehive.game.world.object.CustomGameObject.CustomGameObject (int id, int instance, Position position)
Definition at line 51 of file CustomGameObject.java.
{
        this(id, instance, position, NORTH, ObjectType.GENERAL_PROP);
    }
References com.runehive.game.world.object.ObjectType.GENERAL_PROP, com.runehive.game.world.entity.Entity.instance, and com.runehive.game.world.entity.Entity.position.
CustomGameObject() [4/4]
com.runehive.game.world.object.CustomGameObject.CustomGameObject (int id, Position position)
Definition at line 55 of file CustomGameObject.java.
{
        this(id, Mob.DEFAULT_INSTANCE, position, NORTH, ObjectType.GENERAL_PROP);
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, com.runehive.game.world.object.ObjectType.GENERAL_PROP, and com.runehive.game.world.entity.Entity.position.
Member Function Documentation
active()
boolean com.runehive.game.world.object.CustomGameObject.active ()
Determines if this object is active on the world.
Implements com.runehive.game.world.object.GameObject.
Definition at line 133 of file CustomGameObject.java.
{
        return isRegistered();
    }
References com.runehive.game.world.entity.Entity.isRegistered().
addToRegion()
void com.runehive.game.world.object.CustomGameObject.addToRegion (Region region)
Adds this entity to the specified region.
Parameters
region The region.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 138 of file CustomGameObject.java.
{
        if (!objectRegion.containsObject(getHeight(), this)) {
            TraversalMap.markObject(objectRegion, this, true, true);
            for (Region region : World.getRegions().getSurroundingRegions(getPosition())) {
                for (Player other : region.getPlayers(getHeight())) {
                    if (other.instance != getInstancedHeight())
                        continue;
                    other.send(new SendAddObject(this));
                }
            }
        }
    }
References com.runehive.game.world.region.Region.containsObject(), com.runehive.game.world.entity.Entity.getHeight(), getInstancedHeight(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.region.RegionManager.getSurroundingRegions(), and com.runehive.game.world.pathfinding.TraversalMap.markObject().
Referenced by register().
distance()
int com.runehive.game.world.object.CustomGameObject.distance ()
Implements com.runehive.game.world.object.GameObject.
Definition at line 93 of file CustomGameObject.java.
{
        return definition.getDistance();
    }
References definition.
equals()
boolean com.runehive.game.world.object.CustomGameObject.equals (Object obj)
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 196 of file CustomGameObject.java.
{
        if (obj instanceof CustomGameObject) {
            CustomGameObject other = (CustomGameObject) obj;
            return definition == other.definition && getPosition().equals(other.getPosition()) && getInstancedHeight() == other.getInstancedHeight();
        }
        return obj == this;
    }
References CustomGameObject(), definition, com.runehive.game.world.position.Position.equals(), getInstancedHeight(), and com.runehive.game.world.entity.Entity.getPosition().
getDefinition()
GameObjectDefinition com.runehive.game.world.object.CustomGameObject.getDefinition ()
Gets the object definition.
Implements com.runehive.game.world.object.GameObject.
Definition at line 72 of file CustomGameObject.java.
{
        return definition;
    }
References definition.
getDirection()
ObjectDirection com.runehive.game.world.object.CustomGameObject.getDirection ()
Gets the rotation.
Implements com.runehive.game.world.object.GameObject.
Definition at line 103 of file CustomGameObject.java.
{
        return direction;
    }
References direction.
Referenced by toString().
getGenericAttributes()
GenericAttributes com.runehive.game.world.object.CustomGameObject.getGenericAttributes ()
Gets the generic attributes.
Implements com.runehive.game.world.object.GameObject.
Definition at line 65 of file CustomGameObject.java.
{
        if (genericAttributes == null)
            genericAttributes = new GenericAttributes();
        return genericAttributes;
    }
References genericAttributes.
getInstancedHeight()
int com.runehive.game.world.object.CustomGameObject.getInstancedHeight ()
Implements com.runehive.game.world.object.GameObject.
Definition at line 60 of file CustomGameObject.java.
{
        return instance;
    }
References com.runehive.game.world.entity.Entity.instance.
Referenced by addToRegion(), equals(), and removeFromRegion().
getName()
String com.runehive.game.world.object.CustomGameObject.getName ()
Gets the name of this entity.
Returns
The entity's name.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 181 of file CustomGameObject.java.
{
        return definition.getName();
    }
References definition.
Referenced by com.runehive.content.skill.impl.construction.House.construct().
getObjectType()
ObjectType com.runehive.game.world.object.CustomGameObject.getObjectType ()
Gets the object type.
Implements com.runehive.game.world.object.GameObject.
Definition at line 98 of file CustomGameObject.java.
{
        return type;
    }
References type.
Referenced by toString().
getType()
EntityType com.runehive.game.world.object.CustomGameObject.getType ()
Gets the EntityType.
Returns
The EntityType.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 186 of file CustomGameObject.java.
{
        return EntityType.CUSTOM_OBJECT;
    }
References com.runehive.game.world.entity.EntityType.CUSTOM_OBJECT.
hashCode()
int com.runehive.game.world.object.CustomGameObject.hashCode ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 191 of file CustomGameObject.java.
{
        return Objects.hash(definition.getId(), getPosition());
    }
References definition, and com.runehive.game.world.entity.Entity.getPosition().
length()
int com.runehive.game.world.object.CustomGameObject.length ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 85 of file CustomGameObject.java.
{
        if (direction == NORTH || direction == SOUTH) {
            return definition.getWidth();
        }
        return definition.getLength();
    }
References definition, and direction.
Referenced by toString().
register()
void com.runehive.game.world.object.CustomGameObject.register ()
Registers an entity to the World.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 108 of file CustomGameObject.java.
{
        if (!isRegistered()) {
            Region region = getRegion();
            setRegistered(true);
            if (region == null) {
                setPosition(getPosition());
            } else if (!region.containsObject(getHeight(), this)) {
                addToRegion(region);
            }
            Region.ACTIVE_OBJECT.put(getPosition(), this);
        }
    }
References com.runehive.game.world.region.Region.ACTIVE_OBJECT, addToRegion(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.getRegion(), com.runehive.game.world.entity.Entity.isRegistered(), com.runehive.game.world.entity.Entity.setPosition(), and com.runehive.game.world.entity.Entity.setRegistered().
Referenced by com.runehive.content.skill.impl.construction.House.construct(), com.runehive.content.skill.impl.construction.House.enter(), com.runehive.content.skill.impl.construction.House.enter(), com.runehive.util.parser.impl.GlobalObjectParser.parse(), com.runehive.content.gambling.impl.FlowerPoker.plant(), com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), rotate(), com.runehive.content.lms.LMSGame.setupSafezone(), com.runehive.content.skill.impl.construction.House.toolkit(), and transform().
removeFromRegion()
void com.runehive.game.world.object.CustomGameObject.removeFromRegion (Region region)
Removes this entity from the specified region.
Parameters
region The region.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 152 of file CustomGameObject.java.
{
        if (objectRegion.containsObject(getHeight(), this)) {
            TraversalMap.markObject(objectRegion, this, false, true);
            for (Region region : World.getRegions().getSurroundingRegions(getPosition())) {
                for (Player other : region.getPlayers(getHeight())) {
                    if (other.instance != getInstancedHeight()) {
                        continue;
                    }
                    other.send(new SendRemoveObject(this));
                }
            }
        }
    }
References com.runehive.game.world.region.Region.containsObject(), com.runehive.game.world.entity.Entity.getHeight(), getInstancedHeight(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.region.RegionManager.getSurroundingRegions(), and com.runehive.game.world.pathfinding.TraversalMap.markObject().
Referenced by unregister().
rotate()
void com.runehive.game.world.object.CustomGameObject.rotate (ObjectDirection direction)
Implements com.runehive.game.world.object.GameObject.
Definition at line 174 of file CustomGameObject.java.
{
        unregister();
        this.direction = direction;
        register();
    }
References direction, register(), and unregister().
toString()
String com.runehive.game.world.object.CustomGameObject.toString ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 205 of file CustomGameObject.java.
{
        return String.format("CustomGameObject[id=%s, loc=%s, width=%s, len=%s, rot=%s, type=%s]", getId(), getPosition(), width(), length(), getDirection(), getObjectType());
    }
References getDirection(), com.runehive.game.world.object.GameObject.getId(), getObjectType(), com.runehive.game.world.entity.Entity.getPosition(), length(), and width().
transform()
void com.runehive.game.world.object.CustomGameObject.transform (int id)
Implements com.runehive.game.world.object.GameObject.
Definition at line 167 of file CustomGameObject.java.
{
        unregister();
        definition = GameObjectDefinition.forId(id);
        register();
    }
References definition, com.runehive.game.world.object.GameObjectDefinition.forId(), register(), and unregister().
unregister()
void com.runehive.game.world.object.CustomGameObject.unregister ()
Unregisters an entity from the World.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 124 of file CustomGameObject.java.
{
        if (isRegistered()) {
            Region.ACTIVE_OBJECT.remove(getPosition(), this);
            removeFromRegion(getRegion());
            destroy();
        }
    }
References com.runehive.game.world.region.Region.ACTIVE_OBJECT, com.runehive.game.world.entity.Entity.destroy(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.getRegion(), com.runehive.game.world.entity.Entity.isRegistered(), and removeFromRegion().
Referenced by com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), rotate(), and transform().
width()
int com.runehive.game.world.object.CustomGameObject.width ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 77 of file CustomGameObject.java.
                       {
        if (direction == NORTH || direction == SOUTH) {
            return definition.getLength();
        }
        return definition.getWidth();
    }
References definition, and direction.
Referenced by toString().
Member Data Documentation
definition
GameObjectDefinition com.runehive.game.world.object.CustomGameObject.definition private
The object definition.
Definition at line 28 of file CustomGameObject.java.
Referenced by distance(), equals(), getDefinition(), getName(), hashCode(), length(), transform(), and width().
direction
ObjectDirection com.runehive.game.world.object.CustomGameObject.direction private
The object direction.
Definition at line 31 of file CustomGameObject.java.
Referenced by CustomGameObject(), CustomGameObject(), getDirection(), length(), rotate(), and width().
genericAttributes
GenericAttributes com.runehive.game.world.object.CustomGameObject.genericAttributes private
The generic attributes.
Definition at line 37 of file CustomGameObject.java.
Referenced by getGenericAttributes().
type
ObjectType com.runehive.game.world.object.CustomGameObject.type private
The object type.
Definition at line 34 of file CustomGameObject.java.
Referenced by CustomGameObject(), CustomGameObject(), and getObjectType().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/object/CustomGameObject.java