RuneHive-Game: com.runehive.game.world.entity.mob.player.exchange.ExchangeSession Class Reference
com.runehive.game.world.entity.mob.player.exchange.ExchangeSession Class Reference abstract
Public Member Functions
abstract void accept (Player player, String COMPONENT)
The method invoked when a PLAYER accepts a certain exchange component.
final boolean add (Player player, int slot, int amount)
Attempts to deposit an item to the container.
abstract boolean canAddItem (Player player, Item item, int slot)
Checks if the item can be added to the container.
abstract boolean canRemoveItem (Player player, Item item, int slot)
Checks if the item can be removed from the container.
void depositeAll (Player player)
Deposites all items to the exchange session.
ExchangeSession (Player player, Player other, ExchangeSessionType type)
Constructs a new ExchangeSession.
void forEach (Consumer< Player > action)
Executes the specified action for every player in this session.
Object getAttachment ()
Retrieves the attachment object to this class.
Player getOther (Player p)
Gets the other player in the exchange session.
boolean hasAttachment ()
Determines if the trade stage has an attachment.
boolean inAnySession ()
Determines if the player is any session.
abstract boolean onButtonClick (Player player, int button)
The method invoked when a button is clicked.
abstract boolean onRequest ()
The method invoked when a player requests the other player.
abstract void onReset ()
Any functionality that should be handled when the itemcontainer closes.
final boolean remove (Player player, int slot, int amount)
Attempts to withdraw an item from the container.
boolean request ()
Attempts to start an exchange session.
void setAttachment (Object attachment)
Assigns an attachment to this stage object.
abstract void updateMainComponents (String component)
Updates the main components of the itemcontainer.
abstract void updateOfferComponents ()
Updates the itemcontainer when an item is offered or removed.
Static Public Member Functions
static Optional< ExchangeSession > getSession (Player player)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, ExchangeSessionType type)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, Player other)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, Player other, ExchangeSessionType type)
Gets the session if applicable the player is in.
static boolean inSession (Player player, ExchangeSessionType type)
Determines if the player is a session which matches the type.
static boolean inSession (Player player, Player other, ExchangeSessionType type)
Determines if the player is a session with other which matches the type.
Public Attributes
boolean canOffer = true
Determines if the player can offer or withdraw items.
boolean finalized
Determines if this exchange has been finalized.
final Map< Player, ItemContainer > item_containers = new HashMap<>()
The items which are in this exchange session.
final Player other
The other player in this session.
final Player player
The controller of this session.
final ExchangeSessionType type
The type of this exchange session.
Static Public Attributes
static final Set< ExchangeSession > SESSIONS = new HashSet<>()
The collection of sessions.
Protected Member Functions
void finalize (ExchangeCompletionType type)
Finalizes the exchange session procedure for the specified player in a session.
void withdrawAll (Player player)
Withdraws all items from the exchange session.
Static Private Member Functions
static boolean allMatch (ExchangeSession session, String name, String otherName)
static boolean anyMatch (ExchangeSession session, String name)
Private Attributes
Object attachment
The attachment to the session stage, this will more than likely be a player object that will be attached when they have confirmed a certain stage.
Detailed Description
Author
Stand Up
Since
23-1-2017.
Definition at line 23 of file ExchangeSession.java.
Constructor & Destructor Documentation
ExchangeSession()
com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.ExchangeSession (Player player, Player other, ExchangeSessionType type)
Constructs a new ExchangeSession.
Definition at line 47 of file ExchangeSession.java.
{
        this.player = player;
        this.other = other;
        this.type = type;
        forEach(p -> item_containers.put(p, new ItemContainer(28, ItemContainer.StackPolicy.STANDARD)));
    }
References forEach(), item_containers, other, player, com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD, and type.
Referenced by allMatch(), and anyMatch().
Member Function Documentation
accept()
abstract void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.accept (Player player, String COMPONENT) abstract
The method invoked when a PLAYER accepts a certain exchange component.
Reimplemented in com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession, and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.
References player.
add()
final boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.add (Player player, int slot, int amount)
Attempts to deposit an item to the container.
Definition at line 163 of file ExchangeSession.java.
{
        Item invItem = player.inventory.get(slot);
        if (invItem == null) {
            return false;
        }
        if (!Item.valid(invItem) || !player.inventory.contains(invItem.getId())) {
            return false;
        }
        if (!canOffer) {
            return false;
        }
        if (!inSession(player, type)) {
            return false;
        }
        if (!canAddItem(player, invItem, slot)) {
            return false;
        }
        if (!invItem.isTradeable() && !PlayerRight.isOwner(player)) {
            player.message("You can't offer this item.");
            return false;
        }
        Item item = new Item(invItem.getId(), amount);
        int count = player.inventory.computeAmountForId(item.getId());
        if (item.getAmount() > count) {
            item.setAmount(count);
        }
        if (item_containers.get(player).add(item)) {
            player.inventory.remove(item);
            updateOfferComponents();
            return true;
        }
        return false;
    }
References canAddItem(), canOffer, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), inSession(), com.runehive.game.world.entity.mob.player.PlayerRight.isOwner(), com.runehive.game.world.items.Item.isTradeable(), item_containers, player, com.runehive.game.world.items.Item.setAmount(), type, updateOfferComponents(), and com.runehive.game.world.items.Item.valid().
Referenced by com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.deposit().
allMatch()
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.allMatch (ExchangeSession session, String name, String otherName) static private
Definition at line 395 of file ExchangeSession.java.
{
        return Arrays.stream(new String[]{session.player.getName(), session.other.getName()}).anyMatch(n -> n.equals(name) || n.equals(otherName));
    }
References anyMatch(), ExchangeSession(), com.runehive.game.world.entity.mob.player.Player.getName(), other, and player.
Referenced by getSession(), getSession(), and inSession().
anyMatch()
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.anyMatch (ExchangeSession session, String name) static private
Definition at line 391 of file ExchangeSession.java.
{
        return Arrays.stream(new String[]{session.player.getName(), session.other.getName()}).anyMatch(n -> n.equals(name));
    }
References anyMatch(), ExchangeSession(), com.runehive.game.world.entity.mob.player.Player.getName(), other, and player.
Referenced by allMatch(), anyMatch(), getSession(), and getSession().
canAddItem()
abstract boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.canAddItem (Player player, Item item, int slot) abstract
Checks if the item can be added to the container.
Reimplemented in com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession, and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.
References player.
Referenced by add().
canRemoveItem()
abstract boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.canRemoveItem (Player player, Item item, int slot) abstract
Checks if the item can be removed from the container.
Reimplemented in com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession, and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.
References player.
Referenced by remove().
depositeAll()
void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.depositeAll (Player player)
Deposites all items to the exchange session.
Definition at line 267 of file ExchangeSession.java.
{
        Inventory inventory = player.inventory;
        if (inventory.isEmpty()) {
            player.message("There is nothing in your inventory to deposit!");
            return;
        }
        List<Item> transfer = new ArrayList<>();
        for (Item item : inventory.getItems()) {
            if (item == null || !item.isTradeable()) {
                continue;
            }
            transfer.add(item);
        }
        this.item_containers.get(player).addAll(transfer);
        inventory.removeAll(transfer);
        inventory.refresh();
        updateOfferComponents();
    }
References com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.items.containers.ItemContainer.isEmpty(), player, com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.removeAll(), and updateOfferComponents().
Referenced by com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onButtonClick().
finalize()
void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.finalize (ExchangeCompletionType type) protected
Finalizes the exchange session procedure for the specified player in a session.
Definition at line 304 of file ExchangeSession.java.
{
        final Optional<ExchangeSession> session = getSession(player);
        if (!session.isPresent() || session.get().finalized) {
            return;
        }
        session.get().finalized = true;
        switch (type) {
            case RESTORE:
                session.get().forEach(player -> {
                    ItemContainer items = item_containers.get(player);
                    items.forEach(player.inventory::add);
                    items.clear();
                });
                break;
            case DISPOSE:
                session.get().forEach(s -> item_containers.get(s).clear());
                break;
            case HALT:
                //nothing happens when halted, the session only gets finalized.
                break;
        }
        SESSIONS.remove(this);
        onReset();
    }
References getSession(), item_containers, onReset(), player, SESSIONS, and type.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept().
forEach()
void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach (Consumer< Player > action)
Executes the specified action for every player in this session.
Parameters
action the action to execute.
Definition at line 377 of file ExchangeSession.java.
{
        ImmutableSet.of(player, other).forEach(action);
    }
References other, and player.
Referenced by com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept(), ExchangeSession(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onRequest(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onRequest(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onReset(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onReset(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateMainComponents(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateMainComponents(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents().
getAttachment()
Object com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getAttachment ()
Retrieves the attachment object to this class.
Definition at line 242 of file ExchangeSession.java.
{
        return attachment;
    }
References attachment.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept().
getOther()
Player com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getOther (Player p)
Gets the other player in the exchange session.
Parameters
p the player you don't want to get.
Returns
the other player.
Definition at line 387 of file ExchangeSession.java.
{
        return p.getName().equals(player.getName()) ? this.other : this.player;
    }
References com.runehive.game.world.entity.mob.player.Player.getName(), and player.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept().
getSession() [1/4]
Optional< ExchangeSession > com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getSession (Player player) static
Gets the session if applicable the player is in.
Parameters
player the player to get the session for.
Returns
the session wrapped in an optional.
Definition at line 338 of file ExchangeSession.java.
{
        return SESSIONS.stream().filter(s -> anyMatch(s, player.getName())).findAny();
    }
References anyMatch(), player, and SESSIONS.
Referenced by com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.deposit(), com.runehive.game.task.impl.SessionRemovalNotificationTask.execute(), finalize(), inAnySession(), inSession(), request(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.reset(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.reset(), and com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.withdraw().
getSession() [2/4]
Optional< ExchangeSession > com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getSession (Player player, ExchangeSessionType type) static
Gets the session if applicable the player is in.
Parameters
player the player to get the session for.
Returns
the session wrapped in an optional.
Definition at line 348 of file ExchangeSession.java.
{
        return SESSIONS.stream().filter(s -> s.type.equals(type) && anyMatch(s, player.getName())).findAny();
    }
References anyMatch(), player, SESSIONS, and type.
getSession() [3/4]
Optional< ExchangeSession > com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getSession (Player player, Player other) static
Gets the session if applicable the player is in.
Parameters
player the player to get the session for.
Returns
the session wrapped in an optional.
Definition at line 358 of file ExchangeSession.java.
{
        return SESSIONS.stream().filter(s -> allMatch(s, player.getName(), other.getName())).findAny();
    }
References allMatch(), other, player, and SESSIONS.
getSession() [4/4]
Optional< ExchangeSession > com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getSession (Player player, Player other, ExchangeSessionType type) static
Gets the session if applicable the player is in.
Parameters
player the player to get the session for.
Returns
the session wrapped in an optional.
Definition at line 368 of file ExchangeSession.java.
{
        return SESSIONS.stream().filter(s -> allMatch(s, player.getName(), other.getName()) && s.type.equals(type)).findAny();
    }
References allMatch(), other, player, SESSIONS, and type.
hasAttachment()
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.hasAttachment ()
Determines if the trade stage has an attachment.
Definition at line 247 of file ExchangeSession.java.
{
        return Objects.nonNull(attachment);
    }
References attachment.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept().
inAnySession()
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.inAnySession ()
Determines if the player is any session.
Definition at line 262 of file ExchangeSession.java.
{
        return getSession(player).isPresent();
    }
References getSession(), and player.
Referenced by request().
inSession() [1/2]
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.inSession (Player player, ExchangeSessionType type) static
Determines if the player is a session which matches the type.
Definition at line 257 of file ExchangeSession.java.
{
        return getSession(player, type).isPresent();
    }
References getSession(), player, and type.
inSession() [2/2]
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.inSession (Player player, Player other, ExchangeSessionType type) static
Determines if the player is a session with other which matches the type.
Definition at line 252 of file ExchangeSession.java.
{
        return SESSIONS.stream().anyMatch(session -> allMatch(session, player.getName(), other.getName()) && session.type.equals(type));
    }
References allMatch(), other, player, SESSIONS, and type.
Referenced by add(), com.runehive.game.task.impl.DuelNotificationTask.execute(), and remove().
onButtonClick()
abstract boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.onButtonClick (Player player, int button) abstract
The method invoked when a button is clicked.
Reimplemented in com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession, and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.
References player.
onRequest()
abstract boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.onRequest () abstract
The method invoked when a player requests the other player.
Reimplemented in com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession, and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.
Referenced by request().
onReset()
abstract void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.onReset () abstract
Any functionality that should be handled when the itemcontainer closes.
Reimplemented in com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession, and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.
Referenced by finalize().
remove()
final boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove (Player player, int slot, int amount)
Attempts to withdraw an item from the container.
Definition at line 198 of file ExchangeSession.java.
{
        Item containerItem = this.item_containers.get(player).get(slot);
        if (player == null || containerItem == null) {
            return false;
        }
        if (!Item.valid(containerItem) || !this.item_containers.get(player).contains(containerItem.getId())) {
            return false;
        }
        if (!canOffer) {
            return false;
        }
        if (!inSession(player, type)) {
            return false;
        }
        if (!canRemoveItem(player, containerItem, slot)) {
            return false;
        }
        Item item = new Item(containerItem.getId(), amount == -1 ? this.item_containers.get(player).computeAmountForId(containerItem.getId()) : amount);
        int count = item_containers.get(player).computeAmountForId(item.getId());
        if (item.getAmount() > count) {
            item.setAmount(count);
        }
        if (item_containers.get(player).remove(item)) {
            player.inventory.add(item);
            item_containers.get(player).shift();
            if (this.player.equals(player)) {
                World.schedule(this.type == ExchangeSessionType.DUEL ? new DuelNotificationTask(other) : new SessionRemovalNotificationTask(other));
            } else if (player.equals(other)) {
                World.schedule(this.type == ExchangeSessionType.DUEL ? new DuelNotificationTask(this.player) : new SessionRemovalNotificationTask(this.player));
            }
            updateOfferComponents();
            return true;
        }
        return false;
    }
References canOffer, canRemoveItem(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.game.world.entity.mob.player.Player.equals(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), inSession(), item_containers, other, player, com.runehive.game.world.World.schedule(), com.runehive.game.world.items.Item.setAmount(), type, updateOfferComponents(), and com.runehive.game.world.items.Item.valid().
Referenced by com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.withdraw().
request()
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.request ()
Attempts to start an exchange session.
Definition at line 85 of file ExchangeSession.java.
{
        if (inAnySession()) {
            player.exchangeSession.reset();
            return false;
        }
      /*  if (PlayerRight.isAdministrator(player) && !PlayerRight.isOwner(player) || !PlayerRight.isDeveloper(player)) {
            player.message("You can not exchange as an administrator.");
            return false;
        }
        if (PlayerRight.isAdministrator(other) && !PlayerRight.isOwner(other) || !PlayerRight.isDeveloper(other)) {
            player.message("You can not exchange an administrator.");
            return false;
        }*/
        if (getSession(other).isPresent() && getSession(other).get().inAnySession()) {
            player.message("This player is currently is a " + type.name + " with another player.");
            return false;
        }
        if (Objects.equals(player, other)) {
            player.message("You cannot " + type.name + " with yourself.");
            return false;
        }
        if(player.getGambling().getStage().equals(GambleStage.PLACING_BET) || player.getGambling().getStage().equals(GambleStage.IN_PROGRESS)) {
            return false;
        }
        if(other.getGambling().getStage().equals(GambleStage.PLACING_BET) || other.getGambling().getStage().equals(GambleStage.IN_PROGRESS)) {
            return false;
        }
        if (PlayerRight.isIronman(player) && !PlayerRight.isOwner(other)) {
            player.message("You can not " + type.name + " as you are an iron man.");
            return false;
        }
        if (PlayerRight.isIronman(other) && !PlayerRight.isOwner(player)) {
            player.message(other.getName() + " can not be " + type.name + "d as they are an iron man.");
            return false;
        }
        if (player.exchangeSession.requested_players.contains(other)) {
            player.message("You have already sent a request to this player.");
            return false;
        }
        if (player.locking.locked()) {
            player.message("You cannot send a " + type.name + " request right now.");
            return false;
        }
        if (other.locking.locked()) {
            player.message(other.getName() + " is currently busy.");
            return false;
        }
        if (player.playerAssistant.busy()) {
            player.message("Please finish what you are doing before you do that.");
            return false;
        }
        if (other.playerAssistant.busy()) {
            player.message(other.getName() + " is currently busy.");
            return false;
        }
        if (player.inActivity(ActivityType.DUEL_ARENA)) {
            player.message("You can not do that whilst in a duel!");
            return false;
        }
        if (other.inActivity(ActivityType.DUEL_ARENA)) {
            other.message("You can not do that whilst in a duel!");
            return false;
        }
        if (!onRequest()) {
            return false;
        }
        if(this.type == ExchangeSessionType.DUEL && !other.getPosition().inLocation(new Position(3311, 3201), new Position(3394, 3287), true)) {
            player.exchangeSession.reset();
            return false;
        }
        return SESSIONS.add(this);
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.content.activity.ActivityType.DUEL_ARENA, getSession(), com.runehive.content.gambling.GambleStage.IN_PROGRESS, inAnySession(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.game.world.entity.mob.player.PlayerRight.isOwner(), onRequest(), other, com.runehive.content.gambling.GambleStage.PLACING_BET, player, SESSIONS, and type.
Referenced by com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.request().
setAttachment()
void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.setAttachment (Object attachment)
Assigns an attachment to this stage object.
Definition at line 237 of file ExchangeSession.java.
{
        this.attachment = attachment;
    }
References attachment.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents().
updateMainComponents()
abstract void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.updateMainComponents (String component) abstract
Updates the main components of the itemcontainer.
Reimplemented in com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession, and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.
updateOfferComponents()
abstract void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.updateOfferComponents () abstract
Updates the itemcontainer when an item is offered or removed.
Reimplemented in com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession, and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.
Referenced by add(), depositeAll(), remove(), and withdrawAll().
withdrawAll()
void com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.withdrawAll (Player player) protected
Withdraws all items from the exchange session.
Definition at line 291 of file ExchangeSession.java.
{
        ItemContainer container = this.item_containers.get(player);
        if (container.isEmpty()) {
            player.message("There is nothing in this container to withdraw!");
            return;
        }
        player.inventory.addAll(container);
        container.clear();
        updateOfferComponents();
    }
References com.runehive.game.world.items.containers.ItemContainer.clear(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.containers.ItemContainer.isEmpty(), player, and updateOfferComponents().
Referenced by com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onButtonClick().
Member Data Documentation
attachment
Object com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.attachment private
The attachment to the session stage, this will more than likely be a player object that will be attached when they have confirmed a certain stage.
Definition at line 44 of file ExchangeSession.java.
Referenced by getAttachment(), hasAttachment(), and setAttachment().
canOffer
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.canOffer = true
Determines if the player can offer or withdraw items.
Definition at line 55 of file ExchangeSession.java.
Referenced by add(), and remove().
finalized
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.finalized
Determines if this exchange has been finalized.
Definition at line 58 of file ExchangeSession.java.
item_containers
final Map<Player, ItemContainer> com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.item_containers = new HashMap<>()
The items which are in this exchange session.
Definition at line 38 of file ExchangeSession.java.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept(), add(), ExchangeSession(), finalize(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.getItemNames(), remove(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateMainComponents(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateMainComponents(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents().
other
final Player com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other
The other player in this session.
Definition at line 32 of file ExchangeSession.java.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept(), allMatch(), anyMatch(), ExchangeSession(), forEach(), getSession(), getSession(), inSession(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onButtonClick(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onRequest(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onRequest(), remove(), request(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.StakeSession(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.TradeSession(), and com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents().
player
final Player com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player
The controller of this session.
Definition at line 29 of file ExchangeSession.java.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), accept(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept(), add(), allMatch(), anyMatch(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.canAddItem(), canAddItem(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.canAddItem(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.canRemoveItem(), canRemoveItem(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.canRemoveItem(), depositeAll(), ExchangeSession(), finalize(), forEach(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.getItemNames(), getOther(), getSession(), getSession(), getSession(), getSession(), inAnySession(), inSession(), inSession(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onButtonClick(), onButtonClick(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onButtonClick(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onRequest(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onRequest(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onReset(), remove(), request(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.TradeSession(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateMainComponents(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateMainComponents(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents(), and withdrawAll().
SESSIONS
final Set<ExchangeSession> com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.SESSIONS = new HashSet<>() static
The collection of sessions.
Definition at line 26 of file ExchangeSession.java.
Referenced by finalize(), getSession(), getSession(), getSession(), getSession(), inSession(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onRequest(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onRequest(), request(), and com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.reset().
type
final ExchangeSessionType com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.type
The type of this exchange session.
Definition at line 35 of file ExchangeSession.java.
Referenced by add(), ExchangeSession(), finalize(), getSession(), getSession(), inSession(), inSession(), remove(), and request().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/exchange/ExchangeSession.java