RuneHive-Game: com.runehive.content.shootingstar.ShootingStarAction Class Reference
com.runehive.content.shootingstar.ShootingStarAction Class Reference
Public Member Functions
String getName ()
Gets the name of this action.
WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
ShootingStarAction (Player player, PickaxeData pickaxe, GameObject object)
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
boolean prioritized ()
Determines if this action is prioritized.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Protected Member Functions
boolean canSchedule ()
A function executed on registration.
void execute ()
A function representing the unit of work that will be carried out.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
Private Member Functions
boolean mine ()
Private Attributes
GameObject object
PickaxeData pickaxe
Additional Inherited Members
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
Definition at line 12 of file ShootingStarAction.java.
Constructor & Destructor Documentation
ShootingStarAction()
com.runehive.content.shootingstar.ShootingStarAction.ShootingStarAction (Player player, PickaxeData pickaxe, GameObject object)
Definition at line 17 of file ShootingStarAction.java.
{
        super(player, 3, false);
        this.pickaxe = pickaxe;
        this.object = object;
    }
References object, and pickaxe.
Member Function Documentation
canSchedule()
boolean com.runehive.content.shootingstar.ShootingStarAction.canSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 34 of file ShootingStarAction.java.
{
        return !getMob().skills.get(Skill.MINING).isDoingSkill();
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), and com.runehive.game.world.entity.skill.Skill.MINING.
execute()
void com.runehive.content.shootingstar.ShootingStarAction.execute () protected
A function representing the unit of work that will be carried out.
Reimplemented from com.runehive.game.task.Task.
Definition at line 50 of file ShootingStarAction.java.
{
        if (!getMob().skills.get(Skill.MINING).isDoingSkill()) {
            cancel();
            return;
        }
        if (!mine()) {
            cancel();
        }
    }
References com.runehive.game.task.Task.cancel(), com.runehive.game.action.Action< T extends Mob >.getMob(), mine(), and com.runehive.game.world.entity.skill.Skill.MINING.
getName()
String com.runehive.content.shootingstar.ShootingStarAction.getName ()
Gets the name of this action.
Returns
The name of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 29 of file ShootingStarAction.java.
{
        return "shooting-star-action";
    }
getWalkablePolicy()
WalkablePolicy com.runehive.content.shootingstar.ShootingStarAction.getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 24 of file ShootingStarAction.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
mine()
boolean com.runehive.content.shootingstar.ShootingStarAction.mine () private
Definition at line 61 of file ShootingStarAction.java.
{
        if (!getMob().inventory.hasCapacityFor(new Item(25527))) {
            getMob().dialogueFactory.sendStatement("You can't carry anymore star dust.").execute();
            return false;
        }
        getMob().animate(pickaxe.animation);
        if (Mining.success(getMob(), ShootingStar.shootingStarData.getMiningLevel(), pickaxe)) {
            if (object == null || !object.active()) {
                return false;
            }
            if (ShootingStar.shootingStarData.availableDust <= 0) {
                getMob().resetAnimation();
                return false;
            }
            ShootingStar.shootingStarData.decreaseDust(getMob());
        }
        return true;
    }
References com.runehive.content.shootingstar.ShootingStarData.availableDust, com.runehive.content.shootingstar.ShootingStarData.decreaseDust(), com.runehive.content.shootingstar.ShootingStarData.getMiningLevel(), com.runehive.game.action.Action< T extends Mob >.getMob(), pickaxe, com.runehive.content.shootingstar.ShootingStar.shootingStarData, and com.runehive.content.skill.impl.mining.Mining.success().
Referenced by execute().
onCancel()
void com.runehive.content.shootingstar.ShootingStarAction.onCancel (boolean logout) protected
A function executed on cancellation.
Reimplemented from com.runehive.game.task.Task.
Definition at line 44 of file ShootingStarAction.java.
{
        getMob().resetFace();
        getMob().skills.get(Skill.MINING).setDoingSkill(false);
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), and com.runehive.game.world.entity.skill.Skill.MINING.
onSchedule()
void com.runehive.content.shootingstar.ShootingStarAction.onSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 39 of file ShootingStarAction.java.
{
        getMob().animate(pickaxe.animation);
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), and pickaxe.
Member Data Documentation
object
GameObject com.runehive.content.shootingstar.ShootingStarAction.object private
Definition at line 15 of file ShootingStarAction.java.
Referenced by ShootingStarAction().
pickaxe
PickaxeData com.runehive.content.shootingstar.ShootingStarAction.pickaxe private
Definition at line 14 of file ShootingStarAction.java.
Referenced by mine(), onSchedule(), and ShootingStarAction().
The documentation for this class was generated from the following file:
java/com/runehive/content/shootingstar/ShootingStarAction.java