RuneHive-Game: com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E > Class Template Reference
com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E > Class Template Reference
Public Member Functions
WeightedCollection< E > add (double weight, E result)
double getTotal ()
E next ()
WeightedCollection ()
WeightedCollection (Random random)
Private Attributes
final NavigableMap< Double, E > map = new TreeMap<>()
final Random random
double total = 0
Detailed Description
Definition at line 7 of file WeightedCollection.java.
Constructor & Destructor Documentation
WeightedCollection() [1/2]
com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.WeightedCollection ()
Definition at line 16 of file WeightedCollection.java.
{
        this(new Random());
    }
Referenced by add().
WeightedCollection() [2/2]
com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.WeightedCollection (Random random)
Definition at line 20 of file WeightedCollection.java.
{
        this.random = random;
    }
References random.
Member Function Documentation
add()
WeightedCollection< E > com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.add (double weight, E result)
Definition at line 24 of file WeightedCollection.java.
{
        if (weight <= 0) return this;
        total += weight;
        map.put(total, result);
        return this;
    }
References map, total, and WeightedCollection().
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop().
getTotal()
double com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.getTotal ()
Definition at line 12 of file WeightedCollection.java.
{
        return total;
    }
References total.
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop().
next()
E com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.next ()
Definition at line 31 of file WeightedCollection.java.
                    {
        double value = random.nextDouble() * total;
        return map.higherEntry(value).getValue();
    }
References map, random, and total.
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop().
Member Data Documentation
map
final NavigableMap<Double, E> com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.map = new TreeMap<>() private
Definition at line 8 of file WeightedCollection.java.
Referenced by add(), and next().
random
final Random com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.random private
Definition at line 9 of file WeightedCollection.java.
Referenced by next(), and WeightedCollection().
total
double com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.total = 0 private
Definition at line 10 of file WeightedCollection.java.
Referenced by add(), getTotal(), and next().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/npc/drop/WeightedCollection.java