RuneHive-Game: com.runehive.content.skill.guides.SkillGuides Class Reference
com.runehive.content.skill.guides.SkillGuides Class Reference
Static Public Member Functions
static void openInterface (Player player, int skillId, int optionId, boolean update)
Static Public Attributes
static final int INTERFACE_ID = 42550
Static Private Member Functions
static void cleanInterface (Player player, int menuLength, int start)
Static Private Attributes
static final int CATEGORY_ID = 42558
static final int ITEMS_ID = 42574
static final int RIGHT_OPTIONS_START = 42559
static final int SCROLL_LAYER = 42573
static final int TEXT_LAYER_START = 42575
static final int TITLE_ID = 42557
Detailed Description
Definition at line 11 of file SkillGuides.java.
Member Function Documentation
cleanInterface()
void com.runehive.content.skill.guides.SkillGuides.cleanInterface (Player player, int menuLength, int start) static private
Cleans the right side
Definition at line 63 of file SkillGuides.java.
{
        /**
         * Cleans the right side
         */
        for(int index = menuLength; index < 14; index++) {
            System.out.println("RIGHT_OPTIONS_START + index: " + (RIGHT_OPTIONS_START + index));
            player.send(new SendString("", RIGHT_OPTIONS_START + index));
        }
        //for(int index = 2, child = RIGHT_OPTIONS_START + menuLength; index < 12; index++, child++)
        //    player.send(new SendString("", child));
        if(start < 7) {
            for (int index = 0, id = TEXT_LAYER_START + (2 * start); index < 7; index++, id += 2) {
                player.send(new SendString("", id));
                player.send(new SendString("", id + 1));
            }
        }
        /*for(int index = 0, id = TEXT_LAYER_START + (2 * length) + 1; index < 7; index++, id += 2) {
            player.send(new SendString("", id));
            player.send(new SendString("", id + 1));
        }*/
    }
References RIGHT_OPTIONS_START, com.runehive.game.world.entity.mob.player.Player.send(), and TEXT_LAYER_START.
Referenced by openInterface().
openInterface()
void com.runehive.content.skill.guides.SkillGuides.openInterface (Player player, int skillId, int optionId, boolean update) static
Definition at line 22 of file SkillGuides.java.
{
        if(player.menuOpened == skillId && player.optionOpened == optionId) return;
        GuideData data = GuideData.values()[skillId];
        player.send(new SendString(Utility.capitalizeSentence(data.name().toLowerCase()), TITLE_ID));
        player.send(new SendString(data.options[optionId], CATEGORY_ID));
        int menuLength = data.options.length, length = data.menus[optionId].option.length;
        for(int index = 0; index < menuLength; index++)
            player.send(new SendString(data.options[index], RIGHT_OPTIONS_START + index));
        Item[] items = new Item[length];
        for(int i = 0; i < length; i++)
            items[i] = new Item(data.menus[optionId].option[i].itemId);
        for(int i = 0, id = TEXT_LAYER_START; i < length; i++, id += 2) {
            String level = data.menus[optionId].option[i].level == -1 ? "" : data.menus[optionId].option[i].level + "";
            System.out.println("id: " + id);
            System.out.println("level: " + level);
            System.out.println("data.menus[optionId].option[i].name: " + data.menus[optionId].option[i].name);
            player.send(new SendString(data.menus[optionId].option[i].name, id));
            player.send(new SendString(level, id + 1));
        }
        player.send(new SendItemOnInterface(ITEMS_ID, items));
        cleanInterface(player, menuLength, length);
        int scrollMax = 1;
        if(length == 58) scrollMax = ((length + 3) * 33) + 1;
        else if(length >= 7) scrollMax = (length * 33) + 1;
        player.send(new SendScrollbar(SCROLL_LAYER, scrollMax));
        player.menuOpened = skillId;
        player.optionOpened = optionId;
        if(!update) player.send(new SendInterface(INTERFACE_ID));
    }
References com.runehive.util.Utility.capitalizeSentence(), CATEGORY_ID, cleanInterface(), INTERFACE_ID, com.runehive.content.skill.guides.MenuOption.Option.itemId, ITEMS_ID, com.runehive.content.skill.guides.MenuOption.Option.level, com.runehive.game.world.entity.mob.player.Player.menuOpened, com.runehive.content.skill.guides.GuideData.menus, com.runehive.content.skill.guides.MenuOption.Option.name, com.runehive.content.skill.guides.MenuOption.option, com.runehive.game.world.entity.mob.player.Player.optionOpened, com.runehive.content.skill.guides.GuideData.options, RIGHT_OPTIONS_START, SCROLL_LAYER, com.runehive.game.world.entity.mob.player.Player.send(), TEXT_LAYER_START, and TITLE_ID.
Member Data Documentation
CATEGORY_ID
final int com.runehive.content.skill.guides.SkillGuides.CATEGORY_ID = 42558 static private
Definition at line 15 of file SkillGuides.java.
Referenced by openInterface().
INTERFACE_ID
final int com.runehive.content.skill.guides.SkillGuides.INTERFACE_ID = 42550 static
Definition at line 13 of file SkillGuides.java.
Referenced by openInterface().
ITEMS_ID
final int com.runehive.content.skill.guides.SkillGuides.ITEMS_ID = 42574 static private
Definition at line 18 of file SkillGuides.java.
Referenced by openInterface().
RIGHT_OPTIONS_START
final int com.runehive.content.skill.guides.SkillGuides.RIGHT_OPTIONS_START = 42559 static private
Definition at line 16 of file SkillGuides.java.
Referenced by cleanInterface(), and openInterface().
SCROLL_LAYER
final int com.runehive.content.skill.guides.SkillGuides.SCROLL_LAYER = 42573 static private
Definition at line 17 of file SkillGuides.java.
Referenced by openInterface().
TEXT_LAYER_START
final int com.runehive.content.skill.guides.SkillGuides.TEXT_LAYER_START = 42575 static private
Definition at line 19 of file SkillGuides.java.
Referenced by cleanInterface(), and openInterface().
TITLE_ID
final int com.runehive.content.skill.guides.SkillGuides.TITLE_ID = 42557 static private
Definition at line 14 of file SkillGuides.java.
Referenced by openInterface().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/guides/SkillGuides.java