RuneHive-Game: dev.advo.fs.dispatch.ChannelRequest< T > Class Template Reference
dev.advo.fs.dispatch.ChannelRequest< T > Class Template Reference
A specialised request which contains a channel as well as the request object itself.
Public Member Functions
ChannelRequest (Channel channel, T request)
Creates a new channel request.
int compareTo (ChannelRequest< T > o)
Channel getChannel ()
Gets the channel.
T getRequest ()
Gets the request.
Private Attributes
final Channel channel
The channel.
final T request
The request.
Detailed Description
A specialised request which contains a channel as well as the request object itself.
Author
Graham
Parameters
<T> The type of request.
Definition at line 11 of file ChannelRequest.java.
Constructor & Destructor Documentation
ChannelRequest()
dev.advo.fs.dispatch.ChannelRequest< T >.ChannelRequest (Channel channel, T request)
Creates a new channel request.
Parameters
channel The channel.
request The request.
Definition at line 28 of file ChannelRequest.java.
{
        this.channel = channel;
        this.request = request;
    }
References channel, and request.
Referenced by compareTo().
Member Function Documentation
compareTo()
int dev.advo.fs.dispatch.ChannelRequest< T >.compareTo (ChannelRequest< T > o)
Definition at line 51 of file ChannelRequest.java.
{
        if (request instanceof Comparable<?> && o.request instanceof Comparable<?>) {
            return ((Comparable<T>) request).compareTo(o.request);
        }
        return 0;
    }
References ChannelRequest(), and request.
getChannel()
Channel dev.advo.fs.dispatch.ChannelRequest< T >.getChannel ()
Gets the channel.
Returns
The channel.
Definition at line 37 of file ChannelRequest.java.
{
        return channel;
    }
References channel.
Referenced by dev.advo.fs.dispatch.OnDemandRequestWorker.run().
getRequest()
T dev.advo.fs.dispatch.ChannelRequest< T >.getRequest ()
Gets the request.
Returns
The request.
Definition at line 45 of file ChannelRequest.java.
{
        return request;
    }
References request.
Referenced by dev.advo.fs.dispatch.OnDemandRequestWorker.run().
Member Data Documentation
channel
final Channel dev.advo.fs.dispatch.ChannelRequest< T >.channel private
The channel.
Definition at line 16 of file ChannelRequest.java.
Referenced by ChannelRequest(), and getChannel().
request
final T dev.advo.fs.dispatch.ChannelRequest< T >.request private
The request.
Definition at line 21 of file ChannelRequest.java.
Referenced by ChannelRequest(), compareTo(), and getRequest().
The documentation for this class was generated from the following file:
java/dev/advo/fs/dispatch/ChannelRequest.java