RuneHive-Game: com.runehive.util.Utility Class Reference
com.runehive.util.Utility Class Reference
Handles miscellaneous methods.
Static Public Member Functions
static String bigDaddyTime (long period)
static String capitalizeSentence (final String string)
Capitalize each letter after .
static boolean checkRequirements (Player player, int[] requirements, String action)
static String convertWord (int amount)
Converts an integer into words.
static Position findAccessableTile (Interactable source)
static Position findBestInside (Interactable source, Interactable target)
static void fixInsidePosition (Mob source, Interactable target)
static String formatDigits (final double amount)
Formats digits for doubles.
static String formatDigits (final int amount)
Formats digits for integers.
static String formatDigits (final long amount)
Formats digits for longs.
static String formatEnum (final String string)
Formats name of enum.
static String formatName (final String input)
static String formatPrice (final long amount)
Formats a price for longs.
static String formatText (String s)
static String getAOrAn (String nextWord)
A or an.
static Position[] getBoundaries (Interactable interactable)
static List< Object > getClassesInDirectory (String directory)
Gets all of the classes in a directory.
static int getCurrentDay ()
static String getDate ()
Gets the date of server.
static Position getDelta (Interactable source, Interactable target)
static Position getDelta (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength)
static Position getDelta (Position source, Position target)
static int getDistance (Interactable source, Interactable target)
static int getDistance (Interactable source, Position target)
static int getDistance (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength)
static Position[] getInnerBoundaries (Interactable interactable)
static Position[] getInnerBoundaries (Position position, int width, int length)
static double getPercentageAmount (int progress, int total)
Gets a percentage amount.
static String getSimpleDate ()
Gets the date of server.
static int getStarters (String host)
static List< String > getSubDirectories (Class<?> clazz)
Gets all of the sub directories of a folder.
static String getTime ()
Gets the current server time and formats it.
static String getTime (int ticks)
Gets a basic time based off seconds.
static String getTime (long period)
Gets the time based off a long.
static String getUptime ()
Gets the current uptime of server and formats it.
static final boolean goodDistance (int objectX, int objectY, int playerX, int playerY, int distance)
static long hash (String input)
static boolean hasOneOutOf (double chance)
static boolean inRange (int absX, int absY, int size, int targetX, int targetY, int targetSize, int distance)
static boolean inRange (Interactable source, Interactable target, int distance)
static boolean inside (Interactable source, Interactable target)
static boolean inside (Interactable source, Position target)
static boolean inside (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength)
static boolean isLarger (Interactable source, Interactable other)
static boolean isRegionChange (Position position, Position region)
static String longToString (long l)
static int min (int... values)
static long nameToLong (String text)
Converts the first 12 characters in a string of text to a hash.
static int random (int bound)
static int random (int lowerBound, int upperBound)
static int random (int lowerBound, int upperBound, boolean inclusive)
static< T > T randomElement (Collection< T > collection)
Picks a random element out of any array type.
static int randomElement (int[] array)
Picks a random element out of any array type.
static< T > T randomElement (List< T > list)
Picks a random element out of any list type.
static< T > T randomElement (T[] array)
Picks a random element out of any array type.
static String rank (final String string)
Formats the player name.
static boolean setStarter (Player player)
static int[] shuffleArray (int[] array)
static long stringToLong (String string)
static boolean within (Interactable source, Interactable target, int distance)
static boolean within (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength, int distance)
static boolean within (Position source, Position target, int distance)
static boolean withinDistance (Interactable source, Interactable target, int radius)
static boolean withinDistance (Interactable source, Position target, int radius)
static boolean withinOctal (Interactable source, Interactable target, int distance)
static boolean withinOctal (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength, int distance)
static boolean withinViewingDistance (Interactable source, Interactable target, int radius)
Static Private Attributes
static final Random RANDOM = new Random(System.currentTimeMillis())
Random instance, used to generate pseudo-random primitive types.
static final char[] VALID_CHARS = {'_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '/'}
Array of all valid characters.
Detailed Description
Handles miscellaneous methods.
Author
Daniel
Definition at line 27 of file Utility.java.
Member Function Documentation
bigDaddyTime()
String com.runehive.util.Utility.bigDaddyTime (long period) static
Definition at line 150 of file Utility.java.
{
        return new SimpleDateFormat("HH:mm:ss").format(period);
    }
capitalizeSentence()
String com.runehive.util.Utility.capitalizeSentence (final String string) static
Capitalize each letter after .
Definition at line 99 of file Utility.java.
{
        int pos = 0;
        boolean capitalize = true;
        StringBuilder sb = new StringBuilder(string);
        while (pos < sb.length()) {
            if (sb.charAt(pos) == '.') {
                capitalize = true;
            } else if (capitalize && !Character.isWhitespace(sb.charAt(pos))) {
                sb.setCharAt(pos, Character.toUpperCase(sb.charAt(pos)));
                capitalize = false;
            }
            pos++;
        }
        return sb.toString();
    }
Referenced by com.runehive.util.tools.wiki.impl.ItemDefParser.format(), formatEnum(), com.runehive.content.skill.guides.SkillGuides.openInterface(), com.runehive.game.world.World.sendBroadcast(), com.runehive.content.gambling.GambleManager.sendRequest(), com.runehive.game.world.entity.skill.SkillData.toString(), and com.runehive.content.Yell.yell().
checkRequirements()
boolean com.runehive.util.Utility.checkRequirements (Player player, int[] requirements, String action) static
Definition at line 807 of file Utility.java.
{
        boolean can = true;
        for (int index = 0; index < requirements.length; index++) {
            int level = player.skills.getMaxLevel(index);
            int required = requirements[index];
            if (level < required) {
                player.send(new SendMessage("You need a level of " + required + " " + Skill.getName(index) + " to " + action));
                can = false;
            }
        }
        return can;
    }
References com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.skill.Skill.getName(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.equip().
convertWord()
String com.runehive.util.Utility.convertWord (int amount) static
Converts an integer into words.
Definition at line 136 of file Utility.java.
{
        return Words.getInstance(amount).getNumberInWords();
    }
References com.runehive.util.Words.getInstance(), and com.runehive.util.Words.getNumberInWords().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.useROW().
findAccessableTile()
Position com.runehive.util.Utility.findAccessableTile (Interactable source) static
Definition at line 478 of file Utility.java.
{
        Position found = null;
        Position[] positions = getBoundaries(source);
        for (Position next : positions) {
            Direction direction = Direction.getDirection(source.getPosition(), next);
            if (inside(next, 0, 0, source.getPosition(), source.width(), source.length())) {
                continue;
            }
            if (TraversalMap.isTraversable(next, direction, false)) {
                found = next;
                break;
            }
        }
        return found;
    }
References getBoundaries(), com.runehive.game.world.entity.mob.Direction.getDirection(), com.runehive.game.world.Interactable.getPosition(), inside(), com.runehive.game.world.pathfinding.TraversalMap.isTraversable(), com.runehive.game.world.Interactable.length(), and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.content.pet.Pets.onObtain(), and com.runehive.content.pet.Pets.onSpawn().
findBestInside()
Position com.runehive.util.Utility.findBestInside (Interactable source, Interactable target) static
Definition at line 498 of file Utility.java.
{
        if (target.width() <= 1 || target.length() <= 1) {
            return target.getPosition();
        }
        int dx, dy, dist = Integer.MAX_VALUE;
        Position best = source.getPosition();
        for (int x = 0; x < target.width(); x++) {
            Position boundary = target.getPosition().transform(x, 0);
            int distance = getDistance(source, boundary);
            if (dist > distance) {
                dist = distance;
                best = boundary;
            }
            boundary = target.getPosition().transform(x, target.length() - 1);
            distance = getDistance(source, boundary);
            if (dist > distance) {
                dist = distance;
                best = boundary;
            }
        }
        for (int y = 0; y < target.length(); y++) {
            Position boundary = target.getPosition().transform(0, y);
            int distance = getDistance(source, boundary);
            if (dist > distance) {
                dist = distance;
                best = boundary;
            }
            boundary = target.getPosition().transform(target.width() - 1, y);
            distance = getDistance(source, boundary);
            if (dist > distance) {
                dist = distance;
                best = boundary;
            }
        }
        if (best.equals(source.getPosition())) {
            return source.getPosition();
        }
        Direction direction = Direction.getDirection(source.getPosition(), best);
        Position sourceTopRight = source.getPosition().transform(source.width() - 1, source.length() - 1, 0);
        if (source.getX() > best.getX()) {
            dx = best.getX() - source.getX();
        } else if (sourceTopRight.getX() < best.getX()) {
            dx = best.getX() - sourceTopRight.getX();
        } else {
            dx = direction.getDirectionX();
        }
        if (source.getY() > best.getY()) {
            dy = best.getY() - source.getY();
        } else if (sourceTopRight.getY() < best.getY()) {
            dy = best.getY() - sourceTopRight.getY();
        } else {
            dy = direction.getDirectionY();
        }
        return source.getPosition().transform(dx, dy);
    }
References com.runehive.game.world.position.Position.equals(), com.runehive.game.world.entity.mob.Direction.getDirection(), com.runehive.game.world.entity.mob.Direction.getDirectionX(), com.runehive.game.world.entity.mob.Direction.getDirectionY(), getDistance(), com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.getX(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.Interactable.getY(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.Interactable.length(), com.runehive.game.world.position.Position.transform(), and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), com.runehive.game.world.pathfinding.path.SimplePathChecker.checkLine(), com.runehive.game.world.pathfinding.path.SimplePathChecker.checkProjectile(), com.runehive.game.world.pathfinding.path.impl.DijkstraPathFinder.find(), com.runehive.game.world.entity.mob.movement.waypoint.WalkToWaypoint.onDestination(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start().
fixInsidePosition()
void com.runehive.util.Utility.fixInsidePosition (Mob source, Interactable target) static
Definition at line 567 of file Utility.java.
{
        if (source.movement.needsPlacement()) return;
        List<Position> boundaries = new LinkedList<>();
        Map<Position, LinkedList<Position>> paths = new HashMap<>();
        Position cur = source.getPosition();
        for (Position position : getBoundaries(target)) {
            Position delta = getDelta(target.getPosition(), position);
            int dx = Integer.signum(delta.getX()), dy = Integer.signum(delta.getY());
            Direction direction = Direction.getDirection(dx, dy);
            if (direction == Direction.NONE)
                continue;
            while (inside(cur, source.width(), source.length(), target.getPosition(), target.width(), target.length())) {
                if (!TraversalMap.isTraversable(cur, direction, source.width())) {
                    break;
                }
                cur = cur.transform(direction.getFaceLocation());
                LinkedList<Position> list = paths.computeIfAbsent(position, pos -> {
                    boundaries.add(position);
                    return new LinkedList<>();
                });
                list.add(cur);
                paths.put(position, list);
            }
        }
        if (boundaries.isEmpty()) return;
        source.setFixingInside(true);
        Position random = boundaries.get(0);//RandomUtils.random(boundaries);
        source.movement.addPath(new Path(paths.get(random)));
    }
References com.runehive.game.world.entity.mob.movement.Movement.addPath(), getBoundaries(), getDelta(), com.runehive.game.world.entity.mob.Direction.getDirection(), com.runehive.game.world.entity.mob.Direction.getFaceLocation(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), inside(), com.runehive.game.world.pathfinding.TraversalMap.isTraversable(), com.runehive.game.world.entity.Entity.length, com.runehive.game.world.Interactable.length(), com.runehive.game.world.entity.mob.Mob.movement, com.runehive.game.world.entity.mob.movement.Movement.needsPlacement(), com.runehive.game.world.entity.mob.Direction.NONE, random(), com.runehive.game.world.entity.mob.Mob.setFixingInside(), com.runehive.game.world.position.Position.transform(), com.runehive.game.world.entity.Entity.width, and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.execute().
formatDigits() [1/3]
String com.runehive.util.Utility.formatDigits (final double amount) static
Formats digits for doubles.
Definition at line 51 of file Utility.java.
{
        return NumberFormat.getInstance().format(amount);
    }
formatDigits() [2/3]
String com.runehive.util.Utility.formatDigits (final int amount) static
Formats digits for integers.
Definition at line 41 of file Utility.java.
{
        return NumberFormat.getInstance().format(amount);
    }
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateAchievement(), com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.content.clanchannel.channel.ClanChannel.activateTask(), com.runehive.game.world.items.containers.bank.BankVault.add(), com.runehive.content.clanchannel.channel.ClanChannel.addExperience(), com.runehive.content.combat.Killstreak.announce(), com.runehive.content.triviabot.TriviaBot.answered(), com.runehive.content.tradingpost.TradingPost.buyingDialogueOptions(), com.runehive.content.pet.Pets.buyInsurance(), com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), com.runehive.content.itemaction.impl.CelestialRing.check(), com.runehive.content.itemaction.impl.CrawsBow.check(), com.runehive.content.itemaction.impl.ThammaronsSceptre.check(), com.runehive.content.itemaction.impl.TridentOfTheSeas.check(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.check(), com.runehive.content.itemaction.impl.ViggorasChainmace.check(), com.runehive.content.pet.Pets.claimLostPets(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.content.skill.impl.magic.RunePouch.deposit(), com.runehive.game.world.items.containers.bank.BankVault.deposit(), com.runehive.content.DropDisplay.display(), com.runehive.content.skill.impl.construction.BuildableInterface.display(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.combat.Killstreak.end(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.clanchannel.content.ClanViewer.getDetails(), com.runehive.content.clanchannel.content.ClanViewer.getProfile(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMessages(), com.runehive.content.itemaction.impl.ToxicBlowpipe.load(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.game.world.items.containers.impl.LootingBag.onRefresh(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.onRefresh(), com.runehive.content.ActivityLogger.open(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.WellOfGoodwill.open(), com.runehive.game.world.items.containers.bank.BankVault.open(), com.runehive.content.pet.Pets.openInsurance(), com.runehive.game.world.items.containers.equipment.Equipment.openInterface(), com.runehive.content.pet.Pets.openLostPets(), com.runehive.content.store.impl.PersonalStore.openMenu(), com.runehive.content.donators.Donation.redeem(), com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.reward(), com.runehive.content.combat.Killstreak.reward(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.search(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.searchItem(), com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues(), com.runehive.content.tradingpost.TradingPost.sendItemHistoryData(), com.runehive.content.store.Store.sendPurchaseValue(), com.runehive.content.store.Store.sendSellValue(), com.runehive.content.clanchannel.channel.ClanChannel.splitLoot(), com.runehive.content.skill.impl.slayer.Slayer.store(), com.runehive.content.ProfileViewer.string(), com.runehive.content.itemaction.impl.MagmaHelm.uncharge(), com.runehive.content.itemaction.impl.SerpentineHelm.uncharge(), com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge(), com.runehive.content.activity.impl.fightcaves.FightCaves.update(), com.runehive.content.activity.inferno.Inferno.update(), com.runehive.content.tradingpost.TradingPost.updateBuyingPageWidgets(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents(), com.runehive.content.tradingpost.TradingPost.updatePriceStrings(), com.runehive.game.world.items.containers.bank.BankVault.value(), and com.runehive.game.world.items.containers.bank.BankVault.withdraw().
formatDigits() [3/3]
String com.runehive.util.Utility.formatDigits (final long amount) static
Formats digits for longs.
Definition at line 46 of file Utility.java.
{
        return NumberFormat.getInstance().format(amount);
    }
formatEnum()
String com.runehive.util.Utility.formatEnum (final String string) static
Formats name of enum.
Definition at line 89 of file Utility.java.
{
        return capitalizeSentence(string.toLowerCase().replace("_", " "));
    }
References capitalizeSentence().
Referenced by com.runehive.content.ActivityLogger.add(), com.runehive.content.clanchannel.channel.ClanChannel.addExperience(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel(), com.runehive.content.skill.impl.mining.Mining.clickObject(), com.runehive.content.simulator.DropSimulator.drawList(), com.runehive.content.clanchannel.content.ClanViewer.getDetails(), com.runehive.content.ActivityLogger.open(), com.runehive.content.skill.impl.crafting.impl.Tanning.open(), com.runehive.content.donators.Donation.redeem(), com.runehive.content.activity.record.PlayerRecord.showActivities(), com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.toString(), com.runehive.content.emote.EmoteHandler.unlock(), and com.runehive.content.clanchannel.content.ClanViewer.viewAchievements().
formatName()
String com.runehive.util.Utility.formatName (final String input) static
Definition at line 645 of file Utility.java.
{
        if(input == null) {
            return null;
        }
        //Open chagpt
        StringBuilder formattedName = new StringBuilder();
        // Split the input string by spaces
        String[] words = input.trim().split(" ");
        // Capitalize the first letter of each word
        for (String word : words) {
            if (!word.isEmpty()) {
                // Capitalize the first letter
                char firstLetter = Character.toUpperCase(word.charAt(0));
                formattedName.append(firstLetter);
                // Append the remaining letters
                if (word.length() > 1) {
                    formattedName.append(word.substring(1));
                }
                // Append a space
                formattedName.append(" ");
            }
        }
        // Remove the trailing space and return the formatted name
        return formattedName.toString().trim();
    }
Referenced by com.runehive.game.world.entity.mob.player.relations.PlayerRelation.addFriend(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.addIgnore(), com.runehive.content.dialogue.DialogueFactory.appendKeywords(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.content.store.impl.PersonalStore.changeName(), com.runehive.content.clanchannel.channel.ClanChannelHandler.connected(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteFriend(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteIgnore(), com.runehive.content.activity.record.PlayerRecord.display(), com.runehive.content.skill.impl.construction.House.enter(), com.runehive.content.clanchannel.content.ClanViewer.getDetails(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.content.clanchannel.content.ClanViewer.open(), com.runehive.content.tittle.TitleManager.refresh(), com.runehive.game.world.entity.mob.player.Player.register(), com.runehive.game.world.entity.mob.player.requests.RequestManager.request(), com.runehive.content.famehall.FameHandler.search(), com.runehive.content.dialogue.DialogueFactory.sendPlayerChat(), com.runehive.content.clanchannel.channel.ClanChannel.setName(), com.runehive.content.clanchannel.channel.ClanChannel.setSlogan(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateMainComponents(), com.runehive.content.clanchannel.channel.ClanChannelHandler.updateMemberList(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents().
formatPrice()
String com.runehive.util.Utility.formatPrice (final long amount) static
Formats a price for longs.
Definition at line 56 of file Utility.java.
{
        if (amount >= 0 && amount < 1_000)
            return "" + amount;
        if (amount >= 1_000 && amount < 1_000_000) {
            return (amount / 1_000) + "K";
        }
        if (amount >= 1_000_000 && amount < 1_000_000_000) {
            return (amount / 1_000_000) + "M";
        }
        if (amount >= 1_000_000_000 && amount < Integer.MAX_VALUE) {
            return (amount / 1_000_000_000) + "B";
        }
        return "<col=fc2a2a>Lots!";
    }
Referenced by com.runehive.content.store.impl.PersonalStore.openMenu(), com.runehive.game.world.items.containers.bank.Bank.sendValue(), com.runehive.content.ProfileViewer.string(), and com.runehive.game.world.items.containers.bank.BankVault.withdraw().
formatText()
String com.runehive.util.Utility.formatText (String s) static
Definition at line 682 of file Utility.java.
{
        for (int i = 0; i < s.length(); i++) {
            if (i == 0) {
                s = String.format("%s%s", Character.toUpperCase(s.charAt(0)),
                        s.substring(1));
            }
            if (!Character.isLetterOrDigit(s.charAt(i))) {
                if (i + 1 < s.length()) {
                    s = String.format("%s%s%s", s.subSequence(0, i + 1),
                            Character.toUpperCase(s.charAt(i + 1)),
                            s.substring(i + 2));
                }
            }
        }
        return s.replace("_", " ");
    }
Referenced by com.runehive.content.gambling.impl.FlowerPoker.plant().
getAOrAn()
String com.runehive.util.Utility.getAOrAn (String nextWord) static
A or an.
Definition at line 116 of file Utility.java.
{
        String s = "a";
        char c = nextWord.toUpperCase().charAt(0);
        if (c == 'A' || c == 'E' || c == 'I' || c == 'O' || c == 'U') {
            s = "an";
        }
        return s;
    }
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.util.parser.old.defs.EquipmentRequirement.canEquip(), com.runehive.content.skill.impl.hunter.net.Netting.canSchedule(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.construction.House.construct(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMessages(), com.runehive.content.skill.impl.fishing.Fishing.hasFishingItems(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.inspect(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.content.mysterybox.MysteryBoxEvent.reward(), com.runehive.content.skill.impl.woodcutting.BirdsNest.search(), com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.donators.Donation.updateRank(), com.runehive.game.world.entity.skill.SkillManager.updateSkill(), com.runehive.content.skill.impl.crafting.Crafting.useItem(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
getBoundaries()
Position[] com.runehive.util.Utility.getBoundaries (Interactable interactable) static
Definition at line 605 of file Utility.java.
{
        int nextSlot = 0;
        int width = interactable.width();
        int length = interactable.length();
        Position[] boundaries = new Position[2 * (width + length)];
        for (int y = 0; y < length + 2; y++) {
            for (int x = 0; x < width + 2; x++) {
                int xx = x % (width + 1);
                int yy = y % (length + 1);
                if (xx == 0 && yy == 0 || xx != 0 && yy != 0) continue;
                boundaries[nextSlot++] = interactable.getPosition().transform(x - 1, y - 1, 0);
            }
        }
        return boundaries;
    }
References com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), com.runehive.game.world.position.Position.transform(), and com.runehive.game.world.Interactable.width().
Referenced by findAccessableTile(), and fixInsidePosition().
getClassesInDirectory()
List< Object > com.runehive.util.Utility.getClassesInDirectory (String directory) static
Gets all of the classes in a directory.
Definition at line 284 of file Utility.java.
{
        List<Object> classes = new LinkedList<>();
        File dir = new File(directory);
        if (!dir.exists() || !dir.isDirectory()) {
            return classes;
        }
        try {
            File[] files = dir.listFiles();
            if (files == null) {
                return classes;
            }
            for (File f : files) {
                if (f.isDirectory() || f.getName().contains("$")) {
                    continue;
                }
                String domainPath = Utility.class.getProtectionDomain().getCodeSource().getLocation().getPath().replace("/", "\\");
                String filePath = "\\" + f.getPath();
                String clazzName = filePath.replace(domainPath, "");
                clazzName = clazzName.replace("\\", ".");
                clazzName = clazzName.replace(".class", "");
                Class<?> clazz = Class.forName(clazzName);
                Object o = clazz.getDeclaredConstructor().newInstance();
                classes.add(o);
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException
                 | InvocationTargetException | NoSuchMethodException e) {
            // e.printStackTrace();
        }
        return classes;
    }
getCurrentDay()
int com.runehive.util.Utility.getCurrentDay () static
Definition at line 891 of file Utility.java.
{
        return Calendar.getInstance().get(Calendar.DAY_OF_YEAR);
    }
Referenced by com.runehive.content.dailyeffect.DailyEffect.canUse(), and com.runehive.content.dailyeffect.DailyEffect.use().
getDate()
String com.runehive.util.Utility.getDate () static
Gets the date of server.
Definition at line 126 of file Utility.java.
{
        return new SimpleDateFormat("EE MMM dd yyyy").format(new Date());
    }
Referenced by com.runehive.content.famehall.FameHandler.activate().
getDelta() [1/3]
Position com.runehive.util.Utility.getDelta (Interactable source, Interactable target) static
Definition at line 459 of file Utility.java.
{
        return getDelta(source.getPosition(), source.width(), source.length(), target.getPosition(), target.width(), target.length());
    }
References getDelta(), com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), and com.runehive.game.world.Interactable.width().
getDelta() [2/3]
Position com.runehive.util.Utility.getDelta (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength) static
Definition at line 421 of file Utility.java.
{
        if (source.getHeight() != target.getHeight()) {
            return Position.create(Integer.MAX_VALUE, Integer.MAX_VALUE);
        }
        if (sourceWidth <= 0) sourceWidth = 1;
        if (sourceLength <= 0) sourceLength = 1;
        if (targetWidth <= 0) targetWidth = 1;
        if (targetLength <= 0) targetLength = 1;
        Position sourceTopRight = source.transform(sourceWidth - 1, sourceLength - 1, 0);
        Position targetTopRight = target.transform(targetWidth - 1, targetLength - 1, 0);
        int dx, dy;
        if (sourceTopRight.getX() < target.getX()) {
            dx = target.getX() - sourceTopRight.getX();
        } else if (source.getX() > targetTopRight.getX()) {
            dx = source.getX() - targetTopRight.getX();
        } else {
            dx = 0;
        }
        if (sourceTopRight.getY() < target.getY()) {
            dy = target.getY() - sourceTopRight.getY();
        } else if (source.getY() > targetTopRight.getY()) {
            dy = source.getY() - targetTopRight.getY();
        } else {
            dy = 0;
        }
        return Position.create(dx, dy);
    }
References com.runehive.game.world.position.Position.create(), com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), and com.runehive.game.world.position.Position.transform().
Referenced by fixInsidePosition(), and getDelta().
getDelta() [3/3]
Position com.runehive.util.Utility.getDelta (Position source, Position target) static
Definition at line 463 of file Utility.java.
{
        int dx = target.getX() - source.getX();
        int dy = target.getY() - source.getY();
        return Position.create(dx, dy);
    }
References com.runehive.game.world.position.Position.create(), com.runehive.game.world.position.Position.getX(), and com.runehive.game.world.position.Position.getY().
getDistance() [1/3]
int com.runehive.util.Utility.getDistance (Interactable source, Interactable target) static
Definition at line 455 of file Utility.java.
{
        return getDistance(source.getPosition(), source.width(), source.length(), target.getPosition(), target.width(), target.length());
    }
References getDistance(), com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), and com.runehive.game.world.Interactable.width().
getDistance() [2/3]
int com.runehive.util.Utility.getDistance (Interactable source, Position target) static
Definition at line 363 of file Utility.java.
{
        Position sourceTopRight = source.getPosition().transform(source.width() - 1, source.length() - 1);
        int dx, dy;
        if (sourceTopRight.getX() < target.getX()) {
            dx = target.getX() - sourceTopRight.getX();
        } else if (source.getX() > target.getX()) {
            dx = source.getX() - target.getX();
        } else {
            dx = 0;
        }
        if (sourceTopRight.getY() < target.getY()) {
            dy = target.getY() - sourceTopRight.getY();
        } else if (source.getY() > target.getY()) {
            dy = source.getY() - target.getY();
        } else {
            dy = 0;
        }
        return dx + dy;
    }
References com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.getX(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.Interactable.getY(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.Interactable.length(), com.runehive.game.world.position.Position.transform(), and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.game.world.entity.combat.CombatUtil.areaAction(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.game.world.entity.combat.CombatTarget.compare(), findBestInside(), com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.findRoute(), com.runehive.game.world.region.RegionManager.forNearbyPlayer(), com.runehive.game.world.region.RegionManager.forNearbyPlayer(), getDistance(), com.runehive.game.world.position.Position.getManhattanDistance(), com.runehive.game.world.entity.combat.CombatUtil.getOldHitDelay(), com.runehive.game.world.entity.combat.CombatTarget.setTarget(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.withinDistance(), com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.withinDistance(), and com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.withinDistance().
getDistance() [3/3]
int com.runehive.util.Utility.getDistance (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength) static
Definition at line 387 of file Utility.java.
{
        if (source.getHeight() != target.getHeight()) {
            return Integer.MAX_VALUE;
        }
        if (sourceWidth <= 0) sourceWidth = 1;
        if (sourceLength <= 0) sourceLength = 1;
        if (targetWidth <= 0) targetWidth = 1;
        if (targetLength <= 0) targetLength = 1;
        Position sourceTopRight = source.transform(sourceWidth - 1, sourceLength - 1, 0);
        Position targetTopRight = target.transform(targetWidth - 1, targetLength - 1, 0);
        int dx, dy;
        if (sourceTopRight.getX() < target.getX()) {
            dx = target.getX() - sourceTopRight.getX();
        } else if (source.getX() > targetTopRight.getX()) {
            dx = source.getX() - targetTopRight.getX();
        } else {
            dx = 0;
        }
        if (sourceTopRight.getY() < target.getY()) {
            dy = target.getY() - sourceTopRight.getY();
        } else if (source.getY() > targetTopRight.getY()) {
            dy = source.getY() - targetTopRight.getY();
        } else {
            dy = 0;
        }
        return dx + dy;
    }
References com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), and com.runehive.game.world.position.Position.transform().
getInnerBoundaries() [1/2]
Position[] com.runehive.util.Utility.getInnerBoundaries (Interactable interactable) static
Definition at line 632 of file Utility.java.
{
        int nextSlot = 0;
        int width = interactable.width();
        int length = interactable.length();
        Position[] boundaries = new Position[width * length];
        for (int y = 0; y < length; y++) {
            for (int x = 0; x < width; x++) {
                boundaries[nextSlot++] = interactable.getPosition().transform(x, y, 0);
            }
        }
        return boundaries;
    }
References com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), com.runehive.game.world.position.Position.transform(), and com.runehive.game.world.Interactable.width().
getInnerBoundaries() [2/2]
Position[] com.runehive.util.Utility.getInnerBoundaries (Position position, int width, int length) static
Definition at line 621 of file Utility.java.
{
        int nextSlot = 0;
        Position[] boundaries = new Position[width * length];
        for (int y = 0; y < length; y++) {
            for (int x = 0; x < width; x++) {
                boundaries[nextSlot++] = position.transform(x, y, 0);
            }
        }
        return boundaries;
    }
References com.runehive.game.world.position.Position.transform().
Referenced by com.runehive.content.pet.Pets.abandon(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.finishIncoming(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.hit(), com.runehive.content.activity.impl.magearena.MageArena.meteors(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonAttack(), com.runehive.game.world.entity.mob.npc.Npc.register(), com.runehive.content.bloodmoney.BloodMoneyChest.spawn(), com.runehive.content.activity.impl.fightcaves.FightCaves.start(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.start(), com.runehive.content.activity.inferno.Inferno.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.start().
getPercentageAmount()
double com.runehive.util.Utility.getPercentageAmount (int progress, int total) static
Gets a percentage amount.
Definition at line 36 of file Utility.java.
{
        return 100D * progress / total;
    }
Referenced by com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.content.WellOfGoodwill.open(), com.runehive.content.activity.impl.barrows.Barrows.update(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update(), com.runehive.content.activity.impl.fightcaves.FightCaves.update(), com.runehive.content.activity.impl.magearena.MageArena.update(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.update(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.update(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.update(), com.runehive.content.activity.inferno.Inferno.update(), com.runehive.game.action.impl.TutorialActivity.update(), and com.runehive.content.clanchannel.content.ClanViewer.viewAchievements().
getSimpleDate()
String com.runehive.util.Utility.getSimpleDate () static
Gets the date of server.
Definition at line 131 of file Utility.java.
{
        return new SimpleDateFormat("yyyy/MM/dd").format(new Date());
    }
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.create(), com.runehive.content.clanchannel.channel.ClanChannel.establish(), and com.runehive.content.activity.record.GameRecord.GameRecord().
getStarters()
int com.runehive.util.Utility.getStarters (String host) static
Definition at line 825 of file Utility.java.
{
        int amount = 0;
        try {
            File file = new File("./data/starters/" + host + ".txt");
            if (!file.exists()) {
                return 0;
            }
            BufferedReader in = new BufferedReader(new FileReader(file));
            String whatever = in.readLine();
            long max = Long.parseLong(whatever);
            if (max > Integer.MAX_VALUE) {
                amount = 2;
            } else {
                amount = (int) max;
            }
            in.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return amount;
    }
Referenced by setStarter().
getSubDirectories()
List< String > com.runehive.util.Utility.getSubDirectories (Class<?> clazz) static
Gets all of the sub directories of a folder.
Definition at line 316 of file Utility.java.
{
        String filePath = clazz.getResource("/" + clazz.getName().replace(".", "/") + ".class").getFile();
        File file = new File(filePath);
        File directory = file.getParentFile();
        List<String> list = new ArrayList<>();
        File[] files = directory.listFiles();
        if (files == null) {
            return Collections.emptyList();
        }
        for (File f : files) {
            if (f.isDirectory()) {
                list.add(f.getPath());
            }
        }
        String[] directories = list.toArray(new String[0]);
        return Arrays.asList(directories);
    }
getTime() [1/3]
String com.runehive.util.Utility.getTime () static
Gets the current server time and formats it.
Definition at line 141 of file Utility.java.
{
        return new SimpleDateFormat("hh:mm aa").format(new Date());
    }
Referenced by com.runehive.content.activity.record.PlayerRecord.display(), com.runehive.content.activity.impl.fightcaves.FightCaves.finish(), com.runehive.content.activity.impl.kraken.KrakenActivity.finish(), com.runehive.content.activity.impl.magearena.MageArena.finish(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.finish(), com.runehive.content.activity.impl.VorkathActivity.finish(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.finish(), com.runehive.content.activity.inferno.Inferno.finish(), getUptime(), com.runehive.content.ProfileViewer.string(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update(), com.runehive.content.activity.impl.magearena.MageArena.update(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.update(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.update(), and com.runehive.content.activity.inferno.Inferno.update().
getTime() [2/3]
String com.runehive.util.Utility.getTime (int ticks) static
Gets a basic time based off seconds.
Definition at line 160 of file Utility.java.
{
        long secs = ticks * 3 / 5;
        if (secs < 60) {
            return "0:" + (secs < 10 ? "0" : "") + secs;
        }
        long mins = secs / 60;
        long remainderSecs = secs - (mins * 60);
        if (mins < 60) {
            return mins + ":" + (remainderSecs < 10 ? "0" : "") + remainderSecs + "";
        }
        long hours = mins / 60;
        long remainderMins = mins - (hours * 60);
        if (hours < 24) {
            return hours + "h " + (remainderMins < 10 ? "0" : "") + remainderMins + "m " + (remainderSecs < 10 ? "0" : "") + remainderSecs + "s";
        }
        long days = hours / 24;
        long remainderHrs = hours - (days * 24);
        return days + "d " + (remainderHrs < 10 ? "0" : "") + remainderHrs + "h " + (remainderMins < 10 ? "0" : "") + remainderMins + "m";
    }
getTime() [3/3]
String com.runehive.util.Utility.getTime (long period) static
Gets the time based off a long.
Definition at line 146 of file Utility.java.
{
        return new SimpleDateFormat("m:ss").format(period);
    }
getUptime()
String com.runehive.util.Utility.getUptime () static
Gets the current uptime of server and formats it.
Definition at line 155 of file Utility.java.
{
        return getTime((int) (RuneHive.UPTIME.elapsedTime() / 600));
    }
References com.runehive.util.Stopwatch.elapsedTime(), getTime(), and com.runehive.RuneHive.UPTIME.
goodDistance()
final boolean com.runehive.util.Utility.goodDistance (int objectX, int objectY, int playerX, int playerY, int distance) static
Definition at line 903 of file Utility.java.
{
        int deltaX = objectX - playerX;
        int deltaY = objectY - playerY;
        int trueDistance = ((int) Math.sqrt(Math.pow(deltaX, 2) + Math.pow(deltaY, 2)));
        return trueDistance <= distance;
    }
Referenced by com.runehive.content.wintertodt.Wintertodt.breakBrazier(), com.runehive.content.wintertodt.Wintertodt.doMagicAttack(), and com.runehive.game.world.entity.mob.player.Player.loadRegion().
hash()
long com.runehive.util.Utility.hash (String input) static
Definition at line 217 of file Utility.java.
{
        long hash = 0L;
        if (input == null) {
            input = "null";
        }
        for (int index = 0; index < input.length() && index < 12; index++) {
            char key = input.charAt(index);
            hash *= 37L;
            if (key >= 'A' && key <= 'Z') {
                hash += (1 + key) - 65;
            } else if (key >= 'a' && key <= 'z') {
                hash += (1 + key) - 97;
            } else if (key >= '0' && key <= '9') {
                hash += (27 + key) - 48;
            }
        }
        while (hash % 37L == 0L && hash != 0L) {
            hash /= 37L;
        }
        return hash;
    }
References hash().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), hash(), and nameToLong().
hasOneOutOf()
boolean com.runehive.util.Utility.hasOneOutOf (double chance) static
Definition at line 257 of file Utility.java.
{
        if (chance < 1) {
            chance = 0;
        }
        chance *= 100.0;
        return random(1, (int) chance) <= 100;
    }
References random().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.content.skill.impl.mining.MiningAction.handleCelestialRing(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.hit().
inRange() [1/2]
boolean com.runehive.util.Utility.inRange (int absX, int absY, int size, int targetX, int targetY, int targetSize, int distance) static
Definition at line 910 of file Utility.java.
{
        if (absX < targetX) {
            /*
             * West of target
             */
            int closestX = absX + (size - 1);
            int diffX = targetX - closestX;
            if (diffX > distance)
                return false;
        } else if (absX > targetX) {
            /*
             * East of target
             */
            int closestTargetX = targetX + (targetSize - 1);
            int diffX = absX - closestTargetX;
            if (diffX > distance)
                return false;
        }
        if (absY < targetY) {
            /*
             * South of target
             */
            int closestY = absY + (size - 1);
            int diffY = targetY - closestY;
            return diffY <= distance;
        } else if (absY > targetY) {
            /*
             * North of target
             */
            int closestTargetY = targetY + (targetSize - 1);
            int diffY = absY - closestTargetY;
            return diffY <= distance;
        }
        return true;
    }
Referenced by inRange(), com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >.withinDistance(), com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.withinDistance(), and com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.withinDistance().
inRange() [2/2]
boolean com.runehive.util.Utility.inRange (Interactable source, Interactable target, int distance) static
Definition at line 946 of file Utility.java.
{
        return inRange(source.getX(), source.getY(), source.width(), target.getX(), target.getY(), target.width(), distance);
    }
References com.runehive.game.world.Interactable.getX(), com.runehive.game.world.Interactable.getY(), inRange(), and com.runehive.game.world.Interactable.width().
inside() [1/3]
boolean com.runehive.util.Utility.inside (Interactable source, Interactable target) static
Definition at line 783 of file Utility.java.
{
        return inside(source.getPosition(), source.width(), source.length(), target.getPosition(), target.width(), target.length());
    }
References com.runehive.game.world.Interactable.getPosition(), inside(), com.runehive.game.world.Interactable.length(), and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.checkWithin(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.cloudEffect(), com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.execute(), findAccessableTile(), fixInsidePosition(), inside(), inside(), com.runehive.content.skill.impl.farming.zones.FarmingZone.isViewable(), com.runehive.game.world.region.Region.reachable(), com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.traversable(), and com.runehive.content.skill.impl.farming.patches.FarmingPatch.within().
inside() [2/3]
boolean com.runehive.util.Utility.inside (Interactable source, Position target) static
Definition at line 787 of file Utility.java.
{
        return inside(source.getPosition(), source.width(), source.length(), target, 1, 1);
    }
References com.runehive.game.world.Interactable.getPosition(), inside(), com.runehive.game.world.Interactable.length(), and com.runehive.game.world.Interactable.width().
inside() [3/3]
boolean com.runehive.util.Utility.inside (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength) static
Definition at line 791 of file Utility.java.
{
        if (sourceWidth <= 0) sourceWidth = 1;
        if (sourceLength <= 0) sourceLength = 1;
        if (targetWidth <= 0) targetWidth = 1;
        if (targetLength <= 0) targetLength = 1;
        Position sourceTopRight = source.transform(sourceWidth - 1, sourceLength - 1, 0);
        Position targetTopRight = target.transform(targetWidth - 1, targetLength - 1, 0);
        if (source.equals(target) || sourceTopRight.equals(targetTopRight)) {
            return true;
        }
        if (source.getX() > targetTopRight.getX() || sourceTopRight.getX() < target.getX()) {
            return false;
        }
        return source.getY() <= targetTopRight.getY() && sourceTopRight.getY() >= target.getY();
    }
References com.runehive.game.world.position.Position.equals(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), and com.runehive.game.world.position.Position.transform().
isLarger()
boolean com.runehive.util.Utility.isLarger (Interactable source, Interactable other) static
Definition at line 821 of file Utility.java.
{
        return source.width() * source.length() > other.width() * other.length();
    }
References com.runehive.game.world.Interactable.length(), and com.runehive.game.world.Interactable.width().
isRegionChange()
boolean com.runehive.util.Utility.isRegionChange (Position position, Position region) static
Definition at line 343 of file Utility.java.
{
        int diffX = position.getX() - region.getChunkX() * 8;
        int diffY = position.getY() - region.getChunkY() * 8;
        boolean changed = false;
        if (diffX < 16) {
            changed = true;
        } else if (diffX >= 88) {
            changed = true;
        }
        if (diffY < 16) {
            changed = true;
        } else if (diffY >= 88) {
            changed = true;
        }
        return changed;
    }
References com.runehive.game.world.position.Position.getChunkX(), com.runehive.game.world.position.Position.getChunkY(), com.runehive.game.world.position.Position.getX(), and com.runehive.game.world.position.Position.getY().
Referenced by com.runehive.game.world.entity.mob.Mob.move().
longToString()
String com.runehive.util.Utility.longToString (long l) static
Definition at line 202 of file Utility.java.
{
        if (l <= 0L || l >= 0x5b5b57f8a98a5dd1L)
            return null;
        if (l % 37L == 0L)
            return null;
        int i = 0;
        char ac[] = new char[12];
        while (l != 0L) {
            long l1 = l;
            l /= 37L;
            ac[11 - i++] = VALID_CHARS[(int) (l1 - l * 37L)];
        }
        return new String(ac, 12 - i, i);
    }
References VALID_CHARS.
Referenced by com.runehive.game.world.entity.mob.player.relations.PlayerRelation.addFriend(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.addIgnore(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteFriend(), and com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteIgnore().
min()
int com.runehive.util.Utility.min (int... values) static
Definition at line 895 of file Utility.java.
{
        int i = Integer.MAX_VALUE;
        for(int i2 : values)
            if(i2 < i)
                i = i2;
        return i;
    }
Referenced by com.runehive.content.wintertodt.Wintertodt.mixHerb().
nameToLong()
long com.runehive.util.Utility.nameToLong (String text) static
Converts the first 12 characters in a string of text to a hash.
Definition at line 185 of file Utility.java.
{
        long hash = 0L;
        for (int index = 0; index < text.length() && index < 12; index++) {
            char key = text.charAt(index);
            hash *= 37L;
            if (key >= 'A' && key <= 'Z')
                hash += (1 + key) - 65;
            else if (key >= 'a' && key <= 'z')
                hash += (1 + key) - 97;
            else if (key >= '0' && key <= '9')
                hash += (27 + key) - 48;
        }
        while (hash % 37L == 0L && hash != 0L)
            hash /= 37L;
        return hash;
    }
References hash().
Referenced by com.runehive.net.session.LoginSession.evaluate(), com.runehive.game.world.entity.mob.player.Player.Player(), and com.runehive.game.world.entity.mob.player.Player.setUsername().
random() [1/3]
int com.runehive.util.Utility.random (int bound) static
Definition at line 239 of file Utility.java.
{
        return random(0, bound, false);
    }
References random().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.AcidTask(), com.runehive.content.Obelisks.activate(), com.runehive.content.triviabot.TriviaBot.answer(), com.runehive.content.triviabot.TriviaBot.answered(), com.runehive.content.wintertodt.Wintertodt.applyColdDamage(), com.runehive.content.skill.impl.slayer.Slayer.assign(), com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.wintertodt.Wintertodt.breakBrazier(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.canAttack(), com.runehive.content.skill.impl.thieving.WallSafe.chance(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.wintertodt.Wintertodt.doMagicAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.content.skill.impl.woodcutting.BirdsNest.drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.skill.impl.hunter.net.Netting.execute(), com.runehive.content.skill.impl.thieving.PickpocketAction.execute(), com.runehive.content.wintertodt.Wintertodt.extinguishBraziers(), com.runehive.content.activity.inferno.Inferno.finish(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.finishOutgoing(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), fixInsidePosition(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.gambling.impl.FiftyFive.gamble(), com.runehive.content.gambling.impl.FlowerPoker.gamble(), com.runehive.content.lms.LMSGame.gearUpPlayers(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.clanchannel.content.ClanTask.getAmount(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), com.runehive.content.Obelisks.ObeliskData.getRandom(), com.runehive.game.world.entity.mob.Direction.getRandomDirection(), com.runehive.game.world.position.impl.SquareArea.getRandomLocation(), com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMiscDrops(), hasOneOutOf(), com.runehive.game.world.entity.combat.attack.listener.item.AhrimListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ToragListener.hit(), com.runehive.game.world.entity.combat.attack.listener.npc.SergeantStrongstack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.content.skill.SkillRepository.isSuccess(), com.runehive.content.skill.SkillRepository.isSuccess(), com.runehive.content.skill.SkillRepository.isSuccess(), com.runehive.game.world.items.Item.Item(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.lms.loadouts.LMSLoadoutManager.load(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.content.activity.impl.magearena.MageArena.meteors(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.lms.LMSGame.moveToGame(), com.runehive.content.mysterybox.MysteryBoxEvent.MysteryBoxEvent(), com.runehive.util.parser.impl.NpcForceChatParser.ForcedMessage.nextMessage(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.content.pet.Pets.onReward(), com.runehive.content.pet.Pets.onReward(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), com.runehive.content.wintertodt.Wintertodt.pyromancerText(), random(), random(), com.runehive.content.skill.impl.thieving.WallSafe.rate(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.lms.LMSGame.reset(), com.runehive.content.lms.LMSGame.rollChest(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.content.skill.impl.hunter.trap.TrapExecution.setTrapProcess(), com.runehive.content.lms.LMSGame.setupSafezone(), com.runehive.content.lms.crate.LMSCrate.spawn(), com.runehive.content.activity.impl.magearena.MageArena.start(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.start(), com.runehive.content.activity.inferno.Inferno.start(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.start(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.TeleGrab.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack.start(), com.runehive.content.skill.impl.cooking.Cooking.success(), com.runehive.content.skill.impl.mining.Mining.success(), com.runehive.game.task.impl.CeillingCollapseTask.tick(), and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
random() [2/3]
int com.runehive.util.Utility.random (int lowerBound, int upperBound) static
Definition at line 243 of file Utility.java.
{
        return random(lowerBound, upperBound, false);
    }
References random().
random() [3/3]
int com.runehive.util.Utility.random (int lowerBound, int upperBound, boolean inclusive) static
Definition at line 275 of file Utility.java.
{
        if (lowerBound >= upperBound) {
            throw new IllegalArgumentException("The lower bound cannot be larger than or equal to the upper bound!");
        }
        return lowerBound + RANDOM.nextInt(upperBound - lowerBound) + (inclusive ? 1 : 0);
    }
References RANDOM.
randomElement() [1/4]
static< T > T com.runehive.util.Utility.randomElement (Collection< T > collection) static
Picks a random element out of any array type.
Definition at line 248 of file Utility.java.
{
        return new ArrayList<T>(collection).get((int) (RANDOM.nextDouble() * collection.size()));
    }
References RANDOM.
Referenced by com.runehive.content.pet.Pets.abandon(), com.runehive.content.skill.impl.slayer.SlayerTask.assign(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.content.skill.impl.woodcutting.BirdsNest.drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.skill.impl.thieving.PickpocketAction.execute(), com.runehive.game.task.impl.MessageEvent.execute(), com.runehive.content.bot.objective.impl.RestockObjective.finish(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.generate(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.generate(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.generate(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.generate(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.clanchannel.content.ClanTask.getAssignment(), com.runehive.content.activity.impl.magearena.MageArena.getAvailablePosition(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.getCloudPosition(), com.runehive.content.activity.impl.barrows.BarrowsUtility.getHiddenBrother(), com.runehive.content.preloads.RandomItem.getItem(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.getSnakelingPosition(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMiscDrops(), com.runehive.game.world.entity.combat.attack.listener.npc.SergeantStrongstack.hit(), com.runehive.content.bot.objective.impl.CombatObjective.init(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.content.bot.PlayerBot.loopCombat(), com.runehive.content.bot.BotUtility.nameGenerator(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.nextPhase(), com.runehive.content.DropDisplay.open(), com.runehive.content.simulator.DropSimulator.open(), com.runehive.content.skill.impl.woodcutting.BirdsNest.search(), com.runehive.content.emote.EmoteHandler.selectRandom(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.sequence(), com.runehive.game.world.entity.mob.npc.Npc.sequence(), com.runehive.content.activity.record.PlayerRecord.showActivities(), com.runehive.content.bloodmoney.BloodMoneyChest.spawn(), com.runehive.content.skill.SkillRepository.spawn(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.spawnMonsters(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.start(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.start(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.start(), and com.runehive.content.activity.impl.magearena.MageArena.update().
randomElement() [2/4]
int com.runehive.util.Utility.randomElement (int[] array) static
Picks a random element out of any array type.
Definition at line 271 of file Utility.java.
{
        return array[(int) (RANDOM.nextDouble() * array.length)];
    }
References RANDOM.
randomElement() [3/4]
static< T > T com.runehive.util.Utility.randomElement (List< T > list) static
Picks a random element out of any list type.
Definition at line 253 of file Utility.java.
{
        return list.get((int) (RANDOM.nextDouble() * list.size()));
    }
References RANDOM.
randomElement() [4/4]
static< T > T com.runehive.util.Utility.randomElement (T[] array) static
Picks a random element out of any array type.
Definition at line 266 of file Utility.java.
{
        return array[(int) (RANDOM.nextDouble() * array.length)];
    }
References RANDOM.
rank()
String com.runehive.util.Utility.rank (final String string) static
Formats the player name.
Definition at line 94 of file Utility.java.
{
        return Stream.of(string.trim().split("\\s")).filter(word -> word.length() > 0).map(word -> word.substring(0, 1).toUpperCase() + word.substring(1)).collect(Collectors.joining(" "));
    }
setStarter()
boolean com.runehive.util.Utility.setStarter (Player player) static
Definition at line 851 of file Utility.java.
{
        String host = player.lastHost;
        int amount = getStarters(host);
        if (amount >= 2) {
            return false;
        }
        if (amount == 0) {
            amount = 1;
        } else if (amount == 1) {
            amount = 2;
        }
        try {
            File file = new File("./data/starters/" + host + ".txt");
            BufferedWriter out = new BufferedWriter(new FileWriter(file, false));
            out.write(String.valueOf(amount));
            out.close();
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }
References getStarters(), and com.runehive.game.world.entity.mob.player.Player.lastHost.
shuffleArray()
int[] com.runehive.util.Utility.shuffleArray (int[] array) static
Definition at line 878 of file Utility.java.
{
        int[] shuffledArray = new int[array.length];
        System.arraycopy(array, 0, shuffledArray, 0, array.length);
        for (int i = shuffledArray.length - 1; i > 0; i--) {
            int index = RANDOM.nextInt(i + 1);
            int a = shuffledArray[index];
            shuffledArray[index] = shuffledArray[i];
            shuffledArray[i] = a;
        }
        return shuffledArray;
    }
References RANDOM.
Referenced by com.runehive.content.puzzle.PuzzleDisplay.randomize().
stringToLong()
long com.runehive.util.Utility.stringToLong (String string) static
Definition at line 71 of file Utility.java.
{
        long l = 0L;
        for (int i = 0; i < string.length() && i < 12; i++) {
            char c = string.charAt(i);
            l *= 37L;
            if (c >= 'A' && c <= 'Z')
                l += (1 + c) - 65;
            else if (c >= 'a' && c <= 'z')
                l += (1 + c) - 97;
            else if (c >= '0' && c <= '9')
                l += (27 + c) - 48;
        }
        while (l % 37L == 0L && l != 0L)
            l /= 37L;
        return l;
    }
Referenced by com.runehive.game.world.entity.mob.player.relations.PlayerRelation.isFriendWith().
within() [1/3]
boolean com.runehive.util.Utility.within (Interactable source, Interactable target, int distance) static
Definition at line 699 of file Utility.java.
{
        return within(source.getPosition(), source.width(), source.length(), target.getPosition(), target.width(), target.length(), distance);
    }
References com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), com.runehive.game.world.Interactable.width(), and within().
within() [2/3]
boolean com.runehive.util.Utility.within (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength, int distance) static
Definition at line 731 of file Utility.java.
{
        if (target.getHeight() != source.getHeight()) {
            return false;
        }
        Position sourceTopRight = source.transform(sourceWidth - 1, sourceLength - 1);
        Position targetTopRight = target.transform(targetWidth - 1, targetLength - 1);
        int dx, dy;
        if (sourceTopRight.getX() < target.getX()) {
            dx = Math.abs(target.getX() - sourceTopRight.getX());
        } else if (source.getX() > targetTopRight.getX()) {
            dx = Math.abs(targetTopRight.getX() - source.getX());
        } else {
            dx = 0;
        }
        if (sourceTopRight.getY() < target.getY()) {
            dy = Math.abs(target.getY() - sourceTopRight.getY());
        } else if (source.getY() > targetTopRight.getY()) {
            dy = Math.abs(targetTopRight.getY() - source.getY());
        } else {
            dy = 0;
        }
        return dx + dy <= distance;
    }
References com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), and com.runehive.game.world.position.Position.transform().
within() [3/3]
boolean com.runehive.util.Utility.within (Position source, Position target, int distance) static
Definition at line 676 of file Utility.java.
{
        Interactable interactableSource = Interactable.create(source);
        Interactable interactableTarget = Interactable.create(target);
        return within(interactableSource, interactableTarget, distance);
    }
References com.runehive.game.world.Interactable.create(), and within().
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.Alkahrid.block(), com.runehive.game.action.impl.DoorAction.execute(), com.runehive.game.world.entity.combat.attack.listener.npc.SergeantStrongstack.hit(), within(), within(), com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.withinDistance(), withinDistance(), and withinDistance().
withinDistance() [1/2]
boolean com.runehive.util.Utility.withinDistance (Interactable source, Interactable target, int radius) static
Definition at line 470 of file Utility.java.
{
        return within(source, target, radius);
    }
References within().
Referenced by com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.checkDistances(), com.runehive.content.combat.cannon.CannonManager.getNpc(), com.runehive.content.skill.impl.farming.zones.FarmingZone.isViewable(), com.runehive.game.world.entity.mob.player.requests.RequestManager.request(), com.runehive.game.world.World.sendGraphic(), com.runehive.game.world.World.sendGraphic(), com.runehive.game.world.World.sendObjectAnimation(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.World.sendProjectile(), com.runehive.game.world.World.sendProjectile(), and com.runehive.game.world.World.sendProjectile().
withinDistance() [2/2]
boolean com.runehive.util.Utility.withinDistance (Interactable source, Position target, int radius) static
Definition at line 474 of file Utility.java.
{
        return within(source.getPosition(), source.width(), source.length(), target, 1, 1, radius);
    }
References com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), com.runehive.game.world.Interactable.width(), and within().
withinOctal() [1/2]
boolean com.runehive.util.Utility.withinOctal (Interactable source, Interactable target, int distance) static
Definition at line 703 of file Utility.java.
{
        return withinOctal(source.getPosition(), source.width(), source.length(), target.getPosition(), target.width(), target.length(), distance);
    }
References com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), com.runehive.game.world.Interactable.width(), and withinOctal().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack.hit(), and withinOctal().
withinOctal() [2/2]
boolean com.runehive.util.Utility.withinOctal (Position source, int sourceWidth, int sourceLength, Position target, int targetWidth, int targetLength, int distance) static
Definition at line 707 of file Utility.java.
{
        if (target.getHeight() != source.getHeight()) {
            return false;
        }
        Position sourceTopRight = source.transform(sourceWidth - 1, sourceLength - 1);
        Position targetTopRight = target.transform(targetWidth - 1, targetLength - 1);
        int dx, dy;
        if (sourceTopRight.getX() < target.getX()) {
            dx = Math.abs(target.getX() - sourceTopRight.getX());
        } else if (source.getX() > targetTopRight.getX()) {
            dx = Math.abs(targetTopRight.getX() - source.getX());
        } else {
            dx = 0;
        }
        if (sourceTopRight.getY() < target.getY()) {
            dy = Math.abs(target.getY() - sourceTopRight.getY());
        } else if (source.getY() > targetTopRight.getY()) {
            dy = Math.abs(targetTopRight.getY() - source.getY());
        } else {
            dy = 0;
        }
        return dx <= distance && dy <= distance;
    }
References com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), and com.runehive.game.world.position.Position.transform().
withinViewingDistance()
boolean com.runehive.util.Utility.withinViewingDistance (Interactable source, Interactable target, int radius) static
Definition at line 755 of file Utility.java.
{
        if (source == null || target == null) {
            return false;
        }
        if (target.getHeight() != source.getHeight()) {
            return false;
        }
        Position sourceTopRight = source.getPosition().transform(source.width() - 1, source.length() - 1);
        Position targetTopRight = target.getPosition().transform(target.width() - 1, target.length() - 1);
        int dx, dy;
        if (sourceTopRight.getX() < target.getX()) {
            dx = Math.abs(target.getX() - sourceTopRight.getX());
        } else if (source.getX() > targetTopRight.getX()) {
            dx = Math.abs(targetTopRight.getX() - source.getX());
        } else {
            dx = 0;
        }
        if (sourceTopRight.getY() < target.getY()) {
            dy = Math.abs(target.getY() - sourceTopRight.getY());
        } else if (source.getY() > targetTopRight.getY()) {
            dy = Math.abs(targetTopRight.getY() - source.getY());
        } else {
            dy = 0;
        }
        return dx <= radius && dy <= radius;
    }
References com.runehive.game.world.Interactable.getHeight(), com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.getX(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.Interactable.getY(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.Interactable.length(), com.runehive.game.world.position.Position.transform(), and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.game.world.entity.combat.CombatUtil.areaAction(), com.runehive.game.world.object.StaticGameObject.register(), and com.runehive.game.world.object.StaticGameObject.unregister().
Member Data Documentation
RANDOM
final Random com.runehive.util.Utility.RANDOM = new Random(System.currentTimeMillis()) static private
Random instance, used to generate pseudo-random primitive types.
Definition at line 30 of file Utility.java.
Referenced by random(), randomElement(), randomElement(), randomElement(), randomElement(), and shuffleArray().
VALID_CHARS
final char [] com.runehive.util.Utility.VALID_CHARS = {'_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '/'} static private
Array of all valid characters.
Definition at line 33 of file Utility.java.
{'_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '/'};
Referenced by longToString().
The documentation for this class was generated from the following file:
java/com/runehive/util/Utility.java