RuneHive-Game: com.runehive.net.LoginExecutorService Class Reference
com.runehive.net.LoginExecutorService Class Reference
Public Member Functions
void close () throws IOException
void execute (final LoginSession loginSession, final LoginDetailsPacket loginDetailsPacket)
LoginExecutorService (final int threads)
Private Attributes
final ExecutorService executorService
Static Private Attributes
static final Logger logger = LoggerFactory.getLogger(LoginExecutorService.class)
static final long TERMINATION_TIMEOUT = 60
static final TimeUnit TERMINATION_TIMEOUT_UNIT = TimeUnit.SECONDS
Detailed Description
Definition at line 14 of file LoginExecutorService.java.
Constructor & Destructor Documentation
LoginExecutorService()
com.runehive.net.LoginExecutorService.LoginExecutorService (final int threads)
Definition at line 23 of file LoginExecutorService.java.
{
        this.executorService = Executors.newFixedThreadPool(threads);
    }
Member Function Documentation
close()
void com.runehive.net.LoginExecutorService.close () throws IOException
Definition at line 28 of file LoginExecutorService.java.
{
        final ExecutorService executorService = this.executorService;
        executorService.shutdown();
        try {
            // Wait a while for existing tasks to terminate
            if (!executorService.awaitTermination(TERMINATION_TIMEOUT, TERMINATION_TIMEOUT_UNIT)) {
                executorService.shutdownNow(); // Cancel currently executing tasks
                // Wait a while for tasks to respond to being cancelled
                if (!executorService.awaitTermination(TERMINATION_TIMEOUT, TERMINATION_TIMEOUT_UNIT)) {
                    logger.warn("Pool did not terminate in {} {}", TERMINATION_TIMEOUT, TERMINATION_TIMEOUT_UNIT);
                }
            }
        } catch (final InterruptedException ex) {
            // (Re-)Cancel if current thread also interrupted
            executorService.shutdownNow();
            // Preserve interrupt status
            Thread.currentThread().interrupt();
        }
    }
References executorService, logger, TERMINATION_TIMEOUT, and TERMINATION_TIMEOUT_UNIT.
execute()
void com.runehive.net.LoginExecutorService.execute (final LoginSession loginSession, final LoginDetailsPacket loginDetailsPacket)
Definition at line 48 of file LoginExecutorService.java.
{
        executorService.execute(() -> loginSession.handleUserLoginDetails(loginDetailsPacket));
    }
References executorService, and com.runehive.net.session.LoginSession.handleUserLoginDetails().
Referenced by com.runehive.net.session.LoginSession.handleClientPacket().
Member Data Documentation
executorService
final ExecutorService com.runehive.net.LoginExecutorService.executorService private
Definition at line 21 of file LoginExecutorService.java.
Referenced by close(), and execute().
logger
final Logger com.runehive.net.LoginExecutorService.logger = LoggerFactory.getLogger(LoginExecutorService.class) static private
Definition at line 16 of file LoginExecutorService.java.
Referenced by close().
TERMINATION_TIMEOUT
final long com.runehive.net.LoginExecutorService.TERMINATION_TIMEOUT = 60 static private
Definition at line 18 of file LoginExecutorService.java.
Referenced by close().
TERMINATION_TIMEOUT_UNIT
final TimeUnit com.runehive.net.LoginExecutorService.TERMINATION_TIMEOUT_UNIT = TimeUnit.SECONDS static private
Definition at line 19 of file LoginExecutorService.java.
Referenced by close().
The documentation for this class was generated from the following file:
java/com/runehive/net/LoginExecutorService.java