RuneHive-Game: com.runehive.net.packet.in.ButtonClickPacketListener Class Reference
com.runehive.net.packet.in.ButtonClickPacketListener Class Reference
The GamePacket responsible for clicking buttons on the client.
Public Member Functions
void handlePacket (final Player player, GamePacket packet)
Handles the packet that has just been received.
Detailed Description
The GamePacket responsible for clicking buttons on the client.
Author
Daniel | Obey
Definition at line 22 of file ButtonClickPacketListener.java.
Member Function Documentation
handlePacket()
void com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket (final Player player, GamePacket packet)
Handles the packet that has just been received.
Parameters
player The player receiving this packet.
packet The packet that has been received.
Implements com.runehive.net.packet.PacketListener.
Definition at line 25 of file ButtonClickPacketListener.java.
{
        final int button = packet.readShort();
        if (player.isDead()) {
            return;
        }
        if (player.locking.locked(PacketType.CLICK_BUTTON, button)) {
            return;
        }
        // player.message("Currently not available");
        if (PlayerRight.isDeveloper(player) || PlayerRight.isOwner(player)) {
            player.send(new SendMessage(String.format("[%s]: button=%d", ButtonClickPacketListener.class.getSimpleName(), button)));
            System.out.println(String.format("[%s]: button=%d", ButtonClickPacketListener.class.getSimpleName(), button));
        }//save it plz theres no save button with intellij
        if (EventDispatcher.execute(player, new ClickButtonInteractionEvent(button))) {
            return;
        }
        PluginManager.getDataBus().publish(player, new ButtonClickEvent(button));
    }
References com.runehive.game.world.entity.mob.data.PacketType.CLICK_BUTTON, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.game.world.entity.mob.Mob.isDead(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), com.runehive.game.world.entity.mob.player.PlayerRight.isOwner(), com.runehive.game.world.entity.mob.Locking.locked(), com.runehive.game.world.entity.mob.Mob.locking, com.runehive.game.event.bus.PlayerDataBus.publish(), and com.runehive.game.world.entity.mob.player.Player.send().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/in/ButtonClickPacketListener.java