RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack Class Reference
com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack Class Reference
Public Member Functions
void finishOutgoing (Npc attacker, Mob defender)
Animation getAttackAnimation (Npc attacker, Mob defender)
int getAttackDistance (Npc attacker, FightType fightType)
CombatHit[] getHits (Npc attacker, Mob defender)
void hitsplat (Npc attacker, Mob defender, Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy
void attack (Npc attacker, Mob defender, Hit hit)
boolean canAttack (Npc attacker, Mob defender)
int getAttackDelay (Npc attacker, Mob defender, FightType fightType)
CombatProjectile getCombatProjectile ()
CombatType getCombatType ()
NpcRangedStrategy (CombatProjectile combatProjectile)
void sendAnimation (Npc attacker, Mob defender)
int sendProjectile (Mob from, Mob to, @Nullable Runnable onProjectileLand)
void start (Npc attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Package Functions
RangedAttack ()
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Definition at line 76 of file GeneralGraardor.java.
Constructor & Destructor Documentation
RangedAttack()
com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.RangedAttack () package
Definition at line 77 of file GeneralGraardor.java.
                       {
            super(getDefinition("Graardor Ranged"));
        }
Member Function Documentation
finishOutgoing()
void com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.finishOutgoing (Npc attacker, Mob defender)
Definition at line 103 of file GeneralGraardor.java.
{
            if (attacker.getStrategy() != MELEE) {
                attacker.setStrategy(MELEE);
            }
        }
References com.runehive.game.world.entity.mob.npc.Npc.getStrategy(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.MELEE, and com.runehive.game.world.entity.mob.npc.Npc.setStrategy().
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.getAttackAnimation (Npc attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.
Definition at line 82 of file GeneralGraardor.java.
{
            return new Animation(7021, UpdatePriority.HIGH);
        }
References com.runehive.game.UpdatePriority.HIGH.
getAttackDistance()
int com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.getAttackDistance (Npc attacker, FightType fightType)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.
Definition at line 110 of file GeneralGraardor.java.
{
            return 32;
        }
getHits()
CombatHit[] com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.getHits (Npc attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.
Definition at line 87 of file GeneralGraardor.java.
{
            return new CombatHit[]{nextRangedHit(attacker, defender, 35)};
        }
References com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit().
hitsplat()
void com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.hitsplat (Npc attacker, Mob defender, Hit hit)
Definition at line 92 of file GeneralGraardor.java.
{
            super.hitsplat(attacker, defender, hit);
            CombatUtil.areaAction(attacker, 64, 18, mob -> {
                if (mob.isPlayer() && Area.inBandos(mob)) {
                    mob.damage(nextRangedHit(attacker, defender, 35));
                }
            });
        }
References com.runehive.game.world.entity.combat.CombatUtil.areaAction(), com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.hit(), com.runehive.game.world.position.Area.inBandos(), and com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/npc/GeneralGraardor.java