RuneHive-Game: dev.advo.fs.net.ondemand.OnDemandRequestDecoder Class Reference
dev.advo.fs.net.ondemand.OnDemandRequestDecoder Class Reference
Static Public Member Functions
static int file (int pair)
static int index (int pair)
Protected Member Functions
Object decode (ChannelHandlerContext ctx, Channel c, ChannelBuffer buf) throws Exception
Detailed Description
Definition at line 11 of file OnDemandRequestDecoder.java.
Member Function Documentation
decode()
Object dev.advo.fs.net.ondemand.OnDemandRequestDecoder.decode (ChannelHandlerContext ctx, Channel c, ChannelBuffer buf) throws Exception protected
Definition at line 14 of file OnDemandRequestDecoder.java.
{
//      System.out.println("corrupted request" + buf.readableBytes());//lmfao.
//      for(int i = 0; i < buf.readableBytes(); i++)
//          System.out.println("corrupted request " + i + " " + buf.readByte());
        if (buf.readableBytes() >= 4) {
            int check = buf.readUnsignedByte();
            if(check != 1) {
                System.out.println("corrupted request " + check);
                //After the client submits type 0 for VT. All requestions should be 1.
                return null;
            }
            int hashed = buf.readMedium();
            int type = index(hashed);
            int file = file(hashed);
            System.out.println("requesting file " + type + " - " + file);
            FileDescriptor desc = new FileDescriptor(type, file);
            return new OnDemandRequest(desc);
        } else
        return null;
    }
References file(), and index().
file()
int dev.advo.fs.net.ondemand.OnDemandRequestDecoder.file (int pair) static
Definition at line 42 of file OnDemandRequestDecoder.java.
{
            return pair >>> 5 & 0x7FFFF;
          }
Referenced by decode().
index()
int dev.advo.fs.net.ondemand.OnDemandRequestDecoder.index (int pair) static
Definition at line 38 of file OnDemandRequestDecoder.java.
{
            return pair & 0x1F;
          }
Referenced by decode().
The documentation for this class was generated from the following file:
java/dev/advo/fs/net/ondemand/OnDemandRequestDecoder.java