RuneHive-Game: com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession Class Reference
com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession Class Reference
Public Member Functions
void accept (Player player, String component)
The method invoked when a PLAYER accepts a certain exchange component.
boolean canAddItem (Player player, Item item, int slot)
Checks if the item can be added to the container.
boolean canRemoveItem (Player player, Item item, int slot)
Checks if the item can be removed from the container.
boolean onButtonClick (Player p, int button)
The method invoked when a button is clicked.
boolean onRequest ()
The method invoked when a player requests the other player.
void onReset ()
Any functionality that should be handled when the itemcontainer closes.
TradeSession (Player player, Player other)
Constructs a new ExchangeSession.
void updateMainComponents (String component)
Updates the main components of the itemcontainer.
void updateOfferComponents ()
Updates the itemcontainer when an item is offered or removed.
Public Member Functions inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
final boolean add (Player player, int slot, int amount)
Attempts to deposit an item to the container.
void depositeAll (Player player)
Deposites all items to the exchange session.
ExchangeSession (Player player, Player other, ExchangeSessionType type)
Constructs a new ExchangeSession.
void forEach (Consumer< Player > action)
Executes the specified action for every player in this session.
Object getAttachment ()
Retrieves the attachment object to this class.
Player getOther (Player p)
Gets the other player in the exchange session.
boolean hasAttachment ()
Determines if the trade stage has an attachment.
boolean inAnySession ()
Determines if the player is any session.
final boolean remove (Player player, int slot, int amount)
Attempts to withdraw an item from the container.
boolean request ()
Attempts to start an exchange session.
void setAttachment (Object attachment)
Assigns an attachment to this stage object.
Private Member Functions
String getItemNames (Player player, Item[] items)
Determines and returns the text for items that will be displayed on the confirm trade screen.
Private Attributes
final Stopwatch lastOfferModification = Stopwatch.start()
The stopwatch which blocks the player from further continueing the session if a second hasn't passed after the last item has been added.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
static Optional< ExchangeSession > getSession (Player player)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, ExchangeSessionType type)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, Player other)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, Player other, ExchangeSessionType type)
Gets the session if applicable the player is in.
static boolean inSession (Player player, ExchangeSessionType type)
Determines if the player is a session which matches the type.
static boolean inSession (Player player, Player other, ExchangeSessionType type)
Determines if the player is a session with other which matches the type.
Public Attributes inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
boolean canOffer = true
Determines if the player can offer or withdraw items.
boolean finalized
Determines if this exchange has been finalized.
final Map< Player, ItemContainer > item_containers = new HashMap<>()
The items which are in this exchange session.
final Player other
The other player in this session.
final Player player
The controller of this session.
final ExchangeSessionType type
The type of this exchange session.
Static Public Attributes inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
static final Set< ExchangeSession > SESSIONS = new HashSet<>()
The collection of sessions.
Protected Member Functions inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
void finalize (ExchangeCompletionType type)
Finalizes the exchange session procedure for the specified player in a session.
void withdrawAll (Player player)
Withdraws all items from the exchange session.
Detailed Description
Author
Stand Up
Since
25-1-2017.
Definition at line 25 of file TradeSession.java.
Constructor & Destructor Documentation
TradeSession()
com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.TradeSession (Player player, Player other)
Constructs a new ExchangeSession.
Parameters
player the player this exchange session is for.
other the other player in this exchange session.
Definition at line 39 of file TradeSession.java.
{
        super(player, other, ExchangeSessionType.TRADE);
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, and com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.TRADE.
Member Function Documentation
accept()
void com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept (Player player, String COMPONENT)
The method invoked when a PLAYER accepts a certain exchange component.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 128 of file TradeSession.java.
{
        Player other = getOther(player);
        switch (component) {
            case "OFFER_ITEMS":
                if (!lastOfferModification.elapsed(1_000)) {
                    player.send(new SendString("@red@Trade has been modified!", 33030));
                    return;
                }
                if (!player.inventory.hasCapacityFor(item_containers.get(other).toArray())) {
                    player.send(new SendMessage("You don't have enough free slots for this many items.", MessageColor.RED));
                    break;
                }
                if (!other.inventory.hasCapacityFor(item_containers.get(player).toArray())) {
                    String username = other.getName();
                    player.send(new SendMessage(username + " doesn't have enough free slots for this many items", MessageColor.RED));
                    break;
                }
                if (hasAttachment() && getAttachment() != player) {
                    this.setAttachment(null);
                    updateMainComponents("SECOND_SCREEN");
                    return;
                }
                setAttachment(player);
                player.send(new SendString("Waiting for other player...", 33029));
                other.send(new SendString("Other player has accepted", 33029));
                break;
            case "CONFIRM_DECISION":
                if (hasAttachment() && getAttachment() != player) {
                    this.setAttachment(null);
                    accept(player, "FINALIZE");
                    return;
                }
                setAttachment(player);
                other.send(new SendString("Other player has accepted.", 33202));
                player.send(new SendString("Waiting for other player...", 33202));
                break;
            case "FINALIZE":
                if (other.isRegistered() && player.isRegistered()) {
                    final Item[] playerItems = this.item_containers.get(player).toArray();
                    final Item[] otherItems = this.item_containers.get(other).toArray();
                    player.inventory.addAll(otherItems);
                    other.inventory.addAll(playerItems);
                    World.getDataBus().publish(new TradeLogEvent(player, playerItems, other, otherItems));
                    forEach(p -> p.send(new SendMessage("Trade successfully completed with " + this.getOther(p).getName(), MessageColor.RED)));
                    finalize(ExchangeCompletionType.DISPOSE);
                }
                break;
        }
    }
References accept(), com.runehive.game.world.entity.mob.player.exchange.ExchangeCompletionType.DISPOSE, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.finalize(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getAttachment(), com.runehive.game.world.World.getDataBus(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getOther(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.hasAttachment(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.item_containers, lastOfferModification, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.game.event.bus.DataBus.publish(), com.runehive.util.MessageColor.RED, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.setAttachment(), and updateMainComponents().
Referenced by accept(), and onButtonClick().
canAddItem()
boolean com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.canAddItem (Player player, Item item, int slot)
Checks if the item can be added to the container.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 71 of file TradeSession.java.
{
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player.
canRemoveItem()
boolean com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.canRemoveItem (Player player, Item item, int slot)
Checks if the item can be removed from the container.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 76 of file TradeSession.java.
{
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player.
getItemNames()
String com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.getItemNames (Player player, Item[] items) private
Determines and returns the text for items that will be displayed on the confirm trade screen.
Definition at line 256 of file TradeSession.java.
{
        String tradeItems = "Absolutely nothing!";
        String tradeAmount;
        int count = 0;
        for (Item item : items) {
            if (item == null || tradeItems.contains(item.getName())) {
                continue;
            }
            int amount = this.item_containers.get(player).computeAmountForId(item.getId());
            tradeAmount = item.isStackable() ? amount >= 1000 && amount < 1000000 ? "@cya@" + (amount / 1000) + "K @whi@" + "(" + amount + ")" : amount >= 1000000 ? "@gre@" + (amount / 1000000) + " " + "million @whi@(" + amount + ")" : "" + amount : "(x" + amount + ")";
            tradeItems = count == 0 ? item.getName() : tradeItems + "\\n" + item.getName();
            tradeItems = tradeItems + (item.isStackable() ? " x " : " ") + tradeAmount;
            count++;
        }
        return tradeItems;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.item_containers, and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player.
Referenced by updateMainComponents().
onButtonClick()
boolean com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onButtonClick (Player player, int button)
The method invoked when a button is clicked.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 81 of file TradeSession.java.
{
        switch (button) {
            case -32513:
                if (!player.interfaceManager.isInterfaceOpen(InterfaceConstants.FIRST_TRADE_SCREEN)) {
                    return false;
                }
                depositeAll(p);
                return true;
            case -32510:
                if (!player.interfaceManager.isInterfaceOpen(InterfaceConstants.FIRST_TRADE_SCREEN)) {
                    return false;
                }
                withdrawAll(p);
                return true;
            case -32524:
            case -32530:
            case -32324:
            case -32332:
                p.exchangeSession.reset(ExchangeSessionType.TRADE);
                return true;
            case -32527:
                if (!player.interfaceManager.isInterfaceOpen(InterfaceConstants.FIRST_TRADE_SCREEN)) {
                    return false;
                }
                accept(p, "OFFER_ITEMS");
                return true;
            case -32327:
                if (!player.interfaceManager.isInterfaceOpen(InterfaceConstants.SECOND_TRADE_SCREEN)) {
                    return false;
                }
                accept(p, "CONFIRM_DECISION");
                return true;
        }
        return false;
    }
References accept(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.depositeAll(), com.runehive.game.world.entity.mob.player.Player.exchangeSession, com.runehive.game.world.InterfaceConstants.FIRST_TRADE_SCREEN, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.reset(), com.runehive.game.world.InterfaceConstants.SECOND_TRADE_SCREEN, com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.TRADE, and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.withdrawAll().
onRequest()
boolean com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onRequest ()
The method invoked when a player requests the other player.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 44 of file TradeSession.java.
{
        if(player.playTime < 6000) {
            player.send(new SendMessage("You must have over one hour of play time to trade."));
            return false;
        }
        if(player.getUsername().contains("nicholas") || player.getUsername().contains("muntuna")) {
            player.send(new SendMessage("You cannot trade as a " +player.getPlayer().right));
            return false;
        }
        this.player.face(other.getPosition());
        this.player.exchangeSession.requested_players.add(other);
        if (!other.exchangeSession.requested_players.contains(player)) {
            player.send(new SendMessage("Sending trade request..."));
            other.send(new SendMessage(player.getName() + ":tradereq:", MessageColor.PURPLE));
            return false;
        }
        SESSIONS.add(this);
        this.forEach(p -> {
            p.exchangeSession.resetRequests();
            p.send(new SendMinimapState(SendMinimapState.MinimapState.UNCLICKABLE));
            p.attributes.set("TRADE_KEY", true);
        });
        updateMainComponents("FIRST_SCREEN");
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.util.MessageColor.PURPLE, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.SESSIONS, com.runehive.net.packet.out.SendMinimapState.MinimapState.UNCLICKABLE, and updateMainComponents().
onReset()
void com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onReset ()
Any functionality that should be handled when the itemcontainer closes.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 243 of file TradeSession.java.
{
        forEach(p -> {
            p.attributes.set("TRADE_KEY", false);
            p.interfaceManager.close();
            p.resetFace();
            p.send(new SendMinimapState(SendMinimapState.MinimapState.NORMAL));
        });
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), and com.runehive.net.packet.out.SendMinimapState.MinimapState.NORMAL.
updateMainComponents()
void com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateMainComponents (String component)
Updates the main components of the itemcontainer.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 186 of file TradeSession.java.
{
        switch (component) {
            case "FIRST_SCREEN":
                updateOfferComponents();
                break;
            case "SECOND_SCREEN":
                forEach(p -> {
                    Player recipient = p.getName().equals(player.getName()) ? this.other : this.player;
                    p.send(new SendString("<col=65535>Are you sure you want to make this trade?", 33202));
                    p.send(new SendItemOnInterface(InterfaceConstants.INVENTORY_INTERFACE, p.inventory.toArray()));
                    p.send(new SendString(getItemNames(p, this.item_containers.get(p).toArray()), 33221));
                    p.send(new SendString(getItemNames(recipient, this.item_containers.get(recipient).toArray()), 33251));
                    p.send(new SendString("<col=65535>Trading With:", 33207));
                    p.send(new SendString(String.format("%s <col=65535>%s", PlayerRight.getCrown(recipient), Utility.formatName(recipient.getName())), 33208));
                    p.interfaceManager.openInventory(InterfaceConstants.SECOND_TRADE_SCREEN, 3213);
                });
                break;
        }
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), getItemNames(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.InterfaceConstants.INVENTORY_INTERFACE, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.item_containers, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.game.world.InterfaceConstants.SECOND_TRADE_SCREEN, and updateOfferComponents().
Referenced by accept(), and onRequest().
updateOfferComponents()
void com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents ()
Updates the itemcontainer when an item is offered or removed.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 209 of file TradeSession.java.
{
        this.lastOfferModification.reset();
        this.setAttachment(null);
        forEach(p -> {
            Player recipient = p.getName().equals(player.getName()) ? this.other : this.player;
            int remaining = recipient.inventory.remaining();
            this.item_containers.get(p).refresh(p, InterfaceConstants.PLAYER_TRADE_CONTAINER);
            this.item_containers.get(p).refresh(recipient, InterfaceConstants.OTHER_TRADE_CONTAINER);
            p.send(new SendItemOnInterface(3322, p.inventory.toArray()));
            p.send(new SendString(String.format("Trading with: %s %s", PlayerRight.getCrown(recipient), Utility.formatName(recipient.getName())), 33002));
            p.send(new SendString(Utility.formatName(recipient.getName()), 33003));
            p.send(new SendString("has " + remaining + " free", 33004));
            p.send(new SendString("inventory spaces", 33005));
            // p = current player being looped
            // recipient = the other player (not the player being looped)
            // don't use player and other object because those are the cached values.
//            long difference = this.item_containers.get(p).containerValue(PriceType.VALUE)  - this.item_containers.get(recipient).containerValue(PriceType.VALUE);
//            System.out.println("difference = " + difference);FIXME
//            p.send(new SendString(difference == 0 ? "<col=ffffff> Absolutely nothing!" : "<col=ffffff> " + difference, 33018));
            p.send(new SendString(this.item_containers.get(p).containerValue(PriceType.VALUE) == 0 ? "Nothing." : Utility.formatDigits(this.item_containers.get(p).containerValue(PriceType.VALUE)) + " gp", 33019));
            p.send(new SendString(this.item_containers.get(recipient).containerValue(PriceType.VALUE) == 0 ? "Nothing." : Utility.formatDigits(this.item_containers.get(recipient).containerValue(PriceType.VALUE)) + " gp", 33020));
            p.send(new SendString("", 33029));
            p.send(new SendString("", 33030));
            p.interfaceManager.openInventory(InterfaceConstants.FIRST_TRADE_SCREEN, 3321);
        });
    }
References com.runehive.game.world.InterfaceConstants.FIRST_TRADE_SCREEN, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.item_containers, com.runehive.game.world.InterfaceConstants.OTHER_TRADE_CONTAINER, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.game.world.InterfaceConstants.PLAYER_TRADE_CONTAINER, com.runehive.game.world.items.containers.ItemContainer.remaining(), com.runehive.util.Stopwatch.reset(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.setAttachment(), and com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE.
Referenced by updateMainComponents().
Member Data Documentation
lastOfferModification
final Stopwatch com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.lastOfferModification = Stopwatch.start() private
The stopwatch which blocks the player from further continueing the session if a second hasn't passed after the last item has been added.
Definition at line 31 of file TradeSession.java.
Referenced by accept().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/exchange/trade/TradeSession.java