RuneHive-Game: com.runehive.game.world.entity.combat.accuracy.RangeAccuracy Class Reference
com.runehive.game.world.entity.combat.accuracy.RangeAccuracy Class Reference
@Author Origin 2/22/2023
Static Public Member Functions
static double getAttackRoll (Mob attacker)
static int getDefenceBonus (Mob defender)
static double getDefenceRoll (Mob defender)
static double getEffectiveLevel (Mob attacker)
static double getPrayerAttackBonus (Mob attacker)
static double getPrayerDefenseBonus (Mob defender)
static int getRangeBonus (Mob attacker)
static int getRangeLevel (Mob attacker)
static boolean successful (Mob attacker, Mob defender)
Static Public Attributes
static final SecureRandom srand = new SecureRandom()
Detailed Description
@Author Origin 2/22/2023
Definition at line 18 of file RangeAccuracy.java.
Member Function Documentation
getAttackRoll()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getAttackRoll (Mob attacker) static
Definition at line 104 of file RangeAccuracy.java.
{
        double effectiveLevel = getEffectiveLevel(attacker);
        double bonus = getRangeBonus(attacker);
        double roll = effectiveLevel * (bonus + 64);
        if (attacker instanceof Player player) {
            final Equipment equipment = player.equipment;
            if (equipment.contains(25865)
                    || equipment.contains(25867)
                    || equipment.contains(25884)
                    || equipment.contains(25886)
                    || equipment.contains(25888)
                    || equipment.contains(25890)
                    || equipment.contains(25892)
                    || equipment.contains(25894)
                    || equipment.contains(25896)) {
                if (equipment.contains(23971)) {
                    roll *= 1.05;
                }
                if (equipment.contains(23975)) {
                    roll *= 1.15;
                }
                if (equipment.contains(23975)) {
                    roll *= 1.10;
                }
            }
        }
        return Math.floor(roll);
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), getEffectiveLevel(), and getRangeBonus().
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.modifyAccuracy(), successful(), and com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.successful().
getDefenceBonus()
int com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getDefenceBonus (Mob defender) static
Definition at line 100 of file RangeAccuracy.java.
{
        return defender.getBonus(Equipment.RANGED_DEFENSE);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), and com.runehive.game.world.items.containers.equipment.Equipment.RANGED_DEFENSE.
Referenced by getDefenceRoll().
getDefenceRoll()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getDefenceRoll (Mob defender) static
Definition at line 136 of file RangeAccuracy.java.
{
        double defenceLevel = defender.skills.getLevel(Skill.DEFENCE);
        double defenceBonus = getDefenceBonus(defender);
        if (defender instanceof Player) {
            defenceLevel *= getPrayerDefenseBonus(defender);
            switch (defender.getCombat().getFightType().getStyle()) {
                case DEFENSIVE -> defenceLevel += 3;
                case CONTROLLED -> defenceLevel += 1;
            }
        } else {
            defenceLevel += 9;
        }
        return defenceLevel * (defenceBonus + 64);
    }
References com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.Mob.getCombat(), getDefenceBonus(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), getPrayerDefenseBonus(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by successful(), and com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.successful().
getEffectiveLevel()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getEffectiveLevel (Mob attacker) static
Definition at line 61 of file RangeAccuracy.java.
{
        double effectiveLevel = getRangeLevel(attacker);
        if (attacker instanceof Player) {
            effectiveLevel *= getPrayerAttackBonus(attacker);
            effectiveLevel = Math.floor(effectiveLevel);
            switch (attacker.getCombat().getFightType().getStyle()) {
                case ACCURATE -> effectiveLevel += 3;
                case CONTROLLED -> effectiveLevel += 1;
            }
        }
        effectiveLevel += 8;
        if (attacker instanceof Player player) {
            if (FormulaUtils.voidRanger(player)) {
                effectiveLevel *= 1.10;
            }
        }
        return Math.floor(effectiveLevel);
    }
References com.runehive.game.world.entity.mob.Mob.getCombat(), getPrayerAttackBonus(), getRangeLevel(), and com.runehive.game.world.entity.combat.FormulaUtils.voidRanger().
Referenced by getAttackRoll().
getPrayerAttackBonus()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus (Mob attacker) static
Definition at line 38 of file RangeAccuracy.java.
{
        double prayerBonus = 1;
        if (attacker.getStrategy().getCombatType().equals(CombatType.RANGED)) {
            if (attacker.prayer.isActive(Prayer.SHARP_EYE))
                prayerBonus *= 1.05D; // 5% range level boost
            else if (attacker.prayer.isActive(Prayer.HAWK_EYE))
                prayerBonus *= 1.10D; // 10% range level boost
            else if (attacker.prayer.isActive(Prayer.EAGLE_EYE))
                prayerBonus *= 1.15D; // 15% range level boost
            else if (attacker.prayer.isActive(Prayer.RIGOUR))
                prayerBonus *= 1.20D; // 20% range level boost
        }
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.EAGLE_EYE, com.runehive.game.world.entity.mob.Mob.getStrategy(), com.runehive.game.world.entity.mob.prayer.Prayer.HAWK_EYE, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.combat.CombatType.RANGED, com.runehive.game.world.entity.mob.prayer.Prayer.RIGOUR, and com.runehive.game.world.entity.mob.prayer.Prayer.SHARP_EYE.
Referenced by getEffectiveLevel().
getPrayerDefenseBonus()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerDefenseBonus (Mob defender) static
Definition at line 53 of file RangeAccuracy.java.
{
        double prayerBonus = 1;
        if (defender.prayer.isActive(Prayer.RIGOUR)) {
            prayerBonus *= 1.25D;
        }
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.prayer, and com.runehive.game.world.entity.mob.prayer.Prayer.RIGOUR.
Referenced by getDefenceRoll().
getRangeBonus()
int com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getRangeBonus (Mob attacker) static
Definition at line 96 of file RangeAccuracy.java.
{
        return attacker.getBonus(Equipment.RANGED_OFFENSE);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), and com.runehive.game.world.items.containers.equipment.Equipment.RANGED_OFFENSE.
Referenced by getAttackRoll().
getRangeLevel()
int com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getRangeLevel (Mob attacker) static
Definition at line 83 of file RangeAccuracy.java.
{
        int rangeLevel = 1;
        if (attacker instanceof Npc npc) {
            int[] skills = npc.definition.getSkills();
            if (skills != null) {
                rangeLevel = skills[Skill.RANGED];
            }
        } else {
            rangeLevel = attacker.skills.getLevel(Skill.RANGED);
        }
        return rangeLevel;
    }
References com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.RANGED, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by getEffectiveLevel().
successful()
boolean com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.successful (Mob attacker, Mob defender) static
Definition at line 22 of file RangeAccuracy.java.
{
        double attackRoll = getAttackRoll(attacker);
        double defenceRoll = getDefenceRoll(defender);
        double chance;
        if (attackRoll > defenceRoll)
            chance = 1D - (defenceRoll + 2D) / (2D * (attackRoll + 1D));
        else
            chance = attackRoll / (2D * (defenceRoll + 1D));
        double roll = srand.nextDouble();
        return chance > roll;
    }
References getAttackRoll(), getDefenceRoll(), and srand.
Referenced by com.runehive.game.world.entity.combat.attack.FormulaFactory.isAccurate().
Member Data Documentation
srand
final SecureRandom com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.srand = new SecureRandom() static
Definition at line 20 of file RangeAccuracy.java.
Referenced by successful().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/accuracy/RangeAccuracy.java