RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow Class Reference
com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow Class Reference
Handles the magic shortbow weapon special attack.
Public Member Functions
CombatHit[] getHits (Player attacker, Mob defender)
void hit (Player attacker, Mob defender, Hit hit)
int modifyDamage (Player attacker, Mob defender, int roll)
void onKill (Player attacker, Mob defender, Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy
void attack (Player attacker, Mob defender, Hit hit)
boolean canAttack (Player attacker, Mob defender)
Animation getAttackAnimation (Player attacker, Mob defender)
int getAttackDelay (Player attacker, Mob defender, FightType fightType)
int getAttackDistance (Player attacker, FightType fightType)
CombatType getCombatType ()
void start (Player attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static DarkBow get ()
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions
void sendStuff (Player attacker, Mob defender)
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy
PlayerRangedStrategy ()
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Package Functions
[static initializer]
Private Member Functions
DarkBow ()
Static Private Member Functions
static boolean isDragonArrow (Item item)
static void setProjectiles (CombatProjectile darkness, CombatProjectile dragons)
Static Private Attributes
static Projectile DARKNESS_PROJECTILE_1
static Projectile DARKNESS_PROJECTILE_2
static Projectile DRAGONS_PROJECTILE_1
static Projectile DRAGONS_PROJECTILE_2
static final DarkBow INSTANCE = new DarkBow()
Additional Inherited Members
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Handles the magic shortbow weapon special attack.
Author
Daniel
Michaael | Chex
Definition at line 24 of file DarkBow.java.
Constructor & Destructor Documentation
DarkBow()
com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.DarkBow () private
Definition at line 43 of file DarkBow.java.
                      {
    }
Referenced by get().
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.[static initializer] static package
References DRAGONS_PROJECTILE_2, com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition(), and setProjectiles().
get()
DarkBow com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.get () static
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 130 of file DarkBow.java.
{
        return INSTANCE;
    }
References DarkBow(), and INSTANCE.
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.getHits (Player attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 70 of file DarkBow.java.
{
        CombatHit first = nextRangedHit(attacker, defender);
        CombatHit second = nextRangedHit(attacker, defender);
        int minimum = isDragonArrow(attacker.equipment.get(ARROWS_SLOT)) ? 8 : 5;
        if (first.getDamage() < minimum) {
            first.setDamage(minimum);
            first.setAccurate(true);
        }
        if (second.getDamage() < minimum) {
            second.setDamage(minimum);
            second.setAccurate(true);
        }
        return new CombatHit[] { first, second };
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.combat.hit.Hit.getDamage(), isDragonArrow(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit(), com.runehive.game.world.entity.combat.hit.Hit.setAccurate(), and com.runehive.game.world.entity.combat.hit.Hit.setDamage().
hit()
void com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.hit (Player attacker, Mob defender, Hit hit)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 60 of file DarkBow.java.
{
        if (isDragonArrow(attacker.equipment.get(ARROWS_SLOT))) {
            defender.graphic(new Graphic(1100, true, UpdatePriority.HIGH));
        } else {
            defender.graphic(new Graphic(1103, true, UpdatePriority.HIGH));
        }
        super.hit(attacker, defender, hit);
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.UpdatePriority.HIGH, hit(), and isDragonArrow().
Referenced by hit(), and onKill().
isDragonArrow()
boolean com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.isDragonArrow (Item item) static private
Definition at line 122 of file DarkBow.java.
{
        if (item != null) {
            int id = item.getId();
            return id == 11212 || id == 11227 || id == 11228 || id == 11229;
        }
        return false;
    }
References com.runehive.game.world.items.Item.getId().
Referenced by getHits(), hit(), modifyDamage(), and sendStuff().
modifyDamage()
int com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.modifyDamage (Player attacker, Mob defender, int roll)
Definition at line 89 of file DarkBow.java.
{
        if (isDragonArrow(attacker.equipment.get(ARROWS_SLOT)))
            return roll * 3 / 2;
        return roll * 13 / 10;
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), and isDragonArrow().
onKill()
void com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.onKill (Player attacker, Mob defender, Hit hit)
Definition at line 96 of file DarkBow.java.
{
        if (defender.isPlayer()) {
            AchievementHandler.activate(attacker, AchievementKey.DARKBOW_SPEC);
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.content.achievement.AchievementKey.DARKBOW_SPEC, hit(), and com.runehive.game.world.entity.mob.Mob.isPlayer().
sendStuff()
void com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.sendStuff (Player attacker, Mob defender) protected
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 47 of file DarkBow.java.
{
        super.sendStuff(attacker, defender);
        if (isDragonArrow(attacker.equipment.get(ARROWS_SLOT))) {
            DRAGONS_PROJECTILE_1.send(attacker, defender);
            DRAGONS_PROJECTILE_2.send(attacker, defender);
        } else {
            DARKNESS_PROJECTILE_1.send(attacker, defender);
            DARKNESS_PROJECTILE_2.send(attacker, defender);
        }
    }
References DARKNESS_PROJECTILE_1, DARKNESS_PROJECTILE_2, DRAGONS_PROJECTILE_1, DRAGONS_PROJECTILE_2, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), and isDragonArrow().
setProjectiles()
void com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.setProjectiles (CombatProjectile darkness, CombatProjectile dragons) static private
Definition at line 102 of file DarkBow.java.
{
        if (!darkness.getProjectile().isPresent())
            throw new NullPointerException("No Decent of Darkness projectile found.");
        DARKNESS_PROJECTILE_1 = darkness.getProjectile().get();
        DARKNESS_PROJECTILE_2 = DARKNESS_PROJECTILE_1.copy();
        DARKNESS_PROJECTILE_2.setDuration(15 + DARKNESS_PROJECTILE_2.getDuration());
        DARKNESS_PROJECTILE_2.setCurve(32);
        if (!dragons.getProjectile().isPresent())
            throw new NullPointerException("No Decent of Dragons projectile found.");
        DRAGONS_PROJECTILE_1 = dragons.getProjectile().get().copy();
        DRAGONS_PROJECTILE_2 = DRAGONS_PROJECTILE_1.copy();
        DRAGONS_PROJECTILE_2.setDuration(15 + DRAGONS_PROJECTILE_1.getDuration());
        DRAGONS_PROJECTILE_2.setCurve(32);
    }
References DARKNESS_PROJECTILE_1, DARKNESS_PROJECTILE_2, DRAGONS_PROJECTILE_1, DRAGONS_PROJECTILE_2, and com.runehive.game.world.entity.combat.projectile.CombatProjectile.getProjectile().
Referenced by [static initializer]().
Member Data Documentation
DARKNESS_PROJECTILE_1
Projectile com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.DARKNESS_PROJECTILE_1 static private
Definition at line 27 of file DarkBow.java.
Referenced by sendStuff(), and setProjectiles().
DARKNESS_PROJECTILE_2
Projectile com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.DARKNESS_PROJECTILE_2 static private
Definition at line 28 of file DarkBow.java.
Referenced by sendStuff(), and setProjectiles().
DRAGONS_PROJECTILE_1
Projectile com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.DRAGONS_PROJECTILE_1 static private
Definition at line 30 of file DarkBow.java.
Referenced by sendStuff(), and setProjectiles().
DRAGONS_PROJECTILE_2
Projectile com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.DRAGONS_PROJECTILE_2 static private
Definition at line 31 of file DarkBow.java.
Referenced by [static initializer](), sendStuff(), and setProjectiles().
INSTANCE
final DarkBow com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.INSTANCE = new DarkBow() static private
Definition at line 25 of file DarkBow.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/special/range/DarkBow.java