RuneHive-Game: com.runehive.content.activity.impl.kraken.KrakenActivity Class Reference
com.runehive.content.activity.impl.kraken.KrakenActivity Class Reference
Handles the Kraken boss.
Public Member Functions
void add (Mob mob)
Adds a mob to the activity.
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
void remove (Mob mob)
Removes a mob from the activity.
void transform (Npc npc, int transform)
Handles transforming a Npc.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
ActivityDeathType deathType ()
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
void update ()
The update method.
Static Public Member Functions
static KrakenActivity create (Player player)
Creates a new Kraken activity.
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Public Attributes
int count = 0
The whirlpool activated count.
Npc kraken = null
The Kraken npc.
Protected Member Functions
boolean clickObject (Player player, ObjectInteractionEvent event)
Optional< KrakenActivityListener > getListener ()
Gets an Optional of the ActivityListener for this activity.
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
KrakenActivity (Player player, int instance)
Constructs a new KrakenActivity.
Private Attributes
boolean completed
Flag if kraken has been defeated.
final KrakenActivityListener listener = new KrakenActivityListener(this)
The Kraken activity listener.
final Player player
The player fighting the Kraken.
Set< Npc > tentacles = new HashSet<>()
Set of npc tentacles.
Static Private Attributes
static final int[][] SPAWN
Holds all the monster spawn information.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Handles the Kraken boss.
Author
Daniel
Definition at line 34 of file KrakenActivity.java.
Constructor & Destructor Documentation
KrakenActivity()
com.runehive.content.activity.impl.kraken.KrakenActivity.KrakenActivity (Player player, int instance) private
Constructs a new KrakenActivity.
Definition at line 64 of file KrakenActivity.java.
{
        super(1, instance);
        this.player = player;
    }
References com.runehive.content.activity.Activity.instance, and player.
Referenced by clickObject(), create(), and finish().
Member Function Documentation
add()
void com.runehive.content.activity.impl.kraken.KrakenActivity.add (Mob mob)
Adds a mob to the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 108 of file KrakenActivity.java.
{
        super.add(mob);
        if (mob.isNpc()) {
            if (mob.getNpc().id == 496) {
                kraken = mob.getNpc();
            } else {
                tentacles.add(mob.getNpc());
            }
            mob.locking.lock();
        }
    }
References com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.isNpc(), kraken, com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, and tentacles.
Referenced by create(), and start().
canTeleport()
boolean com.runehive.content.activity.impl.kraken.KrakenActivity.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 162 of file KrakenActivity.java.
{
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.kraken.KrakenActivity.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 186 of file KrakenActivity.java.
{
        count = 0;
        if (kraken != null && kraken.isRegistered())
            kraken.unregister();
        Iterator<Npc> it = tentacles.iterator();
        while (it.hasNext()) {
            Npc npc = it.next();
            npc.animate(npc.definition.getDeathAnimation());
            World.schedule(3, npc::unregister);
            it.remove();
        }
    }
References com.runehive.game.world.entity.mob.Mob.animate(), count, com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getDeathAnimation(), kraken, com.runehive.game.world.World.schedule(), and tentacles.
Referenced by finish(), onDeath(), onLogout(), and onRegionChange().
clickObject()
boolean com.runehive.content.activity.impl.kraken.KrakenActivity.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 200 of file KrakenActivity.java.
{
        if (event.getObject().getId() != 538)
            return false;
        player.dialogueFactory.sendOption("Restart Kraken instance", () -> {
            remove(player);
            Teleportation.teleport(player, new Position(2280, 10031, 0), TeleportationData.CREVICE, () -> KrakenActivity.create(player));
        }, "Leave Kraken Instance", () -> {
            remove(player);
            Teleportation.activateOverride(player, Config.DEFAULT_POSITION, TeleportationData.CREVICE);
        }).execute();
        return true;
    }
References com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride(), com.runehive.content.skill.impl.magic.teleport.TeleportationData.CREVICE, com.runehive.Config.DEFAULT_POSITION, KrakenActivity(), player, and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
create()
KrakenActivity com.runehive.content.activity.impl.kraken.KrakenActivity.create (Player player) static
Creates a new Kraken activity.
Definition at line 70 of file KrakenActivity.java.
{
        KrakenActivity minigame = new KrakenActivity(player, player.playerAssistant.instance());
        minigame.add(player);
        player.gameRecord.start();
        minigame.count = 0;
        return minigame;
    }
References add(), KrakenActivity(), and player.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity().
finish()
void com.runehive.content.activity.impl.kraken.KrakenActivity.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 167 of file KrakenActivity.java.
{
        cleanup();
        if (completed) {
            AchievementHandler.activate(player, AchievementKey.KRAKEN);
            player.send(new SendMessage("Congratulations, you have killed the Kraken. Fight duration: @red@" + Utility.getTime(player.gameRecord.end(ActivityType.KRAKEN)) + "</col>."));
        } else {
            player.gameRecord.end(ActivityType.KRAKEN, false);
        }
        remove(player);
        World.schedule(10, () -> {
            if(Area.inKraken(player)) {
                KrakenActivity.create(player);
            }
        });
    }
References com.runehive.content.achievement.AchievementHandler.activate(), cleanup(), completed, com.runehive.util.Utility.getTime(), com.runehive.game.world.position.Area.inKraken(), com.runehive.content.achievement.AchievementKey.KRAKEN, com.runehive.content.activity.ActivityType.KRAKEN, KrakenActivity(), player, and com.runehive.game.world.World.schedule().
Referenced by onLogout(), and onRegionChange().
getListener()
Optional< KrakenActivityListener > com.runehive.content.activity.impl.kraken.KrakenActivity.getListener () protected
Gets an Optional of the ActivityListener for this activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 219 of file KrakenActivity.java.
{
        return Optional.of(listener);
    }
References listener.
getType()
ActivityType com.runehive.content.activity.impl.kraken.KrakenActivity.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 214 of file KrakenActivity.java.
{
        return ActivityType.KRAKEN;
    }
References com.runehive.content.activity.ActivityType.KRAKEN.
onDeath()
void com.runehive.content.activity.impl.kraken.KrakenActivity.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 90 of file KrakenActivity.java.
{
        if (mob.isPlayer() && mob.equals(player)) {
            player.send(new SendMessage("Better luck next time old chap!"));
            cleanup();
            remove(player);
            return;
        }
        if (mob.isNpc() && mob.getNpc().id == 494) {
            World.schedule(new NpcDeath(mob.getNpc(), () -> {
                completed = true;
                finish();
            }));
            return;
        }
        super.onDeath(mob);
    }
References cleanup(), com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), player, and com.runehive.game.world.World.schedule().
onLogout()
void com.runehive.content.activity.impl.kraken.KrakenActivity.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 147 of file KrakenActivity.java.
{
        player.move(Config.DEFAULT_POSITION);
        cleanup();
        finish();
    }
References cleanup(), com.runehive.Config.DEFAULT_POSITION, finish(), and player.
onRegionChange()
void com.runehive.content.activity.impl.kraken.KrakenActivity.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 154 of file KrakenActivity.java.
{
        if (!Area.inKraken(player)) {
            cleanup();
            finish();
        }
    }
References cleanup(), finish(), com.runehive.game.world.position.Area.inKraken(), and player.
remove()
void com.runehive.content.activity.impl.kraken.KrakenActivity.remove (Mob mob)
Removes a mob from the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 121 of file KrakenActivity.java.
{
        if (!mob.isNpc()) {
            super.remove(mob);
            return;
        }
        int id = mob.getNpc().id;
        if (id == 496) {
            kraken = null;
        } else {
            tentacles.remove(mob.getNpc());
        }
        super.remove(mob);
    }
References kraken, and tentacles.
start()
void com.runehive.content.activity.impl.kraken.KrakenActivity.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 136 of file KrakenActivity.java.
{
        for (int[] aSPAWN : SPAWN) {
            Npc npc = new Npc(aSPAWN[0], new Position(aSPAWN[1], aSPAWN[2]));
            npc.owner = player;
            add(npc);
        }
        player.face(kraken.getPosition());
        pause();
    }
References add(), kraken, com.runehive.content.activity.Activity.pause(), player, and SPAWN.
transform()
void com.runehive.content.activity.impl.kraken.KrakenActivity.transform (Npc npc, int transform)
Handles transforming a Npc.
Definition at line 79 of file KrakenActivity.java.
{
        npc.transform(transform);
        npc.npcAssistant.login();
        if (transform == 5535)
            count++;
        if (transform == 494)
            npc.animate(new Animation(7135, UpdatePriority.HIGH));
        npc.getCombat().attack(player);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), count, com.runehive.game.world.entity.mob.npc.Npc.getCombat(), com.runehive.game.UpdatePriority.HIGH, com.runehive.game.world.entity.mob.npc.NpcAssistant.login(), com.runehive.game.world.entity.mob.npc.Npc.npcAssistant, player, transform(), and com.runehive.game.world.entity.mob.Mob.transform().
Referenced by transform().
Member Data Documentation
completed
boolean com.runehive.content.activity.impl.kraken.KrakenActivity.completed private
Flag if kraken has been defeated.
Definition at line 46 of file KrakenActivity.java.
Referenced by finish().
count
int com.runehive.content.activity.impl.kraken.KrakenActivity.count = 0
The whirlpool activated count.
Definition at line 43 of file KrakenActivity.java.
Referenced by cleanup(), and transform().
kraken
Npc com.runehive.content.activity.impl.kraken.KrakenActivity.kraken = null
The Kraken npc.
Definition at line 40 of file KrakenActivity.java.
Referenced by add(), cleanup(), remove(), and start().
listener
final KrakenActivityListener com.runehive.content.activity.impl.kraken.KrakenActivity.listener = new KrakenActivityListener(this) private
The Kraken activity listener.
Definition at line 52 of file KrakenActivity.java.
Referenced by getListener().
player
final Player com.runehive.content.activity.impl.kraken.KrakenActivity.player private
The player fighting the Kraken.
Definition at line 37 of file KrakenActivity.java.
Referenced by canTeleport(), clickObject(), create(), finish(), KrakenActivity(), onDeath(), onLogout(), onRegionChange(), start(), and transform().
SPAWN
final int [][] com.runehive.content.activity.impl.kraken.KrakenActivity.SPAWN static private
Initial value:
= {
            {493, 2276, 10038},
            {493, 2276, 10034},
            {496, 2278, 10035},
            {493, 2283, 10038},
            {493, 2283, 10034},
    }
Holds all the monster spawn information.
Definition at line 55 of file KrakenActivity.java.
{
            {493, 2276, 10038},
            {493, 2276, 10034},
            {496, 2278, 10035},
            {493, 2283, 10038},
            {493, 2283, 10034},
    };
Referenced by start().
tentacles
Set<Npc> com.runehive.content.activity.impl.kraken.KrakenActivity.tentacles = new HashSet<>() private
Set of npc tentacles.
Definition at line 49 of file KrakenActivity.java.
Referenced by add(), cleanup(), and remove().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/kraken/KrakenActivity.java