RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob > Class Template Reference
com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob > Class Template Reference
Public Member Functions
void attack (T attacker, Mob defender, Hit hit)
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
boolean canAttack (T attacker, Mob defender)
boolean canOtherAttack (Mob attacker, T defender)
void finishIncoming (Mob attacker, T defender)
void finishOutgoing (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
void hitsplat (T attacker, Mob defender, Hit hit)
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
void onKill (T attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, T defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
void start (T attacker, Mob defender, Hit[] hits)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Static Public Attributes
static final CombatListener< Mob > CANT_ATTACK
Detailed Description
Definition at line 7 of file SimplifiedListener.java.
Member Function Documentation
attack()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.attack (T attacker, Mob defender, Hit hit)
Definition at line 35 of file SimplifiedListener.java.
{ }
References hit().
block()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.block (Mob attacker, T defender, Hit hit, CombatType combatType)
Definition at line 41 of file SimplifiedListener.java.
{ }
References hit().
canAttack()
boolean com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.canAttack (T attacker, Mob defender)
Definition at line 27 of file SimplifiedListener.java.
{
        return true;
    }
canOtherAttack()
boolean com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.canOtherAttack (Mob attacker, T defender)
Definition at line 22 of file SimplifiedListener.java.
{
        return true;
    }
finishIncoming()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.finishIncoming (Mob attacker, T defender)
Definition at line 61 of file SimplifiedListener.java.
{ }
finishOutgoing()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.finishOutgoing (T attacker, Mob defender)
Definition at line 64 of file SimplifiedListener.java.
{ }
hit()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.hit (T attacker, Mob defender, Hit hit)
Definition at line 38 of file SimplifiedListener.java.
{ }
References hit().
Referenced by attack(), com.runehive.game.world.entity.combat.attack.listener.item.ElysianListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block(), com.runehive.game.world.entity.combat.attack.listener.npc.Alkahrid.block(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.block(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.block(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.block(), block(), com.runehive.game.world.entity.combat.attack.listener.npc.Ahrim.FireBlast.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Gowler.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.handleRecoil(), hit(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.hitsplat(), hitsplat(), onDamage(), onDeath(), com.runehive.game.world.entity.combat.attack.listener.item.DharokListener.onKill(), onKill(), preDeath(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill(), and preKill().
hitsplat()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.hitsplat (T attacker, Mob defender, Hit hit)
Definition at line 57 of file SimplifiedListener.java.
{
    }
References hit().
onDamage()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.onDamage (T defender, Hit hit)
Definition at line 67 of file SimplifiedListener.java.
{
    }
References hit().
onDeath()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.onDeath (Mob attacker, T defender, Hit hit)
Definition at line 47 of file SimplifiedListener.java.
{ }
References hit().
onKill()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.onKill (T attacker, Mob defender, Hit hit)
Definition at line 54 of file SimplifiedListener.java.
{ }
References hit().
preDeath()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.preDeath (Mob attacker, T defender, Hit hit)
Definition at line 44 of file SimplifiedListener.java.
{ }
References hit().
preKill()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.preKill (Mob attacker, Mob defender, Hit hit)
Reimplemented in com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.
Definition at line 50 of file SimplifiedListener.java.
{
    }
References hit().
start()
void com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.start (T attacker, Mob defender, Hit[] hits)
Definition at line 32 of file SimplifiedListener.java.
{ }
withinDistance()
boolean com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.withinDistance (T attacker, Mob defender)
Definition at line 17 of file SimplifiedListener.java.
{
        return true;
    }
Member Data Documentation
CANT_ATTACK
final CombatListener<Mob> com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >.CANT_ATTACK static
Initial value:
= new SimplifiedListener<Mob>() {
        @Override
        public boolean canAttack(Mob attacker, Mob defender) {
            return false;
        }
    }
Definition at line 9 of file SimplifiedListener.java.
{
        @Override
        public boolean canAttack(Mob attacker, Mob defender) {
            return false;
        }
    };
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/SimplifiedListener.java