RuneHive-Game: com.runehive.game.service.DonationService Class Reference
com.runehive.game.service.DonationService Class Reference
Static Public Member Functions
static void claimDonation (Player player)
Private Member Functions
DonationService ()
Static Private Attributes
static final String CONNECTION_STRING = "jdbc:mysql://173.82.152.23:3306/osroyjs_store_2"
static final Logger logger = LogManager.getLogger(DonationService.class)
static final String PASS = "3AXbU=W7IfzX"
static final String USER = "osroyjs_exo1"
Detailed Description
Definition at line 13 of file DonationService.java.
Constructor & Destructor Documentation
DonationService()
com.runehive.game.service.DonationService.DonationService () private
Definition at line 19 of file DonationService.java.
{
    }
Member Function Documentation
claimDonation()
void com.runehive.game.service.DonationService.claimDonation (Player player) static
Definition at line 23 of file DonationService.java.
{
        if (!player.databaseRequest.elapsed(1, TimeUnit.MINUTES)) {
            player.dialogueFactory.sendNpcChat(5523,"You can only check our database once every 1 minute!").execute();
            return;
        }
        if (!player.inventory.isEmpty()) {
            player.dialogueFactory.sendNpcChat(5523, Expression.SAD, "You must have an empty inventory to do this!").execute();
            return;
        }
        player.dialogueFactory.sendStatement("Checking request...").execute();
        boolean claimed = false;
        player.databaseRequest.reset();
        try(Connection connection = DriverManager.getConnection(CONNECTION_STRING, USER, PASS);
            PreparedStatement sta = connection.prepareStatement("SELECT * FROM payments WHERE player_name = ? AND status='Completed' AND claimed=0", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
            sta.setString(1, player.getName().replace("_", " "));
            ResultSet rs = sta.executeQuery();
            while(rs.next()) {
                final int itemNumber = rs.getInt("item_number");
                final int quantity = rs.getInt("quantity");
                switch(itemNumber) {
                    //$10 DONATOR BOND
                    case 10:
                        if (player.inventory.add(new Item(DonatorBond.BOND_10.item, quantity))) {
                            claimed = true;
                        }
                        break;
                    //$50 DONATOR BOND
                    case 20:
                        if (player.inventory.add(new Item(DonatorBond.BOND_50.item, quantity))) {
                            claimed = true;
                        }
                        break;
                    //$100 DONATOR BOND
                    case 21:
                        if (player.inventory.add(new Item(DonatorBond.BOND_100.item, quantity))) {
                            claimed = true;
                        }
                        break;
                    //$200 DONATOR BOND
                    case 22:
                        if (player.inventory.add(new Item(DonatorBond.BOND_200.item, quantity))) {
                            claimed = true;
                        }
                        break;
                    //$500 DONATOR BOND
                    case 23:
                        if (player.inventory.add(new Item(DonatorBond.BOND_500.item, quantity))) {
                            claimed = true;
                        }
                        break;
                }
                if (claimed) {
                    rs.updateInt("claimed", 1);
                    rs.updateRow();
                }
            }
            if (!claimed) {
                player.dialogueFactory.sendNpcChat(5523,"There is no donation reward for you to claim!").execute();
            } else {
                player.dialogueFactory.sendNpcChat(5523,"Thank-you for your donation!").execute();
            }
        } catch (SQLException ex) {
            logger.error(String.format("Failed to claim donation for player=%s", player.getName()), ex);
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.content.donators.DonatorBond.BOND_10, com.runehive.content.donators.DonatorBond.BOND_100, com.runehive.content.donators.DonatorBond.BOND_200, com.runehive.content.donators.DonatorBond.BOND_50, com.runehive.content.donators.DonatorBond.BOND_500, CONNECTION_STRING, com.runehive.game.world.entity.mob.player.Player.databaseRequest, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.util.Stopwatch.elapsed(), com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.ItemContainer.isEmpty(), logger, PASS, com.runehive.util.Stopwatch.reset(), com.runehive.content.dialogue.Expression.SAD, com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and USER.
Member Data Documentation
CONNECTION_STRING
final String com.runehive.game.service.DonationService.CONNECTION_STRING = "jdbc:mysql://173.82.152.23:3306/osroyjs_store_2" static private
Definition at line 17 of file DonationService.java.
Referenced by claimDonation().
logger
final Logger com.runehive.game.service.DonationService.logger = LogManager.getLogger(DonationService.class) static private
Definition at line 14 of file DonationService.java.
Referenced by claimDonation().
PASS
final String com.runehive.game.service.DonationService.PASS = "3AXbU=W7IfzX" static private
Definition at line 16 of file DonationService.java.
Referenced by claimDonation().
USER
final String com.runehive.game.service.DonationService.USER = "osroyjs_exo1" static private
Definition at line 15 of file DonationService.java.
Referenced by claimDonation().
The documentation for this class was generated from the following file:
java/com/runehive/game/service/DonationService.java