RuneHive-Game: com.runehive.game.world.pathfinding.path.impl.Node Class Reference
com.runehive.game.world.pathfinding.path.impl.Node Class Reference
A Entity representing a weighted Position.
Public Member Functions
void close ()
Closes this Entity.
int compareTo (Node other)
Compares the Entity's cost with another.
final boolean equals (Object obj)
Gets the condition if the Entity equals another object.
Position getPosition ()
Gets the Position this Entity represents.
final int hashCode ()
Gets the node's hash code.
boolean isOpen ()
Returns whether or not this Node is openShop.
Package Functions
int getCost ()
Gets the cost of this Entity.
Node getParent ()
Gets the parent Entity of this Entity.
boolean hasParent ()
Returns whether or not this Entity has a parent Entity.
Node (Position position)
Creates the Entity with the specified Position and cost.
void setCost (int cost)
Sets the cost of this Entity.
void setParent (Node parent)
Sets the parent Entity of this Entity.
Private Member Functions
Node (Position position, int cost)
Creates the Entity with the specified Position and cost.
Private Attributes
int cost
The cost of this Entity.
boolean open = true
Whether or not this Entity is openShop.
Node parent
The parent Entity of this Entity.
final Position position
The Position of this Entity.
Detailed Description
A Entity representing a weighted Position.
Author
Graham
Major
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Definition at line 186 of file AStarPathFinder.java.
Constructor & Destructor Documentation
Node() [1/2]
com.runehive.game.world.pathfinding.path.impl.Node.Node (Position position) package
Creates the Entity with the specified Position and cost.
Parameters
position The Position.
Definition at line 205 of file AStarPathFinder.java.
{
        this(position, 0);
    }
References position.
Referenced by compareTo(), equals(), getParent(), and setParent().
Node() [2/2]
com.runehive.game.world.pathfinding.path.impl.Node.Node (Position position, int cost) private
Creates the Entity with the specified Position and cost.
Parameters
position The Position.
cost The cost of the Entity.
Definition at line 215 of file AStarPathFinder.java.
{
        this.position = position;
        this.cost = cost;
    }
References cost, and position.
Member Function Documentation
close()
void com.runehive.game.world.pathfinding.path.impl.Node.close ()
Closes this Entity.
Definition at line 241 of file AStarPathFinder.java.
{
        open = false;
    }
References open.
Referenced by com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.compare(), and com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find().
compareTo()
int com.runehive.game.world.pathfinding.path.impl.Node.compareTo (Node other)
Compares the Entity's cost with another.
Parameters
other The other Entity to check.
Returns
The differential Integer.
Definition at line 299 of file AStarPathFinder.java.
{
        return Integer.compare(cost, other.cost);
    }
References cost, and Node().
equals()
final boolean com.runehive.game.world.pathfinding.path.impl.Node.equals (Object obj)
Gets the condition if the Entity equals another object.
Parameters
obj The object to be checked.
Returns
true if it's the same as the object, false otherwise.
Definition at line 311 of file AStarPathFinder.java.
{
        if (this == obj) return true;
        if (!(obj instanceof Node)) return false;
        Node other = (Node) obj;
        return getPosition().getX() == other.getPosition().getX()
            && getPosition().getY() == other.getPosition().getY()
            && getPosition().getHeight() == other.getPosition().getHeight()
            && getCost() == other.getCost()
            && getParent().getCost() == other.getParent().getCost()
            && getParent().getPosition().getX() == other.getParent().getPosition().getX()
            && getParent().getPosition().getY() == other.getParent().getPosition().getY()
            && getParent().getPosition().getHeight() == other.getPosition().getHeight();
    }
References getCost(), com.runehive.game.world.position.Position.getHeight(), getParent(), getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), and Node().
getCost()
int com.runehive.game.world.pathfinding.path.impl.Node.getCost () package
Gets the cost of this Entity.
Returns
The cost.
Definition at line 234 of file AStarPathFinder.java.
                  {
        return cost;
    }
References cost.
Referenced by com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.compare(), and equals().
getParent()
Node com.runehive.game.world.pathfinding.path.impl.Node.getParent () package
Gets the parent Entity of this Entity.
Returns
The parent Entity.
Exceptions
NoSuchElementException If this Entity does not have a parent.
Definition at line 269 of file AStarPathFinder.java.
                     {
        return parent;
    }
References Node(), and parent.
Referenced by equals(), and com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find().
getPosition()
Position com.runehive.game.world.pathfinding.path.impl.Node.getPosition ()
Gets the Position this Entity represents.
Returns
The position.
Definition at line 288 of file AStarPathFinder.java.
{
        return position;
    }
References position.
Referenced by com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.compare(), equals(), and com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find().
hashCode()
final int com.runehive.game.world.pathfinding.path.impl.Node.hashCode ()
Gets the node's hash code.
Returns
hash code.
Definition at line 331 of file AStarPathFinder.java.
{
        final int prime = 31;
        int result = 1;
        result = prime * result + position.getX();
        result = prime * result + position.getY();
        result = prime * result + position.getHeight();
        if (hasParent()) {
            Position p = parent.getPosition();
            result = prime * result + p.getX();
            result = prime * result + p.getY();
            result = prime * result + p.getHeight();
        }
        result = prime * result + cost;
        return result;
    }
References cost, com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), hasParent(), parent, and position.
hasParent()
boolean com.runehive.game.world.pathfinding.path.impl.Node.hasParent () package
Returns whether or not this Entity has a parent Entity.
Returns
true if this Entity has a parent Entity, otherwise
false.
Definition at line 279 of file AStarPathFinder.java.
{
        return parent != null;
    }
References parent.
Referenced by com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find(), and hashCode().
isOpen()
boolean com.runehive.game.world.pathfinding.path.impl.Node.isOpen ()
Returns whether or not this Node is openShop.
Returns
true if this Entity is openShop, otherwise false.
Definition at line 250 of file AStarPathFinder.java.
{
        return open;
    }
References open.
Referenced by com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.compare(), and com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.getCheapest().
setCost()
void com.runehive.game.world.pathfinding.path.impl.Node.setCost (int cost) package
Sets the cost of this Entity.
Parameters
cost The cost.
Definition at line 225 of file AStarPathFinder.java.
{
        this.cost = cost;
    }
References cost.
Referenced by com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.compare().
setParent()
void com.runehive.game.world.pathfinding.path.impl.Node.setParent (Node parent) package
Sets the parent Entity of this Entity.
Parameters
parent The parent Entity. May be null.
Definition at line 259 of file AStarPathFinder.java.
{
        this.parent = parent;
    }
References Node(), and parent.
Referenced by com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.compare().
Member Data Documentation
cost
int com.runehive.game.world.pathfinding.path.impl.Node.cost private
The cost of this Entity.
Definition at line 189 of file AStarPathFinder.java.
Referenced by compareTo(), getCost(), hashCode(), Node(), and setCost().
open
boolean com.runehive.game.world.pathfinding.path.impl.Node.open = true private
Whether or not this Entity is openShop.
Definition at line 192 of file AStarPathFinder.java.
Referenced by close(), and isOpen().
parent
Node com.runehive.game.world.pathfinding.path.impl.Node.parent private
The parent Entity of this Entity.
Definition at line 195 of file AStarPathFinder.java.
Referenced by getParent(), hashCode(), hasParent(), and setParent().
position
final Position com.runehive.game.world.pathfinding.path.impl.Node.position private
The Position of this Entity.
Definition at line 198 of file AStarPathFinder.java.
Referenced by getPosition(), hashCode(), Node(), and Node().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/pathfinding/path/impl/AStarPathFinder.java