RuneHive-Game: com.runehive.game.world.items.containers.ItemContainer Class Reference
com.runehive.game.world.items.containers.ItemContainer Class Reference
An abstraction game representing a group of Items.
Classes
class ItemContainerIterator
An Iterator implementation for this container.
enum StackPolicy
An enumerated type defining policies for stackable Items.
Public Member Functions
boolean add (int id, int amount)
Attempts to deposit item into this container.
boolean add (Item item)
Attempts to deposit item into this container.
boolean add (Item item, boolean refresh, boolean stack)
boolean add (Item item, int preferredIndex, boolean refresh)
boolean add (Item item, int preferredIndex, boolean refresh, boolean stack)
Attempts to deposit item into this container, preferably at preferredIndex.
boolean add (Item item, int slot)
Attempts to deposit item into this container.
boolean addAll (Collection<? extends Item > items)
Attempts to deposit items in bulk into this container.
boolean addAll (Item... items)
Attempts to deposit items in bulk into this container.
boolean addAll (ItemContainer items)
Attempts to deposit items in bulk into this container.
final boolean addListener (ItemContainerListener listener)
Adds an ItemContainerListener to this container.
boolean allowZero ()
final int capacity ()
void clear ()
Removes all of the items from this container.
final void clear (boolean refresh)
Removes all of the items from this container.
final int computeAmountForId (int id)
Computes the total quantity of the Items in this container with id.
final int computeFreeIndex ()
Computes the next free (null) index in this container.
final Optional< Integer > computeIdForIndex (int index)
Computes the identifier of the Item on index.
final int computeIndexCount (Item... forItems)
Computes the amount of indexes required to hold items in this container.
final int computeIndexForId (int id)
Computes the first index found that id is in.
long containerValue (PriceType type)
Gets the total worth of the container using the item's values.
boolean contains (int id)
Determines if this container contains id.
final boolean contains (int id, int amount)
final boolean contains (Item item)
final boolean containsAll (Collection< Item > items)
final boolean containsAll (int... identifiers)
Determines if this container contains all identifiers.
final boolean containsAll (Item... items)
final boolean containsAny (Collection< Item > items)
final boolean containsAny (int... identifiers)
Determines if this container contains any identifiers.
final boolean containsAny (Item... items)
final ItemContainer copy ()
Creates a copy of the underlying item container.
final void fireBulkItemsUpdatedEvent ()
Fires the ItemContainerListener.bulkItemsUpdated(ItemContainer) event.
final void fireCapacityExceededEvent ()
Fires the ItemContainerListener.capacityExceeded(ItemContainer) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh)
Fires the ItemContainerListener.itemUpdated(ItemContainer, int) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh, boolean login)
final void forEach (Consumer<? super Item > action)
Iterates through all of the Items within this container and performs action on them, skipping empty indexes (null values) as they are encountered.
final Item get (int index)
Gets the Item located on index.
int getFreeSlots ()
final int getId (int index)
Gets the item id located on index.
Item[] getItems ()
int getSlotById (int id)
Gets a slot by id.
double getWeight ()
Gets the weight of the container.
final boolean hasCapacityAfter (Item[] add, Item... remove)
Creates a copy of the underlying container and removes the items specified from it and after tries to deposit the specified items to it.
final boolean hasCapacityFor (Item... item)
Determines if this container has the capacity for item.
final void ifPresent (int index, Consumer< Item > action)
Consumes an action if the index is a valid item index in this container.
final boolean indexFree (int index)
Returns true if index is not occupied (null).
final boolean indexOccupied (int index)
Returns true if index is occupied (non-null).
final void insert (int oldIndex, int newIndex, boolean refresh)
final boolean isEmpty ()
final boolean isFull ()
ItemContainer (int capacity, StackPolicy policy)
Creates a new ItemContainer.
ItemContainer (int capacity, StackPolicy policy, Item[] items)
Creates a new ItemContainer.
final Iterator< Item > iterator ()
void onRefresh ()
Any functionality that should occur when refreshed.
final StackPolicy policy ()
void refresh (Player player, int widget)
Sends the items on the itemcontainer.
final int remaining ()
boolean remove (int id)
boolean remove (int id, int amount)
boolean remove (Item item)
Attempts to withdraw item from this container.
boolean remove (Item item, int preferredIndex)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean remove (Item item, int preferredIndex, boolean refresh)
boolean remove (Item item, int preferredIndex, boolean refresh, boolean removeAll)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean removeAll (Collection<? extends Item > items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (Item... items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (ItemContainer items)
Attempts to withdraw items in bulk from this container.
final boolean removeListener (ItemContainerListener listener)
Removes an ItemContainerListener from this container.
final boolean replace (int oldId, int newId, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (int oldId, int newId, int index, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (Item first, Item second, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replaceAll (int oldId, int newId)
Replaces all occurrences of Items having the identifier
oldId with newId.
final Optional< Item > retrieve (int index)
Retrieves the item located on index.
Optional< Item > search (int id)
Searches and returns the first item found with id.
Optional< Item > search (Item item)
Searches and returns the first item found with id and
amount.
void set (int index, Item item, boolean refresh)
Sets the index to item.
final void set (Item[] toSet)
void setFiringEvents (boolean firingEvents)
Sets the value for firingEvents.
final void setItems (Item[] items)
final void setItems (Item[] items, boolean copy)
Sets the container of items to items.
void shift ()
Percolates the null indices to the end of the stack.
final int size ()
final Spliterator< Item > spliterator ()
final Stream< Item > stream ()
final void swap (boolean insert, int oldIndex, int newIndex, boolean refresh)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex, boolean refresh)
final Item[] toArray ()
Returns a shallow copy of the backing array.
final Item[] toNonNullArray ()
final void transfer (int firstIndex, int secondIndex, ItemContainer other, boolean refresh)
Private Attributes
final int capacity
The capacity of this container.
boolean firingEvents = true
If events are currently being fired.
Item[] items
The Items within this container.
final List< ItemContainerListener > listeners = new ArrayList<>()
An ArrayList of ItemContainerListeners listening for various events.
final StackPolicy policy
The policy of this container.
Detailed Description
An abstraction game representing a group of Items.
Author
lare96 http://github.com/lare96
Definition at line 24 of file ItemContainer.java.
Constructor & Destructor Documentation
ItemContainer() [1/2]
com.runehive.game.world.items.containers.ItemContainer.ItemContainer (int capacity, StackPolicy policy, Item[] items)
Creates a new ItemContainer.
Definition at line 113 of file ItemContainer.java.
{
        this.capacity = capacity;
        this.policy = policy;
        this.items = items;
    }
References capacity, items, and policy.
Referenced by addAll(), com.runehive.game.world.items.containers.bank.Bank.BankListener.bulkItemsUpdated(), com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.bulkItemsUpdated(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.bulkItemsUpdated(), copy(), com.runehive.game.world.items.containers.bank.DonatorDeposit.DonatorDeposit(), hasCapacityAfter(), com.runehive.game.world.items.containers.ItemContainer.ItemContainerIterator.ItemContainerIterator(), com.runehive.game.world.items.containers.bank.Bank.BankListener.itemUpdated(), com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.itemUpdated(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.itemUpdated(), removeAll(), transfer(), and com.runehive.game.world.items.containers.equipment.Equipment.unequip().
ItemContainer() [2/2]
com.runehive.game.world.items.containers.ItemContainer.ItemContainer (int capacity, StackPolicy policy)
Creates a new ItemContainer.
Definition at line 120 of file ItemContainer.java.
{
        this(capacity, policy, new Item[capacity]);
    }
References capacity, and policy.
Member Function Documentation
add() [1/6]
boolean com.runehive.game.world.items.containers.ItemContainer.add (int id, int amount)
Attempts to deposit item into this container.
Parameters
id the id of the item.
amount the amount of the item.
Returns
true the item was added, false if there was not enough space left.
Definition at line 188 of file ItemContainer.java.
{
        return add(new Item(id, amount));
    }
References add().
add() [2/6]
boolean com.runehive.game.world.items.containers.ItemContainer.add (Item item)
Attempts to deposit item into this container.
Parameters
item The Item to deposit.
Returns
true the Item was added, false if there was not enough space left.
Definition at line 164 of file ItemContainer.java.
{
        return add(item, -1, true);
    }
References add().
Referenced by add(), add(), add(), add(), add(), addAll(), com.runehive.content.wintertodt.Wintertodt.award(), com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.itemaction.impl.CelestialRing.charge(), com.runehive.game.service.DonationService.claimDonation(), com.runehive.content.pet.Pets.claimLostPets(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.thieving.WallSafe.crack(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.content.CrystalChest.createKey(), com.runehive.content.gambling.GambleManager.decline(), com.runehive.content.shootingstar.ShootingStarData.decreaseDust(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.DonatorDeposit.deposit(), com.runehive.game.world.items.containers.impl.LootingBag.deposit(), com.runehive.game.world.items.containers.impl.LostUntradeables.deposit(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), com.runehive.content.skill.impl.hunter.trap.TrapManager.dismantle(), com.runehive.content.itemaction.impl.CelestialRing.drop(), com.runehive.content.itemaction.impl.CrawsBow.drop(), com.runehive.content.itemaction.impl.ThammaronsSceptre.drop(), com.runehive.content.itemaction.impl.ViggorasChainmace.drop(), com.runehive.content.bags.ItemBag.empty(), com.runehive.content.combat.cannon.CannonManager.empty(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.game.action.impl.FlaxPickingAction.execute(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.gambling.GambleManager.give(), com.runehive.content.lms.LMSGame.giveChestItems(), com.runehive.content.skill.impl.hunter.trap.TrapManager.handleLogout(), hasCapacityAfter(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.combat.cannon.CannonManager.logout(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.pet.Pets.onObtain(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.combat.cannon.CannonManager.pickup(), com.runehive.content.store.Store.purchase(), com.runehive.content.store.currency.impl.ItemCurrency.recieveCurrency(), replace(), replace(), replace(), com.runehive.content.lms.LMSGame.resupplyKiller(), com.runehive.content.skill.impl.woodcutting.BirdsNest.search(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), com.runehive.content.itemaction.impl.MagmaHelm.uncharge(), com.runehive.content.itemaction.impl.SerpentineHelm.uncharge(), com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge(), com.runehive.content.itemaction.impl.TridentOfTheSeas.uncharge(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.uncharge(), com.runehive.game.world.items.containers.equipment.Equipment.unequip(), com.runehive.content.itemaction.impl.ToxicBlowpipe.unload(), and com.runehive.content.gambling.GambleManager.withdraw().
add() [3/6]
boolean com.runehive.game.world.items.containers.ItemContainer.add (Item item, boolean refresh, boolean stack)
Definition at line 192 of file ItemContainer.java.
{
        return add(item, -1, refresh, stack);
    }
References add(), and refresh().
add() [4/6]
boolean com.runehive.game.world.items.containers.ItemContainer.add (Item item, int preferredIndex, boolean refresh)
Reimplemented in com.runehive.game.world.items.containers.equipment.Equipment.
Definition at line 196 of file ItemContainer.java.
{
        return add(item, preferredIndex, refresh, false);
    }
References add(), and refresh().
add() [5/6]
boolean com.runehive.game.world.items.containers.ItemContainer.add (Item item, int preferredIndex, boolean refresh, boolean stack)
Attempts to deposit item into this container, preferably at preferredIndex.
Parameters
item The Item to deposit.
preferredIndex The preferable index to deposit item to.
refresh The condition if we will be refreshing our container.
Returns
true if the Item was added, false if there was not enough space left.
Definition at line 211 of file ItemContainer.java.
{
        checkArgument(preferredIndex >= -1, "invalid index identifier");
        item = item.copy();
        boolean stackable = stack || (policy.equals(StackPolicy.STANDARD) && item.isStackable()) || policy.equals(StackPolicy.ALWAYS);
        if (stackable && !stack) {
            preferredIndex = computeIndexForId(item.getId());
        } else if (preferredIndex != -1) {
            preferredIndex = items[preferredIndex] != null ? -1 : preferredIndex;
        }
        preferredIndex = preferredIndex == -1 ? computeFreeIndex() : preferredIndex;
        if (preferredIndex == -1) { // Not enough space in container.
            fireCapacityExceededEvent();
            return false;
        }
        if (stackable) {
            Item current = items[preferredIndex];
            items[preferredIndex] = (current == null) ? item : current.createAndIncrement(item.getAmount());
            fireItemUpdatedEvent(current, items[preferredIndex], preferredIndex, refresh);
        } else {
            int remaining = remaining();
            int until = (remaining > item.getAmount()) ? item.getAmount() : remaining;
            for (int index = 0; index < until; index++) {
                preferredIndex = (preferredIndex > capacity || preferredIndex < 0 || items[preferredIndex] == null) ? preferredIndex : computeFreeIndex();
                if (preferredIndex == -1) {//Couldn't find an empty spot.
                    fireCapacityExceededEvent();
                    return false;
                }
                item.setAmount(1);
                items[preferredIndex] = item;
                fireItemUpdatedEvent(null, item, preferredIndex++, refresh);
            }
        }
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.StackPolicy.ALWAYS, capacity, computeFreeIndex(), computeIndexForId(), com.runehive.game.world.items.Item.copy(), com.runehive.game.world.items.Item.createAndIncrement(), fireCapacityExceededEvent(), fireItemUpdatedEvent(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.isStackable(), items, policy, refresh(), remaining(), com.runehive.game.world.items.Item.setAmount(), and com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD.
add() [6/6]
boolean com.runehive.game.world.items.containers.ItemContainer.add (Item item, int slot)
Attempts to deposit item into this container.
Parameters
item The Item to deposit.
slot The slot to deposit the item too.
Returns
true the Item was added, false if there was not enough space left.
Definition at line 176 of file ItemContainer.java.
{
        return add(item, slot, true);
    }
References add().
addAll() [1/3]
boolean com.runehive.game.world.items.containers.ItemContainer.addAll (Collection<? extends Item > items)
Attempts to deposit items in bulk into this container.
Parameters
items The Items to deposit.
Returns
true if at least 1 of the Items were added, false if none could be added.
Definition at line 261 of file ItemContainer.java.
{
        if (items.size() == 1) { // Bulk operation on singleton list? No thanks..
            Optional<? extends Item> item = items.stream().
                    filter(Objects::nonNull).
                    findFirst();
            return item.isPresent() && add(item.get());
        }
        firingEvents = false;
        boolean added = false;
        try {
            for (Item item : items) {
                if (item == null) {
                    continue;
                }
                if (add(item, -1, false)) {
                    added = true;
                }
            }
        } finally {
            firingEvents = true;
        }
        fireBulkItemsUpdatedEvent();
        return added;
    }
References add(), fireBulkItemsUpdatedEvent(), firingEvents, and items.
Referenced by addAll(), addAll(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.reward().
addAll() [2/3]
boolean com.runehive.game.world.items.containers.ItemContainer.addAll (Item... items)
Attempts to deposit items in bulk into this container.
Parameters
items The Items to deposit.
Returns
true if at least 1 of the Items were added, false if none could be added.
Definition at line 295 of file ItemContainer.java.
{
        return addAll(Arrays.asList(items));
    }
References addAll(), and items.
addAll() [3/3]
boolean com.runehive.game.world.items.containers.ItemContainer.addAll (ItemContainer items)
Attempts to deposit items in bulk into this container.
Parameters
items The Items to deposit.
Returns
true if at least 1 of the Items were added, false if none could be added.
Definition at line 306 of file ItemContainer.java.
{
        return addAll(items.items);
    }
References addAll(), ItemContainer(), and items.
addListener()
final boolean com.runehive.game.world.items.containers.ItemContainer.addListener (ItemContainerListener listener)
Adds an ItemContainerListener to this container.
Parameters
listener The listener to deposit to this container.
Returns
true if the listener was added, false otherwise.
Definition at line 1124 of file ItemContainer.java.
{
        return listeners.add(listener);
    }
References listeners.
Referenced by com.runehive.game.world.items.containers.bank.Bank.Bank(), com.runehive.game.world.items.containers.equipment.Equipment.Equipment(), com.runehive.game.world.items.containers.inventory.Inventory.Inventory(), com.runehive.game.world.items.containers.impl.LootingBag.LootingBag(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceChecker().
allowZero()
boolean com.runehive.game.world.items.containers.ItemContainer.allowZero ()
Returns
this policy checks if the container will allow empty items
Reimplemented in com.runehive.game.world.items.containers.bank.Bank.
Definition at line 1210 of file ItemContainer.java.
{
        return false;
    }
Referenced by remove().
capacity()
final int com.runehive.game.world.items.containers.ItemContainer.capacity ()
Returns
the total amount of used and free indices
Definition at line 1200 of file ItemContainer.java.
{
        return capacity;
    }
References capacity.
clear() [1/2]
void com.runehive.game.world.items.containers.ItemContainer.clear ()
Removes all of the items from this container.
Reimplemented in com.runehive.game.world.items.containers.bank.Bank, and com.runehive.game.world.items.containers.equipment.Equipment.
Definition at line 1098 of file ItemContainer.java.
{
        clear(true);
    }
References clear().
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), clear(), com.runehive.game.world.items.containers.bank.DonatorDeposit.close(), com.runehive.game.world.items.containers.impl.LostUntradeables.close(), com.runehive.game.world.items.containers.bank.DonatorDeposit.confirm(), com.runehive.content.gambling.GambleManager.decline(), com.runehive.content.gambling.GambleManager.give(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.lms.LMSGame.reset(), setItems(), and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.withdrawAll().
clear() [2/2]
final void com.runehive.game.world.items.containers.ItemContainer.clear (boolean refresh)
Removes all of the items from this container.
Definition at line 1103 of file ItemContainer.java.
{
        Arrays.fill(items, null);
        if (refresh)
            fireBulkItemsUpdatedEvent();
    }
References fireBulkItemsUpdatedEvent(), items, and refresh().
computeAmountForId()
final int com.runehive.game.world.items.containers.ItemContainer.computeAmountForId (int id)
Computes the total quantity of the Items in this container with id.
Parameters
id The identifier of the Item to determine the total quantity of.
Returns
The total quantity.
Definition at line 548 of file ItemContainer.java.
{
        int amount = 0;
        for (Item item : items) {
            if (item == null || item.getId() != id)
                continue;
            amount += item.getAmount();
        }
        return amount;
    }
References items.
Referenced by com.runehive.content.itemaction.impl.CelestialRing.charge(), com.runehive.content.itemaction.impl.CrawsBow.charge(), com.runehive.content.itemaction.impl.ThammaronsSceptre.charge(), com.runehive.content.itemaction.impl.ViggorasChainmace.charge(), com.runehive.content.tradingpost.TradingPostListing.checkAndUpdate(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.store.currency.impl.ItemCurrency.currencyAmount(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.wintertodt.Wintertodt.fletch(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.itemaction.impl.CelestialRing.inventory(), com.runehive.content.itemaction.impl.CelestialRing.itemOnItem(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.combat.cannon.CannonManager.load(), com.runehive.content.wintertodt.Wintertodt.mixHerb(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), remove(), com.runehive.content.store.Store.sell(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), com.runehive.content.itemaction.impl.ToxicBlowpipe.unload(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), com.runehive.content.skill.impl.herblore.Herblore.useItem(), com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem(), com.runehive.game.world.items.containers.bank.DonatorDeposit.withdraw(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdraw(), and com.runehive.game.world.items.containers.impl.LootingBag.withdrawBank().
computeFreeIndex()
final int com.runehive.game.world.items.containers.ItemContainer.computeFreeIndex ()
Computes the next free (null) index in this container.
Returns
The free index, -1 if no free indexes could be found.
Definition at line 515 of file ItemContainer.java.
{
        for (int index = 0; index < capacity; index++) {
            if (items[index] == null) {
                return index;
            }
        }
        return -1;
    }
References capacity, and items.
Referenced by add().
computeIdForIndex()
final Optional< Integer > com.runehive.game.world.items.containers.ItemContainer.computeIdForIndex (int index)
Computes the identifier of the Item on index.
Parameters
index The index to compute the identifier for.
Returns
The identifier wrapped in an optional.
Definition at line 564 of file ItemContainer.java.
{
        return retrieve(index).map(Item::getId);
    }
References com.runehive.game.world.items.Item.getId(), and retrieve().
computeIndexCount()
final int com.runehive.game.world.items.containers.ItemContainer.computeIndexCount (Item... forItems)
Computes the amount of indexes required to hold items in this container.
Parameters
forItems The items to compute the index count for.
Returns
The index count.
Definition at line 667 of file ItemContainer.java.
{
        int indexCount = 0;
        for (Item item : forItems) {
            if (item == null)
                continue;
            boolean stackable = (policy.equals(StackPolicy.STANDARD) && item.isStackable()) || policy.equals(StackPolicy.ALWAYS);
            if (stackable) {
                int index = computeIndexForId(item.getId());
                if (index == -1) {
                    indexCount++;
                    continue;
                }
                Item existing = items[index];
                if ((existing.getAmount() + item.getAmount()) <= 0) {
                    indexCount++;
                }
            } else {
                indexCount += item.getAmount();
            }
        }
        return indexCount;
    }
References com.runehive.game.world.items.containers.ItemContainer.StackPolicy.ALWAYS, computeIndexForId(), com.runehive.game.world.items.Item.getAmount(), items, policy, and com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD.
Referenced by hasCapacityFor().
computeIndexForId()
final int com.runehive.game.world.items.containers.ItemContainer.computeIndexForId (int id)
Computes the first index found that id is in.
Parameters
id The identifier to compute for.
Returns
The first index found, -1 if no Item with
id is in this container.
Definition at line 531 of file ItemContainer.java.
{
        for (int index = 0; index < capacity; index++) {
            if (items[index] != null && items[index].getId() == id) {
                return index;
            }
        }
        return -1;
    }
References capacity, getId(), and items.
Referenced by add(), computeIndexCount(), com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), remove(), replace(), replace(), com.runehive.game.world.items.containers.bank.Bank.withdraw(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdraw().
containerValue()
long com.runehive.game.world.items.containers.ItemContainer.containerValue (PriceType type)
Gets the total worth of the container using the item's values.
Returns
The total container worth.
Definition at line 490 of file ItemContainer.java.
{
        long value = 0;
        for (final Item item : items) {
            if (item == null) {
                continue;
            }
            int price = item.getValue(type);
            if (value >= Long.MAX_VALUE - price * item.getAmount()) {
                return Long.MAX_VALUE;
            }
            value += price * item.getAmount();
        }
        return value;
    }
References items.
Referenced by com.runehive.game.world.items.containers.impl.LootingBag.onRefresh(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.onRefresh(), com.runehive.content.ItemsKeptOnDeath.open(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.reward().
contains() [1/3]
boolean com.runehive.game.world.items.containers.ItemContainer.contains (int id)
Determines if this container contains id.
Parameters
id The identifier to check this container for.
Returns
true if this container has id, false otherwise.
Definition at line 726 of file ItemContainer.java.
{
        for (Item item : items) {
            if (item != null && id == item.getId()) {
                return true;
            }
        }
        return false;
    }
References items.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.pet.Pets.buyInsurance(), com.runehive.content.store.currency.impl.ItemCurrency.canRecieveCurrency(), com.runehive.content.skill.impl.HarvestingSkillAction.canRun(), com.runehive.content.pet.Pets.claimLostPets(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.agility.Agility.clickButton(), com.runehive.content.skill.impl.smithing.Smithing.clickObject(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.contains(), contains(), containsAll(), containsAll(), containsAll(), containsAny(), containsAny(), containsAny(), com.runehive.game.world.entity.combat.magic.MagicRune.containsCombo(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), com.runehive.content.wintertodt.Wintertodt.fletch(), com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), com.runehive.content.skill.impl.mining.PickaxeData.getBestPickaxe(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefender(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefenderIndex(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.content.skill.impl.runecrafting.Runecraft.getEssence(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.game.world.entity.combat.FormulaUtils.hasAmuletOfAvarice(), com.runehive.content.skill.impl.fishing.Fishing.hasFishingItems(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.game.world.entity.combat.FormulaUtils.hasThammaronSceptre(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), com.runehive.content.combat.cannon.CannonManager.load(), com.runehive.game.world.entity.combat.FormulaUtils.obbyArmour(), com.runehive.content.pet.Pets.onObtain(), com.runehive.content.skill.impl.crafting.impl.Tanning.open(), com.runehive.content.store.Store.purchase(), com.runehive.content.skill.impl.thieving.WallSafe.rate(), com.runehive.content.lms.LMSGame.rollChest(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.skill.impl.fishing.Fishing.success(), com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), com.runehive.game.world.items.containers.bank.Bank.withdraw(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdraw().
contains() [2/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.contains (int id, int amount)
Returns
true if this container has id with amount
Definition at line 773 of file ItemContainer.java.
{
        for (Item item : items) {
            if (item != null && id == item.getId()) {
                amount -= item.getAmount();
                if (amount <= 0) return true;
            }
        }
        return false;
    }
References items.
contains() [3/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.contains (Item item)
Returns
true if this container has the item
Definition at line 768 of file ItemContainer.java.
{
        return item != null && contains(item.getId(), item.getAmount());
    }
References contains(), com.runehive.game.world.items.Item.getAmount(), and com.runehive.game.world.items.Item.getId().
containsAll() [1/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.containsAll (Collection< Item > items)
Returns
true if this container has all items
Definition at line 794 of file ItemContainer.java.
{
        for (Item item : items) {
            if (!contains(item)) {
                return false;
            }
        }
        return true;
    }
References contains(), and items.
containsAll() [2/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.containsAll (int... identifiers)
Determines if this container contains all identifiers.
Parameters
identifiers The identifiers to check this container for.
Returns
true if this container has all identifiers, false otherwise.
Definition at line 742 of file ItemContainer.java.
{
        for (int id : identifiers) {
            if (!contains(id)) {
                return false;
            }
        }
        return true;
    }
References contains().
Referenced by com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.addListener(), com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), com.runehive.content.skill.impl.HarvestingSkillAction.canRun(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.content.CrystalChest.createKey(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.skill.impl.farming.Farming.getBonus(), com.runehive.content.skill.impl.firemaking.Firemaking.getBonus(), com.runehive.content.skill.impl.fishing.Fishing.getBonus(), com.runehive.content.skill.impl.woodcutting.Woodcutting.getBonus(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.removeListener(), com.runehive.content.skill.impl.crafting.Crafting.start(), and com.runehive.content.skill.impl.fletching.Fletching.start().
containsAll() [3/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.containsAll (Item... items)
Returns
true if this container has all items
Definition at line 784 of file ItemContainer.java.
{
        for (Item item : items) {
            if (!contains(item)) {
                return false;
            }
        }
        return true;
    }
References contains(), and items.
containsAny() [1/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.containsAny (Collection< Item > items)
Returns
true if this container has all items
Definition at line 814 of file ItemContainer.java.
{
        for (Item item : items) {
            if (contains(item)) {
                return true;
            }
        }
        return false;
    }
References contains(), and items.
containsAny() [2/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.containsAny (int... identifiers)
Determines if this container contains any identifiers.
Parameters
identifiers The identifiers to check this container for.
Returns
true if this container has any identifiers, false otherwise.
Definition at line 758 of file ItemContainer.java.
{
        for (int id : identifiers) {
            if (contains(id)) {
                return true;
            }
        }
        return false;
    }
References contains().
Referenced by com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.addListener(), com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.items.containers.equipment.Equipment.hasArmadyl(), com.runehive.game.world.items.containers.equipment.Equipment.hasBandos(), com.runehive.game.world.items.containers.equipment.Equipment.hasRow(), com.runehive.game.world.items.containers.equipment.Equipment.hasSaradomin(), com.runehive.game.world.items.containers.equipment.Equipment.hasShayzien(), com.runehive.game.world.items.containers.equipment.Equipment.hasZamorak(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.removeListener(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), and com.runehive.content.skill.impl.mining.Mining.success().
containsAny() [3/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.containsAny (Item... items)
Returns
true if this container has all items
Definition at line 804 of file ItemContainer.java.
{
        for (Item item : items) {
            if (contains(item)) {
                return true;
            }
        }
        return false;
    }
References contains(), and items.
copy()
final ItemContainer com.runehive.game.world.items.containers.ItemContainer.copy ()
Creates a copy of the underlying item container.
Returns
a copy of the unterlying item container.
Definition at line 1091 of file ItemContainer.java.
{
        ItemContainer container = new ItemContainer(this.capacity, this.policy, this.toArray());
        this.listeners.forEach(container::addListener);
        return container;
    }
References ItemContainer(), and toArray().
Referenced by com.runehive.content.skill.impl.ProducingSkillAction.canRun(), and setItems().
fireBulkItemsUpdatedEvent()
final void com.runehive.game.world.items.containers.ItemContainer.fireBulkItemsUpdatedEvent ()
Fires the ItemContainerListener.bulkItemsUpdated(ItemContainer) event.
Definition at line 1158 of file ItemContainer.java.
{
        if (firingEvents) {
            listeners.forEach(evt -> evt.bulkItemsUpdated(this));
        }
    }
References firingEvents, and listeners.
Referenced by addAll(), clear(), removeAll(), replaceAll(), and setItems().
fireCapacityExceededEvent()
final void com.runehive.game.world.items.containers.ItemContainer.fireCapacityExceededEvent ()
Fires the ItemContainerListener.capacityExceeded(ItemContainer) event.
Definition at line 1168 of file ItemContainer.java.
{
        if (firingEvents) {
            listeners.forEach(evt -> evt.capacityExceeded(this));
        }
    }
References firingEvents, and listeners.
Referenced by add(), and com.runehive.content.skill.impl.ProducingSkillAction.canRun().
fireItemUpdatedEvent() [1/2]
final void com.runehive.game.world.items.containers.ItemContainer.fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh)
Fires the ItemContainerListener.itemUpdated(ItemContainer, int) event.
Definition at line 1144 of file ItemContainer.java.
{
        fireItemUpdatedEvent(oldItem, newItem, index, refresh, false);
    }
References fireItemUpdatedEvent(), and refresh().
Referenced by add(), fireItemUpdatedEvent(), com.runehive.game.world.items.containers.equipment.Equipment.login(), remove(), set(), and swap().
fireItemUpdatedEvent() [2/2]
final void com.runehive.game.world.items.containers.ItemContainer.fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh, boolean login)
Definition at line 1148 of file ItemContainer.java.
{
        if (firingEvents) {
            listeners.forEach(evt -> evt.itemUpdated(this, Optional.ofNullable(oldItem), Optional.ofNullable(newItem), index, refresh, login));
        }
    }
References firingEvents, listeners, and refresh().
forEach()
final void com.runehive.game.world.items.containers.ItemContainer.forEach (Consumer<? super Item > action)
Iterates through all of the Items within this container and performs action on them, skipping empty indexes (null values) as they are encountered.
Definition at line 130 of file ItemContainer.java.
{
        Objects.requireNonNull(action);
        for (Item item : items) {
            if (item != null) {
                action.accept(item);
            }
        }
    }
References items.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems().
get()
final Item com.runehive.game.world.items.containers.ItemContainer.get (int index)
Gets the Item located on index.
Parameters
index The index to get the Item on.
Returns
The Item instance, null if the index is empty.
Definition at line 1030 of file ItemContainer.java.
{
        if (index >= 0 && index < items.length)
            return items[index];
        return null;
    }
References items.
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack(), com.runehive.game.action.impl.BuryBoneAction.BuryBoneAction(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.getHits(), com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnItem(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handleSecondOption(), com.runehive.net.packet.in.ItemOptionPacketListener.handleThirdOption(), com.runehive.content.wintertodt.Wintertodt.healPyromancer(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.hit(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.hit(), com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.modifyDamage(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.game.action.impl.ScatterAshAction.ScatterAshAction(), com.runehive.content.store.Store.sell(), com.runehive.content.store.Store.sendSellValue(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.sendStuff(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.emote.Emote.skillcape(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), transfer(), com.runehive.content.emote.EmoteHandler.updateSkillcape(), com.runehive.content.skill.impl.herblore.Herblore.useItem(), com.runehive.content.gambling.GambleManager.withdraw(), and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.withdrawAll().
getFreeSlots()
int com.runehive.game.world.items.containers.ItemContainer.getFreeSlots ()
Returns
the amount of free slots available in the container
Definition at line 1190 of file ItemContainer.java.
{
        return capacity() - size();
    }
References capacity, and size().
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.canSet(), com.runehive.content.wintertodt.Wintertodt.chopRoot(), com.runehive.content.pet.Pets.claimLostPets(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.bags.ItemBag.empty(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.lms.LMSGame.giveChestItems(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), com.runehive.content.bot.botclass.impl.PureMelee.hit(), com.runehive.content.bot.botclass.impl.ZerkerMelee.hit(), isFull(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.lms.LMSGame.resupplyKiller(), com.runehive.content.activity.impl.duelarena.DuelRule.set(), com.runehive.content.wintertodt.Wintertodt.takeHerb(), com.runehive.content.itemaction.impl.ToxicBlowpipe.unload(), and com.runehive.content.gambling.GambleManager.withdraw().
getId()
final int com.runehive.game.world.items.containers.ItemContainer.getId (int index)
Gets the item id located on index.
Parameters
index The index to get the Item on.
Returns
The Item instance, null if the index is empty.
Definition at line 1042 of file ItemContainer.java.
{
        if (items[index] == null) {
            return -1;
        }
        return items[index].getId();
    }
References items.
Referenced by computeIndexForId(), com.runehive.content.skill.impl.farming.Farming.getBonus(), com.runehive.content.skill.impl.firemaking.Firemaking.getBonus(), com.runehive.content.skill.impl.fishing.Fishing.getBonus(), com.runehive.content.skill.impl.mining.Mining.getBonus(), com.runehive.content.skill.impl.woodcutting.Woodcutting.getBonus(), getSlotById(), com.runehive.content.wintertodt.Wintertodt.healPyromancer(), and remove().
getItems()
Item[] com.runehive.game.world.items.containers.ItemContainer.getItems ()
Returns
The item array in this container.
Definition at line 1175 of file ItemContainer.java.
{
        return items;
    }
References items.
Referenced by com.runehive.game.world.items.containers.bank.DonatorDeposit.close(), com.runehive.game.world.items.containers.bank.DonatorDeposit.confirm(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.depositeAll(), com.runehive.content.bags.ItemBag.fill(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.game.world.items.containers.equipment.Equipment.login(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.game.world.items.containers.impl.LostUntradeables.onRefresh(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.onRefresh(), com.runehive.content.gambling.GambleManager.open(), com.runehive.content.wintertodt.Wintertodt.removeGameItems(), com.runehive.content.lms.LMSGame.reset(), toNonNullArray(), com.runehive.game.world.items.containers.equipment.Equipment.unEquip(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdrawAll().
getSlotById()
int com.runehive.game.world.items.containers.ItemContainer.getSlotById (int id)
Gets a slot by id.
Parameters
id The id.
Returns
The slot, or -1 if it could not be found.
Definition at line 1221 of file ItemContainer.java.
{
        for (int i = 0; i < items.length; i++) {
            if (items[i] == null) {
                continue;
            }
            if (items[i].getId() == id) {
                return i;
            }
        }
        return -1;
    }
References getId(), and items.
getWeight()
double com.runehive.game.world.items.containers.ItemContainer.getWeight ()
Gets the weight of the container.
Returns
The weight of the container.
Definition at line 977 of file ItemContainer.java.
{
        double weight = 0;
        for (Item item : toArray()) {
            if (item == null)
                continue;
            weight += item.getWeight();
        }
        return weight;
    }
References toArray().
hasCapacityAfter()
final boolean com.runehive.game.world.items.containers.ItemContainer.hasCapacityAfter (Item[] add, Item... remove)
Creates a copy of the underlying container and removes the items specified from it and after tries to deposit the specified items to it.
Parameters
add the items to deposit to this container.
remove the items that should be removed before adding.
Returns
true if item can be added, false otherwise.
Definition at line 713 of file ItemContainer.java.
{
        ItemContainer container = new ItemContainer(capacity, policy, toArray());
        container.removeAll(Arrays.copyOf(remove, remove.length));
        return container.hasCapacityFor(add);
    }
References add(), capacity, hasCapacityFor(), ItemContainer(), policy, removeAll(), and toArray().
hasCapacityFor()
final boolean com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor (Item... item)
Determines if this container has the capacity for item.
Parameters
item The Item to determine this for.
Returns
true if item can be added, false otherwise.
Definition at line 699 of file ItemContainer.java.
{
        int indexCount = computeIndexCount(item);
        return remaining() >= indexCount;
    }
References computeIndexCount(), and remaining().
Referenced by com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute(), com.runehive.content.skill.impl.ProducingSkillAction.canRun(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.gambling.GambleManager.decline(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.gambling.GambleManager.give(), hasCapacityAfter(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.pet.Pets.onObtain(), com.runehive.content.store.Store.purchase(), com.runehive.content.itemaction.impl.MagmaHelm.uncharge(), com.runehive.content.itemaction.impl.SerpentineHelm.uncharge(), com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge(), com.runehive.content.itemaction.impl.TridentOfTheSeas.uncharge(), and com.runehive.content.itemaction.impl.TridentOfTheSwamp.uncharge().
ifPresent()
final void com.runehive.game.world.items.containers.ItemContainer.ifPresent (int index, Consumer< Item > action)
Consumes an action if the index is a valid item index in this container.
Parameters
index the index to get the item on.
Definition at line 1019 of file ItemContainer.java.
{
        if (index >= 0 && index < items.length)
            action.accept(items[index]);
    }
References items.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.onEquip().
indexFree()
final boolean com.runehive.game.world.items.containers.ItemContainer.indexFree (int index)
Returns true if index is not occupied (null).
Definition at line 1082 of file ItemContainer.java.
{
        return !indexOccupied(index);
    }
References indexOccupied().
indexOccupied()
final boolean com.runehive.game.world.items.containers.ItemContainer.indexOccupied (int index)
Returns true if index is occupied (non-null).
Definition at line 1075 of file ItemContainer.java.
{
        return retrieve(index).isPresent();
    }
References retrieve().
Referenced by indexFree().
insert()
final void com.runehive.game.world.items.containers.ItemContainer.insert (int oldIndex, int newIndex, boolean refresh)
Definition at line 879 of file ItemContainer.java.
{
        checkArgument(oldIndex >= 0 && oldIndex < capacity, "[insert] oldIndex out of range - [old=" + oldIndex + ", new=" + newIndex + ", refresh=" + refresh + ", size=" + size() + ", capacity=" + capacity + "]");
        checkArgument(newIndex >= 0 && newIndex < capacity, "[insert] newIndex out of range - [old=" + oldIndex + ", new=" + newIndex + ", refresh=" + refresh + ", size=" + size() + ", capacity=" + capacity + "]");
        if (newIndex > oldIndex) {
            for (int index = oldIndex; index < newIndex; index++) {
                swap(index, index + 1, refresh);
            }
        } else if (oldIndex > newIndex) {
            for (int index = oldIndex; index > newIndex; index--) {
                swap(index, index - 1, refresh);
            }
        }
    }
References capacity, refresh(), size(), and swap().
Referenced by swap().
isEmpty()
final boolean com.runehive.game.world.items.containers.ItemContainer.isEmpty ()
Returns
true if this container is empty
Definition at line 1110 of file ItemContainer.java.
{
        return size() == 0;
    }
References size().
Referenced by com.runehive.game.service.DonationService.claimDonation(), com.runehive.game.world.items.containers.bank.DonatorDeposit.confirm(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.depositeAll(), and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.withdrawAll().
isFull()
final boolean com.runehive.game.world.items.containers.ItemContainer.isFull ()
Definition at line 1114 of file ItemContainer.java.
{
        return getFreeSlots() == 0;
    }
References getFreeSlots().
iterator()
final Iterator< Item > com.runehive.game.world.items.containers.ItemContainer.iterator ()
Definition at line 145 of file ItemContainer.java.
{
        return new ItemContainerIterator(this);
    }
onRefresh()
void com.runehive.game.world.items.containers.ItemContainer.onRefresh ()
Any functionality that should occur when refreshed.
Reimplemented in com.runehive.game.world.items.containers.bank.DonatorDeposit, com.runehive.game.world.items.containers.impl.LootingBag, com.runehive.game.world.items.containers.impl.LostUntradeables, and com.runehive.game.world.items.containers.pricechecker.PriceChecker.
Definition at line 834 of file ItemContainer.java.
{
        /* can be overriden */
    }
Referenced by refresh().
policy()
final StackPolicy com.runehive.game.world.items.containers.ItemContainer.policy ()
Returns
the policy this container follows
Definition at line 1205 of file ItemContainer.java.
{
        return policy;
    }
References policy.
refresh()
void com.runehive.game.world.items.containers.ItemContainer.refresh (Player player, int widget)
Sends the items on the itemcontainer.
Parameters
widget The widget to send the Items on.
Reimplemented in com.runehive.game.world.items.containers.equipment.Equipment, and com.runehive.game.world.items.containers.inventory.Inventory.
Definition at line 828 of file ItemContainer.java.
{
        player.send(new SendItemOnInterface(widget, items));
        onRefresh();
    }
References items, onRefresh(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by add(), add(), add(), clear(), fireItemUpdatedEvent(), fireItemUpdatedEvent(), insert(), remove(), remove(), replace(), replace(), replace(), com.runehive.game.world.items.containers.ItemContainerAdapter.sendItemsToWidget(), set(), swap(), swap(), and transfer().
remaining()
final int com.runehive.game.world.items.containers.ItemContainer.remaining ()
Returns
the amount of remaining free indices
Definition at line 1185 of file ItemContainer.java.
{
        return capacity - size();
    }
References capacity, and size().
Referenced by add(), hasCapacityFor(), com.runehive.content.store.Store.purchase(), com.runehive.content.skill.impl.woodcutting.BirdsNest.search(), com.runehive.content.store.Store.sell(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents().
remove() [1/6]
boolean com.runehive.game.world.items.containers.ItemContainer.remove (int id)
Definition at line 335 of file ItemContainer.java.
{
        return remove(new Item(id, 1));
    }
remove() [2/6]
boolean com.runehive.game.world.items.containers.ItemContainer.remove (int id, int amount)
Definition at line 339 of file ItemContainer.java.
{
        return remove(new Item(id, amount));
    }
remove() [3/6]
boolean com.runehive.game.world.items.containers.ItemContainer.remove (Item item)
Attempts to withdraw item from this container.
Parameters
item The Item to withdraw.
Returns
true if the Item was removed, false if it isn't present in this container.
Definition at line 317 of file ItemContainer.java.
{
        return remove(item, -1, true);
    }
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.pet.Pets.buyInsurance(), com.runehive.content.itemaction.impl.CelestialRing.charge(), com.runehive.content.itemaction.impl.CrawsBow.charge(), com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.ThammaronsSceptre.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), com.runehive.content.itemaction.impl.ViggorasChainmace.charge(), com.runehive.content.pet.Pets.claimLostPets(), com.runehive.content.skill.impl.agility.Agility.clickButton(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.content.skill.impl.runecrafting.Runecraft.craft(), com.runehive.content.CrystalChest.createKey(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.itemaction.impl.CelestialRing.drop(), com.runehive.content.itemaction.impl.CrawsBow.drop(), com.runehive.content.itemaction.impl.ThammaronsSceptre.drop(), com.runehive.content.itemaction.impl.ViggorasChainmace.drop(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.bags.ItemBag.fill(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.SerpentineHelm.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap(), com.runehive.content.combat.cannon.CannonManager.load(), com.runehive.content.itemaction.impl.ToxicBlowpipe.load(), com.runehive.content.pet.Pets.onDeath(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.game.action.impl.ScatterAshAction.onExecute(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.content.lms.LMSGame.rollChest(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.content.store.Store.sell(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.store.currency.impl.ItemCurrency.takeCurrency(), com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), com.runehive.content.itemaction.impl.ToxicBlowpipe.unload(), and com.runehive.content.gambling.GambleManager.withdraw().
remove() [4/6]
boolean com.runehive.game.world.items.containers.ItemContainer.remove (Item item, int preferredIndex)
Attempts to withdraw item from this container, preferably from preferredIndex.
Parameters
item The Item to withdraw.
preferredIndex The preferable index to withdraw item from.
Returns
true if the Item was removed, false if it isn't present in this container.
Definition at line 331 of file ItemContainer.java.
{
        return remove(item, preferredIndex, true);
    }
remove() [5/6]
boolean com.runehive.game.world.items.containers.ItemContainer.remove (Item item, int preferredIndex, boolean refresh)
Reimplemented in com.runehive.game.world.items.containers.equipment.Equipment.
Definition at line 343 of file ItemContainer.java.
{
        return remove(item, preferredIndex, refresh, true);
    }
References refresh().
remove() [6/6]
boolean com.runehive.game.world.items.containers.ItemContainer.remove (Item item, int preferredIndex, boolean refresh, boolean removeAll)
Attempts to withdraw item from this container, preferably from preferredIndex.
Parameters
item The Item to withdraw.
preferredIndex The preferable index to withdraw item from.
refresh The condition if we will be refreshing our container.
removeAll Determines if the items should be removed from all slots or only the specified s
Returns
true if the Item was removed, false if it isn't present in this container.
Definition at line 361 of file ItemContainer.java.
{
        checkArgument(preferredIndex >= -1, "invalid index identifier");
        item = item.copy();
        boolean stackable = (policy.equals(StackPolicy.STANDARD) && item.isStackable()) || policy.equals(StackPolicy.ALWAYS);
        if (stackable) {
            //todo fix dupe
            /*
            because stackable is true (due to the coins being stackable). it will compute the first index.
            being the 1 coin, so when you drop. amount is 260. removes 1coin but drops 260k.
             */
            preferredIndex = computeIndexForId(item.getId());
        } else {
            preferredIndex = preferredIndex == -1 ? computeIndexForId(item.getId()) : preferredIndex;
            if (preferredIndex != -1 && items[preferredIndex] == null) {
                preferredIndex = -1;
            }
        }
        if (preferredIndex == -1) { // Item isn't present within this container.
            return false;
        }
        if (stackable) {
            Item current = items[preferredIndex];
            if (current.getAmount() > item.getAmount()) {
                items[preferredIndex] = current.createAndDecrement(item.getAmount());
            } else {
                if (allowZero()) {
                    items[preferredIndex] = current.createWithAmount(0);
                } else {
                    items[preferredIndex] = null;
                }
            }
            fireItemUpdatedEvent(current, items[preferredIndex], preferredIndex, refresh);
        } else {
            int until = removeAll ? computeAmountForId(item.getId()) : items[preferredIndex].getAmount();
            until = (item.getAmount() > until) ? until : item.getAmount();
            for (int index = 0; index < until && index < capacity; index++) {
                if (removeAll) {
                    if (preferredIndex < 0 || preferredIndex >= capacity) {
                        preferredIndex = computeIndexForId(item.getId());
                    } else if (items[preferredIndex] == null) {
                        preferredIndex = computeIndexForId(item.getId());
                    } else if (items[preferredIndex].getId() != item.getId()) {
                        preferredIndex = computeIndexForId(item.getId());
                    }
                    if (preferredIndex == -1) {
                        break;
                    }
                }
                Item oldItem = items[preferredIndex];
                if (allowZero()) {
                    items[preferredIndex] = oldItem.createWithAmount(0);
                } else {
                    items[preferredIndex] = null;
                }
                fireItemUpdatedEvent(oldItem, null, preferredIndex++, refresh);
            }
        }
        return true;
    }
References allowZero(), com.runehive.game.world.items.containers.ItemContainer.StackPolicy.ALWAYS, capacity, computeAmountForId(), computeIndexForId(), com.runehive.game.world.items.Item.createAndDecrement(), com.runehive.game.world.items.Item.createWithAmount(), fireItemUpdatedEvent(), com.runehive.game.world.items.Item.getAmount(), getId(), items, policy, refresh(), removeAll(), and com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD.
removeAll() [1/3]
boolean com.runehive.game.world.items.containers.ItemContainer.removeAll (Collection<? extends Item > items)
Attempts to withdraw items in bulk from this container.
Parameters
items The Items to withdraw.
Returns
true if at least 1 of the Items were withdraw, false if none could be removed.
Definition at line 437 of file ItemContainer.java.
{
        if (items.size() == 1) { // Bulk operation on singleton list? No thanks..
            Optional<? extends Item> item = items.stream().
                    filter(Objects::nonNull).
                    findFirst();
            return item.isPresent() && remove(item.get());
        }
        firingEvents = false;
        boolean removed = false;
        try {
            for (Item item : items) {
                if (item == null) {
                    continue;
                }
                if (remove(item, -1, false)) {
                    removed = true;
                }
            }
        } finally {
            firingEvents = true;
        }
        fireBulkItemsUpdatedEvent();
        return removed;
    }
References fireBulkItemsUpdatedEvent(), firingEvents, and items.
Referenced by com.runehive.content.skill.impl.ProducingSkillAction.canRun(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.depositeAll(), com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), hasCapacityAfter(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), remove(), removeAll(), and removeAll().
removeAll() [2/3]
boolean com.runehive.game.world.items.containers.ItemContainer.removeAll (Item... items)
Attempts to withdraw items in bulk from this container.
Parameters
items The Items to withdraw.
Returns
true if at least 1 of the Items were withdraw, false if none could be removed.
Definition at line 470 of file ItemContainer.java.
{
        return removeAll(Arrays.asList(items));
    }
References items, and removeAll().
removeAll() [3/3]
boolean com.runehive.game.world.items.containers.ItemContainer.removeAll (ItemContainer items)
Attempts to withdraw items in bulk from this container.
Parameters
items The Items to withdraw.
Returns
true if at least 1 of the Items were withdraw, false if none could be removed.
Definition at line 481 of file ItemContainer.java.
{
        return removeAll(items.items);
    }
References ItemContainer(), items, and removeAll().
removeListener()
final boolean com.runehive.game.world.items.containers.ItemContainer.removeListener (ItemContainerListener listener)
Removes an ItemContainerListener from this container.
Parameters
listener The listener to withdraw from this container.
Returns
true if the listener was removed, false otherwise.
Definition at line 1135 of file ItemContainer.java.
{
        return listeners.remove(listener);
    }
References listeners.
replace() [1/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.replace (int oldId, int newId, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
Parameters
oldId The old identifier to replace.
newId The new identifier to replace.
refresh The condition if the coontainer will be refreshed.
Returns
true if the replace operation was successful,
false otherwise.
Definition at line 598 of file ItemContainer.java.
{
        int index = computeIndexForId(oldId);
        if (index == -1) {
            return false;
        }
        Item oldItem = items[index];
        if (oldItem == null || !oldItem.matchesId(oldId))
            return false;
        Item newItem = oldItem.createWithId(newId);
        return remove(oldItem, index, refresh) && add(newItem, index, refresh);
    }
References add(), computeIndexForId(), com.runehive.game.world.items.Item.createWithId(), items, com.runehive.game.world.items.Item.matchesId(), and refresh().
replace() [2/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.replace (int oldId, int newId, int index, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
Parameters
oldId The old identifier to replace.
newId The new identifier to replace.
refresh The condition if the coontainer will be refreshed.
Returns
true if the replace operation was successful,
false otherwise.
Definition at line 578 of file ItemContainer.java.
{
        Item oldItem = items[index];
        if (oldItem == null || !oldItem.matchesId(oldId))
            return false;
        Item newItem = oldItem.createWithId(newId);
        return remove(oldItem, index, refresh) && add(newItem, index, refresh);
    }
References add(), com.runehive.game.world.items.Item.createWithId(), items, com.runehive.game.world.items.Item.matchesId(), and refresh().
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), com.runehive.content.itemaction.impl.DragonfireShield.empty(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.content.itemaction.impl.SerpentineHelm.itemOnItem(), replaceAll(), com.runehive.content.skill.impl.woodcutting.BirdsNest.search(), com.runehive.content.itemaction.impl.MagmaHelm.uncharge(), com.runehive.content.itemaction.impl.SerpentineHelm.uncharge(), com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge(), and com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge().
replace() [3/3]
final boolean com.runehive.game.world.items.containers.ItemContainer.replace (Item first, Item second, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
Parameters
refresh The condition if the coontainer will be refreshed.
Returns
true if the replace operation was successful,
false otherwise.
Definition at line 621 of file ItemContainer.java.
{
        int index = computeIndexForId(first.getId());
        if (index == -1) {
            return false;
        }
        Item oldItem = items[index];
        if (oldItem == null || !oldItem.matchesId(first.getId()))
            return false;
        return remove(oldItem, index, refresh) && add(second, index, refresh);
    }
References add(), computeIndexForId(), com.runehive.game.world.items.Item.getId(), items, com.runehive.game.world.items.Item.matchesId(), and refresh().
replaceAll()
final boolean com.runehive.game.world.items.containers.ItemContainer.replaceAll (int oldId, int newId)
Replaces all occurrences of Items having the identifier
oldId with newId.
Parameters
oldId The old identifier to replace.
newId The new identifier to replace.
Returns
true if the replace operation was successful at least once, false otherwise.
Definition at line 645 of file ItemContainer.java.
{
        boolean replaced = false;
        firingEvents = false;
        try {
            while (replace(oldId, newId, false)) {
                replaced = true;
            }
        } finally {
            firingEvents = true;
        }
        fireBulkItemsUpdatedEvent();
        return replaced;
    }
References fireBulkItemsUpdatedEvent(), firingEvents, and replace().
retrieve()
final Optional< Item > com.runehive.game.world.items.containers.ItemContainer.retrieve (int index)
Retrieves the item located on index.
Parameters
index the index to get the item on.
Returns
the item on the index, or null if no item exists on the index.
Definition at line 1007 of file ItemContainer.java.
{
        if (index >= 0 && index < items.length)
            return Optional.ofNullable(items[index]);
        return Optional.empty();
    }
References items.
Referenced by computeIdForIndex(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.hit(), indexOccupied(), com.runehive.content.store.impl.PersonalStore.itemContainerAction(), com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), com.runehive.game.world.items.containers.equipment.Equipment.onRemove(), and com.runehive.game.world.items.containers.equipment.Equipment.updateRangedEquipment().
search() [1/2]
Optional< Item > com.runehive.game.world.items.containers.ItemContainer.search (int id)
Searches and returns the first item found with id.
Parameters
id the identifier to search this container for.
Returns
the item wrapped within an optional, or an empty optional if no item was found.
Definition at line 1056 of file ItemContainer.java.
{
        return stream().filter(i -> i != null && id == i.getId()).findFirst();
    }
References stream().
search() [2/2]
Optional< Item > com.runehive.game.world.items.containers.ItemContainer.search (Item item)
Searches and returns the first item found with id and
amount.
Parameters
item the item to search this container for.
Returns
the item wrapped within an optional, or an empty optional if no item was found.
Definition at line 1068 of file ItemContainer.java.
{
        return stream().filter(i -> i != null && item.getId() == i.getId() && item.getAmount() == i.getAmount()).findFirst();
    }
References com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), and stream().
set() [1/2]
void com.runehive.game.world.items.containers.ItemContainer.set (int index, Item item, boolean refresh)
Sets the index to item.
Parameters
index The index to set.
item The Item to set on the index.
refresh The condition if the container must be refreshed.
Definition at line 994 of file ItemContainer.java.
{
        Item oldItem = items[index];
        items[index] = item;
        fireItemUpdatedEvent(oldItem, items[index], index, refresh);
    }
References fireItemUpdatedEvent(), items, and refresh().
set() [2/2]
final void com.runehive.game.world.items.containers.ItemContainer.set (Item[] toSet)
Definition at line 940 of file ItemContainer.java.
{
        items = toSet;
    }
References items.
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.wintertodt.Wintertodt.healPyromancer(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.content.wintertodt.Wintertodt.removeGameItems(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), transfer(), and com.runehive.content.skill.impl.herblore.Herblore.useItem().
setFiringEvents()
void com.runehive.game.world.items.containers.ItemContainer.setFiringEvents (boolean firingEvents)
Sets the value for firingEvents.
Definition at line 1180 of file ItemContainer.java.
{
        this.firingEvents = firingEvents;
    }
References firingEvents.
Referenced by com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.impl.LostUntradeables.deposit(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), com.runehive.game.world.items.containers.bank.Bank.moveTab(), com.runehive.game.world.items.containers.bank.Bank.placeHolder(), com.runehive.game.world.items.containers.bank.Bank.withdraw(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdraw().
setItems() [1/2]
final void com.runehive.game.world.items.containers.ItemContainer.setItems (Item[] items)
Definition at line 936 of file ItemContainer.java.
{
        setItems(items, true);
    }
References items, and setItems().
setItems() [2/2]
final void com.runehive.game.world.items.containers.ItemContainer.setItems (Item[] items, boolean copy)
Sets the container of items to items.
The container will not hold any references to the array, nor the item instances in the array.
Parameters
items the new array of items, the capacities of this must be equal to or lesser than the container.
Definition at line 927 of file ItemContainer.java.
{
        Preconditions.checkArgument(items.length <= capacity);
        clear();
        for (int i = 0; i < items.length; i++) {
            this.items[i] = items[i] == null ? null : copy ? items[i].copy() : items[i];
        }
        fireBulkItemsUpdatedEvent();
    }
References capacity, clear(), copy(), fireBulkItemsUpdatedEvent(), and items.
Referenced by com.runehive.content.store.impl.DefaultStore.DefaultStore(), setItems(), and shift().
shift()
void com.runehive.game.world.items.containers.ItemContainer.shift ()
Percolates the null indices to the end of the stack.
Reimplemented in com.runehive.game.world.items.containers.bank.Bank.
Definition at line 906 of file ItemContainer.java.
{
        Item[] newItems = new Item[capacity];
        int newIndex = 0;
        for (Item item : items) {
            if (item == null) {
                continue;
            }
            newItems[newIndex++] = item;
        }
        setItems(newItems);
    }
References capacity, items, and setItems().
Referenced by com.runehive.game.world.items.containers.impl.LostUntradeables.claim(), com.runehive.game.world.items.containers.bank.DonatorDeposit.withdraw(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdraw().
size()
final int com.runehive.game.world.items.containers.ItemContainer.size ()
Returns
the amount of used indices
Definition at line 1195 of file ItemContainer.java.
{
        return (int) Arrays.stream(items).filter(Objects::nonNull).count();
    }
References items.
Referenced by com.runehive.game.world.items.containers.bank.Bank.collapse(), com.runehive.game.world.items.containers.bank.DonatorDeposit.confirm(), com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.DonatorDeposit.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), getFreeSlots(), insert(), isEmpty(), com.runehive.game.world.items.containers.bank.DonatorDeposit.onRefresh(), com.runehive.game.world.items.containers.impl.LostUntradeables.onRefresh(), remaining(), com.runehive.game.world.items.containers.bank.Bank.sendValue(), swap(), and toNonNullArray().
spliterator()
final Spliterator< Item > com.runehive.game.world.items.containers.ItemContainer.spliterator ()
Definition at line 140 of file ItemContainer.java.
{
        return Spliterators.spliterator(items, Spliterator.ORDERED);
    }
References items.
Referenced by stream().
stream()
final Stream< Item > com.runehive.game.world.items.containers.ItemContainer.stream ()
Returns
A stream associated with the elements in this container, built using the spliterator() implementation.
Definition at line 153 of file ItemContainer.java.
{
        return StreamSupport.stream(spliterator(), false);
    }
References spliterator().
Referenced by search(), and search().
swap() [1/3]
final void com.runehive.game.world.items.containers.ItemContainer.swap (boolean insert, int oldIndex, int newIndex, boolean refresh)
Swaps the Items on oldIndex and newIndex.
Parameters
insert If the Item should be inserted.
oldIndex The old index.
newIndex The new index.
refresh The condition that determines if we will refresh the container.
Definition at line 857 of file ItemContainer.java.
{
        if (insert) {
            insert(oldIndex, newIndex, refresh);
        } else {
            swap(oldIndex, newIndex, refresh);
        }
    }
References insert(), refresh(), and swap().
swap() [2/3]
final void com.runehive.game.world.items.containers.ItemContainer.swap (int oldIndex, int newIndex)
Swaps the Items on oldIndex and newIndex.
Parameters
oldIndex The old index.
newIndex The new index.
Definition at line 844 of file ItemContainer.java.
{
        swap(false, oldIndex, newIndex, true);
    }
References swap().
Referenced by com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), insert(), com.runehive.game.world.items.containers.bank.Bank.itemToTab(), com.runehive.game.world.items.containers.bank.Bank.moveItem(), com.runehive.game.world.items.containers.bank.Bank.moveTab(), swap(), and swap().
swap() [3/3]
final void com.runehive.game.world.items.containers.ItemContainer.swap (int oldIndex, int newIndex, boolean refresh)
Definition at line 865 of file ItemContainer.java.
{
        checkArgument(oldIndex >= 0 && oldIndex < capacity, "[swap] oldIndex out of range - [old=" + oldIndex + ", new=" + newIndex + ", refresh=" + refresh + ", size=" + size() + ", capacity=" + capacity + "]");
        checkArgument(newIndex >= 0 && newIndex < capacity, "[swap] newIndex out of range - [old=" + oldIndex + ", new=" + newIndex + ", refresh=" + refresh + ", size=" + size() + ", capacity=" + capacity + "]");
        Item itemOld = items[oldIndex];
        Item itemNew = items[newIndex];
        items[oldIndex] = itemNew;
        items[newIndex] = itemOld;
        fireItemUpdatedEvent(itemOld, items[oldIndex], oldIndex, refresh);
        fireItemUpdatedEvent(itemNew, items[newIndex], newIndex, refresh);
    }
References capacity, fireItemUpdatedEvent(), items, refresh(), and size().
toArray()
final Item[] com.runehive.game.world.items.containers.ItemContainer.toArray ()
Returns a shallow copy of the backing array.
Changes made to the returned array will not be reflected on the backing array.
Returns
A shallow copy of the backing array.
Definition at line 950 of file ItemContainer.java.
{
        return Arrays.copyOf(items, items.length);
    }
References items.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.copy(), copy(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), getWeight(), hasCapacityAfter(), com.runehive.game.world.items.containers.impl.LootingBag.onRefresh(), com.runehive.content.gambling.GambleManager.open(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.content.store.impl.DefaultStore.refresh(), com.runehive.content.store.impl.RecipeForDisasterStore.refresh(), com.runehive.content.store.impl.SkillcapeStore.refresh(), com.runehive.game.world.items.containers.bank.Bank.refresh(), com.runehive.game.world.items.containers.equipment.Equipment.refresh(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.reward(), com.runehive.game.world.items.containers.equipment.Equipment.updateWeight(), and com.runehive.content.gambling.GambleManager.withdraw().
toNonNullArray()
final Item[] com.runehive.game.world.items.containers.ItemContainer.toNonNullArray ()
Definition at line 954 of file ItemContainer.java.
{
        if (size() == 0) {
            return new Item[0];
        }
        final List<Item> items = new ArrayList<>(size());
        for (Item item : getItems()) {
            if (item == null) {
                continue;
            }
            items.add(item);
        }
        return items.toArray(new Item[items.size()]);
    }
References getItems(), items, and size().
Referenced by com.runehive.game.world.items.containers.impl.LootingBag.getDeathItems().
transfer()
final void com.runehive.game.world.items.containers.ItemContainer.transfer (int firstIndex, int secondIndex, ItemContainer other, boolean refresh)
Definition at line 894 of file ItemContainer.java.
{
        checkArgument(firstIndex >= 0 && firstIndex < capacity, "[transfer] firstIndex out of range - [first=" + firstIndex + ", second=" + secondIndex + ", refresh=" + refresh + "]");
        checkArgument(secondIndex >= 0 && secondIndex < other.capacity, "[transfer] secondIndex out of range - [first=" + firstIndex + ", second=" + secondIndex + ", refresh=" + refresh + "]");
        Item first = get(firstIndex);
        Item second = other.get(secondIndex);
        set(firstIndex, second, true);
        other.set(secondIndex, first, true);
    }
References capacity, get(), ItemContainer(), refresh(), and set().
Member Data Documentation
capacity
final int com.runehive.game.world.items.containers.ItemContainer.capacity private
The capacity of this container.
Definition at line 101 of file ItemContainer.java.
Referenced by add(), capacity(), computeFreeIndex(), computeIndexForId(), com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), getFreeSlots(), hasCapacityAfter(), insert(), ItemContainer(), ItemContainer(), com.runehive.game.world.items.containers.bank.DonatorDeposit.onRefresh(), com.runehive.game.world.items.containers.impl.LostUntradeables.onRefresh(), remaining(), remove(), setItems(), shift(), swap(), and transfer().
firingEvents
boolean com.runehive.game.world.items.containers.ItemContainer.firingEvents = true private
If events are currently being fired.
Definition at line 110 of file ItemContainer.java.
Referenced by addAll(), fireBulkItemsUpdatedEvent(), fireCapacityExceededEvent(), fireItemUpdatedEvent(), removeAll(), replaceAll(), and setFiringEvents().
items
Item [] com.runehive.game.world.items.containers.ItemContainer.items private
The Items within this container.
Definition at line 107 of file ItemContainer.java.
Referenced by add(), addAll(), addAll(), addAll(), com.runehive.game.world.items.containers.inventory.Inventory.addOrBank(), com.runehive.game.world.items.containers.inventory.Inventory.addOrBank(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute(), com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute(), com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute(), com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute(), com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute(), com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute(), clear(), computeAmountForId(), computeFreeIndex(), computeIndexCount(), computeIndexForId(), containerValue(), contains(), contains(), containsAll(), containsAll(), containsAny(), containsAny(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.depositAll(), com.runehive.game.world.items.containers.bank.Bank.depositeEquipment(), com.runehive.game.world.items.containers.bank.Bank.depositeInventory(), forEach(), get(), getId(), getItems(), getSlotById(), ifPresent(), ItemContainer(), com.runehive.game.world.items.containers.equipment.Equipment.manualWearAll(), refresh(), remove(), removeAll(), removeAll(), removeAll(), replace(), replace(), replace(), retrieve(), set(), set(), setItems(), setItems(), shift(), size(), spliterator(), swap(), toArray(), and toNonNullArray().
listeners
final List<ItemContainerListener> com.runehive.game.world.items.containers.ItemContainer.listeners = new ArrayList<>() private
An ArrayList of ItemContainerListeners listening for various events.
Definition at line 98 of file ItemContainer.java.
Referenced by addListener(), fireBulkItemsUpdatedEvent(), fireCapacityExceededEvent(), fireItemUpdatedEvent(), and removeListener().
policy
final StackPolicy com.runehive.game.world.items.containers.ItemContainer.policy private
The policy of this container.
Definition at line 104 of file ItemContainer.java.
Referenced by add(), computeIndexCount(), hasCapacityAfter(), ItemContainer(), ItemContainer(), policy(), and remove().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/ItemContainer.java