RuneHive-Game: com.runehive.content.activity.impl.pestcontrol.PestControlGame Class Reference
com.runehive.content.activity.impl.pestcontrol.PestControlGame Class Reference
Classes
class PestControlNode
class PestControlPanel
class Portal
Public Member Functions
boolean canLogout (Player player)
boolean canTeleport (Player player)
Called when the player attempts to teleport.
ActivityDeathType deathType ()
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
void sequence ()
Sequences the activity.
Public Member Functions inherited from com.runehive.content.activity.lobby.LobbyNode
boolean inLobby ()
Public Member Functions inherited from com.runehive.content.activity.GroupActivity
final void addActivity (Mob mob, Activity activity)
Adds an activity to the activities group.
void cleanup ()
Cleans up the activity when finished.
void forEachActivity (BiConsumer< Mob, Activity > activity)
Loops through all the activities.
int getActiveSize ()
Gets the size of the activities in this group.
Activity getActivity (Mob mob)
final void groupMessage (String message)
Sends a message to all the players in the group.
final boolean isActive ()
Checks if this group is active.
final void removeActivity (Mob mob)
Removes an activity from the activities group.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
void update ()
The update method.
Protected Member Functions
boolean clickObject (Player player, ObjectInteractionEvent event)
Activity createActivity (Player player)
boolean finished ()
Optional< PestControlListener > getListener ()
Gets an Optional of the ActivityListener for this activity.
void onStart ()
Protected Member Functions inherited from com.runehive.content.activity.lobby.LobbyNode
boolean contains (Player player)
LobbyNode (LobbyManager manager)
final void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.GroupActivity
GroupActivity (int cooldown, int capacity)
Constructs a new GroupActivity object.
void removeAll ()
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Package Functions
PestControlGame (LobbyManager manager)
Private Member Functions
void agressiveMonsters ()
void spawn (int id, Position southWest, int size)
void spawnMonsters ()
Private Attributes
final PestControlListener listener = new PestControlListener(this)
The Pest control activity listener.
Set< Npc > monsters = new HashSet<>()
The active monsters.
final Portal[] portals
The portals.
Set< Npc > portalSet = new HashSet<>()
The active portals.
final Npc voidKnight = new Npc(1756, Position.create(2656, 2592))
The void knight.
Static Private Attributes
static final Position BLUE_BOUNDS = new Position(2679, 2587)
static final Position BOAT = new Position(2656, 2609)
The position of the pest control boat.
static final int[] DEFILERS = {1728, 1729}
static final Position KNIGHT_BOUNDS = new Position(2654, 2590)
static final Position OUTSIDE_BOAT_POSITION = new Position(2657, 2639)
The position outside the pest control boat.
static final String[] PORTAL_NAMES
The portal names.
static final Position PURPLE_BOUNDS = new Position(2627, 2590)
static final int[] RAVAGERS = {1704, 1705, 1706, 1707, 1708}
static final Position RED_BOUNDS = new Position(2644, 2568)
static final int[] SHIFTERS = {1698, 1699, 1700, 1701}
static final int[] SPLATTERS = {1691, 1692}
static final int[] TORCHERS = {1728, 1729}
static final String[] VOID_KNIGHT_MESSAGES
The void knight messages that he will chant.
static final Position YELLOW_BOUNDS = new Position(2668, 2569)
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Attributes inherited from com.runehive.content.activity.lobby.LobbyNode
final LobbyManager manager
Protected Attributes inherited from com.runehive.content.activity.GroupActivity
final Map< Mob, Activity > activities
A map of activities that handles each mob individually.
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Package Attributes inherited from com.runehive.content.activity.lobby.LobbyNode
boolean lobby
Detailed Description
Definition at line 36 of file PestControlGame.java.
Constructor & Destructor Documentation
PestControlGame()
com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlGame (LobbyManager manager) package
Definition at line 93 of file PestControlGame.java.
{
        super(manager);
        setInstance(Entity.DEFAULT_INSTANCE);
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, com.runehive.content.activity.lobby.LobbyNode.manager, and com.runehive.content.activity.Activity.setInstance().
Member Function Documentation
agressiveMonsters()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.agressiveMonsters () private
Definition at line 266 of file PestControlGame.java.
{
        if (monsters.isEmpty())
            return;
        if (voidKnight == null)
            return;
        for (Npc monster : monsters) {
            if (monster.getCombat().inCombat())
                continue;
            if (monster.getPosition().isWithinDistance(voidKnight.getPosition(), 10)) {
                monster.getCombat().attack(voidKnight);
                continue;
            }
            activities.keySet().forEach(mob -> {
                if (!mob.isPlayer())
                    return;
                if (monster.getPosition().isWithinDistance(mob.getPosition(), 8))
                    monster.getCombat().attack(mob);
            });
        }
    }
References com.runehive.content.activity.GroupActivity.activities, monsters, and voidKnight.
Referenced by sequence().
canLogout()
boolean com.runehive.content.activity.impl.pestcontrol.PestControlGame.canLogout (Player player)
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 167 of file PestControlGame.java.
{
        player.message("You cannot log out during a Pest Control game.");
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.message().
canTeleport()
boolean com.runehive.content.activity.impl.pestcontrol.PestControlGame.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 364 of file PestControlGame.java.
{
        player.send(new SendMessage("Talk to the void-knight next to the boat to leave."));
        return false;
    }
References com.runehive.game.world.entity.mob.player.Player.send().
clickObject()
boolean com.runehive.content.activity.impl.pestcontrol.PestControlGame.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 180 of file PestControlGame.java.
{
        if (event.getObject().getId() == 14314) {
            manager.leave(player);
            return true;
        }
        return false;
    }
References com.runehive.content.activity.lobby.LobbyNode.manager.
createActivity()
Activity com.runehive.content.activity.impl.pestcontrol.PestControlGame.createActivity (Player player) protected
Reimplemented from com.runehive.content.activity.lobby.LobbyNode.
Definition at line 213 of file PestControlGame.java.
{
        PestControlNode node = new PestControlNode(player);
        PestControlPanel panel = new PestControlPanel(player, node);
        panel.open();
        return node;
    }
References com.runehive.content.activity.Activity.panel.
deathType()
ActivityDeathType com.runehive.content.activity.impl.pestcontrol.PestControlGame.deathType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 209 of file PestControlGame.java.
{
        return ActivityDeathType.SAFE;
    }
References com.runehive.content.activity.ActivityDeathType.SAFE.
finish()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.GroupActivity.
Definition at line 189 of file PestControlGame.java.
{
        super.finish();
        remove(voidKnight);
        monsters.forEach(this::remove);
        portalSet.forEach(this::remove);
        monsters.clear();
        portalSet.clear();
    }
References monsters, portalSet, and voidKnight.
finished()
boolean com.runehive.content.activity.impl.pestcontrol.PestControlGame.finished () protected
Reimplemented from com.runehive.content.activity.lobby.LobbyNode.
Definition at line 223 of file PestControlGame.java.
{
        if (getTicks() == FINISH || getActiveSize() == 0) {
            return true;
        }
        if (!inLobby()) {
            if (portalSet.isEmpty()) {
                return true;
            }
            if (voidKnight.isRegistered() && voidKnight.getCurrentHealth() <= 0) {
                return true;
            }
        }
        return false;
    }
References com.runehive.content.activity.Activity.FINISH, com.runehive.content.activity.GroupActivity.getActiveSize(), com.runehive.content.activity.Activity.getTicks(), com.runehive.content.activity.lobby.LobbyNode.inLobby(), portalSet, and voidKnight.
getListener()
Optional< PestControlListener > com.runehive.content.activity.impl.pestcontrol.PestControlGame.getListener () protected
Gets an Optional of the ActivityListener for this activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 199 of file PestControlGame.java.
{
        return Optional.of(listener);
    }
References listener.
getType()
ActivityType com.runehive.content.activity.impl.pestcontrol.PestControlGame.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 204 of file PestControlGame.java.
{
        return ActivityType.PEST_CONTROL;
    }
References com.runehive.content.activity.ActivityType.PEST_CONTROL.
onDeath()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 141 of file PestControlGame.java.
{
        if (mob.isNpc()) {
            Npc npc = mob.getNpc();
            if (npc.id >= 1739 && npc.id <= 1742) {
                portalSet.remove(npc);
                voidKnight.heal(25);
                groupMessage("The " + PORTAL_NAMES[npc.id - 1739] + " is dead! The Void Knight has gained 25 HP.");
            } else {
                monsters.remove(mob.getNpc());
            }
            World.schedule(new NpcDeath(mob.getNpc(), () -> remove(mob)));
        } else {
            mob.move(BOAT.transform(Utility.random(4), Utility.random(6)));
            mob.getPlayer().animate(Animation.RESET, true);
            mob.getPlayer().graphic(Graphic.RESET, true);
        }
    }
References com.runehive.game.world.entity.mob.Mob.animate(), BOAT, com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.content.activity.GroupActivity.groupMessage(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.isNpc(), monsters, com.runehive.game.world.entity.mob.Mob.move(), PORTAL_NAMES, portalSet, com.runehive.util.Utility.random(), com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, com.runehive.game.world.World.schedule(), and voidKnight.
onLogout()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 162 of file PestControlGame.java.
{
        removeActivity(player);
    }
References com.runehive.content.activity.GroupActivity.removeActivity().
onRegionChange()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 173 of file PestControlGame.java.
{
        if (!Area.inPestControl(player)) {
            removeActivity(player);
        }
    }
References com.runehive.game.world.position.Area.inPestControl(), and com.runehive.content.activity.GroupActivity.removeActivity().
onStart()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.onStart () protected
Reimplemented from com.runehive.content.activity.lobby.LobbyNode.
Definition at line 121 of file PestControlGame.java.
{
        forEachActivity((mob, activity) -> {
            if (mob.isPlayer()) {
                mob.getPlayer().playerAssistant.restore();
            }
        });
        add(voidKnight);
        voidKnight.blockFace = true;
        for (Npc portal : portals) {
            add(portal);
            portalSet.add(portal);
        }
        groupMessage("Protect the void knight at all costs, good luck!");
        spawnMonsters();
    }
References com.runehive.content.activity.Activity.add(), com.runehive.content.activity.GroupActivity.forEachActivity(), com.runehive.content.activity.GroupActivity.groupMessage(), portals, portalSet, spawnMonsters(), and voidKnight.
sequence()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.sequence ()
Sequences the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 99 of file PestControlGame.java.
{
        super.sequence();
        if (!inLobby()) {
            if (getTicks() == 0) {
                finishCooldown();
                return;
            }
            if (getTicks() % 20 == 0) {
                voidKnight.speak(Utility.randomElement(VOID_KNIGHT_MESSAGES));
                if (getTicks() > 10) {
                    agressiveMonsters();
                }
            }
        }
        forEachActivity((mob, activity) -> activity.getPanel().ifPresent(panel -> ((PestControlPanel) panel).update()));
    }
References agressiveMonsters(), com.runehive.content.activity.Activity.finishCooldown(), com.runehive.content.activity.GroupActivity.forEachActivity(), com.runehive.content.activity.Activity.getTicks(), com.runehive.content.activity.lobby.LobbyNode.inLobby(), com.runehive.content.activity.Activity.panel, com.runehive.util.Utility.randomElement(), VOID_KNIGHT_MESSAGES, and voidKnight.
spawn()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.spawn (int id, Position southWest, int size) private
Definition at line 259 of file PestControlGame.java.
{
        Position target = RandomUtils.random(TraversalMap.getTraversableTiles(southWest, size, size));
        Npc monster = new Npc(id, target);
        monsters.add(monster);
        add(monster);
    }
References com.runehive.content.activity.Activity.add(), com.runehive.game.world.pathfinding.TraversalMap.getTraversableTiles(), monsters, and com.runehive.util.RandomUtils.random().
Referenced by spawnMonsters().
spawnMonsters()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.spawnMonsters () private
Definition at line 241 of file PestControlGame.java.
{
        for (int index = 0; index < 5; index++) {
            spawn(Utility.randomElement(RAVAGERS), BLUE_BOUNDS, 5);
        }
        for (int index = 0; index < 5; index++) {
            spawn(Utility.randomElement(RAVAGERS), RED_BOUNDS, 5);
        }
        for (int index = 0; index < 5; index++) {
            spawn(Utility.randomElement(RAVAGERS), YELLOW_BOUNDS, 5);
        }
        for (int index = 0; index < 5; index++) {
            spawn(Utility.randomElement(RAVAGERS), PURPLE_BOUNDS, 5);
        }
        for (int index = 0; index < 2; index++) {
            spawn(Utility.randomElement(RAVAGERS), KNIGHT_BOUNDS, 6);
        }
    }
References BLUE_BOUNDS, KNIGHT_BOUNDS, PURPLE_BOUNDS, com.runehive.util.Utility.randomElement(), RAVAGERS, RED_BOUNDS, spawn(), and YELLOW_BOUNDS.
Referenced by onStart().
Member Data Documentation
BLUE_BOUNDS
final Position com.runehive.content.activity.impl.pestcontrol.PestControlGame.BLUE_BOUNDS = new Position(2679, 2587) static private
Definition at line 66 of file PestControlGame.java.
Referenced by spawnMonsters().
BOAT
final Position com.runehive.content.activity.impl.pestcontrol.PestControlGame.BOAT = new Position(2656, 2609) static private
The position of the pest control boat.
Definition at line 39 of file PestControlGame.java.
Referenced by onDeath(), and com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.start().
DEFILERS
final int [] com.runehive.content.activity.impl.pestcontrol.PestControlGame.DEFILERS = {1728, 1729} static private
Definition at line 75 of file PestControlGame.java.
{1728, 1729};
KNIGHT_BOUNDS
final Position com.runehive.content.activity.impl.pestcontrol.PestControlGame.KNIGHT_BOUNDS = new Position(2654, 2590) static private
Definition at line 70 of file PestControlGame.java.
Referenced by spawnMonsters().
listener
final PestControlListener com.runehive.content.activity.impl.pestcontrol.PestControlGame.listener = new PestControlListener(this) private
The Pest control activity listener.
Definition at line 45 of file PestControlGame.java.
Referenced by getListener().
monsters
Set<Npc> com.runehive.content.activity.impl.pestcontrol.PestControlGame.monsters = new HashSet<>() private
The active monsters.
Definition at line 88 of file PestControlGame.java.
Referenced by agressiveMonsters(), finish(), onDeath(), and spawn().
OUTSIDE_BOAT_POSITION
final Position com.runehive.content.activity.impl.pestcontrol.PestControlGame.OUTSIDE_BOAT_POSITION = new Position(2657, 2639) static private
The position outside the pest control boat.
Definition at line 42 of file PestControlGame.java.
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.finish().
PORTAL_NAMES
final String [] com.runehive.content.activity.impl.pestcontrol.PestControlGame.PORTAL_NAMES static private
Initial value:
= {
        "Purple Portal",
        "Blue Portal",
        "Yellow Portal",
        "Red Portal"
    }
The portal names.
Definition at line 51 of file PestControlGame.java.
{
        "Purple Portal",
        "Blue Portal",
        "Yellow Portal",
        "Red Portal"
    };
Referenced by onDeath(), and com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.update().
portals
final Portal [] com.runehive.content.activity.impl.pestcontrol.PestControlGame.portals private
Initial value:
= new Portal[] {
      new Portal(1739, Position.create(2628, 2591)),
        new Portal(1740, Position.create(2680, 2588)),
      new Portal(1741, Position.create(2669, 2570)),
         new Portal(1742, Position.create(2645, 2569))
    }
The portals.
Definition at line 59 of file PestControlGame.java.
{
    /* Purple */  new Portal(1739, Position.create(2628, 2591)),
    /* Blue */    new Portal(1740, Position.create(2680, 2588)),
    /* Yellow */  new Portal(1741, Position.create(2669, 2570)),
    /* Red */     new Portal(1742, Position.create(2645, 2569))
    };
Referenced by onStart(), and com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.update().
portalSet
Set<Npc> com.runehive.content.activity.impl.pestcontrol.PestControlGame.portalSet = new HashSet<>() private
The active portals.
Definition at line 91 of file PestControlGame.java.
Referenced by finish(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.finish(), finished(), onDeath(), and onStart().
PURPLE_BOUNDS
final Position com.runehive.content.activity.impl.pestcontrol.PestControlGame.PURPLE_BOUNDS = new Position(2627, 2590) static private
Definition at line 69 of file PestControlGame.java.
Referenced by spawnMonsters().
RAVAGERS
final int [] com.runehive.content.activity.impl.pestcontrol.PestControlGame.RAVAGERS = {1704, 1705, 1706, 1707, 1708} static private
Definition at line 72 of file PestControlGame.java.
{1704, 1705, 1706, 1707, 1708};
Referenced by spawnMonsters().
RED_BOUNDS
final Position com.runehive.content.activity.impl.pestcontrol.PestControlGame.RED_BOUNDS = new Position(2644, 2568) static private
Definition at line 67 of file PestControlGame.java.
Referenced by spawnMonsters().
SHIFTERS
final int [] com.runehive.content.activity.impl.pestcontrol.PestControlGame.SHIFTERS = {1698, 1699, 1700, 1701} static private
Definition at line 74 of file PestControlGame.java.
{1698, 1699, 1700, 1701};
SPLATTERS
final int [] com.runehive.content.activity.impl.pestcontrol.PestControlGame.SPLATTERS = {1691, 1692} static private
Definition at line 73 of file PestControlGame.java.
{1691, 1692};
TORCHERS
final int [] com.runehive.content.activity.impl.pestcontrol.PestControlGame.TORCHERS = {1728, 1729} static private
Definition at line 76 of file PestControlGame.java.
{1728, 1729};
VOID_KNIGHT_MESSAGES
final String [] com.runehive.content.activity.impl.pestcontrol.PestControlGame.VOID_KNIGHT_MESSAGES static private
Initial value:
= {
        "We must not fail!",
        "Take down the portals",
        "The Void Knights will not fall!",
        "Hail the Void Knights!",
        "We are beating these scum!"
    }
The void knight messages that he will chant.
Definition at line 79 of file PestControlGame.java.
{
        "We must not fail!",
        "Take down the portals",
        "The Void Knights will not fall!",
        "Hail the Void Knights!",
        "We are beating these scum!"
    };
Referenced by sequence().
voidKnight
final Npc com.runehive.content.activity.impl.pestcontrol.PestControlGame.voidKnight = new Npc(1756, Position.create(2656, 2592)) private
The void knight.
Definition at line 48 of file PestControlGame.java.
Referenced by agressiveMonsters(), finish(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.finish(), finished(), onDeath(), onStart(), sequence(), and com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.update().
YELLOW_BOUNDS
final Position com.runehive.content.activity.impl.pestcontrol.PestControlGame.YELLOW_BOUNDS = new Position(2668, 2569) static private
Definition at line 68 of file PestControlGame.java.
Referenced by spawnMonsters().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/pestcontrol/PestControlGame.java