RuneHive-Game: com.runehive.content.itemaction.impl.TridentOfTheSwamp Class Reference
com.runehive.content.itemaction.impl.TridentOfTheSwamp Class Reference
Public Member Functions
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
TridentOfTheSwamp ()
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
boolean drop (Player player, Item item)
String message (Item item)
The message of the action.
String toString ()
Static Private Member Functions
static void check (Player player)
static void uncharge (Player player)
Static Private Attributes
static final short CHARGE_LIMIT = 2500
static final DecimalFormat FORMATTER = new DecimalFormat("#.#")
static final short TRIDENT_ID = 12899
Detailed Description
Definition at line 11 of file TridentOfTheSwamp.java.
Constructor & Destructor Documentation
TridentOfTheSwamp()
com.runehive.content.itemaction.impl.TridentOfTheSwamp.TridentOfTheSwamp ()
Definition at line 16 of file TridentOfTheSwamp.java.
{
        FORMATTER.setRoundingMode(RoundingMode.FLOOR);
    }
References FORMATTER.
Member Function Documentation
check()
void com.runehive.content.itemaction.impl.TridentOfTheSwamp.check (Player player) static private
Definition at line 105 of file TridentOfTheSwamp.java.
{
        player.message("You have " + Utility.formatDigits(player.tridentSwampCharges) + " charges in your Trident of the Swamp.");
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.entity.mob.player.Player.tridentSwampCharges.
Referenced by equipment(), and inventory().
equipment()
boolean com.runehive.content.itemaction.impl.TridentOfTheSwamp.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 94 of file TridentOfTheSwamp.java.
{
        if (item.getId() != TRIDENT_ID) {
            return false;
        }
        if (opcode == 1) {
            check(player);
            return true;
        }
        return true;
    }
References check(), com.runehive.game.world.items.Item.getId(), and TRIDENT_ID.
inventory()
boolean com.runehive.content.itemaction.impl.TridentOfTheSwamp.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 78 of file TridentOfTheSwamp.java.
{
        if (item.getId() != TRIDENT_ID) {
            return false;
        }
        if (opcode == 2) {
            check(player);
            return true;
        }
        if (opcode == 3) {
            uncharge(player);
            return true;
        }
        return true;
    }
References check(), com.runehive.game.world.items.Item.getId(), TRIDENT_ID, and uncharge().
itemOnItem()
boolean com.runehive.content.itemaction.impl.TridentOfTheSwamp.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 26 of file TridentOfTheSwamp.java.
{
        if (first.getId() != TRIDENT_ID && second.getId() != TRIDENT_ID) {
            return false;
        }
        if (player.tridentSwampCharges >= CHARGE_LIMIT) {
            player.message("Your Trident of the Swamp is already fully charged.");
            return true;
        }
        int id1 = first.getId();
        int id2 = second.getId();
        if (id1 == TRIDENT_ID && id2 != TRIDENT_ID)
            if (id2 != 560 && id2 != 562 && id2 != 554 && id2 != 12934)
                return true;
        if (id2 == TRIDENT_ID && id1 != TRIDENT_ID)
            if (id1 != 560 && id1 != 562 && id1 != 554 && id1 != 12934)
                return true;
        int scales = player.inventory.computeAmountForId(12934);
        int death = player.inventory.computeAmountForId(560);
        int chaos = player.inventory.computeAmountForId(562);
        int fire = player.inventory.computeAmountForId(554);
        if (death >= 1 && chaos >= 1 && fire >= 5 && scales >= 1) {
            int minF = fire / 5;
            int charges = Math.min(Math.min(death, chaos), Math.min(scales, minF));
            if (charges > CHARGE_LIMIT)
                charges = CHARGE_LIMIT;
            if (charges > CHARGE_LIMIT - player.tridentSwampCharges)
                charges = CHARGE_LIMIT - player.tridentSwampCharges;
            if (charges > 0) {
                player.inventory.remove(new Item(560, charges), -1, false);
                player.inventory.remove(new Item(562, charges), -1, false);
                player.inventory.remove(new Item(554, charges * 5), -1, false);
                player.inventory.remove(new Item(12934, charges), -1, false);
                player.inventory.refresh();
                player.tridentSwampCharges += charges;
                player.message("You added " + charges + " charges to your Trident of the Swamp");
            }
        } else {
            player.message("You need at least 1x zulrah scale, 1x death rune, 1x chaos rune, and 5x fire runes", "for one charge. Your Trident of the Swamp can hold 2,500 charges.");
        }
        return true;
    }
References CHARGE_LIMIT, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), TRIDENT_ID, and com.runehive.game.world.entity.mob.player.Player.tridentSwampCharges.
name()
String com.runehive.content.itemaction.impl.TridentOfTheSwamp.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 21 of file TridentOfTheSwamp.java.
{
        return "Trident of the Seas";
    }
uncharge()
void com.runehive.content.itemaction.impl.TridentOfTheSwamp.uncharge (Player player) static private
Definition at line 109 of file TridentOfTheSwamp.java.
{
        if (player.tridentSwampCharges < 1) {
            return;
        }
        int amount = player.tridentSwampCharges;
        if (!player.inventory.hasCapacityFor(new Item(560, amount), new Item(562, amount), new Item(554, amount * 5))) {
            player.message("You don't have enough inventory space to uncharge your trident.");
            return;
        }
        player.inventory.add(new Item(560, amount), -1, false);
        player.inventory.add(new Item(562, amount), -1, false);
        player.inventory.add(new Item(554, amount * 5), -1, false);
        player.inventory.refresh();
        player.tridentSwampCharges = 0;
        player.message("You uncharge your trident.");
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), and com.runehive.game.world.entity.mob.player.Player.tridentSwampCharges.
Referenced by inventory().
Member Data Documentation
CHARGE_LIMIT
final short com.runehive.content.itemaction.impl.TridentOfTheSwamp.CHARGE_LIMIT = 2500 static private
Definition at line 13 of file TridentOfTheSwamp.java.
Referenced by itemOnItem().
FORMATTER
final DecimalFormat com.runehive.content.itemaction.impl.TridentOfTheSwamp.FORMATTER = new DecimalFormat("#.#") static private
Definition at line 14 of file TridentOfTheSwamp.java.
Referenced by TridentOfTheSwamp().
TRIDENT_ID
final short com.runehive.content.itemaction.impl.TridentOfTheSwamp.TRIDENT_ID = 12899 static private
Definition at line 12 of file TridentOfTheSwamp.java.
Referenced by equipment(), inventory(), and itemOnItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/TridentOfTheSwamp.java