RuneHive-Game: com.runehive.game.world.entity.combat.hit.Hit Class Reference
com.runehive.game.world.entity.combat.hit.Hit Class Reference
A Hit object holds the damage amount and hitsplat data.
Public Member Functions
int getDamage ()
Gets the damage amount.
HitIcon getHitIcon ()
Gets the hit icon.
Hitsplat getHitsplat ()
Gets the damage type.
Hit[] getMultipleHits ()
Hit (Hit[] multipleHits)
Constructs a new Hit object.
Hit (int damage)
Constructs a new Hit object.
Hit (int damage, HitIcon hitIcon)
Constructs a new Hit object.
Hit (int damage, Hitsplat hitsplat)
Constructs a new Hit object.
Hit (int damage, Hitsplat hitsplat, HitIcon hitIcon)
Constructs a new Hit object.
Hit (int damage, Hitsplat hitsplat, HitIcon hitIcon, boolean accurate)
Constructs a new Hit object.
boolean isAccurate ()
Checks if the hit is accurate.
void modifyDamage (Function< Integer, Integer > modifier)
Sets the hit damage with a function.
void setAccurate (boolean accurate)
void setAs (Hit other)
void setDamage (int damage)
Sets the hit damage.
void setHitsplat (Hitsplat hitsplat)
void setIcon (HitIcon hitIcon)
Sets the hit icon.
Private Attributes
boolean accurate
Whether or not this hit is accurate.
int damage
The damage amount.
HitIcon hitIcon
The hit icon.
Hitsplat hitsplat
The hitsplat type.
Hit[] multipleHits = null
Detailed Description
A Hit object holds the damage amount and hitsplat data.
Author
Michael | Chex
Definition at line 10 of file Hit.java.
Constructor & Destructor Documentation
Hit() [1/6]
com.runehive.game.world.entity.combat.hit.Hit.Hit (Hit[] multipleHits)
Constructs a new Hit object.
Parameters
multipleHits A array of multiple hits
Definition at line 31 of file Hit.java.
{
        this.multipleHits = multipleHits;
        int totalDamage = 0;
        for(Hit hit : multipleHits) totalDamage += hit.damage;
        this.damage = totalDamage;
    }
References Hit(), and multipleHits.
Referenced by com.runehive.game.world.entity.combat.hit.CombatHit.CombatHit(), com.runehive.game.world.entity.combat.hit.CombatHit.CombatHit(), getMultipleHits(), Hit(), and setAs().
Hit() [2/6]
com.runehive.game.world.entity.combat.hit.Hit.Hit (int damage, Hitsplat hitsplat, HitIcon hitIcon, boolean accurate)
Constructs a new Hit object.
Parameters
damage the damage amount
hitsplat the hitsplat type
hitIcon the hit icon
accurate whether or not this hit is accurate
Definition at line 46 of file Hit.java.
{
        this.damage = damage;
        this.hitsplat = hitsplat;
        this.hitIcon = hitIcon;
        this.accurate = accurate;
    }
References accurate, damage, hitIcon, and hitsplat.
Hit() [3/6]
com.runehive.game.world.entity.combat.hit.Hit.Hit (int damage, Hitsplat hitsplat, HitIcon hitIcon)
Constructs a new Hit object.
Parameters
damage the damage amount
hitsplat the hitsplat type
hitIcon the hit icon
Definition at line 60 of file Hit.java.
{
        this(damage, hitsplat, hitIcon, damage > 0);
    }
References damage, hitIcon, and hitsplat.
Hit() [4/6]
com.runehive.game.world.entity.combat.hit.Hit.Hit (int damage, HitIcon hitIcon)
Constructs a new Hit object.
Parameters
damage the damage amount
hitIcon the hit icon
Definition at line 70 of file Hit.java.
{
        this(damage, Hitsplat.NORMAL, hitIcon, damage > 0);
    }
References damage, hitIcon, and com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL.
Hit() [5/6]
com.runehive.game.world.entity.combat.hit.Hit.Hit (int damage, Hitsplat hitsplat)
Constructs a new Hit object.
Parameters
damage the damage amount
hitsplat the hitsplat type
Definition at line 80 of file Hit.java.
{
        this(damage, hitsplat, HitIcon.NONE, damage > 0);
    }
References damage, hitsplat, and com.runehive.game.world.entity.combat.hit.HitIcon.NONE.
Hit() [6/6]
com.runehive.game.world.entity.combat.hit.Hit.Hit (int damage)
Constructs a new Hit object.
Parameters
damage the damage amount
Definition at line 89 of file Hit.java.
{
        this(damage, Hitsplat.NORMAL, HitIcon.NONE, damage > 0);
    }
References damage, com.runehive.game.world.entity.combat.hit.HitIcon.NONE, and com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL.
Member Function Documentation
getDamage()
int com.runehive.game.world.entity.combat.hit.Hit.getDamage ()
Gets the damage amount.
Returns
the damage amount
Definition at line 121 of file Hit.java.
{
        return damage;
    }
References damage.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask(), com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer.attack(), com.runehive.game.world.entity.mob.Mob.decrementHealth(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.fourthOption(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.secondOption(), com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBarrage(), com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBurst(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.thirdOption().
getHitIcon()
HitIcon com.runehive.game.world.entity.combat.hit.Hit.getHitIcon ()
Gets the hit icon.
Returns
the hit icon
Definition at line 139 of file Hit.java.
{
        return hitIcon;
    }
References hitIcon.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask().
getHitsplat()
Hitsplat com.runehive.game.world.entity.combat.hit.Hit.getHitsplat ()
Gets the damage type.
Returns
the damage type
Definition at line 130 of file Hit.java.
{
        return hitsplat;
    }
References hitsplat.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask().
getMultipleHits()
Hit[] com.runehive.game.world.entity.combat.hit.Hit.getMultipleHits ()
Definition at line 152 of file Hit.java.
{ return multipleHits; }
References Hit(), and multipleHits.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask().
isAccurate()
boolean com.runehive.game.world.entity.combat.hit.Hit.isAccurate ()
Checks if the hit is accurate.
Returns
true if the hit is accurate
Definition at line 148 of file Hit.java.
{
        return accurate;
    }
References accurate.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword.attack(), com.runehive.game.world.entity.combat.magic.MagicImpact.bloodBarrage(), com.runehive.game.world.entity.combat.magic.MagicImpact.bloodBurst(), com.runehive.game.world.entity.combat.magic.MagicImpact.iceBarrage(), com.runehive.game.world.entity.combat.magic.MagicImpact.iceBurst(), com.runehive.game.world.entity.combat.magic.MagicImpact.shadowBarrage(), com.runehive.game.world.entity.combat.magic.MagicImpact.shadowBurst(), com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBarrage(), and com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBurst().
modifyDamage()
void com.runehive.game.world.entity.combat.hit.Hit.modifyDamage (Function< Integer, Integer > modifier)
Sets the hit damage with a function.
If the damage is less than one, the damage is set to zero and hitsplat setVenom to block.
Parameters
modifier the modifier to damage
Definition at line 108 of file Hit.java.
{
        damage = modifier.apply(damage);
        if (damage <= 0) {
            damage = 0;
        }
    }
References damage.
Referenced by com.runehive.game.world.entity.combat.hit.CombatHit.copyAndModify(), com.runehive.game.world.entity.mob.Mob.decrementHealth(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.fourthOption().
setAccurate()
void com.runehive.game.world.entity.combat.hit.Hit.setAccurate (boolean accurate)
Definition at line 174 of file Hit.java.
{
        this.accurate = accurate;
    }
References accurate.
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.ArmadylSpritualMage.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.BandosSpritualMage.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SaradominPriest.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SpritualMage.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Kraken.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Tentacle.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.RangedAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.IceSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Magic.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.getHits(), and com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.getHits().
setAs()
void com.runehive.game.world.entity.combat.hit.Hit.setAs (Hit other)
Definition at line 167 of file Hit.java.
{
        this.damage = other.damage;
        this.hitIcon = other.hitIcon;
        this.hitsplat = other.hitsplat;
        this.accurate = other.accurate;
    }
References accurate, damage, Hit(), hitIcon, and hitsplat.
setDamage()
void com.runehive.game.world.entity.combat.hit.Hit.setDamage (int damage)
Sets the hit damage.
Parameters
damage the damage to set
Definition at line 98 of file Hit.java.
{
        this.damage = damage;
    }
References damage.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.IceSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.getHits(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.getHits(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.thirdOption().
setHitsplat()
void com.runehive.game.world.entity.combat.hit.Hit.setHitsplat (Hitsplat hitsplat)
Definition at line 163 of file Hit.java.
{
        this.hitsplat = hitsplat;
    }
References hitsplat.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomDragonfireAttack.getHits().
setIcon()
void com.runehive.game.world.entity.combat.hit.Hit.setIcon (HitIcon hitIcon)
Sets the hit icon.
Parameters
hitIcon the hit icon to set
Definition at line 159 of file Hit.java.
{
        this.hitIcon = hitIcon;
    }
References hitIcon.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits().
Member Data Documentation
accurate
boolean com.runehive.game.world.entity.combat.hit.Hit.accurate private
Whether or not this hit is accurate.
Definition at line 22 of file Hit.java.
Referenced by Hit(), isAccurate(), setAccurate(), and setAs().
damage
int com.runehive.game.world.entity.combat.hit.Hit.damage private
The damage amount.
Definition at line 13 of file Hit.java.
Referenced by getDamage(), Hit(), Hit(), Hit(), Hit(), Hit(), modifyDamage(), setAs(), and setDamage().
hitIcon
HitIcon com.runehive.game.world.entity.combat.hit.Hit.hitIcon private
The hit icon.
Definition at line 19 of file Hit.java.
Referenced by getHitIcon(), Hit(), Hit(), Hit(), setAs(), and setIcon().
hitsplat
Hitsplat com.runehive.game.world.entity.combat.hit.Hit.hitsplat private
The hitsplat type.
Definition at line 16 of file Hit.java.
Referenced by getHitsplat(), Hit(), Hit(), Hit(), setAs(), and setHitsplat().
multipleHits
Hit [] com.runehive.game.world.entity.combat.hit.Hit.multipleHits = null private
Definition at line 24 of file Hit.java.
Referenced by getMultipleHits(), and Hit().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/hit/Hit.java