RuneHive-Game: dev.advo.fs.FileServer Class Reference
dev.advo.fs.FileServer Class Reference
Public Member Functions
void start () throws Exception
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void start (String name, ChannelPipelineFactory pipelineFactory, int port)
Private Attributes
final FileServerHandler handler = new FileServerHandler()
final RequestWorkerPool pool = new RequestWorkerPool()
final ExecutorService service = Executors.newCachedThreadPool()
final Timer timer = new HashedWheelTimer()
Static Private Attributes
static final Logger logger = Logger.getLogger(FileServer.class.getName())
Detailed Description
Definition at line 21 of file FileServer.java.
Member Function Documentation
main()
void dev.advo.fs.FileServer.main (String[] args) static
Definition at line 24 of file FileServer.java.
{
        try {
            new FileServer().start();
        } catch (Throwable t) {
            logger.log(Level.SEVERE, "Error starting server.", t);
        }
    }
References logger, and start().
start() [1/2]
void dev.advo.fs.FileServer.start () throws Exception
Definition at line 40 of file FileServer.java.
{
        logger.info("Starting workers...");
        pool.start();
        logger.info("Starting services...");
        start("ondemand", new OnDemandPipelineFactory(handler, timer), NetworkConstants.SERVICE_PORT);
        logger.info("Ready for connections.");
    }
References handler, logger, pool, dev.advo.fs.net.NetworkConstants.SERVICE_PORT, start(), and timer.
Referenced by main(), com.runehive.RuneHive.start(), and start().
start() [2/2]
void dev.advo.fs.FileServer.start (String name, ChannelPipelineFactory pipelineFactory, int port) private
Definition at line 50 of file FileServer.java.
{
        SocketAddress address = new InetSocketAddress(port);
        logger.info("Binding " + name + " service to " + address + "...");
        ServerBootstrap bootstrap = new ServerBootstrap();
        bootstrap.setFactory(new NioServerSocketChannelFactory(service, service));
        bootstrap.setPipelineFactory(pipelineFactory);
        bootstrap.bind(address);
    }
References logger, and service.
Member Data Documentation
handler
final FileServerHandler dev.advo.fs.FileServer.handler = new FileServerHandler() private
Definition at line 35 of file FileServer.java.
Referenced by start().
logger
final Logger dev.advo.fs.FileServer.logger = Logger.getLogger(FileServer.class.getName()) static private
Definition at line 22 of file FileServer.java.
Referenced by main(), start(), and start().
pool
final RequestWorkerPool dev.advo.fs.FileServer.pool = new RequestWorkerPool() private
Definition at line 34 of file FileServer.java.
Referenced by start().
service
final ExecutorService dev.advo.fs.FileServer.service = Executors.newCachedThreadPool() private
Definition at line 32 of file FileServer.java.
Referenced by start().
timer
final Timer dev.advo.fs.FileServer.timer = new HashedWheelTimer() private
Definition at line 38 of file FileServer.java.
Referenced by start().
The documentation for this class was generated from the following file:
java/dev/advo/fs/FileServer.java