RuneHive-Game: com.runehive.content.skill.impl.magic.spell.SpellCasting Class Reference
com.runehive.content.skill.impl.magic.spell.SpellCasting Class Reference
Handles a player casting a non-combat spell (mostly on items).
Public Member Functions
boolean cast (Spell s)
Handles casting a combat spell.
void cast (Spell spell, Item item)
Handles casting the spell.
void enchant (int itemId)
void enchantItem (int itemID, int spellID)
void openBoltEnchant ()
SpellCasting (Player player)
Creates the SpellCasting.
Public Attributes
Stopwatch castingDelay = Stopwatch.start()
The casting stopwatch.
Spell spell
The casting spell.
Stopwatch vengeanceDelay = Stopwatch.start()
The vengeance stopwatch.
Private Member Functions
int getEnchantmentLevel (int spellID)
boolean hasEnchantRunes (int spellID)
Private Attributes
Player player
The player spell casting.
Static Private Attributes
static final Item[] ITEMS = {new Item(9236), new Item(9240), new Item(9237), new Item(9238), new Item(9241), new Item(9239), new Item(9242), new Item(9243), new Item(9244), new Item(9245)}
static final int[] LEVELS = {4, 7, 14, 24, 27, 29, 49, 57, 68, 87}
static final int[][] RUNES = {{564, 1}, {556, 2}, {564, 1}, {555, 1}, {558, 1}, {564, 1}, {557, 2}, {564, 1}, {555, 2}, {564, 1}, {556, 3}, {561, 1}, {564, 1}, {554, 2}, {564, 1}, {554, 5}, {565, 1}, {564, 1}, {557, 10}, {563, 2}, {564, 1}, {557, 15}, {566, 1}, {564, 1}, {554, 20}, {560, 1}}
Detailed Description
Handles a player casting a non-combat spell (mostly on items).
Author
Daniel
Definition at line 29 of file SpellCasting.java.
Constructor & Destructor Documentation
SpellCasting()
com.runehive.content.skill.impl.magic.spell.SpellCasting.SpellCasting (Player player)
Creates the SpellCasting.
Definition at line 44 of file SpellCasting.java.
{
        this.player = player;
        this.spell = null;
    }
References player.
Member Function Documentation
cast() [1/2]
boolean com.runehive.content.skill.impl.magic.spell.SpellCasting.cast (Spell s)
Handles casting a combat spell.
Definition at line 50 of file SpellCasting.java.
{
        if (player.skills.getLevel(Skill.MAGIC) < s.getLevel()) {
            player.send(new SendMessage("You need a magic level " + s.getLevel() + " of to cast " + s.getName() + "."));
            return false;
        }
        if (!PlayerRight.isDeveloper(player) && !player.isBot && !MagicRune.hasRunes(player, s.getRunes())) {
            player.send(new SendMessage("You do not have the required runes to cast this spell."));
            return false;
        }
        if (Activity.evaluate(player, it -> !it.canSpellCast(player))) {
            return false;
        }
        spell = s;
        player.inventory.removeAll(s.getRunes());
        return true;
    }
References com.runehive.content.activity.Activity.evaluate(), com.runehive.content.skill.impl.magic.spell.Spell.getLevel(), com.runehive.content.skill.impl.magic.spell.Spell.getName(), com.runehive.content.skill.impl.magic.spell.Spell.getRunes(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), com.runehive.game.world.entity.skill.Skill.MAGIC, player, and spell.
cast() [2/2]
void com.runehive.content.skill.impl.magic.spell.SpellCasting.cast (Spell spell, Item item)
Handles casting the spell.
Definition at line 71 of file SpellCasting.java.
{
        if (player.skills.getLevel(Skill.MAGIC) < spell.getLevel()) {
            player.send(new SendMessage("You need a Magic level of " + spell.getLevel() + " to do this!"));
            return;
        }
        if (spell.getRunes() != null) {
            if (!PlayerRight.isDeveloper(player) && !player.isBot && !MagicRune.hasRunes(player, spell.getRunes())) {
                player.send(new SendMessage("You do not have the required runes to do this!"));
                return;
            }
        }
        if (Activity.evaluate(player, it -> !it.canSpellCast(player))) {
            return;
        }
        player.action.execute(new SpellAction(player, spell, item), true);
    }
References com.runehive.content.activity.Activity.evaluate(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), com.runehive.game.world.entity.skill.Skill.MAGIC, player, and spell.
enchant()
void com.runehive.content.skill.impl.magic.spell.SpellCasting.enchant (int itemId)
Definition at line 176 of file SpellCasting.java.
{
        if (!player.interfaceManager.isInterfaceOpen(42750))
            return;
        if (!BoltEchantData.forItem(itemId).isPresent())
            return;
        BoltEchantData enchant = BoltEchantData.forItem(itemId).get();
        String boltName = ItemDefinition.get(enchant.bolt).getName();
        if (player.skills.get(Skill.MAGIC).getLevel() < enchant.levelRequired) {
            player.send(new SendMessage("You need a Magic level of " + enchant.levelRequired + " to enchant " + boltName + "."));
            return;
        }
        if (!player.inventory.contains(new Item(enchant.bolt, 10))) {
            player.send(new SendMessage("You need 10 " + boltName + " to do this!"));
            return;
        }
        if (!player.inventory.containsAll(enchant.runesRequired)) {
            player.send(new SendMessage("You do not have the required runes to do this!"));
            return;
        }
        player.inventory.removeAll(enchant.runesRequired);
        player.inventory.remove(enchant.bolt, 10);
        player.inventory.add(enchant.enchantedBolt, 10);
        player.skills.addExperience(Skill.MAGIC, 250 * Config.MAGIC_MODIFICATION);
        player.send(new SendMessage("@red@You have enchanted 10 " + boltName + (boltName.endsWith("bolts") ? "." : " bolts.")));
        AchievementHandler.activate(player, AchievementKey.ENCHANT_BOLTS, 10);
        openBoltEnchant();
    }
References com.runehive.content.achievement.AchievementHandler.activate(), enchant(), com.runehive.content.achievement.AchievementKey.ENCHANT_BOLTS, com.runehive.content.skill.impl.magic.enchant.BoltEchantData.forItem(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.skill.Skill.MAGIC, com.runehive.Config.MAGIC_MODIFICATION, openBoltEnchant(), and player.
Referenced by enchant().
enchantItem()
void com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem (int itemID, int spellID)
Definition at line 115 of file SpellCasting.java.
{
        SpellEnchant ens = SpellEnchant.forSpell(spellID);
        if (ens == null) {
            return;
        }
        SpellEnchantData enc = SpellEnchantData.forId(itemID);
        if (enc == null) {
            player.message("You can't enchant this item!");
            return;
        }
        if (player.skills.getMaxLevel(Skill.MAGIC) < enc.getLevel()) {
            player.message("You need a magic level of at least " + enc.getMagicLevel() + " to cast this spell.");
            return;
        }
        if (player.skills.getMaxLevel(Skill.CRAFTING) < enc.getCraftingLevel()) {
            player.message("You need a crafting level of at least " + enc.getCraftingLevel() + " to cast this spell.");
            return;
        }
        if (!player.inventory.contains(enc.getUnenchanted(), 1)) {
            return;
        }
        if (!hasEnchantRunes(spellID)) {
            player.message("You do not have enough runes to cast this spell.");
            return;
        }
        if (getEnchantmentLevel(spellID) != enc.getLevel()) {
            player.message("You can only enchant this jewelry using a level-" + enc.getLevel() + " enchantment spell.");
            return;
        }
        player.animate(enc.getAnimation());
        player.inventory.removeAll(ens.getRunes());
        player.inventory.remove(enc.getUnenchanted(), 1);
        player.inventory.add(enc.getEnchanted(), 1);
        player.send(new SendForceTab(Config.MAGIC_TAB));
        player.graphic(new Graphic(enc.getGFX(), true));
        player.skills.addExperience(Skill.MAGIC, enc.getXp() * Config.MAGIC_MODIFICATION);
    }
References com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.forId(), com.runehive.content.skill.impl.magic.enchant.SpellEnchant.forSpell(), com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getAnimation(), com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getCraftingLevel(), com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getEnchanted(), getEnchantmentLevel(), com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getGFX(), com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getLevel(), com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getMagicLevel(), com.runehive.content.skill.impl.magic.enchant.SpellEnchant.getRunes(), com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getUnenchanted(), com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getXp(), hasEnchantRunes(), com.runehive.game.world.entity.skill.Skill.MAGIC, com.runehive.Config.MAGIC_MODIFICATION, com.runehive.Config.MAGIC_TAB, and player.
getEnchantmentLevel()
int com.runehive.content.skill.impl.magic.spell.SpellCasting.getEnchantmentLevel (int spellID) private
Definition at line 95 of file SpellCasting.java.
{
        switch (spellID) {
            case 1155: //Lvl-1 enchant sapphire
                return 1;
            case 1165: //Lvl-2 enchant emerald
                return 2;
            case 1176: //Lvl-3 enchant ruby
                return 3;
            case 1180: //Lvl-4 enchant diamond
                return 4;
            case 1187: //Lvl-5 enchant dragonstone
                return 5;
            case 6003: //Lvl-6 enchant onyx
                return 6;
            case 40180: //Lvl-7 enchant zenyte
                return 7;
        }
        return 0;
    }
Referenced by enchantItem().
hasEnchantRunes()
boolean com.runehive.content.skill.impl.magic.spell.SpellCasting.hasEnchantRunes (int spellID) private
Definition at line 90 of file SpellCasting.java.
{
        SpellEnchant spell = SpellEnchant.forSpell(spellID);
        return spell != null && player.inventory.containsAll(spell.getRunes());
    }
References com.runehive.content.skill.impl.magic.enchant.SpellEnchant.forSpell(), player, and spell.
Referenced by enchantItem().
openBoltEnchant()
void com.runehive.content.skill.impl.magic.spell.SpellCasting.openBoltEnchant ()
Definition at line 162 of file SpellCasting.java.
{
        for (int index = 0; index < LEVELS.length; index++) {
            String color = player.skills.get(Skill.MAGIC).getLevel() < LEVELS[index] ? "@red@" : "@gre@";
            player.send(new SendString(color + "Magic " + LEVELS[index], 42756 + index));
        }
        for (int i = 0; i < RUNES.length; i++) {
            String color = player.inventory.contains(new Item(RUNES[i][0], RUNES[i][1])) ? "@gre@" : "@red@";
            int amount = player.inventory.computeAmountForId(RUNES[i][0]);
            player.send(new SendString(color + (amount >= RUNES[i][1] ? RUNES[i][1] + "" : amount) + "/" + RUNES[i][1], 42766 + i));
        }
        player.send(new SendItemOnInterface(42752, ITEMS));
        player.interfaceManager.open(42750);
    }
References ITEMS, LEVELS, com.runehive.game.world.entity.skill.Skill.MAGIC, player, and RUNES.
Referenced by enchant().
Member Data Documentation
castingDelay
Stopwatch com.runehive.content.skill.impl.magic.spell.SpellCasting.castingDelay = Stopwatch.start()
The casting stopwatch.
Definition at line 37 of file SpellCasting.java.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), and com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute().
ITEMS
final Item [] com.runehive.content.skill.impl.magic.spell.SpellCasting.ITEMS = {new Item(9236), new Item(9240), new Item(9237), new Item(9238), new Item(9241), new Item(9239), new Item(9242), new Item(9243), new Item(9244), new Item(9245)} static private
Definition at line 30 of file SpellCasting.java.
{new Item(9236), new Item(9240), new Item(9237), new Item(9238), new Item(9241), new Item(9239), new Item(9242), new Item(9243), new Item(9244), new Item(9245)};
Referenced by openBoltEnchant().
LEVELS
final int [] com.runehive.content.skill.impl.magic.spell.SpellCasting.LEVELS = {4, 7, 14, 24, 27, 29, 49, 57, 68, 87} static private
Definition at line 32 of file SpellCasting.java.
{4, 7, 14, 24, 27, 29, 49, 57, 68, 87};
Referenced by openBoltEnchant().
player
Player com.runehive.content.skill.impl.magic.spell.SpellCasting.player private
The player spell casting.
Definition at line 41 of file SpellCasting.java.
Referenced by cast(), cast(), enchant(), enchantItem(), hasEnchantRunes(), openBoltEnchant(), and SpellCasting().
RUNES
final int [][] com.runehive.content.skill.impl.magic.spell.SpellCasting.RUNES = {{564, 1}, {556, 2}, {564, 1}, {555, 1}, {558, 1}, {564, 1}, {557, 2}, {564, 1}, {555, 2}, {564, 1}, {556, 3}, {561, 1}, {564, 1}, {554, 2}, {564, 1}, {554, 5}, {565, 1}, {564, 1}, {557, 10}, {563, 2}, {564, 1}, {557, 15}, {566, 1}, {564, 1}, {554, 20}, {560, 1}} static private
Definition at line 31 of file SpellCasting.java.
{{564, 1}, {556, 2}, {564, 1}, {555, 1}, {558, 1}, {564, 1}, {557, 2}, {564, 1}, {555, 2}, {564, 1}, {556, 3}, {561, 1}, {564, 1}, {554, 2}, {564, 1}, {554, 5}, {565, 1}, {564, 1}, {557, 10}, {563, 2}, {564, 1}, {557, 15}, {566, 1}, {564, 1}, {554, 20}, {560, 1}};
Referenced by openBoltEnchant().
spell
Spell com.runehive.content.skill.impl.magic.spell.SpellCasting.spell
The casting spell.
Definition at line 35 of file SpellCasting.java.
Referenced by cast(), cast(), and hasEnchantRunes().
vengeanceDelay
Stopwatch com.runehive.content.skill.impl.magic.spell.SpellCasting.vengeanceDelay = Stopwatch.start()
The vengeance stopwatch.
Definition at line 39 of file SpellCasting.java.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/magic/spell/SpellCasting.java