RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Tanning Class Reference
com.runehive.content.skill.impl.crafting.impl.Tanning Class Reference
Handles tanning leathers.
Classes
enum TanData
The tan data.
Static Public Member Functions
static boolean click (Player player, int button)
Handles clicking the tan buttons on the itemcontainer.
static void open (Player player)
Handles opening the tanning itemcontainer.
static void tan (Player player, int amount, TanData data)
Tans the leather.
Detailed Description
Handles tanning leathers.
Author
Daniel
Definition at line 18 of file Tanning.java.
Member Function Documentation
click()
boolean com.runehive.content.skill.impl.crafting.impl.Tanning.click (Player player, int button) static
Handles clicking the tan buttons on the itemcontainer.
Parameters
player The player instance.
button The button identification.
Returns
If a button was clicked.
Leather
Hard leather
Snake hide
Snakeskin
Green leather
Blue leather
Red leather
Black leather
Definition at line 117 of file Tanning.java.
{
        switch (button) {
            /** Leather */
            case 14817:
                tan(player, 1, TanData.LEATHER);
                return true;
            case 14809:
                tan(player, 5, TanData.LEATHER);
                return true;
            case 14801:
                player.send(new SendInputAmount("How many leathers would you like to tan?", 2, input -> {
                    tan(player, Integer.parseInt(input), TanData.LEATHER);
                }));
                return true;
            case 14793:
                tan(player, 28, TanData.LEATHER);
                return true;
            /** Hard leather */
            case 14818:
                tan(player, 1, TanData.HARD_LEATHER);
                return true;
            case 14810:
                tan(player, 5, TanData.HARD_LEATHER);
                return true;
            case 14802:
                player.send(new SendInputAmount("How many leathers would you like to tan?", 2, input -> {
                    tan(player, Integer.parseInt(input), TanData.HARD_LEATHER);
                }));
                return true;
            case 14794:
                tan(player, 28, TanData.HARD_LEATHER);
                return true;
            /** Snake hide */
            case 14819:
                tan(player, 1, TanData.SNAKE_HIDE);
                return true;
            case 14811:
                tan(player, 5, TanData.SNAKE_HIDE);
                return true;
            case 14803:
                player.send(new SendInputAmount("How many leathers would you like to tan?", 2, input -> {
                    tan(player, Integer.parseInt(input), TanData.SNAKE_HIDE);
                }));
                return true;
            case 14795:
                tan(player, 28, TanData.SNAKE_HIDE);
                return true;
            /** Snakeskin */
            case 14820:
                tan(player, 1, TanData.SNAKESKIN);
                return true;
            case 14812:
                tan(player, 5, TanData.SNAKESKIN);
                return true;
            case 14804:
                player.send(new SendInputAmount("How many leathers would you like to tan?", 2, input -> {
                    tan(player, Integer.parseInt(input), TanData.SNAKESKIN);
                }));
                return true;
            case 14796:
                tan(player, 28, TanData.SNAKESKIN);
                return true;
            /** Green leather */
            case 14821:
                tan(player, 1, TanData.GREEN_LEATHER);
                return true;
            case 14813:
                tan(player, 5, TanData.GREEN_LEATHER);
                return true;
            case 14805:
                player.send(new SendInputAmount("How many leathers would you like to tan?", 2, input -> {
                    tan(player, Integer.parseInt(input), TanData.GREEN_LEATHER);
                }));
                return true;
            case 14797:
                tan(player, 28, TanData.GREEN_LEATHER);
                return true;
            /** Blue leather */
            case 14822:
                tan(player, 1, TanData.BLUE_LEATHER);
                return true;
            case 14814:
                tan(player, 5, TanData.BLUE_LEATHER);
                return true;
            case 14806:
                player.send(new SendInputAmount("How many leathers would you like to tan?", 2, input -> {
                    tan(player, Integer.parseInt(input), TanData.BLUE_LEATHER);
                }));
                return true;
            case 14798:
                tan(player, 28, TanData.BLUE_LEATHER);
                return true;
            /** Red leather */
            case 14823:
                tan(player, 1, TanData.RED_LEATHER);
                return true;
            case 14815:
                tan(player, 5, TanData.RED_LEATHER);
                return true;
            case 14807:
                player.send(new SendInputAmount("How many leathers would you like to tan?", 2, input -> {
                    tan(player, Integer.parseInt(input), TanData.RED_LEATHER);
                }));
                return true;
            case 14799:
                tan(player, 28, TanData.RED_LEATHER);
                return true;
            /** Black leather */
            case 14824:
                tan(player, 1, TanData.BLACK_LEATHER);
                return true;
            case 14816:
                tan(player, 5, TanData.BLACK_LEATHER);
                return true;
            case 14808:
                player.send(new SendInputAmount("How many leathers would you like to tan?", 2, input -> {
                    tan(player, Integer.parseInt(input), TanData.BLACK_LEATHER);
                }));
                return true;
            case 14800:
                tan(player, 28, TanData.BLACK_LEATHER);
                return true;
        }
        return false;
    }
References com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.BLACK_LEATHER, com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.BLUE_LEATHER, com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.GREEN_LEATHER, com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.HARD_LEATHER, com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.LEATHER, com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.RED_LEATHER, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.SNAKE_HIDE, com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.SNAKESKIN, and tan().
Referenced by com.runehive.content.skill.impl.crafting.Crafting.clickButton().
open()
void com.runehive.content.skill.impl.crafting.impl.Tanning.open (Player player) static
Handles opening the tanning itemcontainer.
Parameters
player The player instance.
Definition at line 67 of file Tanning.java.
{
        int count = 0;
        for (TanData data : TanData.values()) {
            player.send(new SendItemOnInterfaceZoom(14769 + count, 250, data.ingredient));
            player.send(new SendString((player.inventory.contains(data.ingredient) ? "<col=23db44>" : "<col=e0061c>") + Utility.formatEnum(data.name()), 14777 + count));
            player.send(new SendString((player.inventory.contains(new Item(Config.CURRENCY, data.cost)) ? "<col=23db44>" : "<col=e0061c>") + data.cost + " coins", 14785 + count));
            count++;
        }
        player.interfaceManager.open(14670);
    }
References com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.Config.CURRENCY, com.runehive.util.Utility.formatEnum(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.content.skill.impl.crafting.Crafting.clickNpc().
tan()
void com.runehive.content.skill.impl.crafting.impl.Tanning.tan (Player player, int amount, TanData data) static
Tans the leather.
Parameters
player The player instance.
amount The amount being tanned.
data The tan data.
Definition at line 86 of file Tanning.java.
{
        if (!player.inventory.contains(data.ingredient)) {
            player.send(new SendMessage("You do not have any " + ItemDefinition.get(data.ingredient).getName() + " to do this."));
            return;
        }
        int contain = player.inventory.computeAmountForId(data.ingredient);
        if (amount > contain)
            amount = contain;
        int cost = data.cost * amount;
        if (!player.inventory.contains(new Item(Config.CURRENCY, cost))) {
            player.send(new SendMessage("You need " + cost + " coins to tan " + amount + " " + ItemDefinition.get(data.ingredient).getName() + "!"));
            return;
        }
        player.inventory.remove(Config.CURRENCY, cost);
        player.inventory.remove(data.ingredient, amount);
        player.inventory.add(data.product, amount);
        player.send(new SendMessage("You successfully tan all the " + ItemDefinition.get(data.ingredient).getName() + " for " + amount + " coins.", true));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.Config.CURRENCY, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.ingredient, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.product, com.runehive.game.world.items.containers.ItemContainer.remove(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by click().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Tanning.java