RuneHive-Game: com.runehive.content.store.impl.DefaultStore.StoreRestockTask Class Reference
com.runehive.content.store.impl.DefaultStore.StoreRestockTask Class Reference
The task that will restock items in shop containers when needed.
Protected Member Functions
void tick ()
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Package Functions
StoreRestockTask (DefaultStore container)
Creates a new StoreRestockTask.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Private Member Functions
boolean restock (StoreItem item)
Attempts to restock item for the container.
Private Attributes
final DefaultStore container
The container that will be restocked.
Additional Inherited Members
Public Member Functions inherited from com.runehive.game.task.TickableTask
void execute ()
A function representing the unit of work that will be carried out.
TickableTask (boolean instant, int delay)
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Detailed Description
The task that will restock items in shop containers when needed.
Definition at line 186 of file DefaultStore.java.
Constructor & Destructor Documentation
StoreRestockTask()
com.runehive.content.store.impl.DefaultStore.StoreRestockTask.StoreRestockTask (DefaultStore container) package
Creates a new StoreRestockTask.
Definition at line 192 of file DefaultStore.java.
{
            super(false, 0);
            this.container = container;
        }
References container, and com.runehive.content.store.impl.DefaultStore.DefaultStore().
Member Function Documentation
restock()
boolean com.runehive.content.store.impl.DefaultStore.StoreRestockTask.restock (StoreItem item) private
Attempts to restock item for the container.
Definition at line 230 of file DefaultStore.java.
{
            if (!item.canReduce()) {
                return false;
            }
            final int reduceAmount = item.getAmount() > 100 ? (int) ((double) item.getAmount() * 0.05D) : 1;
            // if the item is not an original item
            if (!container.original.contains(item.getId())) {
                if (item.getAmount() - 1 <= 0) {
                    container.container.remove(item);
                } else {
                    item.decrementAmountBy(reduceAmount);
                }
                return true;
            } else {
                // the item is an original item
                final boolean originalItem = container.itemCache.containsKey(item.getId());
                final int originalAmount = container.itemCache.get(item.getId());
                // increment the original item if its not fully stocked
                if (originalItem && item.getAmount() < originalAmount) {
                    item.incrementAmount();
                    return true;
                } else if (originalItem && item.getAmount() > originalAmount) { // decrement original item if its over stocked
                    item.decrementAmountBy(reduceAmount);
                    return true;
                }
            }
            return false;
        }
References com.runehive.content.store.StoreItem.canReduce(), container, com.runehive.game.world.items.Item.decrementAmountBy(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), and com.runehive.game.world.items.Item.incrementAmount().
tick()
void com.runehive.content.store.impl.DefaultStore.StoreRestockTask.tick () protected
Reimplemented from com.runehive.game.task.TickableTask.
Definition at line 198 of file DefaultStore.java.
{
            if (container.restockCompleted() || !container.restock) {
                this.cancel();
                return;
            }
            if (tick >= 15) {
                final Item[] items = container.container.toArray();
                boolean restocked = false;
                for (Item item : items) {
                    if (item == null) {
                        continue;
                    }
                    if (item instanceof StoreItem) {
                        if (restock((StoreItem) item)) {
                            restocked = true;
                        }
                    }
                }
                if (restocked) {
                    for (Player player : container.players) {
                        if (player != null) {
                            player.send(new SendItemOnInterface(47551, container.container.toArray()));
                        }
                    }
                }
                tick = 0;
            }
        }
References com.runehive.game.task.Task.cancel(), container, com.runehive.content.store.impl.DefaultStore.items, com.runehive.content.store.impl.DefaultStore.restock, com.runehive.game.world.entity.mob.player.Player.send(), and tick().
Referenced by tick().
Member Data Documentation
container
final DefaultStore com.runehive.content.store.impl.DefaultStore.StoreRestockTask.container private
The container that will be restocked.
Definition at line 189 of file DefaultStore.java.
Referenced by restock(), StoreRestockTask(), and tick().
The documentation for this class was generated from the following file:
java/com/runehive/content/store/impl/DefaultStore.java