RuneHive-Game: com.runehive.game.action.ConsecutiveAction< T extends Mob > Class Template Reference
com.runehive.game.action.ConsecutiveAction< T extends Mob > Class Template Reference abstract
Public Member Functions
ConsecutiveAction (T mob)
Generates a new ConsecutiveAction object.
void execute ()
Public Member Functions inherited from com.runehive.game.action.Action< T >
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
abstract String getName ()
Gets the name of this action.
abstract WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
boolean prioritized ()
Determines if this action is prioritized.
Protected Member Functions
void add (Consumer< Action< T > > action)
Adds an action to the actions list.
void addFirst (Consumer< Action< T > > action)
Adds an action to the actions list.
Private Attributes
LinkedList< Consumer< Action< T > > > actions = new LinkedList<>()
The list of actions.
Detailed Description
Definition at line 8 of file ConsecutiveAction.java.
Constructor & Destructor Documentation
ConsecutiveAction()
com.runehive.game.action.ConsecutiveAction< T extends Mob >.ConsecutiveAction (T mob)
Generates a new ConsecutiveAction object.
Parameters
mob The mob to apply this action to.
Definition at line 19 of file ConsecutiveAction.java.
{
        super(mob, 1, true);
    }
References com.runehive.game.action.Action< T >.mob.
Member Function Documentation
add()
void com.runehive.game.action.ConsecutiveAction< T extends Mob >.add (Consumer< Action< T > > action) protected
Adds an action to the actions list.
Parameters
action The action.
Definition at line 35 of file ConsecutiveAction.java.
{
        actions.add(action);
    }
References com.runehive.game.action.Action< T >.Action(), and actions.
Referenced by com.runehive.game.action.impl.TeleportAction.init().
addFirst()
void com.runehive.game.action.ConsecutiveAction< T extends Mob >.addFirst (Consumer< Action< T > > action) protected
Adds an action to the actions list.
Parameters
action The action.
Definition at line 43 of file ConsecutiveAction.java.
{
        actions.addFirst(action);
    }
References com.runehive.game.action.Action< T >.Action(), and actions.
Referenced by com.runehive.game.action.impl.TeleportAction.start().
execute()
void com.runehive.game.action.ConsecutiveAction< T extends Mob >.execute ()
Definition at line 24 of file ConsecutiveAction.java.
{
        if (!actions.isEmpty()) {
            Consumer<Action<T>> action = actions.poll();
            action.accept(this);
        }
    }
References actions.
Member Data Documentation
actions
LinkedList<Consumer<Action<T> > > com.runehive.game.action.ConsecutiveAction< T extends Mob >.actions = new LinkedList<>() private
The list of actions.
Definition at line 11 of file ConsecutiveAction.java.
Referenced by add(), addFirst(), and execute().
The documentation for this class was generated from the following file:
java/com/runehive/game/action/ConsecutiveAction.java