RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Jewellery Class Reference
com.runehive.content.skill.impl.crafting.impl.Jewellery Class Reference
Handles crafting jewellery.
Classes
enum JewelleryData
The jewellery data.
enum JewelleryType
The jewellery type.
Static Public Member Functions
static void click (Player player, int item, int amount)
Handles clicking on the itemcontainer.
static void open (Player player)
Opens the jewellery creation itemcontainer.
Static Private Member Functions
static Action< Player > craft (Player player, JewelleryData jewellery, int amount)
The jewellery crafting animation.
Detailed Description
Handles crafting jewellery.
Author
Daniel
Definition at line 24 of file Jewellery.java.
Member Function Documentation
click()
void com.runehive.content.skill.impl.crafting.impl.Jewellery.click (Player player, int item, int amount) static
Handles clicking on the itemcontainer.
Parameters
player The player instance.
item The item being crafted.
amount The amount being crafted.
Definition at line 201 of file Jewellery.java.
{
        if (!JewelleryData.forItem(item).isPresent()) {
            return;
        }
        JewelleryData jewellery = JewelleryData.forItem(item).get();
        if (player.skills.getMaxLevel(Skill.CRAFTING) < jewellery.level) {
            String name = ItemDefinition.get(jewellery.product).getName();
            player.send(new SendMessage("You need a crafting level of " + jewellery.level + " to craft " + Utility.getAOrAn(name) + " " + name + "."));
            return;
        }
        boolean contains = true;
        for (Item i : jewellery.materials) {
            if (!player.inventory.contains(i)) {
                String req = i.getName();
                player.send(new SendMessage("You need " + Utility.getAOrAn(req) + " " + req + " to make this!"));
                contains = false;
            }
        }
        if (!contains)
            return;
        player.interfaceManager.close();
        player.action.execute(craft(player, jewellery, amount), true);
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.items.containers.ItemContainer.contains(), craft(), com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.game.action.ActionManager.execute(), com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.forItem(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.level, com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.materials, com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.product, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.skills.
craft()
Action< Player > com.runehive.content.skill.impl.crafting.impl.Jewellery.craft (Player player, JewelleryData jewellery, int amount) static private
The jewellery crafting animation.
Parameters
player The player instance.
jewellery The jewellery data being crafted.
amount The amount of jewellery being crafter.
Returns
The jewellery crafting action.
Definition at line 238 of file Jewellery.java.
{
        return new Action<Player>(player, 4, true) {
            int ticks = 0;
            @Override
            public void execute() {
                if (!player.inventory.containsAll(jewellery.materials)) {
                    player.send(new SendMessage("You do not have the required items to craft this!"));
                    cancel();
                    return;
                }
                player.animate(new Animation(899));
                for (int index = 0; index < jewellery.materials.length; index++) {
                    if (index != 0) {
                        player.inventory.remove(jewellery.materials[index], -1, false);
                    }
                }
                player.inventory.add(new Item(jewellery.product), -1, true);
                player.skills.addExperience(Skill.CRAFTING, jewellery.experience * Config.CRAFTING_MODIFICATION);
                player.send(new SendMessage("You have crafted " + Utility.getAOrAn(new Item(jewellery.product).getName()) + " " + new Item(jewellery.product).getName() + "."));
                if (++ticks == amount) {
                    cancel();
                    return;
                }
            }
            @Override
            public String getName() {
                return "Jewellery crafting";
            }
            @Override
            public boolean prioritized() {
                return false;
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
        };
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.Config.CRAFTING_MODIFICATION, com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.experience, com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.materials, com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.product, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by click().
open()
void com.runehive.content.skill.impl.crafting.impl.Jewellery.open (Player player) static
Opens the jewellery creation itemcontainer.
Parameters
player The player instance.
Definition at line 172 of file Jewellery.java.
{
        int[] items = JewelleryData.getItems(JewelleryType.RING);
        for (int i = 0; i < items.length; i++) {
            player.send(new SendItemOnInterfaceSlot(JewelleryType.RING.identification, items[i], 1, i));
        }
        items = JewelleryData.getItems(JewelleryType.NECKLACE);
        for (int i = 0; i < items.length; i++) {
            player.send(new SendItemOnInterfaceSlot(JewelleryType.NECKLACE.identification, items[i], 1, i));
        }
        items = JewelleryData.getItems(JewelleryType.AMULET);
        for (int i = 0; i < items.length; i++) {
            player.send(new SendItemOnInterfaceSlot(JewelleryType.AMULET.identification, items[i], 1, i));
        }
        player.send(new SendInterfaceConfig(4229, 0, -1));
        player.send(new SendInterfaceConfig(4235, 0, -1));
        player.send(new SendInterfaceConfig(4241, 0, -1));
        player.interfaceManager.open(4161);
    }
References com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryType.AMULET, com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.getItems(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryType.NECKLACE, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryType.RING, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.content.skill.impl.crafting.Crafting.clickObject().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Jewellery.java