RuneHive-Game: com.runehive.content.dialogue.impl.WellOfGoodwillDialogue Class Reference
com.runehive.content.dialogue.impl.WellOfGoodwillDialogue Class Reference
Created by Daniel on 2017-06-02.
Public Member Functions
void sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.dialogue.Dialogue
static final boolean isDialogueButton (int button)
Checks if the button triggered is an optional dialogue button.
Static Public Attributes inherited from com.runehive.content.dialogue.Dialogue
static final ImmutableList< Integer > DIALOGUE_BUTTONS = ImmutableList.of(2461, 2471, 2482, 2462, 2472, 2483, 2473, 2484, 2485, 2494, 2495, 2496, 2497, 2498)
The action buttons responsible for dialogues.
Detailed Description
Created by Daniel on 2017-06-02.
Definition at line 11 of file WellOfGoodwillDialogue.java.
Member Function Documentation
sendDialogues()
void com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Parameters
factory The factory for this dialogue.
Reimplemented from com.runehive.content.dialogue.Dialogue.
Definition at line 14 of file WellOfGoodwillDialogue.java.
{
        factory.sendStatement("Greetings "+factory.getPlayer().getName()+".", "How may the well be of assistance today?").sendOption("How does this work?", () -> {
            factory.onAction(() -> {
                factory.sendStatement(
                    "Players may all contribute as much gold as they desire",
                    "towards the well. In return, once the well reaches",
                    Utility.formatDigits(WellOfGoodwill.MAXIMUM) + " the entire server will be granted").sendStatement(
                    "double experience for 30minutes.",
                    "After those 30 minutes the well will need to be replenished.",
                    "Well data is saved and stores during server restarts and shutdowns.",
                    "Ensuring safety for contributors."
                ).execute();
            });
        }, "Check time left", () -> {
            if (!WellOfGoodwill.isActive()) {
                factory.sendStatement("").sendStatement("The well is not active!").execute();
                return;
            }
            factory.sendStatement("").sendStatement("Time left: " + (30 - WellOfGoodwill.activeTime) + " minutes").execute();
        }, "Check current status", () -> {
            WellOfGoodwill.open(factory.getPlayer());
        }, "Nevermind", factory::clear).execute();
    }
References com.runehive.content.WellOfGoodwill.activeTime, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.WellOfGoodwill.isActive(), com.runehive.content.WellOfGoodwill.MAXIMUM, com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.content.WellOfGoodwill.open(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
The documentation for this class was generated from the following file:
java/com/runehive/content/dialogue/impl/WellOfGoodwillDialogue.java