RuneHive-Game: com.runehive.content.activity.impl.warriorguild.WarriorGuild Class Reference
com.runehive.content.activity.impl.warriorguild.WarriorGuild Class Reference
This class handles the warrior's guild activity.
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
ActivityDeathType deathType ()
void end ()
Handles ending the activity.
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
void sequence ()
Sequences the activity.
void update ()
The update method.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
Static Public Member Functions
static WarriorGuild create (Player player)
Handes creating a new warrior guild activity for the player.
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Public Attributes
WarriorGuildState state
The warrior guild state for this activity.
Protected Member Functions
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
Optional< WarriorGuildActivityListener > getListener ()
Gets an Optional of the ActivityListener for this activity.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
void start ()
Starts the next activity stage.
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
Private Member Functions
void summon (int index, AnimatorData animator)
Handles summoning the animated npc.
WarriorGuild (Player player)
Contructs a new WarriorGuild.
Private Attributes
Npc animated
The animated npc.
Item item
final WarriorGuildActivityListener listener = new WarriorGuildActivityListener(this)
The warrior guild activity listener for this activity.
final Player player
The player in the warrior guild activity.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
This class handles the warrior's guild activity.
Author
Daniel
Definition at line 41 of file WarriorGuild.java.
Constructor & Destructor Documentation
WarriorGuild()
com.runehive.content.activity.impl.warriorguild.WarriorGuild.WarriorGuild (Player player) private
Contructs a new WarriorGuild.
Definition at line 58 of file WarriorGuild.java.
{
        super(3, Mob.DEFAULT_INSTANCE);
        this.player = player;
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, and player.
Referenced by create().
Member Function Documentation
canTeleport()
boolean com.runehive.content.activity.impl.warriorguild.WarriorGuild.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 283 of file WarriorGuild.java.
{
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 140 of file WarriorGuild.java.
{
        if (animated != null) {
            remove(animated);
        }
    }
References animated.
Referenced by end(), onLogout(), and onRegionChange().
clickNpc()
boolean com.runehive.content.activity.impl.warriorguild.WarriorGuild.clickNpc (Player player, NpcInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 179 of file WarriorGuild.java.
{
        int npc = event.getNpc().id;
        if (npc == 2461) {
            player.dialogueFactory.sendDialogue(new KamfreenaDialogue());
            return true;
        }
        if (npc == 2462) {
            Store.STORES.get("Shanomi's Armour Store").open(player);
            return true;
        }
        return false;
    }
References player, and com.runehive.content.store.Store.STORES.
clickObject()
boolean com.runehive.content.activity.impl.warriorguild.WarriorGuild.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 147 of file WarriorGuild.java.
{
        int object = event.getObject().getId();
        if (object == 16671) {
            player.move(new Position(2841, 3538, 2));
            return true;
        }
        if (object == 24303) {
            player.move(new Position(2841, 3538, 0));
            return true;
        }
        if (object == 24306 || object == 24309) {
            if (state == WarriorGuildState.ANIMATOR) {
                if (!SkillCape.isEquipped(player, SkillCape.ATTACK)) {
                    if (!player.inventory.contains(new Item(8851, 25))) {
                        player.dialogueFactory.sendStatement("You need at least 25 warrior guild tokens to enter.").execute();
                        return true;
                    }
                }
                player.inventory.remove(new Item(8851, 25));
                state = WarriorGuildState.CYCLOPS;
                player.move(new Position(player.getX() + 1, player.getY(), 2));
                World.schedule(new WarriorGuildCyclopEvent(player));
            } else if (state == WarriorGuildState.CYCLOPS) {
                player.move(new Position(player.getX() - 2, player.getY(), 2));
                state = WarriorGuildState.ANIMATOR;
            }
            return true;
        }
        return false;
    }
References com.runehive.content.activity.impl.warriorguild.WarriorGuildState.ANIMATOR, com.runehive.content.skillcape.SkillCape.ATTACK, com.runehive.content.activity.impl.warriorguild.WarriorGuildState.CYCLOPS, com.runehive.content.skillcape.SkillCape.isEquipped(), player, com.runehive.game.world.World.schedule(), and state.
create()
WarriorGuild com.runehive.content.activity.impl.warriorguild.WarriorGuild.create (Player player) static
Handes creating a new warrior guild activity for the player.
Definition at line 64 of file WarriorGuild.java.
{
        WarriorGuild minigame = new WarriorGuild(player);
        minigame.state = WarriorGuildState.ANIMATOR;
        minigame.add(player);
        return minigame;
    }
References com.runehive.content.activity.Activity.add(), com.runehive.content.activity.impl.warriorguild.WarriorGuildState.ANIMATOR, player, and WarriorGuild().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity(), and com.runehive.content.teleport.TeleportHandler.special().
deathType()
ActivityDeathType com.runehive.content.activity.impl.warriorguild.WarriorGuild.deathType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 292 of file WarriorGuild.java.
{
        return ActivityDeathType.NORMAL;
    }
References com.runehive.content.activity.ActivityDeathType.NORMAL.
end()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.end ()
Handles ending the activity.
Definition at line 72 of file WarriorGuild.java.
                      {
        cleanup();
        finish();
    }
References cleanup(), and finish().
Referenced by onDeath().
finish()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 134 of file WarriorGuild.java.
{
        remove(player);
        ActivityPanel.clear(player);
    }
References com.runehive.content.activity.panel.ActivityPanel.clear(), and player.
Referenced by end(), onLogout(), and onRegionChange().
getListener()
Optional< WarriorGuildActivityListener > com.runehive.content.activity.impl.warriorguild.WarriorGuild.getListener () protected
Gets an Optional of the ActivityListener for this activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 297 of file WarriorGuild.java.
{
        return Optional.of(listener);
    }
References listener.
getType()
ActivityType com.runehive.content.activity.impl.warriorguild.WarriorGuild.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 302 of file WarriorGuild.java.
{
        return ActivityType.WARRIOR_GUILD;
    }
References com.runehive.content.activity.ActivityType.WARRIOR_GUILD.
onDeath()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 258 of file WarriorGuild.java.
{
        if (mob.isNpc()) {
            World.schedule(new NpcDeath(mob.getNpc()));
            player.send(new SendEntityHintArrow(player, true));
            animated = null;
            return;
        }
        remove(mob);
        mob.move(Config.DEFAULT_POSITION);
        end();
    }
References animated, com.runehive.Config.DEFAULT_POSITION, end(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.move(), player, and com.runehive.game.world.World.schedule().
onLogout()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 238 of file WarriorGuild.java.
{
        if (state == WarriorGuildState.CYCLOPS)
            player.move(new Position(2846, 3540, 2));
        cleanup();
        finish();
    }
References cleanup(), com.runehive.content.activity.impl.warriorguild.WarriorGuildState.CYCLOPS, finish(), player, and state.
onRegionChange()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 246 of file WarriorGuild.java.
{
        if (!Area.inWarriorGuild(player)) {
            if (animated != null) {
                player.send(new SendMessage("The animated armour vanishes as you have leave the region, taking your armour"));
                player.send(new SendMessage("with him."));
            }
            cleanup();
            finish();
        }
    }
References animated, cleanup(), finish(), com.runehive.game.world.position.Area.inWarriorGuild(), and player.
pickupItem()
boolean com.runehive.content.activity.impl.warriorguild.WarriorGuild.pickupItem (Player player, PickupItemInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 228 of file WarriorGuild.java.
{
        if (WarriorGuildUtility.getDefender(player) == event.getItem().getId()) {
            player.pickup(event.getItem(), event.getPosition());
            CollectionLog.logItem(player, CollectionLogData.WARRIORS_GUILD, item.getId(), 1);
        return true;
        }
        return false;
    }
References com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefender(), item, com.runehive.content.collectionlog.CollectionLog.logItem(), player, and com.runehive.content.collectionlog.CollectionLogData.WARRIORS_GUILD.
sequence()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.sequence ()
Sequences the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 288 of file WarriorGuild.java.
{
    }
start()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 129 of file WarriorGuild.java.
{
    }
summon()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.summon (int index, AnimatorData animator) private
Handles summoning the animated npc.
Definition at line 78 of file WarriorGuild.java.
{
        boolean walk_state = player.movement.isRunningToggled();
        animated = new Npc(WarriorGuildUtility.ANIMATED[index], animator.objectPosition);
        animated.owner = player;
        animated.setVisible(false);
        add(animated);
        player.movement.setRunningToggled(false);
        player.locking.lock(LockType.MASTER_WITH_MOVEMENT);
        for (int i = 0; i < WarriorGuildUtility.ARMOUR[index].length; i++) {
            player.inventory.remove(WarriorGuildUtility.ARMOUR[index][i]);
        }
        World.schedule(new Task(1) {
            int count = 0;
            @Override
            protected void execute() {
                if (count == 0) {
                    player.animate(new Animation(827, UpdatePriority.HIGH));
                    player.send(new SendMessage("You place the armour pieces inside the animator..."));
                } else if (count == 2) {
                    player.send(new SendMessage("The animator begins to hum, something appears to be working..."));
                    player.walkExactlyTo(animator.walkToPosition);
                } else if (count == 7) {
                    animated.setVisible(true);
                    animated.animate(4166);
                    animated.speak("I'M ALIVE!");
                    animated.getCombat().attack(player);
                    player.face(animated);
                    player.send(new SendEntityHintArrow(animated));
                    player.send(new SendMessage("The animated armour comes to life!"));
                    cancel();
                }
                count++;
            }
            @Override
            protected void onCancel(boolean logout) {
                player.blockFace = false;
                player.locking.unlock();
                player.movement.reset();
                player.movement.setRunningToggled(walk_state);
            }
        });
    }
References com.runehive.content.activity.Activity.add(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.ANIMATED, animated, com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.ARMOUR, com.runehive.game.UpdatePriority.HIGH, com.runehive.game.world.entity.mob.data.LockType.MASTER_WITH_MOVEMENT, com.runehive.content.activity.impl.warriorguild.AnimatorData.objectPosition, player, com.runehive.game.world.World.schedule(), and com.runehive.content.activity.impl.warriorguild.AnimatorData.walkToPosition.
Referenced by useItem().
update()
void com.runehive.content.activity.impl.warriorguild.WarriorGuild.update ()
The update method.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 271 of file WarriorGuild.java.
{
        if (state == WarriorGuildState.ANIMATOR)
            return;
        if (state == WarriorGuildState.CYCLOPS) {
            int current = WarriorGuildUtility.getDefenderIndex(player);
            int progress = (int) Utility.getPercentageAmount(current + 1, 8);
            Item defender = new Item(WarriorGuildUtility.getDefender(player), 1);
            ActivityPanel.update(player, progress, "Warrior Guild", defender, "Cyclops will be dropping:", "<col=FF5500>" + defender.getName(), "Chance: <col=FF5500>1/20</col>");
        }
    }
References com.runehive.content.activity.impl.warriorguild.WarriorGuildState.ANIMATOR, com.runehive.content.activity.impl.warriorguild.WarriorGuildState.CYCLOPS, com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefender(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefenderIndex(), com.runehive.game.world.items.Item.getName(), com.runehive.util.Utility.getPercentageAmount(), player, state, and com.runehive.content.activity.panel.ActivityPanel.update().
useItem()
boolean com.runehive.content.activity.impl.warriorguild.WarriorGuild.useItem (Player player, ItemOnObjectInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 193 of file WarriorGuild.java.
{
        if (animated != null) {
            player.dialogueFactory.sendStatement("You already have an animated armour spawned!").execute();
            return false;
        }
        int object = event.getObject().getId();
        if (object != 23955) {
            return false;
        }
        Item used = event.getItem();
        int armourIndex = WarriorGuildUtility.contains(player, used.getId());
        if (armourIndex == -1) {
            return true;
        }
        Optional<AnimatorData> animator = AnimatorData.getAnimator(event.getObject().getPosition());
        if (!animator.isPresent()) {
            return true;
        }
        if (!player.getPosition().equals(animator.get().standPosition)) {
            player.dialogueFactory.sendStatement("Please stand in front of the animator!").execute();
            return true;
        }
        summon(armourIndex, animator.get());
        return true;
    }
References animated, com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.contains(), com.runehive.content.activity.impl.warriorguild.AnimatorData.getAnimator(), com.runehive.game.world.items.Item.getId(), player, and summon().
Member Data Documentation
animated
Npc com.runehive.content.activity.impl.warriorguild.WarriorGuild.animated private
The animated npc.
Definition at line 47 of file WarriorGuild.java.
Referenced by cleanup(), onDeath(), onRegionChange(), summon(), and useItem().
item
Item com.runehive.content.activity.impl.warriorguild.WarriorGuild.item private
Definition at line 52 of file WarriorGuild.java.
Referenced by pickupItem().
listener
final WarriorGuildActivityListener com.runehive.content.activity.impl.warriorguild.WarriorGuild.listener = new WarriorGuildActivityListener(this) private
The warrior guild activity listener for this activity.
Definition at line 55 of file WarriorGuild.java.
Referenced by getListener().
player
final Player com.runehive.content.activity.impl.warriorguild.WarriorGuild.player private
The player in the warrior guild activity.
Definition at line 44 of file WarriorGuild.java.
Referenced by canTeleport(), clickNpc(), clickObject(), create(), finish(), onDeath(), onLogout(), onRegionChange(), pickupItem(), summon(), update(), useItem(), and WarriorGuild().
state
WarriorGuildState com.runehive.content.activity.impl.warriorguild.WarriorGuild.state
The warrior guild state for this activity.
Definition at line 50 of file WarriorGuild.java.
Referenced by clickObject(), onLogout(), and update().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/warriorguild/WarriorGuild.java