RuneHive-Game: com.runehive.util.tools.wiki.impl.ItemDefParser Class Reference
com.runehive.util.tools.wiki.impl.ItemDefParser Class Reference
Classes
class Definition
Static Public Member Functions
static void main (String[] args) throws InterruptedException
Protected Member Functions
void finish ()
Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
void execute (Runnable runnable)
Private Member Functions
ItemDefParser ()
Static Private Member Functions
static String format (String name)
static LinkedList< WikiTable > generateTables ()
static List< Definition > parseDefinitions ()
Static Private Attributes
static final Logger logger = LogManager.getLogger(ItemDefParser.class)
Additional Inherited Members
Public Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
void begin () throws InterruptedException
Begins parsing wiki tables for all the names provided.
WikiTableParser (LinkedList< WikiTable > tables)
Constructs a new WikiTableParser object.
Static Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
static void writeToJson (String name, JsonElement array)
Writes the parsed wiki dump to a json file in ./data/wiki named as the name parameter.
Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
final LinkedList< WikiTable > tables
The WikiTable list to parse.
Static Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create()
The gson object.
static final String WIKI_LINK = "http://oldschoolrunescape.wikia.com/wiki/"
The path to the wiki page address.
Detailed Description
Definition at line 21 of file ItemDefParser.java.
Constructor & Destructor Documentation
ItemDefParser()
com.runehive.util.tools.wiki.impl.ItemDefParser.ItemDefParser () private
Definition at line 25 of file ItemDefParser.java.
{
        super(generateTables());
    }
References generateTables().
Referenced by main().
Member Function Documentation
finish()
void com.runehive.util.tools.wiki.impl.ItemDefParser.finish () protected
Reimplemented from com.runehive.util.tools.wiki.parser.WikiTableParser.
Definition at line 191 of file ItemDefParser.java.
{
        JsonArray array = new JsonArray();
        for (WikiTable table : tables) {
            array.addAll(table.getTable());
        }
        writeToJson("wiki_item_dump", array);
    }
References com.runehive.util.tools.wiki.parser.WikiTableParser.tables, and com.runehive.util.tools.wiki.parser.WikiTableParser.writeToJson().
format()
String com.runehive.util.tools.wiki.impl.ItemDefParser.format (String name) static private
Definition at line 199 of file ItemDefParser.java.
{
        name = Utility.capitalizeSentence(name);
        name = name.replace(" ", "_");
        return name;
    }
References com.runehive.util.Utility.capitalizeSentence().
Referenced by generateTables().
generateTables()
LinkedList< WikiTable > com.runehive.util.tools.wiki.impl.ItemDefParser.generateTables () static private
Definition at line 34 of file ItemDefParser.java.
{
        List<Definition> definitions = parseDefinitions();
        LinkedList<WikiTable> tables = new LinkedList<>();
        String link = "https://oldschoolrunescape.fandom.com/wiki/Category:Items";
        Iterator<Definition> iterator = definitions.iterator();
        while (iterator.hasNext()) {
            Definition definition = iterator.next();
            iterator.remove();
            tables.add(new WikiTable(link + format(definition.name)) {
                @Override
                protected void parseDocument(Document document) {
                    Elements infobox = document.select(".wikitable.infobox");
                    Elements equipment = document.select(".wikitable.smallpadding");
                    int idx = 0;
                    EquipmentType type = EquipmentType.NOT_WIELDABLE;
                    boolean twoHanded = false;
                    int[] bonuses = null;
                    for (Element info : infobox) {
                        JsonObject object = new JsonObject();
                        Elements attributes = infobox.select("a");
                        String destroyMessage = "Drop";
                        double weight = 0;
                        boolean tradeable = false;
                        for (Element attribute : attributes) {
                            String attr = attribute.attr("title");
                            try {
                                switch (attr) {
                                    case "Tradeable": {
                                        tradeable = attribute.parent().nextElementSibling().text().equalsIgnoreCase("Yes");
                                        break;
                                    }
                                    case "Destroy": {
                                        destroyMessage = attribute.parent().nextElementSibling().text();
                                        break;
                                    }
                                    case "Weight": {
                                        Element element = attribute.parent().nextElementSibling();
                                        String alchemy = element.text().replaceAll("[^-\\d.]", "");
                                        if (!alchemy.matches("-?[0-9]*\\.?[0-9]*")) {
                                            alchemy = element.children().last().nextSibling().toString().replaceAll("[^-\\d.]", "");
                                        }
                                        if (!alchemy.isEmpty())
                                            weight = Double.parseDouble(alchemy);
                                        break;
                                    }
                                }
                            } catch (Exception ignored) {
                                logger.warn("Exception while parsing item [id=" + definition.id + ", name=" + definition.name + "]", ignored);
                            }
                        }
                        try {
                            if (!equipment.isEmpty()) {
                                bonuses = new int[Equipment.SIZE];
                                Elements equipmentInfo = equipment.select("td");
                                int ind = 0;
                                if (equipmentInfo.size() > idx) {
                                    do {
                                        Element attribute = equipmentInfo.get(idx++);
                                        if (attribute.attr("style").equals("text-align: center; width: 35px;")
                                                || attribute.attr("style").equals("text-align: center; width: 30px;")) {
                                            bonuses[ind++ % Equipment.SIZE] = Integer.parseInt(attribute.text().replace("%", ""));
                                        }
                                    } while (ind < Equipment.SIZE);
                                }
                                for (Element attribute : equipment.select("img")) {
                                    switch (attribute.attr("data-image-key")) {
                                        case "Head_slot.png":
                                            type = EquipmentType.HELM; // TODO
                                            break;
                                        case "Cape_slot.png":
                                            type = EquipmentType.CAPE;
                                            break;
                                        case "Weapon_slot.png":
                                            type = EquipmentType.WEAPON;
                                            break;
                                        case "Neck_slot.png":
                                            type = EquipmentType.AMULET;
                                            break;
                                        case "Ammo_slot.png":
                                            type = EquipmentType.ARROWS;
                                            break;
                                        case "Shield_slot.png":
                                            type = EquipmentType.SHIELD;
                                            break;
                                        case "Torso_slot.png":
                                            type = EquipmentType.BODY; // TODO
                                            break;
                                        case "Legs_slot.png":
                                            type = EquipmentType.LEGS;
                                            break;
                                        case "Gloves_slot.png":
                                            type = EquipmentType.GLOVES;
                                            break;
                                        case "Boots_slot.png":
                                            type = EquipmentType.BOOTS;
                                            break;
                                        case "Ring_slot.png":
                                            type = EquipmentType.RING;
                                            break;
                                        case "2h_slot.png":
                                            type = EquipmentType.WEAPON;
                                            twoHanded = true;
                                            break;
                                    }
                                }
                            }
                        } catch (Exception ignored) {
                            bonuses = null;
                            type = EquipmentType.NOT_WIELDABLE;
                            logger.warn("Exception while parsing item equipment data [id=" + definition.id + ", name=" + definition.name + "]", ignored);
                        }
                        object.addProperty("name", info.select("caption").text());
                        if (!destroyMessage.equals("Drop"))
                            object.addProperty("destroy-message", destroyMessage);
                        if (tradeable)
                            object.addProperty("tradable", true);
                        if (twoHanded)
                            object.addProperty("two-handed", true);
                        if (weight != 0)
                            object.addProperty("weight", weight);
                        if (type != EquipmentType.NOT_WIELDABLE)
                            object.addProperty("equipment-type", type.name());
                        if (bonuses != null) {
                            for (int index = 0; index < BONUS_CONFIG_FIELD_NAMES.length; index++) {
                                String bonusName = BONUS_CONFIG_FIELD_NAMES[index];
                                if (bonuses[index] != 0) {
                                    object.addProperty(bonusName, bonuses[index]);
                                }
                            }
                        }
                        if (!table.contains(object)) {
                            table.add(object);
                        }
                    }
                }
            });
        }
        return tables;
    }
References format(), com.runehive.util.tools.wiki.impl.ItemDefParser.Definition.name, parseDefinitions(), and com.runehive.util.tools.wiki.parser.WikiTableParser.tables.
Referenced by ItemDefParser().
main()
void com.runehive.util.tools.wiki.impl.ItemDefParser.main (String[] args) throws InterruptedException static
Definition at line 29 of file ItemDefParser.java.
{
        ItemDefParser parser = new ItemDefParser();
        parser.begin();
    }
References ItemDefParser().
parseDefinitions()
List< Definition > com.runehive.util.tools.wiki.impl.ItemDefParser.parseDefinitions () static private
Definition at line 205 of file ItemDefParser.java.
{
        Set<String> added = new HashSet<>();
        List<Definition> definitions = new LinkedList<>();
        new GsonParser("wiki/wiki_item_dump") {
            @Override
            protected void parse(JsonObject data) {
                Definition definition = new Definition();
                definition.id = data.get("id").getAsInt();
                definition.name = data.get("name").getAsString();
                if (added.contains(definition.name))
                    return;
                added.add(definition.name);
                definitions.add(definition);
            }
        }.run();
        added.clear();
        return definitions;
    }
References com.runehive.util.tools.wiki.impl.ItemDefParser.Definition.name.
Referenced by generateTables().
Member Data Documentation
logger
final Logger com.runehive.util.tools.wiki.impl.ItemDefParser.logger = LogManager.getLogger(ItemDefParser.class) static private
Definition at line 23 of file ItemDefParser.java.
The documentation for this class was generated from the following file:
java/com/runehive/util/tools/wiki/impl/ItemDefParser.java