RuneHive-Game: com.runehive.content.lms.LMSGame Class Reference
com.runehive.content.lms.LMSGame Class Reference
Static Public Member Functions
static boolean canAttack (Player player, Player target)
Checks if the player is allowed to attack the target.
static int getKeyId ()
The key id the player gets after a kill.
static void giveItems (Player player, boolean clear)
Handles giving the player correct inventory and equipment.
static void handleFog ()
Handles the fog closing in on the save zone.
static boolean inGameArea (Player player)
Handles checking if the player is in the LMS game area.
static boolean isActivePlayer (Player player)
Checks if a player is a active player within the LMS game.
static void moveToGame (List< Player > players)
Handles moving all the players to the game.
static void onDeath (Player player, boolean forceRemove)
Handles when a player within the LMS game dies.
static void onKill (Player killer)
Handles the killers stuff.
static void processPlayer (Player player)
Handles processing the player if hes a active player within the LMS game.
static void reset (Player player)
Handles resetting the player that was in the game and either left by dying or other means.
static void resupplyKiller (Player player)
Handles resupplying the killer.
static void rollChest (Player player, int keyId, boolean lootCrate)
Handles rolling the loot chest.
static void setLevels (Player player)
Handles setting the correct stats of the player It also makes a copy of the player his stats.
static void setupSafezone ()
Handles setting up the safezone.
static void updateInterface ()
Handles updating the player's there interface.
Static Public Attributes
static boolean canAttack = false
Checks if the players are allowed to attack within the game.
static int crateTicks
The current amount of crate ticks within the lms game.
static boolean gameInProgress
Checks if there is currently a game in progress.
static List< Player > gamePlayers = new ArrayList<>()
All the players within the LMS game.
static int gameTicks
The current amount of game ticks within the lms game.
static LMSCrate lmsCrate
The lms crate within the game.
static int startingTicks
The amount of ticks before the real game starts.
Static Private Member Functions
static void gearUpPlayers ()
Handles gearing up all the players.
static String getGameTypeName ()
static int getItemAmountForItem (int loot)
Gets the amount of the item its supposed to drop when a player dies/logouts with there upgrades.
static int getPointsForPlacement (int remaining)
The amount of points the player receives when the player leaves/dies.
static void giveChestItems (int loot, int amount, Player player)
Handles giving the chest loot to the player by inventory or ground.
static void handleFogDamage (Player player)
Handles the fog damage for a player.
static void resetLevels (Player player)
Handles resetting the copied stats to the player.
static void start ()
Handles starting the lms game.
Static Private Attributes
static Fog currentFog = new Fog(-1, -1, -1, -1)
The current fod within the LMS game.
static LMSLoadout currentGameType
The current loadout of the game.
static int lastFogCycle
static List< Position > possible_spawns
All the possible spawns of the lms game.
static LMSSafezone safeZone
The current safe zone within the game.
static List< CustomGameObject > storedObjects = new ArrayList<>()
The safezone objects within the lms game.
Detailed Description
Definition at line 38 of file LMSGame.java.
Member Function Documentation
canAttack()
boolean com.runehive.content.lms.LMSGame.canAttack (Player player, Player target) static
Checks if the player is allowed to attack the target.
Parameters
player
target
Returns
Definition at line 161 of file LMSGame.java.
{
        if (!inGameArea(player)) {
            return false;
        }
        if (!canAttack) {
            player.message("The game has not started yet.");
            return false;
        }
        if (target.lmsImmunity > System.currentTimeMillis()) {
            player.message(target.getUsername() + " has temporary immunity from being attacked!");
            return false;
        }
        if (target.getCombat().isUnderAttack() && !target.getCombat().isUnderAttackBy(player)) {
            if (!Area.inMulti(player) || !Area.inMulti(target)) {
                player.send(new SendMessage(target.getName() + " is currently in combat and can not be attacked."));
                return false;
            }
        }
        return true;
    }
References canAttack, com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.getUsername(), inGameArea(), com.runehive.game.world.position.Area.inMulti(), com.runehive.game.world.entity.mob.player.Player.lmsImmunity, com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.entity.mob.player.Player.send().
gearUpPlayers()
void com.runehive.content.lms.LMSGame.gearUpPlayers () static private
Handles gearing up all the players.
Definition at line 310 of file LMSGame.java.
{
        List<Position> copySpawns = new ArrayList<>();
        copySpawns.addAll(possible_spawns);
        gamePlayers.stream().filter(Objects::nonNull).forEach(player -> {
            //Turns of all the prayers
            player.prayer.reset();
            //Clears all unlocked items
            player.unlockedLMSItems = new ArrayList<>();
            //Toggles the fog on
            player.send(new SendLMSFog(true));
            //Sets the levels
            setLevels(player);
            //Gives the items & equipment
            giveItems(player, false);
            //Reset kills
            player.lmsKills = 0;
            //Pick a random spawn
            Collections.shuffle(copySpawns);
            int randomPick = Utility.random(copySpawns.size() - 1);
            player.move(copySpawns.get(randomPick));
            copySpawns.remove(randomPick);
        });
    }
References gamePlayers, giveItems(), possible_spawns, com.runehive.util.Utility.random(), and setLevels().
Referenced by start().
getGameTypeName()
String com.runehive.content.lms.LMSGame.getGameTypeName () static private
Definition at line 97 of file LMSGame.java.
{
        return currentGameType.getClass().getSimpleName();
    }
References currentGameType.
getItemAmountForItem()
int com.runehive.content.lms.LMSGame.getItemAmountForItem (int loot) static private
Gets the amount of the item its supposed to drop when a player dies/logouts with there upgrades.
Parameters
loot
Returns
Definition at line 682 of file LMSGame.java.
{
        switch(loot){
            case 22636:
            case 299:
            case 11212:
            case 19481:
                return 1000;
            default:
                return 1;
        }
    }
Referenced by onDeath(), and rollChest().
getKeyId()
int com.runehive.content.lms.LMSGame.getKeyId () static
The key id the player gets after a kill.
Returns
Definition at line 716 of file LMSGame.java.
{
        return gamePlayers.size() <= 4 ? 20608 : 20526;
    }
References gamePlayers.
Referenced by onKill().
getPointsForPlacement()
int com.runehive.content.lms.LMSGame.getPointsForPlacement (int remaining) static private
The amount of points the player receives when the player leaves/dies.
Parameters
remaining
Returns
Definition at line 699 of file LMSGame.java.
{
        if (remaining == 2)
            return 4;
        else if (remaining == 3 || remaining == 4)
            return 3;
        else if (remaining >= 5 && remaining <= 9)
            return 2;
        else if (remaining >= 10 && remaining <= 19)
            return 1;
        return 0;
    }
Referenced by onDeath().
giveChestItems()
void com.runehive.content.lms.LMSGame.giveChestItems (int loot, int amount, Player player) static private
Handles giving the chest loot to the player by inventory or ground.
Parameters
loot
amount
player
Definition at line 265 of file LMSGame.java.
{
        boolean space = player.inventory.getFreeSlots() > 0;
        if (space) {
            player.inventory.add(loot, amount);
        } else
            GroundItem.create(player, new Item(loot, amount));
        player.message("You have received " + amount + "x " + ItemDefinition.get(loot).getName() + ". It has been added to " + (space ? "your inventory" : "the ground"));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, and com.runehive.game.world.entity.mob.player.Player.message().
Referenced by rollChest().
giveItems()
void com.runehive.content.lms.LMSGame.giveItems (Player player, boolean clear) static
Handles giving the player correct inventory and equipment.
Parameters
player
clear
Definition at line 358 of file LMSGame.java.
{
        LMSLoadout loadout = currentGameType;
        if(clear) {
            player.equipment.clear();
            player.inventory.clear();
            player.runePouch.clear();
        }
        //Handles setting the correct spellbook
        player.spellbook = loadout.getSpellbook();
        player.interfaceManager.setSidebar(Config.MAGIC_TAB, player.spellbook.getInterfaceId());
        //Handles setting up the inventory
        player.inventory.set(loadout.getInventorySetup().getItems().clone());
        //Handles setting up the equipment
        player.equipment.clear();
        player.equipment.set(loadout.getEquipmentSetup().getItems().clone());
        player.equipment.updateAnimation();
        WeaponInterface.execute(player, player.equipment.getWeapon());
        //Handles the rune pouch
        for(int index = 0; index < loadout.getRunePouchRunes().length; index++)
            player.runePouch.runes.add(new Item(loadout.getRunePouchRunes()[index][0], loadout.getRunePouchRunes()[index][1]));
        player.inventory.refresh();
        player.equipment.refresh();
        player.equipment.updateRangedEquipment();
        player.runePouch.refresh();
        //Call the appearance update flag
        player.updateFlags.add(UpdateFlag.APPEARANCE);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.skill.impl.magic.RunePouch.clear(), com.runehive.game.world.items.containers.equipment.Equipment.clear(), com.runehive.game.world.items.containers.ItemContainer.clear(), com.runehive.game.world.items.Item.clone(), currentGameType, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.content.lms.loadouts.LMSLoadout.getEquipmentSetup(), com.runehive.content.skill.impl.magic.Spellbook.getInterfaceId(), com.runehive.content.lms.loadouts.LMSLoadout.getInventorySetup(), com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.content.lms.loadouts.LMSLoadout.getRunePouchRunes(), com.runehive.content.lms.loadouts.LMSLoadout.getSpellbook(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.Config.MAGIC_TAB, com.runehive.content.skill.impl.magic.RunePouch.refresh(), com.runehive.game.world.items.containers.equipment.Equipment.refresh(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.entity.mob.player.Player.runePouch, com.runehive.content.skill.impl.magic.RunePouch.runes, com.runehive.game.world.items.containers.ItemContainer.set(), com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar(), com.runehive.game.world.entity.mob.player.Player.spellbook, com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation(), com.runehive.game.world.entity.mob.Mob.updateFlags, and com.runehive.game.world.items.containers.equipment.Equipment.updateRangedEquipment().
Referenced by gearUpPlayers().
handleFog()
void com.runehive.content.lms.LMSGame.handleFog () static
Handles the fog closing in on the save zone.
Definition at line 539 of file LMSGame.java.
{
        lastFogCycle++;
        if (lastFogCycle == 10) {
            if (currentFog == null) {
                lastFogCycle = 0;
                return;
            }
            if (safeZone.boundsXSW == currentFog.getLowX() && safeZone.boundsYSW == currentFog.getLowY() && safeZone.boundsXNE == currentFog.getHighX() && safeZone.boundsYNE == currentFog.getHighY()) {
                lastFogCycle = 0;
                return;
            }
            currentFog.decrease();
            lastFogCycle = 0;
        }
    }
References currentFog, lastFogCycle, and safeZone.
Referenced by com.runehive.content.lms.LMSGameEvent.execute().
handleFogDamage()
void com.runehive.content.lms.LMSGame.handleFogDamage (Player player) static private
Handles the fog damage for a player.
Parameters
player
Definition at line 510 of file LMSGame.java.
{
        if(safeZone == null) return;
        if(safeZone.inSafeZone(player)) return;
        if(!Boundary.isIn(player, new Boundary(currentFog.getLowX(), currentFog.getLowY(), currentFog.getHighX(), currentFog.getHighY()))) {
            int distanceX = player.getPosition().getDistances(new Position(currentFog.getLowX(), currentFog.getLowY()));
            int distanceY = player.getPosition().getDistances(new Position(currentFog.getHighX(), currentFog.getHighY()));
            int damage = (distanceX > distanceY) ? distanceY / 10 : distanceX / 10;
            if (damage <= 0)
                damage = 1;
            if (gameTicks > 600)
                damage *= 2;
            else if (gameTicks > 900)
                damage *= 3;
            int fogStrength = (distanceX > distanceY) ? distanceY * 3 : distanceX * 3;
            player.lastFogSent = fogStrength;
            player.send(new SendLMSFog(fogStrength > 155 ? 155 : fogStrength));
            player.damage(new Hit(damage > 10 ? 10 : damage, Hitsplat.NORMAL, HitIcon.NONE, true));
        } else if (player.lastFogSent != 0)
            player.send(new SendLMSFog(0));
    }
References currentFog, com.runehive.game.world.entity.mob.Mob.damage(), gameTicks, com.runehive.game.world.position.Position.getDistances(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Boundary.isIn(), com.runehive.game.world.entity.mob.player.Player.lastFogSent, com.runehive.game.world.entity.combat.hit.HitIcon.NONE, com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL, safeZone, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by processPlayer().
inGameArea()
boolean com.runehive.content.lms.LMSGame.inGameArea (Player player) static
Handles checking if the player is in the LMS game area.
Parameters
player
Returns
Definition at line 142 of file LMSGame.java.
{
        return Boundary.isIn(player, new Boundary(3390, 5757, 3524, 5901));
    }
References com.runehive.game.world.position.Boundary.isIn().
Referenced by com.runehive.game.world.entity.skill.SkillManager.addExperience(), canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), isActivePlayer(), com.runehive.game.world.entity.mob.player.Player.onStep(), and com.runehive.content.combat.Skulling.skull().
isActivePlayer()
boolean com.runehive.content.lms.LMSGame.isActivePlayer (Player player) static
Checks if a player is a active player within the LMS game.
Parameters
player
Returns
Definition at line 151 of file LMSGame.java.
{
        return gamePlayers != null && gamePlayers.contains(player) && inGameArea(player);
    }
References gamePlayers, and inGameArea().
Referenced by com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), processPlayer(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), and com.runehive.game.world.entity.mob.player.Player.unregister().
moveToGame()
void com.runehive.content.lms.LMSGame.moveToGame (List< Player > players) static
Handles moving all the players to the game.
Parameters
players
Definition at line 280 of file LMSGame.java.
{
        currentGameType = LMSLobby.currentGameType;
        gamePlayers.addAll(players);
        gameInProgress = true;
        canAttack = false;
        start();
        //Handles setting a different loadout for next game
        LMSLoadout loadout = null;
        do {
            loadout = LMSLoadoutManager.getLmsLoadouts().get(Utility.random(LMSLoadoutManager.getLmsLoadouts().size()));
        } while(!(loadout != LMSLobby.currentGameType));
        LMSLobby.currentGameType = loadout;
    }
References canAttack, currentGameType, com.runehive.content.lms.lobby.LMSLobby.currentGameType, gameInProgress, gamePlayers, com.runehive.content.lms.loadouts.LMSLoadoutManager.getLmsLoadouts(), com.runehive.util.Utility.random(), and start().
Referenced by com.runehive.content.lms.lobby.LMSLobbyEvent.execute().
onDeath()
void com.runehive.content.lms.LMSGame.onDeath (Player player, boolean forceRemove) static
Handles when a player within the LMS game dies.
Parameters
player
forceRemove
Definition at line 634 of file LMSGame.java.
{
        player.lmsTotalDeaths++;
        if (!forceRemove) {
            Player killer = (Player) player.getCombat().getDamageCache().calculateProperKiller().orElse(null);
            int containerSize = player.unlockedLMSItems.size();
            if(containerSize != 0) {
                for (int i = 0; i < containerSize; i++) {
                    int itemId = player.unlockedLMSItems.get(i);
                    Item item = new Item(itemId, getItemAmountForItem(itemId));
                    if (killer == null)
                        GroundItem.createGlobal(player, item);
                    else
                        GroundItem.create(killer, item);
                }
            }
            player.lmsPoints += getPointsForPlacement(gamePlayers.size());
            player.message("You have been awarded: @red@"+getPointsForPlacement(gamePlayers.size())+" @bla@points for placing @red@#"+gamePlayers.size());
        }
        reset(player);
        if(gamePlayers.size() == 1) {
            gameInProgress = false;
            LMSLobbyEvent.lobbyTicks = LMSLobbyEvent.defaultLobbyTime;
            Player winner = gamePlayers.get(0);
            winner.lmsPoints+= 5;
            winner.lmsWins++;
            winner.message("Congratulations! You've won the LMS Game!");
            winner.message("You have been awarded: @red@5 points@bla@ for your win!");
            reset(winner);
            if (lmsCrate != null) {
                lmsCrate.destroy();
                lmsCrate = null;
            }
            for(CustomGameObject gameObject : storedObjects)
                gameObject.unregister();
            storedObjects.clear();
            gamePlayers.clear();
        }
    }
References com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.items.ground.GroundItem.createGlobal(), com.runehive.content.lms.lobby.LMSLobbyEvent.defaultLobbyTime, gameInProgress, gamePlayers, com.runehive.game.world.entity.mob.player.Player.getCombat(), getItemAmountForItem(), getPointsForPlacement(), lmsCrate, com.runehive.game.world.entity.mob.player.Player.lmsPoints, com.runehive.game.world.entity.mob.player.Player.lmsTotalDeaths, com.runehive.game.world.entity.mob.player.Player.lmsWins, com.runehive.content.lms.lobby.LMSLobbyEvent.lobbyTicks, com.runehive.game.world.entity.mob.player.Player.message(), reset(), storedObjects, and com.runehive.game.world.entity.mob.player.Player.unlockedLMSItems.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), and com.runehive.game.world.entity.mob.player.Player.unregister().
onKill()
void com.runehive.content.lms.LMSGame.onKill (Player killer) static
Handles the killers stuff.
Parameters
killer
Definition at line 572 of file LMSGame.java.
{
        killer.lmsImmunity = System.currentTimeMillis() + 20_000;
        killer.runEnergy = 100;
        CombatSpecial.restore(killer, 100);
        killer.skills.get(Skill.HITPOINTS).modifyLevel(level -> level + 99, 0, 99);
        killer.lmsKills++;
        killer.lmsTotalKills++;
        updateInterface();
        if (killer.lmsKills == 5)
            killer.lmsPoints += 2;
        else if (killer.lmsKills == 3)
            killer.lmsPoints += 1;
        boolean inventory =  killer.inventory.getFreeSlots() > 0;
        Item key = new Item(getKeyId(), 1);
        if (inventory)
            killer.inventory.add(key);
        else
            GroundItem.create(killer, key);
        for(int index = 0; index < killer.inventory.getItems().length; index++) {
            if(killer.inventory.get(index) == null) continue;
            Item potion = killer.inventory.get(index);
            ItemDefinition def = ItemDefinition.get(potion.getId());
            if(def == null || !def.isPotion()) continue;
            killer.inventory.remove(potion);
        }
        resupplyKiller(killer);
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.containers.ItemContainer.getItems(), getKeyId(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.lmsKills, com.runehive.game.world.entity.mob.player.Player.lmsTotalKills, com.runehive.game.world.entity.skill.Skill.modifyLevel(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.restore(), resupplyKiller(), com.runehive.game.world.entity.mob.Mob.skills, and updateInterface().
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.death().
processPlayer()
void com.runehive.content.lms.LMSGame.processPlayer (Player player) static
Handles processing the player if hes a active player within the LMS game.
Parameters
player
Definition at line 498 of file LMSGame.java.
{
        if (!isActivePlayer(player))
            return;
        handleFogDamage(player);
    }
References handleFogDamage(), and isActivePlayer().
Referenced by com.runehive.content.lms.LMSGameEvent.execute().
reset()
void com.runehive.content.lms.LMSGame.reset (Player player) static
Handles resetting the player that was in the game and either left by dying or other means.
Parameters
player
Definition at line 398 of file LMSGame.java.
{
        player.send(new SendHintArrow(0));
        player.face(Direction.SOUTH);
        player.equipment.updateAnimation();
        player.animate(Animation.RESET, true);
        player.graphic(Graphic.RESET, true);
        player.inventory.clear();
        player.equipment.clear();
        player.runePouch.clear(false);
        player.inventory.set(player.inventory_copy.getItems().clone());
        player.equipment.set(player.equipment_copy.getItems().clone());
        for(int index = 0; index < player.runePouch_copy.runes.size(); index++)
            player.runePouch.runes.add(player.runePouch_copy.runes.get(index));
        player.equipment.updateAnimation();
        WeaponInterface.execute(player, player.equipment.getWeapon());
        //Handles clearing the copies of the containers
        player.inventory_copy.clear();
        player.equipment_copy.clear();
        player.runePouch_copy.clear(false);
        player.inventory.refresh();
        player.equipment.refresh();
        player.runePouch.refresh();
        //Handles reseting the spellbook
        player.spellbook = player.spellbook_copy;
        player.interfaceManager.setSidebar(Config.MAGIC_TAB, player.spellbook.getInterfaceId());
        player.prayer.reset();
        player.send(new SendPlayerOption(PlayerOption.ATTACK, false, true));
        resetLevels(player);
        player.send(new SendLMSFog(false));
        if (gamePlayers.contains(player))
            gamePlayers.remove(player);
        updateInterface();
        player.move(new Position(LMSLobby.finish.getX() + Utility.random(1), LMSLobby.finish.getY() + Utility.random(3), 0));
        PlayerSerializer.save(player);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.player.PlayerOption.ATTACK, com.runehive.content.skill.impl.magic.RunePouch.clear(), com.runehive.game.world.items.containers.equipment.Equipment.clear(), com.runehive.game.world.items.containers.ItemContainer.clear(), com.runehive.game.world.items.Item.clone(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.equipment_copy, com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.content.lms.lobby.LMSLobby.finish, gamePlayers, com.runehive.content.skill.impl.magic.Spellbook.getInterfaceId(), com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.inventory_copy, com.runehive.Config.MAGIC_TAB, com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.util.Utility.random(), com.runehive.content.skill.impl.magic.RunePouch.refresh(), com.runehive.game.world.items.containers.equipment.Equipment.refresh(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, com.runehive.game.world.entity.mob.prayer.PrayerBook.reset(), resetLevels(), com.runehive.game.world.entity.mob.player.Player.runePouch, com.runehive.game.world.entity.mob.player.Player.runePouch_copy, com.runehive.content.skill.impl.magic.RunePouch.runes, com.runehive.game.world.entity.mob.player.persist.PlayerSerializer.save(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.items.containers.ItemContainer.set(), com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar(), com.runehive.game.world.entity.mob.Direction.SOUTH, com.runehive.game.world.entity.mob.player.Player.spellbook, com.runehive.game.world.entity.mob.player.Player.spellbook_copy, com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation(), and updateInterface().
Referenced by onDeath().
resetLevels()
void com.runehive.content.lms.LMSGame.resetLevels (Player player) static private
Handles resetting the copied stats to the player.
Parameters
player
Definition at line 448 of file LMSGame.java.
{
        for(int index = 0; index < player.skills.getSkills().length; index++) {
            Skill skill = player.skills.get(index);
            Skill copy_skill = player.skills_copy.get(index);
            skill.setLevel(copy_skill.getLevel());
            skill.setMaxLevel(copy_skill.getMaxLevel());
            skill.setExperience(skill.getExperienceForLevel(copy_skill.getLevel()));
        }
        player.skills.refresh();
    }
References com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.Skill.getLevel(), com.runehive.game.world.entity.skill.Skill.getMaxLevel(), com.runehive.game.world.entity.skill.SkillManager.getSkills(), com.runehive.game.world.entity.skill.SkillManager.refresh(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.mob.Mob.skills_copy.
Referenced by reset().
resupplyKiller()
void com.runehive.content.lms.LMSGame.resupplyKiller (Player player) static
Handles resupplying the killer.
Parameters
player
Definition at line 613 of file LMSGame.java.
{
        LMSLoadout loadout = currentGameType;
        for (int i = 6; i < loadout.getInventory().length; i++) {
            int itemId = loadout.getInventory()[i];
            if(itemId == -1) continue;
            ItemDefinition def = ItemDefinition.get(itemId);
            if(def == null || !def.isPotion()) continue;
            player.inventory.add(itemId, 1);
        }
        player.inventory.add(385, player.inventory.getFreeSlots());
        player.inventory.refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), currentGameType, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.content.lms.loadouts.LMSLoadout.getInventory(), com.runehive.game.world.entity.mob.player.Player.inventory, and com.runehive.game.world.items.containers.inventory.Inventory.refresh().
Referenced by onKill().
rollChest()
void com.runehive.content.lms.LMSGame.rollChest (Player player, int keyId, boolean lootCrate) static
Handles rolling the loot chest.
Parameters
player
keyId
lootCrate
Definition at line 192 of file LMSGame.java.
{
        if (player == null || !player.inventory.contains(keyId) && !lootCrate)
            return;
        LMSLoadout currentLoadout = currentGameType;
        boolean upgradedKey = keyId == 20608;
        int lootTable = Utility.random(1);
        int loot = -1;
        int amount = 1;
        int maximumUnlocks = currentLoadout.getOffensiveItem().length + currentLoadout.getDefensiveItem().length + currentLoadout.getOffensiveItemUpgrades().length;
        if (player.unlockedLMSItems.size() >= maximumUnlocks) return;
        if (!upgradedKey) {
            if (lootTable == 0)
                loot = currentLoadout.getOffensiveItem()[Utility.random(currentLoadout.getOffensiveItem().length - 1)];
            else if (lootTable == 1)
                loot = currentLoadout.getDefensiveItem()[Utility.random(currentLoadout.getDefensiveItem().length - 1)];
        } else
            loot = currentLoadout.getOffensiveItemUpgrades()[Utility.random(currentLoadout.getOffensiveItemUpgrades().length - 1)];
        //Handles duplicated items
        if (player.unlockedLMSItems.contains(loot)) {
            rollChest(player, keyId, lootCrate);
            return;
        }
        player.unlockedLMSItems.add(loot);
        //Add dragon arrows when its a dark bow
        if (loot == 11235) player.unlockedLMSItems.add(11212);
        //Add dragon javelins if its a balista
        if (loot == 19481) player.unlockedLMSItems.add(19484);
        //Add opal bolts e if its a arma cbow
        //if (loot == 11785) player.unlockedLMSItems.add(8723);
        if (!lootCrate) player.inventory.remove(keyId);
        //Set the amount of certain items
        if (loot == 22636 || loot == 299) amount = 1000;
        giveChestItems(loot, amount, player);
        if (lootCrate) {
            player.animate(832);
            World.sendObjectAnimation(86, lmsCrate.getLootCrate());
            lmsCrate.destroy();
            lmsCrate = null;
        }
        //Checks if the loot was javelins or dragon arrows
        int secondary = -1;
        if (loot == 11235) secondary = 11212;
        else if(loot == 19481) secondary = 19484;
        //else if(loot == 11785) secondary = 8723;
        if(secondary != -1)
            giveChestItems(secondary, getItemAmountForItem(secondary), player);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.items.containers.ItemContainer.contains(), currentGameType, com.runehive.content.lms.loadouts.LMSLoadout.getDefensiveItem(), getItemAmountForItem(), com.runehive.content.lms.loadouts.LMSLoadout.getOffensiveItem(), com.runehive.content.lms.loadouts.LMSLoadout.getOffensiveItemUpgrades(), giveChestItems(), com.runehive.game.world.entity.mob.player.Player.inventory, lmsCrate, com.runehive.util.Utility.random(), com.runehive.game.world.items.containers.ItemContainer.remove(), rollChest(), com.runehive.game.world.World.sendObjectAnimation(), and com.runehive.game.world.entity.mob.player.Player.unlockedLMSItems.
Referenced by rollChest().
setLevels()
void com.runehive.content.lms.LMSGame.setLevels (Player player) static
Handles setting the correct stats of the player It also makes a copy of the player his stats.
Parameters
player
Definition at line 340 of file LMSGame.java.
{
        for(int index = 0; index < currentGameType.getSkills().length; index++) {
            int level = currentGameType.getSkills()[index];
            Skill skill = player.skills.get(index);
            skill.setLevel(level);
            skill.setMaxLevel(level);
            skill.setExperience(skill.getExperienceForLevel(level));
        }
        player.skills.refresh();
    }
References currentGameType, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.SkillManager.refresh(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by gearUpPlayers().
setupSafezone()
void com.runehive.content.lms.LMSGame.setupSafezone () static
Handles setting up the safezone.
Definition at line 464 of file LMSGame.java.
{
        safeZone = LMSSafezone.values()[Utility.random(LMSSafezone.values().length - 1)];
        gamePlayers.stream().forEach(player -> player.message("@red@Fog approaching. Get to the safezone at "+ StringUtils.capitalize(safeZone.name().toLowerCase().replaceAll("_", " ")+"!")));
        for (int i = safeZone.boundsYSW; i < safeZone.boundsYSW + 10; i++) {
            CustomGameObject gameObject = new CustomGameObject(34905, new Position(safeZone.boundsXSW, i));
            gameObject.register();
            storedObjects.add(gameObject);
        }
        for (int i = safeZone.boundsXSW; i < safeZone.boundsXSW + 10; i++) {
            CustomGameObject gameObject = new CustomGameObject(34905, new Position(i, safeZone.boundsYSW));
            gameObject.register();
            storedObjects.add(gameObject);
        }
        for (int i = safeZone.boundsXNE - 10; i < safeZone.boundsXNE; i++) {
            CustomGameObject gameObject = new CustomGameObject(34905, new Position(i, safeZone.boundsYNE));
            gameObject.register();
            storedObjects.add(gameObject);
        }
        for (int i = safeZone.boundsYNE - 10; i <= safeZone.boundsYNE; i++) {
            CustomGameObject gameObject = new CustomGameObject(34905, new Position(safeZone.boundsXNE, i));
            gameObject.register();
            storedObjects.add(gameObject);
        }
        currentFog = new Fog(safeZone.boundsXSW - 100, safeZone.boundsYSW - 100, safeZone.boundsXNE + 100, safeZone.boundsYNE + 100);
        updateInterface();
        gamePlayers.stream().forEach(player -> player.send(new SendHintArrow(new Position(safeZone.boundsXSW + 5, safeZone.boundsYSW + 5, 0), 7)));
    }
References com.runehive.util.StringUtils.capitalize(), currentFog, gamePlayers, com.runehive.util.Utility.random(), com.runehive.game.world.object.CustomGameObject.register(), safeZone, storedObjects, and updateInterface().
Referenced by com.runehive.content.lms.LMSGameEvent.execute().
start()
void com.runehive.content.lms.LMSGame.start () static private
Handles starting the lms game.
Definition at line 298 of file LMSGame.java.
{
        gearUpPlayers();
        startingTicks = 10;
        safeZone = null;
        gameTicks = 0;
        crateTicks = 0;
        currentFog.reset();
    }
References crateTicks, currentFog, gameTicks, gearUpPlayers(), safeZone, and startingTicks.
Referenced by moveToGame().
updateInterface()
void com.runehive.content.lms.LMSGame.updateInterface () static
Handles updating the player's there interface.
Definition at line 560 of file LMSGame.java.
{
        gamePlayers.stream().filter(Objects::nonNull).forEach(player -> {
            player.send(new SendString("Survivors: " + gamePlayers.size() + "/" + LMSLobby.maxPlayers, 44664));
            player.send(new SendString("Kills: " + player.lmsKills, 44665));
            player.send(new SendString("Fog: " + (currentFog.isSafe() ? "Safe" : "Approaching"), 44666));
        });
    }
References currentFog, gamePlayers, and com.runehive.content.lms.lobby.LMSLobby.maxPlayers.
Referenced by com.runehive.content.lms.LMSGameEvent.execute(), onKill(), reset(), and setupSafezone().
Member Data Documentation
canAttack
boolean com.runehive.content.lms.LMSGame.canAttack = false static
Checks if the players are allowed to attack within the game.
Definition at line 53 of file LMSGame.java.
Referenced by canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.content.lms.LMSGameEvent.execute(), and moveToGame().
crateTicks
int com.runehive.content.lms.LMSGame.crateTicks static
The current amount of crate ticks within the lms game.
Definition at line 75 of file LMSGame.java.
Referenced by com.runehive.content.lms.LMSGameEvent.execute(), and start().
currentFog
Fog com.runehive.content.lms.LMSGame.currentFog = new Fog(-1, -1, -1, -1) static private
The current fod within the LMS game.
Definition at line 58 of file LMSGame.java.
Referenced by handleFog(), handleFogDamage(), setupSafezone(), start(), and updateInterface().
currentGameType
LMSLoadout com.runehive.content.lms.LMSGame.currentGameType static private
The current loadout of the game.
Definition at line 95 of file LMSGame.java.
Referenced by getGameTypeName(), giveItems(), moveToGame(), resupplyKiller(), rollChest(), and setLevels().
gameInProgress
boolean com.runehive.content.lms.LMSGame.gameInProgress static
Checks if there is currently a game in progress.
Definition at line 48 of file LMSGame.java.
Referenced by com.runehive.content.lms.LMSGameEvent.execute(), com.runehive.content.lms.lobby.LMSLobbyEvent.execute(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), moveToGame(), and onDeath().
gamePlayers
List<Player> com.runehive.content.lms.LMSGame.gamePlayers = new ArrayList<>() static
All the players within the LMS game.
Definition at line 43 of file LMSGame.java.
Referenced by com.runehive.content.lms.LMSGameEvent.execute(), gearUpPlayers(), getKeyId(), isActivePlayer(), moveToGame(), onDeath(), reset(), setupSafezone(), com.runehive.content.lms.crate.LMSCrate.spawn(), and updateInterface().
gameTicks
int com.runehive.content.lms.LMSGame.gameTicks static
The current amount of game ticks within the lms game.
Definition at line 65 of file LMSGame.java.
Referenced by com.runehive.content.lms.LMSGameEvent.execute(), handleFogDamage(), and start().
lastFogCycle
int com.runehive.content.lms.LMSGame.lastFogCycle static private
Definition at line 60 of file LMSGame.java.
Referenced by handleFog().
lmsCrate
LMSCrate com.runehive.content.lms.LMSGame.lmsCrate static
The lms crate within the game.
Definition at line 80 of file LMSGame.java.
Referenced by com.runehive.content.lms.LMSGameEvent.execute(), onDeath(), and rollChest().
possible_spawns
List<Position> com.runehive.content.lms.LMSGame.possible_spawns static private
All the possible spawns of the lms game.
Definition at line 104 of file LMSGame.java.
Referenced by gearUpPlayers().
safeZone
LMSSafezone com.runehive.content.lms.LMSGame.safeZone static private
The current safe zone within the game.
Definition at line 85 of file LMSGame.java.
Referenced by handleFog(), handleFogDamage(), setupSafezone(), and start().
startingTicks
int com.runehive.content.lms.LMSGame.startingTicks static
The amount of ticks before the real game starts.
Definition at line 70 of file LMSGame.java.
Referenced by com.runehive.content.lms.LMSGameEvent.execute(), and start().
storedObjects
List<CustomGameObject> com.runehive.content.lms.LMSGame.storedObjects = new ArrayList<>() static private
The safezone objects within the lms game.
Definition at line 90 of file LMSGame.java.
Referenced by onDeath(), and setupSafezone().
The documentation for this class was generated from the following file:
java/com/runehive/content/lms/LMSGame.java