RuneHive-Game: com.runehive.game.world.entity.mob.player.appearance.Appearance Class Reference
com.runehive.game.world.entity.mob.player.appearance.Appearance Class Reference
Represents a Players appearance.
Public Member Functions
Appearance (final Gender gender, final int head, final int beard, final int torso, final int arms, final int hands, final int legs, final int feet, int hairColor, int torsoColor, int legsColor, int feetColor, int skinColor)
int getArms ()
int getBeard ()
int getFeet ()
int getFeetColor ()
Gender getGender ()
int getHairColor ()
int getHands ()
int getHead ()
int getLegs ()
int getLegsColor ()
int getSkinColor ()
int getTorso ()
int getTorsoColor ()
void setArms (final int arms)
void setFeet (final int feet)
void setFeetColor (int feetColor)
void setGender (final Gender gender)
void setHairColor (int hairColor)
void setHands (final int hands)
void setHead (final int head)
void setJaw (final int beard)
void setLegs (final int legs)
void setLegsColor (int legsColor)
void setSkinColor (int skinColor)
void setTorso (final int torso)
void setTorsoColor (int torsoColor)
String toString ()
Static Public Attributes
static final int ARMS = 3
static final int FEET = 6
static final int HANDS = 4
static final int HEAD = 0
static final int JAW = 1
static final int LEGS = 5
static final int TORSO = 2
Private Attributes
int arms
int beard
int feet
int feetColor
Gender gender
int hairColor
int hands
int head
int legs
int legsColor
int skinColor
int torso
int torsoColor
Detailed Description
Represents a Players appearance.
Author
SeVen
Definition at line 10 of file Appearance.java.
Constructor & Destructor Documentation
Appearance()
com.runehive.game.world.entity.mob.player.appearance.Appearance.Appearance (final Gender gender, final int head, final int beard, final int torso, final int arms, final int hands, final int legs, final int feet, int hairColor, int torsoColor, int legsColor, int feetColor, int skinColor)
Definition at line 52 of file Appearance.java.
{
        this.gender = gender;
        this.head = head;
        this.beard = beard;
        this.torso = torso;
        this.arms = arms;
        this.hands = hands;
        this.legs = legs;
        this.feet = feet;
        this.hairColor = hairColor;
        this.torsoColor = torsoColor;
        this.legsColor = legsColor;
        this.feetColor = feetColor;
        this.skinColor = skinColor;
    }
References arms, beard, feet, feetColor, gender, hairColor, hands, head, legs, legsColor, skinColor, torso, and torsoColor.
Member Function Documentation
getArms()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getArms ()
Returns
the arms
Definition at line 71 of file Appearance.java.
{
        return arms;
    }
References arms.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), and toString().
getBeard()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getBeard ()
Returns
The beard
Definition at line 106 of file Appearance.java.
{
        return beard;
    }
References beard.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), and toString().
getFeet()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getFeet ()
Returns
the feet
Definition at line 78 of file Appearance.java.
{
        return feet;
    }
References feet.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), and toString().
getFeetColor()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getFeetColor ()
Returns
the feetColor
Definition at line 236 of file Appearance.java.
{
        return feetColor;
    }
References feetColor.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.net.packet.in.AppearanceChangePacketListener.isValid().
getGender()
Gender com.runehive.game.world.entity.mob.player.appearance.Appearance.getGender ()
Returns
the gender
Definition at line 85 of file Appearance.java.
{
        return gender;
    }
References gender.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), and toString().
getHairColor()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getHairColor ()
Returns
the hairColor
Definition at line 191 of file Appearance.java.
{
        return hairColor;
    }
References hairColor.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.net.packet.in.AppearanceChangePacketListener.isValid().
getHands()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getHands ()
Returns
the hands
Definition at line 92 of file Appearance.java.
{
        return hands;
    }
References hands.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), and toString().
getHead()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getHead ()
Returns
the head
Definition at line 99 of file Appearance.java.
{
        return head;
    }
References head.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), and toString().
getLegs()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getLegs ()
Returns
the legs
Definition at line 113 of file Appearance.java.
{
        return legs;
    }
References legs.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), and toString().
getLegsColor()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getLegsColor ()
Returns
the legsColor
Definition at line 221 of file Appearance.java.
{
        return legsColor;
    }
References legsColor.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.net.packet.in.AppearanceChangePacketListener.isValid().
getSkinColor()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getSkinColor ()
Returns
the skinColor
Definition at line 251 of file Appearance.java.
{
        return skinColor;
    }
References skinColor.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.net.packet.in.AppearanceChangePacketListener.isValid().
getTorso()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getTorso ()
Returns
the torso
Definition at line 120 of file Appearance.java.
{
        return torso;
    }
References torso.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), and toString().
getTorsoColor()
int com.runehive.game.world.entity.mob.player.appearance.Appearance.getTorsoColor ()
Returns
the torsoColor
Definition at line 206 of file Appearance.java.
{
        return torsoColor;
    }
References torsoColor.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.net.packet.in.AppearanceChangePacketListener.isValid().
setArms()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setArms (final int arms)
Parameters
arms the arms to set
Definition at line 128 of file Appearance.java.
{
        this.arms = arms;
    }
References arms.
setFeet()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setFeet (final int feet)
Parameters
feet the feet to set
Definition at line 136 of file Appearance.java.
{
        this.feet = feet;
    }
References feet.
setFeetColor()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setFeetColor (int feetColor)
Parameters
feetColor the feetColor to set
Definition at line 244 of file Appearance.java.
{
        this.feetColor = feetColor;
    }
References feetColor.
setGender()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setGender (final Gender gender)
Parameters
gender the gender to set
Definition at line 144 of file Appearance.java.
{
        this.gender = gender;
    }
References gender.
setHairColor()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setHairColor (int hairColor)
Parameters
hairColor the hairColor to set
Definition at line 199 of file Appearance.java.
{
        this.hairColor = hairColor;
    }
References hairColor.
setHands()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setHands (final int hands)
Parameters
hands the hands to set
Definition at line 152 of file Appearance.java.
{
        this.hands = hands;
    }
References hands.
setHead()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setHead (final int head)
Parameters
head the head to set
Definition at line 160 of file Appearance.java.
{
        this.head = head;
    }
References head.
setJaw()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setJaw (final int beard)
Parameters
beard the jaw to set
Definition at line 168 of file Appearance.java.
{
        this.beard = beard;
    }
References beard.
setLegs()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setLegs (final int legs)
Parameters
legs the legs to set
Definition at line 176 of file Appearance.java.
{
        this.legs = legs;
    }
References legs.
setLegsColor()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setLegsColor (int legsColor)
Parameters
legsColor the legsColor to set
Definition at line 229 of file Appearance.java.
{
        this.legsColor = legsColor;
    }
References legsColor.
setSkinColor()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setSkinColor (int skinColor)
Parameters
skinColor the skinColor to set
Definition at line 259 of file Appearance.java.
{
        this.skinColor = skinColor;
    }
References skinColor.
setTorso()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setTorso (final int torso)
Parameters
torso the torso to set
Definition at line 184 of file Appearance.java.
{
        this.torso = torso;
    }
References torso.
setTorsoColor()
void com.runehive.game.world.entity.mob.player.appearance.Appearance.setTorsoColor (int torsoColor)
Parameters
torsoColor the torsoColor to set
Definition at line 214 of file Appearance.java.
{
        this.torsoColor = torsoColor;
    }
References torsoColor.
toString()
String com.runehive.game.world.entity.mob.player.appearance.Appearance.toString ()
Definition at line 264 of file Appearance.java.
{
        return String.format("[gen= %s] [head= %d] [jaw= %d] [tor= %d] [arm= %d] [han= %d] [leg= %d] [feet= %d]", getGender().name().toLowerCase(), getHead(), getBeard(), getTorso(), getArms(), getHands(), getLegs(), getFeet());
    }
References getArms(), getBeard(), getFeet(), getGender(), getHands(), getHead(), getLegs(), and getTorso().
Member Data Documentation
ARMS
final int com.runehive.game.world.entity.mob.player.appearance.Appearance.ARMS = 3 static
Definition at line 18 of file Appearance.java.
arms
int com.runehive.game.world.entity.mob.player.appearance.Appearance.arms private
Definition at line 34 of file Appearance.java.
Referenced by Appearance(), getArms(), and setArms().
beard
int com.runehive.game.world.entity.mob.player.appearance.Appearance.beard private
Definition at line 30 of file Appearance.java.
Referenced by Appearance(), getBeard(), and setJaw().
FEET
final int com.runehive.game.world.entity.mob.player.appearance.Appearance.FEET = 6 static
Definition at line 24 of file Appearance.java.
feet
int com.runehive.game.world.entity.mob.player.appearance.Appearance.feet private
Definition at line 40 of file Appearance.java.
Referenced by Appearance(), getFeet(), and setFeet().
feetColor
int com.runehive.game.world.entity.mob.player.appearance.Appearance.feetColor private
Definition at line 48 of file Appearance.java.
Referenced by Appearance(), getFeetColor(), and setFeetColor().
gender
Gender com.runehive.game.world.entity.mob.player.appearance.Appearance.gender private
Definition at line 26 of file Appearance.java.
Referenced by Appearance(), getGender(), and setGender().
hairColor
int com.runehive.game.world.entity.mob.player.appearance.Appearance.hairColor private
Definition at line 42 of file Appearance.java.
Referenced by Appearance(), getHairColor(), and setHairColor().
HANDS
final int com.runehive.game.world.entity.mob.player.appearance.Appearance.HANDS = 4 static
Definition at line 20 of file Appearance.java.
hands
int com.runehive.game.world.entity.mob.player.appearance.Appearance.hands private
Definition at line 36 of file Appearance.java.
Referenced by Appearance(), getHands(), and setHands().
HEAD
final int com.runehive.game.world.entity.mob.player.appearance.Appearance.HEAD = 0 static
Definition at line 12 of file Appearance.java.
head
int com.runehive.game.world.entity.mob.player.appearance.Appearance.head private
Definition at line 28 of file Appearance.java.
Referenced by Appearance(), getHead(), and setHead().
JAW
final int com.runehive.game.world.entity.mob.player.appearance.Appearance.JAW = 1 static
Definition at line 14 of file Appearance.java.
LEGS
final int com.runehive.game.world.entity.mob.player.appearance.Appearance.LEGS = 5 static
Definition at line 22 of file Appearance.java.
legs
int com.runehive.game.world.entity.mob.player.appearance.Appearance.legs private
Definition at line 38 of file Appearance.java.
Referenced by Appearance(), getLegs(), and setLegs().
legsColor
int com.runehive.game.world.entity.mob.player.appearance.Appearance.legsColor private
Definition at line 46 of file Appearance.java.
Referenced by Appearance(), getLegsColor(), and setLegsColor().
skinColor
int com.runehive.game.world.entity.mob.player.appearance.Appearance.skinColor private
Definition at line 50 of file Appearance.java.
Referenced by Appearance(), getSkinColor(), and setSkinColor().
TORSO
final int com.runehive.game.world.entity.mob.player.appearance.Appearance.TORSO = 2 static
Definition at line 16 of file Appearance.java.
torso
int com.runehive.game.world.entity.mob.player.appearance.Appearance.torso private
Definition at line 32 of file Appearance.java.
Referenced by Appearance(), getTorso(), and setTorso().
torsoColor
int com.runehive.game.world.entity.mob.player.appearance.Appearance.torsoColor private
Definition at line 44 of file Appearance.java.
Referenced by Appearance(), getTorsoColor(), and setTorsoColor().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/appearance/Appearance.java