RuneHive-Game: com.runehive.game.world.entity.combat.CombatDamage.DamageCounter Class Reference
com.runehive.game.world.entity.combat.CombatDamage.DamageCounter Class Reference
A counter that will track the amount of damage dealt and whether that damaged has timed out or not.
Public Member Functions
DamageCounter (int amount)
Creates a new DamageCounter.
int getAmount ()
Gets the amount of damage within this counter.
void incrementAmount (int amount)
Increments the amount of damage within this counter.
boolean isTimeout ()
Determines if this counter has timed out or not.
Private Attributes
int amount
The amount of damage within this counter.
final Stopwatch stopwatch = Stopwatch.start()
The stopwatch that will determine when a timeout occurs.
Detailed Description
A counter that will track the amount of damage dealt and whether that damaged has timed out or not.
Author
lare96 http://github.com/lare96
Definition at line 136 of file CombatDamage.java.
Constructor & Destructor Documentation
DamageCounter()
com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.DamageCounter (int amount)
Creates a new DamageCounter.
Parameters
amount the amount of damage within this counter.
Definition at line 153 of file CombatDamage.java.
{
            this.amount = amount;
        }
References amount.
Member Function Documentation
getAmount()
int com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.getAmount ()
Gets the amount of damage within this counter.
Returns
the amount of damage.
Definition at line 162 of file CombatDamage.java.
{
            return amount;
        }
References amount.
Referenced by com.runehive.game.world.entity.combat.CombatDamage.calculateProperKiller(), com.runehive.game.world.entity.combat.CombatDamage.getNpcKiller(), and com.runehive.game.world.entity.combat.CombatDamage.getPlayerKiller().
incrementAmount()
void com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.incrementAmount (int amount)
Increments the amount of damage within this counter.
Parameters
amount the amount to increment by.
Definition at line 171 of file CombatDamage.java.
{
            if (this.isTimeout()) {
                this.amount = 0;
            }
            this.amount += amount;
            this.stopwatch.reset();
        }
References amount, isTimeout(), and com.runehive.util.Stopwatch.reset().
Referenced by com.runehive.game.world.entity.combat.CombatDamage.add().
isTimeout()
boolean com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.isTimeout ()
Determines if this counter has timed out or not.
Returns
true if this counter has timed out, false otherwise.
Definition at line 185 of file CombatDamage.java.
{
            return stopwatch.elapsed(CombatConstants.DAMAGE_CACHE_TIMEOUT, TimeUnit.SECONDS);
        }
References com.runehive.game.world.entity.combat.CombatConstants.DAMAGE_CACHE_TIMEOUT, and stopwatch.
Referenced by com.runehive.game.world.entity.combat.CombatDamage.calculateProperKiller(), com.runehive.game.world.entity.combat.CombatDamage.getNpcKiller(), com.runehive.game.world.entity.combat.CombatDamage.getPlayerKiller(), and incrementAmount().
Member Data Documentation
amount
int com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.amount private
The amount of damage within this counter.
Definition at line 141 of file CombatDamage.java.
Referenced by DamageCounter(), getAmount(), and incrementAmount().
stopwatch
final Stopwatch com.runehive.game.world.entity.combat.CombatDamage.DamageCounter.stopwatch = Stopwatch.start() private
The stopwatch that will determine when a timeout occurs.
Definition at line 146 of file CombatDamage.java.
Referenced by isTimeout().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/CombatDamage.java