RuneHive-Game: com.runehive.game.world.entity.mob.player.IPBannedPlayers Class Reference
com.runehive.game.world.entity.mob.player.IPBannedPlayers Class Reference
Static Public Member Functions
static void ipBan (String host)
static void load ()
Static Public Attributes
static final List< String > ipBans = new ArrayList<>()
Static Private Member Functions
static void writeIpBans ()
Static Private Attributes
static final String IP_BAN_LIST_PATH = "./data/ip-bans.txt"
Detailed Description
Definition at line 13 of file IPBannedPlayers.java.
Member Function Documentation
ipBan()
void com.runehive.game.world.entity.mob.player.IPBannedPlayers.ipBan (String host) static
Definition at line 30 of file IPBannedPlayers.java.
{
        host = host.toLowerCase();
        if (ipBans.contains(host)) {
            return;
        }
        ipBans.add(host);
        writeIpBans();
    }
References ipBans, and writeIpBans().
load()
void com.runehive.game.world.entity.mob.player.IPBannedPlayers.load () static
Definition at line 19 of file IPBannedPlayers.java.
{
        if (!ipBans.isEmpty()) {
            ipBans.clear();
        }
        try {
            ipBans.addAll(Files.readAllLines(Paths.get(IP_BAN_LIST_PATH)));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
References IP_BAN_LIST_PATH, and ipBans.
Referenced by com.runehive.RuneHive.start().
writeIpBans()
void com.runehive.game.world.entity.mob.player.IPBannedPlayers.writeIpBans () static private
Definition at line 39 of file IPBannedPlayers.java.
{
        World.schedule(new Task(1) {
            @Override
            public void execute() {
                try {
                    Files.write(Paths.get(IP_BAN_LIST_PATH), ipBans, Charset.defaultCharset());
                    cancel();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }
References IP_BAN_LIST_PATH, ipBans, and com.runehive.game.world.World.schedule().
Referenced by ipBan().
Member Data Documentation
IP_BAN_LIST_PATH
final String com.runehive.game.world.entity.mob.player.IPBannedPlayers.IP_BAN_LIST_PATH = "./data/ip-bans.txt" static private
Definition at line 15 of file IPBannedPlayers.java.
Referenced by load(), and writeIpBans().
ipBans
final List<String> com.runehive.game.world.entity.mob.player.IPBannedPlayers.ipBans = new ArrayList<>() static
Definition at line 17 of file IPBannedPlayers.java.
Referenced by com.runehive.net.ChannelFilter.channelRegistered(), ipBan(), load(), and writeIpBans().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/IPBannedPlayers.java