RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy Class Reference
com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy Class Reference
Public Member Functions
void attack (Player attacker, Mob defender, Hit hit)
boolean canAttack (Player attacker, Mob defender)
Animation getAttackAnimation (Player attacker, Mob defender)
int getAttackDelay (Player attacker, Mob defender, FightType fightType)
int getAttackDistance (Player attacker, FightType fightType)
CombatType getCombatType ()
CombatHit[] getHits (Player attacker, Mob defender)
void hit (Player attacker, Mob defender, Hit hit)
void start (Player attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static PlayerMeleeStrategy get ()
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions
PlayerMeleeStrategy ()
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Private Attributes
static final PlayerMeleeStrategy INSTANCE = new PlayerMeleeStrategy()
Additional Inherited Members
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Definition at line 23 of file PlayerMeleeStrategy.java.
Constructor & Destructor Documentation
PlayerMeleeStrategy()
com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.PlayerMeleeStrategy () protected
Definition at line 26 of file PlayerMeleeStrategy.java.
{
    }
Referenced by get().
Member Function Documentation
attack()
void com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.attack (Player attacker, Mob defender, Hit hit)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalTentacleWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer, com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword, and com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.
Definition at line 48 of file PlayerMeleeStrategy.java.
{
        Item weapon = attacker.equipment.get(Equipment.WEAPON_SLOT);
        if(weapon != null) {
            switch(weapon.getId()) {
                case ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID -> {
                    attacker.viggorasChainmaceCharges--;
                }
            }
        }
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), hit(), com.runehive.content.itemaction.impl.ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID, com.runehive.game.world.entity.mob.player.Player.viggorasChainmaceCharges, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
canAttack()
boolean com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack (Player attacker, Mob defender)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.
Definition at line 30 of file PlayerMeleeStrategy.java.
{
        if (Activity.search(attacker, DuelArenaActivity.class).isPresent()) {
            DuelArenaActivity activity = Activity.search(attacker, DuelArenaActivity.class).get();
            return !activity.rules.contains(DuelRule.NO_MELEE);
        }
        Item weapon = attacker.equipment.get(Equipment.WEAPON_SLOT);
        if(weapon != null && weapon.getId() == ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID && attacker.viggorasChainmaceCharges < 1) {
            attacker.send(new SendMessage("Your Viggora's chainmace is out of charges!"));
            attacker.getCombat().reset();
            return false;
        }
        return true;
    }
References com.runehive.content.activity.impl.duelarena.DuelRules.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.content.activity.impl.duelarena.DuelRule.NO_MELEE, com.runehive.content.activity.impl.duelarena.DuelArenaActivity.rules, com.runehive.content.activity.Activity.search(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.itemaction.impl.ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID, com.runehive.game.world.entity.mob.player.Player.viggorasChainmaceCharges, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
get()
PlayerMeleeStrategy com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.get () static
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalBludgen, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalTentacleWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.DefaultMelee, com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark, com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonLongsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonMace, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer, com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul, com.runehive.game.world.entity.combat.strategy.player.special.melee.OsmumFang, com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword, com.runehive.game.world.entity.combat.strategy.player.special.melee.VestaLongsword, and com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.
Definition at line 140 of file PlayerMeleeStrategy.java.
{
        return INSTANCE;
    }
References INSTANCE, and PlayerMeleeStrategy().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.getStrategy().
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation (Player attacker, Mob defender)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalBludgen, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalTentacleWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonLongsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonMace, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer, com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul, com.runehive.game.world.entity.combat.strategy.player.special.melee.OsmumFang, com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword, com.runehive.game.world.entity.combat.strategy.player.special.melee.VestaLongsword, and com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.
Definition at line 96 of file PlayerMeleeStrategy.java.
{
        int animation = attacker.getCombat().getFightType().getAnimation();
        if (attacker.equipment.hasShield()) {
            Item weapon = attacker.equipment.getShield();
            FightType fightType = attacker.getCombat().getFightType();
            animation = weapon.getAttackAnimation(fightType).orElse(animation);
        }
        if (attacker.equipment.hasWeapon()) {
            Item weapon = attacker.equipment.getWeapon();
            FightType fightType = attacker.getCombat().getFightType();
            animation = weapon.getAttackAnimation(fightType).orElse(animation);
        }
        if (attacker.overrides.hasOverride(Equipment.WEAPON_SLOT)) {
            final var item = attacker.overrides.get(Equipment.WEAPON_SLOT);
            animation = attacker.overrides.getFightType(item).getAnimation();
        }
        return new Animation(animation, UpdatePriority.HIGH);
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.content.overrides.Overrides.get(), com.runehive.game.world.entity.combat.attack.FightType.getAnimation(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.content.overrides.Overrides.getFightType(), com.runehive.game.world.items.containers.equipment.Equipment.getShield(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.content.overrides.Overrides.hasOverride(), com.runehive.game.world.items.containers.equipment.Equipment.hasShield(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), com.runehive.game.UpdatePriority.HIGH, com.runehive.game.world.entity.mob.player.Player.overrides, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by start(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.start().
getAttackDelay()
int com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackDelay (Player attacker, Mob defender, FightType fightType)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonLongsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonMace, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer, com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul, com.runehive.game.world.entity.combat.strategy.player.special.melee.OsmumFang, and com.runehive.game.world.entity.combat.strategy.player.special.melee.VestaLongsword.
Definition at line 86 of file PlayerMeleeStrategy.java.
{
        return attacker.getCombat().getFightType().getDelay();
    }
References com.runehive.game.world.entity.mob.player.Player.getCombat().
getAttackDistance()
int com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackDistance (Player attacker, FightType fightType)
Definition at line 91 of file PlayerMeleeStrategy.java.
{
        return fightType.getDistance();
    }
References com.runehive.game.world.entity.combat.attack.FightType.getDistance().
getCombatType()
CombatType com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getCombatType ()
Reimplemented from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
Definition at line 136 of file PlayerMeleeStrategy.java.
{
        return CombatType.MELEE;
    }
References com.runehive.game.world.entity.combat.CombatType.MELEE.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.fourthOption(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.thirdOption().
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getHits (Player attacker, Mob defender)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalTentacleWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear, com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul, com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword, and com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.
Definition at line 81 of file PlayerMeleeStrategy.java.
{
        return new CombatHit[]{nextMeleeHit(attacker, defender)};
    }
References com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit().
hit()
void com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.hit (Player attacker, Mob defender, Hit hit)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear, and com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominGodsword.
Definition at line 72 of file PlayerMeleeStrategy.java.
{
        if (hit.getDamage() < 1) {
            return;
        }
        CombatPoisonEffect.getPoisonType(attacker.equipment.getWeapon()).ifPresent(defender::poison);
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), and hit().
Referenced by attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalDagger.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalTentacleWhip.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalWhip.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.SaradominSword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.attack(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.fourthOption(), hit(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalBludgen.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonMace.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.OsmumFang.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.VestaLongsword.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonMace.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.onKill(), com.runehive.game.world.entity.combat.strategy.player.special.melee.OsmumFang.onKill(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.VestaLongsword.onKill().
start()
void com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.start (Player attacker, Mob defender, Hit[] hits)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalTentacleWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.AbyssalWhip, com.runehive.game.world.entity.combat.strategy.player.special.melee.AncientGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.ArmadylGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.BandosGodsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark, com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonDagger, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonLongsword, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonMace, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar, com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonWarhammer, com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul, com.runehive.game.world.entity.combat.strategy.player.special.melee.OsmumFang, and com.runehive.game.world.entity.combat.strategy.player.special.melee.VestaLongsword.
Definition at line 60 of file PlayerMeleeStrategy.java.
{
        if (attacker.isSpecialActivated()) {
            attacker.getCombatSpecial().drain(attacker);
        }
        attacker.animate(getAttackAnimation(attacker, defender), true);
        if (!defender.isPlayer() || !PlayerRight.isIronman(attacker))
            addCombatExperience(attacker, hits);
    }
References com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.addCombatExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.drain(), getAttackAnimation(), com.runehive.game.world.entity.mob.player.Player.getCombatSpecial(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.game.world.entity.mob.Mob.isPlayer(), and com.runehive.game.world.entity.mob.player.Player.isSpecialActivated().
Member Data Documentation
INSTANCE
final PlayerMeleeStrategy com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.INSTANCE = new PlayerMeleeStrategy() static private
Definition at line 24 of file PlayerMeleeStrategy.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/PlayerMeleeStrategy.java