RuneHive-Game: com.runehive.game.event.bus.PlayerDataBus Class Reference
com.runehive.game.event.bus.PlayerDataBus Class Reference
Public Member Functions
boolean publish (Player player, Event event)
void subscribe (PlayerEventListener listener)
void unsubscribe (PlayerEventListener listener)
Static Public Member Functions
static PlayerDataBus getInstance ()
Private Member Functions
PlayerDataBus ()
Static Private Attributes
static final Set< PlayerEventListener > chain = new HashSet<>()
static final PlayerDataBus INSTANCE = new PlayerDataBus()
Detailed Description
Definition at line 10 of file PlayerDataBus.java.
Constructor & Destructor Documentation
PlayerDataBus()
com.runehive.game.event.bus.PlayerDataBus.PlayerDataBus () private
Definition at line 14 of file PlayerDataBus.java.
{
    }
Referenced by getInstance().
Member Function Documentation
getInstance()
PlayerDataBus com.runehive.game.event.bus.PlayerDataBus.getInstance () static
Definition at line 18 of file PlayerDataBus.java.
{
        return INSTANCE;
    }
References INSTANCE, and PlayerDataBus().
publish()
boolean com.runehive.game.event.bus.PlayerDataBus.publish (Player player, Event event)
Definition at line 32 of file PlayerDataBus.java.
{
        for (PlayerEventListener listener : chain) {
            if (listener.accept(player, event)) {
                return true;
            }
        }
        return false;
    }
References chain.
Referenced by com.runehive.net.packet.in.ItemContainerActionPacketListener.allButOne(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fifthAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.firstAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fourthAction(), com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnItem(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handleSecondOption(), com.runehive.net.packet.in.ItemOptionPacketListener.handleThirdOption(), com.runehive.net.packet.in.ItemContainerActionPacketListener.modifiableXAction(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.game.world.items.ground.GroundItem.pickup(), com.runehive.net.packet.in.ItemContainerActionPacketListener.secondAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.sixthAction(), and com.runehive.net.packet.in.ItemContainerActionPacketListener.thirdAction().
subscribe()
void com.runehive.game.event.bus.PlayerDataBus.subscribe (PlayerEventListener listener)
Definition at line 24 of file PlayerDataBus.java.
{
        chain.add(listener);
    }
References chain.
unsubscribe()
void com.runehive.game.event.bus.PlayerDataBus.unsubscribe (PlayerEventListener listener)
Definition at line 28 of file PlayerDataBus.java.
{
        chain.remove(listener);
    }
References chain.
Member Data Documentation
chain
final Set<PlayerEventListener> com.runehive.game.event.bus.PlayerDataBus.chain = new HashSet<>() static private
Definition at line 22 of file PlayerDataBus.java.
Referenced by publish(), subscribe(), and unsubscribe().
INSTANCE
final PlayerDataBus com.runehive.game.event.bus.PlayerDataBus.INSTANCE = new PlayerDataBus() static private
Definition at line 12 of file PlayerDataBus.java.
Referenced by getInstance().
The documentation for this class was generated from the following file:
java/com/runehive/game/event/bus/PlayerDataBus.java