RuneHive-Game: com.runehive.game.service.PostgreService Class Reference
com.runehive.game.service.PostgreService Class Reference
Static Public Member Functions
static Connection getConnection () throws SQLException
static HikariDataSource getConnectionPool ()
static void start () throws Exception
Static Private Attributes
static HikariDataSource connectionPool
static final Logger logger = LogManager.getLogger(PostgreService.class)
Detailed Description
Definition at line 14 of file PostgreService.java.
Member Function Documentation
getConnection()
Connection com.runehive.game.service.PostgreService.getConnection () throws SQLException static
Definition at line 39 of file PostgreService.java.
{
        if (Config.WORLD_TYPE != WorldType.LIVE) {
            return DriverManager.getConnection(Config.POSTGRE_URL, Config.POSTGRE_USER, Config.POSTGRE_PASS);
        }
        return connectionPool.getConnection();
    }
References connectionPool, com.runehive.game.world.WorldType.LIVE, com.runehive.Config.POSTGRE_PASS, com.runehive.Config.POSTGRE_URL, com.runehive.Config.POSTGRE_USER, and com.runehive.Config.WORLD_TYPE.
getConnectionPool()
HikariDataSource com.runehive.game.service.PostgreService.getConnectionPool () static
Definition at line 35 of file PostgreService.java.
{
        return connectionPool;
    }
References connectionPool.
Referenced by com.runehive.game.world.entity.mob.player.persist.PlayerPersistDB.load(), com.runehive.util.tools.ItemDBdefUpdate.main(), com.runehive.game.event.impl.log.ChatLogEvent.onLog(), com.runehive.game.event.impl.log.CommandLogEvent.onLog(), com.runehive.game.event.impl.log.DropItemLogEvent.onLog(), com.runehive.game.event.impl.log.PickupItemLogEvent.onLog(), com.runehive.game.event.impl.log.PrivateMessageChatLogEvent.onLog(), com.runehive.game.event.impl.log.TradeLogEvent.onLog(), and com.runehive.game.world.entity.mob.player.persist.PlayerPersistDB.save().
start()
void com.runehive.game.service.PostgreService.start () throws Exception static
Definition at line 20 of file PostgreService.java.
{
        HikariConfig config = new HikariConfig();
        config.setDriverClassName("org.postgresql.Driver");
        config.setJdbcUrl(Config.POSTGRE_URL);
        config.setUsername(Config.POSTGRE_USER);
        config.setPassword(Config.POSTGRE_PASS);
        config.setMaximumPoolSize(50);
        config.setConnectionTimeout(10_000);
        config.setIdleTimeout(0);
        config.setMaxLifetime(0);
        config.addDataSourceProperty("cachePrepStmts", "true");
        connectionPool = new HikariDataSource(config);
        logger.info("Successfully connected to game database.");
    }
References connectionPool, logger, com.runehive.Config.POSTGRE_PASS, com.runehive.Config.POSTGRE_URL, and com.runehive.Config.POSTGRE_USER.
Referenced by com.runehive.RuneHive.start().
Member Data Documentation
connectionPool
HikariDataSource com.runehive.game.service.PostgreService.connectionPool static private
Definition at line 18 of file PostgreService.java.
Referenced by getConnection(), getConnectionPool(), and start().
logger
final Logger com.runehive.game.service.PostgreService.logger = LogManager.getLogger(PostgreService.class) static private
Definition at line 16 of file PostgreService.java.
Referenced by start().
The documentation for this class was generated from the following file:
java/com/runehive/game/service/PostgreService.java