RuneHive-Game: com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob > Class Template Reference
com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob > Class Template Reference
An Iterator implementation designed specifically MobLists.
Public Member Functions
boolean hasNext ()
E next ()
void remove ()
Package Functions
EntityListIterator (MobList< E > list)
Creates a new EntityListIterator.
Private Member Functions
boolean skipNullIndexes ()
Forwards the curr marker until a non-null element is found.
Private Attributes
int curr
The current index.
final MobList< E > list
The MobList this Iterator is dedicated to.
int prev = -1
The previous index.
Detailed Description
An Iterator implementation designed specifically MobLists.
Parameters
<E> The specific type of Entity being managed within this Iterator.
Author
lare96 http://github.org/lare96
Definition at line 36 of file MobList.java.
Constructor & Destructor Documentation
EntityListIterator()
com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.EntityListIterator (MobList< E > list) package
Creates a new EntityListIterator.
Parameters
list The MobList this Iterator is dedicated to.
Definition at line 53 of file MobList.java.
{
            this.list = list;
        }
References list, and com.runehive.game.world.entity.MobList< E extends Mob >.MobList().
Member Function Documentation
hasNext()
boolean com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.hasNext ()
Definition at line 58 of file MobList.java.
{
            return curr < list.capacity() && skipNullIndexes();
        }
References curr, list, and skipNullIndexes().
next()
E com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.next ()
Definition at line 63 of file MobList.java.
{
            skipNullIndexes();
            checkPositionIndex(curr, list.capacity(), "No elements left");
            E entity = list.element(curr);
            prev = curr++;
            return entity;
        }
References curr, list, prev, and skipNullIndexes().
remove()
void com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.remove ()
Definition at line 72 of file MobList.java.
{
            checkState(prev != -1, "remove() can only be called once after each call to next()");
            list.remove(list.get(prev));
            prev = -1;
        }
References list, and prev.
skipNullIndexes()
boolean com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.skipNullIndexes () private
Forwards the curr marker until a non-null element is found.
Returns
true if a non-null element is found, false otherwise.
Definition at line 86 of file MobList.java.
{
            while (list.get(curr) == null) {
                if (++curr >= list.capacity()) {
                    return false;
                }
            }
            return true;
        }
References curr, and list.
Referenced by hasNext(), and next().
Member Data Documentation
curr
int com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.curr private
The current index.
Definition at line 42 of file MobList.java.
Referenced by hasNext(), next(), and skipNullIndexes().
list
final MobList<E> com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.list private
The MobList this Iterator is dedicated to.
Definition at line 39 of file MobList.java.
Referenced by EntityListIterator(), hasNext(), next(), remove(), and skipNullIndexes().
prev
int com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.prev = -1 private
The previous index.
Definition at line 45 of file MobList.java.
Referenced by next(), and remove().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/MobList.java