RuneHive-Game: com.runehive.content.skill.impl.smithing.SmithingArmour Class Reference
com.runehive.content.skill.impl.smithing.SmithingArmour Class Reference
Holds functionality for creating items on an anvil.
Public Member Functions
Optional< SkillAnimation > animation ()
The skill animation to execute.
boolean canInit ()
Determines if this action can be initialized.
double experience ()
The experience given from this action.
String getName ()
Gets the name of this action.
WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
void init ()
Any functionality that should be handled when this action is submitted.
void onCancel (boolean logout)
A function executed on cancellation.
void onProduce (boolean success)
The method executed upon production of an item.
boolean prioritized ()
Determines if this action is prioritized.
Optional< Item[]> produceItem ()
The item that will be added upon production.
Optional< Item[]> removeItem ()
The item that will be removed upon production.
int skill ()
The skill we should hand to experience to.
Public Member Functions inherited from com.runehive.content.skill.impl.ProducingSkillAction
final boolean canRun ()
Determines if the task can be ran.
Optional< String > message ()
The message that will be sent when the player doesn't have the items required.
final void onExecute ()
The method which is called on intervals of the specified #delay;.
ProducingSkillAction (Player player, Optional< Position > position, boolean instant)
Creates a new ProducingSkillAction.
ProducingSkillAction (Player player, Optional< Position > position, int delay, boolean instant)
Creates a new ProducingSkillAction.
Public Member Functions inherited from com.runehive.content.skill.SkillAction
boolean ignore ()
Determines if future skill actions from the same type should be ignored.
SkillAction (Mob mob, Optional< Position > position, boolean instant)
Creates a new Action randomevent.
SkillAction (Mob mob, Optional< Position > position, int delay, boolean instant)
Creates a new Action randomevent.
final void start ()
Attempts to start the skill.
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Static Package Functions
static boolean forge (Player player, int interfaceId, int slot, int amount)
Attempts to forge the item clicked for the specified player.
static boolean openInterface (Player player, Item item, GameObject object)
Opens the smithing itemcontainer and sets all the values for the specified {code player}.
Private Member Functions
SmithingArmour (Player player, SmithingTable definition, int amount)
Constructs a new Smithing skill.
Private Attributes
int amount
The amount being created.
final SmithingTable definition
The definition for this table.
Static Private Attributes
static final int[][] FRAME_DATA = {{1125, 1094, 0, 1119}, {1126, 1091, 0, 1120}, {1109, 1098, 0, 1121}, {1127, 1102, 0, 1122}, {1128, 1107, 0, 1123}, {1124, 1085, 1, 1119}, {1129, 1093, 1, 1120}, {1110, 1099, 1, 1121}, {1113, 1103, 1, 1122}, {1130, 1108, 1, 1123}, {1116, 1087, 2, 1119}, {1118, 1083, 2, 1120}, {1111, 1100, 2, 1121}, {1114, 1104, 2, 1122}, {1131, 1106, 2, 1123}, {1089, 1086, 3, 1119}, {1095, 1092, 3, 1120}, {1112, 1101, 3, 1121}, {1115, 1105, 3, 1122}, {1132, 1096, 3, 1123}, {1090, 1088, 4, 1119}, {8428, 8429, 4, 1120}, {11459, 11461, 4, 1121}, {13357, 13358, 4, 1122}, {1135, 1134, 4, 1123},}
static final ImmutableMap< Integer, SmithingTable[]> TABLE = ImmutableMap.<Integer, SmithingTable[]>builder().put(2349, SmithingTable.BronzeTable.values()).put(2351, SmithingTable.IronTable.values()).put(2353, SmithingTable.SteelTable.values()).put(2359, SmithingTable.MithrilTable.values()).put(2361, SmithingTable.AdamantTable.values()).put(2363, SmithingTable.RuniteTable.values()).build()
Additional Inherited Members
Protected Member Functions inherited from com.runehive.content.skill.SkillAction
final void execute ()
A function representing the unit of work that will be carried out.
final void onSchedule ()
A function executed on registration.
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
Holds functionality for creating items on an anvil.
Author
Stand Up
Definition at line 26 of file SmithingArmour.java.
Constructor & Destructor Documentation
SmithingArmour()
com.runehive.content.skill.impl.smithing.SmithingArmour.SmithingArmour (Player player, SmithingTable definition, int amount) private
Constructs a new Smithing skill.
Definition at line 38 of file SmithingArmour.java.
{
        super(player, Optional.empty(), SkillCape.isEquipped(player, SkillCape.SMITHING) ? 2 : 4, true);
        this.definition = definition;
        this.amount = amount;
    }
References amount, definition, com.runehive.content.skillcape.SkillCape.isEquipped(), and com.runehive.content.skillcape.SkillCape.SMITHING.
Referenced by forge().
Member Function Documentation
animation()
Optional< SkillAnimation > com.runehive.content.skill.impl.smithing.SmithingArmour.animation ()
The skill animation to execute.
Returns
the skill animation to execute.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 222 of file SmithingArmour.java.
{
        return Optional.empty();
    }
canInit()
boolean com.runehive.content.skill.impl.smithing.SmithingArmour.canInit ()
Determines if this action can be initialized.
Returns
true if it can, false otherwise.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 208 of file SmithingArmour.java.
{
        if (!getMob().skills.get(Skill.SMITHING).reqLevel(definition.getLevelRequirement())) {
            getMob().getPlayer().send(new SendMessage("You need a smithing level of " + definition.getLevelRequirement() + " to smith " + StringUtils.appendIndefiniteArticle(definition.getName())));
            return false;
        }
        return true;
    }
References com.runehive.util.StringUtils.appendIndefiniteArticle(), definition, com.runehive.game.action.Action< T extends Mob >.getMob(), and com.runehive.game.world.entity.skill.Skill.SMITHING.
experience()
double com.runehive.content.skill.impl.smithing.SmithingArmour.experience ()
The experience given from this action.
Returns
the numerical value representing the amount of experience given.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 227 of file SmithingArmour.java.
{
        return definition.getExperience() * Config.SMITHING_MODIFICATION;
    }
References definition, and com.runehive.Config.SMITHING_MODIFICATION.
forge()
boolean com.runehive.content.skill.impl.smithing.SmithingArmour.forge (Player player, int interfaceId, int slot, int amount) static package
Attempts to forge the item clicked for the specified player.
Definition at line 45 of file SmithingArmour.java.
{
        if (player.attributes.get("smithing_equipment") == null) {
            return false;
        }
        SmithingTable[] values = TABLE.get(((Item) player.attributes.get("smithing_equipment")).getId());
        if (values == null) {
            return false;
        }
        SmithingTable table = null;
        for (int i = 0; i < FRAME_DATA.length; i++) {
            if (FRAME_DATA[i][3] == interfaceId && slot == FRAME_DATA[i][2]) {
                if (i >= values.length)
                    break;
                table = values[i];
                break;
            }
        }
        if (table == null) {
            return false;
        }
        if(table.getProduced().getId() == 2 && !player.slayer.getUnlocked().contains(SlayerUnlockable.CANNON_BALLS)) {
            player.message("You need to unlock the ability to make cannon balls first.");
            return false;
        }
        if(table.getProduced().getId() == 2 && !player.inventory.contains(4)) {
            player.message("You need a mould to make cannon balls.");
            return false;
        }
        SmithingArmour smithing = new SmithingArmour(player, table, amount);
        smithing.start();
        return true;
    }
References amount, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.skill.impl.slayer.SlayerUnlockable.CANNON_BALLS, com.runehive.game.world.items.containers.ItemContainer.contains(), FRAME_DATA, com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.world.items.Item.getId(), com.runehive.content.skill.impl.smithing.SmithingTable.getProduced(), com.runehive.content.skill.impl.slayer.Slayer.getUnlocked(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.player.Player.slayer, SmithingArmour(), and TABLE.
Referenced by com.runehive.content.skill.impl.smithing.Smithing.itemContainerAction().
getName()
String com.runehive.content.skill.impl.smithing.SmithingArmour.getName ()
Gets the name of this action.
Returns
The name of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 247 of file SmithingArmour.java.
{
        return "smithing_armour";
    }
getWalkablePolicy()
WalkablePolicy com.runehive.content.skill.impl.smithing.SmithingArmour.getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 242 of file SmithingArmour.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
init()
void com.runehive.content.skill.impl.smithing.SmithingArmour.init ()
Any functionality that should be handled when this action is submitted.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 217 of file SmithingArmour.java.
                       {
        getMob().getPlayer().interfaceManager.close();
    }
References com.runehive.game.action.Action< T extends Mob >.getMob().
onCancel()
void com.runehive.content.skill.impl.smithing.SmithingArmour.onCancel (boolean logout)
A function executed on cancellation.
Reimplemented from com.runehive.game.task.Task.
Definition at line 193 of file SmithingArmour.java.
{
        getMob().attributes.remove("smithing_equipment");
    }
References com.runehive.game.action.Action< T extends Mob >.getMob().
onProduce()
void com.runehive.content.skill.impl.smithing.SmithingArmour.onProduce (boolean success)
The method executed upon production of an item.
Parameters
success determines if the production was successful or not.
Reimplemented from com.runehive.content.skill.impl.ProducingSkillAction.
Definition at line 183 of file SmithingArmour.java.
{
        if (success) {
            getMob().getPlayer().animate(new Animation(898));
            amount--;
            if (amount < 1)
                this.cancel();
        }
    }
References amount, com.runehive.game.task.Task.cancel(), and com.runehive.game.action.Action< T extends Mob >.getMob().
openInterface()
boolean com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface (Player player, Item item, GameObject object) static package
Opens the smithing itemcontainer and sets all the values for the specified {code player}.
Definition at line 85 of file SmithingArmour.java.
{
        if (object.getDefinition().getId() != 2097 && object.getDefinition().getId() != 2672) {
            return false;
        }
        if (!player.inventory.containsAny(2347, 2949)) {
            player.send(new SendMessage("You need a hammer to forge items."));
            return true;
        }
        if (item.getId() == 11286) {
            if (!player.inventory.containsAll(11286, 1540)) {
                player.send(new SendMessage("You need a dragonic visage and an anti-dragonfire shield."));
                return true;
            }
            if (!player.skills.get(Skill.SMITHING).reqLevel(85)) {
                player.send(new SendMessage("You need a level of 85 smithing to do this."));
                return true;
            }
            player.animate(new Animation(898));
            player.skills.addExperience(Skill.SMITHING, 350 * Config.SMITHING_MODIFICATION);
            player.inventory.removeAll(new Item(11286), new Item(1540));
            player.inventory.add(new Item(11283));
            return true;
        }
        if (item.getId() == 22006) {
            if (!player.inventory.containsAll(22006, 1540)) {
                player.send(new SendMessage("You need a skeletal visage and an anti-dragonfire shield."));
                return true;
            }
            if (!player.skills.get(Skill.SMITHING).reqLevel(90)) {
                player.send(new SendMessage("You need a level of 90 smithing to do this."));
                return true;
            }
            player.animate(new Animation(898));
            player.skills.addExperience(Skill.SMITHING, 2000 * Config.SMITHING_MODIFICATION);
            player.inventory.removeAll(new Item(22006), new Item(1540));
            player.inventory.add(new Item(22003));
            return true;
        }
        //Godsword blade creation.
        if (item.getId() == 11794 || item.getId() == 11796 || item.getId() == 11798) {
            if (!player.inventory.containsAll(11794, 11796, 11798)) {
                player.send(new SendMessage("You do not have all the godsword shards."));
                return true;
            }
            if (!player.skills.get(Skill.SMITHING).reqLevel(80)) {
                player.send(new SendMessage("You need a level of 80 smithing to do this."));
                return true;
            }
            player.animate(new Animation(898));
            player.skills.addExperience(Skill.SMITHING, 200);
            player.inventory.removeAll(new Item(11794), new Item(11796), new Item(11798));
            player.inventory.add(new Item(11798));
            return true;
        }
        SmithingTable[] values = TABLE.get(item.getId());
        if (values == null) {
            return false;
        }
        SmithingTable table = null;
        for (int i = 0; i < FRAME_DATA.length; i++) {
            if (i >= values.length) {
                player.send(new SendString("", FRAME_DATA[i][0]));
                player.send(new SendString("", FRAME_DATA[i][1]));
                player.send(new SendItemOnInterfaceSlot(FRAME_DATA[i][3], new Item(-1, 0), FRAME_DATA[i][2]));
                continue;
            }
            table = values[i];
            if (table == null || table.getBar() == null) {
                return false;
            }
            final boolean has_bar = player.inventory.computeAmountForId(table.getBar().getId()) >= table.getBarsRequired();
            final String bar_color = !has_bar ? "@red@" : "@gre@";
            final String name_color = player.skills.get(Skill.SMITHING).getMaxLevel() >= table.getLevelRequirement() && has_bar ? "@whi@" : "@bla@";
            player.send(new SendString(bar_color + table.getBarsRequired() + " Bar" + (table.getBarsRequired() != 1 ? "s" : ""), FRAME_DATA[i][0]));
            player.send(new SendString(name_color + StringUtils.capitalize(table.getName().toLowerCase()), FRAME_DATA[i][1]));
            player.send(new SendItemOnInterfaceSlot(FRAME_DATA[i][3], table.getProduced(), FRAME_DATA[i][2]));
        }
        if (table == null || table.getBar() == null) {
            return false;
        }
        player.attributes.set("smithing_equipment", table.getBar());
        player.interfaceManager.open(994);
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.util.StringUtils.capitalize(), com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.world.items.containers.ItemContainer.containsAny(), FRAME_DATA, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.content.skill.impl.smithing.SmithingTable.getBar(), com.runehive.content.skill.impl.smithing.SmithingTable.getBarsRequired(), com.runehive.game.world.items.Item.getId(), com.runehive.content.skill.impl.smithing.SmithingTable.getLevelRequirement(), com.runehive.game.world.entity.skill.Skill.getMaxLevel(), com.runehive.content.skill.impl.smithing.SmithingTable.getName(), com.runehive.content.skill.impl.smithing.SmithingTable.getProduced(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.game.world.items.containers.ItemContainer.removeAll(), com.runehive.game.world.entity.skill.Skill.reqLevel(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.skill.Skill.SMITHING, com.runehive.Config.SMITHING_MODIFICATION, and TABLE.
Referenced by com.runehive.content.skill.impl.smithing.Smithing.clickObject(), and com.runehive.content.skill.impl.smithing.Smithing.useItem().
prioritized()
boolean com.runehive.content.skill.impl.smithing.SmithingArmour.prioritized ()
Determines if this action is prioritized.
When making an action prioritized, the next action will be ignored if not queued.
Returns
true if this action is prioritized, false otherwise.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 237 of file SmithingArmour.java.
{
        return false;
    }
produceItem()
Optional< Item[]> com.runehive.content.skill.impl.smithing.SmithingArmour.produceItem ()
The item that will be added upon production.
Returns
the item that will be added.
Reimplemented from com.runehive.content.skill.impl.ProducingSkillAction.
Definition at line 203 of file SmithingArmour.java.
{
        return Optional.of(new Item[]{definition.getProduced()});
    }
References definition.
removeItem()
Optional< Item[]> com.runehive.content.skill.impl.smithing.SmithingArmour.removeItem ()
The item that will be removed upon production.
Returns
the item that will be removed.
Reimplemented from com.runehive.content.skill.impl.ProducingSkillAction.
Definition at line 198 of file SmithingArmour.java.
{
        return Optional.of(new Item[]{new Item(definition.getBar().getId(), definition.getBarsRequired())});
    }
References definition.
skill()
int com.runehive.content.skill.impl.smithing.SmithingArmour.skill ()
The skill we should hand to experience to.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 232 of file SmithingArmour.java.
                       {
        return Skill.SMITHING;
    }
References com.runehive.game.world.entity.skill.Skill.SMITHING.
Member Data Documentation
amount
int com.runehive.content.skill.impl.smithing.SmithingArmour.amount private
The amount being created.
Definition at line 35 of file SmithingArmour.java.
Referenced by forge(), onProduce(), and SmithingArmour().
definition
final SmithingTable com.runehive.content.skill.impl.smithing.SmithingArmour.definition private
The definition for this table.
Definition at line 32 of file SmithingArmour.java.
Referenced by canInit(), experience(), produceItem(), removeItem(), and SmithingArmour().
FRAME_DATA
final int [][] com.runehive.content.skill.impl.smithing.SmithingArmour.FRAME_DATA = {{1125, 1094, 0, 1119}, {1126, 1091, 0, 1120}, {1109, 1098, 0, 1121}, {1127, 1102, 0, 1122}, {1128, 1107, 0, 1123}, {1124, 1085, 1, 1119}, {1129, 1093, 1, 1120}, {1110, 1099, 1, 1121}, {1113, 1103, 1, 1122}, {1130, 1108, 1, 1123}, {1116, 1087, 2, 1119}, {1118, 1083, 2, 1120}, {1111, 1100, 2, 1121}, {1114, 1104, 2, 1122}, {1131, 1106, 2, 1123}, {1089, 1086, 3, 1119}, {1095, 1092, 3, 1120}, {1112, 1101, 3, 1121}, {1115, 1105, 3, 1122}, {1132, 1096, 3, 1123}, {1090, 1088, 4, 1119}, {8428, 8429, 4, 1120}, {11459, 11461, 4, 1121}, {13357, 13358, 4, 1122}, {1135, 1134, 4, 1123},} static private
Definition at line 29 of file SmithingArmour.java.
{{1125, 1094, 0, 1119}, {1126, 1091, 0, 1120}, {1109, 1098, 0, 1121}, {1127, 1102, 0, 1122}, {1128, 1107, 0, 1123}, {1124, 1085, 1, 1119}, {1129, 1093, 1, 1120}, {1110, 1099, 1, 1121}, {1113, 1103, 1, 1122}, {1130, 1108, 1, 1123}, {1116, 1087, 2, 1119}, {1118, 1083, 2, 1120}, {1111, 1100, 2, 1121}, {1114, 1104, 2, 1122}, {1131, 1106, 2, 1123}, {1089, 1086, 3, 1119}, {1095, 1092, 3, 1120}, {1112, 1101, 3, 1121}, {1115, 1105, 3, 1122}, {1132, 1096, 3, 1123}, {1090, 1088, 4, 1119}, {8428, 8429, 4, 1120}, {11459, 11461, 4, 1121}, {13357, 13358, 4, 1122}, {1135, 1134, 4, 1123},};
Referenced by forge(), and openInterface().
TABLE
final ImmutableMap<Integer, SmithingTable[]> com.runehive.content.skill.impl.smithing.SmithingArmour.TABLE = ImmutableMap.<Integer, SmithingTable[]>builder().put(2349, SmithingTable.BronzeTable.values()).put(2351, SmithingTable.IronTable.values()).put(2353, SmithingTable.SteelTable.values()).put(2359, SmithingTable.MithrilTable.values()).put(2361, SmithingTable.AdamantTable.values()).put(2363, SmithingTable.RuniteTable.values()).build() static private
Definition at line 28 of file SmithingArmour.java.
Referenced by forge(), and openInterface().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/smithing/SmithingArmour.java