RuneHive-Game: com.runehive.content.event.EventDispatcher Class Reference
com.runehive.content.event.EventDispatcher Class Reference
Public Member Functions
void dispatch (InteractionType type, EventHandler eventHandler)
EventDispatcher (InteractionEvent interactionEvent)
Static Public Member Functions
static boolean execute (Player player, InteractionEvent event)
Private Attributes
final InteractionEvent interactionEvent
Detailed Description
Definition at line 7 of file EventDispatcher.java.
Constructor & Destructor Documentation
EventDispatcher()
com.runehive.content.event.EventDispatcher.EventDispatcher (InteractionEvent interactionEvent)
Definition at line 11 of file EventDispatcher.java.
{
        this.interactionEvent = interactionEvent;
    }
References interactionEvent.
Member Function Documentation
dispatch()
void com.runehive.content.event.EventDispatcher.dispatch (InteractionType type, EventHandler eventHandler)
Definition at line 19 of file EventDispatcher.java.
{
        if (interactionEvent.isHandled()) {
            return;
        }
        if (interactionEvent.getType() == type) {
            interactionEvent.setHandled(eventHandler.handle(interactionEvent));
        }
    }
References com.runehive.content.event.EventHandler.handle(), and interactionEvent.
Referenced by com.runehive.content.activity.Activity.onEvent(), and com.runehive.game.world.entity.skill.Skill.onEvent().
execute()
boolean com.runehive.content.event.EventDispatcher.execute (Player player, InteractionEvent event) static
Definition at line 15 of file EventDispatcher.java.
{
        return player.inActivity() && Activity.evaluate(player, it -> it.onEvent(player, event)) || player.skills.onEvent(event);
    }
References com.runehive.content.activity.Activity.evaluate(), com.runehive.game.world.entity.mob.Mob.inActivity(), com.runehive.game.world.entity.skill.SkillManager.onEvent(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fifthAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.firstAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fourthAction(), com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnItem(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handleSecondOption(), com.runehive.net.packet.in.ItemOptionPacketListener.handleThirdOption(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), com.runehive.game.world.entity.mob.player.Player.register(), com.runehive.net.packet.in.ItemContainerActionPacketListener.secondAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.sixthAction(), and com.runehive.net.packet.in.ItemContainerActionPacketListener.thirdAction().
Member Data Documentation
interactionEvent
final InteractionEvent com.runehive.content.event.EventDispatcher.interactionEvent private
Definition at line 9 of file EventDispatcher.java.
Referenced by dispatch(), and EventDispatcher().
The documentation for this class was generated from the following file:
java/com/runehive/content/event/EventDispatcher.java