RuneHive-Game: com.runehive.util.RandomGen Class Reference
com.runehive.util.RandomGen Class Reference
The ThreadLocalRandom wrapper that provides additional functionality for generating pseudo-random numbers.
Public Member Functions
float floatRandom (float range)
Returns a pseudo-random float between inclusive 0 and exclusive range.
ThreadLocalRandom get ()
Gets the backing ThreadLocalRandom.
int inclusive (int min, int max)
Returns a pseudo-random int value between inclusive min and inclusive max.
int inclusive (int range)
Returns a pseudo-random int value between inclusive 0 and inclusive range.
int inclusiveExcludes (int min, int max, int... exclude)
Returns a pseudo-random int value between inclusive min and inclusive max excluding the specified numbers within the excludes array.
boolean random (boolean[] array)
Pseudo-randomly retrieves an boolean from this array.
byte random (byte[] array)
Pseudo-randomly retrieves an byte from this array.
char random (char[] array)
Pseudo-randomly retrieves an char from this array.
double random (double[] array)
Pseudo-randomly retrieves an double from this array.
float random (float[] array)
Pseudo-randomly retrieves an float from this array.
int random (int[] array)
Pseudo-randomly retrieves an int from this array.
long random (long[] array)
Pseudo-randomly retrieves an long from this array.
short random (short[] array)
Pseudo-randomly retrieves an short from this array.
int randomIndex (Object[] array)
Pseudo-randomly retrieves an index from array.
boolean[] shuffle (boolean[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an boolean array.
byte[] shuffle (byte[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an byte array.
char[] shuffle (char[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an char array.
double[] shuffle (double[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an double array.
float[] shuffle (float[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an float array.
int[] shuffle (int[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an int array.
long[] shuffle (long[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an long array.
short[] shuffle (short[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an short array.
boolean success (double value)
Determines if a pseudorandomly generated double rounded to two decimal places is below or equal to value.
Package Functions
public< T > T random (List< T > list)
Pseudo-randomly retrieves a element from list.
public< T > T random (T[] array)
Pseudo-randomly retrieves a element from array.
public< T > T[] shuffle (T[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an T array.
Private Attributes
final ThreadLocalRandom random = ThreadLocalRandom.current()
The backing ThreadLocalRandom that will pseudorandomly generate numbers.
Detailed Description
The ThreadLocalRandom wrapper that provides additional functionality for generating pseudo-random numbers.
In order to avoid sharing instances of this class across multiple threads, this should only be instantiated locally unless certain that it will never be accessed by another thread.
Author
lare96 http://github.com/lare96
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Definition at line 16 of file RandomGen.java.
Member Function Documentation
floatRandom()
float com.runehive.util.RandomGen.floatRandom (float range)
Returns a pseudo-random float between inclusive 0 and exclusive range.
Parameters
range The exclusive range.
Returns
The pseudo-random float.
Exceptions
IllegalArgumentException If the specified range is less than 0.
Definition at line 95 of file RandomGen.java.
{
        if(range < 0F)
            throw new IllegalArgumentException("range <= 0");
        return random.nextFloat() * range;
    }
References random.
get()
ThreadLocalRandom com.runehive.util.RandomGen.get ()
Gets the backing ThreadLocalRandom.
Returns
the backing random instance.
Definition at line 37 of file RandomGen.java.
{
        return random;
    }
References random.
inclusive() [1/2]
int com.runehive.util.RandomGen.inclusive (int min, int max)
Returns a pseudo-random int value between inclusive min and inclusive max.
Parameters
min the minimum inclusive number.
max the maximum inclusive number.
Returns
the pseudo-random int.
Exceptions
IllegalArgumentException if max - min + 1 is less than 0.
Definition at line 49 of file RandomGen.java.
{
        if(max < min) {
            max = min + 1;
        }
        return random.nextInt((max - min) + 1) + min;
    }
References random.
Referenced by inclusive(), inclusiveExcludes(), and com.runehive.game.world.entity.mob.npc.drop.NpcDrop.toItem().
inclusive() [2/2]
int com.runehive.util.RandomGen.inclusive (int range)
Returns a pseudo-random int value between inclusive 0 and inclusive range.
Parameters
range the maximum inclusive number.
Returns
the pseudo-random int.
Exceptions
IllegalArgumentException if max - min + 1 is less than 0.
Definition at line 63 of file RandomGen.java.
{
        return inclusive(0, range);
    }
References inclusive().
inclusiveExcludes()
int com.runehive.util.RandomGen.inclusiveExcludes (int min, int max, int... exclude)
Returns a pseudo-random int value between inclusive min and inclusive max excluding the specified numbers within the excludes array.
Parameters
min the minimum inclusive number.
max the maximum inclusive number.
Returns
the pseudo-random int.
Exceptions
IllegalArgumentException if max - min + 1 is less than 0.
See also
inclusive(int, int).
Definition at line 77 of file RandomGen.java.
{
        Arrays.sort(exclude);
        int result = inclusive(min, max);
        while(Arrays.binarySearch(exclude, result) >= 0) {
            result = inclusive(min, max);
        }
        return result;
    }
References inclusive().
random() [1/10]
boolean com.runehive.util.RandomGen.random (boolean[] array)
Pseudo-randomly retrieves an boolean from this array.
Parameters
array the array to retrieve an boolean from.
Returns
the boolean retrieved from the array.
Definition at line 178 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
random() [2/10]
byte com.runehive.util.RandomGen.random (byte[] array)
Pseudo-randomly retrieves an byte from this array.
Parameters
array the array to retrieve an byte from.
Returns
the byte retrieved from the array.
Definition at line 160 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
random() [3/10]
char com.runehive.util.RandomGen.random (char[] array)
Pseudo-randomly retrieves an char from this array.
Parameters
array the array to retrieve an char from.
Returns
the char retrieved from the array.
Definition at line 187 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
random() [4/10]
double com.runehive.util.RandomGen.random (double[] array)
Pseudo-randomly retrieves an double from this array.
Parameters
array the array to retrieve an double from.
Returns
the double retrieved from the array.
Definition at line 142 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
random() [5/10]
float com.runehive.util.RandomGen.random (float[] array)
Pseudo-randomly retrieves an float from this array.
Parameters
array the array to retrieve an float from.
Returns
the float retrieved from the array.
Definition at line 169 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
random() [6/10]
int com.runehive.util.RandomGen.random (int[] array)
Pseudo-randomly retrieves an int from this array.
Parameters
array the array to retrieve an int from.
Returns
the int retrieved from the array.
Definition at line 124 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
random() [7/10]
public< T > T com.runehive.util.RandomGen.random (List< T > list) package
Pseudo-randomly retrieves a element from list.
Parameters
list the list to retrieve an element from.
Returns
the element retrieved from the list.
Definition at line 196 of file RandomGen.java.
{
        return list.get((int) (random.nextDouble() * list.size()));
    }
References random.
random() [8/10]
long com.runehive.util.RandomGen.random (long[] array)
Pseudo-randomly retrieves an long from this array.
Parameters
array the array to retrieve an long from.
Returns
the long retrieved from the array.
Definition at line 133 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
random() [9/10]
short com.runehive.util.RandomGen.random (short[] array)
Pseudo-randomly retrieves an short from this array.
Parameters
array the array to retrieve an short from.
Returns
the short retrieved from the array.
Definition at line 151 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
random() [10/10]
public< T > T com.runehive.util.RandomGen.random (T[] array) package
Pseudo-randomly retrieves a element from array.
Parameters
array the array to retrieve an element from.
Returns
the element retrieved from the array.
Definition at line 115 of file RandomGen.java.
{
        return array[(int) (random.nextDouble() * array.length)];
    }
References random.
randomIndex()
int com.runehive.util.RandomGen.randomIndex (Object[] array)
Pseudo-randomly retrieves an index from array.
Parameters
array the array to retrieve an index from.
Returns
the element retrieved from the array.
Definition at line 106 of file RandomGen.java.
{
        return (int) (random.nextDouble() * array.length);
    }
References random.
shuffle() [1/9]
boolean[] com.runehive.util.RandomGen.shuffle (boolean[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an boolean array.
Parameters
array the array that will be shuffled.
Returns
the shuffled array.
Definition at line 318 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            boolean a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
shuffle() [2/9]
byte[] com.runehive.util.RandomGen.shuffle (byte[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an byte array.
Parameters
array the array that will be shuffled.
Returns
the shuffled array.
Definition at line 286 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            byte a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
shuffle() [3/9]
char[] com.runehive.util.RandomGen.shuffle (char[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an char array.
Parameters
array the array that will be shuffled.
Definition at line 333 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            char a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
shuffle() [4/9]
double[] com.runehive.util.RandomGen.shuffle (double[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an double array.
Parameters
array the array that will be shuffled.
Returns
the shuffled array.
Definition at line 254 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            double a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
shuffle() [5/9]
float[] com.runehive.util.RandomGen.shuffle (float[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an float array.
Parameters
array the array that will be shuffled.
Returns
the shuffled array.
Definition at line 302 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            float a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
shuffle() [6/9]
int[] com.runehive.util.RandomGen.shuffle (int[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an int array.
Parameters
array the array that will be shuffled.
Returns
the shuffled array.
Definition at line 222 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            int a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
shuffle() [7/9]
long[] com.runehive.util.RandomGen.shuffle (long[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an long array.
Parameters
array the array that will be shuffled.
Returns
the shuffled array.
Definition at line 238 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            long a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
shuffle() [8/9]
short[] com.runehive.util.RandomGen.shuffle (short[] array)
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an short array.
Parameters
array the array that will be shuffled.
Returns
the shuffled array.
Definition at line 270 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            short a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
shuffle() [9/9]
public< T > T[] com.runehive.util.RandomGen.shuffle (T[] array) package
An implementation of the Fisher-Yates shuffle algorithm that will shuffle the elements of an T array.
Parameters
array the array that will be shuffled.
Returns
the shuffled array.
Definition at line 206 of file RandomGen.java.
{
        for(int i = array.length - 1; i > 0; i--) {
            int index = random.nextInt(i + 1);
            T a = array[index];
            array[index] = array[i];
            array[i] = a;
        }
        return array;
    }
References random.
success()
boolean com.runehive.util.RandomGen.success (double value)
Determines if a pseudorandomly generated double rounded to two decimal places is below or equal to value.
Parameters
value the value to determine this for.
Returns
true if successful, false otherwise.
Definition at line 349 of file RandomGen.java.
{
        return random.nextDouble() <= value;
    }
References random.
Member Data Documentation
random
final ThreadLocalRandom com.runehive.util.RandomGen.random = ThreadLocalRandom.current() private
The backing ThreadLocalRandom that will pseudorandomly generate numbers.
It is generally preferred to use this over Random because although Random is thread safe; the same seed is shared concurrently, which leads to contention between multiple threads and overhead as a result of that. Surprisingly because of the way that ThreadLocalRandom works, even in completely single-threaded situations it runs up to three times faster than Random.
See also
java.util.Random and java.util.concurrent.ThreadLocalRandom in multithreaded environments
Definition at line 31 of file RandomGen.java.
Referenced by floatRandom(), get(), inclusive(), random(), random(), random(), random(), random(), random(), random(), random(), random(), random(), randomIndex(), shuffle(), shuffle(), shuffle(), shuffle(), shuffle(), shuffle(), shuffle(), shuffle(), shuffle(), and success().
The documentation for this class was generated from the following file:
java/com/runehive/util/RandomGen.java