RuneHive-Game: com.runehive.util.parser.old.defs.EquipmentRequirement Class Reference
com.runehive.util.parser.old.defs.EquipmentRequirement Class Reference
Represents the requirements for equipping items.
Public Member Functions
EquipmentRequirement (int level, int skill)
Creates a new EquipmentRequirement.
Public Member Functions inherited from com.runehive.game.world.items.SkillRequirement
int getLevel ()
int getSkill ()
SkillRequirement (int level, int skill)
Creates a new SkillRequirement.
Static Public Member Functions
static boolean canEquip (Player player, int itemId)
Determines if a player can equip a specified item.
Detailed Description
Represents the requirements for equipping items.
Author
Seven
Definition at line 14 of file EquipmentRequirement.java.
Constructor & Destructor Documentation
EquipmentRequirement()
com.runehive.util.parser.old.defs.EquipmentRequirement.EquipmentRequirement (int level, int skill)
Creates a new EquipmentRequirement.
Parameters
level The level required
skill The skill required.
Definition at line 25 of file EquipmentRequirement.java.
{
        super(level, skill);
    }
References com.runehive.game.world.items.SkillRequirement.level, and com.runehive.game.world.items.SkillRequirement.skill.
Member Function Documentation
canEquip()
boolean com.runehive.util.parser.old.defs.EquipmentRequirement.canEquip (Player player, int itemId) static
Determines if a player can equip a specified item.
Parameters
player The player that is equipping the item.
itemId The id of the item to check.
Definition at line 38 of file EquipmentRequirement.java.
{
        final EquipmentDefinition req = EquipmentDefinition.EQUIPMENT_DEFINITIONS.get(itemId);
        if (req == null) return true;
        for (final SkillRequirement r : req.getRequirements()) {
            if (r == null) continue;
            if (player.skills.getMaxLevel(r.getSkill()) < r.getLevel()) {
                player.send(new SendMessage("You need " + Utility.getAOrAn(Skill.getName(r.getSkill())) + " " + Skill.getName(r.getSkill()) + " level of " + r.getLevel() + " to equip this item."));
                return false;
            }
        }
        return true;
    }
References com.runehive.util.parser.old.defs.EquipmentDefinition.EQUIPMENT_DEFINITIONS, com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.skill.Skill.getName(), com.runehive.util.parser.old.defs.EquipmentDefinition.getRequirements(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.items.SkillRequirement.SkillRequirement(), and com.runehive.game.world.entity.mob.Mob.skills.
The documentation for this class was generated from the following file:
java/com/runehive/util/parser/old/defs/EquipmentRequirement.java