RuneHive-Game: com.runehive.content.itemaction.impl.TridentOfTheSeas Class Reference
com.runehive.content.itemaction.impl.TridentOfTheSeas Class Reference
Public Member Functions
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
TridentOfTheSeas ()
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
boolean drop (Player player, Item item)
String message (Item item)
The message of the action.
String toString ()
Static Private Member Functions
static void check (Player player)
static void uncharge (Player player)
Static Private Attributes
static final short CHARGE_LIMIT = 2500
static final DecimalFormat FORMATTER = new DecimalFormat("#.#")
static final short TRIDENT_ID = 11907
Detailed Description
Definition at line 13 of file TridentOfTheSeas.java.
Constructor & Destructor Documentation
TridentOfTheSeas()
com.runehive.content.itemaction.impl.TridentOfTheSeas.TridentOfTheSeas ()
Definition at line 18 of file TridentOfTheSeas.java.
{
        FORMATTER.setRoundingMode(RoundingMode.FLOOR);
    }
References FORMATTER.
Member Function Documentation
check()
void com.runehive.content.itemaction.impl.TridentOfTheSeas.check (Player player) static private
Definition at line 116 of file TridentOfTheSeas.java.
{
        player.message("You have " + Utility.formatDigits(player.tridentSeasCharges) + " charges in your Trident of the Seas.");
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.entity.mob.player.Player.tridentSeasCharges.
Referenced by equipment(), and inventory().
equipment()
boolean com.runehive.content.itemaction.impl.TridentOfTheSeas.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 105 of file TridentOfTheSeas.java.
{
        if (item.getId() != TRIDENT_ID) {
            return false;
        }
        if (opcode == 1) {
            check(player);
            return true;
        }
        return true;
    }
References check(), com.runehive.game.world.items.Item.getId(), and TRIDENT_ID.
inventory()
boolean com.runehive.content.itemaction.impl.TridentOfTheSeas.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 89 of file TridentOfTheSeas.java.
{
        if (item.getId() != TRIDENT_ID) {
            return false;
        }
        if (opcode == 2) {
            check(player);
            return true;
        }
        if (opcode == 3) {
            uncharge(player);
            return true;
        }
        return true;
    }
References check(), com.runehive.game.world.items.Item.getId(), TRIDENT_ID, and uncharge().
itemOnItem()
boolean com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 28 of file TridentOfTheSeas.java.
{
        if (first.getId() != TRIDENT_ID && second.getId() != TRIDENT_ID) {
            return false;
        }
        if (ItemCreation.CreationData.forItems(first, second).isPresent()) {
            if (player.tridentSeasCharges > 0) {
                player.message("You must empty your trident charges before doing this.");
                return true;
            }
            return false;
        }
        if (player.tridentSeasCharges >= CHARGE_LIMIT) {
            player.message("Your Trident of the Seas is already fully charged.");
            return true;
        }
        int id1 = first.getId();
        int id2 = second.getId();
        if (id1 == TRIDENT_ID && id2 != TRIDENT_ID)
            if (id2 != 560 && id2 != 562 && id2 != 554 && id2 != 995)
                return true;
        if (id2 == TRIDENT_ID && id1 != TRIDENT_ID)
            if (id1 != 560 && id1 != 562 && id1 != 554 && id1 != 995)
                return true;
        int death = player.inventory.computeAmountForId(560);
        int chaos = player.inventory.computeAmountForId(562);
        int fire = player.inventory.computeAmountForId(554);
        int coins = player.inventory.computeAmountForId(995);
        if (death >= 1 && chaos >= 1 && fire >= 5 && coins >= 10) {
            int minF = fire / 5;
            int minC = coins / 10;
            int charges = Math.min(Math.min(death, chaos), Math.min(minF, minC));
            if (charges > CHARGE_LIMIT)
                charges = CHARGE_LIMIT;
            if (charges > CHARGE_LIMIT - player.tridentSeasCharges)
                charges = CHARGE_LIMIT - player.tridentSeasCharges;
            if (charges > 0) {
                player.inventory.remove(new Item(560, charges), -1, false);
                player.inventory.remove(new Item(562, charges), -1, false);
                player.inventory.remove(new Item(554, charges * 5), -1, false);
                player.inventory.remove(new Item(995, charges * 10), -1, false);
                player.inventory.refresh();
                player.tridentSeasCharges += charges;
                player.message("You added " + charges + " charges to your Trident of the Seas");
            }
        } else {
            player.message("You need at least 1 x death rune, 1 x chaos rune, 5 x fire runes and 10gp for one charge.", "Your Trident of the Seas can hold ");
        }
        return true;
    }
References CHARGE_LIMIT, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.content.ItemCreation.CreationData.forItems(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), TRIDENT_ID, and com.runehive.game.world.entity.mob.player.Player.tridentSeasCharges.
name()
String com.runehive.content.itemaction.impl.TridentOfTheSeas.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 23 of file TridentOfTheSeas.java.
{
        return "Trident of the Seas";
    }
uncharge()
void com.runehive.content.itemaction.impl.TridentOfTheSeas.uncharge (Player player) static private
Definition at line 120 of file TridentOfTheSeas.java.
{
        if (player.tridentSeasCharges < 1) {
            return;
        }
        int amount = player.tridentSeasCharges;
        if (!player.inventory.hasCapacityFor(new Item(560, amount), new Item(562, amount), new Item(554, amount * 5))) {
            player.message("You don't have enough inventory space to uncharge your trident.");
            return;
        }
        player.inventory.add(new Item(560, amount), -1, false);
        player.inventory.add(new Item(562, amount), -1, false);
        player.inventory.add(new Item(554, amount * 5), -1, false);
        player.inventory.refresh();
        player.tridentSeasCharges = 0;
        player.message("You uncharge your trident.");
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), and com.runehive.game.world.entity.mob.player.Player.tridentSeasCharges.
Referenced by inventory().
Member Data Documentation
CHARGE_LIMIT
final short com.runehive.content.itemaction.impl.TridentOfTheSeas.CHARGE_LIMIT = 2500 static private
Definition at line 15 of file TridentOfTheSeas.java.
Referenced by itemOnItem().
FORMATTER
final DecimalFormat com.runehive.content.itemaction.impl.TridentOfTheSeas.FORMATTER = new DecimalFormat("#.#") static private
Definition at line 16 of file TridentOfTheSeas.java.
Referenced by TridentOfTheSeas().
TRIDENT_ID
final short com.runehive.content.itemaction.impl.TridentOfTheSeas.TRIDENT_ID = 11907 static private
Definition at line 14 of file TridentOfTheSeas.java.
Referenced by equipment(), inventory(), and itemOnItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/TridentOfTheSeas.java