RuneHive-Game: com.runehive.game.world.entity.combat.attack.Modifier Class Reference
com.runehive.game.world.entity.combat.attack.Modifier Class Reference
Public Member Functions
int modifyAggressive (int level)
int modifyAttack (int level)
int modifyDamage (int damage)
int modifyDefensive (int level)
int modifyMagic (int level)
int modifyMaxHit (int max)
int modifyRanged (int level)
Static Public Member Functions
static Modifier link (Modifier first, Modifier second)
static void main (String[] args)
Protected Member Functions
final Modifier aggressive (double percentage)
final Modifier aggressive (int level)
final Modifier attack (int level)
final Modifier attackPercent (double percentage)
final Modifier defensive (double percentage)
final Modifier defensive (int level)
final Modifier magic (double percentage)
final Modifier magic (int level)
final Modifier maxHit (double percentage)
final Modifier maxHit (int level)
final Modifier ranged (double percentage)
final Modifier ranged (int level)
Static Private Member Functions
static Function< Integer, Integer > addition (int amount)
static Modifier attack (double percent)
static Function< Integer, Integer > link (Function< Integer, Integer > modifier, Function< Integer, Integer > next)
static Function< Integer, Integer > percentage (double percent)
Private Attributes
Function< Integer, Integer > aggressiveModifier = Function.identity()
Function< Integer, Integer > attackModifier = Function.identity()
Function< Integer, Integer > damageModifier = Function.identity()
Function< Integer, Integer > defensiveModifier = Function.identity()
Function< Integer, Integer > magicModifier = Function.identity()
Function< Integer, Integer > maxHitModifier = Function.identity()
Function< Integer, Integer > rangedModifier = Function.identity()
Detailed Description
Definition at line 5 of file Modifier.java.
Member Function Documentation
addition()
Function< Integer, Integer > com.runehive.game.world.entity.combat.attack.Modifier.addition (int amount) static private
Definition at line 125 of file Modifier.java.
{
        return modifier -> modifier + amount;
    }
Referenced by aggressive(), attack(), defensive(), magic(), maxHit(), and ranged().
aggressive() [1/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.aggressive (double percentage) protected
Definition at line 32 of file Modifier.java.
{
        aggressiveModifier = link(aggressiveModifier, percentage(percentage));
        return this;
    }
References aggressiveModifier, link(), and percentage().
aggressive() [2/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.aggressive (int level) protected
Definition at line 64 of file Modifier.java.
{
        aggressiveModifier = aggressiveModifier.andThen(addition(level));
        return this;
    }
References addition(), and aggressiveModifier.
attack() [1/2]
Modifier com.runehive.game.world.entity.combat.attack.Modifier.attack (double percent) static private
Definition at line 133 of file Modifier.java.
{
        return new Modifier() {{ attackPercent(percent); }};
    }
References attackPercent().
attack() [2/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.attack (int level) protected
Definition at line 49 of file Modifier.java.
{
        attackModifier = link(attackModifier, addition(level));
        return this;
    }
References addition(), attackModifier, and link().
Referenced by main().
attackPercent()
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.attackPercent (double percentage) protected
Definition at line 17 of file Modifier.java.
{
        attackModifier = link(attackModifier, percentage(percentage));
        return this;
    }
References attackModifier, link(), and percentage().
Referenced by attack().
defensive() [1/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.defensive (double percentage) protected
Definition at line 37 of file Modifier.java.
{
        defensiveModifier = link(defensiveModifier, percentage(percentage));
        return this;
    }
References defensiveModifier, link(), and percentage().
defensive() [2/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.defensive (int level) protected
Definition at line 69 of file Modifier.java.
{
        defensiveModifier = defensiveModifier.andThen(addition(level));
        return this;
    }
References addition(), and defensiveModifier.
link() [1/2]
Function< Integer, Integer > com.runehive.game.world.entity.combat.attack.Modifier.link (Function< Integer, Integer > modifier, Function< Integer, Integer > next) static private
Definition at line 121 of file Modifier.java.
{
        return modifier.andThen(next);
    }
link() [2/2]
Modifier com.runehive.game.world.entity.combat.attack.Modifier.link (Modifier first, Modifier second) static
Definition at line 81 of file Modifier.java.
{
        Modifier modifier = new Modifier();
        modifier.attackModifier = first.attackModifier.andThen(second.attackModifier);
        modifier.magicModifier = first.magicModifier.andThen(second.magicModifier);
        modifier.rangedModifier = first.rangedModifier.andThen(second.rangedModifier);
        modifier.aggressiveModifier = first.aggressiveModifier.andThen(second.aggressiveModifier);
        modifier.defensiveModifier = first.defensiveModifier.andThen(second.defensiveModifier);
        modifier.maxHitModifier = first.maxHitModifier.andThen(second.maxHitModifier);
        modifier.damageModifier = first.damageModifier.andThen(second.damageModifier);
        return modifier;
    }
References aggressiveModifier, attackModifier, damageModifier, defensiveModifier, magicModifier, maxHitModifier, and rangedModifier.
Referenced by aggressive(), attack(), attackPercent(), defensive(), magic(), main(), maxHit(), and ranged().
magic() [1/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.magic (double percentage) protected
Definition at line 27 of file Modifier.java.
{
        magicModifier = link(magicModifier, percentage(percentage));
        return this;
    }
References link(), magicModifier, and percentage().
magic() [2/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.magic (int level) protected
Definition at line 59 of file Modifier.java.
{
        magicModifier = magicModifier.andThen(addition(level));
        return this;
    }
References addition(), and magicModifier.
main()
void com.runehive.game.world.entity.combat.attack.Modifier.main (String[] args) static
Definition at line 137 of file Modifier.java.
{
        Modifier godsword = attack(0.25);
        Modifier agsMaxHit = attack(0.10);
        Modifier chain = link(godsword, agsMaxHit);
        Modifier linked = link(attack(0.25), attack(0.10));
        double total;
        total = link(chain, linked).modifyAttack(10000) / 10000.0;
        System.out.println(total);
        total = link(chain, linked).modifyAttack(10000) / 10000.0;
        System.out.println(total);
    }
References attack(), link(), and modifyAttack().
maxHit() [1/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.maxHit (double percentage) protected
Definition at line 42 of file Modifier.java.
{
        maxHitModifier = link(maxHitModifier, percentage(percentage));
        return this;
    }
References link(), maxHitModifier, and percentage().
maxHit() [2/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.maxHit (int level) protected
Definition at line 74 of file Modifier.java.
{
        maxHitModifier = maxHitModifier.andThen(addition(level));
        return this;
    }
References addition(), and maxHitModifier.
modifyAggressive()
int com.runehive.game.world.entity.combat.attack.Modifier.modifyAggressive (int level)
Definition at line 105 of file Modifier.java.
{
        return aggressiveModifier.apply(level);
    }
References aggressiveModifier.
modifyAttack()
int com.runehive.game.world.entity.combat.attack.Modifier.modifyAttack (int level)
Definition at line 93 of file Modifier.java.
{
        return attackModifier.apply(level);
    }
References attackModifier.
Referenced by main().
modifyDamage()
int com.runehive.game.world.entity.combat.attack.Modifier.modifyDamage (int damage)
Definition at line 117 of file Modifier.java.
{
        return damageModifier.apply(damage);
    }
References damageModifier.
modifyDefensive()
int com.runehive.game.world.entity.combat.attack.Modifier.modifyDefensive (int level)
Definition at line 109 of file Modifier.java.
{
        return defensiveModifier.apply(level);
    }
References defensiveModifier.
modifyMagic()
int com.runehive.game.world.entity.combat.attack.Modifier.modifyMagic (int level)
Definition at line 101 of file Modifier.java.
{
        return magicModifier.apply(level);
    }
References magicModifier.
modifyMaxHit()
int com.runehive.game.world.entity.combat.attack.Modifier.modifyMaxHit (int max)
Definition at line 113 of file Modifier.java.
{
        return maxHitModifier.apply(max);
    }
References maxHitModifier.
modifyRanged()
int com.runehive.game.world.entity.combat.attack.Modifier.modifyRanged (int level)
Definition at line 97 of file Modifier.java.
{
        return rangedModifier.apply(level);
    }
References rangedModifier.
percentage()
Function< Integer, Integer > com.runehive.game.world.entity.combat.attack.Modifier.percentage (double percent) static private
Definition at line 129 of file Modifier.java.
{
        return modifier -> (int) (modifier * (1 + percent));
    }
Referenced by aggressive(), attackPercent(), defensive(), magic(), maxHit(), and ranged().
ranged() [1/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.ranged (double percentage) protected
Definition at line 22 of file Modifier.java.
{
        rangedModifier = link(rangedModifier, percentage(percentage));
        return this;
    }
References link(), percentage(), and rangedModifier.
ranged() [2/2]
final Modifier com.runehive.game.world.entity.combat.attack.Modifier.ranged (int level) protected
Definition at line 54 of file Modifier.java.
{
        rangedModifier = rangedModifier.andThen(addition(level));
        return this;
    }
References addition(), and rangedModifier.
Member Data Documentation
aggressiveModifier
Function<Integer, Integer> com.runehive.game.world.entity.combat.attack.Modifier.aggressiveModifier = Function.identity() private
Definition at line 9 of file Modifier.java.
Referenced by aggressive(), aggressive(), link(), and modifyAggressive().
attackModifier
Function<Integer, Integer> com.runehive.game.world.entity.combat.attack.Modifier.attackModifier = Function.identity() private
Definition at line 6 of file Modifier.java.
Referenced by attack(), attackPercent(), link(), and modifyAttack().
damageModifier
Function<Integer, Integer> com.runehive.game.world.entity.combat.attack.Modifier.damageModifier = Function.identity() private
Definition at line 13 of file Modifier.java.
Referenced by link(), and modifyDamage().
defensiveModifier
Function<Integer, Integer> com.runehive.game.world.entity.combat.attack.Modifier.defensiveModifier = Function.identity() private
Definition at line 10 of file Modifier.java.
Referenced by defensive(), defensive(), link(), and modifyDefensive().
magicModifier
Function<Integer, Integer> com.runehive.game.world.entity.combat.attack.Modifier.magicModifier = Function.identity() private
Definition at line 7 of file Modifier.java.
Referenced by link(), magic(), magic(), and modifyMagic().
maxHitModifier
Function<Integer, Integer> com.runehive.game.world.entity.combat.attack.Modifier.maxHitModifier = Function.identity() private
Definition at line 12 of file Modifier.java.
Referenced by link(), maxHit(), maxHit(), and modifyMaxHit().
rangedModifier
Function<Integer, Integer> com.runehive.game.world.entity.combat.attack.Modifier.rangedModifier = Function.identity() private
Definition at line 8 of file Modifier.java.
Referenced by link(), modifyRanged(), ranged(), and ranged().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/Modifier.java