RuneHive-Game: com.runehive.game.world.items.ItemDefinition Class Reference
com.runehive.game.world.items.ItemDefinition Class Reference
Represents all of an in-game Item's attributes.
Public Member Functions
String getDestroyMessage ()
Gets the item destroy message.
int getId ()
Gets the item id.
String getName ()
Gets the item name.
boolean isNoted ()
Gets the item note state.
ItemDefinition (int id, String name)
Static Public Member Functions
static ItemDefinition[] create (String path)
static GsonParser createParser ()
static void dump (ItemDefinition[] definitions, String path)
static void dump (String path)
static ItemDefinition[] fromClientDump (String path)
static ItemDefinition get (int id)
Gets an item definition.
static void merge (String clientDumpFilePath, String wikiDumpPath, String dumpPath)
Static Public Attributes
static final ItemDefinition DEFAULT = new ItemDefinition(1, "null")
static ItemDefinition[] DEFINITIONS
An array of item definitions.
Private Attributes
int attack_anim
Map< FightType, Integer > attack_animations
int base_value
int block_animation
int[] bonuses
boolean destroyable
String destroyMessage
EquipmentType equipmentType
int highAlch
final int id
int lowAlch
final String name
int notedId
RangedWeaponDefinition rangedDefinition
int[] requirements
int run_animation
boolean stackable
int stand_animation
int street_value
boolean tradeable
boolean twoHanded
int unnotedId
int walk_animation
WeaponInterface weaponInterface
double weight
Static Private Attributes
static final Map< FightType, Integer > EMPTY = new HashMap<>()
Detailed Description
Represents all of an in-game Item's attributes.
Author
Michael | Chex
Daniel | Obey
Definition at line 28 of file ItemDefinition.java.
Constructor & Destructor Documentation
ItemDefinition()
com.runehive.game.world.items.ItemDefinition.ItemDefinition (int id, String name)
Definition at line 63 of file ItemDefinition.java.
{
        this.id = id;
        this.name = name;
        this.destroyMessage = null;
        this.destroyable = false;
        this.stackable = false;
        this.tradeable = true;
        this.twoHanded = false;
        this.unnotedId = id;
        this.notedId = id;
        this.street_value = 0;
        this.base_value = 0;
        this.highAlch = 0;
        this.lowAlch = 0;
        this.weight = 0;
        this.stand_animation = MobAnimation.PLAYER_STAND;
        this.walk_animation = MobAnimation.PLAYER_WALK;
        this.run_animation = MobAnimation.PLAYER_RUN;
        this.attack_animations = EMPTY;
        this.block_animation = -1;
        this.equipmentType = EquipmentType.NOT_WIELDABLE;
        this.weaponInterface = null;
        this.rangedDefinition = null;
        this.requirements = EMPTY_REQUIREMENTS;
        this.bonuses = EMPTY_BONUSES;
    }
References EMPTY, id, name, com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE, com.runehive.game.world.entity.mob.MobAnimation.PLAYER_RUN, com.runehive.game.world.entity.mob.MobAnimation.PLAYER_STAND, and com.runehive.game.world.entity.mob.MobAnimation.PLAYER_WALK.
Referenced by create(), createParser(), dump(), dump(), fromClientDump(), get(), and merge().
Member Function Documentation
create()
ItemDefinition[] com.runehive.game.world.items.ItemDefinition.create (String path) static
Definition at line 226 of file ItemDefinition.java.
{
        ItemDefinition[] definitions = new ItemDefinition[Config.ITEM_DEFINITION_LIMIT];
        new GsonParser(path) {
            @Override
            public void initialize(int size) {
                createParser().run();
            }
            @Override
            protected void parse(JsonObject data) {
                int id = data.get("id").getAsInt();
                String name = data.get("name").getAsString();
                ItemDefinition definition = definitions[id] = new ItemDefinition(id, name);
                ItemDefinition old = DEFINITIONS[id];
                if (data.has("destroyable")) {
                    definition.destroyable = data.get("destroyable").getAsBoolean();
                }
                if (data.has("destroy-message")) {
                    definition.destroyable = true;
                    definition.destroyMessage = data.get("destroy-message").getAsString();
                }
                if (data.has("stackable")) {
                    definition.stackable = data.get("stackable").getAsBoolean();
                }
                if (data.has("tradeable")) {
                    definition.tradeable = data.get("tradeable").getAsBoolean();
                }
                if (data.has("two-handed")) {
                    definition.twoHanded = data.get("two-handed").getAsBoolean();
                }
                if (data.has("noted-id")) {
                    definition.notedId = data.get("noted-id").getAsInt();
                }
                if (data.has("unnoted-id")) {
                    definition.unnotedId = data.get("unnoted-id").getAsInt();
                }
                if (data.has("street-value")) {
                    definition.street_value = data.get("street-value").getAsInt();
                } else if (old != null) {
                    definition.street_value = old.street_value;
                }
                if (data.has("base-value")) {
                    definition.base_value = data.get("base-value").getAsInt();
                }
                if (data.has("high-alch")) {
                    definition.highAlch = data.get("high-alch").getAsInt();
                }
                if (data.has("low-alch")) {
                    definition.lowAlch = data.get("low-alch").getAsInt();
                }
                if (data.has("weight")) {
                    definition.weight = data.get("weight").getAsDouble();
                }
                if (old != null && old.equipmentType != EquipmentType.NOT_WIELDABLE) {
                    definition.equipmentType = old.equipmentType;
                } else if (data.has("equipment-slot")) {
                    definition.equipmentType = EquipmentType.valueOf(data.get("equipment-slot").getAsString());
                }
                for (int index = 0; index < BONUS_CONFIG_FIELD_NAMES.length; index++) {
                    String bonusName = BONUS_CONFIG_FIELD_NAMES[index];
                    if (data.has(bonusName)) {
                        if (definition.bonuses == EMPTY_BONUSES) {
                            definition.bonuses = new int[EMPTY_BONUSES.length];
                        }
                        definition.bonuses[index] = data.get(bonusName).getAsInt();
                    }
                }
                if (old != null) {
                    definition.weaponInterface = old.weaponInterface;
                    definition.requirements = old.requirements;
                    definition.rangedDefinition = old.rangedDefinition;
                    definition.stand_animation = old.stand_animation;
                    definition.walk_animation = old.walk_animation;
                    definition.run_animation = old.run_animation;
                    definition.attack_animations = old.attack_animations;
                    definition.block_animation = old.block_animation;
                }
            }
        }.run();
        return definitions;
    }
References attack_animations, block_animation, bonuses, createParser(), DEFINITIONS, equipmentType, id, com.runehive.Config.ITEM_DEFINITION_LIMIT, ItemDefinition(), name, com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE, rangedDefinition, requirements, com.runehive.util.parser.GenericParser.run(), run_animation, stand_animation, street_value, walk_animation, and weaponInterface.
Referenced by com.runehive.util.parser.old.EquipmentDefinitionParser.main().
createParser()
GsonParser com.runehive.game.world.items.ItemDefinition.createParser () static
Definition at line 90 of file ItemDefinition.java.
{
        return new GsonParser("def/item/item_definitions", false) {
            @Override
            public void initialize(int size) {
                DEFINITIONS = new ItemDefinition[Config.ITEM_DEFINITION_LIMIT];
            }
            @Override
            protected void parse(JsonObject data) {
                int id = data.get("id").getAsInt();
                String name = data.get("name").getAsString();
                ItemDefinition definition = new ItemDefinition(id, name);
                if (data.has("destroyable")) {
                    definition.destroyable = data.get("destroyable").getAsBoolean();
                }
                if (data.has("destroy-message")) {
                    definition.destroyable = true;
                    definition.destroyMessage = data.get("destroy-message").getAsString();
                }
                if (data.has("stackable")) {
                    definition.stackable = data.get("stackable").getAsBoolean();
                }
                if (data.has("tradeable")) {
                    definition.tradeable = data.get("tradeable").getAsBoolean();
                }
                if (data.has("two-handed")) {
                    definition.twoHanded = data.get("two-handed").getAsBoolean();
                }
                if (data.has("noted-id")) {
                    definition.notedId = data.get("noted-id").getAsInt();
                }
                if (data.has("unnoted-id")) {
                    definition.unnotedId = data.get("unnoted-id").getAsInt();
                }
                if (data.has("street-value")) {
                    definition.street_value = data.get("street-value").getAsInt();
                }
                if (data.has("base-value")) {
                    definition.base_value = data.get("base-value").getAsInt();
                }
                if (data.has("high-alch")) {
                    definition.highAlch = data.get("high-alch").getAsInt();
                }
                if (data.has("low-alch")) {
                    definition.lowAlch = data.get("low-alch").getAsInt();
                }
                if (data.has("weight")) {
                    definition.weight = data.get("weight").getAsDouble();
                }
                if (data.has("equipment-slot")) {
                    definition.equipmentType = EquipmentType.valueOf(data.get("equipment-slot").getAsString());
                }
                if (data.has("weapon-interface")) {
                    definition.weaponInterface = WeaponInterface.valueOf(data.get("weapon-interface").getAsString());
                }
                for (int index = 0; index < SKILL_REQUIREMENT_CONFIG_FIELD_NAMES.length; index++) {
                    String skillRequirement = SKILL_REQUIREMENT_CONFIG_FIELD_NAMES[index];
                    if (data.has(skillRequirement)) {
                        if (definition.requirements == EMPTY_REQUIREMENTS) {
                            definition.requirements = new int[EMPTY_REQUIREMENTS.length];
                        }
                        definition.requirements[index] = data.get(skillRequirement).getAsInt();
                    }
                }
                for (int index = 0; index < BONUS_CONFIG_FIELD_NAMES.length; index++) {
                    String bonusName = BONUS_CONFIG_FIELD_NAMES[index];
                    if (data.has(bonusName)) {
                        if (definition.bonuses == EMPTY_BONUSES) {
                            definition.bonuses = new int[EMPTY_BONUSES.length];
                        }
                        definition.bonuses[index] = data.get(bonusName).getAsInt();
                    }
                }
                if (data.has("ranged-type") && data.has("allowed")) {
                    RangedWeaponType type = builder.fromJson(data.get("ranged-type"), RangedWeaponType.class);
                    RangedAmmunition[] allowed = builder.fromJson(data.get("allowed"), RangedAmmunition[].class);
                    definition.rangedDefinition = new RangedWeaponDefinition(type, allowed);
                }
                if (data.has("stand-animation")) {
                    definition.stand_animation = data.get("stand-animation").getAsInt();
                }
                if (data.has("walk-animation")) {
                    definition.walk_animation = data.get("walk-animation").getAsInt();
                }
                if (data.has("run-animation")) {
                    definition.run_animation = data.get("run-animation").getAsInt();
                }
                if (data.has("attack-animations")) {
                    JsonObject object = (JsonObject) data.get("attack-animations");
                    definition.attack_animations = new HashMap<>(object.entrySet().size());
                    for (Map.Entry<String, JsonElement> entry : object.entrySet()) {
                        FightType fightType = FightType.valueOf(entry.getKey());
                        int animation = entry.getValue().getAsInt();
                        definition.attack_animations.put(fightType, animation);
                    }
                }
                if (data.has("block-animation")) {
                    definition.block_animation = data.get("block-animation").getAsInt();
                }
                DEFINITIONS[id] = definition;
            }
            @Override
            protected void onEnd() {
                ItemDefLoader.load();
            }
        };
    }
References attack_animations, bonuses, DEFINITIONS, id, com.runehive.Config.ITEM_DEFINITION_LIMIT, ItemDefinition(), name, and requirements.
Referenced by create(), com.runehive.util.tools.wiki.impl.BonusParser.finish(), com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), com.runehive.util.parser.old.EquipmentDefinitionParser.initialize(), com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.main(), com.runehive.util.tools.ItemDBdefUpdate.main(), and com.runehive.RuneHive.processSequentialStartupTasks().
dump() [1/2]
void com.runehive.game.world.items.ItemDefinition.dump (ItemDefinition[] definitions, String path) static
Definition at line 432 of file ItemDefinition.java.
{
        JsonSaver saver = new JsonSaver();
        for (ItemDefinition definition : definitions) {
            if (definition == null) continue;
            if (definition.name.equals("null")) continue;
            saver.current().addProperty("id", definition.id);
            saver.current().addProperty("name", definition.name);
            if (definition.destroyMessage != null) {
                saver.current().addProperty("destroy-message", definition.destroyMessage);
            } else if (definition.destroyable) {
                saver.current().addProperty("destroyable", true);
            }
            if (definition.stackable) {
                saver.current().addProperty("stackable", true);
            }
            if (!definition.tradeable) {
                saver.current().addProperty("tradeable", false);
            }
            if (definition.twoHanded) {
                saver.current().addProperty("two-handed", true);
            }
            if (definition.unnotedId != definition.id) {
                saver.current().addProperty("unnoted-id", definition.unnotedId);
            }
            if (definition.notedId != definition.id) {
                saver.current().addProperty("noted-id", definition.notedId);
            }
            if (definition.lowAlch > 1) {
                saver.current().addProperty("low-alch", definition.lowAlch);
            }
            if (definition.highAlch > 1) {
                saver.current().addProperty("high-alch", definition.highAlch);
            }
            if (definition.base_value > 1) {
                saver.current().addProperty("base-value", definition.base_value);
            }
            if (definition.street_value > 1) {
                saver.current().addProperty("street-value", definition.street_value);
            }
            if (definition.weight != 0) {
                saver.current().addProperty("weight", definition.weight);
            }
            if (definition.stand_animation != MobAnimation.PLAYER_STAND) {
                saver.current().addProperty("stand-animation", definition.stand_animation);
            }
            if (definition.walk_animation != MobAnimation.PLAYER_WALK) {
                saver.current().addProperty("walk-animation", definition.walk_animation);
            }
            if (definition.run_animation != MobAnimation.PLAYER_RUN) {
                saver.current().addProperty("run-animation", definition.run_animation);
            }
            if (definition.attack_animations != EMPTY) {
                saver.current().add("attack-animations", saver.serializer().toJsonTree(definition.attack_animations));
            }
            if (definition.block_animation != -1) {
                saver.current().addProperty("block-animation", definition.block_animation);
            }
            if (definition.equipmentType != EquipmentType.NOT_WIELDABLE) {
                saver.current().addProperty("equipment-slot", definition.equipmentType.name());
            }
            if (definition.weaponInterface != null && definition.weaponInterface != WeaponInterface.UNARMED) {
                saver.current().addProperty("weapon-interface", definition.weaponInterface.name());
            }
            for (int index = 0; index < SKILL_REQUIREMENT_CONFIG_FIELD_NAMES.length; index++) {
                if (definition.requirements[index] > 0)
                    saver.current().addProperty(SKILL_REQUIREMENT_CONFIG_FIELD_NAMES[index], definition.requirements[index]);
            }
            for (int index = 0; index < BONUS_CONFIG_FIELD_NAMES.length; index++) {
                if (definition.bonuses[index] != 0)
                    saver.current().addProperty(BONUS_CONFIG_FIELD_NAMES[index], definition.bonuses[index]);
            }
            if (definition.rangedDefinition != null) {
                saver.current().addProperty("ranged-type", definition.rangedDefinition.getType().name());
                saver.current().add("allowed", saver.serializer().toJsonTree(definition.rangedDefinition.getAllowed()));
            }
            saver.split();
        }
        saver.publish("./data/" + path + ".json");
    }
References com.runehive.util.parser.JsonSaver.current(), EMPTY, ItemDefinition(), com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE, com.runehive.game.world.entity.mob.MobAnimation.PLAYER_RUN, com.runehive.game.world.entity.mob.MobAnimation.PLAYER_STAND, com.runehive.game.world.entity.mob.MobAnimation.PLAYER_WALK, com.runehive.util.parser.JsonSaver.publish(), com.runehive.util.parser.JsonSaver.serializer, com.runehive.util.parser.JsonSaver.split(), and com.runehive.game.world.entity.combat.weapon.WeaponInterface.UNARMED.
Referenced by com.runehive.util.tools.wiki.impl.BonusParser.finish(), com.runehive.util.parser.old.EquipmentDefinitionParser.main(), merge(), and com.runehive.util.parser.old.EquipmentDefinitionParser.onEnd().
dump() [2/2]
void com.runehive.game.world.items.ItemDefinition.dump (String path) static
Definition at line 537 of file ItemDefinition.java.
{
        JsonSaver saver = new JsonSaver();
        for (ItemDefinition definition : DEFINITIONS) {
            if (definition == null) continue;
            if (definition.name.equals("null")) continue;
            saver.current().addProperty("id", definition.id);
            saver.current().addProperty("name", definition.name);
            if (definition.destroyMessage != null) {
                saver.current().addProperty("destroy-message", definition.destroyMessage);
            } else if (definition.destroyable) {
                saver.current().addProperty("destroyable", true);
            }
            if (definition.stackable) {
                saver.current().addProperty("stackable", true);
            }
            if (!definition.tradeable) {
                saver.current().addProperty("tradeable", false);
            }
            if (definition.twoHanded) {
                saver.current().addProperty("two-handed", true);
            }
            if (definition.unnotedId != definition.id) {
                saver.current().addProperty("unnoted-id", definition.unnotedId);
            }
            if (definition.notedId != definition.id) {
                saver.current().addProperty("noted-id", definition.notedId);
            }
            if (definition.lowAlch > 1) {
                saver.current().addProperty("low-alch", definition.lowAlch);
            }
            if (definition.highAlch > 1) {
                saver.current().addProperty("high-alch", definition.highAlch);
            }
            if (definition.base_value > 1) {
                saver.current().addProperty("base-value", definition.base_value);
            }
            if (definition.street_value > 1) {
                saver.current().addProperty("street-value", definition.street_value);
            }
            if (definition.weight != 0) {
                saver.current().addProperty("weight", definition.weight);
            }
            if (definition.stand_animation != MobAnimation.PLAYER_STAND) {
                saver.current().addProperty("stand-animation", definition.stand_animation);
            }
            if (definition.walk_animation != MobAnimation.PLAYER_WALK) {
                saver.current().addProperty("walk-animation", definition.walk_animation);
            }
            if (definition.run_animation != MobAnimation.PLAYER_RUN) {
                saver.current().addProperty("run-animation", definition.run_animation);
            }
            if (definition.attack_animations != EMPTY) {
                saver.current().add("attack-animations", saver.serializer().toJsonTree(definition.attack_animations));
            }
            if (definition.block_animation != -1) {
                saver.current().addProperty("block-animation", definition.block_animation);
            }
            if (definition.equipmentType != EquipmentType.NOT_WIELDABLE) {
                saver.current().addProperty("equipment-slot", definition.equipmentType.name());
            }
            if (definition.weaponInterface != null && definition.weaponInterface != WeaponInterface.UNARMED) {
                saver.current().addProperty("weapon-interface", definition.weaponInterface.name());
            }
            for (int index = 0; index < SKILL_REQUIREMENT_CONFIG_FIELD_NAMES.length; index++) {
                if (definition.requirements[index] > 0)
                    saver.current().addProperty(SKILL_REQUIREMENT_CONFIG_FIELD_NAMES[index], definition.requirements[index]);
            }
            for (int index = 0; index < BONUS_CONFIG_FIELD_NAMES.length; index++) {
                if (definition.bonuses[index] != 0)
                    saver.current().addProperty(BONUS_CONFIG_FIELD_NAMES[index], definition.bonuses[index]);
            }
            if (definition.rangedDefinition != null) {
                saver.current().addProperty("ranged-type", definition.rangedDefinition.getType().name());
                saver.current().add("allowed", saver.serializer().toJsonTree(definition.rangedDefinition.getAllowed()));
            }
            saver.split();
        }
        saver.publish("./data/" + path + ".json");
    }
References com.runehive.util.parser.JsonSaver.current(), DEFINITIONS, EMPTY, ItemDefinition(), com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE, com.runehive.game.world.entity.mob.MobAnimation.PLAYER_RUN, com.runehive.game.world.entity.mob.MobAnimation.PLAYER_STAND, com.runehive.game.world.entity.mob.MobAnimation.PLAYER_WALK, com.runehive.util.parser.JsonSaver.publish(), com.runehive.util.parser.JsonSaver.serializer, com.runehive.util.parser.JsonSaver.split(), and com.runehive.game.world.entity.combat.weapon.WeaponInterface.UNARMED.
fromClientDump()
ItemDefinition[] com.runehive.game.world.items.ItemDefinition.fromClientDump (String path) static
Definition at line 327 of file ItemDefinition.java.
{
        ItemDefinition[] definitions = new ItemDefinition[Config.ITEM_DEFINITION_LIMIT];
        new GsonParser(path) {
            @Override
            protected void parse(JsonObject data) {
                int id = data.get("id").getAsInt();
                String name = data.get("name").getAsString();
                ItemDefinition definition = definitions[id] = new ItemDefinition(id, name);
                if (data.has("stackable")) {
                    definition.stackable = data.get("stackable").getAsBoolean();
                }
                if (data.has("destroyable")) {
                    definition.destroyable = data.get("destroyable").getAsBoolean();
                }
                if (data.has("noted-id")) {
                    definition.notedId = data.get("noted-id").getAsInt();
                }
                if (data.has("unnoted-id")) {
                    definition.unnotedId = data.get("unnoted-id").getAsInt();
                }
                if (data.has("base-value")) {
                    definition.base_value = data.get("base-value").getAsInt();
                    definition.lowAlch = (int) (definition.base_value * 0.40);
                    definition.highAlch = (int) (definition.base_value * 0.60);
                }
                if (data.has("equipment-type")) {
                    definition.equipmentType = EquipmentType.valueOf(data.get("equipment-type").getAsString());
                }
            }
        }.run();
        return definitions;
    }
References base_value, id, com.runehive.Config.ITEM_DEFINITION_LIMIT, ItemDefinition(), and name.
Referenced by merge().
get()
ItemDefinition com.runehive.game.world.items.ItemDefinition.get (int id) static
Gets an item definition.
Parameters
id The definition's item id.
Returns
The item definition for the item id, or null if the item id is out of bounds.
Definition at line 649 of file ItemDefinition.java.
{
        if (id < 0 || id >= DEFINITIONS.length) {
            return DEFAULT;
        }
        if (DEFINITIONS[id] == null) {
            return DEFINITIONS[id] = new ItemDefinition(id, "null");
        }
        return DEFINITIONS[id];
    }
References DEFAULT, DEFINITIONS, id, and ItemDefinition().
Referenced by com.runehive.content.tradingpost.TradingPost.addToItemHistory(), com.runehive.content.RoyaltyProgram.append(), com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.tradingpost.TradingPost.buyingDialogueOptions(), com.runehive.content.skill.impl.DestructionSkillAction.canRun(), com.runehive.content.skill.impl.hunter.net.Netting.canSchedule(), com.runehive.content.bags.ItemBag.check(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.content.skill.impl.magic.spell.SpellCasting.enchant(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.game.world.items.Item.getDefinition(), com.runehive.content.tradingpost.TradingPost.getItemArrayFromActiveListings(), com.runehive.content.tradingpost.TradingPost.getItemArrayFromItemHistory(), com.runehive.content.tradingpost.TradingPost.getSearchResults(), com.runehive.content.lms.LMSGame.giveChestItems(), com.runehive.content.tradingpost.TradingPost.handleBuyingButton(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.skill.impl.fishing.Fishing.hasFishingItems(), com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), com.runehive.content.bags.impl.CoalBag.isAllowed(), com.runehive.content.bags.impl.GemBag.isAllowed(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.collectionlog.CollectionLog.logItem(), com.runehive.util.tools.ItemDBdefUpdate.main(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.util.parser.impl.NpcDropParser.parse(), com.runehive.util.parser.old.EquipmentDefinitionParser.parse(), com.runehive.content.tradingpost.TradingPost.purchase(), com.runehive.content.clanchannel.content.ClanShowcase.remove(), com.runehive.content.lms.LMSGame.resupplyKiller(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.content.DropDisplay.search(), com.runehive.content.dialogue.ChatBoxItemDialogue.sendInterface(), com.runehive.content.tradingpost.TradingPost.sendItemHistoryData(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), com.runehive.content.store.currency.impl.ItemCurrency.toString(), com.runehive.content.tradingpost.TradingPost.updateBuyingPageWidgets(), and com.runehive.game.world.items.containers.bank.Bank.withdraw().
getDestroyMessage()
String com.runehive.game.world.items.ItemDefinition.getDestroyMessage ()
Gets the item destroy message.
Returns
The item destroy message.
Definition at line 685 of file ItemDefinition.java.
{
        return destroyMessage;
    }
References destroyMessage.
Referenced by com.runehive.game.world.items.Item.getDestroyMessage().
getId()
int com.runehive.game.world.items.ItemDefinition.getId ()
Gets the item id.
Returns
The item id.
Definition at line 667 of file ItemDefinition.java.
                       {
        return id;
    }
References id.
Referenced by com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), com.runehive.util.tools.ItemDBdefUpdate.main(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.search(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.searchItem().
getName()
String com.runehive.game.world.items.ItemDefinition.getName ()
Gets the item name.
Returns
The item name.
Definition at line 676 of file ItemDefinition.java.
{
        return name;
    }
References name.
Referenced by com.runehive.content.tradingpost.TradingPost.addToItemHistory(), com.runehive.content.RoyaltyProgram.append(), com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.tradingpost.TradingPost.buyingDialogueOptions(), com.runehive.content.skill.impl.DestructionSkillAction.canRun(), com.runehive.content.skill.impl.hunter.net.Netting.canSchedule(), com.runehive.content.bags.ItemBag.check(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.skill.impl.magic.spell.SpellCasting.enchant(), com.runehive.util.tools.wiki.impl.BonusParser.finish(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), com.runehive.game.world.items.Item.getName(), com.runehive.content.tradingpost.TradingPost.getSearchResults(), com.runehive.content.lms.LMSGame.giveChestItems(), com.runehive.content.tradingpost.TradingPost.handleBuyingButton(), com.runehive.content.skill.impl.fishing.Fishing.hasFishingItems(), com.runehive.content.bags.impl.CoalBag.isAllowed(), com.runehive.content.bags.impl.GemBag.isAllowed(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.collectionlog.CollectionLog.logItem(), com.runehive.util.tools.ItemDBdefUpdate.main(), com.runehive.util.parser.old.EquipmentDefinitionParser.parse(), com.runehive.content.tradingpost.TradingPost.purchase(), com.runehive.content.clanchannel.content.ClanShowcase.remove(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.content.DropDisplay.search(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.search(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.searchItem(), com.runehive.content.tradingpost.TradingPost.selectItemToList(), com.runehive.content.dialogue.ChatBoxItemDialogue.sendInterface(), com.runehive.content.tradingpost.TradingPost.sendItemHistoryData(), com.runehive.content.skill.impl.crafting.impl.Stringing.string(), com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), com.runehive.content.store.currency.impl.ItemCurrency.toString(), and com.runehive.content.tradingpost.TradingPost.updateBuyingPageWidgets().
isNoted()
boolean com.runehive.game.world.items.ItemDefinition.isNoted ()
Gets the item note state.
Returns
True if the item is noted;
Definition at line 694 of file ItemDefinition.java.
{
        return unnotedId != id;
    }
References id, and unnotedId.
Referenced by com.runehive.content.tradingpost.TradingPost.getItemArrayFromActiveListings(), com.runehive.content.tradingpost.TradingPost.getItemArrayFromItemHistory(), com.runehive.game.world.items.Item.isNoted(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.searchItem().
merge()
void com.runehive.game.world.items.ItemDefinition.merge (String clientDumpFilePath, String wikiDumpPath, String dumpPath) static
Definition at line 364 of file ItemDefinition.java.
{
        new GsonParser(wikiDumpPath) {
            LinkedListMultimap<String, JsonObject> multimap = LinkedListMultimap.create();
            @Override
            protected void parse(JsonObject data) {
                String name = data.get("name").getAsString();
                if (name.isEmpty())
                    return;
                multimap.put(name, data);
            }
            @Override
            protected void onEnd() {
                ItemDefinition[] definitions = fromClientDump(clientDumpFilePath);
                for (ItemDefinition definition : definitions) {
                    if (definition == null || definition.name.equals("null") || definition.name.isEmpty())
                        continue;
                    if (!multimap.containsKey(definition.name))
                        continue;
                    List<JsonObject> value = multimap.get(definition.name);
                    JsonObject object = value.get(value.size() - 1);
                    if (value.size() > 1)
                        multimap.remove(definition.name, object);
                    if (object.has("destroy-message"))
                        definition.destroyMessage = object.get("destroy-message").getAsString();
                    if (object.has("tradable"))
                        definition.tradeable = object.get("tradable").getAsBoolean();
                    if (object.has("weight"))
                        definition.weight = object.get("weight").getAsDouble();
                    if (definition.isNoted()) {
                        continue;
                    }
                    if (object.has("two-handed"))
                        definition.twoHanded = object.get("two-handed").getAsBoolean();
                    if (object.has("equipment-type"))
                        definition.equipmentType = EquipmentType.valueOf(object.get("equipment-type").getAsString());
                    for (int index = 0; index < BONUS_CONFIG_FIELD_NAMES.length; index++) {
                        String bonusName = BONUS_CONFIG_FIELD_NAMES[index];
                        if (object.has(bonusName)) {
                            if (definition.bonuses == EMPTY_BONUSES) {
                                definition.bonuses = new int[EMPTY_BONUSES.length];
                            }
                            definition.bonuses[index] = object.get(bonusName).getAsInt();
                        }
                    }
                }
                DEFINITIONS = definitions;
                dump(dumpPath);
            }
        }.run();
    }
References DEFINITIONS, dump(), fromClientDump(), ItemDefinition(), and name.
Member Data Documentation
attack_anim
int com.runehive.game.world.items.ItemDefinition.attack_anim private
Definition at line 45 of file ItemDefinition.java.
attack_animations
Map<FightType, Integer> com.runehive.game.world.items.ItemDefinition.attack_animations private
Definition at line 48 of file ItemDefinition.java.
Referenced by create(), and createParser().
base_value
int com.runehive.game.world.items.ItemDefinition.base_value private
Definition at line 53 of file ItemDefinition.java.
Referenced by fromClientDump().
block_animation
int com.runehive.game.world.items.ItemDefinition.block_animation private
Definition at line 49 of file ItemDefinition.java.
Referenced by create().
bonuses
int [] com.runehive.game.world.items.ItemDefinition.bonuses private
Definition at line 61 of file ItemDefinition.java.
Referenced by create(), and createParser().
DEFAULT
final ItemDefinition com.runehive.game.world.items.ItemDefinition.DEFAULT = new ItemDefinition(1, "null") static
Definition at line 35 of file ItemDefinition.java.
Referenced by get().
DEFINITIONS
ItemDefinition [] com.runehive.game.world.items.ItemDefinition.DEFINITIONS static
An array of item definitions.
Definition at line 33 of file ItemDefinition.java.
Referenced by create(), createParser(), dump(), com.runehive.util.tools.wiki.impl.BonusParser.finish(), com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), get(), com.runehive.util.tools.ItemDBdefUpdate.main(), merge(), com.runehive.util.parser.old.ItemDefinitionParser.parse(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.search(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.searchItem(), and com.runehive.content.tradingpost.TradingPost.testData().
destroyable
boolean com.runehive.game.world.items.ItemDefinition.destroyable private
Definition at line 40 of file ItemDefinition.java.
destroyMessage
String com.runehive.game.world.items.ItemDefinition.destroyMessage private
Definition at line 39 of file ItemDefinition.java.
Referenced by getDestroyMessage().
EMPTY
final Map<FightType, Integer> com.runehive.game.world.items.ItemDefinition.EMPTY = new HashMap<>() static private
Definition at line 34 of file ItemDefinition.java.
Referenced by dump(), dump(), and ItemDefinition().
equipmentType
EquipmentType com.runehive.game.world.items.ItemDefinition.equipmentType private
Definition at line 57 of file ItemDefinition.java.
Referenced by create().
highAlch
int com.runehive.game.world.items.ItemDefinition.highAlch private
Definition at line 54 of file ItemDefinition.java.
id
final int com.runehive.game.world.items.ItemDefinition.id private
Definition at line 37 of file ItemDefinition.java.
Referenced by create(), createParser(), fromClientDump(), get(), getId(), isNoted(), and ItemDefinition().
lowAlch
int com.runehive.game.world.items.ItemDefinition.lowAlch private
Definition at line 55 of file ItemDefinition.java.
name
final String com.runehive.game.world.items.ItemDefinition.name private
Definition at line 38 of file ItemDefinition.java.
Referenced by create(), createParser(), fromClientDump(), getName(), ItemDefinition(), and merge().
notedId
int com.runehive.game.world.items.ItemDefinition.notedId private
Definition at line 51 of file ItemDefinition.java.
rangedDefinition
RangedWeaponDefinition com.runehive.game.world.items.ItemDefinition.rangedDefinition private
Definition at line 59 of file ItemDefinition.java.
Referenced by create().
requirements
int [] com.runehive.game.world.items.ItemDefinition.requirements private
Definition at line 60 of file ItemDefinition.java.
Referenced by create(), and createParser().
run_animation
int com.runehive.game.world.items.ItemDefinition.run_animation private
Definition at line 47 of file ItemDefinition.java.
Referenced by create().
stackable
boolean com.runehive.game.world.items.ItemDefinition.stackable private
Definition at line 41 of file ItemDefinition.java.
stand_animation
int com.runehive.game.world.items.ItemDefinition.stand_animation private
Definition at line 44 of file ItemDefinition.java.
Referenced by create().
street_value
int com.runehive.game.world.items.ItemDefinition.street_value private
Definition at line 52 of file ItemDefinition.java.
Referenced by create().
tradeable
boolean com.runehive.game.world.items.ItemDefinition.tradeable private
Definition at line 43 of file ItemDefinition.java.
twoHanded
boolean com.runehive.game.world.items.ItemDefinition.twoHanded private
Definition at line 42 of file ItemDefinition.java.
unnotedId
int com.runehive.game.world.items.ItemDefinition.unnotedId private
Definition at line 50 of file ItemDefinition.java.
Referenced by isNoted().
walk_animation
int com.runehive.game.world.items.ItemDefinition.walk_animation private
Definition at line 46 of file ItemDefinition.java.
Referenced by create().
weaponInterface
WeaponInterface com.runehive.game.world.items.ItemDefinition.weaponInterface private
Definition at line 58 of file ItemDefinition.java.
Referenced by create().
weight
double com.runehive.game.world.items.ItemDefinition.weight private
Definition at line 56 of file ItemDefinition.java.
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/ItemDefinition.java