RuneHive-Game: com.runehive.game.ProjectileTest Class Reference
com.runehive.game.ProjectileTest Class Reference
Public Member Functions
int getAngle ()
int getCreatorSize ()
int getDelay ()
int getDuration (int distance)
int getEndHeight ()
int getHitDelay (int distance)
int getLockon ()
Position getOffset ()
int getProjectileId ()
int getRadius ()
int getSlope ()
int getSpeed ()
Position getStart ()
int getStartDistanceOffset ()
int getStartHeight ()
int getStepMultiplier ()
Position getTarget ()
ProjectileTest (Mob source, Mob victim, int projectileId, int delay, int speed, int startHeight, int endHeight, int curve, int creatorSize, int stepMultiplier)
ProjectileTest (Position source, Position delta, int slope, int speed, int projectileId, int startHeight, int endHeight, int lockon, int delay, int creatorSize, int startDistanceOffset)
ProjectileTest (Position start, Position end, int lockon, int projectileId, int speed, int delay, int startHeight, int endHeight, int curve)
ProjectileTest (Position start, Position end, int lockon, int projectileId, int speed, int delay, int startHeight, int endHeight, int curve, int creatorSize, int startDistanceOffset, int stepMultiplier)
Package Attributes
Position offset
Position start
Position target
Private Attributes
final int angle
final int creatorSize
final int delay
final int endHeight
final int lockon
final int projectileId
final int radius
final int slope
final int speed
final int startDistanceOffset
final int startHeight
final int stepMultiplier
Detailed Description
Definition at line 6 of file ProjectileTest.java.
Constructor & Destructor Documentation
ProjectileTest() [1/4]
com.runehive.game.ProjectileTest.ProjectileTest (Position start, Position end, int lockon, int projectileId, int speed, int delay, int startHeight, int endHeight, int curve, int creatorSize, int startDistanceOffset, int stepMultiplier)
Definition at line 11 of file ProjectileTest.java.
{
        this.start = start;
        this.target = end;
        this.offset = new Position((end.getX() - start.getX()),
                (end.getY() - start.getY()));
        this.creatorSize = creatorSize;
        this.startDistanceOffset = startDistanceOffset;
        this.lockon = lockon;
        this.projectileId = projectileId;
        this.delay = delay;
        this.speed = speed;
        this.startHeight = startHeight;
        this.endHeight = endHeight;
        this.slope = curve;
        this.angle = getAngle();
        this.radius = getRadius();
        this.stepMultiplier = stepMultiplier;
    }
References creatorSize, delay, endHeight, getAngle(), getRadius(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), lockon, projectileId, speed, start, startDistanceOffset, startHeight, and stepMultiplier.
ProjectileTest() [2/4]
com.runehive.game.ProjectileTest.ProjectileTest (Mob source, Mob victim, int projectileId, int delay, int speed, int startHeight, int endHeight, int curve, int creatorSize, int stepMultiplier)
Definition at line 32 of file ProjectileTest.java.
{
        this(source.getPosition(), victim.getPosition(),
                (victim.isPlayer() ? -victim.getIndex() - 1
                        : victim.getIndex() + 1), projectileId, speed, delay,
                startHeight, endHeight, curve, creatorSize, 64, stepMultiplier);
    }
References creatorSize, delay, endHeight, com.runehive.game.world.entity.Entity.getIndex(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.Mob.isPlayer(), projectileId, speed, startHeight, and stepMultiplier.
ProjectileTest() [3/4]
com.runehive.game.ProjectileTest.ProjectileTest (Position start, Position end, int lockon, int projectileId, int speed, int delay, int startHeight, int endHeight, int curve)
Definition at line 40 of file ProjectileTest.java.
{
        this(start, end, lockon, projectileId, speed, delay, startHeight, endHeight, curve, 1, 0, 0);
    }
References delay, endHeight, lockon, projectileId, speed, start, and startHeight.
ProjectileTest() [4/4]
com.runehive.game.ProjectileTest.ProjectileTest (Position source, Position delta, int slope, int speed, int projectileId, int startHeight, int endHeight, int lockon, int delay, int creatorSize, int startDistanceOffset)
Definition at line 46 of file ProjectileTest.java.
{
        this(source, delta, lockon, projectileId, speed, delay, startHeight, endHeight, slope, creatorSize, startDistanceOffset, 0);
    }
References creatorSize, delay, endHeight, lockon, projectileId, slope, speed, startDistanceOffset, and startHeight.
Member Function Documentation
getAngle()
int com.runehive.game.ProjectileTest.getAngle ()
Definition at line 102 of file ProjectileTest.java.
{
        return this.angle;
    }
Referenced by ProjectileTest().
getCreatorSize()
int com.runehive.game.ProjectileTest.getCreatorSize ()
Definition at line 82 of file ProjectileTest.java.
{
        return this.creatorSize;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getDelay()
int com.runehive.game.ProjectileTest.getDelay ()
Definition at line 78 of file ProjectileTest.java.
{
        return this.delay;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getDuration()
int com.runehive.game.ProjectileTest.getDuration (int distance)
Definition at line 110 of file ProjectileTest.java.
{
        if (distance > 0) {
            return this.delay + (distance * this.stepMultiplier);
        }
        return 0;
    }
Referenced by getHitDelay().
getEndHeight()
int com.runehive.game.ProjectileTest.getEndHeight ()
Definition at line 66 of file ProjectileTest.java.
{
        return this.endHeight;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getHitDelay()
int com.runehive.game.ProjectileTest.getHitDelay (int distance)
Definition at line 117 of file ProjectileTest.java.
{
        return (int) Math.floor(getDuration(distance) / 30D) + 1; //might be - 1
    }
References getDuration().
Referenced by com.runehive.game.world.World.executeProjectile().
getLockon()
int com.runehive.game.ProjectileTest.getLockon ()
Definition at line 50 of file ProjectileTest.java.
{
        return this.lockon;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getOffset()
Position com.runehive.game.ProjectileTest.getOffset ()
Definition at line 86 of file ProjectileTest.java.
{
        return this.offset;
    }
getProjectileId()
int com.runehive.game.ProjectileTest.getProjectileId ()
Definition at line 54 of file ProjectileTest.java.
{
        return this.projectileId;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getRadius()
int com.runehive.game.ProjectileTest.getRadius ()
Definition at line 106 of file ProjectileTest.java.
{
        return this.radius;
    }
Referenced by ProjectileTest().
getSlope()
int com.runehive.game.ProjectileTest.getSlope ()
Definition at line 62 of file ProjectileTest.java.
{
        return this.slope;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getSpeed()
int com.runehive.game.ProjectileTest.getSpeed ()
Definition at line 74 of file ProjectileTest.java.
{
        return this.speed;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getStart()
Position com.runehive.game.ProjectileTest.getStart ()
Definition at line 94 of file ProjectileTest.java.
{
        return this.start;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getStartDistanceOffset()
int com.runehive.game.ProjectileTest.getStartDistanceOffset ()
Definition at line 90 of file ProjectileTest.java.
{
        return this.startDistanceOffset;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getStartHeight()
int com.runehive.game.ProjectileTest.getStartHeight ()
Definition at line 70 of file ProjectileTest.java.
{
        return this.startHeight;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
getStepMultiplier()
int com.runehive.game.ProjectileTest.getStepMultiplier ()
Definition at line 58 of file ProjectileTest.java.
{
        return stepMultiplier;
    }
References stepMultiplier.
getTarget()
Position com.runehive.game.ProjectileTest.getTarget ()
Definition at line 98 of file ProjectileTest.java.
{
        return this.target;
    }
Referenced by com.runehive.game.world.World.executeProjectile().
Member Data Documentation
angle
final int com.runehive.game.ProjectileTest.angle private
Definition at line 9 of file ProjectileTest.java.
creatorSize
final int com.runehive.game.ProjectileTest.creatorSize private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest(), ProjectileTest(), and ProjectileTest().
delay
final int com.runehive.game.ProjectileTest.delay private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest(), ProjectileTest(), ProjectileTest(), and ProjectileTest().
endHeight
final int com.runehive.game.ProjectileTest.endHeight private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest(), ProjectileTest(), ProjectileTest(), and ProjectileTest().
lockon
final int com.runehive.game.ProjectileTest.lockon private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest(), ProjectileTest(), and ProjectileTest().
offset
Position com.runehive.game.ProjectileTest.offset package
Definition at line 8 of file ProjectileTest.java.
projectileId
final int com.runehive.game.ProjectileTest.projectileId private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest(), ProjectileTest(), ProjectileTest(), and ProjectileTest().
radius
final int com.runehive.game.ProjectileTest.radius private
Definition at line 9 of file ProjectileTest.java.
slope
final int com.runehive.game.ProjectileTest.slope private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest().
speed
final int com.runehive.game.ProjectileTest.speed private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest(), ProjectileTest(), ProjectileTest(), and ProjectileTest().
start
Position com.runehive.game.ProjectileTest.start package
Definition at line 8 of file ProjectileTest.java.
Referenced by ProjectileTest(), and ProjectileTest().
startDistanceOffset
final int com.runehive.game.ProjectileTest.startDistanceOffset private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest(), and ProjectileTest().
startHeight
final int com.runehive.game.ProjectileTest.startHeight private
Definition at line 9 of file ProjectileTest.java.
Referenced by ProjectileTest(), ProjectileTest(), ProjectileTest(), and ProjectileTest().
stepMultiplier
final int com.runehive.game.ProjectileTest.stepMultiplier private
Definition at line 9 of file ProjectileTest.java.
Referenced by getStepMultiplier(), ProjectileTest(), and ProjectileTest().
target
Position com.runehive.game.ProjectileTest.target package
Definition at line 8 of file ProjectileTest.java.
The documentation for this class was generated from the following file:
java/com/runehive/game/ProjectileTest.java