RuneHive-Game: com.runehive.game.world.region.RegionManager Class Reference
com.runehive.game.world.region.RegionManager Class Reference
Manages the world regions.
Public Member Functions
List< Npc > getLocalNpcs (Mob mob)
Gets the local npcs around an entity.
List< Player > getLocalPlayers (Mob mob)
Gets the local players around an entity.
Region getRegion (final int x, final int y)
Gets a region by its x and y coordinates.
Region getRegion (Position position)
Gets a region by position.
Region[] getSurroundingRegions (Position position)
Gets the regions surrounding a position.
Static Public Member Functions
static void forNearbyPlayer (Mob mob, int distance, Consumer< Player > action)
Sends an action to Mob instance which is within a
distance.
static void forNearbyPlayer (Position position, int distance, Consumer< Player > action)
Sends an action to Mob instance which is within a
distance.
Static Private Member Functions
static int hash (int x, int y)
Private Attributes
final Int2ObjectMap< Region > activeRegions = new Int2ObjectOpenHashMap<>()
The active (loaded) region map.
Detailed Description
Manages the world regions.
Author
Graham Edgecombe
Definition at line 20 of file RegionManager.java.
Member Function Documentation
forNearbyPlayer() [1/2]
void com.runehive.game.world.region.RegionManager.forNearbyPlayer (Mob mob, int distance, Consumer< Player > action) static
Sends an action to Mob instance which is within a
distance.
Parameters
action action consumer.
Definition at line 31 of file RegionManager.java.
{
        mob.getRegion().getSurroundingRegions().ifPresent(regions -> {
            for (Region region : regions) {
                for (Player nearby : region.getPlayers(mob.getHeight())) {
                    if (nearby == null) continue;
                    if (Utility.getDistance(nearby, mob) > distance) continue;
                    if (nearby.getCurrentHealth() <= 0 || nearby.isDead()) continue;
                    action.accept(nearby);
                }
            }
        });
    }
References com.runehive.util.Utility.getDistance(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.entity.Entity.getRegion(), and com.runehive.game.world.region.Region.getSurroundingRegions().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Earthquake.hit(), com.runehive.content.clanchannel.channel.ClanChannel.splitLoot(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.start().
forNearbyPlayer() [2/2]
void com.runehive.game.world.region.RegionManager.forNearbyPlayer (Position position, int distance, Consumer< Player > action) static
Sends an action to Mob instance which is within a
distance.
Parameters
action action consumer.
Definition at line 50 of file RegionManager.java.
{
        position.getRegion().getSurroundingRegions().ifPresent(regions -> {
            for (Region region : regions) {
                for (Player other : region.getPlayers(position.getHeight())) {
                    if (other == null) continue;
                    if (Utility.getDistance(other, position) > distance) continue;
                    if (other.getCurrentHealth() <= 0 || other.isDead()) continue;
                    action.accept(other);
                }
            }
        });
    }
References com.runehive.util.Utility.getDistance().
getLocalNpcs()
List< Npc > com.runehive.game.world.region.RegionManager.getLocalNpcs (Mob mob)
Gets the local npcs around an entity.
Parameters
mob The entity.
Returns
The collection of local npcs.
Definition at line 88 of file RegionManager.java.
{
        List<Npc> localNpcs = new LinkedList<>();
        for (Region region : getSurroundingRegions(mob.getPosition())) {
            for (Npc npc : region.getNpcs(mob.getHeight())) {
                if (mob.getPosition().isWithinDistance(npc.getPosition(), Region.VIEW_DISTANCE)) {
                    localNpcs.add(npc);
                }
            }
        }
        return localNpcs;
    }
References com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.entity.Entity.getPosition(), getSurroundingRegions(), com.runehive.game.world.position.Position.isWithinDistance(), and com.runehive.game.world.region.Region.VIEW_DISTANCE.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.areaAction(), and com.runehive.net.packet.out.SendNpcUpdate.encode().
getLocalPlayers()
List< Player > com.runehive.game.world.region.RegionManager.getLocalPlayers (Mob mob)
Gets the local players around an entity.
Parameters
mob The entity.
Returns
The collection of local players.
Definition at line 69 of file RegionManager.java.
{
        Preconditions.checkArgument(mob != null, "mob is null");
        List<Player> localPlayers = new LinkedList<>();
        for (Region region : getSurroundingRegions(mob.getPosition())) {
            for (Player player : region.getPlayers(mob.getHeight())) {
                if (mob.getPosition().isWithinDistance(player.getPosition(), Region.VIEW_DISTANCE)) {
                    localPlayers.add(player);
                }
            }
        }
        return localPlayers;
    }
References com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.entity.Entity.getPosition(), getSurroundingRegions(), com.runehive.game.world.position.Position.isWithinDistance(), and com.runehive.game.world.region.Region.VIEW_DISTANCE.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.areaAction(), and com.runehive.net.packet.out.SendPlayerUpdate.encode().
getRegion() [1/2]
Region com.runehive.game.world.region.RegionManager.getRegion (final int x, final int y)
Gets a region by its x and y coordinates.
Parameters
x The x coordinate.
y The y coordinate.
Returns
The region.
Definition at line 151 of file RegionManager.java.
{
        final int hash = hash(x, y);
        final Region region = activeRegions.get(hash);
        if (region != null) {
            return region;
        }
        final Region newRegion = new Region(x, y);
        activeRegions.put(hash, newRegion);
        return newRegion;
    }
References activeRegions, and hash().
getRegion() [2/2]
Region com.runehive.game.world.region.RegionManager.getRegion (Position position)
Gets a region by position.
Parameters
position The position.
Returns
The region.
Definition at line 140 of file RegionManager.java.
{
        return getRegion(position.getX(), position.getY());
    }
References getRegion().
Referenced by com.runehive.content.Obelisks.activate(), com.runehive.game.world.pathfinding.TraversalMap.getFlags(), com.runehive.game.world.position.Position.getRegion(), getRegion(), getSurroundingRegions(), com.runehive.content.wintertodt.Wintertodt.init(), com.runehive.game.world.pathfinding.TraversalMap.isInactive(), and com.runehive.fs.cache.decoder.RegionDecoder.load().
getSurroundingRegions()
Region[] com.runehive.game.world.region.RegionManager.getSurroundingRegions (Position position)
Gets the regions surrounding a position.
Parameters
position The position.
Returns
The regions surrounding the position.
Definition at line 106 of file RegionManager.java.
{
        Region target = getRegion(position.getX(), position.getY());
        if (target.getSurroundingRegions().isPresent()) {
            return target.getSurroundingRegions().get();
        }
        Set<Region> surrounding = new HashSet<>();
        int chunkX = position.getChunkX();
        int chunkY = position.getChunkY();
        for (int y = -1; y <= 1; y++) {
            for (int x = -1; x <= 1; x++) {
                int xx = (chunkX + x * 8 + 6) << 3;
                int yy = (chunkY + y * 8 + 6) << 3;
                Region region = getRegion(xx, yy);
                if (!surrounding.contains(region)) {
                    surrounding.add(region);
                }
            }
        }
        Region[] x = surrounding.toArray(new Region[surrounding.size()]);
        target.setSurroundingRegions(Optional.of(x));
        return target.getSurroundingRegions().get();
    }
References getRegion(), com.runehive.game.world.region.Region.getSurroundingRegions(), and com.runehive.game.world.region.Region.setSurroundingRegions().
Referenced by com.runehive.game.world.items.ground.GroundItem.addToRegion(), com.runehive.game.world.object.CustomGameObject.addToRegion(), com.runehive.game.world.items.ground.GroundItemEvent.execute(), getLocalNpcs(), getLocalPlayers(), com.runehive.game.world.entity.mob.player.Player.loadRegion(), com.runehive.game.world.object.StaticGameObject.register(), com.runehive.game.world.items.ground.GroundItem.removeFromRegion(), com.runehive.game.world.object.CustomGameObject.removeFromRegion(), and com.runehive.game.world.object.StaticGameObject.unregister().
hash()
int com.runehive.game.world.region.RegionManager.hash (int x, int y) static private
Definition at line 164 of file RegionManager.java.
{
        return ((x >> 6) << 8) + (y >> 6);
    }
Referenced by getRegion().
Member Data Documentation
activeRegions
final Int2ObjectMap<Region> com.runehive.game.world.region.RegionManager.activeRegions = new Int2ObjectOpenHashMap<>() private
The active (loaded) region map.
Definition at line 23 of file RegionManager.java.
Referenced by getRegion().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/region/RegionManager.java