RuneHive-Game: com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect Class Reference
com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect Class Reference
The combat effect applied when a player needs to be skulled.
Public Member Functions
boolean apply (Mob mob)
Applies this effect to mob.
CombatSkullEffect ()
Creates a new CombatSkullEffect.
boolean onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
void process (Mob mob)
Provides processing for this effect on mob.
boolean removeOn (Mob mob)
Removes this effect from mob if needed.
Public Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
CombatEffect (int delay)
Creates a new CombatEffect.
final boolean start (Mob mob)
Starts this combat effect by scheduling a task utilizing the abstract methods in this class.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
static Collection< CombatEffect > values ()
Returns an unmodifiable view of the combat effect listeners.
Static Public Attributes inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
static final Map< CombatEffectType, CombatEffect > EFFECTS = new HashMap<>()
The map of all of the combat effect types mapped to their respective listeners.
Protected Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
final int getDelay ()
Gets the delay for this individual combat effect.
Detailed Description
The combat effect applied when a player needs to be skulled.
Author
lare96 http://github.com/lare96
Definition at line 13 of file CombatSkullEffect.java.
Constructor & Destructor Documentation
CombatSkullEffect()
com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.CombatSkullEffect ()
Creates a new CombatSkullEffect.
Definition at line 18 of file CombatSkullEffect.java.
{
        super(50);
    }
Member Function Documentation
apply()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.apply (Mob mob)
Applies this effect to mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 23 of file CombatSkullEffect.java.
{
        if (mob.isPlayer()) {
            Player player = (Player) mob;
           /* if (Area.inEventArena(mob)) {
                return false;
            }*/
            if (!Area.inWilderness(mob)) {
                return false;
            }
            if (player.skulling.isSkulled()) {
                return false;
            }
            player.skulling.skull();
            return true;
        }
        return false;
    }
References com.runehive.game.world.position.Area.inWilderness(), com.runehive.content.combat.Skulling.isSkulled(), com.runehive.content.combat.Skulling.skull(), and com.runehive.game.world.entity.mob.player.Player.skulling.
onLogin()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 67 of file CombatSkullEffect.java.
{
        if (mob.isPlayer()) {
            Player player = (Player) mob;
            if (player.skulling.isSkulled()) {
                return true;
            }
        }
        return false;
    }
References com.runehive.content.combat.Skulling.isSkulled(), and com.runehive.game.world.entity.mob.player.Player.skulling.
process()
void com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.process (Mob mob)
Provides processing for this effect on mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 62 of file CombatSkullEffect.java.
{
        // nothing to process
    }
removeOn()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect.removeOn (Mob mob)
Removes this effect from mob if needed.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 46 of file CombatSkullEffect.java.
{
        if (mob.isPlayer()) {
            Player player = (Player) mob;
            if (!player.skulling.isSkulled()) {
                player.skulling.unskull();
                return true;
            }
            return false;
        }
        return true;
    }
References com.runehive.content.combat.Skulling.isSkulled(), com.runehive.game.world.entity.mob.player.Player.skulling, and com.runehive.content.combat.Skulling.unskull().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/effect/impl/CombatSkullEffect.java