RuneHive-Game: com.runehive.content.skill.impl.farming.Farming Class Reference
com.runehive.content.skill.impl.farming.Farming Class Reference
Public Member Functions
Farming (Player player)
void fromJson (JsonObject object)
void regionChange (Player player)
JsonObject toJson ()
Static Public Member Functions
static boolean firstClickObject (Player player, GameObject object)
static double getBonus (Player player)
static boolean itemOnObject (Player player, GameObject object, Item item, int slot)
static boolean secondClickObject (Player player, GameObject object)
static void tick (Player player)
Private Attributes
final List< FarmingZone > zones = new LinkedList<>()
Detailed Description
Definition at line 13 of file Farming.java.
Constructor & Destructor Documentation
Farming()
com.runehive.content.skill.impl.farming.Farming.Farming (Player player)
Definition at line 16 of file Farming.java.
{
        zones.add(new CatherbyZone(player));
        zones.add(new ArdougneZone(player));
        zones.add(new FaladorZone(player));
        zones.add(new PhasmatyZone(player));
    }
References zones.
Member Function Documentation
firstClickObject()
boolean com.runehive.content.skill.impl.farming.Farming.firstClickObject (Player player, GameObject object) static
Definition at line 51 of file Farming.java.
{
        boolean success = false;
        for (FarmingZone zone : player.farming.zones) {
            if (zone.isViewable(player.getPosition())) {
                success |= zone.clickObject(object, 1);
            }
        }
        return success;
    }
References com.runehive.content.skill.impl.farming.zones.FarmingZone.clickObject(), com.runehive.game.world.entity.mob.player.Player.farming, com.runehive.game.world.entity.Entity.getPosition(), com.runehive.content.skill.impl.farming.zones.FarmingZone.isViewable(), and zones.
fromJson()
void com.runehive.content.skill.impl.farming.Farming.fromJson (JsonObject object)
Definition at line 87 of file Farming.java.
{
        for (FarmingZone zone : zones) {
            if (!object.has(zone.getClass().getSimpleName())) {
                continue;
            }
            JsonArray thing = object.get(zone.getClass().getSimpleName()).getAsJsonArray();
            zone.fromJson(thing);
        }
    }
References zones.
getBonus()
double com.runehive.content.skill.impl.farming.Farming.getBonus (Player player) static
Definition at line 33 of file Farming.java.
{
        double bonus = 0;
        if(player.equipment.getId(0) == 13646)
            bonus += 0.4;
        if(player.equipment.getId(4) == 13642)
            bonus += 0.8;
        if(player.equipment.getId(7) == 13640)
            bonus += 0.6;
        if(player.equipment.getId(10) == 13644)
            bonus += 0.2;
        if(player.equipment.containsAll(13646, 13642, 13640, 13644))
            bonus = 2.5;
        return bonus;
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.world.entity.mob.player.Player.equipment, and com.runehive.game.world.items.containers.ItemContainer.getId().
Referenced by com.runehive.game.world.entity.skill.SkillManager.addExperience().
itemOnObject()
boolean com.runehive.content.skill.impl.farming.Farming.itemOnObject (Player player, GameObject object, Item item, int slot) static
Definition at line 23 of file Farming.java.
{
        boolean success = false;
        for (FarmingZone zone : player.farming.zones) {
            if (zone.isViewable(player.getPosition())) {
                success |= zone.itemOnObject(object, item, slot);
            }
        }
        return success;
    }
References com.runehive.game.world.entity.mob.player.Player.farming, com.runehive.game.world.entity.Entity.getPosition(), com.runehive.content.skill.impl.farming.zones.FarmingZone.isViewable(), com.runehive.content.skill.impl.farming.zones.FarmingZone.itemOnObject(), and zones.
regionChange()
void com.runehive.content.skill.impl.farming.Farming.regionChange (Player player)
Definition at line 75 of file Farming.java.
{
        zones.forEach(zone -> zone.sendPatchConfigs(player));
    }
References zones.
secondClickObject()
boolean com.runehive.content.skill.impl.farming.Farming.secondClickObject (Player player, GameObject object) static
Definition at line 61 of file Farming.java.
{
        boolean success = false;
        for (FarmingZone zone : player.farming.zones) {
            if (zone.isViewable(player.getPosition())) {
                success |= zone.clickObject(object, 2);
            }
        }
        return success;
    }
References com.runehive.content.skill.impl.farming.zones.FarmingZone.clickObject(), com.runehive.game.world.entity.mob.player.Player.farming, com.runehive.game.world.entity.Entity.getPosition(), com.runehive.content.skill.impl.farming.zones.FarmingZone.isViewable(), and zones.
tick()
void com.runehive.content.skill.impl.farming.Farming.tick (Player player) static
Definition at line 71 of file Farming.java.
{
        player.farming.zones.forEach(FarmingZone::tick);
    }
References com.runehive.game.world.entity.mob.player.Player.farming, com.runehive.content.skill.impl.farming.zones.FarmingZone.tick(), and zones.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.sequence().
toJson()
JsonObject com.runehive.content.skill.impl.farming.Farming.toJson ()
Definition at line 79 of file Farming.java.
{
        JsonObject object = new JsonObject();
        for (FarmingZone zone : zones) {
            object.add(zone.getClass().getSimpleName(), zone.toJson());
        }
        return object;
    }
References zones.
Member Data Documentation
zones
final List<FarmingZone> com.runehive.content.skill.impl.farming.Farming.zones = new LinkedList<>() private
Definition at line 14 of file Farming.java.
Referenced by Farming(), firstClickObject(), fromJson(), itemOnObject(), regionChange(), secondClickObject(), tick(), and toJson().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/farming/Farming.java