RuneHive-Game: com.runehive.content.activity.impl.barrows.BarrowsUtility Class Reference
com.runehive.content.activity.impl.barrows.BarrowsUtility Class Reference
Static Public Member Functions
static boolean teleportPlayer (Player player)
Static Public Attributes
static int BARROWS []
static final int[][] BROKEN_BARROWS
static Item[] JUNK
static int RUNES_AND_AMMUNITION []
Static Package Functions
static void generateRewards (Player player)
static BrotherData getHiddenBrother (Player player)
Detailed Description
Definition at line 22 of file BarrowsUtility.java.
Member Function Documentation
generateRewards()
void com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards (Player player) static package
Definition at line 72 of file BarrowsUtility.java.
{
        Set<Item> rewards = new HashSet<>();
        Item[] rewardDisplay = new Item[5];
        Item junk = Utility.randomElement(JUNK);
        Item runes = new Item(Utility.randomElement(BarrowsUtility.RUNES_AND_AMMUNITION), 25 + Utility.random(5));
        Item runes2 = new Item(Utility.randomElement(BarrowsUtility.RUNES_AND_AMMUNITION), 25 + Utility.random(5));
        if (junk.getId() == 995) {
            junk.setAmount(Utility.random(5000, 25000));
        }
        rewards.add(junk);
        if (runes.getId() == runes2.getId()) {
            runes.setAmount(runes.getAmount() + runes2.getAmount());
            rewards.add(runes);
        } else {
            rewards.add(runes);
            rewards.add(runes2);
        }
        if (Utility.random(100) >= 90) {
            rewards.add(new Item(Utility.randomElement(BarrowsUtility.BARROWS)));
            AchievementHandler.activate(player, AchievementKey.BARROWS_UNIQUE);
        }
        int value = 0;
        int count = 0;
        for (Item item : rewards) {
            value += item.getValue() * item.getAmount();
            rewardDisplay[count] = item;
            count++;
            CollectionLog.logItem(player, CollectionLogData.BARROWS, item.getId(), item.getAmount());
        }
        player.send(new SendString("Total worth: " + Utility.formatDigits(value), 33306));
        player.send(new SendItemOnInterface(33305, rewardDisplay));
        rewards.forEach(player.inventory::addOrDrop);
        player.interfaceManager.open(33300);
        player.activityLogger.add(ActivityLog.BARROWS);
        World.schedule(new CeillingCollapseTask(player));
        AchievementHandler.activate(player, AchievementKey.BARROWS);
        CollectionLog.increaseCounter(player, CollectionLogData.BARROWS);
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.entity.mob.player.Player.activityLogger, com.runehive.content.ActivityLogger.add(), com.runehive.content.achievement.AchievementKey.BARROWS, BARROWS, com.runehive.content.ActivityLog.BARROWS, com.runehive.content.collectionlog.CollectionLogData.BARROWS, com.runehive.content.achievement.AchievementKey.BARROWS_UNIQUE, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.content.collectionlog.CollectionLog.increaseCounter(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, JUNK, com.runehive.content.collectionlog.CollectionLog.logItem(), com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), RUNES_AND_AMMUNITION, com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.items.Item.setAmount().
Referenced by com.runehive.content.activity.impl.barrows.Barrows.clickObject().
getHiddenBrother()
BrotherData com.runehive.content.activity.impl.barrows.BarrowsUtility.getHiddenBrother (Player player) static package
Definition at line 62 of file BarrowsUtility.java.
{
        List<BrotherData> brother = new ArrayList<>();
        for (int i = 0; i < player.barrowKills.length; i++) {
            if (!player.barrowKills[i]) {
                brother.add(BrotherData.values()[i]);
            }
        }
        return Utility.randomElement(brother);
    }
References com.runehive.game.world.entity.mob.player.Player.barrowKills, and com.runehive.util.Utility.randomElement().
Referenced by com.runehive.content.activity.impl.barrows.Barrows.onDeath().
teleportPlayer()
boolean com.runehive.content.activity.impl.barrows.BarrowsUtility.teleportPlayer (Player player) static
Definition at line 51 of file BarrowsUtility.java.
{
        for (BrotherData brother : BrotherData.values()) {
            if (player.getPosition().inLocation(brother.getSouthWest(), brother.getNorthEast(), true)) {
                player.move(brother.getCryptPosition());
                player.send(new SendMessage("You dig a hole and fall into " + brother.name().toLowerCase() + "s crypt!"));
                return true;
            }
        }
        return false;
    }
References com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Position.inLocation(), com.runehive.game.world.entity.mob.Mob.move(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.game.action.impl.SpadeAction.execute().
Member Data Documentation
BARROWS
int com.runehive.content.activity.impl.barrows.BarrowsUtility.BARROWS[] static
Initial value:
= {4708, 4710, 4712, 4714, 4708, 4710, 4712, 4714, 4716, 4718, 4720,
            4722, 4724, 4718, 4720,
            4722, 4724, 4718, 4720,
            4722, 4724, 4726, 4728, 4730, 4732, 4734, 4736, 4738, 4745, 4747,
            4749, 4751, 4753, 4755, 4757, 4759}
Definition at line 35 of file BarrowsUtility.java.
                                  {4708, 4710, 4712, 4714, 4708, 4710, 4712, 4714, 4716, 4718, 4720,
            4722, 4724, 4718, 4720,
            4722, 4724, 4718, 4720,
            4722, 4724, 4726, 4728, 4730, 4732, 4734, 4736, 4738, 4745, 4747,
            4749, 4751, 4753, 4755, 4757, 4759};
Referenced by generateRewards().
BROKEN_BARROWS
final int [][] com.runehive.content.activity.impl.barrows.BarrowsUtility.BROKEN_BARROWS static
Initial value:
= {
            {4708, 4860}, {4710, 4866},
            {4712, 4872}, {4714, 4878}, {4716, 4884}, {4720, 4896},
            {4718, 4890}, {4720, 4896}, {4722, 4902}, {4732, 4932},
            {4734, 4938}, {4736, 4944}, {4738, 4950}, {4724, 4908},
            {4726, 4914}, {4728, 4920}, {4730, 4926}, {4745, 4956},
            {4747, 4926}, {4749, 4968}, {4751, 4994}, {4753, 4980},
            {4755, 4986}, {4757, 4992}, {4759, 4998}}
Definition at line 41 of file BarrowsUtility.java.
{
            {4708, 4860}, {4710, 4866},
            {4712, 4872}, {4714, 4878}, {4716, 4884}, {4720, 4896},
            {4718, 4890}, {4720, 4896}, {4722, 4902}, {4732, 4932},
            {4734, 4938}, {4736, 4944}, {4738, 4950}, {4724, 4908},
            {4726, 4914}, {4728, 4920}, {4730, 4926}, {4745, 4956},
            {4747, 4926}, {4749, 4968}, {4751, 4994}, {4753, 4980},
            {4755, 4986}, {4757, 4992}, {4759, 4998}};
JUNK
Item [] com.runehive.content.activity.impl.barrows.BarrowsUtility.JUNK static
Initial value:
= {
            new Item(995, 500),
            new Item(985),
            new Item(987),
            new Item(1149)
    }
Definition at line 24 of file BarrowsUtility.java.
{
            new Item(995, 500),
            new Item(985),
            new Item(987),
            new Item(1149)
    };
Referenced by generateRewards().
RUNES_AND_AMMUNITION
int com.runehive.content.activity.impl.barrows.BarrowsUtility.RUNES_AND_AMMUNITION[] static
Initial value:
= {
            4740, 558, 560, 565
    }
Definition at line 31 of file BarrowsUtility.java.
{
            4740, 558, 560, 565
    };
Referenced by generateRewards().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/barrows/BarrowsUtility.java