RuneHive-Game: com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit Class Reference
com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit Class Reference
Static Public Member Functions
static int getBaseDamage (Mob player)
static int getEffectiveStrength (Mob player)
static double getOtherBonus (Mob player, boolean includeNpcMax)
static int getStrengthBonus (Mob player)
static int getStrengthLevel (Mob player)
static int getStyleBonus (Mob player)
static int maxHit (Mob player)
static double slayerPerkBonus (Mob player)
Static Private Member Functions
static double getPrayerBonus (Mob player)
Detailed Description
Author
Origin @Since January 16 2022
Definition at line 12 of file MeleeMaxHit.java.
Member Function Documentation
getBaseDamage()
int com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getBaseDamage (Mob player) static
Definition at line 34 of file MeleeMaxHit.java.
{
        return (int) (Math.floor(0.5 + (getEffectiveStrength(player)) * (getStrengthBonus(player) + 64) + 320) / 640.0);
    }
References getEffectiveStrength(), and getStrengthBonus().
Referenced by maxHit().
getEffectiveStrength()
int com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getEffectiveStrength (Mob player) static
Definition at line 228 of file MeleeMaxHit.java.
{
        return (int) (Math.floor(((((getStrengthLevel(player)) * getPrayerBonus(player)) + getStyleBonus(player)) + 8) * getOtherBonus(player, true)));
    }
References getOtherBonus(), getPrayerBonus(), getStrengthLevel(), and getStyleBonus().
Referenced by getBaseDamage().
getOtherBonus()
double com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getOtherBonus (Mob player, boolean includeNpcMax) static
Other bonuses
Definition at line 81 of file MeleeMaxHit.java.
{
        //FightStyle style = player.getCombat().getFightType().getStyle();
        double otherBonus = 1;
        //boolean target = player.getCombat().getDefender().isNpc();
        /**
         * Other bonuses
         *
         */
       /* if (FormulaUtils.voidMelee(player) || FormulaUtils.wearingEliteVoid(player)) {
            otherBonus *= 1.10;
        }
        var wearingAnyBlackMask = FormulaUtils.wearingBlackMask(player) || FormulaUtils.wearingBlackMaskImbued(player) || player.getEquipment().wearingSlayerHelm();
        if(wearingAnyBlackMask && target != null && target.isNpc() && includeNpcMax) {
            NPC npc = target.getAsNpc();
            if(npc.id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.1667;
            }
            if(Slayer.creatureMatches(player, npc.id())) {
                otherBonus *= 1.1667;
            }
        }
        if(player.getEquipment().hasAt(EquipSlot.AMULET, SALVE_AMULET) && !wearingAnyBlackMask && target != null && includeNpcMax) {
            if(target.isNpc() && target.getAsNpc().id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.16;
            }
            if(FormulaUtils.isUndead(target)) {
                otherBonus *= 1.16;
            }
        }
        if(player.getEquipment().hasAt(EquipSlot.AMULET, SALVE_AMULETI) && !wearingAnyBlackMask && target != null && includeNpcMax) {
            if(target.isNpc() && target.getAsNpc().id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.20;
            }
            if(FormulaUtils.isUndead(target)) {
                otherBonus *= 1.20;
            }
        }
        if(player.getEquipment().hasAt(EquipSlot.AMULET, SALVE_AMULET_E) && !wearingAnyBlackMask && target != null && includeNpcMax) {
            if(target.isNpc() && target.getAsNpc().id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.20;
            }
            if(FormulaUtils.isUndead(target)) {
                otherBonus *= 1.20;
            }
        }
        if(player.getEquipment().hasAt(EquipSlot.AMULET, SALVE_AMULETEI) && !wearingAnyBlackMask && target != null && includeNpcMax) {
            if(target.isNpc() && target.getAsNpc().id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.20;
            }
            if(FormulaUtils.isUndead(target)) {
                otherBonus *= 1.20;
            }
        }
        if (player.getEquipment().hasAt(EquipSlot.WEAPON, RED_SLAYER_HELMET_I) && target != null && target.isNpc() && includeNpcMax) {
            otherBonus *= 1.10;
        }
        if (FormulaUtils.wearingTwistedSlayerHelmetI(player) && target != null && target.isNpc() && includeNpcMax) {
            otherBonus *= 1.10;
        }
        if(player.getEquipment().hasAt(EquipSlot.WEAPON, ARCLIGHT) && target != null && includeNpcMax) {
            if(target.isNpc() && target.getAsNpc().id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.70;
            }
            if(FormulaUtils.isDemon(target)) {
                otherBonus *= 1.70;
            }
        }
        if(player.getEquipment().hasAt(EquipSlot.WEAPON, DARKLIGHT) && target != null && includeNpcMax) {
            if(target.isNpc() && target.getAsNpc().id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.60;
            }
            if(FormulaUtils.isDemon(target)) {
                otherBonus *= 1.60;
            }
        }
        if(player.getEquipment().hasAt(EquipSlot.WEAPON, DARKLIGHT) && target != null && includeNpcMax) {
            if(target.isNpc() && target.getAsNpc().id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.175;
            }
            if(target.isNpc() && target.getAsNpc().def() != null && (target.getAsNpc().def().name.equalsIgnoreCase("Kurask") || target.getAsNpc().def().name.equalsIgnoreCase("Turoth"))) {
                otherBonus *= 1.175;
            }
        }
        if (FormulaUtils.obbyArmour(player) && FormulaUtils.hasObbyWeapon(player)) {
            otherBonus *= 1.10;
        }
        if(FormulaUtils.berserkerNecklace(player) && FormulaUtils.hasObbyWeapon(player)) {
            otherBonus *= 1.10;
        }
        if (player.getCombat().getFightType().getAttackType() == AttackType.CRUSH) {
            if (player.getEquipment().hasAt(EquipSlot.HEAD, INQUISITORS_GREAT_HELM) || player.getEquipment().hasAt(EquipSlot.BODY, INQUISITORS_HAUBERK) || player.getEquipment().hasAt(EquipSlot.LEGS, INQUISITORS_PLATESKIRT)) {
                otherBonus *= 1.05;
            }
        }
        if(player.getEquipment().hasAt(EquipSlot.WEAPON, DRAGON_HUNTER_LANCE) && target != null && includeNpcMax) {
            if(target.isNpc() && target.getAsNpc().id() == NpcIdentifiers.COMBAT_DUMMY) {
                otherBonus *= 1.20;
            }
            if(FormulaUtils.isDragon(target)) {
                otherBonus *= 1.20;
            }
        }
        //• Gadderhammer: 1.25 or 2.0 vs shades
        if(player.getEquipment().hasAt(EquipSlot.WEAPON, GADDERHAMMER)) {
            if(target != null && target.isNpc()) {
                NPC npc = target.getAsNpc();
                NpcDefinition def = npc.def();
                var isShade = def != null && def.name.equalsIgnoreCase("Shade");
                otherBonus *= isShade ? 1.25 : 2.00;
            }
        }
        if (FormulaUtils.hasViggorasChainMace(player) && target != null && target.isNpc() && includeNpcMax) {
            otherBonus *= 1.50;
        }*/
        return otherBonus;
    }
Referenced by getEffectiveStrength().
getPrayerBonus()
double com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getPrayerBonus (Mob player) static private
Prayer Bonus
Definition at line 46 of file MeleeMaxHit.java.
{
        /**
         * Prayer Bonus
         *
         */
        double prayerBonus = 1;
        if (player.prayer.isActive(Prayer.THICK_SKIN))
            prayerBonus += 1.05D; // 5% def level boost
        else if (player.prayer.isActive(Prayer.ROCK_SKIN))
            prayerBonus += 1.10D; // 10% def level boost
        else if (player.prayer.isActive(Prayer.STEEL_SKIN))
            prayerBonus += 1.15D; // 15% def level boost
        else if (player.prayer.isActive(Prayer.CHIVALRY))
            prayerBonus += 1.20D; // 20% def level boost
        else if (player.prayer.isActive(Prayer.PIETY))
            prayerBonus += 1.25D; // 25% def level boost
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.CHIVALRY, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.prayer.Prayer.PIETY, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.ROCK_SKIN, com.runehive.game.world.entity.mob.prayer.Prayer.STEEL_SKIN, and com.runehive.game.world.entity.mob.prayer.Prayer.THICK_SKIN.
Referenced by getEffectiveStrength().
getStrengthBonus()
int com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStrengthBonus (Mob player) static
Definition at line 38 of file MeleeMaxHit.java.
{
        return player.getBonus(9);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus().
Referenced by getBaseDamage().
getStrengthLevel()
int com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStrengthLevel (Mob player) static
Definition at line 42 of file MeleeMaxHit.java.
{
        return player.skills.getLevel(Skill.STRENGTH);
    }
References com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.skill.Skill.STRENGTH.
Referenced by getEffectiveStrength().
getStyleBonus()
int com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStyleBonus (Mob player) static
Definition at line 65 of file MeleeMaxHit.java.
{
        FightStyle style = player.getCombat().getFightType().getStyle();
        return style.equals(FightStyle.AGGRESSIVE) ? 3 : style.equals(FightStyle.ACCURATE) ? 1 : 0;
    }
References com.runehive.game.world.entity.combat.attack.FightStyle.ACCURATE, com.runehive.game.world.entity.combat.attack.FightStyle.AGGRESSIVE, and com.runehive.game.world.entity.mob.Mob.getCombat().
Referenced by getEffectiveStrength().
maxHit()
int com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.maxHit (Mob player) static
Max Hit
Random Stuff
Definition at line 14 of file MeleeMaxHit.java.
{
        /**
         * Max Hit
         *
         */
        int maxHit = (int) Math.floor(getBaseDamage(player) * slayerPerkBonus(player));
        /**
         * Random Stuff
         */
       /* if (CombatFactory.fullDharoks(player)) {
            double lostHp = player.maxHp() - player.hp();
            maxHit *= (1 + ((lostHp /100) * (player.maxHp() / 100)));
        } */
        return (int) Math.floor(maxHit);
    }
References getBaseDamage(), maxHit(), and slayerPerkBonus().
Referenced by com.runehive.game.world.entity.combat.attack.FormulaFactory.getMaxHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.getModifiedMaxHit(), and maxHit().
slayerPerkBonus()
double com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.slayerPerkBonus (Mob player) static
Do slayer shit here
Definition at line 70 of file MeleeMaxHit.java.
{
     //   SlayerTask target = player.getPlayer().slayer.getTask();
        double slayerPerkBonus = 1.0;
        /**
         * Do slayer shit here
         */
        return slayerPerkBonus;
    }
References slayerPerkBonus().
Referenced by maxHit(), and slayerPerkBonus().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/maxhit/MeleeMaxHit.java