RuneHive-Game: com.runehive.content.tradingpost.ItemHistory Class Reference
com.runehive.content.tradingpost.ItemHistory Class Reference
Public Member Functions
String getBuyer ()
int getItemId ()
int getPrice ()
int getQuantity ()
String getSeller ()
ItemHistory (int quantity, int itemId, int price, String seller, String buyer)
Private Attributes
final String buyer
final int itemId
final int price
final int quantity
final String seller
Detailed Description
Definition at line 3 of file ItemHistory.java.
Constructor & Destructor Documentation
ItemHistory()
com.runehive.content.tradingpost.ItemHistory.ItemHistory (int quantity, int itemId, int price, String seller, String buyer)
Definition at line 10 of file ItemHistory.java.
{
        this.quantity = quantity;
        this.itemId = itemId;
        this.price = price;
        this.seller = seller;
        this.buyer = buyer;
    }
References buyer, itemId, price, quantity, and seller.
Member Function Documentation
getBuyer()
String com.runehive.content.tradingpost.ItemHistory.getBuyer ()
Definition at line 34 of file ItemHistory.java.
{
        return buyer;
    }
References buyer.
Referenced by com.runehive.content.tradingpost.TradingPost.sendItemHistoryData().
getItemId()
int com.runehive.content.tradingpost.ItemHistory.getItemId ()
Definition at line 22 of file ItemHistory.java.
{
        return itemId;
    }
References itemId.
Referenced by com.runehive.content.tradingpost.TradingPost.addToItemHistory(), and com.runehive.content.tradingpost.TradingPost.sendItemHistoryData().
getPrice()
int com.runehive.content.tradingpost.ItemHistory.getPrice ()
Definition at line 26 of file ItemHistory.java.
{
        return price;
    }
References price.
Referenced by com.runehive.content.tradingpost.TradingPost.sendItemHistoryData().
getQuantity()
int com.runehive.content.tradingpost.ItemHistory.getQuantity ()
Definition at line 18 of file ItemHistory.java.
{
        return quantity;
    }
References quantity.
getSeller()
String com.runehive.content.tradingpost.ItemHistory.getSeller ()
Definition at line 30 of file ItemHistory.java.
{
        return seller;
    }
References seller.
Referenced by com.runehive.content.tradingpost.TradingPost.sendItemHistoryData().
Member Data Documentation
buyer
final String com.runehive.content.tradingpost.ItemHistory.buyer private
Definition at line 8 of file ItemHistory.java.
Referenced by getBuyer(), and ItemHistory().
itemId
final int com.runehive.content.tradingpost.ItemHistory.itemId private
Definition at line 5 of file ItemHistory.java.
Referenced by getItemId(), and ItemHistory().
price
final int com.runehive.content.tradingpost.ItemHistory.price private
Definition at line 6 of file ItemHistory.java.
Referenced by getPrice(), and ItemHistory().
quantity
final int com.runehive.content.tradingpost.ItemHistory.quantity private
Definition at line 4 of file ItemHistory.java.
Referenced by getQuantity(), and ItemHistory().
seller
final String com.runehive.content.tradingpost.ItemHistory.seller private
Definition at line 7 of file ItemHistory.java.
Referenced by getSeller(), and ItemHistory().
The documentation for this class was generated from the following file:
java/com/runehive/content/tradingpost/ItemHistory.java