RuneHive-Game: com.runehive.content.skill.impl.fletching.FletchableItem Class Reference
com.runehive.content.skill.impl.fletching.FletchableItem Class Reference
Public Member Functions
FletchableItem (Item product, int level, double experience)
double getExperience ()
int getLevel ()
Item getProduct ()
Private Attributes
final double experience
final int level
final Item product
Detailed Description
Definition at line 5 of file FletchableItem.java.
Constructor & Destructor Documentation
FletchableItem()
com.runehive.content.skill.impl.fletching.FletchableItem.FletchableItem (Item product, int level, double experience)
Definition at line 13 of file FletchableItem.java.
{
        this.product = product;
        this.level = level;
        this.experience = experience;
    }
References experience, level, and product.
Member Function Documentation
getExperience()
double com.runehive.content.skill.impl.fletching.FletchableItem.getExperience ()
Definition at line 27 of file FletchableItem.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch().
getLevel()
int com.runehive.content.skill.impl.fletching.FletchableItem.getLevel ()
Definition at line 23 of file FletchableItem.java.
{
        return level;
    }
References level.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.start().
getProduct()
Item com.runehive.content.skill.impl.fletching.FletchableItem.getProduct ()
Definition at line 19 of file FletchableItem.java.
{
        return product;
    }
References product.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
Member Data Documentation
experience
final double com.runehive.content.skill.impl.fletching.FletchableItem.experience private
Definition at line 11 of file FletchableItem.java.
Referenced by FletchableItem(), and getExperience().
level
final int com.runehive.content.skill.impl.fletching.FletchableItem.level private
Definition at line 9 of file FletchableItem.java.
Referenced by FletchableItem(), and getLevel().
product
final Item com.runehive.content.skill.impl.fletching.FletchableItem.product private
Definition at line 7 of file FletchableItem.java.
Referenced by FletchableItem(), and getProduct().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/fletching/FletchableItem.java