RuneHive-Game: com.runehive.util.parser.GenericParser Class Reference
com.runehive.util.parser.GenericParser Class Reference abstract
Represents an abstract parser.
Public Member Functions
abstract void deserialize ()
The method that deserializes the file information.
GenericParser (String path, String extension, boolean log)
Creates a new GenericParser.
final int getIndex ()
Gets the current index of the line being parsed.
void onRead ()
The method called after all the data has been parsed.
void run ()
String toString ()
Protected Attributes
int index
The index of the current line being parsed.
final Path path
The path of the file to parse.
Private Attributes
final String extension
The file name extension to parse.
final boolean log
Static Private Attributes
static final Logger logger = LogManager.getLogger(GenericParser.class)
Detailed Description
Represents an abstract parser.
Author
Seven
Definition at line 14 of file GenericParser.java.
Constructor & Destructor Documentation
GenericParser()
com.runehive.util.parser.GenericParser.GenericParser (String path, String extension, boolean log)
Creates a new GenericParser.
Parameters
path The path of the file to parse.
extension The file name extension.
log The flag that denotes to log messages.
Definition at line 47 of file GenericParser.java.
{
        this.path = Paths.get("./data/", path + extension);
        this.extension = extension;
        this.log = log;
    }
References extension, log, and path.
Member Function Documentation
deserialize()
abstract void com.runehive.util.parser.GenericParser.deserialize () abstract
The method that deserializes the file information.
Reimplemented in com.runehive.util.parser.GsonParser, and com.runehive.util.parser.TextFileParser.
Referenced by run().
getIndex()
final int com.runehive.util.parser.GenericParser.getIndex ()
Gets the current index of the line being parsed.
Returns
The index of this line.
Definition at line 79 of file GenericParser.java.
{
        return index;
    }
References index.
onRead()
void com.runehive.util.parser.GenericParser.onRead ()
The method called after all the data has been parsed.
Definition at line 70 of file GenericParser.java.
{
    }
Referenced by run().
run()
void com.runehive.util.parser.GenericParser.run ()
Definition at line 59 of file GenericParser.java.
                      {
        deserialize();
        onRead();
        if (log) {
            logger.info(toString());
        }
    }
References deserialize(), log, logger, onRead(), and toString().
Referenced by com.runehive.game.world.items.ItemDefinition.create(), com.runehive.util.tools.wiki.impl.BonusParser.finish(), com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), com.runehive.util.parser.old.EquipmentDefinitionParser.initialize(), com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.main(), com.runehive.util.tools.DropDefinitionDumper.main(), com.runehive.util.tools.ItemDBdefUpdate.main(), and com.runehive.RuneHive.processSequentialStartupTasks().
toString()
String com.runehive.util.parser.GenericParser.toString ()
Definition at line 84 of file GenericParser.java.
{
        return String.format("Loaded: %d %s.", index, path.getFileName().toString().replace("_", " ").replace(extension, ""));
    }
References extension, index, and path.
Referenced by run().
Member Data Documentation
extension
final String com.runehive.util.parser.GenericParser.extension private
The file name extension to parse.
Definition at line 31 of file GenericParser.java.
Referenced by GenericParser(), and toString().
index
int com.runehive.util.parser.GenericParser.index protected
The index of the current line being parsed.
Definition at line 26 of file GenericParser.java.
Referenced by com.runehive.util.parser.GsonParser.deserialize(), com.runehive.util.parser.TextFileParser.deserialize(), getIndex(), and toString().
log
final boolean com.runehive.util.parser.GenericParser.log private
Definition at line 33 of file GenericParser.java.
Referenced by GenericParser(), com.runehive.util.parser.GsonParser.GsonParser(), run(), and com.runehive.util.parser.TextFileParser.TextFileParser().
logger
final Logger com.runehive.util.parser.GenericParser.logger = LogManager.getLogger(GenericParser.class) static private
Definition at line 16 of file GenericParser.java.
Referenced by run().
path
final Path com.runehive.util.parser.GenericParser.path protected
The path of the file to parse.
Definition at line 21 of file GenericParser.java.
Referenced by com.runehive.util.parser.GsonParser.deserialize(), com.runehive.util.parser.TextFileParser.deserialize(), GenericParser(), com.runehive.util.parser.GsonParser.GsonParser(), com.runehive.util.parser.GsonParser.GsonParser(), com.runehive.util.parser.TextFileParser.TextFileParser(), com.runehive.util.parser.TextFileParser.TextFileParser(), and toString().
The documentation for this class was generated from the following file:
java/com/runehive/util/parser/GenericParser.java