RuneHive-Game: com.runehive.content.clanchannel.content.ClanShowcase Class Reference
com.runehive.content.clanchannel.content.ClanShowcase Class Reference
Public Member Functions
ClanShowcase (ClanChannel channel)
void openShowcase (Player player, int slot)
void remove (Player player)
void select (Player player, int item, int slot)
void set (Player player)
Public Attributes
int[] showcase = new int[3]
List< Integer > showcaseItems = new ArrayList<>(28)
Private Attributes
final ClanChannel channel
int currentItem = -1
int currentSlot = -1
int showcaseSlot
Detailed Description
Definition at line 15 of file ClanShowcase.java.
Constructor & Destructor Documentation
ClanShowcase()
com.runehive.content.clanchannel.content.ClanShowcase.ClanShowcase (ClanChannel channel)
Definition at line 22 of file ClanShowcase.java.
{
        this.channel = channel;
    }
References channel.
Member Function Documentation
openShowcase()
void com.runehive.content.clanchannel.content.ClanShowcase.openShowcase (Player player, int slot)
Definition at line 26 of file ClanShowcase.java.
{
        Item[] showcase = new Item[28];
        for (int index = 0; index < showcaseItems.size(); index++) {
            showcase[index] = new Item(showcaseItems.get(index));
        }
        player.send(new SendString(channel.getName() + "'s Showcase", 57702));
        player.send(new SendString(showcaseItems.size() + "/28", 57718));
        player.send(new SendItemOnInterface(57716, showcase));
        player.send(new SendItemOnInterface(57717));
        showcaseSlot = slot;
        currentSlot = -1;
        currentItem = -1;
        player.interfaceManager.open(57700);
    }
References channel, currentItem, currentSlot, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.game.world.entity.mob.player.Player.send(), showcase, showcaseItems, and showcaseSlot.
Referenced by remove().
remove()
void com.runehive.content.clanchannel.content.ClanShowcase.remove (Player player)
Definition at line 73 of file ClanShowcase.java.
{
        if (!player.interfaceManager.isInterfaceOpen(57700))
            return;
        if (currentSlot == -1 || currentItem == -1) {
            player.send(new SendMessage("You should select an item first."));
            return;
        }
        if (showcaseItems.size() <= 3) {
            player.send(new SendMessage("You need a minimum of 3 showcase items. This action can not be performed."));
            return;
        }
        player.dialogueFactory.sendStatement(
            "Are you sure you want to delete <col=225>" + ItemDefinition.get(currentItem).getName() + "</col>?",
            "Once this action is performed it can not be undone!")
            .sendOption("Yes", () -> {
                showcaseItems.remove(currentSlot);
                openShowcase(player, currentItem);
                player.send(new SendMessage("You have successfully removed that item from your showcase."));
            }, "Nevermind", () -> player.dialogueFactory.clear()).execute();
    }
References currentItem, currentSlot, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), openShowcase(), and showcaseItems.
select()
void com.runehive.content.clanchannel.content.ClanShowcase.select (Player player, int item, int slot)
Definition at line 41 of file ClanShowcase.java.
{
        if (!player.interfaceManager.isInterfaceOpen(57700) || slot < 0 || slot >= showcaseItems.size())
            return;
        int id = showcaseItems.get(slot);
        if (item == id) {
            currentSlot = slot;
            currentItem = id;
            player.send(new SendItemOnInterface(57717, new Item(id)));
        }
    }
References currentItem, currentSlot, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.isInterfaceOpen(), com.runehive.game.world.entity.mob.player.Player.send(), and showcaseItems.
set()
void com.runehive.content.clanchannel.content.ClanShowcase.set (Player player)
Definition at line 53 of file ClanShowcase.java.
{
        if (!player.interfaceManager.isInterfaceOpen(57700) || showcaseSlot < 0 || showcaseSlot >= 3)
            return;
        if (currentSlot == -1 || currentItem == -1) {
            player.send(new SendMessage("You should select an item first."));
            return;
        }
        showcase[showcaseSlot] = currentItem;
        ClanChannelHandler.manage(player);
        Item[] showcase = new Item[28];
        for (int index = 0; index < showcaseItems.size(); index++) {
            showcase[index] = new Item(showcaseItems.get(index));
        }
        player.send(new SendItemOnInterface(57716));
        player.send(new SendItemOnInterface(57716, showcase));
        player.send(new SendMessage("You have successfully changed your showcase."));
    }
References currentItem, currentSlot, com.runehive.content.clanchannel.channel.ClanChannelHandler.manage(), showcase, showcaseItems, and showcaseSlot.
Member Data Documentation
channel
final ClanChannel com.runehive.content.clanchannel.content.ClanShowcase.channel private
Definition at line 16 of file ClanShowcase.java.
Referenced by ClanShowcase(), and openShowcase().
currentItem
int com.runehive.content.clanchannel.content.ClanShowcase.currentItem = -1 private
Definition at line 19 of file ClanShowcase.java.
Referenced by openShowcase(), remove(), select(), and set().
currentSlot
int com.runehive.content.clanchannel.content.ClanShowcase.currentSlot = -1 private
Definition at line 19 of file ClanShowcase.java.
Referenced by openShowcase(), remove(), select(), and set().
showcase
int [] com.runehive.content.clanchannel.content.ClanShowcase.showcase = new int[3]
Definition at line 17 of file ClanShowcase.java.
Referenced by openShowcase(), and set().
showcaseItems
List<Integer> com.runehive.content.clanchannel.content.ClanShowcase.showcaseItems = new ArrayList<>(28)
Definition at line 18 of file ClanShowcase.java.
Referenced by openShowcase(), remove(), select(), and set().
showcaseSlot
int com.runehive.content.clanchannel.content.ClanShowcase.showcaseSlot private
Definition at line 20 of file ClanShowcase.java.
Referenced by openShowcase(), and set().
The documentation for this class was generated from the following file:
java/com/runehive/content/clanchannel/content/ClanShowcase.java