RuneHive-Game: com.runehive.net.ChannelFilter.Connection Class Reference
com.runehive.net.ChannelFilter.Connection Class Reference
Creates a conenction for a host address.
Public Member Functions
void addConnection ()
Adds a connection.
boolean canConnect ()
Checks if this host can connect.
Connection (String host)
Constructs a new Connection object.
boolean equals (Object obj)
int getConnections ()
Gets the amount of connections associated with this host address.
String getHost ()
Gets the host address.
int hashCode ()
void removeConnection ()
Removes a connection.
void setCanConnect (boolean val)
String toString ()
Private Attributes
final AtomicBoolean canConnect = new AtomicBoolean(true)
The stopwatch which caches the time of our last login.
int connections
The amount of connections associated with this host address.
final String host
The host address.
Detailed Description
Creates a conenction for a host address.
Author
Michael | Chex
Definition at line 139 of file ChannelFilter.java.
Constructor & Destructor Documentation
Connection()
com.runehive.net.ChannelFilter.Connection.Connection (String host)
Constructs a new Connection object.
Parameters
host The host address.
Definition at line 156 of file ChannelFilter.java.
{
            this.host = host;
        }
References host.
Referenced by equals().
Member Function Documentation
addConnection()
void com.runehive.net.ChannelFilter.Connection.addConnection ()
Adds a connection.
Definition at line 188 of file ChannelFilter.java.
{
            connections++;
        }
References connections.
Referenced by com.runehive.net.ChannelFilter.channelRegistered().
canConnect()
boolean com.runehive.net.ChannelFilter.Connection.canConnect ()
Checks if this host can connect.
Returns
True if this host can connect.
Definition at line 183 of file ChannelFilter.java.
{
            return canConnect.get();
        }
References canConnect.
equals()
boolean com.runehive.net.ChannelFilter.Connection.equals (Object obj)
Definition at line 207 of file ChannelFilter.java.
{
            if (obj instanceof Connection) {
                Connection other = (Connection) obj;
                return host.equalsIgnoreCase(other.getHost());
            }
            return obj == this;
        }
References Connection(), getHost(), and host.
getConnections()
int com.runehive.net.ChannelFilter.Connection.getConnections ()
Gets the amount of connections associated with this host address.
Returns
The amount of connections associated with this host address.
Definition at line 174 of file ChannelFilter.java.
{
            return connections;
        }
References connections.
Referenced by com.runehive.net.ChannelFilter.channelRegistered(), and com.runehive.net.ChannelFilter.channelUnregistered().
getHost()
String com.runehive.net.ChannelFilter.Connection.getHost ()
Gets the host address.
Returns
The host address.
Definition at line 165 of file ChannelFilter.java.
{
            return host;
        }
References host.
Referenced by com.runehive.net.ChannelFilter.channelRegistered(), com.runehive.net.ChannelFilter.channelUnregistered(), and equals().
hashCode()
int com.runehive.net.ChannelFilter.Connection.hashCode ()
Definition at line 202 of file ChannelFilter.java.
{
            return Objects.hash(host);
        }
References host.
removeConnection()
void com.runehive.net.ChannelFilter.Connection.removeConnection ()
Removes a connection.
Definition at line 193 of file ChannelFilter.java.
{
            connections--;
        }
References connections.
Referenced by com.runehive.net.ChannelFilter.channelUnregistered().
setCanConnect()
void com.runehive.net.ChannelFilter.Connection.setCanConnect (boolean val)
Definition at line 197 of file ChannelFilter.java.
{
            canConnect.compareAndSet(!val, val);
        }
References canConnect.
Referenced by com.runehive.net.ChannelFilter.channelActive(), and com.runehive.net.ChannelFilter.channelRegistered().
toString()
String com.runehive.net.ChannelFilter.Connection.toString ()
Definition at line 216 of file ChannelFilter.java.
{
            return String.format("Connection[host=%s, connections=%s, elapsed=%s]", host, connections, canConnect);
        }
References canConnect, connections, and host.
Member Data Documentation
canConnect
final AtomicBoolean com.runehive.net.ChannelFilter.Connection.canConnect = new AtomicBoolean(true) private
The stopwatch which caches the time of our last login.
Definition at line 142 of file ChannelFilter.java.
Referenced by canConnect(), com.runehive.net.ChannelFilter.channelRegistered(), setCanConnect(), and toString().
connections
int com.runehive.net.ChannelFilter.Connection.connections private
The amount of connections associated with this host address.
Definition at line 148 of file ChannelFilter.java.
Referenced by addConnection(), getConnections(), removeConnection(), and toString().
host
final String com.runehive.net.ChannelFilter.Connection.host private
The host address.
Definition at line 145 of file ChannelFilter.java.
Referenced by Connection(), equals(), getHost(), hashCode(), and toString().
The documentation for this class was generated from the following file:
java/com/runehive/net/ChannelFilter.java