RuneHive-Game: com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect Class Reference
com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect Class Reference
The combat effect applied when a character needs to be venomed.
Public Member Functions
boolean apply (Mob mob)
Applies this effect to mob.
CombatVenomEffect ()
Creates a new CombatVenomEffect.
boolean onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
void process (Mob mob)
Provides processing for this effect on mob.
boolean removeOn (Mob mob)
Removes this effect from mob if needed.
Public Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
CombatEffect (int delay)
Creates a new CombatEffect.
final boolean start (Mob mob)
Starts this combat effect by scheduling a task utilizing the abstract methods in this class.
Static Public Member Functions
static boolean isVenomous (Item weapon)
static boolean isVenomous (Npc npc)
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
static Collection< CombatEffect > values ()
Returns an unmodifiable view of the combat effect listeners.
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
static final Map< CombatEffectType, CombatEffect > EFFECTS = new HashMap<>()
The map of all of the combat effect types mapped to their respective listeners.
Protected Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
final int getDelay ()
Gets the delay for this individual combat effect.
Detailed Description
The combat effect applied when a character needs to be venomed.
Author
lare96 http://github.com/lare96
Definition at line 20 of file CombatVenomEffect.java.
Constructor & Destructor Documentation
CombatVenomEffect()
com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.CombatVenomEffect ()
Creates a new CombatVenomEffect.
Definition at line 23 of file CombatVenomEffect.java.
{
        super(30);
    }
Member Function Documentation
apply()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.apply (Mob mob)
Applies this effect to mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 28 of file CombatVenomEffect.java.
{
        if (mob.isVenomed()) {
            return false;
        }
        if (mob.isNpc() && mob.getNpc().definition.hasVenomImmunity()) {
            return false;
        }
        if (mob.isPlayer() && mob.getPlayer().equipment
                .retrieve(Equipment.HELM_SLOT)
                .filter(helm -> helm.getId() == 13197 || helm.getId() == 13199 || helm.getId() == 12931)
                .isPresent()) {
            return false;
        }
        if (mob.isPlayer()) {
            Player player = mob.getPlayer();
            if (player.getVenomImmunity().get() > 0 || mob.isDead())
                return false;
            player.send(new SendMessage("You have been venomed!"));
            player.send(new SendPoison(SendPoison.PoisonType.VENOM));
        }
        mob.getVenomDamage().set(6);
        return true;
    }
References com.runehive.util.MutableNumber.get(), com.runehive.game.world.entity.mob.player.Player.getVenomImmunity(), com.runehive.game.world.items.containers.equipment.Equipment.HELM_SLOT, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.net.packet.out.SendPoison.PoisonType.VENOM.
isVenomous() [1/2]
boolean com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.isVenomous (Item weapon) static
Definition at line 83 of file CombatVenomEffect.java.
{
        return weapon.matchesId(12_926) || weapon.matchesId(12_904) || weapon.matchesId(12_899);
    }
isVenomous() [2/2]
boolean com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.isVenomous (Npc npc) static
Definition at line 79 of file CombatVenomEffect.java.
{
        return npc.id == 2042 || npc.id == 2043 || npc.id == 2044;
    }
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.attack(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), and com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz().
onLogin()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 72 of file CombatVenomEffect.java.
{
        if (mob.isVenomed() && mob.isPlayer()) {
            mob.getPlayer().send(new SendPoison(SendPoison.PoisonType.REGULAR));
        }
        return mob.isVenomed();
    }
References com.runehive.net.packet.out.SendPoison.PoisonType.REGULAR.
process()
void com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.process (Mob mob)
Provides processing for this effect on mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 66 of file CombatVenomEffect.java.
{
        if (mob.getVenomDamage().get() < 20)
            mob.damage(new Hit(mob.getVenomDamage().getAndIncrement(2), Hitsplat.VENOM, HitIcon.NONE));
    }
References com.runehive.game.world.entity.combat.hit.HitIcon.NONE, and com.runehive.game.world.entity.combat.hit.Hitsplat.VENOM.
removeOn()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.removeOn (Mob mob)
Removes this effect from mob if needed.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 56 of file CombatVenomEffect.java.
{
        boolean remove = !mob.isVenomed() || mob.isDead();
        if (remove && mob.isPlayer()) {
            Player player = (Player) mob;
            player.send(new SendPoison(SendPoison.PoisonType.NO_POISON));
        }
        return remove;
    }
References com.runehive.net.packet.out.SendPoison.PoisonType.NO_POISON, and com.runehive.game.world.entity.mob.player.Player.send().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/effect/impl/CombatVenomEffect.java