RuneHive-Game: com.runehive.content.Obelisks Class Reference
com.runehive.content.Obelisks Class Reference
Created by Daniel on 2017-11-24.
Classes
enum ObeliskData
Public Member Functions
boolean activate (Player player, int objectId)
boolean activate (Player player, int objectId, ObeliskData destination)
void open (Player player, int obj)
Static Public Member Functions
static Obelisks get ()
Static Package Functions
[static initializer]
Static Private Attributes
static Obelisks INSTANCE = new Obelisks()
static Map< Integer, Boolean > state = new HashMap<>()
Detailed Description
Created by Daniel on 2017-11-24.
Definition at line 24 of file Obelisks.java.
Member Function Documentation
[static initializer]()
com.runehive.content.Obelisks.[static initializer] static package
References INSTANCE.
activate() [1/2]
boolean com.runehive.content.Obelisks.activate (Player player, int objectId)
Definition at line 51 of file Obelisks.java.
{
        ObeliskData location = ObeliskData.forObject(objectId);
        return location != null && activate(player, objectId, ObeliskData.getRandom(location));
    }
References activate(), com.runehive.content.Obelisks.ObeliskData.forObject(), and com.runehive.content.Obelisks.ObeliskData.getRandom().
Referenced by activate().
activate() [2/2]
boolean com.runehive.content.Obelisks.activate (Player player, int objectId, ObeliskData destination)
Definition at line 56 of file Obelisks.java.
{
        ObeliskData location = ObeliskData.forObject(objectId);
        if (location == null)
            return false;
        boolean active = state.get(objectId);
        if (active) {
            player.send(new SendMessage("The obelisk is already active, please wait."));
            return true;
        }
        state.put(objectId, true);
        int x = location.getBoundaries().getMinimumX();
        int y = location.getBoundaries().getMinimumY();
        GameObject one = World.getRegions().getRegion(player.getPosition()).getGameObject(objectId, new Position(x, y, player.getHeight()));
        GameObject two = World.getRegions().getRegion(player.getPosition()).getGameObject(objectId, new Position(x + 4, y, player.getHeight()));
        GameObject three = World.getRegions().getRegion(player.getPosition()).getGameObject(objectId, new Position(x, y + 4, player.getHeight()));
        GameObject four = World.getRegions().getRegion(player.getPosition()).getGameObject(objectId, new Position(x + 4, y + 4, player.getHeight()));
        World.schedule(new ObjectReplacementEvent(one, 14825, 15));
        World.schedule(new ObjectReplacementEvent(two, 14825, 15));
        World.schedule(new ObjectReplacementEvent(three, 14825, 15));
        World.schedule(new ObjectReplacementEvent(four, 14825, 15));
        player.attributes.set("OBELISK", -1);
        World.schedule(new Task(14) {
            @Override
            protected void execute() {
                state.put(location.objectId, false);
                Boundary boundary = new Boundary(location.boundary.getMinimumX() + 1, location.boundary.getMinimumY() + 1, location.boundary.getMinimumX() + 3, location.boundary.getMinimumY() + 3);
                List<Player> players = Boundary.getPlayers(boundary);
                if (players.size() > 0) {
                    for (Player p : players) {
                        if (p.isDead())
                            continue;
                        int x = destination.getBoundaries().getMinimumX() + 1;
                        int y = destination.getBoundaries().getMinimumY() + 1;
                        Position position = new Position(x + Utility.random(2), y + Utility.random(2), player.getHeight());
                        Teleportation.activateOverride(p, position, TeleportationData.OBELISK);
                    }
                }
                cancel();
            }
        });
        return true;
    }
References com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride(), com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.Obelisks.ObeliskData.boundary, com.runehive.content.Obelisks.ObeliskData.forObject(), com.runehive.content.Obelisks.ObeliskData.getBoundaries(), com.runehive.game.world.region.Region.getGameObject(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.position.Boundary.getMinimumX(), com.runehive.game.world.position.Boundary.getMinimumY(), com.runehive.game.world.position.Boundary.getPlayers(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.region.RegionManager.getRegion(), com.runehive.game.world.World.getRegions(), com.runehive.content.skill.impl.magic.teleport.TeleportationData.OBELISK, com.runehive.content.Obelisks.ObeliskData.objectId, com.runehive.util.Utility.random(), com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), and state.
get()
Obelisks com.runehive.content.Obelisks.get () static
Definition at line 29 of file Obelisks.java.
{
        return INSTANCE;
    }
open()
void com.runehive.content.Obelisks.open (Player player, int obj)
Definition at line 39 of file Obelisks.java.
{
        if (!PlayerRight.isSuper(player)) {
            player.dialogueFactory.sendStatement("You need to be a super donator to use this feature!").execute();
            return;
        }
        player.attributes.set("OBELISK", obj);
        InterfaceWriter.write(new ObeliskWriter(player));
        player.send(new SendString("Wilderness Obelisk", 51002));
        player.send(new SendString("Click on the obelisk you would like to teleport too", 51003));
        player.interfaceManager.open(51000);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.PlayerRight.isSuper(), com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.util.generic.GenericAttributes.set(), and com.runehive.content.writer.InterfaceWriter.write().
Member Data Documentation
INSTANCE
Obelisks com.runehive.content.Obelisks.INSTANCE = new Obelisks() static private
Definition at line 27 of file Obelisks.java.
Referenced by [static initializer]().
state
Map<Integer, Boolean> com.runehive.content.Obelisks.state = new HashMap<>() static private
Definition at line 26 of file Obelisks.java.
Referenced by activate().
The documentation for this class was generated from the following file:
java/com/runehive/content/Obelisks.java