RuneHive-Game: com.runehive.net.packet.in.UseItemPacketListener Class Reference
com.runehive.net.packet.in.UseItemPacketListener Class Reference
The GamePacket's responsible for an items "use" option.
Public Member Functions
void handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Private Member Functions
void handleItemOnGround (Player player, GamePacket packet)
Handles an randomevent when a player uses the "Use" option of an item with an item on the ground.
void handleItemOnItem (Player player, GamePacket packet)
Handles an randomevent when a player uses the "Use" option of an item with another item in a players inventory.
void handleItemOnNpc (Player player, GamePacket packet)
Handles an randomevent when a player uses the "Use" option of an item with an in-game npc.
void handleItemOnObject (Player player, GamePacket packet)
Handles an randomevent when a player uses the "Use" option of an item with an in-game object.
void handleItemOnPlayer (Player player, GamePacket packet)
Handles an randomevent when a player uses the "Use" option of an item with an in-game player.
Detailed Description
The GamePacket's responsible for an items "use" option.
Author
Daniel
Definition at line 31 of file UseItemPacketListener.java.
Member Function Documentation
handleItemOnGround()
void com.runehive.net.packet.in.UseItemPacketListener.handleItemOnGround (Player player, GamePacket packet) private
Handles an randomevent when a player uses the "Use" option of an item with an item on the ground.
Definition at line 63 of file UseItemPacketListener.java.
{
        final int a1 = packet.readShort(ByteOrder.LE);
        final int itemUsed = packet.readShort(false, ByteModification.ADD);
        final int groundItem = packet.readShort();
        final int gItemY = packet.readShort(false, ByteModification.ADD);
        final int itemUsedSlot = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        final int gItemX = packet.readShort();
        if (PlayerRight.isDeveloper(player)) {
            player.send(new SendMessage("[ItemUsed] - " + itemUsed + " groundItem: " + groundItem + " itemUsedSlot: " + itemUsedSlot + " gItemX: " + gItemX + " gItemY: " + gItemY + " a1: " + a1, MessageColor.DEVELOPER));
        }
        player.send(new SendMessage("Nothing interesting happens."));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.util.MessageColor.DEVELOPER, com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), com.runehive.net.codec.ByteOrder.LE, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by handlePacket().
handleItemOnItem()
void com.runehive.net.packet.in.UseItemPacketListener.handleItemOnItem (Player player, GamePacket packet) private
Handles an randomevent when a player uses the "Use" option of an item with another item in a players inventory.
Definition at line 82 of file UseItemPacketListener.java.
{
        final int usedWithSlot = packet.readShort();
        final int itemUsedSlot = packet.readShort(ByteModification.ADD);
        final Item used = player.inventory.get(itemUsedSlot);
        final Item with = player.inventory.get(usedWithSlot);
        if (used != null && with != null) {
            if (EventDispatcher.execute(player, new ItemOnItemInteractionEvent(used, with, usedWithSlot, itemUsedSlot))) {
                return;
            }
            if (ItemActionRepository.itemOnItem(player, used, with)) {
                return;
            }
            if (PluginManager.getDataBus().publish(player, new ItemOnItemEvent(used, itemUsedSlot, with, usedWithSlot))) {
                return;
            }
            player.send(new SendMessage("Nothing interesting happens."));
        }
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.itemaction.ItemActionRepository.itemOnItem(), com.runehive.game.event.bus.PlayerDataBus.publish(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by handlePacket().
handleItemOnNpc()
void com.runehive.net.packet.in.UseItemPacketListener.handleItemOnNpc (Player player, GamePacket packet) private
Handles an randomevent when a player uses the "Use" option of an item with an in-game npc.
Definition at line 109 of file UseItemPacketListener.java.
{
        final int itemId = packet.readShort(false, ByteModification.ADD);
        final int index = packet.readShort(false, ByteModification.ADD);
        final int slot = packet.readShort(ByteOrder.LE);
        player.getEvents().interact(player, new ItemOnNpcEvent(itemId, index, slot));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.player.Player.getEvents(), and com.runehive.net.codec.ByteOrder.LE.
Referenced by handlePacket().
handleItemOnObject()
void com.runehive.net.packet.in.UseItemPacketListener.handleItemOnObject (Player player, GamePacket packet) private
Handles an randomevent when a player uses the "Use" option of an item with an in-game object.
Definition at line 121 of file UseItemPacketListener.java.
{
        int interfaceType = packet.readShort();
        final int objectId = packet.readShort(ByteOrder.LE);
        final int y = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        final int slot = packet.readShort(ByteOrder.LE);
        final int x = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        final int itemId = packet.readShort();
        player.getEvents().interact(player, new ItemOnObjectEvent(
                interfaceType, itemId, slot, objectId, x, y
        ));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.player.Player.getEvents(), and com.runehive.net.codec.ByteOrder.LE.
Referenced by handlePacket().
handleItemOnPlayer()
void com.runehive.net.packet.in.UseItemPacketListener.handleItemOnPlayer (Player player, GamePacket packet) private
Handles an randomevent when a player uses the "Use" option of an item with an in-game player.
Definition at line 138 of file UseItemPacketListener.java.
{
        final int interfaceId = packet.readShort(ByteModification.ADD);
        final int slot = packet.readShort();
        final int item = packet.readShort();
        final int itemSlot = packet.readShort(ByteOrder.LE);
        if (interfaceId != Inventory.INVENTORY_DISPLAY_ID) {
            return;
        }
        player.getEvents().interact(player, new ItemOnPlayerEvent(
                interfaceId, item, itemSlot, slot
        ));
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.player.Player.getEvents(), com.runehive.game.world.items.containers.inventory.Inventory.INVENTORY_DISPLAY_ID, and com.runehive.net.codec.ByteOrder.LE.
Referenced by handlePacket().
handlePacket()
void com.runehive.net.packet.in.UseItemPacketListener.handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Parameters
player The player receiving this packet.
packet The packet that has been received.
Implements com.runehive.net.packet.PacketListener.
Definition at line 34 of file UseItemPacketListener.java.
{
        if (player.isDead())
            return;
        if (player.locking.locked(PacketType.USE_ITEM))
            return;
        switch (packet.getOpcode()) {
            case ClientPackets.ITEM_ON_GROUND_ITEM:
                handleItemOnGround(player, packet);
                break;
            case ClientPackets.ITEM_ON_ITEM:
                handleItemOnItem(player, packet);
                break;
            case ClientPackets.ITEM_ON_NPC:
                handleItemOnNpc(player, packet);
                break;
            case ClientPackets.ITEM_ON_OBJECT:
                handleItemOnObject(player, packet);
                break;
            case ClientPackets.ITEM_ON_PLAYER:
                handleItemOnPlayer(player, packet);
                break;
        }
    }
References handleItemOnGround(), handleItemOnItem(), handleItemOnNpc(), handleItemOnObject(), handleItemOnPlayer(), com.runehive.game.world.entity.mob.Mob.isDead(), com.runehive.net.packet.ClientPackets.ITEM_ON_GROUND_ITEM, com.runehive.net.packet.ClientPackets.ITEM_ON_ITEM, com.runehive.net.packet.ClientPackets.ITEM_ON_NPC, com.runehive.net.packet.ClientPackets.ITEM_ON_OBJECT, com.runehive.net.packet.ClientPackets.ITEM_ON_PLAYER, com.runehive.game.world.entity.mob.Locking.locked(), com.runehive.game.world.entity.mob.Mob.locking, and com.runehive.game.world.entity.mob.data.PacketType.USE_ITEM.
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/in/UseItemPacketListener.java