RuneHive-Game: com.runehive.net.session.GameSession Class Reference
com.runehive.net.session.GameSession Class Reference
Represents a Session when a Player has been authenticated and active in the game world.
Public Member Functions
Player getPlayer ()
void handleClientPacket (Object o)
The method that is called when the client sends packets to the server.
void processClientPackets ()
void processServerPacketQueue ()
void queueServerPacket (GamePacket packet)
Public Member Functions inherited from com.runehive.net.session.Session
final void close ()
The method to close this session.
Channel getChannel ()
Gets the underlying Channel for this Session.
String getHost ()
Gets the users host address.
Session (Channel channel)
Creates a new Session.
Protected Member Functions
void onClose (ChannelFuture f)
The method called after a session has been closed.
Package Functions
GameSession (Channel channel, Player player)
Private Member Functions
void queueClientPacket (final GamePacket packet)
Private Attributes
final MessagePassingQueue< GamePacket > incomingPackets = new MpscArrayQueue<>(Config.CLIENT_PACKET_THRESHOLD)
final MessagePassingQueue< GamePacket > outgoingPackets = new MpscArrayQueue<>(Config.SERVER_PACKET_THRESHOLD)
final Player player
Static Private Attributes
static final Logger logger = LogManager.getLogger(GameSession.class)
Additional Inherited Members
Protected Attributes inherited from com.runehive.net.session.Session
final Channel channel
The channel attached to this session.
final String host
The users host address.
Detailed Description
Represents a Session when a Player has been authenticated and active in the game world.
Author
nshusa
Definition at line 21 of file GameSession.java.
Constructor & Destructor Documentation
GameSession()
com.runehive.net.session.GameSession.GameSession (Channel channel, Player player) package
Definition at line 33 of file GameSession.java.
{
        super(channel);
        this.player = player;
    }
References com.runehive.net.session.Session.channel, and player.
Member Function Documentation
getPlayer()
Player com.runehive.net.session.GameSession.getPlayer ()
Definition at line 103 of file GameSession.java.
{
        return player;
    }
References player.
handleClientPacket()
void com.runehive.net.session.GameSession.handleClientPacket (Object o)
The method that is called when the client sends packets to the server.
Parameters
o The vague object packet.
Reimplemented from com.runehive.net.session.Session.
Definition at line 39 of file GameSession.java.
{
        if (o instanceof GamePacket) {
            queueClientPacket((GamePacket) o);
        }
    }
References queueClientPacket().
onClose()
void com.runehive.net.session.GameSession.onClose (ChannelFuture future) protected
The method called after a session has been closed.
Parameters
future The result of the session being closed.
Reimplemented from com.runehive.net.session.Session.
Definition at line 46 of file GameSession.java.
{
        World.queueLogout(player);
    }
References player, and com.runehive.game.world.World.queueLogout().
processClientPackets()
void com.runehive.net.session.GameSession.processClientPackets ()
Definition at line 54 of file GameSession.java.
{
        final MessagePassingQueue<GamePacket> incomingPackets = this.incomingPackets;
        final Player player = this.player;
        for (int i = 0; i < Config.CLIENT_PACKET_THRESHOLD; i++) {
            final GamePacket packet = incomingPackets.poll();
            if (packet == null) break;
            try {
                PacketRepository.sendToListener(player, packet);
            } catch (Exception ex) {
                logger.error(String.format("error processing client packet for %s", player), ex);
            } finally {
                packet.release();
            }
        }
    }
References com.runehive.Config.CLIENT_PACKET_THRESHOLD, incomingPackets, logger, player, and com.runehive.net.packet.PacketRepository.sendToListener().
Referenced by com.runehive.game.engine.sync.task.PlayerPreUpdateTask.run().
processServerPacketQueue()
void com.runehive.net.session.GameSession.processServerPacketQueue ()
Definition at line 76 of file GameSession.java.
{
        final Channel channel = this.channel;
        final boolean channelActive = channel.isActive();
        final MessagePassingQueue<GamePacket> outgoingPackets = this.outgoingPackets;
        int count = 0;
        for (; count < Config.SERVER_PACKET_THRESHOLD; count++) {
            final GamePacket packet = outgoingPackets.poll();
            if (packet == null) break;
            if (channelActive) {
                try {
                    channel.write(packet, channel.voidPromise());
                } catch (final Exception ex) {
                    logger.error(String.format("error writing packet %s for %s", packet, player));
                }
            } else {
                if (packet.refCnt() > 0) {
                    packet.release();
                }
            }
        }
        if (channelActive && count > 0) {
            channel.flush();
        }
    }
References com.runehive.net.session.Session.channel, logger, outgoingPackets, player, and com.runehive.Config.SERVER_PACKET_THRESHOLD.
Referenced by com.runehive.game.engine.sync.task.PlayerPostUpdateTask.run().
queueClientPacket()
void com.runehive.net.session.GameSession.queueClientPacket (final GamePacket packet) private
Definition at line 50 of file GameSession.java.
{
        incomingPackets.offer(packet);
    }
References incomingPackets.
Referenced by handleClientPacket().
queueServerPacket()
void com.runehive.net.session.GameSession.queueServerPacket (GamePacket packet)
Definition at line 72 of file GameSession.java.
{
        outgoingPackets.offer(packet);
    }
References outgoingPackets.
Member Data Documentation
incomingPackets
final MessagePassingQueue<GamePacket> com.runehive.net.session.GameSession.incomingPackets = new MpscArrayQueue<>(Config.CLIENT_PACKET_THRESHOLD) private
Definition at line 27 of file GameSession.java.
Referenced by processClientPackets(), and queueClientPacket().
logger
final Logger com.runehive.net.session.GameSession.logger = LogManager.getLogger(GameSession.class) static private
Definition at line 23 of file GameSession.java.
Referenced by processClientPackets(), and processServerPacketQueue().
outgoingPackets
final MessagePassingQueue<GamePacket> com.runehive.net.session.GameSession.outgoingPackets = new MpscArrayQueue<>(Config.SERVER_PACKET_THRESHOLD) private
Definition at line 30 of file GameSession.java.
Referenced by processServerPacketQueue(), and queueServerPacket().
player
final Player com.runehive.net.session.GameSession.player private
Definition at line 25 of file GameSession.java.
Referenced by GameSession(), getPlayer(), onClose(), processClientPackets(), and processServerPacketQueue().
The documentation for this class was generated from the following file:
java/com/runehive/net/session/GameSession.java