RuneHive-Game: com.runehive.content.WellOfGoodwill Class Reference
com.runehive.content.WellOfGoodwill Class Reference
Handles contribution towards the well of goodwill.
Classes
class Contributor
Static Public Member Functions
static void activate ()
Handles activating the well.
static void add (String name, PlayerRight rank, int amount)
static void contribute (Player player, int amount)
Handles contributing to the well.
static String getInformation ()
The information displayed on information tab.
static String isActivated ()
static boolean isActive ()
static void open (Player player)
Opens the well itemcontainer.
Static Public Attributes
static boolean active
static int activeTime = -1
static int CONTRIBUTION
The current contribution amount for the well.
static TreeSet< Contributor > contributors = new TreeSet<>()
The array list of contributors.
static String lastContributor
The last contributor to the well.
static final int MAXIMUM = 15_000_000
The maximum contribution limit for the well.
Detailed Description
Handles contribution towards the well of goodwill.
Author
Daniel.
Definition at line 24 of file WellOfGoodwill.java.
Member Function Documentation
activate()
void com.runehive.content.WellOfGoodwill.activate () static
Handles activating the well.
Definition at line 118 of file WellOfGoodwill.java.
{
        activeTime = 0;
        World.schedule(new DoubleExperienceEvent());
        World.sendMessage("<col=2b58a0>WOG</col>: The well has been fully replenished. 30 minutes of double XP is active.");
        active = true;
    }
References active, activeTime, com.runehive.game.world.World.schedule(), and com.runehive.game.world.World.sendMessage().
Referenced by contribute().
add()
void com.runehive.content.WellOfGoodwill.add (String name, PlayerRight rank, int amount) static
Definition at line 125 of file WellOfGoodwill.java.
{
        Contributor contributor = new Contributor(name, rank, amount);
        for (Iterator<Contributor> iterator = contributors.iterator(); iterator.hasNext(); ) {
            Contributor other = iterator.next();
            if (contributor.name.equals(other.name)) {
                contributor.add(other.contribution);
                iterator.remove();
                break;
            }
        }
        contributors.add(contributor);
    }
References com.runehive.content.WellOfGoodwill.Contributor.add(), com.runehive.content.WellOfGoodwill.Contributor.contribution, contributors, and com.runehive.content.WellOfGoodwill.Contributor.name.
Referenced by contribute(), and com.runehive.util.GameSaver.load().
contribute()
void com.runehive.content.WellOfGoodwill.contribute (Player player, int amount) static
Handles contributing to the well.
Definition at line 71 of file WellOfGoodwill.java.
{
     /*   if (PlayerRight.isAdministrator(player)) {
            player.message("Administrators cannot contribute.");
            return;
        }
*/
        if (Config.DOUBLE_EXPERIENCE) {
            player.message("Double experience is currently active which has temporarily disabled the wog.");
            return;
        }
        if (amount < 100_000) {
            player.message("You must contribute at least 100k into the well.");
            return;
        }
        if (isActive()) {
            player.message("The well is currently active and does not need", "any contribution.");
            return;
        }
        if (amount > MAXIMUM - CONTRIBUTION) {
            amount = MAXIMUM - CONTRIBUTION;
        }
        if (!player.inventory.contains(new Item(995, amount))) {
            player.message("You do not have the required funds to contribute!");
            return;
        }
        player.inventory.remove(new Item(995, amount));
        CONTRIBUTION += amount;
        add(player.getName(), player.right, amount);
        lastContributor = PlayerRight.getCrown(player) + " <col=ffb83f>" + player.getName() + "</col> (" + Utility.formatDigits(amount) + ")";
        player.message("Thank you! Your contribution of " + Utility.formatDigits(amount) + "gp to the well is appreciated!");
        if (amount >= 250000) {
            World.sendMessage("<col=2b58a0>WOG</col>: " + PlayerRight.getCrown(player) + "<col=2b58a0>" + player.getName() + "</col> has just contributed <col=2b58a0>" + Utility.formatDigits(amount) + "</col> coins.");
        }
        if (CONTRIBUTION >= MAXIMUM) activate();
        open(player);
    }
References activate(), add(), com.runehive.game.world.items.containers.ItemContainer.contains(), CONTRIBUTION, com.runehive.Config.DOUBLE_EXPERIENCE, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, isActive(), lastContributor, MAXIMUM, com.runehive.game.world.entity.mob.player.Player.message(), open(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.right, and com.runehive.game.world.World.sendMessage().
getInformation()
String com.runehive.content.WellOfGoodwill.getInformation () static
The information displayed on information tab.
Definition at line 188 of file WellOfGoodwill.java.
{
        return !active ? "Not Active" : isActivated();
    }
References active, and isActivated().
isActivated()
String com.runehive.content.WellOfGoodwill.isActivated () static
Definition at line 141 of file WellOfGoodwill.java.
{
        return "Active";
    }
Referenced by getInformation().
isActive()
boolean com.runehive.content.WellOfGoodwill.isActive () static
Definition at line 138 of file WellOfGoodwill.java.
{
        return activeTime != -1;
    }
References activeTime.
Referenced by com.runehive.game.world.entity.skill.SkillManager.addExperience(), contribute(), com.runehive.game.task.impl.DoubleExperienceEvent.execute(), com.runehive.RuneHive.onStart(), open(), and com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues().
open()
void com.runehive.content.WellOfGoodwill.open (Player player) static
Opens the well itemcontainer.
Definition at line 44 of file WellOfGoodwill.java.
{
        int progress = (int) Utility.getPercentageAmount(CONTRIBUTION, MAXIMUM);
        int id = 43708;
        int count = 0;
        Iterator<Contributor> iterator = contributors.iterator();
        while (count++ < 3 && iterator.hasNext()) {
            Contributor contributor = iterator.next();
            String rank = contributor.rank.getCrownText();
            player.send(new SendString("Latest contributor:", 43711));
            player.send(new SendString(rank + "<col=ffb83f>" + contributor.name + "</col> (" + Utility.formatDigits(contributor.contribution) + ")", id++));
        }
        for (int index = count; index < 3; index++) {
            player.send(new SendString("", id + index));
        }
        if (isActive())
            player.send(new SendMessage("The well will be active for " + (30 - activeTime) + " minutes."));
        player.send(new SendProgressBar(43706, progress));
        player.send(new SendString(lastContributor == null ? "" : lastContributor, 43712));
        player.send(new SendString(progress + "%", 43717));
        player.interfaceManager.open(43700);
    }
References activeTime, CONTRIBUTION, com.runehive.content.WellOfGoodwill.Contributor.contribution, contributors, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrownText(), com.runehive.util.Utility.getPercentageAmount(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, isActive(), lastContributor, MAXIMUM, com.runehive.content.WellOfGoodwill.Contributor.name, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.content.WellOfGoodwill.Contributor.rank, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by contribute(), and com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues().
Member Data Documentation
active
boolean com.runehive.content.WellOfGoodwill.active static
Definition at line 30 of file WellOfGoodwill.java.
Referenced by activate(), and getInformation().
activeTime
int com.runehive.content.WellOfGoodwill.activeTime = -1 static
Definition at line 29 of file WellOfGoodwill.java.
Referenced by activate(), com.runehive.game.task.impl.DoubleExperienceEvent.execute(), isActive(), com.runehive.util.GameSaver.load(), com.runehive.game.task.impl.DoubleExperienceEvent.onCancel(), open(), com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues(), and com.runehive.util.GameSaver.toJson().
CONTRIBUTION
int com.runehive.content.WellOfGoodwill.CONTRIBUTION static
The current contribution amount for the well.
Definition at line 27 of file WellOfGoodwill.java.
Referenced by contribute(), com.runehive.util.GameSaver.load(), com.runehive.game.task.impl.DoubleExperienceEvent.onCancel(), open(), and com.runehive.util.GameSaver.toJson().
contributors
TreeSet<Contributor> com.runehive.content.WellOfGoodwill.contributors = new TreeSet<>() static
The array list of contributors.
Definition at line 34 of file WellOfGoodwill.java.
Referenced by add(), open(), and com.runehive.util.GameSaver.toJson().
lastContributor
String com.runehive.content.WellOfGoodwill.lastContributor static
The last contributor to the well.
Definition at line 37 of file WellOfGoodwill.java.
Referenced by contribute(), com.runehive.util.GameSaver.load(), open(), and com.runehive.util.GameSaver.toJson().
MAXIMUM
final int com.runehive.content.WellOfGoodwill.MAXIMUM = 15_000_000 static
The maximum contribution limit for the well.
Definition at line 41 of file WellOfGoodwill.java.
Referenced by contribute(), open(), and com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues().
The documentation for this class was generated from the following file:
java/com/runehive/content/WellOfGoodwill.java