RuneHive-Game: com.runehive.content.dailyeffect.DailyEffect Class Reference
com.runehive.content.dailyeffect.DailyEffect Class Reference abstract
Public Member Functions
boolean canUse (Player player)
abstract int maxUses (Player player)
int remainingUses (Player player)
void use ()
Private Attributes
int dayUsed
int uses
Detailed Description
Definition at line 6 of file DailyEffect.java.
Member Function Documentation
canUse()
boolean com.runehive.content.dailyeffect.DailyEffect.canUse (Player player)
Definition at line 18 of file DailyEffect.java.
{
        if (dayUsed == Utility.getCurrentDay()) {
            if (uses >= maxUses(player)) {
                player.dialogueFactory.sendStatement("You must wait until tomorrow before you can use this option again.").execute();
                return false;
            }
        } else {
            uses = 0;
        }
        return true;
    }
References dayUsed, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.util.Utility.getCurrentDay(), maxUses(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and uses.
maxUses()
abstract int com.runehive.content.dailyeffect.DailyEffect.maxUses (Player player) abstract
Reimplemented in com.runehive.content.dailyeffect.impl.DailySlayerTaskSkip, com.runehive.content.dailyeffect.impl.DailySlayerTaskTeleport, and com.runehive.content.dailyeffect.impl.DailySpellBookSwap.
Referenced by canUse(), and remainingUses().
remainingUses()
int com.runehive.content.dailyeffect.DailyEffect.remainingUses (Player player)
Definition at line 30 of file DailyEffect.java.
{
        return (maxUses(player) - uses);
    }
References maxUses(), and uses.
use()
void com.runehive.content.dailyeffect.DailyEffect.use ()
Definition at line 11 of file DailyEffect.java.
                      {
        if (uses == 0) {
            dayUsed = Utility.getCurrentDay();
        }
        uses++;
    }
References dayUsed, com.runehive.util.Utility.getCurrentDay(), and uses.
Member Data Documentation
dayUsed
int com.runehive.content.dailyeffect.DailyEffect.dayUsed private
Definition at line 9 of file DailyEffect.java.
Referenced by canUse(), and use().
uses
int com.runehive.content.dailyeffect.DailyEffect.uses private
Definition at line 8 of file DailyEffect.java.
Referenced by canUse(), remainingUses(), and use().
The documentation for this class was generated from the following file:
java/com/runehive/content/dailyeffect/DailyEffect.java