RuneHive-Game: com.runehive.content.skill.impl.farming.zones.FarmingZone Class Reference
com.runehive.content.skill.impl.farming.zones.FarmingZone Class Reference
A zone that manages farming patches.
Public Member Functions
boolean clickObject (GameObject object, int opcode)
Handles clicking a farming patch.
void fromJson (JsonArray array)
boolean isViewable (Position position)
Checks if a position can see this farming zone.
boolean itemOnObject (GameObject object, Item item, int slot)
Handles using an item on a farming patch.
final void sendPatchConfigs (Player player)
Sends the configs of this zone to the player's client.
final void tick ()
Ticks the farming patches in this zone.
JsonArray toJson ()
Package Functions
FarmingZone (Interactable boundary, int size)
Constructs a new farming zone.
void setPatch (int index, FarmingPatch patch)
Sets a farming patch in this zone.
Private Attributes
final Interactable boundary
The boundary of this zone.
final FarmingPatch[] patches
The patches in this zone.
Static Private Attributes
static final int PATCH_CONFIG = 529
The config id of all the patches.
Detailed Description
A zone that manages farming patches.
Author
Michael | Chex
Definition at line 21 of file FarmingZone.java.
Constructor & Destructor Documentation
FarmingZone()
com.runehive.content.skill.impl.farming.zones.FarmingZone.FarmingZone (Interactable boundary, int size) package
Constructs a new farming zone.
Parameters
size the amount of patches in this zone
Definition at line 37 of file FarmingZone.java.
{
        this.boundary = boundary;
        patches = new FarmingPatch[size];
    }
References boundary, and patches.
Member Function Documentation
clickObject()
boolean com.runehive.content.skill.impl.farming.zones.FarmingZone.clickObject (GameObject object, int opcode)
Handles clicking a farming patch.
Parameters
object the object that was clicked
opcode the click opcode (starting at 1)
Returns
true if the object was a patch
Definition at line 59 of file FarmingZone.java.
{
        boolean success = false;
        for (FarmingPatch patch : patches) {
            if (patch.within(object.getPosition())) {
                success |= patch.clickObject(opcode);
            }
        }
        return success;
    }
References patches.
Referenced by com.runehive.content.skill.impl.farming.Farming.firstClickObject(), and com.runehive.content.skill.impl.farming.Farming.secondClickObject().
fromJson()
void com.runehive.content.skill.impl.farming.zones.FarmingZone.fromJson (JsonArray array)
Definition at line 130 of file FarmingZone.java.
{
        int index = 0;
        for (JsonElement element : array) {
            patches[index++].fromJson((JsonObject) element);
        }
    }
References patches.
isViewable()
boolean com.runehive.content.skill.impl.farming.zones.FarmingZone.isViewable (Position position)
Checks if a position can see this farming zone.
Parameters
position the position to check
Returns
true if the zone is viewable from the position
Definition at line 118 of file FarmingZone.java.
{
        return Utility.inside(boundary, position) || Utility.withinDistance(boundary, position, Region.SIZE);
    }
References boundary, com.runehive.util.Utility.inside(), com.runehive.game.world.region.Region.SIZE, and com.runehive.util.Utility.withinDistance().
Referenced by com.runehive.content.skill.impl.farming.Farming.firstClickObject(), com.runehive.content.skill.impl.farming.Farming.itemOnObject(), com.runehive.content.skill.impl.farming.Farming.secondClickObject(), and sendPatchConfigs().
itemOnObject()
boolean com.runehive.content.skill.impl.farming.zones.FarmingZone.itemOnObject (GameObject object, Item item, int slot)
Handles using an item on a farming patch.
Parameters
object the object an item was used on
item the item used on the object
slot the inventory index of the item
Returns
true if the item used on the patch was a farming event
Definition at line 77 of file FarmingZone.java.
{
        boolean success = false;
        for (FarmingPatch patch : patches) {
            if (patch.within(object.getPosition())) {
                success |= patch.itemOnObject(item, slot);
            }
        }
        return success;
    }
References patches.
Referenced by com.runehive.content.skill.impl.farming.Farming.itemOnObject().
sendPatchConfigs()
final void com.runehive.content.skill.impl.farming.zones.FarmingZone.sendPatchConfigs (Player player)
Sends the configs of this zone to the player's client.
Parameters
player the player to send the config to
Definition at line 92 of file FarmingZone.java.
{
        if (!isViewable(player.getPosition())) {
            return;
        }
        int config = 0;
        for (int index = 0; index < patches.length; index++) {
            config |= patches[index].getConfig() << (index << 3);
        }
        player.send(new SendConfig(PATCH_CONFIG, config));
    }
References com.runehive.game.world.entity.Entity.getPosition(), isViewable(), PATCH_CONFIG, patches, and com.runehive.game.world.entity.mob.player.Player.send().
setPatch()
void com.runehive.content.skill.impl.farming.zones.FarmingZone.setPatch (int index, FarmingPatch patch) package
Sets a farming patch in this zone.
Parameters
index the index of the farming patch
patch the patch to set
Definition at line 48 of file FarmingZone.java.
{
        patches[index] = patch;
    }
References patches.
Referenced by com.runehive.content.skill.impl.farming.zones.ArdougneZone.ArdougneZone(), com.runehive.content.skill.impl.farming.zones.CatherbyZone.CatherbyZone(), com.runehive.content.skill.impl.farming.zones.FaladorZone.FaladorZone(), and com.runehive.content.skill.impl.farming.zones.PhasmatyZone.PhasmatyZone().
tick()
final void com.runehive.content.skill.impl.farming.zones.FarmingZone.tick ()
Ticks the farming patches in this zone.
Definition at line 106 of file FarmingZone.java.
{
        for (FarmingPatch patch : patches) {
            patch.tick();
        }
    }
References patches.
Referenced by com.runehive.content.skill.impl.farming.Farming.tick().
toJson()
JsonArray com.runehive.content.skill.impl.farming.zones.FarmingZone.toJson ()
Definition at line 122 of file FarmingZone.java.
{
        JsonArray array = new JsonArray();
        for (FarmingPatch patch : patches) {
            array.add(patch.toJson());
        }
        return array;
    }
References patches.
Member Data Documentation
boundary
final Interactable com.runehive.content.skill.impl.farming.zones.FarmingZone.boundary private
The boundary of this zone.
Definition at line 27 of file FarmingZone.java.
Referenced by FarmingZone(), and isViewable().
PATCH_CONFIG
final int com.runehive.content.skill.impl.farming.zones.FarmingZone.PATCH_CONFIG = 529 static private
The config id of all the patches.
Definition at line 24 of file FarmingZone.java.
Referenced by sendPatchConfigs().
patches
final FarmingPatch [] com.runehive.content.skill.impl.farming.zones.FarmingZone.patches private
The patches in this zone.
Definition at line 30 of file FarmingZone.java.
Referenced by clickObject(), FarmingZone(), fromJson(), itemOnObject(), sendPatchConfigs(), setPatch(), tick(), and toJson().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/farming/zones/FarmingZone.java