RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian Class Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian Class Reference
Public Member Functions
void sequence ()
Public Member Functions inherited from com.runehive.game.world.entity.mob.npc.Npc
void addToRegion (Region region)
Adds this entity to the specified region.
void appendDeath ()
Handles the mob death.
boolean equals (Object obj)
int getBonus (int index)
int[] getBonuses ()
Combat< Npc > getCombat ()
The combat of the mob.
String getName ()
Gets the name of this entity.
int getPriorityIndex ()
CombatStrategy< Npc > getStrategy ()
The combat strategy of the mob.
EntityType getType ()
Gets the EntityType.
int hashCode ()
boolean isAutoRetaliate ()
State of the mob's auto retaliate.
Npc (int id, int instance, Position position)
Npc (int id, Position position)
Npc (int id, Position position, int walkingRadius, Direction direction)
Npc (int id, Position position, int walkingRadius, int instance, Direction direction)
void onStep ()
void register ()
Registers an entity to the World.
void removeFromRegion (Region region)
Removes this entity from the specified region.
void setStrategy (CombatStrategy< Npc > strategy)
String toString ()
void unregister ()
Unregisters an entity from the World.
Public Member Functions inherited from com.runehive.game.world.entity.mob.Mob
void animate (Animation animation)
Plays an animation.
void animate (Animation animation, final boolean override)
Plays an animation.
void animate (int animation)
void animate (int animation, boolean override)
void appendBonus (int index, int amount)
void attack (Mob target)
void clearTeleportTarget ()
Resets the teleport target.
void damage (Hit... hits)
Hit decrementHealth (Hit hit)
void face (Direction direction)
Sets the client update flag to face a certain direction.
void face (GameObject object)
Sets the client update flag to face a certain direction.
void face (Mob mob)
void face (Position position)
Sets the client update flag to face a certain direction.
void follow (Mob target)
void forceMove (int animation, int x, int y)
void forceMove (int delay, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
void forceMove (int delay, int delay2, int animation, int animationDelay, int startSpeed, int endSpeed, Position offset, Direction direction)
Creates a force movement action for an entity.
void forceMove (int delay, int delay2, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
Optional< Animation > getAnimation ()
int getCurrentHealth ()
ForceMovement getForceMovement ()
Optional< Graphic > getGraphic ()
int getId ()
int getListIndex ()
int getMaximumHealth ()
final Npc getNpc ()
final Player getPlayer ()
final MutableNumber getPoisonDamage ()
PoisonType getPoisonType ()
int getTransformId ()
MutableNumber getVenomDamage ()
void graphic (Graphic graphic)
Plays a graphic.
void graphic (Graphic graphic, boolean override)
Plays a graphic.
void graphic (int graphic)
boolean hasPriorityIndex (Mob other)
void heal (int amount)
boolean inActivity ()
boolean inActivity (ActivityType type)
void interact (Mob mob)
Sets the mob interacting with another mob.
boolean isDead ()
boolean isFixingInside ()
final boolean isNpc ()
Check if an entity is an npc.
final boolean isNpc (BooleanInterface< Npc > condition)
Check if an entity is an npc.
final boolean isPlayer ()
Check if an entity is a player.
final boolean isPlayer (Function< Player, Boolean > condition)
Check if an entity is a player.
final boolean isPoisoned ()
boolean isUpdateRequired ()
Checks if mob requires an update.
final boolean isVenomed ()
Mob (Position position)
Constructs a new Mob.
Mob (Position position, boolean visible)
void move (Position position)
Moves the mob to a set position.
void poison (PoisonType type)
Applies poison with an intensity of type to the entity.
final void reset ()
Resets the mob after an update.
void resetAnimation ()
void resetFace ()
Resets the mob's face location.
void resetGraphic ()
final void resetWaypoint ()
Resets the waypoint.
void runTo (Position destination)
void setActivity (Activity activity)
void setBonus (int equipSlot, int bonus)
void setBonuses (int[] bonuses)
void setDead (boolean dead)
void setFixingInside (boolean fixingInside)
void setForceMovement (ForceMovement forceMovement)
void setListIndex (int listIndex)
void speak (String forceChat)
Sets the mob's forced chat.
void takeStep ()
void transform (int transformId)
void transform (int transformId, boolean reload)
Transforms the mob.
void unpoison ()
void unvenom ()
void venom ()
Applies venom to the entity.
void walk (Position destination, boolean ignoreClip)
void walk (Position position)
void walkExactlyTo (Position position)
void walkExactlyTo (Position position, Runnable onDestination)
void walkTo (Interactable target, boolean clearAction, Runnable onDestination)
void walkTo (Interactable target, Runnable onDestination)
void walkTo (Position position)
void walkTo (Position position, Runnable onDestination)
void writeDamage (Hit hit)
void writeFakeDamage (Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.Entity
Entity (Position position)
Entity (Position position, boolean visible)
Position getCenterPosition ()
int getHeight ()
int getIndex ()
Position getPosition ()
Region getRegion ()
int getX ()
int getY ()
boolean is (EntityType type)
final boolean isCustomObject ()
Check if an entity is an object.
final boolean isRegistered ()
final boolean isStaticObject ()
Check if an entity is an object.
boolean isValid ()
Validates this npc based on its current region and registered state.
boolean isVisible ()
int length ()
void setIndex (int index)
void setLength (int length)
void setPosition (Position position)
void setVisible (boolean visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
void setZ (int z)
int width ()
Private Member Functions
Guardian (Position spawn, Npc scorpia)
Private Attributes
final Stopwatch lastHeal = Stopwatch.createStarted()
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.mob.Mob
static boolean pathfinderProjectiles (Mob source)
Static Public Member Functions inherited from com.runehive.game.world.Interactable
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Public Attributes inherited from com.runehive.game.world.entity.mob.npc.Npc
final AtomicInteger atomicPlayerCount = new AtomicInteger(0)
Position[] boundaries
boolean canAttack
NpcDefinition definition
final Direction faceDirection
final NpcAssistant npcAssistant = new NpcAssistant(this)
Mob owner
int pyroHealth = 24
Pyromancer data.
boolean pyroSnowAttack
final Position spawnPosition
boolean walk
int walkingRadius
Public Attributes inherited from com.runehive.game.world.entity.mob.Mob
ActionManager action = new ActionManager()
Activity activity
final GenericAttributes attributes = new GenericAttributes()
boolean blockFace
boolean blockInteract
Stopwatch damageImmunity = Stopwatch.start()
Position facePosition
Hit firstHit
List< Mob > followers = new LinkedList<>()
String forceChat
ForceMovement forceMovement
boolean forceWalking
final Stopwatch freezeImmunity = Stopwatch.start()
int id = -1
boolean inTeleport
Mob interactingWith
Position lastPosition
final Locking locking = new Locking(this)
MobAnimation mobAnimation = new MobAnimation(updateFlags)
final Movement movement = new Movement(this)
transient long nextAnimation
boolean pathfinderProjectiles = false
boolean positionChange
PrayerBook prayer = new PrayerBook()
boolean regionChange
Hit secondHit
final SkillManager skills = new SkillManager(this)
final SkillManager skills_copy = new SkillManager(this)
boolean teleporting
boolean teleportRegion
Position teleportTarget
final EnumSet< UpdateFlag > updateFlags = EnumSet.noneOf(UpdateFlag.class)
Public Attributes inherited from com.runehive.game.world.entity.Entity
int instance = DEFAULT_INSTANCE
Static Public Attributes inherited from com.runehive.game.world.entity.Entity
static final int DEFAULT_INSTANCE = 0
Protected Member Functions inherited from com.runehive.game.world.entity.mob.Mob
void setWaypoint (Waypoint waypoint)
Protected Member Functions inherited from com.runehive.game.world.entity.Entity
Entity destroy ()
Destroys this entity.
void setRegistered (boolean registered)
Protected Attributes inherited from com.runehive.game.world.entity.mob.Mob
Waypoint cachedWaypoint
Package Functions inherited from com.runehive.game.world.entity.mob.npc.Npc
int getDeathTime ()
Detailed Description
Definition at line 70 of file Scorpia.java.
Constructor & Destructor Documentation
Guardian()
com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.Guardian (Position spawn, Npc scorpia) private
Definition at line 73 of file Scorpia.java.
{
            super(6617, spawn);
            setWaypoint(new Waypoint(this, scorpia) {
                @Override
                protected void onDestination() {
                    CombatProjectile.getDefinition("Scorpia guardian").getProjectile().ifPresent(projectile -> projectile.send(mob, scorpia));
                    lastHeal.reset();
                    lastHeal.start();
                    mob.animate(new Animation(6261));
                    scorpia.heal(2);
                }
            });
        }
References com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition(), com.runehive.game.world.entity.combat.projectile.CombatProjectile.getProjectile(), lastHeal, com.runehive.game.world.entity.mob.npc.Npc.Npc(), and com.runehive.game.world.entity.mob.Mob.setWaypoint().
Member Function Documentation
sequence()
void com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.sequence ()
Reimplemented from com.runehive.game.world.entity.mob.npc.Npc.
Definition at line 88 of file Scorpia.java.
{
            super.sequence();
            long millis = lastHeal.elapsed().toMillis();
            if (millis > 15_000) {
                unregister();
            }
        }
References lastHeal, and com.runehive.game.world.entity.mob.npc.Npc.unregister().
Member Data Documentation
lastHeal
final Stopwatch com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.lastHeal = Stopwatch.createStarted() private
Definition at line 71 of file Scorpia.java.
Referenced by Guardian(), and sequence().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/scorpia/Scorpia.java