RuneHive-Game: com.runehive.game.world.entity.mob.npc.drop.NpcDropTable Class Reference
com.runehive.game.world.entity.mob.npc.drop.NpcDropTable Class Reference
The class which represents a npc drop table.
Public Member Functions
List< NpcDrop > generate (Player player, boolean simulated)
NpcDropTable (int[] npcIds, boolean rareDropTable, NpcDrop[] npcDrops, NpcDrop[] always, NpcDrop[] common, NpcDrop[] uncommon, NpcDrop[] rare, NpcDrop[] veryRare)
Constructs a new NpcDropTable.
void setRollData (int[] rollData)
Static Public Member Functions
static void main (String[] args)
Public Attributes
final NpcDrop[] drops
The cached array of NpcDrops.
final int[] npcIds
The npc ids that share this drop table.
final NpcDrop[][] table = new NpcDrop[5][]
Static Private Member Functions
static void printRates (NpcDrop[][] tables, int[] rollData, int[] rollData2)
Private Attributes
int maxRoll = 20_000
final boolean rareDropTable
Determines if this table has access to the rare drop table.
int[] rollData
Static Private Attributes
static final int[] ROLL_DATA
Detailed Description
The class which represents a npc drop table.
Author
Michael | Chex
Definition at line 17 of file NpcDropTable.java.
Constructor & Destructor Documentation
NpcDropTable()
com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.NpcDropTable (int[] npcIds, boolean rareDropTable, NpcDrop[] npcDrops, NpcDrop[] always, NpcDrop[] common, NpcDrop[] uncommon, NpcDrop[] rare, NpcDrop[] veryRare)
Constructs a new NpcDropTable.
Definition at line 56 of file NpcDropTable.java.
{
        this.npcIds = npcIds;
        this.rareDropTable = rareDropTable;
        this.drops = npcDrops;
        rollData = ROLL_DATA;
        table[0] = veryRare;
        table[1] = rare;
        table[2] = uncommon;
        table[3] = common;
        table[4] = always;
    }
References npcIds, rareDropTable, ROLL_DATA, rollData, and table.
Referenced by main().
Member Function Documentation
generate()
List< NpcDrop > com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.generate (Player player, boolean simulated)
Definition at line 68 of file NpcDropTable.java.
{
        LinkedList<NpcDrop> items = new LinkedList<>();
        int roll = RandomUtils.inclusive(maxRoll);
        if (player.equipment.hasRow()) {
            int old = roll;
            roll = PlayerRight.dropRateIncrease(player, roll);
            if (roll < rollData[0] && old >= rollData[0]) {
                if (!simulated) {
                    player.message("Very Rare drop table accessed by ring");
                    player.playerAssistant.useROW();
                }
            } else if (roll < rollData[1] && old >= rollData[1]) {
                if (!simulated) {
                    player.message("Rare drop table accessed by ring");
                    player.playerAssistant.useROW();
                }
            } else {
                /* undo the ring effect since both tables weren't accessed */
                roll = old;
            }
        }
        for (int chance = 0, index = 0; index < rollData.length - 1; index++) {
            chance += rollData[index];
            if (rollData[index] == 0 || roll >= chance) {
                continue;
            }
            if (table[index].length > 0) {
                items.addFirst(RandomUtils.random(table[index]));
                break;
            }
        }
        for (NpcDrop drop : table[4]) {
            items.addFirst(drop);
        }
        return items;
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.dropRateIncrease(), com.runehive.util.RandomUtils.inclusive(), maxRoll, com.runehive.util.RandomUtils.random(), rollData, and table.
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop().
main()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.main (String[] args) static
Definition at line 119 of file NpcDropTable.java.
{
        int npcId = 7241;
        /*
         *
         *  DONT USE RATES LESS THAN 100!!!
         *
         * The ring of wealth works best with values larger than 100
         * since 3% of 100 is 3, anything lower than 100 will break ROW
         *
         */
        int[] customRolls = {
            /* very rare roll */
            200,
            /* rare roll */
            350,
            /* uncommon roll */
            7000,
            /* common roll */
            12500,
            /* empty drop roll */
            200
        };
        ItemDefinition.createParser().run();
        new NpcDropParser().run();
        NpcDropTable table = NpcDropManager.NPC_DROPS.get(npcId);
        System.out.println();
        System.out.println("Table lengths (vr, r, uc, c): ");
        for (int index = 0; index < table.table.length - 1; index++) {
            System.out.print(table.table[index].length + " ");
        }
        System.out.println("\n");
        System.out.println("--------------------------------------------------");
        System.out.println("Current rolls: \t \t \t \t Custom rolls:");
        printRates(table.table, table.rollData, customRolls);
        System.out.println();
    }
References com.runehive.game.world.items.ItemDefinition.createParser(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.NPC_DROPS, NpcDropTable(), printRates(), com.runehive.util.parser.GenericParser.run(), and table.
printRates()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.printRates (NpcDrop tables[][], int[] rollData, int[] rollData2) static private
Definition at line 165 of file NpcDropTable.java.
{
        long maxRoll = 0, maxRoll2 = 0;
        for (int index = 0; index < rollData.length; index++) {
            maxRoll += rollData[index];
            maxRoll2 += rollData2[index];
        }
        System.out.println("--------------------------------------------------");
        System.out.println("Very Rare ---- " + ((long) rollData[0] * 100_00 / maxRoll) / 100.0 + "% \t\t Very Rare ---- " + ((long) rollData2[0] * 100_00 / maxRoll2) / 100.0 + "%");
        System.out.println("Rare --------- " + ((long) rollData[1] * 100_00 / maxRoll) / 100.0 + "% \t\t Rare --------- " + ((long) rollData2[1] * 100_00 / maxRoll2) / 100.0 + "%");
        System.out.println("Uncommon ----- " + ((long) rollData[2] * 100_00 / maxRoll) / 100.0 + "% \t\t Uncommon ----- " + ((long) rollData2[2] * 100_00 / maxRoll2) / 100.0 + "%");
        System.out.println("Common ------- " + ((long) rollData[3] * 100_00 / maxRoll) / 100.0 + "% \t\t Common ------- " + ((long) rollData2[3] * 100_00 / maxRoll2) / 100.0 + "%");
        System.out.println("Empty Drop --- " + ((long) rollData[4] * 100_00 / maxRoll) / 100.0 + "% \t\t Empty Drop --- " + ((long) rollData2[4] * 100_00 / maxRoll2) / 100.0 + "%");
        System.out.println("--------------------------------------------------");
        System.out.println("Very Rare ---- " + ((long) rollData[0] * 100_00 / maxRoll) / tables[0].length / 100.0 + "% \t\t Very Rare ---- " + ((long) rollData2[0] * 100_00 / maxRoll2) / tables[0].length / tables[0].length / 100.0 + "%");
        System.out.println("Rare --------- " + ((long) rollData[1] * 100_00 / maxRoll) / tables[1].length / 100.0 + "% \t\t Rare --------- " + ((long) rollData2[1] * 100_00 / maxRoll2) / tables[0].length / tables[1].length / 100.0 + "%");
        System.out.println("Uncommon ----- " + ((long) rollData[2] * 100_00 / maxRoll) / tables[2].length / 100.0 + "% \t\t Uncommon ----- " + ((long) rollData2[2] * 100_00 / maxRoll2) / tables[0].length / tables[2].length / 100.0 + "%");
        System.out.println("Common ------- " + ((long) rollData[3] * 100_00 / maxRoll) / tables[3].length / 100.0 + "% \t\t Common ------- " + ((long) rollData2[3] * 100_00 / maxRoll2) / tables[0].length / tables[3].length / 100.0 + "%");
        System.out.println("--------------------------------------------------");
    }
References maxRoll, and rollData.
Referenced by main().
setRollData()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.setRollData (int[] rollData)
Definition at line 111 of file NpcDropTable.java.
{
        this.rollData = rollData;
        maxRoll = 0;
        for (int roll : rollData) {
            maxRoll += roll;
        }
    }
References maxRoll, and rollData.
Referenced by com.runehive.util.parser.impl.NpcDropParser.parse().
Member Data Documentation
drops
final NpcDrop [] com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.drops
The cached array of NpcDrops.
Definition at line 26 of file NpcDropTable.java.
Referenced by com.runehive.content.DropDisplay.display(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop(), and com.runehive.content.DropDisplay.search().
maxRoll
int com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.maxRoll = 20_000 private
Definition at line 30 of file NpcDropTable.java.
Referenced by generate(), printRates(), and setRollData().
npcIds
final int [] com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.npcIds
The npc ids that share this drop table.
Definition at line 20 of file NpcDropTable.java.
Referenced by com.runehive.content.DropDisplay.display(), NpcDropTable(), and com.runehive.content.DropDisplay.search().
rareDropTable
final boolean com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.rareDropTable private
Determines if this table has access to the rare drop table.
Definition at line 23 of file NpcDropTable.java.
Referenced by NpcDropTable().
ROLL_DATA
final int [] com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.ROLL_DATA static private
Initial value:
= {
        200,
        350,
        7000,
        12500,
        200
    }
Definition at line 36 of file NpcDropTable.java.
{
        /* very rare roll */
        200,
        /* rare roll */
        350,
        /* uncommon roll */
        7000,
        /* common roll */
        12500,
        /* empty drop roll */
        200
    };
Referenced by NpcDropTable().
rollData
int [] com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.rollData private
Definition at line 53 of file NpcDropTable.java.
Referenced by generate(), NpcDropTable(), printRates(), and setRollData().
table
final NpcDrop [][] com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.table = new NpcDrop[5][]
Definition at line 28 of file NpcDropTable.java.
Referenced by generate(), main(), and NpcDropTable().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/npc/drop/NpcDropTable.java