RuneHive-Game: com.runehive.content.store.Store Class Reference
com.runehive.content.store.Store Class Reference abstract
The class which holds support for further abstraction for shops.
Public Member Functions
abstract void close (Player player)
boolean decrementStock ()
final boolean equals (Object obj)
final int hashCode ()
abstract void itemContainerAction (Player player, int id, int slot, int action, boolean purchase)
void onPurchase (Player player, Item item)
abstract void open (Player player)
boolean purchase (Player player, Item item, int slot)
abstract void refresh (Player player)
abstract SellType sellType ()
Store (String name, ItemContainer.StackPolicy policy, CurrencyType currencyType, int capacity)
abstract StoreType type ()
Static Public Member Functions
static void closeShop (Player player)
static void exchange (Player player, int id, int slot, int action, boolean purchase)
Public Attributes
ItemContainer container
The current item container which contains the current items from this shop.
Map< Integer, Integer > itemCache
The map of cached shop item identifications and their amounts.
final String name
The name of this shop.
final Set< Player > players = new HashSet<>()
The set of players that are currently viewing this shop.
Static Public Attributes
static Map< String, Store > STORES = new HashMap<>()
A mapping of each shop by it's name.
Protected Member Functions
final void sell (Player player, Item item, int slot, boolean addX)
void sendPurchaseValue (Player player, int slot)
final void sendSellValue (Player player, int slot)
Static Protected Member Functions
static List< PersonalStore > getFeaturedShops ()
static List< PersonalStore > getPersonalShops ()
Protected Attributes
final CurrencyType currencyType
The currency for this shop.
Detailed Description
The class which holds support for further abstraction for shops.
Author
Stand Up
Since
4-1-2017.
Definition at line 20 of file Store.java.
Constructor & Destructor Documentation
Store()
com.runehive.content.store.Store.Store (String name, ItemContainer.StackPolicy policy, CurrencyType currencyType, int capacity)
Definition at line 40 of file Store.java.
{
        this.name = name;
        this.currencyType = currencyType;
        this.container = new ItemContainer(capacity, policy, new StoreItem[capacity]);
        this.itemCache = new HashMap<>(container.capacity());
    }
References container, currencyType, and name.
Referenced by com.runehive.content.store.impl.PersonalStore.changeName(), closeShop(), equals(), exchange(), and com.runehive.content.store.impl.PersonalStore.myShop().
Member Function Documentation
close()
abstract void com.runehive.content.store.Store.close (Player player) abstract
Reimplemented in com.runehive.content.store.impl.DefaultStore, com.runehive.content.store.impl.PersonalStore, com.runehive.content.store.impl.RecipeForDisasterStore, and com.runehive.content.store.impl.SkillcapeStore.
closeShop()
void com.runehive.content.store.Store.closeShop (Player player) static
Definition at line 47 of file Store.java.
{
        if (!player.interfaceManager.isInterfaceOpen(StoreConstant.INTERFACE_ID) || !player.attributes.has("SHOP")) {
            return;
        }
        Store store = STORES.get(player.attributes.get("SHOP"));
        if (store == null) {
            return;
        }
        store.close(player);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.util.generic.GenericAttributes.get(), com.runehive.util.generic.GenericAttributes.has(), com.runehive.content.store.StoreConstant.INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.isInterfaceOpen(), Store(), and STORES.
Referenced by com.runehive.game.world.entity.mob.player.InterfaceManager.close().
decrementStock()
boolean com.runehive.content.store.Store.decrementStock ()
Reimplemented in com.runehive.content.store.impl.RecipeForDisasterStore, and com.runehive.content.store.impl.SkillcapeStore.
Definition at line 303 of file Store.java.
{
        return true;
    }
Referenced by purchase().
equals()
final boolean com.runehive.content.store.Store.equals (Object obj)
Definition at line 316 of file Store.java.
{
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof Store))
            return false;
        Store other = (Store) obj;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        return true;
    }
References name, and Store().
Referenced by purchase().
exchange()
void com.runehive.content.store.Store.exchange (Player player, int id, int slot, int action, boolean purchase) static
Definition at line 61 of file Store.java.
{
        if (!player.interfaceManager.isInterfaceOpen(StoreConstant.INTERFACE_ID) || !player.attributes.has("SHOP")) {
            return;
        }
        Store store = STORES.get(player.attributes.get("SHOP"));
        if (store == null) {
            return;
        }
        store.itemContainerAction(player, id, slot, action, purchase);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.util.generic.GenericAttributes.get(), com.runehive.util.generic.GenericAttributes.has(), com.runehive.content.store.StoreConstant.INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.isInterfaceOpen(), purchase(), Store(), and STORES.
getFeaturedShops()
List< PersonalStore > com.runehive.content.store.Store.getFeaturedShops () static protected
Definition at line 81 of file Store.java.
{
        List<PersonalStore> featured_shops = new ArrayList<>();
        STORES.values().stream().filter(s -> s.type().equals(StoreType.PERSONAL) && ((PersonalStore) s).rank > 0).forEach(s -> featured_shops.add((PersonalStore) s));
        return featured_shops;
    }
References com.runehive.content.store.impl.PersonalStore.add(), com.runehive.content.store.StoreType.PERSONAL, and STORES.
Referenced by com.runehive.content.store.impl.PersonalStore.openPanel().
getPersonalShops()
List< PersonalStore > com.runehive.content.store.Store.getPersonalShops () static protected
Definition at line 75 of file Store.java.
{
        List<PersonalStore> personal_shops = new ArrayList<>();
        STORES.values().stream().filter(s -> s.type().equals(StoreType.PERSONAL)).forEach(s -> personal_shops.add((PersonalStore) s));
        return personal_shops;
    }
References com.runehive.content.store.StoreType.PERSONAL, and STORES.
Referenced by com.runehive.content.store.impl.PersonalStore.openMenu(), and com.runehive.content.store.impl.PersonalStore.openPanel().
hashCode()
final int com.runehive.content.store.Store.hashCode ()
Definition at line 308 of file Store.java.
{
        final int prime = 31;
        int result = 1;
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        return result;
    }
References name.
itemContainerAction()
abstract void com.runehive.content.store.Store.itemContainerAction (Player player, int id, int slot, int action, boolean purchase) abstract
Reimplemented in com.runehive.content.store.impl.DefaultStore, com.runehive.content.store.impl.PersonalStore, com.runehive.content.store.impl.RecipeForDisasterStore, and com.runehive.content.store.impl.SkillcapeStore.
References purchase().
onPurchase()
void com.runehive.content.store.Store.onPurchase (Player player, Item item)
Reimplemented in com.runehive.content.store.impl.PersonalStore.
Definition at line 172 of file Store.java.
{
    }
Referenced by purchase().
open()
abstract void com.runehive.content.store.Store.open (Player player) abstract
Reimplemented in com.runehive.content.store.impl.DefaultStore, com.runehive.content.store.impl.PersonalStore, com.runehive.content.store.impl.RecipeForDisasterStore, and com.runehive.content.store.impl.SkillcapeStore.
purchase()
boolean com.runehive.content.store.Store.purchase (Player player, Item item, int slot)
Reimplemented in com.runehive.content.store.impl.SkillcapeStore.
Definition at line 89 of file Store.java.
{
        if (item == null || !Item.valid(item)) {
            return false;
        }
        Optional<Item> find = container.retrieve(slot);
        if (!find.isPresent()) {
            return false;
        }
        Item found = find.get();
        if (!(found instanceof StoreItem)) {
            return false;
        }
        if (!found.matchesId(item.getId())) {
            player.send(new SendMessage("Something went wrong."));
            return false;
        }
        StoreItem storeItem = (StoreItem) find.get();
        if (storeItem.getAmount() < 1) {
            player.send(new SendMessage("There is none of this item left in stock!"));
            return false;
        }
        if(PlayerRight.isIronman(player)) {
            player.send(new SendMessage("Ironman-players cannot buy items sold by players."));
            return false;
        }
        if (item.getAmount() > storeItem.getAmount())
            item.setAmount(storeItem.getAmount());
        if (!player.inventory.hasCapacityFor(item)) {
            item.setAmount(player.inventory.remaining());
            if (item.getAmount() == 0) {
                player.send(new SendMessage("You do not have enough space in your inventory to buy this item!"));
                return false;
            }
        }
        final int value = storeItem.getShopValue();
        if (!(currencyType.currency.currencyAmount(player) >= (value * item.getAmount()))) {
            player.send(new SendMessage("You do not have enough " + currencyType.toString() + " to buy this item."));
            return false;
        }
        if (player.inventory.remaining() >= item.getAmount() && !item.isStackable()
                || player.inventory.remaining() >= 1 && item.isStackable()
                || player.inventory.contains(item.getId()) && item.isStackable()) {
            if (value > 0 && !currencyType.currency.takeCurrency(player, item.getAmount() * value)) {
                return false;
            }
            if (type().equals(StoreType.PERSONAL) && container.retrieve(slot).isPresent() && (container.retrieve(slot).get().getAmount() - item.getAmount() > 0)) {
                container.retrieve(slot).get().decrementAmountBy(item.getAmount());
            } else if (itemCache.containsKey(item.getId()) && container.retrieve(slot).isPresent()) {
                if (decrementStock()) {
                    container.retrieve(slot).get().decrementAmountBy(item.getAmount());
                }
            } else if (!itemCache.containsKey(item.getId())) {
                if (decrementStock()) {
                    container.remove(item);
                }
                if (type().equals(StoreType.PERSONAL)) {
                    container.shift();
                }
            }
            player.inventory.add(new Item(item.getId(), item.getAmount()));
        } else {
            player.send(new SendMessage("You don't have enough space in your inventory."));
            return false;
        }
        onPurchase(player, new Item(item.getId(), item.getAmount() * value));
        refresh(player);
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), container, com.runehive.game.world.items.containers.ItemContainer.contains(), currencyType, decrementStock(), equals(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.content.store.StoreItem.getShopValue(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.game.world.items.Item.isStackable(), itemCache, com.runehive.game.world.items.Item.matchesId(), onPurchase(), com.runehive.content.store.StoreType.PERSONAL, refresh(), com.runehive.game.world.items.containers.ItemContainer.remaining(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.items.Item.setAmount(), type(), and com.runehive.game.world.items.Item.valid().
Referenced by exchange(), com.runehive.content.store.impl.DefaultStore.itemContainerAction(), com.runehive.content.store.impl.PersonalStore.itemContainerAction(), com.runehive.content.store.impl.RecipeForDisasterStore.itemContainerAction(), and itemContainerAction().
refresh()
abstract void com.runehive.content.store.Store.refresh (Player player) abstract
Reimplemented in com.runehive.content.store.impl.DefaultStore, com.runehive.content.store.impl.PersonalStore, com.runehive.content.store.impl.RecipeForDisasterStore, and com.runehive.content.store.impl.SkillcapeStore.
Referenced by purchase(), and sell().
sell()
final void com.runehive.content.store.Store.sell (Player player, Item item, int slot, boolean addX) protected
Definition at line 176 of file Store.java.
{
        if (item == null || !Item.valid(item)) {
            return;
        }
        final Item inventoryItem = player.inventory.get(slot);
        if (inventoryItem == null) {
            player.send(new SendMessage("This item does not exist."));
            return;
        }
        if (sellType() == SellType.NONE) {
            player.send(new SendMessage("This store won't buy any items."));
            return;
        }
        if (!item.isTradeable()) {
            player.send(new SendMessage("This item can't be sold to shops."));
            return;
        }
        final boolean contains = container.contains(item.getId());
        if (!contains && sellType() == SellType.CONTAINS) {
            player.send(new SendMessage("You can't sell " + item.getName() + " to this shop."));
            return;
        }
        if (!container.hasCapacityFor(item)) {
            player.send(new SendMessage("There is no room in this store for the item you are trying to sell!"));
            return;
        }
        if (player.inventory.remaining() == 0 && !currencyType.currency.canRecieveCurrency(player) && inventoryItem.getAmount() > 1) {
            player.send(new SendMessage("You do not have enough space in your inventory to sell this item!"));
            return;
        }
        if (CurrencyType.isCurrency(item.getId())) {
            player.send(new SendMessage("You can not sell currency to this shop!"));
            return;
        }
        final int sellValue = item.getSellValue();
        if (sellValue >= StoreConstant.MAXIMUM_SELL_VALUE) {
            player.send(new SendMessage("This item can not be sold as it has a value greater than 500,000 coins!"));
            return;
        }
        final int amount = player.inventory.computeAmountForId(item.getId());
        if (item.getAmount() > amount && !item.isStackable()) {
            item.setAmount(amount);
        } else if (item.getAmount() > inventoryItem.getAmount() && item.isStackable()) {
            item.setAmount(inventoryItem.getAmount());
        }
        player.inventory.remove(item, slot);
        if (sellValue > 0) {
            currencyType.currency.recieveCurrency(player, item.getAmount() * sellValue);
        }
        final StoreItem converted = new StoreItem(item.getId(), item.getAmount());
        container.add(converted);
        refresh(player);
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), container, com.runehive.content.store.SellType.CONTAINS, currencyType, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.Item.getSellValue(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.store.currency.CurrencyType.isCurrency(), com.runehive.game.world.items.Item.isStackable(), com.runehive.game.world.items.Item.isTradeable(), com.runehive.content.store.StoreConstant.MAXIMUM_SELL_VALUE, com.runehive.content.store.SellType.NONE, refresh(), com.runehive.game.world.items.containers.ItemContainer.remaining(), com.runehive.game.world.items.containers.ItemContainer.remove(), sellType(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.items.Item.setAmount(), and com.runehive.game.world.items.Item.valid().
Referenced by com.runehive.content.store.impl.DefaultStore.itemContainerAction().
sellType()
abstract SellType com.runehive.content.store.Store.sellType () abstract
Reimplemented in com.runehive.content.store.impl.DefaultStore, com.runehive.content.store.impl.PersonalStore, com.runehive.content.store.impl.RecipeForDisasterStore, and com.runehive.content.store.impl.SkillcapeStore.
Referenced by sell(), and sendSellValue().
sendPurchaseValue()
void com.runehive.content.store.Store.sendPurchaseValue (Player player, int slot) protected
Definition at line 277 of file Store.java.
{
        Optional<Item> find = container.retrieve(slot);
        if (!find.isPresent()) {
            return;
        }
        Item item = find.get();
        if (item instanceof StoreItem) {
            StoreItem storeItem = (StoreItem) item;
            final int value = storeItem.getShopValue();
            String message = "This store will sell " + item.getName() + " for " + (value <= 0 ? "free!" : Utility.formatDigits(value) + " " + storeItem.getShopCurrency(this).toString() + ".");
            player.message(message);
        }
    }
References container, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getName(), com.runehive.content.store.StoreItem.getShopCurrency(), com.runehive.content.store.StoreItem.getShopValue(), com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.content.store.currency.CurrencyType.toString().
Referenced by com.runehive.content.store.impl.DefaultStore.itemContainerAction(), com.runehive.content.store.impl.PersonalStore.itemContainerAction(), com.runehive.content.store.impl.RecipeForDisasterStore.itemContainerAction(), and com.runehive.content.store.impl.SkillcapeStore.itemContainerAction().
sendSellValue()
final void com.runehive.content.store.Store.sendSellValue (Player player, int slot) protected
Definition at line 249 of file Store.java.
{
        Item item = player.inventory.get(slot);
        if (item == null) {
            return;
        }
        if (!item.isTradeable()) {
            player.send(new SendMessage("This item can't be sold to shops."));
            return;
        }
        if (CurrencyType.isCurrency(item.getId())) {
            player.send(new SendMessage("You can not sell currency to this shop!"));
            return;
        }
        final int value = item.getSellValue();
        if (value <= 0) {
            player.send(new SendMessage(String.format("This store will buy %s for free!", item.getName())));
            return;
        }
        final String message = this.sellType() != SellType.NONE ? String.format("This store will buy %s for %s %s.", item.getName(), Utility.formatDigits(value), currencyType.toString()) : String.format("[%s] will not buy any items.", name);
        player.send(new SendMessage(message));
    }
References currencyType, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.Item.getSellValue(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.store.currency.CurrencyType.isCurrency(), com.runehive.game.world.items.Item.isTradeable(), name, com.runehive.content.store.SellType.NONE, sellType(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.content.store.impl.DefaultStore.itemContainerAction().
type()
abstract StoreType com.runehive.content.store.Store.type () abstract
Reimplemented in com.runehive.content.store.impl.DefaultStore, com.runehive.content.store.impl.PersonalStore, com.runehive.content.store.impl.RecipeForDisasterStore, and com.runehive.content.store.impl.SkillcapeStore.
Referenced by purchase().
Member Data Documentation
container
ItemContainer com.runehive.content.store.Store.container
The current item container which contains the current items from this shop.
Definition at line 29 of file Store.java.
Referenced by com.runehive.content.store.impl.DefaultStore.DefaultStore(), com.runehive.content.store.impl.PersonalStore.itemContainerAction(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.content.store.impl.DefaultStore.needsRestock(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.PersonalStore.PersonalStore(), purchase(), com.runehive.content.store.impl.RecipeForDisasterStore.RecipeForDisasterStore(), com.runehive.content.store.impl.DefaultStore.refresh(), com.runehive.content.store.impl.RecipeForDisasterStore.refresh(), com.runehive.content.store.impl.PersonalStore.remove(), com.runehive.content.store.impl.DefaultStore.restockCompleted(), sell(), sendPurchaseValue(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.store.impl.SkillcapeStore.SkillcapeStore(), and Store().
currencyType
final CurrencyType com.runehive.content.store.Store.currencyType protected
The currency for this shop.
Definition at line 32 of file Store.java.
Referenced by com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), purchase(), com.runehive.content.store.impl.DefaultStore.refresh(), com.runehive.content.store.impl.RecipeForDisasterStore.refresh(), com.runehive.content.store.impl.SkillcapeStore.refresh(), sell(), sendSellValue(), and Store().
itemCache
Map<Integer, Integer> com.runehive.content.store.Store.itemCache
The map of cached shop item identifications and their amounts.
Definition at line 35 of file Store.java.
Referenced by com.runehive.content.store.impl.DefaultStore.DefaultStore(), com.runehive.content.store.impl.DefaultStore.needsRestock(), purchase(), com.runehive.content.store.impl.RecipeForDisasterStore.RecipeForDisasterStore(), com.runehive.content.store.impl.DefaultStore.restockCompleted(), and com.runehive.content.store.impl.SkillcapeStore.SkillcapeStore().
name
final String com.runehive.content.store.Store.name
The name of this shop.
Definition at line 26 of file Store.java.
Referenced by com.runehive.content.store.impl.DefaultStore.DefaultStore(), equals(), hashCode(), com.runehive.content.store.impl.PersonalStore.isOwner(), com.runehive.content.store.impl.PersonalStore.onPurchase(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.content.store.impl.PersonalStore.openPanel(), com.runehive.content.store.impl.PersonalStore.PersonalStore(), sendSellValue(), and Store().
players
final Set<Player> com.runehive.content.store.Store.players = new HashSet<>()
The set of players that are currently viewing this shop.
Definition at line 38 of file Store.java.
Referenced by com.runehive.content.store.impl.DefaultStore.close(), com.runehive.content.store.impl.PersonalStore.close(), com.runehive.content.store.impl.RecipeForDisasterStore.close(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.DefaultStore.refresh(), com.runehive.content.store.impl.PersonalStore.refresh(), and com.runehive.content.store.impl.RecipeForDisasterStore.refresh().
STORES
Map<String, Store> com.runehive.content.store.Store.STORES = new HashMap<>() static
A mapping of each shop by it's name.
Definition at line 23 of file Store.java.
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.clickNpc(), com.runehive.content.skill.impl.crafting.Crafting.clickNpc(), closeShop(), exchange(), getFeaturedShops(), getPersonalShops(), com.runehive.content.store.impl.PersonalStore.myShop(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.util.parser.impl.StoreParser.parse(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), and com.runehive.content.dialogue.impl.RoyalKingDialogue.store().
The documentation for this class was generated from the following file:
java/com/runehive/content/store/Store.java