RuneHive-Game: com.runehive.content.ai.LazyAIManager Class Reference
com.runehive.content.ai.LazyAIManager Class Reference
Static Public Member Functions
static void clearPlayerConsent (String username)
static OpenAIService getOpenAIService ()
static boolean handleGandalfAIClick (Player player, Npc npc)
static boolean isInitialized ()
static void markInstructionsReceived (String username)
static void shutdown ()
Static Private Member Functions
static void cancelInactivityTimer (String username)
static void initializeOpenAIAndProcess (Player player, Npc npc)
static synchronized boolean initializeOpenAIServices ()
static void showGptInstructions (Player player, Npc npc)
static void showGptInstructionsWithGreeting (Player player, Npc npc)
static void showOpenAIConnectionOffer (Player player, Npc npc)
static void startInactivityTimer (Player player, Npc npc)
Static Private Attributes
static final int GANDALF_AI_ID = 2108
static final Map< String, Task > inactivityTimers = new ConcurrentHashMap<>()
static final Logger logger = LoggerFactory.getLogger(LazyAIManager.class)
static final AtomicBoolean openAIInitialized = new AtomicBoolean(false)
static volatile OpenAIService openAIService
static final Set< String > sessionConsents = ConcurrentHashMap.newKeySet()
Detailed Description
Definition at line 17 of file LazyAIManager.java.
Member Function Documentation
cancelInactivityTimer()
void com.runehive.content.ai.LazyAIManager.cancelInactivityTimer (String username) static private
Definition at line 209 of file LazyAIManager.java.
{
        Task timer = inactivityTimers.remove(username);
        if (timer != null) {
            timer.cancel();
        }
    }
References com.runehive.game.task.Task.cancel(), and inactivityTimers.
Referenced by clearPlayerConsent(), markInstructionsReceived(), and startInactivityTimer().
clearPlayerConsent()
void com.runehive.content.ai.LazyAIManager.clearPlayerConsent (String username) static
Definition at line 216 of file LazyAIManager.java.
{
        if (sessionConsents.remove(username)) {
            logger.info("Cleared OpenAI consent for player: {}", username);
            // Send blue chat message to player about service termination
            World.getPlayerByName(username).ifPresent(player -> {
                String timestamp = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
                player.message("<col=0000FF>[OpenAI Service] Terminated at " + timestamp + ". Conversation History flushed.</col>");
            });
        }
        cancelInactivityTimer(username);
        if (openAIService != null) {
            openAIService.clearConversationHistory(username);
        }
    }
References cancelInactivityTimer(), com.runehive.game.world.World.getPlayerByName(), logger, openAIService, and sessionConsents.
Referenced by startInactivityTimer(), and com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse().
getOpenAIService()
OpenAIService com.runehive.content.ai.LazyAIManager.getOpenAIService () static
Definition at line 133 of file LazyAIManager.java.
{
        return openAIService;
    }
References openAIService.
Referenced by com.runehive.game.world.cronjobs.impl.OpenAIRelayJob.execute(), and com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage().
handleGandalfAIClick()
boolean com.runehive.content.ai.LazyAIManager.handleGandalfAIClick (Player player, Npc npc) static
Definition at line 28 of file LazyAIManager.java.
{
        if (npc.id != GANDALF_AI_ID) {
            return false;
        }
        // Position player 1 tile west of NPC and setup camera
        Position npcPos = npc.getPosition();
        Position playerTarget = new Position(npcPos.getX() - 1, npcPos.getY(), npcPos.getHeight());
        player.move(playerTarget);
        player.face(npc);
        // Initialize dialogue camera - player speaks first
        player.dialogueCamNpc = npc;
        player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_PLAYER;
        if (sessionConsents.contains(player.getUsername())) {
            if (!openAIInitialized.get()) {
                initializeOpenAIServices();
            }
            // Always show instructions when NPC is clicked (connection is idle)
            showGptInstructions(player, npc);
        } else {
            showOpenAIConnectionOffer(player, npc);
        }
        return true;
    }
References com.runehive.game.world.entity.mob.Mob.face(), GANDALF_AI_ID, com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.Mob.id, initializeOpenAIServices(), com.runehive.game.world.entity.mob.Mob.move(), openAIInitialized, sessionConsents, showGptInstructions(), and showOpenAIConnectionOffer().
initializeOpenAIAndProcess()
void com.runehive.content.ai.LazyAIManager.initializeOpenAIAndProcess (Player player, Npc npc) static private
Definition at line 90 of file LazyAIManager.java.
{
        if (!openAIInitialized.get()) {
            if (initializeOpenAIServices()) {
                showGptInstructionsWithGreeting(player, npc);
            } else {
                player.dialogueFactory
                    .sendNpcChat(npc.id, Expression.SAD,
                        "Alas! The mystical networks are unreachable.",
                        "Please ensure the OpenAI key scroll is present",
                        "and try again later.")
                    .execute();
                return;
            }
        } else {
            showGptInstructionsWithGreeting(player, npc);
        }
    }
References com.runehive.game.world.entity.mob.Mob.id, initializeOpenAIServices(), openAIInitialized, com.runehive.content.dialogue.Expression.SAD, and showGptInstructionsWithGreeting().
Referenced by showOpenAIConnectionOffer().
initializeOpenAIServices()
synchronized boolean com.runehive.content.ai.LazyAIManager.initializeOpenAIServices () static private
Definition at line 108 of file LazyAIManager.java.
{
        if (openAIInitialized.compareAndSet(false, true)) {
            logger.info("Player accepted OpenAI connection - initializing OpenAI services...");
            try {
                openAIService = OpenAIService.getInstance();
                openAIService.initialize();
                logger.info("Official OpenAI Service initialized with GPT-4o-mini model");
                logger.info("OpenAI services fully initialized and ready for interactions!");
                return true;
            } catch (Exception e) {
                logger.error("Failed to initialize OpenAI services", e);
                openAIInitialized.set(false);
                return false;
            }
        }
        return true;
    }
References com.runehive.content.ai.OpenAIService.getInstance(), logger, openAIInitialized, and openAIService.
Referenced by handleGandalfAIClick(), and initializeOpenAIAndProcess().
isInitialized()
boolean com.runehive.content.ai.LazyAIManager.isInitialized () static
Definition at line 129 of file LazyAIManager.java.
{
        return openAIInitialized.get();
    }
References openAIInitialized.
Referenced by com.runehive.game.world.cronjobs.impl.OpenAIRelayJob.execute(), and com.runehive.content.ai.AIDialogueHandler.handleAICommand().
markInstructionsReceived()
void com.runehive.content.ai.LazyAIManager.markInstructionsReceived (String username) static
Definition at line 168 of file LazyAIManager.java.
{
        cancelInactivityTimer(username);
    }
References cancelInactivityTimer().
Referenced by com.runehive.content.ai.AIDialogueHandler.handleAICommand().
showGptInstructions()
void com.runehive.content.ai.LazyAIManager.showGptInstructions (Player player, Npc npc) static private
Definition at line 154 of file LazyAIManager.java.
{
        player.dialogueFactory
            .sendPlayerChat("Hello again, Wise Old Man!")
            .onAction(() -> player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_NPC)
            .sendNpcChat(npc.id, Expression.HAPPY,
                "To send a message, type:",
                "<col=0000FF>::gpt <your message></col>")
            .onAction(() -> {
                player.interfaceManager.close();
                com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.requestReset(player);
            })
            .execute();
    }
References com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.entity.mob.player.Player.dialogueCamMode, com.runehive.content.dialogue.Expression.HAPPY, com.runehive.game.world.entity.mob.Mob.id, and com.runehive.game.world.entity.mob.player.Player.interfaceManager.
Referenced by handleGandalfAIClick().
showGptInstructionsWithGreeting()
void com.runehive.content.ai.LazyAIManager.showGptInstructionsWithGreeting (Player player, Npc npc) static private
Definition at line 137 of file LazyAIManager.java.
{
        npc.animate(new com.runehive.game.Animation(858));
        npc.speak("GPT 4o at your service!");
        player.dialogueFactory
            .sendPlayerChat("Hello again, Wise Old Man!")
            .onAction(() -> player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_NPC)
            .sendNpcChat(npc.id, Expression.HAPPY,
                "To send a message, type:",
                "<col=0000FF>::gpt <your message></col>")
            .onAction(() -> {
                player.interfaceManager.close();
                com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.requestReset(player);
                startInactivityTimer(player, npc);
            })
            .execute();
    }
References com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.entity.mob.player.Player.dialogueCamMode, com.runehive.content.dialogue.Expression.HAPPY, com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.Mob.speak(), and startInactivityTimer().
Referenced by initializeOpenAIAndProcess().
showOpenAIConnectionOffer()
void com.runehive.content.ai.LazyAIManager.showOpenAIConnectionOffer (Player player, Npc npc) static private
Definition at line 56 of file LazyAIManager.java.
{
        player.dialogueFactory
            .sendPlayerChat("Hey, Wise Old Man!")
            .onAction(() -> player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_NPC)
            .sendNpcChat(npc.id, Expression.HAPPY,
                "Greetings, " + player.getUsername() + "!",
                "I am Gandalf GPT4o. I can connect to the OpenAI",
                "mystical networks to provide you with advanced",
                "AI assistance.")
            .sendNpcChat(npc.id, Expression.HAPPY,
                "Would you like me to establish this connection?")
            .sendOption(
                "Yes, connect to OpenAI", () -> {
                    sessionConsents.add(player.getUsername());
                    logger.info("Player {} consented to OpenAI connection for this session", player.getUsername());
                    // Send blue chat message to player about service initialization
                    String timestamp = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
                    player.message("<col=0000FF>[OpenAI Service] Initialized at " + timestamp + ". Conversation History = 10.</col>");
                    initializeOpenAIAndProcess(player, npc);
                },
                "No, maybe later", () -> {
                    player.dialogueFactory
                        .sendNpcChat(npc.id, Expression.HAPPY,
                            "Very well. I shall remain here if you change",
                            "your mind. The mystical networks await when",
                            "you are ready.")
                        .execute();
                }
            )
            .execute();
    }
References com.runehive.game.world.entity.mob.player.Player.dialogueCamMode, com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.content.dialogue.Expression.HAPPY, com.runehive.game.world.entity.mob.Mob.id, initializeOpenAIAndProcess(), logger, com.runehive.game.world.entity.mob.player.Player.message(), and sessionConsents.
Referenced by handleGandalfAIClick().
shutdown()
void com.runehive.content.ai.LazyAIManager.shutdown () static
Definition at line 234 of file LazyAIManager.java.
{
        if (openAIInitialized.get() && openAIService != null) {
            logger.info("Shutting down OpenAI services...");
            openAIService.shutdown();
        }
        sessionConsents.clear();
        inactivityTimers.values().forEach(Task::cancel);
        inactivityTimers.clear();
    }
References com.runehive.game.task.Task.cancel(), inactivityTimers, logger, openAIInitialized, openAIService, and sessionConsents.
startInactivityTimer()
void com.runehive.content.ai.LazyAIManager.startInactivityTimer (Player player, Npc npc) static private
Definition at line 172 of file LazyAIManager.java.
{
        cancelInactivityTimer(player.getUsername());
        Task timer = new Task(100) {
            int warningsSent = 0;
            @Override
            public void execute() {
                if (!player.isRegistered() || !sessionConsents.contains(player.getUsername())) {
                    cancel();
                    return;
                }
                if (warningsSent == 0) {
                    player.dialogueFactory
                        .sendNpcChat(npc.id, Expression.HAPPY,
                            "Hey " + player.getUsername() + ", I'm still here!",
                            "If I don't hear back from you within 1 minute,",
                            "I shall close the OpenAI realms. Your message",
                            "history would be reset in this event.")
                        .execute();
                    warningsSent++;
                } else {
                    player.dialogueFactory
                        .sendNpcChat(npc.id, Expression.HAPPY,
                            "Farewell, " + player.getUsername() + "!")
                        .execute();
                    clearPlayerConsent(player.getUsername());
                    cancel();
                }
            }
        };
        World.schedule(timer);
        inactivityTimers.put(player.getUsername(), timer);
    }
References cancelInactivityTimer(), clearPlayerConsent(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.content.dialogue.Expression.HAPPY, com.runehive.game.world.entity.mob.Mob.id, inactivityTimers, com.runehive.game.world.entity.Entity.isRegistered(), com.runehive.game.world.World.schedule(), and sessionConsents.
Referenced by showGptInstructionsWithGreeting().
Member Data Documentation
GANDALF_AI_ID
final int com.runehive.content.ai.LazyAIManager.GANDALF_AI_ID = 2108 static private
Definition at line 21 of file LazyAIManager.java.
Referenced by handleGandalfAIClick().
inactivityTimers
final Map<String, Task> com.runehive.content.ai.LazyAIManager.inactivityTimers = new ConcurrentHashMap<>() static private
Definition at line 24 of file LazyAIManager.java.
Referenced by cancelInactivityTimer(), shutdown(), and startInactivityTimer().
logger
final Logger com.runehive.content.ai.LazyAIManager.logger = LoggerFactory.getLogger(LazyAIManager.class) static private
Definition at line 19 of file LazyAIManager.java.
Referenced by clearPlayerConsent(), initializeOpenAIServices(), showOpenAIConnectionOffer(), and shutdown().
openAIInitialized
final AtomicBoolean com.runehive.content.ai.LazyAIManager.openAIInitialized = new AtomicBoolean(false) static private
Definition at line 20 of file LazyAIManager.java.
Referenced by handleGandalfAIClick(), initializeOpenAIAndProcess(), initializeOpenAIServices(), isInitialized(), and shutdown().
openAIService
volatile OpenAIService com.runehive.content.ai.LazyAIManager.openAIService static private
Definition at line 26 of file LazyAIManager.java.
Referenced by clearPlayerConsent(), getOpenAIService(), initializeOpenAIServices(), and shutdown().
sessionConsents
final Set<String> com.runehive.content.ai.LazyAIManager.sessionConsents = ConcurrentHashMap.newKeySet() static private
Definition at line 23 of file LazyAIManager.java.
Referenced by clearPlayerConsent(), handleGandalfAIClick(), showOpenAIConnectionOffer(), shutdown(), and startInactivityTimer().
The documentation for this class was generated from the following file:
java/com/runehive/content/ai/LazyAIManager.java