RuneHive-Game: com.runehive.content.activity.Activity Class Reference
com.runehive.content.activity.Activity Class Reference abstract
A Activity object constructs an in-game activity and sequences it through the start() and finish() methods with a
cooldown set in game ticks.
Public Member Functions
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canTeleport (Player player)
Called when the player attempts to teleport.
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
abstract void cleanup ()
Cleans up the activity when finished.
void cooldown (int cooldown)
Applies a cooldown.
ActivityDeathType deathType ()
abstract void finish ()
Finishes the activity.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
abstract ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
boolean onEvent (Player player, InteractionEvent interactionEvent)
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
void update ()
The update method.
Static Public Member Functions
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Member Functions
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
abstract void start ()
Starts the next activity stage.
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Static Protected Attributes
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Private Attributes
final int cooldown
The sequencing cooldown.
int instance
The activity instance level.
Activity_Panel panel
The panel for this activity.
int ticks
The remaining game ticks.
Detailed Description
A Activity object constructs an in-game activity and sequences it through the start() and finish() methods with a
cooldown set in game ticks.
Author
Michael | Chex
Definition at line 31 of file Activity.java.
Constructor & Destructor Documentation
Activity()
com.runehive.content.activity.Activity.Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
Definition at line 55 of file Activity.java.
{
        this.instance = instance;
        this.cooldown = cooldown;
    }
References cooldown, and instance.
Referenced by com.runehive.content.activity.GroupActivity.addActivity(), com.runehive.content.activity.GroupActivity.finish(), com.runehive.content.activity.GroupActivity.getActivity(), and search().
Member Function Documentation
add()
void com.runehive.content.activity.Activity.add (Mob mob)
Adds a mob to the activity.
Reimplemented in com.runehive.content.activity.impl.kraken.KrakenActivity.
Definition at line 198 of file Activity.java.
{
        if (mob.isNpc() && !mob.isRegistered()) {
            mob.register();
            mob.unpoison();
            mob.unvenom();
        }
        mob.setActivity(this);
        mob.instance = instance;
        getListener().ifPresent(mob.getCombat()::addListener);
    }
References com.runehive.game.world.entity.mob.Mob.getCombat(), getListener(), instance, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.Entity.isRegistered(), com.runehive.game.world.entity.Entity.register(), com.runehive.game.world.entity.mob.Mob.setActivity(), com.runehive.game.world.entity.mob.Mob.unpoison(), and com.runehive.game.world.entity.mob.Mob.unvenom().
Referenced by com.runehive.content.activity.GroupActivity.addActivity(), com.runehive.content.activity.impl.barrows.Barrows.clickObject(), com.runehive.content.activity.impl.barrows.Barrows.create(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.create(), com.runehive.content.activity.impl.fightcaves.FightCaves.create(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.create(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.create(), com.runehive.content.activity.inferno.Inferno.create(), com.runehive.game.action.impl.TutorialActivity.create(), com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onStart(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.spawn(), com.runehive.content.activity.impl.CerberusActivity.start(), com.runehive.content.activity.impl.fightcaves.FightCaves.start(), com.runehive.content.activity.impl.magearena.MageArena.start(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.start(), com.runehive.content.activity.inferno.Inferno.start(), com.runehive.content.activity.randomevent.RandomEvent.start(), com.runehive.game.action.impl.TutorialActivity.start(), com.runehive.content.activity.impl.barrows.Barrows.summon(), and com.runehive.content.activity.impl.warriorguild.WarriorGuild.summon().
canDrinkPotions()
boolean com.runehive.content.activity.Activity.canDrinkPotions (Player player)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaActivity.
Definition at line 106 of file Activity.java.
{
        return true;
    }
canEat()
boolean com.runehive.content.activity.Activity.canEat (Player player, FoodData foodType)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaActivity.
Definition at line 94 of file Activity.java.
{
        return true;
    }
canEquipItem()
boolean com.runehive.content.activity.Activity.canEquipItem (Player player, Item item, EquipmentType type)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaActivity.
Definition at line 90 of file Activity.java.
{
        return true;
    }
canLogout()
boolean com.runehive.content.activity.Activity.canLogout (Player player)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaActivity, and com.runehive.content.activity.impl.pestcontrol.PestControlGame.
Definition at line 110 of file Activity.java.
{
        return true;
    }
canSpellCast()
boolean com.runehive.content.activity.Activity.canSpellCast (Player player)
Definition at line 114 of file Activity.java.
{
        return true;
    }
canTeleport()
boolean com.runehive.content.activity.Activity.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.CerberusActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.JailActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.impl.zulrah.ZulrahActivity, and com.runehive.content.activity.inferno.Inferno.
Definition at line 193 of file Activity.java.
{
        return false;
    }
canUsePrayer()
boolean com.runehive.content.activity.Activity.canUsePrayer (Player player)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaActivity, and com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.
Definition at line 102 of file Activity.java.
{
        return true;
    }
canUseSpecial()
boolean com.runehive.content.activity.Activity.canUseSpecial (Player player)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaActivity.
Definition at line 98 of file Activity.java.
{
        return true;
    }
cleanup()
abstract void com.runehive.content.activity.Activity.cleanup () abstract
Cleans up the activity when finished.
Reimplemented in com.runehive.content.activity.GroupActivity, com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.CerberusActivity, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.JailActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.impl.zulrah.ZulrahActivity, com.runehive.content.activity.inferno.Inferno, com.runehive.content.activity.randomevent.RandomEvent, and com.runehive.game.action.impl.TutorialActivity.
Referenced by com.runehive.game.world.entity.mob.Mob.setActivity().
clickButton()
boolean com.runehive.content.activity.Activity.clickButton (Player player, ClickButtonInteractionEvent event) protected
Reimplemented in com.runehive.game.action.impl.TutorialActivity.
Definition at line 298 of file Activity.java.
{
        return false;
    }
Referenced by onEvent().
clickItem()
boolean com.runehive.content.activity.Activity.clickItem (Player player, ItemInteractionEvent event) protected
Definition at line 286 of file Activity.java.
{
        return false;
    }
Referenced by onEvent().
clickNpc()
boolean com.runehive.content.activity.Activity.clickNpc (Player player, NpcInteractionEvent event) protected
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.randomevent.impl.DrillDemonEvent, com.runehive.content.activity.randomevent.impl.GenieEvent, and com.runehive.content.activity.randomevent.impl.MimeEvent.
Definition at line 290 of file Activity.java.
{
        return false;
    }
Referenced by onEvent().
clickObject()
boolean com.runehive.content.activity.Activity.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.pestcontrol.PestControlGame, and com.runehive.content.activity.impl.warriorguild.WarriorGuild.
Definition at line 294 of file Activity.java.
{
        return false;
    }
Referenced by onEvent().
cooldown()
void com.runehive.content.activity.Activity.cooldown (int cooldown)
Applies a cooldown.
Reimplemented in com.runehive.game.action.impl.TutorialActivity.
Definition at line 244 of file Activity.java.
{
        this.ticks = cooldown;
    }
References cooldown.
deathType()
ActivityDeathType com.runehive.content.activity.Activity.deathType ()
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.impl.zulrah.ZulrahActivity, and com.runehive.content.activity.randomevent.RandomEvent.
Definition at line 263 of file Activity.java.
{
        return ActivityDeathType.NORMAL;
    }
References com.runehive.content.activity.ActivityDeathType.NORMAL.
evaluate()
boolean com.runehive.content.activity.Activity.evaluate (Mob mob, Predicate< Activity > predicate) static
Definition at line 74 of file Activity.java.
{
        return mob != null && mob.activity != null && predicate.test(mob.activity);
    }
References com.runehive.game.world.entity.mob.Mob.activity.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.mob.player.Player.canLogout(), com.runehive.content.skill.impl.magic.spell.SpellCasting.cast(), com.runehive.content.skill.impl.magic.spell.SpellCasting.cast(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.enable(), com.runehive.content.event.EventDispatcher.execute(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), com.runehive.game.task.impl.PlayerRemovalTask.tick(), com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.withinDistance(), and com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.withinDistance().
finish()
abstract void com.runehive.content.activity.Activity.finish () abstract
Finishes the activity.
Reimplemented in com.runehive.content.activity.GroupActivity, com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.CerberusActivity, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.JailActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame, com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.impl.zulrah.ZulrahActivity, com.runehive.content.activity.inferno.Inferno, com.runehive.content.activity.randomevent.RandomEvent, and com.runehive.game.action.impl.TutorialActivity.
Referenced by onDeath(), and sequence().
finishCooldown()
final void com.runehive.content.activity.Activity.finishCooldown () protected
Sets the cooldown flag to FINISH.
Definition at line 249 of file Activity.java.
{
        ticks = FINISH;
    }
References FINISH, and ticks.
Referenced by com.runehive.content.activity.randomevent.impl.DrillDemonEvent.clickNpc(), com.runehive.content.activity.randomevent.impl.GenieEvent.clickNpc(), com.runehive.content.activity.randomevent.impl.MimeEvent.clickNpc(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.clickObject(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.onDeath(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.onLogout(), com.runehive.content.activity.randomevent.RandomEvent.onRegionChange(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.sequence(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.sequence(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.start(), and com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.start().
forActivity()
void com.runehive.content.activity.Activity.forActivity (Mob mob, Consumer< Activity > consumer) static
Definition at line 78 of file Activity.java.
{
        if (mob == null) {
            return;
        }
        if (mob.activity == null) {
            return;
        }
        consumer.accept(mob.activity);
    }
References com.runehive.game.world.entity.mob.Mob.activity.
Referenced by com.runehive.game.world.entity.mob.npc.Npc.appendDeath(), com.runehive.game.world.entity.mob.player.Player.loadRegion(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.game.world.entity.mob.player.PlayerAssistant.sequence(), and com.runehive.game.world.entity.mob.player.Player.unregister().
getInstance()
int com.runehive.content.activity.Activity.getInstance ()
Gets this activity's instance level.
Definition at line 268 of file Activity.java.
{
        return instance;
    }
References instance.
Referenced by com.runehive.content.activity.impl.magearena.MageArena.meteors(), and com.runehive.content.activity.impl.magearena.MageArena.start().
getListener()
Optional<? extends ActivityListener<? extends Activity > > com.runehive.content.activity.Activity.getListener () protected
Gets an Optional of the ActivityListener for this activity.
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.pestcontrol.PestControlGame, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.impl.zulrah.ZulrahActivity, and com.runehive.content.activity.inferno.Inferno.
Definition at line 282 of file Activity.java.
{
        return Optional.empty();
    }
Referenced by add(), and remove().
getPanel()
Optional< Activity_Panel > com.runehive.content.activity.Activity.getPanel ()
Gets an optional of the activity panel.
Definition at line 183 of file Activity.java.
{
        return Optional.ofNullable(panel);
    }
References panel.
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.finish().
getTicks()
int com.runehive.content.activity.Activity.getTicks ()
Gets the current ticks.
Definition at line 277 of file Activity.java.
{
        return ticks;
    }
References ticks.
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.finished(), com.runehive.content.activity.lobby.LobbyNode.finished(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.sequence(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.sequence(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.update(), and com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.update().
getType()
abstract ActivityType com.runehive.content.activity.Activity.getType () abstract
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.CerberusActivity, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.JailActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame, com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.impl.zulrah.ZulrahActivity, com.runehive.content.activity.inferno.Inferno, com.runehive.content.activity.randomevent.RandomEvent, and com.runehive.game.action.impl.TutorialActivity.
isPaused()
final boolean com.runehive.content.activity.Activity.isPaused () protected
Checks if the cooldown is paused.
Definition at line 259 of file Activity.java.
{
        return ticks == PAUSE;
    }
References PAUSE, and ticks.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.sequence(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.update().
itemContainerAction()
boolean com.runehive.content.activity.Activity.itemContainerAction (Player player, ItemContainerInteractionEvent event) protected
Definition at line 314 of file Activity.java.
{
        return false;
    }
Referenced by onEvent().
onDeath()
void com.runehive.content.activity.Activity.onDeath (Mob mob)
Called when the player die.
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.CerberusActivity, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.JailActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, and com.runehive.content.activity.impl.zulrah.ZulrahActivity.
Definition at line 157 of file Activity.java.
{
        if (mob.isNpc()) {
            World.schedule(new NpcDeath(mob.getNpc()));
            return;
        }
        remove(mob);
        mob.move(Config.DEFAULT_POSITION);
        mob.unpoison();
        mob.unvenom();
        finish();
    }
References com.runehive.Config.DEFAULT_POSITION, finish(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.Mob.unpoison(), and com.runehive.game.world.entity.mob.Mob.unvenom().
onEvent()
boolean com.runehive.content.activity.Activity.onEvent (Player player, InteractionEvent interactionEvent)
Implements com.runehive.content.event.InteractionEventListener.
Definition at line 319 of file Activity.java.
{
        final EventDispatcher dispatcher = new EventDispatcher(interactionEvent);
        dispatcher.dispatch(InteractionEvent.InteractionType.CLICK_BUTTON, e -> clickButton(player, (ClickButtonInteractionEvent) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.ITEM_ON_ITEM, e -> useItem(player, (ItemOnItemInteractionEvent) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.ITEM_ON_OBJECT, e -> useItem(player, (ItemOnObjectInteractionEvent) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.FIRST_ITEM_CLICK, e -> clickItem(player, (FirstItemClickInteractionEvent) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.SECOND_ITEM_CLICK, e -> clickItem(player, (SecondItemClickInteractionEvent) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.THIRD_ITEM_CLICK, e -> clickItem(player, (ThirdItemClickInteractionEvent) e));
//      dispatcher.dispatch(InteractionType.FOURTH_ITEM_CLICK, e -> clickItem(player, (FourthItemClick) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.FIRST_CLICK_NPC, e -> clickNpc(player, (FirstNpcClick) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.SECOND_CLICK_NPC, e -> clickNpc(player, (SecondNpcClick) e));
//      dispatcher.dispatch(InteractionType.CLICK_NPC, e -> clickNpc(player, (ThirdNpcClick) e));
//      dispatcher.dispatch(InteractionType.CLICK_NPC, e -> clickNpc(player, (FourthNpcClick) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.FIRST_CLICK_OBJECT, e -> clickObject(player, (FirstObjectClick) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.SECOND_CLICK_OBJECT, e -> clickObject(player, (SecondObjectClick) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.THIRD_CLICK_OBJECT, e -> clickObject(player, (ThirdObjectClick) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.PICKUP_ITEM, e -> pickupItem(player, (PickupItemInteractionEvent) e));
        dispatcher.dispatch(InteractionEvent.InteractionType.ITEM_CONTAINER_INTERACTION_EVENT, e -> itemContainerAction(player, (ItemContainerInteractionEvent) e));
        return interactionEvent.isHandled();
    }
References com.runehive.content.event.InteractionEvent.InteractionType.CLICK_BUTTON, clickButton(), clickItem(), clickNpc(), clickObject(), com.runehive.content.event.EventDispatcher.dispatch(), com.runehive.content.event.InteractionEvent.InteractionType.FIRST_CLICK_NPC, com.runehive.content.event.InteractionEvent.InteractionType.FIRST_CLICK_OBJECT, com.runehive.content.event.InteractionEvent.InteractionType.FIRST_ITEM_CLICK, com.runehive.content.event.InteractionEvent.isHandled(), com.runehive.content.event.InteractionEvent.InteractionType.ITEM_CONTAINER_INTERACTION_EVENT, com.runehive.content.event.InteractionEvent.InteractionType.ITEM_ON_ITEM, com.runehive.content.event.InteractionEvent.InteractionType.ITEM_ON_OBJECT, itemContainerAction(), com.runehive.content.event.InteractionEvent.InteractionType.PICKUP_ITEM, pickupItem(), com.runehive.content.event.InteractionEvent.InteractionType.SECOND_CLICK_NPC, com.runehive.content.event.InteractionEvent.InteractionType.SECOND_CLICK_OBJECT, com.runehive.content.event.InteractionEvent.InteractionType.SECOND_ITEM_CLICK, com.runehive.content.event.InteractionEvent.InteractionType.THIRD_CLICK_OBJECT, com.runehive.content.event.InteractionEvent.InteractionType.THIRD_ITEM_CLICK, and useItem().
onLogout()
void com.runehive.content.activity.Activity.onLogout (Player player)
Called when the player logs out.
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.CerberusActivity, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.inferno.Inferno, com.runehive.content.activity.randomevent.RandomEvent, and com.runehive.game.action.impl.TutorialActivity.
Definition at line 152 of file Activity.java.
{
        remove(player);
    }
onRegionChange()
void com.runehive.content.activity.Activity.onRegionChange (Player player)
Called when the player changes region.
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.CerberusActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.JailActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.impl.zulrah.ZulrahActivity, com.runehive.content.activity.inferno.Inferno, com.runehive.content.activity.randomevent.RandomEvent, and com.runehive.game.action.impl.TutorialActivity.
Definition at line 188 of file Activity.java.
{
        remove(player);
    }
onStep()
boolean com.runehive.content.activity.Activity.onStep (Mob mob)
Definition at line 173 of file Activity.java.
{
        return false;
    }
pause()
final void com.runehive.content.activity.Activity.pause () protected
Sets the cooldown flag to PAUSE.
Definition at line 254 of file Activity.java.
{
        ticks = PAUSE;
    }
References PAUSE, and ticks.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.create(), setPause(), com.runehive.content.activity.impl.CerberusActivity.start(), com.runehive.content.activity.impl.fightcaves.FightCaves.start(), com.runehive.content.activity.impl.godwars.GodwarsActivity.start(), com.runehive.content.activity.impl.kraken.KrakenActivity.start(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.start(), com.runehive.content.activity.inferno.Inferno.start(), and com.runehive.game.action.impl.TutorialActivity.start().
pickupItem()
boolean com.runehive.content.activity.Activity.pickupItem (Player player, PickupItemInteractionEvent event) protected
Reimplemented in com.runehive.content.activity.impl.warriorguild.WarriorGuild.
Definition at line 306 of file Activity.java.
{
        return false;
    }
Referenced by onEvent().
remove()
void com.runehive.content.activity.Activity.remove (Mob mob)
Removes a mob from the activity.
Reimplemented in com.runehive.content.activity.impl.kraken.KrakenActivity.
Definition at line 210 of file Activity.java.
{
        getListener().ifPresent(mob.getCombat()::removeListener);
        if (mob.isNpc()) {
            mob.getNpc().unregister();
        } else {
            mob.instance = Entity.DEFAULT_INSTANCE;
            mob.getPlayer().setActivity(null);
            mob.getPlayer().graphic(Graphic.RESET, true);
            mob.getPlayer().animate(Animation.RESET, true);
           // mob.getPlayer().send(new SendMessage("You have lost your current progress as you have teleported."));
        }
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, getListener(), com.runehive.game.Animation.RESET, and com.runehive.game.Graphic.RESET.
removeAll()
void com.runehive.content.activity.Activity.removeAll (Mob... mobs)
Removes all mobs from the activity.
Definition at line 225 of file Activity.java.
{
        if (mobs.length != 0)
            for (Mob mob : mobs) {
                if (mob.isRegistered())
                    remove(mob);
            }
    }
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canDrinkPotions(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEat(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canLogout(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canUsePrayer(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canUseSpecial(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.clickObject(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.finish(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.onDeath(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.onLogout(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.sequence(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
resetCooldown()
final void com.runehive.content.activity.Activity.resetCooldown () protected
Resets the remaining ticks to the cached cooldown ticks.
Definition at line 239 of file Activity.java.
{
        cooldown(cooldown);
    }
References cooldown.
Referenced by com.runehive.content.activity.impl.fightcaves.FightCaves.create(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.create(), com.runehive.content.activity.inferno.Inferno.create(), com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.start(), and com.runehive.content.activity.randomevent.RandomEvent.start().
restart()
void com.runehive.content.activity.Activity.restart (int delay, Runnable runnable) protected
Definition at line 169 of file Activity.java.
{
        World.schedule(delay, runnable::run); //deprecated lambda
    }
References com.runehive.game.world.World.schedule().
Referenced by com.runehive.content.activity.impl.VorkathActivity.finish().
search()
static< T extends Activity > Optional< T > com.runehive.content.activity.Activity.search (Player player, Class< T > clazz) static
Definition at line 60 of file Activity.java.
{
        final Activity activity = player.activity;
        if (activity == null) {
            return Optional.empty();
        }
        if (clazz.isInstance(activity)) {
            return Optional.of(clazz.cast(activity));
        }
        return Optional.empty();
    }
References Activity(), and com.runehive.game.world.entity.mob.Mob.activity.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), com.runehive.content.activity.impl.duelarena.DuelRule.canSet(), com.runehive.content.activity.impl.duelarena.DuelRule.set(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.showDuelRulesOnSecondScreen(), com.runehive.game.task.impl.PlayerRemovalTask.tick(), and com.runehive.content.activity.impl.duelarena.DuelRule.validateEquipmentRules().
sequence()
void com.runehive.content.activity.Activity.sequence ()
Sequences the activity.
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.pestcontrol.PestControlGame, and com.runehive.content.activity.impl.warriorguild.WarriorGuild.
Definition at line 119 of file Activity.java.
{
        update();
        if (ticks == PAUSE) {
            return;
        }
        if (ticks > 0) {
            ticks--;
        } else if (ticks == START) {
            start();
        } else if (ticks == FINISH) {
            finish();
        }
    }
References FINISH, finish(), PAUSE, START, start(), ticks, and update().
Referenced by com.runehive.content.activity.lobby.LobbyManager.sequenceActive().
setInstance()
void com.runehive.content.activity.Activity.setInstance (int instance)
Definition at line 272 of file Activity.java.
{
        this.instance = instance;
    }
References instance.
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlGame(), and com.runehive.game.action.impl.TutorialActivity.start().
setPanel()
void com.runehive.content.activity.Activity.setPanel (Activity_Panel panel)
Sets the activity panel.
Definition at line 178 of file Activity.java.
{
        this.panel = panel;
    }
References panel.
setPause()
void com.runehive.content.activity.Activity.setPause (boolean pause)
Sets the pause state of the activity.
Definition at line 234 of file Activity.java.
{
        ticks = pause ? PAUSE : START;
    }
References PAUSE, pause(), START, and ticks.
start()
abstract void com.runehive.content.activity.Activity.start () abstract protected
Starts the next activity stage.
Reimplemented in com.runehive.content.activity.GroupActivity, com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.CerberusActivity, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.JailActivity, com.runehive.content.activity.impl.kraken.KrakenActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.VorkathActivity, com.runehive.content.activity.impl.warriorguild.WarriorGuild, com.runehive.content.activity.impl.zulrah.ZulrahActivity, com.runehive.content.activity.inferno.Inferno, com.runehive.content.activity.lobby.LobbyNode, com.runehive.content.activity.randomevent.RandomEvent, and com.runehive.game.action.impl.TutorialActivity.
Referenced by sequence(), and com.runehive.content.activity.GroupActivity.start().
update()
void com.runehive.content.activity.Activity.update ()
The update method.
Reimplemented in com.runehive.content.activity.impl.barrows.Barrows, com.runehive.content.activity.impl.duelarena.DuelArenaActivity, com.runehive.content.activity.impl.fightcaves.FightCaves, com.runehive.content.activity.impl.godwars.GodwarsActivity, com.runehive.content.activity.impl.magearena.MageArena, com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster, com.runehive.content.activity.impl.warriorguild.WarriorGuild, and com.runehive.content.activity.inferno.Inferno.
Definition at line 145 of file Activity.java.
{
    }
Referenced by com.runehive.game.action.impl.TutorialActivity.next(), sequence(), and com.runehive.game.action.impl.TutorialActivity.start().
useItem() [1/2]
boolean com.runehive.content.activity.Activity.useItem (Player player, ItemOnItemInteractionEvent event) protected
Definition at line 302 of file Activity.java.
{
        return false;
    }
Referenced by onEvent().
useItem() [2/2]
boolean com.runehive.content.activity.Activity.useItem (Player player, ItemOnObjectInteractionEvent event) protected
Reimplemented in com.runehive.content.activity.impl.warriorguild.WarriorGuild.
Definition at line 310 of file Activity.java.
{
        return false;
    }
Member Data Documentation
cooldown
final int com.runehive.content.activity.Activity.cooldown private
The sequencing cooldown.
Definition at line 43 of file Activity.java.
Referenced by Activity(), com.runehive.content.activity.lobby.LobbyManager.canStart(), cooldown(), com.runehive.content.activity.GroupActivity.GroupActivity(), com.runehive.game.action.impl.TutorialActivity.next(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.randomevent.RandomEvent.RandomEvent(), resetCooldown(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.sequence(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.start(), com.runehive.content.activity.impl.magearena.MageArena.start(), com.runehive.content.activity.lobby.LobbyNode.start(), com.runehive.content.activity.randomevent.RandomEvent.start(), and com.runehive.game.action.impl.TutorialActivity.start().
FINISH
final int com.runehive.content.activity.Activity.FINISH = -1 static protected
The 'finish' cooldown id.
Definition at line 37 of file Activity.java.
Referenced by finishCooldown(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.finished(), com.runehive.content.activity.lobby.LobbyNode.finished(), sequence(), com.runehive.content.activity.impl.magearena.MageArena.start(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.update().
instance
int com.runehive.content.activity.Activity.instance private
The activity instance level.
Definition at line 46 of file Activity.java.
Referenced by Activity(), add(), com.runehive.content.activity.impl.CerberusActivity.CerberusActivity(), com.runehive.content.activity.impl.fightcaves.FightCaves.FightCaves(), getInstance(), com.runehive.content.activity.inferno.Inferno.Inferno(), com.runehive.content.activity.impl.kraken.KrakenActivity.KrakenActivity(), com.runehive.content.activity.impl.magearena.MageArena.MageArena(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.RecipeForDisaster(), setInstance(), com.runehive.content.activity.impl.VorkathActivity.VorkathActivity(), and com.runehive.content.activity.impl.zulrah.ZulrahActivity.ZulrahActivity().
panel
Activity_Panel com.runehive.content.activity.Activity.panel private
The panel for this activity.
Definition at line 52 of file Activity.java.
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.createActivity(), getPanel(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.sequence(), and setPanel().
PAUSE
final int com.runehive.content.activity.Activity.PAUSE = -2 static protected
The 'pause' cooldown id.
Definition at line 40 of file Activity.java.
Referenced by isPaused(), pause(), sequence(), and setPause().
START
final int com.runehive.content.activity.Activity.START = 0 static protected
The 'start' cooldown id.
Definition at line 34 of file Activity.java.
Referenced by sequence(), and setPause().
ticks
int com.runehive.content.activity.Activity.ticks private
The remaining game ticks.
Definition at line 49 of file Activity.java.
Referenced by finishCooldown(), getTicks(), isPaused(), pause(), sequence(), and setPause().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/Activity.java