RuneHive-Game: com.runehive.game.world.entity.combat.magic.MagicSpell Class Reference
com.runehive.game.world.entity.combat.magic.MagicSpell Class Reference abstract
Represents a combat spell.
Public Member Functions
Optional< Item[]> equipmentRequired ()
Public Attributes
final int level
final RequiredRune[] runes
Package Functions
boolean canCast (Mob attacker, Optional< Mob > defender)
MagicSpell (int level, double baseExperience, RequiredRune... runes)
Package Attributes
final double baseExperience
Detailed Description
Represents a combat spell.
Created by mmaks on 8/24/2017.
Definition at line 15 of file MagicSpell.java.
Constructor & Destructor Documentation
MagicSpell()
com.runehive.game.world.entity.combat.magic.MagicSpell.MagicSpell (int level, double baseExperience, RequiredRune... runes) package
Definition at line 23 of file MagicSpell.java.
{
        this.level = level;
        this.baseExperience = baseExperience;
        this.runes = runes;
    }
References baseExperience, level, and runes.
Member Function Documentation
canCast()
boolean com.runehive.game.world.entity.combat.magic.MagicSpell.canCast (Mob attacker, Optional< Mob > defender) package
Definition at line 33 of file MagicSpell.java.
{
        if(attacker.isNpc()) {
            return true;
        }
        Player player = attacker.getPlayer();
        if(player.skills.getLevel(Skill.MAGIC) < level) {
            player.send(new SendMessage("You need a Magic level of " + level + " to cast this spell."));
            player.getCombat().reset();
            return false;
        }
        if(equipmentRequired().isPresent() && !player.equipment.containsAll(equipmentRequired().get())) {
            player.send(new SendMessage("You do not have the required equipment to cast this spell."));
            player.getCombat().reset();
            return false;
        }
        return MagicRune.hasRunes(player, runes);
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.world.entity.mob.player.Player.equipment, equipmentRequired(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.game.world.entity.mob.Mob.isNpc(), level, com.runehive.game.world.entity.skill.Skill.MAGIC, runes, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.skills.
equipmentRequired()
Optional< Item[]> com.runehive.game.world.entity.combat.magic.MagicSpell.equipmentRequired ()
Definition at line 29 of file MagicSpell.java.
{
        return Optional.empty();
    }
Referenced by canCast().
Member Data Documentation
baseExperience
final double com.runehive.game.world.entity.combat.magic.MagicSpell.baseExperience package
Definition at line 19 of file MagicSpell.java.
Referenced by MagicSpell().
level
final int com.runehive.game.world.entity.combat.magic.MagicSpell.level
Definition at line 17 of file MagicSpell.java.
Referenced by canCast(), and MagicSpell().
runes
final RequiredRune [] com.runehive.game.world.entity.combat.magic.MagicSpell.runes
Definition at line 21 of file MagicSpell.java.
Referenced by canCast(), and MagicSpell().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/magic/MagicSpell.java