RuneHive-Game: com.runehive.content.skill.impl.crafting.Crafting Class Reference
com.runehive.content.skill.impl.crafting.Crafting Class Reference
Handles the crafting skill.
Public Member Functions
boolean craft (Player player, int index, int amount)
Crafting (int level, double experience)
boolean start (Player player, Craftable craftable, int index, int amount)
Public Member Functions inherited from com.runehive.game.world.entity.skill.Skill
double addExperience (double amount)
Adds experiences to this skill by the given amount.
void addLevel (int amount)
Adds levels to this skill by the given amount.
void divideExperience (double amount)
Divides the current experience of this skill by a given amount.
void divideLevel (double amount)
Divides the current level of this skill by a given amount.
double getExperience ()
Gets the skill experience.
int getLevel ()
Gets the current skill level.
int getMaxLevel ()
Gets the maximum skill level.
int getRoundedExperience ()
Gets the floor experience.
int getSkill ()
Gets the skill id.
boolean isDoingSkill ()
double modifyExperience (Function< Double, Double > function)
Modifies the current experience with a given function.
double modifyExperience (Function< Double, Double > function, int lowerBounds, int upperBounds)
Modifies the current experience with a given function.
void modifyLevel (Function< Integer, Integer > function)
Modifies the current level with a given function.
void modifyLevel (Function< Integer, Integer > function, int lowerBounds, int upperBounds)
Modifies the current level with a given function.
void multiplyExperience (double amount)
Multiplies the current experience of this skill by a given amount.
void multiplyLevel (double amount)
Multiplies the current level of this skill by a given amount.
boolean onEvent (Player player, InteractionEvent interactionEvent)
void removeExperience (double amount)
Removes experiences from this skill by the given amount.
void removeLevel (int amount)
Removes levels from this skill by the given amount.
boolean reqLevel (int level)
Determines if your level is greater than or equal to level.
void setDoingSkill (boolean doingSkill)
void setExperience (double experience)
Sets the experience for this skill.
void setLevel (int level)
Sets the level for this skill.
void setMaxLevel (int maxLevel)
Sets the maximum level for this skill.
Skill (int skill, int level, double experience)
Constructs a new Skill.
String toString ()
Static Public Member Functions
static void addCraftable (Craftable craftable)
Static Public Member Functions inherited from com.runehive.game.world.entity.skill.Skill
static Function< Integer, Integer > add (int amount)
Creates a function that adds a number by an amount.
static Function< Integer, Integer > divide (double amount)
Creates a function that divides a number by an amount.
static final int getExperienceForLevel (int level)
Gets the experience for a given level.
static final byte getLevelForExperience (double experience)
Gets the level for a given experience amount.
static String getName (int skill)
Gets the name for a skill id.
static Function< Integer, Integer > multiply (double amount)
Creates a function that multiplies a number by an amount.
static Function< Integer, Integer > subtract (int amount)
Creates a function that subtracts a number by an amount.
Protected Member Functions
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Protected Member Functions inherited from com.runehive.game.world.entity.skill.Skill
boolean clickItem (Player player, ItemInteractionEvent event)
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
double modifier ()
Private Member Functions
Action< Player > craft (Player player, Craftable craftable, CraftableItem item, int index, int amount)
Static Private Member Functions
static Craftable getCraftable (int use, int with)
Static Private Attributes
static final String CRAFTABLE_KEY = "CRAFTABLE_KEY"
The craftable key.
static final HashMap< Integer, Craftable > CRAFTABLES = new HashMap<>()
The craftable map.
static final Object[][] LEATHER_ARMOR_IDS
The leather armour data.
Additional Inherited Members
Public Attributes inherited from com.runehive.game.world.entity.skill.Skill
transient final Stopwatch stopwatch = Stopwatch.start()
Static Public Attributes inherited from com.runehive.game.world.entity.skill.Skill
static final int AGILITY = 16
The agility skill id.
static final int ATTACK = 0
The attack skill id.
static final int CONSTRUCTION = 21
The construction skill id.
static final int COOKING = 7
The cooking skill id.
static final int CRAFTING = 12
The crafting skill id.
static final int DEFENCE = 1
The defence skill id.
static final int FARMING = 19
The farming skill id.
static final int FIREMAKING = 11
The firemaking skill id.
static final int FISHING = 10
The fishing skill id.
static final int FLETCHING = 9
The fletching skill id.
static final int HERBLORE = 15
The herblore skill id.
static final int HITPOINTS = 3
The hitpoints skill id.
static final int HUNTER = 22
The hunter skill id.
static final int[][] INTERFACE_DATA
Skill tab string data.
static final int MAGIC = 6
The magic skill id.
static final int MINING = 14
The mining skill id.
static final int PRAYER = 5
The prayer skill id.
static final int RANGED = 4
The ranged skill id.
static final int RUNECRAFTING = 20
The runecrafting skill id.
static final int SKILL_COUNT = 23
The amount of available skills.
static final int SLAYER = 18
The slayer skill id.
static final int SMITHING = 13
The smithing skill id.
static final int STRENGTH = 2
The strength skill id.
static final int THIEVING = 17
The thieving skill id.
static final int TOTAL_SKILL_LEVEL = 99 * SKILL_COUNT
The total skill amount.
static final int WOODCUTTING = 8
The woodcutting skill id.
Detailed Description
Handles the crafting skill.
Author
Daniel
Definition at line 30 of file Crafting.java.
Constructor & Destructor Documentation
Crafting()
com.runehive.content.skill.impl.crafting.Crafting.Crafting (int level, double experience)
Definition at line 49 of file Crafting.java.
{
        super(Skill.CRAFTING, level, experience);
    }
References com.runehive.game.world.entity.skill.Skill.experience, com.runehive.game.world.entity.skill.Skill.level, and com.runehive.game.world.entity.skill.Skill.Skill().
Member Function Documentation
addCraftable()
void com.runehive.content.skill.impl.crafting.Crafting.addCraftable (Craftable craftable) static
Definition at line 53 of file Crafting.java.
{
        if (CRAFTABLES.put(craftable.getWith().getId(), craftable) != null) {
            System.out.println("[Crafting] Conflicting item values: " + craftable.getWith().getId() + " Type: " + craftable.getName());
        }
    }
References CRAFTABLES, com.runehive.game.world.items.Item.getId(), com.runehive.content.skill.impl.crafting.Craftable.getName(), and com.runehive.content.skill.impl.crafting.Craftable.getWith().
Referenced by com.runehive.content.skill.impl.crafting.impl.Gem.load(), and com.runehive.content.skill.impl.crafting.impl.Hide.load().
clickButton()
boolean com.runehive.content.skill.impl.crafting.Crafting.clickButton (Player player, ClickButtonInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 195 of file Crafting.java.
{
        if (Tanning.click(player, event.getButton())) {
            return true;
        }
        if (Glass.click(player, event.getButton())) {
            return true;
        }
        if (!player.attributes.has(CRAFTABLE_KEY)) {
            return false;
        }
        int button = event.getButton();
        if (button == 2422) {
            return false;
        }
        if (String.valueOf(player.attributes.getObject(CRAFTABLE_KEY)).equals("HIDE")) {
            for (Object[] i : LEATHER_ARMOR_IDS) {
                if ((int) i[0] == button) {
                    player.interfaceManager.close();
                    start(player, (Craftable) i[2], 0, (int) i[1]);
                    return true;
                }
            }
        }
        Craftable craftable = player.attributes.get(CRAFTABLE_KEY, Craftable.class);
        switch (button) {
            /* Option 1 - Make all */
            case 1747:
                start(player, craftable, 0, player.inventory.computeAmountForId(craftable.getWith().getId()));
                return true;
            /* Option 1 - Make 1 */
            case 2799:
            case 8909:
            case 8874:
            case 8889:
            case 8949:
                start(player, craftable, 0, 1);
                return true;
            /* Option 1 - Make 5 */
            case 2798:
            case 8908:
            case 8873:
            case 8888:
            case 8948:
                start(player, craftable, 0, 5);
                return true;
            /* Option 1 - Make 10 */
            case 1748:
            case 8907:
            case 8872:
            case 8887:
            case 8947:
                start(player, craftable, 0, 10);
                return true;
            /* Option 1 - Make X */
            case 8906:
            case 8871:
            case 8886:
            case 6212:
            case 8946:
                player.send(new SendInputAmount("Enter amount", 10, input -> start(player, craftable, 0, Integer.parseInt(input))));
                return true;
            /* Option 2 - Make 1 */
            case 8913:
            case 8878:
            case 8893:
            case 8953:
                start(player, craftable, 1, 1);
                return true;
            /* Option 2 - Make 5 */
            case 8912:
            case 8877:
            case 8892:
            case 8952:
                start(player, craftable, 1, 5);
                return true;
            /* Option 2 - Make 10 */
            case 8911:
            case 8876:
            case 8891:
            case 8951:
                start(player, craftable, 1, 10);
                return true;
            /* Option 2 - Make X */
            case 8910:
            case 8875:
            case 8890:
            case 8950:
                player.send(new SendInputAmount("Enter amount", 10, input -> start(player, craftable, 1, Integer.parseInt(input))));
                return true;
            /* Option 3 - Make 1 */
            case 8917:
            case 8897:
            case 8957:
                start(player, craftable, 2, 1);
                return true;
            /* Option 3 - Make 5 */
            case 8916:
            case 8896:
            case 8956:
                start(player, craftable, 2, 5);
                return true;
            /* Option 3 - Make 10 */
            case 8915:
            case 8895:
            case 8955:
                start(player, craftable, 2, 10);
                return true;
            /* Option 3 - Make X */
            case 8914:
            case 8894:
            case 8954:
                player.send(new SendInputAmount("Enter amount", 10, input -> start(player, craftable, 2, Integer.parseInt(input))));
                return true;
            /* Option 4 - Make 1 */
            case 8921:
            case 8961:
                start(player, craftable, 3, 1);
                return true;
            /* Option 4 - Make 5 */
            case 8920:
            case 8960:
                start(player, craftable, 3, 5);
                return true;
            /* Option 4 - Make 10 */
            case 8919:
            case 8959:
                start(player, craftable, 3, 10);
                return true;
            /* Option 4 - Make X */
            case 8918:
            case 8958:
                player.send(new SendInputAmount("Enter amount", 10, input -> start(player, craftable, 3, Integer.parseInt(input))));
                return true;
            /* Option 5 - Make 1 */
            case 8965:
                start(player, craftable, 4, 1);
                return true;
            /* Option 5 - Make 5 */
            case 8964:
                start(player, craftable, 4, 5);
                return true;
            /* Option 5 - Make 10 */
            case 8963:
                start(player, craftable, 4, 10);
                return true;
            /* Option 5 - Make X */
            case 8962:
                player.send(new SendInputAmount("Enter amount", 10, input -> start(player, craftable, 4, Integer.parseInt(input))));
                return true;
            default:
                return false;
        }
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.skill.impl.crafting.impl.Glass.click(), com.runehive.content.skill.impl.crafting.impl.Tanning.click(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), CRAFTABLE_KEY, com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.world.items.Item.getId(), com.runehive.util.generic.GenericAttributes.getObject(), com.runehive.content.skill.impl.crafting.Craftable.getWith(), com.runehive.util.generic.GenericAttributes.has(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, LEATHER_ARMOR_IDS, com.runehive.game.world.entity.mob.player.Player.send(), and start().
clickNpc()
boolean com.runehive.content.skill.impl.crafting.Crafting.clickNpc (Player player, NpcInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 79 of file Crafting.java.
{
        if (event.getNpc().id == 5811) {
            if (event.getOpcode() == 0) {
                Tanning.open(player);
            } else if (event.getOpcode() == 1) {
                Store.STORES.get("Crafting Store").open(player);
            }
            return true;
        }
        return false;
    }
References com.runehive.content.skill.impl.crafting.impl.Tanning.open(), and com.runehive.content.store.Store.STORES.
clickObject()
boolean com.runehive.content.skill.impl.crafting.Crafting.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 64 of file Crafting.java.
{
        if (event.getObject().getId() == 4309 && event.getOpcode() == 1) {
            Spinning.open(player);
            return true;
        }
        if (event.getObject().getId() == 11601 && event.getOpcode() == 0) {
            Jewellery.open(player);
            return true;
        }
        return false;
    }
References com.runehive.content.skill.impl.crafting.impl.Jewellery.open(), and com.runehive.content.skill.impl.crafting.impl.Spinning.open().
craft() [1/2]
Action< Player > com.runehive.content.skill.impl.crafting.Crafting.craft (Player player, Craftable craftable, CraftableItem item, int index, int amount) private
Definition at line 418 of file Crafting.java.
{
        return new Action<Player>(player, 2, true) {
            int iterations = 0;
            @Override
            public void execute() {
                player.animate(new Animation(craftable.getAnimation()));
                player.skills.addExperience(Skill.CRAFTING, item.getExperience() * Config.CRAFTING_MODIFICATION);
                final boolean saveMaterial = SkillCape.isEquipped(player, SkillCape.CRAFTING) && Utility.random(1, 3) == 1;
                if (!saveMaterial) {
                    player.inventory.removeAll(craftable.getIngredients(index));
                }
                player.inventory.addOrDrop(item.getProduct());
                player.playerAssistant.activateSkilling(1);
                RandomEventHandler.trigger(player);
                if (craftable.getProductionMessage() != null) {
                    player.send(new SendMessage(craftable.getProductionMessage()));
                }
//              if (craftable.getName() == "Gem") {
//                  AchievementHandler.activateTask(player, AchievementList.CUT_250_GEMS, 1);
//              }
                if (++iterations == amount) {
                    cancel();
                    return;
                }
                if (!player.inventory.containsAll(craftable.getIngredients(index))) {
                    cancel();
                    player.send(new SendMessage("<col=369>You have run out of materials."));
                    return;
                }
            }
            @Override
            public String getName() {
                return "Crafting";
            }
            @Override
            public boolean prioritized() {
                return false;
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
        };
    }
References com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.content.skillcape.SkillCape.CRAFTING, com.runehive.Config.CRAFTING_MODIFICATION, com.runehive.content.skill.impl.crafting.Craftable.getAnimation(), com.runehive.content.skill.impl.crafting.CraftableItem.getExperience(), com.runehive.content.skill.impl.crafting.Craftable.getIngredients(), com.runehive.game.world.entity.skill.Skill.getName(), com.runehive.content.skill.impl.crafting.CraftableItem.getProduct(), com.runehive.content.skill.impl.crafting.Craftable.getProductionMessage(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.util.Utility.random(), com.runehive.game.world.items.containers.ItemContainer.removeAll(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.skill.Skill.Skill(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
craft() [2/2]
boolean com.runehive.content.skill.impl.crafting.Crafting.craft (Player player, int index, int amount)
Definition at line 378 of file Crafting.java.
{
        Craftable craftable = player.attributes.get(CRAFTABLE_KEY);
        return start(player, craftable, index, amount);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, CRAFTABLE_KEY, com.runehive.util.generic.GenericAttributes.get(), and start().
Referenced by start().
getCraftable()
Craftable com.runehive.content.skill.impl.crafting.Crafting.getCraftable (int use, int with) static private
Definition at line 59 of file Crafting.java.
{
        return CRAFTABLES.get(use) == null ? CRAFTABLES.get(with) : CRAFTABLES.get(use);
    }
References CRAFTABLES.
Referenced by useItem().
start()
boolean com.runehive.content.skill.impl.crafting.Crafting.start (Player player, Craftable craftable, int index, int amount)
Definition at line 383 of file Crafting.java.
{
        if (craftable == null) {
            return false;
        }
        player.attributes.remove(CRAFTABLE_KEY);
        CraftableItem item = craftable.getCraftableItems()[index];
        player.interfaceManager.close();
        if (player.skills.getLevel(Skill.CRAFTING) < item.getLevel()) {
            player.dialogueFactory.sendStatement("<col=369>You need a Crafting level of " + item.getLevel() + " to do that.").execute();
            return true;
        }
        if (!player.inventory.containsAll(craftable.getIngredients(index))) {
            Item requiredItem = craftable.getCraftableItems()[index].getRequiredItem();
            Item product = craftable.getCraftableItems()[index].getProduct();
            String productAmount = "";
            if (product.getName().contains("vamb")) {
                productAmount = " pair of";
            } else if (!product.getName().endsWith("s")) {
                productAmount = " " + Utility.getAOrAn(product.getName());
            }
            player.send(new SendMessage("You need " + requiredItem.getAmount() + " piece" + (requiredItem.getAmount() > 1 ? "s" : "") + " of " + requiredItem.getName().toLowerCase() + " to make" + productAmount + " " + product.getName().toLowerCase() + "."));
            return true;
        }
        player.action.execute(craft(player, craftable, item, index, amount), true);
        return true;
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.items.containers.ItemContainer.containsAll(), craft(), CRAFTABLE_KEY, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.items.Item.getAmount(), com.runehive.util.Utility.getAOrAn(), com.runehive.content.skill.impl.crafting.Craftable.getCraftableItems(), com.runehive.content.skill.impl.crafting.Craftable.getIngredients(), com.runehive.content.skill.impl.crafting.CraftableItem.getLevel(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.items.Item.getName(), com.runehive.content.skill.impl.crafting.CraftableItem.getProduct(), com.runehive.content.skill.impl.crafting.CraftableItem.getRequiredItem(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.util.generic.GenericAttributes.remove(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.game.world.entity.skill.Skill.Skill(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by clickButton(), and craft().
useItem() [1/2]
boolean com.runehive.content.skill.impl.crafting.Crafting.useItem (Player player, ItemOnItemInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 106 of file Crafting.java.
{
        Item first = event.getFirst();
        Item second = event.getSecond();
        if (Stringing.useItem(player, first, second)) {
            return true;
        }
        if (first.getId() == 1785 && second.getId() == 1775 || first.getId() == 1775 && second.getId() == 1785) {
            Glass.open(player);
            return true;
        }
        if ((first.getId() == 1733 && second.getId() == 1741) || (first.getId() == 1741 && second.getId() == 1733)) {
            player.attributes.set(CRAFTABLE_KEY, "HIDE");
            player.interfaceManager.open(2311);
            return true;
        }
        Craftable craftable = getCraftable(first.getId(), second.getId());
        if (craftable == null) {
            return false;
        }
        if (!craftable.getUse().equalIds(first) && !craftable.getUse().equalIds(second)) {
            player.message("You need to use this with " + Utility.getAOrAn(craftable.getUse().getName()) + " " + craftable.getUse().getName().toLowerCase() + " to craft this item.");
            return true;
        }
        switch (craftable.getCraftableItems().length) {
            case 1:
                player.attributes.set(CRAFTABLE_KEY, craftable);
                player.send(new SendString("\\n \\n \\n \\n" + craftable.getCraftableItems()[0].getProduct().getName(), 2799));
                player.send(new SendItemOnInterfaceZoom(1746, 170, craftable.getCraftableItems()[0].getProduct().getId()));
                player.send(new SendChatBoxInterface(4429));
                return true;
            case 2:
                player.attributes.set(CRAFTABLE_KEY, craftable);
                player.send(new SendItemOnInterfaceZoom(8869, 170, craftable.getCraftableItems()[0].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8870, 170, craftable.getCraftableItems()[1].getProduct().getId()));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[0].getProduct().getName().replace("d'hide ", "")), 8874));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[1].getProduct().getName().replace("d'hide ", "")), 8878));
                player.send(new SendChatBoxInterface(8866));
                return true;
            case 3:
                player.attributes.set(CRAFTABLE_KEY, craftable);
                player.send(new SendItemOnInterfaceZoom(8883, 170, craftable.getCraftableItems()[0].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8884, 170, craftable.getCraftableItems()[1].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8885, 170, craftable.getCraftableItems()[2].getProduct().getId()));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[0].getProduct().getName().replace("d'hide ", "")), 8889));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[1].getProduct().getName().replace("d'hide ", "")), 8893));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[2].getProduct().getName().replace("d'hide ", "")), 8897));
                player.send(new SendChatBoxInterface(8880));
                return true;
            case 4:
                player.attributes.set(CRAFTABLE_KEY, craftable);
                player.send(new SendItemOnInterfaceZoom(8902, 170, craftable.getCraftableItems()[0].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8903, 170, craftable.getCraftableItems()[1].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8904, 170, craftable.getCraftableItems()[2].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8905, 170, craftable.getCraftableItems()[3].getProduct().getId()));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[0].getProduct().getName().replace("d'hide ", "")), 8909));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[1].getProduct().getName().replace("d'hide ", "")), 8913));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[2].getProduct().getName().replace("d'hide ", "")), 8917));
                player.send(new SendString("\\n \\n \\n \\n".concat(craftable.getCraftableItems()[3].getProduct().getName().replace("d'hide ", "")), 8921));
                player.send(new SendChatBoxInterface(8899));
                return true;
            case 5:
                player.attributes.set(CRAFTABLE_KEY, craftable);
                player.send(new SendItemOnInterfaceZoom(8941, 170, craftable.getCraftableItems()[0].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8942, 170, craftable.getCraftableItems()[1].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8943, 170, craftable.getCraftableItems()[2].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8944, 170, craftable.getCraftableItems()[3].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8945, 170, craftable.getCraftableItems()[4].getProduct().getId()));
                player.send(new SendString("\\n \\n \\n \\n".concat("Body"), 8949));
                player.send(new SendString("\\n \\n \\n \\n".concat("Chaps"), 8953));
                player.send(new SendString("\\n \\n \\n \\n".concat("Vambraces"), 8957));
                player.send(new SendString("\\n \\n \\n \\n".concat("Bandana"), 8961));
                player.send(new SendString("\\n \\n \\n \\n".concat("Boots"), 8965));
                player.send(new SendChatBoxInterface(8938));
                return true;
            default:
                return false;
        }
    }
References com.runehive.game.world.entity.mob.Mob.attributes, CRAFTABLE_KEY, com.runehive.game.world.items.Item.equalIds(), com.runehive.util.Utility.getAOrAn(), getCraftable(), com.runehive.content.skill.impl.crafting.Craftable.getCraftableItems(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.content.skill.impl.crafting.CraftableItem.getProduct(), com.runehive.content.skill.impl.crafting.Craftable.getUse(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.skill.impl.crafting.impl.Glass.open(), com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), and com.runehive.content.skill.impl.crafting.impl.Stringing.useItem().
useItem() [2/2]
boolean com.runehive.content.skill.impl.crafting.Crafting.useItem (Player player, ItemOnObjectInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 93 of file Crafting.java.
{
        Item item = event.getItem();
        GameObject object = event.getObject();
        if (object.getId() == 16469 && (item.getId() == 1783 || item.getId() == 1781)) {
            Glass.craft(player, Glass.GlassData.MOLTEN_GLASS, 28);
            return true;
        }
        return false;
    }
References com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.game.world.items.Item.getId(), and com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.MOLTEN_GLASS.
Member Data Documentation
CRAFTABLE_KEY
final String com.runehive.content.skill.impl.crafting.Crafting.CRAFTABLE_KEY = "CRAFTABLE_KEY" static private
The craftable key.
Definition at line 33 of file Crafting.java.
Referenced by clickButton(), craft(), start(), and useItem().
CRAFTABLES
final HashMap<Integer, Craftable> com.runehive.content.skill.impl.crafting.Crafting.CRAFTABLES = new HashMap<>() static private
The craftable map.
Definition at line 36 of file Crafting.java.
Referenced by addCraftable(), and getCraftable().
LEATHER_ARMOR_IDS
final Object [][] com.runehive.content.skill.impl.crafting.Crafting.LEATHER_ARMOR_IDS static private
Initial value:
= {
            {8635, 1, Leather.LEATHER_BODY}, {8634, 5, Leather.LEATHER_BODY}, {8633, 10, Leather.LEATHER_BODY},
            {8638, 1, Leather.LEATHER_GLOVES}, {8637, 5, Leather.LEATHER_GLOVES}, {8636, 10, Leather.LEATHER_GLOVES},
            {8641, 1, Leather.LEATHER_BOOTS}, {8640, 5, Leather.LEATHER_BOOTS}, {8639, 10, Leather.LEATHER_BOOTS},
            {8644, 1, Leather.LEATHER_VANBRACES}, {8643, 5, Leather.LEATHER_VANBRACES}, {8642, 10, Leather.LEATHER_VANBRACES},
            {8647, 1, Leather.LEATHER_CHAPS}, {8646, 5, Leather.LEATHER_CHAPS}, {8645, 10, Leather.LEATHER_CHAPS},
            {8650, 1, Leather.LEATHER_COIF}, {8649, 5, Leather.LEATHER_COIF}, {8648, 10, Leather.LEATHER_COIF},
            {8653, 1, Leather.LEATHER_COWL}, {8652, 5, Leather.LEATHER_COWL}, {8651, 10, Leather.LEATHER_COWL},
    }
The leather armour data.
Definition at line 39 of file Crafting.java.
{
            {8635, 1, Leather.LEATHER_BODY}, {8634, 5, Leather.LEATHER_BODY}, {8633, 10, Leather.LEATHER_BODY},
            {8638, 1, Leather.LEATHER_GLOVES}, {8637, 5, Leather.LEATHER_GLOVES}, {8636, 10, Leather.LEATHER_GLOVES},
            {8641, 1, Leather.LEATHER_BOOTS}, {8640, 5, Leather.LEATHER_BOOTS}, {8639, 10, Leather.LEATHER_BOOTS},
            {8644, 1, Leather.LEATHER_VANBRACES}, {8643, 5, Leather.LEATHER_VANBRACES}, {8642, 10, Leather.LEATHER_VANBRACES},
            {8647, 1, Leather.LEATHER_CHAPS}, {8646, 5, Leather.LEATHER_CHAPS}, {8645, 10, Leather.LEATHER_CHAPS},
            {8650, 1, Leather.LEATHER_COIF}, {8649, 5, Leather.LEATHER_COIF}, {8648, 10, Leather.LEATHER_COIF},
            {8653, 1, Leather.LEATHER_COWL}, {8652, 5, Leather.LEATHER_COWL}, {8651, 10, Leather.LEATHER_COWL},
    };
Referenced by clickButton().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/crafting/Crafting.java