RuneHive-Game: com.runehive.content.activity.impl.zulrah.ZulrahActivity Class Reference
com.runehive.content.activity.impl.zulrah.ZulrahActivity Class Reference
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
ActivityDeathType deathType ()
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onRegionChange (Player player)
Called when the player changes region.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
void onLogout (Player player)
Called when the player logs out.
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
void update ()
The update method.
Static Public Member Functions
static ZulrahActivity create (Player player)
Creates a new Zulrah activity for the player.
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Public Attributes
Position target
The current zulrah target position.
Protected Member Functions
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Protected Attributes
int count
The activity count.
final Player player
The player instance for this activity.
Stopwatch stopwatch = Stopwatch.start()
The activity stopwatch.
Npc zulrah
The Zulrah npc for this activity.
Package Functions
Position getCloudPosition ()
Gets the cloud position.
Position getSnakelingPosition ()
Gets the snakeling position.
void increment ()
Increments the activity count.
int nextForm ()
Gets the next Zulrah form.
ZulrahPhase nextPhase ()
Gets the next Zulrah phase.
void reset ()
Resets the Zulrah phase.
Package Attributes
List< CustomGameObject > clouds = new ArrayList<>()
The currently spawned clouds.
ZulrahPhase phase = ZulrahPhase.INITIALIZATION
The current zulrah phase.
List< Npc > snakes = new ArrayList<>()
The currently spawned snakes.
Private Member Functions
void cloudEffect ()
Handles the cloud effect.
ZulrahActivity (Player player, int instance)
Constructs a new ZulrahActivity.
Private Attributes
final ActivityListener<? extends Activity > LISTENER = new ZulrahListener(this)
The combat listener for this activity.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Definition at line 29 of file ZulrahActivity.java.
Constructor & Destructor Documentation
ZulrahActivity()
com.runehive.content.activity.impl.zulrah.ZulrahActivity.ZulrahActivity (Player player, int instance) private
Constructs a new ZulrahActivity.
Definition at line 58 of file ZulrahActivity.java.
{
        super(1, instance);
        this.player = player;
    }
References com.runehive.content.activity.Activity.instance, and player.
Referenced by create().
Member Function Documentation
canTeleport()
boolean com.runehive.content.activity.impl.zulrah.ZulrahActivity.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 228 of file ZulrahActivity.java.
{
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.zulrah.ZulrahActivity.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 175 of file ZulrahActivity.java.
{
        if (zulrah != null) {
            remove(zulrah);
        }
        for (Npc snakeling : snakes) {
            remove(snakeling);
        }
        for (GameObject cloud : clouds) {
            cloud.unregister();
        }
        snakes.clear();
        clouds.clear();
    }
References clouds, snakes, and zulrah.
Referenced by finish(), and onRegionChange().
cloudEffect()
void com.runehive.content.activity.impl.zulrah.ZulrahActivity.cloudEffect () private
Handles the cloud effect.
Definition at line 139 of file ZulrahActivity.java.
{
        for (CustomGameObject cloud : clouds) {
            if (Utility.inside(cloud.getPosition(), 2, 2, player.getPosition(), 1, 1))
                player.damage(new Hit(RandomUtils.inclusive(1, 5), Hitsplat.VENOM));
        }
    }
References clouds, com.runehive.util.RandomUtils.inclusive(), com.runehive.util.Utility.inside(), player, and com.runehive.game.world.entity.combat.hit.Hitsplat.VENOM.
Referenced by start().
create()
ZulrahActivity com.runehive.content.activity.impl.zulrah.ZulrahActivity.create (Player player) static
Creates a new Zulrah activity for the player.
Definition at line 64 of file ZulrahActivity.java.
{
        ZulrahActivity activity = new ZulrahActivity(player, player.playerAssistant.instance());
        activity.add(player);
        activity.resetCooldown();
        player.gameRecord.start();
        player.dialogueFactory.sendStatement("Welcome to Zulrah's shrine.").execute();
        return activity;
    }
References player, and ZulrahActivity().
deathType()
ActivityDeathType com.runehive.content.activity.impl.zulrah.ZulrahActivity.deathType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 233 of file ZulrahActivity.java.
{
        return ActivityDeathType.PURCHASE;
    }
References com.runehive.content.activity.ActivityDeathType.PURCHASE.
finish()
void com.runehive.content.activity.impl.zulrah.ZulrahActivity.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 164 of file ZulrahActivity.java.
{
        cleanup();
        remove(player);
        player.animate(Animation.RESET, true);
        player.graphic(Graphic.RESET, true);
        if (zulrah.isDead()) {
            player.send(new SendMessage("Fight duration: @red@" + Utility.getTime(player.gameRecord.end(ActivityType.ZULRAH)) + "</col>."));
        }
    }
References cleanup(), com.runehive.util.Utility.getTime(), player, com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, com.runehive.content.activity.ActivityType.ZULRAH, and zulrah.
getCloudPosition()
Position com.runehive.content.activity.impl.zulrah.ZulrahActivity.getCloudPosition () package
Gets the cloud position.
Definition at line 128 of file ZulrahActivity.java.
{
        Set<Position> positions = new HashSet<>(Arrays.asList(ZulrahConstants.CLOUD_POSITIONS));
        for (GameObject cloud : clouds) {
            if (positions.contains(cloud.getPosition())) {
                positions.remove(cloud.getPosition());
            }
        }
        return Utility.randomElement(positions);
    }
References com.runehive.content.activity.impl.zulrah.ZulrahConstants.CLOUD_POSITIONS, clouds, and com.runehive.util.Utility.randomElement().
getListener()
Optional<? extends ActivityListener<? extends Activity > > com.runehive.content.activity.impl.zulrah.ZulrahActivity.getListener () protected
Gets an Optional of the ActivityListener for this activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 238 of file ZulrahActivity.java.
{
        return Optional.of(LISTENER);
    }
References LISTENER.
getSnakelingPosition()
Position com.runehive.content.activity.impl.zulrah.ZulrahActivity.getSnakelingPosition () package
Gets the snakeling position.
Definition at line 117 of file ZulrahActivity.java.
{
        Set<Position> positions = new HashSet<>(Arrays.asList(ZulrahConstants.SNAKELINGS_POSITIONS));
        for (Npc snake : snakes) {
            if (positions.contains(snake.getPosition())) {
                positions.remove(snake.getPosition());
            }
        }
        return Utility.randomElement(positions);
    }
References com.runehive.util.Utility.randomElement(), com.runehive.content.activity.impl.zulrah.ZulrahConstants.SNAKELINGS_POSITIONS, and snakes.
getType()
ActivityType com.runehive.content.activity.impl.zulrah.ZulrahActivity.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 223 of file ZulrahActivity.java.
{
        return ActivityType.ZULRAH;
    }
References com.runehive.content.activity.ActivityType.ZULRAH.
increment()
void com.runehive.content.activity.impl.zulrah.ZulrahActivity.increment () package
Increments the activity count.
Definition at line 74 of file ZulrahActivity.java.
                     {
        count++;
    }
References count.
nextForm()
int com.runehive.content.activity.impl.zulrah.ZulrahActivity.nextForm () package
Gets the next Zulrah form.
Definition at line 88 of file ZulrahActivity.java.
                   {
        int next = RandomUtils.randomExclude(ZulrahConstants.ZULRAH_IDS, zulrah.id);
        if (next == 2042) {
            ((Zulrah) zulrah.getStrategy()).setRanged();
        } else if (next == 2043) {
            ((Zulrah) zulrah.getStrategy()).setMelee();
        } else if (next == 2044) {
            ((Zulrah) zulrah.getStrategy()).setMagic();
        }
        return next;
    }
References com.runehive.util.RandomUtils.randomExclude(), zulrah, and com.runehive.content.activity.impl.zulrah.ZulrahConstants.ZULRAH_IDS.
nextPhase()
ZulrahPhase com.runehive.content.activity.impl.zulrah.ZulrahActivity.nextPhase () package
Gets the next Zulrah phase.
Definition at line 101 of file ZulrahActivity.java.
{
        if (zulrah.id == 2043) {
            return ZulrahPhase.ATTACKING;
        }
        Set<ZulrahPhase> states = new HashSet<>();
        states.add(ZulrahPhase.ATTACKING);
        if (clouds.size() < ZulrahConstants.MAXIMUM_CLOUDS) {
            states.add(ZulrahPhase.POISONOUS_CLOUD);
        }
        if (snakes.size() < ZulrahConstants.MAXIMUM_SNAKELINGS) {
            states.add(ZulrahPhase.SNAKELINGS);
        }
        return Utility.randomElement(states);
    }
References com.runehive.content.activity.impl.zulrah.ZulrahPhase.ATTACKING, clouds, com.runehive.content.activity.impl.zulrah.ZulrahConstants.MAXIMUM_CLOUDS, com.runehive.content.activity.impl.zulrah.ZulrahConstants.MAXIMUM_SNAKELINGS, com.runehive.content.activity.impl.zulrah.ZulrahPhase.POISONOUS_CLOUD, com.runehive.util.Utility.randomElement(), com.runehive.content.activity.impl.zulrah.ZulrahPhase.SNAKELINGS, snakes, and zulrah.
onDeath()
void com.runehive.content.activity.impl.zulrah.ZulrahActivity.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 201 of file ZulrahActivity.java.
{
        if (mob.isNpc()) {
            Npc npc = mob.getNpc();
            if (mob.equals(zulrah)) {
                World.schedule(new NpcDeath(npc, this::finish));
            }
            if (snakes.contains(npc)) {
                World.schedule(new NpcDeath(npc, () -> {
                    remove(npc);
                    snakes.remove(npc);
                }));
            }
            return;
        }
        super.onDeath(mob);
    }
References com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.World.schedule(), snakes, and zulrah.
onRegionChange()
void com.runehive.content.activity.impl.zulrah.ZulrahActivity.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 190 of file ZulrahActivity.java.
{
        if (!Area.inZulrah(player)) {
            cleanup();
            remove(player);
            player.animate(Animation.RESET, true);
            player.graphic(Graphic.RESET, true);
        }
    }
References cleanup(), com.runehive.game.world.position.Area.inZulrah(), player, com.runehive.game.Animation.RESET, and com.runehive.game.Graphic.RESET.
reset()
void com.runehive.content.activity.impl.zulrah.ZulrahActivity.reset () package
Resets the Zulrah phase.
Definition at line 79 of file ZulrahActivity.java.
                 {
        player.getCombat().reset();
        zulrah.getCombat().reset();
        zulrah.resetFace();
        stopwatch.reset();
        count = -1;
    }
References count, player, stopwatch, and zulrah.
start()
void com.runehive.content.activity.impl.zulrah.ZulrahActivity.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 147 of file ZulrahActivity.java.
{
        cloudEffect();
        boolean valid = zulrah != null;
        if (valid && zulrah.isDead()) {
            return;
        }
        phase.execute(this);
        if (valid) {
            zulrah.getCombat().cooldown(2);
        }
    }
References cloudEffect(), phase, and zulrah.
Member Data Documentation
clouds
List<CustomGameObject> com.runehive.content.activity.impl.zulrah.ZulrahActivity.clouds = new ArrayList<>() package
The currently spawned clouds.
Definition at line 52 of file ZulrahActivity.java.
Referenced by cleanup(), cloudEffect(), getCloudPosition(), and nextPhase().
count
int com.runehive.content.activity.impl.zulrah.ZulrahActivity.count protected
The activity count.
Definition at line 40 of file ZulrahActivity.java.
Referenced by increment(), and reset().
LISTENER
final ActivityListener<? extends Activity> com.runehive.content.activity.impl.zulrah.ZulrahActivity.LISTENER = new ZulrahListener(this) private
The combat listener for this activity.
Definition at line 55 of file ZulrahActivity.java.
Referenced by getListener().
phase
ZulrahPhase com.runehive.content.activity.impl.zulrah.ZulrahActivity.phase = ZulrahPhase.INITIALIZATION package
The current zulrah phase.
Definition at line 46 of file ZulrahActivity.java.
Referenced by start().
player
final Player com.runehive.content.activity.impl.zulrah.ZulrahActivity.player protected
The player instance for this activity.
Definition at line 31 of file ZulrahActivity.java.
Referenced by canTeleport(), cloudEffect(), create(), finish(), onRegionChange(), reset(), and ZulrahActivity().
snakes
List<Npc> com.runehive.content.activity.impl.zulrah.ZulrahActivity.snakes = new ArrayList<>() package
The currently spawned snakes.
Definition at line 49 of file ZulrahActivity.java.
Referenced by cleanup(), getSnakelingPosition(), nextPhase(), and onDeath().
stopwatch
Stopwatch com.runehive.content.activity.impl.zulrah.ZulrahActivity.stopwatch = Stopwatch.start() protected
The activity stopwatch.
Definition at line 37 of file ZulrahActivity.java.
Referenced by reset().
target
Position com.runehive.content.activity.impl.zulrah.ZulrahActivity.target
The current zulrah target position.
Definition at line 43 of file ZulrahActivity.java.
zulrah
Npc com.runehive.content.activity.impl.zulrah.ZulrahActivity.zulrah protected
The Zulrah npc for this activity.
Definition at line 34 of file ZulrahActivity.java.
Referenced by cleanup(), finish(), nextForm(), nextPhase(), onDeath(), reset(), and start().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/zulrah/ZulrahActivity.java