RuneHive-Game: com.runehive.game.world.World Class Reference
com.runehive.game.world.World Class Reference
Represents the game world.
Public Member Functions
void dequeLogins ()
void dequeLogouts ()
Queue< Player > getLogins ()
Queue< Player > getLogouts ()
TaskManager getTaskManager ()
int getWildernessResourcePlayers ()
void process ()
void sequence ()
Handles the world sequencing.
Static Public Member Functions
static void cancelTask (Object attachment)
static void cancelTask (Object attachment, boolean logout)
static int executeProjectile (Mob entity, ProjectileTest projectile)
static World get ()
static int getBotCount ()
static DataBus getDataBus ()
static Optional< Npc > getNpcBySlot (int index)
Gets an npc by index.
static MobList< Npc > getNpcs ()
static Optional< Player > getPlayerByHash (long usernameHash)
static Optional< Player > getPlayerByName (String username)
static Optional< Player > getPlayerBySlot (int index)
Gets a player by index.
static int getPlayerCount ()
Gets the amount of valid players online.
static MobList< Player > getPlayers ()
static RegionManager getRegions ()
static List< Player > getStaff ()
Gets the staff players currently online.
static int getStaffCount ()
static int getWildernessCount ()
static void kickPlayer (Player other)
static void kickPlayer (Predicate< Player > condition)
static void queueLogin (Player player)
Handles queueing the player logins.
static void queueLogout (Player player)
Handles queueing the player logouts.
static void save ()
Saves all the game data.
static void schedule (int delay, Runnable runnable)
Executes a runnable on a delay.
static void schedule (Runnable runnable)
Executes a runnable on a 1 tick delay.
static void schedule (Task task)
Submits a new event.
static Optional< Player > search (String name)
Gets a player by name.
static Optional< Player > searchAll (String name)
static void sendBroadcast (int time, String message, boolean countdown)
Sends a game message.
static void sendGraphic (Graphic graphic, Position position)
static void sendGraphic (Graphic graphic, Position position, int instance)
Sends a graphic to the world.
static void sendKillFeed (final Mob killer, final Mob victim)
Sends a kill feed notification.
static void sendMessage (String message, Predicate< Player > filter)
Sends a global message with an exception.
static void sendMessage (String... messages)
Sends a global message.
static void sendObjectAnimation (int animation, GameObject object)
Sends a world object animation.
static void sendProjectile (Mob source, Mob target, Projectile projectile)
Sends a world projectile.
static void sendProjectile (Mob source, Position target, Projectile projectile)
Sends a world projectile.
static void sendProjectile (Position source, Mob target, Projectile projectile)
static void sendProjectile (Position source, Position target, Projectile projectile)
static void sendProjectile (Projectile projectile, Position position, int instance, int lock, byte offsetX, byte offsetY)
Sends a world projectile.
static void sendStaffMessage (String... messages)
static void shutdown ()
Shuts down the server.
static void update (int time)
Updates the server.
Static Public Attributes
static int addition = 0
static final AtomicBoolean update = new AtomicBoolean(false)
Private Member Functions
World ()
Private Attributes
final Queue< Player > logins = new ConcurrentLinkedQueue<>()
The Players waiting to login.
final Queue< Player > logouts = new ConcurrentLinkedQueue<>()
The Players waiting to onLogout.
final MobList< Npc > npcs = new MobList<>(Config.MAX_NPCS)
The npcs registered in this world.
final MobList< Player > players = new MobList<>(Config.MAX_PLAYERS)
The players registered in this world.
final RegionManager regionManager = new RegionManager()
The region manager.
final TaskDeadlockWatcher taskDeadlockWatcher
The task deadlock watcher relies on the TaskManager.
final Thread taskDeadlockWatcherThread
The thread to watch task deadlocks on.
final TaskManager taskManager
The task manager.
Static Private Attributes
static final DataBus dataBus = DataBus.getInstance()
static final Logger logger = LogManager.getLogger(World.class)
static final World WORLD = new World()
The world instance.
Detailed Description
Represents the game world.
Author
Daniel
Michael
Definition at line 46 of file World.java.
Constructor & Destructor Documentation
World()
com.runehive.game.world.World.World () private
Definition at line 82 of file World.java.
                    {
        dataBus.subscribe(new WorldEventListener());
        taskManager = new TaskManager();
        taskDeadlockWatcher = new TaskDeadlockWatcher(taskManager);
        taskDeadlockWatcherThread = new Thread(taskDeadlockWatcher);
        taskDeadlockWatcherThread.setName("TaskDeadlockWatcher");
        taskDeadlockWatcherThread.start();
    }
References dataBus, taskDeadlockWatcher, taskDeadlockWatcherThread, and taskManager.
Referenced by dequeLogouts(), get(), getNpcBySlot(), getPlayerByHash(), getPlayerByName(), getPlayerBySlot(), queueLogin(), and searchAll().
Member Function Documentation
cancelTask() [1/2]
void com.runehive.game.world.World.cancelTask (Object attachment) static
Definition at line 536 of file World.java.
{
        cancelTask(attachment, false);
    }
References cancelTask().
Referenced by cancelTask(), com.runehive.content.bot.PlayerBot.unregister(), and com.runehive.game.world.entity.mob.player.Player.unregister().
cancelTask() [2/2]
void com.runehive.game.world.World.cancelTask (Object attachment, boolean logout) static
Definition at line 540 of file World.java.
{
        get().taskManager.cancel(attachment, logout);
    }
References taskManager.
dequeLogins()
void com.runehive.game.world.World.dequeLogins ()
Definition at line 427 of file World.java.
{
        if (logins.isEmpty()) {
            return;
        }
        for (int index = 0; index < Config.LOGIN_THESHOLD; index++) {
            Player player = logins.poll();
            if (player == null) {
                break;
            }
            try {
                player.register();
            } catch (Exception ex) {
                logger.error(String.format("error registering %s", player), ex);
            }
        }
    }
References logger, com.runehive.Config.LOGIN_THESHOLD, logins, and com.runehive.game.world.entity.mob.player.Player.register().
dequeLogouts()
void com.runehive.game.world.World.dequeLogouts ()
Definition at line 448 of file World.java.
{
        if (logouts.isEmpty()) {
            return;
        }
        for (int index = 0; index < Config.LOGOUT_THESHOLD; index++) {
            Player player = logouts.poll();
            if (player == null) {
                break;
            }
            World.schedule(new PlayerRemovalTask(player, false));
        }
    }
References com.runehive.Config.LOGOUT_THESHOLD, logouts, and World().
executeProjectile()
int com.runehive.game.world.World.executeProjectile (Mob entity, ProjectileTest projectile) static
Definition at line 366 of file World.java.
{
        if (projectile == null) {
            return 0;
        }
        Position source = projectile.getStart();
        Position target = projectile.getTarget();
        if (source == null || target == null) {
            return 0;
        }
        Position delta = projectile.getTarget().getDelta(source, target);
        int distance = entity.getPosition().getChevDistance(target);
        if (distance <= 60) {
            int creatorSize = projectile.getCreatorSize() == -1 ? 1 : projectile.getCreatorSize(); //TODO size
            for (Player player : getPlayers()) {
                if (player == null) {
                    continue;
                }
                if (source.isViewableFrom(player.getPosition())) {
                    player.send(new SendProjectileTestPacket(source, delta, projectile.getSlope(), projectile.getSpeed(), projectile.getProjectileId(), projectile.getStartHeight(), projectile.getEndHeight(), projectile.getLockon(), projectile.getDelay(), creatorSize, projectile.getStartDistanceOffset()));
                }
            }
        }
        return projectile.getHitDelay(distance);
    }
References com.runehive.game.ProjectileTest.getCreatorSize(), com.runehive.game.ProjectileTest.getDelay(), com.runehive.game.world.position.Position.getDelta(), com.runehive.game.ProjectileTest.getEndHeight(), com.runehive.game.ProjectileTest.getHitDelay(), com.runehive.game.ProjectileTest.getLockon(), getPlayers(), com.runehive.game.ProjectileTest.getProjectileId(), com.runehive.game.ProjectileTest.getSlope(), com.runehive.game.ProjectileTest.getSpeed(), com.runehive.game.ProjectileTest.getStart(), com.runehive.game.ProjectileTest.getStartDistanceOffset(), com.runehive.game.ProjectileTest.getStartHeight(), com.runehive.game.ProjectileTest.getTarget(), and com.runehive.game.world.position.Position.isViewableFrom().
get()
World com.runehive.game.world.World.get () static
Definition at line 532 of file World.java.
{
        return WORLD;
    }
References WORLD, and World().
Referenced by com.runehive.game.engine.GameEngine.runOneIteration().
getBotCount()
int com.runehive.game.world.World.getBotCount () static
Definition at line 494 of file World.java.
{
        return PlayerBot.BOT_COUNT.get();
    }
References com.runehive.content.bot.PlayerBot.BOT_COUNT.
getDataBus()
DataBus com.runehive.game.world.World.getDataBus () static
Definition at line 568 of file World.java.
{
        return dataBus;
    }
References dataBus.
Referenced by com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.items.ground.GroundItem.createGlobal(), com.runehive.game.plugin.PluginContext.handleCommandEvent(), com.runehive.game.plugin.PluginContext.handlePickupItemEvent(), and com.runehive.game.world.entity.mob.player.relations.PlayerRelation.message().
getLogins()
Queue< Player > com.runehive.game.world.World.getLogins ()
Definition at line 560 of file World.java.
{
        return logins;
    }
References logins.
getLogouts()
Queue< Player > com.runehive.game.world.World.getLogouts ()
Definition at line 564 of file World.java.
{
        return logouts;
    }
References logouts.
getNpcBySlot()
Optional< Npc > com.runehive.game.world.World.getNpcBySlot (int index) static
Gets an npc by index.
Definition at line 209 of file World.java.
{
        for (Npc npc : World.getNpcs()) {
            if (npc.getIndex() == index)
                return Optional.of(npc);
        }
        return Optional.empty();
    }
References World().
getNpcs()
MobList< Npc > com.runehive.game.world.World.getNpcs () static
Definition at line 548 of file World.java.
{
        return get().npcs;
    }
References npcs.
Referenced by com.runehive.game.task.impl.ForceChatEvent.execute(), com.runehive.content.ai.AIDialogueHandler.findNearbyNpc(), com.runehive.content.combat.cannon.CannonManager.getNpc(), com.runehive.game.world.entity.mob.npc.Npc.register(), com.runehive.game.engine.GameEngine.runOneIteration(), and com.runehive.game.world.entity.mob.npc.Npc.unregister().
getPlayerByHash()
Optional< Player > com.runehive.game.world.World.getPlayerByHash (long usernameHash) static
Definition at line 183 of file World.java.
{
        for (Player player : World.getPlayers()) {
            if (Objects.equals(player.usernameLong, usernameHash))
                return Optional.of(player);
        }
        return Optional.empty();
    }
References World().
Referenced by com.runehive.net.session.LoginSession.evaluate().
getPlayerByName()
Optional< Player > com.runehive.game.world.World.getPlayerByName (String username) static
Definition at line 191 of file World.java.
{
        for (Player player : World.getPlayers()) {
            if (Objects.equals(player.getUsername(), username))
                return Optional.of(player);
        }
        return Optional.empty();
    }
References World().
Referenced by com.runehive.content.ai.LazyAIManager.clearPlayerConsent().
getPlayerBySlot()
Optional< Player > com.runehive.game.world.World.getPlayerBySlot (int index) static
Gets a player by index.
Definition at line 200 of file World.java.
{
        for (Player player : World.getPlayers()) {
            if (player.getIndex() == index)
                return Optional.of(player);
        }
        return Optional.empty();
    }
References World().
getPlayerCount()
int com.runehive.game.world.World.getPlayerCount () static
Gets the amount of valid players online.
Definition at line 490 of file World.java.
{
        return Math.toIntExact(getPlayers().size() + addition);
    }
References addition, and getPlayers().
Referenced by com.runehive.net.packet.out.SendMarquee.encode(), com.runehive.net.session.LoginSession.evaluate(), com.runehive.game.service.WebsitePlayerCountService.runOneIteration(), and com.runehive.game.world.entity.mob.player.Player.sendInitialPackets().
getPlayers()
MobList< Player > com.runehive.game.world.World.getPlayers () static
Definition at line 544 of file World.java.
{
        return get().players;
    }
References players.
Referenced by com.runehive.content.shootingstar.ShootingStarData.decreaseDust(), com.runehive.game.task.impl.PlayerSaveEvent.execute(), executeProjectile(), com.runehive.content.gambling.GambleManager.finish(), com.runehive.content.bot.BotUtility.getAvailableBotNames(), getPlayerCount(), com.runehive.game.world.position.Boundary.getPlayers(), getStaff(), getStaffCount(), getWildernessCount(), getWildernessResourcePlayers(), com.runehive.content.bot.PlayerBot.register(), com.runehive.game.world.entity.mob.player.Player.register(), com.runehive.game.engine.GameEngine.runOneIteration(), sendGraphic(), sendKillFeed(), sendMessage(), sendMessage(), sendObjectAnimation(), sendProjectile(), sendProjectile(), sendProjectile(), sendProjectile(), sendProjectile(), com.runehive.content.bot.PlayerBot.unregister(), com.runehive.game.world.entity.mob.player.Player.unregister(), and com.runehive.game.world.entity.mob.player.relations.PlayerRelation.updateLists().
getRegions()
RegionManager com.runehive.game.world.World.getRegions () static
Definition at line 552 of file World.java.
{
        return get().regionManager;
    }
References regionManager.
Referenced by com.runehive.content.Obelisks.activate(), com.runehive.game.world.items.ground.GroundItem.addToRegion(), com.runehive.game.world.object.CustomGameObject.addToRegion(), com.runehive.game.world.entity.combat.CombatUtil.areaAction(), com.runehive.net.packet.out.SendNpcUpdate.encode(), com.runehive.net.packet.out.SendPlayerUpdate.encode(), com.runehive.game.world.items.ground.GroundItemEvent.execute(), com.runehive.game.world.pathfinding.TraversalMap.getFlags(), com.runehive.game.world.position.Position.getRegion(), com.runehive.content.wintertodt.Wintertodt.init(), com.runehive.game.world.pathfinding.TraversalMap.isInactive(), com.runehive.fs.cache.decoder.RegionDecoder.load(), com.runehive.game.world.entity.mob.player.Player.loadRegion(), com.runehive.game.world.object.StaticGameObject.register(), com.runehive.game.world.items.ground.GroundItem.removeFromRegion(), com.runehive.game.world.object.CustomGameObject.removeFromRegion(), and com.runehive.game.world.object.StaticGameObject.unregister().
getStaff()
List< Player > com.runehive.game.world.World.getStaff () static
Gets the staff players currently online.
Definition at line 521 of file World.java.
{
        List<Player> staff = new ArrayList<>();
        for (Player player : getPlayers()) {
            if (player != null && (PlayerRight.isModerator(player) || player.right == PlayerRight.HELPER))
                staff.add(player);
        }
        return staff;
    }
References getPlayers(), com.runehive.game.world.entity.mob.player.PlayerRight.HELPER, and com.runehive.game.world.entity.mob.player.PlayerRight.isModerator().
Referenced by sendStaffMessage().
getStaffCount()
int com.runehive.game.world.World.getStaffCount () static
Definition at line 498 of file World.java.
{
        int count = 0;
        for (Player player : getPlayers()) {
            if (player != null && (PlayerRight.isModerator(player) || player.right == PlayerRight.HELPER))
                count++;
        }
        return count;
    }
References getPlayers(), com.runehive.game.world.entity.mob.player.PlayerRight.HELPER, and com.runehive.game.world.entity.mob.player.PlayerRight.isModerator().
getTaskManager()
TaskManager com.runehive.game.world.World.getTaskManager ()
Definition at line 556 of file World.java.
{
        return taskManager;
    }
References taskManager.
getWildernessCount()
int com.runehive.game.world.World.getWildernessCount () static
Definition at line 509 of file World.java.
{
        int count = 0;
        for (Player player : getPlayers()) {
            if (player != null && !player.isBot && Area.inWilderness(player))
                count++;
        }
        return count;
    }
References getPlayers(), and com.runehive.game.world.position.Area.inWilderness().
getWildernessResourcePlayers()
int com.runehive.game.world.World.getWildernessResourcePlayers ()
Definition at line 464 of file World.java.
{
        int count = 0;
        for (Player player : getPlayers()) {
            if (player != null && Area.inWildernessResource(player))
                count++;
        }
        return count;
    }
References getPlayers(), and com.runehive.game.world.position.Area.inWildernessResource().
kickPlayer() [1/2]
void com.runehive.game.world.World.kickPlayer (Player other) static
Definition at line 217 of file World.java.
{
        other.send(new SendLogout());
        queueLogout(other);
    }
References queueLogout(), and com.runehive.game.world.entity.mob.player.Player.send().
kickPlayer() [2/2]
void com.runehive.game.world.World.kickPlayer (Predicate< Player > condition) static
Definition at line 222 of file World.java.
{
        for (Player player : get().players) {
            if (player.isBot)
                continue;
            if (!condition.test(player))
                continue;
            player.send(new SendLogout());
            queueLogout(player);
        }
    }
References players, and queueLogout().
process()
void com.runehive.game.world.World.process ()
Definition at line 233 of file World.java.
{
        try {
            taskManager.processTasks();
        } catch (Exception ex) {
            logger.error("Error sequencing task manager", ex);
        }
        try {
            PestControlLobby.sequence();
        } catch (Exception ex) {
            logger.error("Error sequencing pest control.", ex);
        }
    }
References logger, com.runehive.content.activity.impl.pestcontrol.PestControlLobby.sequence(), and taskManager.
queueLogin()
void com.runehive.game.world.World.queueLogin (Player player) static
Handles queueing the player logins.
Definition at line 129 of file World.java.
{
        if (player.isBot) {
            get().logins.add(player);
        } else {
            player.getSession().ifPresent(it -> World.get().logins.add(player));
        }
    }
References com.runehive.game.world.entity.mob.player.Player.getSession(), com.runehive.game.world.entity.mob.player.Player.isBot, logins, and World().
Referenced by com.runehive.net.session.LoginSession.handleUserLoginDetails().
queueLogout()
void com.runehive.game.world.World.queueLogout (Player player) static
Handles queueing the player logouts.
Definition at line 138 of file World.java.
{
        if (player == null || get().logouts.contains(player)) {
            return;
        }
        get().logouts.add(player);
    }
References logouts.
Referenced by kickPlayer(), kickPlayer(), com.runehive.game.world.entity.mob.player.Player.logout(), and com.runehive.net.session.GameSession.onClose().
save()
void com.runehive.game.world.World.save () static
Saves all the game data.
Definition at line 97 of file World.java.
{
        System.out.println("Saving osroyale...");
        get().players.forEach(PlayerSerializer::save);
        logger.info("All players were successfully saved.");
       /* GlobalRecords.save();
        logger.info("All global records were successfully saved.");*/
        ClanRepository.saveAllActiveClans();
        logger.info("All clans were successfully saved.");
        TradingPost.saveRecentHistory();
        TradingPost.saveAllItemHistory();
        logger.info("All trading post history was successfully saved");
        GameSaver.save();
        logger.info("All game data were successfully saved.");
    }
References logger, players, com.runehive.game.world.entity.mob.player.persist.PlayerSerializer.save(), com.runehive.util.GameSaver.save(), com.runehive.content.clanchannel.ClanRepository.saveAllActiveClans(), com.runehive.content.tradingpost.TradingPost.saveAllItemHistory(), and com.runehive.content.tradingpost.TradingPost.saveRecentHistory().
Referenced by com.runehive.RuneHive.main(), and com.runehive.game.task.impl.SystemUpdateEvent.tick().
schedule() [1/3]
void com.runehive.game.world.World.schedule (int delay, Runnable runnable) static
Executes a runnable on a delay.
Definition at line 252 of file World.java.
{
        schedule(new Task(delay) {
            @Override
            public void execute() {
                runnable.run();
                cancel();
            }
        });
    }
References schedule().
schedule() [2/3]
void com.runehive.game.world.World.schedule (Runnable runnable) static
Executes a runnable on a 1 tick delay.
Definition at line 263 of file World.java.
{
        schedule(1, runnable);
    }
References schedule().
schedule() [3/3]
void com.runehive.game.world.World.schedule (Task task) static
Submits a new event.
Definition at line 247 of file World.java.
{
        get().taskManager.schedule(task);
    }
References taskManager.
Referenced by com.runehive.content.Obelisks.activate(), com.runehive.content.WellOfGoodwill.activate(), com.runehive.game.world.items.ground.GroundItem.addToRegion(), com.runehive.game.world.entity.mob.npc.Npc.appendDeath(), com.runehive.game.world.entity.mob.player.Player.appendDeath(), com.runehive.game.world.entity.mob.Mob.attack(), com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.block(), com.runehive.content.wintertodt.Wintertodt.breakBrazier(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.activity.impl.kraken.KrakenActivity.cleanup(), com.runehive.content.activity.impl.VorkathActivity.clickNpc(), com.runehive.content.skill.impl.hunter.Hunter.clickNpc(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.clickObject(), com.runehive.content.skill.impl.mining.Mining.clickObject(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.construction.House.construct(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.curePlant(), com.runehive.game.world.entity.mob.npc.NpcDeath.death(), com.runehive.content.wintertodt.Wintertodt.doMagicAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.content.combat.cannon.CannonManager.drop(), com.runehive.content.skill.impl.construction.House.enter(), com.runehive.content.skill.impl.construction.House.enter(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.skill.impl.hunter.net.Netting.execute(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.cronjobs.Job.execute(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoEvent.execute(), com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.findRoute(), com.runehive.content.activity.impl.kraken.KrakenActivity.finish(), com.runehive.game.world.entity.mob.Mob.follow(), com.runehive.game.world.entity.mob.Mob.forceMove(), com.runehive.content.gambling.impl.FiftyFive.gamble(), com.runehive.content.gambling.impl.FlowerPoker.gamble(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.activity.infernomobs.MejRah.Ranged.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitTask(), com.runehive.content.shootingstar.ShootingStar.init(), com.runehive.content.wintertodt.Wintertodt.init(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.inspect(), com.runehive.game.task.impl.HunterTask.intialize(), com.runehive.content.combat.cannon.CannonManager.load(), com.runehive.content.activity.impl.magearena.MageArena.meteors(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.game.world.entity.mob.player.PlayerAssistant.moveCamera(), com.runehive.content.consume.PotionData.onAntiPoisonEffect(), com.runehive.content.activity.Activity.onDeath(), com.runehive.content.activity.impl.barrows.Barrows.onDeath(), com.runehive.content.activity.impl.CerberusActivity.onDeath(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.kraken.KrakenActivity.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.content.activity.impl.VorkathActivity.onDeath(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.onDeath(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.onDeath(), com.runehive.content.pet.Pets.onDeath(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneWallClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SteppingStonesInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SwingAcrossCableInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onExecution(), com.runehive.content.pet.Pets.onLogin(), com.runehive.RuneHive.onStart(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.game.world.entity.mob.player.Player.pickup(), com.runehive.content.gambling.impl.FlowerPoker.plant(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.plantScareCrow(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.plantSeed(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonAttack(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.preDeath(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.preDeath(), com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), com.runehive.content.store.impl.DefaultStore.refresh(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove(), com.runehive.content.activity.Activity.restart(), schedule(), schedule(), com.runehive.content.tradingpost.TradingPost.searchExistingItemInput(), com.runehive.content.tradingpost.TradingPost.searchPlayerInput(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), com.runehive.game.world.entity.mob.player.PlayerAssistant.setEffects(), com.runehive.game.world.entity.mob.npc.NpcAssistant.setEvent(), com.runehive.game.world.entity.mob.Mob.setWaypoint(), com.runehive.content.combat.Skulling.skull(), com.runehive.content.activity.inferno.InfernoBoss.spawnbosswave(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.content.mysterybox.MysteryBoxManager.spin(), com.runehive.content.activity.infernomobs.Jalimkot.Burrow.start(), com.runehive.content.activity.infernomobs.JalTokJad.RangedAttack.start(), com.runehive.content.skill.impl.mining.Mining.start(), com.runehive.game.world.entity.combat.effect.CombatEffect.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.start(), com.runehive.content.ai.LazyAIManager.startInactivityTimer(), com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.summon(), com.runehive.game.world.entity.mob.player.Player.teleblock(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.tick(), com.runehive.content.activity.panel.ActivityPanel.timedClear(), update(), com.runehive.game.world.entity.mob.Mob.walkTo(), com.runehive.content.skill.impl.farming.patches.WaterablePatch.waterPatch(), com.runehive.game.world.entity.mob.player.BannedPlayers.writeBans(), com.runehive.game.world.entity.mob.player.IPBannedPlayers.writeIpBans(), and com.runehive.game.world.entity.mob.player.IPMutedPlayers.writeIpMutes().
search()
Optional< Player > com.runehive.game.world.World.search (String name) static
Gets a player by name.
Definition at line 147 of file World.java.
{
        for (Player player : get().players) {
            if (player == null) {
                continue;
            }
            if (player.getUsername().equalsIgnoreCase(name)) {
                return Optional.of(player);
            }
        }
        return Optional.empty();
    }
References players.
Referenced by com.runehive.game.world.entity.mob.player.relations.PlayerRelation.addFriend(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.addIgnore(), com.runehive.content.tradingpost.TradingPost.alertSeller(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteIgnore(), com.runehive.content.skill.impl.construction.House.enter(), com.runehive.net.session.LoginSession.evaluate(), and com.runehive.content.store.impl.PersonalStore.onPurchase().
searchAll()
Optional< Player > com.runehive.game.world.World.searchAll (String name) static
Definition at line 160 of file World.java.
{
        for (Player player : get().players) {
            if (player == null) {
                continue;
            }
            if (player.getUsername().equalsIgnoreCase(name)) {
                return Optional.of(player);
            }
        }
        for (Player player : World.get().getLogins()) {
            if (player == null) {
                continue;
            }
            if (player.getUsername().equalsIgnoreCase(name)) {
                return Optional.of(player);
            }
        }
        return Optional.empty();
    }
References players, and World().
Referenced by com.runehive.net.session.LoginSession.evaluate().
sendBroadcast()
void com.runehive.game.world.World.sendBroadcast (int time, String message, boolean countdown) static
Sends a game message.
Definition at line 420 of file World.java.
{
        get().players.stream().forEach($it -> {
            $it.send(new SendGameMessage(countdown ? 0 : 1, time, Utility.capitalizeSentence(message)));
            $it.send(new SendMessage("<col=2C7526>Broadcast: </col>" + Utility.capitalizeSentence(message)));
        });
    }
References com.runehive.util.Utility.capitalizeSentence(), and players.
Referenced by com.runehive.content.famehall.FameHandler.activate(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.generatePorazdirSpawn(), and com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn().
sendGraphic() [1/2]
void com.runehive.game.world.World.sendGraphic (Graphic graphic, Position position) static
Definition at line 277 of file World.java.
{
        get().players.stream().filter(player -> Utility.withinDistance(player, position, Region.VIEW_DISTANCE))
                .forEach(player -> {
                    player.send(new SendGraphic(graphic, position));
                });
    }
References players, com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinDistance().
sendGraphic() [2/2]
void com.runehive.game.world.World.sendGraphic (Graphic graphic, Position position, int instance) static
Sends a graphic to the world.
Definition at line 268 of file World.java.
{
        for (Player player : getPlayers()) {
            if (player.instance != instance)
                continue;
            if (!Utility.withinDistance(player, position, Region.VIEW_DISTANCE))
                continue;
            player.send(new SendGraphic(graphic, position));
        }
    }
References getPlayers(), com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinDistance().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.lavaTask(), com.runehive.content.activity.impl.magearena.MageArena.meteors(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonTask(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.content.activity.impl.magearena.MageArena.start(), com.runehive.content.activity.infernomobs.JalTokJad.RangedAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.start().
sendKillFeed()
void com.runehive.game.world.World.sendKillFeed (final Mob killer, final Mob victim) static
Sends a kill feed notification.
Definition at line 474 of file World.java.
{
        if (victim.isNpc()) {
            if (Area.inWilderness(victim)) {
                return;
            }
            if (!victim.getNpc().npcAssistant.isBoss()) {
                return;
            }
        }
        for (final Player player : getPlayers()) {
            player.send(new SendKillFeed(killer, victim));
        }
    }
References com.runehive.game.world.entity.mob.Mob.getNpc(), getPlayers(), com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.mob.npc.NpcAssistant.isBoss(), com.runehive.game.world.entity.mob.Mob.isNpc(), and com.runehive.game.world.entity.mob.npc.Npc.npcAssistant.
Referenced by com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.execute().
sendMessage() [1/2]
void com.runehive.game.world.World.sendMessage (String message, Predicate< Player > filter) static
Sends a global message with an exception.
Definition at line 405 of file World.java.
{
        if (com.runehive.Config.DISABLE_BROADCASTS) return;
        for (Player player : getPlayers()) {
            if (player != null && filter.test(player))
                player.message(message);
        }
    }
References getPlayers().
sendMessage() [2/2]
void com.runehive.game.world.World.sendMessage (String... messages) static
Sends a global message.
Definition at line 396 of file World.java.
{
        if (com.runehive.Config.DISABLE_BROADCASTS) return;
        for (Player player : getPlayers()) {
            if (player != null)
                player.message(messages);
        }
    }
References getPlayers().
Referenced by com.runehive.content.WellOfGoodwill.activate(), com.runehive.content.combat.Killstreak.announce(), com.runehive.content.RoyaltyProgram.append(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.defeated(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.defeated(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.defeated(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.combat.Killstreak.end(), com.runehive.content.bloodmoney.BloodChestEvent.execute(), com.runehive.game.task.impl.DoubleExperienceEvent.execute(), com.runehive.game.task.impl.MessageEvent.execute(), com.runehive.game.world.cronjobs.impl.DoubleExperienceJob.execute(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoEvent.execute(), com.runehive.content.bloodmoney.BloodMoneyChest.finish(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.generatePorazdirSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.generateSpawn(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMessages(), com.runehive.content.shootingstar.ShootingStar.init(), com.runehive.game.task.impl.DoubleExperienceEvent.onCancel(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.content.prestige.Prestige.prestige(), com.runehive.content.donators.Donation.redeem(), com.runehive.content.mysterybox.MysteryBoxEvent.reward(), com.runehive.game.world.entity.mob.player.Player.sendInitialPackets(), com.runehive.content.bloodmoney.BloodMoneyChest.spawn(), com.runehive.game.world.entity.mob.player.Player.unregister(), com.runehive.game.world.entity.skill.SkillManager.updateSkill(), and com.runehive.content.Yell.yell().
sendObjectAnimation()
void com.runehive.game.world.World.sendObjectAnimation (int animation, GameObject object) static
Sends a world object animation.
Definition at line 284 of file World.java.
{
        for (Player player : getPlayers()) {
            if (player.instance != object.getInstancedHeight())
                continue;
            if (!Utility.withinDistance(player, object.getPosition(), Region.VIEW_DISTANCE))
                continue;
            player.send(new SendObjectAnimation(animation, object));
        }
    }
References getPlayers(), com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinDistance().
Referenced by com.runehive.content.lms.LMSGame.rollChest(), and com.runehive.content.combat.cannon.CannonManager.rotate().
sendProjectile() [1/5]
void com.runehive.game.world.World.sendProjectile (Mob source, Mob target, Projectile projectile) static
Sends a world projectile.
Definition at line 307 of file World.java.
{
        int lockon = target.isNpc() ? target.getIndex() + 1 : -target.getIndex() - 1;
        int sourceX = source.getX() + source.width() / 2, sourceY = source.getY() + source.length() / 2;
        int targetX = target.getX() + target.width() / 2, targetY = target.getY() + target.length() / 2;
        byte offsetX = (byte) (targetX - sourceX);
        byte offsetY = (byte) (targetY - sourceY);
        Position center = new Position(sourceX, sourceY);
        for (Player player : getPlayers()) {
            if (source.instance != player.instance)
                continue;
            if (!Utility.withinDistance(target, player, Region.VIEW_DISTANCE))
                continue;
            player.send(new SendProjectile(projectile, center, lockon, offsetX, offsetY));
        }
    }
References com.runehive.game.world.entity.Entity.getIndex(), getPlayers(), com.runehive.game.world.entity.Entity.getX(), com.runehive.game.world.entity.Entity.getY(), com.runehive.game.world.entity.Entity.instance, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.Entity.length, com.runehive.game.world.region.Region.VIEW_DISTANCE, com.runehive.game.world.entity.Entity.width, and com.runehive.util.Utility.withinDistance().
sendProjectile() [2/5]
void com.runehive.game.world.World.sendProjectile (Mob source, Position target, Projectile projectile) static
Sends a world projectile.
Definition at line 340 of file World.java.
{
        int sourceX = source.getX() + source.width() / 2, sourceY = source.getY() + source.length() / 2;
        Position center = new Position(sourceX, sourceY);
        byte offsetX = (byte) (target.getX() - sourceX);
        byte offsetY = (byte) (target.getY() - sourceY);
        for (Player player : getPlayers()) {
            if (source.instance != player.instance)
                continue;
            if (!Utility.withinDistance(player, target, Region.VIEW_DISTANCE))
                continue;
            player.send(new SendProjectile(projectile, center, -1, offsetX, offsetY));
        }
    }
References getPlayers(), com.runehive.game.world.entity.Entity.getX(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.entity.Entity.getY(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.Entity.instance, com.runehive.game.world.entity.Entity.length, com.runehive.game.world.region.Region.VIEW_DISTANCE, com.runehive.game.world.entity.Entity.width, and com.runehive.util.Utility.withinDistance().
sendProjectile() [3/5]
void com.runehive.game.world.World.sendProjectile (Position source, Mob target, Projectile projectile) static
Definition at line 324 of file World.java.
{
        int lockon = target.isNpc() ? target.getIndex() + 1 : -target.getIndex() - 1;
        int sourceX = source.getX(), sourceY = source.getY();
        int targetX = target.getX() + target.width() / 2, targetY = target.getY() + target.length() / 2;
        byte offsetX = (byte) (targetX - sourceX);
        byte offsetY = (byte) (targetY - sourceY);
        Position center = new Position(sourceX, sourceY);
        for (Player player : getPlayers()) {
            if (!Utility.withinDistance(target, player, Region.VIEW_DISTANCE))
                continue;
            player.send(new SendProjectile(projectile, center, lockon, offsetX, offsetY));
        }
    }
References com.runehive.game.world.entity.Entity.getIndex(), getPlayers(), com.runehive.game.world.entity.Entity.getX(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.entity.Entity.getY(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.Entity.length, com.runehive.game.world.region.Region.VIEW_DISTANCE, com.runehive.game.world.entity.Entity.width, and com.runehive.util.Utility.withinDistance().
sendProjectile() [4/5]
void com.runehive.game.world.World.sendProjectile (Position source, Position target, Projectile projectile) static
Definition at line 354 of file World.java.
{
        int sourceX = source.getX(), sourceY = source.getY();
        Position center = new Position(sourceX, sourceY);
        byte offsetX = (byte) (target.getX() - sourceX);
        byte offsetY = (byte) (target.getY() - sourceY);
        for (Player player : getPlayers()) {
            if (!Utility.withinDistance(player, target, Region.VIEW_DISTANCE))
                continue;
            player.send(new SendProjectile(projectile, center, -1, offsetX, offsetY));
        }
    }
References getPlayers(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinDistance().
sendProjectile() [5/5]
void com.runehive.game.world.World.sendProjectile (Projectile projectile, Position position, int instance, int lock, byte offsetX, byte offsetY) static
Sends a world projectile.
Definition at line 295 of file World.java.
{
        for (Player player : getPlayers()) {
            if (player.instance != instance)
                continue;
            if (!Utility.withinDistance(player, position, Region.VIEW_DISTANCE))
                continue;
            player.send(new SendProjectile(projectile, position, lock, offsetX, offsetY));
        }
    }
References getPlayers(), com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinDistance().
Referenced by com.runehive.content.combat.cannon.CannonFireAction.execute(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MagicAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.poisonAttack(), com.runehive.game.Projectile.send(), com.runehive.game.Projectile.send(), com.runehive.game.world.entity.combat.projectile.CombatProjectile.sendProjectile(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.start().
sendStaffMessage()
void com.runehive.game.world.World.sendStaffMessage (String... messages) static
Definition at line 413 of file World.java.
{
        for (Player player : getStaff()) {
            player.message(messages);
        }
    }
References getStaff().
sequence()
void com.runehive.game.world.World.sequence ()
Handles the world sequencing.
Definition at line 92 of file World.java.
{
    }
shutdown()
void com.runehive.game.world.World.shutdown () static
Shuts down the server.
Definition at line 122 of file World.java.
{
        System.out.println("shutting down...");
        get().taskDeadlockWatcher.requestExit();
        System.exit(0);
    }
References taskDeadlockWatcher.
Referenced by com.runehive.game.task.impl.SystemUpdateEvent.onCancel().
update()
void com.runehive.game.world.World.update (int time) static
Updates the server.
Definition at line 113 of file World.java.
{
        if (!update.get()) {
            update.set(true);
            schedule(new SystemUpdateEvent(time));
            get().players.stream().forEach(it -> it.send(new SendGameMessage(0, time / 100, "System update" + " in:")));
        }
    }
References players, schedule(), and update.
Member Data Documentation
addition
int com.runehive.game.world.World.addition = 0 static
Definition at line 74 of file World.java.
Referenced by getPlayerCount().
dataBus
final DataBus com.runehive.game.world.World.dataBus = DataBus.getInstance() static private
Definition at line 77 of file World.java.
Referenced by getDataBus(), and World().
logger
final Logger com.runehive.game.world.World.logger = LogManager.getLogger(World.class) static private
Definition at line 48 of file World.java.
Referenced by dequeLogins(), process(), and save().
logins
final Queue<Player> com.runehive.game.world.World.logins = new ConcurrentLinkedQueue<>() private
The Players waiting to login.
Definition at line 57 of file World.java.
Referenced by dequeLogins(), getLogins(), and queueLogin().
logouts
final Queue<Player> com.runehive.game.world.World.logouts = new ConcurrentLinkedQueue<>() private
The Players waiting to onLogout.
Definition at line 60 of file World.java.
Referenced by dequeLogouts(), getLogouts(), and queueLogout().
npcs
final MobList<Npc> com.runehive.game.world.World.npcs = new MobList<>(Config.MAX_NPCS) private
The npcs registered in this world.
Definition at line 54 of file World.java.
Referenced by getNpcs().
players
final MobList<Player> com.runehive.game.world.World.players = new MobList<>(Config.MAX_PLAYERS) private
The players registered in this world.
Definition at line 51 of file World.java.
Referenced by getPlayers(), kickPlayer(), save(), search(), searchAll(), sendBroadcast(), sendGraphic(), and update().
regionManager
final RegionManager com.runehive.game.world.World.regionManager = new RegionManager() private
The region manager.
Definition at line 70 of file World.java.
Referenced by getRegions().
taskDeadlockWatcher
final TaskDeadlockWatcher com.runehive.game.world.World.taskDeadlockWatcher private
The task deadlock watcher relies on the TaskManager.
Definition at line 65 of file World.java.
Referenced by shutdown(), and World().
taskDeadlockWatcherThread
final Thread com.runehive.game.world.World.taskDeadlockWatcherThread private
The thread to watch task deadlocks on.
Definition at line 68 of file World.java.
Referenced by World().
taskManager
final TaskManager com.runehive.game.world.World.taskManager private
The task manager.
Definition at line 63 of file World.java.
Referenced by cancelTask(), getTaskManager(), process(), schedule(), and World().
update
final AtomicBoolean com.runehive.game.world.World.update = new AtomicBoolean(false) static
Definition at line 72 of file World.java.
Referenced by com.runehive.net.session.LoginSession.evaluate(), com.runehive.game.task.impl.PlayerSaveEvent.execute(), and update().
WORLD
final World com.runehive.game.world.World.WORLD = new World() static private
The world instance.
Definition at line 80 of file World.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/World.java