RuneHive-Game: com.runehive.game.world.items.containers.bank.BankVault Class Reference
com.runehive.game.world.items.containers.bank.BankVault Class Reference
Handles the bank vault system.
Public Member Functions
boolean add (VaultCurrency currency, long amount)
Adds an amount into the player's bank vault with no checks.
boolean add (VaultCurrency currency, long amount, boolean message)
Adds an amount into the player's bank vault with no checks.
BankVault (Player player)
Constructs a new BankVault.
boolean contains (VaultCurrency currency, int amount)
Checks if player's bank container contains a certain amount.
void deposit (VaultCurrency currency, int amount)
Deposits an an amount into the player's bank vaut.
void open ()
void remove (VaultCurrency currency, int amount)
Removes a certain amount from the player's bank vault container.
void value (VaultCurrency currency)
Sends message to player about their container value.
void withdraw (VaultCurrency currency, long amount)
Withdraws a certain amount into the player's bank vault container.
Public Attributes
long bloodMoneyContainer
long coinsContainer
Private Member Functions
long getContainer (VaultCurrency currency)
Private Attributes
final Player player
The player instance.
Detailed Description
Handles the bank vault system.
Author
Daniel
Since
12-1-2017.
Definition at line 21 of file BankVault.java.
Constructor & Destructor Documentation
BankVault()
com.runehive.game.world.items.containers.bank.BankVault.BankVault (Player player)
Constructs a new BankVault.
Definition at line 31 of file BankVault.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
add() [1/2]
boolean com.runehive.game.world.items.containers.bank.BankVault.add (VaultCurrency currency, long amount)
Adds an amount into the player's bank vault with no checks.
Careful how you use this!
Definition at line 60 of file BankVault.java.
{
        return add(currency, amount, false);
    }
References add().
Referenced by com.runehive.content.achievement.AchievementHandler.activate(), add(), com.runehive.content.triviabot.TriviaBot.answered(), and deposit().
add() [2/2]
boolean com.runehive.game.world.items.containers.bank.BankVault.add (VaultCurrency currency, long amount, boolean message)
Adds an amount into the player's bank vault with no checks.
Careful how you use this!
Definition at line 65 of file BankVault.java.
{
        long container = getContainer(currency);
        if (player.right == PlayerRight.ULTIMATE_IRONMAN) {
            player.inventory.addOrDrop(new Item(currency.id, (int) amount));
            return true;
        }
        if (container + amount >= Long.MAX_VALUE) {
            return false;
        }
        if (currency == COINS) {
            coinsContainer += amount;
        } else if (currency == BLOOD_MONEY) {
            bloodMoneyContainer += amount;
        }
        if (message) {
            player.send(new SendMessage(Utility.formatDigits(amount) + " " + currency.name + " have been added into your bank vault.", MessageColor.DARK_BLUE));
        }
        return true;
    }
References bloodMoneyContainer, coinsContainer, com.runehive.util.MessageColor.DARK_BLUE, com.runehive.util.Utility.formatDigits(), getContainer(), com.runehive.game.world.items.containers.bank.VaultCurrency.id, com.runehive.game.world.items.containers.bank.VaultCurrency.name, player, and com.runehive.game.world.entity.mob.player.PlayerRight.ULTIMATE_IRONMAN.
contains()
boolean com.runehive.game.world.items.containers.bank.BankVault.contains (VaultCurrency currency, int amount)
Checks if player's bank container contains a certain amount.
Definition at line 55 of file BankVault.java.
{
        return getContainer(currency) >= amount;
    }
References getContainer().
deposit()
void com.runehive.game.world.items.containers.bank.BankVault.deposit (VaultCurrency currency, int amount)
Deposits an an amount into the player's bank vaut.
Definition at line 99 of file BankVault.java.
{
        long container = getContainer(currency);
        if (Long.MAX_VALUE == container) {
            player.send(new SendMessage("Your vault is currently full and can no longer hold any more " + currency.name + "!", MessageColor.RED));
            return;
        }
        if (Long.MAX_VALUE - container < amount) {
            amount = (int) (Long.MAX_VALUE - container);
        }
        int invAmount = player.inventory.computeAmountForId(currency.id);
        int bankAmount = 0;
        if (invAmount < amount) {
            bankAmount = player.bank.computeAmountForId(currency.id);
            if (invAmount + bankAmount <= 0) {
                player.send(new SendMessage("You don't have any " + currency.name + " you noob!", MessageColor.RED));
                return;
            }
        }
        if (invAmount > amount) {
            invAmount = amount;
        }
        if (bankAmount > amount - invAmount) {
            bankAmount = amount - invAmount;
        }
        amount = invAmount + bankAmount;
        if (invAmount > 0)
            player.inventory.remove(currency.id, invAmount);
        if (bankAmount > 0)
            player.bank.remove(currency.id, bankAmount);
        add(currency, amount);
        player.bank.refresh();
        player.send(new SendMessage("You now have " + Utility.formatDigits(container) + " " + currency.name + " stored inside your bank vault.", MessageColor.DARK_RED));
        if (player.interfaceManager.isInterfaceOpen(56300)) {
            long coins = getContainer(COINS);
            long bloodMoney = getContainer(BLOOD_MONEY);
            player.send(new SendString(Utility.formatDigits(coins), 56311));
            player.send(new SendString(Utility.formatDigits(bloodMoney), 56312));
            player.send(new SendItemOnInterface(56314, new Item(995,  coins), new Item(13307, bloodMoney)));
        }
    }
References add(), com.runehive.util.MessageColor.DARK_RED, com.runehive.util.Utility.formatDigits(), getContainer(), com.runehive.game.world.items.containers.bank.VaultCurrency.id, com.runehive.game.world.items.containers.bank.VaultCurrency.name, player, and com.runehive.util.MessageColor.RED.
getContainer()
long com.runehive.game.world.items.containers.bank.BankVault.getContainer (VaultCurrency currency) private
Definition at line 44 of file BankVault.java.
{
        return currency == COINS ? coinsContainer : bloodMoneyContainer;
    }
References bloodMoneyContainer, and coinsContainer.
Referenced by add(), contains(), deposit(), open(), value(), and withdraw().
open()
void com.runehive.game.world.items.containers.bank.BankVault.open ()
Definition at line 35 of file BankVault.java.
                       {
        long coins = getContainer(COINS);
        long bloodMoney = getContainer(BLOOD_MONEY);
        player.send(new SendString(Utility.formatDigits(coins), 56311));
        player.send(new SendString(Utility.formatDigits(bloodMoney), 56312));
        player.send(new SendItemOnInterface(56314, new Item(995, coins), new Item(13307, bloodMoney)));
        player.interfaceManager.open(56300);
    }
References com.runehive.util.Utility.formatDigits(), getContainer(), and player.
remove()
void com.runehive.game.world.items.containers.bank.BankVault.remove (VaultCurrency currency, int amount)
Removes a certain amount from the player's bank vault container.
Definition at line 90 of file BankVault.java.
{
        if (currency == COINS) {
            coinsContainer -= amount;
        } else if (currency == BLOOD_MONEY) {
            bloodMoneyContainer -= amount;
        }
    }
References bloodMoneyContainer, and coinsContainer.
value()
void com.runehive.game.world.items.containers.bank.BankVault.value (VaultCurrency currency)
Sends message to player about their container value.
Definition at line 49 of file BankVault.java.
{
        long container = getContainer(currency);
        player.send(new SendMessage("You currently have " + Utility.formatDigits(container) + " " + currency.name + " stored inside your bank vault.", MessageColor.DARK_RED));
    }
References com.runehive.util.MessageColor.DARK_RED, com.runehive.util.Utility.formatDigits(), getContainer(), com.runehive.game.world.items.containers.bank.VaultCurrency.name, and player.
withdraw()
void com.runehive.game.world.items.containers.bank.BankVault.withdraw (VaultCurrency currency, long amount)
Withdraws a certain amount into the player's bank vault container.
Definition at line 151 of file BankVault.java.
{
        long container = getContainer(currency);
        if (amount < 0) {
            return;
        }
        if (container == 0) {
            player.send(new SendMessage("Your bank vault is currently empty.", MessageColor.RED));
            return;
        }
        if (amount > Integer.MAX_VALUE) {
            player.send(new SendMessage("You can not hold more than " + Utility.formatPrice(Integer.MAX_VALUE) + " " + currency.name + " at a time.", MessageColor.RED));
            return;
        }
        if (amount > container) {
            amount = container;
        }
        int contain = player.inventory.computeAmountForId(currency.id);
        if (contain + amount > Integer.MAX_VALUE) {
            amount = contain - amount;
        }
        if (player.inventory.add(new Item(currency.id, (int) amount))) {
            remove(currency, (int) amount);
            player.send(new SendMessage("You have successfully withdrawn " + Utility.formatDigits(amount) + " " + currency.name + "."));
            player.bank.refresh();
        }
        if (player.interfaceManager.isInterfaceOpen(56300)) {
            long coins = getContainer(COINS);
            long bloodMoney = getContainer(BLOOD_MONEY);
            player.send(new SendString(Utility.formatDigits(coins), 56311));
            player.send(new SendString(Utility.formatDigits(bloodMoney), 56312));
            player.send(new SendItemOnInterface(56314, new Item(995, (int) coins), new Item(13307, (int) bloodMoney)));
        }
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatPrice(), getContainer(), com.runehive.game.world.items.containers.bank.VaultCurrency.id, com.runehive.game.world.items.containers.bank.VaultCurrency.name, player, and com.runehive.util.MessageColor.RED.
Member Data Documentation
bloodMoneyContainer
long com.runehive.game.world.items.containers.bank.BankVault.bloodMoneyContainer
Definition at line 27 of file BankVault.java.
Referenced by add(), getContainer(), and remove().
coinsContainer
long com.runehive.game.world.items.containers.bank.BankVault.coinsContainer
Definition at line 26 of file BankVault.java.
Referenced by add(), getContainer(), and remove().
player
final Player com.runehive.game.world.items.containers.bank.BankVault.player private
The player instance.
Definition at line 24 of file BankVault.java.
Referenced by add(), BankVault(), deposit(), open(), value(), and withdraw().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/bank/BankVault.java