RuneHive-Game: com.runehive.util.chance.WeightedChance< T > Class Template Reference
com.runehive.util.chance.WeightedChance< T > Class Template Reference
An item with a common chance.
Public Member Functions
int compareTo (WeightedObject< T > o)
T get ()
Gets the representation of the weighted chance.
double getWeight ()
Gets the object's weight.
String toString ()
WeightedChance (double weight, T representation)
Private Attributes
final T representation
The representation.
double weight
The weight type.
Detailed Description
An item with a common chance.
Author
Michael | Chex
Definition at line 10 of file WeightedChance.java.
Constructor & Destructor Documentation
WeightedChance()
com.runehive.util.chance.WeightedChance< T >.WeightedChance (double weight, T representation)
Definition at line 18 of file WeightedChance.java.
{
        if (weight <= 0) {
            throw new IllegalArgumentException("The weight of an item must be larger than zero!");
        }
        this.representation = Objects.requireNonNull(representation);
        this.weight = weight;
    }
References representation, and weight.
Member Function Documentation
compareTo()
int com.runehive.util.chance.WeightedChance< T >.compareTo (WeightedObject< T > o)
Definition at line 37 of file WeightedChance.java.
{
        return (int) (getWeight() - o.getWeight());
    }
References getWeight(), and com.runehive.util.chance.WeightedObject< T >.getWeight().
get()
T com.runehive.util.chance.WeightedChance< T >.get ()
Gets the representation of the weighted chance.
Implements com.runehive.util.chance.WeightedObject< T >.
Definition at line 32 of file WeightedChance.java.
                   {
        return representation;
    }
References representation.
getWeight()
double com.runehive.util.chance.WeightedChance< T >.getWeight ()
Gets the object's weight.
Implements com.runehive.util.chance.WeightedObject< T >.
Definition at line 27 of file WeightedChance.java.
{
        return weight;
    }
References weight.
Referenced by compareTo(), and toString().
toString()
String com.runehive.util.chance.WeightedChance< T >.toString ()
Implements com.runehive.util.chance.WeightedObject< T >.
Definition at line 42 of file WeightedChance.java.
{
        return "[Object: " + get() + ", " + "Weight: " + getWeight() + "]";
    }
References getWeight().
Member Data Documentation
representation
final T com.runehive.util.chance.WeightedChance< T >.representation private
The representation.
Definition at line 13 of file WeightedChance.java.
Referenced by get(), and WeightedChance().
weight
double com.runehive.util.chance.WeightedChance< T >.weight private
The weight type.
Definition at line 16 of file WeightedChance.java.
Referenced by getWeight(), and WeightedChance().
The documentation for this class was generated from the following file:
java/com/runehive/util/chance/WeightedChance.java