RuneHive-Game: com.runehive.game.world.entity.combat.hit.CombatHit Class Reference
com.runehive.game.world.entity.combat.hit.CombatHit Class Reference
A wrapper for a Hit object, adding additional variables for hit and hitsplat delays.
Public Member Functions
CombatHit (Hit hit, int hitDelay, int hitsplatDelay)
Constructs a new CombatHit object.
CombatHit (Hit[] hits, int hitDelay, int hitsplatDelay)
CombatHit copyAndModify (Function< Integer, Integer > modifier)
Copies and modifies this combat hit.
int getHitDelay ()
int getHitsplatDelay ()
boolean getMultipleHitsAllowed ()
Public Member Functions inherited from com.runehive.game.world.entity.combat.hit.Hit
int getDamage ()
Gets the damage amount.
HitIcon getHitIcon ()
Gets the hit icon.
Hitsplat getHitsplat ()
Gets the damage type.
Hit[] getMultipleHits ()
Hit (Hit[] multipleHits)
Constructs a new Hit object.
Hit (int damage)
Constructs a new Hit object.
Hit (int damage, HitIcon hitIcon)
Constructs a new Hit object.
Hit (int damage, Hitsplat hitsplat)
Constructs a new Hit object.
Hit (int damage, Hitsplat hitsplat, HitIcon hitIcon)
Constructs a new Hit object.
Hit (int damage, Hitsplat hitsplat, HitIcon hitIcon, boolean accurate)
Constructs a new Hit object.
boolean isAccurate ()
Checks if the hit is accurate.
void modifyDamage (Function< Integer, Integer > modifier)
Sets the hit damage with a function.
void setAccurate (boolean accurate)
void setAs (Hit other)
void setDamage (int damage)
Sets the hit damage.
void setHitsplat (Hitsplat hitsplat)
void setIcon (HitIcon hitIcon)
Sets the hit icon.
Private Attributes
final int hitDelay
The hit delay.
final int hitsplatDelay
The hitsplat delay.
final boolean multipleHitsAllowed
Detailed Description
A wrapper for a Hit object, adding additional variables for hit and hitsplat delays.
Author
Michael | Chex
Definition at line 11 of file CombatHit.java.
Constructor & Destructor Documentation
CombatHit() [1/2]
com.runehive.game.world.entity.combat.hit.CombatHit.CombatHit (Hit hit, int hitDelay, int hitsplatDelay)
Constructs a new CombatHit object.
Definition at line 22 of file CombatHit.java.
{
        super(hit.getDamage(), hit.getHitsplat(), hit.getHitIcon(), hit.isAccurate());
        this.hitDelay = hitDelay;
        this.hitsplatDelay = hitsplatDelay;
        this.multipleHitsAllowed = false;
    }
References com.runehive.game.world.entity.combat.hit.Hit.Hit(), hitDelay, and hitsplatDelay.
Referenced by copyAndModify().
CombatHit() [2/2]
com.runehive.game.world.entity.combat.hit.CombatHit.CombatHit (Hit[] hits, int hitDelay, int hitsplatDelay)
Definition at line 29 of file CombatHit.java.
{
        super(hits);
        this.hitDelay = hitDelay;
        this.hitsplatDelay = hitsplatDelay;
        this.multipleHitsAllowed = true;
    }
References com.runehive.game.world.entity.combat.hit.Hit.Hit(), hitDelay, and hitsplatDelay.
Member Function Documentation
copyAndModify()
CombatHit com.runehive.game.world.entity.combat.hit.CombatHit.copyAndModify (Function< Integer, Integer > modifier)
Copies and modifies this combat hit.
Parameters
modifier the damage modification
Returns
a copy of this combat hit with the damage modifier applied
Definition at line 42 of file CombatHit.java.
{
        CombatHit next = new CombatHit(this, hitDelay, hitsplatDelay);
        next.modifyDamage(modifier);
        return next;
    }
References CombatHit(), hitDelay, hitsplatDelay, and com.runehive.game.world.entity.combat.hit.Hit.modifyDamage().
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.getHits(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.secondOption(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.thirdOption().
getHitDelay()
int com.runehive.game.world.entity.combat.hit.CombatHit.getHitDelay ()
Returns
the hit delay.
Definition at line 49 of file CombatHit.java.
{
        return hitDelay;
    }
References hitDelay.
getHitsplatDelay()
int com.runehive.game.world.entity.combat.hit.CombatHit.getHitsplatDelay ()
Returns
the hit delay.
Definition at line 54 of file CombatHit.java.
{
        return hitsplatDelay;
    }
References hitsplatDelay.
getMultipleHitsAllowed()
boolean com.runehive.game.world.entity.combat.hit.CombatHit.getMultipleHitsAllowed ()
Definition at line 58 of file CombatHit.java.
{
        return multipleHitsAllowed;
    }
References multipleHitsAllowed.
Member Data Documentation
hitDelay
final int com.runehive.game.world.entity.combat.hit.CombatHit.hitDelay private
The hit delay.
Definition at line 14 of file CombatHit.java.
Referenced by CombatHit(), CombatHit(), copyAndModify(), and getHitDelay().
hitsplatDelay
final int com.runehive.game.world.entity.combat.hit.CombatHit.hitsplatDelay private
The hitsplat delay.
Definition at line 17 of file CombatHit.java.
Referenced by CombatHit(), CombatHit(), copyAndModify(), and getHitsplatDelay().
multipleHitsAllowed
final boolean com.runehive.game.world.entity.combat.hit.CombatHit.multipleHitsAllowed private
Definition at line 19 of file CombatHit.java.
Referenced by getMultipleHitsAllowed().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/hit/CombatHit.java