RuneHive-Game: com.runehive.game.world.entity.combat.CombatUtil Class Reference
com.runehive.game.world.entity.combat.CombatUtil Class Reference
A collection of util methods and constants related to combat.
Static Public Member Functions
static void areaAction (Mob mob, Consumer< Mob > action)
Executes an action for mobs within a 3x3 square, including the source mob.
static void areaAction (Mob mob, int max, int distance, Consumer< Mob > action)
Sends an action to Mob instance which is within a
distance.
static boolean canAttack (Mob attacker, Mob defender)
static boolean canBasicAttack (Mob attacker, Mob defender)
static boolean cancelEffect (Mob mob, CombatEffectType effect)
Cancels the effect in any context.
static CombatStrategy< Npc >[] createStrategyArray (CombatStrategy< Npc >... strategies)
static CombatStrategy< Npc >[] createStrategyArray (CombatStrategy< Npc >[] strategies, CombatStrategy< Npc >... moreStrategies)
static boolean effect (Mob mob, CombatEffectType effect)
Applies the effect in any context.
static CombatHit generateDragonfire (Mob attacker, Mob defender, int max, boolean prayer)
static CombatHit generateDragonfire (Mob attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean prayer)
static Animation getBlockAnimation (Mob mob)
static int getHitDelay (final Mob attacker, final Mob defender, final CombatType type)
Gets the hit delay for the specified type.
static int getHitsplatDelay (CombatType type)
Gets the hitsplat delay for the specified type.
static CombatStrategy< Npc > randomStrategy (CombatStrategy< Npc >[] strategies)
Static Package Functions
static boolean validate (Mob attacker, Mob defender)
static boolean validateMobs (Mob attacker, Mob defender)
Private Member Functions
CombatUtil ()
The default constructor.
Static Private Member Functions
static boolean canAttack (Npc attacker, Mob defender)
static boolean canAttack (Player attacker, Mob defender)
static int getOldHitDelay (final Mob attacker, final Mob defender, final CombatType type)
static boolean validate (Mob mob)
Detailed Description
A collection of util methods and constants related to combat.
Author
lare96 http://github.com/lare96
Definition at line 40 of file CombatUtil.java.
Constructor & Destructor Documentation
CombatUtil()
com.runehive.game.world.entity.combat.CombatUtil.CombatUtil () private
The default constructor.
Exceptions
UnsupportedOperationException if this class is instantiated.
Definition at line 47 of file CombatUtil.java.
{
        throw new UnsupportedOperationException("This class cannot be instantiated!");
    }
Member Function Documentation
areaAction() [1/2]
void com.runehive.game.world.entity.combat.CombatUtil.areaAction (Mob mob, Consumer< Mob > action) static
Executes an action for mobs within a 3x3 square, including the source mob.
Parameters
mob the mob to generate an area for
action the action to apply to all mobs in the area
Definition at line 58 of file CombatUtil.java.
{
        action.accept(mob);
        areaAction(mob, 3 * 3, 1, action);
    }
References areaAction().
Referenced by areaAction(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.hitsplat(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Melee.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack.start(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.start(), and com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.start().
areaAction() [2/2]
void com.runehive.game.world.entity.combat.CombatUtil.areaAction (Mob mob, int max, int distance, Consumer< Mob > action) static
Sends an action to Mob instance which is within a
distance.
Parameters
action action consumer.
Definition at line 69 of file CombatUtil.java.
{
        if (!Area.inMulti(mob)) {
            return;
        }
        int added = 0;
        List<Player> players = World.getRegions().getLocalPlayers(mob);
        players.sort((first, second) -> {
            int firstD = Utility.getDistance(first, mob);
            int secondD = Utility.getDistance(second, mob);
            return firstD - secondD;
        });
        for (Player other : players) {
            if (other == null) continue;
            if (other.instance != mob.instance) continue;
            if (!Utility.withinViewingDistance(other, mob, distance)) continue;
            if (other.equals(mob)) continue;
            if (other.getCurrentHealth() <= 0 || other.isDead()) continue;
            if (!Area.inMulti(other)) continue;
            if (mob.isPlayer() && other.isPlayer() && (!Area.inWilderness(mob) || !Area.inWilderness(other)))
                continue;
            action.accept(other);
            if (++added == max) return;
        }
        List<Npc> npcs = World.getRegions().getLocalNpcs(mob);
        npcs.sort((first, second) -> {
            int firstD = Utility.getDistance(first, mob);
            int secondD = Utility.getDistance(second, mob);
            return firstD - secondD;
        });
        for (Npc other : npcs) {
            if (other == null) continue;
            if (other.instance != mob.instance) continue;
            if (!Utility.withinViewingDistance(other, mob, distance)) continue;
            if (other.equals(mob)) continue;
            if (other.getCurrentHealth() <= 0 || other.isDead()) continue;
            if (!Area.inMulti(other)) continue;
            if (!other.definition.isAttackable()) continue;
            action.accept(other);
            if (++added == max) return;
        }
    }
References com.runehive.util.Utility.getDistance(), com.runehive.game.world.region.RegionManager.getLocalNpcs(), com.runehive.game.world.region.RegionManager.getLocalPlayers(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.position.Area.inMulti(), com.runehive.game.world.position.Area.inWilderness(), and com.runehive.util.Utility.withinViewingDistance().
canAttack() [1/3]
boolean com.runehive.game.world.entity.combat.CombatUtil.canAttack (Mob attacker, Mob defender) static
Definition at line 214 of file CombatUtil.java.
{
        if (attacker.isPlayer())
            return canAttack(attacker.getPlayer(), defender);
        return canAttack(attacker.getNpc(), defender);
    }
References canAttack(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.getPlayer(), and com.runehive.game.world.entity.mob.Mob.isPlayer().
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.canAttack(), canAttack(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate(), and validateMobs().
canAttack() [2/3]
boolean com.runehive.game.world.entity.combat.CombatUtil.canAttack (Npc attacker, Mob defender) static private
Definition at line 318 of file CombatUtil.java.
{
        if (attacker.equals(defender)) {
            return false;
        }
        if (defender.isNpc() && defender.getNpc().owner != null && !defender.getNpc().owner.equals(attacker)) {
            return false;
        }
        if (attacker.getCombat().isUnderAttack() && !attacker.getCombat().isUnderAttackBy(defender)) {
            if (!Area.inMulti(attacker) || !Area.inMulti(defender)) {
                return false;
            }
        }
        if (defender.getCombat().isUnderAttack() && !defender.getCombat().isUnderAttackBy(attacker)) {
            return Area.inMulti(attacker) && Area.inMulti(defender);
        }
        return true;
    }
References com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.mob.npc.Npc.equals(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.mob.npc.Npc.getCombat(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.position.Area.inMulti(), com.runehive.game.world.entity.mob.Mob.isNpc(), and com.runehive.game.world.entity.mob.npc.Npc.owner.
canAttack() [3/3]
boolean com.runehive.game.world.entity.combat.CombatUtil.canAttack (Player attacker, Mob defender) static private
Definition at line 220 of file CombatUtil.java.
{
        if (defender.isNpc() && !SlayerTask.canAttack(attacker, defender.getName())) {
            attacker.send(new SendMessage("You do not meet the slayer requirements to attack this npc!"));
            return false;
        }
        if (attacker.equals(defender)) {
            //attacker.send(new SendMessage("You can't attack yourself!"));
            return false;
        }
        if (defender.isNpc() && defender.getNpc().owner != null && !attacker.equals(defender.getNpc().owner)) {
            attacker.send(new SendMessage("You can't attack this npc!"));
            return false;
        }
        if (attacker.getCombat().isUnderAttack() && !attacker.getCombat().isUnderAttackBy(defender)) {
            if (!Area.inMulti(attacker) || !Area.inMulti(defender)) {
                attacker.send(new SendMessage("You are already under attack!"));
                return false;
            }
        }
        if (defender.getCombat().isUnderAttack() && !defender.getCombat().isUnderAttackBy(attacker)) {
            if (!Area.inMulti(attacker) || !Area.inMulti(defender)) {
                if (defender.isPlayer()) {
                    attacker.send(new SendMessage(defender.getName() + " is currently in combat and can not be attacked."));
                } else {
                    attacker.send(new SendMessage("This monster is already under attack!"));
                }
                return false;
            }
        }
        if (defender.isPlayer()) {
            if (attacker.locking.locked(PacketType.COMBAT)) {
                return false;
            }
            if (LMSGame.inGameArea(attacker) && LMSGame.canAttack(attacker, defender.getPlayer())) {
                return true;
            }
            if (Activity.evaluate(attacker, activity -> defender.activity == activity) && attacker.inActivity(ActivityType.DUEL_ARENA)) {
                return true;
            }
/*
            if (Area.inEventArena(attacker) && Area.inEventArena(defender)) {
                return true;
            }
*/
            int difference = Math.abs(attacker.skills.getCombatLevel() - defender.skills.getCombatLevel());
            if (attacker.pvpInstance) {
                if (!defender.getPlayer().pvpInstance) {
                    attacker.message(defender.getName() + " is not in a PvP instance.");
                    return false;
                }
                if (!Area.inPvP(attacker) && !attacker.hasPvPTimer) {
                    attacker.message("You must be in a PvP zone to attack " + defender.getName() + "!");
                    return false;
                }
                if (!Area.inPvP(defender) && !defender.getPlayer().hasPvPTimer) {
                    attacker.message(defender.getName() + " must be in a PvP zone for you to attack!");
                    return false;
                }
                if (difference > 10) {
                    if (!Area.inDuelObsticleArena(attacker)) {
                        attacker.message("Your combat level difference is too great!");
                        return false;
                    }
                }
                return true;
            }
            if (difference > attacker.wilderness) {
                if (!Area.inDuelObsticleArena(attacker)) {
                    attacker.send(new SendMessage("Your combat level difference is too great!"));
                    return false;
                }
            }
            if (!Area.inWilderness(attacker)) {
                attacker.send(new SendMessage("You need to be in the wilderness to attack " + Utility.formatName(defender.getName()) + "."));
                return false;
            }
            if (!Area.inWilderness(defender)) {
                attacker.send(new SendMessage(Utility.formatName(defender.getName()) + " must be in the wilderness for you to attack."));
                return false;
            }
        }
        return true;
    }
References com.runehive.game.world.entity.mob.Mob.activity, com.runehive.content.lms.LMSGame.canAttack, com.runehive.content.skill.impl.slayer.SlayerTask.canAttack(), com.runehive.game.world.entity.mob.data.PacketType.COMBAT, com.runehive.content.activity.ActivityType.DUEL_ARENA, com.runehive.game.world.entity.mob.player.Player.equals(), com.runehive.content.activity.Activity.evaluate(), com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getCombatLevel(), com.runehive.game.world.entity.Entity.getName(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.player.Player.hasPvPTimer, com.runehive.game.world.entity.mob.Mob.inActivity(), com.runehive.game.world.position.Area.inDuelObsticleArena(), com.runehive.content.lms.LMSGame.inGameArea(), com.runehive.game.world.position.Area.inMulti(), com.runehive.game.world.position.Area.inPvP(), com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.Locking.locked(), com.runehive.game.world.entity.mob.Mob.locking, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.npc.Npc.owner, com.runehive.game.world.entity.mob.player.Player.pvpInstance, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.mob.player.Player.wilderness.
canBasicAttack()
boolean com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack (Mob attacker, Mob defender) static
Definition at line 336 of file CombatUtil.java.
{
        if (attacker.equals(defender)) {
            return false;
        }
        if (defender.isNpc() && defender.getNpc().owner != null && !attacker.equals(defender.getNpc().owner)) {
            return false;
        }
        if (Activity.evaluate(attacker, activity -> defender.activity == activity) && attacker.inActivity(ActivityType.DUEL_ARENA)) {
            return true;
        }
        if (attacker.getCombat().isUnderAttack() && !attacker.getCombat().isUnderAttackBy(defender)) {
            if (!Area.inMulti(attacker) || !Area.inMulti(defender)) {
                return false;
            }
        }
        if (defender.getCombat().isUnderAttack() && !defender.getCombat().isUnderAttackBy(attacker)) {
            if (!Area.inMulti(attacker) || !Area.inMulti(defender)) {
                return false;
            }
        }
        if (attacker.isPlayer() && defender.isPlayer()) {
            int difference = Math.abs(attacker.skills.getCombatLevel() - defender.skills.getCombatLevel());
            if (attacker.getPlayer().pvpInstance || defender.getPlayer().pvpInstance) {
                if (!defender.getPlayer().pvpInstance) {
                    return false;
                }
                if (!attacker.getPlayer().pvpInstance) {
                    return false;
                }
                if (!Area.inPvP(attacker)) {
                    return false;
                }
                if (!Area.inPvP(defender)) {
                    return false;
                }
                return difference <= 10;
            }
            if (difference > attacker.getPlayer().wilderness) {
                return false;
            }
            if (!Area.inWilderness(attacker)) {
                return false;
            }
            return Area.inWilderness(defender);
        }
        return true;
    }
References com.runehive.game.world.entity.mob.Mob.activity, com.runehive.content.activity.ActivityType.DUEL_ARENA, com.runehive.game.world.entity.Entity.equals(), com.runehive.content.activity.Activity.evaluate(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getCombatLevel(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.Mob.inActivity(), com.runehive.game.world.position.Area.inMulti(), com.runehive.game.world.position.Area.inPvP(), com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.npc.Npc.owner, com.runehive.game.world.entity.mob.player.Player.pvpInstance, com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.mob.player.Player.wilderness.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.hitEvent(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.hitEvent(), and validate().
cancelEffect()
boolean com.runehive.game.world.entity.combat.CombatUtil.cancelEffect (Mob mob, CombatEffectType effect) static
Cancels the effect in any context.
Parameters
effect the effect that must be applied
Returns
true if it was successfully applied
Definition at line 210 of file CombatUtil.java.
{
        return CombatEffect.EFFECTS.get(effect).removeOn(mob);
    }
References effect(), and com.runehive.game.world.entity.combat.effect.CombatEffect.EFFECTS.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.resetEffects().
createStrategyArray() [1/2]
CombatStrategy< Npc >[] com.runehive.game.world.entity.combat.CombatUtil.createStrategyArray (CombatStrategy< Npc >... strategies) static
Definition at line 485 of file CombatUtil.java.
{
        return strategies;
    }
createStrategyArray() [2/2]
CombatStrategy< Npc >[] com.runehive.game.world.entity.combat.CombatUtil.createStrategyArray (CombatStrategy< Npc >[] strategies, CombatStrategy< Npc >... moreStrategies) static
Definition at line 490 of file CombatUtil.java.
{
        final CombatStrategy<Npc>[] array = new CombatStrategy[strategies.length + moreStrategies.length];
        System.arraycopy(strategies, 0, array, 0, strategies.length);
        System.arraycopy(moreStrategies, 0, array, strategies.length, moreStrategies.length);
        return array;
    }
effect()
boolean com.runehive.game.world.entity.combat.CombatUtil.effect (Mob mob, CombatEffectType effect) static
Applies the effect in any context.
Parameters
effect the effect that must be applied
Returns
true if it was successfully applied
Definition at line 200 of file CombatUtil.java.
{
        return CombatEffect.EFFECTS.get(effect).start(mob);
    }
References effect(), and com.runehive.game.world.entity.combat.effect.CombatEffect.EFFECTS.
Referenced by cancelEffect(), effect(), com.runehive.content.consume.PotionData.onAntiFireEffect(), com.runehive.game.world.entity.mob.Mob.poison(), com.runehive.game.world.entity.combat.magic.MagicImpact.teleblock(), and com.runehive.game.world.entity.mob.Mob.venom().
generateDragonfire() [1/2]
CombatHit com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire (Mob attacker, Mob defender, int max, boolean prayer) static
Definition at line 417 of file CombatUtil.java.
{
        int hitDelay = getHitDelay(attacker, defender, CombatType.MAGIC);
        int hitsplatDelay = 1;
        return generateDragonfire(attacker, defender, max, hitDelay, hitsplatDelay, prayer);
    }
References generateDragonfire(), getHitDelay(), and com.runehive.game.world.entity.combat.CombatType.MAGIC.
Referenced by generateDragonfire(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.Dragonfire.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Dragonfire.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Freeze.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Poison.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Shock.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.DragonfireAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.PinkDragonfireAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomDragonfireAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.impl.BrutalDragonfireStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.npc.impl.DragonfireStrategy.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.getHits(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack.hit().
generateDragonfire() [2/2]
CombatHit com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire (Mob attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean prayer) static
Definition at line 423 of file CombatUtil.java.
{
        int damage;
        if (defender.isPlayer()) {
            Player player = defender.getPlayer();
            if (Equipment.isWearingDFS(player) && player.dragonfireCharges < 50) {
                if (player.equipment.getShield().getId() == 11284) {
                    player.equipment.set(Equipment.SHIELD_SLOT, new Item(11283), true);
                    player.equipment.refresh();
                }
                player.animate(6695);
                player.graphic(1164);
                player.dragonfireCharges++;
                player.getCombat().setCooldown(5);
                player.send(new SendMessage("Your dragonfire Shield Absorbs the Dragon breath."));
                player.face(attacker);
                damage = 0;
            } else {
                prayer &= player.prayer.isActive(Prayer.PROTECT_FROM_MAGIC);
                boolean shield = player.equipment.containsAny(1540, 11283, 21633);
                boolean potion = player.getAntifireDetails().isPresent();
                if (shield && potion) {
                    max -= 65;
                } else if (potion) {
                    AntifireDetails.AntifireType type = player.getAntifireDetails().get().getType();
                    max -= type.getReduction();
                    if (max <= 0) {
                        max = 0;
                    }
                } else if (shield) {
                    max -= 50;
                } else if (prayer) {
                    max -= 45;
                }
                if (max > 0) {
                    damage = RandomUtils.inclusive(max);
                } else {
                    damage = 0;
                }
                if (damage >= 15) {
                    player.send(new SendMessage("You are horribly burned by the dragonfire!", true));
                } else if (!shield && !potion && !prayer && damage < 9 && damage > 0) {
                    player.send(new SendMessage("You manage to resist some of the dragonfire.", true));
                }
            }
        } else {
            damage = max == 0 ? 0 : RandomUtils.inclusive(max);
        }
        Hit hit = new Hit(damage, Hitsplat.NORMAL, HitIcon.NONE, true);
        return new CombatHit(hit, hitDelay, hitsplatDelay);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.items.containers.ItemContainer.containsAny(), com.runehive.game.world.entity.mob.player.Player.dragonfireCharges, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.Mob.face(), com.runehive.game.world.entity.mob.player.Player.getAntifireDetails(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.items.containers.equipment.Equipment.getShield(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.util.RandomUtils.inclusive(), com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.items.containers.equipment.Equipment.isWearingDFS(), com.runehive.game.world.entity.combat.hit.HitIcon.NONE, com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MAGIC, com.runehive.game.world.items.containers.equipment.Equipment.refresh(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.items.containers.ItemContainer.set(), and com.runehive.game.world.items.containers.equipment.Equipment.SHIELD_SLOT.
getBlockAnimation()
Animation com.runehive.game.world.entity.combat.CombatUtil.getBlockAnimation (Mob mob) static
Definition at line 391 of file CombatUtil.java.
{
        int animation = 404;
        if (mob.isPlayer()) {
            final var shieldOverride = mob.getPlayer().overrides.hasOverride(Equipment.SHIELD_SLOT);
            if (mob.getPlayer().equipment.hasShield() || shieldOverride) {
                Item shield = shieldOverride ? mob.getPlayer().overrides.get(Equipment.SHIELD_SLOT) : mob.getPlayer().equipment.getShield();
                animation = shield.getBlockAnimation().orElse(424);
            } else if (mob.isPlayer()) {
                final var weaponOverride = mob.getPlayer().overrides.hasOverride(Equipment.WEAPON_SLOT);
                if (mob.getPlayer().equipment.hasWeapon() || weaponOverride) {
                    Item weapon = weaponOverride ? mob.getPlayer().overrides.get(Equipment.WEAPON_SLOT) : mob.getPlayer().equipment.getWeapon();
                    animation = weapon.getBlockAnimation().orElse(424);
                } else {
                    animation = 404;//TODO
                }
            }
        } else {
            Npc npc = mob.getNpc();
            animation = npc.definition.getBlockAnimation();
        }
        int delay = (int) mob.getCombat().lastBlocked.elapsedTime();
        if (delay < 600)
            return new Animation(animation, delay / 50, UpdatePriority.LOW);
        return new Animation(animation, UpdatePriority.LOW);
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getBlockAnimation(), com.runehive.game.world.items.Item.getBlockAnimation(), com.runehive.game.UpdatePriority.LOW, com.runehive.game.world.items.containers.equipment.Equipment.SHIELD_SLOT, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.hit().
getHitDelay()
int com.runehive.game.world.entity.combat.CombatUtil.getHitDelay (final Mob attacker, final Mob defender, final CombatType type) static
Gets the hit delay for the specified type.
Parameters
attacker the character doing the hit
defender the victim being hit
type the combat type of this hit
Returns
the delay for the combat type
Definition at line 123 of file CombatUtil.java.
{
        if (CombatType.MELEE.equals(type)) return 0;
        final CombatStrategy<? super Mob> strategy = attacker.getStrategy();
        if (strategy != null) {
            final CombatProjectile combatProjectile = strategy.getCombatProjectile();
            if (combatProjectile != null) {
                final int serverTicks = combatProjectile.getServerTicks();
                if (serverTicks > 0) {
                    return serverTicks;
                }
            }
        }
        return getOldHitDelay(attacker, defender, type);
    }
References getOldHitDelay(), com.runehive.game.world.entity.combat.projectile.CombatProjectile.getServerTicks(), com.runehive.game.world.entity.mob.Mob.getStrategy(), and com.runehive.game.world.entity.combat.CombatType.MELEE.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.fourthOption(), generateDragonfire(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack.getHits(), com.runehive.game.world.entity.combat.magic.MagicImpact.hitEvent(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.start().
getHitsplatDelay()
int com.runehive.game.world.entity.combat.CombatUtil.getHitsplatDelay (CombatType type) static
Gets the hitsplat delay for the specified type.
Parameters
type the combat type of this hit
Returns
the delay for the combat type
Definition at line 154 of file CombatUtil.java.
{
        return type.getHitsplatDelay();
    }
References com.runehive.game.world.entity.combat.CombatType.getHitsplatDelay().
getOldHitDelay()
int com.runehive.game.world.entity.combat.CombatUtil.getOldHitDelay (final Mob attacker, final Mob defender, final CombatType type) static private
Definition at line 139 of file CombatUtil.java.
{
        final int distance = Math.min(10, Utility.getDistance(attacker, defender));
        return switch (type) {
            default -> 0;
            case RANGED -> Projectile.RANGED_DELAYS[distance] - 1;
            case MAGIC -> Projectile.MAGIC_DELAYS[distance] - 1;
        };
    }
References com.runehive.util.Utility.getDistance().
Referenced by getHitDelay().
randomStrategy()
CombatStrategy< Npc > com.runehive.game.world.entity.combat.CombatUtil.randomStrategy (CombatStrategy< Npc >[] strategies) static
Definition at line 480 of file CombatUtil.java.
{
        return RandomUtils.random(strategies);
    }
References com.runehive.util.RandomUtils.random().
validate() [1/2]
boolean com.runehive.game.world.entity.combat.CombatUtil.validate (Mob attacker, Mob defender) static package
Definition at line 176 of file CombatUtil.java.
{
        if (!validate(attacker) || !validate(defender)) {
            attacker.getCombat().reset();
            return false;
        }
        if (attacker.instance != defender.instance) {
            attacker.getCombat().reset();
            return false;
        }
        if (!canBasicAttack(attacker, defender)) {
            attacker.getCombat().reset();
            return false;
        }
        return true;
    }
References canBasicAttack(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.Entity.instance, and validate().
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.canAttack(), validate(), and validateMobs().
validate() [2/2]
boolean com.runehive.game.world.entity.combat.CombatUtil.validate (Mob mob) static private
Definition at line 387 of file CombatUtil.java.
{
        return mob != null && !mob.isDead() && mob.isVisible() && mob.isValid() && !mob.teleporting && !mob.inTeleport;
    }
validateMobs()
boolean com.runehive.game.world.entity.combat.CombatUtil.validateMobs (Mob attacker, Mob defender) static package
Definition at line 158 of file CombatUtil.java.
{
        if (!validate(attacker) || !validate(defender)) {
            attacker.getCombat().reset();
            return false;
        }
        if (attacker.instance != defender.instance) {
            attacker.getCombat().reset();
            return false;
        }
        if (!canAttack(attacker, defender)) {
            attacker.getCombat().reset();
            return false;
        }
        return true;
    }
References canAttack(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.Entity.instance, and validate().
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.canAttack(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplat(), and com.runehive.game.world.entity.combat.Combat< T extends Mob >.start().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/CombatUtil.java