RuneHive-Game: com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch Class Reference
com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch Class Reference
A WaterablePatch that can grow flowers and scarecrows for battling disease on an AllotmentPatch.
Public Member Functions
FlowerPatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new FlowerPatch object.
boolean itemOnObject (Item item, int index)
Plant plantForSeed (int seedId)
boolean protectsDisease (int protect)
Checks if this flower patch protects an allotment patch from disease.
Public Member Functions inherited from com.runehive.content.skill.impl.farming.patches.WaterablePatch
WaterablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new WaterablePatch object.
Public Member Functions inherited from com.runehive.content.skill.impl.farming.patches.DiseasablePatch
boolean clickObject (int opcode)
void fromJson (JsonObject object)
JsonObject toJson ()
Public Member Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
int getConfig ()
boolean isComposted ()
boolean isDead ()
boolean isDiseased ()
boolean isEmpty ()
boolean isGrowing ()
boolean isNormal ()
boolean isWatered ()
boolean needsWeeding ()
void setDead ()
void setDiseased ()
void setEmpty ()
void setNormal ()
void setWatered ()
void tick ()
boolean within (Position position)
Static Public Attributes
static final int SCARECROW = 6059
The scarecrow item id.
Protected Member Functions
int animation ()
int getMaxAmount ()
int getMinAmount ()
Protected Member Functions inherited from com.runehive.content.skill.impl.farming.patches.WaterablePatch
void onGrowth ()
Protected Member Functions inherited from com.runehive.content.skill.impl.farming.patches.DiseasablePatch
DiseasablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
void resetPatch ()
Private Member Functions
boolean plantScareCrow (int item, int index)
Plants a scarecrow in this patch if the requirements are met.
Additional Inherited Members
Protected Attributes inherited from com.runehive.content.skill.impl.farming.patches.DiseasablePatch
boolean watched
Protected Attributes inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
CompostType compost
boolean fullyGrown
int growth
Plant plant
final Player player
FarmingStage stage = FarmingStage.FULL_WEEDS
FarmingState state = FarmingState.NORMAL
final Stopwatch timer = Stopwatch.start()
final FarmingZone zone
Package Functions inherited from com.runehive.content.skill.impl.farming.patches.HarvestablePatch
HarvestablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new HarvestablePatch object.
Package Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
FarmingPatch (Player player, FarmingZone zone, Interactable[] boundaries)
Detailed Description
A WaterablePatch that can grow flowers and scarecrows for battling disease on an AllotmentPatch.
Author
Michael | Chex
Definition at line 19 of file FlowerPatch.java.
Constructor & Destructor Documentation
FlowerPatch()
com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.FlowerPatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new FlowerPatch object.
Parameters
player the player that owns this patch
zone the zone this patch belongs to
boundaries the boundaries of this patch
Definition at line 31 of file FlowerPatch.java.
{
        super(player, zone, boundaries);
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.boundaries, com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, and com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone.
Member Function Documentation
animation()
int com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.animation () protected
Returns
the harvesting animation
Reimplemented from com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 105 of file FlowerPatch.java.
{
        return FarmingConstants.PICKING_VEGETABLE_ANIM;
    }
References com.runehive.content.skill.impl.farming.FarmingConstants.PICKING_VEGETABLE_ANIM.
getMaxAmount()
int com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.getMaxAmount () protected
Returns
the maximum amount of produce to harvest
Reimplemented from com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 100 of file FlowerPatch.java.
{
        return 1;
    }
getMinAmount()
int com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.getMinAmount () protected
Returns
the minimum amount of produce to harvest
Reimplemented from com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 95 of file FlowerPatch.java.
{
        return 1;
    }
itemOnObject()
boolean com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.itemOnObject (Item item, int index)
Reimplemented from com.runehive.content.skill.impl.farming.patches.WaterablePatch.
Definition at line 90 of file FlowerPatch.java.
{
        return plantScareCrow(item.getId(), index) || super.itemOnObject(item, index);
    }
References com.runehive.game.world.items.Item.getId(), and plantScareCrow().
plantForSeed()
Plant com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.plantForSeed (int seedId)
Reimplemented from com.runehive.content.skill.impl.farming.patches.FarmingPatch.
Definition at line 85 of file FlowerPatch.java.
{
        return Flower.forId(seedId);
    }
References com.runehive.content.skill.impl.farming.plants.Flower.forId().
Referenced by plantScareCrow().
plantScareCrow()
boolean com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.plantScareCrow (int item, int index) private
Plants a scarecrow in this patch if the requirements are met.
Parameters
item the presumed scarecrow item id
index the index of the item
Returns
true if the scarecrow was successfully planted
Definition at line 42 of file FlowerPatch.java.
{
        if (player.locking.locked()) {
            return false;
        }
        if (plant == null || item != SCARECROW) {
            return false;
        }
        if (!isEmpty()) {
            player.message("You need to clear the patch before planting a scarecrow.");
            return false;
        }
        player.animate(832);
        player.inventory.remove(new Item(SCARECROW), index, true);
        player.locking.lock(2 * 3 / 5);
        World.schedule(2, () -> {
            player.message("You put a scarecrow on the flower patch, and some weeds start to grow around it.");
            plant = plantForSeed(0x24);
            timer.reset();
            zone.sendPatchConfigs(player);
        });
        return true;
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.isEmpty(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.plant, plantForSeed(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, SCARECROW, com.runehive.game.world.World.schedule(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.timer, and com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone.
Referenced by itemOnObject().
protectsDisease()
boolean com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.protectsDisease (int protect)
Checks if this flower patch protects an allotment patch from disease.
Parameters
protect the allotment patch's protect flower id
Returns
true if this flower will protect the allotment from disease
Definition at line 76 of file FlowerPatch.java.
{
        if (!isDead() && fullyGrown && plant.getSeedId() == protect) {
            setDead();
            return true;
        }
        return protect == SCARECROW && plant.getSeedId() >= 0x21 && plant.getSeedId() <= 0x24;
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.fullyGrown, com.runehive.content.skill.impl.farming.patches.FarmingPatch.isDead(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.plant, SCARECROW, and com.runehive.content.skill.impl.farming.patches.FarmingPatch.setDead().
Member Data Documentation
SCARECROW
final int com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.SCARECROW = 6059 static
The scarecrow item id.
Definition at line 22 of file FlowerPatch.java.
Referenced by plantScareCrow(), and protectsDisease().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/farming/patches/impl/FlowerPatch.java