RuneHive-Game: com.runehive.game.world.items.containers.inventory.Inventory Class Reference
com.runehive.game.world.items.containers.inventory.Inventory Class Reference
An ItemContainer implementation that manages the inventory for a Player.
Classes
class InventoryListener
An ItemContainerAdapter implementation that listens for changes to the inventory.
Public Member Functions
void addOrBank (Item... items)
Attempts to deposit an item to the players inventory, if there is no space it'll bank the item instead.
void addOrBank (List< Item > items)
Attempts to deposit an item to the players inventory, if there is no space it'll bank the item instead.
void addOrDrop (Item... items)
Attempts to deposit an item to the players inventory, if there is no space it'll bank the item instead.
void addOrDrop (List< Item > items)
Attempts to deposit an item to the players inventory, if there is no space it'll bank the item instead.
void addOrExecute (Consumer< Item > action, Item... items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
void addOrExecute (Consumer< Item > action, List< Item > items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
void addOrExecute (Consumer< Item > action, Optional< String > message, Item... items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
void addOrExecute (Consumer< Item > action, Optional< String > message, List< Item > items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
void addOrExecute (Consumer< Item > action, String message, Item... items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
void addOrExecute (Consumer< Item > action, String message, List< Item > items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
Inventory (Player player)
Creates a new Inventory.
void refresh ()
Refreshes the players inventory.
void refresh (Player player, int widget)
Refreshes the inventory container.
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainer
boolean add (int id, int amount)
Attempts to deposit item into this container.
boolean add (Item item)
Attempts to deposit item into this container.
boolean add (Item item, boolean refresh, boolean stack)
boolean add (Item item, int preferredIndex, boolean refresh)
boolean add (Item item, int preferredIndex, boolean refresh, boolean stack)
Attempts to deposit item into this container, preferably at preferredIndex.
boolean add (Item item, int slot)
Attempts to deposit item into this container.
boolean addAll (Collection<? extends Item > items)
Attempts to deposit items in bulk into this container.
boolean addAll (Item... items)
Attempts to deposit items in bulk into this container.
boolean addAll (ItemContainer items)
Attempts to deposit items in bulk into this container.
final boolean addListener (ItemContainerListener listener)
Adds an ItemContainerListener to this container.
boolean allowZero ()
final int capacity ()
void clear ()
Removes all of the items from this container.
final void clear (boolean refresh)
Removes all of the items from this container.
final int computeAmountForId (int id)
Computes the total quantity of the Items in this container with id.
final int computeFreeIndex ()
Computes the next free (null) index in this container.
final Optional< Integer > computeIdForIndex (int index)
Computes the identifier of the Item on index.
final int computeIndexCount (Item... forItems)
Computes the amount of indexes required to hold items in this container.
final int computeIndexForId (int id)
Computes the first index found that id is in.
long containerValue (PriceType type)
Gets the total worth of the container using the item's values.
boolean contains (int id)
Determines if this container contains id.
final boolean contains (int id, int amount)
final boolean contains (Item item)
final boolean containsAll (Collection< Item > items)
final boolean containsAll (int... identifiers)
Determines if this container contains all identifiers.
final boolean containsAll (Item... items)
final boolean containsAny (Collection< Item > items)
final boolean containsAny (int... identifiers)
Determines if this container contains any identifiers.
final boolean containsAny (Item... items)
final ItemContainer copy ()
Creates a copy of the underlying item container.
final void fireBulkItemsUpdatedEvent ()
Fires the ItemContainerListener.bulkItemsUpdated(ItemContainer) event.
final void fireCapacityExceededEvent ()
Fires the ItemContainerListener.capacityExceeded(ItemContainer) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh)
Fires the ItemContainerListener.itemUpdated(ItemContainer, int) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh, boolean login)
final void forEach (Consumer<? super Item > action)
Iterates through all of the Items within this container and performs action on them, skipping empty indexes (null values) as they are encountered.
final Item get (int index)
Gets the Item located on index.
int getFreeSlots ()
final int getId (int index)
Gets the item id located on index.
Item[] getItems ()
int getSlotById (int id)
Gets a slot by id.
double getWeight ()
Gets the weight of the container.
final boolean hasCapacityAfter (Item[] add, Item... remove)
Creates a copy of the underlying container and removes the items specified from it and after tries to deposit the specified items to it.
final boolean hasCapacityFor (Item... item)
Determines if this container has the capacity for item.
final void ifPresent (int index, Consumer< Item > action)
Consumes an action if the index is a valid item index in this container.
final boolean indexFree (int index)
Returns true if index is not occupied (null).
final boolean indexOccupied (int index)
Returns true if index is occupied (non-null).
final void insert (int oldIndex, int newIndex, boolean refresh)
final boolean isEmpty ()
final boolean isFull ()
ItemContainer (int capacity, StackPolicy policy)
Creates a new ItemContainer.
ItemContainer (int capacity, StackPolicy policy, Item[] items)
Creates a new ItemContainer.
final Iterator< Item > iterator ()
void onRefresh ()
Any functionality that should occur when refreshed.
final StackPolicy policy ()
final int remaining ()
boolean remove (int id)
boolean remove (int id, int amount)
boolean remove (Item item)
Attempts to withdraw item from this container.
boolean remove (Item item, int preferredIndex)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean remove (Item item, int preferredIndex, boolean refresh)
boolean remove (Item item, int preferredIndex, boolean refresh, boolean removeAll)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean removeAll (Collection<? extends Item > items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (Item... items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (ItemContainer items)
Attempts to withdraw items in bulk from this container.
final boolean removeListener (ItemContainerListener listener)
Removes an ItemContainerListener from this container.
final boolean replace (int oldId, int newId, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (int oldId, int newId, int index, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (Item first, Item second, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replaceAll (int oldId, int newId)
Replaces all occurrences of Items having the identifier
oldId with newId.
final Optional< Item > retrieve (int index)
Retrieves the item located on index.
Optional< Item > search (int id)
Searches and returns the first item found with id.
Optional< Item > search (Item item)
Searches and returns the first item found with id and
amount.
void set (int index, Item item, boolean refresh)
Sets the index to item.
final void set (Item[] toSet)
void setFiringEvents (boolean firingEvents)
Sets the value for firingEvents.
final void setItems (Item[] items)
final void setItems (Item[] items, boolean copy)
Sets the container of items to items.
void shift ()
Percolates the null indices to the end of the stack.
final int size ()
final Spliterator< Item > spliterator ()
final Stream< Item > stream ()
final void swap (boolean insert, int oldIndex, int newIndex, boolean refresh)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex, boolean refresh)
final Item[] toArray ()
Returns a shallow copy of the backing array.
final Item[] toNonNullArray ()
final void transfer (int firstIndex, int secondIndex, ItemContainer other, boolean refresh)
Static Public Attributes
static final int INVENTORY_DISPLAY_ID = 3214
The inventory item display widget identifier.
static final int SIZE = 28
The size of all equipment instances.
Private Attributes
final Player player
The player instance for which this inventory applies to.
Detailed Description
An ItemContainer implementation that manages the inventory for a Player.
Author
lare96 http://github.com/lare96
Definition at line 23 of file Inventory.java.
Constructor & Destructor Documentation
Inventory()
com.runehive.game.world.items.containers.inventory.Inventory.Inventory (Player player)
Creates a new Inventory.
Definition at line 35 of file Inventory.java.
{
        super(SIZE, StackPolicy.STANDARD);
        addListener(new InventoryListener(player));
//      addListener(new ItemWeightListener(player));TODO
        this.player = player;
    }
References com.runehive.game.world.items.containers.ItemContainer.addListener(), player, SIZE, and com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD.
Member Function Documentation
addOrBank() [1/2]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrBank (Item... items)
Attempts to deposit an item to the players inventory, if there is no space it'll bank the item instead.
Definition at line 142 of file Inventory.java.
{
        addOrBank(Arrays.asList(items));
    }
References addOrBank(), and com.runehive.game.world.items.containers.ItemContainer.items.
addOrBank() [2/2]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrBank (List< Item > items)
Attempts to deposit an item to the players inventory, if there is no space it'll bank the item instead.
Definition at line 134 of file Inventory.java.
{
        addOrExecute(t -> player.bank.depositFromNothing(t, 0), "@red@Some of the items were banked since you have no room in your inventory.", items);
    }
References addOrExecute(), com.runehive.game.world.items.containers.ItemContainer.items, and player.
Referenced by addOrBank().
addOrDrop() [1/2]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop (Item... items)
Attempts to deposit an item to the players inventory, if there is no space it'll bank the item instead.
Definition at line 126 of file Inventory.java.
{
        addOrDrop(Arrays.asList(items));
    }
References addOrDrop(), and com.runehive.game.world.items.containers.ItemContainer.items.
addOrDrop() [2/2]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop (List< Item > items)
Attempts to deposit an item to the players inventory, if there is no space it'll bank the item instead.
Definition at line 118 of file Inventory.java.
{
        addOrExecute(t -> GroundItem.create(player, t), "@red@Some of the items were dropped since you have no room in your inventory.", items);
    }
References addOrExecute(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.items.containers.ItemContainer.items, and player.
Referenced by addOrDrop(), com.runehive.content.RoyaltyProgram.append(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.content.combat.Killstreak.end(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.gambling.GambleManager.give(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.store.impl.SkillcapeStore.purchase(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), and com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards().
addOrExecute() [1/6]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute (Consumer< Item > action, Item... items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
Definition at line 110 of file Inventory.java.
{
        addOrExecute(action, Arrays.asList(items));
    }
References addOrExecute(), and com.runehive.game.world.items.containers.ItemContainer.items.
addOrExecute() [2/6]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute (Consumer< Item > action, List< Item > items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
Definition at line 101 of file Inventory.java.
{
        addOrExecute(action, Optional.empty(), items);
    }
References addOrExecute(), and com.runehive.game.world.items.containers.ItemContainer.items.
addOrExecute() [3/6]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute (Consumer< Item > action, Optional< String > message, Item... items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
Definition at line 74 of file Inventory.java.
{
        addOrExecute(action, message, Arrays.asList(items));
    }
References addOrExecute(), and com.runehive.game.world.items.containers.ItemContainer.items.
addOrExecute() [4/6]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute (Consumer< Item > action, Optional< String > message, List< Item > items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
Definition at line 52 of file Inventory.java.
{
        boolean val = false;
        for (Item item : items) {
            if (item == null)
                continue;
            if (hasCapacityFor(item)) {
                player.inventory.add(item);
            } else {
                action.accept(item);
                val = true;
            }
        }
        if (val) {
            message.ifPresent(m -> player.send(new SendMessage(m)));
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.items.containers.ItemContainer.items, and player.
Referenced by addOrBank(), addOrDrop(), addOrExecute(), addOrExecute(), addOrExecute(), addOrExecute(), and addOrExecute().
addOrExecute() [5/6]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute (Consumer< Item > action, String message, Item... items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
Definition at line 83 of file Inventory.java.
{
        addOrExecute(action, Optional.of(message), Arrays.asList(items));
    }
References addOrExecute(), and com.runehive.game.world.items.containers.ItemContainer.items.
addOrExecute() [6/6]
void com.runehive.game.world.items.containers.inventory.Inventory.addOrExecute (Consumer< Item > action, String message, List< Item > items)
Attempts to deposit the items to the inventory, if inventory is full it'll execute the action for the remaining items that were not added.
Definition at line 92 of file Inventory.java.
{
        addOrExecute(action, Optional.of(message), items);
    }
References addOrExecute(), and com.runehive.game.world.items.containers.ItemContainer.items.
refresh() [1/2]
void com.runehive.game.world.items.containers.inventory.Inventory.refresh ()
Refreshes the players inventory.
Definition at line 43 of file Inventory.java.
{
        refresh(player, INVENTORY_DISPLAY_ID);
    }
References INVENTORY_DISPLAY_ID, player, and refresh().
Referenced by com.runehive.content.wintertodt.Wintertodt.award(), com.runehive.content.itemaction.impl.CelestialRing.charge(), com.runehive.content.itemaction.impl.CrawsBow.charge(), com.runehive.content.itemaction.impl.ThammaronsSceptre.charge(), com.runehive.content.itemaction.impl.ViggorasChainmace.charge(), com.runehive.content.gambling.GambleManager.decline(), com.runehive.content.gambling.GambleManager.deposit(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.depositeAll(), com.runehive.content.bags.ItemBag.empty(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.bags.ItemBag.fill(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.itemUpdated(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), refresh(), com.runehive.content.wintertodt.Wintertodt.removeGameItems(), com.runehive.content.lms.LMSGame.reset(), com.runehive.content.lms.LMSGame.resupplyKiller(), com.runehive.content.itemaction.impl.TridentOfTheSeas.uncharge(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.uncharge(), and com.runehive.content.gambling.GambleManager.withdraw().
refresh() [2/2]
void com.runehive.game.world.items.containers.inventory.Inventory.refresh (Player player, int widget)
Refreshes the inventory container.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 148 of file Inventory.java.
{
        player.send(new SendItemOnInterface(widget, toArray()));
    }
References player, and com.runehive.game.world.items.containers.ItemContainer.toArray().
Member Data Documentation
INVENTORY_DISPLAY_ID
final int com.runehive.game.world.items.containers.inventory.Inventory.INVENTORY_DISPLAY_ID = 3214 static
The inventory item display widget identifier.
Definition at line 29 of file Inventory.java.
Referenced by com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.getWidgetId(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnPlayer(), and refresh().
player
final Player com.runehive.game.world.items.containers.inventory.Inventory.player private
The player instance for which this inventory applies to.
Definition at line 32 of file Inventory.java.
Referenced by addOrBank(), addOrDrop(), addOrExecute(), Inventory(), refresh(), and refresh().
SIZE
final int com.runehive.game.world.items.containers.inventory.Inventory.SIZE = 28 static
The size of all equipment instances.
Definition at line 26 of file Inventory.java.
Referenced by Inventory().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/inventory/Inventory.java