RuneHive-Game: com.runehive.content.combat.Killstreak Class Reference
com.runehive.content.combat.Killstreak Class Reference
Public Member Functions
void add ()
void end (Player killer)
Killstreak (Player player)
void reward ()
Public Attributes
int streak
Private Member Functions
void announce ()
boolean announcementNeeded ()
Private Attributes
final Player player
Detailed Description
Definition at line 11 of file Killstreak.java.
Constructor & Destructor Documentation
Killstreak()
com.runehive.content.combat.Killstreak.Killstreak (Player player)
Definition at line 15 of file Killstreak.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
add()
void com.runehive.content.combat.Killstreak.add ()
Definition at line 19 of file Killstreak.java.
                      {
        streak++;
        if (announcementNeeded()) {
            reward();
            announce();
        }
    }
References announce(), announcementNeeded(), reward(), and streak.
Referenced by com.runehive.game.world.entity.mob.player.PlayerKilling.handle().
announce()
void com.runehive.content.combat.Killstreak.announce () private
Definition at line 47 of file Killstreak.java.
{
        String icon = "<icon=0>";
        String name = PlayerRight.getCrown(player) + " " + player.getName();
        int bounty = streak * 150;
        World.sendMessage("<col=FF0000>" + icon + " " + name + " </col>is now on a killstreak of <col=FF0000>" + streak + "</col>. Bounty: <col=FF0000>" + Utility.formatDigits(bounty) + "</col> BM.");
        if (streak == 5) {
            AchievementHandler.activate(player, AchievementKey.KILLSTKREAK_5);
        } else if (streak == 10) {
            AchievementHandler.activate(player, AchievementKey.KILLSTKREAK_10);
        } else if (streak == 15) {
            AchievementHandler.activate(player, AchievementKey.KILLSTKREAK_15);
        } else if (streak == 25) {
            AchievementHandler.activate(player, AchievementKey.KILLSTKREAK_25);
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.content.achievement.AchievementKey.KILLSTKREAK_10, com.runehive.content.achievement.AchievementKey.KILLSTKREAK_15, com.runehive.content.achievement.AchievementKey.KILLSTKREAK_25, com.runehive.content.achievement.AchievementKey.KILLSTKREAK_5, player, com.runehive.game.world.World.sendMessage(), and streak.
Referenced by add().
announcementNeeded()
boolean com.runehive.content.combat.Killstreak.announcementNeeded () private
Definition at line 64 of file Killstreak.java.
{
        return streak >= 5;
    }
References streak.
Referenced by add(), and end().
end()
void com.runehive.content.combat.Killstreak.end (Player killer)
Definition at line 28 of file Killstreak.java.
{
        if (announcementNeeded()) {
            String icon = "<icon=0>";
            String name = PlayerRight.getCrown(player) + " " + player.getName();
            int bounty = streak * 150;
            World.sendMessage("" + icon + " <col=FF0000>" + name + "</col> has lost their kill streak of <col=FF0000>" + streak + "</col> to <col=FF0000>" + killer.getName() + "</col>!");
            killer.inventory.addOrDrop(new Item(13307, bounty));
            killer.message("You were rewarded with " + Utility.formatDigits(bounty) + " blood money for claiming " + player.getName() + "'s bounty!");
        }
        streak = 0;
    }
References com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), announcementNeeded(), com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), player, com.runehive.game.world.World.sendMessage(), and streak.
reward()
void com.runehive.content.combat.Killstreak.reward ()
Definition at line 41 of file Killstreak.java.
{
        int bm = streak * 500;
        player.inventory.addOrDrop(new Item(13307, bm));
        player.message("<col=FF0000>You are rewarded with " + Utility.formatDigits(bm) + " blood money.");
    }
References com.runehive.util.Utility.formatDigits(), player, and streak.
Referenced by add().
Member Data Documentation
player
final Player com.runehive.content.combat.Killstreak.player private
Definition at line 12 of file Killstreak.java.
Referenced by announce(), end(), Killstreak(), and reward().
streak
int com.runehive.content.combat.Killstreak.streak
Definition at line 13 of file Killstreak.java.
Referenced by add(), announce(), announcementNeeded(), end(), reward(), and com.runehive.content.ProfileViewer.string().
The documentation for this class was generated from the following file:
java/com/runehive/content/combat/Killstreak.java