RuneHive-Game: com.runehive.game.world.items.containers.bank.DonatorDeposit Class Reference
com.runehive.game.world.items.containers.bank.DonatorDeposit Class Reference
Handles the donator deposit box.
Public Member Functions
void close ()
Handles closing the donator deposit box.
void confirm ()
Handles confirming the deposit.
boolean deposit (int id, int slot, int amount)
Handles deposting items into the container.
DonatorDeposit (Player player)
void onRefresh ()
Any functionality that should occur when refreshed.
void open ()
Handles opening the donator deposit box.
boolean withdraw (int id, int slot, int amount)
Handles withdrawing items from the container.
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainer
boolean add (int id, int amount)
Attempts to deposit item into this container.
boolean add (Item item)
Attempts to deposit item into this container.
boolean add (Item item, boolean refresh, boolean stack)
boolean add (Item item, int preferredIndex, boolean refresh)
boolean add (Item item, int preferredIndex, boolean refresh, boolean stack)
Attempts to deposit item into this container, preferably at preferredIndex.
boolean add (Item item, int slot)
Attempts to deposit item into this container.
boolean addAll (Collection<? extends Item > items)
Attempts to deposit items in bulk into this container.
boolean addAll (Item... items)
Attempts to deposit items in bulk into this container.
boolean addAll (ItemContainer items)
Attempts to deposit items in bulk into this container.
final boolean addListener (ItemContainerListener listener)
Adds an ItemContainerListener to this container.
boolean allowZero ()
final int capacity ()
void clear ()
Removes all of the items from this container.
final void clear (boolean refresh)
Removes all of the items from this container.
final int computeAmountForId (int id)
Computes the total quantity of the Items in this container with id.
final int computeFreeIndex ()
Computes the next free (null) index in this container.
final Optional< Integer > computeIdForIndex (int index)
Computes the identifier of the Item on index.
final int computeIndexCount (Item... forItems)
Computes the amount of indexes required to hold items in this container.
final int computeIndexForId (int id)
Computes the first index found that id is in.
long containerValue (PriceType type)
Gets the total worth of the container using the item's values.
boolean contains (int id)
Determines if this container contains id.
final boolean contains (int id, int amount)
final boolean contains (Item item)
final boolean containsAll (Collection< Item > items)
final boolean containsAll (int... identifiers)
Determines if this container contains all identifiers.
final boolean containsAll (Item... items)
final boolean containsAny (Collection< Item > items)
final boolean containsAny (int... identifiers)
Determines if this container contains any identifiers.
final boolean containsAny (Item... items)
final ItemContainer copy ()
Creates a copy of the underlying item container.
final void fireBulkItemsUpdatedEvent ()
Fires the ItemContainerListener.bulkItemsUpdated(ItemContainer) event.
final void fireCapacityExceededEvent ()
Fires the ItemContainerListener.capacityExceeded(ItemContainer) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh)
Fires the ItemContainerListener.itemUpdated(ItemContainer, int) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh, boolean login)
final void forEach (Consumer<? super Item > action)
Iterates through all of the Items within this container and performs action on them, skipping empty indexes (null values) as they are encountered.
final Item get (int index)
Gets the Item located on index.
int getFreeSlots ()
final int getId (int index)
Gets the item id located on index.
Item[] getItems ()
int getSlotById (int id)
Gets a slot by id.
double getWeight ()
Gets the weight of the container.
final boolean hasCapacityAfter (Item[] add, Item... remove)
Creates a copy of the underlying container and removes the items specified from it and after tries to deposit the specified items to it.
final boolean hasCapacityFor (Item... item)
Determines if this container has the capacity for item.
final void ifPresent (int index, Consumer< Item > action)
Consumes an action if the index is a valid item index in this container.
final boolean indexFree (int index)
Returns true if index is not occupied (null).
final boolean indexOccupied (int index)
Returns true if index is occupied (non-null).
final void insert (int oldIndex, int newIndex, boolean refresh)
final boolean isEmpty ()
final boolean isFull ()
ItemContainer (int capacity, StackPolicy policy)
Creates a new ItemContainer.
ItemContainer (int capacity, StackPolicy policy, Item[] items)
Creates a new ItemContainer.
final Iterator< Item > iterator ()
final StackPolicy policy ()
void refresh (Player player, int widget)
Sends the items on the itemcontainer.
final int remaining ()
boolean remove (int id)
boolean remove (int id, int amount)
boolean remove (Item item)
Attempts to withdraw item from this container.
boolean remove (Item item, int preferredIndex)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean remove (Item item, int preferredIndex, boolean refresh)
boolean remove (Item item, int preferredIndex, boolean refresh, boolean removeAll)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean removeAll (Collection<? extends Item > items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (Item... items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (ItemContainer items)
Attempts to withdraw items in bulk from this container.
final boolean removeListener (ItemContainerListener listener)
Removes an ItemContainerListener from this container.
final boolean replace (int oldId, int newId, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (int oldId, int newId, int index, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (Item first, Item second, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replaceAll (int oldId, int newId)
Replaces all occurrences of Items having the identifier
oldId with newId.
final Optional< Item > retrieve (int index)
Retrieves the item located on index.
Optional< Item > search (int id)
Searches and returns the first item found with id.
Optional< Item > search (Item item)
Searches and returns the first item found with id and
amount.
void set (int index, Item item, boolean refresh)
Sets the index to item.
final void set (Item[] toSet)
void setFiringEvents (boolean firingEvents)
Sets the value for firingEvents.
final void setItems (Item[] items)
final void setItems (Item[] items, boolean copy)
Sets the container of items to items.
void shift ()
Percolates the null indices to the end of the stack.
final int size ()
final Spliterator< Item > spliterator ()
final Stream< Item > stream ()
final void swap (boolean insert, int oldIndex, int newIndex, boolean refresh)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex, boolean refresh)
final Item[] toArray ()
Returns a shallow copy of the backing array.
final Item[] toNonNullArray ()
final void transfer (int firstIndex, int secondIndex, ItemContainer other, boolean refresh)
Private Member Functions
void refresh ()
Private Attributes
final Player player
The player instance.
Static Private Attributes
static final int DONATOR_DEPOSIT_BOX_DISPLAY_ID = 57207
Detailed Description
Handles the donator deposit box.
Author
Daniel
Definition at line 20 of file DonatorDeposit.java.
Constructor & Destructor Documentation
DonatorDeposit()
com.runehive.game.world.items.containers.bank.DonatorDeposit.DonatorDeposit (Player player)
Constructs a new DonatorDeposit.
Definition at line 30 of file DonatorDeposit.java.
{
        super(28, ItemContainer.StackPolicy.STANDARD);
        this.player = player;
    }
References com.runehive.game.world.items.containers.ItemContainer.ItemContainer(), and player.
Member Function Documentation
close()
void com.runehive.game.world.items.containers.bank.DonatorDeposit.close ()
Handles closing the donator deposit box.
Definition at line 47 of file DonatorDeposit.java.
{
        for (Item item : getItems()) {
            if (item == null)
                continue;
            if (remove(item))
                player.inventory.add(item);
        }
        clear(false);
        refresh();
        player.attributes.set("DONATOR_DEPOSIT_KEY", Boolean.FALSE);
    }
References com.runehive.game.world.items.containers.ItemContainer.clear(), com.runehive.game.world.items.containers.ItemContainer.getItems(), player, and refresh().
confirm()
void com.runehive.game.world.items.containers.bank.DonatorDeposit.confirm ()
Handles confirming the deposit.
Definition at line 60 of file DonatorDeposit.java.
{
        if (!player.interfaceManager.isInterfaceOpen(57200)) {
            return;
        }
        if (isEmpty()) {
            player.send(new SendMessage("There are no items to deposit!"));
            return;
        }
        if (player.bank.getFreeSlots() < this.size()) {
            player.message("You do not have enough space in your bank to deposit these items.");
            return;
        }
        player.send(new SendMessage("You have deposited " + this.size() + " items into your bank."));
        Arrays.stream(this.getItems()).filter(Objects::nonNull).forEach(item -> {
            if(player.bank.depositFromNothing(item, 0) > 0) {
                remove(item, -1, false);
            }
        });
        clear(false);
        refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.clear(), com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.items.containers.ItemContainer.isEmpty(), player, refresh(), and com.runehive.game.world.items.containers.ItemContainer.size().
deposit()
boolean com.runehive.game.world.items.containers.bank.DonatorDeposit.deposit (int id, int slot, int amount)
Handles deposting items into the container.
Definition at line 86 of file DonatorDeposit.java.
{
        if (!player.interfaceManager.isInterfaceOpen(57200)) {
            return false;
        }
        Item item = player.inventory.get(slot);
        if (item == null || item.getId() != id) {
            return false;
        }
        int contain = player.inventory.computeAmountForId(id);
        if (contain < amount) {
            amount = contain;
        }
        int allowedSize = PlayerRight.getDepositAmount(player);
        if (size() >= allowedSize) {
            player.dialogueFactory.sendStatement("You can only deposit up to " + allowedSize + " items.", "The higher your donator rank the more spaces unlocked!").execute();
            return false;
        }
        if(!add(item.getId(), amount)) {
            return false;
        }
        Item current = new Item(item.getId(), amount);
        if (item.isStackable() || amount == 1) {
            player.inventory.remove(current, slot, false);
        } else {
            player.inventory.remove(current, -1, false);
        }
        refresh();
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.PlayerRight.getDepositAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.isStackable(), player, refresh(), and com.runehive.game.world.items.containers.ItemContainer.size().
onRefresh()
void com.runehive.game.world.items.containers.bank.DonatorDeposit.onRefresh ()
Any functionality that should occur when refreshed.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 166 of file DonatorDeposit.java.
{
        player.inventory.refresh();
        player.send(new SendString(this.size() + "/" + this.capacity(), 57206));
        player.send(new SendItemOnInterface(InterfaceConstants.INVENTORY_STORE, player.inventory.toArray()));
    }
References com.runehive.game.world.items.containers.ItemContainer.capacity, com.runehive.game.world.InterfaceConstants.INVENTORY_STORE, player, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.items.containers.ItemContainer.size().
open()
void com.runehive.game.world.items.containers.bank.DonatorDeposit.open ()
Handles opening the donator deposit box.
Definition at line 36 of file DonatorDeposit.java.
                       {
        if (!PlayerRight.isDonator(player)) {
            player.dialogueFactory.sendStatement("You need to be a donator to use this feature!", "The donator deposit allows donators to deposit a certain amount", "of items into their banks every 2 minutes.").execute();
            return;
        }
        refresh();
        player.attributes.set("DONATOR_DEPOSIT_KEY", Boolean.TRUE);
        player.interfaceManager.openInventory(57200, 5063);
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.isDonator(), player, and refresh().
refresh()
void com.runehive.game.world.items.containers.bank.DonatorDeposit.refresh () private
Definition at line 161 of file DonatorDeposit.java.
{
        refresh(player, DONATOR_DEPOSIT_BOX_DISPLAY_ID);
    }
References DONATOR_DEPOSIT_BOX_DISPLAY_ID, player, and refresh().
Referenced by close(), confirm(), deposit(), open(), refresh(), and withdraw().
withdraw()
boolean com.runehive.game.world.items.containers.bank.DonatorDeposit.withdraw (int id, int slot, int amount)
Handles withdrawing items from the container.
Definition at line 126 of file DonatorDeposit.java.
{
        if (!player.interfaceManager.isInterfaceOpen(57200)) {
            return false;
        }
        Item item = get(slot);
        if (item == null || item.getId() != id) {
            return false;
        }
        int contain = computeAmountForId(id);
        if (contain < amount) {
            amount = contain;
        }
        Item current = new Item(id, amount);
        if(!player.inventory.add(current)) {
            return false;
        }
        if (item.isStackable() || amount == 1) {
            remove(current, slot, false);
        } else {
            remove(current, slot, false);
        }
        shift();
        refresh();
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.isStackable(), player, refresh(), and com.runehive.game.world.items.containers.ItemContainer.shift().
Member Data Documentation
DONATOR_DEPOSIT_BOX_DISPLAY_ID
final int com.runehive.game.world.items.containers.bank.DonatorDeposit.DONATOR_DEPOSIT_BOX_DISPLAY_ID = 57207 static private
Definition at line 22 of file DonatorDeposit.java.
Referenced by refresh().
player
final Player com.runehive.game.world.items.containers.bank.DonatorDeposit.player private
The player instance.
Definition at line 25 of file DonatorDeposit.java.
Referenced by close(), confirm(), deposit(), DonatorDeposit(), onRefresh(), open(), refresh(), and withdraw().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/bank/DonatorDeposit.java