RuneHive-Game: com.runehive.content.itemaction.impl.TanzaniteHelm Class Reference
com.runehive.content.itemaction.impl.TanzaniteHelm Class Reference
Public Member Functions
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
TanzaniteHelm ()
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
String message (Item item)
The message of the action.
String toString ()
Static Public Member Functions
static void check (Player player)
Static Private Member Functions
static void charge (Player player, Item helm, Item scales)
static void restore (Player player, Item item)
static void uncharge (Player player)
Static Private Attributes
static final short CHARGED_HELM = 13_197
static final DecimalFormat FORMATTER = new DecimalFormat("#.#")
static final short FULL = 11_000
static final short UNCHARGED_HELM = 13_196
static final short ZULRAH_SCALES = 12_934
Detailed Description
Definition at line 15 of file TanzaniteHelm.java.
Constructor & Destructor Documentation
TanzaniteHelm()
com.runehive.content.itemaction.impl.TanzaniteHelm.TanzaniteHelm ()
Definition at line 25 of file TanzaniteHelm.java.
{
        FORMATTER.setRoundingMode(RoundingMode.FLOOR);
    }
References FORMATTER.
Member Function Documentation
charge()
void com.runehive.content.itemaction.impl.TanzaniteHelm.charge (Player player, Item helm, Item scales) static private
Definition at line 83 of file TanzaniteHelm.java.
{
        if (player.tanzaniteHelmCharges >= FULL) {
            if (helm.matchesId(UNCHARGED_HELM)) {
                player.inventory.replace(UNCHARGED_HELM, CHARGED_HELM, true);
            }
            player.message("Your Tanzanite helm is already fully charged.");
            return;
        }
        if (Integer.MAX_VALUE - scales.getAmount() < FULL) {
            scales = scales.copy();
            scales.setAmount(FULL - player.tanzaniteHelmCharges);
        }
        if (player.tanzaniteHelmCharges + scales.getAmount() > FULL) {
            scales = scales.copy();
            scales.setAmount(FULL - player.tanzaniteHelmCharges);
        }
        player.tanzaniteHelmCharges += scales.getAmount();
        player.inventory.remove(scales);
        player.inventory.replace(UNCHARGED_HELM, CHARGED_HELM, true);
        player.message(String.format("You load %s scales into your Tanzanite helm.", Utility.formatDigits(scales.getAmount())));
    }
References CHARGED_HELM, com.runehive.game.world.items.Item.copy(), com.runehive.util.Utility.formatDigits(), FULL, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.Item.matchesId(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.items.Item.setAmount(), com.runehive.game.world.entity.mob.player.Player.tanzaniteHelmCharges, and UNCHARGED_HELM.
Referenced by itemOnItem().
check()
void com.runehive.content.itemaction.impl.TanzaniteHelm.check (Player player) static
Definition at line 78 of file TanzaniteHelm.java.
{
        String scales = FORMATTER.format(player.tanzaniteHelmCharges * 100 / FULL) + "%";
        player.message("Charges: <col=007F00>" + scales);
    }
References FORMATTER, FULL, com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.entity.mob.player.Player.tanzaniteHelmCharges.
Referenced by equipment(), and inventory().
drop()
boolean com.runehive.content.itemaction.impl.TanzaniteHelm.drop (Player player, Item item)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 70 of file TanzaniteHelm.java.
{
        if (item.matchesId(CHARGED_HELM)) {
            uncharge(player);
            return true;
        }
        return false;
    }
References CHARGED_HELM, com.runehive.game.world.items.Item.matchesId(), and uncharge().
equipment()
boolean com.runehive.content.itemaction.impl.TanzaniteHelm.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 62 of file TanzaniteHelm.java.
{
        if (opcode == 1) {
            check(player);
        }
        return true;
    }
References check().
inventory()
boolean com.runehive.content.itemaction.impl.TanzaniteHelm.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 51 of file TanzaniteHelm.java.
{
        if (opcode == 3) {
            restore(player, item);
        } else if (opcode == 2) {
            check(player);
        }
        return true;
    }
References check(), and restore().
itemOnItem()
boolean com.runehive.content.itemaction.impl.TanzaniteHelm.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 35 of file TanzaniteHelm.java.
{
        Item item = first;
        if (first.getId() == UNCHARGED_HELM || first.getId() == CHARGED_HELM) {
            item = second;
        }
        if (item.getId() == ZULRAH_SCALES) {
            charge(player, item.equals(first) ? second : first, item);
            return true;
        }
        return false;
    }
References charge(), CHARGED_HELM, com.runehive.game.world.items.Item.equals(), com.runehive.game.world.items.Item.getId(), UNCHARGED_HELM, and ZULRAH_SCALES.
name()
String com.runehive.content.itemaction.impl.TanzaniteHelm.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 30 of file TanzaniteHelm.java.
{
        return "Tanzanite Helm";
    }
restore()
void com.runehive.content.itemaction.impl.TanzaniteHelm.restore (Player player, Item item) static private
Definition at line 122 of file TanzaniteHelm.java.
{
        player.send(new SendItemOnInterfaceSlot(14171, item, 0));
        player.send(new SendString("Are you sure you want to restore this item?", 14174));
        player.send(new SendString("Yes.", 14175));
        player.send(new SendString("No.", 14176));
        player.send(new SendString("", 14177));
        player.send(new SendString("This will replace your helm with the original Serpentine helm.", 14182));
        player.send(new SendString("", 14183));
        player.send(new SendString(item.getName(), 14184));
        player.send(new SendChatBoxInterface(14170));
        player.attributes.set("RESTORE_HELM_KEY", item);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.util.generic.GenericAttributes.set().
Referenced by inventory().
uncharge()
void com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge (Player player) static private
Definition at line 108 of file TanzaniteHelm.java.
{
        Item scales = new Item(ZULRAH_SCALES, player.tanzaniteHelmCharges);
        if (!player.inventory.hasCapacityFor(scales)) {
            player.send(new SendMessage("You need more inventory space to do this."));
            return;
        }
        player.tanzaniteHelmCharges = 0;
        player.inventory.add(scales);
        player.inventory.replace(CHARGED_HELM, UNCHARGED_HELM, true);
        player.message(String.format("You uncharged your Tanzanite helm and received %s of Zulra's scales.", Utility.formatDigits(scales.getAmount())));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), CHARGED_HELM, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.Player.tanzaniteHelmCharges, UNCHARGED_HELM, and ZULRAH_SCALES.
Referenced by drop().
Member Data Documentation
CHARGED_HELM
final short com.runehive.content.itemaction.impl.TanzaniteHelm.CHARGED_HELM = 13_197 static private
Definition at line 21 of file TanzaniteHelm.java.
Referenced by charge(), drop(), itemOnItem(), and uncharge().
FORMATTER
final DecimalFormat com.runehive.content.itemaction.impl.TanzaniteHelm.FORMATTER = new DecimalFormat("#.#") static private
Definition at line 23 of file TanzaniteHelm.java.
Referenced by check(), and TanzaniteHelm().
FULL
final short com.runehive.content.itemaction.impl.TanzaniteHelm.FULL = 11_000 static private
Definition at line 16 of file TanzaniteHelm.java.
Referenced by charge(), and check().
UNCHARGED_HELM
final short com.runehive.content.itemaction.impl.TanzaniteHelm.UNCHARGED_HELM = 13_196 static private
Definition at line 20 of file TanzaniteHelm.java.
Referenced by charge(), itemOnItem(), and uncharge().
ZULRAH_SCALES
final short com.runehive.content.itemaction.impl.TanzaniteHelm.ZULRAH_SCALES = 12_934 static private
Definition at line 18 of file TanzaniteHelm.java.
Referenced by itemOnItem(), and uncharge().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/TanzaniteHelm.java