RuneHive-Game: com.runehive.game.world.entity.mob.Locking Class Reference
com.runehive.game.world.entity.mob.Locking Class Reference
Public Member Functions
LockType getLock ()
void lock ()
Locks the mob indefinitely.
void lock (int time)
void lock (int time, LockType type)
Locks the mob for a certain amount of time.
void lock (int time, TimeUnit gUnit, LockType type)
Locks the mob for a certain amount of time.
void lock (LockType type)
boolean locked ()
Checks if the mob is locked.
boolean locked (LockType type)
Checks if the mob is locked by a certain type.
boolean locked (PacketType packet)
boolean locked (PacketType packet, Object object)
void status ()
void unlock ()
Unlocks the mob.
Package Functions
Locking (Mob mob)
Private Attributes
LockType lock = null
long lockTime = -1
final Mob mob
Detailed Description
Definition at line 9 of file Locking.java.
Constructor & Destructor Documentation
Locking()
com.runehive.game.world.entity.mob.Locking.Locking (Mob mob) package
Definition at line 14 of file Locking.java.
                     {
        this.mob = mob;
    }
References mob.
Member Function Documentation
getLock()
LockType com.runehive.game.world.entity.mob.Locking.getLock ()
Definition at line 97 of file Locking.java.
{
        return lock;
    }
References lock.
lock() [1/5]
void com.runehive.game.world.entity.mob.Locking.lock ()
Locks the mob indefinitely.
Definition at line 19 of file Locking.java.
                       {
        lock(Integer.MAX_VALUE, LockType.MASTER);
    }
References lock, and com.runehive.game.world.entity.mob.data.LockType.MASTER.
lock() [2/5]
void com.runehive.game.world.entity.mob.Locking.lock (int time)
Definition at line 23 of file Locking.java.
{
        lock(time, LockType.MASTER);
    }
References lock, and com.runehive.game.world.entity.mob.data.LockType.MASTER.
lock() [3/5]
void com.runehive.game.world.entity.mob.Locking.lock (int time, LockType type)
Locks the mob for a certain amount of time.
Definition at line 32 of file Locking.java.
{
        lock(time, TimeUnit.SECONDS, type);
    }
References lock.
lock() [4/5]
void com.runehive.game.world.entity.mob.Locking.lock (int time, TimeUnit gUnit, LockType type)
Locks the mob for a certain amount of time.
Definition at line 37 of file Locking.java.
{
        long start = System.currentTimeMillis();
        long timer = TimeUnit.MILLISECONDS.convert(time, gUnit);
        if (Long.MAX_VALUE - start <= timer)
            timer = (Long.MAX_VALUE - start);
        if (type.execute(mob, time, gUnit)) {
            mob.movement.reset();
            lock = type;
            lockTime = start + timer;
        }
    }
References com.runehive.game.world.entity.mob.data.LockType.execute(), lock, lockTime, and mob.
lock() [5/5]
void com.runehive.game.world.entity.mob.Locking.lock (LockType type)
Definition at line 27 of file Locking.java.
{
        lock(Integer.MAX_VALUE, type);
    }
References lock.
locked() [1/4]
boolean com.runehive.game.world.entity.mob.Locking.locked ()
Checks if the mob is locked.
Definition at line 52 of file Locking.java.
{
        if (mob.isDead())
            return true;
        boolean state = lock != null && lockTime - System.currentTimeMillis() >= 0;
        if (!state) unlock();
        return state;
    }
References lock, lockTime, mob, and unlock().
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.attack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.canAttack(), com.runehive.game.plugin.extension.CommandExtension.canExecute(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.dragonFireTickableTask(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.net.packet.in.ChatMessagePacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handlePacket(), com.runehive.net.packet.in.KeyPacketListener.handlePacket(), com.runehive.net.packet.in.PickupItemPacketListener.handlePacket(), com.runehive.net.packet.in.UseItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), locked(), locked(), locked(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.start(), status(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
locked() [2/4]
boolean com.runehive.game.world.entity.mob.Locking.locked (LockType type)
Checks if the mob is locked by a certain type.
Definition at line 78 of file Locking.java.
{
        return locked() && lock == type;
    }
References lock, and locked().
locked() [3/4]
boolean com.runehive.game.world.entity.mob.Locking.locked (PacketType packet)
Definition at line 82 of file Locking.java.
{
        return locked() && lock.isLocked(packet);
    }
References lock, and locked().
locked() [4/4]
boolean com.runehive.game.world.entity.mob.Locking.locked (PacketType packet, Object object)
Definition at line 86 of file Locking.java.
{
        return locked() && lock.isLocked(packet, mob, object);
    }
References lock, locked(), and mob.
status()
void com.runehive.game.world.entity.mob.Locking.status ()
Definition at line 60 of file Locking.java.
{
        System.out.println();
        System.out.println("Lock Status");
        System.out.println("Locked: " + locked(LockType.WALKING));
        System.out.println("Lock Time: " + lockTime);
        System.out.println("Lock: " + lock);
        if (lock == null) {
            System.out.println("Lock Packet: null");
        } else {
            System.out.println("Lock Packet: ");
            Arrays.stream(lock.packets).forEach(System.out::println);
        }
        System.out.println();
    }
References lock, locked(), lockTime, and com.runehive.game.world.entity.mob.data.LockType.WALKING.
unlock()
void com.runehive.game.world.entity.mob.Locking.unlock ()
Unlocks the mob.
Definition at line 91 of file Locking.java.
{
        lock = null;
        lockTime = 0;
        mob.freezeImmunity.reset();
    }
References lock, lockTime, and mob.
Referenced by com.runehive.content.emote.Emote.execute(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), locked(), com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.content.emote.Emote.skillcape(), com.runehive.content.activity.inferno.Inferno.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), and com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse().
Member Data Documentation
lock
LockType com.runehive.game.world.entity.mob.Locking.lock = null private
Definition at line 11 of file Locking.java.
Referenced by com.runehive.content.activity.impl.kraken.KrakenActivity.add(), com.runehive.game.world.entity.combat.strategy.player.special.melee.ZamorakGodsword.attack(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.emote.Emote.execute(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.game.world.entity.combat.magic.MagicImpact.freeze(), getLock(), com.runehive.content.ai.AIDialogueHandler.handleAICommand(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), lock(), lock(), lock(), lock(), lock(), locked(), locked(), locked(), locked(), com.runehive.content.StarterKit.open(), com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.content.emote.Emote.skillcape(), status(), and unlock().
lockTime
long com.runehive.game.world.entity.mob.Locking.lockTime = -1 private
Definition at line 12 of file Locking.java.
Referenced by lock(), locked(), status(), and unlock().
mob
final Mob com.runehive.game.world.entity.mob.Locking.mob private
Definition at line 10 of file Locking.java.
Referenced by lock(), locked(), locked(), Locking(), and unlock().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/Locking.java