RuneHive-Game: com.runehive.content.skill.impl.woodcutting.BirdsNest Class Reference
com.runehive.content.skill.impl.woodcutting.BirdsNest Class Reference
Handles dropping & searching birds nest which are obtained from woodcutting.
Static Public Member Functions
static void drop (Player player)
Handles dropping the birds nest.
static void search (Player player, int item)
Handles searching a birds nest.
Static Private Attributes
static final int[] BIRD_NEST = {5070, 5071, 5072, 5073, 5074}
Identification of all bird nest items.
static final int[] RING_REWARD = {1635, 1637, 1639, 1641, 1643}
Identification of all rings obtainable from birds nest.
static final int[] SEED_REWARD = {5312, 5313, 5314, 5315, 5316, 5283, 5284, 5285, 5286, 5287, 5288, 5289, 5290, 5317}
Identification of all seeds obtainable from birds nest.
Detailed Description
Handles dropping & searching birds nest which are obtained from woodcutting.
Author
Daniel
Definition at line 17 of file BirdsNest.java.
Member Function Documentation
drop()
void com.runehive.content.skill.impl.woodcutting.BirdsNest.drop (Player player) static
Handles dropping the birds nest.
Definition at line 29 of file BirdsNest.java.
{
        int chance = player.prestige.hasPerk(PrestigePerk.LITTLE_BIRDY) ? 10 : 5;
        if (Utility.random(1, 200) < chance) {
            Item item = new Item(Utility.randomElement(BIRD_NEST), 1);
            GroundItem.create(player, item);
            player.send(new SendMessage("A bird's nest falls out of the tree.", MessageColor.RED));
        }
    }
References BIRD_NEST, com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.content.prestige.Prestige.hasPerk(), com.runehive.content.prestige.PrestigePerk.LITTLE_BIRDY, com.runehive.game.world.entity.mob.player.Player.prestige, com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), com.runehive.util.MessageColor.RED, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
search()
void com.runehive.content.skill.impl.woodcutting.BirdsNest.search (Player player, int item) static
Handles searching a birds nest.
Definition at line 39 of file BirdsNest.java.
{
        if (player.inventory.remaining() == 0) {
            player.send(new SendMessage("You do not have enough inventory space to do this."));
            return;
        }
        int reward = 0;
        if (item == 5074)
            reward = Utility.randomElement(RING_REWARD);
        else if (item == 5073)
            reward = Utility.randomElement(SEED_REWARD);
        else if (item == 5070)
            reward = 5076;
        else if (item == 5071)
            reward = 5077;
        else if (item == 5072)
            reward = 5078;
        Item rewardItem = new Item(reward, 1);
        String name = rewardItem.getName();
        player.send(new SendMessage("You search the nest... and find " + Utility.getAOrAn(name) + " " + name + "."));
        player.inventory.replace(item, 5075, true);
        player.inventory.add(rewardItem);
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.util.Utility.randomElement(), com.runehive.game.world.items.containers.ItemContainer.remaining(), com.runehive.game.world.items.containers.ItemContainer.replace(), RING_REWARD, SEED_REWARD, and com.runehive.game.world.entity.mob.player.Player.send().
Member Data Documentation
BIRD_NEST
final int [] com.runehive.content.skill.impl.woodcutting.BirdsNest.BIRD_NEST = {5070, 5071, 5072, 5073, 5074} static private
Identification of all bird nest items.
Definition at line 20 of file BirdsNest.java.
{5070, 5071, 5072, 5073, 5074};
Referenced by drop().
RING_REWARD
final int [] com.runehive.content.skill.impl.woodcutting.BirdsNest.RING_REWARD = {1635, 1637, 1639, 1641, 1643} static private
Identification of all rings obtainable from birds nest.
Definition at line 26 of file BirdsNest.java.
{1635, 1637, 1639, 1641, 1643};
Referenced by search().
SEED_REWARD
final int [] com.runehive.content.skill.impl.woodcutting.BirdsNest.SEED_REWARD = {5312, 5313, 5314, 5315, 5316, 5283, 5284, 5285, 5286, 5287, 5288, 5289, 5290, 5317} static private
Identification of all seeds obtainable from birds nest.
Definition at line 23 of file BirdsNest.java.
{5312, 5313, 5314, 5315, 5316, 5283, 5284, 5285, 5286, 5287, 5288, 5289, 5290, 5317};
Referenced by search().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/woodcutting/BirdsNest.java