RuneHive-Game: com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses Class Reference
com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses Class Reference
Static Public Member Functions
static String getTimeLeft (PlayerBirdHouseData playerBirdHouseData)
static void receiveLoot (Player player, PlayerBirdHouseData birdHouseData)
Static Package Attributes
static long DAY = HOUR * 24
static long HOUR = MINUTE * 60
static long MINUTE = SECOND * 60
static long SECOND = 1000
Static Private Member Functions
static boolean wasSuccesful (Player player, int skill, int low, int high)
Detailed Description
Definition at line 18 of file Birdhouses.java.
Member Function Documentation
getTimeLeft()
String com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.getTimeLeft (PlayerBirdHouseData playerBirdHouseData) static
Definition at line 24 of file Birdhouses.java.
{
        long left = playerBirdHouseData.birdhouseTimer - System.currentTimeMillis();
        long minutes = left / MINUTE;
        return minutes < 0 ? "rougly 1 minute." : minutes + " minute(s).";
    }
References MINUTE.
receiveLoot()
void com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot (Player player, PlayerBirdHouseData birdHouseData) static
Definition at line 30 of file Birdhouses.java.
{
        player.send(new SendRemoveInterface());
        if(player.inventory.getFreeSlots() < 2) {
            player.message("You must have two spaces in your inventory to dismantle the birdhouse.");
            return;
        }
        ArrayList<Item> receivedItems = new ArrayList<>();
        player.animate(827);
        player.inventory.addOrDrop(new Item(8792));
        receivedItems.add(new Item(8792));
        for(int index = 0; index < 10; index++) {
            GroundItem.create(player, new Item(9978));
            receivedItems.add(new Item(9978));
        }
        int[] featerAmount = { 30, 40, 50, 60 };
        int featherAmount = featerAmount[Utility.random(featerAmount.length - 1)];
        player.inventory.addOrDrop(new Item(314, featherAmount));
        receivedItems.add(new Item(314, featherAmount));
        int nestsReceived = 0;
        player.inventory.addOrDrop(new Item(5073));
        receivedItems.add(new Item(5073));
        if(wasSuccesful(player, SkillData.HUNTER.ordinal(), 0, 200)) {
            player.inventory.addOrDrop(new Item(5073));
            receivedItems.add(new Item(5073));
            nestsReceived++;
        }
        for(int index = 0; index < 10; index++) {
            int hunterLevel = player.skills.getLevel(SkillData.HUNTER.ordinal());
            if(hunterLevel < 50)
                hunterLevel = 50;
            int nestRate = birdHouseData.birdhouseData.succesRates * (hunterLevel - 1) / 98;
            int randomRoll = Utility.random(1000);
            if(randomRoll < nestRate) {
                int nestChance = 100;
                if(player.equipment.contains(10134))
                    nestChance = 95;
                int nestRoll = Utility.random(nestChance);
                if(nestRoll < 1) {
                    player.inventory.addOrDrop(new Item(5072));
                    receivedItems.add(new Item(5072));
                    nestsReceived++;
                }
                else if(nestRoll < 2) {
                    player.inventory.addOrDrop(new Item(5070));
                    receivedItems.add(new Item(5070));
                    nestsReceived++;
                } else if(nestRoll < 3) {
                    player.inventory.addOrDrop(new Item(5071));
                    receivedItems.add(new Item(5071));
                    nestsReceived++;
                } else if(nestRoll < 35) {
                    player.inventory.addOrDrop(new Item(5074));
                    receivedItems.add(new Item(5074));
                    nestsReceived++;
                } else {
                    player.inventory.addOrDrop(new Item(5075));
                    receivedItems.add(new Item(5075));
                    nestsReceived++;
                }
            }
        }
        player.inventory.refresh();
        player.message("You dismantle and discard the trap, retrieving "+nestsReceived+" nest"+(nestsReceived > 1 ? "s" : "")+", 10 dead birds, "+featherAmount+" feathers and "+birdHouseData.birdhouseData.hunterData[1]+" Hunter XP.");
        player.skills.addExperience(SkillData.HUNTER.ordinal(), birdHouseData.birdhouseData.hunterData[1]);
        player.send(new SendAddObject(new CustomGameObject(birdHouseData.oldObjectId, birdHouseData.birdhousePosition, ObjectDirection.valueOf(birdHouseData.rotation).get(), ObjectType.valueOf(birdHouseData.type).get())));
        player.birdHouseData.remove(birdHouseData);
        PlayerSerializer.save(player);
    }
References com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.player.Player.birdHouseData, com.runehive.content.skill.impl.hunter.birdhouse.PlayerBirdHouseData.birdhouseData, com.runehive.content.skill.impl.hunter.birdhouse.PlayerBirdHouseData.birdhousePosition, com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.SkillData.HUNTER, com.runehive.content.skill.impl.hunter.birdhouse.BirdhouseData.hunterData, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.skill.impl.hunter.birdhouse.PlayerBirdHouseData.oldObjectId, com.runehive.util.Utility.random(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.content.skill.impl.hunter.birdhouse.PlayerBirdHouseData.rotation, com.runehive.game.world.entity.mob.player.persist.PlayerSerializer.save(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.content.skill.impl.hunter.birdhouse.PlayerBirdHouseData.type, com.runehive.game.world.object.ObjectDirection.valueOf(), com.runehive.game.world.object.ObjectType.valueOf(), and wasSuccesful().
wasSuccesful()
boolean com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.wasSuccesful (Player player, int skill, int low, int high) static private
Definition at line 114 of file Birdhouses.java.
{
        int level = player.skills.getLevel(skill);
        int odds = 1 + (low * (99 - level) / 98) + (high * (level - 1) / 98);
        double percent = ((double)odds / 256D) * 100D;
        int random = new Random().nextInt(256);
        return odds >= random;
    }
References com.runehive.game.world.entity.skill.SkillManager.getLevel(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by receiveLoot().
Member Data Documentation
DAY
long com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.DAY = HOUR * 24 static package
Definition at line 22 of file Birdhouses.java.
HOUR
long com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.HOUR = MINUTE * 60 static package
Definition at line 21 of file Birdhouses.java.
MINUTE
long com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.MINUTE = SECOND * 60 static package
Definition at line 20 of file Birdhouses.java.
Referenced by getTimeLeft().
SECOND
long com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.SECOND = 1000 static package
Definition at line 19 of file Birdhouses.java.
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/hunter/birdhouse/Birdhouses.java