RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy Class Reference
com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy Class Reference
Public Member Functions
void attack (Player attacker, Mob defender, Hit hit)
boolean canAttack (Player attacker, Mob defender)
Animation getAttackAnimation (Player attacker, Mob defender)
int getAttackDelay (Player attacker, Mob defender, FightType fightType)
int getAttackDistance (Player attacker, FightType fightType)
CombatType getCombatType ()
CombatHit[] getHits (Player attacker, Mob defender)
void start (Player attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static ScytheOfViturStrategy get ()
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Private Member Functions
void hitEvent (Player attacker, Mob defender, Mob other)
Static Private Attributes
static final Animation ANIMATION = new Animation(8056, UpdatePriority.HIGH)
static final Graphic GRAPHIC = new Graphic(506)
static final ScytheOfViturStrategy INSTANCE = new ScytheOfViturStrategy()
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Definition at line 18 of file ScytheOfViturStrategy.java.
Member Function Documentation
attack()
void com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.attack (Player attacker, Mob defender, Hit hit)
Definition at line 47 of file ScytheOfViturStrategy.java.
{ }
References com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.hit().
canAttack()
boolean com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.canAttack (Player attacker, Mob defender)
Definition at line 26 of file ScytheOfViturStrategy.java.
{
        Item weapon = attacker.equipment.get(Equipment.WEAPON_SLOT);
        if (weapon == null) {
            attacker.getCombat().reset();
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
get()
ScytheOfViturStrategy com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.get () static
Definition at line 74 of file ScytheOfViturStrategy.java.
{
        return INSTANCE;
    }
References INSTANCE.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.getStrategy().
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.getAttackAnimation (Player attacker, Mob defender)
Definition at line 50 of file ScytheOfViturStrategy.java.
{
        return ANIMATION;
    }
References ANIMATION.
getAttackDelay()
int com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.getAttackDelay (Player attacker, Mob defender, FightType fightType)
Definition at line 70 of file ScytheOfViturStrategy.java.
{
        return attacker.getCombat().getFightType().getDelay();
    }
References com.runehive.game.world.entity.mob.player.Player.getCombat().
getAttackDistance()
int com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.getAttackDistance (Player attacker, FightType fightType)
Definition at line 60 of file ScytheOfViturStrategy.java.
{
        return 1;
    }
getCombatType()
CombatType com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.getCombatType ()
Reimplemented from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
Definition at line 55 of file ScytheOfViturStrategy.java.
{
        return CombatType.MELEE;
    }
References com.runehive.game.world.entity.combat.CombatType.MELEE.
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.getHits (Player attacker, Mob defender)
Definition at line 65 of file ScytheOfViturStrategy.java.
{
        return new CombatHit[]{ nextMeleeHit(attacker, defender) };
    }
References com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit().
hitEvent()
void com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.hitEvent (Player attacker, Mob defender, Mob other) private
Definition at line 78 of file ScytheOfViturStrategy.java.
{
        if (!CombatUtil.canBasicAttack(attacker, other)) {
            return;
        }
        if (attacker.equals(other) || defender.equals(other)) {
            return;
        }
        if(!Position.isWithinDiagonalDistance(attacker, other, 1) || defender.getPosition().equals(other.getPosition())) {
            return;
        }
        CombatHit hit = nextMeleeHit(attacker, other);
        other.damage(hit);
        other.getCombat().attack(attacker);
    }
References com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.mob.Mob.damage(), com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.mob.player.Player.equals(), com.runehive.game.world.position.Position.equals(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.hit(), com.runehive.game.world.position.Position.isWithinDiagonalDistance(), and com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit().
Referenced by start().
start()
void com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.start (Player attacker, Mob defender, Hit[] hits)
Definition at line 38 of file ScytheOfViturStrategy.java.
{
        super.start(attacker, defender, hits);
        attacker.animate(ANIMATION, true);
        CombatUtil.areaAction(attacker, 3, 1, other -> hitEvent(attacker, defender, other));
        //attacker.graphic(GRAPHIC);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), ANIMATION, com.runehive.game.world.entity.combat.CombatUtil.areaAction(), and hitEvent().
Member Data Documentation
ANIMATION
final Animation com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.ANIMATION = new Animation(8056, UpdatePriority.HIGH) static private
Definition at line 22 of file ScytheOfViturStrategy.java.
Referenced by getAttackAnimation(), and start().
GRAPHIC
final Graphic com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.GRAPHIC = new Graphic(506) static private
Definition at line 23 of file ScytheOfViturStrategy.java.
INSTANCE
final ScytheOfViturStrategy com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.INSTANCE = new ScytheOfViturStrategy() static private
Definition at line 20 of file ScytheOfViturStrategy.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/custom/ScytheOfViturStrategy.java