RuneHive-Game: com.runehive.net.packet.in.ItemOptionPacketListener Class Reference
com.runehive.net.packet.in.ItemOptionPacketListener Class Reference
The GamePacket responsible for clicking the actions of an
Item.
Public Member Functions
void handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Static Private Member Functions
static void handleFirstOption (Player player, GamePacket packet)
static void handleSecondOption (Player player, GamePacket packet)
static void handleThirdOption (Player player, GamePacket packet)
Detailed Description
The GamePacket responsible for clicking the actions of an
Item.
Author
Daniel | Obey
Definition at line 29 of file ItemOptionPacketListener.java.
Member Function Documentation
handleFirstOption()
void com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption (Player player, GamePacket packet) static private
Definition at line 60 of file ItemOptionPacketListener.java.
{
        final int interfaceId = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        final int slot = packet.readShort(false, ByteModification.ADD);
        final int id = packet.readShort(ByteOrder.LE);
        switch (interfaceId) {
            case 57716:
                player.forClan(channel -> channel.getShowcase().select(player, id, slot));
                break;
            case InterfaceConstants.INVENTORY_INTERFACE:
                final Item item = player.inventory.get(slot);
                if (item == null || item.getId() != id) {
                    return;
                }
                if (EventDispatcher.execute(player, new FirstItemClickInteractionEvent(item, slot))) {
                    return;
                }
                if (ItemActionRepository.inventory(player, item, 1)) {
                    return;
                }
                if (player.mysteryBox.click(item)) {
                    return;
                }
                PluginManager.getDataBus().publish(player, new ItemClickEvent(1, item, slot));
                break;
        }
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.mysterybox.MysteryBoxManager.click(), com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.world.entity.mob.player.Player.forClan(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.game.world.items.Item.getId(), com.runehive.content.itemaction.ItemActionRepository.inventory(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.InterfaceConstants.INVENTORY_INTERFACE, com.runehive.net.codec.ByteOrder.LE, com.runehive.game.world.entity.mob.player.Player.mysteryBox, and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
handlePacket()
void com.runehive.net.packet.in.ItemOptionPacketListener.handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Parameters
player The player receiving this packet.
packet The packet that has been received.
Implements com.runehive.net.packet.PacketListener.
Definition at line 32 of file ItemOptionPacketListener.java.
{
        checkState(player != null, "Player does not exist.");
        if (player.locking.locked(PacketType.CLICK_ITEM)) {
            return;
        }
        if (player.isDead()) {
            return;
        }
        switch (packet.getOpcode()) {
            case FIRST_ITEM_OPTION:
                handleFirstOption(player, packet);
                break;
            case SECOND_ITEM_OPTION:
                handleSecondOption(player, packet);
                break;
            case THIRD_ITEM_OPTION:
                handleThirdOption(player, packet);
                break;
        }
    }
References com.runehive.game.world.entity.mob.data.PacketType.CLICK_ITEM, handleFirstOption(), handleSecondOption(), handleThirdOption(), com.runehive.game.world.entity.mob.Mob.isDead(), com.runehive.game.world.entity.mob.Locking.locked(), and com.runehive.game.world.entity.mob.Mob.locking.
handleSecondOption()
void com.runehive.net.packet.in.ItemOptionPacketListener.handleSecondOption (Player player, GamePacket packet) static private
Definition at line 93 of file ItemOptionPacketListener.java.
{
        final int itemId = packet.readShort(ByteModification.ADD);
        final int slot = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        final int interfaceId = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        switch (interfaceId) {
            case InterfaceConstants.INVENTORY_INTERFACE:
                final Item item = player.inventory.get(slot);
                if (item == null || item.getId() != itemId) {
                    return;
                }
                if (EventDispatcher.execute(player, new SecondItemClickInteractionEvent(item, slot))) {
                    return;
                }
                if (ItemActionRepository.inventory(player, item, 2)) {
                    return;
                }
                PluginManager.getDataBus().publish(player, new ItemClickEvent(2, item, slot));
                break;
        }
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.game.world.items.Item.getId(), com.runehive.content.itemaction.ItemActionRepository.inventory(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.InterfaceConstants.INVENTORY_INTERFACE, com.runehive.net.codec.ByteOrder.LE, and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
handleThirdOption()
void com.runehive.net.packet.in.ItemOptionPacketListener.handleThirdOption (Player player, GamePacket packet) static private
Definition at line 119 of file ItemOptionPacketListener.java.
{
        final int interfaceId = packet.readShort(ByteOrder.LE, ByteModification.ADD);
        final int slot = packet.readShort(ByteOrder.LE);
        final int itemId = packet.readShort(ByteModification.ADD);
        switch (interfaceId) {
            case InterfaceConstants.INVENTORY_INTERFACE:
                Item item = player.inventory.get(slot);
                if (item == null || item.getId() != itemId) {
                    return;
                }
                if (EventDispatcher.execute(player, new ThirdItemClickInteractionEvent(item, slot))) {
                    return;
                }
                if (ItemActionRepository.inventory(player, item, 3)) {
                    return;
                }
                PluginManager.getDataBus().publish(player, new ItemClickEvent(3, item, slot));
                break;
        }
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.plugin.PluginManager.getDataBus(), com.runehive.game.world.items.Item.getId(), com.runehive.content.itemaction.ItemActionRepository.inventory(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.InterfaceConstants.INVENTORY_INTERFACE, com.runehive.net.codec.ByteOrder.LE, and com.runehive.game.event.bus.PlayerDataBus.publish().
Referenced by handlePacket().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/in/ItemOptionPacketListener.java