RuneHive-Game: com.runehive.content.overrides.Overrides Class Reference
com.runehive.content.overrides.Overrides Class Reference
Public Member Functions
void addOverride (int itemId)
Item get (int slot)
FightType getFightType (Item item)
boolean handleButtons (int button)
boolean hasOverride (int slot)
void openInterface ()
record OverridePreset (Item... items)
Overrides (Player player)
void removeOverride (int itemId)
Public Attributes
List< Integer > allOverrides = new ArrayList<>()
Map< Integer, Item > currentOverrides = new HashMap<>()
Map< String, OverridePreset > presets = new HashMap<>()
Package Attributes
final int AMULET_CONTAINER = 60133
final int AMULET_SLOT_BTN = -5413
final int BODY_CONTAINER = 60135
final int BODY_SLOT_BTN = -5410
final int BOOTS_CONTAINER = 60139
final int BOOTS_SLOT_BTN = -5407
final Map< Integer, Integer > buttons = new HashMap<>()
final int CAPE_CONTAINER = 60132
final int CAPE_SLOT_BTN = -5414
EquipmentType filter = EquipmentType.NOT_WIELDABLE
String filterName = "All"
final int GLOVES_CONTAINER = 60138
final int GLOVES_SLOT_BTN = -5406
final int HEAD_CONTAINER = 60131
final int HEAD_SLOT_BTN = -5415
final int INFO_BTN = -5286
final int INFO_CLOSE_BTN = -5270
final int INFO_GO_BACK_BTN = -5267
final int INFO_INTERFACE = 60260
final int LEGS_CONTAINER = 60137
final int LEGS_SLOT_BTN = -5408
final int MANAGE_BTN = -5395
boolean managingOverrides = false
final int OPEN_OVERRIDE_BTN = 27659
final int OVERRIDE_INTERFACE = 60106
final Map< Integer, String > presetButtons = new HashMap<>()
final int SAVE_PRESET_BTN = -5422
final int SHIELD_CONTAINER = 60136
final int SHIELD_SLOT_BTN = -5409
final int VIEW_ALL_BTN = -5428
final int VIEW_PRESET_BTN = -5417
final int WEAPON_CONTAINER = 60134
final int WEAPON_SLOT_BTN = -5411
Private Member Functions
void createPreset (String presetName)
void deleteOverride (Item item)
void deletePreset (String presetName)
int determineContainer (int itemId)
void drawPresets ()
void drawText ()
void equipOverride (Item item)
boolean hasShieldOverride ()
boolean hasWeaponOverride ()
void loadContainers ()
void loadPreset (String presetName)
void manageItemDialogue (Item item)
void manageModeDialogue ()
void managePresetDialogue (String presetName)
void removeAllOverrides ()
void renamePreset (String currentName, String newName)
void setFilter (EquipmentType equipmentType, String name)
SendConfig toggleConfig (int itemId, String toggle)
void wipeInterface ()
Private Attributes
final Player player
Detailed Description
Definition at line 16 of file Overrides.java.
Constructor & Destructor Documentation
Overrides()
com.runehive.content.overrides.Overrides.Overrides (Player player)
Definition at line 19 of file Overrides.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
addOverride()
void com.runehive.content.overrides.Overrides.addOverride (int itemId)
Definition at line 87 of file Overrides.java.
{
        final var item = new Item(itemId);
        final var canEquipItem = item.isEquipable();
        if (!canEquipItem) {
            player.dialogueFactory.sendItem("Keepsake Overrides", "You can only keepsake equipable items.", itemId).execute();
            return;
        }
        final var unallowedSlot = item.getEquipmentType() == EquipmentType.RING || item.getEquipmentType() == EquipmentType.ARROWS;
        if (unallowedSlot) {
            player.dialogueFactory.sendItem("Keepsake Overrides", "You cannot keepsake this item.", itemId).execute();
            return;
        }
        if (allOverrides.contains(itemId)) {
            player.dialogueFactory.sendItem("Keepsake Overrides", "You already have this as an override.", itemId).execute();
            return;
        }
        if (allOverrides.size() > 44) {
            player.dialogueFactory.sendItem("Keepsake Overrides", "You can only have 45 overrides.", itemId).execute();
            return;
        }
        if (Area.inWilderness(player)) {
            player.message("You can't do this in the wilderness.");
            return;
        }
        player.dialogueFactory.sendStatement(
                "Are you sure you want to keepsake the " + item.getName() + "?", "You will @red@not@bla@ be able to reclaim it.").sendOption(
                "Yes, keepsake the " + item.getName(), () -> {
                    allOverrides.add(itemId);
                    player.inventory.remove(2399, 1);
                    player.inventory.remove(itemId, 1);
                },
                "Nevermind", () -> player.dialogueFactory.clear()).execute();
    }
References allOverrides, com.runehive.game.world.items.containers.equipment.EquipmentType.ARROWS, com.runehive.game.world.position.Area.inWilderness(), player, and com.runehive.game.world.items.containers.equipment.EquipmentType.RING.
createPreset()
void com.runehive.content.overrides.Overrides.createPreset (String presetName) private
Definition at line 232 of file Overrides.java.
{
        if (presets.containsKey(presetName)) {
            player.message("You already have a preset named " + presetName + ".");
            return;
        }
        Item[] presetItems = new Item[11];
        currentOverrides.forEach((k, v) -> presetItems[k] = v);
        presets.put(presetName, new OverridePreset(presetItems));
        drawText();
    }
References currentOverrides, drawText(), OverridePreset(), player, and presets.
deleteOverride()
void com.runehive.content.overrides.Overrides.deleteOverride (Item item) private
Definition at line 122 of file Overrides.java.
{
        if (!allOverrides.contains(item.getId())) {
            player.message("Error deleting override.");
            return;
        }
        allOverrides.remove(Integer.valueOf(item.getId()));
        //Remove override if it is currently equipped
        if (currentOverrides.containsValue(item)) {
            removeOverride(item.getId());
        }
        //Remove preset if it contains the deleted override
        for (int i = 0; i < presets.size(); i++) {
            final var preset = presets.get(presets.keySet().toArray()[i].toString());
            if (Arrays.stream(preset.items).anyMatch(presetItem -> presetItem != null && presetItem.getId() == item.getId())) {
                presets.remove(presets.keySet().toArray()[i].toString());
                player.message("A preset has been deleted as it contained a deleted override.");
            }
        }
        drawText();
    }
References allOverrides, currentOverrides, drawText(), com.runehive.game.world.items.Item.getId(), player, presets, and removeOverride().
Referenced by manageItemDialogue().
deletePreset()
void com.runehive.content.overrides.Overrides.deletePreset (String presetName) private
Definition at line 276 of file Overrides.java.
{
        if (!presets.containsKey(presetName)) {
            player.message("Error deleting preset: " + presetName);
            return;
        }
        presets.remove(presetName);
        player.message("Preset deleted.");
        drawText();
    }
References drawText(), player, and presets.
Referenced by managePresetDialogue().
determineContainer()
int com.runehive.content.overrides.Overrides.determineContainer (int itemId) private
Definition at line 474 of file Overrides.java.
{
        final var equipmentSlot = new Item(itemId).getDefinition().getEquipmentType();
        return switch (equipmentSlot) {
            case HAT, HELM, MASK, FACE -> HEAD_CONTAINER;
            case CAPE -> CAPE_CONTAINER;
            case AMULET -> AMULET_CONTAINER;
            case WEAPON -> WEAPON_CONTAINER;
            case BODY, TORSO -> BODY_CONTAINER;
            case SHIELD -> SHIELD_CONTAINER;
            case LEGS -> LEGS_CONTAINER;
            case GLOVES -> GLOVES_CONTAINER;
            case BOOTS -> BOOTS_CONTAINER;
            default -> -1;
        };
    }
References AMULET_CONTAINER, BODY_CONTAINER, BOOTS_CONTAINER, CAPE_CONTAINER, com.runehive.game.world.items.Item.getDefinition(), GLOVES_CONTAINER, HEAD_CONTAINER, LEGS_CONTAINER, SHIELD_CONTAINER, and WEAPON_CONTAINER.
Referenced by equipOverride(), loadContainers(), and removeOverride().
drawPresets()
void com.runehive.content.overrides.Overrides.drawPresets () private
Definition at line 71 of file Overrides.java.
{
        for (int i = 0; i < presets.size(); i++) {
            final var presetName = presets.keySet().toArray()[i].toString();
            player.send(new SendString(presetName, 60146 + (i * 2)));
            presetButtons.put(-5391 + (i * 2), presetName);
        }
    }
References player, presetButtons, and presets.
Referenced by drawText().
drawText()
void com.runehive.content.overrides.Overrides.drawText () private
Definition at line 48 of file Overrides.java.
{
        wipeInterface();
        player.send(new SendString(filterName + " Overrides", 60113));
        if (filterName.equals("Preset")) {
            drawPresets();
            return;
        }
        int slot = 0;
        for (int i = 0; i < allOverrides.size(); i++) {
            final var equipmentSlot = new Item(allOverrides.get(i)).getDefinition().getEquipmentType().getNewItemDefName();
            if (!Objects.equals(equipmentSlot, filter.getNewItemDefName()) && filter != EquipmentType.NOT_WIELDABLE) {
                continue;
            }
            final var itemName = new Item(allOverrides.get(i)).getName();
            player.send(new SendString(itemName, 60146 + (slot * 2)));
            buttons.put(-5391 + (slot * 2), allOverrides.get(i));
            slot++;
        }
    }
References allOverrides, buttons, drawPresets(), filter, filterName, com.runehive.game.world.items.Item.getDefinition(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE, player, and wipeInterface().
Referenced by createPreset(), deleteOverride(), deletePreset(), openInterface(), renamePreset(), and setFilter().
equipOverride()
void com.runehive.content.overrides.Overrides.equipOverride (Item item) private
Definition at line 437 of file Overrides.java.
{
        player.send(toggleConfig(item.getId(), "off"));
        player.send(new SendItemOnInterface(determineContainer(item.getId()), item));
        final var equipmentType = item.getDefinition().getEquipmentType();
        currentOverrides.remove(equipmentType.getSlot());
        currentOverrides.put(equipmentType.getSlot(), item);
        player.updateFlags.add(UpdateFlag.APPEARANCE);
        player.equipment.updateAnimation();
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, currentOverrides, determineContainer(), com.runehive.game.world.items.Item.getDefinition(), com.runehive.game.world.items.Item.getId(), player, and toggleConfig().
Referenced by handleButtons(), loadPreset(), and manageItemDialogue().
get()
Item com.runehive.content.overrides.Overrides.get (int slot)
Definition at line 228 of file Overrides.java.
{
        return currentOverrides.get(slot);
    }
References currentOverrides.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation().
getFightType()
FightType com.runehive.content.overrides.Overrides.getFightType (Item item)
Definition at line 287 of file Overrides.java.
{
        WeaponInterface weapon = item == null ? null : item.getWeaponInterface();
        if (weapon == null) weapon = WeaponInterface.UNARMED;
        FightType[] oldTypes = player.getWeapon().getFightTypes();
        FightType[] newTypes = weapon.getFightTypes();
        FightType result = null;
        for (int index = 0; index < oldTypes.length; index++) {
            if (newTypes.length == index) {
                break;
            }
            if (newTypes[index].getStyle().equals(FightStyle.DEFENSIVE)
                    && player.getCombat().getFightType().getStyle().equals(FightStyle.DEFENSIVE)) {
                result = newTypes[index];
                break;
            }
            if (oldTypes[index] == player.getCombat().getFightType()) {
                boolean oldControlled = oldTypes[index].getStyle().equals(FightStyle.CONTROLLED);
                boolean newControlled = newTypes[index].getStyle().equals(FightStyle.CONTROLLED);
                if (newControlled != oldControlled) {
                    continue;
                }
                result = newTypes[index];
                break;
            }
        }
        if (result == null) {
            if (player.getCombat().getFightType().getStyle().equals(FightStyle.DEFENSIVE)) {
                result = newTypes[newTypes.length - 1];
            } else {
                result = newTypes[1];
            }
        }
        return result;
    }
References com.runehive.game.world.entity.combat.attack.FightStyle.CONTROLLED, com.runehive.game.world.entity.combat.attack.FightStyle.DEFENSIVE, com.runehive.game.world.entity.combat.weapon.WeaponInterface.getFightTypes(), com.runehive.game.world.entity.combat.attack.FightType.getStyle(), com.runehive.game.world.items.Item.getWeaponInterface(), player, and com.runehive.game.world.entity.combat.weapon.WeaponInterface.UNARMED.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation().
handleButtons()
boolean com.runehive.content.overrides.Overrides.handleButtons (int button)
Definition at line 327 of file Overrides.java.
{
        if (presetButtons.containsKey(button)) {
            final var presetName = presetButtons.get(button);
            if (managingOverrides) {
                managePresetDialogue(presetName);
                return true;
            }
            loadPreset(presetName);
            return true;
        }
        if (buttons.containsKey(button)) {
            final var item = new Item(buttons.get(button));
            if (managingOverrides) {
                manageItemDialogue(item);
                return true;
            }
            equipOverride(item);
            return true;
        }
        switch (button) {
            case INFO_BTN -> player.interfaceManager.open(INFO_INTERFACE);
            case INFO_CLOSE_BTN -> player.interfaceManager.close();
            case VIEW_ALL_BTN, INFO_GO_BACK_BTN, OPEN_OVERRIDE_BTN -> openInterface();
            case HEAD_SLOT_BTN -> setFilter(EquipmentType.HELM, "Head");
            case AMULET_SLOT_BTN -> setFilter(EquipmentType.AMULET, "Amulet");
            case BODY_SLOT_BTN -> setFilter(EquipmentType.BODY, "Body");
            case LEGS_SLOT_BTN -> setFilter(EquipmentType.LEGS, "Leg");
            case BOOTS_SLOT_BTN -> setFilter(EquipmentType.BOOTS, "Boot");
            case CAPE_SLOT_BTN -> setFilter(EquipmentType.CAPE, "Cape");
            case WEAPON_SLOT_BTN -> setFilter(EquipmentType.WEAPON, "Weapon");
            case GLOVES_SLOT_BTN -> setFilter(EquipmentType.GLOVES, "Glove");
            case SHIELD_SLOT_BTN -> setFilter(EquipmentType.SHIELD, "Shield");
            case VIEW_PRESET_BTN -> setFilter(EquipmentType.NOT_WIELDABLE, "Preset");
            case MANAGE_BTN -> manageModeDialogue();
            case SAVE_PRESET_BTN -> {
                if (presets.size() > 4) {
                    player.message("You already have the maximum amount of presets saved.");
                    return true;
                }
                player.send(new SendInputMessage("Enter name for preset:", 30, this::createPreset));
                return true;
            }
        }
        return false;
    }
References com.runehive.game.world.items.containers.equipment.EquipmentType.AMULET, AMULET_SLOT_BTN, com.runehive.game.world.items.containers.equipment.EquipmentType.BODY, BODY_SLOT_BTN, com.runehive.game.world.items.containers.equipment.EquipmentType.BOOTS, BOOTS_SLOT_BTN, buttons, com.runehive.game.world.items.containers.equipment.EquipmentType.CAPE, CAPE_SLOT_BTN, equipOverride(), com.runehive.game.world.items.containers.equipment.EquipmentType.GLOVES, GLOVES_SLOT_BTN, HEAD_SLOT_BTN, com.runehive.game.world.items.containers.equipment.EquipmentType.HELM, INFO_BTN, INFO_CLOSE_BTN, INFO_GO_BACK_BTN, INFO_INTERFACE, com.runehive.game.world.items.containers.equipment.EquipmentType.LEGS, LEGS_SLOT_BTN, loadPreset(), MANAGE_BTN, manageItemDialogue(), manageModeDialogue(), managePresetDialogue(), managingOverrides, com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE, OPEN_OVERRIDE_BTN, openInterface(), player, presetButtons, presets, SAVE_PRESET_BTN, setFilter(), com.runehive.game.world.items.containers.equipment.EquipmentType.SHIELD, SHIELD_SLOT_BTN, VIEW_ALL_BTN, VIEW_PRESET_BTN, com.runehive.game.world.items.containers.equipment.EquipmentType.WEAPON, and WEAPON_SLOT_BTN.
hasOverride()
boolean com.runehive.content.overrides.Overrides.hasOverride (int slot)
Definition at line 147 of file Overrides.java.
{
        if (Area.inWilderness(player)) {
            return false;
        }
        if (Area.inDuelArena(player)) {
            return false;
        }
        if (!currentOverrides.containsKey(slot)) {
            return false;
        }
        if (slot == Equipment.WEAPON_SLOT) {
            return hasWeaponOverride();
            /*if (player.equipment.get(Equipment.WEAPON_SLOT) != null) {
                final var wornWeapon = player.equipment.get(Equipment.WEAPON_SLOT).getRangedDefinition();
                final var overrideWeapon = currentOverrides.get(Equipment.WEAPON_SLOT).getRangedDefinition();
                return (wornWeapon.isPresent() || overrideWeapon.isEmpty()) && (overrideWeapon.isPresent() || wornWeapon.isEmpty());
            } else {
                return true;
            }*/
        }
        if (slot == Equipment.SHIELD_SLOT) {
            return hasShieldOverride();
           /* if (player.equipment.get(Equipment.WEAPON_SLOT) != null) {
                final var wornWeapon = player.equipment.get(Equipment.WEAPON_SLOT);
                if (currentOverrides.containsKey(Equipment.WEAPON_SLOT)) {
                    if (wornWeapon.getRangedDefinition().isPresent() && wornWeapon.isTwoHanded() && currentOverrides.get(Equipment.WEAPON_SLOT).getRangedDefinition().isEmpty()) {
                        return false;
                    }
                    return !currentOverrides.get(Equipment.WEAPON_SLOT).isTwoHanded();
                }
                return !wornWeapon.isTwoHanded();
            } else if (currentOverrides.containsKey(Equipment.WEAPON_SLOT)) {
                return !currentOverrides.get(Equipment.WEAPON_SLOT).isTwoHanded();
            } else {
                return true;
            }*/
        }
        return currentOverrides.containsKey(slot);
    }
References currentOverrides, hasShieldOverride(), hasWeaponOverride(), com.runehive.game.world.position.Area.inDuelArena(), com.runehive.game.world.position.Area.inWilderness(), player, com.runehive.game.world.items.containers.equipment.Equipment.SHIELD_SLOT, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation(), and hasWeaponOverride().
hasShieldOverride()
boolean com.runehive.content.overrides.Overrides.hasShieldOverride () private
Definition at line 211 of file Overrides.java.
{
        final var hasWeapon = player.equipment.get(Equipment.WEAPON_SLOT) != null;
        final var weaponIs2h = hasWeapon && player.equipment.get(Equipment.WEAPON_SLOT).isTwoHanded();
        final var hasOverrideWeapon = currentOverrides.containsKey(Equipment.WEAPON_SLOT);
        final var overrideIs2h = hasOverrideWeapon && currentOverrides.get(Equipment.WEAPON_SLOT).isTwoHanded();
        if (weaponIs2h) {
            return false;
        }
        if (overrideIs2h) {
            return false;
        }
        return currentOverrides.containsKey(Equipment.SHIELD_SLOT);
    }
References currentOverrides, player, com.runehive.game.world.items.containers.equipment.Equipment.SHIELD_SLOT, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by hasOverride().
hasWeaponOverride()
boolean com.runehive.content.overrides.Overrides.hasWeaponOverride () private
Definition at line 190 of file Overrides.java.
{
        final var hasWeapon = player.equipment.get(Equipment.WEAPON_SLOT) != null;
        final var weaponIs2h = hasWeapon && player.equipment.get(Equipment.WEAPON_SLOT).isTwoHanded();
        final var weaponIsRanged = hasWeapon && player.equipment.get(Equipment.WEAPON_SLOT).getRangedDefinition().isPresent();
        final var hasOverride = currentOverrides.containsKey(Equipment.WEAPON_SLOT);
        final var overrideIs2h = hasOverride && currentOverrides.get(Equipment.WEAPON_SLOT).isTwoHanded();
        final var overrideIsRanged = hasOverride && currentOverrides.get(Equipment.WEAPON_SLOT).getRangedDefinition().isPresent();
        if (hasWeapon) {
            if (weaponIs2h && !overrideIs2h || overrideIs2h && !weaponIs2h) {
                return false;
            }
            if (weaponIsRanged && !overrideIsRanged || overrideIsRanged && !weaponIsRanged) {
                return false;
            }
        }
        return hasOverride;
    }
References currentOverrides, hasOverride(), player, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by hasOverride().
loadContainers()
void com.runehive.content.overrides.Overrides.loadContainers () private
Definition at line 450 of file Overrides.java.
{
        currentOverrides.forEach((slot, item) -> {
            player.send(toggleConfig(item.getId(), "off"));
            player.send(new SendItemOnInterface(determineContainer(item.getId()), item));
        });
    }
References currentOverrides, determineContainer(), player, and toggleConfig().
Referenced by openInterface().
loadPreset()
void com.runehive.content.overrides.Overrides.loadPreset (String presetName) private
Definition at line 244 of file Overrides.java.
{
        if (!presets.containsKey(presetName)) {
            player.message("Error loading preset: " + presetName);
            return;
        }
        removeAllOverrides();
        for (Item item : presets.get(presetName).items) {
            if (item == null) {
                continue;
            }
            equipOverride(item);
        }
    }
References equipOverride(), player, presets, and removeAllOverrides().
Referenced by handleButtons(), and managePresetDialogue().
manageItemDialogue()
void com.runehive.content.overrides.Overrides.manageItemDialogue (Item item) private
Definition at line 386 of file Overrides.java.
{
        player.dialogueFactory.sendOption(
            "Equip <col=255>" + item.getName()+"</col>", () -> equipOverride(item),
            "@red@Delete " + item.getName(), () -> player.dialogueFactory.sendStatement(
                    "Are you sure you want to delete this override?", "The item will be @red@permanently lost@bla@.").sendOption(
                    "Yes, permanently delete " + item.getName(), () -> deleteOverride(item),
                    "Nevermind", () -> player.dialogueFactory.clear()),
            "Nevermind", () -> player.dialogueFactory.clear()).execute();
    }
References deleteOverride(), equipOverride(), com.runehive.game.world.items.Item.getName(), and player.
Referenced by handleButtons().
manageModeDialogue()
void com.runehive.content.overrides.Overrides.manageModeDialogue () private
Definition at line 374 of file Overrides.java.
{
        player.dialogueFactory.sendOption(
            "Toggle manage mode to " + (managingOverrides ? "@red@off@bla@" : "@gre@on@bla@"), () -> managingOverrides = !managingOverrides,
            "What is manage mode?", () -> player.dialogueFactory.sendStatement(
                    "Manage mode allows you to manage your overrides and presets.",
                    "When manage mode is on, clicking an override or preset will",
                    "open a menu allowing you to equip, delete, or rename it."),
            "Nevermind", () -> player.dialogueFactory.clear()).execute();
    }
References managingOverrides, and player.
Referenced by handleButtons().
managePresetDialogue()
void com.runehive.content.overrides.Overrides.managePresetDialogue (String presetName) private
Definition at line 398 of file Overrides.java.
{
        player.dialogueFactory.sendOption(
                "Equip <col=255>" + presetName + "</col>", () -> loadPreset(presetName),
                "Rename preset", () -> {
                    player.dialogueFactory.clear();
                    player.dialogueFactory.onAction(() -> player.send(new SendInputMessage("Enter new preset name:", 30, input -> renamePreset(presetName, input))));
                },
                "@red@Delete " + presetName, () -> player.dialogueFactory.sendStatement(
                        "Are you sure you want to delete this preset?").sendOption(
                        "Yes, delete " + presetName, () -> deletePreset(presetName),
                        "Nevermind", () -> player.dialogueFactory.clear()),
                "Nevermind", () -> player.dialogueFactory.clear()).execute();
    }
References deletePreset(), loadPreset(), player, and renamePreset().
Referenced by handleButtons().
openInterface()
void com.runehive.content.overrides.Overrides.openInterface ()
Definition at line 36 of file Overrides.java.
{
        if (Area.inWilderness(player)) {
            player.message("You can't do this in the wilderness.");
            return;
        }
        filter = EquipmentType.NOT_WIELDABLE;
        filterName = "All";
        drawText();
        loadContainers();
        player.interfaceManager.open(OVERRIDE_INTERFACE);
    }
References drawText(), filter, filterName, com.runehive.game.world.position.Area.inWilderness(), loadContainers(), com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE, OVERRIDE_INTERFACE, and player.
Referenced by handleButtons().
OverridePreset()
record com.runehive.content.overrides.Overrides.OverridePreset (Item... items)
Definition at line 23 of file Overrides.java.
{}
Referenced by createPreset().
removeAllOverrides()
void com.runehive.content.overrides.Overrides.removeAllOverrides () private
Definition at line 431 of file Overrides.java.
{
        while (!currentOverrides.isEmpty()) {
            removeOverride(currentOverrides.get(currentOverrides.keySet().iterator().next()).getId());
        }
    }
References currentOverrides, and removeOverride().
Referenced by loadPreset().
removeOverride()
void com.runehive.content.overrides.Overrides.removeOverride (int itemId)
Definition at line 421 of file Overrides.java.
{
        player.send(toggleConfig(itemId, "on"));
        player.send(new SendItemOnInterface(determineContainer(itemId), new Item(-1)));
        final var equipmentType = new Item(itemId).getDefinition().getEquipmentType();
        currentOverrides.remove(equipmentType.getSlot());
        player.updateFlags.add(UpdateFlag.APPEARANCE);
        player.equipment.updateAnimation();
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, currentOverrides, determineContainer(), com.runehive.game.world.items.Item.getDefinition(), player, and toggleConfig().
Referenced by deleteOverride(), and removeAllOverrides().
renamePreset()
void com.runehive.content.overrides.Overrides.renamePreset (String currentName, String newName) private
Definition at line 260 of file Overrides.java.
{
        if (!presets.containsKey(currentName)) {
            player.message("Error renaming preset: " + currentName);
            return;
        }
        if (presets.containsKey(newName)) {
            player.message("You already have a preset named " + newName + ".");
            return;
        }
        presets.put(newName, presets.get(currentName));
        presets.remove(currentName);
        player.message("Preset renamed to " + newName + ".");
        drawText();
    }
References drawText(), player, and presets.
Referenced by managePresetDialogue().
setFilter()
void com.runehive.content.overrides.Overrides.setFilter (EquipmentType equipmentType, String name) private
Definition at line 415 of file Overrides.java.
{
        filter = equipmentType;
        filterName = name;
        drawText();
    }
References drawText(), filter, and filterName.
Referenced by handleButtons().
toggleConfig()
SendConfig com.runehive.content.overrides.Overrides.toggleConfig (int itemId, String toggle) private
Definition at line 457 of file Overrides.java.
{
        final var configValue = toggle.equals("on") ? 0 : 1;
        final var equipmentSlot = new Item(itemId).getDefinition().getEquipmentType();
        return switch (equipmentSlot) {
            case HAT, HELM, MASK, FACE -> new SendConfig(1300, configValue);
            case CAPE -> new SendConfig(1301, configValue);
            case AMULET -> new SendConfig(1302, configValue);
            case WEAPON -> new SendConfig(1303, configValue);
            case BODY, TORSO -> new SendConfig(1304, configValue);
            case SHIELD -> new SendConfig(1305, configValue);
            case LEGS -> new SendConfig(1306, configValue);
            case BOOTS -> new SendConfig(1307, configValue);
            case GLOVES -> new SendConfig(1308, configValue);
            default -> null;
        };
    }
References com.runehive.game.world.items.Item.getDefinition().
Referenced by equipOverride(), loadContainers(), and removeOverride().
wipeInterface()
void com.runehive.content.overrides.Overrides.wipeInterface () private
Definition at line 79 of file Overrides.java.
{
        for (int i = 0; i < allOverrides.size() + 1; i++) {
            player.send(new SendString("", 60146 + (i * 2)));
        }
        buttons.clear();
        presetButtons.clear();
    }
References allOverrides, buttons, player, and presetButtons.
Referenced by drawText().
Member Data Documentation
allOverrides
List<Integer> com.runehive.content.overrides.Overrides.allOverrides = new ArrayList<>()
Definition at line 26 of file Overrides.java.
Referenced by addOverride(), deleteOverride(), drawText(), and wipeInterface().
AMULET_CONTAINER
final int com.runehive.content.overrides.Overrides.AMULET_CONTAINER = 60133 package
Definition at line 494 of file Overrides.java.
Referenced by determineContainer().
AMULET_SLOT_BTN
final int com.runehive.content.overrides.Overrides.AMULET_SLOT_BTN = -5413 package
Definition at line 507 of file Overrides.java.
Referenced by handleButtons().
BODY_CONTAINER
final int com.runehive.content.overrides.Overrides.BODY_CONTAINER = 60135 package
Definition at line 492 of file Overrides.java.
Referenced by determineContainer().
BODY_SLOT_BTN
final int com.runehive.content.overrides.Overrides.BODY_SLOT_BTN = -5410 package
Definition at line 508 of file Overrides.java.
Referenced by handleButtons().
BOOTS_CONTAINER
final int com.runehive.content.overrides.Overrides.BOOTS_CONTAINER = 60139 package
Definition at line 497 of file Overrides.java.
Referenced by determineContainer().
BOOTS_SLOT_BTN
final int com.runehive.content.overrides.Overrides.BOOTS_SLOT_BTN = -5407 package
Definition at line 510 of file Overrides.java.
Referenced by handleButtons().
buttons
final Map<Integer, Integer> com.runehive.content.overrides.Overrides.buttons = new HashMap<>() package
Definition at line 29 of file Overrides.java.
Referenced by drawText(), handleButtons(), and wipeInterface().
CAPE_CONTAINER
final int com.runehive.content.overrides.Overrides.CAPE_CONTAINER = 60132 package
Definition at line 495 of file Overrides.java.
Referenced by determineContainer().
CAPE_SLOT_BTN
final int com.runehive.content.overrides.Overrides.CAPE_SLOT_BTN = -5414 package
Definition at line 511 of file Overrides.java.
Referenced by handleButtons().
currentOverrides
Map<Integer, Item> com.runehive.content.overrides.Overrides.currentOverrides = new HashMap<>()
Definition at line 27 of file Overrides.java.
Referenced by createPreset(), deleteOverride(), equipOverride(), get(), hasOverride(), hasShieldOverride(), hasWeaponOverride(), loadContainers(), removeAllOverrides(), and removeOverride().
filter
EquipmentType com.runehive.content.overrides.Overrides.filter = EquipmentType.NOT_WIELDABLE package
Definition at line 32 of file Overrides.java.
Referenced by drawText(), openInterface(), and setFilter().
filterName
String com.runehive.content.overrides.Overrides.filterName = "All" package
Definition at line 33 of file Overrides.java.
Referenced by drawText(), openInterface(), and setFilter().
GLOVES_CONTAINER
final int com.runehive.content.overrides.Overrides.GLOVES_CONTAINER = 60138 package
Definition at line 496 of file Overrides.java.
Referenced by determineContainer().
GLOVES_SLOT_BTN
final int com.runehive.content.overrides.Overrides.GLOVES_SLOT_BTN = -5406 package
Definition at line 513 of file Overrides.java.
Referenced by handleButtons().
HEAD_CONTAINER
final int com.runehive.content.overrides.Overrides.HEAD_CONTAINER = 60131 package
Definition at line 491 of file Overrides.java.
Referenced by determineContainer().
HEAD_SLOT_BTN
final int com.runehive.content.overrides.Overrides.HEAD_SLOT_BTN = -5415 package
Definition at line 506 of file Overrides.java.
Referenced by handleButtons().
INFO_BTN
final int com.runehive.content.overrides.Overrides.INFO_BTN = -5286 package
Definition at line 502 of file Overrides.java.
Referenced by handleButtons().
INFO_CLOSE_BTN
final int com.runehive.content.overrides.Overrides.INFO_CLOSE_BTN = -5270 package
Definition at line 503 of file Overrides.java.
Referenced by handleButtons().
INFO_GO_BACK_BTN
final int com.runehive.content.overrides.Overrides.INFO_GO_BACK_BTN = -5267 package
Definition at line 504 of file Overrides.java.
Referenced by handleButtons().
INFO_INTERFACE
final int com.runehive.content.overrides.Overrides.INFO_INTERFACE = 60260 package
Definition at line 501 of file Overrides.java.
Referenced by handleButtons().
LEGS_CONTAINER
final int com.runehive.content.overrides.Overrides.LEGS_CONTAINER = 60137 package
Definition at line 493 of file Overrides.java.
Referenced by determineContainer().
LEGS_SLOT_BTN
final int com.runehive.content.overrides.Overrides.LEGS_SLOT_BTN = -5408 package
Definition at line 509 of file Overrides.java.
Referenced by handleButtons().
MANAGE_BTN
final int com.runehive.content.overrides.Overrides.MANAGE_BTN = -5395 package
Definition at line 505 of file Overrides.java.
Referenced by handleButtons().
managingOverrides
boolean com.runehive.content.overrides.Overrides.managingOverrides = false package
Definition at line 34 of file Overrides.java.
Referenced by handleButtons(), and manageModeDialogue().
OPEN_OVERRIDE_BTN
final int com.runehive.content.overrides.Overrides.OPEN_OVERRIDE_BTN = 27659 package
Definition at line 518 of file Overrides.java.
Referenced by handleButtons().
OVERRIDE_INTERFACE
final int com.runehive.content.overrides.Overrides.OVERRIDE_INTERFACE = 60106 package
Definition at line 500 of file Overrides.java.
Referenced by openInterface().
player
final Player com.runehive.content.overrides.Overrides.player private
Definition at line 18 of file Overrides.java.
Referenced by addOverride(), createPreset(), deleteOverride(), deletePreset(), drawPresets(), drawText(), equipOverride(), getFightType(), handleButtons(), hasOverride(), hasShieldOverride(), hasWeaponOverride(), loadContainers(), loadPreset(), manageItemDialogue(), manageModeDialogue(), managePresetDialogue(), openInterface(), Overrides(), removeOverride(), renamePreset(), and wipeInterface().
presetButtons
final Map<Integer, String> com.runehive.content.overrides.Overrides.presetButtons = new HashMap<>() package
Definition at line 30 of file Overrides.java.
Referenced by drawPresets(), handleButtons(), and wipeInterface().
presets
Map<String, OverridePreset> com.runehive.content.overrides.Overrides.presets = new HashMap<>()
Definition at line 24 of file Overrides.java.
Referenced by createPreset(), deleteOverride(), deletePreset(), drawPresets(), handleButtons(), loadPreset(), and renamePreset().
SAVE_PRESET_BTN
final int com.runehive.content.overrides.Overrides.SAVE_PRESET_BTN = -5422 package
Definition at line 516 of file Overrides.java.
Referenced by handleButtons().
SHIELD_CONTAINER
final int com.runehive.content.overrides.Overrides.SHIELD_CONTAINER = 60136 package
Definition at line 499 of file Overrides.java.
Referenced by determineContainer().
SHIELD_SLOT_BTN
final int com.runehive.content.overrides.Overrides.SHIELD_SLOT_BTN = -5409 package
Definition at line 514 of file Overrides.java.
Referenced by handleButtons().
VIEW_ALL_BTN
final int com.runehive.content.overrides.Overrides.VIEW_ALL_BTN = -5428 package
Definition at line 517 of file Overrides.java.
Referenced by handleButtons().
VIEW_PRESET_BTN
final int com.runehive.content.overrides.Overrides.VIEW_PRESET_BTN = -5417 package
Definition at line 515 of file Overrides.java.
Referenced by handleButtons().
WEAPON_CONTAINER
final int com.runehive.content.overrides.Overrides.WEAPON_CONTAINER = 60134 package
Definition at line 498 of file Overrides.java.
Referenced by determineContainer().
WEAPON_SLOT_BTN
final int com.runehive.content.overrides.Overrides.WEAPON_SLOT_BTN = -5411 package
Definition at line 512 of file Overrides.java.
Referenced by handleButtons().
The documentation for this class was generated from the following file:
java/com/runehive/content/overrides/Overrides.java