RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener Class Reference
com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener Class Reference
Public Member Functions
void block (Mob attacker, Mob defender, Hit hit, CombatType combatType)
void hit (Mob attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, Mob defender, Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
boolean canAttack (T attacker, Mob defender)
boolean canOtherAttack (Mob attacker, T defender)
void finishIncoming (Mob attacker, T defender)
void finishOutgoing (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
void hitsplat (T attacker, Mob defender, Hit hit)
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
void onKill (T attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, T defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
void start (T attacker, Mob defender, Hit[] hits)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Static Public Member Functions
static PrayerListener get ()
Private Member Functions
PrayerListener ()
Static Private Attributes
static final PrayerListener INSTANCE = new PrayerListener()
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
static final CombatListener< Mob > CANT_ATTACK
Detailed Description
Definition at line 16 of file PrayerListener.java.
Constructor & Destructor Documentation
PrayerListener()
com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.PrayerListener () private
Definition at line 20 of file PrayerListener.java.
{}
Referenced by get().
Member Function Documentation
block()
void com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block (Mob attacker, Mob defender, Hit hit, CombatType combatType)
Definition at line 31 of file PrayerListener.java.
{
        int health = defender.getCurrentHealth() - hit.getDamage();
        if (defender.prayer.isActive(Prayer.REDEMPTION) && health < defender.getMaximumHealth() / 10) {
            Skill skill = defender.skills.get(Skill.PRAYER);
            int amount = skill.getLevel() / 4;
            defender.heal(amount);
            defender.graphic(new Graphic(436, UpdatePriority.HIGH));
            if (defender.isPlayer())
                defender.getPlayer().playerAssistant.drainPrayer(skill.getLevel());
        }
    }
References com.runehive.game.world.entity.mob.player.PlayerAssistant.drainPrayer(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.Mob.heal(), com.runehive.game.UpdatePriority.HIGH, hit(), com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.REDEMPTION, and com.runehive.game.world.entity.mob.Mob.skills.
get()
PrayerListener com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.get () static
Definition at line 60 of file PrayerListener.java.
{
        return INSTANCE;
    }
References INSTANCE, and PrayerListener().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.setPrayer().
hit()
void com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.hit (Mob attacker, Mob defender, Hit hit)
Definition at line 23 of file PrayerListener.java.
{
        if (attacker.prayer.isActive(Prayer.SMITE)) {
            defender.skills.get(Skill.PRAYER).removeLevel(hit.getDamage() / 4);
            defender.skills.refresh(Skill.PRAYER);
        }
    }
References com.runehive.game.world.entity.skill.SkillManager.get(), hit(), com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.skill.SkillManager.refresh(), com.runehive.game.world.entity.skill.Skill.removeLevel(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.mob.prayer.Prayer.SMITE.
Referenced by block(), hit(), and preDeath().
preDeath()
void com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath (Mob attacker, Mob defender, Hit hit)
Definition at line 44 of file PrayerListener.java.
{
        if (defender.prayer.isActive(Prayer.RETRIBUTION)) {
            int max = defender.skills.getMaxLevel(Skill.PRAYER) / 4;
            defender.graphic(new Graphic(437, UpdatePriority.HIGH));
            if (!Area.inMulti(defender)) {
                attacker.damage(new Hit(RandomUtils.inclusive(max), HitIcon.NONE));
            } else {
                CombatUtil.areaAction(defender, 3 * 3, 1, other -> {
                    int damage = RandomUtils.inclusive(max);
                    other.damage(new Hit(damage, HitIcon.NONE));
                });
            }
        }
    }
References com.runehive.game.world.entity.combat.CombatUtil.areaAction(), com.runehive.game.world.entity.mob.Mob.damage(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.UpdatePriority.HIGH, hit(), com.runehive.util.RandomUtils.inclusive(), com.runehive.game.world.position.Area.inMulti(), com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.combat.hit.HitIcon.NONE, com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.RETRIBUTION, and com.runehive.game.world.entity.mob.Mob.skills.
Member Data Documentation
INSTANCE
final PrayerListener com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.INSTANCE = new PrayerListener() static private
Definition at line 18 of file PrayerListener.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/other/PrayerListener.java