RuneHive-Game: com.runehive.RuneHive Class Reference
com.runehive.RuneHive Class Reference
Public Member Functions
LoginExecutorService getLoginExecutorService ()
void start () throws Exception
Static Public Member Functions
static DateTime currentDateTime ()
static RuneHive getInstance ()
static void main (String[] args)
static DateTimeZone timeZone ()
Static Public Attributes
static final AtomicBoolean serverStarted = new AtomicBoolean(false)
static final Stopwatch UPTIME = Stopwatch.start()
Private Member Functions
void onStart ()
Called when the game engine is running and all the startup tasks have finished loading.
void processParallelStartupTasks ()
Called after the sequential startup tasks, use this for faster startup.
void processSequentialStartupTasks ()
RuneHive ()
Private Attributes
final LoginExecutorService loginExecutorService
Static Private Attributes
static final GameEngine gameService = new GameEngine()
static final RuneHive INSTANCE = new RuneHive()
static final Logger logger = LogManager.getLogger(RuneHive.class)
static final NetworkService networkService = new NetworkService()
static final StartupService startupService = new StartupService()
Detailed Description
Definition at line 55 of file RuneHive.java.
Constructor & Destructor Documentation
RuneHive()
com.runehive.RuneHive.RuneHive () private
Definition at line 71 of file RuneHive.java.
                       {
        loginExecutorService = new LoginExecutorService(Runtime.getRuntime().availableProcessors());
    }
References loginExecutorService.
Referenced by getInstance().
Member Function Documentation
currentDateTime()
DateTime com.runehive.RuneHive.currentDateTime () static
Definition at line 204 of file RuneHive.java.
{
        return new DateTime(timeZone());
    }
References timeZone().
Referenced by com.runehive.game.world.cronjobs.impl.DoubleExperienceJob.execute().
getInstance()
RuneHive com.runehive.RuneHive.getInstance () static
Definition at line 200 of file RuneHive.java.
{
        return INSTANCE;
    }
References INSTANCE, and RuneHive().
Referenced by com.runehive.net.session.LoginSession.handleClientPacket().
getLoginExecutorService()
LoginExecutorService com.runehive.RuneHive.getLoginExecutorService ()
Definition at line 212 of file RuneHive.java.
{
        return this.loginExecutorService;
    }
Referenced by com.runehive.net.session.LoginSession.handleClientPacket().
main()
void com.runehive.RuneHive.main (String[] args) static
Definition at line 185 of file RuneHive.java.
{
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            logger.info("shutting down server, initializing shutdown hook");
            World.save();
            com.runehive.content.ai.LazyAIManager.shutdown();
        }));
        try {
            INSTANCE.start();
        } catch (Throwable t) {
            logger.error("A problem has been encountered while starting the server.", t);
        }
    }
References INSTANCE, logger, and com.runehive.game.world.World.save().
onStart()
void com.runehive.RuneHive.onStart () private
Called when the game engine is running and all the startup tasks have finished loading.
Definition at line 131 of file RuneHive.java.
{
        if (WellOfGoodwill.isActive()) {
            World.schedule(new DoubleExperienceEvent());
        }
        World.schedule(new MessageEvent());
        World.schedule(new ClanUpdateEvent());
        World.schedule(new SkotizoEvent());
        World.schedule(new PlayerSaveEvent());
//        World.schedule(new BotStartupEvent());
        World.schedule(new BloodChestEvent());
        // World.schedule(new LMSLobbyEvent()); // Disabled - causes deadlock
        // World.schedule(new LMSGameEvent()); // Disabled - related to LMS
        logger.info("Events have been scheduled");
    }
References com.runehive.content.WellOfGoodwill.isActive(), logger, and com.runehive.game.world.World.schedule().
Referenced by start().
processParallelStartupTasks()
void com.runehive.RuneHive.processParallelStartupTasks () private
Called after the sequential startup tasks, use this for faster startup.
Try not to use this method for tasks that rely on other tasks you'll run into issues.
Definition at line 108 of file RuneHive.java.
{
        startupService.submit(new PacketSizeParser());
        startupService.submit(new PacketListenerLoader());
        startupService.submit(TriviaBot::declare);
//        startupService.submit(PersonalStoreSaver::loadPayments);
        startupService.submit(ClanRepository::loadChannels);
        //  startupService.submit(GlobalRecords::load);
        startupService.submit(SkillRepository::load);
        startupService.submit(ProfileRepository::load);
        startupService.submit(ItemActionRepository::declare);
        startupService.submit(ClueScrollPlugin::declare);
        startupService.submit(MysteryBox::load);
        startupService.submit(GameSaver::load);
        startupService.submit(PreloadRepository::declare);
        startupService.submit(TradingPost::loadAllListings);
        startupService.submit(TradingPost::loadItemHistory);
        startupService.submit(TradingPost::loadRecentItemHistory);
        startupService.shutdown();
    }
References com.runehive.content.itemaction.ItemActionRepository.declare(), com.runehive.content.preloads.PreloadRepository.declare(), com.runehive.content.triviabot.TriviaBot.declare(), com.runehive.content.mysterybox.MysteryBox.load(), com.runehive.content.skill.SkillRepository.load(), com.runehive.game.world.entity.mob.player.profile.ProfileRepository.load(), com.runehive.util.GameSaver.load(), com.runehive.content.tradingpost.TradingPost.loadAllListings(), com.runehive.content.clanchannel.ClanRepository.loadChannels(), com.runehive.content.tradingpost.TradingPost.loadItemHistory(), com.runehive.content.tradingpost.TradingPost.loadRecentItemHistory(), and startupService.
Referenced by start().
processSequentialStartupTasks()
void com.runehive.RuneHive.processSequentialStartupTasks () private
Definition at line 75 of file RuneHive.java.
{
        OldToNew.load();
        try {
            //object/region decoding must be done before parallel.
            new ObjectRemovalParser().run();
            final FileSystem fs = FileSystem.create("data/cache");
            new ObjectDefinitionDecoder(fs).run();
            new MapDefinitionDecoder(fs).run();
            new RegionDecoder(fs).run();
            new AnimationDefinitionDecoder(fs).run();
            CacheNpcDefinition.unpackConfig(fs.getArchive(FileSystem.CONFIG_ARCHIVE));
        } catch (IOException e) {
            e.printStackTrace();
        }
        ItemDefinition.createParser().run();
        NpcDefinition.createParser().run();
        ObjectExamines.loadObjectExamines();
        new CombatProjectileParser().run();
        CombatListenerManager.load();
        new NpcSpawnParser().run();
        new NpcDropParser().run();
        new NpcForceChatParser().run();
        new StoreParser().run();
        new GlobalObjectParser().run();
        // ShootingStar.init(); // Disabled - causes deadlock
        Wintertodt.init();
    }
References com.runehive.fs.cache.FileSystem.CONFIG_ARCHIVE, com.runehive.fs.cache.FileSystem.create(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.createParser(), com.runehive.game.world.items.ItemDefinition.createParser(), com.runehive.content.wintertodt.Wintertodt.init(), com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.load(), com.runehive.fs.cache.decoder.AnimationDefinitionDecoder.run(), com.runehive.fs.cache.decoder.MapDefinitionDecoder.run(), com.runehive.fs.cache.decoder.ObjectDefinitionDecoder.run(), com.runehive.fs.cache.decoder.RegionDecoder.run(), com.runehive.util.parser.GenericParser.run(), and com.runehive.fs.cache.decoder.CacheNpcDefinition.unpackConfig().
Referenced by start().
start()
void com.runehive.RuneHive.start () throws Exception
Definition at line 147 of file RuneHive.java.
{
        if (Config.FORUM_INTEGRATION) {
            ForumService.start(); // used to check users logging in with website credentials
            if (Config.WORLD_TYPE == WorldType.LIVE) {
                PostgreService.start(); // used to start the postgres connection pool
                WebsitePlayerCountService.getInstance().startAsync(); // used to display player count on website
            }
        }
        new FileServer().start();
        logger.info("RuneHive is running (client version " + Config.CLIENT_VERSION + ")");
        logger.info(String.format("Game Engine=%s", Config.PARALLEL_GAME_ENGINE ? "Parallel" : "Sequential"));
        processSequentialStartupTasks();
        processParallelStartupTasks();
        startupService.awaitUntilFinished(5, TimeUnit.MINUTES);
        logger.info("Startup service finished");
        LMSLoadoutManager.load();
        PluginManager.load("plugin");
        gameService.startAsync().awaitRunning();
        logger.info("Game service started");
        onStart();
        Jobs.load();
        BannedPlayers.load();
        IPBannedPlayers.load();
        IPMutedPlayers.load();
        networkService.start(Config.SERVER_PORT);
    }
References com.runehive.Config.CLIENT_VERSION, com.runehive.Config.FORUM_INTEGRATION, gameService, com.runehive.game.service.WebsitePlayerCountService.getInstance(), com.runehive.game.world.WorldType.LIVE, com.runehive.content.lms.loadouts.LMSLoadoutManager.load(), com.runehive.game.plugin.PluginManager.load(), com.runehive.game.world.cronjobs.Jobs.load(), com.runehive.game.world.entity.mob.player.BannedPlayers.load(), com.runehive.game.world.entity.mob.player.IPBannedPlayers.load(), com.runehive.game.world.entity.mob.player.IPMutedPlayers.load(), logger, networkService, onStart(), com.runehive.Config.PARALLEL_GAME_ENGINE, processParallelStartupTasks(), processSequentialStartupTasks(), com.runehive.Config.SERVER_PORT, com.runehive.game.service.ForumService.start(), com.runehive.game.service.PostgreService.start(), dev.advo.fs.FileServer.start(), startupService, and com.runehive.Config.WORLD_TYPE.
timeZone()
DateTimeZone com.runehive.RuneHive.timeZone () static
Definition at line 208 of file RuneHive.java.
{
        return DateTimeZone.UTC;
    }
Referenced by currentDateTime().
Member Data Documentation
gameService
final GameEngine com.runehive.RuneHive.gameService = new GameEngine() static private
Definition at line 64 of file RuneHive.java.
Referenced by start().
INSTANCE
final RuneHive com.runehive.RuneHive.INSTANCE = new RuneHive() static private
Definition at line 67 of file RuneHive.java.
Referenced by getInstance(), and main().
logger
final Logger com.runehive.RuneHive.logger = LogManager.getLogger(RuneHive.class) static private
Definition at line 57 of file RuneHive.java.
Referenced by main(), onStart(), and start().
loginExecutorService
final LoginExecutorService com.runehive.RuneHive.loginExecutorService private
Definition at line 69 of file RuneHive.java.
Referenced by RuneHive().
networkService
final NetworkService com.runehive.RuneHive.networkService = new NetworkService() static private
Definition at line 65 of file RuneHive.java.
Referenced by start().
serverStarted
final AtomicBoolean com.runehive.RuneHive.serverStarted = new AtomicBoolean(false) static
Definition at line 59 of file RuneHive.java.
Referenced by com.runehive.net.session.LoginSession.evaluate(), and com.runehive.game.service.NetworkService.start().
startupService
final StartupService com.runehive.RuneHive.startupService = new StartupService() static private
Definition at line 63 of file RuneHive.java.
Referenced by processParallelStartupTasks(), and start().
UPTIME
final Stopwatch com.runehive.RuneHive.UPTIME = Stopwatch.start() static
Definition at line 60 of file RuneHive.java.
Referenced by com.runehive.util.Utility.getUptime(), and com.runehive.game.service.NetworkService.start().
The documentation for this class was generated from the following file:
java/com/runehive/RuneHive.java