RuneHive-Game: com.runehive.content.clanchannel.content.ClanViewer Class Reference
com.runehive.content.clanchannel.content.ClanViewer Class Reference
Handles viewing clan information.
Classes
enum ClanTab
enum Filter
Public Member Functions
ClanViewer (Player player)
void open (ClanChannel channel, ClanTab tab)
void open (ClanTab tab)
void update (ClanChannel channel)
void viewAchievements ()
Public Attributes
int clanIndex = 0
List< ClanChannel > clanList = new ArrayList<>()
List< ClanMember > clanMembers = new ArrayList<>()
Filter filter = Filter.ALL_TIME
int memberIndex = 0
Private Member Functions
void drawClanDetails ()
void drawClanList (String key)
void drawClanMembers ()
String[] getDetails ()
Gets the clan information details.
String[] getProfile (ClanMember member)
Private Attributes
final Player player
String searchKey = ""
ClanChannel viewing
Detailed Description
Handles viewing clan information.
Author
Daniel
Definition at line 21 of file ClanViewer.java.
Constructor & Destructor Documentation
ClanViewer()
com.runehive.content.clanchannel.content.ClanViewer.ClanViewer (Player player)
Definition at line 33 of file ClanViewer.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
drawClanDetails()
void com.runehive.content.clanchannel.content.ClanViewer.drawClanDetails () private
Definition at line 90 of file ClanViewer.java.
{
        String[] strings = getDetails();
        assert strings.length != 0;
        for (int index = 0, string = 53102; index < strings.length; index++, string += 2) {
            player.send(new SendString(strings[index] == null ? "" : strings[index], string));
        }
    }
References getDetails(), and player.
Referenced by open().
drawClanList()
void com.runehive.content.clanchannel.content.ClanViewer.drawClanList (String key) private
Definition at line 67 of file ClanViewer.java.
{
        Set<ClanChannel> channels = ClanRepository.getTopChanels(filter).orElse(null);
        if (channels == null) return;
        if (!key.isEmpty()) {
            channels.removeIf(channel -> !channel.getName().contains(key));
        }
        int size = channels.size() > 13 ? channels.size() : 13;
        Iterator<ClanChannel> iterator = channels.iterator();
        for (int index = 0, string = 53202; index < size; index++, string += 2) {
            if (iterator.hasNext()) {
                ClanChannel channel = iterator.next();
                String prefix = (index + 1) + ")";
                player.send(new SendString((clanIndex == index ? "<col=ffffff>" : "") + prefix + " " + channel.getName(), string));
                player.send(new SendTooltip("View " + channel.getName() + "'s clan profile", string));
            } else {
                player.send(new SendString("", string));
                player.send(new SendTooltip("", string));
            }
        }
        clanList = new ArrayList<>(channels);
        player.send(new SendScrollbar(53300, size * 14));
    }
References clanIndex, clanList, filter, com.runehive.content.clanchannel.ClanRepository.getTopChanels(), and player.
Referenced by open().
drawClanMembers()
void com.runehive.content.clanchannel.content.ClanViewer.drawClanMembers () private
Definition at line 134 of file ClanViewer.java.
{
        int size = 18;
        List<ClanMember> membersList = new ArrayList<>(size);
        if (viewing != null) {
            viewing.forEach(o -> {
                if (o != null)
                    membersList.add(o);
            });
            size = membersList.size() < 18 ? 18 : membersList.size();
        }
        for (int i = 0, string = 55052; i < size; i++, string += 2) {
            boolean valid = i < membersList.size();
            ClanMember member = valid ? membersList.get(i) : null;
            String name = valid ? member.rank.getString() + " " + member.name : "";
            player.send(new SendString((i == memberIndex ? "<col=ffffff>" : "") + name, string));
            player.send(new SendTooltip(valid ? "View " + member.name + "'s clan profile" : "", string));
        }
        player.send(new SendScrollbar(55050, size * 18));
        clanMembers = membersList;
        if (memberIndex > membersList.size())
            return;
        ClanMember member = membersList.get(memberIndex);
        if (member == null)
            return;
        String[] strings = getProfile(member);
        for (int index = 0, string = 55012; index < strings.length; index++, string += 2) {
            player.send(new SendString(strings[index] == null ? "" : strings[index], string));
        }
    }
References clanMembers, getProfile(), com.runehive.content.clanchannel.ClanRank.getString(), memberIndex, com.runehive.content.clanchannel.ClanMember.name, player, com.runehive.content.clanchannel.ClanMember.rank, and viewing.
Referenced by open().
getDetails()
String[] com.runehive.content.clanchannel.content.ClanViewer.getDetails () private
Gets the clan information details.
Definition at line 99 of file ClanViewer.java.
{
        if (viewing == null)
            return new String[10];
        return new String[]{
                "</col>Owner: " + viewing.getColor() + "<clan=7> " + Utility.formatName(viewing.getOwner()),
                "</col>Established: " + viewing.getColor() + "" + viewing.getDetails().established,
                "</col>Members: " + viewing.getColor() + "" + viewing.getMembers().size(),
                "</col>Type: " + viewing.getColor() + viewing.getDetails().type.getIcon() + " " + Utility.formatEnum(viewing.getDetails().type.name()),
                "</col>Level: " + viewing.getColor() + "" + Utility.formatEnum(viewing.getDetails().level.name()),
                "</col>Tag " + viewing.getColor() + "" + (viewing.getTag().length() <= 0 ? "None" : ("[" + viewing.getTag()) + "]"),
                "</col>Experience: " + viewing.getColor() + "" + Utility.formatDigits(viewing.getDetails().experience),
                "</col>Points: " + viewing.getColor() + "" + Utility.formatDigits(viewing.getDetails().points),
                "</col>Achievements Completed: " + viewing.getColor() + "NA",
                "</col>Tasks Completed: " + viewing.getColor() + "NA",
//           (channel.modifier == null ? "None" : (channel.modifier.name) + "(" + channel.modifierDuration + " minute(s)") + ")",
                "</col>Avg. Total: " + viewing.getColor() + "" + viewing.getDetails().getAverageTotal(),
        };
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatEnum(), com.runehive.util.Utility.formatName(), and viewing.
Referenced by drawClanDetails().
getProfile()
String[] com.runehive.content.clanchannel.content.ClanViewer.getProfile (ClanMember member) private
Definition at line 118 of file ClanViewer.java.
{
        if (member == null)
            return new String[10];
        return new String[]{
                "</col>Rank: " + viewing.getColor() + "" + member.rank.getString() + " " + member.rank.name,
                "</col>Joined: " + viewing.getColor() + "" + member.joined,
                "</col>Exp Gained: " + viewing.getColor() + "" + Utility.formatDigits(member.expGained),
                "</col>PvP Kills: " + viewing.getColor() + "" + member.playerKills,
                "</col>PvM Kills: " + viewing.getColor() + "" + member.npcKills,
                "",
                "",
                "",
                "",
        };
    }
References com.runehive.content.clanchannel.ClanMember.expGained, com.runehive.util.Utility.formatDigits(), com.runehive.content.clanchannel.ClanRank.getString(), com.runehive.content.clanchannel.ClanMember.joined, com.runehive.content.clanchannel.ClanRank.name, com.runehive.content.clanchannel.ClanMember.npcKills, com.runehive.content.clanchannel.ClanMember.playerKills, com.runehive.content.clanchannel.ClanMember.rank, and viewing.
Referenced by drawClanMembers().
open() [1/2]
void com.runehive.content.clanchannel.content.ClanViewer.open (ClanChannel channel, ClanTab tab)
Definition at line 41 of file ClanViewer.java.
{
        int interfaceId = 0;
        this.viewing = channel;
        String name = Utility.formatName(filter.name().toLowerCase().replaceAll("_", " "));
        Item[] showcase = viewing == null ? new Item[3] : viewing.getShowcaseItems();
        if (tab == ClanTab.OVERVIEW) {
            drawClanList(searchKey);
            drawClanDetails();
            interfaceId = 53000;
            player.send(new SendString(name + ":", 53006));
        } else if (tab == ClanTab.MEMBERS) {
            drawClanMembers();
            interfaceId = 53500;
            player.send(new SendString("Member List:", 53006));
        }
        player.send(new SendConfig(531, tab.ordinal()));
        player.send(new SendString(viewing != null ? viewing.getName() : "", 53009));
        player.send(new SendString(viewing != null ? viewing.getSlogan() : "", 53010));
        player.send(new SendString(searchKey.isEmpty() ? "Search for clan" : searchKey, 53012));
        player.send(new SendString(name, 53019));
        player.send(new SendItemOnInterface(53011, showcase));
        player.interfaceManager.open(interfaceId);
    }
References drawClanDetails(), drawClanList(), drawClanMembers(), filter, com.runehive.util.Utility.formatName(), com.runehive.content.clanchannel.content.ClanViewer.ClanTab.MEMBERS, com.runehive.content.clanchannel.content.ClanViewer.ClanTab.OVERVIEW, player, searchKey, and viewing.
open() [2/2]
void com.runehive.content.clanchannel.content.ClanViewer.open (ClanTab tab)
Definition at line 37 of file ClanViewer.java.
{
        open(viewing, tab);
    }
References open(), and viewing.
Referenced by open(), com.runehive.content.dialogue.impl.ClanmasterDialogue.sendDialogues(), and update().
update()
void com.runehive.content.clanchannel.content.ClanViewer.update (ClanChannel channel)
Definition at line 169 of file ClanViewer.java.
{
        if (player.interfaceManager.isInterfaceOpen(53000))
            open(channel, ClanTab.OVERVIEW);
        if (player.interfaceManager.isSidebar(Config.CLAN_TAB, 42000)) {
            ClanChannelHandler.manage(player);
        }
    }
References com.runehive.Config.CLAN_TAB, com.runehive.content.clanchannel.channel.ClanChannelHandler.manage(), open(), com.runehive.content.clanchannel.content.ClanViewer.ClanTab.OVERVIEW, and player.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.setName(), com.runehive.content.clanchannel.channel.ClanChannel.setSlogan(), and com.runehive.content.clanchannel.channel.ClanChannel.setTag().
viewAchievements()
void com.runehive.content.clanchannel.content.ClanViewer.viewAchievements ()
Definition at line 177 of file ClanViewer.java.
{
        ClanChannel channel = player.clanChannel;
        int size = ClanAchievement.values().length;
        Difficulty old = null;
        for (int index = 0, string = 37114; index < size; index++, string++) {
            Optional<ClanAchievement> achievement = ClanAchievement.forOrdinal(index);
            if (achievement.isPresent()) {
                boolean completed = channel.getDetails().completedAchievement(achievement.get());
                Difficulty difficulty = achievement.get().difficulty;
                if (old != difficulty) {
                    string++;
                    player.send(new SendString("<col=255>[" + Utility.formatEnum(difficulty.name()) + "]", string));
                    string++;
                    player.send(new SendString("", string));
                    string++;
                }
                old = difficulty;
                int progress = channel.getDetails().getAchievementCompletion(achievement.get());
                int goal = achievement.get().amount;
                String name = (completed ? "<col=347043>" + "" : "") + achievement.get().details + " (" + Utility.getPercentageAmount(progress, goal) + "%)";
                player.send(new SendString(name, string));
            } else {
                player.send(new SendString("", string));
            }
        }
        player.send(new SendString("<col=000000>These are all the clan achievements available", 37111));
        player.send(new SendString("<col=000000>Completed achievements will be highlighted in <col=347043>green</col>", 37112));
        player.send(new SendString("Completed: 0/" + size, 37113));
        player.send(new SendString("", 37114));
        player.send(new SendString("", 37107));
        player.send(new SendString(channel.getName() + "'s Achievements", 37103));
        player.send(new SendScrollbar(37110, 500));
        player.interfaceManager.open(37100);
    }
References com.runehive.util.Utility.formatEnum(), com.runehive.content.clanchannel.content.ClanAchievement.forOrdinal(), com.runehive.util.Utility.getPercentageAmount(), and player.
Member Data Documentation
clanIndex
int com.runehive.content.clanchannel.content.ClanViewer.clanIndex = 0
Definition at line 26 of file ClanViewer.java.
Referenced by drawClanList().
clanList
List<ClanChannel> com.runehive.content.clanchannel.content.ClanViewer.clanList = new ArrayList<>()
Definition at line 28 of file ClanViewer.java.
Referenced by drawClanList().
clanMembers
List<ClanMember> com.runehive.content.clanchannel.content.ClanViewer.clanMembers = new ArrayList<>()
Definition at line 29 of file ClanViewer.java.
Referenced by drawClanMembers().
filter
Filter com.runehive.content.clanchannel.content.ClanViewer.filter = Filter.ALL_TIME
Definition at line 31 of file ClanViewer.java.
Referenced by drawClanList(), and open().
memberIndex
int com.runehive.content.clanchannel.content.ClanViewer.memberIndex = 0
Definition at line 27 of file ClanViewer.java.
Referenced by drawClanMembers().
player
final Player com.runehive.content.clanchannel.content.ClanViewer.player private
Definition at line 24 of file ClanViewer.java.
Referenced by ClanViewer(), drawClanDetails(), drawClanList(), drawClanMembers(), open(), update(), and viewAchievements().
searchKey
String com.runehive.content.clanchannel.content.ClanViewer.searchKey = "" private
Definition at line 30 of file ClanViewer.java.
Referenced by open().
viewing
ClanChannel com.runehive.content.clanchannel.content.ClanViewer.viewing private
Definition at line 25 of file ClanViewer.java.
Referenced by drawClanMembers(), getDetails(), getProfile(), open(), and open().
The documentation for this class was generated from the following file:
java/com/runehive/content/clanchannel/content/ClanViewer.java