RuneHive-Game: com.runehive.game.world.items.Item Class Reference
com.runehive.game.world.items.Item Class Reference
The container class that represents an item that can be interacted with.
Public Member Functions
Item clone ()
Item copy ()
A substitute for Object#clone() that creates another 'copy' of this instance.
Item createAndDecrement (int removeAmount)
Creates a new item with amount - removeAmount and the same identifier.
Item createAndIncrement (int addAmount)
Creates a new item with amount + addAmount and the same identifier.
Item createWithAmount (int newAmount)
Creates a new item with newAmount and the same identifier as this instance.
Item createWithId (int newId)
Creates a new item with newId and the same amount as this instance.
final void decrementAmount ()
Decrements the amount by 1.
final void decrementAmountBy (int amount)
Decrements the amount by amount @endiliteral.
boolean equalIds (Item other)
boolean equals (Object obj)
final int getAmount ()
Gets the quantity of this item.
OptionalInt getAttackAnimation (FightType type)
int getBaseValue ()
OptionalInt getBlockAnimation ()
int getBonus (int index)
int[] getBonuses ()
ItemDefinition getDefinition ()
Gets the item definition for the item identifier.
String getDestroyMessage ()
EquipmentType getEquipmentType ()
int getHighAlch ()
final int getId ()
Gets the identification of this item.
int getLowAlch ()
String getName ()
int getNotedId ()
Optional< RangedWeaponDefinition > getRangedDefinition ()
int[] getRequirements ()
int getRunAnimation ()
int getSellValue ()
int getStandAnimation ()
int getStreetValue ()
int getUnnotedId ()
int getValue ()
Gets the value for this item.
int getValue (PriceType type)
Gets the value for this item.
int getWalkAnimation ()
WeaponInterface getWeaponInterface ()
double getWeight ()
int hashCode ()
final void incrementAmount ()
Increments the amount by 1.
final void incrementAmountBy (int amount)
Increments the amount by amount.
boolean isDestroyable ()
boolean isEquipable ()
boolean isNoteable ()
boolean isNoted ()
boolean isStackable ()
boolean isTradeable ()
boolean isTwoHanded ()
Item (int id)
Creates a new Item with an quantity of 1.
Item (int id, int amount)
Creates a new Item.
Item (int id, int minAmt, int maxAmt)
Creates a new Item with a random amount between minAmt and maxAmt.
Item (int id, long amount)
boolean matchesId (int id)
Item noted ()
Gets the item note item.
final void setAmount (int amount)
Sets the quantity of this item.
final void setId (int id)
Sets the identification of this item.
final String toString ()
Item unnoted ()
Gets the unnoted item.
Static Public Member Functions
static final Item[] convert (int... id)
Converts an int array into an Item array.
static final int[] convert (Item... ids)
Converts an Item array into an Integer array.
static boolean valid (Item item)
Determines if item is valid.
Private Attributes
int amount
The quantity of this item.
int id
The identification of this item.
Detailed Description
The container class that represents an item that can be interacted with.
Author
lare96 http://github.com/lare96
Definition at line 21 of file Item.java.
Constructor & Destructor Documentation
Item() [1/4]
com.runehive.game.world.items.Item.Item (int id, int amount)
Creates a new Item.
Definition at line 36 of file Item.java.
{
        if (amount < 0) amount = 0;
        this.id = id;
        this.amount = amount;
    }
References amount, and id.
Referenced by clone(), convert(), convert(), copy(), createAndDecrement(), createAndIncrement(), createWithAmount(), createWithId(), equalIds(), equals(), noted(), unnoted(), and valid().
Item() [2/4]
com.runehive.game.world.items.Item.Item (int id, int minAmt, int maxAmt)
Creates a new Item with a random amount between minAmt and maxAmt.
Definition at line 45 of file Item.java.
{
        if (minAmt < 0 || maxAmt < 0) amount = 0;
        this.id = id;
        this.amount = Utility.random(minAmt, maxAmt, true);
    }
References amount, id, and com.runehive.util.Utility.random().
Item() [3/4]
com.runehive.game.world.items.Item.Item (int id, long amount)
Definition at line 51 of file Item.java.
{
        int amount2;
        if (amount < 0) {
            amount2 = 0;
        } else if (amount > Integer.MAX_VALUE) {
            amount2 = Integer.MAX_VALUE;
        } else {
            amount2 = (int) amount;
        }
        this.id = id;
        this.amount = amount2;
    }
References amount, and id.
Item() [4/4]
com.runehive.game.world.items.Item.Item (int id)
Creates a new Item with an quantity of 1.
Parameters
id the identification of this item.
Definition at line 220 of file Item.java.
{
        this(id, 1);
    }
References id.
Member Function Documentation
clone()
Item com.runehive.game.world.items.Item.clone ()
Definition at line 64 of file Item.java.
{
        try {
            return (Item) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
        }
        return this;
    }
References Item().
Referenced by createAndDecrement(), createAndIncrement(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), and com.runehive.content.lms.LMSGame.reset().
convert() [1/2]
final Item[] com.runehive.game.world.items.Item.convert (int... id) static
Converts an int array into an Item array.
Parameters
id the array to convert into an item array.
Returns
the item array containing the values from the int array.
Definition at line 244 of file Item.java.
{
        List<Item> items = new ArrayList<>();
        for (int identifier : id) {
            items.add(new Item(identifier));
        }
        return Iterables.toArray(items, Item.class);
    }
References Item().
convert() [2/2]
final int[] com.runehive.game.world.items.Item.convert (Item... ids) static
Converts an Item array into an Integer array.
Parameters
ids the array to convert into an Integer array.
Returns
the Integer array containing the values from the item array.
Definition at line 230 of file Item.java.
{
        List<Integer> values = new ArrayList<>();
        for (Item identifier : ids) {
            values.add(identifier.getId());
        }
        return values.stream().mapToInt(Integer::intValue).toArray();
    }
References Item().
copy()
Item com.runehive.game.world.items.Item.copy ()
A substitute for Object#clone() that creates another 'copy' of this instance.
The created copy safe meaning it does not hold any references to the original instance.
Returns
the copy of this instance that does not hold any references.
Reimplemented in com.runehive.content.store.StoreItem.
Definition at line 270 of file Item.java.
                       {
        return new Item(id, amount);
    }
References amount, and Item().
Referenced by com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), and com.runehive.content.preset.PresetManager.inventory().
createAndDecrement()
Item com.runehive.game.world.items.Item.createAndDecrement (int removeAmount)
Creates a new item with amount - removeAmount and the same identifier.
The returned Item does not hold any references to this one. It will also have a minimum amount of 1.
Parameters
removeAmount The amount to withdraw.
Returns
The newly incremented Item.
Definition at line 198 of file Item.java.
{
        if (removeAmount < 0) { // Same effect as incrementing.
            return createAndIncrement(-removeAmount);
        }
        int newAmount = amount - removeAmount;
        // Value too low, or an overflow.
        if (newAmount < 1 || newAmount > amount) {
            newAmount = 1;
        }
        Item clone = clone();
        clone.setAmount(newAmount);
        return clone;
    }
References amount, clone(), createAndIncrement(), and Item().
Referenced by createAndIncrement(), and com.runehive.game.world.items.containers.ItemContainer.remove().
createAndIncrement()
Item com.runehive.game.world.items.Item.createAndIncrement (int addAmount)
Creates a new item with amount + addAmount and the same identifier.
The returned Item does not hold any references to this one. It will also have a maximum amount of
Integer.MAX_VALUE.
Parameters
addAmount The amount to deposit.
Returns
The newly incremented Item.
Definition at line 174 of file Item.java.
{
        if (addAmount < 0) { // Same effect as decrementing.
            return createAndDecrement(Math.abs(addAmount));
        }
        int newAmount = amount + addAmount;
        if (newAmount < amount) { // An overflow.
            newAmount = Integer.MAX_VALUE;
        }
        Item item = clone();
        item.setAmount(newAmount);
        return item;
    }
References amount, clone(), createAndDecrement(), Item(), and setAmount().
Referenced by com.runehive.game.world.items.containers.ItemContainer.add(), createAndDecrement(), and com.runehive.game.world.items.containers.equipment.Equipment.equip().
createWithAmount()
Item com.runehive.game.world.items.Item.createWithAmount (int newAmount)
Creates a new item with newAmount and the same identifier as this instance.
The returned Item does not hold any references to this one unless amount == newAmount. It will throw an exception on overflows and negative values.
Parameters
newAmount The new amount to set.
Returns
The newly amount set Item.
Definition at line 158 of file Item.java.
{
        if (amount == newAmount) {
            return this;
        }
        return new Item(id, newAmount);
    }
References amount, and Item().
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), and com.runehive.game.world.items.containers.impl.LootingBag.withdrawBank().
createWithId()
Item com.runehive.game.world.items.Item.createWithId (int newId)
Creates a new item with newId and the same amount as this instance.
The returned Item does not hold any references to this one unless id == newId. It will throw an exception on an invalid id.
Parameters
newId The new id to set.
Returns
The newly id set Item.
Definition at line 142 of file Item.java.
{
        if (id == newId) {
            return this;
        }
        return new Item(newId, amount);
    }
References amount, and Item().
Referenced by com.runehive.game.world.items.containers.ItemContainer.replace(), and com.runehive.game.world.items.containers.ItemContainer.replace().
decrementAmount()
final void com.runehive.game.world.items.Item.decrementAmount ()
Decrements the amount by 1.
Definition at line 284 of file Item.java.
{
        decrementAmountBy(1);
    }
References decrementAmountBy().
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
decrementAmountBy()
final void com.runehive.game.world.items.Item.decrementAmountBy (int amount)
Decrements the amount by amount @endiliteral.
Parameters
amount the amount to decrement by.
Definition at line 302 of file Item.java.
{
        if ((this.amount - amount) < 1) {
            this.amount = 0;
        } else {
            this.amount -= amount;
        }
    }
References amount.
Referenced by decrementAmount(), com.runehive.content.store.impl.PersonalStore.remove(), and com.runehive.content.store.impl.DefaultStore.StoreRestockTask.restock().
equalIds()
boolean com.runehive.game.world.items.Item.equalIds (Item other)
Definition at line 461 of file Item.java.
{
        return other != null && id == other.id;
    }
References id, and Item().
Referenced by com.runehive.content.skill.impl.crafting.Crafting.useItem(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
equals()
boolean com.runehive.game.world.items.Item.equals (Object obj)
Definition at line 475 of file Item.java.
{
        if (obj instanceof Item) {
            Item other = (Item) obj;
            return other.id == id && other.amount == amount;
        }
        return false;
    }
References amount, and Item().
Referenced by com.runehive.game.world.items.ground.GroundItem.equals(), com.runehive.content.itemaction.impl.MagmaHelm.itemOnItem(), com.runehive.content.itemaction.impl.SerpentineHelm.itemOnItem(), and com.runehive.content.itemaction.impl.TanzaniteHelm.itemOnItem().
getAmount()
final int com.runehive.game.world.items.Item.getAmount ()
Gets the quantity of this item.
Returns
the quantity.
Definition at line 342 of file Item.java.
{
        return amount;
    }
References amount.
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.add(), com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.ground.GroundItem.addToRegion(), com.runehive.content.RoyaltyProgram.append(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.check(), com.runehive.game.world.items.ItemComparator.compare(), com.runehive.game.world.items.containers.ItemContainer.computeIndexCount(), com.runehive.content.skill.impl.magic.RunePouch.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.content.store.StoreItem.copy(), com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.impl.LostUntradeables.deposit(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.depositAll(), com.runehive.game.world.items.containers.bank.Bank.depositeEquipment(), com.runehive.game.world.items.containers.bank.Bank.depositeInventory(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), com.runehive.game.world.items.containers.impl.LootingBag.depositMenu(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.activity.impl.duelarena.DuelUtils.getItemNames(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.preset.PresetManager.inventory(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.itemaction.impl.ToxicBlowpipe.load(), com.runehive.content.bot.BotUtility.logLoot(), com.runehive.content.store.impl.PersonalStore.onPurchase(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.onRefresh(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.store.Store.purchase(), com.runehive.content.store.impl.PersonalStore.remove(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.content.store.impl.DefaultStore.StoreRestockTask.restock(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop(), com.runehive.game.world.items.containers.ItemContainer.search(), com.runehive.content.store.Store.sell(), com.runehive.game.world.items.containers.bank.Bank.sendValue(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.clanchannel.channel.ClanChannel.splitLoot(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.skill.impl.slayer.Slayer.store(), com.runehive.content.itemaction.impl.MagmaHelm.uncharge(), com.runehive.content.itemaction.impl.SerpentineHelm.uncharge(), com.runehive.content.itemaction.impl.TanzaniteHelm.uncharge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.uncharge(), com.runehive.content.gambling.GambleManager.withdraw(), com.runehive.game.world.items.containers.bank.Bank.withdraw(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdraw(), and com.runehive.game.world.items.containers.impl.LootingBag.withdrawBank().
getAttackAnimation()
OptionalInt com.runehive.game.world.items.Item.getAttackAnimation (FightType type)
Definition at line 405 of file Item.java.
{
        return getDefinition().getAttackAnimation(type);
    }
References getDefinition().
getBaseValue()
int com.runehive.game.world.items.Item.getBaseValue ()
Definition at line 425 of file Item.java.
{
        return getDefinition().getBaseValue();
    }
References getDefinition().
getBlockAnimation()
OptionalInt com.runehive.game.world.items.Item.getBlockAnimation ()
Definition at line 409 of file Item.java.
{
        return getDefinition().getBlockAnimation();
    }
References getDefinition().
Referenced by com.runehive.game.world.entity.combat.CombatUtil.getBlockAnimation().
getBonus()
int com.runehive.game.world.items.Item.getBonus (int index)
Definition at line 457 of file Item.java.
{
        return getDefinition().getBonuses()[index];
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.addBonus(), and com.runehive.game.world.items.containers.equipment.Equipment.removeBonus().
getBonuses()
int[] com.runehive.game.world.items.Item.getBonuses ()
Definition at line 453 of file Item.java.
{
        return getDefinition().getBonuses();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.addBonus(), and com.runehive.game.world.items.containers.equipment.Equipment.removeBonus().
getDefinition()
ItemDefinition com.runehive.game.world.items.Item.getDefinition ()
Gets the item definition for the item identifier.
Returns
the item definition.
Definition at line 315 of file Item.java.
{
        return ItemDefinition.get(id);
    }
References com.runehive.game.world.items.ItemDefinition.get().
Referenced by com.runehive.content.overrides.Overrides.determineContainer(), com.runehive.content.overrides.Overrides.drawText(), com.runehive.content.overrides.Overrides.equipOverride(), getAttackAnimation(), getBaseValue(), getBlockAnimation(), getBonus(), getBonuses(), getDestroyMessage(), getEquipmentType(), getHighAlch(), getLowAlch(), getName(), getNotedId(), getRangedDefinition(), getRequirements(), getRunAnimation(), getStandAnimation(), getStreetValue(), getUnnotedId(), getValue(), getValue(), getWalkAnimation(), getWeaponInterface(), getWeight(), isDestroyable(), isEquipable(), isNoteable(), isNoted(), isStackable(), isTradeable(), isTwoHanded(), noted(), com.runehive.content.overrides.Overrides.removeOverride(), com.runehive.content.tradingpost.TradingPost.selectItemToList(), com.runehive.content.overrides.Overrides.toggleConfig(), unnoted(), valid(), and com.runehive.content.gambling.GambleManager.withdraw().
getDestroyMessage()
String com.runehive.game.world.items.Item.getDestroyMessage ()
Definition at line 360 of file Item.java.
{
        return getDefinition().getDestroyMessage();
    }
References getDefinition(), and com.runehive.game.world.items.ItemDefinition.getDestroyMessage().
getEquipmentType()
EquipmentType com.runehive.game.world.items.Item.getEquipmentType ()
Definition at line 441 of file Item.java.
{
        return getDefinition().getEquipmentType();
    }
References getDefinition().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.game.world.items.containers.equipment.Equipment.manualWear(), com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), com.runehive.game.world.items.containers.equipment.Equipment.onRemove(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.start(), and com.runehive.game.world.items.containers.equipment.Equipment.unEquip().
getHighAlch()
int com.runehive.game.world.items.Item.getHighAlch ()
Definition at line 429 of file Item.java.
{
        return getDefinition().getHighAlch();
    }
References getDefinition().
Referenced by com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute().
getId()
final int com.runehive.game.world.items.Item.getId ()
Gets the identification of this item.
Returns
the identification.
Definition at line 324 of file Item.java.
{
        return id;
    }
References id.
Referenced by com.runehive.content.prestige.Prestige.activatePerk(), com.runehive.content.store.impl.PersonalStore.add(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.add(), com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.content.skill.impl.crafting.Crafting.addCraftable(), com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), com.runehive.content.RoyaltyProgram.append(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.assign(), com.runehive.content.pet.Pets.buyInsurance(), com.runehive.game.world.items.containers.impl.LostUntradeables.claim(), com.runehive.content.mysterybox.MysteryBoxManager.click(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.hunter.Hunter.clickItem(), com.runehive.content.skill.impl.prayer.BoneSacrifice.clickItem(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickItem(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.game.world.items.ItemComparator.compare(), com.runehive.game.world.items.containers.ItemContainer.computeIdForIndex(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.skill.impl.magic.RunePouch.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.content.store.StoreItem.copy(), com.runehive.content.skill.impl.magic.RunePouch.death(), com.runehive.content.skill.impl.runecrafting.RunecraftPouch.death(), com.runehive.content.overrides.Overrides.deleteOverride(), com.runehive.content.skill.impl.magic.RunePouch.deposit(), com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.DonatorDeposit.deposit(), com.runehive.game.world.items.containers.impl.LootingBag.deposit(), com.runehive.game.world.items.containers.impl.LostUntradeables.deposit(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositeInventory(), com.runehive.content.itemaction.impl.CelestialRing.drop(), com.runehive.content.itemaction.impl.CrawsBow.drop(), com.runehive.content.itemaction.impl.ThammaronsSceptre.drop(), com.runehive.content.itemaction.impl.ViggorasChainmace.drop(), com.runehive.content.itemaction.ItemActionRepository.drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.content.itemaction.impl.CelestialRing.equipment(), com.runehive.content.itemaction.impl.CrawsBow.equipment(), com.runehive.content.itemaction.impl.ThammaronsSceptre.equipment(), com.runehive.content.itemaction.impl.TridentOfTheSeas.equipment(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.equipment(), com.runehive.content.itemaction.impl.ViggorasChainmace.equipment(), com.runehive.content.itemaction.ItemActionRepository.equipment(), com.runehive.content.overrides.Overrides.equipOverride(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.game.world.entity.combat.ranged.RangedAmmunition.find(), com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), com.runehive.content.ItemCreation.CreationData.forItem(), com.runehive.content.ItemCreation.CreationData.forItems(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.skill.impl.smithing.SmeltingData.getDefinitionByItem(), com.runehive.content.consume.PotionData.getReplacementItem(), com.runehive.game.world.entity.mob.player.PlayerAssistant.getStrategy(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMessages(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handleSecondOption(), com.runehive.net.packet.in.ItemOptionPacketListener.handleThirdOption(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.content.wintertodt.Wintertodt.healPyromancer(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.hit(), com.runehive.content.itemaction.impl.CelestialRing.inventory(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), com.runehive.content.itemaction.impl.CrawsBow.inventory(), com.runehive.content.itemaction.impl.ThammaronsSceptre.inventory(), com.runehive.content.itemaction.impl.TridentOfTheSeas.inventory(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.inventory(), com.runehive.content.itemaction.impl.ViggorasChainmace.inventory(), com.runehive.content.itemaction.ItemActionRepository.inventory(), com.runehive.content.preset.PresetManager.inventory(), com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.isDragonArrow(), com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.game.world.items.containers.equipment.Equipment.isItem(), com.runehive.game.world.items.containers.equipment.Equipment.isWearingDFS(), com.runehive.content.itemaction.impl.CelestialRing.itemOnItem(), com.runehive.content.itemaction.impl.CrawsBow.itemOnItem(), com.runehive.content.itemaction.impl.MagmaHelm.itemOnItem(), com.runehive.content.itemaction.impl.SerpentineHelm.itemOnItem(), com.runehive.content.itemaction.impl.TanzaniteHelm.itemOnItem(), com.runehive.content.itemaction.impl.ThammaronsSceptre.itemOnItem(), com.runehive.content.itemaction.impl.ToxicBlowpipe.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem(), com.runehive.content.itemaction.impl.TridentOfTheSwamp.itemOnItem(), com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem(), com.runehive.content.itemaction.ItemActionRepository.itemOnItem(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.itemOnObject(), com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.itemOnObject(), com.runehive.content.skill.impl.farming.patches.WaterablePatch.itemOnObject(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.itemaction.impl.ToxicBlowpipe.load(), com.runehive.content.bot.BotUtility.logLoot(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.content.pet.Pets.onDeath(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.bot.PlayerBot.pot(), com.runehive.content.store.impl.SkillcapeStore.purchase(), com.runehive.content.store.Store.purchase(), com.runehive.game.world.entity.combat.magic.MagicRune.remove(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.content.store.impl.DefaultStore.StoreRestockTask.restock(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop(), com.runehive.game.world.items.containers.ItemContainer.search(), com.runehive.content.tradingpost.TradingPost.selectItemToList(), com.runehive.content.store.Store.sell(), com.runehive.content.dialogue.ChatBoxItemDialogue.sendInterface(), com.runehive.content.dialogue.DialogueFactory.sendItem(), com.runehive.content.store.Store.sendSellValue(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.emote.Emote.skillcape(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start(), com.runehive.game.world.items.containers.equipment.Equipment.unEquip(), com.runehive.content.itemaction.impl.ToxicBlowpipe.unload(), com.runehive.content.emote.EmoteHandler.updateSkillcape(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.useItem(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), com.runehive.content.skill.impl.crafting.Crafting.useItem(), com.runehive.content.skill.impl.crafting.Crafting.useItem(), com.runehive.content.skill.impl.crafting.impl.Stringing.useItem(), com.runehive.content.skill.impl.firemaking.Firemaking.useItem(), com.runehive.content.skill.impl.fletching.Fletching.useItem(), com.runehive.content.skill.impl.herblore.Herblore.useItem(), com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem(), com.runehive.content.gambling.GambleManager.withdraw(), com.runehive.game.world.items.containers.bank.Bank.withdraw(), com.runehive.game.world.items.containers.bank.DonatorDeposit.withdraw(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdraw(), and com.runehive.game.world.items.containers.impl.LootingBag.withdrawBank().
getLowAlch()
int com.runehive.game.world.items.Item.getLowAlch ()
Definition at line 433 of file Item.java.
{
        return getDefinition().getLowAlch();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.ItemComparator.compare(), and com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute().
getName()
String com.runehive.game.world.items.Item.getName ()
Definition at line 356 of file Item.java.
{
        return getDefinition().getName();
    }
References getDefinition(), and com.runehive.game.world.items.ItemDefinition.getName().
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.content.pet.Pets.buyInsurance(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), com.runehive.content.skill.impl.HarvestingSkillAction.canRun(), com.runehive.content.itemaction.impl.ToxicBlowpipe.check(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), com.runehive.game.world.items.containers.impl.LootingBag.deposit(), com.runehive.game.world.entity.mob.player.PlayerAssistant.destroyItem(), com.runehive.content.itemaction.impl.SerpentineHelm.dismantle(), com.runehive.content.DropDisplay.display(), com.runehive.content.overrides.Overrides.drawText(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.content.activity.impl.duelarena.DuelUtils.getItemNames(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), com.runehive.game.world.entity.mob.player.PlayerAssistant.handleDestroyItem(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMessages(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMiscDrops(), com.runehive.content.activity.impl.duelarena.DuelUtils.hasFunWeapon(), com.runehive.content.itemaction.impl.ClanShowcaseBox.inventory(), com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), com.runehive.content.itemaction.impl.ToxicBlowpipe.load(), com.runehive.content.overrides.Overrides.manageItemDialogue(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.content.RoyaltyProgram.open(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.content.itemaction.impl.MagmaHelm.restore(), com.runehive.content.itemaction.impl.TanzaniteHelm.restore(), com.runehive.content.skill.impl.woodcutting.BirdsNest.search(), com.runehive.content.store.Store.sell(), com.runehive.content.store.Store.sendPurchaseValue(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.content.store.Store.sendSellValue(), com.runehive.content.skill.impl.crafting.impl.Spinning.spin(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.skill.impl.slayer.Slayer.store(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.update(), com.runehive.content.skill.impl.crafting.Crafting.useItem(), com.runehive.content.skill.impl.fletching.Fletching.useItem(), and com.runehive.content.skill.impl.herblore.Herblore.useItem().
getNotedId()
int com.runehive.game.world.items.Item.getNotedId ()
Definition at line 413 of file Item.java.
{
        return getDefinition().getNotedId();
    }
References getDefinition().
Referenced by noted(), and com.runehive.game.world.items.containers.bank.Bank.withdraw().
getRangedDefinition()
Optional< RangedWeaponDefinition > com.runehive.game.world.items.Item.getRangedDefinition ()
Definition at line 445 of file Item.java.
{
        return getDefinition().getRangedDefinition();
    }
References getDefinition().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.getStrategy(), com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), com.runehive.game.world.items.containers.equipment.Equipment.onRemove(), and com.runehive.game.world.items.containers.equipment.Equipment.updateRangedEquipment().
getRequirements()
int[] com.runehive.game.world.items.Item.getRequirements ()
Definition at line 449 of file Item.java.
{
        return getDefinition().getRequirements();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.equip().
getRunAnimation()
int com.runehive.game.world.items.Item.getRunAnimation ()
Definition at line 400 of file Item.java.
{
        return getDefinition().getRunAnimation();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation().
getSellValue()
int com.runehive.game.world.items.Item.getSellValue ()
Definition at line 116 of file Item.java.
{
        return (int) Math.floor(getValue() / 2);
    }
References getValue().
Referenced by com.runehive.content.store.Store.sell(), and com.runehive.content.store.Store.sendSellValue().
getStandAnimation()
int com.runehive.game.world.items.Item.getStandAnimation ()
Definition at line 392 of file Item.java.
{
        return getDefinition().getStandAnimation();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation().
getStreetValue()
int com.runehive.game.world.items.Item.getStreetValue ()
Definition at line 421 of file Item.java.
{
        return getDefinition().getStreetValue();
    }
References getDefinition().
getUnnotedId()
int com.runehive.game.world.items.Item.getUnnotedId ()
Definition at line 417 of file Item.java.
{
        return getDefinition().getUnnotedId();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), and unnoted().
getValue() [1/2]
int com.runehive.game.world.items.Item.getValue ()
Gets the value for this item.
Returns
the value of this item.
Definition at line 125 of file Item.java.
{
        ItemDefinition def = getDefinition();
        if (def == null) {
            return 0;
        }
        return def.getValue();
    }
References getDefinition().
Referenced by getSellValue(), and com.runehive.content.store.StoreItem.getShopValue().
getValue() [2/2]
int com.runehive.game.world.items.Item.getValue (PriceType type)
Gets the value for this item.
Parameters
type the type to derive the value from.
Returns
the value of this item.
Definition at line 98 of file Item.java.
{
        ItemDefinition def = getDefinition();
        if (def == null) {
            return 0;
        }
        switch (type) {
            case VALUE:
                return def.getValue();
            case HIGH_ALCH_VALUE:
                return def.getHighAlch();
            case LOW_ALCH_VALUE:
                return def.getLowAlch();
        }
        return 0;
    }
References getDefinition().
Referenced by com.runehive.game.world.items.ItemComparator.compare(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMessages(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.store.impl.PersonalStore.onPurchase(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.onRefresh(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.game.world.items.containers.bank.Bank.sendValue(), and com.runehive.content.clanchannel.channel.ClanChannel.splitLoot().
getWalkAnimation()
int com.runehive.game.world.items.Item.getWalkAnimation ()
Definition at line 396 of file Item.java.
{
        return getDefinition().getWalkAnimation();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation().
getWeaponInterface()
WeaponInterface com.runehive.game.world.items.Item.getWeaponInterface ()
Definition at line 488 of file Item.java.
{
        return getDefinition().getWeaponInterface();
    }
References getDefinition().
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), and com.runehive.content.overrides.Overrides.getFightType().
getWeight()
double com.runehive.game.world.items.Item.getWeight ()
Definition at line 437 of file Item.java.
{
        return getDefinition().getWeight();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.ItemComparator.compare().
hashCode()
int com.runehive.game.world.items.Item.hashCode ()
Definition at line 484 of file Item.java.
{
        return amount << 16 | id & 0xFFFF;
    }
References amount.
incrementAmount()
final void com.runehive.game.world.items.Item.incrementAmount ()
Increments the amount by 1.
Definition at line 277 of file Item.java.
{
        incrementAmountBy(1);
    }
References incrementAmountBy().
Referenced by com.runehive.content.store.impl.DefaultStore.StoreRestockTask.restock().
incrementAmountBy()
final void com.runehive.game.world.items.Item.incrementAmountBy (int amount)
Increments the amount by amount.
Parameters
amount the amount to increment by.
Definition at line 293 of file Item.java.
{
        this.amount += amount;
    }
References amount.
Referenced by com.runehive.game.world.items.containers.bank.Bank.deposit(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), incrementAmount(), and com.runehive.content.itemaction.impl.ToxicBlowpipe.load().
isDestroyable()
boolean com.runehive.game.world.items.Item.isDestroyable ()
Definition at line 388 of file Item.java.
{
        return getDefinition().isDestroyable();
    }
References getDefinition().
isEquipable()
boolean com.runehive.game.world.items.Item.isEquipable ()
Definition at line 376 of file Item.java.
{
        return getDefinition().getEquipmentType() != EquipmentType.NOT_WIELDABLE || getDefinition().isEquipable();
    }
References getDefinition(), and com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), and com.runehive.game.world.items.containers.equipment.Equipment.manualWear().
isNoteable()
boolean com.runehive.game.world.items.Item.isNoteable ()
Definition at line 368 of file Item.java.
{
        return getDefinition().isNoteable();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.bank.Bank.withdraw().
isNoted()
boolean com.runehive.game.world.items.Item.isNoted ()
Definition at line 372 of file Item.java.
{
        return getDefinition().isNoted();
    }
References getDefinition(), and com.runehive.game.world.items.ItemDefinition.isNoted().
Referenced by com.runehive.game.world.items.containers.bank.Bank.deposit(), and com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop().
isStackable()
boolean com.runehive.game.world.items.Item.isStackable ()
Definition at line 364 of file Item.java.
{
        return getDefinition().isStackable();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.ground.GroundItem.addToRegion(), com.runehive.game.world.items.containers.bank.DonatorDeposit.deposit(), com.runehive.content.teleport.TeleportHandler.display(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.onRefresh(), com.runehive.content.store.Store.purchase(), com.runehive.content.store.Store.sell(), com.runehive.content.store.impl.PersonalStore.setValue(), com.runehive.content.skill.impl.slayer.Slayer.store(), com.runehive.game.world.items.containers.bank.DonatorDeposit.withdraw(), and com.runehive.game.world.items.containers.impl.LootingBag.withdrawBank().
isTradeable()
boolean com.runehive.game.world.items.Item.isTradeable ()
Definition at line 384 of file Item.java.
{
        return getDefinition().isTradeable();
    }
References getDefinition().
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.add(), com.runehive.game.world.items.containers.impl.LootingBag.allowed(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.deposit(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMessages(), com.runehive.content.tradingpost.TradingPost.selectItemToList(), com.runehive.content.store.Store.sell(), and com.runehive.content.store.Store.sendSellValue().
isTwoHanded()
boolean com.runehive.game.world.items.Item.isTwoHanded ()
Definition at line 380 of file Item.java.
{
        return getDefinition().isTwoHanded();
    }
References getDefinition().
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.equip(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
matchesId()
boolean com.runehive.game.world.items.Item.matchesId (int id)
Definition at line 465 of file Item.java.
{
        return this.id == id;
    }
References id.
Referenced by com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.MagmaHelm.drop(), com.runehive.content.itemaction.impl.SerpentineHelm.drop(), com.runehive.content.itemaction.impl.TanzaniteHelm.drop(), com.runehive.game.world.entity.mob.player.PlayerAssistant.handleDestroyItem(), com.runehive.game.world.items.containers.equipment.Equipment.hasAccumulator(), com.runehive.game.world.items.containers.equipment.Equipment.hasAssembler(), com.runehive.game.world.items.containers.equipment.Equipment.hasAttractor(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.hit(), com.runehive.content.itemaction.impl.SerpentineHelm.inventory(), com.runehive.content.itemaction.impl.SerpentineHelm.itemOnItem(), com.runehive.content.skill.impl.farming.patches.DiseasablePatch.itemOnObject(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.itemOnObject(), com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), com.runehive.game.world.items.containers.equipment.Equipment.onRemove(), com.runehive.content.store.Store.purchase(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.items.containers.ItemContainer.replace(), and com.runehive.game.world.items.containers.ItemContainer.replace().
noted()
Item com.runehive.game.world.items.Item.noted ()
Gets the item note item.
Returns
The item note id, or the original item item if it cannot be noted.
Definition at line 88 of file Item.java.
{
        return new Item(getDefinition().getNotedId(), amount);
    }
References amount, getDefinition(), getNotedId(), and Item().
setAmount()
final void com.runehive.game.world.items.Item.setAmount (int amount)
Sets the quantity of this item.
Parameters
amount the new quantity of this item.
Definition at line 351 of file Item.java.
{
        if (amount < 0) amount = 0;
        this.amount = amount;
    }
References amount.
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.add(), com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.content.itemaction.impl.MagmaHelm.charge(), com.runehive.content.itemaction.impl.SerpentineHelm.charge(), com.runehive.content.itemaction.impl.TanzaniteHelm.charge(), com.runehive.content.itemaction.impl.ToxicBlowpipe.charge(), createAndIncrement(), com.runehive.game.world.items.containers.bank.Bank.depositeEquipment(), com.runehive.game.world.items.containers.bank.Bank.depositeInventory(), com.runehive.game.world.items.containers.bank.Bank.depositFromNothing(), com.runehive.content.teleport.TeleportHandler.display(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.clanchannel.channel.ClanChannel.getShowcaseItems(), com.runehive.content.preset.PresetManager.inventory(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.store.Store.purchase(), com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove(), com.runehive.content.store.Store.sell(), com.runehive.content.store.impl.PersonalStore.setValue(), and com.runehive.content.skill.impl.slayer.Slayer.store().
setId()
final void com.runehive.game.world.items.Item.setId (int id)
Sets the identification of this item.
Parameters
id the new identification of this item.
Definition at line 333 of file Item.java.
{
        this.id = id;
    }
References id.
toString()
final String com.runehive.game.world.items.Item.toString ()
Definition at line 470 of file Item.java.
{
        return String.format("item[id=%d amount=%d]", id, amount);
    }
References amount.
unnoted()
Item com.runehive.game.world.items.Item.unnoted ()
Gets the unnoted item.
Returns
the unnoted item.
Definition at line 78 of file Item.java.
{
        return new Item(getDefinition().getUnnotedId(), amount);
    }
References amount, getDefinition(), getUnnotedId(), and Item().
Referenced by com.runehive.content.preset.PresetManager.inventory().
valid()
boolean com.runehive.game.world.items.Item.valid (Item item) static
Determines if item is valid.
In other words, determines if item is not null and the Item#id.
Parameters
item the item to determine if valid.
Returns
true if the item is valid, false otherwise.
Definition at line 259 of file Item.java.
{
        return item != null && item.id > 0 && item.id < ItemDefinition.DEFINITIONS.length && item.getDefinition() != null;
    }
References getDefinition(), and Item().
Referenced by com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.add(), com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.content.store.Store.purchase(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove(), and com.runehive.content.store.Store.sell().
Member Data Documentation
amount
int com.runehive.game.world.items.Item.amount private
The quantity of this item.
Definition at line 31 of file Item.java.
Referenced by copy(), createAndDecrement(), createAndIncrement(), createWithAmount(), createWithId(), decrementAmountBy(), equals(), getAmount(), hashCode(), incrementAmountBy(), Item(), Item(), Item(), com.runehive.content.mysterybox.MysteryItem.MysteryItem(), com.runehive.content.mysterybox.MysteryItem.MysteryItem(), noted(), setAmount(), com.runehive.content.store.StoreItem.StoreItem(), com.runehive.content.store.StoreItem.StoreItem(), com.runehive.content.store.StoreItem.StoreItem(), toString(), and unnoted().
id
int com.runehive.game.world.items.Item.id private
The identification of this item.
Definition at line 26 of file Item.java.
Referenced by equalIds(), getId(), Item(), Item(), Item(), Item(), matchesId(), com.runehive.content.mysterybox.MysteryItem.MysteryItem(), setId(), com.runehive.content.store.StoreItem.StoreItem(), and com.runehive.content.store.StoreItem.StoreItem().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/Item.java