RuneHive-Game: com.runehive.game.world.entity.MobList< E extends Mob > Class Template Reference
com.runehive.game.world.entity.MobList< E extends Mob > Class Template Reference
An Iterable implementation acting as a repository that holds instances of Entitys.
Classes
class EntityListIterator
An Iterator implementation designed specifically MobLists.
Public Member Functions
boolean add (E entity)
Adds entity to this list.
int capacity ()
void clear ()
Calls withdraw() on every single Entity in this list.
boolean contains (E entity)
Determines if this list contains entity.
E element (int index)
Retrieves the element on index, the only difference between this and get(int) is that this method throws an exception if no entity is found on index.
List< E > findAll (Predicate<? super E > filter)
Finds all elements that match filter.
Optional< E > findFirst (Predicate<? super E > filter)
Finds the first element that matches filter.
Optional< E > findLast (Predicate<? super E > filter)
Finds the last element that matches filter.
void forEach (Consumer<? super E > action)
E get (int index)
Retrieves the element on index.
boolean isEmpty ()
boolean isFull ()
Iterator< E > iterator ()
MobList (int capacity)
Creates a new MobList.
Stream< E > parallelStream ()
int remaining ()
boolean remove (E entity)
Removes entity from this list.
void remove (int index)
Removes a Entity from this list at index.
void shuffle ()
Shuffles this collections list of entities.
int size ()
Spliterator< E > spliterator ()
Stream< E > stream ()
E[] toArray ()
Please note that this function does not give direct access to the backing array but instead creates a shallow copy.
Private Attributes
final E[] entities
The entities contained within this list.
final TreeSet< Integer > indices
A queue that acts as a fs for indices.
int largestIndex
The largest used index.
int size
The internal size of this list.
Detailed Description
An Iterable implementation acting as a repository that holds instances of Entitys.
Indexes are cached to avoid expensive lookups whenever a new entity is added.
Parameters
<E> The specific type of EntityNode being managed within this list.
Author
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
lare96 http://github.org/lare96
Definition at line 26 of file MobList.java.
Constructor & Destructor Documentation
MobList()
com.runehive.game.world.entity.MobList< E extends Mob >.MobList (int capacity)
Creates a new MobList.
Parameters
capacity The length of the backing array plus 1.
Definition at line 114 of file MobList.java.
{
        entities = (E[]) new Mob[++capacity];
        Stream<Integer> indexStream = IntStream.rangeClosed(1, capacity).boxed();
        indices = new TreeSet<>(indexStream.collect(Collectors.toList()));
    }
References capacity(), entities, indices, and MobList().
Referenced by com.runehive.game.world.entity.MobList< E extends Mob >.EntityListIterator< E extends Mob >.EntityListIterator(), and MobList().
Member Function Documentation
add()
boolean com.runehive.game.world.entity.MobList< E extends Mob >.add (E entity)
Adds entity to this list.
Will throw an exception if this list is full, or if the entity being added has a state of ACTIVE.
Parameters
entity The entity to deposit to this list.
Definition at line 240 of file MobList.java.
{
        Integer index = indices.pollFirst();
        if (index == null || index == capacity()) {
            return false;
        }
        if (index > largestIndex) {
            largestIndex = index;
        }
        entities[index] = entity;
        entity.setIndex(index);
        entity.setListIndex(index);
        size++;
        return true;
    }
References capacity(), entities, indices, largestIndex, and size.
capacity()
int com.runehive.game.world.entity.MobList< E extends Mob >.capacity ()
Returns
The length of the backing array.
Definition at line 349 of file MobList.java.
{
        return entities.length;
    }
References entities.
Referenced by add(), findLast(), isFull(), MobList(), and remaining().
clear()
void com.runehive.game.world.entity.MobList< E extends Mob >.clear ()
Calls withdraw() on every single Entity in this list.
Definition at line 366 of file MobList.java.
{
        forEach(this::remove);
    }
References forEach().
contains()
boolean com.runehive.game.world.entity.MobList< E extends Mob >.contains (E entity)
Determines if this list contains entity.
Parameters
entity The entity to check for.
Returns
true if entity is contained, false otherwise.
Definition at line 314 of file MobList.java.
{
        return entity != null && entity.equals(get(entity.getListIndex()));
    }
element()
E com.runehive.game.world.entity.MobList< E extends Mob >.element (int index)
Retrieves the element on index, the only difference between this and get(int) is that this method throws an exception if no entity is found on index.
Parameters
index The index.
Returns
The retrieved element, will never be null.
Definition at line 301 of file MobList.java.
{
        E entity = get(index);
        checkArgument(entity != null, "index -> null EntityNode");
        return entity;
    }
findAll()
List< E > com.runehive.game.world.entity.MobList< E extends Mob >.findAll (Predicate<? super E > filter)
Finds all elements that match filter.
Parameters
filter The filter to apply to the elements of this sequence.
Returns
An ArrayList containing the elements.
Definition at line 213 of file MobList.java.
{
        List<E> list = new ArrayList<>();
        for (E e : this) {
            if (filter.test(e)) {
                list.add(e);
            }
        }
        return list;
    }
findFirst()
Optional< E > com.runehive.game.world.entity.MobList< E extends Mob >.findFirst (Predicate<? super E > filter)
Finds the first element that matches filter.
Parameters
filter The filter to apply to the elements of this sequence.
Returns
An Optional containing the element, or an empty
Optional if no element was found.
Definition at line 178 of file MobList.java.
{
        for (E e : this) {
            if (filter.test(e)) {
                return Optional.of(e);
            }
        }
        return Optional.empty();
    }
findLast()
Optional< E > com.runehive.game.world.entity.MobList< E extends Mob >.findLast (Predicate<? super E > filter)
Finds the last element that matches filter.
Parameters
filter The filter to apply to the elements of this sequence.
Returns
An Optional containing the element, or an empty
Optional if no element was found.
Definition at line 194 of file MobList.java.
{
        for (int index = capacity(); index > 1; index--) {
            E entity = entities[index];
            if (entity == null) {
                continue;
            }
            if (filter.test(entity)) {
                return Optional.of(entity);
            }
        }
        return Optional.empty();
    }
References capacity(), and entities.
forEach()
void com.runehive.game.world.entity.MobList< E extends Mob >.forEach (Consumer<? super E > action)
This implementation will exclude all elements with a value of
null to avoid NullPointerExceptions.
UPDATED: Now uses a shuffle_list to battle PID. This means that all entities are always processed in an random order instead of having higher priority than other entities because of a higher PID.
Definition at line 162 of file MobList.java.
{
        int index = 0;
        for (E e : entities) {
            if (e == null) continue;
            action.accept(e);
            if (++index >= size) return;
        }
    }
References entities, and size.
Referenced by clear(), com.runehive.game.engine.GameEngine.runOneIteration(), com.runehive.game.engine.sync.ParallelClientSynchronizer.synchronize(), and com.runehive.game.engine.sync.SequentialClientSynchronizer.synchronize().
get()
E com.runehive.game.world.entity.MobList< E extends Mob >.get (int index)
Retrieves the element on index.
Parameters
index The index.
Returns
The retrieved element, possibly null.
Definition at line 289 of file MobList.java.
{
        return entities[index];
    }
References entities.
isEmpty()
boolean com.runehive.game.world.entity.MobList< E extends Mob >.isEmpty ()
Returns
true if this list is empty, false otherwise.
Definition at line 328 of file MobList.java.
{
        return size() == 0;
    }
References size.
isFull()
boolean com.runehive.game.world.entity.MobList< E extends Mob >.isFull ()
Returns
true if this list is full, false otherwise.
Definition at line 321 of file MobList.java.
{
        return size() == capacity();
    }
References capacity(), and size.
iterator()
Iterator< E > com.runehive.game.world.entity.MobList< E extends Mob >.iterator ()
Definition at line 121 of file MobList.java.
{
        return new EntityListIterator<>(this);
    }
parallelStream()
Stream< E > com.runehive.game.world.entity.MobList< E extends Mob >.parallelStream ()
Returns
The Stream that will traverse over this list in parallel. Automatically excludes null values.
Definition at line 382 of file MobList.java.
{
        Spliterator<E> split = Spliterators.spliterator(entities, spliterator().characteristics() | Spliterator.IMMUTABLE);
        return StreamSupport.stream(split, true).filter(Objects::nonNull);
    }
References entities, and spliterator().
remaining()
int com.runehive.game.world.entity.MobList< E extends Mob >.remaining ()
Returns
The amount of free spaces remaining in this list.
Definition at line 342 of file MobList.java.
{
        return capacity() - size();
    }
References capacity(), and size.
remove() [1/2]
boolean com.runehive.game.world.entity.MobList< E extends Mob >.remove (E entity)
Removes entity from this list.
Will throw an exception if the entity being removed does not have a state of ACTIVE.
Parameters
entity The entity to withdraw from this list.
Definition at line 264 of file MobList.java.
{
        checkArgument(entity.getListIndex() != -1, "index == -1");
        indices.add(entity.getListIndex());
        entities[entity.getListIndex()] = null;
        size--;
        return true;
    }
References entities, indices, and size.
remove() [2/2]
void com.runehive.game.world.entity.MobList< E extends Mob >.remove (int index)
Removes a Entity from this list at index.
Will throw an exception if the entity being removed does not have a state of
ACTIVE.
Parameters
index The index to withdraw the Entity at.
Definition at line 279 of file MobList.java.
{
        remove(entities[index]);
    }
References entities.
shuffle()
void com.runehive.game.world.entity.MobList< E extends Mob >.shuffle ()
Shuffles this collections list of entities.
Definition at line 126 of file MobList.java.
{
        if (size < 2) {
            return;
        }
        for (int index = largestIndex; index > 1; index--) {
            int first = index - 1;
            int second = RandomUtils.inclusive(1, index);
            if (first == second) continue;
            E tmp = entities[first];
            entities[first] = entities[second];
            entities[second] = tmp;
            if (entities[first] != null) {
                entities[first].setListIndex(first);
            }
            if (entities[second] != null) {
                entities[second].setListIndex(second);
            }
        }
    }
References entities, com.runehive.util.RandomUtils.inclusive(), largestIndex, and size.
size()
int com.runehive.game.world.entity.MobList< E extends Mob >.size ()
Returns
The amount of entities in this list.
Definition at line 335 of file MobList.java.
                      {
        return size;
    }
References size.
spliterator()
Spliterator< E > com.runehive.game.world.entity.MobList< E extends Mob >.spliterator ()
As a rule of thumb, stream() and parallelStream() should always be used instead unless absolutely needed.
Definition at line 230 of file MobList.java.
{
        return Spliterators.spliterator(entities, Spliterator.ORDERED | Spliterator.DISTINCT);
    }
References entities.
Referenced by parallelStream(), and stream().
stream()
Stream< E > com.runehive.game.world.entity.MobList< E extends Mob >.stream ()
Returns
The Stream that will traverse over this list. Automatically excludes null values.
Definition at line 374 of file MobList.java.
{
        return StreamSupport.stream(spliterator(), false).filter(Objects::nonNull);
    }
References spliterator().
toArray()
E[] com.runehive.game.world.entity.MobList< E extends Mob >.toArray ()
Please note that this function does not give direct access to the backing array but instead creates a shallow copy.
Returns
The shallow copy of the backing array.
Definition at line 359 of file MobList.java.
{
        return Arrays.copyOf(entities, entities.length);
    }
References entities.
Member Data Documentation
entities
final E [] com.runehive.game.world.entity.MobList< E extends Mob >.entities private
The entities contained within this list.
Definition at line 97 of file MobList.java.
Referenced by add(), capacity(), findLast(), forEach(), get(), MobList(), parallelStream(), remove(), remove(), shuffle(), spliterator(), and toArray().
indices
final TreeSet<Integer> com.runehive.game.world.entity.MobList< E extends Mob >.indices private
A queue that acts as a fs for indices.
Definition at line 100 of file MobList.java.
Referenced by add(), MobList(), and remove().
largestIndex
int com.runehive.game.world.entity.MobList< E extends Mob >.largestIndex private
The largest used index.
Definition at line 106 of file MobList.java.
Referenced by add(), and shuffle().
size
int com.runehive.game.world.entity.MobList< E extends Mob >.size private
The internal size of this list.
Definition at line 103 of file MobList.java.
Referenced by add(), forEach(), isEmpty(), isFull(), remaining(), remove(), shuffle(), size(), and com.runehive.game.engine.sync.ParallelClientSynchronizer.synchronize().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/MobList.java