RuneHive-Game: com.runehive.game.world.region.RegionBlock Class Reference
com.runehive.game.world.region.RegionBlock Class Reference
Represents a single region.
Public Member Functions
Set< GroundItem > getGroundItems (Position position)
Gets a Set of GroundItems.
Collection< Npc > getNpcs ()
Collection< Player > getPlayers ()
Package Functions
void addGroundItem (GroundItem item)
Adds a ground item to this block.
void addNpc (Npc npc)
Adds an npc to this block.
void addObject (GameObject object)
Adds an object to this block.
void addPlayer (Player player)
Adds a player to this block.
boolean containsNpc (Npc npc)
boolean containsObject (GameObject object)
boolean containsObject (Position position)
boolean containsPlayer (Player player)
GameObject getCustomObject (int id, Position position)
int getFlags (int x, int y)
Gets a single tile in this region from the specified height, x and y coordinates.
GameObject getGameObject (int id, Position position)
List< GameObject > getGameObjects (Position position)
GroundItem getGroundItem (int id, Position position)
The method that retrieves the item with id on position.
void removeGroundItem (GroundItem item)
Adds a ground item to this block.
void removeNpc (Npc npc)
Removes an npc from this block.
void removeObject (GameObject object)
Removes an object from this block.
void removePlayer (Player player)
Removes a player from this block.
void sendGameObjects (Player player)
void sendGroundItems (Player player)
The method which handles updating when the specified player enters a new region.
void setFlags (int x, int y, int flag)
Gets a single tile in this region from the specified height, x and y coordinates.
void skip (GameObject gameObject)
void unsetFlags (int x, int y, int flag)
Gets a single tile in this region from the specified height, x and y coordinates.
Private Member Functions
Map< Position, Set< GroundItem > > getGroundItems ()
Map< Position, List< GameObject > > getObjects ()
Deque< GameObject > getRemovedObjects ()
Private Attributes
int[] flags
The clipping flags within the region.
Map< Position, Set< GroundItem > > groundItems
A list of ground items in this region.
Deque< Npc > npcs = new ConcurrentLinkedDeque<>()
A list of npcs in this region.
Map< Position, List< GameObject > > objects
A list of objects in this region.
Deque< Player > players = new ConcurrentLinkedDeque<>()
A list of players in this region.
Deque< GameObject > skipped
A list of removed objects in this region.
Detailed Description
Represents a single region.
Author
Graham Edgecombe
Definition at line 24 of file RegionBlock.java.
Member Function Documentation
addGroundItem()
void com.runehive.game.world.region.RegionBlock.addGroundItem (GroundItem item) package
Adds a ground item to this block.
Definition at line 117 of file RegionBlock.java.
{
        Set<GroundItem> items = getGroundItems(item.getPosition());
        int index = 0;
        for (GroundItem other : items) {
            if (other.getIndex() + 1 > index) {
                index = other.getIndex() + 1;
            }
        }
        item.setIndex(index);
        items.add(item);
        getGroundItems().put(item.getPosition(), items);
    }
References getGroundItems(), com.runehive.game.world.entity.Entity.getPosition(), and com.runehive.game.world.entity.Entity.setIndex().
Referenced by com.runehive.game.world.region.Region.addGroundItem().
addNpc()
void com.runehive.game.world.region.RegionBlock.addNpc (Npc npc) package
Adds an npc to this block.
Definition at line 93 of file RegionBlock.java.
{
        npcs.add(npc);
    }
References npcs.
Referenced by com.runehive.game.world.region.Region.addNpc().
addObject()
void com.runehive.game.world.region.RegionBlock.addObject (GameObject object) package
Adds an object to this block.
Definition at line 103 of file RegionBlock.java.
{
        List<GameObject> objs = getObjects().getOrDefault(object.getPosition(), new LinkedList<>());
        if (objs.add(object))
            getObjects().put(object.getPosition(), objs);
    }
References getObjects().
Referenced by com.runehive.game.world.region.Region.addObject().
addPlayer()
void com.runehive.game.world.region.RegionBlock.addPlayer (Player player) package
Adds a player to this block.
Definition at line 83 of file RegionBlock.java.
{
        players.add(player);
    }
References players.
Referenced by com.runehive.game.world.region.Region.addPlayer().
containsNpc()
boolean com.runehive.game.world.region.RegionBlock.containsNpc (Npc npc) package
Returns
true if this region contains this npc
Definition at line 142 of file RegionBlock.java.
{
        return npcs.contains(npc);
    }
References npcs.
Referenced by com.runehive.game.world.region.Region.containsNpc().
containsObject() [1/2]
boolean com.runehive.game.world.region.RegionBlock.containsObject (GameObject object) package
Returns
true if object is in region
Definition at line 152 of file RegionBlock.java.
{
        List<GameObject> objs = getObjects().get(object.getPosition());
        return objs != null && objs.contains(object);
    }
References getObjects().
Referenced by com.runehive.game.world.region.Region.containsObject(), and com.runehive.game.world.region.Region.containsObject().
containsObject() [2/2]
boolean com.runehive.game.world.region.RegionBlock.containsObject (Position position) package
Returns
true if position is occupied by object
Definition at line 158 of file RegionBlock.java.
{
        List<GameObject> objs = getObjects().get(position);
        return objs != null && !objs.isEmpty();
    }
References getObjects().
containsPlayer()
boolean com.runehive.game.world.region.RegionBlock.containsPlayer (Player player) package
Returns
true if this region contains this player
Definition at line 147 of file RegionBlock.java.
{
        return players.contains(player);
    }
References players.
Referenced by com.runehive.game.world.region.Region.containsPlayer().
getCustomObject()
GameObject com.runehive.game.world.region.RegionBlock.getCustomObject (int id, Position position) package
Definition at line 172 of file RegionBlock.java.
{
        Set<Map.Entry<Position, List<GameObject>>> entrySet = getObjects().entrySet();
        for (Map.Entry<Position, List<GameObject>> entry : entrySet) {
            for (GameObject object : entry.getValue()) {
                if (!(object instanceof CustomGameObject))
                    continue;
                CustomGameObject obj = (CustomGameObject) object;
                if (!obj.isValid()) {
                    continue;
                }
                System.err.println("haha we got it " + obj.getId());
                return obj;
            }
        }
        return null;
    }
References com.runehive.game.world.object.GameObject.getId(), getObjects(), and com.runehive.game.world.entity.Entity.isValid().
Referenced by com.runehive.game.world.region.Region.getCustomObject().
getFlags()
int com.runehive.game.world.region.RegionBlock.getFlags (int x, int y) package
Gets a single tile in this region from the specified height, x and y coordinates.
Parameters
x The x coordinate.
y The y coordinate.
Returns
The tile in this region for the specified attributes.
Definition at line 254 of file RegionBlock.java.
{
        if (flags == null)
            flags = new int[SIZE * SIZE];
        return flags[x + y * SIZE];
    }
References flags.
Referenced by com.runehive.game.world.region.Region.getFlags().
getGameObject()
GameObject com.runehive.game.world.region.RegionBlock.getGameObject (int id, Position position) package
Definition at line 163 of file RegionBlock.java.
{
        for (GameObject object : getGameObjects(position)) {
            if (object.getId() == id) {
                return object;
            }
        }
        return null;
    }
References getGameObjects().
Referenced by com.runehive.game.world.region.Region.getGameObject().
getGameObjects()
List< GameObject > com.runehive.game.world.region.RegionBlock.getGameObjects (Position position) package
Definition at line 189 of file RegionBlock.java.
{
        return getObjects().getOrDefault(position, Collections.emptyList());
    }
References getObjects().
Referenced by getGameObject(), and com.runehive.game.world.region.Region.getObjects().
getGroundItem()
GroundItem com.runehive.game.world.region.RegionBlock.getGroundItem (int id, Position position) package
The method that retrieves the item with id on position.
Parameters
id the identifier to retrieve the item with.
position the position to retrieve the item on.
Returns
the item instance wrapped in an optional, or an empty optional if no item is found.
Definition at line 73 of file RegionBlock.java.
{
        for (GroundItem item : getGroundItems(position)) {
            if (item.isRegistered() && item.item.matchesId(id)) {
                return item;
            }
        }
        return null;
    }
References getGroundItems().
Referenced by com.runehive.game.world.region.Region.getGroundItem().
getGroundItems() [1/2]
Map< Position, Set< GroundItem > > com.runehive.game.world.region.RegionBlock.getGroundItems () private
Definition at line 228 of file RegionBlock.java.
{
        if (groundItems == null)
            groundItems = new ConcurrentHashMap<>();
        return groundItems;
    }
References groundItems.
Referenced by addGroundItem(), getGroundItem(), getGroundItems(), and removeGroundItem().
getGroundItems() [2/2]
Set< GroundItem > com.runehive.game.world.region.RegionBlock.getGroundItems (Position position)
Gets a Set of GroundItems.
If none then creating the set.
Parameters
position the position to grab from.
Returns
the set of item nodes on the specified position.
Definition at line 61 of file RegionBlock.java.
{
        return getGroundItems().getOrDefault(position, ConcurrentHashMap.newKeySet());
    }
References getGroundItems().
Referenced by com.runehive.game.world.region.Region.getGroundItems(), and sendGroundItems().
getNpcs()
Collection< Npc > com.runehive.game.world.region.RegionBlock.getNpcs ()
Returns
the npcs in this block
Definition at line 50 of file RegionBlock.java.
{
        return npcs;
    }
References npcs.
Referenced by com.runehive.game.world.region.Region.getNpcs().
getObjects()
Map< Position, List< GameObject > > com.runehive.game.world.region.RegionBlock.getObjects () private
Definition at line 234 of file RegionBlock.java.
{
        if (objects == null)
            objects = new ConcurrentHashMap<>();
        return objects;
    }
References objects.
Referenced by addObject(), containsObject(), containsObject(), getCustomObject(), getGameObjects(), removeObject(), and sendGameObjects().
getPlayers()
Collection< Player > com.runehive.game.world.region.RegionBlock.getPlayers ()
Returns
the players in this block
Definition at line 45 of file RegionBlock.java.
{
        return players;
    }
References players.
Referenced by com.runehive.game.world.region.Region.getPlayers().
getRemovedObjects()
Deque< GameObject > com.runehive.game.world.region.RegionBlock.getRemovedObjects () private
Definition at line 240 of file RegionBlock.java.
{
        if (skipped == null)
            skipped = new ConcurrentLinkedDeque<>();
        return skipped;
    }
References skipped.
Referenced by sendGameObjects(), and skip().
removeGroundItem()
void com.runehive.game.world.region.RegionBlock.removeGroundItem (GroundItem item) package
Adds a ground item to this block.
Definition at line 131 of file RegionBlock.java.
{
        Set<GroundItem> items = getGroundItems(item.getPosition());
        items.remove(item);
        if (items.isEmpty()) {
            getGroundItems().remove(item.getPosition());
        } else {
            getGroundItems().put(item.getPosition(), items);
        }
    }
References getGroundItems(), and com.runehive.game.world.entity.Entity.getPosition().
Referenced by com.runehive.game.world.region.Region.removeGroundItem().
removeNpc()
void com.runehive.game.world.region.RegionBlock.removeNpc (Npc npc) package
Removes an npc from this block.
Definition at line 98 of file RegionBlock.java.
{
        npcs.remove(npc);
    }
References npcs.
Referenced by com.runehive.game.world.region.Region.removeNpc().
removeObject()
void com.runehive.game.world.region.RegionBlock.removeObject (GameObject object) package
Removes an object from this block.
Definition at line 110 of file RegionBlock.java.
{
        List<GameObject> objs = getObjects().get(object.getPosition());
        if (objs != null)
            objs.remove(object);
    }
References getObjects().
Referenced by com.runehive.game.world.region.Region.removeObject().
removePlayer()
void com.runehive.game.world.region.RegionBlock.removePlayer (Player player) package
Removes a player from this block.
Definition at line 88 of file RegionBlock.java.
{
        players.remove(player);
    }
References players.
Referenced by com.runehive.game.world.region.Region.removePlayer().
sendGameObjects()
void com.runehive.game.world.region.RegionBlock.sendGameObjects (Player player) package
Definition at line 193 of file RegionBlock.java.
{
        for (GameObject object : getRemovedObjects()) {
            player.send(new SendRemoveObject(object));
        }
        Set<Map.Entry<Position, List<GameObject>>> entrySet = getObjects().entrySet();
        for (Map.Entry<Position, List<GameObject>> entry : entrySet) {
            for (GameObject object : entry.getValue()) {
                if (!(object instanceof CustomGameObject))
                    continue;
                CustomGameObject obj = (CustomGameObject) object;
                if (!obj.isValid())
                    continue;
                player.send(new SendAddObject(obj));
            }
        }
    }
References getObjects(), getRemovedObjects(), com.runehive.game.world.entity.Entity.isValid(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.game.world.region.Region.sendGameObjects().
sendGroundItems()
void com.runehive.game.world.region.RegionBlock.sendGroundItems (Player player) package
The method which handles updating when the specified player enters a new region.
Definition at line 214 of file RegionBlock.java.
{
        for (Map.Entry<Position, Set<GroundItem>> entry : getGroundItems().entrySet()) {
            for (GroundItem groundItem : entry.getValue()) {
                if (!groundItem.isRegistered())
                    continue;
                if (!groundItem.canSee(player))
                    continue;
                player.send(new SendGroundItem(groundItem));
            }
        }
    }
References getGroundItems(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.game.world.region.Region.sendGroundItems().
setFlags()
void com.runehive.game.world.region.RegionBlock.setFlags (int x, int y, int flag) package
Gets a single tile in this region from the specified height, x and y coordinates.
Parameters
x The x coordinate.
y The y coordinate.
Returns
The tile in this region for the specified attributes.
Definition at line 268 of file RegionBlock.java.
{
        if (flags == null)
            flags = new int[SIZE * SIZE];
        flags[x + y * SIZE] |= flag;
    }
References flags.
Referenced by com.runehive.game.world.region.Region.setFlags().
skip()
void com.runehive.game.world.region.RegionBlock.skip (GameObject gameObject) package
Definition at line 288 of file RegionBlock.java.
{
        getRemovedObjects().add(gameObject);
    }
References getRemovedObjects().
Referenced by com.runehive.game.world.region.Region.skip().
unsetFlags()
void com.runehive.game.world.region.RegionBlock.unsetFlags (int x, int y, int flag) package
Gets a single tile in this region from the specified height, x and y coordinates.
Parameters
x The x coordinate.
y The y coordinate.
Returns
The tile in this region for the specified attributes.
Definition at line 282 of file RegionBlock.java.
{
        if (flags == null)
            flags = new int[SIZE * SIZE];
        flags[x + y * SIZE] &= ~flag;
    }
References flags.
Referenced by com.runehive.game.world.region.Region.unsetFlags().
Member Data Documentation
flags
int [] com.runehive.game.world.region.RegionBlock.flags private
The clipping flags within the region.
Definition at line 27 of file RegionBlock.java.
Referenced by getFlags(), setFlags(), and unsetFlags().
groundItems
Map<Position, Set<GroundItem> > com.runehive.game.world.region.RegionBlock.groundItems private
A list of ground items in this region.
Definition at line 42 of file RegionBlock.java.
Referenced by getGroundItems().
npcs
Deque<Npc> com.runehive.game.world.region.RegionBlock.npcs = new ConcurrentLinkedDeque<>() private
A list of npcs in this region.
Definition at line 33 of file RegionBlock.java.
Referenced by addNpc(), containsNpc(), getNpcs(), and removeNpc().
objects
Map<Position, List<GameObject> > com.runehive.game.world.region.RegionBlock.objects private
A list of objects in this region.
Definition at line 36 of file RegionBlock.java.
Referenced by getObjects().
players
Deque<Player> com.runehive.game.world.region.RegionBlock.players = new ConcurrentLinkedDeque<>() private
A list of players in this region.
Definition at line 30 of file RegionBlock.java.
Referenced by addPlayer(), containsPlayer(), getPlayers(), and removePlayer().
skipped
Deque<GameObject> com.runehive.game.world.region.RegionBlock.skipped private
A list of removed objects in this region.
Definition at line 39 of file RegionBlock.java.
Referenced by getRemovedObjects().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/region/RegionBlock.java