RuneHive-Game: com.runehive.content.itemaction.impl.DragonfireShield Class Reference
com.runehive.content.itemaction.impl.DragonfireShield Class Reference
Public Member Functions
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
boolean drop (Player player, Item item)
boolean itemOnItem (Player player, Item first, Item second)
String message (Item item)
The message of the action.
String toString ()
Private Member Functions
void empty (Player player)
void inspect (Player player)
Detailed Description
Definition at line 10 of file DragonfireShield.java.
Member Function Documentation
empty()
void com.runehive.content.itemaction.impl.DragonfireShield.empty (Player player) private
Definition at line 27 of file DragonfireShield.java.
{
        if (player.dragonfireCharges > 0) {
            player.dragonfireCharges = 0;
            player.graphic(1160);
            player.inventory.replace(11283, 11284, true);
            player.message("You clear your remaining charges.");
        } else {
            player.message("You have no remaining charges.");
        }
    }
References com.runehive.game.world.entity.mob.player.Player.dragonfireCharges, com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.items.containers.ItemContainer.replace().
Referenced by inventory().
equipment()
boolean com.runehive.content.itemaction.impl.DragonfireShield.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 43 of file DragonfireShield.java.
{
        if (opcode == 1) {
            long remaining = System.currentTimeMillis() - player.dragonfireUsed;
            if (remaining < 120_000) {
                player.message("My shield still needs " + (120 - remaining / 1000) + " seconds to recharge.");
                return true;
            }
            if (player.dragonfireCharges == 0) {
                player.message("You have no charges to do this!");
                return true;
            }
            Mob defender = player.getCombat().getDefender();
            if (defender == null && player.getCombat().isAttacking()) {
                defender = player.getCombat().getLastVictim();
            }
            if (defender == null && player.getCombat().isUnderAttack()) {
                defender = player.getCombat().getLastAggressor();
            }
            if (defender == null) {
                player.message("You are not in combat with anything...");
                return true;
            }
            if (defender.isDead() || defender.getCurrentHealth() == 0) {
                player.message("He dead tho...");
                return true;
            }
            player.dragonfireUsed = System.currentTimeMillis();
            final Combat<Player> combat = player.getCombat();
            combat.performChecks(defender);
            combat.submitStrategy(defender, DragonfireShieldStrategy.get());
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.dragonfireCharges, com.runehive.game.world.entity.mob.player.Player.dragonfireUsed, com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.Mob.isDead(), and com.runehive.game.world.entity.mob.player.Player.message().
inspect()
void com.runehive.content.itemaction.impl.DragonfireShield.inspect (Player player) private
Definition at line 38 of file DragonfireShield.java.
{
        player.message("You have " + player.dragonfireCharges + " charges remaining.");
    }
References com.runehive.game.world.entity.mob.player.Player.dragonfireCharges, and com.runehive.game.world.entity.mob.player.Player.message().
Referenced by inventory().
inventory()
boolean com.runehive.content.itemaction.impl.DragonfireShield.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 18 of file DragonfireShield.java.
{
        if (opcode == 2) {
            inspect(player);
        } else if (opcode == 3) {
            empty(player);
        }
        return true;
    }
References empty(), and inspect().
name()
String com.runehive.content.itemaction.impl.DragonfireShield.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 13 of file DragonfireShield.java.
{
        return "Dragonfire shield";
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/DragonfireShield.java