RuneHive-Game: com.runehive.content.store.currency.impl.ItemCurrency Class Reference
com.runehive.content.store.currency.impl.ItemCurrency Class Reference
The currency that provides basic functionality for all tangible currencies.
Public Member Functions
boolean canRecieveCurrency (Player player)
Determines if the currency can be received when player's inventory is full.
int currencyAmount (Player player)
The method that retrieves the amount of currency player currently has.
ItemCurrency (int itemId)
Constructs a new ItemCurrency.
void recieveCurrency (Player player, int amount)
The method executed when the currency is given to player.
boolean takeCurrency (Player player, int amount)
The method executed when the currency is taken from player.
boolean tangible ()
Determines if this currency is tangible.
String toString ()
Gets the name of the currency.
Public Attributes
final int itemId
The item id for this currency.
Detailed Description
The currency that provides basic functionality for all tangible currencies.
Author
lare96 http://github.com/lare96
Definition at line 13 of file ItemCurrency.java.
Constructor & Destructor Documentation
ItemCurrency()
com.runehive.content.store.currency.impl.ItemCurrency.ItemCurrency (int itemId)
Constructs a new ItemCurrency.
Definition at line 19 of file ItemCurrency.java.
{
        this.itemId = itemId;
    }
References itemId.
Member Function Documentation
canRecieveCurrency()
boolean com.runehive.content.store.currency.impl.ItemCurrency.canRecieveCurrency (Player player)
Determines if the currency can be received when player's inventory is full.
Parameters
player the player to determine this for.
Returns
true if the currency can be recieved, false otherwise.
Implements com.runehive.content.store.currency.Currency.
Definition at line 44 of file ItemCurrency.java.
{
        return player.inventory.contains(itemId);
    }
References com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.inventory, and itemId.
currencyAmount()
int com.runehive.content.store.currency.impl.ItemCurrency.currencyAmount (Player player)
The method that retrieves the amount of currency player currently has.
Parameters
player the player who's currency amount will be determined.
Returns
the amount of the currency the player has.
Implements com.runehive.content.store.currency.Currency.
Definition at line 39 of file ItemCurrency.java.
{
        return player.inventory.computeAmountForId(itemId);
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.entity.mob.player.Player.inventory, and itemId.
recieveCurrency()
void com.runehive.content.store.currency.impl.ItemCurrency.recieveCurrency (Player player, int amount)
The method executed when the currency is given to player.
Parameters
player the player the currency is given to.
amount the amount of currency that is given.
Implements com.runehive.content.store.currency.Currency.
Definition at line 34 of file ItemCurrency.java.
{
        player.inventory.add(new Item(itemId, amount));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.Player.inventory, and itemId.
takeCurrency()
boolean com.runehive.content.store.currency.impl.ItemCurrency.takeCurrency (Player player, int amount)
The method executed when the currency is taken from player.
Parameters
player the player the currency is taken from.
amount the amount of currency that is taken.
Implements com.runehive.content.store.currency.Currency.
Definition at line 29 of file ItemCurrency.java.
{
        return player.inventory.remove(new Item(itemId, amount));
    }
References com.runehive.game.world.entity.mob.player.Player.inventory, itemId, and com.runehive.game.world.items.containers.ItemContainer.remove().
tangible()
boolean com.runehive.content.store.currency.impl.ItemCurrency.tangible ()
Determines if this currency is tangible.
Returns
true if this currency is tangible, false otherwise.
Implements com.runehive.content.store.currency.Currency.
Definition at line 24 of file ItemCurrency.java.
{
        return true;
    }
toString()
String com.runehive.content.store.currency.impl.ItemCurrency.toString ()
Gets the name of the currency.
Implements com.runehive.content.store.currency.Currency.
Definition at line 49 of file ItemCurrency.java.
{
        return ItemDefinition.get(itemId).getName();
    }
References com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), and itemId.
Member Data Documentation
itemId
final int com.runehive.content.store.currency.impl.ItemCurrency.itemId
The item id for this currency.
Definition at line 16 of file ItemCurrency.java.
Referenced by canRecieveCurrency(), currencyAmount(), ItemCurrency(), recieveCurrency(), takeCurrency(), and toString().
The documentation for this class was generated from the following file:
java/com/runehive/content/store/currency/impl/ItemCurrency.java