RuneHive-Game: com.runehive.content.combat.cannon.CannonManager Class Reference
com.runehive.content.combat.cannon.CannonManager Class Reference
Classes
enum Rotation
enum Setup
Static Public Member Functions
static void drop (Player player, Cannon cannon)
static void empty (Player player)
static Projectile getCannonFire ()
static Npc[] getNpc (Cannon cannon)
static void load (Player player)
static void logout (Player player)
static void pickup (Player player)
static void rotate (Cannon cannon)
static void test (Player player)
Static Package Attributes
static Map< String, Cannon > ACTIVE_CANNONS = new HashMap<>()
Detailed Description
Definition at line 18 of file CannonManager.java.
Member Function Documentation
drop()
void com.runehive.content.combat.cannon.CannonManager.drop (Player player, Cannon cannon) static
Definition at line 46 of file CannonManager.java.
{
        if (ACTIVE_CANNONS.containsKey(player.getName())) {
            player.send(new SendMessage("You already have a cannon active!"));
            return;
        }
        if(Area.inCatacombs(player)) {
            player.send(new SendMessage("You cannot set up a cannon here!"));
            return;
        }
        if (cannon.getStage().ordinal() != 0) {
            player.send(new SendMessage("You have already started setting up a cannon!"));
            return;
        }
        for (Cannon other : ACTIVE_CANNONS.values()) {
            if (other.getPosition().isWithinDistance(player.getPosition(), 5)) {
                player.send(new SendMessage("You are trying to build too close to another cannon!"));
                return;
            }
        }
        World.schedule(new CannonBuild(player, cannon));
    }
References ACTIVE_CANNONS, com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Area.inCatacombs(), com.runehive.game.world.World.schedule(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by test().
empty()
void com.runehive.content.combat.cannon.CannonManager.empty (Player player) static
Definition at line 97 of file CannonManager.java.
{
        Cannon cannon = ACTIVE_CANNONS.get(player.getName());
        if (cannon == null) {
            player.send(new SendMessage("This is not your cannon!"));
            return;
        }
        if (!cannon.getOwner().equalsIgnoreCase(player.getName())) {
            player.send(new SendMessage("This is not your cannon!"));
            return;
        }
        if(cannon.getAmmunition() != 0)
            player.inventory.add(new Item(2, cannon.getAmmunition()));
        cannon.setFiring(false);
        cannon.setAmmunition(0);
    }
References ACTIVE_CANNONS, com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, and com.runehive.game.world.entity.mob.player.Player.send().
getCannonFire()
Projectile com.runehive.content.combat.cannon.CannonManager.getCannonFire () static
Definition at line 180 of file CannonManager.java.
{
        Projectile p = new Projectile(53);
        p.setStartHeight(50);
        p.setEndHeight(50);
        return p;
    }
References com.runehive.game.Projectile.setEndHeight(), and com.runehive.game.Projectile.setStartHeight().
Referenced by com.runehive.content.combat.cannon.CannonFireAction.execute().
getNpc()
Npc[] com.runehive.content.combat.cannon.CannonManager.getNpc (Cannon cannon) static
Definition at line 187 of file CannonManager.java.
{
        ArrayList<Npc> attack = new ArrayList<>();
        for (Npc npc : World.getNpcs()) {
            if (npc == null) {
                continue;
            }
            if (!Utility.withinDistance(npc, cannon, Region.VIEW_DISTANCE)) {
                continue;
            }
            if (!npc.definition.isAttackable()) {
                continue;
            }
            attack.add(npc);
        }
        Npc[] npc = new Npc[attack.size()];
        for (int i = 0; i < npc.length; i++) {
            npc[i] = attack.get(i);
        }
        return npc;
    }
References com.runehive.game.world.World.getNpcs(), com.runehive.game.world.entity.Entity.length, com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinDistance().
Referenced by com.runehive.content.combat.cannon.CannonFireAction.execute().
load()
void com.runehive.content.combat.cannon.CannonManager.load (Player player) static
Definition at line 134 of file CannonManager.java.
{
        Cannon cannon = ACTIVE_CANNONS.get(player.getName());
        if (cannon == null) {
            player.send(new SendMessage("This is not your cannon!"));
            return;
        }
        if (!cannon.getOwner().equalsIgnoreCase(player.getName())) {
            player.send(new SendMessage("This is not your cannon!"));
            return;
        }
        if (!player.inventory.contains(2)) {
            player.send(new SendMessage("You do not have any Cannon balls."));
            return;
        }
        int needed = 30 - cannon.getAmmunition();
        if (needed == 0) {
            player.send(new SendMessage("Your cannon is full."));
            return;
        }
        int cannon_balls = player.inventory.computeAmountForId(2);
        if (cannon_balls <= needed) {
            player.inventory.remove(2, cannon_balls);
            player.send(new SendMessage("You load the last of your cannon balls"));
            cannon.setAmmunition(cannon.getAmmunition() + cannon_balls);
        } else {
            player.inventory.remove(2, needed);
            player.send(new SendMessage("You load " + needed + " balls into the cannon."));
            cannon.setAmmunition(cannon.getAmmunition() + needed);
        }
        if (cannon.isFiring()) {
            player.send(new SendMessage("The cannon is already firing!"));
            return;
        }
        cannon.setFiring(true);
        World.schedule(new CannonFireAction(player, cannon));
    }
References ACTIVE_CANNONS, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.World.schedule(), and com.runehive.game.world.entity.mob.player.Player.send().
logout()
void com.runehive.content.combat.cannon.CannonManager.logout (Player player) static
Definition at line 117 of file CannonManager.java.
{
        Cannon cannon = ACTIVE_CANNONS.get(player.getName());
        if(cannon == null) return;
        if(cannon.getAmmunition() != 0)
            player.inventory.add(new Item(2, cannon.getAmmunition()));
        int[] ids = { 6, 8, 10, 12 };
        for(int index = 0; index < ids.length; index++)
            player.inventory.add(new Item(ids[index]));
        cannon.unregister();
        ACTIVE_CANNONS.remove(player.getName());
    }
References ACTIVE_CANNONS, com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.Player.getName(), and com.runehive.game.world.entity.mob.player.Player.inventory.
Referenced by com.runehive.game.task.impl.PlayerRemovalTask.tick().
pickup()
void com.runehive.content.combat.cannon.CannonManager.pickup (Player player) static
Definition at line 71 of file CannonManager.java.
{
        Cannon cannon = ACTIVE_CANNONS.get(player.getName());
        if (cannon == null) {
            player.send(new SendMessage("This is not your cannon!"));
            return;
        }
        if (!cannon.getOwner().equalsIgnoreCase(player.getName())) {
            player.send(new SendMessage("This is not your cannon!"));
            return;
        }
        player.animate(new Animation(827));
        if(cannon.getAmmunition() != 0)
            player.inventory.add(new Item(2, cannon.getAmmunition()));
        int[] ids = { 6, 8, 10, 12 };
        for(int index = 0; index < ids.length; index++)
            player.inventory.add(new Item(ids[index]));
        cannon.unregister();
        ACTIVE_CANNONS.remove(player.getName());
    }
References ACTIVE_CANNONS, com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, and com.runehive.game.world.entity.mob.player.Player.send().
rotate()
void com.runehive.content.combat.cannon.CannonManager.rotate (Cannon cannon) static
Definition at line 215 of file CannonManager.java.
{
        switch (cannon.getRotation()) {
        case NORTH:
            World.sendObjectAnimation(516, cannon.getObject());
            break;
        case NORTH_EAST:
            World.sendObjectAnimation(517, cannon.getObject());
            break;
        case EAST:
            World.sendObjectAnimation(518, cannon.getObject());
            break;
        case SOUTH_EAST:
            World.sendObjectAnimation(519, cannon.getObject());
            break;
        case SOUTH:
            World.sendObjectAnimation(520, cannon.getObject());
            break;
        case SOUTH_WEST:
            World.sendObjectAnimation(521, cannon.getObject());
            break;
        case WEST:
            World.sendObjectAnimation(514, cannon.getObject());
            break;
        case NORTH_WEST:
            World.sendObjectAnimation(515, cannon.getObject());
            break;
        }
    }
References com.runehive.game.world.World.sendObjectAnimation().
Referenced by com.runehive.content.combat.cannon.CannonFireAction.execute().
test()
void com.runehive.content.combat.cannon.CannonManager.test (Player player) static
Definition at line 42 of file CannonManager.java.
{
        drop(player, new Cannon(player.getName(), player.getPosition()));
    }
References drop(), com.runehive.game.world.entity.mob.player.Player.getName(), and com.runehive.game.world.entity.Entity.getPosition().
Member Data Documentation
ACTIVE_CANNONS
Map<String, Cannon> com.runehive.content.combat.cannon.CannonManager.ACTIVE_CANNONS = new HashMap<>() static package
Definition at line 20 of file CannonManager.java.
Referenced by drop(), empty(), load(), logout(), pickup(), and com.runehive.content.combat.cannon.CannonBuild.tick().
The documentation for this class was generated from the following file:
java/com/runehive/content/combat/cannon/CannonManager.java