RuneHive-Game: com.runehive.game.world.entity.combat.Combat< T extends Mob > Class Template Reference
com.runehive.game.world.entity.combat.Combat< T extends Mob > Class Template Reference
Public Member Functions
void addFirst (FormulaModifier<? super T > modifier)
void addListener (CombatListener<? super T > listener)
void addModifier (FormulaModifier<? super T > modifier)
boolean attack (Mob defender)
boolean canAttack (Mob defender)
void checkAggression (Position spawn)
boolean checkWithin (T attacker, Mob defender, CombatStrategy<? super T > strategy)
void clearDamageQueue ()
void clearIncoming ()
Combat (T attacker)
void compare (Mob mob, int level, Position spawn)
void cooldown (int delay)
long elapsedTime ()
CombatType getCombatType ()
int getCooldown ()
CombatDamage getDamageCache ()
Mob getDefender ()
FightStyle getFightStyle ()
FightType getFightType ()
Mob getLastAggressor ()
Mob getLastVictim ()
boolean hasPassed (int delay)
boolean inCombat ()
boolean inCombatWith (Mob mob)
boolean isAttacking ()
boolean isAttacking (Mob defender)
boolean isLastAggressor (Mob mob)
boolean isUnderAttack ()
boolean isUnderAttackBy (Mob attacker)
boolean isUnderAttackByNpc ()
boolean isUnderAttackByPlayer ()
int modifyAccuracy (Mob defender, int roll)
int modifyAggresiveBonus (Mob defender, int bonus)
int modifyAttackLevel (Mob defender, int level)
int modifyDamage (Mob defender, int damage)
int modifyDefenceLevel (Mob attacker, int level)
int modifyDefensive (Mob attacker, int roll)
int modifyDefensiveBonus (Mob attacker, int bonus)
int modifyMagicLevel (Mob defender, int level)
int modifyOffensiveBonus (Mob defender, int bonus)
int modifyRangedLevel (Mob defender, int level)
int modifyStrengthLevel (Mob defender, int level)
void onDamage (Hit hit)
void onDeath (Mob attacker, Hit hit)
void onKill (Mob defender, Hit hit)
void performChecks (final Mob defender)
void preDeath (Mob attacker, Hit hit)
void preKill (Mob defender, Hit hit)
void queueDamage (Hit hit)
void removeFirst ()
void removeListener (CombatListener<? super T > listener)
void removeModifier (FormulaModifier<? super T > modifier)
void reset ()
void reset (boolean force)
void resetTimers (int millis)
void setCombatType (CombatType type)
void setCooldown (int delay)
void setFightType (FightType type)
void submitHits (Mob defender, CombatHit... hits)
void submitStrategy (Mob defender, CombatStrategy<? super T > strategy)
void tick ()
Public Attributes
final Stopwatch lastBlocked = Stopwatch.start()
Private Member Functions
void attack (Mob defender, Hit hit, CombatStrategy<? super T > strategy)
void block (Mob attacker, Hit hit, CombatType combatType)
boolean canAttack (Mob defender, CombatStrategy<? super T > strategy)
boolean canOtherAttack (Mob attacker)
boolean checkDistances (Mob defender)
void finishIncoming (Mob attacker)
void finishOutgoing (Mob defender, CombatStrategy<? super T > strategy)
boolean hasPassed (Stopwatch timer, int delay)
void hit (Mob defender, Hit hit, CombatStrategy<? super T > strategy)
void hitsplat (Mob defender, Hit hit, CombatStrategy<? super T > strategy)
Task hitsplatTask (CombatData< T > data)
Task hitTask (CombatData< T > data)
void init (Mob defender, CombatStrategy<? super T > strategy)
void retaliate (Mob attacker)
boolean sendNextHitsplat ()
void start (Mob defender, CombatStrategy<? super T > strategy, Hit... hits)
void submitHits (Mob defender, CombatStrategy<? super T > strategy, CombatHit... hits)
void updateListeners ()
Private Attributes
final T attacker
final Deque< CombatData< T > > combatQueue = new ArrayDeque<>()
CombatType combatType
int cooldown
final CombatDamage damageCache = new CombatDamage()
final Deque< Hit > damageQueue = new ArrayDeque<>()
FightStyle fightStyle
FightType fightType
final CombatFormula< T > formula = new CombatFormula<>()
final int[] hitsplatCooldowns = new int[4]
Mob lastAggressor
final Stopwatch lastAttacked = Stopwatch.start()
Mob lastVictim
final Deque< CombatListener<? super T > > listeners = new ArrayDeque<>()
final Deque< CombatListener<? super T > > pendingAddition = new ArrayDeque<>()
final Deque< CombatListener<? super T > > pendingRemoval = new ArrayDeque<>()
CombatTarget target
Detailed Description
Definition at line 27 of file Combat.java.
Constructor & Destructor Documentation
Combat()
com.runehive.game.world.entity.combat.Combat< T extends Mob >.Combat (T attacker)
Definition at line 53 of file Combat.java.
{
        this.attacker = attacker;
        this.target = new CombatTarget(attacker);
        fightType = FightType.UNARMED_PUNCH;
    }
References attacker, fightType, and com.runehive.game.world.entity.combat.attack.FightType.UNARMED_PUNCH.
Member Function Documentation
addFirst()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.addFirst (FormulaModifier<? super T > modifier)
Definition at line 488 of file Combat.java.
{
        formula.addFirst(modifier);
    }
References formula.
addListener()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.addListener (CombatListener<? super T > listener)
Definition at line 496 of file Combat.java.
{
        if (listeners.contains(listener) || pendingAddition.contains(listener)) {
            return;
        }
//        System.out.println("[@Combat] added listener: " + listener.getClass().getSimpleName());
        pendingAddition.add(listener);
    }
References listeners, and pendingAddition.
addModifier()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.addModifier (FormulaModifier<? super T > modifier)
Definition at line 480 of file Combat.java.
{
        formula.add(modifier);
    }
References formula.
Referenced by submitHits(), and updateListeners().
attack() [1/2]
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack (Mob defender)
Definition at line 59 of file Combat.java.
{
        if (attacker.isPlayer()) {
            Player player = attacker.getPlayer();
            if (!player.interfaceManager.isMainClear() || !player.interfaceManager.isDialogueClear()) {
                player.interfaceManager.close();
            }
        }
        if (!canAttack(defender, attacker.getStrategy())) {
            attacker.face(defender.getPosition());
            attacker.movement.reset();
            target.resetTarget();
            return false;
        }
        target.setTarget(defender);
        attacker.attack(defender);
        return true;
    }
References attacker, canAttack(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.isDialogueClear(), com.runehive.game.world.entity.mob.player.InterfaceManager.isMainClear(), and target.
Referenced by retaliate(), and submitHits().
attack() [2/2]
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack (Mob defender, Hit hit, CombatStrategy<? super T > strategy) private
Definition at line 307 of file Combat.java.
{
        if (!CombatUtil.validateMobs(attacker, defender)) {
            combatQueue.removeIf(_hit -> _hit.getDefender() == defender);
            if (defender.inTeleport)
                defender.getCombat().damageQueue.clear();
            reset();
            return;
        }
        lastVictim = defender;
        lastAttacked.reset();
        attacker.action.reset();
        strategy.attack(attacker, defender, hit);
        listeners.forEach(listener -> listener.attack(attacker, defender, hit));
    }
References attacker, combatQueue, com.runehive.game.world.entity.mob.Mob.getCombat(), hit(), com.runehive.game.world.entity.mob.Mob.inTeleport, lastAttacked, lastVictim, listeners, reset(), and com.runehive.game.world.entity.combat.CombatUtil.validateMobs().
block()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.block (Mob attacker, Hit hit, CombatType combatType) private
Definition at line 324 of file Combat.java.
{
        T defender = this.attacker;
        lastBlocked.reset();
        lastAggressor = attacker;
        defender.action.reset();
        listeners.forEach(listener -> listener.block(attacker, defender, hit, combatType));
        defender.getStrategy().block(attacker, defender, hit, combatType);
        defender.getCombat().retaliate(attacker);
    }
References attacker, combatType, hit(), lastAggressor, lastBlocked, and listeners.
canAttack() [1/2]
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.canAttack (Mob defender)
Definition at line 240 of file Combat.java.
{
        if (!CombatUtil.validate(attacker, defender)) {
            return false;
        }
        if (!CombatUtil.canBasicAttack(attacker, defender)) {
            return false;
        }
        if (!attacker.getStrategy().canAttack(attacker, defender)) {
            return false;
        }
        for (CombatListener<? super T> listener : listeners) {
            if (!listener.canAttack(attacker, defender)) {
                return false;
            }
        }
        return defender.getCombat().canOtherAttack(attacker);
    }
References attacker, com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.game.world.entity.mob.Mob.getCombat(), listeners, and com.runehive.game.world.entity.combat.CombatUtil.validate().
Referenced by attack(), and submitStrategy().
canAttack() [2/2]
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.canAttack (Mob defender, CombatStrategy<? super T > strategy) private
Definition at line 258 of file Combat.java.
{
        if (!CombatUtil.validateMobs(attacker, defender)) {
            return false;
        }
        if (!CombatUtil.canAttack(attacker, defender)) {
            return false;
        }
        if (!strategy.canAttack(attacker, defender)) {
            return false;
        }
        for (CombatListener<? super T> listener : listeners) {
            if (!listener.canAttack(attacker, defender)) {
                return false;
            }
        }
        return defender.getCombat().canOtherAttack(attacker);
    }
References attacker, com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.mob.Mob.getCombat(), listeners, and com.runehive.game.world.entity.combat.CombatUtil.validateMobs().
canOtherAttack()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.canOtherAttack (Mob attacker) private
Definition at line 276 of file Combat.java.
{
        T defender = this.attacker;
        for (CombatListener<? super T> listener : listeners) {
            if (!listener.canOtherAttack(attacker, defender)) {
                return false;
            }
        }
        return defender.getStrategy().canOtherAttack(attacker, defender);
    }
References attacker, com.runehive.game.world.entity.mob.Mob.getStrategy(), and listeners.
checkAggression()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.checkAggression (Position spawn)
Definition at line 585 of file Combat.java.
{
        target.checkAggression(spawn);
    }
References target.
checkDistances()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.checkDistances (Mob defender) private
Definition at line 122 of file Combat.java.
{
        return defender != null && Utility.withinDistance(attacker, defender, Region.VIEW_DISTANCE);
    }
References attacker, com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinDistance().
Referenced by tick().
checkWithin()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.checkWithin (T attacker, Mob defender, CombatStrategy<? super T > strategy)
Definition at line 643 of file Combat.java.
{
        if (strategy == null || Utility.inside(attacker, defender)) {
            return false;
        }
        if (!strategy.withinDistance(attacker, defender)) {
            return false;
        }
        for (CombatListener<? super T> listener : listeners) {
            if (!listener.withinDistance(attacker, defender))
                return false;
        }
        return true;
    }
References attacker, com.runehive.util.Utility.inside(), and listeners.
Referenced by submitStrategy().
clearDamageQueue()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.clearDamageQueue ()
Definition at line 227 of file Combat.java.
{
        damageQueue.clear();
    }
References damageQueue.
clearIncoming()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.clearIncoming ()
Definition at line 512 of file Combat.java.
{
        combatQueue.clear();
    }
References combatQueue.
compare()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.compare (Mob mob, int level, Position spawn)
Definition at line 581 of file Combat.java.
{
        target.compare(mob, level, spawn);
    }
References target.
cooldown()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.cooldown (int delay)
Definition at line 231 of file Combat.java.
{
        if (cooldown < delay)
            cooldown = delay;
    }
References cooldown.
elapsedTime()
long com.runehive.game.world.entity.combat.Combat< T extends Mob >.elapsedTime ()
Definition at line 632 of file Combat.java.
{
        long attacked = lastAttacked.elapsedTime();
        long blocked = lastBlocked.elapsedTime();
        return Math.max(attacked, blocked);
    }
References lastAttacked, and lastBlocked.
Referenced by hasPassed().
finishIncoming()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.finishIncoming (Mob attacker) private
Definition at line 461 of file Combat.java.
{
        T defender = this.attacker;
        defender.getStrategy().finishIncoming(attacker, defender);
        listeners.forEach(listener -> listener.finishIncoming(attacker, defender));
    }
References attacker, com.runehive.game.world.entity.mob.Mob.getStrategy(), and listeners.
finishOutgoing()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.finishOutgoing (Mob defender, CombatStrategy<? super T > strategy) private
Definition at line 455 of file Combat.java.
{
        strategy.finishOutgoing(attacker, defender);
        listeners.forEach(listener -> listener.finishOutgoing(attacker, defender));
        defender.getCombat().finishIncoming(attacker);
    }
References attacker, com.runehive.game.world.entity.mob.Mob.getCombat(), and listeners.
Referenced by hitsplatTask().
getCombatType()
CombatType com.runehive.game.world.entity.combat.Combat< T extends Mob >.getCombatType ()
Definition at line 556 of file Combat.java.
{
        return combatType;
    }
References combatType.
getCooldown()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.getCooldown ()
Definition at line 548 of file Combat.java.
{
        return cooldown;
    }
References cooldown.
getDamageCache()
CombatDamage com.runehive.game.world.entity.combat.Combat< T extends Mob >.getDamageCache ()
Definition at line 577 of file Combat.java.
{
        return damageCache;
    }
References damageCache.
getDefender()
Mob com.runehive.game.world.entity.combat.Combat< T extends Mob >.getDefender ()
Definition at line 573 of file Combat.java.
{
        return target.getTarget();
    }
References target.
getFightStyle()
FightStyle com.runehive.game.world.entity.combat.Combat< T extends Mob >.getFightStyle ()
Definition at line 569 of file Combat.java.
{
        return fightStyle;
    }
References fightStyle.
getFightType()
FightType com.runehive.game.world.entity.combat.Combat< T extends Mob >.getFightType ()
Definition at line 552 of file Combat.java.
{
        return fightType;
    }
References fightType.
getLastAggressor()
Mob com.runehive.game.world.entity.combat.Combat< T extends Mob >.getLastAggressor ()
Definition at line 597 of file Combat.java.
{
        return lastAggressor;
    }
References lastAggressor.
getLastVictim()
Mob com.runehive.game.world.entity.combat.Combat< T extends Mob >.getLastVictim ()
Definition at line 593 of file Combat.java.
{
        return lastVictim;
    }
References lastVictim.
hasPassed() [1/2]
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.hasPassed (int delay)
Definition at line 628 of file Combat.java.
{
        return elapsedTime() - delay >= 0;
    }
References elapsedTime().
hasPassed() [2/2]
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.hasPassed (Stopwatch timer, int delay) private
Definition at line 624 of file Combat.java.
{
        return timer.elapsed(delay, TimeUnit.MILLISECONDS);
    }
References com.runehive.util.Stopwatch.elapsed().
Referenced by isAttacking(), isAttacking(), isUnderAttack(), isUnderAttackBy(), isUnderAttackByNpc(), and isUnderAttackByPlayer().
hit()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit (Mob defender, Hit hit, CombatStrategy<? super T > strategy) private
Definition at line 334 of file Combat.java.
{
        if (!CombatUtil.validateMobs(attacker, defender)) {
            combatQueue.removeIf(_hit -> _hit.getDefender() == defender);
            if (defender.inTeleport)
                defender.getCombat().damageQueue.clear();
            reset();
            return;
        }
        strategy.hit(attacker, defender, hit);
        listeners.forEach(listener -> listener.hit(attacker, defender, hit));
        if (!strategy.getCombatType().equals(CombatType.MAGIC) && hit.getDamage() > -1 && defender.id != 8060) {
            defender.animate(CombatUtil.getBlockAnimation(defender));
        }
        if (defender.getCurrentHealth() - hit.getDamage() > 0) {
            defender.getCombat().block(attacker, hit, strategy.getCombatType());
        }
    }
References com.runehive.game.world.entity.mob.Mob.animate(), attacker, combatQueue, com.runehive.game.world.entity.combat.CombatUtil.getBlockAnimation(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), hit(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.inTeleport, listeners, com.runehive.game.world.entity.combat.CombatType.MAGIC, reset(), and com.runehive.game.world.entity.combat.CombatUtil.validateMobs().
Referenced by attack(), block(), hit(), hitsplat(), hitTask(), onDamage(), onDeath(), onKill(), preDeath(), preKill(), queueDamage(), sendNextHitsplat(), and submitHits().
hitsplat()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplat (Mob defender, Hit hit, CombatStrategy<? super T > strategy) private
Definition at line 355 of file Combat.java.
{
        if (!CombatUtil.validateMobs(attacker, defender)) {
            combatQueue.removeIf(_hit -> _hit.getDefender() == defender);
            if (defender.inTeleport)
                defender.getCombat().damageQueue.clear();
            reset();
            return;
        }
        strategy.hitsplat(attacker, defender, hit);
        listeners.forEach(listener -> listener.hitsplat(attacker, defender, hit));
        if (!strategy.getCombatType().equals(CombatType.MAGIC) || hit.isAccurate()) {
            if (defender.getCurrentHealth() > 0 && hit.getDamage() >= 0) {
                defender.getCombat().queueDamage(hit);
                defender.getCombat().damageCache.add(attacker, hit);
            }
        }
    }
References attacker, combatQueue, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), hit(), com.runehive.game.world.entity.mob.Mob.inTeleport, listeners, com.runehive.game.world.entity.combat.CombatType.MAGIC, reset(), and com.runehive.game.world.entity.combat.CombatUtil.validateMobs().
Referenced by hitsplatTask().
hitsplatTask()
Task com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplatTask (CombatData< T > data) private
Definition at line 612 of file Combat.java.
{
        return new Task(data.getHitsplatDelay()) {
            @Override
            public void execute() {
                hitsplat(data.getDefender(), data.getHit(), data.getStrategy());
                if (data.isLastHit())
                    finishOutgoing(data.getDefender(), data.getStrategy());
                cancel();
            }
        };
    }
References finishOutgoing(), com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getDefender(), com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getHit(), com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getHitsplatDelay(), com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getStrategy(), hitsplat(), and com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.isLastHit().
Referenced by hitTask().
hitTask()
Task com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitTask (CombatData< T > data) private
Definition at line 601 of file Combat.java.
{
        return new Task(data.getHitDelay()) {
            @Override
            public void execute() {
                hit(data.getDefender(), data.getHit(), attacker.getStrategy()/*data.getStrategy()*/);
                World.schedule(hitsplatTask(data));
                cancel();
            }
        };
    }
References attacker, com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getDefender(), com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getHit(), com.runehive.game.world.entity.combat.hit.CombatData< T extends Mob >.getHitDelay(), hit(), hitsplatTask(), and com.runehive.game.world.World.schedule().
Referenced by tick().
inCombat()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.inCombat ()
Definition at line 516 of file Combat.java.
{
        return isAttacking() || isUnderAttack();
    }
References isAttacking(), and isUnderAttack().
inCombatWith()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.inCombatWith (Mob mob)
Definition at line 520 of file Combat.java.
{
        return isAttacking(mob) || isUnderAttackBy(mob);
    }
References isAttacking(), and isUnderAttackBy().
init()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.init (Mob defender, CombatStrategy<? super T > strategy) private
Definition at line 286 of file Combat.java.
{
        strategy.init(attacker, defender);
        listeners.forEach(listener -> listener.init(attacker, defender));
    }
References attacker, and listeners.
Referenced by submitHits(), and submitStrategy().
isAttacking() [1/2]
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.isAttacking ()
Definition at line 524 of file Combat.java.
{
        return target.getTarget() != null && !hasPassed(lastAttacked, CombatConstants.COMBAT_TIMER_COOLDOWN);
    }
References com.runehive.game.world.entity.combat.CombatConstants.COMBAT_TIMER_COOLDOWN, hasPassed(), lastAttacked, and target.
Referenced by inCombat(), inCombatWith(), and tick().
isAttacking() [2/2]
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.isAttacking (Mob defender)
Definition at line 532 of file Combat.java.
{
        return defender != null && defender.equals(lastVictim) && !hasPassed(lastAttacked, CombatConstants.COMBAT_TIMER_COOLDOWN);
    }
References com.runehive.game.world.entity.combat.CombatConstants.COMBAT_TIMER_COOLDOWN, com.runehive.game.world.entity.Entity.equals(), hasPassed(), lastAttacked, and lastVictim.
isLastAggressor()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.isLastAggressor (Mob mob)
Definition at line 589 of file Combat.java.
{
        return mob.equals(lastAggressor);
    }
References lastAggressor.
isUnderAttack()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.isUnderAttack ()
Definition at line 528 of file Combat.java.
{
        return lastAggressor != null && !hasPassed(lastBlocked, CombatConstants.COMBAT_TIMER_COOLDOWN);
    }
References com.runehive.game.world.entity.combat.CombatConstants.COMBAT_TIMER_COOLDOWN, hasPassed(), lastAggressor, and lastBlocked.
Referenced by inCombat().
isUnderAttackBy()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.isUnderAttackBy (Mob attacker)
Definition at line 536 of file Combat.java.
{
        return attacker != null && attacker.equals(lastAggressor) && !hasPassed(lastBlocked, CombatConstants.COMBAT_TIMER_COOLDOWN);
    }
References attacker, com.runehive.game.world.entity.combat.CombatConstants.COMBAT_TIMER_COOLDOWN, hasPassed(), lastAggressor, and lastBlocked.
Referenced by inCombatWith().
isUnderAttackByNpc()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.isUnderAttackByNpc ()
Definition at line 544 of file Combat.java.
{
        return lastAggressor != null && lastAggressor.isNpc() && !hasPassed(lastBlocked, CombatConstants.COMBAT_TIMER_COOLDOWN);
    }
References com.runehive.game.world.entity.combat.CombatConstants.COMBAT_TIMER_COOLDOWN, hasPassed(), lastAggressor, and lastBlocked.
isUnderAttackByPlayer()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.isUnderAttackByPlayer ()
Definition at line 540 of file Combat.java.
{
        return lastAggressor != null && lastAggressor.isPlayer() && !hasPassed(lastBlocked, CombatConstants.COMBAT_TIMER_COOLDOWN);
    }
References com.runehive.game.world.entity.combat.CombatConstants.COMBAT_TIMER_COOLDOWN, hasPassed(), lastAggressor, and lastBlocked.
modifyAccuracy()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyAccuracy (Mob defender, int roll)
Definition at line 677 of file Combat.java.
{
        return formula.modifyAccuracy(attacker, defender, roll);
    }
References attacker, and formula.
modifyAggresiveBonus()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyAggresiveBonus (Mob defender, int bonus)
Definition at line 693 of file Combat.java.
{
        return formula.modifyAggressiveBonus(attacker, defender, bonus);
    }
References attacker, and formula.
modifyAttackLevel()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyAttackLevel (Mob defender, int level)
Definition at line 657 of file Combat.java.
{
        return formula.modifyAttackLevel(attacker, defender, level);
    }
References attacker, and formula.
modifyDamage()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyDamage (Mob defender, int damage)
Definition at line 685 of file Combat.java.
{
        return formula.modifyDamage(attacker, defender, damage);
    }
References attacker, and formula.
modifyDefenceLevel()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyDefenceLevel (Mob attacker, int level)
Definition at line 665 of file Combat.java.
{
        return formula.modifyDefenceLevel(attacker, this.attacker, level);
    }
References attacker, and formula.
modifyDefensive()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyDefensive (Mob attacker, int roll)
Definition at line 681 of file Combat.java.
{
        return formula.modifyDefensive(attacker, this.attacker, roll);
    }
References attacker, and formula.
modifyDefensiveBonus()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyDefensiveBonus (Mob attacker, int bonus)
Definition at line 697 of file Combat.java.
{
        return formula.modifyDefensiveBonus(attacker, this.attacker, bonus);
    }
References attacker, and formula.
modifyMagicLevel()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyMagicLevel (Mob defender, int level)
Definition at line 673 of file Combat.java.
{
        return formula.modifyMagicLevel(attacker, defender, level);
    }
References attacker, and formula.
modifyOffensiveBonus()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyOffensiveBonus (Mob defender, int bonus)
Definition at line 689 of file Combat.java.
{
        return formula.modifyOffensiveBonus(attacker, defender, bonus);
    }
References attacker, and formula.
modifyRangedLevel()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyRangedLevel (Mob defender, int level)
Definition at line 669 of file Combat.java.
{
        return formula.modifyRangedLevel(attacker, defender, level);
    }
References attacker, and formula.
modifyStrengthLevel()
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.modifyStrengthLevel (Mob defender, int level)
Definition at line 661 of file Combat.java.
{
        return formula.modifyStrengthLevel(attacker, defender, level);
    }
References attacker, and formula.
onDamage()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.onDamage (Hit hit)
Definition at line 430 of file Combat.java.
{
        if (attacker != null) {
            listeners.forEach(listener -> listener.onDamage(attacker, hit));
        }
    }
References attacker, hit(), and listeners.
onDeath()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.onDeath (Mob attacker, Hit hit)
Definition at line 445 of file Combat.java.
{
        if (attacker != null) {
            T defender = this.attacker;
            listeners.forEach(listener -> listener.onDeath(attacker, defender, hit));
            defender.movement.reset();
            defender.resetWaypoint();
            reset();
        }
    }
References attacker, hit(), listeners, and reset().
onKill()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.onKill (Mob defender, Hit hit)
Definition at line 436 of file Combat.java.
{
        if (attacker != null) {
            if (attacker.isPlayer() && attacker.getPlayer().getCombatSpecial() != null) {
                attacker.getPlayer().getCombatSpecial().getStrategy().onKill(attacker.getPlayer(), defender, hit);
            }
            listeners.forEach(listener -> listener.onKill(attacker, defender, hit));
        }
    }
References attacker, hit(), and listeners.
performChecks()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.performChecks (final Mob defender)
Definition at line 161 of file Combat.java.
{
        if (defender == null) return;
        for (final CombatListener<? super T> listener : listeners) {
            listener.performChecks(attacker, defender);
        }
        final CombatStrategy<? super T> strategy = attacker.getStrategy();
        if (strategy != null) {
            strategy.performChecks(attacker, defender);
        }
    }
References attacker, and listeners.
Referenced by tick().
preDeath()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.preDeath (Mob attacker, Hit hit)
Definition at line 415 of file Combat.java.
{
        if (attacker != null) {
            T defender = this.attacker;
            defender.getStrategy().preDeath(attacker, defender, hit);
            listeners.forEach(listener -> listener.preDeath(attacker, defender, hit));
            reset();
        }
    }
References attacker, com.runehive.game.world.entity.mob.Mob.getStrategy(), hit(), listeners, and reset().
preKill()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.preKill (Mob defender, Hit hit)
Definition at line 424 of file Combat.java.
{
        if (attacker != null) {
            defender.getCombat().listeners.forEach(listener -> listener.preKill(attacker, defender, hit));
        }
    }
References attacker, com.runehive.game.world.entity.mob.Mob.getCombat(), and hit().
queueDamage()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.queueDamage (Hit hit)
Definition at line 214 of file Combat.java.
{
        if (attacker.getCurrentHealth() <= 0) {
            return;
        }
        if (damageQueue.size() > 10) {
            attacker.decrementHealth(hit);
            return;
        }
        damageQueue.add(hit);
    }
References attacker, damageQueue, and hit().
removeFirst()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.removeFirst ()
Definition at line 492 of file Combat.java.
{
        formula.removeFirst();
    }
References formula.
removeListener()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.removeListener (CombatListener<? super T > listener)
Definition at line 504 of file Combat.java.
{
        if (pendingRemoval.contains(listener)) {
            return;
        }
//        System.out.println("[@Combat] removed listener: " + listener.getClass().getSimpleName());
        pendingRemoval.add(listener);
    }
References pendingRemoval.
removeModifier()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.removeModifier (FormulaModifier<? super T > modifier)
Definition at line 484 of file Combat.java.
{
        formula.remove(modifier);
    }
References formula.
Referenced by submitHits(), and updateListeners().
reset() [1/2]
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.reset ()
Definition at line 476 of file Combat.java.
{
        reset(false);
    }
References reset().
Referenced by attack(), hit(), hitsplat(), onDeath(), preDeath(), reset(), start(), and tick().
reset() [2/2]
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.reset (boolean force)
Definition at line 467 of file Combat.java.
{
        if (force || target.getTarget() != null) {
            target.resetTarget();
            attacker.resetFace();
            attacker.movement.reset();
            attacker.resetWaypoint();
        }
    }
References attacker, and target.
resetTimers()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.resetTimers (int millis)
Definition at line 638 of file Combat.java.
{
        lastAttacked.reset(millis, TimeUnit.MILLISECONDS);
        lastBlocked.reset(millis, TimeUnit.MILLISECONDS);
    }
References lastAttacked, and lastBlocked.
retaliate()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate (Mob attacker) private
Definition at line 375 of file Combat.java.
{
        T defender = this.attacker;
        if (attacker.isPlayer()) {
            Player player = attacker.getPlayer();
            if (!player.interfaceManager.isMainClear() || !player.interfaceManager.isDialogueClear()) {
                player.interfaceManager.close();
            }
            if (defender.isPlayer() && defender.getPlayer().isBot) {
                ((PlayerBot) defender.getPlayer()).retaliate(player);
            }
        }
        if (defender.isPlayer()) {
            Player player = defender.getPlayer();
            if (!player.damageImmunity.finished()) {
                return;
            }
            if (!player.interfaceManager.isMainClear() || !player.interfaceManager.isDialogueClear()) {
                player.interfaceManager.close();
            }
        }
        if (target.getTarget() != null && !target.isTarget(attacker)) {
            return;
        }
        if (!CombatUtil.canAttack(attacker, defender)) {
            return;
        }
        if (defender.isAutoRetaliate() && (defender.isNpc() || defender.movement.isMovementDone())) {
            attack(attacker);
        }
    }
References attack(), attacker, com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.entity.mob.Mob.damageImmunity, com.runehive.util.Stopwatch.finished(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.isDialogueClear(), com.runehive.game.world.entity.mob.player.InterfaceManager.isMainClear(), and target.
sendNextHitsplat()
boolean com.runehive.game.world.entity.combat.Combat< T extends Mob >.sendNextHitsplat () private
Definition at line 126 of file Combat.java.
{
        if (damageQueue.isEmpty()) {
            return false;
        }
        if (attacker.getCurrentHealth() <= 0) {
            damageQueue.clear();
            return false;
        }
        Hit hit = damageQueue.poll();
        attacker.writeDamage(hit);
        return true;
    }
References attacker, damageQueue, and hit().
Referenced by tick().
setCombatType()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.setCombatType (CombatType type)
Definition at line 565 of file Combat.java.
{
        this.combatType = type;
    }
setCooldown()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.setCooldown (int delay)
Definition at line 236 of file Combat.java.
{
        cooldown = delay;
    }
References cooldown.
setFightType()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.setFightType (FightType type)
Definition at line 560 of file Combat.java.
{
        this.fightType = type;
        this.fightStyle = type.getStyle();
    }
References com.runehive.game.world.entity.combat.attack.FightType.getStyle().
start()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.start (Mob defender, CombatStrategy<? super T > strategy, Hit... hits) private
Definition at line 291 of file Combat.java.
{
        if (!CombatUtil.validateMobs(attacker, defender)) {
            combatQueue.removeIf(_hit -> _hit.getDefender() == defender);
            if (defender.inTeleport)
                defender.getCombat().damageQueue.clear();
            reset();
            return;
        }
        defender.getCombat().lastBlocked.reset();
        defender.getCombat().lastAggressor = attacker;
        strategy.start(attacker, defender, hits);
        Hit[] finalHits = hits;
        listeners.forEach(listener -> listener.start(attacker, defender, finalHits));
    }
References attacker, combatQueue, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.mob.Mob.inTeleport, listeners, reset(), and com.runehive.game.world.entity.combat.CombatUtil.validateMobs().
Referenced by submitHits().
submitHits() [1/2]
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.submitHits (Mob defender, CombatHit... hits)
Definition at line 195 of file Combat.java.
{
        CombatStrategy<? super T> strategy = attacker.getStrategy();
        addModifier(strategy);
        init(defender, strategy);
        submitHits(defender, strategy, hits);
        removeModifier(strategy);
    }
References addModifier(), attacker, init(), removeModifier(), and submitHits().
Referenced by submitHits(), and submitStrategy().
submitHits() [2/2]
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.submitHits (Mob defender, CombatStrategy<? super T > strategy, CombatHit... hits) private
Definition at line 203 of file Combat.java.
{
        start(defender, strategy, hits);
        for (int index = 0; index < hits.length; index++) {
            boolean last = index == hits.length - 1;
            CombatHit hit = hits[index];
            CombatData<T> data = new CombatData<>(attacker, defender, hit, strategy, last);
            attack(defender, hit, strategy);
            combatQueue.add(data);
        }
    }
References attack(), attacker, combatQueue, hit(), and start().
submitStrategy()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.submitStrategy (Mob defender, CombatStrategy<? super T > strategy)
Definition at line 173 of file Combat.java.
{
        if (!canAttack(defender, strategy)) {
            return;
        }
        if (!checkWithin(attacker, defender, strategy)) {
            return;
        }
        attacker.interact(target.getTarget());
        formula.add(strategy);
        init(defender, strategy);
        cooldown(strategy.getAttackDelay(attacker, defender, fightType));
        submitHits(defender, strategy, strategy.getHits(attacker, defender));
        formula.remove(strategy);
        if (attacker.isPlayer() && defender.isPlayer()) {
            attacker.getPlayer().skulling.checkForSkulling(defender.getPlayer());
        }
    }
References attacker, canAttack(), checkWithin(), cooldown, fightType, formula, com.runehive.game.world.entity.mob.Mob.getPlayer(), init(), com.runehive.game.world.entity.mob.Mob.isPlayer(), submitHits(), and target.
Referenced by tick().
tick()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.tick ()
Definition at line 79 of file Combat.java.
                       {
        updateListeners();
        performChecks(target.getTarget());
        if (!checkDistances(target.getTarget()))
            reset();
        if (cooldown > 0) {
            cooldown--;
        }
        if (target.getTarget() != null) {
            attacker.interact(target.getTarget());
            if (cooldown == 0) {
                CombatStrategy<? super T> strategy = attacker.getStrategy();
                submitStrategy(target.getTarget(), strategy);
            }
        }
        while (!combatQueue.isEmpty()) {
            CombatData<T> data = combatQueue.poll();
            World.schedule(hitTask(data));
        }
        for (int index = 0, sent = 0; index < hitsplatCooldowns.length; index++) {
            if (hitsplatCooldowns[index] > 0) {
                hitsplatCooldowns[index]--;
            } else if (sent < 2 && sendNextHitsplat()) {
                hitsplatCooldowns[index] = 2;
                sent++;
            }
        }
        final Mob targetMob = target.getTarget();
        if (targetMob != null && attacker.isPlayer() && isAttacking(targetMob)) {
            attacker.getPlayer().send(
                    new SendEntityFeed(targetMob));
        }
    }
References attacker, checkDistances(), combatQueue, cooldown, hitsplatCooldowns, hitTask(), isAttacking(), performChecks(), reset(), com.runehive.game.world.World.schedule(), sendNextHitsplat(), submitStrategy(), target, and updateListeners().
updateListeners()
void com.runehive.game.world.entity.combat.Combat< T extends Mob >.updateListeners () private
Definition at line 141 of file Combat.java.
{
        if (!pendingAddition.isEmpty()) {
            for (Iterator<CombatListener<? super T>> iterator = pendingAddition.iterator(); iterator.hasNext(); ) {
                CombatListener<? super T> next = iterator.next();
                addModifier(next);
                listeners.add(next);
                iterator.remove();
            }
        }
        if (!pendingRemoval.isEmpty()) {
            for (Iterator<CombatListener<? super T>> iterator = pendingRemoval.iterator(); iterator.hasNext(); ) {
                CombatListener<? super T> next = iterator.next();
                removeModifier(next);
                listeners.remove(next);
                iterator.remove();
            }
        }
    }
References addModifier(), listeners, pendingAddition, pendingRemoval, and removeModifier().
Referenced by tick().
Member Data Documentation
attacker
final T com.runehive.game.world.entity.combat.Combat< T extends Mob >.attacker private
Definition at line 28 of file Combat.java.
Referenced by attack(), attack(), block(), canAttack(), canAttack(), canOtherAttack(), checkDistances(), checkWithin(), Combat(), finishIncoming(), finishOutgoing(), hit(), hitsplat(), hitTask(), init(), isUnderAttackBy(), modifyAccuracy(), modifyAggresiveBonus(), modifyAttackLevel(), modifyDamage(), modifyDefenceLevel(), modifyDefensive(), modifyDefensiveBonus(), modifyMagicLevel(), modifyOffensiveBonus(), modifyRangedLevel(), modifyStrengthLevel(), onDamage(), onDeath(), onKill(), performChecks(), preDeath(), preKill(), queueDamage(), reset(), retaliate(), sendNextHitsplat(), start(), submitHits(), submitHits(), submitStrategy(), and tick().
combatQueue
final Deque<CombatData<T> > com.runehive.game.world.entity.combat.Combat< T extends Mob >.combatQueue = new ArrayDeque<>() private
Definition at line 47 of file Combat.java.
Referenced by attack(), clearIncoming(), hit(), hitsplat(), start(), submitHits(), and tick().
combatType
CombatType com.runehive.game.world.entity.combat.Combat< T extends Mob >.combatType private
Definition at line 38 of file Combat.java.
Referenced by block(), and getCombatType().
cooldown
int com.runehive.game.world.entity.combat.Combat< T extends Mob >.cooldown private
Definition at line 51 of file Combat.java.
Referenced by cooldown(), getCooldown(), setCooldown(), submitStrategy(), and tick().
damageCache
final CombatDamage com.runehive.game.world.entity.combat.Combat< T extends Mob >.damageCache = new CombatDamage() private
Definition at line 46 of file Combat.java.
Referenced by getDamageCache().
damageQueue
final Deque<Hit> com.runehive.game.world.entity.combat.Combat< T extends Mob >.damageQueue = new ArrayDeque<>() private
Definition at line 48 of file Combat.java.
Referenced by clearDamageQueue(), queueDamage(), and sendNextHitsplat().
fightStyle
FightStyle com.runehive.game.world.entity.combat.Combat< T extends Mob >.fightStyle private
Definition at line 39 of file Combat.java.
Referenced by getFightStyle().
fightType
FightType com.runehive.game.world.entity.combat.Combat< T extends Mob >.fightType private
Definition at line 36 of file Combat.java.
Referenced by Combat(), getFightType(), and submitStrategy().
formula
final CombatFormula<T> com.runehive.game.world.entity.combat.Combat< T extends Mob >.formula = new CombatFormula<>() private
Definition at line 41 of file Combat.java.
Referenced by addFirst(), addModifier(), modifyAccuracy(), modifyAggresiveBonus(), modifyAttackLevel(), modifyDamage(), modifyDefenceLevel(), modifyDefensive(), modifyDefensiveBonus(), modifyMagicLevel(), modifyOffensiveBonus(), modifyRangedLevel(), modifyStrengthLevel(), removeFirst(), removeModifier(), and submitStrategy().
hitsplatCooldowns
final int [] com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplatCooldowns = new int[4] private
Definition at line 50 of file Combat.java.
Referenced by tick().
lastAggressor
Mob com.runehive.game.world.entity.combat.Combat< T extends Mob >.lastAggressor private
Definition at line 31 of file Combat.java.
Referenced by block(), getLastAggressor(), isLastAggressor(), isUnderAttack(), isUnderAttackBy(), isUnderAttackByNpc(), and isUnderAttackByPlayer().
lastAttacked
final Stopwatch com.runehive.game.world.entity.combat.Combat< T extends Mob >.lastAttacked = Stopwatch.start() private
Definition at line 33 of file Combat.java.
Referenced by attack(), elapsedTime(), isAttacking(), isAttacking(), and resetTimers().
lastBlocked
final Stopwatch com.runehive.game.world.entity.combat.Combat< T extends Mob >.lastBlocked = Stopwatch.start()
Definition at line 34 of file Combat.java.
Referenced by block(), elapsedTime(), isUnderAttack(), isUnderAttackBy(), isUnderAttackByNpc(), isUnderAttackByPlayer(), and resetTimers().
lastVictim
Mob com.runehive.game.world.entity.combat.Combat< T extends Mob >.lastVictim private
Definition at line 31 of file Combat.java.
Referenced by attack(), getLastVictim(), and isAttacking().
listeners
final Deque<CombatListener<? super T> > com.runehive.game.world.entity.combat.Combat< T extends Mob >.listeners = new ArrayDeque<>() private
Definition at line 42 of file Combat.java.
Referenced by addListener(), attack(), block(), canAttack(), canAttack(), canOtherAttack(), checkWithin(), finishIncoming(), finishOutgoing(), hit(), hitsplat(), init(), onDamage(), onDeath(), onKill(), performChecks(), preDeath(), start(), and updateListeners().
pendingAddition
final Deque<CombatListener<? super T> > com.runehive.game.world.entity.combat.Combat< T extends Mob >.pendingAddition = new ArrayDeque<>() private
Definition at line 43 of file Combat.java.
Referenced by addListener(), and updateListeners().
pendingRemoval
final Deque<CombatListener<? super T> > com.runehive.game.world.entity.combat.Combat< T extends Mob >.pendingRemoval = new ArrayDeque<>() private
Definition at line 44 of file Combat.java.
Referenced by removeListener(), and updateListeners().
target
CombatTarget com.runehive.game.world.entity.combat.Combat< T extends Mob >.target private
Definition at line 30 of file Combat.java.
Referenced by attack(), checkAggression(), compare(), getDefender(), isAttacking(), reset(), retaliate(), submitStrategy(), and tick().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/Combat.java