RuneHive-Game: com.runehive.game.world.entity.combat.projectile.CombatProjectile Class Reference
com.runehive.game.world.entity.combat.projectile.CombatProjectile Class Reference
Classes
class ProjectileBuilder
Public Member Functions
CombatProjectile (String name, int maxHit, CombatImpact effect, Animation animation, Graphic start, Graphic end, Projectile projectile)
CombatProjectile (String name, int maxHit, CombatImpact effect, Animation animation, Graphic start, Graphic end, Projectile projectile, int hitDelay, int hitsplatDelay)
Optional< Animation > getAnimation ()
int getClientTicks ()
Optional< CombatImpact > getEffect ()
Optional< Graphic > getEnd ()
OptionalInt getHitDelay ()
OptionalInt getHitsplatDelay ()
int getMaxHit ()
String getName ()
Optional< Projectile > getProjectile ()
int getServerTicks ()
Optional< Graphic > getStart ()
int sendProjectile (Mob attacker, Mob defender)
Static Public Member Functions
static CombatProjectile getDefinition (String name)
Static Public Attributes
static final Map< String, CombatProjectile > definitions = new HashMap<>()
Private Attributes
final Animation animation
final CombatImpact effect
final Graphic end
final int hitDelay
final int hitsplatDelay
final int maxHit
final String name
final Projectile projectile
final Graphic start
Detailed Description
Definition at line 16 of file CombatProjectile.java.
Constructor & Destructor Documentation
CombatProjectile() [1/2]
com.runehive.game.world.entity.combat.projectile.CombatProjectile.CombatProjectile (String name, int maxHit, CombatImpact effect, Animation animation, Graphic start, Graphic end, Projectile projectile, int hitDelay, int hitsplatDelay)
Definition at line 31 of file CombatProjectile.java.
{
        this.name = name;
        this.maxHit = maxHit;
        this.effect = effect;
        this.animation = animation;
        this.start = start;
        this.end = end;
        this.projectile = projectile;
        this.hitDelay = hitDelay;
        this.hitsplatDelay = hitsplatDelay;
    }
References animation, effect, end, hitDelay, hitsplatDelay, maxHit, name, projectile, and start.
Referenced by getDefinition().
CombatProjectile() [2/2]
com.runehive.game.world.entity.combat.projectile.CombatProjectile.CombatProjectile (String name, int maxHit, CombatImpact effect, Animation animation, Graphic start, Graphic end, Projectile projectile)
Definition at line 43 of file CombatProjectile.java.
{
        this(name, maxHit, effect, animation, start, end, projectile, -1, -1);
    }
References animation, effect, end, maxHit, name, projectile, and start.
Member Function Documentation
getAnimation()
Optional< Animation > com.runehive.game.world.entity.combat.projectile.CombatProjectile.getAnimation ()
Definition at line 118 of file CombatProjectile.java.
{
        return Optional.ofNullable(animation);
    }
References animation.
Referenced by com.runehive.game.world.entity.combat.magic.CombatSpell.getAnimation().
getClientTicks()
int com.runehive.game.world.entity.combat.projectile.CombatProjectile.getClientTicks ()
Definition at line 75 of file CombatProjectile.java.
{
        return projectile == null ? 0 : projectile.getClientTicks();
    }
References projectile.
Referenced by getServerTicks(), and sendProjectile().
getDefinition()
CombatProjectile com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition (String name) static
Definition at line 102 of file CombatProjectile.java.
{
        return definitions.get(name);
    }
References CombatProjectile(), definitions, and name.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.special.range.ArmadylCrossbow.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.special.range.CrawsBow.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.special.range.DragonThrownaxe.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.special.range.MagicShortbow.[static initializer](), com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.[static initializer](), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.AcidAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.kril.Balfrug.Balfrug(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack.BarrageAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack.BoomAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.DragonfireAttack.DragonfireAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack.FireballAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.FlockleaderGeerin(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.FrozenSpecial(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.FrozenSpecial(), com.runehive.game.world.entity.combat.magic.CombatSpell.getAnimation(), com.runehive.game.world.entity.combat.magic.CombatSpell.getCombatProjectile(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.CombatAttackData.getDefinition(), com.runehive.game.world.entity.combat.magic.CombatSpell.getEnd(), com.runehive.game.world.entity.combat.magic.CombatSpell.getStart(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.GhostAttack(), com.runehive.content.activity.infernomobs.JalTokJad.Guardian.Guardian(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.Guardian(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.IceSpecial.IceSpecial(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack.JumpAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack.LavaAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.LightingRain(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.LightingRain(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.LightingRain(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.Spinolyp.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.Magic(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.MagicAttack.MagicAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.MagicAttack.MagicAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MagicAttack.MagicAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.MagicAttack.MagicAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.MagicAttack.MagicAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Melee.Melee(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Melee.Melee(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Melee.Melee(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.MinionsAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.GuardianWaypoint.onDestination(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.PinkDragonfireAttack.PinkDragonfireAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack.PrayerAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.PrayerDrain(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack.RainAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.RainAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Ranged.Ranged(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.Spinolyp.Ranged.Ranged(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Ranged.Ranged(), com.runehive.content.activity.infernomobs.JalTokJad.RangedAttack.RangedAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.RangedAttack.RangedAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.RangedAttack.RangedAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.RangedAttack.RangedAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.Roar(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.ScorpiaOffspring.ScorpiaOffspring(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.TeleGrab.TeleGrab(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.TeleGrab.TeleGrab(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.TeleGrab.TeleGrab(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform.Transform(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomDragonfireAttack.VenomDragonfireAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.VenomSpecial(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.Web(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.WingmanSkree(), and com.runehive.game.world.entity.combat.strategy.npc.boss.kril.Zakln.Zakln().
getEffect()
Optional< CombatImpact > com.runehive.game.world.entity.combat.projectile.CombatProjectile.getEffect ()
Definition at line 114 of file CombatProjectile.java.
{
        return Optional.ofNullable(effect);
    }
References effect.
getEnd()
Optional< Graphic > com.runehive.game.world.entity.combat.projectile.CombatProjectile.getEnd ()
Definition at line 126 of file CombatProjectile.java.
{
        return Optional.ofNullable(end);
    }
References end.
Referenced by com.runehive.game.world.entity.combat.magic.CombatSpell.getEnd(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic(), and com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic().
getHitDelay()
OptionalInt com.runehive.game.world.entity.combat.projectile.CombatProjectile.getHitDelay ()
Definition at line 130 of file CombatProjectile.java.
{
        if (hitDelay == -1) {
            return OptionalInt.empty();
        }
        return OptionalInt.of(hitDelay);
    }
References hitDelay.
getHitsplatDelay()
OptionalInt com.runehive.game.world.entity.combat.projectile.CombatProjectile.getHitsplatDelay ()
Definition at line 137 of file CombatProjectile.java.
{
        if (hitsplatDelay == -1) {
            return OptionalInt.empty();
        }
        return OptionalInt.of(hitsplatDelay);
    }
References hitsplatDelay.
getMaxHit()
int com.runehive.game.world.entity.combat.projectile.CombatProjectile.getMaxHit ()
Definition at line 110 of file CombatProjectile.java.
{
        return maxHit;
    }
References maxHit.
Referenced by com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage().
getName()
String com.runehive.game.world.entity.combat.projectile.CombatProjectile.getName ()
Definition at line 106 of file CombatProjectile.java.
{
        return name;
    }
References name.
Referenced by sendProjectile().
getProjectile()
Optional< Projectile > com.runehive.game.world.entity.combat.projectile.CombatProjectile.getProjectile ()
Definition at line 144 of file CombatProjectile.java.
{
        return Optional.ofNullable(projectile);
    }
References projectile.
Referenced by com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getProjectileDuration(), com.runehive.content.activity.infernomobs.JalTokJad.Guardian.Guardian(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.Guardian(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.GuardianWaypoint.onDestination(), and com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow.setProjectiles().
getServerTicks()
int com.runehive.game.world.entity.combat.projectile.CombatProjectile.getServerTicks ()
Definition at line 79 of file CombatProjectile.java.
{
        return GameEngine.clientTicksToServerTicks(getClientTicks());
    }
References com.runehive.game.engine.GameEngine.clientTicksToServerTicks(), and getClientTicks().
Referenced by com.runehive.game.world.entity.combat.CombatUtil.getHitDelay().
getStart()
Optional< Graphic > com.runehive.game.world.entity.combat.projectile.CombatProjectile.getStart ()
Definition at line 122 of file CombatProjectile.java.
{
        return Optional.ofNullable(start);
    }
References start.
Referenced by com.runehive.game.world.entity.combat.magic.CombatSpell.getStart().
sendProjectile()
int com.runehive.game.world.entity.combat.projectile.CombatProjectile.sendProjectile (Mob attacker, Mob defender)
Definition at line 83 of file CombatProjectile.java.
{
        if (projectile == null) return 0;
        /*final Projectile copy = projectile.copy();
        final int duration = getProjectileDuration(attacker, defender);
        copy.setDuration(duration);*/
        final String name = getName();
        if ("Ice Barrage".equals(name) || "Ice Burst".equals(name)
                || "Smoke Barrage".equals(name) || "Smoke Burst".equals(name)) {
            // special case: these are sent from defender pos to defender rather than normal!
            World.sendProjectile(defender.getPosition(), defender, projectile);
        } else {
            projectile.send(attacker, defender);
        }
        return getClientTicks();
    }
References getClientTicks(), getName(), com.runehive.game.world.entity.Entity.getPosition(), name, projectile, and com.runehive.game.world.World.sendProjectile().
Member Data Documentation
animation
final Animation com.runehive.game.world.entity.combat.projectile.CombatProjectile.animation private
Definition at line 23 of file CombatProjectile.java.
Referenced by CombatProjectile(), CombatProjectile(), and getAnimation().
definitions
final Map<String, CombatProjectile> com.runehive.game.world.entity.combat.projectile.CombatProjectile.definitions = new HashMap<>() static
Definition at line 18 of file CombatProjectile.java.
Referenced by getDefinition(), and com.runehive.util.parser.impl.CombatProjectileParser.parse().
effect
final CombatImpact com.runehive.game.world.entity.combat.projectile.CombatProjectile.effect private
Definition at line 22 of file CombatProjectile.java.
Referenced by CombatProjectile(), CombatProjectile(), and getEffect().
end
final Graphic com.runehive.game.world.entity.combat.projectile.CombatProjectile.end private
Definition at line 25 of file CombatProjectile.java.
Referenced by CombatProjectile(), CombatProjectile(), and getEnd().
hitDelay
final int com.runehive.game.world.entity.combat.projectile.CombatProjectile.hitDelay private
Definition at line 28 of file CombatProjectile.java.
Referenced by CombatProjectile(), and getHitDelay().
hitsplatDelay
final int com.runehive.game.world.entity.combat.projectile.CombatProjectile.hitsplatDelay private
Definition at line 29 of file CombatProjectile.java.
Referenced by CombatProjectile(), and getHitsplatDelay().
maxHit
final int com.runehive.game.world.entity.combat.projectile.CombatProjectile.maxHit private
Definition at line 21 of file CombatProjectile.java.
Referenced by CombatProjectile(), CombatProjectile(), and getMaxHit().
name
final String com.runehive.game.world.entity.combat.projectile.CombatProjectile.name private
Definition at line 20 of file CombatProjectile.java.
Referenced by CombatProjectile(), CombatProjectile(), getDefinition(), getName(), and sendProjectile().
projectile
final Projectile com.runehive.game.world.entity.combat.projectile.CombatProjectile.projectile private
Definition at line 26 of file CombatProjectile.java.
Referenced by CombatProjectile(), CombatProjectile(), getClientTicks(), getProjectile(), and sendProjectile().
start
final Graphic com.runehive.game.world.entity.combat.projectile.CombatProjectile.start private
Definition at line 24 of file CombatProjectile.java.
Referenced by CombatProjectile(), CombatProjectile(), and getStart().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/projectile/CombatProjectile.java