RuneHive-Game: com.runehive.game.world.entity.mob.player.relations.PlayerRelation Class Reference
com.runehive.game.world.entity.mob.player.relations.PlayerRelation Class Reference
Public Member Functions
void addFriend (Long username)
void addIgnore (Long username)
void deleteFriend (Long username)
void deleteIgnore (Long username)
PrivacyChatMode getClanChatMode ()
List< Long > getFriendList ()
List< Long > getIgnoreList ()
PrivacyChatMode getPrivateChatMode ()
int getPrivateMessageId ()
PrivacyChatMode getPublicChatMode ()
PrivacyChatMode getTradeChatMode ()
boolean isFriendWith (String player)
void message (Player friend, PrivateChatMessage message)
PlayerRelation onLogin ()
PlayerRelation (Player player)
void setClanChatMode (PrivacyChatMode clanChatMode, boolean update)
void setPrivacyChatModes (int publicChat, int privateChat, int clanChat, int tradeChat)
PlayerRelation setPrivateChatMode (PrivacyChatMode privateChatMode, boolean update)
PlayerRelation setPrivateMessageId (int privateMessageId)
void setPublicChatMode (PrivacyChatMode publicChatMode, boolean update)
void setTradeChatMode (PrivacyChatMode tradeChatMode, boolean update)
PlayerRelation updateLists (boolean online)
Private Member Functions
void sendAddFriend (long name)
void sendFriends ()
void sendIgnores ()
void updatePrivacyChatOptions ()
Private Attributes
PrivacyChatMode clanChatMode = PrivacyChatMode.ON
final List< Long > friendList = new ArrayList<>(200)
final List< Long > ignoreList = new ArrayList<>(100)
Player player
PrivacyChatMode privateChatMode = PrivacyChatMode.ON
int privateMessageId = 1
PrivacyChatMode publicChatMode = PrivacyChatMode.ON
PrivacyChatMode tradeChatMode = PrivacyChatMode.ON
Detailed Description
Definition at line 13 of file PlayerRelation.java.
Constructor & Destructor Documentation
PlayerRelation()
com.runehive.game.world.entity.mob.player.relations.PlayerRelation.PlayerRelation (Player player)
Definition at line 32 of file PlayerRelation.java.
{
        this.player = player;
    }
References player.
Referenced by onLogin(), setPrivateChatMode(), setPrivateMessageId(), and updateLists().
Member Function Documentation
addFriend()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.addFriend (Long username)
Definition at line 108 of file PlayerRelation.java.
{
        String name = Utility.formatName(Utility.longToString(username));
        if (player.usernameLong == username) {
            return;
        }
        if (friendList.size() >= 200) {
            player.send(new SendMessage("Your friend list is full!"));
            return;
        }
        if (ignoreList.contains(username)) {
            player.send(new SendMessage("Please remove " + name + " from your ignore list first."));
            return;
        }
        if (friendList.contains(username)) {
            player.send(new SendMessage(name + " is already on your friends list!"));
        } else {
            friendList.add(username);
            sendAddFriend(username);
            updateLists(true);
            Optional<Player> result = World.search(name);
            result.ifPresent(it -> it.relations.updateLists(true));
        }
    }
References com.runehive.util.Utility.formatName(), friendList, ignoreList, com.runehive.util.Utility.longToString(), player, com.runehive.game.world.World.search(), sendAddFriend(), and updateLists().
addIgnore()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.addIgnore (Long username)
Definition at line 155 of file PlayerRelation.java.
{
        String name = Utility.formatName(Utility.longToString(username));
        if (player.usernameLong == username) {
            return;
        }
        if (ignoreList.size() >= 100) {
            player.send(new SendMessage("Your ignore list is full!"));
            return;
        }
        if (friendList.contains(username)) {
            player.send(new SendMessage("Please remove " + name + " from your friend list first."));
            return;
        }
        if (ignoreList.contains(username)) {
            player.send(new SendMessage(name + " is already on your ignore list!"));
        } else {
            ignoreList.add(username);
            updateLists(true);
            Optional<Player> result = World.search(name);
            result.ifPresent(it -> it.relations.updateLists(false));
        }
    }
References com.runehive.util.Utility.formatName(), friendList, ignoreList, com.runehive.util.Utility.longToString(), player, com.runehive.game.world.World.search(), and updateLists().
deleteFriend()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteFriend (Long username)
Definition at line 139 of file PlayerRelation.java.
{
        final String name = Utility.formatName(Utility.longToString(username));
        if (name.equals(player.getUsername())) {
            return;
        }
        if (friendList.contains(username)) {
            friendList.remove(username);
            if (privateChatMode != PrivacyChatMode.ON) {
                updateLists(false);
            }
        } else {
            player.send(new SendMessage("This player is not on your friends list!"));
        }
    }
References com.runehive.util.Utility.formatName(), friendList, com.runehive.util.Utility.longToString(), com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.ON, player, privateChatMode, and updateLists().
deleteIgnore()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteIgnore (Long username)
Definition at line 181 of file PlayerRelation.java.
{
        String name = Utility.formatName(Utility.longToString(username));
        if (name.equals(player.getUsername())) {
            return;
        }
        if (ignoreList.contains(username)) {
            ignoreList.remove(username);
            updateLists(true);
            if (privateChatMode.equals(PrivacyChatMode.ON)) {
                Optional<Player> result = World.search(name);
                result.ifPresent(it -> it.relations.updateLists(true));
            }
        } else {
            player.send(new SendMessage("This player is not on your ignore list!"));
        }
    }
References com.runehive.util.Utility.formatName(), ignoreList, com.runehive.util.Utility.longToString(), com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.ON, player, privateChatMode, com.runehive.game.world.World.search(), and updateLists().
getClanChatMode()
PrivacyChatMode com.runehive.game.world.entity.mob.player.relations.PlayerRelation.getClanChatMode ()
Definition at line 275 of file PlayerRelation.java.
{
        return clanChatMode;
    }
References clanChatMode.
getFriendList()
List< Long > com.runehive.game.world.entity.mob.player.relations.PlayerRelation.getFriendList ()
Definition at line 41 of file PlayerRelation.java.
{
        return friendList;
    }
References friendList.
getIgnoreList()
List< Long > com.runehive.game.world.entity.mob.player.relations.PlayerRelation.getIgnoreList ()
Definition at line 45 of file PlayerRelation.java.
{
        return ignoreList;
    }
References ignoreList.
getPrivateChatMode()
PrivacyChatMode com.runehive.game.world.entity.mob.player.relations.PlayerRelation.getPrivateChatMode ()
Definition at line 264 of file PlayerRelation.java.
{
        return privateChatMode;
    }
References privateChatMode.
getPrivateMessageId()
int com.runehive.game.world.entity.mob.player.relations.PlayerRelation.getPrivateMessageId ()
Definition at line 26 of file PlayerRelation.java.
{
        return privateMessageId++;
    }
References privateMessageId.
Referenced by com.runehive.net.packet.out.SendPrivateMessage.encode().
getPublicChatMode()
PrivacyChatMode com.runehive.game.world.entity.mob.player.relations.PlayerRelation.getPublicChatMode ()
Definition at line 253 of file PlayerRelation.java.
{
        return publicChatMode;
    }
References publicChatMode.
getTradeChatMode()
PrivacyChatMode com.runehive.game.world.entity.mob.player.relations.PlayerRelation.getTradeChatMode ()
Definition at line 279 of file PlayerRelation.java.
{
        return tradeChatMode;
    }
References tradeChatMode.
isFriendWith()
boolean com.runehive.game.world.entity.mob.player.relations.PlayerRelation.isFriendWith (String player)
Definition at line 135 of file PlayerRelation.java.
{
        return friendList.contains(Utility.stringToLong(player));
    }
References friendList, player, and com.runehive.util.Utility.stringToLong().
message()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.message (Player friend, PrivateChatMessage message)
Definition at line 198 of file PlayerRelation.java.
{
        if (player.punishment.isMuted()) {
            player.message("You can not send private messages while muted!");
            return;
        }
        if (friend == null) {
            player.send(new SendMessage("This player is currently offline."));
            return;
        }
        if (friend.relations.privateChatMode.equals(PrivacyChatMode.FRIENDS_ONLY) && !friend.relations.friendList.contains(player.usernameLong) || friend.relations.privateChatMode.equals(PrivacyChatMode.OFF)) {
            player.send(new SendMessage("This player is currently offline."));
            return;
        }
        if (privateChatMode == PrivacyChatMode.OFF) {
            setPrivateChatMode(PrivacyChatMode.FRIENDS_ONLY, true);
        }
        friend.send(new SendPrivateMessage(player.usernameLong, player.right, message.getCompressed()));
        World.getDataBus().publish(new PrivateMessageChatLogEvent(player, friend, message.getDecompressed()));
    }
References friendList, com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.FRIENDS_ONLY, com.runehive.game.world.World.getDataBus(), message(), com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.OFF, player, privateChatMode, com.runehive.game.event.bus.DataBus.publish(), com.runehive.game.world.entity.mob.player.Player.relations, com.runehive.game.world.entity.mob.player.Player.send(), and setPrivateChatMode().
Referenced by message().
onLogin()
PlayerRelation com.runehive.game.world.entity.mob.player.relations.PlayerRelation.onLogin ()
Definition at line 100 of file PlayerRelation.java.
{
        sendFriends();
        sendIgnores();
        updatePrivacyChatOptions();
        updateLists(true);
        return this;
    }
References PlayerRelation(), sendFriends(), sendIgnores(), updateLists(), and updatePrivacyChatOptions().
sendAddFriend()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.sendAddFriend (long name) private
Definition at line 96 of file PlayerRelation.java.
{
        player.send(new SendAddFriend(name, 0));
    }
References player.
Referenced by addFriend().
sendFriends()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.sendFriends () private
Definition at line 84 of file PlayerRelation.java.
{
        for (long l : friendList) {
            player.send(new SendAddFriend(l, 0));
        }
    }
References friendList, and player.
Referenced by onLogin().
sendIgnores()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.sendIgnores () private
Definition at line 90 of file PlayerRelation.java.
{
        for (long l : ignoreList) {
            player.send(new SendAddIgnore(l));
        }
    }
References ignoreList, and player.
Referenced by onLogin().
setClanChatMode()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setClanChatMode (PrivacyChatMode clanChatMode, boolean update)
Definition at line 268 of file PlayerRelation.java.
{
        this.clanChatMode = clanChatMode;
        if (update) {
            updatePrivacyChatOptions();
        }
    }
References clanChatMode, and updatePrivacyChatOptions().
setPrivacyChatModes()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setPrivacyChatModes (int publicChat, int privateChat, int clanChat, int tradeChat)
Definition at line 235 of file PlayerRelation.java.
{
        if (publicChat >= 0 && publicChat <= PrivacyChatMode.HIDE.getCode()) {
            PrivacyChatMode.get(publicChat).ifPresent(it -> this.publicChatMode = it);
        }
        if (privateChat >= 0 && privateChat <= PrivacyChatMode.OFF.getCode()) {
            PrivacyChatMode.get(privateChat).ifPresent(it -> setPrivateChatMode(it, true));
        }
        if (clanChat >= 0 && clanChat <= PrivacyChatMode.OFF.getCode()) {
            PrivacyChatMode.get(clanChat).ifPresent(it -> this.clanChatMode = it);
        }
        if (tradeChat >= 0 && tradeChat <= PrivacyChatMode.OFF.getCode()) {
            PrivacyChatMode.get(tradeChat).ifPresent(it -> this.tradeChatMode = it);
        }
    }
References com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.get(), com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.HIDE, com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.OFF, and setPrivateChatMode().
setPrivateChatMode()
PlayerRelation com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setPrivateChatMode (PrivacyChatMode privateChatMode, boolean update)
Definition at line 221 of file PlayerRelation.java.
{
        if (this.privateChatMode == privateChatMode) {
            return this;
        }
        this.privateChatMode = privateChatMode;
        if (update) {
            updateLists(true);
        }
        return this;
    }
References PlayerRelation(), privateChatMode, and updateLists().
Referenced by message(), and setPrivacyChatModes().
setPrivateMessageId()
PlayerRelation com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setPrivateMessageId (int privateMessageId)
Definition at line 36 of file PlayerRelation.java.
{
        this.privateMessageId = privateMessageId;
        return this;
    }
References PlayerRelation(), and privateMessageId.
setPublicChatMode()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setPublicChatMode (PrivacyChatMode publicChatMode, boolean update)
Definition at line 257 of file PlayerRelation.java.
{
        this.publicChatMode = publicChatMode;
        if (update) {
            updatePrivacyChatOptions();
        }
    }
References publicChatMode, and updatePrivacyChatOptions().
setTradeChatMode()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setTradeChatMode (PrivacyChatMode tradeChatMode, boolean update)
Definition at line 283 of file PlayerRelation.java.
{
        this.tradeChatMode = tradeChatMode;
        if (update) {
            updatePrivacyChatOptions();
        }
    }
References tradeChatMode, and updatePrivacyChatOptions().
updateLists()
PlayerRelation com.runehive.game.world.entity.mob.player.relations.PlayerRelation.updateLists (boolean online)
Definition at line 49 of file PlayerRelation.java.
{
        if (privateChatMode == PrivacyChatMode.OFF) {
            online = false;
        }
        player.send(new SendPrivateMessageListStatus(PrivateMessageListStatus.LOADED));
        for (Player players : World.getPlayers()) {
            if (players == null) {
                continue;
            }
            boolean temporaryOnlineStatus = online;
            if (players.relations.friendList.contains(player.usernameLong)) {
                if (privateChatMode.equals(PrivacyChatMode.FRIENDS_ONLY) && !friendList.contains(players.usernameLong) ||
                        privateChatMode.equals(PrivacyChatMode.OFF) || ignoreList.contains(players.usernameLong)) {
                    temporaryOnlineStatus = false;
                }
                players.send(new SendAddFriend(player.usernameLong, temporaryOnlineStatus ? 1 : 0));
            }
            boolean tempOn = true;
            if (player.relations.friendList.contains(players.usernameLong)) {
                if (players.relations.privateChatMode.equals(PrivacyChatMode.FRIENDS_ONLY) && !players.relations.getFriendList().contains(player.usernameLong) ||
                        players.relations.privateChatMode.equals(PrivacyChatMode.OFF) || players.relations.getIgnoreList().contains(player.usernameLong)) {
                    tempOn = false;
                }
                player.send(new SendAddFriend(players.usernameLong, tempOn ? 1 : 0));
            }
        }
        return this;
    }
References friendList, com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.FRIENDS_ONLY, com.runehive.game.world.World.getPlayers(), ignoreList, com.runehive.game.world.entity.mob.player.relations.PrivateMessageListStatus.LOADED, com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.OFF, player, PlayerRelation(), and privateChatMode.
Referenced by addFriend(), addIgnore(), deleteFriend(), deleteIgnore(), onLogin(), and setPrivateChatMode().
updatePrivacyChatOptions()
void com.runehive.game.world.entity.mob.player.relations.PlayerRelation.updatePrivacyChatOptions () private
Definition at line 80 of file PlayerRelation.java.
{
        player.send(new SendChatOption(publicChatMode, privateChatMode, clanChatMode, tradeChatMode));
    }
References clanChatMode, player, privateChatMode, publicChatMode, and tradeChatMode.
Referenced by onLogin(), setClanChatMode(), setPublicChatMode(), and setTradeChatMode().
Member Data Documentation
clanChatMode
PrivacyChatMode com.runehive.game.world.entity.mob.player.relations.PlayerRelation.clanChatMode = PrivacyChatMode.ON private
Definition at line 17 of file PlayerRelation.java.
Referenced by getClanChatMode(), setClanChatMode(), and updatePrivacyChatOptions().
friendList
final List<Long> com.runehive.game.world.entity.mob.player.relations.PlayerRelation.friendList = new ArrayList<>(200) private
Definition at line 20 of file PlayerRelation.java.
Referenced by addFriend(), addIgnore(), deleteFriend(), getFriendList(), isFriendWith(), message(), sendFriends(), and updateLists().
ignoreList
final List<Long> com.runehive.game.world.entity.mob.player.relations.PlayerRelation.ignoreList = new ArrayList<>(100) private
Definition at line 22 of file PlayerRelation.java.
Referenced by addFriend(), addIgnore(), deleteIgnore(), getIgnoreList(), sendIgnores(), and updateLists().
player
Player com.runehive.game.world.entity.mob.player.relations.PlayerRelation.player private
Definition at line 30 of file PlayerRelation.java.
Referenced by addFriend(), addIgnore(), deleteFriend(), deleteIgnore(), isFriendWith(), message(), PlayerRelation(), sendAddFriend(), sendFriends(), sendIgnores(), updateLists(), and updatePrivacyChatOptions().
privateChatMode
PrivacyChatMode com.runehive.game.world.entity.mob.player.relations.PlayerRelation.privateChatMode = PrivacyChatMode.ON private
Definition at line 16 of file PlayerRelation.java.
Referenced by deleteFriend(), deleteIgnore(), getPrivateChatMode(), message(), setPrivateChatMode(), updateLists(), and updatePrivacyChatOptions().
privateMessageId
int com.runehive.game.world.entity.mob.player.relations.PlayerRelation.privateMessageId = 1 private
Definition at line 24 of file PlayerRelation.java.
Referenced by getPrivateMessageId(), and setPrivateMessageId().
publicChatMode
PrivacyChatMode com.runehive.game.world.entity.mob.player.relations.PlayerRelation.publicChatMode = PrivacyChatMode.ON private
Definition at line 15 of file PlayerRelation.java.
Referenced by getPublicChatMode(), setPublicChatMode(), and updatePrivacyChatOptions().
tradeChatMode
PrivacyChatMode com.runehive.game.world.entity.mob.player.relations.PlayerRelation.tradeChatMode = PrivacyChatMode.ON private
Definition at line 18 of file PlayerRelation.java.
Referenced by getTradeChatMode(), setTradeChatMode(), and updatePrivacyChatOptions().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/relations/PlayerRelation.java