RuneHive-Game: com.runehive.game.world.entity.combat.effect.CombatEffect Class Reference
com.runehive.game.world.entity.combat.effect.CombatEffect Class Reference abstract
Some sort of temporary effect applied to a Mob during combat.
Public Member Functions
abstract boolean apply (Mob mob)
Applies this effect to mob.
CombatEffect (int delay)
Creates a new CombatEffect.
abstract boolean onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
abstract void process (Mob mob)
Provides processing for this effect on mob.
abstract boolean removeOn (Mob mob)
Removes this effect from mob if needed.
final boolean start (Mob mob)
Starts this combat effect by scheduling a task utilizing the abstract methods in this class.
Static Public Member Functions
static Collection< CombatEffect > values ()
Returns an unmodifiable view of the combat effect listeners.
Static Public Attributes
static final Map< CombatEffectType, CombatEffect > EFFECTS = new HashMap<>()
The map of all of the combat effect types mapped to their respective listeners.
Protected Member Functions
final int getDelay ()
Gets the delay for this individual combat effect.
Private Attributes
final int delay
The delay for this individual combat effect.
Detailed Description
Some sort of temporary effect applied to a Mob during combat.
Combat effects include but are not limited to; being poisoned, skulled, and teleblocked.
Author
lare96 http://github.org/lare96
Definition at line 18 of file CombatEffect.java.
Constructor & Destructor Documentation
CombatEffect()
com.runehive.game.world.entity.combat.effect.CombatEffect.CombatEffect (int delay)
Creates a new CombatEffect.
Definition at line 27 of file CombatEffect.java.
{
        this.delay = delay;
    }
References delay.
Member Function Documentation
apply()
abstract boolean com.runehive.game.world.entity.combat.effect.CombatEffect.apply (Mob mob) abstract
Applies this effect to mob.
Reimplemented in com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect, com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect, com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect, com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect, and com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.
Referenced by start().
getDelay()
final int com.runehive.game.world.entity.combat.effect.CombatEffect.getDelay () protected
Gets the delay for this individual combat effect.
Definition at line 53 of file CombatEffect.java.
{
        return delay;
    }
References delay.
onLogin()
abstract boolean com.runehive.game.world.entity.combat.effect.CombatEffect.onLogin (Mob mob) abstract
Executed on login, primarily used to re-apply the effect to mob.
Reimplemented in com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect, com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect, com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect, com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect, and com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.
process()
abstract void com.runehive.game.world.entity.combat.effect.CombatEffect.process (Mob mob) abstract
Provides processing for this effect on mob.
Reimplemented in com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect, com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect, com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect, com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect, and com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.
removeOn()
abstract boolean com.runehive.game.world.entity.combat.effect.CombatEffect.removeOn (Mob mob) abstract
Removes this effect from mob if needed.
Reimplemented in com.runehive.game.world.entity.combat.effect.impl.CombatAntifireEffect, com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect, com.runehive.game.world.entity.combat.effect.impl.CombatSkullEffect, com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect, and com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.
start()
final boolean com.runehive.game.world.entity.combat.effect.CombatEffect.start (Mob mob)
Starts this combat effect by scheduling a task utilizing the abstract methods in this class.
Definition at line 32 of file CombatEffect.java.
{
        if (apply(mob)) {
            World.schedule(new CombatEffectTask(mob, this));
            return true;
        }
        return false;
    }
References apply(), and com.runehive.game.world.World.schedule().
values()
Collection< CombatEffect > com.runehive.game.world.entity.combat.effect.CombatEffect.values () static
Returns an unmodifiable view of the combat effect listeners.
Definition at line 58 of file CombatEffect.java.
{
        return Collections.unmodifiableCollection(EFFECTS.values());
    }
References EFFECTS.
Member Data Documentation
delay
final int com.runehive.game.world.entity.combat.effect.CombatEffect.delay private
The delay for this individual combat effect.
Definition at line 24 of file CombatEffect.java.
Referenced by CombatEffect(), and getDelay().
EFFECTS
final Map<CombatEffectType, CombatEffect> com.runehive.game.world.entity.combat.effect.CombatEffect.EFFECTS = new HashMap<>() static
The map of all of the combat effect types mapped to their respective listeners.
Definition at line 21 of file CombatEffect.java.
Referenced by com.runehive.game.world.entity.combat.effect.CombatEffectType.[static initializer](), com.runehive.game.world.entity.combat.CombatUtil.cancelEffect(), com.runehive.game.world.entity.combat.CombatUtil.effect(), and values().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/effect/CombatEffect.java