RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern Class Reference
com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern Class Reference
Classes
class Melee
Public Member Functions
boolean canAttack (Npc attacker, Mob defender)
void finishOutgoing (Npc attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
boolean canAttack (T attacker, Mob defender)
boolean canOtherAttack (Mob attacker, T defender)
void finishIncoming (Mob attacker, T defender)
void finishOutgoing (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
void hitsplat (T attacker, Mob defender, Hit hit)
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
void onKill (T attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, T defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
void start (T attacker, Mob defender, Hit[] hits)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Static Package Functions
[static initializer]
Static Private Attributes
static DragonfireStrategy DRAGONFIRE
static CombatStrategy< Npc >[] STRATEGIES
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
static final CombatListener< Mob > CANT_ATTACK
Detailed Description
Author
Daniel
Definition at line 21 of file SkeletalWyvern.java.
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.[static initializer] static package
References DRAGONFIRE, and STRATEGIES.
canAttack()
boolean com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.canAttack (Npc attacker, Mob defender)
Definition at line 35 of file SkeletalWyvern.java.
{
        if (!NpcMeleeStrategy.get().withinDistance(attacker, defender)) {
            attacker.setStrategy(DRAGONFIRE);
        }
        return attacker.getStrategy().canAttack(attacker, defender);
    }
References DRAGONFIRE, com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.get(), com.runehive.game.world.entity.mob.npc.Npc.getStrategy(), com.runehive.game.world.entity.mob.npc.Npc.setStrategy(), and com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.withinDistance().
finishOutgoing()
void com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.finishOutgoing (Npc attacker, Mob defender)
Definition at line 43 of file SkeletalWyvern.java.
{
        if (!NpcMeleeStrategy.get().withinDistance(attacker, defender)) {
            attacker.setStrategy(DRAGONFIRE);
        } else {
            attacker.setStrategy(randomStrategy(STRATEGIES));
        }
    }
References DRAGONFIRE, com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.get(), com.runehive.game.world.entity.mob.npc.Npc.setStrategy(), STRATEGIES, and com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.withinDistance().
Member Data Documentation
DRAGONFIRE
DragonfireStrategy com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.DRAGONFIRE static private
Definition at line 22 of file SkeletalWyvern.java.
Referenced by [static initializer](), canAttack(), and finishOutgoing().
STRATEGIES
CombatStrategy<Npc> [] com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.STRATEGIES static private
Definition at line 23 of file SkeletalWyvern.java.
Referenced by [static initializer](), and finishOutgoing().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/npc/dragon/SkeletalWyvern.java