RuneHive-Game: com.runehive.content.mysterybox.MysteryBox Class Reference
com.runehive.content.mysterybox.MysteryBox Class Reference abstract
The mystery box class.
Static Public Member Functions
static void load ()
Handles loading the mystery boxes.
Protected Member Functions
abstract int item ()
The item identification of the mystery box.
abstract String name ()
The name of the mystery box.
abstract MysteryItem[] rewards ()
The rewards for the mystery box.
Static Package Functions
static Optional< MysteryBox > getMysteryBox (int item)
Handles getting the mystery box.
Static Private Attributes
static Map< Integer, MysteryBox > MYSTERY_BOXES = new HashMap<>()
The map containing all the mystery boxes.
Detailed Description
The mystery box class.
Author
Daniel
Definition at line 17 of file MysteryBox.java.
Member Function Documentation
getMysteryBox()
Optional< MysteryBox > com.runehive.content.mysterybox.MysteryBox.getMysteryBox (int item) static package
Handles getting the mystery box.
Definition at line 36 of file MysteryBox.java.
{
        return MYSTERY_BOXES.containsKey(item) ? Optional.of(MYSTERY_BOXES.get(item)) : Optional.empty();
    }
References item(), and MYSTERY_BOXES.
Referenced by com.runehive.content.mysterybox.MysteryBoxManager.click().
item()
abstract int com.runehive.content.mysterybox.MysteryBox.item () abstract protected
The item identification of the mystery box.
Reimplemented in com.runehive.content.mysterybox.impl.BronzeMysteryBox, com.runehive.content.mysterybox.impl.GoldMysteryBox, com.runehive.content.mysterybox.impl.PetMysteryBox, and com.runehive.content.mysterybox.impl.SilverMysteryBox.
Referenced by getMysteryBox(), and load().
load()
void com.runehive.content.mysterybox.MysteryBox.load () static
Handles loading the mystery boxes.
Definition at line 23 of file MysteryBox.java.
{
        MysteryBox BRONZE_BOX = new BronzeMysteryBox();
        MysteryBox SILVER_BOX = new SilverMysteryBox();
        MysteryBox GOLD_BOX = new GoldMysteryBox();
        MysteryBox PET_BOX = new PetMysteryBox();
        MYSTERY_BOXES.put(BRONZE_BOX.item(), BRONZE_BOX);
        MYSTERY_BOXES.put(SILVER_BOX.item(), SILVER_BOX);
        MYSTERY_BOXES.put(GOLD_BOX.item(), GOLD_BOX);
        MYSTERY_BOXES.put(PET_BOX.item(), PET_BOX);
    }
References item(), and MYSTERY_BOXES.
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
name()
abstract String com.runehive.content.mysterybox.MysteryBox.name () abstract protected
The name of the mystery box.
Reimplemented in com.runehive.content.mysterybox.impl.BronzeMysteryBox, com.runehive.content.mysterybox.impl.GoldMysteryBox, com.runehive.content.mysterybox.impl.PetMysteryBox, and com.runehive.content.mysterybox.impl.SilverMysteryBox.
rewards()
abstract MysteryItem[] com.runehive.content.mysterybox.MysteryBox.rewards () abstract protected
The rewards for the mystery box.
Reimplemented in com.runehive.content.mysterybox.impl.BronzeMysteryBox, com.runehive.content.mysterybox.impl.GoldMysteryBox, com.runehive.content.mysterybox.impl.PetMysteryBox, and com.runehive.content.mysterybox.impl.SilverMysteryBox.
Member Data Documentation
MYSTERY_BOXES
Map<Integer, MysteryBox> com.runehive.content.mysterybox.MysteryBox.MYSTERY_BOXES = new HashMap<>() static private
The map containing all the mystery boxes.
Definition at line 20 of file MysteryBox.java.
Referenced by getMysteryBox(), and load().
The documentation for this class was generated from the following file:
java/com/runehive/content/mysterybox/MysteryBox.java