RuneHive-Game: com.runehive.content.activity.ActivityListener< T extends Activity > Class Template Reference
com.runehive.content.activity.ActivityListener< T extends Activity > Class Template Reference abstract
A combat listener that is applied to all mobs added to (or removed from) the activity.
Public Member Functions
ActivityListener (T activity)
Constructs a new ActivityListener for a activity.
void attack (Mob attacker, Mob defender, Hit hit)
void block (Mob attacker, Mob defender, Hit hit, CombatType combatType)
boolean canAttack (Mob attacker, Mob defender)
boolean canOtherAttack (Mob attacker, Mob defender)
void finishIncoming (Mob attacker, Mob defender)
void finishOutgoing (Mob attacker, Mob defender)
void hit (Mob attacker, Mob defender, Hit hit)
void hitsplat (Mob attacker, Mob defender, Hit hit)
void onDamage (Mob defender, Hit hit)
void onDeath (Mob attacker, Mob defender, Hit hit)
void onKill (Mob attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, Mob defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (Mob attacker, Mob defender, Hit[] hits)
boolean withinDistance (Mob attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Protected Attributes
final T activity
The parent activity.
Detailed Description
A combat listener that is applied to all mobs added to (or removed from) the activity.
Parameters
<T> the activity type
Definition at line 14 of file ActivityListener.java.
Constructor & Destructor Documentation
ActivityListener()
com.runehive.content.activity.ActivityListener< T extends Activity >.ActivityListener (T activity)
Constructs a new ActivityListener for a activity.
Parameters
activity the parent activity
Definition at line 24 of file ActivityListener.java.
{
        this.activity = activity;
    }
References activity.
Member Function Documentation
attack()
void com.runehive.content.activity.ActivityListener< T extends Activity >.attack (Mob attacker, Mob defender, Hit hit)
Definition at line 52 of file ActivityListener.java.
{
    }
References hit().
block()
void com.runehive.content.activity.ActivityListener< T extends Activity >.block (Mob attacker, Mob defender, Hit hit, CombatType combatType)
Reimplemented in com.runehive.content.activity.impl.fightcaves.FightCavesListener, and com.runehive.content.activity.inferno.InfernoCavesListener.
Definition at line 60 of file ActivityListener.java.
{
    }
References hit().
canAttack()
boolean com.runehive.content.activity.ActivityListener< T extends Activity >.canAttack (Mob attacker, Mob defender)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaListener, com.runehive.content.activity.impl.godwars.GodwarsListener, com.runehive.content.activity.impl.kraken.KrakenActivityListener, com.runehive.content.activity.impl.pestcontrol.PestControlListener, com.runehive.content.activity.impl.warriorguild.WarriorGuildActivityListener, and com.runehive.content.activity.impl.zulrah.ZulrahListener.
Definition at line 34 of file ActivityListener.java.
{
        return true;
    }
canOtherAttack()
boolean com.runehive.content.activity.ActivityListener< T extends Activity >.canOtherAttack (Mob attacker, Mob defender)
Reimplemented in com.runehive.content.activity.impl.zulrah.ZulrahListener.
Definition at line 39 of file ActivityListener.java.
{
        return true;
    }
finishIncoming()
void com.runehive.content.activity.ActivityListener< T extends Activity >.finishIncoming (Mob attacker, Mob defender)
Definition at line 80 of file ActivityListener.java.
{
    }
finishOutgoing()
void com.runehive.content.activity.ActivityListener< T extends Activity >.finishOutgoing (Mob attacker, Mob defender)
Definition at line 76 of file ActivityListener.java.
{
    }
hit()
void com.runehive.content.activity.ActivityListener< T extends Activity >.hit (Mob attacker, Mob defender, Hit hit)
Reimplemented in com.runehive.content.activity.impl.kraken.KrakenActivityListener.
Definition at line 56 of file ActivityListener.java.
{
    }
References hit().
Referenced by attack(), block(), com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), hit(), hitsplat(), com.runehive.content.activity.impl.pestcontrol.PestControlListener.hitsplat(), onDamage(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.onDamage(), onDeath(), com.runehive.content.activity.impl.fightcaves.FightCavesListener.onDeath(), com.runehive.content.activity.inferno.InfernoCavesListener.onDeath(), onKill(), com.runehive.content.activity.impl.godwars.GodwarsListener.onKill(), preDeath(), preKill(), and com.runehive.content.activity.impl.duelarena.DuelArenaListener.preKill().
hitsplat()
void com.runehive.content.activity.ActivityListener< T extends Activity >.hitsplat (Mob attacker, Mob defender, Hit hit)
Reimplemented in com.runehive.content.activity.impl.pestcontrol.PestControlListener.
Definition at line 72 of file ActivityListener.java.
{
    }
References hit().
onDamage()
void com.runehive.content.activity.ActivityListener< T extends Activity >.onDamage (Mob defender, Hit hit)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaListener.
Definition at line 44 of file ActivityListener.java.
{
    }
References hit().
onDeath()
void com.runehive.content.activity.ActivityListener< T extends Activity >.onDeath (Mob attacker, Mob defender, Hit hit)
Reimplemented in com.runehive.content.activity.impl.fightcaves.FightCavesListener, com.runehive.content.activity.impl.kraken.KrakenActivityListener, and com.runehive.content.activity.inferno.InfernoCavesListener.
Definition at line 68 of file ActivityListener.java.
{
    }
References hit().
onKill()
void com.runehive.content.activity.ActivityListener< T extends Activity >.onKill (Mob attacker, Mob defender, Hit hit)
Reimplemented in com.runehive.content.activity.impl.godwars.GodwarsListener.
Definition at line 88 of file ActivityListener.java.
{
    }
References hit().
preDeath()
void com.runehive.content.activity.ActivityListener< T extends Activity >.preDeath (Mob attacker, Mob defender, Hit hit)
Definition at line 64 of file ActivityListener.java.
{
    }
References hit().
preKill()
void com.runehive.content.activity.ActivityListener< T extends Activity >.preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implements com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaListener.
Definition at line 84 of file ActivityListener.java.
{
    }
References hit().
start()
void com.runehive.content.activity.ActivityListener< T extends Activity >.start (Mob attacker, Mob defender, Hit[] hits)
Reimplemented in com.runehive.content.activity.impl.duelarena.DuelArenaListener.
Definition at line 48 of file ActivityListener.java.
{
    }
withinDistance()
boolean com.runehive.content.activity.ActivityListener< T extends Activity >.withinDistance (Mob attacker, Mob defender)
Reimplemented in com.runehive.content.activity.impl.kraken.KrakenActivityListener.
Definition at line 29 of file ActivityListener.java.
{
        return true;
    }
Member Data Documentation
activity
final T com.runehive.content.activity.ActivityListener< T extends Activity >.activity protected
The parent activity.
Definition at line 17 of file ActivityListener.java.
Referenced by ActivityListener(), com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.canAttack(), com.runehive.content.activity.impl.warriorguild.WarriorGuildActivityListener.canAttack(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.DuelArenaListener(), com.runehive.content.activity.impl.godwars.GodwarsListener.GodwarsListener(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.hit(), com.runehive.content.activity.impl.pestcontrol.PestControlListener.hitsplat(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.onDamage(), com.runehive.content.activity.impl.fightcaves.FightCavesListener.onDeath(), com.runehive.content.activity.inferno.InfernoCavesListener.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsListener.onKill(), com.runehive.content.activity.impl.pestcontrol.PestControlListener.PestControlListener(), com.runehive.content.activity.impl.duelarena.DuelArenaListener.start(), com.runehive.content.activity.impl.kraken.KrakenActivityListener.withinDistance(), and com.runehive.content.activity.impl.zulrah.ZulrahListener.ZulrahListener().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/ActivityListener.java