RuneHive-Game: com.runehive.game.world.entity.mob.player.relations.ChatMessage Class Reference
com.runehive.game.world.entity.mob.player.relations.ChatMessage Class Reference
Represents a chat message that can be displayed over an entities head.
Public Member Functions
ChatColor getColor ()
ChatEffect getEffect ()
byte[] getEncoded ()
boolean isValid ()
Static Public Member Functions
static ChatMessage create (String message)
static ChatMessage create (String message, ChatColor color)
static ChatMessage create (String message, ChatColor color, ChatEffect effect)
Static Public Attributes
static final int CHARACTER_LIMIT = 100
When a chat message decoded there's a character buffer that can only hold 100 characters.
Private Member Functions
ChatMessage (byte[] encoded)
ChatMessage (byte[] encoded, ChatColor color, ChatEffect effect)
Private Attributes
final ChatColor color
final ChatEffect effect
final byte[] encoded
Detailed Description
Represents a chat message that can be displayed over an entities head.
Author
nshusa
Definition at line 10 of file ChatMessage.java.
Constructor & Destructor Documentation
ChatMessage() [1/2]
com.runehive.game.world.entity.mob.player.relations.ChatMessage.ChatMessage (byte[] encoded) private
Definition at line 21 of file ChatMessage.java.
{
        this(encoded, ChatColor.YELLOW, ChatEffect.NONE);
    }
References encoded, com.runehive.game.world.entity.mob.player.relations.ChatEffect.NONE, and com.runehive.game.world.entity.mob.player.relations.ChatColor.YELLOW.
Referenced by create(), create(), and create().
ChatMessage() [2/2]
com.runehive.game.world.entity.mob.player.relations.ChatMessage.ChatMessage (byte[] encoded, ChatColor color, ChatEffect effect) private
Definition at line 25 of file ChatMessage.java.
{
        this.encoded = encoded;
        this.color = color;
        this.effect = effect;
    }
References color, effect, and encoded.
Member Function Documentation
create() [1/3]
ChatMessage com.runehive.game.world.entity.mob.player.relations.ChatMessage.create (String message) static
Definition at line 31 of file ChatMessage.java.
{
        return create(message, ChatColor.YELLOW, ChatEffect.NONE);
    }
References ChatMessage(), create(), com.runehive.game.world.entity.mob.player.relations.ChatEffect.NONE, and com.runehive.game.world.entity.mob.player.relations.ChatColor.YELLOW.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask(), create(), and create().
create() [2/3]
ChatMessage com.runehive.game.world.entity.mob.player.relations.ChatMessage.create (String message, ChatColor color) static
Definition at line 35 of file ChatMessage.java.
{
        return create(message, color, ChatEffect.NONE);
    }
References ChatMessage(), color, create(), and com.runehive.game.world.entity.mob.player.relations.ChatEffect.NONE.
create() [3/3]
ChatMessage com.runehive.game.world.entity.mob.player.relations.ChatMessage.create (String message, ChatColor color, ChatEffect effect) static
Definition at line 39 of file ChatMessage.java.
{
        return new ChatMessage(ChatCodec.encode(message.isEmpty() || message.length() > CHARACTER_LIMIT ? "Cabbage" : message), color, effect);
    }
References CHARACTER_LIMIT, ChatMessage(), color, and effect.
getColor()
ChatColor com.runehive.game.world.entity.mob.player.relations.ChatMessage.getColor ()
Definition at line 53 of file ChatMessage.java.
{
        return color;
    }
References color.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask().
getEffect()
ChatEffect com.runehive.game.world.entity.mob.player.relations.ChatMessage.getEffect ()
Definition at line 57 of file ChatMessage.java.
{
        return effect;
    }
References effect.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask().
getEncoded()
byte[] com.runehive.game.world.entity.mob.player.relations.ChatMessage.getEncoded ()
Definition at line 61 of file ChatMessage.java.
{
        return encoded;
    }
References encoded.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask().
isValid()
boolean com.runehive.game.world.entity.mob.player.relations.ChatMessage.isValid ()
Definition at line 43 of file ChatMessage.java.
{
        if (color.getCode() < 0 || color.getCode() >= ChatColor.values().length) {
            return false;
        }
        if (effect.getCode() < 0 || effect.getCode() >= ChatColor.values().length) {
            return false;
        }
        return encoded.length != 0 && encoded.length <= CHARACTER_LIMIT;
    }
References CHARACTER_LIMIT, color, effect, and com.runehive.game.world.entity.mob.player.relations.ChatColor.values.
Member Data Documentation
CHARACTER_LIMIT
final int com.runehive.game.world.entity.mob.player.relations.ChatMessage.CHARACTER_LIMIT = 100 static
When a chat message decoded there's a character buffer that can only hold 100 characters.
Definition at line 15 of file ChatMessage.java.
Referenced by create(), com.runehive.net.packet.in.CommandPacketListener.handlePacket(), isValid(), and com.runehive.game.world.entity.mob.Mob.speak().
color
final ChatColor com.runehive.game.world.entity.mob.player.relations.ChatMessage.color private
Definition at line 17 of file ChatMessage.java.
Referenced by ChatMessage(), create(), create(), getColor(), and isValid().
effect
final ChatEffect com.runehive.game.world.entity.mob.player.relations.ChatMessage.effect private
Definition at line 18 of file ChatMessage.java.
Referenced by ChatMessage(), create(), getEffect(), and isValid().
encoded
final byte [] com.runehive.game.world.entity.mob.player.relations.ChatMessage.encoded private
Definition at line 19 of file ChatMessage.java.
Referenced by ChatMessage(), ChatMessage(), and getEncoded().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/relations/ChatMessage.java