RuneHive-Game: com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel Class Reference
com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel Class Reference
Public Member Functions
void update ()
Public Member Functions inherited from com.runehive.content.activity.panel.Activity_Panel
void close ()
String getFooter ()
String getHeader ()
Item getItem ()
Player getPlayer ()
int getProgress ()
String[] getText ()
void open ()
void setFooter (String footer)
void setItem (Item item)
void setProgress (int progress)
Package Functions
DuelPanel (DuelArenaActivity activity, Player player)
Private Member Functions
String accuracy (Player dueler, Player duelee)
Private Attributes
final DuelArenaActivity activity
final Player player
Additional Inherited Members
Protected Member Functions inherited from com.runehive.content.activity.panel.Activity_Panel
Activity_Panel (Player player, String header)
void set (int index, String string)
Detailed Description
Definition at line 614 of file DuelArenaActivity.java.
Constructor & Destructor Documentation
DuelPanel()
com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.DuelPanel (DuelArenaActivity activity, Player player) package
Definition at line 618 of file DuelArenaActivity.java.
{
            super(player, "Duel Arena");
            this.activity = activity;
            this.player = player;
        }
References activity, com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelArenaActivity(), and player.
Member Function Documentation
accuracy()
String com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.accuracy (Player dueler, Player duelee) private
Definition at line 643 of file DuelArenaActivity.java.
{
            CombatStrategy<? super Player> strategy = dueler.getStrategy();
            CombatType type = strategy.getCombatType();
            dueler.getCombat().addModifier(strategy);
            double attackRoll = rollOffensive(dueler, duelee, type.getFormula());
            double defenceRoll = rollDefensive(dueler, duelee, type.getFormula()); //what is this exactly? this class duel arena? just a panel
            dueler.getCombat().removeModifier(strategy);
            double chance = attackRoll / (attackRoll + defenceRoll);
            double accuracy = (int) (chance * 10000) / 100.0;
            return String.valueOf(accuracy) + "%";
        }
References accuracy(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getCombatType(), com.runehive.game.world.entity.combat.CombatType.getFormula(), and com.runehive.game.world.entity.mob.player.Player.getStrategy().
Referenced by accuracy(), and update().
update()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update ()
Definition at line 624 of file DuelArenaActivity.java.
{
            Player dueler = player.equals(activity.player) ? activity.player : activity.opponent;
            Player duelee = !player.equals(activity.player) ? activity.player : activity.opponent;
            if (!activity.started) {
                set(0, "Dueling with: <col=FF5500>" + Utility.formatName(duelee.getName()) + "</col>");
                setProgress(-1);
            } else {
                set(0, "Time remaining: <col=FF5500>" + Utility.getTime(activity.getTicks() / 2) + "</col>");
                set(2, "Your accuracy: <col=FF5500>" + accuracy(dueler, duelee) + "</col>");
                set(3, "Your max hit: <col=FF5500>" + dueler.playerAssistant.getMaxHit(duelee, dueler.getStrategy().getCombatType()) + "</col>");
                set(5, "Opponent's accuracy: <col=FF5500>" + accuracy(duelee, dueler) + "</col>");
                set(6, "Opponent's max hit: <col=FF5500>" + duelee.playerAssistant.getMaxHit(dueler, duelee.getStrategy().getCombatType()) + "</col>");
                setFooter("Opponent health:");
                setProgress((int) Utility.getPercentageAmount(duelee.getCurrentHealth(), duelee.getMaximumHealth()));
            }
            setItem(new Item(4049));
        }
References accuracy(), activity, com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.player.PlayerAssistant.getMaxHit(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.util.Utility.getPercentageAmount(), com.runehive.game.world.entity.mob.player.Player.getStrategy(), com.runehive.util.Utility.getTime(), player, com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.content.activity.panel.Activity_Panel.setFooter(), com.runehive.content.activity.panel.Activity_Panel.setItem(), and com.runehive.content.activity.panel.Activity_Panel.setProgress().
Member Data Documentation
activity
final DuelArenaActivity com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.activity private
Definition at line 615 of file DuelArenaActivity.java.
Referenced by DuelPanel(), and update().
player
final Player com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.player private
Definition at line 616 of file DuelArenaActivity.java.
Referenced by DuelPanel(), and update().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/duelarena/DuelArenaActivity.java