RuneHive-Game: com.runehive.content.store.impl.RecipeForDisasterStore Class Reference
com.runehive.content.store.impl.RecipeForDisasterStore Class Reference
Handles the recipe for disaster store.
Public Member Functions
void close (Player player)
boolean decrementStock ()
void itemContainerAction (Player player, int id, int slot, int action, boolean purchase)
void open (Player player)
RecipeForDisasterStore ()
void refresh (Player player)
SellType sellType ()
StoreType type ()
Public Member Functions inherited from com.runehive.content.store.Store
final boolean equals (Object obj)
final int hashCode ()
void onPurchase (Player player, Item item)
boolean purchase (Player player, Item item, int slot)
Store (String name, ItemContainer.StackPolicy policy, CurrencyType currencyType, int capacity)
Public Attributes
final StoreItem[] items
Public Attributes inherited from com.runehive.content.store.Store
ItemContainer container
The current item container which contains the current items from this shop.
Map< Integer, Integer > itemCache
The map of cached shop item identifications and their amounts.
final String name
The name of this shop.
final Set< Player > players = new HashSet<>()
The set of players that are currently viewing this shop.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.store.Store
static void closeShop (Player player)
static void exchange (Player player, int id, int slot, int action, boolean purchase)
Static Public Attributes inherited from com.runehive.content.store.Store
static Map< String, Store > STORES = new HashMap<>()
A mapping of each shop by it's name.
Protected Member Functions inherited from com.runehive.content.store.Store
final void sell (Player player, Item item, int slot, boolean addX)
void sendPurchaseValue (Player player, int slot)
final void sendSellValue (Player player, int slot)
Static Protected Member Functions inherited from com.runehive.content.store.Store
static List< PersonalStore > getFeaturedShops ()
static List< PersonalStore > getPersonalShops ()
Protected Attributes inherited from com.runehive.content.store.Store
final CurrencyType currencyType
The currency for this shop.
Detailed Description
Handles the recipe for disaster store.
Author
Daniel
Definition at line 23 of file RecipeForDisasterStore.java.
Constructor & Destructor Documentation
RecipeForDisasterStore()
com.runehive.content.store.impl.RecipeForDisasterStore.RecipeForDisasterStore ()
Definition at line 38 of file RecipeForDisasterStore.java.
{
        super("Recipe For Disaster Store", ItemContainer.StackPolicy.ALWAYS, CurrencyType.COINS, 10);
        this.container.setItems(items, true);
        Arrays.stream(items).filter(Objects::nonNull).forEach(item -> itemCache.put(item.getId(), item.getAmount()));
    }
References com.runehive.game.world.items.containers.ItemContainer.StackPolicy.ALWAYS, com.runehive.content.store.currency.CurrencyType.COINS, com.runehive.content.store.Store.container, com.runehive.content.store.Store.itemCache, and items.
Member Function Documentation
close()
void com.runehive.content.store.impl.RecipeForDisasterStore.close (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 105 of file RecipeForDisasterStore.java.
{
        players.remove(player);
        player.attributes.remove("SHOP");
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.store.Store.players, and com.runehive.util.generic.GenericAttributes.remove().
decrementStock()
boolean com.runehive.content.store.impl.RecipeForDisasterStore.decrementStock ()
Reimplemented from com.runehive.content.store.Store.
Definition at line 121 of file RecipeForDisasterStore.java.
{
        return false;
    }
itemContainerAction()
void com.runehive.content.store.impl.RecipeForDisasterStore.itemContainerAction (Player player, int id, int slot, int action, boolean purchase)
Reimplemented from com.runehive.content.store.Store.
Definition at line 45 of file RecipeForDisasterStore.java.
{
        switch (action) {
            case 1:
                if (purchase) {
                    this.sendPurchaseValue(player, slot);
                }
                break;
            default:
                int amount = action == 2 ? 1 : action == 3 ? 10 : action == 4 ? 100 : -100;
                if (amount == -100) {
                    throw new IllegalArgumentException("The action given was invalid. [ACTION=" + action + "]");
                }
                if (purchase) {
                    this.purchase(player, new Item(id, amount), slot);
                }
                break;
        }
    }
References com.runehive.content.store.Store.purchase(), and com.runehive.content.store.Store.sendPurchaseValue().
open()
void com.runehive.content.store.impl.RecipeForDisasterStore.open (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 73 of file RecipeForDisasterStore.java.
{
        player.attributes.set("SHOP", name);
        if (!STORES.containsKey(name)) {
            STORES.put(name, this);
        }
        StoreItem[] storeItems = new StoreItem[10];
        int unlocked = player.glovesTier;
        int lastItem = 0;
        for (int index = 0; index < unlocked; index++) {
            if (index > unlocked)
                break;
            storeItems[index] = items[index];
            lastItem = index;
        }
        for (int i = 0; i < unlocked; i++) {
            player.send(new SendString(storeItems[i].getShopValue() + "," + currencyType.getId(), 47552 + i));
        }
        player.send(new SendString(name, 47502));
        player.send(new SendString("Store size: " + unlocked, 47507));
        player.send(new SendString(CurrencyType.getValue(player, currencyType), 47508));
        player.send(new SendItemOnInterface(47551, storeItems));
        final int scrollBarSize = lastItem <= 32 ? 0 : (lastItem / 8) * 72;
        player.send(new SendScrollbar(47550, scrollBarSize));
        player.send(new SendItemOnInterface(3823, player.inventory.toArray()));
        player.interfaceManager.openInventory(StoreConstant.INTERFACE_ID, 3822);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.store.Store.currencyType, com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.game.world.entity.mob.player.Player.glovesTier, com.runehive.content.store.StoreConstant.INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, items, com.runehive.content.store.Store.name, com.runehive.game.world.entity.mob.player.InterfaceManager.openInventory(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), com.runehive.content.store.Store.STORES, and com.runehive.game.world.items.containers.ItemContainer.toArray().
refresh()
void com.runehive.content.store.impl.RecipeForDisasterStore.refresh (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 65 of file RecipeForDisasterStore.java.
{
        player.send(new SendString("Store size: " + items.length, 47507));
        player.send(new SendString(CurrencyType.getValue(player, currencyType), 47508));
        player.send(new SendItemOnInterface(3823, player.inventory.toArray()));
        players.stream().filter(Objects::nonNull).forEach(p -> player.send(new SendItemOnInterface(47551, container.toArray())));
    }
References com.runehive.content.store.Store.container, com.runehive.content.store.Store.currencyType, com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.game.world.entity.mob.player.Player.inventory, items, com.runehive.content.store.Store.players, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.items.containers.ItemContainer.toArray().
sellType()
SellType com.runehive.content.store.impl.RecipeForDisasterStore.sellType ()
Reimplemented from com.runehive.content.store.Store.
Definition at line 116 of file RecipeForDisasterStore.java.
{
        return SellType.NONE;
    }
References com.runehive.content.store.SellType.NONE.
type()
StoreType com.runehive.content.store.impl.RecipeForDisasterStore.type ()
Reimplemented from com.runehive.content.store.Store.
Definition at line 111 of file RecipeForDisasterStore.java.
{
        return StoreType.DEFAULT;
    }
References com.runehive.content.store.StoreType.DEFAULT.
Member Data Documentation
items
final StoreItem [] com.runehive.content.store.impl.RecipeForDisasterStore.items
Initial value:
= {
            new StoreItem(7453, 1, OptionalInt.of(10000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7454, 1, OptionalInt.of(20000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7455, 1, OptionalInt.of(30000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7456, 1, OptionalInt.of(40000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7457, 1, OptionalInt.of(50000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7458, 1, OptionalInt.of(60000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7459, 1, OptionalInt.of(70000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7460, 1, OptionalInt.of(80000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7461, 1, OptionalInt.of(90000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7462, 1, OptionalInt.of(100000), Optional.of(CurrencyType.COINS))
    }
Definition at line 25 of file RecipeForDisasterStore.java.
{
            new StoreItem(7453, 1, OptionalInt.of(10000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7454, 1, OptionalInt.of(20000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7455, 1, OptionalInt.of(30000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7456, 1, OptionalInt.of(40000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7457, 1, OptionalInt.of(50000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7458, 1, OptionalInt.of(60000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7459, 1, OptionalInt.of(70000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7460, 1, OptionalInt.of(80000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7461, 1, OptionalInt.of(90000), Optional.of(CurrencyType.COINS)),
            new StoreItem(7462, 1, OptionalInt.of(100000), Optional.of(CurrencyType.COINS))
    };
Referenced by open(), RecipeForDisasterStore(), and refresh().
The documentation for this class was generated from the following file:
java/com/runehive/content/store/impl/RecipeForDisasterStore.java