RuneHive-Game: com.runehive.content.activity.panel.ActivityPanel Class Reference
com.runehive.content.activity.panel.ActivityPanel Class Reference
Handles the activity panel.
Static Public Member Functions
static void clear (Player player)
Clears the activity panel.
static void timedClear (Player player, int delay)
Clears the activity panel after a defined set of time.
static void update (Activity_Panel panel)
Sends all the information for the activity panel.
static void update (Player player, int amount, String header, String footer, Item container, String... strings)
Sends all the information for the activity panel.
static void update (Player player, int amount, String header, String footer, Item[] container, String... strings)
Sends all the information for the activity panel.
static void update (Player player, int amount, String title, Item item, String... strings)
Sends all the information for the activity panel.
static void update (Player player, int amount, String title, String footer, String... strings)
Sends all the information for the activity panel.
Detailed Description
Handles the activity panel.
Author
Daniel.
Definition at line 18 of file ActivityPanel.java.
Member Function Documentation
clear()
void com.runehive.content.activity.panel.ActivityPanel.clear (Player player) static
Clears the activity panel.
Definition at line 57 of file ActivityPanel.java.
{
        player.send(new SendItemOnInterface(38016));
        player.send(new SendString("", 38003));
        player.send(new SendString("", 38004));
        player.send(new SendString("", 38005));
        player.send(new SendString("", 38006));
        player.send(new SendString("", 38007));
        player.send(new SendString("", 38008));
        player.send(new SendProgressBar(38008, -1));
        player.send(new SendForceTab(Config.INVENTORY_TAB));
        player.interfaceManager.setSidebar(Config.ACTIVITY_TAB, -1);
    }
References com.runehive.Config.ACTIVITY_TAB, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.Config.INVENTORY_TAB, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar().
Referenced by com.runehive.content.activity.impl.fightcaves.FightCaves.cleanup(), com.runehive.content.activity.impl.godwars.GodwarsActivity.cleanup(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.cleanup(), com.runehive.content.activity.inferno.Inferno.cleanup(), com.runehive.content.activity.impl.barrows.Barrows.finish(), com.runehive.content.activity.impl.magearena.MageArena.finish(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.finish(), com.runehive.game.action.impl.TutorialActivity.finish(), and timedClear().
timedClear()
void com.runehive.content.activity.panel.ActivityPanel.timedClear (Player player, int delay) static
Clears the activity panel after a defined set of time.
Definition at line 71 of file ActivityPanel.java.
{
        World.schedule(delay, () -> clear(player));
    }
References clear(), and com.runehive.game.world.World.schedule().
update() [1/5]
void com.runehive.content.activity.panel.ActivityPanel.update (Activity_Panel panel) static
Sends all the information for the activity panel.
Definition at line 35 of file ActivityPanel.java.
{
        update(panel.getPlayer(), panel.getProgress(), panel.getHeader(), panel.getFooter(), new Item[]{panel.getItem()}, panel.getText());
    }
References update().
update() [2/5]
void com.runehive.content.activity.panel.ActivityPanel.update (Player player, int amount, String header, String footer, Item container, String... strings) static
Sends all the information for the activity panel.
Definition at line 30 of file ActivityPanel.java.
{
        update(player, amount, header, footer, new Item[]{container}, strings);
    }
References update().
update() [3/5]
void com.runehive.content.activity.panel.ActivityPanel.update (Player player, int amount, String header, String footer, Item[] container, String... strings) static
Sends all the information for the activity panel.
Definition at line 40 of file ActivityPanel.java.
{
        player.interfaceManager.setSidebar(Config.ACTIVITY_TAB, 38000);
        if (!player.interfaceManager.isSidebar(Config.ACTIVITY_TAB, 38000)) {
            player.send(new SendForceTab(Config.ACTIVITY_TAB));
        }
        for (int index = 0, string = 38005; index < strings.length; index++, string += 1) {
            player.send(new SendString(strings[index], string));
        }
        if (container != null) {
            player.send(new SendItemOnInterface(38016, container));
        }
        player.send(new SendString(header, 38003));
        player.send(new SendProgressBar(38015, amount));
        player.send(new SendString(amount == -1 ? "" : footer, 38004));
    }
References com.runehive.Config.ACTIVITY_TAB, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.isSidebar(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar().
update() [4/5]
void com.runehive.content.activity.panel.ActivityPanel.update (Player player, int amount, String title, Item item, String... strings) static
Sends all the information for the activity panel.
Definition at line 25 of file ActivityPanel.java.
{
        update(player, amount, title, "Activity Completion:", new Item[]{item}, strings);
    }
References update().
update() [5/5]
void com.runehive.content.activity.panel.ActivityPanel.update (Player player, int amount, String title, String footer, String... strings) static
Sends all the information for the activity panel.
Definition at line 20 of file ActivityPanel.java.
{
        update(player, amount, title, footer, new Item[]{}, strings);
    }
References update().
Referenced by com.runehive.content.activity.impl.fightcaves.FightCaves.create(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.create(), com.runehive.content.activity.inferno.Inferno.create(), com.runehive.content.activity.impl.barrows.Barrows.update(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.update(), com.runehive.content.activity.impl.fightcaves.FightCaves.update(), com.runehive.content.activity.impl.godwars.GodwarsActivity.update(), com.runehive.content.activity.impl.magearena.MageArena.update(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.update(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.update(), com.runehive.content.activity.inferno.Inferno.update(), update(), update(), update(), update(), and com.runehive.game.action.impl.TutorialActivity.update().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/panel/ActivityPanel.java