RuneHive-Game: com.runehive.content.itemaction.impl.ViggorasChainmace Class Reference
com.runehive.content.itemaction.impl.ViggorasChainmace Class Reference
Public Member Functions
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
String message (Item item)
The message of the action.
String toString ()
Static Public Attributes
static final short ETHER_ID = 21820
static final short VIGGORAS_CHAINMACE_CHARGED_ID = 22545
static final short VIGGORAS_CHAINMACE_UNCHARGED_ID = 22542
Private Member Functions
void charge (Player player, int amount)
void check (Player player)
Detailed Description
Definition at line 10 of file ViggorasChainmace.java.
Member Function Documentation
charge()
void com.runehive.content.itemaction.impl.ViggorasChainmace.charge (Player player, int amount) private
Definition at line 95 of file ViggorasChainmace.java.
{
        if (amount > player.inventory.computeAmountForId(ETHER_ID)) {
            amount = player.inventory.computeAmountForId(ETHER_ID);
        }
        if (amount > 0) {
            player.inventory.remove(ETHER_ID, amount);
            player.inventory.refresh();
            player.viggorasChainmaceCharges += amount;
            player.message("You added " + amount + " charges to your "+name()+"");
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), ETHER_ID, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), and com.runehive.game.world.items.containers.ItemContainer.remove().
Referenced by itemOnItem().
check()
void com.runehive.content.itemaction.impl.ViggorasChainmace.check (Player player) private
Definition at line 91 of file ViggorasChainmace.java.
{
        player.message("You have " + Utility.formatDigits(player.viggorasChainmaceCharges) + " charges in your "+name()+".");
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.Player.message(), name(), and com.runehive.game.world.entity.mob.player.Player.viggorasChainmaceCharges.
Referenced by equipment(), and inventory().
drop()
boolean com.runehive.content.itemaction.impl.ViggorasChainmace.drop (Player player, Item item)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 76 of file ViggorasChainmace.java.
{
        if (item.getId() != VIGGORAS_CHAINMACE_CHARGED_ID) {
            return false;
        }
        player.inventory.remove(VIGGORAS_CHAINMACE_CHARGED_ID);
        player.inventory.add(VIGGORAS_CHAINMACE_UNCHARGED_ID, 1);
        player.inventory.add(ETHER_ID, 1000 + player.viggorasChainmaceCharges);
        player.viggorasChainmaceCharges = 0;
        player.message("You uncharge your "+name()+".");
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), ETHER_ID, com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.ItemContainer.remove(), VIGGORAS_CHAINMACE_CHARGED_ID, VIGGORAS_CHAINMACE_UNCHARGED_ID, and com.runehive.game.world.entity.mob.player.Player.viggorasChainmaceCharges.
equipment()
boolean com.runehive.content.itemaction.impl.ViggorasChainmace.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 64 of file ViggorasChainmace.java.
{
        if (item.getId() != VIGGORAS_CHAINMACE_CHARGED_ID) {
            return false;
        }
        if (opcode == 1) {
            check(player);
            return true;
        }
        return true;
    }
References check(), com.runehive.game.world.items.Item.getId(), and VIGGORAS_CHAINMACE_CHARGED_ID.
inventory()
boolean com.runehive.content.itemaction.impl.ViggorasChainmace.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 50 of file ViggorasChainmace.java.
{
        if (item.getId() != VIGGORAS_CHAINMACE_CHARGED_ID) {
            return false;
        }
        if (opcode == 2) {
            check(player);
            return true;
        }
        return false;
    }
References check(), com.runehive.game.world.items.Item.getId(), and VIGGORAS_CHAINMACE_CHARGED_ID.
itemOnItem()
boolean com.runehive.content.itemaction.impl.ViggorasChainmace.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 22 of file ViggorasChainmace.java.
{
        System.out.println("?????");
        if ((first.getId() != VIGGORAS_CHAINMACE_UNCHARGED_ID && second.getId() != VIGGORAS_CHAINMACE_UNCHARGED_ID) && (first.getId() != VIGGORAS_CHAINMACE_CHARGED_ID && second.getId() != VIGGORAS_CHAINMACE_CHARGED_ID)) {
            System.out.println("dfgdfgdfg");
            return false;
        }
        if(first.getId() == ETHER_ID || second.getId() == ETHER_ID) {
            if (first.getId() == VIGGORAS_CHAINMACE_UNCHARGED_ID || second.getId() == VIGGORAS_CHAINMACE_UNCHARGED_ID) {
                if(!player.inventory.contains(ETHER_ID, 1000)) {
                    player.message("You need at least 1000 "+ ItemDefinition.get(ETHER_ID).getName() +" to charge the "+name()+".");
                    return true;
                }
                player.inventory.remove(ETHER_ID, 1000);
                player.inventory.remove(VIGGORAS_CHAINMACE_UNCHARGED_ID);
                player.inventory.add(VIGGORAS_CHAINMACE_CHARGED_ID, 1);
                player.inventory.refresh();
            } else {
                System.out.println("Recharge craws bow");
                player.send(new SendInputAmount("How many charges would you like add? (0-"+player.inventory.computeAmountForId(ETHER_ID)+")", 10, input -> charge(player, Integer.parseInt(input))));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), charge(), com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), ETHER_ID, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), VIGGORAS_CHAINMACE_CHARGED_ID, and VIGGORAS_CHAINMACE_UNCHARGED_ID.
name()
String com.runehive.content.itemaction.impl.ViggorasChainmace.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 17 of file ViggorasChainmace.java.
{
        return "Viggora's chainmace";
    }
Referenced by charge(), check(), drop(), and itemOnItem().
Member Data Documentation
ETHER_ID
final short com.runehive.content.itemaction.impl.ViggorasChainmace.ETHER_ID = 21820 static
Definition at line 14 of file ViggorasChainmace.java.
Referenced by charge(), drop(), and itemOnItem().
VIGGORAS_CHAINMACE_CHARGED_ID
final short com.runehive.content.itemaction.impl.ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID = 22545 static
Definition at line 13 of file ViggorasChainmace.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.attack(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), com.runehive.content.itemaction.ItemActionRepository.declare(), drop(), equipment(), inventory(), and itemOnItem().
VIGGORAS_CHAINMACE_UNCHARGED_ID
final short com.runehive.content.itemaction.impl.ViggorasChainmace.VIGGORAS_CHAINMACE_UNCHARGED_ID = 22542 static
Definition at line 12 of file ViggorasChainmace.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.itemaction.ItemActionRepository.declare(), drop(), and itemOnItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/ViggorasChainmace.java