RuneHive-Game: com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect Class Reference
com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect Class Reference
The combat effect applied when a character needs to be poisoned.
Public Member Functions
boolean apply (Mob mob)
Applies this effect to mob.
CombatPoisonEffect ()
Creates a new CombatPoisonEffect.
boolean onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
void process (Mob mob)
Provides processing for this effect on mob.
boolean removeOn (Mob mob)
Removes this effect from mob if needed.
Public Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
CombatEffect (int delay)
Creates a new CombatEffect.
final boolean start (Mob mob)
Starts this combat effect by scheduling a task utilizing the abstract methods in this class.
Static Public Member Functions
static Optional< PoisonType > getPoisonType (int npc)
Gets the PoisonType for npc wrapped in an optional.
static Optional< PoisonType > getPoisonType (Item item)
Gets the PoisonType for item wrapped in an optional.
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
static Collection< CombatEffect > values ()
Returns an unmodifiable view of the combat effect listeners.
Private Attributes
int amount
The amount of times this player has been hit.
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
static final Map< CombatEffectType, CombatEffect > EFFECTS = new HashMap<>()
The map of all of the combat effect types mapped to their respective listeners.
Protected Member Functions inherited from com.runehive.game.world.entity.combat.effect.CombatEffect
final int getDelay ()
Gets the delay for this individual combat effect.
Detailed Description
The combat effect applied when a character needs to be poisoned.
Author
lare96 http://github.com/lare96
Definition at line 23 of file CombatPoisonEffect.java.
Constructor & Destructor Documentation
CombatPoisonEffect()
com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.CombatPoisonEffect ()
Creates a new CombatPoisonEffect.
Definition at line 29 of file CombatPoisonEffect.java.
{
        super(25);
    }
Member Function Documentation
apply()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.apply (Mob mob)
Applies this effect to mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 34 of file CombatPoisonEffect.java.
{
        if (mob.getPoisonType() == null || mob.isPoisoned() || mob.isVenomed()) {
            return false;
        }
        if (mob.isNpc() && mob.getNpc().definition.hasPoisonImmunity()) {
            return false;
        }
        if (mob.isPlayer() && mob.getPlayer().equipment
                .retrieve(Equipment.HELM_SLOT)
                .filter(helm -> helm.getId() == 13197 || helm.getId() == 13199 || helm.getId() == 12931)
                .isPresent()) {
            return false;
        }
        if (mob.isPlayer()) {
            Player player = mob.getPlayer();
            if (player.getPoisonImmunity().get() > 0 || mob.isDead())
                return false;
            player.send(new SendMessage("You have been poisoned!"));
            player.send(new SendPoison(SendPoison.PoisonType.REGULAR));
        }
        mob.getPoisonDamage().set(mob.getPoisonType().getDamage());
        amount = 4;
        return true;
    }
References amount, com.runehive.util.MutableNumber.get(), com.runehive.game.world.entity.mob.player.Player.getPoisonImmunity(), com.runehive.game.world.items.containers.equipment.Equipment.HELM_SLOT, com.runehive.net.packet.out.SendPoison.PoisonType.REGULAR, and com.runehive.game.world.entity.mob.player.Player.send().
getPoisonType() [1/2]
Optional< PoisonType > com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType (int npc) static
Gets the PoisonType for npc wrapped in an optional.
If a poison type doesn't exist for the NPC then an empty optional is returned.
Parameters
npc the NPC to get the poison type for
Returns
the poison type for this NPC wrapped in an optional, or an empty optional if no poison type exists
Definition at line 124 of file CombatPoisonEffect.java.
{
        NpcDefinition def = NpcDefinition.DEFINITIONS[npc];
        if (def == null || !def.isAttackable() || !def.isPoisonous()) {
            return Optional.empty();
        }
        if (def.getCombatLevel() < 25) {
            return Optional.of(PoisonType.WEAK_NPC);
        }
        if (def.getCombatLevel() < 75) {
            return Optional.of(PoisonType.DEFAULT_NPC);
        }
        if (def.getCombatLevel() < 200) {
            return Optional.of(PoisonType.STRONG_NPC);
        }
        if (def.getCombatLevel() < 225) {
            return Optional.of(PoisonType.SUPER_NPC);
        }
        return Optional.of(PoisonType.EXTRAORDINARY_NPC);
    }
References com.runehive.game.world.entity.combat.PoisonType.DEFAULT_NPC, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.DEFINITIONS, com.runehive.game.world.entity.combat.PoisonType.EXTRAORDINARY_NPC, com.runehive.game.world.entity.combat.PoisonType.STRONG_NPC, com.runehive.game.world.entity.combat.PoisonType.SUPER_NPC, and com.runehive.game.world.entity.combat.PoisonType.WEAK_NPC.
getPoisonType() [2/2]
Optional< PoisonType > com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType (Item item) static
Gets the PoisonType for item wrapped in an optional.
If a poison type doesn't exist for the item then an empty optional is returned.
Parameters
item the item to get the poison type for
Returns
the poison type for this item wrapped in an optional, or an empty optional if no poison type exists
Definition at line 100 of file CombatPoisonEffect.java.
{
        if (item != null) {
            String name = item.getName();
            if (name.endsWith("(p)")) {
                return Optional.of(PoisonType.DEFAULT_MELEE);
            }
            if (name.endsWith("(p+)")) {
                return Optional.of(PoisonType.STRONG_MELEE);
            }
            if (name.endsWith("(p++)")) {
                return Optional.of(PoisonType.SUPER_MELEE);
            }
        }
        return Optional.empty();
    }
References com.runehive.game.world.entity.combat.PoisonType.DEFAULT_MELEE, com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.combat.PoisonType.STRONG_MELEE, and com.runehive.game.world.entity.combat.PoisonType.SUPER_MELEE.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), and com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz().
onLogin()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.onLogin (Mob mob)
Executed on login, primarily used to re-apply the effect to mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 83 of file CombatPoisonEffect.java.
{
        boolean poisoned = mob.isPoisoned();
        if (poisoned && mob.isPlayer()) {
            mob.getPlayer().send(new SendPoison(SendPoison.PoisonType.REGULAR));
        }
        return poisoned;
    }
References com.runehive.net.packet.out.SendPoison.PoisonType.REGULAR.
process()
void com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.process (Mob mob)
Provides processing for this effect on mob.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 73 of file CombatPoisonEffect.java.
{
        amount--;
        mob.damage(new Hit(mob.getPoisonDamage().get(), Hitsplat.POISON, HitIcon.NONE));
        if (amount == 0) {
            amount = 4;
            mob.getPoisonDamage().decrementAndGet();
        }
    }
References amount, com.runehive.game.world.entity.combat.hit.HitIcon.NONE, and com.runehive.game.world.entity.combat.hit.Hitsplat.POISON.
removeOn()
boolean com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.removeOn (Mob mob)
Removes this effect from mob if needed.
Reimplemented from com.runehive.game.world.entity.combat.effect.CombatEffect.
Definition at line 63 of file CombatPoisonEffect.java.
{
        boolean remove = mob.isVenomed() || !mob.isPoisoned() || mob.isDead();
        if (remove && mob.isPlayer()) {
            Player player = (Player) mob;
            player.send(new SendPoison(SendPoison.PoisonType.NO_POISON));
        }
        return remove;
    }
References com.runehive.net.packet.out.SendPoison.PoisonType.NO_POISON, and com.runehive.game.world.entity.mob.player.Player.send().
Member Data Documentation
amount
int com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.amount private
The amount of times this player has been hit.
Definition at line 26 of file CombatPoisonEffect.java.
Referenced by apply(), and process().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/effect/impl/CombatPoisonEffect.java