RuneHive-Game: com.runehive.net.packet.in.ExaminePacketListener Class Reference
com.runehive.net.packet.in.ExaminePacketListener Class Reference
Handles the in examine packet.
Public Member Functions
void handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Static Private Member Functions
static void handleInterfaceExamine (Player player, GamePacket packet)
Static Private Attributes
static final int INTERFACE = 0
static final int ITEM = 2
static final int NPC = 1
static final int OBJECT = 3
Detailed Description
Handles the in examine packet.
Author
Daniel
Definition at line 26 of file ExaminePacketListener.java.
Member Function Documentation
handleInterfaceExamine()
void com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine (Player player, GamePacket packet) static private
Definition at line 59 of file ExaminePacketListener.java.
{
        int slot = packet.readShort();
        int interfaceId = packet.readShort();
        int itemId = packet.readShort();
        if (PlayerRight.isDeveloper(player)) {
            player.send(new SendMessage("[Examine] - slot: " + slot + " -- interfaceId: " + interfaceId + " -- itemId: " + itemId, MessageColor.DEVELOPER));
        }
        if (slot == -1) {
            player.settings.clientWidth = interfaceId;
            player.settings.clientHeight = itemId;
            return;
        }
        switch (interfaceId) {
            case Inventory.INVENTORY_DISPLAY_ID: {
                Item item = player.inventory.get(slot);
                if (item == null || item.getId() != itemId) return;
                final ItemDef itemDef = ItemDefLoader.map.get(itemId);
                if (itemDef != null) {
                    String examine = itemDef.getExamine();
                    if (!"null".equals(examine))
                        player.send(new SendMessage(examine));
                }
                if (item.isTradeable()) {
                    String message = "";
                    message += "Item: <col=A52929>" + item.getName() + "</col> ";
                    message += "Value: <col=A52929>" + Utility.formatDigits(item.getValue(PriceType.VALUE)) + " (" + Utility.formatDigits(item.getValue(PriceType.VALUE) * item.getAmount()) + ")</col> ";
                    message += "High alch: <col=A52929>" + Utility.formatDigits(item.getValue(PriceType.HIGH_ALCH_VALUE)) + "</col> ";
                    player.send(new SendMessage(message));
                }
                break;
            }
            case 26816: {
                if (!player.attributes.has("DROP_SIMULATOR_SORTED_LIST")) return;
                Item[] items = player.attributes.get("DROP_SIMULATOR_SORTED_LIST");
                if (slot < 0 || slot >= items.length) return;
                Item item = items[slot];
                if (item.isTradeable()) {
                    String message = "";
                    message += "Item: <col=A52929>" + item.getName() + "</col> ";
                    message += "Value: <col=A52929>" + Utility.formatDigits(item.getValue(PriceType.VALUE)) + " (" + Utility.formatDigits(item.getValue(PriceType.VALUE) * item.getAmount()) + ")</col> ";
                    message += "High alch: <col=A52929>" + Utility.formatDigits(item.getValue(PriceType.HIGH_ALCH_VALUE));
                    player.send(new SendMessage(message));
                }
                break;
            }
        }
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.util.MessageColor.DEVELOPER, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.Item.getValue(), com.runehive.util.generic.GenericAttributes.has(), com.runehive.game.world.items.containers.pricechecker.PriceType.HIGH_ALCH_VALUE, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.inventory.Inventory.INVENTORY_DISPLAY_ID, com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), com.runehive.game.world.items.Item.isTradeable(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE.
Referenced by handlePacket().
handlePacket()
void com.runehive.net.packet.in.ExaminePacketListener.handlePacket (Player player, GamePacket packet)
Handles the packet that has just been received.
Parameters
player The player receiving this packet.
packet The packet that has been received.
Implements com.runehive.net.packet.PacketListener.
Definition at line 34 of file ExaminePacketListener.java.
{
        final int type = packet.readByte(false);
        switch (type) {
            case INTERFACE: {
                handleInterfaceExamine(player, packet);
                break;
            }
            case NPC: {
                int npcId = packet.readShort(false);
                player.getEvents().interact(player, new NpcExamineEvent(npcId));
                break;
            }
            case ITEM: {
                int itemId = packet.readShort(false);
                player.getEvents().interact(player, new ItemExamineEvent(itemId));
                break;
            }
            case OBJECT: {
                int objectId = packet.readShort(false);
                player.getEvents().interact(player, new ObjectExamineEvent(objectId));
                break;
            }
        }
    }
References com.runehive.game.world.entity.mob.player.Player.getEvents(), handleInterfaceExamine(), INTERFACE, ITEM, NPC, and OBJECT.
Member Data Documentation
INTERFACE
final int com.runehive.net.packet.in.ExaminePacketListener.INTERFACE = 0 static private
Definition at line 28 of file ExaminePacketListener.java.
Referenced by handlePacket().
ITEM
final int com.runehive.net.packet.in.ExaminePacketListener.ITEM = 2 static private
Definition at line 30 of file ExaminePacketListener.java.
Referenced by handlePacket().
NPC
final int com.runehive.net.packet.in.ExaminePacketListener.NPC = 1 static private
Definition at line 29 of file ExaminePacketListener.java.
Referenced by handlePacket().
OBJECT
final int com.runehive.net.packet.in.ExaminePacketListener.OBJECT = 3 static private
Definition at line 31 of file ExaminePacketListener.java.
Referenced by handlePacket().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/in/ExaminePacketListener.java