RuneHive-Game: com.runehive.game.world.pathfinding.path.Path Class Reference
com.runehive.game.world.pathfinding.path.Path Class Reference
Represents a single path in the path finding system.
Public Member Functions
void addSteps (final Movement movement)
Position getDestination ()
Gets the ending location of the path.
Deque< Position > getMoves ()
Gets all moves of the Path.
Position getOrigin ()
Gets the starting location of the path.
boolean isPossible ()
Gets the condition if the path is possible.
Path (Deque< Position > moves)
Creates a new Path.
Position poll ()
Removing one of the last(but first in the queue) walking points.
Private Attributes
final Deque< Position > moves
The deque of all the moves the path has.
Detailed Description
Represents a single path in the path finding system.
Author
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Definition at line 13 of file Path.java.
Constructor & Destructor Documentation
Path()
com.runehive.game.world.pathfinding.path.Path.Path (Deque< Position > moves)
Creates a new Path.
Parameters
moves All of the path moves.
Definition at line 23 of file Path.java.
{
        this.moves = moves;
    }
References moves.
Member Function Documentation
addSteps()
void com.runehive.game.world.pathfinding.path.Path.addSteps (final Movement movement)
Definition at line 72 of file Path.java.
{
        movement.reset();
        while (!moves.isEmpty()) {
            final Position next = moves.poll();
            if (next == null) break;
            movement.addStep(next.getX(), next.getY());
        }
        movement.finish();
    }
References com.runehive.game.world.entity.mob.movement.Movement.addStep(), com.runehive.game.world.entity.mob.movement.Movement.finish(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), moves, and com.runehive.game.world.entity.mob.movement.Movement.reset().
Referenced by com.runehive.game.world.entity.mob.movement.Movement.addPath().
getDestination()
Position com.runehive.game.world.pathfinding.path.Path.getDestination ()
Gets the ending location of the path.
Returns
the ending position.
Definition at line 41 of file Path.java.
{
        return moves.peekLast();
    }
References moves.
getMoves()
Deque< Position > com.runehive.game.world.pathfinding.path.Path.getMoves ()
Gets all moves of the Path.
Returns
the deque containing the coordinates.
Definition at line 59 of file Path.java.
{
        return moves;
    }
References moves.
getOrigin()
Position com.runehive.game.world.pathfinding.path.Path.getOrigin ()
Gets the starting location of the path.
Returns
the starting position.
Definition at line 32 of file Path.java.
{
        return moves.getFirst();
    }
References moves.
isPossible()
boolean com.runehive.game.world.pathfinding.path.Path.isPossible ()
Gets the condition if the path is possible.
Returns
the condition if the path is possible to be done.
Definition at line 50 of file Path.java.
{
        return moves != null && !moves.isEmpty();
    }
References moves.
Referenced by com.runehive.game.world.entity.mob.movement.Movement.addPath().
poll()
Position com.runehive.game.world.pathfinding.path.Path.poll ()
Removing one of the last(but first in the queue) walking points.
Returns
true if removed, false otherwise.
Definition at line 68 of file Path.java.
{
        return moves.pollFirst();
    }
References moves.
Member Data Documentation
moves
final Deque<Position> com.runehive.game.world.pathfinding.path.Path.moves private
The deque of all the moves the path has.
Definition at line 16 of file Path.java.
Referenced by addSteps(), getDestination(), getMoves(), getOrigin(), isPossible(), Path(), and poll().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/pathfinding/path/Path.java