RuneHive-Game: com.runehive.game.world.entity.combat.CombatTarget Class Reference
com.runehive.game.world.entity.combat.CombatTarget Class Reference
Public Member Functions
Mob getTarget ()
void setTarget (Mob target)
Static Public Member Functions
static void checkAggression (Player player)
Package Functions
void checkAggression (Position spawn)
Checks the aggression for this mob if a target is set.
CombatTarget (Mob mob)
void compare (Mob other, int level, Position spawn)
Compares the given mob with the current target.
boolean isTarget (Mob mob)
void resetTarget ()
Private Attributes
int distance
final Mob mob
Mob target
Static Private Attributes
static final int AGGRESSION_TIMEOUT = 20
The aggression timeout in minutes.
Detailed Description
Definition at line 14 of file CombatTarget.java.
Constructor & Destructor Documentation
CombatTarget()
com.runehive.game.world.entity.combat.CombatTarget.CombatTarget (Mob mob) package
Definition at line 22 of file CombatTarget.java.
{
        this.mob = mob;
        this.distance = Integer.MAX_VALUE;
    }
References mob.
Member Function Documentation
checkAggression() [1/2]
void com.runehive.game.world.entity.combat.CombatTarget.checkAggression (Player player) static
Definition at line 110 of file CombatTarget.java.
{
        if (!player.isVisible())
            return;
        if (player.viewport.getNpcsInViewport().isEmpty())
            return;
        if (player.getCombat().inCombat() && !Area.inMulti(player))
            return;
        for (Npc npc : player.viewport.getNpcsInViewport()) {
            if (npc == null || !npc.isValid())
                continue;
            if (!npc.definition.isAttackable() || !npc.definition.isAggressive())
                continue;
            if (npc.isDead() || !npc.isVisible() || npc.forceWalking)
                continue;
            if (npc.locking.locked())
                continue;
            if (player.aggressionTimer.elapsed(AGGRESSION_TIMEOUT, TimeUnit.MINUTES)
                    && !Area.inGodwars(npc)
                    && player.activity == null) {
                if (npc.getCombat().isAttacking(player) && !player.getCombat().isAttacking(npc))
                    npc.getCombat().reset();
                continue;
            }
            /* Godwars check */
            //TODO CLEANER WAY SORRY MICHAEL LOL
            if (Area.inGodwars(npc) && !Area.inGodwarsChambers(npc)) {
                if (npc.npcAssistant.isArmadyl()) {
                    boolean found = false;
                    for (Npc npc1 : npc.getRegion().getNpcs(npc.getHeight())) {
                        if (Utility.getDistance(npc, npc1.getPosition()) < 5 && !npc1.npcAssistant.isArmadyl()) {
                            found = true;
                            npc.getCombat().attack(npc1);
                            break;
                        }
                    }
                    if (found) {
                        continue;
                    }
                    if (player.equipment.hasArmadyl()) {
                        continue;
                    }
                } else if (npc.npcAssistant.isBandos()) {
                    boolean found = false;
                    for (Npc npc1 : npc.getRegion().getNpcs(npc.getHeight())) {
                        if (Utility.getDistance(npc, npc1.getPosition()) < 5 && !npc1.npcAssistant.isBandos()) {
                            found = true;
                            npc.getCombat().attack(npc1);
                            break;
                        }
                    }
                    if (found) {
                        continue;
                    }
                    if (player.equipment.hasBandos()) {
                        continue;
                    }
                } else if (npc.npcAssistant.isSaradomin()) {
                    boolean found = false;
                    for (Npc npc1 : npc.getRegion().getNpcs(npc.getHeight())) {
                        if (Utility.getDistance(npc, npc1.getPosition()) < 5 && !npc1.npcAssistant.isSaradomin()) {
                            found = true;
                            npc.getCombat().attack(npc1);
                            break;
                        }
                    }
                    if (found) {
                        continue;
                    }
                    if (player.equipment.hasSaradomin()) {
                        continue;
                    }
                } else if (npc.npcAssistant.isZamorak()) {
                    boolean found = false;
                    for (Npc npc1 : npc.getRegion().getNpcs(npc.getHeight())) {
                        if (Utility.getDistance(npc, npc1.getPosition()) < 5 && !npc1.npcAssistant.isZamorak()) {
                            found = true;
                            npc.getCombat().attack(npc1);
                            break;
                        }
                    }
                    if (found) {
                        continue;
                    }
                    if (player.equipment.hasZamorak()) {
                        continue;
                    }
                }
            }
            npc.getCombat().compare(player, npc.definition.getCombatLevel(),  npc.spawnPosition);
        }
    }
References com.runehive.game.world.entity.mob.Mob.activity, AGGRESSION_TIMEOUT, com.runehive.game.world.entity.mob.player.Player.aggressionTimer, com.runehive.util.Stopwatch.elapsed(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.util.Utility.getDistance(), com.runehive.game.world.region.Region.getNpcs(), com.runehive.game.world.entity.mob.Viewport.getNpcsInViewport(), com.runehive.game.world.entity.Entity.getRegion(), com.runehive.game.world.items.containers.equipment.Equipment.hasArmadyl(), com.runehive.game.world.items.containers.equipment.Equipment.hasBandos(), com.runehive.game.world.items.containers.equipment.Equipment.hasSaradomin(), com.runehive.game.world.items.containers.equipment.Equipment.hasZamorak(), com.runehive.game.world.position.Area.inGodwars(), com.runehive.game.world.position.Area.inGodwarsChambers(), com.runehive.game.world.position.Area.inMulti(), com.runehive.game.world.entity.Entity.isVisible(), and com.runehive.game.world.entity.mob.player.Player.viewport.
checkAggression() [2/2]
void com.runehive.game.world.entity.combat.CombatTarget.checkAggression (Position spawn) package
Checks the aggression for this mob if a target is set.
Definition at line 28 of file CombatTarget.java.
{
        /* No target */
        if (target == null)
            return;
        /* The target is unreachable */
        if (distance == Integer.MAX_VALUE)
            return;
        /* The mob is too far from spawn */
        if (Utility.getDistance(mob, spawn) > Region.VIEW_DISTANCE && !Area.inFightCaves(mob) && !Area.inGodwarsChambers(mob)) {
            if (mob.getCombat().isUnderAttack()) {
                Mob trgt = target;
                distance = Integer.MAX_VALUE;
                mob.getCombat().reset();
                if (mob.isNpc() && mob.getNpc().boundaries.length > 0) {
                    Position pos = Utility.randomElement(mob.getNpc().boundaries);
                    mob.interact(trgt);
                    mob.walkExactlyTo(pos, () -> {
                        mob.resetFace();
                        resetTarget();
                    });
                }
            } else {
                mob.getCombat().reset();
                mob.resetFace();
                resetTarget();
            }
            return;
        }
        int dist = Utility.getDistance(target, mob);
        int aggressionRadius = mob.width() + 3;
        if (Area.inGodwarsChambers(mob)) {
            aggressionRadius = Region.SIZE;
        }
        /* The mob is too far from target */
        if (dist > aggressionRadius)
            return;
        /* The mob is already in combat with the target */
        if (mob.getCombat().isAttacking(target))
            return;
        if (!mob.getCombat().attack(target)) {
            mob.getCombat().reset();
        }
    }
References distance, com.runehive.util.Utility.getDistance(), com.runehive.game.world.position.Area.inFightCaves(), com.runehive.game.world.position.Area.inGodwarsChambers(), mob, com.runehive.util.Utility.randomElement(), resetTarget(), com.runehive.game.world.region.Region.SIZE, target, and com.runehive.game.world.region.Region.VIEW_DISTANCE.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.sequence().
compare()
void com.runehive.game.world.entity.combat.CombatTarget.compare (Mob other, int level, Position spawn) package
Compares the given mob with the current target.
If the give mob is closer than the current target, the target will be set to the given mob.
Parameters
other the mob to compare to the target
Definition at line 86 of file CombatTarget.java.
{
        int dist = Utility.getDistance(mob, other);
        /* Already targeting this mob */
        if (isTarget(other))
            return;
        /* The npc is too far from target */
        if (dist > Region.VIEW_DISTANCE)
            return;
        if (spawn != null && !(mob instanceof Player && mob.activity != null) && !Area.inFightCaves(mob) && !Area.inGodwars(mob) && Utility.getDistance(other, spawn) > Region.VIEW_DISTANCE)
            return;
        if (other.skills.getCombatLevel() > level * 2 && !Area.inWilderness(mob))
            return;
        /* Found a closer target */
        if (dist < distance && (SimplePathChecker.checkProjectile(mob, other) || SimplePathChecker.checkProjectile(other, mob))) {
            target = other;
            distance = dist;
        }
    }
References com.runehive.game.world.pathfinding.path.SimplePathChecker.checkProjectile(), distance, com.runehive.game.world.entity.skill.SkillManager.getCombatLevel(), com.runehive.util.Utility.getDistance(), com.runehive.game.world.position.Area.inFightCaves(), com.runehive.game.world.position.Area.inGodwars(), com.runehive.game.world.position.Area.inWilderness(), isTarget(), mob, com.runehive.game.world.entity.mob.Mob.skills, target, and com.runehive.game.world.region.Region.VIEW_DISTANCE.
getTarget()
Mob com.runehive.game.world.entity.combat.CombatTarget.getTarget ()
Definition at line 233 of file CombatTarget.java.
{
        return target;
    }
References target.
isTarget()
boolean com.runehive.game.world.entity.combat.CombatTarget.isTarget (Mob mob) package
Definition at line 229 of file CombatTarget.java.
{
        return mob.equals(target);
    }
References mob, and target.
Referenced by compare().
resetTarget()
void com.runehive.game.world.entity.combat.CombatTarget.resetTarget () package
Definition at line 219 of file CombatTarget.java.
                       {
        target = null;
        distance = Integer.MAX_VALUE;
    }
References distance, and target.
Referenced by checkAggression().
setTarget()
void com.runehive.game.world.entity.combat.CombatTarget.setTarget (Mob target)
Definition at line 224 of file CombatTarget.java.
{
        this.target = target;
        distance = Utility.getDistance(mob, target);
    }
References distance, com.runehive.util.Utility.getDistance(), mob, and target.
Member Data Documentation
AGGRESSION_TIMEOUT
final int com.runehive.game.world.entity.combat.CombatTarget.AGGRESSION_TIMEOUT = 20 static private
The aggression timeout in minutes.
Definition at line 17 of file CombatTarget.java.
Referenced by checkAggression().
distance
int com.runehive.game.world.entity.combat.CombatTarget.distance private
Definition at line 20 of file CombatTarget.java.
Referenced by checkAggression(), compare(), resetTarget(), and setTarget().
mob
final Mob com.runehive.game.world.entity.combat.CombatTarget.mob private
Definition at line 18 of file CombatTarget.java.
Referenced by checkAggression(), CombatTarget(), compare(), isTarget(), and setTarget().
target
Mob com.runehive.game.world.entity.combat.CombatTarget.target private
Definition at line 19 of file CombatTarget.java.
Referenced by checkAggression(), compare(), getTarget(), isTarget(), resetTarget(), and setTarget().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/CombatTarget.java