RuneHive-Game: com.runehive.game.world.entity.combat.maxhit.RangeMaxHit Class Reference
com.runehive.game.world.entity.combat.maxhit.RangeMaxHit Class Reference
@Author Origin
Static Public Member Functions
static double getBaseDamage (Mob player)
static double getEffectiveRanged (Mob player)
static double getOtherBonus (Mob player)
static double getPrayerBonus (Mob player)
static int getRangedlevel (Mob player)
static int getStyleBonus (Mob player)
static int maxHit (Mob player)
Detailed Description
@Author Origin
Definition at line 15 of file RangeMaxHit.java.
Member Function Documentation
getBaseDamage()
double com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getBaseDamage (Mob player) static
Definition at line 17 of file RangeMaxHit.java.
{
        int rangestr = player.getBonus(Equipment.RANGED_STRENGTH);
        return (1.3 + (getEffectiveRanged(player) / 10) + (rangestr / 80D) + (getEffectiveRanged(player) * rangestr / 640));
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), getEffectiveRanged(), and com.runehive.game.world.items.containers.equipment.Equipment.RANGED_STRENGTH.
Referenced by maxHit().
getEffectiveRanged()
double com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getEffectiveRanged (Mob player) static
Definition at line 26 of file RangeMaxHit.java.
{
        return Math.floor(((getRangedlevel(player)) * getPrayerBonus(player)) * getOtherBonus(player)) + getStyleBonus(player);
    }
References getOtherBonus(), getPrayerBonus(), getRangedlevel(), and getStyleBonus().
Referenced by getBaseDamage().
getOtherBonus()
double com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getOtherBonus (Mob player) static
Definition at line 50 of file RangeMaxHit.java.
{
        double otherBonus = 1.0;
        Mob target = player.getCombat().getDefender();
            if (FormulaUtils.voidRanger((Player) player)) {
                otherBonus *= 1.10;
            }
            if (FormulaUtils.wearingEliteVoid((Player) player)) {
                otherBonus *= 1.125;
            }
            /*
            * BOWFA, MIGHT ADD COLORED ONES INTO IT. IF SO, ADD HERE.
             */
            if (((Player) player).equipment.contains(23971) && ((Player) player).equipment.contains(25865)) {
                otherBonus *= 1.025;//2.5% damage boost
            }
            if (((Player) player).equipment.contains(23975) && ((Player) player).equipment.contains(25865)) {
                otherBonus *= 1.075;//7.5% damage boost
            }
            if (((Player) player).equipment.contains(23979) && ((Player) player).equipment.contains(25865)) {
                otherBonus *= 1.05;//5.0% damage boost
            }
            if (FormulaUtils.hasCrawsBow((Player) player) && target != null && target.isNpc()) {
                otherBonus += 0.50;
            }
        return otherBonus;
    }
References com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.combat.FormulaUtils.hasCrawsBow(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.combat.FormulaUtils.voidRanger(), and com.runehive.game.world.entity.combat.FormulaUtils.wearingEliteVoid().
Referenced by getEffectiveRanged().
getPrayerBonus()
double com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus (Mob player) static
Definition at line 30 of file RangeMaxHit.java.
{
        double prayerBonus = 1;
        if (player.getStrategy().getCombatType().equals(CombatType.RANGED)) {
            if (player.prayer.isActive(Prayer.SHARP_EYE))
                prayerBonus *= 1.05D; // 5% range level boost
            else if (player.prayer.isActive(Prayer.HAWK_EYE))
                prayerBonus *= 1.10D; // 10% range level boost
            else if (player.prayer.isActive(Prayer.EAGLE_EYE))
                prayerBonus *= 1.15D; // 15% range level boost
            else if (player.prayer.isActive(Prayer.RIGOUR))
                prayerBonus *= 1.20D; // 20% range level boost
        }
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.EAGLE_EYE, com.runehive.game.world.entity.mob.Mob.getStrategy(), com.runehive.game.world.entity.mob.prayer.Prayer.HAWK_EYE, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.combat.CombatType.RANGED, com.runehive.game.world.entity.mob.prayer.Prayer.RIGOUR, and com.runehive.game.world.entity.mob.prayer.Prayer.SHARP_EYE.
Referenced by getEffectiveRanged().
getRangedlevel()
int com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getRangedlevel (Mob player) static
Definition at line 22 of file RangeMaxHit.java.
{
        return player.skills.getLevel(Skill.RANGED);
    }
References com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.RANGED, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by getEffectiveRanged().
getStyleBonus()
int com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getStyleBonus (Mob player) static
Definition at line 45 of file RangeMaxHit.java.
{
        FightStyle style = player.getCombat().getFightType().getStyle();
        return style.equals(FightStyle.ACCURATE) ? 3 : 0;
    }
References com.runehive.game.world.entity.combat.attack.FightStyle.ACCURATE, and com.runehive.game.world.entity.mob.Mob.getCombat().
Referenced by getEffectiveRanged().
maxHit()
int com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.maxHit (Mob player) static
Definition at line 90 of file RangeMaxHit.java.
{
        int maxHit;
        maxHit = (int) getBaseDamage(player);
        return maxHit;
    }
References getBaseDamage(), and maxHit().
Referenced by com.runehive.game.world.entity.combat.attack.FormulaFactory.getModifiedMaxHit(), and maxHit().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/maxhit/RangeMaxHit.java