RuneHive-Game: com.runehive.game.world.entity.mob.npc.Npc Class Reference
com.runehive.game.world.entity.mob.npc.Npc Class Reference
Represents a non-player character in the in-game world.
Public Member Functions
void addToRegion (Region region)
Adds this entity to the specified region.
void appendDeath ()
Handles the mob death.
boolean equals (Object obj)
int getBonus (int index)
int[] getBonuses ()
Combat< Npc > getCombat ()
The combat of the mob.
String getName ()
Gets the name of this entity.
int getPriorityIndex ()
CombatStrategy< Npc > getStrategy ()
The combat strategy of the mob.
EntityType getType ()
Gets the EntityType.
int hashCode ()
boolean isAutoRetaliate ()
State of the mob's auto retaliate.
Npc (int id, int instance, Position position)
Npc (int id, Position position)
Npc (int id, Position position, int walkingRadius, Direction direction)
Npc (int id, Position position, int walkingRadius, int instance, Direction direction)
void onStep ()
void register ()
Registers an entity to the World.
void removeFromRegion (Region region)
Removes this entity from the specified region.
void sequence ()
The method which is invoked every tick.
void setStrategy (CombatStrategy< Npc > strategy)
String toString ()
void unregister ()
Unregisters an entity from the World.
Public Member Functions inherited from com.runehive.game.world.entity.mob.Mob
void animate (Animation animation)
Plays an animation.
void animate (Animation animation, final boolean override)
Plays an animation.
void animate (int animation)
void animate (int animation, boolean override)
void appendBonus (int index, int amount)
void attack (Mob target)
void clearTeleportTarget ()
Resets the teleport target.
void damage (Hit... hits)
Hit decrementHealth (Hit hit)
void face (Direction direction)
Sets the client update flag to face a certain direction.
void face (GameObject object)
Sets the client update flag to face a certain direction.
void face (Mob mob)
void face (Position position)
Sets the client update flag to face a certain direction.
void follow (Mob target)
void forceMove (int animation, int x, int y)
void forceMove (int delay, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
void forceMove (int delay, int delay2, int animation, int animationDelay, int startSpeed, int endSpeed, Position offset, Direction direction)
Creates a force movement action for an entity.
void forceMove (int delay, int delay2, int animation, int startSpeed, int endSpeed, Position offset, Direction direction)
Optional< Animation > getAnimation ()
int getCurrentHealth ()
ForceMovement getForceMovement ()
Optional< Graphic > getGraphic ()
int getId ()
int getListIndex ()
int getMaximumHealth ()
final Npc getNpc ()
final Player getPlayer ()
final MutableNumber getPoisonDamage ()
PoisonType getPoisonType ()
int getTransformId ()
MutableNumber getVenomDamage ()
void graphic (Graphic graphic)
Plays a graphic.
void graphic (Graphic graphic, boolean override)
Plays a graphic.
void graphic (int graphic)
boolean hasPriorityIndex (Mob other)
void heal (int amount)
boolean inActivity ()
boolean inActivity (ActivityType type)
void interact (Mob mob)
Sets the mob interacting with another mob.
boolean isDead ()
boolean isFixingInside ()
final boolean isNpc ()
Check if an entity is an npc.
final boolean isNpc (BooleanInterface< Npc > condition)
Check if an entity is an npc.
final boolean isPlayer ()
Check if an entity is a player.
final boolean isPlayer (Function< Player, Boolean > condition)
Check if an entity is a player.
final boolean isPoisoned ()
boolean isUpdateRequired ()
Checks if mob requires an update.
final boolean isVenomed ()
Mob (Position position)
Constructs a new Mob.
Mob (Position position, boolean visible)
void move (Position position)
Moves the mob to a set position.
void poison (PoisonType type)
Applies poison with an intensity of type to the entity.
final void reset ()
Resets the mob after an update.
void resetAnimation ()
void resetFace ()
Resets the mob's face location.
void resetGraphic ()
final void resetWaypoint ()
Resets the waypoint.
void runTo (Position destination)
void setActivity (Activity activity)
void setBonus (int equipSlot, int bonus)
void setBonuses (int[] bonuses)
void setDead (boolean dead)
void setFixingInside (boolean fixingInside)
void setForceMovement (ForceMovement forceMovement)
void setListIndex (int listIndex)
void speak (String forceChat)
Sets the mob's forced chat.
void takeStep ()
void transform (int transformId)
void transform (int transformId, boolean reload)
Transforms the mob.
void unpoison ()
void unvenom ()
void venom ()
Applies venom to the entity.
void walk (Position destination, boolean ignoreClip)
void walk (Position position)
void walkExactlyTo (Position position)
void walkExactlyTo (Position position, Runnable onDestination)
void walkTo (Interactable target, boolean clearAction, Runnable onDestination)
void walkTo (Interactable target, Runnable onDestination)
void walkTo (Position position)
void walkTo (Position position, Runnable onDestination)
void writeDamage (Hit hit)
void writeFakeDamage (Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.Entity
Entity (Position position)
Entity (Position position, boolean visible)
Position getCenterPosition ()
int getHeight ()
int getIndex ()
Position getPosition ()
Region getRegion ()
int getX ()
int getY ()
boolean is (EntityType type)
final boolean isCustomObject ()
Check if an entity is an object.
final boolean isRegistered ()
final boolean isStaticObject ()
Check if an entity is an object.
boolean isValid ()
Validates this npc based on its current region and registered state.
boolean isVisible ()
int length ()
void setIndex (int index)
void setLength (int length)
void setPosition (Position position)
void setVisible (boolean visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
void setZ (int z)
int width ()
Public Attributes
final AtomicInteger atomicPlayerCount = new AtomicInteger(0)
Position[] boundaries
boolean canAttack
NpcDefinition definition
final Direction faceDirection
final NpcAssistant npcAssistant = new NpcAssistant(this)
Mob owner
int pyroHealth = 24
Pyromancer data.
boolean pyroSnowAttack
final Position spawnPosition
boolean walk
int walkingRadius
Public Attributes inherited from com.runehive.game.world.entity.mob.Mob
ActionManager action = new ActionManager()
Activity activity
final GenericAttributes attributes = new GenericAttributes()
boolean blockFace
boolean blockInteract
Stopwatch damageImmunity = Stopwatch.start()
Position facePosition
Hit firstHit
List< Mob > followers = new LinkedList<>()
String forceChat
ForceMovement forceMovement
boolean forceWalking
final Stopwatch freezeImmunity = Stopwatch.start()
int id = -1
boolean inTeleport
Mob interactingWith
Position lastPosition
final Locking locking = new Locking(this)
MobAnimation mobAnimation = new MobAnimation(updateFlags)
final Movement movement = new Movement(this)
transient long nextAnimation
boolean pathfinderProjectiles = false
boolean positionChange
PrayerBook prayer = new PrayerBook()
boolean regionChange
Hit secondHit
final SkillManager skills = new SkillManager(this)
final SkillManager skills_copy = new SkillManager(this)
boolean teleporting
boolean teleportRegion
Position teleportTarget
final EnumSet< UpdateFlag > updateFlags = EnumSet.noneOf(UpdateFlag.class)
Public Attributes inherited from com.runehive.game.world.entity.Entity
int instance = DEFAULT_INSTANCE
Package Functions
int getDeathTime ()
Private Attributes
final Combat< Npc > combat = new Combat<>(this)
int sequence
CombatStrategy< Npc > strategy
int walkCooldown
Static Private Attributes
static final Logger logger = LogManager.getLogger(Npc.class)
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.mob.Mob
static boolean pathfinderProjectiles (Mob source)
Static Public Member Functions inherited from com.runehive.game.world.Interactable
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Static Public Attributes inherited from com.runehive.game.world.entity.Entity
static final int DEFAULT_INSTANCE = 0
Protected Member Functions inherited from com.runehive.game.world.entity.mob.Mob
void setWaypoint (Waypoint waypoint)
Protected Member Functions inherited from com.runehive.game.world.entity.Entity
Entity destroy ()
Destroys this entity.
void setRegistered (boolean registered)
Protected Attributes inherited from com.runehive.game.world.entity.mob.Mob
Waypoint cachedWaypoint
Detailed Description
Represents a non-player character in the in-game world.
Author
Daniel | Obey
Michael | Chex
Definition at line 29 of file Npc.java.
Constructor & Destructor Documentation
Npc() [1/4]
com.runehive.game.world.entity.mob.npc.Npc.Npc (int id, Position position)
Definition at line 46 of file Npc.java.
{
        this(id, position, 0, Mob.DEFAULT_INSTANCE, Direction.SOUTH);
    }
References com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.Mob(), com.runehive.game.world.entity.Entity.position, and com.runehive.game.world.entity.mob.Direction.SOUTH.
Referenced by equals(), com.runehive.content.activity.infernomobs.JalTokJad.Guardian.Guardian(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.Guardian(), and unregister().
Npc() [2/4]
com.runehive.game.world.entity.mob.npc.Npc.Npc (int id, int instance, Position position)
Definition at line 50 of file Npc.java.
{
        super(position);
        this.id = id;
        this.instance = instance;
        this.faceDirection = Direction.SOUTH;
        this.spawnPosition = position;
        this.walkingRadius = 0;
    }
References com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.Entity.instance, com.runehive.game.world.entity.Entity.position, and com.runehive.game.world.entity.mob.Direction.SOUTH.
Npc() [3/4]
com.runehive.game.world.entity.mob.npc.Npc.Npc (int id, Position position, int walkingRadius, int instance, Direction direction)
Definition at line 59 of file Npc.java.
{
        super(position);
        this.id = id;
        this.instance = instance;
        this.faceDirection = direction;
        this.spawnPosition = position.copy();
        this.walkingRadius = walkingRadius;
    }
References com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.Entity.instance, com.runehive.game.world.entity.Entity.position, and walkingRadius.
Npc() [4/4]
com.runehive.game.world.entity.mob.npc.Npc.Npc (int id, Position position, int walkingRadius, Direction direction)
Definition at line 68 of file Npc.java.
{
        super(position);
        this.id = id;
        this.faceDirection = direction;
        this.spawnPosition = position.copy();
        this.walkingRadius = walkingRadius;
    }
References com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.Entity.position, and walkingRadius.
Member Function Documentation
addToRegion()
void com.runehive.game.world.entity.mob.npc.Npc.addToRegion (Region region)
Adds this entity to the specified region.
Parameters
region The region.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 133 of file Npc.java.
{
        region.addNpc(this);
    }
appendDeath()
void com.runehive.game.world.entity.mob.npc.Npc.appendDeath ()
Handles the mob death.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 147 of file Npc.java.
{
        if (inActivity()) {
            Activity.forActivity(this, activity -> activity.onDeath(this));
            return;
        }
        World.schedule(new NpcDeath(this));
    }
References com.runehive.game.world.entity.mob.Mob.activity, com.runehive.content.activity.Activity.forActivity(), com.runehive.game.world.entity.mob.Mob.inActivity(), and com.runehive.game.world.World.schedule().
Referenced by com.runehive.content.skill.impl.hunter.trap.TrapManager.catchNPC(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.finishIncoming(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit().
equals()
boolean com.runehive.game.world.entity.mob.npc.Npc.equals (Object obj)
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 191 of file Npc.java.
{
        if (obj instanceof Npc) {
            Npc other = (Npc) obj;
            return id == other.id && getIndex() == other.getIndex() && spawnPosition.equals(other.spawnPosition);
        }
        return obj == this;
    }
References com.runehive.game.world.entity.Entity.getIndex(), Npc(), and spawnPosition.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.finishOutgoing(), com.runehive.content.activity.impl.VorkathActivity.onDeath(), and com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.withinDistance().
getBonus()
int com.runehive.game.world.entity.mob.npc.Npc.getBonus (int index)
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 171 of file Npc.java.
{
        return definition.getBonuses()[index];
    }
References definition, and com.runehive.game.world.entity.Entity.index.
Referenced by com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getRangeDefenceLevelNpc().
getBonuses()
int[] com.runehive.game.world.entity.mob.npc.Npc.getBonuses ()
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 176 of file Npc.java.
{
        return definition.getBonuses();
    }
References definition.
getCombat()
Combat< Npc > com.runehive.game.world.entity.mob.npc.Npc.getCombat ()
The combat of the mob.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 156 of file Npc.java.
{
        return combat;
    }
References combat.
Referenced by com.runehive.content.activity.impl.fightcaves.FightCavesListener.block(), com.runehive.content.activity.inferno.InfernoCavesListener.block(), com.runehive.content.activity.infernomobs.JalAk.block(), com.runehive.content.activity.infernomobs.JalTokJad.block(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.block(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.block(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.CrushMelee.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.SlashMelee.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.finishOutgoing(), com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.game.world.entity.combat.attack.listener.npc.SergeantStrongstack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.hit(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.Portal.Portal(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.preDeath(), sequence(), com.runehive.content.activity.impl.fightcaves.FightCaves.start(), com.runehive.content.activity.inferno.Inferno.start(), com.runehive.content.activity.impl.kraken.KrakenActivity.transform(), com.runehive.game.world.entity.mob.Mob.transform(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.withinDistance().
getDeathTime()
int com.runehive.game.world.entity.mob.npc.Npc.getDeathTime () package
Definition at line 204 of file Npc.java.
                       {
        return definition.getDeathTimer();
    }
References definition.
getName()
String com.runehive.game.world.entity.mob.npc.Npc.getName ()
Gets the name of this entity.
Returns
The entity's name.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 166 of file Npc.java.
{
        return definition == null ? "Unknown" : definition.getName();
    }
References definition.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.activate(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.pet.Pets.dialogue(), and toString().
getPriorityIndex()
int com.runehive.game.world.entity.mob.npc.Npc.getPriorityIndex ()
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 217 of file Npc.java.
{
        return -getListIndex();
    }
References com.runehive.game.world.entity.mob.Mob.getListIndex().
getStrategy()
CombatStrategy< Npc > com.runehive.game.world.entity.mob.npc.Npc.getStrategy ()
The combat strategy of the mob.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 161 of file Npc.java.
{
        return strategy;
    }
References strategy.
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Gowler.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.finishOutgoing(), and com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.start().
getType()
EntityType com.runehive.game.world.entity.mob.npc.Npc.getType ()
Gets the EntityType.
Returns
The EntityType.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 181 of file Npc.java.
{
        return EntityType.NPC;
    }
References com.runehive.game.world.entity.EntityType.NPC.
hashCode()
int com.runehive.game.world.entity.mob.npc.Npc.hashCode ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 186 of file Npc.java.
{
        return Objects.hash(getIndex(), definition);
    }
References definition, and com.runehive.game.world.entity.Entity.getIndex().
isAutoRetaliate()
boolean com.runehive.game.world.entity.mob.npc.Npc.isAutoRetaliate ()
State of the mob's auto retaliate.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Definition at line 208 of file Npc.java.
{
        return definition.isRetaliate();
    }
References definition.
onStep()
void com.runehive.game.world.entity.mob.npc.Npc.onStep ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 143 of file Npc.java.
{
    }
register()
void com.runehive.game.world.entity.mob.npc.Npc.register ()
Registers an entity to the World.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 112 of file Npc.java.
{
        if (!isRegistered() && !World.getNpcs().contains(this)) {
            int w = walkingRadius * width();
            int l = walkingRadius * length();
            walk = walkingRadius != 0;
            boundaries = Utility.getInnerBoundaries(spawnPosition.transform(-w, -l), w * 2, l * 2);
            setRegistered(World.getNpcs().add(this));
            setPosition(getPosition());
            npcAssistant.login();
        }
    }
References boundaries, com.runehive.util.Utility.getInnerBoundaries(), com.runehive.game.world.World.getNpcs(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.isRegistered(), com.runehive.game.world.entity.Entity.length, npcAssistant, com.runehive.game.world.entity.Entity.setPosition(), com.runehive.game.world.entity.Entity.setRegistered(), spawnPosition, walk, walkingRadius, and com.runehive.game.world.entity.Entity.width.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.content.pet.Pets.onLogin(), com.runehive.util.parser.impl.NpcSpawnParser.parse(), com.runehive.content.wintertodt.Wintertodt.shootFlame(), com.runehive.content.skill.SkillRepository.spawn(), com.runehive.content.activity.inferno.InfernoBoss.spawnbosswave(), and com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start().
removeFromRegion()
void com.runehive.game.world.entity.mob.npc.Npc.removeFromRegion (Region region)
Removes this entity from the specified region.
Parameters
region The region.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 138 of file Npc.java.
{
        region.removeNpc(this);
    }
sequence()
void com.runehive.game.world.entity.mob.npc.Npc.sequence ()
The method which is invoked every tick.
Reimplemented from com.runehive.game.world.entity.mob.Mob.
Reimplemented in com.runehive.content.activity.infernomobs.JalTokJad.Guardian, and com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.
Definition at line 78 of file Npc.java.
{
        try {
            action.sequence();
            if (sequence % 110 == 0) {
                for (int index = 0; index <= 6; index++) {
                    skills.regress(index);
                }
            }
            if (definition.isAttackable() && (definition.isAggressive() || Area.inWilderness(this))) {
                getCombat().checkAggression(spawnPosition);
            }
            if (!isDead() && !locking.locked(PacketType.MOVEMENT) && combat.getDefender() == null && !combat.inCombat() && walk) {
                if (walkCooldown > 0) {
                    walkCooldown--;
                } else {
                    Position target = Utility.randomElement(boundaries);
                    walk(target);
                    walkCooldown = RandomUtils.inclusive(10, 30);
                }
            }
            if (definition.isAttackable()) {
                getCombat().tick();
            }
        } catch (Exception ex) {
            logger.error(String.format("error npc.sequence(): %s", this), ex);
        }
        sequence++;
    }
References com.runehive.game.world.entity.mob.Mob.action, boundaries, combat, definition, getCombat(), com.runehive.util.RandomUtils.inclusive(), com.runehive.game.world.entity.Entity.index, com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.mob.Mob.isDead(), com.runehive.game.world.entity.mob.Mob.locking, logger, com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT, com.runehive.util.Utility.randomElement(), sequence, com.runehive.game.world.entity.mob.Mob.skills, spawnPosition, walk, and walkCooldown.
setStrategy()
void com.runehive.game.world.entity.mob.npc.Npc.setStrategy (CombatStrategy< Npc > strategy)
Definition at line 212 of file Npc.java.
{
        this.strategy = strategy;
    }
References strategy.
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Ahrim.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.MeleeAttack.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.RangedAttack.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.start(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.start(), com.runehive.game.world.entity.combat.attack.listener.npc.DarkBeast.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.start(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.start(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.start(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.ArmadylSpirtualRanger.start(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.ArmadylSpritualMage.start(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.BandosSpritualMage.start(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.BandosSpritualRanger.start(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SaradominPriest.start(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SpritualMage.start(), com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SpritualRanger.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Gowler.start(), com.runehive.game.world.entity.combat.attack.listener.npc.InfernalMage.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.start(), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Kraken.start(), com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Tentacle.start(), and com.runehive.game.world.entity.mob.Mob.transform().
toString()
String com.runehive.game.world.entity.mob.npc.Npc.toString ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 200 of file Npc.java.
{
        return String.format("Npc[name=" + getName() + " index=%d id=%d registered=%s instance=%s %s]", getIndex(), id, isRegistered(), instance, getPosition());
    }
References com.runehive.game.world.entity.Entity.getIndex(), getName(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.instance, and com.runehive.game.world.entity.Entity.isRegistered().
unregister()
void com.runehive.game.world.entity.mob.npc.Npc.unregister ()
Unregisters an entity from the World.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 126 of file Npc.java.
{
        if (isRegistered()) {
            World.getNpcs().remove((Npc) destroy());
        }
    }
References com.runehive.game.world.entity.Entity.destroy(), com.runehive.game.world.World.getNpcs(), com.runehive.game.world.entity.Entity.isRegistered(), and Npc().
Referenced by com.runehive.content.pet.Pets.abandon(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.defeated(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.defeated(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.defeated(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoEvent.execute(), com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit(), com.runehive.content.pet.Pets.onDeath(), com.runehive.content.pet.Pets.onLogout(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.preDeath(), com.runehive.content.activity.infernomobs.JalTokJad.Guardian.sequence(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.sequence(), and com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start().
Member Data Documentation
atomicPlayerCount
final AtomicInteger com.runehive.game.world.entity.mob.npc.Npc.atomicPlayerCount = new AtomicInteger(0)
Definition at line 44 of file Npc.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.encode().
boundaries
Position [] com.runehive.game.world.entity.mob.npc.Npc.boundaries
Definition at line 42 of file Npc.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), register(), sequence(), and com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack.start().
canAttack
boolean com.runehive.game.world.entity.mob.npc.Npc.canAttack
Definition at line 33 of file Npc.java.
Referenced by com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), and com.runehive.content.activity.impl.zulrah.ZulrahListener.canAttack().
combat
final Combat<Npc> com.runehive.game.world.entity.mob.npc.Npc.combat = new Combat<>(this) private
Definition at line 40 of file Npc.java.
Referenced by getCombat(), and sequence().
definition
NpcDefinition com.runehive.game.world.entity.mob.npc.Npc.definition
Definition at line 37 of file Npc.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.block(), com.runehive.content.activity.impl.kraken.KrakenActivity.cleanup(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.getAttackAnimation(), com.runehive.content.activity.infernomobs.AkMej.getAttackDelay(), com.runehive.content.activity.infernomobs.AkXil.getAttackDelay(), com.runehive.content.activity.infernomobs.JalAk.getAttackDelay(), com.runehive.content.activity.infernomobs.MejRah.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothPrime.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothSupreme.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.Spinolyp.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.CombatUtil.getBlockAnimation(), getBonus(), getBonuses(), getDeathTime(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getDefenceNpc(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicLevelNpc(), getName(), hashCode(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.hit(), isAutoRetaliate(), com.runehive.game.world.position.Position.isWithinDiagonalDistance(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextHit(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile(), and sequence().
faceDirection
final Direction com.runehive.game.world.entity.mob.npc.Npc.faceDirection
Definition at line 35 of file Npc.java.
logger
final Logger com.runehive.game.world.entity.mob.npc.Npc.logger = LogManager.getLogger(Npc.class) static private
Definition at line 30 of file Npc.java.
Referenced by sequence().
npcAssistant
final NpcAssistant com.runehive.game.world.entity.mob.npc.Npc.npcAssistant = new NpcAssistant(this)
Definition at line 39 of file Npc.java.
Referenced by com.runehive.content.activity.impl.godwars.GodwarsListener.onKill(), register(), com.runehive.game.world.World.sendKillFeed(), com.runehive.content.activity.impl.kraken.KrakenActivity.transform(), and com.runehive.game.world.entity.mob.Mob.transform().
owner
Mob com.runehive.game.world.entity.mob.npc.Npc.owner
Definition at line 34 of file Npc.java.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), and com.runehive.content.pet.Pets.dialogue().
pyroHealth
int com.runehive.game.world.entity.mob.npc.Npc.pyroHealth = 24
Pyromancer data.
Definition at line 224 of file Npc.java.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), and com.runehive.content.wintertodt.Wintertodt.healPyromancer().
pyroSnowAttack
boolean com.runehive.game.world.entity.mob.npc.Npc.pyroSnowAttack
Definition at line 225 of file Npc.java.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), and com.runehive.content.wintertodt.Wintertodt.healPyromancer().
sequence
int com.runehive.game.world.entity.mob.npc.Npc.sequence private
Reimplemented in com.runehive.content.activity.infernomobs.JalTokJad.Guardian, and com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Guardian.
Definition at line 31 of file Npc.java.
Referenced by com.runehive.game.engine.GameEngine.runOneIteration(), and sequence().
spawnPosition
final Position com.runehive.game.world.entity.mob.npc.Npc.spawnPosition
Definition at line 36 of file Npc.java.
Referenced by equals(), register(), and sequence().
strategy
CombatStrategy<Npc> com.runehive.game.world.entity.mob.npc.Npc.strategy private
Definition at line 38 of file Npc.java.
Referenced by getStrategy(), and setStrategy().
walk
boolean com.runehive.game.world.entity.mob.npc.Npc.walk
Definition at line 32 of file Npc.java.
Referenced by com.runehive.content.pet.Pets.abandon(), com.runehive.game.action.impl.NpcFaceAction.execute(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.Portal.Portal(), register(), and sequence().
walkCooldown
int com.runehive.game.world.entity.mob.npc.Npc.walkCooldown private
Definition at line 41 of file Npc.java.
Referenced by sequence().
walkingRadius
int com.runehive.game.world.entity.mob.npc.Npc.walkingRadius
Definition at line 43 of file Npc.java.
Referenced by Npc(), Npc(), and register().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/npc/Npc.java