RuneHive-Game: com.runehive.game.world.position.Boundary Class Reference
com.runehive.game.world.position.Boundary Class Reference
Created by Daniel on 2017-11-24.
Public Member Functions
Boundary (int minX, int minY, int highX, int highY)
Boundary (int minX, int minY, int highX, int highY, int height)
int getMaximumX ()
int getMaximumY ()
int getMinimumX ()
int getMinimumY ()
Static Public Member Functions
static List< Player > getPlayers (Boundary boundary)
static boolean isIn (int x, int y, int z, Boundary boundaries)
static boolean isIn (Mob mob, Boundary... boundaries)
static boolean isInSameBoundary (Player player1, Player player2, Boundary[] boundaries)
Package Attributes
int height
int highX
int highY
int minX
int minY
Detailed Description
Created by Daniel on 2017-11-24.
Definition at line 12 of file Boundary.java.
Constructor & Destructor Documentation
Boundary() [1/2]
com.runehive.game.world.position.Boundary.Boundary (int minX, int minY, int highX, int highY)
Definition at line 17 of file Boundary.java.
{
        this.minX = minX;
        this.minY = minY;
        this.highX = highX;
        this.highY = highY;
        height = -1;
    }
References height, highX, highY, minX, and minY.
Referenced by getPlayers(), isIn(), isIn(), and isInSameBoundary().
Boundary() [2/2]
com.runehive.game.world.position.Boundary.Boundary (int minX, int minY, int highX, int highY, int height)
Definition at line 25 of file Boundary.java.
{
        this.minX = minX;
        this.minY = minY;
        this.highX = highX;
        this.highY = highY;
        this.height = height;
    }
References height, highX, highY, minX, and minY.
Member Function Documentation
getMaximumX()
int com.runehive.game.world.position.Boundary.getMaximumX ()
Definition at line 41 of file Boundary.java.
{
        return highX;
    }
References highX.
getMaximumY()
int com.runehive.game.world.position.Boundary.getMaximumY ()
Definition at line 45 of file Boundary.java.
{
        return highY;
    }
References highY.
getMinimumX()
int com.runehive.game.world.position.Boundary.getMinimumX ()
Definition at line 33 of file Boundary.java.
{
        return minX;
    }
References minX.
Referenced by com.runehive.content.Obelisks.activate().
getMinimumY()
int com.runehive.game.world.position.Boundary.getMinimumY ()
Definition at line 37 of file Boundary.java.
{
        return minY;
    }
References minY.
Referenced by com.runehive.content.Obelisks.activate().
getPlayers()
List< Player > com.runehive.game.world.position.Boundary.getPlayers (Boundary boundary) static
Definition at line 70 of file Boundary.java.
{
        List<Player> list = new ArrayList<>();
        for (Player player : World.getPlayers()) {
            if (player != null && isIn(player, boundary))
                list.add(player);
        }
        return list;
    }
References Boundary(), com.runehive.game.world.World.getPlayers(), and isIn().
Referenced by com.runehive.content.Obelisks.activate().
isIn() [1/2]
boolean com.runehive.game.world.position.Boundary.isIn (int x, int y, int z, Boundary boundaries) static
Definition at line 61 of file Boundary.java.
{
        if (boundaries.height >= 0) {
            if (z != boundaries.height) {
                return false;
            }
        }
        return x >= boundaries.minX && x <= boundaries.highX && y >= boundaries.minY && y <= boundaries.highY;
    }
References Boundary(), height, and highY.
isIn() [2/2]
boolean com.runehive.game.world.position.Boundary.isIn (Mob mob, Boundary... boundaries) static
Definition at line 49 of file Boundary.java.
{
        for (Boundary b : boundaries) {
            if (b.height >= 0) {
                if (mob.getHeight() != b.height)
                    continue;
            }
            if (mob.getX() >= b.minX && mob.getX() <= b.highX && mob.getY() >= b.minY && mob.getY() <= b.highY)
                return true;
        }
        return false;
    }
References Boundary(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.entity.Entity.getX(), and com.runehive.game.world.entity.Entity.getY().
Referenced by com.runehive.content.gambling.GambleManager.canGamble(), getPlayers(), com.runehive.content.lms.LMSGame.handleFogDamage(), com.runehive.content.lms.LMSGame.inGameArea(), com.runehive.content.lms.safezone.LMSSafezone.inSafeZone(), isInSameBoundary(), and com.runehive.game.world.entity.mob.player.Player.onStep().
isInSameBoundary()
boolean com.runehive.game.world.position.Boundary.isInSameBoundary (Player player1, Player player2, Boundary[] boundaries) static
Definition at line 79 of file Boundary.java.
{
        Optional<Boundary> boundary1 = Arrays.stream(boundaries).filter(b -> isIn(player1, b)).findFirst();
        Optional<Boundary> boundary2 = Arrays.stream(boundaries).filter(b -> isIn(player2, b)).findFirst();
        if (!boundary1.isPresent() || !boundary2.isPresent()) {
            return false;
        }
        return Objects.equals(boundary1.get(), boundary2.get());
    }
References Boundary(), and isIn().
Member Data Documentation
height
int com.runehive.game.world.position.Boundary.height package
Definition at line 15 of file Boundary.java.
Referenced by Boundary(), Boundary(), and isIn().
highX
int com.runehive.game.world.position.Boundary.highX package
Definition at line 14 of file Boundary.java.
Referenced by Boundary(), Boundary(), and getMaximumX().
highY
int com.runehive.game.world.position.Boundary.highY package
Definition at line 14 of file Boundary.java.
Referenced by Boundary(), Boundary(), getMaximumY(), and isIn().
minX
int com.runehive.game.world.position.Boundary.minX package
Definition at line 14 of file Boundary.java.
Referenced by Boundary(), Boundary(), and getMinimumX().
minY
int com.runehive.game.world.position.Boundary.minY package
Definition at line 14 of file Boundary.java.
Referenced by Boundary(), Boundary(), and getMinimumY().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/position/Boundary.java