RuneHive-Game: com.runehive.util.tools.wiki.impl.BonusParser Class Reference
com.runehive.util.tools.wiki.impl.BonusParser Class Reference
Static Public Member Functions
static void main (String[] args) throws InterruptedException
Protected Member Functions
void finish ()
Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
void execute (Runnable runnable)
Private Member Functions
BonusParser ()
Static Private Member Functions
static LinkedList< WikiTable > generateTables ()
Static Private Attributes
static final String[] TABLE_LINKS
The table links.
Additional Inherited Members
Public Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
void begin () throws InterruptedException
Begins parsing wiki tables for all the names provided.
WikiTableParser (LinkedList< WikiTable > tables)
Constructs a new WikiTableParser object.
Static Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
static void writeToJson (String name, JsonElement array)
Writes the parsed wiki dump to a json file in ./data/wiki named as the name parameter.
Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
final LinkedList< WikiTable > tables
The WikiTable list to parse.
Static Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create()
The gson object.
static final String WIKI_LINK = "http://oldschoolrunescape.wikia.com/wiki/"
The path to the wiki page address.
Detailed Description
Definition at line 16 of file BonusParser.java.
Constructor & Destructor Documentation
BonusParser()
com.runehive.util.tools.wiki.impl.BonusParser.BonusParser () private
Definition at line 34 of file BonusParser.java.
{
        super(generateTables());
    }
References generateTables().
Referenced by main().
Member Function Documentation
finish()
void com.runehive.util.tools.wiki.impl.BonusParser.finish () protected
Reimplemented from com.runehive.util.tools.wiki.parser.WikiTableParser.
Definition at line 94 of file BonusParser.java.
{
        Map<String, Integer[]> bonusMap = new HashMap<>(tables.size());
        JsonArray array = new JsonArray();
        for (WikiTable table : tables) {
            JsonArray tableData = table.getTable();
            array.addAll(tableData);
            for (JsonElement data : tableData) {
                JsonObject next = (JsonObject) data;
                String name = next.get("name").getAsString();
                Integer[] bonuses = GSON.fromJson(next.get("bonuses"), Integer[].class);
                if (bonusMap.containsKey(name)) {
                    System.err.println("Conflicting item: " + name);
                    System.err.println(Arrays.toString(bonuses));
                    System.err.println(Arrays.toString(bonusMap.get(name)));
                    System.err.println();
                } else {
                    bonusMap.put(name, bonuses);
                }
            }
        }
        writeToJson("wiki_dump", array);
        ItemDefinition.createParser().run();
        for (ItemDefinition definition : ItemDefinition.DEFINITIONS) {
            if (definition == null) continue;
            Integer[] bonuses = bonusMap.get(definition.getName());
            if (bonuses != null) {
                Arrays.setAll(definition.getBonuses(), index -> bonuses[index]);
            } else {
                Arrays.setAll(definition.getBonuses(), index -> 0);
            }
        }
        ItemDefinition.dump("wiki/bonus_dump");
    }
References com.runehive.game.world.items.ItemDefinition.createParser(), com.runehive.game.world.items.ItemDefinition.DEFINITIONS, com.runehive.game.world.items.ItemDefinition.dump(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.util.tools.wiki.parser.WikiTableParser.GSON, com.runehive.util.parser.GenericParser.run(), com.runehive.util.tools.wiki.parser.WikiTableParser.tables, and com.runehive.util.tools.wiki.parser.WikiTableParser.writeToJson().
generateTables()
LinkedList< WikiTable > com.runehive.util.tools.wiki.impl.BonusParser.generateTables () static private
Definition at line 38 of file BonusParser.java.
{
        LinkedList<WikiTable> tables = new LinkedList<>();
        for (String link : TABLE_LINKS) {
            tables.add(new WikiTable(link) {
                @Override
                public void parseDocument(Document document) {
                    for (Element wikiTable : document.select(".wikitable")) {
                        for (Element children : wikiTable.children()) {
                            Iterator<Element> iterator = children.children().iterator();
                            iterator.next();
                            while (iterator.hasNext()) {
                                Element child = iterator.next();
                                Elements bonuses = child.children();
                                String name = bonuses.remove(0).text();
                                try {
                                    JsonObject object = new JsonObject();
                                    object.addProperty("name", name);
                                    int idx = 0;
                                    int[] bonusArray = new int[Equipment.SIZE];
                                    for (Element data : bonuses) {
                                        if (data.text().isEmpty()) {
                                            idx++;
                                            continue;
                                        }
                                        if (data.text().contains("trimmed"))
                                            continue;
                                        if (idx >= bonusArray.length)
                                            break;
                                        if ((link.contains("Neck") || link.contains("Body") || link.contains("Leg") || link.contains("Feet") || link.contains("Head") || link.contains("Cape") || link.contains("Ammu") || link.contains("Hand")) && idx == Equipment.RANGED_STRENGTH) {
                                            bonusArray[Equipment.PRAYER_BONUS] = Integer.parseInt(data.text());
                                        } else {
                                            bonusArray[idx++] = Integer.parseInt(data.text());
                                        }
                                    }
                                    object.add("bonuses", GSON.toJsonTree(bonusArray));
                                    table.add(object);
                                } catch (Exception e) {
                                    System.err.println("Failed to parse " + name + "   ---   " + e.toString());
                                }
                            }
                        }
                    }
                }
            });
        }
        return tables;
    }
References com.runehive.util.tools.wiki.parser.WikiTableParser.GSON, com.runehive.game.world.items.containers.equipment.Equipment.PRAYER_BONUS, com.runehive.game.world.items.containers.equipment.Equipment.RANGED_STRENGTH, com.runehive.game.world.items.containers.equipment.Equipment.SIZE, TABLE_LINKS, and com.runehive.util.tools.wiki.parser.WikiTableParser.tables.
Referenced by BonusParser().
main()
void com.runehive.util.tools.wiki.impl.BonusParser.main (String[] args) throws InterruptedException static
Definition at line 132 of file BonusParser.java.
{
        BonusParser parser = new BonusParser();
        parser.begin();
    }
References BonusParser().
Member Data Documentation
TABLE_LINKS
final String [] com.runehive.util.tools.wiki.impl.BonusParser.TABLE_LINKS static private
Initial value:
= {
            "http://oldschoolrunescape.wikia.com/wiki/Ammunition_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Body_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Cape_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Feet_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Hand_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Head_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Legwear_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Neck_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Ring_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Shield_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Two-handed_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Weapons_table"
    }
The table links.
Definition at line 19 of file BonusParser.java.
{
            "http://oldschoolrunescape.wikia.com/wiki/Ammunition_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Body_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Cape_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Feet_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Hand_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Head_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Legwear_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Neck_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Ring_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Shield_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Two-handed_slot_table",
            "http://oldschoolrunescape.wikia.com/wiki/Weapons_table"
    };
Referenced by generateTables().
The documentation for this class was generated from the following file:
java/com/runehive/util/tools/wiki/impl/BonusParser.java