RuneHive-Game: com.runehive.game.world.entity.mob.player.profile.ProfileRepository Class Reference
com.runehive.game.world.entity.mob.player.profile.ProfileRepository Class Reference
Handles the profile repository, used for gathering important information for all created profiles.
Static Public Member Functions
static boolean exist (String name)
Checks if a profile is registered to the parameter.
static List< String > getRegistry (String host)
Gets all the registered accounts to a specific host.
static boolean isFriend (Player player, String other)
Checks if the other player is a friend.
static void load ()
Loads all the profiles.
static void put (Profile profile)
Puts a profile into the hash map.
static void save ()
Saves all the profiles.
Static Private Attributes
static final Path FILE_PATH = Path.of("data", "profile", "world_profile_list.json")
static Map< String, Profile > profiles = new HashMap<>()
The hash map of all the profiles.
Detailed Description
Handles the profile repository, used for gathering important information for all created profiles.
Author
Daniel
Definition at line 23 of file ProfileRepository.java.
Member Function Documentation
exist()
boolean com.runehive.game.world.entity.mob.player.profile.ProfileRepository.exist (String name) static
Checks if a profile is registered to the parameter.
Definition at line 30 of file ProfileRepository.java.
{
        return profiles.containsKey(name);
    }
References profiles.
Referenced by com.runehive.content.skill.impl.construction.House.enter().
getRegistry()
List< String > com.runehive.game.world.entity.mob.player.profile.ProfileRepository.getRegistry (String host) static
Gets all the registered accounts to a specific host.
Definition at line 40 of file ProfileRepository.java.
{
        List<String> list = new ArrayList<>();
        for (Profile profile : profiles.values()) {
            for (String host_list : profile.getHost()) {
                if (host_list != null && host_list.equalsIgnoreCase(host)) {
                    list.add(profile.getName());
                }
            }
        }
        return list;
    }
References profiles.
isFriend()
boolean com.runehive.game.world.entity.mob.player.profile.ProfileRepository.isFriend (Player player, String other) static
Checks if the other player is a friend.
Definition at line 35 of file ProfileRepository.java.
{
        return player.relations.isFriendWith(other);
    }
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.attemptConnection().
load()
void com.runehive.game.world.entity.mob.player.profile.ProfileRepository.load () static
Loads all the profiles.
Definition at line 64 of file ProfileRepository.java.
{
        if (!Files.exists(FILE_PATH)) return;
        final Type type = new TypeToken<Map<String, Profile>>() {
        }.getType();
        try (final FileReader reader = new FileReader(FILE_PATH.toFile())) {
            profiles = GsonUtils.json().fromJson(reader, type);
        } catch (final Exception e) {
            e.printStackTrace();
        }
    }
References FILE_PATH, com.runehive.util.GsonUtils.json(), and profiles.
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
put()
void com.runehive.game.world.entity.mob.player.profile.ProfileRepository.put (Profile profile) static
Puts a profile into the hash map.
Definition at line 53 of file ProfileRepository.java.
{
        final String name = profile.getName();
        if (profiles.containsKey(name)) {
            profiles.replace(name, profile);
        } else {
            profiles.put(name, profile);
        }
        save();
    }
References profiles, and save().
Referenced by com.runehive.net.session.LoginSession.handleUserLoginDetails().
save()
void com.runehive.game.world.entity.mob.player.profile.ProfileRepository.save () static
Saves all the profiles.
Definition at line 78 of file ProfileRepository.java.
{
        Thread.startVirtualThread(() -> {
            try {
                final Path path = FILE_PATH;
                Path parent = path.getParent();
                if (parent == null) {
                    throw new UnsupportedOperationException("Path must have a parent " + path);
                }
                if (!Files.exists(parent)) {
                    parent = Files.createDirectories(parent);
                }
                final Path tempFile = Files.createTempFile(parent, path.getFileName().toString(), ".tmp");
                Files.write(tempFile, GsonUtils.json().toJson(profiles).getBytes());
                Files.move(tempFile, path, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
            } catch (final Exception e) {
                e.printStackTrace();
            }
        });
    }
References FILE_PATH, com.runehive.util.GsonUtils.json(), and profiles.
Referenced by put().
Member Data Documentation
FILE_PATH
final Path com.runehive.game.world.entity.mob.player.profile.ProfileRepository.FILE_PATH = Path.of("data", "profile", "world_profile_list.json") static private
Definition at line 24 of file ProfileRepository.java.
Referenced by load(), and save().
profiles
Map<String, Profile> com.runehive.game.world.entity.mob.player.profile.ProfileRepository.profiles = new HashMap<>() static private
The hash map of all the profiles.
Definition at line 27 of file ProfileRepository.java.
Referenced by exist(), getRegistry(), load(), put(), and save().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/profile/ProfileRepository.java