RuneHive-Game: com.runehive.content.writer.InterfaceWriter Class Reference
com.runehive.content.writer.InterfaceWriter Class Reference abstract
Handles writing on an itemcontainer.
Public Member Functions
InterfaceWriter (Player player)
void scroll ()
Static Public Member Functions
static void write (InterfaceWriter writer)
Protected Member Functions
abstract int[][] color ()
abstract int[][] font ()
abstract int startingIndex ()
abstract String[] text ()
Protected Attributes
Player player
Detailed Description
Handles writing on an itemcontainer.
Author
Daniel
Definition at line 14 of file InterfaceWriter.java.
Constructor & Destructor Documentation
InterfaceWriter()
com.runehive.content.writer.InterfaceWriter.InterfaceWriter (Player player)
Definition at line 16 of file InterfaceWriter.java.
{
        this.player = player;
    }
References player.
Referenced by write().
Member Function Documentation
color()
abstract int[][] com.runehive.content.writer.InterfaceWriter.color () abstract protected
Reimplemented in com.runehive.content.achievement.AchievementWriter, com.runehive.content.writer.impl.InformationWriter, com.runehive.content.writer.impl.ObeliskWriter, com.runehive.content.writer.impl.SettingWriter, and com.runehive.content.writer.impl.ToolWriter.
font()
abstract int[][] com.runehive.content.writer.InterfaceWriter.font () abstract protected
Reimplemented in com.runehive.content.achievement.AchievementWriter, com.runehive.content.writer.impl.InformationWriter, com.runehive.content.writer.impl.ObeliskWriter, com.runehive.content.writer.impl.SettingWriter, and com.runehive.content.writer.impl.ToolWriter.
scroll()
void com.runehive.content.writer.InterfaceWriter.scroll ()
Reimplemented in com.runehive.content.writer.impl.InformationWriter.
Definition at line 30 of file InterfaceWriter.java.
{
    }
startingIndex()
abstract int com.runehive.content.writer.InterfaceWriter.startingIndex () abstract protected
Reimplemented in com.runehive.content.achievement.AchievementWriter, com.runehive.content.writer.impl.InformationWriter, com.runehive.content.writer.impl.ObeliskWriter, com.runehive.content.writer.impl.SettingWriter, and com.runehive.content.writer.impl.ToolWriter.
text()
abstract String[] com.runehive.content.writer.InterfaceWriter.text () abstract protected
Reimplemented in com.runehive.content.achievement.AchievementWriter, com.runehive.content.writer.impl.InformationWriter, com.runehive.content.writer.impl.ObeliskWriter, com.runehive.content.writer.impl.SettingWriter, and com.runehive.content.writer.impl.ToolWriter.
write()
void com.runehive.content.writer.InterfaceWriter.write (InterfaceWriter writer) static
Definition at line 34 of file InterfaceWriter.java.
{
        writer.scroll();
        /* Sends the text */
        int line = writer.startingIndex();
        if (writer.text() != null) {
            for (int index = 0; index < writer.text().length; index++) {
                writer.player.send(new SendString(writer.text()[index], line++));
            }
        }
        /* Sends the color */
        if (writer.color() != null) {
            for (int index = 0; index < writer.color().length; index++) {
                writer.player.send(new SendColor(writer.color()[index][0], writer.color()[index][1]));
            }
        }
        /* Sends the font */
        if (writer.font() != null) {
            for (int index = 0; index < writer.font().length; index++) {
                writer.player.send(new SendFont(writer.font()[index][0], writer.font()[index][1]));
            }
        }
    }
References InterfaceWriter().
Referenced by com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.game.world.entity.mob.player.PlayerAssistant.initialize(), com.runehive.game.plugin.PluginContext.onClick(), com.runehive.content.Obelisks.open(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.game.engine.GameEngine.runOneIteration(), and com.runehive.content.donators.Donation.updateRank().
Member Data Documentation
player
Player com.runehive.content.writer.InterfaceWriter.player protected
Definition at line 20 of file InterfaceWriter.java.
Referenced by com.runehive.content.achievement.AchievementWriter.AchievementWriter(), com.runehive.content.writer.impl.InformationWriter.InformationWriter(), InterfaceWriter(), com.runehive.content.writer.impl.ObeliskWriter.ObeliskWriter(), com.runehive.content.writer.impl.InformationWriter.scroll(), com.runehive.content.writer.impl.SettingWriter.SettingWriter(), and com.runehive.content.writer.impl.ToolWriter.ToolWriter().
The documentation for this class was generated from the following file:
java/com/runehive/content/writer/InterfaceWriter.java