RuneHive-Game: com.runehive.game.Animation Class Reference
com.runehive.game.Animation Class Reference
Class that models a single animation used by an entity.
Public Member Functions
Animation (int id)
Creates a new instance of the animation with a hidden delay of 0.
Animation (int id, int delay)
Creates a new instance of the animation with a specified delay.
Animation (int id, int delay, UpdatePriority priority)
Creates a new instance of the animation with a specified delay.
Animation (int id, UpdatePriority priority)
Creates a new instance of the animation with a hidden delay of 0.
int compareTo (Animation other)
boolean equals (Object obj)
int getDelay ()
Gets the animation delay.
int getId ()
Gets the animation id.
int hashCode ()
boolean isReset ()
String toString ()
Static Public Attributes
static final Animation LUNAR_TELE = new Animation(LUNAR_TELE_ID, UpdatePriority.VERY_HIGH)
static final int LUNAR_TELE_ID = 1816
static final Animation NORMAL_TELE = new Animation(NORMAL_TELE_ID, UpdatePriority.VERY_HIGH)
static final int NORMAL_TELE_ID = 714
static final Animation RESET = new Animation(RESET_ID, UpdatePriority.VERY_LOW)
static final int RESET_ID = 65535
Private Attributes
final int delay
The delay before playing the animation.
final int id
The animation id.
final UpdatePriority priority
The animation priority.
Detailed Description
Class that models a single animation used by an entity.
Author
Michael | Chex
Definition at line 10 of file Animation.java.
Constructor & Destructor Documentation
Animation() [1/4]
com.runehive.game.Animation.Animation (int id)
Creates a new instance of the animation with a hidden delay of 0.
Parameters
id The id of the animation being used.
Definition at line 36 of file Animation.java.
{
        this(id, 0, UpdatePriority.NORMAL);
    }
References id, and com.runehive.game.UpdatePriority.NORMAL.
Referenced by compareTo(), and equals().
Animation() [2/4]
com.runehive.game.Animation.Animation (int id, int delay)
Creates a new instance of the animation with a specified delay.
Parameters
id The id of the animation being used.
delay The delay of the animation in seconds.
Definition at line 48 of file Animation.java.
{
        this(id, delay, UpdatePriority.NORMAL);
    }
References delay, id, and com.runehive.game.UpdatePriority.NORMAL.
Animation() [3/4]
com.runehive.game.Animation.Animation (int id, UpdatePriority priority)
Creates a new instance of the animation with a hidden delay of 0.
Parameters
id The id of the animation being used.
priority The priority level of the animation.
Definition at line 60 of file Animation.java.
{
        this(id, 0, priority);
    }
References id, and priority.
Animation() [4/4]
com.runehive.game.Animation.Animation (int id, int delay, UpdatePriority priority)
Creates a new instance of the animation with a specified delay.
Parameters
id The id of the animation being used.
delay The delay of the animation in seconds.
priority The priority level of the animation.
Definition at line 74 of file Animation.java.
{
        this.priority = priority;
        this.id = id;
        this.delay = delay;
    }
References delay, id, and priority.
Member Function Documentation
compareTo()
int com.runehive.game.Animation.compareTo (Animation other)
Definition at line 113 of file Animation.java.
{
        if (other == null || other.priority == null) {
            return 1;
        }
        return other.priority.compareTo(priority);
    }
References Animation(), and priority.
equals()
boolean com.runehive.game.Animation.equals (Object obj)
Definition at line 104 of file Animation.java.
{
        if (obj instanceof Animation) {
            Animation other = (Animation) obj;
            return id == other.id && delay == other.delay && priority == other.priority;
        }
        return obj == this;
    }
References Animation(), delay, and priority.
getDelay()
int com.runehive.game.Animation.getDelay ()
Gets the animation delay.
Returns
The delay.
Definition at line 85 of file Animation.java.
{
        return delay;
    }
References delay.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendAnimationMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendAnimationMask().
getId()
int com.runehive.game.Animation.getId ()
Gets the animation id.
Returns
The id.
Definition at line 94 of file Animation.java.
                       {
        return id;
    }
References id.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendAnimationMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendAnimationMask().
hashCode()
int com.runehive.game.Animation.hashCode ()
Definition at line 99 of file Animation.java.
{
        return Objects.hash(id, delay, priority);
    }
References delay, and priority.
isReset()
boolean com.runehive.game.Animation.isReset ()
Definition at line 126 of file Animation.java.
{
        return id == -1 || id == RESET_ID;
    }
References RESET_ID.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendAnimation(), and com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.sendAnimation().
toString()
String com.runehive.game.Animation.toString ()
Definition at line 122 of file Animation.java.
{
        return String.format("Animation[priority=%s, id=%s, delay=%s]", priority, id, delay);
    }
References delay, and priority.
Member Data Documentation
delay
final int com.runehive.game.Animation.delay private
The delay before playing the animation.
Definition at line 25 of file Animation.java.
Referenced by Animation(), Animation(), equals(), getDelay(), hashCode(), and toString().
id
final int com.runehive.game.Animation.id private
The animation id.
Definition at line 22 of file Animation.java.
Referenced by Animation(), Animation(), Animation(), Animation(), and getId().
LUNAR_TELE
final Animation com.runehive.game.Animation.LUNAR_TELE = new Animation(LUNAR_TELE_ID, UpdatePriority.VERY_HIGH) static
Definition at line 18 of file Animation.java.
LUNAR_TELE_ID
final int com.runehive.game.Animation.LUNAR_TELE_ID = 1816 static
Definition at line 14 of file Animation.java.
NORMAL_TELE
final Animation com.runehive.game.Animation.NORMAL_TELE = new Animation(NORMAL_TELE_ID, UpdatePriority.VERY_HIGH) static
Definition at line 17 of file Animation.java.
NORMAL_TELE_ID
final int com.runehive.game.Animation.NORMAL_TELE_ID = 714 static
Definition at line 13 of file Animation.java.
priority
final UpdatePriority com.runehive.game.Animation.priority private
The animation priority.
Definition at line 28 of file Animation.java.
Referenced by Animation(), Animation(), compareTo(), equals(), hashCode(), and toString().
RESET
final Animation com.runehive.game.Animation.RESET = new Animation(RESET_ID, UpdatePriority.VERY_LOW) static
Definition at line 16 of file Animation.java.
Referenced by com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.net.packet.out.SendNpcUpdate.appendAnimationMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendAnimationMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.finish(), com.runehive.content.activity.impl.magearena.MageArena.finish(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.finish(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.finish(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.game.action.impl.TeleportAction.onCancel(), com.runehive.content.activity.impl.CerberusActivity.onDeath(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsActivity.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.onRegionChange(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.content.activity.Activity.remove(), and com.runehive.content.lms.LMSGame.reset().
RESET_ID
final int com.runehive.game.Animation.RESET_ID = 65535 static
Definition at line 12 of file Animation.java.
Referenced by isReset().
The documentation for this class was generated from the following file:
java/com/runehive/game/Animation.java