RuneHive-Game: com.runehive.content.itemaction.impl.SerpentineHelm Class Reference
com.runehive.content.itemaction.impl.SerpentineHelm Class Reference
Public Member Functions
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
SerpentineHelm ()
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
String message (Item item)
The message of the action.
String toString ()
Static Public Member Functions
static void check (Player player)
Static Private Member Functions
static void charge (Player player, Item helm, Item scales)
static void dismantle (Player player, Item item)
static void uncharge (Player player)
Static Private Attributes
static final short CHARGED_HELM = 12_931
static final DecimalFormat FORMATTER = new DecimalFormat("#.#")
static final short FULL = 11_000
static final short MAGMA_MUTAGEN = 13201
static final short TANZ_MUTAGEN = 13200
static final short UNCHARGED_HELM = 12_929
static final short ZULRAH_SCALES = 12_934
Detailed Description
Definition at line 15 of file SerpentineHelm.java.
Constructor & Destructor Documentation
SerpentineHelm()
com.runehive.content.itemaction.impl.SerpentineHelm.SerpentineHelm ()
Definition at line 28 of file SerpentineHelm.java.
{
        FORMATTER.setRoundingMode(RoundingMode.FLOOR);
    }
References FORMATTER.
Member Function Documentation
charge()
void com.runehive.content.itemaction.impl.SerpentineHelm.charge (Player player, Item helm, Item scales) static private
Definition at line 121 of file SerpentineHelm.java.
{
        if (player.serpentineHelmCharges >= FULL) {
            if (helm.matchesId(UNCHARGED_HELM)) {
                player.inventory.replace(UNCHARGED_HELM, CHARGED_HELM, true);
            }
            player.message("Your Serpentine helm is already fully charged.");
            return;
        }
        if (Integer.MAX_VALUE - scales.getAmount() < FULL) {
            scales = scales.copy();
            scales.setAmount(FULL - player.serpentineHelmCharges);
        }
        if (player.serpentineHelmCharges + scales.getAmount() > FULL) {
            scales = scales.copy();
            scales.setAmount(FULL - player.serpentineHelmCharges);
        }
        player.serpentineHelmCharges += scales.getAmount();
        player.inventory.remove(scales);
        player.inventory.replace(UNCHARGED_HELM, CHARGED_HELM, true);
        player.message(String.format("You load %s scales into your Serpentine helm.", Utility.formatDigits(scales.getAmount())));
    }
References CHARGED_HELM, com.runehive.game.world.items.Item.copy(), com.runehive.util.Utility.formatDigits(), FULL, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.Item.matchesId(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.entity.mob.player.Player.serpentineHelmCharges, com.runehive.game.world.items.Item.setAmount(), and UNCHARGED_HELM.
Referenced by itemOnItem().
check()
void com.runehive.content.itemaction.impl.SerpentineHelm.check (Player player) static
Definition at line 116 of file SerpentineHelm.java.
{
        String scales = FORMATTER.format(player.serpentineHelmCharges * 100 / FULL) + "%";
        player.message("Charges: <col=007F00>" + scales);
    }
References FORMATTER, FULL, com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.entity.mob.player.Player.serpentineHelmCharges.
Referenced by equipment(), and inventory().
dismantle()
void com.runehive.content.itemaction.impl.SerpentineHelm.dismantle (Player player, Item item) static private
Definition at line 160 of file SerpentineHelm.java.
{
        player.send(new SendItemOnInterfaceSlot(14171, item, 0));
        player.send(new SendString("Are you sure you want to uncharge this item?", 14174));
        player.send(new SendString("Yes.", 14175));
        player.send(new SendString("No.", 14176));
        player.send(new SendString("", 14177));
        player.send(new SendString("This will replace your helm with 20,000 Zulrah's scales.", 14182));
        player.send(new SendString("", 14183));
        player.send(new SendString(item.getName(), 14184));
        player.send(new SendChatBoxInterface(14170));
        player.attributes.set("UNCHARGE_HELM_KEY", item);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.util.generic.GenericAttributes.set().
Referenced by drop(), and inventory().
drop()
boolean com.runehive.content.itemaction.impl.SerpentineHelm.drop (Player player, Item item)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 104 of file SerpentineHelm.java.
{
        if (item.matchesId(CHARGED_HELM)) {
            uncharge(player);
            return true;
        }
        if (item.matchesId(UNCHARGED_HELM)) {
            dismantle(player, item);
            return true;
        }
        return false;
    }
References CHARGED_HELM, dismantle(), com.runehive.game.world.items.Item.matchesId(), uncharge(), and UNCHARGED_HELM.
equipment()
boolean com.runehive.content.itemaction.impl.SerpentineHelm.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 96 of file SerpentineHelm.java.
{
        if (opcode == 1) {
            check(player);
        }
        return true;
    }
References check().
inventory()
boolean com.runehive.content.itemaction.impl.SerpentineHelm.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 82 of file SerpentineHelm.java.
{
        if (opcode == 3 && item.matchesId(UNCHARGED_HELM)) {
            dismantle(player, item);
            return true;
        }
        if (opcode == 2) {
            check(player);
        }
        return true;
    }
References check(), dismantle(), com.runehive.game.world.items.Item.matchesId(), and UNCHARGED_HELM.
itemOnItem()
boolean com.runehive.content.itemaction.impl.SerpentineHelm.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 38 of file SerpentineHelm.java.
{
        Item item = first;
        if (first.getId() == UNCHARGED_HELM || first.getId() == CHARGED_HELM) {
            item = second;
        }
        if ((first.matchesId(CHARGED_HELM) && second.matchesId(TANZ_MUTAGEN))
                || (second.matchesId(CHARGED_HELM) && first.matchesId(TANZ_MUTAGEN))) {
            player.message("You need to uncharge your Serpentine helm first.");
            return true;
        }
        if ((first.matchesId(CHARGED_HELM) && second.matchesId(MAGMA_MUTAGEN))
                || (second.matchesId(CHARGED_HELM) && first.matchesId(MAGMA_MUTAGEN))) {
            player.message("You need to uncharge your Serpentine helm first.");
            return true;
        }
        if ((first.matchesId(UNCHARGED_HELM) && second.matchesId(TANZ_MUTAGEN))
                || (second.matchesId(UNCHARGED_HELM) && first.matchesId(TANZ_MUTAGEN))) {
            player.inventory.remove(TANZ_MUTAGEN);
            player.inventory.replace(UNCHARGED_HELM, 13_196, true);
            player.message(true, "You recolor your Serpentine helm into a Tanzanite helm!");
            return true;
        }
        if ((first.matchesId(UNCHARGED_HELM) && second.matchesId(MAGMA_MUTAGEN))
                || (second.matchesId(UNCHARGED_HELM) && first.matchesId(MAGMA_MUTAGEN))) {
            player.inventory.remove(MAGMA_MUTAGEN);
            player.inventory.replace(UNCHARGED_HELM, 13_198, true);
            player.message(true, "You recolor your Serpentine helm into a Magma helm!");
            return true;
        }
        if (item.getId() == ZULRAH_SCALES) {
            charge(player, item.equals(first) ? second : first, item);
            return true;
        }
        return false;
    }
References charge(), CHARGED_HELM, com.runehive.game.world.items.Item.equals(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, MAGMA_MUTAGEN, com.runehive.game.world.items.Item.matchesId(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.containers.ItemContainer.replace(), TANZ_MUTAGEN, UNCHARGED_HELM, and ZULRAH_SCALES.
name()
String com.runehive.content.itemaction.impl.SerpentineHelm.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 33 of file SerpentineHelm.java.
{
        return "Serpentine helm";
    }
uncharge()
void com.runehive.content.itemaction.impl.SerpentineHelm.uncharge (Player player) static private
Definition at line 146 of file SerpentineHelm.java.
{
        Item scales = new Item(ZULRAH_SCALES, player.serpentineHelmCharges);
        if (!player.inventory.hasCapacityFor(scales)) {
            player.send(new SendMessage("You need more inventory space to do this."));
            return;
        }
        player.serpentineHelmCharges = 0;
        player.inventory.add(scales);
        player.inventory.replace(CHARGED_HELM, UNCHARGED_HELM, true);
        player.message(String.format("You uncharged your Serpentine helm and received %s of Zulra's scales.", Utility.formatDigits(scales.getAmount())));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), CHARGED_HELM, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.Player.serpentineHelmCharges, UNCHARGED_HELM, and ZULRAH_SCALES.
Referenced by drop().
Member Data Documentation
CHARGED_HELM
final short com.runehive.content.itemaction.impl.SerpentineHelm.CHARGED_HELM = 12_931 static private
Definition at line 21 of file SerpentineHelm.java.
Referenced by charge(), drop(), itemOnItem(), and uncharge().
FORMATTER
final DecimalFormat com.runehive.content.itemaction.impl.SerpentineHelm.FORMATTER = new DecimalFormat("#.#") static private
Definition at line 26 of file SerpentineHelm.java.
Referenced by check(), and SerpentineHelm().
FULL
final short com.runehive.content.itemaction.impl.SerpentineHelm.FULL = 11_000 static private
Definition at line 16 of file SerpentineHelm.java.
Referenced by charge(), and check().
MAGMA_MUTAGEN
final short com.runehive.content.itemaction.impl.SerpentineHelm.MAGMA_MUTAGEN = 13201 static private
Definition at line 24 of file SerpentineHelm.java.
Referenced by itemOnItem().
TANZ_MUTAGEN
final short com.runehive.content.itemaction.impl.SerpentineHelm.TANZ_MUTAGEN = 13200 static private
Definition at line 23 of file SerpentineHelm.java.
Referenced by itemOnItem().
UNCHARGED_HELM
final short com.runehive.content.itemaction.impl.SerpentineHelm.UNCHARGED_HELM = 12_929 static private
Definition at line 20 of file SerpentineHelm.java.
Referenced by charge(), drop(), inventory(), itemOnItem(), and uncharge().
ZULRAH_SCALES
final short com.runehive.content.itemaction.impl.SerpentineHelm.ZULRAH_SCALES = 12_934 static private
Definition at line 18 of file SerpentineHelm.java.
Referenced by itemOnItem(), and uncharge().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/SerpentineHelm.java