RuneHive-Game: com.runehive.game.world.items.ground.GroundItem Class Reference
com.runehive.game.world.items.ground.GroundItem Class Reference
Represents a single Ground item on the world map.
Public Member Functions
void addToRegion (Region region)
Adds this entity to the specified region.
boolean canSee (Player other)
boolean equals (Object obj)
String getName ()
Gets the name of this entity.
EntityType getType ()
Gets the EntityType.
int hashCode ()
void register ()
Registers an entity to the World.
void removeFromRegion (Region region)
Removes this entity from the specified region.
String toString ()
void unregister ()
Unregisters an entity from the World.
Public Member Functions inherited from com.runehive.game.world.entity.Entity
Entity (Position position)
Entity (Position position, boolean visible)
Position getCenterPosition ()
int getHeight ()
int getIndex ()
Position getPosition ()
Region getRegion ()
int getX ()
int getY ()
boolean is (EntityType type)
final boolean isCustomObject ()
Check if an entity is an object.
final boolean isRegistered ()
final boolean isStaticObject ()
Check if an entity is an object.
boolean isValid ()
Validates this npc based on its current region and registered state.
boolean isVisible ()
int length ()
void onStep ()
void setIndex (int index)
void setLength (int length)
void setPosition (Position position)
void setVisible (boolean visible)
void setWidth (int width)
void setX (int x)
void setY (int y)
void setZ (int z)
int width ()
Static Public Member Functions
static GroundItem create (Player player, Item item)
Creates a new GroundItem object for a player and an item.
static GroundItem create (Player player, Item item, Position position)
Creates a new GroundItem object for a player, an item and position.
static void createGlobal (Player player, Item item)
Creates a new GroundItem object for a player and an item.
static void createGlobal (Player player, Item item, Position position)
Creates a new GroundItem object for a player and an item.
static void pickup (Player player, Item item, Position position)
Attempts to pick the specified item up.
Static Public Member Functions inherited from com.runehive.game.world.Interactable
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Public Attributes
boolean canIronMenPickThisItemUp = true
final GroundItemEvent event = new GroundItemEvent(this)
The randomevent for ground item.
final Item item
The item that represents this ground item.
final Player player
The optional player whom owns this item.
GroundItemPolicy policy
The policy for this ground item.
Public Attributes inherited from com.runehive.game.world.entity.Entity
int instance = DEFAULT_INSTANCE
Private Member Functions
GroundItem (Player player, Item item, Position position)
Constructs a new GroundItem object for a player, an item, and a position.
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.Entity
static final int DEFAULT_INSTANCE = 0
Protected Member Functions inherited from com.runehive.game.world.entity.Entity
Entity destroy ()
Destroys this entity.
void setRegistered (boolean registered)
Detailed Description
Represents a single Ground item on the world map.
Author
Stand Up
Daniel
Michael | Chex
Since
27-12-2016.
Definition at line 28 of file GroundItem.java.
Constructor & Destructor Documentation
GroundItem()
com.runehive.game.world.items.ground.GroundItem.GroundItem (Player player, Item item, Position position) private
Constructs a new GroundItem object for a player, an item, and a position.
Definition at line 81 of file GroundItem.java.
{
        super(position);
        this.item = item;
        this.player = player;
        this.instance = player.instance;
    }
References item, player, and com.runehive.game.world.entity.Entity.position.
Referenced by addToRegion(), create(), create(), createGlobal(), createGlobal(), equals(), and pickup().
Member Function Documentation
addToRegion()
void com.runehive.game.world.items.ground.GroundItem.addToRegion (Region region)
Adds this entity to the specified region.
Parameters
region The region.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 139 of file GroundItem.java.
{
        if (item.getId() == 11283) {
            item.setId(11284);
            player.dragonfireCharges = 0;
        }
     /*   System.out.println("item id: "+item.getId());
        System.out.println("item amt: "+item.getAmount());*/
        GroundItem groundItem = region.getGroundItem(item.getId(), getPosition());
        if (groundItem != null && groundItem.item.isStackable()
                && policy.equals(groundItem.policy) && (policy == GroundItemPolicy.GLOBAL || player.usernameLong == groundItem.player.usernameLong)) {
            groundItem.event.cancel();
            item.incrementAmountBy(groundItem.item.getAmount());
        }
        Region[] regions = World.getRegions().getSurroundingRegions(getPosition());
        for (Region reg : regions) {
            reg.getPlayers(getHeight()).forEach(player -> {
                if (canSee(player)) {
                    player.send(new SendGroundItem(this));
                }
            });
        }
        region.addGroundItem(this);
        World.schedule(event);
    }
References com.runehive.game.task.Task.cancel(), canSee(), event, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.region.RegionManager.getSurroundingRegions(), com.runehive.game.world.items.ground.GroundItemPolicy.GLOBAL, GroundItem(), com.runehive.game.world.items.Item.isStackable(), item, player, policy, com.runehive.game.world.World.schedule(), and com.runehive.game.world.entity.mob.player.Player.usernameLong.
canSee()
boolean com.runehive.game.world.items.ground.GroundItem.canSee (Player other)
Definition at line 88 of file GroundItem.java.
{
        if (item.isTradeable() && policy.equals(GroundItemPolicy.GLOBAL) && instance == other.instance) {
            return true;
        }
        return player.usernameLong == other.usernameLong;
    }
References com.runehive.game.world.items.ground.GroundItemPolicy.GLOBAL, com.runehive.game.world.entity.Entity.instance, item, policy, and com.runehive.game.world.entity.mob.player.Player.usernameLong.
Referenced by addToRegion(), and removeFromRegion().
create() [1/2]
GroundItem com.runehive.game.world.items.ground.GroundItem.create (Player player, Item item) static
Creates a new GroundItem object for a player and an item.
Definition at line 62 of file GroundItem.java.
{
        GroundItem groundItem = new GroundItem(player, item, player.getPosition());
        groundItem.policy = GroundItemPolicy.ONLY_OWNER;
        groundItem.instance = player.instance;
        groundItem.register();
        World.getDataBus().publish(new DropItemLogEvent(player, groundItem));
        return groundItem;
    }
References com.runehive.game.world.World.getDataBus(), GroundItem(), item, com.runehive.game.world.items.ground.GroundItemPolicy.ONLY_OWNER, player, com.runehive.game.event.bus.DataBus.publish(), and register().
Referenced by com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.create(), com.runehive.content.skill.impl.woodcutting.BirdsNest.drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.lms.LMSGame.giveChestItems(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMiscDrops(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.lms.LMSGame.onDeath(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.tridentRunes(), and com.runehive.game.world.items.containers.equipment.Equipment.unEquip().
create() [2/2]
GroundItem com.runehive.game.world.items.ground.GroundItem.create (Player player, Item item, Position position) static
Creates a new GroundItem object for a player, an item and position.
Definition at line 72 of file GroundItem.java.
{
        GroundItem groundItem = new GroundItem(player, item, position);
        groundItem.policy = GroundItemPolicy.ONLY_OWNER;
        groundItem.instance = player.instance;
        groundItem.register();
        return groundItem;
    }
References GroundItem(), item, com.runehive.game.world.items.ground.GroundItemPolicy.ONLY_OWNER, player, com.runehive.game.world.entity.Entity.position, and register().
createGlobal() [1/2]
void com.runehive.game.world.items.ground.GroundItem.createGlobal (Player player, Item item) static
Creates a new GroundItem object for a player and an item.
Definition at line 45 of file GroundItem.java.
{
        GroundItem groundItem = new GroundItem(player, item, player.getPosition());
        groundItem.policy = GroundItemPolicy.GLOBAL;
        groundItem.instance = player.instance;
        groundItem.register();
        World.getDataBus().publish(new DropItemLogEvent(player, groundItem));
    }
References com.runehive.game.world.World.getDataBus(), com.runehive.game.world.items.ground.GroundItemPolicy.GLOBAL, GroundItem(), item, player, com.runehive.game.event.bus.DataBus.publish(), and register().
Referenced by com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.lms.LMSGame.onDeath(), and com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct().
createGlobal() [2/2]
void com.runehive.game.world.items.ground.GroundItem.createGlobal (Player player, Item item, Position position) static
Creates a new GroundItem object for a player and an item.
Definition at line 54 of file GroundItem.java.
{
        GroundItem groundItem = new GroundItem(player, item, position);
        groundItem.policy = GroundItemPolicy.GLOBAL;
        groundItem.instance = player.instance;
        groundItem.register();
    }
References com.runehive.game.world.items.ground.GroundItemPolicy.GLOBAL, GroundItem(), item, player, com.runehive.game.world.entity.Entity.position, and register().
equals()
boolean com.runehive.game.world.items.ground.GroundItem.equals (Object obj)
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 189 of file GroundItem.java.
{
        if (obj == this) return true;
        if (obj instanceof GroundItem) {
            GroundItem other = (GroundItem) obj;
            return other.getPosition().equals(getPosition())
                && other.item.equals(item)
                && player.usernameLong == other.player.usernameLong;
        }
        return false;
    }
References com.runehive.game.world.items.Item.equals(), com.runehive.game.world.position.Position.equals(), com.runehive.game.world.entity.Entity.getPosition(), GroundItem(), item, player, and com.runehive.game.world.entity.mob.player.Player.usernameLong.
getName()
String com.runehive.game.world.items.ground.GroundItem.getName ()
Gets the name of this entity.
Returns
The entity's name.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 179 of file GroundItem.java.
{
        return item.getName();
    }
References item.
getType()
EntityType com.runehive.game.world.items.ground.GroundItem.getType ()
Gets the EntityType.
Returns
The EntityType.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 184 of file GroundItem.java.
{
        return EntityType.GROUND_ITEM;
    }
References com.runehive.game.world.entity.EntityType.GROUND_ITEM.
hashCode()
int com.runehive.game.world.items.ground.GroundItem.hashCode ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 201 of file GroundItem.java.
{
        return Objects.hash(getPosition(), getIndex());
    }
References com.runehive.game.world.entity.Entity.getIndex(), and com.runehive.game.world.entity.Entity.getPosition().
pickup()
void com.runehive.game.world.items.ground.GroundItem.pickup (Player player, Item item, Position position) static
Attempts to pick the specified item up.
Definition at line 96 of file GroundItem.java.
{
        GroundItem result = position.getRegion().getGroundItem(item.getId(), position);
        if (result == null) {
            return;
        }
        if (PlayerRight.isIronman(player) && (!result.canIronMenPickThisItemUp || result.player.usernameLong != player.usernameLong)) {
            player.send(new SendMessage("As an iron man you may not pick up this item."));
            return;
        }
        if (!player.inventory.hasCapacityFor(item)) {
            player.send(new SendMessage("You don't have enough inventory space."));
            return;
        }
        result.event.cancel();
        player.inventory.add(result.item);
        PluginManager.getDataBus().publish(player, new PickupItemEvent(result));
    }
References com.runehive.game.task.Task.cancel(), canIronMenPickThisItemUp, event, com.runehive.game.plugin.PluginManager.getDataBus(), GroundItem(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), item, player, com.runehive.game.world.entity.Entity.position, com.runehive.game.event.bus.PlayerDataBus.publish(), and com.runehive.game.world.entity.mob.player.Player.usernameLong.
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.PickupWaypoint.onDestination().
register()
void com.runehive.game.world.items.ground.GroundItem.register ()
Registers an entity to the World.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 119 of file GroundItem.java.
{
        if (isRegistered()) {
            return;
        }
        setRegistered(true);
        setPosition(getPosition());
    }
References com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.isRegistered(), com.runehive.game.world.entity.Entity.setPosition(), and com.runehive.game.world.entity.Entity.setRegistered().
Referenced by create(), create(), createGlobal(), and createGlobal().
removeFromRegion()
void com.runehive.game.world.items.ground.GroundItem.removeFromRegion (Region region)
Removes this entity from the specified region.
Parameters
region The region.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 166 of file GroundItem.java.
{
        Region[] regions = World.getRegions().getSurroundingRegions(getPosition());
        for (Region reg : regions) {
            reg.getPlayers(getHeight()).forEach(player -> {
                if (canSee(player)) {
                    player.send(new SendRemoveGroundItem(this));
                }
            });
        }
        region.removeGroundItem(this);
    }
References canSee(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.region.RegionManager.getSurroundingRegions(), and player.
Referenced by unregister().
toString()
String com.runehive.game.world.items.ground.GroundItem.toString ()
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 206 of file GroundItem.java.
{
        return "GroundItem[owner=" + player.getUsername() + ", position=" + getPosition() + ", index=" + getIndex() + ", item=" + item.getName() + "]";
    }
References com.runehive.game.world.entity.Entity.getIndex(), com.runehive.game.world.entity.Entity.getPosition(), item, and player.
unregister()
void com.runehive.game.world.items.ground.GroundItem.unregister ()
Unregisters an entity from the World.
Reimplemented from com.runehive.game.world.entity.Entity.
Definition at line 129 of file GroundItem.java.
{
        if (!isRegistered()) {
            return;
        }
        setRegistered(false);
        removeFromRegion(getRegion());
    }
References com.runehive.game.world.entity.Entity.getRegion(), com.runehive.game.world.entity.Entity.isRegistered(), removeFromRegion(), and com.runehive.game.world.entity.Entity.setRegistered().
Member Data Documentation
canIronMenPickThisItemUp
boolean com.runehive.game.world.items.ground.GroundItem.canIronMenPickThisItemUp = true
Definition at line 42 of file GroundItem.java.
Referenced by pickup().
event
final GroundItemEvent com.runehive.game.world.items.ground.GroundItem.event = new GroundItemEvent(this)
The randomevent for ground item.
Definition at line 37 of file GroundItem.java.
Referenced by addToRegion(), and pickup().
item
final Item com.runehive.game.world.items.ground.GroundItem.item
The item that represents this ground item.
Definition at line 31 of file GroundItem.java.
Referenced by addToRegion(), canSee(), create(), create(), createGlobal(), createGlobal(), equals(), getName(), GroundItem(), pickup(), and toString().
player
final Player com.runehive.game.world.items.ground.GroundItem.player
The optional player whom owns this item.
Definition at line 34 of file GroundItem.java.
Referenced by addToRegion(), create(), create(), createGlobal(), createGlobal(), equals(), GroundItem(), pickup(), removeFromRegion(), and toString().
policy
GroundItemPolicy com.runehive.game.world.items.ground.GroundItem.policy
The policy for this ground item.
Definition at line 40 of file GroundItem.java.
Referenced by addToRegion(), and canSee().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/ground/GroundItem.java