RuneHive-Game: com.runehive.game.world.entity.combat.formula.RangedFormula Class Reference
com.runehive.game.world.entity.combat.formula.RangedFormula Class Reference
Public Member Functions
int modifyAccuracy (Mob attacker, Mob defender, int roll)
int modifyAggressive (Mob attacker, Mob defender, int roll)
int modifyAggressiveBonus (Mob attacker, Mob defender, int bonus)
int modifyDamage (Mob attacker, Mob defender, int damage)
int modifyDefensive (Mob attacker, Mob defender, int roll)
int modifyDefensiveBonus (Mob attacker, Mob defender, int bonus)
int modifyOffensiveBonus (Mob attacker, Mob defender, int bonus)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Detailed Description
Definition at line 10 of file RangedFormula.java.
Member Function Documentation
modifyAccuracy()
int com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAccuracy (Mob attacker, Mob defender, int roll)
Definition at line 13 of file RangedFormula.java.
{
        FightType fightType = attacker.getCombat().getFightType();
        int level = attacker.skills.getLevel(Skill.RANGED);
        int effectiveAccuracy = attacker.getCombat().modifyRangedLevel(defender, level);
        return 8 + effectiveAccuracy + fightType.getStyle().getAccuracyIncrease();
    }
References com.runehive.game.world.entity.combat.attack.FightStyle.getAccuracyIncrease(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.combat.attack.FightType.getStyle(), com.runehive.game.world.entity.skill.Skill.RANGED, and com.runehive.game.world.entity.mob.Mob.skills.
modifyAggressive()
int com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAggressive (Mob attacker, Mob defender, int roll)
Definition at line 21 of file RangedFormula.java.
{
        int level = attacker.skills.getLevel(Skill.RANGED);
        return 8 + attacker.getCombat().modifyRangedLevel(defender, level);
    }
References com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.RANGED, and com.runehive.game.world.entity.mob.Mob.skills.
modifyAggressiveBonus()
int com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAggressiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 41 of file RangedFormula.java.
{
        bonus = attacker.getBonus(Equipment.RANGED_STRENGTH);
        return attacker.getCombat().modifyAggresiveBonus(defender, bonus);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getCombat(), and com.runehive.game.world.items.containers.equipment.Equipment.RANGED_STRENGTH.
modifyDamage()
int com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDamage (Mob attacker, Mob defender, int damage)
Definition at line 53 of file RangedFormula.java.
{
        damage = attacker.getCombat().modifyDamage(defender, damage);
        if (defender.prayer.isActive(Prayer.PROTECT_FROM_RANGE)) {
            damage *= !attacker.isPlayer() || defender.isNpc() ? 0.0 : 0.6;
        }
        return damage;
    }
References com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.Mob.prayer, and com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_RANGE.
modifyDefensive()
int com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensive (Mob attacker, Mob defender, int roll)
Definition at line 27 of file RangedFormula.java.
{
        FightType fightType = defender.getCombat().getFightType();
        int level = defender.skills.getLevel(Skill.DEFENCE);
        int effectiveDefence = defender.getCombat().modifyDefenceLevel(attacker, level);
        return 8 + effectiveDefence + fightType.getStyle().getDefensiveIncrease();
    }
References com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.combat.attack.FightStyle.getDefensiveIncrease(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.combat.attack.FightType.getStyle(), and com.runehive.game.world.entity.mob.Mob.skills.
modifyDefensiveBonus()
int com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 47 of file RangedFormula.java.
{
        bonus = defender.getBonus(Equipment.RANGED_DEFENSE);
        return defender.getCombat().modifyDefensiveBonus(attacker, bonus);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getCombat(), and com.runehive.game.world.items.containers.equipment.Equipment.RANGED_DEFENSE.
modifyOffensiveBonus()
int com.runehive.game.world.entity.combat.formula.RangedFormula.modifyOffensiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 35 of file RangedFormula.java.
{
        bonus = attacker.getBonus(Equipment.RANGED_OFFENSE);
        return attacker.getCombat().modifyOffensiveBonus(defender, bonus);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getCombat(), and com.runehive.game.world.items.containers.equipment.Equipment.RANGED_OFFENSE.
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/formula/RangedFormula.java