RuneHive-Game: com.runehive.content.emote.EmoteHandler Class Reference
com.runehive.content.emote.EmoteHandler Class Reference
This class handles emotes from the emote tab and skill cape.
Static Public Member Functions
static boolean contains (Player player, EmoteUnlockable emote)
static boolean containsAll (Player player, EmoteUnlockable... emotes)
static void refresh (Player player)
Handles refreshing the emote tab.
static EmoteUnlockable selectRandom (Player player, EmoteUnlockable... emotes)
static void unlock (Player player, EmoteUnlockable emote)
Handles unlocking an emote.
static void unlockAll (Player player)
Handles unlocking all the emotes.
static void updateSkillcape (Player player)
Updates the skillcape emote.
Detailed Description
This class handles emotes from the emote tab and skill cape.
Author
Daniel | Obey
Definition at line 20 of file EmoteHandler.java.
Member Function Documentation
contains()
boolean com.runehive.content.emote.EmoteHandler.contains (Player player, EmoteUnlockable emote) static
Definition at line 58 of file EmoteHandler.java.
{
        return player.emoteUnlockable.contains(emote);
    }
References com.runehive.game.world.entity.mob.player.Player.emoteUnlockable.
Referenced by containsAll(), and selectRandom().
containsAll()
boolean com.runehive.content.emote.EmoteHandler.containsAll (Player player, EmoteUnlockable... emotes) static
Definition at line 62 of file EmoteHandler.java.
{
        for (EmoteUnlockable emote : emotes) {
            if (!contains(player, emote)) {
                return false;
            }
        }
        return true;
    }
References contains().
Referenced by com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), and com.runehive.content.itemaction.impl.MimeBox.inventory().
refresh()
void com.runehive.content.emote.EmoteHandler.refresh (Player player) static
Handles refreshing the emote tab.
Parameters
player The player refreshing the emote tab.
Definition at line 28 of file EmoteHandler.java.
{
        for (Emote emote : Emote.values()) {
            if (emote.getConfig() != -1) {
                int flag = emote.activated(player) ? 0 : 1;
                player.send(new SendConfig(emote.getConfig(), flag));
            }
        }
        updateSkillcape(player);
    }
References com.runehive.game.world.entity.mob.player.Player.send(), and updateSkillcape().
Referenced by com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), com.runehive.content.itemaction.impl.MimeBox.inventory(), com.runehive.game.world.entity.mob.player.PlayerAssistant.login(), unlock(), and unlockAll().
selectRandom()
EmoteUnlockable com.runehive.content.emote.EmoteHandler.selectRandom (Player player, EmoteUnlockable... emotes) static
Definition at line 71 of file EmoteHandler.java.
{
        List<EmoteUnlockable> selected = new ArrayList<>(emotes.length);
        for (EmoteUnlockable emote : emotes) {
            if (!contains(player, emote)) {
                selected.add(emote);
            }
        }
        return selected.isEmpty() ? null : Utility.randomElement(selected);
    }
References contains(), and com.runehive.util.Utility.randomElement().
Referenced by com.runehive.content.itemaction.impl.DrillDemonBox.inventory(), and com.runehive.content.itemaction.impl.MimeBox.inventory().
unlock()
void com.runehive.content.emote.EmoteHandler.unlock (Player player, EmoteUnlockable emote) static
Handles unlocking an emote.
Parameters
player the player unlocking the emote.
emote The emote being activated.
Definition at line 89 of file EmoteHandler.java.
{
        if (!player.emoteUnlockable.contains(emote)) {
            player.emoteUnlockable.add(emote);
            refresh(player);
            player.send(new SendMessage("Congratulations, you have unlocked the " + Utility.formatEnum(emote.name()) + " emote."));
        }
    }
References com.runehive.game.world.entity.mob.player.Player.emoteUnlockable, com.runehive.util.Utility.formatEnum(), refresh(), and com.runehive.game.world.entity.mob.player.Player.send().
unlockAll()
void com.runehive.content.emote.EmoteHandler.unlockAll (Player player) static
Handles unlocking all the emotes.
Parameters
player The player unlocking all the emotes.
Definition at line 103 of file EmoteHandler.java.
{
        Arrays.stream(EmoteUnlockable.values()).forEach(e -> {
            if (!player.emoteUnlockable.contains(e)) {
                player.emoteUnlockable.add(e);
            }
        });
        refresh(player);
        player.send(new SendMessage("You have successfully unlocked all the emotes."));
    }
References com.runehive.game.world.entity.mob.player.Player.emoteUnlockable, refresh(), and com.runehive.game.world.entity.mob.player.Player.send().
updateSkillcape()
void com.runehive.content.emote.EmoteHandler.updateSkillcape (Player player) static
Updates the skillcape emote.
Parameters
player The player instance.
Definition at line 44 of file EmoteHandler.java.
{
        int flag = 1;
        Item item = player.equipment.get(Equipment.CAPE_SLOT);
        if (item != null) {
            Skillcape skillcape = Skillcape.forId(item.getId());
            if (skillcape != null) {
                flag = 0;
            }
        }
        player.send(new SendConfig(1114, flag));
    }
References com.runehive.game.world.items.containers.equipment.Equipment.CAPE_SLOT, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.content.emote.Skillcape.forId(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getId(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by refresh().
The documentation for this class was generated from the following file:
java/com/runehive/content/emote/EmoteHandler.java