RuneHive-Game: com.runehive.game.world.entity.mob.player.PlayerKilling Class Reference
com.runehive.game.world.entity.mob.player.PlayerKilling Class Reference
Static Public Member Functions
static void add (Player player, String host)
static boolean contains (Player player, String host)
static void handle (Player killer, Player victim)
static boolean remove (Player player, String host)
Detailed Description
Definition at line 13 of file PlayerKilling.java.
Member Function Documentation
add()
void com.runehive.game.world.entity.mob.player.PlayerKilling.add (Player player, String host) static
Definition at line 62 of file PlayerKilling.java.
{
        if (host == null || host.isEmpty()) {
            return;
        }
        if (player.lastKilled.contains(host)) {
            return;
        }
        if (player.lastKilled.size() >= 2) {
            player.lastKilled.removeFirst();
        }
        player.lastKilled.add(host);
    }
Referenced by handle().
contains()
boolean com.runehive.game.world.entity.mob.player.PlayerKilling.contains (Player player, String host) static
Definition at line 79 of file PlayerKilling.java.
{
        return player.lastKilled != null && player.lastKilled.contains(host);
    }
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.death().
handle()
void com.runehive.game.world.entity.mob.player.PlayerKilling.handle (Player killer, Player victim) static
Definition at line 15 of file PlayerKilling.java.
{
        if (killer.isBot) {
            return;
        }
        if (killer.lastHost.equalsIgnoreCase(victim.lastHost)) {
            killer.message("<col=FF0019>You were not rewarded since you killed someone with your same IP.");
            return;
        }
        if (killer.clanChannel != null && victim.clanChannel != null && killer.clanChannel.getName().equalsIgnoreCase(victim.clanChannel.getName())) {
            if (!killer.clanChannel.getName().equals("osroyale")) {
                killer.message("<col=FF0019>You were not rewarded since you killed someone from your clan.");
                return;
            }
        }
        int reward = PlayerRight.getBloodMoney(killer);
        killer.inventory.addOrDrop(new Item(13307, reward));
        killer.message("<col=295EFF>You were rewarded with " + reward + " blood money for that kill.");
        killer.killstreak.add();
        for (Item item : killer.inventory) {
            if (item == null)
                continue;
            EmblemData emblem = EmblemData.forId(item.getId());
            if (emblem == null)
                continue;
            if (emblem.getNext() == -1)
                continue;
            killer.inventory.replace(item.getId(), emblem.getNext(), true);
            break;
        }
        killer.forClan(channel -> {
            channel.activateTask(PLAYER_KILLING, killer.getName());
            channel.activateAchievement(ClanAchievement.PLAYER_KILLER_I);
            channel.activateAchievement(ClanAchievement.PLAYER_KILLER_II);
            channel.activateAchievement(ClanAchievement.PLAYER_KILLER_III);
        });
        Pets.onReward(killer, PetData.BABY_DARTH);
        InterfaceWriter.write(new InformationWriter(killer));
        add(killer, victim.lastHost);
    }
References com.runehive.content.combat.Killstreak.add(), add(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.content.pet.PetData.BABY_DARTH, com.runehive.game.world.entity.mob.player.Player.clanChannel, com.runehive.game.world.entity.mob.player.Player.forClan(), com.runehive.content.EmblemData.forId(), com.runehive.game.world.entity.mob.player.PlayerRight.getBloodMoney(), com.runehive.game.world.items.Item.getId(), com.runehive.content.clanchannel.channel.ClanChannel.getName(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.EmblemData.getNext(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.isBot, com.runehive.game.world.entity.mob.player.Player.killstreak, com.runehive.game.world.entity.mob.player.Player.lastHost, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.pet.Pets.onReward(), com.runehive.content.clanchannel.content.ClanAchievement.PLAYER_KILLER_I, com.runehive.content.clanchannel.content.ClanAchievement.PLAYER_KILLER_II, com.runehive.content.clanchannel.content.ClanAchievement.PLAYER_KILLER_III, com.runehive.game.world.items.containers.ItemContainer.replace(), and com.runehive.content.writer.InterfaceWriter.write().
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.death().
remove()
boolean com.runehive.game.world.entity.mob.player.PlayerKilling.remove (Player player, String host) static
Definition at line 75 of file PlayerKilling.java.
{
        return player.lastKilled.remove(host);
    }
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/PlayerKilling.java