RuneHive-Game: com.runehive.util.SortedQueue< E > Class Template Reference
com.runehive.util.SortedQueue< E > Class Template Reference
Public Member Functions
boolean add (E element)
boolean addAll (Collection<? extends E > collection)
void clear ()
boolean contains (Object other)
boolean containsAll (Collection<?> collection)
E element ()
boolean isEmpty ()
Iterator< E > iterator ()
boolean offer (E element)
E peek ()
E poll ()
E remove ()
boolean remove (Object other)
boolean removeAll (Collection<?> collection)
boolean retainAll (Collection<?> collection)
int size ()
SortedQueue (int initial)
Object[] toArray ()
Package Functions
public< T > T[] toArray (T[] array)
Private Attributes
Object[] elements
Detailed Description
Definition at line 7 of file SortedQueue.java.
Constructor & Destructor Documentation
SortedQueue()
com.runehive.util.SortedQueue< E >.SortedQueue (int initial)
Definition at line 11 of file SortedQueue.java.
{
        elements = new Object[initial];
    }
References elements.
Member Function Documentation
add()
boolean com.runehive.util.SortedQueue< E >.add (E element)
Definition at line 71 of file SortedQueue.java.
{
        return false;
    }
References element().
addAll()
boolean com.runehive.util.SortedQueue< E >.addAll (Collection<? extends E > collection)
Definition at line 81 of file SortedQueue.java.
{
        return false;
    }
clear()
void com.runehive.util.SortedQueue< E >.clear ()
Definition at line 86 of file SortedQueue.java.
{
    }
contains()
boolean com.runehive.util.SortedQueue< E >.contains (Object other)
Definition at line 21 of file SortedQueue.java.
{
        return false;
    }
containsAll()
boolean com.runehive.util.SortedQueue< E >.containsAll (Collection<?> collection)
Definition at line 26 of file SortedQueue.java.
{
        return false;
    }
element()
E com.runehive.util.SortedQueue< E >.element ()
Definition at line 95 of file SortedQueue.java.
                       {
        return null;
    }
Referenced by add(), and offer().
isEmpty()
boolean com.runehive.util.SortedQueue< E >.isEmpty ()
Definition at line 31 of file SortedQueue.java.
{
        return false;
    }
iterator()
Iterator< E > com.runehive.util.SortedQueue< E >.iterator ()
Definition at line 16 of file SortedQueue.java.
{
        return null;
    }
offer()
boolean com.runehive.util.SortedQueue< E >.offer (E element)
Definition at line 76 of file SortedQueue.java.
{
        return false;
    }
References element().
peek()
E com.runehive.util.SortedQueue< E >.peek ()
Definition at line 100 of file SortedQueue.java.
                    {
        return null;
    }
poll()
E com.runehive.util.SortedQueue< E >.poll ()
Definition at line 90 of file SortedQueue.java.
                    {
        return null;
    }
remove() [1/2]
E com.runehive.util.SortedQueue< E >.remove ()
Definition at line 56 of file SortedQueue.java.
                      {
        return null;
    }
remove() [2/2]
boolean com.runehive.util.SortedQueue< E >.remove (Object other)
Definition at line 51 of file SortedQueue.java.
{
        return false;
    }
removeAll()
boolean com.runehive.util.SortedQueue< E >.removeAll (Collection<?> collection)
Definition at line 61 of file SortedQueue.java.
{
        return false;
    }
retainAll()
boolean com.runehive.util.SortedQueue< E >.retainAll (Collection<?> collection)
Definition at line 66 of file SortedQueue.java.
{
        return false;
    }
size()
int com.runehive.util.SortedQueue< E >.size ()
Definition at line 36 of file SortedQueue.java.
                      {
        return 0;
    }
toArray() [1/2]
Object[] com.runehive.util.SortedQueue< E >.toArray ()
Definition at line 41 of file SortedQueue.java.
{
        return elements;
    }
References elements.
toArray() [2/2]
public< T > T[] com.runehive.util.SortedQueue< E >.toArray (T[] array) package
Definition at line 46 of file SortedQueue.java.
{
        return null;
    }
Member Data Documentation
elements
Object [] com.runehive.util.SortedQueue< E >.elements private
Definition at line 9 of file SortedQueue.java.
Referenced by SortedQueue(), and toArray().
The documentation for this class was generated from the following file:
java/com/runehive/util/SortedQueue.java