RuneHive-Game: com.runehive.game.world.entity.combat.accuracy.MagicAccuracy Class Reference
com.runehive.game.world.entity.combat.accuracy.MagicAccuracy Class Reference
@Author Origin 2/22/2023
Static Public Member Functions
static int getAttackBonus (Mob attacker)
static double getAttackRoll (Mob attacker)
static int getDefenceBonus (Mob defender)
static double getDefenceRoll (Mob defender)
static int getMagicLevel (Mob mob)
static double getPrayerBonus (Mob attacker)
static double getPrayerBonusDefender (Mob defender)
static boolean successful (Mob attacker, Mob defender)
Static Public Attributes
static final SecureRandom srand = new SecureRandom()
Detailed Description
@Author Origin 2/22/2023
Definition at line 17 of file MagicAccuracy.java.
Member Function Documentation
getAttackBonus()
int com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getAttackBonus (Mob attacker) static
Definition at line 41 of file MagicAccuracy.java.
{
        return attacker.getBonus(Equipment.MAGIC_OFFENSE);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), and com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_OFFENSE.
Referenced by getAttackRoll().
getAttackRoll()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getAttackRoll (Mob attacker) static
Definition at line 104 of file MagicAccuracy.java.
{
        double magicLevel = getMagicLevel(attacker);
        double attackBonus = getAttackBonus(attacker);
        double effectiveLevel;
        if (attacker instanceof Player) {
            effectiveLevel = magicLevel * getPrayerBonus(attacker) + 8;
        } else {
            effectiveLevel = magicLevel + 9;
        }
        return effectiveLevel * (attackBonus + 64);
    }
References getAttackBonus(), getMagicLevel(), and getPrayerBonus().
Referenced by successful(), and com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.successful().
getDefenceBonus()
int com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getDefenceBonus (Mob defender) static
Definition at line 45 of file MagicAccuracy.java.
{
        return defender.getBonus(Equipment.MAGIC_DEFENSE);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), and com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_DEFENSE.
Referenced by getDefenceRoll().
getDefenceRoll()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getDefenceRoll (Mob defender) static
Definition at line 49 of file MagicAccuracy.java.
{
        double magicLevel = getMagicLevel(defender);
        double defenceBonus = getDefenceBonus(defender);
        double effectiveLevel;
        if (defender instanceof Player) {
            magicLevel *= getPrayerBonusDefender(defender);
            double defenceLevel = defender.skills.getLevel(Skill.DEFENCE);
            switch (defender.getCombat().getFightType().getStyle()) {
                case DEFENSIVE -> defenceLevel += 3;
                case CONTROLLED -> defenceLevel += 1;
            }
            effectiveLevel = magicLevel * 0.7 + defenceLevel * 0.3 + 8;
        } else {
            effectiveLevel = magicLevel + 9;
        }
        return effectiveLevel * (defenceBonus + 64);
    }
References com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.Mob.getCombat(), getDefenceBonus(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), getMagicLevel(), getPrayerBonusDefender(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by successful(), and com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.successful().
getMagicLevel()
int com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getMagicLevel (Mob mob) static
Definition at line 71 of file MagicAccuracy.java.
{
        int magicLevel = 1;
        if (mob instanceof Npc npc) {
            int[] skills = npc.definition.getSkills();
            if (skills != null) {
                magicLevel = skills[Skill.MAGIC];
            }
        } else {
            magicLevel = mob.skills.getLevel(Skill.MAGIC);
        }
        return magicLevel;
    }
References com.runehive.game.world.entity.skill.Skill.MAGIC.
Referenced by getAttackRoll(), and getDefenceRoll().
getPrayerBonus()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonus (Mob attacker) static
Definition at line 84 of file MagicAccuracy.java.
{
        double prayerBonus = 1;
        if (attacker.prayer.isActive(Prayer.MYSTIC_WILL))
            prayerBonus *= 1.05D; // 5% magic level boost
        else if (attacker.prayer.isActive(Prayer.MYSTIC_LORE))
            prayerBonus *= 1.10D; // 10% magic level boost
        else if (attacker.prayer.isActive(Prayer.MYSTIC_MIGHT))
            prayerBonus *= 1.15D; // 15% magic level boost
        else if (attacker.prayer.isActive(Prayer.AUGURY))
            prayerBonus *= 1.25D; // 25% magic level boost
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.AUGURY, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_LORE, com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_MIGHT, com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_WILL, and com.runehive.game.world.entity.mob.Mob.prayer.
Referenced by getAttackRoll().
getPrayerBonusDefender()
double com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonusDefender (Mob defender) static
Definition at line 97 of file MagicAccuracy.java.
{
        double prayerBonus = 1;
        if (defender.prayer.isActive(Prayer.AUGURY))
            prayerBonus *= 1.25D;
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.AUGURY, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), and com.runehive.game.world.entity.mob.Mob.prayer.
Referenced by getDefenceRoll().
successful()
boolean com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.successful (Mob attacker, Mob defender) static
Definition at line 21 of file MagicAccuracy.java.
{
        double attackRoll = getAttackRoll(attacker);
        if (attacker instanceof Player player) {
            if (FormulaUtils.voidMagic(player)) {
                attackRoll *= 1.45;
            }
        }
        double defenceRoll = getDefenceRoll(defender);
        double chance;
        if (attackRoll > defenceRoll)
            chance = 1D - (defenceRoll + 2D) / (2D * (attackRoll + 1D));
        else
            chance = attackRoll / (2D * (defenceRoll + 1D));
        double roll = srand.nextDouble();
        return chance > roll;
    }
References getAttackRoll(), getDefenceRoll(), srand, and com.runehive.game.world.entity.combat.FormulaUtils.voidMagic().
Referenced by com.runehive.game.world.entity.combat.attack.FormulaFactory.isAccurate().
Member Data Documentation
srand
final SecureRandom com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.srand = new SecureRandom() static
Definition at line 19 of file MagicAccuracy.java.
Referenced by successful().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/accuracy/MagicAccuracy.java