RuneHive-Game: com.runehive.content.skill.SkillRepository Class Reference
com.runehive.content.skill.SkillRepository Class Reference
Static Public Member Functions
static boolean isBones (int item)
static boolean isHerbloreItem (int item)
static boolean isSkillingItem (int item)
static boolean isSuccess (int skill, int levelRequired)
static boolean isSuccess (Player p, int skill, int levelRequired, int toolLevelRequired)
static boolean isSuccess (Player p, int skillId, int levelRequired, boolean usingDragonHarpoon)
static void load ()
Loads all the skilling data.
static void spawn ()
Spawns all the skilling npcs.
Static Public Attributes
static final int[][] IMPLINGS
Static Private Member Functions
static void declareItems ()
Static Private Attributes
static final List< Integer > BONE_ITEMS = new ArrayList<>()
static final List< Integer > ESSENCE_ITEMS = new ArrayList<>()
static final List< Integer > HERBLORE_ITEMS = new ArrayList<>()
static final Position[] HUNTER_SPAWN_POSITION
Holds all the impling onSpawn locations.
static final List< Integer > SKILLING_ITEMS = new ArrayList<>()
Detailed Description
Definition at line 28 of file SkillRepository.java.
Member Function Documentation
declareItems()
void com.runehive.content.skill.SkillRepository.declareItems () static private
Definition at line 88 of file SkillRepository.java.
{
        for (TreeData tree : TreeData.values()) {
            SKILLING_ITEMS.add(tree.item);
        }
        for (OreData ore : OreData.values()) {
            SKILLING_ITEMS.add(ore.ore);
        }
        for (Fishable fish : Fishable.values()) {
            SKILLING_ITEMS.add(fish.getRawFishId());
        }
        for (GrimyHerb herb : GrimyHerb.values()) {
            HERBLORE_ITEMS.add(herb.getCleanID());
        }
        for (GrimyHerb herb : GrimyHerb.values()) {
            HERBLORE_ITEMS.add(herb.getGrimyID());
        }
        for (BoneData bones : BoneData.values()) {
            BONE_ITEMS.add(bones.getId2());
        }
    }
References BONE_ITEMS, HERBLORE_ITEMS, and SKILLING_ITEMS.
Referenced by load().
isBones()
boolean com.runehive.content.skill.SkillRepository.isBones (int item) static
Definition at line 124 of file SkillRepository.java.
{
        for (int id : BONE_ITEMS) {
            if (item == id)
                return true;
        }
        return false;
    }
References BONE_ITEMS.
isHerbloreItem()
boolean com.runehive.content.skill.SkillRepository.isHerbloreItem (int item) static
Definition at line 116 of file SkillRepository.java.
{
        for (int id : SKILLING_ITEMS) {
            if (item == id)
                return true;
        }
        return false;
    }
References SKILLING_ITEMS.
isSkillingItem()
boolean com.runehive.content.skill.SkillRepository.isSkillingItem (int item) static
Definition at line 109 of file SkillRepository.java.
{
        for (int id : SKILLING_ITEMS) {
            if (item == id)
                return true;
        }
        return false;
    }
References SKILLING_ITEMS.
isSuccess() [1/3]
boolean com.runehive.content.skill.SkillRepository.isSuccess (int skill, int levelRequired) static
Definition at line 133 of file SkillRepository.java.
{
        double successChance = Math.ceil(((double) skill * 50.0D - (double) levelRequired * 15.0D) / (double) levelRequired / 3.0D * 4.0D);
        int roll = Utility.random(99);
        return successChance >= roll;
    }
References com.runehive.util.Utility.random().
Referenced by com.runehive.content.skill.impl.fishing.Fishing.success(), com.runehive.content.skill.impl.mining.Mining.success(), and com.runehive.content.skill.impl.woodcutting.Woodcutting.success().
isSuccess() [2/3]
boolean com.runehive.content.skill.SkillRepository.isSuccess (Player p, int skill, int levelRequired, int toolLevelRequired) static
Definition at line 146 of file SkillRepository.java.
{
        double level = (p.skills.getMaxLevel(skill) + toolLevelRequired) / 2.0D;
        double successChance = Math.ceil((((level * 50.0D) - ((double) levelRequired * 15.0D)) / (double) levelRequired / 3.0D) * 4.0D);
        int roll = Utility.random(99);
        return successChance >= roll;
    }
References com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.util.Utility.random(), and com.runehive.game.world.entity.mob.Mob.skills.
isSuccess() [3/3]
boolean com.runehive.content.skill.SkillRepository.isSuccess (Player p, int skillId, int levelRequired, boolean usingDragonHarpoon) static
Definition at line 139 of file SkillRepository.java.
{
        double level = p.skills.getMaxLevel(skillId);
        double successChance = Math.ceil((((level * 50.0D) - ((double) levelRequired * 15.0D)) / (double) levelRequired / 3.0D) * 4.0D);
        int roll = usingDragonHarpoon ? Utility.random(79) : Utility.random(99);
        return successChance >= roll;
    }
References com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.util.Utility.random(), and com.runehive.game.world.entity.mob.Mob.skills.
load()
void com.runehive.content.skill.SkillRepository.load () static
Loads all the skilling data.
Definition at line 70 of file SkillRepository.java.
{
        Gem.load();
        Hide.load();
        Arrow.load();
        Carvable.load();
        Bolt.load();
        Crossbow.load();
        Featherable.load();
        Stringable.load();
        Agility.declare();
        FishingTool.declare();
        Battlestaff.load();
        Fishable.declare();
        FishingSpot.declare();
        spawn();
        declareItems();
    }
References com.runehive.content.skill.impl.agility.Agility.declare(), com.runehive.content.skill.impl.fishing.Fishable.declare(), com.runehive.content.skill.impl.fishing.FishingSpot.declare(), com.runehive.content.skill.impl.fishing.FishingTool.declare(), declareItems(), com.runehive.content.skill.impl.crafting.impl.Gem.load(), com.runehive.content.skill.impl.crafting.impl.Hide.load(), com.runehive.content.skill.impl.fletching.impl.Arrow.load(), com.runehive.content.skill.impl.fletching.impl.Battlestaff.load(), com.runehive.content.skill.impl.fletching.impl.Bolt.load(), com.runehive.content.skill.impl.fletching.impl.Carvable.load(), com.runehive.content.skill.impl.fletching.impl.Crossbow.load(), com.runehive.content.skill.impl.fletching.impl.Featherable.load(), com.runehive.content.skill.impl.fletching.impl.Stringable.load(), and spawn().
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
spawn()
void com.runehive.content.skill.SkillRepository.spawn () static
Spawns all the skilling npcs.
Definition at line 49 of file SkillRepository.java.
{
        for (Position position : HUNTER_SPAWN_POSITION) {
            int npc;
            if (RandomUtils.success(.50)) {
                npc = Utility.randomElement(Butterfly.values()).butterfly;
            } else {
                npc = Utility.randomElement(Impling.values()).impling;
            }
            new Npc(npc, position, Config.NPC_WALKING_RADIUS, Mob.DEFAULT_INSTANCE, Direction.NORTH).register();
        }
        for (int[] IMPLING : IMPLINGS) {
            new Npc(IMPLING[0], new Position(IMPLING[1], IMPLING[2]), Config.NPC_WALKING_RADIUS, Mob.DEFAULT_INSTANCE, Direction.NORTH).register();
        }
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, HUNTER_SPAWN_POSITION, IMPLINGS, com.runehive.game.world.entity.mob.Direction.NORTH, com.runehive.Config.NPC_WALKING_RADIUS, com.runehive.util.Utility.randomElement(), com.runehive.game.world.entity.mob.npc.Npc.register(), and com.runehive.util.RandomUtils.success().
Referenced by load().
Member Data Documentation
BONE_ITEMS
final List<Integer> com.runehive.content.skill.SkillRepository.BONE_ITEMS = new ArrayList<>() static private
Definition at line 32 of file SkillRepository.java.
Referenced by declareItems(), and isBones().
ESSENCE_ITEMS
final List<Integer> com.runehive.content.skill.SkillRepository.ESSENCE_ITEMS = new ArrayList<>() static private
Definition at line 34 of file SkillRepository.java.
HERBLORE_ITEMS
final List<Integer> com.runehive.content.skill.SkillRepository.HERBLORE_ITEMS = new ArrayList<>() static private
Definition at line 31 of file SkillRepository.java.
Referenced by declareItems().
HUNTER_SPAWN_POSITION
final Position [] com.runehive.content.skill.SkillRepository.HUNTER_SPAWN_POSITION static private
Initial value:
= {
            new Position(3081, 3484), new Position(3101, 3484), new Position(3115, 3506),
            new Position(3094, 3453), new Position(3134, 3511), new Position(3180, 3422),
            new Position(3240, 3440), new Position(3287, 3351), new Position(3257, 3247),
            new Position(3221, 3213), new Position(2803, 3445), new Position(2721, 3472),
            new Position(3349, 3271), new Position(3283, 3196), new Position(3574, 3322),
            new Position(2659, 2660), new Position(3377, 3168), new Position(2660, 3706),
            new Position(2318, 3813), new Position(3054, 3514)
    }
Holds all the impling onSpawn locations.
Definition at line 38 of file SkillRepository.java.
{
            new Position(3081, 3484), new Position(3101, 3484), new Position(3115, 3506),
            new Position(3094, 3453), new Position(3134, 3511), new Position(3180, 3422),
            new Position(3240, 3440), new Position(3287, 3351), new Position(3257, 3247),
            new Position(3221, 3213), new Position(2803, 3445), new Position(2721, 3472),
            new Position(3349, 3271), new Position(3283, 3196), new Position(3574, 3322),
            new Position(2659, 2660), new Position(3377, 3168), new Position(2660, 3706),
            new Position(2318, 3813), new Position(3054, 3514)
    };
Referenced by spawn().
IMPLINGS
final int [][] com.runehive.content.skill.SkillRepository.IMPLINGS static
Definition at line 153 of file SkillRepository.java.
{
            /**
             * Baby imps
            */
            {1635, 2612, 4318},
            {1635, 2602, 4314},
            {1635, 2610, 4338},
            {1635, 2582, 4344},
            {1635, 2578, 4344},
            {1635, 2568, 4311},
            {1635, 2583, 4295},
            {1635, 2582, 4330},
            {1635, 2600, 4303},
            {1635, 2611, 4301},
            {1635, 2618, 4329},
            /**
             * Young imps
            */
            {1636, 2591, 4332},
            {1636, 2600, 4338},
            {1636, 2595, 4345},
            {1636, 2610, 4327},
            {1636, 2617, 4314},
            {1636, 2619, 4294},
            {1636, 2599, 4294},
            {1636, 2575, 4303},
            {1636, 2570, 4299},
            /**
             * Gourment imps
            */
            {1637, 2573, 4339},
            {1637, 2567, 4328},
            {1637, 2593, 4297},
            {1637, 2618, 4305},
            {1637, 2605, 4316},
            {1637, 2596, 4333},
            /**
             * Earth imps
            */
            {1638, 2592, 4338},
            {1638, 2611, 4345},
            {1638, 2617, 4339},
            {1638, 2614, 4301},
            {1638, 2606, 4295},
            {1638, 2581, 4299},
            /**
             * Essence imps
            */
            {1639, 2602, 4328},
            {1639, 2608, 4333},
            {1639, 2609, 4296},
            {1639, 2581, 4304},
            {1639, 2570, 4318},
            /**
             * Eclectic imps
            */
            {1640, 2611, 4310},
            {1640, 2617, 4319},
            {1640, 2600, 4347},
            {1640, 2570, 4326},
            {1640, 2579, 4310},
            /**
             * Spirit imps
            */
            /**
             * Nature imps
            */
            {1641, 2581, 4310},
            {1641, 2581, 4310},
            {1641, 2603, 4333},
            {1641, 2576, 4335},
            {1641, 2588, 4345},
            /**
             * Magpie imps
            */
            {1642, 2612, 4324},
            {1642, 2602, 4323},
            {1642, 2587, 4348},
            {1642, 2564, 4320},
            {1642, 2566, 4295},
            /**
             * Ninja imps
            */
            {1643, 2570, 4347},
            {1643, 2572, 4327},
            {1643, 2578, 4318},
            {1643, 2610, 4312},
            {1643, 2594, 4341},
            /**
             * Dragon imps
            */
            {1654, 2613, 4341},
            {1654, 2585, 4337},
            {1654, 2576, 4319},
            {1654, 2576, 4294},
            {1654, 2592, 4305},
    };
Referenced by spawn().
SKILLING_ITEMS
final List<Integer> com.runehive.content.skill.SkillRepository.SKILLING_ITEMS = new ArrayList<>() static private
Definition at line 30 of file SkillRepository.java.
Referenced by declareItems(), isHerbloreItem(), and isSkillingItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/SkillRepository.java