RuneHive-Game: com.runehive.content.tittle.PlayerTitle Class Reference
com.runehive.content.tittle.PlayerTitle Class Reference
The player title class.
Public Member Functions
boolean equals (Object obj)
int getColor ()
Gets the color.
String getTitle ()
Gets the title.
int hashCode ()
Static Public Member Functions
static PlayerTitle create (String title)
Creates a player title.
static PlayerTitle create (String title, int color)
Creates a player title.
static PlayerTitle empty ()
Creates an empty player title.
Private Member Functions
PlayerTitle (String title, int color)
Constructs a new PlayerTitle.
Private Attributes
final int color
The title color.
final String title
The title string.
Static Private Attributes
static final PlayerTitle EMPTY = new PlayerTitle("", 0xC74C1C)
An empty title.
Detailed Description
The player title class.
Author
Daniel.
Definition at line 10 of file PlayerTitle.java.
Constructor & Destructor Documentation
PlayerTitle()
com.runehive.content.tittle.PlayerTitle.PlayerTitle (String title, int color) private
Constructs a new PlayerTitle.
Definition at line 22 of file PlayerTitle.java.
{
        this.title = title;
        this.color = color;
    }
References color, and title.
Referenced by create(), create(), empty(), and equals().
Member Function Documentation
create() [1/2]
PlayerTitle com.runehive.content.tittle.PlayerTitle.create (String title) static
Creates a player title.
Definition at line 33 of file PlayerTitle.java.
{
        return new PlayerTitle(title, 0xC74C1C);
    }
References PlayerTitle(), and title.
create() [2/2]
PlayerTitle com.runehive.content.tittle.PlayerTitle.create (String title, int color) static
Creates a player title.
Definition at line 28 of file PlayerTitle.java.
{
        return new PlayerTitle(title, color);
    }
References color, PlayerTitle(), and title.
Referenced by com.runehive.net.packet.in.ColorPacketListener.handlePacket().
empty()
PlayerTitle com.runehive.content.tittle.PlayerTitle.empty () static
Creates an empty player title.
Definition at line 38 of file PlayerTitle.java.
{
        return EMPTY;
    }
References EMPTY, and PlayerTitle().
Referenced by com.runehive.content.tittle.TitleManager.reset().
equals()
boolean com.runehive.content.tittle.PlayerTitle.equals (Object obj)
Definition at line 53 of file PlayerTitle.java.
{
        if (!(obj instanceof PlayerTitle))
            return false;
        final PlayerTitle other = (PlayerTitle) obj;
        return title.equals(other.getTitle()) && other.getColor() == getColor();
    }
References getColor(), getTitle(), PlayerTitle(), and title.
getColor()
int com.runehive.content.tittle.PlayerTitle.getColor ()
Gets the color.
Definition at line 48 of file PlayerTitle.java.
{
        return color;
    }
References color.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), equals(), and com.runehive.content.tittle.TitleManager.refresh().
getTitle()
String com.runehive.content.tittle.PlayerTitle.getTitle ()
Gets the title.
Definition at line 43 of file PlayerTitle.java.
{
        return title;
    }
References title.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), equals(), com.runehive.net.packet.in.ColorPacketListener.handlePacket(), and com.runehive.content.tittle.TitleManager.refresh().
hashCode()
int com.runehive.content.tittle.PlayerTitle.hashCode ()
Definition at line 61 of file PlayerTitle.java.
{
        return Objects.hash(title, color);
    }
References color, and title.
Member Data Documentation
color
final int com.runehive.content.tittle.PlayerTitle.color private
The title color.
Definition at line 19 of file PlayerTitle.java.
Referenced by create(), getColor(), hashCode(), and PlayerTitle().
EMPTY
final PlayerTitle com.runehive.content.tittle.PlayerTitle.EMPTY = new PlayerTitle("", 0xC74C1C) static private
An empty title.
Definition at line 13 of file PlayerTitle.java.
Referenced by empty().
title
final String com.runehive.content.tittle.PlayerTitle.title private
The title string.
Definition at line 16 of file PlayerTitle.java.
Referenced by create(), create(), equals(), getTitle(), hashCode(), and PlayerTitle().
The documentation for this class was generated from the following file:
java/com/runehive/content/tittle/PlayerTitle.java