RuneHive-Game: com.runehive.content.activity.impl.duelarena.DuelArenaListener Class Reference
com.runehive.content.activity.impl.duelarena.DuelArenaListener Class Reference
Public Member Functions
boolean canAttack (Mob attacker, Mob defender)
void onDamage (Mob defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (Mob attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.content.activity.ActivityListener< T extends Activity >
ActivityListener (T activity)
Constructs a new ActivityListener for a activity.
void attack (Mob attacker, Mob defender, Hit hit)
void block (Mob attacker, Mob defender, Hit hit, CombatType combatType)
boolean canOtherAttack (Mob attacker, Mob defender)
void finishIncoming (Mob attacker, Mob defender)
void finishOutgoing (Mob attacker, Mob defender)
void hit (Mob attacker, Mob defender, Hit hit)
void hitsplat (Mob attacker, Mob defender, Hit hit)
void onDeath (Mob attacker, Mob defender, Hit hit)
void onKill (Mob attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, Mob defender, Hit hit)
boolean withinDistance (Mob attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Package Functions
DuelArenaListener (DuelArenaActivity activity)
Additional Inherited Members
Protected Attributes inherited from com.runehive.content.activity.ActivityListener< T extends Activity >
final T activity
The parent activity.
Detailed Description
Definition at line 11 of file DuelArenaListener.java.
Constructor & Destructor Documentation
DuelArenaListener()
com.runehive.content.activity.impl.duelarena.DuelArenaListener.DuelArenaListener (DuelArenaActivity activity) package
Definition at line 13 of file DuelArenaListener.java.
{
        super(activity);
    }
References com.runehive.content.activity.ActivityListener< T extends Activity >.activity.
Member Function Documentation
canAttack()
boolean com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack (Mob attacker, Mob defender)
Reimplemented from com.runehive.content.activity.ActivityListener< T extends Activity >.
Definition at line 41 of file DuelArenaListener.java.
{
        Player player = activity.player;
        Player opponent = activity.opponent;
        if (player == null || opponent == null || !attacker.isPlayer() || !defender.isPlayer()) {
            return false;
        }
        if (!attacker.equals(player) && !attacker.equals(opponent)) {
            attacker.getPlayer().send(new SendMessage("You are not in this duel."));
            return false;
        }
        if (!defender.equals(player) && !defender.equals(opponent)) {
            attacker.getPlayer().send(new SendMessage(defender.getName() + " is not your opponent!"));
            return false;
        }
        if (!activity.started) {
            attacker.getPlayer().send(new SendMessage("The duel hasn't started yet!"));
            return false;
        }
        if (activity.rules.contains(DuelRule.ONLY_FUN_WEAPONS) && !DuelUtils.hasFunWeapon(attacker.getPlayer(), attacker.getPlayer().equipment.getWeapon())) {
            attacker.getPlayer().send(new SendMessage("You can only use fun weapons!"));
            return false;
        }
        if (activity.rules.contains(DuelRule.ONLY_WHIP_DDS)) {
            if (attacker.getPlayer().equipment.hasWeapon()) {
                Item weapon = attacker.getPlayer().equipment.getWeapon();
                String name = weapon.getName().toLowerCase();
                if (!name.contains("dragon dagger") && !name.contains("abyssal whip") && !name.contains("abyssal tentacle")) {
                    attacker.getPlayer().send(new SendMessage("You can only use a whip or dragon dagger!"));
                    return false;
                }
            }
        }
        CombatType combatType = attacker.getPlayer().getStrategy().getCombatType();
        if (combatType == CombatType.MELEE && activity.rules.contains(DuelRule.NO_MELEE)) {
            attacker.getPlayer().send(new SendMessage("You cannot use melee in the duel arena."));
            return false;
        }
        if (combatType == CombatType.RANGED && activity.rules.contains(DuelRule.NO_RANGED)) {
            attacker.getPlayer().send(new SendMessage("You cannot use ranged in the duel arena."));
            return false;
        }
        if (combatType == CombatType.MAGIC && activity.rules.contains(DuelRule.NO_MAGIC)) {
            attacker.getPlayer().send(new SendMessage("You cannot use magic in the duel arena."));
            return false;
        }
        return super.canAttack(attacker, defender);
    }
References com.runehive.content.activity.ActivityListener< T extends Activity >.activity, com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.Entity.getName(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.player.Player.getStrategy(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.content.activity.impl.duelarena.DuelUtils.hasFunWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.combat.CombatType.MAGIC, com.runehive.game.world.entity.combat.CombatType.MELEE, com.runehive.content.activity.impl.duelarena.DuelRule.NO_MAGIC, com.runehive.content.activity.impl.duelarena.DuelRule.NO_MELEE, com.runehive.content.activity.impl.duelarena.DuelRule.NO_RANGED, com.runehive.content.activity.impl.duelarena.DuelRule.ONLY_FUN_WEAPONS, com.runehive.content.activity.impl.duelarena.DuelRule.ONLY_WHIP_DDS, com.runehive.game.world.entity.combat.CombatType.RANGED, and com.runehive.game.world.entity.mob.player.Player.send().
onDamage()
void com.runehive.content.activity.impl.duelarena.DuelArenaListener.onDamage (Mob defender, Hit hit)
Reimplemented from com.runehive.content.activity.ActivityListener< T extends Activity >.
Definition at line 28 of file DuelArenaListener.java.
{
        if (activity.hasLoser) {
            hit.setDamage(0);
        }
    }
References com.runehive.content.activity.ActivityListener< T extends Activity >.activity, and com.runehive.content.activity.ActivityListener< T extends Activity >.hit().
preKill()
void com.runehive.content.activity.impl.duelarena.DuelArenaListener.preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Reimplemented from com.runehive.content.activity.ActivityListener< T extends Activity >.
Definition at line 35 of file DuelArenaListener.java.
{
        activity.hasLoser = true;
        attacker.damageImmunity.reset();
    }
References com.runehive.game.world.entity.mob.Mob.damageImmunity, com.runehive.content.activity.ActivityListener< T extends Activity >.hit(), and com.runehive.util.Stopwatch.reset().
start()
void com.runehive.content.activity.impl.duelarena.DuelArenaListener.start (Mob attacker, Mob defender, Hit[] hits)
Reimplemented from com.runehive.content.activity.ActivityListener< T extends Activity >.
Definition at line 18 of file DuelArenaListener.java.
{
        System.out.println(defender);
        if (activity.hasLoser) {
            return;
        }
        super.start(attacker, defender, hits);
    }
References com.runehive.content.activity.ActivityListener< T extends Activity >.activity.
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/duelarena/DuelArenaListener.java