RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy Class Reference
com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy Class Reference
Public Member Functions
boolean canAttack (Npc attacker, Mob defender)
Animation getAttackAnimation (Npc attacker, Mob defender)
int getAttackDelay (Npc attacker, Mob defender, FightType fightType)
int getAttackDistance (Npc attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
CombatType getCombatType ()
CombatHit[] getHits (Npc attacker, Mob defender)
NpcMagicStrategy (CombatProjectile combatProjectile)
void sendAnimation (Npc attacker, Mob defender)
int sendProjectile (Npc attacker, Hit[] hits, Mob from, Mob to, @Nullable Runnable onProjectileLand)
void start (Npc attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Protected Attributes
final CombatProjectile combatProjectile
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Static Public Attributes inherited from com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >
static final Graphic SPLASH = new Graphic(85, 0, Graphic.HIGH_HEIGHT)
The spell splash graphic.
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >
static void addCombatExperience (Player player, double base, Hit... hits)
Detailed Description
Definition at line 26 of file NpcMagicStrategy.java.
Constructor & Destructor Documentation
NpcMagicStrategy()
com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.NpcMagicStrategy (CombatProjectile combatProjectile)
Definition at line 30 of file NpcMagicStrategy.java.
{
        this.combatProjectile = combatProjectile;
    }
References combatProjectile.
Member Function Documentation
canAttack()
boolean com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.canAttack (Npc attacker, Mob defender)
Reimplemented in com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web.
Definition at line 113 of file NpcMagicStrategy.java.
{
        return true;
    }
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getAttackAnimation (Npc attacker, Mob defender)
Reimplemented in com.runehive.content.activity.infernomobs.JalAk.Mage, com.runehive.content.activity.infernomobs.JalTokJad.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SpritualMage.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.InfernalMage.MageAttack, com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Shockwave, com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.RangedAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web, com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.DragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.PinkDragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomDragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Magic, com.runehive.game.world.entity.combat.strategy.npc.impl.BrutalDragonfireStrategy, and com.runehive.game.world.entity.combat.strategy.npc.impl.DragonfireStrategy.
Definition at line 108 of file NpcMagicStrategy.java.
{
        return new Animation(attacker.definition.getAttackAnimation(), UpdatePriority.HIGH);
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackAnimation(), and com.runehive.game.UpdatePriority.HIGH.
Referenced by sendAnimation().
getAttackDelay()
int com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getAttackDelay (Npc attacker, Mob defender, FightType fightType)
Reimplemented in com.runehive.content.activity.infernomobs.JalTokJad.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothPrime, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.IceSpecial, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform, com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial, and com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.
Definition at line 92 of file NpcMagicStrategy.java.
{
        int delay = attacker.definition.getAttackDelay();
        if (attacker.getPosition().getDistance(defender.getPosition()) > 4) {
            return 1 + delay;
        }
        return delay;
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackDelay(), com.runehive.game.world.position.Position.getDistance(), and com.runehive.game.world.entity.Entity.getPosition().
getAttackDistance()
int com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getAttackDistance (Npc attacker, FightType fightType)
Reimplemented in com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.Dragonfire, com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.Spinolyp.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Dragonfire, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Freeze, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Poison, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Shock, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.DragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.PinkDragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomDragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.impl.BrutalDragonfireStrategy, and com.runehive.game.world.entity.combat.strategy.npc.impl.DragonfireStrategy.
Definition at line 103 of file NpcMagicStrategy.java.
{
        return 10;
    }
getCombatProjectile()
CombatProjectile com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getCombatProjectile ()
Reimplemented from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
Definition at line 35 of file NpcMagicStrategy.java.
{
        return combatProjectile;
    }
References combatProjectile.
getCombatType()
CombatType com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getCombatType ()
Reimplemented from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
Definition at line 118 of file NpcMagicStrategy.java.
{
        return CombatType.MAGIC;
    }
References com.runehive.game.world.entity.combat.CombatType.MAGIC.
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getHits (Npc attacker, Mob defender)
Reimplemented in com.runehive.content.activity.infernomobs.AkMej.Mage, com.runehive.content.activity.infernomobs.JalAk.Mage, com.runehive.content.activity.infernomobs.JalTokJad.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Ahrim.FireBlast, com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.DarkBeast.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.Dragonfire, com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.godwar.ArmadylSpritualMage.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.godwar.BandosSpritualMage.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SaradominPriest.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.godwar.SpritualMage.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Gowler.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Kraken.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.KrilTsutsaroth.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Tentacle.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree, com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar, com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Shockwave, com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothPrime, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.Spinolyp.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Hydra.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Dragonfire, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Freeze, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Poison, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.Shock, com.runehive.game.world.entity.combat.strategy.npc.boss.kril.Balfrug, com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.TeleGrab, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.TeleGrab, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.FrozenSpecial, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.IceSpecial, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.MutantTarn.RangedAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain, com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.TeleGrab, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform, com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain, com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.Web, com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.DragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.PinkDragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomDragonfireAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial, com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.impl.BrutalDragonfireStrategy, and com.runehive.game.world.entity.combat.strategy.npc.impl.DragonfireStrategy.
Definition at line 87 of file NpcMagicStrategy.java.
{
        return new CombatHit[]{nextMagicHit(attacker, defender, combatProjectile)};
    }
References combatProjectile, and com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit().
sendAnimation()
void com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendAnimation (Npc attacker, Mob defender)
Definition at line 45 of file NpcMagicStrategy.java.
{
        Animation animation = getAttackAnimation(attacker, defender);
        if (animation.isReset()) {
            Optional<Animation> projAnim = combatProjectile.getAnimation();
            if (projAnim.isPresent()) animation = projAnim.get();
        }
        attacker.animate(animation, true);
        combatProjectile.getStart().ifPresent(attacker::graphic);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), combatProjectile, getAttackAnimation(), and com.runehive.game.Animation.isReset().
Referenced by start().
sendProjectile()
int com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile (Npc attacker, Hit[] hits, Mob from, Mob to, @Nullable Runnable onProjectileLand)
Definition at line 56 of file NpcMagicStrategy.java.
{
        final int duration = combatProjectile.sendProjectile(from, to);
        final Graphic endGraphic = getEndGraphic(combatProjectile, missed(hits), SPLASH, duration);
        if (endGraphic != null) to.graphic(endGraphic);
        for (Hit hit : hits) {
            Predicate<CombatImpact> filter = effect -> effect.canAffect(attacker, to, hit);
            Consumer<CombatImpact> execute = effect -> effect.impact(attacker, to, hit, null);
            combatProjectile.getEffect().filter(filter).ifPresent(execute);
            if (attacker.definition.isPoisonous()) {
                if (CombatVenomEffect.isVenomous(attacker) && RandomUtils.success(0.25)) {
                    to.venom();
                } else {
                    CombatPoisonEffect.getPoisonType(attacker.id).ifPresent(to::poison);
                }
            }
        }
        if (onProjectileLand != null) {
            final int delay = GameEngine.clientTicksToServerTicks(duration);
            WorldTask.schedule(delay, onProjectileLand);
        }
        return duration;
    }
References com.runehive.game.engine.GameEngine.clientTicksToServerTicks(), combatProjectile, com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.hit(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isPoisonous(), com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.isVenomous(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.missed(), com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >.SPLASH, com.runehive.util.RandomUtils.success(), and com.runehive.game.world.entity.mob.Mob.venom().
Referenced by start().
start()
void com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.start (Npc attacker, Mob defender, Hit[] hits)
Reimplemented in com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.DarkBeast.MagicAttack, com.runehive.game.world.entity.combat.attack.listener.npc.Gowler.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar, com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.LavaAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.RainAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.MagicAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.MinionsAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.TeleGrab, com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain, com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.TeleGrab, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BarrageAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.PrayerAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.Transform, com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic, com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack, and com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.
Definition at line 40 of file NpcMagicStrategy.java.
{
        sendAnimation(attacker, defender);
        sendProjectile(attacker, hits, attacker, defender, null);
    }
References sendAnimation(), and sendProjectile().
Member Data Documentation
combatProjectile
final CombatProjectile com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.combatProjectile protected
Definition at line 28 of file NpcMagicStrategy.java.
Referenced by getCombatProjectile(), com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Gowler.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.MagicAttack.getHits(), com.runehive.game.world.entity.combat.attack.listener.npc.Kraken.MagicAttack.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.getHits(), getHits(), NpcMagicStrategy(), sendAnimation(), sendProjectile(), com.runehive.game.world.entity.combat.attack.listener.npc.DarkBeast.MagicAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.RainAttack.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.LightingRain.start(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.start().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/NpcMagicStrategy.java