RuneHive-Game: com.runehive.content.skill.impl.HarvestingSkillAction Class Reference
com.runehive.content.skill.impl.HarvestingSkillAction Class Reference abstract
Holds functionality for skills such as woodcutting and mining.
Classes
enum DoubleReward
The double onReward types.
Public Member Functions
final boolean canRun ()
Determines if the task can be ran.
DoubleReward doubleReward ()
If mob will get a double onReward.
WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
HarvestingSkillAction (Mob mob, Optional< Position > position, boolean instant)
Creates a new Action randomevent.
HarvestingSkillAction (Mob mob, Optional< Position > position, int delay, boolean instant)
Creates a new Action randomevent.
abstract Item[] harvestItems ()
The items to be harvested upon a successful harvest.
void onExecute ()
The method which is called on intervals of the specified #delay;.
void onHarvest (Item[] items, boolean success)
The method executed upon harvest of the items.
boolean prioritized ()
Determines if this action is prioritized.
abstract Optional< Item[]> removeItems ()
The items to be removed upon a successful harvest.
abstract double successFactor ()
The success factor for the harvest.
Public Member Functions inherited from com.runehive.content.skill.SkillAction
abstract Optional< SkillAnimation > animation ()
The skill animation to execute.
abstract boolean canInit ()
Determines if this action can be initialized.
abstract double experience ()
The experience given from this action.
boolean ignore ()
Determines if future skill actions from the same type should be ignored.
abstract void init ()
Any functionality that should be handled when this action is submitted.
abstract int skill ()
The skill we should hand to experience to.
SkillAction (Mob mob, Optional< Position > position, boolean instant)
Creates a new Action randomevent.
SkillAction (Mob mob, Optional< Position > position, int delay, boolean instant)
Creates a new Action randomevent.
final void start ()
Attempts to start the skill.
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
abstract String getName ()
Gets the name of this action.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Private Attributes
final RandomGen random = new RandomGen()
The random generator instance that will generate random numbers.
Static Private Attributes
static final int SUCCESS_FACTOR = 10
The factor boost that determines the success rate for harvesting based on skill level.
Additional Inherited Members
Protected Member Functions inherited from com.runehive.content.skill.SkillAction
final void execute ()
A function representing the unit of work that will be carried out.
final void onSchedule ()
A function executed on registration.
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
void onCancel (boolean logout)
A function executed on cancellation.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
Holds functionality for skills such as woodcutting and mining.
Author
Stand Up
Since
19-12-2016.
Definition at line 23 of file HarvestingSkillAction.java.
Constructor & Destructor Documentation
HarvestingSkillAction() [1/2]
com.runehive.content.skill.impl.HarvestingSkillAction.HarvestingSkillAction (Mob mob, Optional< Position > position, boolean instant)
Creates a new Action randomevent.
Parameters
mob mob.
position position.
instant instant.
Definition at line 52 of file HarvestingSkillAction.java.
{
        super(mob, position, instant);
    }
References com.runehive.game.task.Task.instant, com.runehive.game.action.Action< T extends Mob >.mob, and com.runehive.content.skill.SkillAction.position.
HarvestingSkillAction() [2/2]
com.runehive.content.skill.impl.HarvestingSkillAction.HarvestingSkillAction (Mob mob, Optional< Position > position, int delay, boolean instant)
Creates a new Action randomevent.
Parameters
mob mob.
position position.
delay delay.
instant instant.
Definition at line 64 of file HarvestingSkillAction.java.
{
        super(mob, position, delay, instant);
    }
References com.runehive.game.task.Task.delay, com.runehive.game.task.Task.instant, com.runehive.game.action.Action< T extends Mob >.mob, and com.runehive.content.skill.SkillAction.position.
Member Function Documentation
canRun()
final boolean com.runehive.content.skill.impl.HarvestingSkillAction.canRun ()
Determines if the task can be ran.
Reimplemented from com.runehive.game.task.Task.
Definition at line 110 of file HarvestingSkillAction.java.
{
        if (getMob().isPlayer()) {
            Player player = getMob().getPlayer();
            if (getMob().isPlayer() && getMob().getPlayer().inventory.remaining() < 1) {
                getMob().getPlayer().send(new SendMessage("You do not have any space left in your inventory."));
                return false;
            }
            if (removeItems().isPresent()) {
                Item[] remove = removeItems().get();
                if (!player.inventory.containsAll(remove)) {
                    for (Item item : remove) {
                        if (!player.inventory.contains(item)) {
                            player.send(new SendMessage("You don't have " + StringUtils.appendIndefiniteArticle(item.getName() + ".")));
                            break;
                        }
                    }
                    return false;
                }
            }
        }
        return true;
    }
References com.runehive.util.StringUtils.appendIndefiniteArticle(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.action.Action< T extends Mob >.getMob(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.player.Player.inventory, removeItems(), and com.runehive.game.world.entity.mob.player.Player.send().
doubleReward()
DoubleReward com.runehive.content.skill.impl.HarvestingSkillAction.doubleReward ()
If mob will get a double onReward.
Returns
If mob will get a double onReward.
Definition at line 83 of file HarvestingSkillAction.java.
{
        return DoubleReward.NONE;
    }
References com.runehive.content.skill.impl.HarvestingSkillAction.DoubleReward.NONE.
Referenced by onExecute().
getWalkablePolicy()
WalkablePolicy com.runehive.content.skill.impl.HarvestingSkillAction.getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 183 of file HarvestingSkillAction.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
harvestItems()
abstract Item[] com.runehive.content.skill.impl.HarvestingSkillAction.harvestItems () abstract
The items to be harvested upon a successful harvest.
Returns
the items to be harvested.
Referenced by onExecute().
onExecute()
void com.runehive.content.skill.impl.HarvestingSkillAction.onExecute ()
The method which is called on intervals of the specified #delay;.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 135 of file HarvestingSkillAction.java.
{
        Preconditions.checkState(SUCCESS_FACTOR >= 0 && SUCCESS_FACTOR <= 99, "Invalid success factor for harvesting!");
        int factor = (getMob().skills.getSkills()[skill()].getLevel() / SUCCESS_FACTOR);
        double boost = (factor * 0.01);
        if (random.success(successFactor() + boost)) {
            Optional<Item[]> removeItems = removeItems();
            Item[] harvestItems = harvestItems();
            if (getMob().isPlayer()) {
                removeItems.ifPresent(getMob().getPlayer().inventory::removeAll);
                if (harvestItems != null)
                    getMob().getPlayer().inventory.addAll(harvestItems);
                if (experience() != -1)
                    getMob().skills.addExperience(skill(), experience());
                onHarvest(harvestItems, true);
                if (doubleReward() == DoubleReward.ITEM) {
                    getMob().getPlayer().inventory.addAll(harvestItems);
                } else if (doubleReward() == DoubleReward.EXPERIENCE) {
                    getMob().skills.addExperience(skill(), experience());
                } else if (doubleReward() == DoubleReward.ALL) {
                    getMob().getPlayer().inventory.addAll(harvestItems);
                    getMob().skills.addExperience(skill(), experience());
                }
            }
        } else {
            onHarvest(null, false);
        }
    }
References com.runehive.content.skill.impl.HarvestingSkillAction.DoubleReward.ALL, doubleReward(), com.runehive.content.skill.impl.HarvestingSkillAction.DoubleReward.EXPERIENCE, com.runehive.content.skill.SkillAction.experience(), com.runehive.game.action.Action< T extends Mob >.getMob(), harvestItems(), com.runehive.content.skill.impl.HarvestingSkillAction.DoubleReward.ITEM, onHarvest(), random, removeItems(), com.runehive.content.skill.SkillAction.skill(), SUCCESS_FACTOR, and successFactor().
onHarvest()
void com.runehive.content.skill.impl.HarvestingSkillAction.onHarvest (Item[] items, boolean success)
The method executed upon harvest of the items.
Parameters
items the items being harvested.
success determines if the harvest was successful or not.
Definition at line 74 of file HarvestingSkillAction.java.
{
    }
Referenced by onExecute().
prioritized()
boolean com.runehive.content.skill.impl.HarvestingSkillAction.prioritized ()
Determines if this action is prioritized.
When making an action prioritized, the next action will be ignored if not queued.
Returns
true if this action is prioritized, false otherwise.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 173 of file HarvestingSkillAction.java.
{
        return false;
    }
removeItems()
abstract Optional< Item[]> com.runehive.content.skill.impl.HarvestingSkillAction.removeItems () abstract
The items to be removed upon a successful harvest.
Returns
the items to be removed.
Referenced by canRun(), and onExecute().
successFactor()
abstract double com.runehive.content.skill.impl.HarvestingSkillAction.successFactor () abstract
The success factor for the harvest.
The higher the number means the more frequently harvest will be obtained.
Returns
the success factor.
Referenced by onExecute().
Member Data Documentation
random
final RandomGen com.runehive.content.skill.impl.HarvestingSkillAction.random = new RandomGen() private
The random generator instance that will generate random numbers.
Definition at line 43 of file HarvestingSkillAction.java.
Referenced by onExecute().
SUCCESS_FACTOR
final int com.runehive.content.skill.impl.HarvestingSkillAction.SUCCESS_FACTOR = 10 static private
The factor boost that determines the success rate for harvesting based on skill level.
The higher the number the less frequently harvest will be obtained. A value higher than 99 or lower than 0 will throw an IllegalStateException.
Definition at line 38 of file HarvestingSkillAction.java.
Referenced by onExecute().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/HarvestingSkillAction.java