RuneHive-Game: com.runehive.util.GameSaver Class Reference
com.runehive.util.GameSaver Class Reference
Created by Daniel on 2017-11-05.
Static Public Member Functions
static void load ()
static void save ()
static JsonObject toJson ()
Static Public Attributes
static long ITEMS_SOLD = 0
static int MAX_PLAYERS
static long PERSONAL_ITEM_WORTH = 0
Detailed Description
Created by Daniel on 2017-11-05.
Definition at line 20 of file GameSaver.java.
Member Function Documentation
load()
void com.runehive.util.GameSaver.load () static
Definition at line 64 of file GameSaver.java.
{
        new GsonParser("content/game/world") {
            @Override
            protected void parse(JsonObject object) {
                MAX_PLAYERS = object.get("max-players").getAsInt();
                /* Well of Goodwill */
                WellOfGoodwill.activeTime = object.get("wog-active-time").getAsInt();
                WellOfGoodwill.CONTRIBUTION = object.get("wog-contribution").getAsInt();
                if (object.has("wog-last-contributor")) {
                    WellOfGoodwill.lastContributor = object.get("wog-last-contributor").getAsString();
                }
                final JsonArray contributors = object.get("contributors").getAsJsonArray();
                for (JsonElement element : contributors) {
                    final JsonObject contributorObj = (JsonObject) element;
                    final String name = contributorObj.get("name").getAsString();
                    final Optional<PlayerRight> rank = PlayerRight.lookup(contributorObj.get("rank").getAsInt());
                    final int amount = contributorObj.get("amount").getAsInt();
                    WellOfGoodwill.add(name, rank.orElse(PlayerRight.PLAYER), amount);
                }
                 /* Personal Store */
                PERSONAL_ITEM_WORTH = object.get("personal-store-worth").getAsLong();
                ITEMS_SOLD = object.get("personal-store-items-sold").getAsLong();
                BotUtility.BOOT_LOOT = GsonUtils.JSON_PRETTY_ALLOW_NULL.get().fromJson(object.get("pk-bot-loot"), new TypeToken<HashMap<Integer, MutableNumber>>() {  }.getType());
            }
        }.run();
    }
References com.runehive.content.WellOfGoodwill.activeTime, com.runehive.content.WellOfGoodwill.add(), com.runehive.content.bot.BotUtility.BOOT_LOOT, com.runehive.content.WellOfGoodwill.CONTRIBUTION, ITEMS_SOLD, com.runehive.util.GsonUtils.JSON_PRETTY_ALLOW_NULL, com.runehive.content.WellOfGoodwill.lastContributor, com.runehive.game.world.entity.mob.player.PlayerRight.lookup(), MAX_PLAYERS, PERSONAL_ITEM_WORTH, and com.runehive.game.world.entity.mob.player.PlayerRight.PLAYER.
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
save()
void com.runehive.util.GameSaver.save () static
Definition at line 26 of file GameSaver.java.
{
        Thread.startVirtualThread(() -> {
            try (FileWriter fw = new FileWriter("./data/content/game/world.json")) {
                fw.write(GsonUtils.JSON_PRETTY_NO_NULLS.get().toJson(toJson()));
            } catch (final Exception e) {
                e.printStackTrace();
            }
        });
    }
References com.runehive.util.GsonUtils.JSON_PRETTY_NO_NULLS, and toJson().
Referenced by com.runehive.game.world.World.save().
toJson()
JsonObject com.runehive.util.GameSaver.toJson () static
Definition at line 36 of file GameSaver.java.
{
        JsonObject object = new JsonObject();
        object.addProperty("max-players", MAX_PLAYERS);
        /* Well of Goodwill */
        object.addProperty("wog-active-time", WellOfGoodwill.activeTime);
        object.addProperty("wog-contribution", WellOfGoodwill.CONTRIBUTION);
        object.addProperty("wog-last-contributor", WellOfGoodwill.lastContributor);
        JsonArray wogArray = new JsonArray();
        for (Contributor contributor : WellOfGoodwill.contributors) {
            JsonObject contributorObj = new JsonObject();
            contributorObj.addProperty("name", contributor.name);
            contributorObj.addProperty("rank", contributor.rank.getCrown());
            contributorObj.addProperty("amount", contributor.contribution);
            wogArray.add(contributorObj);
        }
        object.add("contributors", wogArray);
        /* Personal Store */
        object.addProperty("personal-store-worth", PERSONAL_ITEM_WORTH);
        object.addProperty("personal-store-items-sold", ITEMS_SOLD);
        object.add("pk-bot-loot", GsonUtils.JSON_PRETTY_ALLOW_NULL.get().toJsonTree(BotUtility.BOOT_LOOT));
        return object;
    }
References com.runehive.content.WellOfGoodwill.activeTime, com.runehive.content.bot.BotUtility.BOOT_LOOT, com.runehive.content.WellOfGoodwill.CONTRIBUTION, com.runehive.content.WellOfGoodwill.Contributor.contribution, com.runehive.content.WellOfGoodwill.contributors, com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), ITEMS_SOLD, com.runehive.util.GsonUtils.JSON_PRETTY_ALLOW_NULL, com.runehive.content.WellOfGoodwill.lastContributor, MAX_PLAYERS, com.runehive.content.WellOfGoodwill.Contributor.name, PERSONAL_ITEM_WORTH, and com.runehive.content.WellOfGoodwill.Contributor.rank.
Referenced by save().
Member Data Documentation
ITEMS_SOLD
long com.runehive.util.GameSaver.ITEMS_SOLD = 0 static
Definition at line 24 of file GameSaver.java.
Referenced by load(), com.runehive.content.store.impl.PersonalStore.onPurchase(), com.runehive.content.store.impl.PersonalStore.openMenu(), and toJson().
MAX_PLAYERS
int com.runehive.util.GameSaver.MAX_PLAYERS static
Definition at line 22 of file GameSaver.java.
Referenced by load(), com.runehive.game.world.entity.mob.player.Player.sendInitialPackets(), and toJson().
PERSONAL_ITEM_WORTH
long com.runehive.util.GameSaver.PERSONAL_ITEM_WORTH = 0 static
Definition at line 23 of file GameSaver.java.
Referenced by load(), com.runehive.content.store.impl.PersonalStore.onPurchase(), com.runehive.content.store.impl.PersonalStore.openMenu(), and toJson().
The documentation for this class was generated from the following file:
java/com/runehive/util/GameSaver.java