RuneHive-Game: com.runehive.game.world.items.containers.equipment.Equipment Class Reference
com.runehive.game.world.items.containers.equipment.Equipment Class Reference
The container that manages the equipment for a player.
Classes
class EquipmentListener
An ItemContainerAdapter implementation that listens for changes to equipment.
Public Member Functions
boolean add (Item item, int preferredIndex, boolean refresh)
Adds an item to the equipment container.
void clear ()
Removes all of the items from this container.
boolean contains (int[] bowsWithNoArrowsRequired)
boolean equip (int inventoryIndex)
boolean equip (Item item)
Equipment (Player player)
Creates a new Equipment.
Item getAmuletSlot ()
Item getCape ()
Item[] getEquipment ()
Item getShield ()
Item getWeapon ()
boolean hasAmmo ()
boolean hasAmulet ()
boolean hasArmadyl ()
boolean hasBandos ()
boolean hasCape ()
boolean hasChest ()
boolean hasFeet ()
boolean hasHands ()
boolean hasHead ()
boolean hasLegs ()
boolean hasRing ()
boolean hasRow ()
boolean hasSaradomin ()
boolean hasShayzien ()
boolean hasShield ()
boolean hasWeapon ()
boolean hasZamorak ()
void login ()
Handles refreshing all the equipment items.
void manualWear (Item item)
Manually wears an item (does not have any restrictions).
void manualWearAll (Item[] items)
Manually wears multiple items (does not have any restrictions).
void openInterface ()
Handles opening the equipment screen itemcontainer.
void refresh ()
Forces a refresh of Equipment items to the
EQUIPMENT_DISPLAY_ID widget.
void refresh (Player player, int widget)
Forces a refresh of Equipment items to the
EQUIPMENT_DISPLAY_ID widget.
boolean remove (Item item, int preferredIndex, boolean refresh)
Removes an item from the equipment container.
void unEquip (Item item)
boolean unequip (int equipmentIndex)
Unequips an Item from the underlying player's Equipment.
void updateAnimation ()
Updates the weapon animation.
void updateRangedEquipment ()
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainer
boolean add (int id, int amount)
Attempts to deposit item into this container.
boolean add (Item item)
Attempts to deposit item into this container.
boolean add (Item item, boolean refresh, boolean stack)
boolean add (Item item, int preferredIndex, boolean refresh, boolean stack)
Attempts to deposit item into this container, preferably at preferredIndex.
boolean add (Item item, int slot)
Attempts to deposit item into this container.
boolean addAll (Collection<? extends Item > items)
Attempts to deposit items in bulk into this container.
boolean addAll (Item... items)
Attempts to deposit items in bulk into this container.
boolean addAll (ItemContainer items)
Attempts to deposit items in bulk into this container.
final boolean addListener (ItemContainerListener listener)
Adds an ItemContainerListener to this container.
boolean allowZero ()
final int capacity ()
final void clear (boolean refresh)
Removes all of the items from this container.
final int computeAmountForId (int id)
Computes the total quantity of the Items in this container with id.
final int computeFreeIndex ()
Computes the next free (null) index in this container.
final Optional< Integer > computeIdForIndex (int index)
Computes the identifier of the Item on index.
final int computeIndexCount (Item... forItems)
Computes the amount of indexes required to hold items in this container.
final int computeIndexForId (int id)
Computes the first index found that id is in.
long containerValue (PriceType type)
Gets the total worth of the container using the item's values.
boolean contains (int id)
Determines if this container contains id.
final boolean contains (int id, int amount)
final boolean contains (Item item)
final boolean containsAll (Collection< Item > items)
final boolean containsAll (int... identifiers)
Determines if this container contains all identifiers.
final boolean containsAll (Item... items)
final boolean containsAny (Collection< Item > items)
final boolean containsAny (int... identifiers)
Determines if this container contains any identifiers.
final boolean containsAny (Item... items)
final ItemContainer copy ()
Creates a copy of the underlying item container.
final void fireBulkItemsUpdatedEvent ()
Fires the ItemContainerListener.bulkItemsUpdated(ItemContainer) event.
final void fireCapacityExceededEvent ()
Fires the ItemContainerListener.capacityExceeded(ItemContainer) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh)
Fires the ItemContainerListener.itemUpdated(ItemContainer, int) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh, boolean login)
final void forEach (Consumer<? super Item > action)
Iterates through all of the Items within this container and performs action on them, skipping empty indexes (null values) as they are encountered.
final Item get (int index)
Gets the Item located on index.
int getFreeSlots ()
final int getId (int index)
Gets the item id located on index.
Item[] getItems ()
int getSlotById (int id)
Gets a slot by id.
double getWeight ()
Gets the weight of the container.
final boolean hasCapacityAfter (Item[] add, Item... remove)
Creates a copy of the underlying container and removes the items specified from it and after tries to deposit the specified items to it.
final boolean hasCapacityFor (Item... item)
Determines if this container has the capacity for item.
final void ifPresent (int index, Consumer< Item > action)
Consumes an action if the index is a valid item index in this container.
final boolean indexFree (int index)
Returns true if index is not occupied (null).
final boolean indexOccupied (int index)
Returns true if index is occupied (non-null).
final void insert (int oldIndex, int newIndex, boolean refresh)
final boolean isEmpty ()
final boolean isFull ()
ItemContainer (int capacity, StackPolicy policy)
Creates a new ItemContainer.
ItemContainer (int capacity, StackPolicy policy, Item[] items)
Creates a new ItemContainer.
final Iterator< Item > iterator ()
void onRefresh ()
Any functionality that should occur when refreshed.
final StackPolicy policy ()
final int remaining ()
boolean remove (int id)
boolean remove (int id, int amount)
boolean remove (Item item)
Attempts to withdraw item from this container.
boolean remove (Item item, int preferredIndex)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean remove (Item item, int preferredIndex, boolean refresh, boolean removeAll)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean removeAll (Collection<? extends Item > items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (Item... items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (ItemContainer items)
Attempts to withdraw items in bulk from this container.
final boolean removeListener (ItemContainerListener listener)
Removes an ItemContainerListener from this container.
final boolean replace (int oldId, int newId, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (int oldId, int newId, int index, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (Item first, Item second, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replaceAll (int oldId, int newId)
Replaces all occurrences of Items having the identifier
oldId with newId.
final Optional< Item > retrieve (int index)
Retrieves the item located on index.
Optional< Item > search (int id)
Searches and returns the first item found with id.
Optional< Item > search (Item item)
Searches and returns the first item found with id and
amount.
void set (int index, Item item, boolean refresh)
Sets the index to item.
final void set (Item[] toSet)
void setFiringEvents (boolean firingEvents)
Sets the value for firingEvents.
final void setItems (Item[] items)
final void setItems (Item[] items, boolean copy)
Sets the container of items to items.
void shift ()
Percolates the null indices to the end of the stack.
final int size ()
final Spliterator< Item > spliterator ()
final Stream< Item > stream ()
final void swap (boolean insert, int oldIndex, int newIndex, boolean refresh)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex, boolean refresh)
final Item[] toArray ()
Returns a shallow copy of the backing array.
final Item[] toNonNullArray ()
final void transfer (int firstIndex, int secondIndex, ItemContainer other, boolean refresh)
Static Public Member Functions
static boolean hasAccumulator (Player player)
static boolean hasAssembler (Player player)
static boolean hasAttractor (Player player)
static boolean isWearingDFS (Player player)
Static Public Attributes
static final int AMULET_SLOT = 2
static final int[][] ANGLER_PIECES
Fishing.
static final int ARROWS_SLOT = 13
static final int CAPE_SLOT = 1
static final int CHEST_SLOT = 4
static final int CRUSH_DEFENCE = 7
static final int CRUSH_OFFENSE = 2
static final int FEET_SLOT = 10
static final int HANDS_SLOT = 9
static final int HEAD_SLOT = 0
Equipment slot constants.
static final int HELM_SLOT = 0
static final int LEGS_SLOT = 7
static final int[][] LUMBERJACK_PIECES
static final int MAGIC_DEFENSE = 8
static final int MAGIC_OFFENSE = 3
static final int MAGIC_STRENGTH = 12
static final int[] PICKAXES = {1265, 1267, 1269, 1273, 1271, 1275, 13243, 20014, 11920, 12797}
static final int PRAYER_BONUS = 13
static final int[][] PROSPECTOR_PIECES
Mining.
static final int RANGED_DEFENSE = 9
static final int RANGED_OFFENSE = 4
static final int RANGED_STRENGTH = 11
static final int RING_SLOT = 12
static final int[] SHAYZIEN_ITEMS = {13377, 13378, 13379, 13380, 13381}
static final int[][] SHAYZIEN_PIECES
static final int SHIELD_SLOT = 5
static final int SIZE = 14
The size of all equipment instances.
static final double SKILLING_SETS_EXPERIENCE_BOOST_PER_PIECE = 1.02
static final int SLASH_DEFENSE = 6
static final int SLASH_OFFENSE = 1
static final int STAB_DEFENSE = 5
static final int STAB_OFFENSE = 0
Equipment bonus constants.
static final int STRENGTH_BONUS = 10
static final int WEAPON_SLOT = 3
Private Member Functions
void addBonus (Item item)
void appearanceForIndex (int equipmentIndex)
Flags the APPEARANCE update block, only if the equipment piece on equipmentIndex requires an appearance update.
boolean isItem (int slot, int itemId)
void onEquip (Item item)
void onRemove (Item item)
void removeBonus (Item item)
boolean unequip (int equipmentIndex, int preferredIndex, ItemContainer container)
Unequips an Item from the underlying player's Equipment.
double updateWeight ()
void writeBonuses ()
Writes a specific the bonus value on the equipment itemcontainer.
Private Attributes
boolean login
final Player player
The player who's equipment is being managed.
Static Private Attributes
static final int[] ARMADYL_ITEMS = {84, 87, 11785, 11802, 11826, 11830, 12253, 12255, 12257, 12259, 12261, 12263, 12470, 12472, 12474, 12476, 12478, 12506, 12508, 12511, 12512, 19930, 20368, 20229, 12610}
static final int[] BANDOS_ITEMS = {11804, 11832, 11834, 11836, 12265, 12267, 12269, 12271, 12273, 12275, 12480, 12482, 12484, 12486, 12488, 12498, 12500, 12502, 12504, 19924, 20370, 20782, 20232, 11061, 12608, 21733}
static final int[] BONUS_IDS = IntStream.rangeClosed(15130, 15143).toArray()
An array of bonus ids.
static final String[] BONUS_NAMES
Item bonus names.
static final int EQUIPMENT_DISPLAY_ID = 1688
The equipment item display widget identifier.
static final String EXCEPTION_MESSAGE = "Please use { equipment.set(index, Item) } instead"
The error message printed when certain functions from the superclass are utilized.
static final ImmutableSet< Integer > NO_APPEARANCE = ImmutableSet.of(RING_SLOT, ARROWS_SLOT)
An ImmutableSet containing equipment indexes that don't require appearance updates.
static final int[] SARADOMIN_ITEMS = {2412, 2415, 2661, 2663, 2665, 2667, 3479, 4037, 6762, 10384, 10386, 10388, 10390, 10440, 10446, 10452, 10458, 10464, 10470, 10778, 10784, 10792, 11806, 11838, 11891, 12637, 12809, 13331, 13332, 19933, 20372, 21776, 21778, 21791, 3840, 12598, 20220, 19997}
static final int[] ZAMORAK_ITEMS = {1033, 1035, 2414, 2417, 2653, 2655, 2657, 2659, 3478, 4039, 6764, 10368, 10370, 10372, 10374, 10444, 10450, 10456, 10460, 10468, 10474, 10776, 10786, 10790, 11808, 11824, 11889, 11892, 12638, 13333, 13334, 19936, 20374, 21780, 21782, 21795, 1724, 3842, 20223, 11791, 12904}
Detailed Description
The container that manages the equipment for a player.
Author
lare96 http://github.com/lare96
Definition at line 38 of file Equipment.java.
Constructor & Destructor Documentation
Equipment()
com.runehive.game.world.items.containers.equipment.Equipment.Equipment (Player player)
Creates a new Equipment.
Definition at line 120 of file Equipment.java.
{
        super(SIZE, StackPolicy.STANDARD);
        this.player = player;
        addListener(new EquipmentListener());
    }
References com.runehive.game.world.items.containers.ItemContainer.addListener(), player, SIZE, and com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD.
Referenced by getEquipment(), and updateAnimation().
Member Function Documentation
add()
boolean com.runehive.game.world.items.containers.equipment.Equipment.add (Item item, int preferredIndex, boolean refresh)
Adds an item to the equipment container.
Parameters
item The Item to deposit.
preferredIndex The preferable index to deposit item to.
refresh The condition if we will be refreshing our container.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 159 of file Equipment.java.
{
        return true;
    }
References refresh().
addBonus()
void com.runehive.game.world.items.containers.equipment.Equipment.addBonus (Item item) private
Definition at line 374 of file Equipment.java.
{
        for (int index = 0; index < item.getBonuses().length; index++) {
            player.appendBonus(index, item.getBonus(index));
        }
    }
References com.runehive.game.world.items.Item.getBonus(), com.runehive.game.world.items.Item.getBonuses(), and player.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), onEquip(), and onRemove().
appearanceForIndex()
void com.runehive.game.world.items.containers.equipment.Equipment.appearanceForIndex (int equipmentIndex) private
Flags the APPEARANCE update block, only if the equipment piece on equipmentIndex requires an appearance update.
Definition at line 368 of file Equipment.java.
{
        if (!NO_APPEARANCE.contains(equipmentIndex)) {
            player.updateFlags.add(UpdateFlag.APPEARANCE);
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, NO_APPEARANCE, and player.
Referenced by equip(), manualWear(), remove(), unEquip(), and unequip().
clear()
void com.runehive.game.world.items.containers.equipment.Equipment.clear ()
Removes all of the items from this container.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 498 of file Equipment.java.
{
        super.clear();
        Arrays.fill(player.getBonuses(), 0);
    }
References player.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.content.StarterKit.refresh(), and com.runehive.content.lms.LMSGame.reset().
contains()
boolean com.runehive.game.world.items.containers.equipment.Equipment.contains (int[] bowsWithNoArrowsRequired)
Definition at line 749 of file Equipment.java.
{
        return containsAny(22550, 25865, 25867, 25884, 25886, 25890, 25892, 25894, 25896, 25888);
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAny().
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getAttackRoll(), com.runehive.content.skill.impl.mining.PickaxeData.getBestPickaxe(), com.runehive.content.skill.impl.mining.Mining.getBonus(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefender(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefenderIndex(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getGearAttackBonus(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), com.runehive.content.wintertodt.Wintertodt.getWarmItemsWorn(), com.runehive.game.world.entity.combat.FormulaUtils.hasCrawsBow(), com.runehive.game.world.entity.combat.FormulaUtils.hasObbyWeapon(), com.runehive.game.world.entity.combat.FormulaUtils.hasViggorasChainMace(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.hit(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), onEquip(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), remove(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), com.runehive.content.skill.impl.cooking.Cooking.success(), com.runehive.content.skill.impl.fishing.Fishing.success(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.twistedBowBonus(), com.runehive.game.world.entity.combat.FormulaUtils.voidBase(), com.runehive.game.world.entity.combat.FormulaUtils.voidMagic(), com.runehive.game.world.entity.combat.FormulaUtils.voidMelee(), com.runehive.game.world.entity.combat.FormulaUtils.voidRanger(), com.runehive.game.world.entity.combat.FormulaUtils.wearingBlackMask(), com.runehive.game.world.entity.combat.FormulaUtils.wearingBlackMaskImbued(), and com.runehive.game.world.entity.combat.FormulaUtils.wearingEliteVoid().
equip() [1/2]
boolean com.runehive.game.world.items.containers.equipment.Equipment.equip (int inventoryIndex)
Definition at line 230 of file Equipment.java.
{
        if (inventoryIndex == -1)
            return false;
        Inventory inventory = player.inventory;
        Item item = inventory.get(inventoryIndex);
        if (!Item.valid(item))
            return false;
        if (!item.isEquipable())
            return false;
        if (!Utility.checkRequirements(player, item.getRequirements(), "to equip this item."))
            return false;
        if (!Skillcape.equip(player, item))
            return false;
        if (item.getId() == 21633)
            player.graphic(new Graphic(1395, true, UpdatePriority.VERY_HIGH));
        EquipmentType type = item.getEquipmentType();
        Item current = get(type.getSlot());
        Item toRemove = null;
        if (current != null && item.isStackable() && isItem(type.getSlot(), item.getId())) {
            int amount = item.getAmount();
            if (Integer.MAX_VALUE - current.getAmount() < amount) {
                amount = Integer.MAX_VALUE - current.getAmount();
            }
            set(type.getSlot(), current.createAndIncrement(amount), true);
            inventory.remove(new Item(item.getId(), amount), inventoryIndex, true);
            return true;
        }
        if (hasWeapon() && type.equals(EquipmentType.SHIELD))
            if (item.isTwoHanded() || getWeapon().isTwoHanded())
                toRemove = getWeapon();
        if (hasShield() && type.equals(EquipmentType.WEAPON))
            if (item.isTwoHanded() || getShield().isTwoHanded())
                toRemove = getShield();
        if (toRemove != null && !inventory.hasCapacityFor(toRemove)) {
            player.send(new SendMessage("You do not have enough space in your inventory."));
            return false;
        }
        inventory.remove(item, inventoryIndex);
        set(type.getSlot(), item, true);
        if (current != null) {
            inventory.add(current, inventoryIndex);
        }
        appearanceForIndex(type.getSlot());
//        if (player.getCombat().isAttacking(player.getCombat().getDefender()) && !player.getCombat().checkWithin(player, player.getCombat().getDefender(), player.getStrategy())) {
//            Mob defender = player.getCombat().getDefender();
//            player.getCombat().reset();
//            System.out.println("ka");
//            player.movement.dijkstraPath(defender);
//        } else {
        player.getCombat().reset();
//        }
        if (toRemove != null) {
            int slot = toRemove.getEquipmentType().getSlot();
            set(slot, null, true);
            appearanceForIndex(slot);
            inventory.add(toRemove, inventoryIndex, true);
        }
        if (player.interfaceManager.isInterfaceOpen(15106)) {
            openInterface();
        }
        return true;
    }
References appearanceForIndex(), com.runehive.util.Utility.checkRequirements(), com.runehive.game.world.items.Item.createAndIncrement(), com.runehive.content.emote.Skillcape.equip(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getEquipmentType(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getRequirements(), getShield(), com.runehive.game.world.items.containers.equipment.EquipmentType.getSlot(), getWeapon(), hasShield(), hasWeapon(), com.runehive.game.world.items.Item.isEquipable(), isItem(), com.runehive.game.world.items.Item.isStackable(), com.runehive.game.world.items.Item.isTwoHanded(), openInterface(), player, com.runehive.game.world.items.containers.equipment.EquipmentType.SHIELD, com.runehive.game.world.items.Item.valid(), com.runehive.game.UpdatePriority.VERY_HIGH, and com.runehive.game.world.items.containers.equipment.EquipmentType.WEAPON.
equip() [2/2]
boolean com.runehive.game.world.items.containers.equipment.Equipment.equip (Item item)
Definition at line 225 of file Equipment.java.
{
        int index = player.inventory.computeIndexForId(item.getId());
        return equip(index);
    }
References equip(), com.runehive.game.world.items.Item.getId(), and player.
Referenced by equip(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.content.itemaction.impl.CelestialRing.inventory(), and unEquip().
getAmuletSlot()
Item com.runehive.game.world.items.containers.equipment.Equipment.getAmuletSlot ()
Definition at line 435 of file Equipment.java.
{
        return get(AMULET_SLOT);
    }
References AMULET_SLOT.
Referenced by com.runehive.game.action.impl.BuryBoneAction.onExecute().
getCape()
Item com.runehive.game.world.items.containers.equipment.Equipment.getCape ()
Definition at line 451 of file Equipment.java.
{
        return get(CAPE_SLOT);
    }
References CAPE_SLOT.
Referenced by com.runehive.content.skillcape.SkillCape.isEquipped().
getEquipment()
Item[] com.runehive.game.world.items.containers.equipment.Equipment.getEquipment ()
Definition at line 463 of file Equipment.java.
{
        Item[] equipment = new Item[15];
        equipment[1] = player.equipment.get(Equipment.HELM_SLOT);
        equipment[3] = player.equipment.get(Equipment.CAPE_SLOT);
        equipment[4] = player.equipment.get(Equipment.AMULET_SLOT);
        equipment[5] = player.equipment.get(Equipment.ARROWS_SLOT);
        equipment[6] = player.equipment.get(Equipment.WEAPON_SLOT);
        equipment[7] = player.equipment.get(Equipment.CHEST_SLOT);
        equipment[8] = player.equipment.get(Equipment.SHIELD_SLOT);
        equipment[10] = player.equipment.get(Equipment.LEGS_SLOT);
        equipment[12] = player.equipment.get(Equipment.HANDS_SLOT);
        equipment[13] = player.equipment.get(Equipment.FEET_SLOT);
        equipment[14] = player.equipment.get(Equipment.RING_SLOT);
        return equipment;
    }
References Equipment(), and player.
getShield()
Item com.runehive.game.world.items.containers.equipment.Equipment.getShield ()
Definition at line 459 of file Equipment.java.
{
        return get(SHIELD_SLOT);
    }
References SHIELD_SLOT.
Referenced by equip(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation().
getWeapon()
Item com.runehive.game.world.items.containers.equipment.Equipment.getWeapon ()
Definition at line 447 of file Equipment.java.
{
        return get(WEAPON_SLOT);
    }
References WEAPON_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.game.world.entity.combat.magic.Autocast.clickButton(), equip(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.hit(), com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), onEquip(), onRemove(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.twistedBowBonus(), updateAnimation(), and updateRangedEquipment().
hasAccumulator()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasAccumulator (Player player) static
Definition at line 669 of file Equipment.java.
{
        Item cape = player.equipment.getCape();
        return cape != null && (cape.matchesId(10499) || cape.matchesId(13337) || cape.matchesId(27363) || cape.matchesId(27365 ) || SkillCape.isEquipped(player, SkillCape.RANGED));
    }
References com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.game.world.items.Item.matchesId(), player, and com.runehive.content.skillcape.SkillCape.RANGED.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
hasAmmo()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasAmmo ()
Definition at line 411 of file Equipment.java.
{
        return get(ARROWS_SLOT) != null;
    }
References ARROWS_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), and com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz().
hasAmulet()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasAmulet ()
Definition at line 407 of file Equipment.java.
{
        return get(AMULET_SLOT) != null;
    }
References AMULET_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), and com.runehive.game.action.impl.BuryBoneAction.onExecute().
hasArmadyl()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasArmadyl ()
Definition at line 729 of file Equipment.java.
{
        return containsAny(ARMADYL_ITEMS);
    }
References ARMADYL_ITEMS, and com.runehive.game.world.items.containers.ItemContainer.containsAny().
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression().
hasAssembler()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasAssembler (Player player) static
Definition at line 674 of file Equipment.java.
{
        Item cape = player.equipment.getCape();
        return cape != null && (cape.matchesId(22109) || cape.matchesId(21898));
    }
References com.runehive.game.world.items.Item.matchesId(), and player.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
hasAttractor()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasAttractor (Player player) static
Definition at line 664 of file Equipment.java.
{
        Item cape = player.equipment.getCape();
        return cape != null && (cape.matchesId(10498) || cape.matchesId(13337) || cape.matchesId(27363) || cape.matchesId(27365 ) || SkillCape.isEquipped(player, SkillCape.RANGED));
    }
References com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.game.world.items.Item.matchesId(), player, and com.runehive.content.skillcape.SkillCape.RANGED.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.removeAmmunition(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
hasBandos()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasBandos ()
Definition at line 733 of file Equipment.java.
{
        return containsAny(BANDOS_ITEMS);
    }
References BANDOS_ITEMS, and com.runehive.game.world.items.containers.ItemContainer.containsAny().
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression().
hasCape()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasCape ()
Definition at line 443 of file Equipment.java.
{
        return get(CAPE_SLOT) != null;
    }
References CAPE_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
hasChest()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasChest ()
Definition at line 415 of file Equipment.java.
{
        return get(CHEST_SLOT) != null;
    }
References CHEST_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
hasFeet()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasFeet ()
Definition at line 427 of file Equipment.java.
{
        return get(FEET_SLOT) != null;
    }
References FEET_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
hasHands()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasHands ()
Definition at line 423 of file Equipment.java.
{
        return get(HANDS_SLOT) != null;
    }
References HANDS_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
hasHead()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasHead ()
Definition at line 403 of file Equipment.java.
{
        return get(HEAD_SLOT) != null;
    }
References HEAD_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
hasLegs()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasLegs ()
Definition at line 419 of file Equipment.java.
{
        return get(LEGS_SLOT) != null;
    }
References LEGS_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
hasRing()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasRing ()
Definition at line 431 of file Equipment.java.
{
        return get(RING_SLOT) != null;
    }
References RING_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
hasRow()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasRow ()
Definition at line 745 of file Equipment.java.
{
        return containsAny(2572, 12785);
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAny().
hasSaradomin()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasSaradomin ()
Definition at line 737 of file Equipment.java.
{
        return containsAny(SARADOMIN_ITEMS);
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAny(), and SARADOMIN_ITEMS.
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression().
hasShayzien()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasShayzien ()
Definition at line 726 of file Equipment.java.
{
        return containsAny(SHAYZIEN_ITEMS);
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAny(), and SHAYZIEN_ITEMS.
hasShield()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasShield ()
Definition at line 455 of file Equipment.java.
{
        return get(SHIELD_SLOT) != null;
    }
References SHIELD_SLOT.
Referenced by equip(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation(), and com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
hasWeapon()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon ()
Definition at line 439 of file Equipment.java.
{
        return get(WEAPON_SLOT) != null;
    }
References WEAPON_SLOT.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), equip(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.hit(), com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), onEquip(), onRemove(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), updateAnimation(), and updateRangedEquipment().
hasZamorak()
boolean com.runehive.game.world.items.containers.equipment.Equipment.hasZamorak ()
Definition at line 741 of file Equipment.java.
{
        return containsAny(ZAMORAK_ITEMS);
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAny(), and ZAMORAK_ITEMS.
Referenced by com.runehive.game.world.entity.combat.CombatTarget.checkAggression().
isItem()
boolean com.runehive.game.world.items.containers.equipment.Equipment.isItem (int slot, int itemId) private
Definition at line 503 of file Equipment.java.
{
        Item item = get(slot);
        return item != null && item.getId() == itemId;
    }
References com.runehive.game.world.items.Item.getId().
Referenced by equip().
isWearingDFS()
boolean com.runehive.game.world.items.containers.equipment.Equipment.isWearingDFS (Player player) static
Definition at line 652 of file Equipment.java.
{
        if (!player.equipment.hasShield()) {
            return false;
        }
        Item shield = player.equipment.getShield();
        return shield.getId() == 11283 || shield.getId() == 11284 ||
                shield.getId() == 21633 || shield.getId() == 21634 ||
                shield.getId() == 22002 || shield.getId() == 22003;
    }
References com.runehive.game.world.items.Item.getId(), and player.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire().
login()
void com.runehive.game.world.items.containers.equipment.Equipment.login ()
Handles refreshing all the equipment items.
Definition at line 129 of file Equipment.java.
{
        login = true;
        Arrays.fill(player.getBonuses(), 0);
        for (int index = 0; index < getItems().length; index++) {
            fireItemUpdatedEvent(null, get(index), index, false, true);
        }
        login = false;
        updateWeight();
        refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.fireItemUpdatedEvent(), com.runehive.game.world.items.containers.ItemContainer.getItems(), login, player, refresh(), and updateWeight().
manualWear()
void com.runehive.game.world.items.containers.equipment.Equipment.manualWear (Item item)
Manually wears an item (does not have any restrictions).
Parameters
item The item to wear.
Definition at line 213 of file Equipment.java.
{
        if (item == null)
            return;
        if (!item.isEquipable())
            return;
        EquipmentType type = item.getEquipmentType();
        if (type.getSlot() == -1)
            return;
        set(type.getSlot(), item, false);
        appearanceForIndex(type.getSlot());
    }
References appearanceForIndex(), com.runehive.game.world.items.Item.getEquipmentType(), com.runehive.game.world.items.containers.equipment.EquipmentType.getSlot(), and com.runehive.game.world.items.Item.isEquipable().
Referenced by manualWearAll().
manualWearAll()
void com.runehive.game.world.items.containers.equipment.Equipment.manualWearAll (Item[] items)
Manually wears multiple items (does not have any restrictions).
Parameters
items The items to wear.
Definition at line 202 of file Equipment.java.
{
        for (Item item : items) {
            manualWear(item);
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.items, and manualWear().
onEquip()
void com.runehive.game.world.items.containers.equipment.Equipment.onEquip (Item item) private
Definition at line 523 of file Equipment.java.
{
        EquipmentType type = item.getEquipmentType();
        double boostedExperience = 0.2;
        for (int index = 0; index < LUMBERJACK_PIECES.length; index++) {
            if (contains(LUMBERJACK_PIECES[index][0])) {
                boostedExperience *= SKILLING_SETS_EXPERIENCE_BOOST_PER_PIECE;
            }
        }
        if (type == EquipmentType.SHIELD || type == EquipmentType.WEAPON) {
            updateRangedEquipment();
            if (item.matchesId(12926) && player.blowpipeDarts != null) {
                addBonus(player.blowpipeDarts);
                retrieve(ARROWS_SLOT).ifPresent(this::removeBonus);
                return;
            }
            item.getRangedDefinition()
                    .filter(def -> def.getType().equals(RangedWeaponType.THROWN))
                    .ifPresent(def -> retrieve(ARROWS_SLOT).ifPresent(this::removeBonus));
        } else if (type == EquipmentType.ARROWS) {
            updateRangedEquipment();
            if (!hasWeapon())
                return;
            if (getWeapon().matchesId(12_926) && !login) {
                removeBonus(item);
                return;
            }
            getWeapon().getRangedDefinition()
                    .filter(def -> def.getType().equals(RangedWeaponType.THROWN))
                    .ifPresent(def -> removeBonus(item));
        }
    }
References addBonus(), com.runehive.game.world.items.containers.equipment.EquipmentType.ARROWS, ARROWS_SLOT, contains(), com.runehive.game.world.items.Item.getEquipmentType(), com.runehive.game.world.items.Item.getRangedDefinition(), getWeapon(), hasWeapon(), com.runehive.game.world.items.containers.ItemContainer.ifPresent(), login, LUMBERJACK_PIECES, com.runehive.game.world.items.Item.matchesId(), player, removeBonus(), com.runehive.game.world.items.containers.ItemContainer.retrieve(), com.runehive.game.world.items.containers.equipment.EquipmentType.SHIELD, SKILLING_SETS_EXPERIENCE_BOOST_PER_PIECE, com.runehive.game.world.entity.combat.ranged.RangedWeaponType.THROWN, updateRangedEquipment(), and com.runehive.game.world.items.containers.equipment.EquipmentType.WEAPON.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated().
onRemove()
void com.runehive.game.world.items.containers.equipment.Equipment.onRemove (Item item) private
Definition at line 561 of file Equipment.java.
{
        EquipmentType type = item.getEquipmentType();
        if (type == EquipmentType.SHIELD || type == EquipmentType.WEAPON) {
            boolean isBlowpipe = item.matchesId(12_926);
            if (isBlowpipe && player.blowpipeDarts != null) {
                removeBonus(player.blowpipeDarts);
            }
            if (isBlowpipe || item.getRangedDefinition()
                    .filter(def -> def.getType().equals(RangedWeaponType.THROWN))
                    .isPresent()) {
                retrieve(ARROWS_SLOT).ifPresent(this::addBonus);
            }
            updateRangedEquipment();
        } else if (type == EquipmentType.ARROWS) {
            if (!hasWeapon())
                return;
            boolean isBlowpipe = getWeapon().matchesId(12_926);
            if (isBlowpipe || getWeapon().getRangedDefinition()
                    .filter(def -> def.getType().equals(RangedWeaponType.THROWN))
                    .isPresent()) {
                addBonus(item);
            }
            updateRangedEquipment();
        }
    }
References addBonus(), com.runehive.game.world.items.containers.equipment.EquipmentType.ARROWS, ARROWS_SLOT, com.runehive.game.world.items.Item.getEquipmentType(), com.runehive.game.world.items.Item.getRangedDefinition(), getWeapon(), hasWeapon(), com.runehive.game.world.items.Item.matchesId(), player, removeBonus(), com.runehive.game.world.items.containers.ItemContainer.retrieve(), com.runehive.game.world.items.containers.equipment.EquipmentType.SHIELD, com.runehive.game.world.entity.combat.ranged.RangedWeaponType.THROWN, updateRangedEquipment(), and com.runehive.game.world.items.containers.equipment.EquipmentType.WEAPON.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated().
openInterface()
void com.runehive.game.world.items.containers.equipment.Equipment.openInterface ()
Handles opening the equipment screen itemcontainer.
Definition at line 141 of file Equipment.java.
{
        player.send(new SendString(Utility.formatDigits(updateWeight()) + " kg", 15145));
        player.send(new SendString("Melee Maxhit: <col=ff7000>" + player.playerAssistant.getMaxHit(player, CombatType.MELEE) + "</col>", 15116));
        player.send(new SendString("Range Maxhit: <col=ff7000>" + player.playerAssistant.getMaxHit(player, CombatType.RANGED) + "</col>", 15117));
        player.send(new SendString(Utility.formatDigits(player.playerAssistant.weight()) + " kg", 15145));
        writeBonuses();
        player.interfaceManager.open(15106);
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.combat.CombatType.MELEE, player, com.runehive.game.world.entity.combat.CombatType.RANGED, updateWeight(), and writeBonuses().
Referenced by equip(), and unequip().
refresh() [1/2]
void com.runehive.game.world.items.containers.equipment.Equipment.refresh ()
Forces a refresh of Equipment items to the
EQUIPMENT_DISPLAY_ID widget.
Definition at line 484 of file Equipment.java.
{
        refresh(player, EQUIPMENT_DISPLAY_ID);
    }
References EQUIPMENT_DISPLAY_ID, player, and refresh().
Referenced by add(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), login(), com.runehive.content.StarterKit.refresh(), refresh(), remove(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), and com.runehive.content.lms.LMSGame.reset().
refresh() [2/2]
void com.runehive.game.world.items.containers.equipment.Equipment.refresh (Player player, int widget)
Forces a refresh of Equipment items to the
EQUIPMENT_DISPLAY_ID widget.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 493 of file Equipment.java.
{
        player.send(new SendItemOnInterface(widget, toArray()));
    }
References player, and com.runehive.game.world.items.containers.ItemContainer.toArray().
remove()
boolean com.runehive.game.world.items.containers.equipment.Equipment.remove (Item item, int preferredIndex, boolean refresh)
Removes an item from the equipment container.
Parameters
item The Item to withdraw.
preferredIndex The preferable index to withdraw item from.
refresh The condition if we will be refreshing our container.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 173 of file Equipment.java.
{
        boolean removed = super.remove(item, preferredIndex, refresh);
        if (removed && !contains(item)) {
            this.appearanceForIndex(item.getEquipmentType().getSlot());
        }
        return removed;
    }
References appearanceForIndex(), contains(), and refresh().
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.PhoenixNecklaceListener.block(), and com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block().
removeBonus()
void com.runehive.game.world.items.containers.equipment.Equipment.removeBonus (Item item) private
Definition at line 380 of file Equipment.java.
{
        for (int index = 0; index < item.getBonuses().length; index++) {
            player.appendBonus(index, -item.getBonus(index));
        }
    }
References com.runehive.game.world.items.Item.getBonus(), com.runehive.game.world.items.Item.getBonuses(), and player.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), onEquip(), and onRemove().
unEquip()
void com.runehive.game.world.items.containers.equipment.Equipment.unEquip (Item item)
Definition at line 508 of file Equipment.java.
{
        if (item == null) {
            return;
        }
        for (Item equip : getItems()) {
            if (equip != null && equip.getId() == item.getId()) {
                EquipmentType type = item.getEquipmentType();
                set(type.getSlot(), null, true);
                appearanceForIndex(type.getSlot());
                if (!player.inventory.add(equip))
                    GroundItem.create(player, equip);
            }
        }
    }
References appearanceForIndex(), com.runehive.game.world.items.ground.GroundItem.create(), equip(), com.runehive.game.world.items.Item.getEquipmentType(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.items.containers.equipment.EquipmentType.getSlot(), and player.
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.hit().
unequip() [1/2]
boolean com.runehive.game.world.items.containers.equipment.Equipment.unequip (int equipmentIndex)
Unequips an Item from the underlying player's Equipment.
Parameters
equipmentIndex The Equipment index to unequip the
Item from.
Returns
true if the item was unequipped, false otherwise.
Definition at line 315 of file Equipment.java.
{
        return unequip(equipmentIndex, -1, player.inventory);
    }
References player, and unequip().
Referenced by unequip(), and unequip().
unequip() [2/2]
boolean com.runehive.game.world.items.containers.equipment.Equipment.unequip (int equipmentIndex, int preferredIndex, ItemContainer container) private
Unequips an Item from the underlying player's Equipment.
Parameters
equipmentIndex The Equipment index to unequip the
Item from.
preferredIndex The preferred inventory slot.
container The container to which we are putting the items on.
Returns
true if the item was unequipped, false otherwise.
Definition at line 329 of file Equipment.java.
{
        if (equipmentIndex == -1)
            return false;
        Item unequip = get(equipmentIndex);
        if (unequip == null)
            return false;
        if (!container.add(unequip, preferredIndex, true)) {
            return false;
        }
        set(equipmentIndex, null, true);
        appearanceForIndex(equipmentIndex);
//        if (player.getCombat().isAttacking(player.getCombat().getDefender())
//                && !player.getCombat().checkWithin(player, player.getCombat().getDefender(), player.getStrategy())) {
//            Mob defender = player.getCombat().getDefender();
//            player.getCombat().reset();
//            player.movement.dijkstraPath(defender);
//        } else {
        player.getCombat().reset();
//        }
        if (!player.interfaceManager.isClear() && !player.interfaceManager.isInterfaceOpen(15106)) {
            player.interfaceManager.close(false);
        }
        if (player.interfaceManager.isInterfaceOpen(15106)) {
            openInterface();
        }
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), appearanceForIndex(), com.runehive.game.world.items.containers.ItemContainer.ItemContainer(), openInterface(), player, and unequip().
updateAnimation()
void com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation ()
Updates the weapon animation.
Definition at line 628 of file Equipment.java.
{
        int stand = PLAYER_STAND;
        int walk = PLAYER_WALK;
        int run = PLAYER_RUN;
        if (hasWeapon()) {
            Item weapon = getWeapon();
            stand = weapon.getStandAnimation();
            walk = weapon.getWalkAnimation();
            run = weapon.getRunAnimation();
        }
        if (player.overrides.hasOverride(Equipment.WEAPON_SLOT)) {
            Item weapon = player.overrides.get(Equipment.WEAPON_SLOT);
            stand = weapon.getStandAnimation();
            walk = weapon.getWalkAnimation();
            run = weapon.getRunAnimation();
        }
        player.mobAnimation.setStand(stand);
        player.mobAnimation.setWalk(walk);
        player.mobAnimation.setRun(run);
    }
References Equipment(), com.runehive.game.world.items.Item.getRunAnimation(), com.runehive.game.world.items.Item.getStandAnimation(), com.runehive.game.world.items.Item.getWalkAnimation(), getWeapon(), hasWeapon(), and player.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), and com.runehive.content.lms.LMSGame.reset().
updateRangedEquipment()
void com.runehive.game.world.items.containers.equipment.Equipment.updateRangedEquipment ()
Definition at line 593 of file Equipment.java.
{
        if (!hasWeapon() || !getWeapon().getRangedDefinition().isPresent()) {
            if (hasWeapon() && getWeapon().matchesId(12_926) && player.blowpipeDarts != null) {
                player.rangedAmmo = RangedAmmunition.find(getWeapon(), player.blowpipeDarts);
            } else {
                player.rangedAmmo =
                        retrieve(ARROWS_SLOT)
                                .map(arrow -> RangedAmmunition.find(getWeapon(), arrow))
                                .orElse(null);
            }
            player.rangedDefinition = null;
            return;
        }
        RangedWeaponDefinition def = getWeapon().getRangedDefinition().get();
        player.rangedDefinition = def;
        switch (def.getType()) {
            case SHOT:
                player.rangedAmmo =
                        retrieve(ARROWS_SLOT)
                                .map(arrow -> RangedAmmunition.find(getWeapon(), arrow))
                                .orElse(null);
                break;
            case THROWN:
                player.rangedAmmo = RangedAmmunition.find(getWeapon(), getWeapon());
                break;
        }
    }
References ARROWS_SLOT, com.runehive.game.world.entity.combat.ranged.RangedAmmunition.find(), com.runehive.game.world.items.Item.getRangedDefinition(), getWeapon(), hasWeapon(), player, and com.runehive.game.world.items.containers.ItemContainer.retrieve().
Referenced by com.runehive.content.lms.LMSGame.giveItems(), onEquip(), and onRemove().
updateWeight()
double com.runehive.game.world.items.containers.equipment.Equipment.updateWeight () private
Returns
the current weight value of the player
Definition at line 182 of file Equipment.java.
{
        double weight = 0;
        for (Item equipment : toArray()) {
            if (equipment == null)
                continue;
            weight += equipment.getWeight();
        }
        for (Item item : player.inventory.toArray()) {
            if (item == null)
                continue;
            weight += item.getWeight();
        }
        return weight;
    }
References player, and com.runehive.game.world.items.containers.ItemContainer.toArray().
Referenced by login(), and openInterface().
writeBonuses()
void com.runehive.game.world.items.containers.equipment.Equipment.writeBonuses () private
Writes a specific the bonus value on the equipment itemcontainer.
Definition at line 387 of file Equipment.java.
{
        for (int i = 0; i < player.getBonuses().length; i++) {
            String bonus = BONUS_NAMES[i] + ": ";
            if (player.getBonus(i) >= 0)
                bonus += "+";
            bonus += player.getBonus(i);
            if (i == 12)
                bonus += "%";
            player.send(new SendString(bonus, BONUS_IDS[i]));
        }
    }
References BONUS_IDS, BONUS_NAMES, and player.
Referenced by openInterface().
Member Data Documentation
AMULET_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.AMULET_SLOT = 2 static
Definition at line 51 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), getAmuletSlot(), hasAmulet(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
ANGLER_PIECES
final int [][] com.runehive.game.world.items.containers.equipment.Equipment.ANGLER_PIECES static
Initial value:
=
            {
                    {13258, Equipment.HEAD_SLOT},
                    {13259, Equipment.CHEST_SLOT},
                    {13260, Equipment.LEGS_SLOT},
                    {13261, Equipment.FEET_SLOT},
            }
Fishing.
Definition at line 698 of file Equipment.java.
            {
                    {13258, Equipment.HEAD_SLOT},
                    {13259, Equipment.CHEST_SLOT},
                    {13260, Equipment.LEGS_SLOT},
                    {13261, Equipment.FEET_SLOT},
            };
ARMADYL_ITEMS
final int [] com.runehive.game.world.items.containers.equipment.Equipment.ARMADYL_ITEMS = {84, 87, 11785, 11802, 11826, 11830, 12253, 12255, 12257, 12259, 12261, 12263, 12470, 12472, 12474, 12476, 12478, 12506, 12508, 12511, 12512, 19930, 20368, 20229, 12610} static private
Definition at line 722 of file Equipment.java.
{84, 87, 11785, 11802, 11826, 11830, 12253, 12255, 12257, 12259, 12261, 12263, 12470, 12472, 12474, 12476, 12478, 12506, 12508, 12511, 12512, 19930, 20368, 20229, 12610};
Referenced by hasArmadyl().
ARROWS_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.ARROWS_SLOT = 13 static
Definition at line 60 of file Equipment.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), hasAmmo(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), onEquip(), onRemove(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems(), and updateRangedEquipment().
BANDOS_ITEMS
final int [] com.runehive.game.world.items.containers.equipment.Equipment.BANDOS_ITEMS = {11804, 11832, 11834, 11836, 12265, 12267, 12269, 12271, 12273, 12275, 12480, 12482, 12484, 12486, 12488, 12498, 12500, 12502, 12504, 19924, 20370, 20782, 20232, 11061, 12608, 21733} static private
Definition at line 721 of file Equipment.java.
{11804, 11832, 11834, 11836, 12265, 12267, 12269, 12271, 12273, 12275, 12480, 12482, 12484, 12486, 12488, 12498, 12500, 12502, 12504, 19924, 20370, 20782, 20232, 11061, 12608, 21733};
Referenced by hasBandos().
BONUS_IDS
final int [] com.runehive.game.world.items.containers.equipment.Equipment.BONUS_IDS = IntStream.rangeClosed(15130, 15143).toArray() static private
An array of bonus ids.
Definition at line 80 of file Equipment.java.
Referenced by writeBonuses().
BONUS_NAMES
final String [] com.runehive.game.world.items.containers.equipment.Equipment.BONUS_NAMES static private
Initial value:
= {
      "Stab",
      "Slash",
      "Crush",
      "Magic",
      "Range",
      "Stab",
      "Slash",
      "Crush",
      "Magic",
      "Range",
      "Strength",
      "Ranged Strength",
      "Magic Strength",
      "Prayer"
    }
Item bonus names.
Definition at line 83 of file Equipment.java.
{
     /* 00 */ "Stab",
     /* 01 */ "Slash",
     /* 02 */ "Crush",
     /* 03 */ "Magic",
     /* 04 */ "Range",
     /* - */
     /* 05 */ "Stab",
     /* 06 */ "Slash",
     /* 07 */ "Crush",
     /* 08 */ "Magic",
     /* 09 */ "Range",
     /* - */
     /* 10 */ "Strength",
     /* 11 */ "Ranged Strength",
     /* 12 */ "Magic Strength",
     /* 13 */ "Prayer"
    };
Referenced by writeBonuses().
CAPE_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.CAPE_SLOT = 1 static
Definition at line 50 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), getCape(), hasCape(), com.runehive.content.emote.Emote.skillcape(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems(), and com.runehive.content.emote.EmoteHandler.updateSkillcape().
CHEST_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.CHEST_SLOT = 4 static
Definition at line 53 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), hasChest(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
CRUSH_DEFENCE
final int com.runehive.game.world.items.containers.equipment.Equipment.CRUSH_DEFENCE = 7 static
Definition at line 71 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus().
CRUSH_OFFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.CRUSH_OFFENSE = 2 static
Definition at line 66 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus().
EQUIPMENT_DISPLAY_ID
final int com.runehive.game.world.items.containers.equipment.Equipment.EQUIPMENT_DISPLAY_ID = 1688 static private
The equipment item display widget identifier.
Definition at line 44 of file Equipment.java.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.getWidgetId(), and refresh().
EXCEPTION_MESSAGE
final String com.runehive.game.world.items.containers.equipment.Equipment.EXCEPTION_MESSAGE = "Please use { equipment.set(index, Item) } instead" static private
The error message printed when certain functions from the superclass are utilized.
Definition at line 106 of file Equipment.java.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.getCapacityExceededMsg().
FEET_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.FEET_SLOT = 10 static
Definition at line 58 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), hasFeet(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
HANDS_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.HANDS_SLOT = 9 static
Definition at line 57 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), hasHands(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
HEAD_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.HEAD_SLOT = 0 static
Equipment slot constants.
Definition at line 48 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), hasHead(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
HELM_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.HELM_SLOT = 0 static
Definition at line 49 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.apply(), com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.apply(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.hit(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma(), com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp(), and com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz().
LEGS_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.LEGS_SLOT = 7 static
Definition at line 56 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), hasLegs(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
login
boolean com.runehive.game.world.items.containers.equipment.Equipment.login private
Definition at line 117 of file Equipment.java.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), login(), and onEquip().
LUMBERJACK_PIECES
final int [][] com.runehive.game.world.items.containers.equipment.Equipment.LUMBERJACK_PIECES static
Initial value:
=
            {
                    {10933, Equipment.FEET_SLOT},
                    {10939, Equipment.CHEST_SLOT},
                    {10940, Equipment.LEGS_SLOT},
                    {10941, Equipment.HEAD_SLOT},
            }
Definition at line 679 of file Equipment.java.
            {
                    {10933, Equipment.FEET_SLOT},
                    {10939, Equipment.CHEST_SLOT},
                    {10940, Equipment.LEGS_SLOT},
                    {10941, Equipment.HEAD_SLOT},
            };
Referenced by onEquip().
MAGIC_DEFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_DEFENSE = 8 static
Definition at line 72 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getDefenceBonus(), and com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDefensiveBonus().
MAGIC_OFFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_OFFENSE = 3 static
Definition at line 67 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getAttackBonus(), com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus(), and com.runehive.game.world.entity.combat.formula.MagicFormula.modifyOffensiveBonus().
MAGIC_STRENGTH
final int com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_STRENGTH = 12 static
Definition at line 76 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage().
NO_APPEARANCE
final ImmutableSet<Integer> com.runehive.game.world.items.containers.equipment.Equipment.NO_APPEARANCE = ImmutableSet.of(RING_SLOT, ARROWS_SLOT) static private
An ImmutableSet containing equipment indexes that don't require appearance updates.
Definition at line 112 of file Equipment.java.
Referenced by appearanceForIndex().
PICKAXES
final int [] com.runehive.game.world.items.containers.equipment.Equipment.PICKAXES = {1265, 1267, 1269, 1273, 1271, 1275, 13243, 20014, 11920, 12797} static
Definition at line 724 of file Equipment.java.
{1265, 1267, 1269, 1273, 1271, 1275, 13243, 20014, 11920, 12797};
Referenced by com.runehive.content.skill.impl.mining.MiningAction.mine().
player
final Player com.runehive.game.world.items.containers.equipment.Equipment.player private
The player who's equipment is being managed.
Definition at line 115 of file Equipment.java.
Referenced by addBonus(), appearanceForIndex(), clear(), equip(), equip(), Equipment(), getEquipment(), hasAccumulator(), hasAssembler(), hasAttractor(), isWearingDFS(), login(), onEquip(), onRemove(), openInterface(), refresh(), refresh(), removeBonus(), unEquip(), unequip(), unequip(), updateAnimation(), updateRangedEquipment(), updateWeight(), and writeBonuses().
PRAYER_BONUS
final int com.runehive.game.world.items.containers.equipment.Equipment.PRAYER_BONUS = 13 static
Definition at line 77 of file Equipment.java.
Referenced by com.runehive.util.tools.wiki.impl.BonusParser.generateTables(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.prayerDrain().
PROSPECTOR_PIECES
final int [][] com.runehive.game.world.items.containers.equipment.Equipment.PROSPECTOR_PIECES static
Initial value:
=
            {
                    {12013, Equipment.HEAD_SLOT},
                    {12014, Equipment.CHEST_SLOT},
                    {12015, Equipment.LEGS_SLOT},
                    {12016, Equipment.FEET_SLOT},
            }
Mining.
Definition at line 709 of file Equipment.java.
            {
                    {12013, Equipment.HEAD_SLOT},
                    {12014, Equipment.CHEST_SLOT},
                    {12015, Equipment.LEGS_SLOT},
                    {12016, Equipment.FEET_SLOT},
            };
RANGED_DEFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.RANGED_DEFENSE = 9 static
Definition at line 73 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getDefenceBonus(), and com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensiveBonus().
RANGED_OFFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.RANGED_OFFENSE = 4 static
Definition at line 68 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getRangeBonus(), and com.runehive.game.world.entity.combat.formula.RangedFormula.modifyOffensiveBonus().
RANGED_STRENGTH
final int com.runehive.game.world.items.containers.equipment.Equipment.RANGED_STRENGTH = 11 static
Definition at line 75 of file Equipment.java.
Referenced by com.runehive.util.tools.wiki.impl.BonusParser.generateTables(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getBaseDamage(), and com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAggressiveBonus().
RING_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.RING_SLOT = 12 static
Definition at line 59 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.block(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), hasRing(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.useROW().
SARADOMIN_ITEMS
final int [] com.runehive.game.world.items.containers.equipment.Equipment.SARADOMIN_ITEMS = {2412, 2415, 2661, 2663, 2665, 2667, 3479, 4037, 6762, 10384, 10386, 10388, 10390, 10440, 10446, 10452, 10458, 10464, 10470, 10778, 10784, 10792, 11806, 11838, 11891, 12637, 12809, 13331, 13332, 19933, 20372, 21776, 21778, 21791, 3840, 12598, 20220, 19997} static private
Definition at line 720 of file Equipment.java.
{2412, 2415, 2661, 2663, 2665, 2667, 3479, 4037, 6762, 10384, 10386, 10388, 10390, 10440, 10446, 10452, 10458, 10464, 10470, 10778, 10784, 10792, 11806, 11838, 11891, 12637, 12809, 13331, 13332, 19933, 20372, 21776, 21778, 21791, 3840, 12598, 20220, 19997};
Referenced by hasSaradomin().
SHAYZIEN_ITEMS
final int [] com.runehive.game.world.items.containers.equipment.Equipment.SHAYZIEN_ITEMS = {13377, 13378, 13379, 13380, 13381} static
Definition at line 723 of file Equipment.java.
{13377, 13378, 13379, 13380, 13381};
Referenced by hasShayzien().
SHAYZIEN_PIECES
final int [][] com.runehive.game.world.items.containers.equipment.Equipment.SHAYZIEN_PIECES static
Initial value:
=
            {
                    {Items.SHAYZIEN_GLOVES_5_, Equipment.HANDS_SLOT},
                    {Items.SHAYZIEN_BOOTS_5_, Equipment.FEET_SLOT},
                    {Items.SHAYZIEN_HELM_5_, Equipment.HEAD_SLOT},
                    {Items.SHAYZIEN_GREAVES_5_, Equipment.LEGS_SLOT},
                    {Items.SHAYZIEN_PLATEBODY_5_, Equipment.CHEST_SLOT},
            }
Definition at line 686 of file Equipment.java.
            {
                    {Items.SHAYZIEN_GLOVES_5_, Equipment.HANDS_SLOT},
                    {Items.SHAYZIEN_BOOTS_5_, Equipment.FEET_SLOT},
                    {Items.SHAYZIEN_HELM_5_, Equipment.HEAD_SLOT},
                    {Items.SHAYZIEN_GREAVES_5_, Equipment.LEGS_SLOT},
                    {Items.SHAYZIEN_PLATEBODY_5_, Equipment.CHEST_SLOT},
            };
SHIELD_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.SHIELD_SLOT = 5 static
Definition at line 54 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.CombatUtil.getBlockAnimation(), getShield(), com.runehive.content.overrides.Overrides.hasOverride(), hasShield(), com.runehive.content.overrides.Overrides.hasShieldOverride(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
SIZE
final int com.runehive.game.world.items.containers.equipment.Equipment.SIZE = 14 static
The size of all equipment instances.
Definition at line 41 of file Equipment.java.
Referenced by Equipment(), and com.runehive.util.tools.wiki.impl.BonusParser.generateTables().
SKILLING_SETS_EXPERIENCE_BOOST_PER_PIECE
final double com.runehive.game.world.items.containers.equipment.Equipment.SKILLING_SETS_EXPERIENCE_BOOST_PER_PIECE = 1.02 static
Definition at line 717 of file Equipment.java.
Referenced by onEquip().
SLASH_DEFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.SLASH_DEFENSE = 6 static
Definition at line 70 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus().
SLASH_OFFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.SLASH_OFFENSE = 1 static
Definition at line 65 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus().
STAB_DEFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.STAB_DEFENSE = 5 static
Definition at line 69 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus().
STAB_OFFENSE
final int com.runehive.game.world.items.containers.equipment.Equipment.STAB_OFFENSE = 0 static
Equipment bonus constants.
Definition at line 64 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus().
STRENGTH_BONUS
final int com.runehive.game.world.items.containers.equipment.Equipment.STRENGTH_BONUS = 10 static
Definition at line 74 of file Equipment.java.
Referenced by com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressiveBonus().
WEAPON_SLOT
final int com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT = 3 static
Definition at line 52 of file Equipment.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.assign(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.CombatUtil.getBlockAnimation(), com.runehive.game.world.entity.mob.player.PlayerAssistant.getStrategy(), getWeapon(), com.runehive.content.overrides.Overrides.hasOverride(), com.runehive.content.overrides.Overrides.hasShieldOverride(), hasWeapon(), com.runehive.content.overrides.Overrides.hasWeaponOverride(), com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
ZAMORAK_ITEMS
final int [] com.runehive.game.world.items.containers.equipment.Equipment.ZAMORAK_ITEMS = {1033, 1035, 2414, 2417, 2653, 2655, 2657, 2659, 3478, 4039, 6764, 10368, 10370, 10372, 10374, 10444, 10450, 10456, 10460, 10468, 10474, 10776, 10786, 10790, 11808, 11824, 11889, 11892, 12638, 13333, 13334, 19936, 20374, 21780, 21782, 21795, 1724, 3842, 20223, 11791, 12904} static private
Definition at line 719 of file Equipment.java.
{1033, 1035, 2414, 2417, 2653, 2655, 2657, 2659, 3478, 4039, 6764, 10368, 10370, 10372, 10374, 10444, 10450, 10456, 10460, 10468, 10474, 10776, 10786, 10790, 11808, 11824, 11889, 11892, 12638, 13333, 13334, 19936, 20374, 21780, 21782, 21795, 1724, 3842, 20223, 11791, 12904};
Referenced by hasZamorak().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/equipment/Equipment.java