RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon Class Reference
com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon Class Reference
Classes
class CrushMelee
class MagicAttack
class StabMelee
Public Member Functions
boolean canAttack (Npc attacker, Mob defender)
void finishOutgoing (Npc attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
boolean canAttack (T attacker, Mob defender)
boolean canOtherAttack (Mob attacker, T defender)
void finishIncoming (Mob attacker, T defender)
void finishOutgoing (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
void hitsplat (T attacker, Mob defender, Hit hit)
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
void onKill (T attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, T defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
void start (T attacker, Mob defender, Hit[] hits)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Static Package Functions
[static initializer]
Static Private Member Functions
static Projectile getMagicProjectile (int npcId)
static int getMaxHit (int npcId)
Static Private Attributes
static BrutalDragonfireStrategy DRAGONFIRE
static CombatStrategy< Npc >[] STRATEGIES
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
static final CombatListener< Mob > CANT_ATTACK
Detailed Description
Author
Michael | Chex
Definition at line 31 of file BrutalDragon.java.
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.[static initializer] static package
References DRAGONFIRE, and STRATEGIES.
canAttack()
boolean com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.canAttack (Npc attacker, Mob defender)
Definition at line 45 of file BrutalDragon.java.
{
        final var style = Utility.random(NpcMeleeStrategy.get().withinDistance(attacker, defender) ? 1 : 2);
        if (style == 0) {
            attacker.setStrategy(DRAGONFIRE);
        } else if (style == 1) {
            attacker.setStrategy(new MagicAttack());
        } else {
            attacker.setStrategy(randomStrategy(STRATEGIES));
        }
        return attacker.getStrategy().canAttack(attacker, defender);
    }
References DRAGONFIRE, com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.get(), com.runehive.game.world.entity.mob.npc.Npc.getStrategy(), com.runehive.util.Utility.random(), com.runehive.game.world.entity.mob.npc.Npc.setStrategy(), STRATEGIES, and com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.withinDistance().
finishOutgoing()
void com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.finishOutgoing (Npc attacker, Mob defender)
Definition at line 58 of file BrutalDragon.java.
{
        final var style = Utility.random(NpcMeleeStrategy.get().withinDistance(attacker, defender) ? 1 : 2);
        if (style == 0) {
            attacker.setStrategy(DRAGONFIRE);
        } else if (style == 1) {
            attacker.setStrategy(new MagicAttack());
        } else {
            attacker.setStrategy(randomStrategy(STRATEGIES));
        }
    }
References DRAGONFIRE, com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.get(), com.runehive.util.Utility.random(), com.runehive.game.world.entity.mob.npc.Npc.setStrategy(), STRATEGIES, and com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.withinDistance().
getMagicProjectile()
Projectile com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.getMagicProjectile (int npcId) static private
Definition at line 136 of file BrutalDragon.java.
{
        return switch (npcId) {
            case 2918, 8081 -> new Projectile(136, 40, 90, 27, 30, 5); //green
            case 7273 -> new Projectile(133, 40, 90, 27, 30, 5); //blue
            case 7274, 8087 -> new Projectile(130, 40, 90, 27, 30, 5); //red
            case 7275, 8092 -> new Projectile(88, 40, 90, 27, 30, 5); //black
            default -> null;
        };
    }
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack.getAttackAnimation().
getMaxHit()
int com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.getMaxHit (int npcId) static private
Definition at line 126 of file BrutalDragon.java.
{
        return switch (npcId) {
            case 2918, 8081 -> 18; //green
            case 7273 -> 21; //blue
            case 7274, 8087 -> 22; //red
            case 7275, 8092 -> 29; //black
            default -> -1;
        };
    }
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.MagicAttack.getHits().
Member Data Documentation
DRAGONFIRE
BrutalDragonfireStrategy com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.DRAGONFIRE static private
Definition at line 32 of file BrutalDragon.java.
Referenced by [static initializer](), canAttack(), and finishOutgoing().
STRATEGIES
CombatStrategy<Npc> [] com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.STRATEGIES static private
Definition at line 33 of file BrutalDragon.java.
Referenced by [static initializer](), canAttack(), and finishOutgoing().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/npc/dragon/BrutalDragon.java