RuneHive-Game: com.runehive.fs.cache.archive.Archive Class Reference
com.runehive.fs.cache.archive.Archive Class Reference
Represents an archive within the Cache.
Public Member Functions
ByteBuffer getData (String name)
Returns the data within the ArchiveSector for the specified String name.
Static Public Member Functions
static Archive decode (ByteBuffer data) throws IOException
Decodes the data within this Archive.
Private Member Functions
Archive (Int2ObjectMap< ArchiveSector > sectors)
Constructs a new Archive with the specified Map of ArchiveSectors.
Optional< ArchiveSector > getSector (int hash)
Retrieves an Optional<ArchiveSector> for the specified hash.
Optional< ArchiveSector > getSector (String name)
Retrieves an Optional<ArchiveSector> for the specified name.
Private Attributes
final Int2ObjectMap< ArchiveSector > sectors
A Map of ArchiveSector hashes to ArchiveSectors.
Detailed Description
Represents an archive within the Cache.
An archive contains varied amounts of ArchiveSectors which contain compressed file system data.
Author
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Definition at line 25 of file Archive.java.
Constructor & Destructor Documentation
Archive()
com.runehive.fs.cache.archive.Archive.Archive (Int2ObjectMap< ArchiveSector > sectors) private
Constructs a new Archive with the specified Map of ArchiveSectors.
Parameters
sectors The Map of sectors within this archive.
Definition at line 36 of file Archive.java.
{
        this.sectors = sectors;
    }
References sectors.
Referenced by decode().
Member Function Documentation
decode()
Archive com.runehive.fs.cache.archive.Archive.decode (ByteBuffer data) throws IOException static
Decodes the data within this Archive.
Parameters
data The encoded data within this archive.
Returns
Returns an Archive with the decoded data, never
null.
Exceptions
IOException If some I/O exception occurs.
Definition at line 48 of file Archive.java.
{
        int length = ByteBufferUtil.getMedium(data);
        int compressedLength = ByteBufferUtil.getMedium(data);
        byte[] uncompressedData = data.array();
        if (compressedLength != length) {
            uncompressedData = CompressionUtil.unbzip2Headerless(data.array(), INDEX_SIZE, compressedLength);
            data = ByteBuffer.wrap(uncompressedData);
        }
        int total = data.getShort() & 0xFF;
        int offset = data.position() + total * 10;
        Int2ObjectMap<ArchiveSector> sectors = new Int2ObjectOpenHashMap<>(total);
        for (int i = 0; i < total; i++) {
            int hash = data.getInt();
            length = ByteBufferUtil.getMedium(data);
            compressedLength = ByteBufferUtil.getMedium(data);
            byte[] sectorData = new byte[length];
            if (length != compressedLength) {
                sectorData = CompressionUtil.unbzip2Headerless(uncompressedData, offset, compressedLength);
            } else {
                System.arraycopy(uncompressedData, offset, sectorData, 0, length);
            }
            sectors.put(hash, new ArchiveSector(ByteBuffer.wrap(sectorData), hash));
            offset += compressedLength;
        }
        return new Archive(sectors);
    }
References Archive(), com.runehive.fs.util.ByteBufferUtil.getMedium(), sectors, and com.runehive.fs.util.CompressionUtil.unbzip2Headerless().
Referenced by com.runehive.fs.cache.FileSystem.create().
getData()
ByteBuffer com.runehive.fs.cache.archive.Archive.getData (String name)
Returns the data within the ArchiveSector for the specified String name.
Parameters
name The name of the ArchiveSector.
Returns
The data within the ArchiveSector or nothing, this method fails-fast if no ArchiveSector exists for the specified
name.
Definition at line 113 of file Archive.java.
{
        Optional<ArchiveSector> optionalData = getSector(name);
        Preconditions.checkArgument(optionalData.isPresent());
        ArchiveSector dataSector = optionalData.get();
        return dataSector.getData();
    }
References com.runehive.fs.cache.archive.ArchiveSector.getData(), and getSector().
getSector() [1/2]
Optional< ArchiveSector > com.runehive.fs.cache.archive.Archive.getSector (int hash) private
Retrieves an Optional<ArchiveSector> for the specified hash.
Parameters
hash The archive sectors hash.
Returns
The optional container.
Definition at line 89 of file Archive.java.
{
        return Optional.ofNullable(sectors.get(hash));
    }
References sectors.
Referenced by getData(), and getSector().
getSector() [2/2]
Optional< ArchiveSector > com.runehive.fs.cache.archive.Archive.getSector (String name) private
Retrieves an Optional<ArchiveSector> for the specified name.
Parameters
name The archive sectors name.
Returns
The optional container.
Definition at line 99 of file Archive.java.
{
        int hash = StringUtils.hashArchive(name);
        return getSector(hash);
    }
References getSector(), and com.runehive.util.StringUtils.hashArchive().
Member Data Documentation
sectors
final Int2ObjectMap<ArchiveSector> com.runehive.fs.cache.archive.Archive.sectors private
A Map of ArchiveSector hashes to ArchiveSectors.
Definition at line 28 of file Archive.java.
Referenced by Archive(), decode(), and getSector().
The documentation for this class was generated from the following file:
java/com/runehive/fs/cache/archive/Archive.java