RuneHive-Game: com.runehive.net.packet.out.SendPlayerUpdate Class Reference
com.runehive.net.packet.out.SendPlayerUpdate Class Reference
Classes
enum UpdateState
Public Member Functions
boolean encode (Player player)
SendPlayerUpdate ()
Public Member Functions inherited from com.runehive.net.packet.OutgoingPacket
void execute (Player player)
OutgoingPacket (int opcode, int capacity)
OutgoingPacket (int opcode, PacketType type)
OutgoingPacket (int opcode, PacketType type, int size)
Static Private Member Functions
static void addNewPlayer (PacketBuilder packetBuf, Player player, Player other)
static void appendAnimationMask (Player other, PacketBuilder maskBuf)
static void appendAppearanceMask (Player other, PacketBuilder blockBuf)
static void appendChatMask (PacketBuilder blockBuf, Player other)
static void appendFaceCoordinteMask (Player other, PacketBuilder blockBuf)
static void appendFaceEntityMask (Player other, PacketBuilder blockBuf)
static void appendForceChatMask (Player other, PacketBuilder blockBuf)
static void appendForceMovementMask (Player player, Player other, PacketBuilder blockBuf)
static void appendGraphicMask (Player other, PacketBuilder blockBuf)
static void appendHitMask (final Player player, final PacketBuilder blockBuf)
static void appendSecondHitMask (final Player player, final PacketBuilder blockBuf)
static void updateMovement (Player player, PacketBuilder packetBuf)
static void updatePlayer (PacketBuilder blockBuf, Player player, Player other, UpdateState state)
Static Private Attributes
static final Logger logger = LogManager.getLogger(SendPlayerUpdate.class)
Additional Inherited Members
Protected Attributes inherited from com.runehive.net.packet.OutgoingPacket
final PacketBuilder builder
Detailed Description
Definition at line 34 of file SendPlayerUpdate.java.
Constructor & Destructor Documentation
SendPlayerUpdate()
com.runehive.net.packet.out.SendPlayerUpdate.SendPlayerUpdate ()
Definition at line 38 of file SendPlayerUpdate.java.
{
        super(81, PacketType.VAR_SHORT);
    }
References com.runehive.net.packet.PacketType.VAR_SHORT.
Member Function Documentation
addNewPlayer()
void com.runehive.net.packet.out.SendPlayerUpdate.addNewPlayer (PacketBuilder packetBuf, Player player, Player other) static private
Definition at line 110 of file SendPlayerUpdate.java.
{
        packetBuf.writeBits(11, other.getIndex())
        .writeBit(true) // isUpdateRequired
        .writeBit(true) // discardWalkingQueue
        .writeBits(5, other.getY() - player.getY())
        .writeBits(5, other.getX() - player.getX());
    }
References com.runehive.game.world.entity.Entity.getIndex(), com.runehive.game.world.entity.Entity.getX(), com.runehive.game.world.entity.Entity.getY(), com.runehive.net.packet.PacketBuilder.writeBit(), and com.runehive.net.packet.PacketBuilder.writeBits().
Referenced by encode().
appendAnimationMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendAnimationMask (Player other, PacketBuilder maskBuf) static private
Definition at line 241 of file SendPlayerUpdate.java.
{
        Animation anim = other.getAnimation().orElse(Animation.RESET);
        maskBuf.writeShort(anim.getId(), ByteOrder.LE);
        maskBuf.writeByte(anim.getDelay(), ByteModification.NEG);
    }
References com.runehive.game.world.entity.mob.Mob.getAnimation(), com.runehive.game.Animation.getDelay(), com.runehive.game.Animation.getId(), com.runehive.net.codec.ByteOrder.LE, com.runehive.net.codec.ByteModification.NEG, com.runehive.game.Animation.RESET, com.runehive.net.packet.PacketBuilder.writeByte(), and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updatePlayer().
appendAppearanceMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask (Player other, PacketBuilder blockBuf) static private
Definition at line 263 of file SendPlayerUpdate.java.
{
        final PacketBuilder tempBuf = PacketBuilder.alloc();
        final var overrides = other.overrides;
        try {
            tempBuf.writeByte(other.appearance.getGender().ordinal())
                    .writeByte(other.headIcon)
                    .writeByte(other.skulling.getHeadIconType().getCode())
                    .writeByte(other.valueIcon);
            if (other.id != -1) {
                tempBuf.writeShort(-1);
                tempBuf.writeShort(other.id);
            } else {
                Item helm = other.equipment.get(Equipment.HEAD_SLOT);
                if (overrides.hasOverride(Equipment.HEAD_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.HELM_SLOT).getId());
                } else if (helm != null && helm.getId() > 1) {
                    tempBuf.writeShort(0x200 + other.equipment.get(Equipment.HELM_SLOT).getId());
                } else {
                    tempBuf.writeByte(0);
                }
                if (overrides.hasOverride(Equipment.CAPE_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.CAPE_SLOT).getId());
                } else if (other.equipment.get(Equipment.CAPE_SLOT) != null) {
                    tempBuf.writeShort(0x200 + other.equipment.get(Equipment.CAPE_SLOT).getId());
                } else {
                    tempBuf.writeByte(0);
                }
                if (overrides.hasOverride(Equipment.AMULET_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.AMULET_SLOT).getId());
                } else if (other.equipment.get(Equipment.AMULET_SLOT) != null) {
                    tempBuf.writeShort(0x200 + other.equipment.get(Equipment.AMULET_SLOT).getId());
                } else {
                    tempBuf.writeByte(0);
                }
                if (overrides.hasOverride(Equipment.WEAPON_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.WEAPON_SLOT).getId());
                } else if (other.equipment.get(Equipment.WEAPON_SLOT) != null) {
                    tempBuf.writeShort(0x200 + other.equipment.get(Equipment.WEAPON_SLOT).getId());
                } else {
                    tempBuf.writeByte(0);
                }
                Item torso = other.equipment.get(Equipment.CHEST_SLOT);
                if (overrides.hasOverride(Equipment.CHEST_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.CHEST_SLOT).getId());
                } else if (torso != null && torso.getId() > 1) {
                    tempBuf.writeShort(0x200 + other.equipment.get(Equipment.CHEST_SLOT).getId());
                } else {
                    tempBuf.writeShort(0x100 + other.appearance.getTorso());
                }
                if (overrides.hasOverride(Equipment.SHIELD_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.SHIELD_SLOT).getId());
                } else if (other.equipment.get(Equipment.SHIELD_SLOT) != null) {
                    if (overrides.hasOverride(Equipment.WEAPON_SLOT) && overrides.get(Equipment.WEAPON_SLOT).isTwoHanded()) {
                        tempBuf.writeByte(0);
                    } else {
                        tempBuf.writeShort(0x200 + other.equipment.get(Equipment.SHIELD_SLOT).getId());
                    }
                } else {
                    tempBuf.writeByte(0);
                }
                if (torso != null && torso.getId() > 1 && torso.getEquipmentType().equals(EquipmentType.BODY) ||
                    overrides.hasOverride(Equipment.CHEST_SLOT) && overrides.get(Equipment.CHEST_SLOT).getEquipmentType().equals(EquipmentType.BODY)) {
                    tempBuf.writeByte(0);
                } else {
                    tempBuf.writeShort(0x100 + other.appearance.getArms());
                }
                if (overrides.hasOverride(Equipment.LEGS_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.LEGS_SLOT).getId());
                } else if (other.equipment.get(Equipment.LEGS_SLOT) != null) {
                    tempBuf.writeShort(0x200 + other.equipment.get(Equipment.LEGS_SLOT).getId());
                } else {
                    tempBuf.writeShort(0x100 + other.appearance.getLegs());
                }
                boolean head = true;
                boolean beard = true;
                if (helm != null && helm.getId() > 1) {
                    EquipmentType type = helm.getEquipmentType();
                    head = type.equals(EquipmentType.MASK) || type.equals(EquipmentType.HAT);
                    beard = type.equals(EquipmentType.FACE) || type.equals(EquipmentType.HAT);
                }
                if (overrides.hasOverride(Equipment.HEAD_SLOT)) {
                    final var override = overrides.get(Equipment.HEAD_SLOT).getEquipmentType();
                    head = override.equals(EquipmentType.MASK) || override.equals(EquipmentType.HAT);
                    beard = override.equals(EquipmentType.FACE) || override.equals(EquipmentType.HAT);
                }
                if (head) {
                    tempBuf.writeShort(0x100 + other.appearance.getHead());
                } else {
                    tempBuf.writeByte(0);
                }
                if (overrides.hasOverride(Equipment.HANDS_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.HANDS_SLOT).getId());
                } else if (other.equipment.get(Equipment.HANDS_SLOT) != null) {
                    tempBuf.writeShort(0x200 + other.equipment.get(Equipment.HANDS_SLOT).getId());
                } else {
                    tempBuf.writeShort(0x100 + other.appearance.getHands());
                }
                if (overrides.hasOverride(Equipment.FEET_SLOT)) {
                    tempBuf.writeShort(0x200 + overrides.get(Equipment.FEET_SLOT).getId());
                } else if (other.equipment.get(Equipment.FEET_SLOT) != null) {
                    tempBuf.writeShort(0x200 + other.equipment.get(Equipment.FEET_SLOT).getId());
                } else {
                    tempBuf.writeShort(0x100 + other.appearance.getFeet());
                }
                if (other.appearance.getGender().equals(Gender.MALE)) {
                    if (beard) {
                        tempBuf.writeShort(0x100 + other.appearance.getBeard());
                    } else {
                        tempBuf.writeByte(0);
                    }
                } else {
                    tempBuf.writeByte(0);
                }
            }
            tempBuf
                    .writeByte(other.appearance.getHairColor())
                    .writeByte(other.appearance.getTorsoColor())
                    .writeByte(other.appearance.getLegsColor())
                    .writeByte(other.appearance.getFeetColor())
                    .writeByte(other.appearance.getSkinColor())
                    .writeShort(other.mobAnimation.getStand())
                    .writeShort(other.mobAnimation.getTurn())
                    .writeShort(other.mobAnimation.getWalk())
                    .writeShort(other.mobAnimation.getTurn180())
                    .writeShort(other.mobAnimation.getTurn90CW())
                    .writeShort(other.mobAnimation.getTurn90CCW())
                    .writeShort(other.mobAnimation.getRun())
                    .writeLong(Utility.hash(other.getName()))
                    .writeString(other.playerTitle.getTitle())
                    .writeInt(other.playerTitle.getColor())
                    .writeString(other.clanChannel == null ? "" : other.clanChannel.getOwner())
                    .writeString(other.clanTag)
                    .writeString(other.clanTagColor)
                    .writeLong(Double.doubleToLongBits(other.skills.getCombatLevel()))
                    .writeByte(other.right.getCrown())
                    .writeShort(0);
            blockBuf.writeByte(tempBuf.content().writerIndex(), ByteModification.NEG);
            blockBuf.writeBytes(tempBuf.content());
        } finally {
            tempBuf.release();
        }
    }
References com.runehive.net.packet.PacketBuilder.alloc(), com.runehive.game.world.items.containers.equipment.Equipment.AMULET_SLOT, com.runehive.game.world.entity.mob.player.Player.appearance, com.runehive.game.world.items.containers.equipment.EquipmentType.BODY, com.runehive.game.world.items.containers.equipment.Equipment.CAPE_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.CHEST_SLOT, com.runehive.game.world.entity.mob.player.Player.clanChannel, com.runehive.game.world.entity.mob.player.Player.clanTag, com.runehive.game.world.entity.mob.player.Player.clanTagColor, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.equipment.EquipmentType.FACE, com.runehive.game.world.items.containers.equipment.Equipment.FEET_SLOT, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getArms(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getBeard(), com.runehive.content.combat.SkullHeadIconType.getCode(), com.runehive.content.tittle.PlayerTitle.getColor(), com.runehive.game.world.entity.skill.SkillManager.getCombatLevel(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.items.Item.getEquipmentType(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getFeet(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getFeetColor(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getGender(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getHairColor(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getHands(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getHead(), com.runehive.content.combat.Skulling.getHeadIconType(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getLegs(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getLegsColor(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.clanchannel.channel.ClanChannel.getOwner(), com.runehive.game.world.entity.mob.MobAnimation.getRun(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getSkinColor(), com.runehive.game.world.entity.mob.MobAnimation.getStand(), com.runehive.content.tittle.PlayerTitle.getTitle(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getTorso(), com.runehive.game.world.entity.mob.player.appearance.Appearance.getTorsoColor(), com.runehive.game.world.entity.mob.MobAnimation.getTurn(), com.runehive.game.world.entity.mob.MobAnimation.getTurn180(), com.runehive.game.world.entity.mob.MobAnimation.getTurn90CCW(), com.runehive.game.world.entity.mob.MobAnimation.getTurn90CW(), com.runehive.game.world.entity.mob.MobAnimation.getWalk(), com.runehive.game.world.items.containers.equipment.Equipment.HANDS_SLOT, com.runehive.util.Utility.hash(), com.runehive.game.world.items.containers.equipment.EquipmentType.HAT, com.runehive.game.world.items.containers.equipment.Equipment.HEAD_SLOT, com.runehive.game.world.entity.mob.player.Player.headIcon, com.runehive.game.world.items.containers.equipment.Equipment.HELM_SLOT, com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.items.containers.equipment.Equipment.LEGS_SLOT, com.runehive.game.world.entity.mob.player.appearance.Gender.MALE, com.runehive.game.world.items.containers.equipment.EquipmentType.MASK, com.runehive.game.world.entity.mob.Mob.mobAnimation, com.runehive.net.codec.ByteModification.NEG, com.runehive.game.world.entity.mob.player.Player.overrides, com.runehive.game.world.entity.mob.player.Player.playerTitle, com.runehive.game.world.entity.mob.player.Player.right, com.runehive.game.world.items.containers.equipment.Equipment.SHIELD_SLOT, com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.mob.player.Player.skulling, com.runehive.net.packet.OutgoingPacket.type, com.runehive.game.world.entity.mob.player.Player.valueIcon, com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT, com.runehive.net.packet.PacketBuilder.writeByte(), com.runehive.net.packet.PacketBuilder.writeBytes(), com.runehive.net.packet.PacketBuilder.writeInt(), com.runehive.net.packet.PacketBuilder.writeLong(), com.runehive.net.packet.PacketBuilder.writeShort(), and com.runehive.net.packet.PacketBuilder.writeString().
Referenced by updatePlayer().
appendChatMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask (PacketBuilder blockBuf, Player other) static private
Definition at line 253 of file SendPlayerUpdate.java.
{
        final ChatMessage message = other.getChatMessage().orElse(ChatMessage.create("Cabbage"));
        final byte[] encoded = message.getEncoded();
        blockBuf.writeShort(((message.getColor().getCode() & 0xFF) << 8) | (message.getEffect().getCode() & 0xFF), ByteOrder.LE)
        .writeByte(other.right.getCrown())
        .writeByte(encoded.length, ByteModification.NEG)
        .writeBytesReverse(encoded);
    }
References com.runehive.game.world.entity.mob.player.relations.ChatMessage.create(), com.runehive.game.world.entity.mob.player.Player.getChatMessage(), com.runehive.game.world.entity.mob.player.relations.ChatColor.getCode(), com.runehive.game.world.entity.mob.player.relations.ChatEffect.getCode(), com.runehive.game.world.entity.mob.player.relations.ChatMessage.getColor(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.entity.mob.player.relations.ChatMessage.getEffect(), com.runehive.game.world.entity.mob.player.relations.ChatMessage.getEncoded(), com.runehive.net.codec.ByteOrder.LE, com.runehive.net.codec.ByteModification.NEG, com.runehive.game.world.entity.mob.player.Player.right, com.runehive.net.packet.PacketBuilder.writeByte(), com.runehive.net.packet.PacketBuilder.writeBytesReverse(), and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updatePlayer().
appendFaceCoordinteMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendFaceCoordinteMask (Player other, PacketBuilder blockBuf) static private
Definition at line 227 of file SendPlayerUpdate.java.
{
        Position loc = other.facePosition;
        if (loc == null) {
            Position currentPos = other.getPosition();
            Direction currentDir = other.movement.lastDirection;
            blockBuf.writeShort(((currentPos.getX() + currentDir.getDirectionX()) << 1), ByteModification.ADD, ByteOrder.LE)
            .writeShort(((currentPos.getY() + currentDir.getDirectionY()) << 1) + 1, ByteOrder.LE);
        } else {
            blockBuf.writeShort((loc.getX() << 1) + 1, ByteModification.ADD, ByteOrder.LE)
            .writeShort((loc.getY() << 1) + 1, ByteOrder.LE);
        }
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.Mob.facePosition, com.runehive.game.world.entity.mob.Direction.getDirectionX(), com.runehive.game.world.entity.mob.Direction.getDirectionY(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.movement.Movement.lastDirection, com.runehive.net.codec.ByteOrder.LE, com.runehive.game.world.entity.mob.Mob.movement, and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updatePlayer().
appendFaceEntityMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendFaceEntityMask (Player other, PacketBuilder blockBuf) static private
Definition at line 214 of file SendPlayerUpdate.java.
{
        Mob mob = other.interactingWith;
        if (mob != null) {
            int index = mob.getIndex();
            if (mob.isPlayer()) {
                index += -32768;
            }
            blockBuf.writeShort(index, ByteOrder.LE);
        } else {
            blockBuf.writeShort(65535, ByteOrder.LE);
        }
    }
References com.runehive.game.world.entity.Entity.getIndex(), com.runehive.game.world.entity.mob.Mob.interactingWith, com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.net.codec.ByteOrder.LE, and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updatePlayer().
appendForceChatMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendForceChatMask (Player other, PacketBuilder blockBuf) static private
Definition at line 210 of file SendPlayerUpdate.java.
{
        blockBuf.writeString(other.forceChat);
    }
References com.runehive.game.world.entity.mob.Mob.forceChat, and com.runehive.net.packet.PacketBuilder.writeString().
Referenced by updatePlayer().
appendForceMovementMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendForceMovementMask (Player player, Player other, PacketBuilder blockBuf) static private
Definition at line 189 of file SendPlayerUpdate.java.
{
        final ForceMovement fm = other.getForceMovement();
        final Position lastPosition = player.lastPosition;
        final Position otherPosition = other.getPosition();
        final int startX = otherPosition.getLocalX(lastPosition);
        final int startY = otherPosition.getLocalY(lastPosition);
        final Position end = fm.getEnd();
        final int endX = end.getX();
        final int endY = end.getY();
        blockBuf.writeByte(startX, ByteModification.SUB)
        .writeByte(startY, ByteModification.SUB)
        .writeByte(startX + endX, ByteModification.SUB)
        .writeByte(startY + endY, ByteModification.SUB)
        .writeShort(fm.getSpeed(), ByteModification.ADD, ByteOrder.LE)
        .writeShort(fm.getReverseSpeed(), ByteModification.ADD)
        .writeByte(fm.getDirection(), ByteModification.SUB);
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.player.ForceMovement.getDirection(), com.runehive.game.world.entity.mob.player.ForceMovement.getEnd(), com.runehive.game.world.entity.mob.Mob.getForceMovement(), com.runehive.game.world.position.Position.getLocalX(), com.runehive.game.world.position.Position.getLocalY(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.player.ForceMovement.getReverseSpeed(), com.runehive.game.world.entity.mob.player.ForceMovement.getSpeed(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.Mob.lastPosition, com.runehive.net.codec.ByteOrder.LE, com.runehive.net.codec.ByteModification.SUB, com.runehive.net.packet.PacketBuilder.writeByte(), and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updatePlayer().
appendGraphicMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendGraphicMask (Player other, PacketBuilder blockBuf) static private
Definition at line 247 of file SendPlayerUpdate.java.
{
        Graphic graphic = other.getGraphic().orElse(Graphic.RESET);
        blockBuf.writeShort(graphic.getId(), ByteOrder.LE)
        .writeInt(graphic.getDelay() | graphic.getHeight());
    }
References com.runehive.game.Graphic.getDelay(), com.runehive.game.world.entity.mob.Mob.getGraphic(), com.runehive.game.Graphic.getHeight(), com.runehive.game.Graphic.getId(), com.runehive.net.codec.ByteOrder.LE, com.runehive.game.Graphic.RESET, com.runehive.net.packet.PacketBuilder.writeInt(), and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updatePlayer().
appendHitMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask (final Player player, final PacketBuilder blockBuf) static private
Definition at line 422 of file SendPlayerUpdate.java.
{
        Hit hit = player.firstHit;
        boolean multipleHits = hit.getMultipleHits() != null;
        blockBuf.writeByte(multipleHits ? 1 : 0);
        int max = player.getMaximumHealth() >= 500 ? 200 : 100;
        int health = player.getCurrentHealth() * max / player.getMaximumHealth();
        if (health > max) health = max;
        if(multipleHits) {
            blockBuf.writeByte(hit.getMultipleHits().length);
            for(int index = 0; index < hit.getMultipleHits().length; index++) {
                Hit currentHit = hit.getMultipleHits()[index];
                int id = currentHit.getHitsplat().getId();
                if (currentHit.getHitsplat() == Hitsplat.NORMAL && currentHit.getDamage() > 0) {
                    id++;
                }
                blockBuf.writeByte(currentHit.getDamage());
                blockBuf.writeByte(id, ByteModification.ADD);
                blockBuf.writeByte(currentHit.getHitIcon().getId());
            }
        } else {
            int id = hit.getHitsplat().getId();
            if (hit.getHitsplat() == Hitsplat.NORMAL && hit.getDamage() > 0) {
                id++;
            }
            blockBuf.writeByte(hit.getDamage());
            blockBuf.writeByte(id, ByteModification.ADD);
            blockBuf.writeByte(hit.getHitIcon().getId());
        }
        blockBuf.writeByte(health);
        blockBuf.writeByte(max, ByteModification.NEG);
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.Mob.firstHit, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.combat.hit.Hit.getDamage(), com.runehive.game.world.entity.combat.hit.Hit.getHitIcon(), com.runehive.game.world.entity.combat.hit.Hit.getHitsplat(), com.runehive.game.world.entity.combat.hit.HitIcon.getId(), com.runehive.game.world.entity.combat.hit.Hitsplat.getId(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.combat.hit.Hit.getMultipleHits(), com.runehive.net.codec.ByteModification.NEG, com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL, and com.runehive.net.packet.PacketBuilder.writeByte().
Referenced by updatePlayer().
appendSecondHitMask()
void com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask (final Player player, final PacketBuilder blockBuf) static private
Definition at line 467 of file SendPlayerUpdate.java.
{
        Hit hit = player.secondHit;
        boolean multipleHits = hit.getMultipleHits() != null;
        blockBuf.writeByte(multipleHits ? 1 : 0);
        int max = player.getMaximumHealth() >= 500 ? 200 : 100;
        int health = player.getCurrentHealth() * max / player.getMaximumHealth();
        if (health > max) health = max;
        if(multipleHits) {
            blockBuf.writeByte(hit.getMultipleHits().length);
            for(int index = 0; index < hit.getMultipleHits().length; index++) {
                Hit currentHit = hit.getMultipleHits()[index];
                int id = currentHit.getHitsplat().getId();
                if (currentHit.getHitsplat() == Hitsplat.NORMAL && currentHit.getDamage() > 0) {
                    id++;
                }
                blockBuf.writeByte(currentHit.getDamage());
                blockBuf.writeByte(id, ByteModification.ADD);
                blockBuf.writeByte(currentHit.getHitIcon().getId());
            }
        } else {
            int id = hit.getHitsplat().getId();
            if (hit.getHitsplat() == Hitsplat.NORMAL && hit.getDamage() > 0) {
                id++;
            }
            blockBuf.writeByte(hit.getDamage());
            blockBuf.writeByte(id, ByteModification.SUB);
            blockBuf.writeByte(hit.getHitIcon().getId());
        }
        blockBuf.writeByte(health);
        blockBuf.writeByte(max, ByteModification.NEG);
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.combat.hit.Hit.getDamage(), com.runehive.game.world.entity.combat.hit.Hit.getHitIcon(), com.runehive.game.world.entity.combat.hit.Hit.getHitsplat(), com.runehive.game.world.entity.combat.hit.HitIcon.getId(), com.runehive.game.world.entity.combat.hit.Hitsplat.getId(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.combat.hit.Hit.getMultipleHits(), com.runehive.net.codec.ByteModification.NEG, com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL, com.runehive.game.world.entity.mob.Mob.secondHit, com.runehive.net.codec.ByteModification.SUB, and com.runehive.net.packet.PacketBuilder.writeByte().
Referenced by updatePlayer().
encode()
boolean com.runehive.net.packet.out.SendPlayerUpdate.encode (Player player)
Reimplemented from com.runehive.net.packet.OutgoingPacket.
Definition at line 43 of file SendPlayerUpdate.java.
{
        if (player.regionChange) {
            player.send(new SendMapRegion());
        }
        final PacketBuilder blockBuf = PacketBuilder.alloc();
        try {
            builder.initializeAccess(AccessType.BIT);
            updateMovement(player, builder);
            if (player.isUpdateRequired()) {
                updatePlayer(blockBuf, player, player, UpdateState.UPDATE_SELF);
            }
            final Collection<Player> localPlayers =  World.getRegions().getLocalPlayers(player);
            builder.writeBits(8, player.viewport.getPlayersInViewport().size());
            for (Iterator<Player> itr = player.viewport.getPlayersInViewport().iterator(); itr.hasNext();) {
                Player other = itr.next();
                if (player.viewport.shouldRemove(other)) {
                    builder.writeBit(true);
                    builder.writeBits(2, 3);
                    itr.remove();
                } else {
                    updateMovement(other, builder);
                    if (other.isUpdateRequired()) {
                        updatePlayer(blockBuf, player, other, UpdateState.UPDATE_LOCAL);
                    }
                }
            }
            int added = 0;
            for (Player localPlayer : localPlayers) {
                if (player.viewport.getPlayersInViewport().size() >= Viewport.CAPACITY || added >= Viewport.ADD_THRESHOLD) {
                    break;
                }
                if (player.viewport.add(localPlayer)) {
                    added++;
                    addNewPlayer(builder, player, localPlayer);
                    updatePlayer(blockBuf, player, localPlayer, UpdateState.ADD_LOCAL);
                }
            }
            if (blockBuf.content().readableBytes() > 0) {
                builder.writeBits(11, 2047);
                builder.initializeAccess(AccessType.BYTE);
                builder.writeBuffer(blockBuf.content());
            } else {
                builder.initializeAccess(AccessType.BYTE);
            }
        } catch (Exception ex) {
            logger.error(String.format("error updating player=%s", player), ex);
        } finally {
            blockBuf.release();
        }
        return true;
    }
References com.runehive.game.world.entity.mob.Viewport.add(), com.runehive.net.packet.out.SendPlayerUpdate.UpdateState.ADD_LOCAL, com.runehive.game.world.entity.mob.Viewport.ADD_THRESHOLD, addNewPlayer(), com.runehive.net.packet.PacketBuilder.alloc(), com.runehive.net.codec.AccessType.BIT, com.runehive.net.packet.OutgoingPacket.builder, com.runehive.net.codec.AccessType.BYTE, com.runehive.game.world.entity.mob.Viewport.CAPACITY, com.runehive.game.world.region.RegionManager.getLocalPlayers(), com.runehive.game.world.entity.mob.Viewport.getPlayersInViewport(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.entity.mob.Mob.isUpdateRequired(), logger, com.runehive.game.world.entity.mob.Mob.regionChange, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.Viewport.shouldRemove(), com.runehive.net.packet.out.SendPlayerUpdate.UpdateState.UPDATE_LOCAL, com.runehive.net.packet.out.SendPlayerUpdate.UpdateState.UPDATE_SELF, updateMovement(), updatePlayer(), and com.runehive.game.world.entity.mob.player.Player.viewport.
updateMovement()
void com.runehive.net.packet.out.SendPlayerUpdate.updateMovement (Player player, PacketBuilder packetBuf) static private
Definition at line 509 of file SendPlayerUpdate.java.
{
        final boolean teleported = player.positionChange || player.teleportRegion;
        final boolean updateRequired = player.isUpdateRequired();
        if (teleported) {
            packetBuf.writeBit(true)
            .writeBits(2, 3)
            .writeBits(2, player.getHeight())
            .writeBits(1, player.regionChange ? 0 : 1)
            .writeBit(updateRequired)
            .writeBits(7, player.getPosition().getLocalY(player.lastPosition))
            .writeBits(7, player.getPosition().getLocalX(player.lastPosition));
        } else if (player.movement.getRunningDirection() != -1) {
            packetBuf.writeBit(true)
            .writeBits(2, 2)
            .writeBits(3, player.movement.getWalkingDirection())
            .writeBits(3, player.movement.getRunningDirection())
            .writeBit(player.isUpdateRequired());
        } else if (player.movement.getWalkingDirection() != -1) {
            packetBuf.writeBit(true)
            .writeBits(2, 1)
            .writeBits(3, player.movement.getWalkingDirection())
            .writeBit(player.isUpdateRequired());
        } else {
            if (updateRequired) {
                packetBuf.writeBit(true)
                .writeBits(2, 0);
            } else {
                packetBuf.writeBit(false);
            }
        }
    }
References com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.position.Position.getLocalX(), com.runehive.game.world.position.Position.getLocalY(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.movement.Movement.getRunningDirection(), com.runehive.game.world.entity.mob.movement.Movement.getWalkingDirection(), com.runehive.game.world.entity.mob.Mob.isUpdateRequired(), com.runehive.game.world.entity.mob.Mob.lastPosition, com.runehive.game.world.entity.mob.Mob.movement, com.runehive.game.world.entity.mob.Mob.regionChange, com.runehive.game.world.entity.mob.Mob.teleportRegion, com.runehive.net.packet.PacketBuilder.writeBit(), and com.runehive.net.packet.PacketBuilder.writeBits().
Referenced by encode().
updatePlayer()
void com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer (PacketBuilder blockBuf, Player player, Player other, UpdateState state) static private
Definition at line 118 of file SendPlayerUpdate.java.
{
        if (!other.isUpdateRequired()) {
            return;
        }
        int mask = 0;
        final EnumSet<UpdateFlag> updateFlags = other.updateFlags;
        for (UpdateFlag flag : UpdateFlag.playerOrder) {
            if (updateFlags.contains(flag) && flag.canApply(player, other, state)) {
                mask |= flag.playerMask;
            }
        }
        if (mask >= 0x100) {
            mask |= 0x40;
            blockBuf.writeByte(mask & 0xFF);
            blockBuf.writeByte(mask >> 8);
        } else {
            blockBuf.writeByte(mask);
        }
        // TODO replace the checks.
       /* for (UpdateFlag flag : UpdateFlag.playerOrder) {
            if (UpdateFlag.containsPlayer(mask, flag)) {
            }
        }*/
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.FORCE_MOVEMENT)) {
            appendForceMovementMask(player, other, blockBuf);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.GRAPHICS)) {
            appendGraphicMask(other, blockBuf);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.ANIMATION)) {
            appendAnimationMask(other, blockBuf);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.FORCED_CHAT)) {
            appendForceChatMask(other, blockBuf);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.CHAT)) {
            appendChatMask(blockBuf, other);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.INTERACT)) {
            appendFaceEntityMask(other, blockBuf);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.APPEARANCE)) {
            appendAppearanceMask(other, blockBuf);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.FACE_COORDINATE)) {
            appendFaceCoordinteMask(other, blockBuf);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.FIRST_HIT)) {
            appendHitMask(other, blockBuf);
        }
        if (UpdateFlag.containsPlayer(mask, UpdateFlag.SECOND_HIT)) {
            appendSecondHitMask(other, blockBuf);
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.ANIMATION, com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, appendAnimationMask(), appendAppearanceMask(), appendChatMask(), appendFaceCoordinteMask(), appendFaceEntityMask(), appendForceChatMask(), appendForceMovementMask(), appendGraphicMask(), appendHitMask(), appendSecondHitMask(), com.runehive.game.world.entity.mob.UpdateFlag.canApply(), com.runehive.game.world.entity.mob.UpdateFlag.CHAT, com.runehive.game.world.entity.mob.UpdateFlag.containsPlayer(), com.runehive.game.world.entity.mob.UpdateFlag.FACE_COORDINATE, com.runehive.game.world.entity.mob.UpdateFlag.FIRST_HIT, com.runehive.game.world.entity.mob.UpdateFlag.FORCE_MOVEMENT, com.runehive.game.world.entity.mob.UpdateFlag.FORCED_CHAT, com.runehive.game.world.entity.mob.UpdateFlag.GRAPHICS, com.runehive.game.world.entity.mob.UpdateFlag.INTERACT, com.runehive.game.world.entity.mob.Mob.isUpdateRequired(), com.runehive.game.world.entity.mob.UpdateFlag.playerMask, com.runehive.game.world.entity.mob.UpdateFlag.playerOrder, com.runehive.game.world.entity.mob.UpdateFlag.SECOND_HIT, com.runehive.game.world.entity.mob.Mob.updateFlags, and com.runehive.net.packet.PacketBuilder.writeByte().
Referenced by encode().
Member Data Documentation
logger
final Logger com.runehive.net.packet.out.SendPlayerUpdate.logger = LogManager.getLogger(SendPlayerUpdate.class) static private
Definition at line 36 of file SendPlayerUpdate.java.
Referenced by encode().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/out/SendPlayerUpdate.java