RuneHive-Game: com.runehive.game.world.entity.mob.player.InterfaceManager Class Reference
com.runehive.game.world.entity.mob.player.InterfaceManager Class Reference
Contains information about the state of interfaces enter in the client.
Public Member Functions
void close ()
Clears the player's screen.
void close (boolean walkable)
Handles clearing the screen.
void close (int interfaceId)
int getDialogue ()
Gets the dialogue interface.
int getMain ()
gets the current main interface.
int getSidebar (int tab)
int getWalkable ()
Gets the walkable interface.
boolean hasAnyOpen (int... ids)
boolean hasSidebar (int id)
boolean isClear ()
Checks if the player's screen is clear.
boolean isDialogueClear ()
Checks if the dialogue interface is clear.
boolean isInterfaceOpen (int id)
Checks if a certain interface is enter.
boolean isMainClear ()
Checks if the main interface is clear.
boolean isSidebar (int tab, int id)
void open (int identification)
Opens an interface for the player.
void open (int identification, boolean secure)
Opens an itemcontainer for the player.
void openInventory (int identification, int overlay)
Opens an inventory interface for the player.
void openWalkable (int identification)
Opens a walkable-itemcontainer for the player.
void setDialogue (int dialogueInterface)
Sets the dialogue interface.
void setMain (int currentInterface)
Sets the current interface.
void setSidebar (int tab, int id)
void setWalkable (int walkableInterface)
Sets the walkable interface.
Package Functions
InterfaceManager (Player player)
Creates a new InterfaceManager.
Private Attributes
int dialogue = -1
The current dialogue.
int main = -1
The current main interface.
int overlay = -1
The current overlay interface.
Player player
The player instance.
int[] sidebars = new int[15]
int walkable = -1
The current walkable-interface.
Detailed Description
Contains information about the state of interfaces enter in the client.
Author
Daniel
Definition at line 14 of file InterfaceManager.java.
Constructor & Destructor Documentation
InterfaceManager()
com.runehive.game.world.entity.mob.player.InterfaceManager.InterfaceManager (Player player) package
Creates a new InterfaceManager.
Definition at line 34 of file InterfaceManager.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
close() [1/3]
void com.runehive.game.world.entity.mob.player.InterfaceManager.close ()
Clears the player's screen.
Definition at line 98 of file InterfaceManager.java.
{
        close(true);
    }
References close().
Referenced by close(), and close().
close() [2/3]
void com.runehive.game.world.entity.mob.player.InterfaceManager.close (boolean walkable)
Handles clearing the screen.
Definition at line 103 of file InterfaceManager.java.
{
        com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.requestReset(player);
        if (player.isBot) {
            return;
        }
        if (player.attributes.has("SHOP")) {
            Store.closeShop(player);
        }
        if (player.attributes.is("BANK_KEY")) {
            player.bank.close();
        }
        if (player.attributes.is("PRICE_CHECKER_KEY")) {
            player.priceChecker.close();
        }
        if (player.attributes.is("TRADE_KEY")) {
            player.exchangeSession.reset(ExchangeSessionType.TRADE);
        }
        if (player.attributes.is("DUEL_KEY")) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
        }
        if (player.attributes.is("DONATOR_DEPOSIT_KEY")) {
            player.donatorDeposit.close();
        }
        if(main == TradingPost.BUYING_PAGE_INTERFACE_ID) {
            player.tradingPost.cleanUp();
        }
        if (walkable) {
            openWalkable(-1);
        }
        main = -1;
        dialogue = -1;
        player.dialogueFactory.clear();
        player.send(new SendRemoveInterface());
//        player.send(new SendString("[CLOSE_MENU]", 0));
        setSidebar(Config.LOGOUT_TAB, 2449);
    }
References com.runehive.content.tradingpost.TradingPost.BUYING_PAGE_INTERFACE_ID, com.runehive.content.store.Store.closeShop(), dialogue, com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.Config.LOGOUT_TAB, main, openWalkable(), player, setSidebar(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.TRADE, and walkable.
close() [3/3]
void com.runehive.game.world.entity.mob.player.InterfaceManager.close (int interfaceId)
Definition at line 91 of file InterfaceManager.java.
{
        if (isInterfaceOpen(interfaceId)) {
            close();
        }
    }
References close(), and isInterfaceOpen().
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack(), com.runehive.content.store.impl.PersonalStore.changeName(), com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.agility.Agility.clickButton(), com.runehive.content.skill.impl.crafting.Crafting.clickButton(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), com.runehive.content.store.currency.impl.ClanPointCurrency.currencyAmount(), com.runehive.net.packet.out.SendFadeScreen.encode(), com.runehive.net.packet.in.CloseInterfacePacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.game.world.entity.mob.Mob.move(), com.runehive.content.skill.impl.crafting.impl.Spinning.open(), com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage(), com.runehive.content.store.currency.impl.ClanPointCurrency.recieveCurrency(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ClanRankDialogue.setRank(), com.runehive.content.ai.LazyAIManager.showGptInstructions(), com.runehive.content.ai.LazyAIManager.showGptInstructionsWithGreeting(), com.runehive.content.skill.impl.smithing.Smelting.smelt(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse(), com.runehive.content.store.currency.impl.ClanPointCurrency.takeCurrency(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
getDialogue()
int com.runehive.game.world.entity.mob.player.InterfaceManager.getDialogue ()
Gets the dialogue interface.
Definition at line 197 of file InterfaceManager.java.
{
        return dialogue;
    }
References dialogue.
getMain()
int com.runehive.game.world.entity.mob.player.InterfaceManager.getMain ()
gets the current main interface.
Definition at line 192 of file InterfaceManager.java.
{
        return main;
    }
References main.
getSidebar()
int com.runehive.game.world.entity.mob.player.InterfaceManager.getSidebar (int tab)
Definition at line 216 of file InterfaceManager.java.
{
        if (tab > sidebars.length) {
            return -1;
        }
        return sidebars[tab];
    }
References sidebars.
getWalkable()
int com.runehive.game.world.entity.mob.player.InterfaceManager.getWalkable ()
Gets the walkable interface.
Definition at line 207 of file InterfaceManager.java.
{
        return walkable;
    }
References walkable.
Referenced by com.runehive.content.wintertodt.Wintertodt.send().
hasAnyOpen()
boolean com.runehive.game.world.entity.mob.player.InterfaceManager.hasAnyOpen (int... ids)
Definition at line 163 of file InterfaceManager.java.
{
        for (int id : ids) {
            if (main == id)
                return true;
        }
        return false;
    }
References main.
hasSidebar()
boolean com.runehive.game.world.entity.mob.player.InterfaceManager.hasSidebar (int id)
Definition at line 227 of file InterfaceManager.java.
{
        for (int sidebar : sidebars) {
            if (sidebar == id) {
                return true;
            }
        }
        return false;
    }
References sidebars.
isClear()
boolean com.runehive.game.world.entity.mob.player.InterfaceManager.isClear ()
Checks if the player's screen is clear.
Definition at line 172 of file InterfaceManager.java.
{
        return main == -1 && dialogue == -1 && walkable == -1;
    }
References dialogue, main, and walkable.
Referenced by com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), and com.runehive.net.packet.in.WieldItemPacketListener.handlePacket().
isDialogueClear()
boolean com.runehive.game.world.entity.mob.player.InterfaceManager.isDialogueClear ()
Checks if the dialogue interface is clear.
Definition at line 182 of file InterfaceManager.java.
{
        return dialogue == -1;
    }
References dialogue.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack(), and com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate().
isInterfaceOpen()
boolean com.runehive.game.world.entity.mob.player.InterfaceManager.isInterfaceOpen (int id)
Checks if a certain interface is enter.
Definition at line 159 of file InterfaceManager.java.
{
        return main == id;
    }
References main.
Referenced by com.runehive.content.store.impl.PersonalStore.add(), close(), com.runehive.content.store.Store.closeShop(), com.runehive.content.store.Store.exchange(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.content.clanchannel.content.ClanShowcase.select(), and com.runehive.content.store.impl.PersonalStore.setValue().
isMainClear()
boolean com.runehive.game.world.entity.mob.player.InterfaceManager.isMainClear ()
Checks if the main interface is clear.
Definition at line 177 of file InterfaceManager.java.
{
        return main == -1;
    }
References main.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.attack(), and com.runehive.game.world.entity.combat.Combat< T extends Mob >.retaliate().
isSidebar()
boolean com.runehive.game.world.entity.mob.player.InterfaceManager.isSidebar (int tab, int id)
Definition at line 223 of file InterfaceManager.java.
{
        return tab <= sidebars.length && sidebars[tab] == id;
    }
References sidebars.
Referenced by com.runehive.content.activity.panel.ActivityPanel.update().
open() [1/2]
void com.runehive.game.world.entity.mob.player.InterfaceManager.open (int identification)
Opens an interface for the player.
Definition at line 39 of file InterfaceManager.java.
{
        open(identification, true);
    }
References open().
Referenced by com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember(), com.runehive.content.collectionlog.CollectionLog.open(), com.runehive.content.DropDisplay.open(), com.runehive.content.famehall.FameHandler.open(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.content.Obelisks.open(), com.runehive.content.ProfileViewer.open(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.simulator.DropSimulator.open(), com.runehive.content.skill.impl.construction.BuildableInterface.open(), com.runehive.content.skill.impl.crafting.impl.Glass.open(), com.runehive.content.skill.impl.crafting.impl.Jewellery.open(), com.runehive.content.skill.impl.crafting.impl.Tanning.open(), com.runehive.content.StarterKit.open(), com.runehive.content.teleport.TeleportHandler.open(), com.runehive.content.tittle.TitleManager.open(), com.runehive.content.WellOfGoodwill.open(), open(), com.runehive.content.pet.Pets.openInsurance(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.pet.Pets.openLostPets(), com.runehive.content.store.impl.PersonalStore.openMenu(), com.runehive.content.store.impl.PersonalStore.openPanel(), com.runehive.content.clanchannel.content.ClanShowcase.openShowcase(), com.runehive.content.clanchannel.channel.ClanManagement.showBanned(), and com.runehive.content.skill.impl.crafting.Crafting.useItem().
open() [2/2]
void com.runehive.game.world.entity.mob.player.InterfaceManager.open (int identification, boolean secure)
Opens an itemcontainer for the player.
Definition at line 44 of file InterfaceManager.java.
{
        if (secure) {
            if (player.isBot || main == identification) {
                return;
            }
            if (player.getCombat().inCombat()) {
                player.send(new SendMessage("You can't do this right now!"));
                return;
            }
            if (player.dialogueFactory.isActive() || player.dialogueFactory.isOption()) {
                player.dialogueFactory.clear();
            }
        }
        main = identification;
        player.movement.reset();
        player.send(new SendInterface(identification));
        player.send(new SendString("[CLOSE_MENU]", 0));
        setSidebar(Config.LOGOUT_TAB, -1);
    }
References com.runehive.Config.LOGOUT_TAB, main, player, and setSidebar().
openInventory()
void com.runehive.game.world.entity.mob.player.InterfaceManager.openInventory (int identification, int overlay)
Opens an inventory interface for the player.
Definition at line 77 of file InterfaceManager.java.
{
        if (player.isBot || main == identification && this.overlay == overlay) {
            return;
        }
        main = identification;
        this.overlay = overlay;
        player.movement.reset();
        player.send(new SendString("[CLOSE_MENU]", 0));
        player.send(new SendInventoryInterface(identification, overlay));
        setSidebar(Config.LOGOUT_TAB, -1);
    }
References com.runehive.Config.LOGOUT_TAB, main, overlay, player, and setSidebar().
Referenced by com.runehive.content.store.impl.DefaultStore.open(), com.runehive.content.store.impl.PersonalStore.open(), com.runehive.content.store.impl.RecipeForDisasterStore.open(), and com.runehive.content.store.impl.SkillcapeStore.open().
openWalkable()
void com.runehive.game.world.entity.mob.player.InterfaceManager.openWalkable (int identification)
Opens a walkable-itemcontainer for the player.
Definition at line 68 of file InterfaceManager.java.
{
        if (walkable == identification) {
            return;
        }
        walkable = identification;
        player.send(new SendWalkableInterface(identification));
    }
References player, and walkable.
Referenced by close(), and com.runehive.content.wintertodt.Wintertodt.send().
setDialogue()
void com.runehive.game.world.entity.mob.player.InterfaceManager.setDialogue (int dialogueInterface)
Sets the dialogue interface.
Definition at line 202 of file InterfaceManager.java.
{
        this.dialogue = dialogueInterface;
    }
Referenced by com.runehive.net.packet.out.SendChatBoxInterface.encode().
setMain()
void com.runehive.game.world.entity.mob.player.InterfaceManager.setMain (int currentInterface)
Sets the current interface.
Definition at line 187 of file InterfaceManager.java.
{
        this.main = currentInterface;
    }
setSidebar()
void com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar (int tab, int id)
Definition at line 149 of file InterfaceManager.java.
{
        if (sidebars[tab] == id && id != -1) {
            return;
        }
        sidebars[tab] = id;
        player.send(new SendSideBarInterface(tab, id));
    }
References player, and sidebars.
Referenced by com.runehive.content.activity.panel.ActivityPanel.clear(), com.runehive.game.world.entity.combat.magic.Autocast.clickButton(), close(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.clanchannel.channel.ClanChannelHandler.manage(), com.runehive.game.plugin.PluginContext.onClick(), open(), openInventory(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.game.world.entity.combat.magic.Autocast.setAutocast(), and com.runehive.content.activity.panel.ActivityPanel.update().
setWalkable()
void com.runehive.game.world.entity.mob.player.InterfaceManager.setWalkable (int walkableInterface)
Sets the walkable interface.
Definition at line 212 of file InterfaceManager.java.
{
        this.walkable = walkableInterface;
    }
Member Data Documentation
dialogue
int com.runehive.game.world.entity.mob.player.InterfaceManager.dialogue = -1 private
The current dialogue.
Definition at line 29 of file InterfaceManager.java.
Referenced by close(), getDialogue(), isClear(), and isDialogueClear().
main
int com.runehive.game.world.entity.mob.player.InterfaceManager.main = -1 private
The current main interface.
Definition at line 20 of file InterfaceManager.java.
Referenced by close(), getMain(), hasAnyOpen(), isClear(), isInterfaceOpen(), isMainClear(), open(), and openInventory().
overlay
int com.runehive.game.world.entity.mob.player.InterfaceManager.overlay = -1 private
The current overlay interface.
Definition at line 23 of file InterfaceManager.java.
Referenced by openInventory().
player
Player com.runehive.game.world.entity.mob.player.InterfaceManager.player private
The player instance.
Definition at line 17 of file InterfaceManager.java.
Referenced by close(), InterfaceManager(), open(), openInventory(), openWalkable(), and setSidebar().
sidebars
int [] com.runehive.game.world.entity.mob.player.InterfaceManager.sidebars = new int[15] private
Definition at line 31 of file InterfaceManager.java.
Referenced by getSidebar(), hasSidebar(), isSidebar(), and setSidebar().
walkable
int com.runehive.game.world.entity.mob.player.InterfaceManager.walkable = -1 private
The current walkable-interface.
Definition at line 26 of file InterfaceManager.java.
Referenced by close(), getWalkable(), isClear(), and openWalkable().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/InterfaceManager.java