RuneHive-Game: com.runehive.content.itemaction.impl.DrillDemonBox Class Reference
com.runehive.content.itemaction.impl.DrillDemonBox Class Reference
Public Member Functions
int delay ()
The item click delay of the action.
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
String message (Item item)
The message of the action.
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean itemOnItem (Player player, Item first, Item second)
String toString ()
Static Private Attributes
static final Item[] CAMO_CLOTHING = {new Item(6656), new Item(6654), new Item(6655)}
static final EmoteUnlockable[] EMOTES = {EmoteUnlockable.SIT_UP, EmoteUnlockable.PUSH_UP, EmoteUnlockable.JUMPING_JACK, EmoteUnlockable.JOG}
Detailed Description
Definition at line 11 of file DrillDemonBox.java.
Member Function Documentation
delay()
int com.runehive.content.itemaction.impl.DrillDemonBox.delay ()
The item click delay of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 28 of file DrillDemonBox.java.
                       {
        return 2;
    }
inventory()
boolean com.runehive.content.itemaction.impl.DrillDemonBox.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 33 of file DrillDemonBox.java.
{
        if (opcode != 1)
            return false;
        player.inventory.remove(item);
        int random = Utility.random(1, 5);
        switch (random) {
            case 1:
            case 2:
                if (!EmoteHandler.containsAll(player, EMOTES)) {
                    EmoteUnlockable emote = EmoteHandler.selectRandom(player, EMOTES);
                    player.emoteUnlockable.add(emote);
                    EmoteHandler.refresh(player);
                    player.send(new SendMessage("You have unlocked the " + Utility.formatName(emote.name().toLowerCase().replace("_", "")) + " emote!"));
                    return true;
                }
                int random2 = Utility.random(1, 2);
                if (random2 == 1) {
                    Item clothing = Utility.randomElement(CAMO_CLOTHING);
                    player.inventory.add(clothing);
                    player.send(new SendMessage("You have received the " + clothing.getName() + " item!"));
                } else {
                    player.inventory.add(new Item(995, 75000));
                }
                break;
            case 3:
            case 4:
                player.inventory.add(Utility.randomElement(CAMO_CLOTHING));
                break;
            case 5:
                player.inventory.add(new Item(995, 75000));
                break;
        }
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), CAMO_CLOTHING, com.runehive.content.emote.EmoteHandler.containsAll(), EMOTES, com.runehive.game.world.entity.mob.player.Player.emoteUnlockable, com.runehive.util.Utility.formatName(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), com.runehive.content.emote.EmoteHandler.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.content.emote.EmoteHandler.selectRandom(), and com.runehive.game.world.entity.mob.player.Player.send().
message()
String com.runehive.content.itemaction.impl.DrillDemonBox.message (Item item)
The message of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 23 of file DrillDemonBox.java.
{
        return "You open the Drill demon box...";
    }
name()
String com.runehive.content.itemaction.impl.DrillDemonBox.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 18 of file DrillDemonBox.java.
{
        return "Drill demon box";
    }
Member Data Documentation
CAMO_CLOTHING
final Item [] com.runehive.content.itemaction.impl.DrillDemonBox.CAMO_CLOTHING = {new Item(6656), new Item(6654), new Item(6655)} static private
Definition at line 15 of file DrillDemonBox.java.
{new Item(6656), new Item(6654), new Item(6655)};
Referenced by inventory().
EMOTES
final EmoteUnlockable [] com.runehive.content.itemaction.impl.DrillDemonBox.EMOTES = {EmoteUnlockable.SIT_UP, EmoteUnlockable.PUSH_UP, EmoteUnlockable.JUMPING_JACK, EmoteUnlockable.JOG} static private
Definition at line 13 of file DrillDemonBox.java.
{EmoteUnlockable.SIT_UP, EmoteUnlockable.PUSH_UP, EmoteUnlockable.JUMPING_JACK, EmoteUnlockable.JOG};
Referenced by inventory().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/DrillDemonBox.java