RuneHive-Game: com.runehive.content.skill.impl.slayer.Slayer Class Reference
com.runehive.content.skill.impl.slayer.Slayer Class Reference
Handles the slayer skill.
Public Member Functions
void activate (Npc npc, int killAmount)
Activates killing a slayer npc.
void assign (TaskDifficulty difficulty)
Assigns a slayer task to the player.
void block ()
Blocks the current assigned slayer task.
boolean cancel (boolean requiresCost)
Cancel's the current assigned slayer task.
void confirm (int button)
Opens the confirm itemcontainer for purchasing a perk.
int getAmount ()
int getAssigned ()
List< SlayerTask > getBlocked ()
int getPoints ()
SlayerTask getTask ()
int getTotalAssigned ()
int getTotalCancelled ()
int getTotalCompleted ()
int getTotalPoints ()
Set< SlayerUnlockable > getUnlocked ()
void open (SlayerTab tab)
Opens the slayer itemcontainer.
void purchase ()
Handles purchasing a slayer perk.
void setAmount (int amount)
void setAssigned (int assigned)
void setBlocked (List< SlayerTask > blocked)
void setPoints (int points)
void setTask (SlayerTask task)
void setTotalAssigned (int totalAssigned)
void setTotalCancelled (int totalCancelled)
void setTotalCompleted (int totalCompleted)
void setTotalPoints (int totalPoints)
void setUnlocked (Set< SlayerUnlockable > unlocked)
Slayer (Player player)
Constructs a new Slayer.
void store (int slot, int amount, boolean value)
Handles purchasing items from the slayer shop.
void unblock (int index)
Unblocks the slayer task.
Static Package Functions
[static initializer]
Static Package Attributes
static Item[] ITEMS = new Item[STORE_ITEMS.length]
Private Attributes
int amount
The current slayer task amount.
int assigned
The slayer task assigned amount.
List< SlayerTask > blocked = new LinkedList<>()
The list of all blocked slayer tasks.
Player player
The player instance.
int points
The slayer points.
SlayerTask task
The slayer task.
int totalAssigned
The total tasks assigned.
int totalCancelled
The total tasks cancelled.
int totalCompleted
The total tasks completed.
int totalPoints
The total points accumulated.
Set< SlayerUnlockable > unlocked = new HashSet<>(SlayerUnlockable.values().length)
The Set of all unlockable slayer perks.
Static Private Attributes
static final StoreItem[] STORE_ITEMS
Detailed Description
Handles the slayer skill.
Author
Daniel
Definition at line 26 of file Slayer.java.
Constructor & Destructor Documentation
Slayer()
com.runehive.content.skill.impl.slayer.Slayer.Slayer (Player player)
Constructs a new Slayer.
Definition at line 61 of file Slayer.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
[static initializer]()
com.runehive.content.skill.impl.slayer.Slayer.[static initializer] static package
References ITEMS, and STORE_ITEMS.
activate()
void com.runehive.content.skill.impl.slayer.Slayer.activate (Npc npc, int killAmount)
Activates killing a slayer npc.
Definition at line 171 of file Slayer.java.
{
        if (task != null && task.valid(npc.getName())) {
            amount -= killAmount;
            if (amount <= 0) {
                int rewardPoints = SlayerTask.getPoints(task.getDifficulty());
                points += rewardPoints;
                player.skills.addExperience(Skill.SLAYER, SlayerTask.getCompletionExperience(task.getDifficulty()));
                task = null;
                amount = 0;
                totalCompleted++;
                player.message("Congratulations, you have completed your assigned task! You have earned " + rewardPoints + " slayer points!");
                AchievementHandler.activate(player, AchievementKey.SLAYER_TASKS);
                return;
            }
            player.skills.addExperience(Skill.SLAYER, npc.getMaximumHealth() * Config.SLAYER_MODIFICATION);
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), amount, com.runehive.content.skill.impl.slayer.SlayerTask.getCompletionExperience(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.mob.npc.Npc.getName(), com.runehive.content.skill.impl.slayer.SlayerTask.getPoints(), player, points, com.runehive.game.world.entity.skill.Skill.SLAYER, com.runehive.Config.SLAYER_MODIFICATION, com.runehive.content.achievement.AchievementKey.SLAYER_TASKS, task, and totalCompleted.
Referenced by com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath().
assign()
void com.runehive.content.skill.impl.slayer.Slayer.assign (TaskDifficulty difficulty)
Assigns a slayer task to the player.
Definition at line 73 of file Slayer.java.
{
        if (task != null) {
            player.message("You currently have a task assigned!");
            return;
        }
        SlayerTask toAssign = SlayerTask.assign(player, difficulty);
        if (toAssign == null) {
            player.dialogueFactory.sendNpcChat(6797, "There are no tasks available for you!", "This can be because you do not have a valid", "slayer level or you haven't unlocked any tasks.");
            return;
        }
        int assignment = 0;
        if (toAssign.getDifficulty() == TaskDifficulty.EASY) {
            assignment = Utility.random(35, 75);
        } else if (toAssign.getDifficulty() == TaskDifficulty.MEDIUM) {
            assignment = Utility.random(45, 80);
        } else if (toAssign.getDifficulty() == TaskDifficulty.HARD) {
            assignment = Utility.random(60, 100);
        } else if (toAssign.getDifficulty() == TaskDifficulty.BOSS) {
            assignment = Utility.random(30, 50);
        }
        totalAssigned++;
        task = toAssign;
        amount = assignment;
        SlayerTab.refresh(player, player.attributes.get("SLAYER_KEY", SlayerTab.class));
        player.message("You have been assigned " + amount + "x " + task.getName() + ".");
    }
References amount, com.runehive.content.skill.impl.slayer.SlayerTask.assign(), com.runehive.content.skill.impl.slayer.TaskDifficulty.BOSS, com.runehive.content.skill.impl.slayer.TaskDifficulty.EASY, com.runehive.content.skill.impl.slayer.SlayerTask.getDifficulty(), com.runehive.content.skill.impl.slayer.TaskDifficulty.HARD, com.runehive.content.skill.impl.slayer.TaskDifficulty.MEDIUM, player, com.runehive.util.Utility.random(), com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), task, and totalAssigned.
block()
void com.runehive.content.skill.impl.slayer.Slayer.block ()
Blocks the current assigned slayer task.
Definition at line 128 of file Slayer.java.
{
        if (task == null) {
            player.message("You do not have a task to block.");
            return;
        }
        if (points < 100) {
            player.message("You need 100 slayer points to block a task.");
            return;
        }
        if (blocked.size() >= 5) {
            player.message("You can only block up to 5 tasks.");
            return;
        }
        if (blocked.contains(task)) {
            player.message("This task is already blocked... but how did you get it again? mmm...");
            return;
        }
        blocked.add(task);
        points -= 100;
        task = null;
        amount = 0;
        totalCancelled++;
        SlayerTab.refresh(player, player.attributes.get("SLAYER_KEY", SlayerTab.class));
        player.message("Your task has been blocked.");
    }
References amount, blocked, player, points, com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), task, and totalCancelled.
cancel()
boolean com.runehive.content.skill.impl.slayer.Slayer.cancel (boolean requiresCost)
Cancel's the current assigned slayer task.
Definition at line 105 of file Slayer.java.
{
        if (task == null) {
            player.message("You do not have a task to cancel.");
            return false;
        }
        if (requiresCost) {
            int cost = PlayerRight.isDonator(player) ? 20 : 25;
            if (points < cost) {
                player.message("You need " + cost + " slayer points to cancel a task.");
                return false;
            }
            points -= cost;
        }
        task = null;
        amount = 0;
        totalCancelled++;
        SlayerTab.refresh(player, player.attributes.get("SLAYER_KEY", SlayerTab.class));
        player.message("Your task has been cancelled.");
        return true;
    }
References amount, com.runehive.game.world.entity.mob.player.PlayerRight.isDonator(), player, points, com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), task, and totalCancelled.
confirm()
void com.runehive.content.skill.impl.slayer.Slayer.confirm (int button)
Opens the confirm itemcontainer for purchasing a perk.
Definition at line 190 of file Slayer.java.
{
        int index = Math.abs((-18625 - button) / 6);
        if (!SlayerUnlockable.get(index).isPresent())
            return;
        SlayerUnlockable unlockable = SlayerUnlockable.get(index).get();
        player.attributes.set("SLAYER_CONFIRM_KEY", unlockable);
        open(SlayerTab.CONFIRM);
    }
References com.runehive.content.skill.impl.slayer.SlayerTab.CONFIRM, com.runehive.content.skill.impl.slayer.SlayerUnlockable.get(), open(), and player.
getAmount()
int com.runehive.content.skill.impl.slayer.Slayer.getAmount ()
Definition at line 303 of file Slayer.java.
{
        return amount;
    }
References amount.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getAssigned()
int com.runehive.content.skill.impl.slayer.Slayer.getAssigned ()
Definition at line 311 of file Slayer.java.
{
        return assigned;
    }
References assigned.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getBlocked()
List< SlayerTask > com.runehive.content.skill.impl.slayer.Slayer.getBlocked ()
Definition at line 351 of file Slayer.java.
{
        return blocked;
    }
References blocked.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTask.asList(), and com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getPoints()
int com.runehive.content.skill.impl.slayer.Slayer.getPoints ()
Definition at line 287 of file Slayer.java.
{
        return points;
    }
References points.
Referenced by com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.store.currency.impl.SlayerPointCurrency.currencyAmount(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.content.store.currency.impl.SlayerPointCurrency.recieveCurrency(), com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), store(), and com.runehive.content.store.currency.impl.SlayerPointCurrency.takeCurrency().
getTask()
SlayerTask com.runehive.content.skill.impl.slayer.Slayer.getTask ()
Definition at line 295 of file Slayer.java.
{
        return task;
    }
References task.
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.SlayerHelmListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyMagicLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyRangedLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyStrengthLevel(), com.runehive.game.world.entity.combat.attack.listener.item.SlayerHelmListener.modifyStrengthLevel(), and com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getTotalAssigned()
int com.runehive.content.skill.impl.slayer.Slayer.getTotalAssigned ()
Definition at line 319 of file Slayer.java.
{
        return totalAssigned;
    }
References totalAssigned.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getTotalCancelled()
int com.runehive.content.skill.impl.slayer.Slayer.getTotalCancelled ()
Definition at line 335 of file Slayer.java.
{
        return totalCancelled;
    }
References totalCancelled.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getTotalCompleted()
int com.runehive.content.skill.impl.slayer.Slayer.getTotalCompleted ()
Definition at line 327 of file Slayer.java.
{
        return totalCompleted;
    }
References totalCompleted.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getTotalPoints()
int com.runehive.content.skill.impl.slayer.Slayer.getTotalPoints ()
Definition at line 343 of file Slayer.java.
{
        return totalPoints;
    }
References totalPoints.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getUnlocked()
Set< SlayerUnlockable > com.runehive.content.skill.impl.slayer.Slayer.getUnlocked ()
Definition at line 359 of file Slayer.java.
{
        return unlocked;
    }
References unlocked.
Referenced by com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), and com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
open()
void com.runehive.content.skill.impl.slayer.Slayer.open (SlayerTab tab)
Opens the slayer itemcontainer.
Definition at line 66 of file Slayer.java.
{
        SlayerTab.refresh(player, tab);
        player.attributes.set("SLAYER_KEY", tab);
        player.interfaceManager.open(tab.getIdentification());
    }
References com.runehive.content.skill.impl.slayer.SlayerTab.getIdentification(), player, and com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
Referenced by confirm(), com.runehive.game.plugin.PluginContext.onClick(), purchase(), and com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues().
purchase()
void com.runehive.content.skill.impl.slayer.Slayer.purchase ()
Handles purchasing a slayer perk.
Definition at line 200 of file Slayer.java.
{
        SlayerUnlockable unlockable = player.attributes.get("SLAYER_CONFIRM_KEY", SlayerUnlockable.class);
        if (points < unlockable.getCost()) {
            open(SlayerTab.UNLOCK);
            player.message("You do not have enough points to purchase this!");
            return;
        }
        if (unlocked.contains(unlockable)) {
            open(SlayerTab.UNLOCK);
            player.message("You have already activated this perk!");
            return;
        }
        points -= unlockable.getCost();
        unlocked.add(unlockable);
        player.message("You have purchased the " + unlockable.getName() + " Slayer perk.");
        open(SlayerTab.UNLOCK);
    }
References com.runehive.content.skill.impl.slayer.SlayerUnlockable.getCost(), com.runehive.content.skill.impl.slayer.SlayerUnlockable.getName(), open(), player, points, com.runehive.content.skill.impl.slayer.SlayerTab.UNLOCK, and unlocked.
setAmount()
void com.runehive.content.skill.impl.slayer.Slayer.setAmount (int amount)
Definition at line 307 of file Slayer.java.
{
        this.amount = amount;
    }
References amount.
setAssigned()
void com.runehive.content.skill.impl.slayer.Slayer.setAssigned (int assigned)
Definition at line 315 of file Slayer.java.
{
        this.assigned = assigned;
    }
References assigned.
setBlocked()
void com.runehive.content.skill.impl.slayer.Slayer.setBlocked (List< SlayerTask > blocked)
Definition at line 355 of file Slayer.java.
{
        this.blocked = blocked;
    }
References blocked.
setPoints()
void com.runehive.content.skill.impl.slayer.Slayer.setPoints (int points)
Definition at line 291 of file Slayer.java.
{
        this.points = points;
    }
References points.
Referenced by com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.store.currency.impl.SlayerPointCurrency.recieveCurrency(), and com.runehive.content.store.currency.impl.SlayerPointCurrency.takeCurrency().
setTask()
void com.runehive.content.skill.impl.slayer.Slayer.setTask (SlayerTask task)
Definition at line 299 of file Slayer.java.
{
        this.task = task;
    }
References task.
setTotalAssigned()
void com.runehive.content.skill.impl.slayer.Slayer.setTotalAssigned (int totalAssigned)
Definition at line 323 of file Slayer.java.
{
        this.totalAssigned = totalAssigned;
    }
References totalAssigned.
setTotalCancelled()
void com.runehive.content.skill.impl.slayer.Slayer.setTotalCancelled (int totalCancelled)
Definition at line 339 of file Slayer.java.
{
        this.totalCancelled = totalCancelled;
    }
References totalCancelled.
setTotalCompleted()
void com.runehive.content.skill.impl.slayer.Slayer.setTotalCompleted (int totalCompleted)
Definition at line 331 of file Slayer.java.
{
        this.totalCompleted = totalCompleted;
    }
References totalCompleted.
setTotalPoints()
void com.runehive.content.skill.impl.slayer.Slayer.setTotalPoints (int totalPoints)
Definition at line 347 of file Slayer.java.
{
        this.totalPoints = totalPoints;
    }
References totalPoints.
setUnlocked()
void com.runehive.content.skill.impl.slayer.Slayer.setUnlocked (Set< SlayerUnlockable > unlocked)
Definition at line 363 of file Slayer.java.
{
        this.unlocked = unlocked;
    }
References unlocked.
store()
void com.runehive.content.skill.impl.slayer.Slayer.store (int slot, int amount, boolean value)
Handles purchasing items from the slayer shop.
Definition at line 247 of file Slayer.java.
{
        if (slot < 0 && slot > STORE_ITEMS.length) {
            return;
        }
        StoreItem item = STORE_ITEMS[slot];
        int cost = item.getShopValue();
        if (value) {
            String price = cost == 0 ? "is free!" : "costs " + Utility.formatDigits(cost) + " slayer points.";
            player.message(item.getName() + " " + price);
            return;
        }
        if (player.inventory.remaining() == 0) {
            player.message("You do not have enough inventory space to buy that.");
            return;
        }
        if (!item.isStackable()) {
            if (amount > player.inventory.remaining()) {
                amount = player.inventory.remaining();
            }
        } else {
            amount *= item.getAmount();
        }
        int price = cost * amount;
        if (getPoints() < price) {
            player.message("You do not have enough slayer points to make this purchase!");
            return;
        }
        item.setAmount(amount);
        points -= price;
        player.inventory.add(item);
        player.send(new SendString(Utility.formatDigits(points) + "\\nPoints", 46714));
    }
References amount, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getName(), getPoints(), com.runehive.content.store.StoreItem.getShopValue(), com.runehive.game.world.items.Item.isStackable(), player, points, com.runehive.game.world.items.Item.setAmount(), and STORE_ITEMS.
unblock()
void com.runehive.content.skill.impl.slayer.Slayer.unblock (int index)
Unblocks the slayer task.
Definition at line 159 of file Slayer.java.
{
        if (!blocked.isEmpty() && index < blocked.size()) {
            SlayerTask task = blocked.get(index);
            blocked.remove(task);
            SlayerTab.refresh(player, player.attributes.get("SLAYER_KEY", SlayerTab.class));
            player.message("You have unblocked the task " + task.getName() + ".");
            return;
        }
        player.message("There is no task to unblock.");
    }
References blocked, player, com.runehive.content.skill.impl.slayer.SlayerTab.refresh(), and task.
Member Data Documentation
amount
int com.runehive.content.skill.impl.slayer.Slayer.amount private
The current slayer task amount.
Definition at line 40 of file Slayer.java.
Referenced by activate(), assign(), block(), cancel(), getAmount(), setAmount(), and store().
assigned
int com.runehive.content.skill.impl.slayer.Slayer.assigned private
The slayer task assigned amount.
Definition at line 37 of file Slayer.java.
Referenced by getAssigned(), and setAssigned().
blocked
List<SlayerTask> com.runehive.content.skill.impl.slayer.Slayer.blocked = new LinkedList<>() private
The list of all blocked slayer tasks.
Definition at line 55 of file Slayer.java.
Referenced by block(), getBlocked(), setBlocked(), and unblock().
ITEMS
Item [] com.runehive.content.skill.impl.slayer.Slayer.ITEMS = new Item[STORE_ITEMS.length] static package
Definition at line 236 of file Slayer.java.
Referenced by [static initializer](), and com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
player
Player com.runehive.content.skill.impl.slayer.Slayer.player private
The player instance.
Definition at line 28 of file Slayer.java.
Referenced by activate(), assign(), block(), cancel(), confirm(), open(), purchase(), Slayer(), store(), and unblock().
points
int com.runehive.content.skill.impl.slayer.Slayer.points private
The slayer points.
Definition at line 31 of file Slayer.java.
Referenced by activate(), block(), cancel(), getPoints(), purchase(), setPoints(), and store().
STORE_ITEMS
final StoreItem [] com.runehive.content.skill.impl.slayer.Slayer.STORE_ITEMS static private
Initial value:
= {
            new StoreItem(4155, 1, 0),
            new StoreItem(11941, 1, 150),
            new StoreItem(11866, 1, 75),
            new StoreItem(4166, 1, 5),
            new StoreItem(4168, 1, 5),
            new StoreItem(4164, 1, 5),
            new StoreItem(4551, 1, 5),
            new StoreItem(8901, 1, 200),
            new StoreItem(10551, 1, 200),
            new StoreItem(11738, 1, 25),
            new StoreItem(13116, 1, 200),
            new StoreItem(25781, 1, 200)
    }
Definition at line 221 of file Slayer.java.
{
            new StoreItem(4155, 1, 0),
            new StoreItem(11941, 1, 150),
            new StoreItem(11866, 1, 75),
            new StoreItem(4166, 1, 5),
            new StoreItem(4168, 1, 5),
            new StoreItem(4164, 1, 5),
            new StoreItem(4551, 1, 5),
            new StoreItem(8901, 1, 200),
            new StoreItem(10551, 1, 200),
            new StoreItem(11738, 1, 25),
            new StoreItem(13116, 1, 200),
            new StoreItem(25781, 1, 200)
    };
Referenced by [static initializer](), and store().
task
SlayerTask com.runehive.content.skill.impl.slayer.Slayer.task private
The slayer task.
Definition at line 34 of file Slayer.java.
Referenced by activate(), assign(), block(), cancel(), getTask(), setTask(), and unblock().
totalAssigned
int com.runehive.content.skill.impl.slayer.Slayer.totalAssigned private
The total tasks assigned.
Definition at line 43 of file Slayer.java.
Referenced by assign(), getTotalAssigned(), and setTotalAssigned().
totalCancelled
int com.runehive.content.skill.impl.slayer.Slayer.totalCancelled private
The total tasks cancelled.
Definition at line 49 of file Slayer.java.
Referenced by block(), cancel(), getTotalCancelled(), and setTotalCancelled().
totalCompleted
int com.runehive.content.skill.impl.slayer.Slayer.totalCompleted private
The total tasks completed.
Definition at line 46 of file Slayer.java.
Referenced by activate(), getTotalCompleted(), and setTotalCompleted().
totalPoints
int com.runehive.content.skill.impl.slayer.Slayer.totalPoints private
The total points accumulated.
Definition at line 52 of file Slayer.java.
Referenced by getTotalPoints(), and setTotalPoints().
unlocked
Set<SlayerUnlockable> com.runehive.content.skill.impl.slayer.Slayer.unlocked = new HashSet<>(SlayerUnlockable.values().length) private
The Set of all unlockable slayer perks.
Definition at line 58 of file Slayer.java.
Referenced by getUnlocked(), purchase(), and setUnlocked().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/slayer/Slayer.java