RuneHive-Game: com.runehive.content.skill.impl.magic.teleport.Teleportation Class Reference
com.runehive.content.skill.impl.magic.teleport.Teleportation Class Reference
Handles a player teleporting.
Static Public Member Functions
static void activateOverride (Mob mob, Position position, TeleportationData teleport)
static void activateOverride (Mob mob, Position position, TeleportationData teleport, Runnable runnable)
static boolean teleport (Player player, Position position)
static boolean teleport (Player player, Position position, int wilderness)
static boolean teleport (Player player, Position position, int wilderness, Runnable runnable)
static boolean teleport (Player player, Position position, int wilderness, TeleportationData teleport)
static boolean teleport (Player player, Position position, int wilderness, TeleportationData teleport, Runnable runnable)
static boolean teleport (Player player, Position position, TeleportationData teleport)
static boolean teleport (Player player, Position position, TeleportationData teleport, Runnable runnable)
Detailed Description
Handles a player teleporting.
Author
Daniel
Definition at line 19 of file Teleportation.java.
Member Function Documentation
activateOverride() [1/2]
void com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride (Mob mob, Position position, TeleportationData teleport) static
Definition at line 22 of file Teleportation.java.
{
        mob.action.execute(new TeleportAction(mob, position, teleport, () -> {}), true);
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.action.ActionManager.execute(), and teleport().
Referenced by com.runehive.content.Obelisks.activate(), com.runehive.content.activity.impl.kraken.KrakenActivity.clickObject(), com.runehive.game.action.impl.LeverAction.execute(), and com.runehive.content.activity.impl.magearena.MageArena.start().
activateOverride() [2/2]
void com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride (Mob mob, Position position, TeleportationData teleport, Runnable runnable) static
Definition at line 26 of file Teleportation.java.
{
        mob.action.execute(new TeleportAction(mob, position, teleport, runnable), true);
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.action.ActionManager.execute(), and teleport().
teleport() [1/7]
boolean com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport (Player player, Position position) static
Definition at line 30 of file Teleportation.java.
{
        return teleport(player, position, 20, TeleportationData.MODERN, () -> {});
    }
References com.runehive.content.skill.impl.magic.teleport.TeleportationData.MODERN, and teleport().
Referenced by activateOverride(), activateOverride(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfLifeListener.block(), com.runehive.content.activity.impl.kraken.KrakenActivity.clickObject(), com.runehive.content.bot.PlayerBot.endFight(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.game.action.impl.TutorialActivity.start(), teleport(), teleport(), teleport(), teleport(), teleport(), teleport(), teleport(), and com.runehive.content.teleport.TeleportHandler.teleport().
teleport() [2/7]
boolean com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport (Player player, Position position, int wilderness) static
Definition at line 42 of file Teleportation.java.
{
        return teleport(player, position, wilderness, TeleportationData.MODERN, () -> {});
    }
References com.runehive.content.skill.impl.magic.teleport.TeleportationData.MODERN, and teleport().
teleport() [3/7]
boolean com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport (Player player, Position position, int wilderness, Runnable runnable) static
Definition at line 46 of file Teleportation.java.
{
        return teleport(player, position, wilderness, TeleportationData.MODERN, runnable);
    }
References com.runehive.content.skill.impl.magic.teleport.TeleportationData.MODERN, and teleport().
teleport() [4/7]
boolean com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport (Player player, Position position, int wilderness, TeleportationData teleport) static
Definition at line 50 of file Teleportation.java.
{
        return teleport(player, position, wilderness, teleport, () -> {});
    }
References teleport().
teleport() [5/7]
boolean com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport (Player player, Position position, int wilderness, TeleportationData teleport, Runnable runnable) static
Definition at line 54 of file Teleportation.java.
{
        if(player.isGambleLocked()) return false;
        player.interfaceManager.close(false);
        if (Activity.evaluate(player, it -> !it.canTeleport(player))) {
            return false;
        }
        if(LMSLobby.lobbyMembers.contains(player) || LMSGame.isActivePlayer(player)) {
            return false;
        }
        if (player.locking.locked(PacketType.TELEPORT)) {
            return false;
        }
        if (player.isTeleblocked()) {
            player.message("You are currently under the affects of a teleblock spell and can not teleport!");
            return false;
        }
        if (player.wilderness > wilderness && !PlayerRight.isDeveloper(player)) {
            player.send(new SendMessage("You can't teleport past " + wilderness + " wilderness!"));
            return false;
        }
        if (teleport != TeleportationData.HOME) {
            player.getCombat().reset();
            player.damageImmunity.reset(3_000);
        }
        if (teleport != TeleportationData.TABLET && player.pvpInstance) {
            player.pvpInstance = false;
            player.instance = Mob.DEFAULT_INSTANCE;
            if (player.pet != null) {
                player.pet.instance = player.instance;
            }
        }
        player.action.execute(new TeleportAction(player, position, teleport, runnable), true);
        return true;
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.entity.mob.Mob.damageImmunity, com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, com.runehive.content.activity.Activity.evaluate(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.content.skill.impl.magic.teleport.TeleportationData.HOME, com.runehive.game.world.entity.Entity.instance, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.content.lms.LMSGame.isActivePlayer(), com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), com.runehive.game.world.entity.mob.player.Player.isGambleLocked(), com.runehive.game.world.entity.mob.player.Player.isTeleblocked(), com.runehive.content.lms.lobby.LMSLobby.lobbyMembers, com.runehive.game.world.entity.mob.Locking.locked(), com.runehive.game.world.entity.mob.Mob.locking, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.player.Player.pet, com.runehive.game.world.entity.mob.player.Player.pvpInstance, com.runehive.util.Stopwatch.reset(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.skill.impl.magic.teleport.TeleportationData.TABLET, com.runehive.game.world.entity.mob.data.PacketType.TELEPORT, teleport(), and com.runehive.game.world.entity.mob.player.Player.wilderness.
teleport() [6/7]
boolean com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport (Player player, Position position, TeleportationData teleport) static
Definition at line 38 of file Teleportation.java.
{
        return teleport(player, position, 20, teleport, () -> {});
    }
References teleport().
teleport() [7/7]
boolean com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport (Player player, Position position, TeleportationData teleport, Runnable runnable) static
Definition at line 34 of file Teleportation.java.
{
        return teleport(player, position, 20, teleport, runnable);
    }
References teleport().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/magic/teleport/Teleportation.java