RuneHive-Game: com.runehive.content.itemaction.impl.CelestialRing Class Reference
com.runehive.content.itemaction.impl.CelestialRing Class Reference
Public Member Functions
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
String message (Item item)
The message of the action.
String toString ()
Static Public Member Functions
static void check (Player player)
Static Public Attributes
static final short CHARGED_RING = 25541
static final short STARDUST = 25527
static final short UNCHARGED_RING = 25539
Private Member Functions
void charge (Player player, int amount, int itemId)
Detailed Description
Definition at line 9 of file CelestialRing.java.
Member Function Documentation
charge()
void com.runehive.content.itemaction.impl.CelestialRing.charge (Player player, int amount, int itemId) private
Definition at line 88 of file CelestialRing.java.
{
        if (amount > player.inventory.computeAmountForId(STARDUST)) {
            amount = player.inventory.computeAmountForId(STARDUST);
        }
        if (amount > 0) {
            if (itemId == UNCHARGED_RING) {
                player.inventory.remove(UNCHARGED_RING, 1);
                player.inventory.add(CHARGED_RING, 1);
            }
            player.inventory.remove(STARDUST, amount);
            player.inventory.refresh();
            player.celestialRingCharges += amount;
            player.message("You added " + amount + " charges to your "+name()+"");
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), CHARGED_RING, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), STARDUST, and UNCHARGED_RING.
Referenced by inventory(), and itemOnItem().
check()
void com.runehive.content.itemaction.impl.CelestialRing.check (Player player) static
Definition at line 84 of file CelestialRing.java.
{
        player.message("You have " + Utility.formatDigits(player.celestialRingCharges) + " charges in your Celestial ring.");
    }
References com.runehive.game.world.entity.mob.player.Player.celestialRingCharges, com.runehive.util.Utility.formatDigits(), and com.runehive.game.world.entity.mob.player.Player.message().
Referenced by equipment(), and com.runehive.net.packet.in.WieldItemPacketListener.handlePacket().
drop()
boolean com.runehive.content.itemaction.impl.CelestialRing.drop (Player player, Item item)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 69 of file CelestialRing.java.
{
        if (item.getId() != CHARGED_RING) {
            return false;
        }
        if (player.celestialRingCharges > 0) {
            player.inventory.remove(CHARGED_RING);
            player.inventory.add(UNCHARGED_RING, 1);
            player.inventory.add(STARDUST, player.celestialRingCharges);
            player.celestialRingCharges = 0;
            player.message("You uncharge your "+name()+".");
        }
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.Player.celestialRingCharges, CHARGED_RING, com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.ItemContainer.remove(), STARDUST, and UNCHARGED_RING.
equipment()
boolean com.runehive.content.itemaction.impl.CelestialRing.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 57 of file CelestialRing.java.
{
        if (item.getId() != CHARGED_RING) {
            return false;
        }
        if (opcode == 1) {
            check(player);
            return true;
        }
        return true;
    }
References CHARGED_RING, check(), and com.runehive.game.world.items.Item.getId().
inventory()
boolean com.runehive.content.itemaction.impl.CelestialRing.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 39 of file CelestialRing.java.
{
        if (item.getId() != UNCHARGED_RING && item.getId() != CHARGED_RING) {
            return false;
        }
        if (opcode == 1 && item.getId() == CHARGED_RING) {
            player.equipment.equip(new Item(CHARGED_RING));
            return true;
        }
        if (opcode == 2) {
            player.send(new SendInputAmount("How many charges would you like add? (0-"+player.inventory.computeAmountForId(STARDUST)+")", 10, input -> charge(player, Integer.parseInt(input), item.getId())));
            return true;
        }
        return false;
    }
References charge(), CHARGED_RING, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.send(), STARDUST, and UNCHARGED_RING.
itemOnItem()
boolean com.runehive.content.itemaction.impl.CelestialRing.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 21 of file CelestialRing.java.
{
        if ((first.getId() != UNCHARGED_RING && second.getId() != UNCHARGED_RING) && (first.getId() != CHARGED_RING && second.getId() != CHARGED_RING)) {
            return false;
        }
        if(first.getId() == STARDUST || second.getId() == STARDUST) {
            if (first.getId() == UNCHARGED_RING || second.getId() == UNCHARGED_RING) {
                player.send(new SendInputAmount("How many charges would you like add? (0-"+player.inventory.computeAmountForId(STARDUST)+")", 10, input -> charge(player, Integer.parseInt(input), UNCHARGED_RING)));
            } else {
                player.send(new SendInputAmount("How many charges would you like add? (0-"+player.inventory.computeAmountForId(STARDUST)+")", 10, input -> charge(player, Integer.parseInt(input), CHARGED_RING)));
            }
            return true;
        }
        return false;
    }
References charge(), CHARGED_RING, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.send(), STARDUST, and UNCHARGED_RING.
name()
String com.runehive.content.itemaction.impl.CelestialRing.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 16 of file CelestialRing.java.
{
        return "Celestial ring";
    }
Referenced by charge(), and drop().
Member Data Documentation
CHARGED_RING
final short com.runehive.content.itemaction.impl.CelestialRing.CHARGED_RING = 25541 static
Definition at line 12 of file CelestialRing.java.
Referenced by charge(), com.runehive.content.itemaction.ItemActionRepository.declare(), drop(), equipment(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), inventory(), and itemOnItem().
STARDUST
final short com.runehive.content.itemaction.impl.CelestialRing.STARDUST = 25527 static
Definition at line 13 of file CelestialRing.java.
Referenced by charge(), drop(), inventory(), and itemOnItem().
UNCHARGED_RING
final short com.runehive.content.itemaction.impl.CelestialRing.UNCHARGED_RING = 25539 static
Definition at line 11 of file CelestialRing.java.
Referenced by charge(), com.runehive.content.itemaction.ItemActionRepository.declare(), drop(), inventory(), and itemOnItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/CelestialRing.java