RuneHive-Game: com.runehive.content.skill.impl.firemaking.FiremakingAction Class Reference
com.runehive.content.skill.impl.firemaking.FiremakingAction Class Reference
Handles the firemaking action.
Public Member Functions
Optional< SkillAnimation > animation ()
The skill animation to execute.
boolean canInit ()
Determines if this action can be initialized.
Item destructItem ()
The item that will be removed upon destruction.
double experience ()
The experience given from this action.
String getName ()
Gets the name of this action.
void init ()
Any functionality that should be handled when this action is submitted.
void onCancel (boolean logout)
A function executed on cancellation.
void onDestruct (boolean success)
The method executed upon destruction of the item.
int skill ()
The skill we should hand to experience to.
double successFactor ()
Public Member Functions inherited from com.runehive.content.skill.impl.DestructionSkillAction
boolean canRun ()
Determines if the task can be ran.
DestructionSkillAction (Mob mob, Optional< Position > position, boolean instant)
Creates a new DestructionSkillAction.
final WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
final void onExecute ()
The method which is called on intervals of the specified #delay;.
boolean prioritized ()
Determines if this action is prioritized.
Public Member Functions inherited from com.runehive.content.skill.SkillAction
boolean ignore ()
Determines if future skill actions from the same type should be ignored.
SkillAction (Mob mob, Optional< Position > position, boolean instant)
Creates a new Action randomevent.
SkillAction (Mob mob, Optional< Position > position, int delay, boolean instant)
Creates a new Action randomevent.
final void start ()
Attempts to start the skill.
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Package Functions
FiremakingAction (Player player, Item item, FiremakingData firemaking)
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Private Attributes
final FiremakingData firemaking
final Item item
Additional Inherited Members
Protected Member Functions inherited from com.runehive.content.skill.SkillAction
final void execute ()
A function representing the unit of work that will be carried out.
final void onSchedule ()
A function executed on registration.
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
Detailed Description
Handles the firemaking action.
Author
Daniel
Definition at line 32 of file FiremakingAction.java.
Constructor & Destructor Documentation
FiremakingAction()
com.runehive.content.skill.impl.firemaking.FiremakingAction.FiremakingAction (Player player, Item item, FiremakingData firemaking) package
Definition at line 36 of file FiremakingAction.java.
{
        super(player, Optional.empty(), false);
        this.item = item;
        this.firemaking = firemaking;
    }
References firemaking, and item.
Member Function Documentation
animation()
Optional< SkillAnimation > com.runehive.content.skill.impl.firemaking.FiremakingAction.animation ()
The skill animation to execute.
Returns
the skill animation to execute.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 61 of file FiremakingAction.java.
{
        return Optional.empty();
    }
canInit()
boolean com.runehive.content.skill.impl.firemaking.FiremakingAction.canInit ()
Determines if this action can be initialized.
Returns
true if it can, false otherwise.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 43 of file FiremakingAction.java.
{
        if (getMob().skills.getMaxLevel(Skill.FIREMAKING) < firemaking.getLevel()) {
            getMob().getPlayer().message("You need a firemaking level of " + firemaking.getLevel() + " to light this log!");
            return false;
        }
        if (Area.inEdgeville(getMob()) || Area.inWilderness(getMob())) {
            getMob().getPlayer().message("You can not burn a fire here! ");
            return false;
        }
        Region region = getMob().getRegion();
        if (region.containsObject(getMob().getPosition())) {
            getMob().getPlayer().send(new SendMessage("You can't light a fire here!"));
            return false;
        }
        return true;
    }
References com.runehive.game.world.region.Region.containsObject(), com.runehive.game.world.entity.skill.Skill.FIREMAKING, firemaking, com.runehive.game.action.Action< T extends Mob >.getMob(), com.runehive.game.world.position.Area.inEdgeville(), and com.runehive.game.world.position.Area.inWilderness().
destructItem()
Item com.runehive.content.skill.impl.firemaking.FiremakingAction.destructItem ()
The item that will be removed upon destruction.
Returns
the item that will be removed.
Reimplemented from com.runehive.content.skill.impl.DestructionSkillAction.
Definition at line 136 of file FiremakingAction.java.
{
        return item;
    }
References item.
experience()
double com.runehive.content.skill.impl.firemaking.FiremakingAction.experience ()
The experience given from this action.
Returns
the numerical value representing the amount of experience given.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 66 of file FiremakingAction.java.
{
        return firemaking.getExperience() * Config.FIREMAKING_MODIFICATION;
    }
References firemaking, and com.runehive.Config.FIREMAKING_MODIFICATION.
Referenced by onDestruct().
getName()
String com.runehive.content.skill.impl.firemaking.FiremakingAction.getName ()
Gets the name of this action.
Returns
The name of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 131 of file FiremakingAction.java.
{
        return "Firemaking";
    }
Referenced by onDestruct().
init()
void com.runehive.content.skill.impl.firemaking.FiremakingAction.init ()
Any functionality that should be handled when this action is submitted.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 76 of file FiremakingAction.java.
                       {
        if (getMob().isPlayer()) {
            getMob().getPlayer().send(new SendMessage("You attempt to light the log."));
        }
        getMob().animate(new Animation(733));
    }
References com.runehive.game.action.Action< T extends Mob >.getMob().
onCancel()
void com.runehive.content.skill.impl.firemaking.FiremakingAction.onCancel (boolean logout)
A function executed on cancellation.
Reimplemented from com.runehive.game.task.Task.
Definition at line 125 of file FiremakingAction.java.
{
        Player player = (Player) getMob();
        player.animate(new Animation(65535));
    }
References com.runehive.game.world.entity.mob.Mob.animate(), and com.runehive.game.action.Action< T extends Mob >.getMob().
onDestruct()
void com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct (boolean success)
The method executed upon destruction of the item.
Parameters
success determines if the destruction was successful or not.
Reimplemented from com.runehive.content.skill.impl.DestructionSkillAction.
Definition at line 89 of file FiremakingAction.java.
{
        if (success) {
            Player player = (Player) getMob();
            final boolean saveLog = SkillCape.isEquipped(player, SkillCape.FIREMAKING) && Utility.random(1, 3) == 1;
            if (!saveLog) {
                player.inventory.remove(item);
            }
            player.takeStep();
            if (player.prestige.hasPerk(PrestigePerk.FLAME_ON) && RandomUtils.success(.25)) {
                player.inventory.remove(firemaking.getLog(), 1);
                player.skills.addExperience(Skill.FIREMAKING, experience());
            }
            RandomEventHandler.trigger(player);
            player.playerAssistant.activateSkilling(1);
            Pets.onReward(player, PetData.PHOENIX.getItem(), 8562);
            CustomGameObject object = new CustomGameObject(5249, player.getPosition());
            object.register();
            if (firemaking == FiremakingData.WILLOW_LOG) {
                player.forClan(channel -> channel.activateTask(ClanTaskKey.BURN_WILLOW_LOG, getMob().getName()));
            }
            World.schedule(new Task(180) {
                @Override
                protected void execute() {
                    GroundItem.createGlobal(player, new Item(592), object.getPosition());
                    object.unregister();
                    cancel();
                }
            });
        }
    }
References com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.content.clanchannel.content.ClanTaskKey.BURN_WILLOW_LOG, com.runehive.game.task.Task.cancel(), com.runehive.game.world.items.ground.GroundItem.createGlobal(), com.runehive.content.skill.SkillAction.execute(), experience(), com.runehive.content.skillcape.SkillCape.FIREMAKING, com.runehive.game.world.entity.skill.Skill.FIREMAKING, firemaking, com.runehive.content.prestige.PrestigePerk.FLAME_ON, com.runehive.game.world.entity.mob.player.Player.forClan(), com.runehive.game.action.Action< T extends Mob >.getMob(), getName(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.content.prestige.Prestige.hasPerk(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skillcape.SkillCape.isEquipped(), item, com.runehive.content.pet.Pets.onReward(), com.runehive.content.pet.PetData.PHOENIX, com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.game.world.entity.mob.player.Player.prestige, com.runehive.util.Utility.random(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.util.RandomUtils.success(), com.runehive.game.world.entity.mob.Mob.takeStep(), com.runehive.game.task.Task.Task(), com.runehive.content.activity.randomevent.RandomEventHandler.trigger(), and com.runehive.content.skill.impl.firemaking.FiremakingData.WILLOW_LOG.
skill()
int com.runehive.content.skill.impl.firemaking.FiremakingAction.skill ()
The skill we should hand to experience to.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 71 of file FiremakingAction.java.
                       {
        return Skill.FIREMAKING;
    }
References com.runehive.game.world.entity.skill.Skill.FIREMAKING.
successFactor()
double com.runehive.content.skill.impl.firemaking.FiremakingAction.successFactor ()
Reimplemented from com.runehive.content.skill.impl.DestructionSkillAction.
Definition at line 84 of file FiremakingAction.java.
{
        return 100 - firemaking.getLevel();
    }
References firemaking.
Member Data Documentation
firemaking
final FiremakingData com.runehive.content.skill.impl.firemaking.FiremakingAction.firemaking private
Definition at line 34 of file FiremakingAction.java.
Referenced by canInit(), experience(), FiremakingAction(), onDestruct(), and successFactor().
item
final Item com.runehive.content.skill.impl.firemaking.FiremakingAction.item private
Definition at line 33 of file FiremakingAction.java.
Referenced by destructItem(), FiremakingAction(), and onDestruct().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/firemaking/FiremakingAction.java