RuneHive-Game: com.runehive.content.skill.impl.hunter.trap.TrapManager Class Reference
com.runehive.content.skill.impl.hunter.trap.TrapManager Class Reference
Static Public Member Functions
static boolean canLay (Player client)
static void catchNPC (Trap trap, Npc npc)
static void deregister (Trap trap)
static void dismantle (Player client, GameObject trap)
static int getMaximumTraps (Player client)
static int getObjectIDByNPCID (int npcId)
static Trap getTrapForGameObject (final GameObject object)
static boolean goodArea (Player client)
static void handleLogout (Player p)
static void handleRegionChange (Player client)
static boolean hasLarupia (Player client)
static boolean isHunterNPC (int npc)
static void layTrap (Player client, Trap trap)
static void lootTrap (Player client, GameObject trap)
static void register (final Trap trap)
static int requiredLevel (int npcType)
Static Public Attributes
static List< Npc > HUNTER_NPC_LIST = new CopyOnWriteArrayList<Npc>()
static List< Trap > traps = new CopyOnWriteArrayList<Trap>()
Static Private Attributes
static final int[] exps = {3254, 3744, 6041, 8811, 10272}
Detailed Description
Definition at line 16 of file TrapManager.java.
Member Function Documentation
canLay()
boolean com.runehive.content.skill.impl.hunter.trap.TrapManager.canLay (Player client) static
Definition at line 39 of file TrapManager.java.
{
        if (!goodArea(client)) {
            client.message("You need to be in a hunting area to lay a trap.");
            return false;
        }
//        if (!client.getClickDelay().elapsed(2000))
//            return false;
        for (final Trap trap : traps) {
            if (trap == null)
                continue;
            if (trap.getGameObject().getPosition().getX() == client.getPosition().getX() && trap.getGameObject().getPosition().getY() == client.getPosition().getY()) {
                client.message("There is already a trap here, please place yours somewhere else.");
                return false;
            }
        }
        int x = client.getPosition().getX();
        int y = client.getPosition().getY();
        for (final Npc npc : HUNTER_NPC_LIST) {
            if (npc == null || !npc.isVisible())
                continue;
            if (x == npc.getPosition().getX() && y == npc.getPosition().getY() || x == npc.getX() && y == npc.getY()) {
                client.message("You cannot place your trap right here, try placing it somewhere else.");
                return false;
            }
        }
        if (client.trapsLaid >= getMaximumTraps(client)) {
            client.message("You can only have a max of " + getMaximumTraps(client) + " traps setup at once.");
            return false;
        }
        return true;
    }
References getMaximumTraps(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), goodArea(), HUNTER_NPC_LIST, com.runehive.game.world.entity.mob.player.Player.message(), traps, and com.runehive.game.world.entity.mob.player.Player.trapsLaid.
Referenced by layTrap().
catchNPC()
void com.runehive.content.skill.impl.hunter.trap.TrapManager.catchNPC (Trap trap, Npc npc) static
Definition at line 251 of file TrapManager.java.
{
        if (trap.getTrapState().equals(Trap.TrapState.CAUGHT))
            return;
        if (trap.getOwner() != null) {
            if (trap.getOwner().skills.getLevel(Skill.HUNTER) < requiredLevel(npc.id)) {
                trap.getOwner().message("You failed to catch the animal because your Hunter level is too low.");
                trap.getOwner().message("You need atleast " + requiredLevel(npc.id) + " Hunter to catch this animal");
                return;
            }
            deregister(trap);
            if (trap instanceof SnareTrap) {
                GameObject object = new CustomGameObject(getObjectIDByNPCID(npc.id), new Position(trap.getGameObject().getPosition().getX(), trap.getGameObject().getPosition().getY()));
                register(new SnareTrap(object, Trap.TrapState.CAUGHT, 100, trap.getOwner()));
            } else {
                GameObject object = new CustomGameObject(getObjectIDByNPCID(npc.id), new Position(trap.getGameObject().getPosition().getX(), trap.getGameObject().getPosition().getY()));
                register(new BoxTrap(object, Trap.TrapState.CAUGHT, 100, trap.getOwner()));
            }
            HUNTER_NPC_LIST.remove(npc);
            npc.setVisible(false);
            npc.appendDeath();
        }
    }
References com.runehive.game.world.entity.mob.npc.Npc.appendDeath(), com.runehive.content.skill.impl.hunter.trap.Trap.TrapState.CAUGHT, deregister(), getObjectIDByNPCID(), com.runehive.game.world.entity.skill.Skill.HUNTER, HUNTER_NPC_LIST, com.runehive.game.world.entity.mob.Mob.id, register(), requiredLevel(), and com.runehive.game.world.entity.Entity.setVisible().
Referenced by com.runehive.content.skill.impl.hunter.trap.TrapExecution.setTrapProcess().
deregister()
void com.runehive.content.skill.impl.hunter.trap.TrapManager.deregister (Trap trap) static
Definition at line 31 of file TrapManager.java.
{
        trap.getGameObject().unregister();
        traps.remove(trap);
        if (trap.getOwner() != null)
            trap.getOwner().trapsLaid--;
    }
References traps.
Referenced by catchNPC(), dismantle(), com.runehive.game.task.impl.HunterTask.execute(), handleLogout(), handleRegionChange(), lootTrap(), and com.runehive.content.skill.impl.hunter.trap.TrapExecution.trapTimerManagement().
dismantle()
void com.runehive.content.skill.impl.hunter.trap.TrapManager.dismantle (Player client, GameObject trap) static
Definition at line 125 of file TrapManager.java.
{
        if (trap == null)
            return;
        final Trap theTrap = getTrapForGameObject(trap);
        if (theTrap != null && theTrap.getOwner() == client) {
            deregister(theTrap);
            if (theTrap instanceof SnareTrap)
                client.inventory.add(10006, 1);
            else if (theTrap instanceof BoxTrap) {
                client.inventory.add(10008, 1);
                client.animate(new Animation(827));
            }
            client.message("You dismantle the trap..");
        } else
            client.message("You cannot dismantle someone else's trap.");
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.Mob.animate(), deregister(), com.runehive.content.skill.impl.hunter.trap.Trap.getOwner(), getTrapForGameObject(), com.runehive.game.world.entity.mob.player.Player.inventory, and com.runehive.game.world.entity.mob.player.Player.message().
Referenced by com.runehive.content.skill.impl.hunter.Hunter.clickObject().
getMaximumTraps()
int com.runehive.content.skill.impl.hunter.trap.TrapManager.getMaximumTraps (Player client) static
Definition at line 93 of file TrapManager.java.
{
        return client.skills.getLevel(Skill.HUNTER) / 20 + 1;
    }
References com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.HUNTER, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by canLay().
getObjectIDByNPCID()
int com.runehive.content.skill.impl.hunter.trap.TrapManager.getObjectIDByNPCID (int npcId) static
Definition at line 99 of file TrapManager.java.
{
        switch (npcId) {
            case 5549:
                return 9373;
            case 5551:
                return 9377;
            case 5552:
                return 9379;
            case 5550:
                return 9375;
            case 5548:
                return 9348;
        }
        return 0;
    }
Referenced by catchNPC().
getTrapForGameObject()
Trap com.runehive.content.skill.impl.hunter.trap.TrapManager.getTrapForGameObject (final GameObject object) static
Definition at line 115 of file TrapManager.java.
{
        for (final Trap trap : traps) {
            if (trap == null)
                continue;
            if (trap.getGameObject().getPosition().equals(object.getPosition()))
                return trap;
        }
        return null;
    }
References traps.
Referenced by dismantle(), and lootTrap().
goodArea()
boolean com.runehive.content.skill.impl.hunter.trap.TrapManager.goodArea (Player client) static
Definition at line 87 of file TrapManager.java.
{
        int x = client.getPosition().getX();
        int y = client.getPosition().getY();
        return x >= 2758 && x <= 2965 && y >= 2880 && y <= 2954 || x >= 2300 && x <= 2320 && y >= 9790 && y <= 9800;
    }
References com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Position.getX(), and com.runehive.game.world.position.Position.getY().
Referenced by canLay().
handleLogout()
void com.runehive.content.skill.impl.hunter.trap.TrapManager.handleLogout (Player p) static
Definition at line 279 of file TrapManager.java.
{
        if (p.trapsLaid > 0) {
            for (Trap trap : traps) {
                if (trap != null) {
                    if (trap.getOwner() != null && trap.getOwner().getUsername().equals(p.getUsername())) {
                        deregister(trap);
                        if (trap instanceof SnareTrap)
                            p.inventory.add(10006, 1);
                        else if (trap instanceof BoxTrap) {
                            p.inventory.add(10008, 1);
                            p.animate(new Animation(827));
                        }
                    }
                }
            }
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.Mob.animate(), deregister(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.game.world.entity.mob.player.Player.inventory, traps, and com.runehive.game.world.entity.mob.player.Player.trapsLaid.
Referenced by com.runehive.game.world.entity.mob.player.Player.unregister().
handleRegionChange()
void com.runehive.content.skill.impl.hunter.trap.TrapManager.handleRegionChange (Player client) static
Definition at line 74 of file TrapManager.java.
{
        if (client.trapsLaid > 0) {
            for (final Trap trap : traps) {
                if (trap == null)
                    continue;
                if (trap.getOwner() != null && trap.getOwner().getUsername().equals(client.getUsername()) && !trap.getGameObject().getPosition().isWithinDistance(client.getPosition(), 50)) {
                    deregister(trap);
                    client.message("You didn't watch over your trap well enough, it has collapsed.");
                }
            }
        }
    }
References deregister(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.game.world.entity.mob.player.Player.message(), traps, and com.runehive.game.world.entity.mob.player.Player.trapsLaid.
Referenced by com.runehive.game.world.entity.mob.player.Player.loadRegion().
hasLarupia()
boolean com.runehive.content.skill.impl.hunter.trap.TrapManager.hasLarupia (Player client) static
Definition at line 274 of file TrapManager.java.
{
        return false;
//        return client.equipment.getItems()[Equipment.HEAD_SLOT].getId() == 10045 && client.getEquipment().getItem()[Equipment.BODY_SLOT].getId() == 10043 && client.getEquipment().getItem()[Equipment.LEG_SLOT].getId() == 10041;
    }
Referenced by com.runehive.content.skill.impl.hunter.trap.TrapExecution.successFormula().
isHunterNPC()
boolean com.runehive.content.skill.impl.hunter.trap.TrapManager.isHunterNPC (int npc) static
Definition at line 191 of file TrapManager.java.
{
        return npc >= 5072 && npc <= 5080;
    }
layTrap()
void com.runehive.content.skill.impl.hunter.trap.TrapManager.layTrap (Player client, Trap trap) static
Definition at line 142 of file TrapManager.java.
{
        int id = 10006;
        if (trap instanceof BoxTrap) {
            id = 10008;
            if (client.skills.getLevel(Skill.HUNTER) < 60) {
                client.message("You need a Hunter level of at least 60 to lay this trap.");
                return;
            }
        }
        if (!client.inventory.contains(id))
            return;
        if (canLay(client)) {
            register(trap);
//            client.getClickDelay().reset();
            client.takeStep();
            client.face(trap.getGameObject());
            client.animate(new Animation(827));
            if (trap instanceof SnareTrap) {
                client.message("You set up a bird snare..");
                client.inventory.remove(10006, 1);
            } else if (trap instanceof BoxTrap) {
                if (client.skills.getLevel(Skill.HUNTER) < 27) {
                    client.message("You need a Hunter level of at least 27 to do this.");
                    return;
                }
                client.message("You set up a box trap..");
                client.inventory.remove(10008, 1);
            }
            HunterTask.intialize();
        }
    }
References com.runehive.game.world.entity.mob.Mob.animate(), canLay(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.HUNTER, com.runehive.game.task.impl.HunterTask.intialize(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), register(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.mob.Mob.takeStep().
Referenced by com.runehive.content.skill.impl.hunter.Hunter.clickItem().
lootTrap()
void com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap (Player client, GameObject trap) static
Definition at line 195 of file TrapManager.java.
{
        if (trap != null) {
            client.face(trap.getPosition());
            final Trap theTrap = getTrapForGameObject(trap);
            if (theTrap != null) {
                if (theTrap.getOwner() != null)
                    if (theTrap.getOwner() == client) {
                        if (theTrap instanceof SnareTrap) {
                            client.inventory.add(10006, 1);
                            client.inventory.add(526, 1);
                            if (theTrap.getGameObject().getId() == 19180) {
                                client.inventory.add(10088, 20 + Utility.random(30));
                                client.inventory.add(9978, 1);
                                client.message("You've succesfully caught a crimson swift.");
                                client.skills.addExperience(Skill.HUNTER, exps[0]);
                            } else if (theTrap.getGameObject().getId() == 19184) {
                                client.inventory.add(10090, 20 + Utility.random(30));
                                client.inventory.add(9978, 1);
                                client.message("You've succesfully caught a Golden Warbler.");
                                client.skills.addExperience(Skill.HUNTER, exps[1]);
                            } else if (theTrap.getGameObject().getId() == 19186) {
                                client.inventory.add(10091, 20 + Utility.random(50));
                                client.inventory.add(9978, 1);
                                client.message("You've succesfully caught a Copper Longtail.");
                                client.skills.addExperience(Skill.HUNTER, exps[2]);
                            } else if (theTrap.getGameObject().getId() == 19182) {
                                client.inventory.add(10089, 20 + Utility.random(30));
                                client.inventory.add(9978, 1);
                                client.message("You've succesfully caught a Cerulean Twitch.");
                                client.skills.addExperience(Skill.HUNTER, (exps[3]));
                            } else if (theTrap.getGameObject().getId() == 19178) {
                                client.inventory.add(10087, 20 + Utility.random(30));
                                client.inventory.add(9978, 1);
                                client.message("You've succesfully caught a Tropical Wagtail.");
                                client.skills.addExperience(Skill.HUNTER, exps[4]);
                            }
                        } else if (theTrap instanceof BoxTrap) {
                            client.inventory.add(10008, 1);
                            if (theTrap.getGameObject().getId() == 19191) {
                                client.inventory.add(10033, 1);
                                client.skills.addExperience(Skill.HUNTER, exps[6]);
                                client.message("You've succesfully caught a chinchompa!");
                            } else if (theTrap.getGameObject().getId() == 19189) {
                                client.inventory.add(10034, 1);
                                client.skills.addExperience(Skill.HUNTER, exps[7]);
                                client.message("You've succesfully caught a red chinchompa!");
                            }
                        }
                        deregister(theTrap);
                        client.animate(new Animation(827));
                    } else
                        client.message("This is not your trap.");
            }
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), deregister(), exps, com.runehive.game.world.entity.mob.Mob.face(), com.runehive.content.skill.impl.hunter.trap.Trap.getGameObject(), com.runehive.game.world.object.GameObject.getId(), com.runehive.content.skill.impl.hunter.trap.Trap.getOwner(), getTrapForGameObject(), com.runehive.game.world.entity.skill.Skill.HUNTER, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.util.Utility.random(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by com.runehive.content.skill.impl.hunter.Hunter.clickObject().
register()
void com.runehive.content.skill.impl.hunter.trap.TrapManager.register (final Trap trap) static
Definition at line 24 of file TrapManager.java.
{
        trap.getGameObject().register();
        traps.add(trap);
        if (trap.getOwner() != null)
            trap.getOwner().trapsLaid++;
    }
References traps.
Referenced by catchNPC(), and layTrap().
requiredLevel()
int com.runehive.content.skill.impl.hunter.trap.TrapManager.requiredLevel (int npcType) static
Definition at line 174 of file TrapManager.java.
{
        int levelToReturn = 1;
        if (npcType == 5072)
            levelToReturn = 19;
        else if (npcType == 5074)
            levelToReturn = 11;
        else if (npcType == 5075)
            levelToReturn = 5;
        else if (npcType == 5076)
            levelToReturn = 9;
        else if (npcType == 5079)
            levelToReturn = 53;
        else if (npcType == 5080)
            levelToReturn = 63;
        return levelToReturn;
    }
Referenced by catchNPC().
Member Data Documentation
exps
final int [] com.runehive.content.skill.impl.hunter.trap.TrapManager.exps = {3254, 3744, 6041, 8811, 10272} static private
Definition at line 22 of file TrapManager.java.
{3254, 3744, 6041, 8811, 10272};
Referenced by lootTrap().
HUNTER_NPC_LIST
List<Npc> com.runehive.content.skill.impl.hunter.trap.TrapManager.HUNTER_NPC_LIST = new CopyOnWriteArrayList<Npc>() static
Definition at line 20 of file TrapManager.java.
Referenced by canLay(), catchNPC(), and com.runehive.content.skill.impl.hunter.trap.TrapExecution.setTrapProcess().
traps
List<Trap> com.runehive.content.skill.impl.hunter.trap.TrapManager.traps = new CopyOnWriteArrayList<Trap>() static
Definition at line 18 of file TrapManager.java.
Referenced by canLay(), deregister(), com.runehive.game.task.impl.HunterTask.execute(), getTrapForGameObject(), handleLogout(), handleRegionChange(), and register().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/hunter/trap/TrapManager.java