RuneHive-Game: com.runehive.content.skill.impl.woodcutting.Woodcutting Class Reference
com.runehive.content.skill.impl.woodcutting.Woodcutting Class Reference
Public Member Functions
Woodcutting (int level, double experience)
Constructs a new Woodcutting skill.
Public Member Functions inherited from com.runehive.game.world.entity.skill.Skill
double addExperience (double amount)
Adds experiences to this skill by the given amount.
void addLevel (int amount)
Adds levels to this skill by the given amount.
void divideExperience (double amount)
Divides the current experience of this skill by a given amount.
void divideLevel (double amount)
Divides the current level of this skill by a given amount.
double getExperience ()
Gets the skill experience.
int getLevel ()
Gets the current skill level.
int getMaxLevel ()
Gets the maximum skill level.
int getRoundedExperience ()
Gets the floor experience.
int getSkill ()
Gets the skill id.
boolean isDoingSkill ()
double modifyExperience (Function< Double, Double > function)
Modifies the current experience with a given function.
double modifyExperience (Function< Double, Double > function, int lowerBounds, int upperBounds)
Modifies the current experience with a given function.
void modifyLevel (Function< Integer, Integer > function)
Modifies the current level with a given function.
void modifyLevel (Function< Integer, Integer > function, int lowerBounds, int upperBounds)
Modifies the current level with a given function.
void multiplyExperience (double amount)
Multiplies the current experience of this skill by a given amount.
void multiplyLevel (double amount)
Multiplies the current level of this skill by a given amount.
boolean onEvent (Player player, InteractionEvent interactionEvent)
void removeExperience (double amount)
Removes experiences from this skill by the given amount.
void removeLevel (int amount)
Removes levels from this skill by the given amount.
boolean reqLevel (int level)
Determines if your level is greater than or equal to level.
void setDoingSkill (boolean doingSkill)
void setExperience (double experience)
Sets the experience for this skill.
void setLevel (int level)
Sets the level for this skill.
void setMaxLevel (int maxLevel)
Sets the maximum level for this skill.
Skill (int skill, int level, double experience)
Constructs a new Skill.
String toString ()
Static Public Member Functions
static double getBonus (Player player)
static boolean success (Player player, TreeData tree, AxeData axe)
Static Public Member Functions inherited from com.runehive.game.world.entity.skill.Skill
static Function< Integer, Integer > add (int amount)
Creates a function that adds a number by an amount.
static Function< Integer, Integer > divide (double amount)
Creates a function that divides a number by an amount.
static final int getExperienceForLevel (int level)
Gets the experience for a given level.
static final byte getLevelForExperience (double experience)
Gets the level for a given experience amount.
static String getName (int skill)
Gets the name for a skill id.
static Function< Integer, Integer > multiply (double amount)
Creates a function that multiplies a number by an amount.
static Function< Integer, Integer > subtract (int amount)
Creates a function that subtracts a number by an amount.
Protected Member Functions
boolean clickObject (Player player, ObjectInteractionEvent event)
Protected Member Functions inherited from com.runehive.game.world.entity.skill.Skill
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
double modifier ()
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Additional Inherited Members
Public Attributes inherited from com.runehive.game.world.entity.skill.Skill
transient final Stopwatch stopwatch = Stopwatch.start()
Static Public Attributes inherited from com.runehive.game.world.entity.skill.Skill
static final int AGILITY = 16
The agility skill id.
static final int ATTACK = 0
The attack skill id.
static final int CONSTRUCTION = 21
The construction skill id.
static final int COOKING = 7
The cooking skill id.
static final int CRAFTING = 12
The crafting skill id.
static final int DEFENCE = 1
The defence skill id.
static final int FARMING = 19
The farming skill id.
static final int FIREMAKING = 11
The firemaking skill id.
static final int FISHING = 10
The fishing skill id.
static final int FLETCHING = 9
The fletching skill id.
static final int HERBLORE = 15
The herblore skill id.
static final int HITPOINTS = 3
The hitpoints skill id.
static final int HUNTER = 22
The hunter skill id.
static final int[][] INTERFACE_DATA
Skill tab string data.
static final int MAGIC = 6
The magic skill id.
static final int MINING = 14
The mining skill id.
static final int PRAYER = 5
The prayer skill id.
static final int RANGED = 4
The ranged skill id.
static final int RUNECRAFTING = 20
The runecrafting skill id.
static final int SKILL_COUNT = 23
The amount of available skills.
static final int SLAYER = 18
The slayer skill id.
static final int SMITHING = 13
The smithing skill id.
static final int STRENGTH = 2
The strength skill id.
static final int THIEVING = 17
The thieving skill id.
static final int TOTAL_SKILL_LEVEL = 99 * SKILL_COUNT
The total skill amount.
static final int WOODCUTTING = 8
The woodcutting skill id.
Detailed Description
Author
Stand Up
Since
24-12-2016.
Definition at line 15 of file Woodcutting.java.
Constructor & Destructor Documentation
Woodcutting()
com.runehive.content.skill.impl.woodcutting.Woodcutting.Woodcutting (int level, double experience)
Constructs a new Woodcutting skill.
Definition at line 18 of file Woodcutting.java.
{
        super(Skill.WOODCUTTING, level, experience);
    }
References com.runehive.game.world.entity.skill.Skill.experience, com.runehive.game.world.entity.skill.Skill.level, and com.runehive.game.world.entity.skill.Skill.Skill().
Member Function Documentation
clickObject()
boolean com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 44 of file Woodcutting.java.
{
        TreeData tree = TreeData.forId(event.getObject().getId());
        if (tree == null)
            return false;
        AxeData axe = AxeData.getDefinition(player).orElse(null);
        if (axe == null) {
            player.send(new SendMessage("You don't have a hatchet."));
            return true;
        }
        if (!player.skills.getSkills()[Skill.WOODCUTTING].reqLevel(axe.level)) {
            player.send(new SendMessage("You need a level of " + axe.level + " to use this hatchet!"));
            return true;
        }
        if (!player.skills.getSkills()[Skill.WOODCUTTING].reqLevel(tree.levelRequired)) {
            player.send(new SendMessage("You need a level of " + tree.levelRequired + " to cut " + StringUtils.appendIndefiniteArticle(event.getObject().getDefinition().getName()) + "."));
            return true;
        }
        if (!player.inventory.hasCapacityFor(new Item(tree.item))) {
            player.message("You do not have enough inventory spaces to do this!");
            return true;
        }
        player.action.execute(new WoodcuttingAction(player, event.getObject(), tree, axe));
        player.skills.get(Skill.WOODCUTTING).setDoingSkill(true);
        player.message(true, "You swing your axe at the tree...");
        return true;
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.util.StringUtils.appendIndefiniteArticle(), com.runehive.game.action.ActionManager.execute(), com.runehive.content.skill.impl.woodcutting.TreeData.forId(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.game.world.entity.skill.SkillManager.getSkills(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.woodcutting.TreeData.item, com.runehive.content.skill.impl.woodcutting.AxeData.level, com.runehive.content.skill.impl.woodcutting.TreeData.levelRequired, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.skill.Skill.reqLevel(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.skill.Skill.setDoingSkill(), com.runehive.game.world.entity.skill.Skill.Skill(), and com.runehive.game.world.entity.mob.Mob.skills.
getBonus()
double com.runehive.content.skill.impl.woodcutting.Woodcutting.getBonus (Player player) static
Definition at line 22 of file Woodcutting.java.
{
        double bonus = 0;
        if(player.equipment.getId(0) == 10941)
            bonus += 0.4;
        if(player.equipment.getId(4) == 10939)
            bonus += 0.8;
        if(player.equipment.getId(7) == 10940)
            bonus += 0.6;
        if(player.equipment.getId(10) == 10933)
            bonus += 0.2;
        if(player.equipment.containsAll(10941, 10939, 10940, 10933))
            bonus = 2.5;
        return bonus;
    }
References com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.world.entity.mob.player.Player.equipment, and com.runehive.game.world.items.containers.ItemContainer.getId().
Referenced by com.runehive.game.world.entity.skill.SkillManager.addExperience().
success()
boolean com.runehive.content.skill.impl.woodcutting.Woodcutting.success (Player player, TreeData tree, AxeData axe) static
Definition at line 39 of file Woodcutting.java.
{
        return SkillRepository.isSuccess(player, Skill.WOODCUTTING, tree.levelRequired, axe.level);
    }
References com.runehive.content.skill.SkillRepository.isSuccess(), com.runehive.content.skill.impl.woodcutting.AxeData.level, com.runehive.content.skill.impl.woodcutting.TreeData.levelRequired, and com.runehive.game.world.entity.skill.Skill.Skill().
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/woodcutting/Woodcutting.java