RuneHive-Game: com.runehive.content.store.impl.PersonalStore Class Reference
com.runehive.content.store.impl.PersonalStore Class Reference
Public Member Functions
void add (Player player, Item item, int slot, boolean addX)
Handles adding an item to the player's personal shop.
void close (Player player)
void itemContainerAction (Player player, int id, int slot, int action, boolean purchase)
void onPurchase (Player player, Item item)
void open (Player player)
PersonalStore (String name, Optional< StoreItem[]> items, int rank, String title, String caption, CurrencyType currency)
Creates a new Store.
void refresh (Player player)
void remove (Player player, Item item, int slot)
Handles adding an item to the player's personal shop.
SellType sellType ()
StoreType type ()
Public Member Functions inherited from com.runehive.content.store.Store
boolean decrementStock ()
final boolean equals (Object obj)
final int hashCode ()
boolean purchase (Player player, Item item, int slot)
Store (String name, ItemContainer.StackPolicy policy, CurrencyType currencyType, int capacity)
Static Public Member Functions
static void add (Player player, PersonalStore store)
static void changeName (Player player, String input, boolean caption)
Changes the name of the shop.
static void claimCoins (Player player)
Handles claiming coins from the personal store.
static void edit (Player player)
Handles editing the personal store.
static void myShop (Player player)
Creates the player's shops if non-existent or will enter.
static void openMenu (Player player)
static void openPanel (Player player)
Opens the panel where a player can search for shops.
Static Public Member Functions inherited from com.runehive.content.store.Store
static void closeShop (Player player)
static void exchange (Player player, int id, int slot, int action, boolean purchase)
Public Attributes
String caption
The caption of this shop.
final int rank
The rank of this shop on the featured list.
String title
The title of this shop.
Public Attributes inherited from com.runehive.content.store.Store
ItemContainer container
The current item container which contains the current items from this shop.
Map< Integer, Integer > itemCache
The map of cached shop item identifications and their amounts.
final String name
The name of this shop.
final Set< Player > players = new HashSet<>()
The set of players that are currently viewing this shop.
Static Public Attributes
static final Map< Integer, PersonalStore > FEATURED_SHOPS = new HashMap<>()
The shops the player is currently viewing.
static Map< String, Long > SOLD_ITEMS = new HashMap<>()
A mapping of a player name with the amount of coins waiting for him.
Static Public Attributes inherited from com.runehive.content.store.Store
static Map< String, Store > STORES = new HashMap<>()
A mapping of each shop by it's name.
Private Member Functions
boolean isOwner (Player player)
Checks if the player is the owner of the shop.
void modify (Player player, int slot)
Modifies the player's shop item.
void setValue (Player player, Item invItem, StoreItem storeItem, int value, int slot)
Private Attributes
boolean updating = false
The flag is the shop is being updated by the owner.
Additional Inherited Members
Protected Member Functions inherited from com.runehive.content.store.Store
final void sell (Player player, Item item, int slot, boolean addX)
void sendPurchaseValue (Player player, int slot)
final void sendSellValue (Player player, int slot)
Static Protected Member Functions inherited from com.runehive.content.store.Store
static List< PersonalStore > getFeaturedShops ()
static List< PersonalStore > getPersonalShops ()
Protected Attributes inherited from com.runehive.content.store.Store
final CurrencyType currencyType
The currency for this shop.
Detailed Description
Author
Stand Up
Since
4-1-2017.
Definition at line 22 of file PersonalStore.java.
Constructor & Destructor Documentation
PersonalStore()
com.runehive.content.store.impl.PersonalStore.PersonalStore (String name, Optional< StoreItem[]> items, int rank, String title, String caption, CurrencyType currency)
Creates a new Store.
Definition at line 43 of file PersonalStore.java.
{
        super(name, ItemContainer.StackPolicy.STANDARD, currency, 28);
        this.rank = rank;
        this.title = title;
        this.caption = caption;
        items.ifPresent(i -> this.container.setItems(i, false));
    }
References caption, com.runehive.content.store.Store.container, com.runehive.content.store.Store.name, rank, com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD, and title.
Referenced by add(), changeName(), myShop(), and openPanel().
Member Function Documentation
add() [1/2]
void com.runehive.content.store.impl.PersonalStore.add (Player player, Item item, int slot, boolean addX)
Handles adding an item to the player's personal shop.
Definition at line 182 of file PersonalStore.java.
{
        if (!player.interfaceManager.isInterfaceOpen(StoreConstant.INTERFACE_ID)) {
            return;
        }
        if (!item.isTradeable()) {
            player.send(new SendMessage("You can not sell untradeable items in your shop!"));
            return;
        }
        if (CurrencyType.isCurrency(item.getId())) {
            player.send(new SendMessage("You can not sell any currency in your shop!"));
            return;
        }
        Item invItem = player.inventory.get(slot);
        final StoreItem storeItem = new StoreItem(invItem.getId(), item.getAmount());
        if (!addX) {
            player.send(new SendInputAmount("What do you want to value your <col=027399>" + item.getName() + "</col>?", 10, value -> {
                setValue(player, invItem, storeItem, Integer.parseInt(value), slot);
                refresh(player);
            }));
            return;
        }
        player.send(new SendInputAmount("How much would you like to put in your shop?", 10, amount -> {
            storeItem.setAmount(Integer.parseInt(amount));
            player.send(new SendInputAmount("What do you want to value your <col=027399>" + item.getName() + "</col>?", 10, value -> {
                setValue(player, invItem, storeItem, Integer.parseInt(value), slot);
                refresh(player);
            }));
        }));
    }
References com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.content.store.StoreConstant.INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.store.currency.CurrencyType.isCurrency(), com.runehive.game.world.entity.mob.player.InterfaceManager.isInterfaceOpen(), com.runehive.game.world.items.Item.isTradeable(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.items.Item.setAmount().
add() [2/2]
void com.runehive.content.store.impl.PersonalStore.add (Player player, PersonalStore store) static
Definition at line 51 of file PersonalStore.java.
{
        STORES.put(player.getName(), store);
    }
References com.runehive.game.world.entity.mob.player.Player.getName(), PersonalStore(), and com.runehive.content.store.Store.STORES.
Referenced by com.runehive.content.store.Store.getFeaturedShops(), and itemContainerAction().
changeName()
void com.runehive.content.store.impl.PersonalStore.changeName (Player player, String input, boolean caption) static
Changes the name of the shop.
Definition at line 102 of file PersonalStore.java.
{
        if (!Store.STORES.containsKey(player.getName())) {
            player.send(new SendMessage("You do not have a store. Set it up by first opening it from the previous menu."));
            return;
        }
        String type = caption ? "caption" : "title";
        if (Arrays.stream(Config.BAD_STRINGS).anyMatch(b -> input.contains(b))) {
            player.send(new SendMessage("You have entered an invalid shop " + type + "."));
            player.interfaceManager.close();
            return;
        }
        PersonalStore shop = (PersonalStore) Store.STORES.get(player.getName());
        String context = Utility.formatName(input);
        if (caption) {
            shop.caption = context;
        } else {
            shop.title = context;
            player.send(new SendString(shop.title, 40002));
        }
        player.send(new SendMessage("You have changed your shop " + type + " to: " + context + "."));
    }
References com.runehive.Config.BAD_STRINGS, caption, com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, PersonalStore(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.store.Store.Store(), title, and type().
Referenced by edit().
claimCoins()
void com.runehive.content.store.impl.PersonalStore.claimCoins (Player player) static
Handles claiming coins from the personal store.
Definition at line 56 of file PersonalStore.java.
{
//        DialogueFactory factory = player.dialogueFactory;
//        if (!SOLD_ITEMS.containsKey(player.getName())) {
//            factory.sendItem("Personal Store", "There are no coins available for you to collect.", Config.CURRENCY).execute();
//            return;
//        }
//        long amount = SOLD_ITEMS.get(player.getName());
//        boolean added = player.bankVault.add(amount);
//        if (added) {
//            SOLD_ITEMS.remove(player.getName());
//        }
//        String message = added ? "Your collected coins have been sent to your bank vault." : "There was not enough room inside your bank vault to hold your coins.";
//        player.send(new SendMessage(message, MessageColor.DARK_GREEN));
//        openMenu(player);
//        factory.sendItem("Personal Store", message, Config.CURRENCY).execute();
    }
close()
void com.runehive.content.store.impl.PersonalStore.close (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 397 of file PersonalStore.java.
{
        players.remove(player);
        player.attributes.remove("SHOP");
        player.viewing_shops.clear();
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.store.Store.players, com.runehive.util.generic.GenericAttributes.remove(), and com.runehive.game.world.entity.mob.player.Player.viewing_shops.
edit()
void com.runehive.content.store.impl.PersonalStore.edit (Player player) static
Handles editing the personal store.
Definition at line 129 of file PersonalStore.java.
{
        DialogueFactory f = player.dialogueFactory;
        f.sendStatement("Loading your shop details...").sendOption("Change shop name", () -> {
            f.onAction(() -> {
                player.send(new SendInputMessage("Enter the name of your shop:", 30, input -> {
                    changeName(player, input, false);
                }));
            });
        }, "Change caption", () -> {
            f.onAction(() -> {
                player.send(new SendInputMessage("Enter the caption of your shop:", 30, input -> {
                    changeName(player, input, true);
                }));
            });
        }).execute();
    }
References changeName(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
isOwner()
boolean com.runehive.content.store.impl.PersonalStore.isOwner (Player player) private
Checks if the player is the owner of the shop.
Definition at line 308 of file PersonalStore.java.
{
        return this.name.equals(player.getName());
    }
References com.runehive.game.world.entity.mob.player.Player.getName(), and com.runehive.content.store.Store.name.
Referenced by itemContainerAction().
itemContainerAction()
void com.runehive.content.store.impl.PersonalStore.itemContainerAction (Player player, int id, int slot, int action, boolean purchase)
Reimplemented from com.runehive.content.store.Store.
Definition at line 313 of file PersonalStore.java.
{
        switch (action) {
            case 1:
                if (purchase) {
                    if (this.isOwner(player)) {
                        this.modify(player, slot);
                    } else {
                        this.sendPurchaseValue(player, slot);
                    }
                } else {
                    if (this.isOwner(player)) {
                        this.add(player, new Item(id, 1), slot, false);
                    }
                }
                break;
            default:
                int count = purchase ? this.container.retrieve(slot).orElse(null).getAmount() : player.inventory.retrieve(slot).orElse(null).getAmount();
                int amount = action == 2 ? (purchase ? 1 : 5) : action == 3 ? 10 : action == 4 ? count : -100;
                if (purchase) {
                    if (this.isOwner(player)) {
                        this.remove(player, new Item(id, amount), slot);
                    } else {
                        if (updating) {
                            player.send(new SendMessage("The owner is currently updating the shop, try again in a few seconds.", MessageColor.RED));
                            return;
                        }
                        this.purchase(player, new Item(id, amount), slot);
                    }
                } else {
                    if (this.isOwner(player)) {
                        this.add(player, new Item(id, amount), slot, amount == -100);
                    }
                }
                break;
        }
    }
References add(), com.runehive.content.store.Store.container, com.runehive.game.world.entity.mob.player.Player.inventory, isOwner(), modify(), com.runehive.content.store.Store.purchase(), com.runehive.util.MessageColor.RED, com.runehive.game.world.items.containers.ItemContainer.retrieve(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.store.Store.sendPurchaseValue(), and updating.
modify()
void com.runehive.content.store.impl.PersonalStore.modify (Player player, int slot) private
Modifies the player's shop item.
Definition at line 278 of file PersonalStore.java.
{
        if (!player.interfaceManager.isInterfaceOpen(StoreConstant.INTERFACE_ID)) {
            return;
        }
        DialogueFactory factory = player.dialogueFactory;
        StoreItem item = (StoreItem) container.retrieve(slot).orElse(null);
        if (item == null)
            return;
        updating = true;
        factory.sendOption(
                "Change value",
                () -> factory.onAction(() -> player.send(new SendInputAmount("Enter new value", 10, input -> {
                    item.setShopValue(Integer.parseInt(input));
                    player.send(new SendMessage("You've changed " + item.getName() + "'s value to " + Utility.formatDigits(Integer.parseInt(input)) + " " + item.getShopCurrency(this)));
                    refresh(player);
                    player.dialogueFactory.clear();
                    updating = false;
                }))),
                "Change currency",
                () -> factory.onAction(() -> updating = false),
                "Nevermind",
                () -> factory.onAction(() -> {
                    updating = false;
                    player.dialogueFactory.clear();
                })).execute();
    }
References com.runehive.content.dialogue.DialogueFactory.clear(), com.runehive.content.store.Store.container, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getName(), com.runehive.content.store.StoreItem.getShopCurrency(), com.runehive.content.store.StoreConstant.INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.isInterfaceOpen(), com.runehive.content.dialogue.DialogueFactory.onAction(), refresh(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendOption(), com.runehive.content.store.StoreItem.setShopValue(), and updating.
Referenced by itemContainerAction().
myShop()
void com.runehive.content.store.impl.PersonalStore.myShop (Player player) static
Creates the player's shops if non-existent or will enter.
Definition at line 92 of file PersonalStore.java.
{
        if (!Store.STORES.containsKey(player.getName())) {
            PersonalStore shop = new PersonalStore(player.getName(), Optional.empty(), player.right.getCrown(), player.getName() + "'s Store", "No caption set", CurrencyType.COINS);
            Store.STORES.put(player.getName(), shop);
        }
        STORES.get(player.getName()).open(player);
    }
References com.runehive.content.store.currency.CurrencyType.COINS, com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.entity.mob.player.Player.getName(), PersonalStore(), com.runehive.game.world.entity.mob.player.Player.right, com.runehive.content.store.Store.Store(), and com.runehive.content.store.Store.STORES.
onPurchase()
void com.runehive.content.store.impl.PersonalStore.onPurchase (Player player, Item item)
Reimplemented from com.runehive.content.store.Store.
Definition at line 352 of file PersonalStore.java.
{
        if (!SOLD_ITEMS.containsKey(name))
            SOLD_ITEMS.put(name, 0L);
        long amount = SOLD_ITEMS.get(name);
        SOLD_ITEMS.replace(name, amount + item.getAmount());
        GameSaver.ITEMS_SOLD++;
        GameSaver.PERSONAL_ITEM_WORTH += (item.getValue() * item.getAmount());
        World.search(name).ifPresent(p -> p.send(new SendMessage("You have coins to collect from your shop!", MessageColor.DARK_GREEN)));
    }
References com.runehive.util.MessageColor.DARK_GREEN, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getValue(), com.runehive.util.GameSaver.ITEMS_SOLD, com.runehive.content.store.Store.name, com.runehive.util.GameSaver.PERSONAL_ITEM_WORTH, com.runehive.game.world.World.search(), and SOLD_ITEMS.
open()
void com.runehive.content.store.impl.PersonalStore.open (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 375 of file PersonalStore.java.
{
        player.attributes.set("SHOP", name);
        players.add(player);
        StoreItem[] items = (StoreItem[]) this.container.getItems();
        int lastItem = 0;
        if (items.length != 0) {
            for (int i = 0; i < items.length; i++) {
                player.send(new SendString(items[i] == null ? "0" : items[i].getShopValue() + "," + 0, 40052 + i));
                lastItem = i;
            }
        }
        final int scrollBarSize = lastItem <= 32 ? 0 : (lastItem / 8) * 72;
        player.send(new SendScrollbar(40050, scrollBarSize));
        player.send(new SendString(title, 40002));
        player.send(new SendItemOnInterface(40051, items));
        player.send(new SendItemOnInterface(3823, player.inventory.toArray()));
        player.send(new SendString("Store size: " + items.length, 40007));
        player.interfaceManager.openInventory(StoreConstant.INTERFACE_ID, 3822);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.store.Store.container, com.runehive.content.store.StoreConstant.INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.store.Store.name, com.runehive.game.world.entity.mob.player.InterfaceManager.openInventory(), com.runehive.content.store.Store.players, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), title, and com.runehive.game.world.items.containers.ItemContainer.toArray().
Referenced by refresh().
openMenu()
void com.runehive.content.store.impl.PersonalStore.openMenu (Player player) static
Definition at line 73 of file PersonalStore.java.
{
        if (player == null) {
            return;
        }
        if (player.getName() == null) {
            return;
        }
        long collect = SOLD_ITEMS.get(player.getName()) == null ? 0 : SOLD_ITEMS.get(player.getName());
        player.send(new SendString("<col=d38537>Active stores:</col> " + getPersonalShops().size(), 38210));
        player.send(new SendString("<col=d38537>Total Items Sold:</col> " + Utility.formatPrice(GameSaver.ITEMS_SOLD), 38211));
        player.send(new SendString("<col=d38537>Total Sold Worth:</col> " + Utility.formatPrice(GameSaver.PERSONAL_ITEM_WORTH), 38213));
        player.send(new SendString(collect <= 0 ? "None" : Utility.formatDigits(collect), 38207));
        player.interfaceManager.open(38200);
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatPrice(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.store.Store.getPersonalShops(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.util.GameSaver.ITEMS_SOLD, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.util.GameSaver.PERSONAL_ITEM_WORTH, com.runehive.game.world.entity.mob.player.Player.send(), and SOLD_ITEMS.
openPanel()
void com.runehive.content.store.impl.PersonalStore.openPanel (Player player) static
Opens the panel where a player can search for shops.
Definition at line 147 of file PersonalStore.java.
{
        List<PersonalStore> personalShops = getPersonalShops();
        int size = personalShops.size() < 10 ? 10 : personalShops.size();
        for (int string = 53031, index = 0; index < size; index++) {
            PersonalStore shop = index >= personalShops.size() ? null : personalShops.get(index);
            String tooltip = shop == null ? "" : "View <col=ffb000>" + shop.name + "<col=FFFFFF>'s shop";
            String name = shop == null ? "" : shop.name;
            String caption = shop == null ? "" : shop.caption;
            if (shop != null)
                player.viewing_shops.put(-(12505 - (index * 3)), shop);
            player.send(new SendTooltip(tooltip, string));
            string++;
            player.send(new SendString(name, string));
            string++;
            player.send(new SendString(caption, string));
            string++;
        }
        List<PersonalStore> featured_shops = getFeaturedShops();
        for (int index = 0, string = 53008; index < 10; index++, string++) {
            PersonalStore shop = index >= featured_shops.size() ? null : featured_shops.get(index);
            String name = shop == null ? "" : shop.name;
            String tooltip = shop == null ? "" : "View <col=ffb000>" + shop.name + "<col=FFFFFF>'s shop";
            if (shop != null)
                FEATURED_SHOPS.put(-(12528 + index), shop);
            player.send(new SendTooltip(tooltip, string));
            player.send(new SendString(name, string));
        }
        player.send(new SendString("Available stores: " + personalShops.size(), 53023));
        player.send(new SendScrollbar(53030, (size * 28)));
        player.interfaceManager.open(53000);
    }
References caption, FEATURED_SHOPS, com.runehive.content.store.Store.getFeaturedShops(), com.runehive.content.store.Store.getPersonalShops(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.content.store.Store.name, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), PersonalStore(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.player.Player.viewing_shops.
refresh()
void com.runehive.content.store.impl.PersonalStore.refresh (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 364 of file PersonalStore.java.
{
        for (Player p : players) {
            if (p != null) {
                open(p);
                if (p != player)
                    p.send(new SendMessage("[" + title + "] The shop has been updated!"));
            }
        }
    }
References open(), com.runehive.content.store.Store.players, and title.
Referenced by modify(), and remove().
remove()
void com.runehive.content.store.impl.PersonalStore.remove (Player player, Item item, int slot)
Handles adding an item to the player's personal shop.
Definition at line 243 of file PersonalStore.java.
{
        if (!player.interfaceManager.isInterfaceOpen(StoreConstant.INTERFACE_ID)) {
            return;
        }
        final StoreItem storeItem = (StoreItem) this.container.retrieve(slot).orElse(null);
        if (storeItem == null)
            return;
        if (item.getAmount() > storeItem.getAmount())
            item.setAmount(storeItem.getAmount());
        if (!player.inventory.hasCapacityFor(item)) {
            item.setAmount(player.inventory.remaining());
            if (item.getAmount() == 0) {
                player.send(new SendMessage("You do not have enough space in your inventory to withdraw this item!"));
                return;
            }
        }
        if (player.inventory.remaining() >= item.getAmount() && !item.isStackable() || player.inventory.remaining() >= 1 && item.isStackable() || player.inventory.contains(item.getId()) && item.isStackable()) {
            if ((storeItem.getAmount() - item.getAmount()) < 1) {
                container.remove(item, slot, false, false);
                container.shift();
            } else {
                storeItem.decrementAmountBy(item.getAmount());
            }
            player.inventory.add(item);
        } else {
            player.send(new SendMessage("You don't have enough space in your inventory."));
            return;
        }
        refresh(player);
    }
References com.runehive.content.store.Store.container, com.runehive.game.world.items.Item.decrementAmountBy(), com.runehive.game.world.items.Item.getAmount(), com.runehive.content.store.StoreConstant.INTERFACE_ID, and refresh().
sellType()
SellType com.runehive.content.store.impl.PersonalStore.sellType ()
Reimplemented from com.runehive.content.store.Store.
Definition at line 409 of file PersonalStore.java.
{
        return SellType.NONE;
    }
References com.runehive.content.store.SellType.NONE.
setValue()
void com.runehive.content.store.impl.PersonalStore.setValue (Player player, Item invItem, StoreItem storeItem, int value, int slot) private
Definition at line 215 of file PersonalStore.java.
{
        if (!player.interfaceManager.isInterfaceOpen(StoreConstant.INTERFACE_ID)) {
            return;
        }
        storeItem.setShopValue(value);
        int amount = player.inventory.computeAmountForId(invItem.getId());
        if (storeItem.getAmount() > amount && !storeItem.isStackable()) {
            storeItem.setAmount(amount);
        } else if (storeItem.getAmount() > player.inventory.get(slot).getAmount() && storeItem.isStackable()) {
            storeItem.setAmount(player.inventory.get(slot).getAmount());
        }
        player.inventory.remove(storeItem, slot);
        Optional<Item> contains = container.stream().filter(i -> i != null && storeItem.getId() == i.getId() && ((StoreItem) i).getShopValue() == storeItem.getShopValue()).findFirst();
        if (contains.isPresent()) {
            contains.get().incrementAmountBy(storeItem.getAmount());
        } else {
            if (!storeItem.isStackable() && storeItem.getAmount() > 1) {
                container.add(storeItem, false, true);
            } else {
                container.add(storeItem);
            }
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.content.store.Store.container, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.content.store.StoreItem.getShopValue(), com.runehive.content.store.StoreConstant.INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.InterfaceManager.isInterfaceOpen(), com.runehive.game.world.items.Item.isStackable(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.Item.setAmount(), and com.runehive.content.store.StoreItem.setShopValue().
type()
StoreType com.runehive.content.store.impl.PersonalStore.type ()
Reimplemented from com.runehive.content.store.Store.
Definition at line 404 of file PersonalStore.java.
{
        return StoreType.PERSONAL;
    }
References com.runehive.content.store.StoreType.PERSONAL.
Referenced by changeName().
Member Data Documentation
caption
String com.runehive.content.store.impl.PersonalStore.caption
The caption of this shop.
Definition at line 37 of file PersonalStore.java.
Referenced by changeName(), openPanel(), and PersonalStore().
FEATURED_SHOPS
final Map<Integer, PersonalStore> com.runehive.content.store.impl.PersonalStore.FEATURED_SHOPS = new HashMap<>() static
The shops the player is currently viewing.
Definition at line 25 of file PersonalStore.java.
Referenced by openPanel().
rank
final int com.runehive.content.store.impl.PersonalStore.rank
The rank of this shop on the featured list.
Definition at line 31 of file PersonalStore.java.
Referenced by PersonalStore().
SOLD_ITEMS
Map<String, Long> com.runehive.content.store.impl.PersonalStore.SOLD_ITEMS = new HashMap<>() static
A mapping of a player name with the amount of coins waiting for him.
Definition at line 28 of file PersonalStore.java.
Referenced by onPurchase(), openMenu(), and com.runehive.content.store.PersonalStoreSaver.savePayments().
title
String com.runehive.content.store.impl.PersonalStore.title
The title of this shop.
Definition at line 34 of file PersonalStore.java.
Referenced by changeName(), open(), PersonalStore(), and refresh().
updating
boolean com.runehive.content.store.impl.PersonalStore.updating = false private
The flag is the shop is being updated by the owner.
Definition at line 40 of file PersonalStore.java.
Referenced by itemContainerAction(), and modify().
The documentation for this class was generated from the following file:
java/com/runehive/content/store/impl/PersonalStore.java