RuneHive-Game: com.runehive.game.world.pathfinding.path.impl.SimplePathFinder Class Reference
com.runehive.game.world.pathfinding.path.impl.SimplePathFinder Class Reference
Represents a simple path finder which determines a straight path to the first blocked tile or it's destination.
Public Member Functions
Path find (Mob source, Position end, int targetWidth, int targetLength)
A default method to find a path for the specified position.
Public Member Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
final Path find (Mob origin, Interactable target)
final Path find (Mob origin, Position target)
Private Member Functions
Deque< Position > addWalks (Mob source, Position target, int targetWidth, int targetLength, Deque< Position > positions)
Performs the path finding calculations to find the path using the A* algorithm.
boolean traversable (Mob source, Position current, Interactable target, Direction direction, boolean projectiles)
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
boolean projectileCheck (Position current, Position going)
Returns whether or not a Position shooting projectile to another Position would lead to is traversable.
boolean traversable (Position current, int size, Direction... directions)
Returns whether or not a Position walking one step in any of the specified Directions would lead to is traversable.
Package Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
boolean traversable (Position current, Position going, int size)
Returns whether or not a Position is traversable to the direction of another Position.
Detailed Description
Represents a simple path finder which determines a straight path to the first blocked tile or it's destination.
Mostly used by Mob following and movement.
Author
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Michael | Chex
Definition at line 26 of file SimplePathFinder.java.
Member Function Documentation
addWalks()
Deque< Position > com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks (Mob source, Position target, int targetWidth, int targetLength, Deque< Position > positions) private
Performs the path finding calculations to find the path using the A* algorithm.
Parameters
source The path finder's start position.
target The path finder's destination.
positions The current searched deque of moves.
Returns
The path to pursue to reach the destination.
Definition at line 50 of file SimplePathFinder.java.
{
        Position current = source.getPosition();
        Position targ = target;
        Interactable targInt = Interactable.create(target, targetWidth, targetLength);
        if (targetWidth > 0 || targetLength > 0)
            target = Utility.findBestInside(source, targInt);
        boolean projectiles = source.pathfinderProjectiles;
        while (!Region.reachable(targ, targetWidth, targetLength, current, source.width(), source.length())) {
            Direction direction = getDirection(current, target);
            if (!traversable(source, current, targInt, direction, projectiles)) {
                if (direction == Direction.NORTH_WEST) {
                    if (traversable(source, current, targInt, Direction.WEST, projectiles)) {
                        direction = Direction.WEST;
                    } else if (traversable(source, current, targInt, Direction.NORTH, projectiles)) {
                        direction = Direction.NORTH;
                    } else
                        break;
                } else if (direction == Direction.NORTH_EAST) {
                    if (traversable(source, current, targInt, Direction.NORTH, projectiles)) {
                        direction = Direction.NORTH;
                    } else if (traversable(source, current, targInt, Direction.EAST, projectiles)) {
                        direction = Direction.EAST;
                    } else
                        break;
                } else if (direction == Direction.SOUTH_WEST) {
                    if (traversable(source, current, targInt, Direction.SOUTH, projectiles)) {
                        direction = Direction.SOUTH;
                    } else if (traversable(source, current, targInt, Direction.WEST, projectiles)) {
                        direction = Direction.WEST;
                    } else
                        break;
                } else if (direction == Direction.SOUTH_EAST) {
                    if (traversable(source, current, targInt, Direction.SOUTH, projectiles)) {
                        direction = Direction.SOUTH;
                    } else if (traversable(source, current, targInt, Direction.EAST, projectiles)) {
                        direction = Direction.EAST;
                    } else
                        break;
                } else
                    break;
            }
            if (direction == NONE)
                break;
            current = current.transform(direction.getFaceLocation());
            positions.addLast(current);
        }
        return positions;
    }
References com.runehive.game.world.Interactable.create(), com.runehive.game.world.entity.mob.Direction.EAST, com.runehive.util.Utility.findBestInside(), com.runehive.game.world.entity.mob.Direction.getFaceLocation(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.length, com.runehive.game.world.entity.mob.Direction.NORTH, com.runehive.game.world.entity.mob.Direction.NORTH_EAST, com.runehive.game.world.entity.mob.Direction.NORTH_WEST, com.runehive.game.world.entity.mob.Mob.pathfinderProjectiles, com.runehive.game.world.region.Region.reachable(), com.runehive.game.world.entity.mob.Direction.SOUTH, com.runehive.game.world.entity.mob.Direction.SOUTH_EAST, com.runehive.game.world.entity.mob.Direction.SOUTH_WEST, com.runehive.game.world.position.Position.transform(), traversable(), com.runehive.game.world.entity.mob.Direction.WEST, and com.runehive.game.world.entity.Entity.width.
Referenced by find().
find()
Path com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.find (Mob source, Position end, int targetWidth, int targetLength)
A default method to find a path for the specified position.
Returns
A Deque of steps to the specified destination.
Reimplemented from com.runehive.game.world.pathfinding.path.PathFinder.
Definition at line 35 of file SimplePathFinder.java.
{
        int approximation = (int) (source.getPosition().getLongestDelta(end) * 1.5);
        Deque<Position> positions = new ArrayDeque<>(approximation);
        return new Path(addWalks(source, end, targetWidth, targetLength, positions));
    }
References addWalks(), com.runehive.game.world.position.Position.getLongestDelta(), and com.runehive.game.world.entity.Entity.getPosition().
traversable()
boolean com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.traversable (Mob source, Position current, Interactable target, Direction direction, boolean projectiles) private
Definition at line 105 of file SimplePathFinder.java.
{
        Position next = current.transform(direction.getFaceLocation());
        return (projectiles ? projectileCheck(current, next) : traversable(current, source.width(), direction))
                && !Utility.inside(next, source.width(), source.length(), target.getPosition(), target.width(), target.length());
    }
References com.runehive.game.world.entity.mob.Direction.getFaceLocation(), com.runehive.game.world.Interactable.getPosition(), com.runehive.util.Utility.inside(), com.runehive.game.world.entity.Entity.length, com.runehive.game.world.Interactable.length(), com.runehive.game.world.pathfinding.path.PathFinder.projectileCheck(), com.runehive.game.world.position.Position.transform(), traversable(), com.runehive.game.world.entity.Entity.width, and com.runehive.game.world.Interactable.width().
Referenced by addWalks(), and traversable().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/pathfinding/path/impl/SimplePathFinder.java