RuneHive-Game: com.runehive.game.world.entity.mob.Viewport Class Reference
com.runehive.game.world.entity.mob.Viewport Class Reference
Represents a viewport in which a Player can see.
Public Member Functions
boolean add (Mob other)
Adds a Mob to this viewport.
void calculateViewingDistance ()
Determines how many tiles out a player can see players or npcs.
List< Npc > getNpcsInViewport ()
The collection of npcs in this viewport.
int getNpcViewingDistance ()
This is how many tiles out this player can see npcs.
List< Player > getPlayersInViewport ()
The collection of players in this viewport.
int getPlayerViewingDistance ()
How many tiles out this player can see other players.
boolean shouldRemove (Mob other)
Determines if a Mob should be removed from this viewport.
Viewport (Player player)
Static Public Attributes
static final int ADD_THRESHOLD = 15
The amount of entities that can be added to this viewport in a single tick.
static final int CAPACITY = 100
The amount of entities that can be visible at all at once 255 players and 255 npcs.
static final int VIEW_DISTANCE = 15
The amount of tiles out an entity can see within this viewport.
Private Member Functions
boolean canAdd (Mob other)
Determines if a Mob can be added to this viewport.
Private Attributes
final List< Npc > npcsInViewport = new LinkedList<>()
The collection of npcs that are visible in this viewport.
final AtomicInteger npcViewingDistance = new AtomicInteger(VIEW_DISTANCE)
The amount of tiles out this mob can see npcs.
final Player player
The player that this viewport belongs to.
final List< Player > playersInViewport = new LinkedList<>()
The collection of players that are visible in this viewport.
final AtomicInteger playerViewingDistance = new AtomicInteger(VIEW_DISTANCE)
The amount of tiles out this mob can see players.
Detailed Description
Represents a viewport in which a Player can see.
Author
nshusa
Definition at line 15 of file Viewport.java.
Constructor & Destructor Documentation
Viewport()
com.runehive.game.world.entity.mob.Viewport.Viewport (Player player)
Definition at line 43 of file Viewport.java.
{
        this.player = player;
    }
References player.
Referenced by calculateViewingDistance().
Member Function Documentation
add()
boolean com.runehive.game.world.entity.mob.Viewport.add (Mob other)
Adds a Mob to this viewport.
true If the Mob was added, otherwise false.
Definition at line 52 of file Viewport.java.
{
        if (!canAdd(other)) {
            return false;
        }
        if (other.isPlayer()) {
            playersInViewport.add(other.getPlayer());
            other.updateFlags.add(UpdateFlag.APPEARANCE);
        } else if (other.isNpc()) {
            npcsInViewport.add(other.getNpc());
            other.updateFlags.add(UpdateFlag.FACE_COORDINATE); // doing this for players for some reason crashes the players client
        }
        return true;
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, canAdd(), com.runehive.game.world.entity.mob.UpdateFlag.FACE_COORDINATE, com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), npcsInViewport, playersInViewport, and com.runehive.game.world.entity.mob.Mob.updateFlags.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.encode(), and com.runehive.net.packet.out.SendPlayerUpdate.encode().
calculateViewingDistance()
void com.runehive.game.world.entity.mob.Viewport.calculateViewingDistance ()
Determines how many tiles out a player can see players or npcs.
Definition at line 107 of file Viewport.java.
{
        if (playersInViewport.size() >= Viewport.CAPACITY) {
            if (playerViewingDistance.decrementAndGet() < 1) {
                playerViewingDistance.set(1);
            }
        } else {
            if (playerViewingDistance.incrementAndGet() > VIEW_DISTANCE) {
                playerViewingDistance.set(VIEW_DISTANCE);
            }
        }
        if (npcsInViewport.size() >= Viewport.CAPACITY) {
            if (npcViewingDistance.decrementAndGet() < 1) {
                npcViewingDistance.set(1);
            }
        } else {
            if (npcViewingDistance.incrementAndGet() > VIEW_DISTANCE) {
                npcViewingDistance.set(VIEW_DISTANCE);
            }
        }
    }
References npcsInViewport, npcViewingDistance, playersInViewport, playerViewingDistance, VIEW_DISTANCE, and Viewport().
canAdd()
boolean com.runehive.game.world.entity.mob.Viewport.canAdd (Mob other) private
Determines if a Mob can be added to this viewport.
true If this Mob can be added, otherwise false.
Definition at line 72 of file Viewport.java.
{
        if (shouldRemove(other)) {
            return false;
        }
        if (other.isPlayer()) {
            Player player = other.getPlayer();
            return !playersInViewport.contains(player);
        } else if (other.isNpc()) {
            Npc npc = other.getNpc();
            return !npcsInViewport.contains(npc);
        }
        return false;
    }
References com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), npcsInViewport, player, playersInViewport, and shouldRemove().
Referenced by add().
getNpcsInViewport()
List< Npc > com.runehive.game.world.entity.mob.Viewport.getNpcsInViewport ()
The collection of npcs in this viewport.
Definition at line 139 of file Viewport.java.
{
        return npcsInViewport;
    }
References npcsInViewport.
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.Alkahrid.block(), com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), and com.runehive.net.packet.out.SendNpcUpdate.encode().
getNpcViewingDistance()
int com.runehive.game.world.entity.mob.Viewport.getNpcViewingDistance ()
This is how many tiles out this player can see npcs.
Definition at line 153 of file Viewport.java.
{
        return npcViewingDistance.get();
    }
References npcViewingDistance.
getPlayersInViewport()
List< Player > com.runehive.game.world.entity.mob.Viewport.getPlayersInViewport ()
The collection of players in this viewport.
Definition at line 132 of file Viewport.java.
{
        return playersInViewport;
    }
References playersInViewport.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.encode(), and com.runehive.game.world.entity.combat.attack.listener.npc.SergeantStrongstack.hit().
getPlayerViewingDistance()
int com.runehive.game.world.entity.mob.Viewport.getPlayerViewingDistance ()
How many tiles out this player can see other players.
Definition at line 146 of file Viewport.java.
{
        return playerViewingDistance.get();
    }
References playerViewingDistance.
shouldRemove()
boolean com.runehive.game.world.entity.mob.Viewport.shouldRemove (Mob other)
Determines if a Mob should be removed from this viewport.
true If the Mob should be removed, otherwise false.
Definition at line 93 of file Viewport.java.
{
        boolean sameEntity = player == other;
        boolean notValid = !other.isValid();
        boolean notVisible = !other.isVisible();
        boolean notSameInstance = player.instance != other.instance;
        boolean notInDistance = !player.getPosition().isWithinDistance(other.getPosition().copy(), other.isPlayer() ? player.viewport.getPlayerViewingDistance() : player.viewport.getNpcViewingDistance());
        boolean positionChanged = other.positionChange || other.teleportRegion;
        boolean regionChanged = other.regionChange && other.teleporting;
        return sameEntity || notValid || notVisible || notSameInstance || notInDistance || regionChanged || positionChanged;
    }
References com.runehive.game.world.position.Position.copy(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.Entity.instance, com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.Entity.isValid(), com.runehive.game.world.entity.Entity.isVisible(), player, com.runehive.game.world.entity.mob.Mob.teleporting, and com.runehive.game.world.entity.mob.Mob.teleportRegion.
Referenced by canAdd(), com.runehive.net.packet.out.SendNpcUpdate.encode(), and com.runehive.net.packet.out.SendPlayerUpdate.encode().
Member Data Documentation
ADD_THRESHOLD
final int com.runehive.game.world.entity.mob.Viewport.ADD_THRESHOLD = 15 static
The amount of entities that can be added to this viewport in a single tick.
Definition at line 18 of file Viewport.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.encode(), and com.runehive.net.packet.out.SendPlayerUpdate.encode().
CAPACITY
final int com.runehive.game.world.entity.mob.Viewport.CAPACITY = 100 static
The amount of entities that can be visible at all at once 255 players and 255 npcs.
Definition at line 21 of file Viewport.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.encode(), and com.runehive.net.packet.out.SendPlayerUpdate.encode().
npcsInViewport
final List<Npc> com.runehive.game.world.entity.mob.Viewport.npcsInViewport = new LinkedList<>() private
The collection of npcs that are visible in this viewport.
Definition at line 30 of file Viewport.java.
Referenced by add(), calculateViewingDistance(), canAdd(), and getNpcsInViewport().
npcViewingDistance
final AtomicInteger com.runehive.game.world.entity.mob.Viewport.npcViewingDistance = new AtomicInteger(VIEW_DISTANCE) private
The amount of tiles out this mob can see npcs.
Definition at line 36 of file Viewport.java.
Referenced by calculateViewingDistance(), and getNpcViewingDistance().
player
final Player com.runehive.game.world.entity.mob.Viewport.player private
The player that this viewport belongs to.
Definition at line 41 of file Viewport.java.
Referenced by canAdd(), shouldRemove(), and Viewport().
playersInViewport
final List<Player> com.runehive.game.world.entity.mob.Viewport.playersInViewport = new LinkedList<>() private
The collection of players that are visible in this viewport.
Definition at line 27 of file Viewport.java.
Referenced by add(), calculateViewingDistance(), canAdd(), and getPlayersInViewport().
playerViewingDistance
final AtomicInteger com.runehive.game.world.entity.mob.Viewport.playerViewingDistance = new AtomicInteger(VIEW_DISTANCE) private
The amount of tiles out this mob can see players.
Definition at line 33 of file Viewport.java.
Referenced by calculateViewingDistance(), and getPlayerViewingDistance().
VIEW_DISTANCE
final int com.runehive.game.world.entity.mob.Viewport.VIEW_DISTANCE = 15 static
The amount of tiles out an entity can see within this viewport.
Definition at line 24 of file Viewport.java.
Referenced by calculateViewingDistance().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/Viewport.java