RuneHive-Game: com.runehive.game.world.entity.mob.movement.Movement Class Reference
com.runehive.game.world.entity.mob.movement.Movement Class Reference
Handles the movement for the player.
Public Member Functions
boolean addPath (Path path)
Finds a smart path to the target.
void addStep (int x, int y)
Adds a single step to the walking queue, filling in the points to the previous point in the queue if necessary.
boolean aStarPath (Interactable interactable)
Finds a smart path to the target.
boolean aStarPath (Position destination)
Finds a smart path to the target.
boolean dijkstraPath (Interactable interactable)
Finds a medium path to the target.
boolean dijkstraPath (Position destination)
Finds a medium path to the target.
void finish ()
Removes the first waypoint which is only used for calculating directions.
int getRunningDirection ()
AStarPathFinder getSmartPathFinder ()
int getWalkingDirection ()
boolean hasSteps ()
boolean isMovementDone ()
boolean isMoving ()
boolean isRunning ()
Checks if any running flag is set.
boolean isRunningQueue ()
Gets the running queue flag.
boolean isRunningToggled ()
Gets the run toggled flag.
Movement (Mob mob)
Creates the WalkingQueue for the specified.
boolean needsPlacement ()
void onRegionChange ()
Re-emit hint arrow on region change.
Position peekDestination ()
void processNextMovement ()
Processes the next player's movement.
void reset ()
Resets the walking queue so it contains no more steps.
void setRunningQueue (boolean runQueue)
Sets the run queue flag.
void setRunningToggled (boolean runToggled)
Sets the run toggled flag.
boolean simplePath (Interactable interactable)
Finds a smart path to the target.
boolean simplePath (Position destination)
Finds a smart path to the target.
void walk (Position position)
Walks to a certain position.
void walkTo (int x, int y)
Handles mob walking to certain coordinates.
void walkTo (Position position)
Handles mob walking to a certain position.
Public Attributes
Direction lastDirection = Direction.SOUTH
The last direction the mob walked in.
Private Member Functions
void addStepInternal (int x, int y)
Adds a single step to the queue internally without counting gaps.
Point getNextPoint ()
Gets the next point of movement.
Private Attributes
Position destinationHint
Destination hint-arrow state.
boolean isMoving
Mob is moving.
Position lastSentHint
Mob mob
The mob.
int runningDirection = -1
boolean runQueue = false
Run for this queue (CTRL-CLICK) toggle.
boolean runToggled = false
Run toggle (button in client).
final AStarPathFinder smartPathFinder
The smart path finder.
int walkingDirection = -1
Deque< Point > waypoints = new ArrayDeque<>()
The queue of waypoints.
Static Private Attributes
static final DijkstraPathFinder DIJKSTRA_PATH_FINDER = new DijkstraPathFinder()
The smart path finder.
static final int MAXIMUM_SIZE = 50
The maximum size of the queue.
static final SimplePathFinder SIMPLE_PATH_FINDER = new SimplePathFinder()
The smart path finder.
Detailed Description
Handles the movement for the player.
Author
Graham Edgecombe
Definition at line 25 of file Movement.java.
Constructor & Destructor Documentation
Movement()
com.runehive.game.world.entity.mob.movement.Movement.Movement (Mob mob)
Creates the WalkingQueue for the specified.
Definition at line 64 of file Movement.java.
{
        this.mob = mob;
        this.smartPathFinder = new AStarPathFinder(mob, new Manhattan());
    }
References mob.
Member Function Documentation
addPath()
boolean com.runehive.game.world.entity.mob.movement.Movement.addPath (Path path)
Finds a smart path to the target.
Definition at line 264 of file Movement.java.
{
        if (!path.isPossible() || mob.locking.locked(PacketType.MOVEMENT))
            return false;
        path.addSteps(this);
        // Set/update the destination hint after steps are enqueued
        if (mob.isPlayer() && !waypoints.isEmpty()) {
            Point last = waypoints.peekLast();
            Position dest = new Position(last.x, last.y, mob.getHeight());
            destinationHint = dest;
            if (lastSentHint == null || !lastSentHint.equals(dest)) {
                new HintArrowTile(dest).execute(mob.getPlayer());
                lastSentHint = dest;
            }
        }
        return true;
    }
References com.runehive.game.world.pathfinding.path.Path.addSteps(), destinationHint, com.runehive.net.packet.OutgoingPacket.execute(), com.runehive.game.world.pathfinding.path.Path.isPossible(), lastSentHint, mob, com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT, waypoints, com.runehive.game.world.entity.mob.movement.Point.x, and com.runehive.game.world.entity.mob.movement.Point.y.
Referenced by aStarPath(), aStarPath(), dijkstraPath(), dijkstraPath(), com.runehive.util.Utility.fixInsidePosition(), simplePath(), and simplePath().
addStep()
void com.runehive.game.world.entity.mob.movement.Movement.addStep (int x, int y)
Adds a single step to the walking queue, filling in the points to the previous point in the queue if necessary.
Definition at line 120 of file Movement.java.
{
//        if (mob.locked()) return;
        if (waypoints.size() == 0)
            reset();
        Point last = waypoints.peekLast();
        int diffX = x - last.x;
        int diffY = y - last.y;
        int max = Math.max(Math.abs(diffX), Math.abs(diffY));
        for (int i = 0; i < max; i++) {
            if (diffX < 0) {
                diffX++;
            } else if (diffX > 0) {
                diffX--;
            }
            if (diffY < 0) {
                diffY++;
            } else if (diffY > 0) {
                diffY--;
            }
            addStepInternal(x - diffX, y - diffY);
        }
    }
References addStepInternal(), reset(), waypoints, com.runehive.game.world.entity.mob.movement.Point.x, and com.runehive.game.world.entity.mob.movement.Point.y.
Referenced by com.runehive.game.world.pathfinding.path.Path.addSteps(), and walk().
addStepInternal()
void com.runehive.game.world.entity.mob.movement.Movement.addStepInternal (int x, int y) private
Adds a single step to the queue internally without counting gaps.
This method is unsafe if used incorrectly so it is private to protect the queue.
Definition at line 148 of file Movement.java.
{
        if (waypoints.size() >= MAXIMUM_SIZE)
            return;
        Point last = waypoints.peekLast();
        int diffX = x - last.x;
        int diffY = y - last.y;
        int dir = Direction.direction(diffX, diffY);
        if (dir > -1)
            waypoints.add(new Point(x, y, dir));
    }
References com.runehive.game.world.entity.mob.Direction.direction(), MAXIMUM_SIZE, waypoints, com.runehive.game.world.entity.mob.movement.Point.x, and com.runehive.game.world.entity.mob.movement.Point.y.
Referenced by addStep(), walkTo(), and walkTo().
aStarPath() [1/2]
boolean com.runehive.game.world.entity.mob.movement.Movement.aStarPath (Interactable interactable)
Finds a smart path to the target.
Definition at line 259 of file Movement.java.
{
        return !mob.locking.locked(PacketType.MOVEMENT) && addPath(smartPathFinder.find(mob, interactable));
    }
References addPath(), mob, com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT, and smartPathFinder.
aStarPath() [2/2]
boolean com.runehive.game.world.entity.mob.movement.Movement.aStarPath (Position destination)
Finds a smart path to the target.
Definition at line 244 of file Movement.java.
{
        return !mob.locking.locked(PacketType.MOVEMENT) && addPath(smartPathFinder.find(mob, destination));
    }
References addPath(), mob, com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT, and smartPathFinder.
dijkstraPath() [1/2]
boolean com.runehive.game.world.entity.mob.movement.Movement.dijkstraPath (Interactable interactable)
Finds a medium path to the target.
Definition at line 254 of file Movement.java.
{
        return !mob.locking.locked(PacketType.MOVEMENT) && addPath(DIJKSTRA_PATH_FINDER.find(mob, interactable));
    }
References addPath(), DIJKSTRA_PATH_FINDER, mob, and com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT.
dijkstraPath() [2/2]
boolean com.runehive.game.world.entity.mob.movement.Movement.dijkstraPath (Position destination)
Finds a medium path to the target.
Definition at line 239 of file Movement.java.
{
        return !mob.locking.locked(PacketType.MOVEMENT) && addPath(DIJKSTRA_PATH_FINDER.find(mob, destination));
    }
References addPath(), DIJKSTRA_PATH_FINDER, mob, and com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT.
finish()
void com.runehive.game.world.entity.mob.movement.Movement.finish ()
Removes the first waypoint which is only used for calculating directions.
This means walking begins at the correct time.
Definition at line 115 of file Movement.java.
{
        waypoints.removeFirst();
    }
References waypoints.
Referenced by com.runehive.game.world.pathfinding.path.Path.addSteps(), walk(), walkTo(), and walkTo().
getNextPoint()
Point com.runehive.game.world.entity.mob.movement.Movement.getNextPoint () private
Gets the next point of movement.
Definition at line 205 of file Movement.java.
{
        Point p = waypoints.poll();
        if (p == null || p.dir == -1) {
            if (isMoving)
                isMoving = false;
            return null;
        } else {
            int diffX = Direction.DELTA_X[p.dir];
            int diffY = Direction.DELTA_Y[p.dir];
            mob.setPosition(mob.getPosition().transform(diffX, diffY));
            if (!isMoving)
                isMoving = true;
            mob.onStep();
            // Clear the arrow once we arrive at the destination or no steps remain
            if (mob.isPlayer() && destinationHint != null) {
                boolean arrived = mob.getPosition().equals(destinationHint);
                boolean noMoreSteps = waypoints.isEmpty();
                if (arrived || noMoreSteps) {
                    new HintArrowClear().execute(mob.getPlayer());
                    destinationHint = null;
                    lastSentHint = null;
                }
            }
            return p;
        }
    }
References com.runehive.game.world.entity.mob.Direction.DELTA_X, com.runehive.game.world.entity.mob.Direction.DELTA_Y, destinationHint, com.runehive.game.world.entity.mob.movement.Point.dir, com.runehive.net.packet.OutgoingPacket.execute(), isMoving, lastSentHint, mob, and waypoints.
Referenced by processNextMovement().
getRunningDirection()
int com.runehive.game.world.entity.mob.movement.Movement.getRunningDirection ()
Definition at line 326 of file Movement.java.
{
        return runningDirection;
    }
References runningDirection.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.updateMovement(), and com.runehive.net.packet.out.SendPlayerUpdate.updateMovement().
getSmartPathFinder()
AStarPathFinder com.runehive.game.world.entity.mob.movement.Movement.getSmartPathFinder ()
Definition at line 318 of file Movement.java.
{
        return smartPathFinder;
    }
References smartPathFinder.
getWalkingDirection()
int com.runehive.game.world.entity.mob.movement.Movement.getWalkingDirection ()
Definition at line 322 of file Movement.java.
{
        return walkingDirection;
    }
References walkingDirection.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.updateMovement(), and com.runehive.net.packet.out.SendPlayerUpdate.updateMovement().
hasSteps()
boolean com.runehive.game.world.entity.mob.movement.Movement.hasSteps ()
Definition at line 310 of file Movement.java.
{
        return !waypoints.isEmpty();
    }
References waypoints.
Referenced by needsPlacement().
isMovementDone()
boolean com.runehive.game.world.entity.mob.movement.Movement.isMovementDone ()
Definition at line 306 of file Movement.java.
{
        return waypoints.size() == 0;
    }
References waypoints.
isMoving()
boolean com.runehive.game.world.entity.mob.movement.Movement.isMoving ()
Definition at line 302 of file Movement.java.
{
        return isMoving;
    }
References isMoving.
isRunning()
boolean com.runehive.game.world.entity.mob.movement.Movement.isRunning ()
Checks if any running flag is set.
Definition at line 298 of file Movement.java.
{
        return runToggled || runQueue;
    }
References runQueue, and runToggled.
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
isRunningQueue()
boolean com.runehive.game.world.entity.mob.movement.Movement.isRunningQueue ()
Gets the running queue flag.
Definition at line 293 of file Movement.java.
{
        return runQueue;
    }
References runQueue.
isRunningToggled()
boolean com.runehive.game.world.entity.mob.movement.Movement.isRunningToggled ()
Gets the run toggled flag.
Definition at line 288 of file Movement.java.
{
        return runToggled;
    }
References runToggled.
needsPlacement()
boolean com.runehive.game.world.entity.mob.movement.Movement.needsPlacement ()
Definition at line 314 of file Movement.java.
{
        return isMoving || hasSteps();
    }
References hasSteps(), and isMoving.
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.execute(), and com.runehive.util.Utility.fixInsidePosition().
onRegionChange()
void com.runehive.game.world.entity.mob.movement.Movement.onRegionChange ()
Re-emit hint arrow on region change.
Definition at line 331 of file Movement.java.
{
        if (mob.isPlayer() && destinationHint != null) {
            new HintArrowTile(destinationHint).execute(mob.getPlayer());
            lastSentHint = destinationHint;
        }
    }
References destinationHint, com.runehive.net.packet.OutgoingPacket.execute(), lastSentHint, and mob.
peekDestination()
Position com.runehive.game.world.entity.mob.movement.Movement.peekDestination ()
Definition at line 338 of file Movement.java.
{
        final Point last = waypoints.peekLast();
        if (last == null) return null;
        if (waypoints.size() == 1 && last.x == mob.getX() && last.y == mob.getY())
            return null;
        return new Position(last.x, last.y, mob.getHeight());
    }
References mob, waypoints, com.runehive.game.world.entity.mob.movement.Point.x, and com.runehive.game.world.entity.mob.movement.Point.y.
processNextMovement()
void com.runehive.game.world.entity.mob.movement.Movement.processNextMovement ()
Processes the next player's movement.
Definition at line 160 of file Movement.java.
{
        boolean teleporting = mob.teleportTarget != null;
        if (teleporting) {
            reset();
            mob.positionChange = true;
            mob.setPosition(mob.teleportTarget);
            mob.clearTeleportTarget();
        } else {
            Point walkPoint, runPoint = null;
            walkPoint = getNextPoint();
            if (runToggled || runQueue) {
                runPoint = getNextPoint();
            }
            int walkDir = walkPoint == null ? -1 : walkPoint.dir;
            int runDir = runPoint == null ? -1 : runPoint.dir;
            if (runDir != -1) lastDirection = Direction.DIRECTIONS.get(runDir);
            else if (walkDir != -1) lastDirection = Direction.DIRECTIONS.get(walkDir);
            this.walkingDirection = walkDir;
            this.runningDirection = runDir;
        }
        int diffX = mob.getPosition().getLocalX(mob.lastPosition);
        int diffY = mob.getPosition().getLocalY(mob.lastPosition);
        boolean changed = false;
        if (diffX < 16) {
            changed = true;
        } else if (diffX >= 88) {
            changed = true;
        }
        if (diffY < 16) {
            changed = true;
        } else if (diffY >= 88) {
            changed = true;
        }
        if (changed)
            mob.regionChange = true;
//        if (mob.attributes.has("mob-following")) {
//            Waypoint waypoint = mob.attributes.get("mob-following");
//            waypoint.onChange();
//        }
    }
References com.runehive.game.world.entity.mob.movement.Point.dir, com.runehive.game.world.entity.mob.Direction.DIRECTIONS, getNextPoint(), lastDirection, mob, reset(), runQueue, and runToggled.
reset()
void com.runehive.game.world.entity.mob.movement.Movement.reset ()
Resets the walking queue so it contains no more steps.
Definition at line 101 of file Movement.java.
{
        runQueue = false;
        waypoints.clear();
        waypoints.add(new Point(mob.getX(), mob.getY(), -1));
        // Clear any active hint
        if (mob.isPlayer() && destinationHint != null) {
            new HintArrowClear().execute(mob.getPlayer());
            destinationHint = null;
            lastSentHint = null;
        }
    }
References destinationHint, com.runehive.net.packet.OutgoingPacket.execute(), lastSentHint, mob, runQueue, and waypoints.
Referenced by addStep(), com.runehive.game.world.pathfinding.path.Path.addSteps(), com.runehive.game.world.entity.combat.magic.MagicImpact.freeze(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), processNextMovement(), walk(), walkTo(), and walkTo().
setRunningQueue()
void com.runehive.game.world.entity.mob.movement.Movement.setRunningQueue (boolean runQueue)
Sets the run queue flag.
Definition at line 283 of file Movement.java.
{
        this.runQueue = runQueue;
    }
References runQueue.
setRunningToggled()
void com.runehive.game.world.entity.mob.movement.Movement.setRunningToggled (boolean runToggled)
Sets the run toggled flag.
Definition at line 93 of file Movement.java.
{
        this.runToggled = runToggled;
        if (mob.isPlayer()) {
            mob.getPlayer().send(new SendConfig(152, runToggled ? 1 : 0));
        }
    }
References mob, and runToggled.
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), and com.runehive.content.StarterKit.refresh().
simplePath() [1/2]
boolean com.runehive.game.world.entity.mob.movement.Movement.simplePath (Interactable interactable)
Finds a smart path to the target.
Definition at line 249 of file Movement.java.
{
        return !mob.locking.locked(PacketType.MOVEMENT) && addPath(SIMPLE_PATH_FINDER.find(mob, interactable));
    }
References addPath(), mob, com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT, and SIMPLE_PATH_FINDER.
simplePath() [2/2]
boolean com.runehive.game.world.entity.mob.movement.Movement.simplePath (Position destination)
Finds a smart path to the target.
Definition at line 234 of file Movement.java.
{
        return !mob.locking.locked(PacketType.MOVEMENT) && addPath(SIMPLE_PATH_FINDER.find(mob, destination));
    }
References addPath(), mob, com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT, and SIMPLE_PATH_FINDER.
Referenced by com.runehive.content.wintertodt.Wintertodt.shootFlame().
walk()
void com.runehive.game.world.entity.mob.movement.Movement.walk (Position position)
Walks to a certain position.
Definition at line 70 of file Movement.java.
{
        reset();
        addStep(position.getX(), position.getY());
        finish();
    }
References addStep(), finish(), and reset().
Referenced by com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.WalkInteraction.onExecution(), and com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onExecution().
walkTo() [1/2]
void com.runehive.game.world.entity.mob.movement.Movement.walkTo (int x, int y)
Handles mob walking to certain coordinates.
Definition at line 77 of file Movement.java.
{
        final int newX = mob.getX() + x;
        final int newY = mob.getY() + y;
        reset();
        addStepInternal(newX, newY);
        finish();
    }
References addStepInternal(), finish(), mob, and reset().
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), and com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2.onExecution().
walkTo() [2/2]
void com.runehive.game.world.entity.mob.movement.Movement.walkTo (Position position)
Handles mob walking to a certain position.
Definition at line 86 of file Movement.java.
{
        reset();
        addStepInternal(position.getX(), position.getY());
        finish();
    }
References addStepInternal(), finish(), and reset().
Member Data Documentation
destinationHint
Position com.runehive.game.world.entity.mob.movement.Movement.destinationHint private
Destination hint-arrow state.
Definition at line 60 of file Movement.java.
Referenced by addPath(), getNextPoint(), onRegionChange(), and reset().
DIJKSTRA_PATH_FINDER
final DijkstraPathFinder com.runehive.game.world.entity.mob.movement.Movement.DIJKSTRA_PATH_FINDER = new DijkstraPathFinder() static private
The smart path finder.
Definition at line 36 of file Movement.java.
Referenced by dijkstraPath(), and dijkstraPath().
isMoving
boolean com.runehive.game.world.entity.mob.movement.Movement.isMoving private
Mob is moving.
Definition at line 48 of file Movement.java.
Referenced by com.runehive.content.pet.Pets.abandon(), getNextPoint(), isMoving(), and needsPlacement().
lastDirection
Direction com.runehive.game.world.entity.mob.movement.Movement.lastDirection = Direction.SOUTH
The last direction the mob walked in.
Default to south
Definition at line 45 of file Movement.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFaceCoordinateMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceCoordinteMask(), and processNextMovement().
lastSentHint
Position com.runehive.game.world.entity.mob.movement.Movement.lastSentHint private
Definition at line 61 of file Movement.java.
Referenced by addPath(), getNextPoint(), onRegionChange(), and reset().
MAXIMUM_SIZE
final int com.runehive.game.world.entity.mob.movement.Movement.MAXIMUM_SIZE = 50 static private
The maximum size of the queue.
If there are more points than this size, they are discarded.
Definition at line 27 of file Movement.java.
Referenced by addStepInternal().
mob
Mob com.runehive.game.world.entity.mob.movement.Movement.mob private
The mob.
Definition at line 39 of file Movement.java.
Referenced by addPath(), aStarPath(), aStarPath(), dijkstraPath(), dijkstraPath(), getNextPoint(), Movement(), onRegionChange(), peekDestination(), processNextMovement(), reset(), setRunningToggled(), simplePath(), simplePath(), and walkTo().
runningDirection
int com.runehive.game.world.entity.mob.movement.Movement.runningDirection = -1 private
Definition at line 57 of file Movement.java.
Referenced by getRunningDirection().
runQueue
boolean com.runehive.game.world.entity.mob.movement.Movement.runQueue = false private
Run for this queue (CTRL-CLICK) toggle.
Definition at line 54 of file Movement.java.
Referenced by isRunning(), isRunningQueue(), processNextMovement(), reset(), and setRunningQueue().
runToggled
boolean com.runehive.game.world.entity.mob.movement.Movement.runToggled = false private
Run toggle (button in client).
Definition at line 51 of file Movement.java.
Referenced by isRunning(), isRunningToggled(), processNextMovement(), and setRunningToggled().
SIMPLE_PATH_FINDER
final SimplePathFinder com.runehive.game.world.entity.mob.movement.Movement.SIMPLE_PATH_FINDER = new SimplePathFinder() static private
The smart path finder.
Definition at line 33 of file Movement.java.
Referenced by simplePath(), and simplePath().
smartPathFinder
final AStarPathFinder com.runehive.game.world.entity.mob.movement.Movement.smartPathFinder private
The smart path finder.
Definition at line 30 of file Movement.java.
Referenced by aStarPath(), aStarPath(), and getSmartPathFinder().
walkingDirection
int com.runehive.game.world.entity.mob.movement.Movement.walkingDirection = -1 private
Definition at line 56 of file Movement.java.
Referenced by getWalkingDirection().
waypoints
Deque<Point> com.runehive.game.world.entity.mob.movement.Movement.waypoints = new ArrayDeque<>() private
The queue of waypoints.
Definition at line 42 of file Movement.java.
Referenced by addPath(), addStep(), addStepInternal(), finish(), getNextPoint(), hasSteps(), isMovementDone(), peekDestination(), and reset().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/movement/Movement.java