RuneHive-Game: com.runehive.game.world.entity.mob.npc.NpcDeath Class Reference
com.runehive.game.world.entity.mob.npc.NpcDeath Class Reference
Handles a npc dying.
Public Member Functions
void death ()
The main part of the death process where the killer is found for the character.
NpcDeath (Npc mob)
Creates a new MobDeath.
NpcDeath (Npc mob, Runnable runnable)
void postDeath (Mob killer)
The last part of the death process where the character is reset.
void preDeath (Mob killer)
The part of the death process where the character is prepared for the rest of the death tick.
Public Member Functions inherited from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >
final void execute ()
A function representing the unit of work that will be carried out.
MobDeath (T mob, int delay)
Creates a new MobDeath.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Private Attributes
Runnable runnable
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
Protected Attributes inherited from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >
final T mob
The mob.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
Handles a npc dying.
(Used mostly for custom statements).
Author
Daniel
Stand Up
Definition at line 31 of file NpcDeath.java.
Constructor & Destructor Documentation
NpcDeath() [1/2]
com.runehive.game.world.entity.mob.npc.NpcDeath.NpcDeath (Npc mob)
Creates a new MobDeath.
Definition at line 35 of file NpcDeath.java.
{
        this(mob, () -> {
        });
    }
References com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob.
NpcDeath() [2/2]
com.runehive.game.world.entity.mob.npc.NpcDeath.NpcDeath (Npc mob, Runnable runnable)
Definition at line 40 of file NpcDeath.java.
{
        super(mob, mob.getDeathTime());
        this.runnable = runnable;
    }
References com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob, and runnable.
Member Function Documentation
death()
void com.runehive.game.world.entity.mob.npc.NpcDeath.death ()
The main part of the death process where the killer is found for the character.
Reimplemented from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.
Definition at line 55 of file NpcDeath.java.
{
        if (mob.owner != null || mob.definition == null || mob.definition.getRespawnTime() == -1) {
            mob.unregister();
            return;
        }
        mob.setVisible(false);
        World.schedule(mob.definition.getRespawnTime(), () -> {
            mob.move(mob.spawnPosition);
            mob.npcAssistant.respawn();
            mob.unvenom();
            mob.unpoison();
        });
    }
References com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob, and com.runehive.game.world.World.schedule().
postDeath()
void com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath (Mob killer)
The last part of the death process where the character is reset.
Reimplemented from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.
Definition at line 71 of file NpcDeath.java.
{
        if (killer == null)
            return;
        /* Npc name. */
        String name = mob.getName().toUpperCase().replace(" ", "_");
        runnable.run();
        switch (killer.getType()) {
            case PLAYER:
                Player playerKiller = killer.getPlayer();
                CollectionLog.onNpcKill(playerKiller, mob.id);
                /* Npc drop. */
                NpcDropManager.drop(playerKiller, mob);
                /* The slayer kill activator. */
                playerKiller.slayer.activate(mob, 1);
                /* The followers. */
                if (playerKiller.followers.contains(mob.getNpc())) {
                    playerKiller.followers.remove(mob);
                }
                /* Activity. */
                EventDispatcher.execute(playerKiller, new OnKillEvent(mob));
                /* Warrior Guild */
                if (Arrays.stream(WarriorGuildUtility.CYCLOPS).anyMatch(cyclop -> cyclop == mob.id) && (Utility.random(20) == 0)) {
                    Item defender = new Item(WarriorGuildUtility.getDefender(playerKiller), 1);
                    GroundItem.create(playerKiller, defender, mob.getPosition());
                    return;
                }
                /* Switch statement. */
                switch (name) {
                    case "SKOTIZO":
                        SkotizoUtility.defeated(mob, playerKiller);
                        playerKiller.activityLogger.add(ActivityLog.SKOTIZO);
                        return;
                    case "ZULRAH":
                        playerKiller.activityLogger.add(ActivityLog.ZULRAH);
                        AchievementHandler.activate(playerKiller, AchievementKey.ZULRAH, 1);
                        return;
                    case "CERBERUS":
                        playerKiller.activityLogger.add(ActivityLog.CERBERUS);
                        AchievementHandler.activate(playerKiller, AchievementKey.CERBERUS, 1);
                        return;
                    case "GENERAL_GRAARDOR":
                        playerKiller.activityLogger.add(ActivityLog.GENERAL_GRAARDOR);
                        AchievementHandler.activate(playerKiller, AchievementKey.GRAARDOR, 1);
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.GENERAL_GRAARDOR, playerKiller.getName()));
                        return;
                    case "LAVA_DRAGON":
                        playerKiller.activityLogger.add(ActivityLog.LAVA_DRAGON);
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BLACK_DRAGON, playerKiller.getName()));
                        return;
                    case "KRAKEN":
                        playerKiller.activityLogger.add(ActivityLog.KRAKEN);
                        return;
                    case "COMMANDER_ZILYANA":
                        playerKiller.activityLogger.add(ActivityLog.COMMANDER_ZILYANA);
                        AchievementHandler.activate(playerKiller, AchievementKey.ZILYANA, 1);
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.COMMANDER_ZILYANA, playerKiller.getName()));
                        return;
                    case "KREE'ARRA":
                        playerKiller.activityLogger.add(ActivityLog.KREE_ARRA);
                        AchievementHandler.activate(playerKiller, AchievementKey.KREE, 1);
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.KREEARRA, playerKiller.getName()));
                        return;
                    case "K'RIL TSUTSAROTH":
                        playerKiller.activityLogger.add(ActivityLog.KRIL_TSUTSAROTH);
                        AchievementHandler.activate(playerKiller, AchievementKey.KRIL, 1);
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.KRIL_TSUTSAROTH, playerKiller.getName()));
                        return;
                    case "CORPOREAL_BEAST":
                        playerKiller.activityLogger.add(ActivityLog.CORPOREAL_BEAST);
                        return;
                    case "LIZARD_SHAMAN":
                        playerKiller.activityLogger.add(ActivityLog.LIZARD_SHAMAN);
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.LIZARD_SHAMAN, playerKiller.getName()));
                        return;
                    case "MITHRIL_DRAGON":
                        playerKiller.activityLogger.add(ActivityLog.MITHRIL_DRAGON);
                        return;
                    case "DARK_BEAST":
                        playerKiller.activityLogger.add(ActivityLog.DARK_BEAST);
                        return;
                    case "ANGRY_BARBARIAN_SPIRIT":
                        GroundItem.create(playerKiller, new Item(2404));
                        return;
                    case "HILL_GIANT":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.HILL_GIANT, playerKiller.getName()));
                        return;
                    case "BLACK_DEMON":
                    case "BLACK_DEMONS":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BLACK_DEMON, playerKiller.getName()));
                        return;
                    case "GREATER_DEMON":
                    case "GREATER_DEMONS":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.GREATER_DEMON, playerKiller.getName()));
                        return;
                    case "ROCK_CRAB":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.ROCK_CRAB, playerKiller.getName()));
                        return;
                    case "SAND_CRAB":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.SAND_CRAB, playerKiller.getName()));
                        return;
                    case "BLUE_DRAGON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BLUE_DRAGON, playerKiller.getName()));
                        return;
                    case "RED_DRAGON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.RED_DRAGON, playerKiller.getName()));
                        return;
                    case "GREEN_DRAGON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.GREEN_DRAGON, playerKiller.getName()));
                        return;
                    case "BLACK_DRAGON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BLACK_DRAGON, playerKiller.getName()));
                        return;
                    case "KING_BLACK_DRAGON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BLACK_DRAGON, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.KING_BLACK_DRAGON);
                        AchievementHandler.activate(playerKiller, AchievementKey.KING_BLACK_DRAGON);
                        return;
                    case "CHAOS_ELEMENTAL":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.CHAOS_ELEMENTAL, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.CHAOS_ELEMENTAL);
                        return;
                    case "CHAOS_FANATIC":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.CHAOS_FANATIC, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.CHAOS_FANATIC);
                        return;
                    case "CRAZY_ARCHAEOLOGIST":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.CRAZY_ARCHAEOLOGIST, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.CRAZY_ARCHAEOLOGIST);
                        return;
                    case "CALLISTO":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.CALLISTO, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.CALLISTO);
                        return;
                    case "SCORPIA":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.SCORPIA, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.SCORPIA);
                        return;
                    case "VET'ION":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.VETION, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.VETION);
                        return;
                    case "VENANTIS":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.VENNANTIS, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.VENANTIS);
                        return;
                    case "SKELETAL_WYVERN":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.SKELETAL_WYVERN, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.SKELETAL_WYVERN);
                        return;
                    case "ABYSSAL_DEMON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.ABYSSAL_DEMON, playerKiller.getName()));
                        playerKiller.activityLogger.add(ActivityLog.ABYSSAL_DEMON);
                        return;
                    case "GHOST":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.GHOST, playerKiller.getName()));
                        return;
                    case "SKELETON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.SKELETON, playerKiller.getName()));
                        return;
                    case "BLACK_KNIGHT":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BLACK_KNIGHT, playerKiller.getName()));
                        return;
                    case "BABY_BLUE_DRAGON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BABY_BLUE_DRAGON, playerKiller.getName()));
                        return;
                    case "BAT":
                    case "GIANT_BAT":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BAT, playerKiller.getName()));
                        return;
                    case "CHAOS_DWARF":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.CHAOS_DWARF, playerKiller.getName()));
                        return;
                    case "MAGIC_AXE":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.MAGIC_AXE, playerKiller.getName()));
                        return;
                    case "CAVE_CRAWLER":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.CAVE_CRAWLER, playerKiller.getName()));
                        return;
                    case "CRAWLING_HAND":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.CRAWLING_HAND, playerKiller.getName()));
                        return;
                    case "BANSHEE":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BANSHEE, playerKiller.getName()));
                        return;
                    case "ICE_FIEND":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.ICE_FIEND, playerKiller.getName()));
                        return;
                    case "HELLHOUND":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.HELLHOUND, playerKiller.getName()));
                        return;
                    case "CAVE_HORROR":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.CAVE_HORROR, playerKiller.getName()));
                        return;
                    case "STEEL_DRAGON":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.STEEL_DRAGON, playerKiller.getName()));
                        return;
                    case "PYRE_FIEND":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.PYRE_FIEND, playerKiller.getName()));
                        return;
                    case "FIRE_GIANT":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.FIRE_GIANT, playerKiller.getName()));
                        return;
                    case "BASILISK":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BASILISK, playerKiller.getName()));
                        return;
                    case "COCKATRICE":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.COCKATRICE, playerKiller.getName()));
                        return;
                    case "DUST_DEVIL":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.DUST_DEVIL, playerKiller.getName()));
                        return;
                    case "SPIRITUAL_RANGER":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.SPIRITUAL_RANGER, playerKiller.getName()));
                        return;
                    case "SPIRITUAL_WARRIOR":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.SPIRITUAL_WARRIOR, playerKiller.getName()));
                        return;
                    case "BLOODVELD":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.BLOODVELD, playerKiller.getName()));
                        return;
                    case "SPIRITUAL_MAGE":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.SPIRITUAL_MAGE, playerKiller.getName()));
                        return;
                    case "NECHRYAEL":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.NECHRYAEL, playerKiller.getName()));
                        return;
                    case "SMOKE_DEVIL":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.SMOKE_DEVIL, playerKiller.getName()));
                        return;
                    case "REVENANT_IMP":
                    case "REVENANT_GOBLIN":
                    case "REVENANT_PYREFIEND":
                    case "REVENANT_HOBGOBLIN":
                    case "REVENANT_CYCLOPS":
                    case "REVENANT_HELLHOUND":
                    case "REVENANT_DEMON":
                    case "REVENANT_ORK":
                    case "REVENANT_DARK_BEAST":
                    case "REVENANT_DRAGON":
                        AchievementHandler.activate(playerKiller, AchievementKey.REVS);
                        return;
                    case "DEMONIC_GORILLA":
                        playerKiller.forClan(channel -> channel.activateTask(ClanTaskKey.DEMONIC_GORILLA, playerKiller.getName()));
                        return;
                }
                break;
            case NPC:
//                Npc npcKiller = killer.getNpc();
                break;
        }
    }
References com.runehive.content.ActivityLog.ABYSSAL_DEMON, com.runehive.content.clanchannel.content.ClanTaskKey.ABYSSAL_DEMON, com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.content.skill.impl.slayer.Slayer.activate(), com.runehive.game.world.entity.mob.player.Player.activityLogger, com.runehive.content.ActivityLogger.add(), com.runehive.content.clanchannel.content.ClanTaskKey.BABY_BLUE_DRAGON, com.runehive.content.clanchannel.content.ClanTaskKey.BANSHEE, com.runehive.content.clanchannel.content.ClanTaskKey.BASILISK, com.runehive.content.clanchannel.content.ClanTaskKey.BAT, com.runehive.content.clanchannel.content.ClanTaskKey.BLACK_DEMON, com.runehive.content.clanchannel.content.ClanTaskKey.BLACK_DRAGON, com.runehive.content.clanchannel.content.ClanTaskKey.BLACK_KNIGHT, com.runehive.content.clanchannel.content.ClanTaskKey.BLOODVELD, com.runehive.content.clanchannel.content.ClanTaskKey.BLUE_DRAGON, com.runehive.content.ActivityLog.CALLISTO, com.runehive.content.clanchannel.content.ClanTaskKey.CALLISTO, com.runehive.content.clanchannel.content.ClanTaskKey.CAVE_CRAWLER, com.runehive.content.clanchannel.content.ClanTaskKey.CAVE_HORROR, com.runehive.content.achievement.AchievementKey.CERBERUS, com.runehive.content.ActivityLog.CERBERUS, com.runehive.content.clanchannel.content.ClanTaskKey.CHAOS_DWARF, com.runehive.content.ActivityLog.CHAOS_ELEMENTAL, com.runehive.content.clanchannel.content.ClanTaskKey.CHAOS_ELEMENTAL, com.runehive.content.ActivityLog.CHAOS_FANATIC, com.runehive.content.clanchannel.content.ClanTaskKey.CHAOS_FANATIC, com.runehive.content.clanchannel.content.ClanTaskKey.COCKATRICE, com.runehive.content.ActivityLog.COMMANDER_ZILYANA, com.runehive.content.clanchannel.content.ClanTaskKey.COMMANDER_ZILYANA, com.runehive.content.ActivityLog.CORPOREAL_BEAST, com.runehive.content.clanchannel.content.ClanTaskKey.CRAWLING_HAND, com.runehive.content.ActivityLog.CRAZY_ARCHAEOLOGIST, com.runehive.content.clanchannel.content.ClanTaskKey.CRAZY_ARCHAEOLOGIST, com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.CYCLOPS, com.runehive.content.ActivityLog.DARK_BEAST, com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.defeated(), com.runehive.content.clanchannel.content.ClanTaskKey.DEMONIC_GORILLA, com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), com.runehive.content.clanchannel.content.ClanTaskKey.DUST_DEVIL, com.runehive.content.event.EventDispatcher.execute(), com.runehive.content.clanchannel.content.ClanTaskKey.FIRE_GIANT, com.runehive.game.world.entity.mob.Mob.followers, com.runehive.game.world.entity.mob.player.Player.forClan(), com.runehive.content.ActivityLog.GENERAL_GRAARDOR, com.runehive.content.clanchannel.content.ClanTaskKey.GENERAL_GRAARDOR, com.runehive.content.activity.impl.warriorguild.WarriorGuildUtility.getDefender(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.Entity.getType(), com.runehive.content.clanchannel.content.ClanTaskKey.GHOST, com.runehive.content.achievement.AchievementKey.GRAARDOR, com.runehive.content.clanchannel.content.ClanTaskKey.GREATER_DEMON, com.runehive.content.clanchannel.content.ClanTaskKey.GREEN_DRAGON, com.runehive.content.clanchannel.content.ClanTaskKey.HELLHOUND, com.runehive.content.clanchannel.content.ClanTaskKey.HILL_GIANT, com.runehive.content.clanchannel.content.ClanTaskKey.ICE_FIEND, com.runehive.content.achievement.AchievementKey.KING_BLACK_DRAGON, com.runehive.content.ActivityLog.KING_BLACK_DRAGON, com.runehive.content.ActivityLog.KRAKEN, com.runehive.content.achievement.AchievementKey.KREE, com.runehive.content.ActivityLog.KREE_ARRA, com.runehive.content.clanchannel.content.ClanTaskKey.KREEARRA, com.runehive.content.achievement.AchievementKey.KRIL, com.runehive.content.ActivityLog.KRIL_TSUTSAROTH, com.runehive.content.clanchannel.content.ClanTaskKey.KRIL_TSUTSAROTH, com.runehive.content.ActivityLog.LAVA_DRAGON, com.runehive.content.ActivityLog.LIZARD_SHAMAN, com.runehive.content.clanchannel.content.ClanTaskKey.LIZARD_SHAMAN, com.runehive.content.clanchannel.content.ClanTaskKey.MAGIC_AXE, com.runehive.content.ActivityLog.MITHRIL_DRAGON, com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob, com.runehive.content.clanchannel.content.ClanTaskKey.NECHRYAEL, com.runehive.content.collectionlog.CollectionLog.onNpcKill(), com.runehive.content.clanchannel.content.ClanTaskKey.PYRE_FIEND, com.runehive.util.Utility.random(), com.runehive.content.clanchannel.content.ClanTaskKey.RED_DRAGON, com.runehive.content.achievement.AchievementKey.REVS, com.runehive.content.clanchannel.content.ClanTaskKey.ROCK_CRAB, runnable, com.runehive.content.clanchannel.content.ClanTaskKey.SAND_CRAB, com.runehive.content.ActivityLog.SCORPIA, com.runehive.content.clanchannel.content.ClanTaskKey.SCORPIA, com.runehive.content.ActivityLog.SKELETAL_WYVERN, com.runehive.content.clanchannel.content.ClanTaskKey.SKELETAL_WYVERN, com.runehive.content.clanchannel.content.ClanTaskKey.SKELETON, com.runehive.content.ActivityLog.SKOTIZO, com.runehive.game.world.entity.mob.player.Player.slayer, com.runehive.content.clanchannel.content.ClanTaskKey.SMOKE_DEVIL, com.runehive.content.clanchannel.content.ClanTaskKey.SPIRITUAL_MAGE, com.runehive.content.clanchannel.content.ClanTaskKey.SPIRITUAL_RANGER, com.runehive.content.clanchannel.content.ClanTaskKey.SPIRITUAL_WARRIOR, com.runehive.content.clanchannel.content.ClanTaskKey.STEEL_DRAGON, com.runehive.content.ActivityLog.VENANTIS, com.runehive.content.clanchannel.content.ClanTaskKey.VENNANTIS, com.runehive.content.ActivityLog.VETION, com.runehive.content.clanchannel.content.ClanTaskKey.VETION, com.runehive.content.achievement.AchievementKey.ZILYANA, com.runehive.content.achievement.AchievementKey.ZULRAH, and com.runehive.content.ActivityLog.ZULRAH.
preDeath()
void com.runehive.game.world.entity.mob.npc.NpcDeath.preDeath (Mob killer)
The part of the death process where the character is prepared for the rest of the death tick.
Reimplemented from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.
Definition at line 46 of file NpcDeath.java.
{
        if (mob.definition == null) {
            return;
        }
        mob.animate(new Animation(mob.definition.getDeathAnimation(), UpdatePriority.VERY_HIGH));
    }
References com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob, and com.runehive.game.UpdatePriority.VERY_HIGH.
Member Data Documentation
runnable
Runnable com.runehive.game.world.entity.mob.npc.NpcDeath.runnable private
Definition at line 32 of file NpcDeath.java.
Referenced by NpcDeath(), and postDeath().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/npc/NpcDeath.java