RuneHive-Game: com.runehive.content.DropDisplay Class Reference
com.runehive.content.DropDisplay Class Reference
Handles displaying the npc drops on an itemcontainer.
Classes
enum DropType
Static Public Member Functions
static void display (Player player, NpcDropTable definition)
static void open (Player player)
static void search (Player player, String context, DropType type)
Static Private Attributes
static final String[] DEFAULT
Detailed Description
Handles displaying the npc drops on an itemcontainer.
Author
Daniel
Definition at line 25 of file DropDisplay.java.
Member Function Documentation
display()
void com.runehive.content.DropDisplay.display (Player player, NpcDropTable definition) static
Definition at line 104 of file DropDisplay.java.
{
        int size = definition == null ? 9 : definition.drops.length < 9 ? 9 : definition.drops.length;
        player.send(new SendScrollbar(54550, definition == null ? 350 : (size * 32)));
        player.send(new SendString(definition == null ? "" : "Drops: " + definition.drops.length, 54514));
        player.send(new SendString(definition == null ? "" : "" + NpcDefinition.get(definition.npcIds[0]).getName(), 54513));
        for (int index = 0, string = 54552; index < size; index++) {
            boolean valid = definition != null && (index < definition.drops.length && (NpcDefinition.get(definition.npcIds[0]) != null));
            NpcDrop drop = valid ? definition.drops[index] : null;
            Item item = valid ? new Item(drop.id, drop.maximum) : null;
            player.send(new SendItemOnInterfaceSlot(54551, item, index));
            string++;
            player.send(new SendString(!valid ? "" : item.getName(), string));
//            player.send(new SendString(!valid ? "" : item.getName() + " (<col=ffffff>" + item.getId() + "</col>)", string));
            string++;
            player.send(new SendString(!valid ? "" : Utility.formatDigits(drop.minimum), string));
            string++;
            player.send(new SendString(!valid ? "" : Utility.formatDigits(drop.maximum), string));
            string++;
            player.send(new SendString(!valid ? "" : drop.type.toString(), string));
            string++;
        }
    }
References com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.drops, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getName(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.npc.drop.NpcDrop.id, com.runehive.game.world.entity.mob.npc.drop.NpcDrop.maximum, com.runehive.game.world.entity.mob.npc.drop.NpcDrop.minimum, com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.npcIds, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.toString(), and com.runehive.game.world.entity.mob.npc.drop.NpcDrop.type.
Referenced by open(), and search().
open()
void com.runehive.content.DropDisplay.open (Player player) static
Definition at line 49 of file DropDisplay.java.
{
        search(player, Utility.randomElement(DEFAULT), DropType.NPC);
        List<Integer> key = player.attributes.get("DROP_DISPLAY_KEY", List.class);
        display(player, NpcDropManager.NPC_DROPS.get(key.get(0)));
        player.interfaceManager.open(54500);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, DEFAULT, display(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.content.DropDisplay.DropType.NPC, com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.NPC_DROPS, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.util.Utility.randomElement(), and search().
Referenced by com.runehive.game.plugin.PluginContext.onClick().
search()
void com.runehive.content.DropDisplay.search (Player player, String context, DropType type) static
Definition at line 56 of file DropDisplay.java.
{
        context = context.trim().toLowerCase();
        List<String> npc = new ArrayList<>();
        List<Integer> integer = new ArrayList<>();
        for (Map.Entry<Integer, NpcDropTable> drop : NpcDropManager.NPC_DROPS.entrySet()) {
            NpcDropTable definition = drop.getValue();
            if (NpcDefinition.get(definition.npcIds[0]) == null)
                continue;
            String name = NpcDefinition.get(definition.npcIds[0]).getName();
            if (type == DropType.NPC) {
                if (name.toLowerCase().contains(context)) {
                    if (!npc.contains(name)) {
                        npc.add(name);
                        integer.add(definition.npcIds[0]);
                    }
                }
            } else if (type == DropType.ITEM) {
                for (NpcDrop item : definition.drops) {
                    String itemName = ItemDefinition.get(item.id).getName();
                    if (itemName.toLowerCase().contains(context)) {
                        if (!npc.contains(name)) {
                            npc.add(name);
                            integer.add(definition.npcIds[0]);
                        }
                    }
                }
            }
        }
        if (integer.isEmpty()) {
            player.dialogueFactory.sendStatement("No search was found for your entry!").execute();
            return;
        }
        int size = npc.size() < 10 ? 10 : npc.size();
        for (int index = 0, string = 54516; index < size; index++, string += 2) {
            if (string >= 54551)
                break;
            String name = index >= npc.size() ? "" : npc.get(index);
            player.send(new SendTooltip(name.isEmpty() ? "" : "View drop table of <col=ff9933>" + name, string));
            player.send(new SendString(name, string + 1));
        }
        player.attributes.set("DROP_DISPLAY_KEY", integer);
        player.send(new SendScrollbar(54515, 280));
        display(player, NpcDropManager.NPC_DROPS.get(0));
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, display(), com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.drops, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getName(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.mob.npc.drop.NpcDrop.id, com.runehive.content.DropDisplay.DropType.ITEM, com.runehive.content.DropDisplay.DropType.NPC, com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.NPC_DROPS, com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.npcIds, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and com.runehive.util.generic.GenericAttributes.set().
Referenced by open().
Member Data Documentation
DEFAULT
final String [] com.runehive.content.DropDisplay.DEFAULT static private
Initial value:
= {
            "King black dragon",
            "Skotizo",
            "Zulrah",
            "Callisto",
            "Commander",
            "Vene",
            "Kraken",
            "Chaos fanatic",
            "Scorpia",
            "Corporeal beast",
            "Lizard shaman",
            "Cerberus",
            "Vorkath",
            "Skeletal wyverns",
    }
Definition at line 32 of file DropDisplay.java.
{
            "King black dragon",
            "Skotizo",
            "Zulrah",
            "Callisto",
            "Commander",
            "Vene",
            "Kraken",
            "Chaos fanatic",
            "Scorpia",
            "Corporeal beast",
            "Lizard shaman",
            "Cerberus",
            "Vorkath",
            "Skeletal wyverns",
    };
Referenced by open().
The documentation for this class was generated from the following file:
java/com/runehive/content/DropDisplay.java