RuneHive-Game: com.runehive.content.pet.Pets Class Reference
com.runehive.content.pet.Pets Class Reference
Handles spawning, rewarding and picking up of pets.
Static Public Member Functions
static Task abandon (Npc npc)
The pet abandon task.
static void buyInsurance (Player player, Item item)
Handles purchasing insurance for a pet.
static void claimLostPets (Player player)
Claims all the lost pets.
static boolean dialogue (Player player, Npc npc)
Handles speaking to a pet.
static void onDeath (Player player)
Handles what happens to a pet when a player dies.
static void onLogin (Player player)
Handles what happens to a pet when a player logs in.
static void onLogout (Player player)
Handles what happens to a pet when a player logouts.
static void onReward (Player player, int item)
Handles rewarding with a 100% a chance.
static void onReward (Player player, int item, int chance)
Handles calculating the chance of a player receiving a skilling pet.
static boolean onReward (Player player, PetData pet)
Generates a unique equation for special defined pets.
static boolean onSpawn (Player player, int item, boolean drop)
Handles spawning a pet.
static void openInsurance (Player player)
Handles opening the insurance interface.
static void openLostPets (Player player)
Handles opening the insurance interface.
Static Public Attributes
static final int INSRUANCE_COST = 8000000
The cost of insuring a pet.
Static Private Member Functions
static boolean hasInsurance (Player player, PetData pet)
Checks if player already has insurance for a pet.
static void onObtain (Player player, int item)
Handles a player receiving a pet onReward.
Detailed Description
Handles spawning, rewarding and picking up of pets.
Author
Daniel
Definition at line 27 of file Pets.java.
Member Function Documentation
abandon()
Task com.runehive.content.pet.Pets.abandon (Npc npc) static
The pet abandon task.
Definition at line 184 of file Pets.java.
{
        return new Task(5) {
            int count = 0;
            @Override
            protected void onSchedule() {
                npc.resetWaypoint();
                npc.resetFace();
            }
            @Override
            protected void execute() {
                if (count >= 15) {
                    cancel();
                    return;
                }
                if (npc.movement.isMoving()) {
                    return;
                }
                Position[] boundaries = Utility.getInnerBoundaries(npc.getPosition().transform(-3, -2), 7, 7);
                npc.walk(Utility.randomElement(boundaries));
                count++;
            }
            @Override
            protected void onCancel(boolean logout) {
                npc.unregister();
            }
        };
    }
References com.runehive.util.Utility.getInnerBoundaries(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.movement.Movement.isMoving, com.runehive.game.world.entity.mob.Mob.movement, com.runehive.util.Utility.randomElement(), com.runehive.game.world.entity.mob.Mob.resetFace(), com.runehive.game.world.entity.mob.Mob.resetWaypoint(), com.runehive.game.world.position.Position.transform(), com.runehive.game.world.entity.mob.npc.Npc.unregister(), and com.runehive.game.world.entity.mob.npc.Npc.walk.
Referenced by onDeath().
buyInsurance()
void com.runehive.content.pet.Pets.buyInsurance (Player player, Item item) static
Handles purchasing insurance for a pet.
Definition at line 238 of file Pets.java.
{
        Optional<PetData> petData = PetData.forItem(item.getId());
        if (!petData.isPresent()) {
            player.dialogueFactory.sendNpcChat(7601, "I can't insure " + item.getName() + "!", "What do I look like to you?", "Show me some respect and use a pet on me.").execute();
            return;
        }
        if (hasInsurance(player, petData.get())) {
            player.dialogueFactory.sendNpcChat(7601, "You already have insurance for " + petData.get().getName() + "!").execute();
            return;
        }
        if (!player.inventory.contains(995, INSRUANCE_COST)) {
            player.dialogueFactory.sendNpcChat(7601, "Naw, it's going to cost " + Utility.formatDigits(INSRUANCE_COST) + " coins", "to insure your pet. Start hustling fam.").execute();
            return;
        }
        player.inventory.remove(995, INSRUANCE_COST);
        player.petInsurance.add(petData.get());
        player.dialogueFactory.sendNpcChat(7601, "You can put your trust in my that I will", "protect your little " + petData.get().getName() + ".").execute();
    }
References com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.pet.PetData.forItem(), com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), hasInsurance(), INSRUANCE_COST, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.petInsurance, com.runehive.game.world.items.containers.ItemContainer.remove(), and com.runehive.content.dialogue.DialogueFactory.sendNpcChat().
claimLostPets()
void com.runehive.content.pet.Pets.claimLostPets (Player player) static
Claims all the lost pets.
Definition at line 258 of file Pets.java.
{
        if (player.lostPets.isEmpty()) {
            player.dialogueFactory.sendNpcChat(7601, "You have no lost pets to claim!");
            return;
        }
        int cost = player.lostPets.size() * 250_000;
        if (!player.inventory.contains(995, cost)) {
            player.dialogueFactory.sendNpcChat(7601, "You need " + Utility.formatDigits(cost) + " coins to claim all", "of your lost pets.");
            return;
        }
        if (player.inventory.getFreeSlots() < player.lostPets.size()) {
            player.dialogueFactory.sendNpcChat(7601, "You need " + player.lostPets.size() + " free inventory spaces", "to claim your pets!");
            return;
        }
        player.inventory.remove(995, cost);
        player.lostPets.forEach(petData -> player.inventory.add(new Item(petData.getItem(), 1)));
        player.lostPets.clear();
        player.dialogueFactory.sendNpcChat(7601, "You have claimed all your lost pets for " + Utility.formatDigits(cost) + " coins.");
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.lostPets, com.runehive.game.world.items.containers.ItemContainer.remove(), and com.runehive.content.dialogue.DialogueFactory.sendNpcChat().
dialogue()
boolean com.runehive.content.pet.Pets.dialogue (Player player, Npc npc) static
Handles speaking to a pet.
Definition at line 128 of file Pets.java.
{
        Optional<PetData> pet = PetData.forNpc(npc.id);
        if (!pet.isPresent()) {
            return false;
        }
        if (npc.owner == null || !npc.owner.equals(player)) {
            player.send(new SendMessage(npc.getName() + " seems uninterested in speaking to you."));
            return true;
        }
        pet.get().dialogue(player.dialogueFactory);
        return true;
    }
References com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.game.world.entity.Entity.equals(), com.runehive.content.pet.PetData.forNpc(), com.runehive.game.world.entity.mob.npc.Npc.getName(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.npc.Npc.owner, and com.runehive.game.world.entity.mob.player.Player.send().
hasInsurance()
boolean com.runehive.content.pet.Pets.hasInsurance (Player player, PetData pet) static private
Checks if player already has insurance for a pet.
Definition at line 317 of file Pets.java.
{
        return player.petInsurance.contains(pet);
    }
References com.runehive.game.world.entity.mob.player.Player.petInsurance.
Referenced by buyInsurance(), onDeath(), and openInsurance().
onDeath()
void com.runehive.content.pet.Pets.onDeath (Player player) static
Handles what happens to a pet when a player dies.
TODO: MULTIPLE OF THE SAME PET
Definition at line 142 of file Pets.java.
{
        Map<PetData, Boolean> lostPets = new HashMap<>();
        if (player.pet != null) {
            Optional<PetData> petData = PetData.forNpc(player.pet.id);
            petData.ifPresent(pet -> {
                lostPets.put(pet, true);
            });
        }
        for (Item items : player.inventory) {
            if (items != null) {
                Optional<PetData> petData = PetData.forItem(items.getId());
                petData.ifPresent(pet -> {
                    lostPets.put(pet, false);
                });
            }
        }
        for (PetData pets : lostPets.keySet()) {
            if (hasInsurance(player, pets)) {
                player.lostPets.add(pets);
                player.inventory.remove(pets.getItem());
                if (lostPets.get(pets)) {
                    player.pet.unregister();
                    player.pet = null;
                }
                player.message("You have lost your pet, luckily you insured it! Speak to the insurance agent to claim.");
            } else {
                player.inventory.remove(pets.getItem());
                if (lostPets.get(pets)) {
                    player.pet.unregister();
                    player.pet = null;
                } else {
                    Npc npc = new Npc(pets.getNpc(), player.getPosition());
                    npc.unregister();
                    World.schedule(abandon(npc));
                }
                player.send(new SendMessage("Your " + pets.getName() + " has disappeared forever! Make sure to insure it!"));
            }
        }
    }
References abandon(), com.runehive.content.pet.PetData.forItem(), com.runehive.content.pet.PetData.forNpc(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.Entity.getPosition(), hasInsurance(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.lostPets, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.player.Player.pet, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.npc.Npc.unregister().
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.death(), and com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath().
onLogin()
void com.runehive.content.pet.Pets.onLogin (Player player) static
Handles what happens to a pet when a player logs in.
Definition at line 224 of file Pets.java.
{
        if (player.pet != null) {
            Npc npc = player.pet;
            npc.owner = player;
            npc.register();
            World.schedule(5, () -> {
                npc.face(player);
                npc.interact(player);
                npc.follow(player);
            });
        }
    }
References com.runehive.game.world.entity.mob.Mob.face(), com.runehive.game.world.entity.mob.Mob.follow(), com.runehive.game.world.entity.mob.Mob.interact(), com.runehive.game.world.entity.mob.player.Player.pet, com.runehive.game.world.entity.mob.npc.Npc.register(), and com.runehive.game.world.World.schedule().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.login().
onLogout()
void com.runehive.content.pet.Pets.onLogout (Player player) static
Handles what happens to a pet when a player logouts.
Definition at line 217 of file Pets.java.
{
        if (player.pet != null) {
            player.pet.unregister();
        }
    }
References com.runehive.game.world.entity.mob.player.Player.pet, and com.runehive.game.world.entity.mob.npc.Npc.unregister().
Referenced by com.runehive.game.world.entity.mob.player.Player.unregister().
onObtain()
void com.runehive.content.pet.Pets.onObtain (Player player, int item) static private
Handles a player receiving a pet onReward.
Definition at line 69 of file Pets.java.
{
        Position position = Utility.findAccessableTile(player);
        if(PetData.forItem(item).isPresent() && (player.inventory.contains(item) || player.bank.contains(item) || (player.pet != null && player.pet.id == PetData.forItem(item).get().getNpc()))) {
                player.send(new SendMessage("<col=FF0000>You have a funny feeling like you would've been followed."));
                return;
        }
        if (player.pet == null && position != null) {
            onSpawn(player, item, false);
        } else if (player.inventory.hasCapacityFor(new Item(item, 1))) {
            player.inventory.add(item, 1);
            player.send(new SendMessage("You feel something weird sneaking into your backpack", MessageColor.RED));
        } else {
            player.send(new SendMessage("There was no space for the pet, he has vanished.", MessageColor.RED));
        }
        if (item == 20693) { //phoenix pet from wintertodt
            CollectionLog.logItem(player, CollectionLogData.WINTERTODT, 20693, 1);
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.Player.bank, com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.util.Utility.findAccessableTile(), com.runehive.content.pet.PetData.forItem(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.collectionlog.CollectionLog.logItem(), onSpawn(), com.runehive.game.world.entity.mob.player.Player.pet, com.runehive.util.MessageColor.RED, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.content.collectionlog.CollectionLogData.WINTERTODT.
Referenced by onReward(), onReward(), and onReward().
onReward() [1/3]
void com.runehive.content.pet.Pets.onReward (Player player, int item) static
Handles rewarding with a 100% a chance.
Parameters
player
item
chance
Definition at line 44 of file Pets.java.
{
        onObtain(player, item);
    }
References onObtain().
onReward() [2/3]
void com.runehive.content.pet.Pets.onReward (Player player, int item, int chance) static
Handles calculating the chance of a player receiving a skilling pet.
Definition at line 33 of file Pets.java.
{
        if (Utility.random(chance) == 0)
            onObtain(player, item);
    }
References onObtain(), and com.runehive.util.Utility.random().
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.activity.impl.fightcaves.FightCaves.finish(), com.runehive.content.activity.inferno.Inferno.finish(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), and com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop().
onReward() [3/3]
boolean com.runehive.content.pet.Pets.onReward (Player player, PetData pet) static
Generates a unique equation for special defined pets.
Definition at line 49 of file Pets.java.
{
        int chance = -1;
        if (pet == PetData.JAD)
            chance = 200;
        if (pet == PetData.ROCKY)
            chance = 5000;
        if (pet == PetData.ROCK_GOLEM)
            chance = 6500;
        if (pet == PetData.BABY_DARTH)
            chance = 30000;
        if (chance != -1 && Utility.random(chance) == 0) {
            onObtain(player, pet.getItem());
            return true;
        }
        return false;
    }
References com.runehive.content.pet.PetData.BABY_DARTH, com.runehive.content.pet.PetData.JAD, onObtain(), com.runehive.util.Utility.random(), com.runehive.content.pet.PetData.ROCK_GOLEM, and com.runehive.content.pet.PetData.ROCKY.
onSpawn()
boolean com.runehive.content.pet.Pets.onSpawn (Player player, int item, boolean drop) static
Handles spawning a pet.
Definition at line 91 of file Pets.java.
{
        if (!PetData.forItem(item).isPresent())
            return false;
        if (player.pet != null) {
            player.send(new SendMessage("You already have a pet following you!"));
            return true;
        }
        Position position = Utility.findAccessableTile(player);
        if (position == null) {
            player.send(new SendMessage("You cannot drop your pet from your current location!"));
            return true;
        }
        PetData pets = PetData.forItem(item).get();
        Npc pet = new Npc(pets.getNpc(), position);
        pet.owner = player;
        if (drop) {
            player.face(position);
            player.animate(new Animation(827));
            player.inventory.remove(item, 1);
        }
        pet.register();
        pet.interact(player);
        pet.follow(player);
        pet.instance = player.instance;
        player.pet = pet;
        if (!drop) {
            player.message("<col=FF0000>You have a funny feeling like you're being followed.");
            World.sendMessage("<icon=11> <col=FF0000>osroyale: <col=" + player.right.getColor() + ">" + player.getName() + "</col> has just received a pet " + pet.getName() + "!");
            AchievementHandler.activate(player, AchievementKey.OBTAIN_PET);
        }
        return true;
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.util.Utility.findAccessableTile(), com.runehive.content.pet.PetData.forItem(), com.runehive.game.world.entity.mob.player.PlayerRight.getColor(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.pet.PetData.getNpc(), com.runehive.game.world.entity.Entity.instance, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.achievement.AchievementKey.OBTAIN_PET, com.runehive.game.world.entity.mob.player.Player.pet, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.right, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.World.sendMessage().
Referenced by onObtain().
openInsurance()
void com.runehive.content.pet.Pets.openInsurance (Player player) static
Handles opening the insurance interface.
Definition at line 279 of file Pets.java.
{
        int size = PetData.values().length;
        for (int index = 0, string = 37115; index < size; index++) {
            PetData pet = PetData.forOrdinal(index).get();
            player.send(new SendString("<col=" + (hasInsurance(player, pet) ? "347043" : "F24444") + ">" + pet.getName(), string++));
        }
        player.send(new SendString("<col=000000>This is a list of all pets that are allowed to be insured", 37111));
        player.send(new SendString("<col=000000>for <col=3c50b2>" + Utility.formatDigits(INSRUANCE_COST) + "<col=000000> gp. Insurance will protect a pet on death.", 37112));
        player.send(new SendString("<col=000000>Red = <col=F24444>Un-insured<col=000000> | Green = <col=347043>Insured", 37113));
        player.send(new SendString("", 37114));
        player.send(new SendString("Total Pets: " + size, 37107));
        player.send(new SendString("Pet Insurance Information", 37103));
        player.send(new SendScrollbar(37110, size * 22));
        player.interfaceManager.open(37100);
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.content.pet.PetData.forOrdinal(), hasInsurance(), INSRUANCE_COST, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), and com.runehive.game.world.entity.mob.player.Player.send().
openLostPets()
void com.runehive.content.pet.Pets.openLostPets (Player player) static
Handles opening the insurance interface.
Definition at line 296 of file Pets.java.
{
        List<PetData> pets = new ArrayList<>();
        pets.addAll(player.lostPets);
        int size = pets.size() < 7 ? 7 : pets.size();
        for (int index = 0, string = 37115; index < size; index++) {
            boolean valid = !pets.isEmpty() && index < pets.size();
            PetData pet = valid ? pets.get(index) : null;
            player.send(new SendString(valid ? "<col=255>" + pet.getName() : "", string++));
        }
        int cost = player.lostPets.size() * 250_000;
        player.send(new SendString("<col=000000>This is a list of all pets available to be claimed", 37111));
        player.send(new SendString("<col=000000>Total Free <col=3c50b2>" + Utility.formatDigits(cost) + "<col=000000> gp", 37112));
        player.send(new SendString("", 37113));
        player.send(new SendString(pets.isEmpty() ? "You have no pets to collect!" : "", 37114));
        player.send(new SendString("Total Lost: " + pets.size(), 37107));
        player.send(new SendString("Lost Pets", 37103));
        player.send(new SendScrollbar(37110, 0));
        player.interfaceManager.open(37100);
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.lostPets, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), and com.runehive.game.world.entity.mob.player.Player.send().
Member Data Documentation
INSRUANCE_COST
final int com.runehive.content.pet.Pets.INSRUANCE_COST = 8000000 static
The cost of insuring a pet.
Definition at line 30 of file Pets.java.
Referenced by buyInsurance(), and openInsurance().
The documentation for this class was generated from the following file:
java/com/runehive/content/pet/Pets.java