RuneHive-Game: com.runehive.game.action.Action< T extends Mob > Class Template Reference
com.runehive.game.action.Action< T extends Mob > Class Template Reference abstract
Represents an action an entity can execute.
Public Member Functions
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
abstract String getName ()
Gets the name of this action.
abstract WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
boolean prioritized ()
Determines if this action is prioritized.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Private Attributes
final T mob
The Mob associated with this ActionEvent.
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
abstract void execute ()
A function representing the unit of work that will be carried out.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
Represents an action an entity can execute.
Author
Stand Up
Definition at line 12 of file Action.java.
Constructor & Destructor Documentation
Action() [1/2]
com.runehive.game.action.Action< T extends Mob >.Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
Parameters
mob mob.
instant instant.
delay delay.
Definition at line 24 of file Action.java.
{
        super(instant, delay);
        this.mob = mob;
    }
References com.runehive.game.task.Task.delay, com.runehive.game.task.Task.instant, and mob.
Action() [2/2]
com.runehive.game.action.Action< T extends Mob >.Action (T mob, int delay)
Creates a new Action randomevent.
Parameters
mob mob.
delay delay.
Definition at line 35 of file Action.java.
{
        this(mob, delay, false);
    }
References com.runehive.game.task.Task.delay, and mob.
Member Function Documentation
cancellableInProgress()
boolean com.runehive.game.action.Action< T extends Mob >.cancellableInProgress ()
Reimplemented in com.runehive.game.action.impl.RevShortcutAction.
Definition at line 73 of file Action.java.
{
        return true;
    }
getMob()
T com.runehive.game.action.Action< T extends Mob >.getMob ()
Gets the player.
Returns
The player.
Definition at line 44 of file Action.java.
                      {
        return mob;
    }
References mob.
Referenced by com.runehive.content.skill.impl.firemaking.FiremakingAction.canInit(), com.runehive.content.skill.impl.smithing.SmithingArmour.canInit(), com.runehive.game.action.impl.BuryBoneAction.canInit(), com.runehive.game.action.impl.ScatterAshAction.canInit(), com.runehive.content.skill.impl.DestructionSkillAction.canRun(), com.runehive.content.skill.impl.HarvestingSkillAction.canRun(), com.runehive.content.skill.impl.ProducingSkillAction.canRun(), com.runehive.content.shootingstar.ShootingStarAction.canSchedule(), com.runehive.content.skill.impl.fishing.FishingAction.canSchedule(), com.runehive.content.skill.impl.mining.MiningAction.canSchedule(), com.runehive.content.skill.impl.smithing.Smelting.canSchedule(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.canSchedule(), com.runehive.game.action.impl.ChestAction.canSchedule(), com.runehive.game.action.impl.DoorAction.canSchedule(), com.runehive.game.action.impl.LadderAction.canSchedule(), com.runehive.game.action.impl.LeverAction.canSchedule(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.shootingstar.ShootingStarAction.execute(), com.runehive.content.skill.impl.fishing.FishingAction.execute(), com.runehive.content.skill.impl.hunter.birdhouse.action.CreateBirdHouse.execute(), com.runehive.content.skill.impl.hunter.birdhouse.action.FillBirdhouse.execute(), com.runehive.content.skill.impl.hunter.birdhouse.action.PlaceBirdhouse.execute(), com.runehive.content.skill.impl.mining.MiningAction.execute(), com.runehive.content.skill.impl.smithing.Smelting.execute(), com.runehive.content.skill.impl.thieving.PickpocketAction.execute(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.execute(), com.runehive.content.skill.SkillAction.execute(), com.runehive.content.wintertodt.actions.ChopRoots.execute(), com.runehive.content.wintertodt.actions.FeedBrazier.execute(), com.runehive.content.wintertodt.actions.FixBrazier.execute(), com.runehive.content.wintertodt.actions.FlameWalk.execute(), com.runehive.content.wintertodt.actions.FletchKindling.execute(), com.runehive.content.wintertodt.actions.LightBrazier.execute(), com.runehive.content.wintertodt.actions.MixHerb.execute(), com.runehive.content.wintertodt.actions.PickHerb.execute(), com.runehive.game.action.impl.DoorAction.execute(), com.runehive.game.action.impl.EmoteAction.execute(), com.runehive.game.action.impl.FlaxPickingAction.execute(), com.runehive.game.action.impl.InspectAction.execute(), com.runehive.game.action.impl.LadderAction.execute(), com.runehive.game.action.impl.LeverAction.execute(), com.runehive.game.action.impl.NpcFaceAction.execute(), com.runehive.game.action.impl.RevShortcutAction.execute(), com.runehive.game.action.impl.SpadeAction.execute(), com.runehive.game.action.impl.BuryBoneAction.experience(), com.runehive.game.action.impl.ScatterAshAction.experience(), com.runehive.content.skill.impl.mining.MiningAction.handleCelestialRing(), com.runehive.content.skill.impl.firemaking.FiremakingAction.init(), com.runehive.content.skill.impl.smithing.SmithingArmour.init(), com.runehive.content.shootingstar.ShootingStarAction.mine(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.game.action.impl.NpcFaceAction.NpcFaceAction(), com.runehive.content.shootingstar.ShootingStarAction.onCancel(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onCancel(), com.runehive.content.skill.impl.fishing.FishingAction.onCancel(), com.runehive.content.skill.impl.hunter.net.PuroPuroAction.onCancel(), com.runehive.content.skill.impl.mining.MiningAction.onCancel(), com.runehive.content.skill.impl.smithing.Smelting.onCancel(), com.runehive.content.skill.impl.smithing.SmithingArmour.onCancel(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.onCancel(), com.runehive.game.action.impl.BuryBoneAction.onCancel(), com.runehive.game.action.impl.ChestAction.onCancel(), com.runehive.game.action.impl.DoorAction.onCancel(), com.runehive.game.action.impl.LeverAction.onCancel(), com.runehive.game.action.impl.ScatterAshAction.onCancel(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.content.skill.impl.DestructionSkillAction.onExecute(), com.runehive.content.skill.impl.HarvestingSkillAction.onExecute(), com.runehive.content.skill.impl.ProducingSkillAction.onExecute(), com.runehive.game.action.impl.BuryBoneAction.onExecute(), com.runehive.game.action.impl.ScatterAshAction.onExecute(), com.runehive.content.skill.impl.smithing.SmithingArmour.onProduce(), com.runehive.content.shootingstar.ShootingStarAction.onSchedule(), com.runehive.content.skill.impl.fishing.FishingAction.onSchedule(), com.runehive.content.skill.impl.hunter.net.PuroPuroAction.onSchedule(), com.runehive.content.skill.impl.mining.MiningAction.onSchedule(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.onSchedule(), com.runehive.content.skill.SkillAction.onSchedule(), com.runehive.game.action.impl.ChestAction.onSchedule(), com.runehive.game.action.impl.LadderAction.onSchedule(), com.runehive.game.action.impl.LeverAction.onSchedule(), com.runehive.game.action.impl.SpadeAction.onSchedule(), com.runehive.game.action.impl.SpellAction.onSchedule(), com.runehive.content.skill.impl.smithing.Smelting.smelt(), and com.runehive.content.skill.SkillAction.start().
getName()
abstract String com.runehive.game.action.Action< T extends Mob >.getName () abstract
Gets the name of this action.
Returns
The name of this action.
Reimplemented in com.runehive.content.shootingstar.ShootingStarAction, com.runehive.content.skill.impl.firemaking.FiremakingAction, com.runehive.content.skill.impl.fishing.FishingAction, com.runehive.content.skill.impl.hunter.birdhouse.action.CreateBirdHouse, com.runehive.content.skill.impl.hunter.birdhouse.action.FillBirdhouse, com.runehive.content.skill.impl.hunter.birdhouse.action.PlaceBirdhouse, com.runehive.content.skill.impl.hunter.net.PuroPuroAction, com.runehive.content.skill.impl.mining.MiningAction, com.runehive.content.skill.impl.smithing.Smelting, com.runehive.content.skill.impl.smithing.SmithingArmour, com.runehive.content.skill.impl.thieving.PickpocketAction, com.runehive.content.skill.impl.woodcutting.WoodcuttingAction, com.runehive.content.wintertodt.actions.ChopRoots, com.runehive.content.wintertodt.actions.FixBrazier, com.runehive.content.wintertodt.actions.FlameWalk, com.runehive.content.wintertodt.actions.LightBrazier, com.runehive.content.wintertodt.actions.MixHerb, com.runehive.content.wintertodt.actions.PickHerb, com.runehive.content.wintertodt.WintertodtAction, com.runehive.game.action.impl.BuryBoneAction, com.runehive.game.action.impl.ChestAction, com.runehive.game.action.impl.DoorAction, com.runehive.game.action.impl.EmoteAction, com.runehive.game.action.impl.FlaxPickingAction, com.runehive.game.action.impl.LadderAction, com.runehive.game.action.impl.LeverAction, com.runehive.game.action.impl.NpcFaceAction, com.runehive.game.action.impl.RevShortcutAction, com.runehive.game.action.impl.ScatterAshAction, com.runehive.game.action.impl.SpadeAction, and com.runehive.game.action.impl.SpellAction.
getWalkablePolicy()
abstract WalkablePolicy com.runehive.game.action.Action< T extends Mob >.getWalkablePolicy () abstract
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented in com.runehive.content.shootingstar.ShootingStarAction, com.runehive.content.skill.impl.DestructionSkillAction, com.runehive.content.skill.impl.fishing.FishingAction, com.runehive.content.skill.impl.HarvestingSkillAction, com.runehive.content.skill.impl.hunter.birdhouse.action.CreateBirdHouse, com.runehive.content.skill.impl.hunter.birdhouse.action.FillBirdhouse, com.runehive.content.skill.impl.hunter.birdhouse.action.PlaceBirdhouse, com.runehive.content.skill.impl.hunter.net.PuroPuroAction, com.runehive.content.skill.impl.mining.MiningAction, com.runehive.content.skill.impl.smithing.Smelting, com.runehive.content.skill.impl.smithing.SmithingArmour, com.runehive.content.skill.impl.thieving.PickpocketAction, com.runehive.content.skill.impl.woodcutting.WoodcuttingAction, com.runehive.content.wintertodt.actions.ChopRoots, com.runehive.content.wintertodt.actions.FixBrazier, com.runehive.content.wintertodt.actions.FlameWalk, com.runehive.content.wintertodt.actions.LightBrazier, com.runehive.content.wintertodt.actions.MixHerb, com.runehive.content.wintertodt.actions.PickHerb, com.runehive.content.wintertodt.WintertodtAction, com.runehive.game.action.impl.BuryBoneAction, com.runehive.game.action.impl.ChestAction, com.runehive.game.action.impl.DoorAction, com.runehive.game.action.impl.EmoteAction, com.runehive.game.action.impl.FlaxPickingAction, com.runehive.game.action.impl.InspectAction, com.runehive.game.action.impl.LadderAction, com.runehive.game.action.impl.LeverAction, com.runehive.game.action.impl.NpcFaceAction, com.runehive.game.action.impl.RevShortcutAction, com.runehive.game.action.impl.ScatterAshAction, com.runehive.game.action.impl.SpadeAction, and com.runehive.game.action.impl.SpellAction.
prioritized()
boolean com.runehive.game.action.Action< T extends Mob >.prioritized ()
Determines if this action is prioritized.
When making an action prioritized, the next action will be ignored if not queued.
Returns
true if this action is prioritized, false otherwise.
Reimplemented in com.runehive.content.skill.impl.DestructionSkillAction, com.runehive.content.skill.impl.HarvestingSkillAction, com.runehive.content.skill.impl.smithing.Smelting, com.runehive.content.skill.impl.smithing.SmithingArmour, com.runehive.content.skill.impl.thieving.PickpocketAction, com.runehive.game.action.impl.BuryBoneAction, com.runehive.game.action.impl.ChestAction, com.runehive.game.action.impl.DoorAction, com.runehive.game.action.impl.EmoteAction, com.runehive.game.action.impl.FlaxPickingAction, com.runehive.game.action.impl.InspectAction, com.runehive.game.action.impl.LadderAction, com.runehive.game.action.impl.LeverAction, com.runehive.game.action.impl.NpcFaceAction, com.runehive.game.action.impl.ScatterAshAction, com.runehive.game.action.impl.SpadeAction, and com.runehive.game.action.impl.SpellAction.
Definition at line 55 of file Action.java.
{
        return false;
    }
Member Data Documentation
mob
final T com.runehive.game.action.Action< T extends Mob >.mob private
The Mob associated with this ActionEvent.
Definition at line 15 of file Action.java.
Referenced by Action(), Action(), com.runehive.content.skill.impl.DestructionSkillAction.DestructionSkillAction(), com.runehive.content.wintertodt.actions.FlameWalk.FlameWalk(), getMob(), com.runehive.content.skill.impl.HarvestingSkillAction.HarvestingSkillAction(), com.runehive.content.skill.impl.HarvestingSkillAction.HarvestingSkillAction(), com.runehive.game.action.impl.LadderAction.LadderAction(), com.runehive.game.action.impl.LadderAction.LadderAction(), com.runehive.game.action.impl.LeverAction.LeverAction(), com.runehive.game.action.impl.LeverAction.LeverAction(), com.runehive.content.skill.SkillAction.SkillAction(), com.runehive.content.skill.SkillAction.SkillAction(), and com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.WoodcuttingAction().
The documentation for this class was generated from the following file:
java/com/runehive/game/action/Action.java