RuneHive-Game: com.runehive.content.skill.impl.magic.spell.impl.Vengeance Class Reference
com.runehive.content.skill.impl.magic.spell.impl.Vengeance Class Reference
Handles the vengeance spell.
Public Member Functions
void execute (Player player, Item item)
Executes the magic spell.
int getLevel ()
Gets the level required to cast spell.
String getName ()
Gets the name of the spell.
Item[] getRunes ()
Gets the runes required to cast the spell.
Detailed Description
Handles the vengeance spell.
Definition at line 20 of file Vengeance.java.
Member Function Documentation
execute()
void com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute (Player player, Item item)
Executes the magic spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 37 of file Vengeance.java.
{
        if (player.spellbook != Spellbook.LUNAR)
            return;
        if (player.skills.getMaxLevel(Skill.DEFENCE) < 45) {
            player.send(new SendMessage("You need a defence level of 45 to cast this spell!"));
            return;
        }
        if (player.venged) {
            player.send(new SendMessage("You already have vengeance casted!"));
            return;
        }
        if (player.spellCasting.vengeanceDelay.elapsedTime(TimeUnit.SECONDS) < 30) {
            player.send(new SendMessage("You can only cast vengeance once every 30 seconds."));
            return;
        }
        player.animate(new Animation(8317, UpdatePriority.HIGH), true);
        player.graphic(new Graphic(726, true));
        player.spellCasting.vengeanceDelay.reset();
        player.send(new SendWidget(SendWidget.WidgetType.VENGEANCE, 30));
        player.venged = true;
        player.getCombat().addListener(VengeanceListener.get());
    }
References com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.util.Stopwatch.elapsedTime(), com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.UpdatePriority.HIGH, com.runehive.content.skill.impl.magic.Spellbook.LUNAR, com.runehive.util.Stopwatch.reset(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.mob.player.Player.spellbook, com.runehive.game.world.entity.mob.player.Player.spellCasting, com.runehive.net.packet.out.SendWidget.WidgetType.VENGEANCE, com.runehive.content.skill.impl.magic.spell.SpellCasting.vengeanceDelay, and com.runehive.game.world.entity.mob.player.Player.venged.
getLevel()
int com.runehive.content.skill.impl.magic.spell.impl.Vengeance.getLevel ()
Gets the level required to cast spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 32 of file Vengeance.java.
{
        return 94;
    }
getName()
String com.runehive.content.skill.impl.magic.spell.impl.Vengeance.getName ()
Gets the name of the spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 22 of file Vengeance.java.
{
        return "Vengeance";
    }
getRunes()
Item[] com.runehive.content.skill.impl.magic.spell.impl.Vengeance.getRunes ()
Gets the runes required to cast the spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 27 of file Vengeance.java.
{
        return new Item[]{new Item(9075, 4), new Item(557, 10), new Item(560, 2)};
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/magic/spell/impl/Vengeance.java