RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife Class Reference
com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife Class Reference
Public Member Functions
Animation getAttackAnimation (Player attacker, Mob defender)
CombatHit[] getHits (Player attacker, Mob defender)
void hit (Player attacker, Mob defender, Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy
void attack (Player attacker, Mob defender, Hit hit)
boolean canAttack (Player attacker, Mob defender)
int getAttackDelay (Player attacker, Mob defender, FightType fightType)
int getAttackDistance (Player attacker, FightType fightType)
CombatType getCombatType ()
void start (Player attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static DragonKnife get ()
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions
void sendStuff (Player attacker, Mob defender)
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy
PlayerRangedStrategy ()
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Package Functions
[static initializer]
Private Member Functions
DragonKnife ()
Static Private Attributes
static final DragonKnife INSTANCE = new DragonKnife()
static CombatProjectile PROJECTILE
Additional Inherited Members
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Author
Andys1814
Definition at line 22 of file DragonKnife.java.
Constructor & Destructor Documentation
DragonKnife()
com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.DragonKnife () private
Definition at line 36 of file DragonKnife.java.
{
    }
Referenced by get().
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.[static initializer] static package
References com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition(), and PROJECTILE.
get()
DragonKnife com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.get () static
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 75 of file DragonKnife.java.
{
        return INSTANCE;
    }
References DragonKnife(), and INSTANCE.
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.getAttackAnimation (Player attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 71 of file DragonKnife.java.
{
        return new Animation(8291);
    }
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.getHits (Player attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 52 of file DragonKnife.java.
{
        CombatHit first = nextRangedHit(attacker, defender);
        CombatHit second = nextRangedHit(attacker, defender);
        int minimum = 5;
        if (first.getDamage() < minimum) {
            first.setDamage(minimum);
            first.setAccurate(true);
        }
        if (second.getDamage() < minimum) {
            second.setDamage(minimum);
            second.setAccurate(true);
        }
        return new CombatHit[] { first, second };
    }
References com.runehive.game.world.entity.combat.hit.Hit.getDamage(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit(), com.runehive.game.world.entity.combat.hit.Hit.setAccurate(), and com.runehive.game.world.entity.combat.hit.Hit.setDamage().
hit()
void com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.hit (Player attacker, Mob defender, Hit hit)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 47 of file DragonKnife.java.
{
        super.hit(attacker, defender, hit);
    }
References hit().
Referenced by hit().
sendStuff()
void com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.sendStuff (Player attacker, Mob defender) protected
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 40 of file DragonKnife.java.
{
        super.sendStuff(attacker, defender);
        PROJECTILE.getProjectile().ifPresent(projectile -> projectile.send(attacker, defender));
    }
References PROJECTILE.
Member Data Documentation
INSTANCE
final DragonKnife com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.INSTANCE = new DragonKnife() static private
Definition at line 24 of file DragonKnife.java.
Referenced by get().
PROJECTILE
CombatProjectile com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.PROJECTILE static private
Definition at line 26 of file DragonKnife.java.
Referenced by [static initializer](), and sendStuff().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/special/range/DragonKnife.java