RuneHive-Game: com.runehive.game.world.entity.mob.npc.drop.NpcDropManager Class Reference
com.runehive.game.world.entity.mob.npc.drop.NpcDropManager Class Reference
The manager class which holds the static entries of drop tables and has a method to execute a drop table from the specified npc.
Static Public Member Functions
static void drop (Player killer, Npc npc)
Attempts to drop the drop table which belongs to npc#id.
Static Public Attributes
static final Map< Integer, NpcDropTable > NPC_DROPS = new HashMap<>()
The collection of npc ids by their representative drop tables.
Static Private Member Functions
static boolean checkAlternativePosition (int npc)
static void handleAshSanctifier (Player player, AshData ashes)
static void handleBoneCrusher (Player player, BoneData bone)
static void handleMessages (Player player, Npc npc, Item item)
static void handleMiscDrops (Player player, Npc npc)
static NpcDrop rollDrop (Player player, Npc npc)
static void tridentRunes (Player killer, Position dropPosition)
Static Private Attributes
static final int[] ALTERNATIVE_POSITION = {2044, 2043, 2042, 494, 8060}
Alternative drop positions for mobs (i.e kraken, zulrah)
static final boolean USE_NEW_SYSTEM = true
Detailed Description
The manager class which holds the static entries of drop tables and has a method to execute a drop table from the specified npc.
Author
Stand Up
Since
29-1-2017.
Definition at line 40 of file NpcDropManager.java.
Member Function Documentation
checkAlternativePosition()
boolean com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.checkAlternativePosition (int npc) static private
Definition at line 306 of file NpcDropManager.java.
{
        for (int alternative : ALTERNATIVE_POSITION) {
            if (alternative == npc)
                return true;
        }
        return false;
    }
References ALTERNATIVE_POSITION.
Referenced by drop(), handleMiscDrops(), and rollDrop().
drop()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop (Player killer, Npc npc) static
Attempts to drop the drop table which belongs to npc#id.
Definition at line 58 of file NpcDropManager.java.
{
        if (killer == null) {
            return;
        }
        if (npc == null) {
            return;
        }
        if (USE_NEW_SYSTEM) {
            rollDrop(killer, npc);
            AchievementHandler.activate(killer, AchievementKey.NPCS);
            return;
        }
        NpcDropTable table = NPC_DROPS.get(npc.id);
        if (table == null) {
            return;
        }
        RandomGen gen = new RandomGen();
        List<NpcDrop> npc_drops = table.generate(killer, false);
        Position dropPosition = npc.getPosition().copy();
        // special drop positions
        if (checkAlternativePosition(npc.id)) {
            dropPosition = killer.getPosition().copy();
        }
        // crystal key drop
        if (npc.getMaximumHealth() > 50 && Utility.random(150) <= 5) {
            Item crystal_key = Utility.randomElement(CrystalChest.KEY_HALVES);
            GroundItem.create(killer, crystal_key, dropPosition);
            killer.send(new SendMessage("<col=BA383E>Rare Drop Notification: </col>" + crystal_key.getName()));
            AchievementHandler.activate(killer, AchievementKey.RARE_DROPS);
        }
        // casket drop
        if (npc.getMaximumHealth() > 10 && Utility.random(200) <= 10) {
            Item casket = new Item(405);
            GroundItem.create(killer, casket, dropPosition);
            killer.send(new SendMessage("<col=BA383E>Rare Drop Notification: </col>" + casket.getName(), true));
            AchievementHandler.activate(killer, AchievementKey.RARE_DROPS);
        }
        // drop table
        for (NpcDrop drop : npc_drops) {
            Item item = drop.toItem(gen);
            if (item.getId() == 11941 && (killer.playerAssistant.contains(new Item(LootingBagPlugin.OPENED_ID)) || killer.playerAssistant.contains(item))) { // looting bag
                killer.message(true, "You have missed out on " + Utility.getAOrAn(item.getName()) + " " + item.getName() + " since you already have on on your account.");
                continue;
            }
//            if (killer.clanChannel != null && killer.clanChannel.lootshareEnabled()) {
//                killer.forClan(channel -> channel.splitLoot(killer, npc, item));
//                return;
//            }
            if (killer.settings.dropNotification && item.getValue() > 1_000_000) {
                String name = item.getName();
                killer.send(new SendMessage("<col=BA383E>Exotic Drop Notification: </col>" + name + " (" + Utility.formatDigits(item.getValue()) + " coins)"));
                World.sendMessage("<col=BA383E>osroyale: <col=" + killer.right.getColor() + ">" + killer.getName() + " </col>has just received " + Utility.getAOrAn(name) + " <col=BA383E>" + name + " </col>from <col=BA383E>" + npc.getName() + "</col>!");
                // DiscordPlugin.sendSimpleMessage(killer.getName() + " has just received " + Utility.getAOrAn(name) + " " + name + " from " + npc.getName() + "!");
                if (killer.settings.screenshotKill) {
                    killer.getPlayer().send(new SendScreenshot());
                }
            } else if (killer.settings.dropNotification && item.getValue() > 100_000) {
                String name = item.getName();
                killer.send(new SendMessage("<col=BA383E>Rare Drop Notification: </col>" + name + " (" + Utility.formatDigits(item.getValue()) + " coins)"));
                AchievementHandler.activate(killer, AchievementKey.RARE_DROPS);
            } else if (killer.settings.untradeableNotification && !item.isTradeable()) {
                killer.send(new SendMessage("<col=F5424B>Untradeable Drop Notification: </col>" + item.getName()));
            }
            CollectionLog.checkItemDrop(killer, npc.id, item.getId(), item.getAmount());
            if (npc.id == 494 && item.getId() == 11907) {
                tridentRunes(killer, dropPosition);
            }
            if (!item.isStackable()) {
                Item single = item.createWithAmount(1);
                for (int i = 0; i < item.getAmount(); i++)
                    GroundItem.create(killer, single, dropPosition);
            } else {
                GroundItem.create(killer, item, dropPosition);
            }
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), checkAlternativePosition(), com.runehive.content.collectionlog.CollectionLog.checkItemDrop(), com.runehive.game.world.entity.mob.player.PlayerAssistant.contains(), com.runehive.game.world.position.Position.copy(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.items.Item.createWithAmount(), drop(), com.runehive.game.world.entity.mob.player.Settings.dropNotification, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.generate(), com.runehive.game.world.items.Item.getAmount(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.entity.mob.player.PlayerRight.getColor(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.items.Item.getValue(), com.runehive.game.world.items.Item.isStackable(), com.runehive.game.world.items.Item.isTradeable(), com.runehive.content.CrystalChest.KEY_HALVES, com.runehive.game.world.entity.mob.player.Player.message(), NPC_DROPS, com.runehive.content.achievement.AchievementKey.NPCS, com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), com.runehive.content.achievement.AchievementKey.RARE_DROPS, com.runehive.game.world.entity.mob.player.Player.right, rollDrop(), com.runehive.game.world.entity.mob.player.Settings.screenshotKill, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.World.sendMessage(), com.runehive.game.world.entity.mob.player.Player.settings, tridentRunes(), com.runehive.game.world.entity.mob.player.Settings.untradeableNotification, and USE_NEW_SYSTEM.
Referenced by drop(), com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath(), and rollDrop().
handleAshSanctifier()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleAshSanctifier (Player player, AshData ashes) static private
Definition at line 184 of file NpcDropManager.java.
{
        if (ashes == null) { return; }
        var exp = (ashes.getExperience() * Config.PRAYER_MODIFICATION);
        player.skills.addExperience(Skill.PRAYER, exp);
    }
References com.runehive.content.skill.impl.prayer.AshData.getExperience(), com.runehive.game.world.entity.skill.Skill.PRAYER, and com.runehive.Config.PRAYER_MODIFICATION.
Referenced by rollDrop().
handleBoneCrusher()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleBoneCrusher (Player player, BoneData bone) static private
Definition at line 159 of file NpcDropManager.java.
{
        if (bone == null) { return; }
        var exp = (bone.getExperience() * Config.PRAYER_MODIFICATION);
        player.skills.addExperience(Skill.PRAYER, exp);
        AchievementHandler.activate(player, AchievementKey.BURY_BONES, 1);
        if (player.equipment.hasAmulet() && player.equipment.getAmuletSlot().getId() == 22111) {
            int current = player.skills.getLevel(Skill.PRAYER);
            int maximum = player.skills.getMaxLevel(Skill.PRAYER);
            if (current < maximum) {
                int points = bone.getBoneAmulet();
                if (current + points > maximum) {
                    points = maximum - current;
                }
                player.skills.get(Skill.PRAYER).addLevel(points);
                player.skills.refresh(Skill.PRAYER);
                player.message("You feel your " + player.equipment.getAmuletSlot().getName() + " vibrate as you bury the bone.");
            }
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.content.achievement.AchievementKey.BURY_BONES, com.runehive.content.skill.impl.prayer.BoneData.getBoneAmulet(), com.runehive.content.skill.impl.prayer.BoneData.getExperience(), com.runehive.game.world.entity.skill.Skill.PRAYER, and com.runehive.Config.PRAYER_MODIFICATION.
Referenced by rollDrop().
handleMessages()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMessages (Player player, Npc npc, Item item) static private
Definition at line 282 of file NpcDropManager.java.
{
        if (item.getId() == 11941 && (player.playerAssistant.contains(new Item(LootingBagPlugin.OPENED_ID)) || player.playerAssistant.contains(item))) { // looting bag
            player.message("You have missed out on " + Utility.getAOrAn(item.getName()) + " " + item.getName() + " since you already have on on your account.");
            return;
        }
        if (player.settings.dropNotification && item.getValue() > 1_000_000) {
            String name = item.getName();
            player.send(new SendMessage("<col=BA383E>Exotic Drop Notification: </col>" + name + " (" + Utility.formatDigits(item.getValue()) + " coins)"));
            World.sendMessage("<col=BA383E>osroyale: <col=" + player.right.getColor() + ">" + player.getName() + " </col>has just received " + Utility.getAOrAn(name) + " <col=BA383E>" + name + " </col>from <col=BA383E>" + npc.getName() + "</col>!");
            // DiscordPlugin.sendSimpleMessage("Exotic drop: " + player.getName() + " has just received " + Utility.getAOrAn(name) + " " + name + " from " + npc.getName() + "!");
            AchievementHandler.activate(player, AchievementKey.RARE_DROPS);
            if (player.settings.screenshotKill) {
                player.getPlayer().send(new SendScreenshot());
            }
        } else if (player.settings.dropNotification && item.getValue() > 100_000) {
            String name = item.getName();
            player.send(new SendMessage("<col=BA383E>Rare Drop Notification: </col>" + name + " (" + Utility.formatDigits(item.getValue()) + " coins)"));
            AchievementHandler.activate(player, AchievementKey.RARE_DROPS);
        } else if (player.settings.untradeableNotification && !item.isTradeable()) {
            player.send(new SendMessage("<col=F5424B>Untradeable Drop Notification: </col>" + item.getName()));
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.Item.getValue(), com.runehive.game.world.items.Item.isTradeable(), com.runehive.content.achievement.AchievementKey.RARE_DROPS, and com.runehive.game.world.World.sendMessage().
Referenced by rollDrop().
handleMiscDrops()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleMiscDrops (Player player, Npc npc) static private
Definition at line 261 of file NpcDropManager.java.
{
        Position dropPosition = npc.getPosition().copy();
        if (checkAlternativePosition(npc.id)) {
            dropPosition = player.getPosition().copy();
        }
        if (npc.getMaximumHealth() > 50 && Utility.random(150) <= 5) {
            Item crystal_key = Utility.randomElement(CrystalChest.KEY_HALVES);
            GroundItem.create(player, crystal_key, dropPosition);
            player.send(new SendMessage("<col=BA383E>Rare Drop Notification: </col>" + crystal_key.getName()));
            AchievementHandler.activate(player, AchievementKey.RARE_DROPS);
        }
        // casket drop
        if (npc.getMaximumHealth() > 10 && Utility.random(200) <= 10) {
            Item casket = new Item(405);
            GroundItem.create(player, casket, dropPosition);
            player.send(new SendMessage("<col=BA383E>Rare Drop Notification: </col>" + casket.getName(), true));
            AchievementHandler.activate(player, AchievementKey.RARE_DROPS);
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), checkAlternativePosition(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.items.Item.getName(), com.runehive.content.CrystalChest.KEY_HALVES, com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), and com.runehive.content.achievement.AchievementKey.RARE_DROPS.
Referenced by rollDrop().
rollDrop()
NpcDrop com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop (Player player, Npc npc) static private
Handle the pet roll if the item is a pet
Handle the pet roll if the item is a pet
Definition at line 190 of file NpcDropManager.java.
{
        //   player.send(new SendMessage("Called rollDrop"));
        NpcDropTable table = NPC_DROPS.get(npc.id);
        Position dropPos = npc.getPosition().copy();
        if (checkAlternativePosition(npc.id)) {
            dropPos = player.getPosition().copy();
        }
        if (table == null) {
            return null;
        }
        handleMiscDrops(player, npc);
        NpcDrop[] drops = table.drops;
        for (NpcDrop drop : drops) {
            if (drop.getWeight() == 0) {
                Item item = drop.toItem(new RandomGen());
                if (BoneData.forId(item.getId()).isPresent() && !item.isNoted() && player.inventory.contains(Items.BONECRUSHER)) {
                    handleBoneCrusher(player, BoneData.forId(item.getId()).get());
                    continue;
                }
                if (AshData.forId(item.getId()).isPresent() && !item.isNoted() && player.inventory.contains(25781)) {
                    handleAshSanctifier(player, AshData.forId(item.getId()).get());
                    continue;
                }
                /**
                 * Handle the pet roll if the item is a pet
                 */
                if(PetData.forItem(item.getId()).isPresent()) {
                    Pets.onReward(player, item.getId());
                } else {
                    GroundItem.create(player, item, dropPos);
                }
            }
        }
        WeightedCollection<NpcDrop> rc = new WeightedCollection<>();
        for (NpcDrop drop : drops) {
            double drOffset = 1 + (PlayerRight.getDropRateBonus(player) / 100.0); // dr bonus is in percent, conversion is 1 + (percent / 100.0)
            int weightMultiplier = 1;
            double dropChance = (drop.getWeight() * weightMultiplier) / drOffset;
            if (dropChance < 1) {
                dropChance = 1;
            }
            double weight = 1.0 / dropChance;
            if (drop.getWeight() != 0) {
                rc.add(weight, drop);
            }
        }
        double weightSum = rc.getTotal();
        if (Math.random() <= weightSum) {
            NpcDrop selectedDrop = rc.next();
            Item item = selectedDrop.toItem(new RandomGen());
            handleMessages(player, npc, item);
            /**
             * Handle the pet roll if the item is a pet
             */
            if (npc.id == 494 && item.getId() == 11907) {
                tridentRunes(player, dropPos);
            }
            if(PetData.forItem(item.getId()).isPresent()) {
                Pets.onReward(player, item.getId());
            } else {
                GroundItem.create(player, item, dropPos);
            }
            CollectionLog.checkItemDrop(player, npc.id, item.getId(), item.getAmount());
            return selectedDrop;
        }
        return null;
    }
References com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.add(), com.runehive.util.Items.BONECRUSHER, checkAlternativePosition(), com.runehive.content.collectionlog.CollectionLog.checkItemDrop(), com.runehive.game.world.items.ground.GroundItem.create(), drop(), com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.drops, com.runehive.content.skill.impl.prayer.AshData.forId(), com.runehive.content.skill.impl.prayer.BoneData.forId(), com.runehive.content.pet.PetData.forItem(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.PlayerRight.getDropRateBonus(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.getTotal(), handleAshSanctifier(), handleBoneCrusher(), handleMessages(), handleMiscDrops(), com.runehive.game.world.items.Item.isNoted(), com.runehive.game.world.entity.mob.npc.drop.WeightedCollection< E >.next(), NPC_DROPS, com.runehive.content.pet.Pets.onReward(), com.runehive.game.world.entity.mob.npc.drop.NpcDrop.toItem(), and tridentRunes().
Referenced by drop().
tridentRunes()
void com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.tridentRunes (Player killer, Position dropPosition) static private
Definition at line 150 of file NpcDropManager.java.
{
        List<Item> fullChargeItems = Arrays.asList(
                new Item(Items.DEATH_RUNE, 2500), new Item(Items.CHAOS_RUNE, 2500),
                new Item(Items.FIRE_RUNE, 12500), new Item(Items.COINS, 25000)
        );
        fullChargeItems.forEach(item -> GroundItem.create(killer, item, dropPosition));
    }
References com.runehive.util.Items.CHAOS_RUNE, com.runehive.util.Items.COINS, com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.util.Items.DEATH_RUNE, and com.runehive.util.Items.FIRE_RUNE.
Referenced by drop(), and rollDrop().
Member Data Documentation
ALTERNATIVE_POSITION
final int [] com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.ALTERNATIVE_POSITION = {2044, 2043, 2042, 494, 8060} static private
Alternative drop positions for mobs (i.e kraken, zulrah)
Definition at line 50 of file NpcDropManager.java.
{2044, 2043, 2042, 494, 8060};
Referenced by checkAlternativePosition().
NPC_DROPS
final Map<Integer, NpcDropTable> com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.NPC_DROPS = new HashMap<>() static
The collection of npc ids by their representative drop tables.
Definition at line 45 of file NpcDropManager.java.
Referenced by com.runehive.content.simulator.DropSimulator.drawList(), drop(), com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.main(), com.runehive.content.DropDisplay.open(), com.runehive.util.parser.impl.NpcDropParser.parse(), rollDrop(), and com.runehive.content.DropDisplay.search().
USE_NEW_SYSTEM
final boolean com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.USE_NEW_SYSTEM = true static private
Definition at line 53 of file NpcDropManager.java.
Referenced by drop().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/npc/drop/NpcDropManager.java