RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd Class Reference
com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd Class Reference
Handles the dragon halbard weapon special attack.
Public Member Functions
void attack (Player attacker, Mob defender, Hit hit)
Animation getAttackAnimation (Player attacker, Mob defender)
CombatHit[] getHits (Player attacker, Mob defender)
int modifyAccuracy (Player attacker, Mob defender, int roll)
int modifyDamage (Player attacker, Mob defender, int damage)
void start (Player attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy
boolean canAttack (Player attacker, Mob defender)
int getAttackDelay (Player attacker, Mob defender, FightType fightType)
int getAttackDistance (Player attacker, FightType fightType)
CombatType getCombatType ()
void hit (Player attacker, Mob defender, Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static DragonHaldberd get ()
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Static Private Attributes
static final Animation ANIMATION = new Animation(1203, UpdatePriority.HIGH)
static final Graphic GRAPHIC = new Graphic(1172, true, UpdatePriority.HIGH)
static final DragonHaldberd INSTANCE = new DragonHaldberd()
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy
PlayerMeleeStrategy ()
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Handles the dragon halbard weapon special attack.
Author
Daniel
Definition at line 17 of file DragonHaldberd.java.
Member Function Documentation
attack()
void com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.attack (Player attacker, Mob defender, Hit hit)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.
Definition at line 28 of file DragonHaldberd.java.
{
        super.attack(attacker, defender, hit);
        attacker.graphic(GRAPHIC);
    }
References GRAPHIC, com.runehive.game.world.entity.mob.Mob.graphic, and com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.hit().
get()
DragonHaldberd com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.get () static
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.
Definition at line 59 of file DragonHaldberd.java.
{
        return INSTANCE;
    }
References INSTANCE.
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.getAttackAnimation (Player attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.
Definition at line 45 of file DragonHaldberd.java.
{
        return ANIMATION;
    }
References ANIMATION.
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.getHits (Player attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.
Definition at line 34 of file DragonHaldberd.java.
{
        if (defender.width() > 1 && defender.length() > 1) {
            CombatHit primary = nextMeleeHit(attacker, defender);
            CombatHit secondary = nextMeleeHit(attacker, defender);
            return new CombatHit[]{primary, secondary};
        }
        return new CombatHit[]{nextMeleeHit(attacker, defender)};
    }
References com.runehive.game.world.entity.Entity.length, com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit(), and com.runehive.game.world.entity.Entity.width.
modifyAccuracy()
int com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.modifyAccuracy (Player attacker, Mob defender, int roll)
Definition at line 50 of file DragonHaldberd.java.
{
        return roll - roll / 4;
    }
modifyDamage()
int com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.modifyDamage (Player attacker, Mob defender, int damage)
Definition at line 55 of file DragonHaldberd.java.
{
        return damage * 11 / 10;
    }
start()
void com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.start (Player attacker, Mob defender, Hit[] hits)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.
Definition at line 23 of file DragonHaldberd.java.
{
        super.start(attacker, defender, hits);
    }
Member Data Documentation
ANIMATION
final Animation com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.ANIMATION = new Animation(1203, UpdatePriority.HIGH) static private
Definition at line 19 of file DragonHaldberd.java.
Referenced by getAttackAnimation().
GRAPHIC
final Graphic com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.GRAPHIC = new Graphic(1172, true, UpdatePriority.HIGH) static private
Definition at line 20 of file DragonHaldberd.java.
Referenced by attack().
INSTANCE
final DragonHaldberd com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonHaldberd.INSTANCE = new DragonHaldberd() static private
Definition at line 18 of file DragonHaldberd.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/special/melee/DragonHaldberd.java