RuneHive-Game: com.runehive.game.action.impl.BuryBoneAction Class Reference
com.runehive.game.action.impl.BuryBoneAction Class Reference
Handles burying a bone.
Public Member Functions
Optional< SkillAnimation > animation ()
The skill animation to execute.
BuryBoneAction (Player player, BoneData bone, int slot)
boolean canInit ()
Determines if this action can be initialized.
double experience ()
The experience given from this action.
String getName ()
Gets the name of this action.
WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
void init ()
Any functionality that should be handled when this action is submitted.
void onCancel (boolean logout)
A function executed on cancellation.
void onExecute ()
The method which is called on intervals of the specified #delay;.
boolean prioritized ()
Determines if this action is prioritized.
int skill ()
The skill we should hand to experience to.
Public Member Functions inherited from com.runehive.content.skill.SkillAction
boolean ignore ()
Determines if future skill actions from the same type should be ignored.
SkillAction (Mob mob, Optional< Position > position, boolean instant)
Creates a new Action randomevent.
SkillAction (Mob mob, Optional< Position > position, int delay, boolean instant)
Creates a new Action randomevent.
final void start ()
Attempts to start the skill.
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Private Attributes
final BoneData bone
final Item item
final int slot
Additional Inherited Members
Protected Member Functions inherited from com.runehive.content.skill.SkillAction
final void execute ()
A function representing the unit of work that will be carried out.
final void onSchedule ()
A function executed on registration.
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
Handles burying a bone.
Author
Michael | Chex
Definition at line 23 of file BuryBoneAction.java.
Constructor & Destructor Documentation
BuryBoneAction()
com.runehive.game.action.impl.BuryBoneAction.BuryBoneAction (Player player, BoneData bone, int slot)
Definition at line 28 of file BuryBoneAction.java.
{
        super(player, Optional.empty(), true);
        this.slot = slot;
        this.bone = bone;
        this.item = player.inventory.get(slot);
    }
References bone, com.runehive.game.world.items.containers.ItemContainer.get(), and com.runehive.game.world.entity.mob.player.Player.inventory.
Member Function Documentation
animation()
Optional< SkillAnimation > com.runehive.game.action.impl.BuryBoneAction.animation ()
The skill animation to execute.
Returns
the skill animation to execute.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 80 of file BuryBoneAction.java.
{
        return Optional.empty();
    }
canInit()
boolean com.runehive.game.action.impl.BuryBoneAction.canInit ()
Determines if this action can be initialized.
Returns
true if it can, false otherwise.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 36 of file BuryBoneAction.java.
{
        return getMob().skills.getSkills()[skill()].stopwatch.elapsed(1200);
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), and skill().
experience()
double com.runehive.game.action.impl.BuryBoneAction.experience ()
The experience given from this action.
Returns
the numerical value representing the amount of experience given.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 85 of file BuryBoneAction.java.
{
        double exp = (bone.getExperience() * Config.PRAYER_MODIFICATION);
        if (SkillCape.isEquipped(getMob().getPlayer(), SkillCape.PRAYER)) {
            exp *= 2.0;
        }
        return exp;
    }
References bone, com.runehive.game.action.Action< T extends Mob >.getMob(), com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.content.skillcape.SkillCape.PRAYER, and com.runehive.Config.PRAYER_MODIFICATION.
Referenced by onExecute().
getName()
String com.runehive.game.action.impl.BuryBoneAction.getName ()
Gets the name of this action.
Returns
The name of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 99 of file BuryBoneAction.java.
{
        return "Bone bury";
    }
getWalkablePolicy()
WalkablePolicy com.runehive.game.action.impl.BuryBoneAction.getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 109 of file BuryBoneAction.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
init()
void com.runehive.game.action.impl.BuryBoneAction.init ()
Any functionality that should be handled when this action is submitted.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 41 of file BuryBoneAction.java.
                       {
    }
onCancel()
void com.runehive.game.action.impl.BuryBoneAction.onCancel (boolean logout)
A function executed on cancellation.
Reimplemented from com.runehive.game.task.Task.
Definition at line 75 of file BuryBoneAction.java.
{
        getMob().skills.getSkills()[skill()].stopwatch.reset();
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), and skill().
onExecute()
void com.runehive.game.action.impl.BuryBoneAction.onExecute ()
The method which is called on intervals of the specified #delay;.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 46 of file BuryBoneAction.java.
{
        getMob().animate(new Animation(827));
        Player player = getMob().getPlayer();
        player.inventory.remove(item, slot, true);
        player.skills.addExperience(skill(), experience());
        player.send(new SendMessage("You bury the " + item.getName() + "."));
        AchievementHandler.activate(player, AchievementKey.BURY_BONES, 1);
        if (player.equipment.hasAmulet() && player.equipment.getAmuletSlot().getId() == 22111) {
            int current = player.skills.getLevel(Skill.PRAYER);
            int maximum = player.skills.getMaxLevel(Skill.PRAYER);
            if (current < maximum) {
                int points = bone.getBoneAmulet();
                if (current + points > maximum) {
                    points = maximum - current;
                }
                player.skills.get(Skill.PRAYER).addLevel(points);
                player.skills.refresh(Skill.PRAYER);
                player.message("You feel your " + player.equipment.getAmuletSlot().getName() + " vibrate as you bury the bone.");
            }
        }
        cancel();
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.skill.Skill.addLevel(), bone, com.runehive.content.achievement.AchievementKey.BURY_BONES, com.runehive.game.task.Task.cancel(), com.runehive.game.world.entity.mob.player.Player.equipment, experience(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.items.containers.equipment.Equipment.getAmuletSlot(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.action.Action< T extends Mob >.getMob(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.items.containers.equipment.Equipment.hasAmulet(), com.runehive.game.world.entity.mob.player.Player.inventory, item, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.skill.SkillManager.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), skill(), and com.runehive.game.world.entity.mob.Mob.skills.
prioritized()
boolean com.runehive.game.action.impl.BuryBoneAction.prioritized ()
Determines if this action is prioritized.
When making an action prioritized, the next action will be ignored if not queued.
Returns
true if this action is prioritized, false otherwise.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 104 of file BuryBoneAction.java.
{
        return false;
    }
skill()
int com.runehive.game.action.impl.BuryBoneAction.skill ()
The skill we should hand to experience to.
Reimplemented from com.runehive.content.skill.SkillAction.
Definition at line 94 of file BuryBoneAction.java.
                       {
        return Skill.PRAYER;
    }
References com.runehive.game.world.entity.skill.Skill.PRAYER.
Referenced by canInit(), onCancel(), and onExecute().
Member Data Documentation
bone
final BoneData com.runehive.game.action.impl.BuryBoneAction.bone private
Definition at line 26 of file BuryBoneAction.java.
Referenced by BuryBoneAction(), experience(), and onExecute().
item
final Item com.runehive.game.action.impl.BuryBoneAction.item private
Definition at line 25 of file BuryBoneAction.java.
Referenced by onExecute().
slot
final int com.runehive.game.action.impl.BuryBoneAction.slot private
Definition at line 24 of file BuryBoneAction.java.
The documentation for this class was generated from the following file:
java/com/runehive/game/action/impl/BuryBoneAction.java