RuneHive-Game: com.runehive.game.world.entity.mob.player.PlayerDeath Class Reference
com.runehive.game.world.entity.mob.player.PlayerDeath Class Reference
Handles the player death listener.
Public Member Functions
void death ()
The main part of the death process where the killer is found for the character.
void postDeath (Mob killer)
The last part of the death process where the character is reset.
void preDeath (Mob killer)
The part of the death process where the character is prepared for the rest of the death tick.
Public Member Functions inherited from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >
final void execute ()
A function representing the unit of work that will be carried out.
MobDeath (T mob, int delay)
Creates a new MobDeath.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Package Functions
PlayerDeath (Player mob)
Creates a new MobDeath.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Private Member Functions
void calculateDropItems (Player character, Mob killer, boolean purchase)
Calculates and drops all of the items from character for killer.
Private Attributes
boolean safe = false
Static Private Attributes
static final String[] DEATH_MESSAGES
Array of all death messages.
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
Protected Attributes inherited from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >
final T mob
The mob.
Detailed Description
Handles the player death listener.
Author
Daniel
Definition at line 48 of file PlayerDeath.java.
Constructor & Destructor Documentation
PlayerDeath()
com.runehive.game.world.entity.mob.player.PlayerDeath.PlayerDeath (Player mob) package
Creates a new MobDeath.
Definition at line 66 of file PlayerDeath.java.
{
        super(mob, 2);
    }
References com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob.
Member Function Documentation
calculateDropItems()
void com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems (Player character, Mob killer, boolean purchase) private
Calculates and drops all of the items from character for killer.
Definition at line 210 of file PlayerDeath.java.
{
        Player theKiller = killer == null || killer.isNpc() ? character : killer.getPlayer();
        if (character.right.equals(PlayerRight.ULTIMATE_IRONMAN)) {
            List<Item> items = new LinkedList<>();
            character.equipment.forEach(items::add);
            character.inventory.forEach(items::add);
            character.lootingBag.forEach(items::add);
            character.equipment.clear();
            character.inventory.clear();
            character.lootingBag.clear();
            items.forEach(item -> {
                if (!item.isTradeable()) {
                    if (!character.lostUntradeables.deposit(item)) {
                        GroundItem.create(character, item);
                    }
                } else {
                    GroundItem.create(theKiller, item, character.getPosition());
                }
            });
            return;
        }
        LinkedList<Item> toDrop = new LinkedList<>();
        List<Item> keep = new LinkedList<>();
        List<Item> items = new LinkedList<>();
        character.equipment.forEach(items::add);
        Item[] lootingBag = character.lootingBag.getDeathItems();
        character.inventory.forEach(item -> {
            if (!LootingBagPlugin.isLootingBag(item)) {
                items.add(item);
            }
        });
        character.equipment.clear();
        character.inventory.clear();
        if (lootingBag != null) {
            items.addAll(Arrays.asList(lootingBag));
            character.lootingBag.clear();
        }
        toDrop.addAll(items);
        toDrop.sort((first, second) -> second.getValue() - first.getValue());
        if (!character.skulling.isSkulled()) {
            keep.add(toDrop.pollFirst());
            keep.add(toDrop.pollFirst());
            keep.add(toDrop.pollFirst());
        }
        if (character.prayer.isActive(Prayer.PROTECT_ITEM)) {
            keep.add(toDrop.pollFirst());
        }
        keep.forEach(item -> {
            if (item == null) {
                return;
            }
            character.inventory.add(new Item(item.getId()));
            if (item.isStackable() && item.getAmount() > 1) {
                toDrop.add(item.createAndDecrement(1));
            }
        });
        if (theKiller.isBot) {
            toDrop.forEach(item -> {
                if (character.runecraftPouch.death(item))
                    return;
                if (character.runePouch.death(item))
                    return;
                if (!item.isTradeable()) {
                    if (!character.lostUntradeables.deposit(item)) {
                        GroundItem.create(character, item);
                    }
                    return;
                }
                if (theKiller.isBot && item.getValue() >= 50_000) {
                    return;
                }
                BotUtility.logLoot(item);
            });
            GroundItem drop = GroundItem.create(theKiller, new Item(526), character.getPosition());
            if (!theKiller.equals(character) && PlayerRight.isIronman(theKiller)) {
                drop.canIronMenPickThisItemUp = false;
            }
            return;
        }
        toDrop.forEach(item -> {
            if (character.runecraftPouch.death(item))
                return;
            if (character.runePouch.death(item))
                return;
            if (purchase) {
                character.lostItems.add(item);
                return;
            }
            if (!item.isTradeable()) {
                if (!character.lostUntradeables.deposit(item)) {
                    GroundItem.create(character, item);
                }
                return;
            }
            if (theKiller.isBot && item.getValue() >= 50_000) {
                return;
            }
            switch(item.getId()) {
                case CrawsBow.CRAWS_CHARGED_ID -> {
                    item.setId(CrawsBow.CRAWS_UNCHARGED_ID);
                    GroundItem drop = GroundItem.create(theKiller, new Item(CrawsBow.ETHER_ID, 1000 + character.crawsBowCharges), character.getPosition());
                    if (!theKiller.equals(character) && PlayerRight.isIronman(theKiller)) {
                        drop.canIronMenPickThisItemUp = false;
                    }
                    character.crawsBowCharges = 0;
                }
                case ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID -> {
                    item.setId(ViggorasChainmace.VIGGORAS_CHAINMACE_UNCHARGED_ID);
                    GroundItem drop = GroundItem.create(theKiller, new Item(CrawsBow.ETHER_ID, 1000 + character.viggorasChainmaceCharges), character.getPosition());
                    if (!theKiller.equals(character) && PlayerRight.isIronman(theKiller)) {
                        drop.canIronMenPickThisItemUp = false;
                    }
                    character.viggorasChainmaceCharges = 0;
                }
                case ThammaronsSceptre.THAMMARONS_SCEPTRE_CHARGED_ID -> {
                    item.setId(ViggorasChainmace.VIGGORAS_CHAINMACE_UNCHARGED_ID);
                    GroundItem drop = GroundItem.create(theKiller, new Item(CrawsBow.ETHER_ID, 1000 + character.thammoranSceptreCharges), character.getPosition());
                    if (!theKiller.equals(character) && PlayerRight.isIronman(theKiller)) {
                        drop.canIronMenPickThisItemUp = false;
                    }
                    character.thammoranSceptreCharges = 0;
                }
            }
            GroundItem drop = GroundItem.create(theKiller, item, character.getPosition());
            if (!theKiller.equals(character) && PlayerRight.isIronman(theKiller)) {
                drop.canIronMenPickThisItemUp = false;
            }
        });
        GroundItem drop = GroundItem.create(theKiller, new Item(526), character.getPosition());
        if (!theKiller.equals(character) && PlayerRight.isIronman(theKiller)) {
            drop.canIronMenPickThisItemUp = false;
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.equipment.Equipment.clear(), com.runehive.game.world.items.containers.ItemContainer.clear(), com.runehive.content.itemaction.impl.CrawsBow.CRAWS_CHARGED_ID, com.runehive.content.itemaction.impl.CrawsBow.CRAWS_UNCHARGED_ID, com.runehive.game.world.entity.mob.player.Player.crawsBowCharges, com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.content.skill.impl.magic.RunePouch.death(), com.runehive.content.skill.impl.runecrafting.RunecraftPouch.death(), com.runehive.game.world.items.containers.impl.LostUntradeables.deposit(), com.runehive.game.world.entity.mob.player.Player.equals(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.content.itemaction.impl.CrawsBow.ETHER_ID, com.runehive.game.world.items.containers.ItemContainer.forEach(), com.runehive.game.world.items.containers.impl.LootingBag.getDeathItems(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.player.Player.isBot, com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.content.combat.Skulling.isSkulled(), com.runehive.content.bot.BotUtility.logLoot(), com.runehive.game.world.entity.mob.player.Player.lootingBag, com.runehive.game.world.entity.mob.player.Player.lostItems, com.runehive.game.world.entity.mob.player.Player.lostUntradeables, com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_ITEM, com.runehive.game.world.entity.mob.player.Player.right, com.runehive.game.world.entity.mob.player.Player.runecraftPouch, com.runehive.game.world.entity.mob.player.Player.runePouch, com.runehive.game.world.entity.mob.player.Player.skulling, com.runehive.content.itemaction.impl.ThammaronsSceptre.THAMMARONS_SCEPTRE_CHARGED_ID, com.runehive.game.world.entity.mob.player.Player.thammoranSceptreCharges, com.runehive.game.world.entity.mob.player.PlayerRight.ULTIMATE_IRONMAN, com.runehive.content.itemaction.impl.ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID, com.runehive.content.itemaction.impl.ViggorasChainmace.VIGGORAS_CHAINMACE_UNCHARGED_ID, and com.runehive.game.world.entity.mob.player.Player.viggorasChainmaceCharges.
Referenced by death().
death()
void com.runehive.game.world.entity.mob.player.PlayerDeath.death ()
The main part of the death process where the killer is found for the character.
Reimplemented from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.
Definition at line 79 of file PlayerDeath.java.
{
        Mob killer = mob.getCombat().getDamageCache().calculateProperKiller().orElse(null);
        if (mob.inActivity()) {
            ActivityDeathType deathType = mob.activity.deathType();
            if (PlayerRight.isAdministrator(mob)) {
                safe = true;
                return;
            }
            if (deathType == ActivityDeathType.SAFE) {
                safe = true;
            } else if (deathType == ActivityDeathType.NORMAL) {
                Pets.onDeath(mob);
                calculateDropItems(mob, killer, false);
            } else if (deathType == ActivityDeathType.PURCHASE) {
                calculateDropItems(mob, killer, true);
                mob.message("You have lost your items. Speak to Lord Marshal Brogan at home to claim them!");
            }
            return;
        }
        if(mob.playTime < 6000) {
            System.out.println("Safe death");
            safe = true;
            mob.message("Your death is safe because you have less than 1 hour of playtime.");
            return;
        }
        if (Area.inZulrah(mob)) {
            safe = true;
            return;
        }
      /*  if (Area.inEventArena(mob)) {
            safe = true;
            return;
        }*/
        if(mob.isPlayer() && LMSGame.inGameArea(mob.getPlayer()) && killer != null && killer.isPlayer()) {
            safe = true;
            LMSGame.onKill(killer.getPlayer());
            return;
        }
        if (!PlayerRight.isAdministrator(mob)) {
            Pets.onDeath(mob);
            calculateDropItems(mob, killer, false);
        }
        if (killer == null || !killer.isPlayer())
            return;
        Player playerKiller = killer.getPlayer();
        if (mob.isBot) {
            playerKiller.message("<col=295EFF>You were rewarded with 100 blood money for that bot kill.");
            playerKiller.inventory.addOrDrop(new Item(13307, 100));
            return;
        }
        playerKiller.kill++;
        mob.death++;
        if (!PlayerKilling.contains(playerKiller, mob.lastHost)) {
            AchievementHandler.activate(playerKiller, AchievementKey.KILLER, 1);
            playerKiller.send(new SendMessage(Utility.randomElement(DEATH_MESSAGES).replace("$VICTIM", mob.getName())));
            PlayerKilling.handle(playerKiller, mob);
        } else {
            playerKiller.message("<col=FF0019>You have recently killed " + mob.getName() + " and were not rewarded. You must kill 2 other players to reset this!");
        }
        EventDispatcher.execute(playerKiller, new OnKillEvent(mob));
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), calculateDropItems(), com.runehive.game.world.entity.mob.player.PlayerKilling.contains(), DEATH_MESSAGES, com.runehive.content.event.EventDispatcher.execute(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.player.PlayerKilling.handle(), com.runehive.content.lms.LMSGame.inGameArea(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.position.Area.inZulrah(), com.runehive.game.world.entity.mob.player.PlayerRight.isAdministrator(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.player.Player.kill, com.runehive.content.achievement.AchievementKey.KILLER, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob, com.runehive.content.activity.ActivityDeathType.NORMAL, com.runehive.content.pet.Pets.onDeath(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.activity.ActivityDeathType.PURCHASE, com.runehive.util.Utility.randomElement(), com.runehive.content.activity.ActivityDeathType.SAFE, safe, and com.runehive.game.world.entity.mob.player.Player.send().
postDeath()
void com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath (Mob killer)
The last part of the death process where the character is reset.
Reimplemented from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.
Definition at line 155 of file PlayerDeath.java.
{
        if (mob.isBot) {
            ((PlayerBot) mob).postDeath();
            return;
        }
        mob.playerAssistant.restore();
        if(mob.isPlayer() && LMSGame.isActivePlayer(mob.getPlayer())) {
            LMSGame.onDeath(mob.getPlayer(), false);
            return;
        }
        if (mob.inActivity()) {
            Activity.forActivity(mob, it -> it.onDeath(mob));
            return;
        }
        if(mob.isPlayer()) {
            ImbuedHeartPlugin.resetCooldown(mob);
        }
        mob.hasPvPTimer = false;
        mob.move(mob.pvpInstance ? new Position(3093, 3494,4) : Config.DEFAULT_POSITION);
        mob.send(new SendMessage("Oh dear, you are dead!"));
        mob.send(new SendCameraReset());
        mob.face(Direction.SOUTH);
        mob.equipment.updateAnimation();
        mob.equipment.refresh();
        mob.animate(Animation.RESET, true);
        mob.graphic(Graphic.RESET, true);
        Pets.onDeath(mob);
        WeaponInterface.execute(mob, mob.equipment.getWeapon());
        InterfaceWriter.write(new InformationWriter(mob));
        if (!safe) {
            if (killer != null && killer.isPlayer() && !mob.equals(killer)) {
                mob.killstreak.end(killer.getPlayer());
            }
            if (mob.right == PlayerRight.HARDCORE_IRONMAN) {
                mob.right = PlayerRight.IRONMAN;
                mob.updateFlags.add(UpdateFlag.APPEARANCE);
                mob.send(new SendMessage("You have lost your hardcore iron man status since you died!"));
                World.sendMessage("<icon=1> <col=FF0000>osroyale: <col=" + mob.right.getColor() + ">" + mob.getName() + "</col>'s hardcore iron man account was lost!");
            }
        }
        if (mob.presetManager.deathOpen) {
            World.schedule(1, mob.presetManager::open);
        }
        if (!mob.lostItems.isEmpty()) {
            mob.dialogueFactory.sendStatement("There are lost items waiting for you!", "Speak to Lord Marshal Brogan at home to claim them!").execute();
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.Config.DEFAULT_POSITION, com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.content.activity.Activity.forActivity(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.player.PlayerRight.HARDCORE_IRONMAN, com.runehive.game.world.entity.mob.player.PlayerRight.IRONMAN, com.runehive.content.lms.LMSGame.isActivePlayer(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob, com.runehive.content.lms.LMSGame.onDeath(), com.runehive.content.pet.Pets.onDeath(), postDeath(), com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, safe, com.runehive.game.world.World.schedule(), com.runehive.game.world.World.sendMessage(), com.runehive.game.world.entity.mob.Direction.SOUTH, and com.runehive.content.writer.InterfaceWriter.write().
Referenced by postDeath().
preDeath()
void com.runehive.game.world.entity.mob.player.PlayerDeath.preDeath (Mob killer)
The part of the death process where the character is prepared for the rest of the death tick.
Reimplemented from com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.
Definition at line 72 of file PlayerDeath.java.
{
        mob.animate(new Animation(836, UpdatePriority.VERY_HIGH));
        mob.graphic(new Graphic(293, UpdatePriority.VERY_HIGH));
    }
References com.runehive.game.world.entity.mob.MobDeath< T extends Mob >.mob, and com.runehive.game.UpdatePriority.VERY_HIGH.
Member Data Documentation
DEATH_MESSAGES
final String [] com.runehive.game.world.entity.mob.player.PlayerDeath.DEATH_MESSAGES static private
Initial value:
= {
            "You have defeated $VICTIM.",
            "With a crushing blow, you defeat $VICTIM.",
            "It's a humiliating defeat for $VICTIM.",
            "$VICTIM didn't stand a chance against you.",
            "You have defeated $VICTIM.",
            "It's all over for $VICTIM.",
            "$VICTIM regrets the day they met you in combat.",
            "$VICTIM falls before your might.",
            "Can anyone defeat you? Certainly not $VICTIM.",
            "You were clearly a better fighter than $VICTIM."
    }
Array of all death messages.
Definition at line 52 of file PlayerDeath.java.
{
            "You have defeated $VICTIM.",
            "With a crushing blow, you defeat $VICTIM.",
            "It's a humiliating defeat for $VICTIM.",
            "$VICTIM didn't stand a chance against you.",
            "You have defeated $VICTIM.",
            "It's all over for $VICTIM.",
            "$VICTIM regrets the day they met you in combat.",
            "$VICTIM falls before your might.",
            "Can anyone defeat you? Certainly not $VICTIM.",
            "You were clearly a better fighter than $VICTIM."
    };
Referenced by death().
safe
boolean com.runehive.game.world.entity.mob.player.PlayerDeath.safe = false private
Definition at line 49 of file PlayerDeath.java.
Referenced by death(), and postDeath().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/PlayerDeath.java