RuneHive-Game: com.runehive.content.wintertodt.Wintertodt Class Reference
com.runehive.content.wintertodt.Wintertodt Class Reference
Static Public Member Functions
static void addPoints (Player player, int amount)
Handles adding wintertodt points to a player.
static void chopRoot (Player player)
Handles chopping the root.
static void feedBrazier (Player player, GameObject gameObject)
Handles feeding the brazier.
static void fixBrazier (Player player, GameObject gameObject)
Handles fixing the brazier.
static void fletch (Player player)
Handles fetching the kindling.
static int getAreaAttackDamage (Player player)
Handles the formula on how much the area attack can do.
static int getBrazierAttackDamage (Player player)
How much damage the brazier does to a player when it breaks.
static int getBraziersLit ()
How many braziers are currently lit.
static int getColdDamage (Player player)
The amount of damagae the player gets from cold.
static int getWarmItemsWorn (Player player)
How much warm clothing the player is wearing.
static void healPyromancer (Player player, Npc npc, int slot)
Handles healing the pyromancer.
static void init ()
static boolean isActive ()
static void lightBrazier (Player player, GameObject gameObject)
Handles lighting a brazier.
static void mixHerb (Player player)
Handles mixing the potion.
static void removeGameItems (Player player)
Handles removes the items within the wintertodt game.
static void send (Player player)
static void shootFlame (Brazier brazier)
Handles spawning the flame that goes to the middle.
static void takeHerb (Player player)
Handles taking a bruma herb.
Static Public Attributes
static final Brazier[] BRAZIERS
Brazier data.
static final int BROKEN_BRAZIER_ID = 29313
static final int BRUMA_HERB = 20698
static final int BRUMA_KINDLING = 20696
static final int BRUMA_ROOT = 20695
Item ids.
static final int BURNING_BRAZIER_ID = 29314
static final int EMPTY_BRAZIER_ID = 29312
static int health = 0
static final int INCAPACITATED_PYROMANCER = 7372
static final int MAX_HP = 3500
static final int PYROMANCER = 7371
static Region region
static final int REGION_ID = 6462
Region of the wintertodt game.
static final int REJUV_POT_1 = 20702
static final int REJUV_POT_2 = 20701
static final int REJUV_POT_3 = 20700
static final int REJUV_POT_4 = 20699
static final int REJUV_POT_UNF = 20697
Static Private Member Functions
static void applyColdDamage ()
static void attackPyromancers ()
Handles attacking the pyromancers.
static void award (Player player)
Handles awarding players with crates.
static void breakBrazier (Brazier brazier)
Handles breaking the brazier.
static void dealDamage ()
Handles dealing damage to the boss.
static void death ()
Handles the death of the boss.
static void doMagicAttack ()
Handles doing the magic attack by the bnoss.
static void extinguishBraziers ()
Handles extinguishing the braziers.
static void pyromancerText ()
Handles the pyromancer speech.
static void start ()
static void update ()
Static Private Attributes
static final int ACTIVE_STORM_ID = 29308
static final int DEFAULT_DELAY = 10
static final int FLAME = 7373
static final List< Integer > GAME_ITEMS = Arrays.asList(BRUMA_ROOT, BRUMA_KINDLING, BRUMA_HERB, REJUV_POT_UNF, REJUV_POT_4, REJUV_POT_3, REJUV_POT_2, REJUV_POT_1)
List of all minigame items.
static final int INACTIVE_STORM_ID = 29309
static final String[] PYROMANCER_DEAD_TEXT = {"My flame burns low.", "Mummy!", "I think I'm dying.", "We are doomed.", "Ugh, help me!"}
Npc ids.
static int pyroSpeechDelay
static final int SNOW_EFFECT_ID = 26690
Game object ids.
static int startDelay = DEFAULT_DELAY
static boolean started = false
Game data.
static final List< Integer > WARM_CLOTHING
List of all warm clothing.
static CustomGameObject WINTERTODT
Detailed Description
Definition at line 31 of file Wintertodt.java.
Member Function Documentation
addPoints()
void com.runehive.content.wintertodt.Wintertodt.addPoints (Player player, int amount) static
Handles adding wintertodt points to a player.
Definition at line 814 of file Wintertodt.java.
{
        int old = player.wintertodtPoints;
        player.wintertodtPoints += amount;
        if (old < 500 && player.wintertodtPoints >= 500) {
            player.message("You have helped enough to earn a supply crate. Further work will go towards better rewards.");
        }
        send(player);
    }
References com.runehive.game.world.entity.mob.player.Player.message(), send(), and com.runehive.game.world.entity.mob.player.Player.wintertodtPoints.
Referenced by com.runehive.content.wintertodt.actions.FeedBrazier.execute(), com.runehive.content.wintertodt.actions.FixBrazier.execute(), com.runehive.content.wintertodt.actions.LightBrazier.execute(), and healPyromancer().
applyColdDamage()
void com.runehive.content.wintertodt.Wintertodt.applyColdDamage () static private
Definition at line 251 of file Wintertodt.java.
{
        region.getPlayers(0).forEach(player -> {
            if(player.getPosition().getY() <= 3987 || Utility.random(25) != 0) return;
            player.damage(new Hit(getColdDamage(player)));
            player.message("The cold of the Wintertodt seeps into your bones.");
            if(player.action.getCurrentAction() instanceof WintertodtAction)
                player.action.getCurrentAction().cancel();
        });
    }
References getColdDamage(), com.runehive.util.Utility.random(), and region.
Referenced by init().
attackPyromancers()
void com.runehive.content.wintertodt.Wintertodt.attackPyromancers () static private
Handles attacking the pyromancers.
Definition at line 411 of file Wintertodt.java.
{
        List<Npc> pyros = Arrays.stream(BRAZIERS).filter(Brazier::isPyromancerAlive).map(Brazier::getPyromancer).collect(Collectors.toList());
        if (!pyros.isEmpty() && Utility.random(pyros.size() * 30) == pyros.size()) {
            Npc pyro = pyros.get(Utility.random(pyros.size()));
            if(pyro.pyroHealth <= 0) return;
            if(pyro.pyroSnowAttack) {
                System.out.println("already a snow attack going for this pyro...");
                return;
            }
            pyro.pyroSnowAttack = true;
            GameObject snow = new CustomGameObject(SNOW_EFFECT_ID, pyro.getPosition());
            snow.register();
            World.schedule(new Task(4) {
                @Override
                public void execute() {
                    int damage = 6 + Utility.random(4);
                    if(damage > pyro.pyroHealth)
                        damage = pyro.pyroHealth;
                    pyro.pyroHealth -= damage;
                    pyro.writeFakeDamage(new Hit(damage));
                    if(pyro.pyroHealth <= 0) {
                        pyro.pyroHealth = 0;
                        pyro.transform(INCAPACITATED_PYROMANCER);
                    }
                    pyro.pyroSnowAttack = false;
                    region.getPlayers(0).forEach(players -> {
                        players.send(new SendRemoveObject(new CustomGameObject(snow.getId(), snow.getPosition())));
                    });
                    snow.unregister();
                    this.cancel();
                }
            });
        }
    }
References BRAZIERS, com.runehive.game.world.object.GameObject.getId(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.object.GameObject.getPosition(), com.runehive.content.wintertodt.Brazier.getPyromancer(), INCAPACITATED_PYROMANCER, com.runehive.content.wintertodt.Brazier.isPyromancerAlive(), com.runehive.game.world.entity.mob.npc.Npc.pyroHealth, com.runehive.game.world.entity.mob.npc.Npc.pyroSnowAttack, com.runehive.util.Utility.random(), region, com.runehive.game.world.object.GameObject.register(), com.runehive.game.world.World.schedule(), SNOW_EFFECT_ID, com.runehive.game.world.entity.mob.Mob.transform(), com.runehive.game.world.object.GameObject.unregister(), and com.runehive.game.world.entity.mob.Mob.writeFakeDamage().
Referenced by init().
award()
void com.runehive.content.wintertodt.Wintertodt.award (Player player) static private
Handles awarding players with crates.
Definition at line 530 of file Wintertodt.java.
{
        removeGameItems(player);
        if (player.wintertodtPoints >= 500) {
            CollectionLog.increaseCounter(player, CollectionLogData.WINTERTODT);
            player.skills.addExperience(Skill.FIREMAKING, (Skill.getLevelForExperience(player.skills.get(Skill.FIREMAKING).getExperience()) * 100) * Config.FIREMAKING_MODIFICATION);
            int crates = player.wintertodtPoints / 500;
            if (crates > 1)
                player.message("You have gained " + crates + " supply crates!");
            else
                player.message("You have gained a supply crate!");
            player.inventory.add(new Item(20703, crates));
            player.inventory.refresh();
        } else player.message("You did not earn enough points to be worthy of a gift from the citizens of Kourend this time.");
        player.wintertodtPoints = 0;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.skill.Skill.FIREMAKING, com.runehive.Config.FIREMAKING_MODIFICATION, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.Skill.getExperience(), com.runehive.game.world.entity.skill.Skill.getLevelForExperience(), com.runehive.content.collectionlog.CollectionLog.increaseCounter(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), removeGameItems(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.content.collectionlog.CollectionLogData.WINTERTODT, and com.runehive.game.world.entity.mob.player.Player.wintertodtPoints.
Referenced by death().
breakBrazier()
void com.runehive.content.wintertodt.Wintertodt.breakBrazier (Brazier brazier) static private
Handles breaking the brazier.
Definition at line 288 of file Wintertodt.java.
{
        if(brazier.getObject().getId() == BROKEN_BRAZIER_ID) return;
        List<GameObject> objects = Arrays.asList(
                new CustomGameObject(SNOW_EFFECT_ID, new Position(brazier.getObject().getPosition().getX() + 1, brazier.getObject().getPosition().getY(), 0)),
                new CustomGameObject(SNOW_EFFECT_ID, new Position(brazier.getObject().getPosition().getX(), brazier.getObject().getPosition().getY() + 1, 0)),
                new CustomGameObject(SNOW_EFFECT_ID, new Position(brazier.getObject().getPosition().getX() + 1, brazier.getObject().getPosition().getY() + 1, 0)),
                new CustomGameObject(SNOW_EFFECT_ID, new Position(brazier.getObject().getPosition().getX() + 2, brazier.getObject().getPosition().getY() + 1, 0)),
                new CustomGameObject(SNOW_EFFECT_ID, new Position(brazier.getObject().getPosition().getX() + 1, brazier.getObject().getPosition().getY() + 2, 0))
        );
        for(GameObject gameObject : objects)
            gameObject.register();
        brazier.setSnowStorm(true);
        World.schedule(new Task(4) {
            @Override
            public void execute() {
                for(GameObject gameObject : objects) {
                    gameObject.unregister();
                    region.getPlayers(0).forEach(players -> {
                        players.send(new SendRemoveObject(new CustomGameObject(gameObject.getId(), gameObject.getPosition())));
                    });
                }
                brazier.setSnowStorm(false);
                if(isActive()) {
                    //Graphio (502, 90, 0)
                    //brazier.getObject().transform(BROKEN_BRAZIER_ID);
                    brazier.getObject().unregister();
                    brazier.setObject(Wintertodt.BROKEN_BRAZIER_ID);
                    brazier.getObject().register();
                    region.getPlayers(0).forEach(player -> {
                        if(Utility.goodDistance(brazier.getObject().getPosition().getX() + 1, brazier.getObject().getPosition().getY() + 1, player.getPosition().getX(), player.getPosition().getY(), 2)) {
                            player.message("The brazier is broken and shrapnel damages you.");
                            player.damage(new Hit(Utility.random(getBrazierAttackDamage(player))));
                        }
                    });
                }
                this.cancel();
            }
        });
    }
References BROKEN_BRAZIER_ID, getBrazierAttackDamage(), com.runehive.game.world.object.GameObject.getId(), com.runehive.content.wintertodt.Brazier.getObject(), com.runehive.game.world.object.GameObject.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.util.Utility.goodDistance(), isActive(), com.runehive.util.Utility.random(), region, com.runehive.game.world.object.GameObject.register(), com.runehive.game.world.World.schedule(), com.runehive.content.wintertodt.Brazier.setObject(), com.runehive.content.wintertodt.Brazier.setSnowStorm(), SNOW_EFFECT_ID, and com.runehive.game.world.object.GameObject.unregister().
Referenced by extinguishBraziers().
chopRoot()
void com.runehive.content.wintertodt.Wintertodt.chopRoot (Player player) static
Handles chopping the root.
Definition at line 595 of file Wintertodt.java.
{
        if(!isActive()) {
            player.message("There's no need to do that at this time.");
            return;
        }
        AxeData axeData = AxeData.getDefinition(player).orElse(null);
        if(axeData == null) {
            player.message("You do not have an axe which you have the woodcutting level to use.");
            return;
        }
        if(player.inventory.getFreeSlots() <= 0) {
            player.message("You have no space for that.");
            return;
        }
        player.action.execute(new ChopRoots(player));
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.action.ActionManager.execute(), com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.entity.mob.player.Player.inventory, isActive(), and com.runehive.game.world.entity.mob.player.Player.message().
dealDamage()
void com.runehive.content.wintertodt.Wintertodt.dealDamage () static private
Handles dealing damage to the boss.
Definition at line 474 of file Wintertodt.java.
{
        int damage = 0;
        for (Brazier brazier : BRAZIERS) {
            if (brazier.isPyromancerAlive() && brazier.getObject().getId() == BURNING_BRAZIER_ID) {
                shootFlame(brazier);
                damage += 5;
            }
        }
        if (damage > 0) {
            health -= damage;
            if (health <= 0) {
                health = 0;
                death();
            }
        } else
            health = Math.min(MAX_HP, health + 5);
    }
References BRAZIERS, BURNING_BRAZIER_ID, death(), health, MAX_HP, and shootFlame().
Referenced by init().
death()
void com.runehive.content.wintertodt.Wintertodt.death () static private
Handles the death of the boss.
Definition at line 506 of file Wintertodt.java.
{
        started = false;
        startDelay = DEFAULT_DELAY;
        WINTERTODT.transform(INACTIVE_STORM_ID);
        for (Brazier brazier : BRAZIERS) {
            brazier.getPyromancer().speak("We can rest for a time.");
            brazier.getPyromancer().transform(PYROMANCER);
            brazier.getPyromancer().pyroSnowAttack = false;
            brazier.getPyromancer().pyroHealth = 24;
            brazier.getPyromancer().animate(65535);
            //brazier.getObject().transform(EMPTY_BRAZIER_ID);
            brazier.getObject().unregister();
            brazier.setObject(EMPTY_BRAZIER_ID);
            brazier.getObject().register();
        }
        region.getPlayers(0).forEach(Wintertodt::award);
    }
References award(), BRAZIERS, DEFAULT_DELAY, EMPTY_BRAZIER_ID, INACTIVE_STORM_ID, PYROMANCER, region, startDelay, started, and WINTERTODT.
Referenced by dealDamage().
doMagicAttack()
void com.runehive.content.wintertodt.Wintertodt.doMagicAttack () static private
Handles doing the magic attack by the bnoss.
Definition at line 345 of file Wintertodt.java.
{
        if(Utility.random(25) != 1 || region.getPlayers(0).size() == 0) return;
        Player player = region.getPlayers(0).toArray(new Player[0])[Utility.random(region.getPlayers(0).size())];
        if (player.getPosition().getY() <= 3987) return;
        int baseX = player.getPosition().getX();
        int baseY = player.getPosition().getY();
        List<GameObject> snowAttacks = new ArrayList<>();
        snowAttacks.add(new CustomGameObject(SNOW_EFFECT_ID, new Position(baseX, baseY, 0)));
        if(region.getObjects(new Position(baseX + 1, baseY + 1, 0)).size() == 0)
            snowAttacks.add(new CustomGameObject(SNOW_EFFECT_ID, new Position(baseX + 1, baseY + 1, 0)));
        if(region.getObjects(new Position(baseX + 1, baseY - 1, 0)).size() == 0)
            snowAttacks.add(new CustomGameObject(SNOW_EFFECT_ID, new Position(baseX + 1, baseY - 1, 0)));
        if(region.getObjects(new Position(baseX - 1, baseY + 1, 0)).size() == 0)
            snowAttacks.add(new CustomGameObject(SNOW_EFFECT_ID, new Position(baseX - 1, baseY + 1, 0)));
        if(region.getObjects(new Position(baseX - 1, baseY - 1, 0)).size() == 0)
            snowAttacks.add(new CustomGameObject(SNOW_EFFECT_ID, new Position(baseX - 1, baseY - 1, 0)));
        for(GameObject gameObject : snowAttacks)
            gameObject.register();
        World.schedule(new Task(4) {
            int index = 0;
            @Override
            public void execute() {
                for(GameObject gameObject : snowAttacks) {
                    gameObject.transform(index == 0 ? 29325 : 29324);
                    index++;
                }
                region.getPlayers(0).forEach(players -> {
                    if(Utility.goodDistance(baseX, baseY, players.getX(), player.getY(), 1)) {
                        players.message("The freezing cold attack of the Wintertodt's magic hits you.");
                        players.damage(new Hit(1 + (getAreaAttackDamage(players) - 1)));
                    }
                });
                this.cancel();
            }
        });
        World.schedule(new Task(14) {
            @Override
            public void execute() {
                for(GameObject gameObject : snowAttacks) {
                    gameObject.unregister();
                    region.getPlayers(0).forEach(players -> {
                        players.send(new SendRemoveObject(new CustomGameObject(gameObject.getId(), gameObject.getPosition())));
                    });
                }
                this.cancel();
            }
        });
    }
References getAreaAttackDamage(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.entity.Entity.getY(), com.runehive.game.world.position.Position.getY(), com.runehive.util.Utility.goodDistance(), com.runehive.util.Utility.random(), region, com.runehive.game.world.World.schedule(), and SNOW_EFFECT_ID.
Referenced by init().
extinguishBraziers()
void com.runehive.content.wintertodt.Wintertodt.extinguishBraziers () static private
Handles extinguishing the braziers.
Definition at line 266 of file Wintertodt.java.
{
        for (Brazier brazier : BRAZIERS) {
            int roll = Utility.random(health + 1500) / 10;
            if(brazier.getObject().getId() == BURNING_BRAZIER_ID && roll == 10) {
                if(brazier.hasSnowStorm()) continue;
                if(Utility.random(health < (MAX_HP / 2) ? 2 : 3) == 1)
                    breakBrazier(brazier);
                else {
                    //Graphic (502, 115, 0)
                    //brazier.getObject().transform(EMPTY_BRAZIER_ID);
                    brazier.getObject().unregister();
                    brazier.setObject(EMPTY_BRAZIER_ID);
                    brazier.getObject().register();
                }
            }
        }
    }
References BRAZIERS, breakBrazier(), BURNING_BRAZIER_ID, EMPTY_BRAZIER_ID, health, MAX_HP, and com.runehive.util.Utility.random().
Referenced by init().
feedBrazier()
void com.runehive.content.wintertodt.Wintertodt.feedBrazier (Player player, GameObject gameObject) static
Handles feeding the brazier.
Definition at line 619 of file Wintertodt.java.
{
        if(!isActive()) {
            player.message("There's no need to do that at this time.");
            return;
        }
        Brazier brazier = null;
        for(Brazier b : BRAZIERS) {
            if(b.getObject().getId() == gameObject.getId() && b.getObject().getPosition() == gameObject.getPosition()) {
                brazier = b;
                break;
            }
        }
        if(brazier == null) {
            System.out.println("Brazier has not been found...");
            return;
        }
        player.animate(832);
        player.action.execute(new FeedBrazier(player, brazier));
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.animate(), BRAZIERS, com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.object.GameObject.getId(), com.runehive.game.world.object.GameObject.getPosition(), isActive(), and com.runehive.game.world.entity.mob.player.Player.message().
fixBrazier()
void com.runehive.content.wintertodt.Wintertodt.fixBrazier (Player player, GameObject gameObject) static
Handles fixing the brazier.
Definition at line 646 of file Wintertodt.java.
{
        if(!isActive()) {
            player.message("There's no need to do that at this time.");
            return;
        }
        Brazier brazier = null;
        for(Brazier b : BRAZIERS) {
            if(b.getObject().getId() == gameObject.getId() && b.getObject().getPosition() == gameObject.getPosition()) {
                brazier = b;
                break;
            }
        }
        if(brazier == null) {
            System.out.println("Brazier has not been found...");
            return;
        }
        if(!brazier.isPyromancerAlive()) {
            player.message("Heal the Pyromancer before fixing the brazier.");
            return;
        }
        if(!player.inventory.contains(2347)) {
            player.message("You need a hammer to fix this brazier.");
            return;
        }
        player.animate(3676);
        player.action.execute(new FixBrazier(player, brazier));
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.animate(), BRAZIERS, com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.object.GameObject.getId(), com.runehive.game.world.object.GameObject.getPosition(), com.runehive.game.world.entity.mob.player.Player.inventory, isActive(), com.runehive.content.wintertodt.Brazier.isPyromancerAlive(), and com.runehive.game.world.entity.mob.player.Player.message().
fletch()
void com.runehive.content.wintertodt.Wintertodt.fletch (Player player) static
Handles fetching the kindling.
Definition at line 683 of file Wintertodt.java.
{
        if(!isActive()) {
            player.message("There's no need to do that at this time.");
            return;
        }
        if(!player.inventory.contains(BRUMA_ROOT)) return;
        player.animate(1248);
        player.action.execute(new FletchKindling(player, player.inventory.computeAmountForId(BRUMA_ROOT)));
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.animate(), BRUMA_ROOT, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.entity.mob.player.Player.inventory, isActive(), and com.runehive.game.world.entity.mob.player.Player.message().
getAreaAttackDamage()
int com.runehive.content.wintertodt.Wintertodt.getAreaAttackDamage (Player player) static
Handles the formula on how much the area attack can do.
Definition at line 404 of file Wintertodt.java.
{
        return (int) ((10.0 - getWarmItemsWorn(player)) * (Skill.getLevelForExperience(player.skills.get(Skill.HITPOINTS).getExperience()) + 1) / Skill.getLevelForExperience(player.skills.get(Skill.FIREMAKING).getExperience()) * 3);
    }
References com.runehive.game.world.entity.skill.Skill.FIREMAKING, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.Skill.getExperience(), com.runehive.game.world.entity.skill.Skill.getLevelForExperience(), getWarmItemsWorn(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by doMagicAttack().
getBrazierAttackDamage()
int com.runehive.content.wintertodt.Wintertodt.getBrazierAttackDamage (Player player) static
How much damage the brazier does to a player when it breaks.
Definition at line 338 of file Wintertodt.java.
{
        return (int) ((10.0 - getWarmItemsWorn(player)) * (Skill.getLevelForExperience(player.skills.get(Skill.HITPOINTS).getExperience()) + 1) / Skill.getLevelForExperience(player.skills.get(Skill.FIREMAKING).getExperience())) * 2;
    }
References com.runehive.game.world.entity.skill.Skill.FIREMAKING, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.Skill.getExperience(), com.runehive.game.world.entity.skill.Skill.getLevelForExperience(), getWarmItemsWorn(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by breakBrazier().
getBraziersLit()
int com.runehive.content.wintertodt.Wintertodt.getBraziersLit () static
How many braziers are currently lit.
Definition at line 584 of file Wintertodt.java.
{
        int count = 0;
        for (Brazier b : BRAZIERS)
            if (b.getObject().getId() == BURNING_BRAZIER_ID)
                count++;
        return Math.min(count, 3);
    }
References BRAZIERS, and BURNING_BRAZIER_ID.
Referenced by getColdDamage().
getColdDamage()
int com.runehive.content.wintertodt.Wintertodt.getColdDamage (Player player) static
The amount of damagae the player gets from cold.
Definition at line 565 of file Wintertodt.java.
{
        return (int) ((16.0 - getWarmItemsWorn(player) - (2 * getBraziersLit())) * (Skill.getLevelForExperience(player.skills.get(Skill.HITPOINTS).getExperience()) + 1) / Skill.getLevelForExperience(player.skills.get(Skill.FIREMAKING).getExperience()));
    }
References com.runehive.game.world.entity.skill.Skill.FIREMAKING, com.runehive.game.world.entity.skill.SkillManager.get(), getBraziersLit(), com.runehive.game.world.entity.skill.Skill.getExperience(), com.runehive.game.world.entity.skill.Skill.getLevelForExperience(), getWarmItemsWorn(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by applyColdDamage().
getWarmItemsWorn()
int com.runehive.content.wintertodt.Wintertodt.getWarmItemsWorn (Player player) static
How much warm clothing the player is wearing.
Definition at line 572 of file Wintertodt.java.
{
        int warmClothing = 0;
        for(int id : WARM_CLOTHING) {
            if(player.equipment.contains(id)) warmClothing++;
            if(warmClothing >= 4) break;
        }
        return warmClothing;
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, and WARM_CLOTHING.
Referenced by getAreaAttackDamage(), getBrazierAttackDamage(), and getColdDamage().
healPyromancer()
void com.runehive.content.wintertodt.Wintertodt.healPyromancer (Player player, Npc npc, int slot) static
Handles healing the pyromancer.
Definition at line 772 of file Wintertodt.java.
{
        if(!isActive()) {
            player.message("There's no need to do that at this time.");
            return;
        }
        Brazier brazier = null;
        for(Brazier b : BRAZIERS) {
            if(b.getPyromancer().getPosition() == npc.getPosition() && b.getPyromancer().id == npc.id) {
                brazier = b;
                break;
            }
        }
        if(brazier == null) {
            System.out.println("Brazier has not been found...");
            return;
        }
        Item itemUsed = player.inventory.get(slot);
        if(itemUsed.getId() != REJUV_POT_4 && itemUsed.getId() != REJUV_POT_3 && itemUsed.getId() != REJUV_POT_2 && itemUsed.getId() != REJUV_POT_1) {
            System.out.println("not a rejuv potion");
            return;
        }
        Item newPot = new Item(player.inventory.getId(slot) + 1);
        if(newPot.getId() > REJUV_POT_1) newPot = null;
        player.inventory.set(slot, newPot, true);
        brazier.getPyromancer().transform(PYROMANCER);
        brazier.getPyromancer().pyroHealth = 24;
        brazier.getPyromancer().pyroSnowAttack = false;
        addPoints(player, 30);
    }
References addPoints(), BRAZIERS, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.containers.ItemContainer.getId(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.content.wintertodt.Brazier.getPyromancer(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.player.Player.inventory, isActive(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.npc.Npc.pyroHealth, PYROMANCER, com.runehive.game.world.entity.mob.npc.Npc.pyroSnowAttack, REJUV_POT_1, REJUV_POT_2, REJUV_POT_3, REJUV_POT_4, com.runehive.game.world.items.containers.ItemContainer.set(), and com.runehive.game.world.entity.mob.Mob.transform().
init()
void com.runehive.content.wintertodt.Wintertodt.init () static
Definition at line 171 of file Wintertodt.java.
{
        region = World.getRegions().getRegion(new Position(1627, 4004, 0));
        pyroSpeechDelay = 8;
        startDelay = DEFAULT_DELAY;
        WINTERTODT = new CustomGameObject(INACTIVE_STORM_ID, new Position(1627, 4004, 0));
        WINTERTODT.register();
        started = false;
        for(Brazier brazier : BRAZIERS)
            brazier.getPyromancer().register();
        World.schedule(new Task(1) {
            @Override
            protected void execute() {
                if(startDelay > 0)
                    startDelay--;
                if(startDelay <= 0 && !started) start();
                update();
            }
        });
        World.schedule(new Task(2) {
            @Override
            protected void execute() {
                if(!isActive()) return;
                pyroSpeechDelay--;
                applyColdDamage();
                extinguishBraziers();
                doMagicAttack();
                attackPyromancers();
                pyromancerText();
                dealDamage();
            }
        });
    }
References applyColdDamage(), attackPyromancers(), BRAZIERS, dealDamage(), DEFAULT_DELAY, doMagicAttack(), extinguishBraziers(), com.runehive.game.world.region.RegionManager.getRegion(), com.runehive.game.world.World.getRegions(), INACTIVE_STORM_ID, isActive(), pyromancerText(), pyroSpeechDelay, region, com.runehive.game.world.World.schedule(), start(), startDelay, started, update(), and WINTERTODT.
Referenced by com.runehive.RuneHive.processSequentialStartupTasks().
isActive()
boolean com.runehive.content.wintertodt.Wintertodt.isActive () static
Definition at line 167 of file Wintertodt.java.
{
        return startDelay <= 0;
    }
References startDelay.
Referenced by breakBrazier(), chopRoot(), feedBrazier(), fixBrazier(), fletch(), healPyromancer(), init(), lightBrazier(), mixHerb(), send(), and takeHerb().
lightBrazier()
void com.runehive.content.wintertodt.Wintertodt.lightBrazier (Player player, GameObject gameObject) static
Handles lighting a brazier.
Definition at line 698 of file Wintertodt.java.
{
        if(!isActive()) {
            player.message("There's no need to do that at this time.");
            return;
        }
        Brazier brazier = null;
        for(Brazier b : BRAZIERS) {
            if(b.getObject().getId() == gameObject.getId() && b.getObject().getPosition() == gameObject.getPosition()) {
                brazier = b;
                break;
            }
        }
        if(brazier == null) {
            System.out.println("Brazier has not been found...");
            return;
        }
        if(!brazier.isPyromancerAlive()) {
            player.message("Heal the Pyromancer before lighting the brazier.");
            return;
        }
        if(!player.inventory.contains(590) && !player.equipment.contains(20720)) {
            player.message("You need a tinderbox or Bruma Torch to light that brazier.");
            return;
        }
        player.animate(733);
        player.action.execute(new LightBrazier(player, brazier));
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.animate(), BRAZIERS, com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.object.GameObject.getId(), com.runehive.game.world.object.GameObject.getPosition(), com.runehive.game.world.entity.mob.player.Player.inventory, isActive(), com.runehive.content.wintertodt.Brazier.isPyromancerAlive(), and com.runehive.game.world.entity.mob.player.Player.message().
mixHerb()
void com.runehive.content.wintertodt.Wintertodt.mixHerb (Player player) static
Handles mixing the potion.
Definition at line 735 of file Wintertodt.java.
{
        if(!isActive()) {
            player.message("There's no need to do that at this time.");
            return;
        }
        int herbs = player.inventory.computeAmountForId(BRUMA_HERB);
        int pots = player.inventory.computeAmountForId(REJUV_POT_UNF);
        int min = Utility.min(herbs, pots);
        if(min == 0) return;
        player.animate(363);
        player.action.execute(new MixHerb(player, min));
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.animate(), BRUMA_HERB, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.entity.mob.player.Player.inventory, isActive(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.util.Utility.min(), and REJUV_POT_UNF.
pyromancerText()
void com.runehive.content.wintertodt.Wintertodt.pyromancerText () static private
Handles the pyromancer speech.
Definition at line 452 of file Wintertodt.java.
{
        if(pyroSpeechDelay <= 0) {
            pyroSpeechDelay = 8;
            for (Brazier brazier : BRAZIERS) {
                if (!brazier.isPyromancerAlive())
                    brazier.getPyromancer().speak(PYROMANCER_DEAD_TEXT[Utility.random(PYROMANCER_DEAD_TEXT.length - 1)]);
                else if (brazier.getObject().getId() == EMPTY_BRAZIER_ID)
                    brazier.getPyromancer().speak("Light this brazier!");
                else if (brazier.getObject().getId() == BROKEN_BRAZIER_ID)
                    brazier.getPyromancer().speak("Fix this brazier!");
                else if (Utility.random(4) == 1)
                    brazier.getPyromancer().speak("Yemalo shi cardito!");
                if (brazier.isPyromancerAlive() && brazier.getObject().getId() == BURNING_BRAZIER_ID && Utility.random(3) == 1)
                    brazier.getPyromancer().animate(4432);
            }
        }
    }
References BRAZIERS, BROKEN_BRAZIER_ID, BURNING_BRAZIER_ID, EMPTY_BRAZIER_ID, PYROMANCER_DEAD_TEXT, pyroSpeechDelay, and com.runehive.util.Utility.random().
Referenced by init().
removeGameItems()
void com.runehive.content.wintertodt.Wintertodt.removeGameItems (Player player) static
Handles removes the items within the wintertodt game.
Definition at line 551 of file Wintertodt.java.
{
        int slot = 0;
        for (Item item : player.inventory.getItems()) {
            if (item != null && GAME_ITEMS.contains(item.getId())) {
                player.inventory.set(slot, null, false);
            }
            slot++;
        }
        player.inventory.refresh();
    }
References GAME_ITEMS, com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.inventory.Inventory.refresh(), and com.runehive.game.world.items.containers.ItemContainer.set().
Referenced by award().
send()
void com.runehive.content.wintertodt.Wintertodt.send (Player player) static
Definition at line 231 of file Wintertodt.java.
{
        player.send(new SendString("Wintertodt's Energy: "+(health / (MAX_HP / 100))+"%", 41553));
        player.send(new SendString(isActive() ? "" : "The Wintertodt returns in: " + ((startDelay * 600) / 1000) + " secs", 41554));
        player.send(new SendString("<col="+(player.wintertodtPoints >= 500 ? "FFFFFF" : "FF0000")+">Points\\n" + player.wintertodtPoints, 41556));
        //Sends the pyromancer config stuff
        player.send(new SendConfig(2224, BRAZIERS[0].isPyromancerAlive() ? 0 : 1));
        player.send(new SendConfig(2222, BRAZIERS[1].isPyromancerAlive() ? 0 : 1));
        player.send(new SendConfig(2223, BRAZIERS[2].isPyromancerAlive() ? 0 : 1));
        player.send(new SendConfig(2225, BRAZIERS[3].isPyromancerAlive() ? 0 : 1));
        //Sends the brazier config stuff
        player.send(new SendConfig(2228, BRAZIERS[0].getBrazierState()));
        player.send(new SendConfig(2226, BRAZIERS[1].getBrazierState()));
        player.send(new SendConfig(2227, BRAZIERS[2].getBrazierState()));
        player.send(new SendConfig(2229, BRAZIERS[3].getBrazierState()));
        if (player.interfaceManager.getWalkable() != 41550)
            player.interfaceManager.openWalkable(41550);
    }
References BRAZIERS, com.runehive.game.world.entity.mob.player.InterfaceManager.getWalkable(), health, com.runehive.game.world.entity.mob.player.Player.interfaceManager, isActive(), MAX_HP, com.runehive.game.world.entity.mob.player.InterfaceManager.openWalkable(), com.runehive.game.world.entity.mob.player.Player.send(), startDelay, and com.runehive.game.world.entity.mob.player.Player.wintertodtPoints.
Referenced by addPoints(), and update().
shootFlame()
void com.runehive.content.wintertodt.Wintertodt.shootFlame (Brazier brazier) static
Handles spawning the flame that goes to the middle.
Definition at line 496 of file Wintertodt.java.
{
        Npc flame = new Npc(FLAME, new Position(brazier.getObject().getPosition().getX() + brazier.getFlameOffsetX(), brazier.getObject().getPosition().getY() + brazier.getFlameOffsetY(), brazier.getObject().getPosition().getHeight()), 0, brazier.direction);
        flame.movement.simplePath(new Position(1630, 4007));
        flame.register();
        flame.action.execute(new FlameWalk(flame));
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.content.wintertodt.Brazier.direction, com.runehive.game.action.ActionManager.execute(), FLAME, com.runehive.content.wintertodt.Brazier.getFlameOffsetX(), com.runehive.content.wintertodt.Brazier.getFlameOffsetY(), com.runehive.game.world.position.Position.getHeight(), com.runehive.content.wintertodt.Brazier.getObject(), com.runehive.game.world.object.GameObject.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.Mob.movement, com.runehive.game.world.entity.mob.npc.Npc.register(), and com.runehive.game.world.entity.mob.movement.Movement.simplePath().
Referenced by dealDamage().
start()
void com.runehive.content.wintertodt.Wintertodt.start () static private
Definition at line 210 of file Wintertodt.java.
{
        WINTERTODT.transform(ACTIVE_STORM_ID);
        for (Brazier brazier : BRAZIERS) {
            //brazier.getObject().transform(EMPTY_BRAZIER_ID);
            brazier.getObject().unregister();
            brazier.setObject(EMPTY_BRAZIER_ID);
            brazier.getObject().register();
            if (!brazier.isPyromancerAlive())
                brazier.getPyromancer().transform(PYROMANCER);
        }
        health = MAX_HP;
        started = true;
        update();
    }
References ACTIVE_STORM_ID, BRAZIERS, EMPTY_BRAZIER_ID, health, MAX_HP, PYROMANCER, started, update(), and WINTERTODT.
Referenced by init().
takeHerb()
void com.runehive.content.wintertodt.Wintertodt.takeHerb (Player player) static
Handles taking a bruma herb.
Definition at line 754 of file Wintertodt.java.
{
        if(!isActive()) {
            player.message("There's no need to do that at this time.");
            return;
        }
        if(player.inventory.getFreeSlots() <= 0) {
            player.message("You have no space for that.");
            return;
        }
        player.animate(2282);
        player.action.execute(new PickHerb(player));
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.entity.mob.player.Player.inventory, isActive(), and com.runehive.game.world.entity.mob.player.Player.message().
update()
void com.runehive.content.wintertodt.Wintertodt.update () static private
Definition at line 227 of file Wintertodt.java.
{
        region.getPlayers(0).forEach(Wintertodt::send);
    }
References region, and send().
Referenced by init(), and start().
Member Data Documentation
ACTIVE_STORM_ID
final int com.runehive.content.wintertodt.Wintertodt.ACTIVE_STORM_ID = 29308 static private
Definition at line 75 of file Wintertodt.java.
Referenced by start().
BRAZIERS
final Brazier [] com.runehive.content.wintertodt.Wintertodt.BRAZIERS static
Initial value:
= {
            new Brazier(World.getRegions().getRegion(new Position(1620, 3997, 0)).getGameObject(29312, new Position(1620, 3997, 0)), new Npc(7371, new Position(1619, 3996, 0), 0, Direction.NORTH_EAST), 2, 2, Direction.NORTH_EAST),
            new Brazier(World.getRegions().getRegion(new Position(1620, 4015, 0)).getGameObject(29312, new Position(1620, 4015, 0)), new Npc(7371, new Position(1619, 4018, 0), 0, Direction.SOUTH_EAST), 2, 0, Direction.SOUTH_EAST),
            new Brazier(World.getRegions().getRegion(new Position(1638, 4015, 0)).getGameObject(29312, new Position(1638, 4015, 0)), new Npc(7371, new Position(1641, 4018, 0), 0, Direction.SOUTH_WEST), 0, 0, Direction.SOUTH_WEST),
            new Brazier(World.getRegions().getRegion(new Position(1638, 3997, 0)).getGameObject(29312, new Position(1638, 3997, 0)), new Npc(7371, new Position(1641, 3996, 0), 0, Direction.NORTH_WEST), 0, 2, Direction.NORTH_WEST)
    }
Brazier data.
Definition at line 160 of file Wintertodt.java.
{
            new Brazier(World.getRegions().getRegion(new Position(1620, 3997, 0)).getGameObject(29312, new Position(1620, 3997, 0)), new Npc(7371, new Position(1619, 3996, 0), 0, Direction.NORTH_EAST), 2, 2, Direction.NORTH_EAST), // sw
            new Brazier(World.getRegions().getRegion(new Position(1620, 4015, 0)).getGameObject(29312, new Position(1620, 4015, 0)), new Npc(7371, new Position(1619, 4018, 0), 0, Direction.SOUTH_EAST), 2, 0, Direction.SOUTH_EAST), // nw
            new Brazier(World.getRegions().getRegion(new Position(1638, 4015, 0)).getGameObject(29312, new Position(1638, 4015, 0)), new Npc(7371, new Position(1641, 4018, 0), 0, Direction.SOUTH_WEST), 0, 0, Direction.SOUTH_WEST), // ne
            new Brazier(World.getRegions().getRegion(new Position(1638, 3997, 0)).getGameObject(29312, new Position(1638, 3997, 0)), new Npc(7371, new Position(1641, 3996, 0), 0, Direction.NORTH_WEST), 0, 2, Direction.NORTH_WEST) // se
    };
Referenced by attackPyromancers(), dealDamage(), death(), extinguishBraziers(), feedBrazier(), fixBrazier(), getBraziersLit(), healPyromancer(), init(), lightBrazier(), pyromancerText(), send(), and start().
BROKEN_BRAZIER_ID
final int com.runehive.content.wintertodt.Wintertodt.BROKEN_BRAZIER_ID = 29313 static
Definition at line 78 of file Wintertodt.java.
Referenced by breakBrazier(), and pyromancerText().
BRUMA_HERB
final int com.runehive.content.wintertodt.Wintertodt.BRUMA_HERB = 20698 static
Definition at line 60 of file Wintertodt.java.
Referenced by com.runehive.content.wintertodt.actions.MixHerb.execute(), com.runehive.content.wintertodt.actions.PickHerb.execute(), and mixHerb().
BRUMA_KINDLING
final int com.runehive.content.wintertodt.Wintertodt.BRUMA_KINDLING = 20696 static
Definition at line 54 of file Wintertodt.java.
Referenced by com.runehive.content.wintertodt.actions.FeedBrazier.execute(), and com.runehive.content.wintertodt.actions.FletchKindling.execute().
BRUMA_ROOT
final int com.runehive.content.wintertodt.Wintertodt.BRUMA_ROOT = 20695 static
Item ids.
Definition at line 53 of file Wintertodt.java.
Referenced by com.runehive.content.wintertodt.actions.ChopRoots.execute(), com.runehive.content.wintertodt.actions.FeedBrazier.execute(), com.runehive.content.wintertodt.actions.FletchKindling.execute(), and fletch().
BURNING_BRAZIER_ID
final int com.runehive.content.wintertodt.Wintertodt.BURNING_BRAZIER_ID = 29314 static
Definition at line 79 of file Wintertodt.java.
Referenced by dealDamage(), com.runehive.content.wintertodt.actions.FeedBrazier.execute(), com.runehive.content.wintertodt.actions.LightBrazier.execute(), extinguishBraziers(), getBraziersLit(), com.runehive.content.wintertodt.Brazier.getBrazierState(), and pyromancerText().
DEFAULT_DELAY
final int com.runehive.content.wintertodt.Wintertodt.DEFAULT_DELAY = 10 static private
Definition at line 33 of file Wintertodt.java.
Referenced by death(), and init().
EMPTY_BRAZIER_ID
final int com.runehive.content.wintertodt.Wintertodt.EMPTY_BRAZIER_ID = 29312 static
Definition at line 77 of file Wintertodt.java.
Referenced by death(), com.runehive.content.wintertodt.actions.FixBrazier.execute(), extinguishBraziers(), com.runehive.content.wintertodt.Brazier.getBrazierState(), pyromancerText(), and start().
FLAME
final int com.runehive.content.wintertodt.Wintertodt.FLAME = 7373 static private
Definition at line 69 of file Wintertodt.java.
Referenced by shootFlame().
GAME_ITEMS
final List<Integer> com.runehive.content.wintertodt.Wintertodt.GAME_ITEMS = Arrays.asList(BRUMA_ROOT, BRUMA_KINDLING, BRUMA_HERB, REJUV_POT_UNF, REJUV_POT_4, REJUV_POT_3, REJUV_POT_2, REJUV_POT_1) static private
List of all minigame items.
Definition at line 85 of file Wintertodt.java.
Referenced by removeGameItems().
health
int com.runehive.content.wintertodt.Wintertodt.health = 0 static
Definition at line 45 of file Wintertodt.java.
Referenced by dealDamage(), extinguishBraziers(), send(), and start().
INACTIVE_STORM_ID
final int com.runehive.content.wintertodt.Wintertodt.INACTIVE_STORM_ID = 29309 static private
Definition at line 76 of file Wintertodt.java.
Referenced by death(), and init().
INCAPACITATED_PYROMANCER
final int com.runehive.content.wintertodt.Wintertodt.INCAPACITATED_PYROMANCER = 7372 static
Definition at line 68 of file Wintertodt.java.
Referenced by attackPyromancers(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), and com.runehive.game.world.entity.mob.Mob.getMaximumHealth().
MAX_HP
final int com.runehive.content.wintertodt.Wintertodt.MAX_HP = 3500 static
Definition at line 44 of file Wintertodt.java.
Referenced by dealDamage(), extinguishBraziers(), send(), and start().
PYROMANCER
final int com.runehive.content.wintertodt.Wintertodt.PYROMANCER = 7371 static
Definition at line 67 of file Wintertodt.java.
Referenced by death(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), healPyromancer(), com.runehive.content.wintertodt.Brazier.isPyromancerAlive(), and start().
PYROMANCER_DEAD_TEXT
final String [] com.runehive.content.wintertodt.Wintertodt.PYROMANCER_DEAD_TEXT = {"My flame burns low.", "Mummy!", "I think I'm dying.", "We are doomed.", "Ugh, help me!"} static private
Npc ids.
Definition at line 65 of file Wintertodt.java.
{"My flame burns low.", "Mummy!", "I think I'm dying.", "We are doomed.", "Ugh, help me!"};
Referenced by pyromancerText().
pyroSpeechDelay
int com.runehive.content.wintertodt.Wintertodt.pyroSpeechDelay static private
Definition at line 47 of file Wintertodt.java.
Referenced by init(), and pyromancerText().
region
Region com.runehive.content.wintertodt.Wintertodt.region static
Definition at line 48 of file Wintertodt.java.
Referenced by applyColdDamage(), attackPyromancers(), breakBrazier(), death(), doMagicAttack(), init(), and update().
REGION_ID
final int com.runehive.content.wintertodt.Wintertodt.REGION_ID = 6462 static
Region of the wintertodt game.
Definition at line 38 of file Wintertodt.java.
REJUV_POT_1
final int com.runehive.content.wintertodt.Wintertodt.REJUV_POT_1 = 20702 static
Definition at line 59 of file Wintertodt.java.
Referenced by healPyromancer().
REJUV_POT_2
final int com.runehive.content.wintertodt.Wintertodt.REJUV_POT_2 = 20701 static
Definition at line 58 of file Wintertodt.java.
Referenced by healPyromancer().
REJUV_POT_3
final int com.runehive.content.wintertodt.Wintertodt.REJUV_POT_3 = 20700 static
Definition at line 57 of file Wintertodt.java.
Referenced by healPyromancer().
REJUV_POT_4
final int com.runehive.content.wintertodt.Wintertodt.REJUV_POT_4 = 20699 static
Definition at line 56 of file Wintertodt.java.
Referenced by com.runehive.content.wintertodt.actions.MixHerb.execute(), and healPyromancer().
REJUV_POT_UNF
final int com.runehive.content.wintertodt.Wintertodt.REJUV_POT_UNF = 20697 static
Definition at line 55 of file Wintertodt.java.
Referenced by com.runehive.content.wintertodt.actions.MixHerb.execute(), and mixHerb().
SNOW_EFFECT_ID
final int com.runehive.content.wintertodt.Wintertodt.SNOW_EFFECT_ID = 26690 static private
Game object ids.
Definition at line 74 of file Wintertodt.java.
Referenced by attackPyromancers(), breakBrazier(), and doMagicAttack().
startDelay
int com.runehive.content.wintertodt.Wintertodt.startDelay = DEFAULT_DELAY static private
Definition at line 46 of file Wintertodt.java.
Referenced by death(), init(), isActive(), and send().
started
boolean com.runehive.content.wintertodt.Wintertodt.started = false static private
Game data.
Definition at line 43 of file Wintertodt.java.
Referenced by death(), init(), and start().
WARM_CLOTHING
final List<Integer> com.runehive.content.wintertodt.Wintertodt.WARM_CLOTHING static private
List of all warm clothing.
Definition at line 91 of file Wintertodt.java.
Referenced by getWarmItemsWorn().
WINTERTODT
CustomGameObject com.runehive.content.wintertodt.Wintertodt.WINTERTODT static private
Definition at line 80 of file Wintertodt.java.
Referenced by death(), init(), and start().
The documentation for this class was generated from the following file:
java/com/runehive/content/wintertodt/Wintertodt.java