RuneHive-Game: com.runehive.content.tradingpost.TradingPostListing Class Reference
com.runehive.content.tradingpost.TradingPostListing Class Reference
Public Member Functions
void addQuantity (Player player, int amount)
void addToAmountSold (int amountSold)
void checkAndUpdate (Player player)
int getAmountLeft ()
int getAmountSold ()
int getInitialQuantity ()
int getItemId ()
int getPrice ()
String getSeller ()
void removeQuantity (Player player, int amount)
void setAmountSold (int amountSold)
void setInitialQuantity (int initialQuantity)
void setPrice (int price)
void setPrice (Player player, int price)
void setQuantity (Player player, int quantity)
TradingPostListing (int itemId, String seller)
Private Attributes
int amountSold = 0
int initialQuantity = 1
final int itemId
int price
final String seller
Detailed Description
Definition at line 6 of file TradingPostListing.java.
Constructor & Destructor Documentation
TradingPostListing()
com.runehive.content.tradingpost.TradingPostListing.TradingPostListing (int itemId, String seller)
Definition at line 13 of file TradingPostListing.java.
{
        this.itemId = itemId;
        this.seller = seller;
    }
References itemId, and seller.
Member Function Documentation
addQuantity()
void com.runehive.content.tradingpost.TradingPostListing.addQuantity (Player player, int amount)
Definition at line 60 of file TradingPostListing.java.
{
        initialQuantity += amount;
        checkAndUpdate(player);
    }
References checkAndUpdate(), and initialQuantity.
addToAmountSold()
void com.runehive.content.tradingpost.TradingPostListing.addToAmountSold (int amountSold)
Definition at line 82 of file TradingPostListing.java.
{
        this.amountSold += amountSold;
    }
References amountSold.
checkAndUpdate()
void com.runehive.content.tradingpost.TradingPostListing.checkAndUpdate (Player player)
Definition at line 65 of file TradingPostListing.java.
{
        int playerAmount = player.inventory.computeAmountForId(itemId);
        if (initialQuantity > playerAmount) {
            initialQuantity = playerAmount;
        }
        player.tradingPost.updateQuantityString();
        player.tradingPost.updatePriceStrings();
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), initialQuantity, com.runehive.game.world.entity.mob.player.Player.inventory, itemId, com.runehive.game.world.entity.mob.player.Player.tradingPost, com.runehive.content.tradingpost.TradingPost.updatePriceStrings(), and com.runehive.content.tradingpost.TradingPost.updateQuantityString().
Referenced by addQuantity(), and setQuantity().
getAmountLeft()
int com.runehive.content.tradingpost.TradingPostListing.getAmountLeft ()
Definition at line 74 of file TradingPostListing.java.
{
        return initialQuantity - amountSold;
    }
References amountSold, and initialQuantity.
Referenced by com.runehive.content.tradingpost.TradingPost.handleDismissListingButton(), com.runehive.content.tradingpost.TradingPost.sort(), and com.runehive.content.tradingpost.TradingPost.updateBuyingPageWidgets().
getAmountSold()
int com.runehive.content.tradingpost.TradingPostListing.getAmountSold ()
Definition at line 78 of file TradingPostListing.java.
{
        return amountSold;
    }
References amountSold.
Referenced by com.runehive.content.tradingpost.TradingPost.updateExistingListingsWidgets().
getInitialQuantity()
int com.runehive.content.tradingpost.TradingPostListing.getInitialQuantity ()
Definition at line 22 of file TradingPostListing.java.
{
        return initialQuantity;
    }
References initialQuantity.
Referenced by com.runehive.content.tradingpost.TradingPost.updateExistingListingsWidgets().
getItemId()
int com.runehive.content.tradingpost.TradingPostListing.getItemId ()
Definition at line 18 of file TradingPostListing.java.
{
        return itemId;
    }
References itemId.
Referenced by com.runehive.content.tradingpost.TradingPost.handleDismissListingButton(), and com.runehive.content.tradingpost.TradingPost.updateBuyingPageWidgets().
getPrice()
int com.runehive.content.tradingpost.TradingPostListing.getPrice ()
Definition at line 34 of file TradingPostListing.java.
{
        return price;
    }
References price.
Referenced by com.runehive.content.tradingpost.TradingPost.sort(), and com.runehive.content.tradingpost.TradingPost.updateBuyingPageWidgets().
getSeller()
String com.runehive.content.tradingpost.TradingPostListing.getSeller ()
Definition at line 47 of file TradingPostListing.java.
{
        return seller;
    }
References seller.
Referenced by com.runehive.content.tradingpost.TradingPost.updateBuyingPageWidgets().
removeQuantity()
void com.runehive.content.tradingpost.TradingPostListing.removeQuantity (Player player, int amount)
Definition at line 51 of file TradingPostListing.java.
{
        initialQuantity -= amount;
        if (initialQuantity <= 0) {
            initialQuantity = 1;
        }
        player.tradingPost.updateQuantityString();
        player.tradingPost.updatePriceStrings();
    }
References initialQuantity, com.runehive.game.world.entity.mob.player.Player.tradingPost, com.runehive.content.tradingpost.TradingPost.updatePriceStrings(), and com.runehive.content.tradingpost.TradingPost.updateQuantityString().
setAmountSold()
void com.runehive.content.tradingpost.TradingPostListing.setAmountSold (int amountSold)
Definition at line 86 of file TradingPostListing.java.
{
        this.amountSold = amountSold;
    }
References amountSold.
setInitialQuantity()
void com.runehive.content.tradingpost.TradingPostListing.setInitialQuantity (int initialQuantity)
Definition at line 94 of file TradingPostListing.java.
{
        this.initialQuantity = initialQuantity;
    }
References initialQuantity.
Referenced by com.runehive.content.tradingpost.TradingPost.testData().
setPrice() [1/2]
void com.runehive.content.tradingpost.TradingPostListing.setPrice (int price)
Definition at line 90 of file TradingPostListing.java.
{
        this.price = price;
    }
References price.
setPrice() [2/2]
void com.runehive.content.tradingpost.TradingPostListing.setPrice (Player player, int price)
Definition at line 38 of file TradingPostListing.java.
{
        if ((long) price * initialQuantity > Integer.MAX_VALUE) {
            player.send(new SendMessage("Unable to set this price to this quantity. reason: above max integer value."));
            return;
        }
        this.price = price;
        player.tradingPost.updatePriceStrings();
    }
References initialQuantity, price, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.Player.tradingPost, and com.runehive.content.tradingpost.TradingPost.updatePriceStrings().
Referenced by com.runehive.content.tradingpost.TradingPost.testData().
setQuantity()
void com.runehive.content.tradingpost.TradingPostListing.setQuantity (Player player, int quantity)
Definition at line 26 of file TradingPostListing.java.
{
        this.initialQuantity = quantity;
        if (this.initialQuantity == 0) {
            this.initialQuantity = 1;
        }
        checkAndUpdate(player);
    }
References checkAndUpdate().
Member Data Documentation
amountSold
int com.runehive.content.tradingpost.TradingPostListing.amountSold = 0 private
Definition at line 9 of file TradingPostListing.java.
Referenced by addToAmountSold(), getAmountLeft(), getAmountSold(), and setAmountSold().
initialQuantity
int com.runehive.content.tradingpost.TradingPostListing.initialQuantity = 1 private
Definition at line 11 of file TradingPostListing.java.
Referenced by addQuantity(), checkAndUpdate(), getAmountLeft(), getInitialQuantity(), removeQuantity(), setInitialQuantity(), and setPrice().
itemId
final int com.runehive.content.tradingpost.TradingPostListing.itemId private
Definition at line 7 of file TradingPostListing.java.
Referenced by checkAndUpdate(), getItemId(), and TradingPostListing().
price
int com.runehive.content.tradingpost.TradingPostListing.price private
Definition at line 10 of file TradingPostListing.java.
Referenced by getPrice(), setPrice(), and setPrice().
seller
final String com.runehive.content.tradingpost.TradingPostListing.seller private
Definition at line 8 of file TradingPostListing.java.
Referenced by getSeller(), and TradingPostListing().
The documentation for this class was generated from the following file:
java/com/runehive/content/tradingpost/TradingPostListing.java