RuneHive-Game: com.runehive.game.world.entity.mob.npc.definition.NpcDefinition Class Reference
com.runehive.game.world.entity.mob.npc.definition.NpcDefinition Class Reference
Contains the npc definitions.
Classes
class CombatAttackData
Public Member Functions
boolean equals (Object obj)
int getAttackAnim ()
int getAttackAnimation ()
int getAttackDelay ()
int getAttackRadius ()
int getBlockAnim ()
int getBlockAnimation ()
int[] getBonuses ()
Optional< CombatAttackData > getCombatAttackData ()
int getCombatLevel ()
int getDeathAnim ()
int getDeathAnimation ()
int getDeathTimer ()
int getId ()
String getName ()
Player getPlayer ()
int getRespawnTime ()
int getSize ()
int[] getSkills ()
int getStand ()
int getTurn180 ()
int getTurn90CCW ()
int getTurn90CW ()
int getWalk ()
int hashCode ()
boolean hasPoisonImmunity ()
boolean hasVenomImmunity ()
boolean isAggressive ()
boolean isAttackable ()
boolean isFlying ()
boolean isPoisonImmunity ()
boolean isPoisonous ()
boolean isRetaliate ()
boolean isVenomImmunity ()
NpcDefinition (int id, String name)
void setAggressive (boolean aggressive)
void setAttackable (boolean attackable)
void setAttackAnim (int attackAnim)
void setAttackDelay (int attackDelay)
void setAttackRadius (int attackRadius)
void setBlockAnim (int blockAnim)
void setBonuses (int[] bonuses)
void setCombatAttackData (CombatAttackData combatAttackData)
void setCombatLevel (int combatLevel)
void setDeathAnim (int deathAnim)
void setDeathTimer (int deathTimer)
void setFlying (boolean flying)
void setPlayer (Player player)
void setPoisonImmunity (boolean poisonImmunity)
void setPoisonous (boolean poisonous)
void setRespawnTime (int respawnTime)
void setRetaliate (boolean retaliate)
void setSize (int size)
void setSkills (int[] skills)
void setStand (int stand)
void setTurn180 (int turn180)
void setTurn90CCW (int turn90CCW)
void setTurn90CW (int turn90CW)
void setVenomImmunity (boolean venomImmunity)
void setWalk (int walk)
Static Public Member Functions
static GsonParser createParser ()
static NpcDefinition get (int id)
Gets a npc definition from the definition array.
static NpcDefinition get (String name)
static String getCombatLevelRange (String name)
static void main (String[] args)
Static Public Attributes
static final NpcDefinition[] DEFINITIONS = new NpcDefinition[Config.NPC_DEFINITION_LIMIT + 1]
The array of npc definitions.
Private Attributes
boolean aggressive
boolean attackable
int attackAnim
int attackDelay
int attackRadius
int blockAnim
int[] bonuses
CombatAttackData combatAttackData
int combatLevel
int deathAnim
int deathTimer
boolean flying
final int id
final String name
Player player
boolean poisonImmunity
boolean poisonous
int respawnTime
boolean retaliate
int size
int[] skills
int stand
int turn180
int turn90CCW
int turn90CW
boolean venomImmunity
int walk
Detailed Description
Contains the npc definitions.
Author
Michael | Chex
Definition at line 22 of file NpcDefinition.java.
Constructor & Destructor Documentation
NpcDefinition()
com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.NpcDefinition (int id, String name)
Definition at line 55 of file NpcDefinition.java.
{
        this.id = id;
        this.name = name;
        this.combatLevel = 0;
        this.size = 1;
        this.stand = -1;
        this.walk = -1;
        this.turn180 = -1;
        this.turn90CW = -1;
        this.turn90CCW = -1;
        this.attackAnim = -1;
        this.blockAnim = -1;
        this.deathAnim = -1;
        this.deathTimer = 3;
        this.flying = false;
        this.attackable = false;
        this.aggressive = false;
        this.retaliate = false;
        this.poisonous = false;
        this.poisonImmunity = false;
        this.venomImmunity = false;
        this.skills = EMPTY_SKILLS;
        this.bonuses = EMPTY_BONUSES;
        this.attackDelay = 4;
        this.attackRadius = 1;
        this.respawnTime = 30;
    }
References id, and name.
Referenced by createParser(), equals(), get(), get(), and getCombatLevelRange().
Member Function Documentation
createParser()
GsonParser com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.createParser () static
Definition at line 88 of file NpcDefinition.java.
{
        return new GsonParser("def/npc/npc_definitions", false) {
            @Override
            protected void parse(JsonObject data) {
                int id = data.get("id").getAsInt();
                boolean convertId = true;
                if (data.has("convert-id")) {
                    convertId = data.get("convert-id").getAsBoolean();
                }
                if (convertId) {
                    int newId = OldToNew.get(id);
                    if (newId != -1) {
                        id = newId;
                    }
                }
                final CacheNpcDefinition cacheDef = CacheNpcDefinition.lookup(id);
                final String cacheDefName = cacheDef.name;
                final NpcDefinition definition = new NpcDefinition(id, cacheDefName == null ? "" : cacheDefName);
                definition.size = cacheDef.size;
                definition.combatLevel = cacheDef.combatLevel;
                definition.stand = cacheDef.standingAnimation;
                definition.walk = cacheDef.walkingAnimation;
                definition.turn180 = cacheDef.halfTurnAnimation;
                definition.turn90CW = cacheDef.quarterClockwiseTurnAnimation;
                definition.turn90CCW = cacheDef.quarterAnticlockwiseTurnAnimation;
                definition.deathTimer = 3;
                if (data.has("death-timer")) {
                    definition.deathTimer = data.get("death-timer").getAsInt();
                }
                if (data.has("attack-animation")) {
                    definition.attackAnim = data.get("attack-animation").getAsInt();
                }
                if (data.has("block-animation")) {
                    definition.blockAnim = data.get("block-animation").getAsInt();
                }
                if (data.has("death-animation")) {
                    definition.deathAnim = data.get("death-animation").getAsInt();
                }
                if (data.has("attackable")) {
                    definition.attackable = data.get("attackable").getAsBoolean();
                }
                if (data.has("aggressive")) {
                    definition.aggressive = data.get("aggressive").getAsBoolean();
                }
                definition.retaliate = definition.isAttackable();
                if (data.has("retaliate")) {
                    definition.retaliate = data.get("retaliate").getAsBoolean();
                }
                if (data.has("poisonous")) {
                    definition.poisonous = data.get("poisonous").getAsBoolean();
                }
                if (data.has("flying")) {
                    definition.flying = data.get("flying").getAsBoolean();
                }
                if (data.has("poison-immunity")) {
                    definition.poisonImmunity = data.get("poison-immunity").getAsBoolean();
                }
                if (data.has("venom-immunity")) {
                    definition.venomImmunity = data.get("venom-immunity").getAsBoolean();
                }
                if (data.has("attack-cooldown")) {
                    definition.attackDelay = data.get("attack-cooldown").getAsInt();
                }
                if (data.has("attack-radius")) {
                    definition.attackRadius = data.get("attack-radius").getAsInt();
                }
                if (data.has("combat-type") && data.has("projectile-key")) {
                    CombatType type = CombatType.valueOf(data.get("combat-type").getAsString());
                    String key = data.get("projectile-key").getAsString();
                    definition.combatAttackData = new CombatAttackData(type, key);
                }
                if (data.has("respawn")) {
                    definition.respawnTime = data.get("respawn").getAsInt();
                }
                for (int index = 0; index < SKILL_FIELD_NAMES.length; index++) {
                    String skillName = SKILL_FIELD_NAMES[index];
                    if (data.has(skillName)) {
                        if (definition.skills == EMPTY_SKILLS) {
                            definition.skills = new int[EMPTY_SKILLS.length];
                        }
                        definition.skills[index] = data.get(skillName).getAsInt();
                    }
                }
                for (int index = 0; index < BONUS_CONFIG_FIELD_NAMES.length; index++) {
                    String bonusName = BONUS_CONFIG_FIELD_NAMES[index];
                    if (data.has(bonusName)) {
                        if (definition.bonuses == EMPTY_BONUSES) {
                            definition.bonuses = new int[EMPTY_BONUSES.length];
                        }
                        definition.bonuses[index] = data.get(bonusName).getAsInt();
                    }
                }
                DEFINITIONS[id] = definition;
            }
            @Override
            protected void onEnd() {
                MonsterDefLoader.load();
            }
        };
    }
References com.runehive.fs.cache.decoder.CacheNpcDefinition.combatLevel, DEFINITIONS, com.runehive.fs.cache.decoder.CacheNpcDefinition.halfTurnAnimation, id, com.runehive.fs.cache.decoder.CacheNpcDefinition.lookup(), com.runehive.fs.cache.decoder.CacheNpcDefinition.name, NpcDefinition(), com.runehive.fs.cache.decoder.CacheNpcDefinition.quarterAnticlockwiseTurnAnimation, com.runehive.fs.cache.decoder.CacheNpcDefinition.quarterClockwiseTurnAnimation, com.runehive.fs.cache.decoder.CacheNpcDefinition.size, com.runehive.fs.cache.decoder.CacheNpcDefinition.standingAnimation, and com.runehive.fs.cache.decoder.CacheNpcDefinition.walkingAnimation.
Referenced by com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), main(), com.runehive.util.tools.DropDefinitionDumper.main(), and com.runehive.RuneHive.processSequentialStartupTasks().
equals()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.equals (Object obj)
Definition at line 509 of file NpcDefinition.java.
{
        return obj == this || (obj instanceof NpcDefinition && ((NpcDefinition) obj).id == id);
    }
References id, and NpcDefinition().
get() [1/2]
NpcDefinition com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get (int id) static
Gets a npc definition from the definition array.
Definition at line 212 of file NpcDefinition.java.
{
        if (id > Config.NPC_DEFINITION_LIMIT)
            return DEFINITIONS[Config.NPC_DEFINITION_LIMIT];
        if (id < 0)
            id = 0;
        if (DEFINITIONS[id] == null)
            return new NpcDefinition(id, "null");
        return DEFINITIONS[id];
    }
References DEFINITIONS, id, com.runehive.Config.NPC_DEFINITION_LIMIT, and NpcDefinition().
Referenced by com.runehive.content.DropDisplay.display(), com.runehive.game.world.entity.mob.npc.NpcAssistant.login(), com.runehive.util.tools.DropDefinitionDumper.main(), com.runehive.content.simulator.DropSimulator.open(), com.runehive.content.DropDisplay.search(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.game.world.entity.mob.Mob.transform(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.transform().
get() [2/2]
NpcDefinition com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get (String name) static
Definition at line 225 of file NpcDefinition.java.
{
        for (NpcDefinition definition : DEFINITIONS) {
            if (definition != null && definition.getName().equals(name)) {
                return definition;
            }
        }
        return null;
    }
References DEFINITIONS, name, and NpcDefinition().
getAttackAnim()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackAnim ()
Definition at line 415 of file NpcDefinition.java.
{
        return attackAnim;
    }
References attackAnim.
getAttackAnimation()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackAnimation ()
Returns
the attack anim.
Definition at line 298 of file NpcDefinition.java.
{
        return attackAnim;
    }
References attackAnim.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getAttackAnimation(), and com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.getAttackAnimation().
getAttackDelay()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackDelay ()
Returns
the attack delay.
Definition at line 351 of file NpcDefinition.java.
{
        return attackDelay;
    }
References attackDelay.
Referenced by com.runehive.content.activity.infernomobs.AkMej.getAttackDelay(), com.runehive.content.activity.infernomobs.AkXil.getAttackDelay(), com.runehive.content.activity.infernomobs.JalAk.getAttackDelay(), com.runehive.content.activity.infernomobs.MejRah.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothPrime.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothSupreme.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.Spinolyp.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getAttackDelay(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getAttackDelay(), and com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.getAttackDelay().
getAttackRadius()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackRadius ()
Returns
the attack radius.
Definition at line 356 of file NpcDefinition.java.
{
        return attackRadius;
    }
References attackRadius.
getBlockAnim()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getBlockAnim ()
Definition at line 423 of file NpcDefinition.java.
{
        return blockAnim;
    }
References blockAnim.
getBlockAnimation()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getBlockAnimation ()
Returns
the block anim.
Definition at line 303 of file NpcDefinition.java.
{
        return blockAnim;
    }
References blockAnim.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.getBlockAnimation().
getBonuses()
int[] com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getBonuses ()
Returns
the equipment bonus array.
Definition at line 371 of file NpcDefinition.java.
{
        return bonuses;
    }
References bonuses.
Referenced by com.runehive.game.world.entity.mob.Mob.transform().
getCombatAttackData()
Optional< CombatAttackData > com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getCombatAttackData ()
Definition at line 499 of file NpcDefinition.java.
{
        return Optional.ofNullable(combatAttackData);
    }
References combatAttackData.
getCombatLevel()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getCombatLevel ()
Returns
the combat level.
Definition at line 268 of file NpcDefinition.java.
{
        return combatLevel;
    }
References combatLevel.
getCombatLevelRange()
String com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getCombatLevelRange (String name) static
Definition at line 234 of file NpcDefinition.java.
{
        List<Integer> levels = new ArrayList<>();
        for (NpcDefinition definition : DEFINITIONS) {
            if (definition != null && definition.getName().contains(name)) {
                levels.add(definition.getCombatLevel());
            }
        }
        if (levels.isEmpty()) {
            return "Unknown";
        }
        Collections.sort(levels);
        return levels.get(0) + "-" + levels.get(levels.size() - 1);
    }
References DEFINITIONS, name, and NpcDefinition().
Referenced by com.runehive.content.skill.impl.slayer.SlayerTask.getCombatLevel().
getDeathAnim()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getDeathAnim ()
Definition at line 431 of file NpcDefinition.java.
{
        return deathAnim;
    }
References deathAnim.
getDeathAnimation()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getDeathAnimation ()
Returns
the death anim.
Definition at line 308 of file NpcDefinition.java.
{
        return deathAnim;
    }
References deathAnim.
Referenced by com.runehive.content.activity.impl.kraken.KrakenActivity.cleanup().
getDeathTimer()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getDeathTimer ()
Definition at line 312 of file NpcDefinition.java.
{
        return deathTimer;
    }
References deathTimer.
getId()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getId ()
Returns
the id.
Definition at line 253 of file NpcDefinition.java.
                       {
        return id;
    }
References id.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.block(), com.runehive.content.simulator.DropSimulator.drawList(), and com.runehive.content.dialogue.DialogueFactory.sendNpcChat().
getName()
String com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getName ()
Returns
the name.
Definition at line 258 of file NpcDefinition.java.
{
        return name;
    }
References name.
Referenced by com.runehive.content.DropDisplay.display(), com.runehive.content.simulator.DropSimulator.drawList(), com.runehive.util.tools.DropDefinitionDumper.main(), com.runehive.content.simulator.DropSimulator.open(), com.runehive.content.DropDisplay.search(), and com.runehive.content.dialogue.DialogueFactory.sendNpcChat().
getPlayer()
Player com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getPlayer ()
Definition at line 491 of file NpcDefinition.java.
{
        return player;
    }
References player.
getRespawnTime()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getRespawnTime ()
Returns
the respawn time in ticks.
Definition at line 361 of file NpcDefinition.java.
{
        return respawnTime;
    }
References respawnTime.
getSize()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getSize ()
Returns
the sze.
Definition at line 263 of file NpcDefinition.java.
{
        return size;
    }
References size.
Referenced by com.runehive.game.world.position.Position.isWithinDiagonalDistance(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextHit(), and com.runehive.game.world.entity.mob.Mob.transform().
getSkills()
int[] com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getSkills ()
Returns
the skill level array.
Definition at line 366 of file NpcDefinition.java.
{
        return skills;
    }
References skills.
Referenced by com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getDefenceNpc(), and com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicLevelNpc().
getStand()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getStand ()
Returns
the stand anim.
Definition at line 273 of file NpcDefinition.java.
{
        return stand;
    }
References stand.
Referenced by com.runehive.game.world.entity.mob.MobAnimation.setNpcAnimations().
getTurn180()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getTurn180 ()
Returns
the turn 180 anim.
Definition at line 283 of file NpcDefinition.java.
{
        return turn180;
    }
References turn180.
Referenced by com.runehive.game.world.entity.mob.MobAnimation.setNpcAnimations().
getTurn90CCW()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getTurn90CCW ()
Returns
the turn 90 CCW anim.
Definition at line 293 of file NpcDefinition.java.
{
        return turn90CCW;
    }
References turn90CCW.
Referenced by com.runehive.game.world.entity.mob.MobAnimation.setNpcAnimations().
getTurn90CW()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getTurn90CW ()
Returns
the turn 90 CW anim.
Definition at line 288 of file NpcDefinition.java.
{
        return turn90CW;
    }
References turn90CW.
Referenced by com.runehive.game.world.entity.mob.MobAnimation.setNpcAnimations().
getWalk()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getWalk ()
Returns
the walk anim.
Definition at line 278 of file NpcDefinition.java.
{
        return walk;
    }
References walk.
Referenced by com.runehive.game.world.entity.mob.MobAnimation.setNpcAnimations().
hashCode()
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.hashCode ()
Definition at line 504 of file NpcDefinition.java.
{
        return Objects.hash(id, name, size);
    }
References name, and size.
hasPoisonImmunity()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.hasPoisonImmunity ()
Returns
the poison immunity flag.
Definition at line 337 of file NpcDefinition.java.
{
        return poisonImmunity;
    }
References poisonImmunity.
hasVenomImmunity()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.hasVenomImmunity ()
Returns
the venom immunity flag.
Definition at line 342 of file NpcDefinition.java.
{
        return venomImmunity;
    }
References venomImmunity.
isAggressive()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isAggressive ()
Returns
the aggressive flag.
Definition at line 322 of file NpcDefinition.java.
{
        return aggressive;
    }
References aggressive.
isAttackable()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isAttackable ()
Returns
the attackable flag.
Definition at line 317 of file NpcDefinition.java.
{
        return attackable;
    }
References attackable.
isFlying()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isFlying ()
Definition at line 346 of file NpcDefinition.java.
{
        return flying;
    }
References flying.
isPoisonImmunity()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isPoisonImmunity ()
Definition at line 451 of file NpcDefinition.java.
{
        return poisonImmunity;
    }
References poisonImmunity.
isPoisonous()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isPoisonous ()
Returns
the poisonous flag.
Definition at line 332 of file NpcDefinition.java.
{
        return poisonous;
    }
References poisonous.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.attack(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.attack(), and com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.sendProjectile().
isRetaliate()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isRetaliate ()
Returns
the retaliate flag.
Definition at line 327 of file NpcDefinition.java.
{
        return retaliate;
    }
References retaliate.
isVenomImmunity()
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isVenomImmunity ()
Definition at line 459 of file NpcDefinition.java.
{
        return venomImmunity;
    }
References venomImmunity.
main()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.main (String[] args) static
Definition at line 83 of file NpcDefinition.java.
{
        GsonParser parser = createParser();
        parser.deserialize();
    }
References createParser(), and com.runehive.util.parser.GsonParser.deserialize().
setAggressive()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setAggressive (boolean aggressive)
Definition at line 375 of file NpcDefinition.java.
{
        this.aggressive = aggressive;
    }
References aggressive.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), and com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn().
setAttackable()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setAttackable (boolean attackable)
Definition at line 443 of file NpcDefinition.java.
{
        this.attackable = attackable;
    }
References attackable.
setAttackAnim()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setAttackAnim (int attackAnim)
Definition at line 419 of file NpcDefinition.java.
{
        this.attackAnim = attackAnim;
    }
References attackAnim.
setAttackDelay()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setAttackDelay (int attackDelay)
Definition at line 479 of file NpcDefinition.java.
{
        this.attackDelay = attackDelay;
    }
References attackDelay.
setAttackRadius()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setAttackRadius (int attackRadius)
Definition at line 483 of file NpcDefinition.java.
{
        this.attackRadius = attackRadius;
    }
References attackRadius.
setBlockAnim()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setBlockAnim (int blockAnim)
Definition at line 427 of file NpcDefinition.java.
{
        this.blockAnim = blockAnim;
    }
References blockAnim.
setBonuses()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setBonuses (int[] bonuses)
Definition at line 475 of file NpcDefinition.java.
{
        this.bonuses = bonuses;
    }
References bonuses.
setCombatAttackData()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setCombatAttackData (CombatAttackData combatAttackData)
Definition at line 487 of file NpcDefinition.java.
{
        this.combatAttackData = combatAttackData;
    }
References combatAttackData.
setCombatLevel()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setCombatLevel (int combatLevel)
Definition at line 387 of file NpcDefinition.java.
{
        this.combatLevel = combatLevel;
    }
References combatLevel.
setDeathAnim()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setDeathAnim (int deathAnim)
Definition at line 435 of file NpcDefinition.java.
{
        this.deathAnim = deathAnim;
    }
References deathAnim.
setDeathTimer()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setDeathTimer (int deathTimer)
Definition at line 439 of file NpcDefinition.java.
{
        this.deathTimer = deathTimer;
    }
References deathTimer.
setFlying()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setFlying (boolean flying)
Definition at line 467 of file NpcDefinition.java.
{
        this.flying = flying;
    }
References flying.
setPlayer()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setPlayer (Player player)
Definition at line 495 of file NpcDefinition.java.
{
        this.player = player;
    }
References player.
setPoisonImmunity()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setPoisonImmunity (boolean poisonImmunity)
Definition at line 455 of file NpcDefinition.java.
{
        this.poisonImmunity = poisonImmunity;
    }
References poisonImmunity.
setPoisonous()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setPoisonous (boolean poisonous)
Definition at line 447 of file NpcDefinition.java.
{
        this.poisonous = poisonous;
    }
References poisonous.
setRespawnTime()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setRespawnTime (int respawnTime)
Definition at line 383 of file NpcDefinition.java.
{
        this.respawnTime = respawnTime;
    }
References respawnTime.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), and com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.hit().
setRetaliate()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setRetaliate (boolean retaliate)
Definition at line 379 of file NpcDefinition.java.
{
        this.retaliate = retaliate;
    }
References retaliate.
setSize()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setSize (int size)
Definition at line 391 of file NpcDefinition.java.
{
        this.size = size;
    }
References size.
setSkills()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setSkills (int[] skills)
Definition at line 471 of file NpcDefinition.java.
{
        this.skills = skills;
    }
References skills.
setStand()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setStand (int stand)
Definition at line 395 of file NpcDefinition.java.
{
        this.stand = stand;
    }
References stand.
setTurn180()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setTurn180 (int turn180)
Definition at line 403 of file NpcDefinition.java.
{
        this.turn180 = turn180;
    }
References turn180.
setTurn90CCW()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setTurn90CCW (int turn90CCW)
Definition at line 411 of file NpcDefinition.java.
{
        this.turn90CCW = turn90CCW;
    }
References turn90CCW.
setTurn90CW()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setTurn90CW (int turn90CW)
Definition at line 407 of file NpcDefinition.java.
{
        this.turn90CW = turn90CW;
    }
References turn90CW.
setVenomImmunity()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setVenomImmunity (boolean venomImmunity)
Definition at line 463 of file NpcDefinition.java.
{
        this.venomImmunity = venomImmunity;
    }
References venomImmunity.
setWalk()
void com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.setWalk (int walk)
Definition at line 399 of file NpcDefinition.java.
{
        this.walk = walk;
    }
References walk.
Member Data Documentation
aggressive
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.aggressive private
Definition at line 41 of file NpcDefinition.java.
Referenced by isAggressive(), and setAggressive().
attackable
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.attackable private
Definition at line 40 of file NpcDefinition.java.
Referenced by isAttackable(), and setAttackable().
attackAnim
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.attackAnim private
Definition at line 36 of file NpcDefinition.java.
Referenced by getAttackAnim(), getAttackAnimation(), and setAttackAnim().
attackDelay
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.attackDelay private
Definition at line 49 of file NpcDefinition.java.
Referenced by getAttackDelay(), and setAttackDelay().
attackRadius
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.attackRadius private
Definition at line 50 of file NpcDefinition.java.
Referenced by getAttackRadius(), and setAttackRadius().
blockAnim
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.blockAnim private
Definition at line 37 of file NpcDefinition.java.
Referenced by getBlockAnim(), getBlockAnimation(), and setBlockAnim().
bonuses
int [] com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.bonuses private
Definition at line 48 of file NpcDefinition.java.
Referenced by getBonuses(), and setBonuses().
combatAttackData
CombatAttackData com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.combatAttackData private
Definition at line 52 of file NpcDefinition.java.
Referenced by getCombatAttackData(), and setCombatAttackData().
combatLevel
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.combatLevel private
Definition at line 29 of file NpcDefinition.java.
Referenced by getCombatLevel(), and setCombatLevel().
deathAnim
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.deathAnim private
Definition at line 38 of file NpcDefinition.java.
Referenced by getDeathAnim(), getDeathAnimation(), and setDeathAnim().
deathTimer
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.deathTimer private
Definition at line 39 of file NpcDefinition.java.
Referenced by getDeathTimer(), and setDeathTimer().
DEFINITIONS
final NpcDefinition [] com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.DEFINITIONS = new NpcDefinition[Config.NPC_DEFINITION_LIMIT + 1] static
The array of npc definitions.
Definition at line 25 of file NpcDefinition.java.
Referenced by createParser(), com.runehive.content.simulator.DropSimulator.drawList(), com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), get(), get(), getCombatLevelRange(), and com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType().
flying
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.flying private
Definition at line 46 of file NpcDefinition.java.
Referenced by isFlying(), and setFlying().
id
final int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.id private
Definition at line 27 of file NpcDefinition.java.
Referenced by createParser(), equals(), get(), getId(), and NpcDefinition().
name
final String com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.name private
Definition at line 28 of file NpcDefinition.java.
Referenced by get(), getCombatLevelRange(), getName(), hashCode(), and NpcDefinition().
player
Player com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.player private
Definition at line 53 of file NpcDefinition.java.
Referenced by getPlayer(), and setPlayer().
poisonImmunity
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.poisonImmunity private
Definition at line 44 of file NpcDefinition.java.
Referenced by hasPoisonImmunity(), isPoisonImmunity(), and setPoisonImmunity().
poisonous
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.poisonous private
Definition at line 43 of file NpcDefinition.java.
Referenced by isPoisonous(), and setPoisonous().
respawnTime
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.respawnTime private
Definition at line 51 of file NpcDefinition.java.
Referenced by getRespawnTime(), and setRespawnTime().
retaliate
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.retaliate private
Definition at line 42 of file NpcDefinition.java.
Referenced by isRetaliate(), and setRetaliate().
size
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.size private
Definition at line 30 of file NpcDefinition.java.
Referenced by getSize(), hashCode(), and setSize().
skills
int [] com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.skills private
Definition at line 47 of file NpcDefinition.java.
Referenced by getSkills(), and setSkills().
stand
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.stand private
Definition at line 31 of file NpcDefinition.java.
Referenced by getStand(), and setStand().
turn180
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.turn180 private
Definition at line 33 of file NpcDefinition.java.
Referenced by getTurn180(), and setTurn180().
turn90CCW
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.turn90CCW private
Definition at line 35 of file NpcDefinition.java.
Referenced by getTurn90CCW(), and setTurn90CCW().
turn90CW
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.turn90CW private
Definition at line 34 of file NpcDefinition.java.
Referenced by getTurn90CW(), and setTurn90CW().
venomImmunity
boolean com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.venomImmunity private
Definition at line 45 of file NpcDefinition.java.
Referenced by hasVenomImmunity(), isVenomImmunity(), and setVenomImmunity().
walk
int com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.walk private
Definition at line 32 of file NpcDefinition.java.
Referenced by getWalk(), and setWalk().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/npc/definition/NpcDefinition.java