RuneHive-Game: com.runehive.content.store.impl.DefaultStore Class Reference
com.runehive.content.store.impl.DefaultStore Class Reference
The default shop which are owned by the server.
Classes
class StoreRestockTask
The task that will restock items in shop containers when needed.
Public Member Functions
void close (Player player)
DefaultStore (StoreItem[] items, String name, SellType sellType, boolean restock, CurrencyType currency)
Creates a new Store.
void itemContainerAction (Player player, int id, int slot, int action, boolean purchase)
void open (Player player)
void refresh (Player player)
SellType sellType ()
StoreType type ()
Public Member Functions inherited from com.runehive.content.store.Store
boolean decrementStock ()
final boolean equals (Object obj)
final int hashCode ()
void onPurchase (Player player, Item item)
boolean purchase (Player player, Item item, int slot)
Store (String name, ItemContainer.StackPolicy policy, CurrencyType currencyType, int capacity)
Public Attributes
final StoreItem[] items
The items in this shop.
Public Attributes inherited from com.runehive.content.store.Store
ItemContainer container
The current item container which contains the current items from this shop.
Map< Integer, Integer > itemCache
The map of cached shop item identifications and their amounts.
final String name
The name of this shop.
final Set< Player > players = new HashSet<>()
The set of players that are currently viewing this shop.
Package Functions
boolean restockCompleted ()
Determines if the items in the container no longer need to be restocked.
Package Attributes
final ItemContainer original
The original item container this shop started with.
final boolean restock
Determines if this shop restocks.
Private Member Functions
boolean needsRestock ()
Determines if the items in the container need to be restocked.
Private Attributes
StoreRestockTask restockTask
The shop restock task that will restock the shops.
final SellType sellType
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.store.Store
static void closeShop (Player player)
static void exchange (Player player, int id, int slot, int action, boolean purchase)
Static Public Attributes inherited from com.runehive.content.store.Store
static Map< String, Store > STORES = new HashMap<>()
A mapping of each shop by it's name.
Protected Member Functions inherited from com.runehive.content.store.Store
final void sell (Player player, Item item, int slot, boolean addX)
void sendPurchaseValue (Player player, int slot)
final void sendSellValue (Player player, int slot)
Static Protected Member Functions inherited from com.runehive.content.store.Store
static List< PersonalStore > getFeaturedShops ()
static List< PersonalStore > getPersonalShops ()
Protected Attributes inherited from com.runehive.content.store.Store
final CurrencyType currencyType
The currency for this shop.
Detailed Description
The default shop which are owned by the server.
Author
Stand Up
Since
4-1-2017.
Definition at line 22 of file DefaultStore.java.
Constructor & Destructor Documentation
DefaultStore()
com.runehive.content.store.impl.DefaultStore.DefaultStore (StoreItem[] items, String name, SellType sellType, boolean restock, CurrencyType currency)
Creates a new Store.
Definition at line 39 of file DefaultStore.java.
{
        super(name, ItemContainer.StackPolicy.ALWAYS, currency, sellType == SellType.ANY ? 80 : items.length);
        this.items = items;
        this.restock = restock;
        this.sellType = sellType;
        this.original = new ItemContainer(items.length, ItemContainer.StackPolicy.ALWAYS);
        this.original.setItems(items, false);
        this.container.setItems(items, false);
        Arrays.stream(items).filter(Objects::nonNull).forEach(item -> itemCache.put(item.getId(), item.getAmount()));
    }
References com.runehive.game.world.items.containers.ItemContainer.StackPolicy.ALWAYS, com.runehive.content.store.SellType.ANY, com.runehive.content.store.Store.container, com.runehive.content.store.Store.itemCache, items, com.runehive.content.store.Store.name, restock, sellType, and com.runehive.game.world.items.containers.ItemContainer.setItems().
Referenced by com.runehive.content.store.impl.DefaultStore.StoreRestockTask.StoreRestockTask().
Member Function Documentation
close()
void com.runehive.content.store.impl.DefaultStore.close (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 131 of file DefaultStore.java.
{
        players.remove(player);
        player.attributes.remove("SHOP");
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.store.Store.players, and com.runehive.util.generic.GenericAttributes.remove().
itemContainerAction()
void com.runehive.content.store.impl.DefaultStore.itemContainerAction (Player player, int id, int slot, int action, boolean purchase)
Reimplemented from com.runehive.content.store.Store.
Definition at line 68 of file DefaultStore.java.
{
        switch (action) {
            case 1:
                if (purchase) {
                    this.sendPurchaseValue(player, slot);
                } else {
                    this.sendSellValue(player, slot);
                }
                break;
            case 5:
                player.send(new SendInputAmount("Enter amount", 10, amount -> {
                    if (purchase) {
                        this.purchase(player, new Item(id, Integer.parseInt(amount)), slot);
                    } else {
                        this.sell(player, new Item(id, Integer.parseInt(amount)), slot, true);
                    }
                }));
                break;
            default:
                int amount = 0;
                if (action == 2) {
                    amount = 1;
                }
                if (action == 3) {
                    amount = 10;
                }
                if (action == 4) {
                    amount = 100;
                }
                if (purchase) {
                    this.purchase(player, new Item(id, amount), slot);
                } else {
                    this.sell(player, new Item(id, amount), slot, false);
                }
                break;
        }
    }
References com.runehive.content.store.Store.purchase(), com.runehive.content.store.Store.sell(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.store.Store.sendPurchaseValue(), and com.runehive.content.store.Store.sendSellValue().
needsRestock()
boolean com.runehive.content.store.impl.DefaultStore.needsRestock () private
Determines if the items in the container need to be restocked.
Definition at line 51 of file DefaultStore.java.
{
        return container.stream().filter(Objects::nonNull).anyMatch(i -> !itemCache.containsKey(i.getId()) || (itemCache.containsKey(i.getId()) && i.getAmount() < itemCache.get(i.getId())));
    }
References com.runehive.content.store.Store.container, and com.runehive.content.store.Store.itemCache.
Referenced by refresh().
open()
void com.runehive.content.store.impl.DefaultStore.open (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 109 of file DefaultStore.java.
{
        if (PlayerRight.isIronman(player)) {
            if (Arrays.stream(StoreConstant.IRON_MAN_STORES).noneMatch(s -> s.equalsIgnoreCase(name))) {
                player.send(new SendMessage("As an iron man you do not have access to this store!"));
                return;
            }
        }
        player.attributes.set("SHOP", name);
        if (!STORES.containsKey(name)) {
            STORES.put(name, this);
        }
        players.add(player);
        player.inventory.refresh();
        refresh(player);
        player.send(new SendString(name, 47502));
        player.interfaceManager.openInventory(StoreConstant.INTERFACE_ID, 3822);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.store.StoreConstant.INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.store.StoreConstant.IRON_MAN_STORES, com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.content.store.Store.name, com.runehive.game.world.entity.mob.player.InterfaceManager.openInventory(), com.runehive.content.store.Store.players, refresh(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), and com.runehive.content.store.Store.STORES.
refresh()
void com.runehive.content.store.impl.DefaultStore.refresh (Player player)
Reimplemented from com.runehive.content.store.Store.
Definition at line 137 of file DefaultStore.java.
{
        player.send(new SendString("Store size: " + items.length, 47507));
        player.send(new SendString(CurrencyType.getValue(player, currencyType), 47508));
        final Item[] items = container.toArray();
        int lastItem = 0;
        for (int i = 0; i < items.length; i++) {
            Item item = items[i];
            if (item == null) {
                continue;
            }
            if (item instanceof StoreItem) {
                StoreItem storeItem = (StoreItem) items[i];
                player.send(new SendString(storeItem.getShopValue() + "," + storeItem.getShopCurrency(this).getId(), 47552 + i));
                lastItem = i;
            }
        }
        final int scrollBarSize = lastItem <= 32 ? 0 : (lastItem / 8) * 72;
        player.send(new SendScrollbar(47550, scrollBarSize));
        player.send(new SendItemOnInterface(3823, player.inventory.toArray()));
        players.stream().filter(Objects::nonNull).forEach(p -> player.send(new SendItemOnInterface(47551, container.toArray())));
        if (restock) {
            if (restockTask != null && restockTask.isRunning()) {
                return;
            }
            if (!needsRestock()) {
                return;
            }
            restockTask = new StoreRestockTask(this);
            World.schedule(restockTask);
        }
    }
References com.runehive.content.store.Store.container, com.runehive.content.store.Store.currencyType, com.runehive.content.store.currency.CurrencyType.getId(), com.runehive.content.store.StoreItem.getShopCurrency(), com.runehive.content.store.StoreItem.getShopValue(), com.runehive.content.store.currency.CurrencyType.getValue(), com.runehive.game.world.entity.mob.player.Player.inventory, items, needsRestock(), com.runehive.content.store.Store.players, restock, restockTask, com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.items.containers.ItemContainer.toArray().
Referenced by open().
restockCompleted()
boolean com.runehive.content.store.impl.DefaultStore.restockCompleted () package
Determines if the items in the container no longer need to be restocked.
Definition at line 56 of file DefaultStore.java.
{
        return container.stream().filter(Objects::nonNull).allMatch(i -> {
            if (itemCache.containsKey(i.getId()) && i.getAmount() >= itemCache.get(i.getId())) {//shop item.
                return true;
            } else if (!itemCache.containsKey(i.getId())) {//unique item.
                return false;
            }
            return false;
        });
    }
References com.runehive.content.store.Store.container, and com.runehive.content.store.Store.itemCache.
sellType()
SellType com.runehive.content.store.impl.DefaultStore.sellType ()
Reimplemented from com.runehive.content.store.Store.
Definition at line 180 of file DefaultStore.java.
{
        return sellType;
    }
References sellType.
type()
StoreType com.runehive.content.store.impl.DefaultStore.type ()
Reimplemented from com.runehive.content.store.Store.
Definition at line 175 of file DefaultStore.java.
{
        return StoreType.DEFAULT;
    }
References com.runehive.content.store.StoreType.DEFAULT.
Member Data Documentation
items
final StoreItem [] com.runehive.content.store.impl.DefaultStore.items
The items in this shop.
Definition at line 25 of file DefaultStore.java.
Referenced by DefaultStore(), refresh(), and com.runehive.content.store.impl.DefaultStore.StoreRestockTask.tick().
original
final ItemContainer com.runehive.content.store.impl.DefaultStore.original package
The original item container this shop started with.
Definition at line 28 of file DefaultStore.java.
restock
final boolean com.runehive.content.store.impl.DefaultStore.restock package
Determines if this shop restocks.
Definition at line 31 of file DefaultStore.java.
Referenced by DefaultStore(), refresh(), and com.runehive.content.store.impl.DefaultStore.StoreRestockTask.tick().
restockTask
StoreRestockTask com.runehive.content.store.impl.DefaultStore.restockTask private
The shop restock task that will restock the shops.
Definition at line 36 of file DefaultStore.java.
Referenced by refresh().
sellType
final SellType com.runehive.content.store.impl.DefaultStore.sellType private
Definition at line 33 of file DefaultStore.java.
Referenced by DefaultStore(), and sellType().
The documentation for this class was generated from the following file:
java/com/runehive/content/store/impl/DefaultStore.java