RuneHive-Game: com.runehive.content.activity.impl.godwars.GodwarsListener Class Reference
com.runehive.content.activity.impl.godwars.GodwarsListener Class Reference
The combat listener for the god wars activity.
Public Member Functions
boolean canAttack (Mob attacker, Mob defender)
void onKill (Mob attacker, Mob defender, Hit hit)
Public Member Functions inherited from com.runehive.content.activity.ActivityListener< T extends Activity >
ActivityListener (T activity)
Constructs a new ActivityListener for a activity.
void attack (Mob attacker, Mob defender, Hit hit)
void block (Mob attacker, Mob defender, Hit hit, CombatType combatType)
boolean canOtherAttack (Mob attacker, Mob defender)
void finishIncoming (Mob attacker, Mob defender)
void finishOutgoing (Mob attacker, Mob defender)
void hit (Mob attacker, Mob defender, Hit hit)
void hitsplat (Mob attacker, Mob defender, Hit hit)
void onDamage (Mob defender, Hit hit)
void onDeath (Mob attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, Mob defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (Mob attacker, Mob defender, Hit[] hits)
boolean withinDistance (Mob attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Package Functions
GodwarsListener (GodwarsActivity activity)
Additional Inherited Members
Protected Attributes inherited from com.runehive.content.activity.ActivityListener< T extends Activity >
final T activity
The parent activity.
Detailed Description
The combat listener for the god wars activity.
Author
Daniel
Definition at line 16 of file GodwarsListener.java.
Constructor & Destructor Documentation
GodwarsListener()
com.runehive.content.activity.impl.godwars.GodwarsListener.GodwarsListener (GodwarsActivity activity) package
Definition at line 18 of file GodwarsListener.java.
{
        super(activity);
    }
References com.runehive.content.activity.ActivityListener< T extends Activity >.activity.
Member Function Documentation
canAttack()
boolean com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack (Mob attacker, Mob defender)
Reimplemented from com.runehive.content.activity.ActivityListener< T extends Activity >.
Definition at line 23 of file GodwarsListener.java.
{
        System.out.println(defender);
        if (!attacker.isPlayer() && !defender.isNpc()) {
            return super.canAttack(attacker, defender);
        }
        Npc npc = defender.getNpc();
        if (npc.id == 3166 || npc.id == 3167 || npc.id == 3168 || npc.id == 3172 || npc.id == 3176 || npc.id == 3183) {
            if (attacker.getStrategy().getCombatType().equals(CombatType.MELEE)) {
                attacker.getPlayer().message("You can't attack Armadyl with melee!");
                return false;
            }
        }
        return super.canAttack(attacker, defender);
    }
References com.runehive.game.world.entity.mob.npc.Npc.canAttack, com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.Mob.getStrategy(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.combat.CombatType.MELEE, and com.runehive.game.world.entity.mob.player.Player.message().
onKill()
void com.runehive.content.activity.impl.godwars.GodwarsListener.onKill (Mob attacker, Mob defender, Hit hit)
Reimplemented from com.runehive.content.activity.ActivityListener< T extends Activity >.
Definition at line 42 of file GodwarsListener.java.
{
        if (defender.isNpc()) {
            Npc npc = defender.getNpc();
            if (npc.npcAssistant.isArmadyl()) {
                activity.increment(ARMADYL);
            } else if (npc.npcAssistant.isBandos()) {
                activity.increment(BANDOS);
            } else if (npc.npcAssistant.isSaradomin()) {
                activity.increment(SARADOMIN);
            } else if (npc.npcAssistant.isZamorak()) {
                activity.increment(ZAMORAK);
            }
        }
    }
References com.runehive.content.activity.ActivityListener< T extends Activity >.activity, com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.content.activity.ActivityListener< T extends Activity >.hit(), com.runehive.game.world.entity.mob.npc.NpcAssistant.isArmadyl(), com.runehive.game.world.entity.mob.npc.NpcAssistant.isBandos(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.npc.NpcAssistant.isSaradomin(), com.runehive.game.world.entity.mob.npc.NpcAssistant.isZamorak(), and com.runehive.game.world.entity.mob.npc.Npc.npcAssistant.
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/godwars/GodwarsListener.java