RuneHive-Game: com.runehive.util.tools.wiki.impl.NpcDropsParser Class Reference
com.runehive.util.tools.wiki.impl.NpcDropsParser Class Reference
Classes
class DropItem
enum DropRarity
class NpcDropTable
Static Public Member Functions
static void main (String[] args) throws InterruptedException
Protected Member Functions
void finish ()
Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
void execute (Runnable runnable)
Private Member Functions
NpcDropsParser ()
Static Private Member Functions
static LinkedList< WikiTable > generateTables ()
Static Private Attributes
static final Map< String, ItemDefinition > itemByName = new HashMap<>()
Additional Inherited Members
Public Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
void begin () throws InterruptedException
Begins parsing wiki tables for all the names provided.
WikiTableParser (LinkedList< WikiTable > tables)
Constructs a new WikiTableParser object.
Static Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
static void writeToJson (String name, JsonElement array)
Writes the parsed wiki dump to a json file in ./data/wiki named as the name parameter.
Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
final LinkedList< WikiTable > tables
The WikiTable list to parse.
Static Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create()
The gson object.
static final String WIKI_LINK = "http://oldschoolrunescape.wikia.com/wiki/"
The path to the wiki page address.
Detailed Description
Definition at line 18 of file NpcDropsParser.java.
Constructor & Destructor Documentation
NpcDropsParser()
com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropsParser () private
Definition at line 22 of file NpcDropsParser.java.
{
        super(generateTables());
    }
References generateTables().
Referenced by main().
Member Function Documentation
finish()
void com.runehive.util.tools.wiki.impl.NpcDropsParser.finish () protected
Reimplemented from com.runehive.util.tools.wiki.parser.WikiTableParser.
Definition at line 71 of file NpcDropsParser.java.
{
        JsonArray array = new JsonArray();
        for (WikiTable table : tables) {
            array.addAll(table.getTable());
        }
        writeToJson("wiki_drop_dump", array);
    }
References com.runehive.util.tools.wiki.parser.WikiTableParser.tables, and com.runehive.util.tools.wiki.parser.WikiTableParser.writeToJson().
generateTables()
LinkedList< WikiTable > com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables () static private
Definition at line 26 of file NpcDropsParser.java.
{
        ItemDefinition.createParser().run();
        for (ItemDefinition definition : ItemDefinition.DEFINITIONS) {
            if (definition == null || definition.getName() == null || definition.getName().equals("null") || itemByName.containsKey(definition.getName())) {
                continue;
            }
            itemByName.put(definition.getName(), definition);
        }
        LinkedListMultimap<String, NpcDefinition> byName = LinkedListMultimap.create();
        NpcDefinition.createParser().run();
        new NpcDropParser().run();
        for (NpcDefinition definition : NpcDefinition.DEFINITIONS) {
            if (definition == null || definition.getName() == null || definition.getName().equals("null")) {
                continue;
            }
            if (!definition.isAttackable()) {
                continue;
            }
            if (NpcDropManager.NPC_DROPS.containsKey(definition.getId())) {
                continue;
            }
            byName.put(definition.getName(), definition);
        }
        LinkedList<WikiTable> tables = new LinkedList<>();
//        tables.add(new NpcDropTable(WIKI_LINK.concat("King Black Dragon".replaceAll(" ", "_")), ImmutableList.of(NpcDefinition.DEFINITIONS[239])));
        for (Map.Entry<String, Collection<NpcDefinition>> entry : byName.asMap().entrySet()) {
            String name = entry.getKey();
            name = name.replaceAll(" ", "_");
            int idx = name.indexOf("(");
            if (idx > -1)
                name = name.substring(0, idx);
            tables.add(new NpcDropTable(WIKI_LINK.concat(name), entry.getValue()));
        }
        return tables;
    }
References com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.createParser(), com.runehive.game.world.items.ItemDefinition.createParser(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.DEFINITIONS, com.runehive.game.world.items.ItemDefinition.DEFINITIONS, com.runehive.game.world.items.ItemDefinition.getId(), com.runehive.game.world.items.ItemDefinition.getName(), itemByName, com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.NPC_DROPS, com.runehive.util.parser.GenericParser.run(), com.runehive.util.tools.wiki.parser.WikiTableParser.tables, and com.runehive.util.tools.wiki.parser.WikiTableParser.WIKI_LINK.
Referenced by NpcDropsParser().
main()
void com.runehive.util.tools.wiki.impl.NpcDropsParser.main (String[] args) throws InterruptedException static
Definition at line 79 of file NpcDropsParser.java.
{
        NpcDropsParser parser = new NpcDropsParser();
        parser.begin();
    }
References NpcDropsParser().
Member Data Documentation
itemByName
final Map<String, ItemDefinition> com.runehive.util.tools.wiki.impl.NpcDropsParser.itemByName = new HashMap<>() static private
Definition at line 20 of file NpcDropsParser.java.
Referenced by generateTables(), and com.runehive.util.tools.wiki.impl.NpcDropsParser.NpcDropTable.parseDocument().
The documentation for this class was generated from the following file:
java/com/runehive/util/tools/wiki/impl/NpcDropsParser.java