RuneHive-Game: com.runehive.content.bloodmoney.BloodMoneyChest Class Reference
com.runehive.content.bloodmoney.BloodMoneyChest Class Reference
The blood money chest manager.
Static Public Member Functions
static void finish (boolean unlocked)
Handles finishing the blood money chet.
static String getInformation ()
The information displayed on information tab.
static void open (Player player)
Handles opening the blood money chest.
static void spawn ()
Handles spawning the blood money chest.
Static Public Attributes
static boolean active
The state of the blood money chest.
static CustomGameObject chest
The blood money chest object.
static BloodMoneyPosition data
Blood chest position.
static Npc guardian
The guardian npc.
static final Stopwatch stopwatch = Stopwatch.start()
The stopwatch for this event.
Static Private Attributes
static Player viewer
The current blood money chest viewer.
Detailed Description
The blood money chest manager.
Author
Daniel
Definition at line 17 of file BloodMoneyChest.java.
Member Function Documentation
finish()
void com.runehive.content.bloodmoney.BloodMoneyChest.finish (boolean unlocked) static
Handles finishing the blood money chet.
Definition at line 56 of file BloodMoneyChest.java.
{
        active = false;
        chest.unregister();
        if (guardian != null && guardian.isRegistered()) {
            guardian.unregister();
        }
        if (viewer != null) {
            if (unlocked) {
                World.sendMessage("<icon=0><col=FF0000> Blood money chest was unlocked by " + viewer.getName() + "!");
                // DiscordPlugin.sendSimpleMessage("Blood money chest has been unlocked by " + viewer.getName() + "!");
                viewer.inventory.addOrDrop(new Item(20608));
            }
            viewer.interfaceManager.close(4543);
            viewer = null;
            return;
        }
        World.sendMessage("<icon=0><col=FF0000> Blood money chest has vanished!");
    }
References active, chest, guardian, com.runehive.game.world.World.sendMessage(), and viewer.
Referenced by com.runehive.content.bloodmoney.BloodChestEvent.execute().
getInformation()
String com.runehive.content.bloodmoney.BloodMoneyChest.getInformation () static
The information displayed on information tab.
Definition at line 98 of file BloodMoneyChest.java.
{
        return !active ? "Not Active" : data.name;
    }
References active, and data.
open()
void com.runehive.content.bloodmoney.BloodMoneyChest.open (Player player) static
Handles opening the blood money chest.
Definition at line 78 of file BloodMoneyChest.java.
{
        if (guardian != null) {
            player.dialogueFactory.sendStatement("The stone guardian must be killed!").execute();
            return;
        }
        if (viewer != null) {
            if (!viewer.interfaceManager.isInterfaceOpen(4543)) {
                viewer = null;
            } else {
                player.dialogueFactory.sendStatement("There is already someone unlocking the chest!").execute();
                return;
            }
        }
        viewer = player;
        player.puzzle.open(PuzzleType.BLOOD_MONEY);
    }
References com.runehive.content.puzzle.PuzzleType.BLOOD_MONEY, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), guardian, com.runehive.content.puzzle.PuzzleDisplay.open(), com.runehive.game.world.entity.mob.player.Player.puzzle, com.runehive.content.dialogue.DialogueFactory.sendStatement(), and viewer.
spawn()
void com.runehive.content.bloodmoney.BloodMoneyChest.spawn () static
Handles spawning the blood money chest.
Definition at line 37 of file BloodMoneyChest.java.
{
        data = Utility.randomElement(BloodMoneyPosition.values());
        chest = new CustomGameObject(27290, data.position);
        chest.rotate(data.direction);
        chest.register();
        guardian = new Npc(8066, data.position);
        guardian.boundaries = Utility.getInnerBoundaries(data.position, 5, 5);
        guardian.walkingRadius = 3;
        guardian.register();
        active = true;
        World.sendMessage("<icon=0><col=FF0000> Blood money chest has spawned at: " + data.name + ".");
        // DiscordPlugin.sendSimpleMessage("Blood money chest has spawned at " + data.name + "!");
    }
References active, chest, data, com.runehive.util.Utility.getInnerBoundaries(), guardian, com.runehive.util.Utility.randomElement(), and com.runehive.game.world.World.sendMessage().
Referenced by com.runehive.content.bloodmoney.BloodChestEvent.execute().
Member Data Documentation
active
boolean com.runehive.content.bloodmoney.BloodMoneyChest.active static
The state of the blood money chest.
Definition at line 19 of file BloodMoneyChest.java.
Referenced by com.runehive.content.bloodmoney.BloodChestEvent.execute(), finish(), getInformation(), and spawn().
chest
CustomGameObject com.runehive.content.bloodmoney.BloodMoneyChest.chest static
The blood money chest object.
Definition at line 25 of file BloodMoneyChest.java.
Referenced by finish(), and spawn().
data
BloodMoneyPosition com.runehive.content.bloodmoney.BloodMoneyChest.data static
Blood chest position.
Definition at line 31 of file BloodMoneyChest.java.
Referenced by getInformation(), and spawn().
guardian
Npc com.runehive.content.bloodmoney.BloodMoneyChest.guardian static
The guardian npc.
Definition at line 28 of file BloodMoneyChest.java.
Referenced by finish(), open(), com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.preDeath(), and spawn().
stopwatch
final Stopwatch com.runehive.content.bloodmoney.BloodMoneyChest.stopwatch = Stopwatch.start() static
The stopwatch for this event.
Definition at line 34 of file BloodMoneyChest.java.
Referenced by com.runehive.content.bloodmoney.BloodChestEvent.execute().
viewer
Player com.runehive.content.bloodmoney.BloodMoneyChest.viewer static private
The current blood money chest viewer.
Definition at line 22 of file BloodMoneyChest.java.
Referenced by finish(), and open().
The documentation for this class was generated from the following file:
java/com/runehive/content/bloodmoney/BloodMoneyChest.java