RuneHive-Game: com.runehive.game.world.items.containers.pricechecker.PriceChecker Class Reference
com.runehive.game.world.items.containers.pricechecker.PriceChecker Class Reference
The price checker container.
Classes
class PriceCheckerListener
Public Member Functions
void close ()
Closes the price checker interface.
void deposit (int slot, int amount)
Deposits an item into the price checker.
void depositAll ()
Deposits all the items into the price checker.
void onRefresh ()
Any functionality that should occur when refreshed.
void open ()
Opens the price checker interface.
PriceChecker (Player player)
Creates a new PriceChecker.
void refresh ()
void search (String name)
Searches for an item.
void searchItem (String name)
Searches for an item.
void setValue (PriceType type)
Sets the calculating value of the price checker.
void withdraw (int itemId, int amount)
Withdraws an item from the price checker.
void withdrawAll ()
Withdraw all the items from the price checker.
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainer
boolean add (int id, int amount)
Attempts to deposit item into this container.
boolean add (Item item)
Attempts to deposit item into this container.
boolean add (Item item, boolean refresh, boolean stack)
boolean add (Item item, int preferredIndex, boolean refresh)
boolean add (Item item, int preferredIndex, boolean refresh, boolean stack)
Attempts to deposit item into this container, preferably at preferredIndex.
boolean add (Item item, int slot)
Attempts to deposit item into this container.
boolean addAll (Collection<? extends Item > items)
Attempts to deposit items in bulk into this container.
boolean addAll (Item... items)
Attempts to deposit items in bulk into this container.
boolean addAll (ItemContainer items)
Attempts to deposit items in bulk into this container.
final boolean addListener (ItemContainerListener listener)
Adds an ItemContainerListener to this container.
boolean allowZero ()
final int capacity ()
void clear ()
Removes all of the items from this container.
final void clear (boolean refresh)
Removes all of the items from this container.
final int computeAmountForId (int id)
Computes the total quantity of the Items in this container with id.
final int computeFreeIndex ()
Computes the next free (null) index in this container.
final Optional< Integer > computeIdForIndex (int index)
Computes the identifier of the Item on index.
final int computeIndexCount (Item... forItems)
Computes the amount of indexes required to hold items in this container.
final int computeIndexForId (int id)
Computes the first index found that id is in.
long containerValue (PriceType type)
Gets the total worth of the container using the item's values.
boolean contains (int id)
Determines if this container contains id.
final boolean contains (int id, int amount)
final boolean contains (Item item)
final boolean containsAll (Collection< Item > items)
final boolean containsAll (int... identifiers)
Determines if this container contains all identifiers.
final boolean containsAll (Item... items)
final boolean containsAny (Collection< Item > items)
final boolean containsAny (int... identifiers)
Determines if this container contains any identifiers.
final boolean containsAny (Item... items)
final ItemContainer copy ()
Creates a copy of the underlying item container.
final void fireBulkItemsUpdatedEvent ()
Fires the ItemContainerListener.bulkItemsUpdated(ItemContainer) event.
final void fireCapacityExceededEvent ()
Fires the ItemContainerListener.capacityExceeded(ItemContainer) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh)
Fires the ItemContainerListener.itemUpdated(ItemContainer, int) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh, boolean login)
final void forEach (Consumer<? super Item > action)
Iterates through all of the Items within this container and performs action on them, skipping empty indexes (null values) as they are encountered.
final Item get (int index)
Gets the Item located on index.
int getFreeSlots ()
final int getId (int index)
Gets the item id located on index.
Item[] getItems ()
int getSlotById (int id)
Gets a slot by id.
double getWeight ()
Gets the weight of the container.
final boolean hasCapacityAfter (Item[] add, Item... remove)
Creates a copy of the underlying container and removes the items specified from it and after tries to deposit the specified items to it.
final boolean hasCapacityFor (Item... item)
Determines if this container has the capacity for item.
final void ifPresent (int index, Consumer< Item > action)
Consumes an action if the index is a valid item index in this container.
final boolean indexFree (int index)
Returns true if index is not occupied (null).
final boolean indexOccupied (int index)
Returns true if index is occupied (non-null).
final void insert (int oldIndex, int newIndex, boolean refresh)
final boolean isEmpty ()
final boolean isFull ()
ItemContainer (int capacity, StackPolicy policy)
Creates a new ItemContainer.
ItemContainer (int capacity, StackPolicy policy, Item[] items)
Creates a new ItemContainer.
final Iterator< Item > iterator ()
final StackPolicy policy ()
void refresh (Player player, int widget)
Sends the items on the itemcontainer.
final int remaining ()
boolean remove (int id)
boolean remove (int id, int amount)
boolean remove (Item item)
Attempts to withdraw item from this container.
boolean remove (Item item, int preferredIndex)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean remove (Item item, int preferredIndex, boolean refresh)
boolean remove (Item item, int preferredIndex, boolean refresh, boolean removeAll)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean removeAll (Collection<? extends Item > items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (Item... items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (ItemContainer items)
Attempts to withdraw items in bulk from this container.
final boolean removeListener (ItemContainerListener listener)
Removes an ItemContainerListener from this container.
final boolean replace (int oldId, int newId, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (int oldId, int newId, int index, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (Item first, Item second, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replaceAll (int oldId, int newId)
Replaces all occurrences of Items having the identifier
oldId with newId.
final Optional< Item > retrieve (int index)
Retrieves the item located on index.
Optional< Item > search (int id)
Searches and returns the first item found with id.
Optional< Item > search (Item item)
Searches and returns the first item found with id and
amount.
void set (int index, Item item, boolean refresh)
Sets the index to item.
final void set (Item[] toSet)
void setFiringEvents (boolean firingEvents)
Sets the value for firingEvents.
final void setItems (Item[] items)
final void setItems (Item[] items, boolean copy)
Sets the container of items to items.
void shift ()
Percolates the null indices to the end of the stack.
final int size ()
final Spliterator< Item > spliterator ()
final Stream< Item > stream ()
final void swap (boolean insert, int oldIndex, int newIndex, boolean refresh)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex, boolean refresh)
final Item[] toArray ()
Returns a shallow copy of the backing array.
final Item[] toNonNullArray ()
final void transfer (int firstIndex, int secondIndex, ItemContainer other, boolean refresh)
Public Attributes
Player player
The player instance.
Private Attributes
PriceType priceType
The price type.
Item searchedItem
The item being searched.
final int[] STRINGS = {48550, 48551, 48552, 48553, 48554, 48555, 48556, 48557, 48558, 48559, 48560, 48561, 48562, 48563, 48564, 48565, 48566, 48567, 48568, 48569, 48570, 48571, 48572, 48573, 48574, 48575, 48576, 48577,}
Holds all the string identifications.
Static Private Attributes
static final int PRICE_CHECKER_DISPLAY_ID = 48542
The price checker display widget identifier.
Detailed Description
The price checker container.
Author
Daniel
Definition at line 20 of file PriceChecker.java.
Constructor & Destructor Documentation
PriceChecker()
com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceChecker (Player player)
Creates a new PriceChecker.
Definition at line 38 of file PriceChecker.java.
{
        super(28, StackPolicy.STANDARD);
        this.player = player;
        this.priceType = PriceType.VALUE;
        addListener(new PriceCheckerListener());
    }
References com.runehive.game.world.items.containers.ItemContainer.addListener(), player, com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD, and com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE.
Member Function Documentation
close()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.close ()
Closes the price checker interface.
Definition at line 56 of file PriceChecker.java.
{
        withdrawAll();
        searchedItem = null;
        player.attributes.set("PRICE_CHECKER_KEY", false);
    }
References player, searchedItem, and withdrawAll().
deposit()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.deposit (int slot, int amount)
Deposits an item into the price checker.
Definition at line 114 of file PriceChecker.java.
{
        Item item = player.inventory.get(slot);
        if (item == null)
            return;
        if (!item.isTradeable()) {
            player.send(new SendMessage("This is item is untradeable!"));
            return;
        }
        int id = item.getId();
        int invAmount = player.inventory.computeAmountForId(id);
        if (invAmount < amount) {
            amount = invAmount;
        }
        setFiringEvents(false);
        add(id, amount);
        player.inventory.remove(item.getId(), amount);
        setFiringEvents(true);
        refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.isTradeable(), player, refresh(), and com.runehive.game.world.items.containers.ItemContainer.setFiringEvents().
Referenced by depositAll().
depositAll()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.depositAll ()
Deposits all the items into the price checker.
Definition at line 181 of file PriceChecker.java.
{
        Item[] items = player.inventory.toArray();
        for (int slot = 0; slot < items.length; slot++) {
            Item item = items[slot];
            if (item == null) {
                continue;
            }
            deposit(slot, item.getAmount());
        }
        refresh();
    }
References deposit(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.containers.ItemContainer.items, player, and refresh().
onRefresh()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.onRefresh ()
Any functionality that should occur when refreshed.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 211 of file PriceChecker.java.
{
        for (int index = 0; index < STRINGS.length; index++) {
            String value = "";
            if (getItems()[index] != null) {
                int price = getItems()[index].getValue(priceType);
                int amount = getItems()[index].getAmount();
                value = getItems()[index].isStackable() ? Utility.formatDigits(amount) + " x " + Utility.formatDigits(price) + "\\n" + "= " + Utility.formatDigits(price * amount) : Utility.formatDigits(price);
            }
            player.send(new SendString(value, STRINGS[index]));
        }
        player.inventory.refresh();
        player.send(new SendString("", 48582));
        player.send(new SendString("", 48583));
        player.send(new SendItemOnInterfaceSlot(48581, searchedItem, 0));
        player.send(new SendConfig(237, priceType == PriceType.VALUE ? 1 : 0));
        player.send(new SendItemOnInterface(InterfaceConstants.INVENTORY_STORE, player.inventory.toArray()));
        player.send(new SendString(searchedItem == null ? "" : "<col=ffb000>" + searchedItem.getName() + ":", 48582));
        player.send(new SendString(searchedItem == null ? "" : Utility.formatDigits(searchedItem.getValue(priceType)), 48583));
        player.send(new SendString("" + (priceType == PriceType.VALUE ? NumberFormat.getInstance().format(containerValue(PriceType.VALUE)) : NumberFormat.getInstance().format(containerValue(PriceType.HIGH_ALCH_VALUE))), 48513));
    }
References com.runehive.game.world.items.containers.ItemContainer.containerValue(), com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.items.Item.getValue(), com.runehive.game.world.items.containers.pricechecker.PriceType.HIGH_ALCH_VALUE, com.runehive.game.world.InterfaceConstants.INVENTORY_STORE, com.runehive.game.world.items.Item.isStackable(), player, priceType, searchedItem, STRINGS, and com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE.
open()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.open ()
Opens the price checker interface.
Definition at line 46 of file PriceChecker.java.
                       {
        refresh();
        player.send(new SendString("", 48583));
        player.send(new SendString("\\nSelect item to search", 48582));
        player.send(new SendItemOnInterface(48581));
        player.attributes.set("PRICE_CHECKER_KEY", true);
        player.interfaceManager.openInventory(48500, 5063);
    }
References player, and refresh().
refresh()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.refresh ()
Definition at line 206 of file PriceChecker.java.
{
        refresh(player, PRICE_CHECKER_DISPLAY_ID);
    }
References player, PRICE_CHECKER_DISPLAY_ID, and refresh().
Referenced by com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.bulkItemsUpdated(), deposit(), depositAll(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.itemUpdated(), open(), refresh(), setValue(), withdraw(), and withdrawAll().
search()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.search (String name)
Searches for an item.
Definition at line 63 of file PriceChecker.java.
{
        ItemDefinition found = null;
        for (ItemDefinition definition : ItemDefinition.DEFINITIONS) {
            if (definition == null)
                continue;
            String searched = definition.getName().toLowerCase().replace("'", "");
            if (!searched.contains(name.toLowerCase()))
                continue;
            found = definition;
            break;
        }
        if (found == null) {
            player.dialogueFactory.sendStatement("There were no results found for", "<col=255>" + name).execute();
            return;
        }
        player.send(new SendString(Utility.formatDigits(found.getValue()), 48582));
        player.send(new SendString(found.getName(), 48583));
        player.send(new SendItemOnInterface(48581, new Item(found.getId())));
    }
References com.runehive.game.world.items.ItemDefinition.DEFINITIONS, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.ItemDefinition.getId(), com.runehive.game.world.items.ItemDefinition.getName(), and player.
searchItem()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.searchItem (String name)
Searches for an item.
Definition at line 93 of file PriceChecker.java.
{
        Item searched = null;
        for (ItemDefinition item : ItemDefinition.DEFINITIONS) {
            if (item != null && (item.getName().equalsIgnoreCase(name) && !item.isNoted())) {
                searched = new Item(item.getId(), 1);
                break;
            }
        }
        if (searched == null) {
            player.send(new SendMessage("There was no item found under the name of " + name + "."));
        } else {
            searchedItem = searched;
            player.send(new SendItemOnInterfaceSlot(48581, searchedItem, 0));
            player.send(new SendString(searchedItem == null ? "" : "<col=ffb000>" + searchedItem.getName() + ":", 48582));
            player.send(new SendString(searchedItem == null ? "" : Utility.formatDigits(searchedItem.getValue(priceType)), 48583));
        }
    }
References com.runehive.game.world.items.ItemDefinition.DEFINITIONS, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.ItemDefinition.getId(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.items.ItemDefinition.isNoted(), player, priceType, and searchedItem.
setValue()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.setValue (PriceType type)
Sets the calculating value of the price checker.
Definition at line 87 of file PriceChecker.java.
{
        priceType = type;
        refresh();
    }
References priceType, and refresh().
withdraw()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdraw (int itemId, int amount)
Withdraws an item from the price checker.
Definition at line 140 of file PriceChecker.java.
{
        int slot = computeIndexForId(itemId);
        if (itemId < 0) return;
        Item item = get(slot);
        if (item == null || itemId != item.getId()) {
            return;
        }
        int contains = computeAmountForId(itemId);
        if (contains < amount) {
            amount = contains;
        }
        int id = item.getId();
        setFiringEvents(false);
        if (!new Item(id).isStackable() && amount > player.inventory.getFreeSlots()) {
            amount = player.inventory.getFreeSlots();
        }
        int fuckingSlot = player.inventory.computeIndexForId(id);
        if (fuckingSlot != -1) {
            Item fuckingStan = player.inventory.get(fuckingSlot);
            if (Integer.MAX_VALUE - fuckingStan.getAmount() < amount) {
                amount = Integer.MAX_VALUE - fuckingStan.getAmount();
                player.send(new SendMessage("Your inventory didn't have enough space to withdraw all that!"));
            }
        }
        if (remove(item.getId(), amount)) {
            player.inventory.add(id, amount);
            shift();
        }
        setFiringEvents(true);
        refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.computeIndexForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), player, refresh(), com.runehive.game.world.items.containers.ItemContainer.setFiringEvents(), and com.runehive.game.world.items.containers.ItemContainer.shift().
withdrawAll()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.withdrawAll ()
Withdraw all the items from the price checker.
Definition at line 195 of file PriceChecker.java.
{
        for (Item item : getItems()) {
            if (item != null) {
                if (this.remove(item)) {
                    player.inventory.add(item, -1, false);
                }
            }
        }
        refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.getItems(), player, and refresh().
Referenced by close().
Member Data Documentation
player
Player com.runehive.game.world.items.containers.pricechecker.PriceChecker.player
The player instance.
Definition at line 29 of file PriceChecker.java.
Referenced by close(), deposit(), depositAll(), onRefresh(), open(), PriceChecker(), refresh(), search(), searchItem(), withdraw(), and withdrawAll().
PRICE_CHECKER_DISPLAY_ID
final int com.runehive.game.world.items.containers.pricechecker.PriceChecker.PRICE_CHECKER_DISPLAY_ID = 48542 static private
The price checker display widget identifier.
Definition at line 26 of file PriceChecker.java.
Referenced by refresh().
priceType
PriceType com.runehive.game.world.items.containers.pricechecker.PriceChecker.priceType private
The price type.
Definition at line 32 of file PriceChecker.java.
Referenced by onRefresh(), searchItem(), and setValue().
searchedItem
Item com.runehive.game.world.items.containers.pricechecker.PriceChecker.searchedItem private
The item being searched.
Definition at line 35 of file PriceChecker.java.
Referenced by close(), onRefresh(), and searchItem().
STRINGS
final int [] com.runehive.game.world.items.containers.pricechecker.PriceChecker.STRINGS = {48550, 48551, 48552, 48553, 48554, 48555, 48556, 48557, 48558, 48559, 48560, 48561, 48562, 48563, 48564, 48565, 48566, 48567, 48568, 48569, 48570, 48571, 48572, 48573, 48574, 48575, 48576, 48577,} private
Holds all the string identifications.
Definition at line 23 of file PriceChecker.java.
{48550, 48551, 48552, 48553, 48554, 48555, 48556, 48557, 48558, 48559, 48560, 48561, 48562, 48563, 48564, 48565, 48566, 48567, 48568, 48569, 48570, 48571, 48572, 48573, 48574, 48575, 48576, 48577,};
Referenced by onRefresh().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/pricechecker/PriceChecker.java