RuneHive-Game: com.runehive.game.world.entity.mob.player.BannedPlayers Class Reference
com.runehive.game.world.entity.mob.player.BannedPlayers Class Reference
Static Public Member Functions
static void ban (String player)
static void load ()
static boolean unban (String player)
Static Public Attributes
static final List< String > bans = new ArrayList<>()
Static Private Member Functions
static void writeBans ()
Static Private Attributes
static final String BAN_LIST_PATH = "./data/bans.txt"
Detailed Description
Definition at line 13 of file BannedPlayers.java.
Member Function Documentation
ban()
void com.runehive.game.world.entity.mob.player.BannedPlayers.ban (String player) static
Definition at line 30 of file BannedPlayers.java.
{
        player = player.toLowerCase();
        if (bans.contains(player)) {
            return;
        }
        bans.add(player);
        writeBans();
    }
References bans, and writeBans().
load()
void com.runehive.game.world.entity.mob.player.BannedPlayers.load () static
Definition at line 19 of file BannedPlayers.java.
{
        if (!bans.isEmpty()) {
            bans.clear();
        }
        try {
            bans.addAll(Files.readAllLines(Paths.get(BAN_LIST_PATH)));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
References BAN_LIST_PATH, and bans.
Referenced by com.runehive.RuneHive.start().
unban()
boolean com.runehive.game.world.entity.mob.player.BannedPlayers.unban (String player) static
Definition at line 39 of file BannedPlayers.java.
{
        player = player.toLowerCase();
        if (!bans.remove(player)) {
            return false;
        }
        writeBans();
        return true;
    }
References bans, and writeBans().
writeBans()
void com.runehive.game.world.entity.mob.player.BannedPlayers.writeBans () static private
Definition at line 48 of file BannedPlayers.java.
{
        World.schedule(new Task(1) {
            @Override
            public void execute() {
                try {
                    Files.write(Paths.get(BAN_LIST_PATH), bans, Charset.defaultCharset());
                    cancel();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
    }
References BAN_LIST_PATH, bans, and com.runehive.game.world.World.schedule().
Referenced by ban(), and unban().
Member Data Documentation
BAN_LIST_PATH
final String com.runehive.game.world.entity.mob.player.BannedPlayers.BAN_LIST_PATH = "./data/bans.txt" static private
Definition at line 15 of file BannedPlayers.java.
Referenced by load(), and writeBans().
bans
final List<String> com.runehive.game.world.entity.mob.player.BannedPlayers.bans = new ArrayList<>() static
Definition at line 17 of file BannedPlayers.java.
Referenced by ban(), com.runehive.net.session.LoginSession.evaluate(), load(), unban(), and writeBans().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/BannedPlayers.java