RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm Class Reference
com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm Class Reference
Public Member Functions
void hit (Player attacker, Mob defender, Hit hit)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
boolean canAttack (T attacker, Mob defender)
boolean canOtherAttack (Mob attacker, T defender)
void finishIncoming (Mob attacker, T defender)
void finishOutgoing (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
void hitsplat (T attacker, Mob defender, Hit hit)
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
void onKill (T attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, T defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
void start (T attacker, Mob defender, Hit[] hits)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Static Private Member Functions
static void magma (Player attacker, Mob defender, ZulrahHelm listener)
static void serp (Player attacker, Mob defender, ZulrahHelm listener)
static void tanz (Player attacker, Mob defender, ZulrahHelm listener)
Additional Inherited Members
Static Public Attributes inherited from com.runehive.game.world.entity.combat.attack.listener.SimplifiedListener< T extends Mob >
static final CombatListener< Mob > CANT_ATTACK
Detailed Description
Definition at line 15 of file ZulrahHelm.java.
Member Function Documentation
hit()
void com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.hit (Player attacker, Mob defender, Hit hit)
Definition at line 18 of file ZulrahHelm.java.
{
        if (!defender.isNpc()) {
            return;
        }
        Item helm = attacker.equipment.get(Equipment.HELM_SLOT);
        if (helm == null) {
            return;
        }
        if (helm.matchesId(12_931)) {
            serp(attacker, defender, this);
        } else if (helm.matchesId(13_197)) {
            tanz(attacker, defender, this);
        } else if (helm.matchesId(13_199)) {
            magma(attacker, defender, this);
        }
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.containers.equipment.Equipment.HELM_SLOT, hit(), com.runehive.game.world.entity.mob.Mob.isNpc(), magma(), com.runehive.game.world.items.Item.matchesId(), serp(), and tanz().
Referenced by hit().
magma()
void com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.magma (Player attacker, Mob defender, ZulrahHelm listener) static private
Definition at line 92 of file ZulrahHelm.java.
{
        if (attacker.magmaHelmCharges > 0) {
            attacker.magmaHelmCharges -= 2;
            boolean poisonous = false;
            if (attacker.equipment.hasWeapon()) {
                poisonous = CombatPoisonEffect.getPoisonType(attacker.equipment.getWeapon()).isPresent();
            }
            if (!poisonous && attacker.equipment.hasAmmo()) {
                poisonous = CombatPoisonEffect.getPoisonType(attacker.equipment.get(Equipment.ARROWS_SLOT)).isPresent();
            }
            if (CombatVenomEffect.isVenomous(attacker.equipment.getWeapon())) {
                defender.venom();
            } else if (RandomUtils.success(poisonous ? 0.50 : 1 / 6.0)) {
                defender.venom();
            }
        }
        if (attacker.magmaHelmCharges == 0) {
            attacker.message("Your Magma helm is out of charges.");
            attacker.equipment.set(Equipment.HELM_SLOT, new Item(13_198), true);
            attacker.getCombat().removeListener(listener);
        }
    }
References com.runehive.game.world.items.containers.equipment.Equipment.ARROWS_SLOT, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.hasAmmo(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.HELM_SLOT, com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.isVenomous(), com.runehive.game.world.entity.mob.player.Player.magmaHelmCharges, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.set(), com.runehive.util.RandomUtils.success(), and com.runehive.game.world.entity.mob.Mob.venom().
Referenced by hit().
serp()
void com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.serp (Player attacker, Mob defender, ZulrahHelm listener) static private
Definition at line 38 of file ZulrahHelm.java.
{
        if (attacker.serpentineHelmCharges > 0) {
            attacker.serpentineHelmCharges -= 2;
            boolean poisonous = false;
            if (attacker.equipment.hasWeapon()) {
                poisonous = CombatPoisonEffect.getPoisonType(attacker.equipment.getWeapon()).isPresent();
            }
            if (!poisonous && attacker.equipment.hasAmmo()) {
                poisonous = CombatPoisonEffect.getPoisonType(attacker.equipment.get(Equipment.ARROWS_SLOT)).isPresent();
            }
            if (CombatVenomEffect.isVenomous(attacker.equipment.getWeapon())) {
                defender.venom();
            } else if (RandomUtils.success(poisonous ? 0.50 : 1 / 6.0)) {
                defender.venom();
            }
        }
        if (attacker.serpentineHelmCharges == 0) {
            attacker.message("Your Serpentine helm is out of charges.");
            attacker.equipment.set(Equipment.HELM_SLOT, new Item(12_929), true);
            attacker.getCombat().removeListener(listener);
        }
    }
References com.runehive.game.world.items.containers.equipment.Equipment.ARROWS_SLOT, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.hasAmmo(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.HELM_SLOT, com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.isVenomous(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.player.Player.serpentineHelmCharges, com.runehive.game.world.items.containers.ItemContainer.set(), com.runehive.util.RandomUtils.success(), and com.runehive.game.world.entity.mob.Mob.venom().
Referenced by hit().
tanz()
void com.runehive.game.world.entity.combat.attack.listener.item.ZulrahHelm.tanz (Player attacker, Mob defender, ZulrahHelm listener) static private
Definition at line 65 of file ZulrahHelm.java.
{
        if (attacker.tanzaniteHelmCharges > 0) {
            attacker.tanzaniteHelmCharges -= 2;
            boolean poisonous = false;
            if (attacker.equipment.hasWeapon()) {
                poisonous = CombatPoisonEffect.getPoisonType(attacker.equipment.getWeapon()).isPresent();
            }
            if (!poisonous && attacker.equipment.hasAmmo()) {
                poisonous = CombatPoisonEffect.getPoisonType(attacker.equipment.get(Equipment.ARROWS_SLOT)).isPresent();
            }
            if (CombatVenomEffect.isVenomous(attacker.equipment.getWeapon())) {
                defender.venom();
            } else if (RandomUtils.success(poisonous ? 0.50 : 1 / 6.0)) {
                defender.venom();
            }
        }
        if (attacker.tanzaniteHelmCharges == 0) {
            attacker.message("Your Tanzanite helm is out of charges.");
            attacker.equipment.set(Equipment.HELM_SLOT, new Item(13_196), true);
            attacker.getCombat().removeListener(listener);
        }
    }
References com.runehive.game.world.items.containers.equipment.Equipment.ARROWS_SLOT, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.hasAmmo(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.HELM_SLOT, com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.isVenomous(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.set(), com.runehive.util.RandomUtils.success(), com.runehive.game.world.entity.mob.player.Player.tanzaniteHelmCharges, and com.runehive.game.world.entity.mob.Mob.venom().
Referenced by hit().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/item/ZulrahHelm.java