RuneHive-Game: com.runehive.game.service.StartupService Class Reference
com.runehive.game.service.StartupService Class Reference
An ExecutorService that waits for all its events to finish executing.
Public Member Functions
boolean awaitTermination (long timeout, TimeUnit unit) throws InterruptedException
void awaitUntilFinished (long timeout, TimeUnit timeUnit)
void execute (Runnable command)
int getPendingTaskAmount ()
Gets the number of pending tasks.
boolean isShutdown ()
boolean isTerminated ()
void shutdown ()
List< Runnable > shutdownNow ()
Future<?> submit (Runnable task)
void waitForPendingTasks () throws ExecutionException
Waits for pending tasks to complete.
Package Functions
public< T > List< Future< T > > invokeAll (Collection<? extends Callable< T > > tasks) throws InterruptedException
public< T > List< Future< T > > invokeAll (Collection<? extends Callable< T > > tasks, long timeout, TimeUnit unit) throws InterruptedException
public< T > T invokeAny (Collection<? extends Callable< T > > tasks) throws InterruptedException, ExecutionException
public< T > T invokeAny (Collection<? extends Callable< T > > tasks, long timeout, TimeUnit unit) throws InterruptedException, ExecutionException, TimeoutException
public< T > Future< T > submit (Callable< T > task)
public< T > Future< T > submit (Runnable task, T result)
Private Attributes
BlockingQueue< Future<?> > pendingTasks = new LinkedBlockingQueue<>()
A list of pending tasks.
ExecutorService service = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors())
The service backing this service.
Detailed Description
An ExecutorService that waits for all its events to finish executing.
Author
Graham Edgecombe
Definition at line 13 of file StartupService.java.
Member Function Documentation
awaitTermination()
boolean com.runehive.game.service.StartupService.awaitTermination (long timeout, TimeUnit unit) throws InterruptedException
Definition at line 58 of file StartupService.java.
{
        return service.awaitTermination(timeout, unit);
    }
References service.
awaitUntilFinished()
void com.runehive.game.service.StartupService.awaitUntilFinished (long timeout, TimeUnit timeUnit)
Definition at line 40 of file StartupService.java.
{
        try {
            service.awaitTermination(timeout, timeUnit);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
References service.
execute()
void com.runehive.game.service.StartupService.execute (Runnable command)
Definition at line 134 of file StartupService.java.
{
        service.execute(command);
    }
References service.
getPendingTaskAmount()
int com.runehive.game.service.StartupService.getPendingTaskAmount ()
Gets the number of pending tasks.
Returns
The number of pending tasks.
Definition at line 53 of file StartupService.java.
{
        return pendingTasks.size();
    }
References pendingTasks.
invokeAll() [1/2]
public< T > List< Future< T > > com.runehive.game.service.StartupService.invokeAll (Collection<? extends Callable< T > > tasks) throws InterruptedException package
Definition at line 63 of file StartupService.java.
{
        List<Future<T>> futures = service.invokeAll(tasks);
        for (Future<?> future : futures) {
            pendingTasks.add(future);
        }
        return futures;
    }
References pendingTasks, and service.
invokeAll() [2/2]
public< T > List< Future< T > > com.runehive.game.service.StartupService.invokeAll (Collection<? extends Callable< T > > tasks, long timeout, TimeUnit unit) throws InterruptedException package
Definition at line 72 of file StartupService.java.
{
        List<Future<T>> futures = service.invokeAll(tasks, timeout, unit);
        for (Future<?> future : futures) {
            pendingTasks.add(future);
        }
        return futures;
    }
References pendingTasks, and service.
invokeAny() [1/2]
public< T > T com.runehive.game.service.StartupService.invokeAny (Collection<? extends Callable< T > > tasks) throws InterruptedException, ExecutionException package
Definition at line 82 of file StartupService.java.
{
        return service.invokeAny(tasks);
    }
References service.
invokeAny() [2/2]
public< T > T com.runehive.game.service.StartupService.invokeAny (Collection<? extends Callable< T > > tasks, long timeout, TimeUnit unit) throws InterruptedException, ExecutionException, TimeoutException package
Definition at line 87 of file StartupService.java.
{
        return service.invokeAny(tasks, timeout, unit);
    }
References service.
isShutdown()
boolean com.runehive.game.service.StartupService.isShutdown ()
Definition at line 93 of file StartupService.java.
{
        return service.isShutdown();
    }
References service.
Referenced by waitForPendingTasks().
isTerminated()
boolean com.runehive.game.service.StartupService.isTerminated ()
Definition at line 98 of file StartupService.java.
{
        return service.isTerminated();
    }
References service.
shutdown()
void com.runehive.game.service.StartupService.shutdown ()
Definition at line 103 of file StartupService.java.
{
        service.shutdown();
    }
References service.
shutdownNow()
List< Runnable > com.runehive.game.service.StartupService.shutdownNow ()
Definition at line 108 of file StartupService.java.
{
        return service.shutdownNow();
    }
References service.
submit() [1/3]
public< T > Future< T > com.runehive.game.service.StartupService.submit (Callable< T > task) package
Definition at line 113 of file StartupService.java.
{
        Future<T> future = service.submit(task);
        pendingTasks.add(future);
        return future;
    }
References pendingTasks, and service.
submit() [2/3]
Future<?> com.runehive.game.service.StartupService.submit (Runnable task)
Definition at line 120 of file StartupService.java.
{
        Future<?> future = service.submit(task);
        pendingTasks.add(future);
        return future;
    }
References pendingTasks, and service.
submit() [3/3]
public< T > Future< T > com.runehive.game.service.StartupService.submit (Runnable task, T result) package
Definition at line 127 of file StartupService.java.
{
        Future<T> future = service.submit(task, result);
        pendingTasks.add(future);
        return future;
    }
References pendingTasks, and service.
waitForPendingTasks()
void com.runehive.game.service.StartupService.waitForPendingTasks () throws ExecutionException
Waits for pending tasks to complete.
Exceptions
ExecutionException if an error in a task occurred.
Definition at line 27 of file StartupService.java.
{
        while (pendingTasks.size() > 0) {
            if (isShutdown()) {
                return;
            }
            try {
                pendingTasks.take().get();
            } catch (InterruptedException e) {
                continue;
            }
        }
    }
References isShutdown(), and pendingTasks.
Member Data Documentation
pendingTasks
BlockingQueue<Future<?> > com.runehive.game.service.StartupService.pendingTasks = new LinkedBlockingQueue<>() private
A list of pending tasks.
Definition at line 19 of file StartupService.java.
Referenced by getPendingTaskAmount(), invokeAll(), invokeAll(), submit(), submit(), submit(), and waitForPendingTasks().
service
ExecutorService com.runehive.game.service.StartupService.service = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors()) private
The service backing this service.
Definition at line 16 of file StartupService.java.
Referenced by awaitTermination(), awaitUntilFinished(), execute(), invokeAll(), invokeAll(), invokeAny(), invokeAny(), isShutdown(), isTerminated(), shutdown(), shutdownNow(), submit(), submit(), and submit().
The documentation for this class was generated from the following file:
java/com/runehive/game/service/StartupService.java