RuneHive-Game: com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob > Class Template Reference
com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob > Class Template Reference
Public Member Functions
boolean add (FormulaModifier<? super T > modifier)
void addFirst (FormulaModifier<? super T > modifier)
int modifyAccuracy (T attacker, Mob defender, int roll)
int modifyAggressive (T attacker, Mob defender, int roll)
int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
int modifyAttackLevel (T attacker, Mob defender, int level)
int modifyDamage (T attacker, Mob defender, int damage)
int modifyDefenceLevel (Mob attacker, T defender, int level)
int modifyDefensive (Mob attacker, T defender, int roll)
int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
int modifyMagicLevel (T attacker, Mob defender, int level)
int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
int modifyRangedLevel (T attacker, Mob defender, int level)
int modifyStrengthLevel (T attacker, Mob defender, int level)
boolean remove (FormulaModifier<? super T > modifier)
void removeFirst ()
Private Attributes
final Deque< FormulaModifier<? super T > > modifiers = new LinkedList<>()
Detailed Description
Definition at line 9 of file CombatFormula.java.
Member Function Documentation
add()
boolean com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.add (FormulaModifier<? super T > modifier)
Definition at line 20 of file CombatFormula.java.
{
        return !modifiers.contains(modifier) && modifiers.add(modifier);
    }
References modifiers.
addFirst()
void com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.addFirst (FormulaModifier<? super T > modifier)
Definition at line 12 of file CombatFormula.java.
{
        modifiers.addFirst(modifier);
    }
References modifiers.
modifyAccuracy()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyAccuracy (T attacker, Mob defender, int roll)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 69 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            roll = modifier.modifyAccuracy(attacker, defender, roll);
        }
        return roll;
    }
References modifiers.
modifyAggressive()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyAggressive (T attacker, Mob defender, int roll)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 77 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            roll = modifier.modifyAggressive(attacker, defender, roll);
        }
        return roll;
    }
References modifiers.
modifyAggressiveBonus()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyAggressiveBonus (T attacker, Mob defender, int bonus)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 109 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            bonus = modifier.modifyAggressiveBonus(attacker, defender, bonus);
        }
        return bonus;
    }
References modifiers.
modifyAttackLevel()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyAttackLevel (T attacker, Mob defender, int level)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 29 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            level = modifier.modifyAttackLevel(attacker, defender, level);
        }
        return level;
    }
References modifiers.
modifyDamage()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyDamage (T attacker, Mob defender, int damage)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 93 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            damage = modifier.modifyDamage(attacker, defender, damage);
        }
        return damage;
    }
References modifiers.
modifyDefenceLevel()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyDefenceLevel (Mob attacker, T defender, int level)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 45 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            level = modifier.modifyDefenceLevel(attacker, defender, level);
        }
        return level;
    }
References modifiers.
modifyDefensive()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyDefensive (Mob attacker, T defender, int roll)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 85 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            roll = modifier.modifyDefensive(attacker, defender, roll);
        }
        return roll;
    }
References modifiers.
modifyDefensiveBonus()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyDefensiveBonus (Mob attacker, T defender, int bonus)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 117 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            bonus = modifier.modifyDefensiveBonus(attacker, defender, bonus);
        }
        return bonus;
    }
References modifiers.
modifyMagicLevel()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyMagicLevel (T attacker, Mob defender, int level)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 61 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            level = modifier.modifyMagicLevel(attacker, defender, level);
        }
        return level;
    }
References modifiers.
modifyOffensiveBonus()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyOffensiveBonus (T attacker, Mob defender, int bonus)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 101 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            bonus = modifier.modifyOffensiveBonus(attacker, defender, bonus);
        }
        return bonus;
    }
References modifiers.
modifyRangedLevel()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyRangedLevel (T attacker, Mob defender, int level)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 53 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            level = modifier.modifyRangedLevel(attacker, defender, level);
        }
        return level;
    }
References modifiers.
modifyStrengthLevel()
int com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifyStrengthLevel (T attacker, Mob defender, int level)
Implements com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >.
Definition at line 37 of file CombatFormula.java.
{
        for (FormulaModifier<? super T> modifier : modifiers) {
            level = modifier.modifyStrengthLevel(attacker, defender, level);
        }
        return level;
    }
References modifiers.
remove()
boolean com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.remove (FormulaModifier<? super T > modifier)
Definition at line 24 of file CombatFormula.java.
{
        return modifiers.remove(modifier);
    }
References modifiers.
removeFirst()
void com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.removeFirst ()
Definition at line 16 of file CombatFormula.java.
{
        modifiers.removeFirst();
    }
References modifiers.
Member Data Documentation
modifiers
final Deque<FormulaModifier<? super T> > com.runehive.game.world.entity.combat.formula.CombatFormula< T extends Mob >.modifiers = new LinkedList<>() private
Definition at line 10 of file CombatFormula.java.
Referenced by add(), addFirst(), modifyAccuracy(), modifyAggressive(), modifyAggressiveBonus(), modifyAttackLevel(), modifyDamage(), modifyDefenceLevel(), modifyDefensive(), modifyDefensiveBonus(), modifyMagicLevel(), modifyOffensiveBonus(), modifyRangedLevel(), modifyStrengthLevel(), remove(), and removeFirst().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/formula/CombatFormula.java