RuneHive-Game: com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas Class Reference
com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas Class Reference
Public Member Functions
void execute (Player player, Item item)
Executes the magic spell.
int getLevel ()
Gets the level required to cast spell.
String getName ()
Gets the name of the spell.
Item[] getRunes ()
Gets the runes required to cast the spell.
Detailed Description
Definition at line 15 of file BonesToBananas.java.
Member Function Documentation
execute()
void com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute (Player player, Item item)
Executes the magic spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 33 of file BonesToBananas.java.
{
        if (player.spellbook != Spellbook.MODERN)
            return;
        int bone = 0;
        for (final int bones : Magic.BONES) {
            if (player.inventory.contains(bones)) {
                bone = bones;
                break;
            }
        }
        if (bone == 0) {
            player.send(new SendMessage("You have no bones to do this!"));
            return;
        }
        final int amount = player.inventory.computeAmountForId(bone);
        player.inventory.remove(bone, amount);
        player.inventory.add(new Item(1963, amount), -1, true);
        player.inventory.removeAll(getRunes());
        player.animate(new Animation(722));
        player.graphic(new Graphic(141, true));
        player.skills.addExperience(Skill.MAGIC, 25 * Config.MAGIC_MODIFICATION);
        player.send(new SendMessage("You have converted " + amount + " bones to bananas."));
        RandomEventHandler.trigger(player);
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.content.skill.impl.magic.Magic.BONES, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), getRunes(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.skill.Skill.MAGIC, com.runehive.Config.MAGIC_MODIFICATION, com.runehive.content.skill.impl.magic.Spellbook.MODERN, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.containers.ItemContainer.removeAll(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.mob.player.Player.spellbook, and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
getLevel()
int com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.getLevel ()
Gets the level required to cast spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 28 of file BonesToBananas.java.
{
        return 15;
    }
getName()
String com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.getName ()
Gets the name of the spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 18 of file BonesToBananas.java.
{
        return "Bones to bananas";
    }
getRunes()
Item[] com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.getRunes ()
Gets the runes required to cast the spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 23 of file BonesToBananas.java.
{
        return new Item[] { new Item(557, 2), new Item(555, 2), new Item(561, 1) };
    }
Referenced by execute().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/magic/spell/impl/BonesToBananas.java