RuneHive-Game: dev.advo.fs.net.ondemand.OnDemandResponse Class Reference
dev.advo.fs.net.ondemand.OnDemandResponse Class Reference
Public Member Functions
ChannelBuffer getChunkData ()
FileDescriptor getFileDescriptor ()
int getFileSize ()
OnDemandResponse (FileDescriptor fileDescriptor, int fileSize, ChannelBuffer chunkData)
Private Attributes
final ChannelBuffer chunkData
final FileDescriptor fileDescriptor
final int fileSize
Detailed Description
Definition at line 8 of file OnDemandResponse.java.
Constructor & Destructor Documentation
OnDemandResponse()
dev.advo.fs.net.ondemand.OnDemandResponse.OnDemandResponse (FileDescriptor fileDescriptor, int fileSize, ChannelBuffer chunkData)
Definition at line 14 of file OnDemandResponse.java.
{
        this.fileDescriptor = fileDescriptor;
        this.fileSize = fileSize;
        this.chunkData = chunkData;
    }
References chunkData, fileDescriptor, and fileSize.
Member Function Documentation
getChunkData()
ChannelBuffer dev.advo.fs.net.ondemand.OnDemandResponse.getChunkData ()
Definition at line 28 of file OnDemandResponse.java.
{
        return chunkData;
    }
References chunkData.
Referenced by dev.advo.fs.net.ondemand.OnDemandResponseEncoder.encode().
getFileDescriptor()
FileDescriptor dev.advo.fs.net.ondemand.OnDemandResponse.getFileDescriptor ()
Definition at line 20 of file OnDemandResponse.java.
{
        return fileDescriptor;
    }
References fileDescriptor.
Referenced by dev.advo.fs.net.ondemand.OnDemandResponseEncoder.encode().
getFileSize()
int dev.advo.fs.net.ondemand.OnDemandResponse.getFileSize ()
Definition at line 24 of file OnDemandResponse.java.
{
        return fileSize;
    }
References fileSize.
Referenced by dev.advo.fs.net.ondemand.OnDemandResponseEncoder.encode().
Member Data Documentation
chunkData
final ChannelBuffer dev.advo.fs.net.ondemand.OnDemandResponse.chunkData private
Definition at line 12 of file OnDemandResponse.java.
Referenced by getChunkData(), and OnDemandResponse().
fileDescriptor
final FileDescriptor dev.advo.fs.net.ondemand.OnDemandResponse.fileDescriptor private
Definition at line 10 of file OnDemandResponse.java.
Referenced by getFileDescriptor(), and OnDemandResponse().
fileSize
final int dev.advo.fs.net.ondemand.OnDemandResponse.fileSize private
Definition at line 11 of file OnDemandResponse.java.
Referenced by getFileSize(), and OnDemandResponse().
The documentation for this class was generated from the following file:
java/dev/advo/fs/net/ondemand/OnDemandResponse.java