RuneHive-Game: com.runehive.content.gambling.Gamble Class Reference
com.runehive.content.gambling.Gamble Class Reference abstract
Public Member Functions
Gamble (Player host, Player opponent)
abstract void gamble ()
Player getHost ()
Player getOpponent ()
Public Attributes
int hostScore
Score betwen the players inside the 'gamble'.
int opponentScore
Private Attributes
Player host
Players inside the 'gamble'.
Player opponent
Detailed Description
Definition at line 5 of file Gamble.java.
Constructor & Destructor Documentation
Gamble()
com.runehive.content.gambling.Gamble.Gamble (Player host, Player opponent)
Definition at line 25 of file Gamble.java.
{
        this.host = host;
        this.opponent = opponent;
    }
References host, and opponent.
Member Function Documentation
gamble()
abstract void com.runehive.content.gambling.Gamble.gamble () abstract
Reimplemented in com.runehive.content.gambling.impl.FiftyFive, and com.runehive.content.gambling.impl.FlowerPoker.
Referenced by com.runehive.content.gambling.GambleManager.finish(), com.runehive.content.gambling.GambleManager.give(), and com.runehive.content.gambling.GambleManager.start().
getHost()
Player com.runehive.content.gambling.Gamble.getHost ()
Definition at line 12 of file Gamble.java.
{
        return host;
    }
References host.
Referenced by com.runehive.content.gambling.GambleManager.finish(), com.runehive.content.gambling.impl.FiftyFive.gamble(), com.runehive.content.gambling.impl.FlowerPoker.gamble(), com.runehive.content.gambling.impl.FlowerPoker.plant(), and com.runehive.content.gambling.GambleManager.start().
getOpponent()
Player com.runehive.content.gambling.Gamble.getOpponent ()
Definition at line 16 of file Gamble.java.
{
        return opponent;
    }
References opponent.
Referenced by com.runehive.content.gambling.impl.FiftyFive.gamble(), com.runehive.content.gambling.impl.FlowerPoker.gamble(), and com.runehive.content.gambling.impl.FlowerPoker.plant().
Member Data Documentation
host
Player com.runehive.content.gambling.Gamble.host private
Players inside the 'gamble'.
Definition at line 10 of file Gamble.java.
Referenced by com.runehive.content.gambling.impl.FiftyFive.FiftyFive(), com.runehive.content.gambling.impl.FlowerPoker.FlowerPoker(), Gamble(), and getHost().
hostScore
int com.runehive.content.gambling.Gamble.hostScore
Score betwen the players inside the 'gamble'.
Definition at line 23 of file Gamble.java.
Referenced by com.runehive.content.gambling.impl.FiftyFive.gamble().
opponent
Player com.runehive.content.gambling.Gamble.opponent private
Definition at line 10 of file Gamble.java.
Referenced by com.runehive.content.gambling.impl.FiftyFive.FiftyFive(), com.runehive.content.gambling.impl.FlowerPoker.FlowerPoker(), Gamble(), and getOpponent().
opponentScore
int com.runehive.content.gambling.Gamble.opponentScore
Definition at line 23 of file Gamble.java.
Referenced by com.runehive.content.gambling.impl.FiftyFive.gamble().
The documentation for this class was generated from the following file:
java/com/runehive/content/gambling/Gamble.java