RuneHive-Game: com.runehive.game.world.entity.mob.prayer.PrayerBook Class Reference
com.runehive.game.world.entity.mob.prayer.PrayerBook Class Reference
A PrayerBook which stores prayers.
Public Member Functions
boolean anyActive (Prayer... prayers)
Checks if any given prayers are active.
void deactivate (Prayer... prayers)
Sends the dectivate prayer packet to the client.
void deactivateOverhead ()
int drainAmount (int bonus)
Calculates the amount of prayer points to drain relative to the given game ticks.
Set< Prayer > getEnabled ()
boolean hasOverhead ()
boolean isActive ()
boolean isActive (Prayer... prayers)
Checks if all given prayers are active.
boolean noneActive (Prayer... prayers)
Checks if none of the given prayers are active.
void only (Prayer... prayers)
Activates only the prayers provided.
void reset ()
Iterates through the active prayers and disables them all.
void resetProtection ()
void setAs (PrayerBook book)
Sets all prayers active from another prayer book.
void setOnChange (Consumer< Prayer > sendActivated, Consumer< Prayer > sendDeactivated, Consumer< Prayer > sendOverhead, Consumer< Prayer > sendNoOverhead)
Sets the method of sending the prayer update to the client.
Prayer[] toArray ()
void toggle (Prayer... prayers)
Inverts a prayer's active state.
String toString ()
Public Attributes
transient int drainCounter
The drain counter.
Private Member Functions
void activate (Prayer... prayers)
Sends the activate prayer packet to the client.
void mutate (Set< Prayer > activate, Set< Prayer > deactivate)
Toggles prayers supplied in the activate and deactivate sets.
void onlyOrNone (Prayer... prayers)
Activates only the prayers provided.
Private Attributes
final Set< Prayer > active = EnumSet.noneOf(Prayer.class)
The set of prayers.
transient Consumer< Prayer > sendActivated
The method of sending the activated prayer config id to the client.
transient Consumer< Prayer > sendDeactivated
The method of sending the deactivated prayer config id to the client.
transient Consumer< Prayer > sendNoOverhead
The method of removing the overhead prayer from the client.
transient Consumer< Prayer > sendOverhead
The method of sending the overhead prayer to the client.
Detailed Description
A PrayerBook which stores prayers.
Prayers in a PrayerBook can be activated and deactivated.
Author
Michael | Chex
Definition at line 12 of file PrayerBook.java.
Member Function Documentation
activate()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.activate (Prayer... prayers) private
Sends the activate prayer packet to the client.
Head icons will also be activated.
Parameters
prayers An array of prayers to activate.
Definition at line 117 of file PrayerBook.java.
{
        for (Prayer prayer : prayers) {
            if (!active.add(prayer) || sendActivated == null) continue;
            sendActivated.accept(prayer);
            if (sendOverhead != null && prayer.is(Prayer.Type.OVERHEAD)) {
                sendOverhead.accept(prayer);
            }
        }
    }
References active, com.runehive.game.world.entity.mob.prayer.Prayer.Type.OVERHEAD, sendActivated, and sendOverhead.
Referenced by mutate(), only(), and toggle().
anyActive()
boolean com.runehive.game.world.entity.mob.prayer.PrayerBook.anyActive (Prayer... prayers)
Checks if any given prayers are active.
Parameters
prayers The prayers to check.
Returns
True if any prayer is active.
Definition at line 67 of file PrayerBook.java.
{
        for (Prayer prayer : prayers)
            if (active.contains(prayer)) return true;
        return false;
    }
References active.
deactivate()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.deactivate (Prayer... prayers)
Sends the dectivate prayer packet to the client.
Head icons will also be deactivated.
Parameters
prayers An array of prayers to deactivate.
Definition at line 133 of file PrayerBook.java.
{
        for (Prayer prayer : prayers) {
            if (!active.remove(prayer) || sendDeactivated == null) continue;
            sendDeactivated.accept(prayer);
            if (sendNoOverhead != null && prayer.is(Prayer.Type.OVERHEAD)) {
                sendNoOverhead.accept(prayer);
            }
        }
    }
References active, com.runehive.game.world.entity.mob.prayer.Prayer.Type.OVERHEAD, sendDeactivated, and sendNoOverhead.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.attack(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), deactivateOverhead(), mutate(), only(), reset(), resetProtection(), and toggle().
deactivateOverhead()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.deactivateOverhead ()
Definition at line 53 of file PrayerBook.java.
{
        for (Prayer prayer : Prayer.OVERHEAD) {
            if (isActive(prayer)) {
                deactivate(prayer);
            }
        }
    }
References deactivate(), isActive(), and com.runehive.game.world.entity.mob.prayer.Prayer.OVERHEAD.
drainAmount()
int com.runehive.game.world.entity.mob.prayer.PrayerBook.drainAmount (int bonus)
Calculates the amount of prayer points to drain relative to the given game ticks.
Parameters
bonus The current prayer bonus.
Returns
The amount of prayer points to drain.
Definition at line 192 of file PrayerBook.java.
{
        if (active.isEmpty())
            return 0;
        int effect = 0, amount = 0;
        int resistance = 60 + 2 * bonus;
        for (Prayer prayer : active) {
            effect += prayer.getDrainRate();
        }
        drainCounter += effect;
        if (drainCounter > resistance) {
            amount = drainCounter / resistance;
            drainCounter -= amount * resistance;
        }
        return amount;
    }
References active, and drainCounter.
getEnabled()
Set< Prayer > com.runehive.game.world.entity.mob.prayer.PrayerBook.getEnabled ()
Definition at line 231 of file PrayerBook.java.
{
        return active;
    }
References active.
hasOverhead()
boolean com.runehive.game.world.entity.mob.prayer.PrayerBook.hasOverhead ()
Definition at line 44 of file PrayerBook.java.
{
        for (Prayer prayer : Prayer.OVERHEAD) {
            if (isActive(prayer)) {
                return true;
            }
        }
        return false;
    }
References isActive(), and com.runehive.game.world.entity.mob.prayer.Prayer.OVERHEAD.
isActive() [1/2]
boolean com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive ()
Definition at line 227 of file PrayerBook.java.
{
        return !active.isEmpty();
    }
References active.
Referenced by deactivateOverhead(), hasOverhead(), onlyOrNone(), and resetProtection().
isActive() [2/2]
boolean com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive (Prayer... prayers)
Checks if all given prayers are active.
Parameters
prayers The prayers to check.
Returns
True if the prayer is active.
Definition at line 38 of file PrayerBook.java.
{
        for (Prayer prayer : prayers)
            if (!active.contains(prayer)) return false;
        return true;
    }
References active.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect.apply(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.block(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getPrayerBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getPrayerBonus(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonusDefender(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerDefenseBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerDefenseBonus(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.handleCombat(), com.runehive.content.bot.botclass.impl.PureMelee.handleCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.handleCombat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.handleCombat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.handleCombat(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MeleeAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MagicAttack.hitsplat(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.hitsplat(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDamage(), com.runehive.content.ItemsKeptOnDeath.open(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.withinDistance().
mutate()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.mutate (Set< Prayer > activate, Set< Prayer > deactivate) private
Toggles prayers supplied in the activate and deactivate sets.
Parameters
activate A set of prayers to activate.
deactivate A set of prayers to deactivate.
Definition at line 180 of file PrayerBook.java.
{
        deactivate(deactivate.toArray(new Prayer[deactivate.size()]));
        activate(activate.toArray(new Prayer[activate.size()]));
    }
References activate(), and deactivate().
Referenced by only(), and toggle().
noneActive()
boolean com.runehive.game.world.entity.mob.prayer.PrayerBook.noneActive (Prayer... prayers)
Checks if none of the given prayers are active.
Parameters
prayers the prayers to check
Returns
true if none of the given prayers are active
Definition at line 79 of file PrayerBook.java.
{
        for (Prayer prayer : prayers)
            if (active.contains(prayer)) return false;
        return true;
    }
References active.
only()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.only (Prayer... prayers)
Activates only the prayers provided.
Any currently active prayers will be deactivated.
Parameters
prayers The prayers to toggle.
Definition at line 103 of file PrayerBook.java.
{
        List<Prayer> list = Arrays.asList(prayers);
        Set<Prayer> activate = new HashSet<>(list);
        Set<Prayer> deactivate = new HashSet<>(active);
        deactivate.removeAll(activate);
        mutate(activate, deactivate);
    }
References activate(), active, deactivate(), and mutate().
Referenced by onlyOrNone(), and com.runehive.content.preset.PresetManager.upload().
onlyOrNone()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.onlyOrNone (Prayer... prayers) private
Activates only the prayers provided.
Any currently active prayers will be deactivated. If all the prayers are already active, then they will be deactivated, along with any other active prayer.
Parameters
prayers The prayers to toggle.
Definition at line 92 of file PrayerBook.java.
{
        if (isActive(prayers)) reset();
        else only(prayers);
    }
References isActive(), only(), and reset().
Referenced by setAs().
reset()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.reset ()
Iterates through the active prayers and disables them all.
Definition at line 223 of file PrayerBook.java.
{
        deactivate(active.toArray(new Prayer[active.size()]));
    }
References active, and deactivate().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.PinkDragonfireAttack.hitsplat(), onlyOrNone(), and com.runehive.content.lms.LMSGame.reset().
resetProtection()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.resetProtection ()
Definition at line 213 of file PrayerBook.java.
{
        if (isActive(Prayer.PROTECT_FROM_MAGIC))
            deactivate(Prayer.PROTECT_FROM_MAGIC);
        if (isActive(Prayer.PROTECT_FROM_MELEE))
            deactivate(Prayer.PROTECT_FROM_MELEE);
        if (isActive(Prayer.PROTECT_FROM_RANGE))
            deactivate(Prayer.PROTECT_FROM_RANGE);
    }
References deactivate(), isActive(), com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MAGIC, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MELEE, and com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_RANGE.
setAs()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.setAs (PrayerBook book)
Sets all prayers active from another prayer book.
Parameters
book The other book.
Definition at line 170 of file PrayerBook.java.
{
        onlyOrNone(book.toArray());
    }
References onlyOrNone(), and toArray().
setOnChange()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.setOnChange (Consumer< Prayer > sendActivated, Consumer< Prayer > sendDeactivated, Consumer< Prayer > sendOverhead, Consumer< Prayer > sendNoOverhead)
Sets the method of sending the prayer update to the client.
Parameters
sendActivated The consumer that sends the activated prayer update to the client.
sendDeactivated The consumer that sends the deactivated prayer update to the client.
sendOverhead The consumer that sends the prayer head icon update to the client.
sendNoOverhead The consumer that removes the prayer head icon from the client.
Definition at line 253 of file PrayerBook.java.
{
        this.sendActivated = sendActivated;
        this.sendDeactivated = sendDeactivated;
        this.sendOverhead = sendOverhead;
        this.sendNoOverhead = sendNoOverhead;
    }
References sendActivated, sendDeactivated, sendNoOverhead, and sendOverhead.
toArray()
Prayer[] com.runehive.game.world.entity.mob.prayer.PrayerBook.toArray ()
Returns
an array of active prayers.
Definition at line 236 of file PrayerBook.java.
{
        if (active.isEmpty()) return new Prayer[0];
        return active.toArray(new Prayer[active.size()]);
    }
References active.
Referenced by setAs().
toggle()
void com.runehive.game.world.entity.mob.prayer.PrayerBook.toggle (Prayer... prayers)
Inverts a prayer's active state.
If the prayer is active, then the prayer will be deactivated. If the prayer is inactive, then the prayer will be activated. Activating some prayers will cause others to deactivate based on their Prayer.Type.
Parameters
prayers A list of prayers to toggle.
Definition at line 151 of file PrayerBook.java.
{
        Set<Prayer> activate = new HashSet<>();
        Set<Prayer> deactivate = new HashSet<>();
        for (Prayer prayer : prayers) {
            if (deactivate.contains(prayer)) continue;
            if (!active.contains(prayer)) {
                deactivate.addAll(prayer.toDeactivate());
                activate.add(prayer);
            } else deactivate.add(prayer);
        }
        deactivate.removeAll(activate);
        mutate(activate, deactivate);
    }
References activate(), active, deactivate(), and mutate().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.block().
toString()
String com.runehive.game.world.entity.mob.prayer.PrayerBook.toString ()
Definition at line 261 of file PrayerBook.java.
{
        return "PrayerBook[active=" + active.toString() + "]";
    }
References active.
Member Data Documentation
active
final Set<Prayer> com.runehive.game.world.entity.mob.prayer.PrayerBook.active = EnumSet.noneOf(Prayer.class) private
The set of prayers.
Definition at line 15 of file PrayerBook.java.
Referenced by activate(), anyActive(), deactivate(), drainAmount(), getEnabled(), isActive(), isActive(), noneActive(), only(), reset(), toArray(), toggle(), and toString().
drainCounter
transient int com.runehive.game.world.entity.mob.prayer.PrayerBook.drainCounter
The drain counter.
Definition at line 30 of file PrayerBook.java.
Referenced by drainAmount().
sendActivated
transient Consumer<Prayer> com.runehive.game.world.entity.mob.prayer.PrayerBook.sendActivated private
The method of sending the activated prayer config id to the client.
Definition at line 18 of file PrayerBook.java.
Referenced by activate(), and setOnChange().
sendDeactivated
transient Consumer<Prayer> com.runehive.game.world.entity.mob.prayer.PrayerBook.sendDeactivated private
The method of sending the deactivated prayer config id to the client.
Definition at line 21 of file PrayerBook.java.
Referenced by deactivate(), and setOnChange().
sendNoOverhead
transient Consumer<Prayer> com.runehive.game.world.entity.mob.prayer.PrayerBook.sendNoOverhead private
The method of removing the overhead prayer from the client.
Definition at line 27 of file PrayerBook.java.
Referenced by deactivate(), and setOnChange().
sendOverhead
transient Consumer<Prayer> com.runehive.game.world.entity.mob.prayer.PrayerBook.sendOverhead private
The method of sending the overhead prayer to the client.
Definition at line 24 of file PrayerBook.java.
Referenced by activate(), and setOnChange().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/prayer/PrayerBook.java