RuneHive-Game: com.runehive.util.tools.wiki.impl.NpcDefParser Class Reference
com.runehive.util.tools.wiki.impl.NpcDefParser Class Reference
Public Member Functions
NpcDefParser ()
Public Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
void begin () throws InterruptedException
Begins parsing wiki tables for all the names provided.
WikiTableParser (LinkedList< WikiTable > tables)
Constructs a new WikiTableParser object.
Static Public Member Functions
static void main (String[] args) throws InterruptedException
Protected Member Functions
void finish ()
Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
void execute (Runnable runnable)
Static Private Member Functions
static LinkedList< WikiTable > generateTables ()
Additional Inherited Members
Static Protected Member Functions inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
static void writeToJson (String name, JsonElement array)
Writes the parsed wiki dump to a json file in ./data/wiki named as the name parameter.
Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
final LinkedList< WikiTable > tables
The WikiTable list to parse.
Static Protected Attributes inherited from com.runehive.util.tools.wiki.parser.WikiTableParser
static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create()
The gson object.
static final String WIKI_LINK = "http://oldschoolrunescape.wikia.com/wiki/"
The path to the wiki page address.
Detailed Description
Definition at line 11 of file NpcDefParser.java.
Constructor & Destructor Documentation
NpcDefParser()
com.runehive.util.tools.wiki.impl.NpcDefParser.NpcDefParser ()
Definition at line 13 of file NpcDefParser.java.
{
        super(generateTables());
    }
References generateTables().
Referenced by main().
Member Function Documentation
finish()
void com.runehive.util.tools.wiki.impl.NpcDefParser.finish () protected
Reimplemented from com.runehive.util.tools.wiki.parser.WikiTableParser.
Definition at line 35 of file NpcDefParser.java.
{
    }
generateTables()
LinkedList< WikiTable > com.runehive.util.tools.wiki.impl.NpcDefParser.generateTables () static private
Definition at line 17 of file NpcDefParser.java.
{
        LinkedList<WikiTable> tables = new LinkedList<>();
        tables.add(new WikiTable("http://oldschoolrunescape.wikia.com/wiki/King_Black_Dragon") {
            @Override
            protected void parseDocument(Document document) {
                Elements infobox = document.select(".wikitable.infobox");
                Elements desc = infobox.select("td");
                System.out.println(desc.tagName("text-align:center").text());
                for (Element child : desc) {
                    System.out.println(child.text());
                }
            }
        });
        return tables;
    }
References com.runehive.util.tools.wiki.parser.WikiTableParser.tables.
Referenced by NpcDefParser().
main()
void com.runehive.util.tools.wiki.impl.NpcDefParser.main (String[] args) throws InterruptedException static
Definition at line 39 of file NpcDefParser.java.
{
        NpcDefParser parser = new NpcDefParser();
        parser.begin();
    }
References NpcDefParser().
The documentation for this class was generated from the following file:
java/com/runehive/util/tools/wiki/impl/NpcDefParser.java