RuneHive-Game: com.runehive.content.skill.impl.mining.MiningAction Class Reference
com.runehive.content.skill.impl.mining.MiningAction Class Reference
Created by Daniel on 2017-12-18.
Public Member Functions
void execute ()
A function representing the unit of work that will be carried out.
String getName ()
Gets the name of this action.
WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
boolean prioritized ()
Determines if this action is prioritized.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Protected Member Functions
boolean canSchedule ()
A function executed on registration.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
Package Functions
MiningAction (Player player, GameObject object, OreData ore, PickaxeData pickaxe)
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Private Member Functions
void handleCelestialRing (int oreId)
boolean mine ()
Private Attributes
final GameObject object
final OreData ore
final PickaxeData pickaxe
Detailed Description
Created by Daniel on 2017-12-18.
Definition at line 32 of file MiningAction.java.
Constructor & Destructor Documentation
MiningAction()
com.runehive.content.skill.impl.mining.MiningAction.MiningAction (Player player, GameObject object, OreData ore, PickaxeData pickaxe) package
Definition at line 37 of file MiningAction.java.
{
        super(player, 3, false);
        this.object = object;
        this.ore = ore;
        this.pickaxe = pickaxe;
    }
References object, ore, and pickaxe.
Member Function Documentation
canSchedule()
boolean com.runehive.content.skill.impl.mining.MiningAction.canSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 150 of file MiningAction.java.
{
        return !getMob().skills.get(Skill.MINING).isDoingSkill();
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), and com.runehive.game.world.entity.skill.Skill.MINING.
execute()
void com.runehive.content.skill.impl.mining.MiningAction.execute ()
A function representing the unit of work that will be carried out.
Reimplemented from com.runehive.game.task.Task.
Definition at line 164 of file MiningAction.java.
{
        if (!getMob().skills.get(Skill.MINING).isDoingSkill()) {
            cancel();
            return;
        }
        if (object == null || !object.active() || object.getGenericAttributes() == null) {
            cancel();
            return;
        }
        if (!mine()) {
            cancel();
        }
    }
References com.runehive.game.task.Task.cancel(), com.runehive.game.action.Action< T extends Mob >.getMob(), mine(), and com.runehive.game.world.entity.skill.Skill.MINING.
getName()
String com.runehive.content.skill.impl.mining.MiningAction.getName ()
Gets the name of this action.
Returns
The name of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 191 of file MiningAction.java.
{
        return "mining-action";
    }
Referenced by mine().
getWalkablePolicy()
WalkablePolicy com.runehive.content.skill.impl.mining.MiningAction.getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 186 of file MiningAction.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
handleCelestialRing()
void com.runehive.content.skill.impl.mining.MiningAction.handleCelestialRing (int oreId) private
Definition at line 125 of file MiningAction.java.
{
        if (!getMob().equipment.containsAny(25541, 25545)) {
            return;
        }
        if (getMob().celestialRingCharges <= 0) {
            getMob().equipment.replace(25541, 25539, true);
            return;
        }
        if (Utility.hasOneOutOf(10)) {
            if(oreId == 453 && getMob().inventory.contains(24480) && getMob().coalBag.container.hasCapacityFor(new Item(oreId))) {
                getMob().coalBag.container.add(new Item(oreId));
            } else {
                getMob().inventory.add(oreId, 1);
            }
            getMob().skills.addExperience(Skill.MINING, ore.experience * Config.MINING_MODIFICATION);
            getMob().message("You receive an additional ore from your Celestial ring.");
        }
        //always remove a charge, even if additional ore is not received
        getMob().celestialRingCharges--;
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), com.runehive.util.Utility.hasOneOutOf(), com.runehive.game.world.entity.skill.Skill.MINING, com.runehive.Config.MINING_MODIFICATION, and ore.
Referenced by mine().
mine()
boolean com.runehive.content.skill.impl.mining.MiningAction.mine () private
Definition at line 44 of file MiningAction.java.
{
        if(!getMob().equipment.containsAny(Equipment.PICKAXES) && !getMob().inventory.containsAny(Equipment.PICKAXES)) {
            getMob().message("You need a pickaxe to mine this rock.");
            getMob().animate(Animation.RESET);
            return false;
        }
        if (getMob().inventory.getFreeSlots() == 0) {
            getMob().dialogueFactory.sendStatement("You can't carry anymore ore.").execute();
            getMob().animate(Animation.RESET);
            return false;
        }
        getMob().animate(pickaxe.animation);
        if (Mining.success(getMob(), ore, pickaxe)) {
            if (object == null || !object.active()) {
                return false;
            }
            int harvest = ore.ore;
            boolean gem = harvest == -1;
            if (gem) {
                harvest = Mining.GEM_ITEMS.next().getId();
            }
            SmeltingData smeltingData = SmeltingData.getSmeltData(harvest);
            boolean combust = smeltingData != null && pickaxe == PickaxeData.INFERNO_ADZE && Utility.random(3) == 0;
            if(!combust) {
                if (harvest == 453 && getMob().inventory.contains(24480) && getMob().coalBag.container.hasCapacityFor(new Item(harvest)))
                    getMob().coalBag.container.add(new Item(harvest));
                else
                    getMob().inventory.add(harvest, 1);
            } else {
                harvest = smeltingData.produced[0].getId();// Bar
                getMob().skills.addExperience(Skill.SMITHING, ore.infernalExperience * Config.SMITHING_MODIFICATION);
                getMob().inventory.add(harvest, 1);
            }
            getMob().skills.addExperience(Skill.MINING, ore.experience * Config.MINING_MODIFICATION);
            getMob().playerAssistant.activateSkilling(1);
            RandomEventHandler.trigger(getMob());
            Pets.onReward(getMob(), PetData.ROCK_GOLEM);
            AchievementHandler.activate(getMob(), AchievementKey.MINNING);
            if (ore == OreData.RUNITE) {
                getMob().forClan(channel -> channel.activateTask(ClanTaskKey.RUNITE_ORES, getMob().getName()));
            }
            if ((SkillCape.isEquipped(getMob(), SkillCape.MINING) || getMob().prestige.hasPerk(PrestigePerk.THE_ROCK)) && RandomUtils.success(.10)) {
                getMob().inventory.addOrDrop(new Item(harvest, 1));
            }
            if (!gem) { handleCelestialRing(harvest); }
            int base_chance = ore.ordinal() * 45;
            int modified_chance = /*getMob().equipment.isWearingChargedGlory() ? (int) (base_chance / 2.2) :*/ base_chance;
            if (Utility.random(modified_chance) == 1) {
                if (getMob().inventory.getFreeSlots() != 0 && !gem) {
                    Item item = Mining.GEM_ITEMS.next();
                    getMob().inventory.add(item);
                    getMob().send(new SendMessage("You have found " + Utility.getAOrAn(item.getName()) + " " + item.getName() + "."));
                    AchievementHandler.activate(getMob(), AchievementKey.MINNING);
                }
            }
            if (object.active() && (!ore.equals(OreData.RUNE_ESSENCE) && Utility.random(8) <= 0 && !Area.inSuperDonatorZone(object) && !Area.inRegularDonatorZone(object))) {
                this.cancel();
                getMob().resetAnimation();
                object.getGenericAttributes().set("ores", -1);
                getMob().skills.get(Skill.MINING).setDoingSkill(false);
                getMob().animate(Animation.RESET, true);
                World.schedule(new ObjectReplacementEvent(object, ore.replacement, ore.respawn, () -> {
                    object.getGenericAttributes().set("ores", ore.oreCount);
                }));
            }
        }
        return true;
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.task.Task.cancel(), com.runehive.content.skill.impl.mining.Mining.GEM_ITEMS, com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.items.Item.getId(), com.runehive.game.action.Action< T extends Mob >.getMob(), getName(), com.runehive.game.world.items.Item.getName(), com.runehive.content.skill.impl.smithing.SmeltingData.getSmeltData(), handleCelestialRing(), com.runehive.content.skill.impl.mining.PickaxeData.INFERNO_ADZE, com.runehive.game.world.position.Area.inRegularDonatorZone(), com.runehive.game.world.position.Area.inSuperDonatorZone(), com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.content.skillcape.SkillCape.MINING, com.runehive.game.world.entity.skill.Skill.MINING, com.runehive.Config.MINING_MODIFICATION, com.runehive.content.achievement.AchievementKey.MINNING, com.runehive.content.pet.Pets.onReward(), ore, pickaxe, com.runehive.game.world.items.containers.equipment.Equipment.PICKAXES, com.runehive.content.skill.impl.smithing.SmeltingData.produced, com.runehive.util.Utility.random(), com.runehive.game.Animation.RESET, com.runehive.content.pet.PetData.ROCK_GOLEM, com.runehive.content.skill.impl.mining.OreData.RUNE_ESSENCE, com.runehive.content.skill.impl.mining.OreData.RUNITE, com.runehive.content.clanchannel.content.ClanTaskKey.RUNITE_ORES, com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.skill.Skill.SMITHING, com.runehive.Config.SMITHING_MODIFICATION, com.runehive.content.skill.impl.mining.Mining.success(), com.runehive.util.RandomUtils.success(), com.runehive.content.prestige.PrestigePerk.THE_ROCK, and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
Referenced by execute().
onCancel()
void com.runehive.content.skill.impl.mining.MiningAction.onCancel (boolean logout) protected
A function executed on cancellation.
Reimplemented from com.runehive.game.task.Task.
Definition at line 180 of file MiningAction.java.
{
        getMob().resetFace();
        getMob().skills.get(Skill.MINING).setDoingSkill(false);
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), and com.runehive.game.world.entity.skill.Skill.MINING.
onSchedule()
void com.runehive.content.skill.impl.mining.MiningAction.onSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 155 of file MiningAction.java.
{
        if (!object.getGenericAttributes().has("ores")) {
            object.getGenericAttributes().set("ores", ore.oreCount);
        }
        getMob().animate(pickaxe.animation);
    }
References com.runehive.game.action.Action< T extends Mob >.getMob(), ore, and pickaxe.
Member Data Documentation
object
final GameObject com.runehive.content.skill.impl.mining.MiningAction.object private
Definition at line 33 of file MiningAction.java.
Referenced by MiningAction().
ore
final OreData com.runehive.content.skill.impl.mining.MiningAction.ore private
Definition at line 34 of file MiningAction.java.
Referenced by handleCelestialRing(), mine(), MiningAction(), and onSchedule().
pickaxe
final PickaxeData com.runehive.content.skill.impl.mining.MiningAction.pickaxe private
Definition at line 35 of file MiningAction.java.
Referenced by mine(), MiningAction(), and onSchedule().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/mining/MiningAction.java