RuneHive-Game: com.runehive.game.world.entity.mob.player.PlayerAssistant Class Reference
com.runehive.game.world.entity.mob.player.PlayerAssistant Class Reference
Method handles small methods for players that do not have any parent class.
Public Member Functions
void activateSkilling (int amount)
boolean busy ()
Checks if player is busy.
boolean checkSendString (String text, int id)
Checks if the string is already stored in the list.
void claimIronmanArmour ()
void clearSendStrings ()
Clears the send strings.
boolean contains (Item item)
void copy (Player other)
Copy's the inventory and equipment of another player.
void destroyItem (Item item, int slot)
Handles sending the destroy item dialogue.
void drainPrayer (int amount)
int getMaxHit (Mob defender, CombatType type)
Gets the max hit of a combat type.
int getMaxSkillCount ()
Gets the total amount of 99s the player has.
CombatStrategy< Player > getStrategy ()
Handles getting the combat strategy.
ValueIcon getValueIcon (Player player)
void handleDestroyItem ()
Handles destroying the item.
int instance ()
Gets the instanced height for player.
String kdr ()
Gets the KDR of the player.
final void login ()
Handles initializing all the player assistant methods on login.
void moveCamera (Position position, int resetDelay)
long networth ()
long networth (ItemContainer... containers)
Gets the net worth of the player.
void reset ()
Resets the player's variables.
void resetEffects ()
Reset's all the player's activated effects.
void restore ()
Resets the player's variables.
void sequence ()
Handles the method that will occur on sequence.
void setPrayer ()
Sets the prayer book.
final void setSidebar (boolean disabled)
Sends all the side-bar identifications to the Player's client.
final void setSidebar (boolean disabled, boolean login)
void setValueIcon ()
void setWidget ()
Sends all the widget data to the client.
void transform (int npc)
Tranforms player into npc.
void useROW ()
double weight ()
Gets the total carried weight of the player.
Package Functions
String getCombatRange ()
PlayerAssistant (Player player)
Creates a new PlayerAssistant
void welcomeScreen ()
Handles displaying the welcome itemcontainer.
Private Member Functions
int getROWIndex (int item)
void initialize ()
initializes the player's random bs.
void prayerDrain ()
Handles draining prayer.
void run ()
Handles the running.
void runRestore ()
Handles restoring the run energy.
void setActivity ()
Sets the activity for the player.
void setAttribute ()
Sets all the player attributes.
void setContextMenu ()
Sends the context menu to the Player's context.
void setEffects ()
Sets the effects for the player.
void skillRestore ()
Handles restoration of skills.
void updateSpecial ()
Updates the special amount.
Private Attributes
Map< Integer, TinterfaceText > interfaceText = new HashMap<>()
Holds itemcontainer strings.
final Player player
The player instance.
Static Private Attributes
static final int[] RING_OF_WEALTH
Detailed Description
Method handles small methods for players that do not have any parent class.
Author
Daniel | Obey
Definition at line 70 of file PlayerAssistant.java.
Constructor & Destructor Documentation
PlayerAssistant()
com.runehive.game.world.entity.mob.player.PlayerAssistant.PlayerAssistant (Player player) package
Creates a new PlayerAssistant
Definition at line 79 of file PlayerAssistant.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
activateSkilling()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling (int amount)
Definition at line 392 of file PlayerAssistant.java.
{
        if (Utility.hasOneOutOf(30)) {
            player.skillingPoints += amount;
            player.message("<col=D4379A>You have earned " + amount + " skilling point" + (amount > 1 ? "" : "s") + ". You now have a total of " + Utility.formatDigits(player.skillingPoints) + ".");
        }
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.hasOneOutOf(), and player.
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.cooking.Cooking.cook(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), and com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards().
busy()
boolean com.runehive.game.world.entity.mob.player.PlayerAssistant.busy ()
Checks if player is busy.
Definition at line 694 of file PlayerAssistant.java.
{
        return !player.interfaceManager.isMainClear() || player.isDead() || player.newPlayer ||
                player.needsStarter || player.locking.locked() || player.inActivity(ActivityType.DUEL_ARENA);
    }
References com.runehive.content.activity.ActivityType.DUEL_ARENA, and player.
Referenced by com.runehive.content.RoyaltyProgram.open(), and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
checkSendString()
boolean com.runehive.game.world.entity.mob.player.PlayerAssistant.checkSendString (String text, int id)
Checks if the string is already stored in the list.
Definition at line 730 of file PlayerAssistant.java.
{
        if (!interfaceText.containsKey(id)) {
            interfaceText.put(id, new TinterfaceText(text, id));
            return true;
        }
        TinterfaceText t = interfaceText.get(id);
        if (t.currentState.equals(text))
            return false;
        t.currentState = text;
        return true;
    }
References com.runehive.util.TinterfaceText.currentState, and interfaceText.
Referenced by com.runehive.net.packet.out.SendString.encode().
claimIronmanArmour()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.claimIronmanArmour ()
Definition at line 445 of file PlayerAssistant.java.
{
        if (player.right == PlayerRight.IRONMAN) {
            player.inventory.addOrDrop(new Item(12810), new Item(12811), new Item(12812));
        } else if (player.right == PlayerRight.ULTIMATE_IRONMAN) {
            player.inventory.addOrDrop(new Item(12813), new Item(12814), new Item(12815));
        } else if (player.right == PlayerRight.HARDCORE_IRONMAN) {
            player.inventory.addOrDrop(new Item(20792), new Item(20794), new Item(20796));
        }
        else {
            player.message("You must be an ironman to claim this armour.");
        }
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.HARDCORE_IRONMAN, com.runehive.game.world.entity.mob.player.PlayerRight.IRONMAN, player, and com.runehive.game.world.entity.mob.player.PlayerRight.ULTIMATE_IRONMAN.
clearSendStrings()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.clearSendStrings ()
Clears the send strings.
Definition at line 743 of file PlayerAssistant.java.
{
        interfaceText.clear();
    }
References interfaceText.
contains()
boolean com.runehive.game.world.entity.mob.player.PlayerAssistant.contains (Item item)
Definition at line 605 of file PlayerAssistant.java.
{
        return player.inventory.contains(item) || player.equipment.contains(item) || player.bank.contains(item);
    }
References player.
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop().
copy()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.copy (Player other)
Copy's the inventory and equipment of another player.
Definition at line 459 of file PlayerAssistant.java.
{
        Item[] inventory = other.inventory.toArray();
        Item[] equipment = other.equipment.toArray();
        player.inventory.clear(false);
        player.equipment.clear(false);
        player.inventory.addAll(inventory);
        player.equipment.manualWearAll(equipment);
        player.inventory.refresh();
        player.equipment.login();
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.inventory, player, and com.runehive.game.world.items.containers.ItemContainer.toArray().
destroyItem()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.destroyItem (Item item, int slot)
Handles sending the destroy item dialogue.
Definition at line 544 of file PlayerAssistant.java.
{
        player.send(new SendItemOnInterfaceSlot(14171, item, 0));
        player.send(new SendString("Are you sure you want to destroy this item?", 14174));
        player.send(new SendString("Yes.", 14175));
        player.send(new SendString("No.", 14176));
        player.send(new SendString("", 14177));
        player.send(new SendString(/*item.getDestroyMessage()*/"Doing this action is permanent!", 14182));
        player.send(new SendString("", 14183));
        player.send(new SendString(item.getName(), 14184));
        player.send(new SendChatBoxInterface(14170));
        player.attributes.set("DESTROY_ITEM_KEY", slot);
    }
References com.runehive.game.world.items.Item.getName(), and player.
drainPrayer()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.drainPrayer (int amount)
Definition at line 431 of file PlayerAssistant.java.
{
        if (amount > 0) {
            Skill skill = player.skills.get(Skill.PRAYER);
            skill.modifyLevel(level -> level - amount, 0, skill.getLevel());
            player.skills.refresh(Skill.PRAYER);
            if (skill.getLevel() == 0) {
                player.send(new SendMessage("You have run out of prayer points; you must recharge at an altar."));
                player.prayer.reset();
                player.getPlayer().send(new SendConfig(659, 0));
            }
        }
    }
References player, and com.runehive.game.world.entity.skill.Skill.PRAYER.
Referenced by com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), and prayerDrain().
getCombatRange()
String com.runehive.game.world.entity.mob.player.PlayerAssistant.getCombatRange () package
Definition at line 689 of file PlayerAssistant.java.
{
        return (player.skills.getCombatLevel() - 10 < 3 ? 3 : player.skills.getCombatLevel() - 10) + " - " + (player.skills.getCombatLevel() + 10 > 126 ? 126 : player.skills.getCombatLevel() + 10);
    }
References player.
getMaxHit()
int com.runehive.game.world.entity.mob.player.PlayerAssistant.getMaxHit (Mob defender, CombatType type)
Gets the max hit of a combat type.
Definition at line 616 of file PlayerAssistant.java.
{
        player.getCombat().addFirst(player.getStrategy());
        int max = FormulaFactory.getModifiedMaxHit(player, defender, type);
        player.getCombat().removeFirst();
        return max;
    }
References com.runehive.game.world.entity.combat.attack.FormulaFactory.getModifiedMaxHit(), and player.
Referenced by com.runehive.content.bot.botclass.impl.AGSRuneMelee.eat(), com.runehive.content.bot.botclass.impl.PureMelee.eat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.eat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.eat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.eat(), com.runehive.content.bot.botclass.impl.PureMelee.pot(), com.runehive.content.bot.botclass.impl.PureRangeMelee.pot(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.update().
getMaxSkillCount()
int com.runehive.game.world.entity.mob.player.PlayerAssistant.getMaxSkillCount ()
Gets the total amount of 99s the player has.
Definition at line 629 of file PlayerAssistant.java.
{
        int count = 0;
        for (int index = 0; index < Skill.SKILL_COUNT; index++) {
            if (player.skills.getMaxLevel(index) == 99)
                count++;
        }
        return count;
    }
References player, and com.runehive.game.world.entity.skill.Skill.SKILL_COUNT.
getROWIndex()
int com.runehive.game.world.entity.mob.player.PlayerAssistant.getROWIndex (int item) private
Definition at line 708 of file PlayerAssistant.java.
{
        int index = -1;
        for (int amulet = 0; amulet < RING_OF_WEALTH.length; amulet++) {
            if (item == RING_OF_WEALTH[amulet]) {
                return amulet;
            }
        }
        return index;
    }
References RING_OF_WEALTH.
Referenced by useROW().
getStrategy()
CombatStrategy< Player > com.runehive.game.world.entity.mob.player.PlayerAssistant.getStrategy ()
Handles getting the combat strategy.
Definition at line 146 of file PlayerAssistant.java.
{
        if (player.isSingleCast())
            return new PlayerMagicStrategy(player.getSingleCastSpell());
        if (player.isAutocast())
            return new PlayerMagicStrategy(player.getAutocastSpell());
        if (player.isSpecialActivated()) {
            if (player.getCombatSpecial() == null) {
                player.setSpecialActivated(false);
                player.send(new SendSpecialEnabled(0));
            } else {
                return player.getCombatSpecial().getStrategy();
            }
        }
        Item item = player.equipment.get(Equipment.WEAPON_SLOT);
        if (item != null) {
            if(item.getId() == 22325) {
                return ScytheOfViturStrategy.get();
            }
            if (item.getId() == 11907) {
                return TridentOfTheSeasStrategy.get();
            }
            if (item.getId() == 27275) {
                return TumekenStrategy.get();
            }
            if (item.getId() == 12899) {
                return TridentOfTheSwampStrategy.get();
            }
            if (item.getId() == 12926) {
                return ToxicBlowpipeStrategy.get();
            }
            if (item.getRangedDefinition().isPresent()) {
                return PlayerRangedStrategy.get();
            }
        }
        return PlayerMeleeStrategy.get();
    }
References com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.get(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.get(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.get(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.get(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.get(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.get(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.get(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getRangedDefinition(), player, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
getValueIcon()
ValueIcon com.runehive.game.world.entity.mob.player.PlayerAssistant.getValueIcon (Player player)
Definition at line 658 of file PlayerAssistant.java.
{
        ValueIcon icon = ValueIcon.NONE;
        long carrying = networth(player.inventory, player.equipment);
        if (carrying < 500_000)
            icon = ValueIcon.BRONZE;
        if (carrying > 500_000 && carrying < 1_500_000)
            icon = ValueIcon.SILVER;
        if (carrying > 1_500_000 && carrying < 5_000_000)
            icon = ValueIcon.GREEN;
        if (carrying > 5_000_000 && carrying < 25_000_000)
            icon = ValueIcon.BLUE;
        if (carrying > 25_000_000)
            icon = ValueIcon.RED;
        return icon;
    }
References com.runehive.content.ValueIcon.BLUE, com.runehive.content.ValueIcon.BRONZE, com.runehive.content.ValueIcon.GREEN, networth(), com.runehive.content.ValueIcon.NONE, player, com.runehive.content.ValueIcon.RED, and com.runehive.content.ValueIcon.SILVER.
Referenced by setActivity(), and setValueIcon().
handleDestroyItem()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.handleDestroyItem ()
Handles destroying the item.
Definition at line 558 of file PlayerAssistant.java.
{
        if (player.attributes.has("UNCHARGE_HELM_KEY")) {
            Item item = player.attributes.get("UNCHARGE_HELM_KEY");
            player.dialogueFactory.clear();
            player.inventory.replace(item, new Item(12_934, 20_000), true);
            player.send(new SendMessage("You have dismantled your " + item.getName() + "."));
            player.attributes.remove("UNCHARGE_HELM_KEY");
            return;
        }
        if (player.attributes.has("RESTORE_HELM_KEY")) {
            Item item = player.attributes.get("RESTORE_HELM_KEY");
            player.dialogueFactory.clear();
            if (item.matchesId(13_197)) {
                player.serpentineHelmCharges += player.tanzaniteHelmCharges;
                player.tanzaniteHelmCharges = 0;
                if (player.serpentineHelmCharges > 11_000) {
                    player.inventory.addOrDrop(new Item(12934, player.serpentineHelmCharges - 11_000));
                    player.serpentineHelmCharges = 11_000;
                }
                player.inventory.replace(item, new Item(player.serpentineHelmCharges <= 0 ? 12_929 : 12_931), true);
            } else if (item.matchesId(13_199)) {
                player.serpentineHelmCharges += player.magmaHelmCharges;
                player.magmaHelmCharges = 0;
                if (player.serpentineHelmCharges > 11_000) {
                    player.inventory.addOrDrop(new Item(12934, player.serpentineHelmCharges - 11_000));
                    player.serpentineHelmCharges = 11_000;
                }
            }
            player.inventory.replace(item, new Item(player.serpentineHelmCharges <= 0 ? 12_929 : 12_931), true);
            player.send(new SendMessage("You have restored your " + item.getName() + "."));
            player.attributes.remove("RESTORE_HELM_KEY");
            return;
        }
        int index = player.attributes.get("DESTROY_ITEM_KEY", Integer.class);
        if (index == -1)
            return;
        Item item = player.inventory.get(index);
        if (item == null)
            return;
        player.dialogueFactory.clear();
        player.inventory.remove(item, index);
        player.send(new SendMessage("You have destroyed your " + item.getName() + "."));
        player.attributes.remove("DESTROY_ITEM_KEY");
    }
References com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.Item.matchesId(), and player.
initialize()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.initialize () private
initializes the player's random bs.
Definition at line 117 of file PlayerAssistant.java.
{
        player.getCombat().resetTimers(-CombatConstants.COMBAT_LOGOUT_COOLDOWN);
        player.send(new SendEntityFeed());
        player.send(new SendSpecialAmount());
        InterfaceWriter.write(new InformationWriter(player));
        InterfaceWriter.write(new AchievementWriter(player));
    }
References com.runehive.game.world.entity.combat.CombatConstants.COMBAT_LOGOUT_COOLDOWN, player, and com.runehive.content.writer.InterfaceWriter.write().
Referenced by login().
instance()
int com.runehive.game.world.entity.mob.player.PlayerAssistant.instance ()
Gets the instanced height for player.
Definition at line 624 of file PlayerAssistant.java.
{
        return player.getIndex() << 2;
    }
References player.
kdr()
String com.runehive.game.world.entity.mob.player.PlayerAssistant.kdr ()
Gets the KDR of the player.
Definition at line 610 of file PlayerAssistant.java.
{
        double KDR = (player.kill / (double) player.death);
        return Double.isNaN(KDR) ? "0.0" : String.format("%.2f", KDR);
    }
References player.
Referenced by com.runehive.content.ProfileViewer.string().
login()
final void com.runehive.game.world.entity.mob.player.PlayerAssistant.login ()
Handles initializing all the player assistant methods on login.
Definition at line 84 of file PlayerAssistant.java.
{
        reset();
        setAttribute();
        setPrayer();
        initialize();
        setSidebar(false, true);
        setActivity();
        setContextMenu();
        setEffects();
        Pets.onLogin(player);
        EmoteHandler.refresh(player);
        ClanChannelHandler.onLogin(player);
        player.setCollectionLog(CollectionLogSaving.load(player));
        player.runePouch.refresh();
    }
References initialize(), com.runehive.content.collectionlog.CollectionLogSaving.load(), com.runehive.content.clanchannel.channel.ClanChannelHandler.onLogin(), com.runehive.content.pet.Pets.onLogin(), player, com.runehive.content.emote.EmoteHandler.refresh(), reset(), setActivity(), setAttribute(), setContextMenu(), setEffects(), setPrayer(), and setSidebar().
Referenced by setSidebar().
moveCamera()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.moveCamera (Position position, int resetDelay)
Definition at line 699 of file PlayerAssistant.java.
{
        player.send(new SendCameraTurn(position.getChunkX(), position.getChunkY(), position.getHeight(), 5, 5));
        World.schedule(resetDelay, () -> player.send(new SendCameraReset()));
    }
References player, and com.runehive.game.world.World.schedule().
networth() [1/2]
long com.runehive.game.world.entity.mob.player.PlayerAssistant.networth ()
Definition at line 638 of file PlayerAssistant.java.
{
        return networth(player.inventory, player.equipment, player.bank);
    }
References networth(), and player.
Referenced by getValueIcon(), networth(), networth(), and com.runehive.content.ProfileViewer.string().
networth() [2/2]
long com.runehive.game.world.entity.mob.player.PlayerAssistant.networth (ItemContainer... containers)
Gets the net worth of the player.
Definition at line 643 of file PlayerAssistant.java.
{
        long networth = 0;
        for (ItemContainer container : containers) {
            networth += container.containerValue(PriceType.VALUE);
        }
        return networth;
    }
References networth(), and com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE.
prayerDrain()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.prayerDrain () private
Handles draining prayer.
Definition at line 422 of file PlayerAssistant.java.
{
        if (!player.prayer.isActive()) {
            return;
        }
        int bonus = player.getBonus(Equipment.PRAYER_BONUS);
        int rate = player.prayer.drainAmount(bonus);
        drainPrayer(rate);
    }
References drainPrayer(), player, and com.runehive.game.world.items.containers.equipment.Equipment.PRAYER_BONUS.
Referenced by sequence().
reset()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.reset ()
Resets the player's variables.
Definition at line 336 of file PlayerAssistant.java.
{
        player.unpoison();
        player.unvenom();
        resetEffects();
        setWidget();
        player.movement.reset();
        player.getCombat().reset();
        player.prayer.reset();
        player.headIcon = -1;
        player.updateFlags.add(UpdateFlag.APPEARANCE);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, player, resetEffects(), and setWidget().
Referenced by login(), and restore().
resetEffects()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.resetEffects ()
Reset's all the player's activated effects.
Definition at line 349 of file PlayerAssistant.java.
{
        CombatUtil.cancelEffect(player, CombatEffectType.TELEBLOCK);
        CombatUtil.cancelEffect(player, CombatEffectType.ANTIFIRE_POTION);
        CombatUtil.cancelEffect(player, CombatEffectType.SKULL);
        CombatUtil.cancelEffect(player, CombatEffectType.VENOM);
    }
References com.runehive.game.world.entity.combat.effect.CombatEffectType.ANTIFIRE_POTION, com.runehive.game.world.entity.combat.CombatUtil.cancelEffect(), player, com.runehive.game.world.entity.combat.effect.CombatEffectType.SKULL, com.runehive.game.world.entity.combat.effect.CombatEffectType.TELEBLOCK, and com.runehive.game.world.entity.combat.effect.CombatEffectType.VENOM.
Referenced by reset().
restore()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.restore ()
Resets the player's variables.
Definition at line 309 of file PlayerAssistant.java.
{
        reset();
        player.runEnergy = 100;
        player.skulling.unskull();
        player.skills.restoreAll();
        player.inventory.refresh();
        player.equipment.login();
        player.action.reset();
        player.interfaceManager.close();
        player.setSpecialActivated(false);
        player.send(new SendSpecialEnabled(0));
        player.getCombat().getDamageCache().clear();
        player.send(new SendRunEnergy());
        player.movement.reset();
        player.teleblockTimer.set(0);
        player.spellCasting.castingDelay.reset();
        player.spellCasting.vengeanceDelay.reset();
        if (player.venged) {
            player.venged = false;
            player.getCombat().removeListener(VengeanceListener.get());
        }
        CombatSpecial.restore(player, 100);
    }
References com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.get(), player, reset(), and com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.restore().
run()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.run () private
Handles the running.
Definition at line 364 of file PlayerAssistant.java.
                       {
        if (player.movement.isRunning() && player.movement.isMoving() && !player.isBot && !PlayerRight.isDeveloper(player)) {
            player.runEnergy--;
            if (player.runEnergy < 0)
                player.runEnergy = 0;
            if (player.runEnergy == 0)
                player.movement.setRunningToggled(false);
            player.send(new SendRunEnergy());
        }
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper(), and player.
Referenced by sequence().
runRestore()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.runRestore () private
Handles restoring the run energy.
Definition at line 376 of file PlayerAssistant.java.
{
        if (player.resting && player.sequence % 50 == 0) {
            player.animate(player.right.getRestAnimation());
        }
        if (player.runEnergy < 100) {
            int rate = player.energyRate > 0 ? 2 : player.resting || SkillCape.isEquipped(player, SkillCape.AGILITY) ? 3 : 4;
            if (player.sequence % rate == 0) {
                player.runEnergy++;
                player.send(new SendRunEnergy());
            }
        }
        if (player.energyRate > 0) {
            player.energyRate--;
        }
    }
References com.runehive.content.skillcape.SkillCape.AGILITY, com.runehive.content.skillcape.SkillCape.isEquipped(), and player.
Referenced by sequence().
sequence()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.sequence ()
Handles the method that will occur on sequence.
Definition at line 126 of file PlayerAssistant.java.
{
        skillRestore();
        updateSpecial();
        prayerDrain();
        run();
        runRestore();
        player.getCombat().tick();
        Activity.forActivity(player, it -> {
            if (!(it instanceof GroupActivity))
                it.sequence();
        });
        CombatTarget.checkAggression(player);
        if (player.sequence % 20 == 0) {
            Farming.tick(player);
        }
    }
References com.runehive.game.world.entity.combat.CombatTarget.checkAggression(), com.runehive.content.activity.Activity.forActivity(), player, prayerDrain(), run(), runRestore(), skillRestore(), com.runehive.content.skill.impl.farming.Farming.tick(), and updateSpecial().
setActivity()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity () private
Sets the activity for the player.
Definition at line 225 of file PlayerAssistant.java.
{
        if (player.punishment.isJailed()) {
            JailActivity.create(player);
        } else if (player.needsStarter) {
            StarterKit.open(player);
        } else if (Area.inGodwars(player)) {
            GodwarsActivity.create(player);
        } else if (Area.inWarriorGuild(player)) {
            WarriorGuild.create(player);
        } else if (Area.inBarrows(player)) {
            Barrows.create(player);
        } else if (Area.inVorkath(player)) {
            VorkathActivity.create(player);
        } else if (Area.inKraken(player)) {
            KrakenActivity.create(player);
        } else if (Area.inCerberus(player)) {
            CerberusActivity.create(player);
        } else if (Area.inWilderness(player)) {
            player.valueIcon = getValueIcon(player).getCode();
            player.updateFlags.add(UpdateFlag.APPEARANCE);
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.activity.impl.barrows.Barrows.create(), com.runehive.content.activity.impl.CerberusActivity.create(), com.runehive.content.activity.impl.godwars.GodwarsActivity.create(), com.runehive.content.activity.impl.JailActivity.create(), com.runehive.content.activity.impl.kraken.KrakenActivity.create(), com.runehive.content.activity.impl.VorkathActivity.create(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.create(), com.runehive.content.ValueIcon.getCode(), getValueIcon(), com.runehive.game.world.position.Area.inBarrows(), com.runehive.game.world.position.Area.inCerberus(), com.runehive.game.world.position.Area.inGodwars(), com.runehive.game.world.position.Area.inKraken(), com.runehive.game.world.position.Area.inVorkath(), com.runehive.game.world.position.Area.inWarriorGuild(), com.runehive.game.world.position.Area.inWilderness(), com.runehive.content.StarterKit.open(), and player.
Referenced by login().
setAttribute()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.setAttribute () private
Sets all the player attributes.
Definition at line 209 of file PlayerAssistant.java.
{
        player.attributes.set("OBELISK", -1);
        player.attributes.set("BANK_KEY", false);
        player.attributes.set("TRADE_KEY", false);
        player.attributes.set("DUEL_KEY", false);
        player.attributes.set("RUN_FLAG_KEY", 10);
        player.attributes.set("PLAYER_TITLE_KEY", 0);
        player.attributes.set("FORCE_MOVEMENT", false);
        player.attributes.set("PRELOADING_SLOT_KEY", 0);
        player.attributes.set("PERSONAL_STORE_KEY", null);
        player.attributes.set("PRICE_CHECKER_KEY", false);
        player.attributes.set("DONATOR_DEPOSIT_KEY", false);
        player.attributes.set("TELEPORT_TYPE_KEY", TeleportType.FAVORITES);
    }
References com.runehive.content.skill.impl.magic.teleport.TeleportType.FAVORITES, and player.
Referenced by login().
setContextMenu()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.setContextMenu () private
Sends the context menu to the Player's context.
Definition at line 250 of file PlayerAssistant.java.
{
        if (Area.inDuelArenaLobby(player)) {
            player.send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false));
            player.send(new SendPlayerOption(PlayerOption.ATTACK, false, true));
      /*  } else if (Area.inWilderness(player) || Area.inEventArena(player)) {
            player.send(new SendPlayerOption(PlayerOption.ATTACK, true));
            player.send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));*/
        } else if (Area.inDuelArena(player) || Area.inDuelObsticleArena(player)) {
            player.send(new SendPlayerOption(PlayerOption.ATTACK, true));
            player.send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
        } else {
            player.send(new SendPlayerOption(PlayerOption.ATTACK, false, true));
            player.send(new SendPlayerOption(PlayerOption.DUEL_REQUEST, false, true));
        }
        player.send(new SendPlayerOption(PlayerOption.FOLLOW, false));
        player.send(new SendPlayerOption(PlayerOption.TRADE_REQUEST, false));
        player.send(new SendPlayerOption(PlayerOption.VIEW_PROFILE, false));
    }
References com.runehive.game.world.entity.mob.player.PlayerOption.ATTACK, com.runehive.game.world.entity.mob.player.PlayerOption.DUEL_REQUEST, com.runehive.game.world.entity.mob.player.PlayerOption.FOLLOW, com.runehive.game.world.position.Area.inDuelArena(), com.runehive.game.world.position.Area.inDuelArenaLobby(), com.runehive.game.world.position.Area.inDuelObsticleArena(), player, com.runehive.game.world.entity.mob.player.PlayerOption.TRADE_REQUEST, and com.runehive.game.world.entity.mob.player.PlayerOption.VIEW_PROFILE.
Referenced by login().
setEffects()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.setEffects () private
Sets the effects for the player.
Definition at line 101 of file PlayerAssistant.java.
{
        if (player.getPoisonImmunity().get() > 0) {
            World.schedule(new SuperAntipoisonTask(player).attach(player));
        }
        if (player.skulling.getSkullRemoveTask().getSkullTime() > 0) {
            player.skulling.skull();
        }
        if (player.teleblockTimer.get() > 0) {
            player.send(new SendWidget(SendWidget.WidgetType.TELEBLOCK, (int) ((double) player.teleblockTimer.get() / 1000D * 600D)));
            World.schedule(new TeleblockTask(player));
        }
    }
References player, com.runehive.game.world.World.schedule(), and com.runehive.net.packet.out.SendWidget.WidgetType.TELEBLOCK.
Referenced by login().
setPrayer()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.setPrayer ()
Sets the prayer book.
Definition at line 270 of file PlayerAssistant.java.
{
        Consumer<Prayer> enable = prayer -> {
            if (player.prayer.anyActive(Prayer.RETRIBUTION, Prayer.REDEMPTION, Prayer.SMITE)) {
                player.getCombat().addListener(PrayerListener.get());
            }
            player.send(new SendConfig(prayer.getConfig(), 1));
            prayer.getListener().ifPresent(listener -> player.getCombat().addListener(listener));
        };
        Consumer<Prayer> disable = prayer -> {
            if (prayer == Prayer.RETRIBUTION || prayer == Prayer.REDEMPTION || prayer == Prayer.SMITE) {
                player.getCombat().removeListener(PrayerListener.get());
            }
            player.send(new SendConfig(prayer.getConfig(), 0));
            prayer.getListener().ifPresent(listener -> player.getCombat().removeListener(listener));
        };
        Consumer<Prayer> overhead = prayer -> {
            player.headIcon = prayer.getHeadIcon();
            player.updateFlags.add(UpdateFlag.APPEARANCE);
        };
        Consumer<Prayer> noOverhead = prayer -> {
            player.headIcon = -1;
            player.updateFlags.add(UpdateFlag.APPEARANCE);
        };
        player.prayer.setOnChange(enable, disable, overhead, noOverhead);
        Consumer<Prayer> qEnable = prayer -> player.send(new SendConfig(prayer.getQConfig(), 0));
        Consumer<Prayer> qDisable = prayer -> player.send(new SendConfig(prayer.getQConfig(), 1));
        player.quickPrayers.setOnChange(qEnable, qDisable, null, null);
        Arrays.stream(Prayer.values()).forEach(prayer -> {
            disable.accept(prayer);
            if (player.quickPrayers.isActive(prayer)) {
                qEnable.accept(prayer);
            } else {
                qDisable.accept(prayer);
            }
        });
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.get(), player, com.runehive.game.world.entity.mob.prayer.Prayer.REDEMPTION, com.runehive.game.world.entity.mob.prayer.Prayer.RETRIBUTION, and com.runehive.game.world.entity.mob.prayer.Prayer.SMITE.
Referenced by login().
setSidebar() [1/2]
final void com.runehive.game.world.entity.mob.player.PlayerAssistant.setSidebar (boolean disabled)
Sends all the side-bar identifications to the Player's client.
Definition at line 193 of file PlayerAssistant.java.
{
        setSidebar(disabled, false);
    }
References setSidebar().
Referenced by login(), and setSidebar().
setSidebar() [2/2]
final void com.runehive.game.world.entity.mob.player.PlayerAssistant.setSidebar (boolean disabled, boolean login)
Definition at line 197 of file PlayerAssistant.java.
{
        for (int index = 0; index < Config.SIDEBAR_INTERFACE.length; index++) {
            player.interfaceManager.setSidebar(Config.SIDEBAR_INTERFACE[index][0], disabled ? -1 : Config.SIDEBAR_INTERFACE[index][1]);
        }
        player.interfaceManager.setSidebar(Config.MAGIC_TAB, disabled ? -1 : player.spellbook.getInterfaceId());
        if (!disabled) {
            WeaponInterface.execute(player, player.equipment.getWeapon(), login);
            player.send(new SendConfig(980, 0));
        }
    }
References com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), login(), com.runehive.Config.MAGIC_TAB, player, and com.runehive.Config.SIDEBAR_INTERFACE.
setValueIcon()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.setValueIcon ()
Definition at line 676 of file PlayerAssistant.java.
{
        ValueIcon icon = getValueIcon(player);
        final int currentIcon = player.valueIcon;
        if (icon.getCode() == currentIcon) {
            return;
        }
        player.valueIcon = icon.getCode();
        player.updateFlags.add(UpdateFlag.APPEARANCE);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.ValueIcon.getCode(), getValueIcon(), and player.
setWidget()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.setWidget ()
Sends all the widget data to the client.
Definition at line 357 of file PlayerAssistant.java.
{
        for (WidgetType widget : WidgetType.values()) {
            player.send(new SendWidget(widget, 0));
        }
    }
References player.
Referenced by reset().
skillRestore()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.skillRestore () private
Handles restoration of skills.
Definition at line 400 of file PlayerAssistant.java.
{
        if (player.sequence % 120 != 0 && player.sequence % 50 != 0)
            return;
        if (player.sequence % (SkillCape.isEquipped(player, SkillCape.HITPOINTS) ? 50 : 100) == 0) {
            player.skills.regress(Skill.HITPOINTS);
        } else if (player.sequence % 50 == 0 && player.prayer.isActive(Prayer.RAPID_HEAL)) {
            player.skills.regress(Skill.HITPOINTS);
        }
        for (int index = 0; index <= 6; index++) {
            if (index == Skill.HITPOINTS || index == Skill.PRAYER) continue;
            int amount = 100;
            Skill skill = player.skills.get(index);
            if (skill.getLevel() < skill.getMaxLevel() && player.prayer.isActive(Prayer.RAPID_RESTORE))
                amount = 50;
            if (skill.getLevel() > skill.getMaxLevel() && player.prayer.isActive(Prayer.PRESERVE))
                amount = 150;
            if (player.sequence % amount == 0)
                player.skills.regress(index);
        }
    }
References com.runehive.content.skillcape.SkillCape.HITPOINTS, com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.content.skillcape.SkillCape.isEquipped(), player, com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.mob.prayer.Prayer.PRESERVE, com.runehive.game.world.entity.mob.prayer.Prayer.RAPID_HEAL, and com.runehive.game.world.entity.mob.prayer.Prayer.RAPID_RESTORE.
Referenced by sequence().
transform()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.transform (int npc)
Tranforms player into npc.
Definition at line 471 of file PlayerAssistant.java.
{
        if (npc == -1) {
            player.mobAnimation.reset();
            player.setWidth(1);
            player.setLength(1);
        } else {
            NpcDefinition def = NpcDefinition.get(npc);
            if (def != null) {
                player.mobAnimation.setStand(def.getStand());
                player.mobAnimation.setWalk(def.getWalk());
                player.mobAnimation.setTurn180(def.getTurn180());
                player.mobAnimation.setTurn90CW(def.getTurn90CW());
                player.mobAnimation.setTurn90CCW(def.getTurn90CCW());
                player.setWidth(def.getSize());
                player.setLength(def.getSize());
            }
        }
        player.id = npc;
        player.updateFlags.add(UpdateFlag.APPEARANCE);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get(), and player.
updateSpecial()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.updateSpecial () private
Updates the special amount.
Definition at line 187 of file PlayerAssistant.java.
{
        if (player.getSpecialPercentage().get() < 100 && player.sequence % 60 == 0)
            CombatSpecial.restore(player, 10);
    }
References player, and com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.restore().
Referenced by sequence().
useROW()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.useROW ()
Definition at line 718 of file PlayerAssistant.java.
{
        for (int row : RING_OF_WEALTH) {
            int index = getROWIndex(row);
            if (player.equipment.contains(row)) {
                player.equipment.set(Equipment.RING_SLOT, new Item(RING_OF_WEALTH[index]), true);
                player.message("<col=7F007F>" + (index == 0 ? "You have used your last charge." : "Your ring of wealth has " + Utility.convertWord(index).toLowerCase() + "charge" + (index == 1 ? "" : "s") + " remaining."));
                break;
            }
        }
    }
References com.runehive.util.Utility.convertWord(), getROWIndex(), player, RING_OF_WEALTH, and com.runehive.game.world.items.containers.equipment.Equipment.RING_SLOT.
weight()
double com.runehive.game.world.entity.mob.player.PlayerAssistant.weight ()
Gets the total carried weight of the player.
Definition at line 652 of file PlayerAssistant.java.
{
        double weight = player.inventory.getWeight();
        weight += player.equipment.getWeight();
        return weight;
    }
References player, and weight().
Referenced by weight().
welcomeScreen()
void com.runehive.game.world.entity.mob.player.PlayerAssistant.welcomeScreen () package
Handles displaying the welcome itemcontainer.
Definition at line 493 of file PlayerAssistant.java.
{
        player.setVisible(true);
//        boolean wants = player.settings.welcomeScreen;
//        if (!wants || Area.inWilderness(player) || player.getCombat().inCombat() || player.newPlayer || player.needsStarter) {
//            player.setVisible(true);
//            player.send(new SendScreenMode(player.settings.clientWidth, player.settings.clientHeight));
//            return;
//        }
//        if (player.settings.clientWidth > 765 || player.settings.clientWidth > 503) {
//            player.settings.clientWidth = 765;
//            player.settings.clientHeight = 503;
//            player.send(new SendScreenMode(765, 503));
//        }
//        for (int index = 0; index < 3; index++) {
//            player.send(new SendString(Config.WELCOME_DIALOGUE[index], 21315 + index));
//        }
//        player.send(new SendInterfaceAnimation(21310, Expression.HAPPY.getId()));
//        player.send(new SendMarquee(21319, Config.WELCOME_MARQUEE));
//        player.send(new SendString("You last logged in <col=EB4646>earlier today</col>.", 21318));//TODO
//        //black marks
//        player.send(new SendString("", 21320));
//        player.send(new SendString("You have 0 black marks!", 21321));
//        player.send(new SendString("Keep up the good work!", 21322));
//        player.send(new SendString("", 21323));
//        //bank pins
//        player.send(new SendString("You do not have a bank", 21324));
//        player.send(new SendString("pin set! Speak to any", 21325));
//        player.send(new SendString("banker to set one.", 21326));
//        player.send(new SendString("Bank pins are security!", 21327));
//        //other
//        player.send(new SendString("Click to vote", 21328));
//        player.send(new SendString("Click to donate", 21329));
//        player.send(new SendString("Click change e-mail", 21330));
//        player.send(new SendString("Click to change pass", 21331));
//        //announcement
//        player.send(new SendString(Config.WELCOME_ANNOUNCEMENT[0], 21332));
//        player.send(new SendString(Config.WELCOME_ANNOUNCEMENT[1], 21333));
//        player.send(new SendString(Config.WELCOME_ANNOUNCEMENT[2], 21334));
//        player.send(new SendString(Config.WELCOME_ANNOUNCEMENT[3], 21335));
//        player.send(new SendString(Config.WELCOME_ANNOUNCEMENT[4], 21336));
//        //update
//        player.send(new SendString(Config.WELCOME_UPDATE[0], 21337));
//        player.send(new SendString(Config.WELCOME_UPDATE[1], 21338));
//        player.send(new SendString(Config.WELCOME_UPDATE[2], 21339));
//        player.send(new SendString(Config.WELCOME_UPDATE[3], 21340));
//        player.send(new SendString(Config.WELCOME_UPDATE[4], 21341));
//        player.interfaceManager.open(450);
    }
References player.
Member Data Documentation
interfaceText
Map<Integer, TinterfaceText> com.runehive.game.world.entity.mob.player.PlayerAssistant.interfaceText = new HashMap<>() private
Holds itemcontainer strings.
Definition at line 76 of file PlayerAssistant.java.
Referenced by checkSendString(), and clearSendStrings().
player
final Player com.runehive.game.world.entity.mob.player.PlayerAssistant.player private
The player instance.
Definition at line 73 of file PlayerAssistant.java.
Referenced by activateSkilling(), busy(), claimIronmanArmour(), contains(), copy(), destroyItem(), drainPrayer(), getCombatRange(), getMaxHit(), getMaxSkillCount(), getStrategy(), getValueIcon(), handleDestroyItem(), initialize(), instance(), kdr(), login(), moveCamera(), networth(), PlayerAssistant(), prayerDrain(), reset(), resetEffects(), restore(), run(), runRestore(), sequence(), setActivity(), setAttribute(), setContextMenu(), setEffects(), setPrayer(), setSidebar(), setValueIcon(), setWidget(), skillRestore(), transform(), updateSpecial(), useROW(), weight(), and welcomeScreen().
RING_OF_WEALTH
final int [] com.runehive.game.world.entity.mob.player.PlayerAssistant.RING_OF_WEALTH static private
Initial value:
= {
            2572, 11988, 11986, 11984, 11982, 11980
    }
Definition at line 704 of file PlayerAssistant.java.
{
            2572, 11988, 11986, 11984, 11982, 11980
    };
Referenced by getROWIndex(), and useROW().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/PlayerAssistant.java