RuneHive-Game: com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager Class Reference
com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager Class Reference
Public Member Functions
boolean deposit (int slot, int amount)
Attempts to deposit an item to an exchange session.
ExchangeSessionManager (Player player)
Constructs a new ExchangeSessionManager.
boolean request (ExchangeSession session)
Attempts to request the specified session.
boolean reset ()
Resets all the sessions the player is in regardless of the session state.
void reset (ExchangeSessionType type)
Resets all the session for the player dependant on the type.
void resetRequests ()
Clears the list of requested players.
boolean withdraw (int slot, int amount)
Attempts to withdraw an item from the exchange session.
Public Attributes
final Player player
The player this manager is for.
final List< Player > requested_players = new ArrayList<>()
The players this player has requested.
Detailed Description
Author
Stand Up
Since
25-1-2017.
Definition at line 15 of file ExchangeSessionManager.java.
Constructor & Destructor Documentation
ExchangeSessionManager()
com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.ExchangeSessionManager (Player player)
Constructs a new ExchangeSessionManager.
Parameters
player the player this manager is for.
Definition at line 31 of file ExchangeSessionManager.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
deposit()
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.deposit (int slot, int amount)
Attempts to deposit an item to an exchange session.
Parameters
slot the slot this item was added from.
amount the amount that was added.
Definition at line 48 of file ExchangeSessionManager.java.
{
        ExchangeSession session = ExchangeSession.getSession(player).orElse(null);
        if(session == null) {
            return false;
        }
        return session.add(player, slot, amount);
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.add(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getSession(), and player.
request()
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.request (ExchangeSession session)
Attempts to request the specified session.
Parameters
session the session to request.
Definition at line 39 of file ExchangeSessionManager.java.
{
        return session.request();
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.request().
reset() [1/2]
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.reset ()
Resets all the sessions the player is in regardless of the session state.
Definition at line 98 of file ExchangeSessionManager.java.
{
        Optional<ExchangeSession> session = ExchangeSession.getSession(player);
        if(!session.isPresent()) {
            return false;
        }
        reset(session.get().type);
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getSession(), player, and reset().
Referenced by reset().
reset() [2/2]
void com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.reset (ExchangeSessionType type)
Resets all the session for the player dependant on the type.
Definition at line 77 of file ExchangeSessionManager.java.
{
        Optional<ExchangeSession> session = ExchangeSession.getSession(player, type);
        if(!session.isPresent()) {
            return;
        }
        session.get().forEach(p -> {
            session.get().finalize(ExchangeCompletionType.RESTORE);
            resetRequests();
            p.interfaceManager.close();
        });
        Player other = session.get().getOther(player);
        other.send(new SendMessage("The other player has declined.", MessageColor.RED));
        ExchangeSession.SESSIONS.remove(session.get());
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getSession(), player, com.runehive.util.MessageColor.RED, resetRequests(), com.runehive.game.world.entity.mob.player.exchange.ExchangeCompletionType.RESTORE, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.SESSIONS.
Referenced by com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onButtonClick().
resetRequests()
void com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.resetRequests ()
Clears the list of requested players.
Definition at line 112 of file ExchangeSessionManager.java.
{
        player.exchangeSession.requested_players.clear();
    }
References player.
Referenced by reset().
withdraw()
boolean com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.withdraw (int slot, int amount)
Attempts to withdraw an item from the exchange session.
Parameters
slot the slot this item was removed from.
amount the amount that was removed.
Definition at line 63 of file ExchangeSessionManager.java.
{
        ExchangeSession session = ExchangeSession.getSession(player).orElse(null);
        if(session == null) {
            return false;
        }
        return session.remove(player, slot, amount);
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getSession(), player, and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove().
Member Data Documentation
player
final Player com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.player
The player this manager is for.
Definition at line 25 of file ExchangeSessionManager.java.
Referenced by deposit(), ExchangeSessionManager(), reset(), reset(), resetRequests(), and withdraw().
requested_players
final List<Player> com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.requested_players = new ArrayList<>()
The players this player has requested.
Definition at line 20 of file ExchangeSessionManager.java.
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/exchange/ExchangeSessionManager.java