RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Stringing Class Reference
com.runehive.content.skill.impl.crafting.impl.Stringing Class Reference
Handles stringing amulets.
Classes
enum AmuletData
The amulet data.
Static Public Member Functions
static void craft (Player player, AmuletData amulet)
Handles crafting the amulet.
static boolean useItem (Player player, Item used, Item with)
Handles using item.
Static Private Member Functions
static Action< Player > string (Player player, AmuletData amulet, int amount)
The amulet stringing action.
Detailed Description
Handles stringing amulets.
Author
Daniel
Definition at line 24 of file Stringing.java.
Member Function Documentation
craft()
void com.runehive.content.skill.impl.crafting.impl.Stringing.craft (Player player, AmuletData amulet) static
Handles crafting the amulet.
Parameters
player The player instance.
amulet The amulet data.
Definition at line 108 of file Stringing.java.
{
        player.dialogueFactory.clear();
        if (player.skills.getMaxLevel(Skill.CRAFTING) < amulet.level) {
            player.dialogueFactory.sendStatement("You need a crafting level of " + amulet.level + " to string this!").execute();
            return;
        }
        if (!player.inventory.contains(amulet.ingredient) || !player.inventory.contains(1759)) {
            player.dialogueFactory.sendStatement("You do not have the required items to do this!").execute();
            return;
        }
        ChatBoxItemDialogue.sendInterface(player, 1746, amulet.ingredient, 170);
        player.chatBoxItemDialogue = new ChatBoxItemDialogue(player) {
            @Override
            public void firstOption(Player player) {
                player.action.execute(string(player, amulet, 1), false);
            }
            @Override
            public void secondOption(Player player) {
                player.action.execute(string(player, amulet, 5), true);
            }
            @Override
            public void thirdOption(Player player) {
                player.send(new SendInputAmount("Enter amount", 2, input -> player.action.execute(string(player, amulet, Integer.parseInt(input)), true)));
            }
            @Override
            public void fourthOption(Player player) {
                player.action.execute(string(player, amulet, 14), true);
            }
        };
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.content.dialogue.DialogueFactory.clear(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.content.skill.impl.crafting.impl.Stringing.AmuletData.ingredient, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.crafting.impl.Stringing.AmuletData.level, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.ChatBoxItemDialogue.sendInterface(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by useItem().
string()
Action< Player > com.runehive.content.skill.impl.crafting.impl.Stringing.string (Player player, AmuletData amulet, int amount) static private
The amulet stringing action.
Parameters
player The player instance.
amulet The amulet data.
amount The amount beeing spun.
Returns
The spinnable action.
Definition at line 153 of file Stringing.java.
{
        return new Action<Player>(player, 2, true) {
            int ticks = 0;
            @Override
            public void execute() {
                if (!player.inventory.contains(amulet.ingredient) || !player.inventory.contains(1759)) {
                    cancel();
                    return;
                }
                player.inventory.remove(amulet.ingredient, 1);
                player.inventory.remove(1759, 1);
                player.inventory.add(amulet.product, 1);
                player.skills.addExperience(Skill.CRAFTING, 4 * Config.CRAFTING_MODIFICATION);
                player.send(new SendMessage("You string the " + ItemDefinition.get(amulet.ingredient).getName() + " into " + Utility.getAOrAn(ItemDefinition.get(amulet.product).getName()) + " " + ItemDefinition.get(amulet.product).getName() + "."));
                if (++ticks == amount) {
                    cancel();
                    return;
                }
            }
            @Override
            public String getName() {
                return "Stringing";
            }
            @Override
            public boolean prioritized() {
                return false;
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
        };
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.Config.CRAFTING_MODIFICATION, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.content.skill.impl.crafting.impl.Stringing.AmuletData.ingredient, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, com.runehive.content.skill.impl.crafting.impl.Stringing.AmuletData.product, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.skills.
useItem()
boolean com.runehive.content.skill.impl.crafting.impl.Stringing.useItem (Player player, Item used, Item with) static
Handles using item.
Parameters
player The player instance.
used The item being used.
with The item being used with.
Definition at line 85 of file Stringing.java.
{
        if (used.getId() != 1759 && with.getId() != 1759) {
            return false;
        }
        Item wool = used.getId() == 1759 ? used : with;
        Item amulet = wool.getId() == used.getId() ? with : used;
        if (!AmuletData.forAmulet(amulet.getId()).isPresent()) {
            return false;
        }
        AmuletData data = AmuletData.forAmulet(amulet.getId()).get();
        craft(player, data);
        return false;
    }
References craft(), com.runehive.content.skill.impl.crafting.impl.Stringing.AmuletData.forAmulet(), and com.runehive.game.world.items.Item.getId().
Referenced by com.runehive.content.skill.impl.crafting.Crafting.useItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Stringing.java