RuneHive-Game: com.runehive.net.ChannelFilter Class Reference
com.runehive.net.ChannelFilter Class Reference
The ChannelInboundHandlerAdapter implementation that will filter out unwanted connections from propagating down the pipeline.
Classes
class Connection
Creates a conenction for a host address.
Public Member Functions
void channelActive (ChannelHandlerContext ctx) throws Exception
void channelRegistered (ChannelHandlerContext ctx) throws Exception
void channelUnregistered (ChannelHandlerContext ctx) throws Exception
Private Member Functions
void disconnect (ChannelHandlerContext ctx, LoginResponse response)
Disconnects ctx with response as the response code.
Connection getConenction (ChannelHandlerContext ctx)
Gets the host address of the user logging in.
Private Attributes
final Multiset< Connection > connections = ConcurrentHashMultiset.create()
A set of connections currently active within the server.
Detailed Description
The ChannelInboundHandlerAdapter implementation that will filter out unwanted connections from propagating down the pipeline.
Author
Seven
Michael | Chex
Definition at line 27 of file ChannelFilter.java.
Member Function Documentation
channelActive()
void com.runehive.net.ChannelFilter.channelActive (ChannelHandlerContext ctx) throws Exception
Definition at line 33 of file ChannelFilter.java.
{
        Connection connection = getConenction(ctx);
        connection.setCanConnect(true);
    }
References getConenction(), and com.runehive.net.ChannelFilter.Connection.setCanConnect().
channelRegistered()
void com.runehive.net.ChannelFilter.channelRegistered (ChannelHandlerContext ctx) throws Exception
Definition at line 39 of file ChannelFilter.java.
{
        Connection connection = getConenction(ctx);
        /* Make sure this channel is not going to get flooded. */
        if (!connection.canConnect()) {
            return;
        }
        /*
         * If this local then, do nothing and proceed to next handler in the
         * pipeline.
         */
        if (connection.getHost().equalsIgnoreCase("127.0.0.1")) {
            return;
        }
        /* Add the host */
        connection.addConnection();
        /* Evaluate the host */
        if (connection.getConnections() > Config.CONNECTION_LIMIT) {
            disconnect(ctx, LoginResponse.LOGIN_LIMIT_EXCEEDED);
            return;
        }
        if (IPBannedPlayers.ipBans.contains(connection.getHost())) {
            disconnect(ctx, LoginResponse.ACCOUNT_DISABLED);
            return;
        }
        connections.add(connection);
        connection.setCanConnect(false);
        /*
         * Nothing went wrong, so register the channel and forward the randomevent to
         * next handler in the pipeline.
         */
        ctx.fireChannelRegistered();
    }
References com.runehive.net.codec.login.LoginResponse.ACCOUNT_DISABLED, com.runehive.net.ChannelFilter.Connection.addConnection(), com.runehive.net.ChannelFilter.Connection.canConnect, com.runehive.Config.CONNECTION_LIMIT, connections, disconnect(), getConenction(), com.runehive.net.ChannelFilter.Connection.getConnections(), com.runehive.net.ChannelFilter.Connection.getHost(), com.runehive.game.world.entity.mob.player.IPBannedPlayers.ipBans, com.runehive.net.codec.login.LoginResponse.LOGIN_LIMIT_EXCEEDED, and com.runehive.net.ChannelFilter.Connection.setCanConnect().
channelUnregistered()
void com.runehive.net.ChannelFilter.channelUnregistered (ChannelHandlerContext ctx) throws Exception
Definition at line 80 of file ChannelFilter.java.
{
        Connection connection = getConenction(ctx);
        /*
         * If this is local, do nothing and proceed to next handler in the
         * pipeline.
         */
        if (connection.getHost().equalsIgnoreCase("127.0.0.1")) {
            return;
        }
        connection.removeConnection();
        /* Remove the host from the connection list */
        if (connection.getConnections() == 0) {
            connections.remove(connection);
        }
        /*
         * The connection is unregistered so forward the randomevent to the next
         * handler in the pipeline.
         */
        ctx.fireChannelUnregistered();
    }
References connections, getConenction(), com.runehive.net.ChannelFilter.Connection.getConnections(), com.runehive.net.ChannelFilter.Connection.getHost(), and com.runehive.net.ChannelFilter.Connection.removeConnection().
disconnect()
void com.runehive.net.ChannelFilter.disconnect (ChannelHandlerContext ctx, LoginResponse response) private
Disconnects ctx with response as the response code.
Parameters
ctx The channel handler context.
response The response to disconnect with.
Definition at line 113 of file ChannelFilter.java.
{
        LoginResponsePacket message = new LoginResponsePacket(response);
        ByteBuf initialMessage = ctx.alloc().buffer(8).writeLong(0);
        ctx.write(initialMessage, ctx.voidPromise());
        ctx.writeAndFlush(message).addListener(ChannelFutureListener.CLOSE);
    }
Referenced by channelRegistered().
getConenction()
Connection com.runehive.net.ChannelFilter.getConenction (ChannelHandlerContext ctx) private
Gets the host address of the user logging in.
Parameters
ctx The context of this channel.
Returns
The host address of this connection.
Definition at line 129 of file ChannelFilter.java.
{
        String host = ((InetSocketAddress) ctx.channel().remoteAddress()).getAddress().getHostAddress();
        return connections.stream().filter(conn -> conn.getHost().equalsIgnoreCase(host)).findFirst().orElse(new Connection(host));
    }
References connections.
Referenced by channelActive(), channelRegistered(), and channelUnregistered().
Member Data Documentation
connections
final Multiset<Connection> com.runehive.net.ChannelFilter.connections = ConcurrentHashMultiset.create() private
A set of connections currently active within the server.
Definition at line 30 of file ChannelFilter.java.
Referenced by channelRegistered(), channelUnregistered(), and getConenction().
The documentation for this class was generated from the following file:
java/com/runehive/net/ChannelFilter.java