RuneHive-Game: com.runehive.content.simulator.DropSimulator Class Reference
com.runehive.content.simulator.DropSimulator Class Reference
This class simulates drops of an npc and places it on an itemcontainer.
Static Public Member Functions
static void drawList (Player player, String context)
Handles drawing the lsit of npcs based off the search context.
static void open (Player player)
Handles opening the drop simulator itemcontainer.
static void simulate (Player player, Simulation simulation, int id, int amount)
Handles displaying the simulated drops.
Static Public Attributes
static final Simulation[] CUSTOM_SIMULATIONS = { }
Static Private Attributes
static final int[] DEFAULT = {3080}
The default NPCs that will have their drops simulated.
Detailed Description
This class simulates drops of an npc and places it on an itemcontainer.
Author
Daniel.
Definition at line 21 of file DropSimulator.java.
Member Function Documentation
drawList()
void com.runehive.content.simulator.DropSimulator.drawList (Player player, String context) static
Handles drawing the lsit of npcs based off the search context.
Definition at line 39 of file DropSimulator.java.
{
        for (int index = 0, string = 26851; index < CUSTOM_SIMULATIONS.length; index++, string++) {
            Simulation simuation = CUSTOM_SIMULATIONS[index];
            String name = Utility.formatEnum(simuation.name());
            player.send(new SendTooltip("Open simulator for " + name, string));
            player.send(new SendString(name, string));
        }
        List<String> npc = new ArrayList<>();
        List<Integer> button = new ArrayList<>();
        for (NpcDefinition definition : NpcDefinition.DEFINITIONS) {
            if (npc.size() >= 50)
                break;
            if (definition == null)
                continue;
            if (!NpcDropManager.NPC_DROPS.containsKey(definition.getId())) {
                continue;
            }
            if (!definition.getName().toLowerCase().contains(context.toLowerCase())) {
                continue;
            }
            if (npc.contains(definition.getName()))
                continue;
            npc.add(definition.getName());
            button.add(definition.getId());
        }
        int size = npc.size() < 14 ? 14 : npc.size();
        for (int index = 0, string = 26851 + CUSTOM_SIMULATIONS.length; index < size; index++, string++) {
            String name = index >= npc.size() ? "" : npc.get(index);
            player.send(new SendTooltip(name.isEmpty() ? "" : "Open drop simulator for " + name, string));
            player.send(new SendString(name, string));
        }
        player.attributes.set("DROP_SIMULATOR_BUTTON_KEY", button);
        player.send(new SendScrollbar(26850, size * 15));
    }
References com.runehive.game.world.entity.mob.Mob.attributes, CUSTOM_SIMULATIONS, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.DEFINITIONS, com.runehive.util.Utility.formatEnum(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getId(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getName(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.NPC_DROPS, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.util.generic.GenericAttributes.set().
Referenced by open().
open()
void com.runehive.content.simulator.DropSimulator.open (Player player) static
Handles opening the drop simulator itemcontainer.
Definition at line 29 of file DropSimulator.java.
{
        int npc = Utility.randomElement(DEFAULT);
        String name = NpcDefinition.get(npc).getName();
        drawList(player, name);
        simulate(player, Simulation.NPC_DROP, npc, 100);
        player.send(new SendString(name, 26810, true));
        player.interfaceManager.open(26800);
    }
References DEFAULT, drawList(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getName(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.content.simulator.Simulation.NPC_DROP, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.util.Utility.randomElement(), com.runehive.game.world.entity.mob.player.Player.send(), and simulate().
Referenced by com.runehive.game.plugin.PluginContext.onClick().
simulate()
void com.runehive.content.simulator.DropSimulator.simulate (Player player, Simulation simulation, int id, int amount) static
Handles displaying the simulated drops.
Definition at line 77 of file DropSimulator.java.
{
        simulation.execute(player, id, amount);
    }
References com.runehive.content.simulator.SimulationFunction.execute().
Referenced by open().
Member Data Documentation
CUSTOM_SIMULATIONS
final Simulation [] com.runehive.content.simulator.DropSimulator.CUSTOM_SIMULATIONS = { } static
Definition at line 26 of file DropSimulator.java.
{ };
Referenced by drawList().
DEFAULT
final int [] com.runehive.content.simulator.DropSimulator.DEFAULT = {3080} static private
The default NPCs that will have their drops simulated.
Definition at line 24 of file DropSimulator.java.
{3080};
Referenced by open().
The documentation for this class was generated from the following file:
java/com/runehive/content/simulator/DropSimulator.java