RuneHive-Game: com.runehive.game.world.entity.mob.player.command.CommandParser Class Reference
com.runehive.game.world.entity.mob.player.command.CommandParser Class Reference
Public Member Functions
int argumentCount ()
String[] getArguments ()
String getCommand ()
boolean hasNext ()
boolean hasNext (int length)
boolean nextBoolean ()
byte nextByte () throws NumberFormatException
double nextDouble () throws NumberFormatException
int nextInt () throws NumberFormatException
String nextLine ()
long nextLong () throws NumberFormatException
short nextShort () throws NumberFormatException
String nextString () throws ArrayIndexOutOfBoundsException
String toString ()
Static Public Member Functions
static CommandParser split (CommandParser parser, String splitter)
static CommandParser split (String command, String input, String splitter)
static CommandParser split (String input, String splitter)
Private Member Functions
CommandParser (String command, String input, String splitter)
Private Attributes
final String[] arguments
final String command
int pointer
Detailed Description
Author
Chex | Michael Modified by nshusa
Definition at line 9 of file CommandParser.java.
Constructor & Destructor Documentation
CommandParser()
com.runehive.game.world.entity.mob.player.command.CommandParser.CommandParser (String command, String input, String splitter) private
Definition at line 16 of file CommandParser.java.
{
        this.command = command;
        this.arguments = Arrays.stream(input.split(splitter)).toArray(String[]::new);
    }
References command.
Referenced by split(), split(), and split().
Member Function Documentation
argumentCount()
int com.runehive.game.world.entity.mob.player.command.CommandParser.argumentCount ()
Definition at line 104 of file CommandParser.java.
{
        return arguments.length;
    }
References arguments.
getArguments()
String[] com.runehive.game.world.entity.mob.player.command.CommandParser.getArguments ()
Definition at line 108 of file CommandParser.java.
{
        return arguments;
    }
References arguments.
getCommand()
String com.runehive.game.world.entity.mob.player.command.CommandParser.getCommand ()
Definition at line 46 of file CommandParser.java.
{
        return command;
    }
References command.
Referenced by com.runehive.game.plugin.extension.CommandExtension.canExecute(), com.runehive.game.plugin.extension.CommandExtension.handleCommand(), and split().
hasNext() [1/2]
boolean com.runehive.game.world.entity.mob.player.command.CommandParser.hasNext ()
Definition at line 50 of file CommandParser.java.
{
        if (arguments.length == 1) {
            if (arguments[0].isEmpty()) {
                return false;
            }
        }
        return hasNext(1);
    }
References arguments, and hasNext().
Referenced by hasNext(), and nextLine().
hasNext() [2/2]
boolean com.runehive.game.world.entity.mob.player.command.CommandParser.hasNext (int length)
Definition at line 59 of file CommandParser.java.
{
        return pointer + length <= arguments.length;
    }
References arguments, and pointer.
nextBoolean()
boolean com.runehive.game.world.entity.mob.player.command.CommandParser.nextBoolean ()
Definition at line 63 of file CommandParser.java.
{
        return Boolean.parseBoolean(nextString());
    }
References nextString().
nextByte()
byte com.runehive.game.world.entity.mob.player.command.CommandParser.nextByte () throws NumberFormatException
Definition at line 67 of file CommandParser.java.
{
        return Byte.parseByte(nextString());
    }
References nextString().
nextDouble()
double com.runehive.game.world.entity.mob.player.command.CommandParser.nextDouble () throws NumberFormatException
Definition at line 71 of file CommandParser.java.
{
        return Double.parseDouble(nextString());
    }
References nextString().
nextInt()
int com.runehive.game.world.entity.mob.player.command.CommandParser.nextInt () throws NumberFormatException
Definition at line 75 of file CommandParser.java.
{
        return Integer.parseInt(nextString());
    }
References nextString().
nextLine()
String com.runehive.game.world.entity.mob.player.command.CommandParser.nextLine ()
Definition at line 95 of file CommandParser.java.
{
        final StringBuilder builder = new StringBuilder();
        while (hasNext()) {
            builder.append(" ").append(nextString());
        }
        return builder.toString().trim();
    }
References hasNext(), and nextString().
Referenced by split().
nextLong()
long com.runehive.game.world.entity.mob.player.command.CommandParser.nextLong () throws NumberFormatException
Definition at line 79 of file CommandParser.java.
{
        return Long.parseLong(nextString());
    }
References nextString().
nextShort()
short com.runehive.game.world.entity.mob.player.command.CommandParser.nextShort () throws NumberFormatException
Definition at line 83 of file CommandParser.java.
{
        return Short.parseShort(nextString());
    }
References nextString().
nextString()
String com.runehive.game.world.entity.mob.player.command.CommandParser.nextString () throws ArrayIndexOutOfBoundsException
Definition at line 87 of file CommandParser.java.
{
        if (pointer >= arguments.length) {
            throw new ArrayIndexOutOfBoundsException("The next argument does not exist. [Size: " + arguments.length + ", Attempted: " + pointer + "]");
        }
        return arguments[pointer++];
    }
References arguments, and pointer.
Referenced by nextBoolean(), nextByte(), nextDouble(), nextInt(), nextLine(), nextLong(), and nextShort().
split() [1/3]
CommandParser com.runehive.game.world.entity.mob.player.command.CommandParser.split (CommandParser parser, String splitter) static
Definition at line 21 of file CommandParser.java.
{
        return new CommandParser(parser.getCommand(), parser.nextLine(), splitter);
    }
References CommandParser(), getCommand(), and nextLine().
Referenced by split().
split() [2/3]
CommandParser com.runehive.game.world.entity.mob.player.command.CommandParser.split (String command, String input, String splitter) static
Definition at line 33 of file CommandParser.java.
{
        int position = input.indexOf(command);
        if (position == -1) {
            position = 0;
        }
        final String string = input.substring(position + command.length()).trim();
        return new CommandParser(command, string, splitter);
    }
References command, and CommandParser().
split() [3/3]
CommandParser com.runehive.game.world.entity.mob.player.command.CommandParser.split (String input, String splitter) static
Definition at line 25 of file CommandParser.java.
{
        final int index = input.indexOf(splitter);
        final String command = index == -1 ? input : input.substring(0, index);
        return split(command, input, splitter);
    }
References command, CommandParser(), and split().
toString()
String com.runehive.game.world.entity.mob.player.command.CommandParser.toString ()
Definition at line 113 of file CommandParser.java.
{
        return String.format("command=[%s] arguments=%s", command, arguments == null ? "none" : Arrays.toString(arguments));
    }
References arguments, and command.
Member Data Documentation
arguments
final String [] com.runehive.game.world.entity.mob.player.command.CommandParser.arguments private
Definition at line 12 of file CommandParser.java.
Referenced by argumentCount(), getArguments(), hasNext(), hasNext(), nextString(), and toString().
command
final String com.runehive.game.world.entity.mob.player.command.CommandParser.command private
Definition at line 11 of file CommandParser.java.
Referenced by CommandParser(), getCommand(), split(), split(), and toString().
pointer
int com.runehive.game.world.entity.mob.player.command.CommandParser.pointer private
Definition at line 14 of file CommandParser.java.
Referenced by hasNext(), and nextString().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/command/CommandParser.java