RuneHive-Game: com.runehive.content.skill.impl.magic.spell.impl.SuperHeat Class Reference
com.runehive.content.skill.impl.magic.spell.impl.SuperHeat Class Reference
The superheat spell.
Public Member Functions
void execute (Player player, Item item)
Executes the magic spell.
int getLevel ()
Gets the level required to cast spell.
String getName ()
Gets the name of the spell.
Item[] getRunes ()
Gets the runes required to cast the spell.
Detailed Description
The superheat spell.
Author
Daniel
Definition at line 21 of file SuperHeat.java.
Member Function Documentation
execute()
void com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute (Player player, Item item)
Executes the magic spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 39 of file SuperHeat.java.
{
        if (player.spellbook != Spellbook.MODERN)
            return;
        if (!player.spellCasting.castingDelay.elapsed(599))
            return;
        Optional<SmeltingData> data = SmeltingData.getDefinitionByItem(item.getId());
        if (!data.isPresent()) {
            player.message("You can not super heat this item!");
            return;
        }
        if (!player.inventory.containsAll(data.get().required)) {
            player.message("You do not contain the required items to super heat!");
            return;
        }
        if (player.skills.getMaxLevel(Skill.SMITHING) < data.get().requirement) {
            player.message("You need a smithing level of " + data.get().requirement + " to do super heat this item!");
            return;
        }
        player.animate(722);
        player.graphic(new Graphic(148, false));
        player.send(new SendForceTab(6));
        player.inventory.removeAll(data.get().required);
        player.inventory.addAll(data.get().produced);
        player.skills.addExperience(Skill.MAGIC, 53* Config.MAGIC_MODIFICATION);
        player.skills.addExperience(Skill.SMITHING, data.get().experience * Config.SMITHING_MODIFICATION);
        player.spellCasting.castingDelay.reset();
    }
References com.runehive.game.world.items.containers.ItemContainer.addAll(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.content.skill.impl.magic.spell.SpellCasting.castingDelay, com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.util.Stopwatch.elapsed(), com.runehive.content.skill.impl.smithing.SmeltingData.getDefinitionByItem(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.skill.Skill.MAGIC, com.runehive.Config.MAGIC_MODIFICATION, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.skill.impl.magic.Spellbook.MODERN, com.runehive.game.world.items.containers.ItemContainer.removeAll(), com.runehive.util.Stopwatch.reset(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.skill.Skill.SMITHING, com.runehive.Config.SMITHING_MODIFICATION, com.runehive.game.world.entity.mob.player.Player.spellbook, and com.runehive.game.world.entity.mob.player.Player.spellCasting.
getLevel()
int com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.getLevel ()
Gets the level required to cast spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 29 of file SuperHeat.java.
{
        return 43;
    }
getName()
String com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.getName ()
Gets the name of the spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 24 of file SuperHeat.java.
{
        return "Super heat";
    }
getRunes()
Item[] com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.getRunes ()
Gets the runes required to cast the spell.
Implements com.runehive.content.skill.impl.magic.spell.Spell.
Definition at line 34 of file SuperHeat.java.
{
        return new Item[] { new Item(554, 1), new Item(561, 1) };
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/magic/spell/impl/SuperHeat.java