RuneHive-Game: com.runehive.content.bot.objective.impl.RestockObjective Class Reference
com.runehive.content.bot.objective.impl.RestockObjective Class Reference
Public Member Functions
void finish (PlayerBot bot)
void init (PlayerBot bot)
Static Private Attributes
static final BotClass[] TYPES
The positions of all the bank locations for the bot to access.
Detailed Description
Definition at line 18 of file RestockObjective.java.
Member Function Documentation
finish()
void com.runehive.content.bot.objective.impl.RestockObjective.finish (PlayerBot bot)
Implements com.runehive.content.bot.objective.BotObjectiveListener.
Definition at line 61 of file RestockObjective.java.
{
        bot.speak(Utility.randomElement(BotUtility.GEAR_UP_MESSAGES));
        BotObjective.WALK_TO_DITCH.init(bot);
    }
References com.runehive.content.bot.BotUtility.GEAR_UP_MESSAGES, com.runehive.util.Utility.randomElement(), and com.runehive.content.bot.objective.BotObjective.WALK_TO_DITCH.
Referenced by init().
init()
void com.runehive.content.bot.objective.impl.RestockObjective.init (PlayerBot bot)
Implements com.runehive.content.bot.objective.BotObjectiveListener.
Definition at line 30 of file RestockObjective.java.
{
        if (bot.botClass == null)
            bot.botClass = RandomUtils.random(TYPES);
        Item[] inventory = bot.botClass.inventory();
        bot.inventory.set(inventory);
        bot.equipment.manualWearAll(bot.botClass.equipment());
        for (Item item : inventory) {
            if (item == null) continue;
            if (FoodData.forId(item.getId()).isPresent()) {
                bot.foodRemaining++;
            }
            Optional<PotionData> potion = PotionData.forId(item.getId());
            if (!potion.isPresent() || potion.get() == PotionData.SUPER_RESTORE_POTIONS || potion.get() == PotionData.SARADOMIN_BREW) {
                continue;
            }
            bot.statBoostersRemaining++;
        }
        int[] skills = bot.botClass.skills();
        for (int skill = 0; skill < skills.length; skill++) {
            bot.skills.setMaxLevel(skill, skills[skill]);
        }
        bot.skills.setCombatLevel();
        CombatSpecial.restore(bot, 100);
        bot.schedule(2, () -> finish(bot));
    }
References finish(), com.runehive.content.consume.FoodData.forId(), com.runehive.content.consume.PotionData.forId(), com.runehive.util.RandomUtils.random(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.restore(), com.runehive.content.consume.PotionData.SARADOMIN_BREW, com.runehive.content.consume.PotionData.SUPER_RESTORE_POTIONS, and TYPES.
Member Data Documentation
TYPES
final BotClass [] com.runehive.content.bot.objective.impl.RestockObjective.TYPES static private
Initial value:
= {
        new WelfareRuneMelee(),
        new AGSRuneMelee(),
        new PureMelee(),
        new PureRangeMelee(),
        new ZerkerMelee()
    }
The positions of all the bank locations for the bot to access.
Definition at line 21 of file RestockObjective.java.
{
        new WelfareRuneMelee(),
        new AGSRuneMelee(),
        new PureMelee(),
        new PureRangeMelee(),
        new ZerkerMelee()
    };
Referenced by init().
The documentation for this class was generated from the following file:
java/com/runehive/content/bot/objective/impl/RestockObjective.java