RuneHive-Game: com.runehive.game.world.items.containers.bank.Bank Class Reference
com.runehive.game.world.items.containers.bank.Bank Class Reference
Handles the Bank container.
Classes
class BankListener
Public Member Functions
boolean allowZero ()
Bank (Player player)
Constructs a new Bank.
void changeTabAmount (int tab, int amount)
Changes the amount of items stored in a tab.
void clear ()
Removes all of the items from this container.
void close ()
Closes the bank itemcontainer.
void collapse (int tab, boolean collapseAll)
Collapses a tab and shifts other tabs one slot to the left.
void deposit (int slot, int amount)
Deposits item into bank.
void depositeEquipment (boolean message)
Handles depositing all the equipment.
void depositeInventory (boolean message)
Handles depositing the entire inventory.
int depositFromNothing (Item item, int tab)
void moveItem (int opcode, int from, int to)
Moves an item within the bank.
void open ()
Opens the bank itemcontainer.
void placeHolder (int item, int slot)
Handles the place holder option for the contianer.
void refresh ()
Refreshes the bank itemcontainer.
void sendValue ()
void shift ()
Percolates the null indices to the end of the stack.
int tabForSlot (int slot)
void withdraw (int itemId, int slot, int amount)
Withdraws item from bank.
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainer
boolean add (int id, int amount)
Attempts to deposit item into this container.
boolean add (Item item)
Attempts to deposit item into this container.
boolean add (Item item, boolean refresh, boolean stack)
boolean add (Item item, int preferredIndex, boolean refresh)
boolean add (Item item, int preferredIndex, boolean refresh, boolean stack)
Attempts to deposit item into this container, preferably at preferredIndex.
boolean add (Item item, int slot)
Attempts to deposit item into this container.
boolean addAll (Collection<? extends Item > items)
Attempts to deposit items in bulk into this container.
boolean addAll (Item... items)
Attempts to deposit items in bulk into this container.
boolean addAll (ItemContainer items)
Attempts to deposit items in bulk into this container.
final boolean addListener (ItemContainerListener listener)
Adds an ItemContainerListener to this container.
final int capacity ()
final void clear (boolean refresh)
Removes all of the items from this container.
final int computeAmountForId (int id)
Computes the total quantity of the Items in this container with id.
final int computeFreeIndex ()
Computes the next free (null) index in this container.
final Optional< Integer > computeIdForIndex (int index)
Computes the identifier of the Item on index.
final int computeIndexCount (Item... forItems)
Computes the amount of indexes required to hold items in this container.
final int computeIndexForId (int id)
Computes the first index found that id is in.
long containerValue (PriceType type)
Gets the total worth of the container using the item's values.
boolean contains (int id)
Determines if this container contains id.
final boolean contains (int id, int amount)
final boolean contains (Item item)
final boolean containsAll (Collection< Item > items)
final boolean containsAll (int... identifiers)
Determines if this container contains all identifiers.
final boolean containsAll (Item... items)
final boolean containsAny (Collection< Item > items)
final boolean containsAny (int... identifiers)
Determines if this container contains any identifiers.
final boolean containsAny (Item... items)
final ItemContainer copy ()
Creates a copy of the underlying item container.
final void fireBulkItemsUpdatedEvent ()
Fires the ItemContainerListener.bulkItemsUpdated(ItemContainer) event.
final void fireCapacityExceededEvent ()
Fires the ItemContainerListener.capacityExceeded(ItemContainer) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh)
Fires the ItemContainerListener.itemUpdated(ItemContainer, int) event.
final void fireItemUpdatedEvent (Item oldItem, Item newItem, int index, boolean refresh, boolean login)
final void forEach (Consumer<? super Item > action)
Iterates through all of the Items within this container and performs action on them, skipping empty indexes (null values) as they are encountered.
final Item get (int index)
Gets the Item located on index.
int getFreeSlots ()
final int getId (int index)
Gets the item id located on index.
Item[] getItems ()
int getSlotById (int id)
Gets a slot by id.
double getWeight ()
Gets the weight of the container.
final boolean hasCapacityAfter (Item[] add, Item... remove)
Creates a copy of the underlying container and removes the items specified from it and after tries to deposit the specified items to it.
final boolean hasCapacityFor (Item... item)
Determines if this container has the capacity for item.
final void ifPresent (int index, Consumer< Item > action)
Consumes an action if the index is a valid item index in this container.
final boolean indexFree (int index)
Returns true if index is not occupied (null).
final boolean indexOccupied (int index)
Returns true if index is occupied (non-null).
final void insert (int oldIndex, int newIndex, boolean refresh)
final boolean isEmpty ()
final boolean isFull ()
ItemContainer (int capacity, StackPolicy policy)
Creates a new ItemContainer.
ItemContainer (int capacity, StackPolicy policy, Item[] items)
Creates a new ItemContainer.
final Iterator< Item > iterator ()
void onRefresh ()
Any functionality that should occur when refreshed.
final StackPolicy policy ()
void refresh (Player player, int widget)
Sends the items on the itemcontainer.
final int remaining ()
boolean remove (int id)
boolean remove (int id, int amount)
boolean remove (Item item)
Attempts to withdraw item from this container.
boolean remove (Item item, int preferredIndex)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean remove (Item item, int preferredIndex, boolean refresh)
boolean remove (Item item, int preferredIndex, boolean refresh, boolean removeAll)
Attempts to withdraw item from this container, preferably from preferredIndex.
boolean removeAll (Collection<? extends Item > items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (Item... items)
Attempts to withdraw items in bulk from this container.
boolean removeAll (ItemContainer items)
Attempts to withdraw items in bulk from this container.
final boolean removeListener (ItemContainerListener listener)
Removes an ItemContainerListener from this container.
final boolean replace (int oldId, int newId, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (int oldId, int newId, int index, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replace (Item first, Item second, boolean refresh)
Replaces the first occurrence of the Item having the identifier oldId with newId.
final boolean replaceAll (int oldId, int newId)
Replaces all occurrences of Items having the identifier
oldId with newId.
final Optional< Item > retrieve (int index)
Retrieves the item located on index.
Optional< Item > search (int id)
Searches and returns the first item found with id.
Optional< Item > search (Item item)
Searches and returns the first item found with id and
amount.
void set (int index, Item item, boolean refresh)
Sets the index to item.
final void set (Item[] toSet)
void setFiringEvents (boolean firingEvents)
Sets the value for firingEvents.
final void setItems (Item[] items)
final void setItems (Item[] items, boolean copy)
Sets the container of items to items.
final int size ()
final Spliterator< Item > spliterator ()
final Stream< Item > stream ()
final void swap (boolean insert, int oldIndex, int newIndex, boolean refresh)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex)
Swaps the Items on oldIndex and newIndex.
final void swap (int oldIndex, int newIndex, boolean refresh)
final Item[] toArray ()
Returns a shallow copy of the backing array.
final Item[] toNonNullArray ()
final void transfer (int firstIndex, int secondIndex, ItemContainer other, boolean refresh)
Public Attributes
int bankTab = 0
The current bank tab.
boolean inserting = false
The inserting flag.
boolean noting = false
The noting flag.
boolean placeHolder
The place holder flag.
int[] tabAmounts = new int[10]
The tab amount array.
Static Public Attributes
static final int SIZE = 360
The size of all equipment instances.
Private Member Functions
void itemToTab (int slot, int toTab)
void moveTab (int tab, int toTab)
void recursiveCollapse (int tab)
int slotForTab (int tab)
Private Attributes
final Player player
The player instance.
Detailed Description
Handles the Bank container.
Author
Michael
Daniel
Definition at line 24 of file Bank.java.
Constructor & Destructor Documentation
Bank()
com.runehive.game.world.items.containers.bank.Bank.Bank (Player player)
Constructs a new Bank.
Definition at line 48 of file Bank.java.
{
        super(SIZE, StackPolicy.ALWAYS);
        this.player = player;
        this.placeHolder = false;
        addListener(new BankListener());
    }
References com.runehive.game.world.items.containers.ItemContainer.addListener(), com.runehive.game.world.items.containers.ItemContainer.StackPolicy.ALWAYS, player, and SIZE.
Member Function Documentation
allowZero()
boolean com.runehive.game.world.items.containers.bank.Bank.allowZero ()
Returns
this policy checks if the container will allow empty items
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 481 of file Bank.java.
{
        return placeHolder;
    }
References placeHolder.
changeTabAmount()
void com.runehive.game.world.items.containers.bank.Bank.changeTabAmount (int tab, int amount)
Changes the amount of items stored in a tab.
Parameters
tab The tab to modify.
amount The amount to change.
Definition at line 316 of file Bank.java.
{
        if (tab < 0 || tab >= tabAmounts.length) {
            return;
        }
        tabAmounts[tab] += amount;
        if (tabAmounts[tab] == 0) {
            collapse(tab, false);
        }
    }
References collapse(), and tabAmounts.
Referenced by deposit(), depositFromNothing(), moveItem(), and withdraw().
clear()
void com.runehive.game.world.items.containers.bank.Bank.clear ()
Removes all of the items from this container.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 467 of file Bank.java.
{
        Arrays.fill(tabAmounts, 0);
        super.clear();
    }
References tabAmounts.
close()
void com.runehive.game.world.items.containers.bank.Bank.close ()
Closes the bank itemcontainer.
Definition at line 108 of file Bank.java.
{
        player.attributes.set("BANK_KEY", Boolean.FALSE);
        if (player.pvpInstance) {
            player.playerAssistant.setValueIcon();
        }
    }
References player.
collapse()
void com.runehive.game.world.items.containers.bank.Bank.collapse (int tab, boolean collapseAll)
Collapses a tab and shifts other tabs one slot to the left.
Parameters
tab The initial tab.
Definition at line 270 of file Bank.java.
{
        if (!player.interfaceManager.isInterfaceOpen(60000)) {
            return;
        }
        if (tab == 0 && collapseAll) {
            Arrays.fill(tabAmounts, 0);
            tabAmounts[0] = size();
            shift();
            return;
        }
        /* Move the remaining items to the main tab. */
        int tabAmount = tabAmounts[tab];
        if (tabAmount > 0) moveTab(tab, 0);
        /* Shift the remaining tabs to the left to fill the gap. */
        recursiveCollapse(tab);
        player.send(new SendConfig(211, bankTab = 0));
    }
References bankTab, moveTab(), player, recursiveCollapse(), shift(), com.runehive.game.world.items.containers.ItemContainer.size(), and tabAmounts.
Referenced by changeTabAmount(), and itemToTab().
deposit()
void com.runehive.game.world.items.containers.bank.Bank.deposit (int slot, int amount)
Deposits item into bank.
Definition at line 128 of file Bank.java.
{
        boolean withinBank = player.interfaceManager.isInterfaceOpen(60000) || player.interfaceManager.isInterfaceOpen(4465);
        if (!withinBank) {
            System.out.println("interface: " + player.interfaceManager.getMain());
            return;
        }
        Item item = player.inventory.get(slot);
        if (item == null)
            return;
        int id = item.getId();
        if (LootingBagPlugin.isLootingBag(item) && !player.lootingBag.isEmpty()) {
            player.interfaceManager.openInventory(60000, 26700);
            return;
        }
        int invAmount = player.inventory.computeAmountForId(id);
        if (invAmount < amount) {
            amount = invAmount;
        }
        setFiringEvents(false);
        if (item.isNoted())
            id = item.getUnnotedId();
        if (!contains(id)) {
            if (size() + 1 > capacity()) {
                player.message("Your bank is full! You need to clear some items from your bank.");
                setFiringEvents(true);
                return;
            }
            changeTabAmount(bankTab, 1);
            add(id, amount);
            int from = computeIndexForId(id);
            int to = slotForTab(bankTab);
            swap(true, from, to, false);
        } else {
            Item fucking = get(computeIndexForId(id));
            if (Integer.MAX_VALUE - fucking.getAmount() < amount) {
                amount = Integer.MAX_VALUE - fucking.getAmount();
                player.send(new SendMessage("Your bank didn't have enough space to deposit all that!"));
            }
            fucking.incrementAmountBy(amount);
        }
        if (amount > 0) {
            if(item.getId() == 12791) player.runePouch.clearInterface();
            player.inventory.remove(item.getId(), amount);
        }
        setFiringEvents(true);
        refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), bankTab, com.runehive.game.world.items.containers.ItemContainer.capacity, changeTabAmount(), com.runehive.game.world.items.containers.ItemContainer.computeIndexForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getUnnotedId(), com.runehive.game.world.items.Item.incrementAmountBy(), com.runehive.game.world.items.Item.isNoted(), player, refresh(), com.runehive.game.world.items.containers.ItemContainer.setFiringEvents(), com.runehive.game.world.items.containers.ItemContainer.size(), slotForTab(), and com.runehive.game.world.items.containers.ItemContainer.swap().
depositeEquipment()
void com.runehive.game.world.items.containers.bank.Bank.depositeEquipment (boolean message)
Handles depositing all the equipment.
Definition at line 372 of file Bank.java.
{
        int tab = bankTab;
        while (tab > 0 && tabAmounts[tab - 1] <= 0) tab--;
        Item[] items = player.equipment.getItems();
        for (int index = 0; index < items.length; index++) {
            if (items[index] == null) continue;
            Item item = items[index].copy();
            item.setAmount(depositFromNothing(item, tab));
            if (item.getAmount() > 0)
                player.equipment.remove(item, index, false);
        }
        if (message) {
            player.send(new SendMessage("You deposited all your worn equipment."));
        }
        player.equipment.login();
        refresh();
    }
References bankTab, depositFromNothing(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.containers.ItemContainer.items, player, refresh(), com.runehive.game.world.items.Item.setAmount(), and tabAmounts.
depositeInventory()
void com.runehive.game.world.items.containers.bank.Bank.depositeInventory (boolean message)
Handles depositing the entire inventory.
Definition at line 353 of file Bank.java.
{
        int tab = bankTab;
        while (tab > 0 && tabAmounts[tab - 1] <= 0) tab--;
        Item[] items = player.inventory.getItems();
        for (int index = 0; index < items.length; index++) {
            if (items[index] == null) continue;
            Item item = items[index].copy();
            item.setAmount(depositFromNothing(item, tab));
            if(item.getId() == 12791) player.runePouch.clearInterface();
            if (item.getAmount() > 0)
                player.inventory.remove(item, index, false);
        }
        if (message) {
            player.send(new SendMessage("You deposited all your inventory items."));
        }
        refresh();
    }
References bankTab, depositFromNothing(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.containers.ItemContainer.items, player, refresh(), com.runehive.game.world.items.Item.setAmount(), and tabAmounts.
depositFromNothing()
int com.runehive.game.world.items.containers.bank.Bank.depositFromNothing (Item item, int tab)
Definition at line 327 of file Bank.java.
{
        setFiringEvents(false);
        item = item.copy();
        int id = item.getUnnotedId();
        if (!contains(id)) {
            if (size() + 1 > capacity()) {
                return 0;
            }
            add(id, item.getAmount());
            changeTabAmount(tab, 1);
            int from = computeIndexForId(id);
            int to = slotForTab(tab);
            swap(true, from, to, false);
        } else {
            Item fucking = get(computeIndexForId(id));
            if (Integer.MAX_VALUE - fucking.getAmount() < item.getAmount()) {
                item.setAmount(Integer.MAX_VALUE - fucking.getAmount());
            }
            fucking.incrementAmountBy(item.getAmount());
        }
        setFiringEvents(true);
        return item.getAmount();
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.ItemContainer.capacity, changeTabAmount(), com.runehive.game.world.items.containers.ItemContainer.computeIndexForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.items.Item.copy(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getUnnotedId(), com.runehive.game.world.items.Item.incrementAmountBy(), com.runehive.game.world.items.Item.setAmount(), com.runehive.game.world.items.containers.ItemContainer.setFiringEvents(), com.runehive.game.world.items.containers.ItemContainer.size(), slotForTab(), and com.runehive.game.world.items.containers.ItemContainer.swap().
Referenced by depositeEquipment(), and depositeInventory().
itemToTab()
void com.runehive.game.world.items.containers.bank.Bank.itemToTab (int slot, int toTab) private
Definition at line 390 of file Bank.java.
{
        int fromTab = tabForSlot(slot);
        /* Item is already in this tab. */
        if (fromTab == toTab) return;
        /*
         * The tab to the left of the chosen tab is empty,
         * so don't create a new tab.
         */
        if (toTab > 1 && tabAmounts[toTab - 1] == 0 && tabAmounts[toTab] == 0) {
            return;
        }
        tabAmounts[toTab]++;
        tabAmounts[fromTab]--;
        int toSlot = slotForTab(toTab);
        if (tabAmounts[fromTab] == 0) {
            collapse(fromTab, false);
        }
        swap(true, slot, toSlot, false);
        refresh();
    }
References collapse(), refresh(), slotForTab(), com.runehive.game.world.items.containers.ItemContainer.swap(), tabAmounts, and tabForSlot().
Referenced by moveItem().
moveItem()
void com.runehive.game.world.items.containers.bank.Bank.moveItem (int opcode, int from, int to)
Moves an item within the bank.
An opcode of 0 performs a swap operation, with from being the origin slot and to being the destination slot.
An opcode of 1 performs an insert operation, with from being the origin slot and to being the destination slot.
An opcode of 2 moves an item from one tab to another, with from being the origin slot and to being the destination tab.
Parameters
opcode The opcode.
from The origin slot or tab.
to The destination slot or tab.
Definition at line 429 of file Bank.java.
{
        if (opcode == 2) {
            itemToTab(from, to);
        } else if (opcode == 1) {
            swap(true, from, to, false);
            int fromTab = tabForSlot(from);
            int toTab = tabForSlot(to);
            if (fromTab != toTab) {
                changeTabAmount(toTab, 1);
                changeTabAmount(fromTab, -1);
                refresh();
            }
        } else {
            swap(from, to);
        }
    }
References changeTabAmount(), itemToTab(), refresh(), com.runehive.game.world.items.containers.ItemContainer.swap(), and tabForSlot().
moveTab()
void com.runehive.game.world.items.containers.bank.Bank.moveTab (int tab, int toTab) private
Definition at line 296 of file Bank.java.
{
        int tabAmount = tabAmounts[tab];
        int fromSlot = slotForTab(tab);
        int toSlot = slotForTab(toTab) + 1;
        tabAmounts[tab] -= tabAmount;
        tabAmounts[toTab] += tabAmount;
        setFiringEvents(false);
        for (int i = 0; i < tabAmount; i++) {
            swap(true, fromSlot, toSlot, false);
        }
        setFiringEvents(true);
    }
References com.runehive.game.world.items.containers.ItemContainer.setFiringEvents(), slotForTab(), com.runehive.game.world.items.containers.ItemContainer.swap(), and tabAmounts.
Referenced by collapse(), and recursiveCollapse().
open()
void com.runehive.game.world.items.containers.bank.Bank.open ()
Opens the bank itemcontainer.
Definition at line 56 of file Bank.java.
                       {
        if (player.right.equals(PlayerRight.ULTIMATE_IRONMAN)) {
            player.send(new SendMessage("As an ultimate iron man you may not use banks!"));
            return;
        }
        if (player.bankPin.hasPin() && !player.bankPin.entered) {
            player.bankPin.enter();
            return;
        }
        noting = false;
        player.send(new SendString("360", 60018));
        player.attributes.set("BANK_KEY", Boolean.TRUE);
        player.interfaceManager.openInventory(60000, InterfaceConstants.INVENTORY_STORE - 1);
        refresh();
    }
References com.runehive.game.world.InterfaceConstants.INVENTORY_STORE, noting, player, refresh(), and com.runehive.game.world.entity.mob.player.PlayerRight.ULTIMATE_IRONMAN.
placeHolder()
void com.runehive.game.world.items.containers.bank.Bank.placeHolder (int item, int slot)
Handles the place holder option for the contianer.
Definition at line 117 of file Bank.java.
{
        boolean hold = placeHolder;
        placeHolder = true;
        setFiringEvents(false);
        withdraw(item, slot, Integer.MAX_VALUE);
        setFiringEvents(true);
        placeHolder = hold;
        refresh();
    }
References placeHolder, refresh(), com.runehive.game.world.items.containers.ItemContainer.setFiringEvents(), and withdraw().
recursiveCollapse()
void com.runehive.game.world.items.containers.bank.Bank.recursiveCollapse (int tab) private
Definition at line 290 of file Bank.java.
{
        if (tab == tabAmounts.length - 1) return;
        moveTab(tab + 1, tab);
        recursiveCollapse(tab + 1);
    }
References moveTab(), recursiveCollapse(), and tabAmounts.
Referenced by collapse(), and recursiveCollapse().
refresh()
void com.runehive.game.world.items.containers.bank.Bank.refresh ()
Refreshes the bank itemcontainer.
Definition at line 73 of file Bank.java.
{
        player.send(new SendConfig(304, inserting ? 1 : 0));
        player.send(new SendTooltip((inserting ? "Enable swapping" : "Enable inserting"), 60006));
        player.send(new SendConfig(115, noting ? 1 : 0));
        player.send(new SendTooltip((noting ? "Disable" : "Enable") + " noting", 60007));
        player.send(new SendConfig(116, placeHolder ? 1 : 0));
        player.send(new SendTooltip((placeHolder ? "Disable" : "Enable") + " place holders", 60073));
        player.send(new SendItemOnInterface(InterfaceConstants.WITHDRAW_BANK, tabAmounts, toArray()));
        player.inventory.refresh(player, InterfaceConstants.INVENTORY_STORE);
        player.inventory.refresh();
        sendValue();
    }
References inserting, com.runehive.game.world.InterfaceConstants.INVENTORY_STORE, noting, placeHolder, player, sendValue(), tabAmounts, com.runehive.game.world.items.containers.ItemContainer.toArray(), and com.runehive.game.world.InterfaceConstants.WITHDRAW_BANK.
Referenced by com.runehive.game.world.items.containers.bank.Bank.BankListener.bulkItemsUpdated(), com.runehive.content.gambling.GambleManager.decline(), deposit(), depositeEquipment(), depositeInventory(), com.runehive.content.gambling.GambleManager.give(), itemToTab(), com.runehive.game.world.items.containers.bank.Bank.BankListener.itemUpdated(), moveItem(), open(), placeHolder(), and withdraw().
sendValue()
void com.runehive.game.world.items.containers.bank.Bank.sendValue ()
Definition at line 87 of file Bank.java.
{
        long value = 0;
        int start = slotForTab(bankTab);
        int end = start + tabAmounts[bankTab];
        if (bankTab == 0) {
            start = 0;
            end = size();
        }
        for (int slot = start; slot < end; slot++) {
            Item item = get(slot);
            if (item == null) continue;
            int price = item.getValue(PriceType.VALUE);
            if (value >= Long.MAX_VALUE - price * item.getAmount()) {
                value = Long.MAX_VALUE;
            }
            value += price * item.getAmount();
        }
        player.send(new SendString((bankTab == 0 ? "Bank" : "Tab " + bankTab) + " value: <col=FF5500>" + Utility.formatPrice(value) + "</col>", 60_079));
    }
References bankTab, com.runehive.util.Utility.formatPrice(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getValue(), player, com.runehive.game.world.items.containers.ItemContainer.size(), slotForTab(), tabAmounts, and com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE.
Referenced by refresh().
shift()
void com.runehive.game.world.items.containers.bank.Bank.shift ()
Percolates the null indices to the end of the stack.
Reimplemented from com.runehive.game.world.items.containers.ItemContainer.
Definition at line 473 of file Bank.java.
{
        int[] amounts = Arrays.copyOf(tabAmounts, tabAmounts.length);
        super.shift();
        amounts = Arrays.copyOf(amounts, amounts.length);
        System.arraycopy(amounts, 0, tabAmounts, 0, amounts.length);
    }
References tabAmounts.
Referenced by collapse(), and withdraw().
slotForTab()
int com.runehive.game.world.items.containers.bank.Bank.slotForTab (int tab) private
Definition at line 458 of file Bank.java.
{
        int passed = -1;
        for (int index = tab; index >= 0; index--) {
            passed += tabAmounts[index];
        }
        return passed;
    }
References tabAmounts.
Referenced by deposit(), depositFromNothing(), itemToTab(), moveTab(), and sendValue().
tabForSlot()
int com.runehive.game.world.items.containers.bank.Bank.tabForSlot (int slot)
Definition at line 446 of file Bank.java.
{
        if (slot <= -1)
            return -1;
        int passed = -1;
        for (int tab = 0; tab < tabAmounts.length; tab++) {
            if (slot <= passed + tabAmounts[tab])
                return tab;
            passed += tabAmounts[tab];
        }
        return -1;
    }
References tabAmounts.
Referenced by itemToTab(), moveItem(), and withdraw().
withdraw()
void com.runehive.game.world.items.containers.bank.Bank.withdraw (int itemId, int slot, int amount)
Withdraws item from bank.
Definition at line 188 of file Bank.java.
{
        if (!player.interfaceManager.isInterfaceOpen(60000)) {
            return;
        }
        slot = computeIndexForId(itemId);
        if (itemId < 0) return;
        Item item = get(slot);
        if (item == null || itemId != item.getId())
            return;
        if (item.getAmount() == 0) {//Releasing place holders
            boolean hold = placeHolder;
            placeHolder = false;
            int tabSlot = computeIndexForId(item.getId());
            int tab = tabForSlot(tabSlot);
            changeTabAmount(tab, -1);
            remove(item);
            shift();
            placeHolder = hold;
            refresh();
            return;
        }
        if (item.getAmount() < amount) {
            amount = item.getAmount();
        }
        int id = item.getId();
        if (noting) {
            if (!item.isNoteable()) {
                player.send(new SendMessage("This item cannot be withdrawn as a note."));
            } else {
                id = item.getNotedId();
            }
        }
        setFiringEvents(false);
        if (!new Item(id).isStackable() && amount > player.inventory.getFreeSlots()) {
            amount = player.inventory.getFreeSlots();
        } else if (ItemDefinition.get(id).isStackable() && player.inventory.getFreeSlots() == 0) {
            if (!player.inventory.contains(id)) {
                amount = 0;
            } else if (player.inventory.computeAmountForId(id) + amount > Integer.MAX_VALUE) {
                amount = Integer.MAX_VALUE - player.inventory.computeAmountForId(id);
            }
        }
        if (amount == 0) {
            player.send(new SendMessage("You do not have enough inventory spaces to withdraw this item."));
            return;
        }
        int fuckingSlot = player.inventory.computeIndexForId(id);
        if (fuckingSlot != -1) {
            Item fuckingStan = player.inventory.get(fuckingSlot);
            if (Integer.MAX_VALUE - fuckingStan.getAmount() < amount) {
                amount = Integer.MAX_VALUE - fuckingStan.getAmount();
                player.send(new SendMessage("Your inventory didn't have enough space to withdraw all that!"));
            }
        }
        if (remove(item.getId(), amount)) {
            player.inventory.add(id, amount);
            if(id == 12791) player.runePouch.refresh();
            // when an item is taken out of the bank completely, it removes one amount from the tab amounts array
            if (!contains(item.getId())) {
                int tab = tabForSlot(slot);
                changeTabAmount(tab, -1);
                shift();
            }
        }
        setFiringEvents(true);
        refresh();
    }
References changeTabAmount(), com.runehive.game.world.items.containers.ItemContainer.computeIndexForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getNotedId(), com.runehive.game.world.items.Item.isNoteable(), noting, placeHolder, player, refresh(), com.runehive.game.world.items.containers.ItemContainer.setFiringEvents(), shift(), and tabForSlot().
Referenced by placeHolder().
Member Data Documentation
bankTab
int com.runehive.game.world.items.containers.bank.Bank.bankTab = 0
The current bank tab.
Definition at line 36 of file Bank.java.
Referenced by collapse(), deposit(), depositeEquipment(), depositeInventory(), and sendValue().
inserting
boolean com.runehive.game.world.items.containers.bank.Bank.inserting = false
The inserting flag.
Definition at line 42 of file Bank.java.
Referenced by refresh().
noting
boolean com.runehive.game.world.items.containers.bank.Bank.noting = false
The noting flag.
Definition at line 39 of file Bank.java.
Referenced by open(), refresh(), and withdraw().
placeHolder
boolean com.runehive.game.world.items.containers.bank.Bank.placeHolder
The place holder flag.
Definition at line 45 of file Bank.java.
Referenced by allowZero(), placeHolder(), refresh(), and withdraw().
player
final Player com.runehive.game.world.items.containers.bank.Bank.player private
The player instance.
Definition at line 33 of file Bank.java.
Referenced by Bank(), close(), collapse(), deposit(), depositeEquipment(), depositeInventory(), open(), refresh(), sendValue(), and withdraw().
SIZE
final int com.runehive.game.world.items.containers.bank.Bank.SIZE = 360 static
The size of all equipment instances.
Definition at line 27 of file Bank.java.
Referenced by Bank().
tabAmounts
int [] com.runehive.game.world.items.containers.bank.Bank.tabAmounts = new int[10]
The tab amount array.
Definition at line 30 of file Bank.java.
Referenced by changeTabAmount(), clear(), collapse(), depositeEquipment(), depositeInventory(), itemToTab(), moveTab(), recursiveCollapse(), refresh(), sendValue(), shift(), slotForTab(), and tabForSlot().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/bank/Bank.java