RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy Class Reference
com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy Class Reference
Public Member Functions
void attack (Player attacker, Mob defender, Hit hit)
boolean canAttack (Player attacker, Mob defender)
Animation getAttackAnimation (Player attacker, Mob defender)
int getAttackDelay (Player attacker, Mob defender, FightType fightType)
int getAttackDistance (Player attacker, FightType fightType)
CombatType getCombatType ()
CombatHit[] getHits (Player attacker, Mob defender)
void hit (Player attacker, Mob defender, Hit hit)
void start (Player attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static PlayerRangedStrategy get ()
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions
PlayerRangedStrategy ()
void sendStuff (Player attacker, Mob defender)
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Private Member Functions
void removeAmmunition (Player attacker, Mob defender, RangedWeaponType type)
Static Private Attributes
static final PlayerRangedStrategy INSTANCE = new PlayerRangedStrategy()
Additional Inherited Members
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Definition at line 34 of file PlayerRangedStrategy.java.
Constructor & Destructor Documentation
PlayerRangedStrategy()
com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.PlayerRangedStrategy () protected
Definition at line 38 of file PlayerRangedStrategy.java.
{
    }
Referenced by get().
Member Function Documentation
attack()
void com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack (Player attacker, Mob defender, Hit hit)
Definition at line 117 of file PlayerRangedStrategy.java.
{
        removeAmmunition(attacker, defender, attacker.rangedDefinition.getType());
        if (hit.getDamage() > 1 && attacker.rangedDefinition != null) {
            Item item = attacker.equipment.get(attacker.rangedDefinition.getSlot());
            CombatPoisonEffect.getPoisonType(item).ifPresent(defender::poison);
        }
        Item weapon = attacker.equipment.get(Equipment.WEAPON_SLOT);
        if(weapon != null) {
            switch(weapon.getId()) {
                case CrawsBow.CRAWS_CHARGED_ID -> {
                    attacker.crawsBowCharges--;
                }
            }
        }
    }
References com.runehive.content.itemaction.impl.CrawsBow.CRAWS_CHARGED_ID, com.runehive.game.world.entity.mob.player.Player.crawsBowCharges, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getSlot(), com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getType(), hit(), com.runehive.game.world.entity.mob.player.Player.rangedDefinition, removeAmmunition(), and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
canAttack()
boolean com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack (Player attacker, Mob defender)
Definition at line 42 of file PlayerRangedStrategy.java.
{
        Item weapon = attacker.equipment.get(Equipment.WEAPON_SLOT);
        if (weapon == null) {
            attacker.getCombat().reset();
            return false;
        }
        if(weapon.getId() == CrawsBow.CRAWS_CHARGED_ID && attacker.crawsBowCharges < 1) {
            attacker.send(new SendMessage("Your Craw's bow is out of charges!"));
            attacker.getCombat().reset();
            return false;
        }
        if (attacker.rangedDefinition == null) {
            return false;
        }
        int bowsWithNoArrowsRequired [] = {22550, 25865, 25867, 25884, 25886, 25890, 25892, 25894, 25896, 25888};
        Item ammo = attacker.equipment.get(attacker.rangedDefinition.getSlot());
        if (ammo != null && attacker.rangedAmmo != null && ammo.getAmount() >= attacker.rangedAmmo.getRemoval()) {
            if (attacker.rangedDefinition.isValid(attacker.rangedAmmo)) {
                return true;
            }
            attacker.send(new SendMessage("You can't use this ammunition with this weapon."));
        } else if
        (attacker.equipment.contains(bowsWithNoArrowsRequired)) {
            return true;
        } else {
            attacker.send(new SendMessage("You need some ammunition to use this weapon!"));
        }
        attacker.getCombat().reset();
        return false;
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.content.itemaction.impl.CrawsBow.CRAWS_CHARGED_ID, com.runehive.game.world.entity.mob.player.Player.crawsBowCharges, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getRemoval(), com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getSlot(), com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.isValid(), com.runehive.game.world.entity.mob.player.Player.rangedAmmo, com.runehive.game.world.entity.mob.player.Player.rangedDefinition, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
get()
PlayerRangedStrategy com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.get () static
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.magic.EldritchNightmareStaff, com.runehive.game.world.entity.combat.strategy.player.special.magic.VolatileNightmareStaff, com.runehive.game.world.entity.combat.strategy.player.special.range.ArmadylCrossbow, com.runehive.game.world.entity.combat.strategy.player.special.range.Ballista, com.runehive.game.world.entity.combat.strategy.player.special.range.CrawsBow, com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow, com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife, com.runehive.game.world.entity.combat.strategy.player.special.range.DragonThrownaxe, com.runehive.game.world.entity.combat.strategy.player.special.range.MagicShortbow, and com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.
Definition at line 240 of file PlayerRangedStrategy.java.
{
        return INSTANCE;
    }
References INSTANCE, and PlayerRangedStrategy().
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.getStrategy().
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation (Player attacker, Mob defender)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.magic.EldritchNightmareStaff, com.runehive.game.world.entity.combat.strategy.player.special.magic.VolatileNightmareStaff, com.runehive.game.world.entity.combat.strategy.player.special.range.Ballista, and com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.
Definition at line 143 of file PlayerRangedStrategy.java.
{
        int animation = attacker.getCombat().getFightType().getAnimation();
        if (attacker.equipment.hasShield()) {
            Item weapon = attacker.equipment.getShield();
            FightType fightType = attacker.getCombat().getFightType();
            animation = weapon.getAttackAnimation(fightType).orElse(animation);
        }
        if (attacker.equipment.hasWeapon()) {
            Item weapon = attacker.equipment.getWeapon();
            FightType fightType = attacker.getCombat().getFightType();
            animation = weapon.getAttackAnimation(fightType).orElse(animation);
        }
        if (attacker.overrides.hasOverride(Equipment.WEAPON_SLOT)) {
            final var item = attacker.overrides.get(Equipment.WEAPON_SLOT);
            animation = attacker.overrides.getFightType(item).getAnimation();
        }
        return new Animation(animation, UpdatePriority.HIGH);
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.content.overrides.Overrides.get(), com.runehive.game.world.entity.combat.attack.FightType.getAnimation(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.content.overrides.Overrides.getFightType(), com.runehive.game.world.items.containers.equipment.Equipment.getShield(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.content.overrides.Overrides.hasOverride(), com.runehive.game.world.items.containers.equipment.Equipment.hasShield(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), com.runehive.game.UpdatePriority.HIGH, com.runehive.game.world.entity.mob.player.Player.overrides, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by sendStuff().
getAttackDelay()
int com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackDelay (Player attacker, Mob defender, FightType fightType)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.magic.EldritchNightmareStaff, com.runehive.game.world.entity.combat.strategy.player.special.magic.VolatileNightmareStaff, and com.runehive.game.world.entity.combat.strategy.player.special.range.Ballista.
Definition at line 167 of file PlayerRangedStrategy.java.
{
        return attacker.getCombat().getFightType().getDelay();
    }
References com.runehive.game.world.entity.mob.player.Player.getCombat().
getAttackDistance()
int com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackDistance (Player attacker, FightType fightType)
Definition at line 172 of file PlayerRangedStrategy.java.
{
        return fightType.getDistance();
    }
References com.runehive.game.world.entity.combat.attack.FightType.getDistance().
getCombatType()
CombatType com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getCombatType ()
Reimplemented from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
Definition at line 187 of file PlayerRangedStrategy.java.
{
        return CombatType.RANGED;
    }
References com.runehive.game.world.entity.combat.CombatType.RANGED.
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getHits (Player attacker, Mob defender)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.magic.EldritchNightmareStaff, com.runehive.game.world.entity.combat.strategy.player.special.magic.VolatileNightmareStaff, com.runehive.game.world.entity.combat.strategy.player.special.range.ArmadylCrossbow, com.runehive.game.world.entity.combat.strategy.player.special.range.Ballista, com.runehive.game.world.entity.combat.strategy.player.special.range.CrawsBow, com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow, com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife, com.runehive.game.world.entity.combat.strategy.player.special.range.DragonThrownaxe, com.runehive.game.world.entity.combat.strategy.player.special.range.MagicShortbow, and com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.
Definition at line 177 of file PlayerRangedStrategy.java.
{
        RangedAmmunition ammo = attacker.rangedAmmo;
        CombatHit[] hits = new CombatHit[ammo.getRemoval()];
        for (int index = 0; index < hits.length; index++) {
            hits[index] = nextRangedHit(attacker, defender);
        }
        return hits;
    }
References com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getRemoval(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit(), and com.runehive.game.world.entity.mob.player.Player.rangedAmmo.
hit()
void com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.hit (Player attacker, Mob defender, Hit hit)
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow, and com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife.
Definition at line 135 of file PlayerRangedStrategy.java.
{
        if (attacker.rangedAmmo != null && attacker.rangedDefinition != null) {
            int id = attacker.equipment.retrieve(attacker.rangedDefinition.getSlot()).map(Item::getId).orElse(-1);
            attacker.rangedAmmo.getEnd(id).ifPresent(defender::graphic);
        }
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getEnd(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getSlot(), hit(), com.runehive.game.world.entity.mob.player.Player.rangedAmmo, com.runehive.game.world.entity.mob.player.Player.rangedDefinition, and com.runehive.game.world.items.containers.ItemContainer.retrieve().
Referenced by attack(), hit(), com.runehive.game.world.entity.combat.strategy.player.special.magic.EldritchNightmareStaff.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.magic.VolatileNightmareStaff.hitsplat(), com.runehive.game.world.entity.combat.strategy.player.special.range.Ballista.hitsplat(), and start().
removeAmmunition()
void com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition (Player attacker, Mob defender, RangedWeaponType type) private
Definition at line 191 of file PlayerRangedStrategy.java.
{
        Item next = attacker.equipment.get(type.getSlot());
        if (next == null) return;
        if (attacker.rangedAmmo.isDroppable()) {
            Item dropItem = new Item(next.getId());
            boolean canBreak = !dropItem.getName().contains("arrow") || !attacker.prestige.hasPerk(PrestigePerk.ARROWHEAD);
            if (!canBreak || RandomUtils.success(0.80)) {
                if (Equipment.hasAssembler(attacker) /* AKA 100% */) {
                    return;
                }
                if (Equipment.hasAccumulator(attacker) && RandomUtils.success(0.90)) {
                    return;
                }
                if (Equipment.hasAttractor(attacker) && RandomUtils.success(0.80)) {
                    return;
                }
                Position dropPoisition = defender.getPosition();
                if (Area.inKraken(attacker) || Area.inZulrah(attacker)) {
                    dropPoisition = attacker.getPosition();
                }
                GroundItem.create(attacker, dropItem, dropPoisition);
            }
        }
        final int bowsWithNoArrowsRequired [] = {22550, 25865, 25867, 25884, 25886, 25890, 25892, 25894, 25896, 25888};
        if (attacker.equipment.contains(bowsWithNoArrowsRequired)) {
            return;
        } else {
            next.decrementAmount();
        }
        if (next.getAmount() == 0 && !attacker.equipment.contains(bowsWithNoArrowsRequired)) {
            attacker.send(new SendMessage("That was the last of your ammunition!"));
            next = null;
        }
        attacker.equipment.set(type.getSlot(), next, false);
        attacker.equipment.refresh();
        attacker.updateFlags.add(UpdateFlag.APPEARANCE);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.prestige.PrestigePerk.ARROWHEAD, com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.items.Item.decrementAmount(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.combat.ranged.RangedWeaponType.getSlot(), com.runehive.game.world.items.containers.equipment.Equipment.hasAccumulator(), com.runehive.game.world.items.containers.equipment.Equipment.hasAssembler(), com.runehive.game.world.items.containers.equipment.Equipment.hasAttractor(), com.runehive.content.prestige.Prestige.hasPerk(), com.runehive.game.world.position.Area.inKraken(), com.runehive.game.world.position.Area.inZulrah(), com.runehive.game.world.entity.combat.ranged.RangedAmmunition.isDroppable(), com.runehive.game.world.entity.mob.player.Player.prestige, com.runehive.game.world.entity.mob.player.Player.rangedAmmo, com.runehive.game.world.items.containers.equipment.Equipment.refresh(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.items.containers.ItemContainer.set(), com.runehive.util.RandomUtils.success(), and com.runehive.game.world.entity.mob.Mob.updateFlags.
Referenced by attack().
sendStuff()
void com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff (Player attacker, Mob defender) protected
Reimplemented in com.runehive.game.world.entity.combat.strategy.player.special.range.ArmadylCrossbow, com.runehive.game.world.entity.combat.strategy.player.special.range.CrawsBow, com.runehive.game.world.entity.combat.strategy.player.special.range.DarkBow, com.runehive.game.world.entity.combat.strategy.player.special.range.DragonKnife, com.runehive.game.world.entity.combat.strategy.player.special.range.DragonThrownaxe, com.runehive.game.world.entity.combat.strategy.player.special.range.MagicShortbow, and com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.
Definition at line 77 of file PlayerRangedStrategy.java.
{
        int id = attacker.equipment.get(attacker.rangedDefinition.getSlot()).getId();
        Animation animation = attacker.rangedAmmo.getAnimation(id).orElse(getAttackAnimation(attacker, defender));
        attacker.animate(animation, true);
        attacker.rangedAmmo.getStart(id).ifPresent(attacker::graphic);
        attacker.rangedAmmo.sendProjectile(attacker, defender);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getAnimation(), getAttackAnimation(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getSlot(), com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getStart(), com.runehive.game.world.entity.mob.player.Player.rangedAmmo, com.runehive.game.world.entity.mob.player.Player.rangedDefinition, and com.runehive.game.world.entity.combat.ranged.RangedAmmunition.sendProjectile().
Referenced by start().
start()
void com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start (Player attacker, Mob defender, Hit[] hits)
Definition at line 86 of file PlayerRangedStrategy.java.
{
        if (attacker.isSpecialActivated()) {
            attacker.getCombatSpecial().drain(attacker);
        }
        if (attacker.getCombat().getDefender() == defender) {
            sendStuff(attacker, defender);
            int id = attacker.equipment.get(attacker.rangedDefinition.getSlot()).getId();
            if (attacker.rangedAmmo.getEffect(id).isPresent()) {
                List<Hit> extra = new LinkedList<>();
                for (Hit hit : hits) {
                    Predicate<CombatImpact> filter = effect -> effect.canAffect(attacker, defender, hit);
                    Consumer<CombatImpact> execute = effect -> effect.impact(attacker, defender, hit, extra);
                    attacker.rangedAmmo.getEffect(id).filter(filter).ifPresent(execute);
                }
                if (!defender.isPlayer() || !PlayerRight.isIronman(attacker)) {
                    if (extra.isEmpty()) {
                        Collections.addAll(extra, hits);
                        addCombatExperience(attacker, extra.toArray(new Hit[0]));
                    } else {
                        addCombatExperience(attacker, hits);
                    }
                }
            } else if (!defender.isPlayer() || !PlayerRight.isIronman(attacker)) {
                addCombatExperience(attacker, hits);
            }
        }
    }
References com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.addCombatExperience(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.drain(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.entity.mob.player.Player.getCombatSpecial(), com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getEffect(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getSlot(), hit(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.player.Player.isSpecialActivated(), com.runehive.game.world.entity.mob.player.Player.rangedAmmo, com.runehive.game.world.entity.mob.player.Player.rangedDefinition, and sendStuff().
Member Data Documentation
INSTANCE
final PlayerRangedStrategy com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.INSTANCE = new PlayerRangedStrategy() static private
Definition at line 36 of file PlayerRangedStrategy.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/PlayerRangedStrategy.java