RuneHive-Game: com.runehive.game.world.entity.mob.player.persist.PlayerSerializer Class Reference
com.runehive.game.world.entity.mob.player.persist.PlayerSerializer Class Reference
Static Public Member Functions
static LoginResponse load (Player player, String expectedPassword)
static void save (Player player)
Static Private Attributes
static final PlayerPersistable perstable
Detailed Description
Definition at line 7 of file PlayerSerializer.java.
Member Function Documentation
load()
LoginResponse com.runehive.game.world.entity.mob.player.persist.PlayerSerializer.load (Player player, String expectedPassword) static
Definition at line 28 of file PlayerSerializer.java.
{
        if (player.isBot) {
            return LoginResponse.COULD_NOT_COMPLETE_LOGIN;
        }
        return perstable.load(player, expectedPassword);
    }
References com.runehive.net.codec.login.LoginResponse.COULD_NOT_COMPLETE_LOGIN, and perstable.
Referenced by com.runehive.net.session.LoginSession.evaluate().
save()
void com.runehive.game.world.entity.mob.player.persist.PlayerSerializer.save (Player player) static
Definition at line 13 of file PlayerSerializer.java.
{
        if (player.isBot) {
            return;
        }
        // player save thread
        Thread.startVirtualThread(() -> {
            try {
                perstable.save(player);
            } catch (final Exception e) {
                e.printStackTrace();
            }
        });
    }
References perstable.
Referenced by com.runehive.content.skill.impl.hunter.birdhouse.action.FillBirdhouse.execute(), com.runehive.content.skill.impl.hunter.birdhouse.action.PlaceBirdhouse.execute(), com.runehive.game.task.impl.PlayerSaveEvent.execute(), com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.world.World.save(), and com.runehive.game.task.impl.PlayerRemovalTask.tick().
Member Data Documentation
perstable
final PlayerPersistable com.runehive.game.world.entity.mob.player.persist.PlayerSerializer.perstable static private
Initial value:
= Config.FORUM_INTEGRATION
            ? new PlayerPersistDB()
            : new PlayerPersistFile()
Definition at line 9 of file PlayerSerializer.java.
Referenced by load(), and save().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/persist/PlayerSerializer.java