RuneHive-Game: com.runehive.util.StringUtils Class Reference
com.runehive.util.StringUtils Class Reference
Static Public Member Functions
static String appendIndefiniteArticle (String thing)
Appends the determined indefinite article to thing.
static String appendPluralCheck (String thing)
Appends the determined plural check to thing.
static String capitalize (String string)
static int convertAmount (String input)
static String format (int num)
static String formatPrice (long amount)
static String formatText (String s)
static String getAOrAn (String nextWord)
static long hash (String input)
Hashes a given string input.
static int hashArchive (String string)
Hashes a String using Jagex's algorithm, this method should be used to convert actual names to hashed names to lookup files within the FileSystem.
static String hashToString (long input)
Static Private Member Functions
static int _hash (String string)
Hashes a String using Jagex's algorithm, this method should be used to convert actual names to hashed names to lookup files within the FileSystem.
static String determineIndefiniteArticle (String thing)
Determines the indefinite article of thing.
static String determinePluralCheck (String thing)
Determines the plural check of thing.
Static Private Attributes
static final char VALID_USERNAME_CHARACTERS []
An array containing valid username characters.
Detailed Description
Definition at line 8 of file StringUtils.java.
Member Function Documentation
_hash()
int com.runehive.util.StringUtils._hash (String string) static private
Hashes a String using Jagex's algorithm, this method should be used to convert actual names to hashed names to lookup files within the FileSystem.
This method should only be used internally, it is marked deprecated as it does not properly hash the specified String. The functionality of this method is used to register a proper String hashing method. The scope of this method has been marked as private to prevent confusion.
Parameters
string The string to hash.
Returns
The hashed string.
Deprecated
This method should only be used internally as it does not correctly hash the specified String. See the note below for more information.
Definition at line 202 of file StringUtils.java.
{
        return IntStream.range(0, string.length()).reduce(0, (hash, index) -> hash * 61 + string.charAt(index) - 32);
    }
References hash().
Referenced by hashArchive().
appendIndefiniteArticle()
String com.runehive.util.StringUtils.appendIndefiniteArticle (String thing) static
Appends the determined indefinite article to thing.
Parameters
thing the thing to append.
Returns
the thing after the indefinite article has been appended.
Definition at line 96 of file StringUtils.java.
{
        return determineIndefiniteArticle(thing).concat(" " + thing);
    }
References determineIndefiniteArticle().
Referenced by com.runehive.content.skill.impl.smithing.SmithingArmour.canInit(), com.runehive.content.skill.impl.HarvestingSkillAction.canRun(), and com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject().
appendPluralCheck()
String com.runehive.util.StringUtils.appendPluralCheck (String thing) static
Appends the determined plural check to thing.
Parameters
thing the thing to append.
Returns
the thing after the plural check has been appended.
Definition at line 86 of file StringUtils.java.
{
        return thing.concat(determinePluralCheck(thing));
    }
References determinePluralCheck().
Referenced by com.runehive.content.skill.impl.ProducingSkillAction.canRun().
capitalize()
String com.runehive.util.StringUtils.capitalize (String string) static
Definition at line 100 of file StringUtils.java.
{
        return Character.toUpperCase(string.charAt(0)) + string.substring(1);
    }
Referenced by com.runehive.content.skill.impl.smithing.SmithingTable.AdamantTable.AdamantTable(), com.runehive.content.skill.impl.smithing.SmithingTable.BronzeTable.BronzeTable(), com.runehive.content.skill.impl.smithing.SmithingTable.IronTable.IronTable(), com.runehive.content.skill.impl.smithing.SmithingTable.MithrilTable.MithrilTable(), com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface(), com.runehive.content.skill.impl.smithing.SmithingTable.RuniteTable.RuniteTable(), com.runehive.content.lms.LMSGame.setupSafezone(), and com.runehive.content.skill.impl.smithing.SmithingTable.SteelTable.SteelTable().
convertAmount()
int com.runehive.util.StringUtils.convertAmount (String input) static
Definition at line 29 of file StringUtils.java.
{
        try {
            input = input.toLowerCase().replace(" ", "");
            int pos = input.indexOf('k');
            if (pos != -1) {
                return Integer.parseInt(input.substring(0, pos)) * 1_000;
            }
            pos = input.indexOf('m');
            if (pos != -1) {
                return Integer.parseInt(input.substring(0, pos)) * 1_000_000;
            }
            pos = input.indexOf('b');
            if (pos != -1) {
                return Integer.parseInt(input.substring(0, pos)) * 1_000_000_000;
            }
        } catch (Exception ex) {
        }
        return 0;
    }
determineIndefiniteArticle()
String com.runehive.util.StringUtils.determineIndefiniteArticle (String thing) static private
Determines the indefinite article of thing.
Parameters
thing the thing to determine for.
Returns
the indefinite article.
Definition at line 63 of file StringUtils.java.
{
        char first = thing.toLowerCase().charAt(0);
        boolean vowel = first == 'a' || first == 'e' || first == 'i' || first == 'o' || first == 'u';
        return vowel ? "an" : "a";
    }
Referenced by appendIndefiniteArticle().
determinePluralCheck()
String com.runehive.util.StringUtils.determinePluralCheck (String thing) static private
Determines the plural check of thing.
Parameters
thing the thing to determine for.
Returns
the plural check.
Definition at line 75 of file StringUtils.java.
{
        boolean needsPlural = !thing.endsWith("s") && !thing.endsWith(")");
        return needsPlural ? "s" : "";
    }
Referenced by appendPluralCheck().
format()
String com.runehive.util.StringUtils.format (int num) static
Definition at line 104 of file StringUtils.java.
{
        return NumberFormat.getInstance().format(num);
    }
formatPrice()
String com.runehive.util.StringUtils.formatPrice (long amount) static
Definition at line 18 of file StringUtils.java.
{
        if (amount >= 1_000 && amount < 1_000_000) {
            return (amount / 1_000) + "K";
        } else if (amount >= 1_000_000 && amount < 1_000_000_000) {
            return (amount / 1_000_000) + "M";
        } else if (amount >= 1_000_000_000) {
            return (amount / 1_000_000_000) + "B";
        }
        return "" + amount;
    }
formatText()
String com.runehive.util.StringUtils.formatText (String s) static
Definition at line 108 of file StringUtils.java.
{
        for (int i = 0; i < s.length(); i++) {
            if (i == 0) {
                s = String.format("%s%s", Character.toUpperCase(s.charAt(0)), s.substring(1));
            }
            if (!Character.isLetterOrDigit(s.charAt(i))) {
                if (i + 1 < s.length()) {
                    s = String.format("%s%s%s", s.subSequence(0, i + 1), Character.toUpperCase(s.charAt(i + 1)), s.substring(i + 2));
                }
            }
        }
        return s.replace("_", " ");
    }
getAOrAn()
String com.runehive.util.StringUtils.getAOrAn (String nextWord) static
Definition at line 122 of file StringUtils.java.
{
        String s = "a";
        final char c = nextWord.toUpperCase().charAt(0);
        if (c == 'A' || c == 'E' || c == 'I' || c == 'O' || c == 'U') {
            s = "an";
        }
        return s;
    }
Referenced by com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), and com.runehive.content.skill.impl.herblore.Herblore.useItem().
hash()
long com.runehive.util.StringUtils.hash (String input) static
Hashes a given string input.
Parameters
input The string to hash.
Returns
A hash as a long.
Definition at line 151 of file StringUtils.java.
{
        long hash = 0;
        for (int index = 0; index < input.length(); index++) {
            char key = input.charAt(index);
            hash *= 37;
            if (key >= 'A' && key <= 'Z') {
                hash += (1 + key) - 65;
            } else if (key >= 'a' && key <= 'z') {
                hash += (1 + key) - 97;
            } else if (key >= '0' && key <= '9') {
                hash += (27 + key) - 48;
            }
        }
        while (hash % 37 == 0 && hash != 0) hash /= 37;
        return hash;
    }
References hash().
Referenced by _hash(), hash(), and hashToString().
hashArchive()
int com.runehive.util.StringUtils.hashArchive (String string) static
Hashes a String using Jagex's algorithm, this method should be used to convert actual names to hashed names to lookup files within the FileSystem.
Parameters
string The string to hash.
Returns
The hashed string.
Definition at line 179 of file StringUtils.java.
{
        return _hash(string.toUpperCase());
    }
References _hash().
Referenced by com.runehive.fs.cache.archive.Archive.getSector().
hashToString()
String com.runehive.util.StringUtils.hashToString (long input) static
Definition at line 131 of file StringUtils.java.
{
        int length = 12;
        char decoded[] = new char[length];
        while (input != 0) {
            long hash = input;
            input /= 37;
            int index = (int) (hash - input * 37);
            decoded[length--] = VALID_USERNAME_CHARACTERS[index];
        }
        return new String(decoded, length, decoded.length - length);
    }
References hash(), and VALID_USERNAME_CHARACTERS.
Member Data Documentation
VALID_USERNAME_CHARACTERS
final char com.runehive.util.StringUtils.VALID_USERNAME_CHARACTERS[] static private
Initial value:
= {
        '_',
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
        'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
    }
An array containing valid username characters.
Definition at line 11 of file StringUtils.java.
{
        '_',
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
        'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
    };
Referenced by hashToString().
The documentation for this class was generated from the following file:
java/com/runehive/util/StringUtils.java