RuneHive-Game: com.runehive.content.Waypoints Class Reference
com.runehive.content.Waypoints Class Reference
Static Public Member Functions
static void getWaypoints (Player player)
static void removeWaypoint (Player player, String waypointName)
static void setWaypoint (Player player, String waypointName)
Static Private Member Functions
static int getAllowedPoints (Player player)
Detailed Description
Definition at line 7 of file Waypoints.java.
Member Function Documentation
getAllowedPoints()
int com.runehive.content.Waypoints.getAllowedPoints (Player player) static private
Definition at line 38 of file Waypoints.java.
{
        return switch (player.right.getName()) {
            case "King Donator" -> 10;
            case "Elite Donator" -> 8;
            case "Extreme Donator" -> 6;
            case "Super Donator" -> 4;
            case "Donator" -> 2;
            default -> 5;
        };
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.getName(), and com.runehive.game.world.entity.mob.player.Player.right.
Referenced by setWaypoint().
getWaypoints()
void com.runehive.content.Waypoints.getWaypoints (Player player) static
Definition at line 30 of file Waypoints.java.
{
        if (player.waypoints.isEmpty()) {
            player.message("You have no waypoints set.");
            return;
        }
        player.message("Current waypoints:");
        player.waypoints.forEach((k, v) -> player.message("@red@" +k));
    }
References com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.entity.mob.player.Player.waypoints.
removeWaypoint()
void com.runehive.content.Waypoints.removeWaypoint (Player player, String waypointName) static
Definition at line 26 of file Waypoints.java.
{
        player.waypoints.remove(waypointName);
        player.dialogueFactory.sendStatement("You have removed " + waypointName + " from your waypoints.").execute();
    }
References com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and com.runehive.game.world.entity.mob.player.Player.waypoints.
setWaypoint()
void com.runehive.content.Waypoints.setWaypoint (Player player, String waypointName) static
Definition at line 9 of file Waypoints.java.
{
        if(Area.inRestrictedArea(player)) {
            player.message("You cannot set a waypoint here");
            return;
        }
        if (player.waypoints.size() >= getAllowedPoints(player)) {
            player.message("You have reached the maximum amount of waypoints allowed for your rank.");
            return;
        }
        if (player.waypoints.containsKey(waypointName)) {
            player.message("You already have a waypoint with this name.");
            return;
        }
        player.waypoints.put(waypointName, player.getPosition().copy());
        player.dialogueFactory.sendStatement("You have set a waypoint named " + waypointName + " at your current location.").execute();
    }
References com.runehive.game.world.position.Position.copy(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), getAllowedPoints(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Area.inRestrictedArea(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and com.runehive.game.world.entity.mob.player.Player.waypoints.
The documentation for this class was generated from the following file:
java/com/runehive/content/Waypoints.java