RuneHive-Game: com.runehive.content.lms.loadouts.LMSLoadout Class Reference
com.runehive.content.lms.loadouts.LMSLoadout Class Reference abstract
Public Member Functions
abstract int[] getDefensiveItem ()
abstract int[] getEquipment ()
ItemContainer getEquipmentSetup ()
abstract int[] getInventory ()
ItemContainer getInventorySetup ()
abstract int[] getOffensiveItem ()
abstract int[] getOffensiveItemUpgrades ()
abstract int[][] getRunePouchRunes ()
int[] getSkills ()
abstract Spellbook getSpellbook ()
void setup ()
Static Public Attributes
static int[] equipmentOrder = { 0, 1, 2, 13, 3, 4, 5, 7, 9, 10, 12 }
Protected Member Functions
abstract int getAttackLevel ()
abstract int getDefenceLevel ()
abstract int getHitpointsLevel ()
abstract int getMagicLevel ()
abstract int getPrayerLevel ()
abstract int getRangedLevel ()
abstract int getStrengthLevel ()
Protected Attributes
ItemContainer equipmentSetup = new ItemContainer(14, ItemContainer.StackPolicy.STANDARD)
ItemContainer inventorySetup = new ItemContainer(28, ItemContainer.StackPolicy.STANDARD)
Detailed Description
Definition at line 8 of file LMSLoadout.java.
Member Function Documentation
getAttackLevel()
abstract int com.runehive.content.lms.loadouts.LMSLoadout.getAttackLevel () abstract protected
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by getSkills().
getDefenceLevel()
abstract int com.runehive.content.lms.loadouts.LMSLoadout.getDefenceLevel () abstract protected
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by getSkills().
getDefensiveItem()
abstract int[] com.runehive.content.lms.loadouts.LMSLoadout.getDefensiveItem () abstract
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by com.runehive.content.lms.LMSGame.rollChest().
getEquipment()
abstract int[] com.runehive.content.lms.loadouts.LMSLoadout.getEquipment () abstract
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by setup().
getEquipmentSetup()
ItemContainer com.runehive.content.lms.loadouts.LMSLoadout.getEquipmentSetup ()
Definition at line 14 of file LMSLoadout.java.
{
        return equipmentSetup;
    }
References equipmentSetup.
Referenced by com.runehive.content.lms.LMSGame.giveItems().
getHitpointsLevel()
abstract int com.runehive.content.lms.loadouts.LMSLoadout.getHitpointsLevel () abstract protected
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by getSkills().
getInventory()
abstract int[] com.runehive.content.lms.loadouts.LMSLoadout.getInventory () abstract
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by com.runehive.content.lms.LMSGame.resupplyKiller(), and setup().
getInventorySetup()
ItemContainer com.runehive.content.lms.loadouts.LMSLoadout.getInventorySetup ()
Definition at line 20 of file LMSLoadout.java.
{
        return inventorySetup;
    }
References inventorySetup.
Referenced by com.runehive.content.lms.LMSGame.giveItems().
getMagicLevel()
abstract int com.runehive.content.lms.loadouts.LMSLoadout.getMagicLevel () abstract protected
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by getSkills().
getOffensiveItem()
abstract int[] com.runehive.content.lms.loadouts.LMSLoadout.getOffensiveItem () abstract
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by com.runehive.content.lms.LMSGame.rollChest().
getOffensiveItemUpgrades()
abstract int[] com.runehive.content.lms.loadouts.LMSLoadout.getOffensiveItemUpgrades () abstract
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by com.runehive.content.lms.LMSGame.rollChest().
getPrayerLevel()
abstract int com.runehive.content.lms.loadouts.LMSLoadout.getPrayerLevel () abstract protected
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by getSkills().
getRangedLevel()
abstract int com.runehive.content.lms.loadouts.LMSLoadout.getRangedLevel () abstract protected
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by getSkills().
getRunePouchRunes()
abstract int[][] com.runehive.content.lms.loadouts.LMSLoadout.getRunePouchRunes () abstract
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by com.runehive.content.lms.LMSGame.giveItems().
getSkills()
int[] com.runehive.content.lms.loadouts.LMSLoadout.getSkills ()
Definition at line 64 of file LMSLoadout.java.
{
        return new int[] { getAttackLevel(), getDefenceLevel(), getStrengthLevel(), getHitpointsLevel(), getRangedLevel(), getPrayerLevel(), getMagicLevel() };
    }
References getAttackLevel(), getDefenceLevel(), getHitpointsLevel(), getMagicLevel(), getPrayerLevel(), getRangedLevel(), and getStrengthLevel().
getSpellbook()
abstract Spellbook com.runehive.content.lms.loadouts.LMSLoadout.getSpellbook () abstract
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by com.runehive.content.lms.LMSGame.giveItems().
getStrengthLevel()
abstract int com.runehive.content.lms.loadouts.LMSLoadout.getStrengthLevel () abstract protected
Reimplemented in com.runehive.content.lms.loadouts.impl.Max, com.runehive.content.lms.loadouts.impl.Pure, and com.runehive.content.lms.loadouts.impl.Zerk.
Referenced by getSkills().
setup()
void com.runehive.content.lms.loadouts.LMSLoadout.setup ()
Definition at line 24 of file LMSLoadout.java.
{
        for(int index = 0; index < LMSLoadout.equipmentOrder.length; index++)
            equipmentSetup.set(LMSLoadout.equipmentOrder[index], new Item(getEquipment()[index], LMSLoadout.equipmentOrder[index] == 13 ? 5000 : 1), false);
        for(int index = 0; index < getInventory().length; index++) {
            int itemId = getInventory()[index];
            if(itemId == -1) continue;
            inventorySetup.set(index, new Item(itemId), false);
        }
    }
References equipmentOrder, equipmentSetup, getEquipment(), getInventory(), and inventorySetup.
Referenced by com.runehive.content.lms.loadouts.LMSLoadoutManager.load().
Member Data Documentation
equipmentOrder
int [] com.runehive.content.lms.loadouts.LMSLoadout.equipmentOrder = { 0, 1, 2, 13, 3, 4, 5, 7, 9, 10, 12 } static
Definition at line 10 of file LMSLoadout.java.
{ 0, 1, 2, 13, 3, 4, 5, 7, 9, 10, 12 };
Referenced by setup().
equipmentSetup
ItemContainer com.runehive.content.lms.loadouts.LMSLoadout.equipmentSetup = new ItemContainer(14, ItemContainer.StackPolicy.STANDARD) protected
Definition at line 12 of file LMSLoadout.java.
Referenced by getEquipmentSetup(), and setup().
inventorySetup
ItemContainer com.runehive.content.lms.loadouts.LMSLoadout.inventorySetup = new ItemContainer(28, ItemContainer.StackPolicy.STANDARD) protected
Definition at line 18 of file LMSLoadout.java.
Referenced by getInventorySetup(), and setup().
The documentation for this class was generated from the following file:
java/com/runehive/content/lms/loadouts/LMSLoadout.java