RuneHive-Game: com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener Class Reference
com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener Class Reference
An ItemContainerAdapter implementation that listens for changes to equipment.
Public Member Functions
void bulkItemsUpdated (ItemContainer container)
Fired when an Items are added, removed, or replaced in bulk.
String getCapacityExceededMsg ()
int getWidgetId ()
void itemUpdated (ItemContainer container, Optional< Item > oldItem, Optional< Item > newItem, int index, boolean refresh, boolean login)
Fired when an Item is added, removed, or replaced.
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainerAdapter
void capacityExceeded (ItemContainer container)
Fired when the capacity of container is exceeded.
ItemContainerAdapter (Player player)
Creates a new ItemContainerAdapter.
Package Functions
EquipmentListener ()
Creates a new EquipmentListener.
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.world.items.containers.ItemContainerAdapter
void sendItemsToWidget (ItemContainer container)
Queues a message that displays items from an ItemContainer on a widget.
Detailed Description
An ItemContainerAdapter implementation that listens for changes to equipment.
Definition at line 754 of file Equipment.java.
Constructor & Destructor Documentation
EquipmentListener()
com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.EquipmentListener () package
Creates a new EquipmentListener.
Definition at line 757 of file Equipment.java.
{
            super(player);
        }
References com.runehive.game.world.items.containers.ItemContainerAdapter.player.
Member Function Documentation
bulkItemsUpdated()
void com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.bulkItemsUpdated (ItemContainer container)
Fired when an Items are added, removed, or replaced in bulk.
This is to prevent firing multiple
itemUpdated(ItemContainer, int) events for a single operation.
Parameters
container The ItemContainer firing the randomevent.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 801 of file Equipment.java.
{
            sendItemsToWidget(container);
        }
References com.runehive.game.world.items.containers.ItemContainer.ItemContainer(), and com.runehive.game.world.items.containers.ItemContainerAdapter.sendItemsToWidget().
getCapacityExceededMsg()
String com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.getCapacityExceededMsg ()
Returns
The message sent when the ItemContainer exceeds its capacity.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 767 of file Equipment.java.
{
            throw new IllegalStateException(EXCEPTION_MESSAGE);
        }
References com.runehive.game.world.items.containers.equipment.Equipment.EXCEPTION_MESSAGE.
getWidgetId()
int com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.getWidgetId ()
Returns
The widget to display items on.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 762 of file Equipment.java.
{
            return EQUIPMENT_DISPLAY_ID;
        }
References com.runehive.game.world.items.containers.equipment.Equipment.EQUIPMENT_DISPLAY_ID.
itemUpdated()
void com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated (ItemContainer container, Optional< Item > oldItem, Optional< Item > newItem, int index, boolean refresh, boolean login)
Fired when an Item is added, removed, or replaced.
Parameters
container The ItemContainer firing the randomevent.
oldItem The old item being removed from this container.
newItem The new item being added to this container.
index The index the update is occurring on.
refresh The condition if we have to refresh this container.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 772 of file Equipment.java.
{
            if (oldItem.equals(newItem))
                return;
            boolean weapon =
                    oldItem.filter(item -> item.getWeaponInterface() != null)
                            .orElse(newItem.filter(item -> item.getWeaponInterface() != null)
                                    .orElse(null)) != null;
            oldItem.ifPresent(item -> {
                removeBonus(item);
                onRemove(item);
                CombatListenerManager.removeListener(player, item.getId());
            });
            newItem.ifPresent(item -> {
                addBonus(item);
                onEquip(item);
                CombatListenerManager.addListener(player, item.getId());
            });
            if (weapon && !login)
                WeaponInterface.execute(player, getWeapon());
            if (refresh)
                sendItemsToWidget(container);
        }
References com.runehive.game.world.items.containers.equipment.Equipment.addBonus(), com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.addListener(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.items.containers.ItemContainer.ItemContainer(), com.runehive.game.world.items.containers.equipment.Equipment.login, com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), com.runehive.game.world.items.containers.equipment.Equipment.onRemove(), com.runehive.game.world.items.containers.ItemContainerAdapter.player, com.runehive.game.world.items.containers.equipment.Equipment.refresh(), com.runehive.game.world.items.containers.equipment.Equipment.removeBonus(), com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.removeListener(), and com.runehive.game.world.items.containers.ItemContainerAdapter.sendItemsToWidget().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/equipment/Equipment.java