RuneHive-Game: com.runehive.net.codec.game.GamePacketDecoder Class Reference
com.runehive.net.codec.game.GamePacketDecoder Class Reference
The class that reads packets from the client into GamePacket's.
Classes
enum State
Represents the current state of this class.
Public Member Functions
GamePacketDecoder (IsaacCipher decryptor)
Protected Member Functions
void decode (ChannelHandlerContext ctx, ByteBuf in, List< Object > out) throws Exception
Private Member Functions
void decodeOpcode (ByteBuf in, List< Object > out)
Decodes the packet identifier.
void decodePayload (ByteBuf in, List< Object > out)
Decodes the packets payload.
void decodeSize (ByteBuf in)
Decodes the packets size.
Private Attributes
final IsaacCipher decryptor
The isaac random used to decrypt a packets opcode.
int opcode
The current packet opcode.
int size
The current packet size.
State state = State.OPCODE
The current state of this class.
PacketType type = PacketType.EMPTY
The current packet type.
Static Private Attributes
static final Logger logger = LogManager.getLogger(GamePacketDecoder.class)
The single logger for this class.
Detailed Description
The class that reads packets from the client into GamePacket's.
Author
nshusa
Definition at line 22 of file GamePacketDecoder.java.
Constructor & Destructor Documentation
GamePacketDecoder()
com.runehive.net.codec.game.GamePacketDecoder.GamePacketDecoder (IsaacCipher decryptor)
Definition at line 54 of file GamePacketDecoder.java.
{
        this.decryptor = decryptor;
    }
References decryptor.
Member Function Documentation
decode()
void com.runehive.net.codec.game.GamePacketDecoder.decode (ChannelHandlerContext ctx, ByteBuf in, List< Object > out) throws Exception protected
Definition at line 59 of file GamePacketDecoder.java.
{
        if (state == State.OPCODE) {
            decodeOpcode(in, out);
        } else if (state == State.SIZE) {
            decodeSize(in);
        } else {
            decodePayload(in, out);
        }
    }
References decodeOpcode(), decodePayload(), decodeSize(), com.runehive.net.codec.game.GamePacketDecoder.State.OPCODE, com.runehive.net.codec.game.GamePacketDecoder.State.SIZE, and state.
decodeOpcode()
void com.runehive.net.codec.game.GamePacketDecoder.decodeOpcode (ByteBuf in, List< Object > out) private
Decodes the packet identifier.
Parameters
in The payload from the client.
out The collection of upstream messages.
Definition at line 75 of file GamePacketDecoder.java.
{
        if (in.isReadable()) {
            opcode = (in.readByte() - decryptor.getKey()) & 0xFF;
            type = PacketRepository.lookupType(opcode);
            size = PacketRepository.lookupSize(opcode);
            if (type == PacketType.EMPTY) {
                state = State.OPCODE;
                out.add(new GamePacket(opcode, type, Unpooled.EMPTY_BUFFER));
            } else if (type == PacketType.FIXED) {
                state = State.PAYLOAD;
            } else if (type == PacketType.VAR_BYTE || type == PacketType.VAR_SHORT) {
                state = State.SIZE;
            } else {
                throw new IllegalStateException(String.format("Illegal packet type=%s", type.name()));
            }
        }
    }
References decryptor, com.runehive.net.packet.PacketType.EMPTY, com.runehive.net.packet.PacketType.FIXED, com.runehive.net.packet.PacketRepository.lookupSize(), com.runehive.net.packet.PacketRepository.lookupType(), com.runehive.net.codec.game.GamePacketDecoder.State.OPCODE, opcode, com.runehive.net.codec.game.GamePacketDecoder.State.PAYLOAD, com.runehive.net.codec.game.GamePacketDecoder.State.SIZE, size, state, type, com.runehive.net.packet.PacketType.VAR_BYTE, and com.runehive.net.packet.PacketType.VAR_SHORT.
Referenced by decode().
decodePayload()
void com.runehive.net.codec.game.GamePacketDecoder.decodePayload (ByteBuf in, List< Object > out) private
Decodes the packets payload.
Parameters
in The payload from the client.
out The collection of upstream messages.
Definition at line 113 of file GamePacketDecoder.java.
{
        if (in.isReadable(size)) {
            final PacketListener listener = PacketRepository.lookupListener(opcode);
            if (listener != null) {
                final ByteBuf payload = in.readBytes(size);
                final GamePacket packet = new GamePacket(opcode, type, payload);
                packet.retain();
                out.add(packet);
            } else {
                in.skipBytes(size);
                logger.info("No listener for client -> server packet={}", opcode);
            }
            state = State.OPCODE;
        }
    }
References logger, com.runehive.net.packet.PacketRepository.lookupListener(), com.runehive.net.codec.game.GamePacketDecoder.State.OPCODE, opcode, size, state, and type.
Referenced by decode().
decodeSize()
void com.runehive.net.codec.game.GamePacketDecoder.decodeSize (ByteBuf in) private
Decodes the packets size.
Parameters
in The payload from the client.
Definition at line 98 of file GamePacketDecoder.java.
{
        if (in.isReadable()) {
            size = in.readUnsignedByte();
            if (size != 0) {
                state = State.PAYLOAD;
            }
        }
    }
References com.runehive.net.codec.game.GamePacketDecoder.State.PAYLOAD, size, and state.
Referenced by decode().
Member Data Documentation
decryptor
final IsaacCipher com.runehive.net.codec.game.GamePacketDecoder.decryptor private
The isaac random used to decrypt a packets opcode.
Definition at line 32 of file GamePacketDecoder.java.
Referenced by decodeOpcode(), and GamePacketDecoder().
logger
final Logger com.runehive.net.codec.game.GamePacketDecoder.logger = LogManager.getLogger(GamePacketDecoder.class) static private
The single logger for this class.
Definition at line 27 of file GamePacketDecoder.java.
Referenced by decodePayload().
opcode
int com.runehive.net.codec.game.GamePacketDecoder.opcode private
The current packet opcode.
Definition at line 37 of file GamePacketDecoder.java.
Referenced by decodeOpcode(), and decodePayload().
size
int com.runehive.net.codec.game.GamePacketDecoder.size private
The current packet size.
Definition at line 42 of file GamePacketDecoder.java.
Referenced by decodeOpcode(), decodePayload(), and decodeSize().
state
State com.runehive.net.codec.game.GamePacketDecoder.state = State.OPCODE private
The current state of this class.
Definition at line 52 of file GamePacketDecoder.java.
Referenced by decode(), decodeOpcode(), decodePayload(), and decodeSize().
type
PacketType com.runehive.net.codec.game.GamePacketDecoder.type = PacketType.EMPTY private
The current packet type.
Definition at line 47 of file GamePacketDecoder.java.
Referenced by decodeOpcode(), and decodePayload().
The documentation for this class was generated from the following file:
java/com/runehive/net/codec/game/GamePacketDecoder.java