RuneHive-Game: com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster Class Reference
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster Class Reference
Handles the recipe for disaster activity.
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
boolean canUsePrayer (Player player)
void cleanup ()
Cleans up the activity when finished.
ActivityDeathType deathType ()
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
void update ()
The update method.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
Static Public Member Functions
static RecipeForDisaster create (Player player)
Handles creating a recipe for disaster activity.
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Member Functions
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
RecipeForDisaster (Player player, int instance)
Constructs a new SequencedMinigame object.
Private Attributes
Npc monster
The boss monster instance of this activity.
final Player player
The player instance of this activity.
RecipeForDisasterData wave = RecipeForDisasterData.AGRITH_NA_NA
The current wave of this activity.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Handles the recipe for disaster activity.
Author
Daniel
Michael
Definition at line 29 of file RecipeForDisaster.java.
Constructor & Destructor Documentation
RecipeForDisaster()
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.RecipeForDisaster (Player player, int instance) private
Constructs a new SequencedMinigame object.
Definition at line 41 of file RecipeForDisaster.java.
{
        super(10, instance);
        this.player = player;
    }
References com.runehive.content.activity.Activity.instance, and player.
Referenced by create().
Member Function Documentation
canTeleport()
boolean com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 124 of file RecipeForDisaster.java.
{
        return true;
    }
References player.
canUsePrayer()
boolean com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.canUsePrayer (Player player)
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 137 of file RecipeForDisaster.java.
{
        player.message("You can not use prayers here!");
        return false;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 115 of file RecipeForDisaster.java.
{
        if (monster != null) {
            player.send(new SendEntityHintArrow(monster, true));
            remove(monster);
        }
        ActivityPanel.clear(player);
    }
References com.runehive.content.activity.panel.ActivityPanel.clear(), monster, and player.
Referenced by finish(), onDeath(), and onRegionChange().
create()
RecipeForDisaster com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.create (Player player) static
Handles creating a recipe for disaster activity.
Definition at line 47 of file RecipeForDisaster.java.
{
        RecipeForDisaster minigame = new RecipeForDisaster(player, player.playerAssistant.instance());
        ActivityPanel.update(player, -1, "Recipe For Disaster", "Good Luck, " + player.getName() + "!", "Wave starting in 6 seconds");
        player.move(new Position(1899, 5356, 2));
        GroundItem.create(player, new Item(1580), player.getPosition());
        player.message("Ice gloves have been dropped for you to fight Flambleed!");
        player.gameRecord.start();
        player.playerAssistant.restore();
        minigame.add(player);
        minigame.resetCooldown();
        GroundItem.create(player, new Item(1580), player.getPosition());
        return minigame;
    }
References com.runehive.content.activity.Activity.add(), com.runehive.game.world.items.ground.GroundItem.create(), player, RecipeForDisaster(), com.runehive.content.activity.Activity.resetCooldown(), and com.runehive.content.activity.panel.ActivityPanel.update().
deathType()
ActivityDeathType com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.deathType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 149 of file RecipeForDisaster.java.
{
        return ActivityDeathType.PURCHASE;
    }
References com.runehive.content.activity.ActivityDeathType.PURCHASE.
finish()
void com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 95 of file RecipeForDisaster.java.
{
        cleanup();
        int reward;
        if (wave == null) {
            long time = player.gameRecord.end(ActivityType.RECIPE_FOR_DISASTER);
            reward = RecipeForDisasterData.CULINAROMANCER.gloves;
            player.send(new SendMessage("You have completed the Recipe For Disaster activity. Final time: @red@" + Utility.getTime(time) + "</col>."));
        } else {
            reward = wave.gloves;
            player.send(new SendMessage("RIP"));
        }
        if (reward > player.glovesTier) {
            player.glovesTier = reward;
        }
        player.move(new Position(3080, 3498, 0));
        player.dialogueFactory.sendNpcChat(6526, "You have been rewarded for your efforts.", "Check my store to see your available gloves.").execute();
        remove(player);
    }
References cleanup(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.CULINAROMANCER, com.runehive.util.Utility.getTime(), player, com.runehive.content.activity.ActivityType.RECIPE_FOR_DISASTER, and wave.
Referenced by onLogout().
getType()
ActivityType com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 172 of file RecipeForDisaster.java.
{
        return ActivityType.RECIPE_FOR_DISASTER;
    }
References com.runehive.content.activity.ActivityType.RECIPE_FOR_DISASTER.
onDeath()
void com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 154 of file RecipeForDisaster.java.
{
        if (mob.isPlayer()) {
            cleanup();
            remove(mob);
            mob.move(new Position(3080, 3498, 0));
            mob.animate(Animation.RESET, true);
            mob.graphic(Graphic.RESET, true);
            return;
        }
        if (mob.isNpc()) {
            player.send(new SendEntityHintArrow(mob, true));
            World.schedule(new NpcDeath(mob.getNpc()));
            wave = wave.getNext();
            resetCooldown();
        }
    }
References com.runehive.game.world.entity.mob.Mob.animate(), cleanup(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.Mob.move(), player, com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, com.runehive.content.activity.Activity.resetCooldown(), com.runehive.game.world.World.schedule(), and wave.
onLogout()
void com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 143 of file RecipeForDisaster.java.
{
        finish();
    }
References finish(), and player.
onRegionChange()
void com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 129 of file RecipeForDisaster.java.
{
        if (!Area.inRFD(player)) {
            cleanup();
            remove(player);
        }
    }
References cleanup(), com.runehive.game.world.position.Area.inRFD(), and player.
start()
void com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 74 of file RecipeForDisaster.java.
{
        if (wave == null) {
            finishCooldown();
            return;
        }
        if (player.locking.locked()) {
            return;
        }
        Position spawn = new Position(1899, 5356, 2);
        Position[] boundaries = Utility.getInnerBoundaries(spawn, 5, 5);
        Npc npc = new Npc(wave.npc, RandomUtils.random(boundaries));
        npc.owner = player;
        add(monster = npc);
        player.send(new SendEntityHintArrow(npc));
        monster.getCombat().attack(player);
        pause();
    }
References com.runehive.content.activity.Activity.add(), com.runehive.content.activity.Activity.finishCooldown(), com.runehive.util.Utility.getInnerBoundaries(), monster, com.runehive.content.activity.Activity.pause(), player, com.runehive.util.RandomUtils.random(), and wave.
update()
void com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.update ()
The update method.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 62 of file RecipeForDisaster.java.
{
        if (wave == null) {
            ActivityPanel.update(player, 100, "Recipe For Disaster", new Item(7462), "</col>Wave: <col=FF5500>" + RecipeForDisasterData.values().length + "/" + RecipeForDisasterData.values().length, "</col>Boss: <col=FF5500>None!", "</col>Time: <col=FF5500>" + Utility.getTime(System.currentTimeMillis() - player.gameRecord.time));
            return;
        }
        int progress = (int) Utility.getPercentageAmount(wave.ordinal(), RecipeForDisasterData.values().length);
        int display = 7453 + wave.gloves;
        String npc = monster == null ? "" : monster.getName();
        ActivityPanel.update(player, progress, "Recipe For Disaster", new Item(display), "</col>Wave: <col=FF5500>" + wave.ordinal() + "/" + RecipeForDisasterData.values().length, "</col>Boss: <col=FF5500>" + npc, "</col>Time: <col=FF5500>" + Utility.getTime(System.currentTimeMillis() - player.gameRecord.time));
    }
References com.runehive.util.Utility.getPercentageAmount(), com.runehive.util.Utility.getTime(), monster, player, com.runehive.content.activity.panel.ActivityPanel.update(), and wave.
Member Data Documentation
monster
Npc com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.monster private
The boss monster instance of this activity.
Definition at line 35 of file RecipeForDisaster.java.
Referenced by cleanup(), start(), and update().
player
final Player com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.player private
The player instance of this activity.
Definition at line 32 of file RecipeForDisaster.java.
Referenced by canTeleport(), canUsePrayer(), cleanup(), create(), finish(), onDeath(), onLogout(), onRegionChange(), RecipeForDisaster(), start(), and update().
wave
RecipeForDisasterData com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.wave = RecipeForDisasterData.AGRITH_NA_NA private
The current wave of this activity.
Definition at line 38 of file RecipeForDisaster.java.
Referenced by finish(), onDeath(), start(), and update().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/recipefordisaster/RecipeForDisaster.java