RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Glass Class Reference
com.runehive.content.skill.impl.crafting.impl.Glass Class Reference
Handles the glass crafting.
Classes
enum GlassData
Holds all the glass data.
Static Public Member Functions
static boolean click (Player player, int button)
Handles clicking on the interface.
static void craft (Player player, GlassData glass, int amount)
Handles crafting the glass.
static void open (Player player)
Handles opening the glass crafting interface.
Static Private Member Functions
static Action< Player > blow (Player player, GlassData glass, int amount)
Handles blowing the glass data.
Detailed Description
Handles the glass crafting.
Author
Daniel
Definition at line 23 of file Glass.java.
Member Function Documentation
blow()
Action< Player > com.runehive.content.skill.impl.crafting.impl.Glass.blow (Player player, GlassData glass, int amount) static private
Handles blowing the glass data.
Definition at line 161 of file Glass.java.
{
        return new Action<Player>(player, 3, true) {
            int ticks = 0;
            @Override
            public void execute() {
                boolean moltenGlass = glass == GlassData.MOLTEN_GLASS;
                if (moltenGlass && (!player.inventory.contains(1783) || !player.inventory.contains(1781))) {
                    player.send(new SendMessage("You need a bucket of sand and soda ash to make molten glass!"));
                    cancel();
                    return;
                }
                if (!player.inventory.contains(1785) && !moltenGlass) {
                    player.send(new SendMessage("You need a glassblowing pipe to do this!"));
                    cancel();
                    return;
                }
                if (!player.inventory.contains(glass.material)) {
                    String name = ItemDefinition.get(glass.material).getName();
                    player.send(new SendMessage("You need " + Utility.getAOrAn(name) + " " + name + " to do this!"));
                    cancel();
                    return;
                }
                player.inventory.remove(glass.material, 1);
                if (moltenGlass) {
                    player.inventory.replace(1783, 1925, true);
                }
                String name = ItemDefinition.get(glass.product).getName();
                player.animate(new Animation(moltenGlass ? 899 : 884));
                player.inventory.add(new Item(glass.product));
                player.skills.addExperience(Skill.CRAFTING, glass.experience * Config.CRAFTING_MODIFICATION);
                player.send(new SendMessage("You make " + Utility.getAOrAn(name) + " " + name + "."));
                if (++ticks == amount) {
                    cancel();
                    return;
                }
            }
            @Override
            public String getName() {
                return "Glass";
            }
            @Override
            public boolean prioritized() {
                return false;
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
        };
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.Config.CRAFTING_MODIFICATION, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.experience, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.material, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.MOLTEN_GLASS, com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.product, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by craft().
click()
boolean com.runehive.content.skill.impl.crafting.impl.Glass.click (Player player, int button) static
Handles clicking on the interface.
Vial
Orb
Beer glass
Candle lantern
Oil lamp
Fishbowl
Lantern lens
Definition at line 69 of file Glass.java.
{
        switch (button) {
            /** Vial */
            case 11474: craft(player, GlassData.VIAL, 1); return true;
            case 11473: craft(player, GlassData.VIAL, 5); return true;
            case 11472: craft(player, GlassData.VIAL, 10); return true;
            case 11471:
                player.send(new SendInputAmount("Enter the amount you would like to craft", 2, input ->
                        craft(player, GlassData.VIAL, Integer.parseInt(input))
                ));
                return true;
            /** Orb */
            case 12396: craft(player, GlassData.UNPOWDERED_ORD, 1); return true;
            case 12395: craft(player, GlassData.UNPOWDERED_ORD, 5); return true;
            case 12394: craft(player, GlassData.UNPOWDERED_ORD, 10); return true;
            case 11475:
                player.send(new SendInputAmount("Enter the amount you would like to craft", 2, input ->
                        craft(player, GlassData.UNPOWDERED_ORD, Integer.parseInt(input))
                ));
                return true;
            /** Beer glass */
            case 12400: craft(player, GlassData.BEER_GLASS, 1); return true;
            case 12399: craft(player, GlassData.BEER_GLASS, 5); return true;
            case 12398: craft(player, GlassData.BEER_GLASS, 10); return true;
            case 12397:
                player.send(new SendInputAmount("Enter the amount you would like to craft", 2, input ->
                        craft(player, GlassData.BEER_GLASS, Integer.parseInt(input))
                ));
                return true;
            /** Candle lantern */
            case 12404: craft(player, GlassData.CANDLE_LANTERN, 1); return true;
            case 12403: craft(player, GlassData.CANDLE_LANTERN, 5); return true;
            case 12402: craft(player, GlassData.CANDLE_LANTERN, 10); return true;
            case 12401:
                player.send(new SendInputAmount("Enter the amount you would like to craft", 2, input ->
                        craft(player, GlassData.CANDLE_LANTERN, Integer.parseInt(input))
                ));
                return true;
            /** Oil lamp */
            case 12408: craft(player, GlassData.OIL_LAMP, 1); return true;
            case 12407: craft(player, GlassData.OIL_LAMP, 5); return true;
            case 12406: craft(player, GlassData.OIL_LAMP, 10); return true;
            case 12405:
                player.send(new SendInputAmount("Enter the amount you would like to craft", 2, input ->
                        craft(player, GlassData.OIL_LAMP, Integer.parseInt(input))
                ));
                return true;
            /** Fishbowl */
            case 6203: craft(player, GlassData.FISHBOWL, 1); return true;
            case 6202: craft(player, GlassData.FISHBOWL, 5); return true;
            case 6201: craft(player, GlassData.FISHBOWL, 10); return true;
            case 6200:
                player.send(new SendInputAmount("Enter the amount you would like to craft", 2, input ->
                        craft(player, GlassData.FISHBOWL, Integer.parseInt(input))
                ));
                return true;
            /** Lantern lens */
            case 12412: craft(player, GlassData.LANTERN_LENS, 1); return true;
            case 12411: craft(player, GlassData.LANTERN_LENS, 5); return true;
            case 12410: craft(player, GlassData.LANTERN_LENS, 10); return true;
            case 12409:
                player.send(new SendInputAmount("Enter the amount you would like to craft", 2, input ->
                        craft(player, GlassData.LANTERN_LENS, Integer.parseInt(input))
                ));
                return true;
        }
        return false;
    }
References com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.BEER_GLASS, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.CANDLE_LANTERN, craft(), com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.FISHBOWL, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.LANTERN_LENS, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.OIL_LAMP, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.UNPOWDERED_ORD, and com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.VIAL.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.clickButton().
craft()
void com.runehive.content.skill.impl.crafting.impl.Glass.craft (Player player, GlassData glass, int amount) static
Handles crafting the glass.
Definition at line 139 of file Glass.java.
{
        if (player.skills.getMaxLevel(Skill.CRAFTING) < glass.level) {
            player.send(new SendMessage("You need a crafting level of " + glass.level + " to craft this!"));
            return;
        }
        if (!player.inventory.contains(1785) && glass != GlassData.MOLTEN_GLASS) {
            player.send(new SendMessage("You need a glassblowing pipe to do this!"));
            return;
        }
        if (!player.inventory.contains(glass.material)) {
            String name = ItemDefinition.get(glass.material).getName();
            player.send(new SendMessage("You need " + Utility.getAOrAn(name) + " " + name + " to do this!"));
            return;
        }
        player.interfaceManager.close();
        player.action.execute(blow(player, glass, amount), true);
    }
References com.runehive.game.world.entity.mob.Mob.action, blow(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.skill.Skill.CRAFTING, com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.util.Utility.getAOrAn(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.level, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.material, com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.MOLTEN_GLASS, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by click(), and com.runehive.content.skill.impl.crafting.Crafting.useItem().
open()
void com.runehive.content.skill.impl.crafting.impl.Glass.open (Player player) static
Handles opening the glass crafting interface.
Definition at line 64 of file Glass.java.
{
        player.interfaceManager.open(11462);
    }
References com.runehive.game.world.entity.mob.player.Player.interfaceManager, and com.runehive.game.world.entity.mob.player.InterfaceManager.open().
Referenced by com.runehive.content.skill.impl.crafting.Crafting.useItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Glass.java