RuneHive-Game: com.runehive.game.world.cronjobs.Job Class Reference
com.runehive.game.world.cronjobs.Job Class Reference abstract
Public Member Functions
abstract void execute ()
void execute (JobExecutionContext jobExecutionContext)
Protected Member Functions
Job (String name)
Private Attributes
final String name
Detailed Description
Definition at line 6 of file Job.java.
Constructor & Destructor Documentation
Job()
com.runehive.game.world.cronjobs.Job.Job (String name) protected
Definition at line 10 of file Job.java.
{
        this.name = name;
    }
References name.
Referenced by execute().
Member Function Documentation
execute() [1/2]
abstract void com.runehive.game.world.cronjobs.Job.execute () abstract
Reimplemented in com.runehive.game.world.cronjobs.impl.DoubleExperienceJob, and com.runehive.game.world.cronjobs.impl.OpenAIRelayJob.
execute() [2/2]
void com.runehive.game.world.cronjobs.Job.execute (JobExecutionContext jobExecutionContext)
Definition at line 15 of file Job.java.
{
        System.out.println("Firing " + name + " job");
        final Job job = this;
        World.schedule(1, () -> {
            try {
                job.execute();
            } catch (Exception e) {
                System.err.println("An error occurred in " + job.name + " job");
            }
        });
    }
References execute(), Job(), name, and com.runehive.game.world.World.schedule().
Referenced by execute().
Member Data Documentation
name
final String com.runehive.game.world.cronjobs.Job.name private
Definition at line 8 of file Job.java.
Referenced by execute(), and Job().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/cronjobs/Job.java