RuneHive-Game: com.runehive.game.world.entity.combat.formula.MeleeFormula Class Reference
com.runehive.game.world.entity.combat.formula.MeleeFormula Class Reference
Public Member Functions
int modifyAccuracy (Mob attacker, Mob defender, int roll)
int modifyAggressive (Mob attacker, Mob defender, int roll)
int modifyAggressiveBonus (Mob attacker, Mob defender, int bonus)
int modifyDamage (Mob attacker, Mob defender, int damage)
int modifyDefensive (Mob attacker, Mob defender, int roll)
int modifyDefensiveBonus (Mob attacker, Mob defender, int bonus)
int modifyOffensiveBonus (Mob attacker, Mob defender, int bonus)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Detailed Description
Definition at line 13 of file MeleeFormula.java.
Member Function Documentation
modifyAccuracy()
int com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAccuracy (Mob attacker, Mob defender, int roll)
Definition at line 16 of file MeleeFormula.java.
{
        FightType fightType = attacker.getCombat().getFightType();
        int level = attacker.skills.getLevel(Skill.ATTACK);
        int effectiveAccuracy = attacker.getCombat().modifyAttackLevel(defender, level);
        return 8 + effectiveAccuracy + fightType.getStyle().getAccuracyIncrease();
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, com.runehive.game.world.entity.combat.attack.FightStyle.getAccuracyIncrease(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.combat.attack.FightType.getStyle(), and com.runehive.game.world.entity.mob.Mob.skills.
modifyAggressive()
int com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressive (Mob attacker, Mob defender, int roll)
Definition at line 24 of file MeleeFormula.java.
{
        FightType fightType = attacker.getCombat().getFightType();
        int level = attacker.skills.getLevel(Skill.STRENGTH);
        int effectiveStrength = attacker.getCombat().modifyStrengthLevel(defender, level);
        return 8 + effectiveStrength + fightType.getStyle().getStrengthIncrease();
    }
References com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.combat.attack.FightStyle.getStrengthIncrease(), com.runehive.game.world.entity.combat.attack.FightType.getStyle(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.entity.skill.Skill.STRENGTH.
modifyAggressiveBonus()
int com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 47 of file MeleeFormula.java.
{
        bonus = attacker.getBonus(Equipment.STRENGTH_BONUS);
        return attacker.getCombat().modifyAggresiveBonus(defender, bonus);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getCombat(), and com.runehive.game.world.items.containers.equipment.Equipment.STRENGTH_BONUS.
modifyDamage()
int com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage (Mob attacker, Mob defender, int damage)
Definition at line 60 of file MeleeFormula.java.
{
        damage = attacker.getCombat().modifyDamage(defender, damage);
        if(defender.isNpc() && defender.getNpc().id == 319 && (attacker.isPlayer() && !attacker.getPlayer().equipment.containsAny(CorporealBeast.weaponsAllowed))) {
            damage /= 2;
        }
        if (defender.isPlayer() && !defender.getPlayer().staffOfDeadSpecial.elapsed(1, TimeUnit.MINUTES) && defender.getPlayer().equipment.containsAny(11791, 12904)) {
            damage /= 2;
        }
        if (defender.prayer.isActive(Prayer.PROTECT_FROM_MELEE) && !defender.attributes.has("VERACS-EFFECT")) {
            damage *= !attacker.isPlayer() || defender.isNpc() ? 0.0 : 0.6;
        }
        return damage;
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.items.containers.ItemContainer.containsAny(), com.runehive.util.Stopwatch.elapsed(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.util.generic.GenericAttributes.has(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MELEE, com.runehive.game.world.entity.mob.player.Player.staffOfDeadSpecial, and com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.weaponsAllowed.
modifyDefensive()
int com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensive (Mob attacker, Mob defender, int roll)
Definition at line 32 of file MeleeFormula.java.
{
        FightType fightType = defender.getCombat().getFightType();
        int level = defender.skills.getLevel(Skill.DEFENCE);
        int effectiveDefence = defender.getCombat().modifyDefenceLevel(attacker, level);
        return 8 + effectiveDefence + fightType.getStyle().getDefensiveIncrease();
    }
References com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.combat.attack.FightStyle.getDefensiveIncrease(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.combat.attack.FightType.getStyle(), and com.runehive.game.world.entity.mob.Mob.skills.
modifyDefensiveBonus()
int com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 53 of file MeleeFormula.java.
{
        FightType fightType = attacker.getCombat().getFightType();
        bonus = defender.getBonus(fightType.getCorrespondingBonus());
        return defender.getCombat().modifyDefensiveBonus(attacker, bonus);
    }
References com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getCombat(), and com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus().
modifyOffensiveBonus()
int com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyOffensiveBonus (Mob attacker, Mob defender, int bonus)
Definition at line 40 of file MeleeFormula.java.
{
        FightType fightType = attacker.getCombat().getFightType();
        bonus = attacker.getBonus(fightType.getBonus());
        return attacker.getCombat().modifyOffensiveBonus(defender, bonus);
    }
References com.runehive.game.world.entity.combat.attack.FightType.getBonus(), com.runehive.game.world.entity.mob.Mob.getBonus(), and com.runehive.game.world.entity.mob.Mob.getCombat().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/formula/MeleeFormula.java