RuneHive-Game: com.runehive.fs.cache.decoder.RegionDecoder Class Reference
com.runehive.fs.cache.decoder.RegionDecoder Class Reference
A class which parses static object definitions, which include tool.mapviewer tiles and landscapes.
Public Member Functions
void load (final Cache mapIndex, final RegionDefinition def)
RegionDecoder (FileSystem fs)
Creates the ObjectDefinitionDecoder.
void run ()
Private Member Functions
void parseGameObject (Region region, ByteBuffer buf, int x, int y, IntSet downHeights)
Parses a GameObject on the specified coordinates.
void parseTerrain (Region region, ByteBuffer mapBuffer, IntSet downHeights)
Loads all of the tool.mapviewer indexes entries and decodes each.
Private Attributes
final AtomicInteger decoded = new AtomicInteger()
Amount of regions correctly decoded.
final AtomicInteger errors = new AtomicInteger()
Amount of regions incorrectly decoded.
final FileSystem fs
The FileSystem.
Static Private Attributes
static final Logger LOGGER = LogManager.getLogger(RegionDecoder.class)
Detailed Description
A class which parses static object definitions, which include tool.mapviewer tiles and landscapes.
Author
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Definition at line 29 of file RegionDecoder.java.
Constructor & Destructor Documentation
RegionDecoder()
com.runehive.fs.cache.decoder.RegionDecoder.RegionDecoder (FileSystem fs)
Creates the ObjectDefinitionDecoder.
Parameters
fs The FileSystem.
Definition at line 53 of file RegionDecoder.java.
{
        this.fs = fs;
    }
References fs.
Member Function Documentation
load()
void com.runehive.fs.cache.decoder.RegionDecoder.load (final Cache mapIndex, final RegionDefinition def)
Definition at line 67 of file RegionDecoder.java.
{
        final int hash = def.getHash();
        final int x = (hash >> 8 & 0xFF) << 6;
        final int y = (hash & 0xFF) << 6;
        try {
            final Region region = World.getRegions().getRegion(x, y);
            ByteBuffer terrainData = mapIndex.get(def.getTerrainFile());
            if (terrainData == null) {
                errors.getAndIncrement();
                return;
            }
            ByteBuffer terrainBuffer = ByteBuffer.wrap(CompressionUtil.gunzip(terrainData.array()));
            final IntSet downHeights = new IntOpenHashSet();
            parseTerrain(region, terrainBuffer, downHeights);
            ByteBuffer gameObjectData = mapIndex.get(def.getObjectFile());
            if (gameObjectData == null) {
                errors.getAndIncrement();
                return;
            }
            ByteBuffer gameObjectBuffer = ByteBuffer.wrap(CompressionUtil.gunzip(gameObjectData.array()));
            parseGameObject(region, gameObjectBuffer, x, y, downHeights);
            decoded.getAndIncrement();
        } catch (Exception e) {
            e.printStackTrace();
            errors.getAndIncrement();
        }
    }
References decoded, errors, com.runehive.fs.cache.Cache.get(), com.runehive.game.world.region.RegionManager.getRegion(), com.runehive.game.world.World.getRegions(), com.runehive.fs.util.CompressionUtil.gunzip(), parseGameObject(), and parseTerrain().
Referenced by run().
parseGameObject()
void com.runehive.fs.cache.decoder.RegionDecoder.parseGameObject (Region region, ByteBuffer buf, int x, int y, IntSet downHeights) private
Parses a GameObject on the specified coordinates.
Parameters
buf The uncompressed game object data buffer.
x The x coordinate this object is on.
y The y coordinate this object is on.
Definition at line 107 of file RegionDecoder.java.
{
        int objId = -1;
        while (true) {
            int objIdOffset = ByteBufferUtil.getSmart(buf);
            if (objIdOffset == 0) break;
            objId += objIdOffset;
            int objPosInfo = 0;
            while (true) {
                int objPosInfoOffset = ByteBufferUtil.getSmart(buf);
                if (objPosInfoOffset == 0) break;
                objPosInfo += objPosInfoOffset - 1;
                int objOtherInfo = buf.get() & 0xFF;
                int localY = objPosInfo & 0x3f;
                int localX = objPosInfo >> 6 & 0x3f;
                int height = objPosInfo >> 12 & 0x3;
                Optional<ObjectType> type = ObjectType.valueOf(objOtherInfo >> 2);
                Optional<ObjectDirection> face = ObjectDirection.valueOf(objOtherInfo & 0x3);
                if (downHeights.contains(Position.hash(localX, localY, 1))) {
                    if (--height < 0) continue;
                } else if (downHeights.contains(Position.hash(localX, localY, height))) {
                    height--;
                }
                if (!type.isPresent() || !face.isPresent()) {
                    continue;
                }
                Position pos = new Position(localX + x, localY + y, height);
                GameObjectDefinition def = GameObjectDefinition.forId(objId);
                if (def == null)
                    continue;
                StaticGameObject staticObject = new StaticGameObject(def, pos, type.get(), face.get());
                if (Region.SKIPPED_OBJECTS.contains(pos)) {
                    region.skip(staticObject);
                } else {
                    TraversalMap.markObject(region, staticObject, true, true);
                }
            }
        }
    }
References com.runehive.game.world.object.GameObjectDefinition.forId(), com.runehive.fs.util.ByteBufferUtil.getSmart(), com.runehive.game.world.position.Position.hash(), com.runehive.game.world.pathfinding.TraversalMap.markObject(), com.runehive.game.world.region.Region.SKIPPED_OBJECTS, com.runehive.game.world.object.ObjectDirection.valueOf(), and com.runehive.game.world.object.ObjectType.valueOf().
Referenced by load().
parseTerrain()
void com.runehive.fs.cache.decoder.RegionDecoder.parseTerrain (Region region, ByteBuffer mapBuffer, IntSet downHeights) private
Loads all of the tool.mapviewer indexes entries and decodes each.
Parameters
mapBuffer The uncompressed tool.mapviewer entry data buffer.
Definition at line 161 of file RegionDecoder.java.
{
        int[][][] attributes = new int[4][64][64];
        for (int height = 0; height < 4; height++) {
            for (int localX = 0; localX < 64; localX++) {
                for (int localY = 0; localY < 64; localY++) {
                    while (true) {
                        int attributeId = mapBuffer.getShort() & 0xFFFF;
                        if (attributeId == 0) {
                            break;
                        }
                        if (attributeId == 1) {
                            int tileHeight = mapBuffer.get() & 0xFF;
                            break;
                        }
                        if (attributeId <= 49) {
                            int overlayId = mapBuffer.getShort() & 0xFFFF;
                        } else if (attributeId <= 81) {
                            attributes[height][localX][localY] = attributeId - 49;
                        }
                    }
                }
            }
        }
        for (int height = 0; height < 4; height++) {
            for (int localX = 0; localX < 64; localX++) {
                for (int localY = 0; localY < 64; localY++) {
                    if ((attributes[height][localX][localY] & 2) == 2) {
                        downHeights.add(Position.hash(localX, localY, height));
                    }
                    if ((attributes[height][localX][localY] & 1) == 1) {
                        int plane = height;
                        if ((attributes[1][localX][localY] & 2) == 2) {
                            downHeights.add(Position.hash(localX, localY, 1));
                            plane--;
                        }
                        if (plane >= 0) {
                            TraversalMap.block(region, plane, localX, localY);
                        }
                    }
                }
            }
        }
    }
References com.runehive.game.world.pathfinding.TraversalMap.block(), and com.runehive.game.world.position.Position.hash().
Referenced by load().
run()
void com.runehive.fs.cache.decoder.RegionDecoder.run ()
Definition at line 58 of file RegionDecoder.java.
                      {
        LOGGER.info("Loading regional map data.");
        final Cache mapIndex = fs.getCache(FileSystem.MAP_INDEX);
        RegionDefinition.getDefinitions()
                .values()
                .forEach(def -> load(mapIndex, def));
        LOGGER.info("Loaded " + decoded + " regions, skipped " + errors + " maps.");
    }
References decoded, errors, fs, com.runehive.game.world.region.RegionDefinition.getDefinitions(), load(), LOGGER, and com.runehive.fs.cache.FileSystem.MAP_INDEX.
Referenced by com.runehive.RuneHive.processSequentialStartupTasks().
Member Data Documentation
decoded
final AtomicInteger com.runehive.fs.cache.decoder.RegionDecoder.decoded = new AtomicInteger() private
Amount of regions correctly decoded.
Definition at line 41 of file RegionDecoder.java.
Referenced by load(), and run().
errors
final AtomicInteger com.runehive.fs.cache.decoder.RegionDecoder.errors = new AtomicInteger() private
Amount of regions incorrectly decoded.
Definition at line 46 of file RegionDecoder.java.
Referenced by load(), and run().
fs
final FileSystem com.runehive.fs.cache.decoder.RegionDecoder.fs private
The FileSystem.
Definition at line 36 of file RegionDecoder.java.
Referenced by RegionDecoder(), and run().
LOGGER
final Logger com.runehive.fs.cache.decoder.RegionDecoder.LOGGER = LogManager.getLogger(RegionDecoder.class) static private
Definition at line 31 of file RegionDecoder.java.
Referenced by run().
The documentation for this class was generated from the following file:
java/com/runehive/fs/cache/decoder/RegionDecoder.java