RuneHive-Game: com.runehive.content.activity.lobby.LobbyManager Class Reference
com.runehive.content.activity.lobby.LobbyManager Class Reference abstract
Public Member Functions
boolean canStart (LobbyNode node)
final void enter (Player player)
int getGameCapacity ()
int getGameCooldown ()
int getLobbyCooldown ()
int getMinimumRequired ()
int getPlayerCapacity ()
final void leave (Player player)
final void sequenceActive ()
Protected Member Functions
abstract LobbyNode createLobby ()
void exceededGameCapacity (Player player)
void exceededPlayerCapacity (Player player)
LobbyManager (int gameCapacity, int playerCapacity, int minimumRequired, int lobbyCooldown, int gameCooldown)
void onEnter (Player player)
void onLeave (Player player)
Private Member Functions
LobbyNode findNode (Player player)
LobbyNode nextLobby ()
Private Attributes
final Deque< LobbyNode > active = new LinkedList<>()
final int gameCapacity
final int gameCooldown
final int lobbyCooldown
final int minimumRequired
final int playerCapacity
Detailed Description
Definition at line 9 of file LobbyManager.java.
Constructor & Destructor Documentation
LobbyManager()
com.runehive.content.activity.lobby.LobbyManager.LobbyManager (int gameCapacity, int playerCapacity, int minimumRequired, int lobbyCooldown, int gameCooldown) protected
Definition at line 18 of file LobbyManager.java.
{
        this.playerCapacity = playerCapacity;
        this.gameCapacity = gameCapacity;
        this.lobbyCooldown = lobbyCooldown;
        this.gameCooldown = gameCooldown;
        this.minimumRequired = minimumRequired;
    }
References gameCapacity, gameCooldown, lobbyCooldown, minimumRequired, and playerCapacity.
Member Function Documentation
canStart()
boolean com.runehive.content.activity.lobby.LobbyManager.canStart (LobbyNode node)
Definition at line 121 of file LobbyManager.java.
{
        if (!node.lobby) {
            return false;
        }
        int activeGames = 0;
        for (LobbyNode activity : active) {
            if (!activity.lobby)
                activeGames++;
        }
        if (activeGames >= gameCapacity) {
            node.cooldown(lobbyCooldown);
            node.forEachActivity((mob, activity) -> {
                if (mob.isPlayer()) {
                    exceededGameCapacity(mob.getPlayer());
                }
            });
            return false;
        }
        if (minimumRequired > node.getActiveSize()) {
            node.cooldown(lobbyCooldown);
            node.groupMessage("This activity requires at least " + minimumRequired + " players to start.");
            return false;
        }
        return true;
    }
References active, com.runehive.content.activity.Activity.cooldown, exceededGameCapacity(), com.runehive.content.activity.GroupActivity.forEachActivity(), gameCapacity, com.runehive.content.activity.GroupActivity.getActiveSize(), com.runehive.content.activity.GroupActivity.groupMessage(), com.runehive.content.activity.lobby.LobbyNode.lobby, lobbyCooldown, and minimumRequired.
createLobby()
abstract LobbyNode com.runehive.content.activity.lobby.LobbyManager.createLobby () abstract protected
Reimplemented in com.runehive.content.activity.impl.battleground.BattlegroundLobby, and com.runehive.content.activity.impl.pestcontrol.PestControlLobby.
Referenced by nextLobby().
enter()
final void com.runehive.content.activity.lobby.LobbyManager.enter (Player player)
Definition at line 26 of file LobbyManager.java.
{
        LobbyNode lobby = nextLobby();
        if (lobby == null) {
            return;
        }
        if (lobby.getActiveSize() >= playerCapacity) {
            exceededPlayerCapacity(player);
            return;
        }
        lobby.addActivity(player, lobby.createActivity(player));
        /* reset lobby cooldown since first player just joined */
        if (minimumRequired > -1 && lobby.getActiveSize() == 1) {
            lobby.cooldown(lobbyCooldown);
        }
        onEnter(player);
    }
References exceededPlayerCapacity(), lobbyCooldown, minimumRequired, nextLobby(), onEnter(), and playerCapacity.
exceededGameCapacity()
void com.runehive.content.activity.lobby.LobbyManager.exceededGameCapacity (Player player) protected
Reimplemented in com.runehive.content.activity.impl.pestcontrol.PestControlLobby.
Definition at line 87 of file LobbyManager.java.
{
        /* do nothing by default */
    }
Referenced by canStart().
exceededPlayerCapacity()
void com.runehive.content.activity.lobby.LobbyManager.exceededPlayerCapacity (Player player) protected
Reimplemented in com.runehive.content.activity.impl.pestcontrol.PestControlLobby.
Definition at line 91 of file LobbyManager.java.
{
        /* do nothing by default */
    }
Referenced by enter().
findNode()
LobbyNode com.runehive.content.activity.lobby.LobbyManager.findNode (Player player) private
Definition at line 95 of file LobbyManager.java.
{
        for (LobbyNode node : active) {
            if (node.contains(player)) {
                return node;
            }
        }
        return null;
    }
References active.
Referenced by leave().
getGameCapacity()
int com.runehive.content.activity.lobby.LobbyManager.getGameCapacity ()
Definition at line 151 of file LobbyManager.java.
{
        return gameCapacity;
    }
References gameCapacity.
getGameCooldown()
int com.runehive.content.activity.lobby.LobbyManager.getGameCooldown ()
Definition at line 163 of file LobbyManager.java.
{
        return gameCooldown;
    }
References gameCooldown.
getLobbyCooldown()
int com.runehive.content.activity.lobby.LobbyManager.getLobbyCooldown ()
Definition at line 167 of file LobbyManager.java.
{
        return lobbyCooldown;
    }
References lobbyCooldown.
getMinimumRequired()
int com.runehive.content.activity.lobby.LobbyManager.getMinimumRequired ()
Definition at line 159 of file LobbyManager.java.
{
        return minimumRequired;
    }
References minimumRequired.
getPlayerCapacity()
int com.runehive.content.activity.lobby.LobbyManager.getPlayerCapacity ()
Definition at line 155 of file LobbyManager.java.
{
        return playerCapacity;
    }
References playerCapacity.
leave()
final void com.runehive.content.activity.lobby.LobbyManager.leave (Player player)
Definition at line 48 of file LobbyManager.java.
{
        LobbyNode lobby = findNode(player);
        if (lobby == null) {
            return;
        }
        lobby.removeActivity(player);
        onLeave(player);
    }
References findNode(), and onLeave().
nextLobby()
LobbyNode com.runehive.content.activity.lobby.LobbyManager.nextLobby () private
Definition at line 104 of file LobbyManager.java.
{
        for (LobbyNode node : active) {
            if (node.inLobby()) {
                return node;
            }
        }
        if (active.size() >= 1 + gameCapacity) {
            return null;
        }
        LobbyNode activity = createLobby();
        active.addFirst(activity);
        activity.lobby = true;
        return activity;
    }
References active, createLobby(), and gameCapacity.
Referenced by enter().
onEnter()
void com.runehive.content.activity.lobby.LobbyManager.onEnter (Player player) protected
Reimplemented in com.runehive.content.activity.impl.pestcontrol.PestControlLobby.
Definition at line 79 of file LobbyManager.java.
{
        /* do nothing by default */
    }
Referenced by enter().
onLeave()
void com.runehive.content.activity.lobby.LobbyManager.onLeave (Player player) protected
Reimplemented in com.runehive.content.activity.impl.pestcontrol.PestControlLobby.
Definition at line 83 of file LobbyManager.java.
{
        /* do nothing by default */
    }
Referenced by leave().
sequenceActive()
final void com.runehive.content.activity.lobby.LobbyManager.sequenceActive ()
Definition at line 59 of file LobbyManager.java.
{
        Iterator<LobbyNode> iterator = active.iterator();
        while (iterator.hasNext()) {
            LobbyNode node = iterator.next();
            if (node.finished()) {
                node.finish();
                node.removeAll();
                node.cleanup();
                iterator.remove();
                continue;
            }
            node.sequence();
        }
    }
References active, com.runehive.content.activity.GroupActivity.cleanup(), com.runehive.content.activity.GroupActivity.finish(), com.runehive.content.activity.lobby.LobbyNode.finished(), com.runehive.content.activity.GroupActivity.removeAll(), and com.runehive.content.activity.Activity.sequence().
Member Data Documentation
active
final Deque<LobbyNode> com.runehive.content.activity.lobby.LobbyManager.active = new LinkedList<>() private
Definition at line 10 of file LobbyManager.java.
Referenced by canStart(), findNode(), nextLobby(), and sequenceActive().
gameCapacity
final int com.runehive.content.activity.lobby.LobbyManager.gameCapacity private
Definition at line 13 of file LobbyManager.java.
Referenced by com.runehive.content.activity.impl.battleground.BattlegroundLobby.BattlegroundLobby(), canStart(), getGameCapacity(), LobbyManager(), and nextLobby().
gameCooldown
final int com.runehive.content.activity.lobby.LobbyManager.gameCooldown private
Definition at line 15 of file LobbyManager.java.
Referenced by com.runehive.content.activity.impl.battleground.BattlegroundLobby.BattlegroundLobby(), getGameCooldown(), and LobbyManager().
lobbyCooldown
final int com.runehive.content.activity.lobby.LobbyManager.lobbyCooldown private
Definition at line 14 of file LobbyManager.java.
Referenced by com.runehive.content.activity.impl.battleground.BattlegroundLobby.BattlegroundLobby(), canStart(), enter(), getLobbyCooldown(), and LobbyManager().
minimumRequired
final int com.runehive.content.activity.lobby.LobbyManager.minimumRequired private
Definition at line 16 of file LobbyManager.java.
Referenced by com.runehive.content.activity.impl.battleground.BattlegroundLobby.BattlegroundLobby(), canStart(), enter(), getMinimumRequired(), and LobbyManager().
playerCapacity
final int com.runehive.content.activity.lobby.LobbyManager.playerCapacity private
Definition at line 12 of file LobbyManager.java.
Referenced by com.runehive.content.activity.impl.battleground.BattlegroundLobby.BattlegroundLobby(), enter(), getPlayerCapacity(), and LobbyManager().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/lobby/LobbyManager.java