RuneHive-Game: com.runehive.game.service.HighscoreService Class Reference
com.runehive.game.service.HighscoreService Class Reference
Static Public Member Functions
static void saveHighscores (Player player)
Private Member Functions
HighscoreService ()
Static Private Member Functions
static String generateQuery ()
static int getRank (PlayerRight right)
Static Private Attributes
static final String CONNECTION_STRING = "jdbc:mysql://45.88.231.118:3306/hiscores"
static final Logger logger = LogManager.getLogger(HighscoreService.class)
static final String PASSWORD = "bQ9R#UnPsW5^HLiU9$4LcJvE4%ZwJWLz"
static final String USERNAME = "root"
Detailed Description
Definition at line 16 of file HighscoreService.java.
Constructor & Destructor Documentation
HighscoreService()
com.runehive.game.service.HighscoreService.HighscoreService () private
Definition at line 135 of file HighscoreService.java.
{
    }
Member Function Documentation
generateQuery()
String com.runehive.game.service.HighscoreService.generateQuery () static private
Definition at line 69 of file HighscoreService.java.
{
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO hs_users (");
        sb.append("id, ");
        sb.append("username, ");
        sb.append("rights, ");
        sb.append("mode, ");
        sb.append("total_prestiges, ");
        sb.append("attack_prestiges, ");
        sb.append("defence_prestiges, ");
        sb.append("strength_prestiges, ");
        sb.append("hitpoints_prestiges, ");
        sb.append("ranged_prestiges, ");
        sb.append("prayer_prestiges, ");
        sb.append("magic_prestiges, ");
        sb.append("cooking_prestiges, ");
        sb.append("woodcutting_prestiges, ");
        sb.append("fletching_prestiges, ");
        sb.append("fishing_prestiges, ");
        sb.append("firemaking_prestiges, ");
        sb.append("crafting_prestiges, ");
        sb.append("smithing_prestiges, ");
        sb.append("mining_prestiges, ");
        sb.append("herblore_prestiges, ");
        sb.append("agility_prestiges, ");
        sb.append("thieving_prestiges, ");
        sb.append("slayer_prestiges, ");
        sb.append("farming_prestiges, ");
        sb.append("runecrafting_prestiges, ");
        sb.append("hunter_prestiges, ");
        sb.append("construction_prestiges,");
        sb.append("total_level, ");
        sb.append("overall_xp, ");
        sb.append("attack_xp, ");
        sb.append("defence_xp, ");
        sb.append("strength_xp, ");
        sb.append("hitpoints_xp, ");
        sb.append("ranged_xp, ");
        sb.append("prayer_xp, ");
        sb.append("magic_xp, ");
        sb.append("cooking_xp, ");
        sb.append("woodcutting_xp, ");
        sb.append("fletching_xp, ");
        sb.append("fishing_xp, ");
        sb.append("firemaking_xp, ");
        sb.append("crafting_xp, ");
        sb.append("smithing_xp, ");
        sb.append("mining_xp, ");
        sb.append("herblore_xp, ");
        sb.append("agility_xp, ");
        sb.append("thieving_xp, ");
        sb.append("slayer_xp, ");
        sb.append("farming_xp, ");
        sb.append("runecrafting_xp, ");
        sb.append("hunter_xp, ");
        sb.append("construction_xp)");
        sb.append("VALUES (" +
                "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " +
                "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " +
                "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " +
                "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " +
                "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " +
                "?, ?, ?)");
        return sb.toString();
    }
Referenced by saveHighscores().
getRank()
int com.runehive.game.service.HighscoreService.getRank (PlayerRight right) static private
Definition at line 59 of file HighscoreService.java.
{
        if (right == PlayerRight.ULTIMATE_IRONMAN)
            return 3;
        if (right == PlayerRight.HARDCORE_IRONMAN)
            return 2;
        if (right == PlayerRight.IRONMAN)
            return 1;
        return 0;
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.HARDCORE_IRONMAN, com.runehive.game.world.entity.mob.player.PlayerRight.IRONMAN, and com.runehive.game.world.entity.mob.player.PlayerRight.ULTIMATE_IRONMAN.
Referenced by saveHighscores().
saveHighscores()
void com.runehive.game.service.HighscoreService.saveHighscores (Player player) static
Definition at line 24 of file HighscoreService.java.
{
        if (player == null || Config.WORLD_TYPE != WorldType.LIVE || PlayerRight.isAdministrator(player)) {
            return;
        }
        try (Connection connection = DriverManager.getConnection(CONNECTION_STRING, USERNAME, PASSWORD);
             PreparedStatement dsta = connection.prepareStatement("DELETE FROM hs_users WHERE id = ?");
             PreparedStatement ista = connection.prepareStatement(generateQuery())) {
            dsta.setInt(1, player.getMemberId());
            dsta.execute();
            ista.setInt(1, player.getMemberId());
            ista.setString(2, player.getName());
            ista.setInt(3, getRank(player.right));
            ista.setInt(4, getRank(player.right));
            ista.setInt(5, player.prestige.totalPrestige);
            for (int x = 0; x < Skill.SKILL_COUNT; x++) {
                ista.setInt(6 + x, player.prestige.prestige[x]);
            }
            ista.setInt(29, player.skills.getTotalLevel());
            ista.setLong(30, player.skills.getTotalXp());
            for (int i = 0; i < Skill.SKILL_COUNT; i++) {
                ista.setInt(31 + i, player.skills.get(i).getRoundedExperience());
            }
            ista.execute();
        } catch (SQLException ex) {
            logger.error(String.format("Failed to save highscores for player=%s", player.getName()), ex);
        }
    }
References CONNECTION_STRING, generateQuery(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.mob.player.Player.getMemberId(), com.runehive.game.world.entity.mob.player.Player.getName(), getRank(), com.runehive.game.world.entity.skill.Skill.getRoundedExperience(), com.runehive.game.world.entity.skill.SkillManager.getTotalLevel(), com.runehive.game.world.entity.skill.SkillManager.getTotalXp(), com.runehive.game.world.entity.mob.player.PlayerRight.isAdministrator(), com.runehive.game.world.WorldType.LIVE, logger, PASSWORD, com.runehive.content.prestige.Prestige.prestige, com.runehive.game.world.entity.mob.player.Player.prestige, com.runehive.game.world.entity.mob.player.Player.right, com.runehive.game.world.entity.skill.Skill.SKILL_COUNT, com.runehive.game.world.entity.mob.Mob.skills, com.runehive.content.prestige.Prestige.totalPrestige, USERNAME, and com.runehive.Config.WORLD_TYPE.
Referenced by com.runehive.game.world.entity.mob.player.persist.PlayerPersistDB.save().
Member Data Documentation
CONNECTION_STRING
final String com.runehive.game.service.HighscoreService.CONNECTION_STRING = "jdbc:mysql://45.88.231.118:3306/hiscores" static private
Definition at line 20 of file HighscoreService.java.
Referenced by saveHighscores().
logger
final Logger com.runehive.game.service.HighscoreService.logger = LogManager.getLogger(HighscoreService.class) static private
Definition at line 18 of file HighscoreService.java.
Referenced by saveHighscores().
PASSWORD
final String com.runehive.game.service.HighscoreService.PASSWORD = "bQ9R#UnPsW5^HLiU9$4LcJvE4%ZwJWLz" static private
Definition at line 22 of file HighscoreService.java.
Referenced by saveHighscores().
USERNAME
final String com.runehive.game.service.HighscoreService.USERNAME = "root" static private
Definition at line 21 of file HighscoreService.java.
Referenced by saveHighscores().
The documentation for this class was generated from the following file:
java/com/runehive/game/service/HighscoreService.java