RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow Class Reference
com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow Class Reference
Handles the magic shortbow weapon special attack.
Public Member Functions
CombatHit[] getHits (Player attacker, Mob defender)
int modifyAccuracy (Player attacker, Mob defender, int roll)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy
void attack (Player attacker, Mob defender, Hit hit)
boolean canAttack (Player attacker, Mob defender)
Animation getAttackAnimation (Player attacker, Mob defender)
int getAttackDelay (Player attacker, Mob defender, FightType fightType)
int getAttackDistance (Player attacker, FightType fightType)
CombatType getCombatType ()
void hit (Player attacker, Mob defender, Hit hit)
void start (Player attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static ZaryteCrossbow get ()
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions
void sendStuff (Player attacker, Mob defender)
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy
PlayerRangedStrategy ()
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Package Functions
[static initializer]
Private Member Functions
ZaryteCrossbow ()
Static Private Member Functions
static void setProjectiles (CombatProjectile projectile)
Static Private Attributes
static final Animation ANIMATION = new Animation(9166, UpdatePriority.HIGH)
static final ZaryteCrossbow INSTANCE = new ZaryteCrossbow()
static Projectile PROJECTILE
Additional Inherited Members
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Handles the magic shortbow weapon special attack.
Author
Daniel
Michaael | Chex
Definition at line 19 of file ZaryteCrossbow.java.
Constructor & Destructor Documentation
ZaryteCrossbow()
com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.ZaryteCrossbow () private
Definition at line 33 of file ZaryteCrossbow.java.
{
    }
Referenced by get().
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.[static initializer] static package
References com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition(), PROJECTILE, and setProjectiles().
get()
ZaryteCrossbow com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.get () static
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 62 of file ZaryteCrossbow.java.
{
        return INSTANCE;
    }
References INSTANCE, and ZaryteCrossbow().
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.getHits (Player attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 43 of file ZaryteCrossbow.java.
{
        return new CombatHit[]{nextRangedHit(attacker, defender)};
    }
References com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit().
modifyAccuracy()
int com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.modifyAccuracy (Player attacker, Mob defender, int roll)
Definition at line 52 of file ZaryteCrossbow.java.
{
        return (int) (2 * RangeAccuracy.getAttackRoll(attacker));
    }
References com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getAttackRoll().
sendStuff()
void com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.sendStuff (Player attacker, Mob defender) protected
Reimplemented from com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.
Definition at line 37 of file ZaryteCrossbow.java.
{
        attacker.animate(ANIMATION, true);
        PROJECTILE.send(attacker, defender);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), ANIMATION, and PROJECTILE.
setProjectiles()
void com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.setProjectiles (CombatProjectile projectile) static private
Definition at line 56 of file ZaryteCrossbow.java.
{
        if (!projectile.getProjectile().isPresent())
            throw new NullPointerException("No Magic Shortbow projectile found.");
        PROJECTILE = projectile.getProjectile().get();
    }
References PROJECTILE.
Referenced by [static initializer]().
Member Data Documentation
ANIMATION
final Animation com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.ANIMATION = new Animation(9166, UpdatePriority.HIGH) static private
Definition at line 22 of file ZaryteCrossbow.java.
Referenced by sendStuff().
INSTANCE
final ZaryteCrossbow com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.INSTANCE = new ZaryteCrossbow() static private
Definition at line 21 of file ZaryteCrossbow.java.
Referenced by get().
PROJECTILE
Projectile com.runehive.game.world.entity.combat.strategy.player.special.range.ZaryteCrossbow.PROJECTILE static private
Definition at line 23 of file ZaryteCrossbow.java.
Referenced by [static initializer](), sendStuff(), and setProjectiles().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/special/range/ZaryteCrossbow.java