RuneHive-Game: com.runehive.content.RoyaltyProgram Class Reference
com.runehive.content.RoyaltyProgram Class Reference
Created by Daniel on 2017-07-13.
Classes
enum RoyaltyReward
Holds all the RoyaltyReward data.
Static Public Member Functions
static void append (Player player)
Handles the royalty program reward.
static void append (Player player, int increment)
Handles the royalty program reward.
static void open (Player player)
Opens the Royalty Reward Program itemcontainer.
Detailed Description
Created by Daniel on 2017-07-13.
Definition at line 24 of file RoyaltyProgram.java.
Member Function Documentation
append() [1/2]
void com.runehive.content.RoyaltyProgram.append (Player player) static
Handles the royalty program reward.
Definition at line 64 of file RoyaltyProgram.java.
{
        append(player, 1);
    }
References append().
Referenced by append().
append() [2/2]
void com.runehive.content.RoyaltyProgram.append (Player player, int increment) static
Handles the royalty program reward.
Definition at line 69 of file RoyaltyProgram.java.
{
        player.royalty += increment;
        String suffix = increment > 1 ? "s" : "";
        int royalty = player.royalty;
        boolean levelUp = royalty >= 100;
        if (levelUp) {
            player.royaltyLevel++;
            player.royalty = 0;
            World.sendMessage("<col=9E4629> RP: " + PlayerRight.getCrown(player) + "<col=9E4629>" + player.getName()
                    + "</col> has just reached prestige <col=9E4629>" + player.royaltyLevel + "</col>.");
        }
        player.send(new SendMessage("You have just received <col=9E4629>" + increment + "</col> royalty point"
                + (suffix) + ". You now have <col=9E4629>" + player.royalty + "</col> point"
                + (player.royalty > 1 ? "s" : "") + " and are level <col=9E4629>" + player.royaltyLevel + "</col>."));
        if (!RoyaltyReward.forLevel(royalty).isPresent())
            return;
        RoyaltyReward reward = RoyaltyReward.forLevel(royalty).get();
        int item = reward.getReward().getId();
        int amount = reward.getReward().getAmount() * player.royaltyLevel;
        String name = ItemDefinition.get(item).getName();
        player.inventory.addOrDrop(new Item(item, amount));
        player.send(
                new SendMessage("You have been rewarded with " + amount + " " + name + ".", MessageColor.DARK_GREEN));
    }
References com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.util.MessageColor.DARK_GREEN, com.runehive.content.RoyaltyProgram.RoyaltyReward.forLevel(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.content.RoyaltyProgram.RoyaltyReward.getReward(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.royalty, com.runehive.game.world.entity.mob.player.Player.royaltyLevel, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.World.sendMessage().
open()
void com.runehive.content.RoyaltyProgram.open (Player player) static
Opens the Royalty Reward Program itemcontainer.
Definition at line 100 of file RoyaltyProgram.java.
{
        if (Area.inWilderness(player)) {
            player.dialogueFactory.sendStatement("You can not open a Royalty Program while in the wilderness!")
                    .execute();
            return;
        }
        if (player.getCombat().inCombat()) {
            player.dialogueFactory.sendStatement("You can not open a Royalty Program while in combat!").execute();
            return;
        }
        if (player.playerAssistant.busy()) {
            player.dialogueFactory.sendStatement("You can not open a Royalty Program right now!").execute();
            return;
        }
        else {
            int size = RoyaltyReward.values().length;
           // Item[] items = new Item[size + 3];
            for (int index = 0, string = 37116; index < size; index++) {
                RoyaltyReward perk = RoyaltyReward.forOrdinal(index).get();
                Item item = perk.getReward();
                int amount = player.royaltyLevel == 0 ? perk.getReward().getAmount()
                        : perk.getReward().getAmount() * player.royaltyLevel;
           //     items[index + 3] = new Item(item.getId(), amount);
                player.send(new SendString("<col=3c50b2>Level: " + perk.getLevel(), string++));
                player.send(new SendString("<col=347043>" + Utility.formatDigits(amount) + "x " + item.getName(),
                        string++));
            }
            player.send(new SendString("The Program rewards players for their activity in game. Every 30", 37111));
            player.send(
                    new SendString("minutes everyone is awarded 1 point. Points accumulate until 100 where", 37112));
            player.send(
                    new SendString("you gain a prestige level, points will be reset and you will be eligible", 37113));
            player.send(
                    new SendString("for the rewards again. Reward amounts are multiplied by prestige level.", 37114));
            player.send(new SendString("", 37115));
            player.send(new SendString("RP: " + player.royalty + "\\nLevel:" + player.royaltyLevel, 37107));
            player.send(new SendString("Royalty Program", 37103));
            player.send(new SendScrollbar(37110, size * 50));
          //  player.send(new SendItemOnInterface(37199, items));
            player.interfaceManager.open(37100);
        }
    }
References com.runehive.game.world.entity.mob.player.PlayerAssistant.busy(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.util.Utility.formatDigits(), com.runehive.content.RoyaltyProgram.RoyaltyReward.forOrdinal(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.content.RoyaltyProgram.RoyaltyReward.getLevel(), com.runehive.game.world.items.Item.getName(), com.runehive.content.RoyaltyProgram.RoyaltyReward.getReward(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.mob.player.InterfaceManager.open(), com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.game.world.entity.mob.player.Player.royalty, com.runehive.game.world.entity.mob.player.Player.royaltyLevel, com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
The documentation for this class was generated from the following file:
java/com/runehive/content/RoyaltyProgram.java