RuneHive-Game: com.runehive.game.engine.sync.task.PlayerPostUpdateTask Class Reference
com.runehive.game.engine.sync.task.PlayerPostUpdateTask Class Reference
Public Member Functions
PlayerPostUpdateTask (Player player)
void run ()
Private Attributes
final Player player
Static Private Attributes
static final Logger logger = LogManager.getLogger(PlayerPostUpdateTask.class)
Detailed Description
Definition at line 8 of file PlayerPostUpdateTask.java.
Constructor & Destructor Documentation
PlayerPostUpdateTask()
com.runehive.game.engine.sync.task.PlayerPostUpdateTask.PlayerPostUpdateTask (Player player)
Definition at line 14 of file PlayerPostUpdateTask.java.
{
        this.player = player;
    }
References player.
Referenced by run().
Member Function Documentation
run()
void com.runehive.game.engine.sync.task.PlayerPostUpdateTask.run ()
Definition at line 19 of file PlayerPostUpdateTask.java.
                      {
        try {
            player.viewport.calculateViewingDistance();
            player.updateFlags.clear();
            player.resetAnimation();
            player.resetGraphic();
            player.clearTeleportTarget();
            player.positionChange = false;
            player.regionChange = false;
            player.teleportRegion = false;
            player.facePosition = null;
            player.getEvents().reset();
            player.getSession().ifPresent(GameSession::processServerPacketQueue);
        } catch (Exception ex) {
            logger.error(String.format("Error in %s", PlayerPostUpdateTask.class.getSimpleName()), ex);
        }
    }
References logger, player, PlayerPostUpdateTask(), and com.runehive.net.session.GameSession.processServerPacketQueue().
Member Data Documentation
logger
final Logger com.runehive.game.engine.sync.task.PlayerPostUpdateTask.logger = LogManager.getLogger(PlayerPostUpdateTask.class) static private
Definition at line 10 of file PlayerPostUpdateTask.java.
Referenced by run().
player
final Player com.runehive.game.engine.sync.task.PlayerPostUpdateTask.player private
Definition at line 12 of file PlayerPostUpdateTask.java.
Referenced by PlayerPostUpdateTask(), and run().
The documentation for this class was generated from the following file:
java/com/runehive/game/engine/sync/task/PlayerPostUpdateTask.java