RuneHive-Game: com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc Class Reference
com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc Class Reference
@Author Origin 2/22/2023
Static Public Member Functions
static double getAttackRoll (Mob attacker, Mob defender, CombatType style)
static int getDefenceNpc (Mob defender)
static double getDefenceRoll (Mob defender, CombatType style)
static double getEffectiveLevelDefender (Mob defender)
static double getEffectiveRanged (Mob attacker, CombatType style)
static int getGearAttackBonus (Mob attacker, Mob defender, CombatType style)
static double getPrayerAttackBonus (Mob attacker)
static int getRangeDefenceLevelNpc (Mob defender, CombatType style)
static int getRangeLevel (Mob attacker)
static boolean successful (Mob attacker, Mob defender, CombatType style)
static double twistedBowBonus (Mob attacker, Mob defender)
Static Public Attributes
static final SecureRandom srand = new SecureRandom()
Detailed Description
@Author Origin 2/22/2023
Definition at line 22 of file RangeAccuracyNpc.java.
Member Function Documentation
getAttackRoll()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getAttackRoll (Mob attacker, Mob defender, CombatType style) static
Definition at line 158 of file RangeAccuracyNpc.java.
{
        double effectiveRangeLevel = getEffectiveRanged(attacker, style);
        double equipmentRangeBonus = getGearAttackBonus(attacker, defender, style);
        double maxRoll = effectiveRangeLevel * (equipmentRangeBonus);
        return (int) (maxRoll);
    }
References getEffectiveRanged(), and getGearAttackBonus().
getDefenceNpc()
int com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getDefenceNpc (Mob defender) static
Definition at line 55 of file RangeAccuracyNpc.java.
{
        return defender.getNpc().definition.getSkills()[1];
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.mob.Mob.getNpc(), and com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getSkills().
Referenced by getEffectiveLevelDefender().
getDefenceRoll()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getDefenceRoll (Mob defender, CombatType style) static
Definition at line 168 of file RangeAccuracyNpc.java.
{
        double effectiveDefenceLevel = getEffectiveLevelDefender(defender);
        int equipmentRangeBonus = getRangeDefenceLevelNpc(defender, style);
        double maxRoll = effectiveDefenceLevel * (equipmentRangeBonus);
        return (int) maxRoll;
    }
References getEffectiveLevelDefender(), and getRangeDefenceLevelNpc().
getEffectiveLevelDefender()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getEffectiveLevelDefender (Mob defender) static
Definition at line 98 of file RangeAccuracyNpc.java.
{
        return getDefenceNpc(defender) + 9;
    }
References getDefenceNpc().
Referenced by getDefenceRoll().
getEffectiveRanged()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getEffectiveRanged (Mob attacker, CombatType style) static
Definition at line 59 of file RangeAccuracyNpc.java.
{
        double effectiveLevel = Math.floor(getRangeLevel(attacker)) * getPrayerAttackBonus(attacker);
        FightStyle fightStyle = attacker.getCombat().getFightType().getStyle();
        switch (fightStyle) {
            case ACCURATE:
                effectiveLevel += 3.0D;
                break;
        }
        effectiveLevel += 8;
        if(attacker.isPlayer()) {
            if (style.equals(CombatType.RANGED)) {
                if (FormulaUtils.voidRanger((Player) attacker)) {
                    effectiveLevel *= 1.10D;
                    effectiveLevel = Math.floor(effectiveLevel);
                }
            }
                if (((Player) attacker).equipment.contains(Items.SALVE_AMULET)) {
                    effectiveLevel *= 1.10D;
            }//END OF UNDEAD
            if (Area.inWilderness(attacker)) {
                if (((Player) attacker).equipment.contains(22550)) {
                    effectiveLevel *= 1.50D;
                }
            }//END OF WILDERNESS BUFFS
            if (attacker.isNpc()) {
                if (((Player) attacker).equipment.contains(Items.SLAYER_HELMET)) {
                    effectiveLevel *= 1.05D;
                }
                if (((Player) attacker).equipment.contains(Items.BLACK_SLAYER_HELMET) || ((Player) attacker).equipment.contains(Items.GREEN_SLAYER_HELMET)  || ((Player) attacker).equipment.contains(Items.PURPLE_SLAYER_HELMET) || ((Player) attacker).equipment.contains(Items.RED_SLAYER_HELMET) || ((Player) attacker).equipment.contains(21888)) {
                    effectiveLevel *= 1.10D;
                }
            }
        }
        return Math.floor(effectiveLevel);
    }
References com.runehive.util.Items.BLACK_SLAYER_HELMET, com.runehive.game.world.entity.mob.Mob.getCombat(), getPrayerAttackBonus(), getRangeLevel(), com.runehive.util.Items.GREEN_SLAYER_HELMET, com.runehive.game.world.position.Area.inWilderness(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.util.Items.PURPLE_SLAYER_HELMET, com.runehive.game.world.entity.combat.CombatType.RANGED, com.runehive.util.Items.RED_SLAYER_HELMET, com.runehive.util.Items.SALVE_AMULET, com.runehive.util.Items.SLAYER_HELMET, and com.runehive.game.world.entity.combat.FormulaUtils.voidRanger().
Referenced by getAttackRoll().
getGearAttackBonus()
int com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getGearAttackBonus (Mob attacker, Mob defender, CombatType style) static
Definition at line 137 of file RangeAccuracyNpc.java.
{
        int bonus = 1;
        if (style == CombatType.RANGED) {
            bonus = attacker.getBonus(4);
        }
        if (attacker.getPlayer().equipment.contains(20997)) {
            bonus *= twistedBowBonus(attacker, defender);
        }
        return bonus;
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.Mob.getBonus(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.combat.CombatType.RANGED, and twistedBowBonus().
Referenced by getAttackRoll().
getPrayerAttackBonus()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus (Mob attacker) static
Definition at line 40 of file RangeAccuracyNpc.java.
{
        double prayerBonus = 1;
        if (attacker.getStrategy().getCombatType().equals(CombatType.RANGED)) {
            if (attacker.prayer.isActive(Prayer.SHARP_EYE))
                prayerBonus *= 1.05D; // 5% range level boost
            else if (attacker.prayer.isActive(Prayer.HAWK_EYE))
                prayerBonus *= 1.10D; // 10% range level boost
            else if (attacker.prayer.isActive(Prayer.EAGLE_EYE))
                prayerBonus *= 1.15D; // 15% range level boost
            else if (attacker.prayer.isActive(Prayer.RIGOUR))
                prayerBonus *= 1.20D; // 20% range level boost
        }
        return prayerBonus;
    }
References com.runehive.game.world.entity.mob.prayer.Prayer.EAGLE_EYE, com.runehive.game.world.entity.mob.Mob.getStrategy(), com.runehive.game.world.entity.mob.prayer.Prayer.HAWK_EYE, com.runehive.game.world.entity.mob.prayer.PrayerBook.isActive(), com.runehive.game.world.entity.mob.Mob.prayer, com.runehive.game.world.entity.combat.CombatType.RANGED, com.runehive.game.world.entity.mob.prayer.Prayer.RIGOUR, and com.runehive.game.world.entity.mob.prayer.Prayer.SHARP_EYE.
Referenced by getEffectiveRanged().
getRangeDefenceLevelNpc()
int com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getRangeDefenceLevelNpc (Mob defender, CombatType style) static
Definition at line 148 of file RangeAccuracyNpc.java.
{
        int bonus = 1;
        if (defender instanceof Npc) {
            if (style == CombatType.RANGED) {
                bonus = defender.getNpc().getBonus(9);
            }
        }
        return bonus;
    }
References com.runehive.game.world.entity.mob.npc.Npc.getBonus(), com.runehive.game.world.entity.mob.Mob.getNpc(), and com.runehive.game.world.entity.combat.CombatType.RANGED.
Referenced by getDefenceRoll().
getRangeLevel()
int com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getRangeLevel (Mob attacker) static
Definition at line 102 of file RangeAccuracyNpc.java.
{
        int rangeLevel = 1;
        if (attacker instanceof Npc npc) {
            if (npc.definition.getSkills() != null)
                rangeLevel = npc.definition.getSkills()[4];
        } else {
            rangeLevel = attacker.skills.getLevel(Skill.RANGED);
        }
        return rangeLevel;
    }
References com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.skill.Skill.RANGED, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by getEffectiveRanged().
successful()
boolean com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.successful (Mob attacker, Mob defender, CombatType style) static
Definition at line 25 of file RangeAccuracyNpc.java.
{
        double attackBonus = RangeAccuracy.getAttackRoll(attacker);//getAttackRoll(attacker, defender, style);
        double defenceBonus = RangeAccuracy.getDefenceRoll(defender);//getDefenceRoll(defender, style);
        double successfulRoll;
        double selectedChance = srand.nextDouble();
        if (attackBonus > defenceBonus)
            successfulRoll = 1D - (defenceBonus + 2D) / (2D * (attackBonus + 1D));
        else
            successfulRoll = attackBonus / (2D * (defenceBonus + 1D));
        return successfulRoll > selectedChance;
    }
References com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getAttackRoll(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getDefenceRoll(), and srand.
Referenced by com.runehive.game.world.entity.combat.attack.FormulaFactory.isAccurate().
twistedBowBonus()
double com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.twistedBowBonus (Mob attacker, Mob defender) static
Definition at line 113 of file RangeAccuracyNpc.java.
{
        double bonus = 1;
        double magicLevel = 1;
        int getMagicLevel = defender.skills.getMaxLevel(Skill.MAGIC);
        Player player = (Player) attacker;
        final Item weapon = player.equipment.getWeapon();
        if (weapon != null) {
            if (player.equipment.contains(20997)) {
                if (attacker.isPlayer()) {
                    if (defender instanceof Npc n) {
                        if (n.definition.getSkills() != null)
                            magicLevel = defender.skills.getMaxLevel(Skill.MAGIC) > 350 ? 350 :defender.skills.getMaxLevel(Skill.MAGIC) > 250D ? 250D : defender.skills.getMaxLevel(Skill.MAGIC);
                    } else {
                            magicLevel = getMagicLevel;
                    }
                    bonus += ((140 + (((10 * 3) * magicLevel) - 10) / 100D) - ((((3 * magicLevel) - 100D) * 2)) / 100D);
                    if (bonus > 2.4D)
                        bonus = (int) 2.4;
                }
            }
        }
        return bonus;
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.skill.Skill.MAGIC, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by getGearAttackBonus().
Member Data Documentation
srand
final SecureRandom com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.srand = new SecureRandom() static
Definition at line 23 of file RangeAccuracyNpc.java.
Referenced by successful().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/accuracy/RangeAccuracyNpc.java