RuneHive-Game: com.runehive.content.ActivityLogger Class Reference
com.runehive.content.ActivityLogger Class Reference
Handles displaying player's activity log.
Public Member Functions
ActivityLogger (Player player)
void add (ActivityLog log)
void add (ActivityLog log, int amount)
int get (ActivityLog log)
void open ()
Private Attributes
final Player player
Detailed Description
Handles displaying player's activity log.
Author
Daniel
Definition at line 14 of file ActivityLogger.java.
Constructor & Destructor Documentation
ActivityLogger()
com.runehive.content.ActivityLogger.ActivityLogger (Player player)
Definition at line 17 of file ActivityLogger.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
add() [1/2]
void com.runehive.content.ActivityLogger.add (ActivityLog log)
Definition at line 21 of file ActivityLogger.java.
{
        add(log, 1);
    }
References add().
Referenced by add(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), and com.runehive.game.world.entity.mob.npc.NpcDeath.postDeath().
add() [2/2]
void com.runehive.content.ActivityLogger.add (ActivityLog log, int amount)
Definition at line 25 of file ActivityLogger.java.
{
        int current = player.loggedActivities.computeIfAbsent(log, a -> 0);
        player.loggedActivities.put(log, current + amount);
        player.message("Your " + Utility.formatEnum(log.name()) + " count is now <col=FF0000>" + get(log) + "</col>.");
    }
References com.runehive.util.Utility.formatEnum(), and player.
get()
int com.runehive.content.ActivityLogger.get (ActivityLog log)
Definition at line 31 of file ActivityLogger.java.
{
        if (!player.loggedActivities.containsKey(log)) {
            player.loggedActivities.put(log, 0);
        }
        return player.loggedActivities.get(log);
    }
References player.
open()
void com.runehive.content.ActivityLogger.open ()
Definition at line 38 of file ActivityLogger.java.
                       {
        for (int index = 0, string = 37111; index < 80; index++) {
            player.send(new SendString("", string));
            string++;
            player.send(new SendString("", string));
            string++;
        }
        int string = 37111;
        for (ActivityLog log : ActivityLog.values()) {
            player.send(new SendString(Utility.formatEnum(log.name()) + ": <col=255>" + Utility.formatDigits(get(log)), string));
            string++;
        }
        player.send(new SendString("", 37107));
        player.send(new SendString("Activity Logger", 37103));
        player.send(new SendScrollbar(37110, (player.loggedActivities.size() * 55)));
        player.interfaceManager.open(37100);
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatEnum(), and player.
Referenced by com.runehive.game.plugin.PluginContext.onClick().
Member Data Documentation
player
final Player com.runehive.content.ActivityLogger.player private
Definition at line 15 of file ActivityLogger.java.
Referenced by ActivityLogger(), add(), get(), and open().
The documentation for this class was generated from the following file:
java/com/runehive/content/ActivityLogger.java