RuneHive-Game: com.runehive.game.world.entity.mob.npc.NpcAssistant Class Reference
com.runehive.game.world.entity.mob.npc.NpcAssistant Class Reference
Method handles small methods for npcs that do not have any parent class.
Public Member Functions
boolean isArmadyl ()
boolean isBandos ()
boolean isBoss ()
boolean isSaradomin ()
boolean isZamorak ()
void login ()
Handles initializing all the npc assistant methods on login.
void reloadSkills ()
Static Public Member Functions
static boolean isDragon (int id)
static Optional< CombatStrategy< Npc > > loadStrategy (Npc npc)
Package Functions
NpcAssistant (Npc npc)
Creates a new NpcAssistant
void respawn ()
Handles the npc respawning.
Private Member Functions
void setEvent ()
Handles setting all the events for the npc.
Private Attributes
Npc npc
The npc.
Detailed Description
Method handles small methods for npcs that do not have any parent class.
Author
Daniel
Definition at line 25 of file NpcAssistant.java.
Constructor & Destructor Documentation
NpcAssistant()
com.runehive.game.world.entity.mob.npc.NpcAssistant.NpcAssistant (Npc npc) package
Creates a new NpcAssistant
Definition at line 31 of file NpcAssistant.java.
{
        this.npc = npc;
    }
References npc.
Member Function Documentation
isArmadyl()
boolean com.runehive.game.world.entity.mob.npc.NpcAssistant.isArmadyl ()
Definition at line 130 of file NpcAssistant.java.
{
        for (int id : NpcUtility.ARMADYL) {
            if (npc.id == id)
                return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.npc.NpcUtility.ARMADYL, and npc.
Referenced by com.runehive.content.activity.impl.godwars.GodwarsListener.onKill().
isBandos()
boolean com.runehive.game.world.entity.mob.npc.NpcAssistant.isBandos ()
Definition at line 122 of file NpcAssistant.java.
{
        for (int id : NpcUtility.BANDOS) {
            if (npc.id == id)
                return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.npc.NpcUtility.BANDOS, and npc.
Referenced by com.runehive.content.activity.impl.godwars.GodwarsListener.onKill().
isBoss()
boolean com.runehive.game.world.entity.mob.npc.NpcAssistant.isBoss ()
Definition at line 114 of file NpcAssistant.java.
{
        for (int id : NpcUtility.BOSSES) {
            if (npc.id == id)
                return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.npc.NpcUtility.BOSSES, and npc.
Referenced by com.runehive.game.world.World.sendKillFeed().
isDragon()
boolean com.runehive.game.world.entity.mob.npc.NpcAssistant.isDragon (int id) static
Definition at line 63 of file NpcAssistant.java.
{
        for (int dragon : NpcUtility.DRAGONS) if (id == dragon) return true;
        return false;
    }
References com.runehive.game.world.entity.mob.npc.NpcUtility.DRAGONS.
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.DragonHunterCrossbowListener.modifyRangedLevel().
isSaradomin()
boolean com.runehive.game.world.entity.mob.npc.NpcAssistant.isSaradomin ()
Definition at line 138 of file NpcAssistant.java.
{
        for (int id : NpcUtility.SARADOMIN) {
            if (npc.id == id)
                return true;
        }
        return false;
    }
References npc, and com.runehive.game.world.entity.mob.npc.NpcUtility.SARADOMIN.
Referenced by com.runehive.content.activity.impl.godwars.GodwarsListener.onKill().
isZamorak()
boolean com.runehive.game.world.entity.mob.npc.NpcAssistant.isZamorak ()
Definition at line 146 of file NpcAssistant.java.
{
        for (int id : NpcUtility.ZAMORAK) {
            if (npc.id == id)
                return true;
        }
        return false;
    }
References npc, and com.runehive.game.world.entity.mob.npc.NpcUtility.ZAMORAK.
Referenced by com.runehive.content.activity.impl.godwars.GodwarsListener.onKill().
loadStrategy()
Optional< CombatStrategy< Npc > > com.runehive.game.world.entity.mob.npc.NpcAssistant.loadStrategy (Npc npc) static
Definition at line 68 of file NpcAssistant.java.
{
        if (!npc.definition.getCombatAttackData().isPresent()) {
            return Optional.empty();
        }
        NpcDefinition.CombatAttackData data = npc.definition.getCombatAttackData().get();
        CombatType type = data.type;
        switch (type) {
            case RANGED: {
                CombatProjectile definition = data.getDefinition();
                if (definition == null) {
                    throw new AssertionError("Could not find ranged projectile for Mob[id=" + npc.id + ", name=" + npc.getName() + "]");
                }
                return Optional.of(new NpcRangedStrategy(definition));
            }
            case MAGIC: {
                CombatProjectile definition = data.getDefinition();
                if (definition == null) {
                    throw new AssertionError("Could not find magic projectile for Mob[id=" + npc.id + ", name=" + npc.getName() + "]");
                }
                return Optional.of(new NpcMagicStrategy(definition));
            }
            case MELEE:
                return Optional.of(NpcMeleeStrategy.get());
        }
        return Optional.empty();
    }
References com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.get(), and npc.
Referenced by login(), and com.runehive.game.world.entity.mob.Mob.transform().
login()
void com.runehive.game.world.entity.mob.npc.NpcAssistant.login ()
Handles initializing all the npc assistant methods on login.
Definition at line 36 of file NpcAssistant.java.
{
        Combat<Npc> combat = npc.getCombat();
        NpcDefinition definition = NpcDefinition.get(npc.id);
        npc.definition = definition;
        npc.pathfinderProjectiles = Mob.pathfinderProjectiles(npc);
        npc.setWidth(definition.getSize());
        npc.setLength(definition.getSize());
        npc.setBonuses(definition.getBonuses());
        npc.mobAnimation.setNpcAnimations(definition);
        reloadSkills();
        CombatListener<Npc> listener = CombatListenerManager.NPC_LISTENERS.get(npc.id);
        if (listener != null) {
            combat.addListener(listener);
        }
        npc.setStrategy(NpcUtility.STRATEGIES.getOrDefault(npc.id, () -> loadStrategy(npc).orElse(NpcMeleeStrategy.get())).get());
        setEvent();
    }
References com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.get(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get(), loadStrategy(), npc, com.runehive.game.world.entity.combat.attack.listener.CombatListenerManager.NPC_LISTENERS, com.runehive.game.world.entity.mob.Mob.pathfinderProjectiles, reloadSkills(), setEvent(), and com.runehive.game.world.entity.mob.npc.NpcUtility.STRATEGIES.
Referenced by com.runehive.content.activity.impl.kraken.KrakenActivity.transform().
reloadSkills()
void com.runehive.game.world.entity.mob.npc.NpcAssistant.reloadSkills ()
Definition at line 57 of file NpcAssistant.java.
{
        for (int index = 0; index < npc.definition.getSkills().length; index++) {
            npc.skills.setNpcMaxLevel(index, npc.definition.getSkills()[index]);
        }
    }
References npc.
Referenced by login(), and com.runehive.game.world.entity.mob.Mob.transform().
respawn()
void com.runehive.game.world.entity.mob.npc.NpcAssistant.respawn () package
Handles the npc respawning.
Definition at line 98 of file NpcAssistant.java.
                   {
        npc.setVisible(true);
        npc.skills.restoreAll();
        npc.getCombat().reset();
    }
References npc.
setEvent()
void com.runehive.game.world.entity.mob.npc.NpcAssistant.setEvent () private
Handles setting all the events for the npc.
Definition at line 105 of file NpcAssistant.java.
{
        if (NpcForceChatParser.FORCED_MESSAGES.containsKey(npc.spawnPosition)) {
            NpcForceChatParser.ForcedMessage forcedMessage = NpcForceChatParser.FORCED_MESSAGES.get(npc.spawnPosition);
            if (forcedMessage.getId() == npc.id) {
                World.schedule(new ForceChatEvent(npc, forcedMessage));
            }
        }
    }
References com.runehive.util.parser.impl.NpcForceChatParser.FORCED_MESSAGES, npc, and com.runehive.game.world.World.schedule().
Referenced by login().
Member Data Documentation
npc
Npc com.runehive.game.world.entity.mob.npc.NpcAssistant.npc private
The npc.
Definition at line 28 of file NpcAssistant.java.
Referenced by isArmadyl(), isBandos(), isBoss(), isSaradomin(), isZamorak(), loadStrategy(), login(), NpcAssistant(), reloadSkills(), respawn(), and setEvent().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/npc/NpcAssistant.java