RuneHive-Game: com.runehive.net.packet.out.SendNpcUpdate Class Reference
com.runehive.net.packet.out.SendNpcUpdate Class Reference
The packet that's responsible for updating npcs.
Public Member Functions
boolean encode (Player player)
SendNpcUpdate ()
Public Member Functions inherited from com.runehive.net.packet.OutgoingPacket
void execute (Player player)
OutgoingPacket (int opcode, int capacity)
OutgoingPacket (int opcode, PacketType type)
OutgoingPacket (int opcode, PacketType type, int size)
Static Private Member Functions
static void addNewNpc (PacketBuilder packet, Player player, Npc npc)
static void appendAnimationMask (Npc npc, PacketBuilder maskBuf)
static void appendFaceCoordinateMask (Npc npc, PacketBuilder maskBuf)
static void appendFaceEntityMask (Npc npc, PacketBuilder maskBuf)
static void appendFirstHitMask (final Npc npc, final PacketBuilder updateBlock)
static void appendForceChatMask (Npc npc, PacketBuilder maskBuf)
static void appendGfxMask (Npc npc, PacketBuilder maskBuf)
static void appendSecondHitMask (final Npc npc, final PacketBuilder updateBlock)
static void appendTransformationMask (Npc npc, PacketBuilder maskBuf)
static void updateMovement (PacketBuilder packet, Npc npc)
static void updateNpc (PacketBuilder maskBuf, Npc npc)
Additional Inherited Members
Protected Attributes inherited from com.runehive.net.packet.OutgoingPacket
final PacketBuilder builder
Detailed Description
The packet that's responsible for updating npcs.
Author
nshusa
Definition at line 33 of file SendNpcUpdate.java.
Constructor & Destructor Documentation
SendNpcUpdate()
com.runehive.net.packet.out.SendNpcUpdate.SendNpcUpdate ()
Definition at line 35 of file SendNpcUpdate.java.
{
        super(65, PacketType.VAR_SHORT);
    }
References com.runehive.net.packet.PacketType.VAR_SHORT.
Member Function Documentation
addNewNpc()
void com.runehive.net.packet.out.SendNpcUpdate.addNewNpc (PacketBuilder packet, Player player, Npc npc) static private
Definition at line 103 of file SendNpcUpdate.java.
{
        packet.writeBits(16, npc.getIndex()); // 16 bits needed since server supports 32000 NPCs
        packet.writeBits(5, npc.getPosition().getY() - player.getPosition().getY());
        packet.writeBits(5, npc.getPosition().getX() - player.getPosition().getX());
        packet.writeBit(false); // discard walking queue
        packet.writeBits(Config.NPC_BITS, npc.id);
        packet.writeBit(npc.isUpdateRequired());
    }
References com.runehive.game.world.entity.Entity.getIndex(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.isUpdateRequired(), and com.runehive.Config.NPC_BITS.
Referenced by encode().
appendAnimationMask()
void com.runehive.net.packet.out.SendNpcUpdate.appendAnimationMask (Npc npc, PacketBuilder maskBuf) static private
Definition at line 195 of file SendNpcUpdate.java.
{
        Animation anim = npc.getAnimation().orElse(Animation.RESET);
        maskBuf.writeShort(anim.getId(), ByteOrder.LE)
                .writeByte(anim.getDelay());
    }
References com.runehive.game.world.entity.mob.Mob.getAnimation(), com.runehive.game.Animation.getDelay(), com.runehive.game.Animation.getId(), com.runehive.net.codec.ByteOrder.LE, com.runehive.game.Animation.RESET, com.runehive.net.packet.PacketBuilder.writeByte(), and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updateNpc().
appendFaceCoordinateMask()
void com.runehive.net.packet.out.SendNpcUpdate.appendFaceCoordinateMask (Npc npc, PacketBuilder maskBuf) static private
Definition at line 225 of file SendNpcUpdate.java.
{
        Position loc = npc.facePosition;
        if (loc == null) {
            Position currentPos = npc.getPosition();
            Direction currentDir = npc.movement.lastDirection;
            maskBuf.writeShort(((currentPos.getX() + currentDir.getDirectionX()) << 1) + 1, ByteOrder.LE)
                    .writeShort(((currentPos.getY() + currentDir.getDirectionY()) << 1) + 1, ByteOrder.LE);
        } else {
            maskBuf.writeShort((loc.getX() << 1) + 1, ByteOrder.LE)
                    .writeShort((loc.getY() << 1) + 1, ByteOrder.LE);
        }
    }
References com.runehive.game.world.entity.mob.Mob.facePosition, com.runehive.game.world.entity.mob.Direction.getDirectionX(), com.runehive.game.world.entity.mob.Direction.getDirectionY(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.movement.Movement.lastDirection, com.runehive.net.codec.ByteOrder.LE, com.runehive.game.world.entity.mob.Mob.movement, and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updateNpc().
appendFaceEntityMask()
void com.runehive.net.packet.out.SendNpcUpdate.appendFaceEntityMask (Npc npc, PacketBuilder maskBuf) static private
Definition at line 207 of file SendNpcUpdate.java.
{
        Mob mob = npc.interactingWith;
        int index = 65535;
        if (mob != null) {
            index = mob.getIndex();
            if (mob.isPlayer()) {
                index += 32768;
            }
            maskBuf.writeShort(index);
        } else {
            maskBuf.writeShort(index);
        }
    }
References com.runehive.game.world.entity.Entity.getIndex(), com.runehive.game.world.entity.mob.Mob.interactingWith, com.runehive.game.world.entity.mob.Mob.isPlayer(), and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updateNpc().
appendFirstHitMask()
void com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask (final Npc npc, final PacketBuilder updateBlock) static private
Definition at line 242 of file SendNpcUpdate.java.
{
        Hit hit = npc.firstHit;
        boolean multipleHits = hit.getMultipleHits() != null;
        updateBlock.writeByte(multipleHits ? 1 : 0);
        int max = npc.getMaximumHealth() >= 500 ? 200 : 100;
        int health = npc.getCurrentHealth() * max / npc.getMaximumHealth();
        if (health > max) health = max;
        if(multipleHits) {
            System.out.println("total 1 = " + hit.getMultipleHits().length);
            updateBlock.writeByte(hit.getMultipleHits().length);
            for(int index = 0; index < hit.getMultipleHits().length; index++) {
                Hit currentHit = hit.getMultipleHits()[index];
                int id = currentHit.getHitsplat().getId();
                if (currentHit.getHitsplat() == Hitsplat.NORMAL && currentHit.getDamage() > 0) {
                    id++;
                }
                updateBlock.writeByte(currentHit.getDamage());
                updateBlock.writeByte(id);
                updateBlock.writeByte(currentHit.getHitIcon().getId());
            }
        } else {
            int id = hit.getHitsplat().getId();
            if (hit.getHitsplat() == Hitsplat.NORMAL && hit.getDamage() > 0) {
                id++;
            }
            updateBlock.writeByte(hit.getDamage());
            updateBlock.writeByte(id);
            updateBlock.writeByte(hit.getHitIcon().getId());
        }
        updateBlock.writeByte(health);
        updateBlock.writeByte(max);
        /*int id = hit.getHitsplat().getId();
        int max = npc.getMaximumHealth() >= 500 ? 200 : 100;
        int health = max * npc.getCurrentHealth() / npc.getMaximumHealth();
        if (health > max) health = max;
        if (hit.getHitsplat() == Hitsplat.NORMAL && hit.getDamage() > 0) {
            id++;
        }
        updateBlock.writeByte(hit.getDamage());
        updateBlock.writeByte(id, ByteModification.ADD);
        updateBlock.writeByte(hit.getHitIcon().getId());
        updateBlock.writeByte(health);
        updateBlock.writeByte(max, ByteModification.NEG);*/
    }
References com.runehive.game.world.entity.mob.Mob.firstHit, com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.combat.hit.Hit.getDamage(), com.runehive.game.world.entity.combat.hit.Hit.getHitIcon(), com.runehive.game.world.entity.combat.hit.Hit.getHitsplat(), com.runehive.game.world.entity.combat.hit.HitIcon.getId(), com.runehive.game.world.entity.combat.hit.Hitsplat.getId(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.combat.hit.Hit.getMultipleHits(), com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL, and com.runehive.net.packet.PacketBuilder.writeByte().
Referenced by updateNpc().
appendForceChatMask()
void com.runehive.net.packet.out.SendNpcUpdate.appendForceChatMask (Npc npc, PacketBuilder maskBuf) static private
Definition at line 221 of file SendNpcUpdate.java.
{
        maskBuf.writeString(npc.forceChat);
    }
References com.runehive.game.world.entity.mob.Mob.forceChat, and com.runehive.net.packet.PacketBuilder.writeString().
Referenced by updateNpc().
appendGfxMask()
void com.runehive.net.packet.out.SendNpcUpdate.appendGfxMask (Npc npc, PacketBuilder maskBuf) static private
Definition at line 201 of file SendNpcUpdate.java.
{
        Graphic gfx = npc.getGraphic().orElse(Graphic.RESET);
        maskBuf.writeShort(gfx.getId())
                .writeInt(gfx.getDelay() | gfx.getHeight());
    }
References com.runehive.game.Graphic.getDelay(), com.runehive.game.world.entity.mob.Mob.getGraphic(), com.runehive.game.Graphic.getHeight(), com.runehive.game.Graphic.getId(), com.runehive.game.Graphic.RESET, com.runehive.net.packet.PacketBuilder.writeInt(), and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updateNpc().
appendSecondHitMask()
void com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask (final Npc npc, final PacketBuilder updateBlock) static private
Definition at line 302 of file SendNpcUpdate.java.
{
        Hit hit = npc.secondHit;
        Hit[] multipleHits = hit.getMultipleHits();
        boolean isMultipleHits = multipleHits != null;
        Hit[] multipleHitsArray = isMultipleHits ? Arrays.copyOf(multipleHits, multipleHits.length) : null;
        updateBlock.writeByte(isMultipleHits ? 1 : 0);
        int max = npc.getMaximumHealth() >= 500 ? 200 : 100;
        int health = npc.getCurrentHealth() * max / npc.getMaximumHealth();
        if (health > max) health = max;
        if(isMultipleHits) {
            updateBlock.writeByte(multipleHitsArray.length);
            for (Hit currentHit : multipleHitsArray) {
                int id = currentHit.getHitsplat().getId();
                if (currentHit.getHitsplat() == Hitsplat.NORMAL
                        && currentHit.getDamage() > 0) {
                    id++;
                }
                updateBlock.writeByte(currentHit.getDamage());
                updateBlock.writeByte(id);
                updateBlock.writeByte(currentHit.getHitIcon().getId());
            }
        } else {
            int id = hit.getHitsplat().getId();
            if (hit.getHitsplat() == Hitsplat.NORMAL && hit.getDamage() > 0) {
                id++;
            }
            updateBlock.writeByte(hit.getDamage());
            updateBlock.writeByte(id);
            updateBlock.writeByte(hit.getHitIcon().getId());
        }
        updateBlock.writeByte(health);
        updateBlock.writeByte(max);
        /*int id = hit.getHitsplat().getId();
        int max = npc.getMaximumHealth() >= 500 ? 200 : 100;
        int health = npc.getCurrentHealth() * max / npc.getMaximumHealth();
        if (health > max) health = max;
        if (hit.getHitsplat() == Hitsplat.NORMAL && hit.getDamage() > 0) {
            id++;
        }
        updateBlock.writeByte(hit.getDamage());
        updateBlock.writeByte(id, ByteModification.SUB);
        updateBlock.writeByte(hit.getHitIcon().getId());
        updateBlock.writeByte(health);
        updateBlock.writeByte(max, ByteModification.NEG);*/
    }
References com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.combat.hit.Hit.getDamage(), com.runehive.game.world.entity.combat.hit.Hit.getHitIcon(), com.runehive.game.world.entity.combat.hit.Hit.getHitsplat(), com.runehive.game.world.entity.combat.hit.HitIcon.getId(), com.runehive.game.world.entity.combat.hit.Hitsplat.getId(), com.runehive.game.world.entity.mob.Mob.getMaximumHealth(), com.runehive.game.world.entity.combat.hit.Hit.getMultipleHits(), com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL, com.runehive.game.world.entity.mob.Mob.secondHit, and com.runehive.net.packet.PacketBuilder.writeByte().
Referenced by updateNpc().
appendTransformationMask()
void com.runehive.net.packet.out.SendNpcUpdate.appendTransformationMask (Npc npc, PacketBuilder maskBuf) static private
Definition at line 238 of file SendNpcUpdate.java.
{
        maskBuf.writeShort(npc.id, ByteModification.ADD, ByteOrder.LE);
    }
References com.runehive.net.codec.ByteModification.ADD, com.runehive.game.world.entity.mob.Mob.id, com.runehive.net.codec.ByteOrder.LE, and com.runehive.net.packet.PacketBuilder.writeShort().
Referenced by updateNpc().
encode()
boolean com.runehive.net.packet.out.SendNpcUpdate.encode (Player player)
Reimplemented from com.runehive.net.packet.OutgoingPacket.
Definition at line 40 of file SendNpcUpdate.java.
{
        PacketBuilder maskBuf = PacketBuilder.alloc();
        try {
            builder.initializeAccess(AccessType.BIT);
            builder.writeBits(8, player.viewport.getNpcsInViewport().size());
            for (Iterator<Npc> itr = player.viewport.getNpcsInViewport().iterator(); itr.hasNext(); ) {
                Npc npc = itr.next();
                if (player.viewport.shouldRemove(npc)) {
                    if (npc.atomicPlayerCount.decrementAndGet() < 0) {
                        npc.atomicPlayerCount.set(0);
                    }
                    itr.remove();
                    builder.writeBits(1, 1);
                    builder.writeBits(2, 3);
                } else {
                    updateMovement(builder, npc);
                    if (npc.isUpdateRequired()) {
                        updateNpc(maskBuf, npc);
                    }
                }
            }
            int npcsAdded = 0;
            for (Npc localNpc : World.getRegions().getLocalNpcs(player)) {
                if (player.viewport.getNpcsInViewport().size() >= Viewport.CAPACITY || npcsAdded == Viewport.ADD_THRESHOLD) {
                    break;
                }
                if (player.viewport.add(localNpc)) {
                    npcsAdded++;
                    addNewNpc(builder, player, localNpc);
                    updateNpc(maskBuf, localNpc);
                    if (localNpc.atomicPlayerCount.incrementAndGet() < 0) {
                        localNpc.atomicPlayerCount.set(0);
                    }
                }
            }
            if (maskBuf.content().readableBytes() > 0) {
                builder.writeBits(16, 65535);
                builder.initializeAccess(AccessType.BYTE);
                builder.writeBytes(maskBuf.content());
            } else {
                builder.initializeAccess(AccessType.BYTE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            maskBuf.release();
        }
        return true;
    }
References com.runehive.game.world.entity.mob.Viewport.add(), com.runehive.game.world.entity.mob.Viewport.ADD_THRESHOLD, addNewNpc(), com.runehive.net.packet.PacketBuilder.alloc(), com.runehive.game.world.entity.mob.npc.Npc.atomicPlayerCount, com.runehive.net.codec.AccessType.BIT, com.runehive.net.packet.OutgoingPacket.builder, com.runehive.net.codec.AccessType.BYTE, com.runehive.game.world.entity.mob.Viewport.CAPACITY, com.runehive.game.world.region.RegionManager.getLocalNpcs(), com.runehive.game.world.entity.mob.Viewport.getNpcsInViewport(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.entity.mob.Mob.isUpdateRequired(), com.runehive.game.world.entity.mob.Viewport.shouldRemove(), updateMovement(), updateNpc(), and com.runehive.game.world.entity.mob.player.Player.viewport.
updateMovement()
void com.runehive.net.packet.out.SendNpcUpdate.updateMovement (PacketBuilder packet, Npc npc) static private
Definition at line 112 of file SendNpcUpdate.java.
{
        final boolean updateRequired = npc.isUpdateRequired();
        final Movement movement = npc.movement;
        final int runDirection = movement.getRunningDirection();
        final int walkDirection = movement.getWalkingDirection();
        if (runDirection != -1) {
            packet.writeBit(true)
                    .writeBits(2, 2)
                    .writeBits(3, walkDirection)
                    .writeBits(3, runDirection)
                    .writeBit(updateRequired);
        } else if (walkDirection != -1) {
            packet.writeBit(true)
                    .writeBits(2, 1)
                    .writeBits(3, walkDirection)
                    .writeBit(updateRequired);
        } else {
            packet.writeBit(updateRequired);
            if (updateRequired) {
                packet.writeBits(2, 0);
            }
        }
    }
References com.runehive.game.world.entity.mob.movement.Movement.getRunningDirection(), com.runehive.game.world.entity.mob.movement.Movement.getWalkingDirection(), com.runehive.game.world.entity.mob.Mob.isUpdateRequired(), and com.runehive.game.world.entity.mob.Mob.movement.
Referenced by encode().
updateNpc()
void com.runehive.net.packet.out.SendNpcUpdate.updateNpc (PacketBuilder maskBuf, Npc npc) static private
Definition at line 138 of file SendNpcUpdate.java.
{
        if (!npc.isUpdateRequired()) {
            return;
        }
        int mask = 0;
        final EnumSet<UpdateFlag> updateFlags = npc.updateFlags;
        for (UpdateFlag flag : UpdateFlag.npcOrder) {
            if (updateFlags.contains(flag) && flag.canApply(npc)) {
                mask |= flag.npcMask;
            }
        }
        maskBuf.writeByte(mask);
        // TODO replace the checks.
       /* for (UpdateFlag flag : UpdateFlag.npcOrder) {
            if (UpdateFlag.containsNpc(mask, flag)) {
            }
        }*/
        if (UpdateFlag.containsNpc(mask, UpdateFlag.ANIMATION)) {
            appendAnimationMask(npc, maskBuf);
        }
        if (UpdateFlag.containsNpc(mask, UpdateFlag.GRAPHICS)) {
            appendGfxMask(npc, maskBuf);
        }
        if (UpdateFlag.containsNpc(mask, UpdateFlag.INTERACT)) {
            appendFaceEntityMask(npc, maskBuf);
        }
        if (UpdateFlag.containsNpc(mask, UpdateFlag.FORCED_CHAT)) {
            appendForceChatMask(npc, maskBuf);
        }
        if (UpdateFlag.containsNpc(mask, UpdateFlag.FIRST_HIT)) {
            appendFirstHitMask(npc, maskBuf);
        }
        if (UpdateFlag.containsNpc(mask, UpdateFlag.SECOND_HIT)) {
            appendSecondHitMask(npc, maskBuf);
        }
        if (UpdateFlag.containsNpc(mask, UpdateFlag.TRANSFORM)) {
            appendTransformationMask(npc, maskBuf);
        }
        if (UpdateFlag.containsNpc(mask, UpdateFlag.FACE_COORDINATE)) {
            appendFaceCoordinateMask(npc, maskBuf);
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.ANIMATION, appendAnimationMask(), appendFaceCoordinateMask(), appendFaceEntityMask(), appendFirstHitMask(), appendForceChatMask(), appendGfxMask(), appendSecondHitMask(), appendTransformationMask(), com.runehive.game.world.entity.mob.UpdateFlag.canApply(), com.runehive.game.world.entity.mob.UpdateFlag.containsNpc(), com.runehive.game.world.entity.mob.UpdateFlag.FACE_COORDINATE, com.runehive.game.world.entity.mob.UpdateFlag.FIRST_HIT, com.runehive.game.world.entity.mob.UpdateFlag.FORCED_CHAT, com.runehive.game.world.entity.mob.UpdateFlag.GRAPHICS, com.runehive.game.world.entity.mob.UpdateFlag.INTERACT, com.runehive.game.world.entity.mob.Mob.isUpdateRequired(), com.runehive.game.world.entity.mob.UpdateFlag.npcMask, com.runehive.game.world.entity.mob.UpdateFlag.npcOrder, com.runehive.game.world.entity.mob.UpdateFlag.SECOND_HIT, com.runehive.game.world.entity.mob.UpdateFlag.TRANSFORM, com.runehive.game.world.entity.mob.Mob.updateFlags, and com.runehive.net.packet.PacketBuilder.writeByte().
Referenced by encode().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/out/SendNpcUpdate.java