RuneHive-Game: com.runehive.util.tools.wiki.parser.WikiTableParser Class Reference
com.runehive.util.tools.wiki.parser.WikiTableParser Class Reference abstract
Parses a wiki page.
Classes
class ParserTask
A task that parses a web page doccument using JSoup.
Public Member Functions
void begin () throws InterruptedException
Begins parsing wiki tables for all the names provided.
WikiTableParser (LinkedList< WikiTable > tables)
Constructs a new WikiTableParser object.
Protected Member Functions
void execute (Runnable runnable)
abstract void finish ()
Static Protected Member Functions
static void writeToJson (String name, JsonElement array)
Writes the parsed wiki dump to a json file in ./data/wiki named as the name parameter.
Protected Attributes
final LinkedList< WikiTable > tables
The WikiTable list to parse.
Static Protected Attributes
static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create()
The gson object.
static final String WIKI_LINK = "http://oldschoolrunescape.wikia.com/wiki/"
The path to the wiki page address.
Private Attributes
final ListeningExecutorService executorService
A thread pool that will run tasks.
Static Private Attributes
static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(WikiTableParser.class)
static final Path WRITE_PATH = Paths.get("./data/wiki")
The path to the wiki dump json file location.
Detailed Description
Parses a wiki page.
Author
Michael | Chex
Definition at line 27 of file WikiTableParser.java.
Constructor & Destructor Documentation
WikiTableParser()
com.runehive.util.tools.wiki.parser.WikiTableParser.WikiTableParser (LinkedList< WikiTable > tables)
Constructs a new WikiTableParser object.
Definition at line 47 of file WikiTableParser.java.
{
        this.tables = tables;
        ExecutorService delegateService = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors(),
                new ThreadFactoryBuilder().setNameFormat("WikiTableParserThread").build());
        executorService = MoreExecutors.listeningDecorator(delegateService);
    }
References executorService, and tables.
Member Function Documentation
begin()
void com.runehive.util.tools.wiki.parser.WikiTableParser.begin () throws InterruptedException
Begins parsing wiki tables for all the names provided.
Definition at line 55 of file WikiTableParser.java.
{
        int size = tables.size();
        logger.info("Parsing " + size + " names from " + WIKI_LINK);
        tables.forEach(table -> execute(new ParserTask(table)));
        executorService.shutdown();
        executorService.awaitTermination(Long.MAX_VALUE, TimeUnit.DAYS);
        finish();
    }
References execute(), executorService, finish(), logger, tables, and WIKI_LINK.
execute()
void com.runehive.util.tools.wiki.parser.WikiTableParser.execute (Runnable runnable) protected
Definition at line 67 of file WikiTableParser.java.
{
        executorService.execute(runnable);
    }
References executorService.
Referenced by begin().
finish()
abstract void com.runehive.util.tools.wiki.parser.WikiTableParser.finish () abstract protected
Reimplemented in com.runehive.util.tools.wiki.impl.BonusParser, com.runehive.util.tools.wiki.impl.ItemDefParser, com.runehive.util.tools.wiki.impl.NpcDefParser, and com.runehive.util.tools.wiki.impl.NpcDropsParser.
Referenced by begin().
writeToJson()
void com.runehive.util.tools.wiki.parser.WikiTableParser.writeToJson (String name, JsonElement array) static protected
Writes the parsed wiki dump to a json file in ./data/wiki named as the name parameter.
Parameters
name the name of the json file to dump to
Definition at line 79 of file WikiTableParser.java.
{
        try {
            String json = GSON.toJson(array);
            if (!Files.exists(WRITE_PATH)) {
                Files.createDirectory(WRITE_PATH);
            }
            Path path = WRITE_PATH.resolve(name += ".json");
            Files.write(path, json.getBytes());
            logger.info("Successfully wrote " + path);
        } catch (IOException e) {
            logger.warn("Could not save '" + name + "' to '" + WRITE_PATH + "'", e);
        }
    }
References GSON, logger, and WRITE_PATH.
Referenced by com.runehive.util.tools.wiki.impl.BonusParser.finish(), com.runehive.util.tools.wiki.impl.ItemDefParser.finish(), and com.runehive.util.tools.wiki.impl.NpcDropsParser.finish().
Member Data Documentation
executorService
final ListeningExecutorService com.runehive.util.tools.wiki.parser.WikiTableParser.executorService private
A thread pool that will run tasks.
Definition at line 41 of file WikiTableParser.java.
Referenced by begin(), execute(), and WikiTableParser().
GSON
final Gson com.runehive.util.tools.wiki.parser.WikiTableParser.GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create() static protected
The gson object.
Definition at line 38 of file WikiTableParser.java.
Referenced by com.runehive.util.tools.wiki.impl.BonusParser.finish(), com.runehive.util.tools.wiki.impl.BonusParser.generateTables(), and writeToJson().
logger
final org.apache.logging.log4j.Logger com.runehive.util.tools.wiki.parser.WikiTableParser.logger = LogManager.getLogger(WikiTableParser.class) static private
Definition at line 35 of file WikiTableParser.java.
Referenced by begin(), and writeToJson().
tables
final LinkedList<WikiTable> com.runehive.util.tools.wiki.parser.WikiTableParser.tables protected
The WikiTable list to parse.
Definition at line 44 of file WikiTableParser.java.
Referenced by begin(), com.runehive.util.tools.wiki.impl.BonusParser.finish(), com.runehive.util.tools.wiki.impl.ItemDefParser.finish(), com.runehive.util.tools.wiki.impl.NpcDropsParser.finish(), com.runehive.util.tools.wiki.impl.BonusParser.generateTables(), com.runehive.util.tools.wiki.impl.ItemDefParser.generateTables(), com.runehive.util.tools.wiki.impl.NpcDefParser.generateTables(), com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables(), and WikiTableParser().
WIKI_LINK
final String com.runehive.util.tools.wiki.parser.WikiTableParser.WIKI_LINK = "http://oldschoolrunescape.wikia.com/wiki/" static protected
The path to the wiki page address.
Definition at line 33 of file WikiTableParser.java.
Referenced by begin(), and com.runehive.util.tools.wiki.impl.NpcDropsParser.generateTables().
WRITE_PATH
final Path com.runehive.util.tools.wiki.parser.WikiTableParser.WRITE_PATH = Paths.get("./data/wiki") static private
The path to the wiki dump json file location.
Definition at line 30 of file WikiTableParser.java.
Referenced by writeToJson().
The documentation for this class was generated from the following file:
java/com/runehive/util/tools/wiki/parser/WikiTableParser.java