RuneHive-Game: com.runehive.content.skill.impl.farming.patches.WaterablePatch Class Reference
com.runehive.content.skill.impl.farming.patches.WaterablePatch Class Reference abstract
A DiseasablePatch that can prevent disease with water.
Public Member Functions
boolean itemOnObject (Item item, int index)
WaterablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new WaterablePatch object.
Public Member Functions inherited from com.runehive.content.skill.impl.farming.patches.DiseasablePatch
boolean clickObject (int opcode)
void fromJson (JsonObject object)
JsonObject toJson ()
Public Member Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
int getConfig ()
boolean isComposted ()
boolean isDead ()
boolean isDiseased ()
boolean isEmpty ()
boolean isGrowing ()
boolean isNormal ()
boolean isWatered ()
boolean needsWeeding ()
abstract Plant plantForSeed (int seedId)
void setDead ()
void setDiseased ()
void setEmpty ()
void setNormal ()
void setWatered ()
void tick ()
boolean within (Position position)
Protected Member Functions
void onGrowth ()
Protected Member Functions inherited from com.runehive.content.skill.impl.farming.patches.DiseasablePatch
DiseasablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
void resetPatch ()
Protected Member Functions inherited from com.runehive.content.skill.impl.farming.patches.HarvestablePatch
abstract int animation ()
abstract int getMaxAmount ()
abstract int getMinAmount ()
Private Member Functions
boolean waterPatch (int itemId, int index)
Waters this patch to prevent disease if requirements are met.
Additional Inherited Members
Protected Attributes inherited from com.runehive.content.skill.impl.farming.patches.DiseasablePatch
boolean watched
Protected Attributes inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
CompostType compost
boolean fullyGrown
int growth
Plant plant
final Player player
FarmingStage stage = FarmingStage.FULL_WEEDS
FarmingState state = FarmingState.NORMAL
final Stopwatch timer = Stopwatch.start()
final FarmingZone zone
Package Functions inherited from com.runehive.content.skill.impl.farming.patches.HarvestablePatch
HarvestablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new HarvestablePatch object.
Package Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
FarmingPatch (Player player, FarmingZone zone, Interactable[] boundaries)
Detailed Description
A DiseasablePatch that can prevent disease with water.
Author
Michael | Chex
Definition at line 15 of file WaterablePatch.java.
Constructor & Destructor Documentation
WaterablePatch()
com.runehive.content.skill.impl.farming.patches.WaterablePatch.WaterablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new WaterablePatch object.
Parameters
player the player that owns this patch
zone the zone this patch belongs in
boundaries the boundaries of this patch
Definition at line 24 of file WaterablePatch.java.
{
        super(player, zone, boundaries);
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.boundaries, com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, and com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone.
Member Function Documentation
itemOnObject()
boolean com.runehive.content.skill.impl.farming.patches.WaterablePatch.itemOnObject (Item item, int index)
Reimplemented from com.runehive.content.skill.impl.farming.patches.DiseasablePatch.
Reimplemented in com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch.
Definition at line 73 of file WaterablePatch.java.
{
        return waterPatch(item.getId(), index) || super.itemOnObject(item, index);
    }
References com.runehive.game.world.items.Item.getId(), and waterPatch().
onGrowth()
void com.runehive.content.skill.impl.farming.patches.WaterablePatch.onGrowth () protected
Reimplemented from com.runehive.content.skill.impl.farming.patches.DiseasablePatch.
Definition at line 85 of file WaterablePatch.java.
{
        super.onGrowth();
        if (isWatered()) {
            setNormal();
        }
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.isWatered(), and com.runehive.content.skill.impl.farming.patches.FarmingPatch.setNormal().
waterPatch()
boolean com.runehive.content.skill.impl.farming.patches.WaterablePatch.waterPatch (int itemId, int index) private
Waters this patch to prevent disease if requirements are met.
Parameters
itemId the presumed watering can item id
index the inventory index of the item
Returns
true if this patch was successfully watered
Definition at line 35 of file WaterablePatch.java.
{
        if (player.locking.locked()) {
            return false;
        }
        if (itemId != 5331 && (itemId < 5333 || itemId > 5340)) {
            return false;
        }
        if (!isGrowing()) {
            player.message("This patch needs to be growing something first.");
            return true;
        }
        if (isWatered() || fullyGrown) {
            player.message("This patch doesn't need watering.");
            return true;
        }
        if (itemId == 5331) {
            player.dialogueFactory.sendStatement("This watering can is empty.").execute();
            return true;
        }
        player.message("You water the patch.");
        player.animate(FarmingConstants.WATERING_CAN_ANIM);
        player.inventory.replace(itemId, itemId == 5333 ? itemId - 2 : itemId - 1, index, true);
        player.locking.lock(5 * 3 / 5);
        setWatered();
        World.schedule(5, () -> {
            player.resetAnimation();
            zone.sendPatchConfigs(player);
        });
        return true;
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.fullyGrown, com.runehive.content.skill.impl.farming.patches.FarmingPatch.isGrowing(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.isWatered(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, com.runehive.game.world.World.schedule(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.setWatered(), com.runehive.content.skill.impl.farming.FarmingConstants.WATERING_CAN_ANIM, and com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone.
Referenced by itemOnObject().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/farming/patches/WaterablePatch.java