RuneHive-Game: com.runehive.content.gambling.GambleManager Class Reference
com.runehive.content.gambling.GambleManager Class Reference
Public Member Functions
void accept (Player player)
Handles accepting the gamble.
void acceptRequest (Player player, Player other)
Handles accepting a request.
boolean canGamble (Player player, GambleStage requiredStage)
Checks if the player is allowed to gamble or not.
boolean canPlayFlowerPokerAtPositon (Player player, Position position)
Checks if the position that was selected is suitable for a game of flower poker.
void decline (Player player)
Handles declining the gamble.
void deposit (Player player, int itemId, int slot, int amount)
Deposit a item into the gamble session.
void finish (Player host, Player opponent, int hostScore, int opponentScore)
Handles finishing up a automated gamble.
ItemContainer getContainer ()
ArrayList< Flowers > getFlowers ()
Gamble getGame ()
ArrayList< CustomGameObject > getGameFlowers ()
Player getOther ()
GambleStage getStage ()
GambleType getType ()
void give (GambleType gambleType, char winnerIdentifier, Player winner, Player loser, boolean draw)
Handles giving the players the winnings or returning the items when its a draw.
void handleModeSelection (Player player, GambleType type)
Handles setting the different game types.
boolean hasConfirmed ()
void open (Player player, Player other)
Handles opening the interface.
void removeFlowers (Player player)
void reset (Player player)
Handles resetting all the gambling variables for a player.
void sendRequest (Player player, Player other)
Handles sending a request to another player.
void setConfirmed (boolean confirmed)
void setGame (Gamble game)
void setOther (Player other)
void setStage (GambleStage stage)
void setType (GambleType type)
void withdraw (Player player, int itemId, int slot, int amount)
Withdraw an item from the gamble session.
Static Public Attributes
static final Boundary GAMBLING_ZONE = new Boundary(3148, 3476, 3181, 3505)
Protected Attributes
boolean confirmed
Checks if the player has confirmed the gamble.
ItemContainer container = new ItemContainer(18, ItemContainer.StackPolicy.STANDARD)
The container with gambled items of the player.
ArrayList< Flowers > flowers = new ArrayList<Flowers>()
Gamble game
The current gamble going on between the two players.
ArrayList< CustomGameObject > gameFlowers = new ArrayList<CustomGameObject>()
Player other
The other player within this gamble.
GambleStage stage = GambleStage.NONE
The current stage of the gamble.
GambleType type = GambleType.NONE
The gamble type going on.
Private Member Functions
Gamble getGame (Player other, Player player, GambleType type)
Get thet game based on the gamble type.
void send (GambleType gambleType, char winnerIdentifier, Player winner, Player loser)
Handles sending the message for who won.
void start (Player player)
Handles starting the gamble.
Private Attributes
final int CONFIG = 444
The config used for selecting the game type.
final int INTERFACE_ID = 44750
The main gambling interface.
final int INVENTORY_ID = 44775
Interface id for the player's inventory.
Detailed Description
Definition at line 22 of file GambleManager.java.
Member Function Documentation
accept()
void com.runehive.content.gambling.GambleManager.accept (Player player)
Handles accepting the gamble.
Parameters
player
Definition at line 222 of file GambleManager.java.
{
        Player other = player.getGambling().getOther();
        if (other == null) return;
        if(player.getGambling().getType() == null || player.getGambling().getType().equals(GambleType.NONE)) {
            player.message("You need to select a game first.");
            return;
        }
        if (System.currentTimeMillis() - player.getLastModification() < 5_000) {
            player.message("@red@Something was changed in the last 5 seconds, you cannot accept yet.");
            return;
        }
        if (player.getGambling().getType() != other.getGambling().getType()) return;
        if(player.getGambling().hasConfirmed()) return;
        player.getGambling().setConfirmed(true);
        player.message("You have accepted the gamble with "+String.format(other.getUsername())+".");
        other.message(String.format(player.getUsername()) + " has accepted the gamble.");
        System.out.println("player: " + String.format(player.getUsername()));
        System.out.println("other: " + String.format(other.getUsername()));
        if (other.getGambling().hasConfirmed()) {
            Gamble game = getGame(other, player, other.getGambling().getType());
            player.getGambling().setGame(game);
            other.getGambling().setGame(game);
            player.getGambling().setStage(GambleStage.SENDING_OFFER);
            player.getGambling().setOther(other);
            System.out.println("Both confirmed start the game...");
            start(player);
        }
    }
References game, com.runehive.game.world.entity.mob.player.Player.getGambling(), getGame(), com.runehive.game.world.entity.mob.player.Player.getLastModification(), getOther(), getType(), com.runehive.game.world.entity.mob.player.Player.getUsername(), hasConfirmed(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.content.gambling.GambleType.NONE, other, com.runehive.content.gambling.GambleStage.SENDING_OFFER, setConfirmed(), setGame(), setOther(), setStage(), and start().
acceptRequest()
void com.runehive.content.gambling.GambleManager.acceptRequest (Player player, Player other)
Handles accepting a request.
Parameters
player
other
Definition at line 183 of file GambleManager.java.
{
        if(player == other) return;
        if (!canGamble(player, GambleStage.NONE) || !canGamble(other, GambleStage.SENDING_OFFER)) return;
        player.getGambling().setStage(GambleStage.SENDING_OFFER);
        player.getGambling().setOther(other);
        if (other.getGambling().getOther() != null && player.getIndex() == other.getGambling().getOther().getIndex()) {
            System.out.println("accepted request...");
            open(other, player);
            open(player, other);
        }
    }
References canGamble(), com.runehive.game.world.entity.mob.player.Player.getGambling(), com.runehive.game.world.entity.Entity.getIndex(), com.runehive.content.gambling.GambleStage.NONE, open(), other, com.runehive.content.gambling.GambleStage.SENDING_OFFER, setOther(), and setStage().
Referenced by sendRequest().
canGamble()
boolean com.runehive.content.gambling.GambleManager.canGamble (Player player, GambleStage requiredStage)
Checks if the player is allowed to gamble or not.
Parameters
player
requiredStage
Returns
Definition at line 132 of file GambleManager.java.
{
        if(!Boundary.isIn(player, GAMBLING_ZONE)) return false;
        if (Objects.nonNull(requiredStage) && !player.getGambling().getStage().equals(requiredStage)) return false;
        return true;
    }
References GAMBLING_ZONE, com.runehive.game.world.entity.mob.player.Player.getGambling(), getStage(), and com.runehive.game.world.position.Boundary.isIn().
Referenced by acceptRequest(), and start().
canPlayFlowerPokerAtPositon()
boolean com.runehive.content.gambling.GambleManager.canPlayFlowerPokerAtPositon (Player player, Position position)
Checks if the position that was selected is suitable for a game of flower poker.
Parameters
player
position
Returns
Definition at line 271 of file GambleManager.java.
{
        //Checks if the spot its checking has a object placed there
        if (!TraversalMap.isTraversable(new Position(position.getX() + 1, position.getY()), Direction.SOUTH, player.width())) return false;
        boolean canPlay = true;
        for(int index = 0; index < 5; index++) {
            if (!TraversalMap.isTraversable(position, Direction.SOUTH, player.width())) {
                canPlay = false;
                break;
            }
            position = position.create(position.getX(), position.getY() + Direction.SOUTH.getDirectionY());
        }
        return canPlay;
    }
References com.runehive.game.world.position.Position.create(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.pathfinding.TraversalMap.isTraversable(), com.runehive.game.world.entity.mob.Direction.SOUTH, and com.runehive.game.world.entity.Entity.width.
Referenced by com.runehive.content.gambling.impl.FlowerPoker.gamble().
decline()
void com.runehive.content.gambling.GambleManager.decline (Player player)
Handles declining the gamble.
Parameters
player
Definition at line 290 of file GambleManager.java.
{
        Player other = player.getGambling().getOther();
        for(Item item : player.getGambling().getContainer()) {
            if(item == null || item.getId() == -1) continue;
            if(player.inventory.hasCapacityFor(item))
                player.inventory.add(item);
            else {
                player.bank.add(item);
                player.message("@red@You had no room for the "+item.getAmount()+" x "+item.getDefinition().getName()+", its been sent to your bank.");
            }
        }
        player.getGambling().getContainer().clear();
        player.inventory.refresh();
        player.bank.refresh();
        if(other != null) {
            for(Item item : other.getGambling().getContainer()) {
                if(item == null || item.getId() == -1) continue;
                if(other.inventory.hasCapacityFor(item))
                    other.inventory.add(item);
                else {
                    other.bank.add(item);
                    other.message("@red@You had no room for the "+item.getAmount()+" x "+item.getDefinition().getName()+", its been sent to your bank.");
                }
            }
            other.getGambling().getContainer().clear();
            other.inventory.refresh();
            other.bank.refresh();
            reset(other);
        }
        reset(player);
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.mob.player.Player.bank, com.runehive.game.world.items.containers.ItemContainer.clear(), getContainer(), com.runehive.game.world.entity.mob.player.Player.getGambling(), getOther(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), other, com.runehive.game.world.items.containers.bank.Bank.refresh(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), and reset().
Referenced by com.runehive.game.world.entity.mob.player.Player.unregister().
deposit()
void com.runehive.content.gambling.GambleManager.deposit (Player player, int itemId, int slot, int amount)
Deposit a item into the gamble session.
Parameters
player
slot
Definition at line 336 of file GambleManager.java.
{
        Player other = player.getGambling().getOther();
        if(other == null) return;
        ItemDefinition def = ItemDefinition.get(itemId);
        if (!def.isTradeable()) {
            player.send(new SendMessage("This is item is untradeable!"));
            return;
        }
        if(!player.inventory.contains(itemId)) return;
        if(amount > player.inventory.computeAmountForId(itemId))
            amount = player.inventory.computeAmountForId(itemId);
        if(amount <= 0) return;
        Item item = new Item(itemId, amount);
        if(player.getGambling().getContainer().hasCapacityFor(item)) {
            player.inventory.remove(item, slot);
            player.getGambling().getContainer().add(item);
            player.inventory.refresh();
            player.inventory.refresh(player, INVENTORY_ID + 1);
        } else
            player.message("Not enough space.");
        player.setLastModification(System.currentTimeMillis());
        other.setLastModification(System.currentTimeMillis());
        player.send(new SendItemOnInterface(44770, player.getGambling().getContainer().toArray()));
        player.send(new SendItemOnInterface(44771, other.getGambling().getContainer().toArray()));
        other.send(new SendItemOnInterface(44770, other.getGambling().getContainer().toArray()));
        other.send(new SendItemOnInterface(44771, player.getGambling().getContainer().toArray()));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.items.ItemDefinition.get(), getContainer(), com.runehive.game.world.entity.mob.player.Player.getGambling(), getOther(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, INVENTORY_ID, com.runehive.game.world.entity.mob.player.Player.message(), other, com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.Player.setLastModification(), and com.runehive.game.world.items.containers.ItemContainer.toArray().
finish()
void com.runehive.content.gambling.GambleManager.finish (Player host, Player opponent, int hostScore, int opponentScore)
Handles finishing up a automated gamble.
Parameters
host
opponent
hostScore
opponentScore
Definition at line 465 of file GambleManager.java.
{
        if (host.getGambling().getGame() == null)
            return;
        if (host.getGambling().getGame().getHost() == null)
            return;
        if (!World.getPlayers().contains(opponent) && World.getPlayers().contains(host)) {
            give(host.getGambling().getType(), 'H', host, opponent, false);
        } else if (World.getPlayers().contains(opponent) && !World.getPlayers().contains(host)) {
            give(host.getGambling().getType(), 'O', opponent, host, false);
        } else {
            if (hostScore == 55) {
                host.speak("The roll was a draw, rerolling...");
                opponent.speak("The roll was a draw, rerolling...");
                host.getGambling().setStage(GambleStage.IN_PROGRESS);
                opponent.getGambling().setStage(GambleStage.IN_PROGRESS);
                host.getGambling().getGame().gamble();
                return;
            }
            boolean hostWon = hostScore > opponentScore;
            give(host.getGambling().getType(), hostWon ? 'H' : 'O', hostWon ? host : opponent, hostWon ? opponent : host, false);
        }
    }
References com.runehive.content.gambling.Gamble.gamble(), com.runehive.game.world.entity.mob.player.Player.getGambling(), getGame(), com.runehive.content.gambling.Gamble.getHost(), com.runehive.game.world.World.getPlayers(), getType(), give(), com.runehive.content.gambling.GambleStage.IN_PROGRESS, setStage(), and com.runehive.game.world.entity.mob.Mob.speak().
Referenced by com.runehive.content.gambling.impl.FiftyFive.gamble(), com.runehive.content.gambling.impl.FlowerPoker.gamble(), and com.runehive.content.gambling.impl.FlowerPoker.plant().
getContainer()
ItemContainer com.runehive.content.gambling.GambleManager.getContainer ()
Definition at line 109 of file GambleManager.java.
{
        return container;
    }
References container.
Referenced by decline(), deposit(), give(), open(), and withdraw().
getFlowers()
ArrayList< Flowers > com.runehive.content.gambling.GambleManager.getFlowers ()
Definition at line 122 of file GambleManager.java.
{
        return flowers;
    }
References flowers.
Referenced by com.runehive.content.gambling.impl.FlowerPoker.gamble(), com.runehive.content.gambling.impl.FlowerPoker.getRank(), com.runehive.content.gambling.impl.FlowerPoker.plant(), and removeFlowers().
getGame() [1/2]
Gamble com.runehive.content.gambling.GambleManager.getGame ()
Definition at line 96 of file GambleManager.java.
{
        return game;
    }
References game.
Referenced by accept(), finish(), give(), and start().
getGame() [2/2]
Gamble com.runehive.content.gambling.GambleManager.getGame (Player other, Player player, GambleType type) private
Get thet game based on the gamble type.
Parameters
other
player
type
Returns
Definition at line 419 of file GambleManager.java.
{
        switch (type) {
            case FIFTY_FIVE:
                return new FiftyFive(player, other);
            case FLOWER_POKER:
                return new FlowerPoker(player, other);
        }
        return null;
    }
References other, and type.
getGameFlowers()
ArrayList< CustomGameObject > com.runehive.content.gambling.GambleManager.getGameFlowers ()
Definition at line 115 of file GambleManager.java.
{
        return gameFlowers;
    }
References gameFlowers.
Referenced by com.runehive.content.gambling.impl.FlowerPoker.gamble(), and removeFlowers().
getOther()
Player com.runehive.content.gambling.GambleManager.getOther ()
Definition at line 57 of file GambleManager.java.
{
        return other;
    }
References other.
Referenced by accept(), decline(), deposit(), handleModeSelection(), reset(), start(), and withdraw().
getStage()
GambleStage com.runehive.content.gambling.GambleManager.getStage ()
Definition at line 44 of file GambleManager.java.
{
        return stage;
    }
References stage.
Referenced by canGamble(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), and reset().
getType()
GambleType com.runehive.content.gambling.GambleManager.getType ()
Definition at line 83 of file GambleManager.java.
{
        return type;
    }
References type.
Referenced by accept(), and finish().
give()
void com.runehive.content.gambling.GambleManager.give (GambleType gambleType, char winnerIdentifier, Player winner, Player loser, boolean draw)
Handles giving the players the winnings or returning the items when its a draw.
Parameters
gambleType
winnerIdentifier
winner
loser
draw
Definition at line 500 of file GambleManager.java.
{
        if(draw) {
            winner.speak("It's a draw!");
            loser.speak("It's a draw!");
            removeFlowers(winner);
            removeFlowers(loser);
            winner.getGambling().setStage(GambleStage.IN_PROGRESS);
            loser.getGambling().setStage(GambleStage.IN_PROGRESS);
            winner.getGambling().getGame().gamble();
            return;
        } else {
            //Handle giving the winner the items
            for(Item item : winner.getGambling().getContainer()) {
                if(item == null || item.getId() == -1) continue;
                if(winner.inventory.hasCapacityFor(item))
                    winner.inventory.add(item);
                else {
                    winner.inventory.addOrDrop(item);
                    winner.bank.refresh();
                }
            }
            for(Item item : loser.getGambling().getContainer()) {
                if(item == null || item.getId() == -1) continue;
                if(winner.inventory.hasCapacityFor(item))
                    winner.inventory.add(item);
                else {
                    winner.inventory.addOrDrop(item);
                    winner.bank.refresh();
                }
            }
            send(gambleType, winnerIdentifier, winner, loser);
        }
        loser.getGambling().container.clear();
        winner.getGambling().container.clear();
        reset(loser);
        reset(winner);
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.game.world.entity.mob.player.Player.bank, com.runehive.game.world.items.containers.ItemContainer.clear(), container, com.runehive.content.gambling.Gamble.gamble(), getContainer(), com.runehive.game.world.entity.mob.player.Player.getGambling(), getGame(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.content.gambling.GambleStage.IN_PROGRESS, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.bank.Bank.refresh(), removeFlowers(), reset(), send(), setStage(), and com.runehive.game.world.entity.mob.Mob.speak().
Referenced by finish().
handleModeSelection()
void com.runehive.content.gambling.GambleManager.handleModeSelection (Player player, GambleType type)
Handles setting the different game types.
Parameters
player
type
Definition at line 579 of file GambleManager.java.
{
        Player other = player.getGambling().getOther();
        if(other == null) return;
        player.getGambling().setConfirmed(false);
        player.getGambling().setType(type);
        player.send(new SendConfig(CONFIG, type.ordinal()));
        player.setLastModification(System.currentTimeMillis());
        other.getGambling().setConfirmed(false);
        other.getGambling().setType(type);
        other.send(new SendConfig(CONFIG, type.ordinal()));
        other.setLastModification(System.currentTimeMillis());
    }
References CONFIG, com.runehive.game.world.entity.mob.player.Player.getGambling(), getOther(), other, com.runehive.game.world.entity.mob.player.Player.send(), setConfirmed(), com.runehive.game.world.entity.mob.player.Player.setLastModification(), setType(), and type.
hasConfirmed()
boolean com.runehive.content.gambling.GambleManager.hasConfirmed ()
Definition at line 70 of file GambleManager.java.
{
        return confirmed;
    }
References confirmed.
Referenced by accept().
open()
void com.runehive.content.gambling.GambleManager.open (Player player, Player other)
Handles opening the interface.
Parameters
player
other
Definition at line 203 of file GambleManager.java.
{
        player.getGambling().setConfirmed(false);
        player.getGambling().setStage(GambleStage.PLACING_BET);
        System.out.println("Open the interface for ["+String.format(player.getUsername())+"] and ["+String.format(other.getUsername())+"]...");
        player.send(new SendInventoryInterface(INTERFACE_ID, INVENTORY_ID));
        player.send(new SendItemOnInterface(44770, player.getGambling().getContainer().toArray()));
        player.send(new SendItemOnInterface(44771, other.getGambling().getContainer().toArray()));
        player.send(new SendItemOnInterface(INVENTORY_ID + 1, player.inventory.getItems()));
        player.send(new SendString("" + String.format(player.getUsername()), 44768));
        player.send(new SendString("" + String.format(other.getUsername()), 44769));
        player.send(new SendConfig(CONFIG, 0));
    }
References CONFIG, getContainer(), com.runehive.game.world.entity.mob.player.Player.getGambling(), com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.entity.mob.player.Player.getUsername(), INTERFACE_ID, com.runehive.game.world.entity.mob.player.Player.inventory, INVENTORY_ID, other, com.runehive.content.gambling.GambleStage.PLACING_BET, com.runehive.game.world.entity.mob.player.Player.send(), setConfirmed(), setStage(), and com.runehive.game.world.items.containers.ItemContainer.toArray().
Referenced by acceptRequest().
removeFlowers()
void com.runehive.content.gambling.GambleManager.removeFlowers (Player player)
Definition at line 619 of file GambleManager.java.
{
        for(CustomGameObject flowers : player.getGambling().getGameFlowers())
            flowers.unregister();
        player.getGambling().getGameFlowers().clear();
        player.getGambling().getFlowers().clear();
    }
References flowers, getFlowers(), com.runehive.game.world.entity.mob.player.Player.getGambling(), and getGameFlowers().
Referenced by give(), and reset().
reset()
void com.runehive.content.gambling.GambleManager.reset (Player player)
Handles resetting all the gambling variables for a player.
Parameters
player
Definition at line 599 of file GambleManager.java.
{
        if(player.getGambling().getStage().equals(GambleStage.NONE))
            return;
        player.getGambling().setConfirmed(false);
        player.getGambling().setGame(null);
        player.getGambling().setType(null);
        player.getGambling().setStage(GambleStage.NONE);
        player.setGambleLock(false);
        player.send(new SendRemoveInterface());
        player.send(new SendConfig(CONFIG, 0));
        removeFlowers(player);
        if(player.getGambling().getOther() != null)
            reset(player.getGambling().getOther());
        player.getGambling().setOther(null);
    }
References CONFIG, com.runehive.game.world.entity.mob.player.Player.getGambling(), getOther(), getStage(), com.runehive.content.gambling.GambleStage.NONE, removeFlowers(), reset(), com.runehive.game.world.entity.mob.player.Player.send(), setConfirmed(), com.runehive.game.world.entity.mob.player.Player.setGambleLock(), setGame(), setOther(), setStage(), and setType().
Referenced by decline(), give(), and reset().
send()
void com.runehive.content.gambling.GambleManager.send (GambleType gambleType, char winnerIdentifier, Player winner, Player loser) private
Handles sending the message for who won.
Parameters
gambleType
winnerIdentifier
winner
loser
Definition at line 559 of file GambleManager.java.
{
        switch(gambleType) {
            case FIFTY_FIVE -> {
                if (winnerIdentifier == 'H')
                    winner.speak("The roll was under 55, I have won the 55x2.");
                else
                    winner.speak("The roll was higher then 55, I have won the 55x2.");
            }
            default -> {
                winner.speak("I have won!");
                loser.speak("I have lost!");
            }
        }
    }
References com.runehive.game.world.entity.mob.Mob.speak().
Referenced by give().
sendRequest()
void com.runehive.content.gambling.GambleManager.sendRequest (Player player, Player other)
Handles sending a request to another player.
Parameters
player
other
Definition at line 146 of file GambleManager.java.
{
        if (PlayerRight.isIronman(player)) {
            player.message("You can not gamble as you are an iron man.");
            return;
        }
        if (PlayerRight.isIronman(other)) {
            player.message(other.getName() + " can not gamble as they are an iron man.");
            return;
        }
        if(player.playTime < 6000) {
            player.message("You must have at least 1 hour of play time to gamble.");
            return;
        }
        Player requested = other.getGambling().getOther();
        if (!Objects.isNull(requested)) {
            System.out.println("Accept...");
            acceptRequest(player, other);
            return;
        }
        player.message("You've sent a gamble invite to " + Utility.capitalizeSentence(other.getName()) + ".");
        other.message(Utility.capitalizeSentence(player.getName()) + ":gamblereq:");
        player.send(new SendRemoveInterface());
        player.getGambling().setOther(other);
        player.getGambling().setStage(GambleStage.SENDING_OFFER);
        System.out.println("send request...");
    }
References acceptRequest(), com.runehive.util.Utility.capitalizeSentence(), com.runehive.game.world.entity.mob.player.Player.getGambling(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.PlayerRight.isIronman(), com.runehive.game.world.entity.mob.player.Player.message(), other, com.runehive.game.world.entity.mob.player.Player.playTime, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.gambling.GambleStage.SENDING_OFFER, setOther(), and setStage().
setConfirmed()
void com.runehive.content.gambling.GambleManager.setConfirmed (boolean confirmed)
Definition at line 74 of file GambleManager.java.
{
        this.confirmed = confirmed;
    }
References confirmed.
Referenced by accept(), handleModeSelection(), open(), and reset().
setGame()
void com.runehive.content.gambling.GambleManager.setGame (Gamble game)
Definition at line 100 of file GambleManager.java.
{
        this.game = game;
    }
References game.
Referenced by accept(), and reset().
setOther()
void com.runehive.content.gambling.GambleManager.setOther (Player other)
Definition at line 61 of file GambleManager.java.
{
        this.other = other;
    }
References other.
Referenced by accept(), acceptRequest(), reset(), and sendRequest().
setStage()
void com.runehive.content.gambling.GambleManager.setStage (GambleStage stage)
Definition at line 48 of file GambleManager.java.
{
        this.stage = stage;
    }
References stage.
Referenced by accept(), acceptRequest(), finish(), give(), open(), reset(), sendRequest(), and start().
setType()
void com.runehive.content.gambling.GambleManager.setType (GambleType type)
Definition at line 87 of file GambleManager.java.
{
        this.type = type;
    }
References type.
Referenced by handleModeSelection(), and reset().
start()
void com.runehive.content.gambling.GambleManager.start (Player player) private
Handles starting the gamble.
Parameters
player
Definition at line 433 of file GambleManager.java.
{
        if (!canGamble(player, GambleStage.SENDING_OFFER)) return;
        Player other = player.getGambling().getOther();
        if (other == null) return;
        if (other.getGambling().hasConfirmed()) {
            if (player.getGambling().getGame() == null) return;
            if (player.getGambling().getGame().getHost() == null)  return;
            player.send(new SendRemoveInterface());
            other.send(new SendRemoveInterface());
            player.getGambling().setStage(GambleStage.IN_PROGRESS);
            other.getGambling().setStage(GambleStage.IN_PROGRESS);
            player.setGambleLock(true);
            other.setGambleLock(true);
            player.getGambling().getGame().gamble();
        }
    }
References canGamble(), com.runehive.content.gambling.Gamble.gamble(), com.runehive.game.world.entity.mob.player.Player.getGambling(), getGame(), com.runehive.content.gambling.Gamble.getHost(), getOther(), com.runehive.content.gambling.GambleStage.IN_PROGRESS, other, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.gambling.GambleStage.SENDING_OFFER, com.runehive.game.world.entity.mob.player.Player.setGambleLock(), and setStage().
Referenced by accept().
withdraw()
void com.runehive.content.gambling.GambleManager.withdraw (Player player, int itemId, int slot, int amount)
Withdraw an item from the gamble session.
Parameters
player
slot
Definition at line 379 of file GambleManager.java.
{
        Player other = player.getGambling().getOther();
        if(other == null) return;
        Item clickedItem = player.getGambling().getContainer().get(slot);
        if(clickedItem.getId() != itemId) return;
        if(amount > clickedItem.getAmount())
            amount = clickedItem.getAmount();
        if(!clickedItem.getDefinition().isStackable() && amount > player.inventory.getFreeSlots())
            amount = player.inventory.getFreeSlots();
        if(amount <= 0) return;
        player.getGambling().getContainer().remove(itemId, amount);
        player.inventory.add(itemId, amount);
        player.inventory.refresh();
        player.inventory.refresh(player, INVENTORY_ID + 1);
        player.setLastModification(System.currentTimeMillis());
        other.setLastModification(System.currentTimeMillis());
        player.send(new SendItemOnInterface(44770, player.getGambling().getContainer().toArray()));
        player.send(new SendItemOnInterface(44771, other.getGambling().getContainer().toArray()));
        other.send(new SendItemOnInterface(44770, other.getGambling().getContainer().toArray()));
        other.send(new SendItemOnInterface(44771, player.getGambling().getContainer().toArray()));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getAmount(), getContainer(), com.runehive.game.world.items.Item.getDefinition(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.entity.mob.player.Player.getGambling(), com.runehive.game.world.items.Item.getId(), getOther(), com.runehive.game.world.entity.mob.player.Player.inventory, INVENTORY_ID, other, com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.Player.setLastModification(), and com.runehive.game.world.items.containers.ItemContainer.toArray().
Member Data Documentation
CONFIG
final int com.runehive.content.gambling.GambleManager.CONFIG = 444 private
The config used for selecting the game type.
Definition at line 35 of file GambleManager.java.
Referenced by handleModeSelection(), open(), and reset().
confirmed
boolean com.runehive.content.gambling.GambleManager.confirmed protected
Checks if the player has confirmed the gamble.
Definition at line 68 of file GambleManager.java.
Referenced by hasConfirmed(), and setConfirmed().
container
ItemContainer com.runehive.content.gambling.GambleManager.container = new ItemContainer(18, ItemContainer.StackPolicy.STANDARD) protected
The container with gambled items of the player.
Definition at line 107 of file GambleManager.java.
Referenced by getContainer(), and give().
flowers
ArrayList<Flowers> com.runehive.content.gambling.GambleManager.flowers = new ArrayList<Flowers>() protected
Definition at line 120 of file GambleManager.java.
Referenced by getFlowers(), and removeFlowers().
GAMBLING_ZONE
final Boundary com.runehive.content.gambling.GambleManager.GAMBLING_ZONE = new Boundary(3148, 3476, 3181, 3505) static
Definition at line 37 of file GambleManager.java.
Referenced by canGamble(), and com.runehive.game.world.entity.mob.player.Player.onStep().
game
Gamble com.runehive.content.gambling.GambleManager.game protected
The current gamble going on between the two players.
Definition at line 94 of file GambleManager.java.
Referenced by accept(), getGame(), and setGame().
gameFlowers
ArrayList<CustomGameObject> com.runehive.content.gambling.GambleManager.gameFlowers = new ArrayList<CustomGameObject>() protected
Definition at line 113 of file GambleManager.java.
Referenced by getGameFlowers().
INTERFACE_ID
final int com.runehive.content.gambling.GambleManager.INTERFACE_ID = 44750 private
The main gambling interface.
Definition at line 27 of file GambleManager.java.
Referenced by open().
INVENTORY_ID
final int com.runehive.content.gambling.GambleManager.INVENTORY_ID = 44775 private
Interface id for the player's inventory.
Definition at line 31 of file GambleManager.java.
Referenced by deposit(), open(), and withdraw().
other
Player com.runehive.content.gambling.GambleManager.other protected
The other player within this gamble.
Definition at line 55 of file GambleManager.java.
Referenced by accept(), acceptRequest(), decline(), deposit(), getGame(), getOther(), handleModeSelection(), open(), sendRequest(), setOther(), start(), and withdraw().
stage
GambleStage com.runehive.content.gambling.GambleManager.stage = GambleStage.NONE protected
The current stage of the gamble.
Definition at line 42 of file GambleManager.java.
Referenced by getStage(), and setStage().
type
GambleType com.runehive.content.gambling.GambleManager.type = GambleType.NONE protected
The gamble type going on.
Definition at line 81 of file GambleManager.java.
Referenced by getGame(), getType(), handleModeSelection(), and setType().
The documentation for this class was generated from the following file:
java/com/runehive/content/gambling/GambleManager.java