RuneHive-Game: com.runehive.game.plugin.PluginManager Class Reference
com.runehive.game.plugin.PluginManager Class Reference
This class handles how plugins are loaded/unloaded and accessed.
Static Public Member Functions
static PlayerDataBus getDataBus ()
static int getPluginCount ()
static void load (final String pkg)
Private Member Functions
PluginManager ()
Static Private Attributes
static final PlayerDataBus dataBus = PlayerDataBus.getInstance()
static final Logger logger = LogManager.getLogger(PluginManager.class)
static final Set< String > plugins = new HashSet<>()
Detailed Description
This class handles how plugins are loaded/unloaded and accessed.
Author
nshusa
Definition at line 17 of file PluginManager.java.
Constructor & Destructor Documentation
PluginManager()
com.runehive.game.plugin.PluginManager.PluginManager () private
Definition at line 23 of file PluginManager.java.
{
        throw new UnsupportedOperationException();
    }
Referenced by load().
Member Function Documentation
getDataBus()
PlayerDataBus com.runehive.game.plugin.PluginManager.getDataBus () static
Definition at line 59 of file PluginManager.java.
{
        return dataBus;
    }
References dataBus.
Referenced by com.runehive.net.packet.in.ItemContainerActionPacketListener.allButOne(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fifthAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.firstAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.fourthAction(), com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnItem(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.net.packet.in.ItemOptionPacketListener.handleSecondOption(), com.runehive.net.packet.in.ItemOptionPacketListener.handleThirdOption(), com.runehive.net.packet.in.ItemContainerActionPacketListener.modifiableXAction(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.game.world.items.ground.GroundItem.pickup(), com.runehive.net.packet.in.ItemContainerActionPacketListener.secondAction(), com.runehive.net.packet.in.ItemContainerActionPacketListener.sixthAction(), and com.runehive.net.packet.in.ItemContainerActionPacketListener.thirdAction().
getPluginCount()
int com.runehive.game.plugin.PluginManager.getPluginCount () static
Definition at line 55 of file PluginManager.java.
{
        return plugins.size();
    }
References plugins.
load()
void com.runehive.game.plugin.PluginManager.load (final String pkg) static
Definition at line 27 of file PluginManager.java.
{
        try (final ScanResult scanResult =
                     new ClassGraph()
                             .enableClassInfo()
                             .enableMethodInfo()
                             .acceptPackages(pkg)
                             .scan()) {
            for (final ClassInfo classInfo : scanResult.getSubclasses(PluginContext.class)) {
                try {
                    if (!classInfo.isAbstract()) {
                        final MethodInfoList constructorInfos = classInfo.getDeclaredConstructorInfo();
                        final MethodInfo constructorInfo = constructorInfos.get(0);
                        final Constructor<?> constructor = constructorInfo.loadClassAndGetConstructor();
                        final Object instance = constructor.newInstance();
                        final PluginContext listener = (PluginContext) instance;
                        listener.onInit();
                        dataBus.subscribe(listener);
                        plugins.add(classInfo.getName());
                    }
                } catch (Exception ex) {
                    logger.error(String.format("Error loading plugin=%s", classInfo.getSimpleName()), ex);
                }
            }
        }
        logger.info(String.format("Loaded: %d plugins.", PluginManager.getPluginCount()));
    }
References dataBus, logger, com.runehive.game.plugin.PluginContext.onInit(), PluginManager(), and plugins.
Referenced by com.runehive.RuneHive.start().
Member Data Documentation
dataBus
final PlayerDataBus com.runehive.game.plugin.PluginManager.dataBus = PlayerDataBus.getInstance() static private
Definition at line 21 of file PluginManager.java.
Referenced by getDataBus(), and load().
logger
final Logger com.runehive.game.plugin.PluginManager.logger = LogManager.getLogger(PluginManager.class) static private
Definition at line 19 of file PluginManager.java.
Referenced by load().
plugins
final Set<String> com.runehive.game.plugin.PluginManager.plugins = new HashSet<>() static private
Definition at line 20 of file PluginManager.java.
Referenced by getPluginCount(), and load().
The documentation for this class was generated from the following file:
java/com/runehive/game/plugin/PluginManager.java