RuneHive-Game: com.runehive.content.activity.impl.magearena.MageArena Class Reference
com.runehive.content.activity.impl.magearena.MageArena Class Reference
The Kolodion's mage arena activity.
Classes
enum Stage
The stages of the activity.
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
ActivityDeathType deathType ()
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
void update ()
The update method.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
Static Public Member Functions
static MageArena create (Player player)
Creates a new MageArena activity.
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Member Functions
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
Position getAvailablePosition ()
Gets the next best available position.
MageArena (Player player, int instance)
Constructs a new MageArena.
void meteors ()
Handles the meteors.
Private Attributes
int killed
The amount of npcs the player has killed.
Map< Integer, Npc > monsters = new HashMap<>()
Holds all the monsters of the activity.
final Player player
The player instance.
int points
The amount of points the player has been awarded.
Stage stage = Stage.INITIALIZE
Activity completion flag.
Static Private Attributes
static final Position[] BOUNDARIES = Utility.getInnerBoundaries(new Position(3105, 3934, 0), 8, 8)
The spawn boundaries.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
The Kolodion's mage arena activity.
Author
Daniel
Definition at line 36 of file MageArena.java.
Constructor & Destructor Documentation
MageArena()
com.runehive.content.activity.impl.magearena.MageArena.MageArena (Player player, int instance) private
Constructs a new MageArena.
Definition at line 61 of file MageArena.java.
{
        super(5, instance);
        this.player = player;
    }
References com.runehive.content.activity.Activity.instance, and player.
Referenced by create().
Member Function Documentation
canTeleport()
boolean com.runehive.content.activity.impl.magearena.MageArena.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 183 of file MageArena.java.
{
        player.send(new SendMessage("You can not teleport out of this activity."));
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.magearena.MageArena.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 164 of file MageArena.java.
{
        for (Npc monster : monsters.values()) {
            monsters.remove(monster);
            remove(monster);
        }
    }
References monsters.
Referenced by finish().
create()
MageArena com.runehive.content.activity.impl.magearena.MageArena.create (Player player) static
Creates a new MageArena activity.
Definition at line 67 of file MageArena.java.
{
        MageArena activity = new MageArena(player, player.playerAssistant.instance());
        player.move(new Position(3105, 3934, 0));
        player.gameRecord.start();
        activity.add(player);
        activity.resetCooldown();
        return activity;
    }
References MageArena(), and player.
deathType()
ActivityDeathType com.runehive.content.activity.impl.magearena.MageArena.deathType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 221 of file MageArena.java.
{
        return ActivityDeathType.SAFE;
    }
References com.runehive.content.activity.ActivityDeathType.SAFE.
finish()
void com.runehive.content.activity.impl.magearena.MageArena.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 143 of file MageArena.java.
{
        long time = player.gameRecord.end(ActivityType.KOLODION_ARENA);
        cleanup();
        remove(player);
        ActivityPanel.clear(player);
        player.move(new Position(2540, 4715, 0));
        player.animate(Animation.RESET, true);
        player.graphic(Graphic.RESET, true);
        if (stage == Stage.FINISH) {
            points += 30;
            player.send(new SendMessage("You have completed Kolodion's arena. Final time: @red@" + Utility.getTime(time) + "</col>. Earned Points: @red@" + points + "</col>."));
            player.activityLogger.add(ActivityLog.KOLODIONS_MINIGAME);
            player.completedMageArena = true;
        }
        player.mageArenaPoints += points;
    }
References cleanup(), com.runehive.content.activity.panel.ActivityPanel.clear(), com.runehive.content.activity.impl.magearena.MageArena.Stage.FINISH, com.runehive.util.Utility.getTime(), com.runehive.content.activity.ActivityType.KOLODION_ARENA, com.runehive.content.ActivityLog.KOLODIONS_MINIGAME, player, points, com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, and stage.
Referenced by onDeath(), onLogout(), onRegionChange(), and start().
getAvailablePosition()
Position com.runehive.content.activity.impl.magearena.MageArena.getAvailablePosition () private
Gets the next best available position.
Definition at line 77 of file MageArena.java.
{
        Position available = Utility.randomElement(BOUNDARIES);
        while (!TraversalMap.isTraversable(available, Direction.NORTH, false)) {
            available = Utility.randomElement(BOUNDARIES);
        }
        return available;
    }
References BOUNDARIES, com.runehive.game.world.pathfinding.TraversalMap.isTraversable(), com.runehive.game.world.entity.mob.Direction.NORTH, and com.runehive.util.Utility.randomElement().
Referenced by start().
getType()
ActivityType com.runehive.content.activity.impl.magearena.MageArena.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 226 of file MageArena.java.
{
        return ActivityType.KOLODION_ARENA;
    }
References com.runehive.content.activity.ActivityType.KOLODION_ARENA.
meteors()
void com.runehive.content.activity.impl.magearena.MageArena.meteors () private
Handles the meteors.
Definition at line 86 of file MageArena.java.
{
        if (Utility.random(1, 3) == 2) {
            Position center = new Position(player.getX() - 2, player.getY() - 2, player.getHeight());
            Position[] bounds = Utility.getInnerBoundaries(center, 5, 5);
            Set<Position> meteors = new HashSet<>();
            for (Position bound : bounds) {
                if (Utility.random(100) > 55) {
                    meteors.add(bound);
                }
            }
            for (Position meteor : meteors) {
                World.sendGraphic(new Graphic(659), meteor, getInstance());
                World.schedule(1, () -> {
                    if (player.getPosition().equals(meteor))
                        player.damage(new Hit(Utility.random(5, 12)));
                });
            }
        }
    }
References com.runehive.util.Utility.getInnerBoundaries(), com.runehive.content.activity.Activity.getInstance(), meteors(), player, com.runehive.util.Utility.random(), com.runehive.game.world.World.schedule(), and com.runehive.game.world.World.sendGraphic().
Referenced by meteors(), and start().
onDeath()
void com.runehive.content.activity.impl.magearena.MageArena.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 199 of file MageArena.java.
{
        if (mob.isPlayer()) {
            mob.animate(Animation.RESET, true);
            mob.graphic(Graphic.RESET, true);
            finish();
            return;
        }
        if (monsters.containsKey(mob.id)) {
            killed++;
            points += Utility.random(15, 20);
            monsters.remove(mob.id);
            World.schedule(new NpcDeath(mob.getNpc()));
        }
        if (monsters.isEmpty()) {
            stage = Stage.FINISH;
            cooldown(10);
            return;
        }
        resetCooldown();
    }
References com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.content.activity.Activity.cooldown, com.runehive.content.activity.impl.magearena.MageArena.Stage.FINISH, finish(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.isPlayer(), killed, monsters, points, com.runehive.util.Utility.random(), com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, com.runehive.content.activity.Activity.resetCooldown(), com.runehive.game.world.World.schedule(), and stage.
onLogout()
void com.runehive.content.activity.impl.magearena.MageArena.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 172 of file MageArena.java.
{
        finish();
    }
References finish(), and player.
onRegionChange()
void com.runehive.content.activity.impl.magearena.MageArena.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 177 of file MageArena.java.
{
        if (!Area.inkolodionArena(player))
            finish();
    }
References finish(), com.runehive.game.world.position.Area.inkolodionArena(), and player.
start()
void com.runehive.content.activity.impl.magearena.MageArena.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 107 of file MageArena.java.
{
        switch (stage) {
            case INITIALIZE:
                for (int index = 0; index < 3; index++) {
                    int id = index == 0 ? 1157 : (index == 1 ? 1160 : 1158);
                    Npc monster = new Npc(id, getAvailablePosition());
                    monster.owner = player;
                    monsters.put(id, monster);
                    add(monster);
                }
                stage = Stage.FIGHTING;
                cooldown(1);
                break;
            case FIGHTING:
                for (Npc monster : monsters.values()) {
                    if (!monster.getCombat().isAttacking(player)) {
                        monster.getCombat().attack(player);
                        continue;
                    }
                    if (monster.getCombat().isUnderAttackBy(player) && Utility.random(5, 15) == 5) {
                        monster.speak("ARGHHH!");
                        World.sendGraphic(new Graphic(1213), player.getPosition(), getInstance());
                        player.damage(new Hit(Utility.random(1, 5)));
                        Teleportation.activateOverride(monster, getAvailablePosition(), TeleportationData.MODERN, () -> monster.getCombat().attack(player));
                    }
                }
                meteors();
                resetCooldown();
                break;
            case FINISH:
                finish();
                break;
        }
    }
References com.runehive.content.skill.impl.magic.teleport.Teleportation.activateOverride(), com.runehive.content.activity.Activity.add(), com.runehive.content.activity.Activity.cooldown, com.runehive.content.activity.impl.magearena.MageArena.Stage.FIGHTING, com.runehive.content.activity.Activity.FINISH, finish(), getAvailablePosition(), com.runehive.content.activity.Activity.getInstance(), meteors(), com.runehive.content.skill.impl.magic.teleport.TeleportationData.MODERN, monsters, player, com.runehive.util.Utility.random(), com.runehive.content.activity.Activity.resetCooldown(), com.runehive.game.world.World.sendGraphic(), and stage.
update()
void com.runehive.content.activity.impl.magearena.MageArena.update ()
The update method.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 189 of file MageArena.java.
{
        int progress = (int) Utility.getPercentageAmount(killed, 3);
        String clock = "Time: <col=FF5500>" + Utility.getTime(System.currentTimeMillis() - player.gameRecord.time) + "</col>";
        String remain = "Monsters Left: <col=FF5500>" + (3 - killed) + "</col>";
        String gained = "Points Gained: <col=FF5500>" + points + "</col>";
        Item[] items = {new Item(2412), new Item(2413), new Item(2414)};
        ActivityPanel.update(player, progress, "Mage's Arena", "Progress:", Utility.randomElement(items), clock, remain, gained);
    }
References com.runehive.util.Utility.getPercentageAmount(), com.runehive.util.Utility.getTime(), killed, player, points, com.runehive.util.Utility.randomElement(), and com.runehive.content.activity.panel.ActivityPanel.update().
Member Data Documentation
BOUNDARIES
final Position [] com.runehive.content.activity.impl.magearena.MageArena.BOUNDARIES = Utility.getInnerBoundaries(new Position(3105, 3934, 0), 8, 8) static private
The spawn boundaries.
Definition at line 38 of file MageArena.java.
Referenced by getAvailablePosition().
killed
int com.runehive.content.activity.impl.magearena.MageArena.killed private
The amount of npcs the player has killed.
Definition at line 49 of file MageArena.java.
Referenced by onDeath(), and update().
monsters
Map<Integer, Npc> com.runehive.content.activity.impl.magearena.MageArena.monsters = new HashMap<>() private
Holds all the monsters of the activity.
Definition at line 58 of file MageArena.java.
Referenced by cleanup(), onDeath(), and start().
player
final Player com.runehive.content.activity.impl.magearena.MageArena.player private
The player instance.
Definition at line 46 of file MageArena.java.
Referenced by canTeleport(), create(), finish(), MageArena(), meteors(), onLogout(), onRegionChange(), start(), and update().
points
int com.runehive.content.activity.impl.magearena.MageArena.points private
The amount of points the player has been awarded.
Definition at line 52 of file MageArena.java.
Referenced by finish(), onDeath(), and update().
stage
Stage com.runehive.content.activity.impl.magearena.MageArena.stage = Stage.INITIALIZE private
Activity completion flag.
Definition at line 55 of file MageArena.java.
Referenced by finish(), onDeath(), and start().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/magearena/MageArena.java