RuneHive-Game: com.runehive.content.activity.impl.godwars.GodwarsActivity Class Reference
com.runehive.content.activity.impl.godwars.GodwarsActivity Class Reference
Handles the godwars activity.
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onRegionChange (Player player)
Called when the player changes region.
void update ()
The update method.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
ActivityDeathType deathType ()
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
void onLogout (Player player)
Called when the player logs out.
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
Static Public Member Functions
static GodwarsActivity create (Player player)
Creates the godwars activity for the player.
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Member Functions
boolean clickObject (Player player, ObjectInteractionEvent event)
Optional< GodwarsListener > getListener ()
Gets an Optional of the ActivityListener for this activity.
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Package Functions
void increment (int index)
Increments the godwars kill count and updates the interface.
Static Package Attributes
static final int ARMADYL = 0
The indexes for the god wars kill count.
static final int BANDOS = 1
static final int SARADOMIN = 2
static final int ZAMORAK = 3
Private Member Functions
boolean canEnter (int index)
Checks if the player can enter the godwars chambers.
GodwarsActivity (Player player)
Constructs a new GodwarsActivity.
Private Attributes
int[] killCount = new int[4]
The kill count array.
final GodwarsListener listener = new GodwarsListener(this)
The combat listener for the god wars activity.
final Player player
The player instance of this activity.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Handles the godwars activity.
TODO: Add a way to get back up after climbing down to Saradomin chambers
Author
Daniel
Definition at line 26 of file GodwarsActivity.java.
Constructor & Destructor Documentation
GodwarsActivity()
com.runehive.content.activity.impl.godwars.GodwarsActivity.GodwarsActivity (Player player) private
Constructs a new GodwarsActivity.
Definition at line 40 of file GodwarsActivity.java.
{
        super(1, Mob.DEFAULT_INSTANCE);
        this.player = player;
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, and player.
Referenced by create().
Member Function Documentation
canEnter()
boolean com.runehive.content.activity.impl.godwars.GodwarsActivity.canEnter (int index) private
Checks if the player can enter the godwars chambers.
Definition at line 60 of file GodwarsActivity.java.
{
        if (PlayerRight.isOwner(player)) {
            return true;
        }
        if (player.inventory.contains(11942, 1)) {
            player.inventory.remove(11942);
            player.message("You have used your Ecumencial key to enter the room.");
            return true;
        }
        if (killCount[index] < 5) {
            player.message("You need 5 kills before accessing this door!");
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.PlayerRight.isOwner(), killCount, and player.
Referenced by clickObject().
canTeleport()
boolean com.runehive.content.activity.impl.godwars.GodwarsActivity.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 173 of file GodwarsActivity.java.
{
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.godwars.GodwarsActivity.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 87 of file GodwarsActivity.java.
{
        ActivityPanel.clear(player);
    }
References com.runehive.content.activity.panel.ActivityPanel.clear(), and player.
Referenced by onDeath().
clickObject()
boolean com.runehive.content.activity.impl.godwars.GodwarsActivity.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 101 of file GodwarsActivity.java.
{
        GameObject object = event.getObject();
        int identification = object.getId();
        switch (identification) {
            case 26502:
                if (canEnter(ARMADYL) && player.getPosition().getY() < object.getPosition().getY()) {
                    player.move(new Position(player.getX(), player.getY() + 2, 2));
                } else if (player.getPosition().getY() > object.getPosition().getY()) {
                    player.move(new Position(player.getX(), player.getY() - 2, 2));
                }
                return true;
            case 26503:
                if (canEnter(BANDOS) && player.getPosition().getX() < object.getPosition().getX()) {
                    player.move(new Position(player.getX() + 2, player.getY(), player.getHeight()));
                } else if (player.getPosition().getX() > object.getPosition().getX()) {
                    player.move(new Position(player.getX() - 2, player.getY(), player.getHeight()));
                }
                return true;
            case 26504:
                if (player.getPosition().getX() < object.getPosition().getX()) {
                    player.move(new Position(player.getX() + 2, player.getY(), 0));
                } else if (canEnter(SARADOMIN) && player.getPosition().getX() > object.getPosition().getX()) {
                    player.move(new Position(player.getX() - 2, player.getY(), 0));
                }
                return true;
            case 26505:
                if (canEnter(ZAMORAK) && player.getPosition().getY() > object.getPosition().getY()) {
                    player.move(new Position(player.getX(), player.getY() - 2, 2));
                } else if (player.getPosition().getY() < object.getPosition().getY()) {
                    player.move(new Position(player.getX(), player.getY() + 2, 2));
                }
                return true;
            case 26518:
                if (player.getY() == 5332) {
                    player.move(new Position(2885, 5345, 2));
                } else {
                    player.move(new Position(2885, 5332, 2));
                }
                return true;
            case 26380:
                if (player.getY() == 5269) {
                    player.move(new Position(2871, 5279, 2));
                } else {
                    player.move(new Position(2871, 5269, 2));
                }
                return true;
            case 26461:
                if (player.getX() >= 2851) {
                    player.move(new Position(2850, 5333, 2));
                } else {
                    player.move(new Position(2851, 5333, 2));
                }
                return true;
            case 26561:
                player.move(new Position(2918, 5300, 1));
                return true;
            case 26562:
                player.move(new Position(2919, 5274, 0));
                return true;
        }
        return false;
    }
References ARMADYL, BANDOS, canEnter(), com.runehive.game.world.object.GameObject.getId(), player, SARADOMIN, and ZAMORAK.
create()
GodwarsActivity com.runehive.content.activity.impl.godwars.GodwarsActivity.create (Player player) static
Creates the godwars activity for the player.
Definition at line 46 of file GodwarsActivity.java.
{
        GodwarsActivity activity = new GodwarsActivity(player);
        activity.add(player);
        activity.update();
        return activity;
    }
References GodwarsActivity(), and player.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity(), and com.runehive.content.teleport.TeleportHandler.special().
finish()
void com.runehive.content.activity.impl.godwars.GodwarsActivity.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 82 of file GodwarsActivity.java.
{
        remove(player);
    }
References player.
Referenced by onRegionChange().
getListener()
Optional< GodwarsListener > com.runehive.content.activity.impl.godwars.GodwarsActivity.getListener () protected
Gets an Optional of the ActivityListener for this activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 191 of file GodwarsActivity.java.
{
        return Optional.of(listener);
    }
References listener.
getType()
ActivityType com.runehive.content.activity.impl.godwars.GodwarsActivity.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 186 of file GodwarsActivity.java.
{
        return ActivityType.GODWARS;
    }
References com.runehive.content.activity.ActivityType.GODWARS.
increment()
void com.runehive.content.activity.impl.godwars.GodwarsActivity.increment (int index) package
Increments the godwars kill count and updates the interface.
Definition at line 54 of file GodwarsActivity.java.
{
        killCount[index]++;
        update();
    }
References killCount, and update().
onDeath()
void com.runehive.content.activity.impl.godwars.GodwarsActivity.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 177 of file GodwarsActivity.java.
{
            if (mob.isPlayer()) {
                cleanup();
                mob.move(Config.DEFAULT_POSITION);
                mob.animate(Animation.RESET, true);
                mob.graphic(Graphic.RESET, true);
            }
        }
References com.runehive.game.world.entity.mob.Mob.animate(), cleanup(), com.runehive.Config.DEFAULT_POSITION, com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.Animation.RESET, and com.runehive.game.Graphic.RESET.
onRegionChange()
void com.runehive.content.activity.impl.godwars.GodwarsActivity.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 166 of file GodwarsActivity.java.
{
        if (!Area.inGodwars(player)) {
            finish();
        }
    }
References finish(), com.runehive.game.world.position.Area.inGodwars(), and player.
start()
void com.runehive.content.activity.impl.godwars.GodwarsActivity.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 77 of file GodwarsActivity.java.
{
        pause();
    }
References com.runehive.content.activity.Activity.pause().
update()
void com.runehive.content.activity.impl.godwars.GodwarsActivity.update ()
The update method.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 92 of file GodwarsActivity.java.
{
        String armadyl = "Armadyl kills: <col=ffffff>" + killCount[ARMADYL];
        String bandos = "Bandos kills: <col=ffffff>" + killCount[BANDOS];
        String saradomin = "Saradomin kills: <col=ffffff>" + killCount[SARADOMIN];
        String zamorak = "Zamorak kills: <col=ffffff>" + killCount[ZAMORAK];
        ActivityPanel.update(player, -1, "God Wars", "", "", armadyl, bandos, saradomin, zamorak);
    }
References ARMADYL, BANDOS, killCount, player, SARADOMIN, com.runehive.content.activity.panel.ActivityPanel.update(), and ZAMORAK.
Referenced by increment().
Member Data Documentation
ARMADYL
final int com.runehive.content.activity.impl.godwars.GodwarsActivity.ARMADYL = 0 static package
The indexes for the god wars kill count.
Definition at line 28 of file GodwarsActivity.java.
Referenced by clickObject(), and update().
BANDOS
final int com.runehive.content.activity.impl.godwars.GodwarsActivity.BANDOS = 1 static package
Definition at line 28 of file GodwarsActivity.java.
Referenced by clickObject(), and update().
killCount
int [] com.runehive.content.activity.impl.godwars.GodwarsActivity.killCount = new int[4] private
The kill count array.
Definition at line 34 of file GodwarsActivity.java.
Referenced by canEnter(), increment(), and update().
listener
final GodwarsListener com.runehive.content.activity.impl.godwars.GodwarsActivity.listener = new GodwarsListener(this) private
The combat listener for the god wars activity.
Definition at line 37 of file GodwarsActivity.java.
Referenced by getListener().
player
final Player com.runehive.content.activity.impl.godwars.GodwarsActivity.player private
The player instance of this activity.
Definition at line 31 of file GodwarsActivity.java.
Referenced by canEnter(), canTeleport(), cleanup(), clickObject(), create(), finish(), GodwarsActivity(), onRegionChange(), and update().
SARADOMIN
final int com.runehive.content.activity.impl.godwars.GodwarsActivity.SARADOMIN = 2 static package
Definition at line 28 of file GodwarsActivity.java.
Referenced by clickObject(), and update().
ZAMORAK
final int com.runehive.content.activity.impl.godwars.GodwarsActivity.ZAMORAK = 3 static package
Definition at line 28 of file GodwarsActivity.java.
Referenced by clickObject(), and update().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/godwars/GodwarsActivity.java