RuneHive-Game: com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition Class Reference
com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition Class Reference
Public Member Functions
RangedAmmunition[] getAllowed ()
int getSlot ()
RangedWeaponType getType ()
boolean isValid (RangedAmmunition ammunition)
RangedWeaponDefinition (RangedWeaponType type, RangedAmmunition... allowed)
String toString ()
Private Attributes
final RangedAmmunition[] allowed
final RangedWeaponType type
Detailed Description
Definition at line 5 of file RangedWeaponDefinition.java.
Constructor & Destructor Documentation
RangedWeaponDefinition()
com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.RangedWeaponDefinition (RangedWeaponType type, RangedAmmunition... allowed)
Definition at line 10 of file RangedWeaponDefinition.java.
{
        this.type = type;
        this.allowed = allowed;
    }
References allowed, and type.
Member Function Documentation
getAllowed()
RangedAmmunition[] com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getAllowed ()
Definition at line 33 of file RangedWeaponDefinition.java.
{
        return allowed;
    }
References allowed.
getSlot()
int com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getSlot ()
Definition at line 15 of file RangedWeaponDefinition.java.
{
        return type.slot;
    }
References type.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.hit(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start().
getType()
RangedWeaponType com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.getType ()
Definition at line 19 of file RangedWeaponDefinition.java.
{
        return type;
    }
References type.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack().
isValid()
boolean com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.isValid (RangedAmmunition ammunition)
Definition at line 23 of file RangedWeaponDefinition.java.
{
        if (ammunition == null) return false;
        for (RangedAmmunition ammo : allowed) {
            if (ammo == ammunition) {
                return true;
            }
        }
        return false;
    }
References allowed.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack().
toString()
String com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.toString ()
Definition at line 38 of file RangedWeaponDefinition.java.
{
        return "RangedWeaponDefinition{" +
                "type=" + type +
                ", allowed=" + Arrays.toString(allowed) +
                '}';
    }
References allowed, and type.
Member Data Documentation
allowed
final RangedAmmunition [] com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.allowed private
Definition at line 8 of file RangedWeaponDefinition.java.
Referenced by getAllowed(), isValid(), RangedWeaponDefinition(), and toString().
type
final RangedWeaponType com.runehive.game.world.entity.combat.ranged.RangedWeaponDefinition.type private
Definition at line 7 of file RangedWeaponDefinition.java.
Referenced by getSlot(), getType(), RangedWeaponDefinition(), and toString().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/ranged/RangedWeaponDefinition.java