RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast Class Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast Class Reference
Classes
class CrushMelee
class MagicAttack
Public Member Functions
void block (Mob attacker, Npc defender, Hit hit, CombatType combatType)
boolean canAttack (Npc attacker, Mob defender)
CorporealBeast ()
void finishOutgoing (Npc attacker, Mob defender)
int getAttackDelay (Npc attacker, Mob defender, FightType fightType)
int modifyAccuracy (Npc attacker, Mob defender, int roll)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy
void attack (Npc attacker, Mob defender, Hit hit)
boolean canOtherAttack (Mob attacker, Npc defender)
void finishIncoming (Mob attacker, Npc defender)
Animation getAttackAnimation (Npc attacker, Mob defender)
int getAttackDistance (Npc attacker, FightType fightType)
CombatType getCombatType ()
CombatHit[] getHits (Npc attacker, Mob defender)
void hit (Npc attacker, Mob defender, Hit hit)
void hitsplat (Npc attacker, Mob defender, Hit hit)
int modifyAggressive (Npc attacker, Mob defender, int roll)
int modifyAggressiveBonus (Npc attacker, Mob defender, int bonus)
int modifyAttackLevel (Npc attacker, Mob defender, int level)
int modifyDamage (Npc attacker, Mob defender, int damage)
int modifyDefenceLevel (Mob attacker, Npc defender, int level)
int modifyDefensive (Mob attacker, Npc defender, int roll)
int modifyDefensiveBonus (Mob attacker, Npc defender, int bonus)
int modifyMagicLevel (Npc attacker, Mob defender, int level)
int modifyOffensiveBonus (Npc attacker, Mob defender, int bonus)
int modifyRangedLevel (Npc attacker, Mob defender, int level)
int modifyStrengthLevel (Npc attacker, Mob defender, int level)
void onDamage (Npc defender, Hit hit)
void onDeath (Mob attacker, Npc defender, Hit hit)
void onKill (Npc attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, Npc defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (Npc attacker, Mob defender, Hit[] hits)
boolean withinDistance (Npc attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Attributes
static final int weaponsAllowed []
Static Private Attributes
static final MagicAttack MAGIC = new MagicAttack()
static final CrushMelee MELEE = new CrushMelee()
static final CombatStrategy< Npc >[] STRATEGIES = createStrategyArray(MAGIC, MELEE)
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Protected Attributes inherited from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy
CombatStrategy< Npc > currentStrategy
Detailed Description
Author
Daniel
Definition at line 22 of file CorporealBeast.java.
Constructor & Destructor Documentation
CorporealBeast()
com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.CorporealBeast ()
Definition at line 32 of file CorporealBeast.java.
{
        currentStrategy = randomStrategy(STRATEGIES);
    }
References com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.currentStrategy, and STRATEGIES.
Member Function Documentation
block()
void com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.block (Mob attacker, Npc defender, Hit hit, CombatType combatType)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 48 of file CorporealBeast.java.
{
            //TODO: 1/8 chance that the dark core will spawn
        defender.getCombat().attack(attacker);
        super.block(attacker, defender, hit, combatType);
    }
References com.runehive.game.world.entity.mob.npc.Npc.getCombat(), and com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.hit().
canAttack()
boolean com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.canAttack (Npc attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 37 of file CorporealBeast.java.
{
        return currentStrategy.canAttack(attacker, defender);
    }
References com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.currentStrategy.
finishOutgoing()
void com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.finishOutgoing (Npc attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 42 of file CorporealBeast.java.
{
        currentStrategy.finishOutgoing(attacker, defender);
        currentStrategy = randomStrategy(STRATEGIES);
    }
References com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.currentStrategy, and STRATEGIES.
getAttackDelay()
int com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.getAttackDelay (Npc attacker, Mob defender, FightType fightType)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 55 of file CorporealBeast.java.
{
        return attacker.definition.getAttackDelay();
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, and com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackDelay().
modifyAccuracy()
int com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.modifyAccuracy (Npc attacker, Mob defender, int roll)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 60 of file CorporealBeast.java.
{
        return (int) (roll * 5.05);
    }
Member Data Documentation
MAGIC
final MagicAttack com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.MAGIC = new MagicAttack() static private
Definition at line 23 of file CorporealBeast.java.
MELEE
final CrushMelee com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.MELEE = new CrushMelee() static private
Definition at line 24 of file CorporealBeast.java.
STRATEGIES
final CombatStrategy<Npc> [] com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.STRATEGIES = createStrategyArray(MAGIC, MELEE) static private
Definition at line 25 of file CorporealBeast.java.
Referenced by CorporealBeast(), and finishOutgoing().
weaponsAllowed
final int com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.weaponsAllowed[] static
Initial value:
= {Items.BRONZE_SPEAR, Items.IRON_SPEAR, Items.STEEL_SPEAR, Items.BLACK_SPEAR,
            Items.MITHRIL_SPEAR, Items.ADAMANT_SPEAR, Items.RUNE_SPEAR, Items.DRAGON_SPEAR,
            Items.GUTHANS_WARSPEAR, Items.ZAMORAKIAN_SPEAR, Items.ZAMORAKIAN_HASTA, 26219, 27246}
Definition at line 26 of file CorporealBeast.java.
                                                {Items.BRONZE_SPEAR, Items.IRON_SPEAR, Items.STEEL_SPEAR, Items.BLACK_SPEAR,
            Items.MITHRIL_SPEAR, Items.ADAMANT_SPEAR, Items.RUNE_SPEAR, Items.DRAGON_SPEAR,
            Items.GUTHANS_WARSPEAR, Items.ZAMORAKIAN_SPEAR, Items.ZAMORAKIAN_HASTA, 26219, 27246};
Referenced by com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/CorporealBeast.java