RuneHive-Game: com.runehive.content.skill.impl.agility.Agility Class Reference
com.runehive.content.skill.impl.agility.Agility Class Reference
Created by Daniel on 2017-11-02.
Static Public Member Functions
static boolean clickButton (Player player, int button)
static void declare ()
static void main (String[] args)
Static Public Attributes
static final int ARDOUGNE_FLAGS = 0b0111_1111
static final int BARBARIAN_FLAGS = 0b0111_1111
static final int GNOME_FLAGS = 0b0111_1111
static final HashMap< Position, Obstacle > obstacles = new HashMap<>()
static final int SEERS_FLAGS = 0b0011_1111
static final int WILDERNESS_FLAGS = 0b0001_1111
Static Private Attributes
static final double TICKET_EXPERIENCE = 50 * Config.AGILITY_MODIFICATION
Detailed Description
Created by Daniel on 2017-11-02.
Definition at line 21 of file Agility.java.
Member Function Documentation
clickButton()
boolean com.runehive.content.skill.impl.agility.Agility.clickButton (Player player, int button) static
Definition at line 48 of file Agility.java.
{
        int amount = -1;
        Consumer<Player> onClick = null;
        switch (button) {
            case 8387:
                amount = 1;
                onClick = p -> p.skills.addExperience(Skill.AGILITY, TICKET_EXPERIENCE * 1);
                break;
            case 8389:
                amount = 10;
                onClick = p -> p.skills.addExperience(Skill.AGILITY, TICKET_EXPERIENCE * 10);
                break;
            case 8390:
                amount = 25;
                onClick = p -> p.skills.addExperience(Skill.AGILITY, TICKET_EXPERIENCE * 25);
                break;
            case 8391:
                amount = 100;
                onClick = p -> p.skills.addExperience(Skill.AGILITY, TICKET_EXPERIENCE * 100);
                break;
            case 8392:
                amount = 1_000;
                onClick = p -> p.skills.addExperience(Skill.AGILITY, TICKET_EXPERIENCE * 1000);
                break;
            case 8382:
                amount = 3;
                onClick = p -> p.inventory.addOrDrop(new Item(3049, 1));
                break;
            case 8383:
                amount = 10;
                onClick = p -> p.inventory.addOrDrop(new Item(3051, 1));
                break;
            case 8381:
                amount = 800;
                onClick = p -> p.inventory.addOrDrop(new Item(2997, 1));
                break;
        }
        if (amount > -1) {
            if (player.inventory.contains(2996, amount)) {
                player.inventory.remove(2996, amount);
                onClick.accept(player);
                player.interfaceManager.close();
                return true;
            } else {
                player.message("You do not have enough agility tickets to purchase that.");
                return true;
            }
        }
        return false;
    }
References com.runehive.game.world.entity.skill.Skill.AGILITY, com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.remove(), and TICKET_EXPERIENCE.
declare()
void com.runehive.content.skill.impl.agility.Agility.declare () static
Definition at line 29 of file Agility.java.
{
        try {
            Obstacle[] loaded = new Gson().fromJson(new BufferedReader(new FileReader("./data/content/skills/agility.json")), Obstacle[].class);
            for (Obstacle obstacle : loaded) {
                if (obstacle.getObjectPosition() == null) {
                    obstacle.setObjectPosition(obstacle.getStart());
                }
                if (obstacle.getType() == null) {
                    System.out.println(obstacle + " No object type found. FIX MUST FIX");
                }
                obstacles.put(obstacle.getObjectPosition(), obstacle);
            }
        } catch (JsonSyntaxException | JsonIOException | FileNotFoundException e) {
            e.printStackTrace();
        }
    }
References obstacles.
Referenced by com.runehive.content.skill.SkillRepository.load().
main()
void com.runehive.content.skill.impl.agility.Agility.main (String[] args) static
Definition at line 100 of file Agility.java.
{
        // Write the obstacles so we don't have to deal with a messy wall
        // of code.
//       obstacles.put(new Location(2551, 3554), new Obstacle.ObstacleBuilder(ObstacleType.ROPE_SWING, new ObeliskData(2551, 3554), new ObeliskData(2551, 3549))
//       .setExperience(22f)
//       .setLevel(35)
//       .setOrdinal(0)
//       .setNext(new Obstacle.ObstacleBuilder(ObstacleType.ROPE_SWING, new Location(2551, 3554), new ObeliskData(2551, 3549)).build())
//       .build());
        try (FileWriter writer = new FileWriter(new File("./data/def/skills/agility1.json"))) {
            Gson builder = new GsonBuilder().setPrettyPrinting().create();
            writer.write(builder.toJson(obstacles.values()).replaceAll("\\{\n      \"x\"", "\\{ \"x\"").replaceAll(",\n      \"y\"", ", \"y\"").replaceAll(",\n      \"z\"", ", \"z\"").replaceAll("\n    \\},", " \\},"));
        } catch (Exception e) {
        }
    }
References obstacles.
Member Data Documentation
ARDOUGNE_FLAGS
final int com.runehive.content.skill.impl.agility.Agility.ARDOUGNE_FLAGS = 0b0111_1111 static
Definition at line 26 of file Agility.java.
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
BARBARIAN_FLAGS
final int com.runehive.content.skill.impl.agility.Agility.BARBARIAN_FLAGS = 0b0111_1111 static
Definition at line 23 of file Agility.java.
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
GNOME_FLAGS
final int com.runehive.content.skill.impl.agility.Agility.GNOME_FLAGS = 0b0111_1111 static
Definition at line 22 of file Agility.java.
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
obstacles
final HashMap<Position, Obstacle> com.runehive.content.skill.impl.agility.Agility.obstacles = new HashMap<>() static
Definition at line 27 of file Agility.java.
Referenced by declare(), and main().
SEERS_FLAGS
final int com.runehive.content.skill.impl.agility.Agility.SEERS_FLAGS = 0b0011_1111 static
Definition at line 25 of file Agility.java.
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
TICKET_EXPERIENCE
final double com.runehive.content.skill.impl.agility.Agility.TICKET_EXPERIENCE = 50 * Config.AGILITY_MODIFICATION static private
Definition at line 46 of file Agility.java.
Referenced by clickButton().
WILDERNESS_FLAGS
final int com.runehive.content.skill.impl.agility.Agility.WILDERNESS_FLAGS = 0b0001_1111 static
Definition at line 24 of file Agility.java.
Referenced by com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/agility/Agility.java