RuneHive-Game: com.runehive.content.skill.impl.farming.patches.HarvestablePatch Class Reference
com.runehive.content.skill.impl.farming.patches.HarvestablePatch Class Reference abstract
A WaterablePatch that can harvest produce.
Public Member Functions
boolean clickObject (int opcode)
void fromJson (JsonObject object)
JsonObject toJson ()
Public Member Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
int getConfig ()
boolean isComposted ()
boolean isDead ()
boolean isDiseased ()
boolean isEmpty ()
boolean isGrowing ()
boolean isNormal ()
boolean isWatered ()
boolean itemOnObject (Item item, int index)
boolean needsWeeding ()
abstract Plant plantForSeed (int seedId)
void setDead ()
void setDiseased ()
void setEmpty ()
void setNormal ()
void setWatered ()
void tick ()
boolean within (Position position)
Protected Member Functions
abstract int animation ()
abstract int getMaxAmount ()
abstract int getMinAmount ()
void resetPatch ()
Protected Member Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
void onGrowth ()
Package Functions
HarvestablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new HarvestablePatch object.
Package Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
FarmingPatch (Player player, FarmingZone zone, Interactable[] boundaries)
Private Member Functions
Action< Player > createHarvestAction (Player player, int min, int max)
Creates the harvesting action.
boolean harvest (int min, int max)
Harvests produce in this patch if the requirements are met.
Private Attributes
int harvest
The harvest amount.
Additional Inherited Members
Protected Attributes inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
CompostType compost
boolean fullyGrown
int growth
Plant plant
final Player player
FarmingStage stage = FarmingStage.FULL_WEEDS
FarmingState state = FarmingState.NORMAL
final Stopwatch timer = Stopwatch.start()
final FarmingZone zone
Detailed Description
A WaterablePatch that can harvest produce.
Author
Michael | Chex
Definition at line 20 of file HarvestablePatch.java.
Constructor & Destructor Documentation
HarvestablePatch()
com.runehive.content.skill.impl.farming.patches.HarvestablePatch.HarvestablePatch (Player player, FarmingZone zone, Interactable[] boundaries) package
Constructs a new HarvestablePatch object.
Parameters
player the player that owns this patch
zone the zone this patch belongs in
boundaries the boundaries of this patch
Definition at line 32 of file HarvestablePatch.java.
{
        super(player, zone, boundaries);
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.boundaries, com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, and com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone.
Member Function Documentation
animation()
abstract int com.runehive.content.skill.impl.farming.patches.HarvestablePatch.animation () abstract protected
Returns
the harvesting animation
Reimplemented in com.runehive.content.skill.impl.farming.patches.impl.AllotmentPatch, com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch, and com.runehive.content.skill.impl.farming.patches.impl.HerbPatch.
Referenced by createHarvestAction().
clickObject()
boolean com.runehive.content.skill.impl.farming.patches.HarvestablePatch.clickObject (int opcode)
Reimplemented from com.runehive.content.skill.impl.farming.patches.FarmingPatch.
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch.
Definition at line 145 of file HarvestablePatch.java.
{
        if (opcode == 1 && !isDead() && fullyGrown) {
            return harvest(getMinAmount(), getMaxAmount());
        }
        return super.clickObject(opcode);
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.fullyGrown, getMaxAmount(), getMinAmount(), harvest, and com.runehive.content.skill.impl.farming.patches.FarmingPatch.isDead().
createHarvestAction()
Action< Player > com.runehive.content.skill.impl.farming.patches.HarvestablePatch.createHarvestAction (Player player, int min, int max) private
Creates the harvesting action.
Parameters
player the player harvesting produce
min the minimum amount of produce to harvest
max the maximum amount of produce to harvest
Returns
a new Action specifically designed to harvest produce
Definition at line 68 of file HarvestablePatch.java.
{
        return new Action<Player>(player, 2) {
            @Override
            protected boolean canSchedule() {
                return !player.locking.locked() && player.inventory.getFreeSlots() > 0;
            }
            @Override
            protected void onSchedule() {
                player.locking.lock(2);
                player.animate(animation());
                player.message("You begin to harvest the crop for " + plant.getProductType() + ".");
            }
            @Override
            public void execute() {
                if (player.inventory.getFreeSlots() <= 0) {
                    cancel();
                    return;
                }
                if (harvest == 0) {
                    harvest = RandomUtils.inclusive(min, max);
                    if (player.equipment.contains(FarmingConstants.MAGIC_SECATEURS)) {
                        harvest = harvest * 13 / 12;
                    }
                    if (SkillCape.isEquipped(player, SkillCape.FARMING)) {
                        harvest += harvest * 13 / 12;
                    }
                    harvest++;
                }
                if (harvest == 1) {
                    resetPatch();
                    cancel();
                    return;
                }
                harvest--;
                if (harvest % 2 == 0)
                    player.animate(animation());
                player.inventory.add(plant.getHarvestId(), 1);
                player.skills.addExperience(Skill.FARMING, plant.getHarvestXp() * Config.FARMING_MODIFICATION);
            }
            @Override
            public void onCancel(boolean logout) {
                player.resetAnimation();
                zone.sendPatchConfigs(player);
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
            @Override
            public String getName() {
                return "Farming Harvest";
            }
        };
    }
References animation(), com.runehive.content.skillcape.SkillCape.FARMING, com.runehive.game.world.entity.skill.Skill.FARMING, com.runehive.Config.FARMING_MODIFICATION, harvest, com.runehive.util.RandomUtils.inclusive(), com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.content.skill.impl.farming.FarmingConstants.MAGIC_SECATEURS, com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, com.runehive.content.skill.impl.farming.patches.FarmingPatch.plant, com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, resetPatch(), and com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone.
Referenced by harvest().
fromJson()
void com.runehive.content.skill.impl.farming.patches.HarvestablePatch.fromJson (JsonObject object)
Reimplemented from com.runehive.content.skill.impl.farming.patches.FarmingPatch.
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch.
Definition at line 166 of file HarvestablePatch.java.
{
        harvest = object.get("harvest").getAsInt();
        super.fromJson(object);
    }
References harvest.
getMaxAmount()
abstract int com.runehive.content.skill.impl.farming.patches.HarvestablePatch.getMaxAmount () abstract protected
Returns
the maximum amount of produce to harvest
Reimplemented in com.runehive.content.skill.impl.farming.patches.impl.AllotmentPatch, com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch, and com.runehive.content.skill.impl.farming.patches.impl.HerbPatch.
Referenced by clickObject().
getMinAmount()
abstract int com.runehive.content.skill.impl.farming.patches.HarvestablePatch.getMinAmount () abstract protected
Returns
the minimum amount of produce to harvest
Reimplemented in com.runehive.content.skill.impl.farming.patches.impl.AllotmentPatch, com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch, and com.runehive.content.skill.impl.farming.patches.impl.HerbPatch.
Referenced by clickObject().
harvest()
boolean com.runehive.content.skill.impl.farming.patches.HarvestablePatch.harvest (int min, int max) private
Harvests produce in this patch if the requirements are met.
Parameters
min the minimum amount of produce to harvest
max the maximum amount of produce to harvest
Returns
true if this patch has successfully begun to harvest produce
Definition at line 44 of file HarvestablePatch.java.
{
        if (plant == null) {
            return false;
        }
        if (!player.inventory.contains(FarmingConstants.SECATEURS) && !player.inventory.contains(FarmingConstants.MAGIC_SECATEURS) &&
        !player.equipment.contains(FarmingConstants.MAGIC_SECATEURS)) {
            player.dialogueFactory.sendStatement("You need secateurs to harvest here.").execute();
            return true;
        }
        min = min * compost.produceIncrease() / 100;
        player.action.execute(createHarvestAction(player, min, max));
        return true;
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.compost, createHarvestAction(), com.runehive.content.skill.impl.farming.FarmingConstants.MAGIC_SECATEURS, com.runehive.content.skill.impl.farming.patches.FarmingPatch.plant, com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, and com.runehive.content.skill.impl.farming.FarmingConstants.SECATEURS.
resetPatch()
void com.runehive.content.skill.impl.farming.patches.HarvestablePatch.resetPatch () protected
Reimplemented from com.runehive.content.skill.impl.farming.patches.FarmingPatch.
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch.
Definition at line 153 of file HarvestablePatch.java.
{
        super.resetPatch();
        harvest = 0;
    }
References harvest.
Referenced by createHarvestAction().
toJson()
JsonObject com.runehive.content.skill.impl.farming.patches.HarvestablePatch.toJson ()
Reimplemented from com.runehive.content.skill.impl.farming.patches.FarmingPatch.
Reimplemented in com.runehive.content.skill.impl.farming.patches.DiseasablePatch.
Definition at line 159 of file HarvestablePatch.java.
{
        JsonObject object = super.toJson();
        object.addProperty("harvest", harvest);
        return object;
    }
References harvest.
Member Data Documentation
harvest
int com.runehive.content.skill.impl.farming.patches.HarvestablePatch.harvest private
The harvest amount.
Definition at line 23 of file HarvestablePatch.java.
Referenced by clickObject(), createHarvestAction(), fromJson(), resetPatch(), and toJson().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/farming/patches/HarvestablePatch.java