RuneHive-Game: com.runehive.game.world.pathfinding.TraversalMap Class Reference
com.runehive.game.world.pathfinding.TraversalMap Class Reference
Contains traversal data for a set of regions.
Static Public Member Functions
static void block (Region region, int height, int localX, int localY)
Marks the specified set of coordinates blocked, unable to be passed through.
static boolean blockedEast (Position position)
static boolean blockedNorth (Position position)
static boolean blockedSouth (Position position)
static boolean blockedWest (Position position)
static int getFlags (int x, int y, int height)
static int getFlags (Position position)
static Position getRandomNonDiagonal (Position from)
static Position getRandomTraversableTile (Position southWest, int width, int length)
static List< Position > getTraversableTiles (Position southWest, int width, int length)
Returns a List of positions that are traversable from the specified position.
static boolean isTraversable (Position from, Direction direction, boolean impenetrable)
Tests whether or not a specified position is traversable in the specified direction.
static boolean isTraversable (Position from, Direction direction, int size)
Tests whether or not a specified position is traversable in the specified direction.
static void markBridge (Region region, int height, int x, int y)
Marks the specified coordinates a bridge.
static void markObject (Region region, GameObject object, boolean add, boolean list)
Marks a GameObject with the specified attributes on the specified Position to the TraversalMap.
static void markOccupant (Region region, int height, int x, int y, int width, int length, boolean impenetrable, boolean add)
Marks the specified coordinates occupied by some object.
static void set (Region region, int height, int x, int y, int flag)
Sets a flag on the specified position.
Private Member Functions
TraversalMap ()
Static Private Member Functions
static boolean isInactive (int height, int x, int y, int flag)
Checks whether or not the specified flag is not active on the specified position.
static boolean isTraversableEast (int height, int x, int y)
Tests if the specified position can be traversed east.
static boolean isTraversableEast (int height, int x, int y, boolean impenetrable)
Tests if the specified position can be traversed east.
static boolean isTraversableEast (int height, int x, int y, int size)
Tests if the specified position can be traversed east.
static boolean isTraversableNorth (int height, int x, int y)
Tests if the specified position can be traversed north.
static boolean isTraversableNorth (int height, int x, int y, boolean impenetrable)
Tests if the specified position can be traversed north.
static boolean isTraversableNorth (int height, int x, int y, int size)
Tests if the specified position can be traversed north.
static boolean isTraversableNorthEast (int height, int x, int y)
Tests if the specified position can be traversed north east.
static boolean isTraversableNorthEast (int height, int x, int y, boolean impenetrable)
Tests if the specified position can be traversed north east.
static boolean isTraversableNorthEast (int height, int x, int y, int size)
Tests if the specified position can be traversed north east.
static boolean isTraversableNorthWest (int height, int x, int y)
Tests if the specified position can be traversed north west.
static boolean isTraversableNorthWest (int height, int x, int y, boolean impenetrable)
Tests if the specified position can be traversed north west.
static boolean isTraversableNorthWest (int height, int x, int y, int size)
Tests if the specified position can be traversed north west.
static boolean isTraversableSouth (int height, int x, int y)
Tests if the specified position can be traversed south.
static boolean isTraversableSouth (int height, int x, int y, boolean impenetrable)
Tests if the specified position can be traversed south.
static boolean isTraversableSouth (int height, int x, int y, int size)
Tests if the specified position can be traversed south.
static boolean isTraversableSouthEast (int height, int x, int y)
Tests if the specified position can be traversed south east.
static boolean isTraversableSouthEast (int height, int x, int y, boolean impenetrable)
Tests if the specified position can be traversed south east.
static boolean isTraversableSouthEast (int height, int x, int y, int size)
Tests if the specified position can be traversed south east.
static boolean isTraversableSouthWest (int height, int x, int y)
Tests if the specified position can be traversed south west.
static boolean isTraversableSouthWest (int height, int x, int y, boolean impenetrable)
Tests if the specified position can be traversed south west.
static boolean isTraversableSouthWest (int height, int x, int y, int size)
Tests if the specified position can be traversed south west.
static boolean isTraversableWest (int height, int x, int y)
Tests if the specified position can be traversed west.
static boolean isTraversableWest (int height, int x, int y, boolean impenetrable)
Tests if the specified position can be traversed west.
static boolean isTraversableWest (int height, int x, int y, int size)
Tests if the specified position can be traversed west.
static void markWall (Region reg, ObjectDirection orientation, int height, int x, int y, ObjectType type, boolean impenetrable)
Informs the region of an existing wall.
static void unmarkWall (Region reg, ObjectDirection orientation, int height, int x, int y, ObjectType type, boolean impenetrable)
Informs the region of an existing wall being removed.
static void unset (Region region, int height, int x, int y, int flag)
Unsets the specified flag from the specified position.
Detailed Description
Contains traversal data for a set of regions.
Author
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Definition at line 24 of file TraversalMap.java.
Constructor & Destructor Documentation
TraversalMap()
com.runehive.game.world.pathfinding.TraversalMap.TraversalMap () private
Definition at line 26 of file TraversalMap.java.
{}
Member Function Documentation
block()
void com.runehive.game.world.pathfinding.TraversalMap.block (Region region, int height, int localX, int localY) static
Marks the specified set of coordinates blocked, unable to be passed through.
Parameters
height The height.
localX The x coordinate.
localY The y coordinate.
Definition at line 352 of file TraversalMap.java.
{
        region.setFlags(height, localX, localY, TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED.
Referenced by com.runehive.fs.cache.decoder.RegionDecoder.parseTerrain().
blockedEast()
boolean com.runehive.game.world.pathfinding.TraversalMap.blockedEast (Position position) static
Definition at line 1027 of file TraversalMap.java.
{
        return !isTraversableEast(position.getHeight(), position.getX(), position.getY(), false);
    }
References isTraversableEast().
Referenced by com.runehive.game.world.region.Region.reachable().
blockedNorth()
boolean com.runehive.game.world.pathfinding.TraversalMap.blockedNorth (Position position) static
Definition at line 1023 of file TraversalMap.java.
{
        return !isTraversableNorth(position.getHeight(), position.getX(), position.getY(), false);
    }
References isTraversableNorth().
Referenced by com.runehive.game.world.region.Region.reachable().
blockedSouth()
boolean com.runehive.game.world.pathfinding.TraversalMap.blockedSouth (Position position) static
Definition at line 1031 of file TraversalMap.java.
{
        return !isTraversableSouth(position.getHeight(), position.getX(), position.getY(), false);
    }
References isTraversableSouth().
Referenced by com.runehive.game.world.region.Region.reachable().
blockedWest()
boolean com.runehive.game.world.pathfinding.TraversalMap.blockedWest (Position position) static
Definition at line 1035 of file TraversalMap.java.
{
        return !isTraversableWest(position.getHeight(), position.getX(), position.getY(), false);
    }
References isTraversableWest().
Referenced by com.runehive.game.world.region.Region.reachable().
getFlags() [1/2]
int com.runehive.game.world.pathfinding.TraversalMap.getFlags (int x, int y, int height) static
Definition at line 1012 of file TraversalMap.java.
{
        int localX = x & 0x3F;
        int localY = y & 0x3F;
        Region region = World.getRegions().getRegion(x, y);
        return region.getFlags(height, localX, localY);
    }
References com.runehive.game.world.region.RegionManager.getRegion(), and com.runehive.game.world.World.getRegions().
Referenced by getFlags(), and com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.withinDistance().
getFlags() [2/2]
int com.runehive.game.world.pathfinding.TraversalMap.getFlags (Position position) static
Definition at line 1019 of file TraversalMap.java.
{
        return getFlags(position.getX(), position.getY(), position.getHeight());
    }
References getFlags().
getRandomNonDiagonal()
Position com.runehive.game.world.pathfinding.TraversalMap.getRandomNonDiagonal (Position from) static
Definition at line 991 of file TraversalMap.java.
{
        List<Position> positions = new LinkedList<>();
        if (isTraversableNorth(from.getHeight(), from.getX(), from.getY()))
            positions.add(from.north());
        if (isTraversableSouth(from.getHeight(), from.getX(), from.getY()))
            positions.add(from.south());
        if (isTraversableEast(from.getHeight(), from.getX(), from.getY()))
            positions.add(from.east());
        if (isTraversableWest(from.getHeight(), from.getX(), from.getY()))
            positions.add(from.west());
        if (positions.isEmpty())
            return null;
        return RandomUtils.random(positions);
    }
References com.runehive.game.world.position.Position.east(), com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), isTraversableEast(), isTraversableNorth(), isTraversableSouth(), isTraversableWest(), com.runehive.game.world.position.Position.north(), com.runehive.util.RandomUtils.random(), com.runehive.game.world.position.Position.south(), and com.runehive.game.world.position.Position.west().
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.start().
getRandomTraversableTile()
Position com.runehive.game.world.pathfinding.TraversalMap.getRandomTraversableTile (Position southWest, int width, int length) static
Definition at line 955 of file TraversalMap.java.
{
        List<Position> positions = new LinkedList<>();
        for (int y = 0; y < length; y++) {
            for (int x = 0; x < width; x++) {
                Position from = southWest.transform(x, y);
                if (isTraversableNorth(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.north());
                if (isTraversableSouth(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.south());
                if (isTraversableEast(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.east());
                if (isTraversableWest(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.west());
                if (isTraversableNorthEast(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.northEast());
                if (isTraversableNorthWest(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.northWest());
                if (isTraversableSouthEast(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.southEast());
                if (isTraversableSouthWest(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.southWest());
            }
        }
        if (positions.isEmpty())
            return null;
        return RandomUtils.random(positions);
    }
References com.runehive.game.world.position.Position.east(), com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), isTraversableEast(), isTraversableNorth(), isTraversableNorthEast(), isTraversableNorthWest(), isTraversableSouth(), isTraversableSouthEast(), isTraversableSouthWest(), isTraversableWest(), com.runehive.game.world.position.Position.north(), com.runehive.game.world.position.Position.northEast(), com.runehive.game.world.position.Position.northWest(), com.runehive.util.RandomUtils.random(), com.runehive.game.world.position.Position.south(), com.runehive.game.world.position.Position.southEast(), com.runehive.game.world.position.Position.southWest(), com.runehive.game.world.position.Position.transform(), and com.runehive.game.world.position.Position.west().
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.finish(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.start().
getTraversableTiles()
List< Position > com.runehive.game.world.pathfinding.TraversalMap.getTraversableTiles (Position southWest, int width, int length) static
Returns a List of positions that are traversable from the specified position.
Parameters
southWest The position moving from.
width The size of the mob attempting to traverse.
length
Returns
A List of positions.
Definition at line 921 of file TraversalMap.java.
{
        List<Position> positions = new LinkedList<>();
        for (int y = 0; y < length; y++) {
            for (int x = 0; x < width; x++) {
                Position from = southWest.transform(x, y);
                if (isTraversableNorth(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.north());
                if (isTraversableSouth(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.south());
                if (isTraversableEast(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.east());
                if (isTraversableWest(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.west());
                if (isTraversableNorthEast(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.northEast());
                if (isTraversableNorthWest(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.northWest());
                if (isTraversableSouthEast(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.southEast());
                if (isTraversableSouthWest(from.getHeight(), from.getX(), from.getY()))
                    positions.add(from.southWest());
            }
        }
        return positions;
    }
References com.runehive.game.world.position.Position.east(), com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), isTraversableEast(), isTraversableNorth(), isTraversableNorthEast(), isTraversableNorthWest(), isTraversableSouth(), isTraversableSouthEast(), isTraversableSouthWest(), isTraversableWest(), com.runehive.game.world.position.Position.north(), com.runehive.game.world.position.Position.northEast(), com.runehive.game.world.position.Position.northWest(), com.runehive.game.world.position.Position.south(), com.runehive.game.world.position.Position.southEast(), com.runehive.game.world.position.Position.southWest(), com.runehive.game.world.position.Position.transform(), and com.runehive.game.world.position.Position.west().
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.spawn(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomSpecial.start().
isInactive()
boolean com.runehive.game.world.pathfinding.TraversalMap.isInactive (int height, int x, int y, int flag) static private
Checks whether or not the specified flag is not active on the specified position.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
flag The flag to check.
Returns
true if the specified flag is not active on the specified position, otherwise false.
Definition at line 823 of file TraversalMap.java.
{
        int localX = x & 0x3F;
        int localY = y & 0x3F;
        Region region = World.getRegions().getRegion(x, y);
        return (region.getFlags(height, localX, localY) & flag) == 0;
    }
References com.runehive.game.world.region.RegionManager.getRegion(), and com.runehive.game.world.World.getRegions().
Referenced by isTraversableEast(), isTraversableNorth(), isTraversableNorthEast(), isTraversableNorthWest(), isTraversableSouth(), isTraversableSouthEast(), isTraversableSouthWest(), and isTraversableWest().
isTraversable() [1/2]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversable (Position from, Direction direction, boolean impenetrable) static
Tests whether or not a specified position is traversable in the specified direction.
Parameters
from The position.
direction The direction to traverse.
impenetrable The condition if impenetrability must be checked.
Returns
true if the direction is traversable otherwise false.
Definition at line 887 of file TraversalMap.java.
{
        switch (direction) {
            case NORTH:
                return isTraversableNorth(from.getHeight(), from.getX(), from.getY(), impenetrable);
            case SOUTH:
                return isTraversableSouth(from.getHeight(), from.getX(), from.getY(), impenetrable);
            case EAST:
                return isTraversableEast(from.getHeight(), from.getX(), from.getY(), impenetrable);
            case WEST:
                return isTraversableWest(from.getHeight(), from.getX(), from.getY(), impenetrable);
            case NORTH_EAST:
                return isTraversableNorthEast(from.getHeight(), from.getX(), from.getY(), impenetrable);
            case NORTH_WEST:
                return isTraversableNorthWest(from.getHeight(), from.getX(), from.getY(), impenetrable);
            case SOUTH_EAST:
                return isTraversableSouthEast(from.getHeight(), from.getX(), from.getY(), impenetrable);
            case SOUTH_WEST:
                return isTraversableSouthWest(from.getHeight(), from.getX(), from.getY(), impenetrable);
            case NONE:
                return true;
            default:
                throw new IllegalArgumentException("direction: " + direction + " is not valid");
        }
    }
References com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), isTraversableEast(), isTraversableNorth(), isTraversableNorthEast(), isTraversableNorthWest(), isTraversableSouth(), isTraversableSouthEast(), isTraversableSouthWest(), and isTraversableWest().
isTraversable() [2/2]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversable (Position from, Direction direction, int size) static
Tests whether or not a specified position is traversable in the specified direction.
Parameters
from The position.
direction The direction to traverse.
size The size of the entity attempting to traverse.
Returns
true if the direction is traversable otherwise false.
Definition at line 852 of file TraversalMap.java.
{
        switch (direction) {
            case NORTH:
                return isTraversableNorth(from.getHeight(), from.getX(), from.getY(), size);
            case SOUTH:
                return isTraversableSouth(from.getHeight(), from.getX(), from.getY(), size);
            case EAST:
                return isTraversableEast(from.getHeight(), from.getX(), from.getY(), size);
            case WEST:
                return isTraversableWest(from.getHeight(), from.getX(), from.getY(), size);
            case NORTH_EAST:
                return isTraversableNorthEast(from.getHeight(), from.getX(), from.getY(), size);
            case NORTH_WEST:
                return isTraversableNorthWest(from.getHeight(), from.getX(), from.getY(), size);
            case SOUTH_EAST:
                return isTraversableSouthEast(from.getHeight(), from.getX(), from.getY(), size);
            case SOUTH_WEST:
                return isTraversableSouthWest(from.getHeight(), from.getX(), from.getY(), size);
            case NONE:
                return false;
            default:
                throw new IllegalArgumentException("direction: " + direction + " is not valid");
        }
    }
References com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), isTraversableEast(), isTraversableNorth(), isTraversableNorthEast(), isTraversableNorthWest(), isTraversableSouth(), isTraversableSouthEast(), isTraversableSouthWest(), and isTraversableWest().
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.canAttack(), com.runehive.content.gambling.GambleManager.canPlayFlowerPokerAtPositon(), com.runehive.util.Utility.findAccessableTile(), com.runehive.util.Utility.fixInsidePosition(), com.runehive.content.activity.impl.magearena.MageArena.getAvailablePosition(), com.runehive.game.world.pathfinding.path.PathFinder.projectileCheck(), com.runehive.game.world.entity.mob.Mob.takeStep(), com.runehive.game.world.pathfinding.path.PathFinder.traversable(), and com.runehive.game.world.pathfinding.path.PathFinder.traversable().
isTraversableEast() [1/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableEast (int height, int x, int y) static private
Tests if the specified position can be traversed east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
true if it is possible to traverse east otherwise false.
Definition at line 524 of file TraversalMap.java.
{
        return isTraversableEast(height, x, y, false);
    }
References isTraversableEast().
isTraversableEast() [2/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableEast (int height, int x, int y, boolean impenetrable) static private
Tests if the specified position can be traversed east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
impenetrable Whether or not this occupation can be traversed.
Returns
true if it is possible to traverse east otherwise false.
Definition at line 538 of file TraversalMap.java.
{
        if (impenetrable) {
            return isInactive(height, x + 1, y, TraversalConstants.IMPENETRABLE_BLOCKED | TraversalConstants.IMPENETRABLE_WALL_WEST);
        }
        return isInactive(height, x + 1, y, TraversalConstants.WALL_WEST | TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_WEST, isInactive(), and com.runehive.game.world.pathfinding.TraversalConstants.WALL_WEST.
isTraversableEast() [3/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableEast (int height, int x, int y, int size) static private
Tests if the specified position can be traversed east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
size The size of the entity attempting to traverse east.
Returns
true if it is possible to traverse east otherwise false
Definition at line 504 of file TraversalMap.java.
{
        for (int offsetX = 0; offsetX < size; offsetX++) {
            for (int offsetY = 0; offsetY < size; offsetY++) {
                if (!isTraversableEast(height, x + offsetX, y + offsetY)) {
                    return false;
                }
            }
        }
        return true;
    }
References isTraversableEast().
Referenced by blockedEast(), getRandomNonDiagonal(), getRandomTraversableTile(), getTraversableTiles(), isTraversable(), isTraversable(), isTraversableEast(), and isTraversableEast().
isTraversableNorth() [1/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorth (int height, int x, int y) static private
Tests if the specified position can be traversed north.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
true if it is possible to traverse north otherwise false.
Definition at line 422 of file TraversalMap.java.
{
        return isTraversableNorth(height, x, y, false);
    }
References isTraversableNorth().
isTraversableNorth() [2/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorth (int height, int x, int y, boolean impenetrable) static private
Tests if the specified position can be traversed north.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
impenetrable Whether or not this occupation can be traversed.
Returns
true if it is possible to traverse north otherwise false.
Definition at line 436 of file TraversalMap.java.
{
        if (impenetrable) {
            return isInactive(height, x, y + 1, TraversalConstants.IMPENETRABLE_BLOCKED | TraversalConstants.IMPENETRABLE_WALL_SOUTH);
        }
        return isInactive(height, x, y + 1, TraversalConstants.WALL_SOUTH | TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH, isInactive(), and com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH.
isTraversableNorth() [3/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorth (int height, int x, int y, int size) static private
Tests if the specified position can be traversed north.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
size The size of the entity attempting to traverse north.
Returns
true if it is possible to traverse north otherwise false
Definition at line 402 of file TraversalMap.java.
{
        for (int offsetX = 0; offsetX < size; offsetX++) {
            for (int offsetY = 0; offsetY < size; offsetY++) {
                if (!isTraversableNorth(height, x + offsetX, y + offsetY)) {
                    return false;
                }
            }
        }
        return true;
    }
References isTraversableNorth().
Referenced by blockedNorth(), getRandomNonDiagonal(), getRandomTraversableTile(), getTraversableTiles(), isTraversable(), isTraversable(), isTraversableNorth(), and isTraversableNorth().
isTraversableNorthEast() [1/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorthEast (int height, int x, int y) static private
Tests if the specified position can be traversed north east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
true if it is possible to traverse north east otherwise false.
Definition at line 626 of file TraversalMap.java.
{
        return isTraversableNorthEast(height, x, y, false);
    }
References isTraversableNorthEast().
isTraversableNorthEast() [2/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorthEast (int height, int x, int y, boolean impenetrable) static private
Tests if the specified position can be traversed north east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
impenetrable Whether or not this occupation can be traversed.
Returns
true if it is possible to traverse north east otherwise false.
Definition at line 640 of file TraversalMap.java.
{
        if (impenetrable) {
            return isInactive(height, x + 1, y + 1, TraversalConstants.IMPENETRABLE_WALL_WEST | TraversalConstants.IMPENETRABLE_WALL_SOUTH | TraversalConstants.IMPENETRABLE_WALL_SOUTH_WEST) && isInactive(height, x + 1, y, TraversalConstants.IMPENETRABLE_WALL_WEST | TraversalConstants.IMPENETRABLE_BLOCKED) && isInactive(height, x, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH | TraversalConstants.IMPENETRABLE_BLOCKED);
        }
        return isInactive(height, x + 1, y + 1, TraversalConstants.WALL_WEST | TraversalConstants.WALL_SOUTH | TraversalConstants.WALL_SOUTH_WEST | TraversalConstants.BLOCKED) && isInactive(height, x + 1, y, TraversalConstants.WALL_WEST | TraversalConstants.BLOCKED) && isInactive(height, x, y + 1, TraversalConstants.WALL_SOUTH | TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_WEST, isInactive(), com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH, com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH_WEST, and com.runehive.game.world.pathfinding.TraversalConstants.WALL_WEST.
isTraversableNorthEast() [3/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorthEast (int height, int x, int y, int size) static private
Tests if the specified position can be traversed north east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
size The size of the entity attempting to traverse north east.
Returns
true if it is possible to traverse north east otherwise false
Definition at line 606 of file TraversalMap.java.
{
        for (int offsetX = 0; offsetX < size; offsetX++) {
            for (int offsetY = 0; offsetY < size; offsetY++) {
                if (!isTraversableNorthEast(height, x + offsetX, y + offsetY)) {
                    return false;
                }
            }
        }
        return true;
    }
References isTraversableNorthEast().
Referenced by getRandomTraversableTile(), getTraversableTiles(), isTraversable(), isTraversable(), isTraversableNorthEast(), and isTraversableNorthEast().
isTraversableNorthWest() [1/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorthWest (int height, int x, int y) static private
Tests if the specified position can be traversed north west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
true if it is possible to traverse north west otherwise false.
Definition at line 677 of file TraversalMap.java.
{
        return isTraversableNorthWest(height, x, y, false);
    }
References isTraversableNorthWest().
isTraversableNorthWest() [2/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorthWest (int height, int x, int y, boolean impenetrable) static private
Tests if the specified position can be traversed north west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
impenetrable Whether or not this occupation can be traversed.
Returns
true if it is possible to traverse north west otherwise false.
Definition at line 691 of file TraversalMap.java.
{
        if (impenetrable) {
            return isInactive(height, x - 1, y + 1, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_WALL_SOUTH | TraversalConstants.IMPENETRABLE_WALL_SOUTH_EAST) && isInactive(height, x - 1, y, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_BLOCKED) && isInactive(height, x, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH | TraversalConstants.IMPENETRABLE_BLOCKED);
        }
        return isInactive(height, x - 1, y + 1, TraversalConstants.WALL_EAST | TraversalConstants.WALL_SOUTH | TraversalConstants.WALL_SOUTH_EAST | TraversalConstants.BLOCKED) && isInactive(height, x - 1, y, TraversalConstants.WALL_EAST | TraversalConstants.BLOCKED) && isInactive(height, x, y + 1, TraversalConstants.WALL_SOUTH | TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH_EAST, isInactive(), com.runehive.game.world.pathfinding.TraversalConstants.WALL_EAST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH, and com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH_EAST.
isTraversableNorthWest() [3/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableNorthWest (int height, int x, int y, int size) static private
Tests if the specified position can be traversed north west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
size The size of the entity attempting to traverse north west.
Returns
true if it is possible to traverse north west otherwise false
Definition at line 657 of file TraversalMap.java.
{
        for (int offsetX = 0; offsetX < size; offsetX++) {
            for (int offsetY = 0; offsetY < size; offsetY++) {
                if (!isTraversableNorthWest(height, x + offsetX, y + offsetY)) {
                    return false;
                }
            }
        }
        return true;
    }
References isTraversableNorthWest().
Referenced by getRandomTraversableTile(), getTraversableTiles(), isTraversable(), isTraversable(), isTraversableNorthWest(), and isTraversableNorthWest().
isTraversableSouth() [1/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouth (int height, int x, int y) static private
Tests if the specified position can be traversed south.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
true if it is possible to traverse south otherwise false.
Definition at line 473 of file TraversalMap.java.
{
        return isTraversableSouth(height, x, y, false);
    }
References isTraversableSouth().
isTraversableSouth() [2/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouth (int height, int x, int y, boolean impenetrable) static private
Tests if the specified position can be traversed south.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
impenetrable Whether or not this occupation can be traversed.
Returns
true if it is possible to traverse south otherwise false.
Definition at line 487 of file TraversalMap.java.
{
        if (impenetrable) {
            return isInactive(height, x, y - 1, TraversalConstants.IMPENETRABLE_BLOCKED | TraversalConstants.IMPENETRABLE_WALL_NORTH);
        }
        return isInactive(height, x, y - 1, TraversalConstants.WALL_NORTH | TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH, isInactive(), and com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH.
isTraversableSouth() [3/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouth (int height, int x, int y, int size) static private
Tests if the specified position can be traversed south.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
size The size of the entity attempting to traverse south.
Returns
true if it is possible to traverse south otherwise false
Definition at line 453 of file TraversalMap.java.
{
        for (int offsetX = 0; offsetX < size; offsetX++) {
            for (int offsetY = 0; offsetY < size; offsetY++) {
                if (!isTraversableSouth(height, x + offsetX, y + offsetY)) {
                    return false;
                }
            }
        }
        return true;
    }
References isTraversableSouth().
Referenced by blockedSouth(), getRandomNonDiagonal(), getRandomTraversableTile(), getTraversableTiles(), isTraversable(), isTraversable(), isTraversableSouth(), and isTraversableSouth().
isTraversableSouthEast() [1/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouthEast (int height, int x, int y) static private
Tests if the specified position can be traversed south east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
true if it is possible to traverse south east otherwise false.
Definition at line 728 of file TraversalMap.java.
{
        return isTraversableSouthEast(height, x, y, false);
    }
References isTraversableSouthEast().
isTraversableSouthEast() [2/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouthEast (int height, int x, int y, boolean impenetrable) static private
Tests if the specified position can be traversed south east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
impenetrable Whether or not this occupation can be traversed.
Returns
true if it is possible to traverse south east otherwise false.
Definition at line 742 of file TraversalMap.java.
{
        if (impenetrable) {
            return isInactive(height, x + 1, y - 1, TraversalConstants.IMPENETRABLE_WALL_WEST | TraversalConstants.IMPENETRABLE_WALL_NORTH | TraversalConstants.IMPENETRABLE_WALL_NORTH_WEST) && isInactive(height, x + 1, y, TraversalConstants.IMPENETRABLE_WALL_WEST | TraversalConstants.IMPENETRABLE_BLOCKED) && isInactive(height, x, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH | TraversalConstants.IMPENETRABLE_BLOCKED);
        }
        return isInactive(height, x + 1, y - 1, TraversalConstants.WALL_WEST | TraversalConstants.WALL_NORTH | TraversalConstants.WALL_NORTH_WEST | TraversalConstants.BLOCKED) && isInactive(height, x + 1, y, TraversalConstants.WALL_WEST | TraversalConstants.BLOCKED) && isInactive(height, x, y - 1, TraversalConstants.WALL_NORTH | TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_WEST, isInactive(), com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH, com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH_WEST, and com.runehive.game.world.pathfinding.TraversalConstants.WALL_WEST.
isTraversableSouthEast() [3/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouthEast (int height, int x, int y, int size) static private
Tests if the specified position can be traversed south east.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
size The size of the entity attempting to traverse south east.
Returns
true if it is possible to traverse south east otherwise false
Definition at line 708 of file TraversalMap.java.
{
        for (int offsetX = 0; offsetX < size; offsetX++) {
            for (int offsetY = 0; offsetY < size; offsetY++) {
                if (!isTraversableSouthEast(height, x + offsetX, y + offsetY)) {
                    return false;
                }
            }
        }
        return true;
    }
References isTraversableSouthEast().
Referenced by getRandomTraversableTile(), getTraversableTiles(), isTraversable(), isTraversable(), isTraversableSouthEast(), and isTraversableSouthEast().
isTraversableSouthWest() [1/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouthWest (int height, int x, int y) static private
Tests if the specified position can be traversed south west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
true if it is possible to traverse south west otherwise false.
Definition at line 779 of file TraversalMap.java.
{
        return isTraversableSouthWest(height, x, y, false);
    }
References isTraversableSouthWest().
isTraversableSouthWest() [2/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouthWest (int height, int x, int y, boolean impenetrable) static private
Tests if the specified position can be traversed south west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
impenetrable Whether or not this occupation can be traversed.
Returns
true if it is possible to traverse south west otherwise false.
Definition at line 793 of file TraversalMap.java.
{
        if (impenetrable) {
            return isInactive(height, x - 1, y - 1, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_WALL_NORTH | TraversalConstants.IMPENETRABLE_WALL_NORTH_EAST) && isInactive(height, x - 1, y, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_BLOCKED) && isInactive(height, x, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH | TraversalConstants.IMPENETRABLE_BLOCKED);
        }
        return isInactive(height, x - 1, y - 1, TraversalConstants.WALL_EAST | TraversalConstants.WALL_NORTH | TraversalConstants.WALL_NORTH_EAST | TraversalConstants.BLOCKED) && isInactive(height, x - 1, y, TraversalConstants.WALL_EAST | TraversalConstants.BLOCKED) && isInactive(height, x, y - 1, TraversalConstants.WALL_NORTH | TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH_EAST, isInactive(), com.runehive.game.world.pathfinding.TraversalConstants.WALL_EAST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH, and com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH_EAST.
isTraversableSouthWest() [3/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableSouthWest (int height, int x, int y, int size) static private
Tests if the specified position can be traversed south west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
size The size of the entity attempting to traverse south west.
Returns
true if it is possible to traverse south west otherwise false
Definition at line 759 of file TraversalMap.java.
{
        for (int offsetX = 0; offsetX < size; offsetX++) {
            for (int offsetY = 0; offsetY < size; offsetY++) {
                if (!isTraversableSouthWest(height, x + offsetX, y + offsetY)) {
                    return false;
                }
            }
        }
        return true;
    }
References isTraversableSouthWest().
Referenced by getRandomTraversableTile(), getTraversableTiles(), isTraversable(), isTraversable(), isTraversableSouthWest(), and isTraversableSouthWest().
isTraversableWest() [1/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableWest (int height, int x, int y) static private
Tests if the specified position can be traversed west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Returns
true if it is possible to traverse west otherwise false.
Definition at line 575 of file TraversalMap.java.
{
        return isTraversableWest(height, x, y, false);
    }
References isTraversableWest().
isTraversableWest() [2/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableWest (int height, int x, int y, boolean impenetrable) static private
Tests if the specified position can be traversed west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
impenetrable Whether or not this occupation can be traversed.
Returns
true if it is possible to traverse west otherwise false.
Definition at line 589 of file TraversalMap.java.
{
        if (impenetrable) {
            return isInactive(height, x - 1, y, TraversalConstants.IMPENETRABLE_BLOCKED | TraversalConstants.IMPENETRABLE_WALL_EAST);
        }
        return isInactive(height, x - 1, y, TraversalConstants.WALL_EAST | TraversalConstants.BLOCKED);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_EAST, isInactive(), and com.runehive.game.world.pathfinding.TraversalConstants.WALL_EAST.
isTraversableWest() [3/3]
boolean com.runehive.game.world.pathfinding.TraversalMap.isTraversableWest (int height, int x, int y, int size) static private
Tests if the specified position can be traversed west.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
size The size of the entity attempting to traverse west.
Returns
true if it is possible to traverse west otherwise false
Definition at line 555 of file TraversalMap.java.
{
        for (int width = 0; width < size; width++) {
            for (int length = 0; length < size; length++) {
                if (!isTraversableWest(height, x + width, y + length)) {
                    return false;
                }
            }
        }
        return true;
    }
References isTraversableWest().
Referenced by blockedWest(), getRandomNonDiagonal(), getRandomTraversableTile(), getTraversableTiles(), isTraversable(), isTraversable(), isTraversableWest(), and isTraversableWest().
markBridge()
void com.runehive.game.world.pathfinding.TraversalMap.markBridge (Region region, int height, int x, int y) static
Marks the specified coordinates a bridge.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
Definition at line 388 of file TraversalMap.java.
{
        set(region, height, x, y, TraversalConstants.BRIDGE);
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BRIDGE.
markObject()
void com.runehive.game.world.pathfinding.TraversalMap.markObject (Region region, GameObject object, boolean add, boolean list) static
Marks a GameObject with the specified attributes on the specified Position to the TraversalMap.
Parameters
object The game object.
add The condition if the object is added.
list the condition if the region object list will be affected.
Definition at line 36 of file TraversalMap.java.
{
        if (object.getId() > GameObjectDefinition.MAX_DEFINITIONS) {
            return;
        }
        GameObjectDefinition def = object.getDefinition();
        if (def.isSolid()) {
            Position position = object.getPosition();
            //Sets the sizes.
            final int sizeX;
            final int sizeY;
            if (object.getDirection() == ObjectDirection.NORTH || object.getDirection() == ObjectDirection.SOUTH) {
                sizeX = def.getLength();
                sizeY = def.getWidth();
            } else {
                sizeX = def.getWidth();
                sizeY = def.getLength();
            }
            if (object.getObjectType() == GROUND_PROP) {
                if (def.hasActions() || def.isDecoration()) {
                    if (def.hasActions()) {
                        markOccupant(region, position.getHeight(), position.getX(), position.getY(), sizeX, sizeY, false, add);
                    }
                }
            } else if (object.getObjectType() == GENERAL_PROP || object.getObjectType() == WALKABLE_PROP) {
                markOccupant(region, position.getHeight(), position.getX(), position.getY(), sizeX, sizeY, def.isImpenetrable(), add);
            } else if (object.getObjectType().getId() >= 12) {
                markOccupant(region, position.getHeight(), position.getX(), position.getY(), sizeX, sizeY, def.isImpenetrable(), add);
            } else if (object.getObjectType() == DIAGONAL_WALL) {
                markOccupant(region, position.getHeight(), position.getX(), position.getY(), sizeX, sizeY, def.isImpenetrable(), add);
            } else if (object.getObjectType().getId() >= 0 && object.getObjectType().getId() <= 3) {
                if (add)
                    markWall(region, object.getDirection(), position.getHeight(), position.getX(), position.getY(), object.getObjectType(), def.isImpenetrable());
                else
                    unmarkWall(region, object.getDirection(), position.getHeight(), position.getX(), position.getY(), object.getObjectType(), def.isImpenetrable());
            }
        }
        if (list && (object.getId() == 11700 || object.getDefinition().hasActions())) {
            if (add) region.addObject(object);
            else region.removeObject(object);
        }
    }
References markOccupant(), markWall(), com.runehive.game.world.object.GameObjectDefinition.MAX_DEFINITIONS, com.runehive.game.world.object.ObjectDirection.NORTH, com.runehive.game.world.object.ObjectDirection.SOUTH, and unmarkWall().
Referenced by com.runehive.game.world.object.CustomGameObject.addToRegion(), com.runehive.fs.cache.decoder.RegionDecoder.parseGameObject(), com.runehive.game.world.object.StaticGameObject.register(), com.runehive.game.world.object.CustomGameObject.removeFromRegion(), and com.runehive.game.world.object.StaticGameObject.unregister().
markOccupant()
void com.runehive.game.world.pathfinding.TraversalMap.markOccupant (Region region, int height, int x, int y, int width, int length, boolean impenetrable, boolean add) static
Marks the specified coordinates occupied by some object.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
width The width of the occupation.
length The length of the occupation.
impenetrable Whether or not this occupation can be passed through.
add Flag if the occupant is added or removed.
Definition at line 368 of file TraversalMap.java.
{
        int flag = TraversalConstants.BLOCKED;
        if (impenetrable) {
            flag += TraversalConstants.IMPENETRABLE_BLOCKED;
        }
        for (int xPos = x; xPos < x + width; xPos++) {
            for (int yPos = y; yPos < y + length; yPos++) {
                if (add) set(region, height, xPos, yPos, flag);
                else unset(region, height, xPos, yPos, flag);
            }
        }
    }
References com.runehive.game.world.pathfinding.TraversalConstants.BLOCKED, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_BLOCKED, and unset().
Referenced by markObject().
markWall()
void com.runehive.game.world.pathfinding.TraversalMap.markWall (Region reg, ObjectDirection orientation, int height, int x, int y, ObjectType type, boolean impenetrable) static private
Informs the region of an existing wall.
Parameters
orientation The orientation of the wall.
height The walls height.
x The walls x coordinate.
y The walls y coordinate.
type The type of wall.
impenetrable Whether or not this wall can be passed through.
Definition at line 94 of file TraversalMap.java.
{
        switch (type) {
            case STRAIGHT_WALL:
                if (orientation == ObjectDirection.WEST) {
                    set(reg, height, x, y, TraversalConstants.WALL_WEST);
                    set(reg, height, x - 1, y, TraversalConstants.WALL_EAST);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_WEST);
                        set(reg, height, x - 1, y, TraversalConstants.IMPENETRABLE_WALL_EAST);
                    }
                }
                if (orientation == ObjectDirection.NORTH) {
                    set(reg, height, x, y, TraversalConstants.WALL_NORTH);
                    set(reg, height, x, y + 1, TraversalConstants.WALL_SOUTH);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_NORTH);
                        set(reg, height, x, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                    }
                }
                if (orientation == ObjectDirection.EAST) {
                    set(reg, height, x, y, TraversalConstants.WALL_EAST);
                    set(reg, height, x + 1, y, TraversalConstants.WALL_WEST);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_EAST);
                        set(reg, height, x + 1, y, TraversalConstants.IMPENETRABLE_WALL_WEST);
                    }
                }
                if (orientation == ObjectDirection.SOUTH) {
                    set(reg, height, x, y, TraversalConstants.WALL_SOUTH);
                    set(reg, height, x, y - 1, TraversalConstants.WALL_NORTH);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                        set(reg, height, x, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH);
                    }
                }
                break;
            case ENTIRE_WALL:
                if (orientation == ObjectDirection.WEST) {
                    set(reg, height, x, y, TraversalConstants.WALL_WEST | TraversalConstants.WALL_NORTH);
                    set(reg, height, x - 1, y, TraversalConstants.WALL_EAST);
                    set(reg, height, x, y + 1, TraversalConstants.WALL_SOUTH);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_WEST | TraversalConstants.IMPENETRABLE_WALL_NORTH);
                        set(reg, height, x - 1, y, TraversalConstants.IMPENETRABLE_WALL_EAST);
                        set(reg, height, x, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                    }
                }
                if (orientation == ObjectDirection.NORTH) {
                    set(reg, height, x, y, TraversalConstants.WALL_EAST | TraversalConstants.WALL_NORTH);
                    set(reg, height, x, y + 1, TraversalConstants.WALL_SOUTH);
                    set(reg, height, x + 1, y, TraversalConstants.WALL_WEST);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_WALL_NORTH);
                        set(reg, height, x, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                        set(reg, height, x + 1, y, TraversalConstants.IMPENETRABLE_WALL_WEST);
                    }
                }
                if (orientation == ObjectDirection.EAST) {
                    set(reg, height, x, y, TraversalConstants.WALL_EAST | TraversalConstants.WALL_SOUTH);
                    set(reg, height, x + 1, y, TraversalConstants.WALL_WEST);
                    set(reg, height, x, y - 1, TraversalConstants.WALL_NORTH);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                        set(reg, height, x + 1, y, TraversalConstants.IMPENETRABLE_WALL_WEST);
                        set(reg, height, x, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH);
                    }
                }
                if (orientation == ObjectDirection.SOUTH) {
                    set(reg, height, x, y, TraversalConstants.WALL_WEST | TraversalConstants.WALL_SOUTH);
                    set(reg, height, x - 1, y, TraversalConstants.WALL_EAST);
                    set(reg, height, x, y - 1, TraversalConstants.WALL_NORTH);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_WEST | TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                        set(reg, height, x - 1, y, TraversalConstants.IMPENETRABLE_WALL_EAST);
                        set(reg, height, x, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH);
                    }
                }
                break;
            case DIAGONAL_CORNER_WALL:
            case WALL_CORNER:
                if (orientation == ObjectDirection.WEST) {
                    set(reg, height, x, y, TraversalConstants.WALL_NORTH_WEST);
                    set(reg, height, x - 1, y + 1, TraversalConstants.WALL_SOUTH_EAST);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_NORTH_WEST);
                        set(reg, height, x - 1, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH_EAST);
                    }
                }
                if (orientation == ObjectDirection.NORTH) {
                    set(reg, height, x, y, TraversalConstants.WALL_NORTH_EAST);
                    set(reg, height, x + 1, y + 1, TraversalConstants.WALL_SOUTH_WEST);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_NORTH_EAST);
                        set(reg, height, x + 1, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH_WEST);
                    }
                }
                if (orientation == ObjectDirection.EAST) {
                    set(reg, height, x, y, TraversalConstants.WALL_SOUTH_EAST);
                    set(reg, height, x + 1, y - 1, TraversalConstants.WALL_NORTH_WEST);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_SOUTH_EAST);
                        set(reg, height, x + 1, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH_WEST);
                    }
                }
                if (orientation == ObjectDirection.SOUTH) {
                    set(reg, height, x, y, TraversalConstants.WALL_SOUTH_WEST);
                    set(reg, height, x - 1, y - 1, TraversalConstants.WALL_NORTH_EAST);
                    if (impenetrable) {
                        set(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_SOUTH_WEST);
                        set(reg, height, x - 1, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH_EAST);
                    }
                }
                break;
            default:
                break;
        }
    }
References com.runehive.game.world.object.ObjectDirection.EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH_EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH_EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_WEST, com.runehive.game.world.object.ObjectDirection.NORTH, com.runehive.game.world.object.ObjectDirection.SOUTH, com.runehive.game.world.pathfinding.TraversalConstants.WALL_EAST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH, com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH_EAST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH, com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH_EAST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_WEST, and com.runehive.game.world.object.ObjectDirection.WEST.
Referenced by markObject().
set()
void com.runehive.game.world.pathfinding.TraversalMap.set (Region region, int height, int x, int y, int flag) static
Sets a flag on the specified position.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
flag The flag to put on this tile.
Definition at line 808 of file TraversalMap.java.
{
        region.setFlags(height, x & 0x3F, y & 0x3F, flag);
    }
unmarkWall()
void com.runehive.game.world.pathfinding.TraversalMap.unmarkWall (Region reg, ObjectDirection orientation, int height, int x, int y, ObjectType type, boolean impenetrable) static private
Informs the region of an existing wall being removed.
Parameters
orientation The orientation of the wall.
height The walls height.
x The walls x coordinate.
y The walls y coordinate.
type The type of wall.
impenetrable Whether or not this wall can be passed through.
Definition at line 224 of file TraversalMap.java.
{
        switch (type) {
            case STRAIGHT_WALL:
                if (orientation == ObjectDirection.WEST) {
                    unset(reg, height, x, y, TraversalConstants.WALL_WEST);
                    unset(reg, height, x - 1, y, TraversalConstants.WALL_EAST);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_WEST);
                        unset(reg, height, x - 1, y, TraversalConstants.IMPENETRABLE_WALL_EAST);
                    }
                }
                if (orientation == ObjectDirection.NORTH) {
                    unset(reg, height, x, y, TraversalConstants.WALL_NORTH);
                    unset(reg, height, x, y + 1, TraversalConstants.WALL_SOUTH);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_NORTH);
                        unset(reg, height, x, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                    }
                }
                if (orientation == ObjectDirection.EAST) {
                    unset(reg, height, x, y, TraversalConstants.WALL_EAST);
                    unset(reg, height, x + 1, y, TraversalConstants.WALL_WEST);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_EAST);
                        unset(reg, height, x + 1, y, TraversalConstants.IMPENETRABLE_WALL_WEST);
                    }
                }
                if (orientation == ObjectDirection.SOUTH) {
                    unset(reg, height, x, y, TraversalConstants.WALL_SOUTH);
                    unset(reg, height, x, y - 1, TraversalConstants.WALL_NORTH);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                        unset(reg, height, x, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH);
                    }
                }
                break;
            case ENTIRE_WALL:
                if (orientation == ObjectDirection.WEST) {
                    unset(reg, height, x, y, TraversalConstants.WALL_WEST | TraversalConstants.WALL_NORTH);
                    unset(reg, height, x - 1, y, TraversalConstants.WALL_EAST);
                    unset(reg, height, x, y + 1, TraversalConstants.WALL_SOUTH);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_WEST | TraversalConstants.IMPENETRABLE_WALL_NORTH);
                        unset(reg, height, x - 1, y, TraversalConstants.IMPENETRABLE_WALL_EAST);
                        unset(reg, height, x, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                    }
                }
                if (orientation == ObjectDirection.NORTH) {
                    unset(reg, height, x, y, TraversalConstants.WALL_EAST | TraversalConstants.WALL_NORTH);
                    unset(reg, height, x, y + 1, TraversalConstants.WALL_SOUTH);
                    unset(reg, height, x + 1, y, TraversalConstants.WALL_WEST);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_WALL_NORTH);
                        unset(reg, height, x, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                        unset(reg, height, x + 1, y, TraversalConstants.IMPENETRABLE_WALL_WEST);
                    }
                }
                if (orientation == ObjectDirection.EAST) {
                    unset(reg, height, x, y, TraversalConstants.WALL_EAST | TraversalConstants.WALL_SOUTH);
                    unset(reg, height, x + 1, y, TraversalConstants.WALL_WEST);
                    unset(reg, height, x, y - 1, TraversalConstants.WALL_NORTH);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                        unset(reg, height, x + 1, y, TraversalConstants.IMPENETRABLE_WALL_WEST);
                        unset(reg, height, x, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH);
                    }
                }
                if (orientation == ObjectDirection.SOUTH) {
                    unset(reg, height, x, y, TraversalConstants.WALL_EAST | TraversalConstants.WALL_SOUTH);
                    unset(reg, height, x, y - 1, TraversalConstants.WALL_WEST);
                    unset(reg, height, x - 1, y, TraversalConstants.WALL_NORTH);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_EAST | TraversalConstants.IMPENETRABLE_WALL_SOUTH);
                        unset(reg, height, x, y - 1, TraversalConstants.IMPENETRABLE_WALL_WEST);
                        unset(reg, height, x - 1, y, TraversalConstants.IMPENETRABLE_WALL_NORTH);
                    }
                }
                break;
            case DIAGONAL_CORNER_WALL:
            case WALL_CORNER:
                if (orientation == ObjectDirection.WEST) {
                    unset(reg, height, x, y, TraversalConstants.WALL_NORTH_WEST);
                    unset(reg, height, x - 1, y + 1, TraversalConstants.WALL_SOUTH_EAST);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_NORTH_WEST);
                        unset(reg, height, x - 1, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH_EAST);
                    }
                }
                if (orientation == ObjectDirection.NORTH) {
                    unset(reg, height, x, y, TraversalConstants.WALL_NORTH_EAST);
                    unset(reg, height, x + 1, y + 1, TraversalConstants.WALL_SOUTH_WEST);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_NORTH_EAST);
                        unset(reg, height, x + 1, y + 1, TraversalConstants.IMPENETRABLE_WALL_SOUTH_WEST);
                    }
                }
                if (orientation == ObjectDirection.EAST) {
                    unset(reg, height, x, y, TraversalConstants.WALL_SOUTH_EAST);
                    unset(reg, height, x + 1, y - 1, TraversalConstants.WALL_NORTH_WEST);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_SOUTH_EAST);
                        unset(reg, height, x + 1, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH_WEST);
                    }
                }
                if (orientation == ObjectDirection.SOUTH) {
                    unset(reg, height, x, y, TraversalConstants.WALL_SOUTH_WEST);
                    unset(reg, height, x - 1, y - 1, TraversalConstants.WALL_NORTH_EAST);
                    if (impenetrable) {
                        unset(reg, height, x, y, TraversalConstants.IMPENETRABLE_WALL_SOUTH_WEST);
                        unset(reg, height, x - 1, y - 1, TraversalConstants.IMPENETRABLE_WALL_NORTH_EAST);
                    }
                }
                break;
            default:
                break;
        }
    }
References com.runehive.game.world.object.ObjectDirection.EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH_EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_NORTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH_EAST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_SOUTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.IMPENETRABLE_WALL_WEST, com.runehive.game.world.object.ObjectDirection.NORTH, com.runehive.game.world.object.ObjectDirection.SOUTH, unset(), com.runehive.game.world.pathfinding.TraversalConstants.WALL_EAST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH, com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH_EAST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_NORTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH, com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH_EAST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_SOUTH_WEST, com.runehive.game.world.pathfinding.TraversalConstants.WALL_WEST, and com.runehive.game.world.object.ObjectDirection.WEST.
Referenced by markObject().
unset()
void com.runehive.game.world.pathfinding.TraversalMap.unset (Region region, int height, int x, int y, int flag) static private
Unsets the specified flag from the specified position.
Parameters
height The height.
x The x coordinate.
y The y coordinate.
flag The flag to unset from the specified position.
Definition at line 838 of file TraversalMap.java.
{
        region.unsetFlags(height, x & 0x3F, y & 0x3F, flag);
    }
Referenced by markOccupant(), and unmarkWall().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/pathfinding/TraversalMap.java