RuneHive-Game: com.runehive.content.mysterybox.MysteryBoxManager Class Reference
com.runehive.content.mysterybox.MysteryBoxManager Class Reference
Public Member Functions
boolean click (Item item)
MysteryBoxManager (Player player)
void spin ()
Public Attributes
MysteryBox box
Package Attributes
int count
Private Attributes
final Player player
Detailed Description
Definition at line 12 of file MysteryBoxManager.java.
Constructor & Destructor Documentation
MysteryBoxManager()
com.runehive.content.mysterybox.MysteryBoxManager.MysteryBoxManager (Player player)
Definition at line 17 of file MysteryBoxManager.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
click()
boolean com.runehive.content.mysterybox.MysteryBoxManager.click (Item item)
Definition at line 21 of file MysteryBoxManager.java.
{
        Optional<MysteryBox> mBox = MysteryBox.getMysteryBox(item.getId());
        if (!mBox.isPresent()) {
            return false;
        }
        if (Area.inWilderness(player)) {
            player.dialogueFactory.sendStatement("You can not open a mystery box while in the wilderness!").execute();
            return true;
        }
        if (player.getCombat().inCombat()) {
            player.dialogueFactory.sendStatement("You can not open a mystery box while in combat!").execute();
            return true;
        }
        if (player.playerAssistant.busy() && !player.interfaceManager.isInterfaceOpen(59500)) {
            player.dialogueFactory.sendStatement("You can not open a mystery box right now!").execute();
            return true;
        }
        box = mBox.get();
        count = player.inventory.computeAmountForId(item.getId());
        spin();
     /*   for (int index = 0; index < 11; index++) {
            player.send(new SendConfig((430 + index), 1));
        }
        player.send(new SendItemOnInterface(59581, mBox.get().rewards()));
        player.send(new SendScrollbar(59580, mBox.get().rewards().length * 5));
        player.send(new SendItemOnInterface(59512));
        player.send(new SendColor(59508, 0x37991C));
        player.send(new SendString(mBox.get().name(), 59503));
        player.send(new SendString("You have " + count + " available!", 59507));
        player.interfaceManager.open(59500);*/
        return true;
    }
References box, count, com.runehive.game.world.items.Item.getId(), com.runehive.content.mysterybox.MysteryBox.getMysteryBox(), com.runehive.game.world.position.Area.inWilderness(), player, and spin().
Referenced by com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption().
spin()
void com.runehive.content.mysterybox.MysteryBoxManager.spin ()
Definition at line 59 of file MysteryBoxManager.java.
                       {
        if (box == null) {
            player.interfaceManager.close();
            return;
        }
        if (count == 0) {
            player.dialogueFactory.sendStatement("You do not have any " + box.name() + "!", "To spin a different mystery box level click on the item first!").execute();
            return;
        }
        World.schedule(new MysteryBoxEvent(player));
    }
References box, count, player, and com.runehive.game.world.World.schedule().
Referenced by click().
Member Data Documentation
box
MysteryBox com.runehive.content.mysterybox.MysteryBoxManager.box
Definition at line 15 of file MysteryBoxManager.java.
Referenced by click(), and spin().
count
int com.runehive.content.mysterybox.MysteryBoxManager.count package
Definition at line 14 of file MysteryBoxManager.java.
Referenced by click(), and spin().
player
final Player com.runehive.content.mysterybox.MysteryBoxManager.player private
Definition at line 13 of file MysteryBoxManager.java.
Referenced by click(), MysteryBoxManager(), and spin().
The documentation for this class was generated from the following file:
java/com/runehive/content/mysterybox/MysteryBoxManager.java