RuneHive-Game: com.runehive.game.action.impl.TutorialActivity Class Reference
com.runehive.game.action.impl.TutorialActivity Class Reference
Handles the tutorial activity.
Public Member Functions
void cleanup ()
Cleans up the activity when finished.
void cooldown (int cooldown)
Applies a cooldown.
void finish ()
Finishes the activity.
ActivityType getType ()
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canTeleport (Player player)
Called when the player attempts to teleport.
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
ActivityDeathType deathType ()
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
void onDeath (Mob mob)
Called when the player die.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
void update ()
The update method.
Static Public Member Functions
static TutorialActivity create (Player player)
Creates the tutorial activity for the player.
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Member Functions
boolean clickButton (Player player, ClickButtonInteractionEvent event)
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
void next ()
TutorialActivity (Player player)
Constructs a new TutorialActivity.
void update (String... strings)
Updates the activity panel.
Private Attributes
boolean completed = false
final DialogueFactory factory
The dialogue factory for this activity.
Npc guide
The guide npc for the activity.
final Player player
The player doing the tutorial activity.
int stage
The current activity stage.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Handles the tutorial activity.
Author
Daniel
Definition at line 36 of file TutorialActivity.java.
Constructor & Destructor Documentation
TutorialActivity()
com.runehive.game.action.impl.TutorialActivity.TutorialActivity (Player player) private
Constructs a new TutorialActivity.
Definition at line 53 of file TutorialActivity.java.
{
        super(2, player.playerAssistant.instance());
        this.stage = 0;
        this.player = player;
        this.factory = player.dialogueFactory;
    }
References player.
Referenced by create().
Member Function Documentation
cleanup()
void com.runehive.game.action.impl.TutorialActivity.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 340 of file TutorialActivity.java.
{
        remove(guide);
    }
References guide.
Referenced by finish(), and onLogout().
clickButton()
boolean com.runehive.game.action.impl.TutorialActivity.clickButton (Player player, ClickButtonInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 363 of file TutorialActivity.java.
{
        int button = event.getButton();
        switch (stage) {
            case 8:
                if (button == -15496) {
                    factory.lock(false);
                    player.send(new SendMessage(":settingupdate:"));
                    player.interfaceManager.open(28_500);
                    start();
                }
                return true;
            case 9:
                if (button == 28502) {
                    factory.lock(false);
                    player.interfaceManager.close();
                    start();
                }
                return true;
            case 10:
                if (button == -15531) {
                    factory.lock(false);
                    player.interfaceManager.setSidebar(Config.WRENCH_TAB, 50300);
                    player.send(new SendConfig(980, 3));
                    next();
                }
                return true;
            case 12:
                if (button == 850) {
                    factory.lock(false);
                    TeleportHandler.open(player, TeleportType.FAVORITES);
                    start();
                }
                return true;
            case 13:
                if (button == -7534) {
                    factory.lock(false);
                    player.interfaceManager.close();
                    start();
                }
                return true;
        }
        return false;
    }
References factory, com.runehive.content.skill.impl.magic.teleport.TeleportType.FAVORITES, next(), com.runehive.content.teleport.TeleportHandler.open(), player, stage, start(), and com.runehive.Config.WRENCH_TAB.
cooldown()
void com.runehive.game.action.impl.TutorialActivity.cooldown (int cooldown)
Applies a cooldown.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 81 of file TutorialActivity.java.
{
        super.cooldown(cooldown);
        factory.clear();
    }
References cooldown(), and factory.
Referenced by cooldown(), and create().
create()
TutorialActivity com.runehive.game.action.impl.TutorialActivity.create (Player player) static
Creates the tutorial activity for the player.
Definition at line 61 of file TutorialActivity.java.
{
        TutorialActivity activity = new TutorialActivity(player);
        player.runEnergy = 100;
        player.send(new SendSpecialAmount());
        player.movement.setRunningToggled(false);
        player.playerAssistant.setSidebar(true);
        player.setVisible(false);
        player.move(Config.DEFAULT_POSITION);
        activity.cooldown(3);
        activity.add(player);
        player.locking.lock();
        return activity;
    }
References com.runehive.content.activity.Activity.add(), cooldown(), com.runehive.Config.DEFAULT_POSITION, player, and TutorialActivity().
finish()
void com.runehive.game.action.impl.TutorialActivity.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 345 of file TutorialActivity.java.
{
        player.setVisible(true);
        player.playerAssistant.setSidebar(false);
        cleanup();
        remove(player);
        factory.clear();
        player.locking.unlock();
        ActivityPanel.clear(player);
        if (completed) {
            AchievementHandler.activate(player, AchievementKey.COMPLETE_TUTORIAL);
        }
        if (player.needsStarter) {
            StarterKit.open(player);
        }
    }
References com.runehive.content.achievement.AchievementHandler.activate(), cleanup(), com.runehive.content.activity.panel.ActivityPanel.clear(), com.runehive.content.achievement.AchievementKey.COMPLETE_TUTORIAL, completed, factory, com.runehive.content.StarterKit.open(), and player.
Referenced by start().
getType()
ActivityType com.runehive.game.action.impl.TutorialActivity.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 423 of file TutorialActivity.java.
{
        return ActivityType.TUTORIAL;
    }
References com.runehive.content.activity.ActivityType.TUTORIAL.
next()
void com.runehive.game.action.impl.TutorialActivity.next () private
Definition at line 86 of file TutorialActivity.java.
{
        update();
        cooldown(1);
    }
References com.runehive.content.activity.Activity.cooldown, and com.runehive.content.activity.Activity.update().
Referenced by clickButton(), and start().
onLogout()
void com.runehive.game.action.impl.TutorialActivity.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 412 of file TutorialActivity.java.
{
        cleanup();
        remove(player);
        player.move(Config.DEFAULT_POSITION);
        if (player.needsStarter) {
            player.newPlayer = true;
        }
    }
References cleanup(), com.runehive.Config.DEFAULT_POSITION, and player.
onRegionChange()
void com.runehive.game.action.impl.TutorialActivity.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 408 of file TutorialActivity.java.
{
    }
References player.
start()
void com.runehive.game.action.impl.TutorialActivity.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 92 of file TutorialActivity.java.
{
//        System.out.println(stage);
        switch (stage) {
            case 0:
                guide = new Npc(306, new Position(3222, 3223));
                add(guide);
                guide.graphic(new Graphic(86, true));
                cooldown(2);
                break;
            case 1:
                guide.face(player.getPosition());
                guide.animate(new Animation(863));
                guide.speak("Hello, " + player.getName() + "!");
                cooldown(2);
                break;
            case 2:
                guide.walk(new Position(3222, 3218));
                cooldown(1);
                break;
            case 3:
                player.face(guide.getPosition());
                factory.sendNpcChat(306, "Welcome to <col=D63E3E>Augury</col>, " + player.getName(),
                        "Would you like a tutorial of our lands?");
                factory.sendOption("Yes", () -> cooldown(1), "No", this::finish);
                factory.execute();
                pause();
                break;
            case 4:
                update("This is the activity panel.", "The activity panel replaces a lot", "of interfaces so be sure",
                        "to get acquainted to it.");
                factory.sendNpcChat(306, "Wise choice my friend! Let's get started.",
                        "The first thing you need to know about is the", "activity panel. When you are doing an activity,",
                        "like this tutorial for example; a panel will be available to you.");
                factory.sendNpcChat(306, "You can access this panel by clicking the red tab icon.",
                        "The activity panel is disabled by default but will", "automatically enable when in a activity.");
                factory.onAction(() -> cooldown(1));
                factory.execute();
                pause();
                break;
            case 5:
                factory.sendNpcChat(306, "Before I show you around I want to show you",
                        "useful content for your adventures.");
                factory.onAction(() -> {
                    player.interfaceManager.setSidebar(Config.QUEST_TAB, 29400);
                    player.send(new SendForceTab(Config.QUEST_TAB));
                    next();
                });
                factory.execute();
                pause();
                break;
            case 6:
                factory.sendNpcChat(306, "This is your quest tab. Inside contains information about",
                        "the world and yourself. On the top right corner of the",
                        "tab you will see a bunch of different buttons.");
                factory.sendNpcChat(306, "The blue button will show you the quest tab",
                        "The green button will provide you with various options.");
                factory.sendNpcChat(306, "Some of these options include - npc drop viwer,",
                        "log drop simulator, log kill logs, title manager and more!");
                factory.sendNpcChat(306, "Lastly, the scroll button will open a menu where you can",
                        "change game related options. For example: welcome screen,",
                        " triviabot, drop notification, and more! These options",
                        "are not to be confused with the client options.");
                factory.onAction(() -> {
                    player.interfaceManager.setSidebar(Config.QUEST_TAB, -1);
                    player.interfaceManager.setSidebar(Config.WRENCH_TAB, 50020);
                    next();
                });
                factory.execute();
                pause();
                break;
            case 7:
                player.send(new SendForceTab(Config.WRENCH_TAB));
                factory.sendNpcChat(306, "This is your settings tab. Here you can change all options",
                        "that are for your client. The interface has different tabs.",
                        "You are currently in the display tab. You can change all", " display settings here.");
                factory.onAction(this::next);
                factory.execute();
                pause();
                break;
            case 8:
                setInstance(Mob.DEFAULT_INSTANCE);
                player.instance = Mob.DEFAULT_INSTANCE;
                player.loadRegion();
                factory.sendNpcChat(306, "Let's move on.");
                factory.sendNpcChat(306, "Edgeville will be your primary home, however you",
                        "can change it later on as you progress", "in the game.").onAction(this::next);
                factory.execute();
                pause();
                break;
            case 9:
                Teleportation.teleport(player, new Position(3089, 3492), MODERN, () -> {
                    player.face(Direction.EAST);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 10:
                factory.sendNpcChat(306, "Throughout your adventures you will find key halves.",
                        "When using the right halves together you will be able",
                        "to form a Crystal key. With that key you can unlock this chest.",
                        "This chest contains various high valued items.").onAction(this::next).execute();
                pause();
                break;
            case 11:
                Teleportation.teleport(player, new Position(3091, 3494), MODERN, () -> {
                    player.face(Direction.WEST);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 12:
                factory.sendNpcChat(306, "This is our market place. You can put any items you",
                                "would like to sell in your store. You can also", "purchase items from other players.")
                        .onAction(this::next);
                factory.execute();
                pause();
                break;
            case 13:
                Teleportation.teleport(player, new Position(3093, 3500), MODERN, () -> {
                    player.face(Direction.EAST);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 14:
                factory.sendNpcChat(306, "These thieving stalls are a very good for making", "quick money.")
                        .onAction(this::next).execute();
                pause();
                break;
            case 15:
                Teleportation.teleport(player, new Position(3080, 3491), MODERN, () -> {
                    player.face(Direction.WEST);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 16:
                factory.sendNpcChat(306, "Here are shops that will sell you all the supplies you may need,",
                        " aswell as gear/food/potions/misc items and more.").onAction(this::next).execute();
                pause();
                break;
            case 17:
                Teleportation.teleport(player, new Position(3080, 3491), MODERN, () -> {
                    player.face(Direction.WEST);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 18:
                factory.sendNpcChat(306, "These npcs can really help you out, anywhere from",
                                "mass decanting potions, changing appearances,", "buying skillcapes and more!").onAction(this::next)
                        .execute();
                pause();
                break;
            case 19:
                Teleportation.teleport(player, new Position(3086, 3500), MODERN, () -> {
                    player.face(Direction.WEST);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 20:
                factory.sendNpcChat(306, "This is the Well of goodwill,",
                        "you will be able to contribute gold for a server wide",
                        "experience bonus that will last 30 Minutes.").onAction(this::next).execute();
                pause();
                break;
            case 21:
                Teleportation.teleport(player, new Position(3078, 3509), MODERN, () -> {
                    player.face(Direction.SOUTH);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 22:
                factory.sendNpcChat(306, "This is the fun pk arena.",
                                "Here you can fight players in multi-combat and lose nothing", "on death!").onAction(this::next)
                        .execute();
                pause();
                break;
            case 23:
                Teleportation.teleport(player, new Position(3090, 3474), MODERN, () -> {
                    player.face(Direction.SOUTH);
                    next();
                    player.onStep();
                    player.locking.lock();
                });
                pause();
                break;
            case 24:
                factory.sendNpcChat(306, "This is the skilling area for members with",
                        "Extreme Donator status.");
                factory.onAction(() -> {
                    player.face(Direction.SOUTH);
                    next();
                    player.locking.lock();
                });
                factory.execute();
                pause();
                break;
            case 25:
                Teleportation.teleport(player, new Position(3097, 3498), MODERN, () -> {
                    player.face(Direction.NORTH);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 26:
                factory.sendNpcChat(1143, "Hello #name.", "I am the clan master.");
                factory.sendNpcChat(1143, "Clans are going to be extremely useful for your adventures.",
                        "Joining a clan can give you extra experience rewards,",
                        "experience and drop modifiers, and much more!", "It is also a great way to make new friends!");
                factory.sendNpcChat(1143, "There are heavily enforced rules for being in a clan.",
                        "Check out the rules on our forums ::clanrules");
                factory.onAction(this::next).execute();
                pause();
                break;
            case 27:
                Teleportation.teleport(player, Config.DEFAULT_POSITION, MODERN, () -> {
                    player.face(Direction.SOUTH);
                    next();
                    player.locking.lock();
                });
                pause();
                break;
            case 28:
                factory.sendNpcChat(306, "That's the end of the tutorial! If you have any more questions",
                                "Check out our forums for detail guides or ask a moderator.", "Good luck #name!")
                        .onAction(this::next).execute();
                pause();
                break;
            case 29:
                completed = true;
                finish();
                break;
        }
        stage++;
    }
References com.runehive.content.activity.Activity.add(), completed, com.runehive.content.activity.Activity.cooldown, com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, com.runehive.Config.DEFAULT_POSITION, com.runehive.game.world.entity.mob.Direction.EAST, factory, finish(), guide, next(), com.runehive.game.world.entity.mob.Direction.NORTH, com.runehive.content.activity.Activity.pause(), player, com.runehive.Config.QUEST_TAB, com.runehive.content.activity.Activity.setInstance(), com.runehive.game.world.entity.mob.Direction.SOUTH, stage, com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport(), com.runehive.content.activity.Activity.update(), com.runehive.game.world.entity.mob.Direction.WEST, and com.runehive.Config.WRENCH_TAB.
Referenced by clickButton().
update()
void com.runehive.game.action.impl.TutorialActivity.update (String... strings) private
Updates the activity panel.
Definition at line 76 of file TutorialActivity.java.
{
        ActivityPanel.update(player, (int) Utility.getPercentageAmount(stage, 27), "Tutorial", "Progress", strings);
    }
References com.runehive.util.Utility.getPercentageAmount(), player, stage, and com.runehive.content.activity.panel.ActivityPanel.update().
Member Data Documentation
completed
boolean com.runehive.game.action.impl.TutorialActivity.completed = false private
Definition at line 50 of file TutorialActivity.java.
Referenced by finish(), and start().
factory
final DialogueFactory com.runehive.game.action.impl.TutorialActivity.factory private
The dialogue factory for this activity.
Definition at line 48 of file TutorialActivity.java.
Referenced by clickButton(), cooldown(), finish(), and start().
guide
Npc com.runehive.game.action.impl.TutorialActivity.guide private
The guide npc for the activity.
Definition at line 42 of file TutorialActivity.java.
Referenced by cleanup(), and start().
player
final Player com.runehive.game.action.impl.TutorialActivity.player private
The player doing the tutorial activity.
Definition at line 39 of file TutorialActivity.java.
Referenced by clickButton(), create(), finish(), onLogout(), onRegionChange(), start(), TutorialActivity(), and update().
stage
int com.runehive.game.action.impl.TutorialActivity.stage private
The current activity stage.
Definition at line 45 of file TutorialActivity.java.
Referenced by clickButton(), start(), and update().
The documentation for this class was generated from the following file:
java/com/runehive/game/action/impl/TutorialActivity.java