RuneHive-Game: com.runehive.content.mysterybox.MysteryBoxEvent Class Reference
com.runehive.content.mysterybox.MysteryBoxEvent Class Reference
Protected Member Functions
boolean canSchedule ()
A function executed on registration.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
void tick ()
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
Package Functions
MysteryBoxEvent (Player player)
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Private Member Functions
double getItemProbability (MysteryItem item)
MysteryItem getNextItem ()
void move ()
void reward ()
Private Attributes
List< MysteryItem > allItems
List< MysteryItem > items
final MysteryBoxManager mysteryBox
final Player player
int speed
Additional Inherited Members
Public Member Functions inherited from com.runehive.game.task.TickableTask
void execute ()
A function representing the unit of work that will be carried out.
TickableTask (boolean instant, int delay)
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Detailed Description
Definition at line 13 of file MysteryBoxEvent.java.
Constructor & Destructor Documentation
MysteryBoxEvent()
com.runehive.content.mysterybox.MysteryBoxEvent.MysteryBoxEvent (Player player) package
Definition at line 21 of file MysteryBoxEvent.java.
{
        super(false, 1);
        this.player = player;
        this.items = new ArrayList<>();
        this.allItems = new ArrayList<>();
        this.speed = Utility.random(30, 40);
        this.mysteryBox = player.mysteryBox;
    }
References player, and com.runehive.util.Utility.random().
Member Function Documentation
canSchedule()
boolean com.runehive.content.mysterybox.MysteryBoxEvent.canSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 95 of file MysteryBoxEvent.java.
{
        return player.mysteryBox.box != null;
    }
getItemProbability()
double com.runehive.content.mysterybox.MysteryBoxEvent.getItemProbability (MysteryItem item) private
Definition at line 49 of file MysteryBoxEvent.java.
{
        switch (item.rarity) {
            case COMMON:
                return 0.40;
            case UNCOMMON:
                return 0.35;
            case RARE:
                return 0.15;
            case EXOTIC:
                return 0.10;
            default:
                return 0;
        }
    }
References com.runehive.content.mysterybox.MysteryItem.rarity.
Referenced by reward().
getNextItem()
MysteryItem com.runehive.content.mysterybox.MysteryBoxEvent.getNextItem () private
Definition at line 38 of file MysteryBoxEvent.java.
{
        MysteryItem next = null;
        for (MysteryItem item : allItems) {
            if (!items.contains(item)) {
                next = item;
                break;
            }
        }
        return next;
    }
References allItems, and items.
Referenced by move().
move()
void com.runehive.content.mysterybox.MysteryBoxEvent.move () private
Definition at line 30 of file MysteryBoxEvent.java.
{
        allItems.add(items.get(0));
        items.remove(0);
        MysteryItem next = getNextItem();
        allItems.remove(next);
        items.add(next);
    }
References allItems, getNextItem(), and items.
onCancel()
void com.runehive.content.mysterybox.MysteryBoxEvent.onCancel (boolean logout) protected
A function executed on cancellation.
Reimplemented from com.runehive.game.task.Task.
Definition at line 124 of file MysteryBoxEvent.java.
{
        if (logout) {
            player.inventory.add(mysteryBox.box.item(), 1);
        } else {
            reward();
        }
    }
References mysteryBox, player, and reward().
onSchedule()
void com.runehive.content.mysterybox.MysteryBoxEvent.onSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 99 of file MysteryBoxEvent.java.
{
        player.dialogueFactory.clear();
        player.locking.lock();
        allItems.addAll(Arrays.asList(mysteryBox.box.rewards()));
        player.inventory.remove(mysteryBox.box.item(), 1);
        mysteryBox.count = player.inventory.computeAmountForId(mysteryBox.box.item());
        Collections.shuffle(allItems);
        for (int index = 0; index < 11; index++) {
            if (index >= allItems.size())
                continue;
            MysteryItem item = allItems.get(index);
            items.add(item);
            allItems.remove(index);
        }
        player.send(new SendColor(59508, 0xF01616));
        player.send(new SendString("You have " + mysteryBox.count + " mystery box available!", 59507));
    }
References allItems, items, mysteryBox, and player.
reward()
void com.runehive.content.mysterybox.MysteryBoxEvent.reward () private
Definition at line 66 of file MysteryBoxEvent.java.
{
        double randomValue = Math.random();
        double cumulativeProbability = 0.0;
        MysteryItem reward = null;
        Collections.sort(items, Comparator.comparingDouble(this::getItemProbability).reversed());
        for (MysteryItem item : items) {
            double itemProbability = getItemProbability(item);
            cumulativeProbability += itemProbability;
            if (randomValue <= cumulativeProbability) {
                reward = item;
                break;
            }
        }
        if(reward == null) {
            reward = items.get(0);
        }
        if (reward.rarity == MysteryRarity.EXOTIC) {
            World.sendMessage("<icon=17><col=5739B3> osroyale: <col=" + player.right.getColor() + ">" + player.getName() + " </col>has won " + Utility.getAOrAn(reward.getName()) + " <col=5739B3>" + reward.getName() + " </col>from the <col=5739B3>" + mysteryBox.box.name() + "</col>.");
        }
        player.locking.unlock();
        player.inventory.add(reward.getId(), reward.getAmount());
        player.message("Congratulations! You have won @red@" + Utility.getAOrAn(reward.getName()) + " " + reward.getName() + "!\nThis item falls in the rarity of " + reward.rarity.name().toLowerCase() + ".");
        System.out.println("Rarity: " + reward.rarity.name().toLowerCase());
    }
References com.runehive.content.mysterybox.MysteryRarity.EXOTIC, com.runehive.util.Utility.getAOrAn(), getItemProbability(), items, mysteryBox, player, reward(), and com.runehive.game.world.World.sendMessage().
Referenced by onCancel(), and reward().
tick()
void com.runehive.content.mysterybox.MysteryBoxEvent.tick () protected
Reimplemented from com.runehive.game.task.TickableTask.
Definition at line 119 of file MysteryBoxEvent.java.
{
        cancel();
    }
References com.runehive.game.task.Task.cancel().
Member Data Documentation
allItems
List<MysteryItem> com.runehive.content.mysterybox.MysteryBoxEvent.allItems private
Definition at line 16 of file MysteryBoxEvent.java.
Referenced by getNextItem(), move(), and onSchedule().
items
List<MysteryItem> com.runehive.content.mysterybox.MysteryBoxEvent.items private
Definition at line 15 of file MysteryBoxEvent.java.
Referenced by getNextItem(), move(), onSchedule(), and reward().
mysteryBox
final MysteryBoxManager com.runehive.content.mysterybox.MysteryBoxEvent.mysteryBox private
Definition at line 18 of file MysteryBoxEvent.java.
Referenced by onCancel(), onSchedule(), and reward().
player
final Player com.runehive.content.mysterybox.MysteryBoxEvent.player private
Definition at line 14 of file MysteryBoxEvent.java.
Referenced by MysteryBoxEvent(), onCancel(), onSchedule(), and reward().
speed
int com.runehive.content.mysterybox.MysteryBoxEvent.speed private
Definition at line 17 of file MysteryBoxEvent.java.
The documentation for this class was generated from the following file:
java/com/runehive/content/mysterybox/MysteryBoxEvent.java