RuneHive-Game: com.runehive.game.world.pathfinding.path.PathFinder Class Reference
com.runehive.game.world.pathfinding.path.PathFinder Class Reference abstract
An algorithm used to find a path between two Positions.
Public Member Functions
final Path find (Mob origin, Interactable target)
final Path find (Mob origin, Position target)
abstract Path find (Mob source, Position target, int targetWidth, int targetLength)
Finds a valid path from the origin Position to the target one.
Protected Member Functions
boolean projectileCheck (Position current, Position going)
Returns whether or not a Position shooting projectile to another Position would lead to is traversable.
boolean traversable (Position current, int size, Direction... directions)
Returns whether or not a Position walking one step in any of the specified Directions would lead to is traversable.
Package Functions
boolean traversable (Position current, Position going, int size)
Returns whether or not a Position is traversable to the direction of another Position.
Detailed Description
An algorithm used to find a path between two Positions.
Author
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Definition at line 14 of file PathFinder.java.
Member Function Documentation
find() [1/3]
final Path com.runehive.game.world.pathfinding.path.PathFinder.find (Mob origin, Interactable target)
Definition at line 26 of file PathFinder.java.
{
        return find(origin, target.getPosition(), target.width(), target.length());
    }
References find(), com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), and com.runehive.game.world.Interactable.width().
find() [2/3]
final Path com.runehive.game.world.pathfinding.path.PathFinder.find (Mob origin, Position target)
Definition at line 30 of file PathFinder.java.
{
        return find(origin, target, 0, 0);
    }
References find().
find() [3/3]
abstract Path com.runehive.game.world.pathfinding.path.PathFinder.find (Mob source, Position target, int targetWidth, int targetLength) abstract
Finds a valid path from the origin Position to the target one.
Parameters
source
target The target Position.
Returns
The path containing the Positions to go through.
Reimplemented in com.runehive.game.world.pathfinding.path.impl.AStarPathFinder, com.runehive.game.world.pathfinding.path.impl.DijkstraPathFinder, com.runehive.game.world.pathfinding.path.impl.SimplePathFinder, and com.runehive.game.world.pathfinding.path.SimplePathChecker.
Referenced by find(), and find().
projectileCheck()
boolean com.runehive.game.world.pathfinding.path.PathFinder.projectileCheck (Position current, Position going) protected
Returns whether or not a Position shooting projectile to another Position would lead to is traversable.
Parameters
current The current Position.
going The position to which we are going.
Returns
true if any of the Directions lead to a projectile traversable tile, otherwise false.
Definition at line 77 of file PathFinder.java.
{
        Direction first = Direction.getDirection(going, current);
        Direction second = Direction.getDirection(current, going);
        return TraversalMap.isTraversable(current, second, true) && TraversalMap.isTraversable(going, first, true);
    }
References com.runehive.game.world.entity.mob.Direction.getDirection(), and com.runehive.game.world.pathfinding.TraversalMap.isTraversable().
Referenced by com.runehive.game.world.pathfinding.path.SimplePathChecker.check(), and com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.traversable().
traversable() [1/2]
boolean com.runehive.game.world.pathfinding.path.PathFinder.traversable (Position current, int size, Direction... directions) protected
Returns whether or not a Position walking one step in any of the specified Directions would lead to is traversable.
Parameters
current The current Position.
size The entity's size.
directions The Directions that should be checked.
Returns
true if any of the Directions lead to a traversable tile, otherwise false.
Definition at line 44 of file PathFinder.java.
{
        for (Direction direction : directions) {
            if (!TraversalMap.isTraversable(current, direction, size)) {
                return false;
            }
        }
        return true;
    }
References com.runehive.game.world.pathfinding.TraversalMap.isTraversable().
Referenced by com.runehive.game.world.pathfinding.path.SimplePathChecker.check(), com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find(), and com.runehive.game.world.pathfinding.path.impl.DijkstraPathFinder.find().
traversable() [2/2]
boolean com.runehive.game.world.pathfinding.path.PathFinder.traversable (Position current, Position going, int size) package
Returns whether or not a Position is traversable to the direction of another Position.
Parameters
current The current Position.
going The position to which we are going.
Returns
true if any of the Directions lead to a traversable tile, otherwise false.
Definition at line 62 of file PathFinder.java.
{
        Direction first = Direction.getDirection(going, current);
        Direction second = Direction.getDirection(current, going);
        return TraversalMap.isTraversable(current, second, size) && TraversalMap.isTraversable(going, first, size);
    }
References com.runehive.game.world.entity.mob.Direction.getDirection(), and com.runehive.game.world.pathfinding.TraversalMap.isTraversable().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/pathfinding/path/PathFinder.java