RuneHive-Game: com.runehive.content.activity.randomevent.impl.GenieEvent Class Reference
com.runehive.content.activity.randomevent.impl.GenieEvent Class Reference
The Genie random event.
Static Public Member Functions
static GenieEvent create (Player player)
Creates a new Genie event.
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Member Functions
boolean clickNpc (Player player, NpcInteractionEvent event)
int eventNpcIdentification ()
The event npc identification.
String[] eventNpcShout ()
The event npc shout messages.
Protected Member Functions inherited from com.runehive.content.activity.randomevent.RandomEvent
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
GenieEvent (Player player)
Constructs a new GenieEvent.
Additional Inherited Members
Public Member Functions inherited from com.runehive.content.activity.randomevent.RandomEvent
void cleanup ()
Cleans up the activity when finished.
ActivityDeathType deathType ()
void finish ()
Finishes the activity.
ActivityType getType ()
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
RandomEvent (Player player, int cooldown)
Constructs a new RandomEvent.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canTeleport (Player player)
Called when the player attempts to teleport.
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
void onDeath (Mob mob)
Called when the player die.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
void update ()
The update method.
Public Attributes inherited from com.runehive.content.activity.randomevent.RandomEvent
Player player
The player instance.
Protected Attributes inherited from com.runehive.content.activity.randomevent.RandomEvent
boolean angered
Flag if the event is angered.
Npc eventNpc
The event npc.
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
The Genie random event.
Author
Daniel
Definition at line 16 of file GenieEvent.java.
Constructor & Destructor Documentation
GenieEvent()
com.runehive.content.activity.randomevent.impl.GenieEvent.GenieEvent (Player player) private
Constructs a new GenieEvent.
Definition at line 19 of file GenieEvent.java.
{
        super(player, 20);
    }
References com.runehive.content.activity.randomevent.RandomEvent.player.
Referenced by create().
Member Function Documentation
clickNpc()
boolean com.runehive.content.activity.randomevent.impl.GenieEvent.clickNpc (Player player, NpcInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 31 of file GenieEvent.java.
{
        if (event.getNpc().id != eventNpcIdentification())
            return false;
        if (!event.getNpc().owner.equals(player))
            return false;
        if (angered) {
            player.dialogueFactory.sendNpcChat(eventNpcIdentification(), "You had your chance...").execute();
            return true;
        }
        if (event.getOpcode() == 0) {
            int id = eventNpcIdentification();
            player.dialogueFactory.sendNpcChat(id, "Take this lamp as a token of appreciation for playing", "osroyale.").onAction(() -> {
                player.dialogueFactory.clear();
                player.inventory.addOrDrop(new Item(2528, 1));
                finishCooldown();
            }).execute();
        } else if (event.getOpcode() == 1) {
            angered = true;
            player.send(new SendMessage("You have dismissed the genie random event."));
            player.animate(new Animation(863));
            player.interact(eventNpc);
            finishCooldown();
        }
        return true;
    }
References com.runehive.content.activity.randomevent.RandomEvent.angered, com.runehive.content.activity.randomevent.RandomEvent.eventNpc, eventNpcIdentification(), com.runehive.content.activity.Activity.finishCooldown(), and com.runehive.content.activity.randomevent.RandomEvent.player.
create()
GenieEvent com.runehive.content.activity.randomevent.impl.GenieEvent.create (Player player) static
Creates a new Genie event.
Definition at line 24 of file GenieEvent.java.
{
        GenieEvent event = new GenieEvent(player);
        event.add(player);
        return event;
    }
References GenieEvent(), and com.runehive.content.activity.randomevent.RandomEvent.player.
Referenced by com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
eventNpcIdentification()
int com.runehive.content.activity.randomevent.impl.GenieEvent.eventNpcIdentification () protected
The event npc identification.
Reimplemented from com.runehive.content.activity.randomevent.RandomEvent.
Definition at line 68 of file GenieEvent.java.
{
        return 326;
    }
Referenced by clickNpc().
eventNpcShout()
String[] com.runehive.content.activity.randomevent.impl.GenieEvent.eventNpcShout () protected
The event npc shout messages.
Reimplemented from com.runehive.content.activity.randomevent.RandomEvent.
Definition at line 58 of file GenieEvent.java.
{
        return new String[]{
                "Hello %name, I'm here to grant you a wish!",
                "Are you there %name? I have something for you!",
                "C'mon %name, I don't have all day!",
                "I guess you didn't want a free wish! Had your chance!"
        };
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/randomevent/impl/GenieEvent.java