RuneHive-Game: com.runehive.game.world.pathfinding.path.impl.AStarPathFinder Class Reference
com.runehive.game.world.pathfinding.path.impl.AStarPathFinder Class Reference
Represents a PathFinder which uses the A* search algorithm(by passing obstacles).
Public Member Functions
AStarPathFinder (Mob character, Distance heuristic)
Constructs a new AStarPathFinder with the specified traversal tool.mapviewer.
Path find (Interactable destination)
A default method to find a path for the specified Mob.
Path find (Mob source, Position target, int targetWidth, int targetLength)
Performs the path finding calculations to find the path using the A* algorithm.
Path find (Position destination)
A default method to find a path for the specified Mob.
Public Member Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
final Path find (Mob origin, Interactable target)
final Path find (Mob origin, Position target)
Private Member Functions
void compare (Node active, Node other)
Node getCheapest (Queue< Node > nodes)
Gets the cheapest open Node from the Queue.
Private Attributes
final Mob character
final Distance heuristic
The Heuristic used by this PathFinder.
final Map< Position, Node > nodes = new HashMap<>(Region.SIZE * Region.SIZE)
final Set< Node > open = new HashSet<>(Region.SIZE * Region.SIZE)
final Deque< Position > shortest = new ArrayDeque<>(100)
final Queue< Node > sorted = new PriorityQueue<>(Region.SIZE * Region.SIZE)
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
boolean projectileCheck (Position current, Position going)
Returns whether or not a Position shooting projectile to another Position would lead to is traversable.
boolean traversable (Position current, int size, Direction... directions)
Returns whether or not a Position walking one step in any of the specified Directions would lead to is traversable.
Package Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
boolean traversable (Position current, Position going, int size)
Returns whether or not a Position is traversable to the direction of another Position.
Detailed Description
Represents a PathFinder which uses the A* search algorithm(by passing obstacles).
Author
Graham
Major | Suggestions, discussion
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Definition at line 23 of file AStarPathFinder.java.
Constructor & Destructor Documentation
AStarPathFinder()
com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.AStarPathFinder (Mob character, Distance heuristic)
Constructs a new AStarPathFinder with the specified traversal tool.mapviewer.
Definition at line 37 of file AStarPathFinder.java.
{
        this.character = character;
        this.heuristic = heuristic;
    }
References character, and heuristic.
Member Function Documentation
compare()
void com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.compare (Node active, Node other) private
Definition at line 148 of file AStarPathFinder.java.
{
        int cost = active.getCost() + heuristic.calculate(active.getPosition(), other.getPosition());
        if (other.getCost() > cost) {
            open.remove(other);
            other.close();
        } else if (other.isOpen() && !open.contains(other)) {
            other.setCost(cost);
            other.setParent(active);
            open.add(other);
            sorted.add(other);
        }
    }
References com.runehive.game.world.pathfinding.path.impl.Node.close(), com.runehive.game.world.pathfinding.path.impl.Node.getCost(), com.runehive.game.world.pathfinding.path.impl.Node.getPosition(), heuristic, com.runehive.game.world.pathfinding.path.impl.Node.isOpen(), open, com.runehive.game.world.pathfinding.path.impl.Node.setCost(), com.runehive.game.world.pathfinding.path.impl.Node.setParent(), and sorted.
Referenced by find().
find() [1/3]
Path com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find (Interactable destination)
A default method to find a path for the specified Mob.
Parameters
destination The destination of the path.
Returns
A Deque of steps to the specified destination.
Definition at line 63 of file AStarPathFinder.java.
{
        Position origin = character.getPosition();
        if (origin.getHeight() != destination.getHeight())
            return new Path(null);
        return find(character, destination);
    }
References character, find(), com.runehive.game.world.Interactable.getHeight(), and com.runehive.game.world.position.Position.getHeight().
find() [2/3]
Path com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find (Mob source, Position target, int targetWidth, int targetLength)
Performs the path finding calculations to find the path using the A* algorithm.
Parameters
source
target The target Position.
Returns
The path to pursue to reach the destination.
Reimplemented from com.runehive.game.world.pathfinding.path.PathFinder.
Definition at line 80 of file AStarPathFinder.java.
{
        if (source.getHeight() != target.getHeight())
            return new Path(null);
        Node start = new Node(source.getPosition()), end = new Node(target);
        open.clear();
        nodes.clear();
        sorted.clear();
        shortest.clear();
        nodes.put(source.getPosition(), start);
        nodes.put(target, end);
        open.add(start);
        sorted.add(start);
        Node active;
        Position next;
        boolean found = false;
        int distance = (int) (source.getPosition().getDistance(target) * Region.SIZE);
        do {
            active = getCheapest(sorted);
            Position position = active.getPosition();
            if (position.equals(target)) {
                found = true;
                break;
            }
            open.remove(active);
            active.close();
            for (Direction direction : Direction.valid()) {
                next = position.transform(direction.getFaceLocation());
                if (traversable(position, source.width(), direction) && traversable(next, source.width(), Direction.getOppositeDirection(direction))) {
                    Node node = nodes.computeIfAbsent(next, Node::new);
                    compare(active, node);
                }
            }
        } while (!open.isEmpty() && sorted.size() < distance);
        if (found) {
            if (end.hasParent()) {
                active = end;
            }
            if (active.hasParent()) {
                Position position = active.getPosition();
                while (!source.getPosition().equals(position)) {
                    shortest.addFirst(position);
                    active = active.getParent();
                    position = active.getPosition();
                    if (shortest.size() >= 100) {
                        break;
                    }
                }
            }
            return new Path(shortest);
        }
        return new Path(null);
    }
References com.runehive.game.world.pathfinding.path.impl.Node.close(), compare(), com.runehive.game.world.position.Position.equals(), getCheapest(), com.runehive.game.world.position.Position.getDistance(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.entity.mob.Direction.getOppositeDirection(), com.runehive.game.world.pathfinding.path.impl.Node.getParent(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.pathfinding.path.impl.Node.getPosition(), com.runehive.game.world.pathfinding.path.impl.Node.hasParent(), nodes, open, shortest, com.runehive.game.world.region.Region.SIZE, sorted, com.runehive.game.world.pathfinding.path.PathFinder.traversable(), com.runehive.game.world.entity.mob.Direction.valid(), and com.runehive.game.world.entity.Entity.width.
find() [3/3]
Path com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find (Position destination)
A default method to find a path for the specified Mob.
Parameters
destination The destination of the path.
Returns
A Deque of steps to the specified destination.
Definition at line 49 of file AStarPathFinder.java.
{
        Position origin = character.getPosition();
        if (origin.getHeight() != destination.getHeight())
            return new Path(null);
        return find(character, destination);
    }
References character, find(), and com.runehive.game.world.position.Position.getHeight().
Referenced by find(), and find().
getCheapest()
Node com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.getCheapest (Queue< Node > nodes) private
Gets the cheapest open Node from the Queue.
Parameters
nodes The queue of nodes.
Returns
The cheapest node.
Definition at line 167 of file AStarPathFinder.java.
{
        Node node = nodes.peek();
        while (!node.isOpen()) {
            nodes.poll();
            node = nodes.peek();
        }
        return node;
    }
References com.runehive.game.world.pathfinding.path.impl.Node.isOpen(), and nodes.
Referenced by find().
Member Data Documentation
character
final Mob com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.character private
Definition at line 27 of file AStarPathFinder.java.
Referenced by AStarPathFinder(), find(), and find().
heuristic
final Distance com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.heuristic private
The Heuristic used by this PathFinder.
Definition at line 26 of file AStarPathFinder.java.
Referenced by AStarPathFinder(), and compare().
nodes
final Map<Position, Node> com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.nodes = new HashMap<>(Region.SIZE * Region.SIZE) private
Definition at line 28 of file AStarPathFinder.java.
Referenced by find(), and getCheapest().
open
final Set<Node> com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.open = new HashSet<>(Region.SIZE * Region.SIZE) private
Definition at line 29 of file AStarPathFinder.java.
Referenced by compare(), and find().
shortest
final Deque<Position> com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.shortest = new ArrayDeque<>(100) private
Definition at line 31 of file AStarPathFinder.java.
Referenced by find().
sorted
final Queue<Node> com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.sorted = new PriorityQueue<>(Region.SIZE * Region.SIZE) private
Definition at line 30 of file AStarPathFinder.java.
Referenced by compare(), and find().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/pathfinding/path/impl/AStarPathFinder.java