RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy Class Reference
com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy Class Reference
Public Member Functions
void attack (Npc attacker, Mob defender, Hit hit)
boolean canAttack (Npc attacker, Mob defender)
Animation getAttackAnimation (Npc attacker, Mob defender)
int getAttackDelay (Npc attacker, Mob defender, FightType fightType)
int getAttackDistance (Npc attacker, FightType fightType)
CombatType getCombatType ()
CombatHit[] getHits (Npc attacker, Mob defender)
void start (Npc attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Static Public Member Functions
static NpcMeleeStrategy get ()
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions
NpcMeleeStrategy ()
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Static Private Attributes
static final NpcMeleeStrategy INSTANCE = new NpcMeleeStrategy()
Additional Inherited Members
Static Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >
static void addCombatExperience (Player player, Hit... hits)
Detailed Description
Definition at line 16 of file NpcMeleeStrategy.java.
Constructor & Destructor Documentation
NpcMeleeStrategy()
com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.NpcMeleeStrategy () protected
Definition at line 20 of file NpcMeleeStrategy.java.
{
    }
Referenced by get().
Member Function Documentation
attack()
void com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.attack (Npc attacker, Mob defender, Hit hit)
Definition at line 29 of file NpcMeleeStrategy.java.
{
        if (!attacker.definition.isPoisonous()) {
            return;
        }
        if (CombatVenomEffect.isVenomous(attacker) && RandomUtils.success(0.25)) {
            defender.venom();
        } else {
            CombatPoisonEffect.getPoisonType(attacker.id).ifPresent(defender::poison);
        }
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.hit(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.isPoisonous(), com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.isVenomous(), com.runehive.util.RandomUtils.success(), and com.runehive.game.world.entity.mob.Mob.venom().
canAttack()
boolean com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.canAttack (Npc attacker, Mob defender)
Reimplemented in com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.ScorpiaGuardian.
Definition at line 64 of file NpcMeleeStrategy.java.
{
        return true;
    }
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.canAttack().
get()
NpcMeleeStrategy com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.get () static
Definition at line 73 of file NpcMeleeStrategy.java.
{
        return INSTANCE;
    }
References INSTANCE, and NpcMeleeStrategy().
Referenced by com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.[static initializer](), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.[static initializer](), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.[static initializer](), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.[static initializer](), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.[static initializer](), com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.canAttack(), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.canAttack(), com.runehive.content.activity.infernomobs.JalTokJad.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.finishOutgoing(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.ChaosFanatic.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.CrazyArchaeologist.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.Skotizo.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.finishOutgoing(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.LizardShaman(), com.runehive.game.world.entity.mob.npc.NpcAssistant.loadStrategy(), com.runehive.game.world.entity.mob.npc.NpcAssistant.login(), com.runehive.game.world.entity.combat.attack.listener.npc.AgrithNaNa.start(), com.runehive.game.world.entity.combat.attack.listener.npc.CommanderZilyana.start(), com.runehive.game.world.entity.combat.attack.listener.npc.DarkBeast.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Dessourt.start(), com.runehive.game.world.entity.combat.attack.listener.npc.dragon.MetalicDragon.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Flambleed.start(), com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.start(), com.runehive.game.world.entity.combat.attack.listener.npc.Karamel.start(), com.runehive.game.world.entity.combat.attack.listener.npc.KetZek.start(), com.runehive.game.world.entity.mob.Mob.transform(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.withinDistance().
getAttackAnimation()
Animation com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getAttackAnimation (Npc attacker, Mob defender)
Reimplemented in com.runehive.content.activity.infernomobs.JalAk.CrushMelee, com.runehive.content.activity.infernomobs.Jalimkot.Melee, com.runehive.content.activity.infernomobs.JalTokJad.MeleeAttack, com.runehive.content.activity.infernomobs.JaxXil.Melee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.CrushMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.StabMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.CrushMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.StabMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.Melee, com.runehive.game.world.entity.combat.attack.listener.npc.GeneralGraardor.MeleeAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.SlashMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.StabMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MeleeAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Earthquake, com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Melee, and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.
Definition at line 59 of file NpcMeleeStrategy.java.
{
        return new Animation(attacker.definition.getAttackAnimation(), UpdatePriority.HIGH);
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackAnimation(), and com.runehive.game.UpdatePriority.HIGH.
Referenced by start().
getAttackDelay()
int com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getAttackDelay (Npc attacker, Mob defender, FightType fightType)
Reimplemented in com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa, and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.
Definition at line 42 of file NpcMeleeStrategy.java.
{
        return attacker.definition.getAttackDelay();
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, and com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackDelay().
getAttackDistance()
int com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getAttackDistance (Npc attacker, FightType fightType)
Reimplemented in com.runehive.content.activity.infernomobs.JalAk.CrushMelee, com.runehive.content.activity.infernomobs.JaxXil.Melee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.CrushMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.StabMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.CrushMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.StabMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.SlashMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.StabMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Melee, and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.
Definition at line 47 of file NpcMeleeStrategy.java.
{
/*        final NpcDefinition definition = attacker.definition;
        return definition == null ? 1 : definition.getSize();*/
        return 1;
    }
getCombatType()
CombatType com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getCombatType ()
Reimplemented from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
Definition at line 69 of file NpcMeleeStrategy.java.
{
        return CombatType.MELEE;
    }
References com.runehive.game.world.entity.combat.CombatType.MELEE.
getHits()
CombatHit[] com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getHits (Npc attacker, Mob defender)
Reimplemented in com.runehive.content.activity.infernomobs.JalAk.CrushMelee, com.runehive.content.activity.infernomobs.Jalimkot.Burrow, com.runehive.content.activity.infernomobs.Jalimkot.Melee, com.runehive.content.activity.infernomobs.JalTokJad.MeleeAttack, com.runehive.content.activity.infernomobs.JaxXil.Melee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.CrushMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.BrutalDragon.StabMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.CrushMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.ChromaticDragon.StabMelee, com.runehive.game.world.entity.combat.attack.listener.npc.dragon.SkeletalWyvern.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa, com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.CorporealBeast.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.SlashMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.CrushMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.KingBlackDragonStrategy.StabMelee, com.runehive.game.world.entity.combat.strategy.npc.boss.kril.Tstanon, com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.Melee, com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MeleeAttack, com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Earthquake, com.runehive.game.world.entity.combat.strategy.npc.boss.Wyrm.Melee, and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.
Definition at line 54 of file NpcMeleeStrategy.java.
{
        return new CombatHit[]{nextMeleeHit(attacker, defender)};
    }
References com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit().
start()
void com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.start (Npc attacker, Mob defender, Hit[] hits)
Reimplemented in com.runehive.content.activity.infernomobs.Jalimkot.Burrow, and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.
Definition at line 24 of file NpcMeleeStrategy.java.
{
        attacker.animate(getAttackAnimation(attacker, defender), true);
    }
References com.runehive.game.world.entity.mob.Mob.animate(), and getAttackAnimation().
Member Data Documentation
INSTANCE
final NpcMeleeStrategy com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.INSTANCE = new NpcMeleeStrategy() static private
Definition at line 18 of file NpcMeleeStrategy.java.
Referenced by get().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/NpcMeleeStrategy.java