RuneHive-Game: com.runehive.game.engine.sync.task.NpcPostUpdateTask Class Reference
com.runehive.game.engine.sync.task.NpcPostUpdateTask Class Reference
Public Member Functions
NpcPostUpdateTask (Npc npc)
void run ()
Private Attributes
final Npc npc
Static Private Attributes
static final Logger logger = LogManager.getLogger(NpcPostUpdateTask.class)
Detailed Description
Definition at line 7 of file NpcPostUpdateTask.java.
Constructor & Destructor Documentation
NpcPostUpdateTask()
com.runehive.game.engine.sync.task.NpcPostUpdateTask.NpcPostUpdateTask (Npc npc)
Definition at line 13 of file NpcPostUpdateTask.java.
{
        this.npc = npc;
    }
References npc.
Referenced by run().
Member Function Documentation
run()
void com.runehive.game.engine.sync.task.NpcPostUpdateTask.run ()
Definition at line 18 of file NpcPostUpdateTask.java.
                      {
        try {
            npc.updateFlags.clear();
            npc.resetAnimation();
            npc.resetGraphic();
            npc.clearTeleportTarget();
            npc.positionChange = false;
            npc.regionChange = false;
            npc.teleportRegion = false;
        } catch (Exception ex) {
            logger.error(String.format("Error in %s", NpcPostUpdateTask.class.getSimpleName()), ex);
        }
    }
References logger, npc, and NpcPostUpdateTask().
Member Data Documentation
logger
final Logger com.runehive.game.engine.sync.task.NpcPostUpdateTask.logger = LogManager.getLogger(NpcPostUpdateTask.class) static private
Definition at line 9 of file NpcPostUpdateTask.java.
Referenced by run().
npc
final Npc com.runehive.game.engine.sync.task.NpcPostUpdateTask.npc private
Definition at line 11 of file NpcPostUpdateTask.java.
Referenced by NpcPostUpdateTask(), and run().
The documentation for this class was generated from the following file:
java/com/runehive/game/engine/sync/task/NpcPostUpdateTask.java