RuneHive-Game: com.runehive.content.itemaction.impl.CrawsBow Class Reference
com.runehive.content.itemaction.impl.CrawsBow Class Reference
Public Member Functions
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
String message (Item item)
The message of the action.
String toString ()
Static Public Attributes
static final short CRAWS_CHARGED_ID = 22550
static final short CRAWS_UNCHARGED_ID = 22547
static final short ETHER_ID = 21820
Private Member Functions
void charge (Player player, int amount)
void check (Player player)
Detailed Description
Definition at line 10 of file CrawsBow.java.
Member Function Documentation
charge()
void com.runehive.content.itemaction.impl.CrawsBow.charge (Player player, int amount) private
Definition at line 93 of file CrawsBow.java.
{
        if (amount > player.inventory.computeAmountForId(ETHER_ID)) {
            amount = player.inventory.computeAmountForId(ETHER_ID);
        }
        if (amount > 0) {
            player.inventory.remove(ETHER_ID, amount);
            player.inventory.refresh();
            player.crawsBowCharges += amount;
            player.message("You added " + amount + " charges to your "+name()+"");
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), ETHER_ID, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), and com.runehive.game.world.items.containers.ItemContainer.remove().
Referenced by itemOnItem().
check()
void com.runehive.content.itemaction.impl.CrawsBow.check (Player player) private
Definition at line 89 of file CrawsBow.java.
{
        player.message("You have " + Utility.formatDigits(player.crawsBowCharges) + " charges in your "+name()+".");
    }
References com.runehive.game.world.entity.mob.player.Player.crawsBowCharges, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.entity.mob.player.Player.message(), and name().
Referenced by equipment(), and inventory().
drop()
boolean com.runehive.content.itemaction.impl.CrawsBow.drop (Player player, Item item)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 74 of file CrawsBow.java.
{
        if (item.getId() != CRAWS_CHARGED_ID) {
            return false;
        }
        player.inventory.remove(CRAWS_CHARGED_ID);
        player.inventory.add(CRAWS_UNCHARGED_ID, 1);
        player.inventory.add(ETHER_ID, 1000 + player.crawsBowCharges);
        player.crawsBowCharges = 0;
        player.message("You uncharge your "+name()+".");
        return true;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), CRAWS_CHARGED_ID, CRAWS_UNCHARGED_ID, com.runehive.game.world.entity.mob.player.Player.crawsBowCharges, ETHER_ID, com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), and com.runehive.game.world.items.containers.ItemContainer.remove().
equipment()
boolean com.runehive.content.itemaction.impl.CrawsBow.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 62 of file CrawsBow.java.
{
        if (item.getId() != CRAWS_CHARGED_ID) {
            return false;
        }
        if (opcode == 1) {
            check(player);
            return true;
        }
        return true;
    }
References check(), CRAWS_CHARGED_ID, and com.runehive.game.world.items.Item.getId().
inventory()
boolean com.runehive.content.itemaction.impl.CrawsBow.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 48 of file CrawsBow.java.
{
        if (item.getId() != CRAWS_CHARGED_ID) {
            return false;
        }
        if (opcode == 2) {
            check(player);
            return true;
        }
        return false;
    }
References check(), CRAWS_CHARGED_ID, and com.runehive.game.world.items.Item.getId().
itemOnItem()
boolean com.runehive.content.itemaction.impl.CrawsBow.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 22 of file CrawsBow.java.
{
        if ((first.getId() != CRAWS_UNCHARGED_ID && second.getId() != CRAWS_UNCHARGED_ID) && (first.getId() != CRAWS_CHARGED_ID && second.getId() != CRAWS_CHARGED_ID)) {
            return false;
        }
        if(first.getId() == ETHER_ID || second.getId() == ETHER_ID) {
            if (first.getId() == CRAWS_UNCHARGED_ID || second.getId() == CRAWS_UNCHARGED_ID) {
                if(!player.inventory.contains(ETHER_ID, 1000)) {
                    player.message("You need at least 1000 "+ ItemDefinition.get(ETHER_ID).getName() +" to charge the "+name()+".");
                    return true;
                }
                player.inventory.remove(ETHER_ID, 1000);
                player.inventory.remove(CRAWS_UNCHARGED_ID);
                player.inventory.add(CRAWS_CHARGED_ID, 1);
                player.inventory.refresh();
            } else {
                System.out.println("Recharge craws bow");
                player.send(new SendInputAmount("How many charges would you like add? (0-"+player.inventory.computeAmountForId(ETHER_ID)+")", 10, input -> charge(player, Integer.parseInt(input))));
            }
            return true;
        }
        return false;
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), charge(), com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), CRAWS_CHARGED_ID, CRAWS_UNCHARGED_ID, ETHER_ID, com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.ItemDefinition.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), name(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), and com.runehive.game.world.entity.mob.player.Player.send().
name()
String com.runehive.content.itemaction.impl.CrawsBow.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 17 of file CrawsBow.java.
{
        return "Craw's bow";
    }
Referenced by charge(), check(), drop(), and itemOnItem().
Member Data Documentation
CRAWS_CHARGED_ID
final short com.runehive.content.itemaction.impl.CrawsBow.CRAWS_CHARGED_ID = 22550 static
Definition at line 13 of file CrawsBow.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.attack(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), com.runehive.content.itemaction.ItemActionRepository.declare(), drop(), equipment(), inventory(), and itemOnItem().
CRAWS_UNCHARGED_ID
final short com.runehive.content.itemaction.impl.CrawsBow.CRAWS_UNCHARGED_ID = 22547 static
Definition at line 12 of file CrawsBow.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.content.itemaction.ItemActionRepository.declare(), drop(), and itemOnItem().
ETHER_ID
final short com.runehive.content.itemaction.impl.CrawsBow.ETHER_ID = 21820 static
Definition at line 14 of file CrawsBow.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), charge(), drop(), and itemOnItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/CrawsBow.java