RuneHive-Game: com.runehive.content.gambling.impl.FlowerPoker Class Reference
com.runehive.content.gambling.impl.FlowerPoker Class Reference
Classes
enum Ranking
Public Member Functions
FlowerPoker (Player host, Player opponent)
void gamble ()
String toString ()
Public Member Functions inherited from com.runehive.content.gambling.Gamble
Gamble (Player host, Player opponent)
Player getHost ()
Player getOpponent ()
Private Member Functions
void plant (Task gambleTask)
Static Private Member Functions
static Map< Integer, Integer > getPairs (ArrayList< Flowers > list)
static Ranking getRank (Player player)
Additional Inherited Members
Public Attributes inherited from com.runehive.content.gambling.Gamble
int hostScore
Score betwen the players inside the 'gamble'.
int opponentScore
Detailed Description
Definition at line 20 of file FlowerPoker.java.
Constructor & Destructor Documentation
FlowerPoker()
com.runehive.content.gambling.impl.FlowerPoker.FlowerPoker (Player host, Player opponent)
Definition at line 22 of file FlowerPoker.java.
{
        super(host, opponent);
    }
References com.runehive.content.gambling.Gamble.host, and com.runehive.content.gambling.Gamble.opponent.
Member Function Documentation
gamble()
void com.runehive.content.gambling.impl.FlowerPoker.gamble ()
Reimplemented from com.runehive.content.gambling.Gamble.
Definition at line 32 of file FlowerPoker.java.
{
        getHost().getGambling().getFlowers().clear();
        getOpponent().getGambling().getFlowers().clear();
        getHost().getGambling().getGameFlowers().clear();
        getOpponent().getGambling().getGameFlowers().clear();
        for (int i = 0; i < 5; i++) {
            Flowers hostFlower = Flowers.values()[Utility.random(Flowers.values().length - 1)];
            Flowers opponentFlower = Flowers.values()[Utility.random(Flowers.values().length - 1)];
            while (hostFlower == Flowers.BLACK || hostFlower == Flowers.WHITE) {
                hostFlower = Flowers.values()[Utility.random(Flowers.values().length - 1)];
            }
            while (opponentFlower == Flowers.BLACK || hostFlower == Flowers.WHITE) {
                opponentFlower = Flowers.values()[Utility.random(Flowers.values().length - 1)];
            }
            getHost().getGambling().getFlowers().add(hostFlower);
            getOpponent().getGambling().getFlowers().add(opponentFlower);
        }
        final Ranking hostResult = getRank(getHost());
        final Ranking opponentResult = getRank(getOpponent());
        System.out.println("Looking for place to play");
        boolean[] canPlay = { false, false };
        Position positionOne, positionTwo;
        do {
            int maxX = GAMBLING_ZONE.getMaximumX() - GAMBLING_ZONE.getMinimumX();
            int maxY = GAMBLING_ZONE.getMaximumY() - GAMBLING_ZONE.getMinimumY();
            System.out.println("maxX: " + maxX + ", " + maxY);
            positionOne = new Position(GAMBLING_ZONE.getMinimumX() + Utility.random(maxX), GAMBLING_ZONE.getMinimumY() + Utility.random(maxY));
            positionTwo = positionOne.create(positionOne.getX() + 1, positionOne.getY());
            canPlay[0] = getHost().getGambling().canPlayFlowerPokerAtPositon(getHost(), positionTwo);
            canPlay[1] = getHost().getGambling().canPlayFlowerPokerAtPositon(getHost(), positionOne);
            System.out.println(canPlay[0] + " - " + canPlay[1]);
        } while(canPlay[0] == false || canPlay[1] == false);
        System.out.println("Found a place to play");
        Position finalPositionOne = positionOne;
        Position finalPositionTwo = positionTwo;
        World.schedule(new Task(1) {
            int time = 0;
            @Override
            protected void execute() {
                if(getHost().getGambling().getStage() != GambleStage.IN_PROGRESS) {
                    cancel();
                    return;
                }
                switch (time) {
                    case 0:
                        getHost().move(finalPositionOne);
                        getOpponent().move(finalPositionTwo);
                        break;
                    case 1:
                        plant(this);
                        break;
                    case 29:
                        getHost().speak("I got " + hostResult.name().toLowerCase().replaceAll("_", " "));
                        getOpponent().speak("I got " + opponentResult.name().toLowerCase().replaceAll("_", " "));
                        break;
                    case 30:
                        getHost().getGambling().finish(getHost(), getOpponent(), hostResult.ordinal(), opponentResult.ordinal());
                        cancel();
                        break;
                }
                time++;
            }
        });
    }
References com.runehive.content.gambling.Flowers.BLACK, com.runehive.content.gambling.GambleManager.canPlayFlowerPokerAtPositon(), com.runehive.game.world.position.Position.create(), com.runehive.content.gambling.GambleManager.finish(), com.runehive.content.gambling.GambleManager.getFlowers(), com.runehive.game.world.entity.mob.player.Player.getGambling(), com.runehive.content.gambling.GambleManager.getGameFlowers(), com.runehive.content.gambling.Gamble.getHost(), com.runehive.content.gambling.Gamble.getOpponent(), getRank(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.content.gambling.GambleStage.IN_PROGRESS, com.runehive.game.world.entity.mob.Mob.move(), plant(), com.runehive.util.Utility.random(), com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.Mob.speak(), and com.runehive.content.gambling.Flowers.WHITE.
getPairs()
Map< Integer, Integer > com.runehive.content.gambling.impl.FlowerPoker.getPairs (ArrayList< Flowers > list) static private
Definition at line 227 of file FlowerPoker.java.
{
        Map<Integer, Integer> finalPairs = new HashMap<Integer, Integer>();
        int[] pairs = new int[14];
        for (Flowers flower : list) {
            pairs[flower.ordinal()]++;
        }
        int slot = 0;
        for (int i = 0; i < pairs.length; i++) {
            if (pairs[i] >= 2) {
                finalPairs.put(slot, pairs[i]);
                slot++;
            }
        }
        return finalPairs;
    }
Referenced by getRank().
getRank()
Ranking com.runehive.content.gambling.impl.FlowerPoker.getRank (Player player) static private
Definition at line 188 of file FlowerPoker.java.
{
        ArrayList<Flowers> flowers = new ArrayList<Flowers>();
        flowers.addAll(player.getGambling().getFlowers());
        Collections.sort(flowers);
        Map<Integer, Integer> pairs = getPairs(flowers);
        for (int i = 0; i < pairs.size(); i++) {
            if (pairs.get(i) == null) {
                continue;
            }
            if (pairs.get(i).intValue() == 5) {
                return Ranking.ROYAL_KIND;
            }
        }
        if (pairs.size() == 2) {
            if ((pairs.get(0).intValue() == 3 && pairs.get(1).intValue() == 2) || (pairs.get(1).intValue() == 3 && pairs.get(0).intValue() == 2)) {
                return Ranking.FULL_HOUSE;
            }
        }
        int totalPairs = 0;
        for (int i = 0; i < pairs.size(); i++) {
            if (pairs.get(i) == null) {
                continue;
            }
            if (pairs.get(i).intValue() == 3) {
                return Ranking.THREE_OF_KIND;
            }
            if (pairs.get(i).intValue() == 2) {
                totalPairs++;
            }
        }
        if (totalPairs == 2) {
            return Ranking.TWO_PAIR;
        }
        if (totalPairs == 1) {
            return Ranking.PAIR;
        }
        return Ranking.NOTHING;
    }
References com.runehive.content.gambling.impl.FlowerPoker.Ranking.FULL_HOUSE, com.runehive.content.gambling.GambleManager.getFlowers(), com.runehive.game.world.entity.mob.player.Player.getGambling(), getPairs(), com.runehive.content.gambling.impl.FlowerPoker.Ranking.NOTHING, com.runehive.content.gambling.impl.FlowerPoker.Ranking.PAIR, com.runehive.content.gambling.impl.FlowerPoker.Ranking.ROYAL_KIND, com.runehive.content.gambling.impl.FlowerPoker.Ranking.THREE_OF_KIND, and com.runehive.content.gambling.impl.FlowerPoker.Ranking.TWO_PAIR.
Referenced by gamble().
plant()
void com.runehive.content.gambling.impl.FlowerPoker.plant (Task gambleTask) private
Definition at line 107 of file FlowerPoker.java.
{
        World.schedule(new Task(1) {
            int time = 0;
            int type = 0;
            Flowers hostFlower = getHost().getGambling().getFlowers().get(type);
            Flowers opponentFlower = getOpponent().getGambling().getFlowers().get(type);
            Player[] players = new Player[] { getHost(), getOpponent() };
            @Override
            protected void execute() {
                if(getHost().getGambling().getStage() != GambleStage.IN_PROGRESS) {
                    cancel();
                    return;
                }
                switch (time) {
                    case 1:
                        for(Player player : players)
                            player.animate(827);
                        break;
                    case 2:
                        hostFlower = getHost().getGambling().getFlowers().get(type);
                        opponentFlower = getOpponent().getGambling().getFlowers().get(type);
                        if (hostFlower == null || opponentFlower == null) {
                            cancel();
                            break;
                        }
                        for(Player player : players) {
                            Flowers flowers = player.equals(getHost()) ? hostFlower : opponentFlower;
                            final CustomGameObject gameFlower = new CustomGameObject(flowers.getId(), player.getPosition().copy());
                            gameFlower.register();
                            player.getGambling().getGameFlowers().add(gameFlower);
                            player.movement.walkTo(player.getPosition().south());
                        }
                        break;
                    case 3:
                        for(Player player : players) {
                            Flowers flowers = player.equals(getHost()) ? hostFlower : opponentFlower;
                            player.speak("I planted a " + Utility.formatText(flowers.name().toLowerCase()) + " flower.");
                        }
                        break;
                    case 4:
                        if(hostFlower.name().equalsIgnoreCase("WHITE") || hostFlower.name().equalsIgnoreCase("BLACK") ||
                           opponentFlower.name().equalsIgnoreCase("WHITE") || opponentFlower.name().equalsIgnoreCase("BLACK")) {
                            getHost().getGambling().finish(getHost(), getOpponent(), 0, 0);
                            gambleTask.cancel();
                            cancel();
                            break;
                        }
                        if (type == 4) {
                            cancel();
                            break;
                        }
                        time = 0;
                        type++;
                        break;
                }
                time++;
            }
        });
    }
References com.runehive.game.task.Task.cancel(), com.runehive.content.gambling.GambleManager.finish(), com.runehive.util.Utility.formatText(), com.runehive.content.gambling.GambleManager.getFlowers(), com.runehive.game.world.entity.mob.player.Player.getGambling(), com.runehive.content.gambling.Gamble.getHost(), com.runehive.content.gambling.Flowers.getId(), com.runehive.content.gambling.Gamble.getOpponent(), com.runehive.content.gambling.GambleStage.IN_PROGRESS, com.runehive.game.world.object.CustomGameObject.register(), and com.runehive.game.world.World.schedule().
Referenced by gamble().
toString()
String com.runehive.content.gambling.impl.FlowerPoker.toString ()
Definition at line 27 of file FlowerPoker.java.
{
        return "Flower Poker";
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/gambling/impl/FlowerPoker.java