RuneHive-Game: com.runehive.content.lms.lobby.LMSLobby Class Reference
com.runehive.content.lms.lobby.LMSLobby Class Reference
Static Public Member Functions
static String getGameTypeName ()
static void joinLobby (Player player)
Handles joining the lobby.
static void leaveLobby (Player player, boolean logout)
Handles leaving the lobby.
Static Public Attributes
static LMSLoadout currentGameType
The current game type.
static boolean DEVELOPMENT_MODE = false
static Position finish = new Position(3141, 3634, 0)
The position the player gets put on when finishing a game.
static List< Player > lobbyMembers = new ArrayList<>()
A list with all the players in the lobby.
static int maxPlayers = 24
The max amount of players allowed in a single game.
static int requiredPlayers = DEVELOPMENT_MODE ? 2 : 4
The amount of players in the lobby required.
Detailed Description
Definition at line 16 of file LMSLobby.java.
Member Function Documentation
getGameTypeName()
String com.runehive.content.lms.lobby.LMSLobby.getGameTypeName () static
Definition at line 45 of file LMSLobby.java.
{
        return currentGameType.getClass().getSimpleName();
    }
References currentGameType.
joinLobby()
void com.runehive.content.lms.lobby.LMSLobby.joinLobby (Player player) static
Handles joining the lobby.
Parameters
player
Definition at line 53 of file LMSLobby.java.
{
        if(lobbyMembers.size() >= maxPlayers) {
            //TODO: Make a dialogue
            return;
        }
        if (LMSGame.isActivePlayer(player)) return;
        if (player.pet != null) {
            //TODO: Make a dialogue
            return;
        }
        if(!lobbyMembers.contains(player))
            lobbyMembers.add(player);
        player.move(player.getPosition().north());
        if(LMSGame.gameInProgress)
            player.message("A game is currently on-going and should end shortly.");
        //Handles making a copy of the spellbook
        player.spellbook_copy = player.spellbook;
        //Handles making a copy of the inventory
        player.inventory_copy.set(player.inventory.getItems().clone());
        player.inventory.clear();
        player.inventory.refresh();
        //Handles making a copy of the equipment
        player.equipment_copy.set(player.equipment.getItems().clone());
        player.equipment.clear();
        player.equipment.refresh();
        player.equipment.updateAnimation();
        WeaponInterface.execute(player, player.equipment.getWeapon());
        //Handles making a copy of the rune pouch
        player.runePouch_copy.clear(false);
        for(Item rune : player.runePouch.runes)
            player.runePouch_copy.runes.add(new Item(rune.getId(), rune.getAmount()));
        player.runePouch.clear(false);
        //Handles making a copy of the skills
        for(int index = 0; index < player.skills.getSkills().length; index++) {
            Skill skill = player.skills_copy.get(index);
            Skill real_skill = player.skills.get(index);
            skill.setLevel(real_skill.getLevel());
            skill.setMaxLevel(real_skill.getMaxLevel());
            skill.setExperience(skill.getExperienceForLevel(real_skill.getLevel()));
        }
        player.skills_copy.experienceCounter = player.skills.experienceCounter;
        player.updateFlags.add(UpdateFlag.APPEARANCE);
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.skill.impl.magic.RunePouch.clear(), com.runehive.game.world.items.containers.equipment.Equipment.clear(), com.runehive.game.world.items.containers.ItemContainer.clear(), com.runehive.game.world.items.Item.clone(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.equipment_copy, com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.game.world.entity.skill.SkillManager.experienceCounter, com.runehive.content.lms.LMSGame.gameInProgress, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.entity.skill.Skill.getLevel(), com.runehive.game.world.entity.skill.Skill.getMaxLevel(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.skill.SkillManager.getSkills(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.inventory_copy, com.runehive.content.lms.LMSGame.isActivePlayer(), lobbyMembers, maxPlayers, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.world.position.Position.north(), com.runehive.game.world.entity.mob.player.Player.pet, com.runehive.game.world.items.containers.equipment.Equipment.refresh(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.entity.mob.player.Player.runePouch, com.runehive.game.world.entity.mob.player.Player.runePouch_copy, com.runehive.content.skill.impl.magic.RunePouch.runes, com.runehive.game.world.items.containers.ItemContainer.set(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.mob.Mob.skills_copy, com.runehive.game.world.entity.mob.player.Player.spellbook, com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation(), and com.runehive.game.world.entity.mob.Mob.updateFlags.
leaveLobby()
void com.runehive.content.lms.lobby.LMSLobby.leaveLobby (Player player, boolean logout) static
Handles leaving the lobby.
Parameters
player
Definition at line 114 of file LMSLobby.java.
{
        lobbyMembers.remove(player);
        //Sets back the players old inventory
        player.inventory.set(player.inventory_copy.getItems().clone());
        player.inventory_copy.clear();
        player.inventory.refresh();
        //Sets back the players old equipment
        player.equipment.set(player.equipment_copy.getItems().clone());
        player.equipment_copy.clear();
        player.equipment.refresh();
        player.equipment.updateAnimation();
        WeaponInterface.execute(player, player.equipment.getWeapon());
        //Sets back the old rune pouch
        player.runePouch.clear();
        for(Item rune : player.runePouch_copy.runes)
            player.runePouch.runes.add(new Item(rune.getId(), rune.getAmount()));
        player.runePouch_copy.clear(false);
        player.updateFlags.add(UpdateFlag.APPEARANCE);
        if(logout)
            player.move(new Position(finish.getX() + Utility.random(1), finish.getY() + Utility.random(3), 0));
        else {
            int diffX = player.getPosition().getX() >= 3142 ? 3142 - player.getPosition().getX() : 3141 - player.getPosition().getX();
            int diffY = 3638 - player.getPosition().getY();
            player.move(player.getPosition().copy().transform(diffX, diffY, 0));
        }
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.skill.impl.magic.RunePouch.clear(), com.runehive.game.world.items.containers.equipment.Equipment.clear(), com.runehive.game.world.items.containers.ItemContainer.clear(), com.runehive.game.world.items.Item.clone(), com.runehive.game.world.position.Position.copy(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.equipment_copy, com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), finish, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.containers.ItemContainer.getItems(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.inventory_copy, lobbyMembers, com.runehive.game.world.entity.mob.Mob.move(), com.runehive.util.Utility.random(), com.runehive.game.world.items.containers.equipment.Equipment.refresh(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.entity.mob.player.Player.runePouch, com.runehive.game.world.entity.mob.player.Player.runePouch_copy, com.runehive.content.skill.impl.magic.RunePouch.runes, com.runehive.game.world.items.containers.ItemContainer.set(), com.runehive.game.world.position.Position.transform(), com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation(), and com.runehive.game.world.entity.mob.Mob.updateFlags.
Member Data Documentation
currentGameType
LMSLoadout com.runehive.content.lms.lobby.LMSLobby.currentGameType static
The current game type.
Definition at line 43 of file LMSLobby.java.
Referenced by getGameTypeName(), com.runehive.content.lms.loadouts.LMSLoadoutManager.load(), com.runehive.content.lms.LMSGame.moveToGame(), and com.runehive.game.world.entity.mob.player.Player.sequence().
DEVELOPMENT_MODE
boolean com.runehive.content.lms.lobby.LMSLobby.DEVELOPMENT_MODE = false static
Definition at line 18 of file LMSLobby.java.
finish
Position com.runehive.content.lms.lobby.LMSLobby.finish = new Position(3141, 3634, 0) static
The position the player gets put on when finishing a game.
Definition at line 23 of file LMSLobby.java.
Referenced by leaveLobby(), and com.runehive.content.lms.LMSGame.reset().
lobbyMembers
List<Player> com.runehive.content.lms.lobby.LMSLobby.lobbyMembers = new ArrayList<>() static
A list with all the players in the lobby.
Definition at line 28 of file LMSLobby.java.
Referenced by com.runehive.content.lms.lobby.LMSLobbyEvent.execute(), joinLobby(), leaveLobby(), com.runehive.game.world.entity.mob.player.Player.sequence(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
maxPlayers
int com.runehive.content.lms.lobby.LMSLobby.maxPlayers = 24 static
The max amount of players allowed in a single game.
Definition at line 38 of file LMSLobby.java.
Referenced by joinLobby(), com.runehive.game.world.entity.mob.player.Player.sequence(), and com.runehive.content.lms.LMSGame.updateInterface().
requiredPlayers
int com.runehive.content.lms.lobby.LMSLobby.requiredPlayers = DEVELOPMENT_MODE ? 2 : 4 static
The amount of players in the lobby required.
Definition at line 33 of file LMSLobby.java.
Referenced by com.runehive.content.lms.lobby.LMSLobbyEvent.execute(), and com.runehive.game.world.entity.mob.player.Player.sequence().
The documentation for this class was generated from the following file:
java/com/runehive/content/lms/lobby/LMSLobby.java