RuneHive-Game: com.runehive.content.shootingstar.ShootingStarData Class Reference
com.runehive.content.shootingstar.ShootingStarData Class Reference
Public Member Functions
void decreaseDust (Player player)
Handles decreasing the dust for a star.
void decreaseLevel ()
Handles the decreasing of the star level.
void destruct ()
Handles removing the star from the game.
String getHint ()
The current hint of the star location.
int getLevel ()
Gets the random star level.
String getLocationName ()
The current location of the star.
int getMiningLevel ()
The required mining level for the star level.
int getObjectId ()
The current object id.
int getPercentage ()
Percentage till the next star level.
int getXPDrop ()
The xp the player gets for the current star.
ShootingStarData ()
Public Attributes
int availableDust
How much dust there currently is in the star.
int[] doubleChance = { 2, 6, 12, 20, 30, 42, 56, 72, 90 }
The chance of doubling stardust depending on the star level.
int maxDust
The max dust for this star level.
int[] possibleDust = { 1200, 700, 430, 250, 175, 80, 40, 40, 15 }
The amount of star dust the player receives for the different star levels.
int[] starIds = { 41229, 41228, 41227, 41226, 41225, 41224, 41223, 41021, }
All the possible object ids for the different star levels.
int starLevel
The current level of the star.
ShootingStarLocations starLocation
The current location of the star.
CustomGameObject starObject
The game object linked to the star.
int[] xpDrops = { 12, 22, 26, 31, 48, 74, 123, 162, 244 }
Possible xp drops for the differernt star levels.
Private Attributes
boolean decreaseDouble = false
See if the dust needs to be removed double.
Detailed Description
Definition at line 11 of file ShootingStarData.java.
Constructor & Destructor Documentation
ShootingStarData()
com.runehive.content.shootingstar.ShootingStarData.ShootingStarData ()
Definition at line 63 of file ShootingStarData.java.
{
        starLevel = getLevel();
        maxDust = possibleDust[starLevel];
        availableDust = maxDust;
        starLocation = ShootingStarLocations.values()[RandomUtils.inclusive(0, ShootingStarLocations.values().length - 1)];
        System.out.println("starLocation.starPosition " + starLocation.starPosition);
        starObject = new CustomGameObject(getObjectId(), starLocation.starPosition);
        starObject.register();
    }
References availableDust, getLevel(), getObjectId(), com.runehive.util.RandomUtils.inclusive(), maxDust, possibleDust, starLevel, starLocation, and starObject.
Member Function Documentation
decreaseDust()
void com.runehive.content.shootingstar.ShootingStarData.decreaseDust (Player player)
Handles decreasing the dust for a star.
Definition at line 77 of file ShootingStarData.java.
{
        player.skills.addExperience(Skill.MINING, getXPDrop() * Config.MINING_MODIFICATION);
        int amount = 1;
        //Handles the double stardust chance
        int roll = RandomUtils.inclusive(0, 100);
        if(roll <= doubleChance[starLevel]) amount *= 2;
        player.inventory.add(new Item(25527, amount));
        availableDust -= decreaseDouble ? amount : amount / 2;
        if(availableDust <= 0) {
            decreaseLevel();
            for(Player p : World.getPlayers()) {
                if(p == null || !(p.action.getCurrentAction() instanceof ShootingStarAction)) continue;
                System.out.println("Reset the mining action for all the players with a shooting star action...");
                p.action.cancel();
                p.resetFace();
                p.skills.get(Skill.MINING).setDoingSkill(false);
            }
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), availableDust, decreaseDouble, decreaseLevel(), doubleChance, com.runehive.game.world.World.getPlayers(), getXPDrop(), com.runehive.util.RandomUtils.inclusive(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.skill.Skill.MINING, com.runehive.Config.MINING_MODIFICATION, com.runehive.game.world.entity.mob.Mob.skills, and starLevel.
Referenced by com.runehive.content.shootingstar.ShootingStarAction.mine().
decreaseLevel()
void com.runehive.content.shootingstar.ShootingStarData.decreaseLevel ()
Handles the decreasing of the star level.
Definition at line 104 of file ShootingStarData.java.
{
        starLevel--;
        if(starLevel < 0) {
            destruct();
            return;
        }
        maxDust = possibleDust[starLevel];
        availableDust = maxDust;
        starObject.transform(getObjectId());
    }
References availableDust, destruct(), getObjectId(), maxDust, possibleDust, starLevel, and starObject.
Referenced by decreaseDust().
destruct()
void com.runehive.content.shootingstar.ShootingStarData.destruct ()
Handles removing the star from the game.
Definition at line 119 of file ShootingStarData.java.
{
        starObject.unregister();
        starObject = null;
    }
References starObject.
Referenced by decreaseLevel().
getHint()
String com.runehive.content.shootingstar.ShootingStarData.getHint ()
The current hint of the star location.
Returns
Definition at line 183 of file ShootingStarData.java.
{
        return starLocation.location[1];
    }
References starLocation.
getLevel()
int com.runehive.content.shootingstar.ShootingStarData.getLevel ()
Gets the random star level.
Returns
Definition at line 128 of file ShootingStarData.java.
{
        int[] chances = { 0, 16, 18, 20, 17, 12, 9, 5 }; //, 3
        for (int index = chances.length - 1; index > 0; index--) {
            int roll = RandomUtils.inclusive(0, 100);
            if (roll < chances[index])
                return index;
        }
        return 2;
    }
References com.runehive.util.RandomUtils.inclusive().
Referenced by ShootingStarData().
getLocationName()
String com.runehive.content.shootingstar.ShootingStarData.getLocationName ()
The current location of the star.
Returns
Definition at line 175 of file ShootingStarData.java.
{
        return starLocation.location[0];
    }
References starLocation.
getMiningLevel()
int com.runehive.content.shootingstar.ShootingStarData.getMiningLevel ()
The required mining level for the star level.
Returns
Definition at line 151 of file ShootingStarData.java.
{
        return (starLevel + 1) * 10;
    }
References starLevel.
Referenced by com.runehive.content.shootingstar.ShootingStarAction.mine().
getObjectId()
int com.runehive.content.shootingstar.ShootingStarData.getObjectId ()
The current object id.
Returns
Definition at line 143 of file ShootingStarData.java.
{
        return starIds[starLevel];
    }
References starIds, and starLevel.
Referenced by decreaseLevel(), and ShootingStarData().
getPercentage()
int com.runehive.content.shootingstar.ShootingStarData.getPercentage ()
Percentage till the next star level.
Returns
Definition at line 159 of file ShootingStarData.java.
{
        return (maxDust - availableDust) * 100 / maxDust;
    }
References availableDust, and maxDust.
getXPDrop()
int com.runehive.content.shootingstar.ShootingStarData.getXPDrop ()
The xp the player gets for the current star.
Returns
Definition at line 167 of file ShootingStarData.java.
{
        return xpDrops[starLevel];
    }
References starLevel, and xpDrops.
Referenced by decreaseDust().
Member Data Documentation
availableDust
int com.runehive.content.shootingstar.ShootingStarData.availableDust
How much dust there currently is in the star.
Definition at line 31 of file ShootingStarData.java.
Referenced by decreaseDust(), decreaseLevel(), getPercentage(), com.runehive.content.shootingstar.ShootingStarAction.mine(), and ShootingStarData().
decreaseDouble
boolean com.runehive.content.shootingstar.ShootingStarData.decreaseDouble = false private
See if the dust needs to be removed double.
Definition at line 16 of file ShootingStarData.java.
Referenced by decreaseDust().
doubleChance
int [] com.runehive.content.shootingstar.ShootingStarData.doubleChance = { 2, 6, 12, 20, 30, 42, 56, 72, 90 }
The chance of doubling stardust depending on the star level.
Definition at line 61 of file ShootingStarData.java.
{ 2, 6, 12, 20, 30, 42, 56, 72, 90 };
Referenced by decreaseDust().
maxDust
int com.runehive.content.shootingstar.ShootingStarData.maxDust
The max dust for this star level.
Definition at line 36 of file ShootingStarData.java.
Referenced by decreaseLevel(), getPercentage(), and ShootingStarData().
possibleDust
int [] com.runehive.content.shootingstar.ShootingStarData.possibleDust = { 1200, 700, 430, 250, 175, 80, 40, 40, 15 }
The amount of star dust the player receives for the different star levels.
Definition at line 46 of file ShootingStarData.java.
{ 1200, 700, 430, 250, 175, 80, 40, 40, 15 };
Referenced by decreaseLevel(), and ShootingStarData().
starIds
int [] com.runehive.content.shootingstar.ShootingStarData.starIds = { 41229, 41228, 41227, 41226, 41225, 41224, 41223, 41021, }
All the possible object ids for the different star levels.
Definition at line 41 of file ShootingStarData.java.
{ 41229, 41228, 41227, 41226, 41225, 41224, 41223, 41021,  };
Referenced by getObjectId().
starLevel
int com.runehive.content.shootingstar.ShootingStarData.starLevel
The current level of the star.
Definition at line 26 of file ShootingStarData.java.
Referenced by decreaseDust(), decreaseLevel(), getMiningLevel(), getObjectId(), getXPDrop(), and ShootingStarData().
starLocation
ShootingStarLocations com.runehive.content.shootingstar.ShootingStarData.starLocation
The current location of the star.
Definition at line 21 of file ShootingStarData.java.
Referenced by getHint(), getLocationName(), and ShootingStarData().
starObject
CustomGameObject com.runehive.content.shootingstar.ShootingStarData.starObject
The game object linked to the star.
Definition at line 56 of file ShootingStarData.java.
Referenced by decreaseLevel(), destruct(), and ShootingStarData().
xpDrops
int [] com.runehive.content.shootingstar.ShootingStarData.xpDrops = { 12, 22, 26, 31, 48, 74, 123, 162, 244 }
Possible xp drops for the differernt star levels.
Definition at line 51 of file ShootingStarData.java.
{ 12, 22, 26, 31, 48, 74, 123, 162, 244 };
Referenced by getXPDrop().
The documentation for this class was generated from the following file:
java/com/runehive/content/shootingstar/ShootingStarData.java