RuneHive-Game: com.runehive.game.engine.sync.task.PlayerUpdateTask Class Reference
com.runehive.game.engine.sync.task.PlayerUpdateTask Class Reference
Public Member Functions
PlayerUpdateTask (Player player)
void run ()
Private Attributes
final Player player
Static Private Attributes
static final Logger logger = LogManager.getLogger(PlayerUpdateTask.class)
Detailed Description
Definition at line 9 of file PlayerUpdateTask.java.
Constructor & Destructor Documentation
PlayerUpdateTask()
com.runehive.game.engine.sync.task.PlayerUpdateTask.PlayerUpdateTask (Player player)
Definition at line 15 of file PlayerUpdateTask.java.
{
        this.player = player;
    }
References player.
Referenced by run().
Member Function Documentation
run()
void com.runehive.game.engine.sync.task.PlayerUpdateTask.run ()
Definition at line 20 of file PlayerUpdateTask.java.
                      {
        try {
            if (player == null) {
                return;
            }
            player.send(new SendPlayerUpdate());
        } catch (Exception ex) {
            logger.fatal(String.format("Error in %s %s", PlayerUpdateTask.class.getSimpleName(), player), ex);
        }
    }
References logger, player, and PlayerUpdateTask().
Member Data Documentation
logger
final Logger com.runehive.game.engine.sync.task.PlayerUpdateTask.logger = LogManager.getLogger(PlayerUpdateTask.class) static private
Definition at line 11 of file PlayerUpdateTask.java.
Referenced by run().
player
final Player com.runehive.game.engine.sync.task.PlayerUpdateTask.player private
Definition at line 13 of file PlayerUpdateTask.java.
Referenced by PlayerUpdateTask(), and run().
The documentation for this class was generated from the following file:
java/com/runehive/game/engine/sync/task/PlayerUpdateTask.java