RuneHive-Game: com.runehive.content.dialogue.impl.ClanmasterDialogue Class Reference
com.runehive.content.dialogue.impl.ClanmasterDialogue Class Reference
Handles the clan master dialogue.
Public Member Functions
void sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Private Member Functions
void clanDefinition (DialogueFactory factory)
void clanInformation (DialogueFactory factory)
The clan information dialogue.
void clanLevel (Player player)
Displays all the clan level information.
void clanManagement (DialogueFactory factory)
The clan management dialogue.
void clanPerks (DialogueFactory factory)
void clanTask (ClanChannel channel, DialogueFactory factory)
The clan task dialogue.
void mainOptions (DialogueFactory factory)
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.dialogue.Dialogue
static final boolean isDialogueButton (int button)
Checks if the button triggered is an optional dialogue button.
Static Public Attributes inherited from com.runehive.content.dialogue.Dialogue
static final ImmutableList< Integer > DIALOGUE_BUTTONS = ImmutableList.of(2461, 2471, 2482, 2462, 2472, 2483, 2473, 2484, 2485, 2494, 2495, 2496, 2497, 2498)
The action buttons responsible for dialogues.
Detailed Description
Handles the clan master dialogue.
Author
Daniel
Definition at line 25 of file ClanmasterDialogue.java.
Member Function Documentation
clanDefinition()
void com.runehive.content.dialogue.impl.ClanmasterDialogue.clanDefinition (DialogueFactory factory) private
Definition at line 49 of file ClanmasterDialogue.java.
{
        factory.sendNpcChat(3841, "A clan is a united group or syndicate of players",
                "who work together to complete various tasks depending on the", "clan type. Clans members can identify one another",
                "by the purple dot on the minimap or their clan tag.");
    }
References com.runehive.content.dialogue.DialogueFactory.sendNpcChat().
Referenced by clanInformation().
clanInformation()
void com.runehive.content.dialogue.impl.ClanmasterDialogue.clanInformation (DialogueFactory factory) private
The clan information dialogue.
Definition at line 43 of file ClanmasterDialogue.java.
{
        factory.sendOption("What is a clan?", () -> clanDefinition(factory),
                "What are clan perks?", () -> clanPerks(factory),
                "Nevermind", factory::clear);
    }
References clanDefinition(), clanPerks(), and com.runehive.content.dialogue.DialogueFactory.sendOption().
Referenced by sendDialogues().
clanLevel()
void com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel (Player player) private
Displays all the clan level information.
Definition at line 117 of file ClanmasterDialogue.java.
{
        int size = ClanLevel.values().length;
        for (int index = 0, string = 37111; index < size; index++) {
            ClanLevel level = ClanLevel.values()[index];
            String color = "<col=" + level.getColor() + ">";
            String experience = "Experience: <col=7A6856>" + Utility.formatDigits(level.getExperience()) + "</col>";
            String points = "Points: <col=7A6856>" + Utility.formatDigits(level.getPoints()) + "</col>";
            player.send(new SendString(color + Utility.formatEnum(level.name()), string));
            string++;
            player.send(new SendString(experience + " <col=000000>|</col> " + points, string));
            string++;
            player.send(new SendString("", string));
            string++;
        }
        player.send(new SendString("", 37107));
        player.send(new SendString("Clan Levels Information", 37103));
        player.send(new SendScrollbar(37110, 750));
        player.send(new SendItemOnInterface(37199));
        player.interfaceManager.open(37100);
    }
References com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.formatEnum(), com.runehive.content.clanchannel.content.ClanLevel.getColor(), com.runehive.content.clanchannel.content.ClanLevel.getExperience(), com.runehive.content.clanchannel.content.ClanLevel.getPoints(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by sendDialogues().
clanManagement()
void com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement (DialogueFactory factory) private
The clan management dialogue.
Definition at line 65 of file ClanmasterDialogue.java.
{
        Player player = factory.getPlayer();
        ClanChannel channel = player.clanChannel;
        if (channel == null) {
            factory.sendNpcChat(3841, "You must be in a clan in order to do this!");
            return;
        }
        Optional<ClanMember> member = channel.getMember(player.getName());
        if (!member.isPresent() || !channel.canManage(member.get())) {
            factory.sendNpcChat(3841, "You do not have the proper authorization to manage", "the clan " + channel.getName() + "! If you want to manage your own clan", "please join your own clan and then speak to me again.");
            return;
        }
        factory.sendOption("View store", () -> Store.STORES.get("The Clanmaster's Store").open(player), "Manage tasks", () -> clanTask(channel, factory), "Nevermind", factory::clear);
    }
References com.runehive.content.clanchannel.channel.ClanChannel.canManage(), com.runehive.game.world.entity.mob.player.Player.clanChannel, clanTask(), com.runehive.content.clanchannel.channel.ClanChannel.getMember(), com.runehive.content.clanchannel.channel.ClanChannel.getName(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.store.Store.STORES.
Referenced by sendDialogues().
clanPerks()
void com.runehive.content.dialogue.impl.ClanmasterDialogue.clanPerks (DialogueFactory factory) private
Definition at line 55 of file ClanmasterDialogue.java.
{
        factory.sendNpcChat(3841,
                "I offer many perks and items to be used for clans.",
                "Clan perks affect all online clan members when used.",
                "These perks vary from rewarding everyone with",
                "random experience in a random skill to having a drop modifier");
        factory.sendNpcChat(3841, "for a certain amount of time.");
    }
References com.runehive.content.dialogue.DialogueFactory.sendNpcChat().
Referenced by clanInformation().
clanTask()
void com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask (ClanChannel channel, DialogueFactory factory) private
The clan task dialogue.
Definition at line 85 of file ClanmasterDialogue.java.
{
        ClanTask task = channel.getDetails().clanTask;
        factory.sendOption("Task Information", () -> {
            if (task == null) {
                factory.sendStatement("Your clan currently does not have a task assigned!");
                return;
            }
            factory.sendStatement("Your current task is to:", task.getName(channel));
        }, "Obtain Clan Task", () -> {
            if (task != null) {
                factory.sendNpcChat(3841, "Your clan currently has a task assigned!", "Cancel or complete it to obtain another one.");
                return;
            }
            factory.sendOption("Easy Task - <col=255>2 CP</col> Reward", () -> channel.receiveTask(Difficulty.EASY), "Medium Task - <col=255>3 CP</col> Reward", () -> channel.receiveTask(Difficulty.MEDIUM), "Hard Task - <col=255>5 CP</col> Reward", () -> channel.receiveTask(Difficulty.HARD));
        }, "Cancel Clan Task (<col=FF2929>5 CP</col>)", () -> {
            if (task == null) {
                factory.sendStatement("Your clan currently does not have a task assigned!");
                return;
            }
            if (channel.getDetails().points < 5) {
                factory.sendStatement("You do not have enough points to cancel your task.", "Current CP: " + channel.getDetails().points);
                return;
            }
            channel.getDetails().points -= 5;
            channel.getDetails().taskAmount = -1;
            channel.getDetails().clanTask = null;
            channel.message("Our clan task was cancelled for 25 CP. We have <col=255>" + Utility.formatDigits(channel.getDetails().points) + "</col> remaining.");
        }, "Nevermind", factory::clear);
    }
References com.runehive.content.clanchannel.channel.ClanDetails.clanTask, com.runehive.util.Difficulty.EASY, com.runehive.util.Utility.formatDigits(), com.runehive.content.clanchannel.channel.ClanChannel.getDetails(), com.runehive.content.clanchannel.content.ClanTask.getName(), com.runehive.util.Difficulty.HARD, com.runehive.util.Difficulty.MEDIUM, com.runehive.content.clanchannel.channel.ClanChannel.message(), com.runehive.content.clanchannel.channel.ClanDetails.points, com.runehive.content.clanchannel.channel.ClanChannel.receiveTask(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.content.dialogue.DialogueFactory.sendOption(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and com.runehive.content.clanchannel.channel.ClanDetails.taskAmount.
Referenced by clanManagement().
mainOptions()
void com.runehive.content.dialogue.impl.ClanmasterDialogue.mainOptions (DialogueFactory factory) private
Definition at line 39 of file ClanmasterDialogue.java.
{
    }
sendDialogues()
void com.runehive.content.dialogue.impl.ClanmasterDialogue.sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Parameters
factory The factory for this dialogue.
Reimplemented from com.runehive.content.dialogue.Dialogue.
Definition at line 28 of file ClanmasterDialogue.java.
{
        Player player = factory.getPlayer();
        factory.sendNpcChat(3841, "Ello mate!", "What can I do you for today?");
        factory.sendOption("Information on Clans", () -> clanInformation(factory),
                "World Clan List", () -> player.clanViewer.open(ClanViewer.ClanTab.OVERVIEW),
                "Clan Management", () -> clanManagement(factory),
                "Clan Levels", () -> clanLevel(factory.getPlayer()),
                "Nevermind", factory::clear);
        factory.execute();
    }
References clanInformation(), clanLevel(), clanManagement(), com.runehive.game.world.entity.mob.player.Player.clanViewer, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.clanchannel.content.ClanViewer.open(), com.runehive.content.clanchannel.content.ClanViewer.ClanTab.OVERVIEW, com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), and com.runehive.content.dialogue.DialogueFactory.sendOption().
The documentation for this class was generated from the following file:
java/com/runehive/content/dialogue/impl/ClanmasterDialogue.java