RuneHive-Game: com.runehive.content.dialogue.DialogueFactory Class Reference
com.runehive.content.dialogue.DialogueFactory Class Reference
Represents a factory class that contains important functions for building dialogues.
Public Member Functions
void clear ()
Clears the current dialogue chain.
DialogueFactory (Player player)
Creates a new DialogueFactory.
final DialogueFactory execute ()
Retrieves the next dialogue in the chain and executes it.
final DialogueFactory executeOption (int type, Optional< OptionDialogue > result)
Executes an result for a player.
final Queue< Chainable > getChain ()
Gets the current chain.
Optional< Runnable > getNextAction ()
Gets the Optional describing the next action in the dialogue chain.
Player getPlayer ()
The player that owns this factory.
boolean isActive ()
boolean isOption ()
Gets if the dialogue is option.
void lock (boolean lock)
final DialogueFactory onAction (Runnable action)
Sets an action so this action can be executed after dialogues are done.
DialogueFactory onNext ()
Accepts the next dialogue in the chain.
final DialogueFactory sendDialogue (Dialogue dialogue)
Sends a player a dialogue.
final DialogueFactory sendInformationBox (String title, String...lines)
final DialogueFactory sendItem (String title, String text, int item)
final DialogueFactory sendItem (String title, String text, Item item)
final DialogueFactory sendNpcChat (int id, Expression expression, String... lines)
Appends an NpcDialogue to the current dialogue chain.
final DialogueFactory sendNpcChat (int id, String... lines)
Appends an NpcDialogue to the current dialogue chain.
final DialogueFactory sendOption (String option1, Runnable action1, String option2, Runnable action2)
Appends the OptionDialogue onto the current dialogue chain.
final DialogueFactory sendOption (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3)
Appends the OptionDialogue onto the current dialogue chain.
final DialogueFactory sendOption (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3, String option4, Runnable action4)
Appends the OptionDialogue onto the current dialogue chain.
final DialogueFactory sendOption (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3, String option4, Runnable action4, String option5, Runnable action5)
Appends the OptionDialogue onto the current dialogue chain.
final DialogueFactory sendPlayerChat (Expression expression, String... lines)
Appends a PlayerDialogue to the current dialogue chain.
final DialogueFactory sendPlayerChat (String... lines)
Appends a PlayerDialogue to the current dialogue chain.
final DialogueFactory sendStatement (String... lines)
Appends a StatementDialogue to the current dialogue chain.
void setActive (boolean active)
void setNextAction (Optional< Runnable > nextAction)
Sets the next action in the dialogue chain.
Package Functions
final DialogueFactory sendInformationBox (InformationDialogue dialogue)
final DialogueFactory sendItem (ItemDialogue dialogue)
final DialogueFactory sendNpcChat (NpcDialogue dialogue)
Sends a dialogue with a npc talking.
final DialogueFactory sendOption (OptionDialogue dialogue)
Sends a dialogue with options.
final DialogueFactory sendPlayerChat (PlayerDialogue dialogue)
Sends a dialogue with a player talking.
final DialogueFactory sendStatement (StatementDialogue dialogue)
Sends a player a statement dialogue.
Private Member Functions
final DialogueFactory append (Chainable chain)
Appends a chain to this factory.
final String appendKeywords (String line)
Appends keywords to an existing dialogue text.
final void validateLength (String... text)
The method that validates the length of text.
Private Attributes
boolean active
The flag that denotes dialogue is active.
final Queue< Chainable > CHAIN = new ArrayDeque<>()
The queue of dialogues in this factory.
boolean locked
Optional< Runnable > nextAction = Optional.empty()
The next action in the dialogue chain.
final Player player
The player who owns this factory.
Static Private Attributes
static final Logger logger = LogManager.getLogger(DialogueFactory.class)
static final int MAXIMUM_LENGTH = 500
The maximum length of a single line of dialogue.
Detailed Description
Represents a factory class that contains important functions for building dialogues.
Author
nshusa
Definition at line 19 of file DialogueFactory.java.
Constructor & Destructor Documentation
DialogueFactory()
com.runehive.content.dialogue.DialogueFactory.DialogueFactory (Player player)
Creates a new DialogueFactory.
Parameters
player The player who owns this factory.
Definition at line 44 of file DialogueFactory.java.
{
        this.player = player;
    }
References player.
Referenced by append(), execute(), executeOption(), onAction(), onNext(), sendDialogue(), sendInformationBox(), sendInformationBox(), sendItem(), sendItem(), sendItem(), sendNpcChat(), sendNpcChat(), sendNpcChat(), sendOption(), sendOption(), sendOption(), sendOption(), sendOption(), sendPlayerChat(), sendPlayerChat(), sendPlayerChat(), sendStatement(), and sendStatement().
Member Function Documentation
append()
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.append (Chainable chain) private
Appends a chain to this factory.
Returns
The instance of this factory.
Definition at line 132 of file DialogueFactory.java.
{
        this.CHAIN.add(chain);
        return this;
    }
References DialogueFactory().
Referenced by sendInformationBox(), sendItem(), sendItem(), sendNpcChat(), sendNpcChat(), sendOption(), sendOption(), sendOption(), sendOption(), sendPlayerChat(), sendPlayerChat(), and sendStatement().
appendKeywords()
final String com.runehive.content.dialogue.DialogueFactory.appendKeywords (String line) private
Appends keywords to an existing dialogue text.
Parameters
line The line to check for a keyword.
Definition at line 208 of file DialogueFactory.java.
{
        if (line.contains("#username")) {
            line = line.replace("#username", Utility.formatName((player.getName())));
        }
        if (line.contains("#name")) {
            line = line.replace("#name", Utility.formatName((player.getName())));
        }
        return line;
    }
References com.runehive.util.Utility.formatName(), and player.
Referenced by sendNpcChat(), and sendPlayerChat().
clear()
void com.runehive.content.dialogue.DialogueFactory.clear ()
Clears the current dialogue chain.
Returns
The instance of this factory.
Definition at line 115 of file DialogueFactory.java.
{
        CHAIN.clear();
        nextAction = Optional.empty();
        player.dialogue = Optional.empty();
        player.optionDialogue = Optional.empty();
        setActive(false);
        player.interfaceManager.setDialogue(-1);
        player.send(new SendRemoveInterface(false));
        // Clear cached interface strings so dialogue can be replayed
        player.playerAssistant.clearSendStrings();
    }
References CHAIN, nextAction, player, and setActive().
Referenced by com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), and com.runehive.content.clanchannel.channel.ClanChannelHandler.testPassword().
execute()
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.execute ()
Retrieves the next dialogue in the chain and executes it.
Returns
The instance of this factory.
Definition at line 161 of file DialogueFactory.java.
{
        if (locked)
            return this;
        if (player.movement.isMoving()) {
            player.movement.reset();
        }
        // check to see if there are anymore dialogues.
        if (getChain().peek() != null) {
            // there is so, grab the next dialogue.
            Chainable entry = getChain().poll();
            // is this an option dialogue?
            if (entry instanceof OptionDialogue) {
                OptionDialogue option = (OptionDialogue) entry;
                player.optionDialogue = Optional.of(option);
            } else {
                player.optionDialogue = Optional.empty();
            }
            player.interfaceManager.setDialogue(1);
            setActive(true);
            // whatever dialogue it is, accept it.
            entry.accept(this);
        } else {
            // there are no dialogues in this chain.
            // is there an action?
            if (getNextAction().isPresent()) {
                // there is so, execute it.
                getNextAction().ifPresent($it -> $it.run());
                // we just used this action so empty it so it can't be used
                // again.
                setNextAction(Optional.empty());
                player.optionDialogue = Optional.empty();
                return this;
            }
            // there are no more dialogues, so clear the screen.
            player.dialogueFactory.clear();
        }
        return this;
    }
References DialogueFactory(), getChain(), getNextAction(), locked, player, setActive(), and setNextAction().
Referenced by com.runehive.content.pet.Pets.buyInsurance(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.canExecute(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.canExecute(), com.runehive.content.dailyeffect.DailyEffect.canUse(), com.runehive.game.service.DonationService.claimDonation(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.activity.impl.barrows.Barrows.clickNpc(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.staff.PlayerManagement.confirm(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.CrystalChest.createKey(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), executeOption(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.content.bloodmoney.BloodMoneyChest.open(), com.runehive.content.Obelisks.open(), com.runehive.content.RoyaltyProgram.open(), com.runehive.game.world.items.containers.bank.BankPin.open(), com.runehive.content.preset.PresetManager.openSettings(), com.runehive.content.shootingstar.ShootingStar.prospect(), com.runehive.content.Waypoints.removeWaypoint(), com.runehive.content.DropDisplay.search(), com.runehive.content.clanchannel.channel.ClanChannelHandler.sendConnectionWarning(), com.runehive.content.dialogue.impl.ClanmasterDialogue.sendDialogues(), com.runehive.content.dialogue.impl.KamfreenaDialogue.sendDialogues(), com.runehive.content.dialogue.impl.LootshareDialogue.sendDialogues(), com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues(), com.runehive.content.dialogue.impl.PrestigeDialogue.sendDialogues(), com.runehive.content.dialogue.impl.RoyalKingDialogue.sendDialogues(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ClanRankDialogue.setRank(), com.runehive.content.Waypoints.setWaypoint(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse(), com.runehive.content.clanchannel.channel.ClanChannelHandler.testPassword(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), and com.runehive.content.skill.impl.herblore.Herblore.useItem().
executeOption()
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.executeOption (int type, Optional< OptionDialogue > result)
Executes an result for a player.
Parameters
type The type of option.
result The option to execute.
Definition at line 96 of file DialogueFactory.java.
{
        if (result.isPresent()) {
            OptionDialogue optionDialogue = result.get();
            if (type < 0 || type >= optionDialogue.getActions().size()) {
                return this;
            }
            optionDialogue.getActions().get(type).run();
        }
        execute();
        return this;
    }
References DialogueFactory(), execute(), and com.runehive.content.dialogue.OptionDialogue.getActions().
getChain()
final Queue< Chainable > com.runehive.content.dialogue.DialogueFactory.getChain ()
Gets the current chain.
Returns
The queue of dialogues.
Definition at line 142 of file DialogueFactory.java.
{
        return CHAIN;
    }
References CHAIN.
Referenced by execute(), isOption(), and onNext().
getNextAction()
Optional< Runnable > com.runehive.content.dialogue.DialogueFactory.getNextAction ()
Gets the Optional describing the next action in the dialogue chain.
Returns
The optional describing the next action.
Definition at line 649 of file DialogueFactory.java.
{
        return nextAction;
    }
References nextAction.
Referenced by execute().
getPlayer()
Player com.runehive.content.dialogue.DialogueFactory.getPlayer ()
The player that owns this factory.
Returns
The player.
Definition at line 639 of file DialogueFactory.java.
{
        return player;
    }
References player.
Referenced by com.runehive.content.dialogue.impl.RoyalKingDialogue.claim(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.dialogue.impl.RoyalKingDialogue.myStats(), com.runehive.content.dialogue.impl.NieveDialogue.sell(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.content.dialogue.impl.ClanmasterDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues(), com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues(), com.runehive.content.dialogue.impl.PrestigeDialogue.sendDialogues(), com.runehive.content.dialogue.impl.RoyalKingDialogue.sendDialogues(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues(), and com.runehive.content.dialogue.impl.RoyalKingDialogue.store().
isActive()
boolean com.runehive.content.dialogue.DialogueFactory.isActive ()
Definition at line 662 of file DialogueFactory.java.
{
        return active;
    }
References active.
isOption()
boolean com.runehive.content.dialogue.DialogueFactory.isOption ()
Gets if the dialogue is option.
Returns
The option dialogue.
Definition at line 151 of file DialogueFactory.java.
{
        Chainable next = getChain().peek();
        return next instanceof OptionDialogue;
    }
References getChain().
lock()
void com.runehive.content.dialogue.DialogueFactory.lock (boolean lock)
Definition at line 71 of file DialogueFactory.java.
{
        this.locked = lock;
    }
References lock().
Referenced by lock().
onAction()
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.onAction (Runnable action)
Sets an action so this action can be executed after dialogues are done.
Parameters
action The action to set.
Returns
The instance of this factory.
Definition at line 66 of file DialogueFactory.java.
{
        setNextAction(Optional.of(action));
        return this;
    }
References DialogueFactory(), and setNextAction().
Referenced by com.runehive.content.store.impl.PersonalStore.edit(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.game.plugin.PluginContext.onClick(), com.runehive.content.skill.impl.crafting.impl.Spinning.open(), com.runehive.content.preset.PresetManager.openSettings(), com.runehive.content.dialogue.impl.NieveDialogue.sell(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues(), com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues(), com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues(), com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse(), and com.runehive.content.clanchannel.channel.ClanChannelHandler.testPassword().
onNext()
DialogueFactory com.runehive.content.dialogue.DialogueFactory.onNext ()
Accepts the next dialogue in the chain.
Returns
The instance of this factory.
Definition at line 80 of file DialogueFactory.java.
{
        if (getChain().peek() != null) {
            Chainable chain = getChain().poll();
            chain.accept(this);
        } else {
            player.interfaceManager.close();
        }
        return this;
    }
References DialogueFactory(), getChain(), and player.
sendDialogue()
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendDialogue (Dialogue dialogue)
Sends a player a dialogue.
Parameters
dialogue The dialogue to sent.
Definition at line 53 of file DialogueFactory.java.
{
        player.dialogue = Optional.of(dialogue);
        dialogue.sendDialogues(this);
        return this;
    }
References DialogueFactory().
Referenced by com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse().
sendInformationBox() [1/2]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendInformationBox (InformationDialogue dialogue) package
Definition at line 580 of file DialogueFactory.java.
{
        validateLength(dialogue.getLines());
        switch (dialogue.getLines().length) {
            case 1:
                player.send(new SendString(dialogue.getTitle(), 6180));
                player.send(new SendString("", 6181));
                player.send(new SendString(dialogue.getLines()[0], 6182));
                player.send(new SendString("", 6183));
                player.send(new SendString("", 6184));
                player.send(new SendChatBoxInterface(6179));
                break;
            case 2:
                player.send(new SendString(dialogue.getTitle(), 6180));
                player.send(new SendString("", 6181));
                player.send(new SendString(dialogue.getLines()[0], 6182));
                player.send(new SendString(dialogue.getLines()[1], 6183));
                player.send(new SendString("", 6184));
                player.send(new SendChatBoxInterface(6179));
                break;
            case 3:
                player.send(new SendString(dialogue.getTitle(), 6180));
                player.send(new SendString("", 6181));
                player.send(new SendString(dialogue.getLines()[0], 6182));
                player.send(new SendString(dialogue.getLines()[1], 6183));
                player.send(new SendString(dialogue.getLines()[2], 6184));
                player.send(new SendChatBoxInterface(6179));
                break;
            case 4:
                player.send(new SendString(dialogue.getTitle(), 6180));
                player.send(new SendString(dialogue.getLines()[0], 6181));
                player.send(new SendString(dialogue.getLines()[1], 6182));
                player.send(new SendString(dialogue.getLines()[2], 6183));
                player.send(new SendString(dialogue.getLines()[3], 6184));
                player.send(new SendChatBoxInterface(6179));
                break;
            default:
                logger.error(String.format("Invalid information dialogue line length: %s", dialogue.getLines().length));
                break;
        }
        return this;
    }
References DialogueFactory(), logger, player, and validateLength().
sendInformationBox() [2/2]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendInformationBox (String title, String... lines)
Definition at line 574 of file DialogueFactory.java.
{
        validateLength(lines);
        append(new InformationDialogue(title, lines));
        return this;
    }
References append(), DialogueFactory(), and validateLength().
Referenced by com.runehive.content.dialogue.InformationDialogue.accept(), and com.runehive.content.preset.PresetManager.openSettings().
sendItem() [1/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendItem (ItemDialogue dialogue) package
Definition at line 563 of file DialogueFactory.java.
{
        validateLength(dialogue.getContext());
        player.send(new SendInterfaceAnimation(4883, 591));
        player.send(new SendString(dialogue.getTitle(), 4884));
        player.send(new SendString(dialogue.getContext(), 4885));
        player.send(new SendString("Click here to continue.", 4886));
        player.send(new SendItemModelOnInterface(4883, 250, dialogue.getItem()));
        player.send(new SendChatBoxInterface(4882));
        return this;
    }
References DialogueFactory(), player, and validateLength().
sendItem() [2/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendItem (String title, String text, int item)
Definition at line 557 of file DialogueFactory.java.
{
        validateLength(text);
        append(new ItemDialogue(title, text, item));
        return this;
    }
References append(), DialogueFactory(), and validateLength().
sendItem() [3/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendItem (String title, String text, Item item)
Definition at line 551 of file DialogueFactory.java.
{
        validateLength(text);
        append(new ItemDialogue(title, text, item.getId()));
        return this;
    }
References append(), DialogueFactory(), com.runehive.game.world.items.Item.getId(), and validateLength().
Referenced by com.runehive.content.dialogue.ItemDialogue.accept(), and com.runehive.content.CrystalChest.createKey().
sendNpcChat() [1/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendNpcChat (int id, Expression expression, String... lines)
Appends an NpcDialogue to the current dialogue chain.
Parameters
id The id of this npc.
expression The expression of this npc.
lines The text of this dialogue.
Returns
The instance of this factory.
Definition at line 313 of file DialogueFactory.java.
{
        return append(new NpcDialogue(id, expression, lines));
    }
References append(), and DialogueFactory().
sendNpcChat() [2/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendNpcChat (int id, String... lines)
Appends an NpcDialogue to the current dialogue chain.
Parameters
id The id of this npc.
lines The text of this dialogue.
Returns
The instance of this factory.
Definition at line 301 of file DialogueFactory.java.
{
        return append(new NpcDialogue(id, Expression.DEFAULT, lines));
    }
References append(), com.runehive.content.dialogue.Expression.DEFAULT, and DialogueFactory().
Referenced by com.runehive.content.dialogue.NpcDialogue.accept(), com.runehive.content.pet.Pets.buyInsurance(), com.runehive.game.service.DonationService.claimDonation(), com.runehive.content.pet.Pets.claimLostPets(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanDefinition(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanPerks(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask(), com.runehive.content.activity.impl.barrows.Barrows.clickNpc(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.skill.impl.thieving.Thieving.exchange(), com.runehive.content.dialogue.impl.PrestigeDialogue.explainPerks(), com.runehive.content.dialogue.impl.PrestigeDialogue.explainPrestige(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.content.dialogue.impl.NieveDialogue.sell(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.content.dialogue.impl.ClanmasterDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues(), com.runehive.content.dialogue.impl.KamfreenaDialogue.sendDialogues(), com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues(), com.runehive.content.dialogue.impl.PrestigeDialogue.sendDialogues(), com.runehive.content.dialogue.impl.RoyalKingDialogue.sendDialogues(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), and com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse().
sendNpcChat() [3/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendNpcChat (NpcDialogue dialogue) package
Sends a dialogue with a npc talking.
Parameters
dialogue The dialogue.
Returns
The instance of this factory.
Definition at line 323 of file DialogueFactory.java.
{
        Expression expression = dialogue.getExpression();
        String[] lines = dialogue.getLines();
        validateLength(lines);
        // NPC speaking  camera behind NPC, looking at player (+slightly faster turn)
        player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_NPC;
        com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.boostSwap(player, 8);
        int id = dialogue.getId();
        final NpcDefinition npcDef = NpcDefinition.get(id);
        if (npcDef == null) return this;
        switch (lines.length) {
            case 1:
                player.send(new SendInterfaceAnimation(4883, expression.getId()));
                player.send(new SendString(npcDef.getName(), 4884));
                player.send(new SendString(appendKeywords(lines[0]), 4885));
                player.send(new SendNpcHead(npcDef.getId(), 4883));
                player.send(new SendChatBoxInterface(4882));
                break;
            case 2:
                player.send(new SendInterfaceAnimation(4888, expression.getId()));
                player.send(new SendString(npcDef.getName(), 4889));
                player.send(new SendString(appendKeywords(lines[0]), 4890));
                player.send(new SendString(appendKeywords(lines[1]), 4891));
                player.send(new SendNpcHead(npcDef.getId(), 4888));
                player.send(new SendChatBoxInterface(4887));
                break;
            case 3:
                player.send(new SendInterfaceAnimation(4894, expression.getId()));
                player.send(new SendString(npcDef.getName(), 4895));
                player.send(new SendString(appendKeywords(lines[0]), 4896));
                player.send(new SendString(appendKeywords(lines[1]), 4897));
                player.send(new SendString(appendKeywords(lines[2]), 4898));
                player.send(new SendNpcHead(npcDef.getId(), 4894));
                player.send(new SendChatBoxInterface(4893));
                break;
            case 4:
                player.send(new SendInterfaceAnimation(4901, expression.getId()));
                player.send(new SendString(npcDef.getName(), 4902));
                player.send(new SendString(appendKeywords(lines[0]), 4903));
                player.send(new SendString(appendKeywords(lines[1]), 4904));
                player.send(new SendString(appendKeywords(lines[2]), 4905));
                player.send(new SendString(appendKeywords(lines[3]), 4906));
                player.send(new SendNpcHead(npcDef.getId(), 4901));
                player.send(new SendChatBoxInterface(4900));
                break;
            default:
                logger.error(String.format("Invalid npc dialogue line length: %s", lines.length));
                break;
        }
        return this;
    }
References appendKeywords(), DialogueFactory(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.get(), com.runehive.content.dialogue.Expression.getId(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getId(), com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getName(), logger, player, and validateLength().
sendOption() [1/5]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendOption (OptionDialogue dialogue) package
Sends a dialogue with options.
Parameters
dialogue The dialogue.
Returns
The instance of this factory.
Definition at line 442 of file DialogueFactory.java.
{
        String[] options = dialogue.getLines();
        validateLength(options);
        switch (options.length) {
            case 2:
                player.send(new SendString("Select an Option", 2460));
                player.send(new SendString(options[0], 2461));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[0], 2461));
                player.send(new SendString(options[1], 2462));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[1], 2461));
                player.send(new SendChatBoxInterface(2459));
                return this;
            case 3:
                player.send(new SendString("Select an Option", 2470));
                player.send(new SendString(options[0], 2471));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[0], 2471));
                player.send(new SendString(options[1], 2472));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[1], 2472));
                player.send(new SendString(options[2], 2473));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[2], 2473));
                player.send(new SendChatBoxInterface(2469));
                return this;
            case 4:
                player.send(new SendString("Select an Option", 2481));
                player.send(new SendString(options[0], 2482));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[0], 2482));
                player.send(new SendString(options[1], 2483));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[1], 2483));
                player.send(new SendString(options[2], 2484));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[2], 2484));
                player.send(new SendString(options[3], 2485));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[3], 2485));
                player.send(new SendChatBoxInterface(2480));
                return this;
            case 5:
                player.send(new SendString("Select an Option", 2493));
                player.send(new SendString(options[0], 2494));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[0], 2494));
                player.send(new SendString(options[1], 2495));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[1], 2495));
                player.send(new SendString(options[2], 2496));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[2], 2496));
                player.send(new SendString(options[3], 2497));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[3], 2497));
                player.send(new SendString(options[4], 2498));
                player.send(new SendTooltip("</col>Select <col=A89590>" + options[4], 2498));
                player.send(new SendChatBoxInterface(2492));
                return this;
        }
        return this;
    }
References DialogueFactory(), player, and validateLength().
sendOption() [2/5]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendOption (String option1, Runnable action1, String option2, Runnable action2)
Appends the OptionDialogue onto the current dialogue chain.
Parameters
option1 The text for the first option.
action1 The action for the first action.
option2 The text for the second option.
action2 The action for the second action.
Definition at line 384 of file DialogueFactory.java.
{
        return append(new OptionDialogue(option1, action1, option2, action2));
    }
References append(), and DialogueFactory().
Referenced by com.runehive.content.dialogue.OptionDialogue.accept(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanInformation(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanManagement(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask(), com.runehive.content.activity.impl.barrows.Barrows.clickNpc(), com.runehive.content.staff.PlayerManagement.confirm(), com.runehive.content.store.impl.PersonalStore.edit(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.store.impl.PersonalStore.modify(), com.runehive.content.skill.impl.slayer.SlayerOfferings.offer(), com.runehive.game.plugin.PluginContext.onClick(), com.runehive.content.skill.impl.crafting.impl.Spinning.open(), com.runehive.game.world.items.containers.bank.BankPin.open(), com.runehive.content.preset.PresetManager.openSettings(), com.runehive.content.dialogue.impl.NieveDialogue.sell(), com.runehive.content.clanchannel.channel.ClanChannelHandler.sendConnectionWarning(), com.runehive.content.dialogue.impl.ClanmasterDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ClanRankDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues(), com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues(), com.runehive.content.dialogue.impl.PrestigeDialogue.sendDialogues(), com.runehive.content.dialogue.impl.RoyalKingDialogue.sendDialogues(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.content.dialogue.impl.RoyalKingDialogue.store(), and com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse().
sendOption() [3/5]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendOption (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3)
Appends the OptionDialogue onto the current dialogue chain.
Parameters
option1 The text for the first option.
action1 The action for the first action.
option2 The text for the second option.
action2 The action for the second action.
option3 The text for the third option.
action3 The action for the third action.
Definition at line 398 of file DialogueFactory.java.
{
        return append(new OptionDialogue(option1, action1, option2, action2, option3, action3));
    }
References append(), and DialogueFactory().
sendOption() [4/5]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendOption (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3, String option4, Runnable action4)
Appends the OptionDialogue onto the current dialogue chain.
Parameters
option1 The text for the first option.
action1 The action for the first action.
option2 The text for the second option.
action2 The action for the second action.
option3 The text for the third option.
action3 The action for the third action.
option4 The text for the four option.
action4 The action for the four action.
Definition at line 414 of file DialogueFactory.java.
{
        return append(new OptionDialogue(option1, action1, option2, action2, option3, action3, option4, action4));
    }
References append(), and DialogueFactory().
sendOption() [5/5]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendOption (String option1, Runnable action1, String option2, Runnable action2, String option3, Runnable action3, String option4, Runnable action4, String option5, Runnable action5)
Appends the OptionDialogue onto the current dialogue chain.
Parameters
option1 The text for the first option.
action1 The action for the first action.
option2 The text for the second option.
action2 The action for the second action.
option3 The text for the third option.
action3 The action for the third action.
option4 The text for the four option.
action4 The action for the four action.
option5 The text for the fifth option.
action5 The action for the fifth action.
Definition at line 432 of file DialogueFactory.java.
{
        return append(new OptionDialogue(option1, action1, option2, action2, option3, action3, option4, action4, option5, action5));
    }
References append(), and DialogueFactory().
sendPlayerChat() [1/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendPlayerChat (Expression expression, String... lines)
Appends a PlayerDialogue to the current dialogue chain.
Parameters
lines The dialogue of the player talking.
expression The expression of this dialogue.
Returns
The instance of this factory.
Definition at line 235 of file DialogueFactory.java.
{
        return append(new PlayerDialogue(expression, lines));
    }
References append(), and DialogueFactory().
sendPlayerChat() [2/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendPlayerChat (PlayerDialogue dialogue) package
Sends a dialogue with a player talking.
Parameters
dialogue The player dialogue.
Returns
The instance of this factory.
Definition at line 245 of file DialogueFactory.java.
{
        Expression expression = dialogue.getExpression();
        String[] lines = dialogue.getLines();
        validateLength(lines);
        // Player speaking  camera behind player, looking at NPC (+slightly faster turn)
        player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_PLAYER;
        com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.boostSwap(player, 8);
        switch (lines.length) {
            case 1:
                player.send(new SendInterfaceAnimation(969, expression.getId()));
                player.send(new SendString(Utility.formatName(player.getName()), 970));
                player.send(new SendString(appendKeywords(lines[0]), 971));
                player.send(new SendPlayerDialogueHead(969));
                player.send(new SendChatBoxInterface(968));
                break;
            case 2:
                player.send(new SendInterfaceAnimation(974, expression.getId()));
                player.send(new SendString(Utility.formatName(player.getName()), 975));
                player.send(new SendString(appendKeywords(lines[0]), 976));
                player.send(new SendString(appendKeywords(lines[1]), 977));
                player.send(new SendPlayerDialogueHead(974));
                player.send(new SendChatBoxInterface(973));
                break;
            case 3:
                player.send(new SendInterfaceAnimation(980, expression.getId()));
                player.send(new SendString(Utility.formatName(player.getName()), 981));
                player.send(new SendString(appendKeywords(lines[0]), 982));
                player.send(new SendString(appendKeywords(lines[1]), 983));
                player.send(new SendString(appendKeywords(lines[2]), 984));
                player.send(new SendPlayerDialogueHead(980));
                player.send(new SendChatBoxInterface(979));
                break;
            case 4:
                player.send(new SendInterfaceAnimation(987, expression.getId()));
                player.send(new SendString(Utility.formatName(player.getName()), 988));
                player.send(new SendString(appendKeywords(lines[0]), 989));
                player.send(new SendString(appendKeywords(lines[1]), 990));
                player.send(new SendString(appendKeywords(lines[2]), 991));
                player.send(new SendString(appendKeywords(lines[3]), 992));
                player.send(new SendPlayerDialogueHead(987));
                player.send(new SendChatBoxInterface(986));
                break;
            default:
                logger.error(String.format("Invalid player dialogue line length: %s", lines.length));
                break;
        }
        return this;
    }
References appendKeywords(), DialogueFactory(), com.runehive.util.Utility.formatName(), com.runehive.content.dialogue.Expression.getId(), logger, player, and validateLength().
sendPlayerChat() [3/3]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendPlayerChat (String... lines)
Appends a PlayerDialogue to the current dialogue chain.
Parameters
lines The dialogue of the player talking.
Returns
The instance of this factory.
Definition at line 224 of file DialogueFactory.java.
{
        return append(new PlayerDialogue(lines));
    }
References append(), and DialogueFactory().
Referenced by com.runehive.content.dialogue.PlayerDialogue.accept(), and com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues().
sendStatement() [1/2]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendStatement (StatementDialogue dialogue) package
Sends a player a statement dialogue.
Parameters
dialogue The statement dialogue.
Definition at line 511 of file DialogueFactory.java.
{
        validateLength(dialogue.getLines());
        switch (dialogue.getLines().length) {
            case 1:
                player.send(new SendString(dialogue.getLines()[0], 357));
                player.send(new SendChatBoxInterface(356));
                break;
            case 2:
                player.send(new SendString(dialogue.getLines()[0], 360));
                player.send(new SendString(dialogue.getLines()[1], 361));
                player.send(new SendChatBoxInterface(359));
                break;
            case 3:
                player.send(new SendString(dialogue.getLines()[0], 364));
                player.send(new SendString(dialogue.getLines()[1], 365));
                player.send(new SendString(dialogue.getLines()[2], 366));
                player.send(new SendChatBoxInterface(363));
                break;
            case 4:
                player.send(new SendString(dialogue.getLines()[0], 369));
                player.send(new SendString(dialogue.getLines()[1], 370));
                player.send(new SendString(dialogue.getLines()[2], 371));
                player.send(new SendString(dialogue.getLines()[3], 372));
                player.send(new SendChatBoxInterface(368));
                break;
            case 5:
                player.send(new SendString(dialogue.getLines()[0], 375));
                player.send(new SendString(dialogue.getLines()[1], 376));
                player.send(new SendString(dialogue.getLines()[2], 377));
                player.send(new SendString(dialogue.getLines()[3], 378));
                player.send(new SendString(dialogue.getLines()[4], 379));
                player.send(new SendChatBoxInterface(374));
                break;
            default:
                logger.error(String.format("Invalid statement dialogue line length: %s", dialogue.getLines().length));
                break;
        }
        return this;
    }
References DialogueFactory(), logger, player, and validateLength().
sendStatement() [2/2]
final DialogueFactory com.runehive.content.dialogue.DialogueFactory.sendStatement (String... lines)
Appends a StatementDialogue to the current dialogue chain.
Parameters
lines The text for this statement.
Returns
The instance of this factory.
Definition at line 500 of file DialogueFactory.java.
{
        validateLength(lines);
        append(new StatementDialogue(lines));
        return this;
    }
References append(), DialogueFactory(), and validateLength().
Referenced by com.runehive.content.dialogue.StatementDialogue.accept(), com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.canExecute(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.canExecute(), com.runehive.content.dailyeffect.DailyEffect.canUse(), com.runehive.game.service.DonationService.claimDonation(), com.runehive.game.service.VoteService.claimReward(), com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask(), com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.herblore.Herblore.clickItem(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.staff.PlayerManagement.confirm(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), com.runehive.content.store.impl.PersonalStore.edit(), com.runehive.content.skill.impl.fishing.FishingAction.fish(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.content.shootingstar.ShootingStar.mine(), com.runehive.content.dialogue.impl.RoyalKingDialogue.myStats(), com.runehive.content.bloodmoney.BloodMoneyChest.open(), com.runehive.content.Obelisks.open(), com.runehive.content.RoyaltyProgram.open(), com.runehive.content.preset.PresetManager.openSettings(), com.runehive.content.shootingstar.ShootingStar.prospect(), com.runehive.content.Waypoints.removeWaypoint(), com.runehive.content.DropDisplay.search(), com.runehive.content.dialogue.impl.NieveDialogue.sell(), com.runehive.content.clanchannel.channel.ClanChannelHandler.sendConnectionWarning(), com.runehive.content.dialogue.impl.LootshareDialogue.sendDialogues(), com.runehive.content.dialogue.impl.WellOfGoodwillDialogue.sendDialogues(), com.runehive.content.dialogue.impl.ClanRankDialogue.setRank(), com.runehive.content.Waypoints.setWaypoint(), com.runehive.content.teleport.TeleportHandler.special(), com.runehive.content.skill.impl.crafting.Crafting.start(), com.runehive.content.skill.impl.fletching.Fletching.start(), com.runehive.content.clanchannel.channel.ClanChannelHandler.testPassword(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), and com.runehive.content.skill.impl.herblore.Herblore.useItem().
setActive()
void com.runehive.content.dialogue.DialogueFactory.setActive (boolean active)
Definition at line 666 of file DialogueFactory.java.
{
        this.active = active;
    }
References active.
Referenced by clear(), execute(), and com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface().
setNextAction()
void com.runehive.content.dialogue.DialogueFactory.setNextAction (Optional< Runnable > nextAction)
Sets the next action in the dialogue chain.
Parameters
nextAction The action to set.
Definition at line 658 of file DialogueFactory.java.
{
        this.nextAction = nextAction;
    }
References nextAction.
Referenced by execute(), and onAction().
validateLength()
final void com.runehive.content.dialogue.DialogueFactory.validateLength (String... text) private
The method that validates the length of text.
Parameters
text the text that will be validated.
Exceptions
IllegalStateException if any lines of the text exceed a certain length.
Definition at line 628 of file DialogueFactory.java.
{
        if (Arrays.stream(text).filter(Objects::nonNull).anyMatch(s -> s.length() > MAXIMUM_LENGTH)) {
            throw new IllegalStateException("Dialogue length too long, maximum length is: " + MAXIMUM_LENGTH);
        }
    }
References MAXIMUM_LENGTH.
Referenced by sendInformationBox(), sendInformationBox(), sendItem(), sendItem(), sendItem(), sendNpcChat(), sendOption(), sendPlayerChat(), sendStatement(), and sendStatement().
Member Data Documentation
active
boolean com.runehive.content.dialogue.DialogueFactory.active private
The flag that denotes dialogue is active.
Definition at line 33 of file DialogueFactory.java.
Referenced by isActive(), and setActive().
CHAIN
final Queue<Chainable> com.runehive.content.dialogue.DialogueFactory.CHAIN = new ArrayDeque<>() private
The queue of dialogues in this factory.
Definition at line 24 of file DialogueFactory.java.
Referenced by clear(), and getChain().
locked
boolean com.runehive.content.dialogue.DialogueFactory.locked private
Definition at line 37 of file DialogueFactory.java.
Referenced by execute().
logger
final Logger com.runehive.content.dialogue.DialogueFactory.logger = LogManager.getLogger(DialogueFactory.class) static private
Definition at line 21 of file DialogueFactory.java.
Referenced by sendInformationBox(), sendNpcChat(), sendPlayerChat(), and sendStatement().
MAXIMUM_LENGTH
final int com.runehive.content.dialogue.DialogueFactory.MAXIMUM_LENGTH = 500 static private
The maximum length of a single line of dialogue.
Definition at line 27 of file DialogueFactory.java.
Referenced by validateLength().
nextAction
Optional<Runnable> com.runehive.content.dialogue.DialogueFactory.nextAction = Optional.empty() private
The next action in the dialogue chain.
Definition at line 36 of file DialogueFactory.java.
Referenced by clear(), getNextAction(), and setNextAction().
player
final Player com.runehive.content.dialogue.DialogueFactory.player private
The player who owns this factory.
Definition at line 30 of file DialogueFactory.java.
Referenced by appendKeywords(), clear(), DialogueFactory(), execute(), getPlayer(), onNext(), sendInformationBox(), sendItem(), sendNpcChat(), sendOption(), sendPlayerChat(), sendStatement(), and com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse().
The documentation for this class was generated from the following file:
java/com/runehive/content/dialogue/DialogueFactory.java