RuneHive-Game: com.runehive.content.activity.inferno.Inferno Class Reference
com.runehive.content.activity.inferno.Inferno Class Reference
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
void finish ()
Finishes the activity.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
ActivityType getType ()
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
void update ()
The update method.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
ActivityDeathType deathType ()
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
void onDeath (Mob mob)
Called when the player die.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
Static Public Member Functions
static Inferno create (Player player)
static void finalWave ()
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Public Attributes
final Set< Npc > npcs = new HashSet<>()
A set of npcs in this activity.
Protected Member Functions
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Package Functions
void handleDeath (Mob dead)
Handles what happens to a mob when they die in the activity.
Private Member Functions
Inferno (Player player, int instance)
Constructs a new Inferno object for a player and an instance.
Private Attributes
boolean completed
The activity completed flag.
final InfernoCavesListener listener = new InfernoCavesListener(this)
The combat listener to add for all mobs.
final Player player
The player in the Inferno.
int rewards
The amount of rewards the player has acquired.
long time
The time it took to complete the activity.
InfernoWaveData.WaveData wave = InfernoWaveData.WaveData.WAVE_1
The current wave of this activity.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Definition at line 26 of file Inferno.java.
Constructor & Destructor Documentation
Inferno()
com.runehive.content.activity.inferno.Inferno.Inferno (Player player, int instance) private
Constructs a new Inferno object for a player and an instance.
Definition at line 53 of file Inferno.java.
{
        super(10, instance);
        this.player = player;
    }
References com.runehive.content.activity.Activity.instance, and player.
Referenced by create().
Member Function Documentation
canTeleport()
boolean com.runehive.content.activity.inferno.Inferno.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 203 of file Inferno.java.
{
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.inferno.Inferno.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 179 of file Inferno.java.
{
        ActivityPanel.clear(player);
        if (!npcs.isEmpty())
            npcs.forEach(this::remove);
    }
References com.runehive.content.activity.panel.ActivityPanel.clear(), npcs, and player.
Referenced by finish(), and onRegionChange().
create()
Inferno com.runehive.content.activity.inferno.Inferno.create (Player player) static
Definition at line 58 of file Inferno.java.
{
        Inferno minigame = new Inferno(player, player.playerAssistant.instance());
        player.move(new Position(2273, 5341, player.getHeight()));
        ActivityPanel.update(player, -1, "Inferno", "Activity Completion:", "Good Luck, " + player.getName() + "!");
        player.dialogueFactory.sendNpcChat(5567, "Welcome to the Inferno, #name.",
                "There are a total of 69 waves, TzKal-Zuk being the last.",
                "Use your activity panel (bottom left tab) for wave information.", "Good luck!").execute();
        minigame.time = System.currentTimeMillis();
        minigame.add(player);
        minigame.resetCooldown();
        return minigame;
    }
References com.runehive.content.activity.Activity.add(), Inferno(), player, com.runehive.content.activity.Activity.resetCooldown(), and com.runehive.content.activity.panel.ActivityPanel.update().
Referenced by com.runehive.content.teleport.TeleportHandler.teleport().
finalWave()
void com.runehive.content.activity.inferno.Inferno.finalWave () static
Definition at line 143 of file Inferno.java.
{
        final int BOSS_ID;
        InfernoWaveData.WaveData wavee = InfernoWaveData.WaveData.WAVE_69;
    }
References com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_69.
finish()
void com.runehive.content.activity.inferno.Inferno.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 149 of file Inferno.java.
{
        cleanup();
        remove(player);
        player.move(new Position(3086, 3501, 0));
        if (completed) {
            player.dialogueFactory.sendNpcChat(5567, "You have defeated Inferno, I am most impressed!",
                    "Please accept this gift, young thug.").execute();
            rewards += 10000;
            player.inventory.addOrDrop(new Item(7775, rewards));
            player.message("<img=9>You now have @red@" + rewards + " Inferno Tickets!");
            if (Utility.random(1, 3) == 3) {
                player.inventory.addOrDrop(new Item(20211));
            }
            player.inventory.addOrDrop(new Item(290));
            Pets.onReward(player, PetData.PIRATE_PETE);
            player.send(new SendMessage(
                    "You have completed the Inferno activity. Final time: @red@" + Utility.getTime(time) + "</col>."));
            player.activityLogger.add(ActivityLog.INFERNO);
            return;
        }
        if (rewards <= 0)
            rewards = 1;
        player.inventory.addOrDrop(new Item(7775, rewards));
        player.message("<img=9>You now have @red@" + rewards + " Inferno Tickets!");
        player.dialogueFactory.sendNpcChat(5567, "Better luck next time!", "Take these points as a reward.").execute();
    }
References cleanup(), completed, com.runehive.util.Utility.getTime(), com.runehive.content.ActivityLog.INFERNO, com.runehive.content.pet.Pets.onReward(), com.runehive.content.pet.PetData.PIRATE_PETE, player, com.runehive.util.Utility.random(), rewards, and time.
Referenced by handleDeath(), onLogout(), and start().
getListener()
Optional<? extends ActivityListener<? extends Activity > > com.runehive.content.activity.inferno.Inferno.getListener ()
Gets an Optional of the ActivityListener for this activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 228 of file Inferno.java.
{
        return Optional.of(listener);
    }
References listener.
getType()
ActivityType com.runehive.content.activity.inferno.Inferno.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 223 of file Inferno.java.
{
        return ActivityType.INFERNO;
    }
References com.runehive.content.activity.ActivityType.INFERNO.
handleDeath()
void com.runehive.content.activity.inferno.Inferno.handleDeath (Mob dead) package
Handles what happens to a mob when they die in the activity.
Definition at line 72 of file Inferno.java.
{
        if (dead.isPlayer() && dead.equals(player)) {
            finish();
            return;
        }
        if (dead.isNpc() && npcs.contains(dead)) {
            if (dead.id == 3162) {
                remove(dead);
                npcs.remove(dead);
                for (int index = 0; index < 2; index++) {
                    Position position = new Position(dead.getX() + (index == 0 ? -1 : +1), dead.getY(),
                            dead.getHeight());
                    Npc roc = new Npc(763, position);
                    add(roc);
                    npcs.add(roc);
                    roc.getCombat().attack(player);
                    dead.animate(Animation.RESET, true);
                    dead.graphic(Graphic.RESET, true);
                }
                return;
            }
            npcs.remove(dead);
            remove(dead);
            rewards += Utility.random(250, 1000);
            if (npcs.isEmpty()) {
                wave = InfernoWaveData.WaveData.getNext(wave.ordinal());
                if (wave == null) {
                    completed = true;
                    player.send(new SendMessage("You have finished the activity!"));
                } else {
                    player.send(new SendMessage("The next wave will commence soon."));
                }
                resetCooldown();
                return;
            }
        }
    }
References com.runehive.content.activity.Activity.add(), com.runehive.game.world.entity.mob.Mob.animate(), completed, com.runehive.game.world.entity.Entity.equals(), finish(), com.runehive.game.world.entity.mob.npc.Npc.getCombat(), com.runehive.game.world.entity.Entity.getHeight(), com.runehive.content.activity.inferno.InfernoWaveData.WaveData.getNext(), com.runehive.game.world.entity.Entity.getX(), com.runehive.game.world.entity.Entity.getY(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), npcs, player, com.runehive.util.Utility.random(), com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, com.runehive.content.activity.Activity.resetCooldown(), rewards, and wave.
onLogout()
void com.runehive.content.activity.inferno.Inferno.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 217 of file Inferno.java.
{
        finish();
        remove(player);
    }
References finish(), and player.
onRegionChange()
void com.runehive.content.activity.inferno.Inferno.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 208 of file Inferno.java.
{
        if (!Area.inInferno(player)) {
            cleanup();
            remove(player);
            player.send(new SendMessage("You have lost your current progress as you have teleported."));
        }
    }
References cleanup(), com.runehive.game.world.position.Area.inInferno(), and player.
start()
void com.runehive.content.activity.inferno.Inferno.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 112 of file Inferno.java.
{
        if (wave == null) {
            finish();
            return;
        }
        if (player.locking.locked()) {
            return;
        }
        Position spawn = new Position(2273, 5337, player.getHeight());
        Position[] boundaries = Utility.getInnerBoundaries(spawn, Utility.random(1, 8), Utility.random(1, 8));
        for (int id : wave.getMonster()) {
            Npc npc = new Npc(id, RandomUtils.random(boundaries));
            npc.owner = player;
            add(npc);
            npcs.add(npc);
            npc.getCombat().attack(player);
            npc.face(player);
            npc.attack(player);
            player.face(npc.getPosition());
            npc.locking.unlock();
            // pause();
        }
        if (wave == InfernoWaveData.WaveData.WAVE_69) {
            player.message("WAVE 69 is here!!");
        }
        pause();
    }
References com.runehive.content.activity.Activity.add(), com.runehive.game.world.entity.mob.Mob.attack(), com.runehive.game.world.entity.mob.Mob.face(), finish(), com.runehive.game.world.entity.mob.npc.Npc.getCombat(), com.runehive.util.Utility.getInnerBoundaries(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.Mob.locking, npcs, com.runehive.content.activity.Activity.pause(), player, com.runehive.util.RandomUtils.random(), com.runehive.util.Utility.random(), com.runehive.game.world.entity.mob.Locking.unlock(), wave, and com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_69.
update()
void com.runehive.content.activity.inferno.Inferno.update ()
The update method.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 186 of file Inferno.java.
{
        if (wave == null) {
            ActivityPanel.update(player, 100, "Inferno", new Item(21295), "Congratulations, you have",
                    "completed the Inferno", "activity!");
            return;
        }
        int progress = (int) Utility.getPercentageAmount(wave.ordinal() + 1, InfernoWaveData.WaveData.values().length);
        if (progress >= 100 && !completed)
            progress = 99;
        ActivityPanel.update(player, progress, "Inferno", new Item(22325),
                "</col>Wave: <col=FF5500>" + (wave.ordinal() + 1) + "/" + (InfernoWaveData.WaveData.values().length),
                "</col>Monsters Left: <col=FF5500>" + npcs.size(),
                "</col>Points Gained: <col=FF5500>" + Utility.formatDigits(rewards),
                "</col>Time: <col=FF5500>" + Utility.getTime());
    }
References completed, com.runehive.util.Utility.formatDigits(), com.runehive.util.Utility.getPercentageAmount(), com.runehive.util.Utility.getTime(), npcs, player, rewards, com.runehive.content.activity.panel.ActivityPanel.update(), and wave.
Member Data Documentation
completed
boolean com.runehive.content.activity.inferno.Inferno.completed private
The activity completed flag.
Definition at line 32 of file Inferno.java.
Referenced by finish(), handleDeath(), and update().
listener
final InfernoCavesListener com.runehive.content.activity.inferno.Inferno.listener = new InfernoCavesListener(this) private
The combat listener to add for all mobs.
Definition at line 47 of file Inferno.java.
Referenced by getListener().
npcs
final Set<Npc> com.runehive.content.activity.inferno.Inferno.npcs = new HashSet<>()
A set of npcs in this activity.
Definition at line 41 of file Inferno.java.
Referenced by cleanup(), handleDeath(), start(), and update().
player
final Player com.runehive.content.activity.inferno.Inferno.player private
The player in the Inferno.
Definition at line 29 of file Inferno.java.
Referenced by canTeleport(), cleanup(), create(), finish(), handleDeath(), Inferno(), onLogout(), onRegionChange(), start(), and update().
rewards
int com.runehive.content.activity.inferno.Inferno.rewards private
The amount of rewards the player has acquired.
Definition at line 38 of file Inferno.java.
Referenced by finish(), handleDeath(), and update().
time
long com.runehive.content.activity.inferno.Inferno.time private
The time it took to complete the activity.
Definition at line 35 of file Inferno.java.
Referenced by finish().
wave
InfernoWaveData.WaveData com.runehive.content.activity.inferno.Inferno.wave = InfernoWaveData.WaveData.WAVE_1 private
The current wave of this activity.
Definition at line 44 of file Inferno.java.
Referenced by handleDeath(), start(), and update().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/inferno/Inferno.java