RuneHive-Game: dev.advo.fs.fs.FileDescriptor Class Reference
dev.advo.fs.fs.FileDescriptor Class Reference
A class which points to a file in the cache.
Public Member Functions
FileDescriptor (int type, int file)
Creates the file descriptor.
int getFile ()
Gets the file id.
int getType ()
Gets the file type.
String toString ()
Private Attributes
final int file
The file id.
final int type
The file type.
Detailed Description
A class which points to a file in the cache.
Author
Graham
Definition at line 7 of file FileDescriptor.java.
Constructor & Destructor Documentation
FileDescriptor()
dev.advo.fs.fs.FileDescriptor.FileDescriptor (int type, int file)
Creates the file descriptor.
Parameters
type The file type.
file The file id.
Definition at line 29 of file FileDescriptor.java.
{
        this.type = type;
        this.file = file;
    }
References file, and type.
Member Function Documentation
getFile()
int dev.advo.fs.fs.FileDescriptor.getFile ()
Gets the file id.
Returns
The file id.
Definition at line 46 of file FileDescriptor.java.
{
        return file;
    }
References file.
Referenced by dev.advo.fs.net.ondemand.OnDemandResponseEncoder.encode().
getType()
int dev.advo.fs.fs.FileDescriptor.getType ()
Gets the file type.
Returns
The file type.
Definition at line 38 of file FileDescriptor.java.
{
        return type;
    }
References type.
Referenced by dev.advo.fs.net.ondemand.OnDemandResponseEncoder.encode().
toString()
String dev.advo.fs.fs.FileDescriptor.toString ()
Definition at line 10 of file FileDescriptor.java.
{
        return " [type=" + type + ", file=" + file + "]";
    }
References file, and type.
Referenced by dev.advo.fs.dispatch.OnDemandRequestWorker.service().
Member Data Documentation
file
final int dev.advo.fs.fs.FileDescriptor.file private
The file id.
Definition at line 22 of file FileDescriptor.java.
Referenced by FileDescriptor(), getFile(), and toString().
type
final int dev.advo.fs.fs.FileDescriptor.type private
The file type.
Definition at line 17 of file FileDescriptor.java.
Referenced by FileDescriptor(), getType(), and toString().
The documentation for this class was generated from the following file:
java/dev/advo/fs/fs/FileDescriptor.java