RuneHive-Game: com.runehive.game.task.TaskManager Class Reference
com.runehive.game.task.TaskManager Class Reference
The class that handles scheduling tasks, and processing them.
Public Member Functions
void cancel (Object attachment)
Cancels a task that has a specific attachment.
void cancel (Object attachment, boolean logout)
Cancels a task that has a specific attachment.
List< Task > getTasks ()
synchronized void processTasks ()
This method handles adding new tasks and processing of active tasks.
synchronized void schedule (Task task)
Schedules a Task to be ran in the future.
Private Attributes
final List< Task > active = new ArrayList<>()
The list of tasks that are currently running.
final Queue< Task > pending = new ConcurrentLinkedQueue<>()
The queue of tasks that are waiting to be executed.
Static Private Attributes
static final Logger logger = LogManager.getLogger(TaskManager.class)
The single logger for this class.
Detailed Description
The class that handles scheduling tasks, and processing them.
Author
nshusa
Definition at line 18 of file TaskManager.java.
Member Function Documentation
cancel() [1/2]
void com.runehive.game.task.TaskManager.cancel (Object attachment)
Cancels a task that has a specific attachment.
Parameters
attachment The object that is attached to the task.
Definition at line 109 of file TaskManager.java.
{
        cancel(attachment, false);
    }
References cancel().
Referenced by cancel().
cancel() [2/2]
void com.runehive.game.task.TaskManager.cancel (Object attachment, boolean logout)
Cancels a task that has a specific attachment.
Parameters
attachment The object that is attached to the task.
logout When the task gets canceled this flag determines if the player should logout.
Definition at line 122 of file TaskManager.java.
{
        for (Task task : pending) {
            if (attachment.equals(task.getAttachment().orElse(null))) {
                task.cancel(logout);
            }
        }
    }
References pending.
getTasks()
List< Task > com.runehive.game.task.TaskManager.getTasks ()
Definition at line 130 of file TaskManager.java.
{
        return active;
    }
References active.
processTasks()
synchronized void com.runehive.game.task.TaskManager.processTasks ()
This method handles adding new tasks and processing of active tasks.
Definition at line 79 of file TaskManager.java.
{
        Task t;
        while((t = pending.poll()) != null) {
            active.add(t);
        }
        for (final ListIterator<Task> itr = active.listIterator(); itr.hasNext();) {
            final Task task = itr.next();
            try {
                //Start execution is called before process so that the task can get the elapsed time from the start of the task
                task.setExecutionTime();
                task.process();
            } catch (Exception ex) {
                logger.warn(String.format("Error executing task: %s [pendingQueue: %d executionQueue: %d], ", task.getClass().getSimpleName(), pending.size(), active.size()), ex);
                task.cancel();
            }
            if (!task.isRunning()) {
                itr.remove();
            }
        }
    }
References active, logger, and pending.
schedule()
synchronized void com.runehive.game.task.TaskManager.schedule (Task task)
Schedules a Task to be ran in the future.
Parameters
task The task to schedule.
Definition at line 44 of file TaskManager.java.
{
        /*StackTraceElement[] stackTrace = Thread.currentThread().getStackTrace();
        System.out.println("Displaying Stack trace using StackTraceElement in Java");
        String myString = "";
        for(StackTraceElement st : stackTrace){
            myString = myString + st + '\n';
        }
        LogManager.getLogger().info(myString);*/
        Preconditions.checkNotNull(task);
        try {
            if (!task.canSchedule()) {
                return;
            }
            task.setRunning(true);
            task.onSchedule();
            if (task.isInstant()) {
                try {
                    task.baseExecute();
                } catch (Exception ex) {
                    logger.warn(String.format("error executing task: %s", task.getClass().getSimpleName()), ex);
                    return;
                }
            }
            pending.add(task);
        } catch (Exception ex) {
            logger.error(String.format("error scheduling task: %s", task.getClass().getSimpleName()), ex);
        }
    }
References logger, and pending.
Member Data Documentation
active
final List<Task> com.runehive.game.task.TaskManager.active = new ArrayList<>() private
The list of tasks that are currently running.
A ArrayList is used here for very fast iteration speed.
Definition at line 36 of file TaskManager.java.
Referenced by getTasks(), and processTasks().
logger
final Logger com.runehive.game.task.TaskManager.logger = LogManager.getLogger(TaskManager.class) static private
The single logger for this class.
Definition at line 23 of file TaskManager.java.
Referenced by processTasks(), and schedule().
pending
final Queue<Task> com.runehive.game.task.TaskManager.pending = new ConcurrentLinkedQueue<>() private
The queue of tasks that are waiting to be executed.
A ConcurrentLinkedQueue is used here so tasks can be added safely from multiple threads.
Definition at line 30 of file TaskManager.java.
Referenced by cancel(), processTasks(), and schedule().
The documentation for this class was generated from the following file:
java/com/runehive/game/task/TaskManager.java