RuneHive-Game: com.runehive.content.skill.impl.thieving.Thieving Class Reference
com.runehive.content.skill.impl.thieving.Thieving Class Reference
Handles the thieving skill.
Public Member Functions
Thieving (int level, double experience)
Public Member Functions inherited from com.runehive.game.world.entity.skill.Skill
double addExperience (double amount)
Adds experiences to this skill by the given amount.
void addLevel (int amount)
Adds levels to this skill by the given amount.
void divideExperience (double amount)
Divides the current experience of this skill by a given amount.
void divideLevel (double amount)
Divides the current level of this skill by a given amount.
double getExperience ()
Gets the skill experience.
int getLevel ()
Gets the current skill level.
int getMaxLevel ()
Gets the maximum skill level.
int getRoundedExperience ()
Gets the floor experience.
int getSkill ()
Gets the skill id.
boolean isDoingSkill ()
double modifyExperience (Function< Double, Double > function)
Modifies the current experience with a given function.
double modifyExperience (Function< Double, Double > function, int lowerBounds, int upperBounds)
Modifies the current experience with a given function.
void modifyLevel (Function< Integer, Integer > function)
Modifies the current level with a given function.
void modifyLevel (Function< Integer, Integer > function, int lowerBounds, int upperBounds)
Modifies the current level with a given function.
void multiplyExperience (double amount)
Multiplies the current experience of this skill by a given amount.
void multiplyLevel (double amount)
Multiplies the current level of this skill by a given amount.
boolean onEvent (Player player, InteractionEvent interactionEvent)
void removeExperience (double amount)
Removes experiences from this skill by the given amount.
void removeLevel (int amount)
Removes levels from this skill by the given amount.
boolean reqLevel (int level)
Determines if your level is greater than or equal to level.
void setDoingSkill (boolean doingSkill)
void setExperience (double experience)
Sets the experience for this skill.
void setLevel (int level)
Sets the level for this skill.
void setMaxLevel (int maxLevel)
Sets the maximum level for this skill.
Skill (int skill, int level, double experience)
Constructs a new Skill.
String toString ()
Static Public Member Functions
static void exchange (Player player)
Static Public Member Functions inherited from com.runehive.game.world.entity.skill.Skill
static Function< Integer, Integer > add (int amount)
Creates a function that adds a number by an amount.
static Function< Integer, Integer > divide (double amount)
Creates a function that divides a number by an amount.
static final int getExperienceForLevel (int level)
Gets the experience for a given level.
static final byte getLevelForExperience (double experience)
Gets the level for a given experience amount.
static String getName (int skill)
Gets the name for a skill id.
static Function< Integer, Integer > multiply (double amount)
Creates a function that multiplies a number by an amount.
static Function< Integer, Integer > subtract (int amount)
Creates a function that subtracts a number by an amount.
Protected Member Functions
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
double modifier ()
Protected Member Functions inherited from com.runehive.game.world.entity.skill.Skill
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
int failureRate (PickpocketData pickpocket, Player player)
The failure rate for pickpocketing.
Additional Inherited Members
Public Attributes inherited from com.runehive.game.world.entity.skill.Skill
transient final Stopwatch stopwatch = Stopwatch.start()
Static Public Attributes inherited from com.runehive.game.world.entity.skill.Skill
static final int AGILITY = 16
The agility skill id.
static final int ATTACK = 0
The attack skill id.
static final int CONSTRUCTION = 21
The construction skill id.
static final int COOKING = 7
The cooking skill id.
static final int CRAFTING = 12
The crafting skill id.
static final int DEFENCE = 1
The defence skill id.
static final int FARMING = 19
The farming skill id.
static final int FIREMAKING = 11
The firemaking skill id.
static final int FISHING = 10
The fishing skill id.
static final int FLETCHING = 9
The fletching skill id.
static final int HERBLORE = 15
The herblore skill id.
static final int HITPOINTS = 3
The hitpoints skill id.
static final int HUNTER = 22
The hunter skill id.
static final int[][] INTERFACE_DATA
Skill tab string data.
static final int MAGIC = 6
The magic skill id.
static final int MINING = 14
The mining skill id.
static final int PRAYER = 5
The prayer skill id.
static final int RANGED = 4
The ranged skill id.
static final int RUNECRAFTING = 20
The runecrafting skill id.
static final int SKILL_COUNT = 23
The amount of available skills.
static final int SLAYER = 18
The slayer skill id.
static final int SMITHING = 13
The smithing skill id.
static final int STRENGTH = 2
The strength skill id.
static final int THIEVING = 17
The thieving skill id.
static final int TOTAL_SKILL_LEVEL = 99 * SKILL_COUNT
The total skill amount.
static final int WOODCUTTING = 8
The woodcutting skill id.
Detailed Description
Handles the thieving skill.
Author
Daniel
Definition at line 31 of file Thieving.java.
Constructor & Destructor Documentation
Thieving()
com.runehive.content.skill.impl.thieving.Thieving.Thieving (int level, double experience)
Definition at line 33 of file Thieving.java.
{
        super(Skill.THIEVING, level, experience);
    }
References com.runehive.game.world.entity.skill.Skill.experience, com.runehive.game.world.entity.skill.Skill.level, and com.runehive.game.world.entity.skill.Skill.Skill().
Member Function Documentation
clickNpc()
boolean com.runehive.content.skill.impl.thieving.Thieving.clickNpc (Player player, NpcInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 52 of file Thieving.java.
{
        if (event.getOpcode() != 1) {
            return false;
        }
        Npc npc = event.getNpc();
        PickpocketData pickpocket = PickpocketData.forId(npc.id);
        if (pickpocket == null) {
            return false;
        }
        if (player.skills.get(THIEVING).isDoingSkill()) {
            return true;
        }
        if (player.skills.getLevel(Skill.THIEVING) < pickpocket.getLevel()) {
            player.send(new SendMessage("You need a thieving level of " + pickpocket.getLevel() + " to do this!"));
            return true;
        }
        boolean failed = Utility.random(100) < failureRate(pickpocket, player);
        player.animate(new Animation(881));
        player.locking.lock(1, LockType.MASTER);
        player.skills.get(THIEVING).setDoingSkill(true);
        player.send(new SendMessage("You attempt to pickpocket the " + npc.getName() + "..."));
        World.schedule(2, () -> {
            if (failed) {
                npc.animate(new Animation(422));
                npc.speak("What do you think you're doing?");
                player.locking.lock(pickpocket.getStun(), LockType.STUN);
                player.damage(new Hit(Utility.random(pickpocket.getDamage())));
                player.send(new SendMessage("You failed to pickpocketing the " + npc.getName() + "."));
                return;
            }
            double experience = Area.inSuperDonatorZone(player) || Area.inRegularDonatorZone(player) ? pickpocket.getExperience() * 2 : pickpocket.getExperience();
            player.skills.get(THIEVING).setDoingSkill(false);
            player.inventory.add(Utility.randomElement(pickpocket.getLoot()));
            player.send(new SendMessage("You have successfully pickpocket the " + npc.getName() + "."));
            player.skills.addExperience(Skill.THIEVING, experience * Config.THIEVING_MODIFICATION);
            RandomEventHandler.trigger(player);
            Pets.onReward(player, PetData.ROCKY);
            player.playerAssistant.activateSkilling(1);
        });
        return true;
    }
References com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.Mob.damage(), com.runehive.game.world.entity.skill.Skill.experience, failureRate(), com.runehive.content.skill.impl.thieving.PickpocketData.forId(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.content.skill.impl.thieving.PickpocketData.getDamage(), com.runehive.content.skill.impl.thieving.PickpocketData.getExperience(), com.runehive.content.skill.impl.thieving.PickpocketData.getLevel(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.content.skill.impl.thieving.PickpocketData.getLoot(), com.runehive.game.world.entity.mob.npc.Npc.getName(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.content.skill.impl.thieving.PickpocketData.getStun(), com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.position.Area.inRegularDonatorZone(), com.runehive.game.world.position.Area.inSuperDonatorZone(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.skill.Skill.isDoingSkill(), com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, com.runehive.game.world.entity.mob.data.LockType.MASTER, com.runehive.content.pet.Pets.onReward(), com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.util.Utility.random(), com.runehive.util.Utility.randomElement(), com.runehive.content.pet.PetData.ROCKY, com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.skill.Skill.setDoingSkill(), com.runehive.game.world.entity.skill.Skill.Skill(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.mob.Mob.speak(), com.runehive.game.world.entity.mob.data.LockType.STUN, com.runehive.game.world.entity.skill.Skill.THIEVING, com.runehive.Config.THIEVING_MODIFICATION, and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
clickObject()
boolean com.runehive.content.skill.impl.thieving.Thieving.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 104 of file Thieving.java.
{
        if (event.getOpcode() == 0 && event.getObject().getId() == 7236) {
            WallSafe.thieve(player);
            return true;
        }
        if (event.getOpcode() != 1) {
            return false;
        }
        GameObject object = event.getObject();
        if (!StallData.forId(object.getId()).isPresent()) {
            return false;
        }
        StallData stall = StallData.forId(object.getId()).get();
        if (!player.inventory.hasCapacityFor(stall.getItem())) {
            player.send(new SendMessage("You need at least 1 free inventory space to do this!"));
            return true;
        }
        if (player.skills.get(THIEVING).getLevel() < stall.getLevel()) {
            player.send(new SendMessage("You need a thieving level of " + stall.getLevel() + " to steal from this stall."));
            return true;
        }
        if (player.skills.get(THIEVING).isDoingSkill()) {
            return true;
        }
        int base_chance = 50;
        int modified_chance = (int) (PlayerRight.isDonator(player) ? base_chance * 2.3
                : SkillCape.isEquipped(player, SkillCape.THIEVING) ? 2.2 : base_chance);
        boolean failed = Utility.random(modified_chance) == 0;
        player.animate(new Animation(832));
        player.locking.lock(1, LockType.MASTER);
        player.skills.get(THIEVING).setDoingSkill(true);
        World.schedule(3, () -> {
            double experience = stall.getExperience() * Config.THIEVING_MODIFICATION;
            double newExperience = Area.inSuperDonatorZone(player) || Area.inRegularDonatorZone(player)? experience * 2 : experience;
            if (failed) {
                player.damage(new Hit(Utility.random(3, 6)));
                player.speak("Ouch!");
                player.send(new SendMessage("You failed to thieve from the stall and were instead inflicted pain!"));
                return;
            }
            player.inventory.add(stall.getItem());
            if (PlayerRight.isSuper(player) && Utility.random(0, 10) > 8) {
                player.inventory.addOrDrop(stall.getItem());
            }
            player.skills.get(THIEVING).setDoingSkill(false);
            player.skills.addExperience(THIEVING, newExperience);
            player.forClan(channel -> channel.activateTask(ClanTaskKey.THIEVING_STALL, player.getName()));
            Pets.onReward(player, PetData.ROCKY);
            RandomEventHandler.trigger(player);
            player.playerAssistant.activateSkilling(1);
        });
        return true;
    }
References com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.Mob.damage(), com.runehive.game.world.entity.skill.Skill.experience, com.runehive.game.world.entity.mob.player.Player.forClan(), com.runehive.content.skill.impl.thieving.StallData.forId(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.content.skill.impl.thieving.StallData.getExperience(), com.runehive.content.skill.impl.thieving.StallData.getItem(), com.runehive.content.skill.impl.thieving.StallData.getLevel(), com.runehive.game.world.entity.skill.Skill.getLevel(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.position.Area.inRegularDonatorZone(), com.runehive.game.world.position.Area.inSuperDonatorZone(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.skill.Skill.isDoingSkill(), com.runehive.game.world.entity.mob.player.PlayerRight.isDonator(), com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.game.world.entity.mob.player.PlayerRight.isSuper(), com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, com.runehive.game.world.entity.mob.data.LockType.MASTER, com.runehive.content.pet.Pets.onReward(), com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.util.Utility.random(), com.runehive.content.pet.PetData.ROCKY, com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.skill.Skill.setDoingSkill(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.mob.Mob.speak(), com.runehive.content.skill.impl.thieving.WallSafe.thieve(), com.runehive.content.skillcape.SkillCape.THIEVING, com.runehive.game.world.entity.skill.Skill.THIEVING, com.runehive.Config.THIEVING_MODIFICATION, com.runehive.content.clanchannel.content.ClanTaskKey.THIEVING_STALL, and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
exchange()
void com.runehive.content.skill.impl.thieving.Thieving.exchange (Player player) static
Definition at line 172 of file Thieving.java.
{
        int amount = 0, count = 0;
        for (Item item : player.inventory.toArray()) {
            if (StallData.isReward(item) && player.inventory.remove(item, -1, false)) {
                amount += StallData.getValue(item);
                count++;
            }
        }
        if (count == 0) {
            player.dialogueFactory.sendNpcChat(3439, Expression.ANGRY, "You do not have any items of which I am interested", "in purchasing.").execute();
            return;
        }
        if (player.inventory.add(new Item(Config.CURRENCY, amount))) {
            player.send(new SendMessage("You have exchanged " + count + " goods for " + Utility.formatDigits(amount) + " coins."));
            player.inventory.refresh();
            return;
        }
        player.send(new SendMessage("You have no items which the merchant would like to purchase."));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), com.runehive.content.dialogue.Expression.ANGRY, com.runehive.Config.CURRENCY, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.util.Utility.formatDigits(), com.runehive.content.skill.impl.thieving.StallData.getValue(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.thieving.StallData.isReward(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), and com.runehive.game.world.items.containers.ItemContainer.toArray().
failureRate()
int com.runehive.content.skill.impl.thieving.Thieving.failureRate (PickpocketData pickpocket, Player player) private
The failure rate for pickpocketing.
Definition at line 40 of file Thieving.java.
{
        double f1 = (double) pickpocket.getLevel() / 10;
        double f2 = (double) 100 / ((player.skills.getMaxLevel(Skill.THIEVING) + 1) - pickpocket.getLevel());
        return (int) Math.floor((f2 + f1) / 2);
    }
References com.runehive.content.skill.impl.thieving.PickpocketData.getLevel(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.skill.Skill.Skill(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by clickNpc().
modifier()
double com.runehive.content.skill.impl.thieving.Thieving.modifier () protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 47 of file Thieving.java.
{
        return Config.THIEVING_MODIFICATION;
    }
References com.runehive.Config.THIEVING_MODIFICATION.
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/thieving/Thieving.java