RuneHive-Game: com.runehive.content.activity.impl.duelarena.DuelArenaActivity Class Reference
com.runehive.content.activity.impl.duelarena.DuelArenaActivity Class Reference
The duel arena activity.
Classes
class DuelPanel
Public Member Functions
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cleanup ()
Cleans up the activity when finished.
ActivityDeathType deathType ()
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void sequence ()
Sequences the activity.
void update ()
The update method.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canSpellCast (Player player)
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
void onRegionChange (Player player)
Called when the player changes region.
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
Static Public Member Functions
static DuelArenaActivity create (StakeSession session, Player player, Player opponent)
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Public Attributes
boolean hasLoser
final DuelRules rules = new DuelRules()
The duel rules for this duel session.
boolean started
Whether or not the duel has started.
Protected Member Functions
boolean clickObject (Player player, ObjectInteractionEvent event)
Optional< DuelArenaListener > getListener ()
Gets an Optional of the ActivityListener for this activity.
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Package Attributes
final Player opponent
The player accepting the duel.
final Player player
The player requesting the duel.
Private Member Functions
DuelArenaActivity (StakeSession session, Player player, Player opponent)
void reward (Player player, Player loser, Item[] reward, long value, boolean stalemate)
void reward (Player winner, Player loser, boolean stalemate)
void unequipItems (Player player)
Private Attributes
final DuelArenaListener listener = new DuelArenaListener(this)
The combat listener for the duel.
Player loser
DuelPanel opponentPanel
The opponent activity panel.
DuelPanel playerPanel
The player activity panel.
boolean rewarded
Whether or not the reward has been given.
final StakeSession session
The duel stake session (holds items).
Player winner
The duel outcome.
Static Private Attributes
static final Position[] ARENAS
The mid-points of all three duel arenas.
static final Position HOSPITAL_BEDS_SOUTHWEST = new Position(3361, 3272)
The south-west tile of the hospital bed area.
static final Position[] OBSTACLE_ARENAS
The mid-points of all three obstacle duel arenas.
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
The duel arena activity.
Author
Michael | Chex
Definition at line 43 of file DuelArenaActivity.java.
Constructor & Destructor Documentation
DuelArenaActivity()
com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelArenaActivity (StakeSession session, Player player, Player opponent) private
Definition at line 95 of file DuelArenaActivity.java.
{
        super(1, Entity.DEFAULT_INSTANCE);
        this.session = session;
        this.player = player;
        this.opponent = opponent;
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, opponent, player, and session.
Referenced by create(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.DuelPanel().
Member Function Documentation
canDrinkPotions()
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canDrinkPotions (Player player)
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 292 of file DuelArenaActivity.java.
{
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return true;
        }
        if (rules.contains(DuelRule.NO_DRINKS)) {
            player.send(new SendMessage("Potions have been disabled!"));
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.content.activity.impl.duelarena.DuelRule.NO_DRINKS, opponent, player, com.runehive.content.activity.Activity.removeAll(), rules, and session.
canEat()
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEat (Player player, FoodData foodType)
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 325 of file DuelArenaActivity.java.
{
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return true;
        }
        if (rules.contains(DuelRule.NO_FOOD)) {
            player.send(new SendMessage("Food has been disabled!"));
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.content.activity.impl.duelarena.DuelRule.NO_FOOD, opponent, player, com.runehive.content.activity.Activity.removeAll(), rules, and session.
canEquipItem()
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem (Player player, Item item, EquipmentType type)
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 357 of file DuelArenaActivity.java.
{
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return true;
        }
        if (type == null) {
            return false;
        }
        if (rules.contains(DuelRule.LOCK_ITEMS)) {
            player.send(new SendMessage("Item switching has been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.ONLY_WHIP_DDS)) {
            final String name = item.getName() == null ? "null" : item.getName().toLowerCase();
            if (!name.contains("dragon dagger") && !name.contains("abyssal whip") && !name.contains("abyssal tentacle")) {
                player.send(new SendMessage("You can only use a whip or dragon dagger!"));
                return false;
            }
        }
        if (rules.contains(DuelRule.ONLY_FUN_WEAPONS) && !DuelUtils.hasFunWeapon(player, item)) {
            player.send(new SendMessage("You can only use fun weapons!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_WEAPON) && type.getSlot() == Equipment.WEAPON_SLOT) {
            player.send(new SendMessage("Weapons have been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_SHIELD) && type.getSlot() == Equipment.SHIELD_SLOT) {
            player.send(new SendMessage("Shields have been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_AMMO) && type.getSlot() == Equipment.ARROWS_SLOT) {
            player.send(new SendMessage("Ammo has been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_HEAD) && type.getSlot() == Equipment.HEAD_SLOT) {
            player.send(new SendMessage("Helms have been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_CAPE) && type.getSlot() == Equipment.CAPE_SLOT) {
            player.send(new SendMessage("Capes have been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_NECKLACE) && type.getSlot() == Equipment.AMULET_SLOT) {
            player.send(new SendMessage("Amulets hae been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_BODY) && type.getSlot() == Equipment.CHEST_SLOT) {
            player.send(new SendMessage("Chest items have been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_LEGS) && type.getSlot() == Equipment.LEGS_SLOT) {
            player.send(new SendMessage("Leg items have been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_GLOVES) && type.getSlot() == Equipment.HANDS_SLOT) {
            player.send(new SendMessage("Gloves have been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_BOOTS) && type.getSlot() == Equipment.FEET_SLOT) {
            player.send(new SendMessage("Boots have been disabled!"));
            return false;
        }
        if (rules.contains(DuelRule.NO_RINGS) && type.getSlot() == Equipment.RING_SLOT) {
            player.send(new SendMessage("Rings have been disabled!"));
            return false;
        }
        return true;
    }
References com.runehive.game.world.items.containers.equipment.Equipment.AMULET_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.ARROWS_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.CAPE_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.CHEST_SLOT, com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.game.world.items.containers.equipment.Equipment.FEET_SLOT, com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.containers.equipment.EquipmentType.getSlot(), com.runehive.game.world.items.containers.equipment.Equipment.HANDS_SLOT, com.runehive.content.activity.impl.duelarena.DuelUtils.hasFunWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.HEAD_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.LEGS_SLOT, com.runehive.content.activity.impl.duelarena.DuelRule.LOCK_ITEMS, com.runehive.content.activity.impl.duelarena.DuelRule.NO_AMMO, com.runehive.content.activity.impl.duelarena.DuelRule.NO_BODY, com.runehive.content.activity.impl.duelarena.DuelRule.NO_BOOTS, com.runehive.content.activity.impl.duelarena.DuelRule.NO_CAPE, com.runehive.content.activity.impl.duelarena.DuelRule.NO_GLOVES, com.runehive.content.activity.impl.duelarena.DuelRule.NO_HEAD, com.runehive.content.activity.impl.duelarena.DuelRule.NO_LEGS, com.runehive.content.activity.impl.duelarena.DuelRule.NO_NECKLACE, com.runehive.content.activity.impl.duelarena.DuelRule.NO_RINGS, com.runehive.content.activity.impl.duelarena.DuelRule.NO_SHIELD, com.runehive.content.activity.impl.duelarena.DuelRule.NO_WEAPON, com.runehive.content.activity.impl.duelarena.DuelRule.ONLY_FUN_WEAPONS, com.runehive.content.activity.impl.duelarena.DuelRule.ONLY_WHIP_DDS, opponent, player, com.runehive.content.activity.Activity.removeAll(), com.runehive.game.world.items.containers.equipment.Equipment.RING_SLOT, rules, session, com.runehive.game.world.items.containers.equipment.Equipment.SHIELD_SLOT, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
canLogout()
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canLogout (Player player)
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 279 of file DuelArenaActivity.java.
{
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return true;
        }
        player.send(new SendMessage("You cannot logout in the duel arena!"));
        return false;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, opponent, player, com.runehive.content.activity.Activity.removeAll(), and session.
canUsePrayer()
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canUsePrayer (Player player)
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 308 of file DuelArenaActivity.java.
{
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return true;
        }
        if (rules.contains(DuelRule.NO_PRAYER)) {
            player.send(new SendMessage("Prayer has been disabled!"));
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.content.activity.impl.duelarena.DuelRule.NO_PRAYER, opponent, player, com.runehive.content.activity.Activity.removeAll(), rules, and session.
canUseSpecial()
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canUseSpecial (Player player)
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 341 of file DuelArenaActivity.java.
{
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return true;
        }
        if (rules.contains(DuelRule.NO_SPECIAL_ATTACK)) {
            player.send(new SendMessage("Special attacks have been disabled!"));
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.content.activity.impl.duelarena.DuelRule.NO_SPECIAL_ATTACK, opponent, player, com.runehive.content.activity.Activity.removeAll(), rules, and session.
cleanup()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 236 of file DuelArenaActivity.java.
{}
clickObject()
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 509 of file DuelArenaActivity.java.
{
        switch(event.getObject().getId()) {
            case 3111:
            case 3113:
            case 3203:
                if (!session.accepted) {
                    player.exchangeSession.reset(ExchangeSessionType.DUEL);
                    opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
                    removeAll(player, opponent);
                    return true;
                }
                if (rules.contains(DuelRule.NO_FORFEIT)) {
                    player.send(new SendMessage("Forfeiting has been disabled!"));
                    return true;
                }
                if (!started) {
                    player.send(new SendMessage("You can't forfeit yet!"));
                    return true;
                }
                finishCooldown();
                if (player.equals(this.player)) {
                    winner = opponent;
                    loser = this.player;
                } else if (player.equals(opponent)) {
                    winner = this.player;
                    loser = opponent;
                }
                return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.content.activity.Activity.finishCooldown(), loser, com.runehive.content.activity.impl.duelarena.DuelRule.NO_FORFEIT, opponent, player, com.runehive.content.activity.Activity.removeAll(), rules, session, started, and winner.
create()
DuelArenaActivity com.runehive.content.activity.impl.duelarena.DuelArenaActivity.create (StakeSession session, Player player, Player opponent) static
Definition at line 102 of file DuelArenaActivity.java.
{
        DuelArenaActivity duel = new DuelArenaActivity(session, player, opponent);
        duel.pause();
        duel.add(player);
        duel.add(opponent);
        duel.playerPanel = new DuelPanel(duel, player);
        duel.opponentPanel = new DuelPanel(duel, opponent);
        return duel;
    }
References com.runehive.content.activity.Activity.add(), DuelArenaActivity(), opponent, com.runehive.content.activity.Activity.pause(), player, and session.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onRequest().
deathType()
ActivityDeathType com.runehive.content.activity.impl.duelarena.DuelArenaActivity.deathType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 556 of file DuelArenaActivity.java.
{
        return ActivityDeathType.SAFE;
    }
References com.runehive.content.activity.ActivityDeathType.SAFE.
finish()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 192 of file DuelArenaActivity.java.
{
        if (rewarded) {
            return;
        }
        player.playerAssistant.restore();
        opponent.playerAssistant.restore();
        player.move(TraversalMap.getRandomTraversableTile(HOSPITAL_BEDS_SOUTHWEST, 14, 7));
        player.send(new SendEntityHintArrow(opponent, true));
        opponent.move(TraversalMap.getRandomTraversableTile(HOSPITAL_BEDS_SOUTHWEST, 14, 7));
        opponent.send(new SendEntityHintArrow(player, true));
        if (winner == null || loser == null) {
            player.message("The duel was a stalemate!");
            opponent.message("The duel was a stalemate!");
            reward(player, opponent, true);
            rewarded = true;
            removeAll(player, opponent);
            playerPanel.close();
            opponentPanel.close();
            return;
        }
        winner.message("You are victorious!");
        loser.message("You lost!");
        reward(winner, loser, false);
        rewarded = true;
        removeAll(player, opponent);
        playerPanel.close();
        opponentPanel.close();
        player.animate(Animation.RESET, true);
        player.graphic(Graphic.RESET, true);
        opponent.animate(Animation.RESET, true);
        opponent.graphic(Graphic.RESET, true);
    }
References com.runehive.game.world.pathfinding.TraversalMap.getRandomTraversableTile(), HOSPITAL_BEDS_SOUTHWEST, loser, opponent, opponentPanel, player, playerPanel, com.runehive.content.activity.Activity.removeAll(), com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, reward(), rewarded, and winner.
getListener()
Optional< DuelArenaListener > com.runehive.content.activity.impl.duelarena.DuelArenaActivity.getListener () protected
Gets an Optional of the ActivityListener for this activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 546 of file DuelArenaActivity.java.
{
        return Optional.of(listener);
    }
References listener.
getType()
ActivityType com.runehive.content.activity.impl.duelarena.DuelArenaActivity.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 551 of file DuelArenaActivity.java.
{
        return ActivityType.DUEL_ARENA;
    }
References com.runehive.content.activity.ActivityType.DUEL_ARENA.
onDeath()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 239 of file DuelArenaActivity.java.
{
        hasLoser = true;
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return;
        }
        finishCooldown();
        if (mob.equals(player)) {
            winner = opponent;
            loser = player;
        } else if (mob.equals(opponent)) {
            winner = player;
            loser = opponent;
        }
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.game.world.entity.Entity.equals(), com.runehive.content.activity.Activity.finishCooldown(), hasLoser, loser, opponent, player, com.runehive.content.activity.Activity.removeAll(), session, and winner.
onLogout()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 260 of file DuelArenaActivity.java.
{
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return;
        }
        finishCooldown();
        if (player.equals(this.player)) {
            winner = opponent;
            loser = this.player;
        } else if (player.equals(opponent)) {
            winner = this.player;
            loser = opponent;
        }
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.content.activity.Activity.finishCooldown(), loser, opponent, player, com.runehive.content.activity.Activity.removeAll(), session, and winner.
reward() [1/2]
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.reward (Player player, Player loser, Item[] reward, long value, boolean stalemate) private
Definition at line 560 of file DuelArenaActivity.java.
{
        player.send(new SendString("<col=E1981F>Total Value: " + Utility.formatDigits(value), 31709));
        player.send(new SendString(loser.getName(), 31706));
        player.send(new SendString(loser.skills.getCombatLevel(), 31707));
        player.send(new SendItemOnInterface(31708, reward));
        player.send(new SendString(stalemate ? "The duel was a stalemate!" : player.equals(loser) ? "You lost!" : "You are victorious!", 31705));
        player.interfaceManager.open(31700, false);
    }
References com.runehive.util.Utility.formatDigits(), loser, player, and reward().
Referenced by finish(), reward(), and reward().
reward() [2/2]
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.reward (Player winner, Player loser, boolean stalemate) private
Definition at line 569 of file DuelArenaActivity.java.
{
        Objects.requireNonNull(winner);
        Objects.requireNonNull(loser);
        ItemContainer winnerContainer = session.item_containers.get(winner);
        Objects.requireNonNull(winnerContainer);
        ItemContainer loserContainer = session.item_containers.get(loser);
        Objects.requireNonNull(loserContainer);
        if (stalemate) {
            reward(loser, loser, loserContainer.toArray(), loserContainer.containerValue(PriceType.VALUE), true);
            reward(winner, loser, winnerContainer.toArray(), winnerContainer.containerValue(PriceType.VALUE), true);
            winner.inventory.addOrDrop(winnerContainer.toArray());
            loser.inventory.addOrDrop(loserContainer.toArray());
        } else {
            long value = 0;
            ItemContainer rewardContainer = new ItemContainer(28, ItemContainer.StackPolicy.STANDARD);
            rewardContainer.addAll(loserContainer.toArray());
            value += loserContainer.containerValue(PriceType.VALUE);
            reward(loser, loser, rewardContainer.toArray(), value, false);
            value += winnerContainer.containerValue(PriceType.VALUE);
            rewardContainer.addAll(winnerContainer.toArray());
            reward(winner, loser, rewardContainer.toArray(), value, false);
            winner.inventory.addOrDrop(rewardContainer.toArray());
        }
    }
References com.runehive.game.world.items.containers.ItemContainer.addAll(), com.runehive.game.world.items.containers.ItemContainer.containerValue(), loser, reward(), session, com.runehive.game.world.items.containers.ItemContainer.StackPolicy.STANDARD, com.runehive.game.world.items.containers.ItemContainer.toArray(), com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE, and winner.
sequence()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.sequence ()
Sequences the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 113 of file DuelArenaActivity.java.
{
        super.sequence();
        if (isPaused()) {
            return;
        }
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return;
        }
        if (getTicks() < 0) {
            return;
        }
        if (getTicks() == 0) {
            if (started) {
                finishCooldown();
                return;
            }
            player.speak("FIGHT!");
            opponent.speak("FIGHT!");
            started = true;
            // 10 minutes, has to be x2 because 2 players sequence this activity
            cooldown(2000);
        } else if (!started && getTicks() <= 6 && getTicks() % 2 == 0) {
            if (getTicks() == 6) {
                playerPanel.open();
                opponentPanel.open();
            }
            player.speak(String.valueOf(getTicks() / 2));
            opponent.speak(String.valueOf(getTicks() / 2));
        }
    }
References com.runehive.content.activity.Activity.cooldown, com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.content.activity.Activity.finishCooldown(), com.runehive.content.activity.Activity.getTicks(), com.runehive.content.activity.Activity.isPaused(), opponent, opponentPanel, player, playerPanel, com.runehive.content.activity.Activity.removeAll(), session, and started.
start()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 155 of file DuelArenaActivity.java.
{
        unequipItems(player);
        unequipItems(opponent);
        player.playerAssistant.restore();
        opponent.playerAssistant.restore();
        if (rules.contains(DuelRule.OBSTACLES)) {
            player.move(TraversalMap.getRandomTraversableTile(OBSTACLE_ARENAS[0].transform(-3, -3), 3, 3));
            opponent.move(TraversalMap.getRandomTraversableTile(OBSTACLE_ARENAS[0].transform(3, -3), 3, 3));
        } else if (rules.contains(DuelRule.NO_MOVEMENT)) {
            Position position = ARENAS[0].transform(-9, -7);
            position = TraversalMap.getRandomTraversableTile(position, 18, 9);
            if (position == null) {
                finishCooldown();
                return;
            }
            player.move(position);
            position = TraversalMap.getRandomNonDiagonal(position);
            if (position == null) {
                finishCooldown();
                return;
            }
            opponent.move(position);
            player.face(opponent);
            opponent.face(player);
        } else {
            player.move(TraversalMap.getRandomTraversableTile(ARENAS[0].transform(-3, -3), 3, 3));
            opponent.move(TraversalMap.getRandomTraversableTile(ARENAS[0].transform(3, -3), 3, 3));
        }
        player.send(new SendEntityHintArrow(opponent, false));
        opponent.send(new SendEntityHintArrow(player, false));
        cooldown(8);
    }
References ARENAS, com.runehive.content.activity.Activity.cooldown, com.runehive.content.activity.Activity.finishCooldown(), com.runehive.game.world.pathfinding.TraversalMap.getRandomNonDiagonal(), com.runehive.game.world.pathfinding.TraversalMap.getRandomTraversableTile(), com.runehive.content.activity.impl.duelarena.DuelRule.NO_MOVEMENT, OBSTACLE_ARENAS, com.runehive.content.activity.impl.duelarena.DuelRule.OBSTACLES, opponent, player, rules, and unequipItems().
unequipItems()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems (Player player) private
Definition at line 445 of file DuelArenaActivity.java.
{
        if (!session.accepted) {
            player.exchangeSession.reset(ExchangeSessionType.DUEL);
            opponent.exchangeSession.reset(ExchangeSessionType.DUEL);
            removeAll(player, opponent);
            return;
        }
        if (rules.contains(DuelRule.NO_WEAPON) && player.equipment.hasWeapon()) {
            player.equipment.unequip(Equipment.WEAPON_SLOT);
        }
        if (rules.contains(DuelRule.NO_HEAD) && player.equipment.hasHead()) {
            player.equipment.unequip(Equipment.HEAD_SLOT);
        }
        if (rules.contains(DuelRule.NO_CAPE) && player.equipment.hasCape()) {
            player.equipment.unequip(Equipment.CAPE_SLOT);
        }
        if (rules.contains(DuelRule.NO_NECKLACE) && player.equipment.hasAmulet()) {
            player.equipment.unequip(Equipment.AMULET_SLOT);
        }
        if (rules.contains(DuelRule.NO_AMMO) && player.equipment.hasAmmo()) {
            player.equipment.unequip(Equipment.ARROWS_SLOT);
        }
        if (rules.contains(DuelRule.NO_BODY) && player.equipment.hasChest()) {
            player.equipment.unequip(Equipment.CHEST_SLOT);
        }
        if (rules.contains(DuelRule.NO_SHIELD)) {
            if (player.equipment.hasWeapon()) {
                Item weapon = player.equipment.getWeapon();
                if (weapon.isTwoHanded()) {
                    player.equipment.unequip(Equipment.WEAPON_SLOT);
                }
            }
            if (player.equipment.hasShield()) {
                player.equipment.unequip(Equipment.SHIELD_SLOT);
            }
        }
        if (rules.contains(DuelRule.NO_LEGS) && player.equipment.hasLegs()) {
            player.equipment.unequip(Equipment.LEGS_SLOT);
        }
        if (rules.contains(DuelRule.NO_GLOVES) && player.equipment.hasHands()) {
            player.equipment.unequip(Equipment.HANDS_SLOT);
        }
        if (rules.contains(DuelRule.NO_BOOTS) && player.equipment.hasFeet()) {
            player.equipment.unequip(Equipment.FEET_SLOT);
        }
        if (rules.contains(DuelRule.NO_RINGS) && player.equipment.hasRing()) {
            player.equipment.unequip(Equipment.RING_SLOT);
        }
    }
References com.runehive.game.world.items.containers.equipment.Equipment.AMULET_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.ARROWS_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.CAPE_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.CHEST_SLOT, com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.game.world.items.containers.equipment.Equipment.FEET_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.HANDS_SLOT, com.runehive.game.world.items.containers.equipment.Equipment.HEAD_SLOT, com.runehive.game.world.items.Item.isTwoHanded(), com.runehive.game.world.items.containers.equipment.Equipment.LEGS_SLOT, com.runehive.content.activity.impl.duelarena.DuelRule.NO_AMMO, com.runehive.content.activity.impl.duelarena.DuelRule.NO_BODY, com.runehive.content.activity.impl.duelarena.DuelRule.NO_BOOTS, com.runehive.content.activity.impl.duelarena.DuelRule.NO_CAPE, com.runehive.content.activity.impl.duelarena.DuelRule.NO_GLOVES, com.runehive.content.activity.impl.duelarena.DuelRule.NO_HEAD, com.runehive.content.activity.impl.duelarena.DuelRule.NO_LEGS, com.runehive.content.activity.impl.duelarena.DuelRule.NO_NECKLACE, com.runehive.content.activity.impl.duelarena.DuelRule.NO_RINGS, com.runehive.content.activity.impl.duelarena.DuelRule.NO_SHIELD, com.runehive.content.activity.impl.duelarena.DuelRule.NO_WEAPON, opponent, player, com.runehive.content.activity.Activity.removeAll(), com.runehive.game.world.items.containers.equipment.Equipment.RING_SLOT, rules, session, com.runehive.game.world.items.containers.equipment.Equipment.SHIELD_SLOT, and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by start().
update()
void com.runehive.content.activity.impl.duelarena.DuelArenaActivity.update ()
The update method.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 603 of file DuelArenaActivity.java.
{
        if (!started || getTicks() == FINISH || isPaused()) {
            return;
        }
        playerPanel.update();
        opponentPanel.update();
        ActivityPanel.update(playerPanel);
        ActivityPanel.update(opponentPanel);
    }
References com.runehive.content.activity.Activity.FINISH, com.runehive.content.activity.Activity.getTicks(), com.runehive.content.activity.Activity.isPaused(), opponentPanel, playerPanel, started, and com.runehive.content.activity.panel.ActivityPanel.update().
Member Data Documentation
ARENAS
final Position [] com.runehive.content.activity.impl.duelarena.DuelArenaActivity.ARENAS static private
Initial value:
= {
            new Position(3345, 3251),
            new Position(3378, 3251),
            new Position(3345, 3213),
            new Position(3379, 3213)
    }
The mid-points of all three duel arenas.
Definition at line 46 of file DuelArenaActivity.java.
{
            new Position(3345, 3251),
            new Position(3378, 3251),
            new Position(3345, 3213),
            new Position(3379, 3213)
    };
Referenced by start().
hasLoser
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.hasLoser
Definition at line 93 of file DuelArenaActivity.java.
Referenced by onDeath().
HOSPITAL_BEDS_SOUTHWEST
final Position com.runehive.content.activity.impl.duelarena.DuelArenaActivity.HOSPITAL_BEDS_SOUTHWEST = new Position(3361, 3272) static private
The south-west tile of the hospital bed area.
Definition at line 61 of file DuelArenaActivity.java.
Referenced by finish().
listener
final DuelArenaListener com.runehive.content.activity.impl.duelarena.DuelArenaActivity.listener = new DuelArenaListener(this) private
The combat listener for the duel.
Definition at line 82 of file DuelArenaActivity.java.
Referenced by getListener().
loser
Player com.runehive.content.activity.impl.duelarena.DuelArenaActivity.loser private
Definition at line 91 of file DuelArenaActivity.java.
Referenced by clickObject(), finish(), onDeath(), onLogout(), reward(), and reward().
OBSTACLE_ARENAS
final Position [] com.runehive.content.activity.impl.duelarena.DuelArenaActivity.OBSTACLE_ARENAS static private
Initial value:
= {
            new Position(3376, 3251),
            new Position(3345, 3231),
            new Position(3376, 3213)
    }
The mid-points of all three obstacle duel arenas.
Definition at line 54 of file DuelArenaActivity.java.
{
            new Position(3376, 3251),
            new Position(3345, 3231),
            new Position(3376, 3213)
    };
Referenced by start().
opponent
final Player com.runehive.content.activity.impl.duelarena.DuelArenaActivity.opponent package
The player accepting the duel.
Definition at line 73 of file DuelArenaActivity.java.
Referenced by canDrinkPotions(), canEat(), canEquipItem(), canLogout(), canUsePrayer(), canUseSpecial(), clickObject(), create(), DuelArenaActivity(), finish(), onDeath(), onLogout(), sequence(), start(), and unequipItems().
opponentPanel
DuelPanel com.runehive.content.activity.impl.duelarena.DuelArenaActivity.opponentPanel private
The opponent activity panel.
Definition at line 79 of file DuelArenaActivity.java.
Referenced by finish(), sequence(), and update().
player
final Player com.runehive.content.activity.impl.duelarena.DuelArenaActivity.player package
The player requesting the duel.
Definition at line 70 of file DuelArenaActivity.java.
Referenced by canDrinkPotions(), canEat(), canEquipItem(), canLogout(), canUsePrayer(), canUseSpecial(), clickObject(), create(), DuelArenaActivity(), finish(), onDeath(), onLogout(), reward(), sequence(), start(), and unequipItems().
playerPanel
DuelPanel com.runehive.content.activity.impl.duelarena.DuelArenaActivity.playerPanel private
The player activity panel.
Definition at line 76 of file DuelArenaActivity.java.
Referenced by finish(), sequence(), and update().
rewarded
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.rewarded private
Whether or not the reward has been given.
Definition at line 85 of file DuelArenaActivity.java.
Referenced by finish().
rules
final DuelRules com.runehive.content.activity.impl.duelarena.DuelArenaActivity.rules = new DuelRules()
The duel rules for this duel session.
Definition at line 64 of file DuelArenaActivity.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), canDrinkPotions(), canEat(), canEquipItem(), canUsePrayer(), canUseSpecial(), clickObject(), start(), and unequipItems().
session
final StakeSession com.runehive.content.activity.impl.duelarena.DuelArenaActivity.session private
The duel stake session (holds items).
Definition at line 67 of file DuelArenaActivity.java.
Referenced by canDrinkPotions(), canEat(), canEquipItem(), canLogout(), canUsePrayer(), canUseSpecial(), clickObject(), create(), DuelArenaActivity(), onDeath(), onLogout(), reward(), sequence(), and unequipItems().
started
boolean com.runehive.content.activity.impl.duelarena.DuelArenaActivity.started
Whether or not the duel has started.
Definition at line 88 of file DuelArenaActivity.java.
Referenced by clickObject(), sequence(), and update().
winner
Player com.runehive.content.activity.impl.duelarena.DuelArenaActivity.winner private
The duel outcome.
Definition at line 91 of file DuelArenaActivity.java.
Referenced by clickObject(), finish(), onDeath(), onLogout(), and reward().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/duelarena/DuelArenaActivity.java