RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra Class Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra Class Reference
Classes
class Magic
class Melee
class Ranged
Public Member Functions
boolean canAttack (Npc attacker, Mob defender)
boolean canOtherAttack (Mob attacker, Npc defender)
void finishOutgoing (Npc attacker, Mob defender)
int getAttackDelay (Npc attacker, Mob defender, FightType fightType)
KreeArra ()
boolean withinDistance (Npc attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy
void attack (Npc attacker, Mob defender, Hit hit)
void block (Mob attacker, Npc defender, Hit hit, CombatType combatType)
void finishIncoming (Mob attacker, Npc defender)
Animation getAttackAnimation (Npc attacker, Mob defender)
int getAttackDistance (Npc attacker, FightType fightType)
CombatType getCombatType ()
CombatHit[] getHits (Npc attacker, Mob defender)
void hit (Npc attacker, Mob defender, Hit hit)
void hitsplat (Npc attacker, Mob defender, Hit hit)
int modifyAccuracy (Npc attacker, Mob defender, int roll)
int modifyAggressive (Npc attacker, Mob defender, int roll)
int modifyAggressiveBonus (Npc attacker, Mob defender, int bonus)
int modifyAttackLevel (Npc attacker, Mob defender, int level)
int modifyDamage (Npc attacker, Mob defender, int damage)
int modifyDefenceLevel (Mob attacker, Npc defender, int level)
int modifyDefensive (Mob attacker, Npc defender, int roll)
int modifyDefensiveBonus (Mob attacker, Npc defender, int bonus)
int modifyMagicLevel (Npc attacker, Mob defender, int level)
int modifyOffensiveBonus (Npc attacker, Mob defender, int bonus)
int modifyRangedLevel (Npc attacker, Mob defender, int level)
int modifyStrengthLevel (Npc attacker, Mob defender, int level)
void onDamage (Npc defender, Hit hit)
void onDeath (Mob attacker, Npc defender, Hit hit)
void onKill (Npc attacker, Mob defender, Hit hit)
void preDeath (Mob attacker, Npc defender, Hit hit)
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (Npc attacker, Mob defender, Hit[] hits)
Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
abstract boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
abstract Animation getAttackAnimation (T attacker, Mob defender)
abstract int getAttackDelay (T attacker, Mob defender, FightType fightType)
abstract int getAttackDistance (T attacker, FightType fightType)
CombatProjectile getCombatProjectile ()
abstract CombatHit[] getHits (T attacker, Mob defender)
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
boolean isAlwaysAccurate ()
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Public Member Functions inherited from com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >
default void init (T attacker, Mob defender)
Called when the strategy initializes.
default void performChecks (T attacker, Mob defender)
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Private Attributes
boolean melee
Static Private Attributes
static final Magic MAGIC = new Magic()
static final Melee MELEE = new Melee()
static final CombatStrategy< Npc >[] NON_MELEE = createStrategyArray(MAGIC, RANGED)
static final Ranged RANGED = new Ranged()
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic)
static Graphic getEndGraphic (final CombatProjectile combatProjectile, final boolean splash, final Graphic splashGraphic, final int duration)
static Graphic getEndGraphic (final Optional< Graphic > end, final boolean splash, final Graphic splashGraphic, final int duration)
static int getProjectileDuration (final CombatProjectile combatProjectile)
static boolean missed (final Hit... hits)
Protected Member Functions inherited from com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >
final CombatHit nextMagicHit (T attacker, Mob defender)
CombatHit nextMagicHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max)
CombatHit nextMagicHit (T attacker, Mob defender, int max, CombatProjectile projectile)
final CombatHit nextMagicHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender)
CombatHit nextMeleeHit (T attacker, Mob defender, int max)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, boolean multipleHitsAllowed)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
CombatHit nextMeleeHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay, boolean multipleHitsAllowed)
final CombatHit nextRangedHit (T attacker, Mob defender)
final CombatHit nextRangedHit (T attacker, Mob defender, CombatProjectile projectile)
final CombatHit nextRangedHit (T attacker, Mob defender, int max)
final CombatHit nextRangedHit (T attacker, Mob defender, int max, CombatProjectile projectile)
CombatHit nextRangedHit (T attacker, Mob defender, int max, int hitDelay, int hitsplatDelay)
Protected Attributes inherited from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy
CombatStrategy< Npc > currentStrategy
Detailed Description
Definition at line 22 of file KreeArra.java.
Constructor & Destructor Documentation
KreeArra()
com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.KreeArra ()
Definition at line 31 of file KreeArra.java.
                      {
        currentStrategy = MELEE;
    }
References com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.currentStrategy, and MELEE.
Member Function Documentation
canAttack()
boolean com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canAttack (Npc attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 45 of file KreeArra.java.
{
        boolean isTarget = attacker.equals(defender.getCombat().getDefender());
        if (!melee && !isTarget) {
            currentStrategy = MELEE;
            melee = true;
        } else if (isTarget) melee = false;
        return super.canAttack(attacker, defender);
    }
References com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.currentStrategy, com.runehive.game.world.entity.mob.npc.Npc.equals(), com.runehive.game.world.entity.mob.Mob.getCombat(), MELEE, and melee.
canOtherAttack()
boolean com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canOtherAttack (Mob attacker, Npc defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 36 of file KreeArra.java.
{
        if (attacker.isPlayer() && attacker.getStrategy().getCombatType().equals(CombatType.MELEE)) {
            attacker.getPlayer().message("You can't attack Armadyl with melee!");
            return false;
        }
        return super.canOtherAttack(attacker, defender);
    }
References com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.Mob.getStrategy(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.combat.CombatType.MELEE, and com.runehive.game.world.entity.mob.player.Player.message().
finishOutgoing()
void com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.finishOutgoing (Npc attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 65 of file KreeArra.java.
{
        super.finishOutgoing(attacker, defender);
        boolean isTarget = attacker.equals(defender.getCombat().getDefender());
        if (!melee && !isTarget) {
            currentStrategy = MELEE;
            melee = true;
        } else {
            currentStrategy = randomStrategy(NON_MELEE);
            if (isTarget) melee = false;
        }
    }
References com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.currentStrategy, com.runehive.game.world.entity.mob.npc.Npc.equals(), com.runehive.game.world.entity.mob.Mob.getCombat(), MELEE, melee, and NON_MELEE.
getAttackDelay()
int com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.getAttackDelay (Npc attacker, Mob defender, FightType fightType)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 78 of file KreeArra.java.
{
        return attacker.definition.getAttackDelay();
    }
References com.runehive.game.world.entity.mob.npc.Npc.definition, and com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getAttackDelay().
withinDistance()
boolean com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.withinDistance (Npc attacker, Mob defender)
Reimplemented from com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
Definition at line 55 of file KreeArra.java.
{
        boolean isTarget = attacker.equals(defender.getCombat().getDefender());
        if (!melee && !isTarget) {
            currentStrategy = MELEE;
            melee = true;
        } else if (isTarget) melee = false;
        return super.withinDistance(attacker, defender);
    }
References com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.currentStrategy, com.runehive.game.world.entity.mob.npc.Npc.equals(), com.runehive.game.world.entity.mob.Mob.getCombat(), MELEE, and melee.
Member Data Documentation
MAGIC
final Magic com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.MAGIC = new Magic() static private
Definition at line 24 of file KreeArra.java.
MELEE
final Melee com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.MELEE = new Melee() static private
Definition at line 25 of file KreeArra.java.
Referenced by canAttack(), finishOutgoing(), KreeArra(), and withinDistance().
melee
boolean com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.melee private
Definition at line 27 of file KreeArra.java.
Referenced by canAttack(), finishOutgoing(), and withinDistance().
NON_MELEE
final CombatStrategy<Npc> [] com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.NON_MELEE = createStrategyArray(MAGIC, RANGED) static private
Definition at line 29 of file KreeArra.java.
Referenced by finishOutgoing().
RANGED
final Ranged com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.RANGED = new Ranged() static private
Definition at line 23 of file KreeArra.java.
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/armadyl/KreeArra.java