RuneHive-Game: com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession Class Reference
com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession Class Reference
The exchange session where two players can agree to a stake.
Public Member Functions
void accept (Player player, String component)
The method invoked when a PLAYER accepts a certain exchange component.
boolean canAddItem (Player player, Item item, int slot)
Checks if the item can be added to the container.
boolean canRemoveItem (Player player, Item item, int slot)
Checks if the item can be removed from the container.
boolean onButtonClick (Player player, int button)
The method invoked when a button is clicked.
boolean onRequest ()
The method invoked when a player requests the other player.
void onReset ()
Any functionality that should be handled when the itemcontainer closes.
StakeSession (Player owner, Player other)
void updateMainComponents (String component)
Updates the main components of the itemcontainer.
void updateOfferComponents ()
Updates the itemcontainer when an item is offered or removed.
Public Member Functions inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
final boolean add (Player player, int slot, int amount)
Attempts to deposit an item to the container.
void depositeAll (Player player)
Deposites all items to the exchange session.
ExchangeSession (Player player, Player other, ExchangeSessionType type)
Constructs a new ExchangeSession.
void forEach (Consumer< Player > action)
Executes the specified action for every player in this session.
Object getAttachment ()
Retrieves the attachment object to this class.
Player getOther (Player p)
Gets the other player in the exchange session.
boolean hasAttachment ()
Determines if the trade stage has an attachment.
boolean inAnySession ()
Determines if the player is any session.
final boolean remove (Player player, int slot, int amount)
Attempts to withdraw an item from the container.
boolean request ()
Attempts to start an exchange session.
void setAttachment (Object attachment)
Assigns an attachment to this stage object.
Public Attributes
boolean accepted
Public Attributes inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
boolean canOffer = true
Determines if the player can offer or withdraw items.
boolean finalized
Determines if this exchange has been finalized.
final Map< Player, ItemContainer > item_containers = new HashMap<>()
The items which are in this exchange session.
final Player other
The other player in this session.
final Player player
The controller of this session.
final ExchangeSessionType type
The type of this exchange session.
Private Member Functions
void showDuelRulesOnSecondScreen (Player p)
Private Attributes
DuelArenaActivity activity
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
static Optional< ExchangeSession > getSession (Player player)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, ExchangeSessionType type)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, Player other)
Gets the session if applicable the player is in.
static Optional< ExchangeSession > getSession (Player player, Player other, ExchangeSessionType type)
Gets the session if applicable the player is in.
static boolean inSession (Player player, ExchangeSessionType type)
Determines if the player is a session which matches the type.
static boolean inSession (Player player, Player other, ExchangeSessionType type)
Determines if the player is a session with other which matches the type.
Static Public Attributes inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
static final Set< ExchangeSession > SESSIONS = new HashSet<>()
The collection of sessions.
Protected Member Functions inherited from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession
void finalize (ExchangeCompletionType type)
Finalizes the exchange session procedure for the specified player in a session.
void withdrawAll (Player player)
Withdraws all items from the exchange session.
Detailed Description
The exchange session where two players can agree to a stake.
The agreed items will be kept in this session until the duel is over.
Author
nshusa
Definition at line 28 of file StakeSession.java.
Constructor & Destructor Documentation
StakeSession()
com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.StakeSession (Player owner, Player other)
Definition at line 33 of file StakeSession.java.
{
        super(owner, other, ExchangeSessionType.DUEL);
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other.
Member Function Documentation
accept()
void com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept (Player player, String COMPONENT)
The method invoked when a PLAYER accepts a certain exchange component.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 79 of file StakeSession.java.
{
        Player other = getOther(player);
        switch (component) {
            case "FIRST_SCREEN":
                if (!player.inventory.hasCapacityFor(item_containers.get(other).toArray())) {
                    player.send(new SendMessage("You don't have enough free slots for this many items.", MessageColor.RED));
                    break;
                }
                if (!other.inventory.hasCapacityFor(item_containers.get(player).toArray())) {
                    String username = other.getName();
                    player.send(new SendMessage(username + " doesn't have enough free slots for this many items", MessageColor.RED));
                    break;
                }
                if (hasAttachment() && !getAttachment().equals(player)) {
                    setAttachment(null);
                    updateMainComponents("SECOND_SCREEN");
                    return;
                }
                setAttachment(player);
                player.send(new SendString("<col=ffffff>Waiting for other player...", 31009));
                other.send(new SendString("<col=ffffff>Other player has accepted", 31009));
                break;
            case "SECOND_SCREEN":
                if (hasAttachment() && !getAttachment().equals(player)) {
                    setAttachment(null);
                    accepted = true;
                    finalize(ExchangeCompletionType.HALT);
                    activity.setPause(false);
                    return;
                }
                setAttachment(player);
                player.send(new SendString("<col=ffffff>Waiting for other player...", 31526));
                other.send(new SendString("<col=ffffff>Other player has accepted", 31526));
                break;
        }
    }
References accepted, activity, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.finalize(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getAttachment(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.getOther(), com.runehive.game.world.entity.mob.player.exchange.ExchangeCompletionType.HALT, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.hasAttachment(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.item_containers, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.util.MessageColor.RED, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.setAttachment(), and updateMainComponents().
Referenced by onButtonClick().
canAddItem()
boolean com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.canAddItem (Player player, Item item, int slot)
Checks if the item can be added to the container.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 123 of file StakeSession.java.
{
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player.
canRemoveItem()
boolean com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.canRemoveItem (Player player, Item item, int slot)
Checks if the item can be removed from the container.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 128 of file StakeSession.java.
{
        return true;
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player.
onButtonClick()
boolean com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onButtonClick (Player player, int button)
The method invoked when a button is clicked.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 133 of file StakeSession.java.
{
        Optional<DuelRule> rule = DuelRule.forButton(button);
        rule.ifPresent(r -> r.set(player, true));
        switch (button) {
            case 31018:
            case 31008:
            case 31002:
            case 31523:
            case 31502:
                player.exchangeSession.reset(ExchangeSessionType.DUEL);
                return true;
            case 31061: // save
                if (!player.interfaceManager.isInterfaceOpen(InterfaceConstants.FIRST_DUEL_SCREEN)) {
                    return false;
                }
                if (activity != null) {
                    EnumSet<DuelRule> flags = activity.rules.getFlags();
                    player.attributes.put("duel_rules", flags);
                }
                return true;
            case 31065: // load
                if (!player.interfaceManager.isInterfaceOpen(InterfaceConstants.FIRST_DUEL_SCREEN)) {
                    return false;
                }
                if (player.attributes.has("duel_rules") && activity != null) {
                    EnumSet<DuelRule> flags = player.attributes.get("duel_rules");
                    activity.rules.reset();
                    flags.forEach(it -> it.set(player, true));
                    DuelRule.showRules(activity, this.player, other);
                }
                return true;
            case 31520:
                if (!player.interfaceManager.isInterfaceOpen(InterfaceConstants.SECOND_DUEL_SCREEN)) {
                    return false;
                }
                accept(player, "SECOND_SCREEN");
                return true;
            case 31015:
                if (!player.interfaceManager.isInterfaceOpen(InterfaceConstants.FIRST_DUEL_SCREEN)) {
                    return false;
                }
                accept(player, "FIRST_SCREEN");
                return true;
        }
        return false;
    }
References accept(), activity, com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL, com.runehive.game.world.InterfaceConstants.FIRST_DUEL_SCREEN, com.runehive.content.activity.impl.duelarena.DuelRule.forButton(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.game.world.InterfaceConstants.SECOND_DUEL_SCREEN, and com.runehive.content.activity.impl.duelarena.DuelRule.showRules().
onRequest()
boolean com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onRequest ()
The method invoked when a player requests the other player.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 38 of file StakeSession.java.
{
//        if (true) {
//            DuelArenaActivity2.create(this, player, other).cooldown(-1);
//            return true;
//        }
        if(player.playTime < 6000) {
            player.message("You must have at least 1 hour of play time before duelling.");
            return false;
        }
        if(other.playTime < 6000) {
            player.message("The other player must have at least 1 hour of play time before duelling.");
            return false;
        }
        // face player they are requesting to duel
        player.face(other.getPosition());
        player.exchangeSession.requested_players.add(other);
        if (!other.exchangeSession.requested_players.contains(player)) {
            player.send(new SendMessage("Sending duel request..."));
            other.send(new SendMessage(player.getName() + ":duelreq:", MessageColor.BRONZE));
            return false;
        }
        SESSIONS.add(this);
        activity = DuelArenaActivity.create(this, player, other);
        forEach(player -> {
            player.exchangeSession.resetRequests();
            player.send(new SendMinimapState(SendMinimapState.MinimapState.UNCLICKABLE));
            player.send(new SendConfig(655, 0)); // stake removal notification
            // reset duel rule configs
            IntStream.range(631, 644).forEach(i -> player.send(new SendConfig(i, 0)));
            player.send(new SendToggle(286, 0));
            player.attributes.set("DUEL_KEY", true);
        });
        updateMainComponents("FIRST_SCREEN");
        return true;
    }
References activity, com.runehive.util.MessageColor.BRONZE, com.runehive.content.activity.impl.duelarena.DuelArenaActivity.create(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.SESSIONS, com.runehive.net.packet.out.SendMinimapState.MinimapState.UNCLICKABLE, and updateMainComponents().
onReset()
void com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onReset ()
Any functionality that should be handled when the itemcontainer closes.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 238 of file StakeSession.java.
{
        forEach(player -> {
            player.send(new SendMinimapState(SendMinimapState.MinimapState.NORMAL));
            player.resetFace();
            player.attributes.set("DUEL_KEY", false);
            if (!accepted) {
                activity.remove(player);
            }
        });
    }
References accepted, activity, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), com.runehive.net.packet.out.SendMinimapState.MinimapState.NORMAL, and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player.
showDuelRulesOnSecondScreen()
void com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.showDuelRulesOnSecondScreen (Player p) private
Definition at line 249 of file StakeSession.java.
{
        Optional<DuelArenaActivity> result = Activity.search(p, DuelArenaActivity.class);
        if (!result.isPresent()) {
            return;
        }
        DuelArenaActivity activity = result.get();
        int count = 0;
        for (DuelRule rule : DuelRule.values()) {
            if (activity.rules.contains(rule)) {
                p.send(new SendString(DuelUtils.getRuleText(rule), 31509 + count));
                count++;
            }
        }
    }
References activity, com.runehive.content.activity.impl.duelarena.DuelUtils.getRuleText(), com.runehive.content.activity.Activity.search(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by updateMainComponents().
updateMainComponents()
void com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateMainComponents (String component)
Updates the main components of the itemcontainer.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 191 of file StakeSession.java.
{
        switch (component) {
            case "FIRST_SCREEN":
                updateOfferComponents();
                break;
            case "SECOND_SCREEN":
                forEach(p -> {
                    Player recipient = p.getName().equals(player.getName()) ? this.other : this.player;
                    p.send(new SendString("Some worn items will be taken off.", 31505));
                    p.send(new SendString("Boosted stats will be restored.", 31506));
                    p.send(new SendString("Existing prayers will be stopped.", 31507));
                    IntStream.range(31509, 31520).forEach(i -> p.send(new SendString("", i))); // rules
                    showDuelRulesOnSecondScreen(p);
                    IntStream.range(31531, 31560).forEach(i -> p.send(new SendString("", i)));
                    IntStream.range(31561, 31589).forEach(i -> p.send(new SendString("", i)));
                    p.send(new SendString(DuelUtils.getItemNames(this.item_containers.get(p).toArray()), 31531));
                    p.send(new SendString(DuelUtils.getItemNames(this.item_containers.get(recipient).toArray()), 31561));
                    p.send(new SendString("", 31526));
                    p.send(new SendItemOnInterface(3322, this.item_containers.get(p).toArray()));
                    p.interfaceManager.open(InterfaceConstants.SECOND_DUEL_SCREEN);
                });
                break;
        }
    }
References com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), com.runehive.content.activity.impl.duelarena.DuelUtils.getItemNames(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.item_containers, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.game.world.InterfaceConstants.SECOND_DUEL_SCREEN, showDuelRulesOnSecondScreen(), and updateOfferComponents().
Referenced by accept(), and onRequest().
updateOfferComponents()
void com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents ()
Updates the itemcontainer when an item is offered or removed.
Reimplemented from com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.
Definition at line 220 of file StakeSession.java.
{
        setAttachment(null);
        forEach(p -> {
            Player recipient = p.getName().equals(player.getName()) ? this.other : this.player;
            p.send(new SendItemOnInterface(3322, p.inventory.toArray()));
            item_containers.get(p).refresh(p, InterfaceConstants.PLAYER_STAKE_CONTAINER);
            item_containers.get(p).refresh(recipient, InterfaceConstants.OTHER_STAKE_CONTAINER);
            p.send(new SendString("Dueling with: " + PlayerRight.getCrown(recipient) + " " + Utility.formatName(recipient.getUsername()), 31005));
            p.send(new SendString("Opponent's combat level: <col=ff7000>" + other.skills.getCombatLevel(), 31006));
            p.send(new SendString("", 31009));
            p.interfaceManager.openInventory(InterfaceConstants.FIRST_DUEL_SCREEN, 3321);
        });
    }
References com.runehive.game.world.InterfaceConstants.FIRST_DUEL_SCREEN, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.forEach(), com.runehive.util.Utility.formatName(), com.runehive.game.world.entity.mob.player.PlayerRight.getCrown(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.item_containers, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.other, com.runehive.game.world.InterfaceConstants.OTHER_STAKE_CONTAINER, com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.player, com.runehive.game.world.InterfaceConstants.PLAYER_STAKE_CONTAINER, and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.setAttachment().
Referenced by updateMainComponents().
Member Data Documentation
accepted
boolean com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accepted
Definition at line 31 of file StakeSession.java.
Referenced by accept(), and onReset().
activity
DuelArenaActivity com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.activity private
Definition at line 30 of file StakeSession.java.
Referenced by accept(), onButtonClick(), onRequest(), onReset(), and showDuelRulesOnSecondScreen().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/player/exchange/duel/StakeSession.java