RuneHive-Game: com.runehive.content.activity.impl.barrows.Barrows Class Reference
com.runehive.content.activity.impl.barrows.Barrows Class Reference
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
ActivityDeathType deathType ()
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
void update ()
The update method.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
Static Public Member Functions
static Barrows create (Player player)
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Member Functions
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
Barrows (Player player)
void move (Position position)
void reset ()
void summon (BrotherData brother)
Private Attributes
Npc brotherNpc
Player player
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Definition at line 22 of file Barrows.java.
Constructor & Destructor Documentation
Barrows()
com.runehive.content.activity.impl.barrows.Barrows.Barrows (Player player) private
Definition at line 28 of file Barrows.java.
{
        super(10, Mob.DEFAULT_INSTANCE);
        this.player = player;
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE, and player.
Referenced by create().
Member Function Documentation
canTeleport()
boolean com.runehive.content.activity.impl.barrows.Barrows.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 148 of file Barrows.java.
{
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.barrows.Barrows.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 108 of file Barrows.java.
{
        if (brotherNpc != null) {
            remove(brotherNpc);
        }
    }
References brotherNpc.
Referenced by finish().
clickNpc()
boolean com.runehive.content.activity.impl.barrows.Barrows.clickNpc (Player player, NpcInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 153 of file Barrows.java.
{
        if (event.getOpcode() == 0 && event.getNpc().id == 1671) {
            DialogueFactory factory = player.dialogueFactory;
            factory.sendNpcChat(1671, "Hello #name,", "would you like me to reset your barrows?");
            factory.sendOption("Yes please", () -> {
                    reset();
                    factory.sendNpcChat(1671, "I have reset your barrows!");
            }, "No thanks", factory::execute);
            factory.execute();
            return true;
        }
        return false;
    }
References com.runehive.content.dialogue.DialogueFactory.execute(), player, reset(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), and com.runehive.content.dialogue.DialogueFactory.sendOption().
clickObject()
boolean com.runehive.content.activity.impl.barrows.Barrows.clickObject (Player player, ObjectInteractionEvent event) protected
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 169 of file Barrows.java.
{
        int id = event.getObject().getId();
        switch (id) {
            case 20973:
                if (player.barrowsKillCount == 6) {
                    if (player.inventory.getFreeSlots() < 5) {
                        player.dialogueFactory.sendPlayerChat("I should free up some inventory slots first.").execute();
                        return true;
                    }
                    reset();
                    BarrowsUtility.generateRewards(player);
                    player.send(new SendMessage("You have completed the barrows minigame, well done!"));
                    finish();
                } else if (player.barrowsKillCount == 5) {
                    if (brotherNpc == null) {
                        brotherNpc = new Npc(player.hiddenBrother.getNpcId(), player.getPosition());
                        add(brotherNpc);
                        brotherNpc.speak("How dare you disturb my slumber!");
                        brotherNpc.getCombat().attack(player);
                        brotherNpc.owner = player;
                        player.send(new SendEntityHintArrow(brotherNpc));
                    }
                    return true;
                }
                break;
            case 20667:
                move(BrotherData.AHRIM.getHillPosition());
                return true;
            case 20770:
                summon(BrotherData.AHRIM);
                return true;
            case 20672:
                move(BrotherData.VERAC.getHillPosition());
                return true;
            case 20772:
                summon(BrotherData.VERAC);
                return true;
            case 20668:
                move(BrotherData.DHAROK.getHillPosition());
                return true;
            case 20720:
                summon(BrotherData.DHAROK);
                return true;
            case 20671:
                move(BrotherData.TORAG.getHillPosition());
                return true;
            case 20721:
                summon(BrotherData.TORAG);
                return true;
            case 20669:
                move(BrotherData.GUTHAN.getHillPosition());
                return true;
            case 20722:
                summon(BrotherData.GUTHAN);
                return true;
            case 20670:
                move(BrotherData.KARIL.getHillPosition());
                return true;
            case 20771:
                summon(BrotherData.KARIL);
                return true;
        }
        return false;
    }
References com.runehive.content.activity.Activity.add(), com.runehive.content.activity.impl.barrows.BrotherData.AHRIM, brotherNpc, com.runehive.content.activity.impl.barrows.BrotherData.DHAROK, finish(), com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), com.runehive.content.activity.impl.barrows.BrotherData.GUTHAN, com.runehive.content.activity.impl.barrows.BrotherData.KARIL, move(), player, reset(), summon(), com.runehive.content.activity.impl.barrows.BrotherData.TORAG, and com.runehive.content.activity.impl.barrows.BrotherData.VERAC.
create()
Barrows com.runehive.content.activity.impl.barrows.Barrows.create (Player player) static
Definition at line 33 of file Barrows.java.
{
        Barrows minigame = new Barrows(player);
        minigame.add(player);
        return minigame;
    }
References com.runehive.content.activity.Activity.add(), Barrows(), and player.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity(), and com.runehive.content.teleport.TeleportHandler.special().
deathType()
ActivityDeathType com.runehive.content.activity.impl.barrows.Barrows.deathType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 235 of file Barrows.java.
{
        return ActivityDeathType.NORMAL;
    }
References com.runehive.content.activity.ActivityDeathType.NORMAL.
finish()
void com.runehive.content.activity.impl.barrows.Barrows.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 101 of file Barrows.java.
{
        cleanup();
        remove(player);
        ActivityPanel.clear(player);
    }
References cleanup(), com.runehive.content.activity.panel.ActivityPanel.clear(), and player.
Referenced by clickObject(), onDeath(), onLogout(), and onRegionChange().
getType()
ActivityType com.runehive.content.activity.impl.barrows.Barrows.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 240 of file Barrows.java.
{
        return ActivityType.BARROWS;
    }
References com.runehive.content.activity.ActivityType.BARROWS.
move()
void com.runehive.content.activity.impl.barrows.Barrows.move (Position position) private
Definition at line 67 of file Barrows.java.
{
        if (brotherNpc != null && !brotherNpc.isDead()) {
            remove(brotherNpc);
            brotherNpc = null;
        }
        player.move(position);
    }
References brotherNpc, and player.
Referenced by clickObject().
onDeath()
void com.runehive.content.activity.impl.barrows.Barrows.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 76 of file Barrows.java.
{
        if (mob.isPlayer() && mob.equals(player)) {
            finish();
            return;
        }
        if (mob.isNpc()) {
            BrotherData bro = BrotherData.getBarrowsBrother(mob.getNpc());
            if (bro != null) {
                brotherNpc = null;
                player.barrowsKillCount += 1;
                player.barrowKills[bro.ordinal()] = true;
                if (player.barrowsKillCount == 1) {
                    player.hiddenBrother = BarrowsUtility.getHiddenBrother(player);
                }
                World.schedule(new NpcDeath(mob.getNpc()));
            }
        }
    }
References brotherNpc, com.runehive.game.world.entity.Entity.equals(), finish(), com.runehive.content.activity.impl.barrows.BrotherData.getBarrowsBrother(), com.runehive.content.activity.impl.barrows.BarrowsUtility.getHiddenBrother(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), player, and com.runehive.game.world.World.schedule().
onLogout()
void com.runehive.content.activity.impl.barrows.Barrows.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 115 of file Barrows.java.
{
        finish();
    }
References finish(), and player.
onRegionChange()
void com.runehive.content.activity.impl.barrows.Barrows.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 120 of file Barrows.java.
{
        if (!Area.inBarrows(player)) {
            finish();
        }
    }
References finish(), com.runehive.game.world.position.Area.inBarrows(), and player.
reset()
void com.runehive.content.activity.impl.barrows.Barrows.reset () private
Definition at line 126 of file Barrows.java.
{
        player.barrowsKillCount = 0;
        player.barrowKills = new boolean[BrotherData.values().length];
        player.hiddenBrother = null;
        update();
    }
References update().
Referenced by clickNpc(), and clickObject().
start()
void com.runehive.content.activity.impl.barrows.Barrows.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 96 of file Barrows.java.
{
    }
summon()
void com.runehive.content.activity.impl.barrows.Barrows.summon (BrotherData brother) private
Definition at line 39 of file Barrows.java.
{
        if (player.barrowKills[brother.ordinal()]) {
            player.dialogueFactory.sendPlayerChat("I have already killed this brother.").execute();
            return;
        }
        if (brotherNpc != null) {
            player.dialogueFactory.sendPlayerChat("Maybe I should finish killing the other one first.").execute();
            return;
        }
        if (player.hiddenBrother == brother && player.barrowsKillCount != 5) {
            player.dialogueFactory.sendPlayerChat("I should return when I've killed the others.").execute();
            return;
        } else if (player.hiddenBrother == brother && player.barrowsKillCount == 5) {
            player.dialogueFactory.sendOption("Enter the tunnel.", () -> {
                player.move(new Position(3551, 9691, 0));
            }, "No, I'm not ready yet.", () -> {
                player.dialogueFactory.clear();
            }).execute();
            return;
        }
        brotherNpc = new Npc(brother.getNpcId(), player.getPosition());
        add(brotherNpc);
        brotherNpc.speak("How dare you disturb my rest!");
        brotherNpc.getCombat().attack(player);
        brotherNpc.owner = player;
        player.send(new SendEntityHintArrow(brotherNpc));
    }
References com.runehive.content.activity.Activity.add(), brotherNpc, com.runehive.content.activity.impl.barrows.BrotherData.getNpcId(), and player.
Referenced by clickObject().
update()
void com.runehive.content.activity.impl.barrows.Barrows.update ()
The update method.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 134 of file Barrows.java.
{
        int killed = player.barrowsKillCount;
        int total = BrotherData.values().length;
        int percentage = (int) Utility.getPercentageAmount(killed, total);
        String ahrim = player.barrowKills[BrotherData.AHRIM.ordinal()] ? "@red@Ahrim the Blighted" : "@gre@Ahrim the Blighted";
        String dharok = player.barrowKills[BrotherData.DHAROK.ordinal()] ? "@red@Dharok the Wretched" : "@gre@Dharok the Wretched";
        String guthan = player.barrowKills[BrotherData.GUTHAN.ordinal()] ? "@red@Guthan the Infested" : "@gre@Guthan the Infested";
        String karil = player.barrowKills[BrotherData.KARIL.ordinal()] ? "@red@Karil the Tainted" : "@gre@Karil the Tainted";
        String torag = player.barrowKills[BrotherData.TORAG.ordinal()] ? "@red@Torag the Corrupted" : "@gre@Torag the Corrupted";
        String verac = player.barrowKills[BrotherData.VERAC.ordinal()] ? "@red@Verac the Defiled" : "@gre@Verac the Defiled";
        ActivityPanel.update(player, percentage, "Barrows", new Item(19629, 0), "Killed: <col=FF5500>" + killed + "</col> - Remaining: <col=FF5500>" + (total - killed) + "</col>", ahrim, dharok, guthan, karil, torag, verac);
    }
References com.runehive.content.activity.impl.barrows.BrotherData.AHRIM, com.runehive.content.activity.impl.barrows.BrotherData.DHAROK, com.runehive.util.Utility.getPercentageAmount(), com.runehive.content.activity.impl.barrows.BrotherData.GUTHAN, com.runehive.content.activity.impl.barrows.BrotherData.KARIL, player, com.runehive.content.activity.impl.barrows.BrotherData.TORAG, com.runehive.content.activity.panel.ActivityPanel.update(), and com.runehive.content.activity.impl.barrows.BrotherData.VERAC.
Referenced by reset().
Member Data Documentation
brotherNpc
Npc com.runehive.content.activity.impl.barrows.Barrows.brotherNpc private
Definition at line 26 of file Barrows.java.
Referenced by cleanup(), clickObject(), move(), onDeath(), and summon().
player
Player com.runehive.content.activity.impl.barrows.Barrows.player private
Definition at line 24 of file Barrows.java.
Referenced by Barrows(), canTeleport(), clickNpc(), clickObject(), create(), finish(), move(), onDeath(), onLogout(), onRegionChange(), summon(), and update().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/barrows/Barrows.java