RuneHive-Game: com.runehive.content.skill.impl.construction.BuildableInterface Class Reference
com.runehive.content.skill.impl.construction.BuildableInterface Class Reference
Static Public Member Functions
static void click (Player player, int button)
static void display (Player player, BuildableObject object)
static void open (Player player, BuildableType type)
static void refresh (Player player, int selected, BuildableType type)
Detailed Description
Definition at line 11 of file BuildableInterface.java.
Member Function Documentation
click()
void com.runehive.content.skill.impl.construction.BuildableInterface.click (Player player, int button) static
Definition at line 20 of file BuildableInterface.java.
{
        int index = Math.abs((-17995 - button));
        BuildableType type = player.attributes.get("CONSTRUCTION_BUILDTYPE_KEY", BuildableType.class);
        List<BuildableObject> list = BuildableObject.get(type);
        if (index >= list.size()) {
            return;
        }
        display(player, list.get(index));
        refresh(player, index, type);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, display(), com.runehive.content.skill.impl.construction.BuildableObject.get(), com.runehive.util.generic.GenericAttributes.get(), and refresh().
Referenced by open().
display()
void com.runehive.content.skill.impl.construction.BuildableInterface.display (Player player, BuildableObject object) static
Definition at line 33 of file BuildableInterface.java.
{
        player.send(new SendString(object == null ? "" : "" + object.getName(), 47515));
        player.send(new SendString(object == null ? "" : "</col>Size: <col=5cf442>" + GameObjectDefinition.forId(object.getObject()).getWidth(), 47518));
        player.send(new SendString(object == null ? "" : "</col>Level: <col=5cf442>" + Utility.formatDigits(object.getLevel()), 47519));
        player.send(new SendString(object == null ? "" : "</col>Experience: <col=5cf442>" + Utility.formatDigits(object.getExperience()), 47520));
        player.send(new SendItemOnInterface(47517, object == null ? null : object.getItems()));
        player.attributes.set("CONSTRUCTION_BUILDOBJECT_KEY", object);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.object.GameObjectDefinition.forId(), com.runehive.util.Utility.formatDigits(), com.runehive.game.world.object.GameObjectDefinition.getWidth(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.util.generic.GenericAttributes.set().
Referenced by click().
open()
void com.runehive.content.skill.impl.construction.BuildableInterface.open (Player player, BuildableType type) static
Definition at line 13 of file BuildableInterface.java.
{
        player.attributes.set("CONSTRUCTION_BUILDTYPE_KEY", type);
        refresh(player, 0, type);
        click(player, -17995);
        player.interfaceManager.open(47500);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, click(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), refresh(), and com.runehive.util.generic.GenericAttributes.set().
refresh()
void com.runehive.content.skill.impl.construction.BuildableInterface.refresh (Player player, int selected, BuildableType type) static
Definition at line 42 of file BuildableInterface.java.
{
        List<BuildableObject> list = BuildableObject.get(type);
        for (int index = 0; index < 50; index++) {
            String name = index >= list.size() ? "" : ((selected == index ? "<col=5cf442>" : "</col>") + list.get(index).getName());
            player.send(new SendString(name, 47541 + index));
        }
        player.send(new SendString("Total object: " + list.size(), 47514));
    }
References com.runehive.content.skill.impl.construction.BuildableObject.get(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by click(), and open().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/construction/BuildableInterface.java