RuneHive-Game: com.runehive.content.activity.impl.CerberusActivity Class Reference
com.runehive.content.activity.impl.CerberusActivity Class Reference
Created by Daniel on 2018-01-20.
Public Member Functions
boolean canTeleport (Player player)
Called when the player attempts to teleport.
void cleanup ()
Cleans up the activity when finished.
void finish ()
Finishes the activity.
ActivityType getType ()
void onDeath (Mob mob)
Called when the player die.
void onLogout (Player player)
Called when the player logs out.
void onRegionChange (Player player)
Called when the player changes region.
Public Member Functions inherited from com.runehive.content.activity.Activity
Activity (int cooldown, int instance)
Constructs a new SequencedMinigame object.
void add (Mob mob)
Adds a mob to the activity.
boolean canDrinkPotions (Player player)
boolean canEat (Player player, FoodData foodType)
boolean canEquipItem (Player player, Item item, EquipmentType type)
boolean canLogout (Player player)
boolean canSpellCast (Player player)
boolean canUsePrayer (Player player)
boolean canUseSpecial (Player player)
void cooldown (int cooldown)
Applies a cooldown.
ActivityDeathType deathType ()
int getInstance ()
Gets this activity's instance level.
Optional< Activity_Panel > getPanel ()
Gets an optional of the activity panel.
int getTicks ()
Gets the current ticks.
boolean onEvent (Player player, InteractionEvent interactionEvent)
boolean onStep (Mob mob)
void remove (Mob mob)
Removes a mob from the activity.
void removeAll (Mob... mobs)
Removes all mobs from the activity.
void sequence ()
Sequences the activity.
void setInstance (int instance)
void setPanel (Activity_Panel panel)
Sets the activity panel.
void setPause (boolean pause)
Sets the pause state of the activity.
void update ()
The update method.
Static Public Member Functions
static CerberusActivity create (Player player)
Static Public Member Functions inherited from com.runehive.content.activity.Activity
static boolean evaluate (Mob mob, Predicate< Activity > predicate)
static void forActivity (Mob mob, Consumer< Activity > consumer)
static< T extends Activity > Optional< T > search (Player player, Class< T > clazz)
Protected Member Functions
void start ()
Starts the next activity stage.
Protected Member Functions inherited from com.runehive.content.activity.Activity
boolean clickButton (Player player, ClickButtonInteractionEvent event)
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
final void finishCooldown ()
Sets the cooldown flag to FINISH.
Optional<? extends ActivityListener<? extends Activity > > getListener ()
Gets an Optional of the ActivityListener for this activity.
final boolean isPaused ()
Checks if the cooldown is paused.
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
final void pause ()
Sets the cooldown flag to PAUSE.
boolean pickupItem (Player player, PickupItemInteractionEvent event)
final void resetCooldown ()
Resets the remaining ticks to the cached cooldown ticks.
void restart (int delay, Runnable runnable)
boolean useItem (Player player, ItemOnItemInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
CerberusActivity (Player player, int instance)
Private Attributes
Npc cerberus = new Npc(5862, new Position(1240, 1252))
List< GameObject > objectList = new ArrayList<>(4)
final Player player
Static Private Attributes
static final GameObject[] OBJECTS = {new CustomGameObject(23105, new Position(1241, 1242)), new CustomGameObject(23105, new Position(1240, 1242)), new CustomGameObject(23105, new Position(1239, 1242)), new CustomGameObject(23105, new Position(1240, 1236))}
Additional Inherited Members
Static Protected Attributes inherited from com.runehive.content.activity.Activity
static final int FINISH = -1
The 'finish' cooldown id.
static final int PAUSE = -2
The 'pause' cooldown id.
static final int START = 0
The 'start' cooldown id.
Detailed Description
Created by Daniel on 2018-01-20.
Definition at line 23 of file CerberusActivity.java.
Constructor & Destructor Documentation
CerberusActivity()
com.runehive.content.activity.impl.CerberusActivity.CerberusActivity (Player player, int instance) private
Definition at line 29 of file CerberusActivity.java.
{
        super(1, instance);
        this.player = player;
    }
References com.runehive.content.activity.Activity.instance, and player.
Referenced by create().
Member Function Documentation
canTeleport()
boolean com.runehive.content.activity.impl.CerberusActivity.canTeleport (Player player)
Called when the player attempts to teleport.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 108 of file CerberusActivity.java.
{
        return true;
    }
References player.
cleanup()
void com.runehive.content.activity.impl.CerberusActivity.cleanup ()
Cleans up the activity when finished.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 59 of file CerberusActivity.java.
{
        for (GameObject object : objectList) {
            System.out.println("unregistering " + object.getId());
            object.unregister();
        }
        objectList.clear();
        remove(cerberus);
    }
References cerberus, and objectList.
Referenced by finish(), onDeath(), onLogout(), and onRegionChange().
create()
CerberusActivity com.runehive.content.activity.impl.CerberusActivity.create (Player player) static
Definition at line 34 of file CerberusActivity.java.
{
        CerberusActivity activity = new CerberusActivity(player, player.playerAssistant.instance());
        activity.add(player);
        activity.resetCooldown();
        return activity;
    }
References CerberusActivity(), and player.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity().
finish()
void com.runehive.content.activity.impl.CerberusActivity.finish ()
Finishes the activity.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 53 of file CerberusActivity.java.
{
        cleanup();
        remove(player);
    }
References cleanup(), and player.
getType()
ActivityType com.runehive.content.activity.impl.CerberusActivity.getType ()
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 113 of file CerberusActivity.java.
{
        return ActivityType.CERBERUS;
    }
References com.runehive.content.activity.ActivityType.CERBERUS.
onDeath()
void com.runehive.content.activity.impl.CerberusActivity.onDeath (Mob mob)
Called when the player die.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 70 of file CerberusActivity.java.
{
        if (mob.isPlayer()) {
            cleanup();
            player.move(new Position(3087, 3497));
            player.animate(Animation.RESET, true);
            player.graphic(Graphic.RESET, true);
            return;
        }
        World.schedule(new NpcDeath(mob.getNpc(), () -> {
            finish();
            restart(10, () -> {
                if (Area.inCerberus(player)) {
                    create(player);
                } else {
                    remove(player);
                }
            });
        }));
    }
References cleanup(), com.runehive.game.world.entity.mob.Mob.getNpc(), com.runehive.game.world.entity.mob.Mob.isPlayer(), player, com.runehive.game.Animation.RESET, com.runehive.game.Graphic.RESET, and com.runehive.game.world.World.schedule().
onLogout()
void com.runehive.content.activity.impl.CerberusActivity.onLogout (Player player)
Called when the player logs out.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 102 of file CerberusActivity.java.
{
        cleanup();
        remove(player);
    }
References cleanup(), and player.
onRegionChange()
void com.runehive.content.activity.impl.CerberusActivity.onRegionChange (Player player)
Called when the player changes region.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 94 of file CerberusActivity.java.
{
        if (!Area.inCerberus(player)) {
            cleanup();
            remove(player);
        }
    }
References cleanup(), com.runehive.game.world.position.Area.inCerberus(), and player.
start()
void com.runehive.content.activity.impl.CerberusActivity.start () protected
Starts the next activity stage.
Reimplemented from com.runehive.content.activity.Activity.
Definition at line 42 of file CerberusActivity.java.
{
        for (GameObject object : OBJECTS) {
            object.register();
            objectList.add(object);
        }
        add(cerberus);
        pause();
    }
References com.runehive.content.activity.Activity.add(), cerberus, objectList, OBJECTS, and com.runehive.content.activity.Activity.pause().
Member Data Documentation
cerberus
Npc com.runehive.content.activity.impl.CerberusActivity.cerberus = new Npc(5862, new Position(1240, 1252)) private
Definition at line 26 of file CerberusActivity.java.
Referenced by cleanup(), and start().
objectList
List<GameObject> com.runehive.content.activity.impl.CerberusActivity.objectList = new ArrayList<>(4) private
Definition at line 27 of file CerberusActivity.java.
Referenced by cleanup(), and start().
OBJECTS
final GameObject [] com.runehive.content.activity.impl.CerberusActivity.OBJECTS = {new CustomGameObject(23105, new Position(1241, 1242)), new CustomGameObject(23105, new Position(1240, 1242)), new CustomGameObject(23105, new Position(1239, 1242)), new CustomGameObject(23105, new Position(1240, 1236))} static private
Definition at line 24 of file CerberusActivity.java.
{new CustomGameObject(23105, new Position(1241, 1242)), new CustomGameObject(23105, new Position(1240, 1242)), new CustomGameObject(23105, new Position(1239, 1242)), new CustomGameObject(23105, new Position(1240, 1236))};
Referenced by start().
player
final Player com.runehive.content.activity.impl.CerberusActivity.player private
Definition at line 25 of file CerberusActivity.java.
Referenced by canTeleport(), CerberusActivity(), create(), finish(), onDeath(), onLogout(), and onRegionChange().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/CerberusActivity.java