RuneHive-Game: com.runehive.net.packet.PacketBuilder Class Reference
com.runehive.net.packet.PacketBuilder Class Reference
The implementation that functions as a dynamic buffer wrapper backed by a ByteBuf that is used for reading and writing data.
Public Member Functions
String getString ()
PacketBuilder initializeAccess (AccessType type)
GamePacket toPacket (int opcode)
GamePacket toPacket (int opcode, PacketType type)
PacketBuilder writeBit (boolean flag)
PacketBuilder writeBits (int amount, int value)
PacketBuilder writeBuffer (ByteBuf buffer)
PacketBuilder writeByte (int value)
PacketBuilder writeByte (int value, ByteModification type)
PacketBuilder writeByteArray (byte[] bytes)
PacketBuilder writeByteArray (byte[] bytes, int offset, int length)
PacketBuilder writeBytes (byte[] from, int size)
PacketBuilder writeBytes (ByteBuf from)
PacketBuilder writeBytesReverse (byte[] data)
PacketBuilder writeInt (int value)
PacketBuilder writeInt (int value, ByteModification type)
PacketBuilder writeInt (int value, ByteModification type, ByteOrder order)
PacketBuilder writeInt (int value, ByteOrder order)
PacketBuilder writeLong (long value)
PacketBuilder writeLong (long value, ByteModification type)
PacketBuilder writeLong (long value, ByteModification type, ByteOrder order)
PacketBuilder writeLong (long value, ByteOrder order)
PacketBuilder writeShort (int value)
PacketBuilder writeShort (int value, ByteModification type)
PacketBuilder writeShort (int value, ByteModification type, ByteOrder order)
PacketBuilder writeShort (int value, ByteOrder order)
PacketBuilder writeString (String string)
Static Public Member Functions
static PacketBuilder alloc ()
static PacketBuilder alloc (int capacity)
static PacketBuilder alloc (int initialCapacity, int maxCapacity)
static PacketBuilder wrap (ByteBuf buf)
Static Package Functions
[static initializer]
Private Member Functions
PacketBuilder (ByteBuf buffer)
Private Attributes
int bitPosition
Static Private Attributes
static final int[] BIT_MASK = new int[32]
static final int DEFAULT_CAPACITY = 128
Detailed Description
The implementation that functions as a dynamic buffer wrapper backed by a ByteBuf that is used for reading and writing data.
Author
lare96 http://github.com/lare96
blakeman8192
Definition at line 19 of file PacketBuilder.java.
Constructor & Destructor Documentation
PacketBuilder()
com.runehive.net.packet.PacketBuilder.PacketBuilder (ByteBuf buffer) private
Definition at line 32 of file PacketBuilder.java.
{
        super(buffer);
    }
Referenced by alloc(), alloc(), alloc(), initializeAccess(), wrap(), writeBit(), writeBits(), writeBuffer(), writeByte(), writeByte(), writeByteArray(), writeByteArray(), writeBytes(), writeBytes(), writeBytesReverse(), writeInt(), writeInt(), writeInt(), writeInt(), writeLong(), writeLong(), writeLong(), writeLong(), writeShort(), writeShort(), writeShort(), writeShort(), and writeString().
Member Function Documentation
[static initializer]()
com.runehive.net.packet.PacketBuilder.[static initializer] static package
References BIT_MASK.
alloc() [1/3]
PacketBuilder com.runehive.net.packet.PacketBuilder.alloc () static
Definition at line 44 of file PacketBuilder.java.
{
        return alloc(DEFAULT_CAPACITY);
    }
References alloc(), DEFAULT_CAPACITY, and PacketBuilder().
Referenced by alloc().
alloc() [2/3]
PacketBuilder com.runehive.net.packet.PacketBuilder.alloc (int capacity) static
Definition at line 40 of file PacketBuilder.java.
{
        return new PacketBuilder(PooledByteBufAllocator.DEFAULT.buffer(capacity));
    }
References PacketBuilder().
alloc() [3/3]
PacketBuilder com.runehive.net.packet.PacketBuilder.alloc (int initialCapacity, int maxCapacity) static
Definition at line 36 of file PacketBuilder.java.
{
        return new PacketBuilder(PooledByteBufAllocator.DEFAULT.buffer(initialCapacity, maxCapacity));
    }
References PacketBuilder().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.out.SendNpcUpdate.encode(), com.runehive.net.packet.out.SendPlayerUpdate.encode(), com.runehive.net.packet.OutgoingPacket.OutgoingPacket(), and com.runehive.net.packet.OutgoingPacket.OutgoingPacket().
getString()
String com.runehive.net.packet.PacketBuilder.getString ()
Definition at line 288 of file PacketBuilder.java.
{
        byte temp;
        StringBuilder builder = new StringBuilder();
        while (content().isReadable() && (temp = content().readByte()) != 10) {
            builder.append((char) temp);
        }
        return builder.toString();
    }
initializeAccess()
PacketBuilder com.runehive.net.packet.PacketBuilder.initializeAccess (AccessType type)
Definition at line 51 of file PacketBuilder.java.
{
        switch (type) {
        case BIT:
            bitPosition = content().writerIndex() * 8;
            break;
        case BYTE:
            content().writerIndex((bitPosition + 7) / 8);
            bitPosition = -1;
            break;
        }
        return this;
    }
References bitPosition, and PacketBuilder().
toPacket() [1/2]
GamePacket com.runehive.net.packet.PacketBuilder.toPacket (int opcode)
Definition at line 280 of file PacketBuilder.java.
{
        return new GamePacket(opcode, PacketType.FIXED, content());
    }
References com.runehive.net.packet.PacketType.FIXED.
toPacket() [2/2]
GamePacket com.runehive.net.packet.PacketBuilder.toPacket (int opcode, PacketType type)
Definition at line 284 of file PacketBuilder.java.
{
        return new GamePacket(opcode, type, content());
    }
wrap()
PacketBuilder com.runehive.net.packet.PacketBuilder.wrap (ByteBuf buf) static
Definition at line 47 of file PacketBuilder.java.
{
        return new PacketBuilder(buf);
    }
References PacketBuilder().
writeBit()
PacketBuilder com.runehive.net.packet.PacketBuilder.writeBit (boolean flag)
Definition at line 87 of file PacketBuilder.java.
{
        writeBits(1, flag ? 1 : 0);
        return this;
    }
References PacketBuilder(), and writeBits().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.addNewPlayer(), and com.runehive.net.packet.out.SendPlayerUpdate.updateMovement().
writeBits()
PacketBuilder com.runehive.net.packet.PacketBuilder.writeBits (int amount, int value)
Definition at line 92 of file PacketBuilder.java.
{
        checkState(amount >= 1 && amount <= 32, "Number of bits must be between 1 and 32 inclusive.");
        int bytePos = bitPosition >> 3;
        int bitOffset = 8 - (bitPosition & 7);
        bitPosition = bitPosition + amount;
        int requiredSpace = bytePos - content().writerIndex() + 1;
        requiredSpace += (amount + 7) / 8;
        if (content().writableBytes() < requiredSpace) {
            content().capacity(content().capacity() + requiredSpace);
        }
        for (; amount > bitOffset; bitOffset = 8) {
            byte tmp = content().getByte(bytePos);
            tmp &= ~BIT_MASK[bitOffset];
            tmp |= (value >> (amount - bitOffset)) & BIT_MASK[bitOffset];
            content().setByte(bytePos++, tmp);
            amount -= bitOffset;
        }
        if (amount == bitOffset) {
            byte tmp = content().getByte(bytePos);
            tmp &= ~BIT_MASK[bitOffset];
            tmp |= value & BIT_MASK[bitOffset];
            content().setByte(bytePos, tmp);
        } else {
            byte tmp = content().getByte(bytePos);
            tmp &= ~(BIT_MASK[amount] << (bitOffset - amount));
            tmp |= (value & BIT_MASK[amount]) << (bitOffset - amount);
            content().setByte(bytePos, tmp);
        }
        return this;
    }
References BIT_MASK, bitPosition, and PacketBuilder().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.addNewPlayer(), com.runehive.net.packet.out.SendPlayerUpdate.updateMovement(), and writeBit().
writeBuffer()
PacketBuilder com.runehive.net.packet.PacketBuilder.writeBuffer (ByteBuf buffer)
Definition at line 297 of file PacketBuilder.java.
{
        this.content().writeBytes(buffer);
        return this;
    }
References PacketBuilder().
writeByte() [1/2]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeByte (int value)
Definition at line 64 of file PacketBuilder.java.
{
        writeByte(value, ByteModification.NONE);
        return this;
    }
References com.runehive.net.codec.ByteModification.NONE, PacketBuilder(), and writeByte().
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendAnimationMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendAnimationMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask(), com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendForceMovementMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask(), com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer(), writeByte(), writeBytes(), writeBytesReverse(), writeInt(), writeLong(), writeShort(), and writeString().
writeByte() [2/2]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeByte (int value, ByteModification type)
Definition at line 69 of file PacketBuilder.java.
{
        switch (type) {
        case ADD:
            value += 128;
            break;
        case NEG:
            value = -value;
            break;
        case SUB:
            value = 128 - value;
            break;
        case NONE:
            break;
        }
        content().writeByte((byte) value);
        return this;
    }
References PacketBuilder().
writeByteArray() [1/2]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeByteArray (byte[] bytes)
Definition at line 302 of file PacketBuilder.java.
{
        content().writeBytes(bytes);
        return this;
    }
References PacketBuilder().
writeByteArray() [2/2]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeByteArray (byte[] bytes, int offset, int length)
Definition at line 307 of file PacketBuilder.java.
{
        content().writeBytes(bytes, offset, length);
        return this;
    }
References PacketBuilder().
writeBytes() [1/2]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeBytes (byte[] from, int size)
Definition at line 124 of file PacketBuilder.java.
{
        content().writeBytes(from, 0, size);
        return this;
    }
References PacketBuilder().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask().
writeBytes() [2/2]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeBytes (ByteBuf from)
Definition at line 129 of file PacketBuilder.java.
{
        for (int i = 0; i < from.writerIndex(); i++) {
            writeByte(from.getByte(i));
        }
        return this;
    }
References PacketBuilder(), and writeByte().
writeBytesReverse()
PacketBuilder com.runehive.net.packet.PacketBuilder.writeBytesReverse (byte[] data)
Definition at line 136 of file PacketBuilder.java.
{
        for (int i = data.length - 1; i >= 0; i--) {
            writeByte(data[i]);
        }
        return this;
    }
References PacketBuilder(), and writeByte().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask().
writeInt() [1/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeInt (int value)
Definition at line 143 of file PacketBuilder.java.
{
        writeInt(value, ByteModification.NONE, ByteOrder.BE);
        return this;
    }
References com.runehive.net.codec.ByteOrder.BE, com.runehive.net.codec.ByteModification.NONE, PacketBuilder(), and writeInt().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.out.SendNpcUpdate.appendGfxMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendGraphicMask(), writeInt(), writeInt(), and writeInt().
writeInt() [2/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeInt (int value, ByteModification type)
Definition at line 153 of file PacketBuilder.java.
{
        writeInt(value, type, ByteOrder.BE);
        return this;
    }
References com.runehive.net.codec.ByteOrder.BE, PacketBuilder(), and writeInt().
writeInt() [3/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeInt (int value, ByteModification type, ByteOrder order)
Definition at line 158 of file PacketBuilder.java.
{
        switch (order) {
        case BE:
            writeByte(value >> 24);
            writeByte(value >> 16);
            writeByte(value >> 8);
            writeByte(value, type);
            break;
        case ME:
            writeByte(value >> 8);
            writeByte(value, type);
            writeByte(value >> 24);
            writeByte(value >> 16);
            break;
        case IME:
            writeByte(value >> 16);
            writeByte(value >> 24);
            writeByte(value, type);
            writeByte(value >> 8);
            break;
        case LE:
            writeByte(value, type);
            writeByte(value >> 8);
            writeByte(value >> 16);
            writeByte(value >> 24);
            break;
        }
        return this;
    }
References PacketBuilder(), and writeByte().
writeInt() [4/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeInt (int value, ByteOrder order)
Definition at line 148 of file PacketBuilder.java.
{
        writeInt(value, ByteModification.NONE, order);
        return this;
    }
References com.runehive.net.codec.ByteModification.NONE, PacketBuilder(), and writeInt().
writeLong() [1/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeLong (long value)
Definition at line 188 of file PacketBuilder.java.
{
        writeLong(value, ByteModification.NONE, ByteOrder.BE);
        return this;
    }
References com.runehive.net.codec.ByteOrder.BE, com.runehive.net.codec.ByteModification.NONE, PacketBuilder(), and writeLong().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), writeLong(), writeLong(), and writeLong().
writeLong() [2/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeLong (long value, ByteModification type)
Definition at line 198 of file PacketBuilder.java.
{
        writeLong(value, type, ByteOrder.BE);
        return this;
    }
References com.runehive.net.codec.ByteOrder.BE, PacketBuilder(), and writeLong().
writeLong() [3/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeLong (long value, ByteModification type, ByteOrder order)
Definition at line 203 of file PacketBuilder.java.
{
        switch (order) {
        case BE:
            writeByte((int) (value >> 56));
            writeByte((int) (value >> 48));
            writeByte((int) (value >> 40));
            writeByte((int) (value >> 32));
            writeByte((int) (value >> 24));
            writeByte((int) (value >> 16));
            writeByte((int) (value >> 8));
            writeByte((int) value, type);
            break;
        case ME:
            throw new UnsupportedOperationException("Middle-endian long " + "is not implemented!");
        case IME:
            throw new UnsupportedOperationException("Inverse-middle-endian long is not implemented!");
        case LE:
            writeByte((int) value, type);
            writeByte((int) (value >> 8));
            writeByte((int) (value >> 16));
            writeByte((int) (value >> 24));
            writeByte((int) (value >> 32));
            writeByte((int) (value >> 40));
            writeByte((int) (value >> 48));
            writeByte((int) (value >> 56));
            break;
        }
        return this;
    }
References PacketBuilder(), and writeByte().
writeLong() [4/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeLong (long value, ByteOrder order)
Definition at line 193 of file PacketBuilder.java.
{
        writeLong(value, ByteModification.NONE, order);
        return this;
    }
References com.runehive.net.codec.ByteModification.NONE, PacketBuilder(), and writeLong().
writeShort() [1/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeShort (int value)
Definition at line 237 of file PacketBuilder.java.
{
        writeShort(value, ByteModification.NONE, ByteOrder.BE);
        return this;
    }
References com.runehive.net.codec.ByteOrder.BE, com.runehive.net.codec.ByteModification.NONE, PacketBuilder(), and writeShort().
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendAnimationMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendAnimationMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask(), com.runehive.net.packet.out.SendNpcUpdate.appendFaceCoordinateMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceCoordinteMask(), com.runehive.net.packet.out.SendNpcUpdate.appendFaceEntityMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceEntityMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendForceMovementMask(), com.runehive.net.packet.out.SendNpcUpdate.appendGfxMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendGraphicMask(), com.runehive.net.packet.out.SendNpcUpdate.appendTransformationMask(), writeShort(), writeShort(), and writeShort().
writeShort() [2/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeShort (int value, ByteModification type)
Definition at line 247 of file PacketBuilder.java.
{
        writeShort(value, type, ByteOrder.BE);
        return this;
    }
References com.runehive.net.codec.ByteOrder.BE, PacketBuilder(), and writeShort().
writeShort() [3/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeShort (int value, ByteModification type, ByteOrder order)
Definition at line 252 of file PacketBuilder.java.
{
        switch (order) {
        case BE:
            writeByte(value >> 8);
            writeByte(value, type);
            break;
        case ME:
            throw new IllegalArgumentException("Middle-endian short is " + "impossible!");
        case IME:
            throw new IllegalArgumentException("Inverse-middle-endian " + "short is impossible!");
        case LE:
            writeByte(value, type);
            writeByte(value >> 8);
            break;
        default:
            break;
        }
        return this;
    }
References PacketBuilder(), and writeByte().
writeShort() [4/4]
PacketBuilder com.runehive.net.packet.PacketBuilder.writeShort (int value, ByteOrder order)
Definition at line 242 of file PacketBuilder.java.
{
        writeShort(value, ByteModification.NONE, order);
        return this;
    }
References com.runehive.net.codec.ByteModification.NONE, PacketBuilder(), and writeShort().
writeString()
PacketBuilder com.runehive.net.packet.PacketBuilder.writeString (String string)
Definition at line 272 of file PacketBuilder.java.
{
        for (final byte value : string.getBytes()) {
            writeByte(value);
        }
        writeByte(10);
        return this;
    }
References PacketBuilder(), and writeByte().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.out.SendNpcUpdate.appendForceChatMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendForceChatMask().
Member Data Documentation
BIT_MASK
final int [] com.runehive.net.packet.PacketBuilder.BIT_MASK = new int[32] static private
Definition at line 21 of file PacketBuilder.java.
Referenced by [static initializer](), and writeBits().
bitPosition
int com.runehive.net.packet.PacketBuilder.bitPosition private
Definition at line 30 of file PacketBuilder.java.
Referenced by initializeAccess(), and writeBits().
DEFAULT_CAPACITY
final int com.runehive.net.packet.PacketBuilder.DEFAULT_CAPACITY = 128 static private
Definition at line 29 of file PacketBuilder.java.
Referenced by alloc().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/PacketBuilder.java