RuneHive-Game: com.runehive.content.bags.ItemBag Class Reference
com.runehive.content.bags.ItemBag Class Reference abstract
Public Member Functions
void check (Player player)
void empty (Player player)
void fill (Player player)
abstract String getIndication ()
abstract String getItem ()
abstract String getName ()
abstract Predicate< Item > isAllowed ()
ItemBag (ItemContainer container)
Public Attributes
final ItemContainer container
Detailed Description
Definition at line 11 of file ItemBag.java.
Constructor & Destructor Documentation
ItemBag()
com.runehive.content.bags.ItemBag.ItemBag (ItemContainer container)
Definition at line 15 of file ItemBag.java.
{
        this.container = container;
    }
References container.
Member Function Documentation
check()
void com.runehive.content.bags.ItemBag.check (Player player)
Reimplemented in com.runehive.content.bags.impl.CoalBag.
Definition at line 72 of file ItemBag.java.
{
        player.message("You look in your "+getName()+" and see:");
        if (container.getFreeSlots() == container.capacity()) {
            player.message("The "+getName()+" is empty.");
            return;
        }
        for (Item item : container.getItems()) {
            if(item == null) continue;
            player.message(item.getAmount() + "x " + ItemDefinition.get(item.getId()).getName());
        }
    }
References container, com.runehive.game.world.items.ItemDefinition.get(), getName(), com.runehive.game.world.items.ItemDefinition.getName(), and com.runehive.game.world.entity.mob.player.Player.message().
empty()
void com.runehive.content.bags.ItemBag.empty (Player player)
Definition at line 44 of file ItemBag.java.
{
        if (container.getFreeSlots() == container.capacity()) {
            player.message("The "+getName()+" is already empty.");
            return;
        }
        if (player.inventory.getFreeSlots() <= 0) {
            player.message("You don't have enough inventory space to empty the contents of this "+getName()+".");
            return;
        }
        for(Item item : container.getItems()) {
            int freeSlots = player.inventory.getFreeSlots();
            if (freeSlots <= 0) {
                player.inventory.refresh();
                return;
            }
            if(item == null) continue;
            int amount = item.getAmount();
            if(amount > freeSlots)
                amount = freeSlots;
            container.remove(new Item(item.getId(), amount));
            player.inventory.add(new Item(item.getId(), item.getAmount()));
        }
        player.inventory.refresh();
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), container, com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.message(), and com.runehive.game.world.items.containers.inventory.Inventory.refresh().
fill()
void com.runehive.content.bags.ItemBag.fill (Player player)
Definition at line 27 of file ItemBag.java.
{
        player.message("You search your inventory for "+getItem()+" to put into the "+getName()+"...");
        if (Arrays.stream(player.inventory.getItems()).noneMatch(isAllowed())) {
            player.message("There "+getIndication()+" no "+getItem()+" in your inventory that can be added to the "+getName()+".");
            return;
        }
        Arrays.stream(player.inventory.getItems()).filter(isAllowed()).forEach(item -> {
            player.inventory.remove(item);
            container.add(item);
        });
        player.message("You add the "+getItem()+" to your "+getName()+".");
        player.inventory.refresh();
    }
References container, getIndication(), getItem(), com.runehive.game.world.items.containers.ItemContainer.getItems(), getName(), com.runehive.game.world.entity.mob.player.Player.inventory, isAllowed(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.inventory.Inventory.refresh(), and com.runehive.game.world.items.containers.ItemContainer.remove().
getIndication()
abstract String com.runehive.content.bags.ItemBag.getIndication () abstract
Reimplemented in com.runehive.content.bags.impl.CoalBag, and com.runehive.content.bags.impl.GemBag.
Referenced by fill().
getItem()
abstract String com.runehive.content.bags.ItemBag.getItem () abstract
Reimplemented in com.runehive.content.bags.impl.CoalBag, and com.runehive.content.bags.impl.GemBag.
Referenced by fill().
getName()
abstract String com.runehive.content.bags.ItemBag.getName () abstract
Reimplemented in com.runehive.content.bags.impl.CoalBag, and com.runehive.content.bags.impl.GemBag.
Referenced by check(), empty(), and fill().
isAllowed()
abstract Predicate< Item > com.runehive.content.bags.ItemBag.isAllowed () abstract
Reimplemented in com.runehive.content.bags.impl.CoalBag, and com.runehive.content.bags.impl.GemBag.
Referenced by fill().
Member Data Documentation
container
final ItemContainer com.runehive.content.bags.ItemBag.container
Definition at line 13 of file ItemBag.java.
Referenced by com.runehive.content.bags.impl.CoalBag.check(), check(), empty(), fill(), and ItemBag().
The documentation for this class was generated from the following file:
java/com/runehive/content/bags/ItemBag.java