RuneHive-Game: com.runehive.game.Graphic Class Reference
com.runehive.game.Graphic Class Reference
Represents a single graphic that can be used by entities.
Public Member Functions
int compareTo (Graphic other)
boolean equals (Object obj)
int getDelay ()
Gets the delay of this graphic.
int getHeight ()
Gets the height of this graphic.
int getId ()
Gets the id of this graphic.
Graphic (int id)
Constructs a new Graphic object with no delay, a low height, and normal priotiry.
Graphic (int id, boolean high)
Constructs a new Graphic object with no delay and normal priotiry.
Graphic (int id, boolean high, UpdatePriority priority)
Constructs a new Graphic object with no delay.
Graphic (int id, int delay)
Constructs a new Graphic object with a low height and normal priotiry.
Graphic (int id, int delay, boolean high)
Constructs a new Graphic object with a normal priotiry.
Graphic (int id, int delay, boolean high, UpdatePriority priority)
Constructs a new Graphic object.
Graphic (int id, int delay, int height)
Graphic (int id, int delay, int height, UpdatePriority priority)
Graphic (int id, int delay, UpdatePriority priority)
Constructs a new Graphic object with a low height.
Graphic (int id, UpdatePriority priority)
Constructs a new Graphic object with no delay and a low height.
int hashCode ()
String toString ()
Static Public Attributes
static final int HIGH_HEIGHT = 0x640000
static final int LUNAR_ID = 747
static final Graphic LUNAR_TELE = new Graphic(LUNAR_ID, 0, UpdatePriority.VERY_HIGH)
static final int NORMAL_ID = 308
static final Graphic NORMAL_TELE = new Graphic(NORMAL_ID, 43, UpdatePriority.VERY_HIGH)
static final Graphic RESET = new Graphic(RESET_ID, UpdatePriority.VERY_LOW)
static final int RESET_ID = 0xFFFF
Private Attributes
final int delay
The delay of this graphic.
final int height
The height of this graphic.
final int id
The graphic id.
final UpdatePriority priority
The priority of the graphic.
Detailed Description
Represents a single graphic that can be used by entities.
Also known as GFX.
Author
Michael | Chex
Definition at line 10 of file Graphic.java.
Constructor & Destructor Documentation
Graphic() [1/10]
com.runehive.game.Graphic.Graphic (int id)
Constructs a new Graphic object with no delay, a low height, and normal priotiry.
Parameters
id The graphic id.
Definition at line 40 of file Graphic.java.
{
        this(id, 0, false);
    }
References id.
Referenced by compareTo(), and equals().
Graphic() [2/10]
com.runehive.game.Graphic.Graphic (int id, boolean high)
Constructs a new Graphic object with no delay and normal priotiry.
Parameters
id The graphic id.
high The graphic height state.
Definition at line 54 of file Graphic.java.
{
        this(id, 0, high);
    }
References id.
Graphic() [3/10]
com.runehive.game.Graphic.Graphic (int id, int delay)
Constructs a new Graphic object with a low height and normal priotiry.
Parameters
id The graphic id.
delay The graphic delay.
Definition at line 68 of file Graphic.java.
{
        this(id, delay, false);
    }
References delay, and id.
Graphic() [4/10]
com.runehive.game.Graphic.Graphic (int id, int delay, boolean high)
Constructs a new Graphic object with a normal priotiry.
Parameters
id The graphic id.
delay The graphic delay.
high The graphic height state.
Definition at line 84 of file Graphic.java.
{
        this(id, delay, high, UpdatePriority.NORMAL);
    }
References delay, id, and com.runehive.game.UpdatePriority.NORMAL.
Graphic() [5/10]
com.runehive.game.Graphic.Graphic (int id, UpdatePriority priority)
Constructs a new Graphic object with no delay and a low height.
Parameters
id The graphic id.
priority The graphic priority.
Definition at line 96 of file Graphic.java.
{
        this(id, 0, false, priority);
    }
References id, and priority.
Graphic() [6/10]
com.runehive.game.Graphic.Graphic (int id, boolean high, UpdatePriority priority)
Constructs a new Graphic object with no delay.
Parameters
id The graphic id.
high The graphic height state.
priority The graphic priority.
Definition at line 111 of file Graphic.java.
{
        this(id, 0, high, priority);
    }
References id, and priority.
Graphic() [7/10]
com.runehive.game.Graphic.Graphic (int id, int delay, UpdatePriority priority)
Constructs a new Graphic object with a low height.
Parameters
id The graphic id.
delay The graphic delay.
priority The graphic priority.
Definition at line 126 of file Graphic.java.
{
        this(id, delay, false, priority);
    }
References delay, id, and priority.
Graphic() [8/10]
com.runehive.game.Graphic.Graphic (int id, int delay, boolean high, UpdatePriority priority)
Constructs a new Graphic object.
Parameters
id The graphic id.
delay The graphic delay.
high The graphic height state.
priority The graphic priority.
Definition at line 144 of file Graphic.java.
{
        this(id, delay, high ? HIGH_HEIGHT : 0, priority);
    }
References delay, HIGH_HEIGHT, id, and priority.
Graphic() [9/10]
com.runehive.game.Graphic.Graphic (int id, int delay, int height, UpdatePriority priority)
Definition at line 148 of file Graphic.java.
{
        this.id = id;
        this.delay = delay;
        this.height = height;
        this.priority = priority;
    }
References delay, height, id, and priority.
Graphic() [10/10]
com.runehive.game.Graphic.Graphic (int id, int delay, int height)
Definition at line 155 of file Graphic.java.
{
        this.id = id;
        this.delay = delay;
        this.height = height;
        this.priority = UpdatePriority.NORMAL;
    }
References delay, height, id, and com.runehive.game.UpdatePriority.NORMAL.
Member Function Documentation
compareTo()
int com.runehive.game.Graphic.compareTo (Graphic other)
Definition at line 204 of file Graphic.java.
{
        return other.priority.ordinal() - priority.ordinal();
    }
References Graphic(), and priority.
Referenced by com.runehive.game.world.entity.mob.Mob.graphic().
equals()
boolean com.runehive.game.Graphic.equals (Object obj)
Definition at line 195 of file Graphic.java.
{
        if (obj instanceof Graphic) {
            Graphic other = (Graphic) obj;
            return id == other.id && height == other.height && delay == other.delay && priority == other.priority;
        }
        return obj == this;
    }
References delay, Graphic(), height, and priority.
getDelay()
int com.runehive.game.Graphic.getDelay ()
Gets the delay of this graphic.
Returns
delay
Definition at line 167 of file Graphic.java.
{
        return delay;
    }
References delay.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendGfxMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendGraphicMask().
getHeight()
int com.runehive.game.Graphic.getHeight ()
Gets the height of this graphic.
Returns
height
Definition at line 176 of file Graphic.java.
{
        return height;
    }
References height.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendGfxMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendGraphicMask(), and com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic().
getId()
int com.runehive.game.Graphic.getId ()
Gets the id of this graphic.
Returns
id
Definition at line 185 of file Graphic.java.
                       {
        return id;
    }
References id.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendGfxMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendGraphicMask(), and com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.getEndGraphic().
hashCode()
int com.runehive.game.Graphic.hashCode ()
Definition at line 190 of file Graphic.java.
{
        return Objects.hash(id, delay, height, priority);
    }
References delay, height, and priority.
toString()
String com.runehive.game.Graphic.toString ()
Definition at line 209 of file Graphic.java.
{
        return String.format("Graphic[id=%s, delay=%s, height=%s, priority=%s]", id, delay, height, priority);
    }
References delay, height, and priority.
Member Data Documentation
delay
final int com.runehive.game.Graphic.delay private
The delay of this graphic.
Definition at line 25 of file Graphic.java.
Referenced by equals(), getDelay(), Graphic(), Graphic(), Graphic(), Graphic(), Graphic(), Graphic(), hashCode(), and toString().
height
final int com.runehive.game.Graphic.height private
The height of this graphic.
Definition at line 28 of file Graphic.java.
Referenced by equals(), getHeight(), Graphic(), Graphic(), hashCode(), and toString().
HIGH_HEIGHT
final int com.runehive.game.Graphic.HIGH_HEIGHT = 0x640000 static
Definition at line 12 of file Graphic.java.
Referenced by Graphic().
id
final int com.runehive.game.Graphic.id private
The graphic id.
Definition at line 22 of file Graphic.java.
Referenced by getId(), Graphic(), Graphic(), Graphic(), Graphic(), Graphic(), Graphic(), Graphic(), Graphic(), Graphic(), and Graphic().
LUNAR_ID
final int com.runehive.game.Graphic.LUNAR_ID = 747 static
Definition at line 15 of file Graphic.java.
LUNAR_TELE
final Graphic com.runehive.game.Graphic.LUNAR_TELE = new Graphic(LUNAR_ID, 0, UpdatePriority.VERY_HIGH) static
Definition at line 19 of file Graphic.java.
NORMAL_ID
final int com.runehive.game.Graphic.NORMAL_ID = 308 static
Definition at line 14 of file Graphic.java.
NORMAL_TELE
final Graphic com.runehive.game.Graphic.NORMAL_TELE = new Graphic(NORMAL_ID, 43, UpdatePriority.VERY_HIGH) static
Definition at line 18 of file Graphic.java.
priority
final UpdatePriority com.runehive.game.Graphic.priority private
The priority of the graphic.
Definition at line 31 of file Graphic.java.
Referenced by compareTo(), equals(), Graphic(), Graphic(), Graphic(), Graphic(), Graphic(), hashCode(), and toString().
RESET
final Graphic com.runehive.game.Graphic.RESET = new Graphic(RESET_ID, UpdatePriority.VERY_LOW) static
Definition at line 17 of file Graphic.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendGfxMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendGraphicMask(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.finish(), com.runehive.content.activity.impl.magearena.MageArena.finish(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.finish(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.finish(), com.runehive.game.world.entity.mob.Mob.graphic(), com.runehive.content.activity.inferno.Inferno.handleDeath(), com.runehive.game.action.impl.TeleportAction.onCancel(), com.runehive.content.activity.impl.CerberusActivity.onDeath(), com.runehive.content.activity.impl.fightcaves.FightCaves.onDeath(), com.runehive.content.activity.impl.godwars.GodwarsActivity.onDeath(), com.runehive.content.activity.impl.magearena.MageArena.onDeath(), com.runehive.content.activity.impl.pestcontrol.PestControlGame.onDeath(), com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.onDeath(), com.runehive.content.activity.impl.zulrah.ZulrahActivity.onRegionChange(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.content.activity.Activity.remove(), and com.runehive.content.lms.LMSGame.reset().
RESET_ID
final int com.runehive.game.Graphic.RESET_ID = 0xFFFF static
Definition at line 16 of file Graphic.java.
The documentation for this class was generated from the following file:
java/com/runehive/game/Graphic.java