RuneHive-Game: com.runehive.content.dialogue.impl.VoteDialogue Class Reference
com.runehive.content.dialogue.impl.VoteDialogue Class Reference
Handles the vote dialogue.
Public Member Functions
void sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Private Member Functions
void exchange (DialogueFactory factory, int amount)
Handles redeeming vote tokens.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.content.dialogue.Dialogue
static final boolean isDialogueButton (int button)
Checks if the button triggered is an optional dialogue button.
Static Public Attributes inherited from com.runehive.content.dialogue.Dialogue
static final ImmutableList< Integer > DIALOGUE_BUTTONS = ImmutableList.of(2461, 2471, 2482, 2462, 2472, 2483, 2473, 2484, 2485, 2494, 2495, 2496, 2497, 2498)
The action buttons responsible for dialogues.
Detailed Description
Handles the vote dialogue.
Author
Daniel
Definition at line 18 of file VoteDialogue.java.
Member Function Documentation
exchange()
void com.runehive.content.dialogue.impl.VoteDialogue.exchange (DialogueFactory factory, int amount) private
Handles redeeming vote tokens.
Definition at line 42 of file VoteDialogue.java.
{
        Player player = factory.getPlayer();
        if (amount > 10000) {
            factory.sendNpcChat(7481, Expression.SAD, "Sorry but you can only exchange", " 10,000 tokens at a time!").execute();
            return;
        }
        int tokenAmount = player.inventory.computeAmountForId(7478);
        if (amount > tokenAmount)
            amount = tokenAmount;
        if (amount == 0) {
            factory.sendNpcChat(7481, Expression.SAD, "Sorry but you do not have enough", "vote tokens to do this!").execute();
            return;
        }
        player.votePoints += amount;
        player.inventory.remove(7478, amount);
        factory.sendNpcChat(7481, Expression.SAD, "I've exchanged " + amount + " vote tokens for you!", "You now have " + Utility.formatDigits(player.votePoints) + " vote points!").execute();
    }
References com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.util.Utility.formatDigits(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.content.dialogue.Expression.SAD, com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), and com.runehive.game.world.entity.mob.player.Player.votePoints.
Referenced by sendDialogues().
sendDialogues()
void com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Parameters
factory The factory for this dialogue.
Reimplemented from com.runehive.content.dialogue.Dialogue.
Definition at line 21 of file VoteDialogue.java.
{
        Player player = factory.getPlayer();
        factory.sendNpcChat(7481, Expression.HAPPY, "Hello " + player.getName() + "!", "What can I do for you today?");
        factory.sendOption("Would you want to know what are some of the benefits of voting are?", () -> {
            factory.sendPlayerChat(Expression.HAPPY, "Yes I would!");
            factory.sendNpcChat(7481, "Voting results in attracting new players!", "In return, you'll receive", "vote points that you can use to buy", "items from the vote store.");
        }, "Exchange vote token", () -> {
            World.schedule(1, () -> player.send(new SendInputAmount("How many vote tokens would you like to exchange?", 10, input -> exchange(factory, Integer.parseInt(input)))));
        }, "Show me your voting store!", () -> {
            Store.STORES.get("osroyale Vote Store").open(player);
        }, "I would like to vote to support this great server!", () -> {
            player.send(new SendURL("https://runehive.com"));
            factory.sendNpcChat(7481, "Thank you for voting!");
        }, "Nevermind, I don't want to do anything for this server.", () -> {
            factory.clear();
        });
        factory.execute();
    }
References com.runehive.content.dialogue.DialogueFactory.clear(), exchange(), com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.dialogue.Expression.HAPPY, com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.content.dialogue.DialogueFactory.sendOption(), com.runehive.content.dialogue.DialogueFactory.sendPlayerChat(), and com.runehive.content.store.Store.STORES.
The documentation for this class was generated from the following file:
java/com/runehive/content/dialogue/impl/VoteDialogue.java