RuneHive-Game: com.runehive.content.wintertodt.actions.LightBrazier Class Reference
com.runehive.content.wintertodt.actions.LightBrazier Class Reference
Public Member Functions
String getName ()
Gets the name of this action.
WalkablePolicy getWalkablePolicy ()
Gets the WalkablePolicy of this action.
LightBrazier (Player player, Brazier brazier)
Public Member Functions inherited from com.runehive.game.action.Action< T extends Mob >
Action (T mob, int delay)
Creates a new Action randomevent.
Action (T mob, int delay, boolean instant)
Creates a new Action randomevent.
boolean cancellableInProgress ()
T getMob ()
Gets the player.
boolean prioritized ()
Determines if this action is prioritized.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Protected Member Functions
void execute ()
A function representing the unit of work that will be carried out.
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Private Attributes
Brazier brazier
Additional Inherited Members
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
Definition at line 11 of file LightBrazier.java.
Constructor & Destructor Documentation
LightBrazier()
com.runehive.content.wintertodt.actions.LightBrazier.LightBrazier (Player player, Brazier brazier)
Definition at line 15 of file LightBrazier.java.
{
        super(player, 3);
        this.brazier = brazier;
    }
References brazier.
Member Function Documentation
execute()
void com.runehive.content.wintertodt.actions.LightBrazier.execute () protected
A function representing the unit of work that will be carried out.
Reimplemented from com.runehive.game.task.Task.
Definition at line 31 of file LightBrazier.java.
{
        if(brazier.getBrazierState() != 2) {
            //brazier.getObject().transform(Wintertodt.BURNING_BRAZIER_ID);
            brazier.getObject().unregister();
            brazier.setObject(Wintertodt.BURNING_BRAZIER_ID);
            brazier.getObject().register();
        }
        getMob().skills.addExperience(Skill.FIREMAKING, (Skill.getLevelForExperience(getMob().skills.get(Skill.FIREMAKING).getExperience()) * 6) * Config.FIREMAKING_MODIFICATION);
        Wintertodt.addPoints(getMob(), 25);
        getMob().animate(65535);
        getMob().action.getCurrentAction().cancel();
    }
References com.runehive.content.wintertodt.Wintertodt.addPoints(), brazier, com.runehive.content.wintertodt.Wintertodt.BURNING_BRAZIER_ID, com.runehive.game.world.entity.skill.Skill.FIREMAKING, com.runehive.Config.FIREMAKING_MODIFICATION, com.runehive.game.world.entity.skill.Skill.getLevelForExperience(), and com.runehive.game.action.Action< T extends Mob >.getMob().
getName()
String com.runehive.content.wintertodt.actions.LightBrazier.getName ()
Gets the name of this action.
Returns
The name of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 26 of file LightBrazier.java.
{
        return "Light brazier";
    }
getWalkablePolicy()
WalkablePolicy com.runehive.content.wintertodt.actions.LightBrazier.getWalkablePolicy ()
Gets the WalkablePolicy of this action.
Returns
The walkable policy of this action.
Reimplemented from com.runehive.game.action.Action< T extends Mob >.
Definition at line 21 of file LightBrazier.java.
{
        return WalkablePolicy.NON_WALKABLE;
    }
References com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE.
Member Data Documentation
brazier
Brazier com.runehive.content.wintertodt.actions.LightBrazier.brazier private
Definition at line 13 of file LightBrazier.java.
Referenced by execute(), and LightBrazier().
The documentation for this class was generated from the following file:
java/com/runehive/content/wintertodt/actions/LightBrazier.java