RuneHive-Game: com.runehive.content.ai.AIDialogueHandler Class Reference
com.runehive.content.ai.AIDialogueHandler Class Reference
Public Member Functions
AIDialogueHandler (Npc npc)
void sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Static Public Member Functions
static void handleAICommand (Player player, String message)
Process AI command input (called from command handler)
Static Public Member Functions inherited from com.runehive.content.dialogue.Dialogue
static final boolean isDialogueButton (int button)
Checks if the button triggered is an optional dialogue button.
Private Member Functions
void processGandalfAIMessage (Player player, Npc npc, String message)
String sanitizeInput (String input)
void streamGandalfResponse (Player player, Npc npc, String response)
String[] wrapTextToLines (String text, int maxCharsPerLine)
Static Private Member Functions
static Npc findNearbyNpc (Player player, int npcId, int targetX, int targetY, int maxDistance)
Find an NPC by ID near specific coordinates.
Private Attributes
final Npc npc
Static Private Attributes
static final int GANDALF_AI_ID = 2108
static final Logger logger = LoggerFactory.getLogger(AIDialogueHandler.class)
Additional Inherited Members
Static Public Attributes inherited from com.runehive.content.dialogue.Dialogue
static final ImmutableList< Integer > DIALOGUE_BUTTONS = ImmutableList.of(2461, 2471, 2482, 2462, 2472, 2483, 2473, 2484, 2485, 2494, 2495, 2496, 2497, 2498)
The action buttons responsible for dialogues.
Detailed Description
Definition at line 17 of file AIDialogueHandler.java.
Constructor & Destructor Documentation
AIDialogueHandler()
com.runehive.content.ai.AIDialogueHandler.AIDialogueHandler (Npc npc)
Definition at line 24 of file AIDialogueHandler.java.
{
        this.npc = npc;
    }
References npc.
Referenced by handleAICommand(), and streamGandalfResponse().
Member Function Documentation
findNearbyNpc()
Npc com.runehive.content.ai.AIDialogueHandler.findNearbyNpc (Player player, int npcId, int targetX, int targetY, int maxDistance) static private
Find an NPC by ID near specific coordinates.
Definition at line 101 of file AIDialogueHandler.java.
{
        for (Npc npc : World.getNpcs()) {
            if (npc.id == npcId && npc.getPosition().getHeight() == player.getPosition().getHeight()) {
                int distX = Math.abs(npc.getPosition().getX() - targetX);
                int distY = Math.abs(npc.getPosition().getY() - targetY);
                if (distX <= maxDistance && distY <= maxDistance) {
                    return npc;
                }
            }
        }
        return null;
    }
References com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.World.getNpcs(), com.runehive.game.world.entity.Entity.getPosition(), and npc.
Referenced by handleAICommand().
handleAICommand()
void com.runehive.content.ai.AIDialogueHandler.handleAICommand (Player player, String message) static
Process AI command input (called from command handler)
Definition at line 53 of file AIDialogueHandler.java.
{
        int npcSpawnX = 1684;
        int npcSpawnY = 3746;
        int maxDistance = 1;
        if (Math.abs(player.getPosition().getX() - npcSpawnX) > maxDistance ||
            Math.abs(player.getPosition().getY() - npcSpawnY) > maxDistance) {
            player.message("You must be near the Wise Old Man to use AI chat.");
            return;
        }
        if (!LazyAIManager.isInitialized()) {
            player.message("AI services are not initialized. Click the Wise Old Man first.");
            return;
        }
        // Find the actual spawned Wise Old Man NPC near the spawn coordinates
        Npc gandalf = findNearbyNpc(player, GANDALF_AI_ID, npcSpawnX, npcSpawnY, maxDistance);
        if (gandalf == null) {
            player.message("Could not find the Wise Old Man NPC. Please stand closer.");
            return;
        }
        // ::gpt must use the exact same choreography as Talk-to on NPC 2108
        // Teleport P to exact position facing the NPC; LOCK P.
        com.runehive.game.world.position.Position npcPos = gandalf.getPosition();
        com.runehive.game.world.position.Position playerTarget = new com.runehive.game.world.position.Position(npcPos.getX() - 1, npcPos.getY(), npcPos.getHeight());
        player.move(playerTarget);
        player.face(gandalf);
        player.locking.lock();
        // Initialize dialogue camera - player speaks first (with delay to prevent misalignment)
        player.dialogueCamNpc = gandalf;
        player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.OFF;
        player.dialogueCamDelayTicks = 2; // delay 2 ticks before camera activates
        com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.boostSwap(player, 8);
        // Mark that player has received instructions and is now using the command
        LazyAIManager.markInstructionsReceived(player.getUsername());
        String sanitizedInput = new AIDialogueHandler(gandalf).sanitizeInput(message);
        new AIDialogueHandler(gandalf).processGandalfAIMessage(player, gandalf, sanitizedInput);
    }
References AIDialogueHandler(), com.runehive.game.world.entity.mob.Mob.face(), findNearbyNpc(), GANDALF_AI_ID, com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.content.ai.LazyAIManager.isInitialized(), com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, com.runehive.content.ai.LazyAIManager.markInstructionsReceived(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.Mob.move(), and com.runehive.game.world.position.Position.Position().
processGandalfAIMessage()
void com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage (Player player, Npc npc, String message) private
Definition at line 122 of file AIDialogueHandler.java.
{
        // Spawn chair at NPC position (facing WEST)
        Position chairPos = npc.getPosition().copy();
        CustomGameObject chair = new CustomGameObject(1096, chairPos, ObjectDirection.WEST, com.runehive.game.world.object.ObjectType.GENERAL_PROP);
        chair.register();
        // Start thinking animation and speak "Hmmmmm" for 3 ticks
        // Treat as advancing into NPC turn (flip camera behind NPC and speed up the turn slightly).
        player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_NPC;
        com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.boostSwap(player, 8);
        npc.animate(new com.runehive.game.Animation(4079));
        npc.speak("Hmmmmm");
        logger.info("Processing Gandalf AI request from {} (length: {})",
                   player.getUsername(), message.length());
        LazyAIManager.getOpenAIService()
            .processPlayerMessage(player.getUsername(), message, npc.id)
            .thenAccept(response -> {
                World.schedule(new Task(3) {
                    @Override
                    public void execute() {
                        if (player == null || !player.isRegistered()) {
                            logger.warn("Player {} is no longer online, skipping response",
                                player != null ? player.getUsername() : "null");
                            chair.unregister();
                            cancel();
                            return;
                        }
                        try {
                            // Remove chair and reset animation after 3 ticks
                            chair.unregister();
                            npc.animate(new com.runehive.game.Animation(-1));
                            player.locking.lock();
                            if (response != null && !response.isEmpty()) {
                                streamGandalfResponse(player, npc, response);
                            } else {
                                player.locking.unlock();
                                player.dialogueFactory
                                    .sendNpcChat(npc.id, Expression.SAD,
                                        "The mystical connection faltered.",
                                        "Perhaps try again with a different query.")
                                    .onAction(() -> {
                                        player.locking.unlock();
                                        player.interfaceManager.close();
                                    })
                                    .execute();
                            }
                        } catch (Exception e) {
                            logger.error("Exception while processing AI response for {}", player.getUsername(), e);
                            player.locking.unlock();
                        }
                        cancel();
                    }
                });
            })
            .exceptionally(throwable -> {
                logger.error("Error in Gandalf AI processing", throwable);
                World.schedule(new Task(1) {
                    @Override
                    public void execute() {
                        if (player == null || !player.isRegistered()) {
                            cancel();
                            return;
                        }
                        try {
                            player.locking.unlock();
                            player.dialogueFactory
                                .sendNpcChat(npc.id, Expression.ANGRY,
                                    "The AI spirits are restless.",
                                    "Please try again in a moment.")
                                .onAction(() -> {
                                    player.interfaceManager.close();
                                })
                                .execute();
                        } catch (Exception e) {
                            logger.error("Exception in error handler for {}", player.getUsername(), e);
                            player.locking.unlock();
                        }
                        cancel();
                    }
                });
                return null;
            });
    }
References com.runehive.content.dialogue.Expression.ANGRY, com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.content.ai.LazyAIManager.getOpenAIService(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.Entity.isRegistered(), com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, logger, npc, com.runehive.content.ai.OpenAIService.processPlayerMessage(), com.runehive.game.world.object.CustomGameObject.register(), com.runehive.content.dialogue.Expression.SAD, com.runehive.game.world.World.schedule(), streamGandalfResponse(), com.runehive.game.world.entity.mob.Locking.unlock(), com.runehive.game.world.object.CustomGameObject.unregister(), and com.runehive.game.world.object.ObjectDirection.WEST.
sanitizeInput()
String com.runehive.content.ai.AIDialogueHandler.sanitizeInput (String input) private
Definition at line 114 of file AIDialogueHandler.java.
{
        if (input == null) {
            return "";
        }
        String cleaned = input.trim().replaceAll("[<>]", "");
        return cleaned.substring(0, Math.min(cleaned.length(), 500));
    }
sendDialogues()
void com.runehive.content.ai.AIDialogueHandler.sendDialogues (DialogueFactory factory)
Sends a player a dialogue.
Parameters
factory The factory for this dialogue.
Reimplemented from com.runehive.content.dialogue.Dialogue.
Definition at line 29 of file AIDialogueHandler.java.
{
        Player player = factory.getPlayer();
        player.locking.lock();
        // Ensure director knows the NPC and start with delay to prevent coordinate misalignment
        player.dialogueCamNpc = npc; // 2108
        player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.OFF;
        player.dialogueCamDelayTicks = 2; // delay 2 ticks before camera activates
        com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.boostSwap(player, 8);
        factory.sendNpcChat(npc.id, Expression.HAPPY,
                "What would you like to ask?",
                "Type in chat: ::gpt <your message>")
               .onAction(() -> {
                   player.locking.unlock();
                   player.interfaceManager.close();
                   com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.requestReset(player);
               })
               .execute();
    }
References com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.content.dialogue.DialogueFactory.getPlayer(), com.runehive.content.dialogue.Expression.HAPPY, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, npc, com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), and com.runehive.game.world.entity.mob.Locking.unlock().
streamGandalfResponse()
void com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse (Player player, Npc npc, String response) private
Definition at line 211 of file AIDialogueHandler.java.
{
        logger.info("[TTS-SERVER] ========================================");
        logger.info("[TTS-SERVER] Sending Gandalf response to player: {}", player.getUsername());
        logger.info("[TTS-SERVER] Full response: {}", response);
        String[] lines = wrapTextToLines(response, 50);
        logger.info("[TTS-SERVER] Wrapped into {} lines", lines.length);
        for (int i = 0; i < lines.length; i++) {
            logger.info("[TTS-SERVER] Line {}: {}", i+1, lines[i]);
        }
        DialogueFactory factory = player.dialogueFactory;
        // Set camera to behind NPC for AI response
        player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_NPC;
        int linesPerPage = 3;
        for (int i = 0; i < lines.length; i += linesPerPage) {
            int endIndex = Math.min(i + linesPerPage, lines.length);
            String[] pageLines = java.util.Arrays.copyOfRange(lines, i, endIndex);
            logger.info("[TTS-SERVER] Sending dialogue page {}: {} lines", (i/linesPerPage)+1, pageLines.length);
            factory.sendNpcChat(npc.id, Expression.HAPPY, pageLines)
                   .onAction(() -> {
                       String combinedText = String.join(" ", pageLines);
                       npc.speak(combinedText);
                   });
        }
        logger.info("[TTS-SERVER] ========================================");
        factory.sendOption(
            "Ask another question", () -> {
                // ASK ANOTHER QUESTION: Immediately reset camera & unlock
                com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.requestReset(player);
                player.locking.unlock();
                player.dialogueFactory.sendDialogue(new AIDialogueHandler(npc)).execute();
            },
            "No further questions", () -> {
                // OPT OUT: Rewind to BEHIND_PLAYER (buttery swap), wait 4 ticks, then overhead line + wave, then unlock and reset
                player.interfaceManager.close();  // Close interface first
                player.dialogueCamMode = com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.Mode.BEHIND_PLAYER;
                com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.boostSwap(player, 6);
                // Wait 5 ticks for camera to reposition behind player, then player speaks
                World.schedule(new Task(5) {
                    @Override
                    public void execute() {
                        // Player overhead text
                        player.speak("No, that's all, thank you.");
                        // 1 tick later, NPC responds with overhead + wave
                        World.schedule(new Task(1) {
                            @Override
                            public void execute() {
                                npc.speak("Come back again, anytime!");
                                npc.animate(863);
                                // After overhead line + animation, unlock & reset camera
                                World.schedule(new Task(3) {
                                    @Override
                                    public void execute() {
                                        LazyAIManager.clearPlayerConsent(player.getUsername());
                                        player.locking.unlock();
                                        com.runehive.game.world.entity.mob.player.camera.DialogueCameraDirector.requestReset(player);
                                        cancel();
                                    }
                                });
                                cancel();
                            }
                        });
                        cancel();
                    }
                });
            }
        );
        factory.execute();
    }
References AIDialogueHandler(), com.runehive.content.ai.LazyAIManager.clearPlayerConsent(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.entity.mob.player.Player.getUsername(), com.runehive.content.dialogue.Expression.HAPPY, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.Mob.locking, logger, npc, com.runehive.content.dialogue.DialogueFactory.onAction(), com.runehive.content.dialogue.DialogueFactory.player, com.runehive.game.world.World.schedule(), com.runehive.content.dialogue.DialogueFactory.sendDialogue(), com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), com.runehive.content.dialogue.DialogueFactory.sendOption(), com.runehive.game.world.entity.mob.Mob.speak(), com.runehive.game.world.entity.mob.Locking.unlock(), and wrapTextToLines().
Referenced by processGandalfAIMessage().
wrapTextToLines()
String[] com.runehive.content.ai.AIDialogueHandler.wrapTextToLines (String text, int maxCharsPerLine) private
Definition at line 291 of file AIDialogueHandler.java.
{
        String[] words = text.split(" ");
        StringBuilder current = new StringBuilder();
        java.util.List<String> lines = new java.util.ArrayList<>();
        for (String word : words) {
            if (current.length() + word.length() + 1 > maxCharsPerLine) {
                if (current.length() > 0) {
                    lines.add(current.toString().trim());
                    current = new StringBuilder(word);
                } else {
                    lines.add(word);
                }
            } else {
                if (current.length() > 0) {
                    current.append(" ");
                }
                current.append(word);
            }
        }
        if (current.length() > 0) {
            lines.add(current.toString().trim());
        }
        return lines.toArray(new String[0]);
    }
Referenced by streamGandalfResponse().
Member Data Documentation
GANDALF_AI_ID
final int com.runehive.content.ai.AIDialogueHandler.GANDALF_AI_ID = 2108 static private
Definition at line 20 of file AIDialogueHandler.java.
Referenced by handleAICommand().
logger
final Logger com.runehive.content.ai.AIDialogueHandler.logger = LoggerFactory.getLogger(AIDialogueHandler.class) static private
Definition at line 19 of file AIDialogueHandler.java.
Referenced by processGandalfAIMessage(), and streamGandalfResponse().
npc
final Npc com.runehive.content.ai.AIDialogueHandler.npc private
Definition at line 22 of file AIDialogueHandler.java.
Referenced by AIDialogueHandler(), findNearbyNpc(), processGandalfAIMessage(), sendDialogues(), and streamGandalfResponse().
The documentation for this class was generated from the following file:
java/com/runehive/content/ai/AIDialogueHandler.java