RuneHive-Game: com.runehive.game.world.object.StaticGameObject Class Reference
com.runehive.game.world.object.StaticGameObject Class Reference
Represents a static game object loaded from the map fs.
Public Member Functions
boolean active ()
Determines if this object is active on the world.
int distance ()
boolean equals (Object obj)
GameObjectDefinition getDefinition ()
Gets the object definition.
ObjectDirection getDirection ()
Gets the rotation.
GenericAttributes getGenericAttributes ()
Gets the generic attributes.
ObjectType getObjectType ()
Gets the object type.
Position getPosition ()
Gets the regional location.
int hashCode ()
int length ()
Gets the length.
void register ()
Registers the game object.
void rotate (ObjectDirection direction)
StaticGameObject (GameObjectDefinition definition, Position position, ObjectType type, ObjectDirection direction)
Creates the game object.
String toString ()
void transform (int id)
void unregister ()
Unregisters the game object.
int width ()
Gets the width.
Public Member Functions inherited from com.runehive.game.world.object.GameObject
default int getId ()
Gets the object id.
default int getInstancedHeight ()
Public Member Functions inherited from com.runehive.game.world.Interactable
default int getHeight ()
default int getX ()
default int getY ()
Private Attributes
GameObjectDefinition definition
The object definition.
ObjectDirection direction
A byte holding the object rotation.
GenericAttributes genericAttributes
The generic attributes.
final Position position
The object position coordinates.
ObjectType type
The object type.
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.Interactable
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Detailed Description
Represents a static game object loaded from the map fs.
Author
Michael | Chex
Definition at line 22 of file StaticGameObject.java.
Constructor & Destructor Documentation
StaticGameObject()
com.runehive.game.world.object.StaticGameObject.StaticGameObject (GameObjectDefinition definition, Position position, ObjectType type, ObjectDirection direction)
Creates the game object.
Definition at line 40 of file StaticGameObject.java.
{
        this.definition = definition;
        this.position = position;
        this.type = type;
        this.direction = direction;
    }
References definition, direction, position, and type.
Referenced by equals().
Member Function Documentation
active()
boolean com.runehive.game.world.object.StaticGameObject.active ()
Determines if this object is active on the world.
Implements com.runehive.game.world.object.GameObject.
Definition at line 145 of file StaticGameObject.java.
{
        return getPosition().getRegion().containsObject(getHeight(), this);
    }
References com.runehive.game.world.region.Region.containsObject(), com.runehive.game.world.Interactable.getHeight(), getPosition(), and com.runehive.game.world.position.Position.getRegion().
distance()
int com.runehive.game.world.object.StaticGameObject.distance ()
Implements com.runehive.game.world.object.GameObject.
Definition at line 82 of file StaticGameObject.java.
{
        return definition.getDistance();
    }
References definition.
equals()
boolean com.runehive.game.world.object.StaticGameObject.equals (Object obj)
Definition at line 155 of file StaticGameObject.java.
{
        if (obj == this) return true;
        if (obj instanceof StaticGameObject) {
            StaticGameObject other = (StaticGameObject) obj;
            return definition == other.definition && position.equals(other.position);
        }
        return false;
    }
References definition, position, and StaticGameObject().
getDefinition()
GameObjectDefinition com.runehive.game.world.object.StaticGameObject.getDefinition ()
Gets the object definition.
Implements com.runehive.game.world.object.GameObject.
Definition at line 56 of file StaticGameObject.java.
{
        return definition;
    }
References definition.
getDirection()
ObjectDirection com.runehive.game.world.object.StaticGameObject.getDirection ()
Gets the rotation.
Implements com.runehive.game.world.object.GameObject.
Definition at line 92 of file StaticGameObject.java.
{
        return direction;
    }
References direction.
Referenced by toString().
getGenericAttributes()
GenericAttributes com.runehive.game.world.object.StaticGameObject.getGenericAttributes ()
Gets the generic attributes.
Implements com.runehive.game.world.object.GameObject.
Definition at line 48 of file StaticGameObject.java.
{
        if (genericAttributes == null) {
            genericAttributes = new GenericAttributes();
        }
        return genericAttributes;
    }
References genericAttributes.
getObjectType()
ObjectType com.runehive.game.world.object.StaticGameObject.getObjectType ()
Gets the object type.
Implements com.runehive.game.world.object.GameObject.
Definition at line 87 of file StaticGameObject.java.
{
        return type;
    }
References type.
Referenced by toString().
getPosition()
Position com.runehive.game.world.object.StaticGameObject.getPosition ()
Gets the regional location.
Implements com.runehive.game.world.object.GameObject.
Definition at line 61 of file StaticGameObject.java.
{
        return position;
    }
References position.
Referenced by active(), register(), toString(), and unregister().
hashCode()
int com.runehive.game.world.object.StaticGameObject.hashCode ()
Definition at line 150 of file StaticGameObject.java.
{
        return Objects.hash(definition.getId(), position);
    }
References definition, and position.
length()
int com.runehive.game.world.object.StaticGameObject.length ()
Gets the length.
Implements com.runehive.game.world.object.GameObject.
Definition at line 74 of file StaticGameObject.java.
{
        if (direction == NORTH || direction == SOUTH) {
            return definition.getWidth();
        }
        return definition.getLength();
    }
References definition, and direction.
Referenced by toString().
register()
void com.runehive.game.world.object.StaticGameObject.register ()
Registers the game object.
Implements com.runehive.game.world.object.GameObject.
Definition at line 97 of file StaticGameObject.java.
{
        Region objectRegion = getPosition().getRegion();
        if (!objectRegion.containsObject(getHeight(), this)) {
            TraversalMap.markObject(objectRegion, this, true, true);
            for (Region region : World.getRegions().getSurroundingRegions(getPosition())) {
                for (Player other : region.getPlayers(getHeight())) {
                    if (other.instance != getInstancedHeight())
                        continue;
                    if (Utility.withinViewingDistance(this, other, Region.VIEW_DISTANCE)) {
                        other.send(new SendAddObject(this));
                    }
                }
            }
        }
    }
References com.runehive.game.world.region.Region.containsObject(), com.runehive.game.world.Interactable.getHeight(), com.runehive.game.world.object.GameObject.getInstancedHeight(), getPosition(), com.runehive.game.world.position.Position.getRegion(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.region.RegionManager.getSurroundingRegions(), com.runehive.game.world.pathfinding.TraversalMap.markObject(), com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinViewingDistance().
Referenced by rotate(), and transform().
rotate()
void com.runehive.game.world.object.StaticGameObject.rotate (ObjectDirection direction)
Implements com.runehive.game.world.object.GameObject.
Definition at line 138 of file StaticGameObject.java.
{
        unregister();
        this.direction = direction;
        register();
    }
References direction, register(), and unregister().
toString()
String com.runehive.game.world.object.StaticGameObject.toString ()
Definition at line 165 of file StaticGameObject.java.
{
        return String.format("StaticGameObject[id=%s, loc=%s, width=%s, len=%s, rot=%s, type=%s]", getId(), getPosition(), width(), length(), getDirection(), getObjectType());
    }
References getDirection(), com.runehive.game.world.object.GameObject.getId(), getObjectType(), getPosition(), length(), and width().
transform()
void com.runehive.game.world.object.StaticGameObject.transform (int id)
Implements com.runehive.game.world.object.GameObject.
Definition at line 131 of file StaticGameObject.java.
{
        unregister();
        definition = GameObjectDefinition.forId(id);
        register();
    }
References definition, com.runehive.game.world.object.GameObjectDefinition.forId(), register(), and unregister().
unregister()
void com.runehive.game.world.object.StaticGameObject.unregister ()
Unregisters the game object.
Implements com.runehive.game.world.object.GameObject.
Definition at line 114 of file StaticGameObject.java.
{
        Region objectRegion = getPosition().getRegion();
        if (objectRegion.containsObject(getHeight(), this)) {
            TraversalMap.markObject(objectRegion, this, false, true);
            for (Region region : World.getRegions().getSurroundingRegions(getPosition())) {
                for (Player other : region.getPlayers(getHeight())) {
                    if (other.instance != getInstancedHeight())
                        continue;
                    if (Utility.withinViewingDistance(this, other, Region.VIEW_DISTANCE)) {
                        other.send(new SendRemoveObject(this));
                    }
                }
            }
        }
    }
References com.runehive.game.world.region.Region.containsObject(), com.runehive.game.world.Interactable.getHeight(), com.runehive.game.world.object.GameObject.getInstancedHeight(), getPosition(), com.runehive.game.world.position.Position.getRegion(), com.runehive.game.world.World.getRegions(), com.runehive.game.world.region.RegionManager.getSurroundingRegions(), com.runehive.game.world.pathfinding.TraversalMap.markObject(), com.runehive.game.world.region.Region.VIEW_DISTANCE, and com.runehive.util.Utility.withinViewingDistance().
Referenced by rotate(), and transform().
width()
int com.runehive.game.world.object.StaticGameObject.width ()
Gets the width.
Implements com.runehive.game.world.object.GameObject.
Definition at line 66 of file StaticGameObject.java.
                       {
        if (direction == NORTH || direction == SOUTH) {
            return definition.getLength();
        }
        return definition.getWidth();
    }
References definition, and direction.
Referenced by toString().
Member Data Documentation
definition
GameObjectDefinition com.runehive.game.world.object.StaticGameObject.definition private
The object definition.
Definition at line 25 of file StaticGameObject.java.
Referenced by distance(), equals(), getDefinition(), hashCode(), length(), StaticGameObject(), transform(), and width().
direction
ObjectDirection com.runehive.game.world.object.StaticGameObject.direction private
A byte holding the object rotation.
Definition at line 37 of file StaticGameObject.java.
Referenced by getDirection(), length(), rotate(), StaticGameObject(), and width().
genericAttributes
GenericAttributes com.runehive.game.world.object.StaticGameObject.genericAttributes private
The generic attributes.
Definition at line 28 of file StaticGameObject.java.
Referenced by getGenericAttributes().
position
final Position com.runehive.game.world.object.StaticGameObject.position private
The object position coordinates.
Definition at line 31 of file StaticGameObject.java.
Referenced by equals(), getPosition(), hashCode(), and StaticGameObject().
type
ObjectType com.runehive.game.world.object.StaticGameObject.type private
The object type.
Definition at line 34 of file StaticGameObject.java.
Referenced by getObjectType(), and StaticGameObject().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/object/StaticGameObject.java