RuneHive-Game: com.runehive.game.world.items.containers.ItemContainerAdapter Class Reference
com.runehive.game.world.items.containers.ItemContainerAdapter Class Reference abstract
An adapter for ItemContainerListener that updates Items on a widget whenever items change, and sends the underlying Player a message when the container is full.
Public Member Functions
void bulkItemsUpdated (ItemContainer container)
Fired when an Items are added, removed, or replaced in bulk.
void capacityExceeded (ItemContainer container)
Fired when the capacity of container is exceeded.
abstract String getCapacityExceededMsg ()
abstract int getWidgetId ()
ItemContainerAdapter (Player player)
Creates a new ItemContainerAdapter.
void itemUpdated (ItemContainer container, Optional< Item > oldItem, Optional< Item > newItem, int index, boolean refresh, boolean login)
Fired when an Item is added, removed, or replaced.
Protected Member Functions
void sendItemsToWidget (ItemContainer container)
Queues a message that displays items from an ItemContainer on a widget.
Private Attributes
final Player player
The Player instance.
Detailed Description
An adapter for ItemContainerListener that updates Items on a widget whenever items change, and sends the underlying Player a message when the container is full.
Author
lare96 http://github.org/lare96
Definition at line 14 of file ItemContainerAdapter.java.
Constructor & Destructor Documentation
ItemContainerAdapter()
com.runehive.game.world.items.containers.ItemContainerAdapter.ItemContainerAdapter (Player player)
Creates a new ItemContainerAdapter.
Parameters
player The Player instance.
Definition at line 25 of file ItemContainerAdapter.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
bulkItemsUpdated()
void com.runehive.game.world.items.containers.ItemContainerAdapter.bulkItemsUpdated (ItemContainer container)
Fired when an Items are added, removed, or replaced in bulk.
This is to prevent firing multiple
itemUpdated(ItemContainer, int) events for a single operation.
Parameters
container The ItemContainer firing the randomevent.
Implements com.runehive.game.world.items.containers.ItemContainerListener.
Reimplemented in com.runehive.game.world.items.containers.bank.Bank.BankListener, com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener, and com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.
Definition at line 53 of file ItemContainerAdapter.java.
{
        sendItemsToWidget(container);
    }
References sendItemsToWidget().
capacityExceeded()
void com.runehive.game.world.items.containers.ItemContainerAdapter.capacityExceeded (ItemContainer container)
Fired when the capacity of container is exceeded.
Parameters
container The ItemContainer firing the randomevent.
Implements com.runehive.game.world.items.containers.ItemContainerListener.
Definition at line 58 of file ItemContainerAdapter.java.
{
        player.send(new SendMessage(getCapacityExceededMsg()));
    }
References getCapacityExceededMsg(), and player.
getCapacityExceededMsg()
abstract String com.runehive.game.world.items.containers.ItemContainerAdapter.getCapacityExceededMsg () abstract
Returns
The message sent when the ItemContainer exceeds its capacity.
Reimplemented in com.runehive.game.world.items.containers.bank.Bank.BankListener, com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener, com.runehive.game.world.items.containers.impl.LootingBag.LootingBagListener, com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener, and com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.
Referenced by capacityExceeded().
getWidgetId()
abstract int com.runehive.game.world.items.containers.ItemContainerAdapter.getWidgetId () abstract
Returns
The widget to display items on.
Reimplemented in com.runehive.game.world.items.containers.bank.Bank.BankListener, com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener, com.runehive.game.world.items.containers.impl.LootingBag.LootingBagListener, com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener, and com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.
Referenced by sendItemsToWidget().
itemUpdated()
void com.runehive.game.world.items.containers.ItemContainerAdapter.itemUpdated (ItemContainer container, Optional< Item > oldItem, Optional< Item > newItem, int index, boolean refresh, boolean login)
Fired when an Item is added, removed, or replaced.
Parameters
container The ItemContainer firing the randomevent.
oldItem The old item being removed from this container.
newItem The new item being added to this container.
index The index the update is occurring on.
refresh The condition if we have to refresh this container.
Implements com.runehive.game.world.items.containers.ItemContainerListener.
Reimplemented in com.runehive.game.world.items.containers.bank.Bank.BankListener, com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener, com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener, and com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.
Definition at line 47 of file ItemContainerAdapter.java.
{
        if(refresh)
            sendItemsToWidget(container);
    }
References sendItemsToWidget().
sendItemsToWidget()
void com.runehive.game.world.items.containers.ItemContainerAdapter.sendItemsToWidget (ItemContainer container) protected
Queues a message that displays items from an ItemContainer on a widget.
Definition at line 32 of file ItemContainerAdapter.java.
{
        container.refresh(player, getWidgetId());
    }
References getWidgetId(), player, and com.runehive.game.world.items.containers.ItemContainer.refresh().
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.bulkItemsUpdated(), bulkItemsUpdated(), com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), and itemUpdated().
Member Data Documentation
player
final Player com.runehive.game.world.items.containers.ItemContainerAdapter.player private
The Player instance.
Definition at line 19 of file ItemContainerAdapter.java.
Referenced by com.runehive.game.world.items.containers.bank.Bank.BankListener.BankListener(), capacityExceeded(), com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.EquipmentListener(), com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.InventoryListener(), ItemContainerAdapter(), com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), com.runehive.game.world.items.containers.inventory.Inventory.InventoryListener.itemUpdated(), com.runehive.game.world.items.containers.impl.LootingBag.LootingBagListener.LootingBagListener(), com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.PriceCheckerListener(), and sendItemsToWidget().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/ItemContainerAdapter.java