RuneHive-Game: com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener Class Reference
com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener Class Reference
Public Member Functions
void bulkItemsUpdated (ItemContainer container)
Fired when an Items are added, removed, or replaced in bulk.
String getCapacityExceededMsg ()
int getWidgetId ()
void itemUpdated (ItemContainer container, Optional< Item > oldItem, Optional< Item > newItem, int index, boolean refresh, boolean login)
Fired when an Item is added, removed, or replaced.
Public Member Functions inherited from com.runehive.game.world.items.containers.ItemContainerAdapter
void capacityExceeded (ItemContainer container)
Fired when the capacity of container is exceeded.
ItemContainerAdapter (Player player)
Creates a new ItemContainerAdapter.
Package Functions
PriceCheckerListener ()
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.world.items.containers.ItemContainerAdapter
void sendItemsToWidget (ItemContainer container)
Queues a message that displays items from an ItemContainer on a widget.
Detailed Description
Definition at line 236 of file PriceChecker.java.
Constructor & Destructor Documentation
PriceCheckerListener()
com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.PriceCheckerListener () package
Definition at line 238 of file PriceChecker.java.
{
            super(player);
        }
References com.runehive.game.world.items.containers.ItemContainerAdapter.player.
Member Function Documentation
bulkItemsUpdated()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.bulkItemsUpdated (ItemContainer container)
Fired when an Items are added, removed, or replaced in bulk.
This is to prevent firing multiple
itemUpdated(ItemContainer, int) events for a single operation.
Parameters
container The ItemContainer firing the randomevent.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 257 of file PriceChecker.java.
{
            refresh();
        }
References com.runehive.game.world.items.containers.ItemContainer.ItemContainer(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.refresh().
getCapacityExceededMsg()
String com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.getCapacityExceededMsg ()
Returns
The message sent when the ItemContainer exceeds its capacity.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 248 of file PriceChecker.java.
{
            return "Your price checker is currently full!";
        }
getWidgetId()
int com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.getWidgetId ()
Returns
The widget to display items on.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 243 of file PriceChecker.java.
{
            return 5063;
        }
itemUpdated()
void com.runehive.game.world.items.containers.pricechecker.PriceChecker.PriceCheckerListener.itemUpdated (ItemContainer container, Optional< Item > oldItem, Optional< Item > newItem, int index, boolean refresh, boolean login)
Fired when an Item is added, removed, or replaced.
Parameters
container The ItemContainer firing the randomevent.
oldItem The old item being removed from this container.
newItem The new item being added to this container.
index The index the update is occurring on.
refresh The condition if we have to refresh this container.
Reimplemented from com.runehive.game.world.items.containers.ItemContainerAdapter.
Definition at line 253 of file PriceChecker.java.
{
        }
References com.runehive.game.world.items.containers.ItemContainer.ItemContainer(), and com.runehive.game.world.items.containers.pricechecker.PriceChecker.refresh().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/items/containers/pricechecker/PriceChecker.java