RuneHive-Game: com.runehive.content.activity.impl.duelarena.DuelRules Class Reference
com.runehive.content.activity.impl.duelarena.DuelRules Class Reference
Public Member Functions
void alternate (DuelRule flag)
boolean contains (DuelRule rule)
void flag (DuelRule rule)
EnumSet< DuelRule > getFlags ()
int getValue ()
void reset ()
void unflag (DuelRule rule)
Private Member Functions
void decrementValue (int value)
void incrementValue (int value)
Private Attributes
final EnumSet< DuelRule > flags = EnumSet.noneOf(DuelRule.class)
int value
Detailed Description
Definition at line 6 of file DuelRules.java.
Member Function Documentation
alternate()
void com.runehive.content.activity.impl.duelarena.DuelRules.alternate (DuelRule flag)
Definition at line 43 of file DuelRules.java.
{
        if (flags.contains(flag)) {
            flags.remove(flag);
            if (DuelRule.EQUIPMENT_RULES.contains(flag)) {
                decrementValue(flag.getValue());
            }
        } else {
            flags.add(flag);
            if (DuelRule.EQUIPMENT_RULES.contains(flag)) {
                incrementValue(flag.getValue());
            }
        }
    }
References decrementValue(), com.runehive.content.activity.impl.duelarena.DuelRule.EQUIPMENT_RULES, flag(), flags, and incrementValue().
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.set().
contains()
boolean com.runehive.content.activity.impl.duelarena.DuelRules.contains (DuelRule rule)
Definition at line 61 of file DuelRules.java.
{
        return flags.contains(rule);
    }
References flags.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack(), and com.runehive.content.activity.impl.duelarena.DuelRule.set().
decrementValue()
void com.runehive.content.activity.impl.duelarena.DuelRules.decrementValue (int value) private
Definition at line 16 of file DuelRules.java.
{
        this.value -= value;
        if (this.value < 0) {
            this.value = 0;
        }
    }
References value.
Referenced by alternate(), and unflag().
flag()
void com.runehive.content.activity.impl.duelarena.DuelRules.flag (DuelRule rule)
Definition at line 23 of file DuelRules.java.
{
        if (flags.contains(rule)) {
            return;
        }
        flags.add(rule);
        if (DuelRule.EQUIPMENT_RULES.contains(rule)) {
            incrementValue(rule.getValue());
        }
    }
References com.runehive.content.activity.impl.duelarena.DuelRule.EQUIPMENT_RULES, flags, com.runehive.content.activity.impl.duelarena.DuelRule.getValue(), and incrementValue().
Referenced by alternate().
getFlags()
EnumSet< DuelRule > com.runehive.content.activity.impl.duelarena.DuelRules.getFlags ()
Definition at line 70 of file DuelRules.java.
{
        return flags.clone();
    }
References flags.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired().
getValue()
int com.runehive.content.activity.impl.duelarena.DuelRules.getValue ()
Definition at line 57 of file DuelRules.java.
{
        return value;
    }
References value.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRule.set().
incrementValue()
void com.runehive.content.activity.impl.duelarena.DuelRules.incrementValue (int value) private
Definition at line 12 of file DuelRules.java.
{
        this.value += value;
    }
References value.
Referenced by alternate(), and flag().
reset()
void com.runehive.content.activity.impl.duelarena.DuelRules.reset ()
Definition at line 65 of file DuelRules.java.
{
        flags.clear();
        value = 0;
    }
References flags, and value.
unflag()
void com.runehive.content.activity.impl.duelarena.DuelRules.unflag (DuelRule rule)
Definition at line 33 of file DuelRules.java.
{
        if (!flags.contains(rule)) {
            return;
        }
        flags.remove(rule);
        if (DuelRule.EQUIPMENT_RULES.contains(rule)) {
            decrementValue(rule.getValue());
        }
    }
References decrementValue(), com.runehive.content.activity.impl.duelarena.DuelRule.EQUIPMENT_RULES, flags, and com.runehive.content.activity.impl.duelarena.DuelRule.getValue().
Member Data Documentation
flags
final EnumSet<DuelRule> com.runehive.content.activity.impl.duelarena.DuelRules.flags = EnumSet.noneOf(DuelRule.class) private
Definition at line 8 of file DuelRules.java.
Referenced by alternate(), contains(), flag(), getFlags(), reset(), and unflag().
value
int com.runehive.content.activity.impl.duelarena.DuelRules.value private
Definition at line 10 of file DuelRules.java.
Referenced by decrementValue(), getValue(), incrementValue(), and reset().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/duelarena/DuelRules.java