RuneHive-Game: com.runehive.content.shootingstar.ShootingStar Class Reference
com.runehive.content.shootingstar.ShootingStar Class Reference
Static Public Member Functions
static void init ()
Handles initializing the shooting stars event.
static void mine (Player player, GameObject o)
Handles the mine option of the shooting star.
static void prospect (Player player)
Handles prospecting the shooting star.
Static Public Attributes
static ShootingStarData shootingStarData
The current data of the shooting star.
static boolean starHasBeenFound = false
Checks if the star has been found before.
static int starTick = 30
Ticks till the next shooting star will spawn.
Static Private Attributes
static final Logger logger = LogManager.getLogger(ShootingStar.class)
Detailed Description
Definition at line 13 of file ShootingStar.java.
Member Function Documentation
init()
void com.runehive.content.shootingstar.ShootingStar.init () static
Handles initializing the shooting stars event.
Definition at line 92 of file ShootingStar.java.
{
        logger.info("Loaded Shooting Stars event.");
        World.schedule(new Task(1) {
            @Override
            protected void execute() {
                starTick--;
                if(starTick <= 0) {
                    if(shootingStarData != null) {
                        shootingStarData.destruct();
                        starHasBeenFound = false;
                    }
                    shootingStarData = new ShootingStarData();
                    World.sendMessage("@red@A shooting star has just crashed " + shootingStarData.getHint() +" " + shootingStarData.getLocationName() + "!");
                    // DiscordPlugin.sendSimpleMessage("A shooting star has just crashed " + shootingStarData.getHint() +" " + shootingStarData.getLocationName() + "!");
                    //4 Hours in ticks
                    starTick = 24_000;
                }
            }
            @Override
            protected void onCancel(boolean logout) {
            }
        });
    }
References logger, com.runehive.game.world.World.schedule(), com.runehive.game.world.World.sendMessage(), shootingStarData, starHasBeenFound, and starTick.
mine()
void com.runehive.content.shootingstar.ShootingStar.mine (Player player, GameObject o) static
Handles the mine option of the shooting star.
Parameters
player
Definition at line 36 of file ShootingStar.java.
{
        if(!starHasBeenFound) {
            starHasBeenFound = true;
            player.dialogueFactory.sendStatement("Congratulations! You were the first person to find this star!").execute();
            player.skills.addExperience(14, 10000);
            return;
        }
        PickaxeData pickaxe = PickaxeData.getBestPickaxe(player).orElse(null);
        if(pickaxe == null) {
            player.message("You don't have a pickaxe.");
            return;
        }
        if (!player.skills.get(Skill.MINING).reqLevel(pickaxe.level)) {
            player.message("You need a level of " + pickaxe.level + " to use this pickaxe!");
            return;
        }
        if(!player.skills.get(Skill.MINING).reqLevel(shootingStarData.getMiningLevel())) {
            player.dialogueFactory.sendStatement("You need a Mining level of " + shootingStarData.getMiningLevel() + " to mine here.").execute();
            return;
        }
        if(!player.inventory.hasCapacityFor(new Item(25527))) {
            player.message("Not enough space in your inventory.");
            return;
        }
        player.message("You swing your pick at the rock.");
        player.animate(pickaxe.animation);
        player.action.execute(new ShootingStarAction(player, pickaxe, o));
        player.skills.get(Skill.MINING).setDoingSkill(true);
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.content.skill.impl.mining.PickaxeData.animation, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.action.ActionManager.execute(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.content.skill.impl.mining.PickaxeData.getBestPickaxe(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skill.impl.mining.PickaxeData.level, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.skill.Skill.MINING, com.runehive.game.world.entity.skill.Skill.reqLevel(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.game.world.entity.skill.Skill.setDoingSkill(), shootingStarData, com.runehive.game.world.entity.mob.Mob.skills, and starHasBeenFound.
prospect()
void com.runehive.content.shootingstar.ShootingStar.prospect (Player player) static
Handles prospecting the shooting star.
Parameters
player
Definition at line 78 of file ShootingStar.java.
{
        if(!starHasBeenFound) {
            starHasBeenFound = true;
            player.dialogueFactory.sendStatement("Congratulations! You were the first person to find this star!", "You have been granted 10,000 mining xp!").execute();
            player.skills.addExperience(14, 10000);
            return;
        }
        player.dialogueFactory.sendStatement("This is a size-"+(shootingStarData.starLevel + 1)+" star. A Mining level of at least "+shootingStarData.getMiningLevel()+" is required to", "mine this layer. It has been mined "+shootingStarData.getPercentage()+"% of the way to the next layer.").execute();
    }
References com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), shootingStarData, com.runehive.game.world.entity.mob.Mob.skills, and starHasBeenFound.
Member Data Documentation
logger
final Logger com.runehive.content.shootingstar.ShootingStar.logger = LogManager.getLogger(ShootingStar.class) static private
Definition at line 15 of file ShootingStar.java.
Referenced by init().
shootingStarData
ShootingStarData com.runehive.content.shootingstar.ShootingStar.shootingStarData static
The current data of the shooting star.
Definition at line 25 of file ShootingStar.java.
Referenced by init(), mine(), com.runehive.content.shootingstar.ShootingStarAction.mine(), and prospect().
starHasBeenFound
boolean com.runehive.content.shootingstar.ShootingStar.starHasBeenFound = false static
Checks if the star has been found before.
Definition at line 20 of file ShootingStar.java.
Referenced by init(), mine(), and prospect().
starTick
int com.runehive.content.shootingstar.ShootingStar.starTick = 30 static
Ticks till the next shooting star will spawn.
Definition at line 30 of file ShootingStar.java.
Referenced by init().
The documentation for this class was generated from the following file:
java/com/runehive/content/shootingstar/ShootingStar.java