RuneHive-Game: com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel Class Reference
com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel Class Reference
Public Member Functions
void update ()
Public Member Functions inherited from com.runehive.content.activity.panel.Activity_Panel
void close ()
String getFooter ()
String getHeader ()
Item getItem ()
Player getPlayer ()
int getProgress ()
String[] getText ()
void open ()
void setFooter (String footer)
void setItem (Item item)
void setProgress (int progress)
Private Member Functions
PestControlPanel (Player player, PestControlNode node)
Private Attributes
final PestControlNode node
Additional Inherited Members
Protected Member Functions inherited from com.runehive.content.activity.panel.Activity_Panel
Activity_Panel (Player player, String header)
void set (int index, String string)
Detailed Description
Definition at line 369 of file PestControlGame.java.
Constructor & Destructor Documentation
PestControlPanel()
com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.PestControlPanel (Player player, PestControlNode node) private
Definition at line 372 of file PestControlGame.java.
{
            super(player, "Pest Control");
            this.node = node;
            node.setPanel(this);
        }
References node, and com.runehive.content.activity.panel.Activity_Panel.player.
Member Function Documentation
update()
void com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.update ()
Definition at line 378 of file PestControlGame.java.
{
            if (inLobby()) {
                set(0, "Next Departure: <col=FF5500>" + Utility.getTime(getTicks()) + "</col>");
                set(1, "Players Ready: <col=FF5500>" + getActiveSize() + "</col>");
                set(2, "(Need <col=FF5500>" + manager.getMinimumRequired() + "</col> to " + manager.getPlayerCapacity() + " players)");
                set(3, "Points: <col=FF5500>" + node.player.pestPoints + "</col>");
                setFooter("Players Ready:");
                setProgress((int) Utility.getPercentageAmount(getActiveSize(), manager.getPlayerCapacity()));
            } else {
                set(0, "Time remaining: <col=FF5500>" + Utility.getTime(getTicks()) + "</col>");
                set(1, "Knight's health: <col=FF5500>" + voidKnight.getCurrentHealth() + "</col>");
                set(2, "Damage: <col=FF5500>" + node.damage + "</col>");
                int dead = 0;
                for (int index = 0; index <= 3; index++) {
                    String value = "dead";
                    Portal portal = portals[index];
                    if (portal.getCurrentHealth() > 0) {
                        value = String.valueOf(portal.getCurrentHealth());
                    } else {
                        dead++;
                    }
                    set(3 + index, PORTAL_NAMES[index] + ": <col=FF5500>" + value + "</col>");
                }
                setFooter("Minigame Completion:");
                setProgress((int) Utility.getPercentageAmount(dead, 4));
            }
            setItem(new Item(11666));
        }
References com.runehive.content.activity.GroupActivity.getActiveSize(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.util.Utility.getPercentageAmount(), com.runehive.content.activity.Activity.getTicks(), com.runehive.util.Utility.getTime(), com.runehive.content.activity.lobby.LobbyNode.inLobby(), com.runehive.content.activity.lobby.LobbyNode.manager, com.runehive.content.activity.impl.pestcontrol.PestControlGame.PORTAL_NAMES, com.runehive.content.activity.impl.pestcontrol.PestControlGame.portals, com.runehive.content.activity.panel.Activity_Panel.setFooter(), com.runehive.content.activity.panel.Activity_Panel.setItem(), com.runehive.content.activity.panel.Activity_Panel.setProgress(), and com.runehive.content.activity.impl.pestcontrol.PestControlGame.voidKnight.
Member Data Documentation
node
final PestControlNode com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlPanel.node private
Definition at line 370 of file PestControlGame.java.
Referenced by PestControlPanel().
The documentation for this class was generated from the following file:
java/com/runehive/content/activity/impl/pestcontrol/PestControlGame.java