RuneHive-Game: com.runehive.game.world.pathfinding.path.SimplePathChecker Class Reference
com.runehive.game.world.pathfinding.path.SimplePathChecker Class Reference
Represents a PathFinder which is meant to be used to check projectiles passage in a straight line.
Public Member Functions
Path find (Mob source, Position end, int targetWidth, int targetLength)
Finds a valid path from the origin Position to the target one.
Public Member Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
final Path find (Mob origin, Interactable target)
final Path find (Mob origin, Position target)
Static Public Member Functions
static boolean checkLine (Interactable source, Interactable target)
static boolean checkLine (Interactable source, Position target)
static boolean checkProjectile (Interactable source, Interactable target)
Private Member Functions
boolean check (Position start, Position end, int size, boolean projectile)
Determines if the projectile can reach it's destination.
Static Private Attributes
static final SimplePathChecker SIMPLE_PATH_CHECKER = new SimplePathChecker()
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
boolean projectileCheck (Position current, Position going)
Returns whether or not a Position shooting projectile to another Position would lead to is traversable.
boolean traversable (Position current, int size, Direction... directions)
Returns whether or not a Position walking one step in any of the specified Directions would lead to is traversable.
Package Functions inherited from com.runehive.game.world.pathfinding.path.PathFinder
boolean traversable (Position current, Position going, int size)
Returns whether or not a Position is traversable to the direction of another Position.
Detailed Description
Represents a PathFinder which is meant to be used to check projectiles passage in a straight line.
Author
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Michael | Chex (improvements to "check" method)
Definition at line 15 of file SimplePathChecker.java.
Member Function Documentation
check()
boolean com.runehive.game.world.pathfinding.path.SimplePathChecker.check (Position start, Position end, int size, boolean projectile) private
Determines if the projectile can reach it's destination.
Parameters
start The projectile's starting Position.
end The projectile's ending Position.
projectile The condition if the check is meant for projectiles.
Returns
true if the projectile can reach it's destination,
false otherwise.
Definition at line 47 of file SimplePathChecker.java.
{
        int dx = end.getX() - start.getX();
        int dy = end.getY() - start.getY();
        int xSignum = Integer.signum(dx);
        int ySignum = Integer.signum(dy);
        int height = start.getHeight();
        int nextX = start.getX();
        int nextY = start.getY();
        int currentX = nextX;
        int currentY = nextY;
        while (true) {
            if (dx == 0) {
                nextY += ySignum;
            } else if (dy == 0) {
                nextX += xSignum;
            } else if (nextX != end.getX()) {
                int pointSlope = (nextX + xSignum - start.getX()) * dy / dx + start.getY();
                if (Math.abs(pointSlope - currentY) > 1) {
                    nextY += ySignum;
                } else {
                    nextX += xSignum;
                    nextY = pointSlope;
                }
            }
            Position current = new Position(currentX, currentY, height);
            Position next = new Position(nextX, nextY, height);
            if (projectile && !projectileCheck(current, next)) {
                return false;
            }
            if (!projectile && !traversable(current, next, size)) {
                return false;
            }
            if (nextX == end.getX() && nextY == end.getY()) {
                break;
            }
            currentX = nextX;
            currentY = nextY;
        }
        return true;
    }
References com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), com.runehive.game.world.pathfinding.path.PathFinder.projectileCheck(), and com.runehive.game.world.pathfinding.path.PathFinder.traversable().
checkLine() [1/2]
boolean com.runehive.game.world.pathfinding.path.SimplePathChecker.checkLine (Interactable source, Interactable target) static
Definition at line 24 of file SimplePathChecker.java.
{
        Position targetPosition = Utility.findBestInside(source, target);
        return SIMPLE_PATH_CHECKER.check(source.getPosition(), targetPosition, source.width(), false);
    }
References com.runehive.util.Utility.findBestInside(), com.runehive.game.world.Interactable.getPosition(), SIMPLE_PATH_CHECKER, and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Derwen.LightingRain.start(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Justiciar.LightingRain.start(), and com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.withinDistance().
checkLine() [2/2]
boolean com.runehive.game.world.pathfinding.path.SimplePathChecker.checkLine (Interactable source, Position target) static
Definition at line 29 of file SimplePathChecker.java.
{
        return SIMPLE_PATH_CHECKER.check(source.getPosition(), target, source.width(), false);
    }
References com.runehive.game.world.Interactable.getPosition(), SIMPLE_PATH_CHECKER, and com.runehive.game.world.Interactable.width().
checkProjectile()
boolean com.runehive.game.world.pathfinding.path.SimplePathChecker.checkProjectile (Interactable source, Interactable target) static
Definition at line 33 of file SimplePathChecker.java.
{
        Position targetPosition = Utility.findBestInside(source, target);
        return SIMPLE_PATH_CHECKER.check(source.getPosition(), targetPosition, Math.max(1, Math.max(source.width(), source.length())), true);
    }
References com.runehive.util.Utility.findBestInside(), com.runehive.game.world.Interactable.getPosition(), com.runehive.game.world.Interactable.length(), SIMPLE_PATH_CHECKER, and com.runehive.game.world.Interactable.width().
Referenced by com.runehive.game.world.entity.combat.CombatTarget.compare(), com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >.withinDistance(), com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.withinDistance(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Zulrah.MeleeAttack.withinDistance().
find()
Path com.runehive.game.world.pathfinding.path.SimplePathChecker.find (Mob source, Position target, int targetWidth, int targetLength)
Finds a valid path from the origin Position to the target one.
Parameters
source
target The target Position.
Returns
The path containing the Positions to go through.
Reimplemented from com.runehive.game.world.pathfinding.path.PathFinder.
Definition at line 19 of file SimplePathChecker.java.
{
        /* empty path */
        return new Path(null);
    }
Member Data Documentation
SIMPLE_PATH_CHECKER
final SimplePathChecker com.runehive.game.world.pathfinding.path.SimplePathChecker.SIMPLE_PATH_CHECKER = new SimplePathChecker() static private
Definition at line 16 of file SimplePathChecker.java.
Referenced by checkLine(), checkLine(), and checkProjectile().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/pathfinding/path/SimplePathChecker.java