RuneHive-Game: com.runehive.content.skill.impl.fletching.Fletching Class Reference
com.runehive.content.skill.impl.fletching.Fletching Class Reference
Handles the fletching skill.
Public Member Functions
boolean fletch (Player player, int index, int amount)
Fletching (int level, double experience)
boolean start (Player player, Fletchable fletchable, int index, int amount)
Public Member Functions inherited from com.runehive.game.world.entity.skill.Skill
double addExperience (double amount)
Adds experiences to this skill by the given amount.
void addLevel (int amount)
Adds levels to this skill by the given amount.
void divideExperience (double amount)
Divides the current experience of this skill by a given amount.
void divideLevel (double amount)
Divides the current level of this skill by a given amount.
double getExperience ()
Gets the skill experience.
int getLevel ()
Gets the current skill level.
int getMaxLevel ()
Gets the maximum skill level.
int getRoundedExperience ()
Gets the floor experience.
int getSkill ()
Gets the skill id.
boolean isDoingSkill ()
double modifyExperience (Function< Double, Double > function)
Modifies the current experience with a given function.
double modifyExperience (Function< Double, Double > function, int lowerBounds, int upperBounds)
Modifies the current experience with a given function.
void modifyLevel (Function< Integer, Integer > function)
Modifies the current level with a given function.
void modifyLevel (Function< Integer, Integer > function, int lowerBounds, int upperBounds)
Modifies the current level with a given function.
void multiplyExperience (double amount)
Multiplies the current experience of this skill by a given amount.
void multiplyLevel (double amount)
Multiplies the current level of this skill by a given amount.
boolean onEvent (Player player, InteractionEvent interactionEvent)
void removeExperience (double amount)
Removes experiences from this skill by the given amount.
void removeLevel (int amount)
Removes levels from this skill by the given amount.
boolean reqLevel (int level)
Determines if your level is greater than or equal to level.
void setDoingSkill (boolean doingSkill)
void setExperience (double experience)
Sets the experience for this skill.
void setLevel (int level)
Sets the level for this skill.
void setMaxLevel (int maxLevel)
Sets the maximum level for this skill.
Skill (int skill, int level, double experience)
Constructs a new Skill.
String toString ()
Static Public Member Functions
static void addFletchable (Fletchable fletchable)
Static Public Member Functions inherited from com.runehive.game.world.entity.skill.Skill
static Function< Integer, Integer > add (int amount)
Creates a function that adds a number by an amount.
static Function< Integer, Integer > divide (double amount)
Creates a function that divides a number by an amount.
static final int getExperienceForLevel (int level)
Gets the experience for a given level.
static final byte getLevelForExperience (double experience)
Gets the level for a given experience amount.
static String getName (int skill)
Gets the name for a skill id.
static Function< Integer, Integer > multiply (double amount)
Creates a function that multiplies a number by an amount.
static Function< Integer, Integer > subtract (int amount)
Creates a function that subtracts a number by an amount.
Protected Member Functions
boolean clickButton (Player player, ClickButtonInteractionEvent event)
double modifier ()
boolean useItem (Player player, ItemOnItemInteractionEvent event)
Protected Member Functions inherited from com.runehive.game.world.entity.skill.Skill
boolean clickItem (Player player, ItemInteractionEvent event)
boolean clickNpc (Player player, NpcInteractionEvent event)
boolean clickObject (Player player, ObjectInteractionEvent event)
boolean itemContainerAction (Player player, ItemContainerInteractionEvent event)
boolean useItem (Player player, ItemOnObjectInteractionEvent event)
Private Member Functions
Action< Player > fletch (Player player, Fletchable fletchable, FletchableItem item, int amount)
Fletchable getFletchable (int use, int with)
Static Private Attributes
static final String FLETCHABLE_KEY = "FLETCHABLE_KEY"
static final HashMap< Integer, Fletchable > FLETCHABLES = new HashMap<>()
static final Logger logger = LogManager.getLogger(Fletching.class)
Additional Inherited Members
Public Attributes inherited from com.runehive.game.world.entity.skill.Skill
transient final Stopwatch stopwatch = Stopwatch.start()
Static Public Attributes inherited from com.runehive.game.world.entity.skill.Skill
static final int AGILITY = 16
The agility skill id.
static final int ATTACK = 0
The attack skill id.
static final int CONSTRUCTION = 21
The construction skill id.
static final int COOKING = 7
The cooking skill id.
static final int CRAFTING = 12
The crafting skill id.
static final int DEFENCE = 1
The defence skill id.
static final int FARMING = 19
The farming skill id.
static final int FIREMAKING = 11
The firemaking skill id.
static final int FISHING = 10
The fishing skill id.
static final int FLETCHING = 9
The fletching skill id.
static final int HERBLORE = 15
The herblore skill id.
static final int HITPOINTS = 3
The hitpoints skill id.
static final int HUNTER = 22
The hunter skill id.
static final int[][] INTERFACE_DATA
Skill tab string data.
static final int MAGIC = 6
The magic skill id.
static final int MINING = 14
The mining skill id.
static final int PRAYER = 5
The prayer skill id.
static final int RANGED = 4
The ranged skill id.
static final int RUNECRAFTING = 20
The runecrafting skill id.
static final int SKILL_COUNT = 23
The amount of available skills.
static final int SLAYER = 18
The slayer skill id.
static final int SMITHING = 13
The smithing skill id.
static final int STRENGTH = 2
The strength skill id.
static final int THIEVING = 17
The thieving skill id.
static final int TOTAL_SKILL_LEVEL = 99 * SKILL_COUNT
The total skill amount.
static final int WOODCUTTING = 8
The woodcutting skill id.
Detailed Description
Handles the fletching skill.
Author
Daniel
Definition at line 34 of file Fletching.java.
Constructor & Destructor Documentation
Fletching()
com.runehive.content.skill.impl.fletching.Fletching.Fletching (int level, double experience)
Definition at line 42 of file Fletching.java.
{
        super(Skill.FLETCHING, level, experience);
    }
References com.runehive.game.world.entity.skill.Skill.experience, com.runehive.game.world.entity.skill.Skill.level, and com.runehive.game.world.entity.skill.Skill.Skill().
Member Function Documentation
addFletchable()
void com.runehive.content.skill.impl.fletching.Fletching.addFletchable (Fletchable fletchable) static
Definition at line 46 of file Fletching.java.
{
        if (FLETCHABLES.put(fletchable.getWith().getId(), fletchable) != null) {
            System.out.println("[Fletching] Conflicting item values: " + fletchable.getWith().getId() + " Type: " + fletchable.getClass().getSimpleName());
        }
    }
References FLETCHABLES, com.runehive.game.world.items.Item.getId(), and com.runehive.content.skill.impl.fletching.Fletchable.getWith().
Referenced by com.runehive.content.skill.impl.fletching.impl.Arrow.load(), com.runehive.content.skill.impl.fletching.impl.Battlestaff.load(), com.runehive.content.skill.impl.fletching.impl.Bolt.load(), com.runehive.content.skill.impl.fletching.impl.Carvable.load(), com.runehive.content.skill.impl.fletching.impl.Crossbow.load(), com.runehive.content.skill.impl.fletching.impl.Featherable.load(), and com.runehive.content.skill.impl.fletching.impl.Stringable.load().
clickButton()
boolean com.runehive.content.skill.impl.fletching.Fletching.clickButton (Player player, ClickButtonInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 135 of file Fletching.java.
{
        if (player.attributes.get(FLETCHABLE_KEY, Fletchable.class) == null) {
            return false;
        }
        Fletchable fletchable = player.attributes.get(FLETCHABLE_KEY, Fletchable.class);
        int button = event.getButton();
        switch (button) {
        /* Option 1 - Make all */
            case 1747:
                start(player, fletchable, 0, 15);
                return true;
        /* Option 1 - Make 1 */
            case 2799:
            case 8909:
            case 8874:
            case 8889:
                start(player, fletchable, 0, 1);
                return true;
        /* Option 1 - Make 5 */
            case 2798:
            case 8908:
            case 8873:
            case 8888:
                start(player, fletchable, 0, 5);
                return true;
        /* Option 1 - Make 10 */
            case 8907:
            case 8872:
            case 8887:
                start(player, fletchable, 0, 10);
                return true;
                //TODO: Make X limited to 150.
        /* Option 1 - Make X */
            case 1748:
            case 8906:
            case 8871:
            case 8886:
            case 6212:
                try {
                    player.send(new SendInputAmount("Enter amount", 3, input ->
                            start(player, fletchable, 0, Integer.parseInt(input))));
                } catch (Exception ex) {
                    logger.error(String.format("player=%s error fletching option1: make-x", player.getName()), ex);
                }
                return true;
        /* Option 2 - Make 1 */
            case 8913:
            case 8878:
            case 8893:
                start(player, fletchable, 1, 1);
                return true;
        /* Option 2 - Make 5 */
            case 8912:
            case 8877:
            case 8892:
                start(player, fletchable, 1, 5);
                return true;
        /* Option 2 - Make 10 */
            case 8911:
            case 8876:
            case 8891:
                start(player, fletchable, 1, 10);
                return true;
        /* Option 2 - Make X */
            case 8910:
            case 8875:
            case 8890:
                try {
                    player.send(new SendInputAmount("Enter amount", 2, input -> start(player, fletchable, 1, Integer.parseInt(input))));
                } catch (Exception ex) {
                    logger.error(String.format("player=%s error fletching option2: make-x", player.getName()), ex);
                }
                return true;
        /* Option 3 - Make 1 */
            case 8917:
            case 8897:
                start(player, fletchable, 2, 1);
                return true;
        /* Option 3 - Make 5 */
            case 8916:
            case 8896:
                start(player, fletchable, 2, 5);
                return true;
        /* Option 3 - Make 10 */
            case 8915:
            case 8895:
                start(player, fletchable, 2, 10);
                return true;
        /* Option 3 - Make X */
            case 8914:
            case 8894:
                try {
                    player.send(new SendInputAmount("Enter amount", 2, input -> start(player, fletchable, 2, Integer.parseInt(input))));
                } catch (Exception ex) {
                    logger.error(String.format("player=%s error fletching option3: make-x", player.getName()), ex);
                }
                return true;
        /* Option 4 - Make 1 */
            case 8921:
                start(player, fletchable, 3, 1);
                return true;
        /* Option 4 - Make 5 */
            case 8920:
                start(player, fletchable, 3, 5);
                return true;
        /* Option 4 - Make 10 */
            case 8919:
                start(player, fletchable, 3, 10);
                return true;
        /* Option 4 - Make X */
            case 8918:
                try {
                    player.send(new SendInputAmount("Enter amount", 2, input -> start(player, fletchable, 3, Integer.parseInt(input))));
                } catch (Exception ex) {
                    logger.error(String.format("player=%s error fletching option3: make-x", player.getName()), ex);
                }
                return true;
            default:
                return false;
        }
    }
References com.runehive.game.world.entity.mob.Mob.attributes, FLETCHABLE_KEY, com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.world.entity.mob.player.Player.getName(), logger, com.runehive.game.world.entity.mob.player.Player.send(), and start().
fletch() [1/2]
Action< Player > com.runehive.content.skill.impl.fletching.Fletching.fletch (Player player, Fletchable fletchable, FletchableItem item, int amount) private
Definition at line 351 of file Fletching.java.
{
        return new Action<Player>(player, 2, true) {
            int iterations = 0;
            @Override
            public void execute() {
                ++iterations;
                player.animate(new Animation(fletchable.getAnimation()));
                player.graphic(new Graphic(fletchable.getGraphics()));
                final boolean saveMaterial = SkillCape.isEquipped(player, SkillCape.FLETCHING) && Utility.random(1, 3) == 1;
                if (fletchable == Carvable.AMETHYST) {
                    player.skills.addExperience(Skill.CRAFTING, item.getExperience() * modifier());
                } else {
                    player.skills.addExperience(Skill.FLETCHING, item.getExperience() * modifier());
                }
                if (!saveMaterial) {
                    player.inventory.removeAll(fletchable.getIngredients());
                }
                player.inventory.addOrDrop(item.getProduct());
                player.playerAssistant.activateSkilling(1);
                RandomEventHandler.trigger(player);
                if (fletchable.getProductionMessage() != null) {
                    player.send(new SendMessage(fletchable.getProductionMessage()));
                }
                if (fletchable == Stringable.MAGIC_SHORTBOWS) {
                    getMob().forClan(channel -> channel.activateTask(ClanTaskKey.MAGIC_SHORTBOW, getMob().getName()));
                } else if (fletchable == Stringable.YEW_SHORTBOWS) {
                    getMob().forClan(channel -> channel.activateTask(ClanTaskKey.YEW_SHORTBOW, getMob().getName()));
                } else if (fletchable instanceof Arrow) {
                    AchievementHandler.activate(player, AchievementKey.FLETCHING);
                }
                if (iterations == amount || iterations > 28 || !(player.inventory.containsAll(fletchable.getIngredients()))) {
                    cancel();
                    if (!(player.inventory.containsAll(fletchable.getIngredients()))) {
                        player.send(new SendMessage("<col=369>You have run out of materials."));
                    }
                    return;
                }
            }
            @Override
            public String getName() {
                return "Fletching";
            }
            @Override
            public boolean prioritized() {
                return false;
            }
            @Override
            public WalkablePolicy getWalkablePolicy() {
                return WalkablePolicy.NON_WALKABLE;
            }
        };
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.content.skill.impl.fletching.impl.Carvable.AMETHYST, com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.content.achievement.AchievementKey.FLETCHING, com.runehive.content.skillcape.SkillCape.FLETCHING, com.runehive.content.skill.impl.fletching.Fletchable.getAnimation(), com.runehive.content.skill.impl.fletching.FletchableItem.getExperience(), com.runehive.content.skill.impl.fletching.Fletchable.getGraphics(), com.runehive.content.skill.impl.fletching.Fletchable.getIngredients(), com.runehive.game.world.entity.skill.Skill.getName(), com.runehive.content.skill.impl.fletching.FletchableItem.getProduct(), com.runehive.content.skill.impl.fletching.Fletchable.getProductionMessage(), com.runehive.game.world.entity.mob.Mob.graphic, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.content.skillcape.SkillCape.isEquipped(), com.runehive.content.clanchannel.content.ClanTaskKey.MAGIC_SHORTBOW, com.runehive.content.skill.impl.fletching.impl.Stringable.MAGIC_SHORTBOWS, modifier(), com.runehive.game.action.policy.WalkablePolicy.NON_WALKABLE, com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.util.Utility.random(), com.runehive.game.world.items.containers.ItemContainer.removeAll(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.skill.Skill.Skill(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.content.activity.randomevent.RandomEventHandler.trigger(), com.runehive.content.clanchannel.content.ClanTaskKey.YEW_SHORTBOW, and com.runehive.content.skill.impl.fletching.impl.Stringable.YEW_SHORTBOWS.
fletch() [2/2]
boolean com.runehive.content.skill.impl.fletching.Fletching.fletch (Player player, int index, int amount)
Definition at line 280 of file Fletching.java.
{
        Fletchable fletchable = player.attributes.get(FLETCHABLE_KEY);
        if (fletchable == null) {
            return false;
        }
        return start(player, fletchable, index, amount);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, FLETCHABLE_KEY, com.runehive.util.generic.GenericAttributes.get(), and start().
Referenced by start().
getFletchable()
Fletchable com.runehive.content.skill.impl.fletching.Fletching.getFletchable (int use, int with) private
Definition at line 52 of file Fletching.java.
{
        return FLETCHABLES.getOrDefault(use, FLETCHABLES.get(with));
    }
References FLETCHABLES.
Referenced by useItem().
modifier()
double com.runehive.content.skill.impl.fletching.Fletching.modifier () protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 57 of file Fletching.java.
{
        return Config.FLETCHING_MODIFICATION;
    }
References com.runehive.Config.FLETCHING_MODIFICATION.
Referenced by fletch().
start()
boolean com.runehive.content.skill.impl.fletching.Fletching.start (Player player, Fletchable fletchable, int index, int amount)
Definition at line 291 of file Fletching.java.
{
        if (fletchable == null) {
            return false;
        }
        player.attributes.remove(FLETCHABLE_KEY);
        FletchableItem item = fletchable.getFletchableItems()[index];
        player.interfaceManager.close();
        if (player.skills.getLevel(Skill.FLETCHING) < item.getLevel()) {
            player.dialogueFactory.sendStatement("<col=369>You need a Fletching level of " + item.getLevel() + " to do that.").execute();
            return true;
        }
        if (!(player.inventory.containsAll(fletchable.getIngredients()))) {
            String firstName = fletchable.getUse().getName().toLowerCase();
            String secondName = fletchable.getWith().getName().toLowerCase();
            if (fletchable.getUse().getAmount() > 1 && !firstName.endsWith("s")) {
                firstName = firstName.concat("s");
            }
            if (fletchable.getWith().getAmount() > 1 && !secondName.endsWith("s")) {
                secondName = secondName.concat("s");
            }
            if (fletchable.getUse().getAmount() == 1 && firstName.endsWith("s")) {
                firstName = firstName.substring(0, firstName.length() - 1);
            }
            if (fletchable.getWith().getAmount() == 1 && secondName.endsWith("s")) {
                secondName = secondName.substring(0, secondName.length() - 1);
            }
            final String firstAmount;
            if (fletchable.getUse().getAmount() == 1) {
                firstAmount = Utility.getAOrAn(fletchable.getUse().getName());
            } else {
                firstAmount = String.valueOf(fletchable.getUse().getAmount());
            }
            final String secondAmount;
            if (fletchable.getWith().getAmount() == 1) {
                secondAmount = Utility.getAOrAn(fletchable.getWith().getName());
            } else {
                secondAmount = String.valueOf(fletchable.getWith().getAmount());
            }
            String firstRequirement = firstAmount + " " + firstName;
            String secondRequirement = secondAmount + " " + secondName;
            player.send(new SendMessage("You need " + firstRequirement + " and " + secondRequirement + " to do that."));
            return true;
        }
        player.action.execute(fletch(player, fletchable, item, amount), true);
        return true;
    }
References com.runehive.game.world.entity.mob.Mob.action, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.items.containers.ItemContainer.containsAll(), com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.action.ActionManager.execute(), fletch(), FLETCHABLE_KEY, com.runehive.game.world.items.Item.getAmount(), com.runehive.util.Utility.getAOrAn(), com.runehive.content.skill.impl.fletching.Fletchable.getFletchableItems(), com.runehive.content.skill.impl.fletching.Fletchable.getIngredients(), com.runehive.content.skill.impl.fletching.FletchableItem.getLevel(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.items.Item.getName(), com.runehive.content.skill.impl.fletching.Fletchable.getUse(), com.runehive.content.skill.impl.fletching.Fletchable.getWith(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.util.generic.GenericAttributes.remove(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.game.world.entity.skill.Skill.Skill(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by clickButton(), and fletch().
useItem()
boolean com.runehive.content.skill.impl.fletching.Fletching.useItem (Player player, ItemOnItemInteractionEvent event) protected
Reimplemented from com.runehive.game.world.entity.skill.Skill.
Definition at line 62 of file Fletching.java.
{
        Item first = event.getFirst();
        Item second = event.getSecond();
        if (FiremakingData.forId(first.getId()).isPresent() && FiremakingData.forId(second.getId()).isPresent()) {
            return false;
        }
        Fletchable fletchable = getFletchable(first.getId(), second.getId());
        if (fletchable == null || first.getId() == 590 || second.getId() == 590 || first.getId() == 8792 || second.getId() == 8792) {
            return false;
        }
        if (!fletchable.getUse().equalIds(first) && !fletchable.getUse().equalIds(second)) {
            player.message("You need to use this with " + Utility.getAOrAn(fletchable.getUse().getName()) + " " + fletchable.getUse().getName().toLowerCase() + " to fletch this item.");
            return true;
        }
        String prefix = fletchable.getWith().getName().split(" ")[0];
        switch (fletchable.getFletchableItems().length) {
            case 1:
                player.attributes.set(FLETCHABLE_KEY, fletchable);
                player.send(new SendString("\\n \\n \\n \\n" + fletchable.getFletchableItems()[0].getProduct().getName(), 2799));
                player.send(new SendItemOnInterfaceZoom(1746, 170, fletchable.getFletchableItems()[0].getProduct().getId()));
                player.send(new SendChatBoxInterface(4429));
                return true;
            case 2:
                player.attributes.set(FLETCHABLE_KEY, fletchable);
                player.send(new SendItemOnInterfaceZoom(8869, 170, fletchable.getFletchableItems()[0].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8870, 170, fletchable.getFletchableItems()[1].getProduct().getId()));
                player.send(new SendString("\\n \\n \\n \\n".concat(prefix + " Short Bow"), 8874));
                player.send(new SendString("\\n \\n \\n \\n".concat(prefix + " Long Bow"), 8878));
                player.send(new SendChatBoxInterface(8866));
                return true;
            case 3:
                player.attributes.set(FLETCHABLE_KEY, fletchable);
                player.send(new SendItemOnInterfaceZoom(8883, 170, fletchable.getFletchableItems()[0].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8884, 170, fletchable.getFletchableItems()[1].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8885, 170, fletchable.getFletchableItems()[2].getProduct().getId()));
                player.send(new SendString("\\n \\n \\n \\n".concat("Arrow heads"), 8889));
                player.send(new SendString("\\n \\n \\n \\n".concat(prefix + " Short Bow"), 8893));
                player.send(new SendString("\\n \\n \\n \\n".concat(prefix + " Long Bow"), 8897));
                player.send(new SendChatBoxInterface(8880));
                return true;
            case 4:
                player.attributes.set(FLETCHABLE_KEY, fletchable);
                player.send(new SendItemOnInterfaceZoom(8902, 170, fletchable.getFletchableItems()[0].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8903, 170, fletchable.getFletchableItems()[1].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8904, 170, fletchable.getFletchableItems()[2].getProduct().getId()));
                player.send(new SendItemOnInterfaceZoom(8905, 170, fletchable.getFletchableItems()[3].getProduct().getId()));
                String[] productNames;
                if (fletchable == Carvable.AMETHYST) {
                    productNames = new String[]{"Arrowtips", "Bolt tips", "Javelin heads", "Dart tips"};
                } else {
                    productNames = new String[]{"Arrow Shafts", "Short Bow", "Long Bow", "Crossbow Stock"};
                }
                player.send(new SendString("\\n \\n \\n \\n".concat(productNames[0]), 8909));
                player.send(new SendString("\\n \\n \\n \\n".concat(productNames[1]), 8913));
                player.send(new SendString("\\n \\n \\n \\n".concat(productNames[2]), 8917));
                player.send(new SendString("\\n \\n \\n \\n".concat(productNames[3]), 8921));
                player.send(new SendChatBoxInterface(8899));
                return true;
            default:
                return false;
        }
    }
References com.runehive.content.skill.impl.fletching.impl.Carvable.AMETHYST, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.items.Item.equalIds(), FLETCHABLE_KEY, com.runehive.content.skill.impl.firemaking.FiremakingData.forId(), com.runehive.util.Utility.getAOrAn(), getFletchable(), com.runehive.content.skill.impl.fletching.Fletchable.getFletchableItems(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.content.skill.impl.fletching.FletchableItem.getProduct(), com.runehive.content.skill.impl.fletching.Fletchable.getUse(), com.runehive.content.skill.impl.fletching.Fletchable.getWith(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.util.generic.GenericAttributes.set().
Member Data Documentation
FLETCHABLE_KEY
final String com.runehive.content.skill.impl.fletching.Fletching.FLETCHABLE_KEY = "FLETCHABLE_KEY" static private
Definition at line 38 of file Fletching.java.
Referenced by clickButton(), fletch(), start(), and useItem().
FLETCHABLES
final HashMap<Integer, Fletchable> com.runehive.content.skill.impl.fletching.Fletching.FLETCHABLES = new HashMap<>() static private
Definition at line 40 of file Fletching.java.
Referenced by addFletchable(), and getFletchable().
logger
final Logger com.runehive.content.skill.impl.fletching.Fletching.logger = LogManager.getLogger(Fletching.class) static private
Definition at line 36 of file Fletching.java.
Referenced by clickButton().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/fletching/Fletching.java