RuneHive-Game: com.runehive.net.packet.PacketRepository Class Reference
com.runehive.net.packet.PacketRepository Class Reference
The repository that stores packets sizes and listeners for how to execute the packets.
Static Public Member Functions
static PacketListener lookupListener (final int opcode)
Looks up the listener for this packet.
static int lookupSize (int opcode)
Looks up the reference size of a packet.
static PacketType lookupType (int opcode)
The method that looks up the packets type.
static void registerListener (int opcode, PacketListener listener)
Registers a listener to listen for client -> server packet events.
static void registerType (int opcode, int type)
Registers a type for a packet.
static void sendToListener (Player player, GamePacket packet)
Static Private Attributes
static final Logger logger = LogManager.getLogger(PacketRepository.class)
static final int MAX_CLIENT_PACKETS = 257
The number of client packets known.
static final PacketListener[] packetListeners = new PacketListener[MAX_CLIENT_PACKETS]
The client -> server packet listeners.
static final int[] packetTypes = new int[MAX_CLIENT_PACKETS]
The array that holds packet types.
Detailed Description
The repository that stores packets sizes and listeners for how to execute the packets.
Author
nshusa
Definition at line 15 of file PacketRepository.java.
Member Function Documentation
lookupListener()
PacketListener com.runehive.net.packet.PacketRepository.lookupListener (final int opcode) static
Looks up the listener for this packet.
Parameters
opcode The opcode of the packet
Returns
The result.
Definition at line 62 of file PacketRepository.java.
{
        final PacketListener[] packetListeners = PacketRepository.packetListeners;
        if (opcode < 0 || opcode >= packetListeners.length) {
            return null;
        }
        return packetListeners[opcode];
    }
References packetListeners.
Referenced by com.runehive.net.codec.game.GamePacketDecoder.decodePayload().
lookupSize()
int com.runehive.net.packet.PacketRepository.lookupSize (int opcode) static
Looks up the reference size of a packet.
Parameters
opcode The packet to lookup
Returns
The reference size.
Definition at line 100 of file PacketRepository.java.
{
        if (opcode < 0 || opcode >= packetTypes.length) {
            return 0;
        }
        return packetTypes[opcode];
    }
References packetTypes.
Referenced by com.runehive.net.codec.game.GamePacketDecoder.decodeOpcode().
lookupType()
PacketType com.runehive.net.packet.PacketRepository.lookupType (int opcode) static
The method that looks up the packets type.
Parameters
opcode The opcode to lookup
Returns
The packet type.
Definition at line 76 of file PacketRepository.java.
{
        if (opcode < 0 || opcode >= packetTypes.length) {
            return PacketType.EMPTY;
        }
        final int size = packetTypes[opcode];
        if (size == -2) {
            return PacketType.VAR_SHORT;
        } else if (size == -1) {
            return PacketType.VAR_BYTE;
        } else if (size > 0) {
            return PacketType.FIXED;
        } else {
            return PacketType.EMPTY;
        }
    }
References com.runehive.net.packet.PacketType.EMPTY, com.runehive.net.packet.PacketType.FIXED, packetTypes, com.runehive.net.packet.PacketType.VAR_BYTE, and com.runehive.net.packet.PacketType.VAR_SHORT.
Referenced by com.runehive.net.codec.game.GamePacketDecoder.decodeOpcode().
registerListener()
void com.runehive.net.packet.PacketRepository.registerListener (int opcode, PacketListener listener) static
Registers a listener to listen for client -> server packet events.
Parameters
opcode The packet to intercept.
listener The listener that will execute this packet.
Definition at line 50 of file PacketRepository.java.
{
        Preconditions.checkArgument(opcode >= 0 && opcode < packetListeners.length);
        packetListeners[opcode] = listener;
    }
References packetListeners.
Referenced by com.runehive.io.PacketListenerLoader.run().
registerType()
void com.runehive.net.packet.PacketRepository.registerType (int opcode, int type) static
Registers a type for a packet.
The following types are...
-2 var_short -1 var_byte 0 empty
0 fixed
Parameters
opcode The packet to register this type for
type The type for this packet.
Definition at line 120 of file PacketRepository.java.
{
        Preconditions.checkArgument(opcode >= 0 && opcode < packetListeners.length);
        packetTypes[opcode] = type;
    }
References packetListeners, and packetTypes.
Referenced by com.runehive.util.parser.impl.PacketSizeParser.parse().
sendToListener()
void com.runehive.net.packet.PacketRepository.sendToListener (Player player, GamePacket packet) static
Definition at line 34 of file PacketRepository.java.
{
        final PacketListener listener = packetListeners[packet.getOpcode()];
        if (listener != null) {
            if (packet.getOpcode() != 0) {
                //logger.info("Packet recv Opcode: {} Player name: {} Size: {}", packet.getOpcode(), player.getUsername(), packet.getSize());
            }
            listener.handlePacket(player, packet);
        }
    }
References com.runehive.net.packet.PacketListener.handlePacket(), and packetListeners.
Referenced by com.runehive.net.session.GameSession.processClientPackets().
Member Data Documentation
logger
final Logger com.runehive.net.packet.PacketRepository.logger = LogManager.getLogger(PacketRepository.class) static private
Definition at line 17 of file PacketRepository.java.
MAX_CLIENT_PACKETS
final int com.runehive.net.packet.PacketRepository.MAX_CLIENT_PACKETS = 257 static private
The number of client packets known.
Definition at line 22 of file PacketRepository.java.
packetListeners
final PacketListener [] com.runehive.net.packet.PacketRepository.packetListeners = new PacketListener[MAX_CLIENT_PACKETS] static private
The client -> server packet listeners.
Definition at line 27 of file PacketRepository.java.
Referenced by lookupListener(), registerListener(), registerType(), and sendToListener().
packetTypes
final int [] com.runehive.net.packet.PacketRepository.packetTypes = new int[MAX_CLIENT_PACKETS] static private
The array that holds packet types.
Definition at line 32 of file PacketRepository.java.
Referenced by lookupSize(), lookupType(), and registerType().
The documentation for this class was generated from the following file:
java/com/runehive/net/packet/PacketRepository.java