RuneHive-Game: com.runehive.content.skill.impl.magic.RunePouch Class Reference
com.runehive.content.skill.impl.magic.RunePouch Class Reference
Handles the rune pouch.
Public Member Functions
void clear ()
void clear (boolean open)
void clearInterface ()
boolean contains (Item item)
boolean containsId (int item)
boolean death (Item item)
void deposit (Item item, int amount)
int getRuneAmount ()
int getRuneAmount (int id)
void open ()
void refresh ()
void remove (Item item)
RunePouch (Player player)
Constructs a new RunePouch.
void withdraw (int item, int amount)
Public Attributes
List< Item > runes = new LinkedList<>()
The runes stores in the rune pouch;.
Private Attributes
final Item[] ALLOWED_RUNES
Array of all runes allowed to be inside the rune pouch.
final Player player
The player instance.
Static Private Attributes
static final int MAXIMUM_RUNE_CAPACITY = 16_000
The maximum amount of total runes the player can carry in their rune pouch.
Detailed Description
Handles the rune pouch.
Author
Daniel
Definition at line 17 of file RunePouch.java.
Constructor & Destructor Documentation
RunePouch()
com.runehive.content.skill.impl.magic.RunePouch.RunePouch (Player player)
Constructs a new RunePouch.
Definition at line 36 of file RunePouch.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
clear() [1/2]
void com.runehive.content.skill.impl.magic.RunePouch.clear ()
Definition at line 52 of file RunePouch.java.
{
        clear(true);
    }
References clear().
Referenced by clear().
clear() [2/2]
void com.runehive.content.skill.impl.magic.RunePouch.clear (boolean open)
Definition at line 45 of file RunePouch.java.
{
        if(open) runes.forEach(player.inventory::add);
        runes.clear();
        if(open) player.interfaceManager.open(41700);
        refresh();
    }
References open(), player, refresh(), and runes.
Referenced by com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), and com.runehive.content.lms.LMSGame.reset().
clearInterface()
void com.runehive.content.skill.impl.magic.RunePouch.clearInterface ()
Definition at line 61 of file RunePouch.java.
{
        player.send(new SendItemOnInterface(41710, new Item[0]));
    }
References player.
contains()
boolean com.runehive.content.skill.impl.magic.RunePouch.contains (Item item)
Definition at line 140 of file RunePouch.java.
{
        for (Item rune : runes) {
            if (rune.getId() == item.getId() && rune.getAmount() >= item.getAmount())
                return true;
        }
        return false;
    }
References com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), and runes.
Referenced by com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes().
containsId()
boolean com.runehive.content.skill.impl.magic.RunePouch.containsId (int item)
Definition at line 148 of file RunePouch.java.
{
        for (Item rune : runes) {
            if (rune.getId() == item)
                return true;
        }
        return false;
    }
References runes.
death()
boolean com.runehive.content.skill.impl.magic.RunePouch.death (Item item)
Definition at line 167 of file RunePouch.java.
{
        if (item.getId() == 12971 && Area.inWilderness(player)) {
            runes.clear();
            return true;
        }
        return false;
    }
References com.runehive.game.world.items.Item.getId(), com.runehive.game.world.position.Area.inWilderness(), player, and runes.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems().
deposit()
void com.runehive.content.skill.impl.magic.RunePouch.deposit (Item item, int amount)
Definition at line 82 of file RunePouch.java.
{
        boolean allowed = false;
        for (Item rune : ALLOWED_RUNES) {
            if (rune.getId() == item.getId()) {
                allowed = true;
                break;
            }
        }
        if (!allowed) {
            player.message("You can only deposit runes into the rune pouch!");
            return;
        }
        for (Item rune : runes) {
            if (item.getId() == rune.getId()) {
                if (rune.getAmount() + amount > MAXIMUM_RUNE_CAPACITY) {
                    amount = MAXIMUM_RUNE_CAPACITY - rune.getAmount();
                    player.message("You can only have a total of " + Utility.formatDigits(MAXIMUM_RUNE_CAPACITY) + " of the same rune in your rune pouch.");
                }
                player.inventory.remove(item.getId(), amount);
                rune.incrementAmountBy(amount);
                refresh();
                return;
            }
        }
        if (runes.size() >= 3) {
            player.message("Your rune pouch is currently full and can not hold any more types of runes!");
            return;
        }
        if (amount > MAXIMUM_RUNE_CAPACITY) {
            amount = MAXIMUM_RUNE_CAPACITY;
            player.message("You can only have a total of " + Utility.formatDigits(MAXIMUM_RUNE_CAPACITY) + " of the same rune in your rune pouch.");
        }
        player.inventory.remove(item.getId(), amount);
        runes.add(new Item(item.getId(), amount));
        refresh();
    }
References ALLOWED_RUNES, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getId(), MAXIMUM_RUNE_CAPACITY, player, refresh(), and runes.
getRuneAmount() [1/2]
int com.runehive.content.skill.impl.magic.RunePouch.getRuneAmount ()
Definition at line 123 of file RunePouch.java.
{
        int amount = 0;
        for (Item rune : runes) {
            amount += rune.getAmount();
        }
        return amount;
    }
References runes.
getRuneAmount() [2/2]
int com.runehive.content.skill.impl.magic.RunePouch.getRuneAmount (int id)
Definition at line 131 of file RunePouch.java.
{
        int amount = 0;
        for (Item rune : runes) {
            if (rune.getId() == id)
                amount += rune.getAmount();
        }
        return amount;
    }
References runes.
open()
void com.runehive.content.skill.impl.magic.RunePouch.open ()
Definition at line 40 of file RunePouch.java.
                       {
        refresh();
        player.interfaceManager.open(41700);
    }
References player, and refresh().
Referenced by clear().
refresh()
void com.runehive.content.skill.impl.magic.RunePouch.refresh ()
Definition at line 56 of file RunePouch.java.
{
        player.send(new SendItemOnInterface(41710, runes.toArray(new Item[runes.size()])));
        player.send(new SendItemOnInterface(41711, player.inventory.getItems()));
    }
References player, and runes.
Referenced by clear(), deposit(), com.runehive.content.lms.LMSGame.giveItems(), open(), com.runehive.content.lms.LMSGame.reset(), and withdraw().
remove()
void com.runehive.content.skill.impl.magic.RunePouch.remove (Item item)
Definition at line 156 of file RunePouch.java.
{
        for (Item rune : runes) {
            if (rune.equalIds(item)) {
                rune.decrementAmountBy(item.getAmount());
                if (rune.getAmount() == 0)
                    runes.remove(rune);
                return;
            }
        }
    }
References runes.
withdraw()
void com.runehive.content.skill.impl.magic.RunePouch.withdraw (int item, int amount)
Definition at line 65 of file RunePouch.java.
{
        for (Item rune : runes) {
            if (rune.getId() == item) {
                int current = player.inventory.computeAmountForId(item);
                if (rune.getAmount() - amount < 0) amount = rune.getAmount();
                player.inventory.add(item, amount);
                int newAm = player.inventory.computeAmountForId(item);
                if (newAm - current < amount) amount = newAm - current;
                rune.decrementAmountBy(amount);
                if (rune.getAmount() == 0)
                    runes.remove(rune);
                refresh();
                return;
            }
        }
    }
References player, refresh(), and runes.
Member Data Documentation
ALLOWED_RUNES
final Item [] com.runehive.content.skill.impl.magic.RunePouch.ALLOWED_RUNES private
Initial value:
= {
            new Item(554), new Item(555), new Item(556), new Item(557), new Item(558),
            new Item(559), new Item(560), new Item(561), new Item(562), new Item(563),
            new Item(564), new Item(565), new Item(566), new Item(9075), new Item(21880)
    }
Array of all runes allowed to be inside the rune pouch.
Definition at line 23 of file RunePouch.java.
{
            new Item(554), new Item(555), new Item(556), new Item(557), new Item(558),
            new Item(559), new Item(560), new Item(561), new Item(562), new Item(563),
            new Item(564), new Item(565), new Item(566), new Item(9075), new Item(21880)
    };
Referenced by deposit().
MAXIMUM_RUNE_CAPACITY
final int com.runehive.content.skill.impl.magic.RunePouch.MAXIMUM_RUNE_CAPACITY = 16_000 static private
The maximum amount of total runes the player can carry in their rune pouch.
Definition at line 20 of file RunePouch.java.
Referenced by deposit().
player
final Player com.runehive.content.skill.impl.magic.RunePouch.player private
The player instance.
Definition at line 30 of file RunePouch.java.
Referenced by clear(), clearInterface(), death(), deposit(), open(), refresh(), RunePouch(), and withdraw().
runes
List<Item> com.runehive.content.skill.impl.magic.RunePouch.runes = new LinkedList<>()
The runes stores in the rune pouch;.
Definition at line 33 of file RunePouch.java.
Referenced by clear(), contains(), containsId(), death(), deposit(), getRuneAmount(), getRuneAmount(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), refresh(), remove(), com.runehive.content.lms.LMSGame.reset(), and withdraw().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/magic/RunePouch.java