RuneHive-Game: com.runehive.content.clanchannel.ClanRepository Class Reference
com.runehive.content.clanchannel.ClanRepository Class Reference
The repository containing all the clans and their corresponding data.
Static Public Member Functions
static void addChannel (ClanChannel channel)
Adds the channel.
static ClanChannel getChannel (String channel)
Returns the channel.
static Optional< Set< ClanChannel > > getTopChanels (ClanType type)
static Optional< Set< ClanChannel > > getTopChanels (ClanViewer.Filter filter)
static void loadChannels ()
Loads all clans and puts them into the map.
static boolean nameExist (String name)
static void removeChannel (ClanChannel channel)
Handles removing a channel from the clan lists.
static void saveAllActiveClans ()
static void setActive (ClanChannel channel)
static void setInactive (ClanChannel channel)
static boolean tagExist (String tag)
Static Public Attributes
static Set< ClanChannel > ACTIVE_CHANNELS = new HashSet<>()
Set of all active clan chat channels.
static Set< String > ACTIVE_NAMES = new HashSet<>()
Set of all active clan chat names.
static Set< String > ACTIVE_TAGS = new HashSet<>()
Set of all active clan chat tags.
static Set< ClanChannel > ALLTIME = new TreeSet<>()
Set of all active clan chat names.
Static Private Member Functions
static void saveClan (ClanChannel channel)
Static Private Attributes
static Map< String, ClanChannel > CHANNELS = new HashMap<>()
Map of all clan chat channels.
static Set< ClanChannel > TOP_IRON_MAN = new TreeSet<>()
Set of all active clan chat names.
static Set< ClanChannel > TOP_PVM = new TreeSet<>()
Set of all active clan chat names.
static Set< ClanChannel > TOP_PVP = new TreeSet<>()
Set of all active clan chat names.
static Set< ClanChannel > TOP_SKILLING = new TreeSet<>()
Set of all active clan chat names.
Detailed Description
The repository containing all the clans and their corresponding data.
Author
Daniel
Definition at line 18 of file ClanRepository.java.
Member Function Documentation
addChannel()
void com.runehive.content.clanchannel.ClanRepository.addChannel (ClanChannel channel) static
Adds the channel.
Definition at line 53 of file ClanRepository.java.
{
        CHANNELS.put(channel.getOwner().toLowerCase().trim(), channel);
    }
References CHANNELS.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.create(), and com.runehive.content.clanchannel.channel.ClanChannel.load().
getChannel()
ClanChannel com.runehive.content.clanchannel.ClanRepository.getChannel (String channel) static
Returns the channel.
Definition at line 48 of file ClanRepository.java.
{
        return CHANNELS.get(channel.toLowerCase().trim());
    }
References CHANNELS.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask(), com.runehive.content.clanchannel.channel.ClanChannelHandler.connect(), com.runehive.content.clanchannel.channel.ClanChannel.create(), and com.runehive.content.clanchannel.channel.ClanChannel.setRank().
getTopChanels() [1/2]
Optional< Set< ClanChannel > > com.runehive.content.clanchannel.ClanRepository.getTopChanels (ClanType type) static
Definition at line 138 of file ClanRepository.java.
{
        if (type.equals(ClanType.PVP)) {
            return Optional.of(TOP_PVP);
        }
        if (type.equals(ClanType.PVM)) {
            return Optional.of(TOP_PVM);
        }
        if (type.equals(ClanType.SKILLING)) {
            return Optional.of(TOP_SKILLING);
        }
        if (type.equals(ClanType.IRON_MAN)) {
            return Optional.of(TOP_IRON_MAN);
        }
        return Optional.empty();
    }
References com.runehive.content.clanchannel.ClanType.IRON_MAN, com.runehive.content.clanchannel.ClanType.PVM, com.runehive.content.clanchannel.ClanType.PVP, com.runehive.content.clanchannel.ClanType.SKILLING, TOP_IRON_MAN, TOP_PVM, TOP_PVP, and TOP_SKILLING.
Referenced by com.runehive.content.clanchannel.content.ClanViewer.drawClanList().
getTopChanels() [2/2]
Optional< Set< ClanChannel > > com.runehive.content.clanchannel.ClanRepository.getTopChanels (ClanViewer.Filter filter) static
Definition at line 154 of file ClanRepository.java.
{
        if (filter.equals(ClanViewer.Filter.ALL_TIME)) {
            return Optional.of(ALLTIME);
        }
        if (filter.equals(ClanViewer.Filter.TOP_PVM)) {
            return Optional.of(TOP_PVM);
        }
        if (filter.equals(ClanViewer.Filter.TOP_PVP)) {
            return Optional.of(TOP_PVP);
        }
        if (filter.equals(ClanViewer.Filter.TOP_SKILLING)) {
            return Optional.of(TOP_SKILLING);
        }
        if (filter.equals(ClanViewer.Filter.TOP_IRON_MAN)) {
            return Optional.of(TOP_IRON_MAN);
        }
        return Optional.empty();
    }
References com.runehive.content.clanchannel.content.ClanViewer.Filter.ALL_TIME, ALLTIME, TOP_IRON_MAN, com.runehive.content.clanchannel.content.ClanViewer.Filter.TOP_IRON_MAN, TOP_PVM, com.runehive.content.clanchannel.content.ClanViewer.Filter.TOP_PVM, TOP_PVP, com.runehive.content.clanchannel.content.ClanViewer.Filter.TOP_PVP, TOP_SKILLING, and com.runehive.content.clanchannel.content.ClanViewer.Filter.TOP_SKILLING.
loadChannels()
void com.runehive.content.clanchannel.ClanRepository.loadChannels () static
Loads all clans and puts them into the map.
Definition at line 112 of file ClanRepository.java.
{
        Path path = Paths.get("./data/content/clan/");
        File[] files = path.toFile().listFiles();
        if (files == null) {
            System.out.println("No clan files were found.");
            return;
        }
        for (File file : files) {
            String fileName = file.getName();
            if (!fileName.toLowerCase().endsWith(".json")) continue;
            /*ClanChannel channel = ClanChannel.fromJson(file.getName().replace(".json", ""));
            if (channel != null) {
                if (!channel.getTag().isEmpty())
                    ACTIVE_TAGS.add(channel.getTag());
                if (!channel.getName().isEmpty())
                    ACTIVE_NAMES.add(channel.getName());
                ALLTIME.add(channel);
                CHANNELS.put(channel.getOwner().toLowerCase().trim(), channel);
            }*/
            ClanChannel.load(file.getName().replace(".json", ""));
        }
    }
References com.runehive.content.clanchannel.channel.ClanChannel.load().
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
nameExist()
boolean com.runehive.content.clanchannel.ClanRepository.nameExist (String name) static
Definition at line 74 of file ClanRepository.java.
{
        return ACTIVE_TAGS.contains(name.toLowerCase().trim());
    }
References ACTIVE_TAGS.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.setName().
removeChannel()
void com.runehive.content.clanchannel.ClanRepository.removeChannel (ClanChannel channel) static
Handles removing a channel from the clan lists.
Definition at line 58 of file ClanRepository.java.
{
        CHANNELS.remove(channel.getOwner().toLowerCase().trim());
        ACTIVE_CHANNELS.remove(channel);
        saveClan(channel);
    }
References ACTIVE_CHANNELS, CHANNELS, and saveClan().
saveAllActiveClans()
void com.runehive.content.clanchannel.ClanRepository.saveAllActiveClans () static
Definition at line 86 of file ClanRepository.java.
{
        for (ClanChannel channel : ClanRepository.ACTIVE_CHANNELS) {
            if (channel.activeSize() <= 0) {
                continue;
            }
            saveClan(channel);
        }
    }
References ACTIVE_CHANNELS, and saveClan().
Referenced by com.runehive.game.task.impl.PlayerSaveEvent.execute(), and com.runehive.game.world.World.save().
saveClan()
void com.runehive.content.clanchannel.ClanRepository.saveClan (ClanChannel channel) static private
Definition at line 95 of file ClanRepository.java.
{
        Thread.startVirtualThread(() -> {
            final File dir = Paths.get("data", "content", "clan").toFile();
            if (!dir.exists()) {
                dir.mkdirs();
            }
            try (FileWriter fw = new FileWriter(dir.toPath().resolve(channel.getOwner() + ".json").toFile())) {
                fw.write(GsonUtils.JSON_PRETTY_NO_NULLS.get().toJson(channel.toJson()));
            } catch (final Exception e) {
                e.printStackTrace();
            }
        });
    }
References com.runehive.util.GsonUtils.JSON_PRETTY_NO_NULLS.
Referenced by removeChannel(), saveAllActiveClans(), and setInactive().
setActive()
void com.runehive.content.clanchannel.ClanRepository.setActive (ClanChannel channel) static
Definition at line 64 of file ClanRepository.java.
{
        ACTIVE_CHANNELS.add(channel);
    }
References ACTIVE_CHANNELS.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.establish().
setInactive()
void com.runehive.content.clanchannel.ClanRepository.setInactive (ClanChannel channel) static
Definition at line 68 of file ClanRepository.java.
{
        if (ACTIVE_CHANNELS.remove(channel)) {
            saveClan(channel);
        }
    }
References ACTIVE_CHANNELS, and saveClan().
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.ban(), and com.runehive.content.clanchannel.channel.ClanChannel.disconnect().
tagExist()
boolean com.runehive.content.clanchannel.ClanRepository.tagExist (String tag) static
Definition at line 78 of file ClanRepository.java.
{
        for (ClanChannel channel : CHANNELS.values()) {
            if (channel.getTag().equalsIgnoreCase(tag))
                return true;
        }
        return false;
    }
References CHANNELS.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.setTag().
Member Data Documentation
ACTIVE_CHANNELS
Set<ClanChannel> com.runehive.content.clanchannel.ClanRepository.ACTIVE_CHANNELS = new HashSet<>() static
Set of all active clan chat channels.
Definition at line 24 of file ClanRepository.java.
Referenced by removeChannel(), saveAllActiveClans(), setActive(), setInactive(), and com.runehive.game.task.impl.ClanUpdateEvent.tick().
ACTIVE_NAMES
Set<String> com.runehive.content.clanchannel.ClanRepository.ACTIVE_NAMES = new HashSet<>() static
Set of all active clan chat names.
Definition at line 30 of file ClanRepository.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.load(), and com.runehive.content.clanchannel.channel.ClanChannel.setName().
ACTIVE_TAGS
Set<String> com.runehive.content.clanchannel.ClanRepository.ACTIVE_TAGS = new HashSet<>() static
Set of all active clan chat tags.
Definition at line 27 of file ClanRepository.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.load(), nameExist(), and com.runehive.content.clanchannel.channel.ClanChannel.setTag().
ALLTIME
Set<ClanChannel> com.runehive.content.clanchannel.ClanRepository.ALLTIME = new TreeSet<>() static
Set of all active clan chat names.
Definition at line 33 of file ClanRepository.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.create(), getTopChanels(), and com.runehive.content.clanchannel.channel.ClanChannel.load().
CHANNELS
Map<String, ClanChannel> com.runehive.content.clanchannel.ClanRepository.CHANNELS = new HashMap<>() static private
Map of all clan chat channels.
Definition at line 21 of file ClanRepository.java.
Referenced by addChannel(), getChannel(), removeChannel(), and tagExist().
TOP_IRON_MAN
Set<ClanChannel> com.runehive.content.clanchannel.ClanRepository.TOP_IRON_MAN = new TreeSet<>() static private
Set of all active clan chat names.
Definition at line 45 of file ClanRepository.java.
Referenced by getTopChanels(), and getTopChanels().
TOP_PVM
Set<ClanChannel> com.runehive.content.clanchannel.ClanRepository.TOP_PVM = new TreeSet<>() static private
Set of all active clan chat names.
Definition at line 39 of file ClanRepository.java.
Referenced by getTopChanels(), and getTopChanels().
TOP_PVP
Set<ClanChannel> com.runehive.content.clanchannel.ClanRepository.TOP_PVP = new TreeSet<>() static private
Set of all active clan chat names.
Definition at line 36 of file ClanRepository.java.
Referenced by getTopChanels(), and getTopChanels().
TOP_SKILLING
Set<ClanChannel> com.runehive.content.clanchannel.ClanRepository.TOP_SKILLING = new TreeSet<>() static private
Set of all active clan chat names.
Definition at line 42 of file ClanRepository.java.
Referenced by getTopChanels(), and getTopChanels().
The documentation for this class was generated from the following file:
java/com/runehive/content/clanchannel/ClanRepository.java