RuneHive-Game: com.runehive.game.action.impl.DebugAction Class Reference
com.runehive.game.action.impl.DebugAction Class Reference
This is a debug action.
Public Member Functions
DebugAction (Player player)
void execute ()
A function representing the unit of work that will be carried out.
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Private Member Functions
void input (Player player)
final void save ()
Private Attributes
Map< Integer, String > DATA = new HashMap<>()
int identification
boolean inputTaken
boolean pause
final Player player
int tick
Additional Inherited Members
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
void onCancel (boolean logout)
A function executed on cancellation.
void onSchedule ()
A function executed on registration.
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Detailed Description
This is a debug action.
Feel free to modify this how you want to test whatever.
Author
Daniel
Definition at line 21 of file DebugAction.java.
Constructor & Destructor Documentation
DebugAction()
com.runehive.game.action.impl.DebugAction.DebugAction (Player player)
Definition at line 35 of file DebugAction.java.
{
        super(true, 1);
        this.player = player;
        this.tick = 0;
        this.identification = 0;
        this.inputTaken = false;
        this.pause = false;
        this.DATA = new HashMap<>();
    }
References player.
Member Function Documentation
execute()
void com.runehive.game.action.impl.DebugAction.execute ()
A function representing the unit of work that will be carried out.
Reimplemented from com.runehive.game.task.Task.
Definition at line 64 of file DebugAction.java.
{
        if (inputTaken) {
            if (tick++ == 1) {
                input(player);
            }
            return;
        }
        if (pause) {
            player.dialogueFactory.sendOption(
            "Empty",
            () -> pause = false,
            "Enter", () -> {
                player.dialogueFactory.clear();
                tick = 0;
                inputTaken = true;
            },
            "Save & End",
            () -> {
                save();
                cancel();
                player.send(new SendMessage("A total of " + DATA.size() + " interfaces were saved."));
            }).execute();
            return;
        }
        identification++;
        player.interfaceManager.open(identification);
        player.send(new SendMessage("Opening itemcontainer: " + identification, MessageColor.DARK_RED));
        pause = true;
    }
References com.runehive.game.task.Task.cancel(), com.runehive.util.MessageColor.DARK_RED, DATA, execute(), identification, input(), inputTaken, pause, player, save(), and tick.
Referenced by execute().
input()
void com.runehive.game.action.impl.DebugAction.input (Player player) private
Definition at line 54 of file DebugAction.java.
{
        player.send(new SendInputMessage("Enter the itemcontainer description", 100, input -> {
            DATA.put(identification, input);
            inputTaken = false;
            pause = false;
        }));
    }
References DATA, identification, input(), inputTaken, pause, and player.
Referenced by execute(), and input().
save()
final void com.runehive.game.action.impl.DebugAction.save () private
Definition at line 45 of file DebugAction.java.
{
        Gson gson = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();
        try (FileWriter fw = new FileWriter("./data/INTERFACES.json")) {
            fw.write(gson.toJson(DATA));
        } catch (final Exception e) {
            e.printStackTrace();
        }
    }
References DATA.
Referenced by execute().
Member Data Documentation
DATA
Map<Integer, String> com.runehive.game.action.impl.DebugAction.DATA = new HashMap<>() private
Definition at line 23 of file DebugAction.java.
Referenced by execute(), input(), and save().
identification
int com.runehive.game.action.impl.DebugAction.identification private
Definition at line 27 of file DebugAction.java.
Referenced by execute(), and input().
inputTaken
boolean com.runehive.game.action.impl.DebugAction.inputTaken private
Definition at line 33 of file DebugAction.java.
Referenced by execute(), and input().
pause
boolean com.runehive.game.action.impl.DebugAction.pause private
Definition at line 31 of file DebugAction.java.
Referenced by execute(), and input().
player
final Player com.runehive.game.action.impl.DebugAction.player private
Definition at line 25 of file DebugAction.java.
Referenced by DebugAction(), execute(), and input().
tick
int com.runehive.game.action.impl.DebugAction.tick private
Definition at line 29 of file DebugAction.java.
Referenced by execute().
The documentation for this class was generated from the following file:
java/com/runehive/game/action/impl/DebugAction.java