RuneHive-Game: com.runehive.content.skill.impl.hunter.trap.TrapExecution Class Reference
com.runehive.content.skill.impl.hunter.trap.TrapExecution Class Reference
Static Public Member Functions
static void setTrapProcess (Trap trap)
static int successFormula (Trap trap)
static boolean trapTimerManagement (Trap trap)
Detailed Description
Definition at line 7 of file TrapExecution.java.
Member Function Documentation
setTrapProcess()
void com.runehive.content.skill.impl.hunter.trap.TrapExecution.setTrapProcess (Trap trap) static
Definition at line 9 of file TrapExecution.java.
{
        for (final Npc npc : TrapManager.HUNTER_NPC_LIST) {
            if (npc == null || !npc.isVisible()) {
                continue;
            }
            if (trap instanceof BoxTrap && npc.id != 5079 && npc.id != 5080)
                continue;
            if (trap instanceof SnareTrap && (npc.id == 5079 || npc.id == 5080))
                continue;
            if (npc.getPosition().isWithinDistance(trap.getGameObject().getPosition(), 1)) {
                if (Utility.random(100) < successFormula(trap)) {
                    TrapManager.catchNPC(trap, npc);
                    return;
                }
            }
        }
    }
References com.runehive.content.skill.impl.hunter.trap.TrapManager.catchNPC(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.content.skill.impl.hunter.trap.TrapManager.HUNTER_NPC_LIST, com.runehive.game.world.entity.mob.Mob.id, com.runehive.game.world.entity.Entity.isVisible(), com.runehive.game.world.position.Position.isWithinDistance(), com.runehive.util.Utility.random(), and successFormula().
Referenced by com.runehive.game.task.impl.HunterTask.execute().
successFormula()
int com.runehive.content.skill.impl.hunter.trap.TrapExecution.successFormula (Trap trap) static
Definition at line 27 of file TrapExecution.java.
{
        if (trap.getOwner() == null)
            return 0;
        int chance = 70;
        if (TrapManager.hasLarupia(trap.getOwner())) {
            chance = chance + 10;
        }
        chance = chance + (int) (trap.getOwner().skills.getLevel(Skill.HUNTER) / 1.5) + 10;
        if (trap.getOwner().skills.getLevel(Skill.HUNTER) < 25)
            chance = (int) (chance * 1.5) + 8;
        if (trap.getOwner().skills.getLevel(Skill.HUNTER) < 40)
            chance = (int) (chance * 1.4) + 3;
        if (trap.getOwner().skills.getLevel(Skill.HUNTER) < 50)
            chance = (int) (chance * 1.3) + 1;
        if (trap.getOwner().skills.getLevel(Skill.HUNTER) < 55)
            chance = (int) (chance * 1.2);
        if (trap.getOwner().skills.getLevel(Skill.HUNTER) < 60)
            chance = (int) (chance * 1.1);
        if (trap.getOwner().skills.getLevel(Skill.HUNTER) < 65)
            chance = (int) (chance * 1.05) + 3;
        return chance;
    }
References com.runehive.content.skill.impl.hunter.trap.TrapManager.hasLarupia(), and com.runehive.game.world.entity.skill.Skill.HUNTER.
Referenced by setTrapProcess().
trapTimerManagement()
boolean com.runehive.content.skill.impl.hunter.trap.TrapExecution.trapTimerManagement (Trap trap) static
Definition at line 54 of file TrapExecution.java.
{
        if (trap.getTicks() > 0)
            trap.setTicks(trap.getTicks() - 1);
        if (trap.getTicks() <= 0) {
            TrapManager.deregister(trap);
            if (trap.getOwner() != null)
                trap.getOwner().message("You left your trap for too long, and it collapsed.");
        }
        return true;
    }
References com.runehive.content.skill.impl.hunter.trap.TrapManager.deregister().
Referenced by com.runehive.game.task.impl.HunterTask.execute().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/hunter/trap/TrapExecution.java