RuneHive-Game: com.runehive.content.gambling.impl.FiftyFive Class Reference
com.runehive.content.gambling.impl.FiftyFive Class Reference
Public Member Functions
FiftyFive (Player host, Player opponent)
void gamble ()
String toString ()
Public Member Functions inherited from com.runehive.content.gambling.Gamble
Gamble (Player host, Player opponent)
Player getHost ()
Player getOpponent ()
Additional Inherited Members
Public Attributes inherited from com.runehive.content.gambling.Gamble
int hostScore
Score betwen the players inside the 'gamble'.
int opponentScore
Detailed Description
Definition at line 9 of file FiftyFive.java.
Constructor & Destructor Documentation
FiftyFive()
com.runehive.content.gambling.impl.FiftyFive.FiftyFive (Player host, Player opponent)
Definition at line 11 of file FiftyFive.java.
{
        super(host, opponent);
    }
References com.runehive.content.gambling.Gamble.host, and com.runehive.content.gambling.Gamble.opponent.
Member Function Documentation
gamble()
void com.runehive.content.gambling.impl.FiftyFive.gamble ()
Reimplemented from com.runehive.content.gambling.Gamble.
Definition at line 21 of file FiftyFive.java.
{
        World.schedule(new Task(1) {
            int time = 0;
            public int randomRoll = 1 + Utility.random(99);
            int hostScore, opponentScore;
            @Override
            protected void execute() {
                switch (time) {
                    case 2:
                        getHost().speak("I rolled " + randomRoll + " on the dice.");
                        getOpponent().speak("The host rolled " + randomRoll + " on the dice.");
                        break;
                    case 4:
                        if (randomRoll > 55) {
                            hostScore = 0;
                            opponentScore = 1;
                        } else if (randomRoll < 55) {
                            hostScore = 1;
                            opponentScore = 0;
                        } else {
                            hostScore = 0;
                            opponentScore = 0;
                        }
                        getHost().getGambling().finish(getHost(), getOpponent(), hostScore, opponentScore);
                        cancel();
                        break;
                }
                time++;
            }
        });
    }
References com.runehive.content.gambling.GambleManager.finish(), com.runehive.game.world.entity.mob.player.Player.getGambling(), com.runehive.content.gambling.Gamble.getHost(), com.runehive.content.gambling.Gamble.getOpponent(), com.runehive.content.gambling.Gamble.hostScore, com.runehive.content.gambling.Gamble.opponentScore, com.runehive.util.Utility.random(), com.runehive.game.world.World.schedule(), and com.runehive.game.world.entity.mob.Mob.speak().
toString()
String com.runehive.content.gambling.impl.FiftyFive.toString ()
Definition at line 16 of file FiftyFive.java.
{
        return "55x2";
    }
The documentation for this class was generated from the following file:
java/com/runehive/content/gambling/impl/FiftyFive.java