RuneHive-Game: com.runehive.game.world.entity.mob.movement.waypoint.Waypoint Class Reference
com.runehive.game.world.entity.mob.movement.waypoint.Waypoint Class Reference abstract
Public Member Functions
boolean equals (Object obj)
void execute ()
A function representing the unit of work that will be carried out.
Interactable getTarget ()
void onChange ()
String toString ()
Public Member Functions inherited from com.runehive.game.task.Task
Task attach (Object newKey)
Attaches a new key.
synchronized final void cancel ()
Cancels all subsequent executions.
synchronized final void cancel (boolean logout)
Cancels all subsequent executions.
boolean canRun ()
Determines if the task can be ran.
Optional< Object > getAttachment ()
String getCreationStackTraceStr ()
int getDelay ()
Long getElapsedTimeFromRunStartTime ()
Optional< Long > getRunStartTime ()
long getTaskCreationTime ()
String getTaskId ()
boolean isInstant ()
boolean isRunning ()
void setDelay (int delay)
Sets the cyclic delay.
void setExecutionTime ()
Task (boolean instant, int delay)
Creates a new Task.
Task (int delay)
Creates a new Task that doesn't execute instantly.
Protected Member Functions
int getRadius ()
void onCancel (boolean logout)
A function executed on cancellation.
abstract void onDestination ()
void onSchedule ()
A function executed on registration.
Waypoint (Mob mob, Interactable target)
boolean withinDistance ()
Protected Member Functions inherited from com.runehive.game.task.Task
void baseExecute ()
boolean canSchedule ()
A function executed on registration.
Protected Attributes
final Mob mob
Interactable target
Package Functions
boolean withinDistance (int x, int y, int x2, int y2, int width, int height, int distance)
Package Functions inherited from com.runehive.game.task.Task
void onException (Exception e)
A function executed on thrown exceptions.
void onLoop ()
A function executed when iterated over.
final synchronized void process ()
synchronized void setRunning (boolean running)
Private Member Functions
void findRoute ()
Private Attributes
Position lastPosition
Detailed Description
Definition at line 20 of file Waypoint.java.
Constructor & Destructor Documentation
Waypoint()
com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.Waypoint (Mob mob, Interactable target) protected
Definition at line 25 of file Waypoint.java.
{
        super(true, 0);
        this.mob = mob;
        this.target = target;
    }
References mob, and target.
Referenced by equals().
Member Function Documentation
equals()
boolean com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.equals (Object obj)
Definition at line 189 of file Waypoint.java.
{
        if (obj == this) return true;
        if (obj instanceof Waypoint other) {
            return Objects.equals(mob, other.mob)
                    && Objects.equals(target, other.target);
        }
        return false;
    }
References mob, target, and Waypoint().
Referenced by com.runehive.game.world.entity.mob.Mob.attack(), com.runehive.game.world.entity.mob.Mob.follow(), com.runehive.game.world.entity.mob.player.Player.pickup(), com.runehive.game.world.entity.mob.Mob.setWaypoint(), and com.runehive.game.world.entity.mob.Mob.walkTo().
execute()
void com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.execute ()
A function representing the unit of work that will be carried out.
Reimplemented from com.runehive.game.task.Task.
Definition at line 102 of file Waypoint.java.
{
        if (target instanceof Mob && Utility.inside(mob, target)) {
            if (!mob.locking.locked(PacketType.MOVEMENT)
                    && !mob.movement.needsPlacement()) {
                Mob targetMob = (Mob) target;
                if (targetMob.hasPriorityIndex(mob)
                        || (!targetMob.isFixingInside() && !targetMob.movement.needsPlacement())) {
                    Utility.fixInsidePosition(mob, target);
                }
            }
            return;
        } else {
            mob.setFixingInside(false);
        }
        if (withinDistance()) {
            onDestination();
            return;
        }
        if (target instanceof GameObject gameObject && mob.isPlayer()) {
            if (gameObject.distance() > 1 && withinDistance(mob.getPosition().getX(), mob.getPosition().getY(), target.getPosition().getX(), target.getPosition().getY(), target.width(), gameObject.length(), gameObject.distance())) {
                onDestination();
                return;
            }
        }
        if (target.getPosition().equals(lastPosition)) {
            return;
        }
        if (mob.locking.locked(PacketType.MOVEMENT)) {
            return;
        }
        lastPosition = target.getPosition();
        findRoute();
    }
References findRoute(), com.runehive.util.Utility.fixInsidePosition(), com.runehive.game.world.entity.mob.Mob.hasPriorityIndex(), com.runehive.util.Utility.inside(), com.runehive.game.world.entity.mob.Mob.isFixingInside(), lastPosition, mob, com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT, com.runehive.game.world.entity.mob.Mob.movement, com.runehive.game.world.entity.mob.movement.Movement.needsPlacement(), onDestination(), target, and withinDistance().
Referenced by onChange().
findRoute()
void com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.findRoute () private
Definition at line 141 of file Waypoint.java.
{
        if (target instanceof Player && mob.equals(((Player) target).pet)) {
            int distance = Utility.getDistance(mob, target);
            if (distance > Region.VIEW_DISTANCE) {
                Npc pet = mob.getNpc();
                pet.move(target.getPosition());
                pet.instance = ((Player) target).instance;
                World.schedule(1, () -> {
                    pet.interact((Player) target);
                    pet.follow((Player) target);
                });
            }
        }
//        if (this instanceof CombatWaypoint) {
//            System.out.println(mob.getPosition());
//            System.out.println(target.getPosition());
//            System.out.println(Utility.getDelta(mob, target));
//            System.out.println();
//        }
        boolean smart = mob.isPlayer() || (mob.isNpc() && !(this instanceof CombatWaypoint));
        if (smart && mob.movement.dijkstraPath(target)) {
            return;
        }
        if (mob.movement.simplePath(target)) {
            return;
        }
        if (mob.isPlayer())
            mob.getPlayer().send(new SendMessage("I can't reach that!"));
        /* No path can be found, lets get out of here!!!! */
        cancel();
    }
References com.runehive.game.task.Task.cancel(), com.runehive.game.world.entity.mob.Mob.follow(), com.runehive.util.Utility.getDistance(), com.runehive.game.world.entity.mob.Mob.interact(), mob, com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.world.World.schedule(), target, and com.runehive.game.world.region.Region.VIEW_DISTANCE.
Referenced by execute(), and onSchedule().
getRadius()
int com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.getRadius () protected
Reimplemented in com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint, and com.runehive.game.world.entity.mob.movement.waypoint.PickupWaypoint.
Definition at line 33 of file Waypoint.java.
{
        return 1;
    }
Referenced by withinDistance().
getTarget()
Interactable com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.getTarget ()
Definition at line 205 of file Waypoint.java.
{
        return target;
    }
References target.
onCancel()
void com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.onCancel (boolean logout) protected
A function executed on cancellation.
Reimplemented from com.runehive.game.task.Task.
Definition at line 180 of file Waypoint.java.
{
        mob.resetFace();
        if (target instanceof Mob other) {
            other.attributes.remove("mob-following");
        }
    }
References mob, and target.
onChange()
void com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.onChange ()
Definition at line 209 of file Waypoint.java.
{
        execute();
//        mob.movement.processNextMovement();
    }
References execute().
onDestination()
abstract void com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.onDestination () abstract protected
Reimplemented in com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.GuardianWaypoint, com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint, com.runehive.game.world.entity.mob.movement.waypoint.FollowWaypoint, com.runehive.game.world.entity.mob.movement.waypoint.PickupWaypoint, and com.runehive.game.world.entity.mob.movement.waypoint.WalkToWaypoint.
Referenced by execute().
onSchedule()
void com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.onSchedule () protected
A function executed on registration.
Reimplemented from com.runehive.game.task.Task.
Definition at line 87 of file Waypoint.java.
{
        if (mob.locking.locked(PacketType.MOVEMENT)) {
            return;
        }
        if (target instanceof Mob) {
            mob.interact((Mob) target);
        }
        if (!withinDistance()) {
            findRoute();
        }
    }
References findRoute(), mob, com.runehive.game.world.entity.mob.data.PacketType.MOVEMENT, target, and withinDistance().
toString()
String com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.toString ()
Definition at line 199 of file Waypoint.java.
{
        return getClass().getSimpleName() + "{" +
                "target=" + target +
                '}';
    }
References target.
withinDistance() [1/2]
boolean com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.withinDistance () protected
Reimplemented in com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.
Definition at line 37 of file Waypoint.java.
{
        if (target instanceof final GameObject object) {
            Position position = mob.getPosition();
            int x = position.getX();
            int y = position.getY();
            GameObjectDefinition definition = object.getDefinition();
            int walkingFlag = definition.getWalkingFlag();
            int sizeX = definition.getWidth();
            int sizeY = definition.getLength();
            int rotation = object.getDirection().getId();
            if (rotation % 2 != 0) {
                sizeX = definition.getLength();
                sizeY = definition.getWidth();
            }
            if (rotation != 0) {
                walkingFlag = (walkingFlag << rotation & 0xF) + (walkingFlag >> 4 - rotation);
            }
            if (sizeX != 0 && sizeY != 0) {
                Position targetPosition = target.getPosition();
                int destX = targetPosition.getX();
                int destY = targetPosition.getY();
                int height = targetPosition.getHeight();
                int flag = TraversalMap.getFlags(destX, destY, height);
                int cornerX = destX + sizeX - 1;
                int cornerY = destY + sizeY - 1;
                if (destX <= x && cornerX >= x && y >= destY && y <= cornerY) {
                    return true;
                }
                if (x == destX - 1 && destY <= y && y <= cornerY && (0x8 & flag) == 0 && (0x8 & walkingFlag) == 0) {
                    return true;
                }
                if (x == cornerX + 1 && destY <= y && cornerY >= y && (flag & 0x80) == 0 && (0x2 & walkingFlag) == 0) {
                    return true;
                }
                if (y == destY - 1 && destX <= x && cornerX >= x && (0x2 & flag) == 0 && (0x4 & walkingFlag) == 0) {
                    return true;
                }
                if (y == cornerY + 1 && destX <= x && cornerX >= x && (flag & 0x20) == 0 && (0x1 & walkingFlag) == 0) {
                    return true;
                }
            }
        }
        return Utility.getDistance(mob, target) <= getRadius() && !mob.movement.needsPlacement();
    }
References com.runehive.util.Utility.getDistance(), com.runehive.game.world.pathfinding.TraversalMap.getFlags(), com.runehive.game.world.position.Position.getHeight(), com.runehive.game.world.object.GameObjectDefinition.getLength(), getRadius(), com.runehive.game.world.object.GameObjectDefinition.getWalkingFlag(), com.runehive.game.world.object.GameObjectDefinition.getWidth(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), mob, and target.
Referenced by execute(), and onSchedule().
withinDistance() [2/2]
boolean com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.withinDistance (int x, int y, int x2, int y2, int width, int height, int distance) package
Definition at line 214 of file Waypoint.java.
{
        if (x > x2) {
            x2 += Math.min(width, x - x2) - 1;
        }
        if (y > y2) {
            y2 += Math.min(height, y - y2) - 1;
        }
        return Math.abs(x - x2) <= distance && Math.abs(y - y2) <= distance;
    }
Member Data Documentation
lastPosition
Position com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.lastPosition private
Definition at line 23 of file Waypoint.java.
Referenced by execute().
mob
final Mob com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.mob protected
Definition at line 21 of file Waypoint.java.
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.CombatWaypoint(), equals(), execute(), findRoute(), com.runehive.game.world.entity.mob.movement.waypoint.FollowWaypoint.FollowWaypoint(), com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.getRadius(), onCancel(), com.runehive.game.world.entity.combat.strategy.npc.boss.scorpia.Scorpia.GuardianWaypoint.onDestination(), com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.onDestination(), com.runehive.game.world.entity.mob.movement.waypoint.FollowWaypoint.onDestination(), com.runehive.game.world.entity.mob.movement.waypoint.PickupWaypoint.onDestination(), com.runehive.game.world.entity.mob.movement.waypoint.WalkToWaypoint.onDestination(), onSchedule(), com.runehive.game.world.entity.mob.movement.waypoint.WalkToWaypoint.WalkToWaypoint(), Waypoint(), com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.withinDistance(), and withinDistance().
target
Interactable com.runehive.game.world.entity.mob.movement.waypoint.Waypoint.target protected
Definition at line 22 of file Waypoint.java.
Referenced by com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.CombatWaypoint(), equals(), execute(), findRoute(), com.runehive.game.world.entity.mob.movement.waypoint.FollowWaypoint.FollowWaypoint(), com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.getRadius(), getTarget(), onCancel(), com.runehive.game.world.entity.mob.movement.waypoint.WalkToWaypoint.onDestination(), onSchedule(), toString(), com.runehive.game.world.entity.mob.movement.waypoint.WalkToWaypoint.WalkToWaypoint(), Waypoint(), com.runehive.game.world.entity.mob.movement.waypoint.CombatWaypoint.withinDistance(), and withinDistance().
The documentation for this class was generated from the following file:
java/com/runehive/game/world/entity/mob/movement/waypoint/Waypoint.java