RuneHive-Game: com.runehive.content.skill.impl.farming.patches.DiseasablePatch Class Reference
com.runehive.content.skill.impl.farming.patches.DiseasablePatch Class Reference abstract
Public Member Functions
boolean clickObject (int opcode)
void fromJson (JsonObject object)
boolean itemOnObject (Item item, int index)
JsonObject toJson ()
Public Member Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
int getConfig ()
boolean isComposted ()
boolean isDead ()
boolean isDiseased ()
boolean isEmpty ()
boolean isGrowing ()
boolean isNormal ()
boolean isWatered ()
boolean needsWeeding ()
abstract Plant plantForSeed (int seedId)
void setDead ()
void setDiseased ()
void setEmpty ()
void setNormal ()
void setWatered ()
void tick ()
boolean within (Position position)
Protected Member Functions
DiseasablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
void onGrowth ()
void resetPatch ()
Protected Member Functions inherited from com.runehive.content.skill.impl.farming.patches.HarvestablePatch
abstract int animation ()
abstract int getMaxAmount ()
abstract int getMinAmount ()
Protected Attributes
boolean watched
Protected Attributes inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
CompostType compost
boolean fullyGrown
int growth
Plant plant
final Player player
FarmingStage stage = FarmingStage.FULL_WEEDS
FarmingState state = FarmingState.NORMAL
final Stopwatch timer = Stopwatch.start()
final FarmingZone zone
Private Member Functions
void curePlant (int index)
Additional Inherited Members
Package Functions inherited from com.runehive.content.skill.impl.farming.patches.HarvestablePatch
HarvestablePatch (Player player, FarmingZone zone, Interactable[] boundaries)
Constructs a new HarvestablePatch object.
Package Functions inherited from com.runehive.content.skill.impl.farming.patches.FarmingPatch
FarmingPatch (Player player, FarmingZone zone, Interactable[] boundaries)
Detailed Description
Definition at line 11 of file DiseasablePatch.java.
Constructor & Destructor Documentation
DiseasablePatch()
com.runehive.content.skill.impl.farming.patches.DiseasablePatch.DiseasablePatch (Player player, FarmingZone zone, Interactable[] boundaries) protected
Definition at line 14 of file DiseasablePatch.java.
{
        super(player, zone, boundaries);
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.boundaries, com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, and com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone.
Member Function Documentation
clickObject()
boolean com.runehive.content.skill.impl.farming.patches.DiseasablePatch.clickObject (int opcode)
Reimplemented from com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 36 of file DiseasablePatch.java.
{
        if (opcode == 1 && isDiseased()) {
            curePlant(-1);
            return true;
        }
        return super.clickObject(opcode);
    }
References curePlant(), and com.runehive.content.skill.impl.farming.patches.FarmingPatch.isDiseased().
curePlant()
void com.runehive.content.skill.impl.farming.patches.DiseasablePatch.curePlant (int index) private
Definition at line 63 of file DiseasablePatch.java.
{
        if (player.locking.locked()) {
            return;
        }
        if (plant == null) {
            return;
        }
        if (!isDiseased()) {
            player.message("This plant doesn't need to be cured.");
            return;
        }
        if (!player.inventory.contains(FarmingConstants.PLANT_CURE)) {
            player.message("You need plant cure to cure this plant.");
            return;
        }
        if (index != -1) {
            player.inventory.replace(FarmingConstants.PLANT_CURE, 229, index, true);
        } else {
            player.inventory.replace(FarmingConstants.PLANT_CURE, 229, true);
        }
        player.locking.lock(7);
        player.animate(FarmingConstants.CURING_ANIM);
        setNormal();
        World.schedule(7, () -> {
            player.resetAnimation();
            player.message("You cure the plant with a plant cure.");
            zone.sendPatchConfigs(player);
        });
    }
References com.runehive.content.skill.impl.farming.FarmingConstants.CURING_ANIM, com.runehive.content.skill.impl.farming.patches.FarmingPatch.isDiseased(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.plant, com.runehive.content.skill.impl.farming.FarmingConstants.PLANT_CURE, com.runehive.content.skill.impl.farming.patches.FarmingPatch.player, com.runehive.game.world.World.schedule(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.setNormal(), and com.runehive.content.skill.impl.farming.patches.FarmingPatch.zone.
Referenced by clickObject(), and itemOnObject().
fromJson()
void com.runehive.content.skill.impl.farming.patches.DiseasablePatch.fromJson (JsonObject object)
Reimplemented from com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 108 of file DiseasablePatch.java.
{
        watched = object.get("watched").getAsBoolean();
        super.fromJson(object);
    }
References watched.
itemOnObject()
boolean com.runehive.content.skill.impl.farming.patches.DiseasablePatch.itemOnObject (Item item, int index)
Reimplemented from com.runehive.content.skill.impl.farming.patches.FarmingPatch.
Reimplemented in com.runehive.content.skill.impl.farming.patches.impl.FlowerPatch, and com.runehive.content.skill.impl.farming.patches.WaterablePatch.
Definition at line 44 of file DiseasablePatch.java.
{
        if (item.matchesId(FarmingConstants.PLANT_CURE)) {
            curePlant(index);
            return true;
        }
        return super.itemOnObject(item, index);
    }
References curePlant(), com.runehive.game.world.items.Item.matchesId(), and com.runehive.content.skill.impl.farming.FarmingConstants.PLANT_CURE.
onGrowth()
void com.runehive.content.skill.impl.farming.patches.DiseasablePatch.onGrowth () protected
Reimplemented from com.runehive.content.skill.impl.farming.patches.FarmingPatch.
Reimplemented in com.runehive.content.skill.impl.farming.patches.WaterablePatch.
Definition at line 19 of file DiseasablePatch.java.
{
        if (isDead()) {
            return;
        }
      /*  if (isDiseased()) {
            setDead();
        } else if (!fullyGrown) {
            handleDisease();
        }*/
    }
References com.runehive.content.skill.impl.farming.patches.FarmingPatch.isDead().
resetPatch()
void com.runehive.content.skill.impl.farming.patches.DiseasablePatch.resetPatch () protected
Reimplemented from com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 31 of file DiseasablePatch.java.
{
        super.resetPatch();
        watched = false;
    }
References watched.
toJson()
JsonObject com.runehive.content.skill.impl.farming.patches.DiseasablePatch.toJson ()
Reimplemented from com.runehive.content.skill.impl.farming.patches.HarvestablePatch.
Definition at line 101 of file DiseasablePatch.java.
{
        JsonObject object = super.toJson();
        object.addProperty("watched", watched);
        return object;
    }
References watched.
Member Data Documentation
watched
boolean com.runehive.content.skill.impl.farming.patches.DiseasablePatch.watched protected
Definition at line 12 of file DiseasablePatch.java.
Referenced by fromJson(), resetPatch(), and toJson().
The documentation for this class was generated from the following file:
java/com/runehive/content/skill/impl/farming/patches/DiseasablePatch.java