RuneHive-Game: com.runehive.content.dialogue.ChatBoxItemDialogue Class Reference
com.runehive.content.dialogue.ChatBoxItemDialogue Class Reference abstract
Public Member Functions
boolean clickButton (int button)
abstract void firstOption (Player player)
abstract void fourthOption (Player player)
abstract void secondOption (Player player)
abstract void thirdOption (Player player)
Static Public Member Functions
static void sendInterface (Player player, int interfaceId, int item, int x, int y, int zoom)
static void sendInterface (Player player, int interfaceId, int item, int zoom)
static void sendInterface (Player player, int interfaceId, Item item, int zoom)
Protected Member Functions
ChatBoxItemDialogue (Player player)
Private Member Functions
void firstOptionClick (Player player)
void fourthOptionClick (Player player)
void secondOptionClick (Player player)
void thirdOptionClick (Player player)
Private Attributes
final Player player
Detailed Description
Definition at line 11 of file ChatBoxItemDialogue.java.
Constructor & Destructor Documentation
ChatBoxItemDialogue()
com.runehive.content.dialogue.ChatBoxItemDialogue.ChatBoxItemDialogue (Player player) protected
Definition at line 14 of file ChatBoxItemDialogue.java.
{
        this.player = player;
    }
References player.
Member Function Documentation
clickButton()
boolean com.runehive.content.dialogue.ChatBoxItemDialogue.clickButton (int button)
Definition at line 33 of file ChatBoxItemDialogue.java.
{
        switch (button) {
        /* Option 1 */
            case 2799:
                firstOptionClick(player);
                return true;
        /* Option 5 */
            case 2798:
                secondOptionClick(player);
                return true;
        /* Option x */
            case 1748:
                thirdOptionClick(player);
                return true;
        /* Option all */
            case 1747:
                fourthOptionClick(player);
                return true;
        }
        return false;
    }
References firstOptionClick(), fourthOptionClick(), player, secondOptionClick(), and thirdOptionClick().
firstOption()
abstract void com.runehive.content.dialogue.ChatBoxItemDialogue.firstOption (Player player) abstract
References player.
Referenced by firstOptionClick().
firstOptionClick()
void com.runehive.content.dialogue.ChatBoxItemDialogue.firstOptionClick (Player player) private
Definition at line 66 of file ChatBoxItemDialogue.java.
{
        player.interfaceManager.close();
        firstOption(player);
    }
References firstOption(), and player.
Referenced by clickButton().
fourthOption()
abstract void com.runehive.content.dialogue.ChatBoxItemDialogue.fourthOption (Player player) abstract
References player.
Referenced by fourthOptionClick().
fourthOptionClick()
void com.runehive.content.dialogue.ChatBoxItemDialogue.fourthOptionClick (Player player) private
Definition at line 81 of file ChatBoxItemDialogue.java.
{
        player.interfaceManager.close();
        fourthOption(player);
    }
References fourthOption(), and player.
Referenced by clickButton().
secondOption()
abstract void com.runehive.content.dialogue.ChatBoxItemDialogue.secondOption (Player player) abstract
References player.
Referenced by secondOptionClick().
secondOptionClick()
void com.runehive.content.dialogue.ChatBoxItemDialogue.secondOptionClick (Player player) private
Definition at line 71 of file ChatBoxItemDialogue.java.
{
        player.interfaceManager.close();
        secondOption(player);
    }
References player, and secondOption().
Referenced by clickButton().
sendInterface() [1/3]
void com.runehive.content.dialogue.ChatBoxItemDialogue.sendInterface (Player player, int interfaceId, int item, int x, int y, int zoom) static
Definition at line 26 of file ChatBoxItemDialogue.java.
{
        player.send(new SendChatBoxInterface(4429));
        player.send(new SendMoveComponent(x, y, interfaceId));
        player.send(new SendItemModelOnInterface(interfaceId, zoom, item));
        player.send(new SendString("\\n \\n \\n \\n" + ItemDefinition.get(item).getName(), 2799));
    }
References com.runehive.game.world.items.ItemDefinition.get(), com.runehive.game.world.items.ItemDefinition.getName(), and player.
sendInterface() [2/3]
void com.runehive.content.dialogue.ChatBoxItemDialogue.sendInterface (Player player, int interfaceId, int item, int zoom) static
Definition at line 22 of file ChatBoxItemDialogue.java.
{
        sendInterface(player, interfaceId, item, 0, 10, zoom);
    }
References player, and sendInterface().
sendInterface() [3/3]
void com.runehive.content.dialogue.ChatBoxItemDialogue.sendInterface (Player player, int interfaceId, Item item, int zoom) static
Definition at line 18 of file ChatBoxItemDialogue.java.
{
        sendInterface(player, interfaceId, item.getId(), 0, 10, zoom);
    }
References com.runehive.game.world.items.Item.getId(), player, and sendInterface().
Referenced by com.runehive.content.skill.impl.crafting.impl.Spinning.click(), com.runehive.content.skill.impl.crafting.impl.Stringing.craft(), sendInterface(), sendInterface(), com.runehive.content.skill.impl.cooking.Cooking.useItem(), com.runehive.content.skill.impl.herblore.Herblore.useItem(), and com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem().
thirdOption()
abstract void com.runehive.content.dialogue.ChatBoxItemDialogue.thirdOption (Player player) abstract
References player.
Referenced by thirdOptionClick().
thirdOptionClick()
void com.runehive.content.dialogue.ChatBoxItemDialogue.thirdOptionClick (Player player) private
Definition at line 76 of file ChatBoxItemDialogue.java.
{
        player.interfaceManager.close();
        thirdOption(player);
    }
References player, and thirdOption().
Referenced by clickButton().
Member Data Documentation
player
final Player com.runehive.content.dialogue.ChatBoxItemDialogue.player private
Definition at line 12 of file ChatBoxItemDialogue.java.
Referenced by ChatBoxItemDialogue(), clickButton(), firstOption(), firstOptionClick(), fourthOption(), fourthOptionClick(), secondOption(), secondOptionClick(), sendInterface(), sendInterface(), sendInterface(), thirdOption(), and thirdOptionClick().
The documentation for this class was generated from the following file:
java/com/runehive/content/dialogue/ChatBoxItemDialogue.java