RuneHive-Game: com.runehive.content.itemaction.ItemActionRepository Class Reference
com.runehive.content.itemaction.ItemActionRepository Class Reference
Handles execution of the item actions.
Static Public Member Functions
static void declare ()
Declares all the item actions.
static boolean drop (Player player, Item item)
static boolean equipment (Player player, Item item, int opcode)
static boolean inventory (Player player, Item item, int opcode)
static boolean itemOnItem (Player player, Item first, Item second)
Static Public Attributes
static HashMap< Integer, ItemAction > ACTIONS = new HashMap<>()
Map of all the item actions.
Detailed Description
Handles execution of the item actions.
Author
Daniel
Definition at line 14 of file ItemActionRepository.java.
Member Function Documentation
declare()
void com.runehive.content.itemaction.ItemActionRepository.declare () static
Declares all the item actions.
Definition at line 20 of file ItemActionRepository.java.
{
        ACTIONS.put(12_931, new SerpentineHelm()); // charged
        ACTIONS.put(12_929, new SerpentineHelm()); // uncharged
        ACTIONS.put(13_196, new TanzaniteHelm()); // charged
        ACTIONS.put(13_197, new TanzaniteHelm()); // uncharged
        ACTIONS.put(13_198, new MagmaHelm()); // charged
        ACTIONS.put(13_199, new MagmaHelm()); // uncharged
        ACTIONS.put(11283, new DragonfireShield()); // charged
        ACTIONS.put(11284, new DragonfireShield()); // uncharged
        ACTIONS.put(12924, new ToxicBlowpipe()); // uncharged
        ACTIONS.put(12926, new ToxicBlowpipe()); // charged
        ACTIONS.put(11907, new TridentOfTheSeas()); // charged
        ACTIONS.put(12899, new TridentOfTheSwamp()); // charged
        ACTIONS.put((int) CrawsBow.CRAWS_UNCHARGED_ID, new CrawsBow()); // uncharged
        ACTIONS.put((int) CrawsBow.CRAWS_CHARGED_ID, new CrawsBow()); // charged
        ACTIONS.put((int) ViggorasChainmace.VIGGORAS_CHAINMACE_UNCHARGED_ID, new ViggorasChainmace()); // uncharged
        ACTIONS.put((int) ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID, new ViggorasChainmace()); // charged
        ACTIONS.put((int) ThammaronsSceptre.THAMMARONS_SCEPTRE_UNCHARGED_ID, new ThammaronsSceptre()); // uncharged
        ACTIONS.put((int) ThammaronsSceptre.THAMMARONS_SCEPTRE_CHARGED_ID, new ThammaronsSceptre()); // charged
        ACTIONS.put((int) CelestialRing.UNCHARGED_RING, new CelestialRing()); // uncharged
        ACTIONS.put((int) CelestialRing.CHARGED_RING, new CelestialRing()); // charged
        ACTIONS.put(6831, new MimeBox());
        ACTIONS.put(6832, new DrillDemonBox());
        ACTIONS.put(12897, new ClanShowcaseBox());
        ACTIONS.put(6854, new ClanResourceBox());
//        ACTIONS.put(1704, new AmuletOfGlory());
//        ACTIONS.put(1706, new AmuletOfGlory());
//        ACTIONS.put(1708, new AmuletOfGlory());
//        ACTIONS.put(1710, new AmuletOfGlory());
//        ACTIONS.put(1712, new AmuletOfGlory());
//        ACTIONS.put(1714, new AmuletOfGlory());
//        ACTIONS.put(11978, new AmuletOfGlory());
//        ACTIONS.put(11978, new AmuletOfGlory());
//        ACTIONS.put(2566, new RingOfDueling());
//        ACTIONS.put(2564, new RingOfDueling());
//        ACTIONS.put(2562, new RingOfDueling());
//        ACTIONS.put(2560, new RingOfDueling());
//        ACTIONS.put(2558, new RingOfDueling());
//        ACTIONS.put(2556, new RingOfDueling());
//        ACTIONS.put(2554, new RingOfDueling());
//        ACTIONS.put(2552, new RingOfDueling());
    }
References ACTIONS, com.runehive.content.itemaction.impl.CelestialRing.CHARGED_RING, com.runehive.content.itemaction.impl.CrawsBow.CRAWS_CHARGED_ID, com.runehive.content.itemaction.impl.CrawsBow.CRAWS_UNCHARGED_ID, com.runehive.content.itemaction.impl.ThammaronsSceptre.THAMMARONS_SCEPTRE_CHARGED_ID, com.runehive.content.itemaction.impl.ThammaronsSceptre.THAMMARONS_SCEPTRE_UNCHARGED_ID, com.runehive.content.itemaction.impl.CelestialRing.UNCHARGED_RING, com.runehive.content.itemaction.impl.ViggorasChainmace.VIGGORAS_CHAINMACE_CHARGED_ID, and com.runehive.content.itemaction.impl.ViggorasChainmace.VIGGORAS_CHAINMACE_UNCHARGED_ID.
Referenced by com.runehive.RuneHive.processParallelStartupTasks().
drop()
boolean com.runehive.content.itemaction.ItemActionRepository.drop (Player player, Item item) static
Definition at line 90 of file ItemActionRepository.java.
{
        ItemAction action = ACTIONS.get(item.getId());
        return action != null && action.drop(player, item);
    }
References ACTIONS, com.runehive.content.itemaction.ItemAction.drop(), and com.runehive.game.world.items.Item.getId().
Referenced by com.runehive.net.packet.in.DropItemPacketListener.handlePacket().
equipment()
boolean com.runehive.content.itemaction.ItemActionRepository.equipment (Player player, Item item, int opcode) static
Definition at line 85 of file ItemActionRepository.java.
{
        ItemAction action = ACTIONS.get(item.getId());
        return action != null && action.equipment(player, item, opcode);
    }
References ACTIONS, com.runehive.content.itemaction.ItemAction.equipment(), and com.runehive.game.world.items.Item.getId().
inventory()
boolean com.runehive.content.itemaction.ItemActionRepository.inventory (Player player, Item item, int opcode) static
Definition at line 80 of file ItemActionRepository.java.
{
        ItemAction action = ACTIONS.get(item.getId());
        return action != null && action.inventory(player, item, opcode);
    }
References ACTIONS, com.runehive.game.world.items.Item.getId(), and com.runehive.content.itemaction.ItemAction.inventory().
Referenced by com.runehive.net.packet.in.ItemOptionPacketListener.handleFirstOption(), com.runehive.net.packet.in.ItemOptionPacketListener.handleSecondOption(), and com.runehive.net.packet.in.ItemOptionPacketListener.handleThirdOption().
itemOnItem()
boolean com.runehive.content.itemaction.ItemActionRepository.itemOnItem (Player player, Item first, Item second) static
Definition at line 75 of file ItemActionRepository.java.
{
        ItemAction action = ACTIONS.getOrDefault(first.getId(), ACTIONS.get(second.getId()));
        return action != null && action.itemOnItem(player, first, second);
    }
References ACTIONS, com.runehive.game.world.items.Item.getId(), and com.runehive.content.itemaction.ItemAction.itemOnItem().
Referenced by com.runehive.net.packet.in.UseItemPacketListener.handleItemOnItem().
Member Data Documentation
ACTIONS
HashMap<Integer, ItemAction> com.runehive.content.itemaction.ItemActionRepository.ACTIONS = new HashMap<>() static
Map of all the item actions.
Definition at line 17 of file ItemActionRepository.java.
Referenced by declare(), drop(), equipment(), inventory(), and itemOnItem().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/ItemActionRepository.java