RuneHive-Game: com.runehive.content.itemaction.impl.MagmaHelm Class Reference
com.runehive.content.itemaction.impl.MagmaHelm Class Reference
Public Member Functions
boolean drop (Player player, Item item)
boolean equipment (Player player, Item item, int opcode)
boolean inventory (Player player, Item item, int opcode)
The execution method of the action.
boolean itemOnItem (Player player, Item first, Item second)
MagmaHelm ()
String name ()
The name of the action.
Public Member Functions inherited from com.runehive.content.itemaction.ItemAction
int delay ()
The item click delay of the action.
String message (Item item)
The message of the action.
String toString ()
Static Public Member Functions
static void check (Player player)
Static Private Member Functions
static void charge (Player player, Item helm, Item scales)
static void restore (Player player, Item item)
static void uncharge (Player player)
Static Private Attributes
static final short CHARGED_HELM = 13_199
static final DecimalFormat FORMATTER = new DecimalFormat("#.#")
static final short FULL = 11_000
static final short UNCHARGED_HELM = 13_198
static final short ZULRAH_SCALES = 12_934
Detailed Description
Definition at line 15 of file MagmaHelm.java.
Constructor & Destructor Documentation
MagmaHelm()
com.runehive.content.itemaction.impl.MagmaHelm.MagmaHelm ()
Definition at line 25 of file MagmaHelm.java.
                       {
        FORMATTER.setRoundingMode(RoundingMode.FLOOR);
    }
References FORMATTER.
Member Function Documentation
charge()
void com.runehive.content.itemaction.impl.MagmaHelm.charge (Player player, Item helm, Item scales) static private
Definition at line 86 of file MagmaHelm.java.
{
        if (player.magmaHelmCharges >= FULL) {
            if (helm.matchesId(UNCHARGED_HELM)) {
                player.inventory.replace(UNCHARGED_HELM, CHARGED_HELM, true);
            }
            player.message("Your Magma helm is already fully charged.");
            return;
        }
        if (Integer.MAX_VALUE - scales.getAmount() < FULL) {
            scales = scales.copy();
            scales.setAmount(FULL - player.magmaHelmCharges);
        }
        if (player.magmaHelmCharges + scales.getAmount() > FULL) {
            scales = scales.copy();
            scales.setAmount(FULL - player.magmaHelmCharges);
        }
        player.magmaHelmCharges += scales.getAmount();
        player.inventory.remove(scales);
        player.inventory.replace(UNCHARGED_HELM, CHARGED_HELM, true);
        player.message(String.format("You load %s scales into your Magma helm.", Utility.formatDigits(scales.getAmount())));
    }
References CHARGED_HELM, com.runehive.game.world.items.Item.copy(), com.runehive.util.Utility.formatDigits(), FULL, com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.magmaHelmCharges, com.runehive.game.world.items.Item.matchesId(), com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.remove(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.items.Item.setAmount(), and UNCHARGED_HELM.
Referenced by itemOnItem().
check()
void com.runehive.content.itemaction.impl.MagmaHelm.check (Player player) static
Definition at line 81 of file MagmaHelm.java.
{
        String scales = FORMATTER.format(player.magmaHelmCharges * 100 / FULL) + "%";
        player.message("Charges: <col=007F00>" + scales);
    }
References FORMATTER, FULL, com.runehive.game.world.entity.mob.player.Player.magmaHelmCharges, and com.runehive.game.world.entity.mob.player.Player.message().
Referenced by equipment(), and inventory().
drop()
boolean com.runehive.content.itemaction.impl.MagmaHelm.drop (Player player, Item item)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 73 of file MagmaHelm.java.
{
        if (item.matchesId(CHARGED_HELM)) {
            uncharge(player);
            return true;
        }
        return false;
    }
References CHARGED_HELM, com.runehive.game.world.items.Item.matchesId(), and uncharge().
equipment()
boolean com.runehive.content.itemaction.impl.MagmaHelm.equipment (Player player, Item item, int opcode)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 65 of file MagmaHelm.java.
{
        if (opcode == 1) {
            check(player);
        }
        return true;
    }
References check().
inventory()
boolean com.runehive.content.itemaction.impl.MagmaHelm.inventory (Player player, Item item, int opcode)
The execution method of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 51 of file MagmaHelm.java.
{
        if (opcode == 3) {
            restore(player, item);
            return true;
        }
        if (opcode == 2) {
            check(player);
        }
        return true;
    }
References check(), and restore().
itemOnItem()
boolean com.runehive.content.itemaction.impl.MagmaHelm.itemOnItem (Player player, Item first, Item second)
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 35 of file MagmaHelm.java.
{
        Item item = first;
        if (first.getId() == UNCHARGED_HELM || first.getId() == CHARGED_HELM) {
            item = second;
        }
        if (item.getId() == ZULRAH_SCALES) {
            charge(player, item.equals(first) ? second : first, item);
            return true;
        }
        return false;
    }
References charge(), CHARGED_HELM, com.runehive.game.world.items.Item.equals(), com.runehive.game.world.items.Item.getId(), UNCHARGED_HELM, and ZULRAH_SCALES.
name()
String com.runehive.content.itemaction.impl.MagmaHelm.name ()
The name of the action.
Reimplemented from com.runehive.content.itemaction.ItemAction.
Definition at line 30 of file MagmaHelm.java.
{
        return "Magma helm";
    }
restore()
void com.runehive.content.itemaction.impl.MagmaHelm.restore (Player player, Item item) static private
Definition at line 125 of file MagmaHelm.java.
{
        player.send(new SendItemOnInterfaceSlot(14171, item, 0));
        player.send(new SendString("Are you sure you want to restore this item?", 14174));
        player.send(new SendString("Yes.", 14175));
        player.send(new SendString("No.", 14176));
        player.send(new SendString("", 14177));
        player.send(new SendString("This will replace your helm with the original Serpentine helm.", 14182));
        player.send(new SendString("", 14183));
        player.send(new SendString(item.getName(), 14184));
        player.send(new SendChatBoxInterface(14170));
        player.attributes.set("RESTORE_HELM_KEY", item);
    }
References com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.util.generic.GenericAttributes.set().
Referenced by inventory().
uncharge()
void com.runehive.content.itemaction.impl.MagmaHelm.uncharge (Player player) static private
Definition at line 111 of file MagmaHelm.java.
{
        Item scales = new Item(ZULRAH_SCALES, player.magmaHelmCharges);
        if (!player.inventory.hasCapacityFor(scales)) {
            player.send(new SendMessage("You need more inventory space to do this."));
            return;
        }
        player.magmaHelmCharges = 0;
        player.inventory.add(scales);
        player.inventory.replace(CHARGED_HELM, UNCHARGED_HELM, true);
        player.message(String.format("You uncharged your Magma helm and received %s of Zulra's scales.", Utility.formatDigits(scales.getAmount())));
    }
References com.runehive.game.world.items.containers.ItemContainer.add(), CHARGED_HELM, com.runehive.util.Utility.formatDigits(), com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.containers.ItemContainer.hasCapacityFor(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.magmaHelmCharges, com.runehive.game.world.entity.mob.player.Player.message(), com.runehive.game.world.items.containers.ItemContainer.replace(), com.runehive.game.world.entity.mob.player.Player.send(), UNCHARGED_HELM, and ZULRAH_SCALES.
Referenced by drop().
Member Data Documentation
CHARGED_HELM
final short com.runehive.content.itemaction.impl.MagmaHelm.CHARGED_HELM = 13_199 static private
Definition at line 21 of file MagmaHelm.java.
Referenced by charge(), drop(), itemOnItem(), and uncharge().
FORMATTER
final DecimalFormat com.runehive.content.itemaction.impl.MagmaHelm.FORMATTER = new DecimalFormat("#.#") static private
Definition at line 23 of file MagmaHelm.java.
Referenced by check(), and MagmaHelm().
FULL
final short com.runehive.content.itemaction.impl.MagmaHelm.FULL = 11_000 static private
Definition at line 16 of file MagmaHelm.java.
Referenced by charge(), and check().
UNCHARGED_HELM
final short com.runehive.content.itemaction.impl.MagmaHelm.UNCHARGED_HELM = 13_198 static private
Definition at line 20 of file MagmaHelm.java.
Referenced by charge(), itemOnItem(), and uncharge().
ZULRAH_SCALES
final short com.runehive.content.itemaction.impl.MagmaHelm.ZULRAH_SCALES = 12_934 static private
Definition at line 18 of file MagmaHelm.java.
Referenced by itemOnItem(), and uncharge().
The documentation for this class was generated from the following file:
java/com/runehive/content/itemaction/impl/MagmaHelm.java