RuneHive-Game: com.runehive.content.tittle.TitleManager Class Reference
com.runehive.content.tittle.TitleManager Class Reference
Handles unlocking player titles.
Static Public Member Functions
static boolean click (Player player, int button)
Handles clicking buttons on the title itemcontainer.
static void open (Player player)
Opens the title itemcontainer.
static void redeem (Player player)
Handles a player redeeming a title.
static void refresh (Player player)
Handles refreshing (send all strings and data) the itemcontainer.
static void reset (Player player)
Handles reseting the player title.
Static Private Attributes
static final int BUTTON_IDENTIFICATION = -26485
The base button identification.
Detailed Description
Handles unlocking player titles.
Author
Daniel
Definition at line 13 of file TitleManager.java.
Member Function Documentation
click()
boolean com.runehive.content.tittle.TitleManager.click (Player player, int button) static
Handles clicking buttons on the title itemcontainer.
Definition at line 25 of file TitleManager.java.
{
        int ordinal = (button - BUTTON_IDENTIFICATION) / 2;
        if (Title.forOrdinal(ordinal).isPresent()) {
            player.attributes.set("PLAYER_TITLE_KEY", ordinal);
            refresh(player);
            return true;
        }
        return false;
    }
References com.runehive.game.world.entity.mob.Mob.attributes, BUTTON_IDENTIFICATION, com.runehive.content.tittle.Title.forOrdinal(), refresh(), and com.runehive.util.generic.GenericAttributes.set().
open()
void com.runehive.content.tittle.TitleManager.open (Player player) static
Opens the title itemcontainer.
Definition at line 19 of file TitleManager.java.
{
        refresh(player);
        player.interfaceManager.open(39_000);
    }
References com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.mob.player.InterfaceManager.open(), and refresh().
Referenced by com.runehive.game.plugin.PluginContext.onClick().
redeem()
void com.runehive.content.tittle.TitleManager.redeem (Player player) static
Handles a player redeeming a title.
Definition at line 69 of file TitleManager.java.
{
        int ordinal = player.attributes.get("PLAYER_TITLE_KEY", Integer.class);
        if (Title.forOrdinal(ordinal).isPresent()) {
            Title title = Title.forOrdinal(ordinal).get();
            if (!title.activated(player)) {
                player.send(new SendMessage("You have not activated this title yet!"));
                return;
            }
            player.playerTitle = title.getTitle();
            player.updateFlags.add(UpdateFlag.APPEARANCE);
            player.send(new SendMessage("You have successfully redeemed your title."));
        }
    }
References com.runehive.util.generic.BooleanInterface< T >.activated(), com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.tittle.Title.forOrdinal(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.content.tittle.Title.getTitle(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.updateFlags.
refresh()
void com.runehive.content.tittle.TitleManager.refresh (Player player) static
Handles refreshing (send all strings and data) the itemcontainer.
Definition at line 36 of file TitleManager.java.
{
        int ordinal = player.attributes.get("PLAYER_TITLE_KEY", Integer.class);
        int string = 39_052;
        int config = 750;
        Title view = null;
        for (Title title : Title.values()) {
            if (title.ordinal() == ordinal) {
                view = title;
            }
            player.send(new SendString((title.ordinal() == ordinal ? "<col=DEB07A>" : "<col=A8865E>") + title.getTitle().getTitle(), string));
            player.send(new SendTooltip("View title: <col=db9423>" + title.getTitle().getTitle() + "</col>", string - 1));
            player.send(new SendConfig(config, title.activated(player) ? 1 : 0));
            string += 2;
            config += 2;
        }
        if (view == null) {
            return;
        }
        String color = Integer.toHexString(view.getTitle().getColor());
        int scroll = Title.values().length * 26;
        for (int index = 0; index < view.getRequirement().length; index++) {
            player.send(new SendString(view.getRequirement()[index], 39006 + index));
        }
        player.send(new SendString("<col=" + (view.activated(player) ? "A1D490>- UNLOCKED -" : "E34F52>- LOCKED -"), 39019));
        player.send(new SendString("<col=" + color + ">" + view.getTitle().getTitle() + "<col=DEB07A> " + Utility.formatName(player.getName()), 39_003));
        player.send(new SendScrollbar(39_050, scroll));
    }
References com.runehive.util.generic.BooleanInterface< T >.activated(), com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.util.Utility.formatName(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.content.tittle.PlayerTitle.getColor(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.content.tittle.Title.getRequirement(), com.runehive.content.tittle.PlayerTitle.getTitle(), com.runehive.content.tittle.Title.getTitle(), and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by click(), and open().
reset()
void com.runehive.content.tittle.TitleManager.reset (Player player) static
Handles reseting the player title.
Definition at line 85 of file TitleManager.java.
{
        player.playerTitle = PlayerTitle.empty();
        player.updateFlags.add(UpdateFlag.APPEARANCE);
        player.send(new SendMessage("You have successfully reset your title."));
    }
References com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.tittle.PlayerTitle.empty(), com.runehive.game.world.entity.mob.player.Player.send(), and com.runehive.game.world.entity.mob.Mob.updateFlags.
Member Data Documentation
BUTTON_IDENTIFICATION
final int com.runehive.content.tittle.TitleManager.BUTTON_IDENTIFICATION = -26485 static private
The base button identification.
Definition at line 16 of file TitleManager.java.
Referenced by click().
The documentation for this class was generated from the following file:
java/com/runehive/content/tittle/TitleManager.java