RuneHive-Game: com.runehive.content.staff.PlayerManagement Enum Reference
com.runehive.content.staff.PlayerManagement Enum Reference
Handles the player management.
Public Member Functions
PlayerManagement (String string)
Public Member Functions inherited from com.runehive.content.staff.ActionEffect
void handle (final Player player)
Handles the execute of the staff panel action.
Static Public Member Functions
static void confirm (Player player, Runnable runnable)
static PlayerManagement forOrdinal (int ordinal)
Public Attributes
CHANGE_USERNAME
CHECK_BANK
CLEAR
COPY
COPY_ME
DEMOTE
JAIL
KICK
LINKED_ACCOUNTS
MOVE_HOME
MUTE
PNPCS
PROMOTE
final String string
TELEPORT_TO
TELEPORT_TO_ME
UNJAIL
UNMUTE
Detailed Description
Handles the player management.
Author
Daniel
Definition at line 32 of file PlayerManagement.java.
Constructor & Destructor Documentation
PlayerManagement()
com.runehive.content.staff.PlayerManagement.PlayerManagement (String string)
Definition at line 336 of file PlayerManagement.java.
{
        this.string = string;
    }
References string.
Referenced by forOrdinal().
Member Function Documentation
confirm()
void com.runehive.content.staff.PlayerManagement.confirm (Player player, Runnable runnable) static
Definition at line 340 of file PlayerManagement.java.
{
        DialogueFactory factory = player.dialogueFactory;
        factory.sendStatement("Are you sure you want to execute this action?");
        factory.sendOption("Confirm action", runnable, "Nevermind", factory::clear);
        factory.execute();
    }
References com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.content.dialogue.DialogueFactory.sendOption(), and com.runehive.content.dialogue.DialogueFactory.sendStatement().
forOrdinal()
PlayerManagement com.runehive.content.staff.PlayerManagement.forOrdinal (int ordinal) static
Definition at line 347 of file PlayerManagement.java.
{
        for (PlayerManagement management : values()) {
            if (management.ordinal() == ordinal) {
                return management;
            }
        }
        return null;
    }
References PlayerManagement().
Member Data Documentation
CHANGE_USERNAME
com.runehive.content.staff.PlayerManagement.CHANGE_USERNAME
Initial value:
=(PlayerRight.getColor(OWNER) + "Change Username") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isOwner(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.send(new SendInputMessage("Enter their new username", 12, input -> {
                    if (ProfileRepository.exist(input)) {
                        player.dialogueFactory.sendStatement("The name " + input + " is already taken.").execute();
                        return;
                    }
                    other.setUsername(input);
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                    PlayerSerializer.save(other);
                    player.dialogueFactory.sendStatement("You have successfully changed their username.").execute();
                }));
            }
        }
    }
Definition at line 313 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isOwner(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.send(new SendInputMessage("Enter their new username", 12, input -> {
                    if (ProfileRepository.exist(input)) {
                        player.dialogueFactory.sendStatement("The name " + input + " is already taken.").execute();
                        return;
                    }
                    other.setUsername(input);
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                    PlayerSerializer.save(other);
                    player.dialogueFactory.sendStatement("You have successfully changed their username.").execute();
                }));
            }
        }
    },;
CHECK_BANK
com.runehive.content.staff.PlayerManagement.CHECK_BANK
Initial value:
=(PlayerRight.getColor(MODERATOR) + "Check Bank") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                long totalValue = other.bank.containerValue(PriceType.VALUE);
                long vaultCoins = other.bankVault.coinsContainer;
                long vaultBM = other.bankVault.bloodMoneyContainer;
                player.interfaceManager.openInventory(60000, 5063);
                player.send(new SendItemOnInterface(InterfaceConstants.WITHDRAW_BANK, other.bank.tabAmounts, other.bank.toArray()));
                player.send(new SendItemOnInterface(InterfaceConstants.INVENTORY_STORE, other.inventory.toArray()));
                player.send(new SendString("", 60_079));
                player.dialogueFactory.sendInformationBox(other.getName() + "'s Bank:", "Bank Value: " + (totalValue), "Bank Vault (Coins): " + (vaultCoins), "Bank Vault (BM): " + (vaultBM)).execute();
            }
        }
    }
Definition at line 176 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                long totalValue = other.bank.containerValue(PriceType.VALUE);
                long vaultCoins = other.bankVault.coinsContainer;
                long vaultBM = other.bankVault.bloodMoneyContainer;
                player.interfaceManager.openInventory(60000, 5063);
                player.send(new SendItemOnInterface(InterfaceConstants.WITHDRAW_BANK, other.bank.tabAmounts, other.bank.toArray()));
                player.send(new SendItemOnInterface(InterfaceConstants.INVENTORY_STORE, other.inventory.toArray()));
                player.send(new SendString("", 60_079));
                player.dialogueFactory.sendInformationBox(other.getName() + "'s Bank:", "Bank Value: " + (totalValue), "Bank Vault (Coins): " + (vaultCoins), "Bank Vault (BM): " + (vaultBM)).execute();
            }
        }
    },
CLEAR
com.runehive.content.staff.PlayerManagement.CLEAR
Initial value:
=(PlayerRight.getColor(OWNER) + "Clear Account") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isOwner(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                confirm(player, () -> {
                    other.bank.clear();
                    other.inventory.clear();
                    for (int index = 0; index < Skill.SKILL_COUNT; index++) {
                        other.skills.setLevel(index, index == 3 ? 10 : 1);
                        other.skills.setMaxLevel(index, index == 3 ? 10 : 1);
                    }
                    other.skills.setCombatLevel();
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                });
            }
        }
    }
Definition at line 276 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isOwner(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                confirm(player, () -> {
                    other.bank.clear();
                    other.inventory.clear();
                    for (int index = 0; index < Skill.SKILL_COUNT; index++) {
                        other.skills.setLevel(index, index == 3 ? 10 : 1);
                        other.skills.setMaxLevel(index, index == 3 ? 10 : 1);
                    }
                    other.skills.setCombatLevel();
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                });
            }
        }
    },
COPY
com.runehive.content.staff.PlayerManagement.COPY
Initial value:
=(PlayerRight.getColor(ADMINISTRATOR) + "Copy") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isAdministrator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.playerAssistant.copy(other);
                player.updateFlags.add(UpdateFlag.APPEARANCE);
                player.message("<col=FF0D5D>You have copied " + other.getName() + ".");
            }
        }
    }
Definition at line 252 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isAdministrator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.playerAssistant.copy(other);
                player.updateFlags.add(UpdateFlag.APPEARANCE);
                player.message("<col=FF0D5D>You have copied " + other.getName() + ".");
            }
        }
    },
COPY_ME
com.runehive.content.staff.PlayerManagement.COPY_ME
Initial value:
=(PlayerRight.getColor(OWNER) + "Copy Me") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isOwner(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.playerAssistant.copy(player);
                other.updateFlags.add(UpdateFlag.APPEARANCE);
                player.message("<col=FF0D5D>You have X-copied " + other.getName() + ".");
            }
        }
    }
Definition at line 264 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isOwner(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.playerAssistant.copy(player);
                other.updateFlags.add(UpdateFlag.APPEARANCE);
                player.message("<col=FF0D5D>You have X-copied " + other.getName() + ".");
            }
        }
    },
DEMOTE
com.runehive.content.staff.PlayerManagement.DEMOTE
Initial value:
=(PlayerRight.getColor(ADMINISTRATOR) + "Demote") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isAdministrator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.right = PlayerRight.PLAYER;
                other.updateFlags.add(UpdateFlag.APPEARANCE);
                other.dialogueFactory.sendStatement("You were demoted by " + player.getName()).execute();
                player.message("You have demoted " + other.getName() + ".");
            }
        }
    }
Definition at line 239 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isAdministrator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.right = PlayerRight.PLAYER;
                other.updateFlags.add(UpdateFlag.APPEARANCE);
                other.dialogueFactory.sendStatement("You were demoted by " + player.getName()).execute();
                player.message("You have demoted " + other.getName() + ".");
            }
        }
    },
JAIL
com.runehive.content.staff.PlayerManagement.JAIL
Definition at line 84 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                confirm(player, () -> {
                    DialogueFactory factory = player.dialogueFactory;
                    factory.sendOption("Jail by day", () -> {
                        factory.onAction(() -> player.send(new SendInputAmount("How long do you want this jail to last for?", 2, input -> {
                            other.punishment.jail(Integer.parseInt(input), TimeUnit.DAYS);
                            factory.clear();
                        })));
                    }, "Jail by hour", () -> {
                        factory.onAction(() -> player.send(new SendInputAmount("How long do you want this jail to last for?", 3, input -> {
                            other.punishment.jail(Integer.parseInt(input), TimeUnit.HOURS);
                            factory.clear();
                        })));
                    }, "Jail by minute", () -> {
                        factory.onAction(() -> player.send(new SendInputAmount("How long do you want this jail to last for?", 3, input -> {
                            other.punishment.jail(Integer.parseInt(input), TimeUnit.MINUTES);
                            factory.clear();
                        })));
                    }, "Jail forever", () -> {
                        factory.onAction(() -> {
                            other.punishment.jail(9999, TimeUnit.DAYS);
                            factory.clear();
                        });
                    });
                });
            }
        }
    },
KICK
com.runehive.content.staff.PlayerManagement.KICK
Initial value:
=(PlayerRight.getColor(MODERATOR) + "Kick") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                confirm(player, () -> {
                    World.kickPlayer(other);
                    player.message("<col=FF0D5D>You have force kicked: " + other.getName() + ".");
                });
            }
        }
    }
Definition at line 71 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                confirm(player, () -> {
                    World.kickPlayer(other);
                    player.message("<col=FF0D5D>You have force kicked: " + other.getName() + ".");
                });
            }
        }
    },
LINKED_ACCOUNTS
com.runehive.content.staff.PlayerManagement.LINKED_ACCOUNTS
Initial value:
=(PlayerRight.getColor(MODERATOR) + "Linked Accounts") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                List<String> list = ProfileRepository.getRegistry(other.lastHost);
                if (!list.isEmpty()) {
                    for (int index = 0; index < 50; index++) {
                        String name = index >= list.size() ? "" : list.get(index);
                        player.send(new SendString(name, 37111 + index));
                    }
                    player.message("<col=FF0D5D>There are " + list.size() + " accounts linked to " + Utility.formatName(other.getName()) + ".");
                    player.send(new SendString("Profiles:\\n" + list.size(), 37107));
                    player.send(new SendString(other.getName(), 37103));
                    player.interfaceManager.open(37100);
                }
            }
        }
    }
Definition at line 193 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                List<String> list = ProfileRepository.getRegistry(other.lastHost);
                if (!list.isEmpty()) {
                    for (int index = 0; index < 50; index++) {
                        String name = index >= list.size() ? "" : list.get(index);
                        player.send(new SendString(name, 37111 + index));
                    }
                    player.message("<col=FF0D5D>There are " + list.size() + " accounts linked to " + Utility.formatName(other.getName()) + ".");
                    player.send(new SendString("Profiles:\\n" + list.size(), 37107));
                    player.send(new SendString(other.getName(), 37103));
                    player.interfaceManager.open(37100);
                }
            }
        }
    },
MOVE_HOME
com.runehive.content.staff.PlayerManagement.MOVE_HOME
Initial value:
=(PlayerRight.getColor(MODERATOR) + "Move Home") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.move(Config.DEFAULT_POSITION);
                other.instance = Mob.DEFAULT_INSTANCE;
                other.pvpInstance = false;
                other.message("<col=FF0D5D>You have been force teleported home by " + player.getName() + ".");
            }
        }
    }
Definition at line 58 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.move(Config.DEFAULT_POSITION);
                other.instance = Mob.DEFAULT_INSTANCE;
                other.pvpInstance = false;
                other.message("<col=FF0D5D>You have been force teleported home by " + player.getName() + ".");
            }
        }
    },
MUTE
com.runehive.content.staff.PlayerManagement.MUTE
Definition at line 130 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                confirm(player, () -> {
                    DialogueFactory factory = player.dialogueFactory;
                    factory.sendOption("Mute by day", () -> {
                        factory.onAction(() -> player.send(new SendInputAmount("How long do you want this mute to last for?", 2, input -> {
                            other.punishment.mute(Integer.parseInt(input), TimeUnit.DAYS);
                            factory.clear();
                        })));
                    }, "Mute by hour", () -> {
                        factory.onAction(() -> player.send(new SendInputAmount("How long do you want this mute to last for?", 3, input -> {
                            other.punishment.mute(Integer.parseInt(input), TimeUnit.HOURS);
                            factory.clear();
                        })));
                    }, "Mute by minute", () -> {
                        factory.onAction(() -> player.send(new SendInputAmount("How long do you want this mute to last for?", 3, input -> {
                            other.punishment.mute(Integer.parseInt(input), TimeUnit.MINUTES);
                            factory.clear();
                        })));
                    }, "Mute forever", () -> {
                        factory.onAction(() -> {
                            other.punishment.mute(9999, TimeUnit.DAYS);
                            factory.clear();
                        });
                    });
                });
            }
        }
    },
PNPCS
com.runehive.content.staff.PlayerManagement.PNPCS
Initial value:
=(PlayerRight.getColor(OWNER) + "Transform") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isOwner(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.send(new SendInputAmount("Enter NPC ID:", 4, input -> {
                    int id = Integer.parseInt(input);
                    if (id == 0)
                        id = -1;
                    other.playerAssistant.transform(id);
                    player.message("<col=FF0D5D>You have turned " + other.getName() + " into " + NpcDefinition.get(id).getName() + ".");
                }));
            }
        }
    }
Definition at line 297 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isOwner(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.send(new SendInputAmount("Enter NPC ID:", 4, input -> {
                    int id = Integer.parseInt(input);
                    if (id == 0)
                        id = -1;
                    other.playerAssistant.transform(id);
                    player.message("<col=FF0D5D>You have turned " + other.getName() + " into " + NpcDefinition.get(id).getName() + ".");
                }));
            }
        }
    },
PROMOTE
com.runehive.content.staff.PlayerManagement.PROMOTE
Initial value:
=(PlayerRight.getColor(ADMINISTRATOR) + "Promote") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isAdministrator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.dialogueFactory.sendOption("Helper", () -> {
                    other.right = PlayerRight.HELPER;
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                    other.dialogueFactory.sendStatement("You were promoted to helper by " + player.getName()).execute();
                    player.message("You have promoted " + other.getName() + " to helper.");
                }, "Moderator", () -> {
                    other.right = PlayerRight.MODERATOR;
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                    other.dialogueFactory.sendStatement("You were promoted to moderator by " + player.getName()).execute();
                    player.message("You have promoted " + other.getName() + " to moderator.");
                }, "Administrator", () -> {
                    other.right = PlayerRight.ADMINISTRATOR;
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                    other.dialogueFactory.sendStatement("You were promoted to administrator by " + player.getName()).execute();
                    player.message("You have promoted " + other.getName() + " to administrator.");
                }).execute();
            }
        }
    }
Definition at line 214 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isAdministrator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.dialogueFactory.sendOption("Helper", () -> {
                    other.right = PlayerRight.HELPER;
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                    other.dialogueFactory.sendStatement("You were promoted to helper by " + player.getName()).execute();
                    player.message("You have promoted " + other.getName() + " to helper.");
                }, "Moderator", () -> {
                    other.right = PlayerRight.MODERATOR;
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                    other.dialogueFactory.sendStatement("You were promoted to moderator by " + player.getName()).execute();
                    player.message("You have promoted " + other.getName() + " to moderator.");
                }, "Administrator", () -> {
                    other.right = PlayerRight.ADMINISTRATOR;
                    other.updateFlags.add(UpdateFlag.APPEARANCE);
                    other.dialogueFactory.sendStatement("You were promoted to administrator by " + player.getName()).execute();
                    player.message("You have promoted " + other.getName() + " to administrator.");
                }).execute();
            }
        }
    },
string
final String com.runehive.content.staff.PlayerManagement.string
Definition at line 334 of file PlayerManagement.java.
Referenced by PlayerManagement().
TELEPORT_TO
com.runehive.content.staff.PlayerManagement.TELEPORT_TO
Initial value:
=(PlayerRight.getColor(MODERATOR) + "Teleport To") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.move(other.getPosition());
                player.instance = other.instance;
                player.pvpInstance = other.pvpInstance;
            }
        }
    }
Definition at line 33 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                player.move(other.getPosition());
                player.instance = other.instance;
                player.pvpInstance = other.pvpInstance;
            }
        }
    },
TELEPORT_TO_ME
com.runehive.content.staff.PlayerManagement.TELEPORT_TO_ME
Initial value:
=(PlayerRight.getColor(MODERATOR) + "Teleport To Me") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.move(player.getPosition());
                other.instance = player.instance;
                other.pvpInstance = player.pvpInstance;
                other.message("<col=FF0D5D>You have been force teleported to " + player.getName() + ".");
            }
        }
    }
Definition at line 45 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.move(player.getPosition());
                other.instance = player.instance;
                other.pvpInstance = player.pvpInstance;
                other.message("<col=FF0D5D>You have been force teleported to " + player.getName() + ".");
            }
        }
    },
UNJAIL
com.runehive.content.staff.PlayerManagement.UNJAIL
Initial value:
=(PlayerRight.getColor(MODERATOR) + "Un-Jail") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.punishment.unJail();
                other.dialogueFactory.sendStatement("You have been unjailed!").execute();
                other.message("<col=FF0D5D>You have been unjailed by: " + player.getName());
                player.message("<col=FF0D5D>You have unjailed: " + other.getName());
            }
        }
    }
Definition at line 117 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.punishment.unJail();
                other.dialogueFactory.sendStatement("You have been unjailed!").execute();
                other.message("<col=FF0D5D>You have been unjailed by: " + player.getName());
                player.message("<col=FF0D5D>You have unjailed: " + other.getName());
            }
        }
    },
UNMUTE
com.runehive.content.staff.PlayerManagement.UNMUTE
Initial value:
=(PlayerRight.getColor(MODERATOR) + "Un-Mute") {
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.punishment.unmute();
                other.dialogueFactory.sendStatement("You have been unmuted!").execute();
                other.message("<col=FF0D5D>You have been unmuted by: " + player.getName());
                player.message("<col=FF0D5D>You have unmuted: " + other.getName());
            }
        }
    }
Definition at line 163 of file PlayerManagement.java.
{
        @Override
        public void handle(Player player) {
            if (PlayerRight.isModerator(player) && player.managing.isPresent()) {
                Player other = player.managing.get();
                other.punishment.unmute();
                other.dialogueFactory.sendStatement("You have been unmuted!").execute();
                other.message("<col=FF0D5D>You have been unmuted by: " + player.getName());
                player.message("<col=FF0D5D>You have unmuted: " + other.getName());
            }
        }
    },
The documentation for this enum was generated from the following file:
java/com/runehive/content/staff/PlayerManagement.java