RuneHive-Game: com.runehive.content.emote.Emote Enum Reference
com.runehive.content.emote.Emote Enum Reference
Holds all the emote data.
Public Member Functions
Emote (int button, int animation, int graphic, int config)
Constructs a new Emote.
int getAnimation ()
Gets the animation of the the emote.
int getButton ()
Gets the button identification of the emote.
int getConfig ()
Gets the config of the emote.
int getGraphic ()
Gets the graphic of the emote.
Public Member Functions inherited from com.runehive.util.generic.BooleanInterface< T >
boolean activated (final T player)
Static Public Member Functions
static void execute (Player player, int animation, int graphic)
static Optional< Emote > forId (int button)
Gets emote data corresponding the the button identification.
static void skillcape (Player player)
Public Attributes
AIR_GUITAR
ANGRY
BECKON
BLOW_KISS
BOW
CHEER
CLAP
CLIMB_ROPE
CRY
DANCE
FLAP
GLASS_BOX
GLASS_WALL
GOBLIN_BOW
GOBLIN_SALUTE
HEADBANG
HYPERMOBILE_DRINKER
IDEA
JIG
JOG
JUMP_FOR_JOY
LAUGH
LEAN
NO
PANIC
PUSH_UP
RABBIT_HOP
RASBERRY
SALUTE
SCARED
SHRUG
SIT_UP
SLAP_HEAD
STAR_JUMP
STOMP
THINK
TWIRL
URI_TRANSFORM
WAVE
YAWN
YES
ZOMBIE_DANCE
ZOMBIE_HAND
ZOMBIE_WALK
Private Attributes
final int animation
The emote animation.
final int button
The button identification.
final int config
The emote configuration.
final int graphic
The emote graphic.
Detailed Description
Holds all the emote data.
Author
Daniel
Definition at line 18 of file Emote.java.
Constructor & Destructor Documentation
Emote()
com.runehive.content.emote.Emote.Emote (int button, int animation, int graphic, int config)
Constructs a new Emote.
Definition at line 299 of file Emote.java.
{
        this.button = button;
        this.animation = animation;
        this.graphic = graphic;
        this.config = config;
    }
References animation, button, config, and graphic.
Member Function Documentation
execute()
void com.runehive.content.emote.Emote.execute (Player player, int animation, int graphic) static
Definition at line 325 of file Emote.java.
{
        player.locking.lock(30);
        player.action.execute(new EmoteAction(player, animation, graphic), false);
        player.locking.unlock();
    }
References com.runehive.game.world.entity.mob.Mob.action, animation, com.runehive.game.action.ActionManager.execute(), graphic, com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, and com.runehive.game.world.entity.mob.Locking.unlock().
Referenced by skillcape().
forId()
Optional< Emote > com.runehive.content.emote.Emote.forId (int button) static
Gets emote data corresponding the the button identification.
Definition at line 352 of file Emote.java.
{
        return Arrays.stream(values()).filter(a -> a.button == button).findAny();
    }
References button.
getAnimation()
int com.runehive.content.emote.Emote.getAnimation ()
Gets the animation of the the emote.
Definition at line 337 of file Emote.java.
{
        return animation;
    }
References animation.
getButton()
int com.runehive.content.emote.Emote.getButton ()
Gets the button identification of the emote.
Definition at line 332 of file Emote.java.
{
        return button;
    }
References button.
getConfig()
int com.runehive.content.emote.Emote.getConfig ()
Gets the config of the emote.
Definition at line 347 of file Emote.java.
{
        return config;
    }
References config.
getGraphic()
int com.runehive.content.emote.Emote.getGraphic ()
Gets the graphic of the emote.
Definition at line 342 of file Emote.java.
{
        return graphic;
    }
References graphic.
skillcape()
void com.runehive.content.emote.Emote.skillcape (Player player) static
Definition at line 306 of file Emote.java.
{
        Item item = player.equipment.get(Equipment.CAPE_SLOT);
        if (item == null) {
            player.send(new SendMessage("You must be wearing a skillcape to perform this emote!"));
            return;
        }
        Skillcape skillcape = Skillcape.forId(item.getId());
        if (skillcape == null) {
            player.send(new SendMessage("You must be wearing a skillcape to perform this emote!"));
            return;
        }
        player.locking.lock(30);
        execute(player, skillcape.getAnimation(), skillcape.getGraphic());
        player.locking.unlock();
    }
References com.runehive.game.world.items.containers.equipment.Equipment.CAPE_SLOT, com.runehive.game.world.entity.mob.player.Player.equipment, execute(), com.runehive.content.emote.Skillcape.forId(), com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, com.runehive.game.world.entity.mob.player.Player.send(), skillcape(), and com.runehive.game.world.entity.mob.Locking.unlock().
Referenced by skillcape().
Member Data Documentation
AIR_GUITAR
com.runehive.content.emote.Emote.AIR_GUITAR
Initial value:
=(18715, -1, 1239, 1115) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.GUITAR);
        }
    }
Definition at line 273 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.GUITAR);
        }
    },
ANGRY
com.runehive.content.emote.Emote.ANGRY
Initial value:
=(167, 864, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 37 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
animation
final int com.runehive.content.emote.Emote.animation private
The emote animation.
Definition at line 290 of file Emote.java.
Referenced by Emote(), execute(), and getAnimation().
BECKON
com.runehive.content.emote.Emote.BECKON
Initial value:
=(165, 859, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 67 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
BLOW_KISS
com.runehive.content.emote.Emote.BLOW_KISS
Initial value:
=(11100, 0x558, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 121 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
BOW
com.runehive.content.emote.Emote.BOW
Initial value:
=(164, 858, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 31 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
button
final int com.runehive.content.emote.Emote.button private
The button identification.
Definition at line 287 of file Emote.java.
Referenced by Emote(), forId(), and getButton().
CHEER
com.runehive.content.emote.Emote.CHEER
Initial value:
=(171, 862, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 61 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
CLAP
com.runehive.content.emote.Emote.CLAP
Initial value:
=(172, 865, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 139 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
CLIMB_ROPE
com.runehive.content.emote.Emote.CLIMB_ROPE
Initial value:
=(18718, 0x46A, -1, 1118) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.CLIMB_ROPE);
        }
    }
Definition at line 170 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.CLIMB_ROPE);
        }
    },
config
final int com.runehive.content.emote.Emote.config private
The emote configuration.
Definition at line 296 of file Emote.java.
Referenced by Emote(), and getConfig().
CRY
com.runehive.content.emote.Emote.CRY
Initial value:
=(161, 860, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 115 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
DANCE
com.runehive.content.emote.Emote.DANCE
Initial value:
=(166, 866, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 91 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
FLAP
com.runehive.content.emote.Emote.FLAP
Initial value:
=(18702, 4280, -1, 1102) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.FLAP);
        }
    }
Definition at line 201 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.FLAP);
        }
    },
GLASS_BOX
com.runehive.content.emote.Emote.GLASS_BOX
Initial value:
=(18717, 0x46B, -1, 1117) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.GLASS_BOX);
        }
    }
Definition at line 164 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.GLASS_BOX);
        }
    },
GLASS_WALL
com.runehive.content.emote.Emote.GLASS_WALL
Initial value:
=(18720, 0x468, -1, 1120) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.GLASS_WALL);
        }
    }
Definition at line 182 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.GLASS_WALL);
        }
    },
GOBLIN_BOW
com.runehive.content.emote.Emote.GOBLIN_BOW
Initial value:
=(13383, 0x84F, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 151 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
GOBLIN_SALUTE
com.runehive.content.emote.Emote.GOBLIN_SALUTE
Initial value:
=(13384, 0x850, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 157 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
graphic
final int com.runehive.content.emote.Emote.graphic private
The emote graphic.
Definition at line 293 of file Emote.java.
Referenced by Emote(), execute(), and getGraphic().
HEADBANG
com.runehive.content.emote.Emote.HEADBANG
Initial value:
=(13365, 2108, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 109 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
HYPERMOBILE_DRINKER
com.runehive.content.emote.Emote.HYPERMOBILE_DRINKER
Initial value:
=(18713, 7131, -1, 1113) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.DRINK);
        }
    }
Definition at line 267 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.DRINK);
        }
    },
IDEA
com.runehive.content.emote.Emote.IDEA
Initial value:
=(18700, 4276, 712, 1100) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.IDEA);
        }
    }
Definition at line 189 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.IDEA);
        }
    },
JIG
com.runehive.content.emote.Emote.JIG
Initial value:
=(13363, 2106, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 97 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
JOG
com.runehive.content.emote.Emote.JOG
Initial value:
=(18711, 2764, -1, 1111) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.JOG);
        }
    }
Definition at line 255 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.JOG);
        }
    },
JUMP_FOR_JOY
com.runehive.content.emote.Emote.JUMP_FOR_JOY
Initial value:
=(13366, 2109, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 79 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
LAUGH
com.runehive.content.emote.Emote.LAUGH
Initial value:
=(170, 861, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 73 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
LEAN
com.runehive.content.emote.Emote.LEAN
Initial value:
=(18719, 0x469, -1, 1119) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.LEAN);
        }
    }
Definition at line 176 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.LEAN);
        }
    },
NO
com.runehive.content.emote.Emote.NO
Initial value:
=(169, 856, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 25 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
PANIC
com.runehive.content.emote.Emote.PANIC
Initial value:
=(13362, 2105, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 127 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
PUSH_UP
com.runehive.content.emote.Emote.PUSH_UP
Initial value:
=(18709, 2756, -1, 1109) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.PUSH_UP);
        }
    }
Definition at line 243 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.PUSH_UP);
        }
    },
RABBIT_HOP
com.runehive.content.emote.Emote.RABBIT_HOP
Initial value:
=(18707, 6111, -1, 1107) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.BUNNY_HOP);
        }
    }
Definition at line 231 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.BUNNY_HOP);
        }
    },
RASBERRY
com.runehive.content.emote.Emote.RASBERRY
Initial value:
=(13367, 2110, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 133 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
SALUTE
com.runehive.content.emote.Emote.SALUTE
Initial value:
=(13369, 2112, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 145 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
SCARED
com.runehive.content.emote.Emote.SCARED
Initial value:
=(18706, 2836, -1, 1106) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.SCARED);
        }
    }
Definition at line 225 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.SCARED);
        }
    },
SHRUG
com.runehive.content.emote.Emote.SHRUG
Initial value:
=(13370, 2113, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 55 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
SIT_UP
com.runehive.content.emote.Emote.SIT_UP
Initial value:
=(18708, 2763, -1, 1108) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.SIT_UP);
        }
    }
Definition at line 237 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.SIT_UP);
        }
    },
SLAP_HEAD
com.runehive.content.emote.Emote.SLAP_HEAD
Initial value:
=(18703, 4275, -1, 1103) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.SLAP);
        }
    }
Definition at line 207 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.SLAP);
        }
    },
STAR_JUMP
com.runehive.content.emote.Emote.STAR_JUMP
Initial value:
=(18710, 2761, -1, 1110) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.JUMPING_JACK);
        }
    }
Definition at line 249 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.JUMPING_JACK);
        }
    },
STOMP
com.runehive.content.emote.Emote.STOMP
Initial value:
=(18701, 4278, -1, 1101) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.STOMP);
        }
    }
Definition at line 195 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.STOMP);
        }
    },
THINK
com.runehive.content.emote.Emote.THINK
Initial value:
=(162, 857, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 43 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
TWIRL
com.runehive.content.emote.Emote.TWIRL
Initial value:
=(13364, 2107, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 103 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
URI_TRANSFORM
com.runehive.content.emote.Emote.URI_TRANSFORM
Initial value:
=(18716, -1, -1, 1116) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.URI);
        }
    }
Definition at line 284 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.URI);
        }
    };
WAVE
com.runehive.content.emote.Emote.WAVE
Initial value:
=(163, 863, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 49 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
YAWN
com.runehive.content.emote.Emote.YAWN
Initial value:
=(13368, 2111, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 85 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
YES
com.runehive.content.emote.Emote.YES
Initial value:
=(168, 855, -1, -1) {
        @Override
        public boolean activated(Player player) {
            return true;
        }
    }
Definition at line 19 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return true;
        }
    },
ZOMBIE_DANCE
com.runehive.content.emote.Emote.ZOMBIE_DANCE
Initial value:
=(18705, 3543, -1, 1105) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.ZOMBIE_DANCE);
        }
    }
Definition at line 219 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.ZOMBIE_DANCE);
        }
    },
ZOMBIE_HAND
com.runehive.content.emote.Emote.ZOMBIE_HAND
Initial value:
=(18712, 4513, 320, 1112) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.DEMON_HAND);
        }
    }
Definition at line 261 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.DEMON_HAND);
        }
    },
ZOMBIE_WALK
com.runehive.content.emote.Emote.ZOMBIE_WALK
Initial value:
=(18704, 3544, -1, 1104) {
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.ZOMBIE_WALK);
        }
    }
Definition at line 213 of file Emote.java.
{
        @Override
        public boolean activated(Player player) {
            return player.emoteUnlockable.contains(EmoteUnlockable.ZOMBIE_WALK);
        }
    },
The documentation for this enum was generated from the following file:
java/com/runehive/content/emote/Emote.java