RuneHive-Game: com.runehive.content.combat.SkullHeadIconType Enum Reference
com.runehive.content.combat.SkullHeadIconType Enum Reference
Public Member Functions
int getCode ()
SkullHeadIconType (int code)
Static Public Member Functions
static Optional< SkullHeadIconType > lookup (int code)
Public Attributes
NO_SKULL =(-1)
RED_SKULL =(1)
WHITE_SKULL =(0)
Private Attributes
final int cocde
Detailed Description
Definition at line 5 of file SkullHeadIconType.java.
Constructor & Destructor Documentation
SkullHeadIconType()
com.runehive.content.combat.SkullHeadIconType.SkullHeadIconType (int code)
Definition at line 12 of file SkullHeadIconType.java.
{
        this.cocde = code;
    }
Referenced by lookup().
Member Function Documentation
getCode()
int com.runehive.content.combat.SkullHeadIconType.getCode ()
Definition at line 24 of file SkullHeadIconType.java.
{
        return cocde;
    }
References cocde.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask().
lookup()
Optional< SkullHeadIconType > com.runehive.content.combat.SkullHeadIconType.lookup (int code) static
Definition at line 16 of file SkullHeadIconType.java.
{
        if (code < -1 || code > 1) {
            return Optional.empty();
        }
        return Optional.of(SkullHeadIconType.values()[code + 1]);
    }
References SkullHeadIconType().
Member Data Documentation
cocde
final int com.runehive.content.combat.SkullHeadIconType.cocde private
Definition at line 10 of file SkullHeadIconType.java.
Referenced by getCode().
NO_SKULL
com.runehive.content.combat.SkullHeadIconType.NO_SKULL =(-1)
Definition at line 6 of file SkullHeadIconType.java.
Referenced by com.runehive.content.combat.Skulling.unskull().
RED_SKULL
com.runehive.content.combat.SkullHeadIconType.RED_SKULL =(1)
Definition at line 8 of file SkullHeadIconType.java.
WHITE_SKULL
com.runehive.content.combat.SkullHeadIconType.WHITE_SKULL =(0)
Definition at line 7 of file SkullHeadIconType.java.
Referenced by com.runehive.content.combat.Skulling.checkForSkulling(), and com.runehive.content.combat.Skulling.skull().
The documentation for this enum was generated from the following file:
java/com/runehive/content/combat/SkullHeadIconType.java