RuneHive-Game: com.runehive.content.Obelisks.ObeliskData Enum Reference
com.runehive.content.Obelisks.ObeliskData Enum Reference
Public Member Functions
Boundary getBoundaries ()
ObeliskData (int objectId, Boundary boundary)
Static Public Member Functions
static ObeliskData forObject (int objectId)
static ObeliskData getRandom (ObeliskData exclude)
Public Attributes
LEVEL_13 =(14829, new Boundary(3154, 3618, 3158, 3622))
LEVEL_19 =(14830, new Boundary(3225, 3665, 3229, 3669))
LEVEL_27 =(14827, new Boundary(3033, 3730, 3037, 3734))
LEVEL_35 =(14828, new Boundary(3104, 3792, 3108, 3796))
LEVEL_44 =(14826, new Boundary(2978, 3864, 2982, 3868))
LEVEL_50 =(14831, new Boundary(3305, 3914, 3309, 3918))
Private Attributes
final Boundary boundary
final int objectId
Detailed Description
Definition at line 105 of file Obelisks.java.
Constructor & Destructor Documentation
ObeliskData()
com.runehive.content.Obelisks.ObeliskData.ObeliskData (int objectId, Boundary boundary)
Definition at line 116 of file Obelisks.java.
{
            this.objectId = objectId;
            this.boundary = boundary;
        }
References boundary, and objectId.
Referenced by forObject(), and getRandom().
Member Function Documentation
forObject()
ObeliskData com.runehive.content.Obelisks.ObeliskData.forObject (int objectId) static
Definition at line 125 of file Obelisks.java.
{
            for (ObeliskData l : values()) {
                if (l.objectId == objectId) {
                    return l;
                }
            }
            return null;
        }
References ObeliskData(), and objectId.
Referenced by com.runehive.content.Obelisks.activate(), and com.runehive.content.Obelisks.activate().
getBoundaries()
Boundary com.runehive.content.Obelisks.ObeliskData.getBoundaries ()
Definition at line 121 of file Obelisks.java.
{
            return boundary;
        }
References boundary.
Referenced by com.runehive.content.Obelisks.activate().
getRandom()
ObeliskData com.runehive.content.Obelisks.ObeliskData.getRandom (ObeliskData exclude) static
Definition at line 134 of file Obelisks.java.
{
            ArrayList<ObeliskData> locations = new ArrayList<>(Arrays.asList(values()));
            locations.remove(exclude);
            return locations.get(Utility.random(locations.size() - 1));
        }
References ObeliskData(), and com.runehive.util.Utility.random().
Referenced by com.runehive.content.Obelisks.activate().
Member Data Documentation
boundary
final Boundary com.runehive.content.Obelisks.ObeliskData.boundary private
Definition at line 114 of file Obelisks.java.
Referenced by com.runehive.content.Obelisks.activate(), getBoundaries(), and ObeliskData().
LEVEL_13
com.runehive.content.Obelisks.ObeliskData.LEVEL_13 =(14829, new Boundary(3154, 3618, 3158, 3622))
Definition at line 106 of file Obelisks.java.
LEVEL_19
com.runehive.content.Obelisks.ObeliskData.LEVEL_19 =(14830, new Boundary(3225, 3665, 3229, 3669))
Definition at line 107 of file Obelisks.java.
LEVEL_27
com.runehive.content.Obelisks.ObeliskData.LEVEL_27 =(14827, new Boundary(3033, 3730, 3037, 3734))
Definition at line 108 of file Obelisks.java.
LEVEL_35
com.runehive.content.Obelisks.ObeliskData.LEVEL_35 =(14828, new Boundary(3104, 3792, 3108, 3796))
Definition at line 109 of file Obelisks.java.
LEVEL_44
com.runehive.content.Obelisks.ObeliskData.LEVEL_44 =(14826, new Boundary(2978, 3864, 2982, 3868))
Definition at line 110 of file Obelisks.java.
LEVEL_50
com.runehive.content.Obelisks.ObeliskData.LEVEL_50 =(14831, new Boundary(3305, 3914, 3309, 3918))
Definition at line 111 of file Obelisks.java.
objectId
final int com.runehive.content.Obelisks.ObeliskData.objectId private
Definition at line 113 of file Obelisks.java.
Referenced by com.runehive.content.Obelisks.activate(), forObject(), and ObeliskData().
The documentation for this enum was generated from the following file:
java/com/runehive/content/Obelisks.java