RuneHive-Game: com.runehive.content.skill.impl.thieving.PickpocketData Enum Reference
com.runehive.content.skill.impl.thieving.PickpocketData Enum Reference
Holds all the data for pickpocketing Npcs.
Public Member Functions
int getDamage ()
Gets The damage from stun.
double getExperience ()
Gets the experience rewarded.
int getLevel ()
Gets the level required.
Item[] getLoot ()
Gets the possible loot.
int[] getNpc ()
Gets the npc identification.
int getStun ()
Gets The stun timer.
PickpocketData (int[] npc, int level, double experience, int stun, int damage, Item... loot)
The pickpocketing data.
Static Public Member Functions
static PickpocketData forId (int npc)
Gets the pickpocket data for npc.
Public Attributes
AL_KHARID_WARRIOR =(new int[] { 3103 }, 25, 26, 5, 2, new Item(Config.CURRENCY, 800))
BEARDED_POLLNIVNIAN_BANDIT =(new int[] { 736 }, 45, 65, 5, 5, new Item(Config.CURRENCY, 1450), new Item(1523, 1), new Item(179, 1))
DESERT_BANDIT =(new int[] { 693 }, 53, 79.5, 5, 3, new Item(Config.CURRENCY, 1450), new Item(1523, 1), new Item(179, 1))
ELF =(new int[] { 5298 }, 85, 353, 6, 5, new Item(Config.CURRENCY, 6000), new Item(Config.CURRENCY, 5500), new Item(565, 3), new Item(1602, 2), new Item(1994, 2))
FARMER =(new int[] { 3086 }, 10, 14.5, 5, 1, new Item(Config.CURRENCY, 655), new Item(5318, 10))
GNOME =(new int[] { 6094 }, 75, 198.5, 5, 1, new Item(Config.CURRENCY, 6000), new Item(557, 5), new Item(445, 2), new Item(570, 2))
HERO =(new int[] { 3106 }, 80, 275, 6, 4, new Item(Config.CURRENCY, 6000), new Item(Config.CURRENCY, 4500), new Item(565, 3), new Item(1602, 2), new Item(1994, 2))
KNIGHT =(new int[] { 3108 }, 55, 84.3, 5, 3, new Item(Config.CURRENCY, 1650))
MAN =(new int[] { 3080, 3081 }, 1, 8, 5, 1, new Item(Config.CURRENCY, 355))
MASTER_FARMER
MENAPHITE_THUG =(new int[] { 3549 }, 65, 137.5, 5, 5, new Item(Config.CURRENCY, 1800))
PALADIN =(new int[] { 1144 }, 70, 151.75, 5, 3, new Item(Config.CURRENCY, 2000), new Item(562, 5))
POLLNIVNIAN_BANDIT =(new int[] { 714 }, 55, 84.3, 5, 5, new Item(Config.CURRENCY, 1650))
ROGUE =(new int[] { 2884 }, 32, 35.5, 5, 2, new Item(Config.CURRENCY, 1000))
VARROCK_GUARD =(new int[] { 3010 }, 40, 46.8, 5, 2, new Item(Config.CURRENCY, 1250))
WOMAN =(new int[] { 3083 }, 1, 8, 5, 1, new Item(Config.CURRENCY, 355))
YANILLE_WATCHMAN =(new int[] { 3251 }, 65, 137.5, 5, 3, new Item(Config.CURRENCY, 1800))
Private Attributes
final int damage
final double experience
final int level
final Item[] loot
final int[] npc
final int stun
Detailed Description
Holds all the data for pickpocketing Npcs.
Author
Daniel
Definition at line 12 of file PickpocketData.java.
Constructor & Destructor Documentation
PickpocketData()
com.runehive.content.skill.impl.thieving.PickpocketData.PickpocketData (int[] npc, int level, double experience, int stun, int damage, Item... loot)
The pickpocketing data.
Parameters
npc The array of npcc.
npc The npc identification.
level The level required.
experience The experience rewarded.
stun The stun timer.
damage The damage from stun.
loot The possible loots.
Definition at line 90 of file PickpocketData.java.
{
        this.npc = npc;
        this.level = level;
        this.experience = experience;
        this.stun = stun;
        this.damage = damage;
        this.loot = loot;
    }
References damage, experience, level, loot, npc, and stun.
Referenced by forId().
Member Function Documentation
forId()
PickpocketData com.runehive.content.skill.impl.thieving.PickpocketData.forId (int npc) static
Gets the pickpocket data for npc.
Parameters
npc The npc being pickpocketed.
Returns
The pickpocket data.
Definition at line 160 of file PickpocketData.java.
{
        for (PickpocketData data : PickpocketData.values())
            for (int id : data.npc)
                if (id == npc)
                    return data;
        return null;
    }
References npc, and PickpocketData().
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickNpc().
getDamage()
int com.runehive.content.skill.impl.thieving.PickpocketData.getDamage ()
Gets The damage from stun.
Returns
The damage from stun.
Definition at line 140 of file PickpocketData.java.
{
        return damage;
    }
References damage.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickNpc().
getExperience()
double com.runehive.content.skill.impl.thieving.PickpocketData.getExperience ()
Gets the experience rewarded.
Returns
The experience rewarded.
Definition at line 122 of file PickpocketData.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickNpc().
getLevel()
int com.runehive.content.skill.impl.thieving.PickpocketData.getLevel ()
Gets the level required.
Returns
The level required.
Definition at line 113 of file PickpocketData.java.
{
        return level;
    }
References level.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickNpc(), and com.runehive.content.skill.impl.thieving.Thieving.failureRate().
getLoot()
Item[] com.runehive.content.skill.impl.thieving.PickpocketData.getLoot ()
Gets the possible loot.
Returns
The possible loot.
Definition at line 149 of file PickpocketData.java.
{
        return loot;
    }
References loot.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickNpc().
getNpc()
int[] com.runehive.content.skill.impl.thieving.PickpocketData.getNpc ()
Gets the npc identification.
Returns
The npc identification.
Definition at line 104 of file PickpocketData.java.
{
        return npc;
    }
References npc.
getStun()
int com.runehive.content.skill.impl.thieving.PickpocketData.getStun ()
Gets The stun timer.
Returns
The stun timer.
Definition at line 131 of file PickpocketData.java.
{
        return stun;
    }
References stun.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickNpc().
Member Data Documentation
AL_KHARID_WARRIOR
com.runehive.content.skill.impl.thieving.PickpocketData.AL_KHARID_WARRIOR =(new int[] { 3103 }, 25, 26, 5, 2, new Item(Config.CURRENCY, 800))
Definition at line 19 of file PickpocketData.java.
BEARDED_POLLNIVNIAN_BANDIT
com.runehive.content.skill.impl.thieving.PickpocketData.BEARDED_POLLNIVNIAN_BANDIT =(new int[] { 736 }, 45, 65, 5, 5, new Item(Config.CURRENCY, 1450), new Item(1523, 1), new Item(179, 1))
Definition at line 34 of file PickpocketData.java.
damage
final int com.runehive.content.skill.impl.thieving.PickpocketData.damage private
Definition at line 67 of file PickpocketData.java.
Referenced by getDamage(), and PickpocketData().
DESERT_BANDIT
com.runehive.content.skill.impl.thieving.PickpocketData.DESERT_BANDIT =(new int[] { 693 }, 53, 79.5, 5, 3, new Item(Config.CURRENCY, 1450), new Item(1523, 1), new Item(179, 1))
Definition at line 36 of file PickpocketData.java.
ELF
com.runehive.content.skill.impl.thieving.PickpocketData.ELF =(new int[] { 5298 }, 85, 353, 6, 5, new Item(Config.CURRENCY, 6000), new Item(Config.CURRENCY, 5500), new Item(565, 3), new Item(1602, 2), new Item(1994, 2))
Definition at line 52 of file PickpocketData.java.
experience
final double com.runehive.content.skill.impl.thieving.PickpocketData.experience private
Definition at line 61 of file PickpocketData.java.
Referenced by getExperience(), and PickpocketData().
FARMER
com.runehive.content.skill.impl.thieving.PickpocketData.FARMER =(new int[] { 3086 }, 10, 14.5, 5, 1, new Item(Config.CURRENCY, 655), new Item(5318, 10))
Definition at line 17 of file PickpocketData.java.
GNOME
com.runehive.content.skill.impl.thieving.PickpocketData.GNOME =(new int[] { 6094 }, 75, 198.5, 5, 1, new Item(Config.CURRENCY, 6000), new Item(557, 5), new Item(445, 2), new Item(570, 2))
Definition at line 48 of file PickpocketData.java.
HERO
com.runehive.content.skill.impl.thieving.PickpocketData.HERO =(new int[] { 3106 }, 80, 275, 6, 4, new Item(Config.CURRENCY, 6000), new Item(Config.CURRENCY, 4500), new Item(565, 3), new Item(1602, 2), new Item(1994, 2))
Definition at line 50 of file PickpocketData.java.
KNIGHT
com.runehive.content.skill.impl.thieving.PickpocketData.KNIGHT =(new int[] { 3108 }, 55, 84.3, 5, 3, new Item(Config.CURRENCY, 1650))
Definition at line 38 of file PickpocketData.java.
level
final int com.runehive.content.skill.impl.thieving.PickpocketData.level private
Definition at line 58 of file PickpocketData.java.
Referenced by getLevel(), and PickpocketData().
loot
final Item [] com.runehive.content.skill.impl.thieving.PickpocketData.loot private
Definition at line 70 of file PickpocketData.java.
Referenced by getLoot(), and PickpocketData().
MAN
com.runehive.content.skill.impl.thieving.PickpocketData.MAN =(new int[] { 3080, 3081 }, 1, 8, 5, 1, new Item(Config.CURRENCY, 355))
Definition at line 13 of file PickpocketData.java.
MASTER_FARMER
com.runehive.content.skill.impl.thieving.PickpocketData.MASTER_FARMER
Initial value:
=(new int[] { 3257, 3097, 5730 }, 38, 43, 5, 3, new Item(Config.CURRENCY, 1150), new Item(Items.POTATO_SEED, 1, 4),
            new Item(Items.ONION_SEED, 1, 2), new Item(Items.CABBAGE_SEED, 1, 3), new Item(Items.TOMATO_SEED, 1, 2),
            new Item(Items.SWEETCORN_SEED, 1, 2), new Item(Items.STRAWBERRY_SEED, 1), new Item(Items.WATERMELON_SEED, 1),
            new Item(22879, 1), new Item(Items.MARIGOLD_SEED, 1), new Item(Items.NASTURTIUM_SEED, 1), new Item(Items.ROSEMARY_SEED, 1),
            new Item(Items.WOAD_SEED, 1), new Item(Items.LIMPWURT_SEED, 1), new Item(Items.GUAM_SEED, 1), new Item(Items.MARRENTILL_SEED, 1),
            new Item(Items.TARROMIN_SEED, 1), new Item(Items.HARRALANDER_SEED, 1), new Item(Items.RANARR_SEED, 1), new Item(Items.TOADFLAX_SEED, 1),
            new Item(Items.IRIT_SEED, 1), new Item(Items.AVANTOE_SEED, 1), new Item(Items.KWUARM_SEED, 1), new Item(Items.SNAPDRAGON_SEED, 1),
            new Item(Items.CADANTINE_SEED, 1), new Item(Items.LANTADYME_SEED, 1), new Item(Items.DWARF_WEED_SEED, 1), new Item(Items.TORSTOL_SEED, 1))
Definition at line 23 of file PickpocketData.java.
MENAPHITE_THUG
com.runehive.content.skill.impl.thieving.PickpocketData.MENAPHITE_THUG =(new int[] { 3549 }, 65, 137.5, 5, 5, new Item(Config.CURRENCY, 1800))
Definition at line 44 of file PickpocketData.java.
npc
final int [] com.runehive.content.skill.impl.thieving.PickpocketData.npc private
Definition at line 55 of file PickpocketData.java.
Referenced by forId(), getNpc(), and PickpocketData().
PALADIN
com.runehive.content.skill.impl.thieving.PickpocketData.PALADIN =(new int[] { 1144 }, 70, 151.75, 5, 3, new Item(Config.CURRENCY, 2000), new Item(562, 5))
Definition at line 46 of file PickpocketData.java.
POLLNIVNIAN_BANDIT
com.runehive.content.skill.impl.thieving.PickpocketData.POLLNIVNIAN_BANDIT =(new int[] { 714 }, 55, 84.3, 5, 5, new Item(Config.CURRENCY, 1650))
Definition at line 40 of file PickpocketData.java.
ROGUE
com.runehive.content.skill.impl.thieving.PickpocketData.ROGUE =(new int[] { 2884 }, 32, 35.5, 5, 2, new Item(Config.CURRENCY, 1000))
Definition at line 21 of file PickpocketData.java.
stun
final int com.runehive.content.skill.impl.thieving.PickpocketData.stun private
Definition at line 64 of file PickpocketData.java.
Referenced by getStun(), and PickpocketData().
VARROCK_GUARD
com.runehive.content.skill.impl.thieving.PickpocketData.VARROCK_GUARD =(new int[] { 3010 }, 40, 46.8, 5, 2, new Item(Config.CURRENCY, 1250))
Definition at line 32 of file PickpocketData.java.
WOMAN
com.runehive.content.skill.impl.thieving.PickpocketData.WOMAN =(new int[] { 3083 }, 1, 8, 5, 1, new Item(Config.CURRENCY, 355))
Definition at line 15 of file PickpocketData.java.
YANILLE_WATCHMAN
com.runehive.content.skill.impl.thieving.PickpocketData.YANILLE_WATCHMAN =(new int[] { 3251 }, 65, 137.5, 5, 3, new Item(Config.CURRENCY, 1800))
Definition at line 42 of file PickpocketData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/thieving/PickpocketData.java