RuneHive-Game: com.runehive.game.world.entity.combat.ranged.RangedAmmunition Enum Reference
com.runehive.game.world.entity.combat.ranged.RangedAmmunition Enum Reference
Public Member Functions
Optional< Animation > getAnimation (int id)
Optional< CombatImpact > getEffect (int id)
Optional< Graphic > getEnd (int id)
abstract CombatProjectile getProjectile ()
int getRemoval ()
Optional< Graphic > getStart (int id)
boolean isDart ()
boolean isDroppable ()
RangedAmmunition (boolean droppable, int... ids)
RangedAmmunition (boolean droppable, int[] weapons, int... ids)
void sendProjectile (Mob attacker, Mob defender)
Static Public Member Functions
[static initializer]
static RangedAmmunition find (Item weapon, Item item)
static RangedAmmunition forItemId (final int itemId)
Public Attributes
ADAMANT_ARROW
ADAMANT_BOLTS
ADAMANT_DART
ADAMANT_JAVELIN
ADAMANT_KNIFE
ADAMANT_THROWNAXE
AMLODD
BLACK_DART
BLACK_KNIFE
BLURITE_BOLTS
BOLT_RACK
BONE_BOLT
BROAD_ARROW
BROAD_TIPPED_BOLTS
BRONZE_ARROW
BRONZE_BOLTS
BRONZE_DART
BRONZE_JAVELIN
BRONZE_KNIFE
BRONZE_THROWNAXE
BRUTAL_ADAMANT_ARROW
BRUTAL_BLACK_ARROW
BRUTAL_BRONZE_ARROW
BRUTAL_IRON_ARROW
BRUTAL_MITHRIL_ARROW
BRUTAL_RUNE_ARROW
BRUTAL_STEEL_ARROW
CADARN
CHINCHOMPA
CRAWS_BOW
CRWYS
DOUBLE_ADAMANT_ARROW
DOUBLE_BRONZE_ARROW
DOUBLE_DRAGON_ARROW
DOUBLE_IRON_ARROW
DOUBLE_MITHRIL_ARROW
DOUBLE_RUNE_ARROW
DOUBLE_STEEL_ARROW
DRAGON_ARROW
DRAGON_BOLTS
DRAGON_DART
DRAGON_JAVELIN
DRAGON_KNIFE
DRAGON_THROWNAXE
GUAM_TAR
HARRALANDER_TAR
HEFIN
ICE_ARROW
IORWERTH
IRON_ARROW
IRON_BOLTS
IRON_DART
IRON_JAVELIN
IRON_KNIFE
IRON_THROWNAXE
KEBBIT_BOLT
LONG_KEBBIT_BOLT
MARRENTIL_TAR
MEILYR
MITHRIL_ARROW
MITHRIL_BOLTS
MITHRIL_DART
MITHRIL_JAVELIN
MITHRIL_KNIFE
MITHRIL_THROWNAXE
OGRE_ARROW
RED_CHINCHOMPA
RUNE_ARROW
RUNE_DART
RUNE_JAVELIN
RUNE_KNIFE
RUNE_THROWNAXE
RUNITE_BOLTS
SILVER_BOLTS
STEEL_ARROW
STEEL_BOLTS
STEEL_DART
STEEL_JAVELIN
STEEL_KNIFE
STEEL_THROWNAXE
TARROMIN_TAR
TOKTZ_XIL_UL
TRAHEAERN
TRAINING_ARROWS
Static Private Member Functions
static int[] darkBows ()
Private Attributes
final boolean droppable
final int[] ids
final int[] weapons
Static Private Attributes
static final Int2ObjectMap< RangedAmmunition > itemIdToType = new Int2ObjectArrayMap<>(values.length)
static final RangedAmmunition[] values = values()
Detailed Description
Definition at line 18 of file RangedAmmunition.java.
Constructor & Destructor Documentation
RangedAmmunition() [1/2]
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RangedAmmunition (boolean droppable, int... ids)
Definition at line 552 of file RangedAmmunition.java.
{
        this.droppable = droppable;
        this.ids = ids;
        this.weapons = new int[0];
    }
References droppable, and ids.
Referenced by [static initializer](), find(), and forItemId().
RangedAmmunition() [2/2]
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RangedAmmunition (boolean droppable, int[] weapons, int... ids)
Definition at line 558 of file RangedAmmunition.java.
{
        this.droppable = droppable;
        this.ids = ids;
        this.weapons = weapons;
    }
References droppable, ids, and weapons.
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.[static initializer] static
References ids, itemIdToType, RangedAmmunition(), and values.
darkBows()
int[] com.runehive.game.world.entity.combat.ranged.RangedAmmunition.darkBows () static private
Definition at line 585 of file RangedAmmunition.java.
{
        return new int[] { 11235, 12765, 12766, 12767, 12768 };
    }
find()
RangedAmmunition com.runehive.game.world.entity.combat.ranged.RangedAmmunition.find (Item weapon, Item item) static
Definition at line 650 of file RangedAmmunition.java.
{
        if (item == null) return null;
        for (RangedAmmunition ammo : values()) {
            if (ammo.weapons.length > 0 && weapon != null) {
                for (int weaponId : ammo.weapons) {
                    if (weaponId == weapon.getId()) {
                        for (int id : ammo.ids) {
                            if (id == item.getId()) {
                                return ammo;
                            }
                        }
                    }
                }
            } else {
                for (int id : ammo.ids) {
                    if (id == item.getId()) {
                        return ammo;
                    }
                }
            }
        }
        return null;
    }
References com.runehive.game.world.items.Item.getId(), RangedAmmunition(), and values.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), com.runehive.content.itemaction.impl.ToxicBlowpipe.itemOnItem(), and com.runehive.game.world.items.containers.equipment.Equipment.updateRangedEquipment().
forItemId()
RangedAmmunition com.runehive.game.world.entity.combat.ranged.RangedAmmunition.forItemId (final int itemId) static
Definition at line 579 of file RangedAmmunition.java.
{
        return itemIdToType.get(itemId);
    }
References itemIdToType, and RangedAmmunition().
getAnimation()
Optional< Animation > com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getAnimation (int id)
Definition at line 674 of file RangedAmmunition.java.
{
        switch (id) {
            case 9236:
            case 9237:
            case 9238:
            case 9239:
            case 9240:
            case 9241:
            case 9242:
            case 9243:
            case 9244:
            case 9245:
                return getDefinition(new Item(id).getName()).getAnimation();
        }
        return getProjectile().getAnimation();
    }
References getProjectile().
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff().
getEffect()
Optional< CombatImpact > com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getEffect (int id)
Definition at line 708 of file RangedAmmunition.java.
{
        switch (id) {
            case 9236:
            case 9237:
            case 9238:
            case 9239:
            case 9240:
            case 9241:
            case 9242:
            case 9243:
            case 9244:
            case 9245:
                return getDefinition(new Item(id).getName()).getEffect();
        }
        return getProjectile().getEffect();
    }
References getProjectile().
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start().
getEnd()
Optional< Graphic > com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getEnd (int id)
Definition at line 691 of file RangedAmmunition.java.
{
        switch (id) {
            case 9236:
            case 9237:
            case 9238:
            case 9239:
            case 9240:
            case 9241:
            case 9242:
            case 9243:
            case 9244:
            case 9245:
                return getDefinition(new Item(id).getName()).getEnd();
        }
        return getProjectile().getEnd();
    }
References getProjectile().
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.hit().
getProjectile()
abstract CombatProjectile com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getProjectile () abstract
Referenced by getAnimation(), getEffect(), getEnd(), getStart(), and sendProjectile().
getRemoval()
int com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getRemoval ()
Definition at line 744 of file RangedAmmunition.java.
{
        switch (this) {
            case DOUBLE_BRONZE_ARROW:
            case DOUBLE_IRON_ARROW:
            case DOUBLE_STEEL_ARROW:
            case DOUBLE_MITHRIL_ARROW:
            case DOUBLE_ADAMANT_ARROW:
            case DOUBLE_RUNE_ARROW:
            case DOUBLE_DRAGON_ARROW:
                return 2;
            default:
                return 1;
        }
    }
References DOUBLE_ADAMANT_ARROW, DOUBLE_BRONZE_ARROW, DOUBLE_DRAGON_ARROW, DOUBLE_IRON_ARROW, DOUBLE_MITHRIL_ARROW, DOUBLE_RUNE_ARROW, and DOUBLE_STEEL_ARROW.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.canAttack(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getHits().
getStart()
Optional< Graphic > com.runehive.game.world.entity.combat.ranged.RangedAmmunition.getStart (int id)
Definition at line 607 of file RangedAmmunition.java.
{
        switch (id) {
            case 9236:
            case 9237:
            case 9238:
            case 9239:
            case 9240:
            case 9241:
            case 9242:
            case 9243:
            case 9244:
            case 9245:
                return getDefinition(new Item(id).getName()).getStart();
        }
        int itemId;
        switch (this) {
            case DOUBLE_BRONZE_ARROW:
                itemId = 1104;
                break;
            case DOUBLE_IRON_ARROW:
                itemId = 1105;
                break;
            case DOUBLE_STEEL_ARROW:
                itemId = 1106;
                break;
            case DOUBLE_MITHRIL_ARROW:
                itemId = 1107;
                break;
            case DOUBLE_ADAMANT_ARROW:
                itemId = 1108;
                break;
            case DOUBLE_RUNE_ARROW:
                itemId = 1109;
                break;
            case DOUBLE_DRAGON_ARROW:
                itemId = 1111;
                break;
            default:
                return getProjectile().getStart();
        }
        return Optional.of(new Graphic(itemId, 0, true, UpdatePriority.HIGH));
    }
References DOUBLE_ADAMANT_ARROW, DOUBLE_BRONZE_ARROW, DOUBLE_DRAGON_ARROW, DOUBLE_IRON_ARROW, DOUBLE_MITHRIL_ARROW, DOUBLE_RUNE_ARROW, DOUBLE_STEEL_ARROW, getProjectile(), and com.runehive.game.UpdatePriority.HIGH.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff().
isDart()
boolean com.runehive.game.world.entity.combat.ranged.RangedAmmunition.isDart ()
Definition at line 729 of file RangedAmmunition.java.
{
        switch (this) {
            case BRONZE_DART:
            case IRON_DART:
            case STEEL_DART:
            case BLACK_DART:
            case MITHRIL_DART:
            case ADAMANT_DART:
            case RUNE_DART:
            case DRAGON_DART:
            return true;
        }
        return false;
    }
References ADAMANT_DART, BLACK_DART, BRONZE_DART, DRAGON_DART, IRON_DART, MITHRIL_DART, RUNE_DART, and STEEL_DART.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.canAttack(), and com.runehive.content.itemaction.impl.ToxicBlowpipe.itemOnItem().
isDroppable()
boolean com.runehive.game.world.entity.combat.ranged.RangedAmmunition.isDroppable ()
Definition at line 725 of file RangedAmmunition.java.
{
        return droppable;
    }
References droppable.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
sendProjectile()
void com.runehive.game.world.entity.combat.ranged.RangedAmmunition.sendProjectile (Mob attacker, Mob defender)
Definition at line 589 of file RangedAmmunition.java.
{
        getProjectile().sendProjectile(attacker, defender);
        switch (this) {
            case DOUBLE_BRONZE_ARROW:
            case DOUBLE_IRON_ARROW:
            case DOUBLE_STEEL_ARROW:
            case DOUBLE_MITHRIL_ARROW:
            case DOUBLE_ADAMANT_ARROW:
            case DOUBLE_RUNE_ARROW:
            case DOUBLE_DRAGON_ARROW:
                Projectile second = getProjectile().getProjectile().get().copy();
                second.setDuration(15 + second.getDuration());
                second.setCurve(32);
                second.send(attacker, defender);
                break;
        }
    }
References DOUBLE_ADAMANT_ARROW, DOUBLE_BRONZE_ARROW, DOUBLE_DRAGON_ARROW, DOUBLE_IRON_ARROW, DOUBLE_MITHRIL_ARROW, DOUBLE_RUNE_ARROW, DOUBLE_STEEL_ARROW, com.runehive.game.Projectile.getDuration(), getProjectile(), com.runehive.game.Projectile.send(), com.runehive.game.Projectile.setCurve(), and com.runehive.game.Projectile.setDuration().
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.sendStuff(), and com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start().
Member Data Documentation
ADAMANT_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.ADAMANT_ARROW
Initial value:
=(true, 890, 891, 5620, 5626) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant arrow");
        }
    }
Definition at line 335 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant arrow");
        }
    },
ADAMANT_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.ADAMANT_BOLTS
Initial value:
=(true, 9143, 9290, 9297, 9304, 9339, 9242, 9340, 9243) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant bolts");
        }
    }
Definition at line 390 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant bolts");
        }
    },
ADAMANT_DART
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.ADAMANT_DART
Initial value:
=(true, 810, 816, 5633, 5640) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant dart");
        }
    }
Definition at line 194 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant dart");
        }
    },
Referenced by isDart().
ADAMANT_JAVELIN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.ADAMANT_JAVELIN
Initial value:
=(false, 829, 835, 5646, 5652) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant javelin");
        }
    }
Definition at line 43 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant javelin");
        }
    },
ADAMANT_KNIFE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.ADAMANT_KNIFE
Initial value:
=(true, 867, 875, 5659, 5666) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant knife");
        }
    }
Definition at line 243 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant knife");
        }
    },
ADAMANT_THROWNAXE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.ADAMANT_THROWNAXE
Initial value:
=(true, 804) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant thrownaxe");
        }
    }
Definition at line 86 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant thrownaxe");
        }
    },
AMLODD
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.AMLODD
Initial value:
=(false, 25896) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Amlodd");
        }
    }
Definition at line 153 of file RangedAmmunition.java.
                         { //BLUE
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Amlodd");
        }
    },
BLACK_DART
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BLACK_DART
Initial value:
=(true, 3093, 3094, 5631, 5638) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Black dart");
        }
    }
Definition at line 176 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Black dart");
        }
    },
Referenced by isDart().
BLACK_KNIFE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BLACK_KNIFE
Initial value:
=(true, 869, 874, 5658, 5665) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Black knife");
        }
    }
Definition at line 225 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Black knife");
        }
    },
BLURITE_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BLURITE_BOLTS
Initial value:
=(true, 9139, 9286, 9293, 9300, 9335, 9237) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Blurite bolts");
        }
    }
Definition at line 360 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Blurite bolts");
        }
    },
BOLT_RACK
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BOLT_RACK
Initial value:
=(false, 4740) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bolt rack");
        }
    }
Definition at line 477 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bolt rack");
        }
    },
BONE_BOLT
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BONE_BOLT
Initial value:
=(true, 8882) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bone bolts");
        }
    }
Definition at line 452 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bone bolts");
        }
    },
BROAD_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BROAD_ARROW
Initial value:
=(true, 4160) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Broad arrow");
        }
    }
Definition at line 490 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Broad arrow");
        }
    },
BROAD_TIPPED_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BROAD_TIPPED_BOLTS
Initial value:
=(true, 13280) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Broad-tipped bolts");
        }
    }
Definition at line 484 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Broad-tipped bolts");
        }
    },
BRONZE_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRONZE_ARROW
Initial value:
=(true, 882, 883, 5616, 5622) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze arrow");
        }
    }
Definition at line 311 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze arrow");
        }
    },
BRONZE_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRONZE_BOLTS
Initial value:
=(true, 877, 878, 6061, 6062, 879, 9236) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze bolts");
        }
    }
Definition at line 354 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze bolts");
        }
    },
BRONZE_DART
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRONZE_DART
Initial value:
=(true, 806, 812, 5628, 5635) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze dart");
        }
    }
Definition at line 105 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze dart");
        }
    },
Referenced by isDart().
BRONZE_JAVELIN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRONZE_JAVELIN
Initial value:
=(false, 825, 831, 5642, 5648) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze javelin");
        }
    }
Definition at line 19 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze javelin");
        }
    },
BRONZE_KNIFE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRONZE_KNIFE
Initial value:
=(true, 864, 870, 5654, 5651) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze knife");
        }
    }
Definition at line 213 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze knife");
        }
    },
BRONZE_THROWNAXE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRONZE_THROWNAXE
Initial value:
=(true, 800) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze thrownaxe");
        }
    }
Definition at line 62 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze thrownaxe");
        }
    },
BRUTAL_ADAMANT_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRUTAL_ADAMANT_ARROW
Initial value:
=(true, 4798) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant brutal");
        }
    }
Definition at line 433 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant brutal");
        }
    },
BRUTAL_BLACK_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRUTAL_BLACK_ARROW
Initial value:
=(true, 4783) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel brutal");
        }
    }
Definition at line 415 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel brutal");
        }
    },
BRUTAL_BRONZE_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRUTAL_BRONZE_ARROW
Initial value:
=(true, 4773) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze brutal");
        }
    }
Definition at line 403 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze brutal");
        }
    },
BRUTAL_IRON_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRUTAL_IRON_ARROW
Initial value:
=(true, 4778) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron brutal");
        }
    }
Definition at line 409 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron brutal");
        }
    },
BRUTAL_MITHRIL_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRUTAL_MITHRIL_ARROW
Initial value:
=(true, 4793) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril brutal");
        }
    }
Definition at line 427 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril brutal");
        }
    },
BRUTAL_RUNE_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRUTAL_RUNE_ARROW
Initial value:
=(true, 4803) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune brutal");
        }
    }
Definition at line 439 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune brutal");
        }
    },
BRUTAL_STEEL_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.BRUTAL_STEEL_ARROW
Initial value:
=(true, 4788) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Black brutal");
        }
    }
Definition at line 421 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Black brutal");
        }
    },
CADARN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.CADARN
Initial value:
=(false, 25890) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Cadarn");
        }
    }
Definition at line 139 of file RangedAmmunition.java.
                         { //GREEN
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Cadarn");
        }
    },
CHINCHOMPA
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.CHINCHOMPA
Initial value:
=(false, 10033) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Chinchompa");
        }
    }
Definition at line 497 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Chinchompa");
        }
    },
CRAWS_BOW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.CRAWS_BOW
Initial value:
=(false, 22550) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Craw's bow");
        }
    }
Definition at line 111 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Craw's bow");
        }
    },
CRWYS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.CRWYS
Initial value:
=(false, 25892) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Crwys");
        }
    }
Definition at line 146 of file RangedAmmunition.java.
                        { //YELLOW
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Crwys");
        }
    },
DOUBLE_ADAMANT_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DOUBLE_ADAMANT_ARROW
Initial value:
=(true, darkBows(), 890, 891, 5620, 5626) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant arrow");
        }
    }
Definition at line 292 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Adamant arrow");
        }
    },
Referenced by getRemoval(), getStart(), and sendProjectile().
DOUBLE_BRONZE_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DOUBLE_BRONZE_ARROW
Initial value:
=(true, darkBows(), 882, 883, 5616, 5622) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze arrow");
        }
    }
Definition at line 268 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Bronze arrow");
        }
    },
Referenced by getRemoval(), getStart(), and sendProjectile().
DOUBLE_DRAGON_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DOUBLE_DRAGON_ARROW
Initial value:
=(true, darkBows(), 11212, 11227, 11228, 11229) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon arrow");
        }
    }
Definition at line 304 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon arrow");
        }
    },
Referenced by getRemoval(), getStart(), and sendProjectile().
DOUBLE_IRON_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DOUBLE_IRON_ARROW
Initial value:
=(true, darkBows(), 884, 885, 5617, 5623) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron arrow");
        }
    }
Definition at line 274 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron arrow");
        }
    },
Referenced by getRemoval(), getStart(), and sendProjectile().
DOUBLE_MITHRIL_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DOUBLE_MITHRIL_ARROW
Initial value:
=(true, darkBows(), 888, 889, 5619, 5625) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril arrow");
        }
    }
Definition at line 286 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril arrow");
        }
    },
Referenced by getRemoval(), getStart(), and sendProjectile().
DOUBLE_RUNE_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DOUBLE_RUNE_ARROW
Initial value:
=(true, darkBows(), 892, 893, 5621, 5627) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune arrow");
        }
    }
Definition at line 298 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune arrow");
        }
    },
Referenced by getRemoval(), getStart(), and sendProjectile().
DOUBLE_STEEL_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DOUBLE_STEEL_ARROW
Initial value:
=(true, darkBows(), 886, 887, 5618, 5624) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel arrow");
        }
    }
Definition at line 280 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel arrow");
        }
    },
Referenced by getRemoval(), getStart(), and sendProjectile().
DRAGON_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DRAGON_ARROW
Initial value:
=(true, 11212, 11227, 11228, 11229) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon arrow");
        }
    }
Definition at line 347 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon arrow");
        }
    },
DRAGON_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DRAGON_BOLTS
Initial value:
=(true, 21932, 21934, 21936, 21938, 21940, 21942, 21944, 21946, 21948, 21950) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon Bolts");
        }
    }
Definition at line 249 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon Bolts");
        }
    },
DRAGON_DART
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DRAGON_DART
Initial value:
=(true, 11230, 11231, 11233, 11234) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon dart");
        }
    }
Definition at line 206 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon dart");
        }
    },
Referenced by isDart().
DRAGON_JAVELIN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DRAGON_JAVELIN
Initial value:
=(false, 19484, 19486, 19488, 19490) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon javelin");
        }
    }
Definition at line 55 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon javelin");
        }
    },
DRAGON_KNIFE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DRAGON_KNIFE
Initial value:
=(true, 22804, 22810) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon knife");
        }
    }
Definition at line 261 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon knife");
        }
    },
DRAGON_THROWNAXE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.DRAGON_THROWNAXE
Initial value:
=(true, 20849) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon thrownaxe");
        }
    }
Definition at line 98 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Dragon thrownaxe");
        }
    },
droppable
final boolean com.runehive.game.world.entity.combat.ranged.RangedAmmunition.droppable private
Definition at line 548 of file RangedAmmunition.java.
Referenced by isDroppable(), RangedAmmunition(), and RangedAmmunition().
GUAM_TAR
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.GUAM_TAR
Initial value:
=(false, 10142) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Guam tar");
        }
    }
Definition at line 523 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Guam tar");
        }
    },
HARRALANDER_TAR
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.HARRALANDER_TAR
Initial value:
=(false, 10145) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Harralander tar");
        }
    }
Definition at line 546 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Harralander tar");
        }
    };
HEFIN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.HEFIN
Initial value:
=(false, 25867) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Hefin");
        }
    }
Definition at line 118 of file RangedAmmunition.java.
                        { //RED
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Hefin");
        }
    },
ICE_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.ICE_ARROW
Initial value:
=(true, 78) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Ice arrows");
        }
    }
Definition at line 464 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Ice arrows");
        }
    },
ids
final int [] com.runehive.game.world.entity.combat.ranged.RangedAmmunition.ids private
Definition at line 549 of file RangedAmmunition.java.
Referenced by [static initializer](), RangedAmmunition(), and RangedAmmunition().
IORWERTH
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.IORWERTH
Initial value:
=(false, 25886) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iorwerth");
        }
    }
Definition at line 125 of file RangedAmmunition.java.
                           { //BLACK 25886
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iorwerth");
        }
    },
IRON_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.IRON_ARROW
Initial value:
=(true, 884, 885, 5617, 5623) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron arrow");
        }
    }
Definition at line 317 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron arrow");
        }
    },
IRON_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.IRON_BOLTS
Initial value:
=(true, 9140, 9287, 9294, 9301, 880, 9238) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron bolts");
        }
    }
Definition at line 366 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron bolts");
        }
    },
IRON_DART
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.IRON_DART
Initial value:
=(true, 807, 813, 5629, 5636) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron dart");
        }
    }
Definition at line 170 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron dart");
        }
    },
Referenced by isDart().
IRON_JAVELIN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.IRON_JAVELIN
Initial value:
=(false, 826, 832, 5643, 5649) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron javelin");
        }
    }
Definition at line 25 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron javelin");
        }
    },
IRON_KNIFE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.IRON_KNIFE
Initial value:
=(true, 863, 871, 5655, 5662) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron knife");
        }
    }
Definition at line 219 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron knife");
        }
    },
IRON_THROWNAXE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.IRON_THROWNAXE
Initial value:
=(true, 801) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron thrownaxe");
        }
    }
Definition at line 68 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Iron thrownaxe");
        }
    },
itemIdToType
final Int2ObjectMap<RangedAmmunition> com.runehive.game.world.entity.combat.ranged.RangedAmmunition.itemIdToType = new Int2ObjectArrayMap<>(values.length) static private
Definition at line 566 of file RangedAmmunition.java.
Referenced by [static initializer](), and forItemId().
KEBBIT_BOLT
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.KEBBIT_BOLT
Initial value:
=(true, 10158) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Kebbit bolts");
        }
    }
Definition at line 510 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Kebbit bolts");
        }
    },
LONG_KEBBIT_BOLT
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.LONG_KEBBIT_BOLT
Initial value:
=(true, 10159) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Long kebbit bolts");
        }
    }
Definition at line 516 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Long kebbit bolts");
        }
    },
MARRENTIL_TAR
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.MARRENTIL_TAR
Initial value:
=(false, 10143) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Marrentill tar");
        }
    }
Definition at line 529 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Marrentill tar");
        }
    },
MEILYR
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.MEILYR
Initial value:
=(false, 25884, 25865, 25894) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Meilyr");
        }
    }
Definition at line 160 of file RangedAmmunition.java.
                                       { //WHITE
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Meilyr");
        }
    },
MITHRIL_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.MITHRIL_ARROW
Initial value:
=(true, 888, 889, 5619, 5625) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril arrow");
        }
    }
Definition at line 329 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril arrow");
        }
    },
MITHRIL_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.MITHRIL_BOLTS
Initial value:
=(true, 9142, 9289, 9296, 9303, 9337, 9240, 9338, 9241) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril bolts");
        }
    }
Definition at line 384 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril bolts");
        }
    },
MITHRIL_DART
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.MITHRIL_DART
Initial value:
=(true, 809, 815, 5632, 5639) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril dart");
        }
    }
Definition at line 188 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril dart");
        }
    },
Referenced by isDart().
MITHRIL_JAVELIN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.MITHRIL_JAVELIN
Initial value:
=(false, 828, 834, 5645, 5651) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril javelin");
        }
    }
Definition at line 37 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril javelin");
        }
    },
MITHRIL_KNIFE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.MITHRIL_KNIFE
Initial value:
=(true, 866, 873, 5657, 5664) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril knife");
        }
    }
Definition at line 237 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril knife");
        }
    },
MITHRIL_THROWNAXE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.MITHRIL_THROWNAXE
Initial value:
=(true, 803) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril thrownaxe");
        }
    }
Definition at line 80 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Mithril thrownaxe");
        }
    },
OGRE_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.OGRE_ARROW
Initial value:
=(true, 2866) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Ogre arrow");
        }
    }
Definition at line 458 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Ogre arrow");
        }
    },
RED_CHINCHOMPA
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RED_CHINCHOMPA
Initial value:
=(false, 10034) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Red chinchompa");
        }
    }
Definition at line 503 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Red chinchompa");
        }
    },
RUNE_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RUNE_ARROW
Initial value:
=(true, 892, 893, 5621, 5627) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune arrow");
        }
    }
Definition at line 341 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune arrow");
        }
    },
RUNE_DART
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RUNE_DART
Initial value:
=(true, 811, 817, 5634, 5641) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune dart");
        }
    }
Definition at line 200 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune dart");
        }
    },
Referenced by isDart().
RUNE_JAVELIN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RUNE_JAVELIN
Initial value:
=(false, 830, 836, 5647, 5653) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune javelin");
        }
    }
Definition at line 49 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune javelin");
        }
    },
RUNE_KNIFE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RUNE_KNIFE
Initial value:
=(true, 868, 876, 5660, 5667) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune knife");
        }
    }
Definition at line 255 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune knife");
        }
    },
RUNE_THROWNAXE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RUNE_THROWNAXE
Initial value:
=(true, 805) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune thrownaxe");
        }
    }
Definition at line 92 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Rune thrownaxe");
        }
    },
RUNITE_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.RUNITE_BOLTS
Initial value:
=(true, 9144, 9291, 9298, 9305, 9341, 9244, 9342, 9245) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Runite bolts");
        }
    }
Definition at line 396 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Runite bolts");
        }
    },
SILVER_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.SILVER_BOLTS
Initial value:
=(true, 9145, 9292, 9299, 9306) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Silver bolts");
        }
    }
Definition at line 372 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Silver bolts");
        }
    },
STEEL_ARROW
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.STEEL_ARROW
Initial value:
=(true, 886, 887, 5618, 5624) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel arrow");
        }
    }
Definition at line 323 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel arrow");
        }
    },
STEEL_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.STEEL_BOLTS
Initial value:
=(true, 9141, 9288, 9295, 9302, 9336, 9239) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel bolts");
        }
    }
Definition at line 378 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel bolts");
        }
    },
STEEL_DART
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.STEEL_DART
Initial value:
=(true, 808, 814, 5630, 5637) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel dart");
        }
    }
Definition at line 182 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel dart");
        }
    },
Referenced by isDart().
STEEL_JAVELIN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.STEEL_JAVELIN
Initial value:
=(false, 827, 833, 5644, 5650) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel javelin");
        }
    }
Definition at line 31 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel javelin");
        }
    },
STEEL_KNIFE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.STEEL_KNIFE
Initial value:
=(true, 865, 872, 5656, 5663) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel knife");
        }
    }
Definition at line 231 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel knife");
        }
    },
STEEL_THROWNAXE
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.STEEL_THROWNAXE
Initial value:
=(true, 802) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel thrownaxe");
        }
    }
Definition at line 74 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Steel thrownaxe");
        }
    },
TARROMIN_TAR
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.TARROMIN_TAR
Initial value:
=(false, 10144) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Tarromin tar");
        }
    }
Definition at line 535 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Tarromin tar");
        }
    },
TOKTZ_XIL_UL
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.TOKTZ_XIL_UL
Initial value:
=(true, 6522) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Toktz-xil-ul");
        }
    }
Definition at line 446 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Toktz-xil-ul");
        }
    },
TRAHEAERN
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.TRAHEAERN
Initial value:
=(false, 25888) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Traheaern");
        }
    }
Definition at line 132 of file RangedAmmunition.java.
                            { //PURPLE
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Traheaern");
        }
    },
TRAINING_ARROWS
com.runehive.game.world.entity.combat.ranged.RangedAmmunition.TRAINING_ARROWS
Initial value:
=(true, 9706) {
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Training arrows");
        }
    }
Definition at line 471 of file RangedAmmunition.java.
{
        @Override
        public CombatProjectile getProjectile() {
            return getDefinition("Training arrows");
        }
    },
values
final RangedAmmunition [] com.runehive.game.world.entity.combat.ranged.RangedAmmunition.values = values() static private
Definition at line 564 of file RangedAmmunition.java.
Referenced by [static initializer](), and find().
weapons
final int [] com.runehive.game.world.entity.combat.ranged.RangedAmmunition.weapons private
Definition at line 550 of file RangedAmmunition.java.
Referenced by RangedAmmunition().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/ranged/RangedAmmunition.java