RuneHive-Game: com.runehive.content.RoyaltyProgram.RoyaltyReward Enum Reference
com.runehive.content.RoyaltyProgram.RoyaltyReward Enum Reference
Holds all the RoyaltyReward data.
Public Member Functions
int getLevel ()
Item getReward ()
RoyaltyReward (int level, Item reward)
Static Public Member Functions
static Optional< RoyaltyReward > forLevel (int level)
static Optional< RoyaltyReward > forOrdinal (int ordinal)
Private Attributes
final int level
final Item reward
Detailed Description
Holds all the RoyaltyReward data.
Definition at line 27 of file RoyaltyProgram.java.
Constructor & Destructor Documentation
RoyaltyReward()
com.runehive.content.RoyaltyProgram.RoyaltyReward.RoyaltyReward (int level, Item reward)
Definition at line 41 of file RoyaltyProgram.java.
{
            this.level = level;
            this.reward = reward;
        }
References level, and reward.
Member Function Documentation
forLevel()
Optional< RoyaltyReward > com.runehive.content.RoyaltyProgram.RoyaltyReward.forLevel (int level) static
Definition at line 54 of file RoyaltyProgram.java.
{
            return Arrays.stream(values()).filter(a -> a.level == level).findAny();
        }
References level.
Referenced by com.runehive.content.RoyaltyProgram.append().
forOrdinal()
Optional< RoyaltyReward > com.runehive.content.RoyaltyProgram.RoyaltyReward.forOrdinal (int ordinal) static
Definition at line 58 of file RoyaltyProgram.java.
{
            return Arrays.stream(values()).filter(a -> a.ordinal() == ordinal).findAny();
        }
Referenced by com.runehive.content.RoyaltyProgram.open().
getLevel()
int com.runehive.content.RoyaltyProgram.RoyaltyReward.getLevel ()
Definition at line 46 of file RoyaltyProgram.java.
{
            return level;
        }
References level.
Referenced by com.runehive.content.RoyaltyProgram.open().
getReward()
Item com.runehive.content.RoyaltyProgram.RoyaltyReward.getReward ()
Definition at line 50 of file RoyaltyProgram.java.
{
            return reward;
        }
References reward.
Referenced by com.runehive.content.RoyaltyProgram.append(), and com.runehive.content.RoyaltyProgram.open().
Member Data Documentation
level
final int com.runehive.content.RoyaltyProgram.RoyaltyReward.level private
Definition at line 38 of file RoyaltyProgram.java.
Referenced by forLevel(), getLevel(), and RoyaltyReward().
reward
final Item com.runehive.content.RoyaltyProgram.RoyaltyReward.reward private
Definition at line 39 of file RoyaltyProgram.java.
Referenced by getReward(), and RoyaltyReward().
The documentation for this enum was generated from the following file:
java/com/runehive/content/RoyaltyProgram.java