RuneHive-Game: com.runehive.content.gambling.Flowers Enum Reference
com.runehive.content.gambling.Flowers Enum Reference
Public Member Functions
Flowers (int id)
The id.
int getId ()
Gets the id.
void setId (int id)
Sets the id.
Public Attributes
BLACK =(2988)
The black flower.
BLUE =(2982)
The blue flower.
ORANGE =(2985)
The orange flower.
PASTEL =(2980)
The pastel flower.
PURPLE =(2984)
The purple flower.
RAINBOW =(2986)
The rainbow flower.
RED =(2981)
The red flower.
WHITE =(2987)
The white flower.
YELLOW =(2983)
The yellow.
Private Attributes
int id
The id.
Detailed Description
Definition at line 3 of file Flowers.java.
Constructor & Destructor Documentation
Flowers()
com.runehive.content.gambling.Flowers.Flowers (int id)
The id.
Parameters
id the id
Definition at line 52 of file Flowers.java.
                    {
        this.setId(id);
    }
References setId().
Member Function Documentation
getId()
int com.runehive.content.gambling.Flowers.getId ()
Gets the id.
Returns
the id
Definition at line 61 of file Flowers.java.
                       {
        return id;
    }
References id.
Referenced by com.runehive.content.gambling.impl.FlowerPoker.plant().
setId()
void com.runehive.content.gambling.Flowers.setId (int id)
Sets the id.
Parameters
id the id
Definition at line 71 of file Flowers.java.
{
        this.id = id;
    }
References id.
Referenced by Flowers().
Member Data Documentation
BLACK
com.runehive.content.gambling.Flowers.BLACK =(2988)
The black flower.
Definition at line 7 of file Flowers.java.
Referenced by com.runehive.content.gambling.impl.FlowerPoker.gamble().
BLUE
com.runehive.content.gambling.Flowers.BLUE =(2982)
The blue flower.
Definition at line 11 of file Flowers.java.
id
int com.runehive.content.gambling.Flowers.id private
The id.
Definition at line 44 of file Flowers.java.
Referenced by getId(), and setId().
ORANGE
com.runehive.content.gambling.Flowers.ORANGE =(2985)
The orange flower.
Definition at line 15 of file Flowers.java.
PASTEL
com.runehive.content.gambling.Flowers.PASTEL =(2980)
The pastel flower.
Purple, blue, cyan
Definition at line 19 of file Flowers.java.
PURPLE
com.runehive.content.gambling.Flowers.PURPLE =(2984)
The purple flower.
Definition at line 23 of file Flowers.java.
RAINBOW
com.runehive.content.gambling.Flowers.RAINBOW =(2986)
The rainbow flower.
Red, yellow, blue
Definition at line 27 of file Flowers.java.
RED
com.runehive.content.gambling.Flowers.RED =(2981)
The red flower.
Definition at line 31 of file Flowers.java.
WHITE
com.runehive.content.gambling.Flowers.WHITE =(2987)
The white flower.
Definition at line 35 of file Flowers.java.
Referenced by com.runehive.content.gambling.impl.FlowerPoker.gamble().
YELLOW
com.runehive.content.gambling.Flowers.YELLOW =(2983)
The yellow.
Definition at line 39 of file Flowers.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/gambling/Flowers.java