RuneHive-Game: com.runehive.game.world.entity.combat.attack.FightType Enum Reference
com.runehive.game.world.entity.combat.attack.FightType Enum Reference
The enumerated type whose elements represent the fighting types.
Public Member Functions
FightType (int animation, int delay, int distance, int parent, int child, int button, int bonus, FightStyle style)
Creates a new FightType.
final int getAnimation ()
Gets the animation executed when this type is active.
final int getBonus ()
Gets the type of bonus this global will apply.
int getButton ()
final int getChild ()
Gets the child config identification.
final int getCorrespondingBonus ()
Determines the corresponding bonus for this fight type.
final int getDelay ()
Gets the attack delay.
int getDistance ()
Gets the attack distance.
final int getParent ()
Gets the parent config identification.
final FightStyle getStyle ()
Gets the style active when this type is active.
Public Attributes
BALLISTA_ACCURATE =(7218, 7, 10, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
BALLISTA_LONGRANGE =(7218, 7, 10, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
BALLISTA_RAPID =(7218, 6, 10, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
BATTLEAXE_BLOCK =(401, 6, 1, 43, 3, 1705, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
BATTLEAXE_CHOP =(401, 6, 1, 43, 0, 1704, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
BATTLEAXE_HACK =(401, 6, 1, 43, 1, 1707, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
BATTLEAXE_SMASH =(401, 6, 1, 43, 2, 1706, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
BLAZE =(5247, 5, 1, 43, 3, 24080, Equipment.MAGIC_OFFENSE, FightStyle.ACCURATE)
BLOWPIPE_ACCURATE =(5061, 4, 7, 43, 0, 4454, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
BLOWPIPE_LONGRANGE =(5061, 4, 7, 43, 2, 4452, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
BLOWPIPE_RAPID =(5061, 3, 7, 43, 1, 4453, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
BLUDGEN_BLOCK =(7054, 4, 1, 43, 3, 4712, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
BLUDGEN_CHOP =(7054, 4, 1, 43, 0, 4711, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
BLUDGEN_SLASH =(7054, 4, 1, 43, 1, 4713, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
BLUDGEN_SMASH =(7054, 4, 1, 43, 2, 4714, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
BULWARK_BLOCK =(7511, 7, 1, 43, 2, 431, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
BULWARK_POUND =(7511, 7, 1, 43, 0, 433, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
BULWARK_PUMMEL =(7511, 7, 1, 43, 1, 432, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
CLAWS_BLOCK =(393, 4, 1, 43, 3, 7769, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
CLAWS_CHOP =(393, 4, 1, 43, 0, 7768, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
CLAWS_LUNGE =(393, 4, 1, 43, 2, 7770, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
CLAWS_SLASH =(393, 4, 1, 43, 1, 7771, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
CROSSBOW_ACCURATE =(4230, 6, 7, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
CROSSBOW_LONGRANGE =(4230, 6, 9, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
CROSSBOW_RAPID =(4230, 5, 7, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
DAGGER_BLOCK =(412, 4, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
DAGGER_LUNGE =(412, 4, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
DAGGER_SLASH =(395, 4, 1, 43, 2, 2284, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
DAGGER_STAB =(412, 4, 1, 43, 0, 2282, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
DARK_BOW_ACCURATE =(426, 9, 9, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
DARK_BOW_LONGRANGE =(426, 9, 10, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
DARK_BOW_RAPID =(426, 8, 9, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
DART_ACCURATE =(929, 3, 5, 43, 0, 4454, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
DART_LONGRANGE =(929, 3, 3, 43, 2, 4452, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
DART_RAPID =(929, 2, 5, 43, 1, 4453, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
DRAGON_DAGGER_BLOCK =(402, 4, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
DRAGON_DAGGER_LUNGE =(402, 4, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
DRAGON_DAGGER_SLASH =(395, 4, 1, 43, 2, 2284, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
DRAGON_DAGGER_STAB =(402, 4, 1, 43, 0, 2282, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
ELDER_MAUL_BLOCK =(7516, 6, 1, 43, 2, 1665, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
ELDER_MAUL_POUND =(7516, 6, 1, 43, 0, 1665, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
ELDER_MAUL_PUMMEL =(7516, 6, 1, 43, 1, 1665, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
FANG_BLOCK =(9471, 5, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
FANG_LUNGE =(9471, 5, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
FANG_SLASH =(390, 5, 1, 43, 2, 2284, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
FANG_STAB =(9471, 5, 1, 43, 0, 2429, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
FLAIL_BLOCK =(2062, 5, 1, 43, 3, 3803, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
FLAIL_POUND =(2062, 5, 1, 43, 0, 3802, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
FLAIL_PUMMEL =(2062, 5, 1, 43, 1, 3805, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
FLAIL_SPIKE =(2062, 5, 1, 43, 2, 3804, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
FLARE =(5247, 5, 1, 43, 2, 24079, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
GHRAZI_BLOCK =(8145, 4, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
GHRAZI_LUNGE =(8145, 4, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
GHRAZI_SLASH =(390, 4, 1, 43, 2, 2284, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
GHRAZI_STAB =(8145, 4, 1, 43, 0, 2282, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
GODSWORD_BLOCK =(7055, 6, 1, 43, 3, 4712, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
GODSWORD_CHOP =(7046, 6, 1, 43, 0, 4711, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
GODSWORD_SLASH =(7045, 6, 1, 43, 1, 4714, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
GODSWORD_SMASH =(7054, 6, 1, 43, 2, 4713, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
GRANITE_MAUL_BLOCK =(1665, 6, 1, 43, 2, 1665, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
GRANITE_MAUL_POUND =(1665, 6, 1, 43, 0, 1665, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
GRANITE_MAUL_PUMMEL =(1665, 6, 1, 43, 1, 1665, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
GREATAXE_BLOCK =(2062, 6, 1, 43, 3, 1705, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
GREATAXE_CHOP =(2062, 6, 1, 43, 0, 1704, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
GREATAXE_HACK =(2062, 6, 1, 43, 1, 1707, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
GREATAXE_SMASH =(2066, 6, 1, 43, 2, 1706, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
HALBERD_FEND =(440, 7, 2, 43, 2, 8467, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
HALBERD_JAB =(440, 7, 2, 43, 0, 8466, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
HALBERD_SWIPE =(440, 7, 2, 43, 1, 8468, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
HUNTER_LANCE_BLOCK =(8288, 5, 1, 43, 3, 4686, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
HUNTER_LANCE_LUNGE =(8288, 5, 1, 43, 0, 4685, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
HUNTER_LANCE_POUND =(8290, 5, 1, 43, 2, 4687, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
HUNTER_LANCE_SWIPE =(8289, 5, 1, 43, 1, 4688, Equipment.SLASH_OFFENSE, FightStyle.CONTROLLED)
INQUISITOR_MACE_BLOCK =(4503, 5, 1, 43, 3, 3803, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
INQUISITOR_MACE_POUND =(4503, 5, 1, 43, 0, 3802, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
INQUISITOR_MACE_PUMMEL =(4503, 5, 1, 43, 1, 3805, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
INQUISITOR_MACE_SPIKE =(400, 5, 1, 43, 2, 3804, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
KARIL_CROSSBOW_ACCURATE =(2075, 6, 7, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
KARIL_CROSSBOW_LONGRANGE =(2075, 6, 9, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
KARIL_CROSSBOW_RAPID =(2075, 5, 7, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
KNIFE_ACCURATE =(929, 3, 6, 43, 0, 4454, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
KNIFE_LONGRANGE =(929, 3, 4, 43, 2, 4452, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
KNIFE_RAPID =(929, 2, 6, 43, 1, 4453, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
LONG_FUSE =(2779, 4, 10, 43, 3, 24061, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
LONGBOW_ACCURATE =(426, 6, 9, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
LONGBOW_LONGRANGE =(426, 6, 10, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
LONGBOW_RAPID =(426, 5, 9, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
LONGSWORD_BLOCK =(390, 5, 1, 43, 3, 2430, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
LONGSWORD_CHOP =(390, 5, 1, 43, 0, 2429, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
LONGSWORD_LUNGE =(386, 5, 1, 43, 2, 2431, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
LONGSWORD_SLASH =(390, 5, 1, 43, 1, 2432, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
MACE_BLOCK =(401, 5, 1, 43, 3, 3803, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
MACE_POUND =(401, 5, 1, 43, 0, 3802, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
MACE_PUMMEL =(401, 5, 1, 43, 1, 3805, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
MACE_SPIKE =(400, 5, 1, 43, 2, 3804, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
MEDIUM_FUSE =(2779, 3, 8, 43, 2, 24060, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
NIGHTMARE_STAFF_BASH =(4505, 5, 1, 43, 0, 6137, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
NIGHTMARE_STAFF_FOCUS =(4505, 5, 1, 43, 2, 6135, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
NIGHTMARE_STAFF_POUND =(4505, 5, 1, 43, 1, 6136, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
PICKAXE_BLOCK =(400, 4, 1, 43, 3, 5577, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
PICKAXE_IMPALE =(400, 4, 1, 43, 1, 5579, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
PICKAXE_SMASH =(401, 4, 1, 43, 2, 5578, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
PICKAXE_SPIKE =(400, 4, 1, 43, 0, 5567, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
SAELDOR_BLOCK =(390, 4, 1, 43, 3, 2430, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
SAELDOR_CRUSH =(386, 4, 1, 43, 2, 2431, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
SAELDOR_SLASH =(390, 4, 1, 43, 1, 2432, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
SAELDOR_STAB =(390, 4, 1, 43, 0, 2429, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
SARADOMIN_BLOCK =(7055, 4, 1, 43, 3, 4712, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
SARADOMIN_CHOP =(7046, 4, 1, 43, 0, 4711, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
SARADOMIN_SLASH =(7045, 4, 1, 43, 2, 4714, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
SARADOMIN_SMASH =(7054, 4, 1, 43, 1, 4713, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
SCIMITAR_BLOCK =(390, 4, 1, 43, 3, 2430, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
SCIMITAR_CHOP =(390, 4, 1, 43, 0, 2429, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
SCIMITAR_LUNGE =(386, 4, 1, 43, 2, 2431, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
SCIMITAR_SLASH =(390, 4, 1, 43, 1, 2432, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
SCORCH =(5247, 5, 1, 43, 0, 24078, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
SCYTHE_BLOCK =(382, 7, 1, 43, 3, 783, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
SCYTHE_CHOP =(382, 7, 1, 43, 1, 784, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
SCYTHE_JAB =(2066, 7, 1, 43, 2, 785, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
SCYTHE_REAP =(414, 7, 1, 43, 0, 782, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
SHADOW_ACCURATE =(9493, 10, 8, 43, 0, 4454, Equipment.MAGIC_OFFENSE, FightStyle.ACCURATE)
SHADOW_LONGRANGE =(9493, 10, 8, 43, 2, 4452, Equipment.MAGIC_OFFENSE, FightStyle.DEFENSIVE)
SHADOW_RAPID =(9493, 9, 8, 43, 1, 4453, Equipment.MAGIC_OFFENSE, FightStyle.AGGRESSIVE)
SHORT_FUSE =(2779, 4, 8, 443, 0, 24059, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
SHORTBOW_ACCURATE =(426, 4, 7, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
SHORTBOW_LONGRANGE =(426, 4, 9, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
SHORTBOW_RAPID =(426, 3, 7, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
SPEAR_BLOCK =(2082, 5, 1, 43, 3, 4686, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
SPEAR_LUNGE =(2080, 5, 1, 43, 0, 4685, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
SPEAR_POUND =(2080, 5, 1, 43, 2, 4687, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
SPEAR_SWIPE =(2081, 5, 1, 43, 1, 4688, Equipment.SLASH_OFFENSE, FightStyle.CONTROLLED)
STAFF_BASH =(401, 5, 1, 43, 0, 6137, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
STAFF_FOCUS =(406, 5, 1, 43, 2, 6135, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
STAFF_POUND =(406, 5, 1, 43, 1, 6136, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
SWORD_BLOCK =(412, 4, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
SWORD_LUNGE =(412, 4, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
SWORD_SLASH =(395, 4, 1, 43, 2, 2284, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
SWORD_STAB =(412, 4, 1, 43, 0, 2282, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
THROWNAXE_ACCURATE =(929, 5, 4, 43, 0, 4454, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
THROWNAXE_LONGRANGE =(929, 5, 6, 43, 2, 4452, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
THROWNAXE_RAPID =(929, 4, 4, 43, 1, 4453, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
TRIDENT_ACCURATE =(929, 4, 8, 43, 0, 791, Equipment.MAGIC_OFFENSE, FightStyle.ACCURATE)
TRIDENT_LONGRANGE =(929, 4, 10, 43, 2, 791, Equipment.MAGIC_OFFENSE, FightStyle.DEFENSIVE)
TRIDENT_RAPID =(929, 4, 8, 43, 1, 791, Equipment.MAGIC_OFFENSE, FightStyle.AGGRESSIVE)
TWOHANDEDSWORD_BLOCK =(407, 7, 1, 43, 3, 4712, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
TWOHANDEDSWORD_CHOP =(407, 7, 1, 43, 0, 4711, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
TWOHANDEDSWORD_SLASH =(407, 7, 1, 43, 1, 4713, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
TWOHANDEDSWORD_SMASH =(406, 7, 1, 43, 2, 4714, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
UNARMED_BLOCK =(422, 4, 1, 43, 2, 5861, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
UNARMED_KICK =(423, 4, 1, 43, 1, 5862, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
UNARMED_PUNCH =(422, 4, 1, 43, 0, 5860, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
VIGGORA_MACE_BLOCK =(245, 5, 1, 43, 3, 3803, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
VIGGORA_MACE_POUND =(245, 5, 1, 43, 0, 3802, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
VIGGORA_MACE_PUMMEL =(245, 5, 1, 43, 1, 3805, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
VIGGORA_MACE_SPIKE =(245, 5, 1, 43, 2, 3804, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
VITUR_BLOCK =(8056, 5, 1, 43, 3, 783, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
VITUR_CHOP =(8056, 5, 1, 43, 1, 784, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
VITUR_JAB =(8056, 5, 1, 43, 2, 785, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
VITUR_REAP =(8056, 5, 1, 43, 0, 782, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
WARHAMMER_BLOCK =(401, 6, 1, 43, 2, 431, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
WARHAMMER_POUND =(401, 6, 1, 43, 0, 433, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
WARHAMMER_PUMMEL =(401, 6, 1, 43, 1, 432, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
WHIP_DEFLECT =(1658, 4, 1, 43, 2, 12296, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
WHIP_FLICK =(1658, 4, 1, 43, 0, 12298, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
WHIP_LASH =(1658, 4, 1, 43, 1, 12297, Equipment.SLASH_OFFENSE, FightStyle.CONTROLLED)
ZARYTE_ACCURATE =(9166, 6, 7, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
ZARYTE_LONGRANGE =(9166, 6, 9, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
ZARYTE_RAPID =(9166, 5, 7, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Private Attributes
final int animation
The animation executed when this type is active.
final int bonus
The type of bonus this global attributes to.
final int button
The style button identification.
final int child
The child config identification.
final int delay
The attack delay.
final int distance
The attack distance.
final int parent
The parent config identification.
final FightStyle style
The style active when this type is active.
Detailed Description
The enumerated type whose elements represent the fighting types.
Author
lare96 http://github.com/lare96
Definition at line 10 of file FightType.java.
Constructor & Destructor Documentation
FightType()
com.runehive.game.world.entity.combat.attack.FightType.FightType (int animation, int delay, int distance, int parent, int child, int button, int bonus, FightStyle style)
Creates a new FightType.
Parameters
animation the animation executed when this type is active
delay the attack delay
parent the parent config identification
child the child config identification
bonus the type of bonus this global will apply
style the style active when this type is active
Definition at line 269 of file FightType.java.
{
        this.animation = animation;
        this.delay = delay;
        this.distance = distance;
        this.parent = parent;
        this.child = child;
        this.button = button;
        this.bonus = bonus;
        this.style = style;
    }
References animation, bonus, button, child, delay, distance, parent, and style.
Member Function Documentation
getAnimation()
final int com.runehive.game.world.entity.combat.attack.FightType.getAnimation ()
Gets the animation executed when this type is active.
Returns
the animation executed
Definition at line 307 of file FightType.java.
{
        return animation;
    }
References animation.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getAttackAnimation(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackAnimation(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackAnimation().
getBonus()
final int com.runehive.game.world.entity.combat.attack.FightType.getBonus ()
Gets the type of bonus this global will apply.
Returns
the bonus type
Definition at line 351 of file FightType.java.
{
        return bonus;
    }
References bonus.
Referenced by getCorrespondingBonus(), and com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyOffensiveBonus().
getButton()
int com.runehive.game.world.entity.combat.attack.FightType.getButton ()
Definition at line 364 of file FightType.java.
{
        return button;
    }
References button.
getChild()
final int com.runehive.game.world.entity.combat.attack.FightType.getChild ()
Gets the child config identification.
Returns
the child config
Definition at line 342 of file FightType.java.
{
        return child;
    }
References child.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute().
getCorrespondingBonus()
final int com.runehive.game.world.entity.combat.attack.FightType.getCorrespondingBonus ()
Determines the corresponding bonus for this fight type.
Returns
the corresponding.
Definition at line 285 of file FightType.java.
{
        switch (getBonus()) {
            case Equipment.CRUSH_OFFENSE:
                return Equipment.CRUSH_DEFENCE;
            case Equipment.MAGIC_OFFENSE:
                return Equipment.MAGIC_DEFENSE;
            case Equipment.RANGED_OFFENSE:
                return Equipment.RANGED_DEFENSE;
            case Equipment.SLASH_OFFENSE:
                return Equipment.SLASH_DEFENSE;
            case Equipment.STAB_OFFENSE:
                return Equipment.STAB_DEFENSE;
            default:
                return Equipment.CRUSH_DEFENCE;
        }
    }
References com.runehive.game.world.items.containers.equipment.Equipment.CRUSH_DEFENCE, com.runehive.game.world.items.containers.equipment.Equipment.CRUSH_OFFENSE, getBonus(), com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_DEFENSE, com.runehive.game.world.items.containers.equipment.Equipment.MAGIC_OFFENSE, com.runehive.game.world.items.containers.equipment.Equipment.RANGED_DEFENSE, com.runehive.game.world.items.containers.equipment.Equipment.RANGED_OFFENSE, com.runehive.game.world.items.containers.equipment.Equipment.SLASH_DEFENSE, com.runehive.game.world.items.containers.equipment.Equipment.SLASH_OFFENSE, com.runehive.game.world.items.containers.equipment.Equipment.STAB_DEFENSE, and com.runehive.game.world.items.containers.equipment.Equipment.STAB_OFFENSE.
Referenced by com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensiveBonus().
getDelay()
final int com.runehive.game.world.entity.combat.attack.FightType.getDelay ()
Gets the attack delay.
Returns
the attack delay
Definition at line 316 of file FightType.java.
{
        return delay;
    }
References delay.
getDistance()
int com.runehive.game.world.entity.combat.attack.FightType.getDistance ()
Gets the attack distance.
Returns
the attack distance
Definition at line 324 of file FightType.java.
{
        return distance;
    }
References distance.
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.getAttackDistance(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getAttackDistance(), and com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getAttackDistance().
getParent()
final int com.runehive.game.world.entity.combat.attack.FightType.getParent ()
Gets the parent config identification.
Returns
the parent config
Definition at line 333 of file FightType.java.
{
        return parent;
    }
References parent.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute().
getStyle()
final FightStyle com.runehive.game.world.entity.combat.attack.FightType.getStyle ()
Gets the style active when this type is active.
Returns
the fighting style
Definition at line 360 of file FightType.java.
{
        return style;
    }
References style.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), com.runehive.content.overrides.Overrides.getFightType(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAccuracy(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressive(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensive(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensive(), and com.runehive.game.world.entity.combat.Combat< T extends Mob >.setFightType().
Member Data Documentation
animation
final int com.runehive.game.world.entity.combat.attack.FightType.animation private
The animation executed when this type is active.
Definition at line 236 of file FightType.java.
Referenced by FightType(), and getAnimation().
BALLISTA_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.BALLISTA_ACCURATE =(7218, 7, 10, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 66 of file FightType.java.
BALLISTA_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.BALLISTA_LONGRANGE =(7218, 7, 10, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 68 of file FightType.java.
BALLISTA_RAPID
com.runehive.game.world.entity.combat.attack.FightType.BALLISTA_RAPID =(7218, 6, 10, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 67 of file FightType.java.
BATTLEAXE_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.BATTLEAXE_BLOCK =(401, 6, 1, 43, 3, 1705, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 48 of file FightType.java.
BATTLEAXE_CHOP
com.runehive.game.world.entity.combat.attack.FightType.BATTLEAXE_CHOP =(401, 6, 1, 43, 0, 1704, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 45 of file FightType.java.
BATTLEAXE_HACK
com.runehive.game.world.entity.combat.attack.FightType.BATTLEAXE_HACK =(401, 6, 1, 43, 1, 1707, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 46 of file FightType.java.
BATTLEAXE_SMASH
com.runehive.game.world.entity.combat.attack.FightType.BATTLEAXE_SMASH =(401, 6, 1, 43, 2, 1706, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 47 of file FightType.java.
BLAZE
com.runehive.game.world.entity.combat.attack.FightType.BLAZE =(5247, 5, 1, 43, 3, 24080, Equipment.MAGIC_OFFENSE, FightStyle.ACCURATE)
Definition at line 233 of file FightType.java.
Referenced by com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.addCombatExperience().
BLOWPIPE_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.BLOWPIPE_ACCURATE =(5061, 4, 7, 43, 0, 4454, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 223 of file FightType.java.
BLOWPIPE_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.BLOWPIPE_LONGRANGE =(5061, 4, 7, 43, 2, 4452, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 225 of file FightType.java.
BLOWPIPE_RAPID
com.runehive.game.world.entity.combat.attack.FightType.BLOWPIPE_RAPID =(5061, 3, 7, 43, 1, 4453, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 224 of file FightType.java.
BLUDGEN_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.BLUDGEN_BLOCK =(7054, 4, 1, 43, 3, 4712, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 173 of file FightType.java.
BLUDGEN_CHOP
com.runehive.game.world.entity.combat.attack.FightType.BLUDGEN_CHOP =(7054, 4, 1, 43, 0, 4711, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 170 of file FightType.java.
BLUDGEN_SLASH
com.runehive.game.world.entity.combat.attack.FightType.BLUDGEN_SLASH =(7054, 4, 1, 43, 1, 4713, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 171 of file FightType.java.
BLUDGEN_SMASH
com.runehive.game.world.entity.combat.attack.FightType.BLUDGEN_SMASH =(7054, 4, 1, 43, 2, 4714, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 172 of file FightType.java.
bonus
final int com.runehive.game.world.entity.combat.attack.FightType.bonus private
The type of bonus this global attributes to.
Definition at line 254 of file FightType.java.
Referenced by FightType(), and getBonus().
BULWARK_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.BULWARK_BLOCK =(7511, 7, 1, 43, 2, 431, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 25 of file FightType.java.
BULWARK_POUND
com.runehive.game.world.entity.combat.attack.FightType.BULWARK_POUND =(7511, 7, 1, 43, 0, 433, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 23 of file FightType.java.
BULWARK_PUMMEL
com.runehive.game.world.entity.combat.attack.FightType.BULWARK_PUMMEL =(7511, 7, 1, 43, 1, 432, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 24 of file FightType.java.
button
final int com.runehive.game.world.entity.combat.attack.FightType.button private
The style button identification.
Definition at line 251 of file FightType.java.
Referenced by FightType(), and getButton().
child
final int com.runehive.game.world.entity.combat.attack.FightType.child private
The child config identification.
Definition at line 248 of file FightType.java.
Referenced by FightType(), and getChild().
CLAWS_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.CLAWS_BLOCK =(393, 4, 1, 43, 3, 7769, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 193 of file FightType.java.
CLAWS_CHOP
com.runehive.game.world.entity.combat.attack.FightType.CLAWS_CHOP =(393, 4, 1, 43, 0, 7768, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 190 of file FightType.java.
CLAWS_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.CLAWS_LUNGE =(393, 4, 1, 43, 2, 7770, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 192 of file FightType.java.
CLAWS_SLASH
com.runehive.game.world.entity.combat.attack.FightType.CLAWS_SLASH =(393, 4, 1, 43, 1, 7771, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 191 of file FightType.java.
Referenced by com.runehive.content.bot.botclass.impl.PureMelee.hit().
CROSSBOW_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.CROSSBOW_ACCURATE =(4230, 6, 7, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 55 of file FightType.java.
CROSSBOW_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.CROSSBOW_LONGRANGE =(4230, 6, 9, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 57 of file FightType.java.
CROSSBOW_RAPID
com.runehive.game.world.entity.combat.attack.FightType.CROSSBOW_RAPID =(4230, 5, 7, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 56 of file FightType.java.
DAGGER_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.DAGGER_BLOCK =(412, 4, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 85 of file FightType.java.
DAGGER_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.DAGGER_LUNGE =(412, 4, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 83 of file FightType.java.
DAGGER_SLASH
com.runehive.game.world.entity.combat.attack.FightType.DAGGER_SLASH =(395, 4, 1, 43, 2, 2284, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 84 of file FightType.java.
DAGGER_STAB
com.runehive.game.world.entity.combat.attack.FightType.DAGGER_STAB =(412, 4, 1, 43, 0, 2282, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
Definition at line 82 of file FightType.java.
DARK_BOW_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.DARK_BOW_ACCURATE =(426, 9, 9, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 78 of file FightType.java.
DARK_BOW_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.DARK_BOW_LONGRANGE =(426, 9, 10, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 80 of file FightType.java.
DARK_BOW_RAPID
com.runehive.game.world.entity.combat.attack.FightType.DARK_BOW_RAPID =(426, 8, 9, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 79 of file FightType.java.
DART_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.DART_ACCURATE =(929, 3, 5, 43, 0, 4454, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 211 of file FightType.java.
DART_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.DART_LONGRANGE =(929, 3, 3, 43, 2, 4452, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 213 of file FightType.java.
DART_RAPID
com.runehive.game.world.entity.combat.attack.FightType.DART_RAPID =(929, 2, 5, 43, 1, 4453, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 212 of file FightType.java.
delay
final int com.runehive.game.world.entity.combat.attack.FightType.delay private
The attack delay.
Definition at line 239 of file FightType.java.
Referenced by FightType(), and getDelay().
distance
final int com.runehive.game.world.entity.combat.attack.FightType.distance private
The attack distance.
Definition at line 242 of file FightType.java.
Referenced by FightType(), and getDistance().
DRAGON_DAGGER_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.DRAGON_DAGGER_BLOCK =(402, 4, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 94 of file FightType.java.
DRAGON_DAGGER_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.DRAGON_DAGGER_LUNGE =(402, 4, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 92 of file FightType.java.
Referenced by com.runehive.content.bot.botclass.impl.WelfareRuneMelee.hit(), and com.runehive.content.bot.botclass.impl.ZerkerMelee.hit().
DRAGON_DAGGER_SLASH
com.runehive.game.world.entity.combat.attack.FightType.DRAGON_DAGGER_SLASH =(395, 4, 1, 43, 2, 2284, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 93 of file FightType.java.
DRAGON_DAGGER_STAB
com.runehive.game.world.entity.combat.attack.FightType.DRAGON_DAGGER_STAB =(402, 4, 1, 43, 0, 2282, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
Definition at line 91 of file FightType.java.
ELDER_MAUL_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.ELDER_MAUL_BLOCK =(7516, 6, 1, 43, 2, 1665, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 33 of file FightType.java.
ELDER_MAUL_POUND
com.runehive.game.world.entity.combat.attack.FightType.ELDER_MAUL_POUND =(7516, 6, 1, 43, 0, 1665, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 31 of file FightType.java.
ELDER_MAUL_PUMMEL
com.runehive.game.world.entity.combat.attack.FightType.ELDER_MAUL_PUMMEL =(7516, 6, 1, 43, 1, 1665, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 32 of file FightType.java.
Referenced by com.runehive.content.bot.botclass.impl.ZerkerMelee.hit().
FANG_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.FANG_BLOCK =(9471, 5, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 104 of file FightType.java.
FANG_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.FANG_LUNGE =(9471, 5, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 102 of file FightType.java.
FANG_SLASH
com.runehive.game.world.entity.combat.attack.FightType.FANG_SLASH =(390, 5, 1, 43, 2, 2284, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 103 of file FightType.java.
FANG_STAB
com.runehive.game.world.entity.combat.attack.FightType.FANG_STAB =(9471, 5, 1, 43, 0, 2429, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
Definition at line 101 of file FightType.java.
FLAIL_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.FLAIL_BLOCK =(2062, 5, 1, 43, 3, 3803, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 139 of file FightType.java.
FLAIL_POUND
com.runehive.game.world.entity.combat.attack.FightType.FLAIL_POUND =(2062, 5, 1, 43, 0, 3802, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 136 of file FightType.java.
FLAIL_PUMMEL
com.runehive.game.world.entity.combat.attack.FightType.FLAIL_PUMMEL =(2062, 5, 1, 43, 1, 3805, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 137 of file FightType.java.
FLAIL_SPIKE
com.runehive.game.world.entity.combat.attack.FightType.FLAIL_SPIKE =(2062, 5, 1, 43, 2, 3804, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 138 of file FightType.java.
FLARE
com.runehive.game.world.entity.combat.attack.FightType.FLARE =(5247, 5, 1, 43, 2, 24079, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 232 of file FightType.java.
Referenced by com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.addCombatExperience().
GHRAZI_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.GHRAZI_BLOCK =(8145, 4, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 89 of file FightType.java.
GHRAZI_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.GHRAZI_LUNGE =(8145, 4, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 87 of file FightType.java.
GHRAZI_SLASH
com.runehive.game.world.entity.combat.attack.FightType.GHRAZI_SLASH =(390, 4, 1, 43, 2, 2284, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 88 of file FightType.java.
GHRAZI_STAB
com.runehive.game.world.entity.combat.attack.FightType.GHRAZI_STAB =(8145, 4, 1, 43, 0, 2282, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
Definition at line 86 of file FightType.java.
GODSWORD_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.GODSWORD_BLOCK =(7055, 6, 1, 43, 3, 4712, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 163 of file FightType.java.
GODSWORD_CHOP
com.runehive.game.world.entity.combat.attack.FightType.GODSWORD_CHOP =(7046, 6, 1, 43, 0, 4711, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 160 of file FightType.java.
GODSWORD_SLASH
com.runehive.game.world.entity.combat.attack.FightType.GODSWORD_SLASH =(7045, 6, 1, 43, 1, 4714, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 161 of file FightType.java.
Referenced by com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), and com.runehive.content.bot.botclass.impl.PureRangeMelee.hit().
GODSWORD_SMASH
com.runehive.game.world.entity.combat.attack.FightType.GODSWORD_SMASH =(7054, 6, 1, 43, 2, 4713, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 162 of file FightType.java.
GRANITE_MAUL_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.GRANITE_MAUL_BLOCK =(1665, 6, 1, 43, 2, 1665, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 29 of file FightType.java.
GRANITE_MAUL_POUND
com.runehive.game.world.entity.combat.attack.FightType.GRANITE_MAUL_POUND =(1665, 6, 1, 43, 0, 1665, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 27 of file FightType.java.
GRANITE_MAUL_PUMMEL
com.runehive.game.world.entity.combat.attack.FightType.GRANITE_MAUL_PUMMEL =(1665, 6, 1, 43, 1, 1665, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 28 of file FightType.java.
GREATAXE_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.GREATAXE_BLOCK =(2062, 6, 1, 43, 3, 1705, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 53 of file FightType.java.
GREATAXE_CHOP
com.runehive.game.world.entity.combat.attack.FightType.GREATAXE_CHOP =(2062, 6, 1, 43, 0, 1704, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 50 of file FightType.java.
GREATAXE_HACK
com.runehive.game.world.entity.combat.attack.FightType.GREATAXE_HACK =(2062, 6, 1, 43, 1, 1707, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 51 of file FightType.java.
GREATAXE_SMASH
com.runehive.game.world.entity.combat.attack.FightType.GREATAXE_SMASH =(2066, 6, 1, 43, 2, 1706, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 52 of file FightType.java.
HALBERD_FEND
com.runehive.game.world.entity.combat.attack.FightType.HALBERD_FEND =(440, 7, 2, 43, 2, 8467, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 197 of file FightType.java.
HALBERD_JAB
com.runehive.game.world.entity.combat.attack.FightType.HALBERD_JAB =(440, 7, 2, 43, 0, 8466, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 195 of file FightType.java.
HALBERD_SWIPE
com.runehive.game.world.entity.combat.attack.FightType.HALBERD_SWIPE =(440, 7, 2, 43, 1, 8468, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 196 of file FightType.java.
HUNTER_LANCE_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.HUNTER_LANCE_BLOCK =(8288, 5, 1, 43, 3, 4686, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 153 of file FightType.java.
HUNTER_LANCE_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.HUNTER_LANCE_LUNGE =(8288, 5, 1, 43, 0, 4685, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 150 of file FightType.java.
HUNTER_LANCE_POUND
com.runehive.game.world.entity.combat.attack.FightType.HUNTER_LANCE_POUND =(8290, 5, 1, 43, 2, 4687, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
Definition at line 152 of file FightType.java.
HUNTER_LANCE_SWIPE
com.runehive.game.world.entity.combat.attack.FightType.HUNTER_LANCE_SWIPE =(8289, 5, 1, 43, 1, 4688, Equipment.SLASH_OFFENSE, FightStyle.CONTROLLED)
Definition at line 151 of file FightType.java.
INQUISITOR_MACE_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.INQUISITOR_MACE_BLOCK =(4503, 5, 1, 43, 3, 3803, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 133 of file FightType.java.
INQUISITOR_MACE_POUND
com.runehive.game.world.entity.combat.attack.FightType.INQUISITOR_MACE_POUND =(4503, 5, 1, 43, 0, 3802, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 129 of file FightType.java.
INQUISITOR_MACE_PUMMEL
com.runehive.game.world.entity.combat.attack.FightType.INQUISITOR_MACE_PUMMEL =(4503, 5, 1, 43, 1, 3805, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 131 of file FightType.java.
INQUISITOR_MACE_SPIKE
com.runehive.game.world.entity.combat.attack.FightType.INQUISITOR_MACE_SPIKE =(400, 5, 1, 43, 2, 3804, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 132 of file FightType.java.
KARIL_CROSSBOW_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.KARIL_CROSSBOW_ACCURATE =(2075, 6, 7, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 62 of file FightType.java.
KARIL_CROSSBOW_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.KARIL_CROSSBOW_LONGRANGE =(2075, 6, 9, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 64 of file FightType.java.
KARIL_CROSSBOW_RAPID
com.runehive.game.world.entity.combat.attack.FightType.KARIL_CROSSBOW_RAPID =(2075, 5, 7, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 63 of file FightType.java.
KNIFE_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.KNIFE_ACCURATE =(929, 3, 6, 43, 0, 4454, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 141 of file FightType.java.
KNIFE_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.KNIFE_LONGRANGE =(929, 3, 4, 43, 2, 4452, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 143 of file FightType.java.
KNIFE_RAPID
com.runehive.game.world.entity.combat.attack.FightType.KNIFE_RAPID =(929, 2, 6, 43, 1, 4453, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 142 of file FightType.java.
LONG_FUSE
com.runehive.game.world.entity.combat.attack.FightType.LONG_FUSE =(2779, 4, 10, 43, 3, 24061, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 229 of file FightType.java.
LONGBOW_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.LONGBOW_ACCURATE =(426, 6, 9, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 74 of file FightType.java.
LONGBOW_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.LONGBOW_LONGRANGE =(426, 6, 10, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 76 of file FightType.java.
LONGBOW_RAPID
com.runehive.game.world.entity.combat.attack.FightType.LONGBOW_RAPID =(426, 5, 9, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 75 of file FightType.java.
LONGSWORD_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.LONGSWORD_BLOCK =(390, 5, 1, 43, 3, 2430, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 114 of file FightType.java.
LONGSWORD_CHOP
com.runehive.game.world.entity.combat.attack.FightType.LONGSWORD_CHOP =(390, 5, 1, 43, 0, 2429, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 111 of file FightType.java.
LONGSWORD_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.LONGSWORD_LUNGE =(386, 5, 1, 43, 2, 2431, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 113 of file FightType.java.
LONGSWORD_SLASH
com.runehive.game.world.entity.combat.attack.FightType.LONGSWORD_SLASH =(390, 5, 1, 43, 1, 2432, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 112 of file FightType.java.
MACE_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.MACE_BLOCK =(401, 5, 1, 43, 3, 3803, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 119 of file FightType.java.
MACE_POUND
com.runehive.game.world.entity.combat.attack.FightType.MACE_POUND =(401, 5, 1, 43, 0, 3802, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 116 of file FightType.java.
MACE_PUMMEL
com.runehive.game.world.entity.combat.attack.FightType.MACE_PUMMEL =(401, 5, 1, 43, 1, 3805, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 117 of file FightType.java.
MACE_SPIKE
com.runehive.game.world.entity.combat.attack.FightType.MACE_SPIKE =(400, 5, 1, 43, 2, 3804, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 118 of file FightType.java.
MEDIUM_FUSE
com.runehive.game.world.entity.combat.attack.FightType.MEDIUM_FUSE =(2779, 3, 8, 43, 2, 24060, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 228 of file FightType.java.
NIGHTMARE_STAFF_BASH
com.runehive.game.world.entity.combat.attack.FightType.NIGHTMARE_STAFF_BASH =(4505, 5, 1, 43, 0, 6137, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 15 of file FightType.java.
NIGHTMARE_STAFF_FOCUS
com.runehive.game.world.entity.combat.attack.FightType.NIGHTMARE_STAFF_FOCUS =(4505, 5, 1, 43, 2, 6135, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 17 of file FightType.java.
NIGHTMARE_STAFF_POUND
com.runehive.game.world.entity.combat.attack.FightType.NIGHTMARE_STAFF_POUND =(4505, 5, 1, 43, 1, 6136, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 16 of file FightType.java.
parent
final int com.runehive.game.world.entity.combat.attack.FightType.parent private
The parent config identification.
Definition at line 245 of file FightType.java.
Referenced by FightType(), and getParent().
PICKAXE_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.PICKAXE_BLOCK =(400, 4, 1, 43, 3, 5577, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 188 of file FightType.java.
PICKAXE_IMPALE
com.runehive.game.world.entity.combat.attack.FightType.PICKAXE_IMPALE =(400, 4, 1, 43, 1, 5579, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 186 of file FightType.java.
PICKAXE_SMASH
com.runehive.game.world.entity.combat.attack.FightType.PICKAXE_SMASH =(401, 4, 1, 43, 2, 5578, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 187 of file FightType.java.
PICKAXE_SPIKE
com.runehive.game.world.entity.combat.attack.FightType.PICKAXE_SPIKE =(400, 4, 1, 43, 0, 5567, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
Definition at line 185 of file FightType.java.
SAELDOR_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.SAELDOR_BLOCK =(390, 4, 1, 43, 3, 2430, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 178 of file FightType.java.
SAELDOR_CRUSH
com.runehive.game.world.entity.combat.attack.FightType.SAELDOR_CRUSH =(386, 4, 1, 43, 2, 2431, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
Definition at line 177 of file FightType.java.
SAELDOR_SLASH
com.runehive.game.world.entity.combat.attack.FightType.SAELDOR_SLASH =(390, 4, 1, 43, 1, 2432, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 176 of file FightType.java.
SAELDOR_STAB
com.runehive.game.world.entity.combat.attack.FightType.SAELDOR_STAB =(390, 4, 1, 43, 0, 2429, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 175 of file FightType.java.
SARADOMIN_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.SARADOMIN_BLOCK =(7055, 4, 1, 43, 3, 4712, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 168 of file FightType.java.
SARADOMIN_CHOP
com.runehive.game.world.entity.combat.attack.FightType.SARADOMIN_CHOP =(7046, 4, 1, 43, 0, 4711, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 165 of file FightType.java.
SARADOMIN_SLASH
com.runehive.game.world.entity.combat.attack.FightType.SARADOMIN_SLASH =(7045, 4, 1, 43, 2, 4714, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 167 of file FightType.java.
SARADOMIN_SMASH
com.runehive.game.world.entity.combat.attack.FightType.SARADOMIN_SMASH =(7054, 4, 1, 43, 1, 4713, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 166 of file FightType.java.
SCIMITAR_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.SCIMITAR_BLOCK =(390, 4, 1, 43, 3, 2430, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 109 of file FightType.java.
SCIMITAR_CHOP
com.runehive.game.world.entity.combat.attack.FightType.SCIMITAR_CHOP =(390, 4, 1, 43, 0, 2429, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 106 of file FightType.java.
SCIMITAR_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.SCIMITAR_LUNGE =(386, 4, 1, 43, 2, 2431, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 108 of file FightType.java.
SCIMITAR_SLASH
com.runehive.game.world.entity.combat.attack.FightType.SCIMITAR_SLASH =(390, 4, 1, 43, 1, 2432, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 107 of file FightType.java.
Referenced by com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), com.runehive.content.bot.botclass.impl.PureMelee.hit(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.hit(), com.runehive.content.bot.botclass.impl.ZerkerMelee.hit(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.initCombat(), com.runehive.content.bot.botclass.impl.PureMelee.initCombat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.initCombat(), and com.runehive.content.bot.botclass.impl.ZerkerMelee.initCombat().
SCORCH
com.runehive.game.world.entity.combat.attack.FightType.SCORCH =(5247, 5, 1, 43, 0, 24078, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 231 of file FightType.java.
Referenced by com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.addCombatExperience().
SCYTHE_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.SCYTHE_BLOCK =(382, 7, 1, 43, 3, 783, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 38 of file FightType.java.
SCYTHE_CHOP
com.runehive.game.world.entity.combat.attack.FightType.SCYTHE_CHOP =(382, 7, 1, 43, 1, 784, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 36 of file FightType.java.
SCYTHE_JAB
com.runehive.game.world.entity.combat.attack.FightType.SCYTHE_JAB =(2066, 7, 1, 43, 2, 785, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
Definition at line 37 of file FightType.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.CrushMelee.finishOutgoing().
SCYTHE_REAP
com.runehive.game.world.entity.combat.attack.FightType.SCYTHE_REAP =(414, 7, 1, 43, 0, 782, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 35 of file FightType.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.dagannoths.DagannothRex.SlashMelee.finishOutgoing().
SHADOW_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.SHADOW_ACCURATE =(9493, 10, 8, 43, 0, 4454, Equipment.MAGIC_OFFENSE, FightStyle.ACCURATE)
Definition at line 219 of file FightType.java.
SHADOW_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.SHADOW_LONGRANGE =(9493, 10, 8, 43, 2, 4452, Equipment.MAGIC_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 221 of file FightType.java.
SHADOW_RAPID
com.runehive.game.world.entity.combat.attack.FightType.SHADOW_RAPID =(9493, 9, 8, 43, 1, 4453, Equipment.MAGIC_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 220 of file FightType.java.
SHORT_FUSE
com.runehive.game.world.entity.combat.attack.FightType.SHORT_FUSE =(2779, 4, 8, 443, 0, 24059, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 227 of file FightType.java.
SHORTBOW_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.SHORTBOW_ACCURATE =(426, 4, 7, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 70 of file FightType.java.
SHORTBOW_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.SHORTBOW_LONGRANGE =(426, 4, 9, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 72 of file FightType.java.
SHORTBOW_RAPID
com.runehive.game.world.entity.combat.attack.FightType.SHORTBOW_RAPID =(426, 3, 7, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 71 of file FightType.java.
Referenced by com.runehive.content.bot.botclass.impl.PureRangeMelee.hit(), and com.runehive.content.bot.botclass.impl.PureRangeMelee.initCombat().
SPEAR_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.SPEAR_BLOCK =(2082, 5, 1, 43, 3, 4686, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 148 of file FightType.java.
SPEAR_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.SPEAR_LUNGE =(2080, 5, 1, 43, 0, 4685, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 145 of file FightType.java.
SPEAR_POUND
com.runehive.game.world.entity.combat.attack.FightType.SPEAR_POUND =(2080, 5, 1, 43, 2, 4687, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
Definition at line 147 of file FightType.java.
SPEAR_SWIPE
com.runehive.game.world.entity.combat.attack.FightType.SPEAR_SWIPE =(2081, 5, 1, 43, 1, 4688, Equipment.SLASH_OFFENSE, FightStyle.CONTROLLED)
Definition at line 146 of file FightType.java.
STAFF_BASH
com.runehive.game.world.entity.combat.attack.FightType.STAFF_BASH =(401, 5, 1, 43, 0, 6137, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 11 of file FightType.java.
STAFF_FOCUS
com.runehive.game.world.entity.combat.attack.FightType.STAFF_FOCUS =(406, 5, 1, 43, 2, 6135, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 13 of file FightType.java.
STAFF_POUND
com.runehive.game.world.entity.combat.attack.FightType.STAFF_POUND =(406, 5, 1, 43, 1, 6136, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 12 of file FightType.java.
style
final FightStyle com.runehive.game.world.entity.combat.attack.FightType.style private
The style active when this type is active.
Definition at line 257 of file FightType.java.
Referenced by FightType(), and getStyle().
SWORD_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.SWORD_BLOCK =(412, 4, 1, 43, 3, 2283, Equipment.STAB_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 99 of file FightType.java.
SWORD_LUNGE
com.runehive.game.world.entity.combat.attack.FightType.SWORD_LUNGE =(412, 4, 1, 43, 1, 2285, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 97 of file FightType.java.
SWORD_SLASH
com.runehive.game.world.entity.combat.attack.FightType.SWORD_SLASH =(395, 4, 1, 43, 2, 2284, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 98 of file FightType.java.
SWORD_STAB
com.runehive.game.world.entity.combat.attack.FightType.SWORD_STAB =(412, 4, 1, 43, 0, 2282, Equipment.STAB_OFFENSE, FightStyle.ACCURATE)
Definition at line 96 of file FightType.java.
THROWNAXE_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.THROWNAXE_ACCURATE =(929, 5, 4, 43, 0, 4454, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 207 of file FightType.java.
THROWNAXE_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.THROWNAXE_LONGRANGE =(929, 5, 6, 43, 2, 4452, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 209 of file FightType.java.
THROWNAXE_RAPID
com.runehive.game.world.entity.combat.attack.FightType.THROWNAXE_RAPID =(929, 4, 4, 43, 1, 4453, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 208 of file FightType.java.
TRIDENT_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.TRIDENT_ACCURATE =(929, 4, 8, 43, 0, 791, Equipment.MAGIC_OFFENSE, FightStyle.ACCURATE)
Definition at line 215 of file FightType.java.
TRIDENT_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.TRIDENT_LONGRANGE =(929, 4, 10, 43, 2, 791, Equipment.MAGIC_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 217 of file FightType.java.
TRIDENT_RAPID
com.runehive.game.world.entity.combat.attack.FightType.TRIDENT_RAPID =(929, 4, 8, 43, 1, 791, Equipment.MAGIC_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 216 of file FightType.java.
TWOHANDEDSWORD_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.TWOHANDEDSWORD_BLOCK =(407, 7, 1, 43, 3, 4712, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 158 of file FightType.java.
TWOHANDEDSWORD_CHOP
com.runehive.game.world.entity.combat.attack.FightType.TWOHANDEDSWORD_CHOP =(407, 7, 1, 43, 0, 4711, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 155 of file FightType.java.
TWOHANDEDSWORD_SLASH
com.runehive.game.world.entity.combat.attack.FightType.TWOHANDEDSWORD_SLASH =(407, 7, 1, 43, 1, 4713, Equipment.SLASH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 156 of file FightType.java.
TWOHANDEDSWORD_SMASH
com.runehive.game.world.entity.combat.attack.FightType.TWOHANDEDSWORD_SMASH =(406, 7, 1, 43, 2, 4714, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 157 of file FightType.java.
UNARMED_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.UNARMED_BLOCK =(422, 4, 1, 43, 2, 5861, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 201 of file FightType.java.
UNARMED_KICK
com.runehive.game.world.entity.combat.attack.FightType.UNARMED_KICK =(423, 4, 1, 43, 1, 5862, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 200 of file FightType.java.
UNARMED_PUNCH
com.runehive.game.world.entity.combat.attack.FightType.UNARMED_PUNCH =(422, 4, 1, 43, 0, 5860, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 199 of file FightType.java.
Referenced by com.runehive.game.world.entity.combat.Combat< T extends Mob >.Combat().
VIGGORA_MACE_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.VIGGORA_MACE_BLOCK =(245, 5, 1, 43, 3, 3803, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 125 of file FightType.java.
VIGGORA_MACE_POUND
com.runehive.game.world.entity.combat.attack.FightType.VIGGORA_MACE_POUND =(245, 5, 1, 43, 0, 3802, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 122 of file FightType.java.
VIGGORA_MACE_PUMMEL
com.runehive.game.world.entity.combat.attack.FightType.VIGGORA_MACE_PUMMEL =(245, 5, 1, 43, 1, 3805, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 123 of file FightType.java.
VIGGORA_MACE_SPIKE
com.runehive.game.world.entity.combat.attack.FightType.VIGGORA_MACE_SPIKE =(245, 5, 1, 43, 2, 3804, Equipment.STAB_OFFENSE, FightStyle.CONTROLLED)
Definition at line 124 of file FightType.java.
VITUR_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.VITUR_BLOCK =(8056, 5, 1, 43, 3, 783, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 43 of file FightType.java.
VITUR_CHOP
com.runehive.game.world.entity.combat.attack.FightType.VITUR_CHOP =(8056, 5, 1, 43, 1, 784, Equipment.STAB_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 41 of file FightType.java.
VITUR_JAB
com.runehive.game.world.entity.combat.attack.FightType.VITUR_JAB =(8056, 5, 1, 43, 2, 785, Equipment.CRUSH_OFFENSE, FightStyle.CONTROLLED)
Definition at line 42 of file FightType.java.
VITUR_REAP
com.runehive.game.world.entity.combat.attack.FightType.VITUR_REAP =(8056, 5, 1, 43, 0, 782, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 40 of file FightType.java.
WARHAMMER_BLOCK
com.runehive.game.world.entity.combat.attack.FightType.WARHAMMER_BLOCK =(401, 6, 1, 43, 2, 431, Equipment.CRUSH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 21 of file FightType.java.
WARHAMMER_POUND
com.runehive.game.world.entity.combat.attack.FightType.WARHAMMER_POUND =(401, 6, 1, 43, 0, 433, Equipment.CRUSH_OFFENSE, FightStyle.ACCURATE)
Definition at line 19 of file FightType.java.
WARHAMMER_PUMMEL
com.runehive.game.world.entity.combat.attack.FightType.WARHAMMER_PUMMEL =(401, 6, 1, 43, 1, 432, Equipment.CRUSH_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 20 of file FightType.java.
WHIP_DEFLECT
com.runehive.game.world.entity.combat.attack.FightType.WHIP_DEFLECT =(1658, 4, 1, 43, 2, 12296, Equipment.SLASH_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 205 of file FightType.java.
WHIP_FLICK
com.runehive.game.world.entity.combat.attack.FightType.WHIP_FLICK =(1658, 4, 1, 43, 0, 12298, Equipment.SLASH_OFFENSE, FightStyle.ACCURATE)
Definition at line 203 of file FightType.java.
WHIP_LASH
com.runehive.game.world.entity.combat.attack.FightType.WHIP_LASH =(1658, 4, 1, 43, 1, 12297, Equipment.SLASH_OFFENSE, FightStyle.CONTROLLED)
Definition at line 204 of file FightType.java.
ZARYTE_ACCURATE
com.runehive.game.world.entity.combat.attack.FightType.ZARYTE_ACCURATE =(9166, 6, 7, 43, 0, 1772, Equipment.RANGED_OFFENSE, FightStyle.ACCURATE)
Definition at line 58 of file FightType.java.
ZARYTE_LONGRANGE
com.runehive.game.world.entity.combat.attack.FightType.ZARYTE_LONGRANGE =(9166, 6, 9, 43, 2, 1770, Equipment.RANGED_OFFENSE, FightStyle.DEFENSIVE)
Definition at line 60 of file FightType.java.
ZARYTE_RAPID
com.runehive.game.world.entity.combat.attack.FightType.ZARYTE_RAPID =(9166, 5, 7, 43, 1, 1771, Equipment.RANGED_OFFENSE, FightStyle.AGGRESSIVE)
Definition at line 59 of file FightType.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/FightType.java