RuneHive-Game: com.runehive.game.world.entity.combat.ranged.RangedEffects Enum Reference
com.runehive.game.world.entity.combat.ranged.RangedEffects Enum Reference
Public Member Functions
CombatImpact getEffect ()
RangedEffects (CombatImpact effect)
Public Attributes
CHINCHOMPA
DIAMOND_BOLTS
DRAGON_BOLTS
EMERALD_BOLTS
GUAM_TAR
HARRALANDER_TAR
JADE_BOLTS
MARRENTIL_TAR
ONYX_BOLTS
OPAL_BOLTS
PEARL_BOLTS
RED_CHINCHOMPA
RUBY_BOLTS
SAPPHIRE_BOLTS
TARROMIN_TAR
TOPAZ_BOLTS
Static Private Member Functions
static void hitEvent (Mob attacker, Mob defender, Mob actor, int damage, List< Hit > extra)
Private Attributes
final CombatImpact effect
Detailed Description
Definition at line 25 of file RangedEffects.java.
Constructor & Destructor Documentation
RangedEffects()
com.runehive.game.world.entity.combat.ranged.RangedEffects.RangedEffects (CombatImpact effect)
Definition at line 302 of file RangedEffects.java.
{
        this.effect = effect;
    }
References effect.
Member Function Documentation
getEffect()
CombatImpact com.runehive.game.world.entity.combat.ranged.RangedEffects.getEffect ()
Definition at line 306 of file RangedEffects.java.
{
        return effect;
    }
References effect.
Referenced by com.runehive.util.parser.impl.CombatProjectileParser.parse().
hitEvent()
void com.runehive.game.world.entity.combat.ranged.RangedEffects.hitEvent (Mob attacker, Mob defender, Mob actor, int damage, List< Hit > extra) static private
Definition at line 310 of file RangedEffects.java.
{
        if (!defender.equals(actor)) {
            int hitDelay = getHitDelay(attacker, defender, CombatType.RANGED);
            CombatHit hit = new CombatHit(new Hit(damage, HitIcon.RANGED), hitDelay, 0);
            attacker.getCombat().submitHits(actor, hit);
            if (extra != null) extra.add(hit);
        }
    }
References com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.combat.CombatType.RANGED, and com.runehive.game.world.entity.combat.hit.HitIcon.RANGED.
Member Data Documentation
CHINCHOMPA
com.runehive.game.world.entity.combat.ranged.RangedEffects.CHINCHOMPA
Initial value:
=((attacker, defender, hit, hits) -> {
        int baseHit = hit.getDamage();
        CombatUtil.areaAction(defender,
            actor -> {
                int min = baseHit - 5;
                if (min < 0) min = 0;
                hitEvent(attacker, defender, actor, RandomUtils.inclusive(min, baseHit + 5), hits);
            });
    })
Definition at line 287 of file RangedEffects.java.
DIAMOND_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.DIAMOND_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            if (defender.isPlayer() && !RandomUtils.success(0.05)) return false;
            if (defender.isNpc() && !RandomUtils.success(0.10)) return false;
            return hit.isAccurate() && hit.getDamage() > 0;
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            hit.setDamage(hit.getDamage() + RandomUtils.inclusive(5, 14));
            defender.graphic(new Graphic(758, 0, 20));
        }
    })
Definition at line 142 of file RangedEffects.java.
DRAGON_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.DRAGON_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            if (defender.isPlayer() && defender.getPlayer().equipment.containsAny(1540, 11283)) {
                return false;
            }
            if (defender.isPlayer() && defender.getPlayer().getAntifireDetails().isPresent()) {
                return false;
            }
            return hit.isAccurate() && hit.getDamage() > 0 && RandomUtils.success(0.06);
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            int baseHit = hit.getDamage();
            hit.setDamage((int) (baseHit * 1.58));
            defender.graphic(new Graphic(756, 0, 20));
        }
    })
Definition at line 156 of file RangedEffects.java.
effect
final CombatImpact com.runehive.game.world.entity.combat.ranged.RangedEffects.effect private
Definition at line 300 of file RangedEffects.java.
Referenced by getEffect(), and RangedEffects().
EMERALD_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.EMERALD_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            if (defender.isPoisoned()) return false;
            return hit.isAccurate() && hit.getDamage() > 0 && RandomUtils.success(0.54);
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            defender.poison(PoisonType.SUPER_RANGED);
        }
    })
Definition at line 107 of file RangedEffects.java.
GUAM_TAR
com.runehive.game.world.entity.combat.ranged.RangedEffects.GUAM_TAR
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return attacker.isPlayer();
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            Player player = attacker.getPlayer();
            FightType fightType = player.getCombat().getFightType();
            CombatType type = fightType.equals(FightType.FLARE) ? CombatType.RANGED : fightType.equals(FightType.SCORCH) ? CombatType.MELEE : CombatType.MAGIC;
            if (type.equals(CombatType.MAGIC)) {
                Skill magic = player.skills.get(Skill.MAGIC);
                int max = (int) (Math.floor(0.5 + magic.getLevel() * 15 / 80) * 10);
                Hit magicHit = FormulaFactory.nextMagicHit(attacker, defender, max);
                hit.setAs(magicHit);
            } else if (type.equals(CombatType.MELEE)) {
                Hit magicHit = FormulaFactory.nextMeleeHit(attacker, defender, 1);
                hit.setAs(magicHit);
            }
        }
    })
Definition at line 194 of file RangedEffects.java.
HARRALANDER_TAR
com.runehive.game.world.entity.combat.ranged.RangedEffects.HARRALANDER_TAR
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return attacker.isPlayer();
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            Player player = attacker.getPlayer();
            FightType fightType = player.getCombat().getFightType();
            CombatType type = fightType.equals(FightType.FLARE) ? CombatType.RANGED : fightType.equals(FightType.SCORCH) ? CombatType.MELEE : CombatType.MAGIC;
            if (type.equals(CombatType.MAGIC)) {
                Skill magic = player.skills.get(Skill.MAGIC);
                int max = (int) (Math.floor(0.5 + magic.getLevel() * 156 / 640) * 10);
                Hit magicHit = FormulaFactory.nextMagicHit(attacker, defender, max);
                hit.setAs(magicHit);
            } else if (type.equals(CombatType.MELEE)) {
                Hit magicHit = FormulaFactory.nextMeleeHit(attacker, defender, 1);
                hit.setAs(magicHit);
            }
        }
    })
Definition at line 263 of file RangedEffects.java.
JADE_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.JADE_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return hit.isAccurate() && hit.getDamage() > 0 && RandomUtils.success(0.06);
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            defender.locking.lock(1199, TimeUnit.MILLISECONDS, LockType.WALKING);
            defender.graphic(new Graphic(755, 0, 20));
        }
    })
Definition at line 68 of file RangedEffects.java.
MARRENTIL_TAR
com.runehive.game.world.entity.combat.ranged.RangedEffects.MARRENTIL_TAR
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return attacker.isPlayer();
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            Player player = attacker.getPlayer();
            FightType fightType = player.getCombat().getFightType();
            CombatType type = fightType.equals(FightType.FLARE) ? CombatType.RANGED : fightType.equals(FightType.SCORCH) ? CombatType.MELEE : CombatType.MAGIC;
            if (type.equals(CombatType.MAGIC)) {
                Skill magic = player.skills.get(Skill.MAGIC);
                int max = (int) (Math.floor(0.5 + magic.getLevel() * 123 / 640) * 10);
                Hit magicHit = FormulaFactory.nextMagicHit(attacker, defender, max);
                hit.setAs(magicHit);
            } else if (type.equals(CombatType.MELEE)) {
                Hit magicHit = FormulaFactory.nextMeleeHit(attacker, defender, 1);
                hit.setAs(magicHit);
            }
        }
    })
Definition at line 217 of file RangedEffects.java.
ONYX_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.ONYX_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return hit.isAccurate() && hit.getDamage() > 0 && RandomUtils.success(0.10);
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            int damage = hit.getDamage() * 6 / 5;
            hit.setDamage(damage);
            attacker.heal(damage / 4);
            defender.graphic(new Graphic(756, 0, 20));
        }
    })
Definition at line 178 of file RangedEffects.java.
OPAL_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.OPAL_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return hit.isAccurate() && hit.getDamage() > 0 && RandomUtils.success(0.05);
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            int baseHit = hit.getDamage();
            hit.setDamage((int) (baseHit * 1.10));
            defender.graphic(new Graphic(749, 0, 20));
        }
    })
Definition at line 26 of file RangedEffects.java.
PEARL_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.PEARL_BOLTS
Initial value:
=(new CombatImpact() {
        final ImmutableSet<Integer> affectedNpcs = ImmutableSet.of(941, 55, 54, 53, 50, 5362, 1590, 1591, 1592, 5363, 110, 1633, 1634, 1635, 1636, 1019, 2591, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2627, 2628, 2629, 2630, 2631, 2631, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746);
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            if (defender.isPlayer() && defender.getPlayer().equipment.containsAny(1383, 1395, 1403, 21006)) {
                return false;
            }
            return hit.isAccurate() && hit.getDamage() > 0 && RandomUtils.success(0.06);
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            boolean multiply = false;
            int baseHit = hit.getDamage();
            if (defender.isNpc() && affectedNpcs.contains(defender.getNpc().id)) {
                multiply = true;
            }
            if (defender.isPlayer() && defender.getPlayer().equipment.containsAny(1387, 1393, 1401)) {
                multiply = true;
            }
            hit.setDamage((int) ((baseHit * 1.075) * (multiply ? 1.20 : 1.0)));
            defender.graphic(new Graphic(750, 0, 20));
        }
    })
Definition at line 39 of file RangedEffects.java.
RED_CHINCHOMPA
com.runehive.game.world.entity.combat.ranged.RangedEffects.RED_CHINCHOMPA
Initial value:
=((attacker, defender, hit, hits) -> {
        CombatUtil.areaAction(defender, actor -> hitEvent(attacker, defender, actor, hit.getDamage(), hits));
    })
Definition at line 298 of file RangedEffects.java.
RUBY_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.RUBY_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            if (attacker.getCurrentHealth() / 5 <= 0) return false;
            if (defender.isPlayer() && !RandomUtils.success(0.11)) return false;
            if (defender.isNpc() && !RandomUtils.success(0.06)) return false;
            return hit.isAccurate() && hit.getDamage() > 0;
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            int damage = defender.getCurrentHealth() / 5;
            if (damage > 100)
                damage = 100;
            hit.setDamage(damage);
            defender.graphic(new Graphic(754, 0, 20));
            int inflict = attacker.getCurrentHealth() / 10;
            attacker.damage(new Hit(inflict, HitIcon.DEFLECT));
        }
    })
Definition at line 119 of file RangedEffects.java.
SAPPHIRE_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.SAPPHIRE_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return hit.isAccurate() && hit.getDamage() > 0 && !defender.isNpc() && RandomUtils.success(0.04);
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            int baseHit = hit.getDamage();
            int percentage = (int) (baseHit * 0.05);
            defender.skills.get(Skill.PRAYER).removeLevel(percentage);
            attacker.skills.get(Skill.PRAYER).addLevel(percentage);
            defender.graphic(new Graphic(759, 100, 20));
        }
    })
Definition at line 92 of file RangedEffects.java.
TARROMIN_TAR
com.runehive.game.world.entity.combat.ranged.RangedEffects.TARROMIN_TAR
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return attacker.isPlayer();
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            Player player = attacker.getPlayer();
            FightType fightType = player.getCombat().getFightType();
            CombatType type = fightType.equals(FightType.FLARE) ? CombatType.RANGED : fightType.equals(FightType.SCORCH) ? CombatType.MELEE : CombatType.MAGIC;
            if (type.equals(CombatType.MAGIC)) {
                Skill magic = player.skills.get(Skill.MAGIC);
                int max = (int) (Math.floor(0.5 + magic.getLevel() * 141 / 640) * 10);
                Hit magicHit = FormulaFactory.nextMagicHit(attacker, defender, max);
                hit.setAs(magicHit);
            } else if (type.equals(CombatType.MELEE)) {
                Hit magicHit = FormulaFactory.nextMeleeHit(attacker, defender, 1);
                hit.setAs(magicHit);
            }
        }
    })
Definition at line 240 of file RangedEffects.java.
TOPAZ_BOLTS
com.runehive.game.world.entity.combat.ranged.RangedEffects.TOPAZ_BOLTS
Initial value:
=(new CombatImpact() {
        @Override
        public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
            return hit.isAccurate() && hit.getDamage() > 0 && !defender.isNpc() && RandomUtils.success(0.04);
        }
        @Override
        public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
            defender.skills.get(Skill.MAGIC).removeLevel(1);
            defender.graphic(new Graphic(757, 0, 20));
        }
    })
Definition at line 80 of file RangedEffects.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/ranged/RangedEffects.java