RuneHive-Game: com.runehive.content.dialogue.Expression Enum Reference
com.runehive.content.dialogue.Expression Enum Reference
Represents the expressions of entities for dialogue.
Public Member Functions
Expression (int expression)
Creates a new Expression.
final int getId ()
Gets the id for this expression.
Public Attributes
AFFLICTED =(597)
ALMOST_CRYING =(598)
ANGRY =(614)
ANNOYED =(595)
ANXIOUS =(589)
BAD =(593)
CALM_TALK =(590)
DEFAULT =(591)
DISTRESSED =(596)
DRUNK_LEFT =(600)
DRUNK_RIGHT =(601)
ENRAGED =(616)
EVIL =(592)
EVIL_LAUGH_SHORT =(609)
FURIOUS =(615)
GUFFAW =(608)
HAPPY =(588)
HAVE_FUN =(607)
LAUGH =(605)
MAD =(617)
NEARLY_CRYING =(613)
NOT_INTERESTED =(602)
ON_ONE_HAND =(612)
PLAIN_EVIL =(604)
SAD =(599)
SLEEPY =(603)
SLIGHTLY_SAD =(610)
SNIGGER =(606)
VERY_SAD =(611)
WICKED =(594)
Private Attributes
final int expression
The id for this expression.
Detailed Description
Represents the expressions of entities for dialogue.
Author
Daniel | Obey
Definition at line 8 of file Expression.java.
Constructor & Destructor Documentation
Expression()
com.runehive.content.dialogue.Expression.Expression (int expression)
Creates a new Expression.
Parameters
expression The id for this expression.
Definition at line 48 of file Expression.java.
{
        this.expression = expression;
    }
References expression.
Member Function Documentation
getId()
final int com.runehive.content.dialogue.Expression.getId ()
Gets the id for this expression.
Returns
The id of this expression.
Definition at line 57 of file Expression.java.
{
        return expression;
    }
References expression.
Referenced by com.runehive.content.dialogue.DialogueFactory.sendNpcChat(), and com.runehive.content.dialogue.DialogueFactory.sendPlayerChat().
Member Data Documentation
AFFLICTED
com.runehive.content.dialogue.Expression.AFFLICTED =(597)
Definition at line 18 of file Expression.java.
ALMOST_CRYING
com.runehive.content.dialogue.Expression.ALMOST_CRYING =(598)
Definition at line 33 of file Expression.java.
ANGRY
com.runehive.content.dialogue.Expression.ANGRY =(614)
Definition at line 35 of file Expression.java.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.exchange(), and com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage().
ANNOYED
com.runehive.content.dialogue.Expression.ANNOYED =(595)
Definition at line 16 of file Expression.java.
ANXIOUS
com.runehive.content.dialogue.Expression.ANXIOUS =(589)
Definition at line 10 of file Expression.java.
BAD
com.runehive.content.dialogue.Expression.BAD =(593)
Definition at line 14 of file Expression.java.
CALM_TALK
com.runehive.content.dialogue.Expression.CALM_TALK =(590)
Definition at line 11 of file Expression.java.
DEFAULT
com.runehive.content.dialogue.Expression.DEFAULT =(591)
Definition at line 12 of file Expression.java.
Referenced by com.runehive.content.dialogue.NpcDialogue.NpcDialogue(), com.runehive.content.dialogue.PlayerDialogue.PlayerDialogue(), and com.runehive.content.dialogue.DialogueFactory.sendNpcChat().
DISTRESSED
com.runehive.content.dialogue.Expression.DISTRESSED =(596)
Definition at line 17 of file Expression.java.
DRUNK_LEFT
com.runehive.content.dialogue.Expression.DRUNK_LEFT =(600)
Definition at line 19 of file Expression.java.
DRUNK_RIGHT
com.runehive.content.dialogue.Expression.DRUNK_RIGHT =(601)
Definition at line 20 of file Expression.java.
ENRAGED
com.runehive.content.dialogue.Expression.ENRAGED =(616)
Definition at line 37 of file Expression.java.
EVIL
com.runehive.content.dialogue.Expression.EVIL =(592)
Definition at line 13 of file Expression.java.
EVIL_LAUGH_SHORT
com.runehive.content.dialogue.Expression.EVIL_LAUGH_SHORT =(609)
Definition at line 28 of file Expression.java.
expression
final int com.runehive.content.dialogue.Expression.expression private
The id for this expression.
Definition at line 41 of file Expression.java.
Referenced by Expression(), and getId().
FURIOUS
com.runehive.content.dialogue.Expression.FURIOUS =(615)
Definition at line 36 of file Expression.java.
GUFFAW
com.runehive.content.dialogue.Expression.GUFFAW =(608)
Definition at line 27 of file Expression.java.
HAPPY
com.runehive.content.dialogue.Expression.HAPPY =(588)
Definition at line 9 of file Expression.java.
Referenced by com.runehive.content.dialogue.impl.PrestigeDialogue.explainPerks(), com.runehive.content.dialogue.impl.PrestigeDialogue.explainPrestige(), com.runehive.content.ai.AIDialogueHandler.sendDialogues(), com.runehive.content.dialogue.impl.ConstructionDialogue.sendDialogues(), com.runehive.content.dialogue.impl.KamfreenaDialogue.sendDialogues(), com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues(), com.runehive.content.dialogue.impl.PrestigeDialogue.sendDialogues(), com.runehive.content.dialogue.impl.RoyalKingDialogue.sendDialogues(), com.runehive.content.dialogue.impl.VoteDialogue.sendDialogues(), com.runehive.content.ai.LazyAIManager.showGptInstructions(), com.runehive.content.ai.LazyAIManager.showGptInstructionsWithGreeting(), com.runehive.content.ai.LazyAIManager.showOpenAIConnectionOffer(), com.runehive.content.ai.LazyAIManager.startInactivityTimer(), and com.runehive.content.ai.AIDialogueHandler.streamGandalfResponse().
HAVE_FUN
com.runehive.content.dialogue.Expression.HAVE_FUN =(607)
Definition at line 26 of file Expression.java.
LAUGH
com.runehive.content.dialogue.Expression.LAUGH =(605)
Definition at line 24 of file Expression.java.
MAD
com.runehive.content.dialogue.Expression.MAD =(617)
Definition at line 38 of file Expression.java.
NEARLY_CRYING
com.runehive.content.dialogue.Expression.NEARLY_CRYING =(613)
Definition at line 34 of file Expression.java.
NOT_INTERESTED
com.runehive.content.dialogue.Expression.NOT_INTERESTED =(602)
Definition at line 21 of file Expression.java.
ON_ONE_HAND
com.runehive.content.dialogue.Expression.ON_ONE_HAND =(612)
Definition at line 32 of file Expression.java.
PLAIN_EVIL
com.runehive.content.dialogue.Expression.PLAIN_EVIL =(604)
Definition at line 23 of file Expression.java.
SAD
com.runehive.content.dialogue.Expression.SAD =(599)
Definition at line 30 of file Expression.java.
Referenced by com.runehive.game.service.DonationService.claimDonation(), com.runehive.content.dialogue.impl.VoteDialogue.exchange(), com.runehive.content.ai.LazyAIManager.initializeOpenAIAndProcess(), and com.runehive.content.ai.AIDialogueHandler.processGandalfAIMessage().
SLEEPY
com.runehive.content.dialogue.Expression.SLEEPY =(603)
Definition at line 22 of file Expression.java.
SLIGHTLY_SAD
com.runehive.content.dialogue.Expression.SLIGHTLY_SAD =(610)
Definition at line 29 of file Expression.java.
SNIGGER
com.runehive.content.dialogue.Expression.SNIGGER =(606)
Definition at line 25 of file Expression.java.
VERY_SAD
com.runehive.content.dialogue.Expression.VERY_SAD =(611)
Definition at line 31 of file Expression.java.
WICKED
com.runehive.content.dialogue.Expression.WICKED =(594)
Definition at line 15 of file Expression.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/dialogue/Expression.java