RuneHive-Game: com.runehive.content.clanchannel.ClanRank Enum Reference
com.runehive.content.clanchannel.ClanRank Enum Reference
The enum containing all the rank's data within a clan channel.
Public Member Functions
ClanRank (String name, int rank)
Constructs a new ClanRank.
String getName ()
String getString ()
boolean greaterThanEqual (ClanRank other)
boolean lessThan (ClanRank other)
Public Attributes
CAPTAIN =("Captain", 5)
CORPORAL =("Corporal", 2)
FRIEND =("Friend", 0)
GENERAL =("General", 6)
LEADER =("Leader", 7)
LIEUTENANT =("Lieutenant", 4)
MEMBER =("Member", -1)
final String name
The name of the clan rank.
final int rank
The rank index.
RECRUIT =("Recruit", 1)
SERGEANT =("Sergeant", 3)
SYSTEM =("System", 8)
Detailed Description
The enum containing all the rank's data within a clan channel.
Author
Daniel.
Definition at line 8 of file ClanRank.java.
Constructor & Destructor Documentation
ClanRank()
com.runehive.content.clanchannel.ClanRank.ClanRank (String name, int rank)
Constructs a new ClanRank.
Definition at line 27 of file ClanRank.java.
{
        this.name = name;
        this.rank = rank;
    }
References name, and rank.
Referenced by greaterThanEqual(), and lessThan().
Member Function Documentation
getName()
String com.runehive.content.clanchannel.ClanRank.getName ()
Definition at line 40 of file ClanRank.java.
{
        return this == MEMBER ? "Anyone" : name;
    }
References MEMBER, and name.
Referenced by com.runehive.content.clanchannel.channel.ClanManagement.setEnterRank(), and com.runehive.content.clanchannel.channel.ClanManagement.setTalkRank().
getString()
String com.runehive.content.clanchannel.ClanRank.getString ()
Definition at line 44 of file ClanRank.java.
{
        return this == MEMBER ? "" : ("<clan=" + rank + ">");
    }
References MEMBER, and rank.
Referenced by com.runehive.content.clanchannel.content.ClanViewer.drawClanMembers(), com.runehive.content.clanchannel.content.ClanViewer.getProfile(), com.runehive.content.dialogue.impl.ClanRankDialogue.setRank(), and com.runehive.content.clanchannel.channel.ClanChannelHandler.updateMemberList().
greaterThanEqual()
boolean com.runehive.content.clanchannel.ClanRank.greaterThanEqual (ClanRank other)
Definition at line 36 of file ClanRank.java.
{
        return rank >= other.rank;
    }
References ClanRank(), and rank.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.ban(), com.runehive.content.clanchannel.channel.ClanManagement.canEnter(), com.runehive.content.clanchannel.channel.ClanManagement.canManage(), and com.runehive.content.clanchannel.channel.ClanManagement.canTalk().
lessThan()
boolean com.runehive.content.clanchannel.ClanRank.lessThan (ClanRank other)
Definition at line 32 of file ClanRank.java.
{
        return rank < other.rank;
    }
References ClanRank(), and rank.
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember().
Member Data Documentation
CAPTAIN
com.runehive.content.clanchannel.ClanRank.CAPTAIN =("Captain", 5)
Definition at line 15 of file ClanRank.java.
CORPORAL
com.runehive.content.clanchannel.ClanRank.CORPORAL =("Corporal", 2)
Definition at line 12 of file ClanRank.java.
FRIEND
com.runehive.content.clanchannel.ClanRank.FRIEND =("Friend", 0)
Definition at line 10 of file ClanRank.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.attemptConnection().
GENERAL
com.runehive.content.clanchannel.ClanRank.GENERAL =("General", 6)
Definition at line 16 of file ClanRank.java.
LEADER
com.runehive.content.clanchannel.ClanRank.LEADER =("Leader", 7)
Definition at line 17 of file ClanRank.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.add(), com.runehive.content.clanchannel.channel.ClanChannel.ban(), com.runehive.content.clanchannel.channel.ClanManagement.ClanManagement(), and com.runehive.content.clanchannel.channel.ClanChannelHandler.manageMember().
LIEUTENANT
com.runehive.content.clanchannel.ClanRank.LIEUTENANT =("Lieutenant", 4)
Definition at line 14 of file ClanRank.java.
MEMBER
com.runehive.content.clanchannel.ClanRank.MEMBER =("Member", -1)
Definition at line 9 of file ClanRank.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.attemptConnection(), com.runehive.content.clanchannel.channel.ClanManagement.ClanManagement(), com.runehive.content.clanchannel.ClanMember.ClanMember(), com.runehive.content.clanchannel.ClanMember.ClanMember(), com.runehive.content.clanchannel.channel.ClanChannel.disconnect(), getName(), getString(), and com.runehive.net.packet.out.SendClanDetails.SendClanDetails().
name
final String com.runehive.content.clanchannel.ClanRank.name
The name of the clan rank.
Definition at line 21 of file ClanRank.java.
Referenced by ClanRank(), getName(), com.runehive.content.clanchannel.content.ClanViewer.getProfile(), and com.runehive.content.dialogue.impl.ClanRankDialogue.setRank().
rank
final int com.runehive.content.clanchannel.ClanRank.rank
The rank index.
Definition at line 24 of file ClanRank.java.
Referenced by ClanRank(), getString(), greaterThanEqual(), and lessThan().
RECRUIT
com.runehive.content.clanchannel.ClanRank.RECRUIT =("Recruit", 1)
Definition at line 11 of file ClanRank.java.
SERGEANT
com.runehive.content.clanchannel.ClanRank.SERGEANT =("Sergeant", 3)
Definition at line 13 of file ClanRank.java.
SYSTEM
com.runehive.content.clanchannel.ClanRank.SYSTEM =("System", 8)
Definition at line 18 of file ClanRank.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.attemptConnection(), com.runehive.content.clanchannel.channel.ClanChannel.disconnect(), and com.runehive.content.clanchannel.ClanMember.message().
The documentation for this enum was generated from the following file:
java/com/runehive/content/clanchannel/ClanRank.java