RuneHive-Game: com.runehive.content.clanchannel.content.ClanLevel Enum Reference
com.runehive.content.clanchannel.content.ClanLevel Enum Reference
Handles the clan levels (based off the total experience earned).
Public Member Functions
ClanLevel (long experience, int points, String color)
The clan level.
String getColor ()
Gets the clan level color.
long getExperience ()
Gets the experience of the clan level.
int getPoints ()
Gets the points rewarded for leveling up.
Static Public Member Functions
static ClanLevel getLevel (double experience)
Gets a clan level based off the experience.
Public Attributes
ADAMANT =(1_500_000, 75, "3B4E3B")
BARROW =(10_000_000, 250, "4F614B")
BLACK =(300_000, 30, "1E1C1C")
BRONZE =(0, 0, "553E21")
DRAGON =(6_000_000, 165, "782924")
GILDED =(18_000_000, 500, "EBC41A")
GODLY =(30_000_000, 800, "E0D290")
IRON =(50_000, 5, "484242")
MITHRIL =(750_000, 50, "3D48BF")
RARE =(100_000_000, 2500, "D468F2")
RUNE =(3_000_000, 115, "4A6775")
STEEL =(150_000, 15, "867B7B")
THIRD_AGE =(50_000_000, 1250, "59b9ff")
Private Attributes
final String color
The clan level color.
final long experience
The experience of the level.
final int points
The clan points rewarded.
Detailed Description
Handles the clan levels (based off the total experience earned).
Author
Daniel
Definition at line 8 of file ClanLevel.java.
Constructor & Destructor Documentation
ClanLevel()
com.runehive.content.clanchannel.content.ClanLevel.ClanLevel (long experience, int points, String color)
The clan level.
Definition at line 33 of file ClanLevel.java.
{
        this.experience = experience;
        this.points = points;
        this.color = color;
    }
References color, experience, and points.
Referenced by getLevel().
Member Function Documentation
getColor()
String com.runehive.content.clanchannel.content.ClanLevel.getColor ()
Gets the clan level color.
Definition at line 50 of file ClanLevel.java.
{
        return color;
    }
References color.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.addExperience(), and com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel().
getExperience()
long com.runehive.content.clanchannel.content.ClanLevel.getExperience ()
Gets the experience of the clan level.
Definition at line 40 of file ClanLevel.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel().
getLevel()
ClanLevel com.runehive.content.clanchannel.content.ClanLevel.getLevel (double experience) static
Gets a clan level based off the experience.
Definition at line 55 of file ClanLevel.java.
{
        ClanLevel level = BRONZE;
        for (ClanLevel levels : values()) {
            if (experience >= levels.getExperience())
                level = levels;
        }
        return level;
    }
References BRONZE, ClanLevel(), and experience.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.addExperience().
getPoints()
int com.runehive.content.clanchannel.content.ClanLevel.getPoints ()
Gets the points rewarded for leveling up.
Definition at line 45 of file ClanLevel.java.
{
        return points;
    }
References points.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.addExperience(), and com.runehive.content.dialogue.impl.ClanmasterDialogue.clanLevel().
Member Data Documentation
ADAMANT
com.runehive.content.clanchannel.content.ClanLevel.ADAMANT =(1_500_000, 75, "3B4E3B")
Definition at line 14 of file ClanLevel.java.
BARROW
com.runehive.content.clanchannel.content.ClanLevel.BARROW =(10_000_000, 250, "4F614B")
Definition at line 17 of file ClanLevel.java.
BLACK
com.runehive.content.clanchannel.content.ClanLevel.BLACK =(300_000, 30, "1E1C1C")
Definition at line 12 of file ClanLevel.java.
BRONZE
com.runehive.content.clanchannel.content.ClanLevel.BRONZE =(0, 0, "553E21")
Definition at line 9 of file ClanLevel.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.create(), and getLevel().
color
final String com.runehive.content.clanchannel.content.ClanLevel.color private
The clan level color.
Definition at line 30 of file ClanLevel.java.
Referenced by ClanLevel(), and getColor().
DRAGON
com.runehive.content.clanchannel.content.ClanLevel.DRAGON =(6_000_000, 165, "782924")
Definition at line 16 of file ClanLevel.java.
experience
final long com.runehive.content.clanchannel.content.ClanLevel.experience private
The experience of the level.
Definition at line 24 of file ClanLevel.java.
Referenced by ClanLevel(), getExperience(), and getLevel().
GILDED
com.runehive.content.clanchannel.content.ClanLevel.GILDED =(18_000_000, 500, "EBC41A")
Definition at line 18 of file ClanLevel.java.
GODLY
com.runehive.content.clanchannel.content.ClanLevel.GODLY =(30_000_000, 800, "E0D290")
Definition at line 19 of file ClanLevel.java.
IRON
com.runehive.content.clanchannel.content.ClanLevel.IRON =(50_000, 5, "484242")
Definition at line 10 of file ClanLevel.java.
MITHRIL
com.runehive.content.clanchannel.content.ClanLevel.MITHRIL =(750_000, 50, "3D48BF")
Definition at line 13 of file ClanLevel.java.
points
final int com.runehive.content.clanchannel.content.ClanLevel.points private
The clan points rewarded.
Definition at line 27 of file ClanLevel.java.
Referenced by ClanLevel(), and getPoints().
RARE
com.runehive.content.clanchannel.content.ClanLevel.RARE =(100_000_000, 2500, "D468F2")
Definition at line 21 of file ClanLevel.java.
RUNE
com.runehive.content.clanchannel.content.ClanLevel.RUNE =(3_000_000, 115, "4A6775")
Definition at line 15 of file ClanLevel.java.
STEEL
com.runehive.content.clanchannel.content.ClanLevel.STEEL =(150_000, 15, "867B7B")
Definition at line 11 of file ClanLevel.java.
THIRD_AGE
com.runehive.content.clanchannel.content.ClanLevel.THIRD_AGE =(50_000_000, 1250, "59b9ff")
Definition at line 20 of file ClanLevel.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/clanchannel/content/ClanLevel.java