RuneHive-Game: com.runehive.content.skill.impl.prayer.BoneData Enum Reference
com.runehive.content.skill.impl.prayer.BoneData Enum Reference
Holds the Bone data.
Public Member Functions
BoneData (int id, int noted, double experience, int boneAmulet)
The bone data.
int getBoneAmulet ()
double getExperience ()
Gets the experience of the bone.
int getId ()
Gets the id of the bone.
int getId2 ()
Static Public Member Functions
static Optional< BoneData > forId (int id)
Gets the bone data based on the item.
Public Attributes
BABYDRAGON_BONES =(534, 535, 30.0D, 3)
BAT_BONES =(530, 531, 4.5D, 1)
BIG_BONES =(532, 533, 15.0D, 2)
DAGG_BONES =(6729, 6730, 125.0D, 4)
DRAGON_BONES =(536, 537, 72.0D, 4)
LAVA_DRAGON_BONES =(11943, 11944, 85.0D, 4)
LONG_BONE =(10976, 10977, 100.0D, 4)
NORMAL_BONES =(526, 527, 4.5D, 1)
OURG_BONES =(4834, 4835, 140.0D, 4)
SKELETAL_WYVERN_BONES =(6812, 6818, 72.0D, 4)
SUPERIOR_DRAGON_BONES =(22124, 22125, 150.0D, 5)
WOLF_BONES =(2859, 2860, 4.5D, 1)
Private Attributes
final int boneAmulet
The amount of prayer points rewarded for bone amulet.
final double experience
The experience of the bone.
final int id
The id of the bone.
final int id2
Detailed Description
Holds the Bone data.
Definition at line 9 of file BoneData.java.
Constructor & Destructor Documentation
BoneData()
com.runehive.content.skill.impl.prayer.BoneData.BoneData (int id, int noted, double experience, int boneAmulet)
The bone data.
Definition at line 34 of file BoneData.java.
{
        this.id = id;
        this.id2 = noted;
        this.experience = experience;
        this.boneAmulet = boneAmulet;
    }
References boneAmulet, experience, and id.
Member Function Documentation
forId()
Optional< BoneData > com.runehive.content.skill.impl.prayer.BoneData.forId (int id) static
Gets the bone data based on the item.
Definition at line 59 of file BoneData.java.
{
        return Arrays.stream(values()).filter(a -> a.id == id).findAny();
    }
Referenced by com.runehive.content.skill.impl.prayer.BoneSacrifice.clickItem(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop(), and com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem().
getBoneAmulet()
int com.runehive.content.skill.impl.prayer.BoneData.getBoneAmulet ()
Definition at line 54 of file BoneData.java.
{
        return boneAmulet;
    }
References boneAmulet.
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleBoneCrusher().
getExperience()
double com.runehive.content.skill.impl.prayer.BoneData.getExperience ()
Gets the experience of the bone.
Definition at line 50 of file BoneData.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleBoneCrusher(), and com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice().
getId()
int com.runehive.content.skill.impl.prayer.BoneData.getId ()
Gets the id of the bone.
Definition at line 42 of file BoneData.java.
                       {
        return id;
    }
References id.
Referenced by com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), and com.runehive.content.skill.impl.prayer.BoneSacrifice.useItem().
getId2()
int com.runehive.content.skill.impl.prayer.BoneData.getId2 ()
Definition at line 45 of file BoneData.java.
{
        return id2;
    }
References id2.
Member Data Documentation
BABYDRAGON_BONES
com.runehive.content.skill.impl.prayer.BoneData.BABYDRAGON_BONES =(534, 535, 30.0D, 3)
Definition at line 14 of file BoneData.java.
BAT_BONES
com.runehive.content.skill.impl.prayer.BoneData.BAT_BONES =(530, 531, 4.5D, 1)
Definition at line 12 of file BoneData.java.
BIG_BONES
com.runehive.content.skill.impl.prayer.BoneData.BIG_BONES =(532, 533, 15.0D, 2)
Definition at line 13 of file BoneData.java.
boneAmulet
final int com.runehive.content.skill.impl.prayer.BoneData.boneAmulet private
The amount of prayer points rewarded for bone amulet.
Definition at line 31 of file BoneData.java.
Referenced by BoneData(), and getBoneAmulet().
DAGG_BONES
com.runehive.content.skill.impl.prayer.BoneData.DAGG_BONES =(6729, 6730, 125.0D, 4)
Definition at line 20 of file BoneData.java.
DRAGON_BONES
com.runehive.content.skill.impl.prayer.BoneData.DRAGON_BONES =(536, 537, 72.0D, 4)
Definition at line 15 of file BoneData.java.
experience
final double com.runehive.content.skill.impl.prayer.BoneData.experience private
The experience of the bone.
Definition at line 28 of file BoneData.java.
Referenced by BoneData(), and getExperience().
id
final int com.runehive.content.skill.impl.prayer.BoneData.id private
The id of the bone.
Definition at line 24 of file BoneData.java.
Referenced by BoneData(), and getId().
id2
final int com.runehive.content.skill.impl.prayer.BoneData.id2 private
Definition at line 26 of file BoneData.java.
Referenced by getId2().
LAVA_DRAGON_BONES
com.runehive.content.skill.impl.prayer.BoneData.LAVA_DRAGON_BONES =(11943, 11944, 85.0D, 4)
Definition at line 19 of file BoneData.java.
LONG_BONE
com.runehive.content.skill.impl.prayer.BoneData.LONG_BONE =(10976, 10977, 100.0D, 4)
Definition at line 17 of file BoneData.java.
NORMAL_BONES
com.runehive.content.skill.impl.prayer.BoneData.NORMAL_BONES =(526, 527, 4.5D, 1)
Definition at line 10 of file BoneData.java.
OURG_BONES
com.runehive.content.skill.impl.prayer.BoneData.OURG_BONES =(4834, 4835, 140.0D, 4)
Definition at line 16 of file BoneData.java.
SKELETAL_WYVERN_BONES
com.runehive.content.skill.impl.prayer.BoneData.SKELETAL_WYVERN_BONES =(6812, 6818, 72.0D, 4)
Definition at line 18 of file BoneData.java.
SUPERIOR_DRAGON_BONES
com.runehive.content.skill.impl.prayer.BoneData.SUPERIOR_DRAGON_BONES =(22124, 22125, 150.0D, 5)
Definition at line 21 of file BoneData.java.
WOLF_BONES
com.runehive.content.skill.impl.prayer.BoneData.WOLF_BONES =(2859, 2860, 4.5D, 1)
Definition at line 11 of file BoneData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/prayer/BoneData.java