RuneHive-Game: com.runehive.game.world.entity.combat.hit.Hitsplat Enum Reference
com.runehive.game.world.entity.combat.hit.Hitsplat Enum Reference
Public Member Functions
final int getId ()
Gets the identification for this hit type.
Hitsplat (int id)
Create a new Hitsplat.
Public Attributes
CRITICAL =(4)
Represents a heal hit type.
NORMAL =(0)
Represents a normal hit type.
POISON =(2)
Represents a poison hit type.
VENOM =(3)
Represents a venom hit type.
Private Attributes
final int id
The identification for this hit type.
Detailed Description
Definition at line 3 of file Hitsplat.java.
Constructor & Destructor Documentation
Hitsplat()
com.runehive.game.world.entity.combat.hit.Hitsplat.Hitsplat (int id)
Create a new Hitsplat.
Parameters
id the identification for this hit type.
Definition at line 25 of file Hitsplat.java.
                     {
        this.id = id;
    }
References id.
Member Function Documentation
getId()
final int com.runehive.game.world.entity.combat.hit.Hitsplat.getId ()
Gets the identification for this hit type.
Returns
the identification for this hit type.
Definition at line 34 of file Hitsplat.java.
{
        return id;
    }
References id.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask().
Member Data Documentation
CRITICAL
com.runehive.game.world.entity.combat.hit.Hitsplat.CRITICAL =(4)
Represents a heal hit type.
Definition at line 15 of file Hitsplat.java.
id
final int com.runehive.game.world.entity.combat.hit.Hitsplat.id private
The identification for this hit type.
Definition at line 18 of file Hitsplat.java.
Referenced by getId(), and Hitsplat().
NORMAL
com.runehive.game.world.entity.combat.hit.Hitsplat.NORMAL =(0)
Represents a normal hit type.
Definition at line 6 of file Hitsplat.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.content.lms.LMSGame.handleFogDamage(), com.runehive.game.world.entity.combat.hit.Hit.Hit(), com.runehive.game.world.entity.combat.hit.Hit.Hit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMagicHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), and com.runehive.game.world.entity.combat.attack.FormulaFactory.nextRangedHit().
POISON
com.runehive.game.world.entity.combat.hit.Hitsplat.POISON =(2)
Represents a poison hit type.
Definition at line 9 of file Hitsplat.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), and com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.process().
VENOM
com.runehive.game.world.entity.combat.hit.Hitsplat.VENOM =(3)
Represents a venom hit type.
Definition at line 12 of file Hitsplat.java.
Referenced by com.runehive.content.activity.impl.zulrah.ZulrahActivity.cloudEffect(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.VenomDragonfireAttack.getHits(), and com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.process().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/hit/Hitsplat.java