RuneHive-Game: com.runehive.content.skill.impl.slayer.SlayerUnlockable Enum Reference
com.runehive.content.skill.impl.slayer.SlayerUnlockable Enum Reference
Holds all the unlockable slayer rewards and tasks.
Public Member Functions
int getCost ()
Gets the unlockable cost.
String getDescription ()
Gets the unlockable description.
int getItem ()
Gets the unlockable item display.
String getName ()
Gets a the unlockable name.
SlayerUnlockable (String name, int item, int cost, String description)
Constructs a new SlayerUnlockable.
Static Public Member Functions
static Optional< SlayerUnlockable > get (int ordinal)
Gets the slayer unlockable data based on the ordinal.
Public Attributes
BROAD_BOLT =("Broader fletching", 11874, 75, "Learn to fletch broad arrows (with level 52\\nfletching) and broad bolts (with level 55 \\nfletching).")
CANNON_BALLS =("Balls of fury", 2, 75, "Learn to craft your own cannonballs, with\\nlevel 35 smithing.")
CHAOS_ELEMENT =("I strive on chaos", 12694, 100, "Unlock the ability to be assigned Chaos\\nelemental as a Slayer task, 65 Slayer\\nneeded.")
CRAZY_ARCHAEOLOGIST =("You drive me crazy", 11990, 100, "Unlock the ability to be assigned Crazy\\narchaeologist as a Slayer task, 60\\nSlayer needed.")
KING_BLACK_DRAGON =("King killer", 11283, 100, "Unlock the ability to be assigned King black\\ndragon as a Slayer task, 75 Slayer needed.")
RING_OF_WEALTH =("Ring bling", 2572, 250, "Learn to craft your own Slayer rings, with\\nlevel 75 crafting.")
SLAYER_HELM =("Malevolent masquerade", 11864, 250, "Learn to combine the protective Slayer\\nheadgear & Slayer gem into one universal\\nhelmet. 55 crafting needed.")
ZULRAH =("Give me venom", 12924, 100, "Unlock the ability to be assigned Zulrah as\\na Slayer task, 95 Slayer needed.")
Private Attributes
final int cost
The unlockable cost.
final String description
The unlockable description.
final int item
The unlockable item display.
final String name
The unlockable name.
Detailed Description
Holds all the unlockable slayer rewards and tasks.
Author
Daniel
Definition at line 11 of file SlayerUnlockable.java.
Constructor & Destructor Documentation
SlayerUnlockable()
com.runehive.content.skill.impl.slayer.SlayerUnlockable.SlayerUnlockable (String name, int item, int cost, String description)
Constructs a new SlayerUnlockable.
Parameters
name The name of the unlockable.
item The item display of the unlockable.
cost The cost of the unlockable.
description The description of the unlockable.
Definition at line 45 of file SlayerUnlockable.java.
{
        this.name = name;
        this.item = item;
        this.cost = cost;
        this.description = description;
    }
References cost, description, item, and name.
Member Function Documentation
get()
Optional< SlayerUnlockable > com.runehive.content.skill.impl.slayer.SlayerUnlockable.get (int ordinal) static
Gets the slayer unlockable data based on the ordinal.
Parameters
ordinal The unlockable ordinal.
Returns
The slayer unlockable data.
Definition at line 95 of file SlayerUnlockable.java.
{
        return Arrays.stream(values()).filter($it -> $it.ordinal() == ordinal).findFirst();
    }
Referenced by com.runehive.content.skill.impl.slayer.Slayer.confirm().
getCost()
int com.runehive.content.skill.impl.slayer.SlayerUnlockable.getCost ()
Gets the unlockable cost.
Returns
cost
Definition at line 75 of file SlayerUnlockable.java.
{
        return cost;
    }
References cost.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.purchase(), and com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getDescription()
String com.runehive.content.skill.impl.slayer.SlayerUnlockable.getDescription ()
Gets the unlockable description.
Returns
description
Definition at line 84 of file SlayerUnlockable.java.
{
        return description;
    }
References description.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getItem()
int com.runehive.content.skill.impl.slayer.SlayerUnlockable.getItem ()
Gets the unlockable item display.
Returns
item
Definition at line 66 of file SlayerUnlockable.java.
{
        return item;
    }
References item.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getName()
String com.runehive.content.skill.impl.slayer.SlayerUnlockable.getName ()
Gets a the unlockable name.
Returns
name
Definition at line 57 of file SlayerUnlockable.java.
{
        return name;
    }
References name.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.purchase(), and com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
Member Data Documentation
BROAD_BOLT
com.runehive.content.skill.impl.slayer.SlayerUnlockable.BROAD_BOLT =("Broader fletching", 11874, 75, "Learn to fletch broad arrows (with level 52\\nfletching) and broad bolts (with level 55 \\nfletching).")
Definition at line 13 of file SlayerUnlockable.java.
CANNON_BALLS
com.runehive.content.skill.impl.slayer.SlayerUnlockable.CANNON_BALLS =("Balls of fury", 2, 75, "Learn to craft your own cannonballs, with\\nlevel 35 smithing.")
Definition at line 15 of file SlayerUnlockable.java.
Referenced by com.runehive.content.skill.impl.smithing.SmithingArmour.forge().
CHAOS_ELEMENT
com.runehive.content.skill.impl.slayer.SlayerUnlockable.CHAOS_ELEMENT =("I strive on chaos", 12694, 100, "Unlock the ability to be assigned Chaos\\nelemental as a Slayer task, 65 Slayer\\nneeded.")
Definition at line 18 of file SlayerUnlockable.java.
cost
final int com.runehive.content.skill.impl.slayer.SlayerUnlockable.cost private
The unlockable cost.
Definition at line 28 of file SlayerUnlockable.java.
Referenced by getCost(), and SlayerUnlockable().
CRAZY_ARCHAEOLOGIST
com.runehive.content.skill.impl.slayer.SlayerUnlockable.CRAZY_ARCHAEOLOGIST =("You drive me crazy", 11990, 100, "Unlock the ability to be assigned Crazy\\narchaeologist as a Slayer task, 60\\nSlayer needed.")
Definition at line 19 of file SlayerUnlockable.java.
description
final String com.runehive.content.skill.impl.slayer.SlayerUnlockable.description private
The unlockable description.
Definition at line 31 of file SlayerUnlockable.java.
Referenced by getDescription(), and SlayerUnlockable().
item
final int com.runehive.content.skill.impl.slayer.SlayerUnlockable.item private
The unlockable item display.
Definition at line 25 of file SlayerUnlockable.java.
Referenced by getItem(), and SlayerUnlockable().
KING_BLACK_DRAGON
com.runehive.content.skill.impl.slayer.SlayerUnlockable.KING_BLACK_DRAGON =("King killer", 11283, 100, "Unlock the ability to be assigned King black\\ndragon as a Slayer task, 75 Slayer needed.")
Definition at line 17 of file SlayerUnlockable.java.
name
final String com.runehive.content.skill.impl.slayer.SlayerUnlockable.name private
The unlockable name.
Definition at line 22 of file SlayerUnlockable.java.
Referenced by getName(), and SlayerUnlockable().
RING_OF_WEALTH
com.runehive.content.skill.impl.slayer.SlayerUnlockable.RING_OF_WEALTH =("Ring bling", 2572, 250, "Learn to craft your own Slayer rings, with\\nlevel 75 crafting.")
Definition at line 14 of file SlayerUnlockable.java.
SLAYER_HELM
com.runehive.content.skill.impl.slayer.SlayerUnlockable.SLAYER_HELM =("Malevolent masquerade", 11864, 250, "Learn to combine the protective Slayer\\nheadgear & Slayer gem into one universal\\nhelmet. 55 crafting needed.")
Definition at line 12 of file SlayerUnlockable.java.
ZULRAH
com.runehive.content.skill.impl.slayer.SlayerUnlockable.ZULRAH =("Give me venom", 12924, 100, "Unlock the ability to be assigned Zulrah as\\na Slayer task, 95 Slayer needed.")
Definition at line 16 of file SlayerUnlockable.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/slayer/SlayerUnlockable.java