RuneHive-Game: com.runehive.game.world.entity.mob.player.relations.ChatEffect Enum Reference
com.runehive.game.world.entity.mob.player.relations.ChatEffect Enum Reference
Public Member Functions
ChatEffect (int code)
int getCode ()
Public Attributes
NONE =(0)
SCROLL =(4)
SHAKE =(3)
SLIDE =(5)
WAVE =(1)
WAVE_2 =(2)
Static Public Attributes
static final ChatEffect[] values = values()
Private Attributes
final int code
Detailed Description
Definition at line 3 of file ChatEffect.java.
Constructor & Destructor Documentation
ChatEffect()
com.runehive.game.world.entity.mob.player.relations.ChatEffect.ChatEffect (int code)
Definition at line 14 of file ChatEffect.java.
{
        this.code = code;
    }
References code.
Member Function Documentation
getCode()
int com.runehive.game.world.entity.mob.player.relations.ChatEffect.getCode ()
Definition at line 18 of file ChatEffect.java.
{
        return code;
    }
References code.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask().
Member Data Documentation
code
final int com.runehive.game.world.entity.mob.player.relations.ChatEffect.code private
Definition at line 12 of file ChatEffect.java.
Referenced by ChatEffect(), and getCode().
NONE
com.runehive.game.world.entity.mob.player.relations.ChatEffect.NONE =(0)
Definition at line 5 of file ChatEffect.java.
Referenced by com.runehive.game.world.entity.mob.player.relations.ChatMessage.ChatMessage(), com.runehive.game.world.entity.mob.player.relations.ChatMessage.create(), and com.runehive.game.world.entity.mob.player.relations.ChatMessage.create().
SCROLL
com.runehive.game.world.entity.mob.player.relations.ChatEffect.SCROLL =(4)
Definition at line 9 of file ChatEffect.java.
SHAKE
com.runehive.game.world.entity.mob.player.relations.ChatEffect.SHAKE =(3)
Definition at line 8 of file ChatEffect.java.
SLIDE
com.runehive.game.world.entity.mob.player.relations.ChatEffect.SLIDE =(5)
Definition at line 10 of file ChatEffect.java.
values
final ChatEffect [] com.runehive.game.world.entity.mob.player.relations.ChatEffect.values = values() static
Definition at line 22 of file ChatEffect.java.
Referenced by com.runehive.net.packet.in.ChatMessagePacketListener.handlePacket().
WAVE
com.runehive.game.world.entity.mob.player.relations.ChatEffect.WAVE =(1)
Definition at line 6 of file ChatEffect.java.
WAVE_2
com.runehive.game.world.entity.mob.player.relations.ChatEffect.WAVE_2 =(2)
Definition at line 7 of file ChatEffect.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/player/relations/ChatEffect.java