RuneHive-Game: com.runehive.content.famehall.FameEntry Enum Reference
com.runehive.content.famehall.FameEntry Enum Reference
Holds all the fame entries.
Public Member Functions
FameEntry (String entry, int display, FameType type)
Constructs a new FameEntry.
int getDisplay ()
Gets the display item.
String getEntry ()
Gets the entry string.
FameType getType ()
Gets the fame type.
Static Public Member Functions
static List< FameEntry > getEntries (FameType type)
Gets all the entries based on the fame type.
Public Attributes
BOO =("Get 100 kills with Abyssal whip", 4151, FameType.PVP)
CLAIM_A_MAX_CAPE =("Claim a Max cape", 13280, FameType.MISC)
Miscellaneous.
CLAIM_AN_ACHIEVEMENT_CAPE =("Claim an Achievement cape", 13069, FameType.MISC)
CRAFT_A_DFS =("Craft a Dragonfire shield", 11283, FameType.MISC)
CRAFT_AN_ARCANE =("Craft an Arcane spirit shield", 12825, FameType.MISC)
CRAFT_AN_ELY =("Craft an Elysian spirit shield", 12817, FameType.MISC)
CRAFT_AN_SPECTRAL =("Craft a Spectral spirit shield", 12821, FameType.MISC)
DEAL_10000_MAGIC_DAMAGE =("Deal 10,000 Magic damage", 11791, FameType.PVP)
DEAL_10000_MELEE_DAMAGE =("Deal 10,000 Melee damage", 4151, FameType.PVP)
DEAL_10000_RANGED_DAMAGE =("Deal 10,000 Ranged damage", 19481, FameType.PVP)
DRINK_10000_POTIONS =("Drink 10,000 potions", 139, FameType.MISC)
EAT_10000_FOOD =("Eat 10,000 food", 385, FameType.MISC)
FIRST_ELYSIAN_DROP =("First Elysian sigil drop", 12819, FameType.PVM)
FIRST_TASSETS_DROP =("First Bandos tassets drop", 11834, FameType.PVM)
Monster Killing.
FIRST_VISAGE_DROP =("First Visage drop", 11286, FameType.PVM)
KILL_1000_BOUNTY_HUNTER_TARGETS =("Kill 1,000 Bounty Hunter targets", 12756, FameType.PVP)
KILL_200_BOUNTY_HUNTER_TARGETS =("Kill 200 Bounty Hunter targets", 12753, FameType.PVP)
KILL_500_BOUNTY_HUNTER_TARGETS =("Kill 500 Bounty Hunter targets", 12756, FameType.PVP)
MAX_AGILITY_LEVEL =("Reach level 99 in Agility", 9771, FameType.SKILL)
Skilling.
MAX_CLAN_MEMBERS =("Own a clan with 250 gameMembers", 12397, FameType.MISC)
MAX_CONSTRUCTION_LEVEL =("Reach level 99 in Construction", 9789, FameType.SKILL)
MAX_COOKING_LEVEL =("Reach level 99 in Cooking", 9801, FameType.SKILL)
MAX_CRAFTING_LEVEL =("Reach level 99 in Crafting", 9780, FameType.SKILL)
MAX_FARMING_LEVEL =("Reach level 99 in Farming", 9810, FameType.SKILL)
MAX_FIREMAKING_LEVEL =("Reach level 99 in Firemaking", 9804, FameType.SKILL)
MAX_FISHING_LEVEL =("Reach level 99 in Fishing", 9798, FameType.SKILL)
MAX_FLETCHING_LEVEL =("Reach level 99 in Fletching", 9783, FameType.SKILL)
MAX_HERBLORE_LEVEL =("Reach level 99 in Herblore", 9774, FameType.SKILL)
MAX_HUNTER_LEVEL =("Reach level 99 in Hunter", 9948, FameType.SKILL)
MAX_MINING_LEVEL =("Reach level 99 in Mining", 9792, FameType.SKILL)
MAX_RUNECRAFTING_LEVEL =("Reach level 99 in Runecrafting", 9765, FameType.SKILL)
MAX_SLAYER_LEVEL =("Reach level 99 in Slayer", 9786, FameType.SKILL)
MAX_SMITHING_LEVEL =("Reach level 99 in Smithing", 9795, FameType.SKILL)
MAX_THIEVING_LEVEL =("Reach level 99 in Thieving", 9777, FameType.SKILL)
MAX_WOODCUTTING_LEVEL =("Reach level 99 in Woodcutting", 9807, FameType.SKILL)
OBTAIN_A_100_KILLSTREAK =("First 100 Kill streak", 13316, FameType.PVP)
OBTAIN_A_50_KILLSTREAK =("First 50 Kill streak", 13315, FameType.PVP)
OBTAIN_A_ARMADYL_PET =("Obtain an Armadyl pet drop", 12649, FameType.PVM)
OBTAIN_A_BANDOS_PET =("First Bandos pet drop", 12650, FameType.PVM)
OBTAIN_A_CALLISTO_PET =("First Callisto pet drop", 13178, FameType.PVM)
OBTAIN_A_KBD_PET =("First KBD pet drop", 12653, FameType.PVM)
OBTAIN_A_KRAKEN_PET =("First Kraken pet drop", 12655, FameType.PVM)
OBTAIN_A_MOLE_PET =("First Giant mole pet drop", 12646, FameType.PVM)
OBTAIN_A_PRIME_PET =("First Prime pet drop", 12644, FameType.PVM)
OBTAIN_A_REX_PET =("First Rex pet drop", 12645, FameType.PVM)
OBTAIN_A_SARADOMIN_PET =("First Saradomin pet drop", 12651, FameType.PVM)
OBTAIN_A_SCORPIA_PET =("First Scorpia pet drop", 13181, FameType.PVM)
OBTAIN_A_SUPREME_PET =("First Supreme pet drop", 12643, FameType.PVM)
OBTAIN_A_VENENATIS_PET =("First Venenatis pet drop", 13177, FameType.PVM)
OBTAIN_A_VETION_PET =("First Vet'ion pet drop", 13179, FameType.PVM)
OBTAIN_A_ZAMORAK_PET =("First Zamorak pet drop", 12652, FameType.PVM)
OBTAIN_A_ZULRAH_PET =("First Zulrah pet drop", 12939, FameType.PVM)
REACH_1000_KILLS =("Reach 1000 kills", 6824, FameType.PVP)
REACH_100_KILLS =("Reach 100 kills", 6824, FameType.PVP)
Player Killing.
REACH_2500_KILLS =("Reach 2500 kills", 6824, FameType.PVP)
REACH_250_KILLS =("Reach 250 kills", 6824, FameType.PVP)
REACH_500_KILLS =("Reach 500 kills", 6824, FameType.PVP)
Private Attributes
final int display
The item display.
final String entry
The entry string.
final FameType type
The fame type.
Detailed Description
Holds all the fame entries.
Author
Daniel
Definition at line 11 of file FameEntry.java.
Constructor & Destructor Documentation
FameEntry()
com.runehive.content.famehall.FameEntry.FameEntry (String entry, int display, FameType type)
Constructs a new FameEntry.
Parameters
entry The entry string.
display The display item.
type The fame type.
Definition at line 108 of file FameEntry.java.
{
        this.entry = entry;
        this.display = display;
        this.type = type;
    }
References display, entry, and type.
Referenced by getEntries().
Member Function Documentation
getDisplay()
int com.runehive.content.famehall.FameEntry.getDisplay ()
Gets the display item.
Returns
Display item.
Definition at line 128 of file FameEntry.java.
{
        return display;
    }
References display.
Referenced by com.runehive.content.famehall.FameHandler.open().
getEntries()
List< FameEntry > com.runehive.content.famehall.FameEntry.getEntries (FameType type) static
Gets all the entries based on the fame type.
Parameters
type The fame type to filter out.
Returns
List of fame entries.
Definition at line 148 of file FameEntry.java.
{
        List<FameEntry> entry_list = new LinkedList<>();
        for (FameEntry entry : FameEntry.values()) {
            if (entry.getType() == type)
                entry_list.add(entry);
        }
        return entry_list;
    }
References entry, FameEntry(), and type.
Referenced by com.runehive.content.famehall.FameHandler.open().
getEntry()
String com.runehive.content.famehall.FameEntry.getEntry ()
Gets the entry string.
Returns
Entry string.
Definition at line 119 of file FameEntry.java.
{
        return entry;
    }
References entry.
Referenced by com.runehive.content.famehall.FameHandler.activate(), and com.runehive.content.famehall.FameHandler.open().
getType()
FameType com.runehive.content.famehall.FameEntry.getType ()
Gets the fame type.
Returns
Fame type.
Definition at line 137 of file FameEntry.java.
{
        return type;
    }
References type.
Referenced by com.runehive.content.famehall.FameHandler.activate(), and com.runehive.content.famehall.FameHandler.getEntry().
Member Data Documentation
BOO
com.runehive.content.famehall.FameEntry.BOO =("Get 100 kills with Abyssal whip", 4151, FameType.PVP)
Definition at line 30 of file FameEntry.java.
CLAIM_A_MAX_CAPE
com.runehive.content.famehall.FameEntry.CLAIM_A_MAX_CAPE =("Claim a Max cape", 13280, FameType.MISC)
Miscellaneous.
Definition at line 77 of file FameEntry.java.
CLAIM_AN_ACHIEVEMENT_CAPE
com.runehive.content.famehall.FameEntry.CLAIM_AN_ACHIEVEMENT_CAPE =("Claim an Achievement cape", 13069, FameType.MISC)
Definition at line 78 of file FameEntry.java.
CRAFT_A_DFS
com.runehive.content.famehall.FameEntry.CRAFT_A_DFS =("Craft a Dragonfire shield", 11283, FameType.MISC)
Definition at line 82 of file FameEntry.java.
CRAFT_AN_ARCANE
com.runehive.content.famehall.FameEntry.CRAFT_AN_ARCANE =("Craft an Arcane spirit shield", 12825, FameType.MISC)
Definition at line 84 of file FameEntry.java.
CRAFT_AN_ELY
com.runehive.content.famehall.FameEntry.CRAFT_AN_ELY =("Craft an Elysian spirit shield", 12817, FameType.MISC)
Definition at line 83 of file FameEntry.java.
CRAFT_AN_SPECTRAL
com.runehive.content.famehall.FameEntry.CRAFT_AN_SPECTRAL =("Craft a Spectral spirit shield", 12821, FameType.MISC)
Definition at line 85 of file FameEntry.java.
DEAL_10000_MAGIC_DAMAGE
com.runehive.content.famehall.FameEntry.DEAL_10000_MAGIC_DAMAGE =("Deal 10,000 Magic damage", 11791, FameType.PVP)
Definition at line 27 of file FameEntry.java.
DEAL_10000_MELEE_DAMAGE
com.runehive.content.famehall.FameEntry.DEAL_10000_MELEE_DAMAGE =("Deal 10,000 Melee damage", 4151, FameType.PVP)
Definition at line 26 of file FameEntry.java.
DEAL_10000_RANGED_DAMAGE
com.runehive.content.famehall.FameEntry.DEAL_10000_RANGED_DAMAGE =("Deal 10,000 Ranged damage", 19481, FameType.PVP)
Definition at line 28 of file FameEntry.java.
display
final int com.runehive.content.famehall.FameEntry.display private
The item display.
Definition at line 93 of file FameEntry.java.
Referenced by FameEntry(), and getDisplay().
DRINK_10000_POTIONS
com.runehive.content.famehall.FameEntry.DRINK_10000_POTIONS =("Drink 10,000 potions", 139, FameType.MISC)
Definition at line 79 of file FameEntry.java.
EAT_10000_FOOD
com.runehive.content.famehall.FameEntry.EAT_10000_FOOD =("Eat 10,000 food", 385, FameType.MISC)
Definition at line 80 of file FameEntry.java.
entry
final String com.runehive.content.famehall.FameEntry.entry private
The entry string.
Definition at line 90 of file FameEntry.java.
Referenced by FameEntry(), getEntries(), and getEntry().
FIRST_ELYSIAN_DROP
com.runehive.content.famehall.FameEntry.FIRST_ELYSIAN_DROP =("First Elysian sigil drop", 12819, FameType.PVM)
Definition at line 36 of file FameEntry.java.
FIRST_TASSETS_DROP
com.runehive.content.famehall.FameEntry.FIRST_TASSETS_DROP =("First Bandos tassets drop", 11834, FameType.PVM)
Monster Killing.
Definition at line 35 of file FameEntry.java.
FIRST_VISAGE_DROP
com.runehive.content.famehall.FameEntry.FIRST_VISAGE_DROP =("First Visage drop", 11286, FameType.PVM)
Definition at line 37 of file FameEntry.java.
KILL_1000_BOUNTY_HUNTER_TARGETS
com.runehive.content.famehall.FameEntry.KILL_1000_BOUNTY_HUNTER_TARGETS =("Kill 1,000 Bounty Hunter targets", 12756, FameType.PVP)
Definition at line 24 of file FameEntry.java.
KILL_200_BOUNTY_HUNTER_TARGETS
com.runehive.content.famehall.FameEntry.KILL_200_BOUNTY_HUNTER_TARGETS =("Kill 200 Bounty Hunter targets", 12753, FameType.PVP)
Definition at line 22 of file FameEntry.java.
KILL_500_BOUNTY_HUNTER_TARGETS
com.runehive.content.famehall.FameEntry.KILL_500_BOUNTY_HUNTER_TARGETS =("Kill 500 Bounty Hunter targets", 12756, FameType.PVP)
Definition at line 23 of file FameEntry.java.
MAX_AGILITY_LEVEL
com.runehive.content.famehall.FameEntry.MAX_AGILITY_LEVEL =("Reach level 99 in Agility", 9771, FameType.SKILL)
Skilling.
Definition at line 57 of file FameEntry.java.
MAX_CLAN_MEMBERS
com.runehive.content.famehall.FameEntry.MAX_CLAN_MEMBERS =("Own a clan with 250 gameMembers", 12397, FameType.MISC)
Definition at line 81 of file FameEntry.java.
MAX_CONSTRUCTION_LEVEL
com.runehive.content.famehall.FameEntry.MAX_CONSTRUCTION_LEVEL =("Reach level 99 in Construction", 9789, FameType.SKILL)
Definition at line 65 of file FameEntry.java.
MAX_COOKING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_COOKING_LEVEL =("Reach level 99 in Cooking", 9801, FameType.SKILL)
Definition at line 69 of file FameEntry.java.
MAX_CRAFTING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_CRAFTING_LEVEL =("Reach level 99 in Crafting", 9780, FameType.SKILL)
Definition at line 60 of file FameEntry.java.
MAX_FARMING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_FARMING_LEVEL =("Reach level 99 in Farming", 9810, FameType.SKILL)
Definition at line 72 of file FameEntry.java.
MAX_FIREMAKING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_FIREMAKING_LEVEL =("Reach level 99 in Firemaking", 9804, FameType.SKILL)
Definition at line 70 of file FameEntry.java.
MAX_FISHING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_FISHING_LEVEL =("Reach level 99 in Fishing", 9798, FameType.SKILL)
Definition at line 68 of file FameEntry.java.
MAX_FLETCHING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_FLETCHING_LEVEL =("Reach level 99 in Fletching", 9783, FameType.SKILL)
Definition at line 61 of file FameEntry.java.
MAX_HERBLORE_LEVEL
com.runehive.content.famehall.FameEntry.MAX_HERBLORE_LEVEL =("Reach level 99 in Herblore", 9774, FameType.SKILL)
Definition at line 58 of file FameEntry.java.
MAX_HUNTER_LEVEL
com.runehive.content.famehall.FameEntry.MAX_HUNTER_LEVEL =("Reach level 99 in Hunter", 9948, FameType.SKILL)
Definition at line 63 of file FameEntry.java.
MAX_MINING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_MINING_LEVEL =("Reach level 99 in Mining", 9792, FameType.SKILL)
Definition at line 66 of file FameEntry.java.
MAX_RUNECRAFTING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_RUNECRAFTING_LEVEL =("Reach level 99 in Runecrafting", 9765, FameType.SKILL)
Definition at line 64 of file FameEntry.java.
MAX_SLAYER_LEVEL
com.runehive.content.famehall.FameEntry.MAX_SLAYER_LEVEL =("Reach level 99 in Slayer", 9786, FameType.SKILL)
Definition at line 62 of file FameEntry.java.
MAX_SMITHING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_SMITHING_LEVEL =("Reach level 99 in Smithing", 9795, FameType.SKILL)
Definition at line 67 of file FameEntry.java.
MAX_THIEVING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_THIEVING_LEVEL =("Reach level 99 in Thieving", 9777, FameType.SKILL)
Definition at line 59 of file FameEntry.java.
MAX_WOODCUTTING_LEVEL
com.runehive.content.famehall.FameEntry.MAX_WOODCUTTING_LEVEL =("Reach level 99 in Woodcutting", 9807, FameType.SKILL)
Definition at line 71 of file FameEntry.java.
OBTAIN_A_100_KILLSTREAK
com.runehive.content.famehall.FameEntry.OBTAIN_A_100_KILLSTREAK =("First 100 Kill streak", 13316, FameType.PVP)
Definition at line 21 of file FameEntry.java.
OBTAIN_A_50_KILLSTREAK
com.runehive.content.famehall.FameEntry.OBTAIN_A_50_KILLSTREAK =("First 50 Kill streak", 13315, FameType.PVP)
Definition at line 20 of file FameEntry.java.
OBTAIN_A_ARMADYL_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_ARMADYL_PET =("Obtain an Armadyl pet drop", 12649, FameType.PVM)
Definition at line 41 of file FameEntry.java.
OBTAIN_A_BANDOS_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_BANDOS_PET =("First Bandos pet drop", 12650, FameType.PVM)
Definition at line 38 of file FameEntry.java.
OBTAIN_A_CALLISTO_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_CALLISTO_PET =("First Callisto pet drop", 13178, FameType.PVM)
Definition at line 50 of file FameEntry.java.
OBTAIN_A_KBD_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_KBD_PET =("First KBD pet drop", 12653, FameType.PVM)
Definition at line 48 of file FameEntry.java.
OBTAIN_A_KRAKEN_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_KRAKEN_PET =("First Kraken pet drop", 12655, FameType.PVM)
Definition at line 47 of file FameEntry.java.
OBTAIN_A_MOLE_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_MOLE_PET =("First Giant mole pet drop", 12646, FameType.PVM)
Definition at line 46 of file FameEntry.java.
OBTAIN_A_PRIME_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_PRIME_PET =("First Prime pet drop", 12644, FameType.PVM)
Definition at line 44 of file FameEntry.java.
OBTAIN_A_REX_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_REX_PET =("First Rex pet drop", 12645, FameType.PVM)
Definition at line 43 of file FameEntry.java.
OBTAIN_A_SARADOMIN_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_SARADOMIN_PET =("First Saradomin pet drop", 12651, FameType.PVM)
Definition at line 40 of file FameEntry.java.
OBTAIN_A_SCORPIA_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_SCORPIA_PET =("First Scorpia pet drop", 13181, FameType.PVM)
Definition at line 52 of file FameEntry.java.
OBTAIN_A_SUPREME_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_SUPREME_PET =("First Supreme pet drop", 12643, FameType.PVM)
Definition at line 45 of file FameEntry.java.
OBTAIN_A_VENENATIS_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_VENENATIS_PET =("First Venenatis pet drop", 13177, FameType.PVM)
Definition at line 49 of file FameEntry.java.
OBTAIN_A_VETION_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_VETION_PET =("First Vet'ion pet drop", 13179, FameType.PVM)
Definition at line 51 of file FameEntry.java.
OBTAIN_A_ZAMORAK_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_ZAMORAK_PET =("First Zamorak pet drop", 12652, FameType.PVM)
Definition at line 39 of file FameEntry.java.
OBTAIN_A_ZULRAH_PET
com.runehive.content.famehall.FameEntry.OBTAIN_A_ZULRAH_PET =("First Zulrah pet drop", 12939, FameType.PVM)
Definition at line 42 of file FameEntry.java.
REACH_1000_KILLS
com.runehive.content.famehall.FameEntry.REACH_1000_KILLS =("Reach 1000 kills", 6824, FameType.PVP)
Definition at line 18 of file FameEntry.java.
REACH_100_KILLS
com.runehive.content.famehall.FameEntry.REACH_100_KILLS =("Reach 100 kills", 6824, FameType.PVP)
Player Killing.
Definition at line 15 of file FameEntry.java.
REACH_2500_KILLS
com.runehive.content.famehall.FameEntry.REACH_2500_KILLS =("Reach 2500 kills", 6824, FameType.PVP)
Definition at line 19 of file FameEntry.java.
REACH_250_KILLS
com.runehive.content.famehall.FameEntry.REACH_250_KILLS =("Reach 250 kills", 6824, FameType.PVP)
Definition at line 16 of file FameEntry.java.
REACH_500_KILLS
com.runehive.content.famehall.FameEntry.REACH_500_KILLS =("Reach 500 kills", 6824, FameType.PVP)
Definition at line 17 of file FameEntry.java.
type
final FameType com.runehive.content.famehall.FameEntry.type private
The fame type.
Definition at line 96 of file FameEntry.java.
Referenced by FameEntry(), getEntries(), and getType().
The documentation for this enum was generated from the following file:
java/com/runehive/content/famehall/FameEntry.java