RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData Enum Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData Enum Reference
Public Member Functions
SpawnData (String location, Position position)
Static Public Member Functions
static SpawnData generate ()
Public Attributes
LEVEL_18 =("Near boneyard hunter", new Position(3307, 3668, 0))
LEVEL_19 =("North of chaos altar", new Position(3222, 3658, 0))
LEVEL_28 =("Near vennenatis", new Position(3308, 3737, 0))
LEVEL_41 =("Near callisto", new Position(3270, 3843, 0))
LEVEL_52 =("Near rogue's castle", new Position(3304, 3929, 0))
LEVEL_53 =("Near scorpia's cave", new Position(3211, 3944, 0))
final String location
final Position position
Detailed Description
Definition at line 43 of file SkotizoUtility.java.
Constructor & Destructor Documentation
SpawnData()
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.SpawnData (String location, Position position)
Definition at line 54 of file SkotizoUtility.java.
{
            this.location = location;
            this.position = position;
        }
References location, and position.
Referenced by generate().
Member Function Documentation
generate()
SpawnData com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.generate () static
Definition at line 59 of file SkotizoUtility.java.
{
            return Utility.randomElement(values());
        }
References com.runehive.util.Utility.randomElement(), and SpawnData().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.generateSpawn().
Member Data Documentation
LEVEL_18
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.LEVEL_18 =("Near boneyard hunter", new Position(3307, 3668, 0))
Definition at line 44 of file SkotizoUtility.java.
LEVEL_19
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.LEVEL_19 =("North of chaos altar", new Position(3222, 3658, 0))
Definition at line 45 of file SkotizoUtility.java.
LEVEL_28
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.LEVEL_28 =("Near vennenatis", new Position(3308, 3737, 0))
Definition at line 46 of file SkotizoUtility.java.
LEVEL_41
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.LEVEL_41 =("Near callisto", new Position(3270, 3843, 0))
Definition at line 47 of file SkotizoUtility.java.
LEVEL_52
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.LEVEL_52 =("Near rogue's castle", new Position(3304, 3929, 0))
Definition at line 48 of file SkotizoUtility.java.
LEVEL_53
com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.LEVEL_53 =("Near scorpia's cave", new Position(3211, 3944, 0))
Definition at line 49 of file SkotizoUtility.java.
location
final String com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.location
Definition at line 51 of file SkotizoUtility.java.
Referenced by SpawnData().
position
final Position com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.SpawnData.position
Definition at line 52 of file SkotizoUtility.java.
Referenced by SpawnData().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/skotizo/SkotizoUtility.java