RuneHive-Game: com.runehive.content.prestige.PrestigeData Enum Reference
com.runehive.content.prestige.PrestigeData Enum Reference
Holds the prestige data.
Public Member Functions
PrestigeData (String name, int skill, int button, int string)
Constructs a new Prestige.
Static Public Member Functions
[static initializer]
static PrestigeData forButton (int button)
Grabs the prestige data based on the button identification.
Public Attributes
AGILITY =("Agility", Skill.AGILITY, -13480, 52018)
ATTACK =("Attack", Skill.ATTACK, -13504, 52010)
final int button
The button identification of the prestige.
COOKING =("Cooking", Skill.COOKING, -13453, 52027)
CRAFTING =("Crafting", Skill.CRAFTING, -13471, 52021)
DEFENCE =("Defence", Skill.DEFENCE, -13498, 52012)
FARMING =("Farming", Skill.FARMING, -13444, 52030)
FIREMAKING =("Firemaking", Skill.FIREMAKING, -13450, 52028)
FISHING =("Fishing", Skill.FISHING, -13456, 52026)
FLETCHING =("Fletching", Skill.FLETCHING, -13468, 52022)
HERBLORE =("Herblore", Skill.HERBLORE, -13477, 52019)
HITPOINTS =("Hitpoints", Skill.HITPOINTS, -13483, 52017)
HUNTER =("Hunter", Skill.HUNTER, -13441, 52031)
MAGIC =("Magic", Skill.MAGIC, -13489, 52015)
MINING =("Mining", Skill.MINING, -13462, 52024)
final String name
The name of the prestige.
PRAYER =("Prayer", Skill.PRAYER, -13492, 52014)
RANGE =("Ranged", Skill.RANGED, -13495, 52013)
RUNECRAFTING =("Runecraft", Skill.RUNECRAFTING, -13486, 52016)
final int skill
The skill identification of the prestige.
SLAYER =("Slayer", Skill.SLAYER, -13465, 52023)
SMITHING =("Smithing", Skill.SMITHING, -13459, 52025)
STRENGTH =("Strength", Skill.STRENGTH, -13501, 52011)
final int string
The string identification of the prestige.
THIEVING =("Thieving", Skill.THIEVING, -13474, 52020)
WOODCUTTING =("Woodcutting", Skill.WOODCUTTING, -13447, 52029)
Static Public Attributes
static final PrestigeData[] values = values()
Static Private Attributes
static final Map< Integer, PrestigeData > prestigeMap
Detailed Description
Holds the prestige data.
Author
Daniel.
Definition at line 14 of file PrestigeData.java.
Constructor & Destructor Documentation
PrestigeData()
com.runehive.content.prestige.PrestigeData.PrestigeData (String name, int skill, int button, int string)
Constructs a new Prestige.
Definition at line 73 of file PrestigeData.java.
{
        this.name = name;
        this.skill = skill;
        this.button = button;
        this.string = string;
    }
References button, name, skill, and string.
Referenced by [static initializer](), and forButton().
Member Function Documentation
[static initializer]()
com.runehive.content.prestige.PrestigeData.[static initializer] static
References PrestigeData(), prestigeMap, and values.
forButton()
PrestigeData com.runehive.content.prestige.PrestigeData.forButton (int button) static
Grabs the prestige data based on the button identification.
Definition at line 83 of file PrestigeData.java.
{
        return prestigeMap.get(button);
    }
References button, PrestigeData(), and prestigeMap.
Member Data Documentation
AGILITY
com.runehive.content.prestige.PrestigeData.AGILITY =("Agility", Skill.AGILITY, -13480, 52018)
Definition at line 31 of file PrestigeData.java.
ATTACK
com.runehive.content.prestige.PrestigeData.ATTACK =("Attack", Skill.ATTACK, -13504, 52010)
Definition at line 15 of file PrestigeData.java.
button
final int com.runehive.content.prestige.PrestigeData.button
The button identification of the prestige.
Definition at line 63 of file PrestigeData.java.
Referenced by forButton(), and PrestigeData().
COOKING
com.runehive.content.prestige.PrestigeData.COOKING =("Cooking", Skill.COOKING, -13453, 52027)
Definition at line 22 of file PrestigeData.java.
CRAFTING
com.runehive.content.prestige.PrestigeData.CRAFTING =("Crafting", Skill.CRAFTING, -13471, 52021)
Definition at line 27 of file PrestigeData.java.
DEFENCE
com.runehive.content.prestige.PrestigeData.DEFENCE =("Defence", Skill.DEFENCE, -13498, 52012)
Definition at line 16 of file PrestigeData.java.
FARMING
com.runehive.content.prestige.PrestigeData.FARMING =("Farming", Skill.FARMING, -13444, 52030)
Definition at line 34 of file PrestigeData.java.
FIREMAKING
com.runehive.content.prestige.PrestigeData.FIREMAKING =("Firemaking", Skill.FIREMAKING, -13450, 52028)
Definition at line 26 of file PrestigeData.java.
FISHING
com.runehive.content.prestige.PrestigeData.FISHING =("Fishing", Skill.FISHING, -13456, 52026)
Definition at line 25 of file PrestigeData.java.
FLETCHING
com.runehive.content.prestige.PrestigeData.FLETCHING =("Fletching", Skill.FLETCHING, -13468, 52022)
Definition at line 24 of file PrestigeData.java.
HERBLORE
com.runehive.content.prestige.PrestigeData.HERBLORE =("Herblore", Skill.HERBLORE, -13477, 52019)
Definition at line 30 of file PrestigeData.java.
HITPOINTS
com.runehive.content.prestige.PrestigeData.HITPOINTS =("Hitpoints", Skill.HITPOINTS, -13483, 52017)
Definition at line 18 of file PrestigeData.java.
HUNTER
com.runehive.content.prestige.PrestigeData.HUNTER =("Hunter", Skill.HUNTER, -13441, 52031)
Definition at line 36 of file PrestigeData.java.
MAGIC
com.runehive.content.prestige.PrestigeData.MAGIC =("Magic", Skill.MAGIC, -13489, 52015)
Definition at line 21 of file PrestigeData.java.
MINING
com.runehive.content.prestige.PrestigeData.MINING =("Mining", Skill.MINING, -13462, 52024)
Definition at line 29 of file PrestigeData.java.
name
final String com.runehive.content.prestige.PrestigeData.name
The name of the prestige.
Definition at line 53 of file PrestigeData.java.
Referenced by PrestigeData().
PRAYER
com.runehive.content.prestige.PrestigeData.PRAYER =("Prayer", Skill.PRAYER, -13492, 52014)
Definition at line 20 of file PrestigeData.java.
prestigeMap
final Map<Integer, PrestigeData> com.runehive.content.prestige.PrestigeData.prestigeMap static private
Definition at line 39 of file PrestigeData.java.
Referenced by [static initializer](), and forButton().
RANGE
com.runehive.content.prestige.PrestigeData.RANGE =("Ranged", Skill.RANGED, -13495, 52013)
Definition at line 19 of file PrestigeData.java.
RUNECRAFTING
com.runehive.content.prestige.PrestigeData.RUNECRAFTING =("Runecraft", Skill.RUNECRAFTING, -13486, 52016)
Definition at line 35 of file PrestigeData.java.
skill
final int com.runehive.content.prestige.PrestigeData.skill
The skill identification of the prestige.
Definition at line 58 of file PrestigeData.java.
Referenced by com.runehive.content.prestige.Prestige.prestige(), and PrestigeData().
SLAYER
com.runehive.content.prestige.PrestigeData.SLAYER =("Slayer", Skill.SLAYER, -13465, 52023)
Definition at line 33 of file PrestigeData.java.
SMITHING
com.runehive.content.prestige.PrestigeData.SMITHING =("Smithing", Skill.SMITHING, -13459, 52025)
Definition at line 28 of file PrestigeData.java.
STRENGTH
com.runehive.content.prestige.PrestigeData.STRENGTH =("Strength", Skill.STRENGTH, -13501, 52011)
Definition at line 17 of file PrestigeData.java.
string
final int com.runehive.content.prestige.PrestigeData.string
The string identification of the prestige.
Definition at line 68 of file PrestigeData.java.
Referenced by PrestigeData().
THIEVING
com.runehive.content.prestige.PrestigeData.THIEVING =("Thieving", Skill.THIEVING, -13474, 52020)
Definition at line 32 of file PrestigeData.java.
values
final PrestigeData [] com.runehive.content.prestige.PrestigeData.values = values() static
Definition at line 38 of file PrestigeData.java.
Referenced by [static initializer](), and com.runehive.content.prestige.Prestige.open().
WOODCUTTING
com.runehive.content.prestige.PrestigeData.WOODCUTTING =("Woodcutting", Skill.WOODCUTTING, -13447, 52029)
Definition at line 23 of file PrestigeData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/prestige/PrestigeData.java