RuneHive-Game: com.runehive.game.world.entity.skill.SkillData Enum Reference
com.runehive.game.world.entity.skill.SkillData Enum Reference
The enumerated type whose elements represent data for the skills.
Public Member Functions
final int getChatbox ()
Gets the chatbox itemcontainer displayed on level up.
final int getFirstLine ()
Gets the first line that level up text will be printed on.
final int getId ()
Gets the identification for this skill in the skills array.
final int getSecondLine ()
Gets the second line that level up text will be printed on.
final boolean isCombatSkill ()
Gets if the skill is combat related.
SkillData (int id, int firstLine, int secondLine, int chatbox, boolean combatSkill)
Creates a new SkillData.
final String toString ()
Public Attributes
AGILITY =(Skill.AGILITY, 4278, 4279, 4277, false)
ATTACK =(Skill.ATTACK, 6248, 6249, 6247, true)
CONSTRUCTION =(Skill.CONSTRUCTION, 4268, 4269, 4267, false)
COOKING =(Skill.COOKING, 6227, 6228, 6226, false)
CRAFTING =(Skill.CRAFTING, 6264, 6265, 6263, false)
DEFENCE =(Skill.DEFENCE, 6254, 6255, 6253, true)
FARMING =(Skill.FARMING, 313, 312, 310, false)
FIREMAKING =(Skill.FIREMAKING, 4283, 4284, 4282, false)
FISHING =(Skill.FISHING, 6259, 6260, 6258, false)
FLETCHING =(Skill.FLETCHING, 6232, 6233, 6231, false)
HERBLORE =(Skill.HERBLORE, 6238, 6239, 6237, false)
HITPOINTS =(Skill.HITPOINTS, 6217, 6218, 6216, true)
HUNTER =(Skill.HUNTER, 313, 312, 310, false)
MAGIC =(Skill.MAGIC, 6212, 6213, 6211, true)
MINING =(Skill.MINING, 4417, 4438, 4416, false)
PRAYER =(Skill.PRAYER, 6243, 6244, 6242, true)
RANGED =(Skill.RANGED, 5453, 6114, 4443, true)
RUNECRAFTING =(Skill.RUNECRAFTING, 4268, 4269, 4267, false)
SLAYER =(Skill.SLAYER, 12123, 12124, 12122, false)
SMITHING =(Skill.SMITHING, 6222, 6223, 6221, false)
STRENGTH =(Skill.STRENGTH, 6207, 6208, 6206, true)
THIEVING =(Skill.THIEVING, 4263, 4264, 4261, false)
WOODCUTTING =(Skill.WOODCUTTING, 4273, 4274, 4272, false)
Private Attributes
final int chatbox
The chatbox itemcontainer displayed on level up.
final boolean combatSkill
The state of the skill being related to combat.
final int firstLine
The first line that level up text will be printed on.
final int id
The identification for this skill in the skills array.
final int secondLine
The second line that level up text will be printed on.
Detailed Description
The enumerated type whose elements represent data for the skills.
Author
lare96 http://github.com/lare96
Definition at line 10 of file SkillData.java.
Constructor & Destructor Documentation
SkillData()
com.runehive.game.world.entity.skill.SkillData.SkillData (int id, int firstLine, int secondLine, int chatbox, boolean combatSkill)
Creates a new SkillData.
Parameters
id the identification for this skill in the skills array.
firstLine the first line that level up text will be printed on.
secondLine the second line that level up text will be printed on.
chatbox the chatbox itemcontainer displayed on level up.
combatSkill the state of the skill being related to combat.
Definition at line 64 of file SkillData.java.
{
        this.id = id;
        this.firstLine = firstLine;
        this.secondLine = secondLine;
        this.chatbox = chatbox;
        this.combatSkill = combatSkill;
    }
References chatbox, combatSkill, firstLine, id, and secondLine.
Member Function Documentation
getChatbox()
final int com.runehive.game.world.entity.skill.SkillData.getChatbox ()
Gets the chatbox itemcontainer displayed on level up.
Returns
the chatbox itemcontainer.
Definition at line 104 of file SkillData.java.
{
        return chatbox;
    }
References chatbox.
Referenced by com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface().
getFirstLine()
final int com.runehive.game.world.entity.skill.SkillData.getFirstLine ()
Gets the first line that level up text will be printed on.
Returns
the first line.
Definition at line 86 of file SkillData.java.
{
        return firstLine;
    }
References firstLine.
Referenced by com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface().
getId()
final int com.runehive.game.world.entity.skill.SkillData.getId ()
Gets the identification for this skill in the skills array.
Returns
the identification for this skill.
Definition at line 77 of file SkillData.java.
{
        return id;
    }
References id.
getSecondLine()
final int com.runehive.game.world.entity.skill.SkillData.getSecondLine ()
Gets the second line that level up text will be printed on.
Returns
the second line.
Definition at line 95 of file SkillData.java.
{
        return secondLine;
    }
References secondLine.
Referenced by com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface().
isCombatSkill()
final boolean com.runehive.game.world.entity.skill.SkillData.isCombatSkill ()
Gets if the skill is combat related.
Returns
the state.
Definition at line 113 of file SkillData.java.
{
        return combatSkill;
    }
References combatSkill.
Referenced by com.runehive.game.world.entity.skill.SkillManager.addExperience(), and com.runehive.game.world.entity.skill.SkillManager.updateSkill().
toString()
final String com.runehive.game.world.entity.skill.SkillData.toString ()
Definition at line 118 of file SkillData.java.
{
        return Utility.capitalizeSentence(name().toLowerCase().replace("_", " "));
    }
References com.runehive.util.Utility.capitalizeSentence().
Referenced by com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface().
Member Data Documentation
AGILITY
com.runehive.game.world.entity.skill.SkillData.AGILITY =(Skill.AGILITY, 4278, 4279, 4277, false)
Definition at line 27 of file SkillData.java.
ATTACK
com.runehive.game.world.entity.skill.SkillData.ATTACK =(Skill.ATTACK, 6248, 6249, 6247, true)
Definition at line 11 of file SkillData.java.
chatbox
final int com.runehive.game.world.entity.skill.SkillData.chatbox private
The chatbox itemcontainer displayed on level up.
Definition at line 45 of file SkillData.java.
Referenced by getChatbox(), and SkillData().
combatSkill
final boolean com.runehive.game.world.entity.skill.SkillData.combatSkill private
The state of the skill being related to combat.
Definition at line 48 of file SkillData.java.
Referenced by isCombatSkill(), and SkillData().
CONSTRUCTION
com.runehive.game.world.entity.skill.SkillData.CONSTRUCTION =(Skill.CONSTRUCTION, 4268, 4269, 4267, false)
Definition at line 32 of file SkillData.java.
COOKING
com.runehive.game.world.entity.skill.SkillData.COOKING =(Skill.COOKING, 6227, 6228, 6226, false)
Definition at line 18 of file SkillData.java.
CRAFTING
com.runehive.game.world.entity.skill.SkillData.CRAFTING =(Skill.CRAFTING, 6264, 6265, 6263, false)
Definition at line 23 of file SkillData.java.
Referenced by com.runehive.content.skill.impl.hunter.birdhouse.action.CreateBirdHouse.execute().
DEFENCE
com.runehive.game.world.entity.skill.SkillData.DEFENCE =(Skill.DEFENCE, 6254, 6255, 6253, true)
Definition at line 12 of file SkillData.java.
FARMING
com.runehive.game.world.entity.skill.SkillData.FARMING =(Skill.FARMING, 313, 312, 310, false)
Definition at line 30 of file SkillData.java.
Referenced by com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface().
FIREMAKING
com.runehive.game.world.entity.skill.SkillData.FIREMAKING =(Skill.FIREMAKING, 4283, 4284, 4282, false)
Definition at line 22 of file SkillData.java.
firstLine
final int com.runehive.game.world.entity.skill.SkillData.firstLine private
The first line that level up text will be printed on.
Definition at line 39 of file SkillData.java.
Referenced by getFirstLine(), and SkillData().
FISHING
com.runehive.game.world.entity.skill.SkillData.FISHING =(Skill.FISHING, 6259, 6260, 6258, false)
Definition at line 21 of file SkillData.java.
FLETCHING
com.runehive.game.world.entity.skill.SkillData.FLETCHING =(Skill.FLETCHING, 6232, 6233, 6231, false)
Definition at line 20 of file SkillData.java.
HERBLORE
com.runehive.game.world.entity.skill.SkillData.HERBLORE =(Skill.HERBLORE, 6238, 6239, 6237, false)
Definition at line 26 of file SkillData.java.
HITPOINTS
com.runehive.game.world.entity.skill.SkillData.HITPOINTS =(Skill.HITPOINTS, 6217, 6218, 6216, true)
Definition at line 14 of file SkillData.java.
HUNTER
com.runehive.game.world.entity.skill.SkillData.HUNTER =(Skill.HUNTER, 313, 312, 310, false)
Definition at line 33 of file SkillData.java.
Referenced by com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot(), and com.runehive.game.world.entity.skill.SkillManager.showLevelUpInterface().
id
final int com.runehive.game.world.entity.skill.SkillData.id private
The identification for this skill in the skills array.
Definition at line 36 of file SkillData.java.
Referenced by getId(), and SkillData().
MAGIC
com.runehive.game.world.entity.skill.SkillData.MAGIC =(Skill.MAGIC, 6212, 6213, 6211, true)
Definition at line 17 of file SkillData.java.
MINING
com.runehive.game.world.entity.skill.SkillData.MINING =(Skill.MINING, 4417, 4438, 4416, false)
Definition at line 25 of file SkillData.java.
PRAYER
com.runehive.game.world.entity.skill.SkillData.PRAYER =(Skill.PRAYER, 6243, 6244, 6242, true)
Definition at line 16 of file SkillData.java.
RANGED
com.runehive.game.world.entity.skill.SkillData.RANGED =(Skill.RANGED, 5453, 6114, 4443, true)
Definition at line 15 of file SkillData.java.
RUNECRAFTING
com.runehive.game.world.entity.skill.SkillData.RUNECRAFTING =(Skill.RUNECRAFTING, 4268, 4269, 4267, false)
Definition at line 31 of file SkillData.java.
secondLine
final int com.runehive.game.world.entity.skill.SkillData.secondLine private
The second line that level up text will be printed on.
Definition at line 42 of file SkillData.java.
Referenced by getSecondLine(), and SkillData().
SLAYER
com.runehive.game.world.entity.skill.SkillData.SLAYER =(Skill.SLAYER, 12123, 12124, 12122, false)
Definition at line 29 of file SkillData.java.
SMITHING
com.runehive.game.world.entity.skill.SkillData.SMITHING =(Skill.SMITHING, 6222, 6223, 6221, false)
Definition at line 24 of file SkillData.java.
STRENGTH
com.runehive.game.world.entity.skill.SkillData.STRENGTH =(Skill.STRENGTH, 6207, 6208, 6206, true)
Definition at line 13 of file SkillData.java.
THIEVING
com.runehive.game.world.entity.skill.SkillData.THIEVING =(Skill.THIEVING, 4263, 4264, 4261, false)
Definition at line 28 of file SkillData.java.
WOODCUTTING
com.runehive.game.world.entity.skill.SkillData.WOODCUTTING =(Skill.WOODCUTTING, 4273, 4274, 4272, false)
Definition at line 19 of file SkillData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/skill/SkillData.java