RuneHive-Game: com.runehive.game.world.items.ItemComparator Enum Reference
com.runehive.game.world.items.ItemComparator Enum Reference
Public Member Functions
int compare (Item first, Item second)
Public Attributes
HIGH_ALCH_COMPARATOR
ITEM_AMOUNT_COMPARATOR
ITEM_ID_COMPARATOR
ITEM_WEIGHT_COMPARATOR
LOW_ALCH_COMPARATOR
SHOP_VALUE_COMPARATOR
Detailed Description
Definition at line 7 of file ItemComparator.java.
Member Function Documentation
compare()
int com.runehive.game.world.items.ItemComparator.compare (Item first, Item second)
Definition at line 16 of file ItemComparator.java.
{
        double firstValue = 0;
        double secondValue = 0;
        if (first == null && second == null) {
            return 0;
        }
        if (first == null) {
            return 1;
        }
        if (second == null) {
            return -1;
        }
        switch (this) {
        case HIGH_ALCH_COMPARATOR:
            firstValue = first.getValue(PriceType.HIGH_ALCH_VALUE);
            secondValue = second.getValue(PriceType.HIGH_ALCH_VALUE);
            break;
        case ITEM_AMOUNT_COMPARATOR:
            firstValue = first.getAmount();
            secondValue = second.getAmount();
            break;
        case ITEM_ID_COMPARATOR:
            firstValue = first.getId();
            secondValue = second.getId();
            break;
        case ITEM_WEIGHT_COMPARATOR:
            firstValue = first.getWeight();
            secondValue = second.getWeight();
            break;
        case LOW_ALCH_COMPARATOR:
            firstValue = first.getLowAlch();
            secondValue = second.getLowAlch();
            break;
        case SHOP_VALUE_COMPARATOR:
            firstValue = first.getValue(PriceType.VALUE);
            secondValue = second.getValue(PriceType.VALUE);
            break;
        }
        return Integer.signum((int) (secondValue - firstValue));
    }
References com.runehive.game.world.items.Item.getAmount(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getLowAlch(), com.runehive.game.world.items.Item.getValue(), com.runehive.game.world.items.Item.getWeight(), HIGH_ALCH_COMPARATOR, com.runehive.game.world.items.containers.pricechecker.PriceType.HIGH_ALCH_VALUE, ITEM_AMOUNT_COMPARATOR, ITEM_ID_COMPARATOR, ITEM_WEIGHT_COMPARATOR, LOW_ALCH_COMPARATOR, SHOP_VALUE_COMPARATOR, and com.runehive.game.world.items.containers.pricechecker.PriceType.VALUE.
Member Data Documentation
HIGH_ALCH_COMPARATOR
com.runehive.game.world.items.ItemComparator.HIGH_ALCH_COMPARATOR
Definition at line 8 of file ItemComparator.java.
Referenced by compare().
ITEM_AMOUNT_COMPARATOR
com.runehive.game.world.items.ItemComparator.ITEM_AMOUNT_COMPARATOR
Definition at line 13 of file ItemComparator.java.
Referenced by compare().
ITEM_ID_COMPARATOR
com.runehive.game.world.items.ItemComparator.ITEM_ID_COMPARATOR
Definition at line 12 of file ItemComparator.java.
Referenced by compare().
ITEM_WEIGHT_COMPARATOR
com.runehive.game.world.items.ItemComparator.ITEM_WEIGHT_COMPARATOR
Definition at line 10 of file ItemComparator.java.
Referenced by compare().
LOW_ALCH_COMPARATOR
com.runehive.game.world.items.ItemComparator.LOW_ALCH_COMPARATOR
Definition at line 9 of file ItemComparator.java.
Referenced by compare().
SHOP_VALUE_COMPARATOR
com.runehive.game.world.items.ItemComparator.SHOP_VALUE_COMPARATOR
Definition at line 11 of file ItemComparator.java.
Referenced by compare(), and com.runehive.content.ItemsKeptOnDeath.open().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/items/ItemComparator.java