RuneHive-Game: com.runehive.game.world.entity.combat.magic.MagicImpact Enum Reference
com.runehive.game.world.entity.combat.magic.MagicImpact Enum Reference
Public Member Functions
CombatImpact getEffect ()
MagicImpact (CombatImpact effect)
Public Attributes
AHRIM_BLAST
BIND =((attacker, defender, hit, extra) -> freeze(defender, 5))
BLOOD_BARRAGE =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> bloodBarrage(attacker, defender, other, hit, extra)))
BLOOD_BLITZ =((attacker, defender, hit, extra) -> heal(attacker, hit))
BLOOD_BURST =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> bloodBurst(attacker, defender, other, hit, extra)))
BLOOD_RUSH =((attacker, defender, hit, extra) -> heal(attacker, hit))
CONFUSE =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.ATTACK, 5))
CURSE =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.DEFENCE, 5))
ENFEEBLE =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.STRENGTH, 10))
ENTANGLE =(((attacker, defender, hit, extra) -> freeze(defender, 15)))
ICE_BARRAGE =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> iceBarrage(attacker, defender, other, extra)))
ICE_BLITZ =((attacker, defender, hit, extra) -> freeze(defender, 15))
ICE_BURST =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> iceBurst(attacker, defender, other, extra)))
ICE_RUSH =((attacker, defender, hit, extra) -> freeze(defender, 5))
KBD_FREEZE =((attacker, defender, hit, extra) -> freeze(defender, 5))
KBD_POISON =((attacker, defender, hit, extra) -> poison(attacker, defender, hit, PoisonType.DEFAULT_NPC))
KBD_SHOCK =((attacker, defender, hit, extra) -> kbdShock(defender))
MAGIC_DART
SHADOW_BARRAGE =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> shadowBarrage(attacker, defender, other, extra)))
SHADOW_BLITZ =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.ATTACK, 15))
SHADOW_BURST =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> shadowBurst(attacker, defender, other, extra)))
SHADOW_RUSH =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.ATTACK, 10))
SMOKE_BARRAGE =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> smokeBarrage(attacker, defender, other, hit, extra)))
SMOKE_BLITZ =((attacker, defender, hit, extra) -> poison(attacker, defender, hit, PoisonType.SUPER_MAGIC))
SMOKE_BURST =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> smokeBurst(attacker, defender, other, hit, extra)))
SMOKE_RUSH =((attacker, defender, hit, extra) -> poison(attacker, defender, hit, PoisonType.DEFAULT_MAGIC))
SNARE =(((attacker, defender, hit, extra) -> freeze(defender, 10)))
STUN =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.ATTACK, 10))
TELEBLOCK =((attacker, defender, hit, extra) -> teleblock(defender))
VULNERABILITY =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.DEFENCE, 10))
WEAKEN =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.STRENGTH, 5))
Static Private Member Functions
static void bloodBarrage (Mob attacker, Mob defender, Mob other, Hit hit, List< Hit > extra)
static void bloodBurst (Mob attacker, Mob defender, Mob other, Hit hit, List< Hit > extra)
static void freeze (Mob defender, int timer)
static void heal (Mob attacker, Hit hit)
static CombatHit hitEvent (Mob attacker, Mob defender, Mob other, int max, List< Hit > extra)
static void iceBarrage (Mob attacker, Mob defender, Mob other, List< Hit > extra)
static void iceBurst (Mob attacker, Mob defender, Mob other, List< Hit > extra)
static void kbdShock (Mob defender)
static void lowerSkill (Mob defender, int id, int percentage)
static void poison (Mob attacker, Mob defender, Hit hit, PoisonType type)
static void shadowBarrage (Mob attacker, Mob defender, Mob other, List< Hit > extra)
static void shadowBurst (Mob attacker, Mob defender, Mob other, List< Hit > extra)
static void smokeBarrage (Mob attacker, Mob defender, Mob other, Hit hit, List< Hit > extra)
static void smokeBurst (Mob attacker, Mob defender, Mob other, Hit hit, List< Hit > extra)
static void teleblock (Mob defender)
Private Attributes
final CombatImpact effect
Detailed Description
Definition at line 21 of file MagicImpact.java.
Constructor & Destructor Documentation
MagicImpact()
com.runehive.game.world.entity.combat.magic.MagicImpact.MagicImpact (CombatImpact effect)
Definition at line 85 of file MagicImpact.java.
{
        this.effect = new CombatImpact() {
            @Override
            public boolean canAffect(Mob attacker, Mob defender, Hit hit) {
                return hit.isAccurate() && effect.canAffect(attacker, defender, hit);
            }
            @Override
            public void impact(Mob attacker, Mob defender, Hit hit, List<Hit> hits) {
                effect.impact(attacker, defender, hit, hits);
            }
        };
    }
References effect.
Member Function Documentation
bloodBarrage()
void com.runehive.game.world.entity.combat.magic.MagicImpact.bloodBarrage (Mob attacker, Mob defender, Mob other, Hit hit, List< Hit > extra) static private
Definition at line 216 of file MagicImpact.java.
{
        heal(attacker, hit);
        CombatHit next = hitEvent(attacker, defender, other, 29, extra);
        if (next != null && next.isAccurate()) {
            heal(attacker, next);
        }
    }
References heal(), hitEvent(), and com.runehive.game.world.entity.combat.hit.Hit.isAccurate().
bloodBurst()
void com.runehive.game.world.entity.combat.magic.MagicImpact.bloodBurst (Mob attacker, Mob defender, Mob other, Hit hit, List< Hit > extra) static private
Definition at line 208 of file MagicImpact.java.
{
        heal(attacker, hit);
        CombatHit next = hitEvent(attacker, defender, other, 21, extra);
        if (next != null && next.isAccurate()) {
            heal(attacker, next);
        }
    }
References heal(), hitEvent(), and com.runehive.game.world.entity.combat.hit.Hit.isAccurate().
freeze()
void com.runehive.game.world.entity.combat.magic.MagicImpact.freeze (Mob defender, int timer) static private
Definition at line 152 of file MagicImpact.java.
{
        if (!defender.freezeImmunity.finished()) {
            return;
        }
        defender.freezeImmunity.reset(TimeUnit.MILLISECONDS.convert(timer + 10, TimeUnit.SECONDS));
        defender.locking.lock(timer, LockType.FREEZE);
        defender.movement.reset();
    }
References com.runehive.util.Stopwatch.finished(), com.runehive.game.world.entity.mob.data.LockType.FREEZE, com.runehive.game.world.entity.mob.Mob.freezeImmunity, com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Mob.locking, com.runehive.game.world.entity.mob.Mob.movement, com.runehive.game.world.entity.mob.movement.Movement.reset(), and com.runehive.util.Stopwatch.reset().
Referenced by iceBarrage(), and iceBurst().
getEffect()
CombatImpact com.runehive.game.world.entity.combat.magic.MagicImpact.getEffect ()
Definition at line 99 of file MagicImpact.java.
{
        return effect;
    }
References effect.
Referenced by com.runehive.util.parser.impl.CombatProjectileParser.parse().
heal()
void com.runehive.game.world.entity.combat.magic.MagicImpact.heal (Mob attacker, Hit hit) static private
Definition at line 162 of file MagicImpact.java.
{
        Skill skill = attacker.skills.get(Skill.HITPOINTS);
        if (skill.getLevel() < skill.getMaxLevel()) {
            float heal = hit.getDamage() / 40f;
            if (heal + skill.getLevel() > skill.getMaxLevel()) {
                heal = skill.getMaxLevel() - skill.getLevel();
            }
            attacker.heal((int) (heal * 10));
        }
    }
References com.runehive.game.world.entity.skill.SkillManager.get(), heal(), com.runehive.game.world.entity.mob.Mob.heal(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by bloodBarrage(), bloodBurst(), and heal().
hitEvent()
CombatHit com.runehive.game.world.entity.combat.magic.MagicImpact.hitEvent (Mob attacker, Mob defender, Mob other, int max, List< Hit > extra) static private
Definition at line 246 of file MagicImpact.java.
{
        if (!attacker.getCombat().canAttack(other)) {
            return null;
        }
        if (!attacker.equals(other) && !defender.equals(other)) {
            int hitDelay = CombatUtil.getHitDelay(attacker, defender, CombatType.MAGIC);
            CombatHit hit = new CombatHit(FormulaFactory.nextMagicHit(attacker, other, max), hitDelay, 0);
            attacker.getCombat().submitHits(other, hit);
            if (extra != null) extra.add(hit);
            return hit;
        }
        return null;
    }
References com.runehive.game.world.entity.Entity.equals(), com.runehive.game.world.entity.mob.Mob.getCombat(), com.runehive.game.world.entity.combat.CombatUtil.getHitDelay(), com.runehive.game.world.entity.combat.CombatType.MAGIC, and com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMagicHit().
Referenced by bloodBarrage(), bloodBurst(), iceBarrage(), iceBurst(), shadowBarrage(), shadowBurst(), smokeBarrage(), and smokeBurst().
iceBarrage()
void com.runehive.game.world.entity.combat.magic.MagicImpact.iceBarrage (Mob attacker, Mob defender, Mob other, List< Hit > extra) static private
Definition at line 232 of file MagicImpact.java.
{
        freeze(defender, 20);
        CombatHit next = hitEvent(attacker, defender, other, 28, extra);
        if (next != null && next.isAccurate()) {
            freeze(other, 20);
        }
    }
References freeze(), hitEvent(), and com.runehive.game.world.entity.combat.hit.Hit.isAccurate().
iceBurst()
void com.runehive.game.world.entity.combat.magic.MagicImpact.iceBurst (Mob attacker, Mob defender, Mob other, List< Hit > extra) static private
Definition at line 224 of file MagicImpact.java.
{
        freeze(defender, 10);
        CombatHit next = hitEvent(attacker, defender, other, 22, extra);
        if (next != null && next.isAccurate()) {
            freeze(other, 10);
        }
    }
References freeze(), hitEvent(), and com.runehive.game.world.entity.combat.hit.Hit.isAccurate().
kbdShock()
void com.runehive.game.world.entity.combat.magic.MagicImpact.kbdShock (Mob defender) static private
Definition at line 103 of file MagicImpact.java.
{
        if (!defender.isPlayer()) {
            return;
        }
        Player player = defender.getPlayer();
        int id = RandomUtils.inclusiveExcludes(Skill.ATTACK, Skill.MAGIC, Skill.HITPOINTS);
        Skill skill = player.skills.get(id);
        if (skill.getLevel() - 1 >= 0) {
            skill.removeLevel(1);
            player.skills.refresh(id);
        }
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.util.RandomUtils.inclusiveExcludes(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.skill.Skill.MAGIC, com.runehive.game.world.entity.skill.SkillManager.refresh(), and com.runehive.game.world.entity.mob.Mob.skills.
lowerSkill()
void com.runehive.game.world.entity.combat.magic.MagicImpact.lowerSkill (Mob defender, int id, int percentage) static private
Definition at line 118 of file MagicImpact.java.
{
        if (!defender.isPlayer()) {
            return;
        }
        Player player = defender.getPlayer();
        Skill skill = player.skills.get(id);
        double ratio = percentage / 100.0;
        int limit = (int) (skill.getMaxLevel() * (1 - ratio));
        int amount = (int) (skill.getLevel() * ratio);
        if (skill.getLevel() - amount < limit) {
            amount = skill.getLevel() - limit;
        }
        if (amount > 0) {
            skill.removeLevel(amount);
            player.skills.refresh(id);
        }
    }
References com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.mob.Mob.getPlayer(), com.runehive.game.world.entity.mob.Mob.isPlayer(), com.runehive.game.world.entity.skill.SkillManager.refresh(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by shadowBarrage(), and shadowBurst().
poison()
void com.runehive.game.world.entity.combat.magic.MagicImpact.poison (Mob attacker, Mob defender, Hit hit, PoisonType type) static private
Definition at line 140 of file MagicImpact.java.
{
        if (!hit.isAccurate() || defender.isPoisoned()) {
            return;
        }
        if (!attacker.isNpc() && hit.getDamage() < 1) {
            return;
        }
        defender.poison(type);
    }
References com.runehive.game.world.entity.mob.Mob.isNpc(), com.runehive.game.world.entity.mob.Mob.isPoisoned(), and com.runehive.game.world.entity.mob.Mob.poison().
Referenced by smokeBarrage(), and smokeBurst().
shadowBarrage()
void com.runehive.game.world.entity.combat.magic.MagicImpact.shadowBarrage (Mob attacker, Mob defender, Mob other, List< Hit > extra) static private
Definition at line 200 of file MagicImpact.java.
{
        lowerSkill(defender, Skill.ATTACK, 15);
        CombatHit next = hitEvent(attacker, defender, other, 28, extra);
        if (next != null && next.isAccurate()) {
            lowerSkill(other, Skill.ATTACK, 15);
        }
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, hitEvent(), com.runehive.game.world.entity.combat.hit.Hit.isAccurate(), and lowerSkill().
shadowBurst()
void com.runehive.game.world.entity.combat.magic.MagicImpact.shadowBurst (Mob attacker, Mob defender, Mob other, List< Hit > extra) static private
Definition at line 192 of file MagicImpact.java.
{
        lowerSkill(defender, Skill.ATTACK, 10);
        CombatHit next = hitEvent(attacker, defender, other, 19, extra);
        if (next != null && next.isAccurate()) {
            lowerSkill(other, Skill.ATTACK, 10);
        }
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, hitEvent(), com.runehive.game.world.entity.combat.hit.Hit.isAccurate(), and lowerSkill().
smokeBarrage()
void com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBarrage (Mob attacker, Mob defender, Mob other, Hit hit, List< Hit > extra) static private
Definition at line 184 of file MagicImpact.java.
{
        poison(attacker, defender, hit, PoisonType.SUPER_MAGIC);
        CombatHit next = hitEvent(attacker, defender, other, 27, extra);
        if (next != null && (attacker.isNpc() || (next.isAccurate() && next.getDamage() > 0))) {
            poison(attacker, other, hit, PoisonType.SUPER_MAGIC);
        }
    }
References com.runehive.game.world.entity.combat.hit.Hit.getDamage(), hitEvent(), com.runehive.game.world.entity.combat.hit.Hit.isAccurate(), com.runehive.game.world.entity.mob.Mob.isNpc(), poison(), and com.runehive.game.world.entity.combat.PoisonType.SUPER_MAGIC.
smokeBurst()
void com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBurst (Mob attacker, Mob defender, Mob other, Hit hit, List< Hit > extra) static private
Definition at line 176 of file MagicImpact.java.
{
        poison(attacker, defender, hit, PoisonType.DEFAULT_MAGIC);
        CombatHit next = hitEvent(attacker, defender, other, 18, extra);
        if (next != null && (attacker.isNpc() || (next.isAccurate() && next.getDamage() > 0))) {
            poison(attacker, other, hit, PoisonType.DEFAULT_MAGIC);
        }
    }
References com.runehive.game.world.entity.combat.PoisonType.DEFAULT_MAGIC, com.runehive.game.world.entity.combat.hit.Hit.getDamage(), hitEvent(), com.runehive.game.world.entity.combat.hit.Hit.isAccurate(), com.runehive.game.world.entity.mob.Mob.isNpc(), and poison().
teleblock()
void com.runehive.game.world.entity.combat.magic.MagicImpact.teleblock (Mob defender) static private
Definition at line 240 of file MagicImpact.java.
{
        if (defender.isPlayer()) {
            CombatUtil.effect(defender, CombatEffectType.TELEBLOCK);
        }
    }
References com.runehive.game.world.entity.combat.CombatUtil.effect(), com.runehive.game.world.entity.mob.Mob.isPlayer(), and com.runehive.game.world.entity.combat.effect.CombatEffectType.TELEBLOCK.
Member Data Documentation
AHRIM_BLAST
com.runehive.game.world.entity.combat.magic.MagicImpact.AHRIM_BLAST
Initial value:
=((attacker, defender, hit, extra) -> {
    })
Definition at line 81 of file MagicImpact.java.
BIND
com.runehive.game.world.entity.combat.magic.MagicImpact.BIND =((attacker, defender, hit, extra) -> freeze(defender, 5))
Definition at line 24 of file MagicImpact.java.
BLOOD_BARRAGE
com.runehive.game.world.entity.combat.magic.MagicImpact.BLOOD_BARRAGE =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> bloodBarrage(attacker, defender, other, hit, extra)))
Definition at line 65 of file MagicImpact.java.
BLOOD_BLITZ
com.runehive.game.world.entity.combat.magic.MagicImpact.BLOOD_BLITZ =((attacker, defender, hit, extra) -> heal(attacker, hit))
Definition at line 64 of file MagicImpact.java.
BLOOD_BURST
com.runehive.game.world.entity.combat.magic.MagicImpact.BLOOD_BURST =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> bloodBurst(attacker, defender, other, hit, extra)))
Definition at line 63 of file MagicImpact.java.
BLOOD_RUSH
com.runehive.game.world.entity.combat.magic.MagicImpact.BLOOD_RUSH =((attacker, defender, hit, extra) -> heal(attacker, hit))
Definition at line 62 of file MagicImpact.java.
CONFUSE
com.runehive.game.world.entity.combat.magic.MagicImpact.CONFUSE =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.ATTACK, 5))
Definition at line 28 of file MagicImpact.java.
CURSE
com.runehive.game.world.entity.combat.magic.MagicImpact.CURSE =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.DEFENCE, 5))
Definition at line 30 of file MagicImpact.java.
effect
final CombatImpact com.runehive.game.world.entity.combat.magic.MagicImpact.effect private
Definition at line 83 of file MagicImpact.java.
Referenced by getEffect(), and MagicImpact().
ENFEEBLE
com.runehive.game.world.entity.combat.magic.MagicImpact.ENFEEBLE =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.STRENGTH, 10))
Definition at line 33 of file MagicImpact.java.
ENTANGLE
com.runehive.game.world.entity.combat.magic.MagicImpact.ENTANGLE =(((attacker, defender, hit, extra) -> freeze(defender, 15)))
Definition at line 26 of file MagicImpact.java.
ICE_BARRAGE
com.runehive.game.world.entity.combat.magic.MagicImpact.ICE_BARRAGE =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> iceBarrage(attacker, defender, other, extra)))
Definition at line 70 of file MagicImpact.java.
ICE_BLITZ
com.runehive.game.world.entity.combat.magic.MagicImpact.ICE_BLITZ =((attacker, defender, hit, extra) -> freeze(defender, 15))
Definition at line 69 of file MagicImpact.java.
ICE_BURST
com.runehive.game.world.entity.combat.magic.MagicImpact.ICE_BURST =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> iceBurst(attacker, defender, other, extra)))
Definition at line 68 of file MagicImpact.java.
ICE_RUSH
com.runehive.game.world.entity.combat.magic.MagicImpact.ICE_RUSH =((attacker, defender, hit, extra) -> freeze(defender, 5))
Definition at line 67 of file MagicImpact.java.
KBD_FREEZE
com.runehive.game.world.entity.combat.magic.MagicImpact.KBD_FREEZE =((attacker, defender, hit, extra) -> freeze(defender, 5))
Definition at line 72 of file MagicImpact.java.
KBD_POISON
com.runehive.game.world.entity.combat.magic.MagicImpact.KBD_POISON =((attacker, defender, hit, extra) -> poison(attacker, defender, hit, PoisonType.DEFAULT_NPC))
Definition at line 73 of file MagicImpact.java.
KBD_SHOCK
com.runehive.game.world.entity.combat.magic.MagicImpact.KBD_SHOCK =((attacker, defender, hit, extra) -> kbdShock(defender))
Definition at line 74 of file MagicImpact.java.
MAGIC_DART
com.runehive.game.world.entity.combat.magic.MagicImpact.MAGIC_DART
Initial value:
=((attacker, defender, hit, extra) -> {
        if (attacker.isPlayer() && hit.isAccurate()) {
            Player player = attacker.getPlayer();
            int damage = 10 + player.skills.getLevel(Skill.MAGIC) / 10;
            if (defender.isNpc() && player.slayer.getTask() != null) {
                Npc mob = defender.getNpc();
                if (player.slayer.getTask().valid(mob.getName())) {
                    damage = 13 + player.skills.getLevel(Skill.MAGIC) / 6;
                }
            }
            hit.setDamage(RandomUtils.inclusive(damage));
        }
    })
Definition at line 36 of file MagicImpact.java.
SHADOW_BARRAGE
com.runehive.game.world.entity.combat.magic.MagicImpact.SHADOW_BARRAGE =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> shadowBarrage(attacker, defender, other, extra)))
Definition at line 60 of file MagicImpact.java.
SHADOW_BLITZ
com.runehive.game.world.entity.combat.magic.MagicImpact.SHADOW_BLITZ =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.ATTACK, 15))
Definition at line 59 of file MagicImpact.java.
SHADOW_BURST
com.runehive.game.world.entity.combat.magic.MagicImpact.SHADOW_BURST =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> shadowBurst(attacker, defender, other, extra)))
Definition at line 58 of file MagicImpact.java.
SHADOW_RUSH
com.runehive.game.world.entity.combat.magic.MagicImpact.SHADOW_RUSH =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.ATTACK, 10))
Definition at line 57 of file MagicImpact.java.
SMOKE_BARRAGE
com.runehive.game.world.entity.combat.magic.MagicImpact.SMOKE_BARRAGE =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> smokeBarrage(attacker, defender, other, hit, extra)))
Definition at line 55 of file MagicImpact.java.
SMOKE_BLITZ
com.runehive.game.world.entity.combat.magic.MagicImpact.SMOKE_BLITZ =((attacker, defender, hit, extra) -> poison(attacker, defender, hit, PoisonType.SUPER_MAGIC))
Definition at line 54 of file MagicImpact.java.
SMOKE_BURST
com.runehive.game.world.entity.combat.magic.MagicImpact.SMOKE_BURST =((attacker, defender, hit, extra) -> CombatUtil.areaAction(defender, other -> smokeBurst(attacker, defender, other, hit, extra)))
Definition at line 53 of file MagicImpact.java.
SMOKE_RUSH
com.runehive.game.world.entity.combat.magic.MagicImpact.SMOKE_RUSH =((attacker, defender, hit, extra) -> poison(attacker, defender, hit, PoisonType.DEFAULT_MAGIC))
Definition at line 52 of file MagicImpact.java.
SNARE
com.runehive.game.world.entity.combat.magic.MagicImpact.SNARE =(((attacker, defender, hit, extra) -> freeze(defender, 10)))
Definition at line 25 of file MagicImpact.java.
STUN
com.runehive.game.world.entity.combat.magic.MagicImpact.STUN =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.ATTACK, 10))
Definition at line 34 of file MagicImpact.java.
TELEBLOCK
com.runehive.game.world.entity.combat.magic.MagicImpact.TELEBLOCK =((attacker, defender, hit, extra) -> teleblock(defender))
Definition at line 22 of file MagicImpact.java.
VULNERABILITY
com.runehive.game.world.entity.combat.magic.MagicImpact.VULNERABILITY =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.DEFENCE, 10))
Definition at line 32 of file MagicImpact.java.
WEAKEN
com.runehive.game.world.entity.combat.magic.MagicImpact.WEAKEN =((attacker, defender, hit, extra) -> lowerSkill(defender, Skill.STRENGTH, 5))
Definition at line 29 of file MagicImpact.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/magic/MagicImpact.java