RuneHive-Game: com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData Enum Reference
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData Enum Reference
Public Member Functions
double getExperience ()
int getItem ()
int getPoints ()
OfferingData (int item, int points, int experience)
Constructs a new OfferingData.
Static Public Member Functions
static OfferingData forItem (int item)
Public Attributes
ANCIENT_SHARD =(19677, 1, 1350)
ENSOULED_ABYSSAL_HEAD =(13507, 1, 1000)
ENSOULED_ABYSSAL_HEAD_II =(13508, 1, 1000)
ENSOULED_AVIANSIE_HEAD =(13504, 1, 1000)
ENSOULED_AVIANSIE_HEAD_II =(13505, 1, 1000)
ENSOULED_BEAR_HEAD =(13462, 1, 1000)
ENSOULED_BEAR_HEAD_II =(13463, 1, 1000)
ENSOULED_BLOODVELD_HEAD =(13495, 1, 1000)
ENSOULED_BLOODVELD_HEAD_II =(13496, 1, 1000)
ENSOULED_CHAOS_DRUID_HEAD =(13471, 1, 1000)
ENSOULED_CHAOS_DRUID_HEAD_II =(13472, 1, 1000)
ENSOULED_DAGANNOTH_HEAD =(13492, 1, 1000)
ENSOULED_DAGANNOTH_HEAD_II =(13493, 1, 1000)
ENSOULED_DEMON_HEAD =(13501, 1, 1000)
ENSOULED_DEMON_HEAD_II =(13502, 1, 1000)
ENSOULED_DOG_HEAD =(13468, 1, 1000)
ENSOULED_DOG_HEAD_II =(13469, 1, 1000)
ENSOULED_DRAGON_HEAD =(13511, 1, 1000)
ENSOULED_DRAGON_HEAD_II =(13510, 1, 1000)
ENSOULED_ELF_HEAD =(13480, 1, 1000)
ENSOULED_ELF_HEAD_II =(13481, 1, 1000)
ENSOULED_GIANT_HEAD =(13474, 1, 1000)
ENSOULED_GIANT_HEAD_II =(13475, 1, 1000)
ENSOULED_GOBLIN_HEAD =(13447, 1, 1000)
ENSOULED_GOBLIN_HEAD_II =(13448, 1, 1000)
ENSOULED_HORROR_HEAD =(13486, 1, 1000)
ENSOULED_HORROR_HEAD_II =(13487, 1, 1000)
ENSOULED_IMP_HEAD =(13453, 1, 1000)
ENSOULED_IMP_HEAD_II =(13454, 1, 1000)
ENSOULED_KALPHITE_HEAD =(13489, 1, 1000)
ENSOULED_KALPHITE_HEAD_II =(13490, 1, 1000)
ENSOULED_MINOTAUR_HEAD =(13456, 1, 1000)
ENSOULED_MINOTAUR_HEAD_II =(13457, 1, 1000)
ENSOULED_MONKEY_HEAD =(13450, 1, 1000)
ENSOULED_MONKEY_HEAD_II =(13451, 1, 1000)
ENSOULED_OGRE_HEAD =(13477, 1, 1000)
ENSOULED_OGRE_HEAD_II =(13478, 1, 1000)
ENSOULED_SCORPION_HEAD =(13459, 1, 1000)
ENSOULED_SCORPION_HEAD_II =(13460, 1, 1000)
ENSOULED_TROLL_HEAD =(13483, 1, 1000)
ENSOULED_TROLL_HEAD_II =(13484, 1, 1000)
ENSOULED_TZHAAR_HEAD =(13498, 1, 1000)
ENSOULED_TZHAAR_HEAD_II =(13499, 1, 1000)
ENSOULED_UNICORN_HEAD =(13465, 1, 1000)
ENSOULED_UNICORN_HEAD_II =(13466, 1, 1000)
TOTEM =(19685, 1, 1350)
TOTEM_BASE =(19679, 1, 1350)
TOTEM_MIDDLE =(19681, 1, 1350)
TOTEM_TOP =(19683, 1, 1350)
Private Attributes
final int experience
final int item
final int points
Detailed Description
Definition at line 61 of file SlayerOfferings.java.
Constructor & Destructor Documentation
OfferingData()
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.OfferingData (int item, int points, int experience)
Constructs a new OfferingData.
Definition at line 117 of file SlayerOfferings.java.
{
            this.item = item;
            this.points = points;
            this.experience = experience;
        }
References experience, item, and points.
Referenced by forItem().
Member Function Documentation
forItem()
OfferingData com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.forItem (int item) static
Definition at line 135 of file SlayerOfferings.java.
{
            for (OfferingData offering : values()) {
                if (offering.getItem() == item)
                    return offering;
            }
            return null;
        }
References item, and OfferingData().
Referenced by com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), and com.runehive.content.skill.impl.slayer.SlayerOfferings.offer().
getExperience()
double com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.getExperience ()
Definition at line 131 of file SlayerOfferings.java.
{
            return experience;
        }
References experience.
Referenced by com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), and com.runehive.content.skill.impl.slayer.SlayerOfferings.offer().
getItem()
int com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.getItem ()
Definition at line 123 of file SlayerOfferings.java.
{
            return item;
        }
References item.
getPoints()
int com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.getPoints ()
Definition at line 127 of file SlayerOfferings.java.
{
            return points;
        }
References points.
Referenced by com.runehive.content.skill.impl.slayer.SlayerOfferings.confirm(), and com.runehive.content.skill.impl.slayer.SlayerOfferings.offer().
Member Data Documentation
ANCIENT_SHARD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ANCIENT_SHARD =(19677, 1, 1350)
Definition at line 62 of file SlayerOfferings.java.
ENSOULED_ABYSSAL_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_ABYSSAL_HEAD =(13507, 1, 1000)
Definition at line 107 of file SlayerOfferings.java.
ENSOULED_ABYSSAL_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_ABYSSAL_HEAD_II =(13508, 1, 1000)
Definition at line 108 of file SlayerOfferings.java.
ENSOULED_AVIANSIE_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_AVIANSIE_HEAD =(13504, 1, 1000)
Definition at line 105 of file SlayerOfferings.java.
ENSOULED_AVIANSIE_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_AVIANSIE_HEAD_II =(13505, 1, 1000)
Definition at line 106 of file SlayerOfferings.java.
ENSOULED_BEAR_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_BEAR_HEAD =(13462, 1, 1000)
Definition at line 77 of file SlayerOfferings.java.
ENSOULED_BEAR_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_BEAR_HEAD_II =(13463, 1, 1000)
Definition at line 78 of file SlayerOfferings.java.
ENSOULED_BLOODVELD_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_BLOODVELD_HEAD =(13495, 1, 1000)
Definition at line 99 of file SlayerOfferings.java.
ENSOULED_BLOODVELD_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_BLOODVELD_HEAD_II =(13496, 1, 1000)
Definition at line 100 of file SlayerOfferings.java.
ENSOULED_CHAOS_DRUID_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_CHAOS_DRUID_HEAD =(13471, 1, 1000)
Definition at line 83 of file SlayerOfferings.java.
ENSOULED_CHAOS_DRUID_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_CHAOS_DRUID_HEAD_II =(13472, 1, 1000)
Definition at line 84 of file SlayerOfferings.java.
ENSOULED_DAGANNOTH_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_DAGANNOTH_HEAD =(13492, 1, 1000)
Definition at line 97 of file SlayerOfferings.java.
ENSOULED_DAGANNOTH_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_DAGANNOTH_HEAD_II =(13493, 1, 1000)
Definition at line 98 of file SlayerOfferings.java.
ENSOULED_DEMON_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_DEMON_HEAD =(13501, 1, 1000)
Definition at line 103 of file SlayerOfferings.java.
ENSOULED_DEMON_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_DEMON_HEAD_II =(13502, 1, 1000)
Definition at line 104 of file SlayerOfferings.java.
ENSOULED_DOG_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_DOG_HEAD =(13468, 1, 1000)
Definition at line 81 of file SlayerOfferings.java.
ENSOULED_DOG_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_DOG_HEAD_II =(13469, 1, 1000)
Definition at line 82 of file SlayerOfferings.java.
ENSOULED_DRAGON_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_DRAGON_HEAD =(13511, 1, 1000)
Definition at line 109 of file SlayerOfferings.java.
ENSOULED_DRAGON_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_DRAGON_HEAD_II =(13510, 1, 1000)
Definition at line 110 of file SlayerOfferings.java.
ENSOULED_ELF_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_ELF_HEAD =(13480, 1, 1000)
Definition at line 89 of file SlayerOfferings.java.
ENSOULED_ELF_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_ELF_HEAD_II =(13481, 1, 1000)
Definition at line 90 of file SlayerOfferings.java.
ENSOULED_GIANT_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_GIANT_HEAD =(13474, 1, 1000)
Definition at line 85 of file SlayerOfferings.java.
ENSOULED_GIANT_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_GIANT_HEAD_II =(13475, 1, 1000)
Definition at line 86 of file SlayerOfferings.java.
ENSOULED_GOBLIN_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_GOBLIN_HEAD =(13447, 1, 1000)
Definition at line 67 of file SlayerOfferings.java.
ENSOULED_GOBLIN_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_GOBLIN_HEAD_II =(13448, 1, 1000)
Definition at line 68 of file SlayerOfferings.java.
ENSOULED_HORROR_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_HORROR_HEAD =(13486, 1, 1000)
Definition at line 93 of file SlayerOfferings.java.
ENSOULED_HORROR_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_HORROR_HEAD_II =(13487, 1, 1000)
Definition at line 94 of file SlayerOfferings.java.
ENSOULED_IMP_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_IMP_HEAD =(13453, 1, 1000)
Definition at line 71 of file SlayerOfferings.java.
ENSOULED_IMP_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_IMP_HEAD_II =(13454, 1, 1000)
Definition at line 72 of file SlayerOfferings.java.
ENSOULED_KALPHITE_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_KALPHITE_HEAD =(13489, 1, 1000)
Definition at line 95 of file SlayerOfferings.java.
ENSOULED_KALPHITE_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_KALPHITE_HEAD_II =(13490, 1, 1000)
Definition at line 96 of file SlayerOfferings.java.
ENSOULED_MINOTAUR_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_MINOTAUR_HEAD =(13456, 1, 1000)
Definition at line 73 of file SlayerOfferings.java.
ENSOULED_MINOTAUR_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_MINOTAUR_HEAD_II =(13457, 1, 1000)
Definition at line 74 of file SlayerOfferings.java.
ENSOULED_MONKEY_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_MONKEY_HEAD =(13450, 1, 1000)
Definition at line 69 of file SlayerOfferings.java.
ENSOULED_MONKEY_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_MONKEY_HEAD_II =(13451, 1, 1000)
Definition at line 70 of file SlayerOfferings.java.
ENSOULED_OGRE_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_OGRE_HEAD =(13477, 1, 1000)
Definition at line 87 of file SlayerOfferings.java.
ENSOULED_OGRE_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_OGRE_HEAD_II =(13478, 1, 1000)
Definition at line 88 of file SlayerOfferings.java.
ENSOULED_SCORPION_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_SCORPION_HEAD =(13459, 1, 1000)
Definition at line 75 of file SlayerOfferings.java.
ENSOULED_SCORPION_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_SCORPION_HEAD_II =(13460, 1, 1000)
Definition at line 76 of file SlayerOfferings.java.
ENSOULED_TROLL_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_TROLL_HEAD =(13483, 1, 1000)
Definition at line 91 of file SlayerOfferings.java.
ENSOULED_TROLL_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_TROLL_HEAD_II =(13484, 1, 1000)
Definition at line 92 of file SlayerOfferings.java.
ENSOULED_TZHAAR_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_TZHAAR_HEAD =(13498, 1, 1000)
Definition at line 101 of file SlayerOfferings.java.
ENSOULED_TZHAAR_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_TZHAAR_HEAD_II =(13499, 1, 1000)
Definition at line 102 of file SlayerOfferings.java.
ENSOULED_UNICORN_HEAD
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_UNICORN_HEAD =(13465, 1, 1000)
Definition at line 79 of file SlayerOfferings.java.
ENSOULED_UNICORN_HEAD_II
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.ENSOULED_UNICORN_HEAD_II =(13466, 1, 1000)
Definition at line 80 of file SlayerOfferings.java.
experience
final int com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.experience private
Definition at line 114 of file SlayerOfferings.java.
Referenced by getExperience(), and OfferingData().
item
final int com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.item private
Definition at line 112 of file SlayerOfferings.java.
Referenced by forItem(), getItem(), and OfferingData().
points
final int com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.points private
Definition at line 113 of file SlayerOfferings.java.
Referenced by getPoints(), and OfferingData().
TOTEM
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.TOTEM =(19685, 1, 1350)
Definition at line 66 of file SlayerOfferings.java.
TOTEM_BASE
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.TOTEM_BASE =(19679, 1, 1350)
Definition at line 63 of file SlayerOfferings.java.
TOTEM_MIDDLE
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.TOTEM_MIDDLE =(19681, 1, 1350)
Definition at line 64 of file SlayerOfferings.java.
TOTEM_TOP
com.runehive.content.skill.impl.slayer.SlayerOfferings.OfferingData.TOTEM_TOP =(19683, 1, 1350)
Definition at line 65 of file SlayerOfferings.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/slayer/SlayerOfferings.java