RuneHive-Game: com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData Enum Reference
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData Enum Reference
Holds the recipe for disaster activity data.
Public Member Functions
RecipeForDisasterData getNext ()
RecipeForDisasterData (int npc, int gloves)
Public Attributes
AGRITH_NA_NA =(4880, 1)
CULINAROMANCER =(4878, 10)
DESSOURT =(4883, 8)
FLAMBEED =(4881, 3)
GELATINNOTH_MOTHER =(4884, 9)
final int gloves
KARAMEL =(4882, 6)
final int npc
Detailed Description
Holds the recipe for disaster activity data.
Author
Daniel
Definition at line 8 of file RecipeForDisasterData.java.
Constructor & Destructor Documentation
RecipeForDisasterData()
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.RecipeForDisasterData (int npc, int gloves)
Definition at line 19 of file RecipeForDisasterData.java.
{
        this.npc = npc;
        this.gloves = gloves;
    }
References gloves, and npc.
Referenced by getNext().
Member Function Documentation
getNext()
RecipeForDisasterData com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.getNext ()
Definition at line 24 of file RecipeForDisasterData.java.
{
        int index = ordinal() + 1;
        if (index >= values().length)
            return null;
        return values()[index];
    }
References RecipeForDisasterData().
Member Data Documentation
AGRITH_NA_NA
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.AGRITH_NA_NA =(4880, 1)
Definition at line 9 of file RecipeForDisasterData.java.
CULINAROMANCER
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.CULINAROMANCER =(4878, 10)
Definition at line 14 of file RecipeForDisasterData.java.
Referenced by com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.finish().
DESSOURT
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.DESSOURT =(4883, 8)
Definition at line 12 of file RecipeForDisasterData.java.
FLAMBEED
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.FLAMBEED =(4881, 3)
Definition at line 10 of file RecipeForDisasterData.java.
GELATINNOTH_MOTHER
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.GELATINNOTH_MOTHER =(4884, 9)
Definition at line 13 of file RecipeForDisasterData.java.
gloves
final int com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.gloves
Definition at line 17 of file RecipeForDisasterData.java.
Referenced by RecipeForDisasterData().
KARAMEL
com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.KARAMEL =(4882, 6)
Definition at line 11 of file RecipeForDisasterData.java.
npc
final int com.runehive.content.activity.impl.recipefordisaster.RecipeForDisasterData.npc
Definition at line 16 of file RecipeForDisasterData.java.
Referenced by RecipeForDisasterData().
The documentation for this enum was generated from the following file:
java/com/runehive/content/activity/impl/recipefordisaster/RecipeForDisasterData.java