RuneHive-Game: com.runehive.content.store.currency.CurrencyType Enum Reference
com.runehive.content.store.currency.CurrencyType Enum Reference
The enumerated type whom holds all the currencies usable for a server.
Public Member Functions
CurrencyType (int id, Currency currency)
int getId ()
String toString ()
Static Public Member Functions
static String getValue (Player player, CurrencyType currency)
static boolean isCurrency (int id)
static Optional< CurrencyType > lookup (int id)
Public Attributes
BLOOD_MONEY =(2, new ItemCurrency(13307))
CLAN_POINTS =(6, new ClanPointCurrency())
COINS =(0, new ItemCurrency(995))
final Currency currency
DONATOR_POINTS =(11, new DonatorPointCurrency())
GRACEFUL_TOKEN =(10, new ItemCurrency(11849))
final int id
KOLODION_POINTS =(9, new MageArenaCurrency())
LMS_POINTS =(6, new LMSPointCurrency())
PARAMAYA_TICKET =(15, new ItemCurrency(620))
PEST_POINTS =(5, new PestPointCurrency())
PLATINUM_TOKEN =(13, new ItemCurrency(13204))
PRESTIGE_POINTS =(8, new PrestigePointCurrency())
ROYALE_TOKEN =(14, new ItemCurrency(20527))
SKILLING_POINTS =(12, new SkillingPointCurrency())
SLAYER_POINTS =(4, new SlayerPointCurrency())
STARDUST =(6, new ItemCurrency(25527))
TOKKUL =(1, new ItemCurrency(6529))
VOTE_POINTS =(7, new VotePointCurrency())
Static Private Attributes
static final ImmutableSet< CurrencyType > VALUES = ImmutableSet.copyOf(values())
Detailed Description
The enumerated type whom holds all the currencies usable for a server.
Author
Stand Up
Since
4-1-2017.
Definition at line 17 of file CurrencyType.java.
Constructor & Destructor Documentation
CurrencyType()
com.runehive.content.store.currency.CurrencyType.CurrencyType (int id, Currency currency)
Definition at line 42 of file CurrencyType.java.
{
        this.id = id;
        this.currency = currency;
    }
References currency, and id.
Referenced by getValue().
Member Function Documentation
getId()
int com.runehive.content.store.currency.CurrencyType.getId ()
Definition at line 52 of file CurrencyType.java.
                       {
        return id;
    }
References id.
Referenced by com.runehive.content.store.impl.DefaultStore.refresh().
getValue()
String com.runehive.content.store.currency.CurrencyType.getValue (Player player, CurrencyType currency) static
Definition at line 60 of file CurrencyType.java.
{
        String value = "";
        switch (currency) {
            case COINS:
                value = "Coins: " + Utility.formatDigits(player.inventory.contains(995) ? player.inventory.computeAmountForId(995) : 0);
                break;
            case TOKKUL:
                value = "Tokkuls: " + Utility.formatDigits(player.inventory.contains(6529) ? player.inventory.computeAmountForId(6529) : 0);
                break;
            case GRACEFUL_TOKEN:
                value = "Tokens: " + Utility.formatDigits(player.inventory.contains(11849) ? player.inventory.computeAmountForId(11849) : 0);
                break;
            case KOLODION_POINTS:
                value = "Points: " + Utility.formatDigits(player.mageArenaPoints);
                break;
            case BLOOD_MONEY:
                value = "BM: " + Utility.formatDigits(player.inventory.contains(13307) ? player.inventory.computeAmountForId(13307) : 0);
                break;
            case PLATINUM_TOKEN:
                value = "Platinum Token: " + Utility.formatDigits(player.inventory.contains(13204) ? player.inventory.computeAmountForId(13204) : 0);
                break;
            case ROYALE_TOKEN:
                value = "Royale Token: " + Utility.formatDigits(player.inventory.contains(20527) ? player.inventory.computeAmountForId(20527) : 0);
                break;
            case SLAYER_POINTS:
                value = "Points: " + Utility.formatDigits(player.slayer.getPoints());
                break;
            case VOTE_POINTS:
                value = "Points: " + Utility.formatDigits(player.votePoints);
                break;
            case PEST_POINTS:
                value = "Points: " + Utility.formatDigits(player.pestPoints);
                break;
            case LMS_POINTS:
                value = "Points: " + Utility.formatDigits(player.lmsPoints);
                break;
            case PRESTIGE_POINTS:
                value = "Points: " + Utility.formatDigits(player.prestige.getPrestigePoint());
                break;
            case DONATOR_POINTS:
                value = "Credits: " + Utility.formatDigits(player.donation.getCredits());
                break;
            case SKILLING_POINTS:
                value = "Points: " + Utility.formatDigits(player.skillingPoints);
                break;
            case STARDUST:
                value = "Stardust: " + Utility.formatDigits(player.inventory.contains(25527) ? player.inventory.computeAmountForId(25527) : 0);
                break;
            case CLAN_POINTS:
                if (player.clanChannel == null) {
                    value = "0";
                } else {
                    value = "CP: " + Utility.formatDigits(player.clanChannel.getDetails().points);
                }
                break;
        }
        return value;
    }
References BLOOD_MONEY, CLAN_POINTS, com.runehive.game.world.entity.mob.player.Player.clanChannel, COINS, com.runehive.game.world.items.containers.ItemContainer.computeAmountForId(), com.runehive.game.world.items.containers.ItemContainer.contains(), currency, CurrencyType(), com.runehive.game.world.entity.mob.player.Player.donation, DONATOR_POINTS, com.runehive.util.Utility.formatDigits(), com.runehive.content.donators.Donation.getCredits(), com.runehive.content.clanchannel.channel.ClanChannel.getDetails(), com.runehive.content.skill.impl.slayer.Slayer.getPoints(), com.runehive.content.prestige.Prestige.getPrestigePoint(), GRACEFUL_TOKEN, com.runehive.game.world.entity.mob.player.Player.inventory, KOLODION_POINTS, LMS_POINTS, com.runehive.game.world.entity.mob.player.Player.lmsPoints, com.runehive.game.world.entity.mob.player.Player.mageArenaPoints, PEST_POINTS, com.runehive.game.world.entity.mob.player.Player.pestPoints, PLATINUM_TOKEN, com.runehive.content.clanchannel.channel.ClanDetails.points, com.runehive.game.world.entity.mob.player.Player.prestige, PRESTIGE_POINTS, ROYALE_TOKEN, SKILLING_POINTS, com.runehive.game.world.entity.mob.player.Player.skillingPoints, com.runehive.game.world.entity.mob.player.Player.slayer, SLAYER_POINTS, STARDUST, TOKKUL, VOTE_POINTS, and com.runehive.game.world.entity.mob.player.Player.votePoints.
Referenced by com.runehive.content.store.impl.RecipeForDisasterStore.open(), com.runehive.content.store.impl.SkillcapeStore.open(), com.runehive.content.store.impl.DefaultStore.refresh(), com.runehive.content.store.impl.RecipeForDisasterStore.refresh(), and com.runehive.content.store.impl.SkillcapeStore.refresh().
isCurrency()
boolean com.runehive.content.store.currency.CurrencyType.isCurrency (int id) static
Definition at line 56 of file CurrencyType.java.
{
        return VALUES.stream().filter(i -> i.currency.tangible()).anyMatch(i -> ((ItemCurrency) i.currency).itemId == id);
    }
References VALUES.
Referenced by com.runehive.content.store.impl.PersonalStore.add(), com.runehive.content.store.Store.sell(), and com.runehive.content.store.Store.sendSellValue().
lookup()
Optional< CurrencyType > com.runehive.content.store.currency.CurrencyType.lookup (int id) static
Definition at line 48 of file CurrencyType.java.
{
        return Arrays.stream(values()).filter(it -> it.getId() == id).findFirst();
    }
toString()
String com.runehive.content.store.currency.CurrencyType.toString ()
Definition at line 120 of file CurrencyType.java.
{
        return name().toLowerCase().replace("_", " ");
    }
Referenced by com.runehive.content.store.Store.sendPurchaseValue().
Member Data Documentation
BLOOD_MONEY
com.runehive.content.store.currency.CurrencyType.BLOOD_MONEY =(2, new ItemCurrency(13307))
Definition at line 20 of file CurrencyType.java.
Referenced by getValue().
CLAN_POINTS
com.runehive.content.store.currency.CurrencyType.CLAN_POINTS =(6, new ClanPointCurrency())
Definition at line 24 of file CurrencyType.java.
Referenced by getValue().
COINS
com.runehive.content.store.currency.CurrencyType.COINS =(0, new ItemCurrency(995))
Definition at line 18 of file CurrencyType.java.
Referenced by com.runehive.content.emote.Skillcape.getItems(), getValue(), com.runehive.content.store.impl.PersonalStore.myShop(), com.runehive.content.store.impl.RecipeForDisasterStore.RecipeForDisasterStore(), and com.runehive.content.store.StoreItem.StoreItem().
currency
final Currency com.runehive.content.store.currency.CurrencyType.currency
Definition at line 38 of file CurrencyType.java.
Referenced by CurrencyType(), and getValue().
DONATOR_POINTS
com.runehive.content.store.currency.CurrencyType.DONATOR_POINTS =(11, new DonatorPointCurrency())
Definition at line 30 of file CurrencyType.java.
Referenced by getValue().
GRACEFUL_TOKEN
com.runehive.content.store.currency.CurrencyType.GRACEFUL_TOKEN =(10, new ItemCurrency(11849))
Definition at line 29 of file CurrencyType.java.
Referenced by getValue().
id
final int com.runehive.content.store.currency.CurrencyType.id
Definition at line 40 of file CurrencyType.java.
Referenced by CurrencyType(), and getId().
KOLODION_POINTS
com.runehive.content.store.currency.CurrencyType.KOLODION_POINTS =(9, new MageArenaCurrency())
Definition at line 28 of file CurrencyType.java.
Referenced by getValue().
LMS_POINTS
com.runehive.content.store.currency.CurrencyType.LMS_POINTS =(6, new LMSPointCurrency())
Definition at line 25 of file CurrencyType.java.
Referenced by getValue().
PARAMAYA_TICKET
com.runehive.content.store.currency.CurrencyType.PARAMAYA_TICKET =(15, new ItemCurrency(620))
Definition at line 34 of file CurrencyType.java.
PEST_POINTS
com.runehive.content.store.currency.CurrencyType.PEST_POINTS =(5, new PestPointCurrency())
Definition at line 22 of file CurrencyType.java.
Referenced by getValue().
PLATINUM_TOKEN
com.runehive.content.store.currency.CurrencyType.PLATINUM_TOKEN =(13, new ItemCurrency(13204))
Definition at line 32 of file CurrencyType.java.
Referenced by getValue().
PRESTIGE_POINTS
com.runehive.content.store.currency.CurrencyType.PRESTIGE_POINTS =(8, new PrestigePointCurrency())
Definition at line 27 of file CurrencyType.java.
Referenced by getValue().
ROYALE_TOKEN
com.runehive.content.store.currency.CurrencyType.ROYALE_TOKEN =(14, new ItemCurrency(20527))
Definition at line 33 of file CurrencyType.java.
Referenced by getValue().
SKILLING_POINTS
com.runehive.content.store.currency.CurrencyType.SKILLING_POINTS =(12, new SkillingPointCurrency())
Definition at line 31 of file CurrencyType.java.
Referenced by getValue().
SLAYER_POINTS
com.runehive.content.store.currency.CurrencyType.SLAYER_POINTS =(4, new SlayerPointCurrency())
Definition at line 21 of file CurrencyType.java.
Referenced by getValue().
STARDUST
com.runehive.content.store.currency.CurrencyType.STARDUST =(6, new ItemCurrency(25527))
Definition at line 23 of file CurrencyType.java.
Referenced by getValue().
TOKKUL
com.runehive.content.store.currency.CurrencyType.TOKKUL =(1, new ItemCurrency(6529))
Definition at line 19 of file CurrencyType.java.
Referenced by getValue().
VALUES
final ImmutableSet<CurrencyType> com.runehive.content.store.currency.CurrencyType.VALUES = ImmutableSet.copyOf(values()) static private
Definition at line 36 of file CurrencyType.java.
Referenced by isCurrency().
VOTE_POINTS
com.runehive.content.store.currency.CurrencyType.VOTE_POINTS =(7, new VotePointCurrency())
Definition at line 26 of file CurrencyType.java.
Referenced by getValue().
The documentation for this enum was generated from the following file:
java/com/runehive/content/store/currency/CurrencyType.java