RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData Enum Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData Enum Reference
Public Member Functions
SpawnData (String location, Position position)
Static Public Member Functions
static SpawnData generate ()
Public Attributes
LEVEL_19 =("lvl 15 wild west dark warrior's fortress", new Position(2988, 3636, 0))
LEVEL_28 =("lvl 19 wild near wilderness ruins", new Position(2964, 3670, 0))
LEVEL_41 =("lvl 10 wild south of dark Warriors", new Position(3016, 3591, 0))
LEVEL_52 =("North of edgeville in the wilderness", new Position(3100, 3528, 0))
LEVEL_53 =("lvl 19 wild west of graveyard of shadows", new Position(3138, 3670, 0))
final String location
final Position position
Detailed Description
Definition at line 41 of file PorazdirUtility.java.
Constructor & Destructor Documentation
SpawnData()
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.SpawnData (String location, Position position)
Definition at line 51 of file PorazdirUtility.java.
{
            this.location = location;
            this.position = position;
        }
References location, and position.
Referenced by generate().
Member Function Documentation
generate()
SpawnData com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.generate () static
Definition at line 56 of file PorazdirUtility.java.
{
            return Utility.randomElement(values());
        }
References com.runehive.util.Utility.randomElement(), and SpawnData().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.generatePorazdirSpawn().
Member Data Documentation
LEVEL_19
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.LEVEL_19 =("lvl 15 wild west dark warrior's fortress", new Position(2988, 3636, 0))
Definition at line 42 of file PorazdirUtility.java.
LEVEL_28
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.LEVEL_28 =("lvl 19 wild near wilderness ruins", new Position(2964, 3670, 0))
Definition at line 43 of file PorazdirUtility.java.
LEVEL_41
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.LEVEL_41 =("lvl 10 wild south of dark Warriors", new Position(3016, 3591, 0))
Definition at line 44 of file PorazdirUtility.java.
LEVEL_52
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.LEVEL_52 =("North of edgeville in the wilderness", new Position(3100, 3528, 0))
Definition at line 45 of file PorazdirUtility.java.
LEVEL_53
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.LEVEL_53 =("lvl 19 wild west of graveyard of shadows", new Position(3138, 3670, 0))
Definition at line 46 of file PorazdirUtility.java.
location
final String com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.location
Definition at line 48 of file PorazdirUtility.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.generatePorazdirSpawn(), and SpawnData().
position
final Position com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.SpawnData.position
Definition at line 49 of file PorazdirUtility.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.generatePorazdirSpawn(), and SpawnData().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/magearena/PorazdirUtility.java