RuneHive-Game: com.runehive.content.skillcape.SkillCape Enum Reference
com.runehive.content.skillcape.SkillCape Enum Reference
Public Member Functions
String getDescription ()
SkillCape (int itemId, String description)
Static Public Member Functions
static boolean isEquipped (Player player, SkillCape cape)
Public Attributes
AGILITY =(9771, "Increased run energy restore rate.")
ATTACK =(9747, "Free access to Cyclops area found upstairs within the Warriors' Guild.")
COOKING =(9801, "Impossible to burn any food.")
CRAFTING =(9780, "Provides a chance to save materials.")
DEFENCE =(9753, "Act as a permanent Ring of Life.")
FARMING =(9810, "5% increased yield from herb patches.")
FIREMAKING =(9804, "Provides a chance to save a log.")
FLETCHING =(9783, "Provides a chance to save materials.")
HERBLORE =(9774, "Provides a chance to save ingredients.")
HITPOINTS =(9768, "2x HP restore rate.")
MAGIC =(9762, "Can cast spellbook swap 5 times per day.")
MINING =(9792, "Provides a chance to receive double materials.")
PRAYER =(9759, "Provides double experience when training Prayer.")
RANGED =(9756, "Act as an Ava's accumulator.")
SLAYER =(9786, "Can cancel up to 2 tasks per day.")
SMITHING =(9795, "Increases speed at which you smelt bars/forge items.")
THIEVING =(9777, "Better chance of succeeding when stealing from stalls.")
WOODCUTTING =(9807, "Provides a chance to receive double materials.")
Private Member Functions
int getItemId ()
Private Attributes
final String description
final int itemId
Detailed Description
Definition at line 6 of file SkillCape.java.
Constructor & Destructor Documentation
SkillCape()
com.runehive.content.skillcape.SkillCape.SkillCape (int itemId, String description)
Definition at line 29 of file SkillCape.java.
{
        this.itemId = itemId;
        this.description = description;
    }
References description, and itemId.
Referenced by isEquipped().
Member Function Documentation
getDescription()
String com.runehive.content.skillcape.SkillCape.getDescription ()
Definition at line 52 of file SkillCape.java.
{
        return description;
    }
References description.
getItemId()
int com.runehive.content.skillcape.SkillCape.getItemId () private
Definition at line 48 of file SkillCape.java.
{
        return itemId;
    }
References itemId.
Referenced by isEquipped().
isEquipped()
boolean com.runehive.content.skillcape.SkillCape.isEquipped (Player player, SkillCape cape) static
Definition at line 34 of file SkillCape.java.
{
        final Item currentCape = player.equipment.getCape();
        if (currentCape == null) {
            return false;
        }
        // Max cape gives all perks.
        if (currentCape.getId() == 13280) {
            return true;
        }
        return currentCape.getId() == cape.getItemId() || currentCape.getId() == cape.getItemId() + 1;
    }
References com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.equipment.Equipment.getCape(), com.runehive.game.world.items.Item.getId(), getItemId(), and SkillCape().
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.activity.impl.warriorguild.WarriorGuild.clickObject(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), com.runehive.content.skill.impl.crafting.Crafting.craft(), com.runehive.content.skill.impl.farming.patches.HarvestablePatch.createHarvestAction(), com.runehive.game.action.impl.BuryBoneAction.experience(), com.runehive.game.action.impl.ScatterAshAction.experience(), com.runehive.content.skill.impl.fletching.Fletching.fletch(), com.runehive.game.world.items.containers.equipment.Equipment.hasAccumulator(), com.runehive.game.world.items.containers.equipment.Equipment.hasAttractor(), com.runehive.content.skill.impl.mining.MiningAction.mine(), com.runehive.content.skill.impl.herblore.Herblore.mix(), com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct(), com.runehive.game.world.entity.mob.player.PlayerAssistant.runRestore(), com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice(), com.runehive.game.world.entity.mob.player.PlayerAssistant.skillRestore(), com.runehive.content.skill.impl.smithing.Smelting.Smelting(), com.runehive.content.skill.impl.smithing.SmithingArmour.SmithingArmour(), and com.runehive.content.skill.impl.cooking.Cooking.success().
Member Data Documentation
AGILITY
com.runehive.content.skillcape.SkillCape.AGILITY =(9771, "Increased run energy restore rate.")
Definition at line 13 of file SkillCape.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.runRestore().
ATTACK
com.runehive.content.skillcape.SkillCape.ATTACK =(9747, "Free access to Cyclops area found upstairs within the Warriors' Guild.")
Definition at line 7 of file SkillCape.java.
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuild.clickObject().
COOKING
com.runehive.content.skillcape.SkillCape.COOKING =(9801, "Impossible to burn any food.")
Definition at line 21 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.cooking.Cooking.success().
CRAFTING
com.runehive.content.skillcape.SkillCape.CRAFTING =(9780, "Provides a chance to save materials.")
Definition at line 16 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.craft().
DEFENCE
com.runehive.content.skillcape.SkillCape.DEFENCE =(9753, "Act as a permanent Ring of Life.")
Definition at line 8 of file SkillCape.java.
description
final String com.runehive.content.skillcape.SkillCape.description private
Definition at line 27 of file SkillCape.java.
Referenced by getDescription(), and SkillCape().
FARMING
com.runehive.content.skillcape.SkillCape.FARMING =(9810, "5% increased yield from herb patches.")
Definition at line 24 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.farming.patches.HarvestablePatch.createHarvestAction().
FIREMAKING
com.runehive.content.skillcape.SkillCape.FIREMAKING =(9804, "Provides a chance to save a log.")
Definition at line 22 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), and com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct().
FLETCHING
com.runehive.content.skillcape.SkillCape.FLETCHING =(9783, "Provides a chance to save materials.")
Definition at line 17 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch().
HERBLORE
com.runehive.content.skillcape.SkillCape.HERBLORE =(9774, "Provides a chance to save ingredients.")
Definition at line 14 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.herblore.Herblore.mix().
HITPOINTS
com.runehive.content.skillcape.SkillCape.HITPOINTS =(9768, "2x HP restore rate.")
Definition at line 12 of file SkillCape.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.skillRestore().
itemId
final int com.runehive.content.skillcape.SkillCape.itemId private
Definition at line 26 of file SkillCape.java.
Referenced by getItemId(), and SkillCape().
MAGIC
com.runehive.content.skillcape.SkillCape.MAGIC =(9762, "Can cast spellbook swap 5 times per day.")
Definition at line 11 of file SkillCape.java.
MINING
com.runehive.content.skillcape.SkillCape.MINING =(9792, "Provides a chance to receive double materials.")
Definition at line 19 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.mining.MiningAction.mine().
PRAYER
com.runehive.content.skillcape.SkillCape.PRAYER =(9759, "Provides double experience when training Prayer.")
Definition at line 10 of file SkillCape.java.
Referenced by com.runehive.game.action.impl.BuryBoneAction.experience(), com.runehive.game.action.impl.ScatterAshAction.experience(), and com.runehive.content.skill.impl.prayer.BoneSacrifice.sacrifice().
RANGED
com.runehive.content.skillcape.SkillCape.RANGED =(9756, "Act as an Ava's accumulator.")
Definition at line 9 of file SkillCape.java.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.hasAccumulator(), and com.runehive.game.world.items.containers.equipment.Equipment.hasAttractor().
SLAYER
com.runehive.content.skillcape.SkillCape.SLAYER =(9786, "Can cancel up to 2 tasks per day.")
Definition at line 18 of file SkillCape.java.
SMITHING
com.runehive.content.skillcape.SkillCape.SMITHING =(9795, "Increases speed at which you smelt bars/forge items.")
Definition at line 20 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.smithing.Smelting.Smelting(), and com.runehive.content.skill.impl.smithing.SmithingArmour.SmithingArmour().
THIEVING
com.runehive.content.skillcape.SkillCape.THIEVING =(9777, "Better chance of succeeding when stealing from stalls.")
Definition at line 15 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickObject().
WOODCUTTING
com.runehive.content.skillcape.SkillCape.WOODCUTTING =(9807, "Provides a chance to receive double materials.")
Definition at line 23 of file SkillCape.java.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skillcape/SkillCape.java