RuneHive-Game: com.runehive.game.world.entity.mob.npc.drop.NpcDropChance Enum Reference
com.runehive.game.world.entity.mob.npc.drop.NpcDropChance Enum Reference
The enumerated type whose elements represent a set of constants used to differ between NpcDrop rarities.
Public Member Functions
NpcDropChance (int tier, int weight)
Constructs a new NpcDropChance.
String toString ()
Public Attributes
ALWAYS =(1, 0)
COMMON =(2, 10)
RARE =(4, 250)
final int tier
The tier of this drop chance.
UNCOMMON =(3, 50)
VERY_RARE =(5, 500)
final int weight
The denominator which is the divisor of a nominator of 1.
Detailed Description
The enumerated type whose elements represent a set of constants used to differ between NpcDrop rarities.
Author
Stand Up
Since
29-1-2017.
Definition at line 11 of file NpcDropChance.java.
Constructor & Destructor Documentation
NpcDropChance()
com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.NpcDropChance (int tier, int weight)
Constructs a new NpcDropChance.
Definition at line 25 of file NpcDropChance.java.
{
        this.weight = weight;
        this.tier = tier;
    }
References tier, and weight.
Member Function Documentation
toString()
String com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.toString ()
Definition at line 31 of file NpcDropChance.java.
{
        return Utility.formatEnum(name());
    }
References com.runehive.util.Utility.formatEnum().
Referenced by com.runehive.content.DropDisplay.display().
Member Data Documentation
ALWAYS
com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.ALWAYS =(1, 0)
Definition at line 12 of file NpcDropChance.java.
Referenced by com.runehive.util.parser.impl.NpcDropParser.parse().
COMMON
com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.COMMON =(2, 10)
Definition at line 13 of file NpcDropChance.java.
Referenced by com.runehive.util.parser.impl.NpcDropParser.parse().
RARE
com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.RARE =(4, 250)
Definition at line 15 of file NpcDropChance.java.
Referenced by com.runehive.util.parser.impl.NpcDropParser.parse().
tier
final int com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.tier
The tier of this drop chance.
Definition at line 19 of file NpcDropChance.java.
Referenced by NpcDropChance().
UNCOMMON
com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.UNCOMMON =(3, 50)
Definition at line 14 of file NpcDropChance.java.
Referenced by com.runehive.util.parser.impl.NpcDropParser.parse().
VERY_RARE
com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.VERY_RARE =(5, 500)
Definition at line 16 of file NpcDropChance.java.
Referenced by com.runehive.util.parser.impl.NpcDropParser.parse().
weight
final int com.runehive.game.world.entity.mob.npc.drop.NpcDropChance.weight
The denominator which is the divisor of a nominator of 1.
Definition at line 22 of file NpcDropChance.java.
Referenced by NpcDropChance().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/npc/drop/NpcDropChance.java