RuneHive-Game: com.runehive.content.skill.impl.fletching.impl.Stringable Enum Reference
com.runehive.content.skill.impl.fletching.impl.Stringable Enum Reference
Public Member Functions
int getAnimation ()
FletchableItem[] getFletchableItems ()
int getGraphics ()
Item[] getIngredients ()
String getProductionMessage ()
Item getUse ()
Item getWith ()
Stringable (Item use, Item with, FletchableItem... items)
Static Public Member Functions
static void load ()
Public Attributes
ADAMANT_CROSSBOWS =(new Item(9438), new Item(9463), new FletchableItem(new Item(9183), 61, 41.0))
BRONZE_CROSSBOWS =(new Item(9438), new Item(9454), new FletchableItem(new Item(9174), 9, 6.0))
IRON_CROSSBOWS =(new Item(9438), new Item(9457), new FletchableItem(new Item(9177), 39, 22.0))
LONGBOWS =(new Item(1777), new Item(48), new FletchableItem(new Item(839), 10, 5.0))
MAGIC_LONGBOWBOWS =(new Item(1777), new Item(70), new FletchableItem(new Item(859), 85, 91.5))
MAGIC_SHORTBOWS =(new Item(1777), new Item(72), new FletchableItem(new Item(861), 80, 83.2))
MAPLE_LONGBOWBOWS =(new Item(1777), new Item(62), new FletchableItem(new Item(851), 55, 58.2))
MAPLE_SHORTBOWS =(new Item(1777), new Item(64), new FletchableItem(new Item(853), 50, 50.0))
MITHRIL_CROSSBOWS =(new Item(9438), new Item(9461), new FletchableItem(new Item(9181), 54, 32.0))
OAK_LONGBOWBOWS =(new Item(1777), new Item(56), new FletchableItem(new Item(845), 25, 25.0))
OAK_SHORTBOWS =(new Item(1777), new Item(54), new FletchableItem(new Item(843), 20, 16.5))
RUNITE_CROSSBOWS =(new Item(9438), new Item(9465), new FletchableItem(new Item(9185), 61, 41.0))
SHORTBOWS =(new Item(1777), new Item(50), new FletchableItem(new Item(841), 5, 5.0))
STEEL_CROSSBOWS =(new Item(9438), new Item(9459), new FletchableItem(new Item(9179), 46, 27.0))
WILLOW_LONGBOWBOWS =(new Item(1777), new Item(58), new FletchableItem(new Item(847), 40, 41.5))
WILLOW_SHORTBOWS =(new Item(1777), new Item(60), new FletchableItem(new Item(849), 35, 32.25))
YEW_LONGBOWBOWS =(new Item(1777), new Item(66), new FletchableItem(new Item(855), 70, 75.0))
YEW_SHORTBOWS =(new Item(1777), new Item(68), new FletchableItem(new Item(857), 65, 67.5))
Private Attributes
final FletchableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 8 of file Stringable.java.
Constructor & Destructor Documentation
Stringable()
com.runehive.content.skill.impl.fletching.impl.Stringable.Stringable (Item use, Item with, FletchableItem... items)
Definition at line 32 of file Stringable.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.fletching.impl.Stringable.getAnimation ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 45 of file Stringable.java.
{
        switch (this) {
        case SHORTBOWS:
            return 6678;
        case LONGBOWS:
            return 6684;
        case OAK_SHORTBOWS:
            return 6679;
        case OAK_LONGBOWBOWS:
            return 6685;
        case WILLOW_SHORTBOWS:
            return 6680;
        case WILLOW_LONGBOWBOWS:
            return 6686;
        case MAPLE_SHORTBOWS:
            return 6681;
        case MAPLE_LONGBOWBOWS:
            return 6687;
        case YEW_SHORTBOWS:
            return 6682;
        case YEW_LONGBOWBOWS:
            return 6688;
        case MAGIC_SHORTBOWS:
            return 6683;
        case MAGIC_LONGBOWBOWS:
            return 6689;
        case BRONZE_CROSSBOWS:
            return 9454;
        case STEEL_CROSSBOWS:
            return 9457;
        case IRON_CROSSBOWS:
            return 9459;
        case MITHRIL_CROSSBOWS:
            return 9461;
        case ADAMANT_CROSSBOWS:
            return 9463;
        case RUNITE_CROSSBOWS:
            return 9465;
        default:
            return 6678;
        }
    }
References ADAMANT_CROSSBOWS, BRONZE_CROSSBOWS, IRON_CROSSBOWS, LONGBOWS, MAGIC_LONGBOWBOWS, MAGIC_SHORTBOWS, MAPLE_LONGBOWBOWS, MAPLE_SHORTBOWS, MITHRIL_CROSSBOWS, OAK_LONGBOWBOWS, OAK_SHORTBOWS, RUNITE_CROSSBOWS, SHORTBOWS, STEEL_CROSSBOWS, WILLOW_LONGBOWBOWS, WILLOW_SHORTBOWS, YEW_LONGBOWBOWS, and YEW_SHORTBOWS.
getFletchableItems()
FletchableItem[] com.runehive.content.skill.impl.fletching.impl.Stringable.getFletchableItems ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 104 of file Stringable.java.
{
        return items;
    }
References items.
getGraphics()
int com.runehive.content.skill.impl.fletching.impl.Stringable.getGraphics ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 89 of file Stringable.java.
{
        return -1;
    }
getIngredients()
Item[] com.runehive.content.skill.impl.fletching.impl.Stringable.getIngredients ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 114 of file Stringable.java.
{
        return new Item[] { use, with };
    }
References use, and with.
getProductionMessage()
String com.runehive.content.skill.impl.fletching.impl.Stringable.getProductionMessage ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 109 of file Stringable.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.fletching.impl.Stringable.getUse ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 94 of file Stringable.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.fletching.impl.Stringable.getWith ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 99 of file Stringable.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.fletching.impl.Stringable.load () static
Definition at line 38 of file Stringable.java.
{
        for (Stringable featherable : values()) {
            Fletching.addFletchable(featherable);
        }
    }
References com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), and Stringable().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
ADAMANT_CROSSBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.ADAMANT_CROSSBOWS =(new Item(9438), new Item(9463), new FletchableItem(new Item(9183), 61, 41.0))
Definition at line 25 of file Stringable.java.
Referenced by getAnimation().
BRONZE_CROSSBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.BRONZE_CROSSBOWS =(new Item(9438), new Item(9454), new FletchableItem(new Item(9174), 9, 6.0))
Definition at line 21 of file Stringable.java.
Referenced by getAnimation().
IRON_CROSSBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.IRON_CROSSBOWS =(new Item(9438), new Item(9457), new FletchableItem(new Item(9177), 39, 22.0))
Definition at line 22 of file Stringable.java.
Referenced by getAnimation().
items
final FletchableItem [] com.runehive.content.skill.impl.fletching.impl.Stringable.items private
Definition at line 30 of file Stringable.java.
Referenced by getFletchableItems(), and Stringable().
LONGBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.LONGBOWS =(new Item(1777), new Item(48), new FletchableItem(new Item(839), 10, 5.0))
Definition at line 10 of file Stringable.java.
Referenced by getAnimation().
MAGIC_LONGBOWBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.MAGIC_LONGBOWBOWS =(new Item(1777), new Item(70), new FletchableItem(new Item(859), 85, 91.5))
Definition at line 20 of file Stringable.java.
Referenced by getAnimation().
MAGIC_SHORTBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.MAGIC_SHORTBOWS =(new Item(1777), new Item(72), new FletchableItem(new Item(861), 80, 83.2))
Definition at line 19 of file Stringable.java.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch(), and getAnimation().
MAPLE_LONGBOWBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.MAPLE_LONGBOWBOWS =(new Item(1777), new Item(62), new FletchableItem(new Item(851), 55, 58.2))
Definition at line 16 of file Stringable.java.
Referenced by getAnimation().
MAPLE_SHORTBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.MAPLE_SHORTBOWS =(new Item(1777), new Item(64), new FletchableItem(new Item(853), 50, 50.0))
Definition at line 15 of file Stringable.java.
Referenced by getAnimation().
MITHRIL_CROSSBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.MITHRIL_CROSSBOWS =(new Item(9438), new Item(9461), new FletchableItem(new Item(9181), 54, 32.0))
Definition at line 24 of file Stringable.java.
Referenced by getAnimation().
OAK_LONGBOWBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.OAK_LONGBOWBOWS =(new Item(1777), new Item(56), new FletchableItem(new Item(845), 25, 25.0))
Definition at line 12 of file Stringable.java.
Referenced by getAnimation().
OAK_SHORTBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.OAK_SHORTBOWS =(new Item(1777), new Item(54), new FletchableItem(new Item(843), 20, 16.5))
Definition at line 11 of file Stringable.java.
Referenced by getAnimation().
RUNITE_CROSSBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.RUNITE_CROSSBOWS =(new Item(9438), new Item(9465), new FletchableItem(new Item(9185), 61, 41.0))
Definition at line 26 of file Stringable.java.
Referenced by getAnimation().
SHORTBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.SHORTBOWS =(new Item(1777), new Item(50), new FletchableItem(new Item(841), 5, 5.0))
Definition at line 9 of file Stringable.java.
Referenced by getAnimation().
STEEL_CROSSBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.STEEL_CROSSBOWS =(new Item(9438), new Item(9459), new FletchableItem(new Item(9179), 46, 27.0))
Definition at line 23 of file Stringable.java.
Referenced by getAnimation().
use
final Item com.runehive.content.skill.impl.fletching.impl.Stringable.use private
Definition at line 28 of file Stringable.java.
Referenced by getIngredients(), getUse(), and Stringable().
WILLOW_LONGBOWBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.WILLOW_LONGBOWBOWS =(new Item(1777), new Item(58), new FletchableItem(new Item(847), 40, 41.5))
Definition at line 14 of file Stringable.java.
Referenced by getAnimation().
WILLOW_SHORTBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.WILLOW_SHORTBOWS =(new Item(1777), new Item(60), new FletchableItem(new Item(849), 35, 32.25))
Definition at line 13 of file Stringable.java.
Referenced by getAnimation().
with
final Item com.runehive.content.skill.impl.fletching.impl.Stringable.with private
Definition at line 29 of file Stringable.java.
Referenced by getIngredients(), getWith(), and Stringable().
YEW_LONGBOWBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.YEW_LONGBOWBOWS =(new Item(1777), new Item(66), new FletchableItem(new Item(855), 70, 75.0))
Definition at line 18 of file Stringable.java.
Referenced by getAnimation().
YEW_SHORTBOWS
com.runehive.content.skill.impl.fletching.impl.Stringable.YEW_SHORTBOWS =(new Item(1777), new Item(68), new FletchableItem(new Item(857), 65, 67.5))
Definition at line 17 of file Stringable.java.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch(), and getAnimation().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fletching/impl/Stringable.java