RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2 Enum Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2 Enum Reference
Public Member Functions
String getLocation ()
Position getPosition ()
Position getTsunami ()
SpawnData2 (String location, Position position, Position tsunami)
Static Public Member Functions
static SpawnData2 generate ()
Public Attributes
LEVEL_16 =("lvl 16 wild near Bone Yard", new Position(3273, 3648, 0), new Position(3267, 3654, 0))
LEVEL_41 =("lvl 19 wild near graveyard of shadows", new Position(3197, 3670, 0), new Position(3194, 3666, 0))
LEVEL_46 =("lvl 46 wild near Spider Hill", new Position(3135, 3888, 0), new Position(3132, 3881, 0))
LEVEL_47 =("lvl 47 wild near obelisk", new Position(3308, 3892, 0), new Position(3305, 3888, 0))
LEVEL_51 =("lvl 51 wild near Rogues Castle", new Position(3266, 3924, 0), new Position(3266, 3927, 0))
LEVEL_53 =("lvl 53 wild near scorpia's cave entrance", new Position(3211, 3944, 0), new Position(3208, 3940, 0))
final String location
final Position position
final Position tsunami
Detailed Description
Definition at line 58 of file JusticarUtility.java.
Constructor & Destructor Documentation
SpawnData2()
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.SpawnData2 (String location, Position position, Position tsunami)
Definition at line 70 of file JusticarUtility.java.
{
            this.location = location;
            this.position = position;
            this.tsunami = tsunami;
        }
References location, position, and tsunami.
Referenced by generate().
Member Function Documentation
generate()
SpawnData2 com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.generate () static
Definition at line 76 of file JusticarUtility.java.
{
            return Utility.randomElement(values());
        }
References com.runehive.util.Utility.randomElement(), and SpawnData2().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn().
getLocation()
String com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.getLocation ()
Definition at line 80 of file JusticarUtility.java.
{
            return location;
        }
References location.
getPosition()
Position com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.getPosition ()
Definition at line 84 of file JusticarUtility.java.
{
            return position;
        }
References position.
getTsunami()
Position com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.getTsunami ()
Definition at line 88 of file JusticarUtility.java.
{
            return tsunami;
        }
References tsunami.
Member Data Documentation
LEVEL_16
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.LEVEL_16 =("lvl 16 wild near Bone Yard", new Position(3273, 3648, 0), new Position(3267, 3654, 0))
Definition at line 60 of file JusticarUtility.java.
LEVEL_41
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.LEVEL_41 =("lvl 19 wild near graveyard of shadows", new Position(3197, 3670, 0), new Position(3194, 3666, 0))
Definition at line 62 of file JusticarUtility.java.
LEVEL_46
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.LEVEL_46 =("lvl 46 wild near Spider Hill", new Position(3135, 3888, 0), new Position(3132, 3881, 0))
Definition at line 59 of file JusticarUtility.java.
LEVEL_47
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.LEVEL_47 =("lvl 47 wild near obelisk", new Position(3308, 3892, 0), new Position(3305, 3888, 0))
Definition at line 63 of file JusticarUtility.java.
LEVEL_51
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.LEVEL_51 =("lvl 51 wild near Rogues Castle", new Position(3266, 3924, 0), new Position(3266, 3927, 0))
Definition at line 61 of file JusticarUtility.java.
LEVEL_53
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.LEVEL_53 =("lvl 53 wild near scorpia's cave entrance", new Position(3211, 3944, 0), new Position(3208, 3940, 0))
Definition at line 64 of file JusticarUtility.java.
location
final String com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.location
Definition at line 66 of file JusticarUtility.java.
Referenced by getLocation(), and SpawnData2().
position
final Position com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.position
Definition at line 67 of file JusticarUtility.java.
Referenced by getPosition(), and SpawnData2().
tsunami
final Position com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.SpawnData2.tsunami
Definition at line 68 of file JusticarUtility.java.
Referenced by getTsunami(), and SpawnData2().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/magearena/JusticarUtility.java