RuneHive-Game: com.runehive.content.activity.inferno.InfernoWaveData.WaveData Enum Reference
com.runehive.content.activity.inferno.InfernoWaveData.WaveData Enum Reference
Public Member Functions
int[] getMonster ()
WaveData (int... monster)
Static Public Member Functions
static WaveData getNext (int current)
static WaveData getOrdinal (int ordinal)
Public Attributes
WAVE_1 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_MEJRAH)
WAVE_10 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH)
WAVE_11 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH)
WAVE_12 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH)
WAVE_13 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_AK)
WAVE_14 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH, JAL_AK)
WAVE_15 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_AK, JAL_IMKOT)
WAVE_16 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_IMKOT)
WAVE_17 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB)
WAVE_18 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL)
WAVE_19 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH)
WAVE_2 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_MEJRAH, JAL_MEJRAH)
WAVE_20 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH)
WAVE_21 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK)
WAVE_22 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_MEJRAH)
WAVE_23 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH, JAL_AK)
WAVE_24 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_AK)
WAVE_25 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT)
WAVE_26 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_MEJRAH)
WAVE_27 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT)
WAVE_28 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_AK)
WAVE_29 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_IMKOT)
WAVE_3 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB)
WAVE_30 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH, JAL_AK)
WAVE_31 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_AK, JAL_IMKOT)
WAVE_32 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_IMKOT)
WAVE_33 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_XIL)
WAVE_34 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB)
WAVE_35 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK)
WAVE_36 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH)
WAVE_37 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH)
WAVE_38 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK)
WAVE_39 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_MEJRAH)
WAVE_4 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK)
WAVE_40 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK)
WAVE_41 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK)
WAVE_42 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT)
WAVE_43 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_MEJRAH)
WAVE_44 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT)
WAVE_45 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_AK)
WAVE_46 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_AK, JAL_IMKOT)
WAVE_47 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_IMKOT)
WAVE_48 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_IMKOT)
WAVE_49 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_IMKOT)
WAVE_5 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_MEJRAH)
WAVE_50 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL)
WAVE_51 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_XIL)
WAVE_52 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH)
WAVE_53 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_AK)
WAVE_54 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_XIL, JAL_AK)
WAVE_55 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_XIL)
WAVE_56 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_XIL)
WAVE_57 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_ZEK, JAL_IMKOT)
WAVE_58 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_IMKOT, JAL_XIL)
WAVE_59 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT, JAL_XIL)
WAVE_6 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_MEJRAH, JAL_MEJRAH)
WAVE_60 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_IMKOT, JAL_XIL)
WAVE_61 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_AK, JAL_IMKOT, JAL_XIL)
WAVE_62 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_IMKOT, JAL_XIL)
WAVE_63 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_IMKOT, JAL_XIL)
WAVE_64 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_IMKOT, JAL_XIL)
WAVE_65 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_XIL)
WAVE_66 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_ZEK, JAL_ZEK)
WAVE_67 =(JALTOK_JAD)
WAVE_68 =(JALTOK_JAD, JALTOK_JAD)
WAVE_69 =(6609)
WAVE_7 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_AK)
WAVE_8 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB)
WAVE_9 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT)
Private Attributes
final int[] monster
Detailed Description
Definition at line 23 of file InfernoWaveData.java.
Constructor & Destructor Documentation
WaveData()
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WaveData (int... monster)
Definition at line 86 of file InfernoWaveData.java.
{
            this.monster = monster;
        }
References monster.
Referenced by getNext(), and getOrdinal().
Member Function Documentation
getMonster()
int[] com.runehive.content.activity.inferno.InfernoWaveData.WaveData.getMonster ()
Definition at line 90 of file InfernoWaveData.java.
{
            return monster;
        }
References monster.
getNext()
WaveData com.runehive.content.activity.inferno.InfernoWaveData.WaveData.getNext (int current) static
Definition at line 102 of file InfernoWaveData.java.
{
            return getOrdinal(current + 1);
        }
References getOrdinal(), and WaveData().
Referenced by com.runehive.content.activity.inferno.Inferno.handleDeath().
getOrdinal()
WaveData com.runehive.content.activity.inferno.InfernoWaveData.WaveData.getOrdinal (int ordinal) static
Definition at line 94 of file InfernoWaveData.java.
{
            for (WaveData wave : values()) {
                if (wave.ordinal() == ordinal)
                    return wave;
            }
            return null;
        }
References WaveData().
Referenced by getNext().
Member Data Documentation
monster
final int [] com.runehive.content.activity.inferno.InfernoWaveData.WaveData.monster private
Definition at line 84 of file InfernoWaveData.java.
Referenced by getMonster(), and WaveData().
WAVE_1
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_1 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_MEJRAH)
Definition at line 24 of file InfernoWaveData.java.
WAVE_10
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_10 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH)
Definition at line 29 of file InfernoWaveData.java.
WAVE_11
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_11 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH)
Definition at line 30 of file InfernoWaveData.java.
WAVE_12
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_12 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH)
Definition at line 31 of file InfernoWaveData.java.
WAVE_13
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_13 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_AK)
Definition at line 32 of file InfernoWaveData.java.
WAVE_14
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_14 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH, JAL_AK)
Definition at line 33 of file InfernoWaveData.java.
WAVE_15
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_15 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_AK, JAL_IMKOT)
Definition at line 34 of file InfernoWaveData.java.
WAVE_16
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_16 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_IMKOT)
Definition at line 35 of file InfernoWaveData.java.
WAVE_17
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_17 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB)
Definition at line 35 of file InfernoWaveData.java.
WAVE_18
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_18 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL)
Definition at line 36 of file InfernoWaveData.java.
WAVE_19
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_19 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH)
Definition at line 36 of file InfernoWaveData.java.
WAVE_2
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_2 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_MEJRAH, JAL_MEJRAH)
Definition at line 24 of file InfernoWaveData.java.
WAVE_20
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_20 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH)
Definition at line 37 of file InfernoWaveData.java.
WAVE_21
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_21 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK)
Definition at line 38 of file InfernoWaveData.java.
WAVE_22
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_22 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_MEJRAH)
Definition at line 39 of file InfernoWaveData.java.
WAVE_23
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_23 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH, JAL_AK)
Definition at line 40 of file InfernoWaveData.java.
WAVE_24
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_24 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_AK)
Definition at line 41 of file InfernoWaveData.java.
WAVE_25
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_25 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT)
Definition at line 42 of file InfernoWaveData.java.
WAVE_26
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_26 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_MEJRAH)
Definition at line 43 of file InfernoWaveData.java.
WAVE_27
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_27 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT)
Definition at line 44 of file InfernoWaveData.java.
WAVE_28
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_28 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_AK)
Definition at line 45 of file InfernoWaveData.java.
WAVE_29
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_29 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_IMKOT)
Definition at line 46 of file InfernoWaveData.java.
WAVE_3
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_3 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB)
Definition at line 25 of file InfernoWaveData.java.
WAVE_30
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_30 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH, JAL_AK)
Definition at line 47 of file InfernoWaveData.java.
WAVE_31
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_31 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_AK, JAL_IMKOT)
Definition at line 48 of file InfernoWaveData.java.
WAVE_32
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_32 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_IMKOT)
Definition at line 49 of file InfernoWaveData.java.
WAVE_33
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_33 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_XIL)
Definition at line 50 of file InfernoWaveData.java.
WAVE_34
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_34 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB)
Definition at line 50 of file InfernoWaveData.java.
WAVE_35
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_35 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK)
Definition at line 51 of file InfernoWaveData.java.
WAVE_36
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_36 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH)
Definition at line 51 of file InfernoWaveData.java.
WAVE_37
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_37 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH)
Definition at line 52 of file InfernoWaveData.java.
WAVE_38
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_38 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK)
Definition at line 53 of file InfernoWaveData.java.
WAVE_39
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_39 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_MEJRAH)
Definition at line 54 of file InfernoWaveData.java.
WAVE_4
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_4 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK)
Definition at line 25 of file InfernoWaveData.java.
WAVE_40
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_40 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK)
Definition at line 55 of file InfernoWaveData.java.
WAVE_41
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_41 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK)
Definition at line 56 of file InfernoWaveData.java.
WAVE_42
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_42 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT)
Definition at line 57 of file InfernoWaveData.java.
WAVE_43
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_43 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_MEJRAH)
Definition at line 58 of file InfernoWaveData.java.
WAVE_44
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_44 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT)
Definition at line 59 of file InfernoWaveData.java.
WAVE_45
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_45 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_AK)
Definition at line 60 of file InfernoWaveData.java.
WAVE_46
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_46 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_AK, JAL_IMKOT)
Definition at line 61 of file InfernoWaveData.java.
WAVE_47
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_47 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_IMKOT)
Definition at line 62 of file InfernoWaveData.java.
WAVE_48
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_48 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_IMKOT)
Definition at line 63 of file InfernoWaveData.java.
WAVE_49
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_49 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_IMKOT)
Definition at line 64 of file InfernoWaveData.java.
WAVE_5
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_5 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_MEJRAH)
Definition at line 26 of file InfernoWaveData.java.
WAVE_50
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_50 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL)
Definition at line 65 of file InfernoWaveData.java.
WAVE_51
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_51 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_XIL)
Definition at line 66 of file InfernoWaveData.java.
WAVE_52
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_52 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH)
Definition at line 67 of file InfernoWaveData.java.
WAVE_53
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_53 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_AK)
Definition at line 68 of file InfernoWaveData.java.
WAVE_54
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_54 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_XIL, JAL_AK)
Definition at line 69 of file InfernoWaveData.java.
WAVE_55
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_55 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_XIL)
Definition at line 70 of file InfernoWaveData.java.
WAVE_56
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_56 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_XIL)
Definition at line 71 of file InfernoWaveData.java.
WAVE_57
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_57 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_ZEK, JAL_IMKOT)
Definition at line 72 of file InfernoWaveData.java.
WAVE_58
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_58 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_IMKOT, JAL_XIL)
Definition at line 73 of file InfernoWaveData.java.
WAVE_59
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_59 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT, JAL_XIL)
Definition at line 74 of file InfernoWaveData.java.
WAVE_6
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_6 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_MEJRAH, JAL_MEJRAH)
Definition at line 27 of file InfernoWaveData.java.
WAVE_60
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_60 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_IMKOT, JAL_XIL)
Definition at line 75 of file InfernoWaveData.java.
WAVE_61
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_61 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_AK, JAL_IMKOT, JAL_XIL)
Definition at line 76 of file InfernoWaveData.java.
WAVE_62
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_62 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_IMKOT, JAL_XIL)
Definition at line 77 of file InfernoWaveData.java.
WAVE_63
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_63 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_IMKOT, JAL_XIL)
Definition at line 78 of file InfernoWaveData.java.
WAVE_64
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_64 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_IMKOT, JAL_XIL)
Definition at line 79 of file InfernoWaveData.java.
WAVE_65
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_65 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_XIL)
Definition at line 80 of file InfernoWaveData.java.
WAVE_66
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_66 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_ZEK, JAL_ZEK)
Definition at line 81 of file InfernoWaveData.java.
WAVE_67
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_67 =(JALTOK_JAD)
Definition at line 81 of file InfernoWaveData.java.
WAVE_68
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_68 =(JALTOK_JAD, JALTOK_JAD)
Definition at line 82 of file InfernoWaveData.java.
WAVE_69
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_69 =(6609)
Definition at line 82 of file InfernoWaveData.java.
Referenced by com.runehive.content.activity.inferno.Inferno.finalWave(), and com.runehive.content.activity.inferno.Inferno.start().
WAVE_7
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_7 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_AK)
Definition at line 28 of file InfernoWaveData.java.
WAVE_8
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_8 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB)
Definition at line 28 of file InfernoWaveData.java.
WAVE_9
com.runehive.content.activity.inferno.InfernoWaveData.WaveData.WAVE_9 =(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT)
Definition at line 29 of file InfernoWaveData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/activity/inferno/InfernoWaveData.java