RuneHive-Game: com.runehive.content.emote.Skillcape Enum Reference
com.runehive.content.emote.Skillcape Enum Reference
Holds the data for skillcape emotes.
Public Member Functions
int getAnimation ()
int getGraphic ()
int getSkill ()
int[] getSkillcape ()
Skillcape (int[] item, int graphic, int animation, int skill)
Static Public Member Functions
static boolean equip (Player player, Item item)
static Skillcape forId (int id)
static Optional< Skillcape > forSkill (int skill)
static StoreItem[] getItems ()
Public Attributes
ACHIEVEMENT_CAPE =(new int[]{13069}, 323, 2709, -1)
AGILITY_CAPE =(new int[]{9771, 9772, 9773}, 830, 4977, Skill.AGILITY)
ATTACK_CAPE =(new int[]{9747, 9748, 9479}, 823, 4959, Skill.ATTACK)
CONSTRUCTION_CAPE =(new int[]{9789, 9790, 9791}, 820, 4953, Skill.CONSTRUCTION)
COOKING_CAPE =(new int[]{9801, 9802, 9803}, 821, 4955, Skill.COOKING)
CRAFTING_CAPE =(new int[]{9780, 9781, 9782}, 818, 4949, Skill.CRAFTING)
DEFENCE_CAPE =(new int[]{9753, 9754, 9755}, 824, 4961, Skill.DEFENCE)
FARMING_CAPE =(new int[]{9810, 9811, 9812}, 825, 4963, Skill.FARMING)
FIREMAKING_CAPE =(new int[]{9804, 9805, 9806}, 831, 4975, Skill.FIREMAKING)
FISHING_CAPE =(new int[]{9798, 9799, 9800}, 819, 4951, Skill.FISHING)
FLETCHING_CAPE =(new int[]{9783, 9784, 9785}, 812, 4937, Skill.FLETCHING)
HERBLORE_CAPE =(new int[]{9774, 9775, 9776}, 835, 4969, Skill.HERBLORE)
HITPOINTS_CAPE =(new int[]{9768, 9769, 9770}, 833, 4971, Skill.HITPOINTS)
HUNTER_CAPE =(new int[]{9948, 9949, 9950}, 907, 5158, Skill.HUNTER)
MAGIC_CAPE =(new int[]{9762, 9763, 9764}, 813, 4939, Skill.MAGIC)
MAX_CAPE =(new int[]{13280, 13329, 13331, 13333, 13335, 13337}, 1286, 7121, -1)
MINING_CAPE =(new int[]{9792, 9793, 9794}, 814, 4941, Skill.MINING)
PRAYER_CAPE =(new int[]{9759, 9760, 9761}, 829, 4979, Skill.PRAYER)
QUEST_POINT_CAPE =(new int[]{9813, 9814, 9815}, 816, 4945, -1)
RANGING_CAPE =(new int[]{9756, 9757, 9758}, 832, 4973, Skill.RANGED)
RUNECRAFT_CAPE =(new int[]{9765, 9766, 9767}, 817, 4947, Skill.RUNECRAFTING)
SLAYER_CAPE =(new int[]{9786, 9787, 9788}, 827, 4967, Skill.SLAYER)
SMITHING_CAPE =(new int[]{9795, 9796, 9797}, 815, 4943, Skill.SMITHING)
STRENGTH_CAPE =(new int[]{9750, 9751, 9752}, 828, 4981, Skill.STRENGTH)
THEIVING_CAPE =(new int[]{9777, 9778, 9779}, 826, 4965, Skill.THIEVING)
WOODCUTTING_CAPE =(new int[]{9807, 9808, 9809}, 822, 4957, Skill.WOODCUTTING)
Private Attributes
final int animation
final int graphic
final int[] item
final int skill
Detailed Description
Holds the data for skillcape emotes.
Author
Daniel
Definition at line 19 of file Skillcape.java.
Constructor & Destructor Documentation
Skillcape()
com.runehive.content.emote.Skillcape.Skillcape (int[] item, int graphic, int animation, int skill)
Definition at line 52 of file Skillcape.java.
{
        this.item = item;
        this.graphic = graphic;
        this.animation = animation;
        this.skill = skill;
    }
References animation, graphic, item, and skill.
Referenced by equip(), forId(), and getItems().
Member Function Documentation
equip()
boolean com.runehive.content.emote.Skillcape.equip (Player player, Item item) static
Definition at line 101 of file Skillcape.java.
{
        Skillcape data = forId(item.getId());
        if (data == null) {
            return true;
        }
        if (data.getSkill() == -1) {
            return true;
        }
        if (player.skills.getMaxLevel(data.getSkill()) != 99) {
            player.send(new SendMessage("You need to have a " + Skill.getName(data.getSkill()) + " level of 99 to equip this item."));
            return false;
        }
        return true;
    }
References forId(), com.runehive.game.world.entity.skill.SkillManager.getMaxLevel(), com.runehive.game.world.entity.skill.Skill.getName(), getSkill(), item, com.runehive.game.world.entity.mob.player.Player.send(), Skillcape(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.equip().
forId()
Skillcape com.runehive.content.emote.Skillcape.forId (int id) static
Definition at line 75 of file Skillcape.java.
{
        for (Skillcape data : Skillcape.values())
            for (int index = 0; index < data.getSkillcape().length; index++)
                if (data.getSkillcape()[index] == id)
                    return data;
        return null;
    }
References Skillcape().
Referenced by equip(), com.runehive.content.store.impl.SkillcapeStore.purchase(), com.runehive.content.emote.Emote.skillcape(), and com.runehive.content.emote.EmoteHandler.updateSkillcape().
forSkill()
Optional< Skillcape > com.runehive.content.emote.Skillcape.forSkill (int skill) static
Definition at line 83 of file Skillcape.java.
{
        return Arrays.stream(values()).filter(s -> s.getSkill() == skill).findFirst();
    }
References skill.
getAnimation()
int com.runehive.content.emote.Skillcape.getAnimation ()
Definition at line 59 of file Skillcape.java.
{
        return animation;
    }
References animation.
getGraphic()
int com.runehive.content.emote.Skillcape.getGraphic ()
Definition at line 63 of file Skillcape.java.
{
        return graphic;
    }
References graphic.
getItems()
StoreItem[] com.runehive.content.emote.Skillcape.getItems () static
Definition at line 87 of file Skillcape.java.
{
        final StoreItem[] items = new StoreItem[Skill.SKILL_COUNT];
        int index = 0;
        for (Skillcape data : values()) {
            if (data.skill == -1)
                continue;
            items[index] = new StoreItem(data.getSkillcape()[1], 1, OptionalInt.of(100000), Optional.of(CurrencyType.COINS));
            index++;
        }
        return items;
    }
References com.runehive.content.store.currency.CurrencyType.COINS, com.runehive.game.world.entity.skill.Skill.SKILL_COUNT, and Skillcape().
getSkill()
int com.runehive.content.emote.Skillcape.getSkill ()
Definition at line 71 of file Skillcape.java.
{
        return skill;
    }
References skill.
Referenced by equip(), and com.runehive.content.store.impl.SkillcapeStore.purchase().
getSkillcape()
int[] com.runehive.content.emote.Skillcape.getSkillcape ()
Definition at line 67 of file Skillcape.java.
{
        return item;
    }
References item.
Member Data Documentation
ACHIEVEMENT_CAPE
com.runehive.content.emote.Skillcape.ACHIEVEMENT_CAPE =(new int[]{13069}, 323, 2709, -1)
Definition at line 44 of file Skillcape.java.
AGILITY_CAPE
com.runehive.content.emote.Skillcape.AGILITY_CAPE =(new int[]{9771, 9772, 9773}, 830, 4977, Skill.AGILITY)
Definition at line 28 of file Skillcape.java.
animation
final int com.runehive.content.emote.Skillcape.animation private
Definition at line 49 of file Skillcape.java.
Referenced by getAnimation(), and Skillcape().
ATTACK_CAPE
com.runehive.content.emote.Skillcape.ATTACK_CAPE =(new int[]{9747, 9748, 9479}, 823, 4959, Skill.ATTACK)
Definition at line 20 of file Skillcape.java.
CONSTRUCTION_CAPE
com.runehive.content.emote.Skillcape.CONSTRUCTION_CAPE =(new int[]{9789, 9790, 9791}, 820, 4953, Skill.CONSTRUCTION)
Definition at line 34 of file Skillcape.java.
COOKING_CAPE
com.runehive.content.emote.Skillcape.COOKING_CAPE =(new int[]{9801, 9802, 9803}, 821, 4955, Skill.COOKING)
Definition at line 38 of file Skillcape.java.
CRAFTING_CAPE
com.runehive.content.emote.Skillcape.CRAFTING_CAPE =(new int[]{9780, 9781, 9782}, 818, 4949, Skill.CRAFTING)
Definition at line 31 of file Skillcape.java.
DEFENCE_CAPE
com.runehive.content.emote.Skillcape.DEFENCE_CAPE =(new int[]{9753, 9754, 9755}, 824, 4961, Skill.DEFENCE)
Definition at line 22 of file Skillcape.java.
FARMING_CAPE
com.runehive.content.emote.Skillcape.FARMING_CAPE =(new int[]{9810, 9811, 9812}, 825, 4963, Skill.FARMING)
Definition at line 41 of file Skillcape.java.
FIREMAKING_CAPE
com.runehive.content.emote.Skillcape.FIREMAKING_CAPE =(new int[]{9804, 9805, 9806}, 831, 4975, Skill.FIREMAKING)
Definition at line 39 of file Skillcape.java.
FISHING_CAPE
com.runehive.content.emote.Skillcape.FISHING_CAPE =(new int[]{9798, 9799, 9800}, 819, 4951, Skill.FISHING)
Definition at line 37 of file Skillcape.java.
FLETCHING_CAPE
com.runehive.content.emote.Skillcape.FLETCHING_CAPE =(new int[]{9783, 9784, 9785}, 812, 4937, Skill.FLETCHING)
Definition at line 32 of file Skillcape.java.
graphic
final int com.runehive.content.emote.Skillcape.graphic private
Definition at line 48 of file Skillcape.java.
Referenced by getGraphic(), and Skillcape().
HERBLORE_CAPE
com.runehive.content.emote.Skillcape.HERBLORE_CAPE =(new int[]{9774, 9775, 9776}, 835, 4969, Skill.HERBLORE)
Definition at line 29 of file Skillcape.java.
HITPOINTS_CAPE
com.runehive.content.emote.Skillcape.HITPOINTS_CAPE =(new int[]{9768, 9769, 9770}, 833, 4971, Skill.HITPOINTS)
Definition at line 27 of file Skillcape.java.
HUNTER_CAPE
com.runehive.content.emote.Skillcape.HUNTER_CAPE =(new int[]{9948, 9949, 9950}, 907, 5158, Skill.HUNTER)
Definition at line 42 of file Skillcape.java.
item
final int [] com.runehive.content.emote.Skillcape.item private
Definition at line 47 of file Skillcape.java.
Referenced by equip(), getSkillcape(), and Skillcape().
MAGIC_CAPE
com.runehive.content.emote.Skillcape.MAGIC_CAPE =(new int[]{9762, 9763, 9764}, 813, 4939, Skill.MAGIC)
Definition at line 25 of file Skillcape.java.
MAX_CAPE
com.runehive.content.emote.Skillcape.MAX_CAPE =(new int[]{13280, 13329, 13331, 13333, 13335, 13337}, 1286, 7121, -1)
Definition at line 45 of file Skillcape.java.
MINING_CAPE
com.runehive.content.emote.Skillcape.MINING_CAPE =(new int[]{9792, 9793, 9794}, 814, 4941, Skill.MINING)
Definition at line 35 of file Skillcape.java.
PRAYER_CAPE
com.runehive.content.emote.Skillcape.PRAYER_CAPE =(new int[]{9759, 9760, 9761}, 829, 4979, Skill.PRAYER)
Definition at line 24 of file Skillcape.java.
QUEST_POINT_CAPE
com.runehive.content.emote.Skillcape.QUEST_POINT_CAPE =(new int[]{9813, 9814, 9815}, 816, 4945, -1)
Definition at line 43 of file Skillcape.java.
RANGING_CAPE
com.runehive.content.emote.Skillcape.RANGING_CAPE =(new int[]{9756, 9757, 9758}, 832, 4973, Skill.RANGED)
Definition at line 23 of file Skillcape.java.
RUNECRAFT_CAPE
com.runehive.content.emote.Skillcape.RUNECRAFT_CAPE =(new int[]{9765, 9766, 9767}, 817, 4947, Skill.RUNECRAFTING)
Definition at line 26 of file Skillcape.java.
skill
final int com.runehive.content.emote.Skillcape.skill private
Definition at line 50 of file Skillcape.java.
Referenced by forSkill(), getSkill(), and Skillcape().
SLAYER_CAPE
com.runehive.content.emote.Skillcape.SLAYER_CAPE =(new int[]{9786, 9787, 9788}, 827, 4967, Skill.SLAYER)
Definition at line 33 of file Skillcape.java.
SMITHING_CAPE
com.runehive.content.emote.Skillcape.SMITHING_CAPE =(new int[]{9795, 9796, 9797}, 815, 4943, Skill.SMITHING)
Definition at line 36 of file Skillcape.java.
STRENGTH_CAPE
com.runehive.content.emote.Skillcape.STRENGTH_CAPE =(new int[]{9750, 9751, 9752}, 828, 4981, Skill.STRENGTH)
Definition at line 21 of file Skillcape.java.
THEIVING_CAPE
com.runehive.content.emote.Skillcape.THEIVING_CAPE =(new int[]{9777, 9778, 9779}, 826, 4965, Skill.THIEVING)
Definition at line 30 of file Skillcape.java.
WOODCUTTING_CAPE
com.runehive.content.emote.Skillcape.WOODCUTTING_CAPE =(new int[]{9807, 9808, 9809}, 822, 4957, Skill.WOODCUTTING)
Definition at line 40 of file Skillcape.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/emote/Skillcape.java