RuneHive-Game: com.runehive.content.EmblemData Enum Reference
com.runehive.content.EmblemData Enum Reference
Created by Daniel on 2018-02-06.
Public Member Functions
EmblemData (int item, int bloodMoney)
int getNext ()
Static Public Member Functions
static EmblemData forId (int id)
Public Attributes
ANCIENT =(21807, 1)
final int bloodMoney
final int item
TIER_1 =(12746, 50)
TIER_10 =(12756, 1000)
TIER_2 =(12748, 75)
TIER_3 =(12749, 100)
TIER_4 =(12750, 150)
TIER_5 =(12751, 225)
TIER_6 =(12752, 300)
TIER_7 =(12753, 400)
TIER_8 =(12754, 525)
TIER_9 =(12755, 750)
Detailed Description
Created by Daniel on 2018-02-06.
Definition at line 6 of file EmblemData.java.
Constructor & Destructor Documentation
EmblemData()
com.runehive.content.EmblemData.EmblemData (int item, int bloodMoney)
Definition at line 22 of file EmblemData.java.
{
        this.item = item;
        this.bloodMoney = bloodMoney;
    }
References bloodMoney, and item.
Referenced by forId().
Member Function Documentation
forId()
EmblemData com.runehive.content.EmblemData.forId (int id) static
Definition at line 27 of file EmblemData.java.
{
        for (EmblemData emblem : values()) {
            if (emblem.item == id)
                return emblem;
        }
        return null;
    }
References EmblemData().
Referenced by com.runehive.game.world.entity.mob.player.PlayerKilling.handle().
getNext()
int com.runehive.content.EmblemData.getNext ()
Definition at line 35 of file EmblemData.java.
{
        if (this == TIER_10 || this == ANCIENT)
            return -1;
        return values()[this.ordinal() + 1].item;
    }
References ANCIENT, and TIER_10.
Referenced by com.runehive.game.world.entity.mob.player.PlayerKilling.handle().
Member Data Documentation
ANCIENT
com.runehive.content.EmblemData.ANCIENT =(21807, 1)
Definition at line 17 of file EmblemData.java.
Referenced by getNext().
bloodMoney
final int com.runehive.content.EmblemData.bloodMoney
Definition at line 20 of file EmblemData.java.
Referenced by EmblemData().
item
final int com.runehive.content.EmblemData.item
Definition at line 19 of file EmblemData.java.
Referenced by EmblemData().
TIER_1
com.runehive.content.EmblemData.TIER_1 =(12746, 50)
Definition at line 7 of file EmblemData.java.
TIER_10
com.runehive.content.EmblemData.TIER_10 =(12756, 1000)
Definition at line 16 of file EmblemData.java.
Referenced by getNext().
TIER_2
com.runehive.content.EmblemData.TIER_2 =(12748, 75)
Definition at line 8 of file EmblemData.java.
TIER_3
com.runehive.content.EmblemData.TIER_3 =(12749, 100)
Definition at line 9 of file EmblemData.java.
TIER_4
com.runehive.content.EmblemData.TIER_4 =(12750, 150)
Definition at line 10 of file EmblemData.java.
TIER_5
com.runehive.content.EmblemData.TIER_5 =(12751, 225)
Definition at line 11 of file EmblemData.java.
TIER_6
com.runehive.content.EmblemData.TIER_6 =(12752, 300)
Definition at line 12 of file EmblemData.java.
TIER_7
com.runehive.content.EmblemData.TIER_7 =(12753, 400)
Definition at line 13 of file EmblemData.java.
TIER_8
com.runehive.content.EmblemData.TIER_8 =(12754, 525)
Definition at line 14 of file EmblemData.java.
TIER_9
com.runehive.content.EmblemData.TIER_9 =(12755, 750)
Definition at line 15 of file EmblemData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/EmblemData.java