RuneHive-Game: com.runehive.game.world.entity.combat.ranged.RangedWeaponType Enum Reference
com.runehive.game.world.entity.combat.ranged.RangedWeaponType Enum Reference
Public Member Functions
int getSlot ()
RangedWeaponType (int slot)
Public Attributes
SHOT =(Equipment.ARROWS_SLOT)
final int slot
THROWN =(Equipment.WEAPON_SLOT)
Detailed Description
Definition at line 5 of file RangedWeaponType.java.
Constructor & Destructor Documentation
RangedWeaponType()
com.runehive.game.world.entity.combat.ranged.RangedWeaponType.RangedWeaponType (int slot)
Definition at line 11 of file RangedWeaponType.java.
{
        this.slot = slot;
    }
Member Function Documentation
getSlot()
int com.runehive.game.world.entity.combat.ranged.RangedWeaponType.getSlot ()
Definition at line 15 of file RangedWeaponType.java.
{
        return slot;
    }
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
Member Data Documentation
SHOT
com.runehive.game.world.entity.combat.ranged.RangedWeaponType.SHOT =(Equipment.ARROWS_SLOT)
Definition at line 6 of file RangedWeaponType.java.
slot
final int com.runehive.game.world.entity.combat.ranged.RangedWeaponType.slot
Definition at line 9 of file RangedWeaponType.java.
THROWN
com.runehive.game.world.entity.combat.ranged.RangedWeaponType.THROWN =(Equipment.WEAPON_SLOT)
Definition at line 7 of file RangedWeaponType.java.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), and com.runehive.game.world.items.containers.equipment.Equipment.onRemove().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/ranged/RangedWeaponType.java