RuneHive-Game: com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType Enum Reference
com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType Enum Reference
Public Member Functions
ExchangeSessionType (String name)
Public Attributes
DUEL =("duel")
final String name
TRADE =("trade")
Detailed Description
Author
Stand Up
Since
23-1-2017.
Definition at line 7 of file ExchangeSessionType.java.
Constructor & Destructor Documentation
ExchangeSessionType()
com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.ExchangeSessionType (String name)
Definition at line 13 of file ExchangeSessionType.java.
{
        this.name = name;
    }
References name.
Member Data Documentation
DUEL
com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.DUEL =("duel")
Definition at line 9 of file ExchangeSessionType.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canDrinkPotions(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEat(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canLogout(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canUsePrayer(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canUseSpecial(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.clickObject(), com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.task.impl.DuelNotificationTask.execute(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onButtonClick(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.onDeath(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.onLogout(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.remove(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.request(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.sequence(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.StakeSession(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
name
final String com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.name
Definition at line 11 of file ExchangeSessionType.java.
Referenced by ExchangeSessionType().
TRADE
com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionType.TRADE =("trade")
Definition at line 8 of file ExchangeSessionType.java.
Referenced by com.runehive.game.world.entity.mob.player.InterfaceManager.close(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onButtonClick(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.TradeSession().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/player/exchange/ExchangeSessionType.java