RuneHive-Game: com.runehive.content.skill.impl.fishing.FishingSpot Enum Reference
com.runehive.content.skill.impl.fishing.FishingSpot Enum Reference
Public Member Functions
FishingSpot (int id, Fishable[] firstOption, Fishable[] secondOption)
Fishable[] getFirstOption ()
int getId ()
Fishable[] getSecondOption ()
Static Public Member Functions
static void declare ()
static FishingSpot forId (int id)
Public Attributes
CAGE_OR_HARPOON =(1519, new Fishable[]{Fishable.LOBSTER}, new Fishable[]{Fishable.TUNA, Fishable.SWORD_FISH})
DARK_CRAB =(1536, new Fishable[]{Fishable.DARK_CRAB}, new Fishable[]{Fishable.DARK_CRAB})
HARPOON_OR_SMALL_NET =(1534, new Fishable[]{Fishable.MONK_FISH}, new Fishable[]{Fishable.MONK_FISH})
LARGE_NET_OR_HARPOON =(1520, new Fishable[]{Fishable.MACKEREL, Fishable.COD, Fishable.BASS}, new Fishable[]{Fishable.SHARK})
LURE_OR_BAIT =(1526, new Fishable[]{Fishable.TROUT, Fishable.SALMON}, new Fishable[]{Fishable.SARDINE, Fishable.HERRING, Fishable.PIKE})
MANTA_RAY =(1521, new Fishable[]{Fishable.MANTA_RAY}, new Fishable[]{Fishable.MANTA_RAY})
SMALL_NET_OR_BAIT =(1518, new Fishable[]{Fishable.SHRIMP, Fishable.ANCHOVIES}, new Fishable[]{Fishable.SARDINE, Fishable.HERRING, Fishable.PIKE})
Private Attributes
Fishable[] firstOption
int id
Fishable[] secondOption
Static Private Attributes
static Map< Integer, FishingSpot > fishingSpots = new HashMap<>()
Detailed Description
Definition at line 6 of file FishingSpot.java.
Constructor & Destructor Documentation
FishingSpot()
com.runehive.content.skill.impl.fishing.FishingSpot.FishingSpot (int id, Fishable[] firstOption, Fishable[] secondOption)
Definition at line 29 of file FishingSpot.java.
{
        this.id = id;
        this.firstOption = firstOption;
        this.secondOption = secondOption;
    }
References firstOption, id, and secondOption.
Referenced by declare(), and forId().
Member Function Documentation
declare()
void com.runehive.content.skill.impl.fishing.FishingSpot.declare () static
Definition at line 20 of file FishingSpot.java.
{
        for (FishingSpot spots : values())
            fishingSpots.put(spots.getId(), spots);
    }
References FishingSpot(), and fishingSpots.
Referenced by com.runehive.content.skill.SkillRepository.load().
forId()
FishingSpot com.runehive.content.skill.impl.fishing.FishingSpot.forId (int id) static
Definition at line 25 of file FishingSpot.java.
{
        return fishingSpots.get(id);
    }
References FishingSpot(), and fishingSpots.
Referenced by com.runehive.content.skill.impl.fishing.Fishing.clickNpc().
getFirstOption()
Fishable[] com.runehive.content.skill.impl.fishing.FishingSpot.getFirstOption ()
Definition at line 39 of file FishingSpot.java.
{
        return firstOption;
    }
References firstOption.
Referenced by com.runehive.content.skill.impl.fishing.Fishing.clickNpc().
getId()
int com.runehive.content.skill.impl.fishing.FishingSpot.getId ()
Definition at line 35 of file FishingSpot.java.
                       {
        return id;
    }
References id.
getSecondOption()
Fishable[] com.runehive.content.skill.impl.fishing.FishingSpot.getSecondOption ()
Definition at line 43 of file FishingSpot.java.
{
        return secondOption;
    }
References secondOption.
Referenced by com.runehive.content.skill.impl.fishing.Fishing.clickNpc().
Member Data Documentation
CAGE_OR_HARPOON
com.runehive.content.skill.impl.fishing.FishingSpot.CAGE_OR_HARPOON =(1519, new Fishable[]{Fishable.LOBSTER}, new Fishable[]{Fishable.TUNA, Fishable.SWORD_FISH})
Definition at line 9 of file FishingSpot.java.
DARK_CRAB
com.runehive.content.skill.impl.fishing.FishingSpot.DARK_CRAB =(1536, new Fishable[]{Fishable.DARK_CRAB}, new Fishable[]{Fishable.DARK_CRAB})
Definition at line 13 of file FishingSpot.java.
firstOption
Fishable [] com.runehive.content.skill.impl.fishing.FishingSpot.firstOption private
Definition at line 16 of file FishingSpot.java.
Referenced by FishingSpot(), and getFirstOption().
fishingSpots
Map<Integer, FishingSpot> com.runehive.content.skill.impl.fishing.FishingSpot.fishingSpots = new HashMap<>() static private
Definition at line 18 of file FishingSpot.java.
Referenced by declare(), and forId().
HARPOON_OR_SMALL_NET
com.runehive.content.skill.impl.fishing.FishingSpot.HARPOON_OR_SMALL_NET =(1534, new Fishable[]{Fishable.MONK_FISH}, new Fishable[]{Fishable.MONK_FISH})
Definition at line 11 of file FishingSpot.java.
id
int com.runehive.content.skill.impl.fishing.FishingSpot.id private
Definition at line 15 of file FishingSpot.java.
Referenced by FishingSpot(), and getId().
LARGE_NET_OR_HARPOON
com.runehive.content.skill.impl.fishing.FishingSpot.LARGE_NET_OR_HARPOON =(1520, new Fishable[]{Fishable.MACKEREL, Fishable.COD, Fishable.BASS}, new Fishable[]{Fishable.SHARK})
Definition at line 10 of file FishingSpot.java.
LURE_OR_BAIT
com.runehive.content.skill.impl.fishing.FishingSpot.LURE_OR_BAIT =(1526, new Fishable[]{Fishable.TROUT, Fishable.SALMON}, new Fishable[]{Fishable.SARDINE, Fishable.HERRING, Fishable.PIKE})
Definition at line 8 of file FishingSpot.java.
MANTA_RAY
com.runehive.content.skill.impl.fishing.FishingSpot.MANTA_RAY =(1521, new Fishable[]{Fishable.MANTA_RAY}, new Fishable[]{Fishable.MANTA_RAY})
Definition at line 12 of file FishingSpot.java.
secondOption
Fishable [] com.runehive.content.skill.impl.fishing.FishingSpot.secondOption private
Definition at line 17 of file FishingSpot.java.
Referenced by FishingSpot(), and getSecondOption().
SMALL_NET_OR_BAIT
com.runehive.content.skill.impl.fishing.FishingSpot.SMALL_NET_OR_BAIT =(1518, new Fishable[]{Fishable.SHRIMP, Fishable.ANCHOVIES}, new Fishable[]{Fishable.SARDINE, Fishable.HERRING, Fishable.PIKE})
Definition at line 7 of file FishingSpot.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fishing/FishingSpot.java