RuneHive-Game: com.runehive.content.achievement.AchievementType Enum Reference
com.runehive.content.achievement.AchievementType Enum Reference
The types of achievement types.
Public Member Functions
AchievementType (int color, String title)
int getColor ()
String getTitle ()
Public Attributes
MINIGAME =(0x4285E3, "Minigame")
MISCELLANEOUS =(0xAE47ED, "Misc.")
PVM =(0xDB8E3B, "PvM")
PVP =(0xE83838, "PvP")
SKILLING =(0x5CC947, "Skilling")
Private Attributes
final int color
final String title
Detailed Description
The types of achievement types.
Author
Daniel
Definition at line 8 of file AchievementType.java.
Constructor & Destructor Documentation
AchievementType()
com.runehive.content.achievement.AchievementType.AchievementType (int color, String title)
Definition at line 18 of file AchievementType.java.
{
        this.title = title;
        this.color = color;
    }
References color, and title.
Member Function Documentation
getColor()
int com.runehive.content.achievement.AchievementType.getColor ()
Definition at line 27 of file AchievementType.java.
{
        return color;
    }
References color.
getTitle()
String com.runehive.content.achievement.AchievementType.getTitle ()
Definition at line 23 of file AchievementType.java.
{
        return title;
    }
References title.
Member Data Documentation
color
final int com.runehive.content.achievement.AchievementType.color private
Definition at line 16 of file AchievementType.java.
Referenced by AchievementType(), and getColor().
MINIGAME
com.runehive.content.achievement.AchievementType.MINIGAME =(0x4285E3, "Minigame")
Definition at line 12 of file AchievementType.java.
Referenced by com.runehive.content.achievement.AchievementWriter.AchievementWriter().
MISCELLANEOUS
com.runehive.content.achievement.AchievementType.MISCELLANEOUS =(0xAE47ED, "Misc.")
Definition at line 13 of file AchievementType.java.
Referenced by com.runehive.content.achievement.AchievementWriter.AchievementWriter().
PVM
com.runehive.content.achievement.AchievementType.PVM =(0xDB8E3B, "PvM")
Definition at line 10 of file AchievementType.java.
PVP
com.runehive.content.achievement.AchievementType.PVP =(0xE83838, "PvP")
Definition at line 9 of file AchievementType.java.
SKILLING
com.runehive.content.achievement.AchievementType.SKILLING =(0x5CC947, "Skilling")
Definition at line 11 of file AchievementType.java.
Referenced by com.runehive.content.achievement.AchievementWriter.AchievementWriter().
title
final String com.runehive.content.achievement.AchievementType.title private
Definition at line 15 of file AchievementType.java.
Referenced by AchievementType(), and getTitle().
The documentation for this enum was generated from the following file:
java/com/runehive/content/achievement/AchievementType.java