RuneHive-Game: com.runehive.content.skill.impl.prayer.AshData Enum Reference
com.runehive.content.skill.impl.prayer.AshData Enum Reference
Public Member Functions
AshData (int id, int noted, double experience)
double getExperience ()
int getId ()
int getId2 ()
Static Public Member Functions
static Optional< AshData > forId (int id)
Public Attributes
ABYSSAL_ASHES =(25775, 25776,85.0D)
FIENDISH_ASHES =(25766, 25767, 10.0D)
INFERNAL_ASHES =(25778, 25779, 110.0D)
MALICIOUS_ASHES =(25772, 25773, 65.0D)
VILE_ASHES =(25769, 25770, 25.0D)
Private Attributes
final double experience
final int id
final int id2
Detailed Description
Definition at line 6 of file AshData.java.
Constructor & Destructor Documentation
AshData()
com.runehive.content.skill.impl.prayer.AshData.AshData (int id, int noted, double experience)
Definition at line 17 of file AshData.java.
{
        this.id = id;
        this.id2 = noted;
        this.experience = experience;
    }
References experience, and id.
Member Function Documentation
forId()
Optional< AshData > com.runehive.content.skill.impl.prayer.AshData.forId (int id) static
Definition at line 32 of file AshData.java.
{
        return Arrays.stream(values()).filter(a -> a.id == id).findAny();
    }
Referenced by com.runehive.content.skill.impl.prayer.BoneSacrifice.clickItem(), and com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop().
getExperience()
double com.runehive.content.skill.impl.prayer.AshData.getExperience ()
Definition at line 29 of file AshData.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.handleAshSanctifier().
getId()
int com.runehive.content.skill.impl.prayer.AshData.getId ()
Definition at line 23 of file AshData.java.
                       {
        return id;
    }
References id.
getId2()
int com.runehive.content.skill.impl.prayer.AshData.getId2 ()
Definition at line 26 of file AshData.java.
{
        return id2;
    }
References id2.
Member Data Documentation
ABYSSAL_ASHES
com.runehive.content.skill.impl.prayer.AshData.ABYSSAL_ASHES =(25775, 25776,85.0D)
Definition at line 10 of file AshData.java.
experience
final double com.runehive.content.skill.impl.prayer.AshData.experience private
Definition at line 15 of file AshData.java.
Referenced by AshData(), and getExperience().
FIENDISH_ASHES
com.runehive.content.skill.impl.prayer.AshData.FIENDISH_ASHES =(25766, 25767, 10.0D)
Definition at line 7 of file AshData.java.
id
final int com.runehive.content.skill.impl.prayer.AshData.id private
Definition at line 13 of file AshData.java.
Referenced by AshData(), and getId().
id2
final int com.runehive.content.skill.impl.prayer.AshData.id2 private
Definition at line 14 of file AshData.java.
Referenced by getId2().
INFERNAL_ASHES
com.runehive.content.skill.impl.prayer.AshData.INFERNAL_ASHES =(25778, 25779, 110.0D)
Definition at line 11 of file AshData.java.
MALICIOUS_ASHES
com.runehive.content.skill.impl.prayer.AshData.MALICIOUS_ASHES =(25772, 25773, 65.0D)
Definition at line 9 of file AshData.java.
VILE_ASHES
com.runehive.content.skill.impl.prayer.AshData.VILE_ASHES =(25769, 25770, 25.0D)
Definition at line 8 of file AshData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/prayer/AshData.java