RuneHive-Game: com.runehive.content.skill.impl.fletching.impl.Battlestaff Enum Reference
com.runehive.content.skill.impl.fletching.impl.Battlestaff Enum Reference
Public Member Functions
Battlestaff (Item use, Item with, FletchableItem... items)
int getAnimation ()
FletchableItem[] getFletchableItems ()
int getGraphics ()
Item[] getIngredients ()
String getProductionMessage ()
Item getUse ()
Item getWith ()
Static Public Member Functions
static void load ()
Public Attributes
AIR_BATTLESTAFF =(new Item(1391, 1), new Item(573, 1), new FletchableItem(new Item(1397, 1), 66, 137.5))
EARTH_BATTLESTAFF =(new Item(1391, 1), new Item(575, 1), new FletchableItem(new Item(1399, 1), 58, 112.5))
FIRE_BATTLESTAFF =(new Item(1391, 1), new Item(569, 1), new FletchableItem(new Item(1393, 1), 62, 125.0))
WATER_BATTLESTAFF =(new Item(1391, 1), new Item(571, 1), new FletchableItem(new Item(1395, 1), 54, 100.0))
Private Attributes
final FletchableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 8 of file Battlestaff.java.
Constructor & Destructor Documentation
Battlestaff()
com.runehive.content.skill.impl.fletching.impl.Battlestaff.Battlestaff (Item use, Item with, FletchableItem... items)
Definition at line 18 of file Battlestaff.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.fletching.impl.Battlestaff.getAnimation ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 31 of file Battlestaff.java.
{
        return 7531;
    }
getFletchableItems()
FletchableItem[] com.runehive.content.skill.impl.fletching.impl.Battlestaff.getFletchableItems ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 61 of file Battlestaff.java.
{
        return items;
    }
References items.
getGraphics()
int com.runehive.content.skill.impl.fletching.impl.Battlestaff.getGraphics ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 36 of file Battlestaff.java.
{
        switch (this) {
            case WATER_BATTLESTAFF:
                return 1370;
            case EARTH_BATTLESTAFF:
                return 1371;
            case FIRE_BATTLESTAFF:
                return 1372;
            case AIR_BATTLESTAFF:
            default:
                return 306;
        }
    }
References AIR_BATTLESTAFF, EARTH_BATTLESTAFF, FIRE_BATTLESTAFF, and WATER_BATTLESTAFF.
getIngredients()
Item[] com.runehive.content.skill.impl.fletching.impl.Battlestaff.getIngredients ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 71 of file Battlestaff.java.
{
        return new Item[] { use, with };
    }
References use, and with.
getProductionMessage()
String com.runehive.content.skill.impl.fletching.impl.Battlestaff.getProductionMessage ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 66 of file Battlestaff.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.fletching.impl.Battlestaff.getUse ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 51 of file Battlestaff.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.fletching.impl.Battlestaff.getWith ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 56 of file Battlestaff.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.fletching.impl.Battlestaff.load () static
Definition at line 24 of file Battlestaff.java.
{
        for (Battlestaff battlestaff : values()) {
            Fletching.addFletchable(battlestaff);
        }
    }
References com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), and Battlestaff().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
AIR_BATTLESTAFF
com.runehive.content.skill.impl.fletching.impl.Battlestaff.AIR_BATTLESTAFF =(new Item(1391, 1), new Item(573, 1), new FletchableItem(new Item(1397, 1), 66, 137.5))
Definition at line 11 of file Battlestaff.java.
Referenced by getGraphics().
EARTH_BATTLESTAFF
com.runehive.content.skill.impl.fletching.impl.Battlestaff.EARTH_BATTLESTAFF =(new Item(1391, 1), new Item(575, 1), new FletchableItem(new Item(1399, 1), 58, 112.5))
Definition at line 12 of file Battlestaff.java.
Referenced by getGraphics().
FIRE_BATTLESTAFF
com.runehive.content.skill.impl.fletching.impl.Battlestaff.FIRE_BATTLESTAFF =(new Item(1391, 1), new Item(569, 1), new FletchableItem(new Item(1393, 1), 62, 125.0))
Definition at line 9 of file Battlestaff.java.
Referenced by getGraphics().
items
final FletchableItem [] com.runehive.content.skill.impl.fletching.impl.Battlestaff.items private
Definition at line 16 of file Battlestaff.java.
Referenced by Battlestaff(), and getFletchableItems().
use
final Item com.runehive.content.skill.impl.fletching.impl.Battlestaff.use private
Definition at line 14 of file Battlestaff.java.
Referenced by Battlestaff(), getIngredients(), and getUse().
WATER_BATTLESTAFF
com.runehive.content.skill.impl.fletching.impl.Battlestaff.WATER_BATTLESTAFF =(new Item(1391, 1), new Item(571, 1), new FletchableItem(new Item(1395, 1), 54, 100.0))
Definition at line 10 of file Battlestaff.java.
Referenced by getGraphics().
with
final Item com.runehive.content.skill.impl.fletching.impl.Battlestaff.with private
Definition at line 15 of file Battlestaff.java.
Referenced by Battlestaff(), getIngredients(), and getWith().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fletching/impl/Battlestaff.java