RuneHive-Game: com.runehive.content.donators.DonatorBond Enum Reference
com.runehive.content.donators.DonatorBond Enum Reference
Holds all the donator bond data.
Public Member Functions
DonatorBond (int item, int moneySpent, int credits)
Constructs a new DonatorBond.
Static Public Member Functions
static DonatorBond forId (int item)
Gets the bond data based on the item provided.
Public Attributes
BOND_10 =(13190, 10, 100)
BOND_100 =(13192, 100, 1000)
BOND_200 =(13193, 200, 2000)
BOND_50 =(13191, 50, 500)
BOND_500 =(13194, 500, 5000)
final int credits
The amount of credits this bond will give.
final int item
The item identification of the donator bond.
final int moneySpent
The amount of money spent that was required for this bond.
Detailed Description
Holds all the donator bond data.
Author
Daniel.
Definition at line 8 of file DonatorBond.java.
Constructor & Destructor Documentation
DonatorBond()
com.runehive.content.donators.DonatorBond.DonatorBond (int item, int moneySpent, int credits)
Constructs a new DonatorBond.
Definition at line 25 of file DonatorBond.java.
{
        this.item = item;
        this.moneySpent = moneySpent;
        this.credits = credits;
    }
References credits, item, and moneySpent.
Referenced by forId().
Member Function Documentation
forId()
DonatorBond com.runehive.content.donators.DonatorBond.forId (int item) static
Gets the bond data based on the item provided.
Definition at line 32 of file DonatorBond.java.
{
        for (DonatorBond bond : values()) {
            if (bond.item == item)
                return bond;
        }
        return null;
    }
References DonatorBond(), and item.
Member Data Documentation
BOND_10
com.runehive.content.donators.DonatorBond.BOND_10 =(13190, 10, 100)
Definition at line 9 of file DonatorBond.java.
Referenced by com.runehive.game.service.DonationService.claimDonation().
BOND_100
com.runehive.content.donators.DonatorBond.BOND_100 =(13192, 100, 1000)
Definition at line 11 of file DonatorBond.java.
Referenced by com.runehive.game.service.DonationService.claimDonation().
BOND_200
com.runehive.content.donators.DonatorBond.BOND_200 =(13193, 200, 2000)
Definition at line 12 of file DonatorBond.java.
Referenced by com.runehive.game.service.DonationService.claimDonation().
BOND_50
com.runehive.content.donators.DonatorBond.BOND_50 =(13191, 50, 500)
Definition at line 10 of file DonatorBond.java.
Referenced by com.runehive.game.service.DonationService.claimDonation().
BOND_500
com.runehive.content.donators.DonatorBond.BOND_500 =(13194, 500, 5000)
Definition at line 13 of file DonatorBond.java.
Referenced by com.runehive.game.service.DonationService.claimDonation().
credits
final int com.runehive.content.donators.DonatorBond.credits
The amount of credits this bond will give.
Definition at line 22 of file DonatorBond.java.
Referenced by DonatorBond(), and com.runehive.content.donators.Donation.redeem().
item
final int com.runehive.content.donators.DonatorBond.item
The item identification of the donator bond.
Definition at line 16 of file DonatorBond.java.
Referenced by DonatorBond(), and forId().
moneySpent
final int com.runehive.content.donators.DonatorBond.moneySpent
The amount of money spent that was required for this bond.
Definition at line 19 of file DonatorBond.java.
Referenced by DonatorBond(), and com.runehive.content.donators.Donation.redeem().
The documentation for this enum was generated from the following file:
java/com/runehive/content/donators/DonatorBond.java