RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Hide Enum Reference
com.runehive.content.skill.impl.crafting.impl.Hide Enum Reference
Public Member Functions
int getAnimation ()
Gets the craftable animation.
CraftableItem[] getCraftableItems ()
Gets the craftable items.
Item[] getIngredients (int index)
Gets the craftable ingredients.
String getName ()
Gets the craftable name.
String getProductionMessage ()
Gets the craftable production message.
Item getUse ()
Gets the craftable used item.
Item getWith ()
Gets the craftable item used with.
Hide (Item use, Item with, CraftableItem... items)
Static Public Member Functions
static int[] getDisplay (int id)
static void load ()
Public Attributes
BLACK_DRAGONHIDE
BLUE_DRAGONHIDE
GREEN_DRAGONHIDE
HARDLEATHER_BODY
RED_DRAGONHIDE
SNAKESIN
YAK_HIDE
Private Attributes
final CraftableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 12 of file Hide.java.
Constructor & Destructor Documentation
Hide()
com.runehive.content.skill.impl.crafting.impl.Hide.Hide (Item use, Item with, CraftableItem... items)
Definition at line 45 of file Hide.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by getDisplay(), and load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.crafting.impl.Hide.getAnimation ()
Gets the craftable animation.
Returns
The craftable animation.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 76 of file Hide.java.
{
        return 1249;
    }
getCraftableItems()
CraftableItem[] com.runehive.content.skill.impl.crafting.impl.Hide.getCraftableItems ()
Gets the craftable items.
Returns
The craftable items.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 91 of file Hide.java.
{
        return items;
    }
References items.
getDisplay()
int[] com.runehive.content.skill.impl.crafting.impl.Hide.getDisplay (int id) static
Definition at line 57 of file Hide.java.
{
        List<Integer> list = new ArrayList<>();
        for (Hide hide : values()) {
            if (hide.getIngredients(0)[0].getId() == id) {
                list.add(hide.getCraftableItems()[0].getProduct().getId());
            }
        }
        int[] ids = new int[list.size()];
        for (int i = 0; i < list.size(); i++) {
            ids[i] = list.get(i);
        }
        return ids;
    }
References Hide().
getIngredients()
Item[] com.runehive.content.skill.impl.crafting.impl.Hide.getIngredients (int index)
Gets the craftable ingredients.
Parameters
index The ingredient index.
Returns
The craftable ingredients.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 101 of file Hide.java.
{
        return new Item[] { new Item(1734, items[index].getRequiredItem().getAmount()), items[index].getRequiredItem()};
    }
References items.
getName()
String com.runehive.content.skill.impl.crafting.impl.Hide.getName ()
Gets the craftable name.
Returns
The craftable name.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 106 of file Hide.java.
{
        return "Hide";
    }
getProductionMessage()
String com.runehive.content.skill.impl.crafting.impl.Hide.getProductionMessage ()
Gets the craftable production message.
Returns
The craftable production message.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 96 of file Hide.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.crafting.impl.Hide.getUse ()
Gets the craftable used item.
Returns
The craftable used item.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 81 of file Hide.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.crafting.impl.Hide.getWith ()
Gets the craftable item used with.
Returns
The craftable item used with.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 86 of file Hide.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.crafting.impl.Hide.load () static
Definition at line 51 of file Hide.java.
{
        for (Hide cuttable : values()) {
            Crafting.addCraftable(cuttable);
        }
    }
References com.runehive.content.skill.impl.crafting.Crafting.addCraftable(), and Hide().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
BLACK_DRAGONHIDE
com.runehive.content.skill.impl.crafting.impl.Hide.BLACK_DRAGONHIDE
Initial value:
=(new Item(1733), new Item(2509),
            new CraftableItem(new Item(2503), new Item(2509, 3), 84, 258.0),
            new CraftableItem(new Item(2491), new Item(2509, 1), 79, 86.0),
            new CraftableItem(new Item(2497), new Item(2509, 2), 82, 172.0))
Definition at line 25 of file Hide.java.
BLUE_DRAGONHIDE
com.runehive.content.skill.impl.crafting.impl.Hide.BLUE_DRAGONHIDE
Initial value:
=(new Item(1733), new Item(2505),
            new CraftableItem(new Item(2499), new Item(2505, 3), 71, 210.0),
            new CraftableItem(new Item(2487), new Item(2505, 1), 66, 70.0),
            new CraftableItem(new Item(2493), new Item(2505, 2), 68, 140.0))
Definition at line 17 of file Hide.java.
GREEN_DRAGONHIDE
com.runehive.content.skill.impl.crafting.impl.Hide.GREEN_DRAGONHIDE
Initial value:
=(new Item(1733), new Item(1745),
            new CraftableItem(new Item(1135), new Item(1745, 3), 63, 186.0),
            new CraftableItem(new Item(1065), new Item(1745, 1), 57, 62.0),
            new CraftableItem(new Item(1099), new Item(1745, 2), 60, 124.0))
Definition at line 13 of file Hide.java.
HARDLEATHER_BODY
com.runehive.content.skill.impl.crafting.impl.Hide.HARDLEATHER_BODY
Initial value:
=(new Item(1733), new Item(1743),
            new CraftableItem(new Item(1131), new Item(1743), 28, 35.0))
Definition at line 39 of file Hide.java.
items
final CraftableItem [] com.runehive.content.skill.impl.crafting.impl.Hide.items private
Definition at line 43 of file Hide.java.
Referenced by getCraftableItems(), getIngredients(), and Hide().
RED_DRAGONHIDE
com.runehive.content.skill.impl.crafting.impl.Hide.RED_DRAGONHIDE
Initial value:
=(new Item(1733), new Item(2507),
            new CraftableItem(new Item(2501), new Item(2507, 3), 77, 234.0),
            new CraftableItem(new Item(2489), new Item(2507, 1), 76, 78.0),
            new CraftableItem(new Item(2495), new Item(2507, 2), 75, 156.0))
Definition at line 21 of file Hide.java.
SNAKESIN
com.runehive.content.skill.impl.crafting.impl.Hide.SNAKESIN
Initial value:
=(new Item(1733), new Item(6289),
            new CraftableItem(new Item(6322), new Item(6289, 15), 82, 3 + 2/3.0),
            new CraftableItem(new Item(6324), new Item(6289, 12), 79, 4 + 1/6.0),
            new CraftableItem(new Item(6330), new Item(6289, 8), 79, 4 + 3/8.0),
            new CraftableItem(new Item(6326), new Item(6289, 5), 79, 9.0),
            new CraftableItem(new Item(6328), new Item(6289, 6), 84, 5.0))
Definition at line 29 of file Hide.java.
use
final Item com.runehive.content.skill.impl.crafting.impl.Hide.use private
Definition at line 41 of file Hide.java.
Referenced by getUse(), and Hide().
with
final Item com.runehive.content.skill.impl.crafting.impl.Hide.with private
Definition at line 42 of file Hide.java.
Referenced by getWith(), and Hide().
YAK_HIDE
com.runehive.content.skill.impl.crafting.impl.Hide.YAK_HIDE
Initial value:
=(new Item(1733), new Item(10818),
            new CraftableItem(new Item(10822), new Item(10818), 43, 32.0),
            new CraftableItem(new Item(10824), new Item(10818, 2), 46, 32.0))
Definition at line 35 of file Hide.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Hide.java