RuneHive-Game: com.runehive.content.prestige.PrestigePerk Enum Reference
com.runehive.content.prestige.PrestigePerk Enum Reference
Handles the perk rewards from prestiging.
Public Member Functions
PrestigePerk (String name, String description, int item)
Constructs a new PrestigePerk.
Static Public Member Functions
[static initializer]
static PrestigePerk forId (int id)
static PrestigePerk forItem (int item)
Public Attributes
ARROWHEAD =("Arrowhead", "Using arrows will not break.", 6798)
final String description
The description of the perk.
DOUBLE_WOOD =("Double wood", "15% chance to receive an additional log.", 6800)
FLAME_ON =("Flame On", "25% chance of burning an extra log.", 6803)
final int item
The item identification of the perk.
LITTLE_BIRDY =("Little Birdy", "Increase the woodcutting rate of bird nest drops by 15%.", 6801)
MASTERBAIRTER =("Masterbaiter", "15% chance of catching extra fish.", 6799)
final String name
The name of the perk.
THE_ROCK =("The Rock", "10% chance to receive an additional ore.", 6802)
Static Public Attributes
static final PrestigePerk[] values = values()
Static Private Attributes
static final Map< Integer, PrestigePerk > perkIdMap
static final Map< Integer, PrestigePerk > perkItemMap
Detailed Description
Handles the perk rewards from prestiging.
Author
Daniel.
Definition at line 13 of file PrestigePerk.java.
Constructor & Destructor Documentation
PrestigePerk()
com.runehive.content.prestige.PrestigePerk.PrestigePerk (String name, String description, int item)
Constructs a new PrestigePerk.
Definition at line 55 of file PrestigePerk.java.
{
        this.name = name;
        this.description = description;
        this.item = item;
    }
References description, item, and name.
Referenced by [static initializer](), forId(), and forItem().
Member Function Documentation
[static initializer]()
com.runehive.content.prestige.PrestigePerk.[static initializer] static
References perkIdMap, perkItemMap, PrestigePerk(), and values.
forId()
PrestigePerk com.runehive.content.prestige.PrestigePerk.forId (int id) static
Definition at line 65 of file PrestigePerk.java.
{
        return perkIdMap.get(id);
    }
References perkIdMap, and PrestigePerk().
Referenced by com.runehive.content.prestige.Prestige.perkInformation().
forItem()
PrestigePerk com.runehive.content.prestige.PrestigePerk.forItem (int item) static
Definition at line 61 of file PrestigePerk.java.
{
        return perkItemMap.get(item);
    }
References item, perkItemMap, and PrestigePerk().
Referenced by com.runehive.content.prestige.Prestige.activatePerk().
Member Data Documentation
ARROWHEAD
com.runehive.content.prestige.PrestigePerk.ARROWHEAD =("Arrowhead", "Using arrows will not break.", 6798)
Definition at line 14 of file PrestigePerk.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition().
description
final String com.runehive.content.prestige.PrestigePerk.description
The description of the perk.
Definition at line 45 of file PrestigePerk.java.
Referenced by com.runehive.content.prestige.Prestige.perkInformation(), and PrestigePerk().
DOUBLE_WOOD
com.runehive.content.prestige.PrestigePerk.DOUBLE_WOOD =("Double wood", "15% chance to receive an additional log.", 6800)
Definition at line 16 of file PrestigePerk.java.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
FLAME_ON
com.runehive.content.prestige.PrestigePerk.FLAME_ON =("Flame On", "25% chance of burning an extra log.", 6803)
Definition at line 19 of file PrestigePerk.java.
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), and com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct().
item
final int com.runehive.content.prestige.PrestigePerk.item
The item identification of the perk.
Definition at line 50 of file PrestigePerk.java.
Referenced by forItem(), and PrestigePerk().
LITTLE_BIRDY
com.runehive.content.prestige.PrestigePerk.LITTLE_BIRDY =("Little Birdy", "Increase the woodcutting rate of bird nest drops by 15%.", 6801)
Definition at line 17 of file PrestigePerk.java.
Referenced by com.runehive.content.skill.impl.woodcutting.BirdsNest.drop().
MASTERBAIRTER
com.runehive.content.prestige.PrestigePerk.MASTERBAIRTER =("Masterbaiter", "15% chance of catching extra fish.", 6799)
Definition at line 15 of file PrestigePerk.java.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish().
name
final String com.runehive.content.prestige.PrestigePerk.name
The name of the perk.
Definition at line 40 of file PrestigePerk.java.
Referenced by com.runehive.content.prestige.Prestige.activatePerk(), com.runehive.content.prestige.Prestige.perkInformation(), and PrestigePerk().
perkIdMap
final Map<Integer, PrestigePerk> com.runehive.content.prestige.PrestigePerk.perkIdMap static private
Definition at line 23 of file PrestigePerk.java.
Referenced by [static initializer](), and forId().
perkItemMap
final Map<Integer, PrestigePerk> com.runehive.content.prestige.PrestigePerk.perkItemMap static private
Definition at line 22 of file PrestigePerk.java.
Referenced by [static initializer](), and forItem().
THE_ROCK
com.runehive.content.prestige.PrestigePerk.THE_ROCK =("The Rock", "10% chance to receive an additional ore.", 6802)
Definition at line 18 of file PrestigePerk.java.
Referenced by com.runehive.content.skill.impl.mining.MiningAction.mine().
values
final PrestigePerk [] com.runehive.content.prestige.PrestigePerk.values = values() static
Definition at line 21 of file PrestigePerk.java.
Referenced by [static initializer](), and com.runehive.content.prestige.Prestige.perkInformation().
The documentation for this enum was generated from the following file:
java/com/runehive/content/prestige/PrestigePerk.java