RuneHive-Game: com.runehive.content.skill.impl.thieving.StallData Enum Reference
com.runehive.content.skill.impl.thieving.StallData Enum Reference
Holds all the data for thieving stalls.
Public Member Functions
int getExperience ()
Gets the experience rewarded.
Item getItem ()
Gets the item reward.
int getLevel ()
Gets the level required.
int getObject ()
Gets the object identification.
int getValue ()
Gets the reward value.
StallData (int object, Item item, int level, int experience, int value)
Constructs a new StallData
Static Public Member Functions
static Optional< StallData > forId (int id)
Gets the stall data base off object identification.
static final int getValue (Item item)
Gets the value of the reward.
static boolean isReward (Item item)
Checks if the item is a reward.
Public Attributes
CRAFTING =(4874, new Item(1635), 40, 125, 1453)
FOOD =(4875, new Item(3162), 1, 25, 275)
GENERAL =(4876, new Item(1887), 20, 50, 760)
RUNES =(4877, new Item(8788), 50, 250, 2546)
SCIMITAR =(4878, new Item(686), 80, 500, 3860)
Private Attributes
final int experience
The experience rewarded.
final Item item
The item rewarded.
final int level
The level required.
final int object
The object identification.
final int value
The item value.
Detailed Description
Holds all the data for thieving stalls.
Author
Daniel
Definition at line 13 of file StallData.java.
Constructor & Destructor Documentation
StallData()
com.runehive.content.skill.impl.thieving.StallData.StallData (int object, Item item, int level, int experience, int value)
Constructs a new StallData
Definition at line 36 of file StallData.java.
{
        this.object = object;
        this.item = item;
        this.level = level;
        this.experience = experience;
        this.value = value;
    }
References experience, item, level, object, and value.
Member Function Documentation
forId()
Optional< StallData > com.runehive.content.skill.impl.thieving.StallData.forId (int id) static
Gets the stall data base off object identification.
Definition at line 70 of file StallData.java.
{
        return Arrays.stream(values()).filter(a -> a.object == id).findAny();
    }
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickObject().
getExperience()
int com.runehive.content.skill.impl.thieving.StallData.getExperience ()
Gets the experience rewarded.
Definition at line 65 of file StallData.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickObject().
getItem()
Item com.runehive.content.skill.impl.thieving.StallData.getItem ()
Gets the item reward.
Definition at line 50 of file StallData.java.
{
        return item;
    }
References item.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickObject().
getLevel()
int com.runehive.content.skill.impl.thieving.StallData.getLevel ()
Gets the level required.
Definition at line 55 of file StallData.java.
{
        return level;
    }
References level.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickObject().
getObject()
int com.runehive.content.skill.impl.thieving.StallData.getObject ()
Gets the object identification.
Definition at line 45 of file StallData.java.
{
        return object;
    }
References object.
getValue() [1/2]
int com.runehive.content.skill.impl.thieving.StallData.getValue ()
Gets the reward value.
Definition at line 60 of file StallData.java.
{
        return value;
    }
References value.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.exchange().
getValue() [2/2]
final int com.runehive.content.skill.impl.thieving.StallData.getValue (Item item) static
Gets the value of the reward.
Definition at line 82 of file StallData.java.
{
        return Arrays.stream(values()).filter(i -> i.getItem().getId() == item.getId()).findAny().get().getValue();
    }
References item.
isReward()
boolean com.runehive.content.skill.impl.thieving.StallData.isReward (Item item) static
Checks if the item is a reward.
Definition at line 75 of file StallData.java.
{
        if (item == null)
            return false;
        return Arrays.stream(values()).anyMatch(i -> i.getItem().getId() == item.getId());
    }
References item.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.exchange().
Member Data Documentation
CRAFTING
com.runehive.content.skill.impl.thieving.StallData.CRAFTING =(4874, new Item(1635), 40, 125, 1453)
Definition at line 16 of file StallData.java.
experience
final int com.runehive.content.skill.impl.thieving.StallData.experience private
The experience rewarded.
Definition at line 30 of file StallData.java.
Referenced by getExperience(), and StallData().
FOOD
com.runehive.content.skill.impl.thieving.StallData.FOOD =(4875, new Item(3162), 1, 25, 275)
Definition at line 14 of file StallData.java.
GENERAL
com.runehive.content.skill.impl.thieving.StallData.GENERAL =(4876, new Item(1887), 20, 50, 760)
Definition at line 15 of file StallData.java.
item
final Item com.runehive.content.skill.impl.thieving.StallData.item private
The item rewarded.
Definition at line 24 of file StallData.java.
Referenced by getItem(), getValue(), isReward(), and StallData().
level
final int com.runehive.content.skill.impl.thieving.StallData.level private
The level required.
Definition at line 27 of file StallData.java.
Referenced by getLevel(), and StallData().
object
final int com.runehive.content.skill.impl.thieving.StallData.object private
The object identification.
Definition at line 21 of file StallData.java.
Referenced by getObject(), and StallData().
RUNES
com.runehive.content.skill.impl.thieving.StallData.RUNES =(4877, new Item(8788), 50, 250, 2546)
Definition at line 17 of file StallData.java.
SCIMITAR
com.runehive.content.skill.impl.thieving.StallData.SCIMITAR =(4878, new Item(686), 80, 500, 3860)
Definition at line 18 of file StallData.java.
value
final int com.runehive.content.skill.impl.thieving.StallData.value private
The item value.
Definition at line 33 of file StallData.java.
Referenced by getValue(), and StallData().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/thieving/StallData.java