RuneHive-Game: com.runehive.content.clanchannel.content.ClanTask Enum Reference
com.runehive.content.clanchannel.content.ClanTask Enum Reference
Holds all the clan task data.
Public Member Functions
ClanTask (ClanType type, Difficulty difficulty, String task, ClanTaskKey key, InclusiveRandom amount)
int getAmount ()
String getName (ClanChannel channel)
double getProgressExperience ()
int getReward ()
Static Public Member Functions
static ClanTask getAssignment (ClanType type, Difficulty difficulty)
static Set< ClanTask > getTasks (ClanType type, Difficulty difficulty)
Public Attributes
final InclusiveRandom amount
BURN_YEW_LOG =(ClanType.SKILLING, Difficulty.EASY, "Burn % willow logs", BURN_WILLOW_LOG, new InclusiveRandom(300, 500))
CATCH_ANGLERFISH =(ClanType.SKILLING, Difficulty.HARD, "Catch % dark crabs", DARK_CRAB, new InclusiveRandom(750, 1000))
CATCH_SHARK =(ClanType.SKILLING, Difficulty.MEDIUM, "Catch % sharks", SHARK, new InclusiveRandom(500, 750))
CHOP_MAGIC =(ClanType.SKILLING, Difficulty.HARD, "Chop % magic logs", MAGIC_LOG, new InclusiveRandom(600, 800))
CHOP_WILLOW =(ClanType.SKILLING, Difficulty.EASY, "Chop % willow logs", CHOP_WILLOW_LOG, new InclusiveRandom(300, 500))
CHOP_YEW =(ClanType.SKILLING, Difficulty.MEDIUM, "Chop % yew logs", YEW_LOG, new InclusiveRandom(500, 750))
COMPLETE_AGILITY_LAP_I =(ClanType.SKILLING, Difficulty.EASY, "Complete % non-rooftop course", AGILITY_COURSE, new InclusiveRandom(300, 500))
COMPLETE_AGILITY_LAP_II =(ClanType.SKILLING, Difficulty.MEDIUM, "Complete % non-rooftop course", AGILITY_COURSE, new InclusiveRandom(500, 750))
COMPLETE_AGILITY_LAP_III =(ClanType.SKILLING, Difficulty.HARD, "Complete % non-rooftop course", AGILITY_COURSE, new InclusiveRandom(750, 1000))
CRAFT_BLOOD_RUNE =(ClanType.SKILLING, Difficulty.HARD, "Craft % blood runes", BLOOD_RUNE, new InclusiveRandom(750, 1000))
CRAFT_DEATH_RUNE =(ClanType.SKILLING, Difficulty.MEDIUM, "Craft % death runes", DEATH_RUNE, new InclusiveRandom(500, 750))
CREATE_SUPER_RESTORE_POTION =(ClanType.SKILLING, Difficulty.MEDIUM, "Create % super restore potions", SUPER_RESTORE_POTION, new InclusiveRandom(500, 750))
final Difficulty difficulty
FLETCH_MAGIC_SHORTBOW =(ClanType.SKILLING, Difficulty.HARD, "Fletch % magic shortbow", MAGIC_SHORTBOW, new InclusiveRandom(1250, 2000))
FLETCH_YEW_SHORTBOW =(ClanType.SKILLING, Difficulty.MEDIUM, "Fletch % yew shortbow", YEW_SHORTBOW, new InclusiveRandom(500, 750))
final ClanTaskKey key
KILL_ABYSSAL_DEMONS =(ClanType.PVM, Difficulty.HARD, "Kill % abyssal demons", ABYSSAL_DEMON, new InclusiveRandom(250, 500))
KILL_BABY_BLUE_DRAGON =(ClanType.PVM, Difficulty.EASY, "Kill % baby blue dragons", BABY_BLUE_DRAGON, new InclusiveRandom(100, 200))
KILL_BANSHEE =(ClanType.PVM, Difficulty.EASY, "Kill % banshees", BANSHEE, new InclusiveRandom(100, 200))
KILL_BASILISK =(ClanType.PVM, Difficulty.MEDIUM, "Kill % basilisks", BASILISK, new InclusiveRandom(150, 250))
KILL_BAT =(ClanType.PVM, Difficulty.EASY, "Kill % bats", BAT, new InclusiveRandom(100, 200))
KILL_BLACK_DEMONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % black demons", BLACK_DEMON, new InclusiveRandom(150, 250))
KILL_BLACK_DRAGONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % black dragons", BLACK_DRAGON, new InclusiveRandom(151, 250))
KILL_BLACK_KNIGHT =(ClanType.PVM, Difficulty.EASY, "Kill % black knights", BLACK_KNIGHT, new InclusiveRandom(100, 200))
KILL_BLOODVELD =(ClanType.PVM, Difficulty.MEDIUM, "Kill % bloodvels", BLOODVELD, new InclusiveRandom(150, 250))
KILL_BLUE_DRAGONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % blue dragons", BLUE_DRAGON, new InclusiveRandom(151, 250))
KILL_CALLISTO =(ClanType.PVM, Difficulty.HARD, "Kill % callistos", CALLISTO, new InclusiveRandom(25, 75))
KILL_CAVE_CRAWLER =(ClanType.PVM, Difficulty.EASY, "Kill % cave crawlers", CAVE_CRAWLER, new InclusiveRandom(100, 200))
KILL_CAVE_HORROR =(ClanType.PVM, Difficulty.MEDIUM, "Kill % cave horrors", CAVE_HORROR, new InclusiveRandom(150, 250))
KILL_CHAOS_DWARF =(ClanType.PVM, Difficulty.EASY, "Kill % chaos dwarves", CHAOS_DWARF, new InclusiveRandom(100, 200))
KILL_CHAOS_FANATIC =(ClanType.PVM, Difficulty.HARD, "Kill % chaos fanatics", CHAOS_FANATIC, new InclusiveRandom(25, 75))
KILL_COCKATRICE =(ClanType.PVM, Difficulty.MEDIUM, "Kill % cockatrices", COCKATRICE, new InclusiveRandom(150, 250))
KILL_COMMANDER_ZILYANA =(ClanType.PVM, Difficulty.HARD, "Kill % commander zilyanas", COMMANDER_ZILYANA, new InclusiveRandom(25, 75))
KILL_CRAWLING_HAND =(ClanType.PVM, Difficulty.EASY, "Kill % crawling hands", CRAWLING_HAND, new InclusiveRandom(100, 200))
KILL_CRAZY_ARCHAEOLOGIST =(ClanType.PVM, Difficulty.HARD, "Kill % crazy archaeologists", CRAZY_ARCHAEOLOGIST, new InclusiveRandom(50, 200))
KILL_DEMONIC_GORILLA =(ClanType.PVM, Difficulty.HARD, "Kill % demonic gorillas", DEMONIC_GORILLA, new InclusiveRandom(50, 100))
KILL_DUST_DEVIL =(ClanType.PVM, Difficulty.MEDIUM, "Kill % dust devils", DUST_DEVIL, new InclusiveRandom(100, 300))
KILL_FIRE_GIANT =(ClanType.PVM, Difficulty.MEDIUM, "Kill % fire giants", FIRE_GIANT, new InclusiveRandom(150, 250))
KILL_GENERAL_GRAARDOR =(ClanType.PVM, Difficulty.HARD, "Kill % general graardors", GENERAL_GRAARDOR, new InclusiveRandom(25, 75))
KILL_GHOST =(ClanType.PVM, Difficulty.EASY, "Kill % ghosts", GHOST, new InclusiveRandom(100, 200))
KILL_GREATER_DEMONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % greater demons", GREATER_DEMON, new InclusiveRandom(150, 250))
KILL_GREEN_DRAGONS_I =(ClanType.PVM, Difficulty.MEDIUM, "Kill % green dragons", GREEN_DRAGON, new InclusiveRandom(50, 150))
KILL_GREEN_DRAGONS_II =(ClanType.PVM, Difficulty.MEDIUM, "Kill % green dragons", GREEN_DRAGON, new InclusiveRandom(151, 250))
KILL_HELLHOUND =(ClanType.PVM, Difficulty.MEDIUM, "Kill % hellhounds", HELLHOUND, new InclusiveRandom(150, 250))
KILL_HILL_GIANTS =(ClanType.PVM, Difficulty.EASY, "Kill % hill giants", HILL_GIANT, new InclusiveRandom(100, 200))
PvM.
KILL_ICE_FIEND =(ClanType.PVM, Difficulty.EASY, "Kill % ice fiends", ICE_FIEND, new InclusiveRandom(100, 200))
KILL_KING_BLACK_DRAGONS =(ClanType.PVM, Difficulty.HARD, "Kill % king black dragons", KING_BLACK_DRAGON, new InclusiveRandom(50, 200))
KILL_KREEARRA =(ClanType.PVM, Difficulty.HARD, "Kill % kree'arras", KREEARRA, new InclusiveRandom(25, 75))
KILL_KRIL_TSUTSAROTH =(ClanType.PVM, Difficulty.HARD, "Kill % k'ril tsutsaroths", KRIL_TSUTSAROTH, new InclusiveRandom(25, 75))
KILL_LIZARD_SHAMAN =(ClanType.PVM, Difficulty.HARD, "Kill % lizard shamans", LIZARD_SHAMAN, new InclusiveRandom(50, 100))
KILL_MAGIC_AXE =(ClanType.PVM, Difficulty.EASY, "Kill % magic axes", MAGIC_AXE, new InclusiveRandom(100, 200))
KILL_MYTHRIL_DRAGON =(ClanType.PVM, Difficulty.HARD, "Kill % king black dragons", KING_BLACK_DRAGON, new InclusiveRandom(25, 100))
KILL_NECHRYAEL =(ClanType.PVM, Difficulty.HARD, "Kill % nachryaels", NECHRYAEL, new InclusiveRandom(50, 100))
KILL_PLAYERS_I =(ClanType.PVP, Difficulty.EASY, "Kill % players", PLAYER_KILLING, new InclusiveRandom(10, 25))
PvP.
KILL_PLAYERS_II =(ClanType.PVP, Difficulty.MEDIUM, "Kill % players", PLAYER_KILLING, new InclusiveRandom(25, 50))
KILL_PLAYERS_III =(ClanType.PVP, Difficulty.HARD, "Kill % players", PLAYER_KILLING, new InclusiveRandom(50, 125))
KILL_PYRE_FIEND =(ClanType.PVM, Difficulty.MEDIUM, "Kill % pyre fiends", PYRE_FIEND, new InclusiveRandom(150, 250))
KILL_RED_DRAGONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % red dragons", RED_DRAGON, new InclusiveRandom(151, 250))
KILL_ROCK_CRABS =(ClanType.PVM, Difficulty.EASY, "Kill % rock crabs", ROCK_CRAB, new InclusiveRandom(100, 200))
KILL_SAND_CRABS =(ClanType.PVM, Difficulty.EASY, "Kill % sand crabs", SAND_CRAB, new InclusiveRandom(100, 200))
KILL_SCORPIA =(ClanType.PVM, Difficulty.HARD, "Kill % scorpias", SCORPIA, new InclusiveRandom(25, 75))
KILL_SKELETAL_WYVERNS =(ClanType.PVM, Difficulty.HARD, "Kill % skeletal wyverns", SKELETAL_WYVERN, new InclusiveRandom(250, 500))
KILL_SKELETON =(ClanType.PVM, Difficulty.EASY, "Kill % skeletons", SKELETON, new InclusiveRandom(100, 200))
KILL_SMOKE_DEVIL =(ClanType.PVM, Difficulty.HARD, "Kill % smoke devils", SMOKE_DEVIL, new InclusiveRandom(50, 100))
KILL_SPIRITUAL_MAGE =(ClanType.PVM, Difficulty.HARD, "Kill % spiritual mages", SPIRITUAL_MAGE, new InclusiveRandom(25, 75))
KILL_SPIRITUAL_RANGER =(ClanType.PVM, Difficulty.MEDIUM, "Kill % spiritual rangers", SPIRITUAL_RANGER, new InclusiveRandom(150, 250))
KILL_SPIRITUAL_WARRIOR =(ClanType.PVM, Difficulty.MEDIUM, "Kill % spiritual warriors", SPIRITUAL_WARRIOR, new InclusiveRandom(150, 250))
KILL_STEEL_DRAGON =(ClanType.PVM, Difficulty.MEDIUM, "Kill % steel dragons", STEEL_DRAGON, new InclusiveRandom(150, 250))
KILL_VENENATIS =(ClanType.PVM, Difficulty.HARD, "Kill % venenatis", VENNANTIS, new InclusiveRandom(25, 75))
KILL_VETION =(ClanType.PVM, Difficulty.HARD, "Kill % vet'ions", VETION, new InclusiveRandom(25, 75))
MINE_RUNITE_ORE =(ClanType.SKILLING, Difficulty.HARD, "Mine % runite ores", RUNITE_ORES, new InclusiveRandom(650, 900))
final String task
THIEVE_FROM_STALL_I =(ClanType.SKILLING, Difficulty.EASY, "Thieve from stall % times", THIEVING_STALL, new InclusiveRandom(300, 500))
Skilling.
THIEVE_FROM_STALL_II =(ClanType.SKILLING, Difficulty.MEDIUM, "Thieve from stall % times", THIEVING_STALL, new InclusiveRandom(500, 750))
final ClanType type
Detailed Description
Holds all the clan task data.
Author
Daniel
Definition at line 18 of file ClanTask.java.
Constructor & Destructor Documentation
ClanTask()
com.runehive.content.clanchannel.content.ClanTask.ClanTask (ClanType type, Difficulty difficulty, String task, ClanTaskKey key, InclusiveRandom amount)
Definition at line 122 of file ClanTask.java.
{
        this.task = task;
        this.key = key;
        this.amount = amount;
        this.difficulty = difficulty;
        this.type = type;
    }
References amount, difficulty, key, task, and type.
Referenced by getAssignment(), and getTasks().
Member Function Documentation
getAmount()
int com.runehive.content.clanchannel.content.ClanTask.getAmount ()
Definition at line 146 of file ClanTask.java.
{
        return Utility.random(amount.minimum, amount.maximum);
    }
References amount, and com.runehive.util.Utility.random().
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.receiveTask().
getAssignment()
ClanTask com.runehive.content.clanchannel.content.ClanTask.getAssignment (ClanType type, Difficulty difficulty) static
Definition at line 159 of file ClanTask.java.
{
        if (type == ClanType.SOCIAL) {
            Set<ClanTask> tasks = new HashSet<>();
            tasks.addAll(getTasks(ClanType.PVM, difficulty));
            tasks.addAll(getTasks(ClanType.PVP, difficulty));
            tasks.addAll(getTasks(ClanType.SKILLING, difficulty));
            return Utility.randomElement(tasks);
        }
        if (type == ClanType.IRON_MAN) {
            Set<ClanTask> tasks = new HashSet<>();
            tasks.addAll(getTasks(ClanType.PVM, difficulty));
            tasks.addAll(getTasks(ClanType.SKILLING, difficulty));
            return Utility.randomElement(tasks);
        }
        return Utility.randomElement(getTasks(type, difficulty));
    }
References ClanTask(), difficulty, getTasks(), com.runehive.content.clanchannel.ClanType.IRON_MAN, com.runehive.content.clanchannel.ClanType.PVM, com.runehive.content.clanchannel.ClanType.PVP, com.runehive.util.Utility.randomElement(), com.runehive.content.clanchannel.ClanType.SKILLING, com.runehive.content.clanchannel.ClanType.SOCIAL, and type.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.receiveTask().
getName()
String com.runehive.content.clanchannel.content.ClanTask.getName (ClanChannel channel)
Definition at line 142 of file ClanTask.java.
{
        return task.replace("%", "" + channel.getDetails().taskAmount);
    }
References task.
Referenced by com.runehive.content.dialogue.impl.ClanmasterDialogue.clanTask(), and com.runehive.content.clanchannel.channel.ClanChannel.receiveTask().
getProgressExperience()
double com.runehive.content.clanchannel.content.ClanTask.getProgressExperience ()
Definition at line 130 of file ClanTask.java.
{
        switch (type) {
            case PVP:
                return 1250;
            case PVM:
                return difficulty == Difficulty.HARD ? 350 : 50;
            case SKILLING:
                return 5;
        }
        return 0;
    }
References difficulty, com.runehive.util.Difficulty.HARD, and type.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask().
getReward()
int com.runehive.content.clanchannel.content.ClanTask.getReward ()
Definition at line 178 of file ClanTask.java.
{
        return (difficulty == Difficulty.EASY) ? 2 : (difficulty == Difficulty.MEDIUM) ? 3 : 5;
    }
References difficulty, com.runehive.util.Difficulty.EASY, and com.runehive.util.Difficulty.MEDIUM.
getTasks()
Set< ClanTask > com.runehive.content.clanchannel.content.ClanTask.getTasks (ClanType type, Difficulty difficulty) static
Definition at line 150 of file ClanTask.java.
{
        Set<ClanTask> tasks = new HashSet<>();
        for (ClanTask task : values()) {
            if (task.type == type && task.difficulty == difficulty)
                tasks.add(task);
        }
        return tasks;
    }
References ClanTask(), difficulty, task, and type.
Referenced by getAssignment().
Member Data Documentation
amount
final InclusiveRandom com.runehive.content.clanchannel.content.ClanTask.amount
Definition at line 118 of file ClanTask.java.
Referenced by ClanTask(), and getAmount().
BURN_YEW_LOG
com.runehive.content.clanchannel.content.ClanTask.BURN_YEW_LOG =(ClanType.SKILLING, Difficulty.EASY, "Burn % willow logs", BURN_WILLOW_LOG, new InclusiveRandom(300, 500))
Definition at line 95 of file ClanTask.java.
CATCH_ANGLERFISH
com.runehive.content.clanchannel.content.ClanTask.CATCH_ANGLERFISH =(ClanType.SKILLING, Difficulty.HARD, "Catch % dark crabs", DARK_CRAB, new InclusiveRandom(750, 1000))
Definition at line 112 of file ClanTask.java.
CATCH_SHARK
com.runehive.content.clanchannel.content.ClanTask.CATCH_SHARK =(ClanType.SKILLING, Difficulty.MEDIUM, "Catch % sharks", SHARK, new InclusiveRandom(500, 750))
Definition at line 98 of file ClanTask.java.
CHOP_MAGIC
com.runehive.content.clanchannel.content.ClanTask.CHOP_MAGIC =(ClanType.SKILLING, Difficulty.HARD, "Chop % magic logs", MAGIC_LOG, new InclusiveRandom(600, 800))
Definition at line 114 of file ClanTask.java.
CHOP_WILLOW
com.runehive.content.clanchannel.content.ClanTask.CHOP_WILLOW =(ClanType.SKILLING, Difficulty.EASY, "Chop % willow logs", CHOP_WILLOW_LOG, new InclusiveRandom(300, 500))
Definition at line 93 of file ClanTask.java.
CHOP_YEW
com.runehive.content.clanchannel.content.ClanTask.CHOP_YEW =(ClanType.SKILLING, Difficulty.MEDIUM, "Chop % yew logs", YEW_LOG, new InclusiveRandom(500, 750))
Definition at line 99 of file ClanTask.java.
COMPLETE_AGILITY_LAP_I
com.runehive.content.clanchannel.content.ClanTask.COMPLETE_AGILITY_LAP_I =(ClanType.SKILLING, Difficulty.EASY, "Complete % non-rooftop course", AGILITY_COURSE, new InclusiveRandom(300, 500))
Definition at line 94 of file ClanTask.java.
COMPLETE_AGILITY_LAP_II
com.runehive.content.clanchannel.content.ClanTask.COMPLETE_AGILITY_LAP_II =(ClanType.SKILLING, Difficulty.MEDIUM, "Complete % non-rooftop course", AGILITY_COURSE, new InclusiveRandom(500, 750))
Definition at line 103 of file ClanTask.java.
COMPLETE_AGILITY_LAP_III
com.runehive.content.clanchannel.content.ClanTask.COMPLETE_AGILITY_LAP_III =(ClanType.SKILLING, Difficulty.HARD, "Complete % non-rooftop course", AGILITY_COURSE, new InclusiveRandom(750, 1000))
Definition at line 111 of file ClanTask.java.
CRAFT_BLOOD_RUNE
com.runehive.content.clanchannel.content.ClanTask.CRAFT_BLOOD_RUNE =(ClanType.SKILLING, Difficulty.HARD, "Craft % blood runes", BLOOD_RUNE, new InclusiveRandom(750, 1000))
Definition at line 113 of file ClanTask.java.
CRAFT_DEATH_RUNE
com.runehive.content.clanchannel.content.ClanTask.CRAFT_DEATH_RUNE =(ClanType.SKILLING, Difficulty.MEDIUM, "Craft % death runes", DEATH_RUNE, new InclusiveRandom(500, 750))
Definition at line 101 of file ClanTask.java.
CREATE_SUPER_RESTORE_POTION
com.runehive.content.clanchannel.content.ClanTask.CREATE_SUPER_RESTORE_POTION =(ClanType.SKILLING, Difficulty.MEDIUM, "Create % super restore potions", SUPER_RESTORE_POTION, new InclusiveRandom(500, 750))
Definition at line 102 of file ClanTask.java.
difficulty
final Difficulty com.runehive.content.clanchannel.content.ClanTask.difficulty
Definition at line 119 of file ClanTask.java.
Referenced by ClanTask(), getAssignment(), getProgressExperience(), getReward(), and getTasks().
FLETCH_MAGIC_SHORTBOW
com.runehive.content.clanchannel.content.ClanTask.FLETCH_MAGIC_SHORTBOW =(ClanType.SKILLING, Difficulty.HARD, "Fletch % magic shortbow", MAGIC_SHORTBOW, new InclusiveRandom(1250, 2000))
Definition at line 108 of file ClanTask.java.
FLETCH_YEW_SHORTBOW
com.runehive.content.clanchannel.content.ClanTask.FLETCH_YEW_SHORTBOW =(ClanType.SKILLING, Difficulty.MEDIUM, "Fletch % yew shortbow", YEW_SHORTBOW, new InclusiveRandom(500, 750))
Definition at line 100 of file ClanTask.java.
key
final ClanTaskKey com.runehive.content.clanchannel.content.ClanTask.key
Definition at line 117 of file ClanTask.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask(), and ClanTask().
KILL_ABYSSAL_DEMONS
com.runehive.content.clanchannel.content.ClanTask.KILL_ABYSSAL_DEMONS =(ClanType.PVM, Difficulty.HARD, "Kill % abyssal demons", ABYSSAL_DEMON, new InclusiveRandom(250, 500))
Definition at line 68 of file ClanTask.java.
KILL_BABY_BLUE_DRAGON
com.runehive.content.clanchannel.content.ClanTask.KILL_BABY_BLUE_DRAGON =(ClanType.PVM, Difficulty.EASY, "Kill % baby blue dragons", BABY_BLUE_DRAGON, new InclusiveRandom(100, 200))
Definition at line 38 of file ClanTask.java.
KILL_BANSHEE
com.runehive.content.clanchannel.content.ClanTask.KILL_BANSHEE =(ClanType.PVM, Difficulty.EASY, "Kill % banshees", BANSHEE, new InclusiveRandom(100, 200))
Definition at line 44 of file ClanTask.java.
KILL_BASILISK
com.runehive.content.clanchannel.content.ClanTask.KILL_BASILISK =(ClanType.PVM, Difficulty.MEDIUM, "Kill % basilisks", BASILISK, new InclusiveRandom(150, 250))
Definition at line 60 of file ClanTask.java.
KILL_BAT
com.runehive.content.clanchannel.content.ClanTask.KILL_BAT =(ClanType.PVM, Difficulty.EASY, "Kill % bats", BAT, new InclusiveRandom(100, 200))
Definition at line 39 of file ClanTask.java.
KILL_BLACK_DEMONS
com.runehive.content.clanchannel.content.ClanTask.KILL_BLACK_DEMONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % black demons", BLACK_DEMON, new InclusiveRandom(150, 250))
Definition at line 49 of file ClanTask.java.
KILL_BLACK_DRAGONS
com.runehive.content.clanchannel.content.ClanTask.KILL_BLACK_DRAGONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % black dragons", BLACK_DRAGON, new InclusiveRandom(151, 250))
Definition at line 52 of file ClanTask.java.
KILL_BLACK_KNIGHT
com.runehive.content.clanchannel.content.ClanTask.KILL_BLACK_KNIGHT =(ClanType.PVM, Difficulty.EASY, "Kill % black knights", BLACK_KNIGHT, new InclusiveRandom(100, 200))
Definition at line 37 of file ClanTask.java.
KILL_BLOODVELD
com.runehive.content.clanchannel.content.ClanTask.KILL_BLOODVELD =(ClanType.PVM, Difficulty.MEDIUM, "Kill % bloodvels", BLOODVELD, new InclusiveRandom(150, 250))
Definition at line 65 of file ClanTask.java.
KILL_BLUE_DRAGONS
com.runehive.content.clanchannel.content.ClanTask.KILL_BLUE_DRAGONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % blue dragons", BLUE_DRAGON, new InclusiveRandom(151, 250))
Definition at line 51 of file ClanTask.java.
KILL_CALLISTO
com.runehive.content.clanchannel.content.ClanTask.KILL_CALLISTO =(ClanType.PVM, Difficulty.HARD, "Kill % callistos", CALLISTO, new InclusiveRandom(25, 75))
Definition at line 73 of file ClanTask.java.
KILL_CAVE_CRAWLER
com.runehive.content.clanchannel.content.ClanTask.KILL_CAVE_CRAWLER =(ClanType.PVM, Difficulty.EASY, "Kill % cave crawlers", CAVE_CRAWLER, new InclusiveRandom(100, 200))
Definition at line 42 of file ClanTask.java.
KILL_CAVE_HORROR
com.runehive.content.clanchannel.content.ClanTask.KILL_CAVE_HORROR =(ClanType.PVM, Difficulty.MEDIUM, "Kill % cave horrors", CAVE_HORROR, new InclusiveRandom(150, 250))
Definition at line 56 of file ClanTask.java.
KILL_CHAOS_DWARF
com.runehive.content.clanchannel.content.ClanTask.KILL_CHAOS_DWARF =(ClanType.PVM, Difficulty.EASY, "Kill % chaos dwarves", CHAOS_DWARF, new InclusiveRandom(100, 200))
Definition at line 40 of file ClanTask.java.
KILL_CHAOS_FANATIC
com.runehive.content.clanchannel.content.ClanTask.KILL_CHAOS_FANATIC =(ClanType.PVM, Difficulty.HARD, "Kill % chaos fanatics", CHAOS_FANATIC, new InclusiveRandom(25, 75))
Definition at line 75 of file ClanTask.java.
KILL_COCKATRICE
com.runehive.content.clanchannel.content.ClanTask.KILL_COCKATRICE =(ClanType.PVM, Difficulty.MEDIUM, "Kill % cockatrices", COCKATRICE, new InclusiveRandom(150, 250))
Definition at line 61 of file ClanTask.java.
KILL_COMMANDER_ZILYANA
com.runehive.content.clanchannel.content.ClanTask.KILL_COMMANDER_ZILYANA =(ClanType.PVM, Difficulty.HARD, "Kill % commander zilyanas", COMMANDER_ZILYANA, new InclusiveRandom(25, 75))
Definition at line 85 of file ClanTask.java.
KILL_CRAWLING_HAND
com.runehive.content.clanchannel.content.ClanTask.KILL_CRAWLING_HAND =(ClanType.PVM, Difficulty.EASY, "Kill % crawling hands", CRAWLING_HAND, new InclusiveRandom(100, 200))
Definition at line 43 of file ClanTask.java.
KILL_CRAZY_ARCHAEOLOGIST
com.runehive.content.clanchannel.content.ClanTask.KILL_CRAZY_ARCHAEOLOGIST =(ClanType.PVM, Difficulty.HARD, "Kill % crazy archaeologists", CRAZY_ARCHAEOLOGIST, new InclusiveRandom(50, 200))
Definition at line 74 of file ClanTask.java.
KILL_DEMONIC_GORILLA
com.runehive.content.clanchannel.content.ClanTask.KILL_DEMONIC_GORILLA =(ClanType.PVM, Difficulty.HARD, "Kill % demonic gorillas", DEMONIC_GORILLA, new InclusiveRandom(50, 100))
Definition at line 82 of file ClanTask.java.
KILL_DUST_DEVIL
com.runehive.content.clanchannel.content.ClanTask.KILL_DUST_DEVIL =(ClanType.PVM, Difficulty.MEDIUM, "Kill % dust devils", DUST_DEVIL, new InclusiveRandom(100, 300))
Definition at line 62 of file ClanTask.java.
KILL_FIRE_GIANT
com.runehive.content.clanchannel.content.ClanTask.KILL_FIRE_GIANT =(ClanType.PVM, Difficulty.MEDIUM, "Kill % fire giants", FIRE_GIANT, new InclusiveRandom(150, 250))
Definition at line 59 of file ClanTask.java.
KILL_GENERAL_GRAARDOR
com.runehive.content.clanchannel.content.ClanTask.KILL_GENERAL_GRAARDOR =(ClanType.PVM, Difficulty.HARD, "Kill % general graardors", GENERAL_GRAARDOR, new InclusiveRandom(25, 75))
Definition at line 84 of file ClanTask.java.
KILL_GHOST
com.runehive.content.clanchannel.content.ClanTask.KILL_GHOST =(ClanType.PVM, Difficulty.EASY, "Kill % ghosts", GHOST, new InclusiveRandom(100, 200))
Definition at line 35 of file ClanTask.java.
KILL_GREATER_DEMONS
com.runehive.content.clanchannel.content.ClanTask.KILL_GREATER_DEMONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % greater demons", GREATER_DEMON, new InclusiveRandom(150, 250))
Definition at line 50 of file ClanTask.java.
KILL_GREEN_DRAGONS_I
com.runehive.content.clanchannel.content.ClanTask.KILL_GREEN_DRAGONS_I =(ClanType.PVM, Difficulty.MEDIUM, "Kill % green dragons", GREEN_DRAGON, new InclusiveRandom(50, 150))
Definition at line 34 of file ClanTask.java.
KILL_GREEN_DRAGONS_II
com.runehive.content.clanchannel.content.ClanTask.KILL_GREEN_DRAGONS_II =(ClanType.PVM, Difficulty.MEDIUM, "Kill % green dragons", GREEN_DRAGON, new InclusiveRandom(151, 250))
Definition at line 54 of file ClanTask.java.
KILL_HELLHOUND
com.runehive.content.clanchannel.content.ClanTask.KILL_HELLHOUND =(ClanType.PVM, Difficulty.MEDIUM, "Kill % hellhounds", HELLHOUND, new InclusiveRandom(150, 250))
Definition at line 55 of file ClanTask.java.
KILL_HILL_GIANTS
com.runehive.content.clanchannel.content.ClanTask.KILL_HILL_GIANTS =(ClanType.PVM, Difficulty.EASY, "Kill % hill giants", HILL_GIANT, new InclusiveRandom(100, 200))
PvM.
Definition at line 31 of file ClanTask.java.
KILL_ICE_FIEND
com.runehive.content.clanchannel.content.ClanTask.KILL_ICE_FIEND =(ClanType.PVM, Difficulty.EASY, "Kill % ice fiends", ICE_FIEND, new InclusiveRandom(100, 200))
Definition at line 45 of file ClanTask.java.
KILL_KING_BLACK_DRAGONS
com.runehive.content.clanchannel.content.ClanTask.KILL_KING_BLACK_DRAGONS =(ClanType.PVM, Difficulty.HARD, "Kill % king black dragons", KING_BLACK_DRAGON, new InclusiveRandom(50, 200))
Definition at line 70 of file ClanTask.java.
KILL_KREEARRA
com.runehive.content.clanchannel.content.ClanTask.KILL_KREEARRA =(ClanType.PVM, Difficulty.HARD, "Kill % kree'arras", KREEARRA, new InclusiveRandom(25, 75))
Definition at line 86 of file ClanTask.java.
KILL_KRIL_TSUTSAROTH
com.runehive.content.clanchannel.content.ClanTask.KILL_KRIL_TSUTSAROTH =(ClanType.PVM, Difficulty.HARD, "Kill % k'ril tsutsaroths", KRIL_TSUTSAROTH, new InclusiveRandom(25, 75))
Definition at line 87 of file ClanTask.java.
KILL_LIZARD_SHAMAN
com.runehive.content.clanchannel.content.ClanTask.KILL_LIZARD_SHAMAN =(ClanType.PVM, Difficulty.HARD, "Kill % lizard shamans", LIZARD_SHAMAN, new InclusiveRandom(50, 100))
Definition at line 83 of file ClanTask.java.
KILL_MAGIC_AXE
com.runehive.content.clanchannel.content.ClanTask.KILL_MAGIC_AXE =(ClanType.PVM, Difficulty.EASY, "Kill % magic axes", MAGIC_AXE, new InclusiveRandom(100, 200))
Definition at line 41 of file ClanTask.java.
KILL_MYTHRIL_DRAGON
com.runehive.content.clanchannel.content.ClanTask.KILL_MYTHRIL_DRAGON =(ClanType.PVM, Difficulty.HARD, "Kill % king black dragons", KING_BLACK_DRAGON, new InclusiveRandom(25, 100))
Definition at line 79 of file ClanTask.java.
KILL_NECHRYAEL
com.runehive.content.clanchannel.content.ClanTask.KILL_NECHRYAEL =(ClanType.PVM, Difficulty.HARD, "Kill % nachryaels", NECHRYAEL, new InclusiveRandom(50, 100))
Definition at line 80 of file ClanTask.java.
KILL_PLAYERS_I
com.runehive.content.clanchannel.content.ClanTask.KILL_PLAYERS_I =(ClanType.PVP, Difficulty.EASY, "Kill % players", PLAYER_KILLING, new InclusiveRandom(10, 25))
PvP.
Definition at line 21 of file ClanTask.java.
KILL_PLAYERS_II
com.runehive.content.clanchannel.content.ClanTask.KILL_PLAYERS_II =(ClanType.PVP, Difficulty.MEDIUM, "Kill % players", PLAYER_KILLING, new InclusiveRandom(25, 50))
Definition at line 24 of file ClanTask.java.
KILL_PLAYERS_III
com.runehive.content.clanchannel.content.ClanTask.KILL_PLAYERS_III =(ClanType.PVP, Difficulty.HARD, "Kill % players", PLAYER_KILLING, new InclusiveRandom(50, 125))
Definition at line 27 of file ClanTask.java.
KILL_PYRE_FIEND
com.runehive.content.clanchannel.content.ClanTask.KILL_PYRE_FIEND =(ClanType.PVM, Difficulty.MEDIUM, "Kill % pyre fiends", PYRE_FIEND, new InclusiveRandom(150, 250))
Definition at line 58 of file ClanTask.java.
KILL_RED_DRAGONS
com.runehive.content.clanchannel.content.ClanTask.KILL_RED_DRAGONS =(ClanType.PVM, Difficulty.MEDIUM, "Kill % red dragons", RED_DRAGON, new InclusiveRandom(151, 250))
Definition at line 53 of file ClanTask.java.
KILL_ROCK_CRABS
com.runehive.content.clanchannel.content.ClanTask.KILL_ROCK_CRABS =(ClanType.PVM, Difficulty.EASY, "Kill % rock crabs", ROCK_CRAB, new InclusiveRandom(100, 200))
Definition at line 32 of file ClanTask.java.
KILL_SAND_CRABS
com.runehive.content.clanchannel.content.ClanTask.KILL_SAND_CRABS =(ClanType.PVM, Difficulty.EASY, "Kill % sand crabs", SAND_CRAB, new InclusiveRandom(100, 200))
Definition at line 33 of file ClanTask.java.
KILL_SCORPIA
com.runehive.content.clanchannel.content.ClanTask.KILL_SCORPIA =(ClanType.PVM, Difficulty.HARD, "Kill % scorpias", SCORPIA, new InclusiveRandom(25, 75))
Definition at line 71 of file ClanTask.java.
KILL_SKELETAL_WYVERNS
com.runehive.content.clanchannel.content.ClanTask.KILL_SKELETAL_WYVERNS =(ClanType.PVM, Difficulty.HARD, "Kill % skeletal wyverns", SKELETAL_WYVERN, new InclusiveRandom(250, 500))
Definition at line 69 of file ClanTask.java.
KILL_SKELETON
com.runehive.content.clanchannel.content.ClanTask.KILL_SKELETON =(ClanType.PVM, Difficulty.EASY, "Kill % skeletons", SKELETON, new InclusiveRandom(100, 200))
Definition at line 36 of file ClanTask.java.
KILL_SMOKE_DEVIL
com.runehive.content.clanchannel.content.ClanTask.KILL_SMOKE_DEVIL =(ClanType.PVM, Difficulty.HARD, "Kill % smoke devils", SMOKE_DEVIL, new InclusiveRandom(50, 100))
Definition at line 81 of file ClanTask.java.
KILL_SPIRITUAL_MAGE
com.runehive.content.clanchannel.content.ClanTask.KILL_SPIRITUAL_MAGE =(ClanType.PVM, Difficulty.HARD, "Kill % spiritual mages", SPIRITUAL_MAGE, new InclusiveRandom(25, 75))
Definition at line 77 of file ClanTask.java.
KILL_SPIRITUAL_RANGER
com.runehive.content.clanchannel.content.ClanTask.KILL_SPIRITUAL_RANGER =(ClanType.PVM, Difficulty.MEDIUM, "Kill % spiritual rangers", SPIRITUAL_RANGER, new InclusiveRandom(150, 250))
Definition at line 63 of file ClanTask.java.
KILL_SPIRITUAL_WARRIOR
com.runehive.content.clanchannel.content.ClanTask.KILL_SPIRITUAL_WARRIOR =(ClanType.PVM, Difficulty.MEDIUM, "Kill % spiritual warriors", SPIRITUAL_WARRIOR, new InclusiveRandom(150, 250))
Definition at line 64 of file ClanTask.java.
KILL_STEEL_DRAGON
com.runehive.content.clanchannel.content.ClanTask.KILL_STEEL_DRAGON =(ClanType.PVM, Difficulty.MEDIUM, "Kill % steel dragons", STEEL_DRAGON, new InclusiveRandom(150, 250))
Definition at line 57 of file ClanTask.java.
KILL_VENENATIS
com.runehive.content.clanchannel.content.ClanTask.KILL_VENENATIS =(ClanType.PVM, Difficulty.HARD, "Kill % venenatis", VENNANTIS, new InclusiveRandom(25, 75))
Definition at line 72 of file ClanTask.java.
KILL_VETION
com.runehive.content.clanchannel.content.ClanTask.KILL_VETION =(ClanType.PVM, Difficulty.HARD, "Kill % vet'ions", VETION, new InclusiveRandom(25, 75))
Definition at line 78 of file ClanTask.java.
MINE_RUNITE_ORE
com.runehive.content.clanchannel.content.ClanTask.MINE_RUNITE_ORE =(ClanType.SKILLING, Difficulty.HARD, "Mine % runite ores", RUNITE_ORES, new InclusiveRandom(650, 900))
Definition at line 109 of file ClanTask.java.
task
final String com.runehive.content.clanchannel.content.ClanTask.task
Definition at line 116 of file ClanTask.java.
Referenced by ClanTask(), getName(), and getTasks().
THIEVE_FROM_STALL_I
com.runehive.content.clanchannel.content.ClanTask.THIEVE_FROM_STALL_I =(ClanType.SKILLING, Difficulty.EASY, "Thieve from stall % times", THIEVING_STALL, new InclusiveRandom(300, 500))
Skilling.
Definition at line 92 of file ClanTask.java.
THIEVE_FROM_STALL_II
com.runehive.content.clanchannel.content.ClanTask.THIEVE_FROM_STALL_II =(ClanType.SKILLING, Difficulty.MEDIUM, "Thieve from stall % times", THIEVING_STALL, new InclusiveRandom(500, 750))
Definition at line 104 of file ClanTask.java.
type
final ClanType com.runehive.content.clanchannel.content.ClanTask.type
Definition at line 120 of file ClanTask.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask(), ClanTask(), getAssignment(), getProgressExperience(), and getTasks().
The documentation for this enum was generated from the following file:
java/com/runehive/content/clanchannel/content/ClanTask.java