RuneHive-Game: com.runehive.content.skill.impl.fishing.FishingTool Enum Reference
com.runehive.content.skill.impl.fishing.FishingTool Enum Reference
Public Member Functions
FishingTool (int toolId, int animation, short[] outcomes)
int getAnimationId ()
short[] getOutcomes ()
int getToolId ()
Static Public Member Functions
static void declare ()
static FishingTool forId (int id)
Public Attributes
BIG_NET =(305, 621, new short[]{353, 341, 363})
CRAYFISH_CAGE =(13431, 619, new short[]{13435})
DRAGON_HARPOON =(21028, 618, new short[]{359, 371})
DRAGON_HARPOON2 =(21029, 618, new short[]{359, 371})
FISHING_ROD =(307, 622, new short[]{327, 345, 349, 3379, 5001, 2148})
FLYFISHING_ROD =(309, 622, new short[]{335, 331})
HARPOON =(311, 618, new short[]{359, 371})
KARAMBWAN_POT =(3157, -1, new short[]{3142})
LOBSTER_POT =(301, 619, new short[]{377})
SMALL_NET =(303, 621, new short[]{317, 3150, 321, 5004, 7994})
Private Attributes
int animation
short[] outcomes
int toolId
Static Private Attributes
static Map< Integer, FishingTool > tools = new HashMap<>()
Detailed Description
Definition at line 6 of file FishingTool.java.
Constructor & Destructor Documentation
FishingTool()
com.runehive.content.skill.impl.fishing.FishingTool.FishingTool (int toolId, int animation, short[] outcomes)
Definition at line 29 of file FishingTool.java.
{
        this.toolId = toolId;
        this.outcomes = outcomes;
        this.animation = animation;
    }
References animation, outcomes, and toolId.
Referenced by declare(), and forId().
Member Function Documentation
declare()
void com.runehive.content.skill.impl.fishing.FishingTool.declare () static
Definition at line 24 of file FishingTool.java.
{
        for (FishingTool tool : values())
            tools.put(tool.getToolId(), tool);
    }
References FishingTool(), and tools.
Referenced by com.runehive.content.skill.SkillRepository.load().
forId()
FishingTool com.runehive.content.skill.impl.fishing.FishingTool.forId (int id) static
Definition at line 47 of file FishingTool.java.
{
        return tools.get(id);
    }
References FishingTool(), and tools.
Referenced by com.runehive.content.skill.impl.fishing.Fishing.start().
getAnimationId()
int com.runehive.content.skill.impl.fishing.FishingTool.getAnimationId ()
Definition at line 35 of file FishingTool.java.
{
        return animation;
    }
References animation.
getOutcomes()
short[] com.runehive.content.skill.impl.fishing.FishingTool.getOutcomes ()
Definition at line 39 of file FishingTool.java.
{
        return outcomes;
    }
References outcomes.
getToolId()
int com.runehive.content.skill.impl.fishing.FishingTool.getToolId ()
Definition at line 43 of file FishingTool.java.
{
        return toolId;
    }
References toolId.
Member Data Documentation
animation
int com.runehive.content.skill.impl.fishing.FishingTool.animation private
Definition at line 19 of file FishingTool.java.
Referenced by FishingTool(), and getAnimationId().
BIG_NET
com.runehive.content.skill.impl.fishing.FishingTool.BIG_NET =(305, 621, new short[]{353, 341, 363})
Definition at line 8 of file FishingTool.java.
CRAYFISH_CAGE
com.runehive.content.skill.impl.fishing.FishingTool.CRAYFISH_CAGE =(13431, 619, new short[]{13435})
Definition at line 9 of file FishingTool.java.
DRAGON_HARPOON
com.runehive.content.skill.impl.fishing.FishingTool.DRAGON_HARPOON =(21028, 618, new short[]{359, 371})
Definition at line 14 of file FishingTool.java.
DRAGON_HARPOON2
com.runehive.content.skill.impl.fishing.FishingTool.DRAGON_HARPOON2 =(21029, 618, new short[]{359, 371})
Definition at line 15 of file FishingTool.java.
FISHING_ROD
com.runehive.content.skill.impl.fishing.FishingTool.FISHING_ROD =(307, 622, new short[]{327, 345, 349, 3379, 5001, 2148})
Definition at line 10 of file FishingTool.java.
FLYFISHING_ROD
com.runehive.content.skill.impl.fishing.FishingTool.FLYFISHING_ROD =(309, 622, new short[]{335, 331})
Definition at line 11 of file FishingTool.java.
HARPOON
com.runehive.content.skill.impl.fishing.FishingTool.HARPOON =(311, 618, new short[]{359, 371})
Definition at line 13 of file FishingTool.java.
KARAMBWAN_POT
com.runehive.content.skill.impl.fishing.FishingTool.KARAMBWAN_POT =(3157, -1, new short[]{3142})
Definition at line 12 of file FishingTool.java.
LOBSTER_POT
com.runehive.content.skill.impl.fishing.FishingTool.LOBSTER_POT =(301, 619, new short[]{377})
Definition at line 16 of file FishingTool.java.
outcomes
short [] com.runehive.content.skill.impl.fishing.FishingTool.outcomes private
Definition at line 20 of file FishingTool.java.
Referenced by FishingTool(), and getOutcomes().
SMALL_NET
com.runehive.content.skill.impl.fishing.FishingTool.SMALL_NET =(303, 621, new short[]{317, 3150, 321, 5004, 7994})
Definition at line 7 of file FishingTool.java.
toolId
int com.runehive.content.skill.impl.fishing.FishingTool.toolId private
Definition at line 18 of file FishingTool.java.
Referenced by FishingTool(), and getToolId().
tools
Map<Integer, FishingTool> com.runehive.content.skill.impl.fishing.FishingTool.tools = new HashMap<>() static private
Definition at line 22 of file FishingTool.java.
Referenced by declare(), and forId().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fishing/FishingTool.java