RuneHive-Game: com.runehive.content.activity.impl.barrows.BrotherData Enum Reference
com.runehive.content.activity.impl.barrows.BrotherData Enum Reference
Public Member Functions
BrotherData (int npcId, Position southWest, Position northEast, Position hillPosition, Position cryptPosition)
Position getCryptPosition ()
Gets the position of the crypt.
Position getHillPosition ()
Gets the position of the hill.
Position getNorthEast ()
Gets the Position that has to be dug to get into the crypt.
int getNpcId ()
Gets the npc id of the barrows brother.
Position getSouthWest ()
Gets the Position that has to be dug to get into the crypt.
Static Public Member Functions
static BrotherData getBarrowsBrother (Npc mob)
static boolean isBarrowsBrother (Npc mob)
Public Attributes
AHRIM =(1672, new Position(3562, 3285), new Position(3568, 3291), new Position(3565, 3288), new Position(3557, 9703, 3))
DHAROK =(1673, new Position(3573, 3295), new Position(3578, 3300), new Position(3575, 3298), new Position(3556, 9718, 3))
GUTHAN =(1674, new Position(3575, 3279), new Position(3580, 3286), new Position(3577, 3282), new Position(3534, 9704, 3))
KARIL =(1675, new Position(3563, 3273), new Position(3568, 3278), new Position(3566, 3275), new Position(3546, 9684, 3))
TORAG =(1676, new Position(3551, 3279), new Position(3556, 3285), new Position(3554, 3282), new Position(3568, 9683, 3))
VERAC =(1677, new Position(3554, 3293), new Position(3560, 3301), new Position(3557, 3297), new Position(3578, 9706, 3))
Private Attributes
Position cryptPosition
The position of the crypt.
Position hillPosition
The position of the hill.
Position northEast
The Position that has to be dug to get into the crypt.
int npcId
The npc id of the barrows brother.
Position southWest
The Position that has to be dug to get into the crypt.
Detailed Description
Definition at line 6 of file BrotherData.java.
Constructor & Destructor Documentation
BrotherData()
com.runehive.content.activity.impl.barrows.BrotherData.BrotherData (int npcId, Position southWest, Position northEast, Position hillPosition, Position cryptPosition)
Definition at line 29 of file BrotherData.java.
{
        this.npcId = npcId;
        this.southWest = southWest;
        this.northEast = northEast;
        this.hillPosition = hillPosition;
        this.cryptPosition = cryptPosition;
    }
References cryptPosition, hillPosition, northEast, npcId, and southWest.
Referenced by getBarrowsBrother(), and isBarrowsBrother().
Member Function Documentation
getBarrowsBrother()
BrotherData com.runehive.content.activity.impl.barrows.BrotherData.getBarrowsBrother (Npc mob) static
Definition at line 91 of file BrotherData.java.
{
        for (BrotherData brother : values()) {
            if (brother.getNpcId() == mob.id) {
                return brother;
            }
        }
        return null;
    }
References BrotherData(), and com.runehive.game.world.entity.mob.Mob.id.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.onDeath().
getCryptPosition()
Position com.runehive.content.activity.impl.barrows.BrotherData.getCryptPosition ()
Gets the position of the crypt.
Returns
the position of the crypt.
Definition at line 78 of file BrotherData.java.
{
        return cryptPosition;
    }
References cryptPosition.
getHillPosition()
Position com.runehive.content.activity.impl.barrows.BrotherData.getHillPosition ()
Gets the position of the hill.
Returns
the position of the hill.
Definition at line 69 of file BrotherData.java.
{
        return hillPosition;
    }
References hillPosition.
getNorthEast()
Position com.runehive.content.activity.impl.barrows.BrotherData.getNorthEast ()
Gets the Position that has to be dug to get into the crypt.
Returns
the Position that has to be dug to get into the crypt.
Definition at line 60 of file BrotherData.java.
{
        return northEast;
    }
References northEast.
getNpcId()
int com.runehive.content.activity.impl.barrows.BrotherData.getNpcId ()
Gets the npc id of the barrows brother.
Returns
the npc id of the barrows brother.
Definition at line 42 of file BrotherData.java.
{
        return npcId;
    }
References npcId.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.summon().
getSouthWest()
Position com.runehive.content.activity.impl.barrows.BrotherData.getSouthWest ()
Gets the Position that has to be dug to get into the crypt.
Returns
the Position that has to be dug to get into the crypt.
Definition at line 51 of file BrotherData.java.
{
        return southWest;
    }
References southWest.
isBarrowsBrother()
boolean com.runehive.content.activity.impl.barrows.BrotherData.isBarrowsBrother (Npc mob) static
Definition at line 82 of file BrotherData.java.
{
        for (BrotherData brother : values()) {
            if (brother.getNpcId() == mob.id) {
                return true;
            }
        }
        return false;
    }
References BrotherData(), and com.runehive.game.world.entity.mob.Mob.id.
Member Data Documentation
AHRIM
com.runehive.content.activity.impl.barrows.BrotherData.AHRIM =(1672, new Position(3562, 3285), new Position(3568, 3291), new Position(3565, 3288), new Position(3557, 9703, 3))
Definition at line 7 of file BrotherData.java.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.clickObject(), and com.runehive.content.activity.impl.barrows.Barrows.update().
cryptPosition
Position com.runehive.content.activity.impl.barrows.BrotherData.cryptPosition private
The position of the crypt.
Definition at line 27 of file BrotherData.java.
Referenced by BrotherData(), and getCryptPosition().
DHAROK
com.runehive.content.activity.impl.barrows.BrotherData.DHAROK =(1673, new Position(3573, 3295), new Position(3578, 3300), new Position(3575, 3298), new Position(3556, 9718, 3))
Definition at line 11 of file BrotherData.java.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.clickObject(), and com.runehive.content.activity.impl.barrows.Barrows.update().
GUTHAN
com.runehive.content.activity.impl.barrows.BrotherData.GUTHAN =(1674, new Position(3575, 3279), new Position(3580, 3286), new Position(3577, 3282), new Position(3534, 9704, 3))
Definition at line 8 of file BrotherData.java.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.clickObject(), and com.runehive.content.activity.impl.barrows.Barrows.update().
hillPosition
Position com.runehive.content.activity.impl.barrows.BrotherData.hillPosition private
The position of the hill.
Definition at line 24 of file BrotherData.java.
Referenced by BrotherData(), and getHillPosition().
KARIL
com.runehive.content.activity.impl.barrows.BrotherData.KARIL =(1675, new Position(3563, 3273), new Position(3568, 3278), new Position(3566, 3275), new Position(3546, 9684, 3))
Definition at line 10 of file BrotherData.java.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.clickObject(), and com.runehive.content.activity.impl.barrows.Barrows.update().
northEast
Position com.runehive.content.activity.impl.barrows.BrotherData.northEast private
The Position that has to be dug to get into the crypt.
Definition at line 21 of file BrotherData.java.
Referenced by BrotherData(), and getNorthEast().
npcId
int com.runehive.content.activity.impl.barrows.BrotherData.npcId private
The npc id of the barrows brother.
Definition at line 15 of file BrotherData.java.
Referenced by BrotherData(), and getNpcId().
southWest
Position com.runehive.content.activity.impl.barrows.BrotherData.southWest private
The Position that has to be dug to get into the crypt.
Definition at line 18 of file BrotherData.java.
Referenced by BrotherData(), and getSouthWest().
TORAG
com.runehive.content.activity.impl.barrows.BrotherData.TORAG =(1676, new Position(3551, 3279), new Position(3556, 3285), new Position(3554, 3282), new Position(3568, 9683, 3))
Definition at line 12 of file BrotherData.java.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.clickObject(), and com.runehive.content.activity.impl.barrows.Barrows.update().
VERAC
com.runehive.content.activity.impl.barrows.BrotherData.VERAC =(1677, new Position(3554, 3293), new Position(3560, 3301), new Position(3557, 3297), new Position(3578, 9706, 3))
Definition at line 9 of file BrotherData.java.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.clickObject(), and com.runehive.content.activity.impl.barrows.Barrows.update().
The documentation for this enum was generated from the following file:
java/com/runehive/content/activity/impl/barrows/BrotherData.java