RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Tanning.TanData Enum Reference
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData Enum Reference
The tan data.
Public Member Functions
TanData (int ingredient, int product, int cost)
Constructs a new TanData.
Public Attributes
BLACK_LEATHER =(1747, 2509, 20)
BLUE_LEATHER =(1751, 2505, 20)
final int cost
The tan cost.
GREEN_LEATHER =(1753, 1745, 20)
HARD_LEATHER =(1739, 1743, 3)
final int ingredient
The ingredient item.
LEATHER =(1739, 1741, 1)
final int product
The product item.
RED_LEATHER =(1749, 2507, 20)
SNAKE_HIDE =(6287, 6287, 15)
SNAKESKIN =(6287, 6289, 20)
Detailed Description
The tan data.
Definition at line 23 of file Tanning.java.
Constructor & Destructor Documentation
TanData()
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.TanData (int ingredient, int product, int cost)
Constructs a new TanData.
Parameters
ingredient The ingredient item.
product The product item.
cost The tan cost.
Definition at line 55 of file Tanning.java.
{
            this.ingredient = ingredient;
            this.product = product;
            this.cost = cost;
        }
References cost, ingredient, and product.
Member Data Documentation
BLACK_LEATHER
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.BLACK_LEATHER =(1747, 2509, 20)
Definition at line 31 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.click().
BLUE_LEATHER
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.BLUE_LEATHER =(1751, 2505, 20)
Definition at line 29 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.click().
cost
final int com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.cost
The tan cost.
Definition at line 46 of file Tanning.java.
Referenced by TanData().
GREEN_LEATHER
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.GREEN_LEATHER =(1753, 1745, 20)
Definition at line 28 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.click().
HARD_LEATHER
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.HARD_LEATHER =(1739, 1743, 3)
Definition at line 25 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.click().
ingredient
final int com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.ingredient
The ingredient item.
Definition at line 36 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), and TanData().
LEATHER
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.LEATHER =(1739, 1741, 1)
Definition at line 24 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.click().
product
final int com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.product
The product item.
Definition at line 41 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.tan(), and TanData().
RED_LEATHER
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.RED_LEATHER =(1749, 2507, 20)
Definition at line 30 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.click().
SNAKE_HIDE
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.SNAKE_HIDE =(6287, 6287, 15)
Definition at line 26 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.click().
SNAKESKIN
com.runehive.content.skill.impl.crafting.impl.Tanning.TanData.SNAKESKIN =(6287, 6289, 20)
Definition at line 27 of file Tanning.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Tanning.click().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Tanning.java