RuneHive-Game: com.runehive.game.world.items.containers.equipment.EquipmentType Enum Reference
com.runehive.game.world.items.containers.equipment.EquipmentType Enum Reference
The enumerated types of a players equipped item slots.
Public Member Functions
EquipmentType (final int slot, final String newItemDefName)
String getNewItemDefName ()
int getSlot ()
Static Public Member Functions
[static initializer]
static EquipmentType forNewName (final String newItemDefName)
static EquipmentType lookup (int slot)
Public Attributes
AMULET =(2, "neck")
ARROWS =(13, "ammo")
BODY =(4, "body")
BOOTS =(10, "feet")
CAPE =(1, "cape")
FACE =(0, "head")
GLOVES =(9, "hands")
HAT =(0, "head")
HELM =(0, "head")
LEGS =(7, "legs")
MASK =(0, "head")
NOT_WIELDABLE =(-1, "NONE")
RING =(12, "ring")
SHIELD =(5, "shield")
TORSO =(4, "body")
WEAPON =(3, "weapon")
Static Public Attributes
static final EquipmentType[] values = values()
Private Attributes
final String newItemDefName
final int slot
Static Private Attributes
static final Object2ObjectMap< String, EquipmentType > newNameToType = new Object2ObjectOpenHashMap<>(values.length)
Detailed Description
The enumerated types of a players equipped item slots.
Author
Daniel
Definition at line 13 of file EquipmentType.java.
Constructor & Destructor Documentation
EquipmentType()
com.runehive.game.world.items.containers.equipment.EquipmentType.EquipmentType (final int slot, final String newItemDefName)
Definition at line 34 of file EquipmentType.java.
{
        this.slot = slot;
        this.newItemDefName = newItemDefName;
    }
References newItemDefName.
Referenced by forNewName(), and lookup().
Member Function Documentation
[static initializer]()
com.runehive.game.world.items.containers.equipment.EquipmentType.[static initializer] static
References newNameToType.
forNewName()
EquipmentType com.runehive.game.world.items.containers.equipment.EquipmentType.forNewName (final String newItemDefName) static
Definition at line 58 of file EquipmentType.java.
{
        return newNameToType.get(newItemDefName);
    }
References EquipmentType(), newItemDefName, and newNameToType.
getNewItemDefName()
String com.runehive.game.world.items.containers.equipment.EquipmentType.getNewItemDefName ()
Definition at line 43 of file EquipmentType.java.
{
        return newItemDefName;
    }
References newItemDefName.
getSlot()
int com.runehive.game.world.items.containers.equipment.EquipmentType.getSlot ()
Definition at line 39 of file EquipmentType.java.
{
        return slot;
    }
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.util.parser.old.defs.EquipmentDefinition.getSlot(), com.runehive.game.world.items.containers.equipment.Equipment.manualWear(), and com.runehive.game.world.items.containers.equipment.Equipment.unEquip().
lookup()
EquipmentType com.runehive.game.world.items.containers.equipment.EquipmentType.lookup (int slot) static
Definition at line 62 of file EquipmentType.java.
{
        return Arrays.stream(values()).filter(it -> it.slot == slot).findFirst().orElse(EquipmentType.NOT_WIELDABLE);
    }
References EquipmentType(), and values.
Member Data Documentation
AMULET
com.runehive.game.world.items.containers.equipment.EquipmentType.AMULET =(2, "neck")
Definition at line 23 of file EquipmentType.java.
Referenced by com.runehive.content.overrides.Overrides.handleButtons().
ARROWS
com.runehive.game.world.items.containers.equipment.EquipmentType.ARROWS =(13, "ammo")
Definition at line 25 of file EquipmentType.java.
Referenced by com.runehive.content.overrides.Overrides.addOverride(), com.runehive.util.parser.old.EquipmentDefinitionParser.getReq(), com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), and com.runehive.game.world.items.containers.equipment.Equipment.onRemove().
BODY
com.runehive.game.world.items.containers.equipment.EquipmentType.BODY =(4, "body")
Definition at line 26 of file EquipmentType.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.util.parser.old.EquipmentDefinitionParser.getReq(), and com.runehive.content.overrides.Overrides.handleButtons().
BOOTS
com.runehive.game.world.items.containers.equipment.EquipmentType.BOOTS =(10, "feet")
Definition at line 22 of file EquipmentType.java.
Referenced by com.runehive.content.overrides.Overrides.handleButtons().
CAPE
com.runehive.game.world.items.containers.equipment.EquipmentType.CAPE =(1, "cape")
Definition at line 19 of file EquipmentType.java.
Referenced by com.runehive.content.overrides.Overrides.handleButtons().
FACE
com.runehive.game.world.items.containers.equipment.EquipmentType.FACE =(0, "head")
Definition at line 18 of file EquipmentType.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), and com.runehive.util.parser.old.EquipmentDefinitionParser.parse().
GLOVES
com.runehive.game.world.items.containers.equipment.EquipmentType.GLOVES =(9, "hands")
Definition at line 21 of file EquipmentType.java.
Referenced by com.runehive.util.parser.old.EquipmentDefinitionParser.getReq(), and com.runehive.content.overrides.Overrides.handleButtons().
HAT
com.runehive.game.world.items.containers.equipment.EquipmentType.HAT =(0, "head")
Definition at line 15 of file EquipmentType.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask().
HELM
com.runehive.game.world.items.containers.equipment.EquipmentType.HELM =(0, "head")
Definition at line 16 of file EquipmentType.java.
Referenced by com.runehive.content.overrides.Overrides.handleButtons(), and com.runehive.util.parser.old.EquipmentDefinitionParser.parse().
LEGS
com.runehive.game.world.items.containers.equipment.EquipmentType.LEGS =(7, "legs")
Definition at line 28 of file EquipmentType.java.
Referenced by com.runehive.content.overrides.Overrides.handleButtons().
MASK
com.runehive.game.world.items.containers.equipment.EquipmentType.MASK =(0, "head")
Definition at line 17 of file EquipmentType.java.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask().
newItemDefName
final String com.runehive.game.world.items.containers.equipment.EquipmentType.newItemDefName private
Definition at line 32 of file EquipmentType.java.
Referenced by EquipmentType(), forNewName(), and getNewItemDefName().
newNameToType
final Object2ObjectMap<String, EquipmentType> com.runehive.game.world.items.containers.equipment.EquipmentType.newNameToType = new Object2ObjectOpenHashMap<>(values.length) static private
Definition at line 50 of file EquipmentType.java.
Referenced by [static initializer](), and forNewName().
NOT_WIELDABLE
com.runehive.game.world.items.containers.equipment.EquipmentType.NOT_WIELDABLE =(-1, "NONE")
Definition at line 14 of file EquipmentType.java.
Referenced by com.runehive.game.world.items.ItemDefinition.create(), com.runehive.content.overrides.Overrides.drawText(), com.runehive.game.world.items.ItemDefinition.dump(), com.runehive.game.world.items.ItemDefinition.dump(), com.runehive.content.overrides.Overrides.handleButtons(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), com.runehive.game.world.items.Item.isEquipable(), com.runehive.game.world.items.ItemDefinition.ItemDefinition(), com.runehive.content.overrides.Overrides.openInterface(), and com.runehive.util.parser.old.EquipmentDefinitionParser.parse().
RING
com.runehive.game.world.items.containers.equipment.EquipmentType.RING =(12, "ring")
Definition at line 24 of file EquipmentType.java.
Referenced by com.runehive.content.overrides.Overrides.addOverride(), and com.runehive.util.parser.old.EquipmentDefinitionParser.getReq().
SHIELD
com.runehive.game.world.items.containers.equipment.EquipmentType.SHIELD =(5, "shield")
Definition at line 20 of file EquipmentType.java.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.content.overrides.Overrides.handleButtons(), com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), and com.runehive.game.world.items.containers.equipment.Equipment.onRemove().
slot
final int com.runehive.game.world.items.containers.equipment.EquipmentType.slot private
Definition at line 31 of file EquipmentType.java.
TORSO
com.runehive.game.world.items.containers.equipment.EquipmentType.TORSO =(4, "body")
Definition at line 27 of file EquipmentType.java.
values
final EquipmentType [] com.runehive.game.world.items.containers.equipment.EquipmentType.values = values() static
Definition at line 47 of file EquipmentType.java.
Referenced by lookup().
WEAPON
com.runehive.game.world.items.containers.equipment.EquipmentType.WEAPON =(3, "weapon")
Definition at line 29 of file EquipmentType.java.
Referenced by com.runehive.game.world.items.containers.equipment.Equipment.equip(), com.runehive.util.parser.old.EquipmentDefinitionParser.getReq(), com.runehive.content.overrides.Overrides.handleButtons(), com.runehive.game.world.items.containers.equipment.Equipment.onEquip(), and com.runehive.game.world.items.containers.equipment.Equipment.onRemove().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/items/containers/equipment/EquipmentType.java