RuneHive-Game: com.runehive.game.world.entity.combat.magic.CombatSpell Enum Reference
com.runehive.game.world.entity.combat.magic.CombatSpell Enum Reference
Public Member Functions
boolean canCast (Mob attacker, Mob defender)
CombatSpell (Spellbook spellbook, int id, int level, float baseExperience, Item weapon, CombatProjectile combatProjectile, RequiredRune[] runes)
Optional< Animation > getAnimation ()
double getBaseExperience ()
CombatProjectile getCombatProjectile ()
Optional< CombatImpact > getEffect ()
Optional< Graphic > getEnd ()
int getId ()
int getLevel ()
String getName ()
RequiredRune[] getRunes ()
Spellbook getSpellbook ()
Optional< Graphic > getStart ()
int sendProjectile (Mob attacker, Mob defender)
Static Public Member Functions
[static initializer]
static CombatSpell get (int id)
Public Attributes
BIND
BLOOD_BARRAGE
BLOOD_BLITZ
BLOOD_BURST
BLOOD_RUSH
CLAWS_OF_GUTHIX
CONFUSE
CRUMBLE_UNDEAD
CURSE
EARTH_BLAST
EARTH_BOLT
EARTH_STRIKE
EARTH_SURGE
EARTH_WAVE
ENFEEBLE
ENTANGLE
FIRE_BLAST
FIRE_BOLT
FIRE_STRIKE
FIRE_SURGE
FIRE_WAVE
FLAMES_OF_ZAMORAK
IBAN_BLAST
ICE_BARRAGE
ICE_BLITZ
ICE_BURST
ICE_RUSH
MAGIC_DART
SARADOMIN_STRIKE
SHADOW_BARRAGE
SHADOW_BLITZ
SHADOW_BURST
SHADOW_RUSH
SMOKE_BARRAGE
SMOKE_BLITZ
SMOKE_BURST
SMOKE_RUSH
SNARE
STUN
TELE_BLOCK
VULNERABILITY
WATER_BLAST
WATER_BOLT
WATER_STRIKE
WATER_SURGE
WATER_WAVE
WEAKEN
WIND_BLAST
WIND_BOLT
WIND_STRIKE
WIND_SURGE
WIND_WAVE
Private Attributes
final CombatProjectile combatProjectile
final int id
final MagicSpell spell
final Spellbook spellbook
Static Private Attributes
static final Map< Integer, CombatSpell > SPELLS
Detailed Description
Definition at line 17 of file CombatSpell.java.
Constructor & Destructor Documentation
CombatSpell()
com.runehive.game.world.entity.combat.magic.CombatSpell.CombatSpell (Spellbook spellbook, int id, int level, float baseExperience, Item weapon, CombatProjectile combatProjectile, RequiredRune[] runes)
Definition at line 501 of file CombatSpell.java.
{
        this.spellbook = spellbook;
        this.id = id;
        this.spell = new MagicSpell(level, baseExperience, runes) {
            @Override
            public Optional<Item[]> equipmentRequired() {
                return weapon == null ? Optional.empty() : Optional.of(new Item[]{weapon});
            }
        };
        this.combatProjectile = combatProjectile;
    }
References combatProjectile, id, and spellbook.
Referenced by [static initializer](), and get().
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.magic.CombatSpell.[static initializer] static
References CombatSpell(), spell, and SPELLS.
canCast()
boolean com.runehive.game.world.entity.combat.magic.CombatSpell.canCast (Mob attacker, Mob defender)
Definition at line 562 of file CombatSpell.java.
{
        return spell.canCast(attacker, Optional.ofNullable(defender));
    }
References spell.
get()
CombatSpell com.runehive.game.world.entity.combat.magic.CombatSpell.get (int id) static
Definition at line 566 of file CombatSpell.java.
{
        return SPELLS.getOrDefault(id, WIND_STRIKE);
    }
References CombatSpell(), id, SPELLS, and WIND_STRIKE.
Referenced by com.runehive.game.world.entity.combat.magic.Autocast.setAutocast().
getAnimation()
Optional< Animation > com.runehive.game.world.entity.combat.magic.CombatSpell.getAnimation ()
Definition at line 541 of file CombatSpell.java.
{
        return CombatProjectile.getDefinition(combatProjectile.getName()).getAnimation();//combatProjectile.getAnimation();
    }
References combatProjectile, com.runehive.game.world.entity.combat.projectile.CombatProjectile.getAnimation(), and com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition().
getBaseExperience()
double com.runehive.game.world.entity.combat.magic.CombatSpell.getBaseExperience ()
Definition at line 529 of file CombatSpell.java.
{
        return spell.baseExperience;
    }
References spell.
getCombatProjectile()
CombatProjectile com.runehive.game.world.entity.combat.magic.CombatSpell.getCombatProjectile ()
Definition at line 525 of file CombatSpell.java.
{
        return combatProjectile == null ? null : CombatProjectile.getDefinition(combatProjectile.getName());
    }
References combatProjectile, and com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition().
Referenced by com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), and sendProjectile().
getEffect()
Optional< CombatImpact > com.runehive.game.world.entity.combat.magic.CombatSpell.getEffect ()
Definition at line 533 of file CombatSpell.java.
{
        return combatProjectile.getEffect();
    }
References combatProjectile.
getEnd()
Optional< Graphic > com.runehive.game.world.entity.combat.magic.CombatSpell.getEnd ()
Definition at line 549 of file CombatSpell.java.
{
        return CombatProjectile.getDefinition(combatProjectile.getName()).getEnd();//combatProjectile.getEnd();
    }
References combatProjectile, com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition(), and com.runehive.game.world.entity.combat.projectile.CombatProjectile.getEnd().
getId()
int com.runehive.game.world.entity.combat.magic.CombatSpell.getId ()
Definition at line 513 of file CombatSpell.java.
                       {
        return id;
    }
References id.
getLevel()
int com.runehive.game.world.entity.combat.magic.CombatSpell.getLevel ()
Definition at line 521 of file CombatSpell.java.
{
        return spell.level;
    }
References spell.
getName()
String com.runehive.game.world.entity.combat.magic.CombatSpell.getName ()
Definition at line 517 of file CombatSpell.java.
{
        return combatProjectile.getName();
    }
References combatProjectile.
getRunes()
RequiredRune[] com.runehive.game.world.entity.combat.magic.CombatSpell.getRunes ()
Definition at line 537 of file CombatSpell.java.
{
        return spell.runes;
    }
References spell.
Referenced by com.runehive.game.world.entity.combat.magic.Autocast.setAutocast().
getSpellbook()
Spellbook com.runehive.game.world.entity.combat.magic.CombatSpell.getSpellbook ()
Definition at line 553 of file CombatSpell.java.
{
        return spellbook;
    }
References spellbook.
getStart()
Optional< Graphic > com.runehive.game.world.entity.combat.magic.CombatSpell.getStart ()
Definition at line 545 of file CombatSpell.java.
{
        return CombatProjectile.getDefinition(combatProjectile.getName()).getStart();//combatProjectile.getStart();
    }
References combatProjectile, com.runehive.game.world.entity.combat.projectile.CombatProjectile.getDefinition(), and com.runehive.game.world.entity.combat.projectile.CombatProjectile.getStart().
sendProjectile()
int com.runehive.game.world.entity.combat.magic.CombatSpell.sendProjectile (Mob attacker, Mob defender)
Definition at line 557 of file CombatSpell.java.
{
        final CombatProjectile combatProjectile = getCombatProjectile();
        return combatProjectile == null ? 0 : combatProjectile.sendProjectile(attacker, defender);
    }
References combatProjectile, and getCombatProjectile().
Member Data Documentation
BIND
com.runehive.game.world.entity.combat.magic.CombatSpell.BIND
Initial value:
=(Spellbook.MODERN, 1572, 20, 30.0f, null,
            getDefinition("Bind"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.NATURE_RUNE, 2),
                    new RequiredRune(MagicRune.EARTH_RUNE, 3),
                    new RequiredRune(MagicRune.WATER_RUNE, 3)
            }
    )
Definition at line 193 of file CombatSpell.java.
BLOOD_BARRAGE
com.runehive.game.world.entity.combat.magic.CombatSpell.BLOOD_BARRAGE
Initial value:
=(Spellbook.ANCIENT, 12929, 92, 51.0f, null,
            getDefinition("Blood Barrage"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 4),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 4),
                    new RequiredRune(MagicRune.SOUL_RUNE, 1)
            }
    )
Definition at line 396 of file CombatSpell.java.
BLOOD_BLITZ
com.runehive.game.world.entity.combat.magic.CombatSpell.BLOOD_BLITZ
Initial value:
=(Spellbook.ANCIENT, 12911, 80, 45.0f, null,
            getDefinition("Blood Blitz"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 4)
            }
    )
Definition at line 379 of file CombatSpell.java.
BLOOD_BURST
com.runehive.game.world.entity.combat.magic.CombatSpell.BLOOD_BURST
Initial value:
=(Spellbook.ANCIENT, 12919, 68, 39.0f, null,
            getDefinition("Blood Burst"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 4)
            }
    )
Definition at line 387 of file CombatSpell.java.
BLOOD_RUSH
com.runehive.game.world.entity.combat.magic.CombatSpell.BLOOD_RUSH
Initial value:
=(Spellbook.ANCIENT, 12901, 56, 33.0f, null,
            getDefinition("Blood Rush"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.BLOOD_RUNE, 1),
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 2)
            }
    )
Definition at line 370 of file CombatSpell.java.
CLAWS_OF_GUTHIX
com.runehive.game.world.entity.combat.magic.CombatSpell.CLAWS_OF_GUTHIX
Initial value:
=(Spellbook.MODERN, 1191, 60, 20.0f, null,
            getDefinition("Claws of Guthix"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.FIRE_RUNE, 2),
                    new RequiredRune(MagicRune.AIR_RUNE, 4)
            }
    )
Definition at line 175 of file CombatSpell.java.
combatProjectile
final CombatProjectile com.runehive.game.world.entity.combat.magic.CombatSpell.combatProjectile private
Definition at line 487 of file CombatSpell.java.
Referenced by CombatSpell(), getAnimation(), getCombatProjectile(), getEffect(), getEnd(), getName(), getStart(), and sendProjectile().
CONFUSE
com.runehive.game.world.entity.combat.magic.CombatSpell.CONFUSE
Initial value:
=(Spellbook.MODERN, 1153, 3, 13.0f, null,
            getDefinition("Confuse"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 3),
                    new RequiredRune(MagicRune.EARTH_RUNE, 2),
                    new RequiredRune(MagicRune.BODY_RUNE, 1)
            }
    )
Definition at line 236 of file CombatSpell.java.
CRUMBLE_UNDEAD
com.runehive.game.world.entity.combat.magic.CombatSpell.CRUMBLE_UNDEAD
Initial value:
=(Spellbook.MODERN, 1171, 39, 24.0f, null,
            getDefinition("Crumble Undead"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.EARTH_RUNE, 2),
                    new RequiredRune(MagicRune.AIR_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 1)
            })
Definition at line 88 of file CombatSpell.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getHits().
CURSE
com.runehive.game.world.entity.combat.magic.CombatSpell.CURSE
Initial value:
=(Spellbook.MODERN, 1161, 19, 29.0f, null,
            getDefinition("Curse"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 2),
                    new RequiredRune(MagicRune.EARTH_RUNE, 3),
                    new RequiredRune(MagicRune.BODY_RUNE, 1)
            }
    )
Definition at line 254 of file CombatSpell.java.
EARTH_BLAST
com.runehive.game.world.entity.combat.magic.CombatSpell.EARTH_BLAST
Initial value:
=(Spellbook.MODERN, 1177, 53, 31.5f, null,
            getDefinition("Earth Blast"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 3),
                    new RequiredRune(MagicRune.EARTH_RUNE, 4),
                    new RequiredRune(MagicRune.DEATH_RUNE, 1)
            }
    )
Definition at line 113 of file CombatSpell.java.
EARTH_BOLT
com.runehive.game.world.entity.combat.magic.CombatSpell.EARTH_BOLT
Initial value:
=(Spellbook.MODERN, 1166, 29, 19.5f, null,
            getDefinition("Earth Bolt"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 1),
                    new RequiredRune(MagicRune.EARTH_RUNE, 3)
            }
    )
Definition at line 70 of file CombatSpell.java.
EARTH_STRIKE
com.runehive.game.world.entity.combat.magic.CombatSpell.EARTH_STRIKE
Initial value:
=(Spellbook.MODERN, 1156, 9, 9.5f, null,
            getDefinition("Earth Strike"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 1),
                    new RequiredRune(MagicRune.MIND_RUNE, 1),
                    new RequiredRune(MagicRune.EARTH_RUNE, 2)
            }
    )
Definition at line 35 of file CombatSpell.java.
EARTH_SURGE
com.runehive.game.world.entity.combat.magic.CombatSpell.EARTH_SURGE
Initial value:
=(Spellbook.MODERN, 40170, 90, 48.5f, null,
            getDefinition("Earth Surge"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 7),
                    new RequiredRune(MagicRune.EARTH_RUNE, 10),
                    new RequiredRune(MagicRune.WRATH_RUNE, 1)
            }
    )
Definition at line 316 of file CombatSpell.java.
EARTH_WAVE
com.runehive.game.world.entity.combat.magic.CombatSpell.EARTH_WAVE
Initial value:
=(Spellbook.MODERN, 1188, 70, 40.0f, null,
            getDefinition("Earth Wave"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 5),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 1),
                    new RequiredRune(MagicRune.EARTH_RUNE, 7)
            }
    )
Definition at line 148 of file CombatSpell.java.
ENFEEBLE
com.runehive.game.world.entity.combat.magic.CombatSpell.ENFEEBLE
Initial value:
=(Spellbook.MODERN, 1543, 73, 83.0f, null,
            getDefinition("Enfeeble"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 8),
                    new RequiredRune(MagicRune.EARTH_RUNE, 8),
                    new RequiredRune(MagicRune.SOUL_RUNE, 1)
            }
    )
Definition at line 272 of file CombatSpell.java.
ENTANGLE
com.runehive.game.world.entity.combat.magic.CombatSpell.ENTANGLE
Initial value:
=(Spellbook.MODERN, 1592, 79, 89.0f, null,
            getDefinition("Entangle"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.NATURE_RUNE, 4),
                    new RequiredRune(MagicRune.EARTH_RUNE, 5),
                    new RequiredRune(MagicRune.WATER_RUNE, 5)
            }
    )
Definition at line 227 of file CombatSpell.java.
FIRE_BLAST
com.runehive.game.world.entity.combat.magic.CombatSpell.FIRE_BLAST
Initial value:
=(Spellbook.MODERN, 1181, 59, 34.5f, null,
            getDefinition("Fire Blast"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 4),
                    new RequiredRune(MagicRune.FIRE_RUNE, 5),
                    new RequiredRune(MagicRune.DEATH_RUNE, 1)
            }
    )
Definition at line 122 of file CombatSpell.java.
FIRE_BOLT
com.runehive.game.world.entity.combat.magic.CombatSpell.FIRE_BOLT
Initial value:
=(Spellbook.MODERN, 1169, 35, 22.5f, null,
            getDefinition("Fire Bolt"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 3),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 1),
                    new RequiredRune(MagicRune.FIRE_RUNE, 4)
            }
    )
Definition at line 79 of file CombatSpell.java.
FIRE_STRIKE
com.runehive.game.world.entity.combat.magic.CombatSpell.FIRE_STRIKE
Initial value:
=(Spellbook.MODERN, 1158, 13, 11.5f, null,
            getDefinition("Fire Strike"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 2),
                    new RequiredRune(MagicRune.MIND_RUNE, 1),
                    new RequiredRune(MagicRune.FIRE_RUNE, 3)
            }
    )
Definition at line 44 of file CombatSpell.java.
FIRE_SURGE
com.runehive.game.world.entity.combat.magic.CombatSpell.FIRE_SURGE
Initial value:
=(Spellbook.MODERN, 40190, 95, 50.5f, null,
            getDefinition("Fire Surge"),
            new RequiredRune[] {
                    new RequiredRune(MagicRune.AIR_RUNE, 7),
                    new RequiredRune(MagicRune.FIRE_RUNE, 10),
                    new RequiredRune(MagicRune.WRATH_RUNE, 1)
            }
    )
Definition at line 325 of file CombatSpell.java.
FIRE_WAVE
com.runehive.game.world.entity.combat.magic.CombatSpell.FIRE_WAVE
Initial value:
=(Spellbook.MODERN, 1189, 75, 42.5f, null,
            getDefinition("Fire Wave"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 5),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 1),
                    new RequiredRune(MagicRune.FIRE_RUNE, 7)
            }
    )
Definition at line 157 of file CombatSpell.java.
FLAMES_OF_ZAMORAK
com.runehive.game.world.entity.combat.magic.CombatSpell.FLAMES_OF_ZAMORAK
Initial value:
=(Spellbook.MODERN, 1192, 60, 20.0f, null,
            getDefinition("Flames of Zamorak"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.FIRE_RUNE, 2),
                    new RequiredRune(MagicRune.AIR_RUNE, 4)
            }
    )
Definition at line 184 of file CombatSpell.java.
IBAN_BLAST
com.runehive.game.world.entity.combat.magic.CombatSpell.IBAN_BLAST
Initial value:
=(Spellbook.MODERN, 1539, 50, 30.0f, new Item(1409),
            getDefinition("Iban Blast"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.FIRE_RUNE, 5),
                    new RequiredRune(MagicRune.DEATH_RUNE, 1)
            }
    )
Definition at line 202 of file CombatSpell.java.
ICE_BARRAGE
com.runehive.game.world.entity.combat.magic.CombatSpell.ICE_BARRAGE
Initial value:
=(Spellbook.ANCIENT, 12891, 94, 52.0f, null,
            getDefinition("Ice Barrage"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 4),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.WATER_RUNE, 6)
            }
    )
Definition at line 361 of file CombatSpell.java.
ICE_BLITZ
com.runehive.game.world.entity.combat.magic.CombatSpell.ICE_BLITZ
Initial value:
=(Spellbook.ANCIENT, 12871, 82, 46.0f, null,
            getDefinition("Ice Blitz"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 3),
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2)
            }
    )
Definition at line 343 of file CombatSpell.java.
ICE_BURST
com.runehive.game.world.entity.combat.magic.CombatSpell.ICE_BURST
Initial value:
=(Spellbook.ANCIENT, 12881, 70, 40.0f, null,
            getDefinition("Ice Burst"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 4),
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 4)
            }
    )
Definition at line 352 of file CombatSpell.java.
ICE_RUSH
com.runehive.game.world.entity.combat.magic.CombatSpell.ICE_RUSH
Initial value:
=(Spellbook.ANCIENT, 12861, 58, 34.0f, null,
            getDefinition("Ice Rush"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 2),
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 2)
            }
    )
Definition at line 334 of file CombatSpell.java.
id
final int com.runehive.game.world.entity.combat.magic.CombatSpell.id private
Definition at line 485 of file CombatSpell.java.
Referenced by CombatSpell(), get(), and getId().
MAGIC_DART
com.runehive.game.world.entity.combat.magic.CombatSpell.MAGIC_DART
Initial value:
=(Spellbook.MODERN, 12037, 50, 30.0f, new Item(4170),
            getDefinition("Magic Dart"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 1),
                    new RequiredRune(MagicRune.MIND_RUNE, 4),
            }
    )
Definition at line 210 of file CombatSpell.java.
SARADOMIN_STRIKE
com.runehive.game.world.entity.combat.magic.CombatSpell.SARADOMIN_STRIKE
Initial value:
=(Spellbook.MODERN, 1190, 60, 20.0f, null,
            getDefinition("Saradomin Strike"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.FIRE_RUNE, 2),
                    new RequiredRune(MagicRune.AIR_RUNE, 4)
            }
    )
Definition at line 166 of file CombatSpell.java.
SHADOW_BARRAGE
com.runehive.game.world.entity.combat.magic.CombatSpell.SHADOW_BARRAGE
Initial value:
=(Spellbook.ANCIENT, 13023, 88, 49.0f, null,
            getDefinition("Shadow Barrage"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.SOUL_RUNE, 3),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.DEATH_RUNE, 4),
                    new RequiredRune(MagicRune.AIR_RUNE, 4)
            }
    )
Definition at line 483 of file CombatSpell.java.
SHADOW_BLITZ
com.runehive.game.world.entity.combat.magic.CombatSpell.SHADOW_BLITZ
Initial value:
=(Spellbook.ANCIENT, 12999, 76, 43.0f, null,
            getDefinition("Shadow Blitz"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.SOUL_RUNE, 2),
                    new RequiredRune(MagicRune.AIR_RUNE, 2)
            }
    )
Definition at line 455 of file CombatSpell.java.
SHADOW_BURST
com.runehive.game.world.entity.combat.magic.CombatSpell.SHADOW_BURST
Initial value:
=(Spellbook.ANCIENT, 13011, 64, 37.0f, null,
            getDefinition("Shadow Burst"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.SOUL_RUNE, 2),
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 4),
                    new RequiredRune(MagicRune.AIR_RUNE, 1)
            }
    )
Definition at line 465 of file CombatSpell.java.
SHADOW_RUSH
com.runehive.game.world.entity.combat.magic.CombatSpell.SHADOW_RUSH
Initial value:
=(Spellbook.ANCIENT, 12987, 52, 31.0f, null,
            getDefinition("Shadow Rush"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 2),
                    new RequiredRune(MagicRune.SOUL_RUNE, 1),
                    new RequiredRune(MagicRune.AIR_RUNE, 1)
            }
    )
Definition at line 445 of file CombatSpell.java.
SMOKE_BARRAGE
com.runehive.game.world.entity.combat.magic.CombatSpell.SMOKE_BARRAGE
Initial value:
=(Spellbook.ANCIENT, 12975, 86, 48.0f, null,
            getDefinition("Smoke Barrage"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 4),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.FIRE_RUNE, 4),
                    new RequiredRune(MagicRune.AIR_RUNE, 4)
            }
    )
Definition at line 435 of file CombatSpell.java.
SMOKE_BLITZ
com.runehive.game.world.entity.combat.magic.CombatSpell.SMOKE_BLITZ
Initial value:
=(Spellbook.ANCIENT, 12951, 74, 42.0f, null,
            getDefinition("Smoke Blitz"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 2),
                    new RequiredRune(MagicRune.FIRE_RUNE, 2),
                    new RequiredRune(MagicRune.AIR_RUNE, 2)
            }
    )
Definition at line 415 of file CombatSpell.java.
SMOKE_BURST
com.runehive.game.world.entity.combat.magic.CombatSpell.SMOKE_BURST
Initial value:
=(Spellbook.ANCIENT, 12963, 62, 36.0f, null,
            getDefinition("Smoke Burst"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 4),
                    new RequiredRune(MagicRune.FIRE_RUNE, 2),
                    new RequiredRune(MagicRune.AIR_RUNE, 2)
            }
    )
Definition at line 425 of file CombatSpell.java.
SMOKE_RUSH
com.runehive.game.world.entity.combat.magic.CombatSpell.SMOKE_RUSH
Initial value:
=(Spellbook.ANCIENT, 12939, 50, 30.0f, null,
            getDefinition("Smoke Rush"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.DEATH_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 2),
                    new RequiredRune(MagicRune.FIRE_RUNE, 1),
                    new RequiredRune(MagicRune.AIR_RUNE, 1)
            }
    )
Definition at line 405 of file CombatSpell.java.
SNARE
com.runehive.game.world.entity.combat.magic.CombatSpell.SNARE
Initial value:
=(Spellbook.MODERN, 1582, 50, 60.0f, null,
            getDefinition("Snare"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.NATURE_RUNE, 3),
                    new RequiredRune(MagicRune.EARTH_RUNE, 4),
                    new RequiredRune(MagicRune.WATER_RUNE, 4)
            }
    )
Definition at line 218 of file CombatSpell.java.
spell
final MagicSpell com.runehive.game.world.entity.combat.magic.CombatSpell.spell private
Definition at line 486 of file CombatSpell.java.
Referenced by [static initializer](), canCast(), getBaseExperience(), getLevel(), and getRunes().
spellbook
final Spellbook com.runehive.game.world.entity.combat.magic.CombatSpell.spellbook private
Definition at line 488 of file CombatSpell.java.
Referenced by CombatSpell(), and getSpellbook().
SPELLS
final Map<Integer, CombatSpell> com.runehive.game.world.entity.combat.magic.CombatSpell.SPELLS static private
Definition at line 490 of file CombatSpell.java.
Referenced by [static initializer](), and get().
STUN
com.runehive.game.world.entity.combat.magic.CombatSpell.STUN
Initial value:
=(Spellbook.MODERN, 1562, 73, 90.0f, null,
            getDefinition("Stun"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 12),
                    new RequiredRune(MagicRune.EARTH_RUNE, 12),
                    new RequiredRune(MagicRune.SOUL_RUNE, 1)
            }
    )
Definition at line 281 of file CombatSpell.java.
TELE_BLOCK
com.runehive.game.world.entity.combat.magic.CombatSpell.TELE_BLOCK
Initial value:
=(Spellbook.MODERN, 12445, 85, 42.5f, null,
            getDefinition("Teleblock"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.LAW_RUNE, 1),
                    new RequiredRune(MagicRune.DEATH_RUNE, 1),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 1)
            }
    )
Definition at line 290 of file CombatSpell.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack().
VULNERABILITY
com.runehive.game.world.entity.combat.magic.CombatSpell.VULNERABILITY
Initial value:
=(Spellbook.MODERN, 1542, 66, 76.0f, null,
            getDefinition("Vulnerability"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 5),
                    new RequiredRune(MagicRune.EARTH_RUNE, 5),
                    new RequiredRune(MagicRune.SOUL_RUNE, 1)
            }
    )
Definition at line 263 of file CombatSpell.java.
WATER_BLAST
com.runehive.game.world.entity.combat.magic.CombatSpell.WATER_BLAST
Initial value:
=(Spellbook.MODERN, 1175, 47, 28.5f, null,
            getDefinition("Water Blast"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 3),
                    new RequiredRune(MagicRune.WATER_RUNE, 3),
                    new RequiredRune(MagicRune.DEATH_RUNE, 1)
            }
    )
Definition at line 104 of file CombatSpell.java.
WATER_BOLT
com.runehive.game.world.entity.combat.magic.CombatSpell.WATER_BOLT
Initial value:
=(Spellbook.MODERN, 1163, 23, 16.5f, null,
            getDefinition("Water Bolt"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 1),
                    new RequiredRune(MagicRune.WATER_RUNE, 2)
            }
    )
Definition at line 61 of file CombatSpell.java.
WATER_STRIKE
com.runehive.game.world.entity.combat.magic.CombatSpell.WATER_STRIKE
Initial value:
=(Spellbook.MODERN, 1154, 5, 7.5f, null,
            getDefinition("Water Strike"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 1),
                    new RequiredRune(MagicRune.MIND_RUNE, 1),
                    new RequiredRune(MagicRune.WATER_RUNE, 1)
            }
    )
Definition at line 26 of file CombatSpell.java.
WATER_SURGE
com.runehive.game.world.entity.combat.magic.CombatSpell.WATER_SURGE
Initial value:
=(Spellbook.MODERN, 40150, 85, 46.5f, null,
            getDefinition("Water Surge"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 7),
                    new RequiredRune(MagicRune.WATER_RUNE, 10),
                    new RequiredRune(MagicRune.WRATH_RUNE, 1)
            }
    )
Definition at line 307 of file CombatSpell.java.
WATER_WAVE
com.runehive.game.world.entity.combat.magic.CombatSpell.WATER_WAVE
Initial value:
=(Spellbook.MODERN, 1185, 65, 37.5f, null,
            getDefinition("Water Wave"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 5),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 1),
                    new RequiredRune(MagicRune.WATER_RUNE, 7)
            }
    )
Definition at line 139 of file CombatSpell.java.
WEAKEN
com.runehive.game.world.entity.combat.magic.CombatSpell.WEAKEN
Initial value:
=(Spellbook.MODERN, 1157, 11, 20.5f, null,
            getDefinition("Weaken"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.WATER_RUNE, 3),
                    new RequiredRune(MagicRune.EARTH_RUNE, 2),
                    new RequiredRune(MagicRune.BODY_RUNE, 1)
            }
    )
Definition at line 245 of file CombatSpell.java.
WIND_BLAST
com.runehive.game.world.entity.combat.magic.CombatSpell.WIND_BLAST
Initial value:
=(Spellbook.MODERN, 1172, 41, 25.5f, null,
            getDefinition("Wind Blast"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 3),
                    new RequiredRune(MagicRune.DEATH_RUNE, 1)
            }
    )
Definition at line 96 of file CombatSpell.java.
WIND_BOLT
com.runehive.game.world.entity.combat.magic.CombatSpell.WIND_BOLT
Initial value:
=(Spellbook.MODERN, 1160, 17, 13.5f, null,
            getDefinition("Wind Bolt"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 2),
                    new RequiredRune(MagicRune.CHAOS_RUNE, 1)
            }
    )
Definition at line 53 of file CombatSpell.java.
WIND_STRIKE
com.runehive.game.world.entity.combat.magic.CombatSpell.WIND_STRIKE
Initial value:
=(Spellbook.MODERN, 1152, 1, 5.5f, null,
            getDefinition("Wind Strike"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 1),
                    new RequiredRune(MagicRune.MIND_RUNE, 1)
            }
    )
Definition at line 18 of file CombatSpell.java.
Referenced by get().
WIND_SURGE
com.runehive.game.world.entity.combat.magic.CombatSpell.WIND_SURGE
Initial value:
=(Spellbook.MODERN, 40140, 82, 44.5f, null,
            getDefinition("Wind Surge"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 7),
                    new RequiredRune(MagicRune.WRATH_RUNE, 1)
            }
    )
Definition at line 299 of file CombatSpell.java.
WIND_WAVE
com.runehive.game.world.entity.combat.magic.CombatSpell.WIND_WAVE
Initial value:
=(Spellbook.MODERN, 1183, 62, 36.0f, null,
            getDefinition("Wind Wave"),
            new RequiredRune[]{
                    new RequiredRune(MagicRune.AIR_RUNE, 5),
                    new RequiredRune(MagicRune.BLOOD_RUNE, 1)
            }
    )
Definition at line 131 of file CombatSpell.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/magic/CombatSpell.java