RuneHive-Game: com.runehive.content.skill.impl.mining.PickaxeData Enum Reference
com.runehive.content.skill.impl.mining.PickaxeData Enum Reference
Represents types of axes.
Public Member Functions
PickaxeData (int id, int level, int animation, double speed)
Creates the axe.
Static Public Member Functions
static Optional< PickaxeData > getBestPickaxe (Player player)
Gets the definition for this pickaxe.
Public Attributes
ADAMANT_PICKAXE =(1271, 31, 628, 0.2)
final int animation
The animation.
BRONZE_PICKAXE =(1265, 1, 625, 0.05)
DRAGON_OR_PICKAXE =(12797, 61, 643, 0.6)
DRAGON_PICKAXE =(11920, 61, 7139, 0.6)
final int id
The id.
INFERNO_ADZE =(13243, 75, 4483, 0.55)
IRON_PICKAXE =(1267, 1, 626, 0.08)
final int level
The level.
MITHRIL_PICKAXE =(1273, 21, 629, 0.16)
RUNE_PICKAXE =(1275, 41, 624, 0.25)
final double speed
The speed of this pickaxe.
STEEL_PICKAXE =(1269, 6, 627, 0.12)
THIRD_AGE_PICKAXE =(20014, 90, 7283, 0.6)
Static Private Attributes
static final ImmutableSet< PickaxeData > VALUES = ImmutableSet.copyOf(values())
Caches our enum values.
Detailed Description
Represents types of axes.
Author
Graham Edgecombe
Definition at line 13 of file PickaxeData.java.
Constructor & Destructor Documentation
PickaxeData()
com.runehive.content.skill.impl.mining.PickaxeData.PickaxeData (int id, int level, int animation, double speed)
Creates the axe.
Parameters
id The id.
level The required level.
animation The animation id.
Definition at line 54 of file PickaxeData.java.
{
        this.id = id;
        this.level = level;
        this.animation = animation;
        this.speed = speed;
    }
References animation, id, level, and speed.
Member Function Documentation
getBestPickaxe()
Optional< PickaxeData > com.runehive.content.skill.impl.mining.PickaxeData.getBestPickaxe (Player player) static
Gets the definition for this pickaxe.
Parameters
player the identifier to check for.
Returns
an optional holding the PickaxeData value found, Optional#empty otherwise.
Definition at line 67 of file PickaxeData.java.
{
        return VALUES.stream().filter(def -> player.equipment.contains(def.id) || player.inventory.contains(def.id)).findAny();
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.inventory, and VALUES.
Referenced by com.runehive.content.skill.impl.mining.Mining.attempt(), and com.runehive.content.shootingstar.ShootingStar.mine().
Member Data Documentation
ADAMANT_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.ADAMANT_PICKAXE =(1271, 31, 628, 0.2)
Definition at line 18 of file PickaxeData.java.
animation
final int com.runehive.content.skill.impl.mining.PickaxeData.animation
The animation.
Definition at line 37 of file PickaxeData.java.
Referenced by com.runehive.content.shootingstar.ShootingStar.mine(), PickaxeData(), and com.runehive.content.skill.impl.mining.Mining.start().
BRONZE_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.BRONZE_PICKAXE =(1265, 1, 625, 0.05)
Definition at line 14 of file PickaxeData.java.
DRAGON_OR_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.DRAGON_OR_PICKAXE =(12797, 61, 643, 0.6)
Definition at line 23 of file PickaxeData.java.
DRAGON_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.DRAGON_PICKAXE =(11920, 61, 7139, 0.6)
Definition at line 22 of file PickaxeData.java.
id
final int com.runehive.content.skill.impl.mining.PickaxeData.id
The id.
Definition at line 31 of file PickaxeData.java.
Referenced by PickaxeData().
INFERNO_ADZE
com.runehive.content.skill.impl.mining.PickaxeData.INFERNO_ADZE =(13243, 75, 4483, 0.55)
Definition at line 20 of file PickaxeData.java.
Referenced by com.runehive.content.skill.impl.mining.MiningAction.mine().
IRON_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.IRON_PICKAXE =(1267, 1, 626, 0.08)
Definition at line 15 of file PickaxeData.java.
level
final int com.runehive.content.skill.impl.mining.PickaxeData.level
The level.
Definition at line 34 of file PickaxeData.java.
Referenced by com.runehive.content.skill.impl.mining.Mining.attempt(), com.runehive.content.shootingstar.ShootingStar.mine(), PickaxeData(), com.runehive.content.skill.impl.mining.Mining.success(), and com.runehive.content.skill.impl.mining.Mining.success().
MITHRIL_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.MITHRIL_PICKAXE =(1273, 21, 629, 0.16)
Definition at line 17 of file PickaxeData.java.
RUNE_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.RUNE_PICKAXE =(1275, 41, 624, 0.25)
Definition at line 19 of file PickaxeData.java.
speed
final double com.runehive.content.skill.impl.mining.PickaxeData.speed
The speed of this pickaxe.
Definition at line 42 of file PickaxeData.java.
Referenced by PickaxeData().
STEEL_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.STEEL_PICKAXE =(1269, 6, 627, 0.12)
Definition at line 16 of file PickaxeData.java.
THIRD_AGE_PICKAXE
com.runehive.content.skill.impl.mining.PickaxeData.THIRD_AGE_PICKAXE =(20014, 90, 7283, 0.6)
Definition at line 21 of file PickaxeData.java.
VALUES
final ImmutableSet<PickaxeData> com.runehive.content.skill.impl.mining.PickaxeData.VALUES = ImmutableSet.copyOf(values()) static private
Caches our enum values.
Definition at line 28 of file PickaxeData.java.
Referenced by getBestPickaxe().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/mining/PickaxeData.java