RuneHive-Game: com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode Enum Reference
com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode Enum Reference
Public Member Functions
int getCode ()
PrivacyChatMode (int code)
Static Public Member Functions
static Optional< PrivacyChatMode > get (int code)
static boolean isValid (int code)
Public Attributes
FRIENDS_ONLY =(1)
HIDE =(3)
OFF =(2)
ON =(0)
Private Attributes
final int code
Detailed Description
Definition at line 5 of file PrivacyChatMode.java.
Constructor & Destructor Documentation
PrivacyChatMode()
com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.PrivacyChatMode (int code)
Definition at line 13 of file PrivacyChatMode.java.
{
        this.code = code;
    }
References code.
Referenced by get(), and isValid().
Member Function Documentation
get()
Optional< PrivacyChatMode > com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.get (int code) static
Definition at line 21 of file PrivacyChatMode.java.
{
        if (!isValid(code)) {
            return Optional.empty();
        }
        return Optional.of(PrivacyChatMode.values()[code]);
    }
References code, isValid(), and PrivacyChatMode().
Referenced by com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setPrivacyChatModes().
getCode()
int com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.getCode ()
Definition at line 28 of file PrivacyChatMode.java.
{
        return code;
    }
References code.
isValid()
boolean com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.isValid (int code) static
Definition at line 17 of file PrivacyChatMode.java.
{
        return code >= 0 && code < PrivacyChatMode.values().length;
    }
References code, and PrivacyChatMode().
Referenced by get().
Member Data Documentation
code
final int com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.code private
Definition at line 11 of file PrivacyChatMode.java.
Referenced by get(), getCode(), isValid(), and PrivacyChatMode().
FRIENDS_ONLY
com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.FRIENDS_ONLY =(1)
Definition at line 7 of file PrivacyChatMode.java.
Referenced by com.runehive.content.clanchannel.ClanMember.chat(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.message(), and com.runehive.game.world.entity.mob.player.relations.PlayerRelation.updateLists().
HIDE
com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.HIDE =(3)
Definition at line 9 of file PrivacyChatMode.java.
Referenced by com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setPrivacyChatModes().
OFF
com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.OFF =(2)
Definition at line 8 of file PrivacyChatMode.java.
Referenced by com.runehive.content.clanchannel.ClanMember.chat(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.message(), com.runehive.game.world.entity.mob.player.relations.PlayerRelation.setPrivacyChatModes(), and com.runehive.game.world.entity.mob.player.relations.PlayerRelation.updateLists().
ON
com.runehive.game.world.entity.mob.player.relations.PrivacyChatMode.ON =(0)
Definition at line 6 of file PrivacyChatMode.java.
Referenced by com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteFriend(), and com.runehive.game.world.entity.mob.player.relations.PlayerRelation.deleteIgnore().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/player/relations/PrivacyChatMode.java