RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Glass.GlassData Enum Reference
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData Enum Reference
Holds all the glass data.
Public Member Functions
GlassData (int product, int level, double experience, int material)
Constructs a new GlassData.
Static Public Member Functions
static Optional< GlassData > forGlass (int item)
Gets the glass data based on the material item.
Public Attributes
BEER_GLASS =(1919, 1, 17.5D, 1775)
CANDLE_LANTERN =(4527, 4, 19.0D, 1775)
FISHBOWL =(6667, 42, 42.5D, 1775)
LANTERN_LENS =(4542, 49, 55.0D, 1775)
LIGHT_ORB =(10973, 87, 70.0D, 1775)
MOLTEN_GLASS =(1775, 1, 20.0D, 1781)
OIL_LAMP =(4522, 12, 25.0D, 1775)
UNPOWDERED_ORD =(567, 46, 52.5D, 1775)
VIAL =(229, 33, 35.0D, 1775)
Private Attributes
final double experience
The experienced rewarded.
final int level
The level required.
final int material
The material required.
final int product
The glass product.
Detailed Description
Holds all the glass data.
Definition at line 26 of file Glass.java.
Constructor & Destructor Documentation
GlassData()
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.GlassData (int product, int level, double experience, int material)
Constructs a new GlassData.
Definition at line 50 of file Glass.java.
{
            this.product = product;
            this.level = level;
            this.experience = experience;
            this.material = material;
        }
References experience, level, material, and product.
Member Function Documentation
forGlass()
Optional< GlassData > com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.forGlass (int item) static
Gets the glass data based on the material item.
Definition at line 58 of file Glass.java.
{
            return Arrays.stream(values()).filter(g -> g.material == item).findFirst();
        }
Member Data Documentation
BEER_GLASS
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.BEER_GLASS =(1919, 1, 17.5D, 1775)
Definition at line 29 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.click().
CANDLE_LANTERN
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.CANDLE_LANTERN =(4527, 4, 19.0D, 1775)
Definition at line 30 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.click().
experience
final double com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.experience private
The experienced rewarded.
Definition at line 44 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.blow(), and GlassData().
FISHBOWL
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.FISHBOWL =(6667, 42, 42.5D, 1775)
Definition at line 32 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.click().
LANTERN_LENS
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.LANTERN_LENS =(4542, 49, 55.0D, 1775)
Definition at line 33 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.click().
level
final int com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.level private
The level required.
Definition at line 41 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.craft(), and GlassData().
LIGHT_ORB
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.LIGHT_ORB =(10973, 87, 70.0D, 1775)
Definition at line 28 of file Glass.java.
material
final int com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.material private
The material required.
Definition at line 47 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), and GlassData().
MOLTEN_GLASS
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.MOLTEN_GLASS =(1775, 1, 20.0D, 1781)
Definition at line 34 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.blow(), com.runehive.content.skill.impl.crafting.impl.Glass.craft(), and com.runehive.content.skill.impl.crafting.Crafting.useItem().
OIL_LAMP
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.OIL_LAMP =(4522, 12, 25.0D, 1775)
Definition at line 31 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.click().
product
final int com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.product private
The glass product.
Definition at line 38 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.blow(), and GlassData().
UNPOWDERED_ORD
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.UNPOWDERED_ORD =(567, 46, 52.5D, 1775)
Definition at line 35 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.click().
VIAL
com.runehive.content.skill.impl.crafting.impl.Glass.GlassData.VIAL =(229, 33, 35.0D, 1775)
Definition at line 27 of file Glass.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Glass.click().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Glass.java