RuneHive-Game: com.runehive.content.consume.PotionData Enum Reference
com.runehive.content.consume.PotionData Enum Reference
The enumerated type managing consumable potion types.
Classes
enum BoostType
The enumerated type whose elements represent the boost types for potions.
Public Member Functions
boolean canDrink (Player player)
The method which determines if the player can drink the potion.
int getIdForDose (int dose)
Gets the item id for the specified dose.
final int[] getIds ()
Gets the identifiers which represent this potion type.
abstract void onEffect (Player player)
The method executed when this potion type activated.
PotionData (int... ids)
Create a new PotionData.
Static Public Member Functions
static Optional< PotionData > forId (int id)
Retrieves the potion consumable element for id.
static Item getReplacementItem (Item item)
Retrieves the replacement item for item.
static void onAntiPoisonEffect (Player player, boolean superPotion, int length)
The method that executes the anti-poison potion action.
Public Attributes
AGILITY_POTION
ANTI_VENOM
ANTI_VENOM_PLUS
ANTIDOTE_PLUS
ANTIDOTE_PLUS_PLUS
ANTIFIRE_POTIONS
ANTIPOISON_POTIONS
ATTACK_POTIONS
DEFENCE_POTIONS
ENERGY_POTIONS
FISHING_POTION
MAGIC_POTIONS
PRAYER_POTIONS
RANGE_POTIONS
RESTORE_POTIONS
SARADOMIN_BREW
STAMINA__POTION
STRENGTH_POTIONS
SUPER_ANTIFIRE_POTIONS
SUPER_ANTIPOISON_POTIONS
SUPER_ATTACK_POTIONS
SUPER_COMBAT_POTION
SUPER_DEFENCE_POTIONS
SUPER_ENERGY_POTIONS
SUPER_PRAYER_POTIONS
SUPER_RESTORE_POTIONS
SUPER_STRENGTH_POTIONS
ZAMORAK_BREW
Static Private Member Functions
static void modifySkill (Player player, int skill, double percentage, int base)
The method that executes the basic effect potion action that will append the level of skill.
static void onAgilityEffect (Player player)
The method that executes the agility potion action.
static void onAntiFireEffect (Player player, boolean superVariant)
The method that executes the anti-fireRunes potion action.
static void onBasicEffect (Player player, int skill, BoostType type)
The method that executes the basic effect potion action that will append the level of skill.
static void onEnergyEffect (Player player, boolean superPotion)
The method that executes the energy potion action.
static void onFishingEffect (Player player)
The method that executes the fishing potion action.
static void onPrayerEffect (Player player, boolean superPrayer)
The method that executes the prayer potion action.
static void onRestoreEffect (Player player, boolean superRestore)
The method that executes the restore potion action.
static void onSaradominEffect (Player player)
The method that executes the Saradomin brew action.
static void onZamorakEffect (Player player)
The method that executes the Zamorak brew action.
Private Attributes
final int[] ids
The identifiers which represent this potion type.
Static Private Attributes
static final ImmutableSet< PotionData > VALUES = Sets.immutableEnumSet(EnumSet.allOf(PotionData.class))
Caches our enum values.
static final Item VIAL = new Item(229)
The default item representing the final potion dose.
Detailed Description
The enumerated type managing consumable potion types.
Author
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
lare96 http://github.com/lare96
Definition at line 29 of file PotionData.java.
Constructor & Destructor Documentation
PotionData()
com.runehive.content.consume.PotionData.PotionData (int... ids)
Create a new PotionData.
Parameters
ids the identifiers which represent this potion type.
Definition at line 259 of file PotionData.java.
{
        this.ids = ids;
    }
References ids.
Referenced by forId().
Member Function Documentation
canDrink()
boolean com.runehive.content.consume.PotionData.canDrink (Player player)
The method which determines if the player can drink the potion.
Parameters
player the player to determine this for.
Definition at line 505 of file PotionData.java.
{
        return true;
    }
Referenced by com.runehive.content.bot.PlayerBot.pot().
forId()
Optional< PotionData > com.runehive.content.consume.PotionData.forId (int id) static
Retrieves the potion consumable element for id.
Parameters
id the id that the potion consumable is attached to.
Returns
the potion consumable wrapped in an optional, or an empty optional if no potion consumable was found.
Definition at line 482 of file PotionData.java.
{
        for (PotionData potion : VALUES) {
            for (int potionId : potion.getIds()) {
                if (id == potionId) {
                    return Optional.of(potion);
                }
            }
        }
        return Optional.empty();
    }
References PotionData(), and VALUES.
Referenced by getReplacementItem(), and com.runehive.content.bot.objective.impl.RestockObjective.init().
getIdForDose()
int com.runehive.content.consume.PotionData.getIdForDose (int dose)
Gets the item id for the specified dose.
Parameters
dose the dose to get the item id from.
Returns
the item id.
Definition at line 524 of file PotionData.java.
{
        return ids[ids.length - dose];
    }
References ids.
getIds()
final int[] com.runehive.content.consume.PotionData.getIds ()
Gets the identifiers which represent this potion type.
Returns
the identifiers for this potion.
Definition at line 514 of file PotionData.java.
{
        return ids;
    }
References ids.
getReplacementItem()
Item com.runehive.content.consume.PotionData.getReplacementItem (Item item) static
Retrieves the replacement item for item.
Parameters
item the item to retrieve the replacement item for.
Returns
the replacement item wrapped in an optional, or an empty optional if no replacement item is available.
Definition at line 462 of file PotionData.java.
{
        Optional<PotionData> potion = forId(item.getId());
        if (potion.isPresent()) {
            int length = potion.get().getIds().length;
            for (int index = 0; index < length; index++) {
                if (potion.get().getIds()[index] == item.getId() && index + 1 < length) {
                    return new Item(potion.get().getIds()[index + 1]);
                }
            }
        }
        return VIAL;
    }
References forId(), com.runehive.game.world.items.Item.getId(), and VIAL.
Referenced by com.runehive.content.bot.PlayerBot.pot().
modifySkill()
void com.runehive.content.consume.PotionData.modifySkill (Player player, int skill, double percentage, int base) static private
The method that executes the basic effect potion action that will append the level of skill.
Parameters
player the player to do this action for.
Definition at line 433 of file PotionData.java.
{
        Skill s = player.skills.get(skill);
        int realLevel = s.getMaxLevel();
        final int boostLevel = (int) (realLevel * percentage + base);
        int cap = s.getLevel();
        if (cap < realLevel + boostLevel) {
            cap = realLevel + boostLevel;
        }
        if (skill == Skill.HITPOINTS && boostLevel < 0) {
            int damage = boostLevel;
            if (player.getCurrentHealth() + damage <= 0) damage = -player.getCurrentHealth() + 1;
            player.damage(new Hit(-damage));
        } else {
            player.skills.get(skill).modifyLevel(level -> level + boostLevel, 0, cap);
        }
        player.skills.refresh(skill);
    }
References com.runehive.game.world.entity.mob.Mob.damage(), com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.mob.Mob.getCurrentHealth(), com.runehive.game.world.entity.skill.Skill.getLevel(), com.runehive.game.world.entity.skill.Skill.getMaxLevel(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.game.world.entity.skill.Skill.modifyLevel(), com.runehive.game.world.entity.skill.SkillManager.refresh(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by onBasicEffect(), onSaradominEffect(), and onZamorakEffect().
onAgilityEffect()
void com.runehive.content.consume.PotionData.onAgilityEffect (Player player) static private
The method that executes the agility potion action.
Parameters
player the player to do this action for.
Definition at line 278 of file PotionData.java.
{
        player.skills.get(Skill.AGILITY).modifyLevel(level -> level + 3);
        player.skills.refresh(Skill.AGILITY);
    }
References com.runehive.game.world.entity.skill.Skill.AGILITY, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.Skill.modifyLevel(), com.runehive.game.world.entity.skill.SkillManager.refresh(), and com.runehive.game.world.entity.mob.Mob.skills.
onAntiFireEffect()
void com.runehive.content.consume.PotionData.onAntiFireEffect (Player player, boolean superVariant) static private
The method that executes the anti-fireRunes potion action.
Parameters
player the player to do this action for.
superVariant determines if this potion is the super variant.
Definition at line 409 of file PotionData.java.
{
        if (superVariant) {
            CombatUtil.effect(player, CombatEffectType.SUPER_ANTIFIRE_POTION);
        } else {
            CombatUtil.effect(player, CombatEffectType.ANTIFIRE_POTION);
        }
    }
References com.runehive.game.world.entity.combat.effect.CombatEffectType.ANTIFIRE_POTION, com.runehive.game.world.entity.combat.CombatUtil.effect(), and com.runehive.game.world.entity.combat.effect.CombatEffectType.SUPER_ANTIFIRE_POTION.
onAntiPoisonEffect()
void com.runehive.content.consume.PotionData.onAntiPoisonEffect (Player player, boolean superPotion, int length) static
The method that executes the anti-poison potion action.
Parameters
player the player to do this action for.
superPotion true if this potion is a super potion,
false otherwise.
length the length that the effect lingers for.
Definition at line 331 of file PotionData.java.
{
        if (player.isVenomed()) {
            player.getVenomDamage().set(0);
            CombatUtil.cancelEffect(player, CombatEffectType.VENOM);
            player.poison(PoisonType.WEAK_NPC);
            return;
        }
        if (player.isPoisoned()) {
            player.getPoisonDamage().set(0);
            CombatUtil.cancelEffect(player, CombatEffectType.POISON);
            player.send(new SendConfig(174, 0));
            player.send(new SendMessage("You have been cured of your poison!"));
            player.send(new SendPoison(SendPoison.PoisonType.NO_POISON));
        }
        if (superPotion) {
            if (length > 0 && player.getPoisonImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against poison."));
                player.getPoisonImmunity().incrementAndGet(length);
                World.schedule(new SuperAntipoisonTask(player).attach(player));
            } else if (player.getPoisonImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against poison has been restored!"));
                player.getPoisonImmunity().set(length);
            }
        }
    }
References com.runehive.game.world.entity.combat.CombatUtil.cancelEffect(), com.runehive.util.MutableNumber.get(), com.runehive.game.world.entity.mob.Mob.getPoisonDamage(), com.runehive.game.world.entity.mob.player.Player.getPoisonImmunity(), com.runehive.game.world.entity.mob.Mob.getVenomDamage(), com.runehive.util.MutableNumber.incrementAndGet(), com.runehive.game.world.entity.mob.Mob.isPoisoned(), com.runehive.game.world.entity.mob.Mob.isVenomed(), com.runehive.net.packet.out.SendPoison.PoisonType.NO_POISON, com.runehive.game.world.entity.combat.effect.CombatEffectType.POISON, com.runehive.game.world.entity.mob.Mob.poison(), com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.MutableNumber.set(), com.runehive.game.world.entity.combat.effect.CombatEffectType.VENOM, and com.runehive.game.world.entity.combat.PoisonType.WEAK_NPC.
onBasicEffect()
void com.runehive.content.consume.PotionData.onBasicEffect (Player player, int skill, BoostType type) static private
The method that executes the basic effect potion action that will append the level of skill.
Parameters
player the player to do this action for.
Definition at line 423 of file PotionData.java.
{
        modifySkill(player, skill, type.amount, type.base);
    }
References com.runehive.content.consume.PotionData.BoostType.amount, com.runehive.content.consume.PotionData.BoostType.base, and modifySkill().
onEffect()
abstract void com.runehive.content.consume.PotionData.onEffect (Player player) abstract
The method executed when this potion type activated.
Parameters
player the player to execute this effect for.
Referenced by com.runehive.content.bot.PlayerBot.pot().
onEnergyEffect()
void com.runehive.content.consume.PotionData.onEnergyEffect (Player player, boolean superPotion) static private
The method that executes the energy potion action.
Parameters
player the player to do this action for.
superPotion true if this potion is a super potion,
false otherwise.
Definition at line 366 of file PotionData.java.
{
        int amount = superPotion ? 20 : 10;
        int energy = player.runEnergy;
        if (amount + energy > 100) {
            player.runEnergy = 100;
        } else {
            player.runEnergy += amount;
        }
        player.send(new SendRunEnergy());
    }
References com.runehive.game.world.entity.mob.player.Player.runEnergy, and com.runehive.game.world.entity.mob.player.Player.send().
onFishingEffect()
void com.runehive.content.consume.PotionData.onFishingEffect (Player player) static private
The method that executes the fishing potion action.
Parameters
player the player to do this action for.
Definition at line 268 of file PotionData.java.
{
        player.skills.get(Skill.FISHING).modifyLevel(level -> level + 3);
        player.skills.refresh(Skill.FISHING);
    }
References com.runehive.game.world.entity.skill.Skill.FISHING, com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.Skill.modifyLevel(), com.runehive.game.world.entity.skill.SkillManager.refresh(), and com.runehive.game.world.entity.mob.Mob.skills.
onPrayerEffect()
void com.runehive.content.consume.PotionData.onPrayerEffect (Player player, boolean superPrayer) static private
The method that executes the prayer potion action.
Parameters
player the player to do this action for.
superPrayer determines if this potion is a super prayer potion.
Definition at line 316 of file PotionData.java.
{
        int realLevel = player.skills.get(Skill.PRAYER).getMaxLevel();
        player.skills.get(Skill.PRAYER).modifyLevel(level -> level + (int) Math.floor(7 + (realLevel * (superPrayer ? 0.35 : 0.25))));
        player.skills.refresh(Skill.PRAYER);
    }
References com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.Skill.getMaxLevel(), com.runehive.game.world.entity.skill.Skill.modifyLevel(), com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.skill.SkillManager.refresh(), and com.runehive.game.world.entity.mob.Mob.skills.
onRestoreEffect()
void com.runehive.content.consume.PotionData.onRestoreEffect (Player player, boolean superRestore) static private
The method that executes the restore potion action.
Parameters
player the player to do this action for.
Definition at line 384 of file PotionData.java.
{
        for (int index = 0; index <= 6; index++) {
            if ((index == Skill.PRAYER) || (index == Skill.HITPOINTS)) {
                continue;
            }
            Skill skill = player.skills.get(index);
            int realLevel = skill.getMaxLevel();
            if (skill.getLevel() >= realLevel) {
                continue;
            }
            int formula = superRestore ? (int) Math.floor(8 + (realLevel * 0.25)) : (int) Math.floor(10 + (realLevel * 0.30));
            player.skills.get(index).modifyLevel(level -> level + formula);
            player.skills.refresh(index);
        }
    }
References com.runehive.game.world.entity.skill.SkillManager.get(), com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.game.world.entity.skill.Skill.modifyLevel(), com.runehive.game.world.entity.skill.Skill.PRAYER, com.runehive.game.world.entity.skill.SkillManager.refresh(), and com.runehive.game.world.entity.mob.Mob.skills.
onSaradominEffect()
void com.runehive.content.consume.PotionData.onSaradominEffect (Player player) static private
The method that executes the Saradomin brew action.
Parameters
player the player to do this action for.
Definition at line 288 of file PotionData.java.
{
        modifySkill(player, Skill.HITPOINTS, 0.15, 2);
        modifySkill(player, Skill.DEFENCE, 0.20, 2);
        modifySkill(player, Skill.ATTACK, -0.10, 2);
        modifySkill(player, Skill.STRENGTH, -0.10, 2);
        modifySkill(player, Skill.RANGED, -0.10, 2);
        modifySkill(player, Skill.MAGIC, -0.10, 2);
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.skill.Skill.HITPOINTS, com.runehive.game.world.entity.skill.Skill.MAGIC, modifySkill(), com.runehive.game.world.entity.skill.Skill.RANGED, and com.runehive.game.world.entity.skill.Skill.STRENGTH.
onZamorakEffect()
void com.runehive.content.consume.PotionData.onZamorakEffect (Player player) static private
The method that executes the Zamorak brew action.
Parameters
player the player to do this action for.
Definition at line 302 of file PotionData.java.
{
        modifySkill(player, Skill.ATTACK, 0.20, 2);
        modifySkill(player, Skill.STRENGTH, 0.12, 2);
        modifySkill(player, Skill.DEFENCE, -0.10, 2);
        modifySkill(player, Skill.HITPOINTS, -0.10, 2);
        modifySkill(player, Skill.PRAYER, 0.10, 0);
    }
References com.runehive.game.world.entity.skill.Skill.ATTACK, com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.skill.Skill.HITPOINTS, modifySkill(), com.runehive.game.world.entity.skill.Skill.PRAYER, and com.runehive.game.world.entity.skill.Skill.STRENGTH.
Member Data Documentation
AGILITY_POTION
com.runehive.content.consume.PotionData.AGILITY_POTION
Initial value:
=(3032, 3034, 3036, 3038) {
        @Override
        public void onEffect(Player player) {
            PotionData.onAgilityEffect(player);
        }
    }
Definition at line 69 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onAgilityEffect(player);
        }
    },
ANTI_VENOM
com.runehive.content.consume.PotionData.ANTI_VENOM
Initial value:
=(12905, 12907, 12909, 12911) {
        @Override
        public void onEffect(Player player) {
            player.unvenom();
            player.unpoison();
            if (player.getPoisonImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against poison."));
                World.schedule(new SuperAntipoisonTask(player).attach(player));
            } else if (player.getPoisonImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against poison has been restored!"));
            }
            player.getPoisonImmunity().set(1200);
            if (player.getVenomImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against venom."));
                World.schedule(new AntiVenomTask(player).attach(player));
            } else if (player.getVenomImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against venom has been restored!"));
            }
            player.getVenomImmunity().set(300);
        }
    }
Definition at line 192 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            player.unvenom();
            player.unpoison();
            if (player.getPoisonImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against poison."));
                World.schedule(new SuperAntipoisonTask(player).attach(player));
            } else if (player.getPoisonImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against poison has been restored!"));
            }
            player.getPoisonImmunity().set(1200);
            if (player.getVenomImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against venom."));
                World.schedule(new AntiVenomTask(player).attach(player));
            } else if (player.getVenomImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against venom has been restored!"));
            }
            player.getVenomImmunity().set(300);
        }
    },
ANTI_VENOM_PLUS
com.runehive.content.consume.PotionData.ANTI_VENOM_PLUS
Initial value:
=(12913, 12915, 12917, 12919) {
        @Override
        public void onEffect(Player player) {
            player.unvenom();
            player.unpoison();
            if (player.getPoisonImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against poison."));
                World.schedule(new SuperAntipoisonTask(player).attach(player));
            } else if (player.getPoisonImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against poison has been restored!"));
            }
            player.getPoisonImmunity().set(1500);
            if (player.getVenomImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against venom."));
                World.schedule(new AntiVenomTask(player).attach(player));
            } else if (player.getVenomImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against venom has been restored!"));
            }
            player.getVenomImmunity().set(3000);
        }
    }
Definition at line 237 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            player.unvenom();
            player.unpoison();
            if (player.getPoisonImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against poison."));
                World.schedule(new SuperAntipoisonTask(player).attach(player));
            } else if (player.getPoisonImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against poison has been restored!"));
            }
            player.getPoisonImmunity().set(1500);
            if (player.getVenomImmunity().get() <= 0) {
                player.send(new SendMessage("You have been granted immunity against venom."));
                World.schedule(new AntiVenomTask(player).attach(player));
            } else if (player.getVenomImmunity().get() > 0) {
                player.send(new SendMessage("Your immunity against venom has been restored!"));
            }
            player.getVenomImmunity().set(3000);
        }
    };
ANTIDOTE_PLUS
com.runehive.content.consume.PotionData.ANTIDOTE_PLUS
Initial value:
=(5943, 5945, 5947, 5949) {
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiPoisonEffect(player, true, 1000);
        }
    }
Definition at line 57 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiPoisonEffect(player, true, 1000);
        }
    },
ANTIDOTE_PLUS_PLUS
com.runehive.content.consume.PotionData.ANTIDOTE_PLUS_PLUS
Initial value:
=(5952, 5954, 5956, 5958) {
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiPoisonEffect(player, true, 1200);
        }
    }
Definition at line 63 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiPoisonEffect(player, true, 1200);
        }
    },
ANTIFIRE_POTIONS
com.runehive.content.consume.PotionData.ANTIFIRE_POTIONS
Initial value:
=(2452, 2454, 2456, 2458) {
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiFireEffect(player, false);
        }
    }
Definition at line 168 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiFireEffect(player, false);
        }
    },
ANTIPOISON_POTIONS
com.runehive.content.consume.PotionData.ANTIPOISON_POTIONS
Initial value:
=(2446, 175, 177, 179) {
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiPoisonEffect(player, false, 0);
        }
    }
Definition at line 180 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiPoisonEffect(player, false, 0);
        }
    },
ATTACK_POTIONS
com.runehive.content.consume.PotionData.ATTACK_POTIONS
Initial value:
=(2428, 121, 123, 125) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.ATTACK, BoostType.NORMAL);
        }
    }
Definition at line 117 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.ATTACK, BoostType.NORMAL);
        }
    },
DEFENCE_POTIONS
com.runehive.content.consume.PotionData.DEFENCE_POTIONS
Initial value:
=(2432, 133, 135, 137) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.DEFENCE, BoostType.NORMAL);
        }
    }
Definition at line 105 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.DEFENCE, BoostType.NORMAL);
        }
    },
ENERGY_POTIONS
com.runehive.content.consume.PotionData.ENERGY_POTIONS
Initial value:
=(3008, 3010, 3012, 3014) {
        @Override
        public void onEffect(Player player) {
            PotionData.onEnergyEffect(player, false);
        }
    }
Definition at line 87 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onEnergyEffect(player, false);
        }
    },
FISHING_POTION
com.runehive.content.consume.PotionData.FISHING_POTION
Initial value:
=(2438, 151, 153, 155) {
        @Override
        public void onEffect(Player player) {
            PotionData.onFishingEffect(player);
        }
    }
Definition at line 75 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onFishingEffect(player);
        }
    },
ids
final int [] com.runehive.content.consume.PotionData.ids private
The identifiers which represent this potion type.
Definition at line 252 of file PotionData.java.
Referenced by getIdForDose(), getIds(), and PotionData().
MAGIC_POTIONS
com.runehive.content.consume.PotionData.MAGIC_POTIONS
Initial value:
=(3040, 3042, 3044, 3046) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.MAGIC, BoostType.MAGIC);
        }
    }
Definition at line 99 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.MAGIC, BoostType.MAGIC);
        }
    },
PRAYER_POTIONS
com.runehive.content.consume.PotionData.PRAYER_POTIONS
Initial value:
=(2434, 139, 141, 143) {
        @Override
        public void onEffect(Player player) {
            PotionData.onPrayerEffect(player, false);
        }
    }
Definition at line 156 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onPrayerEffect(player, false);
        }
    },
RANGE_POTIONS
com.runehive.content.consume.PotionData.RANGE_POTIONS
Initial value:
=(2444, 169, 171, 173) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.RANGED, BoostType.RANGING);
        }
    }
Definition at line 81 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.RANGED, BoostType.RANGING);
        }
    },
Referenced by com.runehive.content.bot.botclass.impl.PureRangeMelee.pot().
RESTORE_POTIONS
com.runehive.content.consume.PotionData.RESTORE_POTIONS
Initial value:
=(2430, 127, 129, 131) {
        @Override
        public void onEffect(Player player) {
            onRestoreEffect(player, false);
        }
    }
Definition at line 141 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            onRestoreEffect(player, false);
        }
    },
SARADOMIN_BREW
com.runehive.content.consume.PotionData.SARADOMIN_BREW
Initial value:
=(6685, 6687, 6689, 6691) {
        @Override
        public void onEffect(Player player) {
            PotionData.onSaradominEffect(player);
        }
    }
Definition at line 51 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onSaradominEffect(player);
        }
    },
Referenced by com.runehive.content.bot.objective.impl.RestockObjective.init().
STAMINA__POTION
com.runehive.content.consume.PotionData.STAMINA__POTION
Initial value:
=(12625, 12627, 12629, 12631) {
        @Override
        public void onEffect(Player player) {
            PotionData.onEnergyEffect(player, true);
            player.energyRate = 200;
        }
    }
Definition at line 30 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onEnergyEffect(player, true);
            player.energyRate = 200;
        }
    },
STRENGTH_POTIONS
com.runehive.content.consume.PotionData.STRENGTH_POTIONS
Initial value:
=(113, 115, 117, 119) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.STRENGTH, BoostType.NORMAL);
        }
    }
Definition at line 111 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.STRENGTH, BoostType.NORMAL);
        }
    },
SUPER_ANTIFIRE_POTIONS
com.runehive.content.consume.PotionData.SUPER_ANTIFIRE_POTIONS
Initial value:
=(15304, 15305, 15306, 15307) {
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiFireEffect(player, true);
        }
    }
Definition at line 174 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiFireEffect(player, true);
        }
    },
SUPER_ANTIPOISON_POTIONS
com.runehive.content.consume.PotionData.SUPER_ANTIPOISON_POTIONS
Initial value:
=(2448, 181, 183, 185) {
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiPoisonEffect(player, true, 500);
        }
    }
Definition at line 186 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onAntiPoisonEffect(player, true, 500);
        }
    },
SUPER_ATTACK_POTIONS
com.runehive.content.consume.PotionData.SUPER_ATTACK_POTIONS
Initial value:
=(2436, 145, 147, 149) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.ATTACK, BoostType.SUPER);
        }
    }
Definition at line 129 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.ATTACK, BoostType.SUPER);
        }
    },
SUPER_COMBAT_POTION
com.runehive.content.consume.PotionData.SUPER_COMBAT_POTION
Initial value:
=(12695, 12697, 12699, 12701) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.ATTACK, BoostType.SUPER);
            PotionData.onBasicEffect(player, Skill.STRENGTH, BoostType.SUPER);
            PotionData.onBasicEffect(player, Skill.DEFENCE, BoostType.SUPER);
        }
    }
Definition at line 37 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.ATTACK, BoostType.SUPER);
            PotionData.onBasicEffect(player, Skill.STRENGTH, BoostType.SUPER);
            PotionData.onBasicEffect(player, Skill.DEFENCE, BoostType.SUPER);
        }
    },
Referenced by com.runehive.content.bot.botclass.impl.AGSRuneMelee.pot(), com.runehive.content.bot.botclass.impl.PureMelee.pot(), com.runehive.content.bot.botclass.impl.PureRangeMelee.pot(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.pot(), and com.runehive.content.bot.botclass.impl.ZerkerMelee.pot().
SUPER_DEFENCE_POTIONS
com.runehive.content.consume.PotionData.SUPER_DEFENCE_POTIONS
Initial value:
=(2442, 163, 165, 167) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.DEFENCE, BoostType.SUPER);
        }
    }
Definition at line 123 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.DEFENCE, BoostType.SUPER);
        }
    },
SUPER_ENERGY_POTIONS
com.runehive.content.consume.PotionData.SUPER_ENERGY_POTIONS
Initial value:
=(3016, 3018, 3020, 3022) {
        @Override
        public void onEffect(Player player) {
            PotionData.onEnergyEffect(player, true);
        }
    }
Definition at line 93 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onEnergyEffect(player, true);
        }
    },
SUPER_PRAYER_POTIONS
com.runehive.content.consume.PotionData.SUPER_PRAYER_POTIONS
Initial value:
=(15328, 15329, 15330, 15331) {
        @Override
        public void onEffect(Player player) {
            PotionData.onPrayerEffect(player, true);
        }
    }
Definition at line 162 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onPrayerEffect(player, true);
        }
    },
SUPER_RESTORE_POTIONS
com.runehive.content.consume.PotionData.SUPER_RESTORE_POTIONS
Initial value:
=(3024, 3026, 3028, 3030) {
        @Override
        public void onEffect(Player player) {
            PotionData.onRestoreEffect(player, true);
            int realLevel = player.skills.getMaxLevel(Skill.PRAYER);
            player.skills.get(Skill.PRAYER).modifyLevel(level -> level + (int) Math.floor(8 + (realLevel * 0.25)));
            player.skills.refresh(Skill.PRAYER);
        }
    }
Definition at line 147 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onRestoreEffect(player, true);
            int realLevel = player.skills.getMaxLevel(Skill.PRAYER);
            player.skills.get(Skill.PRAYER).modifyLevel(level -> level + (int) Math.floor(8 + (realLevel * 0.25)));
            player.skills.refresh(Skill.PRAYER);
        }
    },
Referenced by com.runehive.content.bot.objective.impl.RestockObjective.init(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.pot(), com.runehive.content.bot.botclass.impl.PureMelee.pot(), com.runehive.content.bot.botclass.impl.PureRangeMelee.pot(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.pot(), and com.runehive.content.bot.botclass.impl.ZerkerMelee.pot().
SUPER_STRENGTH_POTIONS
com.runehive.content.consume.PotionData.SUPER_STRENGTH_POTIONS
Initial value:
=(2440, 157, 159, 161) {
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.STRENGTH, BoostType.SUPER);
        }
    }
Definition at line 135 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onBasicEffect(player, Skill.STRENGTH, BoostType.SUPER);
        }
    },
VALUES
final ImmutableSet<PotionData> com.runehive.content.consume.PotionData.VALUES = Sets.immutableEnumSet(EnumSet.allOf(PotionData.class)) static private
Caches our enum values.
Definition at line 242 of file PotionData.java.
Referenced by forId().
VIAL
final Item com.runehive.content.consume.PotionData.VIAL = new Item(229) static private
The default item representing the final potion dose.
Definition at line 247 of file PotionData.java.
Referenced by getReplacementItem().
ZAMORAK_BREW
com.runehive.content.consume.PotionData.ZAMORAK_BREW
Initial value:
=(2450, 189, 191, 193) {
        @Override
        public void onEffect(Player player) {
            PotionData.onZamorakEffect(player);
        }
    }
Definition at line 45 of file PotionData.java.
{
        @Override
        public void onEffect(Player player) {
            PotionData.onZamorakEffect(player);
        }
    },
The documentation for this enum was generated from the following file:
java/com/runehive/content/consume/PotionData.java