RuneHive-Game: com.runehive.game.world.entity.mob.UpdateFlag Enum Reference
com.runehive.game.world.entity.mob.UpdateFlag Enum Reference
Entity update flags.
Public Member Functions
boolean canApply (Npc npc)
boolean canApply (Player player, Player other, SendPlayerUpdate.UpdateState state)
UpdateFlag (int playerMask, int npcMask)
Static Public Member Functions
static boolean contains (int masks, int mask)
static boolean containsNpc (int masks, UpdateFlag flag)
static boolean containsPlayer (int masks, UpdateFlag flag)
Public Attributes
ANIMATION
APPEARANCE =(0x10, -1)
CHAT
FACE_COORDINATE =(0x2, 0x4)
FIRST_HIT =(0x20, 0x40)
FORCE_MOVEMENT
FORCED_CHAT =(0x4, 0x1)
GRAPHICS
INTERACT =(0x1, 0x20)
final int npcMask
final int playerMask
SECOND_HIT =(0x200, 0x8)
TRANSFORM =(-1, 0x2)
Static Public Attributes
static final UpdateFlag[] npcOrder
static final UpdateFlag[] playerOrder
Detailed Description
Entity update flags.
Author
Michael | Chex
Jire
Definition at line 13 of file UpdateFlag.java.
Constructor & Destructor Documentation
UpdateFlag()
com.runehive.game.world.entity.mob.UpdateFlag.UpdateFlag (int playerMask, int npcMask)
Definition at line 59 of file UpdateFlag.java.
{
        this.playerMask = playerMask;
        this.npcMask = npcMask;
    }
References npcMask, and playerMask.
Referenced by containsNpc(), and containsPlayer().
Member Function Documentation
canApply() [1/2]
boolean com.runehive.game.world.entity.mob.UpdateFlag.canApply (Npc npc)
Definition at line 104 of file UpdateFlag.java.
{
        return true;
    }
canApply() [2/2]
boolean com.runehive.game.world.entity.mob.UpdateFlag.canApply (Player player, Player other, SendPlayerUpdate.UpdateState state)
Definition at line 100 of file UpdateFlag.java.
{
        return true;
    }
Referenced by com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
contains()
boolean com.runehive.game.world.entity.mob.UpdateFlag.contains (int masks, int mask) static
Definition at line 88 of file UpdateFlag.java.
{
        return (masks & mask) != 0;
    }
Referenced by containsNpc(), and containsPlayer().
containsNpc()
boolean com.runehive.game.world.entity.mob.UpdateFlag.containsNpc (int masks, UpdateFlag flag) static
Definition at line 96 of file UpdateFlag.java.
{
        return contains(masks, flag.npcMask);
    }
References contains(), npcMask, and UpdateFlag().
Referenced by com.runehive.net.packet.out.SendNpcUpdate.updateNpc().
containsPlayer()
boolean com.runehive.game.world.entity.mob.UpdateFlag.containsPlayer (int masks, UpdateFlag flag) static
Definition at line 92 of file UpdateFlag.java.
{
        return contains(masks, flag.playerMask);
    }
References contains(), playerMask, and UpdateFlag().
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
Member Data Documentation
ANIMATION
com.runehive.game.world.entity.mob.UpdateFlag.ANIMATION
Initial value:
=(0x8, 0x10) {
        @Override
        public boolean canApply(Player player, Player other, SendPlayerUpdate.UpdateState state) {
            return other.getAnimation().isPresent();
        }
        @Override
        public boolean canApply(Npc npc) {
            return npc.getAnimation().isPresent();
        }
    }
Definition at line 32 of file UpdateFlag.java.
{
        @Override
        public boolean canApply(Player player, Player other, SendPlayerUpdate.UpdateState state) {
            return other.getAnimation().isPresent();
        }
        @Override
        public boolean canApply(Npc npc) {
            return npc.getAnimation().isPresent();
        }
    },
Referenced by com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
APPEARANCE
com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE =(0x10, -1)
Definition at line 14 of file UpdateFlag.java.
Referenced by com.runehive.content.preset.PresetManager.activate(), com.runehive.game.world.entity.mob.Viewport.add(), com.runehive.content.clanchannel.channel.ClanChannel.addExperience(), com.runehive.game.world.items.containers.equipment.Equipment.appearanceForIndex(), com.runehive.content.clanchannel.channel.ClanChannel.ban(), com.runehive.content.clanchannel.channel.ClanChannel.disconnect(), com.runehive.game.action.impl.TeleportAction.end(), com.runehive.content.overrides.Overrides.equipOverride(), com.runehive.content.clanchannel.channel.ClanChannel.establish(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.net.packet.in.ColorPacketListener.handlePacket(), com.runehive.game.world.entity.combat.attack.listener.item.StarterAgsListener.hit(), com.runehive.game.world.entity.combat.attack.listener.item.StarterWhipListener.hit(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.game.world.entity.skill.SkillManager.master(), com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction.onExecution(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.content.tittle.TitleManager.redeem(), com.runehive.content.StarterKit.refresh(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.removeAmmunition(), com.runehive.content.overrides.Overrides.removeOverride(), com.runehive.content.tittle.TitleManager.reset(), com.runehive.game.world.entity.mob.MobAnimation.reset(), com.runehive.game.world.entity.mob.player.PlayerAssistant.reset(), com.runehive.game.world.entity.mob.MobAnimation.set(), com.runehive.game.world.entity.mob.player.PlayerAssistant.setActivity(), com.runehive.game.world.entity.mob.MobAnimation.setNpcAnimations(), com.runehive.game.world.entity.mob.player.PlayerAssistant.setPrayer(), com.runehive.game.world.entity.mob.MobAnimation.setRun(), com.runehive.game.world.entity.mob.MobAnimation.setStand(), com.runehive.game.world.entity.mob.MobAnimation.setTurn(), com.runehive.game.world.entity.mob.MobAnimation.setTurn180(), com.runehive.game.world.entity.mob.MobAnimation.setTurn90CCW(), com.runehive.game.world.entity.mob.MobAnimation.setTurn90CW(), com.runehive.game.world.entity.mob.player.PlayerAssistant.setValueIcon(), com.runehive.game.world.entity.mob.MobAnimation.setWalk(), com.runehive.content.combat.Skulling.skull(), com.runehive.game.world.entity.mob.Mob.transform(), com.runehive.game.world.entity.mob.player.PlayerAssistant.transform(), com.runehive.content.combat.Skulling.unskull(), com.runehive.game.world.entity.skill.SkillManager.updateCombat(), com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer(), and com.runehive.content.donators.Donation.updateRank().
CHAT
com.runehive.game.world.entity.mob.UpdateFlag.CHAT
Initial value:
=(0x80, -1) {
        @Override
        public boolean canApply(Player player, Player other, SendPlayerUpdate.UpdateState state) {
            return state != SendPlayerUpdate.UpdateState.UPDATE_SELF && other.getChatMessage().isPresent();
        }
    }
Definition at line 15 of file UpdateFlag.java.
                   {
        @Override
        public boolean canApply(Player player, Player other, SendPlayerUpdate.UpdateState state) {
            return state != SendPlayerUpdate.UpdateState.UPDATE_SELF && other.getChatMessage().isPresent();
        }
    },
Referenced by com.runehive.game.world.entity.mob.player.Player.chat(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
FACE_COORDINATE
com.runehive.game.world.entity.mob.UpdateFlag.FACE_COORDINATE =(0x2, 0x4)
Definition at line 45 of file UpdateFlag.java.
Referenced by com.runehive.game.world.entity.mob.Viewport.add(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
FIRST_HIT
com.runehive.game.world.entity.mob.UpdateFlag.FIRST_HIT =(0x20, 0x40)
Definition at line 46 of file UpdateFlag.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer(), com.runehive.game.world.entity.mob.Mob.writeDamage(), and com.runehive.game.world.entity.mob.Mob.writeFakeDamage().
FORCE_MOVEMENT
com.runehive.game.world.entity.mob.UpdateFlag.FORCE_MOVEMENT
Initial value:
=(0x400, -1) {
        @Override
        public boolean canApply(Player player, Player other, SendPlayerUpdate.UpdateState state) {
            return other.getForceMovement() != null;
        }
    }
Definition at line 54 of file UpdateFlag.java.
{
        @Override
        public boolean canApply(Player player, Player other, SendPlayerUpdate.UpdateState state) {
            return other.getForceMovement() != null;
        }
    };
Referenced by com.runehive.game.world.entity.mob.Mob.setForceMovement(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
FORCED_CHAT
com.runehive.game.world.entity.mob.UpdateFlag.FORCED_CHAT =(0x4, 0x1)
Definition at line 43 of file UpdateFlag.java.
Referenced by com.runehive.game.world.entity.mob.Mob.speak(), com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
GRAPHICS
com.runehive.game.world.entity.mob.UpdateFlag.GRAPHICS
Initial value:
=(0x100, 0x80) {
        @Override
        public boolean canApply(Player player, Player other, SendPlayerUpdate.UpdateState state) {
            return other.getGraphic().isPresent();
        }
        @Override
        public boolean canApply(Npc npc) {
            return npc.getGraphic().isPresent();
        }
    }
Definition at line 21 of file UpdateFlag.java.
{
        @Override
        public boolean canApply(Player player, Player other, SendPlayerUpdate.UpdateState state) {
            return other.getGraphic().isPresent();
        }
        @Override
        public boolean canApply(Npc npc) {
            return npc.getGraphic().isPresent();
        }
    },
Referenced by com.runehive.game.world.entity.mob.Mob.graphic(), com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
INTERACT
com.runehive.game.world.entity.mob.UpdateFlag.INTERACT =(0x1, 0x20)
Definition at line 44 of file UpdateFlag.java.
Referenced by com.runehive.game.world.entity.mob.Mob.interact(), com.runehive.game.world.entity.mob.Mob.resetFace(), com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
npcMask
final int com.runehive.game.world.entity.mob.UpdateFlag.npcMask
Definition at line 57 of file UpdateFlag.java.
Referenced by containsNpc(), UpdateFlag(), and com.runehive.net.packet.out.SendNpcUpdate.updateNpc().
npcOrder
final UpdateFlag [] com.runehive.game.world.entity.mob.UpdateFlag.npcOrder static
Initial value:
= {
            ANIMATION,
            GRAPHICS,
            INTERACT,
            FORCED_CHAT,
            FIRST_HIT,
            SECOND_HIT,
            TRANSFORM,
            FACE_COORDINATE
    }
Definition at line 86 of file UpdateFlag.java.
{
            ANIMATION,
            GRAPHICS,
            INTERACT,
            FORCED_CHAT,
            FIRST_HIT,
            SECOND_HIT,
            TRANSFORM,
            FACE_COORDINATE
    };
Referenced by com.runehive.net.packet.out.SendNpcUpdate.updateNpc().
playerMask
final int com.runehive.game.world.entity.mob.UpdateFlag.playerMask
Definition at line 56 of file UpdateFlag.java.
Referenced by containsPlayer(), UpdateFlag(), and com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
playerOrder
final UpdateFlag [] com.runehive.game.world.entity.mob.UpdateFlag.playerOrder static
Initial value:
= {
            FORCE_MOVEMENT,
            GRAPHICS,
            ANIMATION,
            FORCED_CHAT,
            CHAT,
            INTERACT,
            APPEARANCE,
            FACE_COORDINATE,
            FIRST_HIT,
            SECOND_HIT
    }
Definition at line 75 of file UpdateFlag.java.
{
            FORCE_MOVEMENT,
            GRAPHICS,
            ANIMATION,
            FORCED_CHAT,
            CHAT,
            INTERACT,
            APPEARANCE,
            FACE_COORDINATE,
            FIRST_HIT,
            SECOND_HIT
    };
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer().
SECOND_HIT
com.runehive.game.world.entity.mob.UpdateFlag.SECOND_HIT =(0x200, 0x8)
Definition at line 47 of file UpdateFlag.java.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.updateNpc(), com.runehive.net.packet.out.SendPlayerUpdate.updatePlayer(), com.runehive.game.world.entity.mob.Mob.writeDamage(), and com.runehive.game.world.entity.mob.Mob.writeFakeDamage().
TRANSFORM
com.runehive.game.world.entity.mob.UpdateFlag.TRANSFORM =(-1, 0x2)
Definition at line 48 of file UpdateFlag.java.
Referenced by com.runehive.game.world.entity.mob.Mob.transform(), and com.runehive.net.packet.out.SendNpcUpdate.updateNpc().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/UpdateFlag.java