RuneHive-Game: com.runehive.content.activity.ActivityType Enum Reference
com.runehive.content.activity.ActivityType Enum Reference
Holds all activity types that are timed.
Public Member Functions
ActivityType (boolean record)
Static Public Member Functions
[static initializer]
static ActivityType getFirst ()
static ActivityType getOrdinal (int ordinal)
static List< ActivityType > getRecordable ()
Public Attributes
BARROWS =(true)
CERBERUS =(true)
DUEL_ARENA =(false)
FIGHT_CAVES =(true)
GODWARS =(false)
INFERNO =(true)
JAIL =(false)
KOLODION_ARENA =(true)
KRAKEN =(true)
PEST_CONTROL =(false)
RANDOM_EVENT =(false)
RECIPE_FOR_DISASTER =(true)
final boolean record
TUTORIAL =(false)
VORKATH =(true)
WARRIOR_GUILD =(false)
ZULRAH =(true)
Static Private Attributes
static final List< ActivityType > RECORDABLE = new LinkedList<>()
Detailed Description
Holds all activity types that are timed.
Author
Daniel
Definition at line 12 of file ActivityType.java.
Constructor & Destructor Documentation
ActivityType()
com.runehive.content.activity.ActivityType.ActivityType (boolean record)
Definition at line 40 of file ActivityType.java.
{
        this.record = record;
    }
References record.
Referenced by [static initializer](), getFirst(), and getOrdinal().
Member Function Documentation
[static initializer]()
com.runehive.content.activity.ActivityType.[static initializer] static
References ActivityType(), and RECORDABLE.
getFirst()
ActivityType com.runehive.content.activity.ActivityType.getFirst () static
Definition at line 54 of file ActivityType.java.
{
        return getOrdinal(0);
    }
References ActivityType(), and getOrdinal().
Referenced by com.runehive.game.plugin.PluginContext.onClick().
getOrdinal()
ActivityType com.runehive.content.activity.ActivityType.getOrdinal (int ordinal) static
Definition at line 48 of file ActivityType.java.
{
        if (ordinal < 0 || ordinal > RECORDABLE.size())
            return null;
        return RECORDABLE.get(ordinal);
    }
References ActivityType(), and RECORDABLE.
Referenced by getFirst().
getRecordable()
List< ActivityType > com.runehive.content.activity.ActivityType.getRecordable () static
Definition at line 44 of file ActivityType.java.
{
        return new LinkedList<>(RECORDABLE);
    }
References RECORDABLE.
Referenced by com.runehive.content.activity.record.PlayerRecord.showActivities().
Member Data Documentation
BARROWS
com.runehive.content.activity.ActivityType.BARROWS =(true)
Definition at line 17 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.barrows.Barrows.getType().
CERBERUS
com.runehive.content.activity.ActivityType.CERBERUS =(true)
Definition at line 26 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.CerberusActivity.getType().
DUEL_ARENA
com.runehive.content.activity.ActivityType.DUEL_ARENA =(false)
Definition at line 20 of file ActivityType.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.busy(), com.runehive.game.world.entity.combat.CombatUtil.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.canBasicAttack(), com.runehive.content.activity.impl.duelarena.DuelArenaActivity.getType(), and com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.request().
FIGHT_CAVES
com.runehive.content.activity.ActivityType.FIGHT_CAVES =(true)
Definition at line 13 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.fightcaves.FightCaves.finish(), and com.runehive.content.activity.impl.fightcaves.FightCaves.getType().
GODWARS
com.runehive.content.activity.ActivityType.GODWARS =(false)
Definition at line 27 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.godwars.GodwarsActivity.getType().
INFERNO
com.runehive.content.activity.ActivityType.INFERNO =(true)
Definition at line 15 of file ActivityType.java.
Referenced by com.runehive.content.activity.inferno.Inferno.getType().
JAIL
com.runehive.content.activity.ActivityType.JAIL =(false)
Definition at line 24 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.JailActivity.getType().
KOLODION_ARENA
com.runehive.content.activity.ActivityType.KOLODION_ARENA =(true)
Definition at line 14 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.magearena.MageArena.finish(), and com.runehive.content.activity.impl.magearena.MageArena.getType().
KRAKEN
com.runehive.content.activity.ActivityType.KRAKEN =(true)
Definition at line 19 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.kraken.KrakenActivity.finish(), and com.runehive.content.activity.impl.kraken.KrakenActivity.getType().
PEST_CONTROL
com.runehive.content.activity.ActivityType.PEST_CONTROL =(false)
Definition at line 22 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.getType(), and com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.getType().
RANDOM_EVENT
com.runehive.content.activity.ActivityType.RANDOM_EVENT =(false)
Definition at line 28 of file ActivityType.java.
Referenced by com.runehive.content.activity.randomevent.RandomEvent.getType().
RECIPE_FOR_DISASTER
com.runehive.content.activity.ActivityType.RECIPE_FOR_DISASTER =(true)
Definition at line 16 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.finish(), and com.runehive.content.activity.impl.recipefordisaster.RecipeForDisaster.getType().
record
final boolean com.runehive.content.activity.ActivityType.record
Definition at line 30 of file ActivityType.java.
Referenced by ActivityType().
RECORDABLE
final List<ActivityType> com.runehive.content.activity.ActivityType.RECORDABLE = new LinkedList<>() static private
Definition at line 31 of file ActivityType.java.
Referenced by [static initializer](), getOrdinal(), and getRecordable().
TUTORIAL
com.runehive.content.activity.ActivityType.TUTORIAL =(false)
Definition at line 21 of file ActivityType.java.
Referenced by com.runehive.game.action.impl.TutorialActivity.getType().
VORKATH
com.runehive.content.activity.ActivityType.VORKATH =(true)
Definition at line 23 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.VorkathActivity.finish(), and com.runehive.content.activity.impl.VorkathActivity.getType().
WARRIOR_GUILD
com.runehive.content.activity.ActivityType.WARRIOR_GUILD =(false)
Definition at line 25 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuild.getType().
ZULRAH
com.runehive.content.activity.ActivityType.ZULRAH =(true)
Definition at line 18 of file ActivityType.java.
Referenced by com.runehive.content.activity.impl.zulrah.ZulrahActivity.finish(), and com.runehive.content.activity.impl.zulrah.ZulrahActivity.getType().
The documentation for this enum was generated from the following file:
java/com/runehive/content/activity/ActivityType.java