RuneHive-Game: com.runehive.content.skill.impl.woodcutting.TreeData Enum Reference
com.runehive.content.skill.impl.woodcutting.TreeData Enum Reference
Holds all the data for trees.
Public Member Functions
TreeData (int level, int item, int replacement, int respawn, double experience, int petRate, int logs, double success, int[] tree)
Constructs a new <enum>TreeData</enum>.
Static Public Member Functions
static TreeData forId (int id)
Gets the tree data based on the object identification.
Public Attributes
ACHEY_TREE =(1, 2862, 3371, 15, 25.0D, 317_647, 2, 1.0, new int[]{2023})
ARCTIC_PINE_TREE =(54, 10810, 1356, 40, 150.0D, 155_227, 11, 0.4, new int[]{3037})
DEAD_TREE =(1, 1511, 1341, 15, 25.0D, 317_647, 2, 1.0, new int[]{1284})
DEAD_TREE1 =(1, 1511, 1351, 15, 25.0D, 317_647, 2, 1.0, new int[]{1286})
DEAD_TREE2 =(1, 1511, 1347, 15, 25.0D, 317_647, 2, 1.0, new int[]{1282, 1283})
DEAD_TREE3 =(1, 1511, 1352, 15, 25.0D, 317_647, 2, 1.0, new int[]{1365})
DEAD_TREE4 =(1, 1511, 1353, 15, 25.0D, 317_647, 2, 1.0, new int[]{1289})
DEAD_TREE5 =(1, 1511, 1285, 15, 25.0D, 317_647, 2, 1.0, new int[]{1349})
DYING_TREE =(1, 1511, 3649, 15, 25.0D, 317_647, 2, 1.0, new int[]{3648})
final double experience
The experience rewarded for chopping down the tree.
HOLLOW_TREE =(45, 3239, 4061, 35, 100.0D, 221_918, 10, 0.5, new int[]{1752})
final int item
The product identification for chopping the tree.
final int levelRequired
The level required to chop the tree.
final int logs
The log attribute for the tree.
MAGIC_TREE =(75, 1513, 9713, 60, 250.0D, 72_321, 15, 0.1, new int[]{10834})
MAHOGANY_TREE =(50, 6332, 9035, 40, 130.0D, 175_227, 11, 0.4, new int[]{9034})
MAPLE_TREE =(45, 1517, 9712, 35, 100.0D, 221_918, 10, 0.5, new int[]{1759, 10832})
NORMAL_TREE =(1, 1511, 1342, 15, 25.0D, 317_647, 2, 1.0, new int[]{1276, 1278, 1279})
OAK_TREE =(15, 1521, 1356, 25, 37.5D, 361_146, 5, 0.8, new int[]{10820})
final int petRate
The pet rate for obtaining the tree.
REDWOOD_TREE =(90, 19669, 29669, 60, 250.0D, 28_321, 19, 0.1, new int[]{29668, 29670})
final int replacement
THe replacement object for chopping down the tree.
final int respawn
The respawn time for the tree.
final double success
The success rate for chopping down the tree.
TEAK_TREE =(35, 6333, 9037, 32, 85.0D, 251_528, 10, 0.6, new int[]{9036})
final int[] tree
The tree identifications.
WILLOW_TREE =(30, 1519, 9471, 30, 67.5D, 289_286, 10, 0.6, new int[]{1756, 1758, 1760, 10831})
WILLOW_TREE1 =(30, 1519, 9711, 30, 67.5D, 289_286, 10, 0.6, new int[]{1750, 10819})
YEW_TREE =(60, 1515, 9714, 45, 175.0D, 145_013, 12, 0.3, new int[]{10822, 10823})
Detailed Description
Holds all the data for trees.
Author
Daniel
Definition at line 8 of file TreeData.java.
Constructor & Destructor Documentation
TreeData()
com.runehive.content.skill.impl.woodcutting.TreeData.TreeData (int level, int item, int replacement, int respawn, double experience, int petRate, int logs, double success, int[] tree)
Constructs a new <enum>TreeData</enum>.
Definition at line 58 of file TreeData.java.
{
        this.levelRequired = level;
        this.item = item;
        this.replacement = replacement;
        this.respawn = respawn;
        this.experience = experience;
        this.petRate = petRate;
        this.tree = tree;
        this.logs = logs;
        this.success = success;
    }
References experience, item, logs, petRate, replacement, respawn, success, and tree.
Referenced by forId().
Member Function Documentation
forId()
TreeData com.runehive.content.skill.impl.woodcutting.TreeData.forId (int id) static
Gets the tree data based on the object identification.
Definition at line 71 of file TreeData.java.
{
        for (TreeData data : TreeData.values())
            for (int object : data.tree)
                if (object == id) return data;
        return null;
    }
References TreeData().
Referenced by com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject().
Member Data Documentation
ACHEY_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.ACHEY_TREE =(1, 2862, 3371, 15, 25.0D, 317_647, 2, 1.0, new int[]{2023})
Definition at line 17 of file TreeData.java.
ARCTIC_PINE_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.ARCTIC_PINE_TREE =(54, 10810, 1356, 40, 150.0D, 155_227, 11, 0.4, new int[]{3037})
Definition at line 25 of file TreeData.java.
DEAD_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.DEAD_TREE =(1, 1511, 1341, 15, 25.0D, 317_647, 2, 1.0, new int[]{1284})
Definition at line 11 of file TreeData.java.
DEAD_TREE1
com.runehive.content.skill.impl.woodcutting.TreeData.DEAD_TREE1 =(1, 1511, 1351, 15, 25.0D, 317_647, 2, 1.0, new int[]{1286})
Definition at line 12 of file TreeData.java.
DEAD_TREE2
com.runehive.content.skill.impl.woodcutting.TreeData.DEAD_TREE2 =(1, 1511, 1347, 15, 25.0D, 317_647, 2, 1.0, new int[]{1282, 1283})
Definition at line 13 of file TreeData.java.
DEAD_TREE3
com.runehive.content.skill.impl.woodcutting.TreeData.DEAD_TREE3 =(1, 1511, 1352, 15, 25.0D, 317_647, 2, 1.0, new int[]{1365})
Definition at line 14 of file TreeData.java.
DEAD_TREE4
com.runehive.content.skill.impl.woodcutting.TreeData.DEAD_TREE4 =(1, 1511, 1353, 15, 25.0D, 317_647, 2, 1.0, new int[]{1289})
Definition at line 15 of file TreeData.java.
DEAD_TREE5
com.runehive.content.skill.impl.woodcutting.TreeData.DEAD_TREE5 =(1, 1511, 1285, 15, 25.0D, 317_647, 2, 1.0, new int[]{1349})
Definition at line 16 of file TreeData.java.
DYING_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.DYING_TREE =(1, 1511, 3649, 15, 25.0D, 317_647, 2, 1.0, new int[]{3648})
Definition at line 10 of file TreeData.java.
experience
final double com.runehive.content.skill.impl.woodcutting.TreeData.experience
The experience rewarded for chopping down the tree.
Definition at line 43 of file TreeData.java.
Referenced by TreeData().
HOLLOW_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.HOLLOW_TREE =(45, 3239, 4061, 35, 100.0D, 221_918, 10, 0.5, new int[]{1752})
Definition at line 23 of file TreeData.java.
item
final int com.runehive.content.skill.impl.woodcutting.TreeData.item
The product identification for chopping the tree.
Definition at line 34 of file TreeData.java.
Referenced by com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), and TreeData().
levelRequired
final int com.runehive.content.skill.impl.woodcutting.TreeData.levelRequired
The level required to chop the tree.
Definition at line 31 of file TreeData.java.
Referenced by com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), and com.runehive.content.skill.impl.woodcutting.Woodcutting.success().
logs
final int com.runehive.content.skill.impl.woodcutting.TreeData.logs
The log attribute for the tree.
Definition at line 49 of file TreeData.java.
Referenced by TreeData().
MAGIC_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.MAGIC_TREE =(75, 1513, 9713, 60, 250.0D, 72_321, 15, 0.1, new int[]{10834})
Definition at line 27 of file TreeData.java.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
MAHOGANY_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.MAHOGANY_TREE =(50, 6332, 9035, 40, 130.0D, 175_227, 11, 0.4, new int[]{9034})
Definition at line 24 of file TreeData.java.
MAPLE_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.MAPLE_TREE =(45, 1517, 9712, 35, 100.0D, 221_918, 10, 0.5, new int[]{1759, 10832})
Definition at line 22 of file TreeData.java.
NORMAL_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.NORMAL_TREE =(1, 1511, 1342, 15, 25.0D, 317_647, 2, 1.0, new int[]{1276, 1278, 1279})
Definition at line 9 of file TreeData.java.
OAK_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.OAK_TREE =(15, 1521, 1356, 25, 37.5D, 361_146, 5, 0.8, new int[]{10820})
Definition at line 18 of file TreeData.java.
petRate
final int com.runehive.content.skill.impl.woodcutting.TreeData.petRate
The pet rate for obtaining the tree.
Definition at line 46 of file TreeData.java.
Referenced by TreeData().
REDWOOD_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.REDWOOD_TREE =(90, 19669, 29669, 60, 250.0D, 28_321, 19, 0.1, new int[]{29668, 29670})
Definition at line 28 of file TreeData.java.
replacement
final int com.runehive.content.skill.impl.woodcutting.TreeData.replacement
THe replacement object for chopping down the tree.
Definition at line 37 of file TreeData.java.
Referenced by TreeData().
respawn
final int com.runehive.content.skill.impl.woodcutting.TreeData.respawn
The respawn time for the tree.
Definition at line 40 of file TreeData.java.
Referenced by TreeData().
success
final double com.runehive.content.skill.impl.woodcutting.TreeData.success
The success rate for chopping down the tree.
Definition at line 52 of file TreeData.java.
Referenced by TreeData().
TEAK_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.TEAK_TREE =(35, 6333, 9037, 32, 85.0D, 251_528, 10, 0.6, new int[]{9036})
Definition at line 21 of file TreeData.java.
tree
final int [] com.runehive.content.skill.impl.woodcutting.TreeData.tree
The tree identifications.
Definition at line 55 of file TreeData.java.
Referenced by TreeData().
WILLOW_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.WILLOW_TREE =(30, 1519, 9471, 30, 67.5D, 289_286, 10, 0.6, new int[]{1756, 1758, 1760, 10831})
Definition at line 19 of file TreeData.java.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
WILLOW_TREE1
com.runehive.content.skill.impl.woodcutting.TreeData.WILLOW_TREE1 =(30, 1519, 9711, 30, 67.5D, 289_286, 10, 0.6, new int[]{1750, 10819})
Definition at line 20 of file TreeData.java.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
YEW_TREE
com.runehive.content.skill.impl.woodcutting.TreeData.YEW_TREE =(60, 1515, 9714, 45, 175.0D, 145_013, 12, 0.3, new int[]{10822, 10823})
Definition at line 26 of file TreeData.java.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/woodcutting/TreeData.java