RuneHive-Game: com.runehive.net.codec.login.LoginResponse Enum Reference
com.runehive.net.codec.login.LoginResponse Enum Reference
Represents the enumerated login response codes.
Public Member Functions
final int getOpcode ()
Gets the opcode for this response.
LoginResponse (int opcode)
Creates a new LoginResponse.
Public Attributes
ACCOUNT_DISABLED =(4)
ACCOUNT_ONLINE =(5)
BAD_SESSION_ID =(10)
BAD_USERNAME =(22)
COULD_NOT_COMPLETE_LOGIN =(13)
DELAY =(1)
EARLY_ACCESS =(28)
EXCHANGE_DATA =(0)
FORUM_REGISTRATION =(26)
GAME_UPDATED =(6)
INSUFFICIENT_PERMSSION =(24)
INVALID_CREDENTIALS =(3)
INVALID_EMAIL =(27)
INVALID_LOGIN_SERVER =(20)
LOGIN_ATTEMPTS_EXCEEDED =(16)
LOGIN_LIMIT_EXCEEDED =(9)
LOGIN_SERVER_OFFLINE =(8)
LOGIN_SERVER_REJECTED_SESSION =(11)
MEMBERS_ACCOUNT_REQUIRED =(12)
MEMBERS_ONLY_AREA =(17)
NO_RESPONSE =(-1)
NORMAL =(2)
RECONNECTING =(15)
SERVER_BEING_UPDATED =(14)
SHORT_USERNAME =(23)
TRANSFERING_PROFILE =(21)
UNAUTHORIZED_PRIVILEGE =(25)
WORLD_FULL =(7)
Private Attributes
final int opcode
The response code.
Detailed Description
Represents the enumerated login response codes.
Author
SeVen
Definition at line 8 of file LoginResponse.java.
Constructor & Destructor Documentation
LoginResponse()
com.runehive.net.codec.login.LoginResponse.LoginResponse (int opcode)
Creates a new LoginResponse.
Parameters
opcode The response code.
Definition at line 49 of file LoginResponse.java.
{
        this.opcode = opcode;
    }
References opcode.
Member Function Documentation
getOpcode()
final int com.runehive.net.codec.login.LoginResponse.getOpcode ()
Gets the opcode for this response.
Returns
The response code.
Definition at line 58 of file LoginResponse.java.
{
        return opcode;
    }
References opcode.
Referenced by com.runehive.net.codec.login.LoginDecoder.sendResponseCode().
Member Data Documentation
ACCOUNT_DISABLED
com.runehive.net.codec.login.LoginResponse.ACCOUNT_DISABLED =(4)
Definition at line 14 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser(), com.runehive.net.ChannelFilter.channelRegistered(), and com.runehive.net.session.LoginSession.evaluate().
ACCOUNT_ONLINE
com.runehive.net.codec.login.LoginResponse.ACCOUNT_ONLINE =(5)
Definition at line 15 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.evaluate().
BAD_SESSION_ID
com.runehive.net.codec.login.LoginResponse.BAD_SESSION_ID =(10)
Definition at line 20 of file LoginResponse.java.
BAD_USERNAME
com.runehive.net.codec.login.LoginResponse.BAD_USERNAME =(22)
Definition at line 30 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.evaluate().
COULD_NOT_COMPLETE_LOGIN
com.runehive.net.codec.login.LoginResponse.COULD_NOT_COMPLETE_LOGIN =(13)
Definition at line 23 of file LoginResponse.java.
Referenced by com.runehive.game.world.entity.mob.player.persist.PlayerPersistDB.load(), com.runehive.game.world.entity.mob.player.persist.PlayerPersistFile.load(), and com.runehive.game.world.entity.mob.player.persist.PlayerSerializer.load().
DELAY
com.runehive.net.codec.login.LoginResponse.DELAY =(1)
Definition at line 11 of file LoginResponse.java.
EARLY_ACCESS
com.runehive.net.codec.login.LoginResponse.EARLY_ACCESS =(28)
Definition at line 36 of file LoginResponse.java.
EXCHANGE_DATA
com.runehive.net.codec.login.LoginResponse.EXCHANGE_DATA =(0)
Definition at line 10 of file LoginResponse.java.
FORUM_REGISTRATION
com.runehive.net.codec.login.LoginResponse.FORUM_REGISTRATION =(26)
Definition at line 34 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser().
GAME_UPDATED
com.runehive.net.codec.login.LoginResponse.GAME_UPDATED =(6)
Definition at line 16 of file LoginResponse.java.
Referenced by com.runehive.net.codec.login.LoginDecoder.decodePayload().
INSUFFICIENT_PERMSSION
com.runehive.net.codec.login.LoginResponse.INSUFFICIENT_PERMSSION =(24)
Definition at line 32 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.evaluate().
INVALID_CREDENTIALS
com.runehive.net.codec.login.LoginResponse.INVALID_CREDENTIALS =(3)
Definition at line 13 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser(), com.runehive.net.session.LoginSession.evaluate(), com.runehive.net.session.LoginSession.handleUserLoginDetails(), and com.runehive.game.world.entity.mob.player.persist.PlayerPersistFile.load().
INVALID_EMAIL
com.runehive.net.codec.login.LoginResponse.INVALID_EMAIL =(27)
Definition at line 35 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.evaluate().
INVALID_LOGIN_SERVER
com.runehive.net.codec.login.LoginResponse.INVALID_LOGIN_SERVER =(20)
Definition at line 28 of file LoginResponse.java.
LOGIN_ATTEMPTS_EXCEEDED
com.runehive.net.codec.login.LoginResponse.LOGIN_ATTEMPTS_EXCEEDED =(16)
Definition at line 26 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.handleUserLoginDetails().
LOGIN_LIMIT_EXCEEDED
com.runehive.net.codec.login.LoginResponse.LOGIN_LIMIT_EXCEEDED =(9)
Definition at line 19 of file LoginResponse.java.
Referenced by com.runehive.net.ChannelFilter.channelRegistered().
LOGIN_SERVER_OFFLINE
com.runehive.net.codec.login.LoginResponse.LOGIN_SERVER_OFFLINE =(8)
Definition at line 18 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser().
LOGIN_SERVER_REJECTED_SESSION
com.runehive.net.codec.login.LoginResponse.LOGIN_SERVER_REJECTED_SESSION =(11)
Definition at line 21 of file LoginResponse.java.
Referenced by com.runehive.net.codec.login.LoginDecoder.decodeConnectionType(), com.runehive.net.codec.login.LoginDecoder.decodeHandshake(), com.runehive.net.codec.login.LoginDecoder.decodePayload(), and com.runehive.net.codec.login.LoginDecoder.sendResponseCode().
MEMBERS_ACCOUNT_REQUIRED
com.runehive.net.codec.login.LoginResponse.MEMBERS_ACCOUNT_REQUIRED =(12)
Definition at line 22 of file LoginResponse.java.
MEMBERS_ONLY_AREA
com.runehive.net.codec.login.LoginResponse.MEMBERS_ONLY_AREA =(17)
Definition at line 27 of file LoginResponse.java.
NO_RESPONSE
com.runehive.net.codec.login.LoginResponse.NO_RESPONSE =(-1)
Definition at line 9 of file LoginResponse.java.
NORMAL
com.runehive.net.codec.login.LoginResponse.NORMAL =(2)
Definition at line 12 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.authenticatedForumUser(), com.runehive.net.codec.login.LoginResponseEncoder.encode(), com.runehive.net.session.LoginSession.evaluate(), com.runehive.net.session.LoginSession.handleUserLoginDetails(), com.runehive.game.world.entity.mob.player.persist.PlayerPersistDB.load(), and com.runehive.game.world.entity.mob.player.persist.PlayerPersistFile.load().
opcode
final int com.runehive.net.codec.login.LoginResponse.opcode private
The response code.
Definition at line 41 of file LoginResponse.java.
Referenced by getOpcode(), and LoginResponse().
RECONNECTING
com.runehive.net.codec.login.LoginResponse.RECONNECTING =(15)
Definition at line 25 of file LoginResponse.java.
SERVER_BEING_UPDATED
com.runehive.net.codec.login.LoginResponse.SERVER_BEING_UPDATED =(14)
Definition at line 24 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.evaluate().
SHORT_USERNAME
com.runehive.net.codec.login.LoginResponse.SHORT_USERNAME =(23)
Definition at line 31 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.evaluate().
TRANSFERING_PROFILE
com.runehive.net.codec.login.LoginResponse.TRANSFERING_PROFILE =(21)
Definition at line 29 of file LoginResponse.java.
UNAUTHORIZED_PRIVILEGE
com.runehive.net.codec.login.LoginResponse.UNAUTHORIZED_PRIVILEGE =(25)
Definition at line 33 of file LoginResponse.java.
WORLD_FULL
com.runehive.net.codec.login.LoginResponse.WORLD_FULL =(7)
Definition at line 17 of file LoginResponse.java.
Referenced by com.runehive.net.session.LoginSession.evaluate().
The documentation for this enum was generated from the following file:
java/com/runehive/net/codec/login/LoginResponse.java