RuneHive-Game: com.runehive.content.achievement.AchievementList Enum Reference
com.runehive.content.achievement.AchievementList Enum Reference
Holds all the achievements.
Public Member Functions
AchievementList (String task, int amount, AchievementKey key, AchievementType type, int reward)
int getAmount ()
AchievementKey getKey ()
Item getReward ()
String getTask ()
AchievementType getType ()
Static Public Member Functions
static List< AchievementList > asList (AchievementType difficulty)
static int getTotal ()
Public Attributes
ANSWER_100_TRIVIA_BOTS =("Answer 100 TriviaBot questions", 100, TRIVIABOT, MISCELLANEOUS, 7500)
ANSWER_10_TRIVIA_BOTS =("Answer 10 TriviaBot questions", 10, TRIVIABOT, MISCELLANEOUS, 2500)
ANSWER_30_TRIVIA_BOTS =("Answer 30 TriviaBot questions", 30, TRIVIABOT, MISCELLANEOUS, 5000)
ANSWER_500_TRIVIA_BOTS =("Answer 500 TriviaBot questions", 500, TRIVIABOT, MISCELLANEOUS, 10000)
BURY_10_BONES =("Bury 10 bones (any)", 10, BURY_BONES, MISCELLANEOUS, 500)
CAST_100_HIGH_ALCHEMY =("Cast high alchemy spell 100 times", 100, HIGH_ALCHEMY, SKILLING, 750)
CHANGE_APPEARANCE =("Change your appearance once", 1, AchievementKey.CHANGE_APPEARANCE, MISCELLANEOUS, 500)
Misc achievements.
CHOP_100_TREES =("Chop down 100 trees", 100, WOODCUTTING, SKILLING, 1000)
CHOP_1500_TREES =("Chop down 1,500 trees", 1500, WOODCUTTING, SKILLING, 4000)
CHOP_5000_TREES =("Chop down 5,000 trees", 5000, WOODCUTTING, SKILLING, 7000)
CHOP_500_TREES =("Chop down 500 trees", 500, WOODCUTTING, SKILLING, 4000)
CLAIM_1000_VOTES =("Claim 1,000 vote rewards", 1000, VOTE, MISCELLANEOUS, 10000)
CLAIM_100_VOTE =("Claim 100 vote reward", 100, VOTE, MISCELLANEOUS, 1000)
CLAIM_250_VOTES =("Claim 250 vote rewards", 250, VOTE, MISCELLANEOUS, 2500)
CLAIM_500_VOTES =("Claim 500 vote rewards", 500, VOTE, MISCELLANEOUS, 5000)
COMPLETE_100_BARROW =("Complete 100 Barrows runs", 100, BARROWS, MINIGAME, 3500)
COMPLETE_100_CLUE_SCROLLS =("Complete 100 clue scrolls", 100, CLUE_SCROLLS, MISCELLANEOUS, 1500)
COMPLETE_100_SLAYER_TASKS =("Complete 100 slayer tasks", 100, SLAYER_TASKS, MISCELLANEOUS, 10000)
COMPLETE_10_CLUE_SCROLLS =("Complete 10 clue scrolls", 10, CLUE_SCROLLS, MISCELLANEOUS, 1500)
COMPLETE_10_SLAYER_TASKS =("Complete 10 slayer tasks", 10, SLAYER_TASKS, MISCELLANEOUS, 10000)
COMPLETE_150_PC_GAME =("Complete 150 PC games", 150, PEST_CONTROL, MINIGAME, 7500)
COMPLETE_250_SLAYER_TASKS =("Complete 250 slayer tasks", 250, SLAYER_TASKS, MISCELLANEOUS, 10000)
COMPLETE_25_CLUE_SCROLLS =("Complete 25 clue scrolls", 25, CLUE_SCROLLS, MISCELLANEOUS, 1500)
COMPLETE_25_PC_GAME =("Complete 25 PC games", 25, PEST_CONTROL, MINIGAME, 1500)
COMPLETE_500_BARROWS =("Complete 500 Barrows runs", 500, BARROWS, MINIGAME, 7500)
COMPLETE_50_BARROWS =("Complete 50 Barrows runs", 50, BARROWS, MINIGAME, 1500)
COMPLETE_50_CLUE_SCROLLS =("Complete 50 clue scrolls", 50, CLUE_SCROLLS, MISCELLANEOUS, 1500)
COMPLETE_50_PC_GAME =("Complete 50 PC games", 50, PEST_CONTROL, MINIGAME, 3500)
COMPLETE_50_SLAYER_TASKS =("Complete 50 slayer tasks", 50, SLAYER_TASKS, MISCELLANEOUS, 10000)
COMPLETE_5_BARROWS =("Complete 5 Barrows runs", 5, BARROWS, MINIGAME, 500)
COMPLETE_5_PC_GAME =("Complete 5 PC game", 5, PEST_CONTROL, MINIGAME, 500)
CRAFT_100_OF_ANY_RUNES =("Craft 100 of any runes", 100, RUNECRAFTING, SKILLING, 500)
CRAFT_1500_OF_ANY_RUNES =("Craft 1500 of any runes", 1500, RUNECRAFTING, SKILLING, 4000)
CRAFT_5000_OF_ANY_RUNES =("Craft 5000 of any runes", 5000, RUNECRAFTING, SKILLING, 7000)
CRAFT_500_OF_ANY_RUNES =("Craft 500 of any runes", 500, RUNECRAFTING, SKILLING, 1500)
ENCHANT_10000_BOLTS =("Enchant 10,000 bolts", 10000, ENCHANT_BOLTS, SKILLING, 5000)
ENCHANT_2500_BOLTS =("Enchant 2,500 bolts", 2500, ENCHANT_BOLTS, SKILLING, 2500)
EXPERIENCE_MASTERY =("Earn 200M EXP in 5 skills", 5, AchievementKey.EXPERIENCE_MASTERY, SKILLING, 7500)
FLETCH_10000_ARROWS =("Fletch 10,000 arrows", 10000, FLETCHING, SKILLING, 5000)
FLETCH_2500_ARROWS =("Fletch 2,500 arrows", 2500, FLETCHING, SKILLING, 2500)
GET_1000_TOTAL_LEVELS =("Achieve 1,000 total level", 1000, TOTAL_LEVEL, SKILLING, 3000)
GET_10_FIRE_CAPES =("Get 10 fire capes", 10, FIRE_CAPE, MINIGAME, 1000)
GET_10_ITEM_FROM_BARROWS =("Get 10 unique item from barrows", 10, BARROWS_UNIQUE, MINIGAME, 1000)
GET_1500_TOTAL_LEVEL =("Achieve 1,500 total level", 1500, TOTAL_LEVEL, SKILLING, 5000)
GET_1_ITEM_FROM_BARROWS =("Get 1 unique item from barrows", 1, BARROWS_UNIQUE, MINIGAME, 250)
GET_2000_TOTAL_LEVELS =("Achieve 2,000 total level", 2000, TOTAL_LEVEL, SKILLING, 8000)
GET_A_10_KILLSTREAK =("Kill 10 players without dying", 1, KILLSTKREAK_10, PVP, 2500)
GET_A_15_KILLSTREAK =("Kill 15 players without dying", 1, KILLSTKREAK_15, PVP, 5000)
GET_A_25_KILLSTREAK =("Kill 25 players without dying", 1, KILLSTKREAK_25, PVP, 8500)
GET_A_5_KILLSTREAK =("Kill 5 players without dying", 1, KILLSTKREAK_5, PVP, 1000)
GET_YOUR_FIRST_FIRE_CAPE =("Get your first fire cape", 1, FIRE_CAPE, MINIGAME, 150)
Minigame achievements.
HIT_45_WITH_DRAGON_MACE =("Hit 45+ with Dragon mace special\\non player 10 times", 10, DMACE_MAX, PVP, 5000)
HIT_80_WITH_AGS =("Hit 80+ with AGS special on player 10 times", 10, AGS_SPEC, PVP, 5000)
KILL_10000_NPCS =("Kill 10000 NPC's", 10000, NPCS, MISCELLANEOUS, 10000)
KILL_1000_NPCS =("Kill 1000 NPC's", 1000, NPCS, MISCELLANEOUS, 10000)
KILL_1000_PLAYERS =("Kill 1,000 players using anything", 1000, KILLER, PVP, 35000)
KILL_1000_REVS =("Kill 1000 revenants", 1000, REVS, PVM, 10000)
KILL_100_KBD =("Kill King Black Dragons 100 times", 100, KING_BLACK_DRAGON, PVM, 3000)
KILL_100_KRAKENS =("Kill Kraken 100 times", 100, KRAKEN, PVM, 3000)
KILL_100_REVS =("Kill 100 revenants", 100, REVS, PVM, 10000)
KILL_10_CERBERUS =("Kill Cerberus 10 times", 10, CERBERUS, PVM, 1000)
KILL_10_COMMANDERS =("Kill Commander Zilyana 10 times", 10, ZILYANA, PVM, 1000)
KILL_10_GENERARS =("Kill General Graardor 10 times", 10, GRAARDOR, PVM, 1000)
KILL_10_KBD =("Kill King Black Dragons 10 times", 10, KING_BLACK_DRAGON, PVM, 1000)
PvM achievements.
KILL_10_KRAKENS =("Kill Kraken 10 times", 10, KRAKEN, PVM, 1000)
KILL_10_KREES =("Kill Kree Arra 10 times", 10, KREE, PVM, 1000)
KILL_10_KRILS =("Kill K'ril Tsutaroth 10 times", 10, KRIL, PVM, 1000)
KILL_10_PLAYERS =("Kill 10 players using anything", 10, KILLER, PVP, 2500)
PvP achievements.
KILL_10_VORKATHS =("Kill Vorkath 10 times", 10, VORKATH, PVM, 1000)
KILL_10_WITH_AGS =("Kill 10 players using AGS special", 10, AGS_SPEC, PVP, 2500)
KILL_10_WITH_DARK_BOW =("Kill 10 players using Dark bow special", 10, DARKBOW_SPEC, PVP, 2500)
KILL_10_WITH_DCLAWS =("Kill 10 players using Dragon claws special", 10, DCLAWS_SPEC, PVP, 2500)
KILL_10_WITH_DDS =("Kill 10 players using DDS special", 10, DDS_SPEC, PVP, 2500)
KILL_10_WITH_DHAROK =("Kill 10 players using full d'haroks", 10, DHAROK, PVP, 2500)
KILL_10_WITH_DRAGON_MACE =("Kill 10 players using Dragon mace special", 10, DMACE_SPEC, PVP, 2500)
KILL_10_WITH_GMAUL =("Kill 10 players with a Granite maul special", 10, GMAULED_SPEC, PVP, 2500)
KILL_10_ZULRAH =("Kill Zulrah 10 times", 10, ZULRAH, PVM, 1000)
KILL_125_CERBERUS =("Kill Cerberus 125 times", 125, CERBERUS, PVM, 6000)
KILL_125_COMMANDERS =("Kill Commander Zilyana 125 times", 125, ZILYANA, PVM, 6000)
KILL_125_GENERALS =("Kill General Graardor 125 times", 125, GRAARDOR, PVM, 6000)
KILL_125_KREES =("Kill Kree Arra 125 times", 125, KREE, PVM, 6000)
KILL_125_KRILS =("Kill K'ril Tsutaroth 125 times", 125, KRIL, PVM, 6000)
KILL_125_VORKATHS =("Kill Vorkath 125 times", 125, VORKATH, PVM, 6000)
KILL_150_PLAYERS =("Kill 150 players using anything", 150, KILLER, PVP, 12500)
KILL_150_WITH_AGS =("Kill 150 players using AGS special", 150, AGS_SPEC, PVP, 5000)
KILL_150_WITH_DCLAWS =("Kill 150 players using Dragon claws special", 150, DCLAWS_SPEC, PVP, 5000)
KILL_150_WITH_DDS =("Kill 150 players using DDS special", 150, DDS_SPEC, PVP, 5000)
KILL_150_WITH_DHAROK =("Kill 150 players using full d'haroks", 150, DHAROK, PVP, 12500)
KILL_150_WITH_GMAUL =("Kill 150 players with a Granite maul special", 150, GMAULED_SPEC, PVP, 5000)
KILL_2500_NPCS =("Kill 2500 NPC's", 2500, NPCS, MISCELLANEOUS, 10000)
KILL_250_REVS =("Kill 250 revenants", 250, REVS, PVM, 10000)
KILL_300_ZULRAHS =("Kill Zulrah 300 times", 300, ZULRAH, PVM, 6000)
KILL_350_KBD =("Kill King Black Dragons 350 times", 350, KING_BLACK_DRAGON, PVM, 6000)
KILL_350_KRAKENS =("Kill Kraken 350 times", 350, KRAKEN, PVM, 6000)
KILL_350_WITH_AGS =("Kill 350 players using AGS special", 350, AGS_SPEC, PVP, 8000)
KILL_350_WITH_DCLAWS =("Kill 350 players using Dragon claws special", 350, DCLAWS_SPEC, PVP, 8000)
KILL_350_WITH_DDS =("Kill 350 players using DDS special", 350, DDS_SPEC, PVP, 8000)
KILL_350_WITH_GMAUL =("Kill 350 players with a Granite maul special", 350, GMAULED_SPEC, PVP, 8000)
KILL_35_CERBERUS =("Kill Cerberus 35 times", 35, CERBERUS, PVM, 3000)
KILL_35_COMMANDERS =("Kill Commander Zilyana 35 times", 35, ZILYANA, PVM, 3000)
KILL_35_GENERALS =("Kill General Graardor 35 times", 35, GRAARDOR, PVM, 3000)
KILL_35_KREES =("Kill Kree Arra 35 times", 35, KREE, PVM, 3000)
KILL_35_KRILS =("Kill K'ril Tsutaroth 35 times", 35, KRIL, PVM, 3000)
KILL_35_VORKATHS =("Kill Vorkath 35 times", 35, VORKATH, PVM, 3000)
KILL_5000_NPCS =("Kill 5000 NPC's", 5000, NPCS, MISCELLANEOUS, 10000)
KILL_500_CERBERUS =("Kill Cerberus 500 times", 500, CERBERUS, PVM, 10000)
KILL_500_COMMANDERS =("Kill Commander Zilyana 500 times", 500, ZILYANA, PVM, 10000)
KILL_500_GENERALS =("Kill General Graardor 500 times", 500, GRAARDOR, PVM, 10000)
KILL_500_KREES =("Kill Kree Arra 500 times", 500, KREE, PVM, 10000)
KILL_500_KRILS =("Kill K'ril Tsutaroth 500 times", 500, KRIL, PVM, 10000)
KILL_500_PLAYERS =("Kill 500 players using anything", 500, KILLER, PVP, 20000)
KILL_500_REVS =("Kill 500 revenants", 500, REVS, PVM, 10000)
KILL_500_VORKATHS =("Kill Vorkath 500 times", 500, VORKATH, PVM, 10000)
KILL_500_ZULRAHS =("Kill Zulrah 500 times", 500, ZULRAH, PVM, 10000)
KILL_50_PLAYERS =("Kill 50 players using anything", 50, KILLER, PVP, 6500)
KILL_50_WITH_DHAROK =("Kill 50 players using full d'haroks", 50, DHAROK, PVP, 6500)
KILL_50_ZULRAH =("Kill Zulrah 50 times", 50, ZULRAH, PVM, 3000)
KILL_75_WITH_DARK_BOW =("Kill 75 players using Dark bow special", 75, DARKBOW_SPEC, PVP, 5000)
KILL_75_WITH_DRAGON_MACE =("Kill 75 players using Dragon mace special", 75, DMACE_SPEC, PVP, 5000)
KILL_800_KBD =("Kill King Black Dragons 800 times", 800, KING_BLACK_DRAGON, PVM, 10000)
KILL_800_KRAKENS =("Kill Kraken 800 times", 800, KRAKEN, PVM, 10000)
MAKE_10000_POTIONS =("Make 10,000 potions with herblore", 10000, HERBLORE, SKILLING, 7500)
MAKE_2500_POTIONS =("Make 2,500 potions with herblore", 2500, HERBLORE, SKILLING, 3250)
MAX_1_SKILL =("Achieve level 99 in 1 skill", 1, SKILL_MASTERY, SKILLING, 2000)
Skilling achievements.
MAX_200M_EXPERIENCE =("Earn 200M EXP in all skills", Skill.SKILL_COUNT, AchievementKey.EXPERIENCE_MASTERY, SKILLING, 30000)
MAX_3_SKILLS =("Achieve level 99 in 3 skills", 3, SKILL_MASTERY, SKILLING, 4000)
MAX_ALL_SKILLS =("Achieve level 99 in all skills", Skill.SKILL_COUNT, SKILL_MASTERY, SKILLING, 10000)
MINE_100_ROCKS =("Mine 100 rocks", 100, MINNING, SKILLING, 1000)
MINE_1500_ROCKS =("Mine 1,500 rocks", 1500, MINNING, SKILLING, 4000)
MINE_5000_ROCKS =("Mine 5,000 rocks", 5000, MINNING, SKILLING, 7000)
MINE_500_ROCKS =("Mine 500 rocks", 500, MINNING, SKILLING, 2500)
OBTAIN_100_RARE_DROPS =("Obtain 100 rare drops", 100, RARE_DROPS, MISCELLANEOUS, 1000)
OBTAIN_10_PETS =("Obtain 10 of any pets", 10, OBTAIN_PET, MISCELLANEOUS, 5000)
OBTAIN_250_RARE_DROPS =("Obtain 250 rare drops", 250, RARE_DROPS, MISCELLANEOUS, 1000)
OBTAIN_500_RARE_DROPS =("Obtain 500 rare drops", 500, RARE_DROPS, MISCELLANEOUS, 1000)
OBTAIN_50_RARE_DROPS =("Obtain 50 rare drops", 50, RARE_DROPS, MISCELLANEOUS, 1000)
OBTAIN_5_PETS =("Obtain 5 of any pets", 5, OBTAIN_PET, MISCELLANEOUS, 2500)
OBTAIN_YOUR_FIRST_PET =("Obtain 1 of any pets", 1, OBTAIN_PET, MISCELLANEOUS, 1000)
OPEN_10_CASKETS =("Open 10 caskets", 10, CASKET, MISCELLANEOUS, 1000)
OPEN_10_CRYSTAL_CHESTS =("Open 10 crystal chests", 10, CRYSTAL_CHEST, MISCELLANEOUS, 1000)
OPEN_150_CASKETS =("Open 150 caskets", 150, CASKET, MISCELLANEOUS, 5000)
OPEN_150_CRYSTAL_CHESTS =("Open 150 crystal chests", 150, CRYSTAL_CHEST, MISCELLANEOUS, 5000)
OPEN_500_CASKETS =("Open 500 caskets", 500, CASKET, MISCELLANEOUS, 7500)
OPEN_500_CRYSTAL_CHESTS =("Open 500 crystal chests", 500, CRYSTAL_CHEST, MISCELLANEOUS, 7500)
OPEN_50_CASKETS =("Open 50 caskets", 50, CASKET, MISCELLANEOUS, 2500)
OPEN_50_CRYSTAL_CHESTS =("Open 50 crystal chests", 50, CRYSTAL_CHEST, MISCELLANEOUS, 2500)
RUN_1000_COURSES =("Complete 1,000\\nagility courses", 1000, AGILITY, SKILLING, 50000)
RUN_150_COURSES =("Complete 150 agility courses", 150, AGILITY, SKILLING, 10000)
RUN_500_COURSES =("Complete 500 agility courses", 500, AGILITY, SKILLING, 25000)
RUN_50_COURSES =("Complete 50 agility courses", 50, AGILITY, SKILLING, 5000)
Private Attributes
final int amount
final AchievementKey key
final int reward
final String task
final AchievementType type
Detailed Description
Holds all the achievements.
Author
Daniel
Definition at line 17 of file AchievementList.java.
Constructor & Destructor Documentation
AchievementList()
com.runehive.content.achievement.AchievementList.AchievementList (String task, int amount, AchievementKey key, AchievementType type, int reward)
Definition at line 186 of file AchievementList.java.
{
        this.amount = amount;
        this.key = key;
        this.type = type;
        this.task = task;
        this.reward = reward;
    }
References amount, key, reward, task, and type.
Referenced by asList().
Member Function Documentation
asList()
List< AchievementList > com.runehive.content.achievement.AchievementList.asList (AchievementType difficulty) static
Definition at line 214 of file AchievementList.java.
{
        List<AchievementList> list = new ArrayList<>();
        for (AchievementList achievement : values()) {
            if (achievement.type == difficulty) {
                list.add(achievement);
            }
        }
        return list;
    }
References AchievementList().
Referenced by com.runehive.content.achievement.AchievementHandler.getDifficultyAmount().
getAmount()
int com.runehive.content.achievement.AchievementList.getAmount ()
Definition at line 194 of file AchievementList.java.
{
        return amount;
    }
References amount.
getKey()
AchievementKey com.runehive.content.achievement.AchievementList.getKey ()
Definition at line 198 of file AchievementList.java.
{
        return key;
    }
References key.
getReward()
Item com.runehive.content.achievement.AchievementList.getReward ()
Definition at line 210 of file AchievementList.java.
{
        return new Item(13307, reward);
    }
References reward.
getTask()
String com.runehive.content.achievement.AchievementList.getTask ()
Definition at line 206 of file AchievementList.java.
{
        return task;
    }
References task.
getTotal()
int com.runehive.content.achievement.AchievementList.getTotal () static
Definition at line 226 of file AchievementList.java.
{
        return values().length;
    }
Referenced by com.runehive.content.achievement.AchievementWriter.AchievementWriter(), and com.runehive.content.achievement.AchievementHandler.completedAll().
getType()
AchievementType com.runehive.content.achievement.AchievementList.getType ()
Definition at line 202 of file AchievementList.java.
{
        return type;
    }
References type.
Member Data Documentation
amount
final int com.runehive.content.achievement.AchievementList.amount private
Definition at line 180 of file AchievementList.java.
Referenced by AchievementList(), and getAmount().
ANSWER_100_TRIVIA_BOTS
com.runehive.content.achievement.AchievementList.ANSWER_100_TRIVIA_BOTS =("Answer 100 TriviaBot questions", 100, TRIVIABOT, MISCELLANEOUS, 7500)
Definition at line 154 of file AchievementList.java.
ANSWER_10_TRIVIA_BOTS
com.runehive.content.achievement.AchievementList.ANSWER_10_TRIVIA_BOTS =("Answer 10 TriviaBot questions", 10, TRIVIABOT, MISCELLANEOUS, 2500)
Definition at line 152 of file AchievementList.java.
ANSWER_30_TRIVIA_BOTS
com.runehive.content.achievement.AchievementList.ANSWER_30_TRIVIA_BOTS =("Answer 30 TriviaBot questions", 30, TRIVIABOT, MISCELLANEOUS, 5000)
Definition at line 153 of file AchievementList.java.
ANSWER_500_TRIVIA_BOTS
com.runehive.content.achievement.AchievementList.ANSWER_500_TRIVIA_BOTS =("Answer 500 TriviaBot questions", 500, TRIVIABOT, MISCELLANEOUS, 10000)
Definition at line 155 of file AchievementList.java.
BURY_10_BONES
com.runehive.content.achievement.AchievementList.BURY_10_BONES =("Bury 10 bones (any)", 10, BURY_BONES, MISCELLANEOUS, 500)
Definition at line 143 of file AchievementList.java.
CAST_100_HIGH_ALCHEMY
com.runehive.content.achievement.AchievementList.CAST_100_HIGH_ALCHEMY =("Cast high alchemy spell 100 times", 100, HIGH_ALCHEMY, SKILLING, 750)
Definition at line 103 of file AchievementList.java.
CHANGE_APPEARANCE
com.runehive.content.achievement.AchievementList.CHANGE_APPEARANCE =("Change your appearance once", 1, AchievementKey.CHANGE_APPEARANCE, MISCELLANEOUS, 500)
Misc achievements.
Definition at line 142 of file AchievementList.java.
CHOP_100_TREES
com.runehive.content.achievement.AchievementList.CHOP_100_TREES =("Chop down 100 trees", 100, WOODCUTTING, SKILLING, 1000)
Definition at line 104 of file AchievementList.java.
CHOP_1500_TREES
com.runehive.content.achievement.AchievementList.CHOP_1500_TREES =("Chop down 1,500 trees", 1500, WOODCUTTING, SKILLING, 4000)
Definition at line 106 of file AchievementList.java.
CHOP_5000_TREES
com.runehive.content.achievement.AchievementList.CHOP_5000_TREES =("Chop down 5,000 trees", 5000, WOODCUTTING, SKILLING, 7000)
Definition at line 107 of file AchievementList.java.
CHOP_500_TREES
com.runehive.content.achievement.AchievementList.CHOP_500_TREES =("Chop down 500 trees", 500, WOODCUTTING, SKILLING, 4000)
Definition at line 105 of file AchievementList.java.
CLAIM_1000_VOTES
com.runehive.content.achievement.AchievementList.CLAIM_1000_VOTES =("Claim 1,000 vote rewards", 1000, VOTE, MISCELLANEOUS, 10000)
Definition at line 151 of file AchievementList.java.
CLAIM_100_VOTE
com.runehive.content.achievement.AchievementList.CLAIM_100_VOTE =("Claim 100 vote reward", 100, VOTE, MISCELLANEOUS, 1000)
Definition at line 148 of file AchievementList.java.
CLAIM_250_VOTES
com.runehive.content.achievement.AchievementList.CLAIM_250_VOTES =("Claim 250 vote rewards", 250, VOTE, MISCELLANEOUS, 2500)
Definition at line 149 of file AchievementList.java.
CLAIM_500_VOTES
com.runehive.content.achievement.AchievementList.CLAIM_500_VOTES =("Claim 500 vote rewards", 500, VOTE, MISCELLANEOUS, 5000)
Definition at line 150 of file AchievementList.java.
COMPLETE_100_BARROW
com.runehive.content.achievement.AchievementList.COMPLETE_100_BARROW =("Complete 100 Barrows runs", 100, BARROWS, MINIGAME, 3500)
Definition at line 132 of file AchievementList.java.
COMPLETE_100_CLUE_SCROLLS
com.runehive.content.achievement.AchievementList.COMPLETE_100_CLUE_SCROLLS =("Complete 100 clue scrolls", 100, CLUE_SCROLLS, MISCELLANEOUS, 1500)
Definition at line 163 of file AchievementList.java.
COMPLETE_100_SLAYER_TASKS
com.runehive.content.achievement.AchievementList.COMPLETE_100_SLAYER_TASKS =("Complete 100 slayer tasks", 100, SLAYER_TASKS, MISCELLANEOUS, 10000)
Definition at line 146 of file AchievementList.java.
COMPLETE_10_CLUE_SCROLLS
com.runehive.content.achievement.AchievementList.COMPLETE_10_CLUE_SCROLLS =("Complete 10 clue scrolls", 10, CLUE_SCROLLS, MISCELLANEOUS, 1500)
Definition at line 160 of file AchievementList.java.
COMPLETE_10_SLAYER_TASKS
com.runehive.content.achievement.AchievementList.COMPLETE_10_SLAYER_TASKS =("Complete 10 slayer tasks", 10, SLAYER_TASKS, MISCELLANEOUS, 10000)
Definition at line 144 of file AchievementList.java.
COMPLETE_150_PC_GAME
com.runehive.content.achievement.AchievementList.COMPLETE_150_PC_GAME =("Complete 150 PC games", 150, PEST_CONTROL, MINIGAME, 7500)
Definition at line 139 of file AchievementList.java.
COMPLETE_250_SLAYER_TASKS
com.runehive.content.achievement.AchievementList.COMPLETE_250_SLAYER_TASKS =("Complete 250 slayer tasks", 250, SLAYER_TASKS, MISCELLANEOUS, 10000)
Definition at line 147 of file AchievementList.java.
COMPLETE_25_CLUE_SCROLLS
com.runehive.content.achievement.AchievementList.COMPLETE_25_CLUE_SCROLLS =("Complete 25 clue scrolls", 25, CLUE_SCROLLS, MISCELLANEOUS, 1500)
Definition at line 161 of file AchievementList.java.
COMPLETE_25_PC_GAME
com.runehive.content.achievement.AchievementList.COMPLETE_25_PC_GAME =("Complete 25 PC games", 25, PEST_CONTROL, MINIGAME, 1500)
Definition at line 137 of file AchievementList.java.
COMPLETE_500_BARROWS
com.runehive.content.achievement.AchievementList.COMPLETE_500_BARROWS =("Complete 500 Barrows runs", 500, BARROWS, MINIGAME, 7500)
Definition at line 133 of file AchievementList.java.
COMPLETE_50_BARROWS
com.runehive.content.achievement.AchievementList.COMPLETE_50_BARROWS =("Complete 50 Barrows runs", 50, BARROWS, MINIGAME, 1500)
Definition at line 131 of file AchievementList.java.
COMPLETE_50_CLUE_SCROLLS
com.runehive.content.achievement.AchievementList.COMPLETE_50_CLUE_SCROLLS =("Complete 50 clue scrolls", 50, CLUE_SCROLLS, MISCELLANEOUS, 1500)
Definition at line 162 of file AchievementList.java.
COMPLETE_50_PC_GAME
com.runehive.content.achievement.AchievementList.COMPLETE_50_PC_GAME =("Complete 50 PC games", 50, PEST_CONTROL, MINIGAME, 3500)
Definition at line 138 of file AchievementList.java.
COMPLETE_50_SLAYER_TASKS
com.runehive.content.achievement.AchievementList.COMPLETE_50_SLAYER_TASKS =("Complete 50 slayer tasks", 50, SLAYER_TASKS, MISCELLANEOUS, 10000)
Definition at line 145 of file AchievementList.java.
COMPLETE_5_BARROWS
com.runehive.content.achievement.AchievementList.COMPLETE_5_BARROWS =("Complete 5 Barrows runs", 5, BARROWS, MINIGAME, 500)
Definition at line 130 of file AchievementList.java.
COMPLETE_5_PC_GAME
com.runehive.content.achievement.AchievementList.COMPLETE_5_PC_GAME =("Complete 5 PC game", 5, PEST_CONTROL, MINIGAME, 500)
Definition at line 136 of file AchievementList.java.
CRAFT_100_OF_ANY_RUNES
com.runehive.content.achievement.AchievementList.CRAFT_100_OF_ANY_RUNES =("Craft 100 of any runes", 100, RUNECRAFTING, SKILLING, 500)
Definition at line 112 of file AchievementList.java.
CRAFT_1500_OF_ANY_RUNES
com.runehive.content.achievement.AchievementList.CRAFT_1500_OF_ANY_RUNES =("Craft 1500 of any runes", 1500, RUNECRAFTING, SKILLING, 4000)
Definition at line 114 of file AchievementList.java.
CRAFT_5000_OF_ANY_RUNES
com.runehive.content.achievement.AchievementList.CRAFT_5000_OF_ANY_RUNES =("Craft 5000 of any runes", 5000, RUNECRAFTING, SKILLING, 7000)
Definition at line 115 of file AchievementList.java.
CRAFT_500_OF_ANY_RUNES
com.runehive.content.achievement.AchievementList.CRAFT_500_OF_ANY_RUNES =("Craft 500 of any runes", 500, RUNECRAFTING, SKILLING, 1500)
Definition at line 113 of file AchievementList.java.
ENCHANT_10000_BOLTS
com.runehive.content.achievement.AchievementList.ENCHANT_10000_BOLTS =("Enchant 10,000 bolts", 10000, ENCHANT_BOLTS, SKILLING, 5000)
Definition at line 121 of file AchievementList.java.
ENCHANT_2500_BOLTS
com.runehive.content.achievement.AchievementList.ENCHANT_2500_BOLTS =("Enchant 2,500 bolts", 2500, ENCHANT_BOLTS, SKILLING, 2500)
Definition at line 120 of file AchievementList.java.
EXPERIENCE_MASTERY
com.runehive.content.achievement.AchievementList.EXPERIENCE_MASTERY =("Earn 200M EXP in 5 skills", 5, AchievementKey.EXPERIENCE_MASTERY, SKILLING, 7500)
Definition at line 101 of file AchievementList.java.
FLETCH_10000_ARROWS
com.runehive.content.achievement.AchievementList.FLETCH_10000_ARROWS =("Fletch 10,000 arrows", 10000, FLETCHING, SKILLING, 5000)
Definition at line 123 of file AchievementList.java.
FLETCH_2500_ARROWS
com.runehive.content.achievement.AchievementList.FLETCH_2500_ARROWS =("Fletch 2,500 arrows", 2500, FLETCHING, SKILLING, 2500)
Definition at line 122 of file AchievementList.java.
GET_1000_TOTAL_LEVELS
com.runehive.content.achievement.AchievementList.GET_1000_TOTAL_LEVELS =("Achieve 1,000 total level", 1000, TOTAL_LEVEL, SKILLING, 3000)
Definition at line 98 of file AchievementList.java.
GET_10_FIRE_CAPES
com.runehive.content.achievement.AchievementList.GET_10_FIRE_CAPES =("Get 10 fire capes", 10, FIRE_CAPE, MINIGAME, 1000)
Definition at line 129 of file AchievementList.java.
GET_10_ITEM_FROM_BARROWS
com.runehive.content.achievement.AchievementList.GET_10_ITEM_FROM_BARROWS =("Get 10 unique item from barrows", 10, BARROWS_UNIQUE, MINIGAME, 1000)
Definition at line 135 of file AchievementList.java.
GET_1500_TOTAL_LEVEL
com.runehive.content.achievement.AchievementList.GET_1500_TOTAL_LEVEL =("Achieve 1,500 total level", 1500, TOTAL_LEVEL, SKILLING, 5000)
Definition at line 99 of file AchievementList.java.
GET_1_ITEM_FROM_BARROWS
com.runehive.content.achievement.AchievementList.GET_1_ITEM_FROM_BARROWS =("Get 1 unique item from barrows", 1, BARROWS_UNIQUE, MINIGAME, 250)
Definition at line 134 of file AchievementList.java.
GET_2000_TOTAL_LEVELS
com.runehive.content.achievement.AchievementList.GET_2000_TOTAL_LEVELS =("Achieve 2,000 total level", 2000, TOTAL_LEVEL, SKILLING, 8000)
Definition at line 100 of file AchievementList.java.
GET_A_10_KILLSTREAK
com.runehive.content.achievement.AchievementList.GET_A_10_KILLSTREAK =("Kill 10 players without dying", 1, KILLSTKREAK_10, PVP, 2500)
Definition at line 48 of file AchievementList.java.
GET_A_15_KILLSTREAK
com.runehive.content.achievement.AchievementList.GET_A_15_KILLSTREAK =("Kill 15 players without dying", 1, KILLSTKREAK_15, PVP, 5000)
Definition at line 49 of file AchievementList.java.
GET_A_25_KILLSTREAK
com.runehive.content.achievement.AchievementList.GET_A_25_KILLSTREAK =("Kill 25 players without dying", 1, KILLSTKREAK_25, PVP, 8500)
Definition at line 50 of file AchievementList.java.
GET_A_5_KILLSTREAK
com.runehive.content.achievement.AchievementList.GET_A_5_KILLSTREAK =("Kill 5 players without dying", 1, KILLSTKREAK_5, PVP, 1000)
Definition at line 47 of file AchievementList.java.
GET_YOUR_FIRST_FIRE_CAPE
com.runehive.content.achievement.AchievementList.GET_YOUR_FIRST_FIRE_CAPE =("Get your first fire cape", 1, FIRE_CAPE, MINIGAME, 150)
Minigame achievements.
Definition at line 128 of file AchievementList.java.
HIT_45_WITH_DRAGON_MACE
com.runehive.content.achievement.AchievementList.HIT_45_WITH_DRAGON_MACE =("Hit 45+ with Dragon mace special\\non player 10 times", 10, DMACE_MAX, PVP, 5000)
Definition at line 30 of file AchievementList.java.
HIT_80_WITH_AGS
com.runehive.content.achievement.AchievementList.HIT_80_WITH_AGS =("Hit 80+ with AGS special on player 10 times", 10, AGS_SPEC, PVP, 5000)
Definition at line 29 of file AchievementList.java.
key
final AchievementKey com.runehive.content.achievement.AchievementList.key private
Definition at line 181 of file AchievementList.java.
Referenced by AchievementList(), and getKey().
KILL_10000_NPCS
com.runehive.content.achievement.AchievementList.KILL_10000_NPCS =("Kill 10000 NPC's", 10000, NPCS, MISCELLANEOUS, 10000)
Definition at line 171 of file AchievementList.java.
KILL_1000_NPCS
com.runehive.content.achievement.AchievementList.KILL_1000_NPCS =("Kill 1000 NPC's", 1000, NPCS, MISCELLANEOUS, 10000)
Definition at line 168 of file AchievementList.java.
KILL_1000_PLAYERS
com.runehive.content.achievement.AchievementList.KILL_1000_PLAYERS =("Kill 1,000 players using anything", 1000, KILLER, PVP, 35000)
Definition at line 23 of file AchievementList.java.
KILL_1000_REVS
com.runehive.content.achievement.AchievementList.KILL_1000_REVS =("Kill 1000 revenants", 1000, REVS, PVM, 10000)
Definition at line 92 of file AchievementList.java.
KILL_100_KBD
com.runehive.content.achievement.AchievementList.KILL_100_KBD =("Kill King Black Dragons 100 times", 100, KING_BLACK_DRAGON, PVM, 3000)
Definition at line 54 of file AchievementList.java.
KILL_100_KRAKENS
com.runehive.content.achievement.AchievementList.KILL_100_KRAKENS =("Kill Kraken 100 times", 100, KRAKEN, PVM, 3000)
Definition at line 58 of file AchievementList.java.
KILL_100_REVS
com.runehive.content.achievement.AchievementList.KILL_100_REVS =("Kill 100 revenants", 100, REVS, PVM, 10000)
Definition at line 89 of file AchievementList.java.
KILL_10_CERBERUS
com.runehive.content.achievement.AchievementList.KILL_10_CERBERUS =("Kill Cerberus 10 times", 10, CERBERUS, PVM, 1000)
Definition at line 81 of file AchievementList.java.
KILL_10_COMMANDERS
com.runehive.content.achievement.AchievementList.KILL_10_COMMANDERS =("Kill Commander Zilyana 10 times", 10, ZILYANA, PVM, 1000)
Definition at line 65 of file AchievementList.java.
KILL_10_GENERARS
com.runehive.content.achievement.AchievementList.KILL_10_GENERARS =("Kill General Graardor 10 times", 10, GRAARDOR, PVM, 1000)
Definition at line 69 of file AchievementList.java.
KILL_10_KBD
com.runehive.content.achievement.AchievementList.KILL_10_KBD =("Kill King Black Dragons 10 times", 10, KING_BLACK_DRAGON, PVM, 1000)
PvM achievements.
Definition at line 53 of file AchievementList.java.
KILL_10_KRAKENS
com.runehive.content.achievement.AchievementList.KILL_10_KRAKENS =("Kill Kraken 10 times", 10, KRAKEN, PVM, 1000)
Definition at line 57 of file AchievementList.java.
KILL_10_KREES
com.runehive.content.achievement.AchievementList.KILL_10_KREES =("Kill Kree Arra 10 times", 10, KREE, PVM, 1000)
Definition at line 73 of file AchievementList.java.
KILL_10_KRILS
com.runehive.content.achievement.AchievementList.KILL_10_KRILS =("Kill K'ril Tsutaroth 10 times", 10, KRIL, PVM, 1000)
Definition at line 77 of file AchievementList.java.
KILL_10_PLAYERS
com.runehive.content.achievement.AchievementList.KILL_10_PLAYERS =("Kill 10 players using anything", 10, KILLER, PVP, 2500)
PvP achievements.
Definition at line 19 of file AchievementList.java.
KILL_10_VORKATHS
com.runehive.content.achievement.AchievementList.KILL_10_VORKATHS =("Kill Vorkath 10 times", 10, VORKATH, PVM, 1000)
Definition at line 85 of file AchievementList.java.
KILL_10_WITH_AGS
com.runehive.content.achievement.AchievementList.KILL_10_WITH_AGS =("Kill 10 players using AGS special", 10, AGS_SPEC, PVP, 2500)
Definition at line 36 of file AchievementList.java.
KILL_10_WITH_DARK_BOW
com.runehive.content.achievement.AchievementList.KILL_10_WITH_DARK_BOW =("Kill 10 players using Dark bow special", 10, DARKBOW_SPEC, PVP, 2500)
Definition at line 45 of file AchievementList.java.
KILL_10_WITH_DCLAWS
com.runehive.content.achievement.AchievementList.KILL_10_WITH_DCLAWS =("Kill 10 players using Dragon claws special", 10, DCLAWS_SPEC, PVP, 2500)
Definition at line 39 of file AchievementList.java.
KILL_10_WITH_DDS
com.runehive.content.achievement.AchievementList.KILL_10_WITH_DDS =("Kill 10 players using DDS special", 10, DDS_SPEC, PVP, 2500)
Definition at line 33 of file AchievementList.java.
KILL_10_WITH_DHAROK
com.runehive.content.achievement.AchievementList.KILL_10_WITH_DHAROK =("Kill 10 players using full d'haroks", 10, DHAROK, PVP, 2500)
Definition at line 24 of file AchievementList.java.
KILL_10_WITH_DRAGON_MACE
com.runehive.content.achievement.AchievementList.KILL_10_WITH_DRAGON_MACE =("Kill 10 players using Dragon mace special", 10, DMACE_SPEC, PVP, 2500)
Definition at line 31 of file AchievementList.java.
KILL_10_WITH_GMAUL
com.runehive.content.achievement.AchievementList.KILL_10_WITH_GMAUL =("Kill 10 players with a Granite maul special", 10, GMAULED_SPEC, PVP, 2500)
Definition at line 42 of file AchievementList.java.
KILL_10_ZULRAH
com.runehive.content.achievement.AchievementList.KILL_10_ZULRAH =("Kill Zulrah 10 times", 10, ZULRAH, PVM, 1000)
Definition at line 61 of file AchievementList.java.
KILL_125_CERBERUS
com.runehive.content.achievement.AchievementList.KILL_125_CERBERUS =("Kill Cerberus 125 times", 125, CERBERUS, PVM, 6000)
Definition at line 83 of file AchievementList.java.
KILL_125_COMMANDERS
com.runehive.content.achievement.AchievementList.KILL_125_COMMANDERS =("Kill Commander Zilyana 125 times", 125, ZILYANA, PVM, 6000)
Definition at line 67 of file AchievementList.java.
KILL_125_GENERALS
com.runehive.content.achievement.AchievementList.KILL_125_GENERALS =("Kill General Graardor 125 times", 125, GRAARDOR, PVM, 6000)
Definition at line 71 of file AchievementList.java.
KILL_125_KREES
com.runehive.content.achievement.AchievementList.KILL_125_KREES =("Kill Kree Arra 125 times", 125, KREE, PVM, 6000)
Definition at line 75 of file AchievementList.java.
KILL_125_KRILS
com.runehive.content.achievement.AchievementList.KILL_125_KRILS =("Kill K'ril Tsutaroth 125 times", 125, KRIL, PVM, 6000)
Definition at line 79 of file AchievementList.java.
KILL_125_VORKATHS
com.runehive.content.achievement.AchievementList.KILL_125_VORKATHS =("Kill Vorkath 125 times", 125, VORKATH, PVM, 6000)
Definition at line 87 of file AchievementList.java.
KILL_150_PLAYERS
com.runehive.content.achievement.AchievementList.KILL_150_PLAYERS =("Kill 150 players using anything", 150, KILLER, PVP, 12500)
Definition at line 21 of file AchievementList.java.
KILL_150_WITH_AGS
com.runehive.content.achievement.AchievementList.KILL_150_WITH_AGS =("Kill 150 players using AGS special", 150, AGS_SPEC, PVP, 5000)
Definition at line 37 of file AchievementList.java.
KILL_150_WITH_DCLAWS
com.runehive.content.achievement.AchievementList.KILL_150_WITH_DCLAWS =("Kill 150 players using Dragon claws special", 150, DCLAWS_SPEC, PVP, 5000)
Definition at line 40 of file AchievementList.java.
KILL_150_WITH_DDS
com.runehive.content.achievement.AchievementList.KILL_150_WITH_DDS =("Kill 150 players using DDS special", 150, DDS_SPEC, PVP, 5000)
Definition at line 34 of file AchievementList.java.
KILL_150_WITH_DHAROK
com.runehive.content.achievement.AchievementList.KILL_150_WITH_DHAROK =("Kill 150 players using full d'haroks", 150, DHAROK, PVP, 12500)
Definition at line 26 of file AchievementList.java.
KILL_150_WITH_GMAUL
com.runehive.content.achievement.AchievementList.KILL_150_WITH_GMAUL =("Kill 150 players with a Granite maul special", 150, GMAULED_SPEC, PVP, 5000)
Definition at line 43 of file AchievementList.java.
KILL_2500_NPCS
com.runehive.content.achievement.AchievementList.KILL_2500_NPCS =("Kill 2500 NPC's", 2500, NPCS, MISCELLANEOUS, 10000)
Definition at line 169 of file AchievementList.java.
KILL_250_REVS
com.runehive.content.achievement.AchievementList.KILL_250_REVS =("Kill 250 revenants", 250, REVS, PVM, 10000)
Definition at line 90 of file AchievementList.java.
KILL_300_ZULRAHS
com.runehive.content.achievement.AchievementList.KILL_300_ZULRAHS =("Kill Zulrah 300 times", 300, ZULRAH, PVM, 6000)
Definition at line 63 of file AchievementList.java.
KILL_350_KBD
com.runehive.content.achievement.AchievementList.KILL_350_KBD =("Kill King Black Dragons 350 times", 350, KING_BLACK_DRAGON, PVM, 6000)
Definition at line 55 of file AchievementList.java.
KILL_350_KRAKENS
com.runehive.content.achievement.AchievementList.KILL_350_KRAKENS =("Kill Kraken 350 times", 350, KRAKEN, PVM, 6000)
Definition at line 59 of file AchievementList.java.
KILL_350_WITH_AGS
com.runehive.content.achievement.AchievementList.KILL_350_WITH_AGS =("Kill 350 players using AGS special", 350, AGS_SPEC, PVP, 8000)
Definition at line 38 of file AchievementList.java.
KILL_350_WITH_DCLAWS
com.runehive.content.achievement.AchievementList.KILL_350_WITH_DCLAWS =("Kill 350 players using Dragon claws special", 350, DCLAWS_SPEC, PVP, 8000)
Definition at line 41 of file AchievementList.java.
KILL_350_WITH_DDS
com.runehive.content.achievement.AchievementList.KILL_350_WITH_DDS =("Kill 350 players using DDS special", 350, DDS_SPEC, PVP, 8000)
Definition at line 35 of file AchievementList.java.
KILL_350_WITH_GMAUL
com.runehive.content.achievement.AchievementList.KILL_350_WITH_GMAUL =("Kill 350 players with a Granite maul special", 350, GMAULED_SPEC, PVP, 8000)
Definition at line 44 of file AchievementList.java.
KILL_35_CERBERUS
com.runehive.content.achievement.AchievementList.KILL_35_CERBERUS =("Kill Cerberus 35 times", 35, CERBERUS, PVM, 3000)
Definition at line 82 of file AchievementList.java.
KILL_35_COMMANDERS
com.runehive.content.achievement.AchievementList.KILL_35_COMMANDERS =("Kill Commander Zilyana 35 times", 35, ZILYANA, PVM, 3000)
Definition at line 66 of file AchievementList.java.
KILL_35_GENERALS
com.runehive.content.achievement.AchievementList.KILL_35_GENERALS =("Kill General Graardor 35 times", 35, GRAARDOR, PVM, 3000)
Definition at line 70 of file AchievementList.java.
KILL_35_KREES
com.runehive.content.achievement.AchievementList.KILL_35_KREES =("Kill Kree Arra 35 times", 35, KREE, PVM, 3000)
Definition at line 74 of file AchievementList.java.
KILL_35_KRILS
com.runehive.content.achievement.AchievementList.KILL_35_KRILS =("Kill K'ril Tsutaroth 35 times", 35, KRIL, PVM, 3000)
Definition at line 78 of file AchievementList.java.
KILL_35_VORKATHS
com.runehive.content.achievement.AchievementList.KILL_35_VORKATHS =("Kill Vorkath 35 times", 35, VORKATH, PVM, 3000)
Definition at line 86 of file AchievementList.java.
KILL_5000_NPCS
com.runehive.content.achievement.AchievementList.KILL_5000_NPCS =("Kill 5000 NPC's", 5000, NPCS, MISCELLANEOUS, 10000)
Definition at line 170 of file AchievementList.java.
KILL_500_CERBERUS
com.runehive.content.achievement.AchievementList.KILL_500_CERBERUS =("Kill Cerberus 500 times", 500, CERBERUS, PVM, 10000)
Definition at line 84 of file AchievementList.java.
KILL_500_COMMANDERS
com.runehive.content.achievement.AchievementList.KILL_500_COMMANDERS =("Kill Commander Zilyana 500 times", 500, ZILYANA, PVM, 10000)
Definition at line 68 of file AchievementList.java.
KILL_500_GENERALS
com.runehive.content.achievement.AchievementList.KILL_500_GENERALS =("Kill General Graardor 500 times", 500, GRAARDOR, PVM, 10000)
Definition at line 72 of file AchievementList.java.
KILL_500_KREES
com.runehive.content.achievement.AchievementList.KILL_500_KREES =("Kill Kree Arra 500 times", 500, KREE, PVM, 10000)
Definition at line 76 of file AchievementList.java.
KILL_500_KRILS
com.runehive.content.achievement.AchievementList.KILL_500_KRILS =("Kill K'ril Tsutaroth 500 times", 500, KRIL, PVM, 10000)
Definition at line 80 of file AchievementList.java.
KILL_500_PLAYERS
com.runehive.content.achievement.AchievementList.KILL_500_PLAYERS =("Kill 500 players using anything", 500, KILLER, PVP, 20000)
Definition at line 22 of file AchievementList.java.
KILL_500_REVS
com.runehive.content.achievement.AchievementList.KILL_500_REVS =("Kill 500 revenants", 500, REVS, PVM, 10000)
Definition at line 91 of file AchievementList.java.
KILL_500_VORKATHS
com.runehive.content.achievement.AchievementList.KILL_500_VORKATHS =("Kill Vorkath 500 times", 500, VORKATH, PVM, 10000)
Definition at line 88 of file AchievementList.java.
KILL_500_ZULRAHS
com.runehive.content.achievement.AchievementList.KILL_500_ZULRAHS =("Kill Zulrah 500 times", 500, ZULRAH, PVM, 10000)
Definition at line 64 of file AchievementList.java.
KILL_50_PLAYERS
com.runehive.content.achievement.AchievementList.KILL_50_PLAYERS =("Kill 50 players using anything", 50, KILLER, PVP, 6500)
Definition at line 20 of file AchievementList.java.
KILL_50_WITH_DHAROK
com.runehive.content.achievement.AchievementList.KILL_50_WITH_DHAROK =("Kill 50 players using full d'haroks", 50, DHAROK, PVP, 6500)
Definition at line 25 of file AchievementList.java.
KILL_50_ZULRAH
com.runehive.content.achievement.AchievementList.KILL_50_ZULRAH =("Kill Zulrah 50 times", 50, ZULRAH, PVM, 3000)
Definition at line 62 of file AchievementList.java.
KILL_75_WITH_DARK_BOW
com.runehive.content.achievement.AchievementList.KILL_75_WITH_DARK_BOW =("Kill 75 players using Dark bow special", 75, DARKBOW_SPEC, PVP, 5000)
Definition at line 46 of file AchievementList.java.
KILL_75_WITH_DRAGON_MACE
com.runehive.content.achievement.AchievementList.KILL_75_WITH_DRAGON_MACE =("Kill 75 players using Dragon mace special", 75, DMACE_SPEC, PVP, 5000)
Definition at line 32 of file AchievementList.java.
KILL_800_KBD
com.runehive.content.achievement.AchievementList.KILL_800_KBD =("Kill King Black Dragons 800 times", 800, KING_BLACK_DRAGON, PVM, 10000)
Definition at line 56 of file AchievementList.java.
KILL_800_KRAKENS
com.runehive.content.achievement.AchievementList.KILL_800_KRAKENS =("Kill Kraken 800 times", 800, KRAKEN, PVM, 10000)
Definition at line 60 of file AchievementList.java.
MAKE_10000_POTIONS
com.runehive.content.achievement.AchievementList.MAKE_10000_POTIONS =("Make 10,000 potions with herblore", 10000, HERBLORE, SKILLING, 7500)
Definition at line 125 of file AchievementList.java.
MAKE_2500_POTIONS
com.runehive.content.achievement.AchievementList.MAKE_2500_POTIONS =("Make 2,500 potions with herblore", 2500, HERBLORE, SKILLING, 3250)
Definition at line 124 of file AchievementList.java.
MAX_1_SKILL
com.runehive.content.achievement.AchievementList.MAX_1_SKILL =("Achieve level 99 in 1 skill", 1, SKILL_MASTERY, SKILLING, 2000)
Skilling achievements.
Definition at line 95 of file AchievementList.java.
MAX_200M_EXPERIENCE
com.runehive.content.achievement.AchievementList.MAX_200M_EXPERIENCE =("Earn 200M EXP in all skills", Skill.SKILL_COUNT, AchievementKey.EXPERIENCE_MASTERY, SKILLING, 30000)
Definition at line 102 of file AchievementList.java.
MAX_3_SKILLS
com.runehive.content.achievement.AchievementList.MAX_3_SKILLS =("Achieve level 99 in 3 skills", 3, SKILL_MASTERY, SKILLING, 4000)
Definition at line 96 of file AchievementList.java.
MAX_ALL_SKILLS
com.runehive.content.achievement.AchievementList.MAX_ALL_SKILLS =("Achieve level 99 in all skills", Skill.SKILL_COUNT, SKILL_MASTERY, SKILLING, 10000)
Definition at line 97 of file AchievementList.java.
MINE_100_ROCKS
com.runehive.content.achievement.AchievementList.MINE_100_ROCKS =("Mine 100 rocks", 100, MINNING, SKILLING, 1000)
Definition at line 108 of file AchievementList.java.
MINE_1500_ROCKS
com.runehive.content.achievement.AchievementList.MINE_1500_ROCKS =("Mine 1,500 rocks", 1500, MINNING, SKILLING, 4000)
Definition at line 110 of file AchievementList.java.
MINE_5000_ROCKS
com.runehive.content.achievement.AchievementList.MINE_5000_ROCKS =("Mine 5,000 rocks", 5000, MINNING, SKILLING, 7000)
Definition at line 111 of file AchievementList.java.
MINE_500_ROCKS
com.runehive.content.achievement.AchievementList.MINE_500_ROCKS =("Mine 500 rocks", 500, MINNING, SKILLING, 2500)
Definition at line 109 of file AchievementList.java.
OBTAIN_100_RARE_DROPS
com.runehive.content.achievement.AchievementList.OBTAIN_100_RARE_DROPS =("Obtain 100 rare drops", 100, RARE_DROPS, MISCELLANEOUS, 1000)
Definition at line 173 of file AchievementList.java.
OBTAIN_10_PETS
com.runehive.content.achievement.AchievementList.OBTAIN_10_PETS =("Obtain 10 of any pets", 10, OBTAIN_PET, MISCELLANEOUS, 5000)
Definition at line 178 of file AchievementList.java.
OBTAIN_250_RARE_DROPS
com.runehive.content.achievement.AchievementList.OBTAIN_250_RARE_DROPS =("Obtain 250 rare drops", 250, RARE_DROPS, MISCELLANEOUS, 1000)
Definition at line 174 of file AchievementList.java.
OBTAIN_500_RARE_DROPS
com.runehive.content.achievement.AchievementList.OBTAIN_500_RARE_DROPS =("Obtain 500 rare drops", 500, RARE_DROPS, MISCELLANEOUS, 1000)
Definition at line 175 of file AchievementList.java.
OBTAIN_50_RARE_DROPS
com.runehive.content.achievement.AchievementList.OBTAIN_50_RARE_DROPS =("Obtain 50 rare drops", 50, RARE_DROPS, MISCELLANEOUS, 1000)
Definition at line 172 of file AchievementList.java.
OBTAIN_5_PETS
com.runehive.content.achievement.AchievementList.OBTAIN_5_PETS =("Obtain 5 of any pets", 5, OBTAIN_PET, MISCELLANEOUS, 2500)
Definition at line 177 of file AchievementList.java.
OBTAIN_YOUR_FIRST_PET
com.runehive.content.achievement.AchievementList.OBTAIN_YOUR_FIRST_PET =("Obtain 1 of any pets", 1, OBTAIN_PET, MISCELLANEOUS, 1000)
Definition at line 176 of file AchievementList.java.
OPEN_10_CASKETS
com.runehive.content.achievement.AchievementList.OPEN_10_CASKETS =("Open 10 caskets", 10, CASKET, MISCELLANEOUS, 1000)
Definition at line 164 of file AchievementList.java.
OPEN_10_CRYSTAL_CHESTS
com.runehive.content.achievement.AchievementList.OPEN_10_CRYSTAL_CHESTS =("Open 10 crystal chests", 10, CRYSTAL_CHEST, MISCELLANEOUS, 1000)
Definition at line 156 of file AchievementList.java.
OPEN_150_CASKETS
com.runehive.content.achievement.AchievementList.OPEN_150_CASKETS =("Open 150 caskets", 150, CASKET, MISCELLANEOUS, 5000)
Definition at line 166 of file AchievementList.java.
OPEN_150_CRYSTAL_CHESTS
com.runehive.content.achievement.AchievementList.OPEN_150_CRYSTAL_CHESTS =("Open 150 crystal chests", 150, CRYSTAL_CHEST, MISCELLANEOUS, 5000)
Definition at line 158 of file AchievementList.java.
OPEN_500_CASKETS
com.runehive.content.achievement.AchievementList.OPEN_500_CASKETS =("Open 500 caskets", 500, CASKET, MISCELLANEOUS, 7500)
Definition at line 167 of file AchievementList.java.
OPEN_500_CRYSTAL_CHESTS
com.runehive.content.achievement.AchievementList.OPEN_500_CRYSTAL_CHESTS =("Open 500 crystal chests", 500, CRYSTAL_CHEST, MISCELLANEOUS, 7500)
Definition at line 159 of file AchievementList.java.
OPEN_50_CASKETS
com.runehive.content.achievement.AchievementList.OPEN_50_CASKETS =("Open 50 caskets", 50, CASKET, MISCELLANEOUS, 2500)
Definition at line 165 of file AchievementList.java.
OPEN_50_CRYSTAL_CHESTS
com.runehive.content.achievement.AchievementList.OPEN_50_CRYSTAL_CHESTS =("Open 50 crystal chests", 50, CRYSTAL_CHEST, MISCELLANEOUS, 2500)
Definition at line 157 of file AchievementList.java.
reward
final int com.runehive.content.achievement.AchievementList.reward private
Definition at line 184 of file AchievementList.java.
Referenced by AchievementList(), and getReward().
RUN_1000_COURSES
com.runehive.content.achievement.AchievementList.RUN_1000_COURSES =("Complete 1,000\\nagility courses", 1000, AGILITY, SKILLING, 50000)
Definition at line 119 of file AchievementList.java.
RUN_150_COURSES
com.runehive.content.achievement.AchievementList.RUN_150_COURSES =("Complete 150 agility courses", 150, AGILITY, SKILLING, 10000)
Definition at line 117 of file AchievementList.java.
RUN_500_COURSES
com.runehive.content.achievement.AchievementList.RUN_500_COURSES =("Complete 500 agility courses", 500, AGILITY, SKILLING, 25000)
Definition at line 118 of file AchievementList.java.
RUN_50_COURSES
com.runehive.content.achievement.AchievementList.RUN_50_COURSES =("Complete 50 agility courses", 50, AGILITY, SKILLING, 5000)
Definition at line 116 of file AchievementList.java.
task
final String com.runehive.content.achievement.AchievementList.task private
Definition at line 183 of file AchievementList.java.
Referenced by AchievementList(), and getTask().
type
final AchievementType com.runehive.content.achievement.AchievementList.type private
Definition at line 182 of file AchievementList.java.
Referenced by AchievementList(), and getType().
The documentation for this enum was generated from the following file:
java/com/runehive/content/achievement/AchievementList.java