RuneHive-Game: com.runehive.content.skill.impl.magic.enchant.SpellEnchant Enum Reference
com.runehive.content.skill.impl.magic.enchant.SpellEnchant Enum Reference
Public Member Functions
Item[] getRunes ()
int getSpell ()
SpellEnchant (int spell, Item... runes)
Static Public Member Functions
static SpellEnchant forSpell (int id)
Public Attributes
DIAMOND =(1180, new Item(557, 10), new Item(564, 1))
DRAGONSTONE =(1187, new Item(555, 15), new Item(557, 15), new Item(564, 1))
EMERALD =(1165, new Item(556, 3), new Item(564, 1))
ONYX =(6003, new Item(557, 20), new Item(554, 20), new Item(564, 1))
RUBY =(1176, new Item(554, 5), new Item(564, 1))
SAPPHIRE =(1155, new Item(555, 1), new Item(564, 1))
ZENYTE =(40180, new Item(565, 20), new Item(566, 20), new Item(564))
Private Attributes
final Item[] runes
final int spell
Detailed Description
Definition at line 5 of file SpellEnchant.java.
Constructor & Destructor Documentation
SpellEnchant()
com.runehive.content.skill.impl.magic.enchant.SpellEnchant.SpellEnchant (int spell, Item... runes)
Definition at line 18 of file SpellEnchant.java.
{
        this.spell = spell;
        this.runes = runes;
    }
References runes, and spell.
Referenced by forSpell().
Member Function Documentation
forSpell()
SpellEnchant com.runehive.content.skill.impl.magic.enchant.SpellEnchant.forSpell (int id) static
Definition at line 31 of file SpellEnchant.java.
{
        for (SpellEnchant spellEnchant : values()) {
            if (spellEnchant.getSpell() == id)
                return spellEnchant;
        }
        return null;
    }
References SpellEnchant().
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem(), and com.runehive.content.skill.impl.magic.spell.SpellCasting.hasEnchantRunes().
getRunes()
Item[] com.runehive.content.skill.impl.magic.enchant.SpellEnchant.getRunes ()
Definition at line 27 of file SpellEnchant.java.
{
        return runes;
    }
References runes.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getSpell()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchant.getSpell ()
Definition at line 23 of file SpellEnchant.java.
{
        return spell;
    }
References spell.
Member Data Documentation
DIAMOND
com.runehive.content.skill.impl.magic.enchant.SpellEnchant.DIAMOND =(1180, new Item(557, 10), new Item(564, 1))
Definition at line 9 of file SpellEnchant.java.
DRAGONSTONE
com.runehive.content.skill.impl.magic.enchant.SpellEnchant.DRAGONSTONE =(1187, new Item(555, 15), new Item(557, 15), new Item(564, 1))
Definition at line 10 of file SpellEnchant.java.
EMERALD
com.runehive.content.skill.impl.magic.enchant.SpellEnchant.EMERALD =(1165, new Item(556, 3), new Item(564, 1))
Definition at line 7 of file SpellEnchant.java.
ONYX
com.runehive.content.skill.impl.magic.enchant.SpellEnchant.ONYX =(6003, new Item(557, 20), new Item(554, 20), new Item(564, 1))
Definition at line 11 of file SpellEnchant.java.
RUBY
com.runehive.content.skill.impl.magic.enchant.SpellEnchant.RUBY =(1176, new Item(554, 5), new Item(564, 1))
Definition at line 8 of file SpellEnchant.java.
runes
final Item [] com.runehive.content.skill.impl.magic.enchant.SpellEnchant.runes private
Definition at line 16 of file SpellEnchant.java.
Referenced by getRunes(), and SpellEnchant().
SAPPHIRE
com.runehive.content.skill.impl.magic.enchant.SpellEnchant.SAPPHIRE =(1155, new Item(555, 1), new Item(564, 1))
Definition at line 6 of file SpellEnchant.java.
spell
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchant.spell private
Definition at line 14 of file SpellEnchant.java.
Referenced by getSpell(), and SpellEnchant().
ZENYTE
com.runehive.content.skill.impl.magic.enchant.SpellEnchant.ZENYTE =(40180, new Item(565, 20), new Item(566, 20), new Item(564))
Definition at line 12 of file SpellEnchant.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/magic/enchant/SpellEnchant.java