RuneHive-Game: com.runehive.content.skill.impl.runecrafting.RunecraftPouchData Enum Reference
com.runehive.content.skill.impl.runecrafting.RunecraftPouchData Enum Reference
Holds the runecrafting pouch data.
Public Member Functions
abstract int deposit (Player player, int amount)
What happens to the runecrafting pouch when a player fills it.
abstract void empty (Player player)
Empties the runecrafting pouch.
RunecraftPouchData (int item, int level, int capacity, int decay)
Constructs a new RunecraftPouchData.
abstract int withdraw (Player player)
What happens to the runecrafting pouch when a player empties it.
Static Public Member Functions
static RunecraftPouchData forItem (int item)
Gets the runecrafting pouch data based on the item identification.
Public Attributes
final int capacity
The capacity that the runecrafting pouch can hold.
final int decay
The amount of uses before the runecrafting pouch will decay.
GIANT_POUCH
final int item
The item identification of the runecrafting pouch.
LARGE_POUCH
final int level
The level required to use the runecrafting pouch.
MEDIUM_POUCH
SMALL_POUCH
Detailed Description
Holds the runecrafting pouch data.
Author
Daniel
Definition at line 10 of file RunecraftPouchData.java.
Constructor & Destructor Documentation
RunecraftPouchData()
com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.RunecraftPouchData (int item, int level, int capacity, int decay)
Constructs a new RunecraftPouchData.
Definition at line 187 of file RunecraftPouchData.java.
{
        this.item = item;
        this.level = level;
        this.capacity = capacity;
        this.decay = decay;
    }
References capacity, decay, item, and level.
Referenced by forItem().
Member Function Documentation
deposit()
abstract int com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.deposit (Player player, int amount) abstract
What happens to the runecrafting pouch when a player fills it.
Referenced by com.runehive.content.skill.impl.runecrafting.RunecraftPouch.deposit().
empty()
abstract void com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.empty (Player player) abstract
Empties the runecrafting pouch.
Referenced by com.runehive.content.skill.impl.runecrafting.RunecraftPouch.death().
forItem()
RunecraftPouchData com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.forItem (int item) static
Gets the runecrafting pouch data based on the item identification.
Definition at line 195 of file RunecraftPouchData.java.
{
        for (RunecraftPouchData pouch : values()) {
            if (pouch.item == item)
                return pouch;
        }
        return null;
    }
References item, and RunecraftPouchData().
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.clickItem(), and com.runehive.content.skill.impl.runecrafting.RunecraftPouch.death().
withdraw()
abstract int com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.withdraw (Player player) abstract
What happens to the runecrafting pouch when a player empties it.
Referenced by com.runehive.content.skill.impl.runecrafting.RunecraftPouch.withdraw().
Member Data Documentation
capacity
final int com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.capacity
The capacity that the runecrafting pouch can hold.
Definition at line 172 of file RunecraftPouchData.java.
Referenced by com.runehive.content.skill.impl.runecrafting.RunecraftPouch.deposit(), and RunecraftPouchData().
decay
final int com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.decay
The amount of uses before the runecrafting pouch will decay.
Definition at line 175 of file RunecraftPouchData.java.
Referenced by RunecraftPouchData().
GIANT_POUCH
com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.GIANT_POUCH
Definition at line 163 of file RunecraftPouchData.java.
{
        public int deposit(Player player, int amount) {
            if (player.giantPouch >= capacity) {
                player.message("Your giant pouch is already filled to it's capacity!");
                return 0;
            }
            int essence = player.inventory.computeAmountForId(7936);
            if (amount > essence)
                amount = essence;
            if (player.giantPouch + amount > capacity)
                amount = capacity - player.giantPouch;
            return player.giantPouch += amount;
        }
        @Override
        public int withdraw(Player player) {
            if (player.giantPouch == 0) {
                player.message("You have no rune essences store in your giant pouch!");
                return 0;
            }
            if (player.inventory.getFreeSlots() < player.giantPouch){
                player.message("Please free up some inventory spaces before doing this!");
                return 0;
            }
            int amount = player.giantPouch;
            empty(player);
            return amount;
        }
        @Override
        public void empty(Player player) {
            player.giantPouch = 0;
        }
    };
item
final int com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.item
The item identification of the runecrafting pouch.
Definition at line 166 of file RunecraftPouchData.java.
Referenced by forItem(), and RunecraftPouchData().
LARGE_POUCH
com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.LARGE_POUCH
Definition at line 88 of file RunecraftPouchData.java.
{
        public int deposit(Player player, int amount) {
            if (player.largePouch >= capacity) {
                player.message("Your large pouch is already filled to it's capacity!");
                return 0;
            }
            int essence = player.inventory.computeAmountForId(7936);
            if (amount > essence)
                amount = essence;
            if (player.largePouch + amount > capacity)
                amount = capacity - player.largePouch;
            return player.largePouch += amount;
        }
        @Override
        public int withdraw(Player player) {
            if (player.largePouch == 0) {
                player.message("You have no rune essences store in your large pouch!");
                return 0;
            }
            if (player.inventory.getFreeSlots() < player.largePouch){
                player.message("Please free up some inventory spaces before doing this!");
                return 0;
            }
            int amount = player.largePouch;
            empty(player);
            return amount;
        }
        @Override
        public void empty(Player player) {
            player.largePouch = 0;
        }
    },
level
final int com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.level
The level required to use the runecrafting pouch.
Definition at line 169 of file RunecraftPouchData.java.
Referenced by com.runehive.content.skill.impl.runecrafting.RunecraftPouch.deposit(), and RunecraftPouchData().
MEDIUM_POUCH
com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.MEDIUM_POUCH
Definition at line 50 of file RunecraftPouchData.java.
{
        public int deposit(Player player, int amount) {
            if (player.mediumPouch >= capacity) {
                player.message("Your medium pouch is already filled to it's capacity!");
                return 0;
            }
            int essence = player.inventory.computeAmountForId(7936);
            if (amount > essence)
                amount = essence;
            if (player.mediumPouch + amount > capacity)
                amount = capacity - player.mediumPouch;
            return player.mediumPouch += amount;
        }
        @Override
        public int withdraw(Player player) {
            if (player.mediumPouch == 0) {
                player.message("You have no rune essences store in your medium pouch!");
                return 0;
            }
            if (player.inventory.getFreeSlots() < player.mediumPouch){
                player.message("Please free up some inventory spaces before doing this!");
                return 0;
            }
            int amount = player.mediumPouch;
            empty(player);
            return amount;
        }
        @Override
        public void empty(Player player) {
            player.mediumPouch = 0;
        }
    },
SMALL_POUCH
com.runehive.content.skill.impl.runecrafting.RunecraftPouchData.SMALL_POUCH
Definition at line 11 of file RunecraftPouchData.java.
{
        @Override
        public int deposit(Player player, int amount) {
            if (player.smallPouch >= capacity) {
                player.message("Your small pouch is already filled to it's capacity!");
                return 0;
            }
            int essence = player.inventory.computeAmountForId(7936);
            if (amount > essence)
                amount = essence;
            if (player.smallPouch + amount > capacity)
                amount = capacity - player.smallPouch;
            return player.smallPouch += amount;
        }
        @Override
        public int withdraw(Player player) {
            if (player.smallPouch == 0) {
                player.message("You have no rune essences store in your small pouch!");
                return 0;
            }
            if (player.inventory.getFreeSlots() < player.smallPouch){
                player.message("Please free up some inventory spaces before doing this!");
                return 0;
            }
            int amount = player.smallPouch;
            empty(player);
            return amount;
        }
        @Override
        public void empty(Player player) {
            player.smallPouch = 0;
        }
    },
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/runecrafting/RunecraftPouchData.java