RuneHive-Game: com.runehive.content.skill.impl.fletching.impl.Crossbow Enum Reference
com.runehive.content.skill.impl.fletching.impl.Crossbow Enum Reference
Public Member Functions
Crossbow (Item use, Item with, FletchableItem... items)
int getAnimation ()
FletchableItem[] getFletchableItems ()
int getGraphics ()
Item[] getIngredients ()
String getProductionMessage ()
Item getUse ()
Item getWith ()
Static Public Member Functions
static void load ()
Public Attributes
ADAMANT_CROSSBOW =(new Item(9450), new Item(9429), new FletchableItem(new Item(9463), 61, 82.0))
BRONZE_CROSSBOW =(new Item(9440), new Item(9420), new FletchableItem(new Item(9454), 9, 12.0))
IRON_CROSSBOW =(new Item(9444), new Item(9423), new FletchableItem(new Item(9457), 39, 44.0))
MITHRIL_CROSSBOW =(new Item(9448), new Item(9427), new FletchableItem(new Item(9461), 54, 64.0))
RUNE_CROSSBOW =(new Item(9452), new Item(9431), new FletchableItem(new Item(9465), 69, 100.0))
STEEL_CROSSBOW =(new Item(9446), new Item(9425), new FletchableItem(new Item(9459), 46, 54.0))
Private Attributes
final FletchableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 7 of file Crossbow.java.
Constructor & Destructor Documentation
Crossbow()
com.runehive.content.skill.impl.fletching.impl.Crossbow.Crossbow (Item use, Item with, FletchableItem... items)
Definition at line 19 of file Crossbow.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.fletching.impl.Crossbow.getAnimation ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 32 of file Crossbow.java.
{
        switch (this) {
        case BRONZE_CROSSBOW:
            return 4436;
        case IRON_CROSSBOW:
            return 4438;
        case STEEL_CROSSBOW:
            return 4439;
        case MITHRIL_CROSSBOW:
            return 4440;
        case ADAMANT_CROSSBOW:
            return 4441;
        case RUNE_CROSSBOW:
            return 4442;
        default:
            return 4436;
        }
    }
References ADAMANT_CROSSBOW, BRONZE_CROSSBOW, IRON_CROSSBOW, MITHRIL_CROSSBOW, RUNE_CROSSBOW, and STEEL_CROSSBOW.
getFletchableItems()
FletchableItem[] com.runehive.content.skill.impl.fletching.impl.Crossbow.getFletchableItems ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 67 of file Crossbow.java.
{
        return items;
    }
References items.
getGraphics()
int com.runehive.content.skill.impl.fletching.impl.Crossbow.getGraphics ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 52 of file Crossbow.java.
{
        return -1;
    }
getIngredients()
Item[] com.runehive.content.skill.impl.fletching.impl.Crossbow.getIngredients ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 77 of file Crossbow.java.
{
        return new Item[] { use, with };
    }
References use, and with.
getProductionMessage()
String com.runehive.content.skill.impl.fletching.impl.Crossbow.getProductionMessage ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 72 of file Crossbow.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.fletching.impl.Crossbow.getUse ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 57 of file Crossbow.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.fletching.impl.Crossbow.getWith ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 62 of file Crossbow.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.fletching.impl.Crossbow.load () static
Definition at line 25 of file Crossbow.java.
{
        for (Crossbow cuttable : values()) {
            Fletching.addFletchable(cuttable);
        }
    }
References com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), and Crossbow().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
ADAMANT_CROSSBOW
com.runehive.content.skill.impl.fletching.impl.Crossbow.ADAMANT_CROSSBOW =(new Item(9450), new Item(9429), new FletchableItem(new Item(9463), 61, 82.0))
Definition at line 12 of file Crossbow.java.
Referenced by getAnimation().
BRONZE_CROSSBOW
com.runehive.content.skill.impl.fletching.impl.Crossbow.BRONZE_CROSSBOW =(new Item(9440), new Item(9420), new FletchableItem(new Item(9454), 9, 12.0))
Definition at line 8 of file Crossbow.java.
Referenced by getAnimation().
IRON_CROSSBOW
com.runehive.content.skill.impl.fletching.impl.Crossbow.IRON_CROSSBOW =(new Item(9444), new Item(9423), new FletchableItem(new Item(9457), 39, 44.0))
Definition at line 9 of file Crossbow.java.
Referenced by getAnimation().
items
final FletchableItem [] com.runehive.content.skill.impl.fletching.impl.Crossbow.items private
Definition at line 17 of file Crossbow.java.
Referenced by Crossbow(), and getFletchableItems().
MITHRIL_CROSSBOW
com.runehive.content.skill.impl.fletching.impl.Crossbow.MITHRIL_CROSSBOW =(new Item(9448), new Item(9427), new FletchableItem(new Item(9461), 54, 64.0))
Definition at line 11 of file Crossbow.java.
Referenced by getAnimation().
RUNE_CROSSBOW
com.runehive.content.skill.impl.fletching.impl.Crossbow.RUNE_CROSSBOW =(new Item(9452), new Item(9431), new FletchableItem(new Item(9465), 69, 100.0))
Definition at line 13 of file Crossbow.java.
Referenced by getAnimation().
STEEL_CROSSBOW
com.runehive.content.skill.impl.fletching.impl.Crossbow.STEEL_CROSSBOW =(new Item(9446), new Item(9425), new FletchableItem(new Item(9459), 46, 54.0))
Definition at line 10 of file Crossbow.java.
Referenced by getAnimation().
use
final Item com.runehive.content.skill.impl.fletching.impl.Crossbow.use private
Definition at line 15 of file Crossbow.java.
Referenced by Crossbow(), getIngredients(), and getUse().
with
final Item com.runehive.content.skill.impl.fletching.impl.Crossbow.with private
Definition at line 16 of file Crossbow.java.
Referenced by Crossbow(), getIngredients(), and getWith().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fletching/impl/Crossbow.java