RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Gem Enum Reference
com.runehive.content.skill.impl.crafting.impl.Gem Enum Reference
Public Member Functions
Gem (Item use, Item with, CraftableItem... items)
int getAnimation ()
Gets the craftable animation.
CraftableItem[] getCraftableItems ()
Gets the craftable items.
Item[] getIngredients (int index)
Gets the craftable ingredients.
String getName ()
Gets the craftable name.
String getProductionMessage ()
Gets the craftable production message.
Item getUse ()
Gets the craftable used item.
Item getWith ()
Gets the craftable item used with.
Static Public Member Functions
static void load ()
Public Attributes
DIAMOND =(new Item(1755), new Item(1617), new CraftableItem(new Item(1601), new Item(1617), 43, 107.5))
DRAGONSTONE =(new Item(1755), new Item(1631), new CraftableItem(new Item(1615), new Item(1631), 55, 137.5))
EMERALD =(new Item(1755), new Item(1621), new CraftableItem(new Item(1605), new Item(1621), 27, 67.5))
JADE =(new Item(1755), new Item(1627), new CraftableItem(new Item(1611), new Item(1627), 13, 20.0))
ONYX =(new Item(1755), new Item(6571), new CraftableItem(new Item(6573), new Item(6571), 67, 167.5))
OPAL =(new Item(1755), new Item(1625), new CraftableItem(new Item(1609), new Item(1625), 1, 15.0))
RED_TOPAZ =(new Item(1755), new Item(1629), new CraftableItem(new Item(1613), new Item(1629), 16, 25.0))
RUBY =(new Item(1755), new Item(1619), new CraftableItem(new Item(1603), new Item(1619), 34, 85.0))
SAPPHIRE =(new Item(1755), new Item(1623), new CraftableItem(new Item(1607), new Item(1623), 20, 50.0))
ZENYTE =(new Item(1755), new Item(19496), new CraftableItem(new Item(19493), new Item(19496), 89, 200))
Private Attributes
final CraftableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 8 of file Gem.java.
Constructor & Destructor Documentation
Gem()
com.runehive.content.skill.impl.crafting.impl.Gem.Gem (Item use, Item with, CraftableItem... items)
Definition at line 25 of file Gem.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.crafting.impl.Gem.getAnimation ()
Gets the craftable animation.
Returns
The craftable animation.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 38 of file Gem.java.
{
        switch (this) {
        case OPAL:
        case JADE:
        default:
            return 891;
        case RED_TOPAZ:
            return 892;
        case SAPPHIRE:
            return 888;
        case EMERALD:
            return 889;
        case RUBY:
            return 887;
        case DIAMOND:
            return 890;
        case DRAGONSTONE:
            return 890;
        case ONYX:
            return 2717;
        }
    }
References DIAMOND, DRAGONSTONE, EMERALD, JADE, ONYX, OPAL, RED_TOPAZ, RUBY, and SAPPHIRE.
getCraftableItems()
CraftableItem[] com.runehive.content.skill.impl.crafting.impl.Gem.getCraftableItems ()
Gets the craftable items.
Returns
The craftable items.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 72 of file Gem.java.
{
        return items;
    }
References items.
getIngredients()
Item[] com.runehive.content.skill.impl.crafting.impl.Gem.getIngredients (int index)
Gets the craftable ingredients.
Parameters
index The ingredient index.
Returns
The craftable ingredients.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 82 of file Gem.java.
{
        return new Item[] { with };
    }
References with.
getName()
String com.runehive.content.skill.impl.crafting.impl.Gem.getName ()
Gets the craftable name.
Returns
The craftable name.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 87 of file Gem.java.
{
        return "Gem";
    }
getProductionMessage()
String com.runehive.content.skill.impl.crafting.impl.Gem.getProductionMessage ()
Gets the craftable production message.
Returns
The craftable production message.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 77 of file Gem.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.crafting.impl.Gem.getUse ()
Gets the craftable used item.
Returns
The craftable used item.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 62 of file Gem.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.crafting.impl.Gem.getWith ()
Gets the craftable item used with.
Returns
The craftable item used with.
Implements com.runehive.content.skill.impl.crafting.Craftable.
Definition at line 67 of file Gem.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.crafting.impl.Gem.load () static
Definition at line 31 of file Gem.java.
{
        for (Gem cuttable : values()) {
            Crafting.addCraftable(cuttable);
        }
    }
References com.runehive.content.skill.impl.crafting.Crafting.addCraftable(), and Gem().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
DIAMOND
com.runehive.content.skill.impl.crafting.impl.Gem.DIAMOND =(new Item(1755), new Item(1617), new CraftableItem(new Item(1601), new Item(1617), 43, 107.5))
Definition at line 15 of file Gem.java.
Referenced by getAnimation().
DRAGONSTONE
com.runehive.content.skill.impl.crafting.impl.Gem.DRAGONSTONE =(new Item(1755), new Item(1631), new CraftableItem(new Item(1615), new Item(1631), 55, 137.5))
Definition at line 16 of file Gem.java.
Referenced by getAnimation().
EMERALD
com.runehive.content.skill.impl.crafting.impl.Gem.EMERALD =(new Item(1755), new Item(1621), new CraftableItem(new Item(1605), new Item(1621), 27, 67.5))
Definition at line 13 of file Gem.java.
Referenced by getAnimation().
items
final CraftableItem [] com.runehive.content.skill.impl.crafting.impl.Gem.items private
Definition at line 23 of file Gem.java.
Referenced by Gem(), and getCraftableItems().
JADE
com.runehive.content.skill.impl.crafting.impl.Gem.JADE =(new Item(1755), new Item(1627), new CraftableItem(new Item(1611), new Item(1627), 13, 20.0))
Definition at line 10 of file Gem.java.
Referenced by getAnimation().
ONYX
com.runehive.content.skill.impl.crafting.impl.Gem.ONYX =(new Item(1755), new Item(6571), new CraftableItem(new Item(6573), new Item(6571), 67, 167.5))
Definition at line 17 of file Gem.java.
Referenced by getAnimation().
OPAL
com.runehive.content.skill.impl.crafting.impl.Gem.OPAL =(new Item(1755), new Item(1625), new CraftableItem(new Item(1609), new Item(1625), 1, 15.0))
Definition at line 9 of file Gem.java.
Referenced by getAnimation().
RED_TOPAZ
com.runehive.content.skill.impl.crafting.impl.Gem.RED_TOPAZ =(new Item(1755), new Item(1629), new CraftableItem(new Item(1613), new Item(1629), 16, 25.0))
Definition at line 11 of file Gem.java.
Referenced by getAnimation().
RUBY
com.runehive.content.skill.impl.crafting.impl.Gem.RUBY =(new Item(1755), new Item(1619), new CraftableItem(new Item(1603), new Item(1619), 34, 85.0))
Definition at line 14 of file Gem.java.
Referenced by getAnimation().
SAPPHIRE
com.runehive.content.skill.impl.crafting.impl.Gem.SAPPHIRE =(new Item(1755), new Item(1623), new CraftableItem(new Item(1607), new Item(1623), 20, 50.0))
Definition at line 12 of file Gem.java.
Referenced by getAnimation().
use
final Item com.runehive.content.skill.impl.crafting.impl.Gem.use private
Definition at line 21 of file Gem.java.
Referenced by Gem(), and getUse().
with
final Item com.runehive.content.skill.impl.crafting.impl.Gem.with private
Definition at line 22 of file Gem.java.
Referenced by Gem(), getIngredients(), and getWith().
ZENYTE
com.runehive.content.skill.impl.crafting.impl.Gem.ZENYTE =(new Item(1755), new Item(19496), new CraftableItem(new Item(19493), new Item(19496), 89, 200))
Definition at line 18 of file Gem.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Gem.java