RuneHive-Game: com.runehive.content.skill.impl.runecrafting.RunecraftData Enum Reference
com.runehive.content.skill.impl.runecrafting.RunecraftData Enum Reference
Holds the runecrafting data -.
Public Member Functions
double getExperience ()
Gets the experience rewarded.
int getLevel ()
Gets the level required.
int[] getMultiplier ()
Gets the multiplier.
int getObject ()
Gets the object identification.
int getRunes ()
Gets the runes obtained.
RunecraftData (int object, int runes, double experience, int[] multiplier)
The runecrafting data.
Static Public Member Functions
static Optional< RunecraftData > forId (int id)
Gets the runecrafting data based on the object.
Public Attributes
AIR =(34760, 556, 6.0D, new int[] { 1, 11, 22, 33, 44, 55, 66, 77, 88, 99 })
ASTRAL =(34771, 9075, 21.5D, new int[] { 82 })
BLOOD =(27978, 565, 12.5D, new int[] { 77 })
BODY =(34765, 559, 8.5D, new int[] { 20, 46, 92 })
CHAOS =(34769, 562, 10.5D, new int[] { 35, 74 })
COSMIC =(34766, 564, 10.0D, new int[] { 27, 59 })
DEATH =(34770, 560, 12.0D, new int[] { 65 })
EARTH =(34763, 557, 7.5D, new int[] { 9, 26, 52, 78 })
FIRE =(34764, 554, 8.0D, new int[] { 14, 35, 70 })
LAW =(34767, 563, 10.5D, new int[] { 54 })
MIND =(34761, 558, 6.5D, new int[] { 1, 14, 28, 42, 56, 70, 84, 98 })
NATURE =(34768, 561, 11.0D, new int[] { 44, 91 })
OURNIA =(29631, -1, -1, new int[] { 55 })
SOUL =(27980, 566, 29.7, new int[] { 90 })
WARTH =(34772, 21880, 52.5D, new int[] { 95 })
WATER =(34762, 555, 7.0D, new int[] { 5, 19, 38, 57, 76, 95 })
Private Attributes
final double experience
The experience rewarded.
final int[] multiplier
The multiplier.
final int object
The object identification.
final int runes
The runes obtained.
Detailed Description
Holds the runecrafting data -.
Author
Daniel
Definition at line 7 of file RunecraftData.java.
Constructor & Destructor Documentation
RunecraftData()
com.runehive.content.skill.impl.runecrafting.RunecraftData.RunecraftData (int object, int runes, double experience, int[] multiplier)
The runecrafting data.
Definition at line 38 of file RunecraftData.java.
{
        this.object = object;
        this.runes = runes;
        this.experience = experience;
        this.multiplier = multiplier;
    }
References experience, multiplier, object, and runes.
Member Function Documentation
forId()
Optional< RunecraftData > com.runehive.content.skill.impl.runecrafting.RunecraftData.forId (int id) static
Gets the runecrafting data based on the object.
Definition at line 71 of file RunecraftData.java.
{
        return Arrays.stream(values()).filter(a -> a.object == id).findAny();
    }
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject().
getExperience()
double com.runehive.content.skill.impl.runecrafting.RunecraftData.getExperience ()
Gets the experience rewarded.
Definition at line 66 of file RunecraftData.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), and com.runehive.content.skill.impl.runecrafting.Runecraft.craft().
getLevel()
int com.runehive.content.skill.impl.runecrafting.RunecraftData.getLevel ()
Gets the level required.
Definition at line 51 of file RunecraftData.java.
{
        return multiplier[0];
    }
References multiplier.
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject(), and com.runehive.content.skill.impl.runecrafting.Runecraft.craft().
getMultiplier()
int[] com.runehive.content.skill.impl.runecrafting.RunecraftData.getMultiplier ()
Gets the multiplier.
Definition at line 56 of file RunecraftData.java.
{
        return multiplier;
    }
References multiplier.
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.multiplier().
getObject()
int com.runehive.content.skill.impl.runecrafting.RunecraftData.getObject ()
Gets the object identification.
Definition at line 46 of file RunecraftData.java.
{
        return object;
    }
References object.
getRunes()
int com.runehive.content.skill.impl.runecrafting.RunecraftData.getRunes ()
Gets the runes obtained.
Definition at line 61 of file RunecraftData.java.
{
        return runes;
    }
References runes.
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject().
Member Data Documentation
AIR
com.runehive.content.skill.impl.runecrafting.RunecraftData.AIR =(34760, 556, 6.0D, new int[] { 1, 11, 22, 33, 44, 55, 66, 77, 88, 99 })
Definition at line 8 of file RunecraftData.java.
ASTRAL
com.runehive.content.skill.impl.runecrafting.RunecraftData.ASTRAL =(34771, 9075, 21.5D, new int[] { 82 })
Definition at line 20 of file RunecraftData.java.
BLOOD
com.runehive.content.skill.impl.runecrafting.RunecraftData.BLOOD =(27978, 565, 12.5D, new int[] { 77 })
Definition at line 19 of file RunecraftData.java.
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.craft().
BODY
com.runehive.content.skill.impl.runecrafting.RunecraftData.BODY =(34765, 559, 8.5D, new int[] { 20, 46, 92 })
Definition at line 13 of file RunecraftData.java.
CHAOS
com.runehive.content.skill.impl.runecrafting.RunecraftData.CHAOS =(34769, 562, 10.5D, new int[] { 35, 74 })
Definition at line 15 of file RunecraftData.java.
COSMIC
com.runehive.content.skill.impl.runecrafting.RunecraftData.COSMIC =(34766, 564, 10.0D, new int[] { 27, 59 })
Definition at line 14 of file RunecraftData.java.
DEATH
com.runehive.content.skill.impl.runecrafting.RunecraftData.DEATH =(34770, 560, 12.0D, new int[] { 65 })
Definition at line 18 of file RunecraftData.java.
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.craft().
EARTH
com.runehive.content.skill.impl.runecrafting.RunecraftData.EARTH =(34763, 557, 7.5D, new int[] { 9, 26, 52, 78 })
Definition at line 11 of file RunecraftData.java.
experience
final double com.runehive.content.skill.impl.runecrafting.RunecraftData.experience private
The experience rewarded.
Definition at line 32 of file RunecraftData.java.
Referenced by getExperience(), and RunecraftData().
FIRE
com.runehive.content.skill.impl.runecrafting.RunecraftData.FIRE =(34764, 554, 8.0D, new int[] { 14, 35, 70 })
Definition at line 12 of file RunecraftData.java.
LAW
com.runehive.content.skill.impl.runecrafting.RunecraftData.LAW =(34767, 563, 10.5D, new int[] { 54 })
Definition at line 17 of file RunecraftData.java.
MIND
com.runehive.content.skill.impl.runecrafting.RunecraftData.MIND =(34761, 558, 6.5D, new int[] { 1, 14, 28, 42, 56, 70, 84, 98 })
Definition at line 9 of file RunecraftData.java.
multiplier
final int [] com.runehive.content.skill.impl.runecrafting.RunecraftData.multiplier private
The multiplier.
Definition at line 35 of file RunecraftData.java.
Referenced by getLevel(), getMultiplier(), and RunecraftData().
NATURE
com.runehive.content.skill.impl.runecrafting.RunecraftData.NATURE =(34768, 561, 11.0D, new int[] { 44, 91 })
Definition at line 16 of file RunecraftData.java.
object
final int com.runehive.content.skill.impl.runecrafting.RunecraftData.object private
The object identification.
Definition at line 26 of file RunecraftData.java.
Referenced by getObject(), and RunecraftData().
OURNIA
com.runehive.content.skill.impl.runecrafting.RunecraftData.OURNIA =(29631, -1, -1, new int[] { 55 })
Definition at line 23 of file RunecraftData.java.
Referenced by com.runehive.content.skill.impl.runecrafting.Runecraft.clickObject().
runes
final int com.runehive.content.skill.impl.runecrafting.RunecraftData.runes private
The runes obtained.
Definition at line 29 of file RunecraftData.java.
Referenced by getRunes(), and RunecraftData().
SOUL
com.runehive.content.skill.impl.runecrafting.RunecraftData.SOUL =(27980, 566, 29.7, new int[] { 90 })
Definition at line 21 of file RunecraftData.java.
WARTH
com.runehive.content.skill.impl.runecrafting.RunecraftData.WARTH =(34772, 21880, 52.5D, new int[] { 95 })
Definition at line 22 of file RunecraftData.java.
WATER
com.runehive.content.skill.impl.runecrafting.RunecraftData.WATER =(34762, 555, 7.0D, new int[] { 5, 19, 38, 57, 76, 95 })
Definition at line 10 of file RunecraftData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/runecrafting/RunecraftData.java