RuneHive-Game: com.runehive.util.MessageColor Enum Reference
com.runehive.util.MessageColor Enum Reference
Holds an enum of colors for ease.
Public Member Functions
String getColor ()
Gets the color.
MessageColor (String color)
Public Attributes
BLACK =("000000")
BLUE =("1944BD")
BRONZE =("7E3200")
DARK_BLUE =("11558C")
DARK_GREEN =("118C21")
DARK_ORANGE =("D47A19")
DARK_PURPLE =("9415C2")
DARK_RED =("A11A1A")
DEVELOPER =("C93443")
GREEN =("1ADB34")
GREY =("736D6D")
LIGHT_BLUE =("0DA6D9")
LIGHT_GREEN =("34ED4D")
LIGHT_ORANGE =("FFA340")
LIGHT_PURPLE =("CD45FF")
LIGHT_RED =("E33653")
ORANGE =("FF8400")
PURPLE =("7F007F")
RED =("FF0000")
WHITE =("FFFFFF")
Private Attributes
final String color
Detailed Description
Holds an enum of colors for ease.
Author
Daniel
Definition at line 8 of file MessageColor.java.
Constructor & Destructor Documentation
MessageColor()
com.runehive.util.MessageColor.MessageColor (String color)
Definition at line 48 of file MessageColor.java.
{
        this.color = color;
    }
References color.
Member Function Documentation
getColor()
String com.runehive.util.MessageColor.getColor ()
Gets the color.
Returns
The color.
Definition at line 56 of file MessageColor.java.
{ return color; }
References color.
Referenced by com.runehive.net.packet.out.SendMessage.SendMessage().
Member Data Documentation
BLACK
com.runehive.util.MessageColor.BLACK =("000000")
Definition at line 13 of file MessageColor.java.
Referenced by com.runehive.net.packet.out.SendMessage.SendMessage(), com.runehive.net.packet.out.SendMessage.SendMessage(), and com.runehive.net.packet.out.SendMessage.SendMessage().
BLUE
com.runehive.util.MessageColor.BLUE =("1944BD")
Definition at line 38 of file MessageColor.java.
Referenced by com.runehive.game.world.items.containers.bank.BankPin.enter(), com.runehive.game.world.items.containers.bank.BankPin.remove(), and com.runehive.game.world.items.containers.bank.BankPin.set().
BRONZE
com.runehive.util.MessageColor.BRONZE =("7E3200")
Definition at line 43 of file MessageColor.java.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onRequest().
color
final String com.runehive.util.MessageColor.color private
Definition at line 46 of file MessageColor.java.
Referenced by getColor(), and MessageColor().
DARK_BLUE
com.runehive.util.MessageColor.DARK_BLUE =("11558C")
Definition at line 40 of file MessageColor.java.
Referenced by com.runehive.content.prestige.Prestige.activatePerk(), and com.runehive.game.world.items.containers.bank.BankVault.add().
DARK_GREEN
com.runehive.util.MessageColor.DARK_GREEN =("118C21")
Definition at line 30 of file MessageColor.java.
Referenced by com.runehive.content.RoyaltyProgram.append(), com.runehive.content.skill.impl.construction.House.enter(), com.runehive.content.skill.impl.construction.House.enter(), and com.runehive.content.store.impl.PersonalStore.onPurchase().
DARK_ORANGE
com.runehive.util.MessageColor.DARK_ORANGE =("D47A19")
Definition at line 35 of file MessageColor.java.
DARK_PURPLE
com.runehive.util.MessageColor.DARK_PURPLE =("9415C2")
Definition at line 25 of file MessageColor.java.
DARK_RED
com.runehive.util.MessageColor.DARK_RED =("A11A1A")
Definition at line 20 of file MessageColor.java.
Referenced by com.runehive.game.world.items.containers.bank.BankVault.deposit(), com.runehive.game.action.impl.DebugAction.execute(), and com.runehive.game.world.items.containers.bank.BankVault.value().
DEVELOPER
com.runehive.util.MessageColor.DEVELOPER =("C93443")
Definition at line 10 of file MessageColor.java.
Referenced by com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnGround(), com.runehive.net.packet.in.ColorPacketListener.handlePacket(), com.runehive.net.packet.in.RegionChangePacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), and com.runehive.game.world.entity.mob.player.Player.loadRegion().
GREEN
com.runehive.util.MessageColor.GREEN =("1ADB34")
Definition at line 28 of file MessageColor.java.
GREY
com.runehive.util.MessageColor.GREY =("736D6D")
Definition at line 15 of file MessageColor.java.
LIGHT_BLUE
com.runehive.util.MessageColor.LIGHT_BLUE =("0DA6D9")
Definition at line 39 of file MessageColor.java.
LIGHT_GREEN
com.runehive.util.MessageColor.LIGHT_GREEN =("34ED4D")
Definition at line 29 of file MessageColor.java.
LIGHT_ORANGE
com.runehive.util.MessageColor.LIGHT_ORANGE =("FFA340")
Definition at line 34 of file MessageColor.java.
LIGHT_PURPLE
com.runehive.util.MessageColor.LIGHT_PURPLE =("CD45FF")
Definition at line 24 of file MessageColor.java.
LIGHT_RED
com.runehive.util.MessageColor.LIGHT_RED =("E33653")
Definition at line 19 of file MessageColor.java.
Referenced by com.runehive.game.world.entity.combat.magic.Autocast.setAutocast().
ORANGE
com.runehive.util.MessageColor.ORANGE =("FF8400")
Definition at line 33 of file MessageColor.java.
PURPLE
com.runehive.util.MessageColor.PURPLE =("7F007F")
Definition at line 23 of file MessageColor.java.
Referenced by com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onRequest().
RED
com.runehive.util.MessageColor.RED =("FF0000")
Definition at line 18 of file MessageColor.java.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.accept(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.accept(), com.runehive.game.action.impl.DoorAction.canSchedule(), com.runehive.game.action.impl.LadderAction.canSchedule(), com.runehive.game.action.impl.LeverAction.canSchedule(), com.runehive.game.world.items.containers.bank.BankVault.deposit(), com.runehive.content.skill.impl.woodcutting.BirdsNest.drop(), com.runehive.content.store.impl.PersonalStore.itemContainerAction(), com.runehive.content.pet.Pets.onObtain(), com.runehive.game.world.items.containers.bank.BankPin.remove(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSessionManager.reset(), com.runehive.game.world.items.containers.bank.BankPin.set(), and com.runehive.game.world.items.containers.bank.BankVault.withdraw().
WHITE
com.runehive.util.MessageColor.WHITE =("FFFFFF")
Definition at line 14 of file MessageColor.java.
The documentation for this enum was generated from the following file:
java/com/runehive/util/MessageColor.java