RuneHive-Game: com.runehive.content.clanchannel.content.ClanAchievement Enum Reference
com.runehive.content.clanchannel.content.ClanAchievement Enum Reference
Handles the clan achievements.
Public Member Functions
ClanAchievement (String details, int amount, Difficulty difficulty)
Constructs a new ClanAchievement.
double getExperience ()
Gets the reward experience for completing an achivement.
int getPoints ()
Gets the reward points for completing an achievement.
Static Public Member Functions
static Optional< ClanAchievement > forOrdinal (int ordinal)
Gets the clan achivement based on the ordinal.
Public Attributes
final int amount
The amount required of the achievement.
CLAN_MEMBERS_I =("Have 10 members in your clan", 10, Difficulty.EASY)
CLAN_MEMBERS_II =("Have 50 members in your clan", 50, Difficulty.MEDIUM)
CLAN_MEMBERS_III =("Have 150 members in your clan", 150, Difficulty.HARD)
final String details
The details of the achievement.
final Difficulty difficulty
The difficulty of the achievement.
PLAYER_KILLER_I =("Kill 25 wilderness players", 25, Difficulty.EASY)
PLAYER_KILLER_II =("Kill 150 wilderness players", 150, Difficulty.MEDIUM)
PLAYER_KILLER_III =("Kill 750 wilderness players", 750, Difficulty.HARD)
TASKS_I =("Complete 10 clan tasks", 10, Difficulty.EASY)
TASKS_II =("Complete 100 clan tasks", 100, Difficulty.MEDIUM)
TASKS_III =("Complete 500 clan tasks", 500, Difficulty.HARD)
Detailed Description
Handles the clan achievements.
Author
Daniel.
Definition at line 12 of file ClanAchievement.java.
Constructor & Destructor Documentation
ClanAchievement()
com.runehive.content.clanchannel.content.ClanAchievement.ClanAchievement (String details, int amount, Difficulty difficulty)
Constructs a new ClanAchievement.
Definition at line 39 of file ClanAchievement.java.
{
        this.details = details;
        this.amount = amount;
        this.difficulty = difficulty;
    }
References amount, details, and difficulty.
Referenced by forOrdinal().
Member Function Documentation
forOrdinal()
Optional< ClanAchievement > com.runehive.content.clanchannel.content.ClanAchievement.forOrdinal (int ordinal) static
Gets the clan achivement based on the ordinal.
Definition at line 72 of file ClanAchievement.java.
{
        for (ClanAchievement achievement : values()) {
            if (achievement.ordinal() == ordinal)
                return Optional.of(achievement);
        }
        return Optional.empty();
    }
References ClanAchievement().
Referenced by com.runehive.content.clanchannel.content.ClanViewer.viewAchievements().
getExperience()
double com.runehive.content.clanchannel.content.ClanAchievement.getExperience ()
Gets the reward experience for completing an achivement.
Definition at line 59 of file ClanAchievement.java.
{
        switch (difficulty) {
            case EASY:
                return 2500;
            case MEDIUM:
                return 5000;
            case HARD:
                return 10000;
        }
        return 0;
    }
References difficulty.
getPoints()
int com.runehive.content.clanchannel.content.ClanAchievement.getPoints ()
Gets the reward points for completing an achievement.
Definition at line 46 of file ClanAchievement.java.
{
        switch (difficulty) {
            case EASY:
                return 3;
            case MEDIUM:
                return 5;
            case HARD:
                return 8;
        }
        return 0;
    }
References difficulty.
Member Data Documentation
amount
final int com.runehive.content.clanchannel.content.ClanAchievement.amount
The amount required of the achievement.
Definition at line 33 of file ClanAchievement.java.
Referenced by ClanAchievement().
CLAN_MEMBERS_I
com.runehive.content.clanchannel.content.ClanAchievement.CLAN_MEMBERS_I =("Have 10 members in your clan", 10, Difficulty.EASY)
Definition at line 14 of file ClanAchievement.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.add().
CLAN_MEMBERS_II
com.runehive.content.clanchannel.content.ClanAchievement.CLAN_MEMBERS_II =("Have 50 members in your clan", 50, Difficulty.MEDIUM)
Definition at line 19 of file ClanAchievement.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.add().
CLAN_MEMBERS_III
com.runehive.content.clanchannel.content.ClanAchievement.CLAN_MEMBERS_III =("Have 150 members in your clan", 150, Difficulty.HARD)
Definition at line 24 of file ClanAchievement.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.add().
details
final String com.runehive.content.clanchannel.content.ClanAchievement.details
The details of the achievement.
Definition at line 30 of file ClanAchievement.java.
Referenced by ClanAchievement().
difficulty
final Difficulty com.runehive.content.clanchannel.content.ClanAchievement.difficulty
The difficulty of the achievement.
Definition at line 36 of file ClanAchievement.java.
Referenced by ClanAchievement(), getExperience(), and getPoints().
PLAYER_KILLER_I
com.runehive.content.clanchannel.content.ClanAchievement.PLAYER_KILLER_I =("Kill 25 wilderness players", 25, Difficulty.EASY)
Definition at line 16 of file ClanAchievement.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerKilling.handle().
PLAYER_KILLER_II
com.runehive.content.clanchannel.content.ClanAchievement.PLAYER_KILLER_II =("Kill 150 wilderness players", 150, Difficulty.MEDIUM)
Definition at line 21 of file ClanAchievement.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerKilling.handle().
PLAYER_KILLER_III
com.runehive.content.clanchannel.content.ClanAchievement.PLAYER_KILLER_III =("Kill 750 wilderness players", 750, Difficulty.HARD)
Definition at line 26 of file ClanAchievement.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerKilling.handle().
TASKS_I
com.runehive.content.clanchannel.content.ClanAchievement.TASKS_I =("Complete 10 clan tasks", 10, Difficulty.EASY)
Definition at line 15 of file ClanAchievement.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask().
TASKS_II
com.runehive.content.clanchannel.content.ClanAchievement.TASKS_II =("Complete 100 clan tasks", 100, Difficulty.MEDIUM)
Definition at line 20 of file ClanAchievement.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask().
TASKS_III
com.runehive.content.clanchannel.content.ClanAchievement.TASKS_III =("Complete 500 clan tasks", 500, Difficulty.HARD)
Definition at line 25 of file ClanAchievement.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask().
The documentation for this enum was generated from the following file:
java/com/runehive/content/clanchannel/content/ClanAchievement.java