RuneHive-Game: com.runehive.content.skill.impl.fletching.impl.Bolt Enum Reference
com.runehive.content.skill.impl.fletching.impl.Bolt Enum Reference
Public Member Functions
Bolt (Item use, Item with, FletchableItem... items)
int getAnimation ()
FletchableItem[] getFletchableItems ()
int getGraphics ()
Item[] getIngredients ()
String getProductionMessage ()
Item getUse ()
Item getWith ()
Static Public Member Functions
static void load ()
Public Attributes
AMETHYST_BOLT =(new Item(Items.BROAD_BOLTS, 10), new Item(Items.AMETHYST_BOLT_TIPS, 10), new FletchableItem(new Item(Items.AMETHYST_BROAD_BOLTS, 10), 76, 10.6))
DIAMOND_BOLT =(new Item(9143, 10), new Item(9192, 10), new FletchableItem(new Item(9340, 10), 65, 7.0))
DRAGONSTONE_BOLT =(new Item(9144, 10), new Item(9193, 10), new FletchableItem(new Item(9341, 10), 71, 8.2))
EMERALD_BOLT =(new Item(9142, 10), new Item(9190, 10), new FletchableItem(new Item(9338, 10), 58, 5.5))
ONYX_BOLT =(new Item(9144, 10), new Item(9194, 10), new FletchableItem(new Item(9342, 10), 73, 9.4))
OPAL_BOLT =(new Item(877, 10), new Item(45, 10), new FletchableItem(new Item(879, 10), 11, 1.6))
PEARL_BOLT =(new Item(9140, 10), new Item(46, 10), new FletchableItem(new Item(880, 10), 41, 3.2))
RED_TOPAZ_BOLT =(new Item(9141, 10), new Item(9188, 10), new FletchableItem(new Item(9336, 10), 48, 3.9))
RUBY_BOLT =(new Item(9143, 10), new Item(9191, 10), new FletchableItem(new Item(9339, 10), 63, 6.3))
SAPPHIRE_BOLT =(new Item(9142, 10), new Item(9189, 10), new FletchableItem(new Item(9337, 10), 56, 4.7))
Private Attributes
final FletchableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 9 of file Bolt.java.
Constructor & Destructor Documentation
Bolt()
com.runehive.content.skill.impl.fletching.impl.Bolt.Bolt (Item use, Item with, FletchableItem... items)
Definition at line 25 of file Bolt.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.fletching.impl.Bolt.getAnimation ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 38 of file Bolt.java.
{
        switch (this) {
            case OPAL_BOLT:
                return 8472;
            case PEARL_BOLT:
                return 8473;
            case RED_TOPAZ_BOLT:
                return 8475;
            case SAPPHIRE_BOLT:
            case EMERALD_BOLT:
                return 8476;
            case RUBY_BOLT:
            case DIAMOND_BOLT:
                return 8477;
            case DRAGONSTONE_BOLT:
            case ONYX_BOLT:
            default:
                return 8478;
        }
    }
References DIAMOND_BOLT, DRAGONSTONE_BOLT, EMERALD_BOLT, ONYX_BOLT, OPAL_BOLT, PEARL_BOLT, RED_TOPAZ_BOLT, RUBY_BOLT, and SAPPHIRE_BOLT.
getFletchableItems()
FletchableItem[] com.runehive.content.skill.impl.fletching.impl.Bolt.getFletchableItems ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 75 of file Bolt.java.
{
        return items;
    }
References items.
getGraphics()
int com.runehive.content.skill.impl.fletching.impl.Bolt.getGraphics ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 60 of file Bolt.java.
{
        return -1;
    }
getIngredients()
Item[] com.runehive.content.skill.impl.fletching.impl.Bolt.getIngredients ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 85 of file Bolt.java.
{
        return new Item[] { use, with };
    }
References use, and with.
getProductionMessage()
String com.runehive.content.skill.impl.fletching.impl.Bolt.getProductionMessage ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 80 of file Bolt.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.fletching.impl.Bolt.getUse ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 65 of file Bolt.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.fletching.impl.Bolt.getWith ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 70 of file Bolt.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.fletching.impl.Bolt.load () static
Definition at line 31 of file Bolt.java.
{
        for (Bolt cuttable : values()) {
            Fletching.addFletchable(cuttable);
        }
    }
References com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), and Bolt().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
AMETHYST_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.AMETHYST_BOLT =(new Item(Items.BROAD_BOLTS, 10), new Item(Items.AMETHYST_BOLT_TIPS, 10), new FletchableItem(new Item(Items.AMETHYST_BROAD_BOLTS, 10), 76, 10.6))
Definition at line 18 of file Bolt.java.
DIAMOND_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.DIAMOND_BOLT =(new Item(9143, 10), new Item(9192, 10), new FletchableItem(new Item(9340, 10), 65, 7.0))
Definition at line 16 of file Bolt.java.
Referenced by getAnimation().
DRAGONSTONE_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.DRAGONSTONE_BOLT =(new Item(9144, 10), new Item(9193, 10), new FletchableItem(new Item(9341, 10), 71, 8.2))
Definition at line 17 of file Bolt.java.
Referenced by getAnimation().
EMERALD_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.EMERALD_BOLT =(new Item(9142, 10), new Item(9190, 10), new FletchableItem(new Item(9338, 10), 58, 5.5))
Definition at line 14 of file Bolt.java.
Referenced by getAnimation().
items
final FletchableItem [] com.runehive.content.skill.impl.fletching.impl.Bolt.items private
Definition at line 23 of file Bolt.java.
Referenced by Bolt(), and getFletchableItems().
ONYX_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.ONYX_BOLT =(new Item(9144, 10), new Item(9194, 10), new FletchableItem(new Item(9342, 10), 73, 9.4))
Definition at line 19 of file Bolt.java.
Referenced by getAnimation().
OPAL_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.OPAL_BOLT =(new Item(877, 10), new Item(45, 10), new FletchableItem(new Item(879, 10), 11, 1.6))
Definition at line 10 of file Bolt.java.
Referenced by getAnimation().
PEARL_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.PEARL_BOLT =(new Item(9140, 10), new Item(46, 10), new FletchableItem(new Item(880, 10), 41, 3.2))
Definition at line 11 of file Bolt.java.
Referenced by getAnimation().
RED_TOPAZ_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.RED_TOPAZ_BOLT =(new Item(9141, 10), new Item(9188, 10), new FletchableItem(new Item(9336, 10), 48, 3.9))
Definition at line 12 of file Bolt.java.
Referenced by getAnimation().
RUBY_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.RUBY_BOLT =(new Item(9143, 10), new Item(9191, 10), new FletchableItem(new Item(9339, 10), 63, 6.3))
Definition at line 15 of file Bolt.java.
Referenced by getAnimation().
SAPPHIRE_BOLT
com.runehive.content.skill.impl.fletching.impl.Bolt.SAPPHIRE_BOLT =(new Item(9142, 10), new Item(9189, 10), new FletchableItem(new Item(9337, 10), 56, 4.7))
Definition at line 13 of file Bolt.java.
Referenced by getAnimation().
use
final Item com.runehive.content.skill.impl.fletching.impl.Bolt.use private
Definition at line 21 of file Bolt.java.
Referenced by Bolt(), getIngredients(), and getUse().
with
final Item com.runehive.content.skill.impl.fletching.impl.Bolt.with private
Definition at line 22 of file Bolt.java.
Referenced by Bolt(), getIngredients(), and getWith().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fletching/impl/Bolt.java