RuneHive-Game: com.runehive.game.world.entity.combat.magic.MagicRune Enum Reference
com.runehive.game.world.entity.combat.magic.MagicRune Enum Reference
Public Member Functions
boolean containsCombo (ItemContainer container, int amount)
int[] getCombos ()
int getMainId ()
int[] getStaffs ()
boolean isStaff (int id)
MagicRune (int mainId, int[] combos, int[] staffs)
Static Public Member Functions
static MagicRune forMainId (int id)
static boolean hasRunes (Player player, Item[] required)
static boolean hasRunes (Player player, RequiredRune[] runes)
static void remove (Player player, Item[] required)
static void remove (Player player, RequiredRune[] runes)
Public Attributes
AIR_RUNE =(556, new int[]{4695, 4696, 4697}, new int[]{1381, 1397, 1405, 11998, 12000, 20730, 20733, 20736, 20739})
ASTRAL_RUNE =(9075, null, null)
BLOOD_RUNE =(565, null, null)
BODY_RUNE =(559, null, null)
CHAOS_RUNE =(562, null, null)
COSMIC_RUNE =(564, null, null)
DEATH_RUNE =(560, null, null)
EARTH_RUNE =(557, new int[]{4698, 4696, 4699}, new int[]{3053, 3054, 1385, 1399, 1407, 6562, 6563, 20736, 20739})
FIRE_RUNE =(554, new int[]{4694, 4697, 4699}, new int[]{1387, 1393, 1401, 11998, 12000, 11787, 3053, 3054, 12795})
LAW_RUNE =(563, null, null)
MIND_RUNE =(558, null, null)
NATURE_RUNE =(561, null, null)
SOUL_RUNE =(566, null, null)
WATER_RUNE =(555, new int[]{4694, 4695, 4698}, new int[]{1383, 1395, 1403, 20730, 20733, 6562, 6563, 11787, 11789, 12795, 21006})
WRATH_RUNE =(21880, null, null)
Private Attributes
final int[] combos
final int mainId
final int[] staffs
Detailed Description
Definition at line 10 of file MagicRune.java.
Constructor & Destructor Documentation
MagicRune()
com.runehive.game.world.entity.combat.magic.MagicRune.MagicRune (int mainId, int[] combos, int[] staffs)
Definition at line 31 of file MagicRune.java.
{
        this.mainId = mainId;
        this.combos = combos;
        this.staffs = staffs;
    }
References combos, mainId, and staffs.
Referenced by forMainId(), hasRunes(), and remove().
Member Function Documentation
containsCombo()
boolean com.runehive.game.world.entity.combat.magic.MagicRune.containsCombo (ItemContainer container, int amount)
Definition at line 67 of file MagicRune.java.
{
        if (combos == null) return false;
        for (int combo : combos) {
            if (container.contains(combo, amount)) {
                return true;
            }
        }
        return false;
    }
References combos, and com.runehive.game.world.items.containers.ItemContainer.contains().
Referenced by hasRunes(), and remove().
forMainId()
MagicRune com.runehive.game.world.entity.combat.magic.MagicRune.forMainId (int id) static
Definition at line 49 of file MagicRune.java.
{
        for (MagicRune rune : values()) {
            if (rune.mainId == id)
                return rune;
        }
        return null;
    }
References MagicRune().
Referenced by hasRunes(), and remove().
getCombos()
int[] com.runehive.game.world.entity.combat.magic.MagicRune.getCombos ()
Definition at line 41 of file MagicRune.java.
{
        return combos;
    }
References combos.
getMainId()
int com.runehive.game.world.entity.combat.magic.MagicRune.getMainId ()
Definition at line 37 of file MagicRune.java.
{
        return mainId;
    }
References mainId.
getStaffs()
int[] com.runehive.game.world.entity.combat.magic.MagicRune.getStaffs ()
Definition at line 45 of file MagicRune.java.
{
        return staffs;
    }
References staffs.
hasRunes() [1/2]
boolean com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes (Player player, Item[] required) static
Definition at line 77 of file MagicRune.java.
{
        Item wepon = player.equipment.getWeapon();
        for (Item item : required) {
            MagicRune rune = forMainId(item.getId());
            if (rune == null)
                continue;
            if (player.runePouch.contains(item))
                continue;
            if (wepon != null && rune.isStaff(wepon.getId()))
                continue;
            if (player.inventory.contains(rune.mainId, item.getAmount()))
                continue;
            if (rune.containsCombo(player.inventory, item.getAmount()))
                continue;
            /* does not have runes */
            return false;
        }
        return true;
    }
References com.runehive.content.skill.impl.magic.RunePouch.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), containsCombo(), com.runehive.game.world.entity.mob.player.Player.equipment, forMainId(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.containers.equipment.Equipment.getWeapon(), com.runehive.game.world.entity.mob.player.Player.inventory, isStaff(), MagicRune(), mainId, and com.runehive.game.world.entity.mob.player.Player.runePouch.
Referenced by com.runehive.game.world.entity.combat.magic.MagicSpell.canCast(), com.runehive.content.skill.impl.magic.spell.SpellCasting.cast(), com.runehive.content.skill.impl.magic.spell.SpellCasting.cast(), hasRunes(), and com.runehive.game.world.entity.combat.magic.Autocast.setAutocast().
hasRunes() [2/2]
boolean com.runehive.game.world.entity.combat.magic.MagicRune.hasRunes (Player player, RequiredRune[] runes) static
Definition at line 140 of file MagicRune.java.
{
        List<Item> required = new LinkedList<>();
        for (RequiredRune rune : runes) {
            required.add(new Item(rune.getMainId(), rune.getAmount()));
        }
        return hasRunes(player, required.toArray(new Item[required.size()]));
    }
References hasRunes().
isStaff()
boolean com.runehive.game.world.entity.combat.magic.MagicRune.isStaff (int id)
Definition at line 57 of file MagicRune.java.
{
        if (staffs == null) return false;
        for (int staff : staffs) {
            if (staff == id) {
                return true;
            }
        }
        return false;
    }
References staffs.
Referenced by hasRunes(), and remove().
remove() [1/2]
void com.runehive.game.world.entity.combat.magic.MagicRune.remove (Player player, Item[] required) static
Definition at line 103 of file MagicRune.java.
{
        Item wepon = player.equipment.getWeapon();
        boolean refresh = false;
        player.inventory.setFiringEvents(false);
        for (Item item : required) {
            MagicRune rune = forMainId(item.getId());
            if (rune == null)
                continue;
            if (wepon != null && rune.isStaff(wepon.getId()))
                continue;
            if (player.runePouch.contains(item)) {
                player.runePouch.remove(item);
                continue;
            }
            if (player.inventory.contains(rune.mainId, item.getAmount())) {
                refresh |= player.inventory.remove(rune.mainId, item.getAmount());
                continue;
            }
            if (rune.combos != null && rune.containsCombo(player.inventory, item.getAmount())) {
                for (int combo : rune.combos) {
                    if (player.inventory.contains(combo, item.getAmount())) {
                        refresh |= player.inventory.remove(combo, item.getAmount());
                        break;
                    }
                }
            }
        }
        player.inventory.setFiringEvents(true);
        if (refresh) player.inventory.refresh();
    }
References combos, containsCombo(), forMainId(), com.runehive.game.world.items.Item.getId(), isStaff(), MagicRune(), and mainId.
Referenced by com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start().
remove() [2/2]
void com.runehive.game.world.entity.combat.magic.MagicRune.remove (Player player, RequiredRune[] runes) static
Definition at line 148 of file MagicRune.java.
{
        List<Item> required = new LinkedList<>();
        for (RequiredRune rune : runes) {
            required.add(new Item(rune.getMainId(), rune.getAmount()));
        }
        remove(player, required.toArray(new Item[required.size()]));
    }
Member Data Documentation
AIR_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.AIR_RUNE =(556, new int[]{4695, 4696, 4697}, new int[]{1381, 1397, 1405, 11998, 12000, 20730, 20733, 20736, 20739})
Definition at line 11 of file MagicRune.java.
ASTRAL_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.ASTRAL_RUNE =(9075, null, null)
Definition at line 24 of file MagicRune.java.
BLOOD_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.BLOOD_RUNE =(565, null, null)
Definition at line 22 of file MagicRune.java.
BODY_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.BODY_RUNE =(559, null, null)
Definition at line 16 of file MagicRune.java.
CHAOS_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.CHAOS_RUNE =(562, null, null)
Definition at line 19 of file MagicRune.java.
combos
final int [] com.runehive.game.world.entity.combat.magic.MagicRune.combos private
Definition at line 28 of file MagicRune.java.
Referenced by containsCombo(), getCombos(), MagicRune(), and remove().
COSMIC_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.COSMIC_RUNE =(564, null, null)
Definition at line 21 of file MagicRune.java.
DEATH_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.DEATH_RUNE =(560, null, null)
Definition at line 17 of file MagicRune.java.
EARTH_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.EARTH_RUNE =(557, new int[]{4698, 4696, 4699}, new int[]{3053, 3054, 1385, 1399, 1407, 6562, 6563, 20736, 20739})
Definition at line 14 of file MagicRune.java.
FIRE_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.FIRE_RUNE =(554, new int[]{4694, 4697, 4699}, new int[]{1387, 1393, 1401, 11998, 12000, 11787, 3053, 3054, 12795})
Definition at line 12 of file MagicRune.java.
LAW_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.LAW_RUNE =(563, null, null)
Definition at line 20 of file MagicRune.java.
mainId
final int com.runehive.game.world.entity.combat.magic.MagicRune.mainId private
Definition at line 27 of file MagicRune.java.
Referenced by getMainId(), hasRunes(), MagicRune(), and remove().
MIND_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.MIND_RUNE =(558, null, null)
Definition at line 15 of file MagicRune.java.
NATURE_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.NATURE_RUNE =(561, null, null)
Definition at line 18 of file MagicRune.java.
SOUL_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.SOUL_RUNE =(566, null, null)
Definition at line 23 of file MagicRune.java.
staffs
final int [] com.runehive.game.world.entity.combat.magic.MagicRune.staffs private
Definition at line 29 of file MagicRune.java.
Referenced by getStaffs(), isStaff(), and MagicRune().
WATER_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.WATER_RUNE =(555, new int[]{4694, 4695, 4698}, new int[]{1383, 1395, 1403, 20730, 20733, 6562, 6563, 11787, 11789, 12795, 21006})
Definition at line 13 of file MagicRune.java.
WRATH_RUNE
com.runehive.game.world.entity.combat.magic.MagicRune.WRATH_RUNE =(21880, null, null)
Definition at line 25 of file MagicRune.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/magic/MagicRune.java