RuneHive-Game: com.runehive.content.clanchannel.ClanType Enum Reference
com.runehive.content.clanchannel.ClanType Enum Reference
The different clan types.
Public Member Functions
ClanType (String name, int icon)
String getIcon ()
int getIconValue ()
String getName ()
Public Attributes
IRON_MAN =("Ironman", 18)
Clans that are focused on iron man accounts.
PVM =("PvM", 3)
Clans that are focused on PVM.
PVP =("PvP", 8)
Clans that are focused on PVP.
SKILLING =("Skilling", 5)
Clans that are focused on skilling.
SOCIAL =("Social", 20)
Clans that are focused on socialism.
Private Attributes
final int icon
final String name
Detailed Description
The different clan types.
Author
Daniel
Definition at line 8 of file ClanType.java.
Constructor & Destructor Documentation
ClanType()
com.runehive.content.clanchannel.ClanType.ClanType (String name, int icon)
Definition at line 27 of file ClanType.java.
{
        this.name = name;
        this.icon = icon;
    }
References icon, and name.
Member Function Documentation
getIcon()
String com.runehive.content.clanchannel.ClanType.getIcon ()
Definition at line 40 of file ClanType.java.
{
        return "<icon=" + getIconValue() + ">";
    }
References getIconValue().
getIconValue()
int com.runehive.content.clanchannel.ClanType.getIconValue ()
Definition at line 36 of file ClanType.java.
{
        return icon;
    }
References icon.
Referenced by getIcon().
getName()
String com.runehive.content.clanchannel.ClanType.getName ()
Definition at line 32 of file ClanType.java.
{
        return name;
    }
References name.
Member Data Documentation
icon
final int com.runehive.content.clanchannel.ClanType.icon private
Definition at line 25 of file ClanType.java.
Referenced by ClanType(), and getIconValue().
IRON_MAN
com.runehive.content.clanchannel.ClanType.IRON_MAN =("Ironman", 18)
Clans that are focused on iron man accounts.
Definition at line 22 of file ClanType.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.connect(), com.runehive.content.clanchannel.content.ClanTask.getAssignment(), and com.runehive.content.clanchannel.ClanRepository.getTopChanels().
name
final String com.runehive.content.clanchannel.ClanType.name private
Definition at line 24 of file ClanType.java.
Referenced by ClanType(), and getName().
PVM
com.runehive.content.clanchannel.ClanType.PVM =("PvM", 3)
Clans that are focused on PVM.
Definition at line 13 of file ClanType.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask(), com.runehive.content.clanchannel.content.ClanTask.getAssignment(), and com.runehive.content.clanchannel.ClanRepository.getTopChanels().
PVP
com.runehive.content.clanchannel.ClanType.PVP =("PvP", 8)
Clans that are focused on PVP.
Definition at line 10 of file ClanType.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.activateTask(), com.runehive.content.clanchannel.content.ClanTask.getAssignment(), and com.runehive.content.clanchannel.ClanRepository.getTopChanels().
SKILLING
com.runehive.content.clanchannel.ClanType.SKILLING =("Skilling", 5)
Clans that are focused on skilling.
Definition at line 16 of file ClanType.java.
Referenced by com.runehive.content.clanchannel.content.ClanTask.getAssignment(), and com.runehive.content.clanchannel.ClanRepository.getTopChanels().
SOCIAL
com.runehive.content.clanchannel.ClanType.SOCIAL =("Social", 20)
Clans that are focused on socialism.
Definition at line 19 of file ClanType.java.
Referenced by com.runehive.content.clanchannel.channel.ClanChannel.create(), and com.runehive.content.clanchannel.content.ClanTask.getAssignment().
The documentation for this enum was generated from the following file:
java/com/runehive/content/clanchannel/ClanType.java