RuneHive-Game: com.runehive.game.world.entity.combat.CombatType Enum Reference
com.runehive.game.world.entity.combat.CombatType Enum Reference
Public Member Functions
CombatType (FormulaModifier< Mob > formula, int hitsplatDelay)
FormulaModifier< Mob > getFormula ()
int getHitsplatDelay ()
boolean match (final CombatType type)
boolean match (final CombatType... types)
Public Attributes
final FormulaModifier< Mob > formula
MAGIC =(new MagicFormula(), 2)
MELEE =(new MeleeFormula(), 0)
RANGED =(new RangedFormula(), 1)
Private Attributes
final int hitsplatDelay
Detailed Description
Definition at line 8 of file CombatType.java.
Constructor & Destructor Documentation
CombatType()
com.runehive.game.world.entity.combat.CombatType.CombatType (FormulaModifier< Mob > formula, int hitsplatDelay)
Definition at line 17 of file CombatType.java.
{
        this.formula = formula;
        this.hitsplatDelay = hitsplatDelay;
    }
References formula, and hitsplatDelay.
Referenced by match(), and match().
Member Function Documentation
getFormula()
FormulaModifier< Mob > com.runehive.game.world.entity.combat.CombatType.getFormula ()
Definition at line 22 of file CombatType.java.
{
        return formula;
    }
References formula.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.DuelPanel.accuracy(), com.runehive.game.world.entity.combat.attack.FormulaFactory.getMaxHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.getModifiedMaxHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.isAccurate(), and com.runehive.game.world.entity.combat.attack.FormulaFactory.nextHit().
getHitsplatDelay()
int com.runehive.game.world.entity.combat.CombatType.getHitsplatDelay ()
Definition at line 26 of file CombatType.java.
{
        return hitsplatDelay;
    }
References hitsplatDelay.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.getHitsplatDelay().
match() [1/2]
boolean com.runehive.game.world.entity.combat.CombatType.match (final CombatType type)
Definition at line 30 of file CombatType.java.
{
        return equals(type);
    }
References CombatType().
Referenced by match().
match() [2/2]
boolean com.runehive.game.world.entity.combat.CombatType.match (final CombatType... types)
Definition at line 34 of file CombatType.java.
{
        for (final CombatType type : types) {
            if (match(type)) {
                return true;
            }
        }
        return false;
    }
References CombatType(), and match().
Member Data Documentation
formula
final FormulaModifier<Mob> com.runehive.game.world.entity.combat.CombatType.formula
Definition at line 15 of file CombatType.java.
Referenced by CombatType(), and getFormula().
hitsplatDelay
final int com.runehive.game.world.entity.combat.CombatType.hitsplatDelay private
Definition at line 13 of file CombatType.java.
Referenced by CombatType(), and getHitsplatDelay().
MAGIC
com.runehive.game.world.entity.combat.CombatType.MAGIC =(new MagicFormula(), 2)
Definition at line 11 of file CombatType.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.strategy.npc.NpcMagicStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.getCombatType(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getEquipmentBonus(), com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.PrayerDrain.getHits(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FireballAttack.getHits(), com.runehive.game.world.entity.combat.strategy.player.custom.DragonfireShieldStrategy.getHits(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getMagicDefenceLevelNpc(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getPrayerBonus(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hit(), com.runehive.game.world.entity.combat.magic.MagicImpact.hitEvent(), com.runehive.game.world.entity.combat.Combat< T extends Mob >.hitsplat(), com.runehive.game.world.entity.combat.attack.listener.item.OccultNecklaceListener.modifyDamage(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.elite.EliteKnightMagicListener.modifyDamage(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMagicHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMagicHit(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Magic.start().
MELEE
com.runehive.game.world.entity.combat.CombatType.MELEE =(new MeleeFormula(), 0)
Definition at line 9 of file CombatType.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.content.activity.impl.godwars.GodwarsListener.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlightKilisa.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.FlockleaderGeerin.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.WingmanSkree.canOtherAttack(), com.runehive.game.world.entity.combat.strategy.npc.NpcMeleeStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.custom.ScytheOfViturStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.getCombatType(), com.runehive.game.world.entity.combat.CombatUtil.getHitDelay(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.hit(), com.runehive.content.bot.botclass.impl.PureMelee.hit(), com.runehive.content.bot.botclass.impl.PureRangeMelee.hit(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.hit(), com.runehive.content.bot.botclass.impl.ZerkerMelee.hit(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.VoidKnightMeleeListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.VoidKnightMeleeListener.modifyStrengthLevel(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextMeleeHit(), and com.runehive.game.world.items.containers.equipment.Equipment.openInterface().
RANGED
com.runehive.game.world.entity.combat.CombatType.RANGED =(new RangedFormula(), 1)
Definition at line 10 of file CombatType.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), com.runehive.game.world.entity.combat.strategy.npc.NpcRangedStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.getCombatType(), com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.getCombatType(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getEffectiveRanged(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getGearAttackBonus(), com.runehive.game.world.entity.combat.attack.FormulaFactory.getModifiedMaxHit(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getRangeDefenceLevelNpc(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.ranged.RangedEffects.hitEvent(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.elite.EliteKnightRangedListener.modifyDamage(), com.runehive.game.world.entity.combat.attack.listener.other.prayer.RigourListener.modifyDamage(), com.runehive.game.world.entity.combat.attack.listener.item.voidknight.elite.EliteKnightRangedListener.modifyRangedLevel(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextRangedHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit(), com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.nextRangedHit(), and com.runehive.game.world.items.containers.equipment.Equipment.openInterface().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/CombatType.java