RuneHive-Game: com.runehive.content.skill.impl.firemaking.FiremakingData Enum Reference
com.runehive.content.skill.impl.firemaking.FiremakingData Enum Reference
Public Member Functions
FiremakingData (int log, int coins, int level, double exp)
int getCoins ()
double getExperience ()
int getLevel ()
int getLog ()
Static Public Member Functions
static Optional< FiremakingData > forId (int id)
Public Attributes
ACHEY_LOG =(2862, 25, 1, 40.0D)
ARCTIC_PINE_LOG =(10810, 100, 42, 125.0D)
EUCALYPTUS_LOG =(12581, 500, 58, 300.5D)
MAGIC_LOG =(1513, 2500, 75, 690.9D)
MAPLE_LOG =(1517, 300, 45, 523.0D)
MOHOGANY_LOG =(6332, 400, 50, 300.5D)
NORMAL_LOG =(1511, 50, 1, 150.0D)
OAK_LOG =(1521, 55, 15, 300.0D)
TEAK_LOG =(6333, 80, 35, 105.0D)
WILLOW_LOG =(1519, 60, 30, 450.0D)
YEW_LOG =(1515, 750, 60, 600.5D)
Private Attributes
final int coins
final double exp
final int level
final int log
Detailed Description
Definition at line 6 of file FiremakingData.java.
Constructor & Destructor Documentation
FiremakingData()
com.runehive.content.skill.impl.firemaking.FiremakingData.FiremakingData (int log, int coins, int level, double exp)
Definition at line 27 of file FiremakingData.java.
{
        this.log = log;
        this.coins = coins;
        this.level = level;
        this.exp = exp;
    }
References coins, exp, level, and log.
Member Function Documentation
forId()
Optional< FiremakingData > com.runehive.content.skill.impl.firemaking.FiremakingData.forId (int id) static
Definition at line 50 of file FiremakingData.java.
{
        return Arrays.stream(values()).filter(a -> a.log == id).findAny();
    }
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop(), com.runehive.content.skill.impl.firemaking.Firemaking.clickObject(), com.runehive.content.skill.impl.firemaking.Firemaking.useItem(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
getCoins()
int com.runehive.content.skill.impl.firemaking.FiremakingData.getCoins ()
Definition at line 38 of file FiremakingData.java.
{
        return coins;
    }
References coins.
getExperience()
double com.runehive.content.skill.impl.firemaking.FiremakingData.getExperience ()
Definition at line 46 of file FiremakingData.java.
{
        return exp;
    }
References exp.
getLevel()
int com.runehive.content.skill.impl.firemaking.FiremakingData.getLevel ()
Definition at line 42 of file FiremakingData.java.
{
        return level;
    }
References level.
getLog()
int com.runehive.content.skill.impl.firemaking.FiremakingData.getLog ()
Definition at line 34 of file FiremakingData.java.
{
        return log;
    }
References log.
Member Data Documentation
ACHEY_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.ACHEY_LOG =(2862, 25, 1, 40.0D)
Definition at line 8 of file FiremakingData.java.
ARCTIC_PINE_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.ARCTIC_PINE_LOG =(10810, 100, 42, 125.0D)
Definition at line 12 of file FiremakingData.java.
coins
final int com.runehive.content.skill.impl.firemaking.FiremakingData.coins private
Definition at line 21 of file FiremakingData.java.
Referenced by FiremakingData(), and getCoins().
EUCALYPTUS_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.EUCALYPTUS_LOG =(12581, 500, 58, 300.5D)
Definition at line 15 of file FiremakingData.java.
exp
final double com.runehive.content.skill.impl.firemaking.FiremakingData.exp private
Definition at line 25 of file FiremakingData.java.
Referenced by FiremakingData(), and getExperience().
level
final int com.runehive.content.skill.impl.firemaking.FiremakingData.level private
Definition at line 23 of file FiremakingData.java.
Referenced by FiremakingData(), and getLevel().
log
final int com.runehive.content.skill.impl.firemaking.FiremakingData.log private
Definition at line 19 of file FiremakingData.java.
Referenced by FiremakingData(), and getLog().
MAGIC_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.MAGIC_LOG =(1513, 2500, 75, 690.9D)
Definition at line 17 of file FiremakingData.java.
MAPLE_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.MAPLE_LOG =(1517, 300, 45, 523.0D)
Definition at line 13 of file FiremakingData.java.
MOHOGANY_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.MOHOGANY_LOG =(6332, 400, 50, 300.5D)
Definition at line 14 of file FiremakingData.java.
NORMAL_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.NORMAL_LOG =(1511, 50, 1, 150.0D)
Definition at line 7 of file FiremakingData.java.
OAK_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.OAK_LOG =(1521, 55, 15, 300.0D)
Definition at line 9 of file FiremakingData.java.
TEAK_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.TEAK_LOG =(6333, 80, 35, 105.0D)
Definition at line 11 of file FiremakingData.java.
WILLOW_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.WILLOW_LOG =(1519, 60, 30, 450.0D)
Definition at line 10 of file FiremakingData.java.
Referenced by com.runehive.content.skill.impl.firemaking.Firemaking.bonfireAction(), and com.runehive.content.skill.impl.firemaking.FiremakingAction.onDestruct().
YEW_LOG
com.runehive.content.skill.impl.firemaking.FiremakingData.YEW_LOG =(1515, 750, 60, 600.5D)
Definition at line 16 of file FiremakingData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/firemaking/FiremakingData.java