RuneHive-Game: com.runehive.content.skill.impl.woodcutting.AxeData Enum Reference
com.runehive.content.skill.impl.woodcutting.AxeData Enum Reference
Represents types of axes.
Public Member Functions
AxeData (int id, int level, int animation, double speed)
Creates the axe.
Static Public Member Functions
static Optional< AxeData > getDefinition (Player player)
Gets the definition for this hatchet.
Public Attributes
ADAMANT =(1357, 31, 869, 0.6)
final int animation
The animation.
BLACK =(1361, 6, 873, 0.4)
BRONZE =(1351, 1, 879, 0.1)
DRAGON =(6739, 61, 2846, 0.85)
final int id
The id.
INFERNAL =(13241, 61, 2117, 0.85)
IRON =(1349, 1, 877, 0.2)
final int level
The level.
MITHRIL =(1355, 21, 871, 0.5)
RUNE =(1359, 41, 867, 0.75)
final double speed
The speed of cutting logs.
STEEL =(1353, 6, 875, 0.3)
THIRD_AGE =(20011, 90, 7264, 0.80)
Static Private Attributes
static final ImmutableSet< AxeData > VALUES = ImmutableSortedSet.copyOf(values()).descendingSet()
Caches our enum values.
Detailed Description
Represents types of axes.
Author
Daniel
Definition at line 16 of file AxeData.java.
Constructor & Destructor Documentation
AxeData()
com.runehive.content.skill.impl.woodcutting.AxeData.AxeData (int id, int level, int animation, double speed)
Creates the axe.
Parameters
id The id.
level The required level.
animation The animation id.
speed speed.
Definition at line 61 of file AxeData.java.
{
        this.id = id;
        this.level = level;
        this.animation = animation;
        this.speed = speed;
    }
References animation, id, level, and speed.
Member Function Documentation
getDefinition()
Optional< AxeData > com.runehive.content.skill.impl.woodcutting.AxeData.getDefinition (Player player) static
Gets the definition for this hatchet.
Parameters
player the identifier to check for.
Returns
an optional holding the AxeData value found, Optional#empty otherwise.
Definition at line 74 of file AxeData.java.
{
        if (player.equipment.hasWeapon()) {
            Optional<AxeData> result = VALUES.stream().filter(it -> player.equipment.contains(it.id) && player.skills.getLevel(Skill.WOODCUTTING) >= it.level).findFirst();
            if (result.isPresent()) {
                return result;
            }
        }
        return VALUES.stream().filter(def -> player.inventory.contains(def.id) && player.skills.getLevel(Skill.WOODCUTTING) >= def.level).findAny();
    }
References com.runehive.game.world.items.containers.equipment.Equipment.contains(), com.runehive.game.world.items.containers.ItemContainer.contains(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.Mob.skills, VALUES, and com.runehive.game.world.entity.skill.Skill.WOODCUTTING.
Referenced by com.runehive.content.wintertodt.Wintertodt.chopRoot(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), com.runehive.content.wintertodt.actions.ChopRoots.execute(), and com.runehive.game.task.impl.ChopVineTask.onSchedule().
Member Data Documentation
ADAMANT
com.runehive.content.skill.impl.woodcutting.AxeData.ADAMANT =(1357, 31, 869, 0.6)
Definition at line 22 of file AxeData.java.
animation
final int com.runehive.content.skill.impl.woodcutting.AxeData.animation
The animation.
Definition at line 46 of file AxeData.java.
Referenced by AxeData(), com.runehive.content.wintertodt.actions.ChopRoots.execute(), and com.runehive.game.task.impl.ChopVineTask.onSchedule().
BLACK
com.runehive.content.skill.impl.woodcutting.AxeData.BLACK =(1361, 6, 873, 0.4)
Definition at line 20 of file AxeData.java.
BRONZE
com.runehive.content.skill.impl.woodcutting.AxeData.BRONZE =(1351, 1, 879, 0.1)
Definition at line 17 of file AxeData.java.
DRAGON
com.runehive.content.skill.impl.woodcutting.AxeData.DRAGON =(6739, 61, 2846, 0.85)
Definition at line 25 of file AxeData.java.
id
final int com.runehive.content.skill.impl.woodcutting.AxeData.id
The id.
Definition at line 36 of file AxeData.java.
Referenced by AxeData().
INFERNAL
com.runehive.content.skill.impl.woodcutting.AxeData.INFERNAL =(13241, 61, 2117, 0.85)
Definition at line 26 of file AxeData.java.
Referenced by com.runehive.content.skill.impl.woodcutting.WoodcuttingAction.chop().
IRON
com.runehive.content.skill.impl.woodcutting.AxeData.IRON =(1349, 1, 877, 0.2)
Definition at line 18 of file AxeData.java.
level
final int com.runehive.content.skill.impl.woodcutting.AxeData.level
The level.
Definition at line 41 of file AxeData.java.
Referenced by AxeData(), com.runehive.content.skill.impl.woodcutting.Woodcutting.clickObject(), and com.runehive.content.skill.impl.woodcutting.Woodcutting.success().
MITHRIL
com.runehive.content.skill.impl.woodcutting.AxeData.MITHRIL =(1355, 21, 871, 0.5)
Definition at line 21 of file AxeData.java.
RUNE
com.runehive.content.skill.impl.woodcutting.AxeData.RUNE =(1359, 41, 867, 0.75)
Definition at line 23 of file AxeData.java.
speed
final double com.runehive.content.skill.impl.woodcutting.AxeData.speed
The speed of cutting logs.
Definition at line 51 of file AxeData.java.
Referenced by AxeData().
STEEL
com.runehive.content.skill.impl.woodcutting.AxeData.STEEL =(1353, 6, 875, 0.3)
Definition at line 19 of file AxeData.java.
THIRD_AGE
com.runehive.content.skill.impl.woodcutting.AxeData.THIRD_AGE =(20011, 90, 7264, 0.80)
Definition at line 24 of file AxeData.java.
VALUES
final ImmutableSet<AxeData> com.runehive.content.skill.impl.woodcutting.AxeData.VALUES = ImmutableSortedSet.copyOf(values()).descendingSet() static private
Caches our enum values.
Definition at line 31 of file AxeData.java.
Referenced by getDefinition().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/woodcutting/AxeData.java