RuneHive-Game: com.runehive.game.world.entity.mob.player.PlayerRight Enum Reference
com.runehive.game.world.entity.mob.player.PlayerRight Enum Reference
Holds all the player right data.
Public Member Functions
String getColor ()
Gets the color of the rank.
int getCrown ()
Gets the crown of the rank.
String getCrownText ()
int getMoneyRequired ()
String getName ()
Gets the name of the rank.
int getRestAnimation ()
Gets the rest animation of the rank.
final boolean greater (PlayerRight other)
final boolean greaterOrEqual (PlayerRight other)
final boolean less (PlayerRight other)
final boolean lessOrEqual (PlayerRight other)
PlayerRight (String name, String color, int crown, int moneyRequired, int restAnimation)
Constructs a new PlayerRight.
Static Public Member Functions
static int dropRateIncrease (Player player, int roll)
static PlayerRight forSpent (int spent)
static int getBloodMoney (Player player)
static String getColor (PlayerRight right)
static String getCrown (Player player)
Gets the crown display.
static String getCrown (PlayerRight right)
Gets the crown display.
static int getDepositAmount (Player player)
Gets the deposit amount.
static double getDropRateBonus (Player player)
static int getForumGroupId (PlayerRight right)
static int getPresetAmount (Player player)
static boolean isAdministrator (Player player)
Checks if the player is a privileged member.
static boolean isDeveloper (Player player)
Checks if the player has developer status.
static boolean isDonator (Player player)
Checks if the player has donator status.
static boolean isElite (Player player)
Checks if the player has elite donator status.
static boolean isExtreme (Player player)
Checks if the player has extreme donator status.
static boolean isHelper (Player player)
Checks if the player is a HELPER member.
static boolean isIronman (Player player)
Checks if the player is an ironman.
static boolean isKing (Player player)
Checks if the player has king donator status.
static boolean isManager (Player player)
Checks if the player is a privileged member.
static boolean isModerator (Player player)
Checks if the player is a management member.
static boolean isOwner (Player player)
static boolean isSuper (Player player)
Checks if the player has super donator status.
static Optional< PlayerRight > lookup (int id)
Public Attributes
ADMINISTRATOR =("Administrator", "D17417", 2, -1, 4116)
DEVELOPER =("Developer", "7D0CED", 4, -1, 4117)
DONATOR =("Donator", "9C4B2F", 5, 10, 4112)
ELITE_DONATOR =("Elite Donator", "2CA395", 8, 500, 4114)
EXTREME_DONATOR =("Extreme Donator", "158A76", 7, 250, 4113)
GRAPHIC =("Graphic", "CE795A", 17, -1, 4112)
HARDCORE_IRONMAN =("Hardcore Ironman", "7A6F74", 14, -1, 4114)
HELPER =("Helper", "5C5858", 15, -1, 4115)
IRONMAN =("Ironman", "7A6F74", 12, -1, 4112)
KING_DONATOR =("King Donator", "8F7A42", 9, 1000, 4115)
MANAGER =("Manager", "D17417", 3, -1, 4116)
MODERATOR =("Moderator", "245EFF", 1, -1, 4116)
OWNER =("Owner", "ED0C0C", 2, -1, 4117)
PLAYER =("Player", "000000", 0, -1, 4111)
SUPER_DONATOR =("Super Donator", "2F809C", 6, 50, 4112)
ULTIMATE_IRONMAN =("Ultimate Ironman", "7A6F74", 13, -1, 4113)
VETERAN =("Veteran", "B1800A", 10, -1, 4115)
YOUTUBER =("Youtuber", "91111A", 11, -1, 4112)
Private Attributes
final String color
The rank color.
final int crown
The crown identification.
final int moneyRequired
final String name
The rank name.
final int restAnimation
The rank rest animation.
Detailed Description
Holds all the player right data.
Author
Daniel
Definition at line 11 of file PlayerRight.java.
Constructor & Destructor Documentation
PlayerRight()
com.runehive.game.world.entity.mob.player.PlayerRight.PlayerRight (String name, String color, int crown, int moneyRequired, int restAnimation)
Constructs a new PlayerRight.
Definition at line 57 of file PlayerRight.java.
{
        this.name = name;
        this.color = color;
        this.crown = crown;
        this.moneyRequired = moneyRequired;
        this.restAnimation = restAnimation;
    }
References color, crown, moneyRequired, name, and restAnimation.
Referenced by forSpent(), getColor(), getCrown(), getForumGroupId(), greater(), greaterOrEqual(), less(), and lessOrEqual().
Member Function Documentation
dropRateIncrease()
int com.runehive.game.world.entity.mob.player.PlayerRight.dropRateIncrease (Player player, int roll) static
Definition at line 240 of file PlayerRight.java.
{
        if (isKing(player)) return roll * 9 / 10; // 10%
        else if (isElite(player)) return roll * 37 / 40; // 7.5%
        else if (isExtreme(player)) return roll * 47 / 50; // 6%
        else if (isSuper(player)) return roll * 189 / 200; // 5.5%
        else if (isDonator(player)) return roll * 191 / 200; // 4.5%
        else return roll * 97 / 100; // 3%
    }
References isDonator(), isElite(), isExtreme(), isKing(), and isSuper().
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropTable.generate().
forSpent()
PlayerRight com.runehive.game.world.entity.mob.player.PlayerRight.forSpent (int spent) static
Definition at line 258 of file PlayerRight.java.
{
        if (spent >= PlayerRight.KING_DONATOR.getMoneyRequired())
            return PlayerRight.KING_DONATOR;
        if (spent >= PlayerRight.EXTREME_DONATOR.getMoneyRequired())
            return PlayerRight.EXTREME_DONATOR;
        if (spent >= PlayerRight.ELITE_DONATOR.getMoneyRequired())
            return PlayerRight.ELITE_DONATOR;
        if (spent >= PlayerRight.SUPER_DONATOR.getMoneyRequired())
            return PlayerRight.SUPER_DONATOR;
        if (spent >= PlayerRight.DONATOR.getMoneyRequired())
            return PlayerRight.DONATOR;
        return null;
    }
References PlayerRight().
Referenced by com.runehive.content.donators.Donation.updateRank().
getBloodMoney()
int com.runehive.game.world.entity.mob.player.PlayerRight.getBloodMoney (Player player) static
Definition at line 226 of file PlayerRight.java.
{
        if (isKing(player))
            return 1500;
        else if (isElite(player))
            return 1400;
        else if (isExtreme(player))
            return 1300;
        else if (isSuper(player))
            return 1200;
        else if (isDonator(player))
            return 1100;
        return 1000;
    }
References isDonator(), isElite(), isExtreme(), isKing(), and isSuper().
Referenced by com.runehive.content.activity.impl.pestcontrol.PestControlGame.PestControlNode.finish(), and com.runehive.game.world.entity.mob.player.PlayerKilling.handle().
getColor() [1/2]
String com.runehive.game.world.entity.mob.player.PlayerRight.getColor ()
Gets the color of the rank.
Definition at line 293 of file PlayerRight.java.
{
        return color;
    }
References color.
getColor() [2/2]
String com.runehive.game.world.entity.mob.player.PlayerRight.getColor (PlayerRight right) static
Definition at line 164 of file PlayerRight.java.
{
        return "<col=" + right.getColor() + "><img=" + (right.getCrown() - 1) + ">";
    }
References getColor(), getCrown(), and PlayerRight().
Referenced by com.runehive.content.triviabot.TriviaBot.answered(), com.runehive.game.service.VoteService.claimReward(), com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.drop(), getColor(), com.runehive.content.pet.Pets.onSpawn(), com.runehive.game.world.entity.skill.SkillManager.updateSkill(), and com.runehive.content.Yell.yell().
getCrown() [1/3]
int com.runehive.game.world.entity.mob.player.PlayerRight.getCrown ()
Gets the crown of the rank.
Definition at line 282 of file PlayerRight.java.
{
        return crown;
    }
References crown.
getCrown() [2/3]
String com.runehive.game.world.entity.mob.player.PlayerRight.getCrown (Player player) static
Gets the crown display.
Definition at line 153 of file PlayerRight.java.
{
        return getCrown(player.right);
    }
References getCrown().
Referenced by com.runehive.content.famehall.FameHandler.activate(), com.runehive.content.combat.Killstreak.announce(), com.runehive.content.RoyaltyProgram.append(), com.runehive.net.packet.out.SendPlayerUpdate.appendAppearanceMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask(), com.runehive.content.WellOfGoodwill.contribute(), com.runehive.content.combat.Killstreak.end(), com.runehive.content.activity.record.GameRecord.GameRecord(), getColor(), getCrown(), getCrown(), com.runehive.content.store.impl.PersonalStore.myShop(), com.runehive.content.ProfileViewer.open(), com.runehive.util.GameSaver.toJson(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateMainComponents(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.updateOfferComponents(), com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.updateOfferComponents(), and com.runehive.content.donators.Donation.updateRank().
getCrown() [3/3]
String com.runehive.game.world.entity.mob.player.PlayerRight.getCrown (PlayerRight right) static
Gets the crown display.
Definition at line 160 of file PlayerRight.java.
{
        return right.equals(PLAYER) ? "" : "<img=" + (right.getCrown() - 1) + ">";
    }
References getCrown(), PLAYER, and PlayerRight().
getCrownText()
String com.runehive.game.world.entity.mob.player.PlayerRight.getCrownText ()
Definition at line 168 of file PlayerRight.java.
{
        return this == PLAYER ? "" : "<img=" + (crown - 1) + "> ";
    }
References crown, and PLAYER.
Referenced by com.runehive.content.WellOfGoodwill.open().
getDepositAmount()
int com.runehive.game.world.entity.mob.player.PlayerRight.getDepositAmount (Player player) static
Gets the deposit amount.
Definition at line 198 of file PlayerRight.java.
{
        if (isKing(player))
            return 28;
        else if (isElite(player))
            return 20;
        else if (isExtreme(player))
            return 15;
        else if (isSuper(player))
            return 10;
        else if (isDonator(player))
            return 5;
        return 1;
    }
References isDonator(), isElite(), isExtreme(), isKing(), and isSuper().
Referenced by com.runehive.game.world.items.containers.bank.DonatorDeposit.deposit().
getDropRateBonus()
double com.runehive.game.world.entity.mob.player.PlayerRight.getDropRateBonus (Player player) static
Definition at line 249 of file PlayerRight.java.
{
        if (isKing(player)) return 10;
        else if (isElite(player)) return 7.5;
        else if (isExtreme(player)) return 6;
        else if (isSuper(player)) return 5.5;
        else if (isDonator(player)) return 4.5;
        else return 3;
    }
References isDonator(), isElite(), isExtreme(), isKing(), and isSuper().
Referenced by com.runehive.game.world.entity.mob.npc.drop.NpcDropManager.rollDrop().
getForumGroupId()
int com.runehive.game.world.entity.mob.player.PlayerRight.getForumGroupId (PlayerRight right) static
Definition at line 172 of file PlayerRight.java.
{
        switch (right) {
            case DONATOR:
                return 10;
            case SUPER_DONATOR:
                return 14;
            case EXTREME_DONATOR:
                return 11;
            case ELITE_DONATOR:
                return 12;
            case KING_DONATOR:
                return 16;
            default:
                return -1;
        }
    }
References DONATOR, ELITE_DONATOR, EXTREME_DONATOR, KING_DONATOR, PlayerRight(), and SUPER_DONATOR.
getMoneyRequired()
int com.runehive.game.world.entity.mob.player.PlayerRight.getMoneyRequired ()
Definition at line 286 of file PlayerRight.java.
{
        return moneyRequired;
    }
References moneyRequired.
getName()
String com.runehive.game.world.entity.mob.player.PlayerRight.getName ()
Gets the name of the rank.
Definition at line 275 of file PlayerRight.java.
{
        return name;
    }
References name.
Referenced by com.runehive.content.Waypoints.getAllowedPoints(), com.runehive.content.ProfileViewer.open(), com.runehive.content.donators.Donation.updateRank(), and com.runehive.content.Yell.yell().
getPresetAmount()
int com.runehive.game.world.entity.mob.player.PlayerRight.getPresetAmount (Player player) static
Definition at line 212 of file PlayerRight.java.
{
        if (isKing(player))
            return 10;
        else if (isElite(player))
            return 9;
        else if (isExtreme(player))
            return 8;
        else if (isSuper(player))
            return 7;
        else if (isDonator(player))
            return 6;
        return 5;
    }
References isDonator(), isElite(), isExtreme(), isKing(), and isSuper().
Referenced by com.runehive.content.preset.PresetManager.getTaken(), com.runehive.content.preset.PresetManager.open(), and com.runehive.content.preset.PresetManager.refresh().
getRestAnimation()
int com.runehive.game.world.entity.mob.player.PlayerRight.getRestAnimation ()
Gets the rest animation of the rank.
Definition at line 300 of file PlayerRight.java.
{
        return restAnimation;
    }
References restAnimation.
greater()
final boolean com.runehive.game.world.entity.mob.player.PlayerRight.greater (PlayerRight other)
Definition at line 304 of file PlayerRight.java.
{
        return ordinal() > other.ordinal();
    }
References PlayerRight().
greaterOrEqual()
final boolean com.runehive.game.world.entity.mob.player.PlayerRight.greaterOrEqual (PlayerRight other)
Definition at line 308 of file PlayerRight.java.
{
        return ordinal() >= other.ordinal();
    }
References PlayerRight().
isAdministrator()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isAdministrator (Player player) static
Checks if the player is a privileged member.
Definition at line 90 of file PlayerRight.java.
{
        return isManager(player) || player.right.equals(ADMINISTRATOR);
    }
References ADMINISTRATOR, and isManager().
Referenced by com.runehive.game.world.entity.mob.prayer.Prayer.canToggle(), com.runehive.game.world.entity.mob.player.PlayerDeath.death(), com.runehive.content.activity.record.PlayerRecord.end(), isElite(), isExtreme(), isKing(), isModerator(), com.runehive.game.service.HighscoreService.saveHighscores(), com.runehive.game.world.entity.combat.magic.Autocast.setAutocast(), and com.runehive.content.teleport.TeleportHandler.teleport().
isDeveloper()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isDeveloper (Player player) static
Checks if the player has developer status.
Definition at line 76 of file PlayerRight.java.
{
        return player.right.equals(OWNER) || player.right.equals(DEVELOPER);
    }
References DEVELOPER, and OWNER.
Referenced by com.runehive.content.clanchannel.channel.ClanChannelHandler.attemptConnection(), com.runehive.content.skill.impl.magic.spell.SpellCasting.cast(), com.runehive.content.skill.impl.magic.spell.SpellCasting.cast(), com.runehive.game.plugin.PluginContext.handleDropItemEvent(), com.runehive.net.packet.in.ExaminePacketListener.handleInterfaceExamine(), com.runehive.game.plugin.PluginContext.handleItemContainerContextMenuEvent(), com.runehive.net.packet.in.UseItemPacketListener.handleItemOnGround(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.net.packet.in.DropItemPacketListener.handlePacket(), com.runehive.net.packet.in.MagicOnItemPacketListener.handlePacket(), com.runehive.net.packet.in.RegionChangePacketListener.handlePacket(), com.runehive.game.plugin.PluginContext.handlePickupItemEvent(), isManager(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), com.runehive.game.world.entity.mob.player.Player.loadRegion(), com.runehive.game.world.entity.mob.player.PlayerAssistant.run(), and com.runehive.content.skill.impl.magic.teleport.Teleportation.teleport().
isDonator()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isDonator (Player player) static
Checks if the player has donator status.
Definition at line 111 of file PlayerRight.java.
{
        return isModerator(player) || isHelper(player) || player.donation.getSpent() >= DONATOR.getMoneyRequired();
    }
References DONATOR, isHelper(), and isModerator().
Referenced by com.runehive.content.skill.impl.slayer.Slayer.cancel(), com.runehive.content.skill.impl.thieving.Thieving.clickObject(), dropRateIncrease(), getBloodMoney(), getDepositAmount(), getDropRateBonus(), getPresetAmount(), com.runehive.net.packet.in.AppearanceChangePacketListener.isValid(), com.runehive.content.dailyeffect.impl.DailySlayerTaskTeleport.maxUses(), com.runehive.game.world.entity.mob.player.Player.onStep(), com.runehive.game.world.items.containers.bank.DonatorDeposit.open(), and com.runehive.content.Yell.yell().
isElite()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isElite (Player player) static
Checks if the player has elite donator status.
Definition at line 132 of file PlayerRight.java.
{
        return isAdministrator(player) || player.donation.getSpent() >= ELITE_DONATOR.getMoneyRequired();
    }
References ELITE_DONATOR, and isAdministrator().
Referenced by dropRateIncrease(), getBloodMoney(), getDepositAmount(), getDropRateBonus(), getPresetAmount(), and com.runehive.content.dailyeffect.impl.DailySlayerTaskTeleport.maxUses().
isExtreme()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isExtreme (Player player) static
Checks if the player has extreme donator status.
Definition at line 125 of file PlayerRight.java.
{
        return isAdministrator(player) || player.donation.getSpent() >= EXTREME_DONATOR.getMoneyRequired();
    }
References EXTREME_DONATOR, and isAdministrator().
Referenced by dropRateIncrease(), getBloodMoney(), getDepositAmount(), getDropRateBonus(), getPresetAmount(), and com.runehive.content.dailyeffect.impl.DailySlayerTaskTeleport.maxUses().
isHelper()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isHelper (Player player) static
Checks if the player is a HELPER member.
Definition at line 104 of file PlayerRight.java.
{
        return isModerator(player) || player.right.equals(HELPER);
    }
References HELPER, and isModerator().
Referenced by isDonator(), isSuper(), com.runehive.content.donators.Donation.updateRank(), and com.runehive.content.Yell.yell().
isIronman()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isIronman (Player player) static
Checks if the player is an ironman.
Definition at line 146 of file PlayerRight.java.
{
        return player.right.equals(IRONMAN) || player.right.equals(ULTIMATE_IRONMAN) || player.right.equals(HARDCORE_IRONMAN);
    }
References HARDCORE_IRONMAN, IRONMAN, and ULTIMATE_IRONMAN.
Referenced by com.runehive.content.triviabot.TriviaBot.answered(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.combat.CombatDamage.calculateProperKiller(), com.runehive.content.clanchannel.channel.ClanChannelHandler.connect(), com.runehive.content.store.impl.DefaultStore.open(), com.runehive.game.world.items.ground.GroundItem.pickup(), com.runehive.content.store.Store.purchase(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.request(), com.runehive.content.gambling.GambleManager.sendRequest(), com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.start(), com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.start(), and com.runehive.content.donators.Donation.updateRank().
isKing()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isKing (Player player) static
Checks if the player has king donator status.
Definition at line 139 of file PlayerRight.java.
{
        return isAdministrator(player) || player.donation.getSpent() >= KING_DONATOR.getMoneyRequired();
    }
References isAdministrator(), and KING_DONATOR.
Referenced by dropRateIncrease(), getBloodMoney(), getDepositAmount(), getDropRateBonus(), and getPresetAmount().
isManager()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isManager (Player player) static
Checks if the player is a privileged member.
Definition at line 83 of file PlayerRight.java.
{
        return isDeveloper(player) || player.right.equals(MANAGER);
    }
References isDeveloper(), and MANAGER.
Referenced by isAdministrator().
isModerator()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isModerator (Player player) static
Checks if the player is a management member.
Definition at line 97 of file PlayerRight.java.
{
        return isAdministrator(player) || player.right.equals(MODERATOR);
    }
References isAdministrator(), and MODERATOR.
Referenced by com.runehive.game.world.World.getStaff(), com.runehive.game.world.World.getStaffCount(), isDonator(), isHelper(), isSuper(), com.runehive.content.ProfileViewer.open(), and com.runehive.content.donators.Donation.updateRank().
isOwner()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isOwner (Player player) static
Definition at line 69 of file PlayerRight.java.
{
        return player.right.equals(OWNER);
    }
References OWNER.
Referenced by com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.add(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSeasStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TridentOfTheSwampStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.custom.TumekenStrategy.canAttack(), com.runehive.game.world.entity.combat.strategy.player.PlayerMagicStrategy.canAttack(), com.runehive.content.activity.impl.godwars.GodwarsActivity.canEnter(), com.runehive.net.packet.in.ButtonClickPacketListener.handlePacket(), com.runehive.game.world.entity.mob.player.exchange.ExchangeSession.request(), and com.runehive.content.Yell.yell().
isSuper()
boolean com.runehive.game.world.entity.mob.player.PlayerRight.isSuper (Player player) static
Checks if the player has super donator status.
Definition at line 118 of file PlayerRight.java.
{
        return isModerator(player) || isHelper(player) || player.donation.getSpent() >= SUPER_DONATOR.getMoneyRequired();
    }
References isHelper(), isModerator(), and SUPER_DONATOR.
Referenced by com.runehive.content.skill.impl.thieving.Thieving.clickObject(), dropRateIncrease(), getBloodMoney(), getDepositAmount(), getDropRateBonus(), getPresetAmount(), com.runehive.content.dailyeffect.impl.DailySlayerTaskTeleport.maxUses(), and com.runehive.content.Obelisks.open().
less()
final boolean com.runehive.game.world.entity.mob.player.PlayerRight.less (PlayerRight other)
Definition at line 312 of file PlayerRight.java.
{
        return ordinal() < other.ordinal();
    }
References PlayerRight().
lessOrEqual()
final boolean com.runehive.game.world.entity.mob.player.PlayerRight.lessOrEqual (PlayerRight other)
Definition at line 316 of file PlayerRight.java.
{
        return ordinal() <= other.ordinal();
    }
References PlayerRight().
lookup()
Optional< PlayerRight > com.runehive.game.world.entity.mob.player.PlayerRight.lookup (int id) static
Definition at line 65 of file PlayerRight.java.
{
        return Arrays.stream(values()).filter(it -> it.crown == id).findFirst();
    }
Referenced by com.runehive.util.GameSaver.load().
Member Data Documentation
ADMINISTRATOR
com.runehive.game.world.entity.mob.player.PlayerRight.ADMINISTRATOR =("Administrator", "D17417", 2, -1, 4116)
Definition at line 14 of file PlayerRight.java.
Referenced by isAdministrator().
color
final String com.runehive.game.world.entity.mob.player.PlayerRight.color private
The rank color.
Definition at line 47 of file PlayerRight.java.
Referenced by getColor(), and PlayerRight().
crown
final int com.runehive.game.world.entity.mob.player.PlayerRight.crown private
The crown identification.
Definition at line 40 of file PlayerRight.java.
Referenced by getCrown(), getCrownText(), and PlayerRight().
DEVELOPER
com.runehive.game.world.entity.mob.player.PlayerRight.DEVELOPER =("Developer", "7D0CED", 4, -1, 4117)
Definition at line 17 of file PlayerRight.java.
Referenced by isDeveloper().
DONATOR
com.runehive.game.world.entity.mob.player.PlayerRight.DONATOR =("Donator", "9C4B2F", 5, 10, 4112)
Definition at line 19 of file PlayerRight.java.
Referenced by getForumGroupId(), and isDonator().
ELITE_DONATOR
com.runehive.game.world.entity.mob.player.PlayerRight.ELITE_DONATOR =("Elite Donator", "2CA395", 8, 500, 4114)
Definition at line 22 of file PlayerRight.java.
Referenced by getForumGroupId(), and isElite().
EXTREME_DONATOR
com.runehive.game.world.entity.mob.player.PlayerRight.EXTREME_DONATOR =("Extreme Donator", "158A76", 7, 250, 4113)
Definition at line 21 of file PlayerRight.java.
Referenced by getForumGroupId(), and isExtreme().
GRAPHIC
com.runehive.game.world.entity.mob.player.PlayerRight.GRAPHIC =("Graphic", "CE795A", 17, -1, 4112)
Definition at line 30 of file PlayerRight.java.
HARDCORE_IRONMAN
com.runehive.game.world.entity.mob.player.PlayerRight.HARDCORE_IRONMAN =("Hardcore Ironman", "7A6F74", 14, -1, 4114)
Definition at line 28 of file PlayerRight.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.claimIronmanArmour(), com.runehive.game.service.HighscoreService.getRank(), isIronman(), and com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath().
HELPER
com.runehive.game.world.entity.mob.player.PlayerRight.HELPER =("Helper", "5C5858", 15, -1, 4115)
Definition at line 29 of file PlayerRight.java.
Referenced by com.runehive.game.world.World.getStaff(), com.runehive.game.world.World.getStaffCount(), and isHelper().
IRONMAN
com.runehive.game.world.entity.mob.player.PlayerRight.IRONMAN =("Ironman", "7A6F74", 12, -1, 4112)
Definition at line 26 of file PlayerRight.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.claimIronmanArmour(), com.runehive.game.service.HighscoreService.getRank(), isIronman(), and com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath().
KING_DONATOR
com.runehive.game.world.entity.mob.player.PlayerRight.KING_DONATOR =("King Donator", "8F7A42", 9, 1000, 4115)
Definition at line 23 of file PlayerRight.java.
Referenced by getForumGroupId(), and isKing().
MANAGER
com.runehive.game.world.entity.mob.player.PlayerRight.MANAGER =("Manager", "D17417", 3, -1, 4116)
Definition at line 15 of file PlayerRight.java.
Referenced by isManager().
MODERATOR
com.runehive.game.world.entity.mob.player.PlayerRight.MODERATOR =("Moderator", "245EFF", 1, -1, 4116)
Definition at line 13 of file PlayerRight.java.
Referenced by isModerator().
moneyRequired
final int com.runehive.game.world.entity.mob.player.PlayerRight.moneyRequired private
Definition at line 42 of file PlayerRight.java.
Referenced by getMoneyRequired(), and PlayerRight().
name
final String com.runehive.game.world.entity.mob.player.PlayerRight.name private
The rank name.
Definition at line 35 of file PlayerRight.java.
Referenced by getName(), and PlayerRight().
OWNER
com.runehive.game.world.entity.mob.player.PlayerRight.OWNER =("Owner", "ED0C0C", 2, -1, 4117)
Definition at line 16 of file PlayerRight.java.
Referenced by com.runehive.net.packet.in.ColorPacketListener.handlePacket(), com.runehive.net.packet.in.WieldItemPacketListener.handlePacket(), isDeveloper(), and isOwner().
PLAYER
com.runehive.game.world.entity.mob.player.PlayerRight.PLAYER =("Player", "000000", 0, -1, 4111)
Definition at line 12 of file PlayerRight.java.
Referenced by getCrown(), getCrownText(), com.runehive.util.GameSaver.load(), and com.runehive.net.codec.login.LoginResponsePacket.LoginResponsePacket().
restAnimation
final int com.runehive.game.world.entity.mob.player.PlayerRight.restAnimation private
The rank rest animation.
Definition at line 52 of file PlayerRight.java.
Referenced by getRestAnimation(), and PlayerRight().
SUPER_DONATOR
com.runehive.game.world.entity.mob.player.PlayerRight.SUPER_DONATOR =("Super Donator", "2F809C", 6, 50, 4112)
Definition at line 20 of file PlayerRight.java.
Referenced by getForumGroupId(), and isSuper().
ULTIMATE_IRONMAN
com.runehive.game.world.entity.mob.player.PlayerRight.ULTIMATE_IRONMAN =("Ultimate Ironman", "7A6F74", 13, -1, 4113)
Definition at line 27 of file PlayerRight.java.
Referenced by com.runehive.game.world.items.containers.bank.BankVault.add(), com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), com.runehive.game.world.entity.mob.prayer.Prayer.canToggle(), com.runehive.game.world.entity.mob.player.PlayerAssistant.claimIronmanArmour(), com.runehive.game.service.HighscoreService.getRank(), isIronman(), and com.runehive.game.world.items.containers.bank.Bank.open().
VETERAN
com.runehive.game.world.entity.mob.player.PlayerRight.VETERAN =("Veteran", "B1800A", 10, -1, 4115)
Definition at line 24 of file PlayerRight.java.
YOUTUBER
com.runehive.game.world.entity.mob.player.PlayerRight.YOUTUBER =("Youtuber", "91111A", 11, -1, 4112)
Definition at line 25 of file PlayerRight.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/player/PlayerRight.java