RuneHive-Game: com.runehive.content.skill.impl.fletching.impl.Featherable Enum Reference
com.runehive.content.skill.impl.fletching.impl.Featherable Enum Reference
Public Member Functions
Featherable (Item use, Item with, FletchableItem... items)
int getAnimation ()
FletchableItem[] getFletchableItems ()
int getGraphics ()
Item[] getIngredients ()
String getProductionMessage ()
Item getUse ()
Item getWith ()
Static Public Member Functions
static void load ()
Public Attributes
ADAMANT_BOLT =(new Item(314, 10), new Item(9380, 10), new FletchableItem(new Item(9143, 10), 61, 7.0))
ADAMANT_DARTs =(new Item(314, 10), new Item(823, 10), new FletchableItem(new Item(810, 10), 67, 15.0))
AMETHYST_DARTs =(new Item(314, 10), new Item(25853, 10), new FletchableItem(new Item(25849, 10), 90, 21.0))
BRONZE_BOLT =(new Item(314, 10), new Item(9375, 10), new FletchableItem(new Item(877, 10), 9, 0.5))
BRONZE_DARTs =(new Item(314, 10), new Item(819, 10), new FletchableItem(new Item(806, 10), 1, 1.8))
DRAGON_DARTs =(new Item(314, 10), new Item(11232, 10), new FletchableItem(new Item(11230, 10), 95, 25.0))
HEADLESS_ARROWS =(new Item(314, 15), new Item(52, 15), new FletchableItem(new Item(53, 15), 1, 1.0))
IRON_BOLT =(new Item(314, 10), new Item(9377, 10), new FletchableItem(new Item(9140, 10), 39, 1.5))
IRON_DARTs =(new Item(314, 10), new Item(820, 10), new FletchableItem(new Item(807, 10), 22, 3.8))
MITHRIL_BOLT =(new Item(314, 10), new Item(9379, 10), new FletchableItem(new Item(9142, 10), 54, 5.0))
MITHRIL_DARTs =(new Item(314, 10), new Item(822, 10), new FletchableItem(new Item(809, 10), 52, 11.2))
RUNE_DARTs =(new Item(314, 10), new Item(824, 10), new FletchableItem(new Item(811, 10), 81, 18.8))
RUNITE_BOLT =(new Item(314, 10), new Item(9381, 10), new FletchableItem(new Item(9144, 10), 69, 10.0))
STEEL_BOLT =(new Item(314, 10), new Item(9378, 10), new FletchableItem(new Item(9141, 10), 46, 3.5))
STEEL_DARTs =(new Item(314, 10), new Item(821, 10), new FletchableItem(new Item(808, 10), 37, 7.5))
Private Attributes
final FletchableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 8 of file Featherable.java.
Constructor & Destructor Documentation
Featherable()
com.runehive.content.skill.impl.fletching.impl.Featherable.Featherable (Item use, Item with, FletchableItem... items)
Definition at line 29 of file Featherable.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.fletching.impl.Featherable.getAnimation ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 42 of file Featherable.java.
{
        switch (this) {
            case BRONZE_DARTs:
                return 8482;
            case IRON_DARTs:
                return 8483;
            case STEEL_DARTs:
                return 8484;
            case MITHRIL_DARTs:
                return 8485;
            case ADAMANT_DARTs:
                return 8486;
            case RUNE_DARTs:
                return 8487;
            case DRAGON_DARTs:
                return 8488;
            case BRONZE_BOLT:
                return 8463;
            case IRON_BOLT:
                return 8464;
            case STEEL_BOLT:
                return 8467;
            case MITHRIL_BOLT:
                return 8468;
            case ADAMANT_BOLT:
                return 8469;
            case RUNITE_BOLT:
                return 8470;
            case HEADLESS_ARROWS:
            default:
                return 1248;
        }
    }
References ADAMANT_BOLT, ADAMANT_DARTs, BRONZE_BOLT, BRONZE_DARTs, DRAGON_DARTs, HEADLESS_ARROWS, IRON_BOLT, IRON_DARTs, MITHRIL_BOLT, MITHRIL_DARTs, RUNE_DARTs, RUNITE_BOLT, STEEL_BOLT, and STEEL_DARTs.
getFletchableItems()
FletchableItem[] com.runehive.content.skill.impl.fletching.impl.Featherable.getFletchableItems ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 92 of file Featherable.java.
{
        return items;
    }
References items.
getGraphics()
int com.runehive.content.skill.impl.fletching.impl.Featherable.getGraphics ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 77 of file Featherable.java.
{
        return -1;
    }
getIngredients()
Item[] com.runehive.content.skill.impl.fletching.impl.Featherable.getIngredients ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 102 of file Featherable.java.
{
        return new Item[] { use, with };
    }
References use, and with.
getProductionMessage()
String com.runehive.content.skill.impl.fletching.impl.Featherable.getProductionMessage ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 97 of file Featherable.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.fletching.impl.Featherable.getUse ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 82 of file Featherable.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.fletching.impl.Featherable.getWith ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 87 of file Featherable.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.fletching.impl.Featherable.load () static
Definition at line 35 of file Featherable.java.
{
        for (Featherable featherable : values()) {
            Fletching.addFletchable(featherable);
        }
    }
References com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), and Featherable().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
ADAMANT_BOLT
com.runehive.content.skill.impl.fletching.impl.Featherable.ADAMANT_BOLT =(new Item(314, 10), new Item(9380, 10), new FletchableItem(new Item(9143, 10), 61, 7.0))
Definition at line 14 of file Featherable.java.
Referenced by getAnimation().
ADAMANT_DARTs
com.runehive.content.skill.impl.fletching.impl.Featherable.ADAMANT_DARTs =(new Item(314, 10), new Item(823, 10), new FletchableItem(new Item(810, 10), 67, 15.0))
Definition at line 20 of file Featherable.java.
Referenced by getAnimation().
AMETHYST_DARTs
com.runehive.content.skill.impl.fletching.impl.Featherable.AMETHYST_DARTs =(new Item(314, 10), new Item(25853, 10), new FletchableItem(new Item(25849, 10), 90, 21.0))
Definition at line 22 of file Featherable.java.
BRONZE_BOLT
com.runehive.content.skill.impl.fletching.impl.Featherable.BRONZE_BOLT =(new Item(314, 10), new Item(9375, 10), new FletchableItem(new Item(877, 10), 9, 0.5))
Definition at line 10 of file Featherable.java.
Referenced by getAnimation().
BRONZE_DARTs
com.runehive.content.skill.impl.fletching.impl.Featherable.BRONZE_DARTs =(new Item(314, 10), new Item(819, 10), new FletchableItem(new Item(806, 10), 1, 1.8))
Definition at line 16 of file Featherable.java.
Referenced by getAnimation().
DRAGON_DARTs
com.runehive.content.skill.impl.fletching.impl.Featherable.DRAGON_DARTs =(new Item(314, 10), new Item(11232, 10), new FletchableItem(new Item(11230, 10), 95, 25.0))
Definition at line 23 of file Featherable.java.
Referenced by getAnimation().
HEADLESS_ARROWS
com.runehive.content.skill.impl.fletching.impl.Featherable.HEADLESS_ARROWS =(new Item(314, 15), new Item(52, 15), new FletchableItem(new Item(53, 15), 1, 1.0))
Definition at line 9 of file Featherable.java.
Referenced by getAnimation().
IRON_BOLT
com.runehive.content.skill.impl.fletching.impl.Featherable.IRON_BOLT =(new Item(314, 10), new Item(9377, 10), new FletchableItem(new Item(9140, 10), 39, 1.5))
Definition at line 11 of file Featherable.java.
Referenced by getAnimation().
IRON_DARTs
com.runehive.content.skill.impl.fletching.impl.Featherable.IRON_DARTs =(new Item(314, 10), new Item(820, 10), new FletchableItem(new Item(807, 10), 22, 3.8))
Definition at line 17 of file Featherable.java.
Referenced by getAnimation().
items
final FletchableItem [] com.runehive.content.skill.impl.fletching.impl.Featherable.items private
Definition at line 27 of file Featherable.java.
Referenced by Featherable(), and getFletchableItems().
MITHRIL_BOLT
com.runehive.content.skill.impl.fletching.impl.Featherable.MITHRIL_BOLT =(new Item(314, 10), new Item(9379, 10), new FletchableItem(new Item(9142, 10), 54, 5.0))
Definition at line 13 of file Featherable.java.
Referenced by getAnimation().
MITHRIL_DARTs
com.runehive.content.skill.impl.fletching.impl.Featherable.MITHRIL_DARTs =(new Item(314, 10), new Item(822, 10), new FletchableItem(new Item(809, 10), 52, 11.2))
Definition at line 19 of file Featherable.java.
Referenced by getAnimation().
RUNE_DARTs
com.runehive.content.skill.impl.fletching.impl.Featherable.RUNE_DARTs =(new Item(314, 10), new Item(824, 10), new FletchableItem(new Item(811, 10), 81, 18.8))
Definition at line 21 of file Featherable.java.
Referenced by getAnimation().
RUNITE_BOLT
com.runehive.content.skill.impl.fletching.impl.Featherable.RUNITE_BOLT =(new Item(314, 10), new Item(9381, 10), new FletchableItem(new Item(9144, 10), 69, 10.0))
Definition at line 15 of file Featherable.java.
Referenced by getAnimation().
STEEL_BOLT
com.runehive.content.skill.impl.fletching.impl.Featherable.STEEL_BOLT =(new Item(314, 10), new Item(9378, 10), new FletchableItem(new Item(9141, 10), 46, 3.5))
Definition at line 12 of file Featherable.java.
Referenced by getAnimation().
STEEL_DARTs
com.runehive.content.skill.impl.fletching.impl.Featherable.STEEL_DARTs =(new Item(314, 10), new Item(821, 10), new FletchableItem(new Item(808, 10), 37, 7.5))
Definition at line 18 of file Featherable.java.
Referenced by getAnimation().
use
final Item com.runehive.content.skill.impl.fletching.impl.Featherable.use private
Definition at line 25 of file Featherable.java.
Referenced by Featherable(), getIngredients(), and getUse().
with
final Item com.runehive.content.skill.impl.fletching.impl.Featherable.with private
Definition at line 26 of file Featherable.java.
Referenced by Featherable(), getIngredients(), and getWith().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fletching/impl/Featherable.java