RuneHive-Game: com.runehive.content.skill.impl.fishing.Fishable Enum Reference
com.runehive.content.skill.impl.fishing.Fishable Enum Reference
Public Member Functions
Fishable (int rawFishId, int toolId, int levelRequired, double experienceGain, int baitRequired)
short getBaitRequired ()
double getExperience ()
int getRawFishId ()
short getRequiredLevel ()
short getToolId ()
Static Public Member Functions
static void declare ()
static Fishable forId (int rawFishId)
Public Attributes
ANCHOVIES =(321, SMALL_FISHING_NET, 15, 40.0D, -1)
BASS =(363, BIG_FISHING_NET, 46, 100.0D, -1)
CAVE_EEL =(5001, FISHING_ROD, 38, 80.0D, FISHING_BAIT)
COD =(341, BIG_FISHING_NET, 23, 45.0D, -1)
CRAYFISH =(13435, 13431, 1, 10.0D, -1)
DARK_CRAB =(11934, 301, 85, 205.0D, DARK_FISHING_BAIT)
FROG_SPAWN =(5004, SMALL_FISHING_NET, 33, 75.0D, -1)
HERRING =(345, FISHING_ROD, 10, 30.0D, FISHING_BAIT)
KARAMBWAN =(3142, 3157, 65, 100.0D, -1)
KARAMBWANJI =(3150, SMALL_FISHING_NET, 5, 5.0D, -1)
LAVA_EEL =(2148, FISHING_ROD, 53, 30.0D, FISHING_BAIT)
LOBSTER =(377, LOBSTER_POT, 40, 90.0D, -1)
MACKEREL =(353, BIG_FISHING_NET, 16, 20.0D, -1)
MANTA_RAY =(389, BIG_FISHING_NET, 81, 155.0D, -1)
MONK_FISH =(7944, SMALL_FISHING_NET, 62, 110.0D, -1)
PIKE =(349, FISHING_ROD, 25, 60.0D, FISHING_BAIT)
SALMON =(331, FLY_FISHING_ROD, 30, 70.0D, 314)
SARDINE =(327, FISHING_ROD, 5, 20.0D, FISHING_BAIT)
SEA_TURTLE =(395, -1, 79, 38.0D, -1)
SHARK =(383, HARPOON, 76, 125.0D, -1)
SHRIMP =(317, SMALL_FISHING_NET, 1, 10.0D, -1)
SLIMY_EEL =(3379, FISHING_ROD, 28, 65.0D, FISHING_BAIT)
SWORD_FISH =(371, HARPOON, 50, 100.0D, -1)
SWORD_FISH2 =(371, DRAGON_HARPOON, 50, 100.0D, -1)
TROUT =(335, FLY_FISHING_ROD, 20, 50.0D, 314)
TUNA =(359, HARPOON, 35, 80.0D, -1)
TUNA2 =(359, DRAGON_HARPOON, 35, 80.0D, -1)
Private Attributes
short baitRequired
double experienceGain
short levelRequired
short rawFishId
short toolId
Static Private Attributes
static Map< Integer, Fishable > fish = new HashMap<>()
Detailed Description
Definition at line 8 of file Fishable.java.
Constructor & Destructor Documentation
Fishable()
com.runehive.content.skill.impl.fishing.Fishable.Fishable (int rawFishId, int toolId, int levelRequired, double experienceGain, int baitRequired)
Definition at line 55 of file Fishable.java.
{
        this.rawFishId = ((short) rawFishId);
        this.toolId = ((short) toolId);
        this.levelRequired = ((short) levelRequired);
        this.experienceGain = experienceGain;
        this.baitRequired = ((short) baitRequired);
    }
References baitRequired, experienceGain, levelRequired, rawFishId, and toolId.
Referenced by declare(), and forId().
Member Function Documentation
declare()
void com.runehive.content.skill.impl.fishing.Fishable.declare () static
Definition at line 39 of file Fishable.java.
{
        for (Fishable fishes : values())
            fish.put((int) fishes.getRawFishId(), fishes);
    }
References fish, and Fishable().
Referenced by com.runehive.content.skill.SkillRepository.load().
forId()
Fishable com.runehive.content.skill.impl.fishing.Fishable.forId (int rawFishId) static
Definition at line 51 of file Fishable.java.
{
        return fish.get(rawFishId);
    }
References fish, Fishable(), and rawFishId.
getBaitRequired()
short com.runehive.content.skill.impl.fishing.Fishable.getBaitRequired ()
Definition at line 63 of file Fishable.java.
{
        return baitRequired;
    }
References baitRequired.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish(), and com.runehive.content.skill.impl.fishing.Fishing.hasFishingItems().
getExperience()
double com.runehive.content.skill.impl.fishing.Fishable.getExperience ()
Definition at line 67 of file Fishable.java.
{
        return experienceGain;
    }
References experienceGain.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish().
getRawFishId()
int com.runehive.content.skill.impl.fishing.Fishable.getRawFishId ()
Definition at line 71 of file Fishable.java.
{
        return rawFishId;
    }
References rawFishId.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish().
getRequiredLevel()
short com.runehive.content.skill.impl.fishing.Fishable.getRequiredLevel ()
Definition at line 75 of file Fishable.java.
{
        return levelRequired;
    }
References levelRequired.
Referenced by com.runehive.content.skill.impl.fishing.Fishing.canFish(), and com.runehive.content.skill.impl.fishing.Fishing.success().
getToolId()
short com.runehive.content.skill.impl.fishing.Fishable.getToolId ()
Definition at line 79 of file Fishable.java.
{
        return toolId;
    }
References toolId.
Referenced by com.runehive.content.skill.impl.fishing.Fishing.hasFishingItems(), and com.runehive.content.skill.impl.fishing.Fishing.success().
Member Data Documentation
ANCHOVIES
com.runehive.content.skill.impl.fishing.Fishable.ANCHOVIES =(321, SMALL_FISHING_NET, 15, 40.0D, -1)
Definition at line 14 of file Fishable.java.
baitRequired
short com.runehive.content.skill.impl.fishing.Fishable.baitRequired private
Definition at line 47 of file Fishable.java.
Referenced by Fishable(), and getBaitRequired().
BASS
com.runehive.content.skill.impl.fishing.Fishable.BASS =(363, BIG_FISHING_NET, 46, 100.0D, -1)
Definition at line 27 of file Fishable.java.
CAVE_EEL
com.runehive.content.skill.impl.fishing.Fishable.CAVE_EEL =(5001, FISHING_ROD, 38, 80.0D, FISHING_BAIT)
Definition at line 25 of file Fishable.java.
COD
com.runehive.content.skill.impl.fishing.Fishable.COD =(341, BIG_FISHING_NET, 23, 45.0D, -1)
Definition at line 17 of file Fishable.java.
CRAYFISH
com.runehive.content.skill.impl.fishing.Fishable.CRAYFISH =(13435, 13431, 1, 10.0D, -1)
Definition at line 10 of file Fishable.java.
DARK_CRAB
com.runehive.content.skill.impl.fishing.Fishable.DARK_CRAB =(11934, 301, 85, 205.0D, DARK_FISHING_BAIT)
Definition at line 37 of file Fishable.java.
experienceGain
double com.runehive.content.skill.impl.fishing.Fishable.experienceGain private
Definition at line 48 of file Fishable.java.
Referenced by Fishable(), and getExperience().
fish
Map<Integer, Fishable> com.runehive.content.skill.impl.fishing.Fishable.fish = new HashMap<>() static private
Definition at line 49 of file Fishable.java.
Referenced by declare(), and forId().
FROG_SPAWN
com.runehive.content.skill.impl.fishing.Fishable.FROG_SPAWN =(5004, SMALL_FISHING_NET, 33, 75.0D, -1)
Definition at line 21 of file Fishable.java.
HERRING
com.runehive.content.skill.impl.fishing.Fishable.HERRING =(345, FISHING_ROD, 10, 30.0D, FISHING_BAIT)
Definition at line 13 of file Fishable.java.
KARAMBWAN
com.runehive.content.skill.impl.fishing.Fishable.KARAMBWAN =(3142, 3157, 65, 100.0D, -1)
Definition at line 33 of file Fishable.java.
KARAMBWANJI
com.runehive.content.skill.impl.fishing.Fishable.KARAMBWANJI =(3150, SMALL_FISHING_NET, 5, 5.0D, -1)
Definition at line 11 of file Fishable.java.
LAVA_EEL
com.runehive.content.skill.impl.fishing.Fishable.LAVA_EEL =(2148, FISHING_ROD, 53, 30.0D, FISHING_BAIT)
Definition at line 31 of file Fishable.java.
levelRequired
short com.runehive.content.skill.impl.fishing.Fishable.levelRequired private
Definition at line 46 of file Fishable.java.
Referenced by Fishable(), and getRequiredLevel().
LOBSTER
com.runehive.content.skill.impl.fishing.Fishable.LOBSTER =(377, LOBSTER_POT, 40, 90.0D, -1)
Definition at line 26 of file Fishable.java.
MACKEREL
com.runehive.content.skill.impl.fishing.Fishable.MACKEREL =(353, BIG_FISHING_NET, 16, 20.0D, -1)
Definition at line 15 of file Fishable.java.
MANTA_RAY
com.runehive.content.skill.impl.fishing.Fishable.MANTA_RAY =(389, BIG_FISHING_NET, 81, 155.0D, -1)
Definition at line 36 of file Fishable.java.
MONK_FISH
com.runehive.content.skill.impl.fishing.Fishable.MONK_FISH =(7944, SMALL_FISHING_NET, 62, 110.0D, -1)
Definition at line 32 of file Fishable.java.
PIKE
com.runehive.content.skill.impl.fishing.Fishable.PIKE =(349, FISHING_ROD, 25, 60.0D, FISHING_BAIT)
Definition at line 18 of file Fishable.java.
rawFishId
short com.runehive.content.skill.impl.fishing.Fishable.rawFishId private
Definition at line 44 of file Fishable.java.
Referenced by Fishable(), forId(), and getRawFishId().
SALMON
com.runehive.content.skill.impl.fishing.Fishable.SALMON =(331, FLY_FISHING_ROD, 30, 70.0D, 314)
Definition at line 20 of file Fishable.java.
SARDINE
com.runehive.content.skill.impl.fishing.Fishable.SARDINE =(327, FISHING_ROD, 5, 20.0D, FISHING_BAIT)
Definition at line 12 of file Fishable.java.
SEA_TURTLE
com.runehive.content.skill.impl.fishing.Fishable.SEA_TURTLE =(395, -1, 79, 38.0D, -1)
Definition at line 35 of file Fishable.java.
SHARK
com.runehive.content.skill.impl.fishing.Fishable.SHARK =(383, HARPOON, 76, 125.0D, -1)
Definition at line 34 of file Fishable.java.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish().
SHRIMP
com.runehive.content.skill.impl.fishing.Fishable.SHRIMP =(317, SMALL_FISHING_NET, 1, 10.0D, -1)
Definition at line 9 of file Fishable.java.
SLIMY_EEL
com.runehive.content.skill.impl.fishing.Fishable.SLIMY_EEL =(3379, FISHING_ROD, 28, 65.0D, FISHING_BAIT)
Definition at line 19 of file Fishable.java.
SWORD_FISH
com.runehive.content.skill.impl.fishing.Fishable.SWORD_FISH =(371, HARPOON, 50, 100.0D, -1)
Definition at line 28 of file Fishable.java.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish().
SWORD_FISH2
com.runehive.content.skill.impl.fishing.Fishable.SWORD_FISH2 =(371, DRAGON_HARPOON, 50, 100.0D, -1)
Definition at line 29 of file Fishable.java.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish().
toolId
short com.runehive.content.skill.impl.fishing.Fishable.toolId private
Definition at line 45 of file Fishable.java.
Referenced by Fishable(), and getToolId().
TROUT
com.runehive.content.skill.impl.fishing.Fishable.TROUT =(335, FLY_FISHING_ROD, 20, 50.0D, 314)
Definition at line 16 of file Fishable.java.
TUNA
com.runehive.content.skill.impl.fishing.Fishable.TUNA =(359, HARPOON, 35, 80.0D, -1)
Definition at line 22 of file Fishable.java.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish().
TUNA2
com.runehive.content.skill.impl.fishing.Fishable.TUNA2 =(359, DRAGON_HARPOON, 35, 80.0D, -1)
Definition at line 23 of file Fishable.java.
Referenced by com.runehive.content.skill.impl.fishing.FishingAction.fish().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fishing/Fishable.java