RuneHive-Game: com.runehive.content.collectionlog.CollectionLogData Enum Reference
com.runehive.content.collectionlog.CollectionLogData Enum Reference
Public Member Functions
CollectionLogData (CollectionCategory category, String name, int[] items, int... npcId)
CollectionLogData (CollectionCategory category, String name, String counterText, int[] items)
CollectionLogData (CollectionCategory category, String name, String counterText, int[] items, int... npcId)
String getCounterText ()
int[] getItems ()
String getName ()
int[] getNpcIds ()
CollectionCategory getType ()
Static Public Member Functions
static ArrayList< CollectionLogData > getPageList (CollectionLogPage page)
Public Attributes
ABYSSAL_SIRE =(CollectionCategory.BOSSES, "Abyssal Sire", new int[] { 13262, 13273, 7979, 13265, 13274, 13275, 13276, 13277 }, 3030, 3033, 3029, 3032)
BARROWS =(CollectionCategory.BOSSES, "Barrows", "Barrows chests looted", new int[] {4708, 4716, 4724, 4732, 4753, 4745, 4710, 4718, 4726, 4734, 4755, 4747, 4712, 4720, 4728, 4736, 4757, 4749, 4714, 4722, 4730, 4738, 4759, 4751, 12881, 12877, 12873, 12883, 12875, 12879, 12851, 6798})
CALLISTO =(CollectionCategory.BOSSES, "Callisto", "Callisto kills", new int[] {13178, 12603, 11920, 7158}, 6503)
CERBERUS =(CollectionCategory.BOSSES, "Cerberus", "Cerberus Kills", new int[] {13247, 13227, 13229, 13231, 13245, 13233 }, 5862)
CHAMBERS_OF_XERIC =(CollectionCategory.RAIDS, "Chambers of Xeric", "Chests Looted", new int[] {20784, 21000, 21043, 21015, 21018, 21021, 21024, 20997, 21003, 20851, 21079, 21034})
CHAOS_FANATIC =(CollectionCategory.BOSSES, "Chaos Fanatic", "Chaos Fanatic Kills", new int[] {11995, 11926, 11924}, 6619)
COMMANDER_ZILYANA =(CollectionCategory.BOSSES, "Commander Zilyana", "Commander Zilyana Kills", new int[] {12651, 11785, 11814, 11838, 13256, 11818, 11820, 11822}, 2205)
CORPOREAL_BEAST =(CollectionCategory.BOSSES, "Corporeal Beast", "Corporeal Beast Kills", new int[] {12816, 12819, 12823, 12827, 12833, 12829}, 319)
CRAZY_ARCHAEOLOGIST =(CollectionCategory.BOSSES, "Crazy Archaeologist", "Crazy Archaeologist Kills", new int[] {11926, 11924, 11990}, 6618)
EASY_CLUES
GENERAL_GRAARDOR =(CollectionCategory.BOSSES, "General Graardor", "General Graardor Kills", new int[] {12650, 11832, 11834, 11836, 11812, 11818, 11820, 11822}, 2242, 2243, 2244, 2245, 2235, 2240)
KING_BLACK_DRAGON =(CollectionCategory.BOSSES, "King Black Dragon", "King Black Dragon Kills", new int[] {12653, 7980, 11920, 11286}, 239)
KRAKEN =(CollectionCategory.BOSSES, "Kraken", "Kraken Kills", new int[] {12655, 12004, 11907, 12007}, 494)
KREE_ARRA =(CollectionCategory.BOSSES, "Kree'arra", "Kree'arra Kills", new int[] {12649, 11826, 11828, 11830, 11810, 11818, 11820, 11822}, 3162)
KRIL_TSUTSAROTH =(CollectionCategory.BOSSES, "K'ril Tsutsaroth", "K'ril Tsutsaroth Kills", new int[] {12652, 11791, 11824, 11787, 11816, 11818, 11820, 11822}, 3129)
SCORPIA =(CollectionCategory.BOSSES, "Scorpia", "Scorpia Kills", new int[] {13181, 11926, 11924}, 6615)
SHOOTING_STAR =(CollectionCategory.OTHER, "Shooting Star", "Shooting Star Loot", new int[]{25527})
SKOTIZO =(CollectionCategory.BOSSES, "Skotizo", "Skotizo Kills", new int[] {16014, 19701, 21275, 19685, 6571, 19677}, 7286)
VENENATIS =(CollectionCategory.BOSSES, "Venenatis", "Venenatis Kills", new int[] {13177, 12605, 11920, 7158}, 6504)
VETION =(CollectionCategory.BOSSES, "Vet'ion", "Vet'ion Kills", new int[] {13179, 12601, 11920, 7158}, 6611)
VORKATH =(CollectionCategory.BOSSES, "Vorkath", "Vorkath Kills", new int[] {21992, 2425, 11286, 22002, 22106, 22111}, 8060)
WARRIORS_GUILD =(CollectionCategory.MINIGAMES, "Warrior's Guild", "Defenders obtained", new int[]{8844, 8845, 8846, 8847, 8848, 8849, 8850, 12954})
WINTERTODT =(CollectionCategory.MINIGAMES, "Wintertodt", "Wintertodt kills", new int[]{20693, 20716, 20718, 20708, 20704, 20706, 20712, 20710, 20720, 6739})
ZULRAH =(CollectionCategory.BOSSES, "Zulrah", "Zulrah Kills", new int[] { 12921, 13200, 13201, 12936, 12932, 12927, 12922, 12938, 6571, 12934 }, 2042,2043,2044)
Private Attributes
final String counterText
final int[] items
final String name
final int[] npcIds
final CollectionCategory type
Detailed Description
Definition at line 5 of file CollectionLogData.java.
Constructor & Destructor Documentation
CollectionLogData() [1/3]
com.runehive.content.collectionlog.CollectionLogData.CollectionLogData (CollectionCategory category, String name, int[] items, int... npcId)
Definition at line 54 of file CollectionLogData.java.
{
        this.type = category;
        this.name = name;
        this.items = items;
        this.counterText = null;
        this.npcIds = npcId;
    }
References items, and name.
Referenced by getPageList().
CollectionLogData() [2/3]
com.runehive.content.collectionlog.CollectionLogData.CollectionLogData (CollectionCategory category, String name, String counterText, int[] items)
Definition at line 62 of file CollectionLogData.java.
{
        this.type = category;
        this.name = name;
        this.items = items;
        this.counterText = counterText;
        this.npcIds = new int[0];
    }
References counterText, items, and name.
CollectionLogData() [3/3]
com.runehive.content.collectionlog.CollectionLogData.CollectionLogData (CollectionCategory category, String name, String counterText, int[] items, int... npcId)
Definition at line 70 of file CollectionLogData.java.
{
        this.type = category;
        this.name = name;
        this.items = items;
        this.counterText = counterText;
        this.npcIds = npcId;
    }
References counterText, items, and name.
Member Function Documentation
getCounterText()
String com.runehive.content.collectionlog.CollectionLogData.getCounterText ()
Definition at line 104 of file CollectionLogData.java.
{
        return this.counterText;
    }
Referenced by com.runehive.content.collectionlog.CollectionLog.selectLog().
getItems()
int[] com.runehive.content.collectionlog.CollectionLogData.getItems ()
Definition at line 88 of file CollectionLogData.java.
{
        return this.items;
    }
Referenced by com.runehive.content.collectionlog.CollectionLog.logItem(), and com.runehive.content.collectionlog.CollectionLog.selectLog().
getName()
String com.runehive.content.collectionlog.CollectionLogData.getName ()
Definition at line 100 of file CollectionLogData.java.
{
        return this.name;
    }
Referenced by com.runehive.content.collectionlog.CollectionLog.selectLog().
getNpcIds()
int[] com.runehive.content.collectionlog.CollectionLogData.getNpcIds ()
Definition at line 92 of file CollectionLogData.java.
{
        return this.npcIds;
    }
getPageList()
ArrayList< CollectionLogData > com.runehive.content.collectionlog.CollectionLogData.getPageList (CollectionLogPage page) static
Definition at line 78 of file CollectionLogData.java.
{
        ArrayList<CollectionLogData> list = new ArrayList<>();
        for (CollectionLogData data : values()) {
            if (data.getType() == page.getCategory()) {
                list.add(data);
            }
        }
        return list;
    }
References CollectionLogData(), and com.runehive.content.collectionlog.CollectionLogPage.getCategory().
Referenced by com.runehive.content.collectionlog.CollectionLog.loadPage(), com.runehive.content.collectionlog.CollectionLog.selectLogButton(), and com.runehive.content.collectionlog.CollectionLog.sendButtons().
getType()
CollectionCategory com.runehive.content.collectionlog.CollectionLogData.getType ()
Definition at line 96 of file CollectionLogData.java.
{
        return this.type;
    }
Referenced by com.runehive.content.collectionlog.CollectionLog.selectLog().
Member Data Documentation
ABYSSAL_SIRE
com.runehive.content.collectionlog.CollectionLogData.ABYSSAL_SIRE =(CollectionCategory.BOSSES, "Abyssal Sire", new int[] { 13262, 13273, 7979, 13265, 13274, 13275, 13276, 13277 }, 3030, 3033, 3029, 3032)
Definition at line 10 of file CollectionLogData.java.
BARROWS
com.runehive.content.collectionlog.CollectionLogData.BARROWS =(CollectionCategory.BOSSES, "Barrows", "Barrows chests looted", new int[] {4708, 4716, 4724, 4732, 4753, 4745, 4710, 4718, 4726, 4734, 4755, 4747, 4712, 4720, 4728, 4736, 4757, 4749, 4714, 4722, 4730, 4738, 4759, 4751, 12881, 12877, 12873, 12883, 12875, 12879, 12851, 6798})
Definition at line 8 of file CollectionLogData.java.
Referenced by com.runehive.content.activity.impl.barrows.BarrowsUtility.generateRewards(), and com.runehive.content.collectionlog.CollectionLog.open().
CALLISTO
com.runehive.content.collectionlog.CollectionLogData.CALLISTO =(CollectionCategory.BOSSES, "Callisto", "Callisto kills", new int[] {13178, 12603, 11920, 7158}, 6503)
Definition at line 9 of file CollectionLogData.java.
CERBERUS
com.runehive.content.collectionlog.CollectionLogData.CERBERUS =(CollectionCategory.BOSSES, "Cerberus", "Cerberus Kills", new int[] {13247, 13227, 13229, 13231, 13245, 13233 }, 5862)
Definition at line 11 of file CollectionLogData.java.
CHAMBERS_OF_XERIC
com.runehive.content.collectionlog.CollectionLogData.CHAMBERS_OF_XERIC =(CollectionCategory.RAIDS, "Chambers of Xeric", "Chests Looted", new int[] {20784, 21000, 21043, 21015, 21018, 21021, 21024, 20997, 21003, 20851, 21079, 21034})
Definition at line 30 of file CollectionLogData.java.
CHAOS_FANATIC
com.runehive.content.collectionlog.CollectionLogData.CHAOS_FANATIC =(CollectionCategory.BOSSES, "Chaos Fanatic", "Chaos Fanatic Kills", new int[] {11995, 11926, 11924}, 6619)
Definition at line 12 of file CollectionLogData.java.
COMMANDER_ZILYANA
com.runehive.content.collectionlog.CollectionLogData.COMMANDER_ZILYANA =(CollectionCategory.BOSSES, "Commander Zilyana", "Commander Zilyana Kills", new int[] {12651, 11785, 11814, 11838, 13256, 11818, 11820, 11822}, 2205)
Definition at line 13 of file CollectionLogData.java.
CORPOREAL_BEAST
com.runehive.content.collectionlog.CollectionLogData.CORPOREAL_BEAST =(CollectionCategory.BOSSES, "Corporeal Beast", "Corporeal Beast Kills", new int[] {12816, 12819, 12823, 12827, 12833, 12829}, 319)
Definition at line 14 of file CollectionLogData.java.
counterText
final String com.runehive.content.collectionlog.CollectionLogData.counterText private
Definition at line 51 of file CollectionLogData.java.
Referenced by CollectionLogData(), and CollectionLogData().
CRAZY_ARCHAEOLOGIST
com.runehive.content.collectionlog.CollectionLogData.CRAZY_ARCHAEOLOGIST =(CollectionCategory.BOSSES, "Crazy Archaeologist", "Crazy Archaeologist Kills", new int[] {11926, 11924, 11990}, 6618)
Definition at line 15 of file CollectionLogData.java.
EASY_CLUES
com.runehive.content.collectionlog.CollectionLogData.EASY_CLUES
Initial value:
=(CollectionCategory.CLUES, "Easy Clue Scrolls", "Scrolls Opened", new int[] { 1077, 1089, 1107, 1125, 1151, 1165, 1179, 1195, 1217, 1283, 1297, 1313, 1327,
    1341, 1361, 1367, 1426, 8778, 849, 1167, 1095, 1129, 1131, 1063, 1061, 1059, 1167, 329, 333, 1438, 1440, 1442, 1444, 1446, 1448, 1269, 1452, 1454, 1456, 1458, 1462,
    12205, 12207, 12209, 12211, 12213, 12215, 12217, 12219, 12221, 12223, 12225, 12227, 12229, 12231, 12233, 12235, 12237, 12239, 12241, 12243, 2583, 2585, 2587, 2589, 2591, 2593,
    2595, 2597, 3472, 3473, 2635, 2637, 12247, 2633, 2631, 12245, 7386, 7390, 7394, 7396, 7388, 7392, 12449, 12453, 12445, 12447, 12451, 12455, 7364, 7368, 7362, 7366, 7332, 7338,
    7344, 7350, 7356, 10306, 10308, 10310, 10312, 10314, 10404, 10406, 10424, 10426, 10412, 10414, 10432, 10434, 10408, 10410, 10428, 10430, 10316, 10318, 10320, 10322, 10324,
    10392, 10394, 10396, 10398, 10366, 12375, 12297, 10458, 10464, 12193, 12195, 12253, 12255, 12265, 12267, 20217, 20211, 20214, 12249, 12251, 20166, 20205, 20208, 20199,
            20202, 20164})
Definition at line 33 of file CollectionLogData.java.
GENERAL_GRAARDOR
com.runehive.content.collectionlog.CollectionLogData.GENERAL_GRAARDOR =(CollectionCategory.BOSSES, "General Graardor", "General Graardor Kills", new int[] {12650, 11832, 11834, 11836, 11812, 11818, 11820, 11822}, 2242, 2243, 2244, 2245, 2235, 2240)
Definition at line 16 of file CollectionLogData.java.
items
final int [] com.runehive.content.collectionlog.CollectionLogData.items private
Definition at line 50 of file CollectionLogData.java.
Referenced by CollectionLogData(), CollectionLogData(), and CollectionLogData().
KING_BLACK_DRAGON
com.runehive.content.collectionlog.CollectionLogData.KING_BLACK_DRAGON =(CollectionCategory.BOSSES, "King Black Dragon", "King Black Dragon Kills", new int[] {12653, 7980, 11920, 11286}, 239)
Definition at line 18 of file CollectionLogData.java.
KRAKEN
com.runehive.content.collectionlog.CollectionLogData.KRAKEN =(CollectionCategory.BOSSES, "Kraken", "Kraken Kills", new int[] {12655, 12004, 11907, 12007}, 494)
Definition at line 19 of file CollectionLogData.java.
KREE_ARRA
com.runehive.content.collectionlog.CollectionLogData.KREE_ARRA =(CollectionCategory.BOSSES, "Kree'arra", "Kree'arra Kills", new int[] {12649, 11826, 11828, 11830, 11810, 11818, 11820, 11822}, 3162)
Definition at line 20 of file CollectionLogData.java.
KRIL_TSUTSAROTH
com.runehive.content.collectionlog.CollectionLogData.KRIL_TSUTSAROTH =(CollectionCategory.BOSSES, "K'ril Tsutsaroth", "K'ril Tsutsaroth Kills", new int[] {12652, 11791, 11824, 11787, 11816, 11818, 11820, 11822}, 3129)
Definition at line 21 of file CollectionLogData.java.
name
final String com.runehive.content.collectionlog.CollectionLogData.name private
Definition at line 49 of file CollectionLogData.java.
Referenced by CollectionLogData(), CollectionLogData(), and CollectionLogData().
npcIds
final int [] com.runehive.content.collectionlog.CollectionLogData.npcIds private
Definition at line 52 of file CollectionLogData.java.
SCORPIA
com.runehive.content.collectionlog.CollectionLogData.SCORPIA =(CollectionCategory.BOSSES, "Scorpia", "Scorpia Kills", new int[] {13181, 11926, 11924}, 6615)
Definition at line 22 of file CollectionLogData.java.
SHOOTING_STAR
com.runehive.content.collectionlog.CollectionLogData.SHOOTING_STAR =(CollectionCategory.OTHER, "Shooting Star", "Shooting Star Loot", new int[]{25527})
Definition at line 45 of file CollectionLogData.java.
SKOTIZO
com.runehive.content.collectionlog.CollectionLogData.SKOTIZO =(CollectionCategory.BOSSES, "Skotizo", "Skotizo Kills", new int[] {16014, 19701, 21275, 19685, 6571, 19677}, 7286)
Definition at line 23 of file CollectionLogData.java.
type
final CollectionCategory com.runehive.content.collectionlog.CollectionLogData.type private
Definition at line 48 of file CollectionLogData.java.
VENENATIS
com.runehive.content.collectionlog.CollectionLogData.VENENATIS =(CollectionCategory.BOSSES, "Venenatis", "Venenatis Kills", new int[] {13177, 12605, 11920, 7158}, 6504)
Definition at line 24 of file CollectionLogData.java.
VETION
com.runehive.content.collectionlog.CollectionLogData.VETION =(CollectionCategory.BOSSES, "Vet'ion", "Vet'ion Kills", new int[] {13179, 12601, 11920, 7158}, 6611)
Definition at line 25 of file CollectionLogData.java.
VORKATH
com.runehive.content.collectionlog.CollectionLogData.VORKATH =(CollectionCategory.BOSSES, "Vorkath", "Vorkath Kills", new int[] {21992, 2425, 11286, 22002, 22106, 22111}, 8060)
Definition at line 26 of file CollectionLogData.java.
WARRIORS_GUILD
com.runehive.content.collectionlog.CollectionLogData.WARRIORS_GUILD =(CollectionCategory.MINIGAMES, "Warrior's Guild", "Defenders obtained", new int[]{8844, 8845, 8846, 8847, 8848, 8849, 8850, 12954})
Definition at line 42 of file CollectionLogData.java.
Referenced by com.runehive.content.activity.impl.warriorguild.WarriorGuild.pickupItem().
WINTERTODT
com.runehive.content.collectionlog.CollectionLogData.WINTERTODT =(CollectionCategory.MINIGAMES, "Wintertodt", "Wintertodt kills", new int[]{20693, 20716, 20718, 20708, 20704, 20706, 20712, 20710, 20720, 6739})
Definition at line 43 of file CollectionLogData.java.
Referenced by com.runehive.content.wintertodt.Wintertodt.award(), and com.runehive.content.pet.Pets.onObtain().
ZULRAH
com.runehive.content.collectionlog.CollectionLogData.ZULRAH =(CollectionCategory.BOSSES, "Zulrah", "Zulrah Kills", new int[] { 12921, 13200, 13201, 12936, 12932, 12927, 12922, 12938, 6571, 12934 }, 2042,2043,2044)
Definition at line 27 of file CollectionLogData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/collectionlog/CollectionLogData.java