RuneHive-Game: com.runehive.content.skill.impl.smithing.SmeltingData Enum Reference
com.runehive.content.skill.impl.smithing.SmeltingData Enum Reference
The enumerated type whose elements represent definitions for each smeltable bar.
Public Member Functions
SmeltingData (int buttonId, Item[] required, Item[] produced, double experience, int requirement)
Constructs a new SmeltingData enumerator.
SmeltingData (int buttonId, SmeltingData definition, int amount)
Constructs a new SmeltingData enumerator.
Static Public Member Functions
static Optional< SmeltingData > getDefinition (int buttonId)
Searches for a match for the internal button identification.
static Optional< SmeltingData > getDefinitionByItem (int itemId)
Searches for a match for the internal required items.
static SmeltingData getSmeltData (int itemId)
Public Attributes
ADAMANT =(7446, new Item[]{new Item(449), new Item(453, 6)}, new Item[]{new Item(2361)}, 37.5, 70)
ADAMANT_10 =(7443, ADAMANT, 10)
ADAMANT_5 =(7444, ADAMANT, 5)
ADAMANT_X =(7442, ADAMANT, -1)
final int amount
The amount we're producing.
BRONZE =(3987, new Item[]{new Item(438), new Item(436)}, new Item[]{new Item(2349)}, 6.25, 1)
BRONZE_10 =(2807, BRONZE, 10)
BRONZE_5 =(3986, BRONZE, 5)
BRONZE_X =(2414, BRONZE, -1)
final double experience
The experience gained upon smelting one bar.
GOLD =(4003, new Item[]{new Item(444)}, new Item[]{new Item(2357)}, 22.5, 40)
GOLD_10 =(4001, GOLD, 10)
GOLD_5 =(4002, GOLD, 5)
GOLD_X =(4000, GOLD, -1)
IRON =(3991, new Item[]{new Item(440)}, new Item[]{new Item(2351)}, 12.5, 15)
IRON_10 =(3989, IRON, 10)
IRON_5 =(3990, IRON, 5)
IRON_X =(3988, IRON, -1)
MITHRIL =(7441, new Item[]{new Item(447), new Item(453, 4)}, new Item[]{new Item(2359)}, 30, 50)
MITHRIL_10 =(6397, MITHRIL, 10)
MITHRIL_5 =(7440, MITHRIL, 5)
MITHRIL_X =(4158, MITHRIL, -1)
final Item[] produced
he produced items for smelting the required items.
final Item[] required
The required items to smelt this bar.
final int requirement
The requirement required to smelt the bar.
RUNITE =(7450, new Item[]{new Item(451), new Item(453, 8)}, new Item[]{new Item(2363)}, 50, 85)
RUNITE_10 =(7448, RUNITE, 10)
RUNITE_5 =(7449, RUNITE, 5)
RUNITE_X =(7447, RUNITE, -1)
SILVER =(3995, new Item[]{new Item(442)}, new Item[]{new Item(2355)}, 13.67, 20)
SILVER_10 =(3993, SILVER, 10)
SILVER_5 =(3994, SILVER, 5)
SILVER_X =(3992, SILVER, -1)
STEEL =(3999, new Item[]{new Item(440), new Item(453, 2)}, new Item[]{new Item(2353)}, 17.5, 30)
STEEL_10 =(3997, STEEL, 10)
STEEL_5 =(3998, STEEL, 5)
STEEL_X =(3996, STEEL, -1)
Private Attributes
final int buttonId
The button identification.
Static Private Attributes
static final ImmutableSet< SmeltingData > VALUES = Sets.immutableEnumSet(EnumSet.allOf(SmeltingData.class))
Caches our enum values.
Detailed Description
The enumerated type whose elements represent definitions for each smeltable bar.
Definition at line 15 of file SmeltingData.java.
Constructor & Destructor Documentation
SmeltingData() [1/2]
com.runehive.content.skill.impl.smithing.SmeltingData.SmeltingData (int buttonId, Item[] required, Item[] produced, double experience, int requirement)
Constructs a new SmeltingData enumerator.
Definition at line 71 of file SmeltingData.java.
{
        this.buttonId = buttonId;
        this.required = required;
        this.produced = produced;
        this.experience = experience;
        this.requirement = requirement;
        this.amount = 1;
    }
References buttonId, experience, produced, required, and requirement.
Referenced by getDefinitionByItem(), getSmeltData(), and SmeltingData().
SmeltingData() [2/2]
com.runehive.content.skill.impl.smithing.SmeltingData.SmeltingData (int buttonId, SmeltingData definition, int amount)
Constructs a new SmeltingData enumerator.
Definition at line 81 of file SmeltingData.java.
{
        this.buttonId = buttonId;
        this.required = definition.required;
        this.produced = definition.produced;
        this.experience = definition.experience;
        this.requirement = definition.requirement;
        this.amount = amount;
    }
References amount, buttonId, experience, produced, required, requirement, and SmeltingData().
Member Function Documentation
getDefinition()
Optional< SmeltingData > com.runehive.content.skill.impl.smithing.SmeltingData.getDefinition (int buttonId) static
Searches for a match for the internal button identification.
Definition at line 91 of file SmeltingData.java.
{
        return VALUES.stream().filter(def -> def.buttonId == buttonId).findAny();
    }
References buttonId, and VALUES.
Referenced by com.runehive.content.skill.impl.smithing.Smelting.smelt().
getDefinitionByItem()
Optional< SmeltingData > com.runehive.content.skill.impl.smithing.SmeltingData.getDefinitionByItem (int itemId) static
Searches for a match for the internal required items.
Definition at line 96 of file SmeltingData.java.
{
        for (SmeltingData data : VALUES) {
            for (Item item : data.required) {
                if (item.getId() == itemId) {
                    return Optional.of(data);
                }
            }
        }
        return Optional.empty();
    }
References com.runehive.game.world.items.Item.getId(), SmeltingData(), and VALUES.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute().
getSmeltData()
SmeltingData com.runehive.content.skill.impl.smithing.SmeltingData.getSmeltData (int itemId) static
Definition at line 107 of file SmeltingData.java.
{
        switch(itemId) {
            case 438:
            case 436:
                return BRONZE;
            case 440:
                return IRON;
            case 442:
                return SILVER;
            case 444:
                return GOLD;
            case 447:
                return MITHRIL;
            case 449:
                return ADAMANT;
            case 451:
                return RUNITE;
        }
        return null;
    }
References ADAMANT, BRONZE, GOLD, IRON, MITHRIL, RUNITE, SILVER, and SmeltingData().
Referenced by com.runehive.content.skill.impl.mining.MiningAction.mine().
Member Data Documentation
ADAMANT
com.runehive.content.skill.impl.smithing.SmeltingData.ADAMANT =(7446, new Item[]{new Item(449), new Item(453, 6)}, new Item[]{new Item(2361)}, 37.5, 70)
Definition at line 40 of file SmeltingData.java.
Referenced by getSmeltData().
ADAMANT_10
com.runehive.content.skill.impl.smithing.SmeltingData.ADAMANT_10 =(7443, ADAMANT, 10)
Definition at line 42 of file SmeltingData.java.
ADAMANT_5
com.runehive.content.skill.impl.smithing.SmeltingData.ADAMANT_5 =(7444, ADAMANT, 5)
Definition at line 41 of file SmeltingData.java.
ADAMANT_X
com.runehive.content.skill.impl.smithing.SmeltingData.ADAMANT_X =(7442, ADAMANT, -1)
Definition at line 43 of file SmeltingData.java.
amount
final int com.runehive.content.skill.impl.smithing.SmeltingData.amount
The amount we're producing.
Definition at line 68 of file SmeltingData.java.
Referenced by SmeltingData().
BRONZE
com.runehive.content.skill.impl.smithing.SmeltingData.BRONZE =(3987, new Item[]{new Item(438), new Item(436)}, new Item[]{new Item(2349)}, 6.25, 1)
Definition at line 16 of file SmeltingData.java.
Referenced by getSmeltData().
BRONZE_10
com.runehive.content.skill.impl.smithing.SmeltingData.BRONZE_10 =(2807, BRONZE, 10)
Definition at line 18 of file SmeltingData.java.
BRONZE_5
com.runehive.content.skill.impl.smithing.SmeltingData.BRONZE_5 =(3986, BRONZE, 5)
Definition at line 17 of file SmeltingData.java.
BRONZE_X
com.runehive.content.skill.impl.smithing.SmeltingData.BRONZE_X =(2414, BRONZE, -1)
Definition at line 19 of file SmeltingData.java.
buttonId
final int com.runehive.content.skill.impl.smithing.SmeltingData.buttonId private
The button identification.
Definition at line 53 of file SmeltingData.java.
Referenced by getDefinition(), SmeltingData(), and SmeltingData().
experience
final double com.runehive.content.skill.impl.smithing.SmeltingData.experience
The experience gained upon smelting one bar.
Definition at line 62 of file SmeltingData.java.
Referenced by SmeltingData(), and SmeltingData().
GOLD
com.runehive.content.skill.impl.smithing.SmeltingData.GOLD =(4003, new Item[]{new Item(444)}, new Item[]{new Item(2357)}, 22.5, 40)
Definition at line 32 of file SmeltingData.java.
Referenced by getSmeltData().
GOLD_10
com.runehive.content.skill.impl.smithing.SmeltingData.GOLD_10 =(4001, GOLD, 10)
Definition at line 34 of file SmeltingData.java.
GOLD_5
com.runehive.content.skill.impl.smithing.SmeltingData.GOLD_5 =(4002, GOLD, 5)
Definition at line 33 of file SmeltingData.java.
GOLD_X
com.runehive.content.skill.impl.smithing.SmeltingData.GOLD_X =(4000, GOLD, -1)
Definition at line 35 of file SmeltingData.java.
IRON
com.runehive.content.skill.impl.smithing.SmeltingData.IRON =(3991, new Item[]{new Item(440)}, new Item[]{new Item(2351)}, 12.5, 15)
Definition at line 20 of file SmeltingData.java.
Referenced by getSmeltData().
IRON_10
com.runehive.content.skill.impl.smithing.SmeltingData.IRON_10 =(3989, IRON, 10)
Definition at line 22 of file SmeltingData.java.
IRON_5
com.runehive.content.skill.impl.smithing.SmeltingData.IRON_5 =(3990, IRON, 5)
Definition at line 21 of file SmeltingData.java.
IRON_X
com.runehive.content.skill.impl.smithing.SmeltingData.IRON_X =(3988, IRON, -1)
Definition at line 23 of file SmeltingData.java.
MITHRIL
com.runehive.content.skill.impl.smithing.SmeltingData.MITHRIL =(7441, new Item[]{new Item(447), new Item(453, 4)}, new Item[]{new Item(2359)}, 30, 50)
Definition at line 36 of file SmeltingData.java.
Referenced by getSmeltData().
MITHRIL_10
com.runehive.content.skill.impl.smithing.SmeltingData.MITHRIL_10 =(6397, MITHRIL, 10)
Definition at line 38 of file SmeltingData.java.
MITHRIL_5
com.runehive.content.skill.impl.smithing.SmeltingData.MITHRIL_5 =(7440, MITHRIL, 5)
Definition at line 37 of file SmeltingData.java.
MITHRIL_X
com.runehive.content.skill.impl.smithing.SmeltingData.MITHRIL_X =(4158, MITHRIL, -1)
Definition at line 39 of file SmeltingData.java.
produced
final Item [] com.runehive.content.skill.impl.smithing.SmeltingData.produced
he produced items for smelting the required items.
Definition at line 59 of file SmeltingData.java.
Referenced by com.runehive.content.skill.impl.mining.MiningAction.mine(), SmeltingData(), and SmeltingData().
required
final Item [] com.runehive.content.skill.impl.smithing.SmeltingData.required
The required items to smelt this bar.
Definition at line 56 of file SmeltingData.java.
Referenced by SmeltingData(), and SmeltingData().
requirement
final int com.runehive.content.skill.impl.smithing.SmeltingData.requirement
The requirement required to smelt the bar.
Definition at line 65 of file SmeltingData.java.
Referenced by SmeltingData(), and SmeltingData().
RUNITE
com.runehive.content.skill.impl.smithing.SmeltingData.RUNITE =(7450, new Item[]{new Item(451), new Item(453, 8)}, new Item[]{new Item(2363)}, 50, 85)
Definition at line 44 of file SmeltingData.java.
Referenced by getSmeltData().
RUNITE_10
com.runehive.content.skill.impl.smithing.SmeltingData.RUNITE_10 =(7448, RUNITE, 10)
Definition at line 46 of file SmeltingData.java.
RUNITE_5
com.runehive.content.skill.impl.smithing.SmeltingData.RUNITE_5 =(7449, RUNITE, 5)
Definition at line 45 of file SmeltingData.java.
RUNITE_X
com.runehive.content.skill.impl.smithing.SmeltingData.RUNITE_X =(7447, RUNITE, -1)
Definition at line 47 of file SmeltingData.java.
SILVER
com.runehive.content.skill.impl.smithing.SmeltingData.SILVER =(3995, new Item[]{new Item(442)}, new Item[]{new Item(2355)}, 13.67, 20)
Definition at line 24 of file SmeltingData.java.
Referenced by getSmeltData().
SILVER_10
com.runehive.content.skill.impl.smithing.SmeltingData.SILVER_10 =(3993, SILVER, 10)
Definition at line 26 of file SmeltingData.java.
SILVER_5
com.runehive.content.skill.impl.smithing.SmeltingData.SILVER_5 =(3994, SILVER, 5)
Definition at line 25 of file SmeltingData.java.
SILVER_X
com.runehive.content.skill.impl.smithing.SmeltingData.SILVER_X =(3992, SILVER, -1)
Definition at line 27 of file SmeltingData.java.
STEEL
com.runehive.content.skill.impl.smithing.SmeltingData.STEEL =(3999, new Item[]{new Item(440), new Item(453, 2)}, new Item[]{new Item(2353)}, 17.5, 30)
Definition at line 28 of file SmeltingData.java.
STEEL_10
com.runehive.content.skill.impl.smithing.SmeltingData.STEEL_10 =(3997, STEEL, 10)
Definition at line 30 of file SmeltingData.java.
STEEL_5
com.runehive.content.skill.impl.smithing.SmeltingData.STEEL_5 =(3998, STEEL, 5)
Definition at line 29 of file SmeltingData.java.
STEEL_X
com.runehive.content.skill.impl.smithing.SmeltingData.STEEL_X =(3996, STEEL, -1)
Definition at line 31 of file SmeltingData.java.
VALUES
final ImmutableSet<SmeltingData> com.runehive.content.skill.impl.smithing.SmeltingData.VALUES = Sets.immutableEnumSet(EnumSet.allOf(SmeltingData.class)) static private
Caches our enum values.
Definition at line 50 of file SmeltingData.java.
Referenced by getDefinition(), and getDefinitionByItem().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/smithing/SmeltingData.java