RuneHive-Game: com.runehive.net.packet.out.SendWidget.WidgetType Enum Reference
com.runehive.net.packet.out.SendWidget.WidgetType Enum Reference
Public Member Functions
WidgetType (int icon)
Public Attributes
ANTI_FIRE =(1)
CLAN =(6)
FROZEN =(3)
POISON =(1)
SKULL =(5)
STUN =(7)
TELEBLOCK =(4)
VENGEANCE =(2)
Private Attributes
final int icon
Detailed Description
Definition at line 24 of file SendWidget.java.
Constructor & Destructor Documentation
WidgetType()
com.runehive.net.packet.out.SendWidget.WidgetType.WidgetType (int icon)
Definition at line 35 of file SendWidget.java.
{
            this.icon = icon;
        }
References icon.
Member Data Documentation
ANTI_FIRE
com.runehive.net.packet.out.SendWidget.WidgetType.ANTI_FIRE =(1)
Definition at line 25 of file SendWidget.java.
CLAN
com.runehive.net.packet.out.SendWidget.WidgetType.CLAN =(6)
Definition at line 30 of file SendWidget.java.
FROZEN
com.runehive.net.packet.out.SendWidget.WidgetType.FROZEN =(3)
Definition at line 27 of file SendWidget.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.Vorkath.FrozenSpecial.hit().
icon
final int com.runehive.net.packet.out.SendWidget.WidgetType.icon private
Definition at line 34 of file SendWidget.java.
Referenced by WidgetType().
POISON
com.runehive.net.packet.out.SendWidget.WidgetType.POISON =(1)
Definition at line 32 of file SendWidget.java.
SKULL
com.runehive.net.packet.out.SendWidget.WidgetType.SKULL =(5)
Definition at line 29 of file SendWidget.java.
STUN
com.runehive.net.packet.out.SendWidget.WidgetType.STUN =(7)
Definition at line 31 of file SendWidget.java.
TELEBLOCK
com.runehive.net.packet.out.SendWidget.WidgetType.TELEBLOCK =(4)
Definition at line 28 of file SendWidget.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect.apply(), com.runehive.game.task.impl.TeleblockTask.onCancel(), com.runehive.game.world.entity.mob.player.PlayerAssistant.setEffects(), and com.runehive.game.world.entity.mob.player.Player.teleblock().
VENGEANCE
com.runehive.net.packet.out.SendWidget.WidgetType.VENGEANCE =(2)
Definition at line 26 of file SendWidget.java.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute().
The documentation for this enum was generated from the following file:
java/com/runehive/net/packet/out/SendWidget.java