RuneHive-Game: com.runehive.game.world.entity.combat.attack.FightStyle Enum Reference
com.runehive.game.world.entity.combat.attack.FightStyle Enum Reference
The enumerated type whose elements represent the fighting styles.
Public Member Functions
FightStyle (int accuracyIncrease, int strengthIncrease, int defensiveIncrease)
Constructs a new FightStyle element.
int getAccuracyIncrease ()
int getDefensiveIncrease ()
int getStrengthIncrease ()
Public Attributes
ACCURATE =(3, 0, 0)
AGGRESSIVE =(0, 3, 0)
CONTROLLED =(1, 1, 1)
DEFENSIVE =(0, 0, 3)
Private Attributes
int accuracyIncrease
The increase to accuracy.
int defensiveIncrease
The increase to defense.
int strengthIncrease
The increase to strength.
Detailed Description
The enumerated type whose elements represent the fighting styles.
Author
lare96 http://github.com/lare96
Michael | Chex
Definition at line 9 of file FightStyle.java.
Constructor & Destructor Documentation
FightStyle()
com.runehive.game.world.entity.combat.attack.FightStyle.FightStyle (int accuracyIncrease, int strengthIncrease, int defensiveIncrease)
Constructs a new FightStyle element.
Definition at line 25 of file FightStyle.java.
{
        this.accuracyIncrease = accuracyIncrease;
        this.strengthIncrease = strengthIncrease;
        this.defensiveIncrease = defensiveIncrease;
    }
References accuracyIncrease, defensiveIncrease, and strengthIncrease.
Member Function Documentation
getAccuracyIncrease()
int com.runehive.game.world.entity.combat.attack.FightStyle.getAccuracyIncrease ()
Returns
the accuracy increase
Definition at line 32 of file FightStyle.java.
{
        return accuracyIncrease;
    }
References accuracyIncrease.
Referenced by com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAccuracy(), and com.runehive.game.world.entity.combat.formula.RangedFormula.modifyAccuracy().
getDefensiveIncrease()
int com.runehive.game.world.entity.combat.attack.FightStyle.getDefensiveIncrease ()
Returns
the defense increase
Definition at line 42 of file FightStyle.java.
{
        return defensiveIncrease;
    }
References defensiveIncrease.
Referenced by com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDefensive(), and com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDefensive().
getStrengthIncrease()
int com.runehive.game.world.entity.combat.attack.FightStyle.getStrengthIncrease ()
Returns
the strength increase
Definition at line 37 of file FightStyle.java.
{
        return strengthIncrease;
    }
References strengthIncrease.
Referenced by com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyAggressive().
Member Data Documentation
accuracyIncrease
int com.runehive.game.world.entity.combat.attack.FightStyle.accuracyIncrease private
The increase to accuracy.
Definition at line 16 of file FightStyle.java.
Referenced by FightStyle(), and getAccuracyIncrease().
ACCURATE
com.runehive.game.world.entity.combat.attack.FightStyle.ACCURATE =(3, 0, 0)
Definition at line 10 of file FightStyle.java.
Referenced by com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStyleBonus(), and com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getStyleBonus().
AGGRESSIVE
com.runehive.game.world.entity.combat.attack.FightStyle.AGGRESSIVE =(0, 3, 0)
Definition at line 11 of file FightStyle.java.
Referenced by com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getStyleBonus().
CONTROLLED
com.runehive.game.world.entity.combat.attack.FightStyle.CONTROLLED =(1, 1, 1)
Definition at line 13 of file FightStyle.java.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), and com.runehive.content.overrides.Overrides.getFightType().
DEFENSIVE
com.runehive.game.world.entity.combat.attack.FightStyle.DEFENSIVE =(0, 0, 3)
Definition at line 12 of file FightStyle.java.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), and com.runehive.content.overrides.Overrides.getFightType().
defensiveIncrease
int com.runehive.game.world.entity.combat.attack.FightStyle.defensiveIncrease private
The increase to defense.
Definition at line 22 of file FightStyle.java.
Referenced by FightStyle(), and getDefensiveIncrease().
strengthIncrease
int com.runehive.game.world.entity.combat.attack.FightStyle.strengthIncrease private
The increase to strength.
Definition at line 19 of file FightStyle.java.
Referenced by FightStyle(), and getStrengthIncrease().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/FightStyle.java