RuneHive-Game: com.runehive.content.activity.impl.duelarena.DuelRule Enum Reference
com.runehive.content.activity.impl.duelarena.DuelRule Enum Reference
Classes
interface RuleCondition
Public Member Functions
boolean canSet (Player player)
DuelRule (int button, int value, int slot, RuleCondition condition)
Creates a new DuelRule.
DuelRule (int button, int value, RuleCondition condition)
Creates a new DuelRule.
int getButtonId ()
RuleCondition getCondition ()
int getSlot ()
int getValue ()
boolean set (Player player, boolean showMessage)
Static Public Member Functions
static Optional< DuelRule > forButton (int button)
static int inventorySlotsRequired (Player player, DuelRules rules, DuelRule rule)
static void showRules (DuelArenaActivity activity, Player player, Player other)
static void validateEquipmentRules (Player player)
Public Attributes
LOCK_ITEMS
NO_AMMO =(13816, 134217728, Equipment.ARROWS_SLOT, (player, rules) -> true)
NO_BODY =(13818, 262144, Equipment.CHEST_SLOT,(player, rules) -> true)
NO_BOOTS =(13822, 16777216, Equipment.FEET_SLOT, (player, rules) -> true)
NO_CAPE =(13814, 32768, Equipment.CAPE_SLOT, (player, rules) -> true)
NO_DRINKS =(31041, 638, (player, rules) -> true)
NO_FOOD =(31042, 639, (player, rules) -> true)
NO_FORFEIT
NO_GLOVES =(13823, 8388608, Equipment.HANDS_SLOT, (player, rules) -> true)
NO_HEAD =(13813, 16384, Equipment.HELM_SLOT, (player, rules) -> true)
NO_LEGS =(13820, 2097152, Equipment.LEGS_SLOT, (player, rules) -> true)
NO_MAGIC
NO_MELEE
NO_MOVEMENT
NO_NECKLACE =(13815, 65536, Equipment.AMULET_SLOT, (player, rules) -> true)
NO_PRAYER =(31040, 637, (player, rules) -> true)
NO_RANGED
NO_RINGS =(13821, 67108864, Equipment.RING_SLOT, (player, rules) -> true)
NO_SHIELD =(13819, 524288, Equipment.SHIELD_SLOT, (player, rules) -> true)
NO_SPECIAL_ATTACK =(31037, 634, (player, rules) -> true)
NO_WEAPON
OBSTACLES
ONLY_FUN_WEAPONS
ONLY_WHIP_DDS
Static Public Attributes
static final ImmutableSet< DuelRule > EQUIPMENT_RULES = ImmutableSet.of(NO_HEAD, NO_CAPE, NO_NECKLACE, NO_AMMO, NO_WEAPON, NO_BODY, NO_SHIELD, NO_LEGS, NO_GLOVES, NO_BOOTS, NO_RINGS)
Private Attributes
final int button
The button for this rule.
final RuleCondition condition
The condition for this rule.
final int slot
The equipment slot for this rule.
final int value
The value for the config.
Detailed Description
Definition at line 17 of file DuelRule.java.
Constructor & Destructor Documentation
DuelRule() [1/2]
com.runehive.content.activity.impl.duelarena.DuelRule.DuelRule (int button, int value, RuleCondition condition)
Creates a new DuelRule.
Parameters
button The button for this rule.
value The config id for this rule.
condition The condition for this rule.
Definition at line 212 of file DuelRule.java.
{
        this(button, value, -1, condition);
    }
References button, condition, and value.
Referenced by forButton(), inventorySlotsRequired(), showRules(), and validateEquipmentRules().
DuelRule() [2/2]
com.runehive.content.activity.impl.duelarena.DuelRule.DuelRule (int button, int value, int slot, RuleCondition condition)
Creates a new DuelRule.
Parameters
button The button for this rule.
value The config id for this rule.
slot The equipment slot for this rule.
condition The condition for this rule.
Definition at line 224 of file DuelRule.java.
{
        this.button = button;
        this.value = value;
        this.slot = slot;
        this.condition = condition;
    }
References button, condition, and value.
Member Function Documentation
canSet()
boolean com.runehive.content.activity.impl.duelarena.DuelRule.canSet (Player player)
Definition at line 242 of file DuelRule.java.
{
        if (!Activity.search(player, DuelArenaActivity.class).isPresent()) {
            return false;
        }
        DuelArenaActivity activity = Activity.search(player, DuelArenaActivity.class).get();
        final DuelRules rules = activity.rules;
        if (!condition.canSelect(player, rules)) {
            return false;
        }
        Player other = activity.opponent;
        if (inventorySlotsRequired(player, rules, this) > player.inventory.getFreeSlots()) {
            return false;
        }
        if (inventorySlotsRequired(other, rules, this) > other.inventory.getFreeSlots()) {
            return false;
        }
        return true;
    }
References condition, com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), com.runehive.game.world.entity.mob.player.Player.inventory, inventorySlotsRequired(), and com.runehive.content.activity.Activity.search().
Referenced by validateEquipmentRules().
forButton()
Optional< DuelRule > com.runehive.content.activity.impl.duelarena.DuelRule.forButton (int button) static
Definition at line 233 of file DuelRule.java.
{
        for (DuelRule rules : values()) {
            if (rules.getButtonId() == button) {
                return Optional.of(rules);
            }
        }
        return Optional.empty();
    }
References button, and DuelRule().
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onButtonClick().
getButtonId()
int com.runehive.content.activity.impl.duelarena.DuelRule.getButtonId ()
Returns
the buttonId
Definition at line 442 of file DuelRule.java.
{
        return button;
    }
References button.
Referenced by set().
getCondition()
RuleCondition com.runehive.content.activity.impl.duelarena.DuelRule.getCondition ()
Returns
the condition
Definition at line 463 of file DuelRule.java.
{
        return condition;
    }
References condition.
getSlot()
int com.runehive.content.activity.impl.duelarena.DuelRule.getSlot ()
Returns
the slot
Definition at line 456 of file DuelRule.java.
{
        return slot;
    }
getValue()
int com.runehive.content.activity.impl.duelarena.DuelRule.getValue ()
Returns
the value
Definition at line 449 of file DuelRule.java.
{
        return value;
    }
References value.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRules.flag(), set(), and com.runehive.content.activity.impl.duelarena.DuelRules.unflag().
inventorySlotsRequired()
int com.runehive.content.activity.impl.duelarena.DuelRule.inventorySlotsRequired (Player player, DuelRules rules, DuelRule rule) static
Definition at line 339 of file DuelRule.java.
{
        int required = 0;
        EnumSet<DuelRule> tempRules = EnumSet.copyOf(rules.getFlags());
        tempRules.add(rule);
        if (player.equipment.hasHead()) {
            if (tempRules.contains(DuelRule.NO_HEAD)) {
                required++;
            }
        }
        if (player.equipment.hasAmulet()) {
            if (tempRules.contains(DuelRule.NO_NECKLACE)) {
                required++;
            }
        }
        if (player.equipment.hasWeapon()) {
            Item item = player.equipment.get(Equipment.WEAPON_SLOT);
            if (item != null) {
                String name = item.getName().toLowerCase();
                if (tempRules.contains(DuelRule.NO_WEAPON)) {
                    required++;
                }
                if (tempRules.contains(DuelRule.ONLY_WHIP_DDS)) {
                    if (!(name.contains("whip") || name.contains("abyssal tentacle") || name.contains("dragon dagger"))) {
                        required++;
                    }
                }
            }
        }
        if (player.equipment.hasCape()) {
            if (tempRules.contains(DuelRule.NO_CAPE)) {
                required++;
            }
        }
        if (player.equipment.hasAmmo()) {
            if (tempRules.contains(DuelRule.NO_AMMO)) {
                required++;
            }
        }
        if (player.equipment.hasChest()) {
            if (tempRules.contains(DuelRule.NO_BODY)) {
                required++;
            }
        }
        if (tempRules.contains(DuelRule.NO_SHIELD)) {
            if (player.equipment.hasShield()) {
                required++;
            }
            Item weapon = player.equipment.get(Equipment.WEAPON_SLOT);
            if (weapon != null) {
                ItemDefinition def = ItemDefinition.get(weapon.getId());
                if (def != null && def.isTwoHanded()) {
                    required++;
                }
            }
        }
        if (player.equipment.hasLegs()) {
            if (tempRules.contains(DuelRule.NO_LEGS)) {
                required++;
            }
        }
        if (player.equipment.hasHands()) {
            if (tempRules.contains(DuelRule.NO_GLOVES)) {
                required++;
            }
        }
        if (player.equipment.hasFeet()) {
            if (tempRules.contains(DuelRule.NO_BOOTS)) {
                required++;
            }
        }
        if (player.equipment.hasRing()) {
            if (tempRules.contains(DuelRule.NO_RINGS)) {
                required++;
            }
        }
        tempRules.clear();
        return required;
    }
References DuelRule(), com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.items.containers.ItemContainer.get(), com.runehive.game.world.items.ItemDefinition.get(), com.runehive.content.activity.impl.duelarena.DuelRules.getFlags(), com.runehive.game.world.items.Item.getId(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.items.containers.equipment.Equipment.hasAmmo(), com.runehive.game.world.items.containers.equipment.Equipment.hasAmulet(), com.runehive.game.world.items.containers.equipment.Equipment.hasCape(), com.runehive.game.world.items.containers.equipment.Equipment.hasChest(), com.runehive.game.world.items.containers.equipment.Equipment.hasFeet(), com.runehive.game.world.items.containers.equipment.Equipment.hasHands(), com.runehive.game.world.items.containers.equipment.Equipment.hasHead(), com.runehive.game.world.items.containers.equipment.Equipment.hasLegs(), com.runehive.game.world.items.containers.equipment.Equipment.hasRing(), com.runehive.game.world.items.containers.equipment.Equipment.hasShield(), com.runehive.game.world.items.containers.equipment.Equipment.hasWeapon(), and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by canSet(), and set().
set()
boolean com.runehive.content.activity.impl.duelarena.DuelRule.set (Player player, boolean showMessage)
Definition at line 295 of file DuelRule.java.
{
        if (!Activity.search(player, DuelArenaActivity.class).isPresent()) {
            return false;
        }
        DuelArenaActivity activity = Activity.search(player, DuelArenaActivity.class).get();
        final DuelRules rules = activity.rules;
        boolean meets = condition.canSelect(player, rules);
        Player other = player.equals(activity.opponent) ? activity.player : activity.opponent;
        if (meets) {
            if (inventorySlotsRequired(player, rules, this) > player.inventory.getFreeSlots()) {
                if (showMessage) {
                    player.send(new SendMessage("You do not have enough inventory space."));
                }
                return false;
            }
            if (inventorySlotsRequired(other, rules, this) > other.inventory.getFreeSlots()) {
                if (showMessage) {
                    player.send(new SendMessage("The other player does not have enough space."));
                }
                return false;
            }
            rules.alternate(this);
            if ((this.getButtonId() >= 31034 && this.getButtonId() <= 31056) || this.getButtonId() == 31059) {
                player.send(new SendConfig(this.getValue(), rules.contains(this) ? 1 : 0));
                other.send(new SendConfig(this.getValue(), rules.contains(this) ? 1 : 0));
            } else {
                player.send(new SendToggle(286, rules.getValue()));
                other.send(new SendToggle(286, rules.getValue()));
            }
            player.send(new SendString("", 31009));
            other.send(new SendString("", 31009));
        }
        return meets;
    }
References com.runehive.content.activity.impl.duelarena.DuelRules.alternate(), condition, com.runehive.content.activity.impl.duelarena.DuelRules.contains(), com.runehive.game.world.entity.mob.player.Player.equals(), getButtonId(), com.runehive.game.world.items.containers.ItemContainer.getFreeSlots(), getValue(), com.runehive.content.activity.impl.duelarena.DuelRules.getValue(), com.runehive.game.world.entity.mob.player.Player.inventory, inventorySlotsRequired(), com.runehive.content.activity.Activity.search(), and com.runehive.game.world.entity.mob.player.Player.send().
showRules()
void com.runehive.content.activity.impl.duelarena.DuelRule.showRules (DuelArenaActivity activity, Player player, Player other) static
Definition at line 283 of file DuelRule.java.
{
        for (DuelRule rule : DuelRule.values()) {
            if (!EQUIPMENT_RULES.contains(rule)) {
                player.send(new SendConfig(rule.getValue(), activity.rules.contains(rule) ? 1 : 0));
                other.send(new SendConfig(rule.getValue(), activity.rules.contains(rule) ? 1 : 0));
            }
        }
        player.send(new SendToggle(286, activity.rules.getValue()));
        other.send(new SendToggle(286, activity.rules.getValue()));
    }
References DuelRule(), EQUIPMENT_RULES, and com.runehive.game.world.entity.mob.player.Player.send().
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onButtonClick().
validateEquipmentRules()
void com.runehive.content.activity.impl.duelarena.DuelRule.validateEquipmentRules (Player player) static
Definition at line 268 of file DuelRule.java.
{
        if (Activity.search(player, DuelArenaActivity.class).isPresent()) {
            DuelArenaActivity activity = Activity.search(player, DuelArenaActivity.class).get();
            for (DuelRule rule : DuelRule.EQUIPMENT_RULES) {
                if (activity.rules.contains(rule) && !rule.canSet(player)) {
                    activity.rules.unflag(rule);
                }
            }
            player.send(new SendToggle(286, activity.rules.getValue()));
            activity.opponent.send(new SendToggle(286, activity.rules.getValue()));
        }
    }
References canSet(), DuelRule(), com.runehive.content.activity.Activity.search(), and com.runehive.game.world.entity.mob.player.Player.send().
Member Data Documentation
button
final int com.runehive.content.activity.impl.duelarena.DuelRule.button private
The button for this rule.
Definition at line 188 of file DuelRule.java.
Referenced by DuelRule(), DuelRule(), forButton(), and getButtonId().
condition
final RuleCondition com.runehive.content.activity.impl.duelarena.DuelRule.condition private
The condition for this rule.
Definition at line 203 of file DuelRule.java.
Referenced by canSet(), DuelRule(), DuelRule(), getCondition(), and set().
EQUIPMENT_RULES
final ImmutableSet<DuelRule> com.runehive.content.activity.impl.duelarena.DuelRule.EQUIPMENT_RULES = ImmutableSet.of(NO_HEAD, NO_CAPE, NO_NECKLACE, NO_AMMO, NO_WEAPON, NO_BODY, NO_SHIELD, NO_LEGS, NO_GLOVES, NO_BOOTS, NO_RINGS) static
Definition at line 231 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelRules.alternate(), com.runehive.content.activity.impl.duelarena.DuelRules.flag(), showRules(), and com.runehive.content.activity.impl.duelarena.DuelRules.unflag().
LOCK_ITEMS
com.runehive.content.activity.impl.duelarena.DuelRule.LOCK_ITEMS
Initial value:
=(31059, 643, new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.ONLY_WHIP_DDS)) {
                player.send(new SendMessage("You cannot select lock items when only whip and dds is selected."));
                return false;
            }
            return true;
        }
    })
Definition at line 144 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem().
NO_AMMO
com.runehive.content.activity.impl.duelarena.DuelRule.NO_AMMO =(13816, 134217728, Equipment.ARROWS_SLOT, (player, rules) -> true)
Definition at line 157 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_BODY
com.runehive.content.activity.impl.duelarena.DuelRule.NO_BODY =(13818, 262144, Equipment.CHEST_SLOT,(player, rules) -> true)
Definition at line 178 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_BOOTS
com.runehive.content.activity.impl.duelarena.DuelRule.NO_BOOTS =(13822, 16777216, Equipment.FEET_SLOT, (player, rules) -> true)
Definition at line 182 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_CAPE
com.runehive.content.activity.impl.duelarena.DuelRule.NO_CAPE =(13814, 32768, Equipment.CAPE_SLOT, (player, rules) -> true)
Definition at line 155 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_DRINKS
com.runehive.content.activity.impl.duelarena.DuelRule.NO_DRINKS =(31041, 638, (player, rules) -> true)
Definition at line 103 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canDrinkPotions().
NO_FOOD
com.runehive.content.activity.impl.duelarena.DuelRule.NO_FOOD =(31042, 639, (player, rules) -> true)
Definition at line 104 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEat().
NO_FORFEIT
com.runehive.content.activity.impl.duelarena.DuelRule.NO_FORFEIT
Initial value:
=(31039, 636, new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.NO_MELEE)) {
                player.send(new SendMessage("You can't have No Forfeit and No Melee, you could run out of ammo."));
                return false;
            }
            if (rules.contains(DuelRule.OBSTACLES)) {
                player.send(new SendMessage("You cannot have no-movement and obstacles on at the same time."));
                return false;
            }
            return true;
        }
    })
Definition at line 87 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.clickObject().
NO_GLOVES
com.runehive.content.activity.impl.duelarena.DuelRule.NO_GLOVES =(13823, 8388608, Equipment.HANDS_SLOT, (player, rules) -> true)
Definition at line 181 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_HEAD
com.runehive.content.activity.impl.duelarena.DuelRule.NO_HEAD =(13813, 16384, Equipment.HELM_SLOT, (player, rules) -> true)
Definition at line 154 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_LEGS
com.runehive.content.activity.impl.duelarena.DuelRule.NO_LEGS =(13820, 2097152, Equipment.LEGS_SLOT, (player, rules) -> true)
Definition at line 180 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_MAGIC
com.runehive.content.activity.impl.duelarena.DuelRule.NO_MAGIC
Initial value:
=(31036, 633, new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.NO_MELEE) && rules.contains(DuelRule.NO_RANGED)) {
                player.send(new SendMessage("You must have at least one combat type checked."));
                return false;
            }
            if (rules.contains(DuelRule.NO_WEAPON) && rules.contains(DuelRule.NO_MELEE)) {
                player.message("You can't have No Melee, No Magic, Nothing in your Right Hand, how would you fight?");
                return false;
            }
            return true;
        }
    })
Definition at line 61 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack().
NO_MELEE
com.runehive.content.activity.impl.duelarena.DuelRule.NO_MELEE
Initial value:
=(31035, 632, new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.NO_MAGIC) && rules.contains(DuelRule.NO_RANGED)) {
                player.send(new SendMessage("You must have at least one combat type checked."));
                return false;
            }
            if (rules.contains(DuelRule.NO_WEAPON) && rules.contains(DuelRule.NO_MAGIC)) {
                player.message("You can't have No Melee, No Magic, Nothing in your Right Hand, how would you fight?");
                return false;
            }
            if (rules.contains(DuelRule.NO_FORFEIT)) {
                player.send(new SendMessage("You can't have No Forfeit and No Melee, you could run out of ammo."));
                return false;
            }
            if (rules.contains(DuelRule.ONLY_FUN_WEAPONS)) {
                player.send(new SendMessage("You cannot select no melee when only fun weapons selected."));
                return false;
            }
            if (rules.contains(DuelRule.ONLY_WHIP_DDS)) {
                player.send(new SendMessage("You cannot use whip and dragon dagger if melee is off."));
                return false;
            }
            return true;
        }
    })
Definition at line 30 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), and com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.canAttack().
NO_MOVEMENT
com.runehive.content.activity.impl.duelarena.DuelRule.NO_MOVEMENT
Initial value:
=(31043, 640, new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.OBSTACLES)) {
                player.send(new SendMessage("You cannot have no-movement and obstacles on at the same time."));
                return false;
            }
            return true;
        }
    })
Definition at line 105 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.start().
NO_NECKLACE
com.runehive.content.activity.impl.duelarena.DuelRule.NO_NECKLACE =(13815, 65536, Equipment.AMULET_SLOT, (player, rules) -> true)
Definition at line 156 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_PRAYER
com.runehive.content.activity.impl.duelarena.DuelRule.NO_PRAYER =(31040, 637, (player, rules) -> true)
Definition at line 102 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canUsePrayer().
NO_RANGED
com.runehive.content.activity.impl.duelarena.DuelRule.NO_RANGED
Initial value:
=(31034, 631, new RuleCondition()  {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.NO_MELEE) && rules.contains(DuelRule.NO_MAGIC)) {
                player.send(new SendMessage("You must have at least one combat type checked."));
                return false;
            }
            return true;
        }
    })
Definition at line 18 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack().
NO_RINGS
com.runehive.content.activity.impl.duelarena.DuelRule.NO_RINGS =(13821, 67108864, Equipment.RING_SLOT, (player, rules) -> true)
Definition at line 183 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_SHIELD
com.runehive.content.activity.impl.duelarena.DuelRule.NO_SHIELD =(13819, 524288, Equipment.SHIELD_SLOT, (player, rules) -> true)
Definition at line 179 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
NO_SPECIAL_ATTACK
com.runehive.content.activity.impl.duelarena.DuelRule.NO_SPECIAL_ATTACK =(31037, 634, (player, rules) -> true)
Definition at line 76 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canUseSpecial().
NO_WEAPON
com.runehive.content.activity.impl.duelarena.DuelRule.NO_WEAPON
Initial value:
=(13817, 131072, Equipment.WEAPON_SLOT, new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.NO_MELEE) && rules.contains(DuelRule.NO_MAGIC)) {
                player.message("You can't have No Melee, No Magic, Nothing in your Right Hand, how would you fight?");
                return false;
            }
            if (rules.contains(DuelRule.ONLY_FUN_WEAPONS)) {
                player.send(new SendMessage("You cannot select no weapons when only fun weapons selected."));
                return false;
            }
            if (rules.contains(DuelRule.ONLY_WHIP_DDS)) {
                player.send(new SendMessage("You cannot select no weapons when only whip and dds only is selected."));
                return false;
            }
            return true;
        }
    })
Definition at line 158 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.unequipItems().
OBSTACLES
com.runehive.content.activity.impl.duelarena.DuelRule.OBSTACLES
Initial value:
=(31044, 641,  new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.NO_MOVEMENT)) {
                player.send(new SendMessage("You cannot have no-movement and obstacles on at the same time."));
                return false;
            }
            if (rules.contains(DuelRule.OBSTACLES)) {
                player.message("Obstacles are permanently disabled.");
                return false;
            }
            player.message("Obstacles are permanently disabled.");
            return false;
        }
    })
Definition at line 115 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaActivity.start().
ONLY_FUN_WEAPONS
com.runehive.content.activity.impl.duelarena.DuelRule.ONLY_FUN_WEAPONS
Initial value:
=(31038, 635, new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.NO_WEAPON)) {
                player.send(new SendMessage("You cannot select only fun weapons when no weapons selected."));
                return false;
            }
            return true;
        }
    })
Definition at line 77 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem().
ONLY_WHIP_DDS
com.runehive.content.activity.impl.duelarena.DuelRule.ONLY_WHIP_DDS
Initial value:
=(31056, 642, new RuleCondition() {
        @Override
        public boolean canSelect(Player player, DuelRules rules) {
            if (rules.contains(DuelRule.NO_WEAPON)) {
                player.send(new SendMessage("You cannot select only whip and dds when no weapons selected."));
                return false;
            }
            if (rules.contains(DuelRule.LOCK_ITEMS)) {
                player.send(new SendMessage("You cannot select only whip and dds when lock items is selected."));
                return false;
            }
            return true;
        }
    })
Definition at line 130 of file DuelRule.java.
Referenced by com.runehive.content.activity.impl.duelarena.DuelArenaListener.canAttack(), and com.runehive.content.activity.impl.duelarena.DuelArenaActivity.canEquipItem().
slot
final int com.runehive.content.activity.impl.duelarena.DuelRule.slot private
The equipment slot for this rule.
Definition at line 198 of file DuelRule.java.
value
final int com.runehive.content.activity.impl.duelarena.DuelRule.value private
The value for the config.
Definition at line 193 of file DuelRule.java.
Referenced by DuelRule(), DuelRule(), and getValue().
The documentation for this enum was generated from the following file:
java/com/runehive/content/activity/impl/duelarena/DuelRule.java