RuneHive-Game: com.runehive.content.skill.impl.fletching.impl.Carvable Enum Reference
com.runehive.content.skill.impl.fletching.impl.Carvable Enum Reference
Public Member Functions
Carvable (Item use, Item with, FletchableItem... items)
int getAnimation ()
FletchableItem[] getFletchableItems ()
int getGraphics ()
Item[] getIngredients ()
String getProductionMessage ()
Item getUse ()
Item getWith ()
Static Public Member Functions
static void load ()
Public Attributes
AMETHYST =(new Item(946), new Item(21347), new FletchableItem(new Item(21350, 15), 83, 60.0), new FletchableItem(new Item(21338, 15), 83, 60.0), new FletchableItem(new Item(21352, 8), 89, 60.0), new FletchableItem(new Item(25853, 8), 87, 60.0))
DIAMOND_BOLT_TIP =(new Item(1755), new Item(1601), new FletchableItem(new Item(9192, 12), 65, 7.0))
DRAGONSTONE_BOLT_TIP =(new Item(1755), new Item(1615), new FletchableItem(new Item(9193, 12), 71, 8.2))
EMERALD_BOLT_TIP =(new Item(1755), new Item(1605), new FletchableItem(new Item(9190, 12), 53, 5.5))
JADE_BOLT_TIP =(new Item(1755), new Item(1611), new FletchableItem(new Item(9187, 12), 26, 2.0))
LOG =(new Item(946), new Item(1511), new FletchableItem(new Item(52, 15), 1, 5.0), new FletchableItem(new Item(50), 5, 5.0), new FletchableItem(new Item(48), 10, 10.0), new FletchableItem(new Item(9440), 9, 6.0))
MAGIC_LOG =(new Item(946), new Item(1513),new FletchableItem(new Item(52, 90), 75, 30.0), new FletchableItem(new Item(72), 80, 83.3), new FletchableItem(new Item(70), 85, 91.5))
MAHOGANY_LOG =(new Item(946), new Item(6332), new FletchableItem(new Item(9450), 61, 41.0))
MAPLE_LOG =(new Item(946), new Item(1517),new FletchableItem(new Item(52, 60), 45, 20.0), new FletchableItem(new Item(64), 50, 50.0), new FletchableItem(new Item(62), 55, 51.3), new FletchableItem(new Item(9448), 54, 32.0))
OAK_LOG =(new Item(946), new Item(1521), new FletchableItem(new Item(52, 30), 15, 10.0),new FletchableItem(new Item(54), 20, 16.5), new FletchableItem(new Item(56), 25, 25.0), new FletchableItem(new Item(9442), 24, 16.0))
ONYX_BOLT_TIP =(new Item(1755), new Item(6573), new FletchableItem(new Item(9194, 12), 73, 9.4))
OPAL_BOLT_TIP =(new Item(1755), new Item(1609), new FletchableItem(new Item(45, 12), 11, 1.5))
PEARL_BOLT_TIP =(new Item(1755), new Item(411), new FletchableItem(new Item(46, 24), 41, 3.2))
PEARLS_BOLT_TIP =(new Item(1755), new Item(413), new FletchableItem(new Item(46, 6), 41, 3.2))
RUBY_BOLT_TIP =(new Item(1755), new Item(1603), new FletchableItem(new Item(9191, 12), 63, 6.3))
SAPPHIRE_BOLT_TIP =(new Item(1755), new Item(1607), new FletchableItem(new Item(9189, 12), 56, 4.7))
TEAK_LOG =(new Item(946), new Item(6333), new FletchableItem(new Item(9446), 46, 27.0))
TOPAZ_BOLT_TIP =(new Item(1755), new Item(1613), new FletchableItem(new Item(9188, 12), 48, 3.9))
WILLOW_LOG =(new Item(946), new Item(1519), new FletchableItem(new Item(52, 45), 30, 15.0),new FletchableItem(new Item(60), 35, 33.3), new FletchableItem(new Item(58), 40, 41.5), new FletchableItem(new Item(9444), 39, 22.0))
YEW_LOG =(new Item(946), new Item(1515),new FletchableItem(new Item(52, 75), 60, 25.0), new FletchableItem(new Item(68), 65, 67.5), new FletchableItem(new Item(66), 70, 75.0), new FletchableItem(new Item(9452), 69, 50.0))
Private Attributes
final FletchableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 7 of file Carvable.java.
Constructor & Destructor Documentation
Carvable()
com.runehive.content.skill.impl.fletching.impl.Carvable.Carvable (Item use, Item with, FletchableItem... items)
Definition at line 34 of file Carvable.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.fletching.impl.Carvable.getAnimation ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 47 of file Carvable.java.
{
        switch (this) {
        case OPAL_BOLT_TIP:
        case PEARL_BOLT_TIP:
            return 891;
        case TOPAZ_BOLT_TIP:
            return 892;
        case SAPPHIRE_BOLT_TIP:
            return 888;
        case EMERALD_BOLT_TIP:
            return 889;
        case RUBY_BOLT_TIP:
            return 887;
        case DIAMOND_BOLT_TIP:
            return 890;
            case AMETHYST:
            return 6295;
            case DRAGONSTONE_BOLT_TIP:
            return 890;
        case ONYX_BOLT_TIP:
            return 2717;
        default:
            return 1248;
        }
    }
References AMETHYST, DIAMOND_BOLT_TIP, DRAGONSTONE_BOLT_TIP, EMERALD_BOLT_TIP, ONYX_BOLT_TIP, OPAL_BOLT_TIP, PEARL_BOLT_TIP, RUBY_BOLT_TIP, SAPPHIRE_BOLT_TIP, and TOPAZ_BOLT_TIP.
getFletchableItems()
FletchableItem[] com.runehive.content.skill.impl.fletching.impl.Carvable.getFletchableItems ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 89 of file Carvable.java.
{
        return items;
    }
References items.
getGraphics()
int com.runehive.content.skill.impl.fletching.impl.Carvable.getGraphics ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 74 of file Carvable.java.
{
        return -1;
    }
getIngredients()
Item[] com.runehive.content.skill.impl.fletching.impl.Carvable.getIngredients ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 99 of file Carvable.java.
{
        return new Item[] { with };
    }
References with.
getProductionMessage()
String com.runehive.content.skill.impl.fletching.impl.Carvable.getProductionMessage ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 94 of file Carvable.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.fletching.impl.Carvable.getUse ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 79 of file Carvable.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.fletching.impl.Carvable.getWith ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 84 of file Carvable.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.fletching.impl.Carvable.load () static
Definition at line 40 of file Carvable.java.
{
        for (Carvable car : values()) {
            Fletching.addFletchable(car);
        }
    }
References com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), and Carvable().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
AMETHYST
com.runehive.content.skill.impl.fletching.impl.Carvable.AMETHYST =(new Item(946), new Item(21347), new FletchableItem(new Item(21350, 15), 83, 60.0), new FletchableItem(new Item(21338, 15), 83, 60.0), new FletchableItem(new Item(21352, 8), 89, 60.0), new FletchableItem(new Item(25853, 8), 87, 60.0))
Definition at line 17 of file Carvable.java.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch(), getAnimation(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
DIAMOND_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.DIAMOND_BOLT_TIP =(new Item(1755), new Item(1601), new FletchableItem(new Item(9192, 12), 65, 7.0))
Definition at line 26 of file Carvable.java.
Referenced by getAnimation().
DRAGONSTONE_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.DRAGONSTONE_BOLT_TIP =(new Item(1755), new Item(1615), new FletchableItem(new Item(9193, 12), 71, 8.2))
Definition at line 27 of file Carvable.java.
Referenced by getAnimation().
EMERALD_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.EMERALD_BOLT_TIP =(new Item(1755), new Item(1605), new FletchableItem(new Item(9190, 12), 53, 5.5))
Definition at line 24 of file Carvable.java.
Referenced by getAnimation().
items
final FletchableItem [] com.runehive.content.skill.impl.fletching.impl.Carvable.items private
Definition at line 32 of file Carvable.java.
Referenced by Carvable(), and getFletchableItems().
JADE_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.JADE_BOLT_TIP =(new Item(1755), new Item(1611), new FletchableItem(new Item(9187, 12), 26, 2.0))
Definition at line 19 of file Carvable.java.
LOG
com.runehive.content.skill.impl.fletching.impl.Carvable.LOG =(new Item(946), new Item(1511), new FletchableItem(new Item(52, 15), 1, 5.0), new FletchableItem(new Item(50), 5, 5.0), new FletchableItem(new Item(48), 10, 10.0), new FletchableItem(new Item(9440), 9, 6.0))
Definition at line 9 of file Carvable.java.
MAGIC_LOG
com.runehive.content.skill.impl.fletching.impl.Carvable.MAGIC_LOG =(new Item(946), new Item(1513),new FletchableItem(new Item(52, 90), 75, 30.0), new FletchableItem(new Item(72), 80, 83.3), new FletchableItem(new Item(70), 85, 91.5))
Definition at line 16 of file Carvable.java.
MAHOGANY_LOG
com.runehive.content.skill.impl.fletching.impl.Carvable.MAHOGANY_LOG =(new Item(946), new Item(6332), new FletchableItem(new Item(9450), 61, 41.0))
Definition at line 14 of file Carvable.java.
MAPLE_LOG
com.runehive.content.skill.impl.fletching.impl.Carvable.MAPLE_LOG =(new Item(946), new Item(1517),new FletchableItem(new Item(52, 60), 45, 20.0), new FletchableItem(new Item(64), 50, 50.0), new FletchableItem(new Item(62), 55, 51.3), new FletchableItem(new Item(9448), 54, 32.0))
Definition at line 13 of file Carvable.java.
OAK_LOG
com.runehive.content.skill.impl.fletching.impl.Carvable.OAK_LOG =(new Item(946), new Item(1521), new FletchableItem(new Item(52, 30), 15, 10.0),new FletchableItem(new Item(54), 20, 16.5), new FletchableItem(new Item(56), 25, 25.0), new FletchableItem(new Item(9442), 24, 16.0))
Definition at line 10 of file Carvable.java.
ONYX_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.ONYX_BOLT_TIP =(new Item(1755), new Item(6573), new FletchableItem(new Item(9194, 12), 73, 9.4))
Definition at line 28 of file Carvable.java.
Referenced by getAnimation().
OPAL_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.OPAL_BOLT_TIP =(new Item(1755), new Item(1609), new FletchableItem(new Item(45, 12), 11, 1.5))
Definition at line 18 of file Carvable.java.
Referenced by getAnimation().
PEARL_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.PEARL_BOLT_TIP =(new Item(1755), new Item(411), new FletchableItem(new Item(46, 24), 41, 3.2))
Definition at line 20 of file Carvable.java.
Referenced by getAnimation().
PEARLS_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.PEARLS_BOLT_TIP =(new Item(1755), new Item(413), new FletchableItem(new Item(46, 6), 41, 3.2))
Definition at line 21 of file Carvable.java.
RUBY_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.RUBY_BOLT_TIP =(new Item(1755), new Item(1603), new FletchableItem(new Item(9191, 12), 63, 6.3))
Definition at line 25 of file Carvable.java.
Referenced by getAnimation().
SAPPHIRE_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.SAPPHIRE_BOLT_TIP =(new Item(1755), new Item(1607), new FletchableItem(new Item(9189, 12), 56, 4.7))
Definition at line 23 of file Carvable.java.
Referenced by getAnimation().
TEAK_LOG
com.runehive.content.skill.impl.fletching.impl.Carvable.TEAK_LOG =(new Item(946), new Item(6333), new FletchableItem(new Item(9446), 46, 27.0))
Definition at line 12 of file Carvable.java.
TOPAZ_BOLT_TIP
com.runehive.content.skill.impl.fletching.impl.Carvable.TOPAZ_BOLT_TIP =(new Item(1755), new Item(1613), new FletchableItem(new Item(9188, 12), 48, 3.9))
Definition at line 22 of file Carvable.java.
Referenced by getAnimation().
use
final Item com.runehive.content.skill.impl.fletching.impl.Carvable.use private
Definition at line 30 of file Carvable.java.
Referenced by Carvable(), and getUse().
WILLOW_LOG
com.runehive.content.skill.impl.fletching.impl.Carvable.WILLOW_LOG =(new Item(946), new Item(1519), new FletchableItem(new Item(52, 45), 30, 15.0),new FletchableItem(new Item(60), 35, 33.3), new FletchableItem(new Item(58), 40, 41.5), new FletchableItem(new Item(9444), 39, 22.0))
Definition at line 11 of file Carvable.java.
with
final Item com.runehive.content.skill.impl.fletching.impl.Carvable.with private
Definition at line 31 of file Carvable.java.
Referenced by Carvable(), getIngredients(), and getWith().
YEW_LOG
com.runehive.content.skill.impl.fletching.impl.Carvable.YEW_LOG =(new Item(946), new Item(1515),new FletchableItem(new Item(52, 75), 60, 25.0), new FletchableItem(new Item(68), 65, 67.5), new FletchableItem(new Item(66), 70, 75.0), new FletchableItem(new Item(9452), 69, 50.0))
Definition at line 15 of file Carvable.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fletching/impl/Carvable.java