RuneHive-Game: com.runehive.game.world.entity.combat.weapon.WeaponInterface Enum Reference
com.runehive.game.world.entity.combat.weapon.WeaponInterface Enum Reference
The enumerated type whose elements represent the weapon interfaces.
Public Member Functions
Optional< FightType > forFightButton (int button)
final FightType[] getFightTypes ()
Gets the fight types that correspond with this interface.
final int getId ()
Gets the identification of the interface that will be displayed.
String getNewDefName ()
final int getSpecialBar ()
Gets the identification of the special bar for this interface.
final int getSpecialMeter ()
Gets the identification of the special meter for this interface.
WeaponInterface (int id, String newDefName, int nameLine, int specialButton, int specialBar, int specialMeter, FightType[] fightTypes)
Creates a new WeaponInterface.
Static Public Member Functions
[static initializer]
static void execute (Player player, Item item)
The method executed when weapon item is equipped or unequipped that assigns a weapon interface to player.
static void execute (Player player, Item item, boolean login)
static WeaponInterface forNewName (String newDefName)
static boolean isSpecialButton (int button)
Public Attributes
BALLISTA
BATTLEAXE
BLOWPIPE
BLUDGEN
BULWARK
CHINCHOMPA
CLAWS
COMPOSITE_BOW
CROSSBOW
DAGGER
DARK_BOW
DART
DRAGON_DAGGER
ELDER_MAUL
FLAIL
GHRAZI_SWORD
GODSWORD_SWORD
GRANITE_MAUL
GREATAXE
HALBERD
HUNTER_LANCE
INQUISITOR_MACE
KARIL_CROSSBOW
KNIFE
LONGBOW
LONGSWORD
MACE
MAGIC_STAFF
NIGHTMARE_STAFF
OSMUM_SWORD
PICKAXE
SAELDOR_SWORD
SALAMANDER
SARADOMIN_SWORD
SCIMITAR
SCYTHE
SHADOW
SHORTBOW
SPEAR
STAFF
SWORD
THROWNAXE
TRIDENT
TWO_HANDED_SWORD
UNARMED
VIGGORA_MACE
VITUR
WARHAMMER
WHIP
ZARYTE_CROSSBOW
Static Public Attributes
static final WeaponInterface[] values = values()
Static Private Member Functions
static void defaultWeaponInterface (Player player)
Private Attributes
final FightType[] fightTypes
The fight types that correspond with this interface.
final int id
The identification of the interface that will be displayed.
final int nameLine
The identification of the line the weapon name will be displayed on.
final String newDefName
final int specialBar
The identification of the special bar for this interface.
final int specialButton
The identification of the special bar for this interface.
final int specialMeter
The identification of the special meter for this interface.
Static Private Attributes
static final Object2ObjectMap< String, WeaponInterface > newNameToValue = new Object2ObjectOpenHashMap<>(values.length)
Detailed Description
The enumerated type whose elements represent the weapon interfaces.
Author
lare96 http://github.com/lare96
Definition at line 22 of file WeaponInterface.java.
Constructor & Destructor Documentation
WeaponInterface()
com.runehive.game.world.entity.combat.weapon.WeaponInterface.WeaponInterface (int id, String newDefName, int nameLine, int specialButton, int specialBar, int specialMeter, FightType[] fightTypes)
Creates a new WeaponInterface.
Parameters
id the identification of the interface that will be displayed.
nameLine the identification of the line the weapon name will be displayed on.
fightTypes the fight types that correspond with this interface.
Definition at line 383 of file WeaponInterface.java.
{
        this.id = id;
        this.newDefName = newDefName;
        this.nameLine = nameLine;
        this.fightTypes = fightTypes;
        this.specialButton = specialButton;
        this.specialBar = specialBar;
        this.specialMeter = specialMeter;
    }
References fightTypes, id, nameLine, newDefName, specialBar, specialButton, and specialMeter.
Referenced by [static initializer](), defaultWeaponInterface(), execute(), and isSpecialButton().
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.weapon.WeaponInterface.[static initializer] static
References forNewName(), newDefName, newNameToValue, and WeaponInterface().
defaultWeaponInterface()
void com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface (Player player) static private
Definition at line 467 of file WeaponInterface.java.
{
        CombatSpecial.assign(player);
        CombatSpecial.updateSpecialAmount(player);
        Autocast.reset(player);
        player.setSingleCast(null);
        player.send(new SendString("<col=ff7000>Unarmed", WeaponInterface.UNARMED.nameLine));
        player.interfaceManager.setSidebar(Config.ATTACK_TAB, WeaponInterface.UNARMED.id);
        player.equipment.updateAnimation();
    }
References com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.assign(), com.runehive.Config.ATTACK_TAB, com.runehive.game.world.entity.mob.player.Player.equipment, com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.combat.magic.Autocast.reset(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar(), com.runehive.game.world.entity.mob.player.Player.setSingleCast(), com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.updateSpecialAmount(), and WeaponInterface().
Referenced by execute().
execute() [1/2]
void com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute (Player player, Item item) static
The method executed when weapon item is equipped or unequipped that assigns a weapon interface to player.
Parameters
player the player equipping the item.
item the item the player is equipping, or null if a weapon was unequipped.
Definition at line 402 of file WeaponInterface.java.
{
        execute(player, item, false);
    }
References execute().
Referenced by execute(), com.runehive.content.lms.LMSGame.giveItems(), com.runehive.game.world.items.containers.equipment.Equipment.EquipmentListener.itemUpdated(), com.runehive.content.lms.lobby.LMSLobby.joinLobby(), com.runehive.content.lms.lobby.LMSLobby.leaveLobby(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.content.lms.LMSGame.reset(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setSidebar().
execute() [2/2]
void com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute (Player player, Item item, boolean login) static
Definition at line 406 of file WeaponInterface.java.
{
        WeaponInterface weapon = item == null ? null : item.getWeaponInterface();
        if (weapon == null) weapon = WeaponInterface.UNARMED;
        FightType[] oldTypes = player.getWeapon().fightTypes;
        FightType[] newTypes = weapon.fightTypes;
        FightType result = null;
        for (int index = 0; index < oldTypes.length; index++) {
            if (newTypes.length == index) {
                break;
            }
            if (newTypes[index].getStyle().equals(FightStyle.DEFENSIVE)
                    && player.getCombat().getFightType().getStyle().equals(FightStyle.DEFENSIVE)) {
                result = newTypes[index];
                break;
            }
            if (oldTypes[index] == player.getCombat().getFightType()) {
                boolean oldControlled = oldTypes[index].getStyle().equals(FightStyle.CONTROLLED);
                boolean newControlled = newTypes[index].getStyle().equals(FightStyle.CONTROLLED);
                if (newControlled != oldControlled) {
                    continue;
                }
                result = newTypes[index];
                break;
            }
        }
        if (result == null) {
            if (player.getCombat().getFightType().getStyle().equals(FightStyle.DEFENSIVE)) {
                result = newTypes[newTypes.length - 1];
            } else {
                result = newTypes[1];
            }
        }
        player.setWeapon(weapon);
        if(!login) {
            player.getCombat().setFightType(result);
            player.send(new SendConfig(result.getParent(), result.getChild()));
        }
        if (weapon == WeaponInterface.UNARMED) {
            defaultWeaponInterface(player);
            return;
        }
        CombatSpecial.assign(player);
        CombatSpecial.updateSpecialAmount(player);
        Autocast.reset(player);
        player.setSingleCast(null);
        player.send(new SendString(item.getName(), weapon.nameLine));
        player.interfaceManager.setSidebar(Config.ATTACK_TAB, weapon.id);
        player.equipment.updateAnimation();
    }
References com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.assign(), com.runehive.Config.ATTACK_TAB, com.runehive.game.world.entity.combat.attack.FightStyle.CONTROLLED, defaultWeaponInterface(), com.runehive.game.world.entity.combat.attack.FightStyle.DEFENSIVE, com.runehive.game.world.entity.mob.player.Player.equipment, fightTypes, com.runehive.game.world.entity.combat.attack.FightType.getChild(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.game.world.items.Item.getName(), com.runehive.game.world.entity.combat.attack.FightType.getParent(), com.runehive.game.world.entity.combat.attack.FightType.getStyle(), com.runehive.game.world.entity.mob.player.Player.getWeapon(), com.runehive.game.world.items.Item.getWeaponInterface(), com.runehive.game.world.entity.mob.player.Player.interfaceManager, com.runehive.game.world.entity.combat.magic.Autocast.reset(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.player.InterfaceManager.setSidebar(), com.runehive.game.world.entity.mob.player.Player.setSingleCast(), com.runehive.game.world.entity.mob.player.Player.setWeapon(), com.runehive.game.world.items.containers.equipment.Equipment.updateAnimation(), com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.updateSpecialAmount(), and WeaponInterface().
forFightButton()
Optional< FightType > com.runehive.game.world.entity.combat.weapon.WeaponInterface.forFightButton (int button)
Definition at line 518 of file WeaponInterface.java.
{
        for (FightType type : fightTypes) {
            if (type.getButton() == button) {
                return Optional.of(type);
            }
        }
        return Optional.empty();
    }
References fightTypes.
forNewName()
WeaponInterface com.runehive.game.world.entity.combat.weapon.WeaponInterface.forNewName (String newDefName) static
Definition at line 541 of file WeaponInterface.java.
{
        return newNameToValue.get(newDefName);
    }
Referenced by [static initializer]().
getFightTypes()
final FightType[] com.runehive.game.world.entity.combat.weapon.WeaponInterface.getFightTypes ()
Gets the fight types that correspond with this interface.
Returns
the fight types that correspond.
Definition at line 496 of file WeaponInterface.java.
{
        return fightTypes;
    }
References fightTypes.
Referenced by com.runehive.content.overrides.Overrides.getFightType().
getId()
final int com.runehive.game.world.entity.combat.weapon.WeaponInterface.getId ()
Gets the identification of the interface that will be displayed.
Returns
the identification of the interface.
Definition at line 483 of file WeaponInterface.java.
{
        return id;
    }
References id.
getNewDefName()
String com.runehive.game.world.entity.combat.weapon.WeaponInterface.getNewDefName ()
Definition at line 487 of file WeaponInterface.java.
{
        return newDefName;
    }
References newDefName.
getSpecialBar()
final int com.runehive.game.world.entity.combat.weapon.WeaponInterface.getSpecialBar ()
Gets the identification of the special bar for this interface.
Returns
the identification of the special bar.
Definition at line 505 of file WeaponInterface.java.
{
        return specialBar;
    }
References specialBar.
getSpecialMeter()
final int com.runehive.game.world.entity.combat.weapon.WeaponInterface.getSpecialMeter ()
Gets the identification of the special meter for this interface.
Returns
the identification of the special meter.
Definition at line 514 of file WeaponInterface.java.
{
        return specialMeter;
    }
References specialMeter.
isSpecialButton()
boolean com.runehive.game.world.entity.combat.weapon.WeaponInterface.isSpecialButton (int button) static
Definition at line 527 of file WeaponInterface.java.
{
        for (WeaponInterface weaponInterface : values()) {
            if (weaponInterface.specialButton == button) {
                return true;
            }
        }
        return false;
    }
References values, and WeaponInterface().
Member Data Documentation
BALLISTA
com.runehive.game.world.entity.combat.weapon.WeaponInterface.BALLISTA
Initial value:
=(1764, "crossbow", 1767, 7548, 7549, 7561, new FightType[]{
            FightType.BALLISTA_ACCURATE,
            FightType.BALLISTA_RAPID,
            FightType.BALLISTA_LONGRANGE
    })
Definition at line 281 of file WeaponInterface.java.
BATTLEAXE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.BATTLEAXE
Initial value:
=(1698, "weapon", 1701, 7498, 7499, 7511, new FightType[]{
            FightType.BATTLEAXE_CHOP,
            FightType.BATTLEAXE_HACK,
            FightType.BATTLEAXE_SMASH,
            FightType.BATTLEAXE_BLOCK
    })
Definition at line 73 of file WeaponInterface.java.
BLOWPIPE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.BLOWPIPE
Initial value:
=(4446, "thrown", 4449, 7637, 7649, 7661, new FightType[]{
            FightType.BLOWPIPE_ACCURATE,
            FightType.BLOWPIPE_RAPID,
            FightType.BLOWPIPE_LONGRANGE
    })
Definition at line 244 of file WeaponInterface.java.
BLUDGEN
com.runehive.game.world.entity.combat.weapon.WeaponInterface.BLUDGEN
Initial value:
=(4705, "bludgeon", 4708, 7687, 7699, 7711, new FightType[]{
            FightType.BLUDGEN_CHOP,
            FightType.BLUDGEN_SLASH,
            FightType.BLUDGEN_SMASH,
            FightType.BLUDGEN_BLOCK
    })
Definition at line 340 of file WeaponInterface.java.
BULWARK
com.runehive.game.world.entity.combat.weapon.WeaponInterface.BULWARK
Initial value:
=(425, "bulwark", 428, 7473, 7474, 7486, new FightType[]{
            FightType.BULWARK_POUND,
            FightType.BULWARK_PUMMEL,
            FightType.BULWARK_BLOCK
    })
Definition at line 250 of file WeaponInterface.java.
CHINCHOMPA
com.runehive.game.world.entity.combat.weapon.WeaponInterface.CHINCHOMPA
Initial value:
=(24055, "chinchompas", 24056, -1, -1, -1, new FightType[]{
            FightType.SHORT_FUSE,
            FightType.MEDIUM_FUSE,
            FightType.LONG_FUSE
    })
Definition at line 221 of file WeaponInterface.java.
CLAWS
com.runehive.game.world.entity.combat.weapon.WeaponInterface.CLAWS
Initial value:
=(7762, "claw", 7765, 7788, 7800, 7812, new FightType[]{
            FightType.CLAWS_CHOP,
            FightType.CLAWS_SLASH,
            FightType.CLAWS_LUNGE,
            FightType.CLAWS_BLOCK
    })
Definition at line 196 of file WeaponInterface.java.
COMPOSITE_BOW
com.runehive.game.world.entity.combat.weapon.WeaponInterface.COMPOSITE_BOW
Initial value:
=(1764, "bow", 1767, 7548, 7549, 7561, new FightType[]{
            FightType.LONGBOW_ACCURATE,
            FightType.LONGBOW_RAPID,
            FightType.LONGBOW_LONGRANGE
    })
Definition at line 109 of file WeaponInterface.java.
CROSSBOW
com.runehive.game.world.entity.combat.weapon.WeaponInterface.CROSSBOW
Initial value:
=(1764, "crossbow", 1767, 7548, 7549, 7561, new FightType[]{
            FightType.CROSSBOW_ACCURATE,
            FightType.CROSSBOW_RAPID,
            FightType.CROSSBOW_LONGRANGE
    })
Definition at line 80 of file WeaponInterface.java.
DAGGER
com.runehive.game.world.entity.combat.weapon.WeaponInterface.DAGGER
Initial value:
=(2276, "stab_sword", 2279, 7562, 7574, 7586, new FightType[]{
            FightType.DAGGER_STAB,
            FightType.DAGGER_LUNGE,
            FightType.DAGGER_SLASH,
            FightType.DAGGER_BLOCK
    })
Definition at line 115 of file WeaponInterface.java.
DARK_BOW
com.runehive.game.world.entity.combat.weapon.WeaponInterface.DARK_BOW
Initial value:
=(1764, "bow", 1767, 7548, 7549, 7561, new FightType[]{
            FightType.DARK_BOW_ACCURATE,
            FightType.DARK_BOW_RAPID,
            FightType.DARK_BOW_LONGRANGE
    })
Definition at line 103 of file WeaponInterface.java.
DART
com.runehive.game.world.entity.combat.weapon.WeaponInterface.DART
Initial value:
=(4446, "thrown", 4449, 7637, 7649, 7661, new FightType[]{
            FightType.DART_ACCURATE,
            FightType.DART_RAPID,
            FightType.DART_LONGRANGE
    })
Definition at line 29 of file WeaponInterface.java.
DRAGON_DAGGER
com.runehive.game.world.entity.combat.weapon.WeaponInterface.DRAGON_DAGGER
Initial value:
=(2276, "stab_sword", 2279, 7562, 7574, 7586, new FightType[]{
            FightType.DRAGON_DAGGER_STAB,
            FightType.DRAGON_DAGGER_LUNGE,
            FightType.DRAGON_DAGGER_SLASH,
            FightType.DRAGON_DAGGER_BLOCK
    })
Definition at line 287 of file WeaponInterface.java.
ELDER_MAUL
com.runehive.game.world.entity.combat.weapon.WeaponInterface.ELDER_MAUL
Initial value:
=(425, "blunt", 428, 7473, 7474, 7486, new FightType[]{
            FightType.ELDER_MAUL_POUND,
            FightType.ELDER_MAUL_PUMMEL,
            FightType.ELDER_MAUL_BLOCK
    })
Definition at line 262 of file WeaponInterface.java.
fightTypes
final FightType [] com.runehive.game.world.entity.combat.weapon.WeaponInterface.fightTypes private
The fight types that correspond with this interface.
Definition at line 357 of file WeaponInterface.java.
Referenced by execute(), forFightButton(), getFightTypes(), and WeaponInterface().
FLAIL
com.runehive.game.world.entity.combat.weapon.WeaponInterface.FLAIL
Initial value:
=(3796, "spiked", 3799, 7623, 7624, 7636, new FightType[]{
            FightType.FLAIL_POUND,
            FightType.FLAIL_PUMMEL,
            FightType.FLAIL_SPIKE,
            FightType.FLAIL_BLOCK
    })
Definition at line 294 of file WeaponInterface.java.
GHRAZI_SWORD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.GHRAZI_SWORD
Initial value:
=(2276, "stab_sword", 2279, 7562, 7574, 7586, new FightType[]{
            FightType.GHRAZI_STAB,
            FightType.GHRAZI_LUNGE,
            FightType.GHRAZI_SLASH,
            FightType.GHRAZI_BLOCK
    })
Definition at line 319 of file WeaponInterface.java.
GODSWORD_SWORD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.GODSWORD_SWORD
Initial value:
=(4705, "2h_sword", 4708, 7687, 7699, 7711, new FightType[]{
            FightType.GODSWORD_CHOP,
            FightType.GODSWORD_SLASH,
            FightType.GODSWORD_SMASH,
            FightType.GODSWORD_BLOCK
    })
Definition at line 301 of file WeaponInterface.java.
GRANITE_MAUL
com.runehive.game.world.entity.combat.weapon.WeaponInterface.GRANITE_MAUL
Initial value:
=(425, "blunt", 428, 7473, 7474, 7486, new FightType[]{
            FightType.GRANITE_MAUL_POUND,
            FightType.GRANITE_MAUL_PUMMEL,
            FightType.GRANITE_MAUL_BLOCK
    })
Definition at line 256 of file WeaponInterface.java.
GREATAXE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.GREATAXE
Initial value:
=(1698, "axe", 1701, 7498, 7499, 7591, new FightType[]{
            FightType.GREATAXE_CHOP,
            FightType.GREATAXE_HACK,
            FightType.GREATAXE_SMASH,
            FightType.GREATAXE_BLOCK
    })
Definition at line 268 of file WeaponInterface.java.
HALBERD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.HALBERD
Initial value:
=(8460, "polearm", 8463, 8481, 8493, 8505, new FightType[]{
            FightType.HALBERD_JAB,
            FightType.HALBERD_SWIPE,
            FightType.HALBERD_FEND
    })
Definition at line 203 of file WeaponInterface.java.
HUNTER_LANCE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.HUNTER_LANCE
Initial value:
=(4679, "spear", 4682, 7662, 7674, 7686, new FightType[]{
            FightType.HUNTER_LANCE_LUNGE,
            FightType.HUNTER_LANCE_SWIPE,
            FightType.HUNTER_LANCE_POUND,
            FightType.HUNTER_LANCE_BLOCK
    })
Definition at line 175 of file WeaponInterface.java.
id
final int com.runehive.game.world.entity.combat.weapon.WeaponInterface.id private
The identification of the interface that will be displayed.
Definition at line 345 of file WeaponInterface.java.
Referenced by getId(), and WeaponInterface().
INQUISITOR_MACE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.INQUISITOR_MACE
Initial value:
=(3796, "spiked", 3799, 7623, 7624, 7636, new FightType[]{
            FightType.INQUISITOR_MACE_POUND,
            FightType.INQUISITOR_MACE_PUMMEL,
            FightType.INQUISITOR_MACE_SPIKE,
            FightType.INQUISITOR_MACE_BLOCK
    })
Definition at line 156 of file WeaponInterface.java.
KARIL_CROSSBOW
com.runehive.game.world.entity.combat.weapon.WeaponInterface.KARIL_CROSSBOW
Initial value:
=(1764, "crossbow", 1767, 7548, 7549, 7561, new FightType[]{
            FightType.KARIL_CROSSBOW_ACCURATE,
            FightType.KARIL_CROSSBOW_RAPID,
            FightType.KARIL_CROSSBOW_LONGRANGE
    })
Definition at line 275 of file WeaponInterface.java.
KNIFE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.KNIFE
Initial value:
=(4446, "thrown", 4449, 7637, 7649, 7661, new FightType[]{
            FightType.KNIFE_ACCURATE,
            FightType.KNIFE_RAPID,
            FightType.KNIFE_LONGRANGE
    })
Definition at line 163 of file WeaponInterface.java.
LONGBOW
com.runehive.game.world.entity.combat.weapon.WeaponInterface.LONGBOW
Initial value:
=(1764, "bow", 1767, 7548, 7549, 7561, new FightType[]{
            FightType.LONGBOW_ACCURATE,
            FightType.LONGBOW_RAPID,
            FightType.LONGBOW_LONGRANGE
    })
Definition at line 97 of file WeaponInterface.java.
LONGSWORD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.LONGSWORD
Initial value:
=(2423, "slash_sword", 2426, 7587, 7599, 7611, new FightType[]{
            FightType.LONGSWORD_CHOP,
            FightType.LONGSWORD_SLASH,
            FightType.LONGSWORD_LUNGE,
            FightType.LONGSWORD_BLOCK
    })
Definition at line 136 of file WeaponInterface.java.
MACE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.MACE
Initial value:
=(3796, "spiked", 3799, 7623, 7624, 7636, new FightType[]{
            FightType.MACE_POUND,
            FightType.MACE_PUMMEL,
            FightType.MACE_SPIKE,
            FightType.MACE_BLOCK
    })
Definition at line 143 of file WeaponInterface.java.
MAGIC_STAFF
com.runehive.game.world.entity.combat.weapon.WeaponInterface.MAGIC_STAFF
Initial value:
=(328, "staff", 355, 340, 18566, 18569, new FightType[]{
            FightType.STAFF_BASH,
            FightType.STAFF_POUND,
            FightType.STAFF_FOCUS
    })
Definition at line 41 of file WeaponInterface.java.
nameLine
final int com.runehive.game.world.entity.combat.weapon.WeaponInterface.nameLine private
The identification of the line the weapon name will be displayed on.
Definition at line 352 of file WeaponInterface.java.
Referenced by WeaponInterface().
newDefName
final String com.runehive.game.world.entity.combat.weapon.WeaponInterface.newDefName private
Definition at line 347 of file WeaponInterface.java.
Referenced by [static initializer](), getNewDefName(), and WeaponInterface().
newNameToValue
final Object2ObjectMap<String, WeaponInterface> com.runehive.game.world.entity.combat.weapon.WeaponInterface.newNameToValue = new Object2ObjectOpenHashMap<>(values.length) static private
Definition at line 539 of file WeaponInterface.java.
Referenced by [static initializer]().
NIGHTMARE_STAFF
com.runehive.game.world.entity.combat.weapon.WeaponInterface.NIGHTMARE_STAFF
Initial value:
=(328, "staff", 355, 340, 18566, 18569, new FightType[]{
            FightType.NIGHTMARE_STAFF_BASH,
            FightType.NIGHTMARE_STAFF_POUND,
            FightType.NIGHTMARE_STAFF_FOCUS
    })
Definition at line 46 of file WeaponInterface.java.
OSMUM_SWORD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.OSMUM_SWORD
Initial value:
=(2276, "stab_sword", 2279, 7562, 7574, 7586, new FightType[]{
            FightType.FANG_STAB,
            FightType.FANG_LUNGE,
            FightType.FANG_SLASH,
            FightType.FANG_BLOCK
    })
Definition at line 313 of file WeaponInterface.java.
PICKAXE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.PICKAXE
Initial value:
=(5570, "pickaxe", 5573, 7723, 7724, 7736, new FightType[]{
            FightType.PICKAXE_SPIKE,
            FightType.PICKAXE_IMPALE,
            FightType.PICKAXE_SMASH,
            FightType.PICKAXE_BLOCK
    })
Definition at line 189 of file WeaponInterface.java.
SAELDOR_SWORD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SAELDOR_SWORD
Initial value:
=(2423, "slash_sword", 2426, 7587, 7599, 7611, new FightType[]{
            FightType.SAELDOR_STAB,
            FightType.SAELDOR_SLASH,
            FightType.SAELDOR_CRUSH,
            FightType.SAELDOR_BLOCK
    })
Definition at line 307 of file WeaponInterface.java.
SALAMANDER
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SALAMANDER
Initial value:
=(24074, "salamander", 24075, -1, -1, -1, new FightType[]{
            FightType.SCORCH,
            FightType.FLARE,
            FightType.BLAZE
    })
Definition at line 227 of file WeaponInterface.java.
SARADOMIN_SWORD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SARADOMIN_SWORD
Initial value:
=(4705, "2h_sword", 4708, 7687, 7699, 7711, new FightType[]{
            FightType.SARADOMIN_CHOP,
            FightType.SARADOMIN_SLASH,
            FightType.SARADOMIN_SMASH,
            FightType.SARADOMIN_BLOCK
    })
Definition at line 328 of file WeaponInterface.java.
SCIMITAR
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SCIMITAR
Initial value:
=(2423, "slash_sword", 2426, 7587, 7599, 7611, new FightType[]{
            FightType.SCIMITAR_CHOP,
            FightType.SCIMITAR_SLASH,
            FightType.SCIMITAR_LUNGE,
            FightType.SCIMITAR_BLOCK
    })
Definition at line 129 of file WeaponInterface.java.
SCYTHE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SCYTHE
Initial value:
=(776, "scythe", 779, -1, -1, -1, new FightType[]{
            FightType.SCYTHE_REAP,
            FightType.SCYTHE_CHOP,
            FightType.SCYTHE_JAB,
            FightType.SCYTHE_BLOCK
    })
Definition at line 59 of file WeaponInterface.java.
SHADOW
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SHADOW
Initial value:
=(4446, "powered_staff", 4449, 7637, 7649, 7661, new FightType[]{
            FightType.SHADOW_ACCURATE,
            FightType.SHADOW_RAPID,
            FightType.SHADOW_LONGRANGE
    })
Definition at line 238 of file WeaponInterface.java.
SHORTBOW
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SHORTBOW
Initial value:
=(1764, "bow", 1767, 7548, 7549, 7561, new FightType[]{
            FightType.SHORTBOW_ACCURATE,
            FightType.SHORTBOW_RAPID,
            FightType.SHORTBOW_LONGRANGE
    })
Definition at line 91 of file WeaponInterface.java.
SPEAR
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SPEAR
Initial value:
=(4679, "spear", 4682, 7662, 7674, 7686, new FightType[]{
            FightType.SPEAR_LUNGE,
            FightType.SPEAR_SWIPE,
            FightType.SPEAR_POUND,
            FightType.SPEAR_BLOCK
    })
Definition at line 169 of file WeaponInterface.java.
specialBar
final int com.runehive.game.world.entity.combat.weapon.WeaponInterface.specialBar private
The identification of the special bar for this interface.
Definition at line 367 of file WeaponInterface.java.
Referenced by getSpecialBar(), and WeaponInterface().
specialButton
final int com.runehive.game.world.entity.combat.weapon.WeaponInterface.specialButton private
The identification of the special bar for this interface.
Definition at line 362 of file WeaponInterface.java.
Referenced by WeaponInterface().
specialMeter
final int com.runehive.game.world.entity.combat.weapon.WeaponInterface.specialMeter private
The identification of the special meter for this interface.
Definition at line 372 of file WeaponInterface.java.
Referenced by getSpecialMeter(), and WeaponInterface().
STAFF
com.runehive.game.world.entity.combat.weapon.WeaponInterface.STAFF
Initial value:
=(6103, "staff", 6132, 6104, 6117, 6129, new FightType[]{
            FightType.STAFF_BASH,
            FightType.STAFF_POUND,
            FightType.STAFF_FOCUS
    })
Definition at line 35 of file WeaponInterface.java.
SWORD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.SWORD
Initial value:
=(2276, "slash_sword", 2279, 7562, 7574, 7586, new FightType[]{
            FightType.SWORD_STAB,
            FightType.SWORD_LUNGE,
            FightType.SWORD_SLASH,
            FightType.SWORD_BLOCK
    })
Definition at line 122 of file WeaponInterface.java.
THROWNAXE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.THROWNAXE
Initial value:
=(4446, "thrown", 4449, 7637, 7649, 7661, new FightType[]{
            FightType.THROWNAXE_ACCURATE,
            FightType.THROWNAXE_RAPID,
            FightType.THROWNAXE_LONGRANGE
    })
Definition at line 215 of file WeaponInterface.java.
TRIDENT
com.runehive.game.world.entity.combat.weapon.WeaponInterface.TRIDENT
Initial value:
=(4446, "powered_staff", 4449, 7637, 7649, 7661, new FightType[]{
            FightType.TRIDENT_ACCURATE,
            FightType.TRIDENT_RAPID,
            FightType.TRIDENT_LONGRANGE
    })
Definition at line 233 of file WeaponInterface.java.
TWO_HANDED_SWORD
com.runehive.game.world.entity.combat.weapon.WeaponInterface.TWO_HANDED_SWORD
Initial value:
=(4705, "2h_sword", 4708, 7687, 7699, 7711, new FightType[]{
            FightType.TWOHANDEDSWORD_CHOP,
            FightType.TWOHANDEDSWORD_SLASH,
            FightType.TWOHANDEDSWORD_SMASH,
            FightType.TWOHANDEDSWORD_BLOCK
    })
Definition at line 182 of file WeaponInterface.java.
UNARMED
com.runehive.game.world.entity.combat.weapon.WeaponInterface.UNARMED
Initial value:
=(5855, "unarmed",5857, 7737, 7749, 7761, new FightType[]{
            FightType.UNARMED_PUNCH,
            FightType.UNARMED_KICK,
            FightType.UNARMED_BLOCK
    })
Definition at line 23 of file WeaponInterface.java.
Referenced by com.runehive.game.world.items.ItemDefinition.dump(), com.runehive.game.world.items.ItemDefinition.dump(), and com.runehive.content.overrides.Overrides.getFightType().
values
final WeaponInterface [] com.runehive.game.world.entity.combat.weapon.WeaponInterface.values = values() static
Definition at line 536 of file WeaponInterface.java.
Referenced by isSpecialButton().
VIGGORA_MACE
com.runehive.game.world.entity.combat.weapon.WeaponInterface.VIGGORA_MACE
Initial value:
=(3796, "spiked", 3799, 7623, 7624, 7636, new FightType[]{
            FightType.VIGGORA_MACE_POUND,
            FightType.VIGGORA_MACE_PUMMEL,
            FightType.VIGGORA_MACE_SPIKE,
            FightType.VIGGORA_MACE_BLOCK
    })
Definition at line 149 of file WeaponInterface.java.
VITUR
com.runehive.game.world.entity.combat.weapon.WeaponInterface.VITUR
Initial value:
=(776, "scythe", 779, -1, -1, -1, new FightType[]{
            FightType.VITUR_REAP,
            FightType.VITUR_CHOP,
            FightType.VITUR_JAB,
            FightType.VITUR_BLOCK
    })
Definition at line 65 of file WeaponInterface.java.
WARHAMMER
com.runehive.game.world.entity.combat.weapon.WeaponInterface.WARHAMMER
Initial value:
=(425, "blunt", 428, 7473, 7474, 7486, new FightType[]{
            FightType.WARHAMMER_POUND,
            FightType.WARHAMMER_PUMMEL,
            FightType.WARHAMMER_BLOCK
    })
Definition at line 53 of file WeaponInterface.java.
WHIP
com.runehive.game.world.entity.combat.weapon.WeaponInterface.WHIP
Initial value:
=(12290, "weapon", 12293, 12322, 12323, 12335, new FightType[]{
            FightType.WHIP_FLICK,
            FightType.WHIP_LASH,
            FightType.WHIP_DEFLECT
    })
Definition at line 209 of file WeaponInterface.java.
ZARYTE_CROSSBOW
com.runehive.game.world.entity.combat.weapon.WeaponInterface.ZARYTE_CROSSBOW
Initial value:
=(1764, "crossbow", 1767, 7548, 7549, 7561, new FightType[]{
            FightType.ZARYTE_ACCURATE,
            FightType.ZARYTE_RAPID,
            FightType.ZARYTE_LONGRANGE
    })
Definition at line 85 of file WeaponInterface.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/weapon/WeaponInterface.java