RuneHive-Game: com.runehive.content.skill.impl.magic.Spellbook Enum Reference
com.runehive.content.skill.impl.magic.Spellbook Enum Reference
The in-game spellbooks for players.
Public Member Functions
int getId ()
Gets the id of this spellbook.
int getInterfaceId ()
Gets the sidebar interfaceId of this spellbook.
String getName ()
Gets the spellbook name.
Spellbook (String name, int id, int sidebar)
Constructs a new Spellbook.
Public Attributes
ANCIENT =("Ancient", 1, 12855)
LUNAR =("Lunar", 2, 29999)
MODERN =("Modern", 0, 40000)
Private Attributes
final int id
The id of this spellbook.
final String name
The name of the spellbook.
final int sidebar
The sidebar interfaceId of this spellbook.
Detailed Description
The in-game spellbooks for players.
Author
Daniel | Obey
Definition at line 8 of file Spellbook.java.
Constructor & Destructor Documentation
Spellbook()
com.runehive.content.skill.impl.magic.Spellbook.Spellbook (String name, int id, int sidebar)
Constructs a new Spellbook.
Definition at line 22 of file Spellbook.java.
{
        this.name = name;
        this.id = id;
        this.sidebar = sidebar;
    }
References id, name, and sidebar.
Member Function Documentation
getId()
int com.runehive.content.skill.impl.magic.Spellbook.getId ()
Gets the id of this spellbook.
Definition at line 34 of file Spellbook.java.
                       {
        return id;
    }
References id.
getInterfaceId()
int com.runehive.content.skill.impl.magic.Spellbook.getInterfaceId ()
Gets the sidebar interfaceId of this spellbook.
Definition at line 39 of file Spellbook.java.
{
        return sidebar;
    }
References sidebar.
Referenced by com.runehive.content.lms.LMSGame.giveItems(), and com.runehive.content.lms.LMSGame.reset().
getName()
String com.runehive.content.skill.impl.magic.Spellbook.getName ()
Gets the spellbook name.
Definition at line 29 of file Spellbook.java.
{
        return name;
    }
References name.
Member Data Documentation
ANCIENT
com.runehive.content.skill.impl.magic.Spellbook.ANCIENT =("Ancient", 1, 12855)
Definition at line 10 of file Spellbook.java.
Referenced by com.runehive.content.lms.loadouts.impl.Max.getSpellbook(), com.runehive.content.lms.loadouts.impl.Pure.getSpellbook(), com.runehive.content.lms.loadouts.impl.Zerk.getSpellbook(), com.runehive.content.preloads.impl.InitiateNHPreload.spellbook(), com.runehive.content.preloads.impl.MainNHPreload.spellbook(), com.runehive.content.preloads.impl.PureNHPreload.spellbook(), and com.runehive.content.preloads.impl.ZerkerNHPreload.spellbook().
id
final int com.runehive.content.skill.impl.magic.Spellbook.id private
The id of this spellbook.
Definition at line 17 of file Spellbook.java.
Referenced by getId(), and Spellbook().
LUNAR
com.runehive.content.skill.impl.magic.Spellbook.LUNAR =("Lunar", 2, 29999)
Definition at line 11 of file Spellbook.java.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.Vengeance.execute(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.content.preloads.impl.MainMeleePreload.spellbook(), com.runehive.content.preloads.impl.MainRangePreload.spellbook(), com.runehive.content.preloads.impl.ZerkerMeleePreload.spellbook(), and com.runehive.content.preloads.impl.ZerkerRangePreload.spellbook().
MODERN
com.runehive.content.skill.impl.magic.Spellbook.MODERN =("Modern", 0, 40000)
Definition at line 9 of file Spellbook.java.
Referenced by com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas.execute(), com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches.execute(), com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy.execute(), com.runehive.content.skill.impl.magic.spell.impl.SuperHeat.execute(), com.runehive.content.preset.Preset.Preset(), com.runehive.content.preset.Preset.Preset(), com.runehive.game.world.entity.combat.magic.Autocast.sendSelectionInterface(), com.runehive.content.preloads.impl.F2PMeleePreload.spellbook(), com.runehive.content.preloads.impl.F2PRangePreload.spellbook(), com.runehive.content.preloads.impl.InitiateMeleePreload.spellbook(), com.runehive.content.preloads.impl.InitiateRangePreload.spellbook(), com.runehive.content.preloads.impl.PureMeleePreload.spellbook(), and com.runehive.content.preloads.impl.PureRangePreload.spellbook().
name
final String com.runehive.content.skill.impl.magic.Spellbook.name private
The name of the spellbook.
Definition at line 14 of file Spellbook.java.
Referenced by getName(), and Spellbook().
sidebar
final int com.runehive.content.skill.impl.magic.Spellbook.sidebar private
The sidebar interfaceId of this spellbook.
Definition at line 19 of file Spellbook.java.
Referenced by getInterfaceId(), and Spellbook().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/magic/Spellbook.java