RuneHive-Game: com.runehive.content.bot.objective.BotObjective Enum Reference
com.runehive.content.bot.objective.BotObjective Enum Reference
Public Member Functions
BotObjective (BotObjectiveListener listener)
void finish (PlayerBot bot)
void init (PlayerBot bot)
Public Attributes
COMBAT =(new CombatObjective())
RESTOCK =(new RestockObjective())
WALK_IN_WILDERNESS =(new WildernessWalkObjective())
WALK_TO_BANK =(new BankObjective())
WALK_TO_DITCH =(new WildernessDitchObjective())
Private Attributes
final BotObjectiveListener listener
Detailed Description
Definition at line 6 of file BotObjective.java.
Constructor & Destructor Documentation
BotObjective()
com.runehive.content.bot.objective.BotObjective.BotObjective (BotObjectiveListener listener)
Definition at line 15 of file BotObjective.java.
{
        this.listener = listener;
    }
References listener.
Member Function Documentation
finish()
void com.runehive.content.bot.objective.BotObjective.finish (PlayerBot bot)
Implements com.runehive.content.bot.objective.BotObjectiveListener.
Definition at line 25 of file BotObjective.java.
{
        listener.finish(bot);
    }
References listener.
init()
void com.runehive.content.bot.objective.BotObjective.init (PlayerBot bot)
Implements com.runehive.content.bot.objective.BotObjectiveListener.
Definition at line 20 of file BotObjective.java.
{
        listener.init(bot);
    }
References listener.
Member Data Documentation
COMBAT
com.runehive.content.bot.objective.BotObjective.COMBAT =(new CombatObjective())
Definition at line 11 of file BotObjective.java.
Referenced by com.runehive.content.bot.PlayerBot.retaliate().
listener
final BotObjectiveListener com.runehive.content.bot.objective.BotObjective.listener private
Definition at line 13 of file BotObjective.java.
Referenced by BotObjective(), finish(), and init().
RESTOCK
com.runehive.content.bot.objective.BotObjective.RESTOCK =(new RestockObjective())
Definition at line 10 of file BotObjective.java.
Referenced by com.runehive.content.bot.objective.impl.BankObjective.finish().
WALK_IN_WILDERNESS
com.runehive.content.bot.objective.BotObjective.WALK_IN_WILDERNESS =(new WildernessWalkObjective())
Definition at line 7 of file BotObjective.java.
Referenced by com.runehive.content.bot.objective.impl.WildernessDitchObjective.finish().
WALK_TO_BANK
com.runehive.content.bot.objective.BotObjective.WALK_TO_BANK =(new BankObjective())
Definition at line 9 of file BotObjective.java.
Referenced by com.runehive.content.bot.PlayerBot.endFight(), com.runehive.content.bot.PlayerBot.loopCombat(), com.runehive.content.bot.PlayerBot.postDeath(), and com.runehive.game.task.impl.BotStartupEvent.tick().
WALK_TO_DITCH
com.runehive.content.bot.objective.BotObjective.WALK_TO_DITCH =(new WildernessDitchObjective())
Definition at line 8 of file BotObjective.java.
Referenced by com.runehive.content.bot.objective.impl.RestockObjective.finish().
The documentation for this enum was generated from the following file:
java/com/runehive/content/bot/objective/BotObjective.java