RuneHive-Game: com.runehive.content.skill.impl.herblore.GrimyHerb Enum Reference
com.runehive.content.skill.impl.herblore.GrimyHerb Enum Reference
Holds all the grimy herb data.
Public Member Functions
Item getClean ()
Gets the clean herb.
int getCleanID ()
double getExperience ()
Gets the experience for cleaning a herb.
Item getGrimy ()
Gets the grimy herb.
int getGrimyID ()
int getLevel ()
Gets the level to clean the herb.
GrimyHerb (int grimy, int clean, int level, double experience)
The grimy herb data.
Static Public Member Functions
static Optional< GrimyHerb > forId (int id)
Gets the herb data from the item identification.
Public Attributes
AVANTOE =(211, 261, 48, 10)
CADANTINE =(215, 265, 65, 12.5)
final int clean
The clean herb.
DWARFWEED =(217, 267, 70, 13.8)
final double experience
The experience for cleaning the herb.
final int grimy
The grimy herb.
GUAM =(199, 249, 1, 2.5)
HARRALANDER =(205, 255, 20, 6.3)
IRIT =(209, 259, 40, 8.8)
KWUARM =(213, 263, 54, 11.3)
LANTADYME =(2485, 2481, 67, 13.1)
final int level
The level to clean the herb.
MARRENTILL =(201, 251, 5, 3.8)
RANARR =(207, 257, 25, 7.5)
SNAPDRAGON =(3051, 3000, 59, 11.8)
SPIRITWEED =(12174, 12172, 35, 8)
TARROMIN =(203, 253, 11, 5)
TOADFLAX =(3049, 2998, 30, 8)
TORSTOL =(219, 269, 75, 15)
WERGALI =(14836, 14854, 30, 8)
Detailed Description
Holds all the grimy herb data.
Author
Daniel
Michael | Chex
Definition at line 14 of file GrimyHerb.java.
Constructor & Destructor Documentation
GrimyHerb()
com.runehive.content.skill.impl.herblore.GrimyHerb.GrimyHerb (int grimy, int clean, int level, double experience)
The grimy herb data.
Parameters
grimy The grimy herb.
clean The clean herb.
level The level required to clean the herb.
experience The experience given for cleaning the herb.
Definition at line 61 of file GrimyHerb.java.
{
        this.grimy = grimy;
        this.clean = clean;
        this.level = level;
        this.experience = experience;
    }
References clean, experience, grimy, and level.
Member Function Documentation
forId()
Optional< GrimyHerb > com.runehive.content.skill.impl.herblore.GrimyHerb.forId (int id) static
Gets the herb data from the item identification.
Parameters
id The item identification.
Returns
The grimy herb data.
Definition at line 110 of file GrimyHerb.java.
{
        return Arrays.stream(values()).filter(a -> a.grimy == id).findAny();
    }
Referenced by com.runehive.content.skill.impl.herblore.Herblore.clickItem().
getClean()
Item com.runehive.content.skill.impl.herblore.GrimyHerb.getClean ()
Gets the clean herb.
Returns
The clean herb.
Definition at line 82 of file GrimyHerb.java.
{
        return new Item(clean);
    }
References clean.
Referenced by com.runehive.content.skill.impl.herblore.Herblore.clickItem().
getCleanID()
int com.runehive.content.skill.impl.herblore.GrimyHerb.getCleanID ()
Definition at line 117 of file GrimyHerb.java.
{
        return clean;
    }
References clean.
getExperience()
double com.runehive.content.skill.impl.herblore.GrimyHerb.getExperience ()
Gets the experience for cleaning a herb.
Returns
The experience.
Definition at line 91 of file GrimyHerb.java.
{
        return experience;
    }
References experience.
Referenced by com.runehive.content.skill.impl.herblore.Herblore.clickItem().
getGrimy()
Item com.runehive.content.skill.impl.herblore.GrimyHerb.getGrimy ()
Gets the grimy herb.
Returns
The grimy herb.
Definition at line 73 of file GrimyHerb.java.
{
        return new Item(grimy);
    }
References grimy.
Referenced by com.runehive.content.skill.impl.herblore.Herblore.clickItem().
getGrimyID()
int com.runehive.content.skill.impl.herblore.GrimyHerb.getGrimyID ()
Definition at line 114 of file GrimyHerb.java.
{
        return grimy;
    }
References grimy.
getLevel()
int com.runehive.content.skill.impl.herblore.GrimyHerb.getLevel ()
Gets the level to clean the herb.
Returns
The level required.
Definition at line 100 of file GrimyHerb.java.
{
        return level;
    }
References level.
Referenced by com.runehive.content.skill.impl.herblore.Herblore.clickItem().
Member Data Documentation
AVANTOE
com.runehive.content.skill.impl.herblore.GrimyHerb.AVANTOE =(211, 261, 48, 10)
Definition at line 24 of file GrimyHerb.java.
CADANTINE
com.runehive.content.skill.impl.herblore.GrimyHerb.CADANTINE =(215, 265, 65, 12.5)
Definition at line 27 of file GrimyHerb.java.
clean
final int com.runehive.content.skill.impl.herblore.GrimyHerb.clean
The clean herb.
Definition at line 41 of file GrimyHerb.java.
Referenced by getClean(), getCleanID(), and GrimyHerb().
DWARFWEED
com.runehive.content.skill.impl.herblore.GrimyHerb.DWARFWEED =(217, 267, 70, 13.8)
Definition at line 29 of file GrimyHerb.java.
experience
final double com.runehive.content.skill.impl.herblore.GrimyHerb.experience
The experience for cleaning the herb.
Definition at line 51 of file GrimyHerb.java.
Referenced by getExperience(), and GrimyHerb().
grimy
final int com.runehive.content.skill.impl.herblore.GrimyHerb.grimy
The grimy herb.
Definition at line 35 of file GrimyHerb.java.
Referenced by getGrimy(), getGrimyID(), and GrimyHerb().
GUAM
com.runehive.content.skill.impl.herblore.GrimyHerb.GUAM =(199, 249, 1, 2.5)
Definition at line 15 of file GrimyHerb.java.
HARRALANDER
com.runehive.content.skill.impl.herblore.GrimyHerb.HARRALANDER =(205, 255, 20, 6.3)
Definition at line 18 of file GrimyHerb.java.
IRIT
com.runehive.content.skill.impl.herblore.GrimyHerb.IRIT =(209, 259, 40, 8.8)
Definition at line 22 of file GrimyHerb.java.
KWUARM
com.runehive.content.skill.impl.herblore.GrimyHerb.KWUARM =(213, 263, 54, 11.3)
Definition at line 25 of file GrimyHerb.java.
LANTADYME
com.runehive.content.skill.impl.herblore.GrimyHerb.LANTADYME =(2485, 2481, 67, 13.1)
Definition at line 28 of file GrimyHerb.java.
level
final int com.runehive.content.skill.impl.herblore.GrimyHerb.level
The level to clean the herb.
Definition at line 46 of file GrimyHerb.java.
Referenced by getLevel(), and GrimyHerb().
MARRENTILL
com.runehive.content.skill.impl.herblore.GrimyHerb.MARRENTILL =(201, 251, 5, 3.8)
Definition at line 16 of file GrimyHerb.java.
RANARR
com.runehive.content.skill.impl.herblore.GrimyHerb.RANARR =(207, 257, 25, 7.5)
Definition at line 19 of file GrimyHerb.java.
SNAPDRAGON
com.runehive.content.skill.impl.herblore.GrimyHerb.SNAPDRAGON =(3051, 3000, 59, 11.8)
Definition at line 26 of file GrimyHerb.java.
SPIRITWEED
com.runehive.content.skill.impl.herblore.GrimyHerb.SPIRITWEED =(12174, 12172, 35, 8)
Definition at line 21 of file GrimyHerb.java.
TARROMIN
com.runehive.content.skill.impl.herblore.GrimyHerb.TARROMIN =(203, 253, 11, 5)
Definition at line 17 of file GrimyHerb.java.
TOADFLAX
com.runehive.content.skill.impl.herblore.GrimyHerb.TOADFLAX =(3049, 2998, 30, 8)
Definition at line 20 of file GrimyHerb.java.
TORSTOL
com.runehive.content.skill.impl.herblore.GrimyHerb.TORSTOL =(219, 269, 75, 15)
Definition at line 30 of file GrimyHerb.java.
WERGALI
com.runehive.content.skill.impl.herblore.GrimyHerb.WERGALI =(14836, 14854, 30, 8)
Definition at line 23 of file GrimyHerb.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/herblore/GrimyHerb.java