RuneHive-Game: com.runehive.game.world.entity.combat.effect.CombatEffectType Enum Reference
com.runehive.game.world.entity.combat.effect.CombatEffectType Enum Reference
The enumerated type whose values represent the collection of different combat effect types.
Public Member Functions
CombatEffectType (CombatEffect effect)
Creates a new CombatEffectType.
final CombatEffect getEffect ()
Gets the combat effect that contains the data for this type.
Static Public Member Functions
[static initializer]
Public Attributes
ANTIFIRE_POTION =(new CombatAntifireEffect(AntifireDetails.AntifireType.REGULAR))
POISON =(new CombatPoisonEffect())
SKULL =(new CombatSkullEffect())
SUPER_ANTIFIRE_POTION =(new CombatAntifireEffect(AntifireDetails.AntifireType.SUPER))
TELEBLOCK =(new CombatTeleblockEffect())
VENOM =(new CombatVenomEffect())
Static Public Attributes
static final ImmutableSet< CombatEffectType > TYPES = ImmutableSet.copyOf(values())
Private Attributes
final CombatEffect effect
The combat effect that contains the data for this type.
Detailed Description
The enumerated type whose values represent the collection of different combat effect types.
Author
lare96 http://github.org/lare96
Definition at line 12 of file CombatEffectType.java.
Constructor & Destructor Documentation
CombatEffectType()
com.runehive.game.world.entity.combat.effect.CombatEffectType.CombatEffectType (CombatEffect effect)
Creates a new CombatEffectType.
Definition at line 29 of file CombatEffectType.java.
{
        this.effect = effect;
    }
References effect.
Member Function Documentation
[static initializer]()
com.runehive.game.world.entity.combat.effect.CombatEffectType.[static initializer] static
References com.runehive.game.world.entity.combat.effect.CombatEffect.EFFECTS, and TYPES.
getEffect()
final CombatEffect com.runehive.game.world.entity.combat.effect.CombatEffectType.getEffect ()
Gets the combat effect that contains the data for this type.
Definition at line 34 of file CombatEffectType.java.
{
        return effect;
    }
References effect.
Member Data Documentation
ANTIFIRE_POTION
com.runehive.game.world.entity.combat.effect.CombatEffectType.ANTIFIRE_POTION =(new CombatAntifireEffect(AntifireDetails.AntifireType.REGULAR))
Definition at line 17 of file CombatEffectType.java.
Referenced by com.runehive.content.consume.PotionData.onAntiFireEffect(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.resetEffects().
effect
final CombatEffect com.runehive.game.world.entity.combat.effect.CombatEffectType.effect private
The combat effect that contains the data for this type.
Definition at line 26 of file CombatEffectType.java.
Referenced by CombatEffectType(), and getEffect().
POISON
com.runehive.game.world.entity.combat.effect.CombatEffectType.POISON =(new CombatPoisonEffect())
Definition at line 13 of file CombatEffectType.java.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect(), and com.runehive.game.world.entity.mob.Mob.poison().
SKULL
com.runehive.game.world.entity.combat.effect.CombatEffectType.SKULL =(new CombatSkullEffect())
Definition at line 15 of file CombatEffectType.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.resetEffects().
SUPER_ANTIFIRE_POTION
com.runehive.game.world.entity.combat.effect.CombatEffectType.SUPER_ANTIFIRE_POTION =(new CombatAntifireEffect(AntifireDetails.AntifireType.SUPER))
Definition at line 18 of file CombatEffectType.java.
Referenced by com.runehive.content.consume.PotionData.onAntiFireEffect().
TELEBLOCK
com.runehive.game.world.entity.combat.effect.CombatEffectType.TELEBLOCK =(new CombatTeleblockEffect())
Definition at line 16 of file CombatEffectType.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.resetEffects(), and com.runehive.game.world.entity.combat.magic.MagicImpact.teleblock().
TYPES
final ImmutableSet<CombatEffectType> com.runehive.game.world.entity.combat.effect.CombatEffectType.TYPES = ImmutableSet.copyOf(values()) static
Definition at line 19 of file CombatEffectType.java.
Referenced by [static initializer]().
VENOM
com.runehive.game.world.entity.combat.effect.CombatEffectType.VENOM =(new CombatVenomEffect())
Definition at line 14 of file CombatEffectType.java.
Referenced by com.runehive.content.consume.PotionData.onAntiPoisonEffect(), com.runehive.game.world.entity.mob.player.PlayerAssistant.resetEffects(), and com.runehive.game.world.entity.mob.Mob.venom().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/effect/CombatEffectType.java