RuneHive-Game: com.runehive.content.tittle.Title Enum Reference
com.runehive.content.tittle.Title Enum Reference
Holds all the title data that can be redeemed using the title interface.
Public Member Functions
String[] getRequirement ()
PlayerTitle getTitle ()
Title (PlayerTitle name, String... requirement)
Public Member Functions inherited from com.runehive.util.generic.BooleanInterface< T >
boolean activated (final T player)
Static Public Member Functions
static Optional< Title > forOrdinal (int ordinal)
Public Attributes
BLOODHOUND
CADET
COMMANDER
GLADIATOR
GODLY
LEGEND
MASTER
THE_GREAT
WAR_CHIEF
Private Attributes
final String[] requirement
final PlayerTitle title
Detailed Description
Holds all the title data that can be redeemed using the title interface.
Author
Daniel
Definition at line 15 of file Title.java.
Constructor & Destructor Documentation
Title()
com.runehive.content.tittle.Title.Title (PlayerTitle name, String... requirement)
Definition at line 113 of file Title.java.
{
        this.title = name;
        this.requirement = requirement;
    }
References requirement.
Referenced by forOrdinal().
Member Function Documentation
forOrdinal()
Optional< Title > com.runehive.content.tittle.Title.forOrdinal (int ordinal) static
Definition at line 126 of file Title.java.
{
        for (Title title : values()) {
            if (title.ordinal() == ordinal) {
                return Optional.of(title);
            }
        }
        return Optional.empty();
    }
References Title(), and title.
Referenced by com.runehive.content.tittle.TitleManager.click(), and com.runehive.content.tittle.TitleManager.redeem().
getRequirement()
String[] com.runehive.content.tittle.Title.getRequirement ()
Definition at line 122 of file Title.java.
{
        return requirement;
    }
References requirement.
Referenced by com.runehive.content.tittle.TitleManager.refresh().
getTitle()
PlayerTitle com.runehive.content.tittle.Title.getTitle ()
Definition at line 118 of file Title.java.
{
        return title;
    }
References title.
Referenced by com.runehive.content.tittle.TitleManager.redeem(), and com.runehive.content.tittle.TitleManager.refresh().
Member Data Documentation
BLOODHOUND
com.runehive.content.tittle.Title.BLOODHOUND
Initial value:
=(PlayerTitle.create("Bloodhound", 0xB32424), "Complete the achievement:", "Get a 25 killstreak") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.GET_A_25_KILLSTREAK);
        }
    }
Definition at line 41 of file Title.java.
                                                                                    :", "Get a 25 killstreak") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.GET_A_25_KILLSTREAK);
        }
    },
CADET
com.runehive.content.tittle.Title.CADET
Initial value:
=(PlayerTitle.create("Cadet"), "Complete the achievement:", "Kill 10 players") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.KILL_10_PLAYERS);
        }
    }
Definition at line 17 of file Title.java.
                                                                :", "Kill 10 players") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.KILL_10_PLAYERS);
        }
    },
COMMANDER
com.runehive.content.tittle.Title.COMMANDER
Initial value:
=(PlayerTitle.create("Commander"), "Complete the achievement:", "Kill 500 players") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.KILL_500_PLAYERS);
        }
    }
Definition at line 29 of file Title.java.
                                                                        :", "Kill 500 players") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.KILL_500_PLAYERS);
        }
    },
GLADIATOR
com.runehive.content.tittle.Title.GLADIATOR
Initial value:
=(PlayerTitle.create("Gladiator"), "Complete the achievement:", "Kill 150 players") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.KILL_150_PLAYERS);
        }
    }
Definition at line 23 of file Title.java.
                                                                        :", "Kill 150 players") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.KILL_150_PLAYERS);
        }
    },
GODLY
com.runehive.content.tittle.Title.GODLY
Initial value:
=(PlayerTitle.create("Godly", 0xC7B23E), "Achieve 200M experience in all", "available skills") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.MAX_200M_EXPERIENCE);
        }
    }
Definition at line 59 of file Title.java.
{
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.MAX_200M_EXPERIENCE);
        }
    },
LEGEND
com.runehive.content.tittle.Title.LEGEND
Initial value:
=(PlayerTitle.create("Legend", 0xC25F0E), "Complete the achievement:", "Vote 1,000 times") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.CLAIM_1000_VOTES);
        }
    }
Definition at line 47 of file Title.java.
                                                                            :", "Vote 1,000 times") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.CLAIM_1000_VOTES);
        }
    },
MASTER
com.runehive.content.tittle.Title.MASTER
Initial value:
=(PlayerTitle.create("Master"), "Achieve level 99 in all skills", "") {
        @Override
        public boolean activated(Player player) {
            return player.skills.isMaxed();
        }
    }
Definition at line 53 of file Title.java.
{
        @Override
        public boolean activated(Player player) {
            return player.skills.isMaxed();
        }
    },
requirement
final String [] com.runehive.content.tittle.Title.requirement private
Definition at line 111 of file Title.java.
Referenced by getRequirement(), and Title().
THE_GREAT
com.runehive.content.tittle.Title.THE_GREAT
Initial value:
=(PlayerTitle.create("The Great", 0xC7B23E), "Complete all available achievements", "") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completedAll(player);
        }
    }
Definition at line 65 of file Title.java.
{
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completedAll(player);
        }
    },
title
final PlayerTitle com.runehive.content.tittle.Title.title private
Definition at line 110 of file Title.java.
Referenced by forOrdinal(), and getTitle().
WAR_CHIEF
com.runehive.content.tittle.Title.WAR_CHIEF
Initial value:
=(PlayerTitle.create("War-chief", 0xD053DB), "Complete the achievement:", "Kill 1,000 players") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.KILL_1000_PLAYERS);
        }
    }
Definition at line 35 of file Title.java.
                                                                                  :", "Kill 1,000 players") {
        @Override
        public boolean activated(Player player) {
            return AchievementHandler.completed(player, AchievementList.KILL_1000_PLAYERS);
        }
    },
The documentation for this enum was generated from the following file:
java/com/runehive/content/tittle/Title.java