RuneHive-Game: com.runehive.net.packet.out.SendMinimapState.MinimapState Enum Reference
com.runehive.net.packet.out.SendMinimapState.MinimapState Enum Reference
Represents the state a minimap can be in.
Public Member Functions
int getCode ()
MinimapState (int code)
Public Attributes
HIDDEN =(2)
The state where the map is pitch black, and clicking is disabled.
NORMAL =(0)
The default state where the map is visible and clicking is enabled.
UNCLICKABLE =(1)
The state where the map is visible, but clicking is disabled.
Private Attributes
final int code
Detailed Description
Represents the state a minimap can be in.
Author
Seven
Definition at line 26 of file SendMinimapState.java.
Constructor & Destructor Documentation
MinimapState()
com.runehive.net.packet.out.SendMinimapState.MinimapState.MinimapState (int code)
Definition at line 44 of file SendMinimapState.java.
{
            this.code = code;
        }
References code.
Member Function Documentation
getCode()
int com.runehive.net.packet.out.SendMinimapState.MinimapState.getCode ()
Definition at line 48 of file SendMinimapState.java.
{
            return code;
        }
References code.
Member Data Documentation
code
final int com.runehive.net.packet.out.SendMinimapState.MinimapState.code private
Definition at line 42 of file SendMinimapState.java.
Referenced by getCode(), and MinimapState().
HIDDEN
com.runehive.net.packet.out.SendMinimapState.MinimapState.HIDDEN =(2)
The state where the map is pitch black, and clicking is disabled.
Definition at line 40 of file SendMinimapState.java.
Referenced by com.runehive.content.skill.impl.construction.House.enter(), and com.runehive.content.skill.impl.construction.House.enter().
NORMAL
com.runehive.net.packet.out.SendMinimapState.MinimapState.NORMAL =(0)
The default state where the map is visible and clicking is enabled.
Definition at line 30 of file SendMinimapState.java.
Referenced by com.runehive.content.skill.impl.construction.House.enter(), com.runehive.content.skill.impl.construction.House.enter(), com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onReset(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onReset().
UNCLICKABLE
com.runehive.net.packet.out.SendMinimapState.MinimapState.UNCLICKABLE =(1)
The state where the map is visible, but clicking is disabled.
Definition at line 35 of file SendMinimapState.java.
Referenced by com.runehive.game.world.entity.mob.player.exchange.duel.StakeSession.onRequest(), and com.runehive.game.world.entity.mob.player.exchange.trade.TradeSession.onRequest().
The documentation for this enum was generated from the following file:
java/com/runehive/net/packet/out/SendMinimapState.java