RuneHive-Game: com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData Enum Reference
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData Enum Reference
Public Member Functions
SpawnData (String location, Position position)
Static Public Member Functions
static SpawnData generate ()
Public Attributes
LEVEL_19 =("lvl 15 wild near dark warrior's fortress", new Position(3009, 3637, 0))
LEVEL_28 =("lvl 54 wild near wilderness resource area", new Position(3184, 3948, 0))
LEVEL_41 =("lvl 52 wild near Rouges Castle", new Position(3270, 3933, 0))
LEVEL_53 =("lvl 19 wild near graveyard of shadows", new Position(3146, 3672, 0))
final String location
final Position position
Detailed Description
Definition at line 41 of file DerwenUtility.java.
Constructor & Destructor Documentation
SpawnData()
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.SpawnData (String location, Position position)
Definition at line 50 of file DerwenUtility.java.
{
            this.location = location;
            this.position = position;
        }
References location, and position.
Referenced by generate().
Member Function Documentation
generate()
SpawnData com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.generate () static
Definition at line 55 of file DerwenUtility.java.
{
            return Utility.randomElement(values());
        }
References com.runehive.util.Utility.randomElement(), and SpawnData().
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn().
Member Data Documentation
LEVEL_19
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.LEVEL_19 =("lvl 15 wild near dark warrior's fortress", new Position(3009, 3637, 0))
Definition at line 42 of file DerwenUtility.java.
LEVEL_28
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.LEVEL_28 =("lvl 54 wild near wilderness resource area", new Position(3184, 3948, 0))
Definition at line 43 of file DerwenUtility.java.
LEVEL_41
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.LEVEL_41 =("lvl 52 wild near Rouges Castle", new Position(3270, 3933, 0))
Definition at line 44 of file DerwenUtility.java.
LEVEL_53
com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.LEVEL_53 =("lvl 19 wild near graveyard of shadows", new Position(3146, 3672, 0))
Definition at line 45 of file DerwenUtility.java.
location
final String com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.location
Definition at line 47 of file DerwenUtility.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), and SpawnData().
position
final Position com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.SpawnData.position
Definition at line 48 of file DerwenUtility.java.
Referenced by com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), and SpawnData().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/npc/boss/magearena/DerwenUtility.java