RuneHive-Game: com.runehive.content.skill.impl.slayer.SlayerTab Enum Reference
com.runehive.content.skill.impl.slayer.SlayerTab Enum Reference
Enum for the slayer tab.
Public Member Functions
int getIdentification ()
Gets the itemcontainer identification.
SlayerTab (int identification)
Constructs a new SlayerTab.
Static Public Member Functions
static void refresh (Player player, SlayerTab tab)
Refreshes the tab itemcontainer.
Public Attributes
CONFIRM =(46400)
The confirm itemcontainer - keeps player confirmation on purchase.
DUO =(46800)
The duo itemcontainer - all the duo information.
MAIN =(46700)
The main itemcontainer - all the general information.
REWARD =(46500)
The reward itemcontainer - holds all the rewards for slayer points.
TASK =(46300)
The tasks itemcontainer - displays all the available task for player.
UNLOCK =(46900)
The unlock itemcontainer - holds all the unlockable perks.
Static Private Member Functions
static void setFrame (Player player, int index)
Sets the tab frame.
Private Attributes
final int identification
The itemcontainer identification.
Detailed Description
Enum for the slayer tab.
Author
Daniel
Definition at line 16 of file SlayerTab.java.
Constructor & Destructor Documentation
SlayerTab()
com.runehive.content.skill.impl.slayer.SlayerTab.SlayerTab (int identification)
Constructs a new SlayerTab.
Definition at line 39 of file SlayerTab.java.
{
        this.identification = identification;
    }
References identification.
Referenced by refresh().
Member Function Documentation
getIdentification()
int com.runehive.content.skill.impl.slayer.SlayerTab.getIdentification ()
Gets the itemcontainer identification.
Definition at line 44 of file SlayerTab.java.
{
        return identification;
    }
References identification.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.open().
refresh()
void com.runehive.content.skill.impl.slayer.SlayerTab.refresh (Player player, SlayerTab tab) static
Refreshes the tab itemcontainer.
Definition at line 49 of file SlayerTab.java.
{
        if (tab == null) {
            return;
        }
        SlayerTask task = player.slayer.getTask();
        switch (tab) {
        case MAIN:
            setFrame(player, 0);
//          player.send(new SendNpcDisplay(task == null ? 2044 : task.getNpc()[0], task == null ? 300 : task.getSize()));
            player.send(new SendString(task == null ? "" : "</col>Name: <col=ffffff>" + task.getName(), 46716));
            player.send(new SendString(task == null ? "" : "</col>Level: <col=ffffff>" + task.getCombatLevel(), 46717));
            player.send(new SendString(task == null ? "You do not have a task assigned!" : "</col>Assigned: <col=ffffff>" + player.slayer.getAssigned(), 46718));
            player.send(new SendString(task == null ? "" : "</col>Remaining: <col=ffffff>" + player.slayer.getAmount(), 46735));
            player.send(new SendString(task == null ? "" : "</col>Position: <col=ffffff>" + task.getLocation(), 46736));
            player.send(new SendString("Tasks assigned:\\n<col=ffffff>" + player.slayer.getTotalAssigned(), 46737));
            player.send(new SendString("Tasks completed:\\n<col=ffffff>" + player.slayer.getTotalCompleted(), 46738));
            player.send(new SendString("Tasks Cancelled:\\n<col=ffffff>" + player.slayer.getTotalCancelled(), 46739));
            player.send(new SendString("Accumulated points:\\n<col=ffffff>" + player.slayer.getTotalPoints(), 46740));
            for (int index = 0, string = 46753; index < 5; index++, string += 3) {
                player.send(new SendTooltip("", string - 1));
                player.send(new SendString("", string));
            }
            for (int index = 0, string = 46753; index < player.slayer.getBlocked().size(); index++, string += 3) {
                String name = player.slayer.getBlocked().get(index).getName();
                player.send(new SendTooltip("Unblock <col=FF981F>" + name + "</col>", string - 1));
                player.send(new SendString(name, string));
            }
            player.send(new SendString(Utility.formatDigits(player.slayer.getPoints()) + "\\nPoints", 46714));
            player.send(new SendString("Blocked tasks:  (" + player.slayer.getBlocked().size() + "/5)", 46728));
            break;
        case DUO:
            setFrame(player, 1);
            player.send(new SendString("Current slayer partner: None!", 46811));
            break;
        case UNLOCK:
            setFrame(player, 2);
            int string = 46911;
            for (SlayerUnlockable unlockable : SlayerUnlockable.values()) {
                player.send(new SendTooltip("Purchase <col=FF981F>" + unlockable.getName() + "</col>", string));
                string++;
                player.send(new SendString(unlockable.getName(), string));
                string++;
                player.send(new SendString(unlockable.getDescription(), string));
                string++;
                player.send(new SendString(unlockable.getCost() + " points", string));
                string++;
                player.send(new SendConfig(560 + unlockable.ordinal(), player.slayer.getUnlocked().contains(unlockable) ? 0 : 1));
                string++;
                player.send(new SendItemOnInterfaceSlot(string, new Item(unlockable.getItem(), 1), 0));
                string++;
            }
            player.send(new SendScrollbar(46910, 310));
            break;
        case REWARD:
            player.send(new SendItemOnInterface(46503, Slayer.ITEMS));
            setFrame(player, 3);
            break;
        case CONFIRM:
            SlayerUnlockable unlockable = player.attributes.get("SLAYER_CONFIRM_KEY", SlayerUnlockable.class);
            player.send(new SendString(unlockable.getName(), 46403));
            player.send(new SendString(unlockable.getDescription(), 46404));
            player.send(new SendString("Pay " + Utility.formatDigits(unlockable.getCost()) + " points?", 46405));
            Item[] items = new Item[3];
            for (int index = 0; index < 3; index++) {
                items[index] = new Item(unlockable.getItem());
                items[index].setAmount(0);
            }
            player.send(new SendItemOnInterface(46414, items));
            break;
        case TASK:
            List<SlayerTask> task_list;
            task_list = Arrays.asList(SlayerTask.values());
            int line = 46321;
            for (int index = 0; index < 35; index++) {
                player.send(new SendString("", line + index));
            }
            for (SlayerTask tasks : task_list) {
                line++;
                player.send(new SendString(tasks.getName(), line));
                line++;
                player.send(new SendString(tasks.getCombatLevel(), line));
                line++;
                player.send(new SendString(tasks.getLevel(), line));
                line++;
            }
            player.send(new SendScrollbar(46320, 400));
            break;
        }
    }
References com.runehive.game.world.entity.mob.Mob.attributes, CONFIRM, DUO, com.runehive.util.Utility.formatDigits(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.content.skill.impl.slayer.Slayer.getAmount(), com.runehive.content.skill.impl.slayer.Slayer.getAssigned(), com.runehive.content.skill.impl.slayer.Slayer.getBlocked(), com.runehive.content.skill.impl.slayer.SlayerTask.getCombatLevel(), com.runehive.content.skill.impl.slayer.SlayerUnlockable.getCost(), com.runehive.content.skill.impl.slayer.SlayerUnlockable.getDescription(), com.runehive.content.skill.impl.slayer.SlayerUnlockable.getItem(), com.runehive.content.skill.impl.slayer.SlayerTask.getLocation(), com.runehive.content.skill.impl.slayer.SlayerTask.getName(), com.runehive.content.skill.impl.slayer.SlayerUnlockable.getName(), com.runehive.content.skill.impl.slayer.Slayer.getPoints(), com.runehive.content.skill.impl.slayer.Slayer.getTask(), com.runehive.content.skill.impl.slayer.Slayer.getTotalAssigned(), com.runehive.content.skill.impl.slayer.Slayer.getTotalCancelled(), com.runehive.content.skill.impl.slayer.Slayer.getTotalCompleted(), com.runehive.content.skill.impl.slayer.Slayer.getTotalPoints(), com.runehive.content.skill.impl.slayer.Slayer.getUnlocked(), com.runehive.content.skill.impl.slayer.Slayer.ITEMS, MAIN, REWARD, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.items.Item.setAmount(), setFrame(), com.runehive.game.world.entity.mob.player.Player.slayer, SlayerTab(), TASK, and UNLOCK.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.assign(), com.runehive.content.skill.impl.slayer.Slayer.block(), com.runehive.content.skill.impl.slayer.Slayer.cancel(), com.runehive.content.skill.impl.slayer.Slayer.open(), and com.runehive.content.skill.impl.slayer.Slayer.unblock().
setFrame()
void com.runehive.content.skill.impl.slayer.SlayerTab.setFrame (Player player, int index) static private
Sets the tab frame.
Definition at line 155 of file SlayerTab.java.
{
        player.send(new SendConfig(710, index));
        player.send(new SendString("<col=" + (index == 0 ? "FF981F" : "ff9933") + ">Main", 46710));
        player.send(new SendString("<col=" + (index == 1 ? "FF981F" : "ff9933") + ">Duo", 46711));
        player.send(new SendString("<col=" + (index == 2 ? "FF981F" : "ff9933") + ">Unlocks", 46712));
        player.send(new SendString("<col=" + (index == 3 ? "FF981F" : "ff9933") + ">Store", 46713));
    }
References com.runehive.game.world.entity.mob.player.Player.send().
Referenced by refresh().
Member Data Documentation
CONFIRM
com.runehive.content.skill.impl.slayer.SlayerTab.CONFIRM =(46400)
The confirm itemcontainer - keeps player confirmation on purchase.
Definition at line 33 of file SlayerTab.java.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.confirm(), and refresh().
DUO
com.runehive.content.skill.impl.slayer.SlayerTab.DUO =(46800)
The duo itemcontainer - all the duo information.
Definition at line 21 of file SlayerTab.java.
Referenced by refresh().
identification
final int com.runehive.content.skill.impl.slayer.SlayerTab.identification private
The itemcontainer identification.
Definition at line 36 of file SlayerTab.java.
Referenced by getIdentification(), and SlayerTab().
MAIN
com.runehive.content.skill.impl.slayer.SlayerTab.MAIN =(46700)
The main itemcontainer - all the general information.
Definition at line 18 of file SlayerTab.java.
Referenced by com.runehive.game.plugin.PluginContext.onClick(), refresh(), and com.runehive.content.dialogue.impl.NieveDialogue.sendDialogues().
REWARD
com.runehive.content.skill.impl.slayer.SlayerTab.REWARD =(46500)
The reward itemcontainer - holds all the rewards for slayer points.
Definition at line 27 of file SlayerTab.java.
Referenced by refresh().
TASK
com.runehive.content.skill.impl.slayer.SlayerTab.TASK =(46300)
The tasks itemcontainer - displays all the available task for player.
Definition at line 30 of file SlayerTab.java.
Referenced by refresh().
UNLOCK
com.runehive.content.skill.impl.slayer.SlayerTab.UNLOCK =(46900)
The unlock itemcontainer - holds all the unlockable perks.
Definition at line 24 of file SlayerTab.java.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.purchase(), and refresh().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/slayer/SlayerTab.java