RuneHive-Game: com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial Enum Reference
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial Enum Reference
The enumerated type whose elements represent the combat special attacks.
Public Member Functions
CombatSpecial (int[] ids, int amount, CombatStrategy< Player > strategy)
Creates a new CombatSpecial.
void disable (Player player, boolean clicked)
void drain (Player player)
Drains the special bar for player.
void enable (Player player)
final int getAmount ()
Gets the amount of special energy drained by this attack.
final int[] getIds ()
Gets the identifiers for the weapons that perform this special.
CombatStrategy< Player > getStrategy ()
Executes exactly when player activates the special bar.
Static Public Member Functions
static void assign (Player player)
Updates the weapon itemcontainer with a special bar if needed.
static void drain (Player player, int toDrain)
static Optional< CombatSpecial > forId (int weapon)
static void restore (Player player, int amount)
Restores the special bar for player.
static void updateSpecialAmount (Player player)
Updates the special bar with the amount of special energy player has.
Public Attributes
ABYSSAL_BLUDGEN =(new int[]{13263}, 50, AbyssalBludgen.get())
ABYSSAL_DAGGER =(new int[]{13265}, 50, AbyssalDagger.get())
ABYSSAL_TENTACLE_WHIP =(new int[]{12006}, 50, AbyssalTentacleWhip.get())
ABYSSAL_WHIP =(new int[]{4151, 80, 21371, 15441, 15442, 15443, 15444}, 50, AbyssalWhip.get())
ANCIENT_GODSWORD =(new int[]{26233}, 50, AncientGodsword.get())
ARMADYL_CROSSBOW =(new int[]{11785}, 40, ArmadylCrossbow.get())
ARMADYL_GODSWORD =(new int[]{11802, 81, 20368}, 50, ArmadylGodsword.get())
BALLISTA =(new int[]{19478, 19481}, 55, Ballista.get())
BANDOS_GODSWORD =(new int[]{11804, 20370}, 50, BandosGodsword.get())
BLOW_PIPE =(new int[]{12926}, 50, Blowpipe.get())
DARK_BOW =(new int[]{11235, 12765, 12766, 12767, 12768}, 55, DarkBow.get())
DINHS_BULWARK =(new int[]{21015}, 50, DinhsBulwark.get())
DRAGON_2H =(new int[]{7158}, 60, Dragon2h.get())
DRAGON_AXE
DRAGON_BATTLEAXE
DRAGON_CLAWS =(new int[]{13652, 20784}, 50, DragonClaws.get())
DRAGON_DAGGER =(new int[]{1215, 1231, 5680, 5698}, 25, DragonDagger.get())
DRAGON_HALBERD =(new int[]{3204}, 30, DragonHaldberd.get())
DRAGON_HARPOON
DRAGON_KNIVES =(new int[] { 22804 }, 25, DragonKnife.get())
DRAGON_LONGSWORD =(new int[]{1305}, 25, DragonLongsword.get())
DRAGON_MACE =(new int[]{1434}, 25, DragonMace.get())
DRAGON_PICKAXE
DRAGON_SCIMITAR =(new int[]{4587, 20000}, 55, DragonScimitar.get())
DRAGON_SPEAR =(new int[]{1249, 1263, 5730, 3176, 5716, 11824, 11889}, 25, DragonSpear.get())
DRAGON_THROWNAXE
DRAGON_WARHAMMER =(new int[]{13576}, 50, DragonWarhammer.get())
GRANITE_MAUL
MAGIC_SHORTBOW =(new int[]{861, 12788}, 55, MagicShortbow.get())
OSMUM_FANG =(new int[]{26219, 27246}, 25, OsmumFang.get())
SARADOMIN_GODSWORD =(new int[]{11806, 20372}, 50, SaradominGodsword.get())
SARADOMIN_SWORD =(new int[]{11838, 12809}, 100, SaradominSword.get())
STAFF_OF_DEAD
STAFF_OF_THE_DEAD
TOXIC_STAFF_OF_THE_DEAD
VESTAS_LONGSWORD =(new int[]{22613}, 25, VestaLongsword.get())
ZAMORAK_GODSWORD =(new int[]{11808, 20374}, 50, ZamorakGodsword.get())
ZARYTE_CROSSBOW =(new int[]{26374}, 75, ZaryteCrossbow.get())
Private Attributes
final int amount
The amount of special energy drained by this attack.
final int[] ids
The identifiers for the weapons that perform this special.
final CombatStrategy< Player > strategy
The strength bonus added when performing this special attack.
Detailed Description
The enumerated type whose elements represent the combat special attacks.
Author
Chex
Daniel
Definition at line 27 of file CombatSpecial.java.
Constructor & Destructor Documentation
CombatSpecial()
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.CombatSpecial (int[] ids, int amount, CombatStrategy< Player > strategy)
Creates a new CombatSpecial.
Parameters
ids the identifiers for the weapons that perform this special.
amount the amount of special energy drained by this attack.
Definition at line 249 of file CombatSpecial.java.
{
        this.ids = ids;
        this.amount = amount;
        this.strategy = strategy;
    }
References amount, ids, and strategy.
Referenced by assign(), and forId().
Member Function Documentation
assign()
void com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.assign (Player player) static
Updates the weapon itemcontainer with a special bar if needed.
Parameters
player the player to update the itemcontainer for.
Definition at line 325 of file CombatSpecial.java.
{
        if (player.getCombatSpecial() != null) {
            player.getCombatSpecial().disable(player, false);
        }
        if (player.getWeapon().getSpecialBar() == -1) {
            player.setCombatSpecial(null);
            player.send(new SendInterfaceLayer(player.getWeapon().getSpecialBar(), true));
            return;
        }
        Item item = player.equipment.get(Equipment.WEAPON_SLOT);
        if (item == null) {
            player.setCombatSpecial(null);
            player.send(new SendInterfaceLayer(player.getWeapon().getSpecialBar(), true));
            return;
        }
        Optional<CombatSpecial> special = Arrays.stream(CombatSpecial.values()).filter(c -> Arrays.stream(c.getIds()).anyMatch(id -> item.getId() == id)).findFirst();
        if (special.isPresent()) {
            player.send(new SendInterfaceLayer(player.getWeapon().getSpecialBar(), false));
            player.setCombatSpecial(special.get());
            return;
        }
        player.send(new SendInterfaceLayer(player.getWeapon().getSpecialBar(), true));
        player.setCombatSpecial(null);
    }
References CombatSpecial(), com.runehive.game.world.items.Item.getId(), and com.runehive.game.world.items.containers.equipment.Equipment.WEAPON_SLOT.
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface(), and com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute().
disable()
void com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.disable (Player player, boolean clicked)
Definition at line 388 of file CombatSpecial.java.
{
        if (player.isSpecialActivated()) {
            player.send(new SendConfig(301, 0));
            player.setSpecialActivated(false);
        }
    }
Referenced by drain().
drain() [1/2]
void com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.drain (Player player)
Drains the special bar for player.
Parameters
player the player who's special bar will be drained.
Definition at line 274 of file CombatSpecial.java.
{
        player.send(new SendSpecialEnabled(0));
        player.getSpecialPercentage().decrementAndGet(amount, 0);
        updateSpecialAmount(player);
        disable(player, false);
    }
References amount, disable(), and updateSpecialAmount().
Referenced by com.runehive.game.world.entity.combat.strategy.player.custom.ToxicBlowpipeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerMeleeStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.PlayerRangedStrategy.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DinhsBulwark.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.Dragon2h.start(), com.runehive.game.world.entity.combat.strategy.player.special.melee.GraniteMaul.start(), and com.runehive.game.world.entity.combat.strategy.player.special.range.Blowpipe.start().
drain() [2/2]
void com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.drain (Player player, int toDrain) static
Definition at line 281 of file CombatSpecial.java.
{
        player.send(new SendSpecialEnabled(0));
        player.getSpecialPercentage().decrementAndGet(toDrain, 0);
        updateSpecialAmount(player);
    }
References updateSpecialAmount().
enable()
void com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.enable (Player player)
Definition at line 372 of file CombatSpecial.java.
{
        if (Activity.evaluate(player, it -> !it.canUseSpecial(player))) {
            return;
        }
        if (!player.isSpecialActivated()) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.send(new SendConfig(301, 1));
            player.setSpecialActivated(true);
        }
    }
References com.runehive.content.activity.Activity.evaluate().
forId()
Optional< CombatSpecial > com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.forId (int weapon) static
Definition at line 255 of file CombatSpecial.java.
{
        Optional<CombatSpecial> special = Arrays.stream(CombatSpecial.values()).filter(c -> Arrays.stream(c.getIds()).anyMatch(id -> weapon == id)).findFirst();
        return special;
    }
References CombatSpecial().
getAmount()
final int com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.getAmount ()
Gets the amount of special energy drained by this attack.
Returns
the amount of special energy drained.
Definition at line 368 of file CombatSpecial.java.
{
        return amount;
    }
References amount.
getIds()
final int[] com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.getIds ()
Gets the identifiers for the weapons that perform this special.
Returns
the identifiers for the weapons.
Definition at line 359 of file CombatSpecial.java.
{
        return ids;
    }
References ids.
getStrategy()
CombatStrategy< Player > com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.getStrategy ()
Executes exactly when player activates the special bar.
Returns
the combat strategy
Definition at line 265 of file CombatSpecial.java.
{
        return strategy;
    }
References strategy.
restore()
void com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.restore (Player player, int amount) static
Restores the special bar for player.
Parameters
player the player who's special bar will be restored.
amount the amount of energy to restore to the special bar.
Definition at line 294 of file CombatSpecial.java.
{
        player.getSpecialPercentage().incrementAndGet(amount, 100);
        updateSpecialAmount(player);
    }
References amount, and updateSpecialAmount().
Referenced by com.runehive.content.bot.objective.impl.RestockObjective.init(), com.runehive.content.lms.LMSGame.onKill(), com.runehive.content.bot.PlayerBot.PlayerBot(), com.runehive.content.bot.PlayerBot.postDeath(), com.runehive.game.world.entity.mob.player.PlayerAssistant.restore(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.updateSpecial().
updateSpecialAmount()
void com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.updateSpecialAmount (Player player) static
Updates the special bar with the amount of special energy player has.
Parameters
player the player who's special bar will be updated.
Definition at line 305 of file CombatSpecial.java.
{
        if (player.getWeapon().getSpecialBar() == -1 || player.getWeapon().getSpecialMeter() == -1) {
            return;
        }
        int specialBar = player.getWeapon().getSpecialMeter();
        int specialAmount = player.getSpecialPercentage().get() / 10;
        player.send(new SendSpecialAmount());
        for (int i = 10; i > 0; i--) {
            player.send(new SendMoveComponent(specialAmount >= i ? 500 : 0, 0, --specialBar));
        }
    }
Referenced by com.runehive.game.world.entity.combat.weapon.WeaponInterface.defaultWeaponInterface(), drain(), drain(), com.runehive.game.world.entity.combat.weapon.WeaponInterface.execute(), and restore().
Member Data Documentation
ABYSSAL_BLUDGEN
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ABYSSAL_BLUDGEN =(new int[]{13263}, 50, AbyssalBludgen.get())
Definition at line 32 of file CombatSpecial.java.
ABYSSAL_DAGGER
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ABYSSAL_DAGGER =(new int[]{13265}, 50, AbyssalDagger.get())
Definition at line 31 of file CombatSpecial.java.
ABYSSAL_TENTACLE_WHIP
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ABYSSAL_TENTACLE_WHIP =(new int[]{12006}, 50, AbyssalTentacleWhip.get())
Definition at line 30 of file CombatSpecial.java.
ABYSSAL_WHIP
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ABYSSAL_WHIP =(new int[]{4151, 80, 21371, 15441, 15442, 15443, 15444}, 50, AbyssalWhip.get())
Definition at line 29 of file CombatSpecial.java.
amount
final int com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.amount private
The amount of special energy drained by this attack.
Definition at line 236 of file CombatSpecial.java.
Referenced by CombatSpecial(), drain(), getAmount(), and restore().
ANCIENT_GODSWORD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ANCIENT_GODSWORD =(new int[]{26233}, 50, AncientGodsword.get())
Definition at line 133 of file CombatSpecial.java.
ARMADYL_CROSSBOW
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ARMADYL_CROSSBOW =(new int[]{11785}, 40, ArmadylCrossbow.get())
Definition at line 140 of file CombatSpecial.java.
ARMADYL_GODSWORD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ARMADYL_GODSWORD =(new int[]{11802, 81, 20368}, 50, ArmadylGodsword.get())
Definition at line 130 of file CombatSpecial.java.
BALLISTA
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.BALLISTA =(new int[]{19478, 19481}, 55, Ballista.get())
Definition at line 139 of file CombatSpecial.java.
BANDOS_GODSWORD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.BANDOS_GODSWORD =(new int[]{11804, 20370}, 50, BandosGodsword.get())
Definition at line 132 of file CombatSpecial.java.
BLOW_PIPE
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.BLOW_PIPE =(new int[]{12926}, 50, Blowpipe.get())
Definition at line 136 of file CombatSpecial.java.
DARK_BOW
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DARK_BOW =(new int[]{11235, 12765, 12766, 12767, 12768}, 55, DarkBow.get())
Definition at line 137 of file CombatSpecial.java.
DINHS_BULWARK
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DINHS_BULWARK =(new int[]{21015}, 50, DinhsBulwark.get())
Definition at line 223 of file CombatSpecial.java.
DRAGON_2H
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_2H =(new int[]{7158}, 60, Dragon2h.get())
Definition at line 45 of file CombatSpecial.java.
DRAGON_AXE
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_AXE
Initial value:
=(new int[]{6739, 13241, 20011}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.skills.setLevel(8, player.skills.getLevel(Skill.WOODCUTTING) + 3);
            player.animate(new Animation(2876, UpdatePriority.HIGH), true);
            player.graphic(new Graphic(479, true, UpdatePriority.HIGH));
            player.send(new SendMessage("Your Woodcutting rate has increased by x2!"));
            drain(player, 100);
        }
    }
Definition at line 63 of file CombatSpecial.java.
                        {6739, 13241, 20011}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.skills.setLevel(8, player.skills.getLevel(Skill.WOODCUTTING) + 3);
            player.animate(new Animation(2876, UpdatePriority.HIGH), true);
            player.graphic(new Graphic(479, true, UpdatePriority.HIGH));
            player.send(new SendMessage("Your Woodcutting rate has increased by x2!"));
            drain(player, 100);
        }
    },
DRAGON_BATTLEAXE
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_BATTLEAXE
Initial value:
=(new int[]{1377}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.speak("Raarrrrrgggggghhhhhhh!");
            player.animate(new Animation(1056, UpdatePriority.HIGH), true);
            player.graphic(new Graphic(246, UpdatePriority.HIGH));
            player.skills.modifyLevel(level -> level - level / 10, Skill.ATTACK);
            player.skills.modifyLevel(level -> level - level / 10, Skill.DEFENCE);
            player.skills.modifyLevel(level -> level - level / 10, Skill.RANGED);
            player.skills.modifyLevel(level -> level - level / 10, Skill.MAGIC);
            player.skills.modifyLevel(level -> level + 10 + (player.skills.getMaxLevel(Skill.STRENGTH) - level) / 4, Skill.STRENGTH, 0, 120);
            player.skills.refresh(Skill.ATTACK);
            player.skills.refresh(Skill.DEFENCE);
            player.skills.refresh(Skill.STRENGTH);
            player.skills.refresh(Skill.RANGED);
            player.skills.refresh(Skill.MAGIC);
            drain(player, 100);
        }
    }
Definition at line 104 of file CombatSpecial.java.
                              {1377}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.speak("Raarrrrrgggggghhhhhhh!");
            player.animate(new Animation(1056, UpdatePriority.HIGH), true);
            player.graphic(new Graphic(246, UpdatePriority.HIGH));
            player.skills.modifyLevel(level -> level - level / 10, Skill.ATTACK);
            player.skills.modifyLevel(level -> level - level / 10, Skill.DEFENCE);
            player.skills.modifyLevel(level -> level - level / 10, Skill.RANGED);
            player.skills.modifyLevel(level -> level - level / 10, Skill.MAGIC);
            player.skills.modifyLevel(level -> level + 10 + (player.skills.getMaxLevel(Skill.STRENGTH) - level) / 4, Skill.STRENGTH, 0, 120);
            player.skills.refresh(Skill.ATTACK);
            player.skills.refresh(Skill.DEFENCE);
            player.skills.refresh(Skill.STRENGTH);
            player.skills.refresh(Skill.RANGED);
            player.skills.refresh(Skill.MAGIC);
            drain(player, 100);
        }
    },
DRAGON_CLAWS
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_CLAWS =(new int[]{13652, 20784}, 50, DragonClaws.get())
Definition at line 42 of file CombatSpecial.java.
DRAGON_DAGGER
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_DAGGER =(new int[]{1215, 1231, 5680, 5698}, 25, DragonDagger.get())
Definition at line 36 of file CombatSpecial.java.
DRAGON_HALBERD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_HALBERD =(new int[]{3204}, 30, DragonHaldberd.get())
Definition at line 40 of file CombatSpecial.java.
DRAGON_HARPOON
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_HARPOON
Initial value:
=(new int[]{21028,25373,21031}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.skills.setLevel(Skill.FISHING, player.skills.getLevel(Skill.FISHING) + 3);
            player.animate(new Animation(1056, UpdatePriority.HIGH), true);
            player.graphic(new Graphic(246, UpdatePriority.HIGH));
            player.speak("Here fishy fishies!");
            drain(player, 100);
        }
    }
Definition at line 77 of file CombatSpecial.java.
                            {21028,25373,21031}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.skills.setLevel(Skill.FISHING, player.skills.getLevel(Skill.FISHING) + 3);
            player.animate(new Animation(1056, UpdatePriority.HIGH), true);
            player.graphic(new Graphic(246, UpdatePriority.HIGH));
            player.speak("Here fishy fishies!");
            drain(player, 100);
        }
    },
DRAGON_KNIVES
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_KNIVES =(new int[] { 22804 }, 25, DragonKnife.get())
Definition at line 226 of file CombatSpecial.java.
DRAGON_LONGSWORD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_LONGSWORD =(new int[]{1305}, 25, DragonLongsword.get())
Definition at line 38 of file CombatSpecial.java.
DRAGON_MACE
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_MACE =(new int[]{1434}, 25, DragonMace.get())
Definition at line 44 of file CombatSpecial.java.
DRAGON_PICKAXE
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_PICKAXE
Initial value:
=(new int[]{11920, 12797, 23677, 25376,27695,13243}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.skills.setLevel(Skill.MINING, player.skills.getLevel(Skill.MINING) + 3);
            player.animate(new Animation(7138, UpdatePriority.HIGH), true);
            player.speak("Smashing!");
            drain(player, 100);
        }
    }
Definition at line 91 of file CombatSpecial.java.
                            {11920, 12797, 23677, 25376,27695,13243}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.skills.setLevel(Skill.MINING, player.skills.getLevel(Skill.MINING) + 3);
            player.animate(new Animation(7138, UpdatePriority.HIGH), true);
            player.speak("Smashing!");
            drain(player, 100);
        }
    },
DRAGON_SCIMITAR
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_SCIMITAR =(new int[]{4587, 20000}, 55, DragonScimitar.get())
Definition at line 39 of file CombatSpecial.java.
DRAGON_SPEAR
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_SPEAR =(new int[]{1249, 1263, 5730, 3176, 5716, 11824, 11889}, 25, DragonSpear.get())
Definition at line 43 of file CombatSpecial.java.
DRAGON_THROWNAXE
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_THROWNAXE
Initial value:
=(new int[]{20849}, 25, DragonThrownaxe.get()) {
        @Override
        public void enable(Player player) {
            super.enable(player);
            if (player.isSpecialActivated()) {
                player.getCombat().setCooldown(0);
            }
        }
    }
Definition at line 142 of file CombatSpecial.java.
                              {20849}, 25, DragonThrownaxe.get()) {
        @Override
        public void enable(Player player) {
            super.enable(player);
            if (player.isSpecialActivated()) {
                player.getCombat().setCooldown(0);
            }
        }
    },
DRAGON_WARHAMMER
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.DRAGON_WARHAMMER =(new int[]{13576}, 50, DragonWarhammer.get())
Definition at line 37 of file CombatSpecial.java.
GRANITE_MAUL
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.GRANITE_MAUL
Definition at line 186 of file CombatSpecial.java.
                          {4153, 24225}, 50, GraniteMaul.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.setSpecialActivated(true);
            player.send(new SendConfig(301, 1));
            Combat<Player> combat = player.getCombat();
            Mob defender = combat.getLastVictim();
            if (combat.isAttacking(defender)) {
                combat.performChecks(defender);
                combat.submitStrategy(defender, GraniteMaul.get());
            }
        }
        @Override
        public void disable(Player player, boolean clicked) {
            // TODO: potential bug when specials are disabled other
            // TODO: than in the spec bar, example: switching weapons
            boolean doubleSpec = !player.attributes.has("granite-maul-spec");
            int current = player.getSpecialPercentage().intValue();
            if (clicked && doubleSpec && current >= getAmount()) {
                player.attributes.set("granite-maul-spec", true);
            } else {
                player.attributes.remove("granite-maul-spec");
                super.disable(player, clicked);
            }
        }
    },
ids
final int [] com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ids private
The identifiers for the weapons that perform this special.
Definition at line 231 of file CombatSpecial.java.
Referenced by CombatSpecial(), and getIds().
MAGIC_SHORTBOW
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.MAGIC_SHORTBOW =(new int[]{861, 12788}, 55, MagicShortbow.get())
Definition at line 138 of file CombatSpecial.java.
OSMUM_FANG
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.OSMUM_FANG =(new int[]{26219, 27246}, 25, OsmumFang.get())
Definition at line 41 of file CombatSpecial.java.
SARADOMIN_GODSWORD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.SARADOMIN_GODSWORD =(new int[]{11806, 20372}, 50, SaradominGodsword.get())
Definition at line 129 of file CombatSpecial.java.
SARADOMIN_SWORD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.SARADOMIN_SWORD =(new int[]{11838, 12809}, 100, SaradominSword.get())
Definition at line 153 of file CombatSpecial.java.
STAFF_OF_DEAD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.STAFF_OF_DEAD
Initial value:
=(new int[]{11791, 12904}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.staffOfDeadSpecial.reset();
            player.animate(1720, true);
            player.graphic(new Graphic(1228, 0, 13107200, UpdatePriority.HIGH));
            player.skills.setLevel(1, 125);
            player.send(new SendMessage("Your defence has been boosted!"));
            drain(player, 100);
        }
    }
Definition at line 48 of file CombatSpecial.java.
                           {11791, 12904}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.staffOfDeadSpecial.reset();
            player.animate(1720, true);
            player.graphic(new Graphic(1228, 0, 13107200, UpdatePriority.HIGH));
            player.skills.setLevel(1, 125);
            player.send(new SendMessage("Your defence has been boosted!"));
            drain(player, 100);
        }
    },
STAFF_OF_THE_DEAD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.STAFF_OF_THE_DEAD
Initial value:
=(new int[]{11791, 12904}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.animate(1720, true);
            player.graphic(new Graphic(1228, 0, 13107200, UpdatePriority.HIGH));
            player.skills.setLevel(1, 125);
            player.staffOfDeadSpecial.reset();
            player.send(new SendMessage("Your defence has been boosted!"));
            drain(player, 100);
        }
    }
Definition at line 156 of file CombatSpecial.java.
                               {11791, 12904}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.animate(1720, true);
            player.graphic(new Graphic(1228, 0, 13107200, UpdatePriority.HIGH));
            player.skills.setLevel(1, 125);
            player.staffOfDeadSpecial.reset();
            player.send(new SendMessage("Your defence has been boosted!"));
            drain(player, 100);
        }
    },
strategy
final CombatStrategy<Player> com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.strategy private
The strength bonus added when performing this special attack.
Definition at line 241 of file CombatSpecial.java.
Referenced by CombatSpecial(), and getStrategy().
TOXIC_STAFF_OF_THE_DEAD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.TOXIC_STAFF_OF_THE_DEAD
Initial value:
=(new int[]{12904}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.animate(1720, true);
            player.graphic(new Graphic(1228, 0, 13107200, UpdatePriority.HIGH));
            player.skills.setLevel(1, 125);
            player.staffOfDeadSpecial.reset();
            player.send(new SendMessage("Your defence has been boosted!"));
            drain(player, 100);
        }
    }
Definition at line 171 of file CombatSpecial.java.
                                     {12904}, 100, DefaultMelee.get()) {
        @Override
        public void enable(Player player) {
            if (player.getSpecialPercentage().intValue() < player.getCombatSpecial().getAmount()) {
                player.send(new SendMessage("You do not have enough special energy left!"));
                return;
            }
            player.animate(1720, true);
            player.graphic(new Graphic(1228, 0, 13107200, UpdatePriority.HIGH));
            player.skills.setLevel(1, 125);
            player.staffOfDeadSpecial.reset();
            player.send(new SendMessage("Your defence has been boosted!"));
            drain(player, 100);
        }
    },
VESTAS_LONGSWORD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.VESTAS_LONGSWORD =(new int[]{22613}, 25, VestaLongsword.get())
Definition at line 46 of file CombatSpecial.java.
ZAMORAK_GODSWORD
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ZAMORAK_GODSWORD =(new int[]{11808, 20374}, 50, ZamorakGodsword.get())
Definition at line 131 of file CombatSpecial.java.
ZARYTE_CROSSBOW
com.runehive.game.world.entity.combat.strategy.player.special.CombatSpecial.ZARYTE_CROSSBOW =(new int[]{26374}, 75, ZaryteCrossbow.get())
Definition at line 141 of file CombatSpecial.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/strategy/player/special/CombatSpecial.java