RuneHive-Game: com.runehive.content.collectionlog.CollectionLogPage Enum Reference
com.runehive.content.collectionlog.CollectionLogPage Enum Reference
Public Member Functions
int getButton ()
CollectionCategory getCategory ()
Static Public Member Functions
[static initializer]
static CollectionLogPage forButton (int button)
Public Attributes
BOSSES =(-21030, CollectionCategory.BOSSES)
CLUES =(-21026, CollectionCategory.CLUES)
MINIGAMES =(-21024, CollectionCategory.MINIGAMES)
OTHER =(-21022, CollectionCategory.OTHER)
RAIDS =(-21028, CollectionCategory.RAIDS)
Private Member Functions
CollectionLogPage (int button, CollectionCategory category)
Private Attributes
final int button
final CollectionCategory category
Static Private Attributes
static HashMap< Integer, CollectionLogPage > pages
Detailed Description
Definition at line 5 of file CollectionLogPage.java.
Constructor & Destructor Documentation
CollectionLogPage()
com.runehive.content.collectionlog.CollectionLogPage.CollectionLogPage (int button, CollectionCategory category) private
Definition at line 16 of file CollectionLogPage.java.
{
        this.button = button;
        this.category = category;
    }
References button, and category.
Referenced by [static initializer]().
Member Function Documentation
[static initializer]()
com.runehive.content.collectionlog.CollectionLogPage.[static initializer] static
References button, CollectionLogPage(), forButton(), and pages.
forButton()
CollectionLogPage com.runehive.content.collectionlog.CollectionLogPage.forButton (int button) static
Definition at line 23 of file CollectionLogPage.java.
{
        return pages.get(button);
    }
Referenced by [static initializer](), and com.runehive.content.collectionlog.CollectionLog.clickButton().
getButton()
int com.runehive.content.collectionlog.CollectionLogPage.getButton ()
Definition at line 35 of file CollectionLogPage.java.
{
        return this.button;
    }
getCategory()
CollectionCategory com.runehive.content.collectionlog.CollectionLogPage.getCategory ()
Definition at line 39 of file CollectionLogPage.java.
{
        return this.category;
    }
Referenced by com.runehive.content.collectionlog.CollectionLogData.getPageList().
Member Data Documentation
BOSSES
com.runehive.content.collectionlog.CollectionLogPage.BOSSES =(-21030, CollectionCategory.BOSSES)
Definition at line 7 of file CollectionLogPage.java.
Referenced by com.runehive.content.collectionlog.CollectionLog.open().
button
final int com.runehive.content.collectionlog.CollectionLogPage.button private
Definition at line 13 of file CollectionLogPage.java.
Referenced by [static initializer](), and CollectionLogPage().
category
final CollectionCategory com.runehive.content.collectionlog.CollectionLogPage.category private
Definition at line 14 of file CollectionLogPage.java.
Referenced by CollectionLogPage().
CLUES
com.runehive.content.collectionlog.CollectionLogPage.CLUES =(-21026, CollectionCategory.CLUES)
Definition at line 9 of file CollectionLogPage.java.
MINIGAMES
com.runehive.content.collectionlog.CollectionLogPage.MINIGAMES =(-21024, CollectionCategory.MINIGAMES)
Definition at line 10 of file CollectionLogPage.java.
OTHER
com.runehive.content.collectionlog.CollectionLogPage.OTHER =(-21022, CollectionCategory.OTHER)
Definition at line 11 of file CollectionLogPage.java.
pages
HashMap<Integer, CollectionLogPage> com.runehive.content.collectionlog.CollectionLogPage.pages static private
Definition at line 21 of file CollectionLogPage.java.
Referenced by [static initializer]().
RAIDS
com.runehive.content.collectionlog.CollectionLogPage.RAIDS =(-21028, CollectionCategory.RAIDS)
Definition at line 8 of file CollectionLogPage.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/collectionlog/CollectionLogPage.java