RuneHive-Game: com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData Enum Reference
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData Enum Reference
Public Member Functions
int[] getMonster ()
WaveData (int... monster)
Static Public Member Functions
static WaveData getNext (int current)
static WaveData getOrdinal (int ordinal)
Public Attributes
WAVE_1 =(2189, 2191)
WAVE_10 =(3125, 2193, 2189, 2189)
WAVE_11 =(3125, 2193, 2191, 2191)
WAVE_12 =(3125, 3123, 2189, 2189)
WAVE_13 =(3125, 3123, 2193, 2189)
WAVE_14 =(3125, 3125)
WAVE_15 =(3127, 3128, 3128, 3128, 3128, 3128)
WAVE_2 =(2193, 2189)
WAVE_3 =(2193, 2191, 2189, 2189)
WAVE_4 =(3123, 2189)
WAVE_5 =(3123, 2191, 2189, 2189)
WAVE_6 =(3123, 2193, 2189, 2189)
WAVE_7 =(3123, 2193, 2191, 2191)
WAVE_8 =(3125, 2189)
WAVE_9 =(3125, 2191, 2189, 2189)
Private Attributes
final int[] monster
Detailed Description
Definition at line 7 of file TzhaarData.java.
Constructor & Destructor Documentation
WaveData()
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WaveData (int... monster)
Definition at line 26 of file TzhaarData.java.
{
            this.monster = monster;
        }
References monster.
Referenced by getNext(), and getOrdinal().
Member Function Documentation
getMonster()
int[] com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.getMonster ()
Definition at line 30 of file TzhaarData.java.
{
            return monster;
        }
References monster.
getNext()
WaveData com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.getNext (int current) static
Definition at line 42 of file TzhaarData.java.
{
            return getOrdinal(current + 1);
        }
References getOrdinal(), and WaveData().
Referenced by com.runehive.content.activity.impl.fightcaves.FightCaves.handleDeath().
getOrdinal()
WaveData com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.getOrdinal (int ordinal) static
Definition at line 34 of file TzhaarData.java.
{
            for (WaveData wave : values()) {
                if (wave.ordinal() == ordinal)
                    return wave;
            }
            return null;
        }
References WaveData().
Referenced by getNext().
Member Data Documentation
monster
final int [] com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.monster private
Definition at line 24 of file TzhaarData.java.
Referenced by getMonster(), and WaveData().
WAVE_1
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_1 =(2189, 2191)
Definition at line 8 of file TzhaarData.java.
WAVE_10
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_10 =(3125, 2193, 2189, 2189)
Definition at line 17 of file TzhaarData.java.
WAVE_11
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_11 =(3125, 2193, 2191, 2191)
Definition at line 18 of file TzhaarData.java.
WAVE_12
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_12 =(3125, 3123, 2189, 2189)
Definition at line 19 of file TzhaarData.java.
WAVE_13
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_13 =(3125, 3123, 2193, 2189)
Definition at line 20 of file TzhaarData.java.
WAVE_14
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_14 =(3125, 3125)
Definition at line 21 of file TzhaarData.java.
WAVE_15
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_15 =(3127, 3128, 3128, 3128, 3128, 3128)
Definition at line 22 of file TzhaarData.java.
WAVE_2
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_2 =(2193, 2189)
Definition at line 9 of file TzhaarData.java.
WAVE_3
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_3 =(2193, 2191, 2189, 2189)
Definition at line 10 of file TzhaarData.java.
WAVE_4
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_4 =(3123, 2189)
Definition at line 11 of file TzhaarData.java.
WAVE_5
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_5 =(3123, 2191, 2189, 2189)
Definition at line 12 of file TzhaarData.java.
WAVE_6
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_6 =(3123, 2193, 2189, 2189)
Definition at line 13 of file TzhaarData.java.
WAVE_7
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_7 =(3123, 2193, 2191, 2191)
Definition at line 14 of file TzhaarData.java.
WAVE_8
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_8 =(3125, 2189)
Definition at line 15 of file TzhaarData.java.
WAVE_9
com.runehive.content.activity.impl.fightcaves.TzhaarData.WaveData.WAVE_9 =(3125, 2191, 2189, 2189)
Definition at line 16 of file TzhaarData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/activity/impl/fightcaves/TzhaarData.java