RuneHive-Game: com.runehive.content.skill.impl.herblore.UnfinishedPotion Enum Reference
com.runehive.content.skill.impl.herblore.UnfinishedPotion Enum Reference
Public Member Functions
int getAnimation ()
Gets the potion animation.
double getExperience ()
Gets the experience rewarded.
Item[] getIngredients ()
Gets the ingredients required for the potion.
int getLevel ()
Gets the level required for making the potion.
Item getProduct ()
Gets the potion product.
String toString ()
UnfinishedPotion (int product, int ingredient, int level)
Static Public Member Functions
static UnfinishedPotion get (Item use, Item with)
Public Attributes
AVANTOE_POTION =(103, 261, 50)
CADANTINE_POTION =(107, 265, 66)
DWARF_WEED_POTION =(109, 267, 72)
GUAM_POTION =(91, 249, 1)
HARRALANDER_POTION =(97, 255, 22)
IRIT_POTION =(101, 259, 45)
KWUARM_POTION =(105, 263, 55)
LANTADYME =(2483, 2481, 69)
MARRENTILL_POTION =(93, 251, 5)
RANARR_POTION =(99, 257, 30)
SNAPDRAGON_POTION =(3004, 3000, 63)
SPIRIT_WEED_POTION =(12181, 12172, 40)
TARROMIN_POTION =(95, 253, 12)
TOADFLAX_POTION =(3002, 2998, 34)
TORSTOL_POTION =(111, 269, 78)
WERGALI_POTION =(14856, 14854, 1)
Private Attributes
final Item[] ingredients
final int level
final int product
Detailed Description
Definition at line 7 of file UnfinishedPotion.java.
Constructor & Destructor Documentation
UnfinishedPotion()
com.runehive.content.skill.impl.herblore.UnfinishedPotion.UnfinishedPotion (int product, int ingredient, int level)
Definition at line 29 of file UnfinishedPotion.java.
{
        this.product = product;
        this.ingredients = new Item[] { new Item(227), new Item(ingredient) };
        this.level = level;
    }
References level, and product.
Referenced by get().
Member Function Documentation
get()
UnfinishedPotion com.runehive.content.skill.impl.herblore.UnfinishedPotion.get (Item use, Item with) static
Definition at line 35 of file UnfinishedPotion.java.
{
        for (final UnfinishedPotion potion : values()) {
            if (potion.ingredients[0].equals(use) && potion.ingredients[1].equals(with) || potion.ingredients[1].equals(use) && potion.ingredients[0].equals(with)) {
                return potion;
            }
        }
        return null;
    }
References UnfinishedPotion().
Referenced by com.runehive.content.skill.impl.herblore.Herblore.useItem().
getAnimation()
int com.runehive.content.skill.impl.herblore.UnfinishedPotion.getAnimation ()
Gets the potion animation.
Returns
The potion animation.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 45 of file UnfinishedPotion.java.
{
        return -1;
    }
getExperience()
double com.runehive.content.skill.impl.herblore.UnfinishedPotion.getExperience ()
Gets the experience rewarded.
Returns
The experience rewarded.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 50 of file UnfinishedPotion.java.
{
        return 0;
    }
getIngredients()
Item[] com.runehive.content.skill.impl.herblore.UnfinishedPotion.getIngredients ()
Gets the ingredients required for the potion.
Returns
The potion ingredients.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 55 of file UnfinishedPotion.java.
{
        return Arrays.copyOf(ingredients, ingredients.length);
    }
References ingredients.
getLevel()
int com.runehive.content.skill.impl.herblore.UnfinishedPotion.getLevel ()
Gets the level required for making the potion.
Returns
The level required.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 60 of file UnfinishedPotion.java.
{
        return level;
    }
References level.
getProduct()
Item com.runehive.content.skill.impl.herblore.UnfinishedPotion.getProduct ()
Gets the potion product.
Returns
The potion product.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 65 of file UnfinishedPotion.java.
{
        return new Item(product);
    }
References product.
Referenced by toString().
toString()
String com.runehive.content.skill.impl.herblore.UnfinishedPotion.toString ()
Definition at line 70 of file UnfinishedPotion.java.
{
        return "UnfinishedPotion[product: " + getProduct() + ", level: " + level + ", ingredients: " + Arrays.toString(ingredients) + "]";
    }
References getProduct(), ingredients, and level.
Member Data Documentation
AVANTOE_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.AVANTOE_POTION =(103, 261, 50)
Definition at line 17 of file UnfinishedPotion.java.
CADANTINE_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.CADANTINE_POTION =(107, 265, 66)
Definition at line 20 of file UnfinishedPotion.java.
DWARF_WEED_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.DWARF_WEED_POTION =(109, 267, 72)
Definition at line 22 of file UnfinishedPotion.java.
GUAM_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.GUAM_POTION =(91, 249, 1)
Definition at line 8 of file UnfinishedPotion.java.
HARRALANDER_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.HARRALANDER_POTION =(97, 255, 22)
Definition at line 11 of file UnfinishedPotion.java.
ingredients
final Item [] com.runehive.content.skill.impl.herblore.UnfinishedPotion.ingredients private
Definition at line 26 of file UnfinishedPotion.java.
Referenced by getIngredients(), and toString().
IRIT_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.IRIT_POTION =(101, 259, 45)
Definition at line 15 of file UnfinishedPotion.java.
KWUARM_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.KWUARM_POTION =(105, 263, 55)
Definition at line 18 of file UnfinishedPotion.java.
LANTADYME
com.runehive.content.skill.impl.herblore.UnfinishedPotion.LANTADYME =(2483, 2481, 69)
Definition at line 21 of file UnfinishedPotion.java.
level
final int com.runehive.content.skill.impl.herblore.UnfinishedPotion.level private
Definition at line 27 of file UnfinishedPotion.java.
Referenced by getLevel(), toString(), and UnfinishedPotion().
MARRENTILL_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.MARRENTILL_POTION =(93, 251, 5)
Definition at line 9 of file UnfinishedPotion.java.
product
final int com.runehive.content.skill.impl.herblore.UnfinishedPotion.product private
Definition at line 25 of file UnfinishedPotion.java.
Referenced by getProduct(), and UnfinishedPotion().
RANARR_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.RANARR_POTION =(99, 257, 30)
Definition at line 12 of file UnfinishedPotion.java.
SNAPDRAGON_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.SNAPDRAGON_POTION =(3004, 3000, 63)
Definition at line 19 of file UnfinishedPotion.java.
SPIRIT_WEED_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.SPIRIT_WEED_POTION =(12181, 12172, 40)
Definition at line 14 of file UnfinishedPotion.java.
TARROMIN_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.TARROMIN_POTION =(95, 253, 12)
Definition at line 10 of file UnfinishedPotion.java.
TOADFLAX_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.TOADFLAX_POTION =(3002, 2998, 34)
Definition at line 13 of file UnfinishedPotion.java.
TORSTOL_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.TORSTOL_POTION =(111, 269, 78)
Definition at line 23 of file UnfinishedPotion.java.
WERGALI_POTION
com.runehive.content.skill.impl.herblore.UnfinishedPotion.WERGALI_POTION =(14856, 14854, 1)
Definition at line 16 of file UnfinishedPotion.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/herblore/UnfinishedPotion.java