RuneHive-Game: com.runehive.content.skill.impl.magic.enchant.SpellEnchantData Enum Reference
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData Enum Reference
Public Member Functions
int getAnimation ()
int getCraftingLevel ()
int getEnchanted ()
int getGFX ()
int getLevel ()
int getMagicLevel ()
int getUnenchanted ()
int getXp ()
SpellEnchantData (int unenchanted, int enchanted, int craftingLevel, int magicLevel, int magicExperience, int animation, int graphic, int enchantmentLevel)
Static Public Member Functions
static SpellEnchantData forId (int itemID)
Public Attributes
DIAMOND_AMULET =(1700, 1731, 70, 57, 67, 720, 115, 4)
DIAMOND_NECKLACE =(1662, 11090, 56, 57, 67, 720, 115, 4)
DIAMOND_RING =(1643, 2570, 43, 57, 67, 720, 115, 4)
DRAGONSTONE_AMULET =(1702, 1712, 80, 68, 78, 721, 116, 5)
DRAGONSTONE_NECKLACE =(1664, 11105, 72, 68, 78, 721, 116, 5)
DRAGONSTONE_RING =(1645, 2572, 55, 68, 78, 721, 116, 5)
EMERALD_AMULET =(1696, 1729, 31, 27, 37, 719, 114, 2)
EMERALD_NECKLACE =(1658, 5521, 29, 27, 37, 719, 114, 2)
EMERALD_RING =(1639, 2552, 27, 27, 37, 719, 114, 2)
ONYX_AMULET =(6581, 6585, 90, 87, 97, 721, 452, 6)
ONYX_NECKLACE =(6577, 11128, 82, 87, 97, 721, 452, 6)
ONYX_RING =(6575, 6583, 67, 87, 97, 721, 452, 6)
RUBY_AMULET =(1698, 1725, 50, 47, 59, 720, 115, 3)
RUBY_NECKLACE =(1660, 11194, 40, 47, 59, 720, 115, 3)
RUBY_RING =(1641, 2568, 34, 47, 59, 720, 115, 3)
SAPPHIRE_AMULET =(1694, 1727, 24, 7, 18, 719, 114, 1)
SAPPHIRE_NECKLACE =(1656, 3853, 22, 7, 18, 719, 114, 1)
SAPPHIRE_RING =(1637, 2550, 20, 7, 18, 719, 114, 1)
ZENYTE_AMULET =(19541, 19553, 98, 98, 110, 721, 452, 7)
ZENYTE_BRACELET =(19492, 19544, 95, 93, 110, 721, 452, 7)
ZENYTE_NECKLACE =(19535, 19547, 92, 93, 110, 721, 452, 7)
ZENYTE_RING =(19538, 19550, 89, 93, 110, 721, 452, 7)
Private Attributes
final int animation
final int craftingLevel
final int enchanted
final int enchantmentLevel
final int graphic
final int magicExperience
final int magicLevel
final int unenchanted
Detailed Description
Definition at line 3 of file SpellEnchantData.java.
Constructor & Destructor Documentation
SpellEnchantData()
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.SpellEnchantData (int unenchanted, int enchanted, int craftingLevel, int magicLevel, int magicExperience, int animation, int graphic, int enchantmentLevel)
Definition at line 42 of file SpellEnchantData.java.
{
        this.unenchanted = unenchanted;
        this.enchanted = enchanted;
        this.craftingLevel = craftingLevel;
        this.magicLevel = magicLevel;
        this.magicExperience = magicExperience;
        this.animation = animation;
        this.graphic = graphic;
        this.enchantmentLevel = enchantmentLevel;
    }
References animation, craftingLevel, enchanted, enchantmentLevel, graphic, magicExperience, magicLevel, and unenchanted.
Referenced by forId().
Member Function Documentation
forId()
SpellEnchantData com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.forId (int itemID) static
Definition at line 85 of file SpellEnchantData.java.
{
        for (SpellEnchantData data : values()) {
            if (data.getUnenchanted() == itemID)
                return data;
        }
        return null;
    }
References SpellEnchantData().
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getAnimation()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getAnimation ()
Definition at line 73 of file SpellEnchantData.java.
{
        return animation;
    }
References animation.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getCraftingLevel()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getCraftingLevel ()
Definition at line 61 of file SpellEnchantData.java.
{
        return craftingLevel;
    }
References craftingLevel.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getEnchanted()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getEnchanted ()
Definition at line 57 of file SpellEnchantData.java.
{
        return enchanted;
    }
References enchanted.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getGFX()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getGFX ()
Definition at line 77 of file SpellEnchantData.java.
{
        return graphic;
    }
References graphic.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getLevel()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getLevel ()
Definition at line 81 of file SpellEnchantData.java.
{
        return enchantmentLevel;
    }
References enchantmentLevel.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getMagicLevel()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getMagicLevel ()
Definition at line 65 of file SpellEnchantData.java.
{
        return magicLevel;
    }
References magicLevel.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getUnenchanted()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getUnenchanted ()
Definition at line 53 of file SpellEnchantData.java.
{
        return unenchanted;
    }
References unenchanted.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
getXp()
int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.getXp ()
Definition at line 69 of file SpellEnchantData.java.
                       {
        return magicExperience;
    }
References magicExperience.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.enchantItem().
Member Data Documentation
animation
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.animation private
Definition at line 38 of file SpellEnchantData.java.
Referenced by getAnimation(), and SpellEnchantData().
craftingLevel
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.craftingLevel private
Definition at line 36 of file SpellEnchantData.java.
Referenced by getCraftingLevel(), and SpellEnchantData().
DIAMOND_AMULET
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.DIAMOND_AMULET =(1700, 1731, 70, 57, 67, 720, 115, 4)
Definition at line 17 of file SpellEnchantData.java.
DIAMOND_NECKLACE
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.DIAMOND_NECKLACE =(1662, 11090, 56, 57, 67, 720, 115, 4)
Definition at line 18 of file SpellEnchantData.java.
DIAMOND_RING
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.DIAMOND_RING =(1643, 2570, 43, 57, 67, 720, 115, 4)
Definition at line 16 of file SpellEnchantData.java.
DRAGONSTONE_AMULET
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.DRAGONSTONE_AMULET =(1702, 1712, 80, 68, 78, 721, 116, 5)
Definition at line 21 of file SpellEnchantData.java.
DRAGONSTONE_NECKLACE
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.DRAGONSTONE_NECKLACE =(1664, 11105, 72, 68, 78, 721, 116, 5)
Definition at line 22 of file SpellEnchantData.java.
DRAGONSTONE_RING
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.DRAGONSTONE_RING =(1645, 2572, 55, 68, 78, 721, 116, 5)
Definition at line 20 of file SpellEnchantData.java.
EMERALD_AMULET
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.EMERALD_AMULET =(1696, 1729, 31, 27, 37, 719, 114, 2)
Definition at line 9 of file SpellEnchantData.java.
EMERALD_NECKLACE
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.EMERALD_NECKLACE =(1658, 5521, 29, 27, 37, 719, 114, 2)
Definition at line 10 of file SpellEnchantData.java.
EMERALD_RING
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.EMERALD_RING =(1639, 2552, 27, 27, 37, 719, 114, 2)
Definition at line 8 of file SpellEnchantData.java.
enchanted
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.enchanted private
Definition at line 34 of file SpellEnchantData.java.
Referenced by getEnchanted(), and SpellEnchantData().
enchantmentLevel
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.enchantmentLevel private
Definition at line 40 of file SpellEnchantData.java.
Referenced by getLevel(), and SpellEnchantData().
graphic
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.graphic private
Definition at line 39 of file SpellEnchantData.java.
Referenced by getGFX(), and SpellEnchantData().
magicExperience
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.magicExperience private
Definition at line 37 of file SpellEnchantData.java.
Referenced by getXp(), and SpellEnchantData().
magicLevel
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.magicLevel private
Definition at line 35 of file SpellEnchantData.java.
Referenced by getMagicLevel(), and SpellEnchantData().
ONYX_AMULET
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.ONYX_AMULET =(6581, 6585, 90, 87, 97, 721, 452, 6)
Definition at line 25 of file SpellEnchantData.java.
ONYX_NECKLACE
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.ONYX_NECKLACE =(6577, 11128, 82, 87, 97, 721, 452, 6)
Definition at line 26 of file SpellEnchantData.java.
ONYX_RING
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.ONYX_RING =(6575, 6583, 67, 87, 97, 721, 452, 6)
Definition at line 24 of file SpellEnchantData.java.
RUBY_AMULET
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.RUBY_AMULET =(1698, 1725, 50, 47, 59, 720, 115, 3)
Definition at line 13 of file SpellEnchantData.java.
RUBY_NECKLACE
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.RUBY_NECKLACE =(1660, 11194, 40, 47, 59, 720, 115, 3)
Definition at line 14 of file SpellEnchantData.java.
RUBY_RING
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.RUBY_RING =(1641, 2568, 34, 47, 59, 720, 115, 3)
Definition at line 12 of file SpellEnchantData.java.
SAPPHIRE_AMULET
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.SAPPHIRE_AMULET =(1694, 1727, 24, 7, 18, 719, 114, 1)
Definition at line 5 of file SpellEnchantData.java.
SAPPHIRE_NECKLACE
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.SAPPHIRE_NECKLACE =(1656, 3853, 22, 7, 18, 719, 114, 1)
Definition at line 6 of file SpellEnchantData.java.
SAPPHIRE_RING
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.SAPPHIRE_RING =(1637, 2550, 20, 7, 18, 719, 114, 1)
Definition at line 4 of file SpellEnchantData.java.
unenchanted
final int com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.unenchanted private
Definition at line 33 of file SpellEnchantData.java.
Referenced by getUnenchanted(), and SpellEnchantData().
ZENYTE_AMULET
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.ZENYTE_AMULET =(19541, 19553, 98, 98, 110, 721, 452, 7)
Definition at line 29 of file SpellEnchantData.java.
ZENYTE_BRACELET
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.ZENYTE_BRACELET =(19492, 19544, 95, 93, 110, 721, 452, 7)
Definition at line 30 of file SpellEnchantData.java.
ZENYTE_NECKLACE
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.ZENYTE_NECKLACE =(19535, 19547, 92, 93, 110, 721, 452, 7)
Definition at line 31 of file SpellEnchantData.java.
ZENYTE_RING
com.runehive.content.skill.impl.magic.enchant.SpellEnchantData.ZENYTE_RING =(19538, 19550, 89, 93, 110, 721, 452, 7)
Definition at line 28 of file SpellEnchantData.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/magic/enchant/SpellEnchantData.java