RuneHive-Game: com.runehive.game.world.object.ObjectType Enum Reference
com.runehive.game.world.object.ObjectType Enum Reference
The enumerated type whose elements represent all of the object types.
Public Member Functions
final ObjectGroup getGroup ()
Gets the group of this type.
final int getId ()
Gets the identification of this type.
ObjectType (int id, ObjectGroup group)
Creates a new ObjectType.
Static Public Member Functions
[static initializer]
static Optional< ObjectType > valueOf (final int id)
Returns a ObjectType wrapped in an Optional for the specified id.
Public Attributes
DIAGONAL_BOTTOM_EDGE_CONNECTING_ROOF =(19, ObjectGroup.ROOFING)
Represents diagonal bottom edge connecting roofs.
DIAGONAL_CORNER_WALL =(1, ObjectGroup.WALL)
Represents diagonal walls corner, fences etc connectors.
DIAGONAL_INSIDE_WALL_DECORATION =(7, ObjectGroup.WALL_DECORATION)
Represents diagonal inside wall decorations.
DIAGONAL_INTERIOR_WALL_DECORATION =(8, ObjectGroup.WALL_DECORATION)
Represents diagonal in wall decorations.
DIAGONAL_OUTSIDE_WALL_DECORATION =(6, ObjectGroup.WALL_DECORATION)
Represents diagonal outside wall decorations.
DIAGONAL_SLOPED_CONNECTING_ROOF =(14, ObjectGroup.ROOFING)
Represents diagonal slope connecting roofs.
DIAGONAL_SLOPED_ROOF =(13, ObjectGroup.ROOFING)
Represents diagonal sloped roofs.
DIAGONAL_WALL =(9, ObjectGroup.WALL)
Represents diagonal walls, fences etc.
ENTIRE_WALL =(2, ObjectGroup.WALL)
Represents entire walls, fences etc corners.
GENERAL_PROP =(10, ObjectGroup.INTERACTABLE_OBJECT)
Represents all kinds of objects, trees, statues, signs, fountains etc.
GROUND_PROP =(22, ObjectGroup.GROUND_DECORATION)
Represents ground decoration + map signs (quests, water fountains, shops, etc)
STRAIGHT_BOTTOM_EDGE_CONNECTING_CORNER_ROOF =(21, ObjectGroup.ROOFING)
Represents straight bottom edge connecting corner roofs.
STRAIGHT_BOTTOM_EDGE_CONNECTING_ROOF =(20, ObjectGroup.ROOFING)
Represents straight bottom edge connecting roofs.
STRAIGHT_BOTTOM_EDGE_ROOF =(18, ObjectGroup.ROOFING)
Represents straight bottom edge roofs.
STRAIGHT_FLAT_TOP_ROOF =(17, ObjectGroup.ROOFING)
Represents straight flat top roofs.
STRAIGHT_INSIDE_WALL_DECORATION =(4, ObjectGroup.WALL_DECORATION)
Represents straight inside wall decorations.
STRAIGHT_OUTSIDE_WALL_DECORATION =(5, ObjectGroup.WALL_DECORATION)
Represents straight outside wall decorations.
STRAIGHT_SLOPED_CORNER_CONNECTING_ROOF =(15, ObjectGroup.ROOFING)
Represents straight sloped corner connecting roofs.
STRAIGHT_SLOPED_CORNER_ROOF =(16, ObjectGroup.ROOFING)
Represents straight sloped corner roofs.
STRAIGHT_SLOPED_ROOF =(12, ObjectGroup.ROOFING)
Represents straight sloped roofs.
STRAIGHT_WALL =(0, ObjectGroup.WALL)
Represents straight walls, fences etc.
WALKABLE_PROP =(11, ObjectGroup.INTERACTABLE_OBJECT)
Represents ground objects like daisies etc.
WALL_CORNER =(3, ObjectGroup.WALL)
Represents straight wall corners, fences etc connectors.
Private Attributes
final ObjectGroup group
The ObjectGroup this type is associated to.
final int id
The identification of this type.
Static Private Attributes
static final Int2ObjectMap< ObjectType > idToType = new Int2ObjectOpenHashMap<>(values.length)
A mutable Map of int keys to ObjectType values.
static final ObjectType[] values = values()
Detailed Description
The enumerated type whose elements represent all of the object types.
Author
Ryley Kimmel ryley.nosp@m..kim.nosp@m.mel@l.nosp@m.ive..nosp@m.com
Maxi http://www.rune-server.org/members/maxi/
lare96 http://github.com/lare96
Artem batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Definition at line 17 of file ObjectType.java.
Constructor & Destructor Documentation
ObjectType()
com.runehive.game.world.object.ObjectType.ObjectType (int id, ObjectGroup group)
Creates a new ObjectType.
Parameters
id the identification of this type
group the group of this type.
Definition at line 103 of file ObjectType.java.
{
        this.id = id;
        this.group = group;
    }
References group, and id.
Referenced by [static initializer]().
Member Function Documentation
[static initializer]()
com.runehive.game.world.object.ObjectType.[static initializer] static
References idToType, ObjectType(), and values.
getGroup()
final ObjectGroup com.runehive.game.world.object.ObjectType.getGroup ()
Gets the group of this type.
Returns
the group of this type.
Definition at line 122 of file ObjectType.java.
{
        return group;
    }
References group.
getId()
final int com.runehive.game.world.object.ObjectType.getId ()
Gets the identification of this type.
Returns
the identification of this type.
Definition at line 113 of file ObjectType.java.
{
        return id;
    }
References id.
valueOf()
Optional< ObjectType > com.runehive.game.world.object.ObjectType.valueOf (final int id) static
Returns a ObjectType wrapped in an Optional for the specified id.
Parameters
id The game object type id.
Returns
The optional game object type.
Definition at line 145 of file ObjectType.java.
{
        return Optional.ofNullable(idToType.get(id));
    }
References idToType.
Referenced by com.runehive.content.skill.impl.hunter.birdhouse.action.FillBirdhouse.execute(), com.runehive.game.world.entity.mob.player.Player.loadRegion(), com.runehive.util.parser.impl.GlobalObjectParser.parse(), com.runehive.fs.cache.decoder.RegionDecoder.parseGameObject(), and com.runehive.content.skill.impl.hunter.birdhouse.Birdhouses.receiveLoot().
Member Data Documentation
DIAGONAL_BOTTOM_EDGE_CONNECTING_ROOF
com.runehive.game.world.object.ObjectType.DIAGONAL_BOTTOM_EDGE_CONNECTING_ROOF =(19, ObjectGroup.ROOFING)
Represents diagonal bottom edge connecting roofs.
Definition at line 77 of file ObjectType.java.
DIAGONAL_CORNER_WALL
com.runehive.game.world.object.ObjectType.DIAGONAL_CORNER_WALL =(1, ObjectGroup.WALL)
Represents diagonal walls corner, fences etc connectors.
Definition at line 23 of file ObjectType.java.
DIAGONAL_INSIDE_WALL_DECORATION
com.runehive.game.world.object.ObjectType.DIAGONAL_INSIDE_WALL_DECORATION =(7, ObjectGroup.WALL_DECORATION)
Represents diagonal inside wall decorations.
Definition at line 41 of file ObjectType.java.
DIAGONAL_INTERIOR_WALL_DECORATION
com.runehive.game.world.object.ObjectType.DIAGONAL_INTERIOR_WALL_DECORATION =(8, ObjectGroup.WALL_DECORATION)
Represents diagonal in wall decorations.
Definition at line 44 of file ObjectType.java.
DIAGONAL_OUTSIDE_WALL_DECORATION
com.runehive.game.world.object.ObjectType.DIAGONAL_OUTSIDE_WALL_DECORATION =(6, ObjectGroup.WALL_DECORATION)
Represents diagonal outside wall decorations.
Definition at line 38 of file ObjectType.java.
DIAGONAL_SLOPED_CONNECTING_ROOF
com.runehive.game.world.object.ObjectType.DIAGONAL_SLOPED_CONNECTING_ROOF =(14, ObjectGroup.ROOFING)
Represents diagonal slope connecting roofs.
Definition at line 62 of file ObjectType.java.
DIAGONAL_SLOPED_ROOF
com.runehive.game.world.object.ObjectType.DIAGONAL_SLOPED_ROOF =(13, ObjectGroup.ROOFING)
Represents diagonal sloped roofs.
Definition at line 59 of file ObjectType.java.
DIAGONAL_WALL
com.runehive.game.world.object.ObjectType.DIAGONAL_WALL =(9, ObjectGroup.WALL)
Represents diagonal walls, fences etc.
Definition at line 47 of file ObjectType.java.
ENTIRE_WALL
com.runehive.game.world.object.ObjectType.ENTIRE_WALL =(2, ObjectGroup.WALL)
Represents entire walls, fences etc corners.
Definition at line 26 of file ObjectType.java.
GENERAL_PROP
com.runehive.game.world.object.ObjectType.GENERAL_PROP =(10, ObjectGroup.INTERACTABLE_OBJECT)
Represents all kinds of objects, trees, statues, signs, fountains etc.
Definition at line 50 of file ObjectType.java.
Referenced by com.runehive.game.world.object.CustomGameObject.CustomGameObject(), com.runehive.game.world.object.CustomGameObject.CustomGameObject(), and com.runehive.content.skill.impl.construction.House.toolkit().
GROUND_PROP
com.runehive.game.world.object.ObjectType.GROUND_PROP =(22, ObjectGroup.GROUND_DECORATION)
Represents ground decoration + map signs (quests, water fountains, shops, etc)
Definition at line 89 of file ObjectType.java.
group
final ObjectGroup com.runehive.game.world.object.ObjectType.group private
The ObjectGroup this type is associated to.
Definition at line 95 of file ObjectType.java.
Referenced by getGroup(), and ObjectType().
id
final int com.runehive.game.world.object.ObjectType.id private
The identification of this type.
Definition at line 92 of file ObjectType.java.
Referenced by getId(), and ObjectType().
idToType
final Int2ObjectMap<ObjectType> com.runehive.game.world.object.ObjectType.idToType = new Int2ObjectOpenHashMap<>(values.length) static private
A mutable Map of int keys to ObjectType values.
Definition at line 129 of file ObjectType.java.
Referenced by [static initializer](), and valueOf().
STRAIGHT_BOTTOM_EDGE_CONNECTING_CORNER_ROOF
com.runehive.game.world.object.ObjectType.STRAIGHT_BOTTOM_EDGE_CONNECTING_CORNER_ROOF =(21, ObjectGroup.ROOFING)
Represents straight bottom edge connecting corner roofs.
Definition at line 83 of file ObjectType.java.
STRAIGHT_BOTTOM_EDGE_CONNECTING_ROOF
com.runehive.game.world.object.ObjectType.STRAIGHT_BOTTOM_EDGE_CONNECTING_ROOF =(20, ObjectGroup.ROOFING)
Represents straight bottom edge connecting roofs.
Definition at line 80 of file ObjectType.java.
STRAIGHT_BOTTOM_EDGE_ROOF
com.runehive.game.world.object.ObjectType.STRAIGHT_BOTTOM_EDGE_ROOF =(18, ObjectGroup.ROOFING)
Represents straight bottom edge roofs.
Definition at line 74 of file ObjectType.java.
STRAIGHT_FLAT_TOP_ROOF
com.runehive.game.world.object.ObjectType.STRAIGHT_FLAT_TOP_ROOF =(17, ObjectGroup.ROOFING)
Represents straight flat top roofs.
Definition at line 71 of file ObjectType.java.
STRAIGHT_INSIDE_WALL_DECORATION
com.runehive.game.world.object.ObjectType.STRAIGHT_INSIDE_WALL_DECORATION =(4, ObjectGroup.WALL_DECORATION)
Represents straight inside wall decorations.
Definition at line 32 of file ObjectType.java.
STRAIGHT_OUTSIDE_WALL_DECORATION
com.runehive.game.world.object.ObjectType.STRAIGHT_OUTSIDE_WALL_DECORATION =(5, ObjectGroup.WALL_DECORATION)
Represents straight outside wall decorations.
Definition at line 35 of file ObjectType.java.
STRAIGHT_SLOPED_CORNER_CONNECTING_ROOF
com.runehive.game.world.object.ObjectType.STRAIGHT_SLOPED_CORNER_CONNECTING_ROOF =(15, ObjectGroup.ROOFING)
Represents straight sloped corner connecting roofs.
Definition at line 65 of file ObjectType.java.
STRAIGHT_SLOPED_CORNER_ROOF
com.runehive.game.world.object.ObjectType.STRAIGHT_SLOPED_CORNER_ROOF =(16, ObjectGroup.ROOFING)
Represents straight sloped corner roofs.
Definition at line 68 of file ObjectType.java.
STRAIGHT_SLOPED_ROOF
com.runehive.game.world.object.ObjectType.STRAIGHT_SLOPED_ROOF =(12, ObjectGroup.ROOFING)
Represents straight sloped roofs.
Definition at line 56 of file ObjectType.java.
STRAIGHT_WALL
com.runehive.game.world.object.ObjectType.STRAIGHT_WALL =(0, ObjectGroup.WALL)
Represents straight walls, fences etc.
Definition at line 20 of file ObjectType.java.
values
final ObjectType [] com.runehive.game.world.object.ObjectType.values = values() static private
Definition at line 126 of file ObjectType.java.
Referenced by [static initializer]().
WALKABLE_PROP
com.runehive.game.world.object.ObjectType.WALKABLE_PROP =(11, ObjectGroup.INTERACTABLE_OBJECT)
Represents ground objects like daisies etc.
Definition at line 53 of file ObjectType.java.
WALL_CORNER
com.runehive.game.world.object.ObjectType.WALL_CORNER =(3, ObjectGroup.WALL)
Represents straight wall corners, fences etc connectors.
Definition at line 29 of file ObjectType.java.
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/object/ObjectType.java