RuneHive-Game: com.runehive.game.world.entity.mob.prayer.Prayer Enum Reference
com.runehive.game.world.entity.mob.prayer.Prayer Enum Reference
Handles the prayer book.
Classes
enum Type
Public Member Functions
boolean canToggle (Player player)
Collection< Prayer > forType (Type type)
int getButton ()
int getConfig ()
int getDrainRate ()
int getHeadIcon ()
int getLevel ()
Optional< CombatListener< Mob > > getListener ()
String getName ()
int getQConfig ()
Prayer.Type[] getTypes ()
boolean is (Type type)
Checks if a prayer is of a certain type.
Prayer (String name, int level, int drainRate, int config, int qConfig, int button, CombatListener< Mob > listener, Type... types)
Constructs a new default prayer book.
Prayer (String name, int level, int drainRate, int config, int qConfig, int button, Type... types)
Constructs a new default prayer book.
void reset (Player player)
void reset (Player player, String message)
Resets the configs for this prayer.
Set< Prayer > toDeactivate ()
Gets the prayers to disable after activating this prayer.
Static Public Member Functions
static Optional< Prayer > forButton (int button)
Streams for the prayer button.
static double getBonus (Player player)
Public Attributes
AUGURY =("Augury", 77, 24, 712, 658, 28007, new AuguryListener(), Type.OFFENSIVE, Type.DEFENSIVE, Type.AGGRESSIVE)
BURST_OF_STRENGTH =("Burst of Strength", 4, 3, 84, 631, 5610, new BurstOfStrengthListener(), Type.AGGRESSIVE)
CHIVALRY =("Chivalry", 60, 24, 706, 655, 19825, new ChivalryListener(), Type.OFFENSIVE, Type.AGGRESSIVE, Type.DEFENSIVE)
CLARITY_OF_THOUGHT =("Clarity of Thought", 7, 3, 85, 632, 5611, new ClarityOfThoughtListener(), Type.OFFENSIVE)
EAGLE_EYE =("Eagle Eye", 44, 12, 704, 649, 19821, new EagleEyeListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
HAWK_EYE =("Hawk Eye", 26, 6, 702, 641, 19816, new HawkEyeListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
IMPROVED_REFLEXES =("Improved Reflexes", 16, 6, 88, 637, 5614, new ImprovedReflexesListener(), Type.OFFENSIVE)
INCREDIBLE_REFLEXES =("Incredible Reflexes", 34, 12, 94, 645, 5620, new IncredibleReflexesListener(), Type.OFFENSIVE)
final int level
The required prayer level.
MYSTIC_LORE =("Mystic Lore", 27, 6, 703, 642, 19818, new MysticLoreListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
MYSTIC_MIGHT =("Mystic Might", 45, 12, 705, 650, 19823, new MysticMightListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
MYSTIC_WILL =("Mystic Will", 9, 3, 701, 634, 19814, new MysticWillListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
final String name
The name of the prayer.
PIETY =("Piety", 70, 24, 707, 656, 19827, new PietyListener(), Type.OFFENSIVE, Type.AGGRESSIVE, Type.DEFENSIVE)
PRESERVE =("Preserve", 55, 3, 708, 654, 28001, Type.NORMAL)
PROTECT_FROM_MAGIC =("Protect from Magic", 37, 12, 95, 646, 5621, Type.OVERHEAD)
PROTECT_FROM_MELEE =("Protect from Melee", 43, 12, 97, 648, 5623, Type.OVERHEAD)
PROTECT_FROM_RANGE =("Protect from Range", 40, 12, 96, 647, 5622, Type.OVERHEAD)
PROTECT_ITEM =("Protect Item", 25, 2, 91, 640, 5617, Type.NORMAL)
RAPID_HEAL =("Rapid Heal", 22, 2, 90, 639, 5616, Type.NORMAL)
RAPID_RESTORE =("Rapid Restore", 19, 1, 89, 638, 5615, Type.NORMAL)
REDEMPTION =("Redemption", 49, 6, 99, 652, 684, Type.OVERHEAD)
RETRIBUTION =("Retribution", 46, 3, 98, 651, 683, Type.OVERHEAD)
RIGOUR =("Rigour", 74, 24, 710, 657, 28004, new RigourListener(), Type.OFFENSIVE, Type.DEFENSIVE, Type.AGGRESSIVE)
ROCK_SKIN =("Rock Skin", 10, 6, 86, 635, 5612, new RockSkinListener(), Type.DEFENSIVE)
SHARP_EYE =("Sharp Eye", 8, 3, 700, 633, 19812, new SharpListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
SMITE =("Smite", 52, 18, 100, 653, 685, Type.OVERHEAD)
STEEL_SKIN =("Steel Skin", 28, 12, 92, 643, 5618, new SteelSkinListener(), Type.DEFENSIVE)
SUPERHUMAN_STRENGTH =("Superhuman Strength", 13, 6, 87, 636, 5613, new SuperhumanStrengthListener(), Type.AGGRESSIVE)
THICK_SKIN =("Thick Skin", 1, 3, 83, 630, 5609, new ThickSkinListener(), Type.DEFENSIVE)
ULTIMATE_STRENGTH =("Ultimate Strength", 31, 12, 93, 644, 5619, new UltimateStrengthListener(), Type.AGGRESSIVE)
Static Public Attributes
static final Set< Prayer > EMPTY = ImmutableSet.of()
static final Collection< Prayer > OVERHEAD
Private Attributes
final int button
The button id.
final int config
The prayer config id.
final int drainRate
The prayer drain rate.
final CombatListener< Mob > listener
The listener.
final int qConfig
The quick-prayer config id.
final Type[] types
The prayer type.
Static Private Attributes
static final Collection< Prayer > AGGRESSIVE
static final Collection< Prayer > DEFENSIVE
static final Collection< Prayer > OFFENSIVE
Detailed Description
Handles the prayer book.
Author
Michael
Daniel
Definition at line 40 of file Prayer.java.
Constructor & Destructor Documentation
Prayer() [1/2]
com.runehive.game.world.entity.mob.prayer.Prayer.Prayer (String name, int level, int drainRate, int config, int qConfig, int button, Type... types)
Constructs a new default prayer book.
Parameters
name The prayer name.
level The required prayer level.
drainRate The prayer's drain rate.
config The prayer's config id.
button The button id.
Definition at line 104 of file Prayer.java.
{
        this.name = name;
        this.level = level;
        this.drainRate = drainRate;
        this.config = config;
        this.qConfig = qConfig;
        this.button = button;
        this.listener = null;
        this.types = types;
    }
References button, config, drainRate, level, name, qConfig, and types.
Referenced by getTypes().
Prayer() [2/2]
com.runehive.game.world.entity.mob.prayer.Prayer.Prayer (String name, int level, int drainRate, int config, int qConfig, int button, CombatListener< Mob > listener, Type... types)
Constructs a new default prayer book.
Parameters
name The prayer name.
level The required prayer level.
drainRate The prayer's drain rate.
config The prayer's config id.
button The button id.
Definition at line 124 of file Prayer.java.
{
        this.name = name;
        this.level = level;
        this.drainRate = drainRate;
        this.config = config;
        this.qConfig = qConfig;
        this.button = button;
        this.listener = listener;
        this.types = types;
    }
References button, config, drainRate, level, listener, name, qConfig, and types.
Member Function Documentation
canToggle()
boolean com.runehive.game.world.entity.mob.prayer.Prayer.canToggle (Player player)
Definition at line 235 of file Prayer.java.
{
        if (player.skills.getLevel(Skill.PRAYER) == 0) {
            return false;
        }
        if (level > player.skills.getMaxLevel(Skill.PRAYER)) {
            return false;
        }
        if (this == CHIVALRY && player.skills.getMaxLevel(Skill.DEFENCE) < 60) {
            return false;
        }
        if ((this == PIETY || this == RIGOUR || this == AUGURY) && player.skills.getMaxLevel(Skill.DEFENCE) < 70) {
            return false;
        }
        if (this == PROTECT_ITEM && player.right.equals(PlayerRight.ULTIMATE_IRONMAN)) {
            return false;
        }
      /*  if ((this == PROTECT_FROM_MAGIC || this == PROTECT_FROM_MELEE || this == PROTECT_FROM_RANGE) && Area.inEventArena(player)) {
            return false;
        }*/
        return PlayerRight.isAdministrator(player) || (this != RIGOUR && this != AUGURY && this != PRESERVE) || player.unlockedPrayers.contains(this);
    }
References AUGURY, CHIVALRY, com.runehive.game.world.entity.skill.Skill.DEFENCE, com.runehive.game.world.entity.mob.player.PlayerRight.isAdministrator(), level, PIETY, com.runehive.game.world.entity.skill.Skill.PRAYER, PRESERVE, PROTECT_ITEM, RIGOUR, and com.runehive.game.world.entity.mob.player.PlayerRight.ULTIMATE_IRONMAN.
forButton()
Optional< Prayer > com.runehive.game.world.entity.mob.prayer.Prayer.forButton (int button) static
Streams for the prayer button.
Definition at line 136 of file Prayer.java.
{
        return Arrays.stream(values()).filter(p -> p.getButton() == button).findAny();
    }
References button.
forType()
Collection< Prayer > com.runehive.game.world.entity.mob.prayer.Prayer.forType (Type type)
Definition at line 299 of file Prayer.java.
{
        switch (type) {
            case OFFENSIVE:
                return OFFENSIVE;
            case DEFENSIVE:
                return DEFENSIVE;
            case AGGRESSIVE:
                return AGGRESSIVE;
            case OVERHEAD:
                return OVERHEAD;
            default:
                return EMPTY;
        }
    }
References AGGRESSIVE, DEFENSIVE, EMPTY, OFFENSIVE, and OVERHEAD.
Referenced by toDeactivate().
getBonus()
double com.runehive.game.world.entity.mob.prayer.Prayer.getBonus (Player player) static
Definition at line 217 of file Prayer.java.
{
        double bonus = 0;
        if(player.equipment.getId(0) == 25438)
            bonus += 0.4;
        if(player.equipment.getId(4) == 25434)
            bonus += 0.8;
        if(player.equipment.getId(7) == 25436)
            bonus += 0.6;
        if(player.equipment.getId(10) == 25440)
            bonus += 0.2;
        if(player.equipment.containsAll(25438, 25434, 25436, 25440))
            bonus = 2.5;
        return bonus;
    }
Referenced by com.runehive.game.world.entity.skill.SkillManager.addExperience().
getButton()
int com.runehive.game.world.entity.mob.prayer.Prayer.getButton ()
Definition at line 160 of file Prayer.java.
{
        return button;
    }
References button.
getConfig()
int com.runehive.game.world.entity.mob.prayer.Prayer.getConfig ()
Definition at line 152 of file Prayer.java.
{
        return config;
    }
References config.
getDrainRate()
int com.runehive.game.world.entity.mob.prayer.Prayer.getDrainRate ()
Definition at line 148 of file Prayer.java.
{
        return drainRate;
    }
References drainRate.
getHeadIcon()
int com.runehive.game.world.entity.mob.prayer.Prayer.getHeadIcon ()
Definition at line 280 of file Prayer.java.
{
        switch (this) {
            case PROTECT_FROM_MAGIC:
                return 2;
            case PROTECT_FROM_RANGE:
                return 1;
            case PROTECT_FROM_MELEE:
                return 0;
            case RETRIBUTION:
                return 3;
            case REDEMPTION:
                return 5;
            case SMITE:
                return 4;
            default:
                return -1;
        }
    }
References PROTECT_FROM_MAGIC, PROTECT_FROM_MELEE, PROTECT_FROM_RANGE, REDEMPTION, RETRIBUTION, and SMITE.
getLevel()
int com.runehive.game.world.entity.mob.prayer.Prayer.getLevel ()
Definition at line 144 of file Prayer.java.
{
        return level;
    }
References level.
getListener()
Optional< CombatListener< Mob > > com.runehive.game.world.entity.mob.prayer.Prayer.getListener ()
Definition at line 276 of file Prayer.java.
{
        return Optional.ofNullable(listener);
    }
References listener.
getName()
String com.runehive.game.world.entity.mob.prayer.Prayer.getName ()
Definition at line 140 of file Prayer.java.
{
        return name;
    }
References name.
getQConfig()
int com.runehive.game.world.entity.mob.prayer.Prayer.getQConfig ()
Definition at line 156 of file Prayer.java.
{
        return qConfig;
    }
References qConfig.
getTypes()
Prayer.Type[] com.runehive.game.world.entity.mob.prayer.Prayer.getTypes ()
Definition at line 164 of file Prayer.java.
{
        return types;
    }
References Prayer(), and types.
Referenced by is(), and toDeactivate().
is()
boolean com.runehive.game.world.entity.mob.prayer.Prayer.is (Type type)
Checks if a prayer is of a certain type.
Parameters
type The type to check
Returns
True if the prayer is of thie given type.
Definition at line 198 of file Prayer.java.
{
        return Arrays.stream(getTypes()).anyMatch(other -> type == other);
    }
References getTypes().
reset() [1/2]
void com.runehive.game.world.entity.mob.prayer.Prayer.reset (Player player)
Definition at line 257 of file Prayer.java.
{
        reset(player, null);
    }
References reset().
Referenced by reset().
reset() [2/2]
void com.runehive.game.world.entity.mob.prayer.Prayer.reset (Player player, String message)
Resets the configs for this prayer.
The quick prayer icon will be disabled and all active prayers will be reset.
Parameters
player The player.
message The message to send, or null if none.
Definition at line 268 of file Prayer.java.
{
        player.prayer.reset();
        player.send(new SendConfig(config, 0));
        if (message != null) {
            player.send(new SendMessage(message));
        }
    }
References config.
toDeactivate()
Set< Prayer > com.runehive.game.world.entity.mob.prayer.Prayer.toDeactivate ()
Gets the prayers to disable after activating this prayer.
Returns
A set of prayers to disable.
Definition at line 207 of file Prayer.java.
{
        Type[] types = getTypes();
        if (types.length == 0) return EMPTY;
        Set<Prayer> deactivate = new HashSet<>();
        for (Type type : types) {
            deactivate.addAll(forType(type));
        }
        return deactivate;
    }
References EMPTY, forType(), getTypes(), and types.
Member Data Documentation
AGGRESSIVE
final Collection<Prayer> com.runehive.game.world.entity.mob.prayer.Prayer.AGGRESSIVE static private
Initial value:
= ImmutableList.of(
            BURST_OF_STRENGTH, SUPERHUMAN_STRENGTH, ULTIMATE_STRENGTH,
            SHARP_EYE, HAWK_EYE, EAGLE_EYE,
            MYSTIC_WILL, MYSTIC_LORE, MYSTIC_MIGHT,
            CHIVALRY, PIETY, RIGOUR
    )
Definition at line 180 of file Prayer.java.
Referenced by forType().
AUGURY
com.runehive.game.world.entity.mob.prayer.Prayer.AUGURY =("Augury", 77, 24, 712, 658, 28007, new AuguryListener(), Type.OFFENSIVE, Type.DEFENSIVE, Type.AGGRESSIVE)
Definition at line 69 of file Prayer.java.
Referenced by canToggle(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonus(), com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getPrayerBonus(), and com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonusDefender().
BURST_OF_STRENGTH
com.runehive.game.world.entity.mob.prayer.Prayer.BURST_OF_STRENGTH =("Burst of Strength", 4, 3, 84, 631, 5610, new BurstOfStrengthListener(), Type.AGGRESSIVE)
Definition at line 42 of file Prayer.java.
button
final int com.runehive.game.world.entity.mob.prayer.Prayer.button private
The button id.
Definition at line 87 of file Prayer.java.
Referenced by forButton(), getButton(), Prayer(), and Prayer().
CHIVALRY
com.runehive.game.world.entity.mob.prayer.Prayer.CHIVALRY =("Chivalry", 60, 24, 706, 655, 19825, new ChivalryListener(), Type.OFFENSIVE, Type.AGGRESSIVE, Type.DEFENSIVE)
Definition at line 66 of file Prayer.java.
Referenced by canToggle(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getPrayerBonus(), and com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerDefenseBonus().
CLARITY_OF_THOUGHT
com.runehive.game.world.entity.mob.prayer.Prayer.CLARITY_OF_THOUGHT =("Clarity of Thought", 7, 3, 85, 632, 5611, new ClarityOfThoughtListener(), Type.OFFENSIVE)
Definition at line 43 of file Prayer.java.
config
final int com.runehive.game.world.entity.mob.prayer.Prayer.config private
The prayer config id.
Definition at line 81 of file Prayer.java.
Referenced by getConfig(), Prayer(), Prayer(), and reset().
DEFENSIVE
final Collection<Prayer> com.runehive.game.world.entity.mob.prayer.Prayer.DEFENSIVE static private
Initial value:
= ImmutableList.of(
            THICK_SKIN, ROCK_SKIN, STEEL_SKIN,
            CHIVALRY, PIETY, RIGOUR, AUGURY
    )
Definition at line 185 of file Prayer.java.
Referenced by forType().
drainRate
final int com.runehive.game.world.entity.mob.prayer.Prayer.drainRate private
The prayer drain rate.
Definition at line 78 of file Prayer.java.
Referenced by getDrainRate(), Prayer(), and Prayer().
EAGLE_EYE
com.runehive.game.world.entity.mob.prayer.Prayer.EAGLE_EYE =("Eagle Eye", 44, 12, 704, 649, 19821, new EagleEyeListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
Definition at line 60 of file Prayer.java.
Referenced by com.runehive.content.bot.botclass.impl.PureRangeMelee.endFight(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus(), com.runehive.content.bot.botclass.impl.PureRangeMelee.initCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.meleePrayers(), and com.runehive.content.bot.botclass.impl.PureRangeMelee.rangedPrayers().
EMPTY
final Set<Prayer> com.runehive.game.world.entity.mob.prayer.Prayer.EMPTY = ImmutableSet.of() static
Definition at line 314 of file Prayer.java.
Referenced by forType(), and toDeactivate().
HAWK_EYE
com.runehive.game.world.entity.mob.prayer.Prayer.HAWK_EYE =("Hawk Eye", 26, 6, 702, 641, 19816, new HawkEyeListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
Definition at line 52 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus(), and com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus().
IMPROVED_REFLEXES
com.runehive.game.world.entity.mob.prayer.Prayer.IMPROVED_REFLEXES =("Improved Reflexes", 16, 6, 88, 637, 5614, new ImprovedReflexesListener(), Type.OFFENSIVE)
Definition at line 48 of file Prayer.java.
INCREDIBLE_REFLEXES
com.runehive.game.world.entity.mob.prayer.Prayer.INCREDIBLE_REFLEXES =("Incredible Reflexes", 34, 12, 94, 645, 5620, new IncredibleReflexesListener(), Type.OFFENSIVE)
Definition at line 56 of file Prayer.java.
Referenced by com.runehive.content.bot.botclass.impl.PureMelee.endFight(), com.runehive.content.bot.botclass.impl.PureRangeMelee.endFight(), com.runehive.content.bot.botclass.impl.PureMelee.initCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.meleePrayers(), and com.runehive.content.bot.botclass.impl.PureRangeMelee.rangedPrayers().
level
final int com.runehive.game.world.entity.mob.prayer.Prayer.level
The required prayer level.
Definition at line 75 of file Prayer.java.
Referenced by canToggle(), getLevel(), Prayer(), and Prayer().
listener
final CombatListener<Mob> com.runehive.game.world.entity.mob.prayer.Prayer.listener private
The listener.
Definition at line 90 of file Prayer.java.
Referenced by getListener(), and Prayer().
MYSTIC_LORE
com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_LORE =("Mystic Lore", 27, 6, 703, 642, 19818, new MysticLoreListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
Definition at line 53 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonus(), and com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getPrayerBonus().
MYSTIC_MIGHT
com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_MIGHT =("Mystic Might", 45, 12, 705, 650, 19823, new MysticMightListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
Definition at line 61 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonus(), and com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getPrayerBonus().
MYSTIC_WILL
com.runehive.game.world.entity.mob.prayer.Prayer.MYSTIC_WILL =("Mystic Will", 9, 3, 701, 634, 19814, new MysticWillListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
Definition at line 45 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.accuracy.MagicAccuracy.getPrayerBonus(), and com.runehive.game.world.entity.combat.accuracy.MagicAccuracyNpc.getPrayerBonus().
name
final String com.runehive.game.world.entity.mob.prayer.Prayer.name
The name of the prayer.
Definition at line 72 of file Prayer.java.
Referenced by getName(), Prayer(), and Prayer().
OFFENSIVE
final Collection<Prayer> com.runehive.game.world.entity.mob.prayer.Prayer.OFFENSIVE static private
Initial value:
= ImmutableList.of(
            CLARITY_OF_THOUGHT, IMPROVED_REFLEXES, INCREDIBLE_REFLEXES,
            SHARP_EYE, HAWK_EYE, EAGLE_EYE,
            MYSTIC_WILL, MYSTIC_LORE, MYSTIC_MIGHT,
            CHIVALRY, PIETY, RIGOUR, AUGURY
    )
Definition at line 173 of file Prayer.java.
Referenced by forType().
OVERHEAD
final Collection<Prayer> com.runehive.game.world.entity.mob.prayer.Prayer.OVERHEAD static
Initial value:
= ImmutableList.of(
            PROTECT_FROM_MAGIC, PROTECT_FROM_RANGE, PROTECT_FROM_MELEE,
            RETRIBUTION, REDEMPTION, SMITE
    )
Definition at line 190 of file Prayer.java.
Referenced by com.runehive.game.world.entity.mob.prayer.PrayerBook.deactivateOverhead(), forType(), and com.runehive.game.world.entity.mob.prayer.PrayerBook.hasOverhead().
PIETY
com.runehive.game.world.entity.mob.prayer.Prayer.PIETY =("Piety", 70, 24, 707, 656, 19827, new PietyListener(), Type.OFFENSIVE, Type.AGGRESSIVE, Type.DEFENSIVE)
Definition at line 67 of file Prayer.java.
Referenced by canToggle(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.endFight(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.endFight(), com.runehive.content.bot.botclass.impl.ZerkerMelee.endFight(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getPrayerBonus(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerDefenseBonus(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.initCombat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.initCombat(), and com.runehive.content.bot.botclass.impl.ZerkerMelee.initCombat().
PRESERVE
com.runehive.game.world.entity.mob.prayer.Prayer.PRESERVE =("Preserve", 55, 3, 708, 654, 28001, Type.NORMAL)
Definition at line 65 of file Prayer.java.
Referenced by canToggle(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.skillRestore().
PROTECT_FROM_MAGIC
com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MAGIC =("Protect from Magic", 37, 12, 95, 646, 5621, Type.OVERHEAD)
Definition at line 57 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatTeleblockEffect.apply(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.attack(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), getHeadIcon(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MagicAttack.hitsplat(), com.runehive.game.world.entity.combat.formula.MagicFormula.modifyDamage(), com.runehive.game.world.entity.mob.prayer.PrayerBook.resetProtection(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Venenatis.withinDistance().
PROTECT_FROM_MELEE
com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_MELEE =("Protect from Melee", 43, 12, 97, 648, 5623, Type.OVERHEAD)
Definition at line 59 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.attack(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), getHeadIcon(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.handleCombat(), com.runehive.content.bot.botclass.impl.PureMelee.handleCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.handleCombat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.handleCombat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.handleCombat(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.MeleeAttack.hit(), com.runehive.game.world.entity.combat.formula.MeleeFormula.modifyDamage(), com.runehive.game.world.entity.mob.prayer.PrayerBook.resetProtection(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), and com.runehive.game.world.entity.combat.strategy.npc.boss.StoneGuardian.BoomAttack.start().
PROTECT_FROM_RANGE
com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_FROM_RANGE =("Protect from Range", 40, 12, 96, 647, 5622, Type.OVERHEAD)
Definition at line 58 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonScimitar.attack(), com.runehive.game.world.entity.combat.strategy.npc.boss.DemonicGorillas.block(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.Porazdir.block(), getHeadIcon(), com.runehive.content.activity.infernomobs.JalAk.hit(), com.runehive.content.activity.infernomobs.JalTokJad.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.hit(), com.runehive.game.world.entity.combat.strategy.npc.boss.TzTokJad.RangedAttack.hitsplat(), com.runehive.game.world.entity.combat.formula.RangedFormula.modifyDamage(), com.runehive.game.world.entity.mob.prayer.PrayerBook.resetProtection(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special().
PROTECT_ITEM
com.runehive.game.world.entity.mob.prayer.Prayer.PROTECT_ITEM =("Protect Item", 25, 2, 91, 640, 5617, Type.NORMAL)
Definition at line 51 of file Prayer.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerDeath.calculateDropItems(), canToggle(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.endFight(), com.runehive.content.bot.botclass.impl.PureMelee.endFight(), com.runehive.content.bot.botclass.impl.PureRangeMelee.endFight(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.endFight(), com.runehive.content.bot.botclass.impl.ZerkerMelee.endFight(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.initCombat(), com.runehive.content.bot.botclass.impl.PureMelee.initCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.initCombat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.initCombat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.initCombat(), and com.runehive.content.ItemsKeptOnDeath.open().
qConfig
final int com.runehive.game.world.entity.mob.prayer.Prayer.qConfig private
The quick-prayer config id.
Definition at line 84 of file Prayer.java.
Referenced by getQConfig(), Prayer(), and Prayer().
RAPID_HEAL
com.runehive.game.world.entity.mob.prayer.Prayer.RAPID_HEAL =("Rapid Heal", 22, 2, 90, 639, 5616, Type.NORMAL)
Definition at line 50 of file Prayer.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.skillRestore().
RAPID_RESTORE
com.runehive.game.world.entity.mob.prayer.Prayer.RAPID_RESTORE =("Rapid Restore", 19, 1, 89, 638, 5615, Type.NORMAL)
Definition at line 49 of file Prayer.java.
Referenced by com.runehive.game.world.entity.mob.player.PlayerAssistant.skillRestore().
REDEMPTION
com.runehive.game.world.entity.mob.prayer.Prayer.REDEMPTION =("Redemption", 49, 6, 99, 652, 684, Type.OVERHEAD)
Definition at line 63 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.block(), getHeadIcon(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setPrayer().
RETRIBUTION
com.runehive.game.world.entity.mob.prayer.Prayer.RETRIBUTION =("Retribution", 46, 3, 98, 651, 683, Type.OVERHEAD)
Definition at line 62 of file Prayer.java.
Referenced by getHeadIcon(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setPrayer().
RIGOUR
com.runehive.game.world.entity.mob.prayer.Prayer.RIGOUR =("Rigour", 74, 24, 710, 657, 28004, new RigourListener(), Type.OFFENSIVE, Type.DEFENSIVE, Type.AGGRESSIVE)
Definition at line 68 of file Prayer.java.
Referenced by canToggle(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus(), and com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerDefenseBonus().
ROCK_SKIN
com.runehive.game.world.entity.mob.prayer.Prayer.ROCK_SKIN =("Rock Skin", 10, 6, 86, 635, 5612, new RockSkinListener(), Type.DEFENSIVE)
Definition at line 46 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getPrayerBonus(), and com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerDefenseBonus().
SHARP_EYE
com.runehive.game.world.entity.mob.prayer.Prayer.SHARP_EYE =("Sharp Eye", 8, 3, 700, 633, 19812, new SharpListener(), Type.OFFENSIVE, Type.AGGRESSIVE)
Definition at line 44 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.accuracy.RangeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.accuracy.RangeAccuracyNpc.getPrayerAttackBonus(), and com.runehive.game.world.entity.combat.maxhit.RangeMaxHit.getPrayerBonus().
SMITE
com.runehive.game.world.entity.mob.prayer.Prayer.SMITE =("Smite", 52, 18, 100, 653, 685, Type.OVERHEAD)
Definition at line 64 of file Prayer.java.
Referenced by com.runehive.content.bot.botclass.impl.AGSRuneMelee.endFight(), com.runehive.content.bot.botclass.impl.PureMelee.endFight(), com.runehive.content.bot.botclass.impl.PureRangeMelee.endFight(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.endFight(), com.runehive.content.bot.botclass.impl.ZerkerMelee.endFight(), getHeadIcon(), com.runehive.content.bot.botclass.impl.AGSRuneMelee.handleCombat(), com.runehive.content.bot.botclass.impl.PureMelee.handleCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.handleCombat(), com.runehive.content.bot.botclass.impl.WelfareRuneMelee.handleCombat(), com.runehive.content.bot.botclass.impl.ZerkerMelee.handleCombat(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.hit(), and com.runehive.game.world.entity.mob.player.PlayerAssistant.setPrayer().
STEEL_SKIN
com.runehive.game.world.entity.mob.prayer.Prayer.STEEL_SKIN =("Steel Skin", 28, 12, 92, 643, 5618, new SteelSkinListener(), Type.DEFENSIVE)
Definition at line 54 of file Prayer.java.
Referenced by com.runehive.content.bot.botclass.impl.PureMelee.endFight(), com.runehive.content.bot.botclass.impl.PureRangeMelee.endFight(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getPrayerBonus(), com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerDefenseBonus(), com.runehive.content.bot.botclass.impl.PureMelee.initCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.meleePrayers(), and com.runehive.content.bot.botclass.impl.PureRangeMelee.rangedPrayers().
SUPERHUMAN_STRENGTH
com.runehive.game.world.entity.mob.prayer.Prayer.SUPERHUMAN_STRENGTH =("Superhuman Strength", 13, 6, 87, 636, 5613, new SuperhumanStrengthListener(), Type.AGGRESSIVE)
Definition at line 47 of file Prayer.java.
THICK_SKIN
com.runehive.game.world.entity.mob.prayer.Prayer.THICK_SKIN =("Thick Skin", 1, 3, 83, 630, 5609, new ThickSkinListener(), Type.DEFENSIVE)
Definition at line 41 of file Prayer.java.
Referenced by com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerAttackBonus(), com.runehive.game.world.entity.combat.maxhit.MeleeMaxHit.getPrayerBonus(), and com.runehive.game.world.entity.combat.accuracy.MeleeAccuracy.getPrayerDefenseBonus().
types
final Type [] com.runehive.game.world.entity.mob.prayer.Prayer.types private
The prayer type.
Definition at line 93 of file Prayer.java.
Referenced by getTypes(), Prayer(), Prayer(), and toDeactivate().
ULTIMATE_STRENGTH
com.runehive.game.world.entity.mob.prayer.Prayer.ULTIMATE_STRENGTH =("Ultimate Strength", 31, 12, 93, 644, 5619, new UltimateStrengthListener(), Type.AGGRESSIVE)
Definition at line 55 of file Prayer.java.
Referenced by com.runehive.content.bot.botclass.impl.PureMelee.endFight(), com.runehive.content.bot.botclass.impl.PureRangeMelee.endFight(), com.runehive.content.bot.botclass.impl.PureMelee.initCombat(), com.runehive.content.bot.botclass.impl.PureRangeMelee.meleePrayers(), and com.runehive.content.bot.botclass.impl.PureRangeMelee.rangedPrayers().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/prayer/Prayer.java