RuneHive-Game: com.runehive.content.skill.impl.slayer.SlayerTask Enum Reference
com.runehive.content.skill.impl.slayer.SlayerTask Enum Reference
Holds all the slayer task data.
Public Member Functions
String getCombatLevel ()
Gets the combat level of the npc.
TaskDifficulty getDifficulty ()
Gets the difficulty of the slayer task.
int getLevel ()
Gets the level of the task.
String getLocation ()
Gets the teleport string.
String getName ()
Gets the name of the task.
String[] getNpc ()
Gets the npcs of the task.
Position getPosition ()
Gets the position of the task.
boolean isLevelNeeded ()
SlayerTask (String[] npc, int level, boolean levelNeeded, TaskDifficulty difficulty, Position position, String location)
Constructs a new SlayerTask.
boolean valid (String name)
Checks if the npc is a slayer task assignment.
Public Member Functions inherited from com.runehive.content.skill.impl.slayer.TaskInterface< Player >
boolean canAssign (final T player)
Static Public Member Functions
static ArrayList< SlayerTask > asList (Player player, TaskDifficulty difficulty)
Returns all the available slayer tasks for the player as a list.
static SlayerTask assign (Player player, TaskDifficulty difficulty)
Assigns a slayer task for the player.
static boolean canAttack (Player player, String npc)
Checks if a player can attack a slayer monster.
static int getCompletionExperience (TaskDifficulty difficulty)
static int getPoints (TaskDifficulty difficulty)
Public Attributes
ABERRANT_SPECTRES
ABYSSAL_DEMONS
ANKOU
AVIANSIES
BANSHEE
BLACK_DEMONS
BLOODVELDS
BLUE_DRAGONS
CERBERUS
CRAWLING_HAND
CRAZY_ARCHAEOLOGIST
DAGANNOTHS
DARK_BEAST
DUST_DEVILS
FIRE_GIANT
GARGOYLES
GREEN_DRAGON
HELLHOUNDS
HILL_GIANT
INFERNAL_MAGES
IRON_DRAGONS
KING_BLACK_DRAGON
KRAKEN
MITHRIL_DRAGON
ROCK_CRAB
SAND_CRAB
SKELETAL_WYVERN
SPIRTUAL_MAGES
SPIRTUAL_RANGERS
SPIRTUAL_WARRIORS
STEEL_DRAGONS
ZULRAH
Private Attributes
TaskDifficulty difficulty
The difficulty of the task.
final int level
The slayer level required to receive the task.
final boolean levelNeeded
final String location
The string for the position.
final String[] npc
Array of the slayer npc.
final Position position
The teleport position for the task.
Detailed Description
Holds all the slayer task data.
Author
Daniel
Ethan
Definition at line 17 of file SlayerTask.java.
Constructor & Destructor Documentation
SlayerTask()
com.runehive.content.skill.impl.slayer.SlayerTask.SlayerTask (String[] npc, int level, boolean levelNeeded, TaskDifficulty difficulty, Position position, String location)
Constructs a new SlayerTask.
Definition at line 251 of file SlayerTask.java.
{
        this.level = level;
        this.levelNeeded = levelNeeded;
        this.difficulty = difficulty;
        this.position = position;
        this.location = location;
        this.npc = npc;
    }
References difficulty, level, levelNeeded, location, npc, and position.
Referenced by asList(), assign(), and canAttack().
Member Function Documentation
asList()
ArrayList< SlayerTask > com.runehive.content.skill.impl.slayer.SlayerTask.asList (Player player, TaskDifficulty difficulty) static
Returns all the available slayer tasks for the player as a list.
Definition at line 332 of file SlayerTask.java.
{
        ArrayList<SlayerTask> tasks = new ArrayList<>();
        for (SlayerTask task : values()) {
            if (task.getLevel() > player.skills.getLevel(Skill.SLAYER))
                continue;
            if (!task.canAssign(player))
                continue;
            if (player.slayer.getBlocked().contains(task))
                continue;
            if (task.difficulty != difficulty)
                continue;
            tasks.add(task);
        }
        return tasks;
    }
References difficulty, com.runehive.content.skill.impl.slayer.Slayer.getBlocked(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.skill.Skill.SLAYER, com.runehive.game.world.entity.mob.player.Player.slayer, and SlayerTask().
Referenced by assign().
assign()
SlayerTask com.runehive.content.skill.impl.slayer.SlayerTask.assign (Player player, TaskDifficulty difficulty) static
Assigns a slayer task for the player.
Definition at line 321 of file SlayerTask.java.
{
        ArrayList<SlayerTask> tasks = asList(player, difficulty);
        if (tasks.isEmpty()) {
            return null;
        }
        return Utility.randomElement(tasks);
    }
References asList(), difficulty, com.runehive.util.Utility.randomElement(), and SlayerTask().
Referenced by com.runehive.content.skill.impl.slayer.Slayer.assign().
canAttack()
boolean com.runehive.content.skill.impl.slayer.SlayerTask.canAttack (Player player, String npc) static
Checks if a player can attack a slayer monster.
Definition at line 309 of file SlayerTask.java.
{
        for (SlayerTask task : values()) {
            for (String name : task.getNpc()) {
                if (npc.equalsIgnoreCase(name) && task.isLevelNeeded() && player.skills.getLevel(Skill.SLAYER) < task.getLevel()) {
                    return false;
                }
            }
        }
        return true;
    }
References com.runehive.game.world.entity.skill.SkillManager.getLevel(), npc, com.runehive.game.world.entity.mob.Mob.skills, com.runehive.game.world.entity.skill.Skill.SLAYER, and SlayerTask().
Referenced by com.runehive.game.world.entity.combat.CombatUtil.canAttack().
getCombatLevel()
String com.runehive.content.skill.impl.slayer.SlayerTask.getCombatLevel ()
Gets the combat level of the npc.
Definition at line 295 of file SlayerTask.java.
{
        return NpcDefinition.getCombatLevelRange(npc[0]);
    }
References com.runehive.game.world.entity.mob.npc.definition.NpcDefinition.getCombatLevelRange(), and npc.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getCompletionExperience()
int com.runehive.content.skill.impl.slayer.SlayerTask.getCompletionExperience (TaskDifficulty difficulty) static
Definition at line 362 of file SlayerTask.java.
{
        switch (difficulty) {
            case EASY:
                return 5000;
            case MEDIUM:
                return 10000;
            case HARD:
                return 15000;
            case BOSS:
                return 25000;
        }
        return 0;
    }
References difficulty.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.activate().
getDifficulty()
TaskDifficulty com.runehive.content.skill.impl.slayer.SlayerTask.getDifficulty ()
Gets the difficulty of the slayer task.
Definition at line 275 of file SlayerTask.java.
{
        return difficulty;
    }
References difficulty.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.assign().
getLevel()
int com.runehive.content.skill.impl.slayer.SlayerTask.getLevel ()
Gets the level of the task.
Definition at line 266 of file SlayerTask.java.
{
        return level;
    }
References level.
getLocation()
String com.runehive.content.skill.impl.slayer.SlayerTask.getLocation ()
Gets the teleport string.
Definition at line 285 of file SlayerTask.java.
{
        return location;
    }
References location.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getName()
String com.runehive.content.skill.impl.slayer.SlayerTask.getName ()
Gets the name of the task.
Definition at line 261 of file SlayerTask.java.
{
        return npc[0];
    }
References npc.
Referenced by com.runehive.content.skill.impl.slayer.SlayerTab.refresh().
getNpc()
String[] com.runehive.content.skill.impl.slayer.SlayerTask.getNpc ()
Gets the npcs of the task.
Definition at line 290 of file SlayerTask.java.
{
        return npc;
    }
References npc.
getPoints()
int com.runehive.content.skill.impl.slayer.SlayerTask.getPoints (TaskDifficulty difficulty) static
Definition at line 348 of file SlayerTask.java.
{
        switch (difficulty) {
            case EASY:
                return 15;
            case MEDIUM:
                return 20;
            case HARD:
                return 30;
            case BOSS:
                return 35;
        }
        return 0;
    }
References difficulty.
Referenced by com.runehive.content.skill.impl.slayer.Slayer.activate().
getPosition()
Position com.runehive.content.skill.impl.slayer.SlayerTask.getPosition ()
Gets the position of the task.
Definition at line 280 of file SlayerTask.java.
{
        return position;
    }
References position.
isLevelNeeded()
boolean com.runehive.content.skill.impl.slayer.SlayerTask.isLevelNeeded ()
Definition at line 270 of file SlayerTask.java.
{
        return levelNeeded;
    }
References levelNeeded.
valid()
boolean com.runehive.content.skill.impl.slayer.SlayerTask.valid (String name)
Checks if the npc is a slayer task assignment.
Definition at line 300 of file SlayerTask.java.
{
        for (String npc : npc) {
            if (npc.equalsIgnoreCase(name))
                return true;
        }
        return false;
    }
References npc.
Referenced by com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.SlayerHelmListener.modifyAttackLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyMagicLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyRangedLevel(), com.runehive.game.world.entity.combat.attack.listener.item.ImbuedSlayerHelmListener.modifyStrengthLevel(), and com.runehive.game.world.entity.combat.attack.listener.item.SlayerHelmListener.modifyStrengthLevel().
Member Data Documentation
ABERRANT_SPECTRES
com.runehive.content.skill.impl.slayer.SlayerTask.ABERRANT_SPECTRES
Initial value:
=(new String[]{"Aberrant spectre"}, 60, true, TaskDifficulty.MEDIUM, new Position(3420, 3553, 1), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 93 of file SlayerTask.java.
                                  {"Aberrant spectre"}, 60, true, TaskDifficulty.MEDIUM, new Position(3420, 3553, 1), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
ABYSSAL_DEMONS
com.runehive.content.skill.impl.slayer.SlayerTask.ABYSSAL_DEMONS
Initial value:
=(new String[]{"Abyssal Demon"}, 85, true, TaskDifficulty.HARD, new Position(3414, 3558), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 85;
        }
    }
Definition at line 197 of file SlayerTask.java.
                               {"Abyssal Demon"}, 85, true, TaskDifficulty.HARD, new Position(3414, 3558), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 85;
        }
    },
ANKOU
com.runehive.content.skill.impl.slayer.SlayerTask.ANKOU
Initial value:
=(new String[]{"Ankou"}, 1, false, TaskDifficulty.HARD, new Position(2359, 5236), "Stronghold of Security") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 99 of file SlayerTask.java.
                      {"Ankou"}, 1, false, TaskDifficulty.HARD, new Position(2359, 5236), "Stronghold of Security") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
AVIANSIES
com.runehive.content.skill.impl.slayer.SlayerTask.AVIANSIES
Initial value:
=(new String[]{"Aviansie"}, 50, false, TaskDifficulty.MEDIUM, new Position(2882, 5287, 2), "Stronghold of Security") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 79 of file SlayerTask.java.
                          {"Aviansie"}, 50, false, TaskDifficulty.MEDIUM, new Position(2882, 5287, 2), "Stronghold of Security") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
BANSHEE
com.runehive.content.skill.impl.slayer.SlayerTask.BANSHEE
Initial value:
=(new String[]{"Banshee"}, 15, false, TaskDifficulty.MEDIUM, new Position(3340, 3560), "Pollnivneach Smoke Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 60 of file SlayerTask.java.
                        {"Banshee"}, 15, false, TaskDifficulty.MEDIUM, new Position(3340, 3560), "Pollnivneach Smoke Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
BLACK_DEMONS
com.runehive.content.skill.impl.slayer.SlayerTask.BLACK_DEMONS
Initial value:
=(new String[]{"Black demon"}, 12, false, TaskDifficulty.HARD, new Position(2876, 9790), "Taverly Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 105 of file SlayerTask.java.
                             {"Black demon"}, 12, false, TaskDifficulty.HARD, new Position(2876, 9790), "Taverly Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
BLOODVELDS
com.runehive.content.skill.impl.slayer.SlayerTask.BLOODVELDS
Initial value:
=(new String[]{"Bloodveld"}, 15, false, TaskDifficulty.MEDIUM, new Position(3419, 3562), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 66 of file SlayerTask.java.
                           {"Bloodveld"}, 15, false, TaskDifficulty.MEDIUM, new Position(3419, 3562), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
BLUE_DRAGONS
com.runehive.content.skill.impl.slayer.SlayerTask.BLUE_DRAGONS
Initial value:
=(new String[]{"Blue dragon", "Baby blue dragon"}, 35, false, TaskDifficulty.MEDIUM, new Position(2886, 9799), "Taverly Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 144 of file SlayerTask.java.
                             {"Blue dragon", "Baby blue dragon"}, 35, false, TaskDifficulty.MEDIUM, new Position(2886, 9799), "Taverly Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
CERBERUS
com.runehive.content.skill.impl.slayer.SlayerTask.CERBERUS
Initial value:
=(new String[]{"Cerberus"}, 91, true, TaskDifficulty.BOSS, new Position(1310, 1268, 0), "Cerberus' Lair") {
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 91;
        }
    }
Definition at line 231 of file SlayerTask.java.
                         {"Cerberus"}, 91, true, TaskDifficulty.BOSS, new Position(1310, 1268, 0), "Cerberus' Lair") {
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 91;
        }
    };
CRAWLING_HAND
com.runehive.content.skill.impl.slayer.SlayerTask.CRAWLING_HAND
Initial value:
=(new String[]{"Crawling hand"}, 1, false, TaskDifficulty.EASY, new Position(3424, 3543), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 32 of file SlayerTask.java.
                              {"Crawling hand"}, 1, false, TaskDifficulty.EASY, new Position(3424, 3543), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
CRAZY_ARCHAEOLOGIST
com.runehive.content.skill.impl.slayer.SlayerTask.CRAZY_ARCHAEOLOGIST
Initial value:
=(new String[]{"Crazy archaeologist"}, 60, false, TaskDifficulty.HARD, new Position(2966, 3698), "Wilderness") {
        @Override
        public boolean canAssign(Player player) {
            return player.slayer.getUnlocked().contains(SlayerUnlockable.CRAZY_ARCHAEOLOGIST);
        }
    }
Definition at line 156 of file SlayerTask.java.
                                    {"Crazy archaeologist"}, 60, false, TaskDifficulty.HARD, new Position(2966, 3698), "Wilderness") {
        @Override
        public boolean canAssign(Player player) {
            return player.slayer.getUnlocked().contains(SlayerUnlockable.CRAZY_ARCHAEOLOGIST);
        }
    },
DAGANNOTHS
com.runehive.content.skill.impl.slayer.SlayerTask.DAGANNOTHS
Initial value:
=(new String[]{"Dagannoth", "Dagannoth mother", "Dagannoth Supreme", "Dagannoth Prime", "Dagannoth Rex"}, 1, false, TaskDifficulty.HARD, new Position(1891, 4369), "Fremennik Province Light House") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 111 of file SlayerTask.java.
                           {"Dagannoth", "Dagannoth mother", "Dagannoth Supreme", "Dagannoth Prime", "Dagannoth Rex"}, 1, false, TaskDifficulty.HARD, new Position(1891, 4369), "Fremennik Province Light House") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
DARK_BEAST
com.runehive.content.skill.impl.slayer.SlayerTask.DARK_BEAST
Initial value:
=(new String[]{"Dark beast"}, 90, true, TaskDifficulty.HARD, new Position(2010, 4644), "Temple of Light dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 90;
        }
    }
Definition at line 203 of file SlayerTask.java.
                           {"Dark beast"}, 90, true, TaskDifficulty.HARD, new Position(2010, 4644), "Temple of Light dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 90;
        }
    },
difficulty
TaskDifficulty com.runehive.content.skill.impl.slayer.SlayerTask.difficulty private
The difficulty of the task.
Definition at line 239 of file SlayerTask.java.
Referenced by asList(), assign(), getCompletionExperience(), getDifficulty(), getPoints(), and SlayerTask().
DUST_DEVILS
com.runehive.content.skill.impl.slayer.SlayerTask.DUST_DEVILS
Initial value:
=(new String[]{"Dust devil"}, 65, true, TaskDifficulty.MEDIUM, new Position(3239, 9364), "Pollnivneach Smoke Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 86 of file SlayerTask.java.
                            {"Dust devil"}, 65, true, TaskDifficulty.MEDIUM, new Position(3239, 9364), "Pollnivneach Smoke Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
FIRE_GIANT
com.runehive.content.skill.impl.slayer.SlayerTask.FIRE_GIANT
Initial value:
=(new String[]{"Fire giant"}, 5, false, TaskDifficulty.MEDIUM, new Position(2655, 9489), "Slayer Cave") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 46 of file SlayerTask.java.
                           {"Fire giant"}, 5, false, TaskDifficulty.MEDIUM, new Position(2655, 9489), "Slayer Cave") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
GARGOYLES
com.runehive.content.skill.impl.slayer.SlayerTask.GARGOYLES
Initial value:
=(new String[]{"Gargoyle"}, 75, true, TaskDifficulty.HARD, new Position(3437, 3542), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 75;
        }
    }
Definition at line 150 of file SlayerTask.java.
                          {"Gargoyle"}, 75, true, TaskDifficulty.HARD, new Position(3437, 3542), "Slayer Tower") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 75;
        }
    },
GREEN_DRAGON
com.runehive.content.skill.impl.slayer.SlayerTask.GREEN_DRAGON
Initial value:
=(new String[]{"Green dragon", "Baby green dragon"}, 5, false, TaskDifficulty.MEDIUM, new Position(3339, 3668), "WILDERNESS") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 53 of file SlayerTask.java.
                             {"Green dragon", "Baby green dragon"}, 5, false, TaskDifficulty.MEDIUM, new Position(3339, 3668), "WILDERNESS") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
HELLHOUNDS
com.runehive.content.skill.impl.slayer.SlayerTask.HELLHOUNDS
Initial value:
=(new String[]{"Hellhound", "Cerberus"}, 12, false, TaskDifficulty.HARD, new Position(2827, 9847), "Taverly Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 118 of file SlayerTask.java.
                           {"Hellhound", "Cerberus"}, 12, false, TaskDifficulty.HARD, new Position(2827, 9847), "Taverly Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
HILL_GIANT
com.runehive.content.skill.impl.slayer.SlayerTask.HILL_GIANT
Initial value:
=(new String[]{"Hill Giant"}, 1, false, TaskDifficulty.EASY, new Position(3117, 9856), "") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 39 of file SlayerTask.java.
                           {"Hill Giant"}, 1, false, TaskDifficulty.EASY, new Position(3117, 9856), "") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
INFERNAL_MAGES
com.runehive.content.skill.impl.slayer.SlayerTask.INFERNAL_MAGES
Initial value:
=(new String[]{"Infernal Mage"}, 45, false, TaskDifficulty.MEDIUM, new Position(3445, 3560), "Pollnivneach Well Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 72 of file SlayerTask.java.
                               {"Infernal Mage"}, 45, false, TaskDifficulty.MEDIUM, new Position(3445, 3560), "Pollnivneach Well Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
IRON_DRAGONS
com.runehive.content.skill.impl.slayer.SlayerTask.IRON_DRAGONS
Initial value:
=(new String[]{"Iron dragon"}, 35, false, TaskDifficulty.HARD, new Position(2682, 9463), "Karamja Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 138 of file SlayerTask.java.
                             {"Iron dragon"}, 35, false, TaskDifficulty.HARD, new Position(2682, 9463), "Karamja Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
KING_BLACK_DRAGON
com.runehive.content.skill.impl.slayer.SlayerTask.KING_BLACK_DRAGON
Initial value:
=(new String[]{"King black dragon"}, 1, false, TaskDifficulty.BOSS, new Position(3000, 3849), "Wilderness") {
        @Override
        public boolean canAssign(Player player) {
            return player.slayer.getUnlocked().contains(SlayerUnlockable.KING_BLACK_DRAGON);
        }
    }
Definition at line 215 of file SlayerTask.java.
                                  {"King black dragon"}, 1, false, TaskDifficulty.BOSS, new Position(3000, 3849), "Wilderness") {
        @Override
        public boolean canAssign(Player player) {
            return player.slayer.getUnlocked().contains(SlayerUnlockable.KING_BLACK_DRAGON);
        }
    },
KRAKEN
com.runehive.content.skill.impl.slayer.SlayerTask.KRAKEN
Initial value:
=(new String[]{"Kraken"}, 87, true, TaskDifficulty.BOSS, new Position(2276, 10000, 0), "Kraken cave") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= getLevel();
        }
    }
Definition at line 209 of file SlayerTask.java.
                       {"Kraken"}, 87, true, TaskDifficulty.BOSS, new Position(2276, 10000, 0), "Kraken cave") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= getLevel();
        }
    },
level
final int com.runehive.content.skill.impl.slayer.SlayerTask.level private
The slayer level required to receive the task.
Definition at line 234 of file SlayerTask.java.
Referenced by getLevel(), and SlayerTask().
levelNeeded
final boolean com.runehive.content.skill.impl.slayer.SlayerTask.levelNeeded private
Definition at line 236 of file SlayerTask.java.
Referenced by isLevelNeeded(), and SlayerTask().
location
final String com.runehive.content.skill.impl.slayer.SlayerTask.location private
The string for the position.
Definition at line 245 of file SlayerTask.java.
Referenced by getLocation(), and SlayerTask().
MITHRIL_DRAGON
com.runehive.content.skill.impl.slayer.SlayerTask.MITHRIL_DRAGON
Initial value:
=(new String[]{"Mithril dragon"}, 1, false, TaskDifficulty.HARD, new Position(1748, 5326), "Ancient Caverns") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 125 of file SlayerTask.java.
                               {"Mithril dragon"}, 1, false, TaskDifficulty.HARD, new Position(1748, 5326), "Ancient Caverns") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
npc
final String [] com.runehive.content.skill.impl.slayer.SlayerTask.npc private
Array of the slayer npc.
Definition at line 248 of file SlayerTask.java.
Referenced by canAttack(), getCombatLevel(), getName(), getNpc(), SlayerTask(), and valid().
position
final Position com.runehive.content.skill.impl.slayer.SlayerTask.position private
The teleport position for the task.
Definition at line 242 of file SlayerTask.java.
Referenced by getPosition(), and SlayerTask().
ROCK_CRAB
com.runehive.content.skill.impl.slayer.SlayerTask.ROCK_CRAB
Initial value:
=(new String[]{"Rock Crab"}, 1, false, TaskDifficulty.EASY, new Position(2676, 3711), "Camelot") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 25 of file SlayerTask.java.
                          {"Rock Crab"}, 1, false, TaskDifficulty.EASY, new Position(2676, 3711), "Camelot") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
SAND_CRAB
com.runehive.content.skill.impl.slayer.SlayerTask.SAND_CRAB
Initial value:
=(new String[]{"Sand Crab"}, 1, false, TaskDifficulty.EASY, new Position(1726, 3463), "") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 18 of file SlayerTask.java.
                          {"Sand Crab"}, 1, false, TaskDifficulty.EASY, new Position(1726, 3463), "") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
SKELETAL_WYVERN
com.runehive.content.skill.impl.slayer.SlayerTask.SKELETAL_WYVERN
Initial value:
=(new String[]{"Skeletal wyvern"}, 72, true, TaskDifficulty.HARD, new Position(3056, 9562), "Asgarnia Ice Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 72;
        }
    }
Definition at line 191 of file SlayerTask.java.
                                {"Skeletal wyvern"}, 72, true, TaskDifficulty.HARD, new Position(3056, 9562), "Asgarnia Ice Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return player.skills.getMaxLevel(Skill.SLAYER) >= 72;
        }
    },
SPIRTUAL_MAGES
com.runehive.content.skill.impl.slayer.SlayerTask.SPIRTUAL_MAGES
Initial value:
=(new String[]{"Spiritual Mage"}, 83, false, TaskDifficulty.HARD, new Position(2882, 5287, 2), "Godwars Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 185 of file SlayerTask.java.
                               {"Spiritual Mage"}, 83, false, TaskDifficulty.HARD, new Position(2882, 5287, 2), "Godwars Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
SPIRTUAL_RANGERS
com.runehive.content.skill.impl.slayer.SlayerTask.SPIRTUAL_RANGERS
Initial value:
=(new String[]{"Spiritual Ranger"}, 63, false, TaskDifficulty.HARD, new Position(2882, 5287, 2), "Godwars Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 173 of file SlayerTask.java.
                                 {"Spiritual Ranger"}, 63, false, TaskDifficulty.HARD, new Position(2882, 5287, 2), "Godwars Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
SPIRTUAL_WARRIORS
com.runehive.content.skill.impl.slayer.SlayerTask.SPIRTUAL_WARRIORS
Initial value:
=(new String[]{"Spiritual Warrior"}, 68, false, TaskDifficulty.HARD, new Position(2882, 5287, 2), "Godwars Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 179 of file SlayerTask.java.
                                  {"Spiritual Warrior"}, 68, false, TaskDifficulty.HARD, new Position(2882, 5287, 2), "Godwars Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
STEEL_DRAGONS
com.runehive.content.skill.impl.slayer.SlayerTask.STEEL_DRAGONS
Initial value:
=(new String[]{"Steel dragon"}, 35, false, TaskDifficulty.HARD, new Position(2629, 9422), "Karamja Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    }
Definition at line 132 of file SlayerTask.java.
                              {"Steel dragon"}, 35, false, TaskDifficulty.HARD, new Position(2629, 9422), "Karamja Dungeon") {
        @Override
        public boolean canAssign(Player player) {
            return true;
        }
    },
ZULRAH
com.runehive.content.skill.impl.slayer.SlayerTask.ZULRAH
Initial value:
=(new String[]{"Zulrah"}, 95, false, TaskDifficulty.BOSS, new Position(2206, 3056, 0), "Zulrah's Shrine") {
        @Override
        public boolean canAssign(Player player) {
            return player.slayer.getUnlocked().contains(SlayerUnlockable.ZULRAH);
        }
    }
Definition at line 221 of file SlayerTask.java.
                       {"Zulrah"}, 95, false, TaskDifficulty.BOSS, new Position(2206, 3056, 0), "Zulrah's Shrine") {
        @Override
        public boolean canAssign(Player player) {
            return player.slayer.getUnlocked().contains(SlayerUnlockable.ZULRAH);
        }
    },
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/slayer/SlayerTask.java