RuneHive-Game: com.runehive.game.world.entity.mob.player.relations.ChatColor Enum Reference
com.runehive.game.world.entity.mob.player.relations.ChatColor Enum Reference
Public Member Functions
ChatColor (int code)
int getCode ()
Public Attributes
CYAN =(3)
FLASH_1 =(6)
FLASH_2 =(7)
FLASH_3 =(8)
GLOW_1 =(9)
GLOW_2 =(10)
GLOW_3 =(11)
GREEN =(2)
PURPLE =(4)
RED =(1)
WHITE =(5)
YELLOW =(0)
Static Public Attributes
static final ChatColor[] values = values()
Private Attributes
final int code
Detailed Description
Definition at line 3 of file ChatColor.java.
Constructor & Destructor Documentation
ChatColor()
com.runehive.game.world.entity.mob.player.relations.ChatColor.ChatColor (int code)
Definition at line 20 of file ChatColor.java.
{
        this.code = code;
    }
References code.
Member Function Documentation
getCode()
int com.runehive.game.world.entity.mob.player.relations.ChatColor.getCode ()
Definition at line 24 of file ChatColor.java.
{
        return code;
    }
References code.
Referenced by com.runehive.net.packet.out.SendPlayerUpdate.appendChatMask().
Member Data Documentation
code
final int com.runehive.game.world.entity.mob.player.relations.ChatColor.code private
Definition at line 18 of file ChatColor.java.
Referenced by ChatColor(), and getCode().
CYAN
com.runehive.game.world.entity.mob.player.relations.ChatColor.CYAN =(3)
Definition at line 8 of file ChatColor.java.
FLASH_1
com.runehive.game.world.entity.mob.player.relations.ChatColor.FLASH_1 =(6)
Definition at line 11 of file ChatColor.java.
FLASH_2
com.runehive.game.world.entity.mob.player.relations.ChatColor.FLASH_2 =(7)
Definition at line 12 of file ChatColor.java.
FLASH_3
com.runehive.game.world.entity.mob.player.relations.ChatColor.FLASH_3 =(8)
Definition at line 13 of file ChatColor.java.
GLOW_1
com.runehive.game.world.entity.mob.player.relations.ChatColor.GLOW_1 =(9)
Definition at line 14 of file ChatColor.java.
GLOW_2
com.runehive.game.world.entity.mob.player.relations.ChatColor.GLOW_2 =(10)
Definition at line 15 of file ChatColor.java.
GLOW_3
com.runehive.game.world.entity.mob.player.relations.ChatColor.GLOW_3 =(11)
Definition at line 16 of file ChatColor.java.
GREEN
com.runehive.game.world.entity.mob.player.relations.ChatColor.GREEN =(2)
Definition at line 7 of file ChatColor.java.
PURPLE
com.runehive.game.world.entity.mob.player.relations.ChatColor.PURPLE =(4)
Definition at line 9 of file ChatColor.java.
RED
com.runehive.game.world.entity.mob.player.relations.ChatColor.RED =(1)
Definition at line 6 of file ChatColor.java.
values
final ChatColor [] com.runehive.game.world.entity.mob.player.relations.ChatColor.values = values() static
Definition at line 28 of file ChatColor.java.
Referenced by com.runehive.net.packet.in.ChatMessagePacketListener.handlePacket(), and com.runehive.game.world.entity.mob.player.relations.ChatMessage.isValid().
WHITE
com.runehive.game.world.entity.mob.player.relations.ChatColor.WHITE =(5)
Definition at line 10 of file ChatColor.java.
YELLOW
com.runehive.game.world.entity.mob.player.relations.ChatColor.YELLOW =(0)
Definition at line 5 of file ChatColor.java.
Referenced by com.runehive.game.world.entity.mob.player.relations.ChatMessage.ChatMessage(), and com.runehive.game.world.entity.mob.player.relations.ChatMessage.create().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/player/relations/ChatColor.java