RuneHive-Game: com.runehive.content.ItemCreation.CreationData Enum Reference
com.runehive.content.ItemCreation.CreationData Enum Reference
Holds the creation data.
Public Member Functions
CreationData (Item product, Item dropped, Skill[] level, Item... required)
Constructs a new CreationData.
CreationData (Item[] product, Item dropped, Skill[] level, Item... required)
Constructs a new CreationData.
Static Public Member Functions
static Optional< CreationData > forItem (Item item)
Finds the creation data based off the product item.
static Optional< CreationData > forItems (Item first, Item second)
Handles finding the creation data based off the items used.
Public Attributes
ABYSSAL_FROZEN_WHIP =(new Item(12774), new Item(4151, 1), null, new Item(12769, 1), new Item(4151, 1))
ABYSSAL_TENTACLE_WHIP =(new Item(12006, 1), new Item(12004, 1), null, new Item(12004, 1), new Item(4151, 1))
ABYSSAL_VOLCANIC_WHIP =(new Item(12773), new Item(4151, 1), null, new Item(12771, 1), new Item(4151, 1))
ARMADYL_GODSWORD =(new Item[]{new Item(11802)}, null, null, new Item(11798), new Item(11810))
ASSEMBLER_MAX_CAPE =(new Item[]{new Item(21898), new Item(21900)}, null, null, new Item(22109), new Item(13280), new Item(13281))
AVA2_MAX_CAPE =(new Item[]{new Item(13337), new Item(13338)}, null, null, new Item(10499), new Item(13280), new Item(13281))
BANDOS_GODSWORD =(new Item[]{new Item(11804)}, null, null, new Item(11798), new Item(11812))
BLACK_SLAYER_HELM =(new Item[]{new Item(19639)}, null, null, new Item(11864), new Item(7980))
BLACK_SLAYER_HELM_I =(new Item[]{new Item(19641)}, null, null, new Item(11865), new Item(7980))
BLESSED_SPIRIT_SHIELD =(new Item(12831), null, null, new Item(12829), new Item(12833))
BLUE_DARKBOW =(new Item(12766), new Item(11235, 1), null, new Item(12757, 1), new Item(11235, 1))
CAP_AND_GOGGLES =(new Item(9946), null, null, new Item(9945, 1), new Item(9472, 1))
DRAGON_FIRE_SHIELD =(new Item(11283), null, null, new Item(11286,1), new Item(1540,1))
DRAGON_PICKAXE =(new Item(12797), null, null, new Item(11920, 1), new Item(12800, 1))
final Item dropped
The dropped item.
ETERNAL_BOOTS =(new Item[]{new Item(13235)}, null, new Skill[] { new Skill(Skill.RUNECRAFTING, 60,0), new Skill(Skill.MAGIC, 60, 0) }, new Item(6920), new Item(13227))
FIRE_MAX_CAPE =(new Item[]{new Item(13329), new Item(13330)}, null, null, new Item(6570), new Item(13280), new Item(13281))
Max Capes.
FURY_AMULET_KIT =(new Item(12436), null, null, new Item(6585, 1), new Item(12526, 1))
GODSWORD_BLADE =(new Item[]{new Item(11798)}, null, new Skill[] { new Skill(Skill.SMITHING, 80,0) }, new Item(11822), new Item(11794))
GODSWORD_BLADE_I =(new Item[]{new Item(11798)}, null, new Skill[] { new Skill(Skill.SMITHING, 80,0) }, new Item(11818), new Item(11800))
GODSWORD_BLADE_II =(new Item[]{new Item(11798)}, null, new Skill[] { new Skill(Skill.SMITHING, 80,0) }, new Item(11820), new Item(11796))
GODSWORD_SHARDS_1_AND_2 =(new Item[]{new Item(11794)}, null, null, new Item(11818), new Item(11820))
GODSWORD_SHARDS_1_AND_3 =(new Item[]{new Item(11796)}, null, null, new Item(11818), new Item(11822))
GODSWORD_SHARDS_2_AND_3 =(new Item[]{new Item(11800)}, null, null, new Item(11822), new Item(11820))
GOLDEN_PROS_BOOTS =(new Item(25555), null, null, new Item(25547, 1), new Item(12016, 1))
GOLDEN_PROS_HELM =(new Item(25549), null, null, new Item(25547, 1), new Item(12013, 1))
GOLDEN_PROS_JACKET =(new Item(25551), null, null, new Item(25547, 1), new Item(12014, 1))
GOLDEN_PROS_LEGS =(new Item(25553), null, null, new Item(25547, 1), new Item(12015, 1))
GREEN_DARKBOW =(new Item(12765), new Item(11235, 1), null, new Item(12759, 1), new Item(11235, 1))
GREEN_SLAYER_HELM =(new Item[]{new Item(19643)}, null, null, new Item(11864), new Item(7981))
GREEN_SLAYER_HELMI =(new Item[]{new Item(19645)}, null, null, new Item(11865), new Item(7981))
GUTHIX_MAX_CAPE =(new Item[]{new Item(13335), new Item(13336)}, null, null, new Item(10448), new Item(13280), new Item(13281))
IMBUED_GUTHIX_MAX_CAPE =(new Item[]{new Item(21784), new Item(21786)}, null, null, new Item(21793), new Item(13280), new Item(13281))
IMBUED_SARADOMIN_MAX_CAPE =(new Item[]{new Item(21776), new Item(21778)}, null, null, new Item(21791), new Item(13280), new Item(13281))
IMBUED_ZAMORAK_MAX_CAPE =(new Item[]{new Item(21780), new Item(21782)}, null, null, new Item(21795), new Item(13280), new Item(13281))
INFERNAL_AXE =(new Item[]{new Item(13241)}, null, new Skill[] { new Skill(Skill.WOODCUTTING, 61,0), new Skill(Skill.FIREMAKING, 85, 0) }, new Item(6739), new Item(13233))
INFERNAL_HARPOON =(new Item[]{new Item(21031)}, null, new Skill[] { new Skill(Skill.COOKING, 85,0) }, new Item(21028), new Item(13233))
INFERNAL_MAX_CAPE =(new Item[]{new Item(21284), new Item(21282)}, null, null, new Item(21295), new Item(13280), new Item(13281))
INFERNAL_PICKAXE =(new Item[]{new Item(13243)}, null, new Skill[] { new Skill(Skill.SMITHING, 85,0) }, new Item(11920), new Item(13233))
final Skill[] level
The skill required.
MAGIC_SHORTBOW_INFUSED =(new Item(12788), new Item(861), null, new Item(12786, 1), new Item(861, 1))
PEGASIAN_BOOTS =(new Item[]{new Item(13237)}, null, new Skill[] { new Skill(Skill.RUNECRAFTING, 60,0), new Skill(Skill.MAGIC, 60, 0) }, new Item(2577), new Item(13229))
PRIMORDIAL_BOOTS =(new Item[]{new Item(13239)}, null, new Skill[] { new Skill(Skill.RUNECRAFTING, 60,0), new Skill(Skill.MAGIC, 60, 0) }, new Item(11840), new Item(13231))
final Item[] product
The product of the creation.
PURPLE_SLAYER_HELM =(new Item[]{new Item(21264)}, null, null, new Item(11864), new Item(21275))
PURPLE_SLAYER_HELMI =(new Item[]{new Item(21266)}, null, null, new Item(11865), new Item(21275))
RED_SLAYER_HELM =(new Item[]{new Item(19647)}, null, null, new Item(11864), new Item(7979))
RED_SLAYER_HELMI =(new Item[]{new Item(19649)}, null, null, new Item(11865), new Item(7979))
final Item[] required
The items required.
RING_OF_WEALTH_I =(new Item(12785), null, null, new Item(12783, 1), new Item(2572, 1))
SARADOMIN_GODSWORD =(new Item[]{new Item(11806)}, null, null, new Item(11798), new Item(11814))
SARADOMIN_MAX_CAPE =(new Item[]{new Item(13331), new Item(13332)}, null, null, new Item(10446), new Item(13280), new Item(13281))
SERPENTINE_VISAGE =(new Item(12929), new Item(12927, 1), null, new Item(12927, 1), new Item(1755, 1))
SLAYER_HELM =(new Item[]{new Item(11864)}, null, new Skill[]{new Skill(Skill.CRAFTING, 55, 0)}, new Item(8921), new Item(4166), new Item(4168), new Item(4164), new Item(4551), new Item(4155))
SLAYER_HELM_I =(new Item[]{new Item(11864)}, null, new Skill[]{new Skill(Skill.CRAFTING, 55, 0)}, new Item(8901), new Item(4166), new Item(4168), new Item(4164), new Item(4551), new Item(4155))
TOXIC_BLOWPIPE =(new Item(12924), null, new Skill[] { new Skill(Skill.FLETCHING, 53, 0)}, new Item(12922, 1), new Item(1755, 1))
TOXIC_STAFF_OF_THE_DEAD =(new Item(12904), null, new Skill[]{new Skill(Skill.CRAFTING, 59, 0)}, new Item(11791, 1), new Item(12932, 1))
TRIDENT_OF_THE_SWAMP =(new Item(12899), null, new Skill[]{new Skill(Skill.CRAFTING, 59, 0)}, new Item(12932, 1), new Item(11907, 1))
WHITE_DARKBOW =(new Item(12768), new Item(11235, 1), null, new Item(12763, 1), new Item(11235, 1))
YELLOW_DARKBOW =(new Item(12767), new Item(11235, 1), null, new Item(12761, 1), new Item(11235, 1))
ZAMORAK_GODSWORD =(new Item[]{new Item(11808)}, null, null, new Item(11798), new Item(11816))
ZAMORAK_MAX_CAPE =(new Item[]{new Item(13333), new Item(13334)}, null, null, new Item(10450), new Item(13280), new Item(13281))
ZENYTE_AMULET =(new Item(19541), null,new Skill[] { new Skill(Skill.CRAFTING, 98,200) }, new Item(Items.GOLD_BAR, 1), new Item(Items.AMULET_MOULD, 1), new Item(Items.ZENYTE))
ZENYTE_BRACELET =(new Item(19492), null,new Skill[] { new Skill(Skill.CRAFTING, 95,180) }, new Item(Items.GOLD_BAR, 1), new Item(Items.BRACELET_MOULD, 1), new Item(Items.ZENYTE))
ZENYTE_NECKLACE =(new Item(19535), null,new Skill[] { new Skill(Skill.CRAFTING, 92,165) }, new Item(Items.GOLD_BAR, 1), new Item(Items.NECKLACE_MOULD, 1), new Item(Items.ZENYTE))
ZENYTE_RING =(new Item(19538), null,new Skill[] { new Skill(Skill.CRAFTING, 89,150) }, new Item(Items.GOLD_BAR, 1), new Item(Items.RING_MOULD, 1), new Item(Items.ZENYTE))
Detailed Description
Holds the creation data.
Definition at line 17 of file ItemCreation.java.
Constructor & Destructor Documentation
CreationData() [1/2]
com.runehive.content.ItemCreation.CreationData.CreationData (Item product, Item dropped, Skill[] level, Item... required)
Constructs a new CreationData.
Definition at line 102 of file ItemCreation.java.
{
            this.product = new Item[]{product};
            this.dropped = dropped;
            this.level = level;
            this.required = required;
        }
References dropped, level, product, and required.
Referenced by forItem(), and forItems().
CreationData() [2/2]
com.runehive.content.ItemCreation.CreationData.CreationData (Item[] product, Item dropped, Skill[] level, Item... required)
Constructs a new CreationData.
Definition at line 110 of file ItemCreation.java.
{
            this.product = product;
            this.dropped = dropped;
            this.level = level;
            this.required = required;
        }
References dropped, level, product, and required.
Member Function Documentation
forItem()
Optional< CreationData > com.runehive.content.ItemCreation.CreationData.forItem (Item item) static
Finds the creation data based off the product item.
Definition at line 131 of file ItemCreation.java.
{
            for (CreationData data : CreationData.values()) {
                for (Item items : data.product) {
                    if (item.getId() == items.getId())
                        return Optional.of(data);
                }
            }
            return Optional.empty();
        }
References CreationData(), and com.runehive.game.world.items.Item.getId().
Referenced by com.runehive.content.ItemCreation.onDeath().
forItems()
Optional< CreationData > com.runehive.content.ItemCreation.CreationData.forItems (Item first, Item second) static
Handles finding the creation data based off the items used.
Definition at line 118 of file ItemCreation.java.
{
            for (CreationData data : CreationData.values()) {
                int found = 0;
                for (Item items : data.required) {
                    if (items.getId() == first.getId() || items.getId() == second.getId())
                        found++;
                }
                if (found >= 2) return Optional.of(data);
            }
            return Optional.empty();
        }
References CreationData(), and com.runehive.game.world.items.Item.getId().
Referenced by com.runehive.content.itemaction.impl.TridentOfTheSeas.itemOnItem().
Member Data Documentation
ABYSSAL_FROZEN_WHIP
com.runehive.content.ItemCreation.CreationData.ABYSSAL_FROZEN_WHIP =(new Item(12774), new Item(4151, 1), null, new Item(12769, 1), new Item(4151, 1))
Definition at line 52 of file ItemCreation.java.
ABYSSAL_TENTACLE_WHIP
com.runehive.content.ItemCreation.CreationData.ABYSSAL_TENTACLE_WHIP =(new Item(12006, 1), new Item(12004, 1), null, new Item(12004, 1), new Item(4151, 1))
Definition at line 50 of file ItemCreation.java.
ABYSSAL_VOLCANIC_WHIP
com.runehive.content.ItemCreation.CreationData.ABYSSAL_VOLCANIC_WHIP =(new Item(12773), new Item(4151, 1), null, new Item(12771, 1), new Item(4151, 1))
Definition at line 51 of file ItemCreation.java.
ARMADYL_GODSWORD
com.runehive.content.ItemCreation.CreationData.ARMADYL_GODSWORD =(new Item[]{new Item(11802)}, null, null, new Item(11798), new Item(11810))
Definition at line 28 of file ItemCreation.java.
ASSEMBLER_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.ASSEMBLER_MAX_CAPE =(new Item[]{new Item(21898), new Item(21900)}, null, null, new Item(22109), new Item(13280), new Item(13281))
Definition at line 82 of file ItemCreation.java.
AVA2_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.AVA2_MAX_CAPE =(new Item[]{new Item(13337), new Item(13338)}, null, null, new Item(10499), new Item(13280), new Item(13281))
Definition at line 81 of file ItemCreation.java.
BANDOS_GODSWORD
com.runehive.content.ItemCreation.CreationData.BANDOS_GODSWORD =(new Item[]{new Item(11804)}, null, null, new Item(11798), new Item(11812))
Definition at line 29 of file ItemCreation.java.
BLACK_SLAYER_HELM
com.runehive.content.ItemCreation.CreationData.BLACK_SLAYER_HELM =(new Item[]{new Item(19639)}, null, null, new Item(11864), new Item(7980))
Definition at line 20 of file ItemCreation.java.
BLACK_SLAYER_HELM_I
com.runehive.content.ItemCreation.CreationData.BLACK_SLAYER_HELM_I =(new Item[]{new Item(19641)}, null, null, new Item(11865), new Item(7980))
Definition at line 21 of file ItemCreation.java.
BLESSED_SPIRIT_SHIELD
com.runehive.content.ItemCreation.CreationData.BLESSED_SPIRIT_SHIELD =(new Item(12831), null, null, new Item(12829), new Item(12833))
Definition at line 38 of file ItemCreation.java.
BLUE_DARKBOW
com.runehive.content.ItemCreation.CreationData.BLUE_DARKBOW =(new Item(12766), new Item(11235, 1), null, new Item(12757, 1), new Item(11235, 1))
Definition at line 53 of file ItemCreation.java.
CAP_AND_GOGGLES
com.runehive.content.ItemCreation.CreationData.CAP_AND_GOGGLES =(new Item(9946), null, null, new Item(9945, 1), new Item(9472, 1))
Definition at line 60 of file ItemCreation.java.
DRAGON_FIRE_SHIELD
com.runehive.content.ItemCreation.CreationData.DRAGON_FIRE_SHIELD =(new Item(11283), null, null, new Item(11286,1), new Item(1540,1))
Definition at line 62 of file ItemCreation.java.
DRAGON_PICKAXE
com.runehive.content.ItemCreation.CreationData.DRAGON_PICKAXE =(new Item(12797), null, null, new Item(11920, 1), new Item(12800, 1))
Definition at line 48 of file ItemCreation.java.
dropped
final Item com.runehive.content.ItemCreation.CreationData.dropped
The dropped item.
Definition at line 93 of file ItemCreation.java.
Referenced by CreationData(), and CreationData().
ETERNAL_BOOTS
com.runehive.content.ItemCreation.CreationData.ETERNAL_BOOTS =(new Item[]{new Item(13235)}, null, new Skill[] { new Skill(Skill.RUNECRAFTING, 60,0), new Skill(Skill.MAGIC, 60, 0) }, new Item(6920), new Item(13227))
Definition at line 33 of file ItemCreation.java.
FIRE_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.FIRE_MAX_CAPE =(new Item[]{new Item(13329), new Item(13330)}, null, null, new Item(6570), new Item(13280), new Item(13281))
Max Capes.
Definition at line 77 of file ItemCreation.java.
FURY_AMULET_KIT
com.runehive.content.ItemCreation.CreationData.FURY_AMULET_KIT =(new Item(12436), null, null, new Item(6585, 1), new Item(12526, 1))
Definition at line 59 of file ItemCreation.java.
GODSWORD_BLADE
com.runehive.content.ItemCreation.CreationData.GODSWORD_BLADE =(new Item[]{new Item(11798)}, null, new Skill[] { new Skill(Skill.SMITHING, 80,0) }, new Item(11822), new Item(11794))
Definition at line 42 of file ItemCreation.java.
GODSWORD_BLADE_I
com.runehive.content.ItemCreation.CreationData.GODSWORD_BLADE_I =(new Item[]{new Item(11798)}, null, new Skill[] { new Skill(Skill.SMITHING, 80,0) }, new Item(11818), new Item(11800))
Definition at line 43 of file ItemCreation.java.
GODSWORD_BLADE_II
com.runehive.content.ItemCreation.CreationData.GODSWORD_BLADE_II =(new Item[]{new Item(11798)}, null, new Skill[] { new Skill(Skill.SMITHING, 80,0) }, new Item(11820), new Item(11796))
Definition at line 44 of file ItemCreation.java.
GODSWORD_SHARDS_1_AND_2
com.runehive.content.ItemCreation.CreationData.GODSWORD_SHARDS_1_AND_2 =(new Item[]{new Item(11794)}, null, null, new Item(11818), new Item(11820))
Definition at line 39 of file ItemCreation.java.
GODSWORD_SHARDS_1_AND_3
com.runehive.content.ItemCreation.CreationData.GODSWORD_SHARDS_1_AND_3 =(new Item[]{new Item(11796)}, null, null, new Item(11818), new Item(11822))
Definition at line 41 of file ItemCreation.java.
GODSWORD_SHARDS_2_AND_3
com.runehive.content.ItemCreation.CreationData.GODSWORD_SHARDS_2_AND_3 =(new Item[]{new Item(11800)}, null, null, new Item(11822), new Item(11820))
Definition at line 40 of file ItemCreation.java.
GOLDEN_PROS_BOOTS
com.runehive.content.ItemCreation.CreationData.GOLDEN_PROS_BOOTS =(new Item(25555), null, null, new Item(25547, 1), new Item(12016, 1))
Definition at line 67 of file ItemCreation.java.
GOLDEN_PROS_HELM
com.runehive.content.ItemCreation.CreationData.GOLDEN_PROS_HELM =(new Item(25549), null, null, new Item(25547, 1), new Item(12013, 1))
Definition at line 64 of file ItemCreation.java.
GOLDEN_PROS_JACKET
com.runehive.content.ItemCreation.CreationData.GOLDEN_PROS_JACKET =(new Item(25551), null, null, new Item(25547, 1), new Item(12014, 1))
Definition at line 65 of file ItemCreation.java.
GOLDEN_PROS_LEGS
com.runehive.content.ItemCreation.CreationData.GOLDEN_PROS_LEGS =(new Item(25553), null, null, new Item(25547, 1), new Item(12015, 1))
Definition at line 66 of file ItemCreation.java.
GREEN_DARKBOW
com.runehive.content.ItemCreation.CreationData.GREEN_DARKBOW =(new Item(12765), new Item(11235, 1), null, new Item(12759, 1), new Item(11235, 1))
Definition at line 55 of file ItemCreation.java.
GREEN_SLAYER_HELM
com.runehive.content.ItemCreation.CreationData.GREEN_SLAYER_HELM =(new Item[]{new Item(19643)}, null, null, new Item(11864), new Item(7981))
Definition at line 22 of file ItemCreation.java.
GREEN_SLAYER_HELMI
com.runehive.content.ItemCreation.CreationData.GREEN_SLAYER_HELMI =(new Item[]{new Item(19645)}, null, null, new Item(11865), new Item(7981))
Definition at line 23 of file ItemCreation.java.
GUTHIX_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.GUTHIX_MAX_CAPE =(new Item[]{new Item(13335), new Item(13336)}, null, null, new Item(10448), new Item(13280), new Item(13281))
Definition at line 80 of file ItemCreation.java.
IMBUED_GUTHIX_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.IMBUED_GUTHIX_MAX_CAPE =(new Item[]{new Item(21784), new Item(21786)}, null, null, new Item(21793), new Item(13280), new Item(13281))
Definition at line 86 of file ItemCreation.java.
IMBUED_SARADOMIN_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.IMBUED_SARADOMIN_MAX_CAPE =(new Item[]{new Item(21776), new Item(21778)}, null, null, new Item(21791), new Item(13280), new Item(13281))
Definition at line 84 of file ItemCreation.java.
IMBUED_ZAMORAK_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.IMBUED_ZAMORAK_MAX_CAPE =(new Item[]{new Item(21780), new Item(21782)}, null, null, new Item(21795), new Item(13280), new Item(13281))
Definition at line 85 of file ItemCreation.java.
INFERNAL_AXE
com.runehive.content.ItemCreation.CreationData.INFERNAL_AXE =(new Item[]{new Item(13241)}, null, new Skill[] { new Skill(Skill.WOODCUTTING, 61,0), new Skill(Skill.FIREMAKING, 85, 0) }, new Item(6739), new Item(13233))
Definition at line 35 of file ItemCreation.java.
INFERNAL_HARPOON
com.runehive.content.ItemCreation.CreationData.INFERNAL_HARPOON =(new Item[]{new Item(21031)}, null, new Skill[] { new Skill(Skill.COOKING, 85,0) }, new Item(21028), new Item(13233))
Definition at line 37 of file ItemCreation.java.
INFERNAL_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.INFERNAL_MAX_CAPE =(new Item[]{new Item(21284), new Item(21282)}, null, null, new Item(21295), new Item(13280), new Item(13281))
Definition at line 83 of file ItemCreation.java.
INFERNAL_PICKAXE
com.runehive.content.ItemCreation.CreationData.INFERNAL_PICKAXE =(new Item[]{new Item(13243)}, null, new Skill[] { new Skill(Skill.SMITHING, 85,0) }, new Item(11920), new Item(13233))
Definition at line 36 of file ItemCreation.java.
level
final Skill [] com.runehive.content.ItemCreation.CreationData.level
The skill required.
Definition at line 96 of file ItemCreation.java.
Referenced by CreationData(), and CreationData().
MAGIC_SHORTBOW_INFUSED
com.runehive.content.ItemCreation.CreationData.MAGIC_SHORTBOW_INFUSED =(new Item(12788), new Item(861), null, new Item(12786, 1), new Item(861, 1))
Definition at line 49 of file ItemCreation.java.
PEGASIAN_BOOTS
com.runehive.content.ItemCreation.CreationData.PEGASIAN_BOOTS =(new Item[]{new Item(13237)}, null, new Skill[] { new Skill(Skill.RUNECRAFTING, 60,0), new Skill(Skill.MAGIC, 60, 0) }, new Item(2577), new Item(13229))
Definition at line 34 of file ItemCreation.java.
PRIMORDIAL_BOOTS
com.runehive.content.ItemCreation.CreationData.PRIMORDIAL_BOOTS =(new Item[]{new Item(13239)}, null, new Skill[] { new Skill(Skill.RUNECRAFTING, 60,0), new Skill(Skill.MAGIC, 60, 0) }, new Item(11840), new Item(13231))
Definition at line 32 of file ItemCreation.java.
product
final Item [] com.runehive.content.ItemCreation.CreationData.product
The product of the creation.
Definition at line 90 of file ItemCreation.java.
Referenced by CreationData(), and CreationData().
PURPLE_SLAYER_HELM
com.runehive.content.ItemCreation.CreationData.PURPLE_SLAYER_HELM =(new Item[]{new Item(21264)}, null, null, new Item(11864), new Item(21275))
Definition at line 26 of file ItemCreation.java.
PURPLE_SLAYER_HELMI
com.runehive.content.ItemCreation.CreationData.PURPLE_SLAYER_HELMI =(new Item[]{new Item(21266)}, null, null, new Item(11865), new Item(21275))
Definition at line 27 of file ItemCreation.java.
RED_SLAYER_HELM
com.runehive.content.ItemCreation.CreationData.RED_SLAYER_HELM =(new Item[]{new Item(19647)}, null, null, new Item(11864), new Item(7979))
Definition at line 24 of file ItemCreation.java.
RED_SLAYER_HELMI
com.runehive.content.ItemCreation.CreationData.RED_SLAYER_HELMI =(new Item[]{new Item(19649)}, null, null, new Item(11865), new Item(7979))
Definition at line 25 of file ItemCreation.java.
required
final Item [] com.runehive.content.ItemCreation.CreationData.required
The items required.
Definition at line 99 of file ItemCreation.java.
Referenced by CreationData(), and CreationData().
RING_OF_WEALTH_I
com.runehive.content.ItemCreation.CreationData.RING_OF_WEALTH_I =(new Item(12785), null, null, new Item(12783, 1), new Item(2572, 1))
Definition at line 61 of file ItemCreation.java.
SARADOMIN_GODSWORD
com.runehive.content.ItemCreation.CreationData.SARADOMIN_GODSWORD =(new Item[]{new Item(11806)}, null, null, new Item(11798), new Item(11814))
Definition at line 30 of file ItemCreation.java.
SARADOMIN_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.SARADOMIN_MAX_CAPE =(new Item[]{new Item(13331), new Item(13332)}, null, null, new Item(10446), new Item(13280), new Item(13281))
Definition at line 78 of file ItemCreation.java.
SERPENTINE_VISAGE
com.runehive.content.ItemCreation.CreationData.SERPENTINE_VISAGE =(new Item(12929), new Item(12927, 1), null, new Item(12927, 1), new Item(1755, 1))
Definition at line 58 of file ItemCreation.java.
SLAYER_HELM
com.runehive.content.ItemCreation.CreationData.SLAYER_HELM =(new Item[]{new Item(11864)}, null, new Skill[]{new Skill(Skill.CRAFTING, 55, 0)}, new Item(8921), new Item(4166), new Item(4168), new Item(4164), new Item(4551), new Item(4155))
Definition at line 18 of file ItemCreation.java.
SLAYER_HELM_I
com.runehive.content.ItemCreation.CreationData.SLAYER_HELM_I =(new Item[]{new Item(11864)}, null, new Skill[]{new Skill(Skill.CRAFTING, 55, 0)}, new Item(8901), new Item(4166), new Item(4168), new Item(4164), new Item(4551), new Item(4155))
Definition at line 19 of file ItemCreation.java.
TOXIC_BLOWPIPE
com.runehive.content.ItemCreation.CreationData.TOXIC_BLOWPIPE =(new Item(12924), null, new Skill[] { new Skill(Skill.FLETCHING, 53, 0)}, new Item(12922, 1), new Item(1755, 1))
Definition at line 45 of file ItemCreation.java.
TOXIC_STAFF_OF_THE_DEAD
com.runehive.content.ItemCreation.CreationData.TOXIC_STAFF_OF_THE_DEAD =(new Item(12904), null, new Skill[]{new Skill(Skill.CRAFTING, 59, 0)}, new Item(11791, 1), new Item(12932, 1))
Definition at line 46 of file ItemCreation.java.
TRIDENT_OF_THE_SWAMP
com.runehive.content.ItemCreation.CreationData.TRIDENT_OF_THE_SWAMP =(new Item(12899), null, new Skill[]{new Skill(Skill.CRAFTING, 59, 0)}, new Item(12932, 1), new Item(11907, 1))
Definition at line 47 of file ItemCreation.java.
WHITE_DARKBOW
com.runehive.content.ItemCreation.CreationData.WHITE_DARKBOW =(new Item(12768), new Item(11235, 1), null, new Item(12763, 1), new Item(11235, 1))
Definition at line 56 of file ItemCreation.java.
YELLOW_DARKBOW
com.runehive.content.ItemCreation.CreationData.YELLOW_DARKBOW =(new Item(12767), new Item(11235, 1), null, new Item(12761, 1), new Item(11235, 1))
Definition at line 54 of file ItemCreation.java.
ZAMORAK_GODSWORD
com.runehive.content.ItemCreation.CreationData.ZAMORAK_GODSWORD =(new Item[]{new Item(11808)}, null, null, new Item(11798), new Item(11816))
Definition at line 31 of file ItemCreation.java.
ZAMORAK_MAX_CAPE
com.runehive.content.ItemCreation.CreationData.ZAMORAK_MAX_CAPE =(new Item[]{new Item(13333), new Item(13334)}, null, null, new Item(10450), new Item(13280), new Item(13281))
Definition at line 79 of file ItemCreation.java.
ZENYTE_AMULET
com.runehive.content.ItemCreation.CreationData.ZENYTE_AMULET =(new Item(19541), null,new Skill[] { new Skill(Skill.CRAFTING, 98,200) }, new Item(Items.GOLD_BAR, 1), new Item(Items.AMULET_MOULD, 1), new Item(Items.ZENYTE))
Definition at line 68 of file ItemCreation.java.
ZENYTE_BRACELET
com.runehive.content.ItemCreation.CreationData.ZENYTE_BRACELET =(new Item(19492), null,new Skill[] { new Skill(Skill.CRAFTING, 95,180) }, new Item(Items.GOLD_BAR, 1), new Item(Items.BRACELET_MOULD, 1), new Item(Items.ZENYTE))
Definition at line 75 of file ItemCreation.java.
ZENYTE_NECKLACE
com.runehive.content.ItemCreation.CreationData.ZENYTE_NECKLACE =(new Item(19535), null,new Skill[] { new Skill(Skill.CRAFTING, 92,165) }, new Item(Items.GOLD_BAR, 1), new Item(Items.NECKLACE_MOULD, 1), new Item(Items.ZENYTE))
Definition at line 70 of file ItemCreation.java.
ZENYTE_RING
com.runehive.content.ItemCreation.CreationData.ZENYTE_RING =(new Item(19538), null,new Skill[] { new Skill(Skill.CRAFTING, 89,150) }, new Item(Items.GOLD_BAR, 1), new Item(Items.RING_MOULD, 1), new Item(Items.ZENYTE))
Definition at line 72 of file ItemCreation.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/ItemCreation.java