RuneHive-Game: com.runehive.game.world.entity.mob.Direction Enum Reference
com.runehive.game.world.entity.mob.Direction Enum Reference
Represents the enumerated directions an entity can walk or face.
Public Member Functions
Direction (int directionX, int directionY)
int getDirectionX ()
int getDirectionY ()
Position getFaceLocation ()
int getManhattanOrientation ()
Static Public Member Functions
static int direction (int dx, int dy)
static Direction getDirection (int deltaX, int deltaY)
Gets the direction between two locations.
static Direction getDirection (Position position, Position other)
Gets the direction between two locations.
static int getDoorOrientation (Direction direction)
Gets the orientation for door.
static Direction getFollowDirection (Position source, Position target)
static Direction getManhattanDirection (Position position, Position other)
Gets the direction between two locations, ignoring corners.
static Direction getOppositeDirection (Direction direction)
static Direction getRandomDirection ()
static Direction ofManhattan (int orientation)
Gets the Manhattan direction of an orientation.
static Direction[] valid ()
Public Attributes
EAST =(1, 0)
NONE =(0, 0)
NORTH =(0, 1)
NORTH_EAST =(1, 1)
NORTH_WEST =(-1, 1)
SOUTH =(0, -1)
SOUTH_EAST =(1, -1)
SOUTH_WEST =(-1, -1)
WEST =(-1, 0)
Static Public Attributes
static final byte[] DELTA_X = new byte[]{-1, 0, 1, -1, 1, -1, 0, 1}
Difference in X coordinates for directions array.
static final byte[] DELTA_Y = new byte[]{1, 1, 1, 0, 0, -1, -1, -1}
Difference in Y coordinates for directions array.
static final ImmutableList< Direction > DIRECTIONS = ImmutableList.of(NORTH_WEST, NORTH, NORTH_EAST, WEST, EAST, SOUTH_WEST, SOUTH, SOUTH_EAST)
Private Attributes
final int directionX
final int directionY
final Position faceLocation
Static Private Attributes
static final Direction[] VALID = new Direction[]{NORTH, NORTH_EAST, EAST, SOUTH_EAST, SOUTH, SOUTH_WEST, WEST, NORTH_WEST}
Detailed Description
Represents the enumerated directions an entity can walk or face.
Author
SeVen
Definition at line 12 of file Direction.java.
Constructor & Destructor Documentation
Direction()
com.runehive.game.world.entity.mob.Direction.Direction (int directionX, int directionY)
Definition at line 26 of file Direction.java.
{
        this.directionX = directionX;
        this.directionY = directionY;
        this.faceLocation = new Position(directionX, directionY);
    }
References directionX, and directionY.
Referenced by getDirection(), getDirection(), getDoorOrientation(), getFollowDirection(), getManhattanDirection(), getOppositeDirection(), getRandomDirection(), ofManhattan(), and valid().
Member Function Documentation
direction()
int com.runehive.game.world.entity.mob.Direction.direction (int dx, int dy) static
Definition at line 280 of file Direction.java.
{
        if (dx < 0) {
            if (dy < 0) {
                return 5;
            } else if (dy > 0) {
                return 0;
            } else {
                return 3;
            }
        } else if (dx > 0) {
            if (dy < 0) {
                return 7;
            } else if (dy > 0) {
                return 2;
            } else {
                return 4;
            }
        } else {
            if (dy < 0) {
                return 6;
            } else if (dy > 0) {
                return 1;
            } else {
                return -1;
            }
        }
    }
Referenced by com.runehive.game.world.entity.mob.movement.Movement.addStepInternal(), getDoorOrientation(), and getOppositeDirection().
getDirection() [1/2]
Direction com.runehive.game.world.entity.mob.Direction.getDirection (int deltaX, int deltaY) static
Gets the direction between two locations.
Returns
The direction of the other position.
Definition at line 55 of file Direction.java.
{
        if (deltaY >= 1) {
            if (deltaX >= 1) {
                return NORTH_EAST;
            } else if (deltaX == 0) {
                return NORTH;
            } else if (deltaX <= -1) {
                return NORTH_WEST;
            }
        } else if (deltaY == 0) {
            if (deltaX >= 1) {
                return EAST;
            } else if (deltaX == 0) {
                return NONE;
            } else if (deltaX <= -1) {
                return WEST;
            }
        } else if (deltaY <= -1) {
            if (deltaX >= 1) {
                return SOUTH_EAST;
            } else if (deltaX == 0) {
                return SOUTH;
            } else if (deltaX <= -1) {
                return SOUTH_WEST;
            }
        }
        return Direction.NONE;
    }
References Direction(), EAST, NONE, NORTH, NORTH_EAST, NORTH_WEST, SOUTH, SOUTH_EAST, SOUTH_WEST, and WEST.
Referenced by com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.canAttack(), com.runehive.game.task.impl.ChopVineTask.execute(), com.runehive.util.Utility.findAccessableTile(), com.runehive.util.Utility.findBestInside(), com.runehive.util.Utility.fixInsidePosition(), getFollowDirection(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), com.runehive.game.world.pathfinding.path.PathFinder.projectileCheck(), and com.runehive.game.world.pathfinding.path.PathFinder.traversable().
getDirection() [2/2]
Direction com.runehive.game.world.entity.mob.Direction.getDirection (Position position, Position other) static
Gets the direction between two locations.
Parameters
position The position that will be the viewpoint.
other The other position to get the direction of.
Returns
The direction of the other position.
Definition at line 93 of file Direction.java.
{
        final int deltaX = other.getX() - position.getX();
        final int deltaY = other.getY() - position.getY();
        if (deltaY >= 1) {
            if (deltaX >= 1) {
                return NORTH_EAST;
            } else if (deltaX == 0) {
                return NORTH;
            } else if (deltaX <= -1) {
                return NORTH_WEST;
            }
        } else if (deltaY == 0) {
            if (deltaX >= 1) {
                return EAST;
            } else if (deltaX == 0) {
                return NONE;
            } else if (deltaX <= -1) {
                return WEST;
            }
        } else if (deltaY <= -1) {
            if (deltaX >= 1) {
                return SOUTH_EAST;
            } else if (deltaX == 0) {
                return SOUTH;
            } else if (deltaX <= -1) {
                return SOUTH_WEST;
            }
        }
        return Direction.NONE;
    }
References Direction(), EAST, com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), NONE, NORTH, NORTH_EAST, NORTH_WEST, SOUTH, SOUTH_EAST, SOUTH_WEST, and WEST.
getDirectionX()
int com.runehive.game.world.entity.mob.Direction.getDirectionX ()
Definition at line 308 of file Direction.java.
{
        return directionX;
    }
References directionX.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFaceCoordinateMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceCoordinteMask(), com.runehive.game.task.impl.ChopVineTask.execute(), and com.runehive.util.Utility.findBestInside().
getDirectionY()
int com.runehive.game.world.entity.mob.Direction.getDirectionY ()
Definition at line 311 of file Direction.java.
{
        return directionY;
    }
References directionY.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFaceCoordinateMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendFaceCoordinteMask(), com.runehive.game.task.impl.ChopVineTask.execute(), and com.runehive.util.Utility.findBestInside().
getDoorOrientation()
int com.runehive.game.world.entity.mob.Direction.getDoorOrientation (Direction direction) static
Gets the orientation for door.
Parameters
direction The direction of this object.
Returns
The orientation.
Definition at line 220 of file Direction.java.
{
        switch (direction) {
            case WEST:
                return 0;
            case NORTH:
                return 1;
            case EAST:
                return 2;
            case SOUTH:
                return 3;
            default:
                return 3;
        }
    }
References Direction(), direction(), EAST, NORTH, SOUTH, and WEST.
getFaceLocation()
Position com.runehive.game.world.entity.mob.Direction.getFaceLocation ()
Definition at line 36 of file Direction.java.
{
        return faceLocation;
    }
References faceLocation.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.util.Utility.fixInsidePosition(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonSpear.hit(), and com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.traversable().
getFollowDirection()
Direction com.runehive.game.world.entity.mob.Direction.getFollowDirection (Position source, Position target) static
Definition at line 192 of file Direction.java.
{
        Direction dir = getDirection(source, target);
        int deltaX = Math.abs(source.getX() - target.getX());
        int deltaY = Math.abs(source.getY() - target.getY());
        boolean vertical = deltaY > deltaX;
        switch (dir) {
            case NORTH_EAST:
                if (vertical) return NORTH;
                else return EAST;
            case NORTH_WEST:
                if (vertical) return NORTH;
                else return WEST;
            case SOUTH_EAST:
                if (vertical) return SOUTH;
                else return EAST;
            case SOUTH_WEST:
                if (vertical) return SOUTH;
                else return WEST;
            default: return dir;
        }
    }
References Direction(), EAST, getDirection(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), NORTH, NORTH_EAST, NORTH_WEST, SOUTH, SOUTH_EAST, SOUTH_WEST, and WEST.
Referenced by com.runehive.content.skill.impl.agility.obstacle.impl.ClimbOverInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.RopeSwingInteraction.onExecution(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start().
getManhattanDirection()
Direction com.runehive.game.world.entity.mob.Direction.getManhattanDirection (Position position, Position other) static
Gets the direction between two locations, ignoring corners.
Parameters
position The position that will be the viewpoint.
other The other position to get the direction of.
Returns
The direction of the other position.
Definition at line 145 of file Direction.java.
{
        final int deltaX = other.getX() - position.getX();
        final int deltaY = other.getY() - position.getY();
        if (deltaY >= 1) {
            if (deltaX == 0) {
                return NORTH;
            }
        } else if (deltaY == 0) {
            if (deltaX >= 1) {
                return Direction.EAST;
            } else if (deltaX == 0) {
                return Direction.SOUTH;
            } else if (deltaX <= -1) {
                return Direction.WEST;
            }
        } else if (deltaY <= -1) {
            if (deltaX == 0) {
                return SOUTH;
            }
        }
        return Direction.SOUTH;
    }
References Direction(), com.runehive.game.world.position.Position.getX(), com.runehive.game.world.position.Position.getY(), NORTH, and SOUTH.
getManhattanOrientation()
int com.runehive.game.world.entity.mob.Direction.getManhattanOrientation ()
Definition at line 257 of file Direction.java.
{
        switch (this) {
            case NORTH_WEST:
                return 0;
            case NORTH:
                return 1;
            case NORTH_EAST:
                return 2;
            case WEST:
                return 3;
            case EAST:
                return 4;
            case SOUTH_WEST:
                return 5;
            case SOUTH:
                return 6;
            case SOUTH_EAST:
                return 7;
            default:
                return -1;
        }
    }
References EAST, NORTH, NORTH_EAST, NORTH_WEST, SOUTH, SOUTH_EAST, SOUTH_WEST, and WEST.
getOppositeDirection()
Direction com.runehive.game.world.entity.mob.Direction.getOppositeDirection (Direction direction) static
Definition at line 169 of file Direction.java.
{
        switch (direction) {
            case EAST:
                return WEST;
            case NORTH:
                return SOUTH;
            case NORTH_EAST:
                return SOUTH_WEST;
            case NORTH_WEST:
                return SOUTH_EAST;
            case SOUTH:
                return NORTH;
            case SOUTH_EAST:
                return NORTH_WEST;
            case SOUTH_WEST:
                return NORTH_EAST;
            case WEST:
                return EAST;
            default:
                return NONE;
        }
    }
References Direction(), direction(), EAST, NONE, NORTH, NORTH_EAST, NORTH_WEST, SOUTH, SOUTH_EAST, SOUTH_WEST, and WEST.
Referenced by com.runehive.game.action.impl.DoorAction.execute(), com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Callisto.Roar.start().
getRandomDirection()
Direction com.runehive.game.world.entity.mob.Direction.getRandomDirection () static
Definition at line 127 of file Direction.java.
{
        int random = Utility.random(4);
        switch (random) {
            case 1: return NORTH;
            case 2: return EAST;
            case 3: return SOUTH;
            case 4: return WEST;
            default: return SOUTH;
        }
    }
References Direction(), EAST, NORTH, com.runehive.util.Utility.random(), SOUTH, and WEST.
ofManhattan()
Direction com.runehive.game.world.entity.mob.Direction.ofManhattan (int orientation) static
Gets the Manhattan direction of an orientation.
Manhattan direction does not support diagnal directions, so the orientation must be between [0, 3] inclusive.
Parameters
orientation
Returns
Definition at line 243 of file Direction.java.
{
        switch (orientation) {
            case 0:
                return EAST;
            case 1:
                return SOUTH;
            case 2:
                return WEST;
            case 3:
                return NORTH;
        }
        return NONE;
    }
References Direction(), EAST, NONE, NORTH, SOUTH, and WEST.
valid()
Direction[] com.runehive.game.world.entity.mob.Direction.valid () static
Definition at line 315 of file Direction.java.
{
        return VALID;
    }
References Direction(), and VALID.
Referenced by com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find().
Member Data Documentation
DELTA_X
final byte [] com.runehive.game.world.entity.mob.Direction.DELTA_X = new byte[]{-1, 0, 1, -1, 1, -1, 0, 1} static
Difference in X coordinates for directions array.
Definition at line 43 of file Direction.java.
{-1, 0, 1, -1, 1, -1, 0, 1};
Referenced by com.runehive.game.world.entity.mob.movement.Movement.getNextPoint().
DELTA_Y
final byte [] com.runehive.game.world.entity.mob.Direction.DELTA_Y = new byte[]{1, 1, 1, 0, 0, -1, -1, -1} static
Difference in Y coordinates for directions array.
Definition at line 48 of file Direction.java.
{1, 1, 1, 0, 0, -1, -1, -1};
Referenced by com.runehive.game.world.entity.mob.movement.Movement.getNextPoint().
DIRECTIONS
final ImmutableList<Direction> com.runehive.game.world.entity.mob.Direction.DIRECTIONS = ImmutableList.of(NORTH_WEST, NORTH, NORTH_EAST, WEST, EAST, SOUTH_WEST, SOUTH, SOUTH_EAST) static
Definition at line 33 of file Direction.java.
Referenced by com.runehive.game.world.entity.mob.movement.Movement.processNextMovement().
directionX
final int com.runehive.game.world.entity.mob.Direction.directionX private
Definition at line 23 of file Direction.java.
Referenced by Direction(), and getDirectionX().
directionY
final int com.runehive.game.world.entity.mob.Direction.directionY private
Definition at line 24 of file Direction.java.
Referenced by Direction(), and getDirectionY().
EAST
com.runehive.game.world.entity.mob.Direction.EAST =(1, 0)
Definition at line 15 of file Direction.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), getDirection(), getDirection(), getDoorOrientation(), getFollowDirection(), getManhattanOrientation(), getOppositeDirection(), getRandomDirection(), ofManhattan(), com.runehive.game.action.impl.RevShortcutAction.RevShortcutAction(), com.runehive.game.action.impl.TutorialActivity.start(), and com.runehive.game.world.entity.mob.Mob.takeStep().
faceLocation
final Position com.runehive.game.world.entity.mob.Direction.faceLocation private
Definition at line 25 of file Direction.java.
Referenced by getFaceLocation().
NONE
com.runehive.game.world.entity.mob.Direction.NONE =(0, 0)
Definition at line 21 of file Direction.java.
Referenced by com.runehive.util.Utility.fixInsidePosition(), getDirection(), getDirection(), getOppositeDirection(), and ofManhattan().
NORTH
com.runehive.game.world.entity.mob.Direction.NORTH =(0, 1)
Definition at line 13 of file Direction.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), com.runehive.content.bot.objective.impl.WildernessDitchObjective.finish(), com.runehive.game.world.entity.mob.Mob.forceMove(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.DerwenUtility.generatederwenSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.PorazdirUtility.generatePorazdirSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.magearena.JusticarUtility.generateSpawn(), com.runehive.game.world.entity.combat.strategy.npc.boss.skotizo.SkotizoUtility.generateSpawn(), com.runehive.content.activity.impl.magearena.MageArena.getAvailablePosition(), getDirection(), getDirection(), getDoorOrientation(), getFollowDirection(), getManhattanDirection(), getManhattanOrientation(), getOppositeDirection(), getRandomDirection(), ofManhattan(), com.runehive.game.action.impl.RevShortcutAction.RevShortcutAction(), com.runehive.content.skill.SkillRepository.spawn(), com.runehive.game.action.impl.TutorialActivity.start(), and com.runehive.game.world.entity.mob.Mob.takeStep().
NORTH_EAST
com.runehive.game.world.entity.mob.Direction.NORTH_EAST =(1, 1)
Definition at line 14 of file Direction.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), getDirection(), getDirection(), getFollowDirection(), getManhattanOrientation(), getOppositeDirection(), and com.runehive.content.combat.cannon.CannonBuild.tick().
NORTH_WEST
com.runehive.game.world.entity.mob.Direction.NORTH_WEST =(-1, 1)
Definition at line 20 of file Direction.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), getDirection(), getDirection(), getFollowDirection(), getManhattanOrientation(), and getOppositeDirection().
SOUTH
com.runehive.game.world.entity.mob.Direction.SOUTH =(0, -1)
Definition at line 17 of file Direction.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), com.runehive.content.gambling.GambleManager.canPlayFlowerPokerAtPositon(), getDirection(), getDirection(), getDoorOrientation(), getFollowDirection(), getManhattanDirection(), getManhattanOrientation(), getOppositeDirection(), getRandomDirection(), com.runehive.game.world.entity.mob.npc.Npc.Npc(), com.runehive.game.world.entity.mob.npc.Npc.Npc(), ofManhattan(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction2.onExecution(), com.runehive.game.world.entity.mob.player.PlayerDeath.postDeath(), com.runehive.content.lms.LMSGame.reset(), com.runehive.game.action.impl.RevShortcutAction.RevShortcutAction(), com.runehive.game.action.impl.TutorialActivity.start(), and com.runehive.game.world.entity.mob.Mob.takeStep().
SOUTH_EAST
com.runehive.game.world.entity.mob.Direction.SOUTH_EAST =(1, -1)
Definition at line 16 of file Direction.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), getDirection(), getDirection(), getFollowDirection(), getManhattanOrientation(), and getOppositeDirection().
SOUTH_WEST
com.runehive.game.world.entity.mob.Direction.SOUTH_WEST =(-1, -1)
Definition at line 18 of file Direction.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), getDirection(), getDirection(), getFollowDirection(), getManhattanOrientation(), and getOppositeDirection().
VALID
final Direction [] com.runehive.game.world.entity.mob.Direction.VALID = new Direction[]{NORTH, NORTH_EAST, EAST, SOUTH_EAST, SOUTH, SOUTH_WEST, WEST, NORTH_WEST} static private
Definition at line 34 of file Direction.java.
{NORTH, NORTH_EAST, EAST, SOUTH_EAST, SOUTH, SOUTH_WEST, WEST, NORTH_WEST};
Referenced by valid().
WEST
com.runehive.game.world.entity.mob.Direction.WEST =(-1, 0)
Definition at line 19 of file Direction.java.
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), getDirection(), getDirection(), getDoorOrientation(), getFollowDirection(), getManhattanOrientation(), getOppositeDirection(), getRandomDirection(), ofManhattan(), com.runehive.content.skill.impl.agility.obstacle.impl.SteppingStonesInteraction.onExecution(), com.runehive.game.action.impl.RevShortcutAction.RevShortcutAction(), com.runehive.game.action.impl.TutorialActivity.start(), and com.runehive.game.world.entity.mob.Mob.takeStep().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/mob/Direction.java