RuneHive-Game: com.runehive.content.skill.impl.herblore.FinishedPotion Enum Reference
com.runehive.content.skill.impl.herblore.FinishedPotion Enum Reference
Holds all the finished potion data.
Public Member Functions
FinishedPotion (int product, int unfinishedPotion, int ingredient, int level, double experience)
Constructs a new FinishedPotion.
int getAnimation ()
Gets the potion animation.
double getExperience ()
Gets the experience rewarded.
Item[] getIngredients ()
Gets the ingredients required for the potion.
int getLevel ()
Gets the level required for making the potion.
Item getProduct ()
Gets the potion product.
String toString ()
Static Public Member Functions
static FinishedPotion get (Item use, Item with)
Gets the finished potion data.
Public Attributes
AGILITY_POTION =(3034, 3002, 2152, 34, 80)
ANTIFIRE =(2454, 2483, 241, 69, 157.5)
ANTIPOISON =(175, 93, 235, 5, 37.5)
ATTACK_POTION =(121, 91, 221, 1, 25)
COMBAT_POTION =(9741, 97, 9736, 36, 84)
DEFENCE_POTION =(133, 99, 239, 30, 75)
ENERGY_POTION =(3010, 97, 1975, 26, 67.5)
FISHING_POTION =(181, 101, 235, 48, 112.5)
MAGIC_POTION =(3042, 2483, 3138, 76, 172.5)
RANGING_POTION =(169, 109, 245, 72, 162.5)
RAYER_POTION =(139, 99, 231, 38, 87.5)
RESTORE_POTION =(127, 97, 223, 22, 62.5)
SARADOMIN_BREW =(6687, 3002, 6693, 81, 180)
STRENGTH_POTION =(115, 95, 225, 12, 50)
SUPER_ATTACK =(145, 101, 221, 45, 100)
SUPER_DEFENCE =(163, 107, 239, 66, 150)
SUPER_ENERGY =(3018, 103, 2970, 52, 117.5)
SUPER_RESTORE =(3026, 3004, 223, 63, 142.5)
SUPER_STRENGTH =(157, 105, 225, 55, 137.5)
VIAL_OF_STENCH =(18661, 101, 1871, 46, 0)
WEAPON_POISON =(187, 105, 241, 60, 138)
ZAMORAK_BREW =(189, 111, 247, 78, 175)
Private Attributes
final double experience
The experience rewarded for the potion.
final Item[] ingredients
The finished potion ingredients.
final int level
The level required to make the potion.
final int product
The finished potion product.
Detailed Description
Holds all the finished potion data.
Author
Daniel
Definition at line 12 of file FinishedPotion.java.
Constructor & Destructor Documentation
FinishedPotion()
com.runehive.content.skill.impl.herblore.FinishedPotion.FinishedPotion (int product, int unfinishedPotion, int ingredient, int level, double experience)
Constructs a new FinishedPotion.
Parameters
product The product item.
unfinishedPotion The unfinished potion item.
ingredient The ingredients needed for the potion.
level The level required.
experience The experience rewarded.
Definition at line 65 of file FinishedPotion.java.
{
        this.product = product;
        this.ingredients = new Item[]{new Item(unfinishedPotion), new Item(ingredient)};
        this.level = level;
        this.experience = experience;
    }
References experience, level, and product.
Referenced by get().
Member Function Documentation
get()
FinishedPotion com.runehive.content.skill.impl.herblore.FinishedPotion.get (Item use, Item with) static
Gets the finished potion data.
Parameters
use The item being used.
with The item being used with.
Returns
The finished potion data.
Definition at line 79 of file FinishedPotion.java.
{
        for (final FinishedPotion potion : values()) {
            if (potion.ingredients[0].equals(use) && potion.ingredients[1].equals(with) || potion.ingredients[1].equals(use) && potion.ingredients[0].equals(with)) {
                return potion;
            }
        }
        return null;
    }
References FinishedPotion().
Referenced by com.runehive.content.skill.impl.herblore.Herblore.useItem().
getAnimation()
int com.runehive.content.skill.impl.herblore.FinishedPotion.getAnimation ()
Gets the potion animation.
Returns
The potion animation.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 89 of file FinishedPotion.java.
{
        return 363;
    }
getExperience()
double com.runehive.content.skill.impl.herblore.FinishedPotion.getExperience ()
Gets the experience rewarded.
Returns
The experience rewarded.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 94 of file FinishedPotion.java.
{
        return experience;
    }
References experience.
getIngredients()
Item[] com.runehive.content.skill.impl.herblore.FinishedPotion.getIngredients ()
Gets the ingredients required for the potion.
Returns
The potion ingredients.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 99 of file FinishedPotion.java.
{
        return ingredients;
    }
References ingredients.
getLevel()
int com.runehive.content.skill.impl.herblore.FinishedPotion.getLevel ()
Gets the level required for making the potion.
Returns
The level required.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 104 of file FinishedPotion.java.
{
        return level;
    }
References level.
getProduct()
Item com.runehive.content.skill.impl.herblore.FinishedPotion.getProduct ()
Gets the potion product.
Returns
The potion product.
Implements com.runehive.content.skill.impl.herblore.Potion.
Definition at line 109 of file FinishedPotion.java.
{
        return new Item(product);
    }
References product.
Referenced by toString().
toString()
String com.runehive.content.skill.impl.herblore.FinishedPotion.toString ()
Definition at line 114 of file FinishedPotion.java.
{
        return "FinishedPotion[product: " + getProduct() + ", level: " + level + ", experience: " + experience + ", ingredients: " + Arrays.toString(ingredients) + "]";
    }
References experience, getProduct(), ingredients, and level.
Member Data Documentation
AGILITY_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.AGILITY_POTION =(3034, 3002, 2152, 34, 80)
Definition at line 19 of file FinishedPotion.java.
ANTIFIRE
com.runehive.content.skill.impl.herblore.FinishedPotion.ANTIFIRE =(2454, 2483, 241, 69, 157.5)
Definition at line 30 of file FinishedPotion.java.
ANTIPOISON
com.runehive.content.skill.impl.herblore.FinishedPotion.ANTIPOISON =(175, 93, 235, 5, 37.5)
Definition at line 14 of file FinishedPotion.java.
ATTACK_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.ATTACK_POTION =(121, 91, 221, 1, 25)
Definition at line 13 of file FinishedPotion.java.
COMBAT_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.COMBAT_POTION =(9741, 97, 9736, 36, 84)
Definition at line 20 of file FinishedPotion.java.
DEFENCE_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.DEFENCE_POTION =(133, 99, 239, 30, 75)
Definition at line 18 of file FinishedPotion.java.
ENERGY_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.ENERGY_POTION =(3010, 97, 1975, 26, 67.5)
Definition at line 17 of file FinishedPotion.java.
experience
final double com.runehive.content.skill.impl.herblore.FinishedPotion.experience private
The experience rewarded for the potion.
Definition at line 54 of file FinishedPotion.java.
Referenced by FinishedPotion(), getExperience(), and toString().
FISHING_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.FISHING_POTION =(181, 101, 235, 48, 112.5)
Definition at line 24 of file FinishedPotion.java.
ingredients
final Item [] com.runehive.content.skill.impl.herblore.FinishedPotion.ingredients private
The finished potion ingredients.
Definition at line 44 of file FinishedPotion.java.
Referenced by getIngredients(), and toString().
level
final int com.runehive.content.skill.impl.herblore.FinishedPotion.level private
The level required to make the potion.
Definition at line 49 of file FinishedPotion.java.
Referenced by FinishedPotion(), getLevel(), and toString().
MAGIC_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.MAGIC_POTION =(3042, 2483, 3138, 76, 172.5)
Definition at line 32 of file FinishedPotion.java.
product
final int com.runehive.content.skill.impl.herblore.FinishedPotion.product private
The finished potion product.
Definition at line 39 of file FinishedPotion.java.
Referenced by FinishedPotion(), and getProduct().
RANGING_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.RANGING_POTION =(169, 109, 245, 72, 162.5)
Definition at line 31 of file FinishedPotion.java.
RAYER_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.RAYER_POTION =(139, 99, 231, 38, 87.5)
Definition at line 21 of file FinishedPotion.java.
RESTORE_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.RESTORE_POTION =(127, 97, 223, 22, 62.5)
Definition at line 16 of file FinishedPotion.java.
SARADOMIN_BREW
com.runehive.content.skill.impl.herblore.FinishedPotion.SARADOMIN_BREW =(6687, 3002, 6693, 81, 180)
Definition at line 34 of file FinishedPotion.java.
STRENGTH_POTION
com.runehive.content.skill.impl.herblore.FinishedPotion.STRENGTH_POTION =(115, 95, 225, 12, 50)
Definition at line 15 of file FinishedPotion.java.
SUPER_ATTACK
com.runehive.content.skill.impl.herblore.FinishedPotion.SUPER_ATTACK =(145, 101, 221, 45, 100)
Definition at line 22 of file FinishedPotion.java.
SUPER_DEFENCE
com.runehive.content.skill.impl.herblore.FinishedPotion.SUPER_DEFENCE =(163, 107, 239, 66, 150)
Definition at line 29 of file FinishedPotion.java.
SUPER_ENERGY
com.runehive.content.skill.impl.herblore.FinishedPotion.SUPER_ENERGY =(3018, 103, 2970, 52, 117.5)
Definition at line 25 of file FinishedPotion.java.
SUPER_RESTORE
com.runehive.content.skill.impl.herblore.FinishedPotion.SUPER_RESTORE =(3026, 3004, 223, 63, 142.5)
Definition at line 28 of file FinishedPotion.java.
Referenced by com.runehive.content.skill.impl.herblore.Herblore.mix().
SUPER_STRENGTH
com.runehive.content.skill.impl.herblore.FinishedPotion.SUPER_STRENGTH =(157, 105, 225, 55, 137.5)
Definition at line 26 of file FinishedPotion.java.
VIAL_OF_STENCH
com.runehive.content.skill.impl.herblore.FinishedPotion.VIAL_OF_STENCH =(18661, 101, 1871, 46, 0)
Definition at line 23 of file FinishedPotion.java.
WEAPON_POISON
com.runehive.content.skill.impl.herblore.FinishedPotion.WEAPON_POISON =(187, 105, 241, 60, 138)
Definition at line 27 of file FinishedPotion.java.
ZAMORAK_BREW
com.runehive.content.skill.impl.herblore.FinishedPotion.ZAMORAK_BREW =(189, 111, 247, 78, 175)
Definition at line 33 of file FinishedPotion.java.
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/herblore/FinishedPotion.java