RuneHive-Game: com.runehive.game.world.entity.combat.hit.HitIcon Enum Reference
com.runehive.game.world.entity.combat.hit.HitIcon Enum Reference
The enumerated type whose elements represent the hit icon of a Hit.
Public Member Functions
final int getId ()
Gets the identification for this hit type.
HitIcon (int id)
Create a new HitIcon.
Public Attributes
CANON =(4)
Represents the canon hit icon.
DEFLECT =(3)
Represents the leech hit icon.
MAGIC =(2)
Represents the magic hat hit icon.
MELEE =(0)
Represents the melee sword hit icon.
NONE =(255)
Represents no hit icon at all.
RANGED =(1)
Represents the ranged bow hit icon.
Private Attributes
final int id
The identification for this hit type.
Detailed Description
The enumerated type whose elements represent the hit icon of a Hit.
Author
Artem Batutin artem.nosp@m.batu.nosp@m.tin@g.nosp@m.mail.nosp@m..com
Definition at line 8 of file HitIcon.java.
Constructor & Destructor Documentation
HitIcon()
com.runehive.game.world.entity.combat.hit.HitIcon.HitIcon (int id)
Create a new HitIcon.
Parameters
id the identification for this hit type.
Definition at line 36 of file HitIcon.java.
                    {
        this.id = id;
    }
References id.
Member Function Documentation
getId()
final int com.runehive.game.world.entity.combat.hit.HitIcon.getId ()
Gets the identification for this hit type.
Returns
the identification for this hit type.
Definition at line 45 of file HitIcon.java.
{
        return id;
    }
References id.
Referenced by com.runehive.net.packet.out.SendNpcUpdate.appendFirstHitMask(), com.runehive.net.packet.out.SendPlayerUpdate.appendHitMask(), com.runehive.net.packet.out.SendNpcUpdate.appendSecondHitMask(), and com.runehive.net.packet.out.SendPlayerUpdate.appendSecondHitMask().
Member Data Documentation
CANON
com.runehive.game.world.entity.combat.hit.HitIcon.CANON =(4)
Represents the canon hit icon.
Definition at line 26 of file HitIcon.java.
Referenced by com.runehive.content.combat.cannon.CannonFireAction.execute().
DEFLECT
com.runehive.game.world.entity.combat.hit.HitIcon.DEFLECT =(3)
Represents the leech hit icon.
Definition at line 23 of file HitIcon.java.
Referenced by com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.block(), com.runehive.game.world.entity.combat.attack.listener.item.RingOfRecoilListener.handleRecoil(), and com.runehive.game.world.entity.combat.attack.listener.other.VengeanceListener.preKill().
id
final int com.runehive.game.world.entity.combat.hit.HitIcon.id private
The identification for this hit type.
Definition at line 29 of file HitIcon.java.
Referenced by getId(), and HitIcon().
MAGIC
com.runehive.game.world.entity.combat.hit.HitIcon.MAGIC =(2)
Represents the magic hat hit icon.
Definition at line 20 of file HitIcon.java.
Referenced by com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.addCombatExperience(), com.runehive.game.world.entity.combat.strategy.npc.boss.armadyl.KreeArra.Magic.getHits(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMagicHit(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special().
MELEE
com.runehive.game.world.entity.combat.hit.HitIcon.MELEE =(0)
Represents the melee sword hit icon.
Definition at line 14 of file HitIcon.java.
Referenced by com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >.addCombatExperience(), com.runehive.game.world.entity.combat.strategy.player.special.melee.DragonClaws.fourthOption(), com.runehive.game.world.entity.combat.strategy.npc.boss.Vetion.Earthquake.hit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextMeleeHit(), com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special(), and com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.JumpAttack.start().
NONE
com.runehive.game.world.entity.combat.hit.HitIcon.NONE =(255)
Represents no hit icon at all.
Definition at line 11 of file HitIcon.java.
Referenced by com.runehive.game.world.entity.combat.CombatUtil.generateDragonfire(), com.runehive.game.world.entity.combat.strategy.npc.boss.LizardShaman.AcidAttack.getHits(), com.runehive.content.lms.LMSGame.handleFogDamage(), com.runehive.game.world.entity.combat.hit.Hit.Hit(), com.runehive.game.world.entity.combat.hit.Hit.Hit(), com.runehive.game.world.entity.combat.attack.listener.other.PrayerListener.preDeath(), com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.process(), and com.runehive.game.world.entity.combat.effect.impl.CombatVenomEffect.process().
RANGED
com.runehive.game.world.entity.combat.hit.HitIcon.RANGED =(1)
Represents the ranged bow hit icon.
Definition at line 17 of file HitIcon.java.
Referenced by com.runehive.game.world.entity.combat.ranged.RangedEffects.hitEvent(), com.runehive.game.world.entity.combat.attack.FormulaFactory.nextRangedHit(), and com.runehive.game.world.entity.combat.strategy.npc.boss.Cerberus.GhostAttack.special().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/hit/HitIcon.java