RuneHive-Game: com.runehive.content.skill.impl.fletching.impl.Arrow Enum Reference
com.runehive.content.skill.impl.fletching.impl.Arrow Enum Reference
Public Member Functions
Arrow (Item use, Item with, FletchableItem... items)
int getAnimation ()
FletchableItem[] getFletchableItems ()
int getGraphics ()
Item[] getIngredients ()
String getProductionMessage ()
Item getUse ()
Item getWith ()
Static Public Member Functions
static void load ()
Public Attributes
ADAMANT_ARROWS =(new Item(53, 15), new Item(43, 15), new FletchableItem(new Item(890, 15), 60, 150.0))
AMETHYST_ARROWS =(new Item(53, 15), new Item(Items.AMETHYST_ARROWTIPS, 15), new FletchableItem(new Item(Items.AMETHYST_ARROW, 15), 82, 202.5))
AMETHYST_JAVELIN =(new Item(Items.JAVELIN_SHAFT, 15), new Item(Items.AMETHYST_JAVELIN_HEADS, 15), new FletchableItem(new Item(Items.AMETHYST_JAVELIN, 15), 84, 202.5))
BRONZE_ARROWS =(new Item(53, 15), new Item(39, 15), new FletchableItem(new Item(882, 15), 1, 20))
DRAGON_ARROWS =(new Item(53, 15), new Item(11237, 15), new FletchableItem(new Item(11212, 15), 90, 225.0))
DRAGON_JAVELIN =(new Item(19584, 15), new Item(19582, 15), new FletchableItem(new Item(19484, 15), 92, 225.0))
IRON_ARROWS =(new Item(53, 15), new Item(40, 15), new FletchableItem(new Item(884, 15), 15, 37.5))
MITHRIL_ARROWS =(new Item(53, 15), new Item(42, 15), new FletchableItem(new Item(888, 15), 45, 112.5))
RUNE_ARROWS =(new Item(53, 15), new Item(44, 15), new FletchableItem(new Item(892, 15), 75, 187.5))
STEEL_ARROWS =(new Item(53, 15), new Item(41, 15), new FletchableItem(new Item(886, 15), 30, 7.0))
Private Attributes
final FletchableItem[] items
final Item use
final Item with
Detailed Description
Definition at line 9 of file Arrow.java.
Constructor & Destructor Documentation
Arrow()
com.runehive.content.skill.impl.fletching.impl.Arrow.Arrow (Item use, Item with, FletchableItem... items)
Definition at line 27 of file Arrow.java.
{
        this.use = use;
        this.with = with;
        this.items = items;
    }
References items, use, and with.
Referenced by load().
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.fletching.impl.Arrow.getAnimation ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 40 of file Arrow.java.
{
        return 8480;
    }
getFletchableItems()
FletchableItem[] com.runehive.content.skill.impl.fletching.impl.Arrow.getFletchableItems ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 60 of file Arrow.java.
{
        return items;
    }
References items.
getGraphics()
int com.runehive.content.skill.impl.fletching.impl.Arrow.getGraphics ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 45 of file Arrow.java.
{
        return -1;
    }
getIngredients()
Item[] com.runehive.content.skill.impl.fletching.impl.Arrow.getIngredients ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 70 of file Arrow.java.
{
        return new Item[] { use, with };
    }
References use, and with.
getProductionMessage()
String com.runehive.content.skill.impl.fletching.impl.Arrow.getProductionMessage ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 65 of file Arrow.java.
{
        return null;
    }
getUse()
Item com.runehive.content.skill.impl.fletching.impl.Arrow.getUse ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 50 of file Arrow.java.
{
        return use;
    }
References use.
getWith()
Item com.runehive.content.skill.impl.fletching.impl.Arrow.getWith ()
Implements com.runehive.content.skill.impl.fletching.Fletchable.
Definition at line 55 of file Arrow.java.
{
        return with;
    }
References with.
load()
void com.runehive.content.skill.impl.fletching.impl.Arrow.load () static
Definition at line 33 of file Arrow.java.
{
        for (Arrow cuttable : values()) {
            Fletching.addFletchable(cuttable);
        }
    }
References com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), and Arrow().
Referenced by com.runehive.content.skill.SkillRepository.load().
Member Data Documentation
ADAMANT_ARROWS
com.runehive.content.skill.impl.fletching.impl.Arrow.ADAMANT_ARROWS =(new Item(53, 15), new Item(43, 15), new FletchableItem(new Item(890, 15), 60, 150.0))
Definition at line 14 of file Arrow.java.
AMETHYST_ARROWS
com.runehive.content.skill.impl.fletching.impl.Arrow.AMETHYST_ARROWS =(new Item(53, 15), new Item(Items.AMETHYST_ARROWTIPS, 15), new FletchableItem(new Item(Items.AMETHYST_ARROW, 15), 82, 202.5))
Definition at line 17 of file Arrow.java.
AMETHYST_JAVELIN
com.runehive.content.skill.impl.fletching.impl.Arrow.AMETHYST_JAVELIN =(new Item(Items.JAVELIN_SHAFT, 15), new Item(Items.AMETHYST_JAVELIN_HEADS, 15), new FletchableItem(new Item(Items.AMETHYST_JAVELIN, 15), 84, 202.5))
Definition at line 18 of file Arrow.java.
BRONZE_ARROWS
com.runehive.content.skill.impl.fletching.impl.Arrow.BRONZE_ARROWS =(new Item(53, 15), new Item(39, 15), new FletchableItem(new Item(882, 15), 1, 20))
Definition at line 10 of file Arrow.java.
DRAGON_ARROWS
com.runehive.content.skill.impl.fletching.impl.Arrow.DRAGON_ARROWS =(new Item(53, 15), new Item(11237, 15), new FletchableItem(new Item(11212, 15), 90, 225.0))
Definition at line 16 of file Arrow.java.
DRAGON_JAVELIN
com.runehive.content.skill.impl.fletching.impl.Arrow.DRAGON_JAVELIN =(new Item(19584, 15), new Item(19582, 15), new FletchableItem(new Item(19484, 15), 92, 225.0))
Definition at line 20 of file Arrow.java.
IRON_ARROWS
com.runehive.content.skill.impl.fletching.impl.Arrow.IRON_ARROWS =(new Item(53, 15), new Item(40, 15), new FletchableItem(new Item(884, 15), 15, 37.5))
Definition at line 11 of file Arrow.java.
items
final FletchableItem [] com.runehive.content.skill.impl.fletching.impl.Arrow.items private
Definition at line 25 of file Arrow.java.
Referenced by Arrow(), and getFletchableItems().
MITHRIL_ARROWS
com.runehive.content.skill.impl.fletching.impl.Arrow.MITHRIL_ARROWS =(new Item(53, 15), new Item(42, 15), new FletchableItem(new Item(888, 15), 45, 112.5))
Definition at line 13 of file Arrow.java.
RUNE_ARROWS
com.runehive.content.skill.impl.fletching.impl.Arrow.RUNE_ARROWS =(new Item(53, 15), new Item(44, 15), new FletchableItem(new Item(892, 15), 75, 187.5))
Definition at line 15 of file Arrow.java.
STEEL_ARROWS
com.runehive.content.skill.impl.fletching.impl.Arrow.STEEL_ARROWS =(new Item(53, 15), new Item(41, 15), new FletchableItem(new Item(886, 15), 30, 7.0))
Definition at line 12 of file Arrow.java.
use
final Item com.runehive.content.skill.impl.fletching.impl.Arrow.use private
Definition at line 23 of file Arrow.java.
Referenced by Arrow(), getIngredients(), and getUse().
with
final Item com.runehive.content.skill.impl.fletching.impl.Arrow.with private
Definition at line 24 of file Arrow.java.
Referenced by Arrow(), getIngredients(), and getWith().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/fletching/impl/Arrow.java