RuneHive-Game: com.runehive.content.skill.impl.farming.CompostType Enum Reference
com.runehive.content.skill.impl.farming.CompostType Enum Reference
Public Member Functions
CompostType (int item, int produceIncrease, double protection, double exp)
double getExp ()
double getProtection ()
int produceIncrease ()
Static Public Member Functions
static CompostType forItem (int item)
Public Attributes
COMPOST =(6032, 110, 0.60, 18)
NONE =(-1, 100, 1.00, 0)
SUPERCOMPOST =(6034, 115, 0.30, 26)
ULTRACOMPOST =(21483, 120, 0.10, 32)
Private Attributes
final double exp
final int item
final int produceIncrease
final double protection
Detailed Description
Definition at line 3 of file CompostType.java.
Constructor & Destructor Documentation
CompostType()
com.runehive.content.skill.impl.farming.CompostType.CompostType (int item, int produceIncrease, double protection, double exp)
Definition at line 14 of file CompostType.java.
{
        this.item = item;
        this.produceIncrease = produceIncrease;
        this.protection = protection;
        this.exp = exp;
    }
References exp, item, produceIncrease, and protection.
Referenced by forItem().
Member Function Documentation
forItem()
CompostType com.runehive.content.skill.impl.farming.CompostType.forItem (int item) static
Definition at line 29 of file CompostType.java.
{
        for (CompostType type : values()) {
            if (type.item == item) {
                return type;
            }
        }
        return NONE;
    }
References CompostType(), item, and NONE.
Referenced by com.runehive.content.skill.impl.farming.patches.FarmingPatch.putCompost().
getExp()
double com.runehive.content.skill.impl.farming.CompostType.getExp ()
Definition at line 25 of file CompostType.java.
{
        return exp;
    }
References exp.
Referenced by com.runehive.content.skill.impl.farming.patches.FarmingPatch.putCompost().
getProtection()
double com.runehive.content.skill.impl.farming.CompostType.getProtection ()
Definition at line 21 of file CompostType.java.
{
        return protection;
    }
References protection.
produceIncrease()
int com.runehive.content.skill.impl.farming.CompostType.produceIncrease ()
Definition at line 38 of file CompostType.java.
{
        return produceIncrease;
    }
References produceIncrease.
Member Data Documentation
COMPOST
com.runehive.content.skill.impl.farming.CompostType.COMPOST =(6032, 110, 0.60, 18)
Definition at line 5 of file CompostType.java.
Referenced by com.runehive.content.skill.impl.farming.patches.FarmingPatch.inspect().
exp
final double com.runehive.content.skill.impl.farming.CompostType.exp private
Definition at line 12 of file CompostType.java.
Referenced by CompostType(), and getExp().
item
final int com.runehive.content.skill.impl.farming.CompostType.item private
Definition at line 9 of file CompostType.java.
Referenced by CompostType(), and forItem().
NONE
com.runehive.content.skill.impl.farming.CompostType.NONE =(-1, 100, 1.00, 0)
Definition at line 4 of file CompostType.java.
Referenced by forItem(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.isComposted(), com.runehive.content.skill.impl.farming.patches.FarmingPatch.putCompost(), and com.runehive.content.skill.impl.farming.patches.FarmingPatch.resetPatch().
produceIncrease
final int com.runehive.content.skill.impl.farming.CompostType.produceIncrease private
Definition at line 10 of file CompostType.java.
Referenced by CompostType(), and produceIncrease().
protection
final double com.runehive.content.skill.impl.farming.CompostType.protection private
Definition at line 11 of file CompostType.java.
Referenced by CompostType(), and getProtection().
SUPERCOMPOST
com.runehive.content.skill.impl.farming.CompostType.SUPERCOMPOST =(6034, 115, 0.30, 26)
Definition at line 6 of file CompostType.java.
Referenced by com.runehive.content.skill.impl.farming.patches.FarmingPatch.inspect().
ULTRACOMPOST
com.runehive.content.skill.impl.farming.CompostType.ULTRACOMPOST =(21483, 120, 0.10, 32)
Definition at line 7 of file CompostType.java.
Referenced by com.runehive.content.skill.impl.farming.patches.FarmingPatch.inspect().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/farming/CompostType.java