RuneHive-Game: com.runehive.game.world.entity.combat.PoisonType Enum Reference
com.runehive.game.world.entity.combat.PoisonType Enum Reference
The enumerated type whose elements represent the different levels of poison.
Public Member Functions
final int getDamage ()
Gets the starting damage for this poison type.
PoisonType (int damage)
Creates a new PoisonType.
Public Attributes
DEFAULT_MAGIC =(2)
The default poison type for magic spells.
DEFAULT_MELEE =(4)
The default poison type for melee weapons.
DEFAULT_NPC =(8)
The default poison type for poisonous NPCs.
DEFAULT_RANGED =(2)
The default poison type for ranged ammunition.
EXTRAORDINARY_NPC =(20)
self explanatory maybe?
STRONG_MELEE =(5)
The stronger poison type for melee weapons.
STRONG_NPC =(12)
The stronger poison type for poisonous NPCs.
STRONG_RANGED =(3)
The stronger poison type for ranged ammunition.
SUPER_MAGIC =(4)
The strongest poison type for magic spells.
SUPER_MELEE =(6)
The strongest poison type for melee weapons.
SUPER_NPC =(16)
The strongest poison type for poisonous NPCs.
SUPER_RANGED =(4)
The strongest poison type for ranged ammunition.
WEAK_NPC =(6)
The default poison type for poisonous NPCs.
Private Attributes
final int damage
The starting damage for this poison type.
Detailed Description
The enumerated type whose elements represent the different levels of poison.
Author
lare96 http://github.com/lare96
Definition at line 7 of file PoisonType.java.
Constructor & Destructor Documentation
PoisonType()
com.runehive.game.world.entity.combat.PoisonType.PoisonType (int damage)
Creates a new PoisonType.
Parameters
damage the starting damage for this poison type.
Definition at line 81 of file PoisonType.java.
{
        this.damage = damage;
    }
References damage.
Member Function Documentation
getDamage()
final int com.runehive.game.world.entity.combat.PoisonType.getDamage ()
Gets the starting damage for this poison type.
Returns
the starting damage.
Definition at line 89 of file PoisonType.java.
{
        return damage;
    }
References damage.
Member Data Documentation
damage
final int com.runehive.game.world.entity.combat.PoisonType.damage private
The starting damage for this poison type.
Definition at line 75 of file PoisonType.java.
Referenced by getDamage(), and PoisonType().
DEFAULT_MAGIC
com.runehive.game.world.entity.combat.PoisonType.DEFAULT_MAGIC =(2)
The default poison type for magic spells.
Definition at line 12 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBurst().
DEFAULT_MELEE
com.runehive.game.world.entity.combat.PoisonType.DEFAULT_MELEE =(4)
The default poison type for melee weapons.
Definition at line 37 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType().
DEFAULT_NPC
com.runehive.game.world.entity.combat.PoisonType.DEFAULT_NPC =(8)
The default poison type for poisonous NPCs.
Definition at line 57 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType().
DEFAULT_RANGED
com.runehive.game.world.entity.combat.PoisonType.DEFAULT_RANGED =(2)
The default poison type for ranged ammunition.
Definition at line 17 of file PoisonType.java.
EXTRAORDINARY_NPC
com.runehive.game.world.entity.combat.PoisonType.EXTRAORDINARY_NPC =(20)
self explanatory maybe?
??
Definition at line 70 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType().
STRONG_MELEE
com.runehive.game.world.entity.combat.PoisonType.STRONG_MELEE =(5)
The stronger poison type for melee weapons.
Definition at line 42 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType().
STRONG_NPC
com.runehive.game.world.entity.combat.PoisonType.STRONG_NPC =(12)
The stronger poison type for poisonous NPCs.
Definition at line 62 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType().
STRONG_RANGED
com.runehive.game.world.entity.combat.PoisonType.STRONG_RANGED =(3)
The stronger poison type for ranged ammunition.
Definition at line 22 of file PoisonType.java.
SUPER_MAGIC
com.runehive.game.world.entity.combat.PoisonType.SUPER_MAGIC =(4)
The strongest poison type for magic spells.
Definition at line 27 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.magic.MagicImpact.smokeBarrage().
SUPER_MELEE
com.runehive.game.world.entity.combat.PoisonType.SUPER_MELEE =(6)
The strongest poison type for melee weapons.
Definition at line 47 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType().
SUPER_NPC
com.runehive.game.world.entity.combat.PoisonType.SUPER_NPC =(16)
The strongest poison type for poisonous NPCs.
Definition at line 67 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType().
SUPER_RANGED
com.runehive.game.world.entity.combat.PoisonType.SUPER_RANGED =(4)
The strongest poison type for ranged ammunition.
Definition at line 32 of file PoisonType.java.
WEAK_NPC
com.runehive.game.world.entity.combat.PoisonType.WEAK_NPC =(6)
The default poison type for poisonous NPCs.
Definition at line 52 of file PoisonType.java.
Referenced by com.runehive.game.world.entity.combat.effect.impl.CombatPoisonEffect.getPoisonType(), and com.runehive.content.consume.PotionData.onAntiPoisonEffect().
The documentation for this enum was generated from the following file:
java/com/runehive/game/world/entity/combat/PoisonType.java