RuneHive-Game: com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData Enum Reference
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData Enum Reference
The jewellery data.
Public Member Functions
JewelleryData (int product, int level, double experience, JewelleryType type, Item... materials)
Constructs a new JewelleryData.
Static Public Member Functions
static Optional< JewelleryData > forItem (int item)
Gets the jewellery data based on the product item.
static int[] getItems (JewelleryType type)
Gets the product items based on the jewellery type.
static int getSize (JewelleryType type)
Gets the size of all the jewellery types.
Public Attributes
DIAMOND_AMULET =(1681, 70, 100, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1601))
DIAMOND_NECKLACE =(1662, 56, 90, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1601))
DIAMOND_RING =(1643, 43, 85, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1601))
DRAGONSTONE_AMULET =(1683, 80, 125, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1615))
DRAGONSTONE_NECKLACE =(1664, 72, 105, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1615))
DRAGONSTONE_RING =(1645, 55, 100, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1615))
EMERALD_AMULET =(1677, 31, 61, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1605))
EMERALD_NECKLACE =(1658, 29, 60, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1605))
EMERALD_RING =(1639, 27, 55, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1605))
double experience
The experience rewarded.
GOLD_AMULET =(1673, 8, 30, JewelleryType.AMULET, new Item(1595), new Item(2357))
GOLD_NECKLACE =(1654, 6, 20, JewelleryType.NECKLACE, new Item(1597), new Item(2357))
GOLD_RING =(1635, 5, 15, JewelleryType.RING, new Item(1592), new Item(2357))
int level
The level required.
Item[] materials
The materials required.
ONYX_AMULET =(6579, 90, 150, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(6573))
ONYX_NECKLACE =(6577, 82, 120, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(6573))
ONYX_RING =(6575, 67, 85, JewelleryType.RING, new Item(1592), new Item(2357), new Item(6573))
int product
The production item.
RUBY_AMULET =(1679, 50, 85, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1603))
RUBY_NECKLACE =(1660, 40, 75, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1603))
RUBY_RING =(1641, 34, 70, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1603))
SAPPHIRE_AMULET =(1675, 24, 65, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1607))
SAPPHIRE_NECKLACE =(1656, 22, 55, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1607))
SAPPHIRE_RING =(1637, 20, 40, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1607))
JewelleryType type
The jewellery type.
Detailed Description
The jewellery data.
Need to add furnace at home.
Definition at line 55 of file Jewellery.java.
Constructor & Destructor Documentation
JewelleryData()
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.JewelleryData (int product, int level, double experience, JewelleryType type, Item... materials)
Constructs a new JewelleryData.
Parameters
product The production item.
level The level required.
experience The experience rewarded.
type The jewellery type.
materials The materials required.
Definition at line 114 of file Jewellery.java.
{
            this.product = product;
            this.level = level;
            this.experience = experience;
            this.type = type;
            this.materials = materials;
        }
References experience, level, materials, product, and type.
Referenced by getItems(), and getSize().
Member Function Documentation
forItem()
Optional< JewelleryData > com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.forItem (int item) static
Gets the jewellery data based on the product item.
Parameters
item The item being searched.
Returns
The jewellery data.
Definition at line 162 of file Jewellery.java.
{
            return Arrays.stream(values()).filter(i -> i.product == item).findAny();
        }
Referenced by com.runehive.content.skill.impl.crafting.impl.Jewellery.click().
getItems()
int[] com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.getItems (JewelleryType type) static
Gets the product items based on the jewellery type.
Parameters
type The jewellery type.
Returns
The jewellery type production items.
Definition at line 144 of file Jewellery.java.
{
            int[] items = new int[getSize(type)];
            int count = 0;
            for (JewelleryData data : values()) {
                if (data.type == type) {
                    items[count] = data.product;
                    count++;
                }
            }
            return items;
        }
References getSize(), JewelleryData(), and type.
Referenced by com.runehive.content.skill.impl.crafting.impl.Jewellery.open().
getSize()
int com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.getSize (JewelleryType type) static
Gets the size of all the jewellery types.
Parameters
type The jewellery type.
Returns
The jewellery size.
Definition at line 128 of file Jewellery.java.
{
            int count = 0;
            for (JewelleryData data : values()) {
                if (data.type == type) {
                    count++;
                }
            }
            return count;
        }
References JewelleryData(), and type.
Referenced by getItems().
Member Data Documentation
DIAMOND_AMULET
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.DIAMOND_AMULET =(1681, 70, 100, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1601))
Definition at line 76 of file Jewellery.java.
DIAMOND_NECKLACE
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.DIAMOND_NECKLACE =(1662, 56, 90, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1601))
Definition at line 68 of file Jewellery.java.
DIAMOND_RING
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.DIAMOND_RING =(1643, 43, 85, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1601))
Definition at line 60 of file Jewellery.java.
DRAGONSTONE_AMULET
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.DRAGONSTONE_AMULET =(1683, 80, 125, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1615))
Definition at line 77 of file Jewellery.java.
DRAGONSTONE_NECKLACE
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.DRAGONSTONE_NECKLACE =(1664, 72, 105, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1615))
Definition at line 69 of file Jewellery.java.
DRAGONSTONE_RING
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.DRAGONSTONE_RING =(1645, 55, 100, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1615))
Definition at line 61 of file Jewellery.java.
EMERALD_AMULET
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.EMERALD_AMULET =(1677, 31, 61, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1605))
Definition at line 74 of file Jewellery.java.
EMERALD_NECKLACE
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.EMERALD_NECKLACE =(1658, 29, 60, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1605))
Definition at line 66 of file Jewellery.java.
EMERALD_RING
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.EMERALD_RING =(1639, 27, 55, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1605))
Definition at line 58 of file Jewellery.java.
experience
double com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.experience
The experience rewarded.
Definition at line 93 of file Jewellery.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), and JewelleryData().
GOLD_AMULET
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.GOLD_AMULET =(1673, 8, 30, JewelleryType.AMULET, new Item(1595), new Item(2357))
Definition at line 72 of file Jewellery.java.
GOLD_NECKLACE
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.GOLD_NECKLACE =(1654, 6, 20, JewelleryType.NECKLACE, new Item(1597), new Item(2357))
Definition at line 64 of file Jewellery.java.
GOLD_RING
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.GOLD_RING =(1635, 5, 15, JewelleryType.RING, new Item(1592), new Item(2357))
Definition at line 56 of file Jewellery.java.
level
int com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.level
The level required.
Definition at line 88 of file Jewellery.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), and JewelleryData().
materials
Item [] com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.materials
The materials required.
Definition at line 103 of file Jewellery.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), and JewelleryData().
ONYX_AMULET
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.ONYX_AMULET =(6579, 90, 150, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(6573))
Definition at line 78 of file Jewellery.java.
ONYX_NECKLACE
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.ONYX_NECKLACE =(6577, 82, 120, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(6573))
Definition at line 70 of file Jewellery.java.
ONYX_RING
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.ONYX_RING =(6575, 67, 85, JewelleryType.RING, new Item(1592), new Item(2357), new Item(6573))
Definition at line 62 of file Jewellery.java.
product
int com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.product
The production item.
Definition at line 83 of file Jewellery.java.
Referenced by com.runehive.content.skill.impl.crafting.impl.Jewellery.click(), com.runehive.content.skill.impl.crafting.impl.Jewellery.craft(), and JewelleryData().
RUBY_AMULET
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.RUBY_AMULET =(1679, 50, 85, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1603))
Definition at line 75 of file Jewellery.java.
RUBY_NECKLACE
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.RUBY_NECKLACE =(1660, 40, 75, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1603))
Definition at line 67 of file Jewellery.java.
RUBY_RING
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.RUBY_RING =(1641, 34, 70, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1603))
Definition at line 59 of file Jewellery.java.
SAPPHIRE_AMULET
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.SAPPHIRE_AMULET =(1675, 24, 65, JewelleryType.AMULET, new Item(1595), new Item(2357), new Item(1607))
Definition at line 73 of file Jewellery.java.
SAPPHIRE_NECKLACE
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.SAPPHIRE_NECKLACE =(1656, 22, 55, JewelleryType.NECKLACE, new Item(1597), new Item(2357), new Item(1607))
Definition at line 65 of file Jewellery.java.
SAPPHIRE_RING
com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.SAPPHIRE_RING =(1637, 20, 40, JewelleryType.RING, new Item(1592), new Item(2357), new Item(1607))
Definition at line 57 of file Jewellery.java.
type
JewelleryType com.runehive.content.skill.impl.crafting.impl.Jewellery.JewelleryData.type
The jewellery type.
Definition at line 98 of file Jewellery.java.
Referenced by getItems(), getSize(), and JewelleryData().
The documentation for this enum was generated from the following file:
java/com/runehive/content/skill/impl/crafting/impl/Jewellery.java