RuneHive-Game: com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction Interface Reference
com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction Interface Reference
Public Member Functions
default boolean canExecute (Player player, int level)
default void onCancellation (Player player)
default void onExecution (Player player, Position start, Position end)
default void start (Player player)
Public Member Functions inherited from com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction
default void execute (Player player, Obstacle next, Position start, Position end, int level, float experience, int ordinal)
int getAnimation ()
String getPostMessage ()
String getPreMessage ()
default boolean rewards (Player player, String course, int flags, float bonus)
Detailed Description
Definition at line 13 of file WildernessDoorInteraction.java.
Member Function Documentation
canExecute()
default boolean com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.canExecute (Player player, int level)
Implements com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.
Definition at line 21 of file WildernessDoorInteraction.java.
{
        if (player.skills.getLevel(Skill.AGILITY) < level) {
            player.dialogueFactory.sendStatement("You need an agility level of " + level + " to do this!").execute();
            return false;
        }
        GameObject object = player.attributes.get("AGILITY_OBJ", GameObject.class);
        return object != null && object.getDirection() == ObjectDirection.SOUTH;
    }
References com.runehive.game.world.entity.skill.Skill.AGILITY, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.game.world.object.ObjectDirection.SOUTH.
onCancellation()
default void com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onCancellation (Player player)
Implements com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.
Definition at line 97 of file WildernessDoorInteraction.java.
{
    }
onExecution()
default void com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onExecution (Player player, Position start, Position end)
Implements com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.
Definition at line 31 of file WildernessDoorInteraction.java.
{
        boolean entering = player.getPosition().equals(new Position(2998, 3916));
        Position destination = entering ? new Position(2998, 3930) : new Position(2998, 3917);
        Position finalDestination = entering ? new Position(2998, 3931) : new Position(2998, 3916);
//        GameObject enterDoor = player.getRegion().getGameObject(new Position(2998, 3917));
//        GameObject leavingDoor1 = player.getRegion().getGameObject(new Position(2997, 3931));
//        GameObject leavingDoor2 = player.getRegion().getGameObject(new Position(2998, 3931));
        player.face(finalDestination);
        World.schedule(new Task(2) {
            int count = 0;
            @Override
            public void execute() {
                if (player.getPosition().equals(destination)) {
                    player.mobAnimation.reset();
//                    if (entering) {
//                        leavingDoor1.rotate(Direction.EAST);
//                        leavingDoor2.rotate(Direction.SOUTH);
//                    } else {
//                        enterDoor.rotate(Direction.EAST);
//                    }
                    player.movement.walk(finalDestination);
                    return;
                }
                if (player.getPosition().equals(finalDestination)) {
                    if (entering) {
//                        leavingDoor1.rotate(Direction.WEST);
//                        leavingDoor2.rotate(Direction.WEST);
                        player.send(new SendMessage("Welcome the the wilderness agility course. Be careful :)"));
                    } else {
//                        enterDoor.rotate(Direction.WEST);
                    }
                    cancel();
                    return;
                }
                switch (count) {
                    case 0:
//                        if (entering) {
//                            enterDoor.rotate(Direction.EAST);
//                        } else {
//                            leavingDoor1.rotate(Direction.EAST);
//                            leavingDoor2.rotate(Direction.SOUTH);
//                        }
                        player.movement.walk(destination);
                        break;
                    case 1:
                        player.mobAnimation.setWalk(762);
                        player.mobAnimation.setStand(762);
                        break;
                    case 2:
//                        if (entering) {
//                            enterDoor.rotate(Direction.WEST);
//                        } else {
//                            leavingDoor1.rotate(Direction.WEST);
//                            leavingDoor2.rotate(Direction.WEST);
//                        }
                        break;
                }
                count++;
            }
        });
    }
References com.runehive.game.world.position.Position.equals(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.game.world.entity.Entity.getPosition(), com.runehive.game.world.entity.mob.Mob.mobAnimation, com.runehive.game.world.entity.mob.Mob.movement, com.runehive.game.world.entity.mob.MobAnimation.reset(), com.runehive.game.world.World.schedule(), com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.game.world.entity.mob.MobAnimation.setStand(), com.runehive.game.world.entity.mob.MobAnimation.setWalk(), start(), and com.runehive.game.world.entity.mob.movement.Movement.walk().
start()
default void com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.start (Player player)
Implements com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.
Definition at line 17 of file WildernessDoorInteraction.java.
{
    }
Referenced by onExecution().
The documentation for this interface was generated from the following file:
java/com/runehive/content/skill/impl/agility/obstacle/impl/WildernessDoorInteraction.java