RuneHive-Game: com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction Interface Reference
com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction Interface Reference
Public Member Functions
default boolean canExecute (Player player, int level)
default void execute (Player player, Obstacle next, Position start, Position end, int level, float experience, int ordinal)
int getAnimation ()
String getPostMessage ()
String getPreMessage ()
default void onCancellation (Player player)
void onExecution (Player player, Position start, Position end)
default boolean rewards (Player player, String course, int flags, float bonus)
default void start (Player player)
Detailed Description
Definition at line 26 of file ObstacleInteraction.java.
Member Function Documentation
canExecute()
default boolean com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.canExecute (Player player, int level)
Implemented in com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.
Definition at line 161 of file ObstacleInteraction.java.
{
        if (player.skills.getLevel(Skill.AGILITY) < level) {
            player.dialogueFactory.sendStatement("You need an agility level of " + level + " to do this!").execute();
            return false;
        }
        return true;
    }
References com.runehive.game.world.entity.skill.Skill.AGILITY, com.runehive.game.world.entity.mob.player.Player.dialogueFactory, com.runehive.content.dialogue.DialogueFactory.execute(), com.runehive.game.world.entity.skill.SkillManager.getLevel(), com.runehive.content.dialogue.DialogueFactory.sendStatement(), and com.runehive.game.world.entity.mob.Mob.skills.
Referenced by execute().
execute()
default void com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute (Player player, Obstacle next, Position start, Position end, int level, float experience, int ordinal)
Definition at line 40 of file ObstacleInteraction.java.
{
        if (!canExecute(player, level))
            return;
        if (player.locking.locked(LockType.MASTER))
            return;
        player.getCombat().reset();
        player.locking.lock();
        World.schedule(new Task(true, 1) {
            private final MobAnimation ANIMATION = player.mobAnimation.copy();
            private final boolean RUNNING = player.movement.isRunning();
            private boolean started = false;
            private Obstacle nextObstacle = next;
            @Override
            protected void onSchedule() {
                player.movement.setRunningToggled(false);
                if (getPreMessage() != null)
                    player.send(new SendMessage(getPreMessage()));
                start(player);
                attach(player);
            }
            @Override
            protected void execute() {
                if (nextObstacle != null && player.getPosition().equals(nextObstacle.getEnd())) {
                    if (canExecute(player, level)) {
                        nextObstacle.getType().getInteraction().start(player);
                        nextObstacle.getType().getInteraction().onExecution(player, nextObstacle.getStart(), nextObstacle.getEnd());
                        if (nextObstacle.getType().getInteraction().getPreMessage() != null)
                            player.send(new SendMessage(nextObstacle.getType().getInteraction().getPreMessage()));
                    }
                    if (nextObstacle.getNext() == null) {
                        this.cancel();
                        return;
                    }
                    nextObstacle.getType().getInteraction().onCancellation(player);
                    nextObstacle = nextObstacle.getNext();
                } else if (player.getPosition().equals(end)) {
                    if (nextObstacle != null) {
                        if (canExecute(player, level)) {
                            nextObstacle.getType().getInteraction().start(player);
                            nextObstacle.getType().getInteraction().onExecution(player, nextObstacle.getStart(), nextObstacle.getEnd());
                            if (nextObstacle.getType().getInteraction().getPreMessage() != null) {
                                player.send(new SendMessage(nextObstacle.getType().getInteraction().getPreMessage()));
                            }
                        }
                        if (nextObstacle.getNext() != null) {
                            nextObstacle.getType().getInteraction().onCancellation(player);
                            nextObstacle = nextObstacle.getNext();
                        } else {
                            this.cancel();
                            return;
                        }
                    } else {
                        this.cancel();
                        return;
                    }
                }
                if (!started) {
                    started = true;
                    onExecution(player, start, end);
                    if (ordinal > -1 && Utility.random(50) == 0) {
                        if (!Area.inWildernessResource(player) || !Area.inBarbarianCourse(player) || !Area.inGnomeCourse(player)) {
                            GroundItem.create(player, new Item(11849, 1));
                            player.send(new SendMessage("<col=C60DDE>There appears to be a wild Grace mark near you."));
                        }
                    }
                }
            }
            @Override
            protected void onCancel(boolean logout) {
                if (logout) {
                    player.move(start);
                    return;
                }
                if (getPostMessage() != null)
                    player.send(new SendMessage(getPostMessage()));
                if (experience > 0)
                    player.skills.addExperience(Skill.AGILITY, experience * 25);
                if (ordinal > -1) {
                    if (ordinal == 0) {
                        player.attributes.set("AGILITY_FLAGS", 1 << ordinal);
                    } else {
                        int i = player.attributes.get("AGILITY_FLAGS", Integer.class) | (1 << ordinal);
                        player.attributes.set("AGILITY_FLAGS", i);
                    }
                }
                if (Area.inGnomeCourse(player)) {
                    rewards(player, "Gnome Agility", Agility.GNOME_FLAGS, 39);
                } else if (Area.inBarbarianCourse(player)) {
                    rewards(player, "Barbarian Agility", Agility.BARBARIAN_FLAGS, 46.5f);
                } else if (Area.inWildernessCourse(player)) {
                    rewards(player, "Wilderness Agility", Agility.WILDERNESS_FLAGS, 498.9f);
                } else if (Area.inSeersCourse(player)) {
                    rewards(player, "Seers Agility", Agility.SEERS_FLAGS, 435);
                } else if (Area.inArdougneCourse(player)) {
                    rewards(player, "Ardougne Agility", Agility.ARDOUGNE_FLAGS, 529);
                }
                player.mobAnimation = ANIMATION;
                player.animate(new Animation(65535));
                player.updateFlags.add(UpdateFlag.APPEARANCE);
                player.movement.setRunningToggled(RUNNING);
                Position nextPosition = nextObstacle != null ? nextObstacle.getEnd() : end;
                if (!player.getPosition().equals(nextPosition)) {
                    player.move(nextPosition);
                } else {
                    int time = player.attributes.get("AGILITY_TYPE", ObstacleType.class) == ObstacleType.WILDERNESS_COURSE ? 1199 : 599;
                    player.locking.lock(time, TimeUnit.MILLISECONDS, LockType.MASTER);
                }
                onCancellation(player);
            }
        });
    }
References com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.entity.skill.Skill.AGILITY, com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.game.world.entity.mob.UpdateFlag.APPEARANCE, com.runehive.content.skill.impl.agility.Agility.ARDOUGNE_FLAGS, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.content.skill.impl.agility.Agility.BARBARIAN_FLAGS, canExecute(), com.runehive.game.world.entity.mob.MobAnimation.copy(), com.runehive.game.world.items.ground.GroundItem.create(), com.runehive.game.world.position.Position.equals(), execute(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.world.entity.mob.player.Player.getCombat(), com.runehive.content.skill.impl.agility.obstacle.Obstacle.getEnd(), com.runehive.content.skill.impl.agility.obstacle.ObstacleType.getInteraction(), com.runehive.content.skill.impl.agility.obstacle.Obstacle.getNext(), com.runehive.game.world.entity.Entity.getPosition(), getPostMessage(), getPreMessage(), com.runehive.content.skill.impl.agility.obstacle.Obstacle.getStart(), com.runehive.content.skill.impl.agility.obstacle.Obstacle.getType(), com.runehive.content.skill.impl.agility.Agility.GNOME_FLAGS, com.runehive.game.world.position.Area.inArdougneCourse(), com.runehive.game.world.position.Area.inBarbarianCourse(), com.runehive.game.world.position.Area.inGnomeCourse(), com.runehive.game.world.position.Area.inSeersCourse(), com.runehive.game.world.position.Area.inWildernessCourse(), com.runehive.game.world.position.Area.inWildernessResource(), com.runehive.game.world.entity.mob.movement.Movement.isRunning(), com.runehive.game.world.entity.mob.Locking.lock, com.runehive.game.world.entity.mob.Locking.locked(), com.runehive.game.world.entity.mob.Mob.locking, com.runehive.game.world.entity.mob.data.LockType.MASTER, com.runehive.game.world.entity.mob.Mob.mobAnimation, com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.world.entity.mob.Mob.movement, onCancellation(), onExecution(), com.runehive.util.Utility.random(), rewards(), com.runehive.game.world.World.schedule(), com.runehive.content.skill.impl.agility.Agility.SEERS_FLAGS, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), com.runehive.game.world.entity.mob.movement.Movement.setRunningToggled(), com.runehive.game.world.entity.mob.Mob.skills, start(), com.runehive.game.world.entity.mob.Mob.updateFlags, com.runehive.content.skill.impl.agility.obstacle.ObstacleType.WILDERNESS_COURSE, and com.runehive.content.skill.impl.agility.Agility.WILDERNESS_FLAGS.
Referenced by execute(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneWallClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SteppingStonesInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SwingAcrossCableInteraction.onExecution(), and com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.onExecution().
getAnimation()
int com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.getAnimation ()
Referenced by com.runehive.content.skill.impl.agility.obstacle.impl.ClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.ClimbOverInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SteppingStonesInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.SwingAcrossCableInteraction.onExecution(), com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction.start(), and com.runehive.content.skill.impl.agility.obstacle.impl.WalkInteraction.start().
getPostMessage()
String com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.getPostMessage ()
Referenced by execute().
getPreMessage()
String com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.getPreMessage ()
Referenced by execute().
onCancellation()
default void com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.onCancellation (Player player)
Implemented in com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneJumpGapInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneWallClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ClimbOverInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.RopeSwingInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SteppingStonesInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SwingAcrossCableInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.WalkInteraction, and com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.
Definition at line 38 of file ObstacleInteraction.java.
{}
Referenced by execute().
onExecution()
void com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.onExecution (Player player, Position start, Position end)
Implemented in com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneJumpGapInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneWallClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ClimbOverInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.RopeSwingInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction2, com.runehive.content.skill.impl.agility.obstacle.impl.SteppingStonesInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SwingAcrossCableInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.WalkInteraction, and com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.
References start().
Referenced by execute().
rewards()
default boolean com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.rewards (Player player, String course, int flags, float bonus)
Definition at line 169 of file ObstacleInteraction.java.
{
        int flag = player.attributes.get("AGILITY_FLAGS", Integer.class);
        if ((flag & flags) != flags) {
            return false;
        }
        player.skills.addExperience(Skill.AGILITY, bonus * Config.AGILITY_MODIFICATION);
        player.send(new SendMessage("You have completed the " + course + " course and receive 5 tickets."));
        player.forClan(channel -> channel.activateTask(ClanTaskKey.AGILITY_COURSE, player.getName()));
        player.playerAssistant.activateSkilling(1);
        RandomEventHandler.trigger(player);
        AchievementHandler.activate(player, AchievementKey.AGILITY, 1);
        player.inventory.addOrDrop(new Item(2996, 5));
        player.attributes.set("AGILITY_FLAGS", 0);
        return true;
    }
References com.runehive.content.achievement.AchievementHandler.activate(), com.runehive.game.world.entity.mob.player.PlayerAssistant.activateSkilling(), com.runehive.game.world.entity.skill.SkillManager.addExperience(), com.runehive.game.world.items.containers.inventory.Inventory.addOrDrop(), com.runehive.content.achievement.AchievementKey.AGILITY, com.runehive.game.world.entity.skill.Skill.AGILITY, com.runehive.content.clanchannel.content.ClanTaskKey.AGILITY_COURSE, com.runehive.Config.AGILITY_MODIFICATION, com.runehive.game.world.entity.mob.Mob.attributes, com.runehive.game.world.entity.mob.player.Player.forClan(), com.runehive.util.generic.GenericAttributes.get(), com.runehive.game.world.entity.mob.player.Player.getName(), com.runehive.game.world.entity.mob.player.Player.inventory, com.runehive.game.world.entity.mob.player.Player.playerAssistant, com.runehive.game.world.entity.mob.player.Player.send(), com.runehive.util.generic.GenericAttributes.set(), com.runehive.game.world.entity.mob.Mob.skills, and com.runehive.content.activity.randomevent.RandomEventHandler.trigger().
Referenced by execute().
start()
default void com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.start (Player player)
Implemented in com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneJumpGapInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneRoofJumpInteraction2, com.runehive.content.skill.impl.agility.obstacle.impl.ArdougneWallClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.ClimbOverInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.RopeSwingInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.RunningStartInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SeersClimbInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SteppingStonesInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.SwingAcrossCableInteraction, com.runehive.content.skill.impl.agility.obstacle.impl.WalkInteraction, and com.runehive.content.skill.impl.agility.obstacle.impl.WildernessDoorInteraction.
Definition at line 34 of file ObstacleInteraction.java.
{}
Referenced by execute(), com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction2.onExecution(), and onExecution().
The documentation for this interface was generated from the following file:
java/com/runehive/content/skill/impl/agility/obstacle/ObstacleInteraction.java