RuneHive-Game: com.runehive.content.skill.impl.crafting.Craftable Interface Reference
com.runehive.content.skill.impl.crafting.Craftable Interface Reference
The craftable itemcontainer.
Public Member Functions
int getAnimation ()
Gets the craftable animation.
CraftableItem[] getCraftableItems ()
Gets the craftable items.
Item[] getIngredients (int index)
Gets the craftable ingredients.
String getName ()
Gets the craftable name.
String getProductionMessage ()
Gets the craftable production message.
Item getUse ()
Gets the craftable used item.
Item getWith ()
Gets the craftable item used with.
Detailed Description
The craftable itemcontainer.
Author
Daniel
Definition at line 10 of file Craftable.java.
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.crafting.Craftable.getAnimation ()
Gets the craftable animation.
Returns
The craftable animation.
Implemented in com.runehive.content.skill.impl.crafting.impl.Gem, com.runehive.content.skill.impl.crafting.impl.Hide, and com.runehive.content.skill.impl.crafting.impl.Leather.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.craft().
getCraftableItems()
CraftableItem[] com.runehive.content.skill.impl.crafting.Craftable.getCraftableItems ()
Gets the craftable items.
Returns
The craftable items.
Implemented in com.runehive.content.skill.impl.crafting.impl.Gem, com.runehive.content.skill.impl.crafting.impl.Hide, and com.runehive.content.skill.impl.crafting.impl.Leather.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.start(), and com.runehive.content.skill.impl.crafting.Crafting.useItem().
getIngredients()
Item[] com.runehive.content.skill.impl.crafting.Craftable.getIngredients (int index)
Gets the craftable ingredients.
Parameters
index The ingredient index.
Returns
The craftable ingredients.
Implemented in com.runehive.content.skill.impl.crafting.impl.Gem, com.runehive.content.skill.impl.crafting.impl.Hide, and com.runehive.content.skill.impl.crafting.impl.Leather.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.craft(), and com.runehive.content.skill.impl.crafting.Crafting.start().
getName()
String com.runehive.content.skill.impl.crafting.Craftable.getName ()
Gets the craftable name.
Returns
The craftable name.
Implemented in com.runehive.content.skill.impl.crafting.impl.Gem, com.runehive.content.skill.impl.crafting.impl.Hide, and com.runehive.content.skill.impl.crafting.impl.Leather.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.addCraftable().
getProductionMessage()
String com.runehive.content.skill.impl.crafting.Craftable.getProductionMessage ()
Gets the craftable production message.
Returns
The craftable production message.
Implemented in com.runehive.content.skill.impl.crafting.impl.Gem, com.runehive.content.skill.impl.crafting.impl.Hide, and com.runehive.content.skill.impl.crafting.impl.Leather.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.craft().
getUse()
Item com.runehive.content.skill.impl.crafting.Craftable.getUse ()
Gets the craftable used item.
Returns
The craftable used item.
Implemented in com.runehive.content.skill.impl.crafting.impl.Gem, com.runehive.content.skill.impl.crafting.impl.Hide, and com.runehive.content.skill.impl.crafting.impl.Leather.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.useItem().
getWith()
Item com.runehive.content.skill.impl.crafting.Craftable.getWith ()
Gets the craftable item used with.
Returns
The craftable item used with.
Implemented in com.runehive.content.skill.impl.crafting.impl.Gem, com.runehive.content.skill.impl.crafting.impl.Hide, and com.runehive.content.skill.impl.crafting.impl.Leather.
Referenced by com.runehive.content.skill.impl.crafting.Crafting.addCraftable(), and com.runehive.content.skill.impl.crafting.Crafting.clickButton().
The documentation for this interface was generated from the following file:
java/com/runehive/content/skill/impl/crafting/Craftable.java