RuneHive-Game: com.runehive.game.world.object.GameObject Interface Reference
com.runehive.game.world.object.GameObject Interface Reference
Represents a game object.
Public Member Functions
boolean active ()
Determines if this object is active on the world.
int distance ()
GameObjectDefinition getDefinition ()
Gets the object definition.
ObjectDirection getDirection ()
Gets the rotation.
GenericAttributes getGenericAttributes ()
Gets the generic attributes.
default int getId ()
Gets the object id.
default int getInstancedHeight ()
ObjectType getObjectType ()
Gets the object type.
Position getPosition ()
Gets the regional location.
int length ()
Gets the length.
void register ()
Registers the game object.
void rotate (ObjectDirection direction)
void transform (int id)
void unregister ()
Unregisters the game object.
int width ()
Gets the width.
Public Member Functions inherited from com.runehive.game.world.Interactable
default int getHeight ()
default int getX ()
default int getY ()
Additional Inherited Members
Static Public Member Functions inherited from com.runehive.game.world.Interactable
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Detailed Description
Represents a game object.
Author
Michael | Chex
Definition at line 13 of file GameObject.java.
Member Function Documentation
active()
boolean com.runehive.game.world.object.GameObject.active ()
Determines if this object is active on the world.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
distance()
int com.runehive.game.world.object.GameObject.distance ()
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
getDefinition()
GameObjectDefinition com.runehive.game.world.object.GameObject.getDefinition ()
Gets the object definition.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
Referenced by getId().
getDirection()
ObjectDirection com.runehive.game.world.object.GameObject.getDirection ()
Gets the rotation.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
getGenericAttributes()
GenericAttributes com.runehive.game.world.object.GameObject.getGenericAttributes ()
Gets the generic attributes.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
getId()
default int com.runehive.game.world.object.GameObject.getId ()
Gets the object id.
Definition at line 52 of file GameObject.java.
{
        return getDefinition().getId();
    }
References getDefinition(), and com.runehive.game.world.object.GameObjectDefinition.getId().
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), com.runehive.content.wintertodt.Wintertodt.breakBrazier(), com.runehive.content.activity.impl.godwars.GodwarsActivity.clickObject(), com.runehive.content.skill.impl.construction.House.construct(), com.runehive.content.wintertodt.Wintertodt.feedBrazier(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), com.runehive.game.world.region.RegionBlock.getCustomObject(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), com.runehive.content.skill.impl.hunter.trap.TrapManager.lootTrap(), com.runehive.game.world.object.CustomGameObject.toString(), and com.runehive.game.world.object.StaticGameObject.toString().
getInstancedHeight()
default int com.runehive.game.world.object.GameObject.getInstancedHeight ()
Implemented in com.runehive.game.world.object.CustomGameObject.
Definition at line 15 of file GameObject.java.
{
        return Entity.DEFAULT_INSTANCE;
    }
References com.runehive.game.world.entity.Entity.DEFAULT_INSTANCE.
Referenced by com.runehive.game.world.object.StaticGameObject.register(), and com.runehive.game.world.object.StaticGameObject.unregister().
getObjectType()
ObjectType com.runehive.game.world.object.GameObject.getObjectType ()
Gets the object type.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
getPosition()
Position com.runehive.game.world.object.GameObject.getPosition ()
Gets the regional location.
Implements com.runehive.game.world.Interactable.
Implemented in com.runehive.game.world.object.StaticGameObject.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), com.runehive.content.wintertodt.Wintertodt.breakBrazier(), com.runehive.content.wintertodt.Wintertodt.feedBrazier(), com.runehive.content.wintertodt.Wintertodt.fixBrazier(), com.runehive.content.wintertodt.Wintertodt.lightBrazier(), and com.runehive.content.wintertodt.Wintertodt.shootFlame().
length()
int com.runehive.game.world.object.GameObject.length ()
Gets the length.
Implements com.runehive.game.world.Interactable.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
register()
void com.runehive.game.world.object.GameObject.register ()
Registers the game object.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), and com.runehive.content.wintertodt.Wintertodt.breakBrazier().
rotate()
void com.runehive.game.world.object.GameObject.rotate (ObjectDirection direction)
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
transform()
void com.runehive.game.world.object.GameObject.transform (int id)
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
unregister()
void com.runehive.game.world.object.GameObject.unregister ()
Unregisters the game object.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
Referenced by com.runehive.content.wintertodt.Wintertodt.attackPyromancers(), and com.runehive.content.wintertodt.Wintertodt.breakBrazier().
width()
int com.runehive.game.world.object.GameObject.width ()
Gets the width.
Implements com.runehive.game.world.Interactable.
Implemented in com.runehive.game.world.object.CustomGameObject, and com.runehive.game.world.object.StaticGameObject.
The documentation for this interface was generated from the following file:
java/com/runehive/game/world/object/GameObject.java