RuneHive-Game: com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction Interface Reference
com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction Interface Reference
Public Member Functions
default void onCancellation (Player player)
default void onExecution (Player player, Position start, Position end)
default void start (Player player)
Public Member Functions inherited from com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction
default boolean canExecute (Player player, int level)
default void execute (Player player, Obstacle next, Position start, Position end, int level, float experience, int ordinal)
int getAnimation ()
String getPostMessage ()
String getPreMessage ()
default boolean rewards (Player player, String course, int flags, float bonus)
Detailed Description
Definition at line 10 of file SeersJumpGapInteraction.java.
Member Function Documentation
onCancellation()
default void com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction.onCancellation (Player player)
Implements com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.
Definition at line 62 of file SeersJumpGapInteraction.java.
{
    }
onExecution()
default void com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction.onExecution (Player player, Position start, Position end)
Implements com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.
Definition at line 17 of file SeersJumpGapInteraction.java.
{
        player.face(start);
        World.schedule(new Task(true, 1) {
            int ticks = 0;
            @Override
            public void execute() {
                switch (ticks++) {
                    case 1:
                        player.animate(new Animation(2586));
                        break;
                    case 2:
                        player.animate(new Animation(2588));
                        player.move(new Position(start.getX() - 2, start.getY(), 1));
                        break;
                    case 4:
                        player.move(end);
                        player.animate(new Animation(2588));
                        cancel();
                        break;
                }
            }
        });
//        TaskQueue.queue(new Task(player, 1, true) {
//            int ticks = 0;
//            @Override
//            public void execute() {
//                switch (ticks++) {
//                    case 1:
//                        player.getUpdateFlags().sendAnimation(new Animation(2586));
//                        break;
//                    case 2:
//                        player.getUpdateFlags().sendAnimation(new Animation(2588));
//                        player.teleport(new Location(start.getX() - 2, start.getY(), 2));
//                        break;
//                    case 4:
//                        player.teleport(end);
//                        player.getUpdateFlags().sendAnimation(new Animation(2588));
//                        stop();
//                        break;
//                }
//            }
//        });
    }
References com.runehive.game.world.entity.mob.Mob.animate(), com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.execute(), com.runehive.game.world.entity.mob.Mob.face(), com.runehive.game.world.entity.mob.Mob.move(), com.runehive.game.world.World.schedule(), and start().
start()
default void com.runehive.content.skill.impl.agility.obstacle.impl.SeersJumpGapInteraction.start (Player player)
Implements com.runehive.content.skill.impl.agility.obstacle.ObstacleInteraction.
Definition at line 12 of file SeersJumpGapInteraction.java.
{
//        player.getUpdateFlags().sendFaceToDirection(player.getX() - 1, player.getY());
    }
Referenced by onExecution().
The documentation for this interface was generated from the following file:
java/com/runehive/content/skill/impl/agility/obstacle/impl/SeersJumpGapInteraction.java