RuneHive-Game: com.runehive.game.world.Interactable Interface Reference
com.runehive.game.world.Interactable Interface Reference
An object implementing Interactable has uses.
Public Member Functions
default int getHeight ()
Position getPosition ()
default int getX ()
default int getY ()
int length ()
int width ()
Static Public Member Functions
static Interactable create (Position position)
Creates a new instance of an Interactable.
static Interactable create (Position position, int width, int length)
Creates a new instance of an Interactable.
Detailed Description
An object implementing Interactable has uses.
Author
Michael | Chex
Definition at line 10 of file Interactable.java.
Member Function Documentation
create() [1/2]
Interactable com.runehive.game.world.Interactable.create (Position position) static
Creates a new instance of an Interactable.
Parameters
position the position.
Returns
a new instance
Definition at line 42 of file Interactable.java.
{
        return new Interactable() {
            @Override
            public Position getPosition() {
                return position;
            }
            @Override
            public int width() {
                return 1;
            }
            @Override
            public int length() {
                return 1;
            }
        };
    }
References getPosition(), length(), and width().
Referenced by com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.addWalks(), com.runehive.game.world.pathfinding.path.impl.DijkstraPathFinder.find(), com.runehive.game.world.entity.mob.movement.waypoint.PickupWaypoint.PickupWaypoint(), com.runehive.game.world.entity.mob.Mob.walkExactlyTo(), com.runehive.game.world.entity.mob.Mob.walkTo(), com.runehive.util.Utility.within(), and com.runehive.content.activity.impl.kraken.KrakenActivityListener.withinDistance().
create() [2/2]
Interactable com.runehive.game.world.Interactable.create (Position position, int width, int length) static
Creates a new instance of an Interactable.
Parameters
position the position.
width the width
length the length
Returns
a new instance
Definition at line 69 of file Interactable.java.
{
        return new Interactable() {
            @Override
            public Position getPosition() {
                return position;
            }
            @Override
            public int width() {
                return width;
            }
            @Override
            public int length() {
                return length;
            }
        };
    }
References getPosition(), length(), and width().
getHeight()
default int com.runehive.game.world.Interactable.getHeight ()
Returns
the z coordinate of the getPosition()
Implemented in com.runehive.game.world.entity.Entity.
Definition at line 26 of file Interactable.java.
{
        return getPosition().getHeight();
    }
References com.runehive.game.world.position.Position.getHeight(), and getPosition().
Referenced by com.runehive.game.world.object.StaticGameObject.active(), com.runehive.game.world.pathfinding.path.impl.AStarPathFinder.find(), com.runehive.game.world.object.StaticGameObject.register(), com.runehive.game.world.region.Region.skip(), com.runehive.game.world.object.StaticGameObject.unregister(), and com.runehive.util.Utility.withinViewingDistance().
getPosition()
Position com.runehive.game.world.Interactable.getPosition ()
Returns
the current location
Implemented in com.runehive.content.combat.cannon.Cannon, com.runehive.game.world.entity.Entity, com.runehive.game.world.object.GameObject, and com.runehive.game.world.object.StaticGameObject.
Referenced by com.runehive.game.world.pathfinding.path.SimplePathChecker.checkLine(), com.runehive.game.world.pathfinding.path.SimplePathChecker.checkLine(), com.runehive.game.world.pathfinding.path.SimplePathChecker.checkProjectile(), create(), create(), com.runehive.game.world.pathfinding.path.PathFinder.find(), com.runehive.util.Utility.findAccessableTile(), com.runehive.util.Utility.findBestInside(), com.runehive.util.Utility.fixInsidePosition(), com.runehive.util.Utility.getBoundaries(), com.runehive.util.Utility.getDelta(), com.runehive.util.Utility.getDistance(), com.runehive.util.Utility.getDistance(), getHeight(), com.runehive.util.Utility.getInnerBoundaries(), getX(), getY(), com.runehive.game.world.position.Area.inArea(), com.runehive.util.Utility.inside(), com.runehive.util.Utility.inside(), com.runehive.game.world.region.Region.reachable(), com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.traversable(), com.runehive.util.Utility.within(), com.runehive.util.Utility.withinDistance(), com.runehive.util.Utility.withinOctal(), and com.runehive.util.Utility.withinViewingDistance().
getX()
default int com.runehive.game.world.Interactable.getX ()
Returns
the x coordinate of the getPosition()
Implemented in com.runehive.game.world.entity.Entity.
Definition at line 16 of file Interactable.java.
                       {
        return getPosition().getX();
    }
References getPosition(), and com.runehive.game.world.position.Position.getX().
Referenced by com.runehive.util.Utility.findBestInside(), com.runehive.util.Utility.getDistance(), com.runehive.util.Utility.inRange(), and com.runehive.util.Utility.withinViewingDistance().
getY()
default int com.runehive.game.world.Interactable.getY ()
Returns
the y coordinate of the getPosition()
Implemented in com.runehive.game.world.entity.Entity.
Definition at line 21 of file Interactable.java.
                       {
        return getPosition().getY();
    }
References getPosition(), and com.runehive.game.world.position.Position.getY().
Referenced by com.runehive.util.Utility.findBestInside(), com.runehive.util.Utility.getDistance(), com.runehive.util.Utility.inRange(), and com.runehive.util.Utility.withinViewingDistance().
length()
int com.runehive.game.world.Interactable.length ()
Returns
the length
Implemented in com.runehive.game.world.entity.Entity, com.runehive.game.world.object.CustomGameObject, com.runehive.game.world.object.GameObject, and com.runehive.game.world.object.StaticGameObject.
Referenced by com.runehive.game.world.pathfinding.path.SimplePathChecker.checkProjectile(), create(), create(), com.runehive.game.world.pathfinding.path.PathFinder.find(), com.runehive.util.Utility.findAccessableTile(), com.runehive.util.Utility.findBestInside(), com.runehive.util.Utility.fixInsidePosition(), com.runehive.util.Utility.getBoundaries(), com.runehive.util.Utility.getDelta(), com.runehive.util.Utility.getDistance(), com.runehive.util.Utility.getDistance(), com.runehive.util.Utility.getInnerBoundaries(), com.runehive.util.Utility.inside(), com.runehive.util.Utility.inside(), com.runehive.util.Utility.isLarger(), com.runehive.game.world.region.Region.reachable(), com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.traversable(), com.runehive.util.Utility.within(), com.runehive.util.Utility.withinDistance(), com.runehive.util.Utility.withinOctal(), and com.runehive.util.Utility.withinViewingDistance().
width()
int com.runehive.game.world.Interactable.width ()
Returns
the width
Implemented in com.runehive.game.world.entity.Entity, com.runehive.game.world.object.CustomGameObject, com.runehive.game.world.object.GameObject, and com.runehive.game.world.object.StaticGameObject.
Referenced by com.runehive.game.world.pathfinding.path.SimplePathChecker.checkLine(), com.runehive.game.world.pathfinding.path.SimplePathChecker.checkLine(), com.runehive.game.world.pathfinding.path.SimplePathChecker.checkProjectile(), create(), create(), com.runehive.game.world.pathfinding.path.PathFinder.find(), com.runehive.util.Utility.findAccessableTile(), com.runehive.util.Utility.findBestInside(), com.runehive.util.Utility.fixInsidePosition(), com.runehive.util.Utility.getBoundaries(), com.runehive.util.Utility.getDelta(), com.runehive.util.Utility.getDistance(), com.runehive.util.Utility.getDistance(), com.runehive.util.Utility.getInnerBoundaries(), com.runehive.util.Utility.inRange(), com.runehive.util.Utility.inside(), com.runehive.util.Utility.inside(), com.runehive.util.Utility.isLarger(), com.runehive.game.world.region.Region.reachable(), com.runehive.game.world.pathfinding.path.impl.SimplePathFinder.traversable(), com.runehive.util.Utility.within(), com.runehive.util.Utility.withinDistance(), com.runehive.util.Utility.withinOctal(), and com.runehive.util.Utility.withinViewingDistance().
The documentation for this interface was generated from the following file:
java/com/runehive/game/world/Interactable.java