RuneHive-Game: com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob > Interface Template Reference
com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob > Interface Template Reference
A combat attack is used to describe what the attacking and defending mobs should do in each stage of combat.
Public Member Functions
void attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
void block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
boolean canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
boolean canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
void finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
void finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
void hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
void hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
default void init (T attacker, Mob defender)
Called when the strategy initializes.
void onDamage (T defender, Hit hit)
void onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
void onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
default void performChecks (T attacker, Mob defender)
void preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
void preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
void start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
boolean withinDistance (T attacker, Mob defender)
Public Member Functions inherited from com.runehive.game.world.entity.combat.FormulaModifier< T extends Mob >
default int modifyAccuracy (T attacker, Mob defender, int roll)
default int modifyAggressive (T attacker, Mob defender, int roll)
default int modifyAggressiveBonus (T attacker, Mob defender, int bonus)
default int modifyAttackLevel (T attacker, Mob defender, int level)
default int modifyDamage (T attacker, Mob defender, int damage)
default int modifyDefenceLevel (Mob attacker, T defender, int level)
default int modifyDefensive (Mob attacker, T defender, int roll)
default int modifyDefensiveBonus (Mob attacker, T defender, int bonus)
default int modifyMagicLevel (T attacker, Mob defender, int level)
default int modifyOffensiveBonus (T attacker, Mob defender, int bonus)
default int modifyRangedLevel (T attacker, Mob defender, int level)
default int modifyStrengthLevel (T attacker, Mob defender, int level)
Detailed Description
A combat attack is used to describe what the attacking and defending mobs should do in each stage of combat.
Author
Michael | Chex
Definition at line 14 of file CombatListener.java.
Member Function Documentation
attack()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.attack (T attacker, Mob defender, Hit hit)
Called when the attacking hit executes on the defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit to apply
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
References hit().
block()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.block (Mob attacker, T defender, Hit hit, CombatType combatType)
Called when the defending mob blocks a hit from the attacker.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit being applied
combatType the combat type for this hit
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
References hit().
canAttack()
boolean com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.canAttack (T attacker, Mob defender)
Checks if the attacker can attack the defender.
Parameters
attacker the attacking mob
defender the defending mob
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
canOtherAttack()
boolean com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.canOtherAttack (Mob attacker, T defender)
Checks if the attacker can attack the defender.
Parameters
attacker the attacking mob
defender the defending mob
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
finishIncoming()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.finishIncoming (Mob attacker, T defender)
Called when the attacking mob finishes their strategy's attack.
Parameters
attacker the attacking mob
defender the defending mob
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
finishOutgoing()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.finishOutgoing (T attacker, Mob defender)
Called when the defending mob finishes their strategy's attack.
Parameters
attacker the attacking mob
defender the defending mob
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
hit()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.hit (T attacker, Mob defender, Hit hit)
Called when the attacking mob performs an attack on the defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit to apply
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
References hit().
Referenced by attack(), block(), hit(), hitsplat(), onDamage(), onDeath(), onKill(), preDeath(), and preKill().
hitsplat()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.hitsplat (T attacker, Mob defender, Hit hit)
Called when attacker does the hitsplat.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
References hit().
init()
default void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.init (T attacker, Mob defender)
Called when the strategy initializes.
Parameters
attacker the attacking mob
defender the defending mob
Definition at line 40 of file CombatListener.java.
{}
onDamage()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.onDamage (T defender, Hit hit)
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
References hit().
onDeath()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.onDeath (Mob attacker, T defender, Hit hit)
Called when the defending mob dies.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
References hit().
onKill()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.onKill (T attacker, Mob defender, Hit hit)
Called when attacker killed defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
References hit().
performChecks()
default void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.performChecks (T attacker, Mob defender)
Definition at line 142 of file CombatListener.java.
{
    }
preDeath()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.preDeath (Mob attacker, T defender, Hit hit)
Called right before the defending mob dies.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
References hit().
preKill()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.preKill (Mob attacker, Mob defender, Hit hit)
Called before attacker killed defender.
Parameters
attacker the attacking mob
defender the defending mob
hit the hit that killed the defender
Implemented in com.runehive.content.activity.ActivityListener< T extends Activity >, com.runehive.content.activity.impl.duelarena.DuelArenaListener, com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >, and com.runehive.game.world.entity.combat.strategy.npc.MultiStrategy.
References hit().
start()
void com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.start (T attacker, Mob defender, Hit[] hits)
Called when the strategy starts.
Parameters
attacker the attacking mob
defender the defending mob
Implemented in com.runehive.game.world.entity.combat.strategy.CombatStrategy< T extends Mob >.
withinDistance()
boolean com.runehive.game.world.entity.combat.attack.listener.CombatListener< T extends Mob >.withinDistance (T attacker, Mob defender)
Implemented in com.runehive.game.world.entity.combat.strategy.basic.MagicStrategy< T extends Mob >, com.runehive.game.world.entity.combat.strategy.basic.MeleeStrategy< T extends Mob >, and com.runehive.game.world.entity.combat.strategy.basic.RangedStrategy< T extends Mob >.
The documentation for this interface was generated from the following file:
java/com/runehive/game/world/entity/combat/attack/listener/CombatListener.java