RuneHive-Game: com.runehive.content.skill.impl.smithing.SmithingTable Interface Reference
com.runehive.content.skill.impl.smithing.SmithingTable Interface Reference
Classes
enum AdamantTable
The table for the adamant items.
enum BronzeTable
The table for the bronze items.
enum IronTable
The table for the iron items.
enum MithrilTable
The table for the mithril items.
enum RuniteTable
The table for the rune items.
enum SteelTable
The table for the steel items.
Public Member Functions
Item getBar ()
The item identification for the bar used to forge the table of items.
int getBarsRequired ()
The bars required for smithing this bar.
double getExperience ()
The experience gained upon smithing this bar.
int getLevelRequirement ()
The level requirement for smithing this bar.
String getName ()
The name of the producable item.
Item getProduced ()
The produced item for smithing this bar.
Detailed Description
Definition at line 6 of file SmithingTable.java.
Member Function Documentation
getBar()
Item com.runehive.content.skill.impl.smithing.SmithingTable.getBar ()
The item identification for the bar used to forge the table of items.
Returns
the item object.
Implemented in com.runehive.content.skill.impl.smithing.SmithingTable.AdamantTable, com.runehive.content.skill.impl.smithing.SmithingTable.BronzeTable, com.runehive.content.skill.impl.smithing.SmithingTable.IronTable, com.runehive.content.skill.impl.smithing.SmithingTable.MithrilTable, com.runehive.content.skill.impl.smithing.SmithingTable.RuniteTable, and com.runehive.content.skill.impl.smithing.SmithingTable.SteelTable.
Referenced by com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface().
getBarsRequired()
int com.runehive.content.skill.impl.smithing.SmithingTable.getBarsRequired ()
The bars required for smithing this bar.
Returns
the numerical value.
Implemented in com.runehive.content.skill.impl.smithing.SmithingTable.AdamantTable, com.runehive.content.skill.impl.smithing.SmithingTable.BronzeTable, com.runehive.content.skill.impl.smithing.SmithingTable.IronTable, com.runehive.content.skill.impl.smithing.SmithingTable.MithrilTable, com.runehive.content.skill.impl.smithing.SmithingTable.RuniteTable, and com.runehive.content.skill.impl.smithing.SmithingTable.SteelTable.
Referenced by com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface().
getExperience()
double com.runehive.content.skill.impl.smithing.SmithingTable.getExperience ()
The experience gained upon smithing this bar.
Returns
the numerical value.
Implemented in com.runehive.content.skill.impl.smithing.SmithingTable.AdamantTable, com.runehive.content.skill.impl.smithing.SmithingTable.BronzeTable, com.runehive.content.skill.impl.smithing.SmithingTable.IronTable, com.runehive.content.skill.impl.smithing.SmithingTable.MithrilTable, com.runehive.content.skill.impl.smithing.SmithingTable.RuniteTable, and com.runehive.content.skill.impl.smithing.SmithingTable.SteelTable.
getLevelRequirement()
int com.runehive.content.skill.impl.smithing.SmithingTable.getLevelRequirement ()
The level requirement for smithing this bar.
Returns
the numerical value.
Implemented in com.runehive.content.skill.impl.smithing.SmithingTable.AdamantTable, com.runehive.content.skill.impl.smithing.SmithingTable.BronzeTable, com.runehive.content.skill.impl.smithing.SmithingTable.IronTable, com.runehive.content.skill.impl.smithing.SmithingTable.MithrilTable, com.runehive.content.skill.impl.smithing.SmithingTable.RuniteTable, and com.runehive.content.skill.impl.smithing.SmithingTable.SteelTable.
Referenced by com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface().
getName()
String com.runehive.content.skill.impl.smithing.SmithingTable.getName ()
The name of the producable item.
Returns
the alphabetic value.
Implemented in com.runehive.content.skill.impl.smithing.SmithingTable.AdamantTable, com.runehive.content.skill.impl.smithing.SmithingTable.BronzeTable, com.runehive.content.skill.impl.smithing.SmithingTable.IronTable, com.runehive.content.skill.impl.smithing.SmithingTable.MithrilTable, com.runehive.content.skill.impl.smithing.SmithingTable.RuniteTable, and com.runehive.content.skill.impl.smithing.SmithingTable.SteelTable.
Referenced by com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface().
getProduced()
Item com.runehive.content.skill.impl.smithing.SmithingTable.getProduced ()
The produced item for smithing this bar.
Returns
the item object.
Implemented in com.runehive.content.skill.impl.smithing.SmithingTable.AdamantTable, com.runehive.content.skill.impl.smithing.SmithingTable.BronzeTable, com.runehive.content.skill.impl.smithing.SmithingTable.IronTable, com.runehive.content.skill.impl.smithing.SmithingTable.MithrilTable, com.runehive.content.skill.impl.smithing.SmithingTable.RuniteTable, and com.runehive.content.skill.impl.smithing.SmithingTable.SteelTable.
Referenced by com.runehive.content.skill.impl.smithing.SmithingArmour.forge(), and com.runehive.content.skill.impl.smithing.SmithingArmour.openInterface().
The documentation for this interface was generated from the following file:
java/com/runehive/content/skill/impl/smithing/SmithingTable.java