RuneHive-Game: com.runehive.content.skill.impl.fletching.Fletchable Interface Reference
com.runehive.content.skill.impl.fletching.Fletchable Interface Reference
Public Member Functions
int getAnimation ()
FletchableItem[] getFletchableItems ()
int getGraphics ()
Item[] getIngredients ()
String getProductionMessage ()
Item getUse ()
Item getWith ()
Detailed Description
Definition at line 5 of file Fletchable.java.
Member Function Documentation
getAnimation()
int com.runehive.content.skill.impl.fletching.Fletchable.getAnimation ()
Implemented in com.runehive.content.skill.impl.fletching.impl.Arrow, com.runehive.content.skill.impl.fletching.impl.Battlestaff, com.runehive.content.skill.impl.fletching.impl.Bolt, com.runehive.content.skill.impl.fletching.impl.Carvable, com.runehive.content.skill.impl.fletching.impl.Crossbow, com.runehive.content.skill.impl.fletching.impl.Featherable, and com.runehive.content.skill.impl.fletching.impl.Stringable.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch().
getFletchableItems()
FletchableItem[] com.runehive.content.skill.impl.fletching.Fletchable.getFletchableItems ()
Implemented in com.runehive.content.skill.impl.fletching.impl.Arrow, com.runehive.content.skill.impl.fletching.impl.Battlestaff, com.runehive.content.skill.impl.fletching.impl.Bolt, com.runehive.content.skill.impl.fletching.impl.Carvable, com.runehive.content.skill.impl.fletching.impl.Crossbow, com.runehive.content.skill.impl.fletching.impl.Featherable, and com.runehive.content.skill.impl.fletching.impl.Stringable.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.start(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
getGraphics()
int com.runehive.content.skill.impl.fletching.Fletchable.getGraphics ()
Implemented in com.runehive.content.skill.impl.fletching.impl.Arrow, com.runehive.content.skill.impl.fletching.impl.Battlestaff, com.runehive.content.skill.impl.fletching.impl.Bolt, com.runehive.content.skill.impl.fletching.impl.Carvable, com.runehive.content.skill.impl.fletching.impl.Crossbow, com.runehive.content.skill.impl.fletching.impl.Featherable, and com.runehive.content.skill.impl.fletching.impl.Stringable.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch().
getIngredients()
Item[] com.runehive.content.skill.impl.fletching.Fletchable.getIngredients ()
Implemented in com.runehive.content.skill.impl.fletching.impl.Arrow, com.runehive.content.skill.impl.fletching.impl.Battlestaff, com.runehive.content.skill.impl.fletching.impl.Bolt, com.runehive.content.skill.impl.fletching.impl.Carvable, com.runehive.content.skill.impl.fletching.impl.Crossbow, com.runehive.content.skill.impl.fletching.impl.Featherable, and com.runehive.content.skill.impl.fletching.impl.Stringable.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch(), and com.runehive.content.skill.impl.fletching.Fletching.start().
getProductionMessage()
String com.runehive.content.skill.impl.fletching.Fletchable.getProductionMessage ()
Implemented in com.runehive.content.skill.impl.fletching.impl.Arrow, com.runehive.content.skill.impl.fletching.impl.Battlestaff, com.runehive.content.skill.impl.fletching.impl.Bolt, com.runehive.content.skill.impl.fletching.impl.Carvable, com.runehive.content.skill.impl.fletching.impl.Crossbow, com.runehive.content.skill.impl.fletching.impl.Featherable, and com.runehive.content.skill.impl.fletching.impl.Stringable.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.fletch().
getUse()
Item com.runehive.content.skill.impl.fletching.Fletchable.getUse ()
Implemented in com.runehive.content.skill.impl.fletching.impl.Arrow, com.runehive.content.skill.impl.fletching.impl.Battlestaff, com.runehive.content.skill.impl.fletching.impl.Bolt, com.runehive.content.skill.impl.fletching.impl.Carvable, com.runehive.content.skill.impl.fletching.impl.Crossbow, com.runehive.content.skill.impl.fletching.impl.Featherable, and com.runehive.content.skill.impl.fletching.impl.Stringable.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.start(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
getWith()
Item com.runehive.content.skill.impl.fletching.Fletchable.getWith ()
Implemented in com.runehive.content.skill.impl.fletching.impl.Arrow, com.runehive.content.skill.impl.fletching.impl.Battlestaff, com.runehive.content.skill.impl.fletching.impl.Bolt, com.runehive.content.skill.impl.fletching.impl.Carvable, com.runehive.content.skill.impl.fletching.impl.Crossbow, com.runehive.content.skill.impl.fletching.impl.Featherable, and com.runehive.content.skill.impl.fletching.impl.Stringable.
Referenced by com.runehive.content.skill.impl.fletching.Fletching.addFletchable(), com.runehive.content.skill.impl.fletching.Fletching.start(), and com.runehive.content.skill.impl.fletching.Fletching.useItem().
The documentation for this interface was generated from the following file:
java/com/runehive/content/skill/impl/fletching/Fletchable.java