RuneHive-Game: com.runehive.content.skill.impl.farming.plants.Plant Interface Reference
com.runehive.content.skill.impl.farming.plants.Plant Interface Reference
Public Member Functions
int getEndingState ()
int getFlowerProtect ()
int getGrowthTime ()
int getHarvestId ()
double getHarvestXp ()
String[][] getInspectMessages ()
int getLevelRequired ()
int[] getPaymentToWatch ()
double getPlantingXp ()
String getProductType ()
int getSeedAmount ()
int getSeedId ()
int getStartingState ()
Detailed Description
Definition at line 3 of file Plant.java.
Member Function Documentation
getEndingState()
int com.runehive.content.skill.impl.farming.plants.Plant.getEndingState ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getFlowerProtect()
int com.runehive.content.skill.impl.farming.plants.Plant.getFlowerProtect ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getGrowthTime()
int com.runehive.content.skill.impl.farming.plants.Plant.getGrowthTime ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getHarvestId()
int com.runehive.content.skill.impl.farming.plants.Plant.getHarvestId ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getHarvestXp()
double com.runehive.content.skill.impl.farming.plants.Plant.getHarvestXp ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getInspectMessages()
String[][] com.runehive.content.skill.impl.farming.plants.Plant.getInspectMessages ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getLevelRequired()
int com.runehive.content.skill.impl.farming.plants.Plant.getLevelRequired ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
Referenced by com.runehive.content.skill.impl.farming.patches.FarmingPatch.plantSeed().
getPaymentToWatch()
int[] com.runehive.content.skill.impl.farming.plants.Plant.getPaymentToWatch ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getPlantingXp()
double com.runehive.content.skill.impl.farming.plants.Plant.getPlantingXp ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getProductType()
String com.runehive.content.skill.impl.farming.plants.Plant.getProductType ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
getSeedAmount()
int com.runehive.content.skill.impl.farming.plants.Plant.getSeedAmount ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
Referenced by com.runehive.content.skill.impl.farming.patches.FarmingPatch.plantSeed().
getSeedId()
int com.runehive.content.skill.impl.farming.plants.Plant.getSeedId ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
Referenced by com.runehive.content.skill.impl.farming.patches.FarmingPatch.plantSeed().
getStartingState()
int com.runehive.content.skill.impl.farming.plants.Plant.getStartingState ()
Implemented in com.runehive.content.skill.impl.farming.plants.Allotment, com.runehive.content.skill.impl.farming.plants.Flower, and com.runehive.content.skill.impl.farming.plants.Herb.
The documentation for this interface was generated from the following file:
java/com/runehive/content/skill/impl/farming/plants/Plant.java