RuneHive-Game: com.runehive.content.skill.impl.magic.spell.Spell Interface Reference
com.runehive.content.skill.impl.magic.spell.Spell Interface Reference
The itemcontainer for casting a spell.
Public Member Functions
void execute (Player player, Item item)
Executes the magic spell.
int getLevel ()
Gets the level required to cast spell.
String getName ()
Gets the name of the spell.
Item[] getRunes ()
Gets the runes required to cast the spell.
Detailed Description
The itemcontainer for casting a spell.
Author
Daniel
Definition at line 11 of file Spell.java.
Member Function Documentation
execute()
void com.runehive.content.skill.impl.magic.spell.Spell.execute (Player player, Item item)
Executes the magic spell.
Implemented in com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas, com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches, com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy, com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy, com.runehive.content.skill.impl.magic.spell.impl.SuperHeat, and com.runehive.content.skill.impl.magic.spell.impl.Vengeance.
getLevel()
int com.runehive.content.skill.impl.magic.spell.Spell.getLevel ()
Gets the level required to cast spell.
Implemented in com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas, com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches, com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy, com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy, com.runehive.content.skill.impl.magic.spell.impl.SuperHeat, and com.runehive.content.skill.impl.magic.spell.impl.Vengeance.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.cast().
getName()
String com.runehive.content.skill.impl.magic.spell.Spell.getName ()
Gets the name of the spell.
Implemented in com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas, com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches, com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy, com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy, com.runehive.content.skill.impl.magic.spell.impl.SuperHeat, and com.runehive.content.skill.impl.magic.spell.impl.Vengeance.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.cast().
getRunes()
Item[] com.runehive.content.skill.impl.magic.spell.Spell.getRunes ()
Gets the runes required to cast the spell.
Implemented in com.runehive.content.skill.impl.magic.spell.impl.BonesToBananas, com.runehive.content.skill.impl.magic.spell.impl.BonesToPeaches, com.runehive.content.skill.impl.magic.spell.impl.HighAlchemy, com.runehive.content.skill.impl.magic.spell.impl.LowAlchemy, com.runehive.content.skill.impl.magic.spell.impl.SuperHeat, and com.runehive.content.skill.impl.magic.spell.impl.Vengeance.
Referenced by com.runehive.content.skill.impl.magic.spell.SpellCasting.cast().
The documentation for this interface was generated from the following file:
java/com/runehive/content/skill/impl/magic/spell/Spell.java